### ISSUE TITLE
New device:MES1124MB AC 28-port 100M/1G

### ISSUE THREAD

**Issue by hrtrd** [librenms/librenms#10029]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
show system 
System Description:                       MES1124MB AC 28-port 100M/1G Managed Switch
System Up Time (days,hour:min:sec):       39,22:10:18
System Contact:                           xxxxx
System Name:                              Office-as1
System Location:                          Office
System MAC Address:                       e0:d9:e3:ac:62:c0
System Object ID:                         1.3.6.1.4.1.35265.1.52

./discovery.php -h HOSTNAME -d | ./pbin.sh
https://p.libren.ms/view/8d8387cd

./poller.php -h HOSTNAME -r -f -d | ./pbin.sh
https://p.libren.ms/view/2bee57fd

snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh
i think doestn work

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by hrtrd** [comment]
Download MIB's files, try add with script, got some errors
MIB search path: /opt/librenms/mibs:/opt/librenms/mibs/eltex
Cannot find module (TB): At line 1 in (none)
Did not find 'DisplayString' in module SNMPv2-TC (/opt/librenms/mibs/SNMPv2-MIB)
Did not find 'TestAndIncr' in module SNMPv2-TC (/opt/librenms/mibs/SNMPv2-MIB)
Did not find 'TimeStamp' in module SNMPv2-TC (/opt/librenms/mibs/SNMPv2-MIB)
Did not find 'DisplayString' in module SNMPv2-TC (/opt/librenms/mibs/IF-MIB)
Did not find 'PhysAddress' in module SNMPv2-TC (/opt/librenms/mibs/IF-MIB)
Did not find 'TruthValue' in module SNMPv2-TC (/opt/librenms/mibs/IF-MIB)
Did not find 'RowStatus' in module SNMPv2-TC (/opt/librenms/mibs/IF-MIB)
Did not find 'TimeStamp' in module SNMPv2-TC (/opt/librenms/mibs/IF-MIB)
Did not find 'AutonomousType' in module SNMPv2-TC (/opt/librenms/mibs/IF-MIB)
Did not find 'TestAndIncr' in module SNMPv2-TC (/opt/librenms/mibs/IF-MIB)
Did not find 'PhysAddress' in module SNMPv2-TC (/opt/librenms/mibs/eltex/IP-MIB)
Did not find 'TruthValue' in module SNMPv2-TC (/opt/librenms/mibs/eltex/IP-MIB)
Did not find 'TimeStamp' in module SNMPv2-TC (/opt/librenms/mibs/eltex/IP-MIB)
Did not find 'RowPointer' in module SNMPv2-TC (/opt/librenms/mibs/eltex/IP-MIB)
Did not find 'TestAndIncr' in module SNMPv2-TC (/opt/librenms/mibs/eltex/IP-MIB)
Did not find 'RowStatus' in module SNMPv2-TC (/opt/librenms/mibs/eltex/IP-MIB)
Did not find 'StorageType' in module SNMPv2-TC (/opt/librenms/mibs/eltex/IP-MIB)
Did not find 'DisplayString' in module SNMPv2-TC (/opt/librenms/mibs/HOST-RESOURCES-MIB)
Did not find 'TruthValue' in module SNMPv2-TC (/opt/librenms/mibs/HOST-RESOURCES-MIB)
Did not find 'DateAndTime' in module SNMPv2-TC (/opt/librenms/mibs/HOST-RESOURCES-MIB)
Did not find 'AutonomousType' in module SNMPv2-TC (/opt/librenms/mibs/HOST-RESOURCES-MIB)
Did not find 'TimeStamp' in module SNMPv2-TC (/opt/librenms/mibs/NOTIFICATION-LOG-MIB)
Did not find 'DateAndTime' in module SNMPv2-TC (/opt/librenms/mibs/NOTIFICATION-LOG-MIB)
Did not find 'StorageType' in module SNMPv2-TC (/opt/librenms/mibs/NOTIFICATION-LOG-MIB)
Did not find 'RowStatus' in module SNMPv2-TC (/opt/librenms/mibs/NOTIFICATION-LOG-MIB)
Did not find 'TAddress' in module SNMPv2-TC (/opt/librenms/mibs/NOTIFICATION-LOG-MIB)
Did not find 'TDomain' in module SNMPv2-TC (/opt/librenms/mibs/NOTIFICATION-LOG-MIB)
Did not find 'TDomain' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-TARGET-MIB)
Did not find 'TAddress' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-TARGET-MIB)
Did not find 'TimeInterval' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-TARGET-MIB)
Did not find 'RowStatus' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-TARGET-MIB)
Did not find 'StorageType' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-TARGET-MIB)
Did not find 'TestAndIncr' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-TARGET-MIB)
Did not find 'RowStatus' in module SNMPv2-TC (/opt/librenms/mibs/DISMAN-EVENT-MIB)
Did not find 'TruthValue' in module SNMPv2-TC (/opt/librenms/mibs/DISMAN-EVENT-MIB)
Did not find 'DateAndTime' in module SNMPv2-TC (/opt/librenms/mibs/DISMAN-SCHEDULE-MIB)
Did not find 'RowStatus' in module SNMPv2-TC (/opt/librenms/mibs/DISMAN-SCHEDULE-MIB)
Did not find 'StorageType' in module SNMPv2-TC (/opt/librenms/mibs/DISMAN-SCHEDULE-MIB)
Did not find 'VariablePointer' in module SNMPv2-TC (/opt/librenms/mibs/DISMAN-SCHEDULE-MIB)
Did not find 'TimeStamp' in module SNMPv2-TC (/opt/librenms/mibs/NETWORK-SERVICES-MIB.txt)
Did not find 'TimeInterval' in module SNMPv2-TC (/opt/librenms/mibs/MTA-MIB)
Did not find 'DisplayString' in module SNMPv2-TC (/opt/librenms/mibs/UCD-SNMP-MIB)
Did not find 'TruthValue' in module SNMPv2-TC (/opt/librenms/mibs/UCD-SNMP-MIB)
Did not find 'DisplayString' in module SNMPv2-TC (/opt/librenms/mibs/UCD-DISKIO-MIB)
Did not find 'DisplayString' in module SNMPv2-TC (/opt/librenms/mibs/UCD-DLMOD-MIB)
Did not find 'DisplayString' in module SNMPv2-TC (/opt/librenms/mibs/LM-SENSORS-MIB)
Did not find 'DisplayString' in module SNMPv2-TC (/opt/librenms/mibs/NET-SNMP-AGENT-MIB)
Did not find 'RowStatus' in module SNMPv2-TC (/opt/librenms/mibs/NET-SNMP-AGENT-MIB)
Did not find 'TruthValue' in module SNMPv2-TC (/opt/librenms/mibs/NET-SNMP-AGENT-MIB)
Did not find 'TestAndIncr' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-USER-BASED-SM-MIB)
Did not find 'RowStatus' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-USER-BASED-SM-MIB)
Did not find 'RowPointer' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-USER-BASED-SM-MIB)
Did not find 'StorageType' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-USER-BASED-SM-MIB)
Did not find 'AutonomousType' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-USER-BASED-SM-MIB)
Did not find 'TestAndIncr' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-VIEW-BASED-ACM-MIB)
Did not find 'RowStatus' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-VIEW-BASED-ACM-MIB)
Did not find 'StorageType' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-VIEW-BASED-ACM-MIB)
Did not find 'RowStatus' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-COMMUNITY-MIB)
Did not find 'StorageType' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-COMMUNITY-MIB)
Did not find 'DisplayString' in module SNMPv2-TC (/opt/librenms/mibs/IPV6-MIB)
Did not find 'PhysAddress' in module SNMPv2-TC (/opt/librenms/mibs/IPV6-MIB)
Did not find 'TruthValue' in module SNMPv2-TC (/opt/librenms/mibs/IPV6-MIB)
Did not find 'TimeStamp' in module SNMPv2-TC (/opt/librenms/mibs/IPV6-MIB)
Did not find 'VariablePointer' in module SNMPv2-TC (/opt/librenms/mibs/IPV6-MIB)
Did not find 'RowPointer' in module SNMPv2-TC (/opt/librenms/mibs/IPV6-MIB)
Did not find 'RowStatus' in module SNMPv2-TC (/opt/librenms/mibs/eltex/IP-FORWARD-MIB)
Did not find 'RowStatus' in module SNMPv2-TC (/opt/librenms/mibs/NET-SNMP-EXAMPLES-MIB)
Did not find 'StorageType' in module SNMPv2-TC (/opt/librenms/mibs/NET-SNMP-EXAMPLES-MIB)
Did not find 'DisplayString' in module SNMPv2-TC (/opt/librenms/mibs/NET-SNMP-EXTEND-MIB)
Did not find 'RowStatus' in module SNMPv2-TC (/opt/librenms/mibs/NET-SNMP-EXTEND-MIB)
Did not find 'StorageType' in module SNMPv2-TC (/opt/librenms/mibs/NET-SNMP-EXTEND-MIB)
Did not find 'RowStatus' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-NOTIFICATION-MIB)
Did not find 'StorageType' in module SNMPv2-TC (/opt/librenms/mibs/SNMP-NOTIFICATION-MIB)
Did not find 'DisplayString' in module SNMPv2-TC (/opt/librenms/mibs/NET-SNMP-VACM-MIB)
Did not find 'RowStatus' in module SNMPv2-TC (/opt/librenms/mibs/NET-SNMP-VACM-MIB)
Did not find 'StorageType' in module SNMPv2-TC (/opt/librenms/mibs/NET-SNMP-VACM-MIB)
.*Table$: Unknown Object Identifier (Sub-id not found: (top) -> *Table$)
Failed to create new discovery file /opt/librenms/includes/definitions/discovery/eltex-mes.yaml

**Comment by PipoCanaja** [comment]
Hi @hrtrd 
Data is not complete. Snmpwalk is mandatory to work on device support.
Thx

**Comment by hrtrd** [comment]
@PipoCanaja the fact is that snmp data is very similar to an existing OS that is already pre-awesome in support. In fact, even the libraries are the same there. I’ll deal with integration more closely later. Thank you for reminding me

**Comment by hrtrd** [comment]
waiting new private snmp, have some bugs. Then add support

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11676

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-mes1124mb-ac-28-port-100m-1g/11676/1
