### ISSUE TITLE
Coriant/Infinera 7090 platform

### ISSUE THREAD

**Issue by roelpa** [librenms/librenms#10035]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Would it be possible to support the Coriant 7090 platform, and more specifically 7090-60CEM and 7090-100CEM which have recently added SNMP support?

[discovery-10.249.0.57.txt](https://github.com/librenms/librenms/files/3013115/discovery-10.249.0.57.txt)
[poller-10.249.0.57.txt](https://github.com/librenms/librenms/files/3013116/poller-10.249.0.57.txt)
[alerts-10.249.0.57.txt](https://github.com/librenms/librenms/files/3013118/alerts-10.249.0.57.txt)
[generic-10.249.0.57.snmpwalk.txt](https://github.com/librenms/librenms/files/3013120/generic-10.249.0.57.snmpwalk.txt)

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by PipoCanaja** [comment]
Hi
Any chance you have the MIB for this device family ? 
Thx

**Comment by PipoCanaja** [comment]
More details to be added from @roelpa .

**Comment by roelpa** [comment]
Unfortunately, Coriant  7090 (which is actually OEM from another vendor) is not using the standard if-mib, which means the interfaces are not discovered automatically by LibreNMS.

I will ask them to support the standard mib, but that will be a long shot
In the meantime, I have added the mib's I received.

[cxttrapmib_v2.9.txt](https://github.com/librenms/librenms/files/3898838/cxttrapmib_v2.9.txt)
[PM-MIB.my.txt](https://github.com/librenms/librenms/files/3898839/PM-MIB.my.txt)

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11626

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/coriant-infinera-7090-platform/11626/1
