### ISSUE TITLE
New device:EasyPath Ethernet-PON GFA6900S

### ISSUE THREAD

**Issue by hrtrd** [librenms/librenms#10030]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

http://prntscr.com/n33j89

./discovery.php -h HOSTNAME -d | ./pbin.sh
https://p.libren.ms/view/8c85cc95

./poller.php -h HOSTNAME -r -f -d | ./pbin.sh
https://p.libren.ms/view/4be7d807

snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh
https://p.libren.ms/view/35db7741

snmpwalk
https://p.libren.ms/view/d90e1fff
https://p.libren.ms/view/c31e39d6

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by neoll4ik** [comment]
Edit ./discovery.php -h HOSTNAME -d | ./pbin.sh and ./poller.php -h HOSTNAME -r -f -d | ./pbin.sh
got new firmware, and this commands work now.

**Comment by hrtrd** [comment]
Find MIBs files, download to /opt/librenms/mibs/gfa/  rename with script, and try  ./scripts/new-os.php -h 32 -o gfa -t network -v gwd   got some errors^

**Comment by hrtrd** [comment]
Try add one by one files, anywhere if i choose yes got errors.
![attach](https://user-images.githubusercontent.com/20502851/63589973-345f7600-c5b3-11e9-801b-efbe72447bfb.png)
 https://dropmefiles.com/EXfXU

**Comment by hrtrd** [comment]
Default "Generic Device" defined ports and drew graphics.  Put mib files in a new directory. Created a new profile, decided. The logo, serial number, software version and CPU sensor were determined, but all ports were gone. Somewhere they can be written additionally?

**Comment by PipoCanaja** [comment]
@hrtrd Can we close this issue as the code is now merged ?
