### ISSUE TITLE
add ablility to create generic aggregated graphs 

### ISSUE THREAD

**Issue by elbuit** [librenms/librenms#1003]
There are some aggregated graphs that you can create in librenms, like traffic aggregate.

But you can't to aggregate some graphs from different devices, like a sum of all wifi clients of all controllers, a graph to view some routers CPUs, ...

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #155](https://github.com/librenms/librenmsv2/issues/155) via [**ZenHub**](https://www.zenhub.com/)
