### ISSUE TITLE
Deep Sea Electronics

### ISSUE THREAD

**Issue by dbuschjr** [librenms/librenms#10042]
This is a generator controller. https://www.deepseaelectronics.com/

I ran the commands to upload the files. Below are the links from them:

Discovery: https://p.libren.ms/view/44a11176
Poller: https://p.libren.ms/view/52eaf949
SNMP Walk: https://p.libren.ms/view/b9cef773

**Comment by PipoCanaja** [comment]
Hi @dbuschjr 
Please keep the standard Issue template next time ;) 
PipoCanaja

**Comment by spencerbutler** [comment]
The files LGTM. @dbuschjr do you have the MIBs from the vendor? These would go a long way to getting this device properly supported.

**Comment by frasermclean77** [comment]
im after support for their devices too specifically DSE 7420 MkII (generator controller).

MIB attached! (renamed to .txt)
[DSE7410 MKII DSE7420 MKII V0.47 MIB.txt](https://github.com/librenms/librenms/files/3046051/DSE7410.MKII.DSE7420.MKII.V0.47.MIB.txt)

**Comment by spencerbutler** [comment]
@frasermclean77 Your device identifies as DSE_892 and is not defined in the provided MIB. Update this ticket once you obtain a suitable MIB for this device. I wish you luck with the vendor.

**Comment by frasermclean77** [comment]
@spencerbutler sorry I should have specified my device is a different model to that of the original poster. Same manufacturer but is indeed a dse7520 mkII

**Comment by dbuschjr** [comment]
I have downloaded the MIB file from the device. 
[892v2.zip](https://github.com/librenms/librenms/files/3110180/892v2.zip)

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/deep-sea-electronics/11625/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11625
