### ISSUE TITLE
New Device: Greenpacket OT-350

### ISSUE THREAD

**Issue by inkweb** [librenms/librenms#10065]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations
====================================
Component | Version
--------- | -------
LibreNMS  | 1.50-11-g311d24c3b
DB Schema | 2019_02_10_220000_add_dates_to_fdb (132)
PHP       | 7.2.15-0ubuntu0.18.04.2
MySQL     | 10.1.24-MariaDB-1~precise
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.3
====================================

Discovery: https://p.libren.ms/view/355825a3
Poller: https://p.libren.ms/view/efb0abc8
SNMPWalk: https://p.libren.ms/view/e389fc3a
MIB: https://p.libren.ms/view/936190dd

**Comment by spencerbutler** [comment]
@inkweb can you give PR #10067 a try and provide feedback there?

**Comment by PipoCanaja** [comment]
merged in  PR #10067
