### ISSUE TITLE
New Device: Cisco WAP150 missing CPU, Memory, and wireless client info

### ISSUE THREAD

**Issue by espectrorj** [librenms/librenms#10069]
I have added the Cisco WAP150 device but CPU, Memory, and wireless client count are missing.
The device is showing up as a Linux device but it should be showing up as a Cisco Small Business device.

Discovery output: https://p.libren.ms/view/d8feda43

Poller output: https://p.libren.ms/view/861138eb

SNMPBulkWalk output: https://p.libren.ms/view/cb908409

[wap150_wap361-mibs-20151203.zip](https://github.com/librenms/librenms/files/3045481/wap150_wap361-mibs-20151203.zip)

Thanks,
Daniel Sodre da SIlva Ferreira

**Comment by PipoCanaja** [comment]
Hi @espectrorj 
Could you please provide the snmpwalk exactly using the command and options requested in the issue description that you removed ?
Thanx

**Comment by espectrorj** [comment]
Hi @PipoCanaja 

I'm not sure I understood your request. Please forgive me as I have little experience with linux and have been using librenms for no more than 3 months.

Everytime I run snmpwalk/snmpbulkwalk the wireless device WAP150 returns data but the last line from the output is timed out - Timeout: No Response from 192.168.99.3.

I did snmpwalk one more time as stated in librenms website FAQ.
> snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh. <

If that's not what you meant please let me know.

Thanks,
Daniel Sodre da Silva Ferreira

SNMPBulkWalk output: https://p.libren.ms/view/28a0ee32

**Comment by PipoCanaja** [comment]
The syntax is now correct in this snmpbulkwalk. But it appears to be incomplete. (800 lines instead of 2000 in the first snmpbulkwalk you provided). Did you use the same device as you did in the first snmpbulkwalk ? 
What was the snmpwalk command you used the 1st time ? 
Any latency issue to reach the polled device or is it a test device in the lab (in which case connectivity should not be a problem.)

**Comment by espectrorj** [comment]
@PipoCanaja 
I am sorry for the late reply. Have been really busy since last post.
No, the second output was collected from another device, but the hardware is the same.
Everytime I run snmpbulkwalk I get different results. Maybe it's bad SNMP code from the device.
As it is, I think full support for the device is not possible,.
As stated before, the device is not recognized as ciscosb, instead LibreNMS report it as Linux.
For now, is it possible to add sysObjectID .1.3.6.1.4.1.9.6.1.34.150.1 and also sysObjectID 1.3.6.1.4.1.9.6.1.34.361.1 to includes/definitions/ciscosb.yaml? The reason I mention two sysObjectIDs is because Cisco WAP150 and Cisco WAP361 share the same code (latest release is 1.1.1.0 "Firmware Image for Cisco WAP150 and WAP361", FileName WAP361_WAP150_1.1.1.0.tar).
https://software.cisco.com/download/home/286286263/type/282463166/release/1.1.1.0
https://software.cisco.com/download/home/286286251/type/282463166/release/1.1.1.0
If you think these changes need to be proposed on a separate post let me know.

**Comment by espectrorj** [comment]
Hi @PipoCanaja 

I think I finally got a reliable output from the snmpbulkwalk. Please disregard the other outputs and consider the ones below.

PS: I have already modified my ./includes/definitions/ciscosb.yaml and added 2 sysObjectIDs, one for Cisco WAP 361 and one for Cisco WAP 150.

- .1.3.6.1.4.1.9.6.1.34.361.1
- .1.3.6.1.4.1.9.6.1.34.150.1

Discovery output: https://p.libren.ms/view/da1d3e9e

Poller output: https://p.libren.ms/view/ddcf39be

SNMPBulkWalk output: https://p.libren.ms/view/1837eb8f

Best Regards,
Daniel Sodré da Silva Ferreira

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-cisco-wap150-missing-cpu-memory-and-wireless-client-info/11624/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11624
