### ISSUE TITLE
Improve CyberPower UPS Support

### ISSUE THREAD

**Issue by tigerdjohnson** [librenms/librenms#10080]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

Discovery:  https://p.libren.ms/view/b80fc34c
Poller:  https://p.libren.ms/view/6d71272b
snmpwalk: https://p.libren.ms/view/d4749d2d

- [x] Please provide as much detail as possible.

No sensors are discovered for CyberPower UPSs. UPS is discovered as 'cyberpower' os, but sensor discovery is looking for PDU-specific OIDs not available on the UPS. RFC1628 is not enabled for cyberpower os definition. CP supports RFC1628 for the most part, but load, current, and voltage values are always null in my tests of various models. (Seems like the UPS is returning values for these sensors with an index starting at 1 instead of 0...?)

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by tigerdjohnson** [comment]
I submitted a PR with some changes I made to my dev system to add support for these devices.
https://github.com/librenms/librenms/pull/10087

**Comment by tigerdjohnson** [comment]
Looks like disabling snmpbulkwalk resolves this issue and allows all sensors to be discovered properly. My PR is completely unnecessary, lol.  

includes/definitions/cyberpower.yaml
+nobulk: true

**Comment by PipoCanaja** [comment]
You should open a new PR with this only simple change so next user with the same device won't have to find this out.
