### ISSUE TITLE
Sonus SBC SWE

### ISSUE THREAD

**Issue by DGothmin** [librenms/librenms#10084]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
./discovery.php -h 192.168.61.250 -d | ./pbin.sh
https://p.libren.ms/view/99269f68
./poller.php -h 192.168.61.250 -r -f -d | ./pbin.sh
https://p.libren.ms/view/a24dfb3f
snmpbulkwalk -OUneb -v2c -c QUBIC 192.168.61.250 | ./pbin.sh
https://p.libren.ms/view/f5d44aae

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by DGothmin** [comment]
MIB Ref
https://support.sonus.net/display/UXDOC61/SNMP+MIBs+Reference

**Comment by PipoCanaja** [comment]
Hi @DGothmin 
Seems that the snmpwalk is almost empty. Could you try to run the command below to see if more data is returned : 
``` snmpbulkwalk -OUneb -v2c -c QUBIC 192.168.61.250 . | ./pbin.sh ```
(there is a dot after 250).

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/sonus-sbc-swe/11623/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11623
