### ISSUE TITLE
Support for Ericsson MINI-LINK 6352

### ISSUE THREAD

**Issue by Ftelf** [librenms/librenms#10086]
Ericsson MINI-LINK 6352 all outdoor shorthaul wireless link.

Discovery: https://p.libren.ms/view/6344ab6b

Poller: https://p.libren.ms/view/77d44b24

SNMP:
full on fii.cz since it is too large http://fii.cz/ofehahuz
shorter version: https://p.libren.ms/view/728b2665

Thank you :)

**Comment by locki-cz** [comment]
[PT_MIB.zip](https://github.com/librenms/librenms/files/3067869/PT_MIB.zip)
MIB from R15A411, 2.14 firmwawre

**Comment by erotel** [comment]
https://github.com/librenms/librenms/pull/10543

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11622

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/support-for-ericsson-mini-link-6352/11622/1
