### ISSUE TITLE
Please add support for Zyxel VMG3625-T20A

### ISSUE THREAD

**Issue by DonovanEsterhuizen** [librenms/librenms#10093]
Hi

Please can support be added for the following device: Zyxel VMG3625-T20A

Discovery : https://p.libren.ms/view/246116a4
Poller : https://p.libren.ms/view/e4c0641b
SNMPWalk : https://p.libren.ms/view/e20dd3a3

ZyNOS
ZyNOS is the proprietary operating system used on network devices made by Zyxel Communications. The name is a contraction of Zyxel and Network Operating System (NOS).

Thanks

**Comment by DonovanEsterhuizen** [comment]
Hi

How can I help with verification?

Thanks

**Comment by DonovanEsterhuizen** [comment]
Hi

How can I help with verification?

Thanks

**Comment by PipoCanaja** [comment]
Hi @DonovanEsterhuizen 
The info provided looks good. Next step is that somebody start coding the support (but as you can see, quite a lot of issues are waiting) or you start coding the support directly (and we can help you on Discord, or on community.librenms.org, or here directly in the PullRequest you can open). 
Bye

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11621

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/please-add-support-for-zyxel-vmg3625-t20a/11621/1
