### ISSUE TITLE
Padding for graph-labels overflow on smaller graphs and on large values

### ISSUE THREAD

**Issue by mrjester888** [librenms/librenms#1009]
Another table text alignment issue.

![image](https://cloud.githubusercontent.com/assets/5603366/7638599/ed3cbd26-fa2a-11e4-8fdc-11dcc2b89975.png)

Hardware	 - cisco1811
Operating System - Cisco IOS 12.4(24)T2 (ADVIPSERVICESK9)

**Comment by laf** [comment]
Looks more of a wrapping issue. From the size of the graph I assume that's one of the popup or mini graphs? That's a lot of text to fit into something not that wide :)

**Comment by mrjester888** [comment]
Yes,  mini graphs page.  
device/device=4/tab=port/port=66/

If it is accepted behavior, that is fine.  Just pointing it out incase it can be fixed.

**Comment by paulgear** [comment]
The headings are jammed up in there, though; e.g. maximum appears over the column that is actually average.

**Comment by f0o** [comment]
I'll have a look at it later today
