### ISSUE TITLE
Look at deprecating the old alerting system

### ISSUE THREAD

**Issue by laf** [librenms/librenms#1010]
Something that we discussed loosely on irc.

1. The old alerting causes confusion sometimes for those using the new one but accidentally enabling parts of the old one.

2. We have code that to new users looks to be part of the alerting system so may confuse those wanting to contribute.

3. It makes little sense to maintain both and we shouldn't be afraid of deprecating something that is out of date and not as useful.

So, I propose we select a date (1st of August?) where from that point onwards either the old alerting code will be removed in full or we disable the options in defaults.inc.php and slowly remove the code as we come across it.

This gives people ample time to migrate to the new alerting system and we can:

Put a blog up
Tweet / Facebook / IRC
Put a message up on the mailing list
Closer to the time popup a warning onscreen for those using the old system.

Thoughts?

**Comment by f0o** [comment]
1st August sounds good!
:+1:

**Comment by paulgear** [comment]
Sounds good; I don't think that many people used the old alerting anyway.

**Comment by job** [comment]
yes, kill the old system. two systems nex to each other, with the same name, won't do anybody any good

**Comment by laf** [comment]
Unless @paulgear suggests otherwise, we will be looking at removing the code for the old alerting system to clean things up on the 1st of August 2015.

More info will be published soon.

**Comment by f0o** [comment]
:+1:

**Comment by laf** [comment]
PR in place.
