### ISSUE TITLE
Improve Support for Alcatel-Lucent Switches

### ISSUE THREAD

**Issue by joseUPV** [librenms/librenms#10107]
Alcatel has two different OIDs: .1.3.6.1.4.1.6486.800... and 1.3.6.1.4.1.6486.801...

One possible change is in includes/polling/os/aos.inc.php

if (strpos($device['sysObjectID'],'1.3.6.1.4.1.6486.800'))
        list(,$hardware,$version) = explode(' ', $device['sysDescr']);
else
        list(,,$hardware,$version) = explode(' ', $device['sysDescr']);

There are two diferent MIBs with the same name: https://community.librenms.org/t/alcatel-mibs-problem/7963

**Comment by joseUPV** [comment]
Improved includes/polling/os/aos.inc.php
if (strpos($device['sysObjectID'],'1.3.6.1.4.1.6486.801'))
        list(,,$hardware,$version) = explode(' ', $device['sysDescr']);
elseif (strpos($device['sysObjectID'],'1.3.6.1.4.1.6486.800.1.1.2.2.4'))
        switch ($device['sysObjectID']) {
                case ".1.3.6.1.4.1.6486.800.1.1.2.2.4.1.7": $hardware='LS6212';break;
                case ".1.3.6.1.4.1.6486.800.1.1.2.2.4.1.2": $hardware='LS6224';break;
                case ".1.3.6.1.4.1.6486.800.1.1.2.2.4.1.4": $hardware='LS6248';break;
                default: $hardware='LS6200';
                }
else
        list(,$hardware,$version) = explode(' ', $device['sysDescr']);

**Comment by laf** [comment]
If you've got a change that needs making please make a pull request with those changes. If you want someone else to do it then you need to provide the info asked for.

No further information has been provided so this issue is being closed.

If you have more information to provide then please do so and we will re-open this issue.

**Comment by joseUPV** [comment]
Ok. I'm not developer. 
But we have 350 Alcatel Switches and LibreNMS has bad support for it. I want to help with this trademark.
Some aditional Info:
LibreNMS has support of three Alcatel-Lucent families: Alcatel AOS6, Alcatel Enterprise and OmniSwitch.
LibreNMS says "Enterprise" as $hardware in Enterprise models and "LS" in OmniSwitch Models, AOS6 family is working Ok.
This code was a try to get correctly models of our Alcatel Switches. I have this code in my LibreNMS and all pastebin included has hardware model corrected. 

I included sysDescr and sysObjectID, pastebin of discovery.php and poller.php if anyone wan't to make a pull request, because it's dificult for me to do it.

AOS6 models:
- Switch Alcatel 6350-24: Discovery: https://p.libren.ms/view/a80aafc2, Poller: https://p.libren.ms/view/3c274b1e
RFC1213-MIB::sysDescr.0 = STRING: “Alcatel-Lucent OS6350-24 6.7.1.108.R04 Service Release, January 04, 2017.”
RFC1213-MIB::sysObjectID.0 = OID: RFC1155-SMI::enterprises.6486.800.1.1.2.1.13.1.1
- Switch Alcatel 6350-24P: Discovery: https://p.libren.ms/view/07ec4b34, Poller: https://p.libren.ms/view/434fce29
RFC1213-MIB::sysDescr.0 = STRING: “Alcatel-Lucent OS6350-P24 6.7.1.108.R04 Service Release, January 04, 2017.”
RFC1213-MIB::sysObjectID.0 = OID: RFC1155-SMI::enterprises.6486.800.1.1.2.1.13.1.2
- Switch Alcatel 6350-48: Discovery: https://p.libren.ms/view/243edf1a, Poller: https://p.libren.ms/view/fd0ef5c3 
RFC1213-MIB::sysDescr.0 = STRING: “Alcatel-Lucent OS6350-48 6.7.2.49.R01 GA, March 31, 2017.”
RFC1213-MIB::sysObjectID.0 = OID: RFC1155-SMI::enterprises.6486.800.1.1.2.1.13.1.3
- Switch Alcatel 6424: Discovery: https://p.libren.ms/view/6a6c6e16, Poller: https://p.libren.ms/view/9aa07960
RFC1213-MIB::sysDescr.0 = STRING: “6.3.3.277.R01 GA, August 06, 2008.”
RFC1213-MIB::sysObjectID.0 = OID: RFC1155-SMI::enterprises.6486.800.1.1.2.1.10.1.2

OmniSwitch Models:
- Switch Alcatel 6212: Discovery: https://p.libren.ms/view/818ec304, Poller: https://p.libren.ms/view/6030d209
RFC1213-MIB::sysDescr.0 = STRING: “OmniStack LS 6200”
RFC1213-MIB::sysObjectID.0 = OID: RFC1155-SMI::enterprises.6486.800.1.1.2.2.4.1.7
- Switch Alcatel 6224: Discovery: https://p.libren.ms/view/d6fb47ca, Poller: https://p.libren.ms/view/75cd6821
RFC1213-MIB::sysDescr.0 = STRING: “OmniStack LS 6200”
RFC1213-MIB::sysObjectID.0 = OID: RFC1155-SMI::enterprises.6486.800.1.1.2.2.4.1.2
- Switch Alcatel 6248: Discovery: https://p.libren.ms/view/469625ba, Poller: https://p.libren.ms/view/fe065bf3
RFC1213-MIB::sysDescr.0 = STRING: “OmniStack LS 6200”
RFC1213-MIB::sysObjectID.0 = OID: RFC1155-SMI::enterprises.6486.800.1.1.2.2.4.1.4

Enterprise models:
- Switch Alcatel 6860E-U28: Discovery: https://p.libren.ms/view/04d4b3d0, Poller: https://p.libren.ms/view/3f20931f
RFC1213-MIB::sysDescr.0 = STRING: “Alcatel-Lucent Enterprise OS6860E-U28 8.5.255.R02 GA, August 29, 2018.”
RFC1213-MIB::sysObjectID.0 = OID: RFC1155-SMI::enterprises.6486.801.1.1.2.1.11.1.9
Switch Alcatel 6860E-24: Discovery: https://p.libren.ms/view/1aa0207a, Poller: https://p.libren.ms/view/a25d07aa
RFC1213-MIB::sysDescr.0 = STRING: “Alcatel-Lucent Enterprise OS6860E-24 8.5.255.R02 GA, August 29, 2018.”
RFC1213-MIB::sysObjectID.0 = OID: RFC1155-SMI::enterprises.6486.801.1.1.2.1.11.1.5
Switch Alcatel 6860E-48: Discovery: https://p.libren.ms/view/dfcf9209, Poller: https://p.libren.ms/view/ec589ced
RFC1213-MIB::sysDescr.0 = STRING: “Alcatel-Lucent Enterprise OS6860E-48 8.5.255.R02 GA, August 29, 2018.”
RFC1213-MIB::sysObjectID.0 = OID: RFC1155-SMI::enterprises.6486.801.1.1.2.1.11.1.7
Switch Alcatel 6900-T40: Discovery: https://p.libren.ms/view/df8f4634, Poller: https://p.libren.ms/view/1b0b0523
RFC1213-MIB::sysDescr.0 = STRING: “Alcatel-Lucent Enterprise OS6900-T40 8.5.255.R02 GA, August 29, 2018.”
RFC1213-MIB::sysObjectID.0 = OID: RFC1155-SMI::enterprises.6486.801.1.1.2.1.10.1.4
Switch Alcatel 6900-X72: Discovery: https://p.libren.ms/view/bb1b97dc, Poller: https://p.libren.ms/view/8a564718
RFC1213-MIB::sysDescr.0 = STRING: “Alcatel-Lucent Enterprise OS6900-X72 8.5.255.R02 GA, August 29, 2018.”
RFC1213-MIB::sysObjectID.0 = OID: RFC1155-SMI::enterprises.6486.801.1.1.2.1.10.1.6
