### ISSUE TITLE
Better Support of Alcatel Enterprise Switches

### ISSUE THREAD

**Issue by joseUPV** [librenms/librenms#10108]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
validate.php: https://p.libren.ms/view/369d6f99
discovery.php (6860E-24): https://p.libren.ms/view/f68b5d2f
poller.php (6860E-24): https://p.libren.ms/view/1be579ea
snmpbulkwalk (6860E-24): https://p.libren.ms/view/191c8322 (snmpblukwalk has a break)
discovery.php (6900-T40): https://p.libren.ms/view/9d76b5b5
poller.php (6900-T40): https://p.libren.ms/view/1c2ec341
snmpbulkwalk (6900-T40): [o94-asic8e.txt.gz](https://github.com/librenms/librenms/files/3080666/o94-asic8e.txt.gz) (complete)

- [x] Please provide as much detail as possible.
Enterprise models has diferent MIB with same name, it changes 800 to 801.
AOS6 models with POE and Enterprise models has fans and libreNMS doesn't support it.
Enterprise models has bad support for memory and storage
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by joseUPV** [comment]
Alcatel OmniSwitch mempool: TIMETRA-SYSTEM-MIB
- Total: sgiMemoryAvailable
- used: sgiMemoryUsed
Alcatel AOS6 mempool: ALCATEL-IND1-SYSTEM-MIB (aos6)
- Total: .1.3.6.1.4.1.6486.800.1.1.1.2.1.1.3.4.0
- Percent: .1.3.6.1.4.1.6486.800.1.2.1.16.1.1.1.10.0
Alcatel Enterprise Mempool: ALCATEL-IND1-SYSTEM-MIB (aos7)
- Total: .1.3.6.1.4.1.6486.801.1.1.1.2.1.1.3.4.0
- Percent: .1.3.6.1.4.1.6486.801.1.2.1.16.1.1.1.1.1.8.0

**Comment by joseUPV** [comment]
I don't know how to create a pull request but here is my code:

- Some new graphs in top:  includes/definitions/aos.yaml
https://p.libren.ms/view/cbed273f
- Fan State on AOS6350 POE: includes/definitions/discovery/aos.yaml
https://p.libren.ms/view/60c7fff3
- Mempools discovery :  includes/discovery/mempools/aos-device.inc.php
https://p.libren.ms/view/59e8a54f
- Mempools polling: includes/polling/mempools/aos-device.inc.php
https://p.libren.ms/view/1e55846f
- Temperature discovery: includes/discovery/sensors/temperature/aos.inc.php
https://p.libren.ms/view/bfc4ef01
- Fan Speed on AOS6900T-40:  includes/discovery/sensors/fanspeed/aos.inc.php
https://p.libren.ms/view/4b436a7a
- OS polling:  includes/polling/os/aos.inc.php
https://p.libren.ms/view/ea167a48

**Comment by PipoCanaja** [comment]
Hello @joseUPV 
Please have a look here https://docs.librenms.org/Developing/Using-Git/ and in the dev documentation in general, you'll find all details you need to submit a pull request. 
That will allow your code to be merged into LibreNMS and will not break your updates like it is now. 

We can help you if needed (on Discord, community.librenms.org, or in the Pull Request itself when opened).

Bye

**Comment by joseUPV** [comment]
Included in PR #10672
