### ISSUE TITLE
Better Support of Alcatel OmniStack LS Switches

### ISSUE THREAD

**Issue by joseUPV** [librenms/librenms#10116]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

This part is done with modified aos scripts:
validate.php: https://p.libren.ms/view/227ade63
- includes/discovery/mempools/aos-device.inc.php: https://p.libren.ms/view/9c37be30
- includes/polling/mempools/aos-device.inc.php: https://p.libren.ms/view/78874670
- includes/polling/os/aos.inc.php: https://p.libren.ms/view/8c442528

discovery.php: https://p.libren.ms/view/14afd5bc
poller.php: https://p.libren.ms/view/cd9bfd30

snmpbulkwalk -v 2c -c xxxx o22-cfp02 -m ALL -M /disco2/opt/librenms/mibs:/disco2/opt/librenms/mibs/radlan .1.3.6.1.4.1.89 >/tmp/radlan-o22-cfp02.txt : [radlan-o22-cfp02.txt.gz](https://github.com/librenms/librenms/files/3084641/radlan-o22-cfp02.txt.gz)

Old Discovery and poller captures from other models:
    Switch Alcatel 6212P: Discovery: https://p.libren.ms/view/818ec304, Poller: https://p.libren.ms/view/6030d209
    RFC1213-MIB::sysDescr.0 = STRING: “OmniStack LS 6200”
    RFC1213-MIB::sysObjectID.0 = OID: RFC1155-SMI::enterprises.6486.800.1.1.2.2.4.1.7
    Switch Alcatel 6224P: Discovery: https://p.libren.ms/view/d6fb47ca, Poller: https://p.libren.ms/view/75cd6821
    RFC1213-MIB::sysDescr.0 = STRING: “OmniStack LS 6200”
    RFC1213-MIB::sysObjectID.0 = OID: RFC1155-SMI::enterprises.6486.800.1.1.2.2.4.1.2
    Switch Alcatel 6248P: Discovery: https://p.libren.ms/view/469625ba, Poller: https://p.libren.ms/view/fe065bf3
    RFC1213-MIB::sysDescr.0 = STRING: “OmniStack LS 6200”
    RFC1213-MIB::sysObjectID.0 = OID: RFC1155-SMI::enterprises.6486.800.1.1.2.2.4.1.4

**Comment by joseUPV** [comment]
Alcatel OmniStack LS CPU: RADLAN-rndMng
- rlCpuUtilDuringLastSecond, rlCpuUtilDuringLastMinute, rlCpuUtilDuringLast5Minutes

**Comment by PipoCanaja** [comment]
Hello @joseUPV 
Could you please provide the data required in the issue ? Most importantly the snmpwalk must be taken with the exact command provided, so it can be used to "simulate" your device directly on the server that will be used to write and test code for your request. 
The data attached to this issue cannot be used. 

Thanx

**Comment by joseUPV** [comment]
Hi,
I'm sorry, but the exact command doesn't work:
seti#  snmpbulkwalk -OUneb -v2c -c xxxx xxxx .  | ./pbin.sh
Paste endpoint: https://p.libren.ms/api/create
title:
name: librenms
private: 1
expire: 0
Error: Missing paste text

I tried snmpbulkwalk -OUneb -v2c -c xxxx xxxx .  | tee /tmp/o22-cfp02.txt
[o24-asic02.txt.gz](https://github.com/librenms/librenms/files/3377632/o24-asic02.txt.gz)
[o22-cfp02.txt.gz](https://github.com/librenms/librenms/files/3377616/o22-cfp02.txt.gz)
[o21-oxealc1.txt.gz](https://github.com/librenms/librenms/files/3377643/o21-oxealc1.txt.gz)

¿Can be it useable?

**Comment by joseUPV** [comment]
Created PR #10672
