### ISSUE TITLE
Pull in UPS info from Mikrotik

### ISSUE THREAD

**Issue by laf** [librenms/librenms#1011]
Please see:

https://groups.google.com/forum/#!topic/librenms-project/8SF0LrTRvNQ

**Comment by Lonecrowe** [comment]
Add the fan speeds and voltages and temps too while you are at it :) I think its under /system/health

**Comment by Lonecrowe** [comment]
Also add 1.3.6.1.2.1.4.24.3.0 please.  It counts how many active routes there are.  Handy for monitoring OSPF.

**Comment by Lonecrowe** [comment]
Mikrotik health voltage fans temps etc  handy here 
mtxrHealth!@#.iso.org.dod.internet.private.enterprises.mikrotik.mikrotikExperimentalModule.mtXRouterOs.mtxrHealth

OID	 .1.3.6.1.4.1.14988.1.1.3

Also very handy is  DHCP LEASE COUNT

mtxrDHCPLeaseCount!@#.iso.org.dod.internet.private.enterprises.mikrotik.mikrotikExperimentalModule.mtXRouterOs.mtxrDHCP.mtxrDHCPLeaseCount

OID	 .1.3.6.1.4.1.14988.1.1.6.1

**Comment by paulgear** [comment]
@Lonecrowe, it would be good to have separate issues created for the features you want to see - then we can track each feature separately. :+1: on those ideas, though. :-)

**Comment by acidsas** [comment]
I also need this feature! I can provide access to few mikrotiks with APC UPSes.
