### ISSUE TITLE
Support for IgniteNet METROLINQ 2.5 60 Wireless (new firmware)

### ISSUE THREAD

**Issue by 07stuntar1** [librenms/librenms#10119]
Hi,
 
It seems like the METROLINQ 2.5 60-19 - and METROLINQ 2.5 60-BF-18-Panel Firmware has been updated and Wireless tab is not reporting the 60ghz. Also is there a way to show multiple clients connected and a list of SSIDs?

FW: IgniteNet HeliOS 2.1.1-2446
![image](https://user-images.githubusercontent.com/30091711/56248129-ca522580-6042-11e9-9ef6-27a3d0892cdb.png)

FW: IgniteNet HeliOS 2.3.1-3071
![image](https://user-images.githubusercontent.com/30091711/56247947-27011080-6042-11e9-8552-9b233a472df8.png)

====================================
Component | Version
--------- | -------
LibreNMS  | 1.50-41-gd069d0f
DB Schema | 2019_02_10_220000_add_dates_to_fdb (132)
PHP       | 7.2.16
MySQL     | 5.5.60-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

MIB File: https://support.ignitenet.com/portal/kb/articles/ml2-5-60-35-product-page

discovery FW: IgniteNet HeliOS 2.3.1-3071 METROLINQ 2.5 60-BF-18
https://p.libren.ms/view/9ec26323

poller FW: IgniteNet HeliOS 2.3.1-3071 METROLINQ 2.5 60-BF-18
https://p.libren.ms/view/4e168418

snmpbuilkwalk FW: IgniteNet HeliOS 2.3.1-3071 METROLINQ 2.5 60-BF-18
https://p.libren.ms/view/cd045f46

Mib File: https://support.ignitenet.com/portal/kb/articles/metrolinq-2-5g-60-19-info-and-links

discovery FW: IgniteNet HeliOS 2.3.1-3071 METROLINQ 2.5 60-19
https://p.libren.ms/view/5341f402

poller FW: IgniteNet HeliOS 2.3.1-3071 METROLINQ 2.5 60-19
https://p.libren.ms/view/dbdd7185

snmpbuilkwalk FW: IgniteNet HeliOS 2.3.1-3071 METROLINQ 2.5 60-19
https://p.libren.ms/view/02e18331

Please let me know if you need anything else.
Thank You

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11620

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/support-for-ignitenet-metrolinq-2-5-60-wireless-new-firmware/11620/1
