### ISSUE TITLE
Can't list any bills

### ISSUE THREAD

**Issue by Najihel** [librenms/librenms#10110]
Hello,

I can't list any bills throught API when a single bill have `bill_quota` or `bill_cdr` equal 0

To reproduce, you can create a bill like that :

```json
{
  "bill_name": "test",
  "bill_type": "quota",
  "bill_day": 1,
  "bill_quota": 0,
  "bill_custid": "",
  "bill_ref": "",
  "bill_notes": "",
}
```

or

```json
{
  "bill_name": "test",
  "bill_type": "cdr",
  "bill_day": 1,
  "bill_cdr": 0,
  "bill_custid": "",
  "bill_ref": "",
  "bill_notes": "",
}
```

And call the api list_bills `/api/v0/bills`. The API will return a empty body response with a 200 HTTP CODE

Can you look at this ?

Thanks for your time,

Regards

**Comment by kkrumm1** [comment]
👋 @lewisvive sorry but this is not the place to ask for help/ or report bugs.

This issue has been closed as it isn't classed as a new device request.

For help please use our Discord server or the community site: https://docs.librenms.org/Support
