### ISSUE TITLE
New device request: Reliable Controls Mach-Pro

### ISSUE THREAD

**Issue by whysyn** [librenms/librenms#10140]
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hi guys, I gave this a shot myself following the docs to add a new OS but I'm out of my depth.

This is a building controller for an HVAC installation.  I'm sure there's more than can be done with it, but my only real desire is graphing temperature and humidity reading from the various sensors installed throughout the building.

Discovery: https://p.libren.ms/view/caa96253
Poller: https://p.libren.ms/view/9daec750
snmpbulkwalk: https://p.libren.ms/view/7e4bc96e

[RC-ROOT-MIB.txt](https://github.com/librenms/librenms/files/3112667/RC-ROOT-MIB.txt)
[RC-MACH-PRO-MIB.txt](https://github.com/librenms/librenms/files/3112670/RC-MACH-PRO-MIB.txt)

**Comment by whysyn** [comment]
In case it helps, I've been able to track down the following, and verify with the building automation vendor the reading are correct.  I just don't know how to get these monitoring in LibreNMS:
.1.3.6.1.4.1.15255.1.2.1.3.1.2.26 contains the computer room temperature, off by a factor of 100 (reading of 6803 = 68.03 degrees F)
.1.3.6.1.4.1.15255.1.2.1.3.1.2.27 contains the computer room humidity, also off by a factor of 100 (reading 4249 = 42.49% RH)

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11619

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-request-reliable-controls-mach-pro/11619/1
