### ISSUE TITLE
AVTECH RoomAlert 4E not showing external temp sensor info

### ISSUE THREAD

**Issue by ickyfeet** [librenms/librenms#10145]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

Discovery:  https://p.libren.ms/view/1c51bf96

Poller:  https://p.libren.ms/view/4006851e

SNMP walk:  https://p.libren.ms/view/c0a1a548  (SNMP v1 Device)

- [ x] Please provide as much detail as possible.

Librenms will not collect or display external temp sensor data.  Device firmware shows up to date (v4.2.4).  Debug on discovery shows that it can see the external temp sensor/data, it just doesn't show up for the device.

- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by kkrumm1** [comment]
I suspect this is the issue 


State:
Warning: Illegal string offset '.1.3.6.1.4.1.20916.1.6.1.3.1.0' in /opt/librenms/includes/discovery/functions.inc.php on line 1045
Cur 0, Low: null, Low Warn: null, Warn: null, High: null
.
Count:
Temperature:
Warning: Illegal string offset '.1.3.6.1.4.1.20916.1.6.1.1.1.2.0' in /opt/librenms/includes/discovery/functions.inc.php on line 1045
Cur 2, Low: null, Low Warn: null, Warn: null, High: null
.
Voltage:
Snr:
Pressure:
Cooling:

**Comment by ickyfeet** [comment]
Just so you know.  These devices have a really nice rest api that returns JSON formatted data that would make it pretty easy to determine if the external sensor is temp or not.

**Comment by murrant** [comment]
You have several permission denied messages, perhaps you should validate your install first.

Your snmpwalk shows no sensor oids.   Did you walk with `.`?  If that didn't include the data still, try `.1.3.6.1.4.1.20916`

**Comment by ickyfeet** [comment]
Install validated, all green.  Did not walk with . , here's the new pastebin https://p.libren.ms/view/68a051be  Reran discovery on the device and external sensor is still not detected.

**Comment by murrant** [comment]
@ickyfeet do you have an updated MIB file?  The one LibreNMS has has the sensor description at a different oid than shows in the snmpwalk you sent.

**Comment by ickyfeet** [comment]
[ROOMALERT4E.TXT](https://github.com/librenms/librenms/files/3128603/ROOMALERT4E.TXT)

**Comment by ickyfeet** [comment]
That's straight off of the device.

**Comment by murrant** [comment]
The only place they offer it. It does look like they moved the labels... silly.
