### ISSUE TITLE
Device Update: Cambium PTP 650

### ISSUE THREAD

**Issue by inkweb** [librenms/librenms#10151]
Could we get mainPSUPortSpeedAndDuplex added to the PTP 650? We'd like to be able to set an alert on the value.

**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery: https://p.libren.ms/view/48c7ee99
Poller: https://p.libren.ms/view/047e80f3
SNMPWalk: https://p.libren.ms/view/5df846ed
MIB: https://p.libren.ms/view/5556e99e

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by PipoCanaja** [comment]
Hi @inkweb 
This information is already available in LibreNMS, via standard IFMIB
![Capture d’écran 2019-12-14 à 18 11 22](https://user-images.githubusercontent.com/38363551/70852061-4dab6b80-1e9d-11ea-9830-cd5bcc3c55c8.png)
It is not necessary to poll it and store it again. 

Feel free to reopen this issue if you have another need.
