### ISSUE TITLE
Make footer non-static

### ISSUE THREAD

**Issue by arjitc** [librenms/librenms#1015]
It would be nice to have the footer of each page as non-static and like a normal footer right at the bottom of the page, not that the footer is too big but I guess that few px would be nice to regain.

**Comment by f0o** [comment]
:+1:

**Comment by laf** [comment]
I thought I'd replied back to this yesterday :/

You can disable the footer in config.php - is this a solution?

**Comment by arjitc** [comment]
Yeah that could be a solution, but I wouldn't mind having Librenms linked at the footer if it wasn't static/fixed (like the navbar is). I could submit a patch for this to make it non-fixed, could you tell me which file the footer is in?

**Comment by arjitc** [comment]
Pushed a PR for this #1020 

screenshot: http://i.imgur.com/m6JAEDg.png

**Comment by paulgear** [comment]
Looks OK to me.  @arjitc, would you mind signing the contributor's agreement per http://docs.librenms.org/General/Contributing/ ?

**Comment by arjitc** [comment]
Done :)
