### ISSUE TITLE
ARP discovery process mac address changing issue

### ISSUE THREAD

**Issue by laf** [librenms/librenms#1016]
"Juniper SRX firewall where I have changed the MAC address of my ISP-facing interface to retain the IP address I got for my last CPE. That means that there is a configured MAC and a hardware MAC. LibreNMS sometimes figures this out and determines that the MAC has changed. This happens every 6 hours."

Issue is in includes/discovery/arp-table.inc.php

log_event("MAC change: $ip : " . mac_clean_to_readable($old_mac) . " -> " . mac_clean_to_readable($clean_mac), $device, "interface", $interface['port_id']);

**Comment by lasseleegaard** [comment]
Reporter here... This is not a bug, but LibreNMS detecting that things are not OK at my network. It is a mac change event as seen from the firewall.

**Comment by lasseleegaard** [comment]
debug info as requested - for what its worth...

LibreNMS 2014.master Discovery

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1]
SQL[SELECT revision FROM `dbSchema`]
SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE '***' ORDER BY device_id DESC]
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '3'] *** 3 junos
ARP Table : DEBUG: SNMP Auth options =  -v2c -c ***
/usr/bin/snmpbulkwalk -v2c -c *** -Oq  -m IP-MIB -M /opt/librenms/mibs udp:***k:161 ipNetToMediaPhysAddress
IP-MIB::ipNetToMediaPhysAddress.511.*** b0:c6:9a:60:ba:40
IP-MIB::ipNetToMediaPhysAddress.511.*** 0:0:24:c5:ce:c9
IP-MIB::ipNetToMediaPhysAddress.514.10.1.1.1 0:26:88:38:3d:c1
IP-MIB::ipNetToMediaPhysAddress.514.10.1.1.12 0:21:b7:96:17:74
IP-MIB::ipNetToMediaPhysAddress.514.10.1.1.13 70:3e:ac:91:f1:6c
IP-MIB::ipNetToMediaPhysAddress.514.10.1.1.14 74:81:14:3b:5f:56
IP-MIB::ipNetToMediaPhysAddress.514.10.1.1.17 0:6:dc:80:90:c8
IP-MIB::ipNetToMediaPhysAddress.514.10.1.1.20 8c:89:a5:c1:f7:9a
IP-MIB::ipNetToMediaPhysAddress.514.10.1.1.21 0:11:32:2:a:78
IP-MIB::ipNetToMediaPhysAddress.514.10.1.1.22 64:66:b3:ce:b:fc
IP-MIB::ipNetToMediaPhysAddress.514.10.1.1.23 b4:f0:ab:ca:5a:dd
IP-MIB::ipNetToMediaPhysAddress.514.10.1.1.24 58:55:ca:48:de:5d
IP-MIB::ipNetToMediaPhysAddress.514.10.1.1.25 b8:c7:5d:c8:3d:71
IP-MIB::ipNetToMediaPhysAddress.514.10.1.1.26 70:3e:ac:83:6f:36
IP-MIB::ipNetToMediaPhysAddress.514.10.1.1.29 6c:ad:f8:d0:a8:b4
IP-MIB::ipNetToMediaPhysAddress.514.10.1.1.34 8c:89:a5:64:ab:81
IP-MIB::ipNetToMediaPhysAddress.514.10.1.1.52 0:23:12:24:2:3e


SQL[SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '511']
SQL[SELECT COUNT(*) from ipv4_mac WHERE port_id = '23' AND ipv4_address = '***']
SQL[SELECT mac_address from ipv4_mac WHERE ipv4_address='***' AND port_id='23']
SQL[UPDATE `ipv4_mac` set `mac_address` ='b0c69a60ba40' WHERE port_id='23' AND ipv4_address='***'] .
SQL[SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '511']
SQL[SELECT COUNT(*) from ipv4_mac WHERE port_id = '23' AND ipv4_address = '***']
SQL[SELECT mac_address from ipv4_mac WHERE ipv4_address='***' AND port_id='23']
SQL[UPDATE `ipv4_mac` set `mac_address` ='000024c5cec9' WHERE port_id='23' AND ipv4_address='***'] .
SQL[SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '514']
SQL[SELECT COUNT(*) from ipv4_mac WHERE port_id = '26' AND ipv4_address = '10.1.1.1']
SQL[SELECT mac_address from ipv4_mac WHERE ipv4_address='10.1.1.1' AND port_id='26']
SQL[UPDATE `ipv4_mac` set `mac_address` ='002688383dc1' WHERE port_id='26' AND ipv4_address='10.1.1.1'] .
SQL[SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '514']
SQL[SELECT COUNT(*) from ipv4_mac WHERE port_id = '26' AND ipv4_address = '10.1.1.12']
SQL[SELECT mac_address from ipv4_mac WHERE ipv4_address='10.1.1.12' AND port_id='26']
SQL[UPDATE `ipv4_mac` set `mac_address` ='0021b7961774' WHERE port_id='26' AND ipv4_address='10.1.1.12'] .
SQL[SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '514']
SQL[SELECT COUNT(*) from ipv4_mac WHERE port_id = '26' AND ipv4_address = '10.1.1.13']
SQL[SELECT mac_address from ipv4_mac WHERE ipv4_address='10.1.1.13' AND port_id='26']
SQL[UPDATE `ipv4_mac` set `mac_address` ='703eac91f16c' WHERE port_id='26' AND ipv4_address='10.1.1.13'] .
SQL[SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '514']
SQL[SELECT COUNT(*) from ipv4_mac WHERE port_id = '26' AND ipv4_address = '10.1.1.14']
SQL[SELECT mac_address from ipv4_mac WHERE ipv4_address='10.1.1.14' AND port_id='26']
SQL[UPDATE `ipv4_mac` set `mac_address` ='7481143b5f56' WHERE port_id='26' AND ipv4_address='10.1.1.14'] .
SQL[SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '514']
SQL[SELECT COUNT(*) from ipv4_mac WHERE port_id = '26' AND ipv4_address = '10.1.1.17']
SQL[SELECT mac_address from ipv4_mac WHERE ipv4_address='10.1.1.17' AND port_id='26']
SQL[UPDATE `ipv4_mac` set `mac_address` ='0006dc8090c8' WHERE port_id='26' AND ipv4_address='10.1.1.17'] .
SQL[SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '514']
SQL[SELECT COUNT(*) from ipv4_mac WHERE port_id = '26' AND ipv4_address = '10.1.1.20']
SQL[SELECT mac_address from ipv4_mac WHERE ipv4_address='10.1.1.20' AND port_id='26']
SQL[UPDATE `ipv4_mac` set `mac_address` ='8c89a5c1f79a' WHERE port_id='26' AND ipv4_address='10.1.1.20'] .
SQL[SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '514']
SQL[SELECT COUNT(*) from ipv4_mac WHERE port_id = '26' AND ipv4_address = '10.1.1.21']
SQL[SELECT mac_address from ipv4_mac WHERE ipv4_address='10.1.1.21' AND port_id='26']
SQL[UPDATE `ipv4_mac` set `mac_address` ='001132020a78' WHERE port_id='26' AND ipv4_address='10.1.1.21'] .
SQL[SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '514']
SQL[SELECT COUNT(*) from ipv4_mac WHERE port_id = '26' AND ipv4_address = '10.1.1.22']
SQL[SELECT mac_address from ipv4_mac WHERE ipv4_address='10.1.1.22' AND port_id='26']
SQL[UPDATE `ipv4_mac` set `mac_address` ='6466b3ce0bfc' WHERE port_id='26' AND ipv4_address='10.1.1.22'] .
SQL[SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '514']
SQL[SELECT COUNT(*) from ipv4_mac WHERE port_id = '26' AND ipv4_address = '10.1.1.23']
SQL[SELECT mac_address from ipv4_mac WHERE ipv4_address='10.1.1.23' AND port_id='26']
SQL[UPDATE `ipv4_mac` set `mac_address` ='b4f0abca5add' WHERE port_id='26' AND ipv4_address='10.1.1.23'] .
SQL[SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '514']
SQL[SELECT COUNT(*) from ipv4_mac WHERE port_id = '26' AND ipv4_address = '10.1.1.24']
SQL[SELECT mac_address from ipv4_mac WHERE ipv4_address='10.1.1.24' AND port_id='26']
SQL[UPDATE `ipv4_mac` set `mac_address` ='5855ca48de5d' WHERE port_id='26' AND ipv4_address='10.1.1.24'] .
SQL[SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '514']
SQL[SELECT COUNT(*) from ipv4_mac WHERE port_id = '26' AND ipv4_address = '10.1.1.25']
SQL[SELECT mac_address from ipv4_mac WHERE ipv4_address='10.1.1.25' AND port_id='26']
SQL[UPDATE `ipv4_mac` set `mac_address` ='b8c75dc83d71' WHERE port_id='26' AND ipv4_address='10.1.1.25'] .
SQL[SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '514']
SQL[SELECT COUNT(*) from ipv4_mac WHERE port_id = '26' AND ipv4_address = '10.1.1.26']
SQL[SELECT mac_address from ipv4_mac WHERE ipv4_address='10.1.1.26' AND port_id='26']
SQL[UPDATE `ipv4_mac` set `mac_address` ='703eac836f36' WHERE port_id='26' AND ipv4_address='10.1.1.26'] .
SQL[SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '514']
SQL[SELECT COUNT(*) from ipv4_mac WHERE port_id = '26' AND ipv4_address = '10.1.1.29']
SQL[SELECT mac_address from ipv4_mac WHERE ipv4_address='10.1.1.29' AND port_id='26']
SQL[UPDATE `ipv4_mac` set `mac_address` ='6cadf8d0a8b4' WHERE port_id='26' AND ipv4_address='10.1.1.29'] .
SQL[SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '514']
SQL[SELECT COUNT(*) from ipv4_mac WHERE port_id = '26' AND ipv4_address = '10.1.1.34']
SQL[SELECT mac_address from ipv4_mac WHERE ipv4_address='10.1.1.34' AND port_id='26']
SQL[UPDATE `ipv4_mac` set `mac_address` ='8c89a564ab81' WHERE port_id='26' AND ipv4_address='10.1.1.34'] .
SQL[SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '514']
SQL[SELECT COUNT(*) from ipv4_mac WHERE port_id = '26' AND ipv4_address = '10.1.1.52']
SQL[SELECT mac_address from ipv4_mac WHERE ipv4_address='10.1.1.52' AND port_id='26']
SQL[UPDATE `ipv4_mac` set `mac_address` ='00231224023e' WHERE port_id='26' AND ipv4_address='10.1.1.52'] .
SQL[SELECT * from ipv4_mac AS M, ports as I WHERE M.port_id = I.port_id and I.device_id = '3']
SQL[DELETE FROM `ipv4_mac` WHERE `port_id` = '26' AND `mac_address` = '00886540daf4'] -

SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='network',`last_discovered_timetaken` ='0.463' WHERE `device_id` = '3'] Discovered in 0.463 seconds


SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','***','1431643717.0979','0.477','1')] ./discovery.php *** 2015-05-15 00:48:37 - 1 devices discovered in 0.477 secs
MySQL: Cell[1/0s] Row[52/0.05s] Rows[1/0s] Column[0/0s] Update[18/0.17s] Insert[1/0.01s] Delete[0/0s]

**Comment by laf** [comment]
Thanks for reporting back :)
