### ISSUE TITLE
Get Arista VRFs from an Arista extra MIB

### ISSUE THREAD

**Issue by Senetus** [librenms/librenms#10179]
Arista VRFs are not detected in the currently implemented way but there is a way to read the VRFs out with an Arista specific MIB. (http://www.circitor.fr/Mibs/Html/A/ARISTA-VRF-MIB.php)

One has to parse it out of the response of ARISTA-VRF-MIB::aristaVrfRoutingStatus, which is .1.3.6.1.4.1.30065.3.18.1.1.1.2.

Example:
snmpwalk -v2c -c xxxx 172.29.173.169  .1.3.6.1.4.1.30065.3.18.1.1.1.2
SNMPv2-SMI::enterprises.30065.3.18.1.1.1.2.3.109.103.116 = Hex-STRING: 00

It returns for example 3.18.1.1.1.2.3.109.103.116 where the first byte after the 2 is protocol identifier so 3 in dec is ipv4 and 9 in dec is ipv6 (I think). The rest are ascii codes in dec so in this case the vrf name would be ‘mgt’ (109 103 116).

After that getting the vrf specific route polling can be done with routing-instance@community string requests.

This should allow for BGP sessions within VRFs to be properly monitored.

See also: https://community.librenms.org/t/vrfs-are-not-added-discovered-for-arista-switches/8155/

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

(EDIT): 
[snmp.txt](https://github.com/librenms/librenms/files/3151358/snmp.txt)
[discovery.txt](https://github.com/librenms/librenms/files/3140914/discovery.txt)
[poller.txt](https://github.com/librenms/librenms/files/3140915/poller.txt)
(/EDIT)

**Comment by PipoCanaja** [comment]
Please also add all the snmp data that is required for the issues, taken on a device that has at least one vrf.

Thanx.

**Comment by esajo** [comment]
Full output of the arista vrf mib:

SNMPv2-SMI::enterprises.30065.3.18.1.1.1.2.3.77.103.116 = Hex-STRING: 00
SNMPv2-SMI::enterprises.30065.3.18.1.1.1.3.3.77.103.116 = STRING: "62003:1"
SNMPv2-SMI::enterprises.30065.3.18.1.1.1.4.3.77.103.116 = INTEGER: 1
SNMPv2-SMI::enterprises.30065.3.18.1.2.1.1.999001 = STRING: "Mgt"

So there is a cleartext string available if looking at the interface membership.

snmpwalk output attached

[arista.txt](https://github.com/librenms/librenms/files/3137905/arista.txt)

**Comment by PipoCanaja** [comment]
Sorry to insist, but you need to provide all info required exactly as described here : 
http://docs.librenms.org/Support/FAQ/#faq20
This is necessary to "simulate" the device and get the support implemented without asking the requester to "send" the device by post :)

**Comment by esajo** [comment]
Sorry I missed that, I was so annoyed with the connection problems :)

Hopefully this formatting is ok, I had to clean them up a bit.

[discovery.txt](https://github.com/librenms/librenms/files/3140914/discovery.txt)
[poller.txt](https://github.com/librenms/librenms/files/3140915/poller.txt)

**Comment by esajo** [comment]
[snmp.txt](https://github.com/librenms/librenms/files/3151358/snmp.txt)
Here the proper bulkwalk dump

**Comment by PipoCanaja** [comment]
Looks much better now. Cannot promise when I'll have a look, I really lack time these days. But at least the information needed is collected.

**Comment by esajo** [comment]
Looks like it would be easier to do with oid 1.3.6.1.4.1.30065.3.18.1.2.1 and with the normal community, only the specific MIB has to be added to the system (ARISTA-VRF-MIB)

**Comment by oroomans** [comment]
Hello, is there any progress about this issue ? 
We are in the same situation where we have multiple VRFs and bgp and ospf peering informations that are out of the default VRF are not seen. 

Thanks.

**Comment by esajo** [comment]
Unfortunately no progress here, I just looked into it a bit to see what can be done but don't have the knowledge to implement anything myself.

**Comment by f0rkz** [comment]
Bumping for visibility.

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11618

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/get-arista-vrfs-from-an-arista-extra-mib/11618/1
