### ISSUE TITLE
python2 code still relevant?

### ISSUE THREAD

**Issue by dvzrv** [librenms/librenms#10170]
Sorry, if I'm breaking the rules here by asking a question, it's just that there is more than sparse documentation on anything related to the topic...
I honestly don't really feel like signing up to the next closed community to discuss things that are relevant for the codebase and therefore belong on a bug tracker.

I'm currently packaging librenms for Arch Linux and find myself in the weird situation of not understanding what part of the application is actually deprecated.
There are a few python2 based scripts floating around, but python2 is soon EOL.
Are these still relevant? If so, it would be great, if they could just be removed, so that people don't accidentally ship and/or use them.

From an outsider's perspective it's hard to understand why there are so many different places for scripts and what their specific dependencies actually are (is requirements.txt relevant for the python2 or python3 scripts? or for both?). This in turn makes it hard for people from distributions to package this software somewhat FHS compliant.

**Comment by murrant** [comment]
A. you don't have to sign up.
B. python2 is not required for any current scripts, it remains for legacy users
C. this is a community project there isn't much cohesion.  I have been working to unify scripts behind the lnms script.
