### ISSUE TITLE
Customers ports are not listed if the case differs

### ISSUE THREAD

**Issue by alarig** [librenms/librenms#10187]
Hi,

Let’s suppose that you have two devices, a customer has one port on each. On the first you set alias "Cust: alarig" and on the other "Cust: Alarig".

Then, if you go to the tab “Customers”, the aggregated graph show both ports, but only the first is listed.

See the screenshots following:
[Customers view](https://pix.milkywan.fr/OOq5fshf.png)
[Old port view](https://pix.milkywan.fr/HaM0XWz1.png)
[New port view](https://pix.milkywan.fr/GlYKjQ8j.png)

**Comment by laf** [comment]
I’d be interested in understanding what you missed telling you not to create an issue here in the default template?
