### ISSUE TITLE
Please help to add IBM AIX.

### ISSUE THREAD

**Issue by dlesel** [librenms/librenms#10199]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

[root@localhost definitions]# cat aix.yaml
os: aix
text: aix
type: server
over:
    - { graph: device_processor, text: 'Processor Usage' }
    - { graph: device_ucd_memory, text: 'Memory Usage' }
    - { graph: device_storage, text: 'Storage Usage' }

discovery:
    - sysObjectID:
        - .1.3.6.1.4.1.8072.3.2.15
        - sysDescr_regex: '/^IBM/'

[generic-cgkent.umm.edu.snmpwalk.txt](https://github.com/librenms/librenms/files/3159004/generic-cgkent.umm.edu.snmpwalk.txt)

[discovery-cgkent.umm.edu.txt](https://github.com/librenms/librenms/files/3158992/discovery-cgkent.umm.edu.txt)
[poller-cgkent.umm.edu.txt](https://github.com/librenms/librenms/files/3158994/poller-cgkent.umm.edu.txt)

**Comment by dlesel** [comment]
Successfully added aix:

[root@localhost definitions]# cat aix.yaml
os: aix
text: 'aix'
type: server
icon: aix
group: ibm
over:
    - { graph: device_bits, text: 'Device Traffic' }
    - { graph: device_processor, text: 'CPU Usage' }
    - { graph: device_mempool, text: 'Memory Usage' }
discovery:
    - sysObjectID:
        - .1.3.6.1.2.1
    - sysDescr_regex: '/AIX version/'
mib_dir:
    - ibm

[root@localhost os]# pwd
/opt/librenms/includes/polling/os
[root@localhost os]# cat aix.inc.php
<?php
$serial = snmp_get($device, 'aixSeSerialNumber.0', '-Oqv', 'IBM-AIX-MIB');
$hardware = snmp_get($device, 'aixSeMachineType.0', '-Oqv', 'IBM-AIX-MIB');

1. hrStorageSize show incorrect size for the file system greater that 8 TB. IBM told me to use aixFsTable from IBM-AIX-MIB.
2. Also i wold like  to change hrStorageName with aixFsMountPoint.

i created files
/opt/librenms/includes/polling/storage/aix.inc.php
/opt/librenms/includes/discovery/storage/aix.inc.php
but it did not work.

Any help appreciated.

Thanks,
david.

**Comment by dlesel** [comment]
1. hrStorageSize shows incorrect size for the file system greater that 8 TB. IBM told me to use aixFsTable from IBM-AIX-MIB.
2. Also i wold like  to change hrStorageName with aixFsMountPoint.

i created files
/opt/librenms/includes/polling/storage/aix.inc.php
/opt/librenms/includes/discovery/storage/aix.inc.php
but it did not work.

Any help appreciated.
Thanks,
david.

**Comment by PipoCanaja** [comment]
Fixed in #10569
