### ISSUE TITLE
Cisco IR1101 RSSI (wireless).

### ISSUE THREAD

**Issue by maladd3** [librenms/librenms#10203]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

https://p.libren.ms/view/27133fe7
https://p.libren.ms/view/e78afa41
https://p.libren.ms/view/ed320ed9

We have new IR1101 routers, previously we ran IR 809 routers (previously issue #7090).  

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/cisco-ir1101-rssi-wireless/11616/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11616
