### ISSUE TITLE
Huawei UPS 2000

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#10212]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

[discovery.txt](https://github.com/librenms/librenms/files/3171627/discovery.txt)
[poller.txt](https://github.com/librenms/librenms/files/3171628/poller.txt)
[snmpwalk.txt](https://github.com/librenms/librenms/files/3171630/snmpwalk.txt)

because ./pbin.sh doesnt work in freebsd !!!

- [x] Please provide as much detail as possible.

no graphs info in librenms :
UPS 2000
SNMP version: V100R002C02B150
Website: http://www.huawei.com
Email: support@huawei.com

- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by kristoferus75** [comment]
Hi I have a question -> whats is with this new device ? What meens  need verification  ?

**Comment by PipoCanaja** [comment]
@kristoferus75 The PR is on the way. Should be merged in the next few days. 
Bye
