### ISSUE TITLE
SMS Eagle Bug

### ISSUE THREAD

**Issue by charlesnwyble** [librenms/librenms#10218]
This is a code bug. I'm posting it here. A very quick one line fix.  I don't see why that shouldn't be opened directly as an issue and I'm not going to wade through the forum. 

Anyway there is a spurious http when the url string is built. diff below. 

diff -u Smseagle.php Smseagle.php.bak
--- Smseagle.php        2019-05-13 10:56:06.748446269 -0500
+++ Smseagle.php.bak    2019-05-13 10:48:09.556439567 -0500
@@ -52,7 +52,7 @@
             'to' => implode(',', $opts['to']),
             'message' => $obj['title'],
         ];
-        $url    = '' . $opts['url'] . '/index.php/http_api/send_sms?' . http_build_query($params);
+        $url    = 'http://' . $opts['url'] . '/index.php/http_api/send_sms?' . http_build_query($params);
         $curl   = curl_init($url);

         set_curl_proxy($curl);

**Comment by murrant** [comment]
If you have a fix, please send a pull request.

**Comment by murrant** [comment]
@charlesnwyble fyi, your url should contain the http://

**Comment by charlesnwyble** [comment]
The http is already included in the database. Trying to omit it from the GUI when setting up the transport, gives an error (forcing inclusion of http). Hence the bug. Working on the pull request now.

**Comment by charlesnwyble** [comment]
PR created 10221
