### ISSUE TITLE
ANS3000RM 

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#10211]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
[snmpwalk.txt](https://github.com/librenms/librenms/files/3171549/snmpwalk.txt)
[poller.txt](https://github.com/librenms/librenms/files/3171550/poller.txt)
[discovery.txt](https://github.com/librenms/librenms/files/3171551/discovery.txt)

because the pbin.sh doesnt work on freebsd !

- [x] Please provide as much detail as possible.

Power device like ATS but current no graphs ! (Gude Expert Transfer Switch)
have always two power inputs -> Primary and secondary

KESS
ANS3000RM
https://www.kess.at/ans3000rm-automatischer-netzumschalter-zur-sicheren-stromversorgung/

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by PipoCanaja** [comment]
Hi @kristoferus75 
There is absolutely no data in the snmpwalk, so we cannot display anything except a logo. Could you check if the SNMP data you provided is complete ? 
Thanx

**Comment by kristoferus75** [comment]
Hi PipoCanaja !

root@vm_corenms:~ # snmpwalk -v2c -c xxxx 172.18.9.42
SNMPv2-MIB::sysDescr.0 = STRING: ATS
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.28507.40
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (2478543204) 286 days, 20:50:32.04
SNMPv2-MIB::sysContact.0 = STRING: infrastruktur@kabelplus.co.at
SNMPv2-MIB::sysName.0 = STRING: ats-eis-tz-svr1-02
SNMPv2-MIB::sysLocation.0 = STRING: Eisenstadt-TZ-Serverraum1
SNMPv2-MIB::sysServices.0 = INTEGER: 72
IF-MIB::ifNumber.0 = INTEGER: 1
IF-MIB::ifIndex.1 = INTEGER: 1
IF-MIB::ifDescr.1 = STRING: eth_cf52259
IF-MIB::ifType.1 = INTEGER: ethernetCsmacd(6)
IF-MIB::ifMtu.1 = INTEGER: 1500
IF-MIB::ifSpeed.1 = Gauge32: 100000000
IF-MIB::ifPhysAddress.1 = STRING: 0:19:32:0:a1:d1
IF-MIB::ifAdminStatus.1 = INTEGER: up(1)
IF-MIB::ifOperStatus.1 = INTEGER: up(1)
IF-MIB::ifLastChange.1 = Timeticks: (2478543204) 286 days, 20:50:32.04
IF-MIB::ifInOctets.1 = Counter32: 4108738168
IF-MIB::ifInUcastPkts.1 = Counter32: 8401392
IF-MIB::ifInNUcastPkts.1 = Counter32: 42741908
IF-MIB::ifInDiscards.1 = Counter32: 0
IF-MIB::ifInErrors.1 = Counter32: 1189
IF-MIB::ifInUnknownProtos.1 = Counter32: 0
IF-MIB::ifOutOctets.1 = Counter32: 726505834
IF-MIB::ifOutUcastPkts.1 = Counter32: 6296600
IF-MIB::ifOutNUcastPkts.1 = Counter32: 57637
IF-MIB::ifOutDiscards.1 = Counter32: 0
IF-MIB::ifOutErrors.1 = Counter32: 6296603
IF-MIB::ifOutQLen.1 = Gauge32: 0
IF-MIB::ifSpecific.1 = OID: SNMPv2-SMI::zeroDotZero

**Comment by PipoCanaja** [comment]
Just to be sure, can you try "snmpwalk -v2c -c xxxx 172.18.9.42 ." (note that a space and a dot are added after the 42)

If no change, then clearly this device does not provide anything useful. You should probably contact the vendor and ask for a proper SNMP implementation.

**Comment by kristoferus75** [comment]
Hi !

Crazy this a ats here a see the primary and secodary power state and it works:


```
snmpwalk -v2c -c xxxx 172.18.24.41
SNMPv2-MIB::sysDescr.0 = STRING: Auto Transfer Switch
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.28507.4
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (3827578600) 443 days, 0:09:46.00
SNMPv2-MIB::sysContact.0 = STRING: 
SNMPv2-MIB::sysName.0 = STRING: yyyyyyyy
SNMPv2-MIB::sysLocation.0 = STRING: yyyyy
SNMPv2-MIB::sysServices.0 = INTEGER: 72
IF-MIB::ifNumber.0 = INTEGER: 1
IF-MIB::ifIndex.1 = INTEGER: 1
IF-MIB::ifDescr.1 = STRING: eth_cf52235
IF-MIB::ifType.1 = INTEGER: ethernetCsmacd(6)
IF-MIB::ifMtu.1 = INTEGER: 1500
IF-MIB::ifSpeed.1 = Gauge32: 10000000
IF-MIB::ifPhysAddress.1 = STRING: 0:19:32:0:2f:64
IF-MIB::ifAdminStatus.1 = INTEGER: up(1)
IF-MIB::ifOperStatus.1 = INTEGER: up(1)
IF-MIB::ifLastChange.1 = Timeticks: (3827578600) 443 days, 0:09:46.00
IF-MIB::ifInOctets.1 = Counter32: 2112418622
IF-MIB::ifInUcastPkts.1 = Counter32: 7336672
IF-MIB::ifInNUcastPkts.1 = Counter32: 19730245
IF-MIB::ifInDiscards.1 = Counter32: 0
IF-MIB::ifInErrors.1 = Counter32: 13
IF-MIB::ifInUnknownProtos.1 = Counter32: 0
IF-MIB::ifOutOctets.1 = Counter32: 404932552
IF-MIB::ifOutUcastPkts.1 = Counter32: 3290933
IF-MIB::ifOutNUcastPkts.1 = Counter32: 217830
IF-MIB::ifOutDiscards.1 = Counter32: 0
IF-MIB::ifOutErrors.1 = Counter32: 3290936
IF-MIB::ifOutQLen.1 = Gauge32: 0
IF-MIB::ifSpecific.1 = OID: SNMPv2-SMI::zeroDotZero

```
but oin this device a see only the ethernet interface :

snmpwalk -v2c -c xxxx 172.18.9.42

```
root@vm_corenms:~ # snmpwalk -v2c -c xxxx 172.18.9.42
SNMPv2-MIB::sysDescr.0 = STRING: ATS
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.28507.40
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (2478543204) 286 days, 20:50:32.04
SNMPv2-MIB::sysContact.0 = STRING: infrastruktur@kabelplus.co.at
SNMPv2-MIB::sysName.0 = STRING: xxxxxxxxx
SNMPv2-MIB::sysLocation.0 = STRING: xxxxxx
SNMPv2-MIB::sysServices.0 = INTEGER: 72
IF-MIB::ifNumber.0 = INTEGER: 1
IF-MIB::ifIndex.1 = INTEGER: 1
IF-MIB::ifDescr.1 = STRING: eth_cf52259
IF-MIB::ifType.1 = INTEGER: ethernetCsmacd(6)
IF-MIB::ifMtu.1 = INTEGER: 1500
IF-MIB::ifSpeed.1 = Gauge32: 100000000
IF-MIB::ifPhysAddress.1 = STRING: 0:19:32:0:a1:d1
IF-MIB::ifAdminStatus.1 = INTEGER: up(1)
IF-MIB::ifOperStatus.1 = INTEGER: up(1)
IF-MIB::ifLastChange.1 = Timeticks: (2478543204) 286 days, 20:50:32.04
IF-MIB::ifInOctets.1 = Counter32: 4108738168
IF-MIB::ifInUcastPkts.1 = Counter32: 8401392
IF-MIB::ifInNUcastPkts.1 = Counter32: 42741908
IF-MIB::ifInDiscards.1 = Counter32: 0
IF-MIB::ifInErrors.1 = Counter32: 1189
IF-MIB::ifInUnknownProtos.1 = Counter32: 0
IF-MIB::ifOutOctets.1 = Counter32: 726505834
IF-MIB::ifOutUcastPkts.1 = Counter32: 6296600
IF-MIB::ifOutNUcastPkts.1 = Counter32: 57637
IF-MIB::ifOutDiscards.1 = Counter32: 0
IF-MIB::ifOutErrors.1 = Counter32: 6296603
IF-MIB::ifOutQLen.1 = Gauge32: 0
IF-MIB::ifSpecific.1 = OID: SNMPv2-SMI::zeroDotZero
```

**Comment by PipoCanaja** [comment]
OK. Not much to find here. You should get in touch with the vendor and add to this issue the feedback they'll give you.

**Comment by PipoCanaja** [comment]
Hi @kristoferus75 
Closing this issue for now. Feel free to reopen it if you get more from the vendor.
