### ISSUE TITLE
Broken overlib graph in /health/metric=processor/view=detail/

### ISSUE THREAD

**Issue by paulgear** [librenms/librenms#1026]
The overlib popup for the processor graph shows a broken image.  See screenshot:

![mrwqb68e](https://cloud.githubusercontent.com/assets/107222/7664912/39d35348-fbe3-11e4-8dbc-1da3833b34c8.png)

I'll look into this if I have the time when investigating bootgrid for the storage table.

**Comment by itscassa** [comment]
Images are working here.

**Comment by f0o** [comment]
https://demo.librenms.org/health/metric=processor/view=detail/

Works for me :/

**Comment by laf** [comment]
Doesn't work for me on the demo :)

It's not the hostname mini graphs btw. If you hover over the green bar graphs it breaks

**Comment by f0o** [comment]
That's correct.
Can reproduce when hovering either the minigraphs or the bar

**Comment by paulgear** [comment]
I can reproduce it easily on the demo site

**Comment by f0o** [comment]
It's an HTML error, I will PR it if I got time today
