### ISSUE TITLE
Ceragon IP-10 Generic device

### ISSUE THREAD

**Issue by hgdatamarsl** [librenms/librenms#10279]
Hello.
I have a wireless radio Ceragon IP-10. After adding to librenms. Does not work, generic device. Please help me. Thank you

[http://www.hgdata.sk/tmp/poller_ceragon.txt](url)
[http://www.hgdata.sk/tmp/discovery-ceragon.txt](url)

**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by kkrumm1** [comment]
We need The snmpbulk walk also

**Comment by hgdatamarsl** [comment]
Sorry this device work. I have snmp version v2c....
