### ISSUE TITLE
SIAE ALFOplus 17GHZ not work

### ISSUE THREAD

**Issue by hgdatamarsl** [librenms/librenms#10278]
Hello.
I have a wireless radio siae alfo plus. After adding to librenms. Does not work. Please help. Thank you

Firmware Version:N10052 01.04.06
Equipment Type:ALFOplus

http://www.hgdata.sk/tmp/poller_SIAE.txt
http://www.hgdata.sk/tmp/siae-172.17.5.2.snmpwalk
http://www.hgdata.sk/tmp/discovery-siae.txt
http://www.hgdata.sk/tmp/siae17.mib

**PLEASE READ FIRST**

**Please do not post bugs or ask questions or feature requests here**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org/c/help).**

To create a new device request please use this link: https://github.com/librenms/librenms/issues/new?template=New-Device.md

**Comment by kkrumm1** [comment]
Your links are not working.

**Comment by hgdatamarsl** [comment]
Fixed It.

**Comment by Wend2019** [comment]
Hi,

Just wondering do you have sufficient information to check out this issue as we have come across this issue also and if you need any more information, we might be able to help?

Thanks

**Comment by jozefrebjak** [comment]
@hgdatamarsl write me a pm, you can in slovak language. SIAE is supported in LibreNMS, i will try to help you.

**Comment by Wend2019** [comment]
Thank you. Unfortunately, I can only speak in English.

**Comment by hgdatamarsl** [comment]
> 
> 
> @hgdatamarsl write me a pm, you can in slovak language. SIAE is supported in LibreNMS, i will try to help you.

Ahoj. Neviem ako mam poslat PM na githube :( Mozes mi prosim poslat mail na: marcel.budzak@hgdata.sk
Dakujem

**Comment by bandziorw** [comment]
I have same problem, pleas help me

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11615

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/siae-alfoplus-17ghz-not-work/11615/1
