### ISSUE TITLE
Selected Port Polling + ignoreIfDesc == issues...

### ISSUE THREAD

**Issue by peelman** [librenms/librenms#10275]
After the update @murrant made in #8650, (which was largely a positive change I remember working with him on and providing feedback for), I have had intermittent issues with polling our Calix E7's, but there is a bit of background here.

We use a _lot_ of Calix equipment, including a ton of E7 vDSL blades and several E7-20s (for GPON delivery).

This creates a couple of frustrating conundrums where the vDSL blades are slower than christmas, making it prohibitive to monitor even 48, let alone the possible 96 ports vDSL ports (in a single chassis, let alone using a multi-chassis config).

On the E7-20 side, you can have 20 blades, each serving anywhere from 4-16 PON splitters, with each splitter serving up to 32 customer ONTs, and each customer having 2-8 ethernet ports.  All of those ethernet ports are seen by the E7 as interfaces on that single device in libre (a theoretical max of almost 82,000 ports, on a single device.  That's obviously worse-case, but we still see a total of about 5000 ports on our largest E7-20 right now, with predominately 2-port and 4-port ONTs.  So doing interface polling of all of that is ridiculous.

Luckily Libre offers a solution, and has forever:

    $config['os']['exa']['bad_if_regexp'][] = '/^(adsl|dsl-fullrate|DSL-FullRate|Dslport|Ont|ont).*/';
    $config['os']['exa']['polling']['selected_ports'] = true;

In those two amazing lines, I can ignore all DSL interfaces, while still monitoring the 1/10Gb uplinks on vDSL chassis, and ignore the ONTs and their interfaces, while still monitoring the 1/10Gb uplinks and even teh 2.5Gbps PON ports on the GPON equipment.

Until #8650.  After that it works _most of the time_, and I don't have good data on why it breaks.

Tonight, the problem started when I purged deleted ports.  I had the page time out on me a couple of times because they hadn't been purged in a while and ESXi had clobbered it up with a bunch of gunk.  During the initial purge run, when things were gummy anyway with that query being slogged through, i started getting Cron emails about polling taking too long. I began seeing Poller times jump considerably on our E7-20s:

![Screen Shot 2019-05-29 at 9 56 14 PM](https://user-images.githubusercontent.com/52936/58602911-a21e2f00-825c-11e9-9aa0-93d7c8b9b568.png)

After a bunch of hair pulling, i finally added two lines to the poller to *force* selected polling, in spite of Tony's efforts:

        // if less than 5 ports or less than 10% of the total ports are skipped, walk the base oids instead of get
        $polled_port_count = count($polled_ports);
        $total_port_count = count($ports);
        $use_bad_if_regex = $config['os'][$device['os']]['bad_if_regexp'] === true;
        $walk_base = $total_port_count - $polled_port_count < 5 || $polled_port_count / $total_port_count > 0.9 || $use_bad_if_regex ;

By testing to see if i'm ignoring interfaces via regex for the current OS and factoring that into whether or not I want to use selected port polling, I was able to force selected port polling back on and caused poller times to plummet back to normal or better than normal.

This is a hack and i'm not advocating that it be merged.  But i'm going to have to continue forward with it until we square the circle of what libre's port count in the database is, vs what the actual port count on the device is, because as long as interfaces can be ignored at discovery time, you can't count on those two counts being the same (I think Tony and I had a debate about this at the time, its probably still in our discord or IRC chat history).

Largely, I agree with the logic he built into the Selected Port Polling piece; but I either need a nerd knob I can turn on to override it per-device or per-os, (which is kinda what Selected Port Polling is in the first place), or I need it to be comparing the actual number of interfaces as polled from the device, instead of what's in the database.  The latter option is problematic, because just walking even the bare minimum IFMIB OIDs just to get the count can take 600+ seconds on our E7-20s right now (using the `collect-port-polling.php` script took over 11 minutes on one, and the "selected" option brought it down from 671s to 21s, for one example; I lost the actual output from both of our worst devices to some terminal stupid (watch and nano and bad at destroying scrollback).

To head off an obvious question:

> But why not just stop ignoring everything and use selected port polling "naturally"?

Because everytime outside plant adds an ONT (which can happen tens, if not dozens of times per day), they'd add 2+ interfaces that would have to manually go be unchecked in Libre.  Ignoring them at discovery time isn't flawless, but its much better than the alternative.

**Comment by peelman** [comment]
really @kkrumm1?  you see this as a support request?

**Comment by kkrumm1** [comment]
Yes this is ONLY FOR NEW DEVICE requests and it’s stated all over here.

Your post should be made in the forums or in discord.
