### ISSUE TITLE
SUMMIT DEVELOPMENT wireles radio

### ISSUE THREAD

**Issue by hgdatamarsl** [librenms/librenms#10280]
Hello.
I have a wireless radio SUMMIT DEVELOPMENT. After adding to librenms. Does not work, generic device. Please help me. Thank you

http://www.hgdata.sk/tmp/poller_sdv.txt
http://www.hgdata.sk/tmp/discovery-sdv.txt
http://www.hgdata.sk/tmp/sdv.snmpwalk

**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11614

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/summit-development-wireles-radio/11614/1
