### ISSUE TITLE
Eltek Smartpack 2

### ISSUE THREAD

**Issue by hgdatamarsl** [librenms/librenms#10282]
Hello.
I have a Power Eltek Smart Pack 2 . After adding to librenms. Does not work, generic device. Please help me. Thank you

http://www.hgdata.sk/tmp/poller-eltek.txt
http://www.hgdata.sk/tmp/discovery-eltek.txt
http://www.hgdata.sk/tmp/eltek.snmpwalk

**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
Your walk is missing the sysObjectID and others.  Make sure you run it with the dot (`.`) at the end.

**Comment by hgdatamarsl** [comment]
I run this:
root@librenms:/opt/librenms# snmpbulkwalk -OUneb -v2c -c public 172.17.0.175 .  | ./pbin.sh  

https://p.libren.ms/view/a61352e5

**Comment by murrant** [comment]
So `snmpget -v2c -c public 172.17.0.175 SNMPv2-MIB::sysDescr.0` returns nothing?

**Comment by hgdatamarsl** [comment]
root@librenms:/opt/librenms# snmpget -v2c -c public 172.17.0.175 SNMPv2-MIB::sysDescr.0
MIB search path: /root/.snmp/mibs:/usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf:/usr/share/mibs/site:/usr/share/snmp/mibs:/usr/share/mibs/iana:/usr/share/mibs/ietf:/usr/share/mibs/netsnmp
Cannot find module (SNMPv2-MIB): At line 0 in (none)
SNMPv2-MIB::sysDescr.0: Unknown Object Identifier

snmpwalk -OUneb -v1 -c public 172.17.0.175 . | ./pbin.sh :
https://p.libren.ms/view/ce49c59c

**Comment by hgdatamarsl** [comment]
I have change file in /opt/librenms/includes/definitions/enexus.yaml
line: 14 
of :  value: '/Micropack System|Smartpack S/'
to:  value: '/Micropack System|SmartPack2|Smartpack S/'

and librenms discover device :)

**Comment by murrant** [comment]
@hgdatamarsl I suggest you submit the change to be included upstream. :)

**Comment by hgdatamarsl** [comment]
:( not work correctly.
http://www.hgdata.sk/tmp/smartpack2_librenms.png
http://www.hgdata.sk/tmp/smartpack2_web.png

Librenms not show backup AC current, only 48V
Librenms not show curent mains

**Comment by PipoCanaja** [comment]
@hgdatamarsl This is something else you can correct later : 
- Step 1: The device is identified correctly as enexus OS. 
- Step 2: You can add sensors/values to be discovered/polled in /opt/librenms/includes/definitions/discovery/enexus.yaml : This is where all sensors currently discovered are added. 

As murrant said, you can then create a PR with the 2 updated versions of the yaml files, and you'll also be asked to collect test-data (we'll help you on this).

**Comment by Simonk007** [comment]
> :( not work correctly.
> http://www.hgdata.sk/tmp/smartpack2_librenms.png
> http://www.hgdata.sk/tmp/smartpack2_web.png
> 
> Librenms not show backup AC current, only 48V
> Librenms not show curent mains

@hgdatamarsl how did you manage to have ELTEK scanned into Librenms.
I have about 900 Elteks online, i would love to monitor. Please help me if u can.

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/eltek-smartpack-2/11613/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11613
