### ISSUE TITLE
LibreNMS not reading correct MTU for jumbo frames on FS switches (fs.com)

### ISSUE THREAD

**Issue by hrv231** [librenms/librenms#10293]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
[snmpbulkwalk.txt](https://github.com/librenms/librenms/files/3242225/snmpbulkwalk.txt)
[poller.txt](https://github.com/librenms/librenms/files/3242226/poller.txt)
[discovery.txt](https://github.com/librenms/librenms/files/3242227/discovery.txt)

- [x] Please provide as much detail as possible.

LibreNMS sees all the FS switches ports as 1500 MTU, doesn't detect jumbo frames packets.
In this case, ports 14 to 20 have the command "jumboframe enable" on the switch, and LibreNMS shows them as 1500 MTU.
![image](https://user-images.githubusercontent.com/41212308/58722882-7b134a80-838d-11e9-9214-24d3859851a4.png)

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by hrv231** [comment]
I'm not asking for help, this is a problem from LibreNMS, not a configuration problem.

**Comment by murrant** [comment]
Actually, it isn't a problem.  The routing MTU on those ports is most likely 1500.  You changed the system MTU for switched packets.   Check the SNMP output if you like the device is returning 1500.  Contact device manufacture if you have further questions.
