### ISSUE TITLE
API port data return ifDesc/ifAlias

### ISSUE THREAD

**Issue by sngx13** [librenms/librenms#10292]
Hi,

At the moment API call to "/api/v0/devices/:hostname/ports" returns ifName which is great but not much use if you are parsing this data and have no idea what it is. Would be nice to have ifDesc or / and ifAlias added (maybe even port id) e.g:

{
    "status": "ok",
    "ports": [
        {
            "ifName": "GigabitEthernet2/0.101", 
            **_"ifDesc": "Customer ABC"_**,
            **_"port_id": (int)_** 
        }
    ],
}%                                            

Thank you.

**Comment by kkrumm1** [comment]
This issue has been closed as it isn't classed as a new device request.

For help and or feature request please use our Discord server or the community site: https://docs.librenms.org/Support
