### ISSUE TITLE
Mysql Indexing Required for Notifications Query to function

### ISSUE THREAD

**Issue by susmadel** [librenms/librenms#10337]
Distributed LibreNMS server with single webui, rrdcache and memcache on 1 server.  Two other pollers and a final server with mysql.

explain select count(*) as aggregate from `notifications` left join `notifications_attribs` on `notifications_attribs`.`notifications_id` = `notifications`.`notifications_id` where (`notifications_attribs`.`key` = 'sticky' and `notifications_attribs`.`value` = 1) or (not exists (select 1 from `notifications_attribs` where notifications.notifications_id = notifications_attribs.notifications_id and `notifications_attribs`.`user_id` = 62));
+----+--------------------+-----------------------+------------+-------+---------------+------------------------------+---------+------+------+----------+----------------------------------------------------+
| id | select_type        | table                 | partitions | type  | possible_keys | key                          | key_len | ref  | rows | filtered | Extra                                              |
+----+--------------------+-----------------------+------------+-------+---------------+------------------------------+---------+------+------+----------+----------------------------------------------------+
|  1 | PRIMARY            | notifications         | NULL       | index | NULL          | notifications_severity_index | 5       | NULL |   46 |   100.00 | Using index                                        |
|  1 | PRIMARY            | notifications_attribs | NULL       | ALL   | NULL          | NULL                         | NULL    | NULL |  974 |   100.00 | Using where; Using join buffer (Block Nested Loop) |
|  2 | DEPENDENT SUBQUERY | notifications_attribs | NULL       | ALL   | NULL          | NULL                         | NULL    | NULL |  974 |     1.00 | Using where                                        |
+----+--------------------+-----------------------+------------+-------+---------------+------------------------------+---------+------+------+----------+----------------------------------------------------+

 new indexes on  (`notifications_id`,`key`,`value`)(`notifications_id`,`user_id`)should take less than 1 sec 

After creating new indexes, below is the explain plan. Please see the 'ROWS' column, numbers of rows read are greatly reduced and i dont see this query any more in slow query log.

explain select count(*) as aggregate from `notifications` left join `notifications_attribs` on `notifications_attribs`.`notifications_id` = `notifications`.`notifications_id` where (`notifications_attribs`.`key` = 'sticky' and `notifications_attribs`.`value` = 1) or (not exists (select 1 from `notifications_attribs` where notifications.notifications_id = notifications_attribs.notifications_id and `notifications_attribs`.`user_id` = 62));
+----+--------------------+-----------------------+------------+-------+--------------------------------------------------+------------------------------+---------+-----------------------------------------------+------+----------+--------------------------+
| id | select_type        | table                 | partitions | type  | possible_keys                                    | key                          | key_len | ref                                           | rows | filtered | Extra                    |
+----+--------------------+-----------------------+------------+-------+--------------------------------------------------+------------------------------+---------+-----------------------------------------------+------+----------+--------------------------+
|  1 | PRIMARY            | notifications         | NULL       | index | NULL                                             | notifications_severity_index | 5       | NULL                                          |   52 |   100.00 | Using index              |
|  1 | PRIMARY            | notifications_attribs | NULL       | ref   | notification_id_key_value,notification_id_userid | notification_id_key_value    | 4       | librenms.notifications.notifications_id       |   33 |   100.00 | Using where; Using index |
|  2 | DEPENDENT SUBQUERY | notifications_attribs | NULL       | ref   | notification_id_key_value,notification_id_userid | notification_id_userid       | 8       | librenms.notifications.notifications_id,const |    1 |   100.00 | Using index              |
+----+--------------------+-----------------------+------------+-------+--------------------------------------------------+------------------------------+---------+-----------------------------------------------+------+----------+--------------------------+

The issue is that now LibreNMS ./validate.php is showing issues with the schema.  

[FAIL]  We have detected that your database schema may be wrong, please report the following to us on Discord (https://t.libren.ms/discord) or the community site (https://t.libren.ms/5gscd):
	[FIX]:
	Run the following SQL statements to fix.
	SQL Statements:
	 ALTER TABLE `notifications_attribs` DROP INDEX `notification_id_key_value`;
	 ALTER TABLE `notifications_attribs` DROP INDEX `notification_id_userid`;

We want to ensure our LibreNMS will function and that daily.sh will run.  Please let me know what else is needed for this issue.

**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
@susmadel the index looks good, if you want to avoid local changes, submit a Pull Request to change it upstream.  https://laravel.com/docs/migrations
