### ISSUE TITLE
Ubiquiti Edgepower

### ISSUE THREAD

**Issue by tomck** [librenms/librenms#10330]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

https://p.libren.ms/view/23e326a4
https://p.libren.ms/view/84566970
Edited: https://p.libren.ms/view/68d352d0

- [x] Please provide as much detail as possible.

The Edgepower device is missing a few lines of data, primarily the ones about power consumption and generation. The MIBs can be found in this thread:
https://community.ubnt.com/t5/EdgePower/EdgePower-1-2-0Beta1-Release-Includes-SNMP-UNMS/td-p/2227999

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by PipoCanaja** [comment]
Hi @tomck 
Could you please ensure that the snmpwalk data is added to this Issue ? Without it, the issue cannot be processed. 
Thanx

**Comment by kkrumm1** [comment]
This will be reopened once the info requested is supplied.

**Comment by tomck** [comment]
Sorry, didn't catch the e-mail. You have to switch from -v 2c to -v 1 and from snmpbulkwalk to snmpwalk to get data. https://p.libren.ms/view/68d352d0

**Comment by tomck** [comment]
@kkrumm1 Could you reopen as promised?

**Comment by jepke** [comment]
Im stumbling upon the same thing with our Edgepowers, would like to get the power data in librenms. If someone can point me in the direction where to find the code for it i can go and try to make it work.

**Comment by jepke** [comment]
Spend a bit of time getting missing power values  #11254

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11611

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/ubiquiti-edgepower/11611/1
