### ISSUE TITLE
Add ability to overwrite interface description parser for Core/Peer/Transit

### ISSUE THREAD

**Issue by killsudo** [librenms/librenms#1033]
Based upon closed issue #998

It would be nice to also have the ability to customize the parser for Core/Peer/Transit links to enable librenms users the ability to quickly integrate with existing network interface descriptions.

As an example we use the following on interface descriptions,

Core = X-Connect:

Peer = IXP:

Transit = Uplink:

**Comment by laf** [comment]
Merged in now. See docs for additional config options.
