### ISSUE TITLE
Alertlog entries - device object header

### ISSUE THREAD

**Issue by killsudo** [librenms/librenms#1034]
Add ability to enable an alert entry header for the device object that triggered the alert.

As seen in the screen shot it's nice to know the device and alert message but it's useless without being able to quickly see which interface generated the port over-utilization.

![librenms-alerts](https://cloud.githubusercontent.com/assets/1152396/7669185/ab66416e-fc29-11e4-97ff-4086bc7f1e30.jpeg)

**Comment by f0o** [comment]
Yeah I'll merge the same code like in the alerts code. Should be done by today evening (utc)
