### ISSUE TITLE
Microsoft Service Monitoring via PyWinRM

### ISSUE THREAD

**Issue by killsudo** [librenms/librenms#1035]
This is a lofty request but further down the road once LibreNMS starts to settle up on pressing matters it would be nice to eventually see Microsoft Service monitoring if LibreNMS plans to keep the service monitoring feature.

PyWinRM allows a Linux user of LibreNMS to install the kerberos package in their distro and join a Microsoft Active Directory domain. Once kerberos tickets can be issued to the linux host, PyWinRM can be used to poll service statistics of Windows/AD/SQL/IIS etc as Microsoft adds WinRM across products.

PyWinRM also supports TLS requests to ensure a secure monitoring platform and because kerberos is used, LibreNMS would not need to store username and password values. AD can then be leveraged to restrict the librenms user for further security when monitoring a Microsoft environment.

https://pypi.python.org/pypi/pywinrm

Zenoss leverages PyWinRM for Microsoft monitoring and may provide some good idea's.

https://github.com/zenoss/ZenPacks.zenoss.Microsoft.Windows

http://wiki.zenoss.org/ZenPack:Microsoft_Windows

**Comment by f0o** [comment]
Sounds promising

**Comment by laf** [comment]
Needs us to record login details for it to be used. We'd need to come up with a really secure way of storing these as I'd hate people just chucking admin details into LibreNMS as I'm sure @f0o would as well :)

**Comment by killsudo** [comment]
If anyone wants to pick this up in the future, you can bypass the need to store Windows users/pass in LibreNMS if your have an Active Directory environment.

The easiest way to integrate would be to run LibreNMS on centos7 or another newer distro that supports 'realm'.

The first half of this guide for be applicable to getting kerberos support and a valid ticket from AD for PyWinRM to use for calls to Windows WinRM hosts.
http://www.hexblot.com/blog/centos-7-active-directory-and-samba

If you don't have Microsoft Server AD support, you can deploy Samba4 to enable open-source AD auth between linux and Microsoft OS's while still using Microsoft AD tools to configure and manage Samba4.

**Comment by killsudo** [comment]
Debian 8 support - http://www.alandmoore.com/blog/2015/05/06/joining-debian-8-to-active-directory/

**Comment by killsudo** [comment]
https://wiki.samba.org/index.php/Samba_AD_DC_HOWTO

**Comment by f0o** [comment]
Yeah Krb/LDAP is the way to go, have a central Host-Based ACL manager and then deny liability on librenms' side for the lack of restrictive ACLs that go to the WMI/PyWinRM hosts.
(I know that deny liability part sounds rough, but we really dont want write access to any devices with credentials that are stored in the wild)

**Comment by XxPatrickxX** [comment]
Interested in support for this functionality as well.

**Comment by XxPatrickxX** [comment]
Including a pre-compiled version of wmic (http://techedemic.com/2014/09/17/installing-wmic-in-ubuntu-14-04-lts-64-bit/) would provide the functional backend for it. At that point it's straight up WMI calls. As for credential storing it would need to be done via config file or the like unless the box was joined to the domain the librenms user was a domain user.

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Really not happy with storing wmi credentials in plaintext.
But I do like to see wmi support.
Maybe we can think of a less plaintext storage of the credentials. Does windows support any asymetric authentication?


On September 23, 2015 5:08:33 AM GMT+02:00, Cheezehead <notifications@github.com> wrote:
>Including a pre-compiled version of wmic
>(http://techedemic.com/2014/09/17/installing-wmic-in-ubuntu-14-04-lts-64-bit/)
>would provide the functional backend for it. At that point it's
>straight up WMI calls. As for credential storing it would need to be
>done via config file or the like unless the box was joined to the
>domain the librenms user was a domain user.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/1035#issuecomment-142478429
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJPBAEBCgA5BQJWAkilMhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikg
PGYwb0BsaWJyZW5tcy5vcmc+AAoJEJMZKtVWOFzBBBQQAJ0XUXnNYyJ3v0Wp9dpC
NJPVhVP8226GNBHkZsVOpixt3bO3wCEkGLgBJj89aruL0+SvA8bqZVNJK7Yhfgnf
UFnbnQmOad3NeyxWIjKxnvyHYR+5pCPKirhjHr6ttcy9zsb38sz589kbfo5q0VD9
glAAhH+cbkDyX996AHaCsufv7ZMeVJJCY0SdOag0swyhMGsgRSqBapmEcduEeXT2
zJto73C1PHWPGLwMjrUQ99ReEXJ+n4hTflTeU5mr6C1Th2q3H/1Xs/Hdq71JO8gl
P+zl+U2dVs48swkhQzPne0mT5MJbLcqgQnPi59vF3dBsY9TR16upykbquFLxMWbA
9PvAcSQhM2AHiuerYjj04r/tL1Ho8s5lLgwNr4hZbwGCpRfKlcy0uvypgJhKHkbw
aJpIA0Sptrmc8nhgSMwMKpQ/sQ0PfinA9byDrIX9qXMt7CmF/27NxLDvFHrieX+s
fr3U4twzBGoyMBdEpmSXM+tbbnoazmXfS+k5qnEbzj6Sv9fdn9kXrxelS1pIfry5
zHQq26o2hoqGlMgBK/moiHJLWYnt+JU0FiqwnTm7998IQOrOgNyXrh+dNv4z2rnu
hDxb5dlXk1ehq+N64z3U/cMJS5xWLP6MkuUa4de47F2pvFf5KteThoyvpavf9INo
Eay+rNj/q5/MEGFvyN2cmR7p
=GH76
-----END PGP SIGNATURE-----

**Comment by XxPatrickxX** [comment]
Masking the credentials
 ./wmic //hostname -A authfile.pw "SELECT * FROM win32_logicaldisk"

authfile.pw contents
username = myusername
password = mypassword
domain = myNTDomain   (not necessarily mydomain.com)

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
