### ISSUE TITLE
Nagios Dig Monitor Application

### ISSUE THREAD

**Issue by killsudo** [librenms/librenms#1036]
We utilize the following feature for monitoring DNS servers for basic response time. The bind/TinyDNS etc applications are nice but sometimes you just want to add a DNS server to LibreNMS and configure a basic dns lookup request monitor to graph/alert on dns query response times for a test record.

http://wiki.zenoss.org/ZenPack:Dig_Monitor

DNS responses are critical in a proper NMS environment and having this check to give you a heads up about potential issues before your NMS starts claiming devices are down or services due to dns lookup failures.

**Comment by killsudo** [comment]
This feature can leverage the check_dig Nagios plugin

**Comment by f0o** [comment]
This already exists, see the 'dns' check under services, it utilizes check_dns from nagios-plugins which is the same as check_dig (at least for upstream debian wheezy)

**Comment by f0o** [comment]
Moving 'dns' check to use nagios_dig to enable the passing of dig's arguments, will also solve #1037
