### ISSUE TITLE
Nagios DNS Monitor Application for DNS records

### ISSUE THREAD

**Issue by killsudo** [librenms/librenms#1037]
In a dual-stacked IPv4 and IPv6 world dns hostnames are critical more then ever in a proper NMS environment. Checking the result of a returned dns query can be the difference between a successful NMS system and chasing your tail as to why services are failing in the NMS and the realworld.

Sometimes you simply have a dns record that you need to ensure exists or your environment might as well be offline to the world even if IP connectivity is fine.

Having the ability for your NMS to query a specific name server for a specific record and then checking that record against a defined result opens up many NMS options.

1. If you want to ensure that you company website is returning the primary IP. This would allow you check the dns query result to decided if everything is healthy or if you failed over to a DR site.

2. If you want to monitor a critical hostname for a specific IP. If another team member thinks they know better and modifies a domain name record for say an Email cluster. By default your MX record should return your mail clusters smtp HA/VIP IP to load-balance smtp connections. The employee updates the record to a specific IP. You can be alerted that this critical record has changed and take action. Maybe the change was needed during an emergency to restore service to one working box while you fix the other box's. Knowing this happened and having a visual alert to remind you to fix the dns record is helpful.

3. If you are running a Split DNS environment with External and Internal networks with both IPv4 and Ipv6 and over-lapping hostnames so humans don't need to remember two different hostnames based upon the network they are connected to. You need the ability to query a specific DNS server for a specific record to ensure both External and Internal environments are healthy.

4. If you are running a dual-stacked environment you need to confirm that a hostname returns the proper IP for both an A record and AAAA record.

http://wiki.zenoss.org/ZenPack:DNS_Monitor

This feature can leverage the check_dig Nagios plugin

**Comment by laf** [comment]
I've just tagged this as might be fixed in PR #2214 as it extends out the nagios service checks which allow you to do all of this.
