### ISSUE TITLE
Alcatel-Lucent Stellar AP Support

### ISSUE THREAD

**Issue by difi80211g** [librenms/librenms#10374]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

ould like to request the Stellar Wireless line of access points (https://www.al-enterprise.com/en/products/wlan 1) be added to the supported devices and hopefully the new wireless section. The device polled in the below files is the AP-1231.

discovery:
https://p.libren.ms/view/e96280b9

poller:
https://p.libren.ms/view/7e6f5010

snmbulkwalk:
https://p.libren.ms/view/976312b6

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11673

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/alcatel-lucent-stellar-ap-support/11673/1
