### ISSUE TITLE
Have the pbin.sh script sanitize identifiable information before posting

### ISSUE THREAD

**Issue by SandMouse** [librenms/librenms#10386]
When posting device information using the pbin.sh script the posted information is not sanitized and may contain identifiable information.

**Comment by kkrumm1** [comment]
Please jump on discord https://discord.gg/librenms

**Comment by SandMouse** [comment]
I'll try and catch you tomorrow. If not monday.

Cheers.

On 27 Jun 2019, at 21:59, Kevin Krumm <notifications@github.com> wrote:

Please jump on discord https://discord.gg/librenms
