### ISSUE TITLE
add/update Senturion Environmental Manager (sensatronics-em1)

### ISSUE THREAD

**Issue by SandMouse** [librenms/librenms#10385]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

A Sensatronic Senturion SFE020 can be added to LibreNMS and is recognized as a "sensatronics-em1" type device. The device can be polled using SNMPv1 and returns data. (see supplied links). The defined OID's in the YAML file (/opt/librenms/includes/definitions/discovery/sensatronics-em1.yaml)
 do not correspond with the OID's supplied by the device. The device supplies the data but is not graphed.

https://p.libren.ms/view/48c2a636
https://p.libren.ms/view/db7bf2ab
https://p.libren.ms/view/86c9f230

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/add-update-senturion-environmental-manager-sensatronics-em1/11610/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11610
