### ISSUE TITLE
Blank map

### ISSUE THREAD

**Issue by krakazyabra** [librenms/librenms#10389]
Hi!  
Have problem with maps.  
After adding 5th device in a group, the map (Device Groups Map) becomes blank. If delete the 5th device, the map still is blank, and nothing else helps.  
The group looks like on the picture, all devices are present and polled. The validation passed, version is up-to-date.  
Working variant
![изображение](https://user-images.githubusercontent.com/26598203/60339082-080aed00-99a8-11e9-9f8c-79fff4a0d4df.png)
![изображение](https://user-images.githubusercontent.com/26598203/60339105-1a852680-99a8-11e9-8a13-7e5a198e0278.png)
Adding another device  
![изображение](https://user-images.githubusercontent.com/26598203/60339198-69cb5700-99a8-11e9-905e-c6fb747f8769.png)
The map became blank.  
but if I'll be lucky, and point the mouse to the right place, i'll get the hover with graph
![изображение](https://user-images.githubusercontent.com/26598203/60339244-85cef880-99a8-11e9-8dc0-00f55dd36a65.png)

The logs of nginx and librenms are fine, no errors. The only one message i have - is from browser console:  
```
    TypeError: t is null
    overrideOpacity    https://librenms.domain.org/js/vis.min.js:25
    value                     https://librenms.domain.org/js/vis.min.js:34
    value                     https://librenms.domain.org/js/vis.min.js:34
    value                     https://librenms.domain.org/js/vis.min.js:30
    value                     https://librenms.domain.org/js/vis.min.js:43
    value                     https://librenms.domain.org/js/vis.min.js:43
    value                     https://librenms.domain.org/js/vis.min.js:43
    emit                       https://librenms.domain.org/js/vis.min.js:26
    <anonim>              self-hosted:985
    value                     https://librenms.domain.org/js/vis.min.js:43
    value                     self-hosted:985
```  
So, what is it and how to repair?

**Comment by F47991** [comment]
I am seeing the same issue. In my installation it looks like its related to nodes that are down.
For a device group were all nodes are up the map is working. But with a device group where one of the nodes are down I only get some of the links shown and none of the devices (See image below).
![image](https://user-images.githubusercontent.com/46204365/60376229-b9903980-9a0d-11e9-9b87-44864ebf9a93.png)

The installation is running 1.52-81-g197947d4a, Apache/2.4.29 (Ubuntu).

**Comment by F47991** [comment]
From my Browser Console log:
```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead
jquery.min.js:2:21
TypeError: t is null
vis.min.js:25:8818
    overrideOpacity https://librenms.domain.org/js/vis.min.js:25
    value https://librenms.domain.org/js/vis.min.js:34
    value https://librenms.domain.org/js/vis.min.js:34
    value https://librenms.domain.org/js/vis.min.js:30
    value https://librenms.domain.org/js/vis.min.js:43
    value https://librenms.domain.org/js/vis.min.js:43
    value https://librenms.domain.org/js/vis.min.js:43
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://librenms.domain.org/js/vis.min.js
Source Map URL: vis.map

Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://librenms.domain.org/js/jquery.min.js
Source Map URL: jquery-1.10.2.min.map

Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://librenms.domain.org/js/vis.min.js
Source Map URL: vis.map

Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://librenms.domain.org/js/jquery.min.js
Source Map URL: jquery-1.10.2.min.map
```

**Comment by krakazyabra** [comment]
I'm not asking for help, i'm posting bug.

**Comment by kkrumm1** [comment]
This is not the place to post bugs it stated that when you click on the open issue.

**Comment by vadonka** [comment]
The issue is still persist. I run into it too. Fresh install centos 7+nginx
