### ISSUE TITLE
Dispatcher Service: Can't disable REDIS

### ISSUE THREAD

**Issue by InsaneSplash** [librenms/librenms#10409]
When running the new v2 Dispatcher Service on a system running a existing Redis server with the redis-py module, one is not able to get the service to ignore this and continue. The service tries to load the Redis module and configuration defaults but since there is an old version of Redis available, it then tries to use it. It will do this even if there are no attributes configured within the .env file.

This is an issue when the Redis server is for example Version 3.x or not required for distributed polling.

Is it possible to only load Redis if there is a REDIS_HOST configured in the .env file?

**Comment by kkrumm1** [comment]
You could have posted on the forums
