### ISSUE TITLE
Smoking outgoing graphs broken

### ISSUE THREAD

**Issue by steffann** [librenms/librenms#10414]
Smokeping outgoing graphs are not working because of looking in the wrong place when smokeping.integration is enabled, and because of not converting underscores in RRD filenames to dots.

Pull request with fixes for this incoming :)

**Comment by laf** [comment]
Thanks for the issue, we don't need it for tracking though so I'll close it down and await the PR :D

**Comment by steffann** [comment]
I'll send it once I have run `./scripts/pre-commit.php`. I don't expect anything, but that's what everybody says before they run it ;)
