### ISSUE TITLE
apc AP7921 power usage

### ISSUE THREAD

**Issue by guy-new** [librenms/librenms#10418]
Recent convert from observium.

In observium my AP7921 has the power usage tracked which doesn't seem to show up in librenms.

Is it possible to add a graph for the power "Watts", the OID for it is "iso.3.6.1.4.1.318.1.1.12.1.16.0"

**Comment by kkrumm1** [comment]
Please don’t delete the text that said DO NOT DELETE. Also you need to provide all the info asked for in the template issues. Which you chose to ignore.

**Comment by guy-new** [comment]
There was no  "DO NOT DELETE" message at the top of the template..

it said: 

**PLEASE READ FIRST**

**Please do not post bugs or ask questions or feature requests here**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org/c/help).**

To create a new device request please use this link: https://github.com/librenms/librenms/issues/new?template=New-Device.md


if you can point me to the template with the questions you need answered then I'll happily fill that in

**Comment by kkrumm1** [comment]
When you click on create new issue follow the new device issue. It has everything we need. 
![B725C055-EFAD-4379-8139-E3A0436E7A14](https://user-images.githubusercontent.com/27959419/60734340-3f801900-9f15-11e9-9d62-5a23d9eaf583.png)

**Comment by guy-new** [comment]
Ok will do.. I thought as this device already existed, and just adding a graph for an object it didn't count as a new device.
