### ISSUE TITLE
JunOS (EX-/MX-Series): OSPF Monitoring

### ISSUE THREAD

**Issue by MrXermon** [librenms/librenms#10433]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

It would be great if we could monitor the OSPF status (neighbors, areas, route count) via LibreNMS. I attached the JunOS OSPF MIB to the issue.

./discovery.php -h HOSTNAME -d | ./pbin.sh
> https://p.libren.ms/view/16c48b06

./poller.php -h HOSTNAME -r -f -d | ./pbin.sh
> https://p.libren.ms/view/7a85efe4

snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh
> https://p.libren.ms/view/d969acd9

[MIB File for OSPF in JunOS](https://github.com/librenms/librenms/files/3376590/mib-jnx-ospfv3mib.txt)

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by MrXermon** [comment]
Is there already a update or sth. i can help you guys with?

**Comment by kkrumm1** [comment]
No update nobody is actively working on issues. ..Sure you can submit the code for this

**Comment by zombah** [comment]
OSPF is working for Junos MX series, maybe it is better to clarify what exactly is missing? Supplied mib file is for OSPF IPv6 support as i understand.

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11609

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/junos-ex-mx-series-ospf-monitoring/11609/1
