### ISSUE TITLE
Add support: PICOS enterprise switches

### ISSUE THREAD

**Issue by rbax82** [librenms/librenms#10441]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Could you please add device support for Pica8 based switches including environmental sensors? OS name is picos. [PICA8 MIB file](https://docs.pica8.com/display/PICOS2111cg/Pica8+Private+MIB)

./discovery.php -h HOSTNAME -d | ./pbin.sh
` https://p.libren.ms/view/cfd8d4d3`
./poller.php -h HOSTNAME -r -f -d | ./pbin.sh
`https://p.libren.ms/view/c8c222f9`
snmpbulkwalk was too large for pbin so I threw it in dropbox.
`https://www.dropbox.com/s/s9dq9ejjwt5utnp/picos_snmpbulkwalk.txt?dl=0`

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by rbax82** [comment]
Is there anything I can do to help with this?

**Comment by kkrumm1** [comment]
Yes you can submit a PR for this with all the code.

**Comment by PipoCanaja** [comment]
Hello @rbax82 
The snmp implementation for this device is weird : temperatures, for instance, are transmitted as strings, which makes it difficult for us to parse them using the standard way. I did implement very basic support right now, using the standard method of LibreNMS. If you need the temperature metrics, we can help you contribute them. 
You can test current implementation by doing this : 
`./scripts/github-apply 11185`

**Comment by rbax82** [comment]
thank you. =)
