### ISSUE TITLE
Geist Watchdog External Sensor Discovery Not Working

### ISSUE THREAD

**Issue by VanillaNinjaD** [librenms/librenms#10449]
Old Issue
https://github.com/librenms/librenms/issues/8393

Since the last issue was closed I figured I'd open a new one and attach the relevant data. Geist released another new firmware (v3.4.0) and apparently a new MIB file with Vertiv???

Can someone that is way smarter than me take a look and see if I'm just missing something?

Discovery
https://p.libren.ms/view/dfcea0c2

Poller
https://p.libren.ms/view/65a213be

snmpbulkwalk
https://p.libren.ms/view/eaee4297

VERTIV-BB-MIB
https://p.libren.ms/view/4dfb753f#L2

**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by PipoCanaja** [comment]
Looks like the necessary data is here. 
@VanillaNinjaD If you feel it, just try to implement it yourself by adding to the existing YAML files for this OS. 
https://docs.librenms.org/Developing/Support-New-OS/

You can ask for help here or in community forums or in discord.

When done, we'll also help you to send us a PullRequest so we can merge it into LibreNMS.

Bye

**Comment by Munzy** [comment]
```
./scripts/new-os.php -h 475 -o vertiv-watchdog -t environment -v vertiv

sysDescr: idf-s-watcher.rg
sysObjectID: .1.3.6.1.4.1.21239.42.1.31

We already detect this device as OS geist-watchdog type, do you want to continue to add sensors? (Y/n) y
ctrl+c to exit now otherwise please enter the MIB name including path (url is also fine) for us to check for sensors: VERTIV-BB-MIB
Do you want to add a2dSensorTable? (y/N) y
env: 'mib2c': No such file or directory

In Yaml.php line 75:

  Argument 1 passed to Symfony\Component\Yaml\Yaml::parse() must be of the type string, null given, called in /opt/librenms/scripts/new-os.php on line 115

```

Facing the same issue.

**Comment by PipoCanaja** [comment]
You can actually edit yourself the yaml file in includes/definitions/discovery/geist-watchdog.yaml to add the sensors there. Usually simpler...

**Comment by Munzy** [comment]
The sensor that is missing is already in that YAML though.

https://github.com/librenms/librenms/blob/master/includes/definitions/discovery/geist-watchdog.yaml#L16

I'm wondering if this has something to do with it. They both have the same oid.

`.1.3.6.1.4.1.21239.5.1.4.1.5.1 = INTEGER: 632
.1.3.6.1.4.1.21239.5.1.4.1.5.1 = No more variables left in this MIB View (It is past the end of the MIB tree)`

**Comment by Munzy** [comment]
Here is the snmprec that was asked for.

https://p.libren.ms/view/26cb7d2a
[vertiv-watchdog.zip](https://github.com/librenms/librenms/files/3407527/vertiv-watchdog.zip)

**Comment by murrant** [comment]
The two mibs have the same oid names on it.  So, the mibs need to be specified in the sensor declarations.

**Comment by Munzy** [comment]
How do I go about doing that. I am not with Geist, but if I can get it to work I will.


Just need some examples.

**Comment by VanillaNinjaD** [comment]
I know this is probably such a simple issue, but I'm so over my head

After tinkering around with the following 2 files, adding the VERTIV MIB and explicitly defining the proper MIB to each OID I am starting to think the amateur hacks like myself are probably going to break older devices if we start getting too heavy in here.

includes/definitions/discovery/geist-watchdog.yaml
includes/discovery/sensors/temperature/geist-watchdog.inc.php

I can submit a PR to show what I've changed but the only thing I've managed to accomplish is polling the external temp probe properly while simultaneously losing the ability to poll the internal probe. Still not sure how I did that.

It appears that many OIDs are shared as @murrant mentions. Also, Geist/VERTIV have changed the OID names in the MIB files of many parameters as well and I'm not sure how to reference, for instance, "internalName" on the old OS and MIB vs "internalLabel" on the new OS version and MIB to get the proper sensor labels

I don't mind helping in any way that I can but I may be reaching the end of my helpfulness I fear

**Comment by murrant** [comment]
I mean one sensor should be:
`oid: GEIST-V4-MIB::tempSensorTable`

The other should be:
`oid: GEIST-MIB-V3::tempSensorTable`

**Comment by murrant** [comment]
The other option is to split it into two OS.

**Comment by VanillaNinjaD** [comment]
Thanks @murrant, I'll get working on it and see what I come up with

**Comment by Munzy** [comment]
Any updates on this?




> I mean one sensor should be:
> `oid: GEIST-V4-MIB::tempSensorTable`
> 
> The other should be:
> `oid: GEIST-MIB-V3::tempSensorTable`

In regards to this, do you mean we can preface the .yaml file with which file to look at?

**Comment by VanillaNinjaD** [comment]
The current GEIST implementation is so extensive and distributed throughout the file system I’m having a hard time wrapping my head around what it’s doing.

Even when I remove all GEIST support from the software and add in barebones support for just the Watchdog i’m only able to poll either the internal temp sensor or the external temp probe, bever both.

It only reads the sensor OID that is configured second in the .yaml file.

In other words, i’m lost

**Comment by PipoCanaja** [comment]
If you need some help on the files themselves, I suggest that you open a Pull Request with your current code, add "WIP" (work in progress), and we can continue the discussion there. Will be easier for us to see your tests, and help you getting it right. 

Bye

**Comment by murrant** [comment]
No, you can add both sensors to the discovery yaml file.  That is the point of discovery it checks to see what sensors exist.  It is ok that some sensors will always fail on some devices.

**Comment by CameronMunroe** [comment]
Any updates on this?

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11608

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/geist-watchdog-external-sensor-discovery-not-working/11608/1
