### ISSUE TITLE
Add Support For Fuji S100

### ISSUE THREAD

**Issue by Daemonslayer2048** [librenms/librenms#10456]
./discovery.php -h HOSTNAME -d | ./pbin.sh
https://p.libren.ms/view/ec7278b9

./poller.php -h HOSTNAME -r -f -d | ./pbin.sh
https://p.libren.ms/view/5ad409bb

snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh
https://p.libren.ms/view/85a5970a

To add to the above commands I was also able to obtain what I believe to be the full MIB structure. 
[S100_MIB.xlsx](https://github.com/librenms/librenms/files/3417894/S100_MIB.xlsx)

If I missed anything or anyone needs more information please let me know.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by PipoCanaja** [comment]
Hi @Daemonslayer2048 
Do you by chance have the MIB file itself (not an xlsx file) ? Only a properly formated MIB file can be used by the snmp poller. If you don't, then just let us know, and it can still be done using the numerical OID (but is far less readable as you can imagine). 
Thanx

**Comment by Daemonslayer2048** [comment]
Awesome thanks for the quick response, I was able to retrieve the MIB files. 

[S100_MIBs.zip](https://github.com/librenms/librenms/files/3419254/S100_MIBs.zip)

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11607

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/add-support-for-fuji-s100/11607/1
