### ISSUE TITLE
Multiple spelling mistakes in Applications.md

### ISSUE THREAD

**Issue by johnhumphrys** [librenms/librenms#10450]
Under SUDO subheading it reads:

One majoy thing to keep in mind when using SNMP extends is on my systems these run as a unprivlidged user. In these situations you need to use sudo.

Should read:
One major thing to keep in mind when using SNMP extends is on my
systems these run as an unprivileged user. In these situations you need
to use sudo.

**Comment by kkrumm1** [comment]
Please don’t open an issue. This is only for requesting new device support. If you would like to fix the spelling mistakes. Click on the edit button in the Docs page and submit your fixes and or changes.
Thank you
