### ISSUE TITLE
Cisco SG250X Support

### ISSUE THREAD

**Issue by maniacek** [librenms/librenms#10468]
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

discovery https://p.libren.ms/view/abef172d
poller https://p.libren.ms/view/ad5c8c86
snmpbulkwalk https://p.libren.ms/view/47c37f70

**Comment by PipoCanaja** [comment]
Hi @maniacek 
Pull request to add the support is already on its way. Could you please test it by doing : 
``` ./scripts/github-apply 10472 ```
in your /opt/librenms directory ? 

You can then manually run discovery and poller to see the changes. Let us know if it goes well.

**Comment by maniacek** [comment]
Nothings has changed:

```
root@stat1:~# su - librenms
$ cd /opt
$ cd librenms
$ ./scripts/github-apply 10472
Checking patch includes/definitions/ciscosb.yaml...
Applied patch includes/definitions/ciscosb.yaml cleanly.
$ ./discovery.php -h 2
LibreNMS Discovery
as1-switch 2 generic

#### Load disco module core ####

>> Runtime for discovery module 'core': 0.0070 seconds with 1104 bytes
>> SNMP: [10/0.07s] MySQL: [4/0.00s] RRD: [0/0.00s]
#### Unload disco module core ####


#### Load disco module os ####
OS: Generic Device (generic)
---
$ ./poller.php -h 2
 Poller
Starting polling run:

Hostname:    as1-switch
Device ID:   2
OS:          generic



#### Load poller module core ####
Uptime:  113 days 22 hours 6 minutes 3 seconds

```

**Comment by PipoCanaja** [comment]
You need to 
``` rm cache/os_defs.cache ```
before

**Comment by PipoCanaja** [comment]
Tested it on my side. Works OK with the standard features of the others Cisco SB.

**Comment by maniacek** [comment]
Now is ok, thanks for advice.

**Comment by PipoCanaja** [comment]
You will need to remove the patch you just tested in order to upgrade LibreNMS now. You can either do it right now or wait until upgrade fails. 
```
git checkout includes/definitions/ciscosb.yaml 
```

**Comment by PipoCanaja** [comment]
(doing it now will break again the SG250X support until patch is merged into LibreNMS)
