### ISSUE TITLE
Support for TRANGO Microwave Radios

### ISSUE THREAD

**Issue by digitalpilotnm** [librenms/librenms#1046]
Hi,  We are looking for support for Trango Systems, GigaPlus, Orion etc radios.
We  can provide snmp walks and access for testing.

Thank you

**Comment by Lonecrowe** [comment]
I may have a couple devices that can be used for testing.. I can set up port forwards to them.  Will try and set up  later this week.

**Comment by digitalpilotnm** [comment]
http://pastebin.com/embed_iframe.php?i=YZBSC06M

http://pastebin.com/embed_iframe.php?i=Xga7TpQv

**Comment by laf** [comment]
Can you let us know what data you want to see from this?

Also what device is that walk from?

**Comment by digitalpilotnm** [comment]
Hi,
http://support.trangosys.com/categories/20133906   Giga Orion

-Link Lock Status
-Packet Drops
-RSSI (both local and remote side, floating point)
-MSE (both local and remote side, modem and radio, floating point)
-ODU temperature
-IDU temperature
-RF Port Rate in Mbps
-RF Port Utilization in % 
-RF Speed 
-RF Packets and Octets in/out
-Ping
-Uptime

Thanks

**Comment by Lonecrowe** [comment]
Can you put the oid next to each of those data points?  It'll help him speed up the process.

**Comment by digitalpilotnm** [comment]
Will do.  Sorry

**Comment by paulgear** [comment]
Now that is one dumb MIB.  Why would they completely duplicate stuff from IF-MIB in their own enterprise?

**Comment by Lonecrowe** [comment]
Trango was ahead of the game at one point but their SNMP stuff was always completely dumb from day one.   At one point if you wanted to query a subscriber unit you had to query the AP for that customers radio info.

**Comment by digitalpilotnm** [comment]
Thankfully Trango got OUT of the PtMP business and primarily does licensed
PtP stuff only.

**Comment by Rosiak** [comment]
Please supply some walks with no expiry date.

**Comment by digitalpilotnm** [comment]
what do you mean "with no expiry date" ?

**Comment by SaaldjorMike** [comment]
@digitalpilotnm When clicking on the pastebin links you posted, we meet a message that the link has expired, so we can't see the data anymore.

**Comment by digitalpilotnm** [comment]
Yes, I don't like having things on pastebin for ever and for others to mine.
So I limit the time frame.

**Comment by Rosiak** [comment]
@digitalpilotnm 
Can you mail us the data then?
We need data to move on with this.

**Comment by digitalpilotnm** [comment]
where would you like me to mail it to ?

**Comment by laf** [comment]
team@librenms.org will be fine.

**Comment by Lonecrowe** [comment]
Sorry dropped the ball on this one.. you still need any walks?  We only have 1 device left.  Trango is dying a slow death it seems.

**Comment by digitalpilotnm** [comment]
http://support.trangosys.com/attachments/token/0z6i3eorlctajt5/?name=TRANGO-PTP-MIB.txt
http://support.trangosys.com/attachments/token/rkitr3wigpy2h9u/?name=GigaPlus_v3.0_oids.csv
http://support.trangosys.com/attachments/token/zc11jvsvjtihegl/?name=GigaPlus_v3.0_oids.xls

At present it seems the standard ifOutOctets ifInOctets is not tracking
real usage.

The above are links to the companies MIB files.
the attached are two snmp walks I did of a live unit.

rf RSSI for both local and remote are useful
MSE is also useful
RF / Packet errors is useful

Things like temp's are also useful.

WE have active unit we can test against.

Thanks

**Comment by laf** [comment]
Please provide the output of `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .`

**Comment by laf** [comment]
Feel free to comment back with the info when it's available.
