### ISSUE TITLE
Add support for defining SNMP community string per Device Group

### ISSUE THREAD

**Issue by killsudo** [librenms/librenms#1047]
In larger environments you need the ability to maintain multiple default snmp community strings based upon which device group a device resides in.

Sometimes you have multiple separate networks with 20+ devices and each network uses a unique snmp community string.

This open's up two use cases.
1. LibreNMS users could create a new device group, set the snmp community string on the group, add the regex's for matching hostnames into the group. The user adds the new subnet to auto-discovery and all of your devices are auto-added based upon the unique group snmp community.
2. LibreNMS users may need to roll their snmp community at least once a year across devices for security. Manually updating each device community string in LibreNMS isn't easy or fast. Being able to update the snmp community once for an entire group is much simpler.

In the future the API could be extended to allow admins the ability to script snmp community string changes across multiple librenms device groups easily.

In our environment we routinely roll the snmp community and leverage rancid to push the config change to groups of devices. Zenoss then allows us to define an snmp community string per device or per group both in the webui or via api making updates quick and painless.

In a single day we can update our snmp community strings across all of our devices and in our NMS with minimal trouble helping to maintain better security practices.

"[15:13] <lafwood> We support device groups so we could probably easily provide a form to update all snmp details for those devices belonging to X group"

**Comment by f0o** [comment]
ok so this Feature Request is actually 2:

1) Allow overriding config's SNMP credentials on a per-Group basis.
2) Allow bulk-updating DB's SNMP credentials on a per Group basis.

as for 1st, that's fairly easy to do. 2nd requires a bit more work though.

If you run into the need of 1st asap, you can define multiple default credentials in the config afaik, so autodiscovery would pick up the rest of your gear.

I wouldnt want to patch in some code that allows 1st & 2nd as of now. We're having a Dynamic-Config patch inbound that moves parts of the config away from the file and into the DB, that would make this request much easier and nicer to fulfil.

Tagging @laf in regards to the dynconfig-patch

**Comment by killsudo** [comment]
Yup sounds like you have it. Nothing ASAP but I can see this being useful for users as they really start scaling out LibreNMS or want to use it in more tightly controlled environments.

The 1. is going to be important for people trying to monitor different/unique networks for say multiple customers.

2. is just nice to have in the future if you do need to perform a mass snmp community change.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
