### ISSUE TITLE
Can't subscribe on community.librenms.org

### ISSUE THREAD

**Issue by mthld** [librenms/librenms#10484]
Hi,

I'm very sorry to post this issue here, I tried to contact you on Twitter but nobody answered.
Your subscription/login setup on the Discourse forum is broken, we get lost in infinite redirections.

See the following screen recording:
![output](https://user-images.githubusercontent.com/41020854/62310588-1f973300-b48a-11e9-986e-b7767634e0da.gif)

Can you forward this to someone competent with this issue?

Thanks,

**Comment by murrant** [comment]
Seems like it is a Safari bug...  Did you try to log in after that?  Try a different browser.

**Comment by mthld** [comment]
Hi @murrant 

> Seems like it is a Safari bug...

Looks like a CSRF feature which is not allowed in Safari.

> Did you try to log in after that?

Yeah, no luck

> Try a different browser.

It works under Firefox

Anyway, thank you for your help!
