### ISSUE TITLE
Commscope/Adtran/Ubiquoss C9500 OLT

### ISSUE THREAD

**Issue by jdtinsley88** [librenms/librenms#10480]
I have a Commscope C9500 Fiber OLT originally made by Ubiquoss.  Ubiquoss was bought out by Adtran.

I have the MIBs and will upload them with this request.  I would like someone to develop a template for this.

[Ubiquoss-mibs.zip](https://github.com/librenms/librenms/files/3453846/Ubiquoss-mibs.zip)

**Comment by kkrumm1** [comment]
Please provide all the info requested.

**Comment by jdtinsley88** [comment]
Kevin,

 

I noticed that the output of ./discovery.php -h HOSTNAME -d | ./pbin.sh shows IP Addresses and some VLANs that I cannot expose to the Public and nobody’s business to know.

 

May I redirect the ./discovery.php output to a text file, remove IP Addresses and VLANS, and then upload the text file?

 

Thanks
