### ISSUE TITLE
Extend the BGP session information via IRR info

### ISSUE THREAD

**Issue by killsudo** [librenms/librenms#1048]
LibreNMS could leverage the Internet Routing Registries such as RadB for identifying the company behind an AS number, their telephone number, e-mail addresses etc.

This could allow LibreNMS to point Admins in the proper direction if they are having issues with a BGP peer.

$ whois -h whois.radb.net AS3356 | grep abuse
remarks:        Abuse reports to abuse@Level3.net
remarks:       Abuse reports to abuse@Level3.net

$ whois -h whois.radb.net AS3356 | grep issues
remarks:        Operational issues to noc@Level3.net
remarks:       Operational issues to noc@Level3.net

$ whois -h whois.radb.net AS3356 | grep name
as-name:        Level3
as-name:       Level3

Another option would be to simply have LibreNMS perform the whois lookup on the entire AS number and display the output in a pop-up window or 'whois info' page link you can click on from the BGP session page.

**Comment by f0o** [comment]
Although we support whois-lookups via the netcmd.php I would prefer having a prefetch cache solution to avoid direct web-accessed shell_exec and also potentially malicious request-floods.

**Comment by killsudo** [comment]
Looks like Perl provides NET:IRR for parsing IRR info,

http://search.cpan.org/~tcaine/Net-IRR/lib/Net/IRR.pm

$whois->match('aut-num', 'AS5650'); - get RPSL objects registered in the database
The example above will retrieve the aut-num object with the key AS5650. This method will return the first RPSL object matching the object type and name specified as parameters to $whois->match(). undef is returned upon failure.

**Comment by Rosiak** [comment]
This could perhaps be tied with #2051

**Comment by laf** [comment]
Think this still has a few more points that need working on (aside from branching out from just RIPE)

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
