### ISSUE TITLE
Riello OS - Object ID

### ISSUE THREAD

**Issue by robertobru** [librenms/librenms#10508]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ X] Please provide as much detail as possible.
- [ X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Dear LibreNMS community,
I'm running the daily update version, my Riello UPSes are identifyed as "generic devices". I noticed that in the Riello OS in the master branch includes only one Object ID, different from mine (my one is .1.3.6.1.4.1.5491.0). I tried to add it manually, and everything seems working correctly. Can you add this object id to the Riello OS also in the master branch?

**Comment by kkrumm1** [comment]
Please provide all info asked for.

**Comment by robertobru** [comment]
Sorry, herein you can find all the requested info:
discovery: [https://p.libren.ms/view/e60a862b](https://p.libren.ms/view/e60a862b)
poller: [https://p.libren.ms/view/eacc92da](https://p.libren.ms/view/eacc92da)
snmpwalk: [https://p.libren.ms/view/aba0c7fb](https://p.libren.ms/view/aba0c7fb)
