### ISSUE TITLE
Add better support for Ciena 39xx and 51xx Switches

### ISSUE THREAD

**Issue by AB-Tony** [librenms/librenms#10517]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

We have a few different switches we want to monitor.

Service Delivery:
3903
3930

Service Aggregation:
5142
5160

Information requested was pulled from a 5142 Running SAOS: saos-06-18-00-0200 

Discovery: https://p.libren.ms/view/7186f96b
Poller: https://p.libren.ms/view/b3812d23
[snmpwalk.txt](https://github.com/librenms/librenms/files/3493101/snmpwalk.txt)
If you need SNMP access to one of these, I can setup one up outside of production.

**Comment by PipoCanaja** [comment]
I am afraid we need an IP address instead of x.x.x.x. It breaks snmp type check to return a letter instead of a number.

**Comment by AB-Tony** [comment]
Here you go.

[snmpwalk.txt](https://github.com/librenms/librenms/files/3493101/snmpwalk.txt)

**Comment by PipoCanaja** [comment]
All good.

**Comment by PipoCanaja** [comment]
Hi @AB-Tony 
The SNMP File is still not good. A few lines include a "return" in the middle, making it impossible to load them. 

Could you re-run this ? 

Thanx
