### ISSUE TITLE
Add better support for Cisco Catalyst 9200

### ISSUE THREAD

**Issue by hunnymonster** [librenms/librenms#10514]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Attaching files here since p.libren.ms barfs with Database error 1153 on the SNMP & Poller files.

[c9200-discover.txt](https://github.com/librenms/librenms/files/3491458/c9200-discover.txt)
[c9200-poller.txt](https://github.com/librenms/librenms/files/3491459/c9200-poller.txt)
[c9200-snmp.txt](https://github.com/librenms/librenms/files/3491460/c9200-snmp.txt)

Most functions work as-is - however the OS type & version isn't detected correctly and nor is the system type when the switches are stacked (it detects a stack as "STACK-T4-50CM" (that's the stacking cable)

**Comment by johnpalumbo** [comment]
I am also experiencing this issue.

**Comment by PipoCanaja** [comment]
SNMP data is not usable. Please reopen the issue if it is still necessary, and provide a proper SNMP file so we can replicate this. 
Thanx

**Comment by hunnymonster** [comment]
Ok then - please tell me exactly what you want because as far as I can see I followed the documentation.

**Comment by PipoCanaja** [comment]
Hi @hunnymonster 
Some ASR9k code was merged a few days ago. So if this issue is still necessary, we'll have to go deeper.
So first, let me know if you see an improvement after "./daily.php".

Then, if still not good, you'll have to follow the documentation (again) but ensure that no "carriage returns" are added in the middle of the text. That made the previous data unusable, even if it looked ok at first check. 

Thanx

**Comment by hunnymonster** [comment]
OK - but ASR9k != Catalyst 9k... It certainly hadn't made a difference on Friday afternoon when I last looked. Will force an update & rediscover now to check.

**Comment by hunnymonster** [comment]
Current codebase is bf181b9dc (1.57-70) and still have 9300 stacks detected as STACK-T1-50CM and 9200 stacks as STACK-T4-50CM.

**Comment by PipoCanaja** [comment]
Ok. Then let's try to do a proper snmpwalk, without any carriages returns in the middle :) 

And concerning issues, please remember that there is absolutely no commitement that somebody will ever proceed anything in the issues. This project is community based. So it may stay forever in the issues until somebody has the proper motivation to code it into LibreNMS :)

**Comment by hunnymonster** [comment]
OK - here's the output from `./discovery.php -v -d -h <host> | tee output.file` for both a single chassis and a 2-stack of Catalyst 9300
[c9300-1.txt](https://github.com/librenms/librenms/files/3857540/c9300-1.txt)
[c9300-2.txt](https://github.com/librenms/librenms/files/3857541/c9300-2.txt)

**Comment by hunnymonster** [comment]
Here's the output from the SNMP discover tab in LibreNMS for the 2-stack
[c9300-2-snmp-from-librenms.txt](https://github.com/librenms/librenms/files/3857570/c9300-2-snmp-from-librenms.txt) - I hesitate to include both :)

**Comment by hunnymonster** [comment]
If these are useful - I'll do the same for the 9200.

**Comment by hunnymonster** [comment]
And for clarity - I have the motivation - what I don't have is the skill/knowledge - for that I need assistance... thelast thing I programmed (beyond some perl/sed/awk scripts and Excel macros) was in PASCAL in ~1990...

**Comment by PipoCanaja** [comment]
> Here's the output from the SNMP discover tab in LibreNMS for the 2-stack
> [c9300-2-snmp-from-librenms.txt](https://github.com/librenms/librenms/files/3857570/c9300-2-snmp-from-librenms.txt) - I hesitate to include both :)

Still not good : 
``` 
.1.3.6.1.2.1.2.2.1.15.91 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.92 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.93 = Counte
r32: 0
.1.3.6.1.2.1.2.2.1.15.94 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.95 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.96 = Counter32: 0
```

There are a couple of "carriage returns" in this file. I don't know what could cause this, but it makes the files unusable. What do you exactly do to create those files ?

**Comment by hunnymonster** [comment]
Device in Librenms... Settings > Capture > Discover (or Poller or SNMP)

Whatever command/options Librenms runs - I don't seem to be able to readily replicate it on the command line :(

**Comment by hunnymonster** [comment]
[c9300.txt](https://github.com/librenms/librenms/files/3874163/c9300.txt)
Here's the output of the command `snmpwalk -v 2c -c public 10.246.2.124 2>&1 | tee c9300.txt`

Looks to be CR free... nowhere near as comprehensive as the output from the verbose discovery... maybe sufficient though?

**Comment by PipoCanaja** [comment]
The command must be exactly as asked in the doc : https://docs.librenms.org/Support/FAQ/#faq20
```snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh```

if the result is too big for pbin.sh, you can attach the file to the issue instead.  
```snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME . > c9300.txt```

**Comment by hunnymonster** [comment]
[c9300.txt](https://github.com/librenms/librenms/files/3874365/c9300.txt)
There's the output from a stack of 2no c9300 switches of `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME`

**Comment by hunnymonster** [comment]
[c9300-1.txt](https://github.com/librenms/librenms/files/3874397/c9300-1.txt)
There's the output from a single c9300 switch of `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME`

**Comment by PipoCanaja** [comment]
@hunnymonster  the files in the last 2 posts look good. I'll test them in the simulator and confirm this.

**Comment by hunnymonster** [comment]
Hopefully that will solve the 9200/9400/9500 too - if not I can certainly do the same for the 9200.

**Comment by PipoCanaja** [comment]
1st patch for HW identification here : 
https://github.com/librenms/librenms/pull/10862

Works fine with the c9300.txt

**Comment by hunnymonster** [comment]
Yahoo! On a sample of 1no 9200 stack & 1no 9300 stack that appears to have detected the stacked devices and the software versions...

**Comment by hunnymonster** [comment]
Seems on the face of it to have resolved it for all (so far). I guess someone with a 9400 or 9500 needs to test too?

**Comment by hunnymonster** [comment]
Only comment (from my colleague) is that it detects a Catalyst 3650 and a Catalyst 3850 as IOS-XE (correct) but the C9200/9300 are detected as IOS... consistency would be good.

**Comment by PipoCanaja** [comment]
Right, your colleague is right :) Moving to IOS-XE right now. Basically, Cisco wrote IOSXE and not IOS-XE which broke the discovery :) Consistancy you said ? :)

> Only comment (from my colleague) is that it detects a Catalyst 3650 and a Catalyst 3850 as IOS-XE (correct) but the C9200/9300 are detected as IOS... consistency would be good.

**Comment by hunnymonster** [comment]
Yeah, I know - Cisco != consistent... some switches are "stack-able" vs "stackable" but since we aren't Cisco, a man can dream

**Comment by PipoCanaja** [comment]
All right, sounds like ready for review, unless you see something else that would be missing for this device.

**Comment by hunnymonster** [comment]
Observation - a Cisco 6509 VSS pair is now detected as one of the cards within... specifically a WS-X6748-GE-TX

No problem for me - I'm within a month of eliminating it forever.

**Comment by PipoCanaja** [comment]
Please attach an snmpwalk ' -OUneb ' of this, I'll try to find if it is possible to have both without mistakes :)

**Comment by hunnymonster** [comment]
Will do - it's a live device so I may have to sanitise the output (unless I can share it confidentially?)

**Comment by PipoCanaja** [comment]
If you connect in discord or in the community forum, you can send me the file privately. Or you can sanitise it and post it here.

**Comment by hunnymonster** [comment]
Here's the export from the 6509e - it did have some control characters in (direct from the export) - I _think_ I've removed all of those. 
[6509e.txt](https://github.com/librenms/librenms/files/3891244/6509e.txt)
