### ISSUE TITLE
Add support for Tripplite PDU PDUMV20NETLX

### ISSUE THREAD

**Issue by vb543** [librenms/librenms#10531]
Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery: https://p.libren.ms/view/f3f3907c
Poller: https://p.libren.ms/view/c77ca526
SNMP Walk: https://p.libren.ms/view/66a1b8d0

I've added the device successfully via SNMP and can see network traffic, but no metrics for power are available. I do see Tripplite provides an MIB on their website. Anyone able to please help me add better support for this device? Thanks!

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/add-support-for-tripplite-pdu-pdumv20netlx/11606/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11606
