### ISSUE TITLE
Add Support For N-Tron 714FX6 industrial switch

### ISSUE THREAD

**Issue by pedjaj** [librenms/librenms#10547]
./discovery.php -h HOSTNAME -d | ./pbin.sh
https://p.libren.ms/view/30277b17

./poller.php -h HOSTNAME -r -f -d | ./pbin.sh
https://p.libren.ms/view/d3a5dab0

snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME . | ./pbin.sh
https://p.libren.ms/view/5339af8e

MIB file
[714fx6_mibs.zip](https://github.com/librenms/librenms/files/3529226/714fx6_mibs.zip)

If I missed anything or anyone needs more information please let me know.

**Comment by PipoCanaja** [comment]
Hi @pedjaj 
The data looks good here. I can encourage you to have a look and add this support yourself if you have time. We can help you, either here in github when you open a pull request, or in discord. This is by far the fastest way, cause we lack contributors to empty this list of device support requests. 
Bye

**Comment by pedjaj** [comment]
Hi @PipoCanaja 
where to start ?

**Comment by PipoCanaja** [comment]
Basically, for the initial discovery, you need to : 
- Choose an OS name : I would go with 'ntron' here.
- Add an svg or png logo to ``` html/images/os/redlion.svg ``` or ``` html/images/os/redlion.png ``` 
- Add the mib file (NTRON716-MIB) to the ``` include/mibs/redlion ``` directory
- Create a discovery file named ``` includes/definitions/ntron.yaml ``` for this device, that would more or less look like this : 
```
os: ntron
text: 'Redlion N-Tron'
type: network
icon: redlion
mib_dir:
    - redlion
over:
    - { graph: device_bits, text: 'Device Traffic' }
    - { graph: device_processor, text: 'CPU Usage' }
    - { graph: device_mempool, text: 'Memory Usage' }
discovery:
    - sysObjectID:
        - .1.3.6.1.4.1.28381.
```
- remove the cache
``` rm cache/os_defs.cache  ```
- force a new discovery of your device
``` ./discovery.php -h <deviceId> ```

Your device should appear with the correct icon.

After this 1st step, the discovery can be extended with sensors etc etc,

**Comment by PipoCanaja** [comment]
You can find more details here : 
https://github.com/librenms/librenms/edit/master/doc/Developing/os/Initial-Detection.md

**Comment by pedjaj** [comment]
Finally get some time.
includes/definitions/ntron.yaml
`os: ntron
text: 'Redlion N-Tron'
type: network
icon: redlion
mib_dir:
    - redlion
over:
    - { graph: device_bits, text: 'Device Traffic' }
discovery:
    - sysObjectID:
        - .1.3.6.1.4.1.28381.
bad_ifname_regexp: 
    - "/^cpu/"`

html/images/os/redlion.png
![redlion](https://user-images.githubusercontent.com/27769532/65307962-4ec44980-db89-11e9-8a83-70defa4d858d.png)
include/mibs/redlion
[ntron714fx6.zip](https://github.com/librenms/librenms/files/3634682/ntron714fx6.zip)

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11605

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/add-support-for-n-tron-714fx6-industrial-switch/11605/1
