### ISSUE TITLE
Riello NetMan - Object ID not recognized 

### ISSUE THREAD

**Issue by robertobru** [librenms/librenms#10576]
**PLEASE READ FIRST**

**Please do not post bugs or ask questions or feature requests here**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org/c/help).**

To create a new device request please use this link: https://github.com/librenms/librenms/issues/new?template=New-Device.md

Dear LibreNMS community,
sorry for re-opening this issue.
I'm running the daily update version, my Riello UPSes are identifyed as "generic devices". I noticed that in the Riello OS in the master branch includes only one Object ID, different from mine (my one is .1.3.6.1.4.1.5491.0). I tried to add it manually, and everything seems working correctly. Can you add this object id to the Riello OS also in the master branch?

Herein you can find all the requested info:
discovery: https://p.libren.ms/view/e60a862b
poller: https://p.libren.ms/view/eacc92da
snmpwalk: https://p.libren.ms/view/aba0c7fb

**Comment by PipoCanaja** [comment]
Hi @robertobru 
If you already did the change and tried it, the easier and faster would be that you submit a Pull Request directly, so we can discuss it and merge it into LibreNMS. 
Thanx

**Comment by sippe2** [comment]
Hello,

I suppose the correct oid is **1.3.6.1.4.1.5491** with Netman204 device.


**Device with 16 series firmware:**
librenms@librenms:/opt/librenms$ snmpwalk -v2c -csecretshere xxx.xxx.xxx.xxx iso.3.6.1.4.1.5491
iso.3.6.1.4.1.5491.5.1.1.1.0 = STRING: "nlandpA"
iso.3.6.1.4.1.5491.5.1.1.2.0 = STRING: "EMSTM13ANB00    "
iso.3.6.1.4.1.5491.5.1.1.3.0 = STRING: "SWM022-03-33"
iso.3.6.1.4.1.5491.5.1.1.4.0 = INTEGER: 8
iso.3.6.1.4.1.5491.5.1.1.5.0 = INTEGER: 1
iso.3.6.1.4.1.5491.5.1.1.6.0 = INTEGER: 0
iso.3.6.1.4.1.5491.5.1.1.7.0 = INTEGER: 0
iso.3.6.1.4.1.5491.5.1.1.8.0 = STRING: "Netman204"
iso.3.6.1.4.1.5491.5.1.2.1.0 = INTEGER: 1
iso.3.6.1.4.1.5491.5.1.2.2.0 = INTEGER: 1
iso.3.6.1.4.1.5491.5.1.2.3.0 = INTEGER: 1
iso.3.6.1.4.1.5491.5.1.2.4.0 = STRING: "AppVer. 02.05.000"
...

**Device with 18 series firmware:**
librenms@librenms:/opt/librenms$ snmpwalk -v2c -ctopsecretshere xxx.xxx.xxx.xxx iso.3.6.1.4.1.5491
iso.3.6.1.4.1.5491.5.1.1.1.0 = STRING: "nlandpA"
iso.3.6.1.4.1.5491.5.1.1.2.0 = STRING: "SDH 3000"
iso.3.6.1.4.1.5491.5.1.1.3.0 = STRING: "SWM035-01-14"
iso.3.6.1.4.1.5491.5.1.1.4.0 = INTEGER: 1
iso.3.6.1.4.1.5491.5.1.1.5.0 = INTEGER: 8
iso.3.6.1.4.1.5491.5.1.1.6.0 = INTEGER: 0
iso.3.6.1.4.1.5491.5.1.1.7.0 = INTEGER: 0
iso.3.6.1.4.1.5491.5.1.1.8.0 = STRING: "Netman204"
iso.3.6.1.4.1.5491.5.1.2.1.0 = INTEGER: 1
iso.3.6.1.4.1.5491.5.1.2.2.0 = INTEGER: 1
iso.3.6.1.4.1.5491.5.1.2.3.0 = INTEGER: 1
iso.3.6.1.4.1.5491.5.1.2.4.0 = STRING: "AppVer. 02.17.000"
...

**Comment by robertobru** [comment]
yes, it is also for 17 series firmware:

snmpwalk -v2c  -ctopsecretshere xxx.xxx.xxx.xxx iso.3.6.1.4.1.5491
SNMPv2-SMI::enterprises.5491.5.1.1.1.0 = STRING: "RPS SpA"
SNMPv2-SMI::enterprises.5491.5.1.1.2.0 = STRING: "CSDU6K0AA700RUA"
SNMPv2-SMI::enterprises.5491.5.1.1.3.0 = STRING: "SWM070-01-03"
SNMPv2-SMI::enterprises.5491.5.1.1.4.0 = INTEGER: 1
SNMPv2-SMI::enterprises.5491.5.1.1.5.0 = INTEGER: 8
SNMPv2-SMI::enterprises.5491.5.1.1.6.0 = INTEGER: 0
SNMPv2-SMI::enterprises.5491.5.1.1.7.0 = INTEGER: 0
SNMPv2-SMI::enterprises.5491.5.1.1.8.0 = STRING: "Netman204"
SNMPv2-SMI::enterprises.5491.5.1.2.1.0 = INTEGER: 1
SNMPv2-SMI::enterprises.5491.5.1.2.2.0 = INTEGER: 1
SNMPv2-SMI::enterprises.5491.5.1.2.3.0 = INTEGER: 1
SNMPv2-SMI::enterprises.5491.5.1.2.4.0 = STRING: "AppVer. 02.17.000"
....
