### ISSUE TITLE
Polling PoE device causes way to many calls to snmpbulkwalk

### ISSUE THREAD

**Issue by SaaldjorMike** [librenms/librenms#1057]
Enabled $config['enable_ports_poe'], and got the following debug output from poller:
http://paste.ubuntu.com/11209298/

**Comment by f0o** [comment]
wow, big list

**Comment by SaaldjorMike** [comment]
Yeah. LibreNMS tells me that the device has 38 ports (physical and virtual combined) and looks like these two walks are called for each port:
```/usr/bin/snmpbulkwalk -v3 -n "" -l authPriv -a MD5 -A "" -u cacti -x DES -X "" -OQUs  -m POWER-ETHERNET-MIB -M /opt/librenms/mibs -t 5 -r 5 udp:host:161 pethPsePortEntry```

```/usr/bin/snmpbulkwalk -v3 -n "" -l authPriv -a MD5 -A "" -u cacti -x DES -X "" -OQUs  -m CISCO-POWER-ETHERNET-EXT-MIB -M /opt/librenms/mibs -t 5 -r 5 udp:host:161 cpeExtPsePortEntry```

Grepping for snmpbulkwalk gives:
http://paste.ubuntu.com/11212028/

**Comment by SaaldjorMike** [comment]
My Cisco SB switch went from the typical 1-2% CPU usage to ~20% when enabling the PoE polling. I was hoping to add support for fetch PoE info from the Cisco SB devices, but I guess I'll wait a bit until this issue is resolved.

**Comment by f0o** [comment]
I'm afraid I'm no use here, maybe @laf who's closer to cisco-gear can have a look?

**Comment by laf** [comment]
Hey @SaaldjorMike.

This might have been an easy fix but I don't have anything poe to test so would you mind?

You need to be running a clean branch (git status) which should return:
```bash
On branch master
nothing to commit, working directory clean
```

If so then do the following:

```bash
git remove add laf https://github.com/laf/librenms.git
git remote update laf
git checkout issue-1057
git pull
./poller.php -h HOSTNAME -d -m ports
```

Once done and you don't see any errors then see how it is after 15 minutes or so as you should see graphs by then.

You can switch back to master at any stage by doing:

```bash
git checkout master
```

**Comment by SaaldjorMike** [comment]
@laf: I've now got the following:
http://paste.ubuntu.com/11282044/

Grepping for snmpbulkwalk in the output of the poller shows that it is only called once, which is great. I don't see any PoE section anywhere in the WebUI. Where is it supposed to be? I know that the values for how much power is actually drawn is not shown in the current polling, because it is included in a separate MIB for the Cisco SB devices (CISCOSB-POE-MIB).

Running a snmpbulkwalk on CISCOSB-POE-MIB::rlPoe with switchport 23 having a Cisco Access Point connected:
http://paste.ubuntu.com/11282099/

**Comment by laf** [comment]
Another test @SaaldjorMike if you don't mind:

```bash
git remote update laf
git checkout issue-1057
git pull
./poller.php -h HOSTNAME -d -m ports
```

**Comment by SaaldjorMike** [comment]
@laf: http://paste.ubuntu.com/11284390/

**Comment by laf** [comment]
Hi @SaaldjorMike 

Trying to catch up on some old PRs and just got back to this one. That output doesn't contain all the info by the looks of it (No DB calls). I'll redo that branch now to fit in with current master.

**Comment by SaaldjorMike** [comment]
Awesome. Let me know if you need anything from me :) Would probably be preferable to have some generic code where one could "just" refer to which part of the mib's contain the values needed for specific devices/types.

**Comment by laf** [comment]
PR done to fix this.
