### ISSUE TITLE
LLDP remote port resolution is not working when the remote device is a Mikrotik bridge

### ISSUE THREAD

**Issue by kedare** [librenms/librenms#10592]
Using LLDP, when the remote port is on a Mikrotik device and part of a bridge, the remote Mikrotik advertise the port as `bridgename/portname` like in this example:

```
------------------------------------------------
Chassis id: 4c5e.0c7e.6c5b
Port id: bridge/ether1
Port Description - not advertised
System Name: FRNTE1WAP1.xxx.net

System Description:
MikroTik RouterOS 6.46beta38 (testing) RBmAP2n

Time remaining: 111 seconds
System Capabilities: B,W,R
Enabled Capabilities: B,W,R
Management Addresses:
    IP: 192.168.1.103
    IPV6: FE80::4E5E:CFF:XXXX:XXXX
Auto Negotiation - not supported
Physical media capabilities - not advertised
Media Attachment Unit type - not advertised
Vlan ID: - not advertised
```

In this case, the `find_port_id` in the discovery-protocols will not be able to resolve the interface correctly.

I would suggest that when the remove device is a Mikrotik, and the `$lldp['lldpRemPortId']` contains a `/`, only keep the last part (that would contain for example `ether1` in this case, and fix the issue).

Thanks

**Comment by kkrumm1** [comment]
This is not the place to post fixes or report bugs please the forums for that thanks.
