### ISSUE TITLE
Edgeswitch ES-24-LITE

### ISSUE THREAD

**Issue by Cormoran96** [librenms/librenms#10603]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
- [X] Please provide as much detail as possible.

Please keep in mind that LibreNMS is a community project, it is run by people like you using their free time. 
Which means it may take time before support is added to LibreNMS. 

We encourage you to do it yourself and submit it in GitHub as a Pull request. It is not so difficult, most of
it can be done without writing a single line of code. You can find the documentation below :
👉  https://docs.librenms.org/Developing/os/Initial-Detection/

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

./discovery.php -h HOSTNAME -d 
https://gist.github.com/88f73fe95879a53d2de77f3ede8a6c8b

./poller.php -h HOSTNAME -r -f -d 
https://gist.github.com/943b075a72432df07c16c4e3ed9dfc0e

snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  
https://gist.github.com/4a92143a727daf1ba9987fe31e3c296f

I probabli found MIB here: 
https://www.ui.com/download/edgemax/edgeswitch-lite/es-24-lite/edgeswitch-firmware-v182

or directly here:
https://www.ui.com/downloads/firmwares/edgemax/EdgeSwitch/v1.8.2/ES-eswh.v1.8.2.5192445-mibs.tar.gz

But I don't know how to integrate to librenms

**Comment by crcro** [comment]
it’s already supported. just configure snmp on your device and add it to librenms

**Comment by Cormoran96** [comment]
Nope the ES-**24-LITE** 
![image](https://user-images.githubusercontent.com/9927793/64927628-88095c00-d80d-11e9-9a2a-88fd0f6fc2c2.png)

**Comment by crcro** [comment]
![7FA78D43-2F7A-4985-80FE-F2CEC32996DA](https://user-images.githubusercontent.com/3048315/64928797-919ebe00-d825-11e9-9ac1-691dfc4d4584.jpeg)

es-24-lite running 1.8.2

**Comment by Cormoran96** [comment]
Ok I have the firmware 1.7.1
