### ISSUE TITLE
Missing icon for dBm

### ISSUE THREAD

**Issue by SaaldjorMike** [librenms/librenms#1060]
In the health section of the menubar, see: https://i.imgur.com/3aLl1Lx.png

**Comment by Lonecrowe** [comment]
I haven't seen that under health yet.  Which branch is that on?

**Comment by SaaldjorMike** [comment]
@Lonecrowe: Not quite sure what you're asking. The dBm section shows the transmit/receive power for optics that supports DDM/DOM.

**Comment by Lonecrowe** [comment]
dBM generally is used in Wireless technology for signal.  I didnt know it would be used for fiber as well.

**Comment by laf** [comment]
PR done, @SaaldjorMike using this if that's ok: http://fontawesome.io/icon/sun-o/

**Comment by SaaldjorMike** [comment]
Looks good to me. Go ahead @laf
