### ISSUE TITLE
Nutanix OS

### ISSUE THREAD

**Issue by jdtinsley88** [librenms/librenms#10602]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Details -

Add support for Nutanix software/hardware.

Attached is the commands and Nutanix MIB
[NEW-OS-SUPPORT-COMMANDS-NUTANIX.txt](https://github.com/librenms/librenms/files/3606618/NEW-OS-SUPPORT-COMMANDS-NUTANIX.txt)
[Nutanix-MIB.txt](https://github.com/librenms/librenms/files/3606619/Nutanix-MIB.txt)

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11604

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/nutanix-os/11604/1
