### ISSUE TITLE
HPE ILO5 1.45 wrong uptime

### ISSUE THREAD

**Issue by francio87** [librenms/librenms#10605]
Hello, librenms report the **wrong uptime** from **Integrated Lights-Out 5 1.45**

Shown in the dashboard:
```
snmpwalk -c public -v 2c 192.168.110.178 .1.3.6.1.2.1.1.3.0
iso.3.6.1.2.1.1.3.0 = Timeticks: (2235472806) 258 days, 17:38:48.06
```
The correct one should be this:
```
snmpwalk -c public -v 2c 192.168.110.178 .1.3.6.1.2.1.25.1.1
iso.3.6.1.2.1.25.1.1.0 = Timeticks: (53019035) 6 days, 3:16:30.35
```
![wrong_uptime_ilo](https://user-images.githubusercontent.com/42090061/64921008-181fb500-d7be-11e9-8a47-1fe85be691e0.png)

**Comment by SourceDoctor** [comment]
i had this with a netgear switch also.
Solution was adding this into config.php

`$config['os']['netgear']['bad_snmpEngineTime'] = true;`

**Comment by PipoCanaja** [comment]
@francio87 Could you check if your issue is solved as suggested ? 

For next time, please use our community site for questions. This github issues is for device support, and a template must be used to provide the data.
Thx
