### ISSUE TITLE
Support for Versa Devices

### ISSUE THREAD

**Issue by bohdy** [librenms/librenms#10613]
Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Info attached in files.
[versa-mib.txt](https://github.com/librenms/librenms/files/3625940/versa-mib.txt)
[versa-discovery.txt](https://github.com/librenms/librenms/files/3625941/versa-discovery.txt)
[versa-poller.txt](https://github.com/librenms/librenms/files/3625942/versa-poller.txt)

Details:
OS: Versa Appliance

Founded by network industry veterans, Versa Networks is an innovative vendor in the SD-WAN and SD-Security market. Versa solutions enable service providers and large enterprises to transform the WAN and branch networks to achieve unprecedented business advantages. Versa’s carrier-grade network function virtualization (NFV) software provides unmatched agility, cost savings and flexibility vs. traditional network hardware.

Lanner and Versa Networks have tested and validated an integrated solution that combines Lanner’s compact virtual CPE equipment and Versa Networks’ highly-flexible NFV-based SD-WAN and SD-Security software. The joint solution enables service providers to centrally and cost-effectively manage a truly NFV-based and software-defined WAN at their network customers’ sites, instead of the traditional investment in proprietary hardware and hands-on management. The integration of Versa’s NFV-based architecture and Lanner’s hardware vCPE platform delivers flexibility and cost advantages for creating agile and profitable managed services.

**Comment by crapzDK** [comment]
This i also really like to have added ;)

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11603

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/support-for-versa-devices/11603/1
