### ISSUE TITLE
Unified Poll Time Variable

### ISSUE THREAD

**Issue by guipoletto** [librenms/librenms#1061]
Currently there is no easy way to change the Poll times from the default 5minutes.

That is OK for most "integral" by nature variables, like TX/RX octets and disk usage, but very bad for instantaneous stuff, like ADSL SNR statistics, and Wreless statistics. 

My idea is to link the standard polling times that are currently hard-coded to variables in the config file, so that we can set lower (or higher) polling times if deemed necessary.

**Comment by f0o** [comment]
This is very hard to realize as it's tied to the RRD files.
RRD will discard any data that's not within the defined `STEP` at it's creation.

We can introduce a variable that can never be changed upon installation, i.e. before any RRDs has been created. But that's just as bad situation as it is now as you can never change it, not even by accident..

**Comment by laf** [comment]
@guipoletto If you want to go through the code base and set all of the variables up to deal with this then be our guest :)

It wouldn't be a good thing to have loads of config options for various different sections. Would be much better to have a single variable that people can change from 5m to 1m if they want. Not everyone struggles with 5m polling.

**Comment by paulgear** [comment]
In my opinion, we don't want to encourage people going through the code and looking for things to change from hard-coded to variable.  I think we should take a step back and have another think about how we want this to work long-term.

Variable poll times is probably now our most asked-for feature, and we need to think about how we can do it in a way that works sensibly and scales well.

**Comment by guipoletto** [comment]
Maybe a field during the "Add device" step could be set to 1minute, for
instance, ant the RRD file for that specific device would be created with 1
minute step.

The main Poller-thread that is trigged by cron would still poll each 5
minutes, but i understand that the empty spaces in the graphing files would
just be "jumped over" during the graphing process.

Now you have a file that has spaces where you can plug values each minute,
but you are just filling the 0+5t ones.


The next logical step would be to have a second polling thread specific to
that interval, and assign a specific list of devices to that polling thread
(and remove those from the main standard thread).


Maybe something like that could provide a migration path to the way things
currently work, without causing too much trouble.

(in this example, only new devices would be capable of being polled at
different than 5m times)

2015-05-21 20:19 GMT-03:00 Paul Gear <notifications@github.com>:

**Comment by f0o** [comment]
that does sound fairly reasonable but how would we handle future changes of the interval?
exporting the rrd-values into xml, dump the rrd, create the new rrd and re-feed it with the xml-exported data has a fairly high failure-potential from my POV

**Comment by laf** [comment]
No further feedback provided so closing.
