### ISSUE TITLE
Add support for per-OS SNMP max repeaters configuration file setting.

### ISSUE THREAD

**Issue by nwautomator** [librenms/librenms#10627]
**PLEASE READ FIRST**

**Please do not post bugs or ask questions or feature requests here**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org/c/help).**

To create a new device request please use this link: https://github.com/librenms/librenms/issues/new?template=New-Device.md

**Comment by kkrumm1** [comment]
You have a PR open no need to open this.
