### ISSUE TITLE
discovery broken, per irc chat thread with blahdeblah

### ISSUE THREAD

**Issue by digitalpilotnm** [librenms/librenms#1063]
running  ./discover.php -h <hostname> -d   
The router discovery will wedge on trying to discover a router that is a) not powered on, b) not connected to the host that discover is presently running on.

Attached are text version of the discovery output and a text of the tcpdump capture at the same time

tcpdump:  http://pastebin.com/embed_iframe.php?i=q4ih5apm

discover.php:  http://pastebin.com/embed_iframe.php?i=A6n26biQ

**Comment by laf** [comment]
PR #1088 fixes b).

a) Is a bit different as it's not to do with discovery technically. If the first device is still reporting the second device via snmp ospf mib then we will record that data and then try and discover on it. So not sure we can do much about that.

Once this fix is merged in, give it a try and report back.
