### ISSUE TITLE
Please add support for Huawei OceanStor with all Luns and Pools

### ISSUE THREAD

**Issue by BotirM** [librenms/librenms#10653]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Please keep in mind that LibreNMS is a community project, it is run by people like you using their free time. 
Which means it may take time before support is added to LibreNMS. 

We encourage you to do it yourself and submit it in GitHub as a Pull request. It is not so difficult, most of
it can be done without writing a single line of code. You can find the documentation below :
👉  https://docs.librenms.org/Developing/os/Initial-Detection/

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by BotirM** [comment]
Please add support for Huawei OceanStor with all Luns and Pools

**Comment by kkrumm1** [comment]
Please provide all information asked for.

**Comment by BotirM** [comment]
I want to add about Support OceanStor systems to LibreNMS
пн, 7 окт. 2019 г. в 16:27, Kevin Krumm <notifications@github.com>:

**Comment by kkrumm1** [comment]
Yes but if you read above you need to provide all the information. If you are coding this yourself then no need to open this. Just submit a PR.
