### ISSUE TITLE
New OS request - Dell ME4012

### ISSUE THREAD

**Issue by rvanmoorsel** [librenms/librenms#10664]
Hi,
Not quite sure if I submit this the correct way. If not, please inform me about the right way :) The FAQ on the site is not totally clear on this.  

The device I'm trying to add is a DellEMC  ME4012 SAN. I've attached the MIB as provided by DellEMC.
[me4-A01.zip](https://github.com/librenms/librenms/files/3706197/me4-A01.zip)

==================================================
Discovery output:
https://pastebin.com/Gf0BjqpJ
==================================================

==================================================
Poller output:
https://pastebin.com/uU92exec
==================================================

==================================================
SNMPWalk output:
https://pastebin.com/xw8s1yqe
==================================================

If there is anything I could do to help, please let me know!

Thanks for all the hard work! Keep it up guys!!

**Comment by asmith3006** [comment]
I would also be interested in this.

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11672

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-os-request-dell-me4012/11672/1
