### ISSUE TITLE
Move Contacts-gathering from trigger to dispatch

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#1066]
Current situation is that the contacts for an alert (this includes the override-setting 'default_mail') are gathered on trigger time.
By the time of writing this code, I felt this would be the right way to ensure that, the users who are in responsible for the device would get the alert even in case their account's permissions would change while the incident is unresolved.
However now I realize that this is not always applicable in real world as people tend to be shift around with their responsibilities and thus they should not be notified for an ongoing unresolved issue after their responsibility has been moved away from the device in question.

I can move the contact-gatherer to the Dispatch-code rather than the Trigger-code. This would reconsider and rebuild the list of contacts to inform about the incident on every notification rather than on trigger.

Pros: User-perm change would have immediate effect and not on the 'next' alert.
Cons: In case of LDAP, it would result in fairly regular LDAP queries for the entire userbase to determine userlevels and responsibilities.

Tagging @paulgear & @laf to opt into this discussion and provide their POV of the situation.

FYI: The codechange to allow Contact-Gathering on dispatch is trivial, don't bother arguing like "is it's worth the change?.." 

RFC :)

**Comment by digitalpilotnm** [comment]
Hi
Some alerts seem to only happen once a day.  During that time frame the
list of who should get notified could change.  Maybe they got sick, went on
walk-about, etc.

I can't see the load on a LDAP machine being that high to be a problem.

I'm in favor of this modification..

In the alternative, could the relevant code changes be wrapped with a
mutually exclusive check of a config value.  Such value would allow either
or behaviour.  I would suspect that would be trivial as well

+2

**Comment by paulgear** [comment]
I think @digitalpilotnm's use case is probably the most common one (i.e. needing to change how alerts are dispatched after they've occurred), and we should optimise for it. So :+1: from me to move it from trigger time to dispatch time.  If people are really worried about LDAP load, they can run a local read-only LDAP replica.

**Comment by f0o** [comment]
I'll go for the best of both worlds... like @digitalpilotnm suggested, a config switch.
I will PR this in a moment and then either @laf or @paulgear or none will merge it in.
