### ISSUE TITLE
Please add ability to create alert for power supply / fan down for all devices

### ISSUE THREAD

**Issue by louis-oui** [librenms/librenms#10677]
hello,

I see that power supply and and fan state are present in /device/device=X/tab=health/metric=state/

Could please add a generic filter for power and fan state on alert rule, so that we can create an alert rule on it ?

It is difficult to create a specific alert for each kind of device.

Thanks in advance

**Comment by kkrumm1** [comment]
This not the place to ask for this please use.  https://community.librenms.org/c/feature-requests
