### ISSUE TITLE
 FX DocuPrint M225 z, Firmware Ver.G ,MID 8C5-HA7,FID 2

### ISSUE THREAD

**Issue by echowings** [librenms/librenms#10670]
This is a printer but it can not be supported by librenms.
Operating SystemGeneric Device
Object ID.1.3.6.1.4.1.2435.2.3.9.1

**Comment by PipoCanaja** [comment]
Hi @echowings 
You have to fill all the details requested in the IssueTemplate. Please reopen it with the proper data. 
Thanx
