### ISSUE TITLE
Dell Networking OS 9 bgp 

### ISSUE THREAD

**Issue by JimKlapwijk** [librenms/librenms#10688]
It seems that in Dell Networking OS 9 bgp is not working properly.
Only in version 9.11(2.1) it does.
The problem is that no information regarding the bgp peer is provided via SNMP:
https://i.imgur.com/BMy90FJ.png

The status remains unknown etc. 
Thus all alerts go off... 

Unfortunately I have no clue how to read MIB files, but I'm glad to help if someone can point me out what to look for exactly. 
Hopefully all required information is below, if anything else is required, please let me know! 

Thank you kindly in advance. 

============
Discovery:
https://49ea53c44f8340dbb990471dcf700288.objectstore.eu/upload/da1c8729d5d6-temp1.txt?temp_url_expires=1573734963&temp_url_sig=899f4f78d490d06cd17231ac6808ed1a2cfc4f5b

Poller:
https://49ea53c44f8340dbb990471dcf700288.objectstore.eu/upload/a539b03fe4af-temp2.txt?temp_url_expires=1573734963&temp_url_sig=5a77466838ad5ade184b7b281ead441a494a2cb1

snmpbulkwalk:
https://49ea53c44f8340dbb990471dcf700288.objectstore.eu/upload/092a517b40c4-temp3.txt?temp_url_expires=1573734963&temp_url_sig=7f9b85385c327db508149ab04987664b9da4ae99

**Comment by PipoCanaja** [comment]
Hi @JimKlapwijk 
The link you posted are not permanent, making the data unavailable. Please use our pbin service, or attach the files directly to this issue.
