### ISSUE TITLE
Multiple links on map

### ISSUE THREAD

**Issue by louis-oui** [librenms/librenms#10686]
Hello,
Maps display only one link if multiple links are present between devices.
https://community.librenms.org/t/network-map-w-port-channels-or-multiple-links/2467/3

My suggestion is to remove in the if condition:
!array_key_exists($device_id1, $device_assoc_seen) &&
!array_key_exists($device_id2, $device_assoc_seen)

" // Ensure only one link exists between any two ports, or any two devices. it prints only one link
if (!array_key_exists($link_id1, $link_assoc_seen) &&
!array_key_exists($link_id2, $link_assoc_seen) &&
!array_key_exists($device_id1, $device_assoc_seen) &&
!array_key_exists($device_id2, $device_assoc_seen)) {
$local_port = cleanPort($local_port);
$remote_port = cleanPort($remote_port);
// $local_port = cleanPort($items[‘local_port_id’]);
//$remote_port = cleanPort($items[‘remote_port_id’]);
$links[] = array_merge(
array(
‘from’=>$items[‘local_device_id’],
"

**Comment by laf** [comment]
If you have a fix, please submit a pull request.
