### ISSUE TITLE
Graphs and config not working

### ISSUE THREAD

**Issue by bitency** [librenms/librenms#10703]
Hi,

I have updated LibreNMS today, but we have a few problems:

- Graphs not showing anymore from port on the ports page from a switch
- Billing Graphs are not showing anymore
- If i go to a switch (switch -> config) for the configuration (Oxidized) then i get a big logo from the brand of the switch

Screenshots:
https://ibb.co/FVqT68p
https://ibb.co/0ytsx8H
https://ibb.co/Gk0Q88L

Version 1.56-34-g25e8de3 - Thu Oct 17 2019 04:46:44 GMT+0200 

[librenms@nms ~]$ ./daily.sh
Updating to latest codebase                        OK
Updating Composer packages                         OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK

[librenms@nms ~]$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.56-34-g25e8de3
DB Schema | 2019_02_05_140857_remove_config_definition_from_db (145)
PHP       | 7.2.21
MySQL     | 5.5.60-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Composer Version: 1.9.0
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct

**Comment by kkrumm1** [comment]
It’s know and also don’t post issues it’s only for new device support.
