### ISSUE TITLE
Model detection of old 3Com 4200 device

### ISSUE THREAD

**Issue by joseUPV** [librenms/librenms#10717]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Please keep in mind that LibreNMS is a community project, it is run by people like you using their free time. 
Which means it may take time before support is added to LibreNMS. 

We encourage you to do it yourself and submit it in GitHub as a Pull request. It is not so difficult, most of
it can be done without writing a single line of code. You can find the documentation below :
👉  https://docs.librenms.org/Developing/os/Initial-Detection/

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by joseUPV** [comment]
We have and Old 3Com 4200 Series Gigabit device.

SNMPv2-MIB::sysDescr.0 = STRING: 3Com SuperStack 3
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.43.10.27.4.1.2.11

Poller detects this:
#### Load poller module os ####
Hardware: SuperStack 3
Version:
Features:
Serial:

There are no reference of model in de snmp data of the switch or in mibs in librenms.

I have found a old 3Com with model oid references: [A3COM0025-STACK-UNIT-TYPES](http://www.mibdepot.com/cgi-bin/vendor_index.cgi?r=a3com)
Is It worth a try to add this mib to get the model number with this:
preg_match('/stackSwitch(.+)/', snmp_get($device, 'sysObjectID.0', '-Osqv', 'A3COM0025-STACK-UNIT-TYPES'), $model); // stackSwitch4200
$hardware.=$model[1];

**Comment by joseUPV** [comment]
ports can be obtained from:

stack24Port10100BaseTxSwitch2T   OBJECT IDENTIFIER ::= {stackUnitTypes 56}
stack24Port10100BaseTxSwitch2T2G OBJECT IDENTIFIER ::= {stackUnitTypes 57}
stack48Port10100BaseTxSwitch2T   OBJECT IDENTIFIER ::= {stackUnitTypes 58}

**Comment by joseUPV** [comment]
I have tested it, are needed four mibs:  A3COM0004-GENERIC  A3COM0025-STACK-UNIT-TYPES  A3COM0352-STACK-CONFIG  A3Com-products-MIB
And this code:
if (preg_match('/stackSwitch(.+)/', snmp_get($device, 'sysObjectID.0', '-Osqv', 'A3COM0025-STACK-UNIT-TYPES'), $model)) {
        // stackSwitch4200
        $hardware.= ' ' . $model[1];
    }

I will create a PR next week.

**Comment by kkrumm1** [comment]
@joseUPV there is no need to open an issue on this just submit your PR.
