### ISSUE TITLE
New Device: D-Link CCTV DCS-7513

### ISSUE THREAD

**Issue by Chewie9999** [librenms/librenms#10712]
Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

This is just detected as "Generic Device", but is a PoE CCTV camera.

Please see below for diagnostic output

https://p.libren.ms/view/f3a60fe4
https://p.libren.ms/view/4b0119ec
https://p.libren.ms/view/fb8a1dfc

The NICs etc are detected and are being graphed properly, I think it's just the device type that needs adding.

Thanks

**Comment by PipoCanaja** [comment]
Hi @Chewie9999 
Thanx for the informations. As you describe it, it seems that you only need to add proper icon and device type. This is fairly easy to do. 
Would you like to have a look on the link below, add the support and submit it as a Pull Request? 
https://docs.librenms.org/Developing/os/Initial-Detection/

As you may have seen, there is a huge backlog of devices to add ... 

Thanx

**Comment by Chewie9999** [comment]
Hi @PipoCanaja,
Thank you for the reply, I will try it and update the issue accordingly :)

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11671

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-d-link-cctv-dcs-7513/11671/1
