### ISSUE TITLE
HPE J9773A Switch incorrect discovery and polling

### ISSUE THREAD

**Issue by EvilGrinUK** [librenms/librenms#10734]
Device: HP J9773A 2530-24G-PoEP Switch, revision YA.16.09.0003
LibreNMS version: 1.56-72-g10b1b9c

When discovered, several sensors are setup and labeled as 'port 25'. Including one sensor for 'Port 25 tx/rx power' that is labeled as DBm. This also produces alerts for out of bounds values.

Please see the screenshot for an example.

![image](https://user-images.githubusercontent.com/2217729/67274358-2eedb180-f4b8-11e9-83ac-64ca5827e1fd.png)

![image](https://user-images.githubusercontent.com/2217729/67274407-475dcc00-f4b8-11e9-88d4-23d65b2b8ab0.png)

**Comment by laf** [comment]
You need to provide the information asked for when you open an issue.

**Comment by EvilGrinUK** [comment]
errornous DBm readings were fixed by a device rescan.
