### ISSUE TITLE
don't report BGP down, when BGP is in a admin down state

### ISSUE THREAD

**Issue by digitalpilotnm** [librenms/librenms#1074]
LibreNMS is reporting that a BGP session is "down"  yet that session/peer is in an admin down state in the router.   as in 

router bgp 12345
  neigh 1.2.3.4 remote-a  99999
  neigh 1.2.3.4 SHUTDOWN

I would think, like ports, we wouldn't report this as down

**Comment by f0o** [comment]
I suggest adjusting the Rule to include something like `%bgpPeers.bgpPeerState != "idle"`
