### ISSUE TITLE
Incorrect discovery of port-speed on Cisco 3750's, cisco 3500 family, cisco 6509

### ISSUE THREAD

**Issue by digitalpilotnm** [librenms/librenms#1075]
Libre is reporting that a port has exceeded utilization of 80% for a port.
For some reason Libre thinks the port is a 10Mb/s, yet when we log into the Cisco, its clearly showing 1000Mb/s

GigabitEthernet0/1 is up, line protocol is up (connected) 
  Hardware is Gigabit Ethernet, address is 24b6.5783.6ac1 (bia 24b6.5783.6ac1)
  Description: A USEFUL DESCRIPTION
  Internet address is 1.2.3.4/30
  MTU 9000 bytes, BW 10000 Kbit/sec, DLY 10 usec, 
     reliability 255/255, txload 114/255, rxload 255/255
  Encapsulation ARPA, loopback not set
  Keepalive set (10 sec)
  Full-duplex, 1000Mb/s, media type is 10/100/1000BaseTX

This creates false alarms

**Comment by f0o** [comment]
Can you give us more information about your hardware?

**Comment by digitalpilotnm** [comment]
Cisco 3750's, cisco 3500 family,  cisco 6509 (Sup720-3BXL)

**Comment by laf** [comment]
In the webui does it show the port as 10mb?

Do you have bandwidth config on the interfaces?

**Comment by digitalpilotnm** [comment]
Yes, it shows at 10Mb, 
No I do not have a bandwidth statement on the inferface configs.
It will also flip to higher bandwidth levels at various times

2015-05-19 14:15:20	csr01.abq	Gi2/45	ifSpeed: 100000000 -> 10000000
2015-05-19 13:35:24	csr01.abq	Gi2/45	ifHighSpeed: 10 -> 100
2015-05-19 13:35:24	csr01.abq	Gi2/45	ifSpeed: 10000000 -> 100000000

**Comment by laf** [comment]
We're only reporting what's coming back from snmp, I wonder if it's flipping due to get ifHighSpeed one time and then not another. We might have to do some digging on this.

**Comment by adammmmm** [comment]
I'm pretty sure it's the bandwidth: "BW 10000 Kbit/sec" which screws it up. I've observed the same issue with a bunch of our ISP's routers. Especially on tunnel interfaces which defaults to 100 Kbit/s if you don't change it with the "bandwidth"-command under the interface.

**Comment by digitalpilotnm** [comment]
So what can be done about it ?   It seems to flip-flop .  Using the
bandwidth command is a reasonable way to tell protocols like OSPF what the
link speed is.   Important when you have a microwave connection that does
500Mb/s, but the physical ethernet ports are full GigE.    I'd want to know
that at 400Mb/s we have hit 80 percent.

**Comment by Rosiak** [comment]
Is this still relevant?

**Comment by digitalpilotnm** [comment]
I believe so. I haven't seen anything to say its fixed, or such.
I disabled those (and many other alerts) because it was very chatty.

I will turn it back on today and see what it does and report back based on
current version of librenms code

**Comment by digitalpilotnm** [comment]
Yes, this is still a bug.

I've got GigE interfaces that are alerting for over threshold, yet the
actual bw being used is less than 100Mb/s  and in some cases less than
10Mb/s

**Comment by ekoyle** [comment]
Just to be sure, are the ports running at 1gbit at the time of the alert?
We have seen this kind of behavior on client ports when clients go to sleep
and bump the connection speed down to 10Mbit full-duplex, even though it is
a gig nic on the client.

**Comment by digitalpilotnm** [comment]
yes the ports are at 1gig
No there is nothing plugged in that "goes to sleep"
These are infrastructure ports, so the have other routers, or switches, or
ptp microwave radios connected to them.
NOT desktop hosts that power down.
