### ISSUE TITLE
Memcached app always reports app_state="ERROR"

### ISSUE THREAD

**Issue by willhseitz** [librenms/librenms#10768]
**PLEASE READ FIRST**

**Please do not post bugs or ask questions or feature requests here**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org/c/help).**

To create a new device request please use this link: https://github.com/librenms/librenms/issues/new?template=New-Device.md

---
The memcached.inc.php application poller always returns app_state as "ERROR". This is because the returned $details value is an array, and the update_application() function expects that parameter as a string

**Comment by willhseitz** [comment]
proposed fix #10739

**Comment by kkrumm1** [comment]
No need to open an issue to go with the PR.
