### ISSUE TITLE
Raritan PDU - CPU temperature sensor continuosly readded

### ISSUE THREAD

**Issue by robertobru** [librenms/librenms#10779]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ X] Please provide as much detail as possible.
- [ X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Please keep in mind that LibreNMS is a community project, it is run by people like you using their free time.
Which means it may take time before support is added to LibreNMS.

We encourage you to do it yourself and submit it in GitHub as a Pull request. It is not so difficult, most of
it can be done without writing a single line of code. You can find the documentation below :
👉  https://docs.librenms.org/Developing/os/Initial-Detection/

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Dear LibreNMS community,
I'm opening this issue because of a possible bug in the discovery of temp sensors in the Raritan OS.
In detail, it seems that in older Raritan PDUs the CPU Temp sensor is rediscovered approximately every 6 hours as a new sensor, and added to the list of temp sensors. 
I tried to remove and readd this PDU 11 days ago: at the beginning I had only 1 temp sensor, now LibreNMS reports 45 CPU temp sensors for that CPU, each one with exactely the same values.

Please note that this happens only with the PDUs using the old Raritan MIBs (recognized with obj id .1.3.6.1.4.1.13742.4). I have more recent PDUs using the new Raritan MIBs that are not affected by this bug.

The requested output info are in the following URLs:
[snmpbulkwalk](https://p.libren.ms/view/1e3235c3)
[poller](https://p.libren.ms/view/d2e00606)
[discovery](https://p.libren.ms/view/cb313f41)

The output of validate.php is the following:
====================================
Component | Version
--------- | -------
LibreNMS  | 1.57-12-gd90b0212b
DB Schema | 2019_10_03_211702_serialize_config (145)
PHP       | 7.2.19-0ubuntu0.18.04.2
MySQL     | 10.1.41-MariaDB-0ubuntu0.18.04.1
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.9.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[FAIL]  We have found some files that are owned by a different user than librenms, this will stop you updating automatically and / or rrd files being updated causing graphs to fail.
        [FIX]:
        sudo chown -R librenms:librenms /opt/librenms
        sudo setfacl -d -m g::rwx /opt/librenms/rrd /opt/librenms/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
        sudo chmod -R ug=rwX /opt/librenms/rrd /opt/librenms/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
        Files:
         /opt/librenms/.config
         /opt/librenms/.config/oxidized
         /opt/librenms/.config/oxidized/config

**Comment by kkrumm1** [comment]
Please bugs and issues dont go here. ONLY NEW DEVICE requests. Use the forums or discord.
