### ISSUE TITLE
Chloride UPS

### ISSUE THREAD

**Issue by guestus** [librenms/librenms#10813]
Please confirm each of the sections below by putting an `x` in the box like `[x]`.
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
discovery.php: https://p.libren.ms/view/94d2d61a
poller.php: https://p.libren.ms/view/85f417d0
snmpbulkwalk: https://p.libren.ms/view/4151a97c
- [x] Please provide as much detail as possible.
this is chloride UPS whith SNMP card installed. Must use standard MIB UPS-MIB
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11670

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/chloride-ups/11670/1
