### ISSUE TITLE
IOS-XE temperature alarms

### ISSUE THREAD

**Issue by tylerapplebaum** [librenms/librenms#1081]
I receive these every 15 minutes or so...

Temperature Alarm: rtr-inet-b module R0 - CPU Die R0/20 - CPU Die is under
threshold: 15C (< 120C)

I've done everything I think I need to do to disable them, and yet they are still alerting.

**Comment by laf** [comment]
That's our old alerting system, disable it to start with and ensure you are only using the new one :)

https://groups.google.com/forum/#!topic/librenms-project/1llxos4m0p4

http://docs.librenms.org/Extensions/Alerting/#transports-email

Then you can define what rules you want to run.

**Comment by tylerapplebaum** [comment]
That worked :)

My colleagues thank you... they were sick of those.

This may be a record for fasted ever "bugfix".

**Comment by paulgear** [comment]
:+1:
