### ISSUE TITLE
VRF Support  for Alcatel Enterprise Switches

### ISSUE THREAD

**Issue by joseUPV** [librenms/librenms#10845]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Please keep in mind that LibreNMS is a community project, it is run by people like you using their free time.
Which means it may take time before support is added to LibreNMS.

We encourage you to do it yourself and submit it in GitHub as a Pull request. It is not so difficult, most of
it can be done without writing a single line of code. You can find the documentation below :
👉  https://docs.librenms.org/Developing/os/Initial-Detection/

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by joseUPV** [comment]
Module VRF doesn't work with alcatel Enterprise switches.
Here is a snmpwalk of VRF data of one Alcatel 6900 Enterprise (two devices in one virtual chassis):
# snmpwalk -m ALCATEL-IND1-VIRTUALROUTER-MIB -M /disco2/opt/librenms/mibs:/disco2/opt/librenms/mibs/nokia/aos7 o94-asic4l alaVirtualRouterConfig | ./pbin.sh
Pastebin: https://p.libren.ms/view/ed45bc1e

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/vrf-support-for-alcatel-enterprise-switches/11602/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11602
