### ISSUE TITLE
Request: Gui tool to test / validate email alert settings

### ISSUE THREAD

**Issue by digitalpilotnm** [librenms/librenms#1084]
At present one has to fail an interface, create an alert, and then wait up to 11 minutes before knowing if librenms will properly send email based on settings in config.php

It would be useful to have a tool that simulates an alert and thus immediately sends an email via normal system channels.

**Comment by f0o** [comment]
You can create a rule like `macros.device = 1` and have delay set to `0` and count to `-1` - that does alert instantly and forever.

However, if this is not acceptable I can create a small test-page to send mock alerts.
