### ISSUE TITLE
add support for data plane cpu monitoring on SRX devices

### ISSUE THREAD

**Issue by radoslawcz** [librenms/librenms#1085]
LibreNMS monitors control plane CPU on SRX devices. Please add support for data plane CPU monitoring. Details here: https://kb.juniper.net/library/CUSTOMERSERVICE/GLOBAL_JTAC/BK26199/SRX%20SNMP%20Monitoring%20Guide_v1.2.pdf

**Comment by laf** [comment]
Merged in :)
