### ISSUE TITLE
FiberStore S3900-24T4S Switch

### ISSUE THREAD

**Issue by valsily** [librenms/librenms#10866]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
Discovery: https://p.libren.ms/view/9a9500be
Poller: https://p.libren.ms/view/2068a2ea
Snmpwalk: https://github.com/librenms/librenms/files/3877744/S3900_snmpwalk.zip
MIB file: https://img-en.fs.com/file/user_manual/fs-s3900-series-switches-snmp-mib-files.zip
- [x] Please provide as much detail as possible.
The switch is currently detected as "Generic Device" without OS information. The link status of the ports is not shown ( all in blue regardless of the links are up or down). Is it possible to extend the support to cover this model? 
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Please keep in mind that LibreNMS is a community project, it is run by people like you using their free time.
Which means it may take time before support is added to LibreNMS.

We encourage you to do it yourself and submit it in GitHub as a Pull request. It is not so difficult, most of
it can be done without writing a single line of code. You can find the documentation below :
👉  https://docs.librenms.org/Developing/os/Initial-Detection/

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by valsily** [comment]
This is how it currently looks in Librenms
![FS3900-Librenms](https://user-images.githubusercontent.com/13020079/69357838-c36a5000-0cc0-11ea-9596-ca47f1b5c562.PNG)

**Comment by PipoCanaja** [comment]
Hi @valsily 
Could you check the snmpwalk capture (Snmpwalk: https://p.libren.ms/view/79501ffc) and prevent any Carriage Returns in the middle of it ? It makes the import impossible in snmpsim, and this is necessary for a contributor to work on this device without having it locally. 
Thanx

**Comment by valsily** [comment]
@PipoCanaja Sorry I did not notice that there were so many Carriage Returns in my previous snmp upload and it also seemed to be incomplete. The output was a direct copy-and-paste from Librenms Capture feature in Google Chrome. I just run a capture again and the output still has hundreds of random Carriage Returns. 

Anyway, I have cleaned up the output but it seems to be too large for the Paste service as I get an error:

**Error Number: 1153

Got a packet bigger than 'max_allowed_packet' bytes**

I am attaching the output here as a zipped text file. Please let me know if it works this time.

[S3900_snmpwalk.zip](https://github.com/librenms/librenms/files/3877744/S3900_snmpwalk.zip)

Really appreciate your time and help.

**Comment by PipoCanaja** [comment]
@valsily 
Seems that you still have issues in this snmpwalk. Could you please do it in CLI, exactly as suggested in the documentation (I suspect you did it in the WEB ui, cause there is some html noise at the end stating that a timeout occued)
Thanx

**Comment by valsily** [comment]
> @valsily
> Seems that you still have issues in this snmpwalk. Could you please do it in CLI, exactly as suggested in the documentation (I suspect you did it in the WEB ui, cause there is some html noise at the end stating that a timeout occurred)
> 
> `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME . > s3900.txt ` and attach the zipped file here ?
> 
> Thanx

@PipoCanaja Sorry for the trouble. I am attaching the dump file created using the command above.
However, there are some error messages in the console which are not captured in the text file:




[s3900.txt](https://github.com/librenms/librenms/files/3919324/s3900.txt)

root@odroid:/opt/librenms# snmpbulkwalk -OUneb -v2c -c public 192.168.2.250 . > /tmp/s3900.txt
Error: OID not increasing: .1.3.6.1.2.1.4.22.1.4.1030.192.168.1.250
 >= .1.3.6.1.2.1.4.22.1.4.1001.192.168.2.1

Error: OID not increasing: .1.3.6.1.2.1.4.22.1.4.1030.192.168.1.250
 >= .1.3.6.1.2.1.4.22.1.4.1001.192.168.2.10

Error: OID not increasing: .1.3.6.1.2.1.4.22.1.4.1030.192.168.1.250
 >= .1.3.6.1.2.1.4.22.1.4.1001.192.168.2.11

Error: OID not increasing: .1.3.6.1.2.1.4.22.1.4.1030.192.168.1.250
 >= .1.3.6.1.2.1.4.22.1.4.1001.192.168.2.18

Error: OID not increasing: .1.3.6.1.2.1.4.22.1.4.1030.192.168.1.250
 >= .1.3.6.1.2.1.4.22.1.4.1001.192.168.2.20

Error: OID not increasing: .1.3.6.1.2.1.4.22.1.4.1030.192.168.1.250
 >= .1.3.6.1.2.1.4.22.1.4.1001.192.168.2.21

Error: OID not increasing: .1.3.6.1.2.1.4.22.1.4.1030.192.168.1.250
 >= .1.3.6.1.2.1.4.22.1.4.1001.192.168.2.22

Error: OID not increasing: .1.3.6.1.2.1.4.22.1.4.1030.192.168.1.250
 >= .1.3.6.1.2.1.4.22.1.4.1001.192.168.2.25

Error: OID not increasing: .1.3.6.1.2.1.4.22.1.4.1030.192.168.1.250
 >= .1.3.6.1.2.1.4.22.1.4.1001.192.168.2.91

Error: OID not increasing: .1.3.6.1.2.1.4.22.1.4.1030.192.168.1.250
 >= .1.3.6.1.2.1.4.22.1.4.1001.192.168.2.92

**Comment by PipoCanaja** [comment]
Yep, it seems even worse with those OID not increasing.

Could you try to apply the current patch by typing, as librenms user, the following commands : 
``` ./scripts/github-apply 10904 ```
``` rm cache/os_defs.cache ```
``` ./discovery.php -h <yourDevice> ```

**Comment by PipoCanaja** [comment]
That should give you the "FS" icon. 

And then, please try to run this variant of snmpwalk : 

``` snmpbulkwalk -Cc -OUneb -v2c -c COMMUNITY HOSTNAME . > s3900.txt ```

The resulting file, if successful, should at least be more than 3.2 Mb big...

**Comment by valsily** [comment]
@PipoCanaja Thanks for your prompt response. Yes, with the patch now I have FS icon!!

![2019-12-04_20-02-31](https://user-images.githubusercontent.com/13020079/70141282-ae82b900-16d1-11ea-8619-a5eafd780c54.png)

And the new SNMP dump has 5225 KB in size. Please see attached.
[s3900_new.zip](https://github.com/librenms/librenms/files/3921692/s3900_new.zip)

Thank you very much.

**Comment by PipoCanaja** [comment]
Hi @valsily 
Could you please remove the patch you added previously, (using ./scripts/github-remove) and reapply it (so you get current version).
You should get much more details.

**Comment by valsily** [comment]
Hi @PipoCanaja 

After re-applying the patch, I can now see the new Health tab with CPU and temperature information. 

![2019-12-05_11-13-40](https://user-images.githubusercontent.com/13020079/70201237-f1d03c80-1750-11ea-81ed-04a8ac0f0bec.png)

However, I noticed that the version number in the Operating System field is 1.4. Below is what I see in the S3900 management interface. It seems that it's the (boot)loader version value that is picked by Librenms. Just wondering whether it should be the "firmware version" instead?

![2019-12-05_11-14-50](https://user-images.githubusercontent.com/13020079/70201236-f137a600-1750-11ea-9aee-0b5e59cff412.png)

Thank you very much for your help.

**Comment by PipoCanaja** [comment]
- Concerning the version, the patch is already pushed. 
- The port link status is presented as "lowerLayerDown" and not as "down". This seems not to be handled by LibreNMS right now. Will have a look at how we could handle this but won't happen in the short time.

**Comment by valsily** [comment]
Hi @PipoCanaja 

Thanks for the prompt action. With latest patch, the color coded port link status works.
The only glitch I can see is the total number of down links. It should be 16 (33-17) while currently showing 0. 

![Cap](https://user-images.githubusercontent.com/13020079/70233241-1f40d880-1799-11ea-8596-e2dac9bd59a2.PNG)

Kudos to you for the great and continuous support!!

**Comment by PipoCanaja** [comment]
@valsily This one is also OK now. You can refresh your patch and test this.

**Comment by valsily** [comment]
> @valsily This one is also OK now. You can refresh your patch and test this.

Hi @PipoCanaja ,

Yes, I can confirm the number of down links is correct after re-applying the patch.

Thanks a lot.
