### ISSUE TITLE
NEC M Series RAID chassis

### ISSUE THREAD

**Issue by ideasman69** [librenms/librenms#10860]
Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

- **./discovery.php -h raid1c0 -d**
https://p.libren.ms/view/e9d51fc3

- **./poller.php -h raid1c0 -r -f -d**
https://p.libren.ms/view/90e726ad

- **snmpwalk -OUneb -v1 -c public raid1c0 .**
https://p.libren.ms/view/63a3f405

- [x] Please provide as much detail as possible.
These NEC RAID units have 12 disks per chassis. There's a primary chassis with 2 controllers and 2 power supplies. Connected to the primary chassis is an expansion chassis with another 12 disks and two power supplies. The current config is 4x 6 drive RAID5 LUNs across the 24 drives. Here's the MIB file: [ARMGMT-MIB-M_j2gv.zip](https://github.com/librenms/librenms/files/3871659/ARMGMT-MIB-M_j2gv.zip)

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11669

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/nec-m-series-raid-chassis/11669/1
