### ISSUE TITLE
Request support for Huawei Dorado5000 V3 storage system

### ISSUE THREAD

**Issue by erdems** [librenms/librenms#10889]
Relevant information:

https://p.libren.ms/view/677e98f7
https://p.libren.ms/view/0decadd6
https://p.libren.ms/view/6b95d25b

**PLEASE READ FIRST**

**Please do not post bugs or ask questions or feature requests here**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org/c/help).**

To create a new device request please use this link: https://github.com/librenms/librenms/issues/new?template=New-Device.md

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11668

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/request-support-for-huawei-dorado5000-v3-storage-system/11668/1
