### ISSUE TITLE
Cacti like zooming for graphs

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#1091]
Would LOOOOOOOOOVE to see this support.
Laf have this implemented somewhere, but a few things needs to be resolved he mentioned.

**Comment by SaaldjorMike** [comment]
:+1:

**Comment by f0o** [comment]
:+1:

**Comment by Lonecrowe** [comment]
:white_check_mark:

**Comment by joubertredrat** [comment]
+1
why not? This is good feature :)

**Comment by Rosiak** [comment]
Perhaps highcharts.com can be used to some extend, investigating

**Comment by nickatniteatx** [comment]
+1 this is the only thing I miss from cacti

**Comment by wiad** [comment]
I too miss this from cacti, it would be a really big improvement.

**Comment by Rosiak** [comment]
Will be addressed in v2

**Comment by juanquy** [comment]
anyone having issues zooming graph?

**Comment by murrant** [comment]
Everyone is, it is not supported.  ;)

**Comment by juanquy** [comment]
Whatttt!!! We need that feature !! Let do it Libre!!!
