### ISSUE TITLE
Support for Inteno/Genexis devices - XG6846

### ISSUE THREAD

**Issue by sp1rr3** [librenms/librenms#10923]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery : https://p.libren.ms/view/c2070efd
Poller : https://p.libren.ms/view/2958991b
snmpwalk : https://p.libren.ms/view/10e280e6

Mib file:
[XAVI-XG6846-MIB.zip](https://github.com/librenms/librenms/files/3943620/XAVI-XG6846-MIB.zip)

Inteno/Genexis is a big provder of CPE/Gateway solutions to ISPs. would be nice to get device support in librenms. right now it shows just as a generic device.

**Comment by PipoCanaja** [comment]
Hi @sp1rr3 
Support can be tested in the PR. 
Bye
