### ISSUE TITLE
'Mail' Alert Transport does not allow multiple email addresses

### ISSUE THREAD

**Issue by admiralspark** [librenms/librenms#10938]
LibreNMS version impacted: **1.58.1**, possibly more.

## How to reproduce:
Go to **Alerts** > **Alert Transports**
Click **+ Create alert transport**
Enter a name, select Transport Type **Mail**, Default Alert is **off**, and [entering multiple emails per the documentation](https://docs.librenms.org/Alerting/Transports/#mail) gives the following error: 
`The email must be a valid email address.`

#### Image of error below:
https://imgur.com/a/TZpRWnN

I'll poke at it, but if anyone else has a fast fix please submit it here as I'm pretty slow.

**Comment by PipoCanaja** [comment]
Hi @admiralspark 
The easy workaround is a transport group with multiple transport emails. I think that the fix here should be in the documentation, indicating that only 1 email address should be entered in a Transport. 
I'll leave this one opened for now.

**Comment by admiralspark** [comment]
Hi @PipoCanaja 
Is that really the correct solution though, removing features? The actual issue is that when LibreNMS started using [Laravel validation](https://laravel.com/docs/5.7/validation), they accidentally introduced this problem because the current validation checks only for one email, not allowing multiple. 

https://github.com/librenms/librenms/blob/e98dd35a9b13330c49211bce87f09921c9204ad2/LibreNMS/Alert/Transport/Mail.php#L56

I honestly just haven't had time to look into whether it can be worked around or they have extended options for it, will check it out this week.

**Comment by PipoCanaja** [comment]
The documentation was done before Transports were created, and not updated. And in Transports, the idea is to have one Transport per target, and combine multiple transports.

**Comment by kkrumm1** [comment]
Updated docs https://github.com/librenms/librenms/pull/10963

**Comment by PipoCanaja** [comment]
Thx. We can close this.
