### ISSUE TITLE
Add back power sensor data from Microsemi midspans

### ISSUE THREAD

**Issue by lfkeitel** [librenms/librenms#10952]
Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery: https://p.libren.ms/view/d58f590c
Poll: https://p.libren.ms/view/dc303e68
SNMP Walk: https://p.libren.ms/view/349dad06

Running discovery on a Microsemi midspan powerdsine no longer polls the power sensors on the ports. The last working device was discovered on 2018-03-12 17:42:39. The discovery shows the power sensors in the log but they aren't saved to the database.

Issue opened at request of [PipoCanaja](https://community.librenms.org/t/microsemi-midspans-not-showing-port-wattage/10323/11)

**Comment by PipoCanaja** [comment]
Hi @lfkeitel 
Looking at the doc (here : https://www.microsemi.com/documents/powerdsine/support/downloads/snmp/Technote_PoE_MIB.pdf ) I don't find the POE consumption of a port. So I don't understand what you had in graphs before. 
- Could you share a screen of a working device (not rediscovered) so I get a chance to see what you would like to get ? 
- Could you share the result of ./poller.php -h <device> -v -m ports on working device (not rediscovered) ?

**Comment by lfkeitel** [comment]
Poll for working device: https://p.libren.ms/view/9d7c409f (beginning line 35) It's the sensors module, not port. The port only returns its management interface. That interface doesn't do power.

![librenms_port_power](https://user-images.githubusercontent.com/6619743/71019247-a2c6c780-20bf-11ea-92a6-a1f340b370a3.png)

In the discovery log I link above, the power sensors start at line 380.

**Comment by PipoCanaja** [comment]
OK, got it. It not using the POE code in LibreNMS at all, only a sensor. Should be fixable. 

Could you get the mibfile from the vendor ? We don't have it for the moment, makes things more difficult and less understandable.

**Comment by lfkeitel** [comment]
I found an old pull request with the MIB but it wasn't accepted: https://github.com/librenms/librenms/pull/7075 (MIB: https://github.com/EnzoZafra/librenms/blob/ece46b3a850af8c2a2dd8e07aff6d639fb01ecea/mibs/microsemi/MICROSEMI-PDSINE-MIB).

I can't find an "official" MIB file from them. Is this file https://github.com/librenms/librenms/blob/master/includes/discovery/sensors/power/microsemipdsine.inc.php not suppose to find that particular SNMP path?

**Comment by PipoCanaja** [comment]
Working with numerical OID is annoying (and currently broken here). Rewriting it is mandatory, so I try first to do it with textual OIDs, if possible,

**Comment by PipoCanaja** [comment]
Hi @lfkeitel 
You can test by typing : 
`./scripts/github-apply 10959`
`./discovery.php -v -d -h <deviceId>`

Let me know how it goes.

**Comment by lfkeitel** [comment]
That works!

**Comment by lfkeitel** [comment]
Thank you so much for looking into this. We really appreciate it.

**Comment by PipoCanaja** [comment]
OK.
It is now merged. You need to revert the patch you apply before next LibreNMS upgrade. If not, you'll get a message that the upgrade failed. 
Bye
