### ISSUE TITLE
Time Machines NTP SNMP support added

### ISSUE THREAD

**Issue by 07stuntar1** [librenms/librenms#10950]
Time Machines
https://timemachinescorp.com/

Looks like they added support for SNMP in version 0.3.4 These timemachine have been working really well for us. We would like to be able to monitor them.

Version 0.3.4
9/2019 0.3.4

SNMP V2/V3 Support
Ability to access Peer NTP servers
Manual Time Setting
UDP Packet Formatting Update to PTP
NTP Authentication Support
Minor change to NTP Response Packets
Update takes 20-25 minutes to complete
Not Compatible with Verizon eFemto Applications, contact css-design.com

https://p.libren.ms/view/9699f15c
https://p.libren.ms/view/57c95924
https://p.libren.ms/view/a8a5329d

I have attached there MIB

[TMI-COMMON-SHI.txt](https://github.com/librenms/librenms/files/3971110/TMI-COMMON-SHI.txt)

**Comment by PipoCanaja** [comment]
Hi @07stuntar1 
Unfortunately, only standard linux OIDs are in your walk. Not a single OID from the proprietary mib. And there is no way to discriminate this from a standard linux box. So I think you still have some configuration to change on the device to enable the MIB (or may be another update)

**Comment by 07stuntar1** [comment]
Maybe the next update. I have enabled everything

**Comment by PipoCanaja** [comment]
Ok.
Then please close the issue here, and reopen it when the data is available. 
Thx
