### ISSUE TITLE
Support temperatures on FreeBSD

### ISSUE THREAD

**Issue by Duffyx** [librenms/librenms#10964]
Hi guys, this is not really a "device" request although it is an extra functionality for FreeBSD hosts. I'm wondering what the easiest method would be to extend the snmp agent or the LibreNMS agent to import temperatures in graphs from the following sysctls:

dev.cpu.0.temperature: 24.0C
dev.cpu.1.temperature: 24.0C
dev.cpu.2.temperature: 25.0C
dev.cpu.3.temperature: 25.0C
dev.cpu.4.temperature: 22.0C
dev.cpu.5.temperature: 21.0C
dev.cpu.6.temperature: 22.0C
dev.cpu.7.temperature: 21.0C
dev.jedec_dimm.0.temp: 30.7C
dev.jedec_dimm.1.temp: 30.7C
dev.jedec_dimm.2.temp: 30.6C
dev.jedec_dimm.3.temp: 29.7C
hw.acpi.thermal.tz0.temperature: 27.9C
hw.acpi.thermal.tz1.temperature: 29.9C

The above output is a simple 2 line script I have locally so very easy to extract temperatures.
I'm happy to provide more details, script to get the values required or anything else.
I just don't see myself coding it in through a pull request as that exceeds my technical knowledge.

**Comment by kkrumm1** [comment]
It would better if you submit this a pull request.
