### ISSUE TITLE
Search field parsing is slightly broken:  Location or Type; not both

### ISSUE THREAD

**Issue by fjwcash** [librenms/librenms#1098]
On the devices list page (with all the search fields on top), you can search by any combination of the items in the first row:  Hostname, OS, Version, Platform.

However, you can only search for using 1 of the fields in the second row:  Location, Device Type.

Once you select one of the fields in the second row, selecting the other one always results in 0 items displayed.  There's an issue with the array parameter parsing in the PHP code.

The following patch fixes the issue, allowing you to use any combination of any of the search fields:
```
diff --git a/html/includes/table/devices.inc.php b/html/includes/table/devices.inc.php
index 68a29e2..f168805 100644
--- a/html/includes/table/devices.inc.php
+++ b/html/includes/table/devices.inc.php
@@ -38,7 +38,8 @@ if (!empty($_POST['ignore']))   { $sql .= " AND `ignore`= ?";       $param[] = $
 if (!empty($_POST['location']) && $_POST['location'] == "Unset") { $location_filter = ''; }
 if (!empty($_POST['location'])) {
     $sql .= " AND (((`DA`.`attrib_type`='override_sysLocation_string' AND `DA`.`attrib_value` = ?)) OR `location` = ?)";
-    $param = array(mres($_POST['location']),mres($_POST['location']));
+    $param[] = mres($_POST['location']);
+    $param[] = mres($_POST['location']);
 }
 if( !empty($_POST['group']) ) {
     require_once('../includes/device-groups.inc.php');
```

**Comment by laf** [comment]
Thanks for the report and fixing, you can submit this as a pull request yourself if you like?

**Comment by fjwcash** [comment]
Oops, my e-mail reply got messed up.

How does one do a pull request?  I've never done one before.

**Comment by f0o** [comment]
@fjwcash easiest way:
0) Fork the LibreNMS repo at https://github.com/librenms/librenms
1) Create a branch called issue-1098
2) commit & push you patch
3) go to https://github.com/librenms/librenms - it should show you a big green button to Compare&Pull-Request the changes
4) ???
5) Profit!!!


-1) Sign Contributor's Agreement, it will be shown when you attempt to PR something

**Comment by fjwcash** [comment]
Okay, I think I've done it right.  :)  Let me know if there's anything missing.

**Comment by laf** [comment]
That looks correct. If you now click pull request within that branch you should be able to submit it.

If you can also do a pull request to sign the contributors agreement that would be great, an example one is: https://github.com/librenms/librenms/pull/1027

**Comment by fjwcash** [comment]
Done.  I think.  I see 2 pull requests against my forked repo, but they aren't showing on the pull requests list for the master repo, so not sure if they were done correctly, or if I missed a step, or ... ?

https://github.com/fjwcash/librenms/pull/1
https://github.com/fjwcash/librenms/pull/2

**Comment by SaaldjorMike** [comment]
@fjwcash: Looks like you created the pull request on your own repo, but you need to create the request here. Try going to: https://github.com/librenms/librenms and click on the green compare&pull-request thing

**Comment by fjwcash** [comment]
Aha!

I believe I've created the pull requests correctly now.

Thanks.

**Comment by SaaldjorMike** [comment]
@fjwcash: Yup! Thanks for helping out!

**Comment by laf** [comment]
Brilliant, all merged in :)
