### ISSUE TITLE
New OS Albentia WIMAX

### ISSUE THREAD

**Issue by conecta3** [librenms/librenms#10993]
https://p.libren.ms/view/7975b709  (Discovery)
https://p.libren.ms/view/fe478827 (Poller)
https://p.libren.ms/view/7be17dbc (SNMP)

**PLEASE READ FIRST**

**Please do not post bugs or ask questions or feature requests here**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org/c/help).**

To create a new device request please use this link: https://github.com/librenms/librenms/issues/new?template=New-Device.md

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11599

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-os-albentia-wimax/11599/1
