### ISSUE TITLE
Graph of total poll time

### ISSUE THREAD

**Issue by SaaldjorMike** [librenms/librenms#1099]
On the page /pollers/tab=pollers/ I see the field "Total Poll Time". It would be nice to have a graph of the polling time. This would be very helpful when trying to tweak the configuration and see if the poll time is getting any better or worse. I realise that you could wait 5-10 minutes and see whatever value it puts in next time it finishes, but a graph would be a lot better when trying to see over time if changes actually are better over time.

**Comment by Lonecrowe** [comment]
I second this.

**Comment by khobbits** [comment]
Yep, having a graph of the 'per poller' 'total poll time', would be quite useful.
A single graph with a dataset for each poller, so you could see if a poller was misbehaving sounds amazing.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
