### ISSUE TITLE
Add Temperature Sensor for EdgeCore ECS4120

### ISSUE THREAD

**Issue by LFustinoni** [librenms/librenms#10998]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Please keep in mind that LibreNMS is a community project, it is run by people like you using their free time.
Which means it may take time before support is added to LibreNMS.

We encourage you to do it yourself and submit it in GitHub as a Pull request. It is not so difficult, most of
it can be done without writing a single line of code. You can find the documentation below :
👉  https://docs.librenms.org/Developing/os/Initial-Detection/

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

[poller.txt](https://github.com/librenms/librenms/files/4019841/poller.txt)
[snmpwalk.txt](https://github.com/librenms/librenms/files/4019842/snmpwalk.txt)
[discovery.txt](https://github.com/librenms/librenms/files/4019843/discovery.txt)

[ECS4120-MIB.txt](https://github.com/librenms/librenms/files/4019844/ECS4120-MIB.txt)

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11598

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/add-temperature-sensor-for-edgecore-ecs4120/11598/1
