### ISSUE TITLE
Sorting by Up/Down Time

### ISSUE THREAD

**Issue by ewysong** [librenms/librenms#10996]
When sorting devices by Up/Down Time devices are mostly sorted correctly, but there are some that are not. Here are a couple examples:
![example1](https://user-images.githubusercontent.com/17579891/71731802-a4a8be80-2e13-11ea-8783-c10dc7d07138.png)

![example2](https://user-images.githubusercontent.com/17579891/71732281-da01dc00-2e14-11ea-80b9-910ed46202d0.png)

This happens in FireFox and Chrome.

**Comment by kkrumm1** [comment]
Im not seeing this 

can you run ./validate.php and post the output.

**Comment by ewysong** [comment]
```
bash-4.2$ ./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 1.59-6-g4246316
DB Schema | 2019_12_01_165514_add_indexes_to_mpls_lsp_paths_table (152)
PHP       | 7.2.24
MySQL     | 5.5.64-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Composer Version: 1.9.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

**Comment by josephtingiris** [comment]
FWIW, I see the problem sorting by up/down time too.   

1) Disabled devices are always a problem.  They never have an uptime value, but still get mixed in with both up and down devices.
2) When there are no down devices or disabled devices then sort seems to work OK.

I've checked a couple different installations and they're doing the same thing.  Both validate.  One is php 7.2.11 and the other php 7.3.3

I was thinking it might have something to do with this ...

https://bugs.php.net/bug.php?id=77007

@kkrumm1 what version of php are you using?

**Comment by aTanCS** [comment]
I can confirm, sorting of Down devices does not work as expected.  I use latest LibreNMS and PHP 7.4. This issue was already mentioned on a forum:
https://community.librenms.org/t/up-down-time-column-sort-for-device-that-are-down/9729

> On the devices page, when a device is currently down the Up/Down Time column shows the Downtime in place of the Uptime, but when sorting this column those device will be sorted based on the last known Uptime before the current Downtime (which is not displayed, not very relevant when a device is down.)

**Comment by murrant** [comment]
Try sorting by the very left column of the table ;-)

**Comment by aTanCS** [comment]
> Try sorting by the very left column of the table ;-)

I'm not sure how it could solve the issue (but I tried it). I need to sort Down devices by down time duration. The very left column just sorts devices by state (up/down). I have Up devices filtered out. Only Down are visible and it can't be sorted by down time using up/down column.

**Comment by SourceDoctor** [comment]
what about as temporarly workaround:
only show uptime in uptime/downtime column if device is up
and nothing if device is down?

**Comment by murrant** [comment]
If you want to sort by up/down time, you need to build a complex sql query to calculate both up and downtime in one field.  Downtime should be negative so it is sorted properly.
