### ISSUE TITLE
dot1dTpFdbPort and vlans 1002 --> 1005

### ISSUE THREAD

**Issue by nistorj** [librenms/librenms#11004]
Hello everyone,

I read through some older pull req's (10510/Reduce discovery snmp load of Cisco VTP vlans module) and (10519/Tests for IOS Vlans/Vtp) to see if those would lead me to some answers but I don't think it has.

In our environment we log all failed authentication requests towards our systems.  Since we generally block all SNMP req's the failed auth's always come from bad scripts, outdated read communities or other.  In this case I'm looking at the other part.

What we are noticing is that running: `/opt/librenms/discovery.php -d -v -m fdb-table -h <host>` yields auth errors when trying to pull community@VLANID, and that vlan being between 1002 and 1005.

When the query runs the output example is as follows:
```
SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'SNMP_RO_COMM@1' '-OQUsetX' '-m' 'BRIDGE-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' '-t' '10' '-r' '3' 'udp:400-tz01-tor2:161' 'dot1dBasePortIfIndex']
dot1dBasePortIfIndex[1] = 8
dot1dBasePortIfIndex[2] = 9
dot1dBasePortIfIndex[3] = 10
dot1dBasePortIfIndex[4] = 11
dot1dBasePortIfIndex[5] = 12
......

SQL[SELECT * FROM `ports` WHERE `device_id` = ? AND `ifIndex` = ? [51,"8"] 1.09ms]

SQL[SELECT * FROM `ports` WHERE `device_id` = ? AND `ifIndex` = ? [51,"9"] 0.86ms]

SQL[SELECT * FROM `ports` WHERE `device_id` = ? AND `ifIndex` = ? [51,"10"] 0.45ms]

.....
vlan 1248 mac 000efe011e4d port (1) 33246
vlan 1248 mac a8b45662dba7 port (3) 33248
vlan 1248 mac a8b456ebfeeb port (4) 33249
vlan 1248 mac f80f6f1ee433 port (2) 33247
1002 SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'SNMP_RO_COMM@1002' '-OQUsetX' '-m' 'BRIDGE-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' '-t' '10' '-r' '3' 'udp:400-tz01-tor2:161' 'dot1dTpFdbPort']
.....

We only find the timeouts happen on vlans 1002->1005 and cause auth error (snmp traps) to be produced.

Has anyone else run into this issue? I was thinking of providing a patch to resolve this as it's a simple one line fix in includes/discovery/fdb-table/ios.inc.php line 21, vlan_raw just needs to check that its not between 1002 and 1005.

Thoughts?

**Comment by PipoCanaja** [comment]
Hi,
Are we sure that no IOS device (routers, etc) can use these 4 VLANs at any time ? if yes, then go ahead for the patch! If no, we would need to find a list of device that should not be modified ...

**Comment by nistorj** [comment]
I will double check into that however even on all modern equipment, Cat 9300, ISR4k+IOSXE 16.12/17 they all read as active/unsupported and their state cannot be changed in the running config.

Will get back to this thread shortly with more info.

**Comment by nistorj** [comment]
I have a ticket open with Cisco about the behaviour of these vlans and SNMP queries, but here is their first response in reference to the vlans:

```
“VLANs are identified by a number from 1 to 4094. VLAN 1 is the default VLAN and is created during system initialization. VLAN IDs 1002 through 1005 are reserved for Token Ring and FDDI VLANs. All of the VLANs except 1002 to 1005 are available for user configuration.”
 ```

Given the documentation referencing that it's safe to assume that 1002 through 1005 should not have any data in them and thus be safe to ignore.  I think the issue of it timing out and causing auth errors is another issue that cisco could probably resolve in their own code.

I just tested on a Nexus 9k device as well and it also throws trap errors although I don't show those vlans in the active vlan database.  It actually errors and throws auth traps on any vlan that you try to query which is not an active vlan on the system.  Since it appears on the Nexus it doesn't show up on a general query of `vtpVlanEntry` this likely wouldn't be an issue on NXOS just IOS/XE.

thoughts?

**Comment by nistorj** [comment]
Another update -- when you run `show snmp context` on the catalyst switch it will give you the available contexts to query:

eg:
```
400-CS01-TOR2#show snmp context
vlan-1
vlan-10
vlan-21
vlan-22
vlan-30
vlan-32
vlan-33
....
```

Question now becomes how to best query what contexts are available instead of blinding assuming all are based on data within vtp/dot1dTpFdbPort.

**Comment by nistorj** [comment]
Cisco uses community based name indexing for SNMP v1 and v2c to allow getting that vlan specific information from the BRIDGE-MIB, however in SNMP v3 there's a variation of this specific to v3 contexts or else it won't show by the sounds of it.

`show snmp context` to get a list of SNMP contexts, we're interested in vlan-
config needed to be added for SNMPv3 users:
```
conf t
snmp-server group v3GroupName v3 auth context vlan- match prefix
(don't forget the dash after the word vlan)
```

If your switch doesn't support the config word 'prefix' then you need to add each vlan manually:
```
conf t
snmp-server group v3GroupName v3 priv context vlan-1
snmp-server group v3GroupName v3 priv context vlan-2
snmp-server group v3GroupName v3 priv context vlan-3
... etc
```

I found that you could potentially use the CISCO-CONTEXT-MAPPING-MIB to figure out which contexts exist on the switch prior to the query however this does not seem to be supported on IOS-XE devices today, although it is supported on NXOS devices.


Based on all the information today I think it's safe to ignore vlans 1002-1005 on the query to help speed up discovery.
