### ISSUE TITLE
Ericsson IPOS-16.3.1.3.13

### ISSUE THREAD

**Issue by IMRAGAA** [librenms/librenms#11008]
Hi ,
I have Ericsson Routers SSR that are discovered as a Generic device which is with OS ver “Ericsson IPOS Version IPOS-16.3.1.3.13-Release” .
Although the Ericsson SE routers with OS “SEOS-12.1.1.11p7-Release” are discovered and add to managed devices normally .

what is wrong with this devices ?

Regards

**Comment by kkrumm1** [comment]
We need this info asked for 

**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Please keep in mind that LibreNMS is a community project, it is run by people like you using their free time.
Which means it may take time before support is added to LibreNMS.

We encourage you to do it yourself and submit it in GitHub as a Pull request. It is not so difficult, most of
it can be done without writing a single line of code. You can find the documentation below :
👉  https://docs.librenms.org/Developing/os/Initial-Detection/

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by kkrumm1** [comment]
Closing for now. Once all the info is provided we can re open it
