### ISSUE TITLE
New Device: SonicWall SMA

### ISSUE THREAD

**Issue by sshowers** [librenms/librenms#11046]
SonicWall SMA (Secure Mobile Access) detected as Generic x86 64-bit Linux 4.4.111 device

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery: https://p.libren.ms/view/444f6687
Poller: https://p.libren.ms/view/b46f6f02
snmpbulkwalk: https://p.libren.ms/view/b4e3c060
![SonicWall-logo](https://user-images.githubusercontent.com/43894357/72644898-d2bfef80-3937-11ea-8fa2-4d57ed8119f1.png)
![SonicWall-icon](https://user-images.githubusercontent.com/43894357/72644906-d784a380-3937-11ea-9b0a-26816db5444c.png)
[sonicwallCustomSMAMibs.zip](https://github.com/librenms/librenms/files/4078998/sonicwallCustomSMAMibs.zip)

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-sonicwall-sma/11596/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11596
