### ISSUE TITLE
New Device: Talari Networks APN Appliance

### ISSUE THREAD

**Issue by sshowers** [librenms/librenms#11045]
Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery: https://p.libren.ms/view/df4dd04f
Poller: https://p.libren.ms/view/fbdccf3d
snmpbulkwalk: https://p.libren.ms/view/27053d72
snmpwalk: https://p.libren.ms/view/4f61fb88
![talari_logo](https://user-images.githubusercontent.com/43894357/72642220-79ed5880-3931-11ea-8f77-cbd8481c054a.png)
![talari_icon](https://user-images.githubusercontent.com/43894357/72643020-5b885c80-3933-11ea-9573-1d338289784e.png)

[TALARI-MIB.txt](https://github.com/librenms/librenms/files/4078725/TALARI-MIB.txt)

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-talari-networks-apn-appliance/11597/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11597
