### ISSUE TITLE
UPS nut (app) add ups.state

### ISSUE THREAD

**Issue by mpikzink** [librenms/librenms#11060]
Please add the ups.satus to the UPS_nut app

ups.satus=OL (Online - OK State)
ups.status: OL CHRG (Charching - Warning)
ups.satus=OB (On Battery - Warning) 
ups.status: OB LB (On Low Battery - Crititcal) 

"OL means your system is running on line power. If it says something else (like OB - on battery, or LB - low battery), your driverwas probably misconfigured during the Driver configuration step..." REF https://networkupstools.org/docs/user-manual.pdf

This is useful for UPS which have no input current/voltage sensor such as APC1500

By the way, the ups.serial would be also interresting for the inventory.

THX

**Comment by kkrumm1** [comment]
We need more info that is asked for in here 
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Please keep in mind that LibreNMS is a community project, it is run by people like you using their free time.
Which means it may take time before support is added to LibreNMS.

We encourage you to do it yourself and submit it in GitHub as a Pull request. It is not so difficult, most of
it can be done without writing a single line of code. You can find the documentation below :
👉  https://docs.librenms.org/Developing/os/Initial-Detection/

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations
