### ISSUE TITLE
Cannot login librenms for first time intallation

### ISSUE THREAD

**Issue by sirjana** [librenms/librenms#11094]
I have just installed the librenms and after typing username and password it send a error:
I have used same password of database user and password. Is there a default password??

 Error connecting to database. 
 SQLSTATE[HY000] [1045] Access denied for user 'librenms'@'localhost' (using password: YES) 

When running ./validate.php it send following error.
 Could not connect to database, check logs/librenms.log.

And from librenms log
production.ERROR: PDOException: SQLSTATE[HY000] [1045] Access denied for user 'librenms'@'localhost' (using password: YES) in /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000] [1045] Access denied for user 'librenms'@'localhost' (using password: YES) in /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47

Please suggest me.

**Comment by kkrumm1** [comment]
This only for bugs and new device requests pulse the forums and discord.
