### ISSUE TITLE
VLAN ID are missing for HP/Aruba procurve switches in FDB table

### ISSUE THREAD

**Issue by sajiby3k** [librenms/librenms#11121]
Hi,

The issue is Librenms cannot associate vlan with fdb tables for HP/Aruba procurve switches.

It can only associate vlan 1 with fdb table.

But all the vlans apart from vlan 1 is never associate in fdb table.

The link where I have reported this issue is -

https://community.librenms.org/t/vlan-id-missing-in-fdb-tables-for-hp-provurve-or-aruba-switches/10889

I am attaching the log for - 

discovery - https://p.libren.ms/view/d4da7305
poller - https://p.libren.ms/view/f124be88
[snmpbulkwalk.txt](https://github.com/librenms/librenms/files/4183297/snmpbulkwalk.txt)

Please any developer can look at this. Let me know if more logs are needed from my side.

Regards,

Shariful Hoque

**Comment by PipoCanaja** [comment]
@sajiby3k Please just add the snmpwalk file to the github issue (you can drag-drop on it) instead of using a 3rd party file sharing service that will break in a few days/week.

**Comment by joseUPV** [comment]
I have hp proliant and aruba switches.
discovery.php -> https://p.libren.ms/view/e5fa6079

Discovery doesn't translate snmp vlan index to vlan number in fdb module.
#### Load disco module vlans ####
VLAN 1
...
VLAN 179
...  
VLAN 999
...
#### Load disco module fdb-table ####
dot1qTpFdbPort[1][0:0:5e:0:1:1] = 28
dot1qTpFdbPort[1][0:0:87:d5:ff:c3] = 28
....
dot1qTpFdbPort[2][0:c:29:5c:14:3d] = 28
dot1qTpFdbPort[2][0:10:74:b5:21:c2] = 28
....
dot1qTpFdbPort[3][0:12:cf:c4:9e:40] = 28
dot1qTpFdbPort[3][0:15:9b:20:a4:1] = 28
....

**Comment by sajiby3k** [comment]
@PipoCanaja Sorry for the inconvenience.  Now the snmpwalk is uploaded.

**Comment by joseUPV** [comment]
Works on Aos6 devices getting fdb data form other mib and preparing for this script. #11145

**Comment by joseUPV** [comment]
Test data form PR#11132
It's a procurve 2520 POE switch.
test/snmpsim/procurve.snmprec: https://p.libren.ms/view/8be5c060
test/data/procurve.json: https://p.libren.ms/view/9c30bccf

**Comment by joseUPV** [comment]
./discovery.php -h 4 | ./pbin.sh =>https://p.libren.ms/view/fde847c8
./scripts/collect-snmp-data.php -h 4 | ./pbin.sh => https://p.libren.ms/view/6a8e610a
./scripts/save-test-data.php -o procurve | ./pbin.sh => https://p.libren.ms/view/02ef5256
What I'm doing bad?

**Comment by cjwbath** [comment]
I think we maybe need an -m fdb-table argument to each of those but I'm not really sure myself how we're supposed to then commit these as tests.

**Comment by joseUPV** [comment]
Was a permission problem, i didn't do chmod scripts after git clone.
Files were librenms original test files
This are the correct ones:
/tests/data/procurve.json | ./pbin.sh => https://p.libren.ms/view/b4b0b3ae
/tests/snmpsim/procurve.snmprec | ./pbin.sh => https://p.libren.ms/view/a906131d

**Comment by joseUPV** [comment]
And with -m fdb-table
procurve.json => https://p.libren.ms/view/4654362e
procurve.snmprec => https://p.libren.ms/view/35b20001

**Comment by PipoCanaja** [comment]
Hi @sajiby3k 
Can you confirm this case is now closed with the new code merged in #11145 ?
