### ISSUE TITLE
Fortigate firewall (not working) - Added support for routing table collection in discovery #10182

### ISSUE THREAD

**Issue by sajiby3k** [librenms/librenms#11142]
Routing table detection not working for fortigate firewalls (pull request 10182).

I am attaching all the necessary files. I can see from discovery output that routing table is detected, but nothing comes into database.

[discovery.txt](https://github.com/librenms/librenms/files/4198851/discovery.txt)
[discovery-only-route-module.txt](https://github.com/librenms/librenms/files/4198852/discovery-only-route-module.txt)
[poller.txt](https://github.com/librenms/librenms/files/4198854/poller.txt)
[snmpbulkwalk.txt](https://github.com/librenms/librenms/files/4198855/snmpbulkwalk.txt)

Anyone can look at this?

Regards

**Comment by PipoCanaja** [comment]
Hi @sajiby3k 
Patch is submitted in github. Feel free to test it. 

https://github.com/librenms/librenms/pull/11144
