### ISSUE TITLE
New device : Forcepoint NGFW Engine

### ISSUE THREAD

**Issue by ilymare** [librenms/librenms#11163]
![forcepoint](https://user-images.githubusercontent.com/14330952/74725949-ee702b80-523e-11ea-9463-1b308dc7eb71.png)
Discovery : [forcepoint_discovery.txt](https://github.com/librenms/librenms/files/4218548/forcepoint_discovery.txt)
Poller : [forcepoint_poller.txt](https://github.com/librenms/librenms/files/4218549/forcepoint_poller.txt)
SNMPBulk : [forcepoint_snmpbulk.txt](https://github.com/librenms/librenms/files/4218550/forcepoint_snmpbulk.txt)
MIB : [STONESOFT-FIREWALL-MIB.txt](https://github.com/librenms/librenms/files/4218572/STONESOFT-FIREWALL-MIB.txt)

**Comment by ilymare** [comment]
MIB : [STONESOFT-FIREWALL-MIB.txt](https://github.com/librenms/librenms/files/4218572/STONESOFT-FIREWALL-MIB.txt)

**Comment by ilymare** [comment]
Hi, 

I don't know if i have to create an issue or a PR in order to have some support to add the OS for forcepoint device. Tell me if i have to do it with an other method.

Regards,

Ilymare

**Comment by kkrumm1** [comment]
You can do an issue but it could take a while because users voluntarily work on adding new device requests. Or you can do it your self and submit the PR and we can help you along the way.

**Comment by ilymare** [comment]
> 
> 
> You can do an issue but it could take a while because users voluntarily work on adding new device requests. Or you can do it your self and submit the PR and we can help you along the way.

@kkrumm1 I tried it, requested some help since October on the community website, discord and twitter but no response ... I really struggling with the memory discovery and polling ...

https://community.librenms.org/t/mempool-for-new-os-not-working/9922/2

**Comment by kkrumm1** [comment]
Again this all voluntarily based so no guarantee someone will be able to help you. You should submit what you have so far as a PR

**Comment by ilymare** [comment]
@kkrumm1  I know and I'm trying to develop the plugin in order to post it but i thing the global documentation is lacking of some info in order to succeed. 

For example I'm struggling with the mempool module but there is no indication of the structure of the discover_mempool() function for example.

The result is that i have a code error 400 : " invalid field format", but there is no mention of the format to use in the documentation.

I'm just trying to have some feedback for someone who already added a new device to have an other point of view.

**Comment by ilymare** [comment]
OK i find the issue. 

The name of the ".inc.php" of the module have to be exactly the same that the OS name of the device.

If the name is diffrent, it’s working for the discovery module but not for the polling module.

I'm trying to finish all the modules that i can in order to publish it.

Regards,

Ilymare
