### ISSUE TITLE
Adding hosts silently fails when MySQL sql_mode='STRICT_ALL_TABLES'

### ISSUE THREAD

**Issue by ernstae** [librenms/librenms#1116]
Perhaps not a bug in its truest sense, but it just took me a few hours to figure out that this has caused the addhost.php to fail silently (as well as the GUI "add device" equivalent).

The silent failures were frustrating, but I've isolated the cause to to the following setting in our MySQL environment (version 5.6)

set global sql_mode='STRICT_ALL_TABLES';

(see https://dev.mysql.com/doc/refman/5.6/en/sql-mode.html#sqlmode_strict_all_tables)

Disabling this mode, allows for the addhost.php script to work as expected.

This could be fixed with your SQL queries, and if I can find some time to take a look at the code, I will, but wanted to open this just so it was documented (as a first-time user of the software, if I had come across a report like this, I might not have spent so long trying to figure it out).

**Comment by laf** [comment]
Hi @ernstae, thanks for the report.

We should be adding this to the docs actually to make sure people do disable strict mode. We've made some headway a while ago in ensuring the code works when it's enabled but it's obviously not 100% complete (https://github.com/librenms/librenms/pull/521)

We'll get this sorted - sorry you had to spend time debugging it in the first place :(
