### ISSUE TITLE
Some BGP sessions on Huawei no longer visible after 95820bf

### ISSUE THREAD

**Issue by ianh14721** [librenms/librenms#11211]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Please keep in mind that LibreNMS is a community project, it is run by people like you using their free time.
Which means it may take time before support is added to LibreNMS.

We encourage you to do it yourself and submit it in GitHub as a Pull request. It is not so difficult, most of
it can be done without writing a single line of code. You can find the documentation below :
👉  https://docs.librenms.org/Developing/os/Initial-Detection/

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Hi folks,

Having an issue since 95820bf with IPv6 BGP session polling on Huawei VRP (hardware NE05E-SQ, software V300R003C10SPC500+V300R003SPH028 and V300R002C10SPC200). Discovery picks up v6 BGP sessions just fine, but polling never finds them.

```
$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.60-81-gcf023b936
DB Schema | 2020_02_10_223323_create_alert_location_map_table (159)
PHP       | 7.3.11-1+0~20191026.48+debian9~1.gbpf71ca0
MySQL     | 10.1.41-MariaDB-0+deb9u1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.9.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[FAIL]  Discovery has not completed in the last 24 hours.
	[FIX]: 
	Check the cron job to make sure it is running and using discovery-wrapper.py
[WARN]  Your local git contains modified files, this could prevent automatic updates.
	[FIX]: 
	You can fix this with ./scripts/github-remove
	Modified Files:
	 rrd/.gitignore
$ 
```
(Discovery has definitely run in the previous 24 hours, not sure why that check fails).

From the poller debugger:

```
Checking BGP peer xxxx:xxxx::1 Fetching BGP4-MIB data... 
SNMP['/usr/bin/snmpget' '-v3' '-l' 'authPriv' '-n' "" '-a' 'SHA' '-A' 'PASSWORD' '-u' 'USER' '-x' 'AES' '-X' 'PASSWORD' '-OQUs' '-m' 'BGP4-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/huawei' 'udp:HOSTNAME:161' 'bgpPeerState.xxxx:xxxx::1' 'bgpPeerAdminStatus.xxxx:xxxx::1' 'bgpPeerInUpdates.xxxx:xxxx::1' 'bgpPeerOutUpdates.xxxx:xxxx::1' 'bgpPeerInTotalMessages.xxxx:xxxx::1' 'bgpPeerOutTotalMessages.xxxx:xxxx::1' 'bgpPeerFsmEstablishedTime.xxxx:xxxx::1' 'bgpPeerInUpdateElapsedTime.xxxx:xxxx::1' 'bgpPeerLocalAddr.xxxx:xxxx::1']

Checking BGP peer x.x.x.1 Fetching BGP4-MIB data... 
SNMP['/usr/bin/snmpget' '-v3' '-l' 'authPriv' '-n' "" '-a' 'SHA' '-A' 'PASSWORD' '-u' 'USER' '-x' 'AES' '-X' 'PASSWORD' '-OQUs' '-m' 'BGP4-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/huawei' 'udp:HOSTNAME:161' 'bgpPeerState.x.x.x.1' 'bgpPeerAdminStatus.x.x.x.1' 'bgpPeerInUpdates.x.x.x.1' 'bgpPeerOutUpdates.x.x.x.1' 'bgpPeerInTotalMessages.x.x.x.1' 'bgpPeerOutTotalMessages.x.x.x.1' 'bgpPeerFsmEstablishedTime.x.x.x.1' 'bgpPeerInUpdateElapsedTime.x.x.x.1' 'bgpPeerLocalAddr.x.x.x.1']
```
In an snmpwalk the v6 sessions don’t show up:

```
$ /usr/bin/snmpwalk -v3 -l authPriv -aSHA -A x -u x -xAES -X x -OQUs -mBGP4-MIB -M/opt/librenms/mibs:/opt/librenms/mibs/huawei router01 bgpPeerState
bgpPeerState.x.x.x.205 = established
bgpPeerState.x.x.x.1 = established
bgpPeerState.x.x.x.2 = established
bgpPeerState.x.x.x.3 = established
bgpPeerState.x.x.x.4 = established
bgpPeerState.x.x.x.6 = established
bgpPeerState.x.x.x.10 = established
bgpPeerState.x.x.x.100 = established
bgpPeerState.x.x.x.60 = established
bgpPeerState.x.x.x.68 = established
bgpPeerState.x.x.x.146 = established
$ 
```
I’d totally believe v6 sessions just not being exposed via SNMP with the new MIB. Is this a bug, or something I’m missing?

Thanks,

I.

**Comment by manjunath1110** [comment]
I am facing the same issue, it does not detect v6 bgp peers

**Comment by PipoCanaja** [comment]
Hi
Please open an issue with this, and provide all the data required. I'll have a look. 
Thanx

**Comment by murrant** [comment]
We had a merge break some Huawei MIBs, please run ./daily.sh and test again.

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/bgp-peers-disappeared/11134/2

**Comment by PipoCanaja** [comment]
@ianh14721 @manjunath1110 
Please provide the details so we can look at the issue, most importantly this :
`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME . ` 
Thanx

**Comment by ianh14721** [comment]
> Please provide the details so we can look at the issue, most importantly this :

Collected, can I send you the URLs privately?

Thanks again,

**Comment by PipoCanaja** [comment]
> > Please provide the details so we can look at the issue, most importantly this : 

> Collected, can I send you the URLs privately?
> Thanks again,

Yep, you can. Find me on https://community.librenms.org/ 
Bye

**Comment by PipoCanaja** [comment]
@ianh14721 
Issue should be solved now. Please test and confirm it is all good so we can close this.

**Comment by ianh14721** [comment]
Confirmed working, thank you!
