### ISSUE TITLE
Huwaei switch cpu and memory other sensors not dectected in latest update

### ISSUE THREAD

**Issue by manjunath1110** [librenms/librenms#11213]
After the latest update librenms is not detecting sensors like cpu memory transreciver etc on huawei S5720-32X-EI-AC
It is working for switches added on jan 2020, after the latest update when we add new switch its not getting discovered.

root@librenms:/opt/librenms# ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.60-89-ge8f252de9
DB Schema | 2020_02_10_223323_create_alert_location_map_table (159)
PHP       | 7.2.24-0ubuntu0.18.04.3
MySQL     | 10.1.44-MariaDB-0ubuntu0.18.04.1
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.9.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct

**Comment by PipoCanaja** [comment]
Hi,
In the process to be corrected.
