### ISSUE TITLE
Huawei sfp transceiver TX/RX power not working after latest update

### ISSUE THREAD

**Issue by manjunath1110** [librenms/librenms#11220]
After Latest librenms update, sfp transceiver TX/RX power is not getting detected or getting graphed. it was working last month, Please check

root@librenms:/opt/librenms# ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.60-92-g7254f13b2
DB Schema | 2020_02_10_223323_create_alert_location_map_table (159)
PHP       | 7.2.24-0ubuntu0.18.04.3
MySQL     | 10.1.44-MariaDB-0ubuntu0.18.04.1
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.9.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct

**Comment by kkrumm1** [comment]
i think this was resolved with a recent update. please try updating.
