### ISSUE TITLE
New Device : - Climate Monitor CM-2

### ISSUE THREAD

**Issue by AreaA41** [librenms/librenms#11221]
Another variant. 

System Name
climate monitor cm-2
Operating System
ITWatchDogs Goose
Object ID
.1.3.6.1.4.1.17373.3

discovery https://p.libren.ms/view/a6085e68
poller https://p.libren.ms/view/9293e838
snmp https://p.libren.ms/view/02db1b8e

**Comment by AreaA41** [comment]
Device is detected  as wxgoose but dosen't generate graphs for enviroment. 
(had a play withe the yaml files,  and generated a inc.php but couldn't get it working. )

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-climate-monitor-cm-2/11595/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11595
