### ISSUE TITLE
Junos ISIS support

### ISSUE THREAD

**Issue by ognjen011** [librenms/librenms#11224]
Are there any plans to add under routing options support to view status of ISIS protocol data for Junos devices. 

I am looking to see an alert that shows when ISIS adjacency goes down or comes back up.  In terms of this being available via SNMP i am not too sure. 

Example when a ISIS adjacency goes down
RPD_ISIS_ADJDOWN: IS-IS lost L2 adjacency to Host1 on xe-0/2/2, reason: BFD Session Down

when it comes back up 
RPD_ISIS_ADJUP: IS-IS new L2 adjacency to Host1 on xe-0/2/2

the above are examples that router logs as SNMP trap.

**Comment by kkrumm1** [comment]
please use discord or community forums for this. thank you
