### ISSUE TITLE
All Aruba models are showing We couldn't retrieve the device information from Oxidized

### ISSUE THREAD

**Issue by SlyK7** [librenms/librenms#11233]
2020-03-02 13:12:01 - NoMethodError - undefined method `output' for nil:NilClass:
        /usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:176:in `block in yield_node_output'
        /usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:130:in `synchronize'
        /usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:130:in `with_lock'
        /usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:174:in `yield_node_output'
        /usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:62:in `fetch'
        /usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-web-0.13.1/lib/oxidized/web/webapp.rb:82:in `block in <class:WebApp>'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/nulllogger.rb:9:in `call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/head.rb:13:in `call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
        /usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/urlmap.rb:66:in `block in call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/urlmap.rb:50:in `each'
        /usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/urlmap.rb:50:in `call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/builder.rb:153:in `call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
        /usr/local/rvm/gems/ruby-2.3.8/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
        /usr/local/rvm/gems/ruby-2.3.8/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
        /usr/local/rvm/gems/ruby-2.3.8/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
        /usr/local/rvm/gems/ruby-2.3.8/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by SlyK7** [comment]
All the Aruba Devices not showing up in oxidized, and not config

**Comment by kkrumm1** [comment]
Please us the forums for this https://community.librenms.org/c/help/oxidized/10
