### ISSUE TITLE
New Device: Schneider Electric Uniflair LE

### ISSUE THREAD

**Issue by michael-schneider-mk** [librenms/librenms#11234]
Schneider Electric Uniflair LE Room Air Conditioner (formerly APC Uniflair)

- [ x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/5f80b433
https://p.libren.ms/view/71f42b49
https://p.libren.ms/view/9d52815c
- [x ] Please provide as much detail as possible.
https://download.schneider-electric.com/files?p_enDocType=User+guide&p_File_Name=ERIN-B75N5P_R0_EN.pdf&p_Doc_Ref=SPD_ERIN-B75N5P_EN
Unit is identified as APC Management Module AOS v6.1.8 / App v6.2.0 . Recognized as UPS/Power device, should be Environmental.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11594

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-schneider-electric-uniflair-le/11594/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11594
