### ISSUE TITLE
config.php.default refers to includes/defaults.inc.php

### ISSUE THREAD

**Issue by dlangille** [librenms/librenms#11242]
With recent changes, `includes/defaults.inc.php`was removed.

https://github.com/librenms/librenms/blob/master/config.php.default#L3 contains:

```
## Have a look in includes/defaults.inc.php for examples of settings you can set here. DO NOT EDIT defaults.inc.php!
```

I would have supplied a patch, but I don't know what this should refer to now. I'm happy to patch the file and submit a merge request if someone lets me know.  Thank you.

**Comment by dlangille** [comment]
See also:

* https://github.com/librenms/librenms/blob/master/doc/Developing/os/Initial-Detection.md (multiple instances)
* tests/config/config.test.php

**Comment by PipoCanaja** [comment]
@dlangille You can directly edit the files from the documentation using the little pen on the top right:
https://docs.librenms.org/Developing/os/Initial-Detection/

**Comment by dlangille** [comment]
@PipoCanaja Thanks.

The current is: I do not know what the corrected text should be.

**Comment by dlangille** [comment]
misc/config_definitions.json has been suggested
