### ISSUE TITLE
Please add support to Add a new device using MIB.

### ISSUE THREAD

**Issue by pavithranv** [librenms/librenms#11268]
Dear team,

We have multiple GPON OLTs which are non-branded (Chinese). We have the MIBs of those devices. How can we add them to LibreNMS. We have Connection Technology (CTS, Taiwan made, which is not populated). Please suggest a solution.

**Comment by kkrumm1** [comment]
Please follow the guidelines that you deleted.

**Comment by pavithranv** [comment]
> Please follow the guidelines that you deleted.

I didn't get you. Can you please let me know how to add a device using MIBs.

**Comment by kkrumm1** [comment]
First adding mib by its self will do nothing. 

Please put docs for adding support to a device or 

**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Please keep in mind that LibreNMS is a community project, it is run by people like you using their free time.
Which means it may take time before support is added to LibreNMS.

We encourage you to do it yourself and submit it in GitHub as a Pull request. It is not so difficult, most of
it can be done without writing a single line of code. You can find the documentation below :
👉  https://docs.librenms.org/Developing/os/Initial-Detection/

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations
