### ISSUE TITLE
New sensors: Eaton gigabit network card and Environment sensor 2

### ISSUE THREAD

**Issue by 917huB** [librenms/librenms#11289]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Im upgraded an old Eaton UPS that with a new [gigabit network card](https://www.eaton.com/us/en-us/catalog/backup-power-ups-surge-it-power-distribution/eaton-gigabit-network-card---na.html) that makes use of a new [EMPDT1H1C2 environment monitor](https://www.eaton.com/us/en-us/catalog/backup-power-ups-surge-it-power-distribution/eaton-environmental-monitoring-probe-gen-2.html)

The sensors for temperature, humidity and contact sensor states are not displayed in LibreNMS. This was working fine with the older network card and environment sensor. 

[./discovery.php -h ups-9px -d | ./pbin.sh](https://p.libren.ms/view/6748344d)

[./poller.php -h ups-9px -r -f -d | ./pbin.sh](https://p.libren.ms/view/903fe284)

[snmpwalk -OUneb -v2c -c public ups-9px .  | ./pbin.sh](https://p.libren.ms/view/8a290c7b)

EDIT: I noticed theres additional data relating to the environment card when I run this through e web interface so have stored the web page output [on pastebin here](https://pastebin.com/u9TFBGdJ).

[link to MIB data, included in this zip under EATON-EMP-MIB](https://www.eaton.com/content/dam/eaton/products/backup-power-ups-surge-it-power-distribution/Firmware/connectivity/eaton-network-connectivity-mib-files.zip)

thank you for considering adding these new sensors.

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11675

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-sensors-eaton-gigabit-network-card-and-environment-sensor-2/11675/1
