### ISSUE TITLE
Interfaces sometimes will report larger amounts of traffic than they are capable of

### ISSUE THREAD

**Issue by laf** [librenms/librenms#1128]
Need to put a safety net in to limit this.

**Comment by paulgear** [comment]
:+1: - Fixing the problem at the source rather than using the remove spikes method makes good sense to me.

**Comment by f0o** [comment]
This bug also applies for Billing

**Comment by joubertredrat** [comment]
Hi guys,

I reported this with @laf on irc channel, but I don't remember if I open issue, probably not.
This issue It occurred in my environment also.

**Comment by Kr1stian** [comment]
Hi guys, 

We noticed  same issue with our librenms installation and  linked it with network problems. 
e.g  we tested it by disabling network interface on our librenms machine and after we enabled it and pooled new data, bandwidth statistics for that day went skyrocketing.  Here is one example 
![libre](https://cloud.githubusercontent.com/assets/12649004/7869099/e10d9afa-0580-11e5-9630-289d9c474b67.PNG)

Each of this spikes was caused by the network inaccessibility on the librenms host.  The last spike was caused by deliberate disabling of network interface just to see if this is the problem. 

Kristian

**Comment by joubertredrat** [comment]
Hi,

Interesting @Kr1stian, on mine case was same problem, but I didn't have time to see the problem.

![libre_bill1](https://cloud.githubusercontent.com/assets/1520407/7869392/d33135ea-0558-11e5-89ba-fe714d07e916.jpg)
![libre_bill2](https://cloud.githubusercontent.com/assets/1520407/7869391/d32fcc3c-0558-11e5-94c2-b51809da61b7.jpg)

**Comment by SaaldjorMike** [comment]
I have a friend that reports some very large spikes when performing failover on a active/standby ASA setup. This would certainly be nice to get fixed somehow.

**Comment by f0o** [comment]
I wonder if it's just an odd timing issue an SNMP is actually providing these values for some reason or if it's rather an uncatched conditional on our side... Odd thing is that the values of the spikes arent consistent, or are they?

**Comment by Kr1stian** [comment]
Maybe the size of the spike depends on the time that librenms  host didn't had network access ? 
e.g the last spike on my graph was caused by having network interface disabled for around hour and half.

**Comment by spinza** [comment]
Not sure if this is related but I've also seen large spikes on application / bind charts.  Might there be room for a general solution to this problem?

**Comment by f0o** [comment]
@spinza how large? like impossible large?

**Comment by spinza** [comment]
Yes very impossibly large.  I think it might be the first time it starts up?  Or it might be if it was not available for a couple of polls.

**Comment by f0o** [comment]
rrd overflow?

**Comment by spinza** [comment]
How do I check if that's the issue?

**Comment by laf** [comment]
Ok, so done some research into this tonight - these may not be the only reasons we see spikes but I've included three potential fixes.

So, it appears to happen on graphs that are using rrd files that have COUNTERS, the idea behind these is they provide the difference between two values - the last value and the current. Now for a variety of reasons which aren't worth discussing, it's quite possible for an interface not to be polled for a period of time so when it next is, the difference is larger than expected so you get a spike in your graph - annoying eh!

We have a few options available, all with pros and cons so it would be good to get feedback.

1. Use DERIVE instead. I've read and heard that this can be a good option as most interface speeds in 5 minutes won't see counter resets. However you can't use it with snmp v1 afaik making it a pain to implement.

2. Set sensible max values for rrd files (i.e for a 100Mb port, set 100Mb to be the max). Now we can work this out with ifSpeed or ifHighSpeed when we create the file or run rrdtune to correct it on poller. The issue here is that some interfaces are reported incorrectly, those that under report the ifSpeed will mean people lose data. However it means spikes outside of the interface speed will be excluded.

3. Use a CDEF rule to limit the graph to only show upto it's max ifSpeed value. Same issue with interfaces that under report ifSpeed but at least you don't lose data - you just don't see it.

So #2 and #3 seem to be better options with #3 being pretty simple to implement. I've done a test on this. Below are two graphs, the first showing the actual graph as it would stand today, the second if it was limited to 100M port (it's a 1G port).

It still won't stop spikes as such, but it will stop the unbelievable spikes people see.

4. Now we run the web interface with permissions to access rrd files, we could run removespikes.php from within the browser and just let the user deal with it (still a possibility anyway).

None of this will affect billing btw, that will need to be dealt with by us as data is inserted / read from MySQL so has nothing to do with rrd.

Thoughts?

![image](https://cloud.githubusercontent.com/assets/3941142/8269797/102091f0-17b3-11e5-9519-955dd8fa7e6b.png)


![image](https://cloud.githubusercontent.com/assets/3941142/8269795/f1879bda-17b2-11e5-94fa-ab05d7263839.png)

**Comment by stromsoe** [comment]
I ran into the same issue with a home-grown polling/graphing system and ended up solving it by using the DERIVE type in the RRD, setting the max-value to U, and polling and storing the appropriate value for ifSpeed/ifHighSpeed in the RRD along with octets/packets.  My graphing CDEF uses the stored speed to clip the maximum value in the graph.  That builds in flexibility to move port speed from 10/mb/100mb to 1gb or between 1gb/10gb without having to change hard-coded values (in the RRD or in the CDEF).

**Comment by f0o** [comment]
DERIVE :+1: 
However implies new rrds, or did I miss something?

**Comment by Tatermen** [comment]
I've now gotten a spike on a port that's shutdown.
![spike](https://cloud.githubusercontent.com/assets/8707177/11118895/6c7aacdc-893d-11e5-957e-cb255efb1050.png)
