### ISSUE TITLE
count number may be wrong at "/librenms/html/includes/table/poll-log.inc.php"

### ISSUE THREAD

**Issue by nicole212** [librenms/librenms#1129]
When Librenms counts the number of poll-log entries, may be  "$count_sql = "SELECT COUNT(`D`.`device_id`) $sql"; ..."  at row 19 to 23 should be put after $sql is fully finished (after row 36), otherwise the total number of the table at "/poll-log/" will not fit the actual number of the rows in the poll-log table when any device is down or disabled or be ignored.

**Comment by laf** [comment]
Close, line 25 needed moving to above 19.

The reason I've not included lines below this is that they make up part of the sql query that limits the results to what we expect, the $count_sql call is to get us everything we expect so we know how many results to tell the user we have.

Thanks very much for spotting this though @nicole212 :)

A pr is in place and should get merged pretty soon.
