### ISSUE TITLE
419 Page Expired error when navigating pages in "Custom OID" page

### ISSUE THREAD

**Issue by Chewie9999** [librenms/librenms#11357]
When viewing page http://xx.xx.xx.xx/device/device=xx/tab=edit/section=customoid/, on one device I have more than 10 Custom OIDs I want to display in one page.
When I select any of the values from the Action combo box, the page reloads and I get blank page with the error "419 | Page Expired" in the middle.

This error also occurs when I click any of the page numbers, or the "<" ">" "<<" or ">>" buttons.

This is on Version | 1.61 - Mon Mar 02 2020 04:03:32 GMT+0000

**Comment by murrant** [comment]
your page has expired, refresh the page to fix the issue.

**Comment by Chewie9999** [comment]
refreshing does not help!
