### ISSUE TITLE
Translation to another language

### ISSUE THREAD

**Issue by ppasserini** [librenms/librenms#11363]
Hi,
sorry I know I shouldn't post question but if somebody want to translate to another language, IMO, will not be able to find the right files. I mean, under " /opt/librenms/resources/lang" there are some languages but it's not clear which one is the "master file" to translate.
Morover the uk.json file contains Ukrain translation or am I wrong?
Thank you for you time.

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Please keep in mind that LibreNMS is a community project, it is run by people like you using their free time.
Which means it may take time before support is added to LibreNMS.

We encourage you to do it yourself and submit it in GitHub as a Pull request. It is not so difficult, most of
it can be done without writing a single line of code. You can find the documentation below :
👉  https://docs.librenms.org/Developing/os/Initial-Detection/

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
Yes, translation is a huge work in progress.  It needs to be organized better and easier to find.  Help is appreciated.  Come see us on Discord
