### ISSUE TITLE
Add Basic Support for PBN Devices

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#1140]
im working on it...

http://www.pbnglobal.com/

**Comment by laf** [comment]
Brilliant, if we can help in anyway just let us know.

**Comment by vitalisator** [comment]
This is my first try on git.
I have placed i pull request #1145 for the pbn.png Logo for first.
What happens now? Should i wait for commitment or can i place the other code as separate pull request?

Mit freundlichen Grüßen

Vitali Kari

Von: Neil Lathwood [mailto:notifications@github.com]
Gesendet: Mittwoch, 27. Mai 2015 15:48
An: librenms/librenms
Cc: Kari, Vitali
Betreff: Re: [librenms] Add Basic Support for PBN Devices (#1140)


Brilliant, if we can help in anyway just let us know.

**Comment by vitalisator** [comment]
Can anyone help me to make a "includes/polling/os/pbn.inc.php" from this sysDescr output?

iso.3.6.1.2.1.1.1.0 = STRING: "Pacific Broadband Networks Internetwork Operating System Software
AOCM3924 Series Software, Version 2.1.0C Build 15419, RELEASE SOFTWARE
Compiled: 2013-11-11 14:55:11 by SYS
ROM: System Bootstrap, Version 0.4.0
Serial num:S39010199, ID num:39010199
"
 thanks!

**Comment by Rosiak** [comment]
Hi vitalisator,

Question:
Is the S/N, Version, Hardware not represented in separate OID's?
If not this will require some regex.

**Comment by vitalisator** [comment]
Yes, i got yesterday a lot of  MIB files, but first only for internal use. ☹
I will ask PBN for permission to contribute this file to libreNMS…

Is there a example or a good template how to use MIB files?

**Comment by laf** [comment]
@vitalisator We really could do with the mibs in case we have to provide additional features but to get you started something like this should work:

includes/discovery/os/pbn.inc.php
```php
<?php

if (!$os) {
    if (stristr($sysDescr, "Pacific Broadband Networks")) {
        $os = 'pbn';
    }
}
```

You also need to create a includes/discovery/os/pbn.inc.php and also update includes/definitions.inc.php
