### ISSUE TITLE
Support for Proxmox VE

### ISSUE THREAD

**Issue by joubertredrat** [librenms/librenms#1143]
Hi,
I want to implement support for Proxmox VE. Proxmox VE is a powerful open source server virtualization Platform, based on kvm and Openvz. Is based on Debian linux distro.

I think that can be monitored openvz and kvm resources.

**Comment by arjitc** [comment]
Proxmox VE runs off Debian as the base OS and can be SSH'd into, ie, snmpd can be installed on this machine + the libvirt plugin / config can be enabled from under config.php

**Comment by joubertredrat** [comment]
Hi,
Yes @arjitc, I see that is possible to monitor with snmp, but in some cases isn't possible to monitor with ssh. I as example, my Proxmox ssh access is only with restricted ssh user with keys, then, In my case don't work.

I will see if is good idea to use snmp to monitoring openvz and kvm resources, as this example.

https://openvz.org/Monitoring_openvz_resources_using_nagios_and_snmp

**Comment by tuxis-ie** [comment]
Hi, PR 1789 is about to be merged and will start with graphing the VM network interfaces, grouped by cluster. Maybe, in the future, disk-io and cpu-usage will be available as wel..

**Comment by f0o** [comment]
Tagging: #1789

**Comment by Rosiak** [comment]
Can this be closed?

**Comment by tuxis-ie** [comment]
I'd say so, yes.
