### ISSUE TITLE
Proxy Bluecoat ASG-S500 recognized like a generic device

### ISSUE THREAD

**Issue by sri-ratp** [librenms/librenms#11469]
Hello,
My proxy Bluecoat Device is not recognized as it should be. it's seen like a generic device !!
Here are the you ask for helping:
/discovery.php -h xxxxxxxxx -d | ./pbin.sh : https://p.libren.ms/view/b48ba309
./poller.php -h HOSTNAME -r -f -d | ./pbin.sh : https://p.libren.ms/view/6ae0604c
snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh : doesn't return a link ! Her is the message: Error: Missing paste text.

If you can help.

**Comment by sri-ratp** [comment]
Hello, 
Can you tell me what info do you need ?
regards

**Comment by PipoCanaja** [comment]
@sri-ratp  The snmpwalk is the most important data to provide.

**Comment by TheGreatDoc** [comment]
@sri-ratp could you provide the snmpwalk?

**Comment by Jellyfrog** [comment]
Add the request here instead please; https://community.librenms.org/c/device-requests/12
