### ISSUE TITLE
making graphs public?

### ISSUE THREAD

**Issue by arjitc** [librenms/librenms#1146]
Hello,
I was looking for an option to make a graph public, anything specific I need to add into config.php?

**Comment by laf** [comment]
http://docs.librenms.org/Support/Configuration/#authentication

$config['allow_unauth_graphs']      = 0;
$config['allow_unauth_graphs_cidr'] = array();

We still support this from the fork but I'd highly recommend that you switch to the api: http://docs.librenms.org/API/API-Docs/

**Comment by f0o** [comment]
Closing this issue as all required informations are found in the docs.
Feel free to reopen it if you miss something.
