### ISSUE TITLE
Support for Server model Penguin?

### ISSUE THREAD

**Issue by Sasiko** [librenms/librenms#11492]
My issue is that none of the graphic are working as im getting

SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-Oqv' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/supermicro:/opt/librenms/mibs/dell:/opt/librenms/mibs/wti' 'udp:HOSTNAME:161' 'WTI-MPC-MIB::environmentUnitName.1']
No Such Object available on this agent at this OID

The question is if its looking for dell and supermicro mibs if so then its not checking my server mibs properly since i dont have a supermicro board or dell rack.

Model | Penguin Computing Relion 2800i

Motherboard | Quanta S210-X22RQ V2

Centos 7

./discovery.php -d -h 7

Output:
https://www.mediafire.com/file/null/output.txt/file

./poller.php -d -h 7

Output:
https://www.mediafire.com/file/w3lxs73wrlges1m/poller.txt/file

snmpwalk -v 2c -c servermon 127.0.0.1

Output:
https://www.mediafire.com/file/8as1d2luo5q2ukf/snmp.txt/file

**Comment by Jellyfrog** [comment]
Add the request here instead please; https://community.librenms.org/c/device-requests/12
