### ISSUE TITLE
Support for HPE MSA2050 SAN

### ISSUE THREAD

**Issue by eJc2** [librenms/librenms#11537]
Hi, please add support for HPE MSA 2050 SAN, right now librenms just show traffic on management port, no cpu, raid state, space, etc.

Mibs file from HPE attached.

[mibs.zip](https://github.com/librenms/librenms/files/4568537/mibs.zip)

**Comment by kkrumm1** [comment]
Please review the info requested

**Comment by eJc2** [comment]
Hi, what kind of info do you need?

**Comment by kkrumm1** [comment]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Please keep in mind that LibreNMS is a community project, it is run by people like you using their free time.
Which means it may take time before support is added to LibreNMS.

We encourage you to do it yourself and submit it in GitHub as a Pull request. It is not so difficult, most of
it can be done without writing a single line of code. You can find the documentation below :
👉  https://docs.librenms.org/Developing/os/Initial-Detection/

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations
