### ISSUE TITLE
Overwrite IP in Add Device missing

### ISSUE THREAD

**Issue by gertfriend** [librenms/librenms#11565]
Hello,

since a few weeks, after a update, i have the problem that i am missing “Overwrite IP” in the “Add Device” screen.
Is this intended or its a bug?

Thanks

**Comment by murrant** [comment]
Intended.  If you would like to add a device by IP, just type the IP in the "hostname" field.

**Comment by gertfriend** [comment]
May it be possible to add the possibility to enable this field permanently in the settings.
The problem is, that i monitor some devices over the public ip but with different ports so i have to give as hostname another name as the public hostname (IP) is?
Thanks

**Comment by murrant** [comment]
It still exists under the device settings.  The problem is we had many users breaking things with that setting as they did not understand it.  And it only benefits a few users.  (most send snmp over a vpn or similar)

**Comment by gertfriend** [comment]
Ok, so it i would ask you gently if its possible to create a checkbox to enable it for every entry?
Or can i enable it editing simply a file?
If not, can you please tell me the last version where it was available so i will go back to this version and disable updates.
Thank you very much and thanks for your great work.

**Comment by gertfriend** [comment]
Ok, so it i would ask you gently if its possible to create a checkbox to enable it for every entry?
Or can i enable it editing simply a file?
If not, can you please tell me the last version where it was available so i will go back to this version and disable updates.

Thank you very much and thanks for your great work.

**Comment by gertfriend** [comment]
Ok, so it i would ask you gently if its possible to create a checkbox to enable it for every entry?
Or can i enable it editing simply a file?
If not, can you please tell me the last version where it was available so i will go back to this version and disable updates.

Thank you very much and thanks for your great work.

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/overwrite-ip-in-add-device-missing/11878/2
