### ISSUE TITLE
Fortigate cpu/core usage

### ISSUE THREAD

**Issue by atbohmer** [librenms/librenms#11570]
Hello,

Quite desperate, so I hope this issue is allowed to be created and gets some much appreciated attention. For more background information, please do see https://community.librenms.org/t/not-discovering-cores-just-1-cpu/6809/6

I myself tested with a recent LibreNMS Centos7 OVA image and also a fresh Centos 7.8 installation with latest LibreNMS git master branch. Both to no avail, shows only one cpu usage/total average cpu usage.

Best regards,
Andre

**Comment by jozefrebjak** [comment]
Hello @atbohmer do you want to switch from `fgSysCpuUsage` which is for Current CPU usage, which is same for all fortinet fortigate devices to which one from table `fgProcessors`

There is for example output from walk of that table for `FGT_60E` for example. 

```
FORTINET-FORTIGATE-MIB::fgProcessorCount.0 = INTEGER: 4
FORTINET-FORTIGATE-MIB::fgProcessorEntIndex.1 = INTEGER: 1
FORTINET-FORTIGATE-MIB::fgProcessorEntIndex.2 = INTEGER: 2
FORTINET-FORTIGATE-MIB::fgProcessorEntIndex.3 = INTEGER: 3
FORTINET-FORTIGATE-MIB::fgProcessorEntIndex.4 = INTEGER: 4
FORTINET-FORTIGATE-MIB::fgProcessorUsage.1 = Gauge32: 0 %
FORTINET-FORTIGATE-MIB::fgProcessorUsage.2 = Gauge32: 0 %
FORTINET-FORTIGATE-MIB::fgProcessorUsage.3 = Gauge32: 0 %
FORTINET-FORTIGATE-MIB::fgProcessorUsage.4 = Gauge32: 0 %
FORTINET-FORTIGATE-MIB::fgProcessorUsage5sec.1 = Gauge32: 0 %
FORTINET-FORTIGATE-MIB::fgProcessorUsage5sec.2 = Gauge32: 0 %
FORTINET-FORTIGATE-MIB::fgProcessorUsage5sec.3 = Gauge32: 0 %
FORTINET-FORTIGATE-MIB::fgProcessorUsage5sec.4 = Gauge32: 0 %
FORTINET-FORTIGATE-MIB::fgProcessorType.1 = OID: FORTINET-FORTIGATE-MIB::fgProcessorOther
FORTINET-FORTIGATE-MIB::fgProcessorType.2 = OID: FORTINET-FORTIGATE-MIB::fgProcessorOther
FORTINET-FORTIGATE-MIB::fgProcessorType.3 = OID: FORTINET-FORTIGATE-MIB::fgProcessorOther
FORTINET-FORTIGATE-MIB::fgProcessorType.4 = OID: FORTINET-FORTIGATE-MIB::fgProcessorOther
FORTINET-FORTIGATE-MIB::fgProcessorContainedIn.1 = INTEGER: 1
FORTINET-FORTIGATE-MIB::fgProcessorContainedIn.2 = INTEGER: 1
FORTINET-FORTIGATE-MIB::fgProcessorContainedIn.3 = INTEGER: 1
FORTINET-FORTIGATE-MIB::fgProcessorContainedIn.4 = INTEGER: 1
FORTINET-FORTIGATE-MIB::fgProcessorPktRxCount.1 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgProcessorPktRxCount.2 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgProcessorPktRxCount.3 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgProcessorPktRxCount.4 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgProcessorPktTxCount.1 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgProcessorPktTxCount.2 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgProcessorPktTxCount.3 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgProcessorPktTxCount.4 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgProcessorPktDroppedCount.1 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgProcessorPktDroppedCount.2 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgProcessorPktDroppedCount.3 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgProcessorPktDroppedCount.4 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgProcessorUserUsage.1 = Gauge32: 0 %
FORTINET-FORTIGATE-MIB::fgProcessorUserUsage.2 = Gauge32: 0 %
FORTINET-FORTIGATE-MIB::fgProcessorUserUsage.3 = Gauge32: 0 %
FORTINET-FORTIGATE-MIB::fgProcessorUserUsage.4 = Gauge32: 0 %
FORTINET-FORTIGATE-MIB::fgProcessorSysUsage.1 = Gauge32: 0 %
FORTINET-FORTIGATE-MIB::fgProcessorSysUsage.2 = Gauge32: 0 %
FORTINET-FORTIGATE-MIB::fgProcessorSysUsage.3 = Gauge32: 0 %
FORTINET-FORTIGATE-MIB::fgProcessorSysUsage.4 = Gauge32: 0 %
```

Do you know which one do you need ?

**Comment by atbohmer** [comment]
Hello Josef,
Indeed you're right, I was focusing on the main 3700d with LibreNMS cluster but Observium is not able to retrieve all processor info from a 200D model, only from a 3700 and a 100.
Is there a way I can check in Observium which OID it uses to collect cpu info from the 3700D?
Best regards,
Andre

**Comment by Senetus** [comment]
Run tcpdump with the fortigate host ip as filter, you should see what it polls. But of course you might need to parse through a lot of data. Or alternatively go through the code. Is the 100 model also a 100d or a newer generation? With larger models there were always additional parameters that could be read but with the smaller ones not. Except with newer models.

**Comment by atbohmer** [comment]
Both 3700D and 100D are from 2014. I've made a pcap from observium as wel LibreNMS and will compare both, will let you know soon, thanks!

**Comment by atbohmer** [comment]
Great work, thanks!
