### ISSUE TITLE
lm-sensors fan speeds

### ISSUE THREAD

**Issue by stpq** [librenms/librenms#1160]
lm-sensors fan speeds from linux box:)

**Comment by laf** [comment]
http://d.admamsterdam.org/pub/lmMiscSensorsEntry.txt

**Comment by f0o** [comment]
This is an issue with snmpd versions lower 5.5 and lmsensors versions higher 3.0.

As seen in debian wheezy, they ship lmsensors >3.0 but snmp <5.5 despite lmsensors stating a requirement for snmpd >=5.5. All sensors are pushed to the lmMisc namespace as a result.
As for debian jessie, they updated snmpd to 5.7 and therefore all sensors are fine again.

I'd say it's an upstream problem.

**Comment by laf** [comment]
Looking at the output from the snmpwalk it doesn't look like we are able to use the data anyway as it gives no indication of what's the actual readings or what's max / min, you just have to assume.

Proposing we close this in 24 hours unless further info can be provided.
