### ISSUE TITLE
NX-OS 9.3(4) 

### ISSUE THREAD

**Issue by aalmenar** [librenms/librenms#11659]
After upgrading a few Nexus 3K switches to 9.3(4) LibreNMS no longer detects them as NX-OS devices, but rather shows them all as generic. I've rerun discovery on them, but it made no difference.

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

https://p.libren.ms/view/b91c967c
https://p.libren.ms/view/856e9e34

- [x] Please provide as much detail as possible.

**Comment by PipoCanaja** [comment]
Please provide the `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh`as well. This is the most important one to replicate your device.

**Comment by aalmenar** [comment]
Hi, its too big to post with ./pbin.sh, also there are information thta should not be public in there, how can it be dodne ?

**Comment by aalmenar** [comment]
Does it work ? or do i need to get more information ?

**Comment by network-guy** [comment]
@aalmenar The OS definition checks the sysDescr OID (.1.3.6.1.2.1.1.1.0) for either "NX-OS(tm)" or "Cisco NX-OS". The sysDescr OID on your output shows "iso.3.6.1.2.1.1.1.0 = STRING: "Usage:". I don't have any 3Ks to test with. I do have some 9Ks on 9.3.3 without issues.

More than likely this is a bug with that particular firmware release. I'm not sure of any other good way of detecting the OS outside the sysDescr OID.

**Comment by eimann** [comment]
I remember having this issue with 9.3(2). But I can't remember if I deconfigured snmp completely and put the configuration or reloaded the box.

**Comment by pedrompcaetano** [comment]
Hi,
I run a few switches running nxos 9.3(2) as well.

After discovering the devices, make sure the device is set to Network. (mine was set to generic)

Since that change, all devices are being correctly polled :-)

HTH

**Comment by Jellyfrog** [comment]
Add the request here instead please; https://community.librenms.org/c/device-requests/12
