### ISSUE TITLE
Asus RT-AC68U Support

### ISSUE THREAD

**Issue by aalmenar** [librenms/librenms#11712]
- [x ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

- ./discovery.php -h HOSTNAME -d | ./pbin.sh
https://p.libren.ms/view/6be0f177

- ./poller.php -h HOSTNAME -r -f -d | ./pbin.sh
https://p.libren.ms/view/dbb930bf

- snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh
https://p.libren.ms/view/c6501bc6

Regards.

**Comment by murrant** [comment]
Device, request, please move to community site.
