### ISSUE TITLE
Not receiving correct data from new Ubiquiti Unifi 8-port switch

### ISSUE THREAD

**Issue by jumpingmushroom** [librenms/librenms#11733]
Hi!

I just received a new 8-port unifi switch with the board revision 24, which seems like it's one of the newest (tested this may 2020 before being shipped out according to the box). This one doesn't return the same SNMP values as my older model (board revision 10), and as such is not identified properly by librenms. I tried chaning the values specified in this commit #5407, as snmp polling the value iso.3.6.1.2.1.1.1.0 returns "USW GigaBit Ethernet Switch, firmware v4.3.13.11253". The definition was set up to look for /^USW-, which seems no longer the case. That helped identify the swith, but there's still missing a lot of info (like version number, hostname, vlans for each port etc). Could I in any way help out fixing this?

This is the model btw: https://store.ui.com/collections/unifi-network-routing-switching/products/unifi-switch-8

Thanks!

**Comment by TyShawn76** [comment]
The last word I got from them is they needed to create a new mib set for the newer switches. I am with you on this problem and it affects all new switches UI has introduced.
