### ISSUE TITLE
APC In-Row cooler not discovered

### ISSUE THREAD

**Issue by karrots** [librenms/librenms#11763]
- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

https://p.libren.ms/view/717f0845
https://p.libren.ms/view/04d6a360
https://p.libren.ms/view/d90b2f0a

These are APC in-row coolers. They are a newer model. They are not detecting as an APC in-row cooler

**Comment by kkrumm1** [comment]
Looks like you are have a PR open. No need to open an issue for this.
