### ISSUE TITLE
Empty RRDs only on localhost

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#1177]
Hi,

what can be a cause for empty rrds on localhost (LibreNMS Server)
Installation is made upon WEB installation Instruction for Debian.
the rrd graphs for othes systems are fin, only localhost is empty.

**Comment by laf** [comment]
Hi @vitalisator 

snmp setup correctly on localhost?

If so, run ./poller.php -h localhost -d -m system,os and paste the output for us to look at.

**Comment by vitalisator** [comment]
Thanks for hint @laf,
a saw there was a permission problem:
ERROR: opening '/opt/librenms/rrd/localhost/uptime.rrd': Permission denied

this solves my Problem.
chown -R librenms.librenms /opt/librenms/rrd/localhost

thanks!
