### ISSUE TITLE
Installation instructions - pymysql vs. mysqldb

### ISSUE THREAD

**Issue by candlerb** [librenms/librenms#11814]
The [installation instructions](https://docs.librenms.org/Installation/Installation-Ubuntu-1804-Apache/) for Ubuntu 18.04 say to install `python-mysqldb`.   Since LibreNMS is using python3, I installed `python3-mysqldb`.

However the polller fails with the following error:

```
Cronic detected failure or error output for the command:
/opt/librenms/poller-wrapper.py 16

RESULT CODE: 1

ERROR OUTPUT:
Traceback (most recent call last):
  File "/opt/librenms/poller-wrapper.py", line 28, in <module>
    import LibreNMS.library as LNMS
  File "/opt/librenms/LibreNMS/__init__.py", line 12, in <module>
    from .service import Service, ServiceConfig
  File "/opt/librenms/LibreNMS/service.py", line 6, in <module>
    import pymysql
ModuleNotFoundError: No module named 'pymysql'
```

AFAICS the correct package is `python3-pymysql`.  After installing this, polling works.

However, I can see that mysqldb *is* used in other places:

```
/opt/librenms/LibreNMS/__init__.py:            pymysql.install_as_MySQLdb()
/opt/librenms/LibreNMS/__init__.py:            import MySQLdb
/opt/librenms/LibreNMS/__init__.py:            conn = MySQLdb.connect(**args)
/opt/librenms/LibreNMS/__init__.py:        :rtype: MySQLdb.Cursor
/opt/librenms/LibreNMS/library.py:    import MySQLdb
/opt/librenms/LibreNMS/library.py:        pymysql.install_as_MySQLdb()
/opt/librenms/LibreNMS/library.py:        import MySQLdb
/opt/librenms/LibreNMS/library.py:        return MySQLdb.connect(**options)
```

So I'm not sure if the problem here is that the installation instructions have forgotten the `python3-pymysql` package, or if it was intended that the poller should be changed to using MySQLdb.

------

Additional: the installation instructions also say to install `python-memcache`; I think this should now say `python3-memcache`.

**Comment by candlerb** [comment]
Additional related note from validate.php (not worth a separate issue for):

```
[FAIL]  Python3 module issue found: 'The 'python-dotenv' distribution was not found and is required by the application
```

This can be fixed by adding "python3-dotenv" to the installation instructions as well.

**Comment by kkrumm1** [comment]
You can modify the docs and submit the changes :)
