### ISSUE TITLE
Latest update broke login with GET variables

### ISSUE THREAD

**Issue by ozupey** [librenms/librenms#11811]
Some time ago, this pull request added authentication via GET variables: https://github.com/librenms/librenms/pull/9268

However, this commit seems to have broken it: https://github.com/librenms/librenms/commit/5c6c8844e8270f2f565577444c8ed6497c4fac56

For example, this used to work:
http://librenms.example.com/overview?dashboard=1&username=foo&password=bar

But since the latest update, this just redirects to the login page. Any code inside the LegacyExternalAuth.php `handler()` never gets executed.

**Comment by kkrumm1** [comment]
https://github.com/librenms/librenms/pull/11813
