### ISSUE TITLE
Ability to SORT Columns

### ISSUE THREAD

**Issue by Lonecrowe** [librenms/librenms#1182]
For example when I go to HEALTH / PROCESSOR I'd like to be able to click on "Usage" and have it sort by highest to lowest.  Or if I click on Processor it'll sort them by type alphabetically.  

This goes for many of the health settings.

**Comment by Rosiak** [comment]
Hi @Lonecrowe,
PR #1188 should fix this :)

**Comment by Lonecrowe** [comment]
Thanks that works great!

**Comment by Lonecrowe** [comment]
Woops.. would like to be able to sort other columns as well for other health items such

Memory Usage %
Temperature
Battery Charge
Fanspeed
Voltage
And importantly - Current  (So you can see which devices are drawing the most power)

**Comment by Rosiak** [comment]
Memory has been PR'ed in #1192 @Lonecrowe :)

**Comment by Lonecrowe** [comment]
Lemme check.. 

Beautiful works.  Thanks a bunch again!
