### ISSUE TITLE
F5 BIG-IP 10Gbps port speed not correct

### ISSUE THREAD

**Issue by anderssonpof** [librenms/librenms#1189]
F5 BIG-IP 10Gbps ports reported as 4.29Gbps
BIG-IP 4000s if that is any help

![image](https://cloud.githubusercontent.com/assets/7721452/7956735/746e7dfe-09e2-11e5-92f6-24dfef411556.png)

![image](https://cloud.githubusercontent.com/assets/7721452/7958309/5706c7c4-09ee-11e5-870c-9029a5295c00.png)

**Comment by SaaldjorMike** [comment]
@anderssonpof: Can you please provide output from the following?
`/opt/librenms/poller.php -h HOSTNAME -d -m ports`
Remember to filter out any sensitive information before pasting it to a service like https://bpaste.net/

**Comment by anderssonpof** [comment]
@SaaldjorMike see: https://bpaste.net/show/1acb57bc8d13

**Comment by SaaldjorMike** [comment]
From what I can see the following gets reported:
```
ifSpeed.864 = 4294967295
ifSpeed.880 = 4294967295
```

So from LibreNMS' perspective, this is exactly what the switch reports.

**Comment by paulgear** [comment]
That looks suspiciously like the value of UINT_MAX; is there a 64-bit counter for those?

**Comment by anderssonpof** [comment]
@paulgear How do i check?

Found this from the F5 docs: All BIG-IP system statistics are defined by 64-bit counters

**Comment by paulgear** [comment]
@anderssonpof /usr/bin/snmpbulkwalk -v2c -c snmpstring -OQUs  -m IF-MIB -M /opt/librenms/mibs udp:hostname:161 ifXEntry should show it if it's there.

**Comment by laf** [comment]
@paulgear We try ifXEntry and it's in the debug:

/usr/bin/snmpbulkwalk -v2c -c snmpstring -OQUs  -m IF-MIB -M /opt/librenms/mibs udp:hostname:161 ifXEntry
ifXEntry = No Such Object available on this agent at this OID

@anderssonpof can you run;

```bash
/usr/bin/snmpbulkwalk -v2c -c snmpstring -OQUs  -m IF-MIB -M /opt/librenms/mibs udp:hostname:161 ifHighSpeed
```

**Comment by anderssonpof** [comment]
@paulgear @laf 
```
:~# /usr/bin/snmpbulkwalk -v2c -c snmpstring -OQUs  -m IF-MIB -M /opt/librenms/mibs udp:hostname:161 ifHighSpeed
ifHighSpeed = No Such Object available on this agent at this OID
```

if i run this it seems to get the correct values 
```
:~# /usr/bin/snmpbulkwalk -v2c -c snmpstring -OQUs  -m IF-MIB -M /opt/librenms/mibs udp:hostname:161 .1.3.6.1.4.1.3375.2.1.2.4.1.2.1.2
enterprises.3375.2.1.2.4.1.2.1.2.3.49.46.49 = 1000
enterprises.3375.2.1.2.4.1.2.1.2.3.49.46.50 = 0
enterprises.3375.2.1.2.4.1.2.1.2.3.49.46.51 = 1000
enterprises.3375.2.1.2.4.1.2.1.2.3.49.46.52 = 1000
enterprises.3375.2.1.2.4.1.2.1.2.3.49.46.53 = 0
enterprises.3375.2.1.2.4.1.2.1.2.3.49.46.54 = 0
enterprises.3375.2.1.2.4.1.2.1.2.3.49.46.55 = 0
enterprises.3375.2.1.2.4.1.2.1.2.3.49.46.56 = 1000
enterprises.3375.2.1.2.4.1.2.1.2.3.50.46.49 = 10000
enterprises.3375.2.1.2.4.1.2.1.2.3.50.46.50 = 10000
enterprises.3375.2.1.2.4.1.2.1.2.4.109.103.109.116 = 1000
```
Found in:
F5-BIGIP-SYSTEM-MIB
sysInterfaceMediaMaxSpeed

**Comment by laf** [comment]
Yeah I did read that f5 have there own mib for interface data. We'll probably need to use that mib and alter the ports poller to get this to work.

**Comment by paulgear** [comment]
Is this the part where we start raging at vendors for non-standard SNMP and refuse to support them? :-)

**Comment by laf** [comment]
lol. No way :)

**Comment by anderssonpof** [comment]
Anything more needed for this?

**Comment by laf** [comment]
Can you provide the output of: `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .`

**Comment by anderssonpof** [comment]
Hi,

I'm sorry but I've got a new job and no longer have access to a F5.

Thanks you anyway :)
