### ISSUE TITLE
Add support for CyberPower ATS/PDU

### ISSUE THREAD

**Issue by engageant** [librenms/librenms#11940]
- [x ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery: https://p.libren.ms/view/acd12634
Poller: https://p.libren.ms/view/706124aa
SNMP Walk: https://p.libren.ms/view/f71345c9
CyberPower MIB: https://p.libren.ms/view/d7a84fec
Model: CyberPower PDU30SWT17ATNET

LibreNMS detects the OS as Cyberpower but does not pull any data. The only two graphs that appear are voltage and current; both of them show "Error Drawing Graph". 

If there are further details I can provide, please let me know. Thanks!

**Comment by PipoCanaja** [comment]
From your snmpwalk, it appears that the device is not returning anything from its own mib. 

You should get in touch with your vendor, get a correct/updated firmware, and ensure that your device is replying data to snmp requests.
