### ISSUE TITLE
WMI (Windows Management Instrumentation) Support

### ISSUE THREAD

**Issue by nova-2nd** [librenms/librenms#11970]
Dear LibreNMS Dev Team,

As a longtime user of LibreNMS, I would love to see WMI support (, finally). Which would extend LibreNMS capabilities massively!

WMI is a very mature and well established framework, which would enable at least the following,
- Access any Windows performance counter!!, including
-- Operating system, especially those which are not exposed via SNMP directly (!!DISKS!!)
-- Active Directory
-- Exchange
-- IIS
-- SQL
-- ... whatever else I forgot

Unlike discussed in issue (https://github.com/librenms/librenms/issues/1035), there is no need for a painful Password/Kerberos, WinRM/WBEM implementation for interfacing with WMI.

There is and was for the last 20 years, WMI over SNMP, so it would be really "just" the development of the content exchange on existing SNMP infrastructure in LibreNMS.

Like the SNMP agent extension on Linux via check_mk, there would be the requirement to create and compile, so called mof's, but looking on the benefit, IMHO that's more than worth the effort. (https://docs.microsoft.com/en-us/windows/win32/wmisdk/setting-up-the-wmi-snmp-environment)

So, when I mean massively, then I am meaning that literally!

Greets,
Stefan

**Comment by kkrumm1** [comment]
Please post feature requests on the forums.

**Comment by spastro** [comment]
Anyupdate to WMI? or a way to pull in all desktops / laptops / servers?
