### ISSUE TITLE
Temperature Support for Synology DS213+

### ISSUE THREAD

**Issue by Calvario** [librenms/librenms#1198]
Hello !

I have a Synology DS213+ with an UPS APC Back-UPS RS 900G.
I'd like to help you to improve the managements of Synology products

I have a little problem with the poller they return 0 on the System temperature but with the snmpwalk that return 36.

snmpwalk -v 2c -c mycommunity myip 1.3.6.1.4.1.6574.1.2
SNMPv2-SMI::enterprises.6574.1.2.0 = INTEGER: 36

Thanks for helping and thanks for this software !!

**Comment by laf** [comment]
Hi @Calvario 

We can sort the temperature support :)

If you don't mind creating a separate issue for the UPS as they will be worked on separately that would be great.


Yes we can support fan status of just 1/0 using the states sensor. We only have Dell openmanage disk support in at the moment but we can add more, just need the OIDs and what device it is - again if you can create a separate issue that you would be great.
