### ISSUE TITLE
Validate.php capabilities false positive with symlinks

### ISSUE THREAD

**Issue by filippog** [librenms/librenms#11998]
Following up here since there have been no answers to my post on the forum: https://community.librenms.org/t/validate-php-capabilities-false-positive-with-symlinks/12856

I’m running into an issue with validate.php and fping6 on Debian Buster (10). Namely, /usr/bin/fping6 is a symlink and getcap doesn’t seem to follow symlinks. The end result being that validate.php suggests a fix for fping6 capabilities which in fact are already correct:

```
[FAIL]  fping6 should have CAP_NET_RAW!
    [FIX] getcap c /usr/bin/fping6

# ls -la /usr/bin/fping /usr/bin/fping6
-rwxr-xr-x 1 root root 48032 Feb 19  2019 /usr/bin/fping
lrwxrwxrwx 1 root root     5 Feb 19  2019 /usr/bin/fping6 -> fping
# getcap /usr/bin/fping
/usr/bin/fping = cap_net_raw+ep
# getcap /usr/bin/fping6
# echo $?
0
```

Sort-of related, the suggested fix uses getcap while I think it should suggest `setcap cap_net_raw+ep <path>`

thank you!

**Comment by filippog** [comment]
Arguably this is a bug in `validate.php` yielding a FAIL where it shouldn't, and the suggested FIX isn't correct AFAICS. What's the procedure in this case?

**Comment by Senetus** [comment]
Set the fping6 path into the fping binary in your config.

**Comment by Senetus** [comment]
And in general all help and bugs should be reported in discord or the community sites, bug reports are not handled in github.
