### ISSUE TITLE
Migrate to mysqli

### ISSUE THREAD

**Issue by supertylerc** [librenms/librenms#12]
The `mysql_` functions currently in use are deprecated as of PHP 5.5.0 in favor of the `mysqli_` functions.

See the [PHP FAQ][1] for more details.

We need to start looking at a migration path.

[1]: http://www.php.net/manual/en/faq.databases.php#faq.databases.mysql.deprecated "mysql deprecated php 5.5.50"

**Comment by f0o** [comment]
any update on this very old issue?

**Comment by laf** [comment]
Now done.
