### ISSUE TITLE
System Status Support for Synology DS213+

### ISSUE THREAD

**Issue by Calvario** [librenms/librenms#1200]
Hello !

I have a Synology DS213+.
I'd like to help you to improve the managements of Synology products

It's possible to add the Status stat support for the Synology ?
I have copy past the OIDs and the result i have.

System Status (1 Normal, 2 Failed)
.1.3.6.1.4.1.6574.1.1.0
SNMPv2-SMI::enterprises.6574.1.1.0 = INTEGER: 1

Power Status  (1 Normal, 2 Failed)
.1.3.6.1.4.1.6574.1.3.0
SNMPv2-SMI::enterprises.6574.1.3.0 = INTEGER: 1

System Fan Status  (1 Normal, 2 Failed)
.1.3.6.1.4.1.6574.1.4.1.0
SNMPv2-SMI::enterprises.6574.1.4.1.0 = INTEGER: 1

CPU Fan Status  (1 Normal, 2 Failed)
.1.3.6.1.4.1.6574.1.4.2.0
SNMPv2-SMI::enterprises.6574.1.4.2.0 = INTEGER: 1

DSM Upgrade Available  (1 Available, 2 Unavailable, 3 Connecting, 4 Disconnected, 5 Others)
.1.3.6.1.4.1.6574.1.4.2.0
SNMPv2-SMI::enterprises.6574.1.4.2.0 = INTEGER: 1

Disks Status (1 Normal, 2 Initialized, 3 Not Initialized, 4 System Partition Failed, 5 Crashed )
.1.3.6.1.4.1.6574.2.1.1.5
SNMPv2-SMI::enterprises.6574.2.1.1.5.0 = INTEGER: 1
SNMPv2-SMI::enterprises.6574.2.1.1.5.1 = INTEGER: 1

RAID Status ( 1 Normal, 2 Repairing, 3 Migrating, 4 Expanding, 5 Deleting, 6 Creating, 7 RaidSyncing, 8 RaidParityChecking, 9 RaidAssembling, 10 Canceling, 11 Degrade, 12 Crashed)
.1.3.6.1.4.1.6574.3.1.1.3
SNMPv2-SMI::enterprises.6574.3.1.1.3.0 = INTEGER: 1

UPS Status ( OL - On Line, OB - On Battery)
.1.3.6.1.4.1.6574.4.2.1.0
SNMPv2-SMI::enterprises.6574.4.2.1.0 = STRING: "OL"

Thanks for helping and thanks for this software !!

**Comment by Lonecrowe** [comment]
Good stuff. I'd like to see it too and I can test any builds on my machines as well.

**Comment by Calvario** [comment]
Actualy i have code it but i'm still waiting for this issue : #1236

**Comment by laf** [comment]
So this can be done without the reliance on #1236 but it means you won't have human readable output, just simply the state back.

**Comment by Calvario** [comment]
OK i have add the pull to to the pull request.

**Comment by laf** [comment]
@Calvario This is due to you working in the master branch, any commits you do will go to the same PR. 

I'd suggest reading: http://docs.librenms.org/Developing/Using-Git/

Note though, this bit isn't really needed:

```bash
git checkout master
git pull upstream master
git push origin master
``
