### ISSUE TITLE
Proposal - User submitted stats

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#1204]
Would be nice to prompt the user for the "User Submitted Stats", could be a notification like the one used when devices haven't been polled for 5 mins. Users can then choose, yes opt in or no don't, a entry in the DB will then be updated so it will remain a one-time question only.

**Comment by f0o** [comment]
Ideally we should think of a method to announce changes etc inside of LibreNMS.
Air-Gapped systems are going to be a tough issue ;)

Maybe have it all predefined and db-driven like @Rosiak suggests and feed either a folder for the messages so we can update them with simple commits..

Or we dont care about Air-Gapped installs and go for an RSS-feed.

Tagging the whole team to discuss: @laf @paulgear

**Comment by laf** [comment]
I'm with you on the DB driven system, that's been my intentions for a while but never started on it. It's really simple but will need to include a read / ack / dismiss feature so people can close off messages. Needs to be able to insert messages for all the admin accounts.

As we are doing that then it would be good to maybe enable user to user messaging.

**Comment by paulgear** [comment]
Yeah - I think the pop-ups as they stand are a little annoying; every time you refresh the page and something's wrong, they alert you.  Like @laf says, needs an ack / dismiss.  User to user messaging seems to be to be well worth not doing - there are plenty of other solutions for that.  We don't want to be LibreEmacs. :-)

**Comment by Rosiak** [comment]
Perhaps something like this can be used?
https://github.com/mouse0270/bootstrap-notify

**Comment by laf** [comment]
@paulgear Once you've added the facility to add messages to a table where we can inject them on an update then you're a simple form away from allowing say an admin to send a message all users so not sure why we'd not bother imho.

@Rosiak The current pop up notification system is similar to the one you've linked to.
