### ISSUE TITLE
Extreme Switch CPU OID

### ISSUE THREAD

**Issue by ghost** [librenms/librenms#12094]
The Extreme switch cpu oid contains in exists os yaml  is wrong. 
Its only "System Utilization 5mins". 
The correct one is 1.3.6.1.4.1.1916.1.32.1.2.0. 
This 1.3.6.1.4.1.1916.1.32.1.2.0.  is "Total Utilization" for whole processes.

**Comment by ottorei** [comment]
Fixed with #13633
