### ISSUE TITLE
Add some graphs to Multimatic UPS

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#1216]
there are a lot of Sensors, but i don't know how to add this to graphs.
its all UPS-MIB RFC1628

can anyone show example to make to put it into temperature or load etc.
i saw the includes/discovery/load/apc.inc.php but it is to difficult for me at the moment.

snmpwalk -v2c -c public 10.130.30.103 UPS-MIB::upsMIB
UPS-MIB::upsIdentManufacturer.0 = STRING: Multimatic
UPS-MIB::upsIdentModel.0 = STRING: MD-3000I
UPS-MIB::upsIdentUPSSoftwareVersion.0 = STRING: n/a
UPS-MIB::upsIdentAgentSoftwareVersion.0 = STRING: CS121 v 5.22.17
UPS-MIB::upsIdentName.0 = STRING: CS121 SNMP/WEB Adapter
UPS-MIB::upsIdentAttachedDevices.0 = STRING: UPS protected devices
UPS-MIB::upsBatteryStatus.0 = INTEGER: batteryNormal(2)
UPS-MIB::upsSecondsOnBattery.0 = INTEGER: 0 seconds
UPS-MIB::upsEstimatedMinutesRemaining.0 = INTEGER: 95 minutes
UPS-MIB::upsEstimatedChargeRemaining.0 = INTEGER: 100 percent
UPS-MIB::upsBatteryVoltage.0 = INTEGER: 824 0.1 Volt DC
UPS-MIB::upsBatteryCurrent.0 = INTEGER: 0 0.1 Amp DC
UPS-MIB::upsBatteryTemperature.0 = INTEGER: 51 degrees Centigrade
UPS-MIB::upsInputLineBads.0 = Counter32: 0
UPS-MIB::upsInputNumLines.0 = INTEGER: 1
UPS-MIB::upsInputLineIndex.1 = INTEGER: 1
UPS-MIB::upsInputFrequency.1 = INTEGER: 499 0.1 Hertz
UPS-MIB::upsInputVoltage.1 = INTEGER: 229 RMS Volts
UPS-MIB::upsInputCurrent.1 = INTEGER: 0 0.1 RMS Amp
UPS-MIB::upsInputTruePower.1 = INTEGER: 0 Watts
UPS-MIB::upsOutputSource.0 = INTEGER: normal(3)
UPS-MIB::upsOutputFrequency.0 = INTEGER: 0 0.1 Hertz
UPS-MIB::upsOutputNumLines.0 = INTEGER: 1
UPS-MIB::upsOutputLineIndex.1 = INTEGER: 1
UPS-MIB::upsOutputVoltage.1 = INTEGER: 230 RMS Volts
UPS-MIB::upsOutputCurrent.1 = INTEGER: 0 0.1 RMS Amp
UPS-MIB::upsOutputPower.1 = INTEGER: 540 Watts
UPS-MIB::upsOutputPercentLoad.1 = INTEGER: 18 percent
UPS-MIB::upsBypassFrequency.0 = INTEGER: 0 0.1 Hertz
UPS-MIB::upsBypassNumLines.0 = INTEGER: 1
UPS-MIB::upsBypassLineIndex.1 = INTEGER: 1
UPS-MIB::upsBypassVoltage.1 = INTEGER: 0 RMS Volts
UPS-MIB::upsBypassCurrent.1 = INTEGER: 0 0.1 RMS Amp
UPS-MIB::upsBypassPower.1 = INTEGER: 0 Watts
UPS-MIB::upsAlarmsPresent.0 = Gauge32: 0
UPS-MIB::upsTestId.0 = OID: UPS-MIB::upsTestNoTestsInitiated
UPS-MIB::upsTestSpinLock.0 = INTEGER: 1
UPS-MIB::upsTestResultsSummary.0 = INTEGER: noTestsInitiated(6)
UPS-MIB::upsTestResultsDetail.0 = STRING: No test initiated.
UPS-MIB::upsTestStartTime.0 = Timeticks: (0) 0:00:00.00
UPS-MIB::upsTestElapsedTime.0 = INTEGER: 0
UPS-MIB::upsShutdownType.0 = INTEGER: system(2)
UPS-MIB::upsShutdownAfterDelay.0 = INTEGER: -1 seconds
UPS-MIB::upsStartupAfterDelay.0 = INTEGER: -1 seconds
UPS-MIB::upsRebootWithDuration.0 = INTEGER: -1 seconds
UPS-MIB::upsAutoRestart.0 = INTEGER: on(1)
UPS-MIB::upsControl.6.0 = INTEGER: 0
UPS-MIB::upsControl.7.0 = ""
UPS-MIB::upsConfigInputVoltage.0 = INTEGER: 0 RMS Volts
UPS-MIB::upsConfigInputFreq.0 = INTEGER: 0 0.1 Hertz
UPS-MIB::upsConfigOutputVoltage.0 = INTEGER: 0 RMS Volts
UPS-MIB::upsConfigOutputFreq.0 = INTEGER: 0 0.1 Hertz
UPS-MIB::upsConfigOutputVA.0 = INTEGER: 0 Volt-Amps
UPS-MIB::upsConfigOutputPower.0 = INTEGER: 0 Watts
UPS-MIB::upsConfigLowBattTime.0 = INTEGER: 0 minutes
UPS-MIB::upsConfigAudibleStatus.0 = INTEGER: 0
UPS-MIB::upsConfigLowVoltageTransferPoint.0 = INTEGER: 0 RMS Volts
UPS-MIB::upsConfigHighVoltageTransferPoint.0 = INTEGER: 0 RMS Volts
UPS-MIB::upsObjects.10.1.1.0 = INTEGER: 0
UPS-MIB::upsObjects.10.1.2.0 = INTEGER: 0
UPS-MIB::upsObjects.10.1.3.0 = INTEGER: 0
UPS-MIB::upsObjects.10.1.4.0 = INTEGER: 0
UPS-MIB::upsObjects.10.1.5.0 = INTEGER: 0
UPS-MIB::upsObjects.10.1.6.0 = INTEGER: 0
UPS-MIB::upsObjects.10.1.7.0 = INTEGER: 0
UPS-MIB::upsObjects.10.1.8.0 = INTEGER: 0
UPS-MIB::upsObjects.10.2.1.0 = INTEGER: 0
UPS-MIB::upsObjects.10.2.2.0 = INTEGER: 0
UPS-MIB::upsObjects.10.2.3.0 = INTEGER: 0
UPS-MIB::upsObjects.10.2.4.0 = INTEGER: 0
UPS-MIB::upsObjects.10.2.5.0 = INTEGER: 0
UPS-MIB::upsObjects.10.2.6.0 = INTEGER: 0
UPS-MIB::upsObjects.10.2.7.0 = INTEGER: 0
UPS-MIB::upsObjects.10.2.8.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.1.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.2.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.3.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.4.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.5.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.6.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.7.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.8.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.9.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.10.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.11.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.12.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.13.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.14.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.15.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.16.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.17.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.18.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.19.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.20.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.21.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.22.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.23.0 = INTEGER: 0
UPS-MIB::upsObjects.10.3.24.0 = INTEGER: 0
UPS-MIB::upsObjects.10.4.1.0 = INTEGER: 0
UPS-MIB::upsObjects.10.4.2.0 = INTEGER: 0
UPS-MIB::upsObjects.10.4.3.0 = INTEGER: 0
UPS-MIB::upsObjects.10.4.4.0 = INTEGER: 0
UPS-MIB::upsObjects.10.4.5.0 = INTEGER: 0
UPS-MIB::upsObjects.10.4.6.0 = INTEGER: 0
UPS-MIB::upsObjects.10.4.7.0 = INTEGER: 0
UPS-MIB::upsObjects.10.4.8.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.1.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.2.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.3.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.4.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.5.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.6.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.7.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.8.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.9.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.10.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.11.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.12.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.13.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.14.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.15.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.16.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.17.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.18.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.19.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.20.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.21.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.22.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.23.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.24.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.25.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.26.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.27.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.28.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.29.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.30.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.31.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.32.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.33.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.34.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.35.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.36.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.37.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.38.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.39.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.40.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.41.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.42.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.43.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.44.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.45.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.46.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.47.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.48.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.49.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.50.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.51.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.52.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.53.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.54.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.55.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.56.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.57.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.58.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.59.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.60.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.61.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.62.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.63.0 = INTEGER: 0
UPS-MIB::upsObjects.10.5.64.0 = INTEGER: 0
UPS-MIB::upsObjects.11.1.0 = INTEGER: 0
UPS-MIB::upsObjects.11.2.0 = INTEGER: 0
UPS-MIB::upsObjects.11.3.0 = INTEGER: 0
UPS-MIB::upsObjects.11.4.0 = INTEGER: 0
UPS-MIB::upsObjects.12.1.1.0 = INTEGER: 0
UPS-MIB::upsObjects.12.1.2.0 = STRING: "Temp. Sensor 1"
UPS-MIB::upsObjects.12.1.3.0 = STRING: "Degree Celsius"
UPS-MIB::upsObjects.12.1.4.0 = INTEGER: 0
UPS-MIB::upsObjects.12.1.5.0 = INTEGER: 1000
UPS-MIB::upsObjects.12.1.6.0 = INTEGER: 255
UPS-MIB::upsObjects.12.1.7.0 = INTEGER: 0
UPS-MIB::upsObjects.12.2.1.0 = INTEGER: 0
UPS-MIB::upsObjects.12.2.2.0 = STRING: "Temp. Sensor 2"
UPS-MIB::upsObjects.12.2.3.0 = STRING: "Degree Celsius"
UPS-MIB::upsObjects.12.2.4.0 = INTEGER: 0
UPS-MIB::upsObjects.12.2.5.0 = INTEGER: 1000
UPS-MIB::upsObjects.12.2.6.0 = INTEGER: 255
UPS-MIB::upsObjects.12.2.7.0 = INTEGER: 0
UPS-MIB::upsObjects.12.3.1.0 = INTEGER: 0
UPS-MIB::upsObjects.12.3.2.0 = STRING: "Temp. Sensor 3"
UPS-MIB::upsObjects.12.3.3.0 = STRING: "Degree Celsius"
UPS-MIB::upsObjects.12.3.4.0 = INTEGER: 1000
UPS-MIB::upsObjects.12.3.5.0 = INTEGER: 0
UPS-MIB::upsObjects.12.3.6.0 = INTEGER: 255
UPS-MIB::upsObjects.12.3.7.0 = INTEGER: 0
UPS-MIB::upsObjects.12.4.1.0 = INTEGER: 0
UPS-MIB::upsObjects.12.4.2.0 = STRING: "Temp. Sensor 4"
UPS-MIB::upsObjects.12.4.3.0 = STRING: "Degree Celsius"
UPS-MIB::upsObjects.12.4.4.0 = INTEGER: 1000
UPS-MIB::upsObjects.12.4.5.0 = INTEGER: 0
UPS-MIB::upsObjects.12.4.6.0 = INTEGER: 255
UPS-MIB::upsObjects.12.4.7.0 = INTEGER: 0
UPS-MIB::upsObjects.12.5.1.0 = INTEGER: 0
UPS-MIB::upsObjects.12.5.2.0 = STRING: "Temp. Sensor 5"
UPS-MIB::upsObjects.12.5.3.0 = STRING: "Degree Celsius"
UPS-MIB::upsObjects.12.5.4.0 = INTEGER: 0
UPS-MIB::upsObjects.12.5.5.0 = INTEGER: 1000
UPS-MIB::upsObjects.12.5.6.0 = INTEGER: 255
UPS-MIB::upsObjects.12.5.7.0 = INTEGER: 0
UPS-MIB::upsObjects.12.6.1.0 = INTEGER: 0
UPS-MIB::upsObjects.12.6.2.0 = STRING: "Temp. Sensor 6"
UPS-MIB::upsObjects.12.6.3.0 = STRING: "Degree Celsius"
UPS-MIB::upsObjects.12.6.4.0 = INTEGER: 0
UPS-MIB::upsObjects.12.6.5.0 = INTEGER: 1000
UPS-MIB::upsObjects.12.6.6.0 = INTEGER: 255
UPS-MIB::upsObjects.12.6.7.0 = INTEGER: 0
UPS-MIB::upsObjects.12.7.1.0 = INTEGER: 0
UPS-MIB::upsObjects.12.7.2.0 = STRING: "Temp. Sensor 7"
UPS-MIB::upsObjects.12.7.3.0 = STRING: "Degree Celsius"
UPS-MIB::upsObjects.12.7.4.0 = INTEGER: 1000
UPS-MIB::upsObjects.12.7.5.0 = INTEGER: 0
UPS-MIB::upsObjects.12.7.6.0 = INTEGER: 255
UPS-MIB::upsObjects.12.7.7.0 = INTEGER: 0
UPS-MIB::upsObjects.12.8.1.0 = INTEGER: 0
UPS-MIB::upsObjects.12.8.2.0 = STRING: "Temp. Sensor 8"
UPS-MIB::upsObjects.12.8.3.0 = STRING: "Degree Celsius"
UPS-MIB::upsObjects.12.8.4.0 = INTEGER: 1000
UPS-MIB::upsObjects.12.8.5.0 = INTEGER: 0
UPS-MIB::upsObjects.12.8.6.0 = INTEGER: 255
UPS-MIB::upsObjects.12.8.7.0 = INTEGER: 0
UPS-MIB::upsObjects.12.9.1.0 = INTEGER: 0
UPS-MIB::upsObjects.12.9.2.0 = STRING: "Digital Input 1"
UPS-MIB::upsObjects.12.9.3.0 = INTEGER: 0
UPS-MIB::upsObjects.12.10.1.0 = INTEGER: 0
UPS-MIB::upsObjects.12.10.2.0 = STRING: "Digital Input 2"
UPS-MIB::upsObjects.12.10.3.0 = INTEGER: 0
UPS-MIB::upsObjects.12.11.1.0 = INTEGER: 0
UPS-MIB::upsObjects.12.11.2.0 = STRING: "Digital Input 3"
UPS-MIB::upsObjects.12.11.3.0 = INTEGER: 0
UPS-MIB::upsObjects.12.12.1.0 = INTEGER: 0
UPS-MIB::upsObjects.12.12.2.0 = STRING: "Digital Input 4"
UPS-MIB::upsObjects.12.12.3.0 = INTEGER: 0
UPS-MIB::upsObjects.12.13.1.0 = INTEGER: 0
UPS-MIB::upsObjects.12.13.2.0 = STRING: "Digital Output 1"
UPS-MIB::upsObjects.12.13.3.0 = INTEGER: 0
UPS-MIB::upsObjects.12.14.1.0 = INTEGER: 0
UPS-MIB::upsObjects.12.14.2.0 = STRING: "Digital Output 2"
UPS-MIB::upsObjects.12.14.3.0 = INTEGER: 0
UPS-MIB::upsObjects.12.15.1.0 = INTEGER: 0
UPS-MIB::upsObjects.12.15.2.0 = STRING: "Digital Output 3"
UPS-MIB::upsObjects.12.15.3.0 = INTEGER: 0
UPS-MIB::upsObjects.12.16.1.0 = INTEGER: 0
UPS-MIB::upsObjects.12.16.2.0 = STRING: "Digital Output 4"
UPS-MIB::upsObjects.12.16.3.0 = INTEGER: 0
UPS-MIB::upsObjects.13.1.0 = INTEGER: 0
UPS-MIB::upsObjects.13.2.0 = INTEGER: 0
UPS-MIB::upsObjects.13.3.0 = INTEGER: 0
UPS-MIB::upsObjects.13.4.0 = INTEGER: 0
UPS-MIB::upsObjects.13.5.0 = INTEGER: 0
UPS-MIB::upsObjects.13.6.0 = INTEGER: 0
UPS-MIB::upsObjects.13.7.0 = INTEGER: 0
UPS-MIB::upsObjects.13.8.0 = INTEGER: 0
UPS-MIB::upsObjects.13.9.0 = INTEGER: 0
UPS-MIB::upsObjects.13.9.0 = No more variables left in this MIB View (It is past the end of the MIB tree)

**Comment by laf** [comment]
Hi @vitalisator. This PR is a good starting point: https://github.com/librenms/librenms/pull/888/files

It contains a bit more than you need as it also contained the initial code to get load supported.

Basically you want a discovery file in includes/discovery/X/ where X = temperature, load, etc.

Any further questions, just ask.

**Comment by vitalisator** [comment]
works with rfc1628 part.
