### ISSUE TITLE
Aruba InstantOn 1930 Switch

### ISSUE THREAD

**Issue by mzac** [librenms/librenms#12177]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Please keep in mind that LibreNMS is a community project, it is run by people like you using their free time.
Which means it may take time before support is added to LibreNMS.

We encourage you to do it yourself and submit it in GitHub as a Pull request. It is not so difficult, most of
it can be done without writing a single line of code. You can find the documentation below :
👉  https://docs.librenms.org/Developing/os/Initial-Detection/

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

This if for Aruba's new line of InstantOn 1930 switches.  Currently, LibreNMS only picks up the interfaces and general info but none of the CPU, Memory, Temperature, POE graphs.

https://www.arubainstanton.com/files/DS_AIO_1930SwitchSeries.pdf

Discovery: https://p.libren.ms/view/b886cf78
Poller: https://p.libren.ms/view/f570f147
SNMP Walk: https://p.libren.ms/view/c73414b2

Mibs: https://community.arubainstanton.com/ehvxd43934/attachments/ehvxd43934/InstantOnSoftware/1/3/1930_MIBS_1.0.1.116.zip

**Comment by PipoCanaja** [comment]
Hello,
Without the snmpwalk, nothing can be done to help you. Please reopen this issue when you can provide it. 
Thanx

**Comment by mzac** [comment]
Here is the snmpwalk, I was having some issues with it at first...

https://p.libren.ms/view/c73414b2#L17

**Comment by Jellyfrog** [comment]
Add here instead; https://community.librenms.org/c/device-requests/12
