### ISSUE TITLE
Install instructions state 7.2 install check errors that 7.3 is needed

### ISSUE THREAD

**Issue by shanedizer** [librenms/librenms#12175]
following: https://docs.librenms.org/Installation/Installation-Ubuntu-1804-Nginx/ has you install the following packages:

php7.2-cli php7.2-curl php7.2-fpm php7.2-gd php7.2-json php7.2-mbstring php7.2-mysql php7.2-snmp php7.2-xml php7.2-zip python-memcache python-mysqldb rrdtool snmp snmpd whois unzip python3-pip

However, once installed & configured libre issues an error on install that php 7.3 or newer is needed. The below happens when you navigate to http://librenms.example.com/install/checks

![image](https://user-images.githubusercontent.com/45395906/94729141-43286880-032f-11eb-8068-127b28ab22aa.png)

**Comment by murrant** [comment]
It is true that only 7.2 is required.  The minimum version has been bumped as an early warning that 7.3 will be required soon.
Probably someone needs to review the install docs to reflect this.

**Comment by shanedizer** [comment]
Thanks @murrant  Is there a way i can get past the install checks, since the app should function normally?

**Comment by murrant** [comment]
Unless you want to re-do your install in a month, I suggest installing PHP 7.3 :p

**Comment by murrant** [comment]
otherwise, you can edit LibreNMS/Validations/Php.php to temporarily allow a lower version.
