### ISSUE TITLE
Docs rendering issue (General/Changelog)

### ISSUE THREAD

**Issue by candlerb** [librenms/librenms#12198]
To reproduce:
* Go to https://docs.librenms.org/
* Click on "General"
* Click on "Changelog"

This takes you to <https://docs.librenms.org/General/Changelog.md> but the rendering is incredibly funky: massive icons, each one as big as the whole screen.  Then after scrolling through screens and screens of this, right at the bottom, there's a 404.

![image](https://user-images.githubusercontent.com/44789/95197496-9851f780-07d1-11eb-8617-89d3e13f33bc.png)

Tested using Chrome, Firefox and Safari under macOS - same results.

Also: I note that in the LibreNMS repo, [CHANGELOG.md](https://github.com/librenms/librenms/blob/master/CHANGELOG.md) links to a different URL which is <https://docs.librenms.org/#General/Changelog/>.  But that link just shows the top-level docs site.

WORKAROUND: go to https://github.com/librenms/librenms/blob/master/doc/General/Changelog.md

**Comment by murrant** [comment]
known issue, just happened :)

**Comment by candlerb** [comment]
OK, I was unlucky with my timing :-)

**Comment by murrant** [comment]
Yep, it is back now :)  Thanks for the heads up though.

**Comment by candlerb** [comment]
Great.  I do think the link in [CHANGELOG.md](https://github.com/librenms/librenms/blob/master/CHANGELOG.md) points to the wrong place, it should have the '#' removed.
