### ISSUE TITLE
Defective poller.php for OKI printers.

### ISSUE THREAD

**Issue by MilanVolf** [librenms/librenms#12207]
Hi, please repair OKI printers.

Pooler.php does not work on OKI printers.

When starting manually, we throw an error:

`#### Load poller module os ####

In okilan.inc.php line 4:

  require(): Failed opening required 'includes/polling/os/jetdirect.inc.php' (include_path='.:/usr/local/share/pear')`

File in librenms at location: includes / polling / os / jetdirect.inc.php
It really does not exist, not even in the official distribution on the net.

Thank you.

**Comment by murrant** [comment]
Looks like we don't have any test data for those devices, can you send some?

As the librenms user, make sure you replace <HOSTNAME> with the hostname of the device
```
./scripts/github-apply 12213
./scripts/collect-snmp-data.php -v 2 -h <HOSTNAME>
./scripts/github-remove -d
```

Then attach the generated tests/snmpsim/okilan-2.snmprec file here.

**Comment by MilanVolf** [comment]
Good day,

I attached the generated file to an attachment.

[okilan_1.zip](https://github.com/librenms/librenms/files/5385638/okilan_1.zip)

How will we continue?

Thank you.

Command output:

OS: okilan
Module(s): all
Variant: 1

Capturing Data:  sysDescr.0 sysObjectID.0 sysName.0 sysLocation.0 .1.3.6.1.4.1.11.2.3.9.1.1.7.0 ifDescr ifName ifAlias ifType ifOperStatus ifStackStatus entPhysicalEntry hrProcessorLoad .1.3.6.1.4.1.2021.11.11.0 dellNetCpuUtilTable DellNetProcessorEntry FORTINET-FORTIAUTHENTICATOR-MIB::facSysMemUsage.0 FORTINET-FORTISANDBOX-MIB::fsaSysMemUsage.0 hpLocal hpGlobal hrStorageEntry ipAdEntIfIndex ipAdEntNetMask.10.10.104.125 ipAddressIfIndex.ipv6 ipv6AddrPfxLength IP-FORWARD-MIB::inetCidrRouteNumber.0 inetCidrRouteNumber.0 ipCidrRouteNumber.0 .1.3.6.1.2.1.4.21 mplsL3VpnVrfPerfCurrNumRoutes mplsL3VpnVrfRteTable entPhysicalDescr hrDeviceStatus.1 hrPrinterDetectedErrorState.1 aixFsTableEntry fileSystemSpaceTable datasetTable zpoolTable dskTable hrDeviceEntry hrProcessorEntry cdpCache lldpRemTable ipNetToPhysicalPhysAddress ipNetToMediaPhysAddress bgpLocalAs bgpPeerRemoteAs dot1dBasePortIfIndex dot1qVlanVersionNumber.0 prtMarkerSuppliesLevel prtMarkerSuppliesType prtMarkerSuppliesMaxCapacity prtMarkerSuppliesDescription prtInputName prtInputCurrentLevel prtInputMaxCapacity diskIOEntry dot1dStpProtocolSpecification.0 dot1qTpFdbPort dot1dTpFdbPort sysUpTime.0 sysContact.0 snmpEngineTime.0 hrSystemUptime.0 .1.3.6.1.2.1.25.3.2.1.5.1 .1.3.6.1.2.1.25.3.5.1.2.1 hrMemorySize.0 icmp ipForwDatagrams ipInDelivers ipInReceives ipOutRequests ipInDiscards ipOutDiscards ipOutNoRoutes ipReasmReqds ipReasmOKs ipReasmFails ipFragOKs ipFragFails ipFragCreates ipInUnknownProtos ipInHdrErrors ipInAddrErrors IP-FORWARD-MIB::ipCidrRouteNumber.0 snmp tcpActiveOpens tcpPassiveOpens tcpAttemptFails tcpEstabResets tcpCurrEstab tcpInSegs tcpOutSegs tcpRetransSegs tcpInErrs tcpOutRsts tcpHCInSegs.0 tcpHCOutSegs.0 udpInDatagrams udpOutDatagrams udpInErrors udpNoPorts hrSystemProcesses.0 hrSystemNumUsers.0 systemStats memTotalSwap.0 memAvailSwap.0 memTotalReal.0 memAvailReal.0 memTotalFree.0 memShared.0 memBuffer.0 memCached.0 laLoadInt.1 laLoadInt.2 laLoadInt.3 ipSystemStats ifXEntry ifEntry dot3StatsIndex dot3StatsDuplexStatus dot1qPvid .1.3.6.1.2.1.43.11.1.1.9.1.1 .1.3.6.1.2.1.43.11.1.1.9.1.2 .1.3.6.1.2.1.43.11.1.1.9.1.3 .1.3.6.1.2.1.43.11.1.1.9.1.4 .1.3.6.1.2.1.43.11.1.1.9.1.5 .1.3.6.1.2.1.43.11.1.1.9.1.6 .1.3.6.1.2.1.43.11.1.1.9.1.7 .1.3.6.1.2.1.43.11.1.1.9.1.8 .1.3.6.1.2.1.43.11.1.1.9.1.9 .1.3.6.1.2.1.43.11.1.1.9.1.10 .1.3.6.1.2.1.43.8.2.1.10.1.1 .1.3.6.1.2.1.43.8.2.1.10.1.2 .1.3.6.1.2.1.43.8.2.1.10.1.3

./tests/snmpsim/okilan_1.snmprec
