### ISSUE TITLE
"Sub-directory Support" does not accept top-level (root) URL

### ISSUE THREAD

**Issue by candlerb** [librenms/librenms#12205]
Summary: when configured following the sub-directory support instructions, paths like `/librenms/devices` and `/librenms/validate` work fine, but the top level path `/librenms/` gives a 404 error.

To reproduce:

* I created a fresh Ubuntu 20.04 lxd container
* I installed LibreNMS git head (2793585c) exactly as per the [Install-LibreNMS](https://docs.librenms.org/Installation/Install-LibreNMS/) page, using Apache rather than Nginx.
* I went through the database setup pages, then validate, then added `localhost` device.  LibreNMS is working fine at this point.
* I then modified the configuration as per [Sub-directory Support](https://docs.librenms.org/Extensions/Sub-Directory/)

```
--- /etc/apache2/sites-available/librenms.conf.old	2020-10-11 17:40:42.714705144 +0000
+++ /etc/apache2/sites-available/librenms.conf	2020-10-11 17:47:59.622870362 +0000
@@ -1,8 +1,10 @@
+AllowEncodedSlashes On
+Alias /librenms /opt/librenms/html
+
 <VirtualHost *:80>
   DocumentRoot /opt/librenms/html/
   ServerName  librenms.example.com

-  AllowEncodedSlashes NoDecode
   <Directory "/opt/librenms/html/">
     Require all granted
     AllowOverride All
```

```
--- /opt/librenms/html/.htaccess.old	2020-10-11 17:45:44.213581077 +0000
+++ /opt/librenms/html/.htaccess	2020-10-11 17:45:51.393649471 +0000
@@ -20,7 +20,7 @@
 </IfModule>

 RewriteEngine on
-RewriteBase /
+RewriteBase /librenms
 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteCond %{REQUEST_URI} !\.(js|ico|txt|gif|jpg|png|css|php)
```

```
--- /opt/librenms/.env.old	2020-10-11 17:45:25.301400911 +0000
+++ /opt/librenms/.env	2020-10-11 17:45:58.561717747 +0000
@@ -5,5 +5,5 @@
 DB_USERNAME=librenms
 DB_PASSWORD=password

-#APP_URL=
+APP_URL=/librenms/
 NODE_ID=5f83401f8b0fa
```

```
--- /opt/librenms/config.php.old	2020-10-11 17:44:58.193142622 +0000
+++ /opt/librenms/config.php	2020-10-11 17:46:05.021779276 +0000
@@ -8,7 +8,7 @@

 ### This should *only* be set if you want to *force* a particular hostname/port
 ### It will prevent the web interface being usable form any other hostname
-#$config['base_url']        = "/";
+$config["base_url"] = '/librenms/';

 ### Enable this to use rrdcached. Be sure rrd_dir is within the rrdcached dir
 ### and that your web server has permission to talk to rrdcached.
```

```
systemctl restart apache2
systemctl restart php7.4-fpm
```

Now go to path `/librenms/validate` and it's fine:

![image](https://user-images.githubusercontent.com/44789/95685882-8ff32580-0bf2-11eb-8da1-351b49dcf226.png)

But go to path `/librenms/` and it gives a 404 error:

![image](https://user-images.githubusercontent.com/44789/95685897-a4372280-0bf2-11eb-95bf-cd17e7e72f25.png)

Note that the LibreNMS logo in the top left-hand corner of the screen links to `/librenms/`

![image](https://user-images.githubusercontent.com/44789/95686002-2b849600-0bf3-11eb-8f2a-ac00156c114a.png)

**Comment by murrant** [comment]
Would love to hear how to make subdirectory support work.

**Comment by candlerb** [comment]
I have this as a temporary workaround:

```
<LocationMatch "^/librenms/$">
  Redirect /librenms/overview
</LocationMatch>
```

**Comment by candlerb** [comment]
There are some additional issues with sub-directory support in the oxidized page (although I'm testing with libreNMS 1.68 now instead of HEAD).  To reproduce, go to `/librenms/oxidized`.

1. The device links point to `/device/device=N`, missing the `/librenms/` prefix

    ![image](https://user-images.githubusercontent.com/44789/95767654-fccaf600-0cac-11eb-9829-1e3e972c0a66.png)

2. The "Oxidized config validation" link points to `/librenms/librenms/tools/tool=oxidized-cfg-check/`, doubling up the `/librenms/` prefix

    ![image](https://user-images.githubusercontent.com/44789/95767793-2d129480-0cad-11eb-87ee-78683bbfc20e.png)

**Comment by CrossEyeORG** [comment]
I had for years the sub-directory / URI support working but after this mentioned forum post it has since stopped working.

https://community.librenms.org/t/404-not-found-on-virtual-host/12771

Definitely am looking forward to the fix!

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/404-not-found-on-virtual-host/12771/27

**Comment by candlerb** [comment]
Thanks for the forum link.  FWIW, previously I was using LibreNMS 1.64.1 and it worked then.

**Comment by murrant** [comment]
I don't think any of the devs use a subdirectory in their production or dev systems.  I tried to set it up, but I have no idea how subdirectory is supposed to be configured in the webserver, so I don't know if I have it misconfigured webserver or am fighting issues in LibreNMS...

**Comment by candlerb** [comment]
I gave an Apache example above which was a minimal change to the default configuration, but here is a more realistic one:

```
# https://docs.librenms.org/Extensions/Sub-Directory/
AllowEncodedSlashes NoDecode
Alias /librenms /opt/librenms/html

<Directory "/opt/librenms/html/">
  Require all granted
  AllowOverride All
  Options FollowSymLinks MultiViews
</Directory>

<LocationMatch "^/librenms/.*\.php">
  SetEnvIfNoCase ^Authorization$ "(.+)" HTTP_AUTHORIZATION=$1
  SetHandler "proxy:unix:/run/php-fpm-librenms.sock|fcgi://localhost"
</LocationMatch>

# Workaround for https://github.com/librenms/librenms/issues/12205
<LocationMatch "^/librenms/$">
  Redirect /librenms/overview
</LocationMatch>
```

This allows allows other PHP apps which are not under `/librenms/` to use mod_php as normal.  It also includes the workaround to redirect `/librenms/` to `/librenms/overview`, and that's the part I'd like to get rid of if the underlying routing issue can be fixed.

The other config changes required are to `config.php`, `.env` and `html/.htaccess`, all documented in [Extensions/Sub-Directory](https://docs.librenms.org/Extensions/Sub-Directory/)

**Comment by arrmo** [comment]
> It also includes the workaround to redirect `/librenms/` to `/librenms/overview`, and that's the part I'd like to get rid of if the underlying routing issue can be fixed.

Having the same issue here - it's what breaks using the logo / icon in the upper left corner ... agreed?

Thanks!

**Comment by candlerb** [comment]
Yes, the logo is visible, but clicking on it takes you to `/librenms/` which gives a 404 error.

**Comment by arrmo** [comment]
Yep, same issue I noted here,
https://community.librenms.org/t/dashboard-home-site-issues-using-sub-directory/13044

Glad I'm not completely crazy ... LOL!

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/dashboard-home-site-issues-using-sub-directory/13044/24

**Comment by arrmo** [comment]
```
# Workaround for https://github.com/librenms/librenms/issues/12205
<LocationMatch "^/librenms/$">
  Redirect /librenms/overview
</LocationMatch>
```

This works perfectly, thanks!


> <LocationMatch "^/librenms/.*\.php">
>   SetEnvIfNoCase ^Authorization$ "(.+)" HTTP_AUTHORIZATION=$1
>   SetHandler "proxy:unix:/run/php-fpm-librenms.sock|fcgi://localhost"
> </LocationMatch>

OK, this part doesn't - for me at least 😆

**Comment by murrant** [comment]
Still need someone to come up with the correct fix instead of a workaround.

**Comment by f0o** [comment]
Is this exclusive to Apache setups?

**Comment by mpikzink** [comment]
Hi I could fix it with this Route in the beginning, but I am not a pro in Laravel:

diff --git a/includes/html/print-date-selector.inc.php b/includes/html/print-date-selector.inc.php
--- a/routes/web.php
+++ b/routes/web.php
@@ -14,6 +14,8 @@
// Auth
Auth::routes(['register' => false, 'reset' => false, 'verify' => false]);

+Route::get('/', 'OverviewController@index')->name('home');
+
// WebUI

**Comment by ThomasCr** [comment]
I temporaly fix the double routing (/librenms/librenms/....) with the following htaccess entry after `RewriteBase...`

`RewriteRule ^librenms/(.*)$ /librenms/$1 [R,L,NC]`

But your fix don't work for me (see PR) and yes, I removed my RewriteRule for testing.

**Comment by mpikzink** [comment]
You are right. I see I have a different config then from the doc.

`$config["base_url"] = 'https://servername.domain.de/librenms/';`

After a change to /librenms/ I have the same problems again! :-(

**Comment by Compizfox** [comment]
Same problem here (with identical to @candlerb).

@mpikzink's workaround of specifying the fully-qualified base URL fixes the double `/librenms/librenms/` URLs, but the root URL still 404s.

**Comment by dlehman83** [comment]
The pull request and rewrite rule work about the same for me.  
The base url /librenms gives 404.  
The double librenms when trying to work with items is fixed.  
One of the issues I've been having is changing the time range of a graph.  I'd get 404 double librenms after clicking update..  

It is progress.

**Comment by tomasrojas26** [comment]
I have a dedicated VM (clean install, no plugins, no addons, just localhost configured) just to test the sub-directory functionality.

So far this is my actual config (but I still have problems):

**/etc/apache2/conf-available/librenms.conf**

```
Alias /librenms /usr/local/librenms/html

AllowEncodedSlashes On
  <Directory "/usr/local/librenms/html">
    Require all granted
    AllowOverride All
    Options FollowSymLinks MultiViews
  </Directory>

  # Enable http authorization headers
  <LocationMatch "^/librenms/.*\.php">
    SetEnvIfNoCase ^Authorization$ "(.+)" HTTP_AUTHORIZATION=$1
    SetHandler "proxy:unix:/run/php-fpm-librenms.sock|fcgi://localhost"
  </LocationMatch>

  # Workaround for bad homepage resolution after login - https://github.com/librenms/librenms/issues/12205
  <LocationMatch "^/librenms/$">
    Redirect /librenms/overview
  </LocationMatch>
```

**/usr/local/librenms/html/.htaccess**

```
RewriteBase /librenms
# Workaround for double routing
RewriteRule ^librenms/(.*)$ /librenms/$1 [R,L,NC]
```

**/usr/local/librenms/.env**

```
APP_URL=/librenms/
```

**/usr/local/librenms/config.php**

```
$config["base_url"] = '/librenms/';
```

Now I found problems in Health module:

**Processor**
![image](https://user-images.githubusercontent.com/3728074/114583873-6a55e000-9c58-11eb-9d2b-5410d59a10b8.png)

**Storage**
![image](https://user-images.githubusercontent.com/3728074/114584236-d46e8500-9c58-11eb-8ffe-2af495dfed3c.png)

**Memory (it works just fine)**
![image](https://user-images.githubusercontent.com/3728074/114585175-be14f900-9c59-11eb-9175-bb7f46a51375.png)

Also I found problems in Alert Log module:

![image](https://user-images.githubusercontent.com/3728074/114586304-e4876400-9c5a-11eb-9cb3-0e7ce4ee582a.png)

Please add information to this thread if anyone solve this problems.

Thank you!

**Comment by arrmo** [comment]
FYI, here is the patch I have been using - does this work for you?
```
diff --git a/LibreNMS/Util/Url.php b/LibreNMS/Util/Url.php
index 6bf4294e5..d0ce58048 100644
--- a/LibreNMS/Util/Url.php
+++ b/LibreNMS/Util/Url.php
@@ -225,13 +225,14 @@ class Url
      */
     public static function deviceUrl($device, $vars = [])
     {
-        $routeParams = [is_int($device) ? $device : $device->device_id];
+/*        $routeParams = [is_int($device) ? $device : $device->device_id];
         if (isset($vars['tab'])) {
             $routeParams[] = $vars['tab'];
             unset($vars['tab']);
         }
-
-        return route('device', $routeParams) . self::urlParams($vars);
+ */
+       return self::generate(['page' => 'device', 'device' => is_int($device) ? $device : $device->device_id], $vars);
+//        return route('device', $routeParams) . self::urlParams($vars);
     }

     public static function portUrl($port, $vars = [])
```

Thanks!

**Comment by mpikzink** [comment]
Still on it

**Comment by arrmo** [comment]
> I have this as a temporary workaround:
> 
> ```
> <LocationMatch "^/librenms/$">
>   Redirect /librenms/overview
> </LocationMatch>
> ```

FYI, still seems this workaround is needed - or is it just me?

Thanks!

**Comment by murrant** [comment]
@mpikzink it was auto-closed by your tags on the PR :)
