### ISSUE TITLE
When selecting which columns to view in 'Devices', some column names are blank

### ISSUE THREAD

**Issue by giladhinberger** [librenms/librenms#12245]
Hi,

When I select the customize view (which columns to view) in 'Devices', some column names are black.
The same happened with all the sub-menus under 'Health'.

A links to some screenshots:
Devices: https://ibb.co/th89zqX
Health, Temperature: https://ibb.co/9szs01v

Thanks

**Comment by murrant** [comment]
Correct, those columns do not have titles.

**Comment by giladhinberger** [comment]
Don't you think it's a bit confusing? How do I know which column I'm selecting?...
Answers like this remind me the answers from Adam Armstrong, and that's the reason I left Observium and moved to LibreNMS...

Anyway, thanks
