### ISSUE TITLE
Unauthenticated graph access via IP whitelist fails

### ISSUE THREAD

**Issue by sijm** [librenms/librenms#12272]
**Problem**
Unauthenticated access to a graph via a whitelisted IP address results in an HTTP 500 error.

**Cause**
`LibreNMS/Cache/PermissionsCache.php` contains a function call to `Config::get`.
As `LibreNMS\Config` is not included, this function call fails.

**Solution**
Add the following line to `LibreNMS/Cache/PermissionsCache.php`:
> `use LibreNMS\Config;`

**Analysis**
In 4746c3f9d03e11b0d8d2a919aa1aa80697f7e753, `LibreNMS/Permissions.php` was renamed `LibreNMS/Cache/PermissionsCache.php`.
Its namespace changed from `LibreNMS` to `LibreNMS\Cache`.
As a result, `LibreNMS\Config` is out of scope.

**Comment by sijm** [comment]
`LibreNMS/DB/Eloquent.php` seems to have a similar bug.

It started using `\Config` since ad2da9fcdb2738429db4df5db3731c0d363c7ac8.
Its namespace is `LibreNMS\DB`, and `LibreNMS\Config` is not included.

Bug search oneliner:
> librenms@monitor:/opt/librenms# for i in \`rgrep Config:: LibreNMS/*/ | awk '{ print $1 }' | sort | uniq | rev | cut -c 2- | rev\`; do echo /$i; grep "use LibreNMS\\\\\\Config;" $i; echo; done

**Comment by murrant** [comment]
Thanks for the report @sijm
