### ISSUE TITLE
Support for Unifi Switch Flex

### ISSUE THREAD

**Issue by mzac** [librenms/librenms#12304]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Please keep in mind that LibreNMS is a community project, it is run by people like you using their free time.
Which means it may take time before support is added to LibreNMS.

We encourage you to do it yourself and submit it in GitHub as a Pull request. It is not so difficult, most of
it can be done without writing a single line of code. You can find the documentation below :
👉  https://docs.librenms.org/Developing/os/Initial-Detection/

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Model: 
- Ubiquiti Switch Flex - Managed Layer 2 Gigabit Switch with 802.3af PoE Support
- https://www.ui.com/unifi-switching/unifi-switch-flex/

Discovery: https://p.libren.ms/view/979fe0cd
Poller: https://p.libren.ms/view/7052641a
SNMP Bulk Walk: https://p.libren.ms/view/03039412

**Comment by mzac** [comment]
Ports do not show up in discovery/poller

![image](https://user-images.githubusercontent.com/10270879/98414890-2f68d400-204a-11eb-96b9-f2e1290fb736.png)

**Comment by murrant** [comment]
@mzac looks like you need to file a bug with Ubiquiti to fix IF-MIB support.  If you look at the snmpwalk, there is no  port infromation there to be had.
