### ISSUE TITLE
Extend LibreNMS with Galicaster Support

### ISSUE THREAD

**Issue by joseUPV** [librenms/librenms#12314]
I want to add support via SNMP extend of media devices with galicaster software.
https://wiki.teltek.es/display/Galicaster/Galicaster+project+Home

I have some scripts (I think for zabbix) to get data from video devices:
- bios_version.sh
- ledscreen_device_conected.sh
- blackboard_device_connected.sh
- list_video_devices.sh
- blackmagic_device_connected.sh
- photo_device_connected.sh
- check_network_speed.sh
- presenter_device_connected.sh
- datapath_device_connected.sh
- temperature_cpu.sh
- hard_disk_usage.sh

And I want to create one for snmp extend

extend galicaster /etc/snmp/galicaster.sh

And the integrate it in Librenms as Application

**Comment by joseUPV** [comment]
I will create a Pull request when i had coded it.

**Comment by kkrumm1** [comment]
closing for now waiting on PR
