### ISSUE TITLE
Mikrotik Wireless Interface Data

### ISSUE THREAD

**Issue by spinza** [librenms/librenms#1232]
Looking to capture more detail on wireless info from Mikrotik SNMP.  I was hoping detailed CCQ is available in Mikrotik SNMP but I see just the overall CCQ is available on each wireless interface.  We really want the CCQ on each registration table entry but that's not available in Mikrotik SNMP info.

I dump the info below.  Happy to do it.  Would need some guidance on what I need to do.

I imagine first is to start with wireless interface info only.

Wireless interfaces

```
/interface wireless print                   
Flags: X - disabled, R - running 
 0  R name="wlan" mtu=1500 mac-address=XX:XX:XX:XX:XX:XX arp=enabled 
      interface-type=Atheros AR9300 mode=ap-bridge ssid="xxx" 
      frequency=2412 band=2ghz-b/g/n channel-width=20/40mhz-ht-above 
      scan-list=default wireless-protocol=any wds-mode=disabled 
      wds-default-bridge=none wds-ignore-ssid=no bridge-mode=enabled 
      default-authentication=yes default-forwarding=yes default-ap-tx-limit=0 
      default-client-tx-limit=0 hide-ssid=no security-profile=default 
      compression=no 
```

OID Information 

```
/interface wireless print oid
 0 tx-rate=.1.3.6.1.4.1.14988.1.1.1.3.1.2.12 
   rx-rate=.1.3.6.1.4.1.14988.1.1.1.3.1.3.12 
   ssid=.1.3.6.1.4.1.14988.1.1.1.3.1.4.12 
   bssid=.1.3.6.1.4.1.14988.1.1.1.3.1.5.12 
   client-count=.1.3.6.1.4.1.14988.1.1.1.3.1.6.12 
   frequency=.1.3.6.1.4.1.14988.1.1.1.3.1.7.12 
   band=.1.3.6.1.4.1.14988.1.1.1.3.1.8.12 
   noise-floor=.1.3.6.1.4.1.14988.1.1.1.3.1.9.12 
   overall-ccq=.1.3.6.1.4.1.14988.1.1.1.3.1.10.12
```

Wireless registration table (this is a list of clients). 

```
/interface wireless registration-table print
 # INTERFACE           RADIO-NAME       MAC-ADDRESS       AP  SIGNAL... TX-RATE
 0 wlan                                 xx:xx:xx:xx:xx:xx no  -51dBm... 48.0...
 1 wlan                                 xx:xx:xx:xx:xx:xx no  -77dBm... 11.0...
```

OID

```
/interface wireless registration-table print oid
 0 signal-strength=.1.3.6.1.4.1.14988.1.1.1.2.1.3.0.4.32.34.64.141.12 
   tx-signal-strength=.1.3.6.1.4.1.14988.1.1.1.2.1.19.0.4.32.34.64.141.12 
   tx-bytes=.1.3.6.1.4.1.14988.1.1.1.2.1.4.0.4.32.34.64.141.12 
   rx-bytes=.1.3.6.1.4.1.14988.1.1.1.2.1.5.0.4.32.34.64.141.12 
   tx-packets=.1.3.6.1.4.1.14988.1.1.1.2.1.6.0.4.32.34.64.141.12 
   rx-packets=.1.3.6.1.4.1.14988.1.1.1.2.1.7.0.4.32.34.64.141.12 
   tx-rate=.1.3.6.1.4.1.14988.1.1.1.2.1.8.0.4.32.34.64.141.12 
   rx-rate=.1.3.6.1.4.1.14988.1.1.1.2.1.9.0.4.32.34.64.141.12 
   routeros-version=.1.3.6.1.4.1.14988.1.1.1.2.1.10.0.4.32.34.64.141.12 
   uptime=.1.3.6.1.4.1.14988.1.1.1.2.1.11.0.4.32.34.64.141.12 
   signal-to-noise=.1.3.6.1.4.1.14988.1.1.1.2.1.12.0.4.32.34.64.141.12 
   tx-signal-strength-ch0=.1.3.6.1.4.1.14988.1.1.1.2.1.13.0.4.32.34.64.141.12 
   signal-strength-ch0=.1.3.6.1.4.1.14988.1.1.1.2.1.14.0.4.32.34.64.141.12 
   tx-signal-strength-ch1=.1.3.6.1.4.1.14988.1.1.1.2.1.15.0.4.32.34.64.141.12 
   signal-strength-ch1=.1.3.6.1.4.1.14988.1.1.1.2.1.16.0.4.32.34.64.141.12 
   tx-signal-strength-ch2=.1.3.6.1.4.1.14988.1.1.1.2.1.17.0.4.32.34.64.141.12 
   signal-strength-ch2=.1.3.6.1.4.1.14988.1.1.1.2.1.18.0.4.32.34.64.141.12 
```

**Comment by paulgear** [comment]
It's likely that this will be covered by the MIB-based polling in #2536. On my RB2011 it shows some Mikrotik OIDs with very similar numbers (see attached screenshot).
![screenshot from 2016-01-02 17-14-54](https://cloud.githubusercontent.com/assets/107222/12074079/f9daab7e-b18b-11e5-8eae-7b539be187dd.png)

**Comment by novafire99** [comment]
Change include/pollers/wifi.inc.php mikrotik section to:

 # MikroTik RouterOS
 if ($device['os'] == 'routeros')
 {
   # Lookup the ifIndex from the database
   $wirelesscards = array();
   foreach (dbFetchRows("SELECT * FROM `ports` WHERE `device_id` = ? AND `deleted` = 0 AND `ifType` = 'ieee80211'", array($device['device_id'])) as $entry)
   {
    $wirelesscards[$entry['ifIndex']] = $entry;
   }
   foreach ($wirelesscards as $ifIndex => $wirelesscheck)
   {
       echo('Checking RouterOS Wireless clients... ifIndex = $ifIndex ');
       $wificlients1 = snmp_get($device, "1.3.6.1.4.1.14988.1.1.1.3.1.6.$ifIndex", '-OUqnv', 'MIKROTIK-MIB');
       echo(($wificlients1 +0) . " clients\n");
       unset($wirelesscards);
   }
 }

This makes detection  of number of wireless clients work properly in all my test cases i have.

**Comment by remix5** [comment]
librenms is a good program only thing it misses or that i can see is ccq and signal tabs. As far as administrating networks these fields are important to view and alert on. can this not be added to librenms as a feature to view signal and ccq and or does anyone know how to create a plugin for this so that it viewable?


thanks in advance

**Comment by spinza** [comment]
Problem is Mikrotik doesn't make this properly available via snmp.

On Fri, 08 Jul 2016, 13:58 remix5 <notifications@github.com> wrote:

> librenms is a good program only thing it misses or that i can see is ccq
> and signal tabs. As far as administrating networks these fields are
> important to view and alert on. can this not be added to librenms as a
> feature to view signal and ccq and or does anyone know how to create a
> plugin for this so that it viewable?
>
> thanks in advance
>
> —
> You are receiving this because you authored the thread.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/librenms/librenms/issues/1232#issuecomment-231341926>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADVuHm9HnrJsDoEhk8RV8p8gTNWYGf6eks5qTjtJgaJpZM4E-TOH>
> .
>
-- 
__
Louis Rossouw
+27 82 498 7214

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-mikrotik-wireless-interface-data/739
