### ISSUE TITLE
SMC TigerSwitch 1000 SMC8612XL3 aka Edge-core ES4612

### ISSUE THREAD

**Issue by freedomwarrior** [librenms/librenms#12333]
It recognized as Generic Device
discovery: https://p.libren.ms/view/d4a144e7
poller: https://p.libren.ms/view/bed73dbc
snmpbulkwalk: https://p.libren.ms/view/719b96f7

**Comment by Jellyfrog** [comment]
Add here instead; https://community.librenms.org/c/device-requests/12
