### ISSUE TITLE
Poller.php fail to run

### ISSUE THREAD

**Issue by razerrazer** [librenms/librenms#12345]
For some reason the polling are fail to run automatically since latest update.

![photo_2020-11-24_09-21-10](https://user-images.githubusercontent.com/17000974/100067442-93efa580-2e36-11eb-85db-4c853658e114.jpg)

version : 	1.69-56-g305f97161 - Tue Nov 24 2020 00:16:41 GMT+0100
Database Schema	2020_10_12_095504_mempools_add_oids (191)
Web Server	Apache/2.4.25 (Debian)
PHP	7.3.3-1+0~20190307202245.32+stretch~1.gbp32ebb2
Python	3.5.3
MySQL	10.1.44-MariaDB-0+deb9u1
Laravel	8.11.2
RRDtool	1.6.0

./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.69-56-g305f97161
DB Schema | 2020_10_12_095504_mempools_add_oids (191)
PHP       | 7.3.3-1+0~20190307202245.32+stretch~1.gbp32ebb2
Python    | 3.5.3
MySQL     | 10.1.44-MariaDB-0+deb9u1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
OpenSSL   |
====================================

[OK]    Composer Version: 2.0.7
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct

**Comment by awlx** [comment]
https://github.com/librenms/librenms/commit/c149ce0b3acc8e06c1ae9b427c09d07137985815#r44482300

Found the issue in the code

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/daily-update-breaks-poller/14049/16

**Comment by oszafraniec** [comment]
Same problem with me... poller stoped after daily.sh this night... 

After some debug, found this...
```
$ /opt/librenms/cronic /opt/librenms/poller-wrapper.py 16
Cronic detected failure or error output for the command:
/opt/librenms/poller-wrapper.py 16

RESULT CODE: 1

ERROR OUTPUT:
Traceback (most recent call last):
  File "/opt/librenms/poller-wrapper.py", line 28, in <module>
    import LibreNMS.library as LNMS
  File "/opt/librenms/LibreNMS/__init__.py", line 12, in <module>
    from .service import Service, ServiceConfig
  File "/opt/librenms/LibreNMS/service.py", line 6, in <module>
    import pymysql
ModuleNotFoundError: No module named 'pymysql'

STANDARD OUTPUT:
```
Which is strange, poller before was working without problem. I've installed pymysql with 'apt install python3-pymysql' and started to see this...
```
$ /opt/librenms/cronic /opt/librenms/poller-wrapper.py 16
Cronic detected failure or error output for the command:
/opt/librenms/poller-wrapper.py 16

RESULT CODE: 1

ERROR OUTPUT:
Traceback (most recent call last):
  File "/opt/librenms/poller-wrapper.py", line 181, in <module>
    config = json.loads(LNMS.get_config_data(install_dir))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

STANDARD OUTPUT:
```
Everything else is working OK. If I start the poller via Capture/GUI it will poll the device without problem. Only poller-wrapper.py in cron has a problem.

If I start via CLI `./poller.php -h all` it works also without problem.

Libra info
```
$ /opt/librenms/validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.69-56-g305f97161
DB Schema | 2020_10_12_095504_mempools_add_oids (191)
PHP       | 7.4.3
Python    | 3.8.5
MySQL     | 10.3.25-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
OpenSSL   | 
====================================

[OK]    Composer Version: 2.0.7
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```
OS
```
$ uname -a
Linux librenms 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by fulljackz** [comment]
Same here on Debian 9.13

`
~  uname -r
4.9.0-13-amd64
`

**Comment by awlx** [comment]
> Same here on Debian 9.13 / 4.9.0-13-amd64
> 
> When starting ./poller.php -h all here is the output in /var/mail/librenms
> 
> ```
> Cronic detected failure or error output for the command:
> /opt/librenms/poller-wrapper.py 16
> 
> RESULT CODE: 2
> 
> ERROR OUTPUT:
> 
> STANDARD OUTPUT:
> 2020-11-24 10:20:02,804 :: ERROR :: Command [['/usr/bin/env', 'php', '/opt/librenms/config_to_json.php']] failed for unknown reasons [__init__() got an unexpected keyword argument 'encoding'].
> 2020-11-24 10:20:02,804 :: ERROR :: ERROR: Could not execute: ['/usr/bin/env', 'php', '/opt/librenms/config_to_json.php']
> 2020-11-24 10:20:02,804 :: ERROR :: exit code: None. Output:
> __init__() got an unexpected keyword argument 'encoding'
> ```
Fix is here:
https://github.com/librenms/librenms/commit/c149ce0b3acc8e06c1ae9b427c09d07137985815#diff-6eca5b80d25c2594d13bac16a4eab6b2f4d5328a84b2a9121257ac8d0f985c67R141

**Comment by oszafraniec** [comment]
FYI, `git checkout 4bdcb7d88e0d92ad507ca39215e2fc04231bffea` (before "Python log mysql connection errors and harden config retrieval" commit) solves the problem :)

**Comment by razerrazer** [comment]
I did what you have suggested, but then i get this issue:

[WARN]  Your database schema has extra migrations (2020_10_12_095504_mempools_add_oids). If you just switched to the stable release from the daily release, your database is in between releases and this will be resolved with the next release.
[FAIL]  Database: missing column (mempools/hrDeviceIndex)
[FAIL]  Database: incorrect column (mempools/mempool_descr)
[FAIL]  Database: extra column (mempools/mempool_class)
[FAIL]  Database: extra column (mempools/mempool_perc_oid)
[FAIL]  Database: extra column (mempools/mempool_used_oid)
[FAIL]  Database: extra column (mempools/mempool_free_oid)
[FAIL]  Database: extra column (mempools/mempool_total_oid)
[FAIL]  We have detected that your database schema may be wrong, please report the following to us on Discord (https://t.libren.ms/discord) or the community site (https://t.libren.ms/5gscd):
        [FIX]:
        Run the following SQL statements to fix.
        SQL Statements:
         ALTER TABLE `mempools` ADD `hrDeviceIndex` int NULL  AFTER `entPhysicalIndex`;
         ALTER TABLE `mempools` CHANGE `mempool_descr` `mempool_descr` varchar(64) NOT NULL ;
         ALTER TABLE `mempools` DROP `mempool_class`;
         ALTER TABLE `mempools` DROP `mempool_perc_oid`;
         ALTER TABLE `mempools` DROP `mempool_used_oid`;
         ALTER TABLE `mempools` DROP `mempool_free_oid`;
         ALTER TABLE `mempools` DROP `mempool_total_oid`;
[WARN]  Your install is over 24 hours out of date, last update: Mon, 23 Nov 2020 06:35:19 +0000
        [FIX]:
        Make sure your daily.sh cron is running and run ./daily.sh by hand to see if there are any errors.
[WARN]  Your local git branch is not master, this will prevent automatic updates.
        [FIX]:
        You can switch back to master with git checkout master

**Comment by oszafraniec** [comment]
@razerrazer , you are correct but those SQL changes are not so much important. I've added missing column, left varchar at 128 value and 5 columns as they are. But even without those SQLs poller starts to work and draws charts :) it's a workaround only for today/tommorrow... don't think it will last more ;)

**Comment by murrant** [comment]
Reverted the change, run ./daily.sh

**Comment by oszafraniec** [comment]
done daily.sh, can confirm that poller is working. Thx @murrant 👍 

@razerrazer if you made those SQLs you will have to remove added column as I did just now, it will show up in verify config ;)
