### ISSUE TITLE
Bad urls generated when running on sub-directory path

### ISSUE THREAD

**Issue by candlerb** [librenms/librenms#12351]
Tested with librenms 1.68, and also upgraded to git HEAD `1.69-59-ge8d054831 - Wed Nov 25 2020 01:47:40 GMT+0000`

Summary: when running librenms on a sub-directory path, in some cases the generated links include the path twice (e.g. `/librenms/librenms/...`), and in some cases the generated links are missing the sub-directory path entirely.

Here are the cases I have found so far.

### Case 1

* Navigate to any device, e.g. `/librenms/device/1`
* Click the settings cog, this takes you to `/librenms/device/1/edit`
* Hover over any of the tabs `Device Settings | SNMP | Port Settings | Applications | Alert Rules | Modules | Services | IPMI | Storage | Processors | Memory | Misc | Components | Custom OID`
* You will see the path doubled to `/librenms/librenms/...` (clicking the link gives a 404 of course)

In this screenshot I am hovering over the "SNMP" link:

![image](https://user-images.githubusercontent.com/44789/100209514-e34ed800-2f01-11eb-877d-4ef7ea36b357.png)

### Case 2a

* Enable an app on a device (I enabled "NTP client" on a server)
* Go to `Apps > NTP Client` (takes you to `/librenms/apps/app=ntp-client`)
* Hover over a graph; the link has `/librenms/librenms/...`

![image](https://user-images.githubusercontent.com/44789/100210159-95869f80-2f02-11eb-8341-b93672bd3938.png)

### Case 2b

* Go to `Apps > Overview` then click on a graph (takes you to `/librenms/device/1/apps/app=ntp-client`)
* Hover over a graph; the link has `/librenms/librenms/...`

![image](https://user-images.githubusercontent.com/44789/100210621-19408c00-2f03-11eb-9080-4af53d676f68.png)

### Case 3

* Go to any device, e.g. `/librenms/device/1`
* Hover over any of the "Memory" or "Storage" links, e.g. "Physical Memory"; the link has `/librenms/librenms/...`

![image](https://user-images.githubusercontent.com/44789/100211139-adaaee80-2f03-11eb-8589-8d25e94c56f5.png)

### Case 4

This one's a bit trick to replicate.  You need to have devices in your network which are NTP-enabled and where application discovery takes place via SNMP.  This gives you "Apps > NTP" rather than "Apps > NTP Client" or "Apps > NTP Server"

If I browse to Apps > NTP which takes me to `/librenms/apps/app=ntp` then I see a list of devices with clickable links.  However the links are missing the `/librenms` prefix, i.e. they link directly to `/device/...`

![image](https://user-images.githubusercontent.com/44789/100217062-f2865380-2f0a-11eb-9f40-8555db6d38bd.png)

### Workaround

Very ugly, but if you put this in apache config then you can follow the broken links:

```
Redirect /librenms/librenms /librenms
Redirect /device /librenms/device
```

### References

Relates to: #12205

**Comment by candlerb** [comment]
By running a link scanner, I've found some more cases.

### Prefix doubled

"Parent URL" = page containing link, "Real URL" = page linked to

```
Parent URL http://localhost/librenms/oxidized
Real URL   http://localhost/librenms/librenms/tools/tool=oxidized-cfg-check/

Parent URL http://localhost/librenms/search/search=[arp|mac|fdb|ipv4|ipv6]
Real URL   http://localhost/librenms/librenms/search/search=[ipv4|ipv6|mac|arp|fdb]/

Parent URL http://localhost/librenms/devices
Real URL   http://localhost/librenms/librenms/devices/format=[list_basic|list_detail]/
```
![image](https://user-images.githubusercontent.com/44789/100234701-60d71000-2f23-11eb-848f-e7c29efc0914.png)

```
Parent URL http://localhost/librenms/devices
Real URL   http://localhost/librenms/librenms/devices/format=graph_bits/from=-24hour/to=now/
Real URL   http://localhost/librenms/librenms/devices/format=graph_processor/from=-24hour/to=now/
Real URL   http://localhost/librenms/librenms/devices/format=graph_ucd_load/from=-24hour/to=now/
...etc for other formats

Real URL   http://localhost/librenms/librenms/devices/format=list_detail/searchbar=hide/
Real URL   http://localhost/librenms/librenms/devices/format=list_detail/bare=yes/
```

```
Parent URL http://localhost/librenms/services
Real URL   http://localhost/librenms/librenms/services/view=<view>/state=[all|ok|warning|critical]/

Parent URL http://localhost/librenms/ports[/errors=yes|/state=down|/state=admindown...]
Real URL   http://localhost/librenms/librenms/ports/format=[list_basic|list_detail|graph_bits|graph_upkts|....]/
```

This one you get from going to `/librenms/ports` then hovering over "Export CSV":

```
Parent URL http://localhost/librenms/ports, line 603, col 722
Real URL   http://localhost/librenms/csv.php/report=http%3A/localhost/librenms/librenms/ports/
```

```
Parent URL http://localhost/librenms/health
Real URL   http://localhost/librenms/librenms/health/metric=[mempool|processor|storage|temperature]/view=<view>/
```

```
Parent URL http://localhost/librenms/routing[/protocol=bgp|/protocol=vrf]
Real URL   http://localhost/librenms/librenms/routing/protocol=bgp/
```

It's pretty manual so I stopped at this point.  Hopefully there is some common underlying cause which can fix them all.

### Prefix missing

Page | Links to
----- | -----
`/librenms/notifications`, `/librenms/notifications/archive/` | `/notifications`
`/librenms/css/mktree.css` | `/images/bullet.gif`, `/images/plus.gif`, `/images/minus.gif`
`/librenms/css/styles.css` | `/css/PIE.htc`

### Reference gives 404

```
Parent URL http://localhost/librenms/css/jquery-ui.min.css, line 3, col 1809
Real URL   http://localhost/librenms/css/images/ui-bg_flat_75_ffffff_40x100.png
Parent URL http://localhost/librenms/css/jquery-ui.min.css, line 3, col 1971
Real URL   http://localhost/librenms/css/images/ui-bg_highlight-soft_50_dddddd_1x100.png
Parent URL http://localhost/librenms/css/jquery-ui.min.css, line 3, col 2234
Real URL   http://localhost/librenms/css/images/ui-bg_highlight-soft_100_f6f6f6_1x100.png
Parent URL http://localhost/librenms/css/jquery-ui.min.css, line 3, col 2660
Real URL   http://localhost/librenms/css/images/ui-bg_highlight-soft_25_0073ea_1x100.png
Parent URL http://localhost/librenms/css/jquery-ui.min.css, line 3, col 3100
Real URL   http://localhost/librenms/css/images/ui-bg_glass_65_ffffff_1x400.png
Parent URL http://localhost/librenms/css/jquery-ui.min.css, line 3, col 3434
Real URL   http://localhost/librenms/css/images/ui-bg_flat_55_ffffff_40x100.png
Parent URL http://localhost/librenms/css/jquery-ui.min.css, line 3, col 3748
Real URL   http://localhost/librenms/css/images/ui-bg_flat_55_ffffff_40x100.png
Parent URL http://localhost/librenms/css/jquery-ui.min.css, line 3, col 4605
Real URL   http://localhost/librenms/css/images/ui-icons_ff0084_256x240.png
Parent URL http://localhost/librenms/css/jquery-ui.min.css, line 3, col 4691
Real URL   http://localhost/librenms/css/images/ui-icons_0073ea_256x240.png
Parent URL http://localhost/librenms/css/jquery-ui.min.css, line 3, col 4777
Real URL   http://localhost/librenms/css/images/ui-icons_666666_256x240.png
Parent URL http://localhost/librenms/css/jquery-ui.min.css, line 3, col 4886
Real URL   http://localhost/librenms/css/images/ui-icons_ffffff_256x240.png
Parent URL http://localhost/librenms/css/jquery-ui.min.css, line 3, col 4971
Real URL   http://localhost/librenms/css/images/ui-icons_454545_256x240.png
Parent URL http://localhost/librenms/css/jquery-ui.min.css, line 3, col 5059
Real URL   http://localhost/librenms/css/images/ui-icons_0073ea_256x240.png
Parent URL http://localhost/librenms/css/jquery-ui.min.css, line 3, col 5173
Real URL   http://localhost/librenms/css/images/ui-icons_ff0084_256x240.png
Parent URL http://localhost/librenms/css/jquery-ui.min.css, line 3, col 14892
Real URL   http://localhost/librenms/css/images/ui-bg_flat_0_eeeeee_40x100.png
Parent URL http://localhost/librenms/css/jquery-ui.min.css, line 3, col 15057
Real URL   http://localhost/librenms/css/images/ui-bg_flat_0_aaaaaa_40x100.png
Parent URL http://localhost/librenms/css/vis.min.css, line 1, col 10686
Real URL   http://localhost/librenms/css/img/network/cross.png
Parent URL http://localhost/librenms/css/vis.min.css, line 1, col 11645
Real URL   http://localhost/librenms/css/img/network/backIcon.png
Parent URL http://localhost/librenms/css/vis.min.css, line 1, col 12124
Real URL   http://localhost/librenms/css/img/network/addNodeIcon.png
Parent URL http://localhost/librenms/css/vis.min.css, line 1, col 12293
Real URL   http://localhost/librenms/css/img/network/editIcon.png
Parent URL http://localhost/librenms/css/vis.min.css, line 1, col 12523
Real URL   http://localhost/librenms/css/img/network/connectIcon.png
Parent URL http://localhost/librenms/css/vis.min.css, line 1, col 12636
Real URL   http://localhost/librenms/css/img/network/deleteIcon.png
Parent URL http://localhost/librenms/css/vis.min.css, line 1, col 13595
Real URL   http://localhost/librenms/css/img/network/upArrow.png
Parent URL http://localhost/librenms/css/vis.min.css, line 1, col 13722
Real URL   http://localhost/librenms/css/img/network/downArrow.png
Parent URL http://localhost/librenms/css/vis.min.css, line 1, col 13851
Real URL   http://localhost/librenms/css/img/network/leftArrow.png
Parent URL http://localhost/librenms/css/vis.min.css, line 1, col 13981
Real URL   http://localhost/librenms/css/img/network/rightArrow.png
Parent URL http://localhost/librenms/css/vis.min.css, line 1, col 14113
Real URL   http://localhost/librenms/css/img/network/plus.png
Parent URL http://localhost/librenms/css/vis.min.css, line 1, col 14241
Real URL   http://localhost/librenms/css/img/network/minus.png
Parent URL http://localhost/librenms/css/vis.min.css, line 1, col 14374
Real URL   http://localhost/librenms/css/img/network/zoomExtends.png
```

**Comment by murrant** [comment]
Duplicate

**Comment by candlerb** [comment]
Could you tell me which issue this is a duplicate of? There are currently 11 open issues, none of which seem to match this.

**Comment by candlerb** [comment]
Note that #12205 is just for the top-level access, i.e. going to `^/librenms/$` fails, you have to select `/librenms/overview` as the starting point.

What I have reported above is that some of the links generated *within* a page are bad.  (Note that some are good; some are bad)

**Comment by murrant** [comment]
It is the same issue. Reporting individual links is not helpful at this point.  Submit a fix as a pull request if you think there is a code issue.
