### ISSUE TITLE
Status management in LibreNMS

### ISSUE THREAD

**Issue by Calvario** [librenms/librenms#1236]
It will be interessant to update the Status system in LibreNMS.
It will be cool to allow a custom message with a color.

Another fact, this link doesn't work : https://lnms/health/metric=state/
But we can see the status in the device.

**Comment by f0o** [comment]
Why do you expect it to work?

And can you be a bit more detailed with your request please?

**Comment by Calvario** [comment]
Sorry of course.

Well actualy the States system only can get 0/1 and create a graph but it's more suitable to have a list with the states.

Example

Status - (color with return gravity 1/2/3) - Custom message

System Status - (green)OK(green)
Raid Status - (yellow)Raid Syncing(yellow)
System Fan - (red)Error(red)

Why ? Because if my snmp return for Raid Status 7 the user don't know what this it and it's more easy to read and see a color then a number for a status.

Thank you to keep time to understand my request.

**Comment by laf** [comment]
We'd need to work out how to do this and maybe @paulgear new polling from MIB feature might fix this as the issue we have is we don't know what the states are supposed to mean, we just report them back as is so it's currently upto the user to know.

**Comment by Calvario** [comment]
Well i understand thanks for the answer. I know it's hard to define what exactly was a status but on other products it work with this idea. What's the issue or the conversation about the new polling system, i'm curious.

**Comment by laf** [comment]
paulgear is building something that will just parse mib files to create the graphs, this in theory should mean we can then also parse the output using the same mib file for what that info means. I.e state 7 = raid rebuilding.

**Comment by Calvario** [comment]
Well that will be a good news but how do you will show that information in case of Status.
For example State 7 = Raid Rebuilding

**Comment by laf** [comment]
@Calvario At present we can't, this will need either code to be written that does manual mapping to the states or we see if @paulgear new system can do this.

**Comment by Rosiak** [comment]
Could imagine something like this http://snag.gy/iWXIU.jpg

**Comment by Rosiak** [comment]
@librenms/core-team 
Should we try to see if we can pick this up in Q1 16' ?
I think it's a pretty vital part, we've been sorta missing out on for some time.

**Comment by SaaldjorMike** [comment]
:+1:

**Comment by f0o** [comment]
:+1:

**Comment by paulgear** [comment]
I don't think this has much overlap with MIB-based polling.
