### ISSUE TITLE
update to 1.70 lost graylog integration

### ISSUE THREAD

**Issue by lucasevabou14** [librenms/librenms#12385]
Hello, 

Since I update librenms to 1.70 I have lost graylog integration. No update from graylog server. Server still functionnal.

array (
  'device-page' =>
  array (
    'loglevel' => 7,
    'rowCount' => 10,
  ),
  'server' => 'https://syslog-srv2.xxx-xx.fr',
  'port' => 9000,
  'username' => 'svc-graylog',
  'password' => 'xxxxxxx',
  'version' => 'other',
  'timezone' => 'Europe/Paris',
  'match-any-address' => 'true',
  'base_uri' => '/api/search/universal/relative/',
)

**Comment by lucasevabou14** [comment]
Here is the following error I am encountering in chrome debug mode 

{"error":"cURL error 77:  (see https:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html) for https:\/\/syslog-srv2.xxx-xxx.fr:9000\/api\/search\/universal\/relative\/?query=%2A&limit=25&offset=0"}

**Comment by murrant** [comment]
Your SSL cert has expired or something.

From the link you posted.
```CURLE_SSL_CACERT_BADFILE (77)

Problem with reading the SSL CA cert (path? access rights?)```
