### ISSUE TITLE
Cisco IPSEC Tunnels

### ISSUE THREAD

**Issue by Cupidazul** [librenms/librenms#12393]
I'm getting an error in the polling of cipsec-tunnels, I'm not sure if i should open here or in the community.librenms.org ...
thx

Warning: array_merge(): Expected parameter 2 to be an array, null given in /opt/librenms/includes/polling/cipsec-tunnels.inc.php on line 24

Poller Debug:

#### Load poller module cipsec-tunnels ####
SNMP['/usr/bin/snmpbulkwalk' '-Cr20' '-v2c' '-c' 'COMMUNITY' '-OQUs' '-m' 'CISCO-IPSEC-FLOW-MONITOR-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' 'udp:HOSTNAME:161' 'cipSecTunnelEntry']
cipSecTunIkeTunnelIndex.11 = 27
cipSecTunIkeTunnelIndex.12 = 27
cipSecTunIkeTunnelIndex.13 = 27
cipSecTunIkeTunnelIndex.14 = 27
cipSecTunIkeTunnelIndex.97 = 469
cipSecTunIkeTunnelIndex.99 = 479
cipSecTunIkeTunnelIndex.100 = 479
cipSecTunIkeTunnelAlive.11 = false
cipSecTunIkeTunnelAlive.12 = false
cipSecTunIkeTunnelAlive.13 = false
cipSecTunIkeTunnelAlive.14 = false
cipSecTunIkeTunnelAlive.97 = false
cipSecTunIkeTunnelAlive.99 = false
cipSecTunIkeTunnelAlive.100 = false
cipSecTunLocalAddr.11 = "D4 5A CA 22 "
cipSecTunLocalAddr.12 = "D4 5A CA 22 "
cipSecTunLocalAddr.13 = "D4 5A CA 22 "
cipSecTunLocalAddr.14 = "D4 5A CA 22 "
cipSecTunLocalAddr.97 = "D4 5A CA 22 "
cipSecTunLocalAddr.99 = "D4 5A CA 22 "
cipSecTunLocalAddr.100 = "D4 5A CA 22 "
cipSecTunRemoteAddr.11 = "3E 1C 48 39 "
cipSecTunRemoteAddr.12 = "3E 1C 48 39 "
cipSecTunRemoteAddr.13 = "3E 1C 48 39 "
cipSecTunRemoteAddr.14 = "3E 1C 48 39 "
cipSecTunRemoteAddr.97 = "3E 1C 48 39 "
cipSecTunRemoteAddr.99 = "3E 1C 48 39 "
cipSecTunRemoteAddr.100 = "3E 1C 48 39 "
cipSecTunKeyType.11 = ike
cipSecTunKeyType.12 = ike
cipSecTunKeyType.13 = ike
cipSecTunKeyType.14 = ike
cipSecTunKeyType.97 = ike
cipSecTunKeyType.99 = ike
cipSecTunKeyType.100 = ike
cipSecTunEncapMode.11 = tunnel
cipSecTunEncapMode.12 = tunnel
cipSecTunEncapMode.13 = tunnel
cipSecTunEncapMode.14 = tunnel
cipSecTunEncapMode.97 = tunnel
cipSecTunEncapMode.99 = tunnel
cipSecTunEncapMode.100 = tunnel
cipSecTunLifeSize.11 = 4608000
cipSecTunLifeSize.12 = 4608000
cipSecTunLifeSize.13 = 4608000
cipSecTunLifeSize.14 = 4608000
cipSecTunLifeSize.97 = 4608000
cipSecTunLifeSize.99 = 4608000
cipSecTunLifeSize.100 = 4608000
cipSecTunLifeTime.11 = 3600
cipSecTunLifeTime.12 = 3600
cipSecTunLifeTime.13 = 3600
cipSecTunLifeTime.14 = 3600
cipSecTunLifeTime.97 = 3600
cipSecTunLifeTime.99 = 3600
cipSecTunLifeTime.100 = 3600
cipSecTunActiveTime.11 = 166518
cipSecTunActiveTime.12 = 229497
cipSecTunActiveTime.13 = 34615
cipSecTunActiveTime.14 = 106149
cipSecTunActiveTime.97 = 207384
cipSecTunActiveTime.99 = 123615
cipSecTunActiveTime.100 = 122130
cipSecTunSaLifeSizeThreshold.11 = 64
cipSecTunSaLifeSizeThreshold.12 = 64
cipSecTunSaLifeSizeThreshold.13 = 64
cipSecTunSaLifeSizeThreshold.14 = 64
cipSecTunSaLifeSizeThreshold.97 = 64
cipSecTunSaLifeSizeThreshold.99 = 64
cipSecTunSaLifeSizeThreshold.100 = 64
cipSecTunSaLifeTimeThreshold.11 = 10
cipSecTunSaLifeTimeThreshold.12 = 10
cipSecTunSaLifeTimeThreshold.13 = 10
cipSecTunSaLifeTimeThreshold.14 = 10
cipSecTunSaLifeTimeThreshold.97 = 10
cipSecTunSaLifeTimeThreshold.99 = 10
cipSecTunSaLifeTimeThreshold.100 = 10
cipSecTunTotalRefreshes.11 = 434
cipSecTunTotalRefreshes.12 = 434
cipSecTunTotalRefreshes.13 = 433
cipSecTunTotalRefreshes.14 = 433
cipSecTunTotalRefreshes.97 = 162
cipSecTunTotalRefreshes.99 = 22
cipSecTunTotalRefreshes.100 = 22
cipSecTunExpiredSaInstances.11 = 828
cipSecTunExpiredSaInstances.12 = 828
cipSecTunExpiredSaInstances.13 = 826
cipSecTunExpiredSaInstances.14 = 826
cipSecTunExpiredSaInstances.97 = 20
cipSecTunExpiredSaInstances.99 = 4
cipSecTunExpiredSaInstances.100 = 4
cipSecTunCurrentSaInstances.11 = 2
cipSecTunCurrentSaInstances.12 = 2
cipSecTunCurrentSaInstances.13 = 2
cipSecTunCurrentSaInstances.14 = 2
cipSecTunCurrentSaInstances.97 = 2
cipSecTunCurrentSaInstances.99 = 2
cipSecTunCurrentSaInstances.100 = 2
cipSecTunInSaDiffHellmanGrp.11 = none
cipSecTunInSaDiffHellmanGrp.12 = none
cipSecTunInSaDiffHellmanGrp.13 = none
cipSecTunInSaDiffHellmanGrp.14 = none
cipSecTunInSaDiffHellmanGrp.97 = none
cipSecTunInSaDiffHellmanGrp.99 = none
cipSecTunInSaDiffHellmanGrp.100 = none
cipSecTunInSaEncryptAlgo.11 = des3
cipSecTunInSaEncryptAlgo.12 = des3
cipSecTunInSaEncryptAlgo.13 = des3
cipSecTunInSaEncryptAlgo.14 = des3
cipSecTunInSaEncryptAlgo.97 = des3
cipSecTunInSaEncryptAlgo.99 = des3
cipSecTunInSaEncryptAlgo.100 = des3
cipSecTunInSaAhAuthAlgo.11 = none
cipSecTunInSaAhAuthAlgo.12 = none
cipSecTunInSaAhAuthAlgo.13 = none
cipSecTunInSaAhAuthAlgo.14 = none
cipSecTunInSaAhAuthAlgo.97 = none
cipSecTunInSaAhAuthAlgo.99 = none
cipSecTunInSaAhAuthAlgo.100 = none
cipSecTunInSaEspAuthAlgo.11 = hmacMd5
cipSecTunInSaEspAuthAlgo.12 = hmacMd5
cipSecTunInSaEspAuthAlgo.13 = hmacMd5
cipSecTunInSaEspAuthAlgo.14 = hmacMd5
cipSecTunInSaEspAuthAlgo.97 = hmacMd5
cipSecTunInSaEspAuthAlgo.99 = hmacMd5
cipSecTunInSaEspAuthAlgo.100 = hmacMd5
cipSecTunInSaDecompAlgo.11 = none
cipSecTunInSaDecompAlgo.12 = none
cipSecTunInSaDecompAlgo.13 = none
cipSecTunInSaDecompAlgo.14 = none
cipSecTunInSaDecompAlgo.97 = none
cipSecTunInSaDecompAlgo.99 = none
cipSecTunInSaDecompAlgo.100 = none
cipSecTunOutSaDiffHellmanGrp.11 = none
cipSecTunOutSaDiffHellmanGrp.12 = none
cipSecTunOutSaDiffHellmanGrp.13 = none
cipSecTunOutSaDiffHellmanGrp.14 = none
cipSecTunOutSaDiffHellmanGrp.97 = none
cipSecTunOutSaDiffHellmanGrp.99 = none
cipSecTunOutSaDiffHellmanGrp.100 = none
cipSecTunOutSaEncryptAlgo.11 = des3
cipSecTunOutSaEncryptAlgo.12 = des3
cipSecTunOutSaEncryptAlgo.13 = des3
cipSecTunOutSaEncryptAlgo.14 = des3
cipSecTunOutSaEncryptAlgo.97 = des3
cipSecTunOutSaEncryptAlgo.99 = des3
cipSecTunOutSaEncryptAlgo.100 = des3
cipSecTunOutSaAhAuthAlgo.11 = none
cipSecTunOutSaAhAuthAlgo.12 = none
cipSecTunOutSaAhAuthAlgo.13 = none
cipSecTunOutSaAhAuthAlgo.14 = none
cipSecTunOutSaAhAuthAlgo.97 = none
cipSecTunOutSaAhAuthAlgo.99 = none
cipSecTunOutSaAhAuthAlgo.100 = none
cipSecTunOutSaEspAuthAlgo.11 = hmacMd5
cipSecTunOutSaEspAuthAlgo.12 = hmacMd5
cipSecTunOutSaEspAuthAlgo.13 = hmacMd5
cipSecTunOutSaEspAuthAlgo.14 = hmacMd5
cipSecTunOutSaEspAuthAlgo.97 = hmacMd5
cipSecTunOutSaEspAuthAlgo.99 = hmacMd5
cipSecTunOutSaEspAuthAlgo.100 = hmacMd5
cipSecTunOutSaCompAlgo.11 = none
cipSecTunOutSaCompAlgo.12 = none
cipSecTunOutSaCompAlgo.13 = none
cipSecTunOutSaCompAlgo.14 = none
cipSecTunOutSaCompAlgo.97 = none
cipSecTunOutSaCompAlgo.99 = none
cipSecTunOutSaCompAlgo.100 = none
cipSecTunInOctets.11 = 25956263
cipSecTunInOctets.12 = 84377867
cipSecTunInOctets.13 = 20614314
cipSecTunInOctets.14 = 11200662
cipSecTunInOctets.97 = 11724
cipSecTunInOctets.99 = 48426634
cipSecTunInOctets.100 = 7003486
cipSecTunHcInOctets.11 = 25956263
cipSecTunHcInOctets.12 = 84377867
cipSecTunHcInOctets.13 = 20614314
cipSecTunHcInOctets.14 = 11200662
cipSecTunHcInOctets.97 = 11724
cipSecTunHcInOctets.99 = 48426634
cipSecTunHcInOctets.100 = 7003486
cipSecTunInOctWraps.11 = 0
cipSecTunInOctWraps.12 = 0
cipSecTunInOctWraps.13 = 0
cipSecTunInOctWraps.14 = 0
cipSecTunInOctWraps.97 = 0
cipSecTunInOctWraps.99 = 0
cipSecTunInOctWraps.100 = 0
cipSecTunInDecompOctets.11 = 25956263
cipSecTunInDecompOctets.12 = 84377867
cipSecTunInDecompOctets.13 = 20614314
cipSecTunInDecompOctets.14 = 11201004
cipSecTunInDecompOctets.97 = 11724
cipSecTunInDecompOctets.99 = 48426634
cipSecTunInDecompOctets.100 = 7003486
cipSecTunHcInDecompOctets.11 = 25956263
cipSecTunHcInDecompOctets.12 = 84377867
cipSecTunHcInDecompOctets.13 = 20614314
cipSecTunHcInDecompOctets.14 = 11201004
cipSecTunHcInDecompOctets.97 = 11724
cipSecTunHcInDecompOctets.99 = 48426634
cipSecTunHcInDecompOctets.100 = 7003486
cipSecTunInDecompOctWraps.11 = 0
cipSecTunInDecompOctWraps.12 = 0
cipSecTunInDecompOctWraps.13 = 0
cipSecTunInDecompOctWraps.14 = 0
cipSecTunInDecompOctWraps.97 = 0
cipSecTunInDecompOctWraps.99 = 0
cipSecTunInDecompOctWraps.100 = 0
cipSecTunInPkts.11 = 291325
cipSecTunInPkts.12 = 495224
cipSecTunInPkts.13 = 149599
cipSecTunInPkts.14 = 44309
cipSecTunInPkts.97 = 176
cipSecTunInPkts.99 = 78386
cipSecTunInPkts.100 = 22709
cipSecTunInDropPkts.11 = 0
cipSecTunInDropPkts.12 = 0
cipSecTunInDropPkts.13 = 0
cipSecTunInDropPkts.14 = 0
cipSecTunInDropPkts.97 = 0
cipSecTunInDropPkts.99 = 0
cipSecTunInDropPkts.100 = 0
cipSecTunInReplayDropPkts.11 = 0
cipSecTunInReplayDropPkts.12 = 0
cipSecTunInReplayDropPkts.13 = 0
cipSecTunInReplayDropPkts.14 = 0
cipSecTunInReplayDropPkts.97 = 0
cipSecTunInReplayDropPkts.99 = 0
cipSecTunInReplayDropPkts.100 = 0
cipSecTunInAuths.11 = 291325
cipSecTunInAuths.12 = 495224
cipSecTunInAuths.13 = 149599
cipSecTunInAuths.14 = 44309
cipSecTunInAuths.97 = 176
cipSecTunInAuths.99 = 78386
cipSecTunInAuths.100 = 22709
cipSecTunInAuthFails.11 = 0
cipSecTunInAuthFails.12 = 0
cipSecTunInAuthFails.13 = 0
cipSecTunInAuthFails.14 = 0
cipSecTunInAuthFails.97 = 0
cipSecTunInAuthFails.99 = 0
cipSecTunInAuthFails.100 = 0
cipSecTunInDecrypts.11 = 291325
cipSecTunInDecrypts.12 = 495224
cipSecTunInDecrypts.13 = 149599
cipSecTunInDecrypts.14 = 44309
cipSecTunInDecrypts.97 = 176
cipSecTunInDecrypts.99 = 78386
cipSecTunInDecrypts.100 = 22709
cipSecTunInDecryptFails.11 = 0
cipSecTunInDecryptFails.12 = 0
cipSecTunInDecryptFails.13 = 0
cipSecTunInDecryptFails.14 = 0
cipSecTunInDecryptFails.97 = 0
cipSecTunInDecryptFails.99 = 0
cipSecTunInDecryptFails.100 = 0
cipSecTunOutOctets.11 = 758058368
cipSecTunOutOctets.12 = 362064032
cipSecTunOutOctets.13 = 22834808
cipSecTunOutOctets.14 = 7310376
cipSecTunOutOctets.97 = 542232
cipSecTunOutOctets.99 = 30129192
cipSecTunOutOctets.100 = 11063440
cipSecTunHcOutOctets.11 = 758058368
cipSecTunHcOutOctets.12 = 362064032
cipSecTunHcOutOctets.13 = 22834808
cipSecTunHcOutOctets.14 = 7310376
cipSecTunHcOutOctets.97 = 542232
cipSecTunHcOutOctets.99 = 30129192
cipSecTunHcOutOctets.100 = 11063440
cipSecTunOutOctWraps.11 = 0
cipSecTunOutOctWraps.12 = 0
cipSecTunOutOctWraps.13 = 0
cipSecTunOutOctWraps.14 = 0
cipSecTunOutOctWraps.97 = 0
cipSecTunOutOctWraps.99 = 0
cipSecTunOutOctWraps.100 = 0
cipSecTunOutUncompOctets.11 = 758058368
cipSecTunOutUncompOctets.12 = 362064032
cipSecTunOutUncompOctets.13 = 22834808
cipSecTunOutUncompOctets.14 = 7310376
cipSecTunOutUncompOctets.97 = 542232
cipSecTunOutUncompOctets.99 = 30129192
cipSecTunOutUncompOctets.100 = 11063440
cipSecTunHcOutUncompOctets.11 = 758058368
cipSecTunHcOutUncompOctets.12 = 362064032
cipSecTunHcOutUncompOctets.13 = 22834808
cipSecTunHcOutUncompOctets.14 = 7310376
cipSecTunHcOutUncompOctets.97 = 542232
cipSecTunHcOutUncompOctets.99 = 30129192
cipSecTunHcOutUncompOctets.100 = 11063440
cipSecTunOutUncompOctWraps.11 = 0
cipSecTunOutUncompOctWraps.12 = 0
cipSecTunOutUncompOctWraps.13 = 0
cipSecTunOutUncompOctWraps.14 = 0
cipSecTunOutUncompOctWraps.97 = 0
cipSecTunOutUncompOctWraps.99 = 0
cipSecTunOutUncompOctWraps.100 = 0
cipSecTunOutPkts.11 = 879683
cipSecTunOutPkts.12 = 904942
cipSecTunOutPkts.13 = 116857
cipSecTunOutPkts.14 = 35645
cipSecTunOutPkts.97 = 4370
cipSecTunOutPkts.99 = 78434
cipSecTunOutPkts.100 = 34187
cipSecTunOutDropPkts.11 = 830
cipSecTunOutDropPkts.12 = 1380
cipSecTunOutDropPkts.13 = 0
cipSecTunOutDropPkts.14 = 0
cipSecTunOutDropPkts.97 = 1
cipSecTunOutDropPkts.99 = 1
cipSecTunOutDropPkts.100 = 1
cipSecTunOutAuths.11 = 879683
cipSecTunOutAuths.12 = 904942
cipSecTunOutAuths.13 = 116857
cipSecTunOutAuths.14 = 35645
cipSecTunOutAuths.97 = 4370
cipSecTunOutAuths.99 = 78434
cipSecTunOutAuths.100 = 34187
cipSecTunOutAuthFails.11 = 0
cipSecTunOutAuthFails.12 = 0
cipSecTunOutAuthFails.13 = 0
cipSecTunOutAuthFails.14 = 0
cipSecTunOutAuthFails.97 = 0
cipSecTunOutAuthFails.99 = 0
cipSecTunOutAuthFails.100 = 0
cipSecTunOutEncrypts.11 = 879683
cipSecTunOutEncrypts.12 = 904942
cipSecTunOutEncrypts.13 = 116857
cipSecTunOutEncrypts.14 = 35645
cipSecTunOutEncrypts.97 = 4370
cipSecTunOutEncrypts.99 = 78434
cipSecTunOutEncrypts.100 = 34187
cipSecTunOutEncryptFails.11 = 0
cipSecTunOutEncryptFails.12 = 0
cipSecTunOutEncryptFails.13 = 0
cipSecTunOutEncryptFails.14 = 0
cipSecTunOutEncryptFails.97 = 0
cipSecTunOutEncryptFails.99 = 0
cipSecTunOutEncryptFails.100 = 0
cipSecTunStatus.11 = active
cipSecTunStatus.12 = active
cipSecTunStatus.13 = active
cipSecTunStatus.14 = active
cipSecTunStatus.97 = active
cipSecTunStatus.99 = active
cipSecTunStatus.100 = active

SNMP['/usr/bin/snmpbulkwalk' '-Cr20' '-v2c' '-c' 'COMMUNITY' '-OQUs' '-m' 'CISCO-IPSEC-FLOW-MONITOR-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' 'udp:HOSTNAME:161' 'cikeTunnelEntry']
cikeTunLocalType.481 = ipAddrPeer
cikeTunLocalValue.481 = *
cikeTunLocalAddr.481 = "D4 5A CA 22 "
cikeTunLocalName.481 = <removed>
cikeTunRemoteType.481 = ipAddrPeer
cikeTunRemoteValue.481 = *
cikeTunRemoteAddr.481 = "3E 1C 48 39 "
cikeTunRemoteName.481 =
cikeTunNegoMode.481 = main
cikeTunDiffHellmanGrp.481 = dhGroup2
cikeTunEncryptAlgo.481 = des3
cikeTunHashAlgo.481 = md5
cikeTunAuthMethod.481 = preSharedKey
cikeTunLifeTime.481 = 3600
cikeTunActiveTime.481 = 268226
cikeTunSaRefreshThreshold.481 = 0
cikeTunTotalRefreshes.481 = 0
cikeTunInOctets.481 = 1860
cikeTunInPkts.481 = 10
cikeTunInDropPkts.481 = 0
cikeTunInNotifys.481 = 0
cikeTunInP2Exchgs.481 = 8
cikeTunInP2ExchgInvalids.481 = 0
cikeTunInP2ExchgRejects.481 = 0
cikeTunInP2SaDelRequests.481 = 0
cikeTunOutOctets.481 = 3378
cikeTunOutPkts.481 = 23
cikeTunOutDropPkts.481 = 0
cikeTunOutNotifys.481 = 8
cikeTunOutP2Exchgs.481 = 13
cikeTunOutP2ExchgInvalids.481 = 0
cikeTunOutP2ExchgRejects.481 = 0
cikeTunOutP2SaDelRequests.481 = 7
cikeTunStatus.481 = active

SQL[SELECT * FROM `ipsec_tunnels` WHERE `device_id` = ? [122] 0.62ms]

Warning: array_merge(): Expected parameter 2 to be an array, null given in /opt/librenms/includes/polling/cipsec-tunnels.inc.php on line 24
Tunnel 11 ()
Address

Warning: array_merge(): Expected parameter 2 to be an array, null given in /opt/librenms/includes/polling/cipsec-tunnels.inc.php on line 24
Tunnel 12 ()
Address

Warning: array_merge(): Expected parameter 2 to be an array, null given in /opt/librenms/includes/polling/cipsec-tunnels.inc.php on line 24
Tunnel 13 ()
Address

Warning: array_merge(): Expected parameter 2 to be an array, null given in /opt/librenms/includes/polling/cipsec-tunnels.inc.php on line 24
Tunnel 14 ()
Address

Warning: array_merge(): Expected parameter 2 to be an array, null given in /opt/librenms/includes/polling/cipsec-tunnels.inc.php on line 24
Tunnel 97 ()
Address

Warning: array_merge(): Expected parameter 2 to be an array, null given in /opt/librenms/includes/polling/cipsec-tunnels.inc.php on line 24
Tunnel 99 ()
Address

Warning: array_merge(): Expected parameter 2 to be an array, null given in /opt/librenms/includes/polling/cipsec-tunnels.inc.php on line 24
Tunnel 100 ()
Address

>> Runtime for poller module 'cipsec-tunnels': 2.2873 seconds with 3744 bytes
>> SNMP: [2/2.29s] MySQL: [1/0.00s] RRD: [2/0.00s]

**Comment by Cupidazul** [comment]
Ok, Assign this to me, I can do some tests here...

**Comment by vertIcod3r** [comment]
@Cupidazul I am having the same issue: 
#### Load poller module cipsec-tunnels ####

In cipsec-tunnels.inc.php line 24:
                                                                
  array_merge(): Argument #2 must be of type array, null given  

Is there any progress on this, or can I manually solve this some way?

**Comment by Cupidazul** [comment]
Sure go ahead, I didn't have time to finish this troubleshoot.

**Comment by murrant** [comment]
Looks like code that is incompatible with PHP8 but isn't covered by our tests.

**Comment by murrant** [comment]
Can one of you save test data with `./scripts/save-test-data.php -h <hostname> -m cipsec-tunnels`
#13463

**Comment by lodbetarn** [comment]
Turned on the module again and can't see the error anymore. I will get back to you if the error reappears.

**Comment by realgreef** [comment]
I have the same error when enabling module cipsec-tunnels for a Cisco FTD device:

[2022-08-11T13:20:30.348038+02:00] production.ERROR: Error polling cipsec-tunnels module for ftd-firewall. TypeError: array_merge(): Argument #2 must be of type array, null given in /opt/librenms/includes/polling/cipsec-tunnels.inc.php:24
Stack trace:
#0 /opt/librenms/includes/polling/cipsec-tunnels.inc.php(24): array_merge()
#1 /opt/librenms/includes/polling/functions.inc.php(331): include('...')
#2 /opt/librenms/poller.php(138): poll_device()
#3 {main}  

When running ./collect-snmp-data.php -h ftd-firewall -o ftd -m cipsec-tunnels -v ftd  I can see collected relevant data (peer ips etc)

Running php 8.1.8

Any solution to this?
