### ISSUE TITLE
Defining timespan when viewing a graph doesn't work if client timezone isn't UTC

### ISSUE THREAD

**Issue by cs-1** [librenms/librenms#1239]
When clicking a graph to view its details, it's possible to define a timespan that you want to view. If the client machine that runs the browser doesn't have "UTC" as timezone, clicking the "Update" button next to the timespan fields "From" and "To" will make the times that have been entered jump the amount of hours that the client's timezone differs from UTC.

The easiest way to reproduce this issue is this:
- Use a host that has a timezone other than UTC.
- View a graph.
- Click "Update" next to the timespan fields "From" and "To" without entering anything in those field.
- Look at the times that can now be seen in "From" and "To" (they will have jumped).

**Comment by laf** [comment]
If this isn't currently fixed from the PR attached please re-open this.
