### ISSUE TITLE
Warning: include(includes/polling/mib.inc.php): failed to open stream: No such file or directory in /opt/librenms/includes/polling/functions.inc.php on line 317

### ISSUE THREAD

**Issue by nntu** [librenms/librenms#12401]
#### Load poller module mib ####

Warning: include(includes/polling/mib.inc.php): failed to open stream: No such file or directory in /opt/librenms/includes/polling/functions.inc.php on line 317

Warning: include(): Failed opening 'includes/polling/mib.inc.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /opt/librenms/includes/polling/functions.inc.php on line 317

>> Runtime for poller module 'mib': 0.0002 seconds with 0 bytes
>> SNMP: [0/0.00s] MySQL: [0/0.00s]
#### Unload poller module mib ####

**Comment by kkrumm1** [comment]
MIB based poller is no longer supported
