### ISSUE TITLE
HP Procurve Switch (HP 1810) listed as generic device

### ISSUE THREAD

**Issue by azcobain** [librenms/librenms#1240]
I have 2 HP Procurve switches (HP 1810) that are being detected as generic devices. I have another HP Procurve switch that has been detected fine. Here is the snmpbulkwalk: https://gist.github.com/azcobain/923522f9bf8c13ef4478

Thanks.

**Comment by Lonecrowe** [comment]
I'll check I'm pretty sure I have a few..  that were detected fine

http://imgur.com/PvtKewC

**Comment by SaaldjorMike** [comment]
Mine was also detected fine, but it looks like his sysDescr returns:
```
iso.3.6.1.2.1.1.1.0 = STRING: "HP 1810-24G, PL.1.9, eCos-3.0, 1_12_8-customized-h"
```
whereas mine returns:
```
iso.3.6.1.2.1.1.1.0 = STRING: " HP ProCurve 1810G - 24 GE, P.2.2, eCos-2.0, CFE-2.1"
```

The check at the moment is to just search for "ProCurve" in the string's I've included above. This explains why it is not detected as a ProCurve device.

**Comment by laf** [comment]
I think we can update the detection for eCos-[0-9\.]+ as this is hopefully specific to Procurve.

**Comment by azcobain** [comment]
Thanks all, switches are now being detected.

**Comment by Steinies** [comment]
Just want to notice eCos is the Operation System -> "http://ecos.sourceware.org/"
It's not specific to HP or Procurve.
