### ISSUE TITLE
Sensor still get Alerts even when alerts turned off for it.

### ISSUE THREAD

**Issue by Ftelf** [librenms/librenms#1243]
I have a RB2011 with broken temperature sensor. Randomly reports high temperature.
So I did turned alerts for this one sensor off: http://fii.cz/vaqawryq

Alert rules stays, since I still want other sensor to be triggered: http://fii.cz/dzhxz

But I still got email alerts for this particular sensor: http://fii.cz/tevay

Also in Device / log: http://fii.cz/yhbbpmw

But not in Device / Alerts: http://fii.cz/uvhdeedb
But this is empty all the time for all my devices and any other alerts I got.

**Comment by f0o** [comment]
Those settings arent honoured by the alerting.
I will look into it and PR a patch.

**Comment by f0o** [comment]
add '&& %sensors.sensor_alert EQUALS 1' to your rule
