### ISSUE TITLE
Strange memory information on Juniper devices after #12282

### ISSUE THREAD

**Issue by ottorei** [librenms/librenms#12435]
For some reason after the mempools modernization (https://github.com/librenms/librenms/pull/12282) some networking devices are having strange memory graphs and some devices lost all memory information. Mainly MX-routers have odd memory information and for example, EX-4300 switches lost all memory information.

See the attachment from an MX104 router.
![mx104memory2](https://user-images.githubusercontent.com/7031571/104612150-8f08de80-568e-11eb-8ffd-5eefd4ed3cce.PNG)

The total amount of memory seems to be correct and seems to display the memory amount from Routing Engine.
![memory1](https://user-images.githubusercontent.com/7031571/104613164-9e3c5c00-568f-11eb-8223-227345cab935.PNG)

**Comment by Syl4r-v** [comment]
I'm experiencing the same thing with MX80 routers.

**Comment by murrant** [comment]
Routing Engine 0 = 20%/21%  looks correct.

If the other devices do not have memory, then we need a way to be able to filter them from the memory information returned by the device....  Run `lnms poller:discover <HOSTNAME> -m mempools -vv` and pastebin the output.  (or look at it your self to see the snmp data fetched from your device.

**Comment by ottorei** [comment]
> 
> 
> Routing Engine 0 = 20%/21% looks correct.
> 
> If the other devices do not have memory, then we need a way to be able to filter them from the memory information returned by the device.... Run `lnms poller:discover <HOSTNAME> -m mempools -vv` and pastebin the output. (or look at it your self to see the snmp data fetched from your device.

This is from an MX-80 router:
https://pastebin.com/dV9BmFg0

**Comment by ottorei** [comment]
#12443 seems to have fixed incorrect sensors from being discovered
