### ISSUE TITLE
Webui - horizontal scroll bars for alert widgets

### ISSUE THREAD

**Issue by efelon** [librenms/librenms#12454]
Alert widgets on the dashboard always display a horizontal scroll bar which only moves a few pixel. As @murrant suggest in #12453 the issue should not be solved by just hiding the scroll bars with `overflow-x: hidden;`.
![image](https://user-images.githubusercontent.com/10722552/105481182-ffbf8480-5ca6-11eb-901d-b0435be9563d.png)

I looked in the HTML output of the dashboard an found a div with class "row" as first element in the widget_body before the header which causes the scrollbars to appear.
![image](https://user-images.githubusercontent.com/10722552/105502966-4f617880-5cc6-11eb-83ac-e33ac5a9d26e.png)

If I remove (or reduce by 5px) the _margin_right_ element of that additional div class "row" or remove the div completely the scrollbar disappears.

Root cause is the .gridster margins get overwritten by class "row":

```
.row {
    margin-right: -15px;
    margin-left: -15px;
}
```

**Comment by efelon** [comment]
This problem will be worked around by #12459.
I leave this problem open in the case someone wants to have a look anyway.

**Comment by hanserasmus** [comment]
I think since you have a PR open already, it might be better to close the issue, and contain all discussions in the PR.
