### ISSUE TITLE
os.getenv returns a string instead of integer, that breaks REDIS_TIMEOUT if set

### ISSUE THREAD

**Issue by OahzEgroeg** [librenms/librenms#12480]
test-poller(CRITICAL):ERROR: Redis connection required for distributed polling
test-poller(CRITICAL):Could not connect to Redis. an integer is required (got type str)

https://github.com/librenms/librenms/blob/5379176bd80007cc901de87029f6538ed27f6d95/LibreNMS/service.py#L141

**Comment by murrant** [comment]
Looks like you already know the solution.  Please send a PR casting it to an integer.
