### ISSUE TITLE
RAy2- needs to be changed

### ISSUE THREAD

**Issue by littlecake** [librenms/librenms#12516]
I tried to add some Racom wireless lines without success.

I changed the file LibreNMS/OS/Ray.php with adding each OID (.0) on the end and it works well.
Please can someone review the code, may be is there some fail

**Comment by littlecake** [comment]
Can i ask what was wrong ?
The Racom antennas realy does not works without this change .
Best Regards
Michal Kolacek

9. 2. 2021 v 16:52, Kevin Krumm <notifications@github.com<mailto:notifications@github.com>>:



Closed #12516<https://github.com/librenms/librenms/issues/12516>.

**Comment by murrant** [comment]
@littlecake there was an old pull request with this change, but it was never finished. Feel free to search the closed PRs and continue that work.
