### ISSUE TITLE
Orvaldi UPS template wrong voltage OID

### ISSUE THREAD

**Issue by pcolomes** [librenms/librenms#12519]
We own some generic UPS which are polling the device with the wrong OID to obtain both Input and Output voltage. As you can see in the following image, the sensor_oid is set to .1.3.6.1.2.1.33.1.3.3.1.3.0 but this value shows nothing

<img width="858" alt="image" src="https://user-images.githubusercontent.com/30818006/107424813-def78b80-6afc-11eb-9ab7-d622958e22c7.png">

If I query that oid I get a 0
```bash
root@monitoring:~# snmpwalk -c public  -v1 10.120.90.201 .1.3.6.1.2.1.33.1.3.3.1.3.0
iso.3.6.1.2.1.33.1.3.3.1.3.0 = INTEGER: 0
root@monitoring:~# 
```

This is the right OID:
```bash
root@monitoring:~# snmpwalk -c public  -v1 10.120.90.201 .1.3.6.1.2.1.33.1.3.3.1.3.1
iso.3.6.1.2.1.33.1.3.3.1.3.1 = INTEGER: 227
root@monitoring:~# 
```
The code at **includes/discovery/sensors/voltage/rfc1628.inc.php** is using an $index variable which for some reason adds a 0 at the end:

```php
$input_volts = snmpwalk_group($device, 'upsInputVoltage', 'UPS-MIB');
foreach ($input_volts as $index => $data) {
//  $volt_oid = ".1.3.6.1.2.1.33.1.3.3.1.3.$index";
    $volt_oid = ".1.3.6.1.2.1.33.1.3.3.1.3.1";
    $divisor = get_device_divisor($device, $pre_cache['poweralert_serial'], 'voltage', $volt_oid);
    $descr = 'Input';
    if (count($input_volts) > 1) {
        $descr .= " Phase $index";
    }
```

Is this a bug or an intended feature?

**Comment by murrant** [comment]
Likely the sensor_index is the same for all sensors.  Make sure it incorporates the $index variable too so they are both added.

**Comment by pcolomes** [comment]
It should be the same, but not in this case. The $index variable always returns 0 when I run a discovery or poller against an Orvaldi UPS but the index should be 1 to retrieve the correct voltage value.

Why does LibreNMS assign a 0 instead of 1?

**Comment by murrant** [comment]
0 is what snmp returns.  Almost all non-table oids end in 0

**Comment by PipoCanaja** [comment]
@pcolomes If your device supports it, have you tried in SNMP v2 ? I have seen devices behaving a little bit better in v2 instead of v1.

**Comment by pcolomes** [comment]
> @pcolomes If your device supports it, have you tried in SNMP v2 ? I have seen devices behaving a little bit better in v2 instead of v1.

I tried but the device supports only v1.  I don't know how to force LibreNMS to read that OID correctly without altering the source code.

**Comment by PipoCanaja** [comment]
Unfortunately @pcolomes, the issue is the device here, not LibreNMS. So the only proper way to solve it is to have the device follow the rules, or make a dirty hack in the code to handle the wrong code of the device ... 
You might want to analyse the discovery of the device, in verbose and debug mode, as well as play with snmpwalk to see if there is a workaround doable. 

```./discovery.php -h <deviceID> -m sensors -v -d ```

And the snmpwalk command will be visible in the discovery debug for you to play with.

**Comment by PipoCanaja** [comment]
@pcolomes 
You can try to collect the details as described here : 
https://docs.librenms.org/Support/FAQ/#faq20
That would allow somebody else to test without owning the device (unless the snmp-implementation is so buggy that the collection does not give the same results depending if snmpget and snmpwalk is used).
Bye
