### ISSUE TITLE
LibreNMS Syslog retention not applied

### ISSUE THREAD

**Issue by Crash0v3r1de** [librenms/librenms#12515]
Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X ] Please provide **ALL** info asked for [here](https://docs.librenms.org/Support/FAQ/#faq20).
- [ X] Please provide as much detail as possible.
- [ X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Really no info is needed to replicate. I have a LibreNMS install with no distributed pollers being used. I have syslog installed setup and functioning with LibreNMS after following the docs for the install and configure.

My host has a massive amount of syslog entries however it does not clear out the entries overtime. I've even set the retention day to 1 and it did not clear any bit of the log size.

I was told to run daily.php with -f and -d and bellow are the outputs:
php daily.php -f syslog - Does nothing and nothing is outputted
php daily.php -d syslog - Outputs "DEBUG" and does nothing
php daily.php -d -f syslog - Also outputs "DEBUG" and does nothing

Nothing fails on validate and everything besides this growing size of logs works great.

**Comment by murrant** [comment]
Your syslog is too big.  Check the queries in sql while it "does nothing"
Fastest option is to truncate the entire table.
If you need a large amount of syslog storage, check the graylog integration.
