### ISSUE TITLE
Global Read user not able to view Config Tab (despite Oxidized working fine)

### ISSUE THREAD

**Issue by the-coder-within** [librenms/librenms#12534]
Was this issue from 2016 ever resolved as am running into similar problems:
https://github.com/librenms/librenms/issues/3377 

I would really like for a new **Global Read** user to be able to view the **Config** tab for all Devices.

The Admin user is able to view the **Config** tab fine which means Oxidized is working properly.
But I do not want this new user to be an Admin, I want them to stay as **Global Read**

How can I achieve this?

-------------------------------------
Here is my LibreNMS version:

./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.1.0-28-gb86dbcf69
DB Schema | 2021_02_08_224355_fix_invalid_dates (199)
PHP       | 7.4.3
Python    | 3.8.5
MySQL     | 10.3.25-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

**Comment by murrant** [comment]
Global read does not have config access as they contain sensitive data.  If you would like to change this you need to contribute RBAC or make a local change to your install.
