### ISSUE TITLE
Add XOS  X650 vlan collect

### ISSUE THREAD

**Issue by freedomwarrior** [librenms/librenms#12533]
Hello.
Is it possible to add vlan collection for extreme networks x650 ?
Thanks.

**Comment by PipoCanaja** [comment]
Hello @freedomwarrior 
As you probably imagine, without owning and running such device, it will be difficult to do so. Your options : 
- Provide the required informations as described here and wait for somebody to do it: 
https://docs.librenms.org/Support/FAQ/#faq20
- Do it yourself
Bye
