### ISSUE TITLE
Object HP Procurve, Enterasys , Brocade MLX

### ISSUE THREAD

**Issue by ziodona85** [librenms/librenms#12541]
Hi,

i have a problem with some nodes added to LibreNMS:

-Aruba and HP Procurve --> i added object but i can't see Serial Number in the extraction of device database. I have done a debug and i have noticed that during discovery miss the mib file HP-SN-AGENT-MIB. If i add this mib file and i do a debug discovery, the serial was added in librenms object description and in the librenms database, but after a polling the value disappear newly. How can i do modify permanently?

-Enterasys/Extreme we have 2 wifi controller Enterasys/Extreme, same models but with 2 firmware version. The new version controller is marked Extreme with correct symbol and i can see AP and wireless module is corrected loaded with extreme mib, the oldest is marked Enterasys with correct symbol but i can't see graph of APs. I have tried to do a SNMP Walk manually with extreme mib and it answer correctly. How can fix problem for Enterasys controller?

***********NEW*********

#### Load disco module core ####

SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-OUQn' '-m' 'SNMPv2-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/ewc:/opt/librenms/mibs/enterasys' 'udp:HOSTNAME:161' 'sysName.0' 'sysObjectID.0' 'sysDescr.0']

.*.*.0 = HWC-VICO
.*.*.0 = .*.4.1.43*.10
.*.*.0 = Extreme Networks Wireless Controller - C5110-2,  System Version *3  

************OLD*************
#### Load disco module core ####

SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-OUQn' '-m' 'SNMPv2-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/enterasys' 'udp:HOSTNAME:161' 'sysName.0' 'sysObjectID.0' 'sysDescr.0']

*.*.0 = EWC2
.*.*.0 = .*.4.1.43*.10
.*.*.0 = Enterasys Networks, Inc. Wireless Controller - C5110-2,  System Version *4  

-BROCADE-MLX-4, MLXE-16 i can't see ip virtual interface (ve), so i don't have traffic of subinterface and ipv4 address/ipv4 routes in librenms and in the database. How could i fix this problem? 

Could you help me?

Thanks for your work.

Regards.

**PLEASE READ FIRST**

**Please do not post bugs or ask questions or feature requests here**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org/c/help).**

To create a new device request please use this link: https://github.com/librenms/librenms/issues/new?template=New-Device.md

**Comment by PipoCanaja** [comment]
Hello @ziodona85 

> -Aruba and HP Procurve --> i added object but i can't see Serial Number in the extraction of device database. I have done a debug and i have noticed that during discovery miss the mib file HP-SN-AGENT-MIB. If i add this mib file and i do a debug discovery, the serial was added in librenms object description and in the librenms database, but after a polling the value disappear newly. How can i do modify permanently?

Can you please show us here how you temporarily fix the issue ? Do you add a mibfile in the mibs directory ? If yes, you simply need to open a Pull Request and add this mib file, and after next update, the issue will be fixed.

> -Enterasys/Extreme we have 2 wifi controller Enterasys/Extreme, same models but with 2 firmware version. The new version controller is marked Extreme with correct symbol and i can see AP and wireless module is corrected loaded with extreme mib, the oldest is marked Enterasys with correct symbol but i can't see graph of APs. I have tried to do a SNMP Walk manually with extreme mib and it answer correctly. How can fix problem for Enterasys controller?

As far as I can see, we discover them as 2 different OSes because they don't use the same OIDs (and mibs): 
```
~/includes/definitions/enterasys.yaml 
~/includes/definitions/ewc.yaml 
```
And the Wireless code for EWC is here : 
```
LibreNMS/OS/Ewc.php
``` 

But nothing in Enterasys:
```
LibreNMS/OS/Enterasys.php
``` 

So you can probably play with `LibreNMS/OS/Enterasys.php` and get the working sensors from EWC discovery code.

> -BROCADE-MLX-4, MLXE-16 i can't see ip virtual interface (ve), so i don't have traffic of subinterface and ipv4 address/ipv4 routes in librenms and in the database. How could i fix this problem?

Virtual interfaces might be filtered by default. Have a look here :
[https://docs.librenms.org/Developing/os/Settings/](https://docs.librenms.org/Developing/os/Settings/)

Bye
