### ISSUE TITLE
DB Schema 

### ISSUE THREAD

**Issue by ataullahsaleem** [librenms/librenms#12552]
![image](https://user-images.githubusercontent.com/70479567/108812242-9f3aa480-75d0-11eb-8d31-dedeac2bf66a.png)
once i fix librenms@netplus-NMS:~$ ./lnms migrate
anyone help me please i have using Nginx in UBUNTU

**Comment by ataullahsaleem** [comment]
and while build database/Configure Database  via Web interface 
Starting Update...
Migration table created successfully.
Migrating: 2018_07_03_091314_create_access_points_table
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'access_points' already exists (SQL: create table `access_points` (`accesspoint_id` int unsigned not null auto_increment primary key, `device_id` int unsigned not null, `name` varchar(255) not null, `radio_number` tinyint null, `type` varchar(16) not null, `mac_addr` varchar(24) not null, `deleted` tinyint(1) not null default '0', `channel` tinyint unsigned not null default '0', `txpow` tinyint not null default '0', `radioutil` tinyint not null default '0', `numasoclients` smallint not null default '0', `nummonclients` smallint not null default '0', `numactbssid` tinyint not null default '0', `nummonbssid` tinyint not null default '0', `interference` tinyint unsigned not null) default character set utf8 collate 'utf8_unicode_ci')

Error!

**Comment by murrant** [comment]
Seems like your database is VERY old, run `./includes/sql-schema/update.php` to attempt to update it.
