### ISSUE TITLE
Add support for mysql-snmp

### ISSUE THREAD

**Issue by drybjed** [librenms/librenms#1255]
[mysql-snmp](https://github.com/masterzen/mysql-snmp) is a SNMP subagent which connects to a MariaDB/MySQL server, as well as `snmpd` AgentX instance and allows monitoring of MariaDB/MySQL database using SNMP.

I'd like to propose adding support for `mysql-snmp` in LibreNMS - this means adding necessary MIBs and providing UI pages for database monitoring.

I'm aware of the `check_mk_agent` UNIX agent and a way to monitor the database using it, however this requires adding `xinetd` and potentially making bigger attack surface on the database server. Connection to `check_mk_agent` needs to be encrypted separately using a `stunnel`, VPN, or SSH tunnel, which also requires additional configuration.

In contrast to the above, SNMPv3 is already present on the server due to the monitoring of the host itself by LibreNMS, and offers reliable encryption without all the configuration headache with separate tunnels/VPN.

**Comment by f0o** [comment]
:+1:

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
