### ISSUE TITLE
Custom background image for login screen

### ISSUE THREAD

**Issue by tommybuck** [librenms/librenms#12589]
Please could you add a field under the Global Config - Web UI - Style that would allow a login screen background image to be added? Then add it to the styles.css so it shows up on the login screen?

I have currently added the background-image setting to the styles.css under the body tag. It looks really cool but it applies it to all pages and not just the login screen.

**Comment by murrant** [comment]
Sounds like neat idea, you should add it to the feature requests on https://community.librenms.org
