### ISSUE TITLE
Cisco NCS exclusion for Cisco XR dBm workaround

### ISSUE THREAD

**Issue by WillIrvine** [librenms/librenms#12591]
Cisco ASR9K devices have previously needed a work around to obtain correct dBm values from their transceivers.
This is because the ASR9K devices only return these values as a wattage value, rather than a dBm value.

The pull request below was added to fix these in XR devices.
https://github.com/librenms/librenms/pull/1661
https://github.com/librenms/librenms/issues/1641

The code in question is here, it builds a "fake sensor" to map the watt values as dBm results after a conversion

https://github.com/librenms/librenms/blob/master/includes/discovery/sensors/cisco-entity-sensor.inc.php#L201

Since this pull request, some of the newer XR devices (Namely, the NCS series) does report correct dBm values, what now happens is that this conversion logic is now applied to these values that are already correct and returns a very incorrect value.

![image](https://user-images.githubusercontent.com/32685892/110253948-bd9d9880-7ff1-11eb-8d02-ac42b6637114.png)

Now, i've tested excluding devices with NCS in the "hardware" field, however I wanted to start a discussion about how this should best be approached.

Would it be better to:

1. Statically exclude XR devices that do provide correct dBm values from this logic to convert watts to dbm
2. Change the current logic to statically include XR devices that do not return dBm vlaues (potentially breaking some users setups while we determine what devices these are, currently i only believe ASR9K routers do this)
3. try and add a check somehow to see what values the devices return and apply the correct logic (unsure how we would approach this)

Currently i've tested excluding NCS devices in the logic, as i know those return the correct values and that has turned out correctly below.

![image](https://user-images.githubusercontent.com/32685892/110254496-44537500-7ff4-11eb-94e4-5c9a7cdb9fcd.png)

**PLEASE READ FIRST**

**Please do not post bugs or ask questions or feature requests here**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org/c/help).**

To create a new device request please use this link: https://github.com/librenms/librenms/issues/new?template=New-Device.md

**Comment by PipoCanaja** [comment]
Hi @WillIrvine 
Excluding "per model" is an option of course, but it requires updates every time Cisco changes something. Which happened with NCS family it seems. 
A better way would be to find out if the value is Watts or dBm. Any chance to deduct this information from the value that was read ? or from another OID ?

**Comment by WillIrvine** [comment]
Thanks Pipo, Yea correct, i don't like the per device exclusion, it has the potential to get messy and out of hand.
I've dug into this a bit further, it looks as though the sensors actually discover correctly, but are overwritten after the first polling cycle due to this polling file

https://github.com/librenms/librenms/blob/master/includes/polling/sensors/dbm/iosxr.inc.php

This applies the mW to dBm conversion on all dBm values, not only the ones that were originally mW and converted.
I'll see if i can work out some logic to extract what the sensor value originally was and only apply it to that.

**Comment by WillIrvine** [comment]
I have worked this out and will submit a pull request soon. Just working with Cisco to fix a bug with the 9001 chassis reporting an incorrect precision value
