### ISSUE TITLE
Missing bind query graphs

### ISSUE THREAD

**Issue by cousintroy** [librenms/librenms#1259]
I believe I followed the documentation correctly as 95% of my Librenms is working correctly.  However, I have two bind servers (master/slave) to which I have being monitored by Librenms and the queries graphs show broken image icons.  Librenms is installed on an Ubuntu (14.04 LTS) VM.  I have searched librenms Github and online but have not found any information regarding this issue.

Any help would be appreciated!
Thanks

**Comment by f0o** [comment]
Have you followed http://docs.librenms.org/Extensions/Agent-Setup/ ?
Does `telnet bind.domain.tld 6556` return the data found in `/etc/bind/named.stats` from your bind-server?

**Comment by cousintroy** [comment]
f0o...thanks for the link.  I may have missed that part and, briefly looking over the page, that may be the issue.  I will work on that over the weekend and write back with the results.  Again...thanks for the link.

**Comment by cousintroy** [comment]
f0o...unfortunately that didn't work but it may still be the issue.  When I get more time I will work at it...thanks again.

**Comment by soamz** [comment]
It asks for application, dont know what to enter.

**Comment by laf** [comment]
Please create your own issue or ask for help in irc.
