### ISSUE TITLE
API does not return VLAN on Juniper QFX-5120-32C even though the UI shows it.

### ISSUE THREAD

**Issue by dnowacki91** [librenms/librenms#12607]
API call does not return VLAN IDs even though they are displayed in the UI for the same port.

Query: curl -H 'X-Auth-Token: YOURAPITOKENHERE' https://LIBRE/api/v0/ports/2985

```
      "ifVlan" => ""
      "ifTrunk" => null
```

UI displays this information for xe-0/0/12:1, I have enclosed API results for xe-0/0/12:1 and xe-0/0/12:1.0 just in case.
This doesn't return value for any port.

<img width="350" alt="Screenshot 2021-03-11 at 10 07 25" src="https://user-images.githubusercontent.com/55637685/110771081-03589c00-8252-11eb-9429-75c843ef2ff9.png">
<img width="349" alt="Screenshot 2021-03-11 at 10 07 12" src="https://user-images.githubusercontent.com/55637685/110771088-05225f80-8252-11eb-9ce5-babf6fcd1894.png">

![image](https://user-images.githubusercontent.com/55637685/110771296-3ac74880-8252-11eb-9e63-48270ebc4f78.png)

**Comment by murrant** [comment]
FYI, ifVlan only shows the native vlan and only if it was filled during polling.

**Comment by Ashark** [comment]
The problem is not specific to Juniper, but also for Cisco.

> FYI, ifVlan only shows the native vlan and only if it was filled during polling.

Is it intentional? Then how to receive info about all other tagged vlans?

**Comment by Ashark** [comment]
As a temporary workaround, I have created a script to get info of vlans from web interface.
See https://gist.github.com/Ashark/9a6a0c2af5b7c78e4acad7a07e96eb7e

**Comment by PipoCanaja** [comment]
Hi @Ashark 
This issue is more a feature request to add the list of VLANs. Feel free to open a PR to implement it. 
Thx
