### ISSUE TITLE
web-ui-snmpv3-password-in-plain-text

### ISSUE THREAD

**Issue by Naithachal** [librenms/librenms#12609]
i knew i shouldn't but obviously no one cares for a Security issue i reportet months ago.
I had to take down Libre in our Network because it's to dangerous.
https://community.librenms.org/t/web-ui-snmpv3-password-in-plain-text-settings-poller-snmp/14197

**Comment by PipoCanaja** [comment]
Hello @Naithachal 
This project is run by contributors like you and me, providing patch when something should be pathed. So you are very welcome to provide a patch to improve LibreNMS. 
Bye

**Comment by murrant** [comment]
I'm not so sure administrators being able to view read-only passwords is a security issue.
I have a feeling, many would be annoyed if they could not view it in the administrator area, so if you want to replace them with dots, you probably need to implement a view password button.
