### ISSUE TITLE
rfc1628 UPS metrics for output phases intermingled with input and bypass ones

### ISSUE THREAD

**Issue by einhirn** [librenms/librenms#1260]
Currently it's looking like this:

```
Voltage
Output Phase 1      230V
Battery         272.6V
Input Phase 1       232V
Input Phase 2       232V
Input Phase 3       233V
Output Phase 2      231V
Bypass Phase 1      231V
Bypass Phase 2      233V
Bypass Phase 3      232V
Output Phase 3      232V

Current
Output Phase 1      52A
Input Phase 1       3A
Input Phase 2       2A
Input Phase 3       2A
Output Phase 2      52A
Bypass Phase 1      NaNA
Bypass Phase 2      NaNA
Bypass Phase 3      NaNA
Output Phase 3      53A
Battery         NaNA
```

when of course "Output 1", "Output 2" and "Output 3" should be listed together.

Working on it in [rztuc/librenms#1260](/rztuc/librenms/tree/issue-1260)

**Comment by einhirn** [comment]
Since changing indices of existing sensors means losing historic data, @laf suggested this to be fixed in WebUI. The items would have to be sorted numerically instead of lexicographically. Current results are like this:
```
1
101
102
103
2
201
202
203
3
500
```

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by einhirn** [comment]
I don't know if this is still an issue, because we stopped monitoring our UPSses with librenms. Probably still in there because of autodetection, but doesn't matter any more. So, if no one else has had a problem with this, let's just close it until it comes up again.
