### ISSUE TITLE
RealTime Graphs shows wrong information

### ISSUE THREAD

**Issue by Cupidazul** [librenms/librenms#12610]
**PLEASE READ FIRST**

**Please do not post bugs or ask questions or feature requests here**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org/c/help).**

To create a new device request please use this link: https://github.com/librenms/librenms/issues/new?template=New-Device.md

I bellieve that the graph-realtime.php is showing MB and Mb information inverted, because if we look at the interface utilization that is usually in Mbps, this matches the utilization seen in realtime but only if we select to see it in MB. This should be a simple fix. just swap-out MB with Mb.

Look:
![image](https://user-images.githubusercontent.com/12242582/110924249-bc35de00-8319-11eb-9b91-0b26704d6e1b.png)

**Comment by murrant** [comment]
The top summary is from up to five minutes ago.  There is almost no way they would ever match.

**Comment by Cupidazul** [comment]
> The top summary is from up to five minutes ago. There is almost no way they would ever match.

I'm still having some issues in this topic, with a 1Gb connection I should not get 2Gb utilization, the average input throught in this link is 400mbps...

![image](https://user-images.githubusercontent.com/12242582/111126356-850a3b80-856a-11eb-9b3c-b97621758151.png)

![image](https://user-images.githubusercontent.com/12242582/111126484-ab2fdb80-856a-11eb-83c2-7680c4aedfb1.png)

**Comment by murrant** [comment]
See the orange text? Caching may be in effect, estimated 2s cache.   This means at 1s interval the device will return the same value two times in a row, then return the change since 2s ago, resulting in a doubling of the rate of change.  There is no way to prevent this other than lock the refresh at a minimum of 2s for your particular device.

**Comment by murrant** [comment]
Perhaps the text should be red and blink...

**Comment by Cupidazul** [comment]
Look, I see what you mean with the orange text, and I understand. I really do. But that should happen only in the first seconds...
But this is happenning not just in a few seconds, during caching... 
Regardless of the time I wait for caching to stop, I'm allways getting these values in realtime, sometimes, I get the impression that I'm having +2Gbps of traffic when this is not true, this link is only 1Gb. And it is not overloaded, most of the times it maxes out at 50%, not much more than that.

This is a device with a quite stable and predictable growth of throughput.
It doesn't make sense, the atual traffic now was about 74Mbps, I do not have 200+ Mbps neither in or out.
This is quite clear here:
![image](https://user-images.githubusercontent.com/12242582/111222904-57f27300-85d4-11eb-8294-54b8f07e32da.png)

For me, this information really seams swapped out, I don't know if these high-speed OID's work differently, but this BW is not right. I'm sure that the BW in MB is correct, and Mbps it is not. I can provide a fix, if you need my help.

Cheers.

**Comment by Cupidazul** [comment]
I've waitted for (much) more than 10 secs jus to be sure, and got this print again:

![image](https://user-images.githubusercontent.com/12242582/111223463-17dfc000-85d5-11eb-9af3-388568345dbf.png)

**Comment by Cupidazul** [comment]
Again, we don't see realtime utilization bellow 100Mbps, and for sure thats where we are 'now' :

![image](https://user-images.githubusercontent.com/12242582/111223818-8de42700-85d5-11eb-9071-5018a97812d4.png)

**Comment by Cupidazul** [comment]
I see this is occurring for more than one device in several interfaces with 1Gb connectivity or more.
Sorry for the trouble.
Thx.

**Comment by Cupidazul** [comment]
Maybe I'm wrong here. I'm getting alot more throughput than expected. I need more tests.

**Comment by murrant** [comment]
Because LibreNMS is not the thing doing the caching, it is the device.  LibreNMS had no control or indication the caching is happening.  It can only guess it is happening using a heuristic.

In summary you can only view realtime at 5s intervals.  This is your device's fault and LibreNMS cannot do anything to change that.

If you still don't believe me, run snmpget on ifInOctects of ifOutOctets, several times in a row and check the values returned.

**Comment by Cupidazul** [comment]
ok. Thank you for your kind reply,
