### ISSUE TITLE
Edit SNMPv3 Crypto Algorithm : DES appears as AES when saved.

### ISSUE THREAD

**Issue by Cupidazul** [librenms/librenms#12727]
https://github.com/librenms/librenms/blob/edb36fd69defe1c7f54b9ba2dff15f45fe583a36/includes/html/pages/device/edit/snmp.inc.php#L389

Atual Code:
```
    <option value='AES' " . ($device['cryptoalgo'] === 'AES' ? 'selected' : '') . ">AES</option>
    <option value='AES-192' " . ($device['cryptoalgo'] === 'AES-192' ? 'selected' : '') . ($snmpv3_aes256 ?: ' disabled') . ">AES-192</option>
    <option value='AES-256' " . ($device['cryptoalgo'] === 'AES-256' ? 'selected' : '') . ($snmpv3_aes256 ?: ' disabled') . ">AES-256</option>
    <option value='AES-256-C' " . ($device['cryptoalgo'] === 'AES-256-C' ? 'selected' : '') . ($snmpv3_aes256 ?: ' disabled') . ">AES-256 Cisco</option>
    <option value='DES'>DES</option>

```
Proposed CHG:   ( simply put DES on top of the options list )
```
    <option value='DES'>DES</option>
    <option value='AES' " . ($device['cryptoalgo'] === 'AES' ? 'selected' : '') . ">AES</option>
    <option value='AES-192' " . ($device['cryptoalgo'] === 'AES-192' ? 'selected' : '') . ($snmpv3_aes256 ?: ' disabled') . ">AES-192</option>
    <option value='AES-256' " . ($device['cryptoalgo'] === 'AES-256' ? 'selected' : '') . ($snmpv3_aes256 ?: ' disabled') . ">AES-256</option>
    <option value='AES-256-C' " . ($device['cryptoalgo'] === 'AES-256-C' ? 'selected' : '') . ($snmpv3_aes256 ?: ' disabled') . ">AES-256 Cisco</option>
```

Details:
'DES'  should come first, since there is no 'selected' code in place for it to be the selected option.
In my case I had 'DES' saved on a device, and 'AES' was allways showing up as the saved selection. What happens is that, there is no 'selected' in the options list, and HTML will leave the first option on the list as the default when there is no 'selected' option set, with the Actual Code 'AES' will allways come first if 'DES' is saved to DB.

This is a minor fix, Thx.
Cheers.

**Comment by murrant** [comment]
@Cupidazul correct fix should be to set DES as selected like the others... Someone moved it to the bottom on purpose but did not include the select code.

**Comment by Cupidazul** [comment]
yeah. that'll do to...
cheers.

**Comment by Jellyfrog** [comment]
Should be fixed in nightly
