### ISSUE TITLE
Displaying CPU usage on UAP-HD need to use multiplier 0,01

### ISSUE THREAD

**Issue by andrzejmaczka** [librenms/librenms#12726]
Hi , i double checked output from snmp and 'top' for UniFi UAP-HD device and in my opinion  CPU should be multiplier 0,01

snmpwalk -v 2c -c  ###  ###.###.###.### .1.3.6.1.4.1.10002.1.1.1.4.2.1.3
SNMPv2-SMI::enterprises.10002.1.1.1.4.2.1.2.1 = STRING: "1 Minute Average"
SNMPv2-SMI::enterprises.10002.1.1.1.4.2.1.2.2 = STRING: "5 Minute Average"
SNMPv2-SMI::enterprises.10002.1.1.1.4.2.1.2.3 = STRING: "15 Minute Average"
SNMPv2-SMI::enterprises.10002.1.1.1.4.2.1.3.1 = Gauge32: 104
SNMPv2-SMI::enterprises.10002.1.1.1.4.2.1.3.2 = Gauge32: 103
SNMPv2-SMI::enterprises.10002.1.1.1.4.2.1.3.3 = Gauge32: 100

od the device it looks 

CPU:  0% usr  1% sys  0% nic 98% idle  0% io  0% irq  0% sirq

Load average: 1.04 1.03 1.00 2/113 21785

**Comment by murrant** [comment]
would be cool if unifi gave us cpu usage instead of only load average...

**Comment by andrzejmaczka** [comment]
I agree, but what can I do :)

**Comment by andrzejmaczka** [comment]
Until the UI provides CPU usage, it's better not to show these graphs as they are very confusing
![image](https://user-images.githubusercontent.com/67277751/114178888-96165480-993e-11eb-914f-4bb03fbb596c.png)

**Comment by murrant** [comment]
Send a pull request modifying the divisor.

**Comment by andrzejmaczka** [comment]
i don't have enough experience to contribute this project

**Comment by murrant** [comment]
Neither did I when I started, but I did it anyway.  You can do it.
https://docs.librenms.org/Developing/os/Health-Information/#simple-health-discovery

**Comment by murrant** [comment]
Maybe fixed by #12854
