### ISSUE TITLE
Files for new Device GUDEADS ATS3020

### ISSUE THREAD

**Issue by back2live** [librenms/librenms#12762]
Hello,

i already implemented a new device.
maybe you can add these changes:

/opt/librenms/includes/definitions/discovery/ets.yaml
and
/opt/librenms/mibs/gude/GUDEADS-ATS3020-MIB

Andy
i added .txt for upload

[ets.yaml.txt](https://github.com/librenms/librenms/files/6317586/ets.yaml.txt)
[GUDEADS-ATS3020-MIB.txt](https://github.com/librenms/librenms/files/6317595/GUDEADS-ATS3020-MIB.txt)

**Comment by PipoCanaja** [comment]
Hello @back2live 
You can directly open a pull request with the files to get those changes merged into LibreNMS.
Bye

**Comment by Jellyfrog** [comment]
Please open a pull request with your changes instead
