### ISSUE TITLE
keep-hostname(yes); in syslog-ng config options

### ISSUE THREAD

**Issue by solune** [librenms/librenms#12760]
Hi,
I'm relaying syslog messages like this : device->central-syslog-server -> kubernetes cluster -> librenms-syslog-ng-docker.
It works so good but I need to add the keep-hostname(yes) to the /etc/syslog-ng/syslog-ng.conf like this

```
options {
    chain_hostnames(off);
    flush_lines(0);
    use_dns(no);
    use_fqdn(no);
    owner("root");
    group("adm");
    perm(0640);
    stats_freq(0);
    bad_hostname("^gconfd$");
    keep-hostname(yes);
};
```
Can you add it by défault or make a config variable to set it ?
Regards

**Comment by PipoCanaja** [comment]
Hello @solune 
syslog-ng config is not part of LibreNMS. So there is nothing LibreNMS can really do about its default options. 
Bye
