### ISSUE TITLE
./lnms migrate fails SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by frankmcc** [librenms/librenms#12770]
My LibreNMS installation failed over the weekend.  I'm assuming a failed update.  Nothing much in the logs other than:
Error in printer-supplies module. SQLSTATE[42S02]: Base table or view not found: 1146 Table 'librenms.printer_supplies' doesn't exist.

Did this:
-----------------------------------------------------------------------------------------------------------------------------------
**php validate.php**
====================================
Component | Version
--------- | -------
LibreNMS  | 21.4.0
DB Schema | 2020_12_14_091314_create_port_groups_table (203)
PHP       | 7.4.3
Python    | 3.8.5
MySQL     | 10.3.25-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.0.12
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[FAIL]  Your database is out of date!
        [FIX]:
        ./lnms migrate

**run ./lnms migrate and it fails with**

Migrating: 2021_02_09_122930_migrate_to_utf8mb4

In Connection.php line 678:

  SQLSTATE[HY000] [2002] Connection refused (SQL: ALTER TABLE `syslog`
                      MODIFY `facility`
                      varchar(10)
                      CHARACTER SET utf8mb4
                      COLLATE utf8mb4_unicode_ci
                      NULL ;)

In Exception.php line 18:

  SQLSTATE[HY000] [2002] Connection refused

In PDOConnection.php line 39:

  SQLSTATE[HY000] [2002] Connection refused
---------------------------------------------------------------------------------------------------------------------------------

**I would assume the migrate job should fix this, but It won't complete.  I'm in a catch-22 here.**

**Additional info:
I ran lnms migrate --force -vvv which went along well until:**

SQL[select * from `information_schema`.`columns` where `table_schema` = ? and `CHARACTER_SET_NAME` is not null and `COLLATION_NAME` is not null and (`CHARACTER_SET_NAME` != ? or `COLLATION_NAME` != ?) ["librenms","utf8mb4","utf8mb4_unicode_ci"] 14.14ms]

SQLSTATE[HY000] [2002] Connection refused (SQL: ALTER TABLE `syslog`
                    MODIFY `facility`
                    varchar(10)
                    CHARACTER SET utf8mb4
                    COLLATE utf8mb4_unicode_ci
                    NULL ;) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] Connection refused (SQL: ALTER TABLE `syslog`
                    MODIFY `facility`
                    varchar(10)
                    CHARACTER SET utf8mb4
                    COLLATE utf8mb4_unicode_ci
                    NULL ;) at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:678)
[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)
[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"}

In Connection.php line 678:

  [Illuminate\Database\QueryException (2002)]
  SQLSTATE[HY000] [2002] Connection refused (SQL: ALTER TABLE `syslog`
                      MODIFY `facility`
                      varchar(10)
                      CHARACTER SET utf8mb4
                      COLLATE utf8mb4_unicode_ci
                      NULL ;)

Exception trace:
  at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
 Illuminate\Database\Connection->runQueryCallback() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:752
 Illuminate\Database\Connection->tryAgainIfCausedByLostConnection() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:732
 Illuminate\Database\Connection->handleQueryException() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:641
 Illuminate\Database\Connection->run() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:524
 Illuminate\Database\Connection->unprepared() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:371
 Illuminate\Database\DatabaseManager->__call() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
 Illuminate\Support\Facades\Facade::__callStatic() at /opt/librenms/database/migrations/2021_02_09_122930_migrate_to_utf8mb4.php:77
 MigrateToUtf8mb4->migrateCharsetTo() at /opt/librenms/database/migrations/2021_02_09_122930_migrate_to_utf8mb4.php:15
 MigrateToUtf8mb4->up() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:392
 Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:401
 Illuminate\Database\Migrations\Migrator->runMigration() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:200
 Illuminate\Database\Migrations\Migrator->runUp() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:165
 Illuminate\Database\Migrations\Migrator->runPending() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:110
 Illuminate\Database\Migrations\Migrator->run() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:85
 Illuminate\Database\Console\Migrations\MigrateCommand->Illuminate\Database\Console\Migrations\{closure}() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:541
 Illuminate\Database\Migrations\Migrator->usingConnection() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:94
 Illuminate\Database\Console\Migrations\MigrateCommand->handle() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php:40
 Illuminate\Container\Util::unwrapIfClosure() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
 Illuminate\Container\BoundMethod::call() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php:611
 Illuminate\Container\Container->call() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
 Illuminate\Console\Command->execute() at /opt/librenms/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php:121
 Illuminate\Console\Command->run() at /opt/librenms/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at /opt/librenms/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at /opt/librenms/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Application.php:92
 Illuminate\Console\Application->run() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:129
 Illuminate\Foundation\Console\Kernel->handle() at /opt/librenms/app/Console/Kernel.php:72
 App\Console\Kernel->handle() at /opt/librenms/lnms:40

In Exception.php line 18:

  [Doctrine\DBAL\Driver\PDO\Exception (2002)]
  SQLSTATE[HY000] [2002] Connection refused

Exception trace:
  at /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
 Doctrine\DBAL\Driver\PDO\Exception::new() at /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
 Doctrine\DBAL\Driver\PDOConnection->__construct() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:67
 Illuminate\Database\Connectors\Connector->createPdoConnection() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:100
 Illuminate\Database\Connectors\Connector->tryAgainIfCausedByLostConnection() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:50
 Illuminate\Database\Connectors\Connector->createConnection() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php:24
 Illuminate\Database\Connectors\MySqlConnector->connect() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:184
 Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}() at n/a:n/a
 call_user_func() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:949
 Illuminate\Database\Connection->getPdo() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:520
 Illuminate\Database\Connection->Illuminate\Database\{closure}() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
 Illuminate\Database\Connection->runQueryCallback() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:752
 Illuminate\Database\Connection->tryAgainIfCausedByLostConnection() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:732
 Illuminate\Database\Connection->handleQueryException() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:641
 Illuminate\Database\Connection->run() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:524
 Illuminate\Database\Connection->unprepared() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:371
 Illuminate\Database\DatabaseManager->__call() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
 Illuminate\Support\Facades\Facade::__callStatic() at /opt/librenms/database/migrations/2021_02_09_122930_migrate_to_utf8mb4.php:77
 MigrateToUtf8mb4->migrateCharsetTo() at /opt/librenms/database/migrations/2021_02_09_122930_migrate_to_utf8mb4.php:15
 MigrateToUtf8mb4->up() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:392
 Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:401
 Illuminate\Database\Migrations\Migrator->runMigration() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:200
 Illuminate\Database\Migrations\Migrator->runUp() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:165
 Illuminate\Database\Migrations\Migrator->runPending() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:110
 Illuminate\Database\Migrations\Migrator->run() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:85
 Illuminate\Database\Console\Migrations\MigrateCommand->Illuminate\Database\Console\Migrations\{closure}() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:541
 Illuminate\Database\Migrations\Migrator->usingConnection() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:94
 Illuminate\Database\Console\Migrations\MigrateCommand->handle() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php:40
 Illuminate\Container\Util::unwrapIfClosure() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
 Illuminate\Container\BoundMethod::call() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php:611
 Illuminate\Container\Container->call() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
 Illuminate\Console\Command->execute() at /opt/librenms/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php:121
 Illuminate\Console\Command->run() at /opt/librenms/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at /opt/librenms/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at /opt/librenms/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Application.php:92
 Illuminate\Console\Application->run() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:129
 Illuminate\Foundation\Console\Kernel->handle() at /opt/librenms/app/Console/Kernel.php:72
 App\Console\Kernel->handle() at /opt/librenms/lnms:40

In PDOConnection.php line 39:

  [PDOException (2002)]
  SQLSTATE[HY000] [2002] Connection refused

Exception trace:
  at /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39
 PDO->__construct() at /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39
 Doctrine\DBAL\Driver\PDOConnection->__construct() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:67
 Illuminate\Database\Connectors\Connector->createPdoConnection() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:100
 Illuminate\Database\Connectors\Connector->tryAgainIfCausedByLostConnection() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:50
 Illuminate\Database\Connectors\Connector->createConnection() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php:24
 Illuminate\Database\Connectors\MySqlConnector->connect() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:184
 Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}() at n/a:n/a
 call_user_func() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:949
 Illuminate\Database\Connection->getPdo() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:520
 Illuminate\Database\Connection->Illuminate\Database\{closure}() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
 Illuminate\Database\Connection->runQueryCallback() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:752
 Illuminate\Database\Connection->tryAgainIfCausedByLostConnection() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:732
 Illuminate\Database\Connection->handleQueryException() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:641
 Illuminate\Database\Connection->run() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:524
 Illuminate\Database\Connection->unprepared() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:371
 Illuminate\Database\DatabaseManager->__call() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
 Illuminate\Support\Facades\Facade::__callStatic() at /opt/librenms/database/migrations/2021_02_09_122930_migrate_to_utf8mb4.php:77
 MigrateToUtf8mb4->migrateCharsetTo() at /opt/librenms/database/migrations/2021_02_09_122930_migrate_to_utf8mb4.php:15
 MigrateToUtf8mb4->up() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:392
 Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:401
 Illuminate\Database\Migrations\Migrator->runMigration() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:200
 Illuminate\Database\Migrations\Migrator->runUp() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:165
 Illuminate\Database\Migrations\Migrator->runPending() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:110
 Illuminate\Database\Migrations\Migrator->run() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:85
 Illuminate\Database\Console\Migrations\MigrateCommand->Illuminate\Database\Console\Migrations\{closure}() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:541
 Illuminate\Database\Migrations\Migrator->usingConnection() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:94
 Illuminate\Database\Console\Migrations\MigrateCommand->handle() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php:40
 Illuminate\Container\Util::unwrapIfClosure() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
 Illuminate\Container\BoundMethod::call() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php:611
 Illuminate\Container\Container->call() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
 Illuminate\Console\Command->execute() at /opt/librenms/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php:121
 Illuminate\Console\Command->run() at /opt/librenms/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at /opt/librenms/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at /opt/librenms/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Application.php:92
 Illuminate\Console\Application->run() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:129
 Illuminate\Foundation\Console\Kernel->handle() at /opt/librenms/app/Console/Kernel.php:72
 App\Console\Kernel->handle() at /opt/librenms/lnms:40

**Comment by murrant** [comment]
Your database server is refusing the connection for some reason.  Make sure you are running at least MySQL 5.7.7 or MariaDB 10.2.2.

**Comment by cliffalbert** [comment]
I have this exact same problem. It's probably not LibreNMS related, because the query crashes MariaDB 10.3.x on Ubuntu 20.04.3

**Comment by murrant** [comment]
@cliffalbert would be helpful if you could isolate the problematic query.  (it is not the one shown in OP, that fails because something failed before)
