### ISSUE TITLE
Can't use function return value in write context in /opt/librenms/html/install.php on line 35

### ISSUE THREAD

**Issue by chilicuil** [librenms/librenms#1278]
Hi,

I recently installed librenms (commit 1b7bbf86049520a20d3737b903ab2c15c1c7f27e) and the installation phase failed with the above code.

I'm using PHP 5.3.10-1ubuntu3.18 on Ubuntu 12.04.

Looking at the code I was able to continue the installation process by editing the offending line with:

```
$end_dir = end($cur_dir);
if( empty($end_dir) ) {
```

Thanks for providing such an awesome alternative to the original project.

**Comment by f0o** [comment]
Hi,

PHP5.3 is not 100% supported, Can you get a PHP5.4 or PHP5.5 via backports?

Cheers

**Comment by laf** [comment]
I ran php5.3 up until a few months ago without issue - what part of the code have you made those changes?

Currently we don't actually state min versions for anything which we should get in there. Like the alerting system, we possibly should set a date where we say that php 5.3 will no longer be actively supported. I know when I was running it we had to alter a PR or two as it wasn't compatible.

Also, may be worth doing some checks on versions at upgrade time?

**Comment by chilicuil** [comment]
Thanks for pointing it out, maybe the instructions at http://docs.librenms.org/Installation/Installation-(Debian-Ubuntu)/ could be updated to state than a php backport version is required on Ubuntu 12.04 systems, I could do that if you want =)

**Comment by runnane** [comment]
Hi
empty() can only be used on variables in PHP versions < 5.5. So if I am not mistaken, this error would also cause a Fatal error on version 5.4. (The stable on Debian Wheezy)

**Comment by f0o** [comment]
Works fine in PHP5.4 on wheezy

```shell
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.8 (wheezy)
Release:        7.8
Codename:       wheezy

# php --version
PHP 5.4.39-0+deb7u2 (cli) (built: Mar 25 2015 08:33:29) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
```

```php
<?php
$foo = array('bar','baz');
$test = end($foo);
if( empty($test) ) {
  var_dump('$test is empty');
} else {
  var_dump('$test is not empty');
}
?>
```

```shell
# php -f test.php 
string(18) "$test is not empty"
```

**Comment by runnane** [comment]
Hi f0o
The install.php in the current version has the code `empty(end($cur_dir))` which do not work in PHP 5.4
Your example has moved the end() function out of empty. 

```
if( empty(end($cur_dir)) ) {
  $install_dir = array_pop($cur_dir);
}
```
I agree that the workaround you and chilicuil noted, of moving the end() function solves the issue, I just wanted to make you aware that the install.php in master is only runnable with 5.5 or higher. :)

**Comment by f0o** [comment]
Oh I see, pardon then I totally misread the quoted text as 'is' instead of 'should-be'.
PR is on the way.

**Comment by f0o** [comment]
Solved & Merged
