### ISSUE TITLE
Javascript error when trying to create rule 'device unpolled' from collection

### ISSUE THREAD

**Issue by ahmedsajid** [librenms/librenms#12801]
Creating rule 'device unpolled' from collection fails with Javascript error in browser console. 
Here are the steps to reproduce:
1. Bring up LibreNMS deployment using docker-compose environment https://github.com/librenms/docker/tree/master/examples/compose
2. Navigate to alert-rules page http://127.0.0.1:8000/alert-rules
3. Click on 'Create rule from collection'
4. Look up 'Device unpolled'
5. Click Select
6. Nothing gets added.
7. If you have developer tool open you should see javascript error on your console.
```
Uncaught UndefinedFilterError: Undefined filter "UNIX_TIMESTAMP() - UNIX_TIMESTAMP(devices.last_polled)"
    error http://127.0.0.1:8000/js/query-builder.standalone.min.js:7
    getFilterById http://127.0.0.1:8000/js/query-builder.standalone.min.js:6
    d http://127.0.0.1:8000/js/query-builder.standalone.min.js:6
    d http://127.0.0.1:8000/js/query-builder.standalone.min.js:6
    setRules http://127.0.0.1:8000/js/query-builder.standalone.min.js:6
    queryBuilder http://127.0.0.1:8000/js/query-builder.standalone.min.js:7
    loadRule http://127.0.0.1:8000/alert-rules:865
    success http://127.0.0.1:8000/alert-rules:1833
    jQuery 8
    hideModal http://127.0.0.1:8000/js/bootstrap.min.js:6
    g http://127.0.0.1:8000/js/bootstrap.min.js:6
    i jQuery
    handle http://127.0.0.1:8000/js/bootstrap.min.js:6
    jQuery 7
    e http://127.0.0.1:8000/js/bootstrap.min.js:6
    setTimeout handler*a.fn.emulateTransitionEnd http://127.0.0.1:8000/js/bootstrap.min.js:6
    backdrop http://127.0.0.1:8000/js/bootstrap.min.js:6
    hideModal http://127.0.0.1:8000/js/bootstrap.min.js:6
    jQuery 2
    handle http://127.0.0.1:8000/js/bootstrap.min.js:6
    jQuery 8
    hide http://127.0.0.1:8000/js/bootstrap.min.js:6
    b http://127.0.0.1:8000/js/bootstrap.min.js:6
    jQuery 2
    b http://127.0.0.1:8000/js/bootstrap.min.js:6
    success http://127.0.0.1:8000/alert-rules:1836
    jQuery 6
    grid http://127.0.0.1:8000/alert-rules:1825
    jQuery 2
```

Attached GIF which shows the error

![LibreNMS-AlertfromCollection-polledtime](https://user-images.githubusercontent.com/8458067/116295034-a4e66f00-a766-11eb-9815-fd6f5fbaddc2.gif)

**Comment by ahmedsajid** [comment]
A little googling reveals that others might be facing same issues. https://community.librenms.org/t/create-device-unpolled-alert-from-collection/15575

**Comment by murrant** [comment]
That rule has been removed until someone can contribute a correct rule.  Please check the poller log page until then.
