### ISSUE TITLE
LDAP Authentication - Wildcard not working for nested ou

### ISSUE THREAD

**Issue by ChrisDeh** [librenms/librenms#12835]
We've discovered an issue with LDAP Authentication wildcard, when having users in nested ou suffix.

In our LDAP, a User can exist in two different trees in our directory:
```
# Employees
,ou=accounts,ou=users,dc=example,dc=com
# Freelancers and other external People
,ou=extern,ou=accounts,ou=users,dc=example,dc=com
```

In config.php we've configured following:
```
...
$config['auth_ldap_wildcard_ou'] = true;
$config['auth_ldap_suffix'] = ",ou=accounts,ou=users,dc=example,dc=com";
...
```
With this configuration, a user in `ou=accounts` is able to log in, but not a user in `ou=extern,ou=accounts`

The scenario that works, is the case where a user is a parallel group like:
```
,ou=internal,ou=accounts,ou=users,dc=example,dc=com
,ou=extern,ou=accounts,ou=users,dc=example,dc=com
```
In this case, it is possible to log in for users in both groups. But we sadly cant change our directory structure.

Would be nice, to add support for nested ou's for users as well.

**Comment by murrant** [comment]
Are you using a bind user?  If not, it probably won't work.  If you are using a bind user, make sure the bind user has search permissions.  You can always use the auth_test.php script in debug to get an idea of why it isn't working.
