### ISSUE TITLE
Graph legend broken

### ISSUE THREAD

**Issue by driew2** [librenms/librenms#12843]
Between:
librenms@librenms:~$ git reset --hard 33c71517630e7d2303d89d8d07726ea687d308b5
HEAD is now at 33c715176 Additional data collection for GAIA (#12713)

and

librenms@librenms:~$ git reset --hard 2833d935e0a8734b7f304b8cb652e27a7597b20f
HEAD is now at 2833d935e RRD Graph optimization (#12735)

The rrd port graph legends appear on one line.

![Screenshot from 2021-05-08 02-33-24](https://user-images.githubusercontent.com/6242193/117532742-532fb700-afa6-11eb-96e2-d79b72f44e7b.png)
![Screenshot from 2021-05-08 02-33-48](https://user-images.githubusercontent.com/6242193/117532744-5c208880-afa6-11eb-9702-b33b2e3582e2.png)

**Comment by PipoCanaja** [comment]
Hi @driew2 
Fix is already coming here : 
https://github.com/librenms/librenms/pull/12841
