### ISSUE TITLE
Security risk; when 2fa times out, search still displays information

### ISSUE THREAD

**Issue by sliddjur** [librenms/librenms#12859]
I have enabled 2fa on my account, and when my session times out, so that I have to enter 2fa code again I can still use the search menu to see devices and ports.

To reproduce:

- Enable 2fa on account and login to LibreNMS
- Have browser up, and wait for session timeout 
- Type something in search - everything will be shown 
- Click on a link, and you're thrown back to https://librenms/2fa

**Comment by murrant** [comment]
2fa is not enabled until you verify it.  Legacy entry points do not support redirect, would love to see someone port them to Laravel.
