### ISSUE TITLE
Port Settings : disable Down not working ( with proposed FIX )

### ISSUE THREAD

**Issue by Cupidazul** [librenms/librenms#12863]
In previous versions this was working. But only to "Ignore Alerts".

We should have a button to disable both " Disable polling" and "Ignore alert tag".

Other Buttons, like Toggle, are all working well, only the "Down" and "Alerted" are not responding as usual.

Cheers.

**Comment by Cupidazul** [comment]
TESTS / Proposed FIX :
Replace 'name' with 'id', on both onclicks. 
Note: I've added the "disabled" trigger, usually when Ports are DOWN, I want to 'ignore' and 'disable' polling alltogether. But, I leave this to your review.

---
        $('#down-select').click(function (event) {
            // select ignore buttons for all ports which are down
            event.preventDefault();
            $('[id^="operstatus_"]').each(function () {
                var name = $(this).attr('id');
                var text = $(this).text();
                if (name && text == 'down') {
                    // get the interface number from the object name
                    var port_id = name.split('_')[1];
                    // find its corresponding checkbox and toggle it
                    $('input[name="ignore_' + port_id + '"]').trigger('click');
                    $('input[name="disabled_' + port_id + '"]').trigger('click');
                }
            });
        });

        $('#alerted-toggle').click(function (event) {
            // toggle ignore buttons for all ports which are in class red
            event.preventDefault();
            $('.red').each(function () {
                var name = $(this).attr('name');
                if (name) {
                    // get the interface number from the object name
                    var port_id = name.split('_')[1];
                    // find its corresponding checkbox and toggle it
                    $('input[name="ignore_' + port_id + '"]').trigger('click');
                    $('input[name="disabled_' + port_id + '"]').trigger('click');
                }
            });
        });

---

Cheers.

**Comment by Cupidazul** [comment]
I'm not sure if this should be applied in both these files:
includes/html/pages/device/edit/component.inc.php
includes/html/pages/device/edit/ports.inc.php

**Comment by PipoCanaja** [comment]
@Cupidazul Could you directly create a PR with your proposed fix ?

**Comment by Cupidazul** [comment]
Hi @PipoCanaja , sure, I'll try to do that as soon as I can... I'm a bit busy now...

**Comment by murrant** [comment]
@Cupidazul FYI that button only should set ignore, not disable polling.  (Polling is already disabled for down ports when using selected port polling)

**Comment by Cupidazul** [comment]
Ok. thats fine.

**Comment by murrant** [comment]
I'm saying you can't disable polling for down ports, it is always disabled.
