### ISSUE TITLE
Checkpoint MIB Update

### ISSUE THREAD

**Issue by enesakyol** [librenms/librenms#12887]
Hi,
I get a few errors when I add the checkpoint 7000 series firewall to librenms. When I checked its mib on github, I saw that it is not the same as the latest mib on the checkpoint site. Can you update the checkpoint mib on Github to version R80.40?
https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk90470

Thanx,
Have a good day.

**Comment by PipoCanaja** [comment]
Hello @enesakyol 
Could you please do it directly by opening a Pull request here and updating the necessary mibfiles.
Thanx
