### ISSUE TITLE
Add ability to add username to Telnet / SSH connection

### ISSUE THREAD

**Issue by cs-1** [librenms/librenms#1288]
There's the possibility to open an SSH connection to devices in the devices list. However, the URL is simply ssh://hostname. There're cases when this won't work properly because SSH will use the default username of the client it is run from. It would be great to be able to add a field in the database for each device which could be called "ssh-username" and "telnet-username" which should be defined in the default configuration or per device. This would add a lot of comfort to this functionality.

**Comment by Rosiak** [comment]
I'm pretty certain on what needs to be done, will get this done between xmas and new year - otherwise people are free to pick it up before then :)

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #160](https://github.com/librenms/librenmsv2/issues/160) via [**ZenHub**](https://www.zenhub.com/)
