### ISSUE TITLE
Error in polling Docker

### ISSUE THREAD

**Issue by Calimerorulez** [librenms/librenms#12890]
Hi,

I ran into an issue getting the docker Application polling running:

```
#### Load poller module applications ####

In docker.inc.php line 27:

  Return value of convertToBytes() must be of the type int or null, float returned

```

I've managed to get it working by editing "includes/polling/applications/docker.inc.php", line 11, from

`function convertToBytes(string $from): ?int`

to

`function convertToBytes(string $from): ?float`

The output form validate.php is:
```
====================================
Component | Version
--------- | -------
LibreNMS  | 21.4.0-100-g3cd7043fa
DB Schema | 2021_04_08_151101_add_foreign_keys_to_port_group_port_table (208)
PHP       | 7.3.27-1~deb10u1
Python    | 3.7.3
MySQL     | 10.3.27-MariaDB-0+deb10u1
RRDTool   | 1.7.1
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 2.0.13
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```
The host that runs Docker is a Debian 10 amd64. the host running Librenms is a Raspberrypi.

I'm happy to give more info.

**Comment by murrant** [comment]
Honestly, it should return an integer.  Probably needs a cast somewhere within the function... I don't understand how you end up with a float.
