### ISSUE TITLE
All Devices Visible to Normal Users

### ISSUE THREAD

**Issue by gadago** [librenms/librenms#1289]
There still seem to be a few areas in the GUI where it is possible for a "Normal User" to see (at least the names of) devices they should not be able to. So far I have tracked it down to the following:

 - IPv4 Search, All Devices dropdown
 - IPv6 Search, All Devices dropdown
 - MAC Search, All Devices dropdown
 - ARP Tables, All Devices dropdown
 - Packages (shows packages on devices/servers they have not been given access to)
 - Plugins Menu (gives access to plugins such as Vlan Search and WeatherMap with no way of controlling/hiding these by user group)

Additionally, it seems alerts/thresholds cannot be set on a per user/group basis. For example, if I create a high CPU alert of above or equal to 50%, this will show in the normal user view. This is understandable, but it might be we want to set a different threshold per user. 50% might be high to us, but the user may want 75% for example. It would be good if thresholds could be set per user, or even just disabled on a per user basis.

**Comment by gadago** [comment]
Also, Overview > Alerts, normal users can see alerts for devices the do not have permission on.

**Comment by laf** [comment]
What fun that was :)

Ok, all sorted in #1411 except:

Plugins. Not sure the best approach here, only admins can enable / disable plugins but I think it's upto the plugin itself to handle user permissions so I don't think we should change this.

Alerts per user, one for @f0o but I expect this is a bit challenging and I'd be inclined to say this should be dealt with outside LibreNMS. we provide a variety of transports which support filtering alerts per user already.
