### ISSUE TITLE
Firebrick support: Possible issue with BGP peerings

### ISSUE THREAD

**Issue by cjsoftuk** [librenms/librenms#12917]
Following the merge of the Firebrick support into master, A&A (who run lots of Firebricks) have identified that their LibreNMS is running incredibly slow and is, in some cases, making thousands of BGP peers in LibreNMS

I'm investigating this internally with them to work out what's happening and will provide updates & PR here once I understand what the cause.

**Comment by cjsoftuk** [comment]
This looks to have been caused by https://github.com/librenms/librenms/blob/master/includes/discovery/bgp-peers/firebrick.inc.php#L62 returning 0 when it shouldn't.  I am investigating this directly in their DB to identify exactly what is going on.

**Comment by cjsoftuk** [comment]
OK, so it seems that there's a bug that wasn't present on my test installation, but is present on A&A's live platform.  This appears to be the result of MariaDB handling NULL and 0 differently between the two installations.  I'm obviously looking into this with high priority for them as it made their LibreNMS unusable fairly quickly.  It will only affect people with Firebricks, and the quantity of Firebricks will affect the speed at which this breaks for people.

I hope to have a patch later today and a PR will appear shortly.

**Comment by PipoCanaja** [comment]
Hello @cjsoftuk 
Can you confirm the issue can now be closed? 
Thanx
