### ISSUE TITLE
NS-BSD Plugin (Stormshield) dosn't work since 3.7.19 LTSB

### ISSUE THREAD

**Issue by ilymare** [librenms/librenms#12915]
Hi,

Since the LTSB version of the stromshield OS in 3.7.19 (and also in last version in 3.7.20) the stormshield firewall are seen as a generic device.

The objectID in the MIB as change from ".1.3.6.1.4.1.8072.3.2.8" to ".1.3.6.1.4.1.11256.2.0" in the file "librenms/includes/definitions/ns-bsd.yaml".

After running the script ./discovery.php -h <Stromshield_device>, everything is back to normal.

Regards,

Q.

**Comment by PipoCanaja** [comment]
> Hi,
> 
> Since the LTSB version of the stromshield OS in 3.7.19 (and also in last version in 3.7.20) the stormshield firewall are seen as a generic device.
> 
> The objectID in the MIB as change from ".1.3.6.1.4.1.8072.3.2.8" to ".1.3.6.1.4.1.11256.2.0" in the file "librenms/includes/definitions/ns-bsd.yaml".
> 
> After running the script ./discovery.php -h <Stromshield_device>, everything is back to normal.
> 
> Regards,
> 
> Q.

Hello @ilymare 
As it seems you found out the solution, could you please open a pull request directly with the added objectID (please keep the original as well so you don't break older devices) ? You would also need to provide test data (to allow regression tests to take place). 
Thanx in advance

**Comment by ilymare** [comment]
Hi,

I already had this issue last time i post on the git but every pull request that I make are incomplete because I cannot extract data form my compagny devices. 

I post the info here so if someone needs it or/and can complete a pull request for the community.

Sorry for the inconvenience.

Ilymare.

**Comment by PipoCanaja** [comment]
Please at least do the PR for the YAML file.
