### ISSUE TITLE
Alert rules: locations match doesn't work

### ISSUE THREAD

**Issue by andrzejmaczka** [librenms/librenms#12921]
Adding location in match field doesn't take any effect.

**Comment by andrzejmaczka** [comment]
Found missing part at poller.php output:

SQL[SELECT DISTINCT a.* FROM alert_rules a
        LEFT JOIN alert_device_map d ON a.id=d.rule_id AND (a.invert_map = 0 OR a.invert_map = 1 AND d.device_id = ?)
        LEFT JOIN alert_group_map g ON a.id=g.rule_id AND (a.invert_map = 0 OR a.invert_map = 1 AND g.group_id IN (SELECT DISTINCT device_group_id FROM device_group_device WHERE device_id = ?))
        LEFT JOIN alert_location_map l ON a.id=l.rule_id AND (a.invert_map = 0 OR a.invert_map = 1 AND l.location_id IN (SELECT DISTINCT location_id FROM devices WHERE device_id = ?))
        LEFT JOIN device_group_device dg ON g.group_id=dg.device_group_id AND dg.device_id = ?
        **WHERE a.disabled = 0 AND (
            (d.device_id IS NULL AND g.group_id IS NULL)
            OR (a.invert_map = 0 AND (d.device_id=? OR dg.device_id=?))
            OR (a.invert_map = 1  AND (d.device_id != ? OR d.device_id IS NULL) AND (dg.device_id != ? OR dg.device_id IS NULL))
        )**

should be :

WHERE a.disabled = 0 AND (
            (d.device_id IS NULL AND g.group_id IS NULL AND l.location_id IS NULL)
            OR (a.invert_map = 0 AND (d.device_id = ? OR dg.device_id = ? OR l.location_id = ?))
            OR (a.invert_map = 1 AND (d.device_id != ? OR d.device_id IS NULL ) AND ( dg.device_id != ? OR dg.device_id IS NULL ) AND (l.location_id != ? l.location_id IS NULL))
            )

what do you think?

**Comment by lflinders** [comment]
Also seeing this same behavior.
Set an alerting rule and added locations in order to filter here:
![image](https://user-images.githubusercontent.com/70960998/120815193-8171c980-c547-11eb-947e-8107cb8b609d.png)
The rule started alerting based on the other variables for all locations.

**Comment by murrant** [comment]
If you have a fix, please send a pull request for others :)  Thanks.
