### ISSUE TITLE
Values for jnxRpmHistSumPercentLost are not correctly discovered and collected.

### ISSUE THREAD

**Issue by Brief-Timaeus** [librenms/librenms#12929]
The MIBs define `jnxRpmResultsSummaryTable` with a composite index:

```
    jnxRpmResultsSummaryEntry OBJECT-TYPE
        SYNTAX      JnxRpmResultsSummaryEntry
        MAX-ACCESS  not-accessible
        STATUS      current
        DESCRIPTION
            "Each entry in the table provides a summary of the RPM results
             over a single collection of probes.  For each RPM entry, there
             are several collections maintained: the current test, the
             most recently completed test, a configurable number of the most
             recent probes (aka 'moving average'), and a global collection
             representing all the probes.  Each entry in this table summarizes
             the results for one of these collections."
        INDEX { pingCtlOwnerIndex, pingCtlTestName, jnxRpmResSumCollection }
        ::= { jnxRpmResultsSummaryTable 1 }
```

The first two (`pingCtlOwnerIndex` and `pingCtlTestName`) are strings and the last one (`jnxRpmResSumCollection`) is an enumeration:
```
    SYNTAX INTEGER {
               currentTest       (1),
               lastCompletedTest (2),
               movingAverage     (3),
               allTests          (4)
           }
```

Also, the values collected need to be divided by 10^6.

**Comment by PipoCanaja** [comment]
Hello @Brief-Timaeus 
RPM support is not implemented yet, it is currently a work in progress. You can follow it here : 
#12799 
Bye

**Comment by geg347** [comment]
Hello,
I don't use this value in my polling part.
I am using mainly jnxPingResultsRttUs from jnxPingResultsTable.
And pingResultsSentProbes with pingResultsProbeResponses for percentage loss. Calulated by subtracting pingResultsSentProbes to pingResultsProbeResponses and displayed in percentage in the RRD graphs.
I don't know if it is better to query jnxRpmHistSumPercentLost though.
