### ISSUE TITLE
Filter out ignored/disabled ports in port listings (errored, down)

### ISSUE THREAD

**Issue by xenith** [librenms/librenms#1292]
Either by default, or by adding a selectable UI element, filter out disabled/ignored ports when viewing port lists. For instance, when I am looking at a list of down or error ports, I specifically do not care about ignored/disabled ports. We already have UI elements to display Ignored, Disabled, and Deleted ports.

As a specific example, I have a bunch of devices that report errors on a port (via the standard IF-MIB) that are not actually ethernet/IP errors, thus the value is meaningless. There is no way to disable this on the device and the vendor will not change this behavior, so I mark the port as 'Ignored' because I'm aware about the errors but do not care, yet I still want the port polled so I get the traffic graph.

**Comment by f0o** [comment]
#1228

**Comment by xenith** [comment]
That PR only addresses disabled ports, but not ignored ports. I don't even think ignored ports should be filtered out of the 'all ports' list necessarily, I just need a way to filter them out of the 'errors' and 'down' port lists.
