### ISSUE TITLE
Docker App Issue

### ISSUE THREAD

**Issue by tgregory86** [librenms/librenms#12933]
Hi,

The RRD Graphs for the Docker App are populating the wrong info. For the container cpu usage, the graphs are not populating with % values.:
![image](https://user-images.githubusercontent.com/45361664/120649407-b77d5380-c44a-11eb-892e-567cd1ee01f8.png)

Then for the container memory usage, % there is no values populating:
![image](https://user-images.githubusercontent.com/45361664/120649492-d11e9b00-c44a-11eb-87d8-cec739a9fe1f.png)

% Values are being returned by the poller and the app script:

SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-Oqv' '-m' 'NET-SNMP-EXTEND-MIB' '-M' '/opt/librenms/mibs' '-t' '10' 'udp:HOSTNAME:161' 'nsExtendOutputFull.6.100.111.99.107.101.114']

{"version":"1","data":[{"container":"esphome","pids":4,"memory":{"used":"42.2MiB","limit":"3.703GiB","perc":"1.11%"},"cpu":"0.00%"},{"container":"home_assistant","pids":73,"memory":{"used":"433.7MiB","limit":"3.703GiB","perc":"11.44%"},"cpu":"12.65%"},{"container":"mariadb-ha","pids":19,"memory":{"used":"447.2MiB","limit":"3.703GiB","perc":"11.79%"},"cpu":"2.28%"},{"container":"mosquitto","pids":1,"memory":{"used":"2.301MiB","limit":"3.703GiB","perc":"0.06%"},"cpu":"0.11%"},{"container":"watchtower","pids":10,"memory":{"used":"10.59MiB","limit":"3.703GiB","perc":"0.28%"},"cpu":"0.00%"},{"container":"dozzle","pids":10,"memory":{"used":"8.109MiB","limit":"3.703GiB","perc":"0.21%"},"cpu":"0.02%"},{"container":"diun","pids":11,"memory":{"used":"18.91MiB","limit":"3.703GiB","perc":"0.50%"},"cpu":"0.05%"},{"container":"home_assistant2","pids":18,"memory":{"used":"246.5MiB","limit":"3.703GiB","perc":"6.50%"},"cpu":"0.15%"}],"error":"0","errorString":""}  

  

SQL[UPDATE `applications` set `app_state`=?,`app_status`=?,`timestamp`=NOW() WHERE `app_id` = ? ["OK","",123] 5.79ms] 
  

SQL[SELECT * FROM `application_metrics` WHERE app_id=? [123] 2.8ms] 
  

: 
SQL[UPDATE `application_metrics` set `value`=?,`value_prev`=? WHERE app_id=? && metric=? [0,0.02,123,"esphome_cpu_usage"] 5.53ms] 
  
U....
SQL[UPDATE `application_metrics` set `value`=?,`value_prev`=? WHERE app_id=? && metric=? [12.65,10.64,123,"home_assistant_cpu_usage"] 5.29ms] 
  
U..
SQL[UPDATE `application_metrics` set `value`=?,`value_prev`=? WHERE app_id=? && metric=? [454767411,454662553,123,"home_assistant_mem_used"] 4.61ms] 
  
U
SQL[UPDATE `application_metrics` set `value`=?,`value_prev`=? WHERE app_id=? && metric=? [11.44,11.43,123,"home_assistant_mem_perc"] 4.49ms] 
  
U
SQL[UPDATE `application_metrics` set `value`=?,`value_prev`=? WHERE app_id=? && metric=? [2.28,0.04,123,"mariadb-ha_cpu_usage"] 4.14ms] 
  
U..
SQL[UPDATE `application_metrics` set `value`=?,`value_prev`=? WHERE app_id=? && metric=? [468923187,469237760,123,"mariadb-ha_mem_used"] 5.44ms] 
  
U
SQL[UPDATE `application_metrics` set `value`=?,`value_prev`=? WHERE app_id=? && metric=? [11.79,11.8,123,"mariadb-ha_mem_perc"] 4.18ms] 
  
U
SQL[UPDATE `application_metrics` set `value`=?,`value_prev`=? WHERE app_id=? && metric=? [0.11,0.08,123,"mosquitto_cpu_usage"] 4.15ms] 
  
U.........
SQL[UPDATE `application_metrics` set `value`=?,`value_prev`=? WHERE app_id=? && metric=? [0.02,0,123,"dozzle_cpu_usage"] 5.36ms] 
  
U.........
SQL[UPDATE `application_metrics` set `value`=?,`value_prev`=? WHERE app_id=? && metric=? [0.15,4.51,123,"home_assistant2_cpu_usage"] 4.29ms] 
  
U..
SQL[UPDATE `application_metrics` set `value`=?,`value_prev`=? WHERE app_id=? && metric=? [258473984,258578841,123,"home_assistant2_mem_used"] 4.21ms] 
  
U.

{
  "version": "1",
  "data": [
    {
      "container": "esphome",
      "pids": 4,
      "memory": {
        "used": "42.2MiB",
        "limit": "3.703GiB",
        "perc": "1.11%"
      },
      "cpu": "0.00%"
    },
    {
      "container": "home_assistant",
      "pids": 73,
      "memory": {
        "used": "433.7MiB",
        "limit": "3.703GiB",
        "perc": "11.44%"
      },
      "cpu": "12.65%"
    },
    {
      "container": "mariadb-ha",
      "pids": 19,
      "memory": {
        "used": "447.2MiB",
        "limit": "3.703GiB",
        "perc": "11.79%"
      },
      "cpu": "2.28%"
    },
    {
      "container": "mosquitto",
      "pids": 1,
      "memory": {
        "used": "2.301MiB",
        "limit": "3.703GiB",
        "perc": "0.06%"
      },
      "cpu": "0.11%"
    },
    {
      "container": "watchtower",
      "pids": 10,
      "memory": {
        "used": "10.59MiB",
        "limit": "3.703GiB",
        "perc": "0.28%"
      },
      "cpu": "0.00%"
    },
    {
      "container": "dozzle",
      "pids": 10,
      "memory": {
        "used": "8.109MiB",
        "limit": "3.703GiB",
        "perc": "0.21%"
      },
      "cpu": "0.02%"
    },
    {
      "container": "diun",
      "pids": 11,
      "memory": {
        "used": "18.91MiB",
        "limit": "3.703GiB",
        "perc": "0.50%"
      },
      "cpu": "0.05%"
    },
    {
      "container": "home_assistant2",
      "pids": 18,
      "memory": {
        "used": "246.5MiB",
        "limit": "3.703GiB",
        "perc": "6.50%"
      },
      "cpu": "0.15%"
    }
  ],
  "error": "0",
  "errorString": ""
}

**Comment by rhinoau** [comment]
Confirmed my side, but haven't deep-dived on RRDs in the past ~15 years to know the quick fix:
![image](https://user-images.githubusercontent.com/78184917/123388276-2e7db600-d5cb-11eb-87de-5dd7020d3f4f.png)

**Comment by murrant** [comment]
Current code:
```php
    $fields = [
        'cpu_usage' => (float) $data['cpu'],
        'pids' => $data['pids'],
        'mem_limit' => convertToBytes($data['memory']['limit']),
        'mem_used' => convertToBytes($data['memory']['used']),
        'mem_perc' => (float) $data['memory']['perc'],
    ];
```

Probably the cast to float isn't working... maybe `(float) str_replace('%', '', $data['cpu'])` or something like that would fix it.

**Comment by rhinoau** [comment]
> Probably the cast to float isn't working... maybe `(float) str_replace('%', '', $data['cpu'])` or something like that would fix it.

Gave that a try but no change to either CPU or Memory - looks like the original code works based on some testing:

```
php > $val = (float) '4.56';
php > echo $val;
4.56

php > $val = (float) '4.56%';
php > echo $val;
4.56

php > $val = (float) '4.56%%';
php > echo $val;
4.56

php > $val = (float) str_replace('%', '', '4.56%');
php > echo $val;
4.56
```

**Comment by BioSehnsucht** [comment]
Just got done with adding docker stats to our docker VMs and noticed this issue, though at first I thought it was my replacement docker stats script (for containers whose name starts with our company name, it checks to see if it has the composer project label set, and if so, attempts to group them into one 'bucket' of stat reporting, so we don't have 6x however many projects are on a given VM reported for stats, but instead just a single collected stat for all the containers that make up each project).

Turns out it wasn't my replacement script after all, it's this same annoyance.

**Comment by prahal** [comment]
You might want to try my PR https://github.com/librenms/librenms/pull/14080 . This will not fix old data.
If you want to start clean, docker app rrd files are in the rrd_dir (see config.php) subdir host name, files app-docker-*.rrd .
I deleted them then triggered polling as librenms user with `./poller.php -h <host name> -v -d` .
