### ISSUE TITLE
Overrides return empty string

### ISSUE THREAD

**Issue by Zyzto** [librenms/librenms#12936]
I am using Librenms + Oxidized and trying to change os type from librenms to oxidzied by : 
`$config['oxidized']['maps']['os']['os'][] = array('match' => 'ciscosb', 'group' => 'ciscosmb');`
inside config.custom.php in librenms and I have couple of rules that are working but os to os doesn't work
and I would get this in oxidized logs
```
IPADDR  
D, [2021-06-08T09:15:37.222535 #136] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value ''
D, [2021-06-08T09:15:37.222722 #136] DEBUG -- : node.rb: setting node key 'model' to value 'junos' from global
D, [2021-06-08T09:15:37.222942 #136] DEBUG -- : node.rb: returning node key 'model' with value ''
D, [2021-06-08T09:15:37.223096 #136] DEBUG -- : lib/oxidized/node.rb: Loading model ""
D, [2021-06-08T09:15:37.219743 #136] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 25
E, [2021-06-08T09:15:37.223962 #136] ERROR -- : node {:name=>"10.0.0.5", :model=>"", :group=>nil, :ip=>""} raised Oxidized::ModelNotFound with message ' not found for node 10.0.0.5'
D, [2021-06-08T09:15:37.224044 #136] DEBUG -- : resolving DNS for 10.0.0.5...
D, [2021-06-08T09:15:37.224149 #136] DEBUG -- : IPADDR 
```

**Comment by murrant** [comment]
The rule you mention is already in the defaults...

What does `lnms config:get oxiddized.maps` show?

**Comment by Zyzto** [comment]
@murrant thanks for your comment.

I fixed the issue after taking long break and looking back I didn't change the "GROUP" in the second half of librenms config:
`$config['oxidized']['maps']['os']['os'][] = array('match' => 'ciscosb', 'group' => 'ciscosmb');`
this becomes this 
`$config['oxidized']['maps']['os']['os'][] = array('match' => 'ciscosb', 'os' => 'ciscosmb');`
