### ISSUE TITLE
Please add suppot for VyOS

### ISSUE THREAD

**Issue by seitzbg** [librenms/librenms#1294]
Like UBNT EdgeOS, this was forked from vyatta community.

Currently it shows up as  'generic device'.

I can assist in providing dumps etc if needed.

**Comment by paulgear** [comment]
Hi @seitzbg - EdgeOS & Vyatta support was added some time ago.  (https://github.com/librenms/librenms/pull/351)  Is your LibreNMS install up-to-date?  If not, please update.

If so, it may be that you have a newer hardware model or software version that has changed its identification - in that case, please send us the output of an snmpwalk and we'll update the detection code.

**Comment by Rosiak** [comment]
Can confirm EdgeOS is currently working.

**Comment by laf** [comment]
Merged in a fix for newer versions in #1299
