### ISSUE TITLE
Add RADIUS authentication method

### ISSUE THREAD

**Issue by job** [librenms/librenms#1295]
Currently LibreNMS supports MySQL & LDAP based authentication. If RADIUS support were to be added that would make my life easier in some scenario's.

**Comment by laf** [comment]
Don't mind having a crack at this but some questions.

Using the http-auth module we still expect users to be in the MySQL db, if not then you can define a fallback user so at least it's privs are used going forward. We can do the same for RADIUS auth but it strikes me as odd having to maintain a user list in MySQL anyway - so anyway to:

1. Return a userlevel in the LDAP response so we know what user level to assign to people.
2. Anyway to confirm a user account exists via LDAP?
3. Anyway to list all users?

1. is possible via the Reply-Message attribute response in Radius which we could parse say userlevel=X but what about the others? If these aren't possible then we'll fall back to using the MySQL to maintain users still.

**Comment by job** [comment]
1) afaik no, but i'd just assign a predefined access level to users being authenticated against radius
2) dunno, just try and authenticate it? If that fails error: "either username or password wrong"
3) no
4) not sure i understand the question

**Comment by masonke** [comment]
Resurrecting this thread, Radius would make things a lot simpler for AD authentication as the Active Directory Radius tool is pretty good.

With my other tools, we assign a mapping on the Radius tools for the users AD group to the Access Levels on the tool. For example, the members of NetEng are admins on the Riverbed Cascade system, SysEng and Security are Operator, etc

If a user login fails, the radius server returns an error message.

This would act very similar to LDAP where you would not know the name of all the users

If Radius is not available, fallback would be to a limited number of people with local accounts. Depending on the deployment, a generic readonly account could be created to view the dashboards.

Does that help?

**Comment by laf** [comment]
Ok so the auth side of this is easy, I've got that sorted. The issue we face is that we need a user id and user level, neither of which we can get from radius. So we'd have to add users to mysql as well (no passwords) so that lookups for user id and level come from mysql.

You'd either have to create users still in LibreNMS or we can auto add users when they successfully login, however removing old users would be a manual job.

Thoughts?

**Comment by job** [comment]
Automatically add users when they login. Make it a configurable option in config.php what by default their user level is. Job                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Neil LathwoodSent: zondag 13 december 2015 03:02To: librenms/librenmsReply To: librenms/librenmsCc: Job SnijdersSubject: Re: [librenms] Add RADIUS authentication method (#1295)Ok so the auth side of this is easy, I've got that sorted. The issue we face is that we need a user id and user level, neither of which we can get from radius. So we'd have to add users to mysql as well (no passwords) so that lookups for user id and level come from mysql.

You'd either have to create users still in LibreNMS or we can auto add users when they successfully login, however removing old users would be a manual job.

Thoughts?

—Reply to this email directly or view it on GitHub.

**Comment by f0o** [comment]
Removal of users can be cronjob'd:
I.e. if user has default access and hasnt logged in within N time => remove.
Thoughts?

**Comment by job** [comment]
On Sun, Dec 13, 2015 at 02:02:37AM -0800, Daniel Preussker wrote:
> Removal of users can be cronjob'd:
> I.e. if user has default access and hasnt logged in within N time => remove.
> Thoughts?

Wasn't there some kind of radius command to check if a user /exists/ or
not? You could check every 24 hours if the user exists, and if not
remove it.

Kind regards,

Job

**Comment by job** [comment]
On Sun, Dec 13, 2015 at 11:24:24AM +0100, Job Snijders wrote:
> On Sun, Dec 13, 2015 at 02:02:37AM -0800, Daniel Preussker wrote:
> > Removal of users can be cronjob'd:
> > I.e. if user has default access and hasnt logged in within N time => remove.
> > Thoughts?
> 
> Wasn't there some kind of radius command to check if a user /exists/ or
> not? You could check every 24 hours if the user exists, and if not
> remove it.

Seems I was confused, there is no such command.

I'd make the defaults that the access level is 'read only' and the
internal user is deleted after 12 hours or so.

We can document that admins & read/write access levels should be 'real'
users created through other means (commandline, ldap).

Kind regards,

Job

**Comment by masonke** [comment]
Seems like a reasonable methodology to start.
~KEM

**Comment by laf** [comment]
@job 

If you want to test, I've just submitted a PR #2615. If your install is upto date then you could add my git repo as another branch and switch over to test it.

**Comment by job** [comment]
@laf the authentication itself works. How can I set an access level?

**Comment by laf** [comment]
@job 

So you can either do that by manually adding the user with ./adduser.php in the cli. Or if you have an existing admin user then login with those and edit the user within the webui and if you don't then just update the users table in mysql:

`UPDATE users SET level=10 WHERE username='job';`
