### ISSUE TITLE
Eventlog widgets sometimes cease to refresh their contents

### ISSUE THREAD

**Issue by ottorei** [librenms/librenms#12956]
When using a dashboard with two eventlog-type widgets with different options, the other one usually fails to refresh it's contents after a few refreshes. I have seen this with types "alerts" and "reboots" configured at the same time. The other one continues to update. When this issue occurs, the misbehaving widget does not even show the typical "Loading..." text - it is just completely empty. Sometimes manually refreshing the page seems to work for a while. Other widgets do not seem to have this issue.

**Comment by murrant** [comment]
Any error in the web-dev console?
