### ISSUE TITLE
Add Serialnumber for some HP/ARUBA Procurve switch devices

### ISSUE THREAD

**Issue by ziodona85** [librenms/librenms#12961]
Serialnumber for some HP/ARUBA Procurve devices is not inserted in device table.
I have noticed that miss the MIB HP-SN-AGENT-MIB for adding this information.
I have inserted file HP-SN-AGENT-MIB in dir mibs/hp/ and with Capture Debug Information --> Discovery works but after some hours it disappears.

System Namekye0016art_1fontana3
Hardware2930F-24G-PoE+-4SFP
Operating SystemHP ProCurve WC.16.07.0003
SerialCN95HL2XXX
Object ID.1.3.6.1.4.1.11.2.3.7.11.181.24
Device Added189 days 14 hours 7 minutes 43 seconds ago
Last Discovered19 minutes 3 seconds ago
Uptime28 minutes 52 seconds

**Comment by ziodona85** [comment]
UPDATE i have copied file HP-SN-AGENT-MIB also on all poller and now it works correctly. i suggest to insert this MIB in the next release.

**Comment by murrant** [comment]
Can you send a pull request adding the MIB?  You can do that directly from the Github web page.

**Comment by ziodona85** [comment]
Hi,

i have opened a new pull request (Adding Serialnumber for some HP/ARUBA Procurve switch devices #12981
) but it's the first time and surely i was wrong the branch.
Can you check it?
Thanks.

**Comment by PipoCanaja** [comment]
@ziodona85 If you only need to add a mib file, it can be done directly from github GUI.

**Comment by laf** [comment]
Mib was added in #13009 so closing this.
