### ISSUE TITLE
Option "physics": false in edges breaking Network Map

### ISSUE THREAD

**Issue by fabriciotm** [librenms/librenms#12972]
When add the _physics:false_ for Edges in network_map_vis_options, the map stop working.
Used the example configuration from documentation:

$config['network_map_vis_options'] = '{
  "nodes": {
    "color": {
      "background": "rgba(20,252,18,1)"
    },
    "font": {
      "face": "tahoma"
    },
    "physics": false
  },
  "edges": {
    "smooth": {
      "forceDirection": "none"
    }
  },
  "interaction": {
    "hover": true,
    "multiselect": true,
    "navigationButtons": true
  },
  "manipulation": {
    "enabled": true
  },
  "physics": {
    "barnesHut": {
      "avoidOverlap": 0.11
    },
    "minVelocity": 0.75
  }
}';

 Removing the option, map works fine.
I got the following error in browser's debug console:

![image](https://user-images.githubusercontent.com/13259471/122797056-70d68880-d295-11eb-8fbe-35afc67323f6.png)

 ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.6.0-8-g748186c05
DB Schema | 2021_25_01_0127_create_isis_adjacencies_table (211)
PHP       | 7.3.27-1~deb10u1
Python    | 3.7.3
MySQL     | 10.3.27-MariaDB-0+deb10u1
RRDTool   | 1.7.1
SNMP      | NET-SNMP 5.7.3
====================================

**Comment by murrant** [comment]
According to the vis.js docs, physics should be an object, not a boolean.

https://visjs.github.io/vis-network/docs/network/physics.html

**Comment by fabriciotm** [comment]
The problem is in Edge module, not in network.


https://visjs.github.io/vis-network/docs/network/edges.html
