### ISSUE TITLE
ISIS not picking up older Cisco devices

### ISSUE THREAD

**Issue by wtc-jeff** [librenms/librenms#12986]
ISIS discovery and polling are not working on older Cisco OS's. We have a bunch of Cisco 7301's and a few 6500's running ios 15.2.x that do not support the ISIS-MIB, it uses the CISCO-IETF-ISIS-MIB.  Is there any way these devices could also be polled for ISIS adjacencies?

**Comment by aarchijs** [comment]
It is said that only Juniper MX-80, MX-240 and Cisco ASR9K-series are tested. These specific devices does not support proprietary CISCO-IETF-ISIS-MIB. Only IOS and IOS-XE does. I looked in to existing polling code and it is specifically made to support only ISIS-MIB as it is not compatible with Cisco proprietary MIB. Only way to support older devices is to do addition to code to support CISCO-IETF-ISIS-MIB and it des not look like adding two lines of code would do the trick.

**Comment by wtc-jeff** [comment]
Thanks for the reply.

**Comment by murrant** [comment]
Would be happy to see someone add support for the proprietary mib.
