### ISSUE TITLE
SMTP Error: Could not connect to SMTP host

### ISSUE THREAD

**Issue by carlofab** [librenms/librenms#12991]
Hi,
     with a fresh installation of Librenms (Ubuntu20) we had a problem on SMTP setting: testing the mail transport failed with "SMTP Error: Could not connect to SMTP host". We uses the Company SMTP Exchange Server.
Looking around we discovered this issue related to PHPMailer: https://github.com/PHPMailer/PHPMailer/issues/1318 

We added the following row in SMTP section of /opt/librenms/includes/functions.php  (row 821)
`$mail->SMTPOptions = array('ssl' => array('verify_peer' => false,'verify_peer_name' => false,'allow_self_signed' => true));`
and the mail transport works fine.
Do you think could be useful add this row on the code?

Regards,
Carlo

_librenms@librenms:~$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.6.0-6-g7ef302a8b
DB Schema | 2021_25_01_0127_create_isis_adjacencies_table (211)
PHP       | 7.4.3
Python    | 3.8.5
MySQL     | 10.3.29-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8_

**Comment by PipoCanaja** [comment]
Hello @carlofab 
Disabling all security cannot be done on a default basis. 
Acceptable solutions : 
- Install the self signed certificate to your LibreNMS server to allow the verification to succeed.
- Patch LibreNMS to allow the configuration of these option graphically, and document it in LibreNMS doc.

The best (and easiest) solution is of course the 1st one.
