### ISSUE TITLE
Problem Enterasys Controller Wireless with old release

### ISSUE THREAD

**Issue by ziodona85** [librenms/librenms#13015]
Hi,

i have noticed a problem with Enterasys Controller 

System Nameewc2.milano.it
Operating SystemEnterasys Wireless Convergence
Object ID.1.3.6.1.4.1.4329.15.1.1.10
ContactController Enterasys
Device Added197 days 1 hour 46 minutes 51 seconds ago
Last Discovered2 hours 17 minutes 30 seconds ago

It has an old software release --> Enterasys Networks, Inc. Wireless Controller - C5110-2, System Version 08.11.03.0024, 
so it was mapped as generic switch and it haven't wireless menu.
I have applied a workaround:
I have copied EWC file into Enterasys file, modifying /opt/librenms/LibreNMS/OS/Enterasys.php  and /opt/librenms/includes/definitions/enterasys.yaml .
The workaround works but i don't know if it could create problem with other Enterasys device.

Steps:

cp /opt/librenms/LibreNMS/OS/Ewc.php /opt/librenms/LibreNMS/OS/Enterasys.php 
cp /opt/librenms/mibs/ewc/HIPATH-WIRELESS-* /opt/librenms/mibs/enterasys/
cp /opt/librenms/includes/definitions/ewc.yaml /opt/librenms/includes/definitions/enterasys.yaml
rm /opt/librenms/LibreNMS/OS/Enterasys.php 
vi /opt/librenms/LibreNMS/OS/Enterasys.php 

<?php
/**
 * Enterasys.php
 *
 * Enterasys Wireless Controller
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @link       https://www.librenms.org
 * @copyright  2017 James Andrewartha
 * @author     James Andrewartha <trs80@ucc.asn.au>
 */

namespace LibreNMS\OS;

use LibreNMS\Device\WirelessSensor;
use LibreNMS\Interfaces\Discovery\Sensors\WirelessApCountDiscovery;
use LibreNMS\Interfaces\Discovery\Sensors\WirelessClientsDiscovery;
use LibreNMS\Interfaces\Discovery\Sensors\WirelessErrorsDiscovery;
use LibreNMS\Interfaces\Discovery\Sensors\WirelessFrequencyDiscovery;
use LibreNMS\Interfaces\Discovery\Sensors\WirelessNoiseFloorDiscovery;
use LibreNMS\Interfaces\Discovery\Sensors\WirelessRssiDiscovery;
use LibreNMS\Interfaces\Discovery\Sensors\WirelessSnrDiscovery;
use LibreNMS\Interfaces\Discovery\Sensors\WirelessUtilizationDiscovery;
use LibreNMS\OS;

class Enterasys extends OS implements

rm /opt/librenms/includes/definitions/enterasys.yaml 
vi /opt/librenms/includes/definitions/enterasys.yaml 

os: enterasys
text: 'Enterasys Wireless Convergence'
type: wireless
icon: enterasys
over:
    - { graph: device_bits, text: 'Device Traffic' }
    - { graph: device_processor, text: 'CPU Usage' }
    - { graph: device_mempool, text: 'Memory Usage' }
    - { graph: device_wireless_ap-count, text: 'Connected APs' }
    - { graph: device_wireless_clients, text: 'Connected Clients' }
discovery:
    -
        sysObjectID:
            - .1.3.6.1.4.1.4329.15.1.1.
mib_dir: enterasys

Could you help me? Is it possible to do permanently this modify?
Thankds.
Regards.

**Comment by ziodona85** [comment]
![librenms2](https://user-images.githubusercontent.com/74834035/125058028-22edbd00-e0aa-11eb-86d7-11872947abce.png)

**Comment by Jellyfrog** [comment]
Please send a pull request or use the forum for device requests
