### ISSUE TITLE
Not checked php-ldap module existence

### ISSUE THREAD

**Issue by Sea-n** [librenms/librenms#13028]
The `php-ldap` module is not required during installation.

It's better to pop up a warning when the user enabled LDAP login without `php-ldap` installed.

**Comment by kkrumm1** [comment]
Its a part of the install docs https://docs.librenms.org/Extensions/Authentication/#ldap-authentication

Config option: ldap

Install php_ldap or php7.0-ldap, making sure to install the same version as PHP.
