### ISSUE TITLE
Error when modifying an existing group

### ISSUE THREAD

**Issue by Negatifff** [librenms/librenms#13024]
I created a new dynamic group. it was successfully created and devices were added to it. 
![изображение](https://user-images.githubusercontent.com/24737933/125157723-30bc4480-e175-11eb-9df6-ff0a2688712a.png)

but when I want to make any changes to it (edit the title, description, add rules, or just save without changing anything) I get an error. 

![изображение](https://user-images.githubusercontent.com/24737933/125157790-93addb80-e175-11eb-8413-4c8a17ab5a52.png)

this behavior is related to the number of devices added to the group. for groups with fewer devices, this does not happen. 

upd. I manually deleted the devices associated with this group from the DB (table device_group_device)  and the group could be edited again. but once.  

> -bash-4.2$ ./validate.php
> ====================================
> Component | Version
> --------- | -------
> LibreNMS  | 21.6.0-34-gccb267b
> DB Schema | 2021_06_07_123600_create_sessions_table (214)
> PHP       | 7.3.26
> Python    | 3.6.8
> MySQL     | 10.5.9-MariaDB
> RRDTool   | 1.7.1
> SNMP      | NET-SNMP 5.7.2
> ====================================
> 
> [OK]    Composer Version: 2.1.3
> [OK]    Dependencies up-to-date.
> [OK]    Database connection successful
> [OK]    Database schema correct
> [INFO]  Detected Python Wrapper
> [OK]    Connection to memcached is ok
> [WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.

**Comment by ottorei** [comment]
I had this same issue a while ago with very large groups. If I remember correctly, the dynamic group makes a POST-request with all the devices in it if you make any changes to the group in the UI. My workaround was to increase the PHP's option "max_input_vars" to a bigger value like 10000 in php.ini (/etc/php/7.4/fpm/php.ini, Ubuntu 20.04 LTS).

**Comment by ottorei** [comment]
Added a PR for a FAQ about this. #13110

**Comment by Negatifff** [comment]
thanks. now works as it should.
