### ISSUE TITLE
LibreNMS virtual image cronjobs missing

### ISSUE THREAD

**Issue by optimdevel** [librenms/librenms#13040]
Looking at manual and following manual instructions, I noticed that libreNMS should have:
```
cat /etc/cron.d/librenms
# Using this cron file requires an additional user on your system, please see install docs.

33   */6  * * *   librenms    /opt/librenms/cronic /opt/librenms/discovery-wrapper.py 1
*/5  *    * * *   librenms    /opt/librenms/discovery.php -h new >> /dev/null 2>&1
*/5  *    * * *   librenms    /opt/librenms/cronic /opt/librenms/poller-wrapper.py 16
*    *    * * *   librenms    /opt/librenms/alerts.php >> /dev/null 2>&1
*/5  *    * * *   librenms    /opt/librenms/poll-billing.php >> /dev/null 2>&1
01   *    * * *   librenms    /opt/librenms/billing-calculate.php >> /dev/null 2>&1
*/5  *    * * *   librenms    /opt/librenms/check-services.php >> /dev/null 2>&1

# Daily maintenance script. DO NOT DISABLE!
# If you want to modify updates:
#  Switch to monthly stable release: https://docs.librenms.org/General/Releases/
#  Disable updates: https://docs.librenms.org/General/Updating/
15   0    * * *   librenms    /opt/librenms/daily.sh >> /dev/null 2>&1
```

but it actually has:
```
librenms@librenms:~$ cat /etc/cron.d/librenms 
*/5 * * * * librenms /opt/librenms/html/plugins/Weathermap/map-poller.php >> /dev/null 2>&1
```

So I guess either install instructions are wrong, or virtual image is missing all cron jobs.

**Comment by kkrumm1** [comment]
I think the images are using this https://docs.librenms.org/Extensions/Dispatcher-Service/

**Comment by optimdevel** [comment]
Maybe add more description to the image docs or general docs, so this is clear for others that might use the image an get confused reading official install docs.

**Comment by optimdevel** [comment]
Also why would prepared images contain "release candidate" code?
Are they not for production use?

**Comment by optimdevel** [comment]
Why would default virtual image have cronjob for map pooler, if according to docs, everything is run from librenms-service.py?

**Comment by murrant** [comment]
Because Weathermap is not part of LibreNMS.  It has it's own cron job.

Feel free to update docs or contribute VM improvements.
