### ISSUE TITLE
ADD ping/snmp alerting

### ISSUE THREAD

**Issue by Alastair-VOIPUNLIMITED** [librenms/librenms#1305]
Hi guys,

Following our conversation on IRC....

would it be possible to have the ability to create alerts based on ICMP discovery and SNMP discovery separately? :simple_smile: on the platform that shall not be named (observium) we used "device_status eq 0 device_status_type match ping" and "device_status_type match snmp", any ideas on how we could do the same in libre?

I believe you suggested updating the poller to include device_status_type

Thank you

Alastair

**Comment by laf** [comment]
All merged in.

status_reason will now contain either icmp or snmp when a device is down for you to alert on.
