### ISSUE TITLE
ADD smokeping config file generation

### ISSUE THREAD

**Issue by mkvo** [librenms/librenms#1306]
Hi,

Please could you add the ability to automatically generate smokeping config files every X hours from the hosts configured in librenms? The configuration files are pretty simple:

http://oss.oetiker.ch/smokeping/doc/smokeping_examples.en.html

Thanks!

**Comment by paulgear** [comment]
This would be a cool feature. :+1:   If someone doesn't get to it before me, I'll take a look at it once I'm finished with this Ruckus stuff.

**Comment by Rosiak** [comment]
I'll take a look at it :-)

**Comment by laf** [comment]
Hopefully all good with this now in #1407
