### ISSUE TITLE
APC InRow DX show power in W instead of kW

### ISSUE THREAD

**Issue by Codomme** [librenms/librenms#13065]
Hello,
It's look like the problem is located on the Poller side that it's assuming that all APC devices reports W and not maybe Kw.

You can see in the output that the unit should be kW : [https://p.libren.ms/view/3201b995](https://p.libren.ms/view/3201b995)

.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.2.1.7 = STRING: "Total Air Side Cooling Demand"
.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.2.1.8 = STRING: "Total Sensible Cooling Power"
.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.2.1.24 = STRING: "Cool Demand"
.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.2.1.25 = STRING: "Cool Output"
.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.4.1.7 = STRING: "kW"
.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.4.1.8 = STRING: "kW"
.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.4.1.24 = STRING: "kW"
.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.4.1.25 = STRING: "kW"
.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.5.1.8 = INTEGER: 10
.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.5.1.7 = INTEGER: 10
.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.5.1.8 = INTEGER: 10
.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.5.1.24 = INTEGER: 10
.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.5.1.25 = INTEGER: 10

Poller module : [https://p.libren.ms/view/f9a27252#L154](https://p.libren.ms/view/f9a27252#L154)

Checking (snmp) power Total Air Side Cooling Demand...
Checking (snmp) power Total Sensible Cooling Power...
Checking (snmp) power Cool Demand...
Checking (snmp) power Cool Output...
10.9 W
SQL[[1;33mUPDATE `sensors` set `sensor_current`=?,`sensor_prev`=?,`lastupdate`=NOW() WHERE `sensor_class` = ? AND `sensor_id` = ? [0;33m[10.9,11.1,"power",104876][0m 0.71ms]
 
11.7 W
SQL[[1;33mUPDATE `sensors` set `sensor_current`=?,`sensor_prev`=?,`lastupdate`=NOW() WHERE `sensor_class` = ? AND `sensor_id` = ? [0;33m[11.7,10.1,"power",104877][0m 0.38ms]
 
0 W
0 W

Thank you !

**Comment by PipoCanaja** [comment]
Hi @Codomme 
The code handling this case is here :
`includes/discovery/sensors/power/apc.inc.php`
Bye

**Comment by Codomme** [comment]
Hi @PipoCanaja, thank you for your answer.
I agree but they provide the good kW also it's why it should be easier to collect ca during discovery so there is no 'manual' setting.
I'll have a look.

**Comment by Codomme** [comment]
I digged a bit and I see two issues.

First, the following function never look for units (like the discover_storage):
'function discover_sensor(&$valid, $class, $device, $oid, $index, $type, $descr, $divisor = 1, $multiplier = 1, $low_limit = null, $low_warn_limit = null, $warn_limit = null, $high_limit = null, $current = null, $poller_type = 'snmp', $entPhysicalIndex = null, $entPhysicalIndex_measured = null, $user_func = null, $group = null)'

But there is other "power" information like Amp for the fans.

      'coolingUnitStatusAnalogTableIndex' => '67',
      'coolingUnitStatusAnalogDescription' => 'Fan Power Supply 1',
      'coolingUnitStatusAnalogValue' => '397',
      'coolingUnitStatusAnalogUnits' => 'A',
      'coolingUnitStatusAnalogScale' => '1000',

Second, if we assume that it will be always kW, then we can something else like Watts or Amps like my previous example.

**Comment by PipoCanaja** [comment]
Hi,

"discover_sensor" expects among other things, a multiplier and a divisor. Default being 1 and 1 (means no change). And it has absolutely no way to guess them.
All the job to defined those must be done before, and it is the mission of the php file I sent you, to compute the right values for both divisor and multiplier. 
So, in your case, (multiplier,divisor) could be set as (1000,10). 1000 for "kilo" in kW, and 10 for the scale value (which is basically a divisor). That can be simplified as 100 of course. 
If other OIDs are provided this way, then discovery must be adapted, you are right.

**Comment by PipoCanaja** [comment]
Hi @Codomme 
Seems that this issue is getting old and forgotten. Let us know if you have new elements here, and feel free to reopen.
Bye
