### ISSUE TITLE
Navbar Missing

### ISSUE THREAD

**Issue by nbeard49** [librenms/librenms#13079]
I'm running into an issue where the navbar at the top of the page (Overview, Devices, Services, etc) has gone missing with no manual intervention. I'm running daily updates and the validate script doesn't report any issues:

```
librenms@monitoring:~$ ./daily.sh 
Updating to latest codebase                        OK
Updating Composer packages                         OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK
Caching Mac OUI data                               OK
```
```
librenms@monitoring:~$ ./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 21.7.0-29-gb9e6a5975
DB Schema | 2021_07_06_1845_alter_bill_history_max_min (212)
PHP       | 7.4.3
Python    | 3.8.10
MySQL     | 10.3.30-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.1.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

This is on an Ubuntu Server 20.04.2 LTS fully patched system. A screenshot of what I'm seeing is below:

![stellar-librenms](https://user-images.githubusercontent.com/17462407/127661194-63fb76f4-033c-4c78-8dc4-27f5f9df87e3.png)

Inspecting the generated HTML code also shows no code present for that navigation bar (see below):

![non-working-html](https://user-images.githubusercontent.com/17462407/127661402-da9bcdac-9d33-44a5-b39e-ec161ec0113b.png)

This is compared against another system that is working correctly (see below):

![working-html](https://user-images.githubusercontent.com/17462407/127661545-eefd7a3c-bc0e-44ba-b8d3-453a09a8fbe1.png)

The OS is fully patched and all other LibreNMS frontend/backend items look to be OK with the exception of that navbar.

**Comment by murrant** [comment]
You set bare=yes in the url.

**Comment by nbeard49** [comment]
Nope - using the base URL without the option to hide the menubar.

**Comment by murrant** [comment]
That is the only way it can be hidden:
```blade
@if(Request::get('bare') == 'yes')
    <style>body { padding-top: 0 !important; padding-bottom: 0 !important; }</style>
@elseif($show_menu)
    @include('layouts.menu')
@endif
```

You can check your librenms.log file for errors, but I don't know any way for it to hide the menu.

**Comment by nbeard49** [comment]
I've included a screenshot showing the full URL:

![stellar-librenms](https://user-images.githubusercontent.com/17462407/128875600-b3d83ffa-fe11-4d83-b5cb-b2fad4a0cb9e.png)

You can see that this is a base URL and also that the navbar is missing. I already checked the error_log file and nothing is output. The librenms.log file is also fine and nothing is showing the the Apache logs for errors.

**Comment by mikej96** [comment]
Disabling 2FA resolves this. The following code block in LayoutComposer.php was setting $show_menu to false. 

```
        $show_menu = auth()->check();
        if ($show_menu && Config::get('twofactor') && ! session('twofactor')) {
            $show_menu = empty(UserPref::getPref(auth()->user(), 'twofactor'));
        }
```

**Comment by murrant** [comment]
Hmm, it should only hide it until two factor is completed.  (the ! session('twofactor') part)
