### ISSUE TITLE
ISIS discovery and polling not returning full list of adjacencies

### ISSUE THREAD

**Issue by wtc-jeff** [librenms/librenms#13077]
Hello,

I have been trying to determine why LibreNMS was not showing the full set of adjacencies when polling some devices.  Doing some digging I discovered the OS that is corrupting the output of the snmp results and creating garbled responses:

/usr/bin/snmpbulkwalk -v2c -c community -OQUsetX -m ISIS-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:myrouter:161 ISIS-MIB::isisISAdj

```
isisISAdjIPAddrAddress[554][1][1] = "
*       ["
isisISAdjIPAddrAddress[561][1][1] = "
*       ?"
isisISAdjIPAddrAddress[563][1][1] = "
*       D"
isisISAdjIPAddrAddress[565][1][1] = "
*       y"
isisISAdjIPAddrAddress[614][1][1] = "
*       7"
isisISAdjIPAddrAddress[618][1][1] = "0A 2A 09 C8 "
```

Adding an 'x' to the SNMP options to force display of hex values

/usr/bin/snmpbulkwalk -v2c -c community -OQUsetXx -m ISIS-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:myrouter:161 ISIS-MIB::isisISAdj

```
isisISAdjIPAddrAddress[554][1][1] = "0A 2A 09 5B "
isisISAdjIPAddrAddress[561][1][1] = "0A 2A 09 3F "
isisISAdjIPAddrAddress[563][1][1] = "0A 2A 09 44 "
isisISAdjIPAddrAddress[565][1][1] = "0A 2A 09 79 "
isisISAdjIPAddrAddress[614][1][1] = "0A 2A 09 37 "
isisISAdjIPAddrAddress[618][1][1] = "0A 2A 09 C8 "
```

I edited the /opt/librenms/includes/snmp.inc.php to add the x to the snmpwalk command:

@Line 657
-    $cmd = gen_snmpwalk_cmd($device, $oid, '-OQUsetX', $mib, $mibdir, $strIndexing);
+    $cmd = gen_snmpwalk_cmd($device, $oid, '-OQUsetXx', $mib, $mibdir, $strIndexing);

Researching why the snmp*walk was returning incorrect info I ran into this page and tried adding the x to the snmp args with successful results

https://net-snmp.sourceforge.io/wiki/index.php/Printable_Characters_and_Hexadecimal_Output_from_the_tools

My LibreNMS
System : Ubuntu 20.04.2
NET-SNMP 5.8

Also tested on Debian 10, OSX 10.15 with the same garbled results.

**Comment by PipoCanaja** [comment]
Hi @wtc-jeff 
Extensive testing should take place after this change, cause it will impact all calls to snmpwalk_group, not only the ISIS ones.

**Comment by ottorei** [comment]
Does it work correctly with the modified snmp calls?

**Comment by wtc-jeff** [comment]
So far I have not experienced any problems adding devices, running discovery, or had problems polling. As PiPCanaja mentioned, there should be extensive testing done to make sure there is not a fringe use case somewhere in LibreNMS that this change breaks.

**Comment by murrant** [comment]
This feels like a broken mib...  ISIS-MIB shows SYNTAX as InetAddressType

**Comment by murrant** [comment]
Nope, it is broken device implementation... FYI, your fix will break other code.   The fix would be to use snmpwalk_cache_oid() instead of snmpwalk_group().  Then you can send -Ox.

Another possible fix would be to report the bug to the vendor (or update firmware if already fixed)

**Comment by wtc-jeff** [comment]
I opened a ticket with Juniper and they responded by having me "run  show snmp mib walk isisISAdj" on the router, this showed the correct results in hex.

```
router> show snmp mib walk isisISAdj
isisISAdjIPAddrAddress.554.1.1 = 0a 2a 09 5b 
isisISAdjIPAddrAddress.561.1.1 = 0a 2a 09 3f 
isisISAdjIPAddrAddress.563.1.1 = 0a 2a 09 44 
isisISAdjIPAddrAddress.565.1.1 = 0a 2a 09 79 
isisISAdjIPAddrAddress.614.1.1 = 0a 2a 09 37 
isisISAdjIPAddrAddress.618.1.1 = 0a 2a 09 c8 
```


Taking it a step further, I ran a tcpdump on the snmpbulkwalk command against the router and the resulting output was showing the correct hex values:

```

13:23:44.148658 IP (tos 0x0, ttl 63, id 57104, offset 0, flags [none], proto UDP (17), length 316)
    x.x.x.250.snmp > x.x.x.17.59832: [udp sum ok]  { SNMPv2c C="community" { GetResponse(267) R=1008580060  138.1.6.3.1.2.614.1.1=1 138.1.6.3.1.2.618.1.1=1 138.1.6.3.1.3.554.1.1=0a_2a_09_5b 138.1.6.3.1.3.561.1.1=0a_2a_09_3f 138.1.6.3.1.3.563.1.1=0a_2a_09_44 138.1.6.3.1.3.565.1.1=0a_2a_09_79 138.1.6.3.1.3.614.1.1=0a_2a_09_37 138.1.6.3.1.3.618.1.1=0a_2a_09_c8 138.1.6.4.1.1.554.1.204=204 138.1.6.4.1.1.561.1.204=204 } } 

```

The issue may be with the lack of hint as mentioned above and is a result of Net-SNMP interpreting the string into ascii, the Juniper is returning the correct values.

**Comment by murrant** [comment]
Thanks for checking with Juniper @wtc-jeff 

I don't understand how the hint could be wrong for one...  maybe the bug is in net-snmp.  What version is your net-snmp?

**Comment by murrant** [comment]
try running snmpwalk with some different output options and see if it still formats it as a string.

**Comment by wtc-jeff** [comment]
> I don't understand how the hint could be right for one... maybe the bug is in net-snmp. What version is your net-snmp?

I am currently running LibreNMS on Ubuntu 20.04.2 LTS, Net-SNMP is distro provided and is currently 5.8 (package 5.8+dfsg-2ubuntu2.3), my secondary poller server is a Debian 10.10 running NET-SNMP 5.7.3 (disto provided version), and on OSX 10.15 running NET-SNMP version 5.6.2.1.  Every test shows the same results when running the snmpbulkwalk without the x added to the query options.

I tested using -OUsetX (no Q) to show the type information, the incorrectly formatted values are being shown as STRING instead of HEX-STRING when the results are correct:

```
isisISAdjIPAddrAddress[554][1][1] = STRING: "
*       ["
isisISAdjIPAddrAddress[561][1][1] = STRING: "
*       ?"
isisISAdjIPAddrAddress[563][1][1] = STRING: "
*       D"
isisISAdjIPAddrAddress[565][1][1] = STRING: "
*       y"
isisISAdjIPAddrAddress[614][1][1] = STRING: "
*       7"
isisISAdjIPAddrAddress[618][1][1] = Hex-STRING: 0A 2A 09 C8 
```
when running the query with the x added and Q removed ( -OUsetXx ) the correct output is shown

```
isisISAdjIPAddrAddress[554][1][1] = Hex-STRING: 0A 2A 09 5B 
isisISAdjIPAddrAddress[561][1][1] = Hex-STRING: 0A 2A 09 3F 
isisISAdjIPAddrAddress[563][1][1] = Hex-STRING: 0A 2A 09 44 
isisISAdjIPAddrAddress[565][1][1] = Hex-STRING: 0A 2A 09 79 
isisISAdjIPAddrAddress[614][1][1] = Hex-STRING: 0A 2A 09 37 
isisISAdjIPAddrAddress[618][1][1] = Hex-STRING: 0A 2A 09 C8
```

The only way to get the un-interpreted output is to use the x  option.

**Comment by ottorei** [comment]
And this a Juniper device? I tried to replicate this with various MX-routers and unfortunately all of the responses are in hex.

Ubuntu 20.04 LTS with libsnmp-base 5.8+dfsg-2ubuntu2.3.

**Comment by wtc-jeff** [comment]
The output above is from a Juniper MX104 running Junos 15.1.r6.7, I have also tested against Junos 14.1.R7.4, 17.3R3-S2.2 on MX480 & MX960 and get the same output results. 

running "show snmp snmp mib walk isisISAdj" on the routers themselves show the correct hex string and mentioned, running a tcpdump while doing a snmpbulkwalk shows the correct values, it changes when the results are displayed on the screen unless the x is added to the query options.

**Comment by wtc-jeff** [comment]
Just to see if I could replicate the issue against another manufacturer, I tested against an older cisco 7301 router and receive the same garbled output:

```
/usr/bin/snmpbulkwalk -v2c -c community -OQUsetX -m ISIS-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:router-c7301:161 CISCO-IETF-ISIS-MIB:ciiISAdj

ciiISAdjIPAddrAddress[2][2][1] = "
*       \\"
ciiISAdjIPAddrAddress[3][1][1] = "
*       ^"


/usr/bin/snmpbulkwalk -v2c -c community -OQUsetXx -m ISIS-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:router-c7301:161 CISCO-IETF-ISIS-MIB:ciiISAdj

ciiISAdjIPAddrAddress[2][2][1] = "0A 2A 09 5C "
ciiISAdjIPAddrAddress[3][1][1] = "0A 2A 09 5E "

```

**Comment by ottorei** [comment]
Just tested with an older MX480 on Junos 17.3R3-S4.2 and all returned addresses were in hex with:
snmpbulkwalk -v2c -c community -OQUsetX -m ISIS-MIB -M /opt/librenms/mibs/ udp:mx480-router:161 ISIS-MIB::isisISAdj

Oldest possible lab device was MX240 on Junos 11.4R6.6 and even that worked correctly.

MIB-file:
https://github.com/ottorei/librenms/blob/worknoc/mibs/ISIS-MIB

Linux packages:
![snmp-ubuntu](https://user-images.githubusercontent.com/7031571/128889683-ebe8a8bb-3997-4f2d-9dfc-f9845dde9e59.PNG)

**Comment by murrant** [comment]
Can I get some testers on https://github.com/librenms/librenms/pull/13155 ?

The code is very different... hopefully faster.

**Comment by wtc-jeff** [comment]
applied the update, are there any specific tests you would like the output from?

**Comment by murrant** [comment]
@wtc-jeff run discovery and polling (or wait for it to run).  Verify all information is correct and all adjacencies are list.

**Comment by ottorei** [comment]
Tested this in our NOC today. So far so good. I will run some checks later but have not found issuea yet.

⁣Hanki BlueMail for Android ​

20. elok. 2021 klo 18.44, 18.44, Tony Murray ***@***.***> kirjoitti:
***@***.*** run discovery and polling (or wait for it to run).  Verify

**Comment by ottorei** [comment]
> 
> 
> applied the update, are there any specific tests you would like the output from?

Have you had any success with the latest codebase?
