### ISSUE TITLE
ADD packetloss alerting

### ISSUE THREAD

**Issue by Alastair-VOIPUNLIMITED** [librenms/librenms#1307]
Hi team,

Would it be possible to monitor and then alert on packet loss?

Cheers

Alastair

**Comment by tylerapplebaum** [comment]
I second this. Solarwinds has this functionality, and it looks like this:

![image](https://cloud.githubusercontent.com/assets/8419153/8264104/1c637968-1697-11e5-867e-b36dd462f5f7.png)

**Comment by paulgear** [comment]
You can already monitor it somewhat using smokeping integration.

**Comment by laf** [comment]
Should be possible now with the linked merged PR
