### ISSUE TITLE
Huawei S5700-28X-LI-24S-DC not showing dbm values

### ISSUE THREAD

**Issue by nintox** [librenms/librenms#13091]
Hello,

We have a lot of S5700-28X-LI-24S-DC and they are not showing up with dbm in librenms.

We have tried different firmwares, the oldest one seems to work best.
But we don't want to be running that firmware on our switches.

V200R008C00SPC500 - Is the oldest firmware and are showing dbm values
V200R010C00SPC600 - Is the current firmware we run on all our switches
V200R011C10SPC600 - Is the newest firmware from Huawei and its only showing TX dbm.

How can we fix this to work with V200R010C00SPC600 firmware that we have on most switches?

**Comment by PipoCanaja** [comment]
Hi,

You need to find out what OID huawei provides to read those values. They are very inconsistant between devices and between versions for a device. 
You can troubleshoot discovery process, play with snmpwalk, and suggest a pull request with the necessary changes in LibreNMS YAML discovery files.

https://docs.librenms.org/Support/Discovery%20Support/#debugging

Bye

**Comment by PipoCanaja** [comment]
By the way, device support request are here : 
https://community.librenms.org/c/device-requests/12
