### ISSUE TITLE
Dlink switches appear to have no ifDescr on some ports.

### ISSUE THREAD

**Issue by laf** [librenms/librenms#131]
See https://ezcrypt.it/be8n#4azbrMfshxnEBLTEu6gzm802

**Comment by toyowheelin** [comment]
po1, po2, po3, po4, po5, po6, po7, po8, Vlanmgmt interfaces seem to be missing again at some point after redoing the device definitions in yaml.

The new fix appears to be adding empty_ifdescr: 1 to the dlink.yaml

**Comment by toyowheelin** [comment]
PR #8402 created to address this.
