### ISSUE TITLE
 librenms/mibs/TNMS-NBI-MIB 

### ISSUE THREAD

**Issue by farhanjohandy** [librenms/librenms#13100]
### The problem

Hi there, i have this error when using TNMS-NBI-MIB in Splunk to convert raw SNMP events

08-03-2021 17:49:05.335 +0700 ERROR ExecProcessor - message from "python /apps/splunk/etc/apps/snmp_ta/bin/snmp.py" pysnmp.smi.error.MibLoadError: MIB module '/apps/splunk/etc/apps/snmp_ta/bin/mibs/user_python_mibs/TNMS-NBI-MIB.pyc' load error: ['Traceback (most recent call last):\n', '  File "/apps/splunk/etc/apps/snmp_ta/bin/pysnmp/smi/builder.py", line 362, in loadModule\n    exec(codeObj, g)\n', '  File "mibs/user_python_mibs/TNMS-NBI-MIB.py", line 1326, in <module>\n    enmsProxyStateChangeTrap = NotificationType((1, 3, 6, 1, 4, 1, 42229, 6, 22, 5, 3, 1, 1)).setObjects(("TNMS-NBI-MIB", "enmsTrapCounter"), ("TNMS-NBI-MIB", "enmsProxyName"), ("TNMS-NBI-MIB", "enmsTrapEventDetails"), ("TNMS-NBI-MIB", "enmsProxyOpState"))\n', '  File "/apps/splunk/etc/apps/snmp_ta/bin/pyasn1/type/univ.py", line 107, in __init__\n    base.SimpleAsn1Type.__init__(self, value, **kwargs)\n', '  File "/apps/splunk/etc/apps/snmp_ta/bin/pyasn1/type/base.py", line 267, in __init__\n    value = self.prettyIn(value)\n', '  File "/apps/splunk/etc/apps/snmp_ta/bin/pysnmp/smi/mibs/SNMPv2-TC.py", line 370, in prettyIn\n    return base.prettyIn(self, value)\n', '  File "/apps/splunk/etc/apps/snmp_ta/bin/pyasn1/type/univ.py", line 258, in prettyIn\n    return int(value)\n', "TypeError: int() argument must be a string or a number, not 'tuple'\n"]caused by <type 'exceptions.TypeError'>: int() argument must be a string or a number, not 'tuple'

the error points to a block in the MIB file which is:

enmsProxyStateChangeTrap NOTIFICATION-TYPE
    OBJECTS
    {
        enmsTrapCounter,
        enmsProxyName,
        enmsTrapEventDetails,
        enmsProxyOpState
    }
    STATUS        current
    DESCRIPTION
         "Proxy state change trap."
    ::= { enmsCommonTraps 1 }

Do you have the latest update for this file? thanks in advance.

### Output of ./validate.php

```txt
08-03-2021 17:49:05.335 +0700 ERROR ExecProcessor - message from "python /apps/splunk/etc/apps/snmp_ta/bin/snmp.py" pysnmp.smi.error.MibLoadError: MIB module '/apps/splunk/etc/apps/snmp_ta/bin/mibs/user_python_mibs/TNMS-NBI-MIB.pyc' load error: ['Traceback (most recent call last):\n', '  File "/apps/splunk/etc/apps/snmp_ta/bin/pysnmp/smi/builder.py", line 362, in loadModule\n    exec(codeObj, g)\n', '  File "mibs/user_python_mibs/TNMS-NBI-MIB.py", line 1326, in <module>\n    enmsProxyStateChangeTrap = NotificationType((1, 3, 6, 1, 4, 1, 42229, 6, 22, 5, 3, 1, 1)).setObjects(("TNMS-NBI-MIB", "enmsTrapCounter"), ("TNMS-NBI-MIB", "enmsProxyName"), ("TNMS-NBI-MIB", "enmsTrapEventDetails"), ("TNMS-NBI-MIB", "enmsProxyOpState"))\n', '  File "/apps/splunk/etc/apps/snmp_ta/bin/pyasn1/type/univ.py", line 107, in __init__\n    base.SimpleAsn1Type.__init__(self, value, **kwargs)\n', '  File "/apps/splunk/etc/apps/snmp_ta/bin/pyasn1/type/base.py", line 267, in __init__\n    value = self.prettyIn(value)\n', '  File "/apps/splunk/etc/apps/snmp_ta/bin/pysnmp/smi/mibs/SNMPv2-TC.py", line 370, in prettyIn\n    return base.prettyIn(self, value)\n', '  File "/apps/splunk/etc/apps/snmp_ta/bin/pyasn1/type/univ.py", line 258, in prettyIn\n    return int(value)\n', "TypeError: int() argument must be a string or a number, not 'tuple'\n"]caused by <type 'exceptions.TypeError'>: int() argument must be a string or a number, not 'tuple'
```

### Anything in the logs that might be useful for us?

```txt
08-03-2021 17:49:05.335 +0700 ERROR ExecProcessor - message from "python /apps/splunk/etc/apps/snmp_ta/bin/snmp.py" pysnmp.smi.error.MibLoadError: MIB module '/apps/splunk/etc/apps/snmp_ta/bin/mibs/user_python_mibs/TNMS-NBI-MIB.pyc' load error: ['Traceback (most recent call last):\n', '  File "/apps/splunk/etc/apps/snmp_ta/bin/pysnmp/smi/builder.py", line 362, in loadModule\n    exec(codeObj, g)\n', '  File "mibs/user_python_mibs/TNMS-NBI-MIB.py", line 1326, in <module>\n    enmsProxyStateChangeTrap = NotificationType((1, 3, 6, 1, 4, 1, 42229, 6, 22, 5, 3, 1, 1)).setObjects(("TNMS-NBI-MIB", "enmsTrapCounter"), ("TNMS-NBI-MIB", "enmsProxyName"), ("TNMS-NBI-MIB", "enmsTrapEventDetails"), ("TNMS-NBI-MIB", "enmsProxyOpState"))\n', '  File "/apps/splunk/etc/apps/snmp_ta/bin/pyasn1/type/univ.py", line 107, in __init__\n    base.SimpleAsn1Type.__init__(self, value, **kwargs)\n', '  File "/apps/splunk/etc/apps/snmp_ta/bin/pyasn1/type/base.py", line 267, in __init__\n    value = self.prettyIn(value)\n', '  File "/apps/splunk/etc/apps/snmp_ta/bin/pysnmp/smi/mibs/SNMPv2-TC.py", line 370, in prettyIn\n    return base.prettyIn(self, value)\n', '  File "/apps/splunk/etc/apps/snmp_ta/bin/pyasn1/type/univ.py", line 258, in prettyIn\n    return int(value)\n', "TypeError: int() argument must be a string or a number, not 'tuple'\n"]caused by <type 'exceptions.TypeError'>: int() argument must be a string or a number, not 'tuple'
```

**Comment by PipoCanaja** [comment]
Hello @farhanjohandy 
Unfortunately, we are not at all involved with splunk. You should contact their support.
Bye
