### ISSUE TITLE
Graphs for "interface non unicast" and "interface errors" show bps instead of pps

### ISSUE THREAD

**Issue by nightcore500** [librenms/librenms#13119]
### The problem

It seems that the graphs for "interface errors" use a wrong unit. The legend does not show pps but bps. The same can be observed under "interface non unicast". This occurs with all graphs. So it is not device dependent.

![Screenshot 2021-08-09 135044](https://user-images.githubusercontent.com/25873532/128702618-18b53437-3e96-4d6c-a8d7-4da66f0523a1.png)
![Screenshot 2021-08-09 135100](https://user-images.githubusercontent.com/25873532/128702619-e6767b89-9c61-43c9-8845-97ebc987aec2.png)

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.7.0-56-gd6039399f
DB Schema | 2021_08_04_102914_add_syslog_indexes (213)
PHP       | 7.4.20
Python    | 3.7.3
MySQL     | 5.7.34-log
RRDTool   | 1.7.1
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 2.1.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

**Comment by murrant** [comment]
Should be a very small fix to send the suffix to the number format function.

**Comment by Cupidazul** [comment]
proposed fix:
https://github.com/librenms/librenms/pull/13266
