### ISSUE TITLE
poller-wrapper.py issue due to missing MIBS

### ISSUE THREAD

**Issue by crcro** [librenms/librenms#13121]
### The problem

Due to some missing MIBS ( in my case they were 2: Dell-Vendor-MIB and SNA-SDLC-MIB) the command 
`php /opt/librenms/config_to_json.php` generated some debug output like:

`# php /opt/librenms/config_to_json.php
MIB search path: /root/.snmp/mibs:/usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf:/opt/librenms/mibs
Cannot find module (SNA-SDLC-MIB): At line 14 in /opt/librenms/mibs/DLSW-MIB
Did not find 'sdlcLSAddress' in module #-1 (/opt/librenms/mibs/DLSW-MIB)
`

that would then throw an python error:

`
s# ./poller-wrapper.py 16 -d
ERROR: Could not execute command [['/usr/bin/env', 'php', '/opt/librenms/config_to_json.php']]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "./poller-wrapper.py", line 37, in <module>
    log_dir = config["log_dir"]
TypeError: 'NoneType' object is not subscriptable
`

causing blanks in my graphs.

in my case adding those 2 mib files into the mibs dir fixed the issue.

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.7.0-61-g93209a0fc
DB Schema | 2021_08_04_102914_add_syslog_indexes (213)
PHP       | 7.4.3
Python    | 3.8.10
MySQL     | 10.3.30-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.1.5
[OK]    Dependencies up-to-date.
[WARN]  Debug enabled.  This is a security risk.
[OK]    Database connection successful
[OK]    Database schema correct
```

### What was the last working version of LibreNMS?

21.7.0-61-g93209a0fc - Tue Aug 10 2021 03:33:04 GMT+0300

**Comment by PipoCanaja** [comment]
Hello
It seems that only mibs/junos/SNA-SDLC-MIB  should be moved back to mibs/SNA-SDLC-MIB. Dell MIB should not be involved. Could you check that ? 
I'll commit a fix. 
Thanx

**Comment by crcro** [comment]
Hello

without that Dell-Vendor-MIB i get the following errors:

`
php /opt/librenms/config_to_json.php
MIB search path: /opt/librenms/.snmp/mibs:/usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf:/opt/librenms/mibs
Cannot find module (Dell-Vendor-MIB): At line 20 in /opt/librenms/mibs/BROADCOM-REF-MIB
Did not find 'dellLanExtension' in module #-1 (/opt/librenms/mibs/BROADCOM-REF-MIB)
Did not find 'dellLan' in module #-1 (/opt/librenms/mibs/BROADCOM-REF-MIB)
Unlinked OID in BROADCOM-REF-MIB: lvl7 ::= { dellLanExtension 6132 }
Undefined identifier: dellLanExtension near line 23 of /opt/librenms/mibs/BROADCOM-REF-MIB
Unlinked OID in BROADCOM-REF-MIB: dellM6220Switch ::= { dellLan 3015 }
Undefined identifier: dellLan near line 65 of /opt/librenms/mibs/BROADCOM-REF-MIB
Unlinked OID in BROADCOM-REF-MIB: dell6224FSwitch ::= { dellLan 3014 }
Undefined identifier: dellLan near line 63 of /opt/librenms/mibs/BROADCOM-REF-MIB
Unlinked OID in BROADCOM-REF-MIB: dell6248PSwitch ::= { dellLan 3013 }
Undefined identifier: dellLan near line 61 of /opt/librenms/mibs/BROADCOM-REF-MIB
Unlinked OID in BROADCOM-REF-MIB: dell6224PSwitch ::= { dellLan 3012 }
Undefined identifier: dellLan near line 59 of /opt/librenms/mibs/BROADCOM-REF-MIB
Unlinked OID in BROADCOM-REF-MIB: dell6248Switch ::= { dellLan 3011 }
Undefined identifier: dellLan near line 57 of /opt/librenms/mibs/BROADCOM-REF-MIB
Unlinked OID in BROADCOM-REF-MIB: dell6224Switch ::= { dellLan 3010 }
Undefined identifier: dellLan near line 55 of /opt/librenms/mibs/BROADCOM-REF-MIB
Did not find 'fastPath' in module BROADCOM-REF-MIB (/opt/librenms/mibs/BROADCOM-POWER-ETHERNET-MIB)
Unlinked OID in BROADCOM-POWER-ETHERNET-MIB: fastPathpowerEthernetMIB ::= { fastPath 15 }
Undefined identifier: fastPath near line 22 of /opt/librenms/mibs/BROADCOM-POWER-ETHERNET-MIB
`

**Comment by PipoCanaja** [comment]
OK
Can you try to move both BROADCOM* files into the "~/mibs/dell" directory, instead of adding Dell-Vendor-MIB to ~/mibs/dell ?

**Comment by crcro** [comment]
with the `BROADCOM-POWER-ETHERNET-MIB` and `BROADCOM-REF-MIB` moved inside dell dir everything works properly.

the Dell-Vendor-MIB was placed inside mibs dir, not inside mibs/dell
