### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by hagaiwech** [librenms/librenms#13144]
### The problem

Hi LibreNMS team,

I did not manage to find any security issue mail address, so I've contacted your personal email.
If you did not get this email, please contact me back at hagai.wechsler@whitesourcesoftware.com,
it is about a security issue.

Thanks,
Hagai

### Output of ./validate.php

```txt
hagai.wechsler@whitesourcesoftware.com
```

**Comment by murrant** [comment]
Did not see an email anywhere.  Can you please contact us on Discord?

**Comment by hagaiwech** [comment]
Hi,
We prefer to contact through email. Can you please send me a message through the address I wrote?

Thanks

**Comment by hagaiwech** [comment]
@murrant
