### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by hagaiwech** [librenms/librenms#13189]
### The problem

Hi @murrant, @Jellyfrog, @laf, @robje,

I tried to contact you both through email (to gh+n@laf.io) and here as an issue. Also, I tried to enter your Discord channel but it seems the link is expired or invalid. 
It is regarding a security issue, please contact me back on email, to this address: hagai.wechsler@whitesourcesoftware.com.
We are approaching the end of the disclosure timeline, which ends in about two weeks.

Thanks,
Hagai

### Output of ./validate.php

```txt
hagai.wechsler@whitesourcesoftware.com
```

**Comment by Jellyfrog** [comment]
Please talk to us on https://discord.gg/librenms

**Comment by hagaiwech** [comment]
@Jellyfrog the link you sent here is expired/invalid, I cannot access. Please contact me by mail, thank you.

**Comment by Jellyfrog** [comment]
I just created a test account via that link, works fine. But ill write you an email
