### ISSUE TITLE
Graph widget showing red lines at the top and bottom

### ISSUE THREAD

**Issue by 3cks** [librenms/librenms#13190]
### The problem

I have LibreNMS running and everything is working great. 

I have a dashboard created that I put in the Graph widget and it is putting a red line across the top and bottom. Is there a way to remove that from the Graph widget?

Here is a picture of what I am referring to.
![image](https://user-images.githubusercontent.com/89936485/131722189-e66a2b9e-ed34-4b1a-9e49-d97df84a5b88.png)

### Output of ./validate.php

```txt
====================================
Component | Version--------- | -------LibreNMS  | 21.8.0-13-g676bb8c5aDB Schema | 2021_25_01_0129_isis_adjacencies_nullable (216)PHP       | 7.4.3Python    | 3.8.10MySQL     | 10.3.31-MariaDB-0ubuntu0.20.04.1RRDTool   | 1.7.2SNMP      | NET-SNMP 5.8
====================================
[OK]    Composer Version: 2.1.6[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

**Comment by 3cks** [comment]
Hi Murrant,

I have posted on the community with a couple issues I am having but never received any replies. So I thought I would ask this question here.  Is there any way to remove that line?

Thank you .

**Comment by ryanov** [comment]
Curious: what possible reason could you have for wanting to remove it? It's useful data.
