### ISSUE TITLE
Dark Theme - Device name colour changed

### ISSUE THREAD

**Issue by FingerlessGlov3s** [librenms/librenms#13260]
### The problem

Since LibreNMS recently updated, the dark theme has make the system names go to a darkish blue, which is a little hard to read at times. I believe this should be white or something to that effect.

Device View
![image](https://user-images.githubusercontent.com/3495647/134218088-a052bb34-3e41-4c1e-a361-0e64d3e1c961.png)

"All Devices" View
![image](https://user-images.githubusercontent.com/3495647/134218330-3ff47041-f393-45d6-b6c0-ba460bd24fc5.png)

### Output of ./validate.php

```txt
$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.9.0
DB Schema | 2021_25_01_0129_isis_adjacencies_nullable (217)
PHP       | 7.3.29-1~deb10u1
Python    | 3.7.3
MySQL     | 10.4.21-MariaDB-1:10.4.21+maria~buster
RRDTool   | 1.7.1
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 2.1.8
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]:
        You can fix this with ./scripts/github-remove
        Modified Files:
         rrd/.gitignore
```

**Comment by murrant** [comment]
What was the previous color?

**Comment by FingerlessGlov3s** [comment]
After some researching for old screenshot I eventually found one.

![image](https://user-images.githubusercontent.com/3495647/134236790-81359683-9c18-4def-8a08-b776613094ff.png)

**Comment by murrant** [comment]
https://github.com/librenms/librenms/pull/13262

**Comment by FingerlessGlov3s** [comment]
Applied PR via the tooling and looks much better.

![image](https://user-images.githubusercontent.com/3495647/134243290-b88fa07b-0d8a-4472-991a-2841fcea3d24.png)

**Comment by efelon** [comment]
This is a sample HTML from one of the device names in the "All devices" list:
```HTML
    <a class="tw-font-bold  tw-text-blue-900 visited:tw-text-blue-900 " href="https://mydomain.com/device/8">
        myserver
    </a>
```
I was not able to find the source file in my time available but the tailwind class `tw-text-blue-900` brings in the blue color. By overwriting this in a custom CSS file you can bring it back to grey.

**Comment by meyerje** [comment]
This is much better than previous.  Is it possible to apply similar changes to the Device\Overview ports section, Device\Ports, and Device\Logs section where the blue on dark background still exists?

**Comment by fcqpl** [comment]
I got enabled light theme and now devices name isn't visible:
![image](https://user-images.githubusercontent.com/46460263/134652400-0453a639-1fc9-4566-8ea7-5a159a536fea.png)

**Comment by murrant** [comment]
Odd, must be enabling dark mode erroneously

**Comment by murrant** [comment]
@fcqpl Do you have your device set to dark mode perhaps?

**Comment by fcqpl** [comment]
> @fcqpl Do you have your device set to dark mode perhaps?

Probably it's dark mode. But every website looks correct, with white background. In LibreNMS i got selected "Light" style.

**Comment by sipshowpeers** [comment]
> @fcqpl Do you have your device set to dark mode perhaps?

I am seeing this issue as well.  On MacOS 11.6 with dark mode set, but with LibreNMS website set to light mode.
Graphs on hover of hostname on devices page also looks a little odd
<img width="305" alt="Screen Shot 2021-09-24 at 8 20 52 PM" src="https://user-images.githubusercontent.com/977103/134751417-8868765d-6d54-4b8c-99ab-d17840d189a4.png">
<img width="622" alt="Screen Shot 2021-09-24 at 8 21 10 PM" src="https://user-images.githubusercontent.com/977103/134751418-4f7874a6-9d04-4806-a737-c4c0fef80695.png">
.

**Comment by murrant** [comment]
Removed device theme detection
