### ISSUE TITLE
ubnt AirMAX M Series wireless data

### ISSUE THREAD

**Issue by Ftelf** [librenms/librenms#1327]
Please add a snmp getters for ubnt airMAX M Series (ie. Rocket M) wireless data.

I have made a Rocket M public for this. Not sure how log I'll make it available though.
Latest firmware 5.8.10 installed on live Access Point with about 5 clients.
snmpwalk -v1 -c public 78.108.155.130:1161 1

There should be one client device available on snmp
78.108.155.130:1162

http://fii.cz/bgzgzb
http://fii.cz/fxyue
http://fii.cz/kdbawpwz
http://fii.cz/qyavsu
http://fii.cz/nepwvg

http://fii.cz/tdjcfgm

Seems like only signal strength, data Rate, data in/out is available through snmp.

It is possible to get all the data through telnet / ssh, but I assume that this is a no-go for librenms.
This is a way how a Zenoss polls all available data.
http://wiki.zenoss.org/ZenPack:Ubiquiti_airMAX_AP

**Comment by Ftelf** [comment]
This issue is obsolete now. UBNT released 5.6.1 firmware version which adds some snmp values to the places when the current code already expected it.
Well the LibreNMS is still not perfect, because it cannot handle the Wifi Client odb on the and their values on the AP device, but it's better now.

**Comment by Rosiak** [comment]
@Ftelf 
Should we keep this issue open?

**Comment by Ftelf** [comment]
I think that with the 5.6.x firmware for airMAX M, there is no need for any more effort from LibreNMS team.
