### ISSUE TITLE
Light theme - hover on device name is dark

### ISSUE THREAD

**Issue by fcqpl** [librenms/librenms#13270]
### The problem

Hello,
Hover on device name is dark. I got enabled light theme
![chrome_mvy7lA18Fb](https://user-images.githubusercontent.com/46460263/134653092-f86aa3c7-71f4-4c6a-8c21-57a50e6f04bb.png)
.

### Output of ./validate.php

```txt
librenms@librenms:~$ /opt/librenms/validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.9.0-19-gd6fa206aa
DB Schema | 2021_08_26_093522_config_value_to_medium_text (217)
PHP       | 7.4.3
Python    | 3.8.10
MySQL     | 10.3.31-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.1.8
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

**Comment by murrant** [comment]
Your device is set to dark mode... I guess we will disable that functionality.

**Comment by fcqpl** [comment]
> Your device is set to dark mode... I guess we will disable that functionality.

My device is in dark mode, correct, but in LibreNMS i have selected Light style, not Dark.

**Comment by murrant** [comment]
That's fine, just need to remove the theme detection code.
