### ISSUE TITLE
Port Disable polling and Ignore alert tag resetting after turning on

### ISSUE THREAD

**Issue by WajeedShaik** [librenms/librenms#13280]
### The problem

The device port is flapping frequently and to suppress the alerts. I have enabled "Disable polling and Ignore alert tag" in the port setting (tried combinations) after a day or two the settings reset and librenms triggering the alert. Any suggestions?

### Output of ./validate.php

```txt
DatabaseOk
DependenciesOk
DiskOk
DistributedpollerOk
MailOk
PhpOk
ProgramsWarning
Warning: IPv6 is disabled on your server, you will not be able to add IPv6 devices.
PythonOk
RrdOk
RrdcheckOk
SystemOk
UpdatesWarning
Warning: Non-git install, updates are manual or from package
UserOk
```

### What was the last working version of LibreNMS?

21.5.0

**Comment by murrant** [comment]
Use the port macro in your alert rule to allow ports to be ignored:
https://docs.librenms.org/Alerting/Macros/#port-boolean
