### ISSUE TITLE
Hovering (tooltip) charts positioned under other panels in dashboard

### ISSUE THREAD

**Issue by TD-er** [librenms/librenms#13298]
### The problem

![image](https://user-images.githubusercontent.com/3751318/135402958-01460f47-d1b6-440a-87f3-002ff1ea9aca.png)
See the image.
When hovering over the items on the dashboard page, it does show the tooltip with charts under the other panels.

This used to work, but roughly a month a go, it shows the charts under the other panels.

The next one is probably related, as it also was changed at the same time.
When looking through a list of devices (doesn't matter which list), the hovering charts may block the clickable link to the device.
![image](https://user-images.githubusercontent.com/3751318/135403555-d40eeae7-b951-4d37-9a37-beae7e0603f0.png)
This depends on the used browser scaling(zoom) and may also be related to the Windows scaling factor as it differs among computers I use.
The problem will get worse, the further down the list you go, so that may also be my 'feeling' it may be related to the scaling factor. (125% on 4k screens -> longer pages)

This screenshot was taken on 100% zoom in the browser and 125% scaling in Windows. (Chrome)
This one is really frustrating as it sometimes leaves just a few pixels to click, on devices which have either capitals or "longer letters".

### Output of ./validate.php

```txt
Not related as it is a browser/display issue
```

**Comment by murrant** [comment]
https://github.com/librenms/librenms/pull/13257 exists already.  Unless you can find a better fix.
Perhaps appending the popup to the body instead of directly in the html would fix it, but the logistics seem sketchy for that.

**Comment by TD-er** [comment]
It has been fixed now.
Thanks :)
