### ISSUE TITLE
LibreNMS widget Top interfaces and Top traffic are displaying No data

### ISSUE THREAD

**Issue by hescobar627** [librenms/librenms#13294]
### The problem

I have recently installed LibreNMS on a new OS (Rocky Linux).  I copied all the files need rrd/ .env config.php and librenms.sql database.  Everything seems to be working except for the widgets the Top Interfaces and Top Traffic are showing 'No data' Its been up for over 12 hours and done multiple reboots and I got nothing.  I did recreted the widgets with no success. 

[librenms@S-MCSOS-LibreNMS ~]$ ./daily.sh 
Updating to latest codebase                        OK
Updating Composer packages                         OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK
Caching Mac OUI data                               OK

### Output of ./validate.php

```txt
[librenms@S-MCSOS-LibreNMS ~]$ ./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 21.9.0-34-g50f766476
DB Schema | 2021_25_01_0129_isis_adjacencies_nullable (217)
PHP       | 7.3.20
Python    | 3.6.8
MySQL     | 10.5.12-MariaDB
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.1.8
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

### What was the last working version of LibreNMS?

21.9.0-34

**Comment by murrant** [comment]
Are you sure your poller is running?

**Comment by hescobar627** [comment]
> Are you sure your poller is running?

I believe it is. I did manually run the script poller-wrapper.py -d bellow is the output:

#### End Alerts ####
/opt/librenms/poller.php 155 2021-10-01 08:05:24 - 1 devices polled in 1.835 secs  
MySQL [11/0.04s]: Cell[1/0.00s] Row[-1/-0.00s] Rows[3/0.01s] Column[1/0.00s] Update[6/0.02s] Insert[1/0.01s] Delete[0/0.00s]
RRD [7/0.00s]: Update[7/0.00s]

2021-10-01 08:05:24,539 :: INFO :: worker Thread-8 finished device 155 in 2 seconds
2021-10-01 08:05:24,539 :: INFO :: poller-wrapper checked 140 devices in 122 seconds with 6 workers with 0 errors
[librenms@S-MCSOS-LibreNMS ~]$
