### ISSUE TITLE
Duplicate entries under OSPF  

### ISSUE THREAD

**Issue by dejantep** [librenms/librenms#13343]
### The problem

Duplicate entries are showing wherever you have ospf information present. For instance
https://librenms/routing/protocol=ospf
https://librenms/device/device=XX/tab=routing/proto=ospf/

Even when you expand device information to show neighbors  you'll see duplicate entries

![image](https://user-images.githubusercontent.com/71568639/136337652-30b5fe48-7955-4285-99d3-9ae9db5ba0dd.png)

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.9.0-71-g8d5bc3fc4
DB Schema | 2021_09_07_094310_create_push_subscriptions_table (221)
PHP       | 7.4.12
Python    | 3.6.9
MySQL     | 10.2.37-MariaDB-1:10.2.37+maria~bionic
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 2.1.8
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

**Comment by murrant** [comment]
If you manually delete them both, do they come back?  I think there was a brief state where you could get duplicates, but because the way cleans up, it won't remove duplicates.  AKA, you may have just gotten unlucky.

**Comment by dejantep** [comment]
How do i do manual removal?
