### ISSUE TITLE
Bad default alert rule collection: Dell iDRAC Memory Status Critical

### ISSUE THREAD

**Issue by IKatsu** [librenms/librenms#13389]
### The problem

The default 'Dell iDRAC Memory Status Critical' alert rule is faulty and produces no results.
The current is:
```
sensors.sensor_current REGEX 5
sensors.sensor_oid EQUAL .1.3.6.1.4.1.674.10892.5.4.1100.50.1.5
```
or as SQL:
```
SELECT * FROM devices,sensors WHERE (devices.device_id = ? AND devices.device_id = sensors.device_id) AND sensors.sensor_current REGEXP 5 AND sensors.sensor_oid = ".1.3.6.1.4.1.674.10892.5.4.1100.50.1.5"
```

This should be:
```
sensors.sensor_current != 0
sensors.sensor_current != 3
sensors.sensor_oid BEGINS WITH .1.3.6.1.4.1.674.10892.5.4.1100.50.1.5
```
or as SQL:
```
SELECT * FROM devices,sensors WHERE (devices.device_id = ? AND devices.device_id = sensors.device_id) AND sensors.sensor_current != 0 AND sensors.sensor_current != 3 AND sensors.sensor_oid LIKE '.1.3.6.1.4.1.674.10892.5.4.1100.50.1.5%' 
```

Sensor current 0 means there is no dimm installed, sensor current 3 means normal.
There is a state 4 which is a theoretically a non critical failure but it's actually critical hence the 2 excludes and not a regex on 5.
Regarding the OID change to _LIKE_, the DIMMs are numbered from 1 to however many can fit in the server.
.1.3.6.1.4.1.674.10892.5.4.1100.50.1.5.1 / .1.3.6.1.4.1.674.10892.5.4.1100.50.1.5.2 / .1.3.6.1.4.1.674.10892.5.4.1100.50.1.5.3 etc

### Output of ./validate.php

```txt
not relevant
```

### What was the last working version of LibreNMS?

21.10.0-24-gf94f7f23b

**Comment by Jellyfrog** [comment]
Please send a pull request

**Comment by laf** [comment]
This alert rule was removed fully so closing this issue.
