### ISSUE TITLE
"Device rebooted" alerts after daily update

### ISSUE THREAD

**Issue by fcqpl** [librenms/librenms#13386]
### The problem

Hello,
We have ~160 alerts "Device Rebooted" on two LibreNMS instances after daily update.

Is something broken in 2021-10-20 daily update?

![chrome_lYzYtwEDQU](https://user-images.githubusercontent.com/46460263/138000523-f7a12013-ae0d-488c-a7b7-a0b5eb8119c4.png)
![image](https://user-images.githubusercontent.com/46460263/138000429-fae1fcd4-a0dd-4029-90ea-fd7171a88502.png)

### Output of ./validate.php

```txt
librenms@librenms:~$ /opt/librenms/validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.10.0-24-gf94f7f23b
DB Schema | 2021_07_28_102443_plugins_add_version_and_settings (222)
PHP       | 7.4.3
Python    | 3.8.10
MySQL     | 10.3.31-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.1.9
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

**Comment by nightcore500** [comment]
I can confirm this. A few minutes ago I was surprised by a flood of reboot alerts. The uptime graph is missing on the affected devices. In addition, the uptime on the device overview is stuck at a few seconds.

**Comment by TheMysteriousX** [comment]
This hasn't resolved things for me - I think I've now hit a wrap around issue. Not everything is affected, but some devices have gained implausible uptimes and are continuing to generate notifications, e.g.:


  | 2021-10-20 02:49:09 |   | Device rebooted after  37 years 243 days 10 hours 57 minutes 21 seconds -> 11878694s
  | 2021-10-20 02:47:32 |   | Device rebooted after  37 years 243 days 8 hours 16 minutes 17 seconds -> 11878597s
  | 2021-10-20 02:42:32 |   | Device rebooted after  37 years 242 days 23 hours 55 minutes 31 seconds -> 11878297s
  | 2021-10-20 02:37:31 |   | Device rebooted after  37 years 242 days 15 hours 33 minutes 16 seconds -> 11877996s
  | 2021-10-20 02:32:30 |   | Device rebooted after  37 years 242 days 7 hours 12 minutes 48 seconds -> 11877695s
  | 2021-10-20 02:27:31 |   | Device rebooted after  37 years 241 days 22 hours 53 minutes 15 seconds -> 11877396s

```
#### Load poller module core ####
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/raritan' '-v3' '-l' 'authPriv' '-n' "" '-x' 'AES' '-X' 'PASSWORD' '-a' 'SHA' '-A' 'PASSWORD' '-u' 'USER' '-OQXUte' '-On' 'udp:HOSTNAME:161' 'SNMPv2-MIB::sysDescr.0' 'SNMPv2-MIB::sysObjectID.0' 'SNMPv2-MIB::sysUpTime.0' 'SNMPv2-MIB::sysName.0']
.*.*.0 = PX2 030610
.*.*.0 = .*.4.1.13742.6
.*.*.0 = 1187879495
.*.*.0 = pdu-005-b

SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/raritan' '-v3' '-l' 'authPriv' '-n' "" '-x' 'AES' '-X' 'PASSWORD' '-a' 'SHA' '-A' 'PASSWORD' '-u' 'USER' '-OQXUte' 'udp:HOSTNAME:161' 'SNMP-FRAMEWORK-MIB::snmpEngineTime.0' 'HOST-RESOURCES-MIB::hrSystemUptime.0']
SNMP-FRAMEWORK-MIB::snmpEngineTime.0 = 11878823
HOST-RESOURCES-MIB::hrSystemUptime.0 = No Such Object available on this agent at this OID


Uptime seconds: 11878823

SQL[insert into `eventlog` (`device_id`, `reference`, `type`, `datetime`, `severity`, `message`, `username`) values (?, ?, ?, ?, ?, ?, ?) [386,"1187879495","reboot","2021-10-20 02:51:18",4,"Device rebooted after  37 years 243 days 14 hours 31 minutes 35 seconds -> 11878823s",""] 2.28ms]

RRD[last pdu-005-b/uptime.rrd  --daemon unix:/run/rrdcached.sock]
RRD[update pdu-005-b/uptime.rrd N:11878823 --daemon unix:/run/rrdcached.sock]
Uptime:  137 days 11 hours 40 minutes 23 seconds
SQL[update `devices` set `uptime` = ? where `device_id` = ? ["11878823",386] 1.83ms]


>> Runtime for poller module 'core': 0.1727 seconds with 132320 bytes
>> SNMP: [2/0.16s] MySQL: [2/0.04s] RRD: [2/0.00s]
#### Unload poller module core ####
```

**Comment by fcqpl** [comment]
> #13388 fixed it, so run ./daily.sh if you still have a bug

Oops, sorry. We made daily.sh only after this PR: https://github.com/librenms/librenms/pull/13387
Looks fixed with https://github.com/librenms/librenms/pull/13388

**Comment by murrant** [comment]
hmm, I wonder if the datetime between is wrong.
