### ISSUE TITLE
Custom port description (ifAlias) gets overwritten on next poll

### ISSUE THREAD

**Issue by mjbnz** [librenms/librenms#13381]
### The problem

For devices that have port names longer than 25 characters (32 - `strlen('ifName:')` (7) = 25), a custom port description gets overwritten on the next device poll. This happens because the `attrib_type` column in the `devices_attribs` table is only a `VARCHAR(32)`. Increasing this to something like 64 might be useful.

The device in question that I found this on was a QinQ interface from a VPP router. Interfaces with 3 digits or less (or 1 digit QinQ) vlans worked fine, but anything longer would get overwritten on the next poll:

`GigabitEthernet13/0/0` => 21  becomes: `ifName:GigabitEthernet13/0/0` => 28
`GigabitEthernet13/0/0.123` => 25 becomes: `ifName:GigabitEthernet13/0/0.123` => 32
or QinQ:
`GigabitEthernet13/0/0.1.2` => 25 becomes: `ifName:GigabitEthernet13/0/0.1.2` => 32

however:
`GigabitEthernet13/0/0.123.456` => 29 becomes: `ifName:GigabitEthernet13/0/0.123` => 32

This then fails to match the interface name when checking attributes here: https://github.com/librenms/librenms/blob/master/includes/polling/ports.inc.php#L670 .

### Output of ./validate.php

```txt
N/A
```

### Anything in the logs that might be useful for us?

```txt
N/A
```

**Comment by murrant** [comment]
I wonder if you hit the length limit of a database field. Can you check in your database (device_prefs table)?

**Comment by mjbnz** [comment]
> I wonder if you hit the length limit of a database field. Can you check in your database (device_prefs table)?

My first paragraph literally says it's a db field length issue. So, yes.

**Comment by murrant** [comment]
@mjbnz somehow missed that when reading.  I must have been a bit too tired.  Should be an easy fix, would you like to try to send it?
