### ISSUE TITLE
False alerts being generated

### ISSUE THREAD

**Issue by tylerapplebaum** [librenms/librenms#1341]
![image](https://cloud.githubusercontent.com/assets/8419153/8357885/1a2c7fa8-1b12-11e5-9fd2-f6eb2f463250.png)

Libre keeps telling me that devices are being rebooted or are up/down. This is definitely not the case.

Validate.php looks good.

root@librenms:/opt/librenms# ./validate.php
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php5/cli/conf.d/mcrypt.ini on line 1 in Unknown on line 0
[OK]      config.php tested ok
[OK]      Database connection successful
[OK]      fping has been found
root@librenms:/opt/librenms#

**Comment by f0o** [comment]
I think this is just a symptom of the issue being described in the IRC and hopefully addressed with revert-pr #1340 

@tylerapplebaum Can you check your eventlog if there are Off/Unreachable events about the time the alert got triggered?

// @laf

**Comment by tylerapplebaum** [comment]
I would love to, but...

Showing 1 to 50 of 124641 entries

This started after yesterday's updates. Way too much to sift through without knowing exactly what I'm looking for. If there's something specific I can look for to help, please let me know.

**Comment by f0o** [comment]
@tylerapplebaum under `/eventlog/` search for the terms `Device status changed to Down`

**Comment by tylerapplebaum** [comment]
Yep, there's 400 or so since yesterday's pull.

2015-06-24 11:41:08 is the first "fake" down status.

**Comment by f0o** [comment]
@tylerapplebaum I think this issue has been addressed already and a fix is upstream.

If not, please yell ;)

**Comment by tylerapplebaum** [comment]
You're right; looks better now.
