### ISSUE TITLE
Login remember me - no longer remembers

### ISSUE THREAD

**Issue by JohnyGemityg** [librenms/librenms#13436]
### The problem

Hello guys,

it seems to me that remember me login option does not work anymore. I used remember me login option on my monitoring PC with dashboards.

I know there is an option to put username and password directly to the URL, but since we use AD login I don't want to let plaintext username and password in the URL. It is not visible but still.

Using local user does not work when AD login is enabled.

How long should the remember me option remember?

Is there any other option how to display dashboard without plaintext AD credentials in URL?

Thanks. 

### Output of ./validate.php

```txt
bash-4.4$ ./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 21.10.0-52-gd211944f4
DB Schema | 2021_10_20_224207_increase_length_of_attrib_type_column (224)
PHP       | 7.4.24
Python    | 3.6.8
MySQL     | 10.3.28-MariaDB
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.1.9
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

### Anything in the logs that might be useful for us?

```txt
Nothing suspicions in /opt/librenms/logs/
```

**Comment by JohnyGemityg** [comment]
Hello guys any idea or workaround?

**Comment by murrant** [comment]
A quick test shows me it does work.  Did you block cookies for your nms site perhaps?

**Comment by JohnyGemityg** [comment]
> A quick test shows me it does work. Did you block cookies for your LibreNMS site perhaps?

Have you tried log in with remember me and get back to it after 24H?

I dont know about anything that would block cookies. I have tried it with Firefox and Google Chrome. 

I see after fresh login.
![obrazek](https://user-images.githubusercontent.com/3658238/140280329-6a1ba539-6be1-4e12-99b9-5bb4aa1557a7.png)

But next day. This cookie is missing and I have to log in again.

**Comment by murrant** [comment]
I wonder if it is tied to `SESSION_LIFETIME` now.

**Comment by JohnyGemityg** [comment]
> I wonder if it is tied to `SESSION_LIFETIME` now.

I will try to adjust this parameter in .env. Will see tomorrow.

**Comment by JohnyGemityg** [comment]
Ok, adjusting SESSION_LIFETIME helps. I suppose it modifies all sessions no matter remember on, but it solves my issue.
