### ISSUE TITLE
Mikrotik changed UPS estimated runtime from reporting seconds to minutes

### ISSUE THREAD

**Issue by TechieDylan** [librenms/librenms#13441]
### The problem

Since version 6.47 Mikrotik had changed the OID for measuring UPS Runtime (.1.3.6.1.2.1.33.1.2.3) from seconds to minutes to follow RFC1628 (confirmed from Janis at mikrotik support)

Changelog line in 6.47 relating to this: *) snmp - changed "upsEstimatedMinutesRemaining" reported value from seconds to minutes;

### Output of ./validate.php

```txt
N/A
```

### Device info

Mikrotik - Any Model

### Discovery output

```txt
N/A
```

### Poller output

```txt
N/A
```

**Comment by murrant** [comment]
PHP has a version_compare() function which does what you want.
```php
    if (Str::startsWith($oid, '.1.3.6.1.2.1.33.1.2.3.')) {
            if ($device['os'] == 'routeros' && version_compare($os_version), '6.47', '<') {
               return 60;
            }

            return 1;
    }
```

Are you willing to send a pull request with that change, or would you like me to submit it for you?

**Comment by TechieDylan** [comment]
If you could that would be great. I haven't done a pull before.

Thank you for your help!

**Comment by TechieDylan** [comment]
@murrant Looking for a bit more assistance with this one, looks like it still matches and returns 60. Had noticed sooner but was too busy to investigate at the time.

Looking at it now it seems that $os_version is reporting an empty string causing it to always match the IF statement: `if ($device['os'] == 'routeros' && version_compare($os_version, '6.47', '<'))`

When I hard set the value to the OS Version in my case its '6.49.2' it works as expected.

**Comment by TechieDylan** [comment]
Seems like its related to https://github.com/librenms/librenms/blob/7c157c1577c7d7dceb01269114f100d08609b911/includes/discovery/sensors/runtime/rfc1628.inc.php#L34

Specifically this value $pre_cache['poweralert_serial'] it passes. When I change that to '6.49.2' it works as well.

**Comment by murrant** [comment]
So, that variable is mislabled.

Just use $device['version'] instead.

**Comment by TechieDylan** [comment]
That does the trick! 

`if ($device['os'] == 'routeros' && version_compare($device['version'], '6.47', '<'))`

If you want to submit that change again feel free.

Thanks again for your help.

**Comment by murrant** [comment]
Sorry, I won't have the time.  Feel free to submit one.
