### ISSUE TITLE
Syslog - All Programs & All Priorities Tab does not populate when Syslog Table is very large

### ISSUE THREAD

**Issue by mxmartins** [librenms/librenms#13448]
### The problem

I have syslog enabled on LibreNMS.  I have numerous devices forwarding their syslogs to LibreNMS.  That functionality is working properly.  However, when the syslog table has over approximately 50 million records, the All Programs tab and All Priorities tab do not populate at all.  The tabs return "The results could not be loaded".

Problem is described here as well (https://community.librenms.org/t/syslog-view-does-not-populate-all-programs-tab/17257).  The screen shot and validate info are there as well.

### Output of ./validate.php

```txt
librenms@LibreNMS:~$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.10.2
DB Schema | 2021_10_20_224207_increase_length_of_attrib_type_column (224)
PHP       | 7.4.3
Python    | 3.8.10
MySQL     | 10.3.31-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.1.9
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[WARN]  Your database schema has extra migrations (2021_07_28_102443_plugins_add_version_and_settings, 2021_10_20_072929_disable_example_plugin, 2021_10_20_224207_increase_length_of_attrib_type_column). If you just switched to the stable release from the daily release, your database is in between releases and this will be resolved with the next release.
[OK]    Database schema correct
librenms@LibreNMS:~$
```

### Anything in the logs that might be useful for us?

```txt
The only error in the log is this, repeated a few times:

2021-10-28 14:55:01 240707 [Warning] Aborted connection 240707 to db: 'librenms' user: 'librenms' host: 'localhost' (Got an error reading communication packets)
```

**Comment by mxmartins** [comment]
Looking at the query used to fill the tab, as reported by slow-query

# Time: 211103 10:59:00
# User@Host: librenms[librenms] @ localhost []
# Thread_id: 10557  Schema: librenms  QC_hit: No
# Query_time: 20.449829  Lock_time: 0.000014  Rows_sent: 51  Rows_examined: 24151708
# Rows_affected: 0  Bytes_sent: 1145
SET timestamp=1635958740;
select distinct `program` from `syslog` limit 51 offset 0;

Wouldn't an index on the 'program' field yield faster results?

**Comment by mxmartins** [comment]
After digging into this problem, it turns out the default mysql/mariaDB settings were not appropriate for my situation, given the extremely large size of the syslog table.  
I tweaked the mysql settings/configuration, and now all works as advertised.

**Comment by ciroiriarte** [comment]
> After digging into this problem, it turns out the default mysql/mariaDB settings were not appropriate for my situation, given the extremely large size of the syslog table. I tweaked the mysql settings/configuration, and now all works as advertised.

out of curiosity, what did you change?
