### ISSUE TITLE
ALL LOCATION tab showing nothing

### ISSUE THREAD

**Issue by troublestarter** [librenms/librenms#13455]
### The problem

The "ALL LOCATION" showing nothing.

![image](https://user-images.githubusercontent.com/6012203/139605329-71aa7d29-4e53-4aa9-9c7d-11e0698419f9.png)

I have many locations registered
![image](https://user-images.githubusercontent.com/6012203/139605397-88e7e73f-a7ed-488a-b1f6-50978cad075b.png)

### Output of ./validate.php

```txt
librenms@supervision:~$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.10.0-77-g064463915
DB Schema | 2021_25_01_0129_isis_adjacencies_nullable (224)
PHP       | 7.4.25
Python    | 3.9.2
MySQL     | 10.5.12-MariaDB-0+deb11u1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.9
====================================

[OK]    Composer Version: 2.1.10
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

**Comment by murrant** [comment]
Can you look for an error generated in your logs/librenms.log?  Otherwise there isn't enough info here to fix anything.  Thanks.

**Comment by troublestarter** [comment]
Sorry, i miss some errors in the log :

many line like this 

Next Illuminate\Database\QueryException: SQLSTATE[HY000] [1045] **Access denied for user 'librenms'@'localhost' (using password: NO) (SQL: select * from `config` where (`config_name` = rrdtool_version) l**
imit 1) in /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:703
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(663): Illuminate\Database\Connection->runQueryCallback()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(367): Illuminate\Database\Connection->run()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2351): Illuminate\Database\Connection->select()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2339): Illuminate\Database\Query\Builder->runSelect()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2873): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2340): Illuminate\Database\Query\Builder->onceWithColumns()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(615): Illuminate\Database\Query\Builder->get()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(599): Illuminate\Database\Eloquent\Builder->getModels()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(259): Illuminate\Database\Eloquent\Builder->get()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(464): Illuminate\Database\Eloquent\Builder->first()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(498): Illuminate\Database\Eloquent\Builder->firstOrNew()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->updateOrCreate()
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2109): Illuminate\Database\Eloquent\Model->forwardCallTo()
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2121): Illuminate\Database\Eloquent\Model->__call()
#14 /opt/librenms/LibreNMS/Config.php(255): Illuminate\Database\Eloquent\Model::__callStatic()
#15 /opt/librenms/LibreNMS/Config.php(462): LibreNMS\Config::persist()
#16 /opt/librenms/LibreNMS/Config.php(60): LibreNMS\Config::processConfig()
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(957): LibreNMS\Config::load()
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(900): Illuminate\Foundation\Application->fireAppCallbacks()
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\Foundation\Application->bootstrapWith()
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(136): Illuminate\Foundation\Http\Kernel->bootstrap()
#23 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#24 /opt/librenms/html/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#25 {main}
[2021-10-31 17:22:38] production.ERROR: Error when loading hook App\Plugins\ExamplePlugin\DeviceOverview of type App\Plugins\Hooks\DeviceOverviewHook for ExamplePlugin: Trying to get property 'plugin_a
ctive' of non-object
[2021-10-31 17:22:38] production.ERROR: Error when loading hook App\Plugins\ExamplePlugin\Menu of type App\Plugins\Hooks\MenuEntryHook for ExamplePlugin: Trying to get property 'plugin_active' of non-o
bject
[2021-10-31 17:22:38] production.ERROR: Error when loading hook App\Plugins\ExamplePlugin\Page of type App\Plugins\Hooks\PageHook for ExamplePlugin: Trying to get property 'plugin_active' of non-object

[2021-10-31 17:22:38] production.ERROR: Error when loading hook App\Plugins\ExamplePlugin\PortTab of type App\Plugins\Hooks\PortTabHook for ExamplePlugin: Trying to get property 'plugin_active' of non-
object
[2021-10-31 17:22:38] production.ERROR: Error when loading hook App\Plugins\ExamplePlugin\Settings of type App\Plugins\Hooks\SettingsHook for ExamplePlugin: Trying to get property 'plugin_active' of no
n-object
[2021-10-31 17:22:38] production.ERROR: PDOException: SQLSTATE[HY000] [1045] Access denied for user 'librenms'@'localhost' (using password: NO) in /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/D
river/PDOConnection.php:40
Stack trace:
#0 /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(40): PDO->__construct()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(67): Doctrine\DBAL\Driver\PDOConnection->__construct()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\Database\Connectors\MySqlConnector->connect()
#5 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1021): call_user_func()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1057): Illuminate\Database\Connection->getPdo()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(433): Illuminate\Database\Connection->getReadPdo()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(359): Illuminate\Database\Connection->getPdoForSelect()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(696): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(663): Illuminate\Database\Connection->runQueryCallback()
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(367): Illuminate\Database\Connection->run()

**Comment by troublestarter** [comment]
i confirm that i have done the MariaDB part in the documentation as follow
CREATE DATABASE librenms CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'librenms'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON librenms.* TO 'librenms'@'localhost';
FLUSH PRIVILEGES;
exit

**Comment by murrant** [comment]
@troublestarter are your database credentials correct in `/opt/librenms/.env`?

**Comment by troublestarter** [comment]
Yes correct, and just tested it again in CLI

root@supervision:/opt/uptime-kuma# cat /opt/librenms/.env
APP_KEY=XXXXXXXXXXXXXXXXXXXXXXXXX(masked)

DB_HOST=localhost
DB_DATABASE=librenms
DB_USERNAME=librenms
DB_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXX(masked)

#APP_URL=
NODE_ID=617ec0564858e
VAPID_PUBLIC_KEY=XXXXXXXXXXXXXXXXXXXXXXXXX(masked)

root@supervision:/opt/uptime-kuma# mysql -ulibrenms -pXXXXXXXXXXXXXXXXXXXXXXXXX(masked)
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 17536
Server version: 10.5.12-MariaDB-0+deb11u1 Debian 11

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>

**Comment by murrant** [comment]
`Access denied for user 'librenms'@'localhost' (using password: NO)`  You'll need to fix that first.  Make sure you don't have any db_* settings in your config.php

**Comment by troublestarter** [comment]
ok will investiguate but it seems i have no recent error like this in the log.

**Comment by troublestarter** [comment]
Hi Tony,

The errors in librenms.log seems old errors.

No db_* settings in config.php.
See below

<?php

## Have a look in misc/config_definitions.json for examples of settings you can set here. DO NOT EDIT misc/config_definitions.json!

// This is the user LibreNMS will run as
//Please ensure this user is created and has the correct permissions to your install
#$config['user'] = 'librenms';

### This should *only* be set if you want to *force* a particular hostname/port
### It will prevent the web interface being usable form any other hostname
#$config['base_url']        = "/";

### Enable this to use rrdcached. Be sure rrd_dir is within the rrdcached dir
### and that your web server has permission to talk to rrdcached.
#$config['rrdcached']    = "unix:/var/run/rrdcached.sock";

### Default community
#$config['snmp']['community'] = array('public');

### Authentication Model
#$config['auth_mechanism'] = "mysql"; # default, other options: ldap, http-auth
#$config['http_auth_guest'] = "guest"; # remember to configure this user if you use http-auth

### List of RFC1918 networks to allow scanning-based discovery
#$config['nets'][] = "10.0.0.0/8";
#$config['nets'][] = "172.16.0.0/12";
#$config['nets'][] = "192.168.0.0/16";

# Uncomment the next line to disable daily updates
#$config['update'] = 0;

# Number in days of how long to keep old rrd files. 0 disables this feature
#$config['rrd_purge'] = 0;

# Uncomment to submit callback stats via proxy
#$config['callback_proxy'] = "hostname:port";

# Set default port association mode for new devices (default: ifIndex)
#$config['default_port_association_mode'] = 'ifIndex';

# Enable the in-built billing extension
#$config['enable_billing'] = 1;

# Enable the in-built services support (Nagios plugins)
#$config['show_services'] = 1;

**Comment by troublestarter** [comment]
I just find the problem, this is only appears in French language ! (No issue in english).

**Comment by rtorrente** [comment]
Same issue here

All location tabs show empty array with French Language Interface.

Error in js console is "Uncaught SyntaxError: missing ) after argument list" on locations:247 

The line is : 

`toastr.error('Echec de suppression de l'emplacement: ' + e.statusText)`

It seem there is no escape before ' of "l'emplacement"

**Comment by troublestarter** [comment]
The problem has been solved.
Please do an update.
