### ISSUE TITLE
Issue with .lnms migrate after upgrading PHP and Composer

### ISSUE THREAD

**Issue by Tommytdrx** [librenms/librenms#13472]
### The problem

So, we went to upgrade to php7.4 and Libre broke, so if it was broke we went for broke and upgraded everything, php8.0.12, Composer 2.1.11, python 3.8.10, you can see the rest in the ./validate.php below. 

Suffice it to say, everything looked OK and the login page came up, then it said I had a few errors I fixed and needed to run ./lnms migrate. I did this and it did not fix Libre, I re-ran it with --force and -vv verbosity to have a trace of what happened. and at this point I just need some help. I have been all over the support forms, here on github and refrained from asking anyone because I am a resourceful guy and I can copy an paste like the next guy who had the same issues I have had before. However, I have not seen much about this issue or searched it wrong. 

I get that it says the index column exceeds the maximum colunm size, but how would any production system running for some time not exceed 767 bytes? Is there a fix or a work around? I have been running the ./daily.sh with the exception of getting the Composer/PHP/Laravel Framework out of the vicious cycle of "Running composer update is not advisable.  Please run composer install to update instead. If know what you are doing and want to write a new composer.lock file set FORCE=1. If you don't know what to do, run: composer install" and "composer install  > LibreNMS\ComposerHelper::preInstall
Installing dependencies from lock file (including require-dev)  Verifying lock file contents can be installed on current platform. Your lock file does not contain a compatible set of packages. Please run composer update. "

So you can't run update and you can't run install. Uninstalling composer does no good because it doesn't create a new lock file or pull right on reinstall. The solution there was copying the current composer.lock file from github and dropping it in and editing it by hand so it allowed updates properly. Believe me I have notes on top of notes of each error and solution I faced/fixed. Some by plan, some by trial and error.

Anyway, here are my current errors below:

$ ./lnms migrate --force -vv
SQL[select `config_name`, `config_value` from `config` [] 0.47ms]

SQL[select * from `graph_types` [] 0.5ms]

SQL[select * from information_schema.tables where table_schema = ? and table_name = ? and table_type = 'BASE TABLE' ["librenms","migrations"] 1.47ms]

SQL[select * from information_schema.tables where table_schema = ? and table_name = ? and table_type = 'BASE TABLE' ["librenms","migrations"] 0.91ms]

SQL[select `migration` from `migrations` order by `batch` asc, `migration` asc [] 3.68ms]

SQL[select `migration` from `migrations` order by `batch` asc, `migration` asc [] 0.55ms]

SQL[select max(`batch`) as aggregate from `migrations` [] 0.77ms]

Migrating: 2020_12_14_091314_create_port_groups_table
SQL[select * from information_schema.tables where table_schema = ? and table_name = ? and table_type = 'BASE TABLE' ["librenms","port_groups"] 1.64ms]

SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes (SQL: alter table `port_groups` add unique `port_groups_name_unique`(`name`)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes (SQL: alter table `port_groups` add unique `port_groups_name_unique`(`name`)) at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:703)
[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: HY000): SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes at /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)
[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes at /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)"}

   Illuminate\Database\QueryException

  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes (SQL: alter table `port_groups` add unique `port_groups_name_unique`(`name`))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:703
    699▕         // If an exception occurs when attempting to run a query, we'll format the error
    700▕         // message to include the bindings with SQL, which will make this exception a
    701▕         // lot more helpful to the developer instead of just the database's errors.
    702▕         catch (Exception $e) {
  ➜ 703▕             throw new QueryException(
    704▕                 $query, $this->prepareBindings($bindings), $e
    705▕             );
    706▕         }
    707▕     }

  1   vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
      Doctrine\DBAL\Driver\PDO\Exception::("SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes")

  2   vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119
      Doctrine\DBAL\Driver\PDO\Exception::new()

  3   vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
      PDOException::("SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes")

  4   vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
      PDOStatement::execute()

  5   vendor/laravel/framework/src/Illuminate/Database/Connection.php:492
      Doctrine\DBAL\Driver\PDOStatement::execute()

  6   vendor/laravel/framework/src/Illuminate/Database/Connection.php:696
      Illuminate\Database\Connection::Illuminate\Database\{closure}()

  7   vendor/laravel/framework/src/Illuminate/Database/Connection.php:663
      Illuminate\Database\Connection::runQueryCallback()

  8   vendor/laravel/framework/src/Illuminate/Database/Connection.php:493
      Illuminate\Database\Connection::run()

  9   vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php:109
      Illuminate\Database\Connection::statement()

  10  vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:365
      Illuminate\Database\Schema\Blueprint::build()

  11  vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:212
      Illuminate\Database\Schema\Builder::build()

  12  vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
      Illuminate\Database\Schema\Builder::table()

  13  database/migrations/2020_12_14_091314_create_port_groups_table.php:24
      Illuminate\Support\Facades\Facade::__callStatic()

  14  vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:394
      CreatePortGroupsTable::up()

  15  vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:403
      Illuminate\Database\Migrations\Migrator::Illuminate\Database\Migrations\{closure}()

  16  vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:202
      Illuminate\Database\Migrations\Migrator::runMigration()

  17  vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:167
      Illuminate\Database\Migrations\Migrator::runUp()

  18  vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:112
      Illuminate\Database\Migrations\Migrator::runPending()

  19  vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:85
      Illuminate\Database\Migrations\Migrator::run()

  20  vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:585
      Illuminate\Database\Console\Migrations\MigrateCommand::Illuminate\Database\Console\Migrations\{closure}()

  21  vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:94
      Illuminate\Database\Migrations\Migrator::usingConnection()

  22  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
      Illuminate\Database\Console\Migrations\MigrateCommand::handle()

  23  vendor/laravel/framework/src/Illuminate/Container/Util.php:40
      Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()

  24  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
      Illuminate\Container\Util::unwrapIfClosure()

  25  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
      Illuminate\Container\BoundMethod::callBoundMethod()

  26  vendor/laravel/framework/src/Illuminate/Container/Container.php:653
      Illuminate\Container\BoundMethod::call()

  27  vendor/laravel/framework/src/Illuminate/Console/Command.php:136
      Illuminate\Container\Container::call()

  28  vendor/symfony/console/Command/Command.php:299
      Illuminate\Console\Command::execute()

  29  vendor/laravel/framework/src/Illuminate/Console/Command.php:121
      Symfony\Component\Console\Command\Command::run()

  30  vendor/symfony/console/Application.php:978
      Illuminate\Console\Command::run()

  31  vendor/symfony/console/Application.php:295
      Symfony\Component\Console\Application::doRunCommand()

  32  vendor/symfony/console/Application.php:167
      Symfony\Component\Console\Application::doRun()

  33  vendor/laravel/framework/src/Illuminate/Console/Application.php:94
      Symfony\Component\Console\Application::run()

  34  vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:129
      Illuminate\Console\Application::run()

  35  app/Console/Kernel.php:72
      Illuminate\Foundation\Console\Kernel::handle()

  36  lnms:40
      App\Console\Kernel::handle()

I hope someone can make more sense of it... before I do the wrong thing and just start fishing around for a solution again. 
~Thanks for any help or suggestions. 

### Output of ./validate.php

```txt
./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.10.0-85-gf4ee508f3
DB Schema | 2020_12_14_091314_create_port_group_port_table (199)
PHP       | 8.0.12
Python    | 3.8.10
MySQL     | 10.3.31-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.1.11
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[FAIL]  Your database is out of date!
        [FIX]:
        ./lnms migrate
[INFO]  Detected Python Wrapper
[FAIL]  We could not get memcached stats, it is possible that we cannot connect to your memcached server, please check
you have mail
```

### Anything in the logs that might be useful for us?

```txt
librenms.log has:
[2021-11-03 13:51:02] production.ERROR: Error when loading hook App\Plugins\ExamplePlugin\DeviceOverview of type App\Plugins\Hooks\DeviceOverviewHook for ExamplePlugin: Attempt to read property "plugin_active" on null
[2021-11-03 13:51:02] production.ERROR: Error when loading hook App\Plugins\ExamplePlugin\Menu of type App\Plugins\Hooks\MenuEntryHook for ExamplePlugin: Attempt to read property "plugin_active" on null
[2021-11-03 13:51:02] production.ERROR: Error when loading hook App\Plugins\ExamplePlugin\Page of type App\Plugins\Hooks\PageHook for ExamplePlugin: Attempt to read property "plugin_active" on null
[2021-11-03 13:51:02] production.ERROR: Error when loading hook App\Plugins\ExamplePlugin\PortTab of type App\Plugins\Hooks\PortTabHook for ExamplePlugin: Attempt to read property "plugin_active" on null
[2021-11-03 13:51:02] production.ERROR: Error when loading hook App\Plugins\ExamplePlugin\Settings of type App\Plugins\Hooks\SettingsHook for ExamplePlugin: Attempt to read property "plugin_active" on null
/opt/librenms/poller.php 760 2021-11-03 13:51:06 - 1 devices polled in 15.19 secs
/opt/librenms/poller.php 759 2021-11-03 13:51:06 - 1 devices polled in 15.17 secs

error_log had no relevant time stamped errors that pertain to anything I am seeing that has not been fixed. 

daily.log had this but I don't think it is applicable to the current error:

Fatal error: Uncaught Error: Class "App\Application" not found in /opt/librenms/bootstrap/app.php:14
Stack trace:
#0 /opt/librenms/LibreNMS/Util/Laravel.php(44): require_once()
#1 /opt/librenms/includes/init.php(92): LibreNMS\Util\Laravel::bootCli()
#2 /opt/librenms/daily.php(19): require('...')
#3 {main}
  thrown in /opt/librenms/bootstrap/app.php on line 14
Returned: 255
Caching PeeringDB data
PHP Fatal error:  Uncaught Error: Class "App\Application" not found in /opt/librenms/bootstrap/app.php:14
Stack trace:
#0 /opt/librenms/LibreNMS/Util/Laravel.php(44): require_once()
#1 /opt/librenms/includes/init.php(92): LibreNMS\Util\Laravel::bootCli()
#2 /opt/librenms/daily.php(19): require('...')
#3 {main}
  thrown in /opt/librenms/bootstrap/app.php on line 14

Fatal error: Uncaught Error: Class "App\Application" not found in /opt/librenms/bootstrap/app.php:14
Stack trace:
#0 /opt/librenms/LibreNMS/Util/Laravel.php(44): require_once()
#1 /opt/librenms/includes/init.php(92): LibreNMS\Util\Laravel::bootCli()
#2 /opt/librenms/daily.php(19): require('...')
#3 {main}
  thrown in /opt/librenms/bootstrap/app.php on line 14
Returned: 255
```

**Comment by Jellyfrog** [comment]
This has been posted a billion times before in the forum and is not a librenms problem per se. 
https://community.librenms.org/t/upgrade-to-version-21-x/16855/3
