### ISSUE TITLE
IPv6 cross connecting ?

### ISSUE THREAD

**Issue by Npeca75** [librenms/librenms#13481]
### The problem

Hi
when i looks at PORTS, every port which have ipv6 address is cross connected with device which is in totally different v6 subnet

for ex
fd00:1:1::101/64 is connected with fd00:3:254::206/64
i suspected first on LLDP but no, two device is 10 hops away

if i try do delete one by one addresses from DB / ipv6_addressess, the ports get back to normal, they are NOT cros connected anymore, which is OK

on IPv4, everything is fine

looks like IPv6 does not account prefix length ???

![lnms1](https://user-images.githubusercontent.com/59750439/140624380-314ca840-3474-4488-9867-c3aa658092c1.png)
![lnms2](https://user-images.githubusercontent.com/59750439/140624383-a71a3c15-ca98-4095-9477-f4bba8b180fb.png)
![lnms3](https://user-images.githubusercontent.com/59750439/140624385-1b2941e8-09c8-4e95-91e4-44dce54cd1b3.png)
![lnms4](https://user-images.githubusercontent.com/59750439/140624386-21a67b0a-0c67-4a3b-8d52-0f6b1a96dd12.png)

### Output of ./validate.php

```txt
$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.10.0-95-g1ff48018f
DB Schema | 2021_10_20_224207_increase_length_of_attrib_type_column (224)
PHP       | 7.4.23
Python    | 3.6.9
MySQL     | 5.7.35-0ubuntu0.18.04.1
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 2.1.11
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

**Comment by bakerds** [comment]
I don't see this with GUA -- is it an issue only with ULA?

**Comment by murrant** [comment]
Should APIPA and ULA should be ignored for detecting devices in the same subnet?

**Comment by bakerds** [comment]
APIPA and link-local should be ignored, but ULA should be treated just like GUA. If ULA are used correctly there shouldn’t be any overlap or reuse within a network, even a very large one.

**Comment by Npeca75** [comment]
> APIPA and link-local should be ignored, but ULA should be treated just like GUA

yes, exactly
it is out of question to use GUA for managing devices, 
Huge problem is that your GUA prefix might change, and faking 2000::/3 addresses inside MGMN network, only to stay "fixed" is  not a good approach.
Most devices already struggling with IPv6, some older switches does not have SLAAC, so GUA prefix changes will bring your MGMN down
from my point of view, ULA is is the way to go and should be treated like GUA
they are typically used as the equivalent of IPv4 private addresses; e.g., routed exclusively within an enterprise private network. 
The ULA prefix is fc00::/7. But the 8th most-significant-bit (MSB) determines which “half” of the allocation a prefix is being assigned from, fc00::/8 or fd00::/8.
According to the RFC 4193 “Unique Local IPv6 Unicast Addresses,” this bit indicates a locally assigned prefix when set to 1 and is undefined when set to 0. Thus, technically only prefixes from fd00::/8 should be defined and used.

so, YES
fd00::/8 is valid IPv6

**Comment by Npeca75** [comment]
I was right
on older LNMS everything worked fine
LibreNMS  | 1.70.1
![lnm1](https://user-images.githubusercontent.com/59750439/142989372-1cfa4db1-bc79-4bcf-87e9-69570001e7fc.png)
![lnm2](https://user-images.githubusercontent.com/59750439/142989376-90c6deeb-67d7-4594-b9b7-7177ed1b59cc.png)

vlan254 is separated from vlan1
