### ISSUE TITLE
PHP8 Compatibility in `includes/polling/applications/ntp-server.inc.php`

### ISSUE THREAD

**Issue by amanualgoldstein** [librenms/librenms#13504]
### The problem

I had previously upgraded an existing installation from PHP 7.4 -> PHP 8.0 and failed to notice for a while that polling was broken on _some_ hosts.

It appears that the ntp-server application script uses an undefined constant when initializing its data array. The use of undefined constants previously generated a warning, and since PHP 8.0 generates an error instead. 

```
diff --git a/includes/polling/applications/ntp-server.inc.php b/includes/polling/applications/ntp-server.inc.php
index 307d8f53d..17f23283a 100644
--- a/includes/polling/applications/ntp-server.inc.php
+++ b/includes/polling/applications/ntp-server.inc.php
@@ -16,7 +16,7 @@ try {
     $legacy = $e->getOutput();
 
     $ntp = [
-        data => [],
+        'data' => [],
     ];
 
     [$ntp['data']['stratum'], $ntp['data']['offset'], $ntp['data']['frequency'], $ntp['data']['jitter'],
```

### Output of ./validate.php

```txt
Not relevant
```

**Comment by murrant** [comment]
Send as a pull request to get the fix included in LibreNMS.  Browse to the file and click edit, make the change, click save and create pull request.
