### ISSUE TITLE
Feature request: Thru API add device with option to ignore all interfaces at first discovery

### ISSUE THREAD

**Issue by kivimartin** [librenms/librenms#1351]
Thru the API or CLI , when adding new devices having the option to ignore all interfaces on a device at first discovery and polls.

When you adding access switches using automation or bulk import observium will alert if interfaces are down, on access switches this is a normal state. 

So this option will make it easy:er to integrate librenms easy:er with other device registers.

**Comment by brillormen** [comment]
Great suggestion i'm also looking for this. :+1:

**Comment by f0o** [comment]
:+1:

**Comment by Rosiak** [comment]
This could be some device specific option, since ports are first added after disco.
Perhaps just a simple if statement in the code afterwards.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-thru-api-add-device-with-option-to-ignore-all-interfaces-at-first-discovery/893
