### ISSUE TITLE
RRD - Disk space where /opt/librenms/rrd is located is empty!!!

### ISSUE THREAD

**Issue by kevintdiep** [librenms/librenms#13516]
### The problem

I have noticed the graphs are missing from all devices this morning.  Here is my output from ./validate.php.
====================================
Component | Version
--------- | -------
LibreNMS  | 21.11.0-6-gbef021b15
DB Schema | 2021_11_12_123037_change_cpwVcID_to_unsignedInteger (225)
PHP       | 7.4.3
Python    | 3.8.10
MySQL     | 10.3.31-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.1.11
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[FAIL]  Disk space where /opt/librenms/rrd is located is empty!!!
[WARN]  Your RRD directory is owned by root, please consider changing over to user a non-root user
[WARN]  Your RRD directory is not set to 0775
	[FIX]: 
	chmod 775 /opt/librenms/rrd
[WARN]  Your local git contains modified files, this could prevent automatic updates.
	[FIX]: 
	You can fix this with ./scripts/github-remove
	Modified Files:
	 rrd/.gitignore

Please provide assistance to resolve this issue.

Thank you.

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.11.0-6-gbef021b15
DB Schema | 2021_11_12_123037_change_cpwVcID_to_unsignedInteger (225)
PHP       | 7.4.3
Python    | 3.8.10
MySQL     | 10.3.31-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.1.11
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[FAIL]  Disk space where /opt/librenms/rrd is located is empty!!!
[WARN]  Your RRD directory is owned by root, please consider changing over to user a non-root user
[WARN]  Your RRD directory is not set to 0775
	[FIX]: 
	chmod 775 /opt/librenms/rrd
[WARN]  Your local git contains modified files, this could prevent automatic updates.
	[FIX]: 
	You can fix this with ./scripts/github-remove
	Modified Files:
	 rrd/.gitignore
```

### What was the last working version of LibreNMS?

21.11.0-6-gbef021b15

**Comment by murrant** [comment]
`Your RRD directory is owned by root` looks like LibreNMS does not have permission to access your rrd directory.  For support requests, please ask elsewhere.
