### ISSUE TITLE
OSPF module failing on Mikrotik and Fortigate devices

### ISSUE THREAD

**Issue by alchemyx** [librenms/librenms#13532]
### The problem

Poller throws errors about OSPF module:

#### Load poller module ospf ####
 Processes: .1 Areas: .1 Ports:
In Ospf.php line 115:

  Too few arguments to function LibreNMS\Modules\Ospf::LibreNMS\Modules\{closure}(), 2 passed and exactly 3 expected

It happens for me on Mikrotik SwOS based devices and for somebody else on Fortigates (related topic https://community.librenms.org/t/minor-bug-found-in-poller-new-ospf-port-module/17462). Module can't be disabled in global settings but only on per-device basis. If it is disabled for specific device it works just fine.

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.11.0-15-g31c9d9c30
DB Schema | 2021_11_12_123037_change_cpwVcID_to_unsignedInteger (225)
PHP       | 7.4.3
Python    | 3.8.10
MySQL     | 10.3.31-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.1.12
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  Your local git contains modified files, this could prevent automatic updates.
	[FIX]:
	You can fix this with ./scripts/github-remove
	Modified Files:
	 html/js/jquery.gridster.min.js
	 includes/polling/ports/os/smartax.inc.php
```

### Anything in the logs that might be useful for us?

```txt
Nothing in logs.
```

**Comment by murrant** [comment]
@alchemyx check your librenms.log for `Too few arguments to function LibreNMS\Modules\Ospf::LibreNMS\Modules{closure}(), 2 passed and exactly 3 expected`

If that is the case, I need test data, can you snmpwalk `OSPF-MIB::ospfIfTable`

#13530

**Comment by alchemyx** [comment]
@murrant unfortunately grepping on that yelds no results, I only get it when manually running poller, for example:

`root@noc:/opt/librenms# sudo -u librenms ./poller.php  -h hostname
LibreNMS Poller
Starting polling run:

Hostname:   hostname
Device ID:   7
OS:          swos
 (mikrotik)


#### Load poller module core ####
Uptime:  1 year 112 days 11 hours 47 minutes 36 seconds

>> Runtime for poller module 'core': 6.0411 seconds with 58192 bytes
>> SNMP: [2/6.03s] MySQL: [1/0.03s] RRD: [1/0.00s]
#### Unload poller module core ####

Module [ unix-agent ] disabled globally.


#### Load poller module os ####
Generic :(
Location: Swinoujscie, Monte Cassino 10
Hardware:
OS Version:
OS Features:
Serial:

>> Runtime for poller module 'os': 0.0034 seconds with 107656 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.00s] RRD: [1/0.00s]
#### Unload poller module os ####


#### Load poller module availability ####
Availability:
1 day : 100%
7 days : 100%
30 days : 100%
365 days : 99.999%

>> Runtime for poller module 'availability': 0.0068 seconds with 12488 bytes
>> SNMP: [0/0.00s] MySQL: [10/0.04s] RRD: [5/0.00s]
#### Unload poller module availability ####


#### Load poller module ipmi ####

>> Runtime for poller module 'ipmi': 0.0009 seconds with 1488 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [1/0.00s]
#### Unload poller module ipmi ####


#### Load poller module sensors ####

>> Runtime for poller module 'sensors': 0.0008 seconds with 456 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [1/0.00s]
#### Unload poller module sensors ####


#### Load poller module processors ####

>> Runtime for poller module 'processors': 0.0018 seconds with 59056 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [1/0.00s]
#### Unload poller module processors ####


#### Load poller module mempools ####

>> Runtime for poller module 'mempools': 0.0020 seconds with 142832 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [1/0.00s]
#### Unload poller module mempools ####


#### Load poller module storage ####

>> Runtime for poller module 'storage': 0.0025 seconds with 904 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.02s] RRD: [1/0.00s]
#### Unload poller module storage ####

Module [ netstats ] disabled on host.

Module [ hr-mib ] disabled on host.

Module [ ucd-mib ] disabled on host.


#### Load poller module ipSystemStats ####


>> Runtime for poller module 'ipSystemStats': 0.0221 seconds with 1064 bytes
>> SNMP: [1/0.02s] MySQL: [0/0.00s] RRD: [1/0.00s]
#### Unload poller module ipSystemStats ####


#### Load poller module ports ####
Caching Oids: Full ports polling dot3StatsDuplexStatus
Port Port1: Port1 (1 / #287) VLAN =  Port1bps(0 bps/0 bps)bytes(0 B/0 B)pkts(0 pps/0 pps)
Port Port2: Port2 (2 / #288) VLAN =  Port2bps(67.69 Kbps/1.9 Mbps)bytes(1.98 MiB/55.54 MiB)pkts(130.58 pps/210.65 pps)
Port Port3: Port3 (3 / #289) VLAN =  Port3bps(0 bps/0 bps)bytes(0 B/0 B)pkts(0 pps/0 pps)
Port Port4: Port4 (4 / #290) VLAN =  Port4bps(3.68 Kbps/4.88 Kbps)bytes(110.04 KiB/146.08 KiB)pkts(3.49 pps/5.36 pps)
Port Port5: Port5 (5 / #291) VLAN =  Port5bps(0 bps/0 bps)bytes(0 B/0 B)pkts(0 pps/0 pps)
Port SFP: SFP (6 / #292) VLAN =  SFPbps(1.91 Mbps/76.16 Kbps)bytes(55.88 MiB/2.22 MiB)pkts(216.55 pps/134.65 pps)

>> Runtime for poller module 'ports': 0.2851 seconds with 56104 bytes
>> SNMP: [4/0.24s] MySQL: [15/0.30s] RRD: [7/0.00s]
#### Unload poller module ports ####


#### Load poller module customoid ####

>> Runtime for poller module 'customoid': 0.0007 seconds with 1320 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.00s] RRD: [1/0.00s]
#### Unload poller module customoid ####


#### Load poller module bgp-peers ####

>> Runtime for poller module 'bgp-peers': 0.0026 seconds with 14088 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [1/0.00s]
#### Unload poller module bgp-peers ####

Module [ junose-atm-vp ] disabled globally.

Module [ printer-supplies ] disabled globally.


#### Load poller module ucd-diskio ####

>> Runtime for poller module 'ucd-diskio': 0.0005 seconds with 816 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.00s] RRD: [1/0.00s]
#### Unload poller module ucd-diskio ####

Module [ wifi ] disabled globally.


#### Load poller module wireless ####

>> Runtime for poller module 'wireless': 0.0022 seconds with 103152 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [1/0.00s]
#### Unload poller module wireless ####


#### Load poller module ospf ####
 Processes: .1 Areas: .1 Ports:
In Ospf.php line 115:

  Too few arguments to function LibreNMS\Modules\Ospf::LibreNMS\Modules\{closure}(), 2 passed and exactly 3 expected
`

Result of snmpwalk:

`root@noc:/opt/librenms# snmpwalk -v1 -c XXX hostname OSPF-MIB::ospfIfTable
End of MIB`

**Comment by murrant** [comment]
@alchemyx ok, I updated #13530 to handle "End of MIB" can you test that PR?

**Comment by alchemyx** [comment]
I can confirm that that PR fixed it and now poller.php runs cleanly.

**Comment by murrant** [comment]
Awesome, thanks @alchemyx
