### ISSUE TITLE
Device group Pattern is scrambled on resave

### ISSUE THREAD

**Issue by Ftelf** [librenms/librenms#1355]
I have a custom device groups to logically group my devices according to a logical placement. The group is Description based. Until now I was able to add a new Attribute, but now, after resave. The Pattern is scrambled rendering the group non-working.

Previous pattern is working:
This lists all my devices which does not have been categorized
'%devices.purpose !~ "[AP Dejvyd]" && %devices.purpose !~ "[AP Stealth]" && %devices.purpose !~ "[AP Budik]" && %devices.purpose !~ "[AP Locki]" && %devices.purpose !~ "[AP Jarekluky]"'
http://fii.cz/qfnrw
http://fii.cz/agmgqpfu
http://fii.cz/zvwfgwm

Now I have new attribute
http://fii.cz/tptrvxz

After save:
http://fii.cz/mfkbbhbh
http://fii.cz/jyhqtzqn

It does not work, because there is extra whitespace added.

**Comment by laf** [comment]
@Ftelf 

Can you paste me the pattern from your db entry so I can replicate and fix this?

**Comment by Ftelf** [comment]
Have a look at the fii.cz links  "After save" Its a screenshot from the librenms and phpmyadmin after clicking save.
Anyway:

%devices.purpose !~ "[AP Dejvyd] " && %devices.purpose !~ "[AP Stealth] " && %devices.purpose !~ "[AP Budik] " && %devices.purpose !~ "[AP Locki] " && %devices.purpose !~ "[AP Jarekluky] " && %devices.purpose !~ "[AP Karel]"   

http://fii.cz/euvffmhf

**Comment by f0o** [comment]
That patterns transforms to me fine as:
```sql
SELECT
 DISTINCT(devices.device_id)
FROM
 devices
WHERE (
 devices.purpose NOT LIKE "[AP Dejvyd] "    &&
 devices.purpose NOT LIKE "[AP Stealth] "   &&
 devices.purpose NOT LIKE "[AP Budik] "     &&
 devices.purpose NOT LIKE "[AP Locki] "     &&
 devices.purpose NOT LIKE "[AP Jarekluky] " &&
 devices.purpose NOT LIKE "[AP Karel]"
)
```

**Comment by Ftelf** [comment]
This is the wrong pattern after the resave. There are extra whitespace added which invalided the whole pattern.
https://youtu.be/GFynX6s-h1g

**Comment by laf** [comment]
Thanks @Ftelf I can see what you mean about the white space. Please try this patch and report back:

```bash
diff --git a/html/forms/parse-device-group.inc.php b/html/forms/parse-device-group.inc.php
index 7009459..9ecd4e5 100644
--- a/html/forms/parse-device-group.inc.php
+++ b/html/forms/parse-device-group.inc.php
@@ -20,7 +20,7 @@ $group_id = $_POST['group_id'];

 if(is_numeric($group_id) && $group_id > 0) {
     $group = dbFetchRow("SELECT * FROM `device_groups` WHERE `id` = ? LIMIT 1",array($group_id));
-    $group_split = preg_split('/([a-zA-Z0-9_\-\.\=\%\<\>\ \"\'\!\~\(\)\*\/\@]+[&&\|\|]+)/',$group['pattern'], -1, PREG_SPLIT_DELIM_CAPTURE | PREG_SPLIT_NO_EMPTY);
+    $group_split = preg_split('/([a-zA-Z0-9_\-\.\=\%\<\>\ \"\'\!\~\(\)\*\/\@\[\]]+[&&\|\|]+)/',$group['pattern'], -1, PREG_SPLIT_DELIM_CAPTURE | PREG_SPLIT_NO_EMPTY);
     $count = count($group_split) - 1;
     $group_split[$count] = $group_split[$count].'  &&';
     $output = array('name'=>$group['name'],'desc'=>$group['desc'],'pattern'=>$group_split);
```

**Comment by Ftelf** [comment]
Seems all right now.

**Comment by laf** [comment]
Excellent, you will need to remove that patch by doing git checkout -- html/forms/parse-device-group.inc.php at some stage otherwise you won't be able to update.
