### ISSUE TITLE
oxidized skip groups bug

### ISSUE THREAD

**Issue by galbets** [librenms/librenms#13568]
### The problem

Hi!

We are trying to exclude some groups of oxidized process but it's not working. We have set the configuration as following:

![image](https://user-images.githubusercontent.com/95028210/143433389-c345bb5f-52b0-429a-a599-aa8c748fd411.png)

We have also tryied using config.php with the same results.

$config['oxidized']['enabled'] = true;
$config['oxidized']['url'] = 'http://127.0.0.1:8888';
$config['oxidized']['features']['versioning'] = true;
$config['oxidized']['group_support'] = false;
$config['oxidized']['default_group'] = 'routeros';
$config['oxidized']['reload_nodes'] = false;
$config['oxidized']['maps']['group']['hostname'][] = array('match' => '10.140.200.100', 'group' => 'routeros');
$config['oxidized']['maps']['group']['os'][] = array('match' => 'routeros', 'group' => 'routeros');
$config['oxidized']['maps']['group']['os'][] = array('match' => 'ciscosmb', 'group' => 'ciscosmb');
$config['oxidized']['maps']['group']['os'][] = array('match' => 'airos', 'group' => 'airos');
$config['oxidized']['maps']['group']['os'][] = array('match' => 'ubnt_pi', 'group' => 'airos');
$config['oxidized']['maps']['group']['os'][] = array('match' => 'edgeswitch', 'group' => 'edgeswitch');
$config['oxidized']['maps']['group']['os'][] = array('match' => 'ios', 'group' => 'ios');

$config['oxidized']['ignore_types'] = array('server','power');
$config['oxidized']['ignore_os'] = array('Ping only','linux','windows','ping','mimosa','hpe-ilo','generic','hpe-msa');

The errors of database in validate.php are caused because we added an extra table to add own funcionalities but that doesn't affect on devices table.

Thanks

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.8.0-41-g0a76ca444
DB Schema | 2021_08_26_093522_config_value_to_medium_text (219)
PHP       | 7.3.29-1~deb10u1
Python    | 3.7.3
MySQL     | 10.3.29-MariaDB-0+deb10u1
RRDTool   | 1.7.1
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 2.1.12
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[FAIL]  Database: incorrect column (notifications/datetime)
[FAIL]  Database: incorrect column (users/created_at)
[FAIL]  Database: extra table (onts_online)
[FAIL]  We have detected that your database schema may be wrong, please report the following to us on Discord (https://t.libren.ms/discord) or the community site (https://t.libren.ms/5gscd):
	[FIX]: 
	Run the following SQL statements to fix.
	SQL Statements:
	 SET TIME_ZONE='+00:00';
	 ALTER TABLE `notifications` CHANGE `datetime` `datetime` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00' ;
	 ALTER TABLE `users` CHANGE `created_at` `created_at` timestamp NOT NULL DEFAULT '1970-01-02 00:00:01' ;
	 DROP TABLE `onts_online`;
[FAIL]  MySQL column collation is wrong: 
	[FIX]: 
	Check https://community.librenms.org/t/new-default-database-charset-collation/14956 for info on how to fix.
	Columns:
	 onts_online: onts_down   utf8mb4   utf8mb4_bin
[WARN]  Your install is over 24 hours out of date, last update: Thu, 09 Sep 2021 00:45:58 +0000
	[FIX]: 
	Make sure your daily.sh cron is running and run ./daily.sh by hand to see if there are any errors.
[WARN]  Your local git contains modified files, this could prevent automatic updates.
	[FIX]: 
	You can fix this with ./scripts/github-remove
	Modified Files:
	 LibreNMS/Alert/Transport/Discord.php
	 misc/config_definitions.json
	 rrd/.gitignore
[FAIL]  We have found some files that are owned by a different user than 'librenms', this will stop you updating automatically and / or rrd files being updated causing graphs to fail.
	[FIX]: 
	sudo chown -R librenms:librenms /opt/librenms
	sudo setfacl -d -m g::rwx /opt/librenms/rrd /opt/librenms/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
	sudo chmod -R ug=rwX /opt/librenms/rrd /opt/librenms/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
	Files:
	 /opt/librenms/database/migrations/2021_06_28_121613_update_onts_online_table.php
```

### What was the last working version of LibreNMS?

21.8.0

**Comment by murrant** [comment]
Those oxidized groups do not exist in your config.

You are confusing Device Groups and Oxidized Groups.
