### ISSUE TITLE
Synology 412+ on DSM version 5

### ISSUE THREAD

**Issue by arnoldthebat** [librenms/librenms#1358]
Hi All

The above device fails to get detected properly with the current codebase as of 26th June.

Its a simple fix as per below in includes/discovery/os/linux.inc.php

// Check for Synology DSM
      //$hrSystemInitialLoadParameters = trim(snmp_get($device, "hrSystemInitialLoadParameters.0", "-Osqnv"));

      //if (strpos($hrSystemInitialLoadParameters, "syno_hw_version") !== FALSE) { $os = "dsm"; }
      if (is_numeric(snmp_get($device, "systemStatus.0", "-Osqnv", "SYNOLOGY-SYSTEM-MIB"))) { $os = "dsm"; }

I would do this properly in GIT but you guys would sort it far faster (and may catch additional logic requirements!)

BTW, syno_hw_version does exist in the MIB string but for whatever reason is being ignored on the original code..

**Comment by mikrogroove** [comment]
Mine seems to fail at 

 `$hrSystemInitialLoadParameters = trim(snmp_get($device, "hrSystemInitialLoadParameters.0", "-Osqnv"));`

with

`hrSystemInitialLoadParameters.0: Unknown Object Identifier (Sub-id not found: (top) -> hrSystemInitialLoadParameters)`

**Comment by arnoldthebat** [comment]
Im wondering wither its a simple as its not building in HOST-RESOURCES-MIB::hrSystemInitialLoadParameters.0 for the polling...

Ill go and test later today..

**Comment by laf** [comment]
Merged in #1360

**Comment by mikrogroove** [comment]
Many thanks for this update - I can confirm that it fixed detection of my DS214+ and I can now see the system temperatures. Unfortunately all the extra information means polling now takes ~15 seconds, but I'll figure out how to pare things down later.
