### ISSUE TITLE
Oxidized plugin map rule dropdown missing "hardware"

### ISSUE THREAD

**Issue by frank42hh** [librenms/librenms#13599]
### The problem

Under `/settings/external/oxidized` there's the possibility to create map rules. New map rule supports a source dropdown containing hostname, os, type and sysOBJECTID. The dropdown item "hardware" is missing here, even though the commandline client does support it.
Example:
lnms config:set oxidized.maps.group.hardware.+ '{"regex": "/1820 24G/", "value": "nobackup"}'

![Screenshot 2021-12-06 113235](https://user-images.githubusercontent.com/17932878/144830997-b5178856-7462-493e-bde3-fcd0211c0641.png)

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.11.0-66-g528d8e55b
DB Schema | 2021_11_17_105321_device_add_display_field (226)
PHP       | 7.3.31-1~deb10u1
Python    | 3.7.3
MySQL     | 10.3.31-MariaDB-0+deb10u1
RRDTool   | 1.7.1
SNMP      | 5.7.3
====================================

[OK]    Composer Version: 2.1.14
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

### What was the last working version of LibreNMS?

21.11.0

### Anything in the logs that might be useful for us?

```txt
Simple frontend problem, nothing in logs for that.
```

**Comment by martinberg** [comment]
I believe @Negatifff made a little error when he pushed his code and wrote `hostname` instead of `hardware`.
Unfortunately I don't seem to be able to make my own PR because I can't figure out how to make my changes appear in the webui. 
It should be as simple to edit `resources/js/components/SettingOxidizedMaps.vue` due to all the underlying code already has the parameters needed. 
If somebody decides to fix this it would be great if you could add support for the other types that just doesn't have a option in the webui, ie `sysName, sysDescr, location, ip`.

https://github.com/librenms/librenms/blob/a0464208887ce42b027ebb2fe462a09c0ba58b50/resources/js/components/SettingOxidizedMaps.vue#L53-L64

**Comment by Negatifff** [comment]
yes, indeed, it looks like I pointed to hostname instead of hardware. I will try to fix the code if I remember how to do it correctly - for a beginner there is a rather complicated sequence of actions;)

**Comment by martinberg** [comment]
> yes, indeed, it looks like I pointed to hostname instead of hardware. I will try to fix the code if I remember how to do it correctly - for a beginner there is a rather complicated sequence of actions;)

This should work. Although I believe `type` isn't used for anything. Maybe @murrant can confirm this?
```
<div class="form-group"> 
     <label for="source" class="col-sm-4 control-label">Source</label> 
     <div class="col-sm-8"> 
         <select class="form-control" id="source" v-model="mapModalSource"> 
             <option value="hostname">hostname</option>
             <option value="os">os</option>
             <option value="type">type</option>
             <option value="hardware">hardware</option>
             <option value="sysObjectID">sysObjectID</option>
             <option value="sysName">sysName</option>
             <option value="sysDescr">sysDescr</option>
             <option value="location">location</option>
             <option value="ip">ip</option>
         </select> 
     </div> 
</div> 
```
     </div> 
</div> 
```

**Comment by Negatifff** [comment]
> This should work. Although I believe `type` isn't used for anything. Maybe @murrant can confirm this?

the difficulty is not in the code, but in the assembly. As far as I remember, there are features of the JS assembly - I'll try to remember.

**Comment by martinberg** [comment]
> > This should work. Although I believe `type` isn't used for anything. Maybe @murrant can confirm this?
> 
> the difficulty is not in the code, but in the assembly. As far as I remember, there are features of the JS assembly - I'll try to remember.

I got my stuff together and made a PR #13604
