### ISSUE TITLE
Sudden Permission error

### ISSUE THREAD

**Issue by tpelado** [librenms/librenms#13605]
### The problem

Our librenms instance started throwing a permission denied error this morning.

We aren't aware of any modification made to the machine.

While using the specified commands resolved it, we don't know what caused the issue in the first place.

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/25641016/145198378-d735350c-d3be-4d89-9245-c16a40342695.png)

Sorry if this isn't clear. This isn't urgent as we've already resolved the issue, but this is more of a "hey this happened, just letting you know".

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS | 21.11.0-69-ga04642088
DB Schema | 2021_11_29_165436_improve_ports_search_index (229)
PHP | 7.4.3
Python | 3.8.10
MySQL | 10.3.32-MariaDB-0ubuntu0.20.04.1
RRDTool | 1.7.2
SNMP | 5.8
====================================



[OK] Composer Version: 2.1.14
[OK] Dependencies up-to-date.
[OK] Database connection successful
[OK] Database schema correct
```

### Anything in the logs that might be useful for us?

```txt
production.ERROR: file_put_contents(/opt/librenms/storage/framework/sessions/SecSo5eZcxeq4OSYmanQbzMXxii7mRANDaMMNaPh): failed to open stream: Permissio
n denied {"exception":"[object] (ErrorException(code: 0): file_put_contents(/opt/librenms/storage/framework/sessions/SecSo5eZcxeq4OSYmanQbzMXxii7mRANDaMMNaPh): failed to open stream: Perm
ission denied at /opt/librenms/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:187)"}
```
```

**Comment by tpelado** [comment]
Another note on that, is that librenms worked fine if you had it in your browser cache, resulting in a weird situation with users able to access it as usual, while others encountered the error page shown above.

**Comment by murrant** [comment]
LibreNMS can't break this itself.  It can only be something a user did.  Just run the commands to fix it.
