### ISSUE TITLE
Settings page is not working.

### ISSUE THREAD

**Issue by ngvirus** [librenms/librenms#13610]
### The problem

Settings page doesn't load.

### Output of ./validate.php

```txt
$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.11.0-72-g9e6590104
DB Schema | 2021_11_29_165436_improve_ports_search_index (229)
PHP       | 7.3.20
Python    | 3.6.8
MySQL     | 10.3.28-MariaDB
RRDTool   | 1.7.0
SNMP      | 5.8
====================================

[OK]    Composer Version: 2.1.14
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

### What was the last working version of LibreNMS?

I just tested with 21.11.0 and it works properly (no changes to db, just the files)

### Anything in the logs that might be useful for us?

Here's what i see in the chrome console.
![image](https://user-images.githubusercontent.com/5470026/145569199-f95fa95c-13c2-4d63-b6bf-0a7a950f4ac6.png)
Same thing in private window with no extensions. Same goes for firefox:
![image](https://user-images.githubusercontent.com/5470026/145569392-c7e31b93-1cd1-4636-94a7-b9cb697499da.png)

**Comment by TurnpointDesigns** [comment]
Same issue for me, after it upgraded to
21.11.0-72-g9e6590104
