### ISSUE TITLE
Dashboard tiles aren't locked on touch devices

### ISSUE THREAD

**Issue by tim427** [librenms/librenms#13611]
### The problem

Like stated in this Pull-Request: https://github.com/librenms/librenms/pull/2042

```
By default lock all tiles
Only allow moving/resizing if in Edit mode
```

This behaviour is true for normal browsers, controlled by a pointing device. When approaching the dashboard with a mobile device, with Edit mode off, I'm still able to move tiles.

This results in accidentally moving tiles on the dashboard, while scrolling on a mobile device.

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.11.0-72-g9e65901
DB Schema | 2021_11_29_165436_improve_ports_search_index (229)
PHP       | 7.4.26
Python    | 3.6.8
MySQL     | 5.7.36
RRDTool   | 1.4.8
SNMP      | 5.7.2
====================================

[OK]    Composer Version: 2.1.14
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

### Anything in the logs that might be useful for us?

_No response_ #

**Comment by murrant** [comment]
Was able to reproduce this.  It is a bug in the upstream js library, which is no longer in development.  Last release, 2016.

**Comment by tim427** [comment]
I found something; when the browser/window is slightly resized; Gridster becomes active again and therefore "losing" the disabled state.

I'm currently debugging why/when this happens.
