### ISSUE TITLE
Brocade VDX NOS support

### ISSUE THREAD

**Issue by infernix** [librenms/librenms#1361]
This appears to be missing and VDX switches are detected as servers. Most things seem to work fine but the interface names show up as however they are set in their description. The original port name does not appear in snmpwalk output.

    SNMPv2-MIB::sysDescr.0  Brocade VDX Switch.
    SNMPv2-MIB::sysObjectID.0 .1.3.6.1.4.1.1588.2.2.1.1.1.5
    ENTITY-MIB::entPhysicalMfgName.1
    .1.3.6.1.4.1.674.10895.3000.1.2.100.1.0  No Such Object available on this agent at this OID
    .1.3.6.1.4.1.39165.1.6.0 No Such Object available on this agent at this OID

    sysObjectID.0 SNMPv2-SMI::enterprises.1588.2.2.1.1.1.5

**Comment by infernix** [comment]
Actually it does show up. Here's one 10g example:

    iso.3.6.1.2.1.2.2.1.1.405995536 = INTEGER: 405995536
    iso.3.6.1.2.1.2.2.1.2.405995536 = STRING: "Core: foo to bar"
    iso.3.6.1.2.1.2.2.1.3.405995536 = INTEGER: 6
    iso.3.6.1.2.1.2.2.1.4.405995536 = INTEGER: 2500
    iso.3.6.1.2.1.2.2.1.5.405995536 = Gauge32: 1000000000
    iso.3.6.1.2.1.2.2.1.6.405995536 = Hex-STRING: 00 05 33 A7 E5 94 
    iso.3.6.1.2.1.2.2.1.7.405995536 = INTEGER: 1
    iso.3.6.1.2.1.2.2.1.8.405995536 = INTEGER: 1
    iso.3.6.1.2.1.2.2.1.9.405995536 = Timeticks: (2432167608) 281 days, 12:01:16.08
    iso.3.6.1.2.1.2.2.1.10.405995536 = Counter32: 1039139192
    iso.3.6.1.2.1.2.2.1.11.405995536 = Counter32: 1850376790
    iso.3.6.1.2.1.2.2.1.12.405995536 = Counter32: 3458081644
    iso.3.6.1.2.1.2.2.1.13.405995536 = Counter32: 3389
    iso.3.6.1.2.1.2.2.1.14.405995536 = Counter32: 0
    iso.3.6.1.2.1.2.2.1.15.405995536 = Counter32: 0
    iso.3.6.1.2.1.2.2.1.16.405995536 = Counter32: 3445078483
    iso.3.6.1.2.1.2.2.1.17.405995536 = Counter32: 1281257129
    iso.3.6.1.2.1.2.2.1.18.405995536 = Counter32: 3303822059
    iso.3.6.1.2.1.2.2.1.19.405995536 = Counter32: 71
    iso.3.6.1.2.1.2.2.1.20.405995536 = Counter32: 0
    iso.3.6.1.2.1.2.2.1.21.405995536 = Gauge32: 0
    iso.3.6.1.2.1.2.2.1.22.405995536 = OID: ccitt.0
    iso.3.6.1.2.1.31.1.1.1.1.405995536 = STRING: "TenGigabitEthernet 0/51"
    iso.3.6.1.2.1.31.1.1.1.2.405995536 = Counter32: 2114980771
    iso.3.6.1.2.1.31.1.1.1.3.405995536 = Counter32: 1343153849
    iso.3.6.1.2.1.31.1.1.1.4.405995536 = Counter32: 1505530402
    iso.3.6.1.2.1.31.1.1.1.5.405995536 = Counter32: 1798322688

**Comment by laf** [comment]
@infernix Not sure if you're saying it's fixed or if it needs something doing to it, can you screenshot what you are seeing?

**Comment by infernix** [comment]
Yes, this needs at least following fix:

- Switch isn't detected as Brocade Switch, no checking for ```Brocade VDX Switch``` in any of the discover probes so ends up as unknown device and as type ```Server```

And maybe the following as well:

- Interfaces are being given the name ```Core: foo to bar``` with no description, as can be seen here: http://pastebin.ca/3040438 and that's probably because ifAlias=NULL

**Comment by laf** [comment]
PR done for basic support @infernix 

If you have a full snmpwalk from one of these units so we can look at adding hardware / serial / version info that would be good.

**Comment by infernix** [comment]
Device discovery is now good, but the interface description is still empty. This makes so that any Core: or Transit: descriptions do not show up at all on the respective pages.

I deleted and readded a brocade and after a discovery and poller run, here's the mysql data for a port: https://bpaste.net/show/c2a10693d3cb - ```port_descr_*``` are all ```NULL``` which I think is why they don't show up.

Also, here's a full snmpwalk dump: https://bpaste.net/show/0f8b5e86f6e5
