### ISSUE TITLE
Temperature and Voltage sensors are not detected anymore after manual rescan of device.

### ISSUE THREAD

**Issue by Fehler12** [librenms/librenms#13623]
### The problem

When I rescan a device from CLI the values for temperature, voltage and percent are not detected anymore.

Steps to reproduce:
1.) add a device via web gui with SNMP.
2.) wait until the device is fully detectet
3.) rescan device from command line with php discovery.php -h XX -d (XX is the device id)
![image](https://user-images.githubusercontent.com/53938045/146240542-2f1e2c3f-dee4-4063-a09a-45baccd491cc.png)

Steps to resolve the issue: delete the device and rediscover it.

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.11.0-76-ge24862545
DB Schema | 2021_25_01_0129_isis_adjacencies_nullable (229)
PHP       | 7.4.3
Python    | 3.8.10
MySQL     | 10.3.32-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | 5.8
====================================

[OK]    Composer Version: 2.1.14
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  Your install is over 24 hours out of date, last update: Mon, 13 Dec 2021 14:30:57 +0000
        [FIX]:
        Make sure your daily.sh cron is running and run ./daily.sh by hand to see if there are any errors.
```

**Comment by murrant** [comment]
They are still detected, but discovery doesn't set the actual value...  only poller does.  When poller runs again, it will set the correct values.   This is kind of intended, although there are ways to make it set the values during discovery.

**Comment by Fehler12** [comment]
Hi,

but that would mean that the values should be present after the next poller run? For some reason the values keep zero, even after several days. That‘s what I would like to change.

**Comment by Fehler12** [comment]
Update: it seems to me that the poller itself is not able to gather the sensors correctly:

`./poller.php -h 43
LibreNMS Poller
Starting polling run:

Hostname:    10.2.30.4
Device ID:   43
OS:          lenovoXClarityIMPI



#### Load poller module core ####
Uptime:  2 days 22 hours 4 minutes 52 seconds

>> Runtime for poller module 'core': 0.3395 seconds with 57000 bytes
>> SNMP: [2/0.33s] MySQL: [1/0.07s] RRD: [1/0.00s]
#### Unload poller module core ####

Module [ unix-agent ] disabled globally.


#### Load poller module os ####
Generic :(
Location: DTM
Hardware: ThinkSystem SR250
OS Version: TEI3C0N 4.83
OS Features:
Serial: S4AVL151

>> Runtime for poller module 'os': 0.0029 seconds with 108064 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.00s] RRD: [1/0.00s]
#### Unload poller module os ####


#### Load poller module availability ####
Availability:
1 day : 100%
7 days : 100%
30 days : 100%
365 days : 100%

>> Runtime for poller module 'availability': 0.0064 seconds with 12336 bytes
>> SNMP: [0/0.00s] MySQL: [10/0.04s] RRD: [5/0.00s]
#### Unload poller module availability ####


#### Load poller module ipmi ####

>> Runtime for poller module 'ipmi': 0.0008 seconds with 1488 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.00s] RRD: [1/0.00s]
#### Unload poller module ipmi ####


#### Load poller module sensors ####
Checking (snmp) percent Fan 1 Tach...
Checking (snmp) percent Fan 2 Tach...
Checking (snmp) percent Fan 3 Tach...
Checking (snmp) percent Fan 4 Tach...
0
0
0
0
Checking (snmp) state Overall System Status...
Checking (snmp) state Power status...
255 #
255 #
Checking (snmp) temperature CPU Temp...
Checking (snmp) temperature CPU DTS...
Checking (snmp) temperature Ambient Temp...
Checking (snmp) temperature Exhaust Temp...
0 C
0 C
0 C
0 C
Checking (snmp) voltage CMOS Battery...
Checking (snmp) voltage SysBrd 3.3V...
Checking (snmp) voltage SysBrd 5V...
Checking (snmp) voltage SysBrd 12V...
0 V
0 V
0 V
0 V

>> Runtime for poller module 'sensors': 0.2841 seconds with 12208 bytes
>> SNMP: [4/0.28s] MySQL: [5/0.02s] RRD: [15/0.00s]
#### Unload poller module sensors ####


#### Load poller module processors ####
Processor: 35%
Processor: 34%

>> Runtime for poller module 'processors': 0.0763 seconds with 125312 bytes
>> SNMP: [1/0.06s] MySQL: [3/0.10s] RRD: [3/0.00s]
#### Unload poller module processors ####


#### Load poller module mempools ####
hrstorage [system]: Physical memory: 56%  259.53 MiB / 464.11 MiB
hrstorage [virtual]: Virtual memory: 83%  386.68 MiB / 464.11 MiB
hrstorage [buffers]: Memory buffers: 4%  16.33 MiB / 464.11 MiB
hrstorage [cached]: Cached memory: 24%  110.82 MiB / 464.11 MiB
hrstorage [shared]: Shared memory: 1%  6.34 MiB / 464.11 MiB

>> Runtime for poller module 'mempools': 0.0891 seconds with 98328 bytes
>> SNMP: [1/0.06s] MySQL: [5/0.25s] RRD: [6/0.00s]
#### Unload poller module mempools ####


#### Load poller module storage ####

>> Runtime for poller module 'storage': 0.0008 seconds with 856 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.00s] RRD: [1/0.00s]
#### Unload poller module storage ####


#### Load poller module netstats ####
icmp ip ip_forward snmp udp tcp

>> Runtime for poller module 'netstats': 0.3803 seconds with 23688 bytes
>> SNMP: [6/0.38s] MySQL: [0/0.00s] RRD: [6/0.00s]
#### Unload poller module netstats ####


#### Load poller module hr-mib ####
 Processes Users

>> Runtime for poller module 'hr-mib': 0.1832 seconds with 27656 bytes
>> SNMP: [1/0.18s] MySQL: [1/0.01s] RRD: [3/0.00s]
#### Unload poller module hr-mib ####


#### Load poller module ucd-mib ####

>> Runtime for poller module 'ucd-mib': 0.1541 seconds with 3232 bytes
>> SNMP: [2/0.15s] MySQL: [0/0.00s] RRD: [19/0.00s]
#### Unload poller module ucd-mib ####


#### Load poller module ipSystemStats ####
ipv4 ipv6

>> Runtime for poller module 'ipSystemStats': 0.1869 seconds with 16096 bytes
>> SNMP: [1/0.19s] MySQL: [0/0.00s] RRD: [3/0.00s]
#### Unload poller module ipSystemStats ####


#### Load poller module ports ####
Caching Oids: Full ports polling ifDescr ifAdminStatus ifOperStatus ifLastChange                                                                              ifType ifPhysAddress ifMtu ifInErrors ifOutErrors ifInDiscards ifOutDiscards do                                                                             t3StatsDuplexStatus
Port lo: lo (1 / #803) VLAN =  lobps(1.23 Kbps/1.23 Kbps)bytes(15.91 KiB/15.91 K                                                                             iB)pkts(1.09 pps/1.09 pps)
Port eth0: eth0 (2 / #804) VLAN =  eth0bps(100 bps/100 bps)bytes(1.29 KiB/1.29 K                                                                             iB)pkts(0.21 pps/0.21 pps)
Port eth1: eth1 (3 / #805) VLAN =  eth1bps(1.09 Kbps/1.35 Kbps)bytes(14.03 KiB/1                                                                             7.49 KiB)pkts(1.12 pps/0.57 pps)
Port sit0: sit0 (4 / #806) VLAN =  sit0
Port usb0: usb0 (5 / #807) VLAN =  usb0bps(0 bps/323 bps)bytes(0 B/4.18 KiB)pkts                                                                             (0 pps/0.31 pps)

>> Runtime for poller module 'ports': 1.2135 seconds with 37480 bytes
>> SNMP: [14/1.17s] MySQL: [12/0.29s] RRD: [5/0.00s]
#### Unload poller module ports ####


#### Load poller module customoid ####

>> Runtime for poller module 'customoid': 0.0006 seconds with 1320 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.00s] RRD: [1/0.00s]
#### Unload poller module customoid ####


#### Load poller module bgp-peers ####

>> Runtime for poller module 'bgp-peers': 0.0019 seconds with 14024 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.00s] RRD: [1/0.00s]
#### Unload poller module bgp-peers ####

Module [ junose-atm-vp ] disabled globally.

Module [ printer-supplies ] disabled globally.


#### Load poller module ucd-diskio ####

>> Runtime for poller module 'ucd-diskio': 0.0004 seconds with 816 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.00s] RRD: [1/0.00s]
#### Unload poller module ucd-diskio ####

Module [ wifi ] disabled globally.


#### Load poller module wireless ####

>> Runtime for poller module 'wireless': 0.0014 seconds with 103152 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.00s] RRD: [1/0.00s]
#### Unload poller module wireless ####


#### Load poller module ospf ####
 Processes: 0
>> Runtime for poller module 'ospf': 0.0785 seconds with 98864 bytes
>> SNMP: [1/0.07s] MySQL: [2/0.02s] RRD: [1/0.00s]
#### Unload poller module ospf ####

Module [ isis ] disabled globally.

Module [ cisco-ipsec-flow-monitor ] disabled globally.

Module [ cisco-remote-access-monitor ] disabled globally.

Module [ cisco-cef ] disabled globally.

Module [ slas ] disabled globally.

Module [ cisco-mac-accounting ] disabled globally.

Module [ cipsec-tunnels ] disabled globally.

Module [ cisco-ace-loadbalancer ] disabled globally.

Module [ cisco-ace-serverfarms ] disabled globally.

Module [ cisco-asa-firewall ] disabled globally.

Module [ cisco-voice ] disabled globally.

Module [ cisco-cbqos ] disabled globally.

Module [ cisco-otv ] disabled globally.

Module [ cisco-qfp ] disabled globally.

Module [ cisco-vpdn ] disabled globally.

Module [ nac ] disabled globally.

Module [ netscaler-vsvr ] disabled globally.

Module [ aruba-controller ] disabled globally.


#### Load poller module entity-physical ####

>> Runtime for poller module 'entity-physical': 0.0002 seconds with 520 bytes
>> SNMP: [0/0.00s] MySQL: [0/0.00s] RRD: [1/0.00s]
#### Unload poller module entity-physical ####

Module [ entity-state ] disabled globally.


#### Load poller module applications ####

>> Runtime for poller module 'applications': 0.0006 seconds with 464 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.00s] RRD: [1/0.00s]
#### Unload poller module applications ####

Module [ mib ] disabled globally.


#### Load poller module stp ####


>> Runtime for poller module 'stp': 0.0670 seconds with 3504 bytes
>> SNMP: [1/0.07s] MySQL: [1/0.00s] RRD: [1/0.00s]
#### Unload poller module stp ####


#### Load poller module ntp ####

>> Runtime for poller module 'ntp': 0.0002 seconds with 400 bytes
>> SNMP: [0/0.00s] MySQL: [0/0.00s] RRD: [1/0.00s]
#### Unload poller module ntp ####

Module [ loadbalancers ] disabled globally.

Module [ mef ] disabled globally.


#### Load poller module mpls ####

>> Runtime for poller module 'mpls': 0.0006 seconds with 23984 bytes
>> SNMP: [0/0.00s] MySQL: [0/0.00s] RRD: [1/0.00s]
#### Unload poller module mpls ####

Enabling graphs:

Polled in 4.203 seconds
### Start Device Groups ###
### End Device Groups, runtime: 0.0065s ###

#### Start Alerts ####
Rule #1 (Devices up/down):
Status: NOCHG
Rule #2 (Sensor over limit - Check Device Health Settings):
Status: SKIP
#### End Alerts ####

SNMP [35/3.00s]: Snmpget[18/1.48s] Snmpwalk[17/1.52s]
SQL [69/1.06s]: Select[44/0.24s] Insert[1/0.04s] Update[23/0.77s] Delete[1/0.01s                                                                             ]
RRD [82/0.01s]: Update[82/0.01s]
`

SNMP-Walk gives me the correct values.

**Comment by murrant** [comment]
Check the values returned by the device... You can see those if you run the poller with -d

**Comment by Fehler12** [comment]
Found the issue. A wrong SNMP-Table was referenced. The discovery.php script was somehow able to find the values, the poller.php not. Fix is included in https://github.com/librenms/librenms/pull/13617

**Comment by murrant** [comment]
```
lenovoXClarityIMPI.yaml does not validate. Violations:
[modules.sensors.voltage.data[0]] The property state_name is not defined and the definition does not allow additional properties
[modules.sensors.temperature.data[0].skip_values] String value found, but a number is required
[modules.sensors.temperature.data[0].skip_values] String value found, but an array is required
[modules.sensors.temperature.data[0].skip_values] Failed to match at least one schema
[modules.sensors.temperature.data[0]] The property state_name is not defined and the definition does not allow additional properties
```

Need to fix all those violations of the schema.  There is also a small chance the schema is wrong, but it doesn't look like it in this case.
