### ISSUE TITLE
Overall Traffic Graph not showing after upgrade

### ISSUE THREAD

**Issue by rokkhan** [librenms/librenms#13638]
### The problem

Hello,

I have just updated our librenms server to the latest available version and since the update I have some devices where overall traffic graph is empty. 

![imagen](https://user-images.githubusercontent.com/22644111/147578320-e1a529dc-2f36-42f7-81ed-7fbce030b5a1.png)

If I clink on "Ports" menu to see the graph of each indiviviual interface, the graphs are showing correctly only the overall graph is empty. 
Does not seem to be related to device because I have a pair of Paloalto firewalls of same hardware an software version and one is showing the overall graph without any issue.

![imagen](https://user-images.githubusercontent.com/22644111/147578477-aa1f71cf-00a1-4257-996c-0f89a7fa363d.png)

### Output of ./validate.php

```txt
[librenms@XXXXXXXXX~]$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.12.0-4-g4b64d33
DB Schema | 2021_25_01_0129_isis_adjacencies_nullable (229)
PHP       | 7.3.33
Python    | 3.6.8
MySQL     | 10.5.13-MariaDB
RRDTool   | 1.4.8
SNMP      | 5.7.2
====================================

[OK]    Composer Version: 2.2.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]:
        You can fix this with ./scripts/github-remove
        Modified Files:
         bootstrap/cache/.gitignore
         logs/.gitignore
         rrd/.gitignore
         storage/app/.gitignore
         storage/app/public/.gitignore
         storage/framework/sessions/.gitignore
         storage/framework/testing/.gitignore
         storage/framework/views/.gitignore
         storage/logs/.gitignore
```

### What was the last working version of LibreNMS?

21.9.0

**Comment by laf** [comment]
Works for me on 21.12.0

<img width="877" alt="image" src="https://user-images.githubusercontent.com/3941142/147607456-60fdcd25-0324-48fb-b51d-af5453ca17be.png">

Try clicking the empty graph, then on the next page click show rrd command. Try copy/pasting that command in on the CLI and see what you get.

**Comment by rokkhan** [comment]
Did you mean this?
![imagen](https://user-images.githubusercontent.com/22644111/147608402-2d1ff46a-87d2-4bf7-8958-7130a8076e07.png)

[librenms@XXXXXXX ~]$ rrdtool graph /tmp/Wl0lxBYsMtNofWxw  -g --alt-autoscale-max --rigid -E --start 1640640000 --end 1640726400 --width 1296 --height 300 -c BACK\#EEEEEE00 -c SHADEA\#EEEEEE00 -c SHADEB\#EEEEEE00 -c CANVAS\#FFFFFF00 -c GRID\#a5a5a5 -c MGRID\#FF9999 -c FRAME\#5e5e5e -c ARROW\#5e5e5e -R normal -c FONT\#000000 --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal COMMENT:'                                            ' COMMENT:'     Current' COMMENT:'   Average' COMMENT:'   Maximum' COMMENT:'\\n' HRULE:0\#999999 --daemon unix:/var/run/rrdcached/rrdcached.sock
1377x339

**Comment by laf** [comment]
So that shows it's not actually seeing any interfaces to pull data for. I haven't done much dev on LibreNMS for a while so can't offer any next steps.

**Comment by rokkhan** [comment]
Thanks @laf. 
The issue is that if i click on individual interfaces the graphs are working ok.
![imagen](https://user-images.githubusercontent.com/22644111/148068011-1494c5a3-6f0a-4b73-b792-bf4c8c7a9dfb.png)

I would remove the device a rediscover it, but I don´t to lose the invidual interfaces graph.

**Comment by murrant** [comment]
Looks like ALL your interfaces are of type `ieee8023adLag` which is excluded from the overview by default because it would double up the traffic shown there (because the underlying interfaces are shown too).

You can modify the `device_traffic_iftype` setting if you would like to modify this behavior for your install.

If the ports are not LAGs, you should report the snmp bug to your device vendor.

**Comment by rokkhan** [comment]
Yes, all the interfaces were ieee8023adLag. I have added the physical ones and started to graph.
Thanks a lot!

**Comment by MyoMinKyaw10** [comment]
I am facing an issue like this! How did you recover it?
