### ISSUE TITLE
Missing key "display" in alert array

### ISSUE THREAD

**Issue by nightcore500** [librenms/librenms#13646]
### The problem

I currently have a device in my monitoring which unfortunately does not output a sysname via snmp. I have just tried to use the display function on this device to force a device name. However, the new parameter does not appear in the alert array when an alert is issued. ($alert->display or something else) The set name is also not to be found by $alert->sysName. So I have no way to process the new parameter in a template.
I am currently unsure if this is intentional and I have misunderstood the new "display" function or if this is a bug?

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.12.0
DB Schema | 2021_11_29_165436_improve_ports_search_index (229)
PHP       | 7.4.25
Python    | 3.7.3
MySQL     | 10.5.11-MariaDB-1-log
RRDTool   | 1.7.1
SNMP      | 5.7.3
====================================

[OK]    Composer Version: 2.2.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

**Comment by murrant** [comment]
LibreNMS is large, it is hard to find all the spots which might not respect the display variable. Thanks for reporting.
