### ISSUE TITLE
No processor and memory usage info

### ISSUE THREAD

**Issue by arabesc** [librenms/librenms#13643]
### The problem

LibreNMS is installed on a FreeBSD 13.0-RELEASE-p4 system and it doesn't show processor and memory usage information for it.

![image](https://user-images.githubusercontent.com/2709027/147865425-5ed90e3b-6852-4d67-8f48-31082bdcc2ab.png)

### Output of ./validate.php

```txt
# sudo -u www ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.5.1
DB Schema | 2021_04_08_151101_add_foreign_keys_to_port_group_port_table (208)
PHP       | 7.4.27
Python    | 3.8.12
MySQL     | 10.4.22-MariaDB-log
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.9
====================================

[OK]    Installed from package; no Composer required
[OK]    Database connection successful
[OK]    Database schema correct
```

**Comment by PipoCanaja** [comment]
Hi @arabesc 
Is you snmpd server properly configured ? did you try snmpwalk manually to check if the values are returned ? what does LibreNMS debug data tells you ? 
You should open a post on the community forum or on discord to receive help on how to use and configure LibreNMS. Issues are primarily for bugs

**Comment by arabesc** [comment]
I haven't done anything specific about that issue but the processor and memory statistics is working now.
