### ISSUE TITLE
Ubiquiti AirOS Temperature Scale

### ISSUE THREAD

**Issue by JKJameson** [librenms/librenms#13647]
### The problem

Temperature is reported as 385.88 M°C when expected temp is about 30 to 40c

![Untitled](https://user-images.githubusercontent.com/275770/147987365-e49f1a39-b432-4eff-b560-cbe0a3004df2.png)

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.12.0-4-g4b64d33d1
DB Schema | 2021_25_01_0129_isis_adjacencies_nullable (229)
PHP       | 7.4.25
Python    | 3.9.2
MySQL     | 10.5.12-MariaDB-0+deb11u1
RRDTool   | 1.7.2
SNMP      | 5.9
====================================

[OK]    Composer Version: 2.2.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

**Comment by aztec102** [comment]
Hello!
Apparently, Ubiquiti used to send via OID Interger (0 ... 255). Now, on the new AirOS 8, they began to give values more, which must be divided by 10.

**Comment by JKJameson** [comment]
AirOS 6.3.6 does not seem to poll temperatures. Nothing in the GUI, also nothing in the poller debug log. This is fine - it doesn't throw an erroneous alert.


AirOS 8.7.5
`Checking (snmp) temperature Temperature... 
335.54432 C
RRD[last 10.2.0.103/sensor-temperature-airos-0.rrd  --daemon unix:/run/rrdcached.sock]  
RRD[update 10.2.0.103/sensor-temperature-airos-0.rrd N:335.54432 --daemon unix:/run/rrdcached.sock]  
`

Adding a divisor of 10000000 does the trick for me. As the temperature isn't detected for AirOS 6 and presumably earlier, I am assuming this is fine, but have no earlier devices to test.

https://github.com/librenms/librenms/pull/13655

**Comment by murrant** [comment]
So, looks like 8.7.4 and 8.7.5 have the bad values... Probably the fix is to add two temperature sensor entries and skip them for os versions where it doesn't apply.   Very cool stuff Ubiquiti.

**Comment by JKJameson** [comment]
It's very unfortunate that I started using LibreNMS with AirOS firmware from 8.7.4 or I would have picked up that the specific update broke this.

https://community.ui.com/releases/airMAX-AC-8-7-4/6b38ecfe-8486-40c0-9be5-5fb168c7a010

![image](https://user-images.githubusercontent.com/275770/148690369-104d6531-d8cc-40e6-80b2-8451d9e4ab63.png)

9 months ago report... still broken. The chance of them fixing this by user request is slim to none.

**Comment by murrant** [comment]
Agreed.  Please see my suggested fix in my previous post.  Would be great if you could update your PR to include that.
