### ISSUE TITLE
Add "Red Alarm" and "Yellow Alarm" State monitoring to Juniper EX switches.

### ISSUE THREAD

**Issue by westones3** [librenms/librenms#1365]
Juniper switches have yellow and red alarm state monitoring (on / off) which are currently monitored in observium. I was hoping to match that functionality. That "state" shows up in the overview section of the device indicating if the alarms are on or off. The OIDs for alarm states are:

Red Alarm: jnxRedAlarmState 	1.3.6.1.4.1.2636.3.4.2.3.1
Yellow Alarm: jnxYellowAlarmState 	1.3.6.1.4.1.2636.3.4.2.2.1

Here is the webpage where I found those OIDs along with some other OIDs relating to the alarms. http://www.matthewjwhite.co.uk/2012/08/16/monitoring-alarm-status-on-juniper-ex-switches/

**Comment by laf** [comment]
Are these pure and simple a single OID to lookup that provides a 0 or 1?

**Comment by westones3** [comment]
I found a little more documentation on this. It looks like there are 3 states. 1 = unknown, 2 = off, 3 = on

http://www.juniper.net/techpubs/en_US/junos14.2/topics/reference/general/jnxredalarms-nm-mib.html
