### ISSUE TITLE
Bonding interface does not show traffic above 1Gbit

### ISSUE THREAD

**Issue by shark136** [librenms/librenms#13651]
### The problem

![image](https://user-images.githubusercontent.com/16813665/148071751-ae62b7f5-5dfc-4910-b7cf-97b185ccfbf4.png)

### Output of ./validate.php

```txt
Last login: Tue Jan  4 12:33:47 2022
librenms@librenms:~$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.12.0
DB Schema | 2021_11_29_165436_improve_ports_search_index (229)
PHP       | 7.4.16
Python    | 3.8.10
MySQL     | 10.3.32-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | 5.8
====================================

[OK]    Composer Version: 2.2.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
librenms@librenms:~$
```

**Comment by laf** [comment]
Check the output of snmp for this device, you might find that it's only reporting back that to us. Are you sure it's doing more than 1Gbps? what do the unbonded ports show?

**Comment by murrant** [comment]
My bet is he has port rrdtune enabled and ifSpeed set to 1000

**Comment by shark136** [comment]
> My bet is he has port rrdtune enabled and ifSpeed set to 1000

![image](https://user-images.githubusercontent.com/16813665/148159400-c5b8f60a-b819-49de-83a1-ba456fcb9340.png)
all settings in default as it was from the box.
p.s bet lost;) 

The problem still turned out to be in mikrotik, because it sends such information and this bug has been going on for a very long time. Found a thread from 2017 on their forum.

But at the same time, I installed Observium it specifically for the test, and at least it does not show an empty graph, but makes a cut-off for 1Gbit. 
![image](https://user-images.githubusercontent.com/16813665/148160241-c4a411c8-0686-4d1a-b9ad-111016fb1e99.png)

**Comment by murrant** [comment]
Well to understand what is going on , we would need to know the snmp output and polling debug output of the device.

`snmpwalk -v2c -c COMMUNITY HOSTNAME IF-MIB::ifInOctets`

`./poller.php -m ports -d -h HOSTNAME`

**Comment by shark136** [comment]
> snmpwalk -v2c -c COMMUNITY HOSTNAME IF-MIB::ifInOctets
how exactly it should be ? just with replace "COMMUNITY" and "HOSTNAME" it doesn't work.


> ./poller.php -m ports -d -h HOSTNAME
attached[](url
[1.zip](https://github.com/librenms/librenms/files/7815971/1.zip)
)

**Comment by murrant** [comment]
From your poller log I see:
A. Your device is reporting ifHighSpeed as 1000 (or 1Gbps)
B. LibreNMS is correctly calculating 1.07Gbps
C. LibreNMS is also sending the correct values to RRD.

This means, your rrd file has a max change set to 1Gbps (as I guessed) and is discarding the values over 1Gbps.

Options to fix:
1. Delete the rrd file an let LibreNMS recreate it.
2. Set the ifSpeed to 2Gbps manually in LibreNMS and enable rrdtune.  This should change the max value in your rrd file.

So, seems like my guess was right and at some point rrdtune was enabled and set the incorrect max speed of 1Gbps given by the device. ;-)

**Comment by shark136** [comment]
> 2\. Set the ifSpeed to 2Gbps manually in LibreNMS and enable rrdtune.  This should change the max value in your rrd file.
yeah, already did this. tnx.
