### ISSUE TITLE
Trouble fetching graph with encoded uri component

### ISSUE THREAD

**Issue by dannylifino** [librenms/librenms#13660]
### The problem

Original interface name: HP Flex d11

https://monitor.serverion.com/plugins/netbox-graph.php?device=asw002.zmr.serverion.com&interface=HP%20Flex%20d11&duration=8h

Because the interface is encoded, it doesn't work. Is there a fix for this, to probably fetch it?

### Output of ./validate.php

```txt
-
```

### What was the last working version of LibreNMS?

21.7

### Anything in the logs that might be useful for us?

```txt
-
```

**Comment by laf** [comment]
Where about in the UI are you having this info, I couldn't work it out from what you've provided so far?

**Comment by dannylifino** [comment]
@laf 

Hey Neil,

Thanks for your response. I have found more information regarding this particular issue in the error log. It seems that when using this information, we get a CURL undefined error.

`2022/01/25 12:07:52 [error] 23547#23547: *1021222 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: curl in /opt/librenms/html/plugins/netbox-graph.php on line 76PHP message: PHP Warning:  curl_close() expects parameter 1 to be resource, null given in /opt/librenms/html/plugins/netbox-graph.php on line 76" while reading response header from upstream, client: 81.207.37.147, server: monitor.serverion.com, request: "GET /plugins/netbox-graph.php?device=asw013.zmr.serverion.com&interface=HP%20VC%20FlexFabric%2010Gb/24-Port%20Module%204.85%20d3&duration=8h HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "monitor.serverion.com"`

`Warning:  curl_close() expects parameter 1 to be resource, null given in /opt/librenms/html/plugins/netbox-graph.php on line 76`

This only happens with this particular interface. What could be the reason for this error that curl is null?

**Comment by dannylifino** [comment]
@laf Could you please help out?

**Comment by laf** [comment]
Is this some custom code? I mean yes you do have an error and it needs fixing but that netbox-graph.php isn't one of our files so you need to take it up with whoever wrote it.
