### ISSUE TITLE
Installation impossible

### ISSUE THREAD

**Issue by Peter2121** [librenms/librenms#13664]
### The problem

I'm trying to install LibreNMS, at the end of the procedure I start the browser and try to access http://<IP>/install
Error 404 is shown in the browser.
Checking the installation directory, I cannot find /librenms/html/install subdirectory.
I saw several issues like this, but I've never found any information about the origin of this error.
In the git repository /install subdirectory is absent as well.
_Please_, explain the _source_ of this problem and how to fix it in different environments.

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.5.1
DB Schema | Not Connected (0)
PHP       | 7.4.27
Python    | 3.8.12
MySQL     | ?
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.9
====================================
```

**Comment by laf** [comment]
You are probably better asking on discord as this isn't a LibreNMS really, you're not using the correct URL to access the install.
