### ISSUE TITLE
~250 empty ports created for D-Link DGS-3100-48

### ISSUE THREAD

**Issue by tobiasa1** [librenms/librenms#1366]
I have done some basic troubleshooting with @laf regarding interfaces without any data from this switch, couldn’t find any good solution so let's start again from here.
1. DGS-3100 creates 250 empty ports in LibreNMS with no description, name or traffic data. Sometimes they get deleted but comes back after a while.
2. CPU/Memory graphs doesn't work. Maybe not supported from SNMP on this switch?

If you need SNMP access for troubleshooting please let me know.

**Comment by laf** [comment]
Anyone able to assist with this? I've checked quite a bit with tobiasa direct and couldn't find what was wrong.

**Comment by Rosiak** [comment]
Is this anything worth proceeding with?

**Comment by tobiasa1** [comment]
The issue is still there. Let me know if I can help by providing any kind of snmp queries.

**Comment by Rosiak** [comment]
Can you provide a SNMPWALK of this unit?

**Comment by durgoll** [comment]
Hi,

snmp queries is following:

nmpwalk -Os -v 2c -c public switch1

Find attached logs.

[snmpwalk.txt](https://github.com/librenms/librenms/files/350161/snmpwalk.txt)

**Comment by laf** [comment]
We would need the output of `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .`

**Comment by murrant** [comment]
You can disable the ports-stack module if you are not using port stacking.
This device reports all stacking ports as active, which makes them show up as interfaces.

**Comment by kyob** [comment]
>  CPU/Memory graphs doesn't work. Maybe not supported from SNMP on this switch?

Don't know if it's related but librenms don't graph CPU/Memory for none of my dlink switches (DGS-3120, DGS-3100, DES-3028, DES-3052, DGS-3100, DGS-3627)

**Comment by laf** [comment]
No further info provided

**Comment by kyob** [comment]
SNMPBULKWALK: [d-link-dgs-3100-24.txt](https://github.com/librenms/librenms/files/736753/d-link-dgs-3100-24.txt)

Maybe it's related with hardware revision my is **04**
