### ISSUE TITLE
Links broken in Web interface

### ISSUE THREAD

**Issue by Peter2121** [librenms/librenms#13672]
### The problem

As I cannot install my own instance [(https://github.com/librenms/librenms/issues/13664),](https://github.com/librenms/librenms/issues/13664) I tried to use the VM image downloaded from GitHub. It works better, but many links are broken in the Web interface.
![shot-2022-01-12_14-12-11](https://user-images.githubusercontent.com/3807655/149151289-06d94e92-642e-4d12-a3a1-fad5e57bf90a.jpg)
_All menus_ of this type are broken - the links are shown like [http://localhost:8080/http:/devices/format=graph_processor/from=-24hour/to=now/](http://localhost:8080/http:/devices/format=graph_processor/from=-24hour/to=now/)

### Output of ./validate.php

```txt
This is an official image, I did not change anything inside.
====================================
Component | Version
--------- | -------
LibreNMS  | 21.2.0-2-gd20e1bdf5
DB Schema | 2021_02_09_084318_remove_perf_times (199)
PHP       | 7.4.3
Python    | 3.8.10
MySQL     | 10.3.32-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.2.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  Your install is over 24 hours out of date, last update: Thu, 18 Feb 2021 14:10:32 +0000
	[FIX]:
	Make sure your daily.sh cron is running and run ./daily.sh by hand to see if there are any errors.
```

**Comment by Peter2121** [comment]
The version 1.63 from previous OVA does not have this problem.

**Comment by laf** [comment]
Same response as you're other issue, please use discord or the community.librenms.org site for help like this.

**Comment by Peter2121** [comment]
Personally, I don't need any help now - I've downloaded the OVA with 1.63 version, and it works fine for me. It's sad that you don't want to fix _your_ software.

**Comment by laf** [comment]
1.63 is extremely old and has had many bug and security fixes in it.

The software isn't broken, if all the links you are claiming are broken, were actually broken, we'd have a lot of people raising posts in GitHub, Discord and the Community site. That's not the case and as GitHub is for the codebase and this isn't a code issue I've merely asked you to seek help in a more appropriate channel. Feel free not to but please don't sling comments around that are simply untrue.

**Comment by drebatto** [comment]
I am using the official OVA image and I am seeing the same problem: all the links of the sub-menus have an extra 'http:/' string in the middle, which needs to be removed by hand in the browser's URL box.
I don't get why are you so reluctant to call it a code issue: even if it's some corner case, even if it depends on some misconfiguration, it is still up to the code not to build up broken links.

**Comment by drebatto** [comment]
P.S. this seems a regression of the problem mentioned here:
https://community.librenms.org/t/broken-links-for-graphs-in-ui/12874
which had been fixed in the code already.
