### ISSUE TITLE
Expand Client/Server model

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#1373]
First of all I'd like to thank @laf for the great work he did on our API.
We can get almost all information presented by the UI via the API.

I'd like to see a full separation of the UI/API from the pollers and discover'ers.
Following this idea will enable us to drastically refurnish our UI and make it a piece of cake for 3rd parties to include our data into their overviews. (Desktop/Mobile Apps, Customer-specific quick overviews, ...)
It also allows us to rapidly extend the UI as it would ultimately only require access to the API's Host and range from a plain JS website operating with AJAX or to any other preferred language stack that your environment might favour over PHP.
Apart from these development-centric opportunities it also clears the path for redundant active/passive failover and potentially even active/active loadbalancing setups.

This imposes a big structural change.

Request For Comments ;)

**Comment by laf** [comment]
So you're saying have the Web UI talk directly to the API for everything? Interesting idea. It's something I know Domoticz does as the front end is a cachable JS implementation.

Couldn't say whether I think it's a good idea or not, it seems like it will be a big chunk of work but for what gain?

**Comment by laf** [comment]
In progress with rewrite. Closing
