### ISSUE TITLE
LibreNMS alerting mail stops working after some time

### ISSUE THREAD

**Issue by R-Rep** [librenms/librenms#13734]
### The problem

Hello,

We have an installation of libreNMS and this monitors the network switches. We should get an mail when an device is down. This is working right after reboot. However, when some time passes it seems like the server is unable to send the allert mails. When this occurs we see the following error:

**"Could not issue critical alert for rule 'Down (24x7)' to transport 'mail' Error: <strong>Message body empty</strong><br />"**
![image](https://user-images.githubusercontent.com/98741648/151780965-372a6342-7ea1-4bc8-815f-63001d0695fe.png)

When we use the test option for the mail it gives an OK back and we get the test mail. 
running our validate.sh it show a fail on memcached but thats because we use rrdcache. 

Our Mail settings are as follows:
![tempsnip](https://user-images.githubusercontent.com/98741648/151781942-9d6e0aef-afb0-4e34-854d-d3a7139d4827.png)
![image](https://user-images.githubusercontent.com/98741648/151781586-5bb23a7a-75a2-4fc5-bad0-bd09a1b9ba9d.png)

Can you help us understand what could cause this behaviour?

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.11.0
DB Schema | 2021_11_17_105321_device_add_display_field (226)
PHP       | 8.0.13
Python    | 3.8.10
MySQL     | 10.5.9-MariaDB-1:10.5.9+maria~bionic
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.1.14
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[WARN]  Your database schema has extra migrations (2021_11_12_123037_change_cpwVcID_to_unsignedInteger, 2021_11_17_105321_device_add_display_field). If you just switched to the stable release from the daily release, your database is in between releases and this will be resolved with the next release.
[OK]    Database schema correct
[INFO]  Detected Dispatcher Service
[FAIL]  Dispatcher service is enabled on your cluster, but not in use on this node
[FAIL]  Missing PHP extension: memcached
        [FIX]: 
        Please install memcached
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]: 
        You can fix this with ./scripts/github-remove
        Modified Files:
         rrd/.gitignore
```

### What was the last working version of LibreNMS?

21.11.0

### Anything in the logs that might be useful for us?

```txt
We could not find any errors in the logs.
```

**Comment by ottorei** [comment]
You should update to the latest release first. 

I am using the email transport without any issues for similar purpose myself. Do you have a custom template attached to the alert rule? Have you renamed the default template? Is this a single node setup?

**Comment by R-Rep** [comment]
Hello,

I don't have any custom template attached to the alert. Furthermore the setup consist of 2 nodes. But each node is servicing its own group op devices (no group has multiple nodes).

Met vriendelijke groet,

N.R. Rep

E: ***@***.******@***.***>
T: +31 50 521 3021
M: +31 6 1566 5476
Van: ottorei ***@***.***>
Verzonden: maandag 31 januari 2022 13:32
Aan: librenms/librenms ***@***.***>
CC: Rep N.R. (Rudie) ***@***.***>; Author ***@***.***>
Onderwerp: Re: [librenms/librenms] LibreNMS alerting mail stops working after some time (Issue #13734)


You should update to the latest release first.

I am using the email transport without any issues for similar purpose myself. Do you have a custom template attached to the alert rule? Have you renamed the default template? Is this a single node setup?

-
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flibrenms%2Flibrenms%2Fissues%2F13734%23issuecomment-1025692284&data=04%7C01%7Cn.r.rep%40gasunie.nl%7C24e4194420d945351a0108d9e4b5b829%7C0dba6fac697148f39af1d8a86d20e1ed%7C0%7C0%7C637792291396901966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iJmPiQVZNMiflrU3z33VpK2teyFFXeEL8Rpfg0vW%2BfI%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXRK3EEEWF5H7NJDZJB6BFLUYZ6NBANCNFSM5NF5KWMA&data=04%7C01%7Cn.r.rep%40gasunie.nl%7C24e4194420d945351a0108d9e4b5b829%7C0dba6fac697148f39af1d8a86d20e1ed%7C0%7C0%7C637792291396901966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=avQ7XSeGnKq2s97yHxf5IftdSKMoqd4kbk6OJv4bZac%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cn.r.rep%40gasunie.nl%7C24e4194420d945351a0108d9e4b5b829%7C0dba6fac697148f39af1d8a86d20e1ed%7C0%7C0%7C637792291396901966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ajUxPpzO5YXxp0rAayXzxquYdr04gqUADAwji0%2FAfqg%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cn.r.rep%40gasunie.nl%7C24e4194420d945351a0108d9e4b5b829%7C0dba6fac697148f39af1d8a86d20e1ed%7C0%7C0%7C637792291396901966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TLXFcitogSFqiVk%2BXtBbRAZdseabvwier4te7IYi%2Buo%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________
This communication is intended only for use by the addressee. It may contain confidential or privileged information. If you receive this communication unintentionally, please let us know by replying immediately. N.V. Nederlandse Gasunie does not guarantee that the information sent with this E-mail is correct and does not accept any liability for damages related thereto.
________________________________
