### ISSUE TITLE
Date picker default values are in UTC

### ISSUE THREAD

**Issue by clinta** [librenms/librenms#1374]
If your local time is configured properly, if you click a 6 hour graph the graph is properly drawn, with the axis labeled in local time, but the date picker above is pre-populated with the UTC time that corresponds to the graph.

If you use the date picker to select a time, the filter is applied as local time.

The easiest way to see this is to click a six hour graph, then hit update with the default values that are in the date picker and watch the graph change.

**Comment by f0o** [comment]
Possible Duplicate: #1239
Given-Up attempt of fixing it: #1241

**Comment by laf** [comment]
Feel free to re-open if this isn't resolved, PR has been merged in which hopefully does.
