### ISSUE TITLE
Brocade FESX switch shows MAC address on the map

### ISSUE THREAD

**Issue by azhermughal** [librenms/librenms#1375]
Under the map, Brocade switch FESX448 shows MAC address on the link with the neighboring switch. Rather it should show the port number. Laf helped in debugging and his comments are:

<lafwood> azher: It looks like the mac is returned for the remote port: lldpRemPortId.0.1050756.1 = "00 0c db c8 b0 70"

pastebin for Brocade Fesx448: http://pastebin.com/LZk1DLUP
pastebin for the uplink switch Dell S4810: http://pastebin.com/npvsNqyY

So can we change the MAC address to a more reasonable port name on the map ?

Thanks
-Azher

**Comment by laf** [comment]
Out of interest on the Brocade, can you do a show of your lldp neighbours to see what the remote port id is being shown as?

**Comment by azhermughal** [comment]
Please see below:

SSH@x448-IPAC:R-022-MRG07#show lldp nei
Lcl Port Chassis ID      Port ID         Port Description        System
Name  
49       0001.e88b.8993  TenGigabitEthe~ Rack-022-MRG07-Foundry~
s4810:R-022-M~


SSH@x448-IPAC:R-022-MRG07#show lldp neighbors detail
Local port: 49
  Neighbor: 0001.e88b.8995, TTL 96 seconds
    + Chassis ID (MAC address): 0001.e88b.8993
    + Port ID (interface name): "TenGigabitEthernet 0/17"
    + Time to live: 120 seconds
    + Port description    : "Rack-022-MRG07-Foundry-x448-e49"
    + System name         : "s4810:R-022-MRG-08"
    + System description  : "Dell Real Time Operating System Software.
Dell Op\
                             erating System Version: 2.0. Dell
Application Sof\
                             tware Version: 9.7(0.0P4) Copyright (c)
1999-2015\
                              Dell Inc. All Rights Reserved.Build Time:
Mon Ma\
                             y  4 20:52:56 2015"
    + System capabilities : repeater, bridge, router
      Enabled capabilities: repeater, bridge, router
    + Maximum frame size: 9216 octets
    + Port-Protocol VLAN ID: 6
    + Port-Protocol VLAN ID: 10

SSH@x448-IPAC:R-022-MRG07#

**Comment by laf** [comment]
I don't believe we can fix this as the port id is being shown as a mac here :(

**Comment by azhermughal** [comment]
I agree this switch is creating confusion. Perhaps for this model, could
we use the port number learned from the switch itself, instead of
relying on the neighbor as what port the neighbor sees for this switch
port ?

-Azher

**Comment by laf** [comment]
@azhermughal We won't really be able to do anything on this as it would be a specific fix for a single device, something might be fixed in updated firmware and may not be something others experience.

Feel free to re-open this if we can help further.

**Comment by azhermughal** [comment]
I see same issues with the recent Brocade MLX series of switches. It is running the latest code release 05800b. 

http://imagebin.ca/v/28HPco8PtOZa

-Azher
