### ISSUE TITLE
URL Not Found, from Dashboard (Alerts)

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#13761]
### The problem

Hi,

I thought I was going crazy, for a long time ... LOL. Community issue noted [here](https://community.librenms.org/t/dashboard-home-site-issues-using-sub-directory/13044), but I think I finally found the exact scenario to make this happen. There have been a lot of updates, so links from the dashboard work ... and they do, for several of the window "types". For example, clicking on a device now in the Availability Map, or Traffic (Top 5) all work fine. But ... if I click on a device in Alerts, I get the error, "The requested URL was not found on this server.".

To clarify, this is with a value set for RewriteBase (in html/.htaccess). And again - it only seems to be the case with the devices in the Alerts window now.

Let me know what I can do to try to help debug this!

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 22.1.0-129-g6f1b1de4b
DB Schema | 2021_12_02_113537_ports_stp_designated_cost_change_to_int (234)
PHP       | 8.0.8
Python    | 3.9.7
MySQL     | 10.5.13-MariaDB-0ubuntu0.21.10.1-log
RRDTool   | 1.7.2
SNMP      | 5.9
====================================

[OK]    Composer Version: 2.2.6
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]:
        You can fix this with ./scripts/github-remove
        Modified Files:
         html/.htaccess
```

**Comment by arrmo** [comment]
FYI, in case this helps! Also see the same issue from the Alerts > Notifications page. Thinking they are linked, but I may be wrong.

Thanks!

**Comment by murrant** [comment]
If that doesn't show right, try changing this in routes/web.php:
    Route::get('/', 'OverviewController@index')->name('home');
to 
    Route::get(null, 'OverviewController@index')->name('home');

**Comment by murrant** [comment]
If that doesn't show right, try changing this in routes/web.php:
    Route::get('/', 'OverviewController@index')->name('home');
to 
    Route::get(null, 'OverviewController@index')->name('home');

And clear your route cache `php artisan route:clear`

**Comment by ottorei** [comment]
You mentioned you have some rewrite-rules on .htaccess, could you post those also? I also believe you have followed the instructions from the docs (https://docs.librenms.org/Extensions/Sub-Directory/)?

In any case, the recommended way to run the software is with (sub)domain and that is also what has been tested and documented. If using an internal DNS-record for the server is an option, I would definitely recommend using that.

**Comment by arrmo** [comment]
FYI, even with the setup as above - if I don't set the RewriteBase in html/.htaccess, my pages (all of them) don't seem to work?

Thanks!

**Comment by arrmo** [comment]
Sorry, just checking back in - in case you are looking / waiting for something from me (and I didn't get that 😆).

Thanks!

**Comment by arrmo** [comment]
Still having this issue with the latest release - but only for the Alerts widget. Is it working for others?

Thanks!

**Comment by arrmo** [comment]
Still having this issue with the latest release - but only for the Alerts widget. Is it working for others?

Thanks!

**Comment by murrant** [comment]
I don't know why your urls for that are generated wrong, there are a lot of variables.

However, I do know that the Laravel route helpers will generate correct links for you.  So one way of fixing this would be to convert the `includes/html/table/alerts.inc.php` file to a Laravel controller in `app/Http/Controllers/Table` and use the route helpers to generate the link.  There are many examples in the code.

**Comment by arrmo** [comment]
OK, let me take a look. The issue is that it's just not including the `RewriteBase` - the other widgets are fine, just the Alerts is failing.

Thanks.

**Comment by arrmo** [comment]
Arrgh. No idea what happened, but my posting from yesterday seems to be lost 😞. I did dig into this, and it seems to be related to `RewriteBase` not being used with the library functions for Url generation? What I mean is ...
1. `includes/html/table/alerts.inc.php` => `generate_device_link` (`includes/html/functions.inc.php`)
2. `includes/html/functions.inc.php` => `\LibreNMS\Util\Url::deviceLink`
3. `LibreNMS/Util/Url.php` => `Url::deviceUrl` => `return route`

But route does not seem to make use of `RewriteBase`? Seems this is missing in general?

Thanks!

**Comment by arrmo** [comment]
Hi,

I'm definitely not a Laravel expert (not even close 😆), but looking at the code, and also [this info](https://stackoverflow.com/questions/23059918/laravel-get-base-url), it seems that perhaps the `base_url` is not set?

Thanks!

**Comment by arrmo** [comment]
Oh, and to avoid any confusion - I am using a sub-directory (`/librenms`), and have set it up like [here](https://docs.librenms.org/Extensions/Sub-Directory/). Only the Alerts widget isn't working, the others are fine.

Thanks!

**Comment by arrmo** [comment]
OK, this is so odd 😆. I am set up almost fully like this [info](https://docs.librenms.org/Extensions/Sub-Directory/), and have tried both of the options below (as one matches the link, the other the info in `config.php`),
```
### This should *only* be set if you want to *force* a particular hostname/port
### It will prevent the web interface being usable form any other hostname
#$config['base_url']        = "http://librenms.company.com";
$config['base_url'] =(!empty($_SERVER['HTTPS']) ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'] . '/' . 'librenms/';
$config['base_url'] = '/librenms/';
```

Still the same issue, only with Alerts. But I also see now a second issue, when I'm on a device page, and click (for example) on a port ... I get `/librenms` twice in the path! Of course, that doesn't work 😞. It really seems related to the Sub-directory settings, but I am following the docs.

Thanks!

**Comment by Jellyfrog** [comment]
Librenms doesn't fully support being in a sub-directory, use a subdomain instead.
If you figure out what's missing, submit a pull request !

**Comment by murrant** [comment]
@arrmo It "works" but I think it very easy to implement sub-directory in a way that doesn't work.  No one has stepped up to fix things that are broken and/or clarify documentation.  There have been a few fixes over the years.

**Comment by arrmo** [comment]
No worries, understand. I tried to worm my way through the code, as noted above ... but got stopped as it "jumped" to libraries 😞. I'll just move to the subdomain approach, but perhaps the online documentation should be updated? Just a thought.

Thanks!
