### ISSUE TITLE
Brocade MLXe-8 wrong Dynamic Memory Value

### ISSUE THREAD

**Issue by azhermughal** [librenms/librenms#1378]
Brocade Router MLXe-8 is showing wrong Dynamic Memory "2147483647%"

Here is the poller debug output: http://pastebin.com/q4Kyag3N

Please let me know if you need more details, I can get all the latest MIBs for this device.

-Azher

**Comment by laf** [comment]
Hi @azhermughal if you can provide us with the mibs that would be good.

For snAgGblDynMemTotal which is returning -1 it says "For NI platforms, refer to snAgentBrdMemoryTotal". Is this an NI platform?

**Comment by laf** [comment]
bump

**Comment by azhermughal** [comment]
This is Brocade MLXe 8 slot chassis. Though it has one old NetIron (NI) 10GE card installed (slot 4) as well. Rest of the line cards are from the MLX series, but fabric and others seem common to both chassis. Operating system, it is called as Net Iron

Mibs that came along with the latest release a month ago 05800b are attached.

Let me know if you need more info. Thanks.

SSH@MLXe8-HEP#show module
Module                                                          Status                       Ports    Starting MAC   
M1 (left ):BR-MLX-MR2-M Management Module                       Active                       
M2 (right):BR-MLX-MR2-M Management Module                       Standby(Ready State)
F1: NI-X-HSF Switch Fabric Module                               Active                         
F2: NI-X-HSF Switch Fabric Module                               Active                         
F3: NI-X-HSF Switch Fabric Module                               Active                         
S1: BR-MLX-100Gx2-X 2-port 100GbE Module                        CARD_STATE_UP                2        cc4e.241c.7500
S2: Blocked for full height card in Slot 1
S3: BR-MLX-40Gx4-M 4-port 40GbE Module                          CARD_STATE_UP                4        cc4e.241c.7560
S4: NI-MLX-10Gx8-M 8-port 10GbE (M) Module                      CARD_STATE_UP                8        cc4e.241c.7590
S5:
S6: Configured as BR-MLX-40Gx4-M 4-port 40GbE Module (31)
S7:
S8:

SSH@MLXe8-HEP#show version
System Mode: MLX
Chassis: MLXe 8-slot (Serial #: BGB2538J01K,  Part #: 40-1000362-04)
NI-X-HSF Switch Fabric Module 1 (Serial #: BEU0428J01B,  Part #: 60-1001588-14)
FE 1: Type fe600,  Version 1
FE 3: Type fe600,  Version 1
Switch Fabric Module 1 Up Time is 44 days 22 hours 39 minutes 43 seconds
NI-X-HSF Switch Fabric Module 2 (Serial #: BEU0430J02R,  Part #: 60-1001588-14)
FE 1: Type fe600,  Version 1
FE 3: Type fe600,  Version 1
Switch Fabric Module 2 Up Time is 44 days 22 hours 39 minutes 43 seconds
NI-X-HSF Switch Fabric Module 3 (Serial #: BEU0435J010,  Part #: 60-1001588-14)
FE 1: Type fe600,  Version 1
FE 3: Type fe600,  Version 1
Switch Fabric Module 3 Up Time is 44 days 22 hours 39 minutes 43 seconds
==========================================================================
SL M1: BR-MLX-MR2-M Management Module Active (Serial #: BVP0427J032, Part #: 60-1002374-07):
Boot     : Version 5.8.0T165 Copyright (c) 1996-2014 Brocade Communications Systems, Inc.
Compiled on May 18 2015 at 13:02:10 labeled as xmprm05800
 (521590 bytes) from boot flash
Monitor  : Version 5.8.0T165 Copyright (c) 1996-2014 Brocade Communications Systems, Inc.
Compiled on May 18 2015 at 13:01:40 labeled as xmb05800
 (539721 bytes) from code flash
IronWare : Version 5.8.0bT163 Copyright (c) 1996-2014 Brocade Communications Systems, Inc.
Compiled on May 21 2015 at 08:57:56 labeled as xmr05800b         
 (9940970 bytes) from Primary
Board ID : 00 MBRIDGE Revision : 37
1666 MHz Power PC processor 7448 (version 8004/0202) 166 MHz bus
512 KB Boot Flash (MX29LV040C), 128 MB Code Flash (MT28F256J3)
4096 MB DRAM INSTALLED
4096 MB DRAM ADDRESSABLE

**Comment by laf** [comment]
Can you provide the output of:

```bash
/usr/bin/snmpget -v2c -c community -OvQ -m FOUNDRY-SN-AGENT-MIB -M /opt/librenms/mibs udp:brocade-mlxe8-r5:161 snAgSystemDRAMTotal
/usr/bin/snmpget -v2c -c community -OvQ -m FOUNDRY-SN-AGENT-MIB -M /opt/librenms/mibs udp:brocade-mlxe8-r5:161 snAgentBrdMemoryTotal
```

**Comment by azhermughal** [comment]
I get the same following response while issuing both commands:

No Such Instance currently exists at this OID

**Comment by thecityofguanyu** [comment]
I can confirm this issue on Brocade MLX8 chassis, as well as CERs. Both models run NetIron code.

![Image]
(http://i.imgur.com/uxW1eD9.png)

**Comment by thecityofguanyu** [comment]
@laf 

>Can you provide the output of:
/usr/bin/snmpget -v2c -c community -OvQ -m FOUNDRY-SN-AGENT-MIB -M /opt/librenms/mibs udp:brocade-mlxe8-r5:161 snAgSystemDRAMTotal
/usr/bin/snmpget -v2c -c community -OvQ -m FOUNDRY-SN-AGENT-MIB -M /opt/librenms/mibs udp:brocade-mlxe8-r5:161 snAgentBrdMemoryTotal

I get  `No Such Instance currently exists at this OID` if I run the commands as `snmpget` as you requested. If I `snmpwalk`, however:

```
FOUNDRY-SN-AGENT-MIB::snAgSystemDRAMTotal.0 = INTEGER: -1
```

And,

```
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.1 = Counter64: 2147483648
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.2 = Counter64: 2147483648
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.3 = Counter64: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.4 = Counter64: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.5 = Counter64: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.6 = Counter64: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.7 = Counter64: 1073741824
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.8 = Counter64: 1073741824
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.9 = Counter64: 4294967295
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.10 = Counter64: 4294967295
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.11 = Counter64: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.12 = Counter64: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.13 = Counter64: 0
```

**Comment by thecityofguanyu** [comment]
@laf 

>For snAgGblDynMemTotal which is returning -1 it says "For NI platforms, refer to snAgentBrdMemoryTotal". Is this an NI platform?

Yes, MLX/XMR & CER are both NetIron platforms.

Here is snAgentBrdMemoryTotal
```
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.1 = Counter64: 2147483648
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.2 = Counter64: 2147483648
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.3 = Counter64: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.4 = Counter64: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.5 = Counter64: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.6 = Counter64: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.7 = Counter64: 1073741824
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.8 = Counter64: 1073741824
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.9 = Counter64: 4294967295
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.10 = Counter64: 4294967295
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.11 = Counter64: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.12 = Counter64: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryTotal.13 = Counter64: 0
```

Also, snAgentBrdMemoryUtil100thPercent:
```
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryUtil100thPercent.1 = Gauge32: 3368
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryUtil100thPercent.2 = Gauge32: 3371
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryUtil100thPercent.3 = Gauge32: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryUtil100thPercent.4 = Gauge32: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryUtil100thPercent.5 = Gauge32: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryUtil100thPercent.6 = Gauge32: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryUtil100thPercent.7 = Gauge32: 5827
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryUtil100thPercent.8 = Gauge32: 5827
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryUtil100thPercent.9 = Gauge32: 1596
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryUtil100thPercent.10 = Gauge32: 1979
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryUtil100thPercent.11 = Gauge32: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryUtil100thPercent.12 = Gauge32: 0
FOUNDRY-SN-AGENT-MIB::snAgentBrdMemoryUtil100thPercent.13 = Gauge32: 0
```

**Comment by thecityofguanyu** [comment]
@laf 

As far as I've gathered, the current mempool poller method for all Brocade Ironware devices is what is defined in <code>includes/polling/mempools/ironware-dyn.inc.php</code> as:

```
<?php
// Simple hard-coded poller for Brocade Ironware Dynamic Memory (old style)
// Yes, it really can be this simple.
$mempool['total'] = snmp_get($device, 'snAgGblDynMemTotal.0', '-OvQ', 'FOUNDRY-SN-AGENT-MIB');
$mempool['free']  = snmp_get($device, 'snAgGblDynMemFree.0', '-OvQ', 'FOUNDRY-SN-AGENT-MIB');
$mempool['used']  = ($mempool['total'] - $mempool['free']);
```

Which seems to work fine for FastIron devices (e.g. ICX switches).

For NetIron devices (e.g. MLX, CER), should it be more to this effect?

[disclaimer: I do not know php and also ripped this directly off the junos template. please point out any errors in the drafted code]

```
<?php

$oid = $mempool['mempool_index'];

d_echo('Ironware NetIron Mempool');

if (!is_array($mempool_cache['ironware-ni'])) {
    d_echo('caching');
    $mempool_cache['ironware-ni'] = array();
    $mempool_cache['ironware-ni'] = snmpwalk_cache_multi_oid($device, 'snAgentBrdMemoryUtil100thPercent', $mempool_cache['ironware-ni'], 'FOUNDRY-SN-AGENT-MIB', $config['install_dir'].'/mibs');
    $mempool_cache['ironware-ni'] = snmpwalk_cache_multi_oid($device, 'snAgentBrdMemoryAvailable', $mempool_cache['ironware-ni'], 'FOUNDRY-SN-AGENT-MIB', $config['install_dir'].'/mibs');
    $mempool_cache['ironware-ni'] = snmpwalk_cache_multi_oid($device, 'snAgentBrdMemoryTotal', $mempool_cache['ironware-ni'], 'FOUNDRY-SN-AGENT-MIB', $config['install_dir'].'/mibs');
    d_echo($mempool_cache);
}

$entry = $mempool_cache['ironware-ni'][$mempool[mempool_index]];

$perc = $entry['snAgentBrdMemoryUtil100thPercent'];

$memory_available = $entry['snAgentBrdMemoryTotal'];

$mempool['total'] = $memory_available;
$mempool['used']  = ($memory_available / 100 * $perc);
$mempool['free']  = ($memory_available - $mempool['used']);
```

Does that seem to be along the right track?

I guess there should be some way to incorporate a check to determine if the device is NI or not, though I'm not yet sure how to go about achieving that.

**Comment by thecityofguanyu** [comment]
In-progress solution:

```
<?php

$oid = $mempool['mempool_index'];

d_echo('Ironware NetIron Mempool');

if (!is_array($mempool_cache['ironware'])) {
    $is_netiron = snmp_get($device, 'sysDescr.0', '-OvQ', 'FOUNDRY-SN-AGENT-MIB');
    if (strpos($is_netiron, 'NetIron') !== true) {
        d_echo('caching');
        $mempool_cache['ironware'] = array();
        $mempool_cache['ironware'] = snmpwalk_cache_multi_oid($device, 'snAgGblDynMemUtil', $mempool_cache['ironware'], 'FOUNDRY-SN-AGENT-MIB', $config['install_dir'].'/mibs');
        $mempool_cache['ironware'] = snmpwalk_cache_multi_oid($device, 'snAgGblDynMemFree', $mempool_cache['ironware'], 'FOUNDRY-SN-AGENT-MIB', $config['install_dir'].'/mibs');
        $mempool_cache['ironware'] = snmpwalk_cache_multi_oid($device, 'snAgGblDynMemTotal', $mempool_cache['ironware'], 'FOUNDRY-SN-AGENT-MIB', $config['install_dir'].'/mibs');
        d_echo($mempool_cache);

        $entry = $mempool_cache['ironware'][$mempool[mempool_index]];

        $perc = $entry['snAgGblDynMemUtil'];

        $memory_available = $entry['snAgGblDynMemTotal'];

    }
    else {
        d_echo('caching');
        $mempool_cache['ironware'] = array();
        $mempool_cache['ironware'] = snmpwalk_cache_multi_oid($device, 'snAgentBrdMemoryUtil100thPercent', $mempool_cache['ironware'], 'FOUNDRY-SN-AGENT-MIB', $config['install_dir'].'/mibs');
        $mempool_cache['ironware'] = snmpwalk_cache_multi_oid($device, 'snAgentBrdMemoryAvailable', $mempool_cache['ironware'], 'FOUNDRY-SN-AGENT-MIB', $config['install_dir'].'/mibs');
        $mempool_cache['ironware'] = snmpwalk_cache_multi_oid($device, 'snAgentBrdMemoryTotal', $mempool_cache['ironware'], 'FOUNDRY-SN-AGENT-MIB', $config['install_dir'].'/mibs');
        d_echo($mempool_cache);

        $entry = $mempool_cache['ironware'][$mempool[mempool_index]];

        $perc = ($entry['snAgentBrdMemoryUtil100thPercent']) / 100);

        $memory_available = $entry['snAgentBrdMemoryTotal'];

    }
}


$mempool['total'] = $memory_available;
$mempool['used']  = ($memory_available / 100 * $perc);
$mempool['free']  = ($memory_available - $mempool['used']);
```

**Comment by thecityofguanyu** [comment]
In-progress discovery solution:

```
<?php

if ($device['os'] == 'ironware' || $device['os_type'] == 'ironware') {

    $is_netiron = snmp_get($device, 'sysDescr.0', '-OvQ', 'FOUNDRY-SN-AGENT-MIB');
    if (strpos($is_netiron, 'NetIron') !== true) {

        echo 'Ironware Dynamic: ';

        $percent = snmp_get($device, 'snAgGblDynMemUtil.0', '-OvQ', 'FOUNDRY-SN-AGENT-MIB');

        if (is_numeric($percent)) {
            discover_mempool($valid_mempool, $device, 0, 'ironware-dyn', 'Dynamic Memory', '1', null, null);
        }

    else {

        echo 'NetIron: ';

        d_echo('caching');
        $ni-mempools_array = snmpwalk_cache_multi_oid($device, 'snAgentBrdMainBrdDescription', $ni-mempools_array, 'FOUNDRY-SN-AGENT-MIB', $config['install_dir'].'/mibs');
        $ni-mempools_array = snmpwalk_cache_multi_oid($device, 'snAgentBrdMemoryUtil100thPercent', $ni-mempools_array, 'FOUNDRY-SN-AGENT-MIB', $config['install_dir'].'/mibs');
        $ni-mempools_array = snmpwalk_cache_multi_oid($device, 'snAgentBrdMemoryAvailable', $ni-mempools_array, 'FOUNDRY-SN-AGENT-MIB', $config['install_dir'].'/mibs');
        $ni-mempools_array = snmpwalk_cache_multi_oid($device, 'snAgentBrdMemoryTotal', $ni-mempools_array, 'FOUNDRY-SN-AGENT-MIB', $config['install_dir'].'/mibs');
        d_echo($ni-mempool_array);

       if (is_array($ni-mempools_array)) {
           foreach ($ni-mempools_array as $index => $entry) {

                d_echo($index.' '.$entry['jnxOperatingDescr'].' -> '.$entry['jnxOperatingBuffer'].' -> '.$entry['jnxOperatingDRAMSize']."
");
                $usage_oid = '.1.3.6.1.4.1.1991.1.1.2.2.1.1.28.'.$index;
                $descr     = $entry['snAgentBrdMainBrdDescription']];
                $usage     = ($entry['snAgentBrdMemoryUtil100thPercent']) / 10000);
                if (!strstr($descr, 'No') && !strstr($usage, 'No') && $descr != '') {
                    discover_mempool($valid_mempool, $device, $index, 'ironware-dyn', $descr, '1', null, null);

    }
}

unset($ni-mempools_array);
```

**Comment by thecityofguanyu** [comment]
PR #3312 opened to address this issue.

**Comment by laf** [comment]
pr merged.
