### ISSUE TITLE
Increase snmp polling rate to 1 minute

### ISSUE THREAD

**Issue by masonke** [librenms/librenms#1379]
Adding this issue as a feature request.

With 10Gbit interface now a standard in data centers and 40Gbit/100Gbit interfaces becoming common, the current 5 min polling rate is not fast enough.  A 1 minute polling rate would provide the visibility needed.

**Comment by Rosiak** [comment]
Hmm.
I have multiple 10G,40G and 80G ports/channels.
I don't see any issues for my equipment.

**Comment by masonke** [comment]
It isnt an issue for the equipment, but a granularity problem. At the higher speeds, the counters increment at a higher rate. Averaging over the larger value makes the data less precise. For example, a server can go offline for 30 seconds and then come back. With 5 min resolution, it is often masked. With 1 minute, it is found. The same for discards, overflows and other congestion values.

The 5 minute resolution also makes it harder to correlate to netflow / ipfix data, which is in 1 minute increments.

**Comment by paulgear** [comment]
This is something I'd like to consider, but it will require some significant changes to how the poller data is stored, so it will take some time & thought.

**Comment by masonke** [comment]
I have no doubt it is a big effort, but if someone doesn't ask, it wont happen.

**Comment by f0o** [comment]
stupid question here:
What if...
we create an option, for example `high_precision_modules`, and let it contain the poller-modules one like to have with say 1m resolution.
Then have a 2nd set of rrds that get created in addition to the normal 5m rrds but for specified modules only with 1m resolutions.
On graphing we would prefer the 2nd set prior the normal set.

This wouldnt alter much code but more masquerade the filenames in certain conditions. As polling by modules is supported already it would only need a small addition to the pollerwrapper to pass on module args...

my 2 cents.. probably have missed something..

**Comment by clinta** [comment]
1 minute polling time was my goal in writing #1405. All of my servers are polled once per minute using it and the hp network switches which take nearly 2 minutes to respond to  a poll are just polled constantly. It's working very well for me, I'd encourage you to test it out.

**Comment by f0o** [comment]
@clinta your pr doesnt redefine any rrds so it doesnt matter how often you poll, rrd will only take one value every 5 minutes afaik.

**Comment by paulgear** [comment]
@f0o @clinta You can add more than one value during the interval, but RRD will only record the average and maximum of them.  Which means that you get something a little more interesting than 5-minute resolution, but not by much.  We really won't get much value out of increasing the polling rate until we can overhaul the RRD creation code, which is tricky because it's scattered all over the app at the moment.

**Comment by paulgear** [comment]
(I also forgot to mention minimum value)

**Comment by clinta** [comment]
Oh I see. I'm using the higher polling rate to have quicker alrets for outages, but I use the collectd integration for the more granular graph data.

**Comment by srossen** [comment]
Just adding comment here to serve as a vote for wanting to see this. Having done 1-minute polling in Cacti I get the RRD changes. Obviously I don't fully understand the LibreNMS code changes but if is scared all of the place clearly it is not a simple as a switch of 1 vs 5 while adding a host.

**Comment by murrant** [comment]
I think it is best to use something else for outage alerts like Icinga. LibreNMS pulls a lot of data so that restricts the poll frequency.

**Comment by masonke** [comment]
No matter what is used for alerting, the data has to be collected first

**Comment by f0o** [comment]
Data for alerting is collected at any desired rate. Only data for graphing is capped at 5 minutes due to the current implemented RRD-format

**Comment by laf** [comment]
Duplicate in #1061

**Comment by jallakim** [comment]
@laf, since the "duplicate" got closed (#1061), maybe this should be re-opened again, so that we at least have one open issue regarding this?

**Comment by nrm21** [comment]
+1 for < 5 min polling

**Comment by f0o** [comment]
I think if you switch to influxdb you can have >5m polling. Not sure how/if graphing will work. Perhaps use kibana instead.. perhaps a workaround?

**Comment by nrm21** [comment]
I don't honestly care if the graphing stays showing 5 mins (for longer term data than 2 hours that's all you want anyway).  As long as I can get < 5min weathermap data for all my ports.  So I guess I would need to have Weathermap somehow pull from Influx and change the cron line for weathermap poller down from */5 to */1.  Of course I can change cron now and it will redraw evey min.  But it does me no good if it draws the same data from 2nd to the 5th min over again.  :)

Any documentation on how to get Influx working with Libre and/or weathermap by chance?  I already have an Influx running for something else.

**Comment by laf** [comment]
Influx support is documented.

Influx with Weathermap, that's not possible but is obviously a weathermap question rather than one for us.

**Comment by johnhtodd** [comment]
Experimenting with LibreNMS here, with a fork of data going to InfluxDB. It seems that LibreNMS is a nice SNMP tool that takes care of a lot of the heavy lifting of determining "what" needs to polled, and the RRD views and other tools are a very nice set of standard instrumentation.  I typically do much more sophisticated aggregation and visualization using Grafana, and it seems like a win to have LibreNMS forwarding that back at a higher speed rate even though RRD isn't suitable for the lower interval. In my experiences, 1 minute polling is pretty much standard (actually, much faster is typical for app-level stuff, but this is network so 1m is fine) and I'd like to bump my polling interval to 1m. I know RRD will not get much benefit from this, but my Grafana and other tools that digest the InfluxDB data can do lots with more data.

Am I just missing that 1m intervals are possible?  I don't see an obvious config that allows me to move this interval down.  I see the poller-service additions (http://docs.librenms.org/Extensions/Poller-Service/) but I'm a bit concerned that they say "HIGHLY EXPERIMENTAL" in big helpful warning letters, which is not something I lean towards when thinking about how to eventually put this in production.

**Comment by LaurentDumont** [comment]
Isn't the biggest problem having a polling cycle longer than a minute? I know I probably can count of the speed of the poller with 3k + Ports on our not-so great servers. Plus, even if you send the data to influxdb, the rrd files are still being updated and they are set to a 5 minute interval.

**Comment by johnhtodd** [comment]
Agreed that having custom polling intervals on certain devices or ports would be ideal, which might mitigate the issue somewhat. 

I don't care much about the RRD file generation interval; those are for "rough approximation" usage. If it's at 5 minutes, that's fine. As far as polling cycles: yes, clearly that is an issue, but distributed polling can handle that - http://docs.librenms.org/Extensions/Distributed-Poller/ - that page claims 50,000 ports on one installation.
