### ISSUE TITLE
Empty Alert Template Titles no longer allowed

### ISSUE THREAD

**Issue by esljaz** [librenms/librenms#13807]
### The problem

We've been using LibreNMS with empty alert titles for a while now. We prefer all information as part of the actual template, so we don't need the titles. So far we've been able to disable them, by just putting a space in there.

Since a recent XSS fix, this is now getting prevented: https://github.com/librenms/librenms/blame/41ddce63772cbb5f0df9bf9025e521fac394afe3/includes/html/forms/alert-templates.inc.php#L37-L38

![chrome_ApLgNy0ma0](https://user-images.githubusercontent.com/60260824/154841431-5b13b71d-6331-4179-95e1-b8bb3312f80c.png)

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 22.2.1
DB Schema | 2021_25_01_0129_isis_adjacencies_nullable (234)
PHP       | 7.4.28
Python    | 3.9.2
MySQL     | 10.5.12-MariaDB-0+deb11u1
RRDTool   | 1.7.2
SNMP      | 5.9
====================================
```

### What was the last working version of LibreNMS?

22.1.0

**Comment by PipoCanaja** [comment]
Seems that blade rendering is removing unnecessary spaces. And current test to define if blade-parsing failed is the result being empty. So currently, you need 1 character, and not a space. The ideal solution would be to include some kind of Blade exception handling if that is possible.

**Comment by ottorei** [comment]
We also wanted to have the most valuable information within the first lines of the alert for emails and other transports. It depends on where you sending these alerts but this kind of template works correctly for at least for emails, Telegram and PagerDuty:

![template_Example](https://user-images.githubusercontent.com/7031571/155234138-47127f09-1975-4bc5-819d-ccb49b5ba821.png)

**Comment by esljaz** [comment]
@murrant Thanks for your feedback. 
Is this a feature you'd generally be up for?

Knowing my way around Laravel, could you give me some hints on how you'd like to see this implemented?

**Comment by murrant** [comment]
@esljaz most complicated part is how do you handle cases that expect empty title means use default title?

Probably add a checkbox in the template dialog that disables the title... but I don't know what that would look like in the backend.
