### ISSUE TITLE
SNMP-traps integration

### ISSUE THREAD

**Issue by Alastair-VOIPUNLIMITED** [librenms/librenms#1380]
Hey guys,

Would be awesome if this were supported or re-looked at. We have a great number of devices that only support traps.

Was suggested I put this into an issue here from IRC.

Thank you

Alastair

**Comment by Alastair-VOIPUNLIMITED** [comment]
would be really neat too if there was ipv6 support on this too :)

**Comment by muahdib69** [comment]
Here's a me too ... 

It would be nice to have snmp-trap support, I especially would like it to be able to see which switch/port has excessive traffic in case someone creates a loop. 

f0o mentioned to use the syslog integration. I'l try if I can get something working with the net-snmptrapd listening for traps and then writing to the log ...

**Comment by Alastair-VOIPUNLIMITED** [comment]
any news on TRAP support? would anyone else find this useful? :)

**Comment by RichiH** [comment]
I would.

**Comment by SaaldjorMike** [comment]
:+1:

**Comment by blgarion** [comment]
Another person interested here, in case it helps push into that direction. Either way, awesome work to all of the guys helping at LibreNMS. I love it.

**Comment by samyscoub** [comment]
Hi, i look for the implementation of this feature inside LibreNMS.
What is, in your opinion, the best solution to add this feature ?
Add a new form into the menu or a new plugin to upload MIB and choose OID to manage this kind of SNMP Trap ?
To manage SNMP Tarps, LibrenMS currently uses php scripts for each receive trap (ie `linkUp.php`) sent by the `snmptrap.php` script.
Do you think that is it possible to improve this behaviour by using a dedicated table into the Mysql backend and add some methods into the libreNMS API to provision massively some SNMP Trap to parse and to manage through the alerting system ?

**Comment by gcoeugnet** [comment]
Hi, I just refer this issue in another one opened this morning cause I would like to implement more traps in LibreNMS. Regarding how LibreNMS is using it today, I already tested that sending a particular TRAP, for example coldStart, can update a new DB table. Then, writing a new rule can handle this table and send an alert as it works today for LinkUP/LinkDown.
 
- I use snmptrapd to receive traps and pass them to a snmptt handler with this configuration in /etc/snmp/snmptrapd.conf : 
`traphandle default /usr/sbin/snmptthandler`

- In snmptt, I use this configuration to call the snmptrap.php script of LibreNMS :
```
EVENT coldStart .1.3.6.1.6.3.1.1.5.1 "Status Events" Normal
FORMAT Device reinitialized (coldStart)
EXEC /opt/librenms/snmptrap.php "$A,coldStart,$1,$2,$3"
SDESC
A coldStart trap signifies that the SNMPv2 entity, acting
in an agent role, is reinitializing itself and that its
configuration may have been altered.
EDESC
```

- This then call a new trap script which update a field in a new table "test" : 
```
<?php

if (!$device) {
    exit;
}

log_event("SNMP Trap: coldStart" , $device, "", "");
 dbUpdate(array('value' => '1'), 'test', 'device_id=?',array($device['device_id']));
```

- Writting according rule can parse this table and send alerts easily.

So, the job would be to create a new table per constructor (for instance cisco_traps). This table would have four columns ('device_id','trap_name','value','number_received'). Trap_name would be for example 'coldStart'. Lots of code, of rules, but it works ! This is the more time consumer but simpler approach.

Another one would be to create a script that handle all of this dynamically when user upload for instance a new MIB in LibreNMS through the WebUI. But this require to create tables on the fly which is not a good idea I think. I don't succeed in designing a database schema which would handle undefined numbers (and constructor) of MIBs... Such generic table would allow not to create table on the fly and maybe to design only one rule to rule them all...

**Comment by laf** [comment]
This sounds like a good idea.

I actually like the dynamic approach - we might have the table thing covered in http://docs.librenms.org/Extensions/Component/ which is a generic table structure hopefully useable for something like this.

**Comment by samyscoub** [comment]
Hi Everyone, 

How do you think about managing a custom snmptt configuration inside the LibreNMS context which could dynamically populated by a custome form inside LibreNMS ? This can also be populated through the API to add SNMP Traps massively.

Your opinions ?

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-snmp-traps-integration/738
