### ISSUE TITLE
check_mk and dpkg plugin

### ISSUE THREAD

**Issue by winglessza** [librenms/librenms#13818]
### The problem

dpkg not showing pkg section on devices.

check_mk is installed aswell as the dpkg plugin on several ubuntu 20.04LTS servers, and I can see the dpkg info if i open a connection to the check_mk agent. The rpm plugin works perfectly on centos 7 servers, and shows the pkg section.

![image](https://user-images.githubusercontent.com/20675553/156131369-d872639c-67a3-40a6-80d7-27eabe40dc05.png)

### Output of ./validate.php

```txt
-bash-4.2$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 22.2.1-10-g86a504e
DB Schema | 2022_02_03_164059_increase_auth_id_length (235)
PHP       | 7.4.20
Python    | 3.6.8
MySQL     | 10.2.38-MariaDB
RRDTool   | 1.4.8
SNMP      | 5.7.2
====================================

[OK]    Composer Version: 2.2.7
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

**Comment by murrant** [comment]
Is the database (packages table) populated for that device?
What is the poller output?  `./poller.php -h <hostname> -d`

**Comment by murrant** [comment]
Code appears to process dpkg.  You might have to add some dump() statements to see what is going.  (side note that code is absolute rubbish to read)

**Comment by murrant** [comment]
No idea #13840 fixes your issue, but I could barely read the previous code.  Test it and see if it works.

**Comment by mwen** [comment]
I've had the same problem, and I can confirm that commit  #13840 is working really well. The missing device_id in the packages table appear, and the list of installed/removed/updated packages of two servers is finally updated after a couple of months of being stuck in the same state. The list of installed packages now also appear for my other Debian-based servers.

**Comment by murrant** [comment]
@mwen so #13840 is working perfectly for you? If so, I'll merge it.

**Comment by mwen** [comment]
@murrant Yes, #13840 can be merged,. And thanks for the bugfix, I really appeciate it.
