### ISSUE TITLE
Geocoding failing

### ISSUE THREAD

**Issue by bboy8012** [librenms/librenms#13814]
### The problem

Seems after the last update, geocoding is failing with this error for Google Maps

`production.ERROR: Geocoding failed. {"response":{"error_message":"Invalid request. Missing the 'address', 'components', 'latlng' or 'place_id' parameter.","results":[],"status":"INVALID_REQUEST"}}`

I have validated with other Mapping Engines and it's failing as well.

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 22.2.1-6-g703745d0e
DB Schema | 2022_02_03_164059_increase_auth_id_length (235)
PHP       | 8.0.15
Python    | 3.6.8
MySQL     | 10.3.28-MariaDB
RRDTool   | 1.7.0
SNMP      | 5.8
====================================

[OK]    Composer Version: 2.2.6
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

### Anything in the logs that might be useful for us?

```txt
[2022-02-24T11:53:15.853480-08:00] production.ERROR: Geocoding failed. {"response":{"error_message":"Invalid request. Missing the 'address', 'components', 'latlng' or 'place_id' parameter.","re                                              sults":[],"status":"INVALID_REQUEST"}}
/opt/librenms/discovery.php 1 2022-02-24 11:53:24 - 1 devices discovered in 9.829 secs
/opt/librenms/poller.php 1 2022-02-24 11:54:06 - 1 devices polled in 11.76 secs
[2022-02-24T11:55:44.470180-08:00] production.ERROR: Error discovering os module for 10.153.134.6. Argument 2 passed to App\ApiClients\NominatimApi::checkResponse() must be of the type array, n                                              ull given, called in /opt/librenms/app/ApiClients/GeocodingHelper.php on line 57
#0 /opt/librenms/app/ApiClients/GeocodingHelper.php(57): App\ApiClients\NominatimApi->checkResponse()
#1 /opt/librenms/app/Models/Location.php(130): App\ApiClients\NominatimApi->getCoordinates()
#2 /opt/librenms/app/Models/Location.php(96): App\Models\Location->fetchCoordinates()
#3 /opt/librenms/app/Models/Device.php(422): App\Models\Location->lookupCoordinates()
#4 /opt/librenms/LibreNMS/Modules/Os.php(116): App\Models\Device->setLocation()
#5 /opt/librenms/LibreNMS/Modules/Os.php(37): LibreNMS\Modules\Os->updateLocation()
#6 /opt/librenms/includes/discovery/os.inc.php(3): LibreNMS\Modules\Os->discover()
#7 /opt/librenms/includes/discovery/functions.inc.php(157): include('/opt/librenms/i...')
#8 /opt/librenms/discovery.php(118): discover_device()
#9 {main}
/opt/librenms/discovery.php 1 2022-02-24 11:55:52 - 1 devices discovered in 9.904 secs
/opt/librenms/poller.php 1 2022-02-24 11:59:07 - 1 devices polled in 12.57 secs
/opt/librenms/poller.php 1 2022-02-24 12:04:07 - 1 devices polled in 11.77 secs
[2022-02-24T12:04:41.330463-08:00] production.ERROR: Error discovering os module for 10.153.134.6. Argument 2 passed to App\ApiClients\MapquestApi::checkResponse() must be of the type array, null given, called in /opt/librenms/app/ApiClients/GeocodingHelper.php on line 57
#0 /opt/librenms/app/ApiClients/GeocodingHelper.php(57): App\ApiClients\MapquestApi->checkResponse()
#1 /opt/librenms/app/Models/Location.php(130): App\ApiClients\MapquestApi->getCoordinates()
#2 /opt/librenms/app/Models/Location.php(96): App\Models\Location->fetchCoordinates()
#3 /opt/librenms/app/Models/Device.php(422): App\Models\Location->lookupCoordinates()
#4 /opt/librenms/LibreNMS/Modules/Os.php(116): App\Models\Device->setLocation()
#5 /opt/librenms/LibreNMS/Modules/Os.php(37): LibreNMS\Modules\Os->updateLocation()
#6 /opt/librenms/includes/discovery/os.inc.php(3): LibreNMS\Modules\Os->discover()
#7 /opt/librenms/includes/discovery/functions.inc.php(157): include('/opt/librenms/i...')
#8 /opt/librenms/discovery.php(118): discover_device()
#9 {main}
```

**Comment by jonasblomq** [comment]
I'm experincing the same issue here.

I ran the discovery in debug mode and noticed a odd error refering to a failed DNS request, we are using openstreetmap as the location provider.

Yaml location data:
SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-Oqv' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' '-t' '15' 'udp:HOSTNAME:161' 'SNMPv2-MIB::sysLocation.0']
<ADDRESS REDACTED>

SQL[select * from `locations` where (`location` = ?) limit 1 ["<ADDRESS REDACTED>"] 0.3ms]

::query() failed: DNS request failed: The domain name referenced in the query does not exist.
OpenStreetMap geocode engine
Error discovering os module for 10.110.XX.YY. Argument 2 passed to App\ApiClients\NominatimApi::checkResponse() must be of the type array, null given, called in /opt/librenms/app/ApiClients/GeocodingHelper.php on line 57
#0 /opt/librenms/app/ApiClients/GeocodingHelper.php(57): App\ApiClients\NominatimApi->checkResponse()
#1 /opt/librenms/app/Models/Location.php(130): App\ApiClients\NominatimApi->getCoordinates()
#2 /opt/librenms/app/Models/Location.php(96): App\Models\Location->fetchCoordinates()
#3 /opt/librenms/app/Models/Device.php(422): App\Models\Location->lookupCoordinates()
#4 /opt/librenms/LibreNMS/Modules/Os.php(116): App\Models\Device->setLocation()
#5 /opt/librenms/LibreNMS/Modules/Os.php(37): LibreNMS\Modules\Os->updateLocation()
#6 /opt/librenms/includes/discovery/os.inc.php(3): LibreNMS\Modules\Os->discover()
#7 /opt/librenms/includes/discovery/functions.inc.php(157): include('/opt/librenms/i...')
#8 /opt/librenms/discovery.php(118): discover_device()
#9 {main}
SQL[insert into `eventlog` (`device_id`, `reference`, `type`, `datetime`, `severity`, `message`, `username`) values (?, ?, ?, ?, ?, ?, ?) [485,null,"discovery","2022-02-25 13:07:03",5,"Error discovering os module. Check log file for more details.",""] 0.6ms]





$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 22.2.1-7-gb8736fa75
DB Schema | 2022_02_03_164059_increase_auth_id_length (235)
PHP       | 7.4.26
Python    | 3.6.9
MySQL     | 10.5.9-MariaDB-1:10.5.9+maria~bionic
RRDTool   | 1.7.0
SNMP      | 5.7.3
====================================

**Comment by Jellyfrog** [comment]
after this line; https://github.com/librenms/librenms/blob/master/app/ApiClients/GeocodingHelper.php#L56
add: `dd($response, $response_data);

Rerun and post result

**Comment by jonasblomq** [comment]
Hi

Here's the requested output, I redacted the physical address..

Yaml location data:
SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-Oqv' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' '-t' '15' 'udp:HOSTNAME:161' 'SNMPv2-MIB::sysLocation.0']
<REDACTED> 1078, <REDACTED> <REDACTED>

SQL[select * from `locations` where (`location` = ?) limit 1 ["<REDACTED> 1078, <REDACTED> <REDACTED>"] 2ms]

::query() failed: DNS request failed: The domain name referenced in the query does not exist.
OpenStreetMap geocode engine
^ Illuminate\Http\Client\Response^ {#5871
  #response: GuzzleHttp\Psr7\Response^ {#5787
    -reasonPhrase: "OK"
    -statusCode: 200
    -headers: array:9 [
      "Server" => array:1 [
        0 => "nginx"
      ]
      "Date" => array:1 [
        0 => "Mon, 28 Feb 2022 07:03:37 GMT"
      ]
      "Content-Type" => array:1 [
        0 => "text/html"
      ]
      "Content-Length" => array:1 [
        0 => "780"
      ]
      "Last-Modified" => array:1 [
        0 => "Thu, 20 Jan 2022 17:10:28 GMT"
      ]
      "Connection" => array:1 [
        0 => "keep-alive"
      ]
      "Keep-Alive" => array:1 [
        0 => "timeout=20"
      ]
      "ETag" => array:1 [
        0 => ""61e99784-30c""
      ]
      "Accept-Ranges" => array:1 [
        0 => "bytes"
      ]
    ]
    -headerNames: array:9 [
      "server" => "Server"
      "date" => "Date"
      "content-type" => "Content-Type"
      "content-length" => "Content-Length"
      "last-modified" => "Last-Modified"
      "connection" => "Connection"
      "keep-alive" => "Keep-Alive"
      "etag" => "ETag"
      "accept-ranges" => "Accept-Ranges"
    ]
    -protocol: "1.1"
    -stream: GuzzleHttp\Psr7\Stream^ {#5786
      -stream: stream resource {@1523
        wrapper_type: "PHP"
        stream_type: "TEMP"
        mode: "w+b"
        unread_bytes: 0
        seekable: true
        uri: "php://temp"
        options: []
      }
      -size: null
      -seekable: true
      -readable: true
      -writable: true
      -uri: "php://temp"
      -customMetadata: []
    }
  }
  #decoded: null
  +"cookies": GuzzleHttp\Cookie\CookieJar^ {#5822
    -cookies: []
    -strictMode: false
  }
  +"transferStats": GuzzleHttp\TransferStats^ {#5794
    -request: GuzzleHttp\Psr7\Request^ {#5821
      -method: "GET"
      -requestTarget: null
      -uri: GuzzleHttp\Psr7\Uri^ {#5799
        -scheme: "https"
        -userInfo: ""
        -host: "nominatim.openstreetmap.org"
        -port: null
        -path: "/ui/search.html"
        -query: "query%5Bq%5D=<REDACTED>%201078%2C%20<REDACTED>%20<REDACTED>&query%5Bformat%5D=json&query%5Blimit%5D=1&headers%5BUser-Agent%5D=LibreNMS&headers%5BAccept%5D=application%2Fjson"
        -fragment: ""
        -composedComponents: "https://nominatim.openstreetmap.org/ui/search.html?query%5Bq%5D=<REDACTED>%201078%2C%20<REDACTED>%20<REDACTED>&query%5Bformat%5D=json&query%5Blimit%5D=1&headers%5BUser-Agent%5D=LibreNMS&headers%5BAccept%5D=application%2Fjson"
      }
      -headers: array:2 [
        "Host" => array:1 [
          0 => "nominatim.openstreetmap.org"
        ]
        "User-Agent" => array:1 [
          0 => "GuzzleHttp/7"
        ]
      ]
      -headerNames: array:2 [
        "host" => "Host"
        "user-agent" => "User-Agent"
      ]
      -protocol: "1.1"
      -stream: GuzzleHttp\Psr7\Stream^ {#5795
        -stream: stream resource {@1521
          wrapper_type: "PHP"
          stream_type: "TEMP"
          mode: "w+b"
          unread_bytes: 0
          seekable: true
          uri: "php://temp"
          options: []
        }
        -size: 0
        -seekable: true
        -readable: true
        -writable: true
        -uri: "php://temp"
        -customMetadata: []
      }
    }
    -response: GuzzleHttp\Psr7\Response^ {#5787}
    -transferTime: 0.048387
    -handlerStats: array:31 [
      "url" => "https://nominatim.openstreetmap.org/ui/search.html?query%5Bq%5D=<REDACTED>%201078%2C%20<REDACTED>%20<REDACTED>&query%5Bformat%5D=json&query%5Blimit%5D=1&headers%5BUser-Agent%5D=LibreNMS&headers%5BAccept%5D=application%2Fjson"
      "content_type" => "text/html"
      "http_code" => 200
      "header_size" => 255
      "request_size" => 263
      "filetime" => -1
      "ssl_verify_result" => 0
      "redirect_count" => 0
      "total_time" => 0.048387
      "namelookup_time" => 5.3E-5
      "connect_time" => 5.3E-5
      "pretransfer_time" => 0.000112
      "size_upload" => 0.0
      "size_download" => 780.0
      "speed_download" => 16250.0
      "speed_upload" => 0.0
      "download_content_length" => 780.0
      "upload_content_length" => -1.0
      "starttransfer_time" => 0.048272
      "redirect_time" => 0.0
      "redirect_url" => ""
      "primary_ip" => "184.104.226.109"
      "certinfo" => []
      "primary_port" => 443
      "local_ip" => "10.50.59.91"
      "local_port" => 54082
      "http_version" => 2
      "protocol" => 2
      "ssl_verifyresult" => 0
      "scheme" => "HTTPS"
      "appconnect_time" => 5.4E-5
    ]
    -handlerErrorData: 0
  }
}
^ null

**Comment by bboy8012** [comment]
Here also is my redacted results using discovery in debug mode from the gui.

`LibreNMS Discovery

SQL[select `migration` from `migrations` order by `id` desc limit 1 [] 0.47ms] 
  

SQL[select count(*) as aggregate from `migrations` limit 1 [] 0.35ms] 
  

SQL[select version() [] 0.35ms] 
  

===================================
Version info:
Commit SHA: 86a504e675ebe76392af914b53bf38add658de84
Commit Date: 1645955793
DB Schema: 2022_02_03_164059_increase_auth_id_length (235)
PHP: 8.0.15
MySQL: 10.3.28-MariaDB
RRDTool: 1.7.0
SNMP: 5.8
==================================DEBUG!

Updating os_def.cache  

SQL[SELECT * FROM `devices` WHERE disabled = 0 AND `hostname` LIKE '10.153.144.6' ORDER BY device_id DESC [] 0.71ms] 
  

SQL[select * from `devices` where `device_id` = ? limit 1 [42] 0.47ms] 
  

SQL[select * from `devices_attribs` where `devices_attribs`.`device_id` = ? and `devices_attribs`.`device_id` is not null [42] 0.3ms] 
  

10.153.144.6 42 panos 
[FPING] '/usr/sbin/fping' '-e' '-q' '-c' '1' '-p' '300' '-t' '300' '-O' '0' '10.153.144.6'
  

response: xmt/rcv/%loss = 1/1/0%, min/avg/max = 46.1/46.1/46.1  

SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/paloaltonetworks' '-v2c' '-c' 'COMMUNITY' '-OQXUte' 'udp:HOSTNAME:161' 'SNMPv2-MIB::sysObjectID.0']  

SNMPv2-MIB::sysObjectID.0 = SNMPv2-SMI::enterprises.254*
  

  

Modules status: Global+  

OS  
Device  

#### Load disco module core ####

Attempting to initialize OS: panos  

OS initialized: LibreNMS\OS\Panos  

SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/paloaltonetworks' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-On' 'udp:HOSTNAME:161' 'SNMPv2-MIB::sysObjectID.0' 'SNMPv2-MIB::sysDescr.0' 'SNMPv2-MIB::sysName.0']  

.*.*.0 = .*.4.1.254*
.*.*.0 = Palo Alto Networks VM-Series firewall
.*.*.0 = REDACTED
  
  

| Palo Alto Networks VM-Series firewall | .1.3.6.1.4.1.25461.2.3.29 | 
  

OS: PanOS (panos)

Attempting to initialize OS: panos  

OS initialized: LibreNMS\OS\Panos  


>> Runtime for discovery module 'core': 0.0830 seconds with -77632 bytes
>> SNMP: [1/0.07s] MySQL: [0/0.00s] RRD: [0/0.00s]  

#### Unload disco module core ####


Modules status: Global+  
OS  

Device  

#### Load disco module os ####

Yaml location data:  
SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-Oqv' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/paloaltonetworks' 'udp:HOSTNAME:161' 'SNMPv2-MIB::sysLocation.0']

REDACTED  
  

SQL[select * from `locations` where (`location` = ?) limit 1 ["#####################################"] 0.49ms] 
  

::query() failed: DNS request failed: The domain name referenced in the query does not exist.  

Google Maps geocode engine  

Illuminate\Http\Client\Response {#1497
  #response: GuzzleHttp\Psr7\Response {#1550
    -reasonPhrase: "Bad Request"
    -statusCode: 400
    -headers: array:14 [
      "Content-Type" => array:1 [
        0 => "application/json; charset=UTF-8"
      ]
      "Date" => array:1 [
        0 => "Mon, 28 Feb 2022 18:15:14 GMT"
      ]
      "Pragma" => array:1 [
        0 => "no-cache"
      ]
      "Expires" => array:1 [
        0 => "Fri, 01 Jan 1990 00:00:00 GMT"
      ]
      "Cache-Control" => array:1 [
        0 => "no-cache, must-revalidate"
      ]
      "Access-Control-Allow-Origin" => array:1 [
        0 => "*"
      ]
      "Server" => array:1 [
        0 => "mafe"
      ]
      "X-XSS-Protection" => array:1 [
        0 => "0"
      ]
      "X-Frame-Options" => array:1 [
        0 => "SAMEORIGIN"
      ]
      "Server-Timing" => array:1 [
        0 => "gfet4t7; dur=2"
      ]
      "Alt-Svc" => array:1 [
        0 => "h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43""
      ]
      "Accept-Ranges" => array:1 [
        0 => "none"
      ]
      "Vary" => array:1 [
        0 => "Accept-Encoding"
      ]
      "Transfer-Encoding" => array:1 [
        0 => "chunked"
      ]
    ]
    -headerNames: array:14 [
      "content-type" => "Content-Type"
      "date" => "Date"
      "pragma" => "Pragma"
      "expires" => "Expires"
      "cache-control" => "Cache-Control"
      "access-control-allow-origin" => "Access-Control-Allow-Origin"
      "server" => "Server"
      "x-xss-protection" => "X-XSS-Protection"
      "x-frame-options" => "X-Frame-Options"
      "server-timing" => "Server-Timing"
      "alt-svc" => "Alt-Svc"
      "accept-ranges" => "Accept-Ranges"
      "vary" => "Vary"
      "transfer-encoding" => "Transfer-Encoding"
    ]
    -protocol: "1.1"
    -stream: GuzzleHttp\Psr7\Stream {#1549
      -stream: stream resource {@1497
        wrapper_type: "PHP"
        stream_type: "TEMP"
        mode: "w+b"
        unread_bytes: 0
        seekable: true
        uri: "php://temp"
        options: []
      }
      -size: null
      -seekable: true
      -readable: true
      -writable: true
      -uri: "php://temp"
      -customMetadata: []
    }
  }
  #decoded: array:3 [
    "error_message" => "Invalid request. Missing the 'address', 'components', 'latlng' or 'place_id' parameter."
    "results" => []
    "status" => "INVALID_REQUEST"
  ]
  +"cookies": GuzzleHttp\Cookie\CookieJar {#1530
    -cookies: []
    -strictMode: false
  }
  +"transferStats": GuzzleHttp\TransferStats {#1551
    -request: GuzzleHttp\Psr7\Request {#1537
      -method: "GET"
      -requestTarget: null
      -uri: GuzzleHttp\Psr7\Uri {#1534
        -scheme: "https"
        -userInfo: ""
        -host: "maps.googleapis.com"
        -port: null
        -path: "/maps/api/geocode/json"
        -query: "query%5Bkey%5D=#################20&query%5Baddress%5D=####%20XXXX%20XXXX%20XXXX%2C%20XXXX%2C%20XX%20XXXXX"
        -fragment: ""
        -composedComponents: "https://maps.googleapis.com/maps/api/geocode/json?query%5Bkey%5D=#################20&query%5Baddress%5D=####%20XXXX%20XXXX%20XXXX%2C%20XXXX%2C%20XX%20XXXXX"
      }
      -headers: array:2 [

        "User-Agent" => array:1 [
          0 => "GuzzleHttp/7"
        ]
        "Host" => array:1 [
          0 => "maps.googleapis.com"
        ]
      ]
      -headerNames: array:2 [
        "user-agent" => "User-Agent"
        "host" => "Host"
      ]
      -protocol: "1.1"
      -stream: GuzzleHttp\Psr7\Stream {#1536

        -stream: stream resource {@1488
          wrapper_type: "PHP"

          stream_type: "TEMP"
          mode: "w+b"

          unread_bytes: 0
          seekable: true

          uri: "php://temp"

          options: []
        }

        -size: 0
        -seekable: true

        -readable: true
        -writable: true

        -uri: "php://temp"

        -customMetadata: []
      }
    }

    -response: GuzzleHttp\Psr7\Response {#1550}
    -transferTime: 0.057548
    -handlerStats: array:38 [
      "url" => "https://maps.googleapis.com/maps/api/geocode/json?query%5Bkey%5D=#################20&query%5Baddress%5D=####%20XXXX%20XXXX%20XXXX%2C%20XXXX%2C%20XX%20XXXXX"
      "content_type" => "application/json; charset=UTF-8"
      "http_code" => 400
      "header_size" => 584
      "request_size" => 225
      "filetime" => -1
      "ssl_verify_result" => 0
      "redirect_count" => 0
      "total_time" => 0.057548
      "namelookup_time" => 0.004125
      "connect_time" => 0.007252
      "pretransfer_time" => 0.02652
      "size_upload" => 0.0
      "size_download" => 167.0
      "speed_download" => 2929.0
      "speed_upload" => 0.0
      "download_content_length" => -1.0
      "upload_content_length" => -1.0
      "starttransfer_time" => 0.056947
      "redirect_time" => 0.0
      "redirect_url" => ""
      "primary_ip" => "142.250.72.138"
      "certinfo" => []
      "primary_port" => 443
      "local_ip" => "10.130.2.4"
      "local_port" => 52498
      "http_version" => 2
      "protocol" => 2
      "ssl_verifyresult" => 0
      "scheme" => "HTTPS"
      "appconnect_time_us" => 26478
      "connect_time_us" => 7252
      "namelookup_time_us" => 4125
      "pretransfer_time_us" => 26520
      "redirect_time_us" => 0
      "starttransfer_time_us" => 56947
      "total_time_us" => 57548
      "appconnect_time" => 0.026478
    ]
    -handlerErrorData: 0
  }
}
array:3 [
  "error_message" => "Invalid request. Missing the 'address', 'components', 'latlng' or 'place_id' parameter."
  "results" => []
  "status" => "INVALID_REQUEST"
]`
