### ISSUE TITLE
Enabling Prometheus Pushgateway slows down polling to zero functionality

### ISSUE THREAD

**Issue by vincnt** [librenms/librenms#13826]
### The problem

# Summary:
Enabling Pushgateway causes polling to grind to a stop, most likely due to the post requests blocking the thread execution.

![image](https://user-images.githubusercontent.com/11012155/156622606-5475102a-3464-47aa-8e82-6e9d92ea58d1.png)

# Steps I've taken:
In /opt/librenms/Data/Store/Prometheus.php , I've timed the time taken to sent the post request to my pushgateway instance.
```
$now = time();
$result = $this->client->request('POST', $promurl, $options);
$time_diff = time() - $now;
Log::info("Time for request " . $time_diff . " seconds.");
```
Then running `./poller.php -h all` , I get the following:
```
LibreNMS Poller
Starting polling run:

Hostname:  ...
Device ID:   ...
OS:          ...
Resolved IP: ...

17:56:51 Time for request 6 seconds.  

#### Load poller module core ####
17:56:58 Time for request 7 seconds.  
Uptime:  2 years 302 days 9 hours 21 minutes 49 seconds

>> Runtime for poller module 'core': 6.2953 seconds with 5064 bytes
>> SNMP: [2/0.05s] MySQL: [1/0.01s] Prometheus: [1/6.24s] RRD: [1/0.00s]  
#### Unload poller module core ####

17:57:05 Time for request 7 seconds.  
Module [ unix-agent ] disabled globally.


#### Load poller module os ####
Location: ...
Hardware: ...
OS Version: ...
OS Features: ...
Serial: ...

>> Runtime for poller module 'os': 0.0043 seconds with 44376 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.01s] Prometheus: [1/7.29s] RRD: [1/0.00s]  
#### Unload poller module os ####

17:57:13 Time for request 8 seconds.  

#### Load poller module availability ####
Availability: 
17:57:20 Time for request 7 seconds.  
1 day : 95.273%
17:57:28 Time for request 8 seconds.  
7 days : -5577.242%
17:57:36 Time for request 8 seconds.  
30 days : -6375.712%

```
Each requests take about 8 seconds, significantly slowing down the poller. 

I have about 2000 unique groups with around 8 values each that need to be pushed every minute. I've tried batching
metrics into a larger group and doing a PUT to <url>/job/<job_id> , however I realised this causes the previous push's data to be erased as they both fall under the grouping `job:'<job>', instance=''`. 

I've struggled to make the requests asynchronous / non-waiting using php. Some online recommendations suggest using `exec (curl ...)` but I would want to avoid going down that route. 

I've also tried setting the timeout on the guzzle post request to 1 second - which partially works, but still slows down the polling significantly to about 50% the original volume.

# Possible solutions
Anyone have any idea if it would be possible to spin up a thread pool and assign these requests to the pool such that it does not block the main polling threads?

An alternative would be for me to write the data to a file, and start a separate web server which reads from the files and behaves like a Prometheus exporter. 

Would appreciate any suggestions for debugging further or fixing this. 

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 22.2.1-10-g86a504e
DB Schema | 2022_02_03_164059_increase_auth_id_length (235)
PHP       | 7.4.11
Python    | 3.6.8
MySQL     | 10.2.33-MariaDB
RRDTool   | 1.7.2
SNMP      | 5.7.2
====================================

[OK]    Composer Version: 2.2.7
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
```

### Anything in the logs that might be useful for us?

```txt
/opt/librenms/poller.php 78 2022-03-03 18:16:20 - 1 devices polled in 51.70 secs
/opt/librenms/poller.php 21 2022-03-03 18:16:23 - 1 devices polled in 43.17 secs
/opt/librenms/discovery.php 293 2022-03-03 18:16:25 - 1 devices discovered in 117.0 secs
/opt/librenms/poller.php 289 2022-03-03 18:16:26 - 1 devices polled in 118.0 secs
/opt/librenms/poller.php 144 2022-03-03 18:16:35 - 1 devices polled in 186.5 secs
/opt/librenms/poller.php 218 2022-03-03 18:16:39 - 1 devices polled in 83.64 secs
/opt/librenms/discovery.php 292 2022-03-03 18:16:39 - 1 devices discovered in 123.3 secs
/opt/librenms/poller.php 51 2022-03-03 18:16:39 - 1 devices polled in 204.2 secs
/opt/librenms/poller.php 318 2022-03-03 18:16:40 - 1 devices polled in 87.66 secs
```
```

**Comment by tr2vil** [comment]
We've been solved this issue by using graphite exporter. 
librenms write to the exporter, If you set the exporter you can get the metrics.

**Comment by washcroft** [comment]
@tr2vil interesting... did you create a mapping file you could share, or is one not required?
