### ISSUE TITLE
22.2.2 LibreNMS/Util/Version.php was not bumped

### ISSUE THREAD

**Issue by ryanmerolle** [librenms/librenms#13850]
### The problem

Any installs of 22.2.2 show the incorrect version of 22.2.1 because the file was never bumped.

You can see from https://github.com/librenms/librenms/compare/22.2.0...22.2.2

This is such a minor issue for which I only realized when I upgraded my container image.

### Output of ./validate.php

```txt
N/A
```

### What was the last working version of LibreNMS?

22.2.1

### Anything in the logs that might be useful for us?

```txt
N/A
```

**Comment by murrant** [comment]
22.2.2 will forever show the wrong version in the about.  I don't think it is a worthwhile version bump to correct 22.2.3.  22.3.0 will be out soon.

**Comment by ryanmerolle** [comment]
Yea totally fair.  It was just an observation.  Worst case someone searches for the issue and finds the answer.
