### ISSUE TITLE
Ports list export to CSV empty

### ISSUE THREAD

**Issue by aarchijs** [librenms/librenms#13856]
### The problem

When I select specific device from this list (1) or by specific description (2) then "export CSV" function works. 
(1)
![image](https://user-images.githubusercontent.com/17215746/158762035-7e99e9e6-750c-48bc-9b5d-89ae3e012982.png)

(2)
![image](https://user-images.githubusercontent.com/17215746/158762797-3b250140-452b-4a87-849d-9be69753d72b.png)

But when I do it through hostname search when I want to find specific device"Export CSV" returns empty file
(3)
![image](https://user-images.githubusercontent.com/17215746/158762264-7f093dc2-567c-4a6b-a441-2df6c4437b2e.png)

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 22.2.2
DB Schema | 2021_12_02_113537_ports_stp_designated_cost_change_to_int (234)
PHP       | 7.4.3
Python    | 3.8.10
MySQL     | 10.3.34-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | 5.8
====================================

[OK]    Composer Version: 2.2.9
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]: 
        You can fix this with ./scripts/github-remove
        Modified Files:
         rrd/.gitignore
```

**Comment by cliffalbert** [comment]
I have the exact same problem on one of my installs:

====================================
Component | Version
--------- | -------
LibreNMS  | 22.3.0-24-g75ba74fe5
DB Schema | 2022_02_03_164059_increase_auth_id_length (235)
PHP       | 7.4.28
Python    | 3.9.2
MySQL     | 10.5.12-MariaDB-0+deb11u1
RRDTool   | 1.7.2
SNMP      | 5.9
====================================

[OK]    Composer Version: 2.3.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct

It however works on another install I have:

====================================
Component | Version
--------- | -------
LibreNMS  | 22.3.0-24-g75ba74fe5
DB Schema | 2022_02_03_164059_increase_auth_id_length (235)
PHP       | 7.4.3
Python    | 3.8.10
MySQL     | 8.0.28-0ubuntu0.20.04.3
RRDTool   | 1.7.2
SNMP      | 5.8
====================================

[OK]    Composer Version: 2.3.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct

**Comment by murrant** [comment]
Hmm, the csv export doesn't work at all for me.   It needs to be re-written.  Probably should just delete it for now.

**Comment by electrocret** [comment]
Interesting, the port export to CSV works for me, with the exception of the filters I recently added (portgroup and devicegroup). 

I did some poking around in the code (/html/csv.php), and it doesn't look like it'll be a monumental task to modernize this, but I'm also not the most versed with PHP or Laravel. 

The current code appears to use the report value to determine which report file to run to build the query, then builds the CSV file from the query's output.

To modernize it, we could route it into the table builder for the query, then we'd just have to convert the JSON to CSV. 

Am I on the right track? @murrant

**Comment by murrant** [comment]
@electrocret you could probably add it to the table builder generically so it isn't specific to a table.  Then add a resource to transform the table for csv: https://laravel.com/docs/9.x/eloquent-resources and use laravel-excel to build the file.

**Comment by murrant** [comment]
Or maybe you don't need the resource at all and just add named exports using laravel-excel

**Comment by electrocret** [comment]
I'll look into possibly taking a stab at this whenever I have time. However I feel this might be beyond my skills, so if there's someone else who'd be more comfortable,  have at it.

**Comment by laf** [comment]
This looks to be working for me, closing for now until someone reports back.
