### ISSUE TITLE
Mini Graphs are broken

### ISSUE THREAD

**Issue by steveneppler** [librenms/librenms#13859]
### The problem

I've noticed that mini graphs have been broken in my install for a while. I haven't been able to determine why.  I have tested Chrome, Edge, Safari, and Firefox on macOS.

To reproduce, go to 'Ports' on any device and click on any of the 'Mini' links.  This is can also be reproduced on the demo LibreNMS site (https://demo.librenms.org/device/device=59/tab=ports/view=minigraphs/graph=upkts/ for example).  Screenshot of demo site attached.
<img width="1004" alt="Screen Shot 2022-03-18 at 8 40 31 AM" src="https://user-images.githubusercontent.com/24479922/159023856-6552104a-e011-4d2c-aaf8-3d4bfafe65e0.png">

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 22.3.0
DB Schema | 2022_02_03_164059_increase_auth_id_length (235)
PHP       | 7.4.3
Python    | 3.8.10
MySQL     | 10.3.34-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | 5.8
====================================

[OK]    Composer Version: 2.2.7
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

**Comment by ottorei** [comment]
Can confirm this issue on my installation as well.

**Comment by ottorei** [comment]
Some old legacy code was removed a while ago. I suspect this has something to do with this issue. I suspect some of these lines in the if-statement are the key to resolving this https://github.com/librenms/librenms/blob/02b5ef797b36cf872a6d0d0c79ef5dd941ddf77e/includes/html/functions.inc.php#L380

**Comment by murrant** [comment]
The actual problem was they didn't include the graphs LOL
It just got deleted in one of the code changes.  I think it was because it was really far off to the right and it wasn't seen.
