### ISSUE TITLE
Total traffic of a VM is displayed incorrectly

### ISSUE THREAD

**Issue by Maxo112** [librenms/librenms#13865]
### The problem

 I can no longer see the total traffic in gigabytes (GB) but only the network performance in Mbit.

I would like to see the used traffic again and not the minimum and maximum network performance that was achieved.

If I click on the individual Ethernet interfaces I can then see the traffic of the interface but I have partly 4 interfaces where I just want to see the traffic of all interfaces and do not want to calculate everything individually together.

![image](https://user-images.githubusercontent.com/38752564/159275663-9c94b42c-a84a-4a67-9c80-ddb790c3ba6f.png)

![image](https://user-images.githubusercontent.com/38752564/159275696-7e0395ee-3b64-4fd1-af30-24a5a515b1d3.png)

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 22.3.0-2-g8ad389f16
DB Schema | 2022_02_03_164059_increase_auth_id_length (235)
PHP       | 7.4.13
Python    | 3.6.9
MySQL     | 10.5.15-MariaDB-1:10.5.15+maria~bionic
RRDTool   | 1.7.0
SNMP      | 5.7.3
====================================

[OK]    Composer Version: 2.2.9
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

**Comment by Maxo112** [comment]
@kkrumm1  It's a bug not an Support Request. A few versions before that version it displayed correctly.

**Comment by murrant** [comment]
> A few versions before that version it displayed correctly.

Indeed and nothing has changed in that code and it is working for everyone else, so what changed in your system?
