### ISSUE TITLE
API add_device with snmp_disable set to true not working

### ISSUE THREAD

**Issue by jpobeda** [librenms/librenms#13873]
### The problem

Hi there,

I'm having an issue with the API, specifically with "add_device" and "ping-only". 
It was working fine but some time between version 21.10.2 and 22.3.x got broken.

```bash
 curl -X POST -d '{"hostname":"newserver.domain.com","snmp_disable": true}' -H 'X-Auth-Token: THEMAGICTOKEN' https://librenms.domain.com/api/v0/devices
```
```json
{
    "status": "error",
    "message": "Already have device newserver.domain.com due to duplicate sysName: "
}
```

I ran a select against devices table and the device doesn't exist. Not sure what's going on, adding devices with snmp seems to be working ok tho.

Let me know if you need further details.

### Output of ./validate.php

```txt
[librenms@server ~]$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 22.3.0
DB Schema | 2022_02_03_164059_increase_auth_id_length (235)
PHP       | 7.3.29
Python    | 3.6.8
MySQL     | 10.5.13-MariaDB
RRDTool   | 1.4.8
SNMP      | 5.7.2
====================================

[OK]    Composer Version: 2.1.6
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

### What was the last working version of LibreNMS?

21.10.2

**Comment by murrant** [comment]
Already fixed by #13870

**Comment by jpobeda** [comment]
Awesome, I just tested it 

```bash
./scripts/github-apply 13870
```

I now get a good result. @murrant When is this likely going to be merged?

**Comment by murrant** [comment]
I should probably send a separate PR for the fix so it can be merged right away, but I don't know if I'll have any time to get that done.
