### ISSUE TITLE
Issue with drawing graphs of GPON on Huawei devices

### ISSUE THREAD

**Issue by mWachu** [librenms/librenms#13934]
### The problem

Hello,

I have encountered a inaccessibility of GPON graphs on Huawei MA5603T device. 

My NMS instance is up to date, i tried everything from my end and could not be able to recover it. 

![Screen Shot 2022-04-20 at 19 09 21](https://user-images.githubusercontent.com/77017007/164285523-4794f257-e736-431d-ac6a-f3589abba10c.png)

I can see that graphs were displayed correctly in the past:

![Screen Shot 2022-04-20 at 19 10 39](https://user-images.githubusercontent.com/77017007/164285745-108f4019-5a6d-40c2-8de9-cb2e1740c9dd.png)

I suspect it may have been damaged by one of daily updates, as i have found one article with the same issue from the same timestamp:
https://community.librenms.org/t/huawei-olt-smartax-gpon-port-graphs/17517

### Output of ./validate.php

```txt
bash-4.2$ ./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 22.3.0-51-gcc6112b
DB Schema | 2022_04_08_085504_isis_adjacencies_table_add_index (236)
PHP       | 7.3.18
Python    | 3.6.8
MySQL     | 8.0.19
RRDTool   | 1.4.8
SNMP      | 5.7.2
====================================

[OK]    Composer Version: 2.3.5
[OK]    Dependencies up-to-date.
[WARN]  Debug enabled.  This is a security risk.
[OK]    Database connection successful
[OK]    Database schema correct
```

### Device info

Huawei MA5603T

### Discovery output

```txt
Pasting as URL because output is too long: https://pastebin.com/dGf0uaxx
```

### Poller output

```txt
Pasting as URL because output is too long: 
https://pastebin.com/8KBVWjzD
```

**Comment by murrant** [comment]
Thanks for the debug output...

Looking at GPON 0/0/3:
ifOctets_prev = "18446744073709551615"
ifOctets "18446744073709551615"

You'll notice that counter has not changed and in fact, that is MAX_INT 64bit


    'ifName' => 'GPON 0/0/3',
    'ifInMulticastPkts' => '4294967295',
    'ifInBroadcastPkts' => '4294967295',
    'ifOutMulticastPkts' => '4294967295',
    'ifOutBroadcastPkts' => '4294967295',
    'ifHCInOctets' => '18446744073709551615',
    'ifHCInUcastPkts' => '18446744073709551615',
    'ifHCInMulticastPkts' => '18446744073709551615',
    'ifHCInBroadcastPkts' => '18446744073709551615',
    'ifHCOutOctets' => '18446744073709551615',
    'ifHCOutUcastPkts' => '18446744073709551615',
    'ifHCOutMulticastPkts' => '18446744073709551615',
    'ifHCOutBroadcastPkts' => '18446744073709551615',
    
Looking at all those, they are the max 32 bit and 64 bit values for the respective 32bit and 64bit counters.

This is a device issue.  There is no way for LibreNMS to fix it.
