### ISSUE TITLE
 There is an error between billing bandwidth graph and MySQL data. 

### ISSUE THREAD

**Issue by liys888** [librenms/librenms#13946]
### The problem

![图片](https://user-images.githubusercontent.com/104246383/164879535-d9d30a2d-b97b-47a6-927c-aeed341b2528.png)

max:27.60M
 
2 | 2022-04-23 13:05:03 |    301 |     108497 |      40215 |      68282 |
      2 | 2022-04-23 13:10:03 |    300 | 1057132342 |    3306611 | 1053825731 |
    2 | 2022-04-23 13:15:02 |    299 |     109737 |      41275 |      68462 |

Replace 1053825731 with bandwidth：

1053825731 / 5 / 1000 / 1000 = 25.129m, which is different from Max shown in the figure

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 22.4.0-5-gd4479e1
DB Schema | 2022_04_08_085504_isis_adjacencies_table_add_index (236)
PHP       | 7.3.33
Python    | 3.6.8
MySQL     | 10.5.15-MariaDB
RRDTool   | 1.4.8
SNMP      | 5.7.2
====================================

[OK]    Composer Version: 2.3.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[FAIL]  Python3 module issue found: 'Required packages: ['PyMySQL!=1.0.0', 'python-dotenv', 'redis>=3.0', 'setuptools', 'psutil>=5.6.0', 'command_runner>=1.3.0']
Package not found: The 'command_runner>=1.3.0' distribution was not found and is required by the application
'
        [FIX]: 
        pip3 install -r /opt/librenms/requirements.txt
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]: 
        You can fix this with ./scripts/github-remove
        Modified Files:
         bootstrap/cache/.gitignore
         logs/.gitignore
         rrd/.gitignore
         storage/app/.gitignore
         storage/app/public/.gitignore
         storage/debugbar/.gitignore
         storage/framework/cache/.gitignore
         storage/framework/cache/data/.gitignore
         storage/framework/sessions/.gitignore
         storage/framework/testing/.gitignore
         storage/framework/views/.gitignore
         storage/logs/.gitignore
```

**Comment by murrant** [comment]
You are not displaying a billing graph here, this is a port polling graph.  Those are averaged over time.

**Comment by liys888** [comment]
It is recommended to read the bill in MySQL from the figure in bill_data drawing. If the RRD chart is inconsistent with the data, the customer will question it.
This is more perfect.

**Comment by liys888** [comment]
It is suggested to add the billing model: the fourth (the fourth value in the order of daily peak), and the monthly average (the average of daily peak)

**Comment by murrant** [comment]
Use the billing "Accurate" graphs there might even be a config setting to hide the port graphs.   If you cannot, I suggest you explain to the customer that those are just quick graphs that are averaged and consolidated.
