### ISSUE TITLE
install document is not clear

### ISSUE THREAD

**Issue by fowlmouse** [librenms/librenms#13964]
### The problem

when following below step then report issue:
Sometime when there is a proxy used to gain internet access, the above script may fail. The workaround is to install the composer package manually. For a global installation:

wget https://getcomposer.org/composer-stable.phar
mv composer-stable.phar /usr/bin/composer
chmod +x /usr/bin/composer

issue report message: mv: replace '/usr/bin/composer', overriding mode 0755 (rwxr-xr-x)?

### Output of ./validate.php

```txt
na
```

### Anything in the logs that might be useful for us?

```txt
na
```

**Comment by kkrumm1** [comment]
doc changes are welcome you can submit changes in the docs.
