### ISSUE TITLE
The VLANs tab on my switches are empty

### ISSUE THREAD

**Issue by Lilooman** [librenms/librenms#13962]
### The problem

Hello everyone,

My LibreNMS is installed on Docker.
I just noticed that the VLANs tab on my switches now displays nothing...

After a bit of troubleshooting, I've seen that the Discovery of the VLAN module ends with this:
![image](https://user-images.githubusercontent.com/57174673/166205748-8cb1d5c3-2550-4e21-926f-2b8ca01ebfd6.png)

Just so you know, the Ports module is disabled on this device (HPE 5130). On other switches (HPE 5700) on which the Ports module is enabled, I get a different output but nothing in the VLANs tab either.

_See the two debug outputs below._

Thanks in advance for your help.

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 22.3.0
DB Schema | 2022_02_03_164059_increase_auth_id_length (235)
PHP       | 7.4.28
Python    | 3.9.7
MySQL     | 10.4.24-MariaDB-1:10.4.24+maria~focal
RRDTool   | 1.7.2
SNMP      | 5.9.1
====================================

[OK]    Installed from the official Docker image; no Composer required
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[WARN]  Updates are managed through the official Docker image
```

### Anything in the logs that might be useful for us?

```txt
Here are the pastebins of the discovery of the VLANs module.

HPE 5130: https://pastebin.com/YXfq2sn8
HPE 5700: https://pastebin.com/bP0XTGpL
```

**Comment by murrant** [comment]
`Exitcode: 2 ["Error in packet.\nReason: (tooBig) Response message would have been too large.\n"] `  

https://docs.librenms.org/Support/SNMP-Configuration-Examples/#comware
