### ISSUE TITLE
Add Meraki OS detection

### ISSUE THREAD

**Issue by willjones** [librenms/librenms#1396]
I'd like to add some basic support to detect and classify Meraki hardware broadly speaking the MX/MR/MS line of products.

Meraki don't expose very much via SNMP when probing the devices directly but they do give enough information to determine the hardware platform and some basic interface stats.

**Comment by Rosiak** [comment]
Can this be closed now, since #1402 has been merged? :)

**Comment by laf** [comment]
Thanks @Rosiak
