### ISSUE TITLE
how to enable API ?

### ISSUE THREAD

**Issue by luca-m** [librenms/librenms#1397]
Cant accesso api interface __even__ in demo server:

    curl -H 'X-Auth-Token: f2567fbe1805386bcfaa0d57c9f83551' https://demo.librenms.org/api/v0/devices

**Comment by luca-m** [comment]
Its a http rewrite rule issue..

**Comment by laf** [comment]
I'm assuming you aren't using apache?

**Comment by luca-m** [comment]
exactly, with lighttpd I had to disable the rewrite rules, making the rest
of the web ui not working.. I am not a lighttpd expert, maybe there is a
better way to tune up its rewrite rules.

On 6 July 2015 at 18:33, Neil Lathwood <notifications@github.com> wrote:

> I'm assuming you aren't using apache?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/librenms/librenms/issues/1397#issuecomment-118918572>.
>



-- 
-lm

**Comment by laf** [comment]
Definitely needs a rule, I'm not expert on lighttpd either and don't even have it installed. Let's see if someone else can come up with a rule.

**Comment by luca-m** [comment]
I'll try to findout something..
Il giorno 08/lug/2015 01.36, "Neil Lathwood" <notifications@github.com> ha
scritto:

**Comment by laf** [comment]
@luca-m 

Would something like this work:

```bash
server.document-root = "/opt/librenms/html"
 url.rewrite-once = (
   "^/api/v0/(.*)" => "/api/v0/$0",
   "^/(.*)\.(png|css|jpg|gif|php)$" => "/$0",
   "^/([a-z|0-9\-]+)/(.+)/(.+)/(.+)/(.+)/(.+)/(.+)/(.+)/(.+)/(.+)/(.+)/" => "/?page=$1&$2&$3&$4&$5&$6&$7&$8&$9&$10",
   "^/([a-z|0-9\-]+)/(.+)/(.+)/(.+)/(.+)/(.+)/(.+)/(.+)/(.+)/(.+)/" => "/?page=$1&$2&$3&$4&$5&$6&$7&$8&$9",
   "^/([a-z|0-9\-]+)/(.+)/(.+)/(.+)/(.+)/(.+)/(.+)/(.+)/(.+)/" => "/?page=$1&$2&$3&$4&$5&$6&$7&$8",
   "^/([a-z|0-9\-]+)/(.+)/(.+)/(.+)/(.+)/(.+)/(.+)/(.+)/" => "/?page=$1&$2&$3&$4&$5&$6&$7",
   "^/([a-z|0-9\-]+)/(.+)/(.+)/(.+)/(.+)/(.+)/(.+)/" => "/?page=$1&$2&$3&$4&$5&$6",
   "^/([a-z|0-9\-]+)/(.+)/(.+)/(.+)/(.+)/" => "/?page=$1&$2&$3&$4&$5",
   "^/([a-z|0-9\-]+)/(.+)/(.+)/(.+)/" => "/?page=$1&$2&$3&$4",
   "^/([a-z|0-9\-]+)/(.+)/(.+)/" => "/?page=$1&$2&$3",
   "^/([a-z|0-9\-]+)/(.+)/" => "/?page=$1&$2",
   "^/([a-z|0-9]+)/$" => "/?page=$1"
 )
```

**Comment by f0o** [comment]
Is this resolved?

**Comment by luca-m** [comment]
Sure, ty for your time! :)
Il 30/ago/2015 16:47, "Daniel Preussker" <notifications@github.com> ha
scritto:

**Comment by laf** [comment]
If it's fixed @luca-m can you confirm what that fix is so we can document and help others?

**Comment by Rosiak** [comment]
closed
