### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by Kage1** [librenms/librenms#13998]
### The problem

I have a very large number of VLANs device on a Dell N3200 switches and when I try to load the VLANs for that device Lbrenms throws an error: Whoops, looks like something went wrong. Check your librenms.log.

The log entry shows:
`[2022-05-27T11:52:24.422675-05:00] production.ERROR: Allowed memory size of 268435456 bytes exhausted (tried to allocate 95521616 bytes) {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Allowed memory size of 268435456 bytes exhausted (tried to allocate 95521616 bytes) at /opt/librenms/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesLayouts.php:102)"}`

PHP 8.1 memory has been increased to 256MB, reflected in the log entry. According to the log the attempted allocation ~95MB should have sufficient space.

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 22.5.0-12-g78583a4e7
DB Schema | 2022_02_21_073500_add_iface_field_to_bgp_peers (237)
PHP       | 8.1.2
Python    | 3.10.4
MySQL     | 10.6.7-MariaDB-2ubuntu1
RRDTool   | 1.7.2
SNMP      | 5.9.1
====================================

[OK]    Composer Version: 2.3.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[FAIL]  Database: incorrect column (notifications/datetime)
[FAIL]  Database: incorrect column (users/created_at)
[FAIL]  We have detected that your database schema may be wrong
        [FIX]:
        Run the following SQL statements to fix it
        SQL Statements:
         SET TIME_ZONE='+00:00';
         ALTER TABLE `notifications` CHANGE `datetime` `datetime` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00' ;
         ALTER TABLE `users` CHANGE `created_at` `created_at` timestamp NOT NULL DEFAULT '1970-01-02 00:00:01' ;
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]:
        You can fix this with ./scripts/github-remove
        Modified Files:
         bootstrap/cache/.gitignore
         logs/.gitignore
         rrd/.gitignore
         storage/app/.gitignore
         storage/app/public/.gitignore
         storage/debugbar/.gitignore
         storage/framework/cache/.gitignore
         storage/framework/cache/data/.gitignore
         storage/framework/sessions/.gitignore
         storage/framework/testing/.gitignore
         storage/framework/views/.gitignore
         storage/logs/.gitignore
```

### Anything in the logs that might be useful for us?

```txt
This instance was migrated from an Ubutnu 20.04 to a new instance running on Ubuntu 22.04 with PHP 8.1. I have run the SQL commands noted above, but the outputs from them were "Query OK, 0 rows affected" for each.
```

**Comment by Kage1** [comment]
Note: After posting this I have already fixed the noted database schema errors and the php memory error is still being issued.

**Comment by murrant** [comment]
@Kage1 you need to increase your php memory limit.

**Comment by Kage1** [comment]
Hello, this was reported here since it appears that it's a bug. If PHP has enough memory allocated but it's reporting its out of memory to me seems like a code issue.

**Comment by murrant** [comment]
Why do you think PHP has enough memory allocated?
