### ISSUE TITLE
All-in-one status view

### ISSUE THREAD

**Issue by trick77** [librenms/librenms#1400]
I'm really loving this all-in-one status view in Observium which is about my only reason for not using LibreNMS yet. Where would I have to start looking/developing such a view in LibreNMS? I might contribute this to the project even though it may take a while.

![Status View](http://i.imgur.com/Ykh5ERY.png)

**Comment by laf** [comment]
@trick77 So just the device overview page with the normal cpu / mem / disk / network graphs on it?

**Comment by trick77** [comment]
Yes, it's
OS icon + device + linebreak + location, CPU, memory, disk and network

**Comment by trick77** [comment]
I've looked at devices.inc.php and the code is a bit "old-style" (combination of php + db + html code) which makes it difficult to integrate another "path" like a condensed view into it. It's going to be a mess if I merge a condensed view into the existing code without some heavy refactoring.

**Comment by laf** [comment]
@trick77 

I'd say this is do-able, we currently have Basic / Detail and could add Overview, we then just need to swap out the Platform / Operating System / Uptime/Location columns out for the graphs needed.

This will all be done in:

html/pages/devices.inc.php
html/includes/table/devices.inc.php

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #163](https://github.com/librenms/librenmsv2/issues/163) via [**ZenHub**](https://www.zenhub.com/)
