### ISSUE TITLE
Ignored Items Show in Port List When Unchecked

### ISSUE THREAD

**Issue by Bigman397** [librenms/librenms#14009]
### The problem

When you go to the down port list instead of showing the small number of down ports(18) it is also showing me the ignored ones. If I select ignored it shows me only those ignored (557), if I unselect ignore it shows all ignored + normal down ports (573). I can't seem to get the page to show me those ports that are down and not otherwise ignored/disabled like the counter is showing. It has been like this for some number of months i'm finally just putting a bug request in.

### Output of ./validate.php

```txt
librenms@librenms:~$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 22.5.0-16-g6761d37cd
DB Schema | 2022_05_25_090027_drop_widgets_table (241)
PHP       | 7.4.3
Python    | 3.8.10
MySQL     | 10.6.8-MariaDB-1:10.6.8+maria~focal
RRDTool   | 1.7.2
SNMP      | 5.8
====================================

[OK]    Composer Version: 2.3.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]:
        You can fix this with ./scripts/github-remove
        Modified Files:
         rrd/.gitignore
librenms@librenms:~$
```

**Comment by laf** [comment]
I don't think this is an issue anymore so closing unless more reports come in.
