### ISSUE TITLE
Slow WebUI for devices with huge amount of ports

### ISSUE THREAD

**Issue by HolgerHees** [librenms/librenms#14021]
### The problem

I have a cisco switch with >400 virtual ports. If I open the "Port Settings" edit form and change the amount from 50 to all, it tooks more then 20 second to load this page.

I use this "all" overview to change "Disable Polling" or "Ignore alert tag" in one step. I also checked this regex based way to ignore interfaces, but there is no common way to identify interfaces I want to exclude. So I have to do it manually.

Next Problem is that we have >500 devices. Means loading 500 pages in > 20 seconds is very annoying.

I also debugged the page a little bit to find out whats the reason. It is not the network request itself. Its the amount of dom operations. Each pageload generates > 500 dom events. Looks like the jQuery Bootgrid lib is handling this in a very inefficient way.

Any Idea, how to optimize this. Or are there any plans to replace this old library with something newer? The lib itself has its last update 7 years ago.

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 22.3.0
DB Schema | 2022_02_03_164059_increase_auth_id_length (235)
PHP       | 7.4.28
Python    | 3.9.7
MySQL     | 10.5.15-MariaDB-1:10.5.15+maria~focal
RRDTool   | 1.7.2
SNMP      | 5.9.1
====================================

[OK]    Installed from the official Docker image; no Composer required
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[WARN]  Updates are managed through the official Docker image
```

**Comment by ottorei** [comment]
> This is more of a feature request. It is known that the device ports page loads slow when there are many ports. It is designed to load all ports and not paginate the results. To resolve that, someone would need to re-write the page.

Did you have an example with the proposed new JS-library yet? There are other pages as well which could be rewritten at some point.

**Comment by laf** [comment]
Ports page is now paginated so closing this down
