### ISSUE TITLE
Validation fails since #13930

### ISSUE THREAD

**Issue by tim427** [librenms/librenms#14030]
### Problem 1: rrdtool version mismatch
The local `rrdtool` is version `1.4.8`:

```
[root@nms01 librenms]# rrdtool
RRDtool 1.4.8  Copyright 1997-2013 by Tobias Oetiker <tobi@oetiker.ch>
               Compiled Nov 20 2015 19:23:48

Usage: rrdtool [options] command command_options
Valid commands: create, update, updatev, graph, graphv,  dump, restore,
		last, lastupdate, first, info, fetch, tune,
		resize, xport, flushcached

RRDtool is distributed under the Terms of the GNU General
Public License Version 2. (www.gnu.org/copyleft/gpl.html)

For more information read the RRD manpages
```

Somehow the validation script thinks it's `1.5.5`, although it's correctly been detected at the beginning of the `validate.php` script (see "Output of ./validate.php").

### Problem 2: mysql time zone mismatch
```
[root@nms01 librenms]# echo "LOCAL_SYTEM" && date && echo && echo "MYSQL" && mysql -uroot -pSUPERPASSWORD --execute="SELECT NOW(); SELECT @@global.time_zone;" librenms && echo && echo "PHP" && php -r 'print_r(date_default_timezone_get());' && echo&& php -r 'echo date("m/d/Y h:i:s a", time());' && echo
LOCAL_SYTEM
Sun 12 Jun 11:54:50 CEST 2022

MYSQL
+---------------------+
| NOW()               |
+---------------------+
| 2022-06-12 11:54:50 |
+---------------------+
+--------------------+
| @@global.time_zone |
+--------------------+
| SYSTEM             |
+--------------------+

PHP
Europe/Amsterdam
06/12/2022 11:54:50 am
```

We can clearly see; sytem, mysql and php are all using the same timezone and are correctly. Not sure why `validate.php` still complains it's two hours earlier (see "Output of ./validate.php").

###  Problem 3: 

```DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character```

(see "Output of ./validate.php")

### Output of ./validate.php

```txt
[root@nms01 librenms]# cd /opt/librenms/ && sudo -u librenms /opt/librenms/validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 22.5.0-41-g3e547de
DB Schema | 2022_05_30_084932_update-app-status-length (242)
PHP       | 7.4.30
Python    | 3.6.8
MySQL     | 5.7.38
RRDTool   | 1.4.8
SNMP      | 5.7.2
====================================

[OK]    Composer Version: 2.3.7
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]
[OK]    Database schema correct
[FAIL]  Time between this server and the mysql database is off
 Mysql time 2022-06-12 09:44:29
 PHP time 2022-06-12 11:44:29
[FAIL]  The rrdtool version you have specified is newer than what is installed.
	[FIX]:
	Either comment out or delete $config['rrdtool_version'] = '1.4.8'; from your config.php file
Attempt to fix this issue (y or n)?:n
[OK]    Connected to rrdcached
[FAIL]  DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character
```

**Comment by raphael247** [comment]
### Problem 2:

The reason for the timezone-problem is, that the timezone in CheckSchemaStructure is set to UTC: 
LibreNMS/Validations/Database/CheckSchemaStructure.php line 200:
`            array_unshift($this->schema_update, "SET TIME_ZONE='+00:00';");
`

Later in: LibreNMS/Validations/Database/CheckSqlServerTime.php line 41:
`        $raw_time = Eloquent::DB()->selectOne('SELECT NOW() as time')->time;`

the database-time will be queried.

I think the solution will be:
- CheckSqlServerTime before CheckSchemaStructure
- or reset database-Timezone to default_time_zone before doing the time-query

**Comment by murrant** [comment]
I bet the checks are in a different order than they used to be.  It should backup and restore the timeline.  A change will need to be made.

**Comment by murrant** [comment]
@tim427 Seems like the rrdtool validation is correct.  Show `lnms config:get rrdtool_version`  it will return 1.5.5 instead of the ancient 1.4.8 version you have.

**Comment by tim427** [comment]
> 
The check is correct;
```
[root@nms01 librenms]# cd /opt/librenms/ && sudo -u librenms /usr/bin/php ./lnms config:get rrdtool_version
1.4.8
```
Also `1.4.8` is shown at the beginning of `./validate.php`, but still comes up with:
```
[FAIL]  The rrdtool version you have specified is newer than what is installed.
	[FIX]:
	Either comment out or delete $config['rrdtool_version'] = '1.4.8'; from your config.php file
Attempt to fix this issue (y or n)?:
```

**Comment by murrant** [comment]
Oh, the rrdtool version was left hardcoded for testing... oops.  Will get the fix merged.
