### ISSUE TITLE
bad_ifalias_regexp and bad_ifname_regexp require    --ignore-checks

### ISSUE THREAD

**Issue by manonfgoo** [librenms/librenms#14089]
### The problem

bad_ifname_regexp and bad_ifalias_regexp should be able to be set from `lnms config:set`  without  the option --ignore-checks

### Output of ./validate.php

```txt
ConfigurationOk
DatabaseOk
DependenciesOk
DiskOk
DistributedpollerOk
MailOk
PhpOk
ProgramsWarning
Warning: IPv6 is disabled on your server, you will not be able to add IPv6 devices.
PythonOk
RrdOk
RrdcheckOk
SystemOk
UpdatesWarning
Warning: Non-git install, updates are manual or from package
UserOK
```

**Comment by Jellyfrog** [comment]
"Report an issue with LibreNMS
Bugs/issues only, no requests!"

**Comment by murrant** [comment]
Looks like they aren't defined in config_definitions.json.  Feel free to submit a pull request adding them :)
