### ISSUE TITLE
Reporting Interface

### ISSUE THREAD

**Issue by XxPatrickxX** [librenms/librenms#1409]
New feature request, custom reporting module. Thinking of a saveable list of custom reports for your given environment, currently I'm doing direct mysql queries for some of these.

/// show all servers by uptime descending
select hostname,uptime from devices where os = "windows" or os = "linux" order by uptime desc

/// Show all warning syslog events

select sysName, timestamp, program,msg from syslog join devices on devices.device_id = syslog.device_id where priority = "warning" limit 50

/// See which device is generating the most syslog entries

select devices.sysname, count(syslog.device_id) as Occurrences from syslog join devices on devices.device_id = syslog.device_id group by syslog.device_id order by Occurrences desc;

/// Show all warning or above syslog events

select * from syslog where priority = "warning" or priority = "critical"

Beyond the above, would be nice if they could have scheduled creation with email notifications....ie daily report style.

**Comment by paulgear** [comment]
:+1: from me - I'd also like to see this in a live dashboard, which I started, but never got back to.

**Comment by brillormen** [comment]
Would be great if you could create "complete" device reports from LibreNMS that includes the following in a CSV or PDF.

Name on device
Brand and model on device
Software on device
If VLAN is tagged or untagged on interfaces
IP-interface
SFP in which ports
Routing-table
Connected devices with LLDP
I guess all this info is in the database already.

**Comment by Iggybiggy** [comment]
For reporting I would like to be able to see historical data for the following:

Per device/hypervisor - 
Memory and CPU consumption
Storage information: size of disk + size of data on disk to assist in calculating storage growth
List of installed software/services. Preferably with version information and parent directory

Network ports -
Bandwidth consumption, ingress and egress
Traffic flow information - type of traffic traversing port, what logical ports are open/listening, etc.
Type of port - 10/100/1000/10GBASE etc. 
Connected devices - most useful report would be something like a visualization like what ZenMAP (windows GUI for NMAP) does. If it's in a table would be useful to see what device or port is connected on the "next hop." For instance, DNS name of client, or port # on the switch (ge.1.1, etc.)

A report that can group clients by service running. Something like "how many clients on my network are running DHCP, Active Directory, DNS, Print Server?" etc. 

Maybe have a report builder tool that allows you to group certain sets of information and arrange them hierarchically.

**Comment by baggar11** [comment]
Another vote for this. I can see this especially useful in needing to create bandwidth site reports on a monthly basis.

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #170](https://github.com/librenms/librenmsv2/issues/170) via [**ZenHub**](https://www.zenhub.com/)
