### ISSUE TITLE
docs: install mariadb

### ISSUE THREAD

**Issue by dontforget** [librenms/librenms#1410]
It maybe better to install mariadb instead of mysql?

If needed I'll update documentation.

**Comment by laf** [comment]
I'm not sure we recommend one over the other, it's upto the user on what they choose.

Might be good to at least mention MariaDB is supported if you want to add that?

**Comment by Rosiak** [comment]
Agree with @laf on this one.

**Comment by f0o** [comment]
I use MariaDB with Multi-Master clustering using Galera (codership vendor) and can say that it works outofthebox.

**Comment by paulgear** [comment]
:+1: to leaving it up to the user's choice

**Comment by laf** [comment]
PR done, can this be closed please.
