### ISSUE TITLE
API /api/v0/devicesgroups/:name/maintenance doesn't set device group

### ISSUE THREAD

**Issue by dnikoliouk** [librenms/librenms#14111]
### The problem

API /api/v0/devicesgroups/:name/maintenance creates maintenance windows, but doesn't set the devicegroup under **Map To** field. For additional details about this issue, please refer to a community discussion [API /api/v0/devicesgroups/:name/maintenance - “Server Error: Set APP_DEBUG=true to see details.”](https://community.librenms.org/t/api-api-v0-devicesgroups-name-maintenance-server-error-set-app-debug-true-to-see-details/19164)

![image](https://user-images.githubusercontent.com/37638768/179048406-df7e6882-f1d2-427e-96ae-98401aec0195.png)
 

### Output of ./validate.php

```txt
N/A
```

**Comment by danislav** [comment]
Just to mention that in my case, calling the api to set device maintenance also does not assign a device in the schedule.

**Comment by danislav** [comment]
Related: https://github.com/librenms/librenms/issues/14065

**Comment by murrant** [comment]
Duplicate
