### ISSUE TITLE
HPE BladeSystem c7000 Enclosure: No Blade Bay Status and Name of Bays

### ISSUE THREAD

**Issue by ebstefan6** [librenms/librenms#14149]
### The problem

We migrate from observium to librenms and have multiple HPE BladeSystem c7000 Enclosure.
In Observisum there show something like that:

![image](https://user-images.githubusercontent.com/109528170/181190058-2ba61bd8-7758-40ac-8bd9-cf314cbd2d03.png)

In Librenms this left complete, i only see the Bay Temperature.

What we forget here? IPMI Access configured in Device already.

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 22.7.0-14-ga214dbc8f
DB Schema | 2022_07_19_081224_plugins_unique_index (244)
PHP       | 7.3.31-1~deb10u1
Python    | 3.7.3
MySQL     | 10.3.34-MariaDB-0+deb10u1
RRDTool   | 1.7.1
SNMP      | 5.7.3
====================================

[OK]    Composer Version: 2.3.10
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
```

**Comment by MrXermon** [comment]
The status of the blades seems to be present in the cpqRackServerBlade table of the CPQRACK-MIB. The status is described within the cpqRackServerBladeStatus object.  Sadly, I were not able to get LibreNMS to add the value as a health-state to the device.

**Comment by Jellyfrog** [comment]
It needs to be added to the discovery definition for the OS. This is a device request tho; https://community.librenms.org/c/device-requests/12
