### ISSUE TITLE
php version minimum ask too high

### ISSUE THREAD

**Issue by dominic16y** [librenms/librenms#14172]
### The problem

Hi Everyone:

I follow this guide to install LibreNMS
https://docs.librenms.org/Installation/Install-LibreNMS/

it says "Please note the minimum supported PHP version is 7.3"

so I install to final step , login web page

it shows
PHP (8.1 or higher required)
[https://live.staticflickr.com/65535/52257784381_be569ebe0d_c.jpg](url)

so I was stucked here, no more next step

php version 8.1 asked was too difficult to achievement

debian10 apt install version is php 7.3
debian11 (currently stable version) apt install version is php 7.4

How do we meet the php 8.1 version this requirement?  

### Output of ./validate.php

```txt
Install fail , so no vaildate.php
```

**Comment by murrant** [comment]
@dominic16y good thing it won't be in effect until September.

**Comment by sniff122** [comment]
I know this was closed but this does appear to be an issue, ive just been following the install steps in the docs for ubuntu 20.04 and the version that is installed in the required packages step is 7.4 and the web based installer requires 8.1+, im not sure how one would complete the setup following the installation instructions in the docs

**Comment by murrant** [comment]
Updated 22.04 install docs are pending
