### ISSUE TITLE
Enabling alert rules on specific device changes global alert rules

### ISSUE THREAD

**Issue by SaaldjorMike** [librenms/librenms#1417]
Should only be changed for the specific device, and not globally.

**Comment by laf** [comment]
Hi @SaaldjorMike. Could you give us more information on this as I'm quite sure what you mean.

**Comment by SaaldjorMike** [comment]
@laf Sure. Going to the site:
/device/device=2/tab=edit/section=alert-rules/
Then disabling an alert rule, this disables the rule globally and not only for the device. This can be verified by then going to:
https://librenms.kollegienet.dk/alert-rules/

**Comment by laf** [comment]
Ah ok so what I believe is happening here is:

Global alert rule created (i.e not device specific).
Disable that alert rule in the specific device.
Global alert rule is then disabled.

That's actually by design as we show global alert rules for the specific devices that would match them. Maybe we just need to make it clearer that disabling it for that device will affect others.

Did I get what you mean?

**Comment by SaaldjorMike** [comment]
Yep. Exactly. I had a friend that mentioned that he was expecting it to only disable the rule for that specific device when disabling it in this way. Would it make sense to add a button to allow the user to ignore/disable a given rule for specific devices from that edit section on some device? Or how's your take on this?

**Comment by laf** [comment]
It's a difficult one as the only way to exclude that device from the alert rule is to change the alert rule which is technically possible but I'd be worried that we cause an issue with the rule.

Having just the ack button is fine as that's done per alert but we already have a page for that. 

We could remove the disable button for global rules or add something to indicate what it is so people know.

?

**Comment by SaaldjorMike** [comment]
It might be enough for now to just make it clear that it is global rules that are getting modified.

**Comment by SaaldjorMike** [comment]
I still receive comments regarding the issue where my friend needs to change the rule to exclude specific servers from the alert rule. This is not a nice way to exclude some devices from what would else be global rule for all other devices.

**Comment by SaaldjorMike** [comment]
Closing this one, as one should use the alert mappings for mapping alerts to a set of devices.
