### ISSUE TITLE
MySQL SNMP extend error

### ISSUE THREAD

**Issue by eJc2** [librenms/librenms#14188]
### The problem

Hi, the SNMP Extent for MySQL doesn't work:

librenms@lnms01:$ /etc/snmp/mysql
PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied; you need (at least one of) the PROCESS privilege(s) for this operation in /etc/snmp/mysql:1313
Stack trace:
#0 /etc/snmp/mysql(1313): mysqli_query()
#1 /etc/snmp/mysql(539): run_query()
#2 /etc/snmp/mysql(141): ss_get_mysql_stats()
#3 {main}
  thrown in /etc/snmp/mysql on line 1313
librenms@lnms01:~$

Any hints?

### Output of ./validate.php

```txt
librenms@lnms01:~$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 22.7.0-47-ge9211d93c
DB Schema | 2022_07_19_081224_plugins_unique_index (244)
PHP       | 8.1.8
Python    | 3.9.2
Database  | MariaDB 10.5.15-MariaDB-0+deb11u1
RRDTool   | 1.7.2
SNMP      | 5.9
====================================

[OK]    Composer Version: 2.3.10
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

22.7.0

### Anything in the logs that might be useful for us?

librenms@lnms01:/etc/snmp$ cat mysql.cnf
<?php
$mysql_user = 'librenms';
$mysql_pass = '05^1rUvVJZW72w!iVEeb';
$mysql_host = '127.0.0.1';
$mysql_port = 3306;
$chk_options['slave'] = false;

**Comment by duhow** [comment]
Assuming that your file `/etc/snmp/mysql.cnf` is empty, you should configure with proper credentials.
Also ensure that the user can execute the following command.

https://github.com/librenms/librenms-agent/blob/1914bcb1eac47f0f48aaf3789e376e0d8d17fd14/snmp/mysql#L539

**Comment by murrant** [comment]
The hint: `Access denied; you need (at least one of) the PROCESS privilege(s) for this operation`

**Comment by eJc2** [comment]
> Assuming that your file `/etc/snmp/mysql.cnf` is empty, you should configure with proper credentials. Also ensure that the user can execute the following command.
> 
> https://github.com/librenms/librenms-agent/blob/1914bcb1eac47f0f48aaf3789e376e0d8d17fd14/snmp/mysql#L539

Yes sr,

![image](https://user-images.githubusercontent.com/41594696/183412320-6d6358c4-ddd3-4fa2-a700-b7d940f7b435.png)

**Comment by eJc2** [comment]
> The hint: `Access denied; you need (at least one of) the PROCESS privilege(s) for this operation`

This extent not work with librenms, mysql, Debian-snmp nor root users:

librenms user:
![image](https://user-images.githubusercontent.com/41594696/183413268-eb5dcd17-e6ac-423c-9724-1ee693a98648.png)

mysql user:
![image](https://user-images.githubusercontent.com/41594696/183416086-96bc49a8-1f70-47d7-b578-244e925284bb.png)

Debian-snmp user:
![image](https://user-images.githubusercontent.com/41594696/183416355-66e39bee-e999-4deb-a47f-513206165c78.png)

root user:
![image](https://user-images.githubusercontent.com/41594696/183416436-8f037fcf-2891-4c1a-8887-c25dcf847be4.png)

1313 line on /etc/snmp/mysql
![image](https://user-images.githubusercontent.com/41594696/183416672-477a652c-eb7f-43fc-b4cd-b772ed94d70f.png)

**Comment by andrzejmaczka** [comment]
Fix:

To grant the PROCESS privilege, log in as an administrator user and run the following query:

GRANT PROCESS ON *.* TO librenms@localhost;
