### ISSUE TITLE
Spaces cannot be avoided when using @if or @foreach

### ISSUE THREAD

**Issue by nightcore500** [librenms/librenms#14201]
### The problem

If you use @if or @foreach a space between text and the @if or @foreach seems to be necessary. Otherwise this leads to a "Template failed to be parsed, please check the syntax. syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF)". However, this leads to unwanted spaces between text modules. 

As an example the following template:
`This is a sentence without if or forearch! This is an alert named @if ($alert->name) {{ $alert->name }} @endif @if ($alert->faults) and the key @foreach ($alert->faults as $key => $value) {{ $key }} @endforeach is available @endif!`

Leads to this:
`This is a sentence without if or forearch! This is an alert named  Test alert   and the key  1  is available !`
EDIT: Hm, looks like github is removing the duplicate spaces....

The unwanted spaces are clearly visible here. This also occurs with titles.

### Output of ./validate.php

```txt
$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 22.7.0
DB Schema | 2022_07_19_081224_plugins_unique_index (243)
PHP       | 7.4.30
Python    | 3.7.3
MySQL     | 10.5.11-MariaDB-1-log
RRDTool   | 1.7.1
SNMP      | 5.7.3
====================================

[OK]    Composer Version: 2.3.10
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

**Comment by Jellyfrog** [comment]
Just remove the space around `{{..}}`
```blade
This is a sentence without if or forearch! This is an alert named @if ($alert->name){{ $alert->name }}@endif @if ($alert->faults) and the key @foreach ($alert->faults as $key => $value){{ $key }}@endforeach is available @endif!
```
apart from that, this is a laravel issue, have to be reported there instead
