### ISSUE TITLE
ZTE GPON OLT - add-on that causes problems and instability of the device

### ISSUE THREAD

**Issue by streamthing** [librenms/librenms#14203]
### The problem

This commit https://github.com/librenms/librenms/pull/14049 causes:
- browser sometimes crashes when loading device page due to around 3000 entires in dBm box
- can't scroll to bottom to eg. logs due to high count of entires in dBm category (browser goes crazy on scrolling)
- shows "ONU Rx :1" - commit has bug and don't shows correct GPON ID
- -80dBm signal (there is no possibility of such a signal, maximum -40)
- on "OLT Interfaces" there is only "Rx", "Tx" without any description
- CPU in OLT has a problem with reading each ONU every 5 minutes
- ZTE does not recommend frequent reading the signal from ONU by SNMP, the minimum is one read per hour (here 5 minutes)
- ZTE GPON OLT has a software bug that causes the line card to crash due to frequent polling

Why was this makeshift code added to LibreNMS? LibreNMS should consist of safe and stable code. If the device is overloaded by LibreNMS, it is not safe for the network.

Please LibreNMS staff remove it from LibreNMS or add some option to disable this code. This code shouldn't be enabled by default!!!

![ONU](https://user-images.githubusercontent.com/90110072/184417416-9f2f2623-c1e6-4058-a52e-07ec2b03828d.png)
![OLT](https://user-images.githubusercontent.com/90110072/184417443-5236a95c-fab9-4c83-bd1c-70e408381d1e.png)

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 22.7.0-61-g4d4ac9dc3
DB Schema | 2022_07_03_1947_add_app_data (244)
PHP       | 7.3.19-1~deb10u1
Python    | 3.7.3
Database  | MariaDB 10.3.27-MariaDB-0+deb10u1
RRDTool   | 1.7.1
SNMP      | 5.7.3
====================================

[OK]    Composer Version: 2.3.10
[OK]    Dependencies up-to-date.
[WARN]  Debug enabled.  This is a security risk.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[WARN]  PHP version 8.1 is the minimum supported version as of September, 2022. We recommend you update PHP to a supported version (8.1 suggested) to continue to receive updates. If you do not update PHP, LibreNMS will continue to function but stop receiving bug fixes and updates.
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### Device info

ZTE GPON OLT C300 and C320

### Discovery output

```txt
not needed
```

### Poller output

```txt
not needed
```

**Comment by aztec102** [comment]
Good afternoon!
I think yes, with a large number of devices it is necessary to somehow fight.
Another point, I think it was redundant to add graphics for the TX signal for ONT
We can write a fix with the signal, I think we can fix -80 too.
With descriptions - I already told @murrant that there is a problem with forming them. Perhaps it should be taken to pre-cache.
ZTE C300 specifically has a jamb when reading data from cards. I helped a friend and we looked for all the patches for all the boards and looked for a system patch. After installing just the system patch - more or less the problem was solved. But charts are written with a timeout of 180 seconds.

**Comment by aztec102** [comment]
At the moment, I have a suggestion to leave DDM monitoring for ONT only for ZTE C320.
I am generally ready to write a PR

**Comment by murrant** [comment]
@aztec102 pre-cache is mis-named.  It just means fetch the value more than LibreNMS normally would.  When using yaml, if the same oid is referenced multiple times it is only fetched once and is not fetched if it is not needed.

@streamthing There is no LibreNMS staff, only community members.  LibreNMS maintainers do not have access to basically any of the devices LibreNMS supports so we have to trust things work with the actual hardware.

I'm more than happy to revert the PR, @aztec102 do you want to try to fix things before I do?

**Comment by aztec102** [comment]
@murrant I already went to do PR

**Comment by aztec102** [comment]
@streamthing There is a silence that I don't like at all. I wrote a change, excluded the C300 at this stage.
After talking with people, they told me that I know about the problem, but apparently the vendor does not know it.
Owners of SCTM management cards are more fortunate, because there are no stocks there.
Can you clarify whether you contacted the vendor and described the problem to him?

**Comment by streamthing** [comment]
We don't have time for unstable software, your commit caused us a lot of issues with our internet services and too much phone calls from our clients. We have now removed all OLT's ZTE from LibreNMS, but it's not great solution.
We expect that entire pull request will be deleted or added some variable for disable it in config.php.

**Comment by aztec102** [comment]
@streamthing You can test PR yourself. The fact is that PR excludes the inclusion of graphs on the ZTE C300. I personally do not have a C300, so there is no way to test it.

**Comment by saefuls** [comment]
i need  to update ZTE Gpon OLT add DBM

**Comment by razvan919** [comment]
Error discovering ports-stack module for 10.0.0.10. ArgumentCountError: Too few arguments to function LibreNMS\Modules\PortsStack::LibreNMS\Modules{closure}(), 2 passed and exactly 3 expected in /opt/librenms/LibreNMS/Modules/PortsStack.php:78
Stack trace:
#0 [internal function]: LibreNMS\Modules\PortsStack->LibreNMS\Modules{closure}()
#1 /opt/librenms/LibreNMS/Data/Source/SnmpResponse.php(248): call_user_func()
#2 /opt/librenms/LibreNMS/Modules/PortsStack.php(90): LibreNMS\Data\Source\SnmpResponse->mapTable()
#3 /opt/librenms/includes/discovery/ports-stack.inc.php(8): LibreNMS\Modules\PortsStack->discover()
#4 /opt/librenms/includes/discovery/functions.inc.php(170): include(‘…’)
#5 /opt/librenms/discovery.php(108): discover_device()
#6 {main}
Too few arguments to function LibreNMS\Modules\PortsStack::LibreNMS\Modules{closure}(), 2 passed and exactly 3 expected {“exception”:“[object] (ArgumentCountError(code: 0): Too few arguments to function LibreNMS\Modules\PortsStack::LibreNMS\Modules\{closure}(), 2 passed and exactly 3 expected at /opt/librenms/LibreNMS/Modules/PortsStack.php:78)”}
/opt/librenms/discovery.php 1 2025-04-06 00:33:11 - 1 devices discovered in 9.687 secs
/opt/librenms/discovery.php 4 2025-04-06 00:33:16 - 1 devices discovered in 3.949 secs
/opt/librenms/discovery.php 3 2025-04-06 00:33:18 - 1 devices discovered in 1.952 secs
/opt/librenms/discovery.php 2 2025-04-06 00:33:20 - 1 devices discovered in 1.725 secs
/opt/librenms/discovery.php new 2025-04-06 00:35:02 - 0 devices discovered in 0.001 secs

![Image](https://github.com/user-attachments/assets/7d4568b8-3b56-475a-bbb5-c78e6008f962)

**Comment by razvan919** [comment]
Can someone solve this problem please?
