### ISSUE TITLE
Cannot match fields with NULL values in device-group patterns

### ISSUE THREAD

**Issue by Ftelf** [librenms/librenms#1422]
When I add new device it is not listed in custom group until I manually edit and resave it.
This is very flustrating since I have this custom group as a flag / label of not assorted devices.

http://fii.cz/meguwnm

**Comment by laf** [comment]
@Ftelf 

If I understand you correctly what you're saying is:

A device group is created - let's say that groups all linux devices together.
You add a new device which is linux.
You click the group linux and you don't see the device?

If that's the case then I can't replicate that, works for me fine. The query is dynamic so I can't see why you need to edit / save it again.

If that's not what you mean can you provide more info please.

**Comment by Ftelf** [comment]
I have a Groups based on Description. Because of the lack of some Labels or custom attributes I need to logically group devices together based on various attributes.
So I found that I can add my device Desctiption: [AP Stealth] [AttrA2] [AttrB3]
Than I have a Groups:
http://fii.cz/jsfmeaab

The group  "FILL Description" means, that the Description is still empty and I have to process this device.
But when the new device is add I cannot see it in the group "FILL Description" unless I previously edit it and resave, even I did not changed a thing.

I have found the source of the problem.
Once created the purpose column in the devices group is NULL, but once resaved, its empty String.
So the pattern %devices.purpose .... just skips the processing and eliminate the device as a candidate of the group member.

I believe that you should either have a empty String as a default value of the purpose or when processing the pattern handle NULL as empty String.

**Comment by f0o** [comment]
Sorry too big fingers.. Its really annoying I know :S

What i wanted to say:
@ftelf can you try out using the Like-comparisson instead of Equals?
`Like ""` should apply to `NULL`

**Comment by Ftelf** [comment]
Maybe I do not understand, because I already use Like comparison. LIKE == ~

But I may follow your point. As a possible workaround I have added:
&& %devices.purpose ~ ""

But still I miss the devices which has purpose field equal to NULL.

http://fii.cz/vmdhewqn

**Comment by f0o** [comment]
hrm I see..

tricky - I will get some test-case up and see what I can do

**Comment by f0o** [comment]
@Ftelf I found a solution. Can you please apply this patch & Config:

Rule :
`%macros.null_purpose = 1`

`config.php` :
```php
$config['alert']['macros']['group']['null_purpose'] = "%devices.purpose IS NULL";
```

Patch:
```diff
diff --git a/includes/device-groups.inc.php b/includes/device-groups.inc.php
index 533b433..43c57cf 100644
--- a/includes/device-groups.inc.php
+++ b/includes/device-groups.inc.php
@@ -29,6 +29,10 @@
  * @return string
  */
 function GenGroupSQL($pattern,$search='') {
+	$pattern = RunGroupMacros($pattern);
+	if( $pattern === false ) {
+		return false;
+	}
 	$tmp = explode(" ",$pattern);
 	$tables = array();
 	foreach( $tmp as $opt ) {
@@ -91,4 +95,29 @@ function GetGroupsFromDevice($device) {
 	}
 	return $ret;
 }
+
+/**
+ * Process Macros
+ * @param string $rule Rule to process
+ * @param int $x Recursion-Anchor
+ * @return string|boolean
+ */
+function RunGroupMacros($rule,$x=1) {
+	global $config;
+	krsort($config['alert']['macros']['group']);
+	foreach( $config['alert']['macros']['group'] as $macro=>$value ) {
+		if( !strstr($macro," ") ) {
+			$rule = str_replace('%macros.'.$macro,'('.$value.')',$rule);
+		}
+	}
+	if( strstr($rule,"%macros") ) {
+		if( ++$x < 30 ) {
+			$rule = RunGroupMacros($rule,$x);
+		} else {
+			return false;
+		}
+	}
+	return $rule;
+}
+
 ?>
```

**Comment by Ftelf** [comment]
I have patched the device-groups.inc-php, added line co config.php.
But I do not follow the first thing:
Rule :
%macros.null_purpose = 1

So far no change.

**Comment by f0o** [comment]
The rule is what goes into the device-group along with other conditions.

**Comment by Ftelf** [comment]
I see, no change. Still cannot see the devices with null purpose.
http://fii.cz/wnehwvum

btw, I had to force the rule naming, the whisperer did not offered the "null_purpose"

**Comment by f0o** [comment]
Yeah the suggest-code is not touched yet.

However, the pattern `%macros.null_purpose = 1` does return me all devices with purpose being NULL...

Can you try only having: `%macros.null_purpose = 1 || %devices.purpose ~ ""` ? (you might not be able to get this done via the UI because it might not allow empty values :S)

**Comment by Ftelf** [comment]
Sorry,
I'm idiot. Your right, but the GUI widget which creates the query puts the operator to the end of the query, so when I choose the || I would had to choose it for the previous operand. 
http://fii.cz/bpwme
http://fii.cz/zxvwse
http://fii.cz/enuswguk

I had edited this in DB and it works now, but I think about it only as a temporary solution, because I do not think that the user have to keep in mind that the field could be both null or empty string.

**Comment by f0o** [comment]
`%macros.null_purpose = 1` Should be enough tho, it is enough for me... Do you mind retrying it with only that?

**Comment by Ftelf** [comment]
http://fii.cz/hfycts

Becames strange. Groups.....
FILL Description hits both String.Empty and NULL.
NULL hits only null purpose.
So when I hit just edit->save it disappeares from the NULL group.

**Comment by f0o** [comment]
I dont quite understand what you mean :S

**Comment by Ftelf** [comment]
Ok, the purpose column could be either NULL (once the device is newly created) or String.Empty (once the device get saved) or whatever you'll edit.
Now I have a mix of devices which has a purpose filled with a meaningful value, devices resaved with purpose as a String.Empty value and devices newly created which has a NULL value.

I have a two groups for this issue. My previous one named: FILL Description
http://fii.cz/xbyhrts

And the suggested one named NULL
http://fii.cz/mmyrngp

The first group "FILL Description" works fine. I get both String.Empty and NULL purpose listed.

But the second group lists only purpose as NULL, not the String.Empty.

**Comment by f0o** [comment]
Ah ok!, edit the config so it looks like:
```php
$config['alert']['macros']['group']['null_purpose'] = '%devices.purpose IS NULL || %devices.purpose ~ ""';
```

And the group pattern would be `%macros.null_purpose = 1`

**Comment by Ftelf** [comment]
Did the trick.

**Comment by f0o** [comment]
perfect, will PR this :)

**Comment by Ftelf** [comment]
Searching for empty purpose by:
$config['alert']['macros']['group']['null_purpose'] = '%devices.purpose IS NULL || %devices.purpose ~ ""';
and group pattern would be %macros.null_purpose = 1
does not work anymore. After some time I have listed those devices, but the expected ones were missing:
config.php http://fii.cz/unvzam
device group http://fii.cz/kytfzz
actual group search http://fii.cz/fntgzzxw
