### ISSUE TITLE
ALERT RULES | "Match devices, groups and locations list" is not honoring "locations "

### ISSUE THREAD

**Issue by teixemf** [librenms/librenms#14246]
### The problem

Alert Rules are not matching against "locations". 
If a Location is chosen from the list, the Alert Rule ignores it and matches against any device.
This behavior is not observed if a Group or specific Devices are chosen on the list.

Setup:
1) Create an Alert Rule
2) Setup "Match devices, groups and locations list" to match a Location.

Expected behavior:
It is expected the alert rule to match only devices which are part of that specifc Location.

Result:
The alert rule matches against all devices.

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 22.8.0
DB Schema | 2022_07_03_1947_add_app_data (244)
PHP       | 8.0.22
Python    | 3.10.5
Database  | MariaDB 10.5.13-MariaDB-1:10.5.13+maria~focal
RRDTool   | 1.7.2
SNMP      | 5.9.3
====================================

[OK]    Installed from the official Docker image; no Composer required
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No python wrapper pollers found
[OK]    Redis is functional
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Updates are managed through the official Docker image
```

**Comment by murrant** [comment]
Need more info such as generated sql and sql results and expected results.

**Comment by electrocret** [comment]
I can confirm the issue exists.
Test Alert Created:
![image](https://user-images.githubusercontent.com/6815956/186721465-06effaf0-f9a7-4ead-a800-a560c2dc87c5.png)

Alert on device not at specified location:
![image](https://user-images.githubusercontent.com/6815956/186721786-d38dd7ed-2b03-4ff7-bf87-a222bcf5d008.png)

**Comment by teixemf** [comment]
> Need more info such as generated sql and sql results and expected results.

Sorry but I am still trying to figure how LibreNMS works under the hood to provide proper feedback.
I can I help exactly?  Does the output of "alert.php -d" helps?

**Comment by murrant** [comment]
Go to a device where the alert triggers.  Click the dropdown menu and select capture, then pick alert.  That will give you all the information.

**Comment by teixemf** [comment]
These rules should not match since the device is not part of the Location selected on the Alert Rule.

Rule name: Port status up/down
Alert rule: macros.port_down = 1 AND port_groups.id = 5
Alert query: SELECT * FROM devices,ports,port_group_port,port_groups WHERE (devices.device_id = ? AND devices.device_id = ports.device_id AND ports.port_id = port_group_port.port_id AND port_group_port.port_group_id = port_groups.id) AND (ports.ifOperStatus = "down" && ports.ifAdminStatus != "down" && (ports.deleted = 0 && ports.ignore = 0 && ports.disabled = 0)) = 1 AND port_groups.id = 5
Rule match: matches

Rule name: MT | TEST | Port status up/down
Alert rule: macros.port_down = 1 AND port_groups.id = 5
Alert query: SELECT * FROM devices,ports,port_group_port,port_groups WHERE (devices.device_id = ? AND devices.device_id = ports.device_id AND ports.port_id = port_group_port.port_id AND port_group_port.port_group_id = port_groups.id) AND (ports.ifOperStatus = "down" && ports.ifAdminStatus != "down" && (ports.deleted = 0 && ports.ignore = 0 && ports.disabled = 0)) = 1 AND port_groups.id = 5
Rule match: matches

**Comment by murrant** [comment]
Looks like the AlertUtil::getRules() function joins the location map table, but never checks it

**Comment by andrzejmaczka** [comment]
https://github.com/librenms/librenms/issues/12921
