### ISSUE TITLE
Remote Devices not visible if behind a port channel

### ISSUE THREAD

**Issue by azhermughal** [librenms/librenms#1425]
I have Dell s4810 switch connected to another Dell (Force10) switch using 4 parallel 10GE ports under a LAG. The Arp list shows the MAC addresses but does not show remote devices which are visible through portchannel, thus locating a MAC address is very tedious.

Arp-table for this switch: http://imagebin.ca/v/287UoZAFLuZO

For the Discovery and Poller output for both of the involved switches, I am sending email to team@librenms email.

Thanks
-Azher

**Comment by laf** [comment]
For the ones where it shows the device name and port does it show anything for the remote?

I'd be more interested to start with in trying to find out why the device and port name aren't showing. Can you send us the output of (replace 64 with your device id):

```bash
SELECT *,`P`.`ifDescr` AS `interface`  FROM `ipv4_mac` AS M, `ports` AS P, `devices` AS D  WHERE M.port_id = P.port_id AND P.device_id = D.device_id   AND `mac_address` LIKE '%%' AND P.device_id = 64 ORDER BY  hostname asc LIMIT 0,10;
```

**Comment by azhermughal** [comment]
ipv4_mac tables has only 3 columns. Not sure from which table I can find the device id ? Thanks.

mysql> select * from ipv4_mac limit 1,1;
+---------+--------------+----------------+
| port_id | mac_address  | ipv4_address   |
+---------+--------------+----------------+
|      69 | 003048fbfbca | 131.215.207.41 |
+---------+--------------+----------------+
1 row in set (0.00 sec)

**Comment by azhermughal** [comment]
Hi laf,

Further outputs which might help are as below:

mysql> SELECT *,`P`.`ifDescr` AS `interface`  FROM `ipv4_mac` AS M, `ports` AS P, `devices` AS D  WHERE M.port_id = P.port_id AND P.device_id = D.device_id   AND `mac_address` LIKE '%%' AND P.device_id = 64 ORDER BY  hostname asc LIMIT 0,10;
Empty set (0.00 sec)

The device in question has id=11

mysql> select device_id,hostname from devices  LIMIT 0,10;
+-----------+------------------+
| device_id | hostname         |
+-----------+------------------+
|        24 | 192.168.255.130  |
|         9 | brocade-cer-r5   |
|        10 | brocade-mlxe8-r5 |
|        22 | c3750-campus-gw  |
|         2 | c7606            |
|        21 | d6248-ipac-mrg09 |
|        19 | d6248-lrt-r4     |
|         8 | d6248-r6         |
|        15 | d6248-r7         |
|        11 | e600-r9          |
+-----------+------------------+
10 rows in set (0.00 sec)

mysql> select * from ipv4_mac where ipv4_address='192.168.255.9' LIMIT 0,100;
+---------+--------------+---------------+
| port_id | mac_address  | ipv4_address  |
+---------+--------------+---------------+
|       3 | 0001e80c15d0 | 192.168.255.9 |
+---------+--------------+---------------+
1 row in set (0.00 sec)

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
