### ISSUE TITLE
device wrongly shows as 'rebooted' or 'down' on the device overview screen

### ISSUE THREAD

**Issue by jarnotimmermans** [librenms/librenms#1426]
Hello,

We switched from Observium to LibreNMS recently and have an issue with the device overview screen. (not alerting)

One of our switches, a Cisco 2960 - v15.0(2)SE, shows that it has rebooted a few hours ago, but when connecting with the switch we see that this was not the case. 'show version' shows >1 year uptime. What could cause LibreNMS to flag this device as 'rebooted'?

Perhaps related, one of our 6513-E core switches sometimes shows as 'device down' while it's actually not. After a few minutes LibreNMS detects that it's up and the device box goes away.

We're monitoring roughly 50 devices & 500 ports.

How does LibreNMS detect a device as down or rebooted? Are there any timers I might have to adjust to make them less sensitive?

Thanks in advance!

**Comment by Rosiak** [comment]
Afaik this has something to do with the counter on the devices.
I've seen it a lot of times, even with my own 2950's.

**Comment by laf** [comment]
Yeah, circa 430 days and it will roll and show the device as rebooted. We can fix it, just not got round to it yet.

**Comment by jarnotimmermans** [comment]
Ok, thanks for the feedback! I'll keep an eye on future change-logs :)

What about the 'device down' issue we notice on one of our core switches? (The C6513-E)
Is it also related to uptime or?

**Comment by laf** [comment]
Sorry @jarnotimmermans I didn't see your other question.

We detect a device down either when 3 icmp requests via fping don't make it through - or snmp doesn't respond in time.
