### ISSUE TITLE
Dell/Force10 switches do not show platform

### ISSUE THREAD

**Issue by azhermughal** [librenms/librenms#1429]
These are originally Force10 Devices, a company acquired by Dell.

http://imagebin.ca/v/2892qFgqmrj8

For another #1425, I have sent the MIBs.

Please let me know if more MIBs are needed.

Thanks
-Azher

**Comment by Rosiak** [comment]
Can you provide us with a SNMPWALK or similar?

**Comment by azhermughal** [comment]
Here are few lines, please let me know if you need more specific:

root@ubuntu-librenms:/opt/librenms# snmpwalk -v2c -c xxxxxxxx s4810-r3 | more
iso.3.6.1.2.1.1.1.0 = STRING: "Dell Networking OS
Operating System Version: 2.0
Application Software Version: 9.7(0.0P4)
Series: S4810
Copyright (c) 1999-2015 by Dell Inc. All Rights Reserved.
Build Time: Mon May  4 20:52:56 2015"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.6027.1.3.14
iso.3.6.1.2.1.1.3.0 = Timeticks: (515674402) 59 days, 16:25:44.02
iso.3.6.1.2.1.1.4.0 = STRING: "Azher"
iso.3.6.1.2.1.1.5.0 = STRING: "R3:s4810"
iso.3.6.1.2.1.1.6.0 = STRING: "CACR Rack-3"
iso.3.6.1.2.1.1.7.0 = INTEGER: 6
iso.3.6.1.2.1.2.1.0 = INTEGER: 134
