### ISSUE TITLE
Mac address formatted incorrectly on device port page

### ISSUE THREAD

**Issue by fbouynot** [librenms/librenms#14308]
### The problem

On de device port page, eg. https://librenms/device/device=226/tab=port/port=12167/, the mac address is formatted as an IPv6 address (well, incorrectly), eg. 70::4:c::a5::6:8::d8::5:1
I'm expecting 70:4c:a5:68:d8:51 or 704c.a568.d851

### Output of ./validate.php

```txt
$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 22.8.0-58-g3f27d8927
DB Schema | 2022_07_03_1947_add_app_data (244)
PHP       | 8.1.10
Python    | 3.6.8
Database  | MariaDB 10.8.4-MariaDB
RRDTool   | 1.7.0
SNMP      | 5.8
====================================

[OK]    Composer Version: 2.4.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

**Comment by murrant** [comment]
That isn't an IPv6 ;)   You are only allowed one :: in an IPv6 :D  Likely it is from your device sending the MAC in an unexpected format.

**Comment by fbouynot** [comment]
>  You are only allowed one :: in an IPv6

Yes I know, that's why I did write "incorrectly".

> Likely it is from your device sending the MAC in an unexpected format

I have this for every port of every device (ESX VM, Cisco, Riverbed, etc).

You don't have the same issue?

**Comment by eimann** [comment]
We see the issue too across all vendors.

**Comment by murrant** [comment]
Haha, I can guess what happened.  Format as mac twice :D

**Comment by fbouynot** [comment]
Thanks @murrant ! I tried the patch and it works.
