### ISSUE TITLE
ports_purge Config Setting Inconsistent

### ISSUE THREAD

**Issue by washcroft** [librenms/librenms#14336]
### The problem

**The config setting/documentation for ports_purge is inconsistent.**

The UI shows the value should be an amount of days:

![image](https://user-images.githubusercontent.com/1866176/189529560-74a3573b-bdd2-457b-b5bb-d52287b6ea8c.png)

The [Cleanup documentation](https://docs.librenms.org/Support/Cleanup-options/#ports-purge) also shows the value should be an amount of days in the config example:

`$config['ports_purge'] = 10;`

...but then true/false in the description:

> You can purge all deleted ports from the WebUI (see below) or by setting $config['ports_purge'] = true; in config.php

In actual fact, the code which uses this value is purging ports during daily.sh on a true/false basis (therefore, when anything other zero):

https://github.com/librenms/librenms/blob/master/daily.php#L137

PR #13026 relates.

### Output of ./validate.php

```txt
Irrelevant
```

### What was the last working version of LibreNMS?

22.8.0

**Comment by murrant** [comment]
Should be fixable by updating config_definitions.json if you want to send a fix.

**Comment by PipoCanaja** [comment]
fixed by https://github.com/librenms/librenms/pull/14402
