### ISSUE TITLE
'Operating System' field not updated

### ISSUE THREAD

**Issue by WilliamDEdwards** [librenms/librenms#14355]
### The problem

The ‘Operating System’ field for devices is never updated, except for with one device. For example, one device used ‘Linux 4.19.0-16-amd64 (Debian GNU/Linux 10)’ on its first discovery, but has been on ‘Linux 5.10.0-15-amd64 (Debian GNU/Linux 11)’ for 2 months.

This field did update for one device that was upgraded about 20 minutes after I ran the poller manually (although it might have updated by itself; I don’t know if the poller ran before I ran it manually after upgrading the device). This is the only exception. I’m not sure what’s different about this device.

I posted some debugging information here: https://community.librenms.org/t/operating-system-field-not-updated/19493

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 22.8.0-133-g0f14a7c17
DB Schema | 2022_07_19_081224_plugins_unique_index (244)
PHP       | 7.4.30
Python    | 3.7.3
Database  | MariaDB 10.6.9-MariaDB-1:10.6.9+maria~deb10-log
RRDTool   | 1.7.1
SNMP      | 5.7.3
====================================

[OK]    Composer Version: 2.4.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
[WARN]  Your install is over 24 hours out of date, last update: Tue, 23 Aug 2022 22:24:35 +0000
	[FIX]:
	Make sure your daily.sh cron is running and run ./daily.sh by hand to see if there are any errors.
[WARN]  Your local git contains modified files, this could prevent automatic updates.
	[FIX]:
	You can fix this with ./scripts/github-remove
	Modified Files:
	 rrd/.gitignore
```

**Comment by murrant** [comment]
I am not able to reproduce this.  When the snmpextend output changes, so does the data in the database.

One clarification, the data is collected during the discovery process (every 6hrs by default), so running the poller will not update the data.
