### ISSUE TITLE
Nightly update breaks LNMS due to new dependency

### ISSUE THREAD

**Issue by 0xc0decafe** [librenms/librenms#14396]
### The problem

Waking up in the morning I had to recon that the nightly update broke my setup as a new dependency (php-simplexml) was required.
After manually installing the dependency everything is working fine again, but i'm missing a whole night of data.
In the future, PLEASE DON'T introduce new dependencies without previous notification.

### Output of ./validate.php

```txt
In platform_check.php line 47:
                                                                                                                                          
  Composer detected issues in your platform: Your Composer dependencies require the following PHP extensions to be installed: simplexml.
```

### What was the last working version of LibreNMS?

latest nightly updated version on Sunday 26.Sept.2022

**Comment by tomck** [comment]
I just switched from CentOS 8.5 to CentOS stream so I could go from PHP 7.3 to PHP 8.2 via remirepo, and I am getting the same error, and I got composer to update with --ignore-platform-reqs, but am still getting the complaint when running daily.sh.

```
Updating to latest codebase                        OK
Updating Composer packages                         FAIL
> LibreNMS\ComposerHelper::preInstall
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - fgrosse/phpasn1 is locked to version v2.4.0 and an update of this package was not requested.
    - fgrosse/phpasn1 v2.4.0 requires php ~7.1.0 || ~7.2.0 || ~7.3.0 || ~7.4.0 || ~8.0.0 || ~8.1.0 -> your php version (8.2.0RC3) does not satisfy that requirement.
  Problem 2
    - fgrosse/phpasn1 v2.4.0 requires php ~7.1.0 || ~7.2.0 || ~7.3.0 || ~7.4.0 || ~8.0.0 || ~8.1.0 -> your php version (8.2.0RC3) does not satisfy that requirement.
    - web-token/jwt-core v2.2.11 requires fgrosse/phpasn1 ^2.0 -> satisfiable by fgrosse/phpasn1[v2.4.0].
    - web-token/jwt-core is locked to version v2.2.11 and an update of this package was not requested.
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK
Caching Mac OUI data                               OK
```

**Comment by murrant** [comment]
This is not a new dependency.  Just a missed dependency in the composer definition.  If you check the install docs, they include xml.

**Comment by 0xc0decafe** [comment]
@tomck I'm on FreeBSD running php 8.1.7. Didn't mention because it shouldn't make a difference.
@murrant Well, I was running without simplexml happily for quite some time now. Haven't found it being mentioned in any documentation though :-/ Anyhow, I have it installed now, as composer forced me to... 

I hope the nightlys are not breaking the setup again.
Closing here.
