### ISSUE TITLE
Weathermap plugin - unable to edit maps 

### ISSUE THREAD

**Issue by JohnyGemityg** [librenms/librenms#14406]
### The problem

Accessing URL where Weathermap editing is done throws an error.

![image](https://user-images.githubusercontent.com/3658238/192973822-be9df78a-8296-48b7-b8c4-a2b59ba09332.png)

[2022-09-29T09:46:35.951671+02:00] production.ERROR: Attempt to assign property "configline" on null {"userId":68,"exception":"[object] (Error(code: 0): Attempt to assign property \"configline\" on null at /opt/librenms/html/plugins/Weathermap/lib/Weathermap.class.php:1926)"} 

### Output of ./validate.php

```txt
bash-4.4$ ./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 22.9.0-14-gf60b6788d
DB Schema | 2022_09_03_091314_update_ports_adsl_table_with_defaults (246)
PHP       | 8.1.10
Python    | 3.6.8
Database  | MariaDB 10.5.9-MariaDB
RRDTool   | 1.7.0
SNMP      | 5.8
====================================

[OK]    Composer Version: 2.4.2
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

**Comment by Jellyfrog** [comment]
[This is not an offical plugin, you have to post your issue ](https://community.librenms.org/c/plugins/15)
