### ISSUE TITLE
ping only monitoring

### ISSUE THREAD

**Issue by demslam** [librenms/librenms#1441]
Would it be possible to add in ping monitoring only? From my understanding (pardon as it is limited) devices are monitored via SNMP, I have multiple devices (cameras, webrelays, PLC) on the network that i would like to be able to monitor when they are responding. I know this is possible in some sense via monitoring the ports on the respective switch, but some of the devices i want to monitor freeze and show the port as active even though the device is not active.
Thank you

**Comment by laf** [comment]
@demslam You want: http://docs.librenms.org/Extensions/Services/

basically once you've set it up as in the instructions. On one of the devices you do have SNMP on (localhost would be good - you are monitoring the LibreNMS box aren't you :)), you can add service checks such as ping with the IP of another device. This can be then used to create alert rules to trigger when the status changes and the additional boxes go down.

**Comment by demslam** [comment]
Thank you for the fast response.
Great i will start playing around with this tonight.
Another question once i add this in would i be able to use the weathermap plugin to show it connected in the network.off of the respective switch.

**Comment by laf** [comment]
I believe that's possible, it won't pull anything out in the webui but Weathermap supports custom items having data pulled afaik:

http://network-weathermap.com/
Data is collected via plugins. Plugins are supplied for RRDtool, MRTG (RRD and old log-format), tab-delimited text files, SNMP, fping, external scripts, and Cacti-specific data. The RRDtool plugin means you have access to data from a large range of open source monitoring tools, including Cacti, Cricket, Zenoss, MRTG, Routers2, Munin, and many more. Other sources are supported via plugins or external scripts.

**Comment by laf** [comment]
Feel free to re-open this if you need to.

**Comment by laf** [comment]
Just an FYI. We now support monitoring devices with only ICMP / PING
