### ISSUE TITLE
"Error discovering discovery-protocols module - Juniper - after update to PHP8.1"

### ISSUE THREAD

**Issue by albertsulva** [librenms/librenms#14474]
### The problem

After needed update PHP to ver 8.1 discovery protocol cannot find any Junipers. Seems to be that code is not fully functional with new PHP. Did I saw that right? Any clues?

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 22.9.0-58-gae3925b09 (2022-10-16T18:15:17+02:00)
DB Schema | 2022_09_03_091314_update_ports_adsl_table_with_defaults (246)
PHP       | 8.1.11
Python    | 3.6.8
Database  | MariaDB 10.3.28-MariaDB
RRDTool   | 1.7.0
SNMP      | 5.8
===========================================
```

### Anything in the logs that might be useful for us?

```txt
production.ERROR: Error discovering discovery-protocols module for x.x.x.x. TypeError: trim(): Argument #1 ($string) must be of type string, array given in /opt/librenms/includes/discovery/discovery-protocols.inc.php:320
[2022-10-17T19:03:04.981623+02:00] production.ERROR: trim(): Argument #1 ($string) must be of type string, array given {"exception":"[object] (TypeError(code: 0): trim(): Argument #1 ($string) must be of type string, array given at /opt/librenms/includes/discovery/discovery-protocols.inc.php:320)"}
```

**Comment by murrant** [comment]
Curious, looks like there was a hidden bug before.  Can you give the full debug output of `./discovery.php -d -m discovery-protocols -h <hostname>`

**Comment by albertsulva** [comment]
Yes, here it is.

`./discovery.php -d -m discovery-protocols -h <hostname>
LibreNMS Discovery
SQL[select `migration` from `migrations` order by `id` desc limit 1 [] 0.61ms]

SQL[select count(*) as aggregate from `migrations` [] 0.42ms]

SQL[select version() [] 0.34ms]

===========================================
Component | Version
--------- | -------
LibreNMS  | 22.10.0-36-g339e3c28b (2022-10-25T23:10:35+02:00)
DB Schema | 2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (248)
PHP       | 8.1.11
Python    | 3.6.8
Database  | MariaDB 10.3.28-MariaDB
RRDTool   | 1.7.0
SNMP      | 5.8
===========================================
DEBUG!
Updating os_def.cache
Override discovery modules: discovery-protocols
SQL[SELECT * FROM `devices` WHERE disabled = 0 AND `hostname` LIKE '<hostname>' ORDER BY device_id DESC [] 0.94ms]

./discovery.php <hostname> 2022-10-26 11:39:38 - 0 devices discovered in 0.252 secs

SNMP [0/0.00s]:
SQL [5/0.03s]: Select[5/0.03s]
RRD [0/0.00s]:
`

Real hostname was changed for testing.

**Comment by PipoCanaja** [comment]
0 device discovered, @albertsulva . Seems that you did not put a real device number after `-h`. 

Could you please do it again: 

`./discovery.php -d -m discovery-protocols -h 123` (for instance, if your deviceID is 123. Replace it with real device ID)

**Comment by albertsulva** [comment]
Yes, you're right. I used hostname not device ID. 

Full output i very long, over 140 text pages that contains many private informations. Can you specify, what you wanna see/paste from here?

This output contains programming bad usage of trim function which I posted first time, here is the snap from discovery.

`
Error discovering discovery-protocols module for X.X.X.X. TypeError: trim(): Argument #1 ($string) must be of type string, array given in /opt/librenms/includes/discovery/discovery-protocols.inc.php:320
Stack trace: #0 /opt/librenms/includes/discovery/discovery-protocols.inc.php(320): trim(Array)
#1 /opt/librenms/includes/discovery/functions.inc.php(153): include('/opt/librenms/i...')
#2 /opt/librenms/discovery.php(106): discover_device(Array, true)
#3 {main}
SQL[insert into `eventlog` (`device_id`, `reference`, `type`, `datetime`, `severity`, `message`, `username`) values (?, ?, ?, ?, ?, ?, ?) [6,null,"discovery","2022-10-31 14:07:44",5,"Error discovering discovery-protocols module. Check log file for more details.",""] 1.76ms]
`

**Comment by PipoCanaja** [comment]
Hi @albertsulva 
Looking at this line : 
`if (strcmp(trim($ptopo['ptopoConnRemoteChassis']), trim($lldp['lldpRemChassisId'])) == 0) { `
it seems that $ptopo['ptopoConnRemoteChassis'] is an array instead of a string. And PHP 8.1 is a little bit stricter with things.
A little bit before the error, the variable should be displayed by this code ` d_echo($ptopo_array); `. Assuming the discovery was run with `-d -v` options. 

Please do that and show the significant parts (or all if possible) of the $ptopo_array variable.

**Comment by albertsulva** [comment]
Hi @PipoCanaja.
 Discovery was runned with -d parameter not -v. But now I run it with -v. Yes, you're right with PHP8.x is stricter and trim does not accept array now. Don't know how/where to run/put that d_echo($ptopo_arrary) code and get that output. Let me know and I'll run it. But there is ptopoConnRemoteChassis var:

` 'ptopoConnRemoteChassis' =>
    array (
      1 =>
      array (
        516 =>
        array (
          18441 => '24 FC 4E F1 80 00',
        ),
      ),
    ),
`

**Comment by PipoCanaja** [comment]
Right, that makes sense. So current code is not expecting array here. And this mib always provides an array. I found a cisco nexus device that also has this MIB, I'll try to reproduce and fix the issue with it.

**Comment by PipoCanaja** [comment]
Hi @albertsulva 
Could you try https://github.com/librenms/librenms/pull/14564 and see if it goes better ?

**Comment by albertsulva** [comment]
Hi @PipoCanaja , sorry for big delay. Was happy to read that and i was tested it out. All seems good to me now. Like:  'ptopoConnRemoteChassis' => '4C 4E 35 FD 2F 80',
Thank you for fixing. For me this issue can be closed.
