### ISSUE TITLE
memcached app polling broken

### ISSUE THREAD

**Issue by Npeca75** [librenms/librenms#14498]
### The problem

Application: memcached, app_id=75SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-Oqv' '-m' 'NET-SNMP-EXTEND-MIB' '-M' '/opt/librenms/mibs' 'udp:HOSTNAME:161' 'nsExtendOutputFull.9.109.101.109.99.97.99.104.101.100']
{"data":{"*:11211":{"pid":134086,"uptime":160,"time":1666503426,"version":"1.5.22","libevent":"2.1.11-stable","pointer_size":64,"rusage_user":0.086749,"rusage_system":0.07144,"max_connections":1024,"curr_connections":2,"total_connections":45,"rejected_connections":43,"connection_structures":40,"reserved_fds":20,"cmd_get":675,"cmd_set":494,"cmd_flush":0,"cmd_touch":0,"cmd_meta":0,"get_hits":566,"get_misses":109,"get_expired":1,"get_flushed":0,"delete_misses":106,"delete_hits":110,"incr_misses":0,"incr_hits":3,"decr_misses":0,"decr_hits":3,"cas_misses":0,"cas_hits":0,"cas_badval":0,"touch_hits":0,"touch_misses":0,"auth_cmds":0,"auth_errors":0,"bytes_read":61732,"bytes_written":45108,"limit_maxbytes":67108864,"accepting_conns":1,"listen_disabled_num":0,"time_in_listen_disabled_us":0,"threads":4,"conn_yields":0,"hash_power_level":16,"hash_bytes":524288,"hash_is_expanding":0,"slab_reassign_rescues":0,"slab_reassign_chunk_rescues":0,"slab_reassign_evictions_nomem":0,"slab_reassign_inline_reclaim":0,"slab_reassign_busy_items":0,"slab_reassign_busy_deletes":0,"slab_reassign_running":0,"slabs_moved":0,"lru_crawler_running":0,"lru_crawler_starts":511,"lru_maintainer_juggles":2082,"malloc_fails":0,"log_worker_dropped":0,"log_worker_written":0,"log_watcher_skipped":0,"log_watcher_sent":0,"bytes":10598,"curr_items":104,"total_items":494,"slab_global_page_pool":0,"expired_unfetched":1,"evicted_unfetched":0,"evicted_active":0,"evictions":0,"reclaimed":1,"crawler_reclaimed":0,"crawler_items_checked":69,"lrutail_reflocked":237,"moves_to_cold":286,"moves_to_warm":80,"moves_within_lru":2,"direct_reclaims":0,"lru_bumps_dropped":0}},"error":0,"errorString":"SUCCESS","version":"1.1"} 

```
Error polling applications module for 127.0.0.1. TypeError: reset(): Argument #1 ($array) must be of type array, null given in /opt/librenms/includes/polling/applications/memcached.inc.php:13
Stack trace:
#0 /opt/librenms/includes/polling/applications/memcached.inc.php(13): reset()
#1 /opt/librenms/includes/polling/applications.inc.php(9): include('...')
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(245): {closure}()
#3 /opt/librenms/includes/polling/applications.inc.php(14): Illuminate\Support\Collection->each()
#4 /opt/librenms/includes/polling/functions.inc.php(340): include('...')
#5 /opt/librenms/poller.php(126): poll_device()
#6 {main} ```

### Output of ./validate.php

```txt
librenms@soada-srv-nms:~$ ./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 22.10.0-21-g056dbc9a5 (2022-10-23T00:24:31+02:00)
DB Schema | 2022_09_03_091314_update_ports_adsl_table_with_defaults (246)
PHP       | 8.1.11
Python    | 3.8.10
Database  | MySQL 8.0.30-0ubuntu0.20.04.2
RRDTool   | 1.7.2
SNMP      | 5.8
===========================================

[OK]    Composer Version: 2.4.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connection to memcached is ok
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

before Fix memcached unserialize vulnerability (#14459) 

### Anything in the logs that might be useful for us?

```txt
downloaded new snmp agent
```

**Comment by andrzejmaczka** [comment]
I have exactly the same issue

**Comment by murrant** [comment]
This is intentional.  Security fix require breakage.  It was a rough one, allowed any device monitored by your install to inject php code.

See #14459 and https://github.com/librenms/librenms-agent/pull/428

**Comment by murrant** [comment]
Can one of you test the linked fix?

**Comment by andrzejmaczka** [comment]
Application: memcached, app_id=494
SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-Oqv' '-m' 'NET-SNMP-EXTEND-MIB' '-M' '/opt/librenms/mibs' 'udp:HOSTNAME:161' 'nsExtendOutputFull.9.109.101.109.99.97.99.104.101.100']

{"data":{"localhost:11211":{"pid":884,"uptime":191090,"time":1666681061,"version":"1.5.22","libevent":"2.1.11-stable","pointer_size":64,"rusage_user":221.953617,"rusage_system":364.976832,"max_connections":1024,"curr_connections":230,"total_connections":200847,"rejected_connections":200846,"connection_structures":614,"reserved_fds":20,"cmd_get":4185467,"cmd_set":3461392,"cmd_flush":0,"cmd_touch":0,"cmd_meta":0,"get_hits":3718811,"get_misses":466656,"get_expired":2508,"get_flushed":0,"delete_misses":750840,"delete_hits":461250,"incr_misses":2,"incr_hits":6352,"decr_misses":0,"decr_hits":6333,"cas_misses":0,"cas_hits":0,"cas_badval":0,"touch_hits":0,"touch_misses":0,"auth_cmds":0,"auth_errors":0,"bytes_read":366184820,"bytes_written":240020634,"limit_maxbytes":67108864,"accepting_conns":1,"listen_disabled_num":0,"time_in_listen_disabled_us":0,"threads":4,"conn_yields":0,"hash_power_level":16,"hash_bytes":524288,"hash_is_expanding":0,"slab_reassign_rescues":0,"slab_reassign_chunk_rescues":0,"slab_reassign_evictions_nomem":0,"slab_reassign_inline_reclaim":0,"slab_reassign_busy_items":0,"slab_reassign_busy_deletes":0,"slab_reassign_running":0,"slabs_moved":0,"lru_crawler_running":0,"lru_crawler_starts":65379,"lru_maintainer_juggles":7716660,"malloc_fails":0,"log_worker_dropped":0,"log_worker_written":0,"log_watcher_skipped":0,"log_watcher_sent":0,"bytes":4964907,"curr_items":45783,"total_items":3461508,"slab_global_page_pool":0,"expired_unfetched":436158,"evicted_unfetched":0,"evicted_active":0,"evictions":0,"reclaimed":390467,"crawler_reclaimed":53907,"crawler_items_checked":18661384,"lrutail_reflocked":17958,"moves_to_cold":844769,"moves_to_warm":291254,"moves_within_lru":179612,"direct_reclaims":0,"lru_bumps_dropped":0}},"error":0,"errorString":"SUCCESS","version":"1.1"}  

  

 memcached()
SQL[update `applications` set `timestamp` = NOW() where `app_id` = ? [494] 0.31ms] 
  

SQL[SELECT * FROM `application_metrics` WHERE app_id=? [494] 0.6ms] 
  

: ......
..........
..


App_state not change ( still unknown) but without any error in log

**Comment by murrant** [comment]
It never set app_state...

**Comment by andrzejmaczka** [comment]
This is not the point, still not updating data.

**Comment by murrant** [comment]
@andrzejmaczka My test system is updating data after the fix applied https://github.com/librenms/librenms/pull/14501.  Perhaps you need to open a separate ticket?

**Comment by murrant** [comment]
Also, I added #14536 so, maybe that will help you diagnose the issue after it is merged.
