### ISSUE TITLE
Plugin blades are no longer shown in the web UI since 22.10

### ISSUE THREAD

**Issue by mbwz** [librenms/librenms#14491]
### The problem

Plugins no longer work since the 22.10 upgrade. Even the ExamplePlugin plugin no longer works. By "not work" I mean none of the widgets or pages that the plugin adds via the blades are shown in the Web UI, even though the plugin shows enabled in the plugin admin menu. Toggling off and on has no effect. None of the log files in the logs directory say anything relevant. I've switched back to the master branch and re-ran daily.sh with no luck, and validate.sh shows no errors. Could this issue be related to this change? https://github.com/librenms/librenms/commit/e990dfcb359badc9cba75ee43499e8772bc323a6

I'm running Debian 11 with PHP 8.1 via the sury repo. I'm getting no errors anywhere I can see, so have nothing to go off of. I made a version 1 test plugin following the docs, and was able to display a blade on a device page, so it seems to just be a version 2 issue.

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 22.10.0-11-ga166df006 (2022-10-21T08:05:49-07:00)
DB Schema | 2022_09_03_091314_update_ports_adsl_table_with_defaults (246)
PHP       | 8.1.9
Python    | 3.9.2
Database  | MariaDB 10.5.15-MariaDB-0+deb11u1
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================

[OK]    Composer Version: 2.4.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### What was the last working version of LibreNMS?

22.7.0

### Anything in the logs that might be useful for us?

```txt
Nothing relevant in any logs in /opt/librenms/logs, or my webserver logs.
```

**Comment by PipoCanaja** [comment]
Hi @mbwz 
It is indeed broken in some way. I am trying to debug it as well, without much success so far. Will update here, and hopefully come with a PR.
