### ISSUE TITLE
Problme with application free radius 

### ISSUE THREAD

**Issue by it008-debug** [librenms/librenms#14535]
### The problem

I have problem with application freeradius 

I get an error like below 

Application: freeradius, app_id=108
SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-Oqv' '-M' '/opt/librenms/mibs' 'udp:HOSTNAME:161' '.1.3.6.1.4.1.8072.1.3.2.3.1.2.10.102.114.101.101.114.97.100.105.117.115']

/etc/snmp/freeradius.sh: line 29: -s: command not found
invalid result from radclient status request, check server settings  

**line 29: RESULT=$(echo "$RADIUS_STATUS_CMD" | $BIN_RADCLIENT -s $RADIUS_SERVER:$RADIUS_PORT status $RADIUS_KEY)**

### Output of ./validate.php

```txt
Component | Version
--------- | -------
LibreNMS  | 22.10.0-41-gd5fcf53 (2022-10-28T12:55:37+02:00)
DB Schema | 2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (248)
PHP       | 8.1.11
Python    | 3.6.8
Database  | MariaDB 10.5.17-MariaDB
RRDTool   | 1.4.8
SNMP      | 5.7.2
===========================================

[OK]    Composer Version: 2.4.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
```

### What was the last working version of LibreNMS?

22.10.0-41

**Comment by murrant** [comment]
That means the variable ` $BIN_RADCLIENT` is empty.  Set it to the location of the binary at the  top of the script.

Also, please file bugs for application scripts on the unix-agent repository.
