### ISSUE TITLE
graph inaccurate titles

### ISSUE THREAD

**Issue by Npeca75** [librenms/librenms#14543]
### The problem

few days ago, strange graph titles started to show on top of graph

ok, i understand, graphs need title
but this is confusing and counter productive
i see that port name and alias is there, but no spacing between and no slash '/', and this leading number is IP without dots 

![lnms](https://user-images.githubusercontent.com/59750439/198885961-126f8139-f6f4-4091-8b16-0da8629746e0.png)

anyone with same problem ?

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 22.10.0-43-g437322f8c (2022-10-30T11:13:41+01:00)
DB Schema | 2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (248)
PHP       | 8.1.11
Python    | 3.8.10
Database  | MySQL 8.0.31-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | 5.8
===========================================

[OK]    Composer Version: 2.4.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connection to memcached is ok
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

last week was ok ... probably

**Comment by Npeca75** [comment]
port name
![lnms2](https://user-images.githubusercontent.com/59750439/198886369-8f7c55cb-2d83-4950-a9a9-233d0985beaf.png)

graph title ???
![lnms3](https://user-images.githubusercontent.com/59750439/198886370-d3eb23bf-018d-4d22-a60f-17df9c372598.png)

**Comment by murrant** [comment]
The titles aren't supposed to be shown by default... I think some boolean check is backwards.

**Comment by murrant** [comment]
@Npeca75 what type of graph is that?  If you don't know paste the url and that will show it.

**Comment by murrant** [comment]
I think that is the hostname (aka IP), but `.` is not allowed :D
