### ISSUE TITLE
Problem with graph application 

### ISSUE THREAD

**Issue by it008-debug** [librenms/librenms#14542]
### The problem

I have problem with graph on application.  Value are correct when I check on debug file  but in graph are generated wrong with different value

FreeRADIUS-Total-Access-Accepts = 17367
FreeRADIUS-Total-Access-Rejects = 55732
FreeRADIUS-Total-Access-Challenges = 0
FreeRADIUS-Total-Auth-Responses = 73099

In graph

![image](https://user-images.githubusercontent.com/116889094/198848986-d5c6875a-ae9f-44bb-bbc3-ef087527c49d.png)

### Output of ./validate.php

```txt
bash-4.2$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 22.10.0-42-g4b65dc4 (2022-10-28T15:06:29+02:00)
DB Schema | 2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (248)
PHP       | 8.1.11
Python    | 3.6.8
Database  | MariaDB 10.5.17-MariaDB
RRDTool   | 1.4.8
SNMP      | 5.7.2
===========================================

[OK]    Composer Version: 2.4.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
```

### What was the last working version of LibreNMS?

22.10.0-41

**Comment by PipoCanaja** [comment]
Hi @it008-debug 
This is expected. The total number is an absolute value, but the graph is showing the derived value (so the variation of this total between 2 polls, displayed in a "per second" unit). It is written "per sec" for "per second".
This graph you show says that you have about 1 RADIUS request every 4 seconds, average, in that previous poll
