### ISSUE TITLE
alerts and alerts-log details column dont show icon

### ISSUE THREAD

**Issue by si458** [librenms/librenms#14570]
### The problem

when you go into the alerts menu or alerts-log menu, the details column should show icons
instead all it shows is a square icon with numbers in (like its missing the font)
![Screenshot 2022-11-03 144044](https://user-images.githubusercontent.com/765314/199751987-ae8d8a60-1a51-49ac-87b0-225459ebe724.png)

it also appears the `fa-info` was never migrated from font awesome 4 to 6 ?
https://fontawesome.com/docs/web/setup/upgrade/upgrade-from-v4#icons-renamed-since-version-4

### Output of ./validate.php

```txt
librenms@librenms:~$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 22.10.0-66-g0c365d08e (2022-11-02T23:50:46+00:00)
DB Schema | 2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (248)
PHP       | 8.1.12
Python    | 3.8.10
Database  | MariaDB 10.3.34-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | 5.8
===========================================

[OK]    Composer Version: 2.4.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
librenms@librenms:~$
```

**Comment by murrant** [comment]
Noticed that the other day.  Turns out mixing font awesome classes into the button icons doesn't work like it used to on older version.
