### ISSUE TITLE
Documentation inconsistent for docker application

### ISSUE THREAD

**Issue by marcusry** [librenms/librenms#14607]
### The problem

Hello,

the last 2 days I struggled getting the docker-application based on the docker-stats.sh script running. While searching for the reason of the not working application, I run over some inconsistencies in the documentation. 

1. The original documentation suggests to add the snmp user (in my case Debian-snmp) to the docker system group. However, I found some interesting discussions on stackoverflow, which suggest to not add the snmp user to docker group, as the snmp process may gain root access in non rootless docker installations, which is quite plausible to me. The solution, which also worked for me, was to utilize sudo, to allow the execution of the script. 

2. The second issue is more severe. I struggled with the snmp response of our server, because librenms did not display the docker stats. A closer look using the included bug tracking (capture) option revealed no informative errors, except that the librenms snmp process stopped a few MIBs after the beginning of the applications part, if the extension was enabled. After trying different solutions e.g. the extension of the poller timeout, which was the most promising solution in the internet, I finally solved the issue by activating the **librenms-query-optimizer**. I guess the json-string produced by the docker-stats.sh script is to long, which leads to the crash of the snmp process. We are running a small docker environment for development purposes with currently round about 5 containers. Hence, this was a bit unexpected for me. Therefore, I suggest adding a few words regarding the optimizer to prevent others to struggle with this error. 

I can offer to add a few notes the documentation and create a pull request further one. However, I expect its not so much work an a more experienced developer may want to do this. Just give me a hint about your preferred workflow. 

Thanks to all for the effort in this excellent project. :-) 

Best wishes - Marcus

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 22.10.0-96-g0e9bb0407 (2022-11-08T18:22:37+01:00)
DB Schema | 2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (248)
PHP       | 8.1.12
Python    | 3.8.10
Database  | MariaDB 10.3.34-MariaDB-0ubuntu0.20.04.1-log
RRDTool   | 1.7.2
SNMP      | 5.8
===========================================
[OK]    Composer Version: 2.4.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Your install is over 24 hours out of date, last update: Tue, 08 Nov 2022 17:22:37 +0000
        [FIX]:
        Make sure your daily.sh cron is running and run ./daily.sh by hand to see if there are any errors.
```

### What was the last working version of LibreNMS?

22.10

### Anything in the logs that might be useful for us?

```txt
Error in librenms SNMP-Capture:

SNMP error: (genError) A general failure occurred
```

**Comment by murrant** [comment]
Any documentation improvements are welcome.

Some of the docs do suggest sudo solutions, which is reasonable to me.  The application docs are very inconsistent among themselves and probably need to de-duplicated.
