### ISSUE TITLE
Bug: RIPE NCC API Tool:  RipeApi.php

### ISSUE THREAD

**Issue by lynch4fr** [librenms/librenms#14602]
### The problem

Hello,
I have opened my original application here [https://community.librenms.org/t/configure-ripe-ncc-api-tools/20100](url)

And I supose there is a bug in the code of the file
librenms/app/ApiClientsRipeApi.php
the request URL should no longer contain "?query=..." but "?resource="

Here is the diff when I made a conclusive test : `diff RipeApi.php RipeApi.php.sav` 

'resource' => $resource
---
'query' => [ 'resource' => $resource, ],

Thanks

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 22.10.0-92-gb807fd526 (2022-11-07T21:28:16+01:00)
DB Schema | 2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (248)
PHP       | 8.1.12
Python    | 3.8.10
Database  | MariaDB 10.3.34-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | 5.8
===========================================

[OK]    Composer Version: 2.4.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### What was the last working version of LibreNMS?

22.10.0-92

**Comment by murrant** [comment]
It looks like you have a fix in that post.  Could you submit it to LibreNMS?  Just go to the file in github and click the edit button.

**Comment by lynch4fr** [comment]
Merci je vais essayer de faire ca :-)
