### ISSUE TITLE
Is it possible to use the old style interconnect maps?

### ISSUE THREAD

**Issue by masonke** [librenms/librenms#1461]
Is there a way to use the old style interconnection maps vs the elastic maps? The older version was a lot easier to read. The new style tends to bunch up in a ball and when pulled about, snaps back.

**Comment by laf** [comment]
Hi @masonke, do you mean the very old map from when we forked or from last week before the last update?

On the new map they shouldn't bunch up into a ball and zoom into a good level (you can then zoom again).

**Comment by masonke** [comment]
Hi @laf 
I believe the map from last week is what I am referring to. To be sure, I have included a screenshot as static_map.jpg . As you can see in the Elastic_map.jpg, the interface names are covered up with the new map style. Dragging the devices opens this up, but when the mouse is released, it bounces back. It is particularly bothersome when there are multiple interfaces between 2 devices, such as a LAG.

![static_map](https://cloud.githubusercontent.com/assets/1863778/8732704/1cf3ad76-2bcd-11e5-9479-f2621b660b11.jpg)
![elastic_map](https://cloud.githubusercontent.com/assets/1863778/8732709/23de0582-2bcd-11e5-9ebc-5b87112b9e20.jpg)

**Comment by laf** [comment]
Wow, you've not updated in a while :) That is something that was changed in March :)

Does it show you the data you need? We can make it more visible I'm sure.

**Comment by slm4996** [comment]
Here is another random vote for the old, fixed, map. The new elastic, octo-map is horrendous. It's always played out in a different shape/layout and tangled up + overlapping. It's basically useless.

**Comment by laf** [comment]
Wow don't hold back guys

**Comment by masonke** [comment]
I would not say it is horrendous at all, it is a pretty cool display.  If there was a way to move the devices and have them stay in a place, it would be fine.

@laf As to the not updating, i did a trial with the virtual image last week and thought it had updated. When I built another VM for full testing this week, the update worked and I discovered the Elastic map. 

If there was a way to move things around and make them stay, that would be fine. The static maps, were perfect to give to a Tier 1 person, meaning nice and predictable at 2am. :)

**Comment by slm4996** [comment]
Horrendous may have been a bit harsh. However a map is next to useless when it is not static (layed out in same order each time it is displayed).

**Comment by laf** [comment]
#1470 Now sets the map out to be the same each time + other updates which may make it more useful for you.

If not - and as is the good thing about open source - you're more than welcome to re-introduce the old network map that existed but this needs to be done by a config option so people can have the choice. However please be aware that if you're network map is drawn from data from the ipv4_mac table then the old network map will not work.

**Comment by masonke** [comment]
That was fast, thank you very much!  I will check this out tonight.

**Comment by laf** [comment]
It's not merged just yet.

**Comment by laf** [comment]
Merged in, please re-open this if it's still not right for you.

**Comment by masonke** [comment]
Just tried it and it is much better, thank you! There are some oddities that may or may not be fixable.I have included some annotated screen shots that can show what I mean. My job does include testing software, so my apologies if the information seems too detailed.  For this test, I selected wnd-rack-a03 and ran the map off that.

* When let go, devices drift over the interface labels of other device, blocking them.

* The device Rack-a03 has a pair of 2x 1gig-e , layer 2 port-channels (lag) to a pair of core routers. On one, it shows as a pair of grey lines, on the other as a single blue line. Having this show as different lines is the preferred option, if possible.

* For some of the interfaces, the label starts with VL

* When hovering over the interface labels and lines, only the rack-a03 interface information is show, not the information from the other device

* When hovering over the lines, the popup displays only the device name, not the interface name. Should it show the interface?

As a side note, when I selected either of the core routers, the cpu load shot up and the screen crawled. When the screen settled, trying to select and then move each generated a spinning beach ball. For maps over 20 interfaces, the dynamic repositioning might be too much work. I will play with this some more and see where the bottleneck is.
![overlap-int_names_hidden](https://cloud.githubusercontent.com/assets/1863778/8764155/277af65c-2d92-11e5-8c91-1de6961ab450.jpg)
![port channels display differently](https://cloud.githubusercontent.com/assets/1863778/8764152/27762dde-2d92-11e5-89a6-9f124b7214d9.jpg)
![stats_pointing_to_esx_host](https://cloud.githubusercontent.com/assets/1863778/8764153/2776d360-2d92-11e5-9f01-33bb5f5f1a61.jpg)
![stats-pointing_to_wnd-rack-a03-int](https://cloud.githubusercontent.com/assets/1863778/8764154/27791c60-2d92-11e5-84c5-3c50ff871517.jpg)

**Comment by laf** [comment]
Rather than me push another update can you try my branch (I'm assuming you don't have any local customisation):

```bash
cd /opt/librenms
git remote add laf https://github.com/laf/librenms.git
git remote update laf
git checkout issue-1461
```

When you've tested you can go back to master at any stage by doing:

```bash
git checkout master
```

**Comment by masonke** [comment]
A little better on the device overlapping the interfaces. The port channels are really overlapped by each other. 
From a performance point, when there are 15 interconnects displayed, the browser just locks with a spinning beach ball.
![patch-1461-a](https://cloud.githubusercontent.com/assets/1863778/8775577/7aaf2fe8-2eb7-11e5-8690-3c973065ac65.jpg)
