### ISSUE TITLE
Test 

### ISSUE THREAD

**Issue by Jellyfrog** [librenms/librenms#14651]
### The problem

@phptinker 
```php
collect([1,2,3]);
```

### Output of ./validate.php

```txt
.
```

**Comment by phptinker** [comment]
@Jellyfrog, here's the evaluated code:

```
Illuminate\Support\Collection {#966
  all: [
    1,
    2,
    3,
  ],
}
```

<details>
<summary>We evaluated this code</summary>

```php
collect([1,2,3]);
```
</details>

Check out [Tinkerwell](https://tinkerwell.app) for even easier code evaluation.
