### ISSUE TITLE
Missing RRD for sensors etc

### ISSUE THREAD

**Issue by tamikkelsen** [librenms/librenms#14662]
### The problem

Missing data files for sensors. 
![Skjermbilde 2022-11-22 kl  08 20 21](https://user-images.githubusercontent.com/575045/203250080-e4e0569a-5fad-4475-9bb1-7c5b2416f758.png)

Some RRD files are created like, memory, cpu, traffic etc.. but temperature, voltage sensors and more are not created. I get the following error message from RRD Command when clicking on the sensor:

ERROR: rrdcached@unix:/run/rrdcached.sock: rrd_fetch_r failed: opening '/opt/librenms/rrd/device_ip/sensor-voltage-cisco-entity-sensor-7017.rrd': No such file or directory

### Output of ./validate.php

```txt
./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 22.10.0-135-g7635ace4f (2022-11-20T05:10:25+01:00)
DB Schema | 2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (248)
PHP       | 8.1.12
Python    | 3.8.10
Database  | MySQL 8.0.31-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | 5.8
===========================================

[OK]    Composer Version: 2.4.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No active python wrapper pollers found
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

**Comment by murrant** [comment]
Need the poller debug logs for when it should be putting data into those files.

**Comment by tamikkelsen** [comment]
http://dpaste.com//CQCHSWNQ4

**Comment by tamikkelsen** [comment]
http://dpaste.com//7HF4V4ZBS <- debug + verbose

**Comment by murrant** [comment]
You disabled the sensors module which does the polling for the cisco-entity-sensor discovery module.

`Module [ sensors ] disabled globally.`
