### ISSUE TITLE
POST size exhaust when attempting to ignore many (200) ports

### ISSUE THREAD

**Issue by mkaipov** [librenms/librenms#1467]
Hello guys.
I have little issue with adding our Nexus 5k to LibreNMS. We have many amount of free ports which LIbreNMS highlighted as issue (Port Down) I try to set this ports as ignored, by I can't. Nearly 210 ports set to be ignored others is not. Paul Gear help me to fix it through mysql console.It was issue with max number of postable items. To resolve issue Paul advice me manualy set down ports to be ignored by sql query.
update `ports` set `ignore` = 1 where `ifoperstatus` = 'down' and `device_id` = ###;

**Comment by tylerapplebaum** [comment]
What version of code do you have on your N5k? I have both of mine with 8 FEXs attached and everything shows up properly.

**Comment by paulgear** [comment]
@tylerapplebaum The issue seemed to be with the limit on the size of an HTTP POST request.  It's not really anything specific to Nexus 5K; it could happen on any device with a large number of ports.

**Comment by mkaipov** [comment]
@tylerapplebaum In my case I have N5k (5596) with code ver 5.2.1 and 14 FEX N2K-C2248TP-E-1GE. So you can see, I have too much ports. As @paulgear say there is issue with HTTP POST request and was fixed by sql magic.

**Comment by laf** [comment]
Should be sorted now, if you can close this issue please @mkaipov

**Comment by f0o** [comment]
I can close it :)
