### ISSUE TITLE
32bit restriction with application wireguard

### ISSUE THREAD

**Issue by efelon** [librenms/librenms#14688]
### The problem

I have a long running wireguard on a (still 32bit) raspberry pi 4 Debian buster:
`Linux 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux`

Some of the peers have high values for send/receive transfer counter. e.g.:
```
peer: ***  mobile_mw
  preshared key: (hidden)
  endpoint: *:*
  allowed ips: *
  latest handshake: 1 minute, 56 seconds ago
  transfer: 761.16 MiB received, 3.83 GiB sent
```

Althoug the absolute byte values output by `wg show all dump` are not at the limit:
```
4113015344 (value by wg)
4294967296 (2^32)
```
the graphs in the web ui show nand for these values. As a test I modified `wireguard.py` as follows, which "fixes" the display problem in the web ui:
```
[...]
        bytes_rcvd = long(line_parsed[6]) / 1000
        bytes_sent = long(line_parsed[7]) / 1000
[...]
```

I'm pretty sure, the 32bit OS/php/python is the problem somehow, but wanted to report this behavior in case there is another solution other than "32bit is not supported any more".

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 22.11.0 (2022-11-24T07:01:26+01:00)
DB Schema | 2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (248)
PHP       | 8.1.12
Python    | 3.7.3
Database  | MariaDB 10.3.36-MariaDB-0+deb10u2
RRDTool   | 1.7.1
SNMP      | 5.7.3
===========================================

[OK]    Composer Version: 2.4.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[WARN]  Using database for locking, you should set CACHE_DRIVER=redis
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

**Comment by murrant** [comment]
Please report this on the https://github.com/librenms/librenms-agent repository and if you have a fix, I suggest you submit it.

**Comment by efelon** [comment]
@murrant I opened it here "first" because the numbers by the `wireguard.py` script are correctly fetched from the output. Isn't it more possible that the graph creation/rrd is somehow messing this up?

**Comment by murrant** [comment]
Unsure, I have no way to test it.  If there is a 32bit restriction, likely your are running 32bit software somewhere and storing/passing numbers as integers instead of strings.

Pretty unlikely that they are messed up on the LibreNMS side, it just stores the values it gets and then graphs those., should be no manipulation.

**Comment by efelon** [comment]
I moved my LibreNMS installation to 64bit, which solved the display problem (see details [here](https://github.com/librenms/librenms-agent/issues/445#issuecomment-1341635439)). Maybe your command about strings means anything to @bnerickson?!
