### ISSUE TITLE
Device Overview -> Notes section "App\Plugins\Hooks\DeviceOverviewHook"

### ISSUE THREAD

**Issue by Bierchermuesli** [librenms/librenms#14698]
### The problem

Same as mentioned by someone else in the [community Forum](https://community.librenms.org/t/can-anyone-tell-me-why-i-have-this-in-the-header-of-what-appears-to-be-the-notes-section-of-the-device-overview-screen/17168), my note section looks strange::

![image](https://user-images.githubusercontent.com/13567009/205665952-6d3e5890-a096-4f44-bc81-1a40a5d0d197.png)

tried on different browser, in prod and on my local dev enviroment (fresh from git)

any guess or advice to troubleshoot?

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 22.10.0-135-g7635ace4f (2022-11-20T05:10:25+01:00)
DB Schema | 2021_02_09_122930_migrate_to_utf8mb4 (248)
PHP       | 8.1.12
Python    | 3.9.2
Database  | MariaDB 10.5.15-MariaDB-0+deb11u1
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================

[OK]    Composer Version: 2.4.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    Python wrapper cron entry is not present
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

**Comment by electrocret** [comment]
That's from the example plugin and is supposed to be like that to show potential plugin developers how to use it. 

You could make your own plugin by copying the example plugin then editing Line 5 in /app/Plugins/ExamplePlugin/resources/views/device-overview.blade.php from " {{ Title }}" to "Notes".

**Comment by Bierchermuesli** [comment]
dammit, thanks for the enlightenment!
