### ISSUE TITLE
Cisco Switches report incorrect DOM data from SFP

### ISSUE THREAD

**Issue by Jumb0Fr4m3** [librenms/librenms#14749]
### The problem

It seems like We are getting incorrect transceiver data when polling snmp data from the switches.

Look at this example:

Reported from the switch:
                                             Optical   Optical
             Temperature  Voltage  Current   Tx Power  Rx Power
Port         (Celsius)    (Volts)  (mA)      (dBm)     (dBm)
---------    -----------  -------  --------  --------  --------
Gi1/1/4      41.3       3.26      22.1      -4.8      -3.6   

Debug from LibreNMS poller:

SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-OUQntea' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' 'udp:HOSTNAME:161' '.1.3.6.1.4.1.9.9.91.1.1.1.1.4.1119' '.1.3.6.1.4.1.9.9.91.1.1.1.1.4.1124' '.1.3.6.1.4.1.9.9.91.1.1.1.1.4.1120' '.1.3.6.1.4.1.9.9.91.1.1.1.1.4.1125']
.*.*.*.1.4.1119 = 0
.*.*.*.1.4.1124 = -4
.*.*.*.1.4.1120 = 0
.*.*.*.1.4.1125 = -3  
  
Checking (snmp) dbm Gi1/1/3 Transmit Power... 
Checking (snmp) dbm Gi1/1/4 Transmit Power... 
Checking (snmp) dbm Gi1/1/3 Receive Power... 
Checking (snmp) dbm Gi1/1/4 Receive Power... 
0 dBm
RRD[last 10.8.4.5/sensor-dbm-cisco-entity-sensor-1119.rrd  --daemon librenms.svgkomm.svgdrift.no:42217]  
RRD[update 10.8.4.5/sensor-dbm-cisco-entity-sensor-1119.rrd N:0 --daemon librenms.svgkomm.svgdrift.no:42217]  
-0.4 dBm
RRD[last 10.8.4.5/sensor-dbm-cisco-entity-sensor-1124.rrd  --daemon librenms.svgkomm.svgdrift.no:42217]  
RRD[update 10.8.4.5/sensor-dbm-cisco-entity-sensor-1124.rrd N:-0.4 --daemon librenms.svgkomm.svgdrift.no:42217]  
0 dBm
RRD[last 10.8.4.5/sensor-dbm-cisco-entity-sensor-1120.rrd  --daemon librenms.svgkomm.svgdrift.no:42217]  
RRD[update 10.8.4.5/sensor-dbm-cisco-entity-sensor-1120.rrd N:0 --daemon librenms.svgkomm.svgdrift.no:42217]  
-0.3 dBm
RRD[last 10.8.4.5/sensor-dbm-cisco-entity-sensor-1125.rrd  --daemon librenms.svgkomm.svgdrift.no:42217]  
RRD[update 10.8.4.5/sensor-dbm-cisco-entity-sensor-1125.rrd N:-0.3 --daemon librenms.svgkomm.svgdrift.no:42217]  

It seems to update with the incorrect value. The correct number seems to be divided by 10 before entered into the system????
(-4 turns into -0.4 and -3 turns into -0.3)

### Output of ./validate.php

```txt
-bash-4.2$ ./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 22.11.0-36-g098bbc6 (2022-12-20T14:58:01+01:00)
DB Schema | 2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (252)
PHP       | 8.1.13
Python    | 3.6.8
Database  | MariaDB 10.2.44-MariaDB
RRDTool   | 1.7.1
SNMP      | 5.7.2
===========================================

[OK]    Composer Version: 2.4.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    Python wrapper cron entry is not present
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### Device info

Cisco 3650 and Cisco 9300

### Discovery output

```txt
-
```

### Poller output

```txt
-
```

**Comment by Bierchermuesli** [comment]
I don't have an issue with 3650/9300 - can you verify if resolvend in the meantime - if yes please close this issue

**Comment by Jumb0Fr4m3** [comment]
It seems to be fixed now.
Not sure what has caused this, I upgraded the 9300 to 17.6.5 and 3650 to 16.12.9 so that might have fixed it.
