### ISSUE TITLE
Librenms Extend Pihole Not Working

### ISSUE THREAD

**Issue by mxmartins** [librenms/librenms#14758]
### The problem

Due to auth changes to pihole api (https://pi-hole.net/blog/2022/11/17/upcoming-changes-authentication-for-more-api-endpoints-required/#page-content), snmp extend scrip no longer works

### Output of ./validate.php

```txt
not needed.
```

### Anything in the logs that might be useful for us?

```txt
Librenms script to extend snmp monitoring must be changes to include auth in the URL_READ_ONLY and GET_STATS must include the addition of the API_AUTH_KEY.
```

**Comment by mxmartins** [comment]
New /etc/snmp/pi-hole script `attached....

[pi-hole.txt](https://github.com/librenms/librenms/files/10304673/pi-hole.txt)

**Comment by GerritS76** [comment]
Looks like something has changed at the Pi-Hole end, summaryRaw now seem to require a auth.

A temporary (working) fix?:
Edit your /etc/snmp/pi-hole and change "URL_READ_ONLY" from;
?summaryRaw
to
?summaryRaw&auth=$API_AUTH_KEY

So the full line shows:
URL_READ_ONLY="?summaryRaw&auth=$API_AUTH_KEY"
