### ISSUE TITLE
Duplicate events "Device status changed to ... from icmp check."

### ISSUE THREAD

**Issue by MANT5149** [librenms/librenms#14751]
### The problem

We are using fast ping checks. When device statuses change to up or down due to icmp checks, there are duplicate event log messages created.

A screenshot is show below
![events](https://user-images.githubusercontent.com/71085838/208953711-2e729eda-9ca6-406a-bf77-aca13eb3b898.PNG)

I believe the following code is causing this:
https://github.com/librenms/librenms/blob/71d740770b4c10ec3bce612b61142df6cb5b1a13/app/Observers/DeviceObserver.php#L43

https://github.com/librenms/librenms/blob/71d740770b4c10ec3bce612b61142df6cb5b1a13/app/Jobs/PingCheck.php#L257

Is it possible to add additional checking to one of these files so that only one event log entry is generated?

Thank you!

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 22.11.0 (2022-11-23T22:01:26-08:00)
DB Schema | 2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (248)
PHP       | 8.1.13
Python    | 3.9.2
Database  | MariaDB 10.5.15-MariaDB-0+deb11u1
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================

[OK]    Composer Version: 2.4.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

**Comment by murrant** [comment]
Probably the one in PingCheck just needs to be removed. It was needed there at one time, but no longer.
