### ISSUE TITLE
Alerting - Pushbullet

### ISSUE THREAD

**Issue by itscassa** [librenms/librenms#1478]
Hi,

I would like to see Pushbullet as an alert target.
I'll try to create this myself once I have more free time.

https://docs.pushbullet.com/

**Comment by MLWALK3R** [comment]
+1 for pushbullet

**Comment by f0o** [comment]
kk

**Comment by f0o** [comment]
@casdr / @MLWALK3R please test my branch 'issue-1478' and report back in the PR #1721 

Thanks!
