### ISSUE TITLE
Force proxy in oxidized function

### ISSUE THREAD

**Issue by ExcelonBlackCat** [librenms/librenms#14849]
### The problem

Hi,
i have an issue if i want to refresh a node for oxidized :
[Screenshot](https://pasteboard.co/Ignc7CqgKtVn.png)

In the function  oxidized_node_update, we can see proxy set :
```
function oxidized_node_update($hostname, $msg, $username = 'not_provided')
{
    // Work around https://github.com/rack/rack/issues/337
    $msg = str_replace('%', '', $msg);
    $postdata = ['user' => $username, 'msg' => $msg];
    $oxidized_url = Config::get('oxidized.url');
    if (! empty($oxidized_url)) {
        Requests::put("$oxidized_url/node/next/$hostname", [], json_encode($postdata), ['proxy' => get_proxy()]);
        return true;
    return false;
}
```

But function get_proxy don't care about no_proxy :
```
function get_proxy()
{
    if (getenv('http_proxy')) {
        return getenv('http_proxy');
    } elseif (getenv('https_proxy')) {
        return getenv('https_proxy');
    } elseif ($callback_proxy = Config::get('callback_proxy')) {
        return $callback_proxy;
    } elseif ($http_proxy = Config::get('http_proxy')) {
        return $http_proxy;
    }
    return false;
}
```

In case i use a docker-compose so my containers are on same network so i use proxy only to go outside my host.
Haved fix it with Requests::put("$oxidized_url/node/next/$hostname", [], json_encode($postdata)); but if i rebuild i delete my change :'(

### Output of ./validate.php

```txt
/opt/librenms/includes/functions.php
```

### Anything in the logs that might be useful for us?

```txt
{
    "message": "cURL error 35: error:1408F10B:SSL routines:ssl3_get_record:wrong version number",
    "exception": "Requests_Exception",
    "file": "/opt/librenms/vendor/rmccue/requests/library/Requests/Transport/cURL.php",
    "line": 443,
    "trace": [
        {
            "file": "/opt/librenms/vendor/rmccue/requests/library/Requests/Transport/cURL.php",
            "line": 179,
            "function": "process_response",
            "class": "Requests_Transport_cURL",
            "type": "->"
        },
        {
            "file": "/opt/librenms/vendor/rmccue/requests/library/Requests.php",
            "line": 381,
            "function": "request",
            "class": "Requests_Transport_cURL",
            "type": "->"
        },
        {
            "file": "/opt/librenms/vendor/rmccue/requests/library/Requests.php",
            "line": 276,
            "function": "request",
            "class": "Requests",
            "type": "::"
        },
        {
            "file": "/opt/librenms/includes/functions.php",
            "line": 2140,
            "function": "put",
            "class": "Requests",
            "type": "::"
        },
        {
            "file": "/opt/librenms/includes/html/forms/refresh-oxidized-node.inc.php",
            "line": 17,
            "function": "oxidized_node_update"
        },
        {
            "file": "/opt/librenms/html/ajax_form.php",
            "line": 28,
            "function": "include_once"
        }
    ]
}
```

**Comment by chrismooredev** [comment]
Looks like we'll get no_proxy support in #14763, that's also something I'm interested in.

We use a locally hosted Oxidized server that sometimes causes errors (specifically when adding/removing) devices. We use an HTTP proxy for our LibreNMS server to reach out to our alerting system, and the proxy doesn't allow internal connections to go through it. We need to exclude Oxidized from that proxy, and we think no_proxy is the way to go.

**Comment by murrant** [comment]
@chrismooredev #14763 is ready now.  Any chance you could test it?

**Comment by chrismooredev** [comment]
@murrant I'd have to get a test instance setup within my organization to enable proxy usage, but unfortunately, we're tied up with other projects at the moment so I can't guarantee when that could happen (probably at least a few weeks, if not a few months...) I'd love to, I just don't know if I can in a reasonable timeframe :)

**Comment by laf** [comment]
Closing as support for no_proxy now exists.
