### ISSUE TITLE
Unsetting non-existing variables at includes/port-descr-parser.inc.php

### ISSUE THREAD

**Issue by Txxkirsch** [librenms/librenms#14850]
### The problem

Hello,

File: includes/port-descr-parser.inc.php

it seems that at the bottom of the script unused variable get unset (like $port_type).
Imo it should be `unset($type, $descr ...);`

Greetings

### Output of ./validate.php

```txt
dont have output. Just seen it in the file
```

**Comment by electrocret** [comment]
Heh, good catch. I submitted a PR to address this.
