### ISSUE TITLE
Incorrect storage values in TrueNAS Scale 22.12.1

### ISSUE THREAD

**Issue by Leppunen** [librenms/librenms#14865]
### The problem

Adding a new TrueNAS Scale (Version 22.12.1) into LibreNMS seems to show incorrect storage measurements, and there is an error parsing the zpoolTable when doing a storage discovery.

I did some investigation and it looks like that the version of the FREENAS-MIB in LibreNMS is too old to read out the data from this version of TrueNAS properly. ( Fields like zpoolAllocationUnits read out as "ONLINE" for example)

Related iXsystems ticket: https://ixsystems.atlassian.net/browse/NAS-120434 (Apparently lots of OID related things got changed in this version of TrueNAS)

iXsystems distributes new MIB versions as part of the OS, and the current version is available here: https://p.libren.ms/view/54921699

For reference, here are the differences of the data when polled via both new and old MIBs

zpoolTable:
Old MIB: https://p.libren.ms/view/c6bb18b0
New MIB: https://p.libren.ms/view/c857f42f

dataSetTable:
Old MIB: https://p.libren.ms/view/415ea4cb
New MIB: https://p.libren.ms/view/281daf03

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.2.0-3-gc0fd1e15e (2023-02-24T12:10:10+00:00)
DB Schema | 2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (248)
PHP       | 8.2.3
Python    | 3.10.6
Database  | MariaDB 10.11.2-MariaDB
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.5.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### Device info

TrueNAS / FreeNAS

### Discovery output

```txt
Only the storage module is included, since the issue is related to storage specifically.

https://p.libren.ms/view/6f8b3adc
```

### Poller output

```txt
Only the storage module is included, since the issue is related to storage specifically.

https://p.libren.ms/view/0835bea2
```

**Comment by Jellyfrog** [comment]
Hi. Device requests go here; https://community.librenms.org/c/device-requests/12

You could try simply replace the mib and see what happens, might get lucky there.
