### ISSUE TITLE
DivisionByZeroError: Division by zero in /opt/librenms/includes/discovery/functions.inc.php:959

### ISSUE THREAD

**Issue by G0nz0uk** [librenms/librenms#14877]
### The problem

Hello,

We use LibreNMS to monitor some custom devices which was working fine on a previous version on LibreNMS when on php .7.x.  I think the upgrade to php 8.1 many months ago broke this for us, but we've only just noticed.

Basically this device (we have 100s) cannot be discovered and when using the discovery.php I see the error:

`Error discovering sensors module for 10.123.30.208. DivisionByZeroError: Division by zero in /opt/librenms/includes/discovery/functions.inc.php:959`

Full output - https://pastebin.com/SSBbdJUp

Forum post - https://community.librenms.org/t/error-discovering-device-divisionbyzeroerror-division-by-zero-php/20964

Please advise/help

Thanks

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.2.0-15-gd7a7e0c15 (2023-03-04T18:00:31+00:00)
DB Schema | 2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (248)
PHP       | 8.1.2-1ubuntu2.11
Python    | 3.10.6
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.5.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    Python wrapper cron entry is not present
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
[WARN]  Your local git contains modified files, this could prevent automatic updates.
	[FIX]: 
	You can fix this with ./scripts/github-remove
	Modified Files:
	 rrd/.gitignore
```

**Comment by G0nz0uk** [comment]
Possible fix by adding this to the functions.inc.php in /opt/librenms/includes/discovery

Added this to like 936

`$divisor = $divisor === 0 ? 1 : $divisor;`

like this


```
                    $divisor = $data['divisor'] ?? ($sensor_options['divisor'] ?? 1);
                    $divisor = $divisor === 0 ? 1 : $divisor;
                    $multiplier = $data['multiplier'] ?? ($sensor_options['multiplier'] ?? 1);
```

**Comment by murrant** [comment]
Likely the problem is in your custom os specification.

**Comment by G0nz0uk** [comment]
Not sure, I posted my issue on the PHP Reddit forum in the end and they said the issue is the functions.ini.php when does account for 0 values, so they helped and suggested the fix is to add this and all works now:

$divisor = $divisor === 0 ? 1 : $divisor;

**Comment by murrant** [comment]
@G0nz0uk That is what I'm saying $divisor will never be 0 in LibreNMS code.
