### ISSUE TITLE
TrueNAS / FreeNAS Storage poller zilstat data pulled into wrong sensor, zpool state sensor updates with storage size value

### ISSUE THREAD

**Issue by hugalafutro** [librenms/librenms#14881]
### The problem

After recent update of Truenas SCALE Bluefin I noticed LibreNMS spams `Error discovering storage module. Check log file for more details.` in Event Log.

librenms.log has this:
```
[2023-03-07T07:16:33.612927+00:00] production.ERROR: Error discovering storage module for turbofreenas.lan. TypeError: Unsupported operand types: string * string in /opt/librenms/includes/discovery/storage/freenas-zpool.inc.php:13
Stack trace:
#0 /opt/librenms/includes/include-dir.inc.php(6): include()
#1 /opt/librenms/includes/discovery/storage.inc.php(7): require('...')
#2 /opt/librenms/includes/discovery/functions.inc.php(153): include('...')
#3 /opt/librenms/discovery.php(106): discover_device()
#4 {main}
[2023-03-07T07:16:33.679870+00:00] production.ERROR: Unsupported operand types: string * string {"exception":"[object] (TypeError(code: 0): Unsupported operand types: string * string at /opt/librenms/includes/discovery/storage/freenas-zpool.inc.php:13)"}
[2023-03-07T07:16:36.789458+00:00] production.ERROR: No Storage {"userId":2,"exception":"[object] (LibreNMS\\Exceptions\\RrdGraphException(code: 0): No Storage at /opt/librenms/includes/html/graphs/device/storage.inc.php:14)"}
[2023-03-07T07:16:36.807317+00:00] production.ERROR: No Storage {"userId":2,"exception":"[object] (LibreNMS\\Exceptions\\RrdGraphException(code: 0): No Storage at /opt/librenms/includes/html/graphs/device/storage.inc.php:14)"}
[2023-03-07T07:16:36.925426+00:00] production.ERROR: No Storage {"userId":2,"exception":"[object] (LibreNMS\\Exceptions\\RrdGraphException(code: 0): No Storage at /opt/librenms/includes/html/graphs/device/storage.inc.php:14)"}
/opt/librenms/discovery.php 38 2023-03-07 07:16:44 - 1 devices discovered in 27.33 secs
```

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.1.1 (2023-02-09T19:33:37+00:00)
DB Schema | 2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (248)
PHP       | 8.1.15
Python    | 3.10.10
Database  | MariaDB 10.5.19-MariaDB-1:10.5.19+maria~ubu2004
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Installed from package; no Composer required
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No python wrapper pollers found
[OK]    Redis is functional
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Non-git install, updates are manual or from package
```

### Device info

TrueNAS SCALE 22.12.1

### Discovery output

[https://o.o5.ddns.net/M3iHY](https://o.o5.ddns.net/M3iHY)

### Poller output

[https://o.o5.ddns.net/iyMEX](https://o.o5.ddns.net/iyMEX)

**Comment by murrant** [comment]
Uh, this is supposed to be a number (from your discovery output):

```
zpoolAllocationUnits.1 = "ONLINE"
zpoolAllocationUnits.2 = "ONLINE"
```

**Comment by murrant** [comment]
Either this is an upstream bug, or the MIB is out of date.  Do you have access to a newer MIB?

If the MIB is out of date, it was a huge blunder for FreeNAS to re-arrange indexes in their SNMP output...

**Comment by hugalafutro** [comment]
I think there is something switched around as there are also 2 State sensors created 1 for `pool` and ` for `boot-pool` which instead of state hold the size of the pool and spam Event Log as well.
```
2023-03-07 07:23:00	sensor	turbofreenas	Sensor Deleted: state zpoolTable zpoolHealth.2 ZPool: pool1	System
2023-03-07 07:22:59	sensor	turbofreenas	Sensor Deleted: state zpoolTable zpoolHealth.1 ZPool: boot-pool	System
2023-03-07 07:22:23	State	turbofreenas	State sensor ZPool: pool1 has changed from (1606458511360) to (1607035596800)	System
2023-03-07 07:22:23	State	turbofreenas	State sensor ZPool: boot-pool has changed from (22786742272) to (22795749376)	System
2023-03-07 07:21:22	State	turbofreenas	State sensor ZPool: pool1 has changed from (1605921034240) to (1606458511360)	System
2023-03-07 07:21:22	State	turbofreenas	State sensor ZPool: boot-pool has changed from (22754587648) to (22786742272)	System
2023-03-07 07:20:22	State	turbofreenas	State sensor ZPool: pool1 has changed from (1605420896256) to (1605921034240)	System
2023-03-07 07:20:22	State	turbofreenas	State sensor ZPool: boot-pool has changed from (22715650048) to (22754587648)	System
2023-03-07 07:19:23	State	turbofreenas	State sensor ZPool: pool1 has changed from (1604901990400) to (1605420896256)	System
2023-03-07 07:19:22	State	turbofreenas	State sensor ZPool: boot-pool has changed from (22708391936) to (22715650048)	System
2023-03-07 07:18:27	State	turbofreenas	State sensor ZPool: pool1 has changed from (1594489524224) to (1604901990400)	System
2023-03-07 07:18:27	State	turbofreenas	State sensor ZPool: boot-pool has changed from (22698848768) to (22708391936)	System
2023-03-07 07:17:23	State	turbofreenas	State sensor ZPool: pool1 has changed from (1593831739392) to (1594489524224)	System
2023-03-07 07:17:23	State	turbofreenas	State sensor ZPool: boot-pool has changed from (22691276800) to (22698848768)	System
2023-03-07 07:16:33	discovery	turbofreenas	Error discovering storage module. Check log file for more details.
```

Shouldn't it then be the `zpoolAllocationUnits.1` is the number and `zpoolHealth.1` should be ONLINE

But this used to work 1 or 2 versions of Truenas back so presumably they changed and broke it?

**Comment by murrant** [comment]
I was able to find TRUENAS-MIB... it is similar but has different indexes.  Is it true that FreeNAS is now "TrueNAS Core"?

Do we need to detect them as different OS now? Or drop support of FreeNAS?

**Comment by hugalafutro** [comment]
So `FreeNAS` is `TrueNAS` now

And what used to be `FreeNAS` (running on freebsd) is now `TrueNAS Core` (still running on freebsd) and there is another version developed in parallel which runs on linux that is called `TrueNAS SCALE`

**Comment by Leppunen** [comment]
I have the same issue in my TrueNAS SCALE system. i filed an issue about it aswell. https://github.com/librenms/librenms/issues/14865 the .1 release changed snmp things a lot which was surprising for a point release. currently the zpool state sensor is also reading from the wrong place. The latest MIB linked in my issue has the values in the correct location but some values used by the storage discovery code has been removed from it, making those nonfunctional aswell.

**Comment by simmonmt** [comment]
After upgrading to Bluefin I saw all the freenas-dataset filesystems polled at 100%. Running snmpwalk with the librenms FREENAS-MIB I saw lots of complaints about a mismatch between INTEGER (what librenms wanted) and Counter64 (what I presume the NAS is sending). Replacing the librenms FREENAS-MIB with the FREENAS-MIB.txt from the NAS fixed the problem for me in that those filesystems no longer poll at 100% full. No other massive differences jumped out at me from the poller.php. Diff between old and new poller output below. I ran it as `./poller.php -h 'leiper*' -r fpdv`. I've also attached the MIB I used.

[leiper.diff.txt](https://github.com/librenms/librenms/files/10951852/leiper.diff.txt)
[FREENAS-MIB.txt](https://github.com/librenms/librenms/files/10951857/FREENAS-MIB.txt)

**Comment by murrant** [comment]
@hugalafutro It looks like no one has submitted a fix for it.

**Comment by STRUBartacus** [comment]
i have the same problem. would be nice if it could be solved

**Comment by qskwood** [comment]
Is there consensus on this issue stemming from the MIB being used?

I'm trying to identify how to start poking at this issue, after I noticed it recently.

**Comment by qskwood** [comment]
I grabbed `/usr/local/share/snmp/mibs/FREENAS-MIB.txt` from my TrueNAS SCALE (Linux-based) machine and modified `/opt/librenms/includes/discovery/storage/freenas-zpool.inc.php` to use it, to see how that affected things. The error no longer appears, and I also see some other differences in the discovery script output. I've included a snippet of what stood out to me below.

Before:
```
$ sudo -u librenms /opt/librenms/discovery.php -d -h 10.0.0.34 -m storage
[...]
USNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'COMMUNITY' '-OQUs' '-m' 'FREENAS-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/ixsystems' 'udp:HOSTNAME:161' 'zpoolTable']
zpoolIndex.1 = 1
zpoolIndex.2 = 2
zpoolDescr.1 = boot-pool
zpoolDescr.2 = pool01
zpoolAllocationUnits.1 = "ONLINE"
zpoolAllocationUnits.2 = "ONLINE"
zpoolSize.1 = 14673
zpoolSize.2 = 2932904
zpoolUsed.1 = 48367
zpoolUsed.2 = 4460937
zpoolAvailable.1 = 342966272
zpoolAvailable.2 = 278523691008
zpoolHealth.1 = 789487616
zpoolHealth.2 = 102595510272
zpoolReadOps.1 = 0
zpoolReadOps.2 = 0
zpoolWriteOps.1 = 0
zpoolWriteOps.2 = 384
zpoolReadBytes.1 = 0
zpoolReadBytes.2 = 0
zpoolWriteBytes.1 = 0
zpoolWriteBytes.2 = 4734976
[...]
```

After:
```
sudo -u librenms /opt/librenms/discovery.php -d -h 10.0.0.34 -m storage
[...]
USNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'COMMUNITY' '-OQUs' '-m' 'TRUENAS-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/ixsystems' 'udp:HOSTNAME:161' 'zpoolTable']
zpoolIndex.1 = 1
zpoolIndex.2 = 2
zpoolName.1 = boot-pool
zpoolName.2 = pool01
zpoolHealth.1 = ONLINE
zpoolHealth.2 = ONLINE
zpoolReadOps.1 = 14673
zpoolReadOps.2 = 2933100
zpoolWriteOps.1 = 48546
zpoolWriteOps.2 = 4483360
zpoolReadBytes.1 = 342966272
zpoolReadBytes.2 = 278526439424
zpoolWriteBytes.1 = 792199168
zpoolWriteBytes.2 = 103067566080
zpoolReadOps1sec.1 = 0
zpoolReadOps1sec.2 = 0
zpoolWriteOps1sec.1 = 0
zpoolWriteOps1sec.2 = 68
zpoolReadBytes1sec.1 = 0
zpoolReadBytes1sec.2 = 0
zpoolWriteBytes1sec.1 = 0
zpoolWriteBytes1sec.2 = 1998848
[...]
```

There's also a file called [TRUENAS-MIB.txt](https://github.com/truenas/middleware/blob/master/src/freenas/usr/local/share/snmp/mibs/TRUENAS-MIB.txt) in the TrueNAS GitHub, which is not the same as what's on my system. When I use it I get no lines with the word "zpool" in them. Let me know if any of this seems like a worthwhile direction to keep heading.

**Comment by SuperQ** [comment]
It looks like ixSystems renamed the MIB: https://github.com/truenas/middleware/pull/10291

**Comment by hugalafutro** [comment]
No idea if it got fixed in iX side or LibreNMS side as I updated both around same time, but with `TrueNAS-SCALE-23.10.0.1` and `LibreNMS 23.11.0` after rediscovery the mount points and their usage got detected ok:

![image](https://github.com/librenms/librenms/assets/30209689/76dccb40-301e-4bbc-843c-a11eb5b7ad3a)

**Comment by BloodyIron** [comment]
I think this warrants re-opening as I just set up a TrueNAS system version "Dragonfish-24.04.0" and have libreNMS connecting to it via SNMP. It is getting ARC stats put into L2ARC, which is wrong because I don't have any L2ARC at all, and the ARC stats in libreNMS for this system show 0 value (not null) for ARC data/hit/miss/etc, but there are stats for L2ARC (again when there is no L2ARC at all).

This is a fresh install off TrueNAS as of a few days ago of this writing.

Additionally, in the "storage" section of the overview of the device in libreNMS, each zpool (one boot, one data pool I'm doing stuff with) show up _twice_. Each one shows up under /mnt/whatever and also at the bottom just the "nameofzpoolhere" (without any slashes). The ones for /mnt/whatever show accurate (I think?) usage % (as in bytes on disk used), and the second "duplicate" entries show 100% usage 0B free (literally that). So not sure what's up with that duplication there.

That being said, I am VERY glad that TrueNAS support in libreNMS is this good already. So I'm hoping we can keep building on it and make it even more awesome than it already is. :)

I also want to thank @murrant and anyone else involved in keeping libreNMS going because you guys ROCK and I recommend libreNMS to anyone, every chance I get, and one of the reasons is because of the active development and such. I'm not trying to pander/beg for additional help here, more I just want you all to know that your work is appreciated! BY A LOT!

Anyways, if we could re-open this and such that would be appreciated, thanks! :D

**Comment by hugalafutro** [comment]
I just updated to Dragonfish 24.04.1.1, how are you getting the arc data in? Is there a specific place to enable it in TN or Lnms? I have the zilstat checked in Truenas SNMP service settings.

Thanks for the pointer to unignore the zpool sensor they indeed work now.

I cannot replicate the issue with duplicate storage (I rediscovered about 5 times):
![image](https://github.com/librenms/librenms/assets/30209689/0a79ac1e-c391-466f-9b27-5c0936d66749)

**Comment by hugalafutro** [comment]
nevermind I see now it took a bit to start pulling the data in

I can confirm the zilstat data is pulled into wrong sensors I do not have any l2arc either
![image](https://github.com/librenms/librenms/assets/30209689/b34f0815-485a-4eef-96d1-2f636c9a715c)

**Comment by BloodyIron** [comment]
WOOT!

**Comment by murrant** [comment]
This needs to be re-submitted because it was merged during a freeze :)
