### ISSUE TITLE
ASR1001 environmental 

### ISSUE THREAD

**Issue by alchemyx** [librenms/librenms#14896]
### The problem

After one of the recent upgrades (I wasn't able to locate which), ASR environmental readings no longer work and I get following errors from the poller:

[2023-03-11T09:15:05.986160+01:00] production.ERROR: Error polling sensors module for gw0. LibreNMS\Exceptions\UserFunctionExistException: Invalid user function:  in /opt/librenms/LibreNMS/Util/UserFuncHelper.php:38
Stack trace:
#0 /opt/librenms/includes/polling/functions.inc.php(182): LibreNMS\Util\UserFuncHelper->__call()
#1 /opt/librenms/includes/polling/functions.inc.php(130): record_sensor_data()
#2 /opt/librenms/includes/polling/sensors.inc.php(28): poll_sensor()
#3 /opt/librenms/includes/polling/functions.inc.php(339): include('...')
#4 /opt/librenms/poller.php(126): poll_device()
#5 {main}

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.2.0-168-gc5c7166bc (2023-03-11T00:15:15+01:00)
DB Schema | 2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (248)
PHP       | 8.1.16
Python    | 3.8.10
Database  | MariaDB 10.3.38-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | 5.8
===========================================

[OK]    Composer Version: 2.5.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### Device info

Cisco ASR1001-X

### Discovery output

```txt
Due to amount of confidential information I need to skip. I hope it's fine.
```

### Poller output

```txt
Due to amount of confidential information I need to skip. I hope it's fine.
```

**Comment by CoMMyz** [comment]
We have seen the same problem on our end with multiple devices and same errors in the log

Reverting to commit 1e373de has fixed the problem.

**Comment by alchemyx** [comment]
I can confirm it fixed the issue for us, thank you @Jellyfrog
