### ISSUE TITLE
CentOS 7/Nginx install randomly broke overnight?

### ISSUE THREAD

**Issue by DeviantEng** [librenms/librenms#1489]
So I followed the install guide about a month ago and setup a new instance of LibreNMS on CentOS 7, using Nginx and PHP-fpm.  It worked great for weeks, but the other day I could no longer log in.  I see the login page, and if I try to log in with a known bad username/password, it has a red box that says "Authentication failed."  If I use a known good username/password (created one with the adduser.php file called root, with a password of root) I get no prompts, and the page essentially refreshes itself.

In /opt/librenms/logs/error.log I see this:
2015/07/19 20:38:12 [error] 14245#0: *31 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: PATH_TRANSLATED in /opt/librenms/html/index.php on line 16
PHP message: PHP Notice:  Undefined index: ORIG_SCRIPT_FILENAME in /opt/librenms/html/index.php on line 16" while reading response header from upstream, client: 172.16.1.12, server: librenms.domain.local, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "librenms.domain.local", referrer: "http://librenms.domain.local/"

Nginx and PHP-fpm are both running, and seem to be happy/healthy.  I've not installed or changed anything on this system, other than maybe running "yum update".  Obviously mariadb is running since it's able to (or at least appear to) authenticate known good creds.  SELinux is set to permissive, fyi.

Any ideas?

**Comment by laf** [comment]
Can you add /debug=yes/ onto the end of the url and see what it says.

**Comment by DeviantEng** [comment]
I added that to the end of the URL, and it made no noticeable difference.  Nothing new was shown on the webpage, and I experienced the exact same behavior.  error.log showed nothing new, either.  

This sucks.  Maybe I should just rebuild, but I really don't want to loose any rrd data I already have.  Can that be imported easily enough?

**Comment by laf** [comment]
@DeviantEng 

Rebuilding is easy but I'm not sure you'd expect something different. Are you able to jump in our IRC channel?

**Comment by DeviantEng** [comment]
Yeah, I'll hop in.  I stopped by yesterday, but wasn't sure if anyone was around.

**Comment by hogsim** [comment]
Hey, 
did you find a solution? 
just happend for me.

**Comment by DeviantEng** [comment]
@hogsim I did get my issue fixed, but I don't remember what it was I did.  I would advise you to stop by the IRC chat, and ask for help there.  The guys were great, and very prompt with helping me!

**Comment by laf** [comment]
Was this session related within php.ini?

**Comment by hogsim** [comment]
Ok, I just did a clear install and it's working now.
