### ISSUE TITLE
More consistent use of font-awesome icons

### ISSUE THREAD

**Issue by trick77** [librenms/librenms#1490]
What do you guys think about using the FA icons in the devices overview?

Here's my suggestion:
<a href="http://imgur.com/Z9lgkJn"><img src="http://i.imgur.com/Z9lgkJn.png" title="source: imgur.com" /></a>

**Comment by laf** [comment]
I know not everyone is but I prefer using FA where possible as it cuts down on page load times, especially on pages where a number of images are served (I know the images in the above screenshot are duplicated)

You can color them still which I'd probably suggest we do but you have a big :+1: from me.

**Comment by trick77** [comment]
I just had a look at the device.inc.php and it uses a ton of icons as well. Just changing the icons in the overview to FA would in fact create a less consistent look unless all other icons would be changed as well.

We probably should agree on an icon mapping first, like this:

port icon --> fa-link
overview icon --> fa-server
graphs icon --> fa-line-chart
processes icon --> ?
performance icon --> fa-rocket
map --> fa-sitemap
packages --> fa-archive
services icon --> fa-th?
inventory --> fa-cubes
nfsen-rrd icon --> ?
health icon --> fa-heartbeat
munin icon --> fa-user-secret (looks like an agent)
pseudowires --> fa-arrows-alt
loadbalancer icon --> fa-random
wireless --> fa-wifi
vlan icon --> fa-exchange?
latency icon --> fa-truck?
vm icon --> fa-puzzle-piece or fa-gears
toner icon --> fa-print
temperature icon -> fa-fire
storage icon -> fa-database

And there should be a global switch to turn the new icons on or keep the old ones, just to keep everyone happy.

**Comment by laf** [comment]
processes icon --> fa-tasks or fa-spinner
services icon --> fa-cogs (already used to represent this in the navbar)
nfsen-rrd icon --> fa-venus-mars

@paulgear / @f0o ?

**Comment by f0o** [comment]
fa-venus-mars looks weird to me in that context.. (http://fontawesome.io/icon/venus-mars/)

**Comment by laf** [comment]
Suggestions welcome :)

**Comment by Rosiak** [comment]
@trick77 I propose you pop in a PR, then we can discuss the changes needed :)

**Comment by laf** [comment]
Proposing to close this in the next 24 hours.

**Comment by laf** [comment]
Closed. No further information provided
