### ISSUE TITLE
Seeking Your Guidance: Custom NMS with Multiple Ports per Host

### ISSUE THREAD

**Issue by c3budiman** [librenms/librenms#14926]
### The problem

Hello,

I hope you're doing well! First of all, I want to express my gratitude for your remarkable open-source project. It has been an excellent foundation for a custom Network Management System (NMS) that I'm currently developing for my office.

Our initial implementation has been working seamlessly, with features such as data exporting to Excel. However, I've encountered a challenge when trying to add two hosts with the same IP but different ports. As you're aware, the RRD folder and poller utilize the hostname for organization and polling purposes, respectively.

To overcome this hurdle, I've been considering the following approach:

- Modify the device model to include an 'is_multiple_port' attribute (1 for true, 0 for false).
- In ValidateDeviceAndCreate.php, allow bypassing the hostname check for devices with multiple ports.
- On the frontend, introduce a radio option for 'is_multiple_port'.
- Store the RRD data using 'hostname_port' when 'is_multiple_port' is set to 1. in initRrdDirectory function inside Poller.php

I would be incredibly grateful if you could share your thoughts or suggestions on this approach or recommend an alternative solution. Your expertise and experience with this project would be invaluable in helping me address this issue.

Thank you in advance for your time and support. I look forward to hearing from you!

### Output of ./validate.php

```txt
this has nothing to do with it.
```

**Comment by ottorei** [comment]
It is a bit unclear to me why you would need to add the same host multiple times if the actual physical device is the same. If the device is actually the same physical device, why not just add it once and create the necessary alert rules? Or am I misunderstanding something here like do you have multiple different physical devices with same IP-address and you are using distributed polling to poll each device from different poller? If that is the case, you could use DNS-names for the hostname and pin each device to different pollers.

**Comment by c3budiman** [comment]
nevermind i figured it out
