### ISSUE TITLE
upsEstimatedMinutesRemaining is interpreted as seconds

### ISSUE THREAD

**Issue by bp0** [librenms/librenms#14935]
### The problem

The field [upsEstimatedMinutesRemaining](https://oidref.com/1.3.6.1.2.1.33.1.2.3) (1.3.6.1.2.1.33.1.2.3) is supposed to be in minutes, but LibreNMS reports it as seconds.

snmpwalk output:
```
1.3.6.1.2.1.33.1.2.3.0 = INTEGER: 25
```
LibreNMS reports:
![image](https://user-images.githubusercontent.com/1758090/229331788-61c105a9-c0d5-453b-85e8-db1cba3ca6fd.png)

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.2.0-46-gd508d2d6 (2023-03-30T14:04:06-05:00)
DB Schema | 2023_03_14_130653_migrate_empty_user_funcs_to_null (249)
PHP       | 8.2.0
Python    | 3.9.2
Database  | MariaDB 10.5.18-MariaDB-0+deb11u1
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================

[OK]    Composer Version: 2.5.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

**Comment by bp0** [comment]
After I posted this issue, it changed to minutes on it's own. I didn't change anything. 
You can still see in the graph that it was interpreted as seconds for the first four hours.

![image](https://user-images.githubusercontent.com/1758090/229351609-35c34309-e91c-4ed7-be97-939222d64ab0.png)

Weird.

**Comment by murrant** [comment]
Just a race condition where the OS data has not been pulled in yet.  I'm guessing this is a routeros device.
