### ISSUE TITLE
multiple ospf instances on router

### ISSUE THREAD

**Issue by mkaipov** [librenms/librenms#1495]
Hello guys.
I expereince issue with ospf processes on my 7600 routers. In my  case I use ospf for globar routing table and some OSPF processes in VRF for PE-CE routing. So in "Routing" inset I can see just one OSPF process, and this process for PE-CE routing. I found that RFC1850 defined  to work with only one OSPF process/instance on a given router. So in SNMPv2 the system would pick a more or less random "default" instance when it returned the scalar objects and some tables. In these cases, information from the other instances was not available via SNMP. But for this types of case designed RFC4750. I use this document form cisco http://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/111869-ospf-with-snmp.html

**Comment by Rosiak** [comment]
I hear your issue, but I am really not much of a fan of Cisco's proposed solution.
Hence I think we should close this issue for now.
@librenms/reviewers ?

**Comment by Rosiak** [comment]
Closing since there haven't been any response.
