### ISSUE TITLE
Add an option to switch between the dynamic and static map styles.

### ISSUE THREAD

**Issue by masonke** [librenms/librenms#1497]
This is an idea from issue-1461. My coding skills are no where near the level needed to do this work, so I am adding this issue in the hopes someone could take this on when they have time.

Create a config parameter to switch between the new dynamic maps and the older static maps. This would allow shops to switch for for preference or functional purposes. Part of that would be accepting that the old style maps would not support L4_mac discovery.

Attached is what I am referring to as the static maps

![static_map](https://cloud.githubusercontent.com/assets/1863778/8775663/688c2d38-2eb8-11e5-8214-bf647a6dfc04.jpg)

**Comment by f0o** [comment]
Isnt this a duplicate of #1461 ?

**Comment by paulgear** [comment]
:+1: from me - I much prefer the old style

**Comment by laf** [comment]
I'd say this is a duplicate, @masonke can you close this please and it can be worked on from #1461

**Comment by masonke** [comment]
Closed as a duplicate
