### ISSUE TITLE
SSO no longer works in dev branch

### ISSUE THREAD

**Issue by salfers** [librenms/librenms#14990]
### The problem

We have Google SSO configured on our LibreNMS instance, approximately on 17. Apr the SSO logins were still working and they are no longer working now.

What happens is:
1. Click on "Login with Google", login form opens
2. Google redirects to `https://HOST/auth/google/callback`
3. Instead of completing the process librenms responds with a 302 back to the login form

Our socialite config looks fairly standard:
```
$ lnms config:get auth.socialite
{
    "redirect": false,
    "register": false,
    "configs": {
        "google": {
            "client_id": "redacted",
            "client_secret": "redacted",
            "listener": "\\SocialiteProviders\\Google\\GoogleExtendSocialite"
        }
    }
}
```

### Output of ./validate.php

We already rolled back to stable but we were on commit 2ddfba51dd8aae7fbcfa8fc9bed04c5be1e81fa4.

Here's the validate output on stable:

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.4.1 (2023-04-11T20:44:45+02:00)
DB Schema | 2023_03_14_130653_migrate_empty_user_funcs_to_null (249)
PHP       | 8.1.18
Python    | 3.6.8
Database  | MariaDB 10.8.7-MariaDB
RRDTool   | 1.7.0
SNMP      | 5.8
===========================================

[OK]    Composer Version: 2.5.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

23.4.1

### Anything in the logs that might be useful for us?

Nothing relevant at all in the logs as far as I can see.

**Comment by murrant** [comment]
Dang, a small error broke it.
