### ISSUE TITLE
API Returning with 401 Unauthorized

### ISSUE THREAD

**Issue by Frowwny** [librenms/librenms#15019]
### The problem

Hi There,

I am trying to test the oxidized API that I created by using RESTClient as well as the curl command. I am extremely new to all of this so please excuse my arrogance. Please let me know what other outputs are needed and thank you in advance!

curl -X GET -i 'http://192.168.1.180/api/v0/oxidized'
HTTP/1.1 401 Unauthorized
Server: nginx/1.18.0 (Ubuntu)
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache, private
Date: Sun, 30 Apr 2023 20:33:08 GMT

Here is my Oxidized Config File
username: username
password: password
model: junos
resolve_dns: false
interval: 3600
use_syslog: false
debug: false
threads: 30
use_max_threads: false
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 192.168.1.180:8888
next_adds_job: false
vars: {}
groups: {}
group_map: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: file
  file:
    directory: "/home/oxidized/.config/oxidized/configs"
source:
  default: http
  debug: true
http:
    url: http://192.168.1.180/api/v0/oxidized
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: '84f9cd144934996c99ec5a0c41a07678'
model_map:
  defaultgrp:
    username: admin
    password: private
  cisco:
    username: admin
    password: private

### Output of ./validate.php

```txt
librenms@CM:~$ ./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.4.1-48-g7e8e11f09 (2023-04-28T10:13:55-05:00)
DB Schema | 2023_04_12_174529_modify_ports_table (250)
PHP       | 8.1.2-1ubuntu2.11
Python    | 3.10.6
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.5.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    Python wrapper cron entry is not present
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
librenms@CM:~$
```

### What was the last working version of LibreNMS?

23.4.1

**Comment by ottorei** [comment]
Your are missing the authentication token on your API call. You can find an example on the docs: https://docs.librenms.org/API/. Please note that you need to use the token on almost all routes with curl. Looking at your Oxidized config, I believe that might work.
