### ISSUE TITLE
Add hostname into device overview page

### ISSUE THREAD

**Issue by Ftelf** [librenms/librenms#1503]
At All devices list I can see the hostname (sysName) of the device, which is much better to read and understand for humans.
http://fii.cz/bywrzwwy

But there is no single refference to hostname in Device Overview:
http://fii.cz/cbyzxxtz

I believe that adding the sysName into Overview will enhance the readability. In fact I would also welcome purpose and version info.

**Comment by Rosiak** [comment]
Regarding the sysName, fine with me, if everyone agrees I'll PR the stuff.

Version is already available as part of the "Operating System" string.
Not sure about the purpose tho'.

**Comment by SaaldjorMike** [comment]
IMO, if people add devices based on IP instead of hostnames, it makes quite a lot of sense to show the sysName on the overview page of the device.

**Comment by Ftelf** [comment]
Version is already seen but only for some device types. Ie. Mikrotik OK.
http://fii.cz/hwxpyfc

But UBNT only some:
http://fii.cz/czyyfej
http://fii.cz/zesacn
But do not worry about it, I realized that this ubnt device is very old Bullet 5 with fw v4.0.3. Other is fine.

**Comment by laf** [comment]
> Regarding the sysName, fine with me, if everyone agrees I'll PR the stuff.
>

Go for it :)

**Comment by laf** [comment]
Merged in
