### ISSUE TITLE
Graphs stop updating after moving rrd directory

### ISSUE THREAD

**Issue by samuelbarata** [librenms/librenms#15037]
### The problem

I noticed the VM I have running libreNMS ran out of space. I attached another virtual disk and copied `/opt/librenms/rrd` to that new volume and changed the path in the config.
The problem I'm having is that half of my devices isn't updating the graphs on the UI but the other half is working fine.
- I haven't found a single device that doesn't have last years history.
- I'm receiving alerts from the devices that are not updating their graphs.
- I've checked that the devices that are working as expected are writing to the correct directory and that the old directory is empty

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.2.0-27-ge9f8e6450 (2023-03-10T14:00:03+00:00)
DB Schema | 2022_09_03_091314_update_ports_adsl_table_with_defaults (248)
PHP       | 8.2.0
Python    | 3.9.2
Database  | MariaDB 10.5.18-MariaDB-0+deb11u1
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================
```

### What was the last working version of LibreNMS?

23.2.0

**Comment by murrant** [comment]
You need to fix the permissions
