### ISSUE TITLE
Added support for Extreme CPU usage + Memory, bug fix for Extreme Power, changes/additions in rewrites.inc.php and added support for some new Extreme platforms/features

### ISSUE THREAD

**Issue by rasssta** [librenms/librenms#1504]
* Added support for Extreme CPU usage + Memory
* Bug fix for Extreme Power that was giving a value of 0 no matter the snmp result
* Changes/additions in rewrites.inc.php for Extreme models and Brocade TurboIron 24x
* Added support for some new Extreme platforms and features (version etc)

**Comment by laf** [comment]
Merged in.
