### ISSUE TITLE
Power info via API

### ISSUE THREAD

**Issue by starnetwork** [librenms/librenms#1506]
Hi,
it's possible to get the Power / Electricity data via librenms API so we can use it for billing as we do for bandwidth?

**Comment by laf** [comment]
Does the data you need exist already in LibreNMS?

**Comment by starnetwork** [comment]
I didn't see any PDU in the demo but it's should be in the SNMP data for PDU
this for example: http://www.apc.com/products/resource/include/techspec_index.cfm?base_sku=AP7851 and all others PDU supporting in show this data via SNMP

**Comment by laf** [comment]
For each power outlet, we might have to add that support then add the API support on top of it. Possible though.

Can you provide access to an APC unit?

**Comment by starnetwork** [comment]
sure, I can provide it, 
but it's production unit so can you please email me in private?

**Comment by Rosiak** [comment]
I'm using the AP7822 B2, works fine :)
http://snag.gy/UtdMk.jpg

**Comment by laf** [comment]
Hey @Rosiak. Think it's per outlet data that he's after.

**Comment by starnetwork** [comment]
Rosiak, thanks!
it's show this data also via API?

**Comment by laf** [comment]
I'll leave this open. It's a useful feature to have we've just not got round to doing it yet.

**Comment by starnetwork** [comment]
sorry, you right, the APC Power is working, but:
1. no info per Power connector (will be very good to get the power info per Cable)
2. no API support yet (as good as I know)

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-power-info-via-api/818
