### ISSUE TITLE
Support for Alpha FXM Power Controllers

### ISSUE THREAD

**Issue by Lonecrowe** [librenms/librenms#1507]
Product Page

https://www.alpha.ca/web2/products/standard-systems/indoor-ups-solutions/item/alpha-fxm-350-2000

The downloads section is offline at the moment but I have a copy of the MIB I can send to whoever needs to work on it.  

Pastebin of the MIB can be found here  http://pastebin.com/9Vdn0eQL

I'd like to see the standard power  health items to be graphed. 

Input - Voltage, Frequency

Output - Voltage, Current

Battery - Capacity (Time Remaining in the UPS)

Output Source -  whether its outputting via battery or line mode.  

I'll be available to test this of course and help with any other information needed.

**Comment by Rosiak** [comment]
Can you please post output from a snmpwalk?

**Comment by Lonecrowe** [comment]
Here you go -  the enterprises version.  It also has the IF mib and rfc-1213 standard stuff.  

http://pastebin.com/nUq8HK1X

It doesn't have your standard stuff so might need to get creative.  Here are some interesting data points to graph. 

upsBatteryStatus  unknown(1),batteryNormal(2),batteryLow(3),batteryDepleted(4)
upsSecondsOnBattery
upsBatteryVoltage
upsBatteryChargingCurrent
upsBatteryCapacity (in amp hours) 
upsBatteryTemperature

upsInputFrequency
upsInputVoltage
upsOutputSource standby(1),line(2),boost2(3),boost1(4),buck1(5),buck2(6),inverter(7),retransfer(8),transfer(9),shutdown(10),bypass(11)

upsOutputFrequency
upsOutputVoltage
upsOutputCurrent
upsOutputPowerVA
upsOutputPowerWatt
upsPowerFactor

Many others

**Comment by laf** [comment]
Hi @Lonecrowe 

Can you provide an snmpwalk without using the mib, just want to see what the standard output is.

**Comment by Lonecrowe** [comment]
http://pastebin.com/ExdeCJKU

**Comment by Lonecrowe** [comment]
Not using them anymore and doubt anyone else will .. closing
