### ISSUE TITLE
API POST transports no longer set Content-type header properly.

### ISSUE THREAD

**Issue by QuadPiece** [librenms/librenms#15082]
### The problem

Sometime in May alert transports of the type "API" seem to have stopped respecting `Content-Type` headers. I believe it was caused by #14763 

I use API POST transports, and the endpoints often require specific a content type to be sent, such as `application/json`. Recently I noticed that my API POSTs had stopped working. After some troubleshooting it turns out it's because all the requests sent by LibreNMS contain `Content-Type: text/plain` rather than the header that I set.

I'm unsure exactly when this started happening, but the 25th of May was when I noticed it. I know that outgoing API POSTs worked on April 28th, as that was the last time LibreNMS successfully created a ticket in another one of our monitoring systems using API calls.

![image](https://github.com/librenms/librenms/assets/6379091/165852e2-4766-4869-9d19-07b436937998)

Specifically I suspect this piece of code's headers is no longer being overridden as they should: 

https://github.com/librenms/librenms/blob/075267dcc976153da1c64e58fe709333b5418356/LibreNMS/Alert/Transport/Api.php#L51-L54

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.5.0-9-gea57c2518 (2023-05-31T01:49:12+02:00)
DB Schema | 2023_04_27_164904_update_slas_opstatus_tinyint (252)
PHP       | 8.1.2-1ubuntu2.11
Python    | 3.10.6
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.5.7
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]:
        You can fix this with ./scripts/github-remove
        Modified Files:
         includes/definitions/rutos-rutx.yaml
```

**Comment by PipoCanaja** [comment]
Hi @QuadPiece 
Will try to reproduce this issue. And may be applying headers after the withBody() call will solve the issue. 

Could you try this : 

```
 $client = Http::client();
  
 if ($method !== 'get') { 
     $request_body = SimpleTemplate::parse($this->config['api-body'], $alert_data); 
     $client->withBody($request_body, 'text/plain'); // Content-Type can be overriden by user headers 
 }
$client->withHeaders($request_headers); //get each line of key-values and process the variables for Headers 
```

Instead of this
https://github.com/librenms/librenms/blob/075267dcc976153da1c64e58fe709333b5418356/LibreNMS/Alert/Transport/Api.php#L48-L54

**Comment by QuadPiece** [comment]
Hi @PipoCanaja,

This hotfix partially works, but makes LibreNMS send both a `text/plain` like before as well as the specified Content-Type.
Certain endpoints seem to handle this, others do not. Usually returning a 400 bad request if they do not handle it.

Of course it is not proper to send two Content-Type headers, so this won't function as a permanent upstream fix.

Following the change, a POST request from LibreNMS configured as so:

![image](https://github.com/librenms/librenms/assets/6379091/4e96c4ec-eba0-44e5-a8cc-01373d3826d1)

Results in this outgoing request:

![image](https://github.com/librenms/librenms/assets/6379091/171f481a-f1f0-49d4-a539-d8cdd22517a4)

For reference, this is the request LibreNMS sends prior to applying the hotfix:

![image](https://github.com/librenms/librenms/assets/6379091/1d1a9330-7fc8-4c94-bc2d-57e1c3e2f8d3)

**Comment by tjanik1** [comment]
Depending on how you are using the API push, our fix was to update the default value from 'text/plain' to 'application/json' in side the if block and leave everything else the same.  This worked and hopefully when the new version comes out with the fix, it will just overwrite this with the older code and the config changes in the transport from the UI will just go back to working.

**Comment by gdanielson** [comment]
hi,  +1 up vote for this. I've been trying to add a new integration and now realise I'm hitting this issue.

**Comment by tjanik1** [comment]
I wouldn't hold your breath for this to be fixed. It's been a few months already. The work around is to just edit the file yourself (you only need to change that one line).

Tom


Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by PipoCanaja** [comment]
Hi @QuadPiece  and @tjanik1 
Feel free to submit a PR on this issue. LibreNMS is made by all of us, and the best way to see a fix happening is to submit it yourself. We'll review it and merge it to the repository.
Bye

**Comment by gdanielson** [comment]
That patch shown hasn't worked for me.  Pointing at AWS ApiGateway still returned HTTP 415 Unsupported Media Type and testing to webhook.site continued to show text/plain. To get it working I hardcoded L54 to application/json

My first time with LibreNMS. I've never touched any php before, if I knew more about it I'd have a go at troubleshooting.

**Comment by murrant** [comment]
Is anyone planning on submitting a change to fix this?

**Comment by PipoCanaja** [comment]
@murrant : Done. Content-Type handling is not at all as we would expect it to be.

**Comment by PipoCanaja** [comment]
@QuadPiece Could you please test the PR https://github.com/librenms/librenms/pull/15574 and let us know if it works as expected for you ?

**Comment by PipoCanaja** [comment]
@tjanik1 @gdanielson  Could you please test the PR https://github.com/librenms/librenms/pull/15574 and let us know if it works as expected for you ?
