### ISSUE TITLE
Missing EIGRP support

### ISSUE THREAD

**Issue by SaaldjorMike** [librenms/librenms#1508]
According to the docs I see that it states that you can enable eigrp stuff:

```
$config['enable_eigrp']                 = 1; # Enable EIGRP session collection and display
```

Looking at the codebase, it looks like this is completely missing.

```
➜  librenms git:(master) find . -type f -name "*.php" |xargs grep -R eigrp       
./html/includes/geshi/geshi/ios.php:        // 'isis', 'ospf', 'eigrp', 'rip', 'igrp', 'bgp', 'ipv4', 'unicast', 'multicast', 'ipv6', 'connected', 'static', 'subnets', 'tcl'
./includes/defaults.inc.php:$config['enable_eigrp'] = 1;
./scripts/geshi-ios.php:        // 'isis', 'ospf', 'eigrp', 'rip', 'igrp', 'bgp', 'ipv4', 'unicast', 'multicast', 'ipv6', 'connected', 'static', 'subnets', 'tcl'
```

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
