### ISSUE TITLE
Alert Template page (webgui)

### ISSUE THREAD

**Issue by Alastair-VOIPUNLIMITED** [librenms/librenms#1509]
Hi guys, 

Alerting template page is rather buggy, doesnt allow deletion of templates (after we have added quite a few of them). Also trying to change which templates go with which alert rules (we have over 20 if this makes a difference) doesnt work, changing one seems to change all of them, some of them or none. 

Very odd.

I can easily capture my screen using FRAPS and show this, have tried various browsers and same results. 

Alastair

**Comment by Alastair-VOIPUNLIMITED** [comment]
forgot to mention that %value.#variable-here# occasionally does not add itself to the email, a colleague of mine was troubleshooting with f0o yesterday with this and since i have found the problem is intermittent.

**Comment by laf** [comment]
Fixed in 1527 - except the %value.variable - please create a separate issue for that :)

**Comment by f0o** [comment]
Its not really clear to me what you mean by '%value.#variable-here# occasionally does not add itself to the email'.

Could you clarify/elaborate?
I remember the issue and it turned out to be just a typo afaik.

**Comment by laf** [comment]
Closing this as the primary issue is fixed. please raise another issue with details of the second issue.
