### ISSUE TITLE
OSPF discovery

### ISSUE THREAD

**Issue by Alastair-VOIPUNLIMITED** [librenms/librenms#1510]
Hi Guys,

Have an issue where OSPF on some of our core routers is detecting various ports on the same device as separate devices (they have resolvable names.) To stop these devices being polled like crazy I have disabled and ignored these duplicates but this causes alot of error logs all over libre like this example:

OSPF discovery of 1-ge0-1-cr3.thw.as42004.net (91.151.0.137) failed - check ping and SNMP access

Any ideas on how I can resolve this or to be able to turn off Libre's discovery of OSPF peers?

Alastair

(edit, typo)

**Comment by laf** [comment]
```bash
$config['autodiscovery']['ospf'] = false;
```

we have duplicate detection but not if the hostnames are all coming back differently :(

**Comment by laf** [comment]
Another thing but you could also add those IPs to $config['autodiscovery']['nets-exclude'] config so they are no longer picked up.

**Comment by Alastair-VOIPUNLIMITED** [comment]
can we wildcard $config['autodiscovery']['nets-exclude']?

for example:

$config['autodiscovery']['nets-exclude'] = "*-cr1.rb-hex.as42004.net";

Thank you

**Comment by SaaldjorMike** [comment]
As far as i know nets-exclude needs to be subnets and hostname-based.

**Comment by laf** [comment]
Yeah it's IP based rather than subnets so you would need to add the IP that the hostname resolves to as a /32.

**Comment by paulgear** [comment]
Hi @Alastair-VOIPUNLIMITED,

We're just having a look at this at the summit; did you try ```php
$config['autodiscovery']['ospf'] = false;
```
Also, can you confirm that your preferred scenario would be that:
a) OSPF discovery is left on,
b) You don't have to add anything to $config['autodiscovery']['nets-exclude'], and
c) Devices for which multiple DNS names exist are not discovered as duplicates.

**Comment by laf** [comment]
Any further update @Alastair-VOIPUNLIMITED or can this be closed?
