### ISSUE TITLE
alert templates HTML support

### ISSUE THREAD

**Issue by Alastair-VOIPUNLIMITED** [librenms/librenms#1511]
hey guys,

Would be really neat if there was HTML support within the template creation area so we can make some nice pretty emails. 

And on a side note, is there support to change the subject line of alert emails?

Thank you

Alastair

**Comment by f0o** [comment]
Please reference this request in #1314

**Comment by f0o** [comment]
Reopening, PR'ing later today

**Comment by Alastair-VOIPUNLIMITED** [comment]
Hi guys, any updates on this?

**Comment by laf** [comment]
I thought something like this had been merged in but I'm not sure. @f0o?

**Comment by f0o** [comment]
I think masonke from IRC has an early draft of it. Will ask him today how it went

**Comment by laf** [comment]
This was merged in
