### ISSUE TITLE
Nvidia application graphing wrong counters by type

### ISSUE THREAD

**Issue by mikebutash** [librenms/librenms#15121]
### The problem

Nvidia Application when enabled is graphing the counters incorrectly to their type.  This seems to be a result of nvidia-smi adding fields over time, but the rrd fields are not accounting for added later $memtemp.

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 1.65-36-g0e9658987
DB Schema | 2020_06_23_00522_alter_availability_perc_column (170)
PHP       | 7.4.3-4ubuntu2.18
Python    | 3.8.10
MySQL     | 10.3.38-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.5.8
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
sh: 1: pip3: not found
[WARN]  Your install is over 24 hours out of date, last update: Wed, 15 Jul 2020 12:45:09 +0000
        [FIX]: 
        Make sure your daily.sh cron is running and run ./daily.sh by hand to see if there are any errors.
```

### Anything in the logs that might be useful for us?

I was testing the nvidia application extension on a host, and after polling for a day noticed I was getting no processor utilization, but memory and plenty other things.  After review, it seems the counters are just one-off, "GPU Utilization" is blank, but the next "Memory Utilization" and "Encoder Utilization" *do* have active counters.  Watching the actual nvidia-smi, Encoder Utilization *is* actually Memory, and Memory is GPU so off-by-one.  Opps.

Digging into the nvidia-smi, extension, and eventually librenms application nvidia.inc.php itself, it looks like the problem lies around nvidia.inc.php or at least and a missing $memtemp rrd/fields definition for added $memtemp to match for whether nvidia-smi returns 19 or 18 counters.

```
nvidia-smi dmon -c 1 -s pucvmet
# gpu    pwr  gtemp  mtemp     sm    mem    enc    dec   mclk   pclk  pviol  tviol     fb   bar1  sbecc  dbecc    pci  rxpci  txpci 
# Idx      W      C      C      %      %      %      %    MHz    MHz      %   bool     MB     MB   errs   errs   errs   MB/s   MB/s 
    0     34     61      -    32      6      0      0   6000    510      0      0   7924     58      -     -     0    364     15 
```
This probably just needs adding the fields/rrd for missing $memtemp and rebuild the rrd, but I think the UI will probably need that added as well still.  Either way, a definite problem.

Another thing I noticed is the snmp script itself says to loop and exit after 5 gpus, but these days that might not be enough.  Might want to up this to 8 or even 16 these days as a default.

This otherwise works beautifully for monitoring gpu's!
```

**Comment by Jellyfrog** [comment]
> LibreNMS  | 1.65-36-g0e9658987

A lot has changed in 3 years, and the applications are only meant for latest version. Start there and come back if the problem persists!

**Comment by mikebutash** [comment]
Librenms itself might have changed lots, but the nvidia feature hasn't been updated in 3 years, and certainly not to fix this issue, so obviously no one has used this since then and will be unhappy when they do still.

I did monkey patch mine to attempt to add the missing fields across the 3 locations necessary to add the missing $memtemp, and sorta works, but these still show up out of order for some reason that is eluding me since the oids seem to come across in the right order.  This is where I go "I am not a developer..."
