### ISSUE TITLE
Device Overview: wrong overall trafic graph.

### ISSUE THREAD

**Issue by setiseta** [librenms/librenms#1514]
the graph of overall trafic show me up to 2TBit on a n1kv.
in same time range it shows on other system about 1gbit.
same thing on other devices.

the values on single ports seems ok, but there seems something wrong in summing up all ports?

**Comment by laf** [comment]
Got some screenshots to show us an example?

**Comment by setiseta** [comment]
Attached two images. one first from our new librenms, and the second from the same device from the observium.

![librenms-n1kv](https://cloud.githubusercontent.com/assets/4118404/8818884/c99b8436-3046-11e5-802e-afa69ecd7b68.png)
![observium-n1kv](https://cloud.githubusercontent.com/assets/4118404/8818889/cd329fd0-3046-11e5-9c18-ede5396bd7d4.png)

**Comment by Tatermen** [comment]
I am seeing similar issues across multiple devices after updating (to version 1ad21e0) about 2 weeks ago. It seems to be proceeded by the eventlog being filled with messages implying that the device is being discovered from scratch.

![graph php](https://cloud.githubusercontent.com/assets/8707177/9261552/909c46b2-4206-11e5-94f8-4a4628a0d7b9.png)

![graph php](https://cloud.githubusercontent.com/assets/8707177/9261573/b868e5ba-4206-11e5-957c-47a62111b029.png)
