### ISSUE TITLE
Juniper VLANS not updating

### ISSUE THREAD

**Issue by Fiala06** [librenms/librenms#15157]
### The problem

We’re having trouble with our Juniper VLANS not updating in LibreNMS. After initially adding the device it pulls all the correct data/vlans. Once you make a change a port to a new vlan the data is never updated in LibreNMS.

Our HP 2920’s do update properly so seems to only be Junipers.

I’ve also setup a clean instance of LibreNMS and the issue persists.

Here is the discovery for the Juniper: [https://p.libren.ms/view/3a3f13a3 2](https://p.libren.ms/view/3a3f13a3)

./poller.php -h 163.41.64.3 -r -f -d | ./pbin.sh : [https://p.libren.ms/view/0308443c 2](https://p.libren.ms/view/0308443c)

Let me know if there is anything else you may need. Thanks

We use Juniper EX3400
This happens for single switches and ones in virtual chassis
Tried updating to JunOS 21.4R3.15 and issue persists Currently on 20.4R3.8

### Output of ./validate.php

```txt
librenms@librenms:~$ /opt/librenms/validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.7.0 (2023-07-16T21:42:41-07:00)
DB Schema | 2023_04_27_164904_update_slas_opstatus_tinyint (252)
PHP       | 8.1.2-1ubuntu2.13
Python    | 3.10.6
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.5.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

**Comment by ottorei** [comment]
I tried to replicate this issue with my LAB EX2300. The associated VLAN does not seem to update during poll but does update during discovery.

**Comment by nanedi** [comment]
My EX series doesn't seem to load hardware info.
CPU RAM etc...

**Comment by murrant** [comment]
FYI @ottorei There is no vlan poller module, only discovery.  So that seems correct.

**Comment by murrant** [comment]
Perhaps OP is not running discovery?

**Comment by Fiala06** [comment]
> Perhaps OP is not running discovery?

I’ve tied manually running poller and discovery and it doesn’t update. It does work for our hp switches tho.

**Comment by ottorei** [comment]
> > Perhaps OP is not running discovery?
> 
> I’ve tied manually running poller and discovery and it doesn’t update. It does work for our hp switches tho.

Did you check the debug log of the discovery? Did it detect the correct VLAN?

**Comment by ottorei** [comment]
Are you sure your vlan module is enabled? I tried to reproduce this situation with my EX3400 (could not test with your exact software) and the device does seem to output vlan info correctly during each discovery. From your paste, I can not find anything related to vlans.

You should see something similar to these lines when the module is enabled:
`#### Load disco module vlans ####

SQL[SELECT * FROM `vlans` WHERE `device_id` = ? [19631] 0.5ms] 
  

SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'COMMUNITY' '-OQUs' '-m' 'BRIDGE-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/junos' 'udp:HOSTNAME:161' 'dot1dBasePortIfIndex']

dot1dBasePortIfIndex.490 = 514
dot1dBasePortIfIndex.491 = 515
dot1dBasePortIfIndex.492 = 516
dot1dBasePortIfIndex.493 = 517
dot1dBasePortIfIndex.494 = 518
dot1dBasePortIfIndex.495 = 519`

**Comment by Fiala06** [comment]
> Are you sure your vlan module is enabled?`

I believe so. Thi sis the setting right?
![image](https://github.com/librenms/librenms/assets/5183146/f3c06fa5-251b-4b1e-acdd-851762de1680)

**Comment by ottorei** [comment]
> > Are you sure your vlan module is enabled?`
> 
> I believe so. This is the setting right? ![image](https://user-images.githubusercontent.com/5183146/281784435-f3c06fa5-251b-4b1e-acdd-851762de1680.png)

Yes. But still, your debug log is missing all VLAN-related information. Could you double check the global and device module settings and then make a new debug log. Also, if you have a distributed polling, check all servers that might be polling that device.

**Comment by murrant** [comment]
That is just the global setting.  Please look at the device settings page to see the final enabled/disabled status.

**Comment by Fiala06** [comment]
> > > Are you sure your vlan module is enabled?`
> > 
> > 
> > I believe so. This is the setting right? ![image](https://user-images.githubusercontent.com/5183146/281784435-f3c06fa5-251b-4b1e-acdd-851762de1680.png)
> 
> Yes. But still, your debug log is missing all VLAN-related information. Could you double check the global and device module settings and then make a new debug log. Also, if you have a distributed polling, check all servers that might be polling that device. And upgrade to the latest release if you have not done so already.


Yes it's enabled on the device setting itself. 

![image](https://github.com/librenms/librenms/assets/5183146/23f429e8-b095-4fa7-a593-ea5e68ff7c87)

Fresh to new log
https://p.libren.ms/view/768fccc9
