### ISSUE TITLE
iDRAC6 detected as ARMv5

### ISSUE THREAD

**Issue by clinta** [librenms/librenms#1518]
Having trouble figuring out the priorities for OS detection. I have an iDRAC6 device. It is being detected as Generic ARMv5 because SysDescr coontains the string 'armv5tejl'.

sysObjectID is .1.3.6.1.4.1.674.10892.2 so it should be detected as drac, but it looks like the ARM detection is taking precidence.

**Comment by laf** [comment]
@clinta 

I can't find any arm detection, what is the OS it's being set to?

**Comment by clinta** [comment]
I believe it's coming from https://github.com/librenms/librenms/blob/master/includes/polling/os/unix.inc.php#L20

OS is detected as Linux 2.6.23.1

**Comment by laf** [comment]
@clinta you will need to just add an && sysObjectID != 'blah' to that line.
