### ISSUE TITLE
auth_test.php broken for lldap

### ISSUE THREAD

**Issue by jacobw** [librenms/librenms#15197]
### The problem

auth_test.php does not seem to populate the user array properly.

ibrenms:/opt/librenms/scripts# ./auth_test.php -u lnms
Authentication Method: ldap
Password:
Authenticate user lnms:
User (lnms):
  username =>
  realname =>
  user_id => 0
  email => 
  level => 0

Looking at librenms/LibreNMS/Authentication/LdapAuthorizer.php line 234:

foreach ($entries as $entry) {

In the first pass through the for loop the first $entry is just a integer 1, instead of an array, which looks incorrect as manually selecting entries[0] is the expected array. 

Adding this above line 240 fixes it by skipping the foreach loop and just selecting the first array entry:
$user = $this->ldapToUser($entries[0]);

this results in:

librenms:/opt/librenms/scripts# ./auth_test2.php -u lnms
Authentication Method: ldap
Password:
Authenticate user lnms:

User (lnms):
  username => lnms
  realname => lnmsdisplay
  user_id => 0
  email => lnms@example.com
  level => 10
Groups: ; cn=admin,ou=groups,dc=example,dc=com

No idea why the foreach is not working as it looks like it should. Sorry I can't be more help.

Separately in librenms/LibreNMS/Authentication/LdapAuthorizer.php line 363:
'user_id' => (int) $entry[$uid_attr][0]

This field is the username string, so I think it fails the cast to int. Maybe that is an issue on my end, not sure.

### Output of ./validate.php

```txt
librenms:~$  /opt/librenms/validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.5.0 (2023-06-15T02:54:54+00:00)
DB Schema | 2023_05_12_071412_devices_expand_timetaken_doubles (251)
PHP       | 8.1.20
Python    | 3.10.12
Database  | MariaDB 10.5.21-MariaDB-1:10.5.21+maria~ubu2004
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Installed from package; no Composer required
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[FAIL]  We have detected that your database schema may be wrong
Database: missing table (bgpPeers)
Database: missing table (bgpPeers_cbgp)
Database: missing table (ciscoASA)
Database: missing table (dbSchema)
Database: missing table (entityState)
Database: missing table (entPhysical)
Database: missing table (entPhysical_state)
Database: missing table (hrDevice)
Database: missing table (hrSystem)
Database: missing table (juniAtmVp)
Database: extra table (bgppeers)
Database: extra table (bgppeers_cbgp)
Database: extra table (ciscoasa)
Database: extra table (dbschema)
Database: extra table (entitystate)
Database: extra table (entphysical)
Database: extra table (entphysical_state)
Database: extra table (hrdevice)
Database: extra table (hrsystem)
Database: extra table (juniatmvp)
	[FIX]:
	Run the following SQL statements to fix it
	SQL Statements:
	 CREATE TABLE `bgpPeers` (`bgpPeer_id` int unsigned NOT NULL auto_increment, `device_id` int unsigned NOT NULL , `vrf_id` int unsigned NULL , `astext` varchar(255) NOT NULL , `bgpPeerIdentifier` text NOT NULL , `bgpPeerRemoteAs` bigint NOT NULL , `bgpPeerState` text NOT NULL , `bgpPeerAdminStatus` text NOT NULL , `bgpPeerLastErrorCode` int NULL , `bgpPeerLastErrorSubCode` int NULL , `bgpPeerLastErrorText` varchar(254) NULL , `bgpPeerIface` int unsigned NULL , `bgpLocalAddr` text NOT NULL , `bgpPeerRemoteAddr` text NOT NULL , `bgpPeerDescr` varchar(255) NOT NULL DEFAULT '' , `bgpPeerInUpdates` int NOT NULL , `bgpPeerOutUpdates` int NOT NULL , `bgpPeerInTotalMessages` int NOT NULL , `bgpPeerOutTotalMessages` int NOT NULL , `bgpPeerFsmEstablishedTime` int NOT NULL , `bgpPeerInUpdateElapsedTime` int NOT NULL , `context_name` varchar(128) NULL , PRIMARY KEY (`bgpPeer_id`), INDEX `bgppeers_device_id_context_name_index` (`device_id`,`context_name`));
	 CREATE TABLE `bgpPeers_cbgp` (`device_id` int unsigned NOT NULL , `bgpPeerIdentifier` varchar(64) NOT NULL , `afi` varchar(16) NOT NULL , `safi` varchar(16) NOT NULL , `AcceptedPrefixes` int NOT NULL , `DeniedPrefixes` int NOT NULL , `PrefixAdminLimit` int NOT NULL , `PrefixThreshold` int NOT NULL , `PrefixClearThreshold` int NOT NULL , `AdvertisedPrefixes` int NOT NULL , `SuppressedPrefixes` int NOT NULL , `WithdrawnPrefixes` int NOT NULL , `AcceptedPrefixes_delta` int NOT NULL , `AcceptedPrefixes_prev` int NOT NULL , `DeniedPrefixes_delta` int NOT NULL , `DeniedPrefixes_prev` int NOT NULL , `AdvertisedPrefixes_delta` int NOT NULL , `AdvertisedPrefixes_prev` int NOT NULL , `SuppressedPrefixes_delta` int NOT NULL , `SuppressedPrefixes_prev` int NOT NULL , `WithdrawnPrefixes_delta` int NOT NULL , `WithdrawnPrefixes_prev` int NOT NULL , `context_name` varchar(128) NULL , UNIQUE `bgppeers_cbgp_device_id_bgppeeridentifier_afi_safi_unique` (`device_id`,`bgpPeerIdentifier`,`afi`,`safi`), INDEX `bgppeers_cbgp_device_id_bgppeeridentifier_context_name_index` (`device_id`,`bgpPeerIdentifier`,`context_name`));
	 CREATE TABLE `ciscoASA` (`ciscoASA_id` int unsigned NOT NULL auto_increment, `device_id` int unsigned NOT NULL , `oid` varchar(255) NOT NULL , `data` bigint NOT NULL , `high_alert` bigint NOT NULL , `low_alert` bigint NOT NULL , `disabled` tinyint NOT NULL DEFAULT '0' , PRIMARY KEY (`ciscoASA_id`), INDEX `ciscoasa_device_id_index` (`device_id`));
	 CREATE TABLE `dbSchema` (`version` int NOT NULL DEFAULT '0' , PRIMARY KEY (`version`));
	 CREATE TABLE `entityState` (`entity_state_id` int unsigned NOT NULL auto_increment, `device_id` int unsigned NULL , `entPhysical_id` int unsigned NULL , `entStateLastChanged` datetime NULL , `entStateAdmin` int NULL , `entStateOper` int NULL , `entStateUsage` int NULL , `entStateAlarm` text NULL , `entStateStandby` int NULL , PRIMARY KEY (`entity_state_id`), INDEX `entitystate_device_id_index` (`device_id`));
	 CREATE TABLE `entPhysical` (`entPhysical_id` int unsigned NOT NULL auto_increment, `device_id` int unsigned NOT NULL , `entPhysicalIndex` int NOT NULL , `entPhysicalDescr` text NOT NULL , `entPhysicalClass` text NOT NULL , `entPhysicalName` text NOT NULL , `entPhysicalHardwareRev` varchar(64) NULL , `entPhysicalFirmwareRev` varchar(64) NULL , `entPhysicalSoftwareRev` varchar(64) NULL , `entPhysicalAlias` varchar(32) NULL , `entPhysicalAssetID` varchar(32) NULL , `entPhysicalIsFRU` varchar(8) NULL , `entPhysicalModelName` text NOT NULL , `entPhysicalVendorType` text NULL , `entPhysicalSerialNum` text NOT NULL , `entPhysicalContainedIn` int NOT NULL , `entPhysicalParentRelPos` int NOT NULL , `entPhysicalMfgName` text NOT NULL , `ifIndex` int NULL , PRIMARY KEY (`entPhysical_id`), INDEX `entphysical_device_id_index` (`device_id`));
	 CREATE TABLE `entPhysical_state` (`id` bigint unsigned NOT NULL auto_increment, `device_id` int unsigned NOT NULL , `entPhysicalIndex` varchar(64) NOT NULL , `subindex` varchar(64) NULL , `group` varchar(64) NOT NULL , `key` varchar(64) NOT NULL , `value` varchar(255) NOT NULL , PRIMARY KEY (`id`), INDEX `device_id_index` (`device_id`,`entPhysicalIndex`));
	 CREATE TABLE `hrDevice` (`hrDevice_id` int unsigned NOT NULL auto_increment, `device_id` int unsigned NOT NULL , `hrDeviceIndex` int NOT NULL , `hrDeviceDescr` text NOT NULL , `hrDeviceType` text NOT NULL , `hrDeviceErrors` int NOT NULL DEFAULT '0' , `hrDeviceStatus` text NOT NULL , `hrProcessorLoad` tinyint NULL , PRIMARY KEY (`hrDevice_id`), INDEX `hrdevice_device_id_index` (`device_id`));
	 CREATE TABLE `hrSystem` (`hrSystem_id` int unsigned NOT NULL auto_increment, `device_id` int unsigned NOT NULL , `hrSystemNumUsers` int NULL , `hrSystemProcesses` int NULL , `hrSystemMaxProcesses` int NULL , PRIMARY KEY (`hrSystem_id`), INDEX `hrsystem_device_id_index` (`device_id`));
	 CREATE TABLE `juniAtmVp` (`id` bigint unsigned NOT NULL auto_increment, `juniAtmVp_id` int unsigned NOT NULL , `port_id` int unsigned NOT NULL , `vp_id` int unsigned NOT NULL , `vp_descr` varchar(32) NOT NULL , PRIMARY KEY (`id`), INDEX `juniatmvp_port_id_index` (`port_id`));
	 DROP TABLE `bgppeers`;
	 DROP TABLE `bgppeers_cbgp`;
	 DROP TABLE `ciscoasa`;
	 DROP TABLE `dbschema`;
	 DROP TABLE `entitystate`;
	  and 5 more...
Attempt to fix this issue (y or n)?:n
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No python wrapper pollers found
[OK]    Redis is unavailable
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[FAIL]  Scheduler is not running
	[FIX]:
	cp /opt/librenms/dist/librenms-scheduler.service /opt/librenms/dist/librenms-scheduler.timer /etc/systemd/system/
systemctl enable librenms-scheduler.timer
systemctl start librenms-scheduler.timer
[WARN]  Non-git install, updates are manual or from package
```

### What was the last working version of LibreNMS?

23.5.0

### Anything in the logs that might be useful for us?

```txt
testing against lldap. It's a very simple ldap server an easy to test against as a container.
```

**Comment by murrant** [comment]
@nitnelave you sure it isn't a bug in lldap or issue with your configuration?  Issue hasn't occurred with any other LDAP server.

**Comment by nitnelave** [comment]
I looked at the LDAP request/responses in the conversation, they seem entirely valid. My guess is that they're valid, but different from what OpenLDAP returns, and LibreNMS relies on a field that isn't present in LLDAP's response, or something like that.

You can see the LDAP record of the conversation here: 
[message.txt](https://github.com/librenms/librenms/files/12261172/message.txt)

We also have the librenms logs if you want.

**Comment by murrant** [comment]
Different from: OpenLDAP, Active Directory, JumpCloud, Google, and Okta.

**Comment by nitnelave** [comment]
😅 fair enough. It may eventually turn out to be an issue in LLDAP, I admit, but so far I don't see any issue in the LDAP messages returned, and @jacobw seems to have tracked the problem to a line in LibreNMS. LLDAP also has a long list of clients that it's working fine with: https://github.com/lldap/lldap#sample-client-configurations, so it's not trivial to say who's not respecting the protocol.

I know that LLDAP doesn't implement a full LDAP server (intentionally), but for a typical read-only use case like that, it should be fully supported.

**Comment by murrant** [comment]
If you think you can fix it without breaking other LDAP servers, go ahead and create a pull request.

**Comment by jacobw** [comment]
Just tried that and it doesn't fix it. It never correctly populates $user.

librenms:/opt/librenms/scripts# ./auth_test2.php -u lnms Authentication Method: ldap Password: Authenticate user lnms:
User (lnms): Groups: ; cn=admin,ou=groups,dc=example,dc=com

I noticed that the existing code should have still printed 2 arrays even if the first one didn't populate correctly, it only printed one. It's like it was finding the 'count' entry in entries instead of the actual entry.

**Comment by nitnelave** [comment]
It seems that librenms is trying to read the "uidnumber" config attribute for the integer identifier for the user. LLDAP doesn't have an integer identifier for users, so maybe that's what's missing. It would explain the authentication failures, since that's what's compared to identify users. I'm not sure what PHP does when you cast a string to an int, but I think that's what the code is trying to do.

**Comment by murrant** [comment]
@nitnelave why not just set auth_ldap_uid_attribute to another attribute?

**Comment by nitnelave** [comment]
There's no number too uniquely identify a user in the response. I'm working on that :)

**Comment by murrant** [comment]
Why does it have to be a number?

**Comment by jacobw** [comment]
user_id is cast to an int on the function below in LdapAuthorizer.php which I think just leaves the field empty. I'm not sure what the knock on effect of that it but I assume that breaks things.

/**
     * @param  array  $entry  ldap entry array
     * @return array
     */
    private function ldapToUser($entry)
    {
        $uid_attr = strtolower(Config::get('auth_ldap_uid_attribute', 'uidnumber'));

        return [
            'username' => $entry['uid'][0],
            'realname' => $entry['cn'][0],
            'user_id' => (int) $entry[$uid_attr][0],
            'email' => $entry[Config::get('auth_ldap_emailattr', 'mail')][0],
            'level' => $this->getUserlevel($entry['uid'][0]),
        ];
    }

**Comment by nitnelave** [comment]
AFAIU, the ldapToUser function looks up the "uidNumber" attribute in the
response to get a number for the user (that's what's cast to int). And it's
probably empty. It's just a guess though, so maybe instrumenting this
function to check if the field is present and logging something if it's not
could help narrow it down?

**Comment by jacobw** [comment]
I think the result of the cast is a result of 0. I tried removing the cast incase it wasn't actually required but nothing changed so I think it's needed elsewhere.

without cast:
librenms:/opt/librenms# ./scripts/auth_test.php -u admin
Authentication Method: ldap
Password:
Authenticate user admin:
AUTH SUCCESS

User ():
  username => admin
  realname => Administrator
  user_id =>
  email =>
  level => 10
Groups: cn=nms_admin,ou=groups,dc=example,dc=com

with cast (normal)
librenms:/opt/librenms# ./scripts/auth_test.php -u admin
Authentication Method: ldap
Password:
Authenticate user admin:
AUTH SUCCESS

User ():
  username => admin
  realname => Administrator
  user_id => 0
  email =>
  level => 10
Groups: cn=nms_admin,ou=groups,dc=example,dc=com

**Comment by murrant** [comment]
That cast to integer isn't needed.  The "user_id" from legacy authentication is stored in the "auth_id" user field which is a varchar.

**Comment by jacobw** [comment]
There are 4 cast to int:

librenms:/opt/librenms/LibreNMS/Authentication# grep user_id LdapAuthorizer.php.orig LdapAuthorizationAuthorizer.php.orig  | grep int
LdapAuthorizer.php.orig:            if ((int) $user['user_id'] !== (int) $user_id) {
LdapAuthorizer.php.orig:            'user_id' => (int) $entry[$uid_attr][0],
LdapAuthorizationAuthorizer.php.orig:            $user_id = (int) $entries[0]['uidnumber'][0];
LdapAuthorizationAuthorizer.php.orig:            if ((int) $user['user_id'] === (int) $user_id) {

I I remove the casts I can successfully log in as admin with level 10.

Can these cast's be removed if I submit a PR?

**Comment by jacobw** [comment]
https://github.com/librenms/librenms/pull/15205

**Comment by jacobw** [comment]
This was fixed by https://github.com/librenms/librenms/pull/15205
