### ISSUE TITLE
Oxidised configuration retrieval timeout too low

### ISSUE THREAD

**Issue by roelfdiedericks** [librenms/librenms#15222]
### The problem

I have a fairly large number of devices in Oxidized, and the HTTP request timeout in ApiClients/Oxidized.php defaults to 90 seconds.

I have nodes that can take well over 180 seconds to retrieve a configuration from Oxidised.

Can the timeout in ApiClients/Oxidized.php be made a config.php item please?

e.g. something like the following...

 public function __construct()
    {
        **$this->timeout = Config::get('oxidized.timeout') ? Config::get('oxidized.timeout') : 90;**
        $this->base_uri = Config::get('oxidized.url') ?? '';
        $this->enabled = Config::get('oxidized.enabled') === true && $this->base_uri;
    }

### Output of ./validate.php

```txt
Not required.
```

**Comment by electrocret** [comment]
Just wondering.
-Do you have your Oxidized output to a git repo?
-if yes, do you have show revision history enabled?
-if yes, have you tried disabling it?

I ask these series of questions cause the ruby library that Oxidized uses is notoriously slow. 
I personally have disabled the revision history, and have Oxidized push the config repo to my Gitlab. 

IMO, if I have to wait over 90 seconds to see a config, I don't want to see it anymore.

**Comment by PipoCanaja** [comment]
Hi @roelfdiedericks 
Feel free to submit a patch and we'll discuss the PR with you. LibreNMS is built by users like you and me.
Bye
