### ISSUE TITLE
Wireless AP's : Interference index (meaning)

### ISSUE THREAD

**Issue by any4one** [librenms/librenms#15229]
### The problem

![image](https://github.com/librenms/librenms/assets/21181551/3373f672-c757-4185-a3db-3d7d0da9b5bf)
Dear guyz,
please i need to know exactly the meaning of those information regarding Aps. Does interference index mean SNR?

### Output of ./validate.php

```txt
Dear guyz,
please i need to know exactly the meaning of those information regarding Aps. Does interference index mean SNR?
```

### What was the last working version of LibreNMS?

22.10.0

**Comment by PipoCanaja** [comment]
Hi, 
It depends on the Wireless device. You can check what value is polled by LibreNMS on your device, and read the documentation from the vendor describing this value.
