### ISSUE TITLE
95th Traffic bills - Multiple devices and vlans

### ISSUE THREAD

**Issue by olafurh** [librenms/librenms#15239]
### The problem

When selecting a single device and subinterface, the traffic bills are generated correctly. For instance, when the billed port is set to Bundle-Ether1.123 on core03.router, the calculations are accurate.

However, an issue arises when selecting multiple devices or subinterfaces for a bill. As an example, when the billed ports are set to Bundle-Ether1.123 on core03.router AND Bundle-Ether1.123 on core04.router, the 95th percentile calculations appear to compute the 95th of both devices as a whole and not their sum of individual subinterfaces. This results in inaccurate calculations.

![image](https://github.com/librenms/librenms/assets/1606300/345e9f8b-53f2-4d9c-aa05-850d94f7e101)
note that the single interface in this calculation is carring the active traffic

![image](https://github.com/librenms/librenms/assets/1606300/4ff98b72-5568-4dab-8f0b-0ebd742b0e8e) 
Working
![image](https://github.com/librenms/librenms/assets/1606300/a22a53a0-aad5-456e-b1b5-dbe8fd1581c7)
Not working

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.8.1 (2023-08-21T05:31:19+00:00)
DB Schema | 2023_08_02_120455_vendor_ouis_unique_index (255)
PHP       | 8.2.7
Python    | 3.9.2
Database  | MariaDB 10.5.19-MariaDB-0+deb11u2
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================

[OK]    Composer Version: 2.5.8
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[FAIL]  Both Dispatcher Service and Python Wrapper were active recently, this could cause double polling
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

23.8.1

**Comment by murrant** [comment]
@olafurh it sounds like you are describing something that should be two separate bills.

**Comment by olafurh** [comment]
No - both Bundle-Ether1.123 are part of HSRP on different routers.

**Comment by murrant** [comment]
You haven't given enough information for me to know what you are looking for:
1. give the 95th and usage for each individual port
2. show the actual value (done)
3. show the expected outcome
4. I don't know the layout and configuration of your network, what devices you are using (or probably have any experience with them) so you are going to have to hold my hand a bit more.

In particular, I can't figure out what you mean by this `compute the 95th of both devices as a whole and not their sum of individual subinterfaces`
