### ISSUE TITLE
Customize warning levels for storage in webui

### ISSUE THREAD

**Issue by clinta** [librenms/librenms#1524]
`storage.storage_perc_warn` seems to default to 60, but can be updated manually. This field with an alert for `%storage.storage_perc > %storage.storage_perc_warn` is very useful. It'd be great if there was a way to change the storage_perc_warn value via the web interface.

**Comment by f0o** [comment]
:+1:

**Comment by laf** [comment]
Working on this, should be done by tomorrow.
