### ISSUE TITLE
Get Links beetween Port-Channel

### ISSUE THREAD

**Issue by Ryad3** [librenms/librenms#15251]
### The problem

Hello, I'm currently trying to write a script that will gather all links from a list of device_id. I'm using the API but the issue is that when i'm using this API's path : /api/v0/devices/:device_id/links, just neighboors that are discovered by 'xdp' are in the response, and i want Port-Channel and Bundle too. I tried to use others one as ARP but it's not suitable. 

### Output of ./validate.php

```txt
.
```

### What was the last working version of LibreNMS?

22.9.0

**Comment by murrant** [comment]
@Ryad3 xdp doesn't report for port channels, only physical links.  Not a limitation of LibreNMS, but the design of  the protocol.

**Comment by Ryad3** [comment]
Thanks you for the answer. I understood that Links that are generated by the API are with xdp, and i wasn't thinking it was a limitation, i just wanted to know if there are others ways to have the 2 port_id beetween port Channel or Bundle of a Link with using the Librenms API.

**Comment by murrant** [comment]
I'm saying almost all devices I know of don't report which ports are in a bundle or port channel.  There is no way of LibreNMS knowing which ones belong together.  If you asking for advice on how to use LiberNMS, but bug tracker is not the correct place.
