### ISSUE TITLE
Requesting ability to create alarms from sensor page

### ISSUE THREAD

**Issue by dcslv** [librenms/librenms#1525]
It would be nice to be able to create alarms associated with sensors from the sensor itself. 
For example a bandwidth alarm on an interface from the rrd page. 
This would make adding sensors much simpler.

**Comment by laf** [comment]
Would people find this useful, I've thought it would be a good idea previously but now having second thoughts. The alert rules are typically created as generic items, I'm not sure how useful it is to be able to create a 100 different rules which all could be dealt with in a handful.

What do others think?

**Comment by Alastair-VOIPUNLIMITED** [comment]
If this would be overriding any existing alarms affecting that device, IE have some global sensor alert rules but then be able to create exceptions using this, then it would be incredibly useful.

**Comment by f0o** [comment]
```irc
18:46:49        dcslv | it would be easier if i could click on a graph and set limits                                          
18:46:51        dcslv | upper and lower                                
18:46:57        dcslv | and get alerted when it violates it
```

This seems plausible, it would require Per-Graph/Entity boundaries and then a single rule can do all the checks required.

**Comment by dcslv** [comment]
As a refinement of this request I'd also add that this could easily exist within the same framework of your current alerting system. 
What i mean by that, is that by creating these alarms from the same page the graph is displayed on could simply use the same logic as the existing alerting page but take the guessing out of the entities and macros (for users like me who are not programmers this would make it easier to quickly create important alerts without having to do any extra leg work)
Subsequent to that if these thresholds created alert rules that were displayed alongside the exiting alert rules, it would help as a way to interpret what macros and entities are being used so that it would be easier overall to add alerts. 
This request is simply aimed at more closely associating the alarm levels with the actual device they're being created for with regard to the GUI.

**Comment by laf** [comment]
Working on generic button to create alert rule from sensor, will pre-populate a rule and limit it to the device and sensor id.

**Comment by laf** [comment]
Take a look at the PR #1755 - it may be what you were after it may not.

**Comment by laf** [comment]
Proposing to close in 48 hours.
