### ISSUE TITLE
Cannot find module (SNMP-VACM-MIB): At line 15 in (none)

### ISSUE THREAD

**Issue by Oirbsiu** [librenms/librenms#15282]
### The problem

I recenty added an ASA Firewal to my Libre set up - on running the discovery I noted an error - 

`SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' 'udp:HOSTNAME:161' 'SNMPv2-MIB::sysObjectID.0']  

SNMPv2-MIB::sysObjectID.0 = SNMPv2-SMI::enterprises.9.1.1408
  

MIB search path: /opt/librenms/mibs:/opt/librenms/mibs/cisco
Cannot find module (SNMP-VACM-MIB): At line 15 in (none)
 `
Should the the line in NetSnmpQuery.php 

`Line 86    private array $mibs = ['SNMPv2-TC', 'SNMPv2-MIB', 'IF-MIB', 'IP-MIB', 'TCP-MIB', 'UDP-MIB', 'SNMP-VACM-MIB'];`

be 'NET-SNMP-VACM-MIB'

If I change this in my code, I no longer see the error

### Output of ./validate.php

```txt
[librenms@librenms ~]$ ./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.8.2-25-g6d1b1ac1f (2023-09-04T04:47:23+01:00)
DB Schema | 2023_09_01_084057_application_new_defaults (258)
PHP       | 8.1.20
Python    | 3.9.17
Database  | MariaDB 10.5.16-MariaDB
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.5.8
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### Anything in the logs that might be useful for us?

```txt
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' 'udp:HOSTNAME:161' 'SNMPv2-MIB::sysObjectID.0']  

Exitcode: 1 ["MIB search path: /opt/librenms/mibs\nCannot find module (SNMP-VACM-MIB): At line 12 in (none)\n
```

**Comment by murrant** [comment]
Thanks for the report
