### ISSUE TITLE
alert template issue

### ISSUE THREAD

**Issue by Alastair-VOIPUNLIMITED** [librenms/librenms#1529]
Hi guys, 

As per mentioned in #1509.

When writing in %value.variable into alert templates they often do not work. For example:

{foreach %faults} Sensor-Value of Fault #%key: %value.sensor_class on %value.sensor_descr currently at %value.sensor_current (>%value.sensors.sensor_limit) {/foreach}

gives this example output:

Sensor-Value of Fault #1: current on Output currently at 3.7 (>)

Please let me know if this is me being useless (as previously i reported this and i had a typo, but this time it seems to be a bug.)

Thanks guys

Alastair

**Comment by laf** [comment]
Hi,

That looks fine to me:

Sensor-Value of Fault #%key: = Sensor-Value of Fault #1:
%value.sensor_class on = current on
%value.sensor_descr currently at = Output currently at
%value.sensor_current = 3.7

So sensor_class is current and sensor_descr is Output. Whislt descr might not be that descriptive it's either what's returned by the device or no descr was set so we've set it to Output.

**Comment by Alastair-VOIPUNLIMITED** [comment]
however "%value.sensors.sensor_limit" is not honored? 

Idea was to have the upper limit shown in the brackets afterwards

**Comment by laf** [comment]
Use %value.sensor_limit instead?

**Comment by f0o** [comment]
Quoting: %value.sensors.sensor_limit
Is wrong.
Only %value.sensor_limit would be correct

**Comment by Alastair-VOIPUNLIMITED** [comment]
just retested, it was indeed me being useless, sorry to waste time, :)
