### ISSUE TITLE
AD-Authorization broken because of [count] in "group-array"

### ISSUE THREAD

**Issue by LKLG** [librenms/librenms#15304]
### The problem

Last week we noticed that we could no longer log in to librenms with our active directory accounts.

Today I found the time to investigate the problem. 

In the "LibreNMS/Authentication/ADAuthorizationAuthorizer.php" line 116 the common name is read from the values of the array. However, the first value in the array is not a cn, but the number of elements in the array via the key [count].

my workaround:

Lines 115-117 changed from

foreach ($entries[0]['memberof'] as $entry) {
            $group_cn = $this->getCn($entry);

to
foreach ($entries[0]['memberof'] as $ekey => $entry) {
            if ($ekey == "count") { continue; }
            $group_cn = $this->getCn($entry);

### Output of ./validate.php

```txt
librenms@librenms01:~$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.8.2-38-g74ed7aa70 (2023-09-08T23:48:27+02:00)
DB Schema | 2023_08_30_105156_add_applications_soft_deleted (259)
PHP       | 8.2.10
Python    | 3.9.2
Database  | MariaDB 10.5.19-MariaDB-0+deb11u2
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================

[OK]    Composer Version: 2.6.2
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Your install is over 24 hours out of date, last update: Fri, 08 Sep 2023 21:48:27 +0000
        [FIX]:
        Make sure your daily.sh cron is running and run ./daily.sh by hand to see if there are any errors.
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]:
        You can fix this with ./scripts/github-remove
        Modified Files:
         LibreNMS/Authentication/ADAuthorizationAuthorizer.php
```

**Comment by ottorei** [comment]
Unfortunately my (Windows) AD authentication seems to work fine with the latest code. If I may ask, what kind of AD setup are you running on? The same kind of bug was seen on LDAP after the RBAC feature (https://github.com/librenms/librenms/pull/15259). 

Anyway, could you create a PR of this fix? Thanks.
