### ISSUE TITLE
Unable to configure SAML2 account / broken login

### ISSUE THREAD

**Issue by LoZio** [librenms/librenms#15308]
### The problem

I configured a SAML2 application in my Google Workspace as per https://docs.librenms.org/Extensions/OAuth-SAML/#saml2-example
Then I tried to create a user in the local users of LibreNMS that matches the one I use with Google SSO. The username, as always and as described in the linked config, is the primary email of the user.
If you try to create a user having the email as the username, you are blocked as the email format is not supported
![image](https://github.com/librenms/librenms/assets/869890/bd4250e3-0b7c-4cb2-85fb-105def3809d5)
So you can't add users from your SAML2 provider.
Also any login with the traditional user/password combo fails with
![image](https://github.com/librenms/librenms/assets/869890/ddd81753-e8de-4abe-b0e5-ccef72dcd436)
I'm trying a way to roll-back to the old config...

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.8.2 (2023-08-21T17:48:13+02:00)
DB Schema | 2023_08_02_120455_vendor_ouis_unique_index (255)
PHP       | 8.1.22
Python    | 3.9.2
Database  | MariaDB 10.5.19-MariaDB-0+deb11u2
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================

[OK]    Composer Version: 2.6.2
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    Python wrapper cron entry is not present
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

**Comment by LoZio** [comment]
Ok, the login with traditional account was fixed *removing* the
`SESSION_SAME_SITE_COOKIE=none`
that was addedd following the doc from the .env file

**Comment by LoZio** [comment]
In the logs, when a SAML2 login fails, and of course it does since there is no mapped user defined, I find
`{"exception":"[object] (Laravel\\Socialite\\Two\\InvalidStateException(code: 0):  at /opt/librenms/vendor/socialiteproviders/saml2/Provider.php:551)"}`

**Comment by murrant** [comment]
You do not create users for SAML manually. They are created upon login.

**Comment by LoZio** [comment]
Enabled also that option in the Socialite setup, no user is created this is why I asked

**Comment by murrant** [comment]
Like create user should be disabled an unavailable when using anything other than mysql auth.  I'm not sure how you accessed the create user page and it is bothering me a bit.

**Comment by LoZio** [comment]
I reached it via the usual menu. Following the config instruction in the page at the opening post I end up having both the option for local login and a button for SAML2

**Comment by murrant** [comment]
local login won't work though.  that should also be hidden.

**Comment by LoZio** [comment]
![image](https://github.com/librenms/librenms/assets/869890/c35b7b78-4f32-4865-832e-343093370e77)
this is my current login page. SAML2 not working, local working

**Comment by murrant** [comment]
Ok, I guess I misunderstood how SAML2 works in LibreNMS a bit (and so did you).

**Comment by murrant** [comment]
I'm probably going to close this as it is a support request.  Please ask for help on the community site or Discord.

**Comment by LoZio** [comment]
Not sure about the support request. Is there a different doc that explains what I miunderstood and the "correct" way to configure SAML2?
I have configured dozens of SAML2 applications, LibreNMS is one of the last that were kept behind so I would like to configure also this one.

**Comment by murrant** [comment]
I don't see a specific bug here.  If after you try to get help from the support channels and find a specific thing that isn't working then you should file a bug report.
