### ISSUE TITLE
Mikrotik temp sensors negative issue

### ISSUE THREAD

**Issue by murrant** [librenms/librenms#15323]
Hi

Version LibreNMS 23.8.2-41-ga1eb90fe6 - Tue Sep 12 2023
Database Schema 2023_08_30_105156_add_applications_soft_deleted (259)

I have Mikrotik access points installed in a cold room, the temperature is minus 18 Celsius. The temperature of the access point itself was about zero. Recently, the temperature in the room was lowered and the temperature of the access point dropped to -1 and -3 Celsius. LibrNMS incorrectly converts negative values. In LibreNMS and on charts, negative values are displayed as 4294967294, 4294967295, 4294967294. The warning "The sensor is under restriction - Check the device health settings" is constantly displayed.

Can anyone suggest how to solve this problem?

A little information for diagnosis:

rrdtool graph /tmp/73g5PyvZtH3g95sc --start 1694525400 --end 1694611800 --width 1367 --height 300 --imgformat=SVG --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal -c FONT\#000000 -c BACK\#EEEEEE00 -c SHADEA\#EEEEEE00 -c SHADEB\#EEEEEE00 -c CANVAS\#FFFFFF00 -c GRID\#a5a5a5 -c MGRID\#FF9999 -c FRAME\#5e5e5e -c ARROW\#5e5e5e -l 0 -u 60 --slope-mode  COMMENT:'                          Min     Last   Max\\n' DEF:sensor=/opt/librenms/rrd/AP-5/sensor-temperature-routeros-mtxrGaugeTemperature.14.rrd:sensor:AVERAGE DEF:sensor_max=/opt/librenms/rrd/AP-5/sensor-temperature-routeros-mtxrGaugeTemperature.14.rrd:sensor:MAX DEF:sensor_min=/opt/librenms/rrd/AP-5/sensor-temperature-routeros-mtxrGaugeTemperature.14.rrd:sensor:MIN CDEF:sensorwarm=sensor_max,4294967314,GT,sensor,UNKN,IF CDEF:sensorcold=sensor_min,20,LT,sensor,UNKN,IF CDEF:sensor_diff=sensor_max,sensor_min,- AREA:sensor_min AREA:sensor_diff\#c5c5c5::STACK LINE1.5:sensor\#cc0000:'temperature           ' GPRINT:sensor_min:MIN:%4.1lfC GPRINT:sensor:LAST:%4.1lfC GPRINT:sensor_max:MAX:%4.1lfC\\l HRULE:4294967314\#999999::dashes HRULE:4294967284\#999999::dashes

/system/health/print show-ids oid
*D name=.1.3.6.1.4.1.14988.1.1.3.100.1.2.13 
   value=.1.3.6.1.4.1.14988.1.1.3.100.1.3.13 
   type=.1.3.6.1.4.1.14988.1.1.3.100.1.4.13 

*E name=.1.3.6.1.4.1.14988.1.1.3.100.1.2.14 
   value=.1.3.6.1.4.1.14988.1.1.3.100.1.3.14 
   type=.1.3.6.1.4.1.14988.1.1.3.100.1.4.14 

/system/health/print 
Columns: NAME, VALUE, TYPE
-#  NAME         VALUE  TYPE
0  voltage      22.9   V   
1  temperature  -3     C

_Originally posted by @sergf0 in https://github.com/librenms/librenms/issues/15289#issuecomment-1717832179_

**Comment by murrant** [comment]
@sergf0 can you post some discovery debug output?  I'm not sure if the bug is in the Mikrotiks or LibreNMS.

**Comment by murrant** [comment]
There are no issues with LibreNMS handling negative values.  Perhaps the device itself is sending bad data.

**Comment by sergf0** [comment]
Yes, I can probably provide a debug, what needs to be done?

I remembered.
Some time ago I was playing with Arduino. Faced with such a problem.
I used unsigned long as a counter, but I did not provide for possible negative values in the program, as a result, when going below zero, I got the maximum value of unsigned long in the output.
Perhaps this will help in finding the problem.

**Comment by murrant** [comment]
Considering the device is returning 4294967293, yes this is a Mikrotik bug.  Open a ticket with them.

**Comment by sergf0** [comment]
Created a ticket in Mikrotik

**Comment by tippenring** [comment]
@sergf0 I'm curious what results you got with Mikrotik support.

I have the same issue with some outdoor equipment. It appears to me that the gauge32 valid range is 0 to 2^32-1, so Mikrotik is returning an unsigned integer to indicate values < 0. 

Should Mikrotik change to return signed integers?

**Comment by midyrp** [comment]
doing upgrades in steps and it's still an issue in routeros 7.5
will test more later, the temperature reached just 0 now ; )

**Comment by tippenring** [comment]
Just happened to find the likely fix in the release notes for 7.12 yesterday. I haven't had a chance to test it yet though.

[snmp - changed "mtxrGaugeValue" type to integer; ](https://mikrotik.com/download/changelogs/#show-tab-tree_2-id-05234381e090cffff2e7d94df7899f45)

**Comment by tonoitp** [comment]
it's tricky, I now read zero in the router, but librenms is already reporting 4.29 G°C
but, soon i'll continue testing...............

**Comment by sergf0** [comment]
Confirm. I have version 7.12.1 installed, librenms displays a negative temperature value.

It seems that this has been fixed since the release of 7.12?

There were no notifications from Microtik. :)
