### ISSUE TITLE
LibreNMS is support Aerohive AP230?

### ISSUE THREAD

**Issue by macbook8** [librenms/librenms#1532]
LibreNMS is Support Aerohive AP230?

**Comment by Rosiak** [comment]
Hi @macbook8 

As mentioned on IRC, are you able to supply a snmp-walk or similar?

**Comment by macbook8** [comment]
Hi Rosiak,

What is snmp-walk?

**Comment by Rosiak** [comment]
I've mailed Aerohive regarding permission to use their logo.

**Comment by f0o** [comment]
Merged with #1546
