### ISSUE TITLE
MySQL hangs during update

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#1533]
As discussed on IRC, some users are experiencing that mysql sometimes crash during an SQL update.

I'm able to reproduce the issue on a install.
The SQL starts hanging after doing this:
```mysql> LOCK TABLES `devices` WRITE;```

Part of this:
058.sql

If the locations table exists and we run the 058.sql, it goes through just fine.
If the locations tables does not exist we're able to reproduce the problem if we run the 058.sql manually again, then the mysql starts hanging.

This issue is seen on Description:	
```Ubuntu 14.04.2 LTS```
```Release:	14.04```
```mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3```

Doing the same on a Centos 6.6 with the following MySQL version works without any issues:
```mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1```

**Comment by laf** [comment]
Duplicate to #1345
