### ISSUE TITLE
F5OS Disk counts does not display correctly

### ISSUE THREAD

**Issue by zagosch** [librenms/librenms#15334]
### The problem

In 23.9.0 F5OS was added to the devices. I've discoved the devices correctly now, but on all three F5 OS rSeries devices the DISK count are counting upwards, instead of giving the current value. 

![screenshot DISK count](https://github.com/librenms/librenms/assets/10849746/b1e58c26-03dd-450b-ba20-b696bcd3289b)

Added discovery and poller output as text because of the size. 

[discovery output.txt](https://github.com/librenms/librenms/files/12657636/discovery.output.txt)
[poller output.txt](https://github.com/librenms/librenms/files/12657637/poller.output.txt)

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.9.1 (2023-09-19T03:59:06+02:00)
DB Schema | 2023_09_01_084057_application_new_defaults (259)
PHP       | 8.2.9
Python    | 3.9.16
Database  | MariaDB 10.5.16-MariaDB
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.5.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No python wrapper pollers found
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

23.9.1

### Device info

F5OS F5 rSeries 2800

### Discovery output

```txt
Added the discovery output to discovery output.txt
```

### Poller output

```txt
Added the discovery output to poller output.txt
```

**Comment by PipoCanaja** [comment]
Hi @zagosch 
The PR that should fix this is on the way. If the tests are running as expected in GitHub, I'll get back to you here, to help you  test them in your LibreNMS instance. 
Bye

**Comment by zagosch** [comment]
I'm testing the solution now, ill let it run for a couple of hours to see the results.

**Comment by zagosch** [comment]
I can confirm it gives the right data/graph now. One counter does not work, but i've discovered that the F5OS device gives the same snmp counter value back each time (Read Merged). I'll take that back to f5. 

![screenshot](https://github.com/librenms/librenms/assets/10849746/d1dd0008-27ce-4fb5-9151-ab2259ac7dec)
