### ISSUE TITLE
Paging issue in APPS -> NTP

### ISSUE THREAD

**Issue by Ac0lyte** [librenms/librenms#15344]
### The problem

While browsing **APPS** -> **NTP** I noticed that if I have more than one page of devices I get two strange paging issues.

- The first page show 10 devices (1 - 10) as expected. When I click the ">"  button, or click on one of the page numbers it only increments by 1 no 10 and I get devices 2 - 11.  This is the same if I choose 25 devices to be shown. I could not check 50 devices as I only have 32.

- If I select show "All" devices I get none and the message "No results found!"

![Screenshot 2023-09-25 at 6 17 10 PM](https://github.com/librenms/librenms/assets/4017755/f9c3825e-d9c4-46c0-8b4f-d0906a07e497)
![Screenshot 2023-09-25 at 6 15 05 PM](https://github.com/librenms/librenms/assets/4017755/0f2be209-628a-4b05-849b-72ee99b31d91)
![Screenshot 2023-09-25 at 6 11 18 PM](https://github.com/librenms/librenms/assets/4017755/a504195b-5093-4c1d-af16-b1e0be815af3)

### Output of ./validate.php

```txt
./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.9.1-15-gc8041b669 (2023-09-25T17:49:22-07:00)
DB Schema | 2023_08_30_105156_add_applications_soft_deleted (259)
PHP       | 8.1.14
Python    | 3.9.16
Database  | MariaDB 10.5.16-MariaDB
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.6.2
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### Anything in the logs that might be useful for us?

```txt
I have not seen any errors in the logs
```

**Comment by murrant** [comment]
I don't have any test data for this, you can check in: `includes/html/table/app_ntp.inc.php`

**Comment by Ac0lyte** [comment]
Thanks for the pointer! 
I found both issues and will fork and submit a pull request.

Incase anyone wants to implement or test prior to my PR here is a patch
[ntp.patch](https://github.com/librenms/librenms/files/12729890/ntp.patch)

**Comment by Ac0lyte** [comment]
https://github.com/librenms/librenms/pull/15349
