### ISSUE TITLE
New install - openssl_pkey_new(): Private key length must be at least 384 bits, configured to 0 

### ISSUE THREAD

**Issue by gotshaykes** [librenms/librenms#15353]
### The problem

Not sure this is an lnms bug or an issue in a dependency - or I'm dumb and missing something - but thought I'd report it in case. I am building a new LNMS instance from scratch on Ubuntu 22.0.4.3. When I get to the point of installing php dependencies, I receive the following error:

```
LibreNMS\ComposerHelper::postInstall
Script LibreNMS\ComposerHelper::postInstall handling the post-install-cmd event terminated with an exception

In ECKey.php line 93:

  openssl_pkey_new(): Private key length must be at least 384 bits, configured to 0
```

Environment:

- Ubuntu 22.0.4.3 LTS
- OpenSSL 3.0.2
- PHP 8.1.23
- Python 3.10.12
- MariaDB 10.6

To replicate:

1. Install Ubuntu 22.04.3
2. apt update/upgrade & reboot
3. Follow lnms installation instructions to the point of installing PHP dependencies
4. Run ./scripts/composer_wrapper.php install --no-dev
5. Install fails with error

I’ve replicated the issue on Debian 12: PHP 8.2.10, OpenSSL 3.0.9, python3 3.11.2, mariadb 10.11.3-1

Images with more details available here:
#https://community.librenms.org/t/new-install-openssl-pkey-new-private-key-length-must-be-at-least-384-bits-configured-to-0/22396

### Output of ./validate.php

```txt
Can't get to this point yet.
```

### What was the last working version of LibreNMS?

 23.9.1-15-gc8041b669 (2023-09-25T19:49:22-05:00)

**Comment by murrant** [comment]
I have never seen that error before.  What changes did you make to Ubuntu/PHP before installing?

**Comment by gotshaykes** [comment]
> I have never seen that error before. What changes did you make to Ubuntu/PHP before installing?

Same here... very strange.

No changes to Ubuntu/PHP I can think of.  :/ I performed a clean install of Ubuntu server, updated packages, then copy-pasted commands from the [install docs](https://docs.librenms.org/Installation/Install-LibreNMS/).  I thought I'd borked something, so I deleted the VM and started over, but got the same results. I then updated PHP8.1 to the latest versions from ppa:ondrej/php thinking maybe a version-specific issue, but it made no difference.

For the Debian side, I did the same: no-GUI net-install, copy-pasted commands. Everything was smooth up until php dependencies step. The only change I made to the php configuration was for timezone.

My OoO is: clean install, get it working & verify, then go back and apply security/performance tweaks. So I hadn't gotten to any customizations yet.

**Comment by gotshaykes** [comment]
Nevermind! While transferring the previous host's SSL certs/key, I accidentally overwrote the default openssl.cnf file with a cnf that was intended for csr only. I restored the default deb12/ubuntu /etc/ssl/openssl.cnf and all is good. :)
