### ISSUE TITLE
Configurable Network Map Parameters

### ISSUE THREAD

**Issue by spinza** [librenms/librenms#1536]
Idea is to make the network map paramteres in [html/includes/print-map.inc.php](https://github.com/librenms/librenms/blob/master/html/includes/print-map.inc.php) configurable via ```config.php```.

Current map configuration is not ideal for me so I want to change it.  Thought I'd just make it configurable.  

If no objections I'll start on it.
Useful to this:
http://visjs.org/network_examples.html
http://visjs.org/docs/network/physics.html#
http://visjs.org/docs/network/edges.html#

**Comment by f0o** [comment]
:+1:

**Comment by laf** [comment]
100%, it's been difficult to get exactly the right thing. I'd just allow one big json personally but not sure what others think.

**Comment by spinza** [comment]
I prefer the barnesHut for the network I'm looking at.  It works well on the default vis options from here: http://visjs.org/docs/network/physics.html#

The defaults in LibrenNMS produces a circle with a lot of connections that is not structued.  I think the defaults would work better for a structured hierarchical net.  Not a jumbled mess like what we are monitoring.
