### ISSUE TITLE
changing subject line of alerting emails

### ISSUE THREAD

**Issue by Alastair-VOIPUNLIMITED** [librenms/librenms#1537]
Hi Team,

Is it possible to change the subject line of alerting emails?

"device recovered from device down alert" can be rather confusing to some :)

Cheers.

**Comment by f0o** [comment]
What would be less confusing?

**Comment by Alastair-VOIPUNLIMITED** [comment]
if in the alerting template page we could change the subject line?

enabling us to change the recovery subject line to something like: "Device has recovered" or "Device is back up." Just examples for a device down template?

**Comment by f0o** [comment]
Tagging: #1314 
Will be dealt with in the above tagged issue. Leaving issue open as reminder.
