### ISSUE TITLE
Wall of "Ping Latency" alerts after midnight update

### ISSUE THREAD

**Issue by RafalNiewinski** [librenms/librenms#15382]
### The problem

Hello, after today nightly update I have a wall of "Ping Latency" alerts (9 of 17 of my devices currently altering) but in real test the ping is normal and also ping graphs says that there is no problem.

![obraz](https://github.com/librenms/librenms/assets/1041387/6bbdd0cf-5e4a-413e-950e-10364dd8683a)
![obraz](https://github.com/librenms/librenms/assets/1041387/8d758805-f857-4e69-b994-458af87fef35)

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.9.1-41-ge0444bffc (2023-10-04T23:32:02+02:00)
DB Schema | 2023_08_30_105156_add_applications_soft_deleted (259)
PHP       | 8.1.2-1ubuntu2.14
Python    | 3.10.12
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================
```

**Comment by fbouynot** [comment]
Hi, same here.
On ~350 devices, we get 12 in latency error since 00:20am (cron daily.sh runs at 00:19): the 12 NXOS. (we have 12 devices running NXOS only)

I guess from the recent merged PR, it might come from https://github.com/librenms/librenms/pull/15370 but I'm not sure about that.

**Comment by murrant** [comment]
Check your librenms.log file for errors.

**Comment by murrant** [comment]
The ping time taken looks wrong, says it took longer than the whole poll :D

**Comment by RafalNiewinski** [comment]
Issue came back with tonight's update.
As I can see there are changes yesterday to the same code as previously (8f91fb3877dd70c3e8680904d4275ef20557b645)

**Comment by fbouynot** [comment]
Same here

**Comment by fbouynot** [comment]
So we should do In Poller.php: 

    private function recordPerformance(Measurement $measurement): void
    {
        $measurement->manager()->record('device', $measurement);
        $this->device->last_polled = Carbon::now();
 -       $this->device->last_ping_timetaken = $measurement->getDuration(); 
 -       $this->device->last_polled_timetaken = $measurement->getDuration();
