### ISSUE TITLE
long polling on Juniper switches highly misuse system resources

### ISSUE THREAD

**Issue by albertsulva** [librenms/librenms#15389]
### The problem

Hello, after today daily update I have problem with polling of one Juniper switch stack which have "bad" JunOS version 15.1 in which SNMP load CPU and I had to turn on "Enable selected port polling" in past as I had similar problem like this: https://community.librenms.org/t/port-polling-takes-up-to-380-seconds-on-juniper-ex-4200-series/12448. This stack lost all ports (they are as deleted now) and I had to disable polling of unneeded ports once again. Polling takes many minutes even after that.
 
There was probably some change in polling also in June because I see more CPU load and longer polling times in graphs but not as bad as it is today.

![Juniper_graphs](https://github.com/librenms/librenms/assets/116037714/4d31e46f-feed-4a48-a888-148ca83fcfcb)

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.9.1-41-ge0444bffc (2023-10-04T23:32:02+02:00)
DB Schema | 2023_08_30_105156_add_applications_soft_deleted (259)
PHP       | 8.1.11
Python    | 3.6.8
Database  | MariaDB 10.3.28-MariaDB
RRDTool   | 1.7.0
SNMP      | 5.8
===========================================

[OK]    Composer Version: 2.6.4
[OK]    Dependencies up-to-date.
[WARN]  Debug enabled.  This is a security risk.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]:
        You can fix this with ./scripts/github-remove
        Modified Files:
         rrd/.gitignore

```

**Comment by BirdDawg01** [comment]
Same issue happening here across the board after yesterday's update. Rebooting pollers restores operation for maybe 2 polls and then quits again.
![image](https://github.com/librenms/librenms/assets/109314993/9a8899ef-d519-470b-8fec-6269f4a54343)
![image](https://github.com/librenms/librenms/assets/109314993/822474b0-bc30-4fb7-8a5f-d84027d91cc7)

Also can't add new hardware. receiving module errors.
![image](https://github.com/librenms/librenms/assets/109314993/3ec786da-9131-4239-a137-6079cfd35856)

**Comment by murrant** [comment]
Everyone having this issue run `lnms config:set reporting.error false`

What happened is the poller is no longer hiding existing errors and trying to report them.  But the error reporting doesn't have any rate limiting.

**Comment by murrant** [comment]
@albertsulva can you show the error message(s) from your LibreNMS.log file?

**Comment by murrant** [comment]
Fixed by #15391

**Comment by albertsulva** [comment]
Hi, youre faster than I am. Thanks for fixing. Issues with polling seemes to be fixed and errors from librenms.log gone. But problems with high CPU load on that Juniper switch still remains. Either after device rediscovery discovered ports disappears.

**Comment by murrant** [comment]
@albertsulva You kind of have two issues. As mentioned, look in the log file (ibrenms.log) for errors and please share them.

**Comment by murrant** [comment]
Interesting, you overflowed the size of the sql column because you have process(s) that have exceeded 999 days of runtime :)

**Comment by albertsulva** [comment]
That sounds like an error in sw draft that didnt count with process living logner that 999 days to me. Am I wrong?

**Comment by murrant** [comment]
@albertsulva not really, the database field didn't allow a long enough string to store it.

**Comment by murrant** [comment]
@albertsulva can you make a new issue with new debug information because there were multiple issues.

**Comment by albertsulva** [comment]
Will do and thank you @murrant !
