### ISSUE TITLE
Adding new device smpv3 with API

### ISSUE THREAD

**Issue by julianboehne** [librenms/librenms#15433]
### The problem

I try to add a new device to my LibreNMS using api.
Following api-request:
![image](https://github.com/librenms/librenms/assets/110762908/f1a94314-100d-4ac4-91c9-1d30460a1f92)
and got follwing error:
`{ "status": "error", "message": "No information has been provided to add this new device" }`

### Output of ./validate.php

```txt
No information has been provided to add this new device
```

**Comment by murrant** [comment]
That error is checked right away to see if the json payload exists.
Do you perhaps have an error in your json payload?  Perhaps an unescaped double quote in one of the passwords?  Put your json in an online lint tool and see if it is valid.

**Comment by julianboehne** [comment]
You're right, my failure! Thanks for your help.
