### ISSUE TITLE
Syslog received and not mapped to the device

### ISSUE THREAD

**Issue by LoZio** [librenms/librenms#15454]
### The problem

I have a Librenms installation that is also a syslog server.
I have dozens of devices logging to it. I can see the logs for these devices on the devica/syslog page in Librenms since ages. I'm pretty confident it normally works.

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.9.1 (2023-09-19T03:59:06+02:00)
DB Schema | 2023_09_01_084057_application_new_defaults (259)
PHP       | 8.1.23
Python    | 3.9.2
Database  | MariaDB 10.5.19-MariaDB-0+deb11u2
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================

[OK]    Composer Version: 2.6.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    Python wrapper cron entry is not present
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### Anything in the logs that might be useful for us?

```txt
I added a new Cisco Catalyst by DNS name. The LibreNMS name can reach the device (it is in LAN), can resolve the device name, the reverse DNS of the IP resolves back to the switch name.
In the device page I see the full DNS name and the resolved IP is the one I expect (it actually has only 1 IP).
If I run a tcpdump session on LibreNMS filtering the IP of the switch I see the syslog packet coming. It comes from the expected address. Inside the syslog packet the name advertised by the device is the FQDN of the switch, the same I see in the LibreNMS device page both for DNS and sysname
I captured the device using the IP address instead of FQDN. Nothing changes.
So: name<->ip match, traffic is coming since I sniff it, in the meanwhile other devices log with no problem.
Any idea where to start debugging this problem?
```

**Comment by LoZio** [comment]
This is the message I receive on the wire
![image](https://github.com/librenms/librenms/assets/869890/7f0571cf-793c-4af5-9060-39ac67d84d4b)
and this is the device in LibreNMS
![image](https://github.com/librenms/librenms/assets/869890/a7648ad2-ffe9-43f5-ba7b-a30d54afce80)

Also tried to configure the switch to send its name in the message, it does, the name matches the one in LibreNMS, still no logs are recorded, only for this device.

**Comment by murrant** [comment]
I don't think it matches on IP when added by hostname.  Generally people set syslog to the same as they add devices to LibreNMS.  So syslog will send the name if they are using hostnames.

**Comment by LoZio** [comment]
Other threads on this topic say it matches by name, sysname and IP.
In any case I have captured the device with IP, short name, FQDN. Each time I configured the switch to send syslog using IP or names, and verified by sniffing that it is doing what I want.
Same behavior each time, packet is received from the server, nothing is sent to the syslog table. I have dozens other switches logging correctly on the same server and can sniff their traffic being exactly the same as this one, mainly captured by IP and configured to send their IP.

**Comment by murrant** [comment]
Are those other threads threads for graylog?

**Comment by LoZio** [comment]
This one https://github.com/librenms/librenms/issues/3891 and others, maybe derived from this from Iaf.
In any case as I wrote I captured the switch in any possible way with the same result.
I can sniff a packet after executing the same action from another switch , then one from the interested switch, and the only difference in the captured packets is the source IP address of the device. Same facility, level and text content.
Currently both captured via IP, correctly shown on the device pace.
If I send the same log also to another syslog collector (QRadar) it is correctly received and reported from the correct IP. The same using tftpd32 syslogd function.

**Comment by jepke** [comment]
Just worked on Graylog which i dont think you use but with graylog if syslog source is `ip` you'll need your device in librenms added with ip. Then it will query graylog with device IP and device sysname/displayname. If device is added with fqdn it will query with fqdn and sysname never query for IP address.

This is with graylog at least.

**Comment by LoZio** [comment]
This is a problem I had in the past with LibreNMS and usually it was just a metter of deleting and capturing the device via IP as you said. But if you look at the messages above this is the first thing I did (several times also) and just doesn't work.

**Comment by jepke** [comment]
Which syslog variant are you using with librenms?

**Comment by LoZio** [comment]
rsyslog, and before starting the "check this/that" please take a look at my first messages. I have dozens of devices logging into that specific installation, they all work. And the switch is configured using the same device template as the others, except for the IP address of course.
