### ISSUE TITLE
[Dark Theme] Light-grey text on white background for some menus (scheduled maintenance, event log, others?) unreadable

### ISSUE THREAD

**Issue by BloodyIron** [librenms/librenms#15495]
### The problem

As you'll see in the below screenshot, when trying to schedule systems for maintenance, the categories are effectively unreadable due to extremely poor contrast with the colour of text being light-grey on a white background. I'm using the Dark Theme that's native, and Dark Theme all the things IMO.

This has been exhibited for months(/years?) and I think this might just be an overlooked part.

Can we get this addressed at some point please? There may be some other areas in libreNMS webGUI that I might be missing too, but this is an easily found one. Thanks!

![image](https://github.com/librenms/librenms/assets/12439391/42796956-6661-478e-8ecc-a7ad29be0cca)

### Output of ./validate.php

```txt
$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.9.1-117-g79cc5c911 (2023-10-23T03:02:17-06:00)
DB Schema | 2023_10_20_075853_cisco_asa_add_default_limits (268)
PHP       | 8.2.11
Python    | 3.8.10
Database  | MySQL 8.0.34-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | 5.8
===========================================

[OK]    Composer Version: 2.6.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No active python wrapper pollers found
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### Anything in the logs that might be useful for us?

```txt
Logs seem irrelevant here.
```

**Comment by BloodyIron** [comment]
I found another area of similar issue:

![image](https://github.com/librenms/librenms/assets/12439391/5d8e33e9-7768-49c7-8c3a-37d5c502a044)

**Comment by BloodyIron** [comment]
Ugh how did I fat-finger that title, how embarrassing >.<

**Comment by BloodyIron** [comment]
@PipoCanaja unsure when I can make the time to get approved for PRs then make good content to contribute. Life is complicated so this is more me putting it out there for "someday" to be corrected, or something like that.

**Comment by PipoCanaja** [comment]
> @PipoCanaja unsure when I can make the time to get approved for PRs then make good content to contribute. Life is complicated so this is more me putting it out there for "someday" to be corrected, or something like that.

I know and I agree, it is the same for all of us: this is exactly how LibreNMS is made, on our free time, or sometimes on work hours, depending how useful the time spent can be for your employer :) If you or anybody in your team/company complains about this, then it is probably right to spend 30 minutes in the CSS to fix it, and another couple of minutes to submit the PR.

**Comment by GonBlank** [comment]
Hello @BloodyIron 

I made PR #16083 that solves this issue.

**Comment by BloodyIron** [comment]
@GonBlank WOOT THANKS! :DDD
