### ISSUE TITLE
web_mouseover = false, not honoured

### ISSUE THREAD

**Issue by BloodyIron** [librenms/librenms#15496]
### The problem

To try and tune load on librenms and the underlying storage, I want "web_mouseover" to be "false", except when I declare it in config.php or "lnms config:set" the setting isn't honoured. I've restarted the apache2 on the instance after setting it, cleared cache, etc, but the hover graphs always show. I even re-read the documentation talking about it several times to see that in-fact I am doing it correctly.

#1592 supposedly should have fixed this, but... maybe this is a regression?

For me the hovering graphs don't have value (my use-case), so turning them off isn't really taking away from me.

### Output of ./validate.php

```txt
$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.9.1-117-g79cc5c911 (2023-10-23T03:02:17-06:00)
DB Schema | 2023_10_20_075853_cisco_asa_add_default_limits (268)
PHP       | 8.2.11
Python    | 3.8.10
Database  | MySQL 8.0.34-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | 5.8
===========================================

[OK]    Composer Version: 2.6.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No active python wrapper pollers found
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### Anything in the logs that might be useful for us?

```txt
NA
```

**Comment by murrant** [comment]
probably a regression, things are constantly changing inside LibreNMS.

Side note, what a terrible setting name :D

**Comment by murrant** [comment]
Yes, worse ;-)

Can you give a specific example of a location or two where you are seeing a popup you don't expect so I can have somewhere to look?  Thanks.

**Comment by BloodyIron** [comment]
All devices -> mouse over "name" that is the hyperlink for each device, whether it's the hostname, FQDN, or IP, mousing over shows graphs, and AFAIK it should not when this is "false".

**Comment by BloodyIron** [comment]
@murrant so far looks working for me! Thanks as always! :DDD \o/ 😎😎😎
