### ISSUE TITLE
/users and /authlog pages get error 403

### ISSUE THREAD

**Issue by nanedi** [librenms/librenms#15523]
### The problem

`/users` and `/authlog` pages get error 403.

### Output of ./validate.php

```txt
~$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.10.0-6-gf7c9b230d (2023-10-30T07:28:07-07:00)
DB Schema | 2023_10_20_075853_cisco_asa_add_default_limits (268)
PHP       | 8.1.2-1ubuntu2.14
Python    | 3.10.12
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.6.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

**Comment by murrant** [comment]
Your user does not have permissions to access them.

You can create a new admin with `lnms user:add --role=admin`

**Comment by nanedi** [comment]
> Your user does not have permissions to access them.
> 
> You can create a new admin with `lnms user:add --role=admin`

Can I change the role to admin for existing users?

**Comment by murrant** [comment]
Yes, if you are an admin.

**Comment by nanedi** [comment]
@murrant 
Yes, but that page is error 403.
 I have no idea why.

**Comment by murrant** [comment]
admin role likely does not exist in your install for some reason. See: https://community.librenms.org/t/admin-user-roles/22172

**Comment by nanedi** [comment]
@murrant 

Add a new admin account, error 403 is still here.

The same issue. Fixed now. This is the solution.
https://community.librenms.org/t/403-unauthorized-upon-clicking-auth-history-or-manage-users/22207

Thanks
