### ISSUE TITLE
No longer graphing data after recent auto-update

### ISSUE THREAD

**Issue by Incognify** [librenms/librenms#15544]
### The problem

We noticed that LibreNMS is no longer graphing data. We've ran LibreNMS for probably two years now and have never encountered this error, with auto-updates enabled with daily checking. We have dozens of devices that all of a sudden are no longer being monitored or polled for alerting or other critical tasks.

No changes have been made by on our end, with only "Enable updates in ./daily.sh" enabled with the daily update channel selected.

We can only assume that this occurred in a recent update, as the issue occurs in all browsers and platforms.

Additionally, a newly added device was added successfully, without error, but as you can see below no data is being collected.
 
![Screenshot from 2023-11-04 07-12-47](https://github.com/librenms/librenms/assets/75774592/dacd955f-86e4-4988-a323-3bc80c5815f9)

(Other devices don't have the "Data file mempool-hrsstorage-*" errors shown)

All devices can reach LibreNMS and LibreNMS can reach all devices. Via ping and via snmpwalk.

EDIT:
- It would appear that this happened on October 31st (Tuesday) @ 18:00 EST.
- I can still view live port data for previously added devices. Sensor data that displays as text will also appear properly (Fan speed, temps, etc). But no graphing.

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.10.0-46-g5b63f109c (2023-11-02T20:25:56-04:00)
DB Schema | 2023_10_31_080052_ospf_ports_unsigned (272)
PHP       | 8.1.2-1ubuntu2.14
Python    | 3.10.12
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.6.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### Anything in the logs that might be useful for us?

```txt
Nothing at a glance stands out as being particularly useful.
```

**Comment by murrant** [comment]
It sounds like you are no longer polling devices.
1. run the poller with debug mode and check for errors
2. Check logs/librenms.log for errors
3. Check to make sure scheduled polling processes are running.

**Comment by Incognify** [comment]
> It sounds like you are no longer polling devices.
> 
>     1. run the poller with debug mode and check for errors
> 
>     2. Check logs/librenms.log for errors
> 
>     3. Check to make sure scheduled polling processes are running.

Interestingly enough, found that the issue was a Prometheus Datastore which was never actually live or active. Was just used for some experimentation from several weeks ago but never used in full production. I removed it and now all is good for the regular SNMP polling.

Weird. Anyhow, issue resolved!

**Comment by Incognify** [comment]
See above. Issue resolved. Had an older Prometheus Datastore config saved from some time back. (For whatever reason) that was the issue. Once removed, SNMP polling continued as expected. Strange.
