### ISSUE TITLE
Feature Request: Custom Font, Font Color, BG Color, Navbar Color etc.

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#1554]
Been looking at some difference ones, for fun. 
What do people think? :)

http://imgur.com/a/t4i6Y

**Comment by paulgear** [comment]
I'm not a huge fan, but very happy to have it as a configurable option. :-)

**Comment by laf** [comment]
I like, certainly personal opinion and nothing that a config option wouldn't then open up a world of comic sans and custom fonts :)
