### ISSUE TITLE
php validate.php and validate config give 2 different outputs

### ISSUE THREAD

**Issue by ervin09** [librenms/librenms#15570]
### The problem

im checking php validate.php and validate config (from the web) there are 2 different outputs.

php validate.php from the CLI reports no issues. but the validate config from the web reports of an isssue. 

is it possible to unify those 2 outputs? 

### Output of ./validate.php

```txt
php validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.10.0-62-g63eeeb7 (2023-11-08T15:36:09+01:00)
DB Schema | 2023_11_04_125846_packages_increase_name_column_length (273)
PHP       | 8.1.25
Python    | 3.9.18
Database  | MariaDB 10.5.16-MariaDB
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.6.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is functional
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

**Comment by ervin09** [comment]
![Screenshot_1](https://github.com/librenms/librenms/assets/1549892/bbf9aa3d-d33a-4b4c-aa88-13e1af4672b6)

**Comment by ervin09** [comment]
![Screenshot_1](https://github.com/librenms/librenms/assets/1549892/3cc5b2e8-7a15-4ca5-acd6-b766587bb655)

**Comment by ervin09** [comment]
![Screenshot_2](https://github.com/librenms/librenms/assets/1549892/9091a021-1884-4f47-b006-c2523b6f02d3)

**Comment by murrant** [comment]
How are you supposed to validate on the command line if a browser is accessing the site without a secure cookie?
Some validations only work via the web.
