### ISSUE TITLE
Authentication with GET variables no longer works

### ISSUE THREAD

**Issue by zagub59** [librenms/librenms#15582]
### The problem

Hi everyone,

We've been using LibreNMS for several years and really like it.

Until recently, we used to display a dashboard from our digital signage on TV using GET variables to authenticate with an URL like this : 
https://LIBRENMS/overview/?username=USERNAME&password=PASSWORD&dashboard=XX&bare=yes

Sadly, it no longer works at the moment with version version 23.10.0-70-g3768e5944

Any idea what could cause this ?

Thanks for your help!

### Output of ./validate.php

```txt
Configuration Ok
Database Ok
Dependencies Ok
Disk Ok
Distributedpoller Ok
Mail Ok
Php Ok
Poller Ok
Programs Ok
Python Ok
Rrd Ok
Rrdcheck Ok
Scheduler Ok
System Ok
Updates Ok
User Ok
Webserver O
```

**Comment by murrant** [comment]
#15558 

You can enable it, instructions inside PR.

**Comment by zagub59** [comment]
Thank you very much for quick answer, it's working as expected 👍
