### ISSUE TITLE
LM-Sensors temperature graphs spikes and disappears with negative temperatures

### ISSUE THREAD

**Issue by Raspbianuser** [librenms/librenms#15609]
### The problem

I have soldered a temp sensor (DS18B20) to my Raspberry Pi, and a couple of weeks ago the graphs disappeared all the sudden. And I thought it was due to the the latest relasese. But after some testing it was the weather. The RPi stationed up on our loft here in Norway and it's quite cold. Hence I monitor the temperatures. So I moved the sensor on top of a Unifi switch inside a "data rack" and the temperature graphs came back. 

And to be sure, I have this python script that I use to check if there is something wrong with the connection or whatever, and the sensor has been online the whole time, but not able to graph. 

So in conclusion, Librenms can't handle temp graphing going from + Celcius, to - Celcius as far as I can document here.  

https://community.librenms.org/t/ds18b20-temp-sensor-custom-oid-help/22954/7 - Images and further documentation can be seen here. At least at the latest post, disregard the first ones as I thought I had other issues. 

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.11.0-13-g7630983b5 (2023-11-30T18:54:50+01:00)
DB Schema | 2023_11_21_172239_increase_vminfo.vmwvmguestos_column_length (274)
PHP       | 8.2.12
Python    | 3.9.2
Database  | MariaDB 10.5.21-MariaDB-0+deb11u1
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================

[OK]    Composer Version: 2.6.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

**Comment by PipoCanaja** [comment]
Hi @Raspbianuser 
Looks like an unsigned INT issue somewhere. Instead of ` -2147483648 to 2147483647 ` the value is ` 0 to 4,294,967,295 `. You have to check at which step this mismatch occurs.

**Comment by Raspbianuser** [comment]
Thanks for the reply, I have no idea how to check that, sorry. But I can certainly try if you tell me how.

**Comment by Raspbianuser** [comment]
So I went out and bought a third sensor mounted to the third and last RPi I have, and I'm ready for some science!
<img width="1491" alt="Screenshot 2023-12-02 at 21 58 02" src="https://github.com/librenms/librenms/assets/84146171/a5e0c26b-8c05-4680-895b-1d6210db2586">

**Comment by Raspbianuser** [comment]
Got some help over at Reddit and I produced this output from the poller:
**This is the sensor before moving it outside of the rack.**
```
#### Load poller module sensors ####
Module enabled: Global + | OS   | Device   | Manual    
SQL[SELECT `sensor_class` FROM `sensors` WHERE `device_id` = ? GROUP BY `sensor_class` [6] 1.42ms] 
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = ? AND `device_id` = ? ["temperature",6] 1.68ms] 
SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-OUQntea' '-M' '/opt/librenms/mibs' 'udp:HOSTNAME:161' '.1.3.6.1.4.1.2021.13.16.2.1.3.1' '.1.3.6.1.4.1.2021.13.16.2.1.3.2']
.*.4.1.2*.1.3.1 = 26284
.*.4.1.2*.1.3.2 = 1562  
Checking (snmp) temperature temp1... 
Checking (snmp) temperature w1_slave_virtual-0:temp1... 

26.284 C

SQL[UPDATE `sensors` set `sensor_current`=?,`sensor_prev`=?,`lastupdate`=NOW() WHERE `sensor_class` = ? AND `sensor_id` = ? [26.284,32.615,"temperature",50] 3.17ms] 

1.562 C

SQL[UPDATE `sensors` set `sensor_current`=?,`sensor_prev`=?,`lastupdate`=NOW() WHERE `sensor_class` = ? AND `sensor_id` = ? [1.562,2.375,"temperature",178] 2.66ms] 
>> SNMP: [1/0.84s] MySQL: [4/0.09s]   
>> Runtime for poller module 'sensors': 0.8565 seconds with 83888 bytes  
#### Unload poller module sensors ####
```

After putting outside the rack:
```
#### Load poller module sensors ####
Module enabled: Global + | OS   | Device   | Manual    
SQL[SELECT `sensor_class` FROM `sensors` WHERE `device_id` = ? GROUP BY `sensor_class` [6] 1.25ms] 
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = ? AND `device_id` = ? ["temperature",6] 1.51ms] 
SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-OUQntea' '-M' '/opt/librenms/mibs' 'udp:HOSTNAME:161' '.1.3.6.1.4.1.2021.13.16.2.1.3.1' '.1.3.6.1.4.1.2021.13.16.2.1.3.2']
.*.4.1.2*.1.3.1 = 29206
.*.4.1.2*.1.3.2 = 4294966609  
Checking (snmp) temperature temp1... 
Checking (snmp) temperature w1_slave_virtual-0:temp1... 

29.206 C

SQL[UPDATE `sensors` set `sensor_current`=?,`sensor_prev`=?,`lastupdate`=NOW() WHERE `sensor_class` = ? AND `sensor_id` = ? [29.206,31.154,"temperature",50] 2.47ms] 

4294966.609 C

SQL[UPDATE `sensors` set `sensor_current`=?,`sensor_prev`=?,`lastupdate`=NOW() WHERE `sensor_class` = ? AND `sensor_id` = ? [4294966.609,4294966.984,"temperature",178] 2.3ms] 
>> SNMP: [1/0.84s] MySQL: [4/0.08s]   
>> Runtime for poller module 'sensors': 0.8604 seconds with 83936 bytes  
#### Unload poller module sensors ####
```

**Comment by PipoCanaja** [comment]
The data is wrong from the SNMP polling, so the best place for the fix would be on the device itself. LibreNMS is indeed displaying the value that is received.

**Comment by Raspbianuser** [comment]
Looking [this](http://www.satsignal.eu/raspberry-pi/monitoring.html#ambient) and [this](https://djsattempt.blogspot.com/2013/03/raspberry-pi-and-snmp-polling-using.html?m=1) from [/u/djamp42](https://www.reddit.com/user/djamp42) I have done some testing, but so far without any luck. 
Here is the /home/pi/read-ds2.pl

`$sensor_temp = "";
$attempts = 0;
$temperature = 0;

while ($sensor_temp !~ /YES/g && $attempts < 5)
{
        $sensor_temp = `cat /sys/bus/w1/devices/28-3cb9e38162b8/w1_slave 2>&1`;
        if ($sensor_temp =~ /No such file or directory/)
        {
                last;
        }
        elsif ($sensor_temp !~ /NO/g)
        {
                $sensor_temp =~ s/.*t=//i;
                $temperature = int ((9*$'/5) + 32000);
        }
        $attempts++;
}
print "$temperature\n";`

This script are suppose to work with 

`#!/bin/bash
if [ "$1" = "-g" ]
then
echo .1.3.6.1.2.1.25.1.10
echo gauge
perl /home/pi/read-ds2.pl
fi
exit 0   `

And this is added as: 
`pass .1.3.6.1.2.1.25.1.10 /bin/sh /usr/local/bin/snmp-ds2-temp
pass .1.3.6.1.2.1.25.1.9 /bin/sh /usr/local/bin/snmp-ds2-temp`

In /etc/snmp/snmpd.conf and gives me:

`pi@librenms:~ $ snmpget -v2c -c community localhost .1.3.6.1.2.1.25.1.10
iso.3.6.1.2.1.25.1.10 = Gauge32: 26150
pi@librenms:~ $ snmpget -v2c -c community localhost .1.3.6.1.2.1.25.1.9
iso.3.6.1.2.1.25.1.10 = Gauge32: 26150`

So that tells me nothing, but according to my python script, them temp should read:

`pi@librenms:~ $ python tempsensor.py 
05/12/23@09:55:30 - -3.2 C`

And for referance, here is the python-script:

`#!/usr/bin/env python

import os
import glob
import time
import datetime

def read_temp(decimals = 1, sleeptime = 3):

    """Reads the temperature from a 1-wire device"""

    device = glob.glob("/sys/bus/w1/devices/" + "28*")[0] + "/w1_slave"
    while True:
        try:
            timepoint = datetime.datetime.now()
            with open(device, "r") as f:
                lines = f.readlines()
            while lines[0].strip()[-3:] != "YES":
                time.sleep(0.2)
                lines = read_temp_raw()
            timepassed = (datetime.datetime.now() - timepoint).total_seconds()
            equals_pos = lines[1].find("t=")
            if equals_pos != -1:
                temp_string = lines[1][equals_pos+2:]
                temp = round(float(temp_string) / 1000.0, decimals)
                print(time.strftime("%d/%m/%y@%H:%M:%S - ")+str(temp)+" C")
                time.sleep(sleeptime-timepassed)
                timepoint = datetime.datetime.now()
        except KeyboardInterrupt:
            break

if __name__ == "__main__":
    read_temp()`

**Comment by PipoCanaja** [comment]
What does the command `/usr/local/bin/snmp-ds2-temp` returns ? I suppose the value is wrong already at this step. If yes, then you need to fix snmp-ds2-temp. 

It is not clear for me what text is retrieved here `cat /sys/bus/w1/devices/28-3cb9e38162b8/w1_slave ` and what conversion should be done to display it right. The python script does not seem to do much conversion.
