### ISSUE TITLE
Aerohive AP230

### ISSUE THREAD

**Issue by macbook8** [librenms/librenms#1562]
When I upgraded Aerohive AP230 to version 6.6r1 LibreNMS the status is down.

**Comment by laf** [comment]
Can you provide the output of ./poller.php -h HOSTNAME -d -r

**Comment by macbook8** [comment]
SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'AH-231' ORDER BY `device_id` ASC]

**Comment by laf** [comment]
Thanks, that should output a lot more than that, if the hostname is AH-231 that is. Can you paste the rest of the output.

**Comment by macbook8** [comment]
LibreNMS 2014.master Poller

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'AH-231' ORDER BY `device_id` ASC] ./poller.php AH-231 2015-08-02 08:41:42 - 0 devices polled in 0.001 secs

MySQL: Cell[0/0s] Row[0/0s] Rows[1/0s] Column[0/0s] Update[0/0s] Insert[0/0s] Delete[0/0s]

**Comment by laf** [comment]
If that is all you get back still either you have the device marked as disabled or the hostname isn't AH-231

**Comment by laf** [comment]
Proposing to close this in the next 48 hours unless more info can be provided.

**Comment by f0o** [comment]
Closing due to lack of informations.

@macbook8 feel free to reopen this issue with the asked informations.
