### ISSUE TITLE
Downtime showing 58 Years on main status page

### ISSUE THREAD

**Issue by nonekdan** [librenms/librenms#15634]
### The problem

I have recently noticed that when I have a device go down, the main device page shows a downtime of 58 years.
![Screenshot 2023-12-08 090519](https://github.com/librenms/librenms/assets/47051093/ffd49edb-08f4-4d4c-ac2f-3f7a268f8b68)

### Output of ./validate.php

```txt
librenms@librenms-monitoring:~$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.11.0-27-g8cf721c32 (2023-12-11T06:14:36-07:00)
DB Schema | 2023_11_21_172239_increase_vminfo.vmwvmguestos_column_length (274)
PHP       | 8.1.9
Python    | 3.10.12
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.6.6
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
librenms@librenms-monitoring:~$
```

### What was the last working version of LibreNMS?

23.11

**Comment by PipoCanaja** [comment]
Hi @nonekdan  
Was this device ever up before ?

**Comment by nonekdan** [comment]
Yeah.. it's unfortunately not just this one..  It is VERY widespread if not all of them.. I haven't tried to do anything to them yet to see if I can clear it up, but it's definitely all over the place in my database and not isolated.

**Comment by nonekdan** [comment]
So here is another example  This.  What's odd is that if I hover over the item in my dashboard widget it shows the correct downtime.  As soon as I click it and pull up the main status page it shows 58 years.
![Dwight CultGoodDowntime](https://github.com/librenms/librenms/assets/47051093/170c74bd-91a4-4ae0-b3fc-dfbf1e358f3d)
![DwightCultBadDwon](https://github.com/librenms/librenms/assets/47051093/e2be6412-00e8-4810-8c47-8c68f243f319)

**Comment by PipoCanaja** [comment]
Is it only on devices that are "ping only" ? I have almost none in my environnements, so that may explain why I did not see many of these 58 years downtime. And would make it easier to track them

**Comment by nonekdan** [comment]
Sorry, I should have clarified.  The first one is a switch that is snmp and icmp and the second one is just ping only.  I was thinking about that too that it's maybe one or the other, but it seems to be everywhere.   But very weirdly I had another netgear that I messed with and I turned off snmp.  I had the status page open and it correctly showed the downtime for at least 5 minutes until I turned it back on.  Do you know where the status page is pulling that from?  Maybe I can look at the tables and see if any data is there?

**Comment by nonekdan** [comment]
Anybody have any ideas on this one?  Is there something I can look at?
Thank you.

**Comment by nonekdan** [comment]
Bueller?

**Comment by nonekdan** [comment]
Sorry for the late reply on this..  This is in fact fixed for us.   
Strangely it came back for us very briefly after it initially seemed to clear.  And I apologize for not staying on top of this.  You guys have been making some recent fixes and updates to Librenms that are incredibly appreciated.    
The map addition took me by pleasant surprise as weathermap was not terribly fun to work with.   I need to look for custom icons, but just wanted to thank anyone who is working on this and Murrant, I know you are putting in some crazy time and again.. appreciated.
My issue here can certainly be closed.
