### ISSUE TITLE
Autodiscovery for hosts

### ISSUE THREAD

**Issue by tahkau** [librenms/librenms#1564]
Hello all,

 I was wondering if someone can point me to the right direction. I install librenms together with its auto discovery configuration, so problem is I can't seem to scan all my host's and automatically add them to librenms. I would have to add them manually, I want to add all host's automatically so I can monitory their traffic usage if this is possible on librenms.

Thanks

**Comment by laf** [comment]
Hi @tahkau,

You need to add at least one device which can then detect others via arp, xDP or bgp. We don't have a way to just scan your network at present.

**Comment by laf** [comment]
Ability to do this has now been merged in.

**Comment by f0o** [comment]
Added with #1577

**Comment by tahkau** [comment]
Thanks where would I go about enabling this feature ?

**Comment by SaaldjorMike** [comment]
@tahkau: See http://docs.librenms.org/Support/Discovery%20Support/ in the section "SNMP Scan" (all the way in the bottom of the page.

**Comment by tahkau** [comment]
Hi I do not see a scan.php in libre install directory, is there a way I can get that script ?

**Comment by paulgear** [comment]
@tahkau You need to update your LibreNMS install to get the update @laf mentioned.
