### ISSUE TITLE
CDP discovery on PBN devices

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#1566]
hi,

if I try to discover an PBN device with CDP it dont works because the SNMP output is little different to cisco implementation.
maybe it is possible to make this PDP called protocol working.

---
librenms@libreNMS:~$ ./discovery.php -h 10.10.100.30 -d -m discovery-protocols
LibreNMS 2014.master Discovery

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
SQL[SELECT revision FROM `dbSchema`] 
SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE '10.10.100.30' ORDER BY device_id DESC] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '123'] 10.10.100.30 123 pbn 
Discovery protocols: CISCO-CDP-MIB: DEBUG: SNMP Auth options =  -v2c -c public
/usr/bin/snmpbulkwalk -v2c -c public -O QUs -M /opt/librenms/mibs -m CISCO-CDP-MIB udp:10.10.100.30:161 cdpCache 2>/dev/null
cdpCacheVersion.3 = PBN(tm) AOCM3948 Software, Version 2.1.0C
Serial: S31060286, System Address: 000B056268E1
Copyright (c) 1995-2013 Pacific Broadband Networks
Compiled: 2014-2-21 10:3:43 by SYS
cdpCacheDeviceId.3 = kx-dre-sw1
cdpCacheDevicePort.3 = GigaEthernet0/1
cdpCachePlatform.3 = PBN AOCM3948 Software, RISC processor
cdpCacheCapabilities.3 = "00 00 00 09 "

 LLDP-MIB: DEBUG: SNMP Auth options =  -v2c -c public
/usr/bin/snmpbulkwalk -v2c -c public -O QUs -M /opt/librenms/mibs -m LLDP-MIB udp:10.10.100.30:161 lldpRemoteSystemsData
lldpRemoteSystemsData = No Such Object available on this agent at this OID

lldpRemoteSystemsData = No Such Object available on this agent at this OID || lldpRemoteSystemsData ||  ||  || 
DEBUG: SNMP Auth options =  -v2c -c public
/usr/bin/snmpbulkwalk -v2c -c public -OQUs  -m BRIDGE-MIB -M /opt/librenms/mibs udp:10.10.100.30:161 dot1dBasePortIfIndex
dot1dBasePortIfIndex.1 = 1
dot1dBasePortIfIndex.2 = 2
dot1dBasePortIfIndex.3 = 3
dot1dBasePortIfIndex.4 = 4
dot1dBasePortIfIndex.5 = 5
dot1dBasePortIfIndex.6 = 6
dot1dBasePortIfIndex.7 = 7
dot1dBasePortIfIndex.8 = 8
dot1dBasePortIfIndex.9 = 9
dot1dBasePortIfIndex.10 = 10
dot1dBasePortIfIndex.11 = 11
dot1dBasePortIfIndex.12 = 12
dot1dBasePortIfIndex.13 = 13
dot1dBasePortIfIndex.14 = 14
dot1dBasePortIfIndex.15 = 15
dot1dBasePortIfIndex.16 = 16
dot1dBasePortIfIndex.17 = 17
dot1dBasePortIfIndex.18 = 18
dot1dBasePortIfIndex.19 = 19
dot1dBasePortIfIndex.20 = 20
dot1dBasePortIfIndex.21 = 21
dot1dBasePortIfIndex.22 = 22
dot1dBasePortIfIndex.23 = 23
dot1dBasePortIfIndex.24 = 24
dot1dBasePortIfIndex.25 = 25
dot1dBasePortIfIndex.26 = 26
dot1dBasePortIfIndex.27 = 27
dot1dBasePortIfIndex.28 = 28
dot1dBasePortIfIndex.29 = 29
dot1dBasePortIfIndex.30 = 30
dot1dBasePortIfIndex.31 = 31
dot1dBasePortIfIndex.32 = 32
dot1dBasePortIfIndex.33 = 33
dot1dBasePortIfIndex.34 = 34
dot1dBasePortIfIndex.35 = 35
dot1dBasePortIfIndex.36 = 36
dot1dBasePortIfIndex.37 = 37
dot1dBasePortIfIndex.38 = 38
dot1dBasePortIfIndex.39 = 39
dot1dBasePortIfIndex.40 = 40
dot1dBasePortIfIndex.41 = 41
dot1dBasePortIfIndex.42 = 42
dot1dBasePortIfIndex.43 = 43
dot1dBasePortIfIndex.44 = 44
dot1dBasePortIfIndex.45 = 45
dot1dBasePortIfIndex.46 = 46
dot1dBasePortIfIndex.47 = 47
dot1dBasePortIfIndex.48 = 48

OSPF Discovery: enabled

SQL[SELECT DISTINCT(`ospfNbrIpAddr`),`device_id` FROM `ospf_nbrs` WHERE `device_id`='123'] discovering 10.10.100.10
ip lookup result: 10.10.100.10

SQL[SELECT COUNT(*) FROM `devices` WHERE `hostname` = '10.10.100.10'] Already got host 10.10.100.10
discovering 10.10.100.22
ip lookup result: 10.10.100.22

SQL[SELECT COUNT(*) FROM `devices` WHERE `hostname` = '10.10.100.22'] Already got host 10.10.100.22
discovering 10.10.100.32
ip lookup result: 10.10.100.32

SQL[SELECT COUNT(*) FROM `devices` WHERE `hostname` = '10.10.100.32'] Already got host 10.10.100.32
discovering 10.10.100.33
ip lookup result: 10.10.100.33

SQL[SELECT COUNT(*) FROM `devices` WHERE `hostname` = '10.10.100.33'] Already got host 10.10.100.33
discovering 10.10.100.34
ip lookup result: 10.10.100.34

SQL[SELECT COUNT(*) FROM `devices` WHERE `hostname` = '10.10.100.34'] Already got host 10.10.100.34

SQL[SELECT * FROM `links` AS L, `ports` AS I WHERE L.local_port_id = I.port_id AND I.device_id = '123'] 

SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='network',`last_discovered_timetaken` ='0.242' WHERE `device_id` = '123'] Discovered in 0.242 seconds

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','10.10.100.30','1438268845.3378','0.248','1')] ./discovery.php 10.10.100.30 2015-07-30 17:07:25 - 1 devices discovered in 0.248 secs
MySQL: Cell[1/0s] Row[6/0s] Rows[2/0s] Column[0/0s] Update[1/0s] Insert[1/0s] Delete[0/0s]
---

In listing we can see one device on Port ge0/3 discovered via PDP
attention, this Output has really new Lines!
---
cdpCacheVersion.3 = PBN(tm) AOCM3948 Software, Version 2.1.0C
Serial: S31060286, System Address: 000B056268E1
Copyright (c) 1995-2013 Pacific Broadband Networks
Compiled: 2014-2-21 10:3:43 by SYS
---

**Comment by laf** [comment]
Hi @vitalisator 

I've just added some debug code to discovery-protocols, https://github.com/librenms/librenms/pull/1590

When that gets merged in if you can re-run:

```bash
 ./discovery.php -h 10.10.100.30 -d -m discovery-protocols
```

And post the output to dpaste.de and link back here that would be great.

**Comment by vitalisator** [comment]
https://dpaste.de/v4pS

**Comment by laf** [comment]
@vitalisator Did you update before running the discovery again? Looks the same as before.

**Comment by vitalisator** [comment]
@laf new try. it was not updated.
https://dpaste.de/XEzt
it seems that the array is empty.

**Comment by laf** [comment]
Thanks, it's a starting point at least :)

**Comment by laf** [comment]
@vitalisator 

I've proposed an update to discovery-protocols.inc.php which I'd hope fixes this for you. Once it's merged, if you can test and let me know that would be great.

**Comment by vitalisator** [comment]
@laf 
here a debug output with changes you made.
https://dpaste.de/oBVd

PS. I'm for next two weeks on holidays, so it maybe than i answer with some delay.

**Comment by laf** [comment]
@vitalisator 

From that debug it looks like it's worked, should show up in the network map now.

Have a great holiday :)

**Comment by vitalisator** [comment]
the map for this device is definitely empty :-( 
hmm.. it looks for me than there only first letters are inserted to SQL:
---
SQL[INSERT INTO `links` (`local_port_id`,`local_device_id`,`protocol`,`remote_hostname`,`remote_device_id`,`remote_port`,`remote_platform`,`remote_version`) VALUES ('3672','123','cdp','P','','P','P','P')] +( 92 inserted )
---
OR is the reason for absent MAP entry the fact that linked entry is a hostname "kx-dre-sw1" but i have entered only IP adress as device name "10.10.100.31"?

maybe it works after my holidays :-)
