### ISSUE TITLE
Wrong Advanced SQL "Override CPU Rule"

### ISSUE THREAD

**Issue by blknight88** [librenms/librenms#15700]
### The problem

Using the example from here: https://docs.librenms.org/Alerting/Rules/#advanced for overall CPU alerting always worked fine. Then after the 23.10.0 update it no longer works. I have updated even to the recent 24.1.0 and it still does not work. 

The only change I have made is setting the query 85 instead of 10.

I have tried every suggestion ChatGPT could give me to try and fix this and posted in the Discord channel and no one responded to my post about it months ago so I figured I'd add an issue report here. 

This is the error it gives me in the web UI:

`Error  in alert rule Processor Usage over 85% (1): SQLSTATE[42000]: Syntax  error or access violation: 1140 Mixing of GROUP columns  (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is  no GROUP BY clause (Connection: mysql, SQL: SELECT  *,AVG(processors.processor_usage) as cpu_avg FROM devices,processors  WHERE (devices.device_id = 51 AND devices.device_id =  processors.device_id) AND (devices.status = 1 &&  (devices.disabled = 0 && devices.ignore = 0)) = 1 HAVING  AVG(processors.processor_usage) > 85)`

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.1.0 (2024-01-07T07:49:52-08:00)
DB Schema | 2023_12_08_184652_mpls_addrtype_fix (276)
PHP       | 8.1.2-1ubuntu2.14
Python    | 3.10.12
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.6.6
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### What was the last working version of LibreNMS?

23.9.0

**Comment by PipoCanaja** [comment]
Hi,
Newer version of Laravel (the framework LibreNMS uses) is using strict mode in mysql. You can replicate this in your CLI (or whatever DB client you use) with this command
`set sql_mode='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,ONLY_FULL_GROUP_BY';`

All SQL queries must now be written correctly, and this one is not. You need to either fix it (and submit a pull request) or wait until somebody fixes the documentation.

**Comment by blknight88** [comment]
Thanks for that information, I am no expert on this, but thanks to that feedback I was able to get ChatGPT to eventually give me a query that worked. However now I see the "processor_usage" is not working in my Alert Template anymore either (it just reports the % with no value), I'm guessing that also must change now. 

Here is the query from ChatGPT that worked, in case it helps anyone else:

`SELECT devices.device_id, devices.status, devices.disabled, devices.ignore, AVG(processors.processor_usage) AS cpu_avg  FROM devices INNER JOIN processors ON devices.device_id = processors.device_id WHERE devices.device_id = ?      AND devices.status = 1      AND devices.disabled = 0      AND devices.ignore = 0  GROUP BY devices.device_id, devices.status, devices.disabled, devices.ignore HAVING AVG(processors.processor_usage) > 85`

**Comment by PipoCanaja** [comment]
@blknight88 
Could you create a pull request with your change ? we can then review and merge it so everybody will get the fix.
Thanx
