### ISSUE TITLE
Dashboard Loses Items with Syslog Configured

### ISSUE THREAD

**Issue by baggar11** [librenms/librenms#1572]
I noticed that once I enable syslog in config.php, the dashboard shows syslog entries which is great, but loses the also helpful alertlog and eventlog sections. See below for an example.

http://puddlehunters.net/librenms-nosyslog.png
http://puddlehunters.net/librenms-syslog.png

Can a config selection of some kind be an option?

**Comment by laf** [comment]
I'd say that we should fix this with the new dashboard. Provides the full flexibility at that stage.

**Comment by paulgear** [comment]
:+1:

**Comment by laf** [comment]
Try the new dashboard, you can customise this without fear it will all of a sudden change:

```php
$config['front_page']       = "pages/front/tiles.php";
```

**Comment by baggar11** [comment]
I added that line to my config.php and got the following;

http://puddlehunters.net/librenms-widget.png

I'm not seeing anyway to add any widgets.

**Comment by f0o** [comment]
@baggar11 good news then? :)
Are we good to close the issue?

**Comment by baggar11** [comment]
Yeah, thanks! You guys rock!
