### ISSUE TITLE
Missing a word in "service page"

### ISSUE THREAD

**Issue by My-Random-Thoughts** [librenms/librenms#15729]
### The problem

https://github.com/librenms/librenms/blob/dd7e03fffc15dc0394e9909c901ddbf7d95ef92f/includes/html/modal/new_service.inc.php#L35C51-L35C51

Currently reads: "Service will modified for the specified Device."
Should read: "Service will be modified for the specified Device."

Strangely, it seems it was put in like that 4 years ago and no one noticed :)

### Output of ./validate.php

```txt
n/a
```

### What was the last working version of LibreNMS?

24.1.0

### Anything in the logs that might be useful for us?

```txt
n/a
```

**Comment by PipoCanaja** [comment]
Hi @My-Random-Thoughts 
Please open a PR with the fix, we'll review and merge it. 
Thanx

**Comment by My-Random-Thoughts** [comment]
Tis done, https://github.com/librenms/librenms/pull/15746
