### ISSUE TITLE
Suggestion: Menubar Change 

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#1575]
A minor change.
Thoughts/ideas?
http://imgur.com/lLrBcuj,jfz6KH1#0
http://imgur.com/lLrBcuj,jfz6KH1#1

**Comment by f0o** [comment]
:+1:

**Comment by f0o** [comment]
Will come in handy in conjunction with the briefly discussed messaging system

**Comment by paulgear** [comment]
:+1: from me too - as we get more features we're going to need to find ways of keeping the menu structure sane.

**Comment by f0o** [comment]
What about this crazy old idea of having a sidebar?

**Comment by laf** [comment]
We need to shrink or look at the navbar before we add another icon. On a number of resolutions the navbar no longer fits and doesn't condense down :(

**Comment by paulgear** [comment]
Is there a way we can sensibly make a sidebar optional?  I really hate them when I'm browsing on a widescreen desktop, but on a narrowscreen phone they make a lot of sense.

**Comment by laf** [comment]
No mention of a sidebar hear!

**Comment by f0o** [comment]
Okok, no Sidebar... But how about a Vertically Aligned Bar snapped to the left edge of the screen? :P

**Comment by laf** [comment]
Ah now I see the side bar. I think to have a toggle between topnav / sidenav would be challenging. 

Probably just need to re-vist the bootstrap code for the navbar to make sure it's 100% right.

**Comment by laf** [comment]
#1624 tackles this a little to create more room.

**Comment by Rosiak** [comment]
Should I proceed with this one?

**Comment by Rosiak** [comment]
bump

**Comment by f0o** [comment]
Yes please :)

**Comment by laf** [comment]
So long as we are shrinking the navbar in some other way, adding another menu entry is going to wrap the navbar more than it already does on some screen resolutions.

**Comment by Rosiak** [comment]
Will PR this ASAP, just need to separate the menus since I ditched the old work.

![screen shot 2015-12-09 at 23 32 22](https://cloud.githubusercontent.com/assets/6378934/11700982/3a697df4-9ecd-11e5-8afe-8cc3c54d82d4.png)
