### ISSUE TITLE
Actual master branch web installer is broken with Debian 12 / Ubuntu 22.04

### ISSUE THREAD

**Issue by dominiaz** [librenms/librenms#15758]
### The problem

I had you use branch 23.8, because actual master branch installer doesn`t work.

There is an error when you will go to: http://librenms.example.com/

### Output of ./validate.php

```txt
none
```

**Comment by ottorei** [comment]
Could you post the steps to reproduce this and possibly the error message?

**Comment by DamLaw** [comment]
same here. followed documentation,  getting

Whoops, looks like something went wrong. Check your librenms.log.

librenms.log shows

PDOException: SQLSTATE[HY000] [1698] Access denied for user 'librenms'@'localhost' in /opt/librenms/vendor/laravel/framework/>
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(65): PDO->__construct()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(45): Illuminate\Database\Connector>
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Conn>
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\Database\>
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1319): call_user_func()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1355): Illuminate\Database\Connection->getPd>
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->getRea>
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\Database\Connection->getPdo>
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(809): Illuminate\Database\Connection->Illumi>
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\Database\Connection->runQu>
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(424): Illuminate\Database\Connection->run()
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2752): Illuminate\Database\Connection->s>
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2740): Illuminate\Database\Query\Builder>
#14 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3294): Illuminate\Database\Query\Builder>
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2741): Illuminate\Database\Query\Builder>
#16 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(737): Illuminate\Database\Query\Build>
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(721): Illuminate\Database\Eloquent\Bu>
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(333): Illuminate\Database\Eloqu>
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(566): Illuminate\Database\Eloquent\Bu>
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(598): Illuminate\Database\Eloquent\Bu>
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\>
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2334): Illuminate\Database\Eloquent\Mod>
#23 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2346): Illuminate\Database\Eloquent\Mod>
#24 /opt/librenms/LibreNMS/Config.php(262): Illuminate\Database\Eloquent\Model::__callStatic()
#25 /opt/librenms/LibreNMS/Config.php(460): LibreNMS\Config::persist()
#26 /opt/librenms/LibreNMS/Config.php(61): LibreNMS\Config::processConfig()
#27 /opt/librenms/app/Providers/ConfigServiceProvider.php(27): LibreNMS\Config::load()
#28 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Providers\ConfigServiceProvider->
#29 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminat>
#30 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfC>
#31 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::ca>
#32 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::cal>
#33 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1030): Illuminate\Container\Container->c>
#34 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1011): Illuminate\Foundation\Application>
#35 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#36 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1012): array_walk()
#37 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\A>
#38 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(263): Illuminate\Foundation\Bootstrap\Bo>
#39 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(447): Illuminate\Foundation\Applicati>
#40 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(199): Illuminate\Foundation\Console\K>
#41 /opt/librenms/app/Console/Kernel.php(66): Illuminate\Foundation\Console\Kernel->handle()
#42 /opt/librenms/artisan(37): App\Console\Kernel->handle()
#43 {main}

Next Illuminate\Database\QueryException: SQLSTATE[HY000] [1698] Access denied for user 'librenms'@'localhost' (Connection: my>
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\Database\Connection->runQue>
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(424): Illuminate\Database\Connection->run()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2752): Illuminate\Database\Connection->se>
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2740): Illuminate\Database\Query\Builder->
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3294): Illuminate\Database\Query\Builder->
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2741): Illuminate\Database\Query\Builder->
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(737): Illuminate\Database\Query\Builde>
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(721): Illuminate\Database\Eloquent\Bui>
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(333): Illuminate\Database\Eloque>
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(566): Illuminate\Database\Eloquent\Bui>
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(598): Illuminate\Database\Eloquent\Bu>
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\>
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2334): Illuminate\Database\Eloquent\Mod>
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2346): Illuminate\Database\Eloquent\Mod>
#14 /opt/librenms/LibreNMS/Config.php(262): Illuminate\Database\Eloquent\Model::__callStatic()
#15 /opt/librenms/LibreNMS/Config.php(460): LibreNMS\Config::persist()
#16 /opt/librenms/LibreNMS/Config.php(61): LibreNMS\Config::processConfig()
#17 /opt/librenms/app/Providers/ConfigServiceProvider.php(27): LibreNMS\Config::load()
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Providers\ConfigServiceProvider->
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminat>
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfC>
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::ca>
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::cal>
#23 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1030): Illuminate\Container\Container->c>
#24 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1011): Illuminate\Foundation\Application>
#25 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#26 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1012): array_walk()
#27 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\A>
#28 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(263): Illuminate\Foundation\Bootstrap\Bo>
#29 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(447): Illuminate\Foundation\Applicati>
#30 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(199): Illuminate\Foundation\Console\K>
#31 /opt/librenms/app/Console/Kernel.php(66): Illuminate\Foundation\Console\Kernel->handle()
#32 /opt/librenms/artisan(37): App\Console\Kernel->handle()
#33 {main}
PDOException: SQLSTATE[HY000] [1698] Access denied for user 'librenms'@'localhost' in /opt/librenms/vendor/laravel/framework/>
