### ISSUE TITLE
Graph not visible in Wireless tab

### ISSUE THREAD

**Issue by radokristof** [librenms/librenms#15761]
### The problem

On the wireless tab, the graphs shows an error. All other graphs from the device is drawn perfectly.
This seems to be an issue with LibreNMS as multiple vendor devices has the same issue (MikroTik and Unifi tested).

The error message is not very visible:

<img width="1895" alt="image" src="https://github.com/librenms/librenms/assets/36210568/ac4552e8-db53-458b-80c8-a3472a22f391">

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.11.0 (2023-11-25T20:17:34+01:00)
DB Schema | 2023_11_04_125846_packages_increase_name_column_length (273)
PHP       | 8.1.22
Python    | 3.10.13
Database  | MariaDB 10.5.23-MariaDB-1:10.5.23+maria~ubu2004
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Installed from the official Docker image; no Composer required
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No python wrapper pollers found
[OK]    Redis is unavailable
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Updates are managed through the official Docker image
```

**Comment by PipoCanaja** [comment]
Hi @radokristof 
Could you please go in the community forums to troubleshoot this issue first ? If the issue is in the code, then you'll file an issue. 

https://community.librenms.org

Thanx

**Comment by radokristof** [comment]
@PipoCanaja Ok, thank you, I have created it. For future reference: https://community.librenms.org/t/graph-not-visible-in-wireless-tab/23394

**Comment by radokristof** [comment]
@PipoCanaja unfortunately no one answered there
