### ISSUE TITLE
LDAP with Active Directory

### ISSUE THREAD

**Issue by nessenj** [librenms/librenms#1576]
In our environment we use Active Directory to authenticate our users, Has anyone been successful in tweaking the LDAP settings with LibreNMS to get this working?

Thanks.

**Comment by paulgear** [comment]
I haven't done this, but it should be possible; perhaps by using clues from another Free Software project that does it we'll be able to work it out.

**Comment by laf** [comment]
@nessenj 

If you need any assistance on this feel free to re-open this issue.
