### ISSUE TITLE
Daily update fail - dependecy problem  with  php 8.3.2

### ISSUE THREAD

**Issue by wr4eng** [librenms/librenms#15838]
### The problem

We just attempted to update your install but failed. The information below
should help you fix this.

> LibreNMS\ComposerHelper::preInstall
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run
composer update.

  Problem 1
    - ezyang/htmlpurifier is locked to version v4.16.0 and an update of this
package was not requested.
    - ezyang/htmlpurifier v4.16.0 requires php ~5.6.0 || ~7.0.0 || ~7.1.0 ||
~7.2.0 || ~7.3.0 || ~7.4.0 || ~8.0.0 || ~8.1.0 || ~8.2.0 -> your php version
(8.3.2) does not satisfy that requirement.
  Problem 2
    - nette/schema is locked to version v1.2.3 and an update of this package
was not requested.
    - nette/schema v1.2.3 requires php >=7.1 <8.3 -> your php version
(8.3.2) does not satisfy that requirement.
  Problem 3
    - nette/utils is locked to version v4.0.0 and an update of this package
was not requested.
    - nette/utils v4.0.0 requires php >=8.0 <8.3 -> your php version (8.3.2)
does not satisfy that requirement.
  Problem 4
    - ezyang/htmlpurifier v4.16.0 requires php ~5.6.0 || ~7.0.0 || ~7.1.0 ||
~7.2.0 || ~7.3.0 || ~7.4.0 || ~8.0.0 || ~8.1.0 || ~8.2.0 -> your php version
(8.3.2) does not satisfy that requirement.
    - mews/purifier 3.4.0 requires ezyang/htmlpurifier ^4.16.0 ->
satisfiable by ezyang/htmlpurifier[v4.16.0].
    - mews/purifier is locked to version 3.4.0 and an update of this package
was not requested.

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.1.0 (2024-01-07T22:49:52+07:00)
DB Schema | 2023_12_15_105529_access_points_nummonbssid_integer (276)
PHP       | 8.3.2-1+0~20240120.16+debian11~1.gbpb43448
Python    | 3.9.2
Database  | MariaDB 10.5.23-MariaDB-0+deb11u1
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================

[OK]    Composer Version: 2.7.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

**Comment by murrant** [comment]
It looks like you are on an old version of LibreNMS, closing.
