### ISSUE TITLE
Docker Application removed, but status still OK

### ISSUE THREAD

**Issue by Drakon74** [librenms/librenms#15858]
### The problem

I had Docker containers running on one of my servers and had the Docker Application activated via SNMP Extend. This worked all good and well.

However all docker containers were now removed and the docker service is still running, but without any containers. Along with that i also commented out the SNMP Extend command and LibreNMS correctly disabled the Docker Application on next discovery.

However, i have a alert rule, which checks the following:

`applications.app_type = "docker" AND applications.app_state = "OK" AND application_metrics.metric = "total_running" AND application_metrics.value = 0`

The meaning behind this is, to detect an empty running docker service. However now the rule gets triggered, since there are no docker containers anymore... and despite the docker application being completely disabled, which i hoped to catch by checking the app state.

I checked the database and the status in there is still "OK" but also the column "deleted_at" has the correct timestamp when the application was disabled by the discovery process.

I assume this is a bug, since the Docker Application can't / shouldn't be "OK" when there is literally no output coming back and the application is disabled too. Or is this eventually being cleaned up? I waited 2 days to see if that might be the case, but nothing happened.

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.2.0 (2024-02-27T19:54:10+01:00)
DB Schema | 2024_02_07_151845_custom_map_additions (290)
PHP       | 8.1.2-1ubuntu2.14
Python    | 3.10.12
Database  | MariaDB 10.6.16-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.7.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

**Comment by murrant** [comment]
Your alert rule needs to check if they are deleted.
