### ISSUE TITLE
Custom Map Editor - Label Field is not pulling the correct data on Edge lines.

### ISSUE THREAD

**Issue by monteroman** [librenms/librenms#15867]
### The problem

There appears to be an issue when you are making edits with Edges (lines) between 2 devices. 

1. When you create a new edge, the label field is blank (expected).  You add a label to it and save it.

![image](https://github.com/librenms/librenms/assets/5451042/fd9eae35-3ecb-4e32-9ef4-1a793ee8d4e1)

2. You create a 2nd edge, the Label field has the information from the previous edge. You change it and save.

3. You go back to the 1st edge and edit it. It is showing the label from the 2nd edge. If you save it, it will overwrite what you initially set it to.

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.2.0-3-g165af7541 (2024-02-29T18:29:53-05:00)
DB Schema | 2024_02_07_151845_custom_map_additions (290)
PHP       | 8.1.2-1ubuntu2.14
Python    | 3.10.12
Database  | MariaDB 10.6.16-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.7.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

**Comment by monteroman** [comment]
This is my first time using this Map Editor so I don't know if this was working before and just isn't now or if it's been broken all along.

**Comment by eskyuu** [comment]
This is new functionality, so thanks for reporting the bug.  It should be a relatively simple fix.  I'll look at it soon.

**Comment by eskyuu** [comment]
I've just create the following pull request which fixes the issue in my testing:
https://github.com/librenms/librenms/pull/15875

**Comment by monteroman** [comment]
Awesome! Thank you!
