### ISSUE TITLE
Custom Maps: Style - Device Image -  does not become inactive

### ISSUE THREAD

**Issue by santiag0z** [librenms/librenms#15888]
### The problem

In Custom Maps, when selecting the Device Image option, the icon does not appear as DOWN, unlike icons for other options such as Device Image (Circular).

Example with down device

Device Image (Circular) - OK!
![image](https://github.com/librenms/librenms/assets/34222550/b672df91-d5ac-4c7d-9410-9bb6b4c2a842)

Device Image - Bug!
![image](https://github.com/librenms/librenms/assets/34222550/e6ce07a6-258e-46c4-ad8e-7c7d7315bbe7)

### Output of ./validate.php

```txt
librenms@librenms:~$ ./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.2.0 (2024-02-27T15:54:10-03:00)
DB Schema | 2024_02_07_151845_custom_map_additions (290)
PHP       | 8.1.16
Python    | 3.8.10
Database  | MariaDB 10.3.39-MariaDB-0ubuntu0.20.04.2
RRDTool   | 1.7.2
SNMP      | 5.8
===========================================

[OK]    Composer Version: 2.7.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
librenms@librenms:~$
```

**Comment by eskyuu** [comment]
Unfortunately, images don't have the option to change colour.  A change has been pushed recently to change the text colour when a device is offline, which is the best we can do.  I am closing this issue given that I believe it has been addressed.  Please re-open with additional comments if you disagree.
