### ISSUE TITLE
Synology DS214se wrong operating system version 

### ISSUE THREAD

**Issue by macbook8** [librenms/librenms#1589]
Hi,

LibreNMS is showing wrong Operating System version on Synology DS214se 

Wrong Operating System: Synology DSM 3.2.40  
Correct Operating System: Synology DSM 5.2-5592 Update 2

Thanks & regards,

**Comment by laf** [comment]
Hi @macbook8 

Please post the edited output for:

./poller.php -h HOSTNAME -d -r -m system,os

Where HOSTNAME = the devices hostname or ID.

**Comment by macbook8** [comment]
LibreNMS 2014.master Poller

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE '                                                                                                 NAS-17' ORDER BY `device_id` ASC]
SQL[SELECT * FROM `devices` WHERE `device_id` = '6']
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '6'] nas-17 6 dsm (unix)

SQL[INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,                                                                                                 `timestamp`)  VALUES ('3','3','0','0.24','0.30','0.28','6',NOW())] DEBUG: SNMP A                                                                                                 uth options =  -v2c -c xxxxx
/usr/bin/snmpget -v2c -c xxxxx -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:nas-                                                                                                 17:161 sysObjectID.0
SNMPv2-SMI::enterprises.8072.3.2.10

DEBUG: SNMP Auth options =  -v2c -c xxxxx
/usr/bin/snmpget -v2c -c xxxxx -OQUs -m SNMPv2-MIB -M /opt/librenms/mibs udp:nas                                                                                                 -17:161 sysUpTime.0 sysLocation.0 sysContact.0 sysName.0
sysUpTime.0 = 0:1:11:26.94
sysLocation.0 = 
sysContact.0 = 
sysName.0 = NAS-17

DEBUG: SNMP Auth options =  -v2c -c xxxxx
/usr/bin/snmpget -v2c -c xxxxx -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:nas-                                                                                                 17:161 sysDescr.0
Linux Xxxxx-NAS17 3.2.40 #5592 Wed Jul 29 14:39:20 CST 2015 armv7l

DEBUG: SNMP Auth options =  -v2c -c xxxxx
/usr/bin/snmpget -v2c -c xxxxx -Oqvn -m SNMPv2-MIB -M /opt/librenms/mibs udp:nas                                                                                                 -17:161 sysObjectID.0
.1.3.6.1.4.1.8072.3.2.10

DEBUG: SNMP Auth options =  -v2c -c xxxxx
/usr/bin/snmpget -v2c -c xxxxx -OUqv -m SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs                                                                                                  udp:nas-17:161 snmpEngineTime.0
4286

DEBUG: SNMP Auth options =  -v2c -c xxxxx
/usr/bin/snmpget -v2c -c xxxxx -Oqv -m HOST-RESOURCES-MIB -M /opt/librenms/mibs                                                                                                  udp:nas-17:161 hrSystemUptime.0
0:1:12:37.90

Using hrSystemUptime (0:1:12:37.90)
[RRD Disabled]RRD[update /opt/librenms/rrd/nas-17/uptime.rrd N:4357] Uptime: 1h                                                                                                  12m 37s
DEBUG: SNMP Auth options =  -v2c -c 
/usr/bin/snmpget -v2c -c xxxxx -Osqnv -M /opt/librenms/mibs udp:nas-17:161 hrSys                                                                                                 temInitialLoadParameters.0
hrSystemInitialLoadParameters.0: Unknown Object Identifier (Sub-id not found: (t                                                                                                 op) -> hrSystemInitialLoadParameters)


Hardware:  Version:  Features:  Serial:

SQL[SELECT `graph` FROM `device_graphs` WHERE `device_id` = '6']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'netstat_i                                                                                                 p']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'netstat_i                                                                                                 p_frag']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'netstat_t                                                                                                 cp']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'netstat_u                                                                                                 dp']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'netstat_i                                                                                                 cmp']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'netstat_i                                                                                                 cmp_info']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'netstat_s                                                                                                 nmp']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'netstat_s                                                                                                 nmp_pkt']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'hr_proces                                                                                                 ses']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'hr_users'                                                                                                 ]
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ucd_cpu']                                                                                                 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ucd_swap_                                                                                                 io']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ucd_io']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ucd_conte                                                                                                 xts']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ucd_inter                                                                                                 rupts']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ucd_memor                                                                                                 y']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ucd_load'                                                                                                 ]
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ipsystems                                                                                                 tats_ipv4']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ipsystems                                                                                                 tats_ipv4_frag']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ipsystems                                                                                                 tats_ipv6']
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ipsystems                                                                                                 tats_ipv6_frag'] uptime [RRD Disabled]RRD[update /opt/librenms/rrd/nas-17/poller                                                                                                 -perf.rrd N:0.313] [RRD Disabled]RRD[update /opt/librenms/rrd/nas-17/ping-perf.r                                                                                                 rd N:0.28] Polled in 0.313 seconds

SQL[UPDATE `devices` set `uptime` ='4357',`last_polled` =NOW(),`last_polled_time                                                                                                 taken` ='0.313',`last_ping` =NOW(),`last_ping_timetaken` ='0.28' WHERE `device_i                                                                                                 d` = '6'] UPDATED!

SQL[SELECT * FROM device_groups]
SQL[SELECT DISTINCT(alert_schedule.schedule_id) FROM alert_schedule LEFT JOIN al                                                                                                 ert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_i                                                                                                 d WHERE ( alert_schedule_items.target = '6' ) && NOW() BETWEEN alert_schedule.st                                                                                                 art AND alert_schedule.end LIMIT 1]
SQL[SELECT * FROM device_groups]
SQL[SELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=                                                                                                 alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 |                                                                                                 | alert_rules.device_id = '6' ) || alert_map.target = '6'  )]

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`polle                                                                                                 r`)  VALUES ('poll','NAS-17','1438534511.9342','0.317','1','ubuntu-librenms\n')]                                                                                                  ./poller.php NAS-17 2015-08-02 09:55:12 - 1 devices polled in 0.317 secs

MySQL: Cell[1/0s] Row[2/0s] Rows[4/0s] Column[0/0s] Update[1/0s] Insert[2/0.01s]                                                                                                  Delete[0/0s]
root@ubuntu-librenms:/opt/librenms#

**Comment by laf** [comment]
Can you run this please @macbook8 

```bash
snmpget -v2c -c xxxxx -Osqnv -M /opt/librenms/mibs udp:nas-17:161 -m SYNOLOGY-SYSTEM-MIB version
```

Replace xxxx with your community.

**Comment by Calvario** [comment]
Hello laf,

I hope that can help.

snmpget -v2c -c XXXX -Osqnv -M /opt/librenms/mibs udp:XXX:161 -m SYNOLOGY-SYSTEM-MIB version
return : No Such Instance currently exists at this OID

snmpwalk -v2c -c XXXX -Osqnv -M /opt/librenms/mibs udp:XXX:161 -m SYNOLOGY-SYSTEM-MIB version
return : "DSM 5.2-5592"

snmpget -v2c -c XXXX -Osqnv -M /opt/librenms/mibs udp:XXX:161 .1.3.6.1.4.1.6574.1.5.3
return : No Such Instance currently exists at this OID

snmpwalk -v2c -c XXXX -Osqnv -M /opt/librenms/mibs udp:XXX:161 .1.3.6.1.4.1.6574.1.5.3
return : "DSM 5.2-5592"
