### ISSUE TITLE
Wrong total clients on wireless devices.

### ISSUE THREAD

**Issue by def-bs** [librenms/librenms#15908]
### The problem

Dear librenms community,

On wireless devices (Access point) the total clients values is 0 but in reality there are more clients connected.
You can see this issue on the following image:
![image](https://github.com/librenms/librenms/assets/31916347/1a7fac96-735c-4b4e-a28d-904241ad3f50)

Could you please provide guidance to solve this issue?
Thank you.

### Output of ./validate.php

```txt
/opt/librenms/validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.2.0-32-gec174e7f9 (2024-03-24T19:02:11+01:00)
DB Schema | 2024_02_07_151845_custom_map_additions (290)
PHP       | 8.3.4
Python    | 3.11.2
Database  | MariaDB 10.11.6-MariaDB-0+deb12u1
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Composer Version: 2.7.2
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### What was the last working version of LibreNMS?

24.2.0-32

**Comment by PipoCanaja** [comment]
Seems that you are right. But without any details, we cannot help you. 

We need details on the device (vendor, OS recognised in LibreNMS at least).

**Comment by murrant** [comment]
No information provided, closing.
