### ISSUE TITLE
Suggestion: Device Reports

### ISSUE THREAD

**Issue by brillormen** [librenms/librenms#1591]
Would be great if you could create "complete"  device reports from LibreNMS that includes the following in a CSV or PDF.

- Name on device
- Brand and model on device
- Software on device
- If VLAN is tagged or untagged on interfaces
- IP-interface
- SFP in which ports
- Routing-table
- Connected devices with LLDP

I guess all this info is in the database already.

**Comment by laf** [comment]
Hi @brillormen 
If you can add this info to https://github.com/librenms/librenms/issues/1409 and close this down.

We will tackle this within the generic reporting capabilities :)
