### ISSUE TITLE
Devices page doesn't honour: $config['web_mouseover'] = false;

### ISSUE THREAD

**Issue by adaniels21487** [librenms/librenms#1592]
Hi Team,
If I navigate to: Devices -> All Devices -> *anything* (html/pages/devices.inc.php)
and go to any of the graph links in the header bar, they don't honour the configuration setting: $config['web_mouseover'] = false;

Is this desired behaviour or a bug?

Thanks,
Aaron

**Comment by laf** [comment]
Hi @adaniels21487 

Do you mean hovering over the hostname? If so it works for me, If I set:

```php
$config['web_mouseover'] = false;
```

It doesn't show a popover. You need to make sure false isn't wrapped in quotes.

**Comment by adaniels21487** [comment]
@laf I think you might be looking at the 'lists' pages which do work fine.
I am referring to the 'graphs' pages where a mouseover gives you a zoomed graph with the legend,
I will have a PR that addresses this shortly.

**Comment by laf** [comment]
Cool, thanks @adaniels21487
