### ISSUE TITLE
Perform Schema-Updates with daily.sh

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#1595]
Instead of using `discovery.php`, let's execute all schema-updates within daily.sh after git pull and before any other operations.

I'll submit a PR

**Comment by laf** [comment]
Be mindful that it's done in discovery to catch those who might just run git pull and not run the updated schema. I'd suggest as a safe guard it's left in discovery.

Doesn't daily.sh run git pull  + perform schema update already?

**Comment by f0o** [comment]
It didnt for me on the demo :(

**Comment by f0o** [comment]
False alarm
