### ISSUE TITLE
Text alignment in legends on port page

### ISSUE THREAD

**Issue by SaaldjorMike** [librenms/librenms#1596]
Notice the graphs for "Interface Non Unicast" and "Interface Errors". Both looks fine when clicking on them, it seems to be just on this port overview page.

Example of the page: /device/device=42/tab=port/port=42/
Screenshot: https://i.imgur.com/v4kgq0A.png

**Comment by SaaldjorMike** [comment]
With the most recent merge we're closer, but not quite there yet :-)
https://i.imgur.com/ixYF8Ni.png

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by SaaldjorMike** [comment]
Looks like this was fixed. Closing.
