### ISSUE TITLE
Output of adding Device by API doenst hide passwords

### ISSUE THREAD

**Issue by tomhouweling1987** [librenms/librenms#15970]
### The problem

When adding the device with the api with snmp3 settings authpass and cryptopass we are using secrets to hide it. But in the output they are plain text. Please hide them in the output or hash them.

Or only let me know that the device is succesfully added.

### Output of ./validate.php

```txt
-
```

### What was the last working version of LibreNMS?

24.3.0

### Anything in the logs that might be useful for us?

```txt
{status=ok, devices=[{hostname=HOSTNAME, authlevel=authPriv, authname=SNMPUser, authpass=PASSWORD, authalgo=SHA, cryptopass=PASSWORD, cryptoalgo=AES, snmpver=v3, port=161, transport=udp, poller_group=0, os=linux, status_reason=, sysName=HOSTNAME, port_association_mode=1, community=null, sysDescr=Linux HOSTNAME 5.15.0-105-generic #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024 x86_64, sysObjectID=.1.3.6.1.4.1.8072.3.2.10, device_id=341}], message=Device HOSTNAME (341) has been added successfully, count=1}
```

**Comment by murrant** [comment]
It is the job of the API consumer to conceal credentials.

**Comment by tomhouweling1987** [comment]
@murrant i get the idea of concealing when you do the api call. But I don’t expected to get an output from de api server back with the given authpass and  cryptopass.

**Comment by murrant** [comment]
@tomhouweling1987 doing an API call doesn't output anything to the screen. it returns an HTTP response.  Whatever you are doing to call the API is what outputs it to the screen.  If we were to remove it, they would be removed from all APIs and API would not be able to fetch the data.

**Comment by tomhouweling1987** [comment]
Hey @murrant, i think i didnt make it clear anough, its not the output of the api call but the response. As you can see in my issue i get the  authpass and the cryptopass back in clear text. When i do the api call im using secrets to hide those. 

So in the '`return api_success([$device->attributesToArray()], 'devices', $message);`'  call, the information of the device is in the response, also the authpass and cryptopass. In my opinion returning the $message should be enough.

**Comment by murrant** [comment]
When you get the response from the API, only check the response code is 200 then. No need to do anything with the response content.
