### ISSUE TITLE
daily.sh better output

### ISSUE THREAD

**Issue by ervin09** [librenms/librenms#16014]
### The problem

hi guys, 

is it possible to have a better output for the daily.sh ?
in my case i've switched the frequency of the updates to monthly.  

The following is the output

./daily.sh
Fetching new release information                   OK
Between releases, waiting for newer release
Updating Composer packages                          OK
Updated from unset to                                     OK
Updating SQL-Schema                                     OK
Updating submodules                                      OK
Cleaning up DB                                                 OK
Fetching notifications                                       OK
Caching PeeringDB data                                  OK

the lines that would make sense to be formatted differently are these :
Between releases, waiting for newer release    (OKAY, NOT OKAY, display the current release maybe)
Updated from unset to                                     OK     (uneset to what???, from what???)

### Output of ./validate.php

```txt
$ php validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.4.1-11-g443bfdb (2024-04-26T14:48:03+02:00)
DB Schema | 2024_04_22_161711_custom_maps_add_group (292)
PHP       | 8.1.28
Python    | 3.9.18
Database  | MariaDB 10.11.6-MariaDB
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.7.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is functional
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

**Comment by murrant** [comment]
This is a feature request.  PRs welcome :)
