### ISSUE TITLE
Missing RRD files - Force Recreate Down/Disabled ports

### ISSUE THREAD

**Issue by kiwilad-nz** [librenms/librenms#16013]
### The problem

I'm running into an issue on a lot of monitored hosts where I believe RRD files were accidentally deleted by means of testing  during issues with unexpected problems arising trying to integrate rrdcached which have since been fixed.

Long story short, RRD files were deleted for ports. Active/Up ports I believe aren't exhibiting this issue and are recreated if missing. However, down and disabled ports that had RRD files generated when 1st added that no longer exists won't get regenerated and really makes it a nuisance when viewing the graphs as it shows errors for every RRD graph that is missing.

The error that makes me believe it is this is this:
eth1118400 skipped because port is still down since last polling.

Is there a way to force create RRD files for ports that are down/disabled across all hosts or at least by specifying hosts?

I've tried different methods but it won't create the missing RRD files:
./poller.php -h OBFUSCATED-HOSTNAME -d -v
lnms device:poll OBFUSCATED-HOSTNAME -m ports

I can resolve the issue by either readding the device so that the down ports are also generated upon being added for the 1st time, otherwise I can disable polling on the ports which also resolves the gui from reporting midding RRD files. Either method however is not preferred as I want to retain all other historical data and also want to monitor all ports incase they are later used or recover.

![327714678-4b1edd7f-e168-4c35-bb99-8d1564c7c8fa](https://github.com/librenms/librenms/assets/50952231/b8a301bf-1d98-4834-a202-71d9fbcbcab8)

### Output of ./validate.php

```txt
/opt/librenms $ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.3.0 (2024-04-07T00:24:16+13:00)
DB Schema | 2024_02_07_151845_custom_map_additions (291)
PHP       | 8.2.17
Python    | 3.11.8
Database  | MariaDB 10.5.24-MariaDB-1:10.5.24+maria~ubu2004
RRDTool   | 1.8.0
SNMP      | 5.9.4
===========================================

[OK]    Installed from the official Docker image; no Composer required
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No python wrapper pollers found
[OK]    Redis is functional
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
[WARN]  Updates are managed through the official Docker image
```

### Anything in the logs that might be useful for us?

```txt
eth1118400 skipped because port is still down since last polling.


Port eth1: eth1 (5 / #118400) ifInOctets
ifHCOutOctets
ifInUcastPkts
ifHCOutUcastPkts
ifInBroadcastPkts
ifOutBroadcastPkts
ifInMulticastPkts
ifOutMulticastPkts
ifHighSpeed (0)
VLAN = ?  Using ifDescr as ifAlias
eth1118400 skipped because port is still down since last polling.
SQL[UPDATE `ports` set `ifSpeed_prev`=?,`poll_time`=?,`poll_prev`=?,`poll_period`=? WHERE `port_id` = ? [0,1714727391,1714727310,81,118400] 0.47ms]
```

**Comment by murrant** [comment]
@kiwilad-nz likely you have enabled rrd_purge which deletes files that have not been updated for awhile and selected port polling.
