### ISSUE TITLE
Incorrect number of seconds in a day

### ISSUE THREAD

**Issue by Pikamander2** [librenms/librenms#16038]
### The problem

Hi there, I used a code search and found an incorrect number of seconds in a day (84600 instead of 86400) listed in one of your files. I recommend fixing it to avoid incorrect timings that could potentially lead to unexpected behavior.

https://github.com/librenms/librenms/blob/c1f955e06e9fe66014473aafd98875aad767fc21/app/Http/Controllers/Table/DeviceController.php#L199

### Output of ./validate.php

```txt
Code search
```

**Comment by murrant** [comment]
The fallback value here is almost impossible to hit because uptime_warning is defined in config_defintions.json. 

Feel free to send a pull request to either remove the fallback value or update it to be consistent with the value in config_defintions.json.
