### ISSUE TITLE
Can i get original data from Maps->Network page?

### ISSUE THREAD

**Issue by fengjian1993** [librenms/librenms#16046]
### The problem

Need original device data and link data, can i know how to get it?

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.4.0 (2024-05-05T00:28:52+02:00)
DB Schema | 2024_04_10_093513_remove_device_perf (291)
PHP       | 8.2.18
Python    | 3.11.9
Database  | MariaDB 10.5.24-MariaDB-1:10.5.24+maria~ubu2004
RRDTool   | 1.8.0
SNMP      | 5.9.4
===========================================

[OK]    Installed from package; no Composer required
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No python wrapper pollers found
[OK]    Redis is functional
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Non-git install, updates are manual or from package
```

**Comment by murrant** [comment]
Either go to links page or dump the links table from the database.

**Comment by fengjian1993** [comment]
> Either go to links page or dump the links table from the database.

i did't found link page from website and i query from table links even if all tables and apis. no relation with Network topo.
Thanks for the reply!
+--------------------------------+
| Tables_in_librenms             |
+--------------------------------+
| abilities                      |
| access_points                  |
| alert_device_map               |
| alert_group_map                |
| alert_location_map             |
| alert_log                      |
| alert_rules                    |
| alert_schedulables             |
| alert_schedule                 |
| alert_template_map             |
| alert_templates                |
| alert_transport_groups         |
| alert_transport_map            |
| alert_transports               |
| alerts                         |
| api_tokens                     |
| application_metrics            |
| applications                   |
| assigned_roles                 |
| authlog                        |
| availability                   |
| bgpPeers                       |
| bgpPeers_cbgp                  |
| bill_data                      |
| bill_history                   |
| bill_perms                     |
| bill_port_counters             |
| bill_ports                     |
| bills                          |
| cache                          |
| cache_locks                    |
| callback                       |
| cef_switching                  |
| ciscoASA                       |
| component                      |
| component_prefs                |
| component_statuslog            |
| config                         |
| custom_map_backgrounds         |
| custom_map_edges               |
| custom_map_nodes               |
| custom_maps                    |
| customers                      |
| customoids                     |
| dashboards                     |
| device_graphs                  |
| device_group_device            |
| device_groups                  |
| device_outages                 |
| device_relationships           |
| devices                        |
| devices_attribs                |
| devices_group_perms            |
| devices_perms                  |
| entPhysical                    |
| entPhysical_state              |
| entityState                    |
| eventlog                       |
| graph_types                    |
| hrDevice                       |
| hrSystem                       |
| ipsec_tunnels                  |
| ipv4_addresses                 |
| ipv4_mac                       |
| ipv4_networks                  |
| ipv6_addresses                 |
| ipv6_networks                  |
| isis_adjacencies               |
| juniAtmVp                      |
| links                          |
| loadbalancer_rservers          |
| loadbalancer_vservers          |
| locations                      |
| mac_accounting                 |
| mefinfo                        |
| mempools                       |
| migrations                     |
| mpls_lsp_paths                 |
| mpls_lsps                      |
| mpls_saps                      |
| mpls_sdp_binds                 |
| mpls_sdps                      |
| mpls_services                  |
| mpls_tunnel_ar_hops            |
| mpls_tunnel_c_hops             |
| munin_plugins                  |
| munin_plugins_ds               |
| netscaler_vservers             |
| notifications                  |
| notifications_attribs          |
| ospf_areas                     |
| ospf_instances                 |
| ospf_nbrs                      |
| ospf_ports                     |
| packages                       |
| pdb_ix                         |
| pdb_ix_peers                   |
| permissions                    |
| plugins                        |
| poller_cluster                 |
| poller_cluster_stats           |
| poller_groups                  |
| pollers                        |
| port_group_port                |
| port_groups                    |
| ports                          |
| ports_adsl                     |
| ports_fdb                      |
| ports_nac                      |
| ports_perms                    |
| ports_stack                    |
| ports_statistics               |
| ports_stp                      |
| ports_vdsl                     |
| ports_vlans                    |
| printer_supplies               |
| processes                      |
| processors                     |
| proxmox                        |
| proxmox_ports                  |
| pseudowires                    |
| push_subscriptions             |
| roles                          |
| route                          |
| sensors                        |
| sensors_to_state_indexes       |
| service_templates              |
| service_templates_device       |
| service_templates_device_group |
| services                       |
| session                        |
| sessions                       |
| slas                           |
| state_indexes                  |
| state_translations             |
| storage                        |
| stp                            |
| syslog                         |
| tnmsneinfo                     |
| transport_group_transport      |
| ucd_diskio                     |
| users                          |
| users_prefs                    |
| users_widgets                  |
| vendor_ouis                    |
| vlans                          |
| vminfo                         |
| vrf_lite_cisco                 |
| vrfs                           |
| wireless_sensors

"ack_alert": "http://10.20.4.120:8001/api/v0/alerts/{id}",
    "add_components": "http://10.20.4.120:8001/api/v0/devices/{hostname}/components/{type}",
    "add_device": "http://10.20.4.120:8001/api/v0/devices",
    "add_device_group": "http://10.20.4.120:8001/api/v0/devicegroups",
    "add_location": "http://10.20.4.120:8001/api/v0/locations",
    "add_parents_to_host": "http://10.20.4.120:8001/api/v0/devices/{id}/parents",
    "add_port_group": "http://10.20.4.120:8001/api/v0/port_groups",
    "add_rule": "http://10.20.4.120:8001/api/v0/rules",
    "add_service_for_host": "http://10.20.4.120:8001/api/v0/services/{hostname}",
    "assign_port_group": "http://10.20.4.120:8001/api/v0/port_groups/{port_group_id}/assign",
    "create_bill": "http://10.20.4.120:8001/api/v0/bills",
    "del_device": "http://10.20.4.120:8001/api/v0/devices/{hostname}",
    "del_location": "http://10.20.4.120:8001/api/v0/locations/{location}",
    "del_parents_from_host": "http://10.20.4.120:8001/api/v0/devices/{id}/parents",
    "del_service_from_host": "http://10.20.4.120:8001/api/v0/services/{id}",
    "delete_bill": "http://10.20.4.120:8001/api/v0/bills/{bill_id}",
    "delete_components": "http://10.20.4.120:8001/api/v0/devices/{hostname}/components/{component}",
    "delete_device_group": "http://10.20.4.120:8001/api/v0/devicegroups/{name}",
    "delete_rule": "http://10.20.4.120:8001/api/v0/rules/{id}",
    "device_availability": "http://10.20.4.120:8001/api/v0/devices/{hostname}/availability",
    "device_outages": "http://10.20.4.120:8001/api/v0/devices/{hostname}/outages",
    "device_under_maintenance": "http://10.20.4.120:8001/api/v0/devices/{hostname}/maintenance",
    "edit_bgp_descr": "http://10.20.4.120:8001/api/v0/bgp/{id}",
    "edit_components": "http://10.20.4.120:8001/api/v0/devices/{hostname}/components",
    "edit_location": "http://10.20.4.120:8001/api/v0/locations/{location_id_or_name}",
    "edit_rule": "http://10.20.4.120:8001/api/v0/rules",
    "edit_service_for_host": "http://10.20.4.120:8001/api/v0/services/{id}",
    "generated::liKs2DAeTOti74r4": "http://10.20.4.120:8001/api/v0",
    "generated::s5ybgIW8yFrk8zMQ": "http://10.20.4.120:8001/api/v0/{path?}",
    "get_alert": "http://10.20.4.120:8001/api/v0/alerts/{id}",
    "get_alert_rule": "http://10.20.4.120:8001/api/v0/rules/{id}",
    "get_all_ports": "http://10.20.4.120:8001/api/v0/ports",
    "get_bgp": "http://10.20.4.120:8001/api/v0/bgp/{id}",
    "get_bill": "http://10.20.4.120:8001/api/v0/bills/{bill_id}",
    "get_bill_graph": "http://10.20.4.120:8001/api/v0/bills/{bill_id}/graphs/{graph_type}",
    "get_bill_graphdata": "http://10.20.4.120:8001/api/v0/bills/{bill_id}/graphdata/{graph_type}",
    "get_bill_history": "http://10.20.4.120:8001/api/v0/bills/{bill_id}/history",
    "get_bill_history_graph": "http://10.20.4.120:8001/api/v0/bills/{bill_id}/history/{bill_hist_id}/graphs/{graph_type}",
    "get_bill_history_graphdata": "http://10.20.4.120:8001/api/v0/bills/{bill_id}/history/{bill_hist_id}/graphdata/{graph_type}",
    "get_components": "http://10.20.4.120:8001/api/v0/devices/{hostname}/components",
    "get_device": "http://10.20.4.120:8001/api/v0/devices/{hostname}",
    "get_device_groups": "http://10.20.4.120:8001/api/v0/devicegroups",
    "get_device_groups_device": "http://10.20.4.120:8001/api/v0/devices/{hostname}/groups",
    "get_devices_by_group": "http://10.20.4.120:8001/api/v0/devicegroups/{name}",
    "get_fdb": "http://10.20.4.120:8001/api/v0/devices/{hostname}/fdb",
    "get_graph_by_port_hostname": "http://10.20.4.120:8001/api/v0/devices/{hostname}/ports/{ifname}/{type}",
    "get_graph_by_portgroup": "http://10.20.4.120:8001/api/v0/portgroups/{group}",
    "get_graph_by_portgroup_multiport_bits": "http://10.20.4.120:8001/api/v0/portgroups/multiport/bits/{id}",
    "get_graph_by_service": "http://10.20.4.120:8001/api/v0/devices/{hostname}/services/{id}/graphs/{datasource}",
    "get_graph_generic_by_hostname": "http://10.20.4.120:8001/api/v0/devices/{hostname}/{type}",
    "get_graphs": "http://10.20.4.120:8001/api/v0/devices/{hostname}/graphs",
    "get_health_graph": "http://10.20.4.120:8001/api/v0/devices/{hostname}/graphs/health/{type}/{sensor_id?}",
    "get_inventory": "http://10.20.4.120:8001/api/v0/inventory/{hostname}",
    "get_inventory_for_device": "http://10.20.4.120:8001/api/v0/inventory/{hostname}/all",
    "get_ip_addresses": "http://10.20.4.120:8001/api/v0/devices/{hostname}/ip",
    "get_link": "http://10.20.4.120:8001/api/v0/resources/links/{id}",
    "get_location": "http://10.20.4.120:8001/api/v0/location/{location_id_or_name}",
    "get_network_ip_addresses": "http://10.20.4.120:8001/api/v0/resources/ip/networks/{id}/ip",
    "get_oxidized_config": "http://10.20.4.120:8001/api/v0/oxidized/config/{device_name}",
    "get_poller_group": "http://10.20.4.120:8001/api/v0/poller_group/{poller_group_id_or_name?}",
    "get_port_description": "http://10.20.4.120:8001/api/v0/ports/{portid}/description",
    "get_port_graphs": "http://10.20.4.120:8001/api/v0/devices/{hostname}/ports",
    "get_port_groups": "http://10.20.4.120:8001/api/v0/port_groups",
    "get_port_info": "http://10.20.4.120:8001/api/v0/ports/{portid}",
    "get_port_ip_info": "http://10.20.4.120:8001/api/v0/ports/{portid}/ip",
    "get_port_stack": "http://10.20.4.120:8001/api/v0/devices/{hostname}/port_stack",
    "get_port_stats_by_port_hostname": "http://10.20.4.120:8001/api/v0/devices/{hostname}/ports/{ifname}",
    "get_ports_by_group": "http://10.20.4.120:8001/api/v0/port_groups/{name}",
    "get_vlans": "http://10.20.4.120:8001/api/v0/devices/{hostname}/vlans",
    "get_vrf": "http://10.20.4.120:8001/api/v0/routing/vrf/{id}",
    "get_wireless_graph": "http://10.20.4.120:8001/api/v0/devices/{hostname}/graphs/wireless/{type}/{sensor_id?}",
    "list_alert_rules": "http://10.20.4.120:8001/api/v0/rules",
    "list_alertlog": "http://10.20.4.120:8001/api/v0/logs/alertlog/{hostname?}",
    "list_alerts": "http://10.20.4.120:8001/api/v0/alerts",
    "list_arp": "http://10.20.4.120:8001/api/v0/resources/ip/arp/{query}/{cidr?}",
    "list_authlog": "http://10.20.4.120:8001/api/v0/logs/authlog",
    "list_available_health_graphs": "http://10.20.4.120:8001/api/v0/devices/{hostname}/health/{type?}/{sensor_id?}",
    "list_available_wireless_graphs": "http://10.20.4.120:8001/api/v0/devices/{hostname}/wireless/{type?}/{sensor_id?}",
    "list_bgp": "http://10.20.4.120:8001/api/v0/bgp",
    "list_bills": "http://10.20.4.120:8001/api/v0/bills",
    "list_cbgp": "http://10.20.4.120:8001/api/v0/routing/bgp/cbgp",
    "list_devices": "http://10.20.4.120:8001/api/v0/devices",
    "list_eventlog": "http://10.20.4.120:8001/api/v0/logs/eventlog/{hostname?}",
    "list_fdb": "http://10.20.4.120:8001/api/v0/resources/fdb",
    "list_fdb_detail": "http://10.20.4.120:8001/api/v0/resources/fdb/{mac}/detail",
    "list_fdb_mac": "http://10.20.4.120:8001/api/v0/resources/fdb/{mac}",
    "list_ip_addresses": "http://10.20.4.120:8001/api/v0/resources/ip/addresses",
    "list_ip_networks": "http://10.20.4.120:8001/api/v0/resources/ip/networks",
    "list_ipsec": "http://10.20.4.120:8001/api/v0/routing/ipsec/data/{hostname}",
    "list_links": "http://10.20.4.120:8001/api/v0/resources/links",
    "list_links_device": "http://10.20.4.120:8001/api/v0/devices/{hostname}/links",
    "list_locations": "http://10.20.4.120:8001/api/v0/resources/locations",
    "list_mpls_saps": "http://10.20.4.120:8001/api/v0/routing/mpls/saps",
    "list_mpls_services": "http://10.20.4.120:8001/api/v0/routing/mpls/services",
    "list_ospf": "http://10.20.4.120:8001/api/v0/ospf",
    "list_ospf_ports": "http://10.20.4.120:8001/api/v0/ospf_ports",
    "list_oxidized": "http://10.20.4.120:8001/api/v0/oxidized/{hostname?}",
    "list_sensors": "http://10.20.4.120:8001/api/v0/resources/sensors",
    "list_services": "http://10.20.4.120:8001/api/v0/services",
    "list_services_device": "http://10.20.4.120:8001/api/v0/services/{hostname}",
    "list_syslog": "http://10.20.4.120:8001/api/v0/logs/syslog/{hostname?}",
    "list_vlans": "http://10.20.4.120:8001/api/v0/resources/vlans",
    "list_vrf": "http://10.20.4.120:8001/api/v0/routing/vrf",
    "maintenance_device": "http://10.20.4.120:8001/api/v0/devices/{hostname}/maintenance",
    "maintenance_devicegroup": "http://10.20.4.120:8001/api/v0/devicegroups/{name}/maintenance",
    "post_syslogsink": "http://10.20.4.120:8001/api/v0/syslogsink",
    "remove_port_group": "http://10.20.4.120:8001/api/v0/port_groups/{port_group_id}/remove",
    "rename_device": "http://10.20.4.120:8001/api/v0/devices/{hostname}/rename/{new_hostname}",
    "search_mac": "http://10.20.4.120:8001/api/v0/ports/mac/{search}",
    "search_oxidized": "http://10.20.4.120:8001/api/v0/oxidized/config/search/{searchstring}",
    "search_ports": "http://10.20.4.120:8001/api/v0/ports/search/{field}/{search?}",
    "server_info": "http://10.20.4.120:8001/api/v0/system",
    "trigger_device_discovery": "http://10.20.4.120:8001/api/v0/devices/{hostname}/discover",
    "unmute_alert": "http://10.20.4.120:8001/api/v0/alerts/unmute/{id}",
    "update_device_field": "http://10.20.4.120:8001/api/v0/devices/{hostname}",
    "update_device_group": "http://10.20.4.120:8001/api/v0/devicegroups/{name}",
    "update_device_group_add_devices": "http://10.20.4.120:8001/api/v0/devicegroups/{name}/devices",
    "update_device_group_remove_devices": "http://10.20.4.120:8001/api/v0/devicegroups/{name}/devices",
    "update_device_port_notes": "http://10.20.4.120:8001/api/v0/devices/{hostname}/port/{portid}",
    "update_port_description": "http://10.20.4.120:8001/api/v0/ports/{portid}/description"

**Comment by murrant** [comment]
https://docs.librenms.org/API/Switching/#list_links
