### ISSUE TITLE
Unable to configure nfsen_base

### ISSUE THREAD

**Issue by whitej46** [librenms/librenms#16051]
### The problem

I was trying to integrate nfsen. Graphs are working great. However, when I run the stats, nfdump runs, but doesn’t find any data files. Glancing through the code, it looks like there is a configuration item called ‘nfsen_base’ that needs to be defined. However, when I try to configure this with the command:
lnms config:set nfsen_base ‘/opt/nfsen/’
I get the error message:
“This is not a valid setting. Please check your input”

It appears that the code is referring to this object, but that somewhere along the way, the ability to set it was lost.

Screen shot of validate.php attached (I can't copy from this terminal)
![validate](https://github.com/librenms/librenms/assets/168861166/362ab1ca-dace-4c0e-bff5-11cd1bba1e22)

### Output of ./validate.php

```txt
Sorry, unable to paste the text, please see screen shot above.
```

### Anything in the logs that might be useful for us?

```txt
To test out my theory, I hardcoded the path in my functions.inc.php and things worked splendidly.  Unfortunately, do not know enough about coding and how the config variables are defined in the LibreNMS environment to make the code adjustment myself.  Hopefully someone more knowledge can get the nfsen_base configuration variable in so that it can be set.
```

**Comment by murrant** [comment]
It needs to be added to config_definitions.json

**Comment by whitej46** [comment]
Took a little bit of playing to get type correct, but got it working.  Put in a pull request.
