### ISSUE TITLE
alerts notifications never cleaned up

### ISSUE THREAD

**Issue by mmarchand** [librenms/librenms#1608]
Hi,

I have lots of alerts that never gets cleaned up in "Alerts notifications", altough it's polling the device just fine for days and the alert is no longer relevant (example "Device down" alert and "Device rebooted" alert for example)

![alert](https://cloud.githubusercontent.com/assets/1297584/9058236/e5589a34-3a9f-11e5-81bb-ac0bfcf9d1ae.png)
![notif](https://cloud.githubusercontent.com/assets/1297584/9058235/e55726d6-3a9f-11e5-8dff-0c61433e0327.png)

![alert-reboot](https://cloud.githubusercontent.com/assets/1297584/9058273/36b954a4-3aa0-11e5-81c4-93c0717d5e8d.png)
![rebooted](https://cloud.githubusercontent.com/assets/1297584/9058274/3a3193c6-3aa0-11e5-854d-951f0642cbd1.png)

**Comment by laf** [comment]
That's odd, I've never seen that before.

Tagging @f0o in for his thoughts.

**Comment by f0o** [comment]
@mmarchand would be best to arrange a time-window we both could be on IRC. I personally cant reproduce the situation. Can you collect information on software+versions installed, OS, Distribution, Commit, Rules, Anonymized snapshot of devices table,...

Feel free to send me those information privately at f0o@librenms.org

**Comment by mmarchand** [comment]
Looks like it was some old behavior,
I deleted all alerts from the alerts table to start from a fresh state and I have not seen any alerts showing this behavior, so it was probably a bug in my table history I believe
let's close this issue for now, sorry for the noise
