### ISSUE TITLE
Issue with Devices Menu Shortcut

### ISSUE THREAD

**Issue by darkdecoy** [librenms/librenms#16167]
### The problem

If you only create ping monitors then the devices page shortcut in the menu is broken and instead sends to the home page.

![2024-06-28_22-36](https://github.com/librenms/librenms/assets/22571553/29169fda-c8d7-4daa-9f36-66b61a3c4497)

Unless you manually to go to at least one device and set its type then the devices shortcut will work properly.

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.6.0-27-g5ab2f685b (2024-06-28T13:45:50+00:00)
DB Schema | 2024_04_29_183605_custom_maps_drop_background_suffix_and_background_version (294)
PHP       | 8.1.2-1ubuntu2.18
Python    | 3.10.12
Database  | MariaDB 10.6.18-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.7.7
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

24.6.0-27-g5ab2f685b - Fri Jun 28 2024 13:45:50 GMT+0000

**Comment by murrant** [comment]
Looks like a user permissions issue at first glance.

**Comment by darkdecoy** [comment]
This is with the user that is created during the installation process.  Also if I navigate to the device page or devices page by typing their exact url then I can get to them both.

**Comment by jiannelli** [comment]
I can replicate it.

**Comment by jiannelli** [comment]
The submenu is shown [only when there are device types.](https://github.com/librenms/librenms/blob/0fbaaf7a7473bba6d346cb8bcb80d95324836c98/resources/views/layouts/menu.blade.php#L130)

If there isn't any device with a device type the menú will show "No devices" with no link to the devices list. href="#"
If there are devices with devices types it will show "All devices" with a link to the device list.

The expected behavious would be to show the device list page and with an All Devices submenu, even when there are no device types.
