### ISSUE TITLE
Can't add host on fresh install

### ISSUE THREAD

**Issue by Alucardfh** [librenms/librenms#1618]
Hi,

I just gave a go at librenms to compare it against our current Observium.

I couldn't manage to add any host after following the install doc for centos.

The php build-base.php command finished successfully.

I tracked the issue to the SQL insert query : 
Error in query: . Field 'status_reason' doesn't have a default value

Indeed if you check the devices table it doesn't show any default value for the field status_reason.
| status_reason             | varchar(50)                                  | NO   |     | NULL    |                |

Setting a default value of 0 correct the problem and seems to cause no other issue :
ALTER TABLE devices CHANGE COLUMN status_reason status_reason VARCHAR(50) NOT NULL DEFAULT '0';

But this is probably not the right fix.

**Comment by laf** [comment]
Sounds like you have strict mode on in MySQL, I'd suggest you disable this.

**Comment by Alucardfh** [comment]
Well spotted.

I forgot to edit my /etc/my.cnf on my fresh install.

It solves this issue and also the fact that the configured alerts showed up in the overview but without any descriptions.

I noticed in the changelog that efforts are being made to improve strict mode support but in the meantime It would probably be a good idea to mention that it should be disable in the documentation.

From my searches in  http://docs.librenms.org/Installation/Installation-(RHEL-CentOS)/ and http://docs.librenms.org/Installation/Installation-(Debian-Ubuntu)/ there is no mention at all about strict mode.

Thanks again for the quick answer

**Comment by SaaldjorMike** [comment]
Also, if there's a way to notify the user that strict-mode is on and should be disabled.

**Comment by laf** [comment]
I don't think we can visually let warn people as we only have the in page popup system which could/would annoy people.

Hopefully PR #1635 at least covers us on the install docs + if people run validate.php
