### ISSUE TITLE
Add the poller groups to the Pollers List and in Poll-Log

### ISSUE THREAD

**Issue by masonke** [librenms/librenms#1619]
This is a low priority, nice to have request

In the Preferences -> Pollers -> Pollers it would be handy to show what poller groups the device supports
and 
In the Preferences -> Pollers -> Poll-Log views, it would be handy to show what poller group was used to poll the device

**Comment by laf** [comment]
I have number 2 ready to go but I'm not sure what you mean by number 1.

Preferences -> Pollers -> Pollers doesn't show a break down by device so we can't show the groups supported here.

**Comment by masonke** [comment]
Thanks for the fast work, here are some screen shots of what I mean by #1 and #2.
![poller-log](https://cloud.githubusercontent.com/assets/1863778/9122964/716640ec-3c5a-11e5-8fe5-f7167ad52330.jpg)
![pollers](https://cloud.githubusercontent.com/assets/1863778/9122963/71664290-3c5a-11e5-9e68-2fe883de4931.jpg)

**Comment by laf** [comment]
Thanks @masonke 

Number two is done, number one I still don't know what you want :) I know the page but you asked for:

"it would be handy to show what poller groups the device supports"

But that page isn't a list of devices so can't show what groups the devices support

**Comment by masonke** [comment]
My bad, I used the wrong term and confused things.
It should have been:
"it would be handy to show what poller groups each poller supports"

The idea is to show what groups each poller is configured for.

BTW, I sent a snmp monitoring vendor away muttering bad words about LibreNMS today. The distributed poller shut them down hard. Thank you!

**Comment by laf** [comment]
I'll take a look. 

What vendor out of interest :)?

**Comment by laf** [comment]
K, not sure number 1 is possible. We only know which groups a poller supports from $config so it's not available centrally :(
