### ISSUE TITLE
Name the log file based on the device name

### ISSUE THREAD

**Issue by masonke** [librenms/librenms#1620]
This is a low priority, nice to have request

The log file is named librenms.log, which works well for a single instance. With the distributed systems, it would be nice to have the log use the system name. That way we could have them all collected via a file share into one location.

The config.php value for  distributed_poller_name might be appropriate.
$config['distributed_poller_name']   = file_get_contents('/proc/sys/kernel/hostname');

**Comment by laf** [comment]
I just did a commit for this but then thought about people that might have (and should be) running logrotate on this file in the first place. If we then by default change the log file name then it may not rotate.

So then I though, we'll just leave the default as is and allow people to change config.php to say they want to use the new format but we already have this.

I'd suggest just setting
```bash
$config['log_file'] = rtrim($config['distributed_poller_name']);
```

Anyone else's thoughts? Shall we just make this the default.

**Comment by masonke** [comment]
Good catch. The only time this would be used is if you have a distributed environment and want to aggregate the logs. Given that, default off should be fine.

**Comment by laf** [comment]
@masonke That's what I'm saying though, if you have to change a config option to turn on a different file name then you may as well just edit the config option that specifies the filename?

We could tie it in to distributed polling being enabled but you don't need to have that on for the web server so that log file would just be librenms.log.

**Comment by paulgear** [comment]
:+1: We should make it the default; we can include logrotate config that handles it - logrotate supports wildcards.

**Comment by laf** [comment]
Making it the default now means it's not the default for everyone who has things setup already and could cause issues. We don't control people's logrotate setup so you could at worse break logrotate for someone leading to disk space issues.

You'd need to ensure you give people adequate notice that this change will happen or just update the distributed poller docs and advice people change it when setting that up.

**Comment by paulgear** [comment]
We don't have to use the system logrotate config; we can make a separate call to it from our cron.

**Comment by laf** [comment]
Indeed but that's just duplicating what logrotate is for and I'd expect we can't do it as efficiently either.

**Comment by paulgear** [comment]
I mean actually calling logrotate, not rewriting it.  I'll PR it to explain what I mean.

**Comment by laf** [comment]
Proposing this is closed in 48 hours.

**Comment by paulgear** [comment]
Sorry - will write up something before the summit for this.

**Comment by laf** [comment]
Proposing to close in 48 hours.

**Comment by masonke** [comment]
Did this get added as an option that can be turned on?

**Comment by laf** [comment]
You can already set the log file in config.php today but nothing else from this issue has been added for reasons I've made above.

**Comment by masonke** [comment]
Thank you
~KEM
