### ISSUE TITLE
OAuth users role resets to default_role at login

### ISSUE THREAD

**Issue by suom1** [librenms/librenms#16218]
### The problem

I have recently setup OAuth for Google based on the Microsoft example in [documentation](https://docs.librenms.org/Extensions/OAuth-SAML/) which worked great. 

However I have one problem, all OAuth users roles get reset to the role that is defined as default role (`auth.socialite.default_role`) in my case global-read at login. I can change the role just fine and verify after that the role indeed is changed.

There are no errors or anything logged.

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.7.0-5-g97a13f6fe (2024-07-17T23:07:57+02:00)
DB Schema | 2024_07_13_133839_modify_ent_physical_defaults (295)
PHP       | 8.3.6
Python    | 3.12.3
Database  | MariaDB 10.11.8-MariaDB-0ubuntu0.24.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.4.pre2
===========================================

[OK]    Composer Version: 2.7.7
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### What was the last working version of LibreNMS?

24.7.0

**Comment by Jellyfrog** [comment]
Seems it overwrites all roles, should we set `$create=true` ? @murrant 
https://github.com/librenms/librenms/blob/512403a2554fa5fab1a134a16e72daa69d8b82e3/app/Http/Controllers/Auth/SocialiteController.php#L177-L178

https://github.com/librenms/librenms/blob/512403a2554fa5fab1a134a16e72daa69d8b82e3/app/Models/User.php#L116-L125

**Comment by murrant** [comment]
Ok, so if I delete a role from the ISP, how is it removed?

**Comment by Jellyfrog** [comment]
We’re talking about default role assignment here only. Which overwrites all other roles on each login if set

**Comment by murrant** [comment]
Create should be conditionally true then (true if the user doesn't exist yet)

**Comment by murrant** [comment]
Actually, the code in the provider looks completely wrong to me. default_roles just overrides everything every time.

**Comment by bagassy** [comment]
I think the problem prior to this, 
If the code found any roles in the returned attributes, it would have exited earlier at
https://github.com/librenms/librenms/blob/512403a2554fa5fab1a134a16e72daa69d8b82e3/app/Http/Controllers/Auth/SocialiteController.php#L170-L174

And not reached the code Jellyfrog pasted above, assuming OP set claims/scopes in config.
Ref. this other bug report: 
https://github.com/librenms/librenms/issues/16220

**Comment by suom1** [comment]
`{
    "redirect": false,
    "register": true,
    "default_role": "global-read",
    "claims": [],
    "configs": {
        "google": {
            "client_id": "client_id.apps.googleusercontent.com",
            "client_secret": "client_secret",
            "listener": "\\SocialiteProviders\\Google\\GoogleExtendSocialite"
        }
    }
}
`

The changes suggested in your issue does not solve the problem for me, but it also doesn't break anything.

**Comment by bagassy** [comment]
Some things with your config:
- `claims` and `scopes` are empty/undefined.

Looking at the setRolesFromClaim function:

https://github.com/librenms/librenms/blob/512403a2554fa5fab1a134a16e72daa69d8b82e3/app/Http/Controllers/Auth/SocialiteController.php#L158-L181

Both `claims` and `scopes` must be set for the code to set roles, else the `default_role` is assigned as the role. So you'll definitely need to set these 2 config. parameters. 

In my bug report, there is an example (for SAML) at the bottom of the `validate.php` output.
See the documentation, in the section "Claims / Access Scopes"

Check with some sort of browser extension/plugin that group information is being returned in the OAuth messages, and that the attribute name being used matches your `scopes`, this helped me with troubleshooting.

**Comment by suom1** [comment]
In my case I would like to not use claims or scopes?
I want everyone who logins with google to get global read and then just change to admin for a few specific users. And because of that I don't want `default_role` to overwrite set access at login.

**Comment by bagassy** [comment]
To assign admin for a few users, you will need to set `scopes` and `claims`, and add admin users to a `librenms_admin` group. Everyone else will get `default_role`.

Then you will hit the bug I linked to previously.

**Comment by suom1** [comment]
Sure you could do it with scopes and claims, but is that the only way it should be done and essentially the manual system is not supposed to work? 
Since to me it doesn't make sense that manually changing a users role would not work. 

Your bug and mine seems to be a bit different as my problem is only really that the role is overwritten with `default_role` each login.

**Comment by bagassy** [comment]
That's not how it's currently designed/coded. Roles for *external* users are evaluated at every login and any manual role assignments will be lost/reset at next login.
So we can say that it's working as expected, since you haven't defined any scopes/claims, everyone is getting `default_role` at login.

But I'd be happy to be corrected by someone with more knowledge.
