### ISSUE TITLE
Polling specific OIDs

### ISSUE THREAD

**Issue by MauJFernandez** [librenms/librenms#1622]
This issue comes from this Google Group thread: https://groups.google.com/forum/#!topic/librenms-project/j70XvcoExMA

I quote the question:

>Another question, I added the Citrix NetScaler 17550, it has discovered everything nicely, in the Load Balancer menu I see the VServers but I need to see the services attached to each VServer (each service name is the 1.3.6.1.4.1.5951.4.1.3.2.1.9 OID named vsvrServiceFullName), that is, each Bits/Packets/Connections/Requests/HitMiss for each service, is that included in the application? If no, is there a way to add just a specific OID the poll and have its own graph?"

**Comment by Ftelf** [comment]
I will second that. A generic snmp Module, which could allow to manual oids to be added. I know cacti way, it's ugly etc, but there are so many devices in the world a nice ones which will be never supported, but deserve to be graphed. Like www.onlinetechnology.cz and many more.

**Comment by paulgear** [comment]
Hi all; this is something I've got almost ready to merge back in, but we need to resolve our strategy for #1888 before we add any other major data structures.

**Comment by MauJFernandez** [comment]
This is awesome news @paulgear, I can't wait to test it!

**Comment by paulgear** [comment]
@MauJFernandez PR #2536 has been submitted; some more details at https://groups.google.com/forum/#!topic/librenms-project/5Yo8slYxHwM

**Comment by MauJFernandez** [comment]
Hi @paulgear, sorry for the delay, I'm now deploying a test server to play with this.

Thank you!

**Comment by paulgear** [comment]
MIB-based polling has been merged; please see doc/Extensions/MIB-based-polling.md for details.

**Comment by MauJFernandezUVR** [comment]
Hey @paulgear, I've been testing this and after some tinkering with the mibs and adding the modules to the {os}.inc.php, I been able to discover what I was looking for, this is fantastic, thanks for such awesome work, my boss is happy :+1: 

I'm now experimenting with AudioCodes Gateways, do you have any plans to add an on/off for the discovered OIDs? Having an entire MIB being polled when I just want some of them is overkill I think.

Again, thanks for your work.

**Comment by paulgear** [comment]
@MauJFernandez Filtering is definitely something I'd like to add, but it might be down the track a little.  You can limit the effects of it by selecting a specific part of the MIB to load.  e.g. if your MIB is:
```
enterprises.big.long.mib.path.mymib.part1ofmib
enterprises.big.long.mib.path.mymib.part1ofmib.dataset1
enterprises.big.long.mib.path.mymib.part1ofmib.dataset1.thispart
enterprises.big.long.mib.path.mymib.part1ofmib.dataset1.thispart.instance1
enterprises.big.long.mib.path.mymib.part1ofmib.dataset1.thispart.instance2
enterprises.big.long.mib.path.mymib.part1ofmib.dataset1.thispart.instance3
```
You can usually choose to poll at "thispart" instead of "dataset1" or "part1ofmib" or "mymib" by passing "thispart" to the register_mibs() function in includes/discovery/os/YOUROS.inc.php.

**Comment by masonke** [comment]
@MauJFernandez Could you share what you added to the netscaler.inc.php ? For some reason I keep hitting "MIB: Could not find all::enterprises.5951.1" on discovery

Thanks
