### ISSUE TITLE
mikrotik routeros : wrong local port name in neighbours tab

### ISSUE THREAD

**Issue by pescobar** [librenms/librenms#16253]
### The problem

I have two mikrotik routeros devices connected like this:

switch `sw-mkt-scicoremed-02` >> interface `sfp-sfpplus3` >><< interface `sfp-sfpplus20` << switch `sw-mkt-scicoremed-02`

interface `sfp-sfpplus3` in `sw-mkt-scicoremed-02` belong to bond `uplink-bond`
interface `sfp-sfpplus20` in `sw-mkt-scicoremed-dist-01` belong to bond `mlag-bond-20`

This is the output of `/ip/neighbor/print` in `sw-mkt-scicoremed-02`

```
sw-mkt-scicoremed-02]> /ip/neighbor/print where identity~"sw-mkt-scicoremed-dist-01"
Columns: INTERFACE, MAC-ADDRESS, IDENTITY
#  INTERFACE     MAC-ADDRESS        IDENTITY
1  sfp-sfpplus3  DC:2C:6E:4E:16:8C  sw-mkt-scicoremed-dist-01
   uplink-bond
   bridge
```

This is the output of `/ip/neighbor/print` in `sw-mkt-scicoremed-dist-01`
```
sw-mkt-scicoremed-dist-01]> /ip/neighbor/print where identity~"sw-mkt-scicoremed-02"
Columns: INTERFACE, MAC-ADDRESS, IDENTITY
#  INTERFACE      MAC-ADDRESS        IDENTITY
7  sfp-sfpplus20  48:A9:8A:AB:04:0E  sw-mkt-scicoremed-02
   mlag-bond-20
   bridge
   ```

The discovery process from librenms looks good. The main difference in the discovery output is that the interfaces are named `bridge/mlag-bond-20/sfp-sfpplus20` and `bridge/uplink-bond/sfp-sfpplus3`. See the output below:

```
/opt/librenms/discovery.php -h sw-mkt-scicoremed-02 -d -m discovery-protocols|grep "Discover link"|grep scicoremed-dist-01
Discover link: 1120, lldp, 1207, sw-mkt-scicoremed-dist-01, bridge/mlag-bond-20/sfp-sfpplus20, , MikroTik RouterOS 7.13.1 (stable) Jan/05/2024 13:51:11 CRS326-24S+2Q+, 18
```

```
/opt/librenms/discovery.php -h sw-mkt-scicoremed-dist-01 -d -m discovery-protocols|grep "Discover link" |grep mkt-scicoremed-02
Discover link: 1207, lldp, 1107, sw-mkt-scicoremed-02, bridge/uplink-bond/sfp-sfpplus3, , MikroTik RouterOS 7.12 (stable) Nov/09/2023 07:45:06 CRS354-48G-4S+2Q+, 20
```

But when I got to `webui >> devices >> sw-mkt-scicoremed-02 >> Neighbours` it says that the `Local port` for the link between `sw-mkt-scicoremed-02` and `sw-mkt-scicoremed-dist-01` is `Ether12` . See the screenshot below:

![librenms neighbours](https://github.com/user-attachments/assets/ba530dff-ec21-4291-9d0f-55c0862ae552)

I would appreciate if you point me in the right direction to further debug this issue.

Let me know if you need more details.

### Output of ./validate.php

```txt
./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.7.0 (2024-07-17T08:35:08+02:00)
DB Schema | 2024_07_13_133839_modify_ent_physical_defaults (295)
PHP       | 8.1.2-1ubuntu2.18
Python    | 3.10.12
Database  | MariaDB 10.6.18-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Installed from package; no Composer required
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Non-git install, updates are manual or from package
```
```


### What was the last working version of LibreNMS?

_No response_

### Anything in the logs that might be useful for us?

_No response_

**Comment by murrant** [comment]
This is an upstream issue.  LibreNMS is just using whatever the mikrotiks are sending to their neighbors with LLDP.

The main root of the problem is Mikrotiks allow you to rename the "ifName" of the device, this should be a read-only field.  User descriptions should be in ifAlias.  Them and their users get to deal with that design choice.

**Comment by pescobar** [comment]
Hi @murrant 

Maybe I am misunderstanding but I think there is a mismatch between the info provided by the librenms discover and the info in the librenms webui

When I manually execute the discovery the interface names look correct ( interface names `bridge/uplink-bond/sfp-sfpplus3` and `bridge/mlag-bond-20/sfp-sfpplus20`)  See below:

```
/opt/librenms/discovery.php -h sw-mkt-scicoremed-dist-01 -d -m discovery-protocols|grep "Discover link" |grep mkt-scicoremed-02
Discover link: 1207, lldp, 1107, sw-mkt-scicoremed-02, bridge/uplink-bond/sfp-sfpplus3, , MikroTik RouterOS 7.12 (stable) Nov/09/2023 07:45:06 CRS354-48G-4S+2Q+, 20
```
```
/opt/librenms/discovery.php -h sw-mkt-scicoremed-02 -d -m discovery-protocols|grep "Discover link"|grep scicoremed-dist-01
Discover link: 1120, lldp, 1207, sw-mkt-scicoremed-dist-01, bridge/mlag-bond-20/sfp-sfpplus20, , MikroTik RouterOS 7.13.1 (stable) Jan/05/2024 13:51:11 CRS326-24S+2Q+, 18
```

But in the librenms webui it says the local interface name for device `sw-mkt-scicoremed-02`  is `Ether22` (See the screenshot in my original post). Actually interface `Ether22` in device `sw-mkt-scicoremed-02` is not in use

If I grep for `Ether22` in the discovery output I think it's reporting that interface ether22 is the remotePort on a different device `sw-mkt-mgmt-06`. That's why I don't understand why webui says `Ether22` is local port in device `sw-mkt-scicoremed-02`. See the ouput below

```
/opt/librenms/discovery.php -h sw-mkt-scicoremed-dist-02 -d -m discovery-protocols|grep -i ether22
lldpRemPortId[0][1][2] = "bridge/ether22"
    'lldpRemPortId' => 'bridge/ether22',
Discover link: 1160, lldp, 0, sw-mkt-mgmt-06, bridge/ether22 (dc2c6e9debd0), , MikroTik RouterOS 7.6 (stable) Oct/17/2022 10:55:40 CRS326-24G-2S+,
SQL[SELECT COUNT(*) FROM `links` WHERE `remote_hostname` = ? AND `local_port_id` = ? AND `protocol` = ? AND `remote_port` = ? ["sw-mkt-mgmt-06",1160,"lldp","bridge\/ether22 (dc2c6e9debd0)"] 0.27ms]
SQL[SELECT `id`,`local_device_id`,`remote_platform`,`remote_version`,`remote_device_id`,`remote_port_id` FROM `links` WHERE `remote_hostname` = ? AND `local_port_id` = ? AND `protocol` = ? AND `remote_port` = ? ["sw-mkt-mgmt-06",1160,"lldp","bridge\/ether22 (dc2c6e9debd0)"] 0.7ms]
      'bridge/ether22 (dc2c6e9debd0)' => 1,
1160 -> sw-mkt-mgmt-06 -> bridge/ether22 (dc2c6e9debd0)
```

Feel free to close the issue in case I am wrong and this is not an issue on the librenms side.

Regards.

**Comment by murrant** [comment]
@pescobar You are correct on both counts.  This is because that is what the Mikrotik device says they are (in both cases).

LibreNMS is not changing things, simply displaying the info given to it by your devices.  I tried to explain the nuance of why Mikrotik doesn't give you the desired result in my first post, but it seems I failed.

**Comment by murrant** [comment]
Oh anecdotally, if you set the port "descriptions" in your Mikrotik device to match the default port names, things will work as you hope.
