### ISSUE TITLE
Polling doesnt set os+system info for device

### ISSUE THREAD

**Issue by SaaldjorMike** [librenms/librenms#1625]
When I run polling with
```
./poller.php -h 206 -d -m system,os
```
I get the following output: http://paste.ubuntu.com/12009994/

It looks like values for the entry in the devices table in the SQL database is still NULL, which leaves me with a device overview where the left part is missing a lot of info (e.g. hardware and version) even though the events shows that they are picked up(?):
https://i.imgur.com/zIWYzp5.png

**Comment by adammmmm** [comment]
After updating our LibreNMS deployment after vacations this week I noticed the same issue on Cisco IOS devices that previously worked fine.

Probably related to another issue that popped up at the same time "Device rebooted after 1 years, 131 days, 22h 4m 43s" every five minutes. Looking at the device you see the uptime 1 years, 131 days, 22h 4m 43s, so it doesn't seem like it's updated anymore.

**Comment by adammmmm** [comment]
In my case, this was fixed with the merge of #1629 , all system info is added correctly now.
