### ISSUE TITLE
Add device with API

### ISSUE THREAD

**Issue by Meiqo** [librenms/librenms#16276]
### The problem

Hi. Started using the API and encountered a small problem when adding devices, namely when creating not all fields are available, which are then used by the device. 
So the request is just that, expand the capabilities of the add_device option, add fields: 'sysName', 'purpose', 'notes'.
In this case, the field data is transferred but not written to the new device. 
Ideally it would be possible to specify all fields when adding devices, but the ones I specified are very lacking. 
Thanks.

### Output of ./validate.php

```txt
Component | Version
--------- | -------
LibreNMS  | 24.7.0-41-gb62a4bacd (2024-08-07T05:19:50+03:00)
DB Schema | 2024_07_19_120719_update_ports_stack_table (296)
PHP       | 8.1.2-1ubuntu2.18
Python    | 3.10.12
Database  | MariaDB 10.6.18-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.7.7
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

**Comment by murrant** [comment]
Thank you for your submission.  This is a feature request.  Issues are for confirmed bugs.

Please post all feature requests in the community forum: https://community.librenms.org/c/feature-requests/3
