### ISSUE TITLE
The update of uptime device not working

### ISSUE THREAD

**Issue by Calvario** [librenms/librenms#1627]
Hello @SaaldjorMike,

Since this commit #1610 the uptime will not updated on devices.

includes/polling/functions.inc.php
(-)        $update_array['last_polled']           = array('NOW()');
(-)        $update_array['last_polled_timetaken'] = $device_time;
(-)        $update_array['last_ping']             = array('NOW()');
(-)        $update_array['last_ping_timetaken']   = $ping_time;
(+)        $update_array = array(
(+)            'last_polled'           => array('NOW()'),
(+)            'last_polled_timetaken' => $device_time,
(+)            'last_ping'             => array('NOW()'),
(+)            'last_ping_timetaken'   => $ping_time,
(+)        );

This part of code make the problem.
When restoring before the commit everything work.

PS : this issues can be have the same problem #1625 

Thanks.

**Comment by Rosiak** [comment]
#1629 will revert the change and should fix it, waiting for merge.

**Comment by Calvario** [comment]
Confirmed OK
