### ISSUE TITLE
Missing support for BGP4v2-MIB on VyOS / FRR

### ISSUE THREAD

**Issue by alyxto** [librenms/librenms#16271]
### The problem

I have a couple of VyOS based Routers doing BGP.
Unfortunately, LibreNMS is unable to monitor the IPv6 based BGP sessions.

I assume this issue was caused by the fact that VyOS is using FRR which itself only supported BGP4-MIB.
However, FRR added support for BGP4v2-MIB a couple of years ago, so it would be great if LibreNMS would use those.

VyOS Issue: https://vyos.dev/T366
FRR Issue: https://github.com/FRRouting/frr/issues/6486
FRR Commits adding BGP4v2-MIB support: https://github.com/FRRouting/frr/pull/12311, https://github.com/FRRouting/frr/pull/12384, https://github.com/FRRouting/frr/pull/12501

### Output of ./validate.php

```txt
N/A
```

### What was the last working version of LibreNMS?

24.6.0

**Comment by canoziia** [comment]
Hello, have you found a solution? My librenms 24.11.0 still does not show ipv6 neighbors.

**Comment by sever-sever** [comment]
> Hello, have you found a solution? My librenms 24.11.0 still does not show ipv6 neighbors.

Can you try this? https://gist.github.com/sever-sever/d58ebefe32e326fbca368955230679e2
```
wget https://gist.github.com/sever-sever/d58ebefe32e326fbca368955230679e2
sudo bash snmp_mibs_downloader.sh
```

**Comment by nonobzh29** [comment]
Does not change anything unfortunately :(

I think the problem is in this file: https://github.com/librenms/librenms/blob/master/includes/polling/bgp-peers.inc.php#L67
If the device is not in the list above this line (this is the case for VyOS), it falls back to BGP4-MIB.

**Comment by netchron-personal** [comment]
Any updates on this?

**Comment by canoziia** [comment]
I've partially fixed the problem by using BGP4V2-MIB for IPv6 and using BGP4-MIB for IPv4. It should now be able to display IPv6 peers, but BGP updates are still not showing up.

If you think this is acceptable, I can submit a pr.

https://github.com/KawaiiNetworks/librenms/commit/613160e7e9d2ff4cfdeb2b2f773d9952a91dbba7
