### ISSUE TITLE
Adding devices via API using force_add never get polled or discovered - Revisit

### ISSUE THREAD

**Issue by OskarBLarsson** [librenms/librenms#16282]
### The problem

According to documentation we should be able to omit SNMP information when we add an device via the API.
https://github.com/librenms/librenms/blob/master/doc/API/Devices.md#add_device

When using the option "force_add", example call: "_curl -X POST -d '{"hostname":"r-mydevice-hub.myorg.net", "force_add":"true"}' -H 'X-Auth-Token: <redacted>' http://librenms.myorg.net/api/v0/devices_"

The device will never get discoverd. A TCP Dump shows that we are trying to poll the device, but we are sending an **empty** community string.

My understanding is that LibreNMS should use our Global SNMP settings. 

This is the same issue that was reported in #15636 , but it seems that the issue was not fixed, just worked around.

### Output of ./validate.php

```txt
$ /opt/librenms/validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.7.0-44-g9455173ed (2024-08-12T19:21:14+02:00)
DB Schema | 2024_07_19_120719_update_ports_stack_table (296)
PHP       | 8.2.20
Python    | 3.11.2
Database  | MariaDB 10.11.6-MariaDB-0+deb12u1
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Composer Version: 2.7.7
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
$
```

**Comment by murrant** [comment]
snmp community / authentication is required when using force adding.  LibreNMS is unable to probe for the correct info when force_add is enabled.
