### ISSUE TITLE
Cannot use /api/v0/devices/mydevices/ports/Gigabit.....

### ISSUE THREAD

**Issue by StoBlock** [librenms/librenms#16286]
### The problem

Im looking for how to use the path over API to call informations about GigabitEthernet1/0/1 for example
http://librenms.local/api/v0/devices/mydevice/ports/GigabitEthernet1/0/1
return : 0 series returned, that's normal with the "/" in the GigabitEthernet1/0/1 the api call seems to be broken

i'm trying to do that with an simple curl with get request and API token

im trying to do that for recover tagged vlan on specific switch interface. If its not possible how can i make that ?

Thanks

### Output of ./validate.php

```txt
its just for know how api endpoint works for GigabitEthernet, all works fine
```

**Comment by PipoCanaja** [comment]
Hi @StoBlock 
You are right. And you should use the PortID instead of the name in that case.

**Comment by murrant** [comment]
You need to url encode the / I think (%2F)

As @PipoCanaja said port_id is better.
