### ISSUE TITLE
Alerts no longer sending notifications as a result of #16281

### ISSUE THREAD

**Issue by lwhitworth** [librenms/librenms#16295]
### The problem

Noticed we were no longer receiving notifications when rules were firiing.   Looking at the commit history I found https://github.com/librenms/librenms/commit/9455173edce6971777cf6666d540eeeaf6201920, reverted that change and alerts are now being recieved again.  

We are using an API transport but I also setup a telegram one to test and this didn't work either until the above change was reverted.  Once that was done both the API and the telegram one began working as expected.

### Output of ./validate.php

```txt
-
```

### What was the last working version of LibreNMS?

24.7.0

**Comment by PipoCanaja** [comment]
Hi @lwhitworth 
Can you tell us a little bit more about your setup ? I have a few LibreNMS servers and they run alerts perfectly (API, Email, Teams, etc) . So there must be something in your setup that is different from most of the other (working) setups.

**Comment by lwhitworth** [comment]
Sure thing, running on a Ubuntu 22.04 host, I've uploaded an image of the rule defintion, the transport we usually use is nothing special, just a POST to a Zulip server

```
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.8.0-4-g00124e1e6 (2024-08-16T14:04:50+01:00)
DB Schema | 2024_07_19_120719_update_ports_stack_table (296)
PHP       | 8.1.2-1ubuntu2.18
Python    | 3.10.12
Database  | MariaDB 10.6.18-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================
```

![librenms](https://github.com/user-attachments/assets/c4856beb-6465-40fc-9602-78fc5a57f852)

Let me know what else I can supply to help

**Comment by lwhitworth** [comment]
On closer inspection, it appears that _some_ of our alerts are still working, e.g. 

![librenms2](https://github.com/user-attachments/assets/22fdc4ea-f05e-4f94-9d2f-31ac2cb886d7)

So probably an issue with how certain rules can run and not generate enough to satisfy:

`isset($alert['details']['count'])`

**Comment by HermoXanti** [comment]
Hi,

I have the same issue, some alerts are triggering others not.
When I remove the change && isset($alert['details']['count']) in /opt/librenms/LibreNMS/Alert/RunAlerts.php everything works again.

Regards

**Comment by kruczek8989** [comment]
I have the same problem, but the above solution does not help and some alerts still do not work.

**Comment by nltommynl** [comment]
As mentioned by others, we are also experiencing this issue on three different instances.

We have two types of alert rules configured:

Max Alerts -1, Delay 20m, Interval 10m —> this is sent once and then no more.
Max Alerts -1, Delay 0, Interval 10m —> this is not sent at all.

**Comment by kruczek8989** [comment]
In my case it looks like this

Alert device not working
Max Alerts -1, Delay 5m, Interval 60m <- ​​no alerts, but only for some devices (LAN switches) - other devices, e.g. VoIP telephones receive an UP/DOWN alert

Alert device has been restarted
Max Alerts 1, Delay 0, Interval 0 <- receives one alert correctly as before.

**Comment by PipoCanaja** [comment]
@murrant : Could you have a look at this issue ? We may have a change of behaviour here.

**Comment by varesa** [comment]
+1 For this.

We have an alert rule with a config like:
![screenshot_2024-08-21-160104](https://github.com/user-attachments/assets/34c2c590-5d24-4ae0-89eb-c68e71003e5f)

This alert becomes `alerts.open=0` and gets ignored by RunAlerts.php, since the only way out of `open = 0` seems to be a state change (AlertState::BETTER or AlertState::WORSE).

A `print_r($alert)`: from RunAlerts.php:
```
Array
(
    [id] => 104384
    [rule_id] => 43
    [device_id] => 413
    [state] => 1
    [details] => Array
        (
            [contacts] => Array(<redacted>)
            [rule] => Array
                (
                    [0] => Array
                        (
                            [device_id] => 413
                            [inserted] => 2020-12-16 13:36:37
                            [hostname] => redacted
                            [sysName] => Dummy device for heartbeating
                            [display] =>
                            [ip] => 1.2.3.4
                            [overwrite_ip] =>
                            [community] =>
                            [authlevel] =>
                            [authname] =>
                            [authpass] =>
                            [authalgo] =>
                            [cryptopass] =>
                            [cryptoalgo] =>
                            [snmpver] => v2c
                            [port] => 161
                            [transport] => udp
                            [timeout] =>
                            [retries] =>
                            [snmp_disable] => 1
                            [bgpLocalAs] =>
                            [sysObjectID] =>
                            [sysDescr] =>
                            [sysContact] =>
                            [version] =>
                            [hardware] =>
                            [features] =>
                            [location_id] =>
                            [os] => ping
                            [status] => 1
                            [status_reason] =>
                            [ignore] => 0
                            [disabled] => 0
                            [uptime] =>
                            [agent_uptime] => 0
                            [last_polled] => 2024-08-21 15:50:58
                            [last_poll_attempted] =>
                            [last_polled_timetaken] => 1.122339963913
                            [last_discovered_timetaken] => 0.001
                            [last_discovered] => 2024-08-21 12:54:52
                            [last_ping] => 2024-08-21 15:50:57
                            [last_ping_timetaken] => 0.028
                            [purpose] =>
                            [type] => server
                            [serial] =>
                            [icon] =>
                            [poller_group] => 0
                            [override_sysLocation] => 0
                            [notes] =>
                            [port_association_mode] => 1
                            [max_depth] => 0
                            [disable_notify] => 0
                            [ignore_status] => 0
                        )

                )

            [interval] => 1724244842
        )

    [time_logged] => 2020-12-16 14:41:12
    [rule] =>
    [severity] => critical
    [extra] => {"mute":false,"count":"-1","delay":60,"invert":false,"interval":300,"recovery":true,"options":{"override_query":null}}
    [name] => Heartbeat
    [query] => SELECT * FROM devices WHERE (devices.device_id = ?) AND (devices.disabled = 0 && devices.ignore = 0) = 1 AND devices.ignore != 1
    [builder] => {"condition":"AND","rules":[{"id":"macros.device","field":"macros.device","type":"integer","input":"radio","operator":"equal","value":"1"},{"id":"devices.ignore","field":"devices.ignore","type":"string","input":"text","operator":"not_equal","value":"1"}],"valid":true}
    [proc] =>
    [alert_id] => 6157
    [alerted] => 1
    [note] => Pidä un-ackina. Käytetään OpsGenien heartbeat-valvontaan
    [info] =>
)
```

The property `$alert['details']['count'] does not appear set, so this does not get hit:
```
                if (in_array($alert['state'], [AlertState::ACTIVE, AlertState::WORSE, AlertState::BETTER]) && ! empty($rextra['count']) && isset($alert['details']['count']) && ($rextra['count'] == -1 || $alert['details']['count']++ < $rextra['count'])) {
                    if ($alert['details']['count'] < $rextra['count']) {
                        $noacc = true;
                    }

                    $updet = true;
                    $noiss = false;
                }
```

and `$noacc` remains `false`

and the alert gets closed:
```
            if (! $noacc) {
                dbUpdate(['open' => 0], 'alerts', 'rule_id = ? && device_id = ?', [$alert['rule_id'], $alert['device_id']]);
            }
```
