### ISSUE TITLE
Reboot Alert-Rule does not trigger

### ISSUE THREAD

**Issue by Ftelf** [librenms/librenms#1630]
LibreNMS shoul be able to detect it's own system but it can't. I can add a localhost to be monitored. I can see a correct uptime after restart, but LibreNMS should send an alert that it has been rebooted.

**Comment by dcslv** [comment]
This is where a custom sensor from the graph page would be useful.
If it were available it would be possible to make a rule that if uptime is less than some number throw an alert

**Comment by laf** [comment]
You can add an alert for reboots, I suppose we could enable the default alert rules and we already ask users to add localhost

**Comment by Ftelf** [comment]
Yes, the alert is triggered on localhost once rebooted, but the email is not sent afterwards.

**Comment by f0o** [comment]
There is no difference between alerts triggered on localhost or elsewhere. Alerts are being emailed if configured so. It sounds more likely that something is fuzzy with your setup if it cant email.

I'm getting emails for localhost reboots.

For true selfmonitoring one would also require a proper HA stack that is capable of failovers. Corosync does a good job for me, sends me state-changes and relocates the crons to my failover host.

**Comment by laf** [comment]
Potentially the options you have for the reboot alert rule @Ftelf?

**Comment by Ftelf** [comment]
I have checked the librenms system and it looks like the alerts have stopped working since some git update.
I have just rebooted one of the other device.
http://fii.cz/smjsnqx

http://fii.cz/pftypsz
You can see that at 2015-07-26 there were mail alert, but this time not. I did not changed anything in the alert rules. I did not touched the librenms system for some time, so this is mystery for me.
http://fii.cz/dqteyge

http://fii.cz/ruwhfk

**Comment by laf** [comment]
Can you post a screenshot of your reboot rule please?

**Comment by Ftelf** [comment]
It's the third fii.cz image above http://fii.cz/dqteyge.

**Comment by laf** [comment]
@Ftelf Ok standard one, their is every chance that rule hasn't run due to timings. For example:

Poller happens at 09:00 - uptime is 16 days
Device is rebooted at 09:04 but doesn't come back up till 09:06 so is missed from polling
Poller next happens at 09:11 as the device isn't the first to be polled. The device has now been up for 301 seconds.

You could change it from being rebooted in the last 5 minutes to 10 minutes.

**Comment by Ftelf** [comment]
I have changed the limit to 600 seconds.
http://fii.cz/htpjque
no change

I have found the solution. For some reason with some update the
$config['alerts']['email']['enable'] defaulted to false

Now I have to explicitely put
$config['alerts']['email']['enable'] = true
into config.php

I'll also try to reboot the librenms system and report back

**Comment by laf** [comment]
@Ftelf are you running alerts.php via cron?

Mysql strict mode enabled? (run ./validate.php)

After a reboot, run ./poller.php -h HOSTNAME -d -r -m system

**Comment by Ftelf** [comment]
I have a preinstalled vmware image with librenms, never changed anything complex.
http://fii.cz/xnktuu

http://fii.cz/dybpmjev

**Comment by laf** [comment]
@Ftelf 

We deprecated the old alerting system in full on the 1st of August, we posted on the mailing list a few times to warn users + it's in the irc channel.

Glad it's now working for you.

**Comment by Ftelf** [comment]
When the %devices.uptime has been changed back to 300 it stopped working again. I'll try to update the alerting system as suggested.

**Comment by laf** [comment]
After a reboot, run ./poller.php -h HOSTNAME -d -r -m system

**Comment by Ftelf** [comment]
I have setted the email configuration using the web forms exactly as I have in config.php. commented #$config['alerts']['email']['enable']       = true;
since I understood is the old email alerting.

So the email alerting setting is now in the web based configuration, but why there is a paragraph about email configuration in config.php ?
http://docs.librenms.org/Extensions/Alerting/

http://fii.cz/sqctd

So the email config in config.php could be completely removed, right ?

**Comment by laf** [comment]
If you use the web ui to configure alert settings and transports then I'd suggest removing anything from config.php to do with alerting.

**Comment by Ftelf** [comment]
I do not know how the source has changed since about the August, but I have nice Up-Down email alerts, port up-down email alerts. But no matter what I have zero reboot alerts. I have tried to reboot some devices like 10 times. It is alerted only in web, but zero email alerts. I have tried to manually run the ./poller.php, right after the reboot. This is the only time I got reboot email alert. but the rest, none.

**Comment by f0o** [comment]
@Ftelf can you remove the delay-option from your reboot-rule and increase the rule-condition to something like:
`%devices.uptime < "450" && %macros.device = "1"`

That will alert if the uptime of a device is smaller than 7:30 mins

**Comment by Ftelf** [comment]
So, I have updated the reboot rule.
http://fii.cz/jtndnc
First note. You are unable to remove the Delay option using web UI. When cleaned, the default value of 5 minutes is saved instead. Also when you just open the Rule with blank option and just resave, your Rule is scrambled.
So I had to edit it using phpmyadmin directly in database.

Now the result. The reboot is now triggered twice.
http://fii.cz/knpyhzce

I miss the pre-1.August code. It was 100% accurate.

**Comment by f0o** [comment]
Well sad to disappoint you but I'm not aware of any code changes in that matter for a couple of months

**Comment by f0o** [comment]
Worth to mention, I cant reproduce your error :/
The twice is odd however.

**Comment by Ftelf** [comment]
I can provide both ssh and web access to the machine if arranged by private chat. Also a device which could be rebooted without consequences.

**Comment by f0o** [comment]
@Ftelf please join IRC for this, my nick is the same as here on GitHub (f0o).

**Comment by f0o** [comment]
Should be dealt with in #1685 - Reopen issue if not
