### ISSUE TITLE
Top Menu -> Devices -> Geo Locations -> List shows pre-rename location

### ISSUE THREAD

**Issue by davidngrc** [librenms/librenms#16311]
### The problem

in many of the snmp device, we only giving a password with ReadOnly permission.
for example:
Router1, snmp v2c, read-only community sting is: public

we add it to LibreNMS
and we found out the location string is,  Unknown

but we know it is located at 10F server room, so we go
Top Menu -> Devices -> All Devices -> choose the device -> right side: Gear icon -> Device setting -> Override sysLocation, set it to "ON" -> and fill  "10F Server Room" in the below input box.

then we go to
1) Top Menu -> Devices -> Geo Locations -> List
2) Top Menu -> Devices -> All Devices -> List -> click the drop down menu "All Location"

"Unknown" and "10F Server Room" will both listed there.
it should be just "10F Server Room", 
"Unknown" should NOT be listed there.

### Output of ./validate.php

```txt
valid, latest version
```

**Comment by murrant** [comment]
Location still exists, even if no devices are attached to it.  You can just delete it.
