### ISSUE TITLE
Alerting still having issues

### ISSUE THREAD

**Issue by danb223** [librenms/librenms#16326]
### The problem

After 24.8.0 we had various issues with alerting, this was supposedly fixed in [16309](https://github.com/librenms/librenms/pull/16309) however we are still seeing issues. 
If I revert the file back to 24.7.0 all appears to work fine again.
Example of a fairly simple rule and an alert, the initial alert is triggered after the delay, but then appears to ignore the interval and no further alert is generated.
![alert](https://github.com/user-attachments/assets/bdf68fdc-647d-4ec2-a2c8-ddd40fad9a7c)

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.8.1 (2024-08-21T22:50:00-04:00)
DB Schema | 2024_07_19_120719_update_ports_stack_table (299)
PHP       | 8.1.27
Python    | 3.6.8
Database  | MariaDB 10.5.24-MariaDB
RRDTool   | 1.8.0
SNMP      | 5.7.2
===========================================

[OK]    Composer Version: 2.7.8
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

24.7.0

**Comment by kruczek8989** [comment]
I have the same problem too.
The first alert is generated and sent, but if the failure lasts longer, subsequent alerts depending on the interval and with the "max alerts = -1" parameter are not generated.

**Comment by nltommynl** [comment]
> I have the same problem too. The first alert is generated and sent, but if the failure lasts longer, subsequent alerts depending on the interval and with the "max alerts = -1" parameter are not generated.

The exact same scenario is the case with us.

**Comment by murrant** [comment]
Does #16358 fix the issue?

**Comment by danb223** [comment]
Initial testing it does appear to

**Comment by Calvario** [comment]
The alerts that got affected by 24.8 & 24.8.1 will not get resolved as they got modified on the database.
The fix will only work for new alerts.
@danb223 did you try #16358 or #16359 ?

**Comment by danb223** [comment]
I tried #16359 however #16358 was effectively rolling back to 24.7.0 version which we have also been running since I created this issue, which works also.
