### ISSUE TITLE
[Draytek Vigor167] wrong xDSL detection

### ISSUE THREAD

**Issue by Commifreak** [librenms/librenms#16339]
### The problem

I added my Vigor167 and the xDSL page shows me no data:
![grafik](https://github.com/user-attachments/assets/4be8491e-88bc-46ce-a59e-42deec7e12c7)

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.8.0 (2024-08-25T23:45:45+02:00)
DB Schema | 2024_07_19_120719_update_ports_stack_table (296)
PHP       | 8.2.20
Python    | 3.11.9
Database  | MySQL 8.4.2
RRDTool   | 1.8.0
SNMP      | 5.9.4
===========================================

[OK]    Installed from package; no Composer required
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No python wrapper pollers found
[WARN]  Using database for locking, you should set CACHE_DRIVER=redis
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Non-git install, updates are manual or from package
```

### Device info

Draytek Vigor 167

### Discovery output

https://pastebin.com/g7TifnDb (otherwise it were too long)

### Poller output

https://pastebin.com/24ZL3qsX (otherwise too long)

**Comment by murrant** [comment]
From the log output: Failed to discover this port, ifIndex invalid.

Looking up above at `adslLineConfProfile[0] = VDSL2` This says the ifIndex is 0, which is indeed invald (all ifIndex must be > 0) And if you look further up still, you can see your ifIndex range from 1-14.

LibreNMS cannot work around this kind of broken, sorry.  Try updating your device's firmware or filing a bug request with the vendor.

**Comment by Commifreak** [comment]
I try to fill a bug to DrayTek then. Thanks!
