### ISSUE TITLE
Can't install in web server subdirectory

### ISSUE THREAD

**Issue by miken32** [librenms/librenms#1633]
Our desire is to have LibreNMS installed in a subdirectory (e.g. https://server.internal/librenms/) but this is not supported!

* `html/.htaccess` needs `RewriteBase` changed
* `html/includes/vars.inc.php` needs `$_SERVER["REQUEST_URI"]` altered
* `html/install.php` shouldn't assume it's in `$_SERVER["DOCUMENT_ROOT"]` and use `__DIR__` instead. It should also have the `<base>` element removed.
* Many HTML files reference images like `/images/foo.png` and should have the leading slash removed

The change to `install.php` is simple enough, as are the changes to account for the images directory, and `vars.inc.php` can account for the value of `$config["base_url"]` to change things accordingly:
```php
    $base_url = parse_url($config["base_url"]);
    $segments = explode('/', trim(str_replace($base_url["path"], "", $_SERVER['REQUEST_URI']), '/'));
```
But `.htaccess` would likely need to be created at installation.

**Comment by laf** [comment]
We have an open issue #285 with regards to this.

I've heard on irc someone was working on support for this but nothing further - I'm pretty certain more than the above needs changing. If this is something you'd like to contribute to then we would be willing to accept the changes needed.

**Comment by miken32** [comment]
Thanks; I looked through the open issues list but I guess I didn't look hard enough! I'll close this issue and start watching #285.

I'm just working out the bugs to get this running (battling with SELinux right now) and will look at doing a pull request once I get things working.

**Comment by laf** [comment]
Thanks @miken32 - it wasn't you on irc talking about this was it?

**Comment by miken32** [comment]
Nope, despite being on the internet for 22 years, I've never IRC'd in my life!

**Comment by paulgear** [comment]
Pretty sure that it was @LeslieCarr asking about it a while back. Leslie - it may be a case of too little, too late, but #1645 has the fix.

**Comment by laf** [comment]
@paulgear yeah I linked to that issue above but someone else on irc in the last week has been talking about it and also done some code updates.
