### ISSUE TITLE
Error with the IfAlias script

### ISSUE THREAD

**Issue by mzambrano-tc** [librenms/librenms#16387]
### The problem

The IfAlias use the output of the command "ip link". However, the output is not always sorted by the interface index.
When the "ip link" out is not sorted, you can find errors reported by Snmp like this:

```
IF-MIB::ifAlias.2670 = STRING:
IF-MIB::ifAlias.2545 = STRING:
Error: OID not increasing: IF-MIB::ifAlias.2670
 >= IF-MIB::ifAlias.2545
 ```
 
 to solve this replace the line 22 in `scripts/ifAlias` file
 
 - IP_LINK="$(ip link)"
 + IP_LINK="$(ip -o link | sort -n)"

### Output of ./validate.php

```txt
N/A
```

**Comment by murrant** [comment]
OID not increasing is a bug in your device's snmp implementation.
