### ISSUE TITLE
Collecte data from Cisco CIMC stop working

### ISSUE THREAD

**Issue by elric72** [librenms/librenms#16383]
### The problem

After the commit 9d35fbc6a7f1b68cda04e17598140ea4086551e9 ([Entity Physical discovery: Rewrite to modern style) LibreNMS stop collecting data from CIMC.
This is normal if I read the description of the post : 
...
Skip cimc for now... no test data
...

I have several CIMC so I can give you data. I just need some help to give you exactly what you need.

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS | 24.8.0-60-g64241dbdf (2024-09-09T13:12:42+02:00)
DB Schema | 2024_08_27_182000_ports_statistics_table_rev_length (299)
PHP | 8.1.14
Python | 3.9.18
Database | MariaDB 10.5.22-MariaDB
RRDTool | 1.7.2
SNMP | 5.9.1
===========================================

[OK] Composer Version: 2.7.9
[OK] Dependencies up-to-date.
[OK] Database connection successful
[OK] Database connection successful
[OK] Database Schema is current
[OK] SQL Server meets minimum requirements
[OK] lower_case_table_names is enabled
[OK] MySQL engine is optimal
[OK] Database and column collations are correct
[OK] Database schema correct
[OK] MySQL and PHP time match
[OK] Active pollers found
[OK] Dispatcher Service not detected
[OK] Locks are functional
[OK] Python poller wrapper is polling
[OK] Redis is unavailable
[OK] rrdtool version ok
[OK] Connected to rrdcached
```

### What was the last working version of LibreNMS?

24.8.0-60-g64241dbdf

**Comment by PipoCanaja** [comment]
Hi @elric72 
Could you please collect the snmpwalk data : 
`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh`

If possible, use a test device, or review (and remove) any sensitive data that could be in the CIMC. 

Then post the link here. That whould allow integration of CIMC back in LibreNMS. 

Ths

**Comment by murrant** [comment]
@elric72 Correct, it was intentionally removed because the code was incomprehensible and there was no test data for it.

PR to add support will be accepted, but as of now, this is a feature request.
