### ISSUE TITLE
Forcepoint Standard MIB issue

### ISSUE THREAD

**Issue by ilymare** [librenms/librenms#16394]
### The problem

Since the v7.1.3 and newer version of the NGFW firmware, the names of the forcepoint firewalls interfaces doesnt display correctly. Instead of displaying eth0_0, the interface name polled is 'Intel Corporation I210 Gigabit Network Connection'. After making a snmpwalk on the new version of NGFW and a version before the v7.1.3 we can see the difference on the Standard MIB :

on a v6.10.8 :
• .1.3.6.1.2.1.2.2.1.1.2 (ifIndex) => '2',
• .1.3.6.1.2.1.2.2.1.2.2 (ifDescr) => 'eth0_0',

on a 7.1.3 :
• .1.3.6.1.2.1.2.2.1.1.2 (ifIndex) => '2',
• .1.3.6.1.2.1.2.2.1.2.2 (ifDescr) => 'Intel Corporation I210 Gigabit Network Connection',

This choice of changing the field ifDesc on the standard MIB since the v7.1.3 has been confirm to us by a case opened at forcepoint support :

> In earlier versions than 7.1.3 the behavior was incorrect. When requesting ifDescr the SNMP always returned ifName instead. In 7.1.3 and newer versions this has been fixed to match the correct behavior of the IF-MIB standard:
ifDescr OBJECT-TYPE
SYNTAX DisplayString (SIZE (0..255))
MAX-ACCESS read-only
STATUS current
::= { ifEntry 2 }
If you wish to see the interface name, you need to change the SNMP monitoring to query for ifName instead of ifDescr.

Is there a way to integrate that change so that the interface are correctly polled ?

Thanks in advance.
QD

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.7.0 (2024-07-17T08:35:08+02:00)
DB Schema | 2024_07_13_133839_modify_ent_physical_defaults (295)
PHP       | 8.1.2-1ubuntu2.18
Python    | 3.10.12
Database  | MariaDB 10.6.18-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Installed from package; no Composer required
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[WARN]  Your tmp directory (/tmp/user/1111) is not set to 777 so graphs most likely won't be generated
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[INFO]  Could not read cron files
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
[WARN]  Non-git install, updates are manual or from package
```

### What was the last working version of LibreNMS?

24.7.0

### Device info

Forcepoint FE 2205-0-C1

### Discovery output

https://github.com/user-attachments/files/16989713/discovery.txt

### Poller output

https://github.com/user-attachments/files/16989715/poller.txt

**Comment by ilymare** [comment]
[discovery.txt](https://github.com/user-attachments/files/16989713/discovery.txt)
[poller.txt](https://github.com/user-attachments/files/16989715/poller.txt)

**Comment by PipoCanaja** [comment]
Hi @ilymare 
You can try to add `ifname: true` after `os: forcepoint-fe` in file `~/includes/definitions/forcepoint-fe.yaml`. And force run a discovery of your device in debug mode like so : `./discovery.php -v -d -h <device_id>`. 
Let us know if it fixes the issue. If yes, next step is to check how it impacts older versions (before v7.1.3). If it works in both cases (as I would imagine it does) then you can submit a PR to fix this issue in LibreNMS.

**Comment by ilymare** [comment]
Hi @PipoCanaja

It works, thanks for the solution. I dont think older version are impacted. if I am not mistaken the forcepoint-fe script works for v7.1 and newer version. the older version are taking care by the "old" forcepoint script.

**Comment by murrant** [comment]
FYI, the snmp data given in v7.1 seems correct and older versions were broken.
ifName should countain the string `eth0_0`
