### ISSUE TITLE
No transceiver optical dbm monitoring on ios-xr devices

### ISSUE THREAD

**Issue by mmarchand** [librenms/librenms#1641]
Hi,

Is it expected to not monitor transceiver budget in "decibels" on IOS-XR devices ? (ASR9k here)
I only get the power levels in Voltage, Current, Power (Watts) and Temperature but no dbms graphs like I can get on 4500X devices (IOS-XE there)
for a 4500x device I have "/tab=health/metric=dbm/"  graphs available but not on ASR9k (this is the case for 3 different IOS-XR versions at least)

thanks
Mik

**Comment by Rosiak** [comment]
Would it be possible to get a walk of CISCO-ENTITY-SENSOR-MIB? 
I only have access to a XE device /:

**Comment by mmarchand** [comment]
Sure, here it is : http://mx.mikmak.fr/a9k1-sensor.txt

**Comment by Rosiak** [comment]
Is this with the CISCO-ENTITY-SENSOR-MIB loaded?

**Comment by mmarchand** [comment]
how do you do that ? :)

**Comment by mmarchand** [comment]
here it is : 
http://mx.mikmak.fr/a9k1-sensor-2.txt

**Comment by Rosiak** [comment]
No dBm info there at all.
Can you please try using this updated MIB? 
ftp://ftp.cisco.com/pub/mibs/v2/CISCO-ENTITY-SENSOR-MIB.my

**Comment by mmarchand** [comment]
here is the updated walk : 
http://mx.mikmak.fr/a9k1-sensor-3.txt

**Comment by mmarchand** [comment]
I asked to Cisco experts, it seems to be doable https://supportforums.cisco.com/discussion/12577221/snmp-polling-optical-budget-dbm#comment-10706751 :)

**Comment by mmarchand** [comment]
Ok so in the end IOS-XR does not expose dbm values through snmp, 
one needs to convert the mWatts to dbm with 10*log(mW) = dbm formula,
is there a way we can add graphs for this ? (I find dbm to be much more easy to understand than mWatts in regards to optical budgets)

**Comment by laf** [comment]
What I expect we can do here is to check for IOS-XR in the includes/discovery/cisco-entity-sensor.inc.php is to add a static map for dbm to watts and perform the required calculation.

Is this something you can do @mmarchand?
