### ISSUE TITLE
Feature request: Colour Coded IRC Messages

### ISSUE THREAD

**Issue by gadago** [librenms/librenms#1642]
We currently make use of the librenms IRC bot to feed alerts into an IRC channel. It would be really nice to have these message colour coded inline with ones shown in the Alertlog entries in the WebUI (green, tick, red cross, up/down amber icons).

So I imagine something along the lines of:

Critical = Light Red (255,0,0)
Warning = Yellow (255,255,0)
OK = Green (0,147,0)
Got worse = Orange (252,127,0)
Got better = Light orange (not sure on RGB code)

What do people think?

**Comment by f0o** [comment]
IRC is not RGB'able sadly, But we can add some colors :)
