### ISSUE TITLE
Route [vlans.index] not defined

### ISSUE THREAD

**Issue by michalzahor** [librenms/librenms#16440]
### The problem

On the web page (librenms) message appears: **Whoops, looks like something went wrong. Check your librenms.log.**

In the librenms.log I can see those lines every time I try to load librenms web page.

_Route [vlans.index] not defined. {"view":{"view":"/opt/librenms/resources/views/layouts/menu.blade.php","data":[]},"userId":1,"exception":"[object] (Spatie\\LaravelIgnition\\E>
[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Route [vlans.index] not defined. at /opt/librenms/vendor/laravel/framew>_

**Recently we have replaced switch (same vendor, different model) - switch is running with the same IP as the one before and switch object in the librenms was not removed before switch replacement.**

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.8.0-92-ga6c195ee9 (2024-09-26T20:39:25+02:00)
DB Schema | 2024_08_27_182000_ports_statistics_table_rev_length (299)
PHP       | 8.2.20
Python    | 3.11.2
Database  | MariaDB 10.11.6-MariaDB-0+deb12u1
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Composer Version: 2.7.9
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Your local git contains modified files, this could prevent automatic updates.
	[FIX]:
	You can fix this with ./scripts/github-remove
	Modified Files:
	 bootstrap/cache/.gitignore
	 logs/.gitignore
	 rrd/.gitignore
	 storage/app/.gitignore
	 storage/app/public/.gitignore
	 storage/debugbar/.gitignore
	 storage/framework/cache/.gitignore
	 storage/framework/cache/data/.gitignore
	 storage/framework/sessions/.gitignore
	 storage/framework/testing/.gitignore
	 storage/framework/views/.gitignore
	 storage/logs/.gitignore
```

### What was the last working version of LibreNMS?

24.8.0-92

**Comment by laf** [comment]
Try `php artisan route:clear`

I'd clean up your files that are being reported as modified as well.

**Comment by michalzahor** [comment]
Thank you,

running `php artisan route:clear` solved the issue

**Comment by murrant** [comment]
Looks like he is/was testing a PR...
