### ISSUE TITLE
Missing second temperature sensor for ServersCheck

### ISSUE THREAD

**Issue by tomck** [librenms/librenms#16476]
### The problem

Related to #7383, I'm not seeing both temperature sensors show up, only one. It's annoying. There is a second annoying feature which is that it doesn't know that it's Fahrenheit (I wish the other tech would be OK with using Celsius but that's out of my control) so librenms displays it as being insanely hot in Celsius. But I don't know if that's fixable because nothing indicates the unit of measurement in the snmpwalk.

The problem is `sensor1name.0 = "ac temp"` shows up in the discovery but that measurement isn't listed in librenms. `sensor3name.0 = "Ext. Temp1"` does show up.  The humidity line does show up too.

Kindly ignore the PHP error in validate.php, this issue has been a problem for years and I just haven't gotten around to reporting. Also ignore the poller not working, it is working, I don't know why it says this.

Had to use pastebin as body for comment is too long.

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.9.1-7-gd4bd71a57 (2024-10-01T17:40:46-05:00)
DB Schema | 2024_03_27_123152_create_transceivers_table (300)
PHP       | 8.1.11
Python    | 3.6.8
Database  | MariaDB 10.3.28-MariaDB
RRDTool   | 1.7.0
SNMP      | 5.8
===========================================

[OK]    Composer Version: 2.7.9
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[WARN]  PHP version 8.2 is the minimum supported version as of October, 2024. We recommend you update PHP to a supported version (8.3 suggested) to continue to receive updates. If you do not update PHP, LibreNMS will continue to function but stop receiving bug fixes and updates.
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[FAIL]  Some poller nodes have not checked in recently
        Inactive Nodes:
         xms
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### Device info

ServersCheck SensorGateway HW v5.1

### Discovery output

```txt
https://pastebin.com/4qQy1FCE
```

### Poller output

```txt
https://pastebin.com/igScpiJ8
```

**Comment by laf** [comment]
It's because the name of that sensor is lowercased temp and we check for Temp.

This patch should correct that, can you try it please: https://gist.githubusercontent.com/laf/0ba22db4d5da055b4563d8d61e7a9493/raw/6aaf03183b99b5e66f2dbc529f5902db6dc52e27/gistfile1.txt
