### ISSUE TITLE
New feature global VLAN ports page causes long running SQL queries and a high load

### ISSUE THREAD

**Issue by stefanl234** [librenms/librenms#16472]
### The problem

If selected, the new feature Global VLAN ports page #16415 causes several long running SQL queries on our server and a high load.

The command `show full processlist` on the MariaDB command line shows several queries like the following, which run for a long time and do not seem to stop:

`select count(*) as aggregate from `ports` left join `ports_vlans` on `ports`.`port_id` = `ports_vlans`.`port_id` where (`ifVlan` = ? or `ports_vlans`.`vlan` = ?)`

We've got a very high number of VLANs in our environment. Maybe that's a possible cause for this issue.

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.9.1-3-g2726787f9 (2024-09-30T19:32:24+02:00)
DB Schema | 2024_03_27_123152_create_transceivers_table (300)
PHP       | 8.2.20
Python    | 3.11.2
Database  | MariaDB 10.11.6-MariaDB-0+deb12u1
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Composer Version: 2.7.9
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
[WARN]  Your local git contains modified files, this could prevent automatic updates.
	[FIX]:
	You can fix this with ./scripts/github-remove
	Modified Files:
	 config/snmptraps.php
```

**Comment by elherr** [comment]
Running into the same issue here.  We have around 3000 VLANs spread across 409 Cisco boxes.  Cherry picking PR 16484 did not seem to fix.

`===========================================
Component | Version
--------- | -------
LibreNMS  | 24.9.1 (2024-09-29T16:40:22-07:00)
DB Schema | 2024_08_27_182000_ports_statistics_table_rev_length (300)
PHP       | 8.3.12
Python    | 3.10.12
Database  | MariaDB 10.6.18-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.8.0
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]:
        You can fix this with ./scripts/github-remove
        Modified Files:
         app/Http/Controllers/Device/Tabs/ShowConfigController.php
         includes/html/pages/device/showconfig.inc.php
`
