### ISSUE TITLE
Alerts not more shown/empty in Alert Widget, also not in Alert Tab on Device

### ISSUE THREAD

**Issue by SourceDoctor** [librenms/librenms#16491]
### The problem

Alerts are not more shown in Alert Widget.
Also they are not shown in Alert Tab on Device.
But on taking a look into Alert Rules, there are Rules marked as matched/alerted.

Alert Rules:
![image](https://github.com/user-attachments/assets/36800255-f3a9-4838-b61b-b8999c1df178)

Alert Tab on Device:
![image](https://github.com/user-attachments/assets/a77da58f-2b61-4646-8310-d691cabcc258)

Alert Widget:
![image](https://github.com/user-attachments/assets/de3d0de4-c330-4de8-b199-b736c1849350)

i tried to delete Browser Cache, but problem still exists.
Problems exists on several different Browser

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.9.1-10-g32f9effd8 (2024-10-03T00:28:09+02:00)
DB Schema | 2024_03_27_123152_create_transceivers_table (300)
PHP       | 8.2.20
Python    | 3.11.2
Database  | MariaDB 10.11.6-MariaDB-0+deb12u1
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Composer Version: 2.7.9
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    Python wrapper cron entry is not present
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

**Comment by laf** [comment]
The demo is on that version and seems fine. Check your developer console within the browser and see if anything shows there

**Comment by SourceDoctor** [comment]
ah ok found it, 
i've got a redirect on local network, with it i've a Allow-Origin - Problem now

So there is no problem with librenms itself.

Thx for the hint @laf
