### ISSUE TITLE
Standard method for adding device components to the database

### ISSUE THREAD

**Issue by adaniels21487** [librenms/librenms#1650]
Hi Team,

I am looking into how one would add a new component to the database, but I can't find a standard method of doing so.
I see database tables for: several types of ports, ospf, bgp, slas, and many others, but nothing generic.

To address this, I propose to build a set of tables that could hold this type of information in a generic manner to allow easy expansion for new types.
The new DB Tables would be something like:
- component: id, device, type, component_status, system_status
- component_type: id, name, description
- component_prefs: id, component, attribute, value

The following features would be written:
- Standard interfaces to get and set information from the database
- Integration to the Alerting system, alert on any component
- Integration to the API system, query any component
- Ability to disable polling/alerting on any component

In the future any new 'component' that used this system would only need to create a unique entry in the component_type table. 

Is this something the community would be interested in?

Thanks,
Aaron

**Comment by laf** [comment]
Hey @adaniels21487 

Can you show a use case quickly as in what data you would see in those tables, feel free to post it as a bunch of SQL so we can set the tables up and see how it could work.

**Comment by adaniels21487** [comment]
Hi @laf.
Apologies for the long post...
So, the tables currently look like this:
```SQL
CREATE TABLE `component_type` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID for each component',
  `name` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Unique identifier for the type of component',
  `description` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Description of the type of component',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='type of component'

CREATE TABLE `component` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID for each component, unique index',
  `device` int(11) unsigned NOT NULL COMMENT 'device_id from the devices table',
  `type` int(11) unsigned NOT NULL COMMENT 'id from the component_type table',
  `component_status` int(11) DEFAULT NULL COMMENT 'The status of the component, retreived from the device',
  `admin_status` int(11) DEFAULT NULL COMMENT 'The status of the component, as configured in LibreNMS',
  PRIMARY KEY (`id`),
  KEY `device` (`device`),
  KEY `type` (`type`),
  CONSTRAINT `component_ibfk_2` FOREIGN KEY (`type`) REFERENCES `component_type` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='components of a device.'

CREATE TABLE `component_prefs` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID for each entry',
  `component` int(11) unsigned NOT NULL COMMENT 'id from the component table',
  `attribute` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Attribute for the Component',
  `value` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Value for the Component',
  PRIMARY KEY (`id`),
  KEY `component` (`component`),
  CONSTRAINT `component_prefs_ibfk_1` FOREIGN KEY (`component`) REFERENCES `component` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='AV Pairs for each component'
```

I have 2 examples on how this would be used,
- IPSLA. to give a comparison, lets use existing data. This is an example of IPSLA in my lab currently.
```SQL
mysql> select * from slas limit 1;
+--------+-----------+--------+-------+---------+----------+--------+---------+
| sla_id | device_id | sla_nr | owner | tag     | rtt_type | status | deleted |
+--------+-----------+--------+-------+---------+----------+--------+---------+
|      1 |         2 |      1 |       | 1.1.1.2 | echo     |      1 |       0 |
+--------+-----------+--------+-------+---------+----------+--------+---------+
```
If this was created in this structure, it would look like this:
```SQL
mysql> select * from component_type limit 1;
+----+-------+--------------------+
| id | name  | description        |
+----+-------+--------------------+
|  1 | IPSLA | Cisco IPSLA Probes |
+----+-------+--------------------+

mysql> select * from component limit 1;     
+----+--------+------+------------------+--------------+
| id | device | type | component_status | admin_status |
+----+--------+------+------------------+--------------+
|  1 |      2 |    1 |                1 |            1 |
+----+--------+------+------------------+--------------+

mysql> select * from component_prefs where component=1;
+----+-----------+-----------+---------+
| id | component | attribute | value   |
+----+-----------+-----------+---------+
|  1 |         1 | sla_nr    | 1       |
|  2 |         1 | tag       | 1.1.1.2 |
|  3 |         1 | rtt_type  | echo    |
|  4 |         1 | owner     |         |
+----+-----------+-----------+---------+
```
Same data, different structure.
- I was also looking at #1622 you self-assigned a few days ago.
If this structure was implemented I would see it looking something like:
```SQL
mysql> select * from component_type where id=2;
+----+-------------+------------------------------------------+
| id | name        | description                              |
+----+-------------+------------------------------------------+
|  2 | CustomGraph | Graph created from user supplied DS data |
+----+-------------+------------------------------------------+

mysql> select * from component where type=2;   
+----+--------+------+------------------+--------------+
| id | device | type | component_status | admin_status |
+----+--------+------+------------------+--------------+
|  2 |      1 |    2 |                1 |            1 |
+----+--------+------+------------------+--------------+

mysql> select * from component_prefs where component=2;
+----+-----------+-------------+------------------------------------+
| id | component | attribute   | value                              |
+----+-----------+-------------+------------------------------------+
|  5 |         2 | DS_SNMP_1   | .1.2.3.4.5.6.7                      |
|  6 |         2 | DS_SNMP_2   | .1.2.3.4.5.6.99                     |
|  7 |         2 | Name        | Graph that shows really good stuff |
|  8 |         2 | Name_SNMP_1 | Widget in                          |
|  9 |         2 | Name_SNMP_2 | Widget out                         |
+----+-----------+-------------+------------------------------------+
```
The key point is that by providing this kind of framework, new players (like me) dont need to create new tables to add new components, We only need to add a row to component_type.

Thanks,
Aaron

**Comment by laf** [comment]
@paulgear How do you see this working with the mib based poller? Would it tie in together so we could save the data as well?

**Comment by f0o** [comment]
@adaniels21487 :+1: 
To be discussed ;)

**Comment by paulgear** [comment]
I think this one is worth talking through at the summit!  I've certainly got plans for phase 3 of the MIB-based poller being such that it will allow custom graphs, but that's just vapourware at present.

**Comment by adaniels21487** [comment]
Hi Team.
I have a working implementation of this at: https://github.com/adaniels21487/librenms/tree/issue-1650
component.test.php shows how one would interface with the API from a discovery/poller module.

Please let me know what you think and if it's ready for a PR.

Thanks,
Aaron

**Comment by laf** [comment]
Thanks @adaniels21487 

I've added this issue number to try and discuss at the summit.

**Comment by adaniels21487** [comment]
Hi Team,
Did you get a chance to discuss this issue at the summit?

I have developed a couple of modules which use the component concept for storage: #1851 and #2196.
Please don't see this as an attempt to force your hand, if you dont like the component idea please let me know and I'll happily refactor the modules with separate db tables.

Please let me know.
Thanks,
Aaron

**Comment by laf** [comment]
We didn't I'm afraid :(

My only overall concern with how much data we might see in this table but overall it's unlikely to be too much that MySQL can't cope.

@librenms/reviewers Any thoughts folks?

**Comment by Rosiak** [comment]
:+1: So far. 
No matter what status the MIB polling is on, we would still need to be able to add custom OIDs or similar at some point. 
How is the historic data preserved?

**Comment by adaniels21487** [comment]
Hi @Rosiak,
Just to clarify, #1650 is to create a generic DB storage mechanism for Discovery/Poller modules. The basic idea being that if a module needs to store information in the database they can use this API and do not need to create their own database tables and write their own SQL.

The driver to create this is to implement the functionality of ports (enable/disable, ignore, etc) but to do this in a generic way so that the code/db tables could support multiple modules.

This is nothing specific to the MIB poller. However the MIB poller, like any other module could use this component engine for storage.

Thanks,
Aaron

**Comment by paulgear** [comment]
@adaniels21487 I'm not entirely clear on how you would see this being used, and I'm not sure there's much overlap with the MIB polling.  It actually seems like it might be the start of a custom graphing solution.  How would you see it as working?

**Comment by adaniels21487** [comment]
Hi @paulgear,
This is proposed as a generic storage container with an easy to use API. As an example, using this I can easily create:
Cisco CBQoS (#1851) - https://github.com/adaniels21487/librenms/tree/feature/Cisco-CBQOS
Cisco CallManager (#2196) - https://github.com/adaniels21487/librenms/tree/feature/CUCM-Perfmon
I can use component for storage. I dont need to create a new CBQOS/CallManager table to store module data.

And of course any other new or existing discovery/poller module could use this to avoid db sprawl.
Also, because code is centralised in the API, we dont need to duplicate SQL in discovery/poller/presentation code.

The custom graphing agent was just an open issue I found as an example that could also utilise a container like this.

Thanks,
Aaron

**Comment by laf** [comment]
We have code that could use something like this for logging data to the DB which we currently don't do and we can't then provide alerting functionality for.

@librenms/reviewers We need to progress this one way or the other so that @adaniels21487 can submit his PRs for the new functionality being proposed.

**Comment by adaniels21487** [comment]
Perhaps a screenshot will help articulate the need I perceive.
So, as mentioned, the driver for this is to produce a generic container with the capabilities that ports has, the edit menu:
![image](https://cloud.githubusercontent.com/assets/13431617/10961166/943a466c-83d7-11e5-95f0-0847b18c5507.png)
Look familiar?

Without something like components, If I needed to duplicate this ports functionality for each module produced, I would need to duplicate all the code and the menu structure. A device could end up with many menu's under edit, just to enable/disable alerting and monitoring for new components.
I dont beleive that option scales well.

Thanks,
Aaron

**Comment by laf** [comment]
@librenms/reviewers we really need to push on with a decision one way or the other.

It has my +1 as we have a number of areas that don't store info in the DB but could do.

**Comment by Rosiak** [comment]
:+1:

**Comment by f0o** [comment]
:+1:

**Comment by SaaldjorMike** [comment]
I don't have any problems with this, and seems like the general view is :+1:

@paulgear had a few comments previously, so think we should let him come with his view on this.

**Comment by adaniels21487** [comment]
Hi @paulgear,
Could you please supply your thoughts so we can get a resolution on this one way or the other.

I am planning a phase 2 which would look at adding performance data and performance threshold alerting but I dont want to spend too much time on it if the community is not interested.

Please let me know,
Aaron

**Comment by Rosiak** [comment]
I think we should get moving on this!
@librenms/reviewers

**Comment by paulgear** [comment]
I've looked at the diff of adaniels/librenms/issue-1650 against librenms/librenms/master, and it seems pretty clean; I think this is ready for a PR.  There's not really any overlap with MIB-based polling as it stands; the two may be able to use each other's services in future.

**Comment by Rosiak** [comment]
@adaniels21487 
Ready for PR?
