### ISSUE TITLE
Discovery : CPU, Memory, Session usage on Zywall USG

### ISSUE THREAD

**Issue by Calvario** [librenms/librenms#1652]
Hello,

Is it possible to add the following OIDs :

CPU Usage 
OID = 1.3.6.1.4.1.890.1.6.22.1.1.0
Return = SNMPv2-SMI::enterprises.890.1.6.22.1.1.0 = INTEGER: 28

Memory Usage 
OID = 1.3.6.1.4.1.890.1.6.22.1.2.0 
Return = SNMPv2-SMI::enterprises.890.1.6.22.1.2.0 = INTEGER: 60

Active sessions (NAT)
OID = 1.3.6.1.4.1.890.1.6.22.1.6.0
Return = SNMPv2-SMI::enterprises.890.1.6.22.1.6.0 = INTEGER: 135

Firmware version
OID = 1.3.6.1.4.1.890.1.15.3.1.6.0
Return = SNMPv2-SMI::enterprises.890.1.15.3.1.6.0 = STRING: "3.30(AQQ.7)/1.13/2015-01-13 16:30:24"

Thanks.

**Comment by laf** [comment]
What OS do these get detected as?

**Comment by Calvario** [comment]
The OS is "Zywall"

**Comment by Calvario** [comment]
Thanks for the pull.
But i didn't see the active session number in your pull.
It can't be added ?

**Comment by laf** [comment]
It can, I just wanted to get the simple stuff sorted first.

**Comment by Calvario** [comment]
@laf,

Ok no problem, thanks.

**Comment by Calvario** [comment]
Thanks @laf.

1. Processor is ok on Zywall USG 100 and Zywall USG 20W.

2. Memory doesn't work. It create the mempool and destroy it after
Debug = http://pastebin.com/YHRKy0hE

3. Active sessions (NAT) to add.

4. Firmware version  is ok on Zywall USG 100 and Zywall USG 20W.
But it's possible to only catch this part and not all ?
*3.30(AQQ.7)*

5. Serial  is ok on Zywall USG 100 and Zywall USG 20W.
But it apear on Librenms like this = Serial " S12XX0300XXXX"
It's possible to only have this part ? *S12XX0300XXXX*

snmpwalk -c comm -v 2c ip 1.3.6.1.4.1.890.1.15.3.1.12.0
SNMPv2-SMI::enterprises.890.1.15.3.1.12.0 = STRING: " S120Z03007705"

Many thanks !

**Comment by laf** [comment]
@Calvario for 4 and 5 can you post:

./poller.php -h HOSTNAME -d -r -m system,os

**Comment by Calvario** [comment]
@laf 
http://pastebin.com/Q213vcmA

**Comment by Calvario** [comment]
Hello @laf,

Something strange happen. 
The processor of Zywall USG 100 is deleted and added for no reason.
When it "works", I have data until it removes and adds it again.
It doesn't happen in Zywall USG 20w.

2015-09-05 18:33:55 	System	Processor added: type zywall index 0 descr Processor
2015-09-05 06:33:53 	System	Processor removed: type zywall index 0 descr Processor
2015-09-05 00:33:53 	System	Processor added: type zywall index 0 descr Processor
2015-09-04 12:33:55 	System	Processor removed: type zywall index 0 descr Processor
2015-09-04 00:33:55 	System	Processor added: type zywall index 0 descr Processor
2015-09-03 18:33:57 	System	Processor removed: type zywall index 0 descr Processor

**Comment by laf** [comment]
We require the output of `snmpbulkwalk -Onet -v2c -c COMMUNITY HOSTNAME .` to proceed with this.
