### ISSUE TITLE
LibreNMS 24.9.1 generates page links incorrectly

### ISSUE THREAD

**Issue by mattock** [librenms/librenms#16531]
### The problem

I have built LibreNMS 24.9.1 for Ubuntu 24.04 using the official instructions. I'm using self-signed (snakeoil) certificates in nginx. I access LibreNMS using the IPv4 address (e.g. https://3.75.178.92). The *server_name* parameter as well as the *cn* in the self-signed certificate is set to "librenms.local".

In this setup LibreNMS generates some internal URLs as https://3.75.178.92 and some with https://librenms.local. The latter of course does not work, unless the *server_name* is also a valid DNS name pointing to LibreNMS. This inconsistency in URL generation seems to be a bug.

The practical implication is that *server_name* in this case must be set to an IPv4 address or some internal URLs in LibreNMS will not work. Doing this of course breaks IPv6 access to LibreNMS as a side-effect.

### Output of ./validate.php

```txt
librenms@librenms:~$ ./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.9.1 (2024-09-29T23:40:22+00:00)
DB Schema | 2024_08_27_182000_ports_statistics_table_rev_length (300)
PHP       | 8.3.6
Python    | 3.12.3
Database  | MariaDB 10.11.8-MariaDB-0ubuntu0.24.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.4.pre2
===========================================

[OK]    Composer Version: 2.8.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[WARN]  You have no devices.
        [FIX]: 
        Consider adding a device such as localhost: /addhost
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Your install is over 24 hours out of date, last update: Sun, 29 Sep 2024 23:40:22 +0000
        [FIX]: 
        Make sure your daily.sh cron is running and run ./daily.sh by hand to see if there are any errors.
[WARN]  Your local git branch is not master, this will prevent automatic updates.
        [FIX]: 
        You can switch back to master with git checkout master
```
```


### What was the last working version of LibreNMS?

_No response_

### Anything in the logs that might be useful for us?

```txt
Reproducing this should be easy: change the *server_name* in nginx to something, e.g. *librenms.local*. Then login to LibreNMS, however over "Devices" in the menu and check where the link leads. It should (incorrectly) lead to https://librenms.local/devices.

If you're unable to reproduce this then try to login to LibreNMS using a IP address instead of using the DNS name (e.g. https://3.75.178.92 instead of https://librenms.domain.com).
```

**Comment by murrant** [comment]
Make sure you set APP_URL.

**Comment by mattock** [comment]
Let me clarify: I'm not asking for help. I'm trying to report a bug about the inconsistent/confusing behavior in how LibreNMS constructs its internal links. At minimum the documentation seems to incomplete and/or misleading. I would like to help get the underlying problem fixed, or if that is not possible, at least documented. I'm willing to send PRs your way, but I don't know the internals of LibreNMS well enough so pointers would be appreciated.

I did more testing with `server_name librenms.local;` in nginx config to understand the fixes/workarounds:

* Setting `APP_URL=https://3.75.178.92` in */opt/librenms/.env* did not have any effect. Graph URL were still written with *librenms.local*. This is surprising because [documentation claims](https://docs.librenms.org/Support/Environment-Variables/) that it should work.
* Setting `APP_PROXY_URL=127.0.0.1` in */opt/librenms/.env* did not have any effect on generated URLs, even when used in combination with *APP_URL*.
* Running `lnms config:set base_url https://3.75.178.92/` **did fix** the problem.
* Setting `servername  3.75.178.92;` in */etc/nginx/conf.d/librenms.conf* **did fix** the problem.

The problem manifests itself with URLs such as *https://<base_url>/device/device=1/tab=graphs/group=system* where *<base_url>* was set to the non-resolveable address *librenms.local* from nginx configuration. I used anonymous browser windows (launch, login, test, exit) and restarted nginx and php8.3-fpm services for each test to make sure caches are not playing tricks on me.

**NOTE:** The problem only happens when LibreNMS admin webui is loaded using an IP address. Given that precondition the URL generation logic causes the following problems:
* Simultaneous IPv4 and IPv6 access won't work as one needs to configure one or the other with lnms or nginx server_name.
* If LibreNMS server IP changes URLs are partially broken until fixed again (e.g. typical on a test system in a public Cloud).

This problem would not affect most "normal" production setups.
