### ISSUE TITLE
Poller keeps overwriting discovery states to 0 of various devices (Cisco Nexus Fans,Checkpoint PwSupplies, etc)

### ISSUE THREAD

**Issue by zagosch** [librenms/librenms#16544]
### The problem

We have a libre with destributed poller setup. After the update to 24.9.1 all pollers keeps rediscovering devices at full, as example it sets a state of a FAN of powersupply first to default (0) and after the polling it sets it to state 2 (up). It keeps generating alerts like if it completly deletes al statusses en relearns them again. It does that on all our devices (300+). On all pollers.

It also relearns it IP adresses, see picture of a event summary on one of the devices:

![afbeelding](https://github.com/user-attachments/assets/2b3eeca8-1eda-4714-820b-f879cd922b1a)

It does this like every 6 hours i think. 

Poller performance:
![afbeelding](https://github.com/user-attachments/assets/fcce64f8-a3c1-4459-822d-07f5428cf9bb)

It wasn't like this before the update, so i don't think performance on the first thought. Please advice. 

### Output of ./validate.php

```txt
08:14:51 librenms@LibreNMS:~$ ./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.9.1 (2024-09-30T01:40:22+02:00)
DB Schema | 2024_08_27_182000_ports_statistics_table_rev_length (300)
PHP       | 8.2.21
Python    | 3.9.18
Database  | MariaDB 10.5.22-MariaDB
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.5.8
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No python wrapper pollers found
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
08:14:56 librenms@LibreNMS:~$
```

### What was the last working version of LibreNMS?

24.8.0

**Comment by zagosch** [comment]
Hmm, it is performance i think now. I've added additional memory and cpu's to my pollers and it now works. Never had this issue before. Well it is solved for me know. Is 24.9.1 asking much more then 24.8.0?

**Comment by murrant** [comment]
@zagosch likely some bad php code related your specific device OS.  Discovery debug output would be helpful.

**Comment by zagosch** [comment]
Please find the Discovery debug log attached from a troubled device. (cisco nexus device)
Used command: ./discovery.php -h 190 -d -v
If i need to run it with some additional flags, please let met know. 
[discovery debug log.log](https://github.com/user-attachments/files/17406887/discovery.debug.log.log)

**Comment by rudybroersma** [comment]
We're seeing the same issue on multiple devices. One issue is based on my own PR: https://github.com/librenms/librenms/pull/15793

We're seeing:
![afbeelding](https://github.com/user-attachments/assets/6cc332a4-73f4-4911-a06d-f81fce6f0bfb)

However, as can be seen here:
https://github.com/librenms/librenms/pull/15793/files#r1843785382

I'm not setting any default value (default = null)

**Comment by murrant** [comment]
@rudybroersma yeah, you want to send the current value in discovery.

**Comment by zagosch** [comment]
Is this something that can be ported into cisco nexus and checkpoint devices discovery?

**Comment by rudybroersma** [comment]
> Is this something that can be ported into cisco nexus and checkpoint devices discovery?

Yeah, I can probably fix that for you. Do you have a snmprec file of your device for me? 
And perhaps a screenshot of the sensors that are having this issue?

**Comment by zagosch** [comment]
On nexus devices it happens on all discovered fan state sensors:
![afbeelding](https://github.com/user-attachments/assets/f15a9e53-3667-4c6a-930d-4005bcabbe4d)

On checkpoints devices it happens on all discovered powersupply state sensors:
![afbeelding](https://github.com/user-attachments/assets/f4ee4339-2766-4f14-9624-9111c4fa28d9)

I need to look into the snmprec files. How to create those files. I'm not familiair with that.

**Comment by zagosch** [comment]
Also i'm looking at the include file for state nxos.inc.php. On 4 sept it changed (along with all other state includes), maybe this has something to do with this issue. I'm not a programmer so i'm not totaly aware of the impact of this change. 

Sensors remove reliance on global variable (#16344)

[Sensors remove reliance on global variable (](https://github.com/librenms/librenms/commit/f15f8fa63a7b70da6542312d461931513acafb3d)https://github.com/librenms/librenms/pull/16344[)](https://github.com/librenms/librenms/commit/f15f8fa63a7b70da6542312d461931513acafb3d)

**Comment by rudybroersma** [comment]
> On nexus devices it happens on all discovered fan state sensors: ![afbeelding](https://private-user-images.githubusercontent.com/10849746/388541228-f15a9e53-3667-4c6a-930d-4005bcabbe4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyODkyMTIsIm5iZiI6MTczMjI4ODkxMiwicGF0aCI6Ii8xMDg0OTc0Ni8zODg1NDEyMjgtZjE1YTllNTMtMzY2Ny00YzZhLTkzMGQtNDAwNWJjYWJiZTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDE1MjE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MTI5OTUzYjJlZGI4YmIzZjMxZWNiYTg1MjcyZjE4ZGExOTU1ZGExZGFiZDc3NTRkNGI5NmM3MDM5NmY2YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6nU1phXSdlvrXPX5-YhcORSMOSyzSgCjN0aKsEw0MGw)
> 
> On checkpoints devices it happens on all discovered powersupply state sensors: ![afbeelding](https://private-user-images.githubusercontent.com/10849746/388541549-f4ee4339-2766-4f14-9624-9111c4fa28d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyODkyMTIsIm5iZiI6MTczMjI4ODkxMiwicGF0aCI6Ii8xMDg0OTc0Ni8zODg1NDE1NDktZjRlZTQzMzktMjc2Ni00ZjE0LTk2MjQtOTExMWM0ZmEyOGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDE1MjE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NmRlZTZiOTdjNmI5Y2EyYmFlOWNiOTgyN2EzNzdmMjllYWYxZTQzYjQzNGQwN2M1ZjVhYzdiYzBkOTk5OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ip865O7ptPDlE8rZfSI6v6d4nMAZ78NvghZcy_IktOc)
> 
> I need to look into the snmprec files. How to create those files. I'm not familiair with that.

The issue is in includes/discovery/sensors/state/nxos.inc.php
Line 42, in which the sensor is added to the database, does not contain a value.

Thus, value is set to null or 0.

When the poller process iterates over your NXOS device, it updates the value from 0 to whatever it really is.

I'll make a PR

**Comment by zagosch** [comment]
@rudybroersma That would be nice. Cisco Nexus is the biggest issue for us. Is there also a way that checkpoint has some links with this issue? Since it does the same with the powersupply states on checkpoints (gaia).

**Comment by rudybroersma** [comment]
> @rudybroersma That would be nice. Cisco Nexus is the biggest issue for us. Is there also a way that checkpoint has some links with this issue? Since it does the same with the powersupply states on checkpoints (gaia).
> 
> I'm seeing that you are doing some PR for fortigate as well. It look like this issue is broadly on most devices?

Any device can suffer from this issue, depending on it's LibreNMS implementation.
I added the Cisco Nexus 3k from the LibreNMS's SNMPrec's into my installation, but I can't reproduce the issue with this device.

Can you send me a snmprec file of your device? 

See  " collect snmp data"  on https://docs.librenms.org/Developing/os/Test-Units/#capturing-test-data

It generates a snmprec file, which I'd like to receive from you.

**Comment by zagosch** [comment]
I've creaded snmprec files. One for a 3k nexus, one for a 9k nexus and one for a checkpoint. All affected with this issue. 
 
[snmprec.zip](https://github.com/user-attachments/files/17903910/snmprec.zip)

**Comment by rudybroersma** [comment]
My bad. My development LibreNMS instance hasn't been updated for months. It didn't have this bug :-)
I can now reproduce your issue. Sorry for the confusion

**Comment by minusdelta** [comment]
Cisco "Small Business" SG300-10 is affected too:

![image](https://github.com/user-attachments/assets/c62f3b6c-8cd7-48ef-9766-0aae8dfd7f27)

**Comment by rudybroersma** [comment]
So, with the NXOS and Cisco SB PR's merged, the remaining problem is the Checkpoint devices, correct?

**Comment by rudybroersma** [comment]
I tried to replicate the issue with the Gaia 6600 SNMPrec.. Still can't produce the problem.

**Comment by zagosch** [comment]
Well ill try to implement the nxos fix first. Lets see how the gaia discovery workshop after that. NXOS are our most used devices. 400+ devices.

**Comment by zagosch** [comment]
Last update i've implemented this PR into librenms, our issues with NXOS are fixed now. For checkpoint, the issue still persist. It is not only our 6600 checkpoint, but also our other checkpoint models. 

![afbeelding](https://github.com/user-attachments/assets/7a5f49fc-c475-4e60-8c88-15e42884d5f0)

**Comment by rudybroersma** [comment]
> Last update i've implemented this PR into librenms, our issues with NXOS are fixed now. For checkpoint, the issue still persist. It is not only our 6600 checkpoint, but also our other checkpoint models.
> 

Can you reach out to me on tozz@kijkt.tv?

**Comment by rudybroersma** [comment]
> Last update i've implemented this PR into librenms, our issues with NXOS are fixed now. For checkpoint, the issue still persist. It is not only our 6600 checkpoint, but also our other checkpoint models.
> 

zagosch has reached out to me by e-mail. I believe zagosch is still using https://github.com/librenms/librenms/pull/15136/

I've e-mailed him my findings and I'm 99% certain this is a local issue on zagosch's installation.

**Comment by rudybroersma** [comment]
zagosch has informed me his issue is resolved after manually removing the files from PR #15136 

I believe this issue can be closed.

**Comment by zagosch** [comment]
I agree, my issues are now resolved. The NX-OS part with https://github.com/librenms/librenms/pull/16776 and the checkpoint with removing old config from #15136. Thanks all.
