### ISSUE TITLE
Windows Server 2012 R2 'Standard' listed as 'Datacenter'

### ISSUE THREAD

**Issue by Tawmu** [librenms/librenms#1657]
"Microsoft Windows Server 2012 R2 Datacenter (NT 6.3) (Multiprocessor)" should be showing as "Microsoft Windows Server 2012 R2 Standard (NT 6.3) (Multiprocessor)".

Not sure this can be figured out via a version number but Windows reports it in various places, I'm not sure how LibreNMS deduces it as a Datacenter install.

**Comment by laf** [comment]
Thanks @Tawmu 

Can you post the output of ./poller.php -h HOSTNAME -d -r -m system,os

**Comment by Tawmu** [comment]
@laf http://pastebin.com/pvtQBmpM

**Comment by laf** [comment]
That's really odd. the sysObjectID reported back is what's traditionally been set for Datacentre.

**Comment by Tawmu** [comment]
2012R2 Datacenter: http://pastebin.com/rVAyrzY7

Interestingly, LibreNMS is showing this one as simply "Microsoft Windows
Server 2012 R2 (NT 6.3)" whereas it is showing Standard as "Microsoft Windows
Server 2012 R2 Datacenter (NT 6.3)"
