### ISSUE TITLE
New Graylog 6.0.7+ NOT integrating with LIbrenms.

### ISSUE THREAD

**Issue by davidshirk80** [librenms/librenms#16581]
### The problem

In the newest versions of graylog (6+), the /search/universal/relative API is a legacy API that does not appear to be working. When I run this: curl -X GET -u 'admin:password' -H 'accept:application/json' 'https://hostname/api/search/universal/relative?query=*&range=1500&limit=1000&batch_size=500&fields=*'  - it pulls the expected data along with resolved hostnames etc matching the DNS names used by LibreNMS on their respective devices(or seems to). SO I know it is not an HTTPS or DNS issue. I have opened a case with Graylog over it as well - https://github.com/Graylog2/graylog2-server/issues/20787 . 

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.9.1-59-gaf15eabbb (2024-10-24T22:50:56-05:00)
DB Schema | 2024_10_06_002633_ports_vlans_table_add_port_id_index (301)
PHP       | 8.3.6
Python    | 3.12.3
Database  | MariaDB 10.11.8-MariaDB-0ubuntu0.24.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.4.pre2
===========================================

[OK]    Composer Version: 2.8.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]: 
        You can fix this with ./scripts/github-remove
        Modified Files:
         app/ApiClients/GraylogApi.php
```

### What was the last working version of LibreNMS?

24.9.1-59

### Anything in the logs that might be useful for us?

```txt
I cannot find any graylog entries in the librenms log file, or syslog file.
```

**Comment by murrant** [comment]
I confirmed that the same API endpoint exists in 6.0.7 and is unchanged.

However, you posted the batch api endpoint instead of the endpoint LibreNMS actually uses. (omit batch_size)

`https://hostname/api/search/universal/relative?query=*&range=25`

**Comment by murrant** [comment]
You also reference "syslog" in your report.  When you integrate Graylog into LibreNMS, all syslog functionality is removed (including storing logs in the database) and the menu entries are replaced with "Graylog".  Specifically in to places.

1. The overview menu Syslog is removed and Graylog is added, pointing to "https://librenms.url/graylog"
2. In device logs page, Syslog tab is removed and Graylog is added, pointing to "https://librenms.url/device/device=<device_id>/tab=logs/section=graylog/"

**Comment by davidshirk80** [comment]
curl -X GET -u 'admin:PW' -H 'accept:application/json' 'https://host/api/search/universal/relative?query=*&range=1500&limit=1000&batch_size=500&fields=*' returns a lot of data - so I know that the connectivity is there, and that the API is actually working (sorry for the late night miss on my end). The output shows the resolved hostnames exactly as they are in the LibrenNMS server, the messages - all of it. Yet this page https://host/graylog  still says no entried found. Any recommendation on where to go next?

**Comment by davidshirk80** [comment]
fails cross check
Request URL:
https://Hostname/ajax/table/graylog
Request Method:
POST
Status Code:
500 Internal Server Error
Remote Address:
xxx.xxx.xxx.xxx:443
Referrer Policy:
strict-origin-when-cross-origin
cache-control:
no-cache, private
connection:
keep-alive
content-type:
application/json
date:
Mon, 28 Oct 2024 17:07:03 GMT
server:
nginx/1.24.0 (Ubuntu)

**Comment by davidshirk80** [comment]
![LibreGraylogNWerror](https://github.com/user-attachments/assets/96e60ea2-beb1-4514-853f-f72a70f41848)

**Comment by murrant** [comment]
Closing this, it works with Graylog 6.1.
