### ISSUE TITLE
World Map don´t show devices

### ISSUE THREAD

**Issue by daniel-franca** [librenms/librenms#16631]
### The problem

After upgrade (using version [24.9.1-111-gd78966d3e - Fri Nov 01 2024 14:55:22 GMT-0300]), world map on dashboards stopped to show devices icons, and the maps is empty.

### Output of ./validate.php

```txt
$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.9.1-111-gd78966d3e (2024-11-01T14:55:22-03:00)
DB Schema | 2023_12_21_085427_create_view_port_mac_link (304)
PHP       | 8.2.24
Python    | 3.11.2
Database  | MariaDB 11.5.2-MariaDB
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Composer Version: 2.8.2
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connection to memcached is ok
[OK]    Connected to rrdcached
[FAIL]  Poller is not running.  No poller has run within the last 300 seconds.
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[FAIL]  Python wrapper cron entry is not present
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

24.9.1

**Comment by erickmelo** [comment]
The problem seems to be associated with this merge-request (https://github.com/librenms/librenms/pull/15567), where the populate_map_markers() function was moved.
The browser console is showing this error:
``` 
Uncaught ReferenceError: populate_map_markers is not defined
    at Array.<anonymous> (<anonymous>:14:25)
    at Object.success (librenms.js?ver=29092024:256:48)
    at c (jquery.min.js?ver=05072021:2:28327)
    at Object.fireWith [as resolveWith] (jquery.min.js?ver=05072021:2:29072)
    at l (jquery.min.js?ver=05072021:2:79901)
    at XMLHttpRequest.<anonymous> (jquery.min.js?ver=05072021:2:82355)
```

**Comment by murrant** [comment]
Hmm, I can't reproduce this issue.  Try hard refreshing the page CTRL-F5.

**Comment by Evil8864** [comment]
how to remove this 1 st nov update

**Comment by murrant** [comment]
If anyone can give me tips on how I can trigger this issue, that would be helpful for fixing it.  As I said, I can't make it misbehave.

**Comment by smwinn** [comment]
I have three installations of LibreNMS and the world map on all of them is showing devices up+down even though only down is chosen. Changing it or creating a new world map doesn't make any difference.

**Comment by murrant** [comment]
This is a separate issue, but thanks for reporting.

**Comment by daniel-franca** [comment]
We use here OpenStreetMap Mapping Engine, we don´t test with google or other engine.

**Comment by eskyuu** [comment]
Good to hear the update fixed it.
