### ISSUE TITLE
Libre nms LLDP map

### ISSUE THREAD

**Issue by Evil8864** [librenms/librenms#16635]
### The problem

before 1 nov update port-channel multiple links are showing on network maps. bot now its now showing and some devices where lldp is not on after update those devices are showing on map. suggest how to fix or rollback previous map
<img width="728" alt="map" src="https://github.com/user-attachments/assets/8c661f68-8d82-45ac-b073-1a6ef5e39707">

### Output of ./validate.php

```txt
librenms@web-server:~$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.9.1-113-gaaa100251 (2024-11-02T09:03:13+05:30)
DB Schema | 2023_12_21_085427_create_view_port_mac_link (304)
PHP       | 8.2.24
Python    | 3.11.2
Database  | MariaDB 10.3.39-MariaDB-0ubuntu0.20.04.2
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Composer Version: 2.8.2
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connection to memcached is ok
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

24.9.1-113-gaaa100251 - Sat Nov 02 2024 09:03:13 GMT+0530

**Comment by eskyuu** [comment]
Can you please clarify what you expect to see by answering the following:
1 - Do you expect devices to only show on the map if they have LLDP neighbours?  For example, would you expect pradip_chattraj in the image above to disappear from the map?
2 - Can you please tell me 2 devices that are on the image above that have port-channels between them?  I want to know if the issue is that you are seeing gigabit-ethernet ports where you expect to see port-channel, or if the issue is that port-channel LLDP neighbours are just not showing on the map at all.

**Comment by Evil8864** [comment]
Only single link is there

**Comment by Evil8864** [comment]
In the devices neighbour section both links are showing...but the problem
is on the map

**Comment by Evil8864** [comment]
includes/html/print-map.inc.php ---this file is missing on new update

**Comment by eskyuu** [comment]
I checked on our production system, which is on the monthly update cycle, and confirmed that the changes are as follows:
 - The old maps did not show any devices that were isolated
 - The old maps allowed multiple links between devices
 - The line widths were different

I'm about to push a PR to fix all of these

**Comment by eskyuu** [comment]
https://github.com/librenms/librenms/pull/16638 Fixes these issues

**Comment by Evil8864** [comment]
thanks issue resolve now

**Comment by Evil8864** [comment]
<img width="610" alt="image" src="https://github.com/user-attachments/assets/70998221-9a29-4b90-8a16-4ecb2af37dc5">
some port details is not showing.

**Comment by eskyuu** [comment]
I've just updated the PR to fix the duplicates because both devices have a peer link to the other.

I'm not sure why the labels are missing on those ports, but I'll need to look at that later

**Comment by Evil8864** [comment]
Every link has duplicate link. please see my attachment.
