### ISSUE TITLE
Base table or view already exists: 1050 Table 'custom_map_nodes' already exists

### ISSUE THREAD

**Issue by AmarsDing** [librenms/librenms#16658]
### The problem

# 15874

Didn't solve the problem

problem：

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'custom_map_  
  nodes' already exists (Connection: mysql, SQL: create table `custom_map_nod  
  es` (`custom_map_node_id` int unsigned not null auto_increment primary key,  
   `custom_map_id` int unsigned not null, `device_id` int unsigned null, `lab  
  el` varchar(50) not null, `style` varchar(50) not null, `icon` varchar(8) n  
  ull, `size` int not null, `border_width` int not null, `text_face` varchar(  
  50) not null, `text_size` int not null, `text_colour` varchar(10) not null,  
   `colour_bg` varchar(10) null, `colour_bdr` varchar(10) null, `x_pos` int n  
  ot null, `y_pos` int not null, `created_at` timestamp null, `updated_at` ti  
  mestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

I think should update this sql      

create table if not exists `custom_map_nodes` (`custom_map_node_id` int unsigned not null auto_increment primary key,  
   `custom_map_id` int unsigned not null, `device_id` int unsigned null, `lab  
  el` varchar(50) not null, `style` varchar(50) not null, `icon` varchar(8) n  
  ull, `size` int not null, `border_width` int not null, `text_face` varchar(  
  50) not null, `text_size` int not null, `text_colour` varchar(10) not null,  
   `colour_bg` varchar(10) null, `colour_bdr` varchar(10) null, `x_pos` int n  
  ot null, `y_pos` int not null, `created_at` timestamp null, `updated_at` ti  
  mestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'

### Output of ./validate.php

```txt
[cont-init.d] 04-svc-main.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing... 
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing... 
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-fix-perms.sh: executing... 
Fixing perms...
[cont-init.d] 02-fix-perms.sh: exited 0.
[cont-init.d] 03-config.sh: executing... 
Setting timezone to Asia/Shanghai...
Setting PHP-FPM configuration...
Setting PHP INI configuration...
Setting OpCache configuration...
Setting Nginx configuration...
Updating SNMP community...
Initializing LibreNMS files / folders...
Setting LibreNMS configuration...
Checking LibreNMS plugins...
Fixing perms...
Checking additional Monitoring plugins...
Checking alert templates...
[cont-init.d] 03-config.sh: exited 0.
[cont-init.d] 04-svc-main.sh: executing... 
Waiting 60s for database to be ready...
Database ready!
Updating database schema...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.

   INFO  Running migrations.  

  2023_12_08_081420_create_custom_map_node_table .................... 3ms FAIL

In Connection.php line 829:
                                                                               
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'custom_map_  
  nodes' already exists (Connection: mysql, SQL: create table `custom_map_nod  
  es` (`custom_map_node_id` int unsigned not null auto_increment primary key,  
   `custom_map_id` int unsigned not null, `device_id` int unsigned null, `lab  
  el` varchar(50) not null, `style` varchar(50) not null, `icon` varchar(8) n  
  ull, `size` int not null, `border_width` int not null, `text_face` varchar(  
  50) not null, `text_size` int not null, `text_colour` varchar(10) not null,  
   `colour_bg` varchar(10) null, `colour_bdr` varchar(10) null, `x_pos` int n  
  ot null, `y_pos` int not null, `created_at` timestamp null, `updated_at` ti  
  mestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')    
                                                                               

In Connection.php line 587:
                                                                               
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'custom_map_  
  nodes' already exists                                                        
                                                                               

[cont-init.d] 04-svc-main.sh: exited 1.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

### What was the last working version of LibreNMS?

24.10.0

**Comment by eskyuu** [comment]
The database migrations all use Schema::create(), which results in the above SQL code.  There is a separate database table that gets updated to indicate that a particular migration file has run.  In your case, it looks like the system doesn't think a migration has applied, so it's trying to apply it.  Did you have a database crash during migration at some point?

The immediate fix for you is to drop the table manually.

@murrant - Is it worth wrapping all database create statements inside a Schema::hasTable() call to cleanly handle database issues during migrations?  Or are we satisfied that they are rare enough to require a manual clean-up?

**Comment by murrant** [comment]
Sometimes, but this was caused by a DB server crash, so likely it is corrupted anyway.

**Comment by murrant** [comment]
https://github.com/MariaDB/mariadb-docker/issues/617
