### ISSUE TITLE
database warning

### ISSUE THREAD

**Issue by Evil8864** [librenms/librenms#16680]
### The problem

how to fix database warning issue

### Output of ./validate.php

```txt
librenms@web-server:~$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.10.1-4-gf10e02b58 (2024-11-09T03:42:10+05:30)
DB Schema | 2024_10_20_154356_create_qos_table (305)
PHP       | 8.2.24
Python    | 3.11.2
Database  | MariaDB 10.3.39-MariaDB-0ubuntu0.20.04.2
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Composer Version: 2.8.2
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[WARN]  Your database schema has extra migrations (2024_10_20_154356_create_qos_table). If you just switched to the stable release from the daily release, your database is in between releases and this will be resolved with the next release.
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    MySQL and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connection to memcached is ok
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]:
        You can fix this with ./scripts/github-remove
        Modified Files:
         app/Http/Controllers/Device/Tabs/NeighboursController.php
You have new mail in /var/mail/librenms
```

### What was the last working version of LibreNMS?

24.10.1-4-gf10e02b58 (2024-11-09T03:42:10+05:30)

**Comment by eskyuu** [comment]
You need to run:
./artisan migrate:rollback --step 1

**Comment by Evil8864** [comment]
librenms@web-server:~$ ./artisan migrate:rollback --step 1


                                                                 APPLICATION IN PRODUCTION.


 ┌ Are you sure you want to run this command? ──────────────────┐
 │ Yes                                                          │
 └──────────────────────────────────────────────────────────────┘

   INFO  Rolling back migrations.

  2024_10_20_154356_create_qos_table ........................................................................................... Migration not found

**Comment by Evil8864** [comment]
still same issue

**Comment by Evil8864** [comment]
librenms@web-server:~$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.10.1-4-gf10e02b58 (2024-11-09T03:42:10+05:30)
DB Schema | 2024_10_20_154356_create_qos_table (305)
PHP       | 8.2.24
Python    | 3.11.2
Database  | MariaDB 10.3.39-MariaDB-0ubuntu0.20.04.2
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Composer Version: 2.8.2
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[WARN]  Your database schema has extra migrations (2024_10_20_154356_create_qos_table). If you just switched to the stable release from the daily release, your database is in between releases and this will be resolved with the next release.
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    MySQL and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connection to memcached is ok
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]:
        You can fix this with ./scripts/github-remove
        Modified Files:
         app/Http/Controllers/Device/Tabs/NeighboursController.php

**Comment by Evil8864** [comment]
Please help

**Comment by laf** [comment]
You've tested #16552, re-apply it, run the `./artisan migrate:rollback --step 1` command again then remove the patch.
