### ISSUE TITLE
Feature Request: Add Cisco Power and Fan Status

### ISSUE THREAD

**Issue by RobsanInc** [librenms/librenms#1668]
LibreNMS Team,

Please add Cisco Power and Fan status to the device overview tab.

Thank you!

**Comment by Rosiak** [comment]
Can you be a bit more specific in regards to which model you're asking for? (So we can test, ask for data etc)

**Comment by RobsanInc** [comment]
Sure,

2811, 3550G, 3750, 3750X, 3945, and ASR-1004.

In my home lab I can test the 2811 and 3550-12T, the rest of the devices are in a production system.

Rob

**Comment by laf** [comment]
Info will be from CISCO-ENTITY-FRU-CONTROL-MIB

**Comment by Rosiak** [comment]
Can you do a SNMPWALK on CISCO-ENTITY-FRU-CONTROL-MIB towards one of the devices, and paste it here?

**Comment by RobsanInc** [comment]
Rosiak,

It's a bit too large to cut and paste. Here is the output of CISCO-ENTITY-FRU-CONTROL-MIB:

snmpwalk -v 2c -c ********** 2811-top -m CISCO-ENTITY-FRU-CONTROL-MIB

http://www.rzatek.com/librenms/CISCO-ENTITY-FRU-CONTROL-MIB-OUTPUT2.txt

Rob

**Comment by Rosiak** [comment]
#3102 Implemented this.
