### ISSUE TITLE
Discovery : Windows process and software installed

### ISSUE THREAD

**Issue by Calvario** [librenms/librenms#1669]
Hello,

Do you think it is possible to add process and the software installed in Windows machine?

I saw by making a snmpwalk of "Windows 7" and "Windows 2008R2" that

HOST-RESOURCES-MIB::hrSWRunIndex.1 = INTEGER: 1
HOST-RESOURCES-MIB::hrSWRunName.1 = STRING: "System Idle Process"
HOST-RESOURCES-MIB::hrSWRunPath.1 = ""
HOST-RESOURCES-MIB::hrSWRunParameters.1 = ""
HOST-RESOURCES-MIB::hrSWRunType.1 = INTEGER: operatingSystem(2)
HOST-RESOURCES-MIB::hrSWRunStatus.1 = INTEGER: running(1)
HOST-RESOURCES-MIB::hrSWRunPerfCPU.1 = INTEGER: 115942880
HOST-RESOURCES-MIB::hrSWRunPerfMem.1 = INTEGER: 24 KBytes

HOST-RESOURCES-MIB::hrSWInstalledIndex.1 = INTEGER: 1
HOST-RESOURCES-MIB::hrSWInstalledName.1 = STRING: "7-Zip 9.20"
HOST-RESOURCES-MIB::hrSWInstalledType.1 = INTEGER: application(4)
HOST-RESOURCES-MIB::hrSWInstalledDate.1 = STRING: 2014-4-5,18:26:20.0

Thanks !

**Comment by laf** [comment]
Possible yes, think we would need to do this with another table and a discovery option. Certainly possible.

**Comment by killsudo** [comment]
@laf if you tackle this can you add it for Junos/Redhat/Centos also per #789 ?

**Comment by laf** [comment]
We require the output of `snmpbulkwalk -Onet -v2c -c COMMUNITY HOSTNAME .` to be able to take this any further.

**Comment by BryannaM** [comment]
I did not know if you needed that ran on more then one version of Windows in case they are different. So I ran it on a few of our servers, I attached and named the files by what windows version they are from. 
[2012R2-SNMP.txt](https://github.com/librenms/librenms/files/525429/2012R2-SNMP.txt)
[2012-SNMP.txt](https://github.com/librenms/librenms/files/525431/2012-SNMP.txt)
[2016-SNMP.txt](https://github.com/librenms/librenms/files/525430/2016-SNMP.txt)
[2008R2-SP1-SNMP.txt](https://github.com/librenms/librenms/files/525432/2008R2-SP1-SNMP.txt)

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-discovery-windows-process-and-software-installed/737
