### ISSUE TITLE
4byte asn not showing up properly 

### ISSUE THREAD

**Issue by lokespotify** [librenms/librenms#1670]
Hi when using the 4byte asn 4200102900 on a juniper EX4300 in the gui it shows up as AS-94864396.

**Comment by Rosiak** [comment]
Altering the bgpPeers->bgpPeerRemoteAs column to bigint(20) should fix this.
Any input @laf or @f0o ?

**Comment by f0o** [comment]
@Rosiak Would be great if that's the solution!
Can you file a PR so we can test that on the CI?
