### ISSUE TITLE
Help with Devices unpolled message

### ISSUE THREAD

**Issue by masonke** [librenms/librenms#1672]
On the GUI, the yellow box with "Devices Unpolled" error keeps popping up. It says there are devices that have not been polled in the last 15 minutes.

Where can I see the devices it is complaining about? The logs show me the device number of devices that were polled, but finding the ones that did not is escaping me.

All the devices in the Poll log show polled, so any pointers would be welcome.

Librenms version e6dcc93
2 Distributed poller groups

**Comment by f0o** [comment]
Sort the table by 'Last Polled' and look at the oldest timestamp

**Comment by masonke** [comment]
They are all within 6 minutes of the time i looked

**Comment by laf** [comment]
@masonke 

It simply runs this query:

```
SELECT hostname FROM `devices` WHERE `last_polled` <= DATE_ADD(NOW(), INTERVAL - 15 minute) AND `ignore` = 0 AND `disabled` = 0 AND status = 1;
```

If you run that it will tell you the hostname of ones it couldn't poll.

**Comment by masonke** [comment]
Found the problem. We had 2 routers that were mis-configured with 998 interface vlan commands. These were taking 650 - 720 seconds to poll , which was way too long. Fixing those 2 devices solved the problem.

Not sure where the 15 minutes comes in, that would be 900 seconds. Maybe it was overlapping polls?

Is there a way to force LibreNMS to kill a poll after 280 seconds and spit put an error?

If there is any data you would like, let me know.

**Comment by laf** [comment]
That's a bit tricky, could be possible though. However it's not a hard 280 seconds, if that device didn't start polling until 4 minutes 30 seconds into the poller-wrapper run then it only has 30 seconds to complete. By default, long poll time devices should be tried first.

Anyone else?

**Comment by masonke** [comment]
Good points.

As a data point,  I had 2 poller in that distributed polling group. Could there have been a race condition where both pollers were trying to poll the same device?
~KEM

**Comment by laf** [comment]
I've never had or seen that happen before. The polls are registered in memcached. @f0o?

**Comment by f0o** [comment]
same @laf - The pollers register a lock prior attempting to poll a device. That lock is only removed by the exclusive master-node after all pollers terminate to avoid timed loops.

Do you experience this frequently?

**Comment by masonke** [comment]
If 2 pollers could poll the same device was a question on my part.  Will grab the logs today and that may shed some light.

It happened every time when the device were mis-configured and I moved from a single poller to a distributed poller

It would be nice if the polling log listed the time it took to complete the poll.
~KEM

**Comment by masonke** [comment]
Would you like me to close this and open a new request to add the time it took to poll to the log entries?

**Comment by laf** [comment]
Post here. That's fine

**Comment by masonke** [comment]
Please add the amount of time it took to poll a device to the log file. That would help with troubleshooting devices that take a long time to poll, such as a mis-configured device, or congested link.

**Comment by laf** [comment]
Just checked this and found that poller time is logged in both the log file and the webui:

/opt/librenms/poller.php 1 2015-08-23 20:15:07 - 1 devices polled in 5.360 secs

or

![image](https://cloud.githubusercontent.com/assets/3941142/9430015/8591f5fe-49dc-11e5-947a-917551d1f4f4.png)

Is this what you meant?

**Comment by Rosiak** [comment]
Proposing closing this in 48hrs.

**Comment by masonke** [comment]
Close it now. Thank you
