### ISSUE TITLE
BUG : Override sysLocation adding adress with a ' will be escaped \'

### ISSUE THREAD

**Issue by Calvario** [librenms/librenms#1674]
Hello,

When i override sysLocation with an address like this = "Blabla bla l'bla" they will be "Blabla bla l\'bla"

Thanks

**Comment by f0o** [comment]
Can reproduce, will file a patch within the next hour or two

**Comment by laf** [comment]
Can't reproduce :(

![image](https://cloud.githubusercontent.com/assets/3941142/9533537/9f317f3a-4d0a-11e5-9c0b-8c827e2fe77e.png)

Any info so we can replicate it?

**Comment by Calvario** [comment]
It's when you save the override, the ' will be escaped in \'
I think it's because de mres escape the ' for MySQL.

**Comment by f0o** [comment]
@laf it's reproducible on the demo-install :/

**Comment by f0o** [comment]
See: https://demo.librenms.org/device/device=1/
`T\'est, Manchester, United Kingdom`

**Comment by Rosiak** [comment]
Tagging @librenms/core-team , isn't this a trivial fix?

**Comment by laf** [comment]
PRs welcome @Rosiak :)
