### ISSUE TITLE
Tool tips on question mark UI elements flash and don't show up

### ISSUE THREAD

**Issue by abacef** [librenms/librenms#16766]
### The problem

For example opening the authentication settings page when hovering over a question mark, I am not able to read the tool tip no matter where I move my cursor because every time I move it it flashes quickly and just disappears. I tried chrome and Firefox, both are doing it, but a little differently. I am using the Nov 25 2023 version of librenms

### Output of ./validate.php

```txt
N/A
```

### Anything in the logs that might be useful for us?

```txt
No
```

**Comment by laf** [comment]
Please update your version of LibreNMS before posting for help.

**Comment by abacef** [comment]
I just tried using the latest librenms and this is still happening
