### ISSUE TITLE
Adding a device with a specific Display name

### ISSUE THREAD

**Issue by siminkuv** [librenms/librenms#16784]
### The problem

I am adding a device via webgui. When adding a device I have to enter a hostname or IP address. Since I have some devices behind NAT and remote, I used to enter the hostname in /etc/hosts in the past, but I discovered when editing the device in webgui that I can set the Display name, which would suit me so that I don't have to enter the hostname in /etc/hosts. Unfortunately, when I edit the device, I enter hostname/IP as the IP address, e.g. 1.1.1.1 (public WAN where NAT) and set the Display name. Unfortunately, webgui tells me that a directory with the IP address 1.1.1.1 already exists in /var/www/librenms/rrd. When I delete the directory 1.1.1.1, it sometimes allows me to add the device. Is this a bug in Librenms? Thank you

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.11.0-34-gd31ba0696 (2024-11-30T17:17:09+01:00)
DB Schema | 2024_11_22_135845_alert_log_refactor_indexes (308)
PHP       | 8.2.26
Python    | 3.9.19
Database  | MariaDB 10.5.22-MariaDB
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.8.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No python wrapper pollers found
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

24.11.0

**Comment by laf** [comment]
No bug, whatever you give as the hostname must be unique.

**Comment by siminkuv** [comment]
So should I still continue to edit it in /etc/hosts? Isn't it planned to not make the hostname unique, but to ignore it?

**Comment by murrant** [comment]
Hostname/IP must be unique.  Display Name can be set to anything.
