### ISSUE TITLE
Discovery : VPN on Zywall USG

### ISSUE THREAD

**Issue by Calvario** [librenms/librenms#1679]
Hello,

After I'm pulling out my hair, I find OIDs in ZyXELL ZyWALL (zywall OS) that are not referenced in MIBS.

After analysis, this is what I discovered:

VPN-ID
1.3.6.1.4.1.890.1.6.22.2.4.1.1.1 = INTEGER: 1
1.3.6.1.4.1.890.1.6.22.2.4.1.1.2 = INTEGER: 2

VPN Name
1.3.6.1.4.1.890.1.6.22.2.4.1.2.1 STRING = "VPN Site-to-Site"
1.3.6.1.4.1.890.1.6.22.2.4.1.2.2 STRING = "VPN-L2TP"

VPN Gateway
1.3.6.1.4.1.890.1.6.22.2.4.1.3.1 STRING = "VPN-Gateway-Site-To-Site"
1.3.6.1.4.1.890.1.6.22.2.4.1.3.2 STRING = "VPN-L2TP Gateway"

Protocol
1.3.6.1.4.1.890.1.6.22.2.4.1.4.1 STRING = "IPv4"
1.3.6.1.4.1.890.1.6.22.2.4.1.4.2 STRING = "IPv4"

Enable
1.3.6.1.4.1.890.1.6.22.2.4.1.5.1 = INTEGER: 1
1.3.6.1.4.1.890.1.6.22.2.4.1.5.2 = INTEGER: 1

Connected
1.3.6.1.4.1.890.1.6.22.2.4.1.6.1 = INTEGER: 1
1.3.6.1.4.1.890.1.6.22.2.4.1.6.2 = INTEGER: 0

Do you think it is possible to integrate it?

Thank you

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
