### ISSUE TITLE
Device dependency map multi-link

### ISSUE THREAD

**Issue by devuxnullux** [librenms/librenms#16802]
### The problem

Hi,
My device dependency maps (/maps/devicedependency?group=XX) are showing multiple dependency links, with a new link being added each time the page automatically refreshes. While it creates amusing balloon-like shapes, it’s quite impractical and significantly slows down the browser.
![image](https://github.com/user-attachments/assets/31773da9-7880-48f2-b332-ecdbe11d7e7d)
I’m still using PHP version 8.1, which is outdated, but I believe it’s irrelevant to this issue.

You can reproduce the behavior without waiting for the auto-refresh by toggling the "Highlight Dependencies to Root Device" option, which forces a refresh.

Tested on both Chrome and Firefox on Windows.

BR
 

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.10.1-57-gd8ac25e2d (2024-11-20T15:51:35+01:00)
DB Schema | 2024_11_07_110342_custommap_edge_add_text_align (307)
PHP       | 8.1.13
Python    | 3.6.9
Database  | MariaDB 10.5.15-MariaDB-1:10.5.15+maria~bionic
RRDTool   | 1.7.0
SNMP      | 5.7.3
===========================================

[OK]    Composer Version: 2.8.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[WARN]  PHP version 8.2 is the minimum supported version as of October, 2024. We recommend you update PHP to a supported version (8.3 suggested) to continue to receive updates. If you do not update PHP, LibreNMS will continue to function but stop receiving bug fixes and updates.
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

**Comment by murrant** [comment]
Hmm, odd because I would assume other people would call a single link (assuming these have LAGs between them) a bug.

**Comment by eskyuu** [comment]
I think the issue is that more lines appear whenever the page refreshes.

**Comment by eskyuu** [comment]
https://github.com/librenms/librenms/pull/16816 should fix this
