### ISSUE TITLE
Ability to Define Background Color for Entire Graph Including Legend

### ISSUE THREAD

**Issue by MilanVolf** [librenms/librenms#16805]
### The problem

Hello,

I would like to ask if it is possible in LibreNMS to define the background color for the entire graph, including the legend, similar to how it is possible using the bg=FFFFFF parameter in the URL. Currently, I am using the following URL to display the device availability graph:

graph.php?type=device_availability&device={{ $alert->device_id }}&from=end-24h&to=now&bg=FFFFFF&legend=yes
The issue arises when the email client has a dark theme, and the graphs are transparent, causing display problems. Would it be possible to add an option to color the entire graph area, including the legend, to ensure proper visibility in different email client themes?

I know that the bg=FFFFFF parameter only colors the graph itself without the legend. Could this functionality be extended to include the legend as well?

Thank you for your help and response.

Best regards,
Milan Volf

See the current preview of the email message from the client:
![mail](https://github.com/user-attachments/assets/860cf9ff-4fc0-47fd-b8b2-0216cc0af717)

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.11.0-39-g92a822d (2024-12-03T11:55:49+01:00)
DB Schema | 2024_11_22_135845_alert_log_refactor_indexes (308)
PHP       | 8.2.3
Python    | 3.6.8
Database  | MySQL 5.7.44
RRDTool   | 1.7.0
SNMP      | 5.7.2
===========================================

[OK]    Composer Version: 2.8.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

24.11.0-40-g6b9ef8b

**Comment by murrant** [comment]
Thank you for your submission.  This is a feature request.  Issues are for confirmed bugs.

Please post all feature requests in the community forum: https://community.librenms.org/c/feature-requests/3
