### ISSUE TITLE
Get Device by Mac, IP Address via REST API

### ISSUE THREAD

**Issue by jekhokie** [librenms/librenms#1680]
As a user requesting information about a device via the REST API,
I wish to be able to search for a device via MAC address or IP Address
Such that I can retrieve device information in the same fashion that searching by 'hostname' currently allows for the get_device function.

**Comment by laf** [comment]
I've submitted a PR for this support - however it's not done by get_device, search (at least by ipv4) could return more than a single result so we can't decide what device to return info for so this has to be done via list_devices.
