### ISSUE TITLE
Postfix queue monitoring

### ISSUE THREAD

**Issue by spinza** [librenms/librenms#1681]
We have some scripts there already:
- snmp extension: https://github.com/librenms/librenms/blob/02f39189ebbc64faa5c17dd05c4e858399bd14ae/scripts/postfix-queues
- also in check_mk: https://github.com/librenms/librenms/blob/02f39189ebbc64faa5c17dd05c4e858399bd14ae/scripts/check_mk_agent

Is this implemented anywhere?  In terms of graphing or alerting?  I'd like to do so.

**Comment by laf** [comment]
@spinza That's a check_mk script so you can get graphing, alerting I'm not so sure as It doesn't look like it records to the db so alerting wouldn't be possible.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
