### ISSUE TITLE
Don't get the toner capacity on devices.

### ISSUE THREAD

**Issue by MindTooth** [librenms/librenms#1682]
Hi,

Thank you for an awesome piece of software.  Really enjoyed setting in up and configure it for my organization.  Truly!

The one main issue I am currently experiencing is that the toner details don't get filled in when viewing the WebGUI.
I can do a snmpwalk and get the details using the MIB-strings used in toner.inc.php.

The details get pulled correctly, but at some point along, they don't get inserted, nor updated inside the WebGUI.

Does anyone else experience the same issue?

I will gladly provide a snmpwalk.  Must wait until tomorrow though, as I am writing this on my iPhone.  And I don't have access to Github via my workstation.

**Comment by laf** [comment]
Hi @MindTooth glad you like the software :)

If you can provide the output of the following commands on something like dpaste.de:

```bash
./discovery.php -h HOSTNAME -d -m toner
./poller.php -h HOSTNAME -d -r -m toner
```

Replace HOSTNAME with the devices hostname or ID

**Comment by MindTooth** [comment]
`./discovery.php` https://dpaste.de/FLVx
`./poller.php`https://dpaste.de/Y4XV

There you go :-)  Adding an extra `snmpwalk` of the MIB: https://dpaste.de/CMk1

Thank you for taking the time to reply!

**Comment by laf** [comment]
@MindTooth 

The output has been set to expire so the links no longer work, can you re-post with non-expiring links please.

**Comment by MindTooth** [comment]
@laf:  My bad :-P

`./discover.php` https://dpaste.de/Pigu
`./poller.php` https://dpaste.de/PsW0
`snmpwalk`https://dpaste.de/J482

**Comment by Rosiak** [comment]
@MindTooth 
Can you paste them again please? Expired.

Otherwise I propose that we close this one.

**Comment by laf** [comment]
Think dpaste.de only allows 1 month, best posting the data elsewhere.

**Comment by MindTooth** [comment]
Gist: https://gist.github.com/MindTooth/feac3aa337c948bbf51e

Problem seems to occur for every HP and Konica-Minolta printers.

**Comment by laf** [comment]
Do you have `$config['enable_printers'] = true;` in config.php? From the toner discovery we print out "Toner :" before doing anything, I can't see that in your debug so I'm guessing that config option is not enabled.

**Comment by MindTooth** [comment]
I did not know that was a feature.  I'll be sure to enable it on Monday, and report back to you.

Thanks!

**Comment by MindTooth** [comment]
All hail the God :+1:
