### ISSUE TITLE
Insights into device discovery with sysObjectID

### ISSUE THREAD

**Issue by rudybroersma** [librenms/librenms#16839]
### The problem

We replaced an ABB UPS with a new model and the CS141 SNMP card seems to behave a little different. sysDescr no longer returns "CS141" but not identifies itself as "ABB SNMP Card".  It's now detected as a generic device (instead of Generex UPS)

However.. sysObjectID is unchanged and I'm a bit confused why LibreNMS doesn't catch this card based on the sysObjectID.

includes/definitions/generex-ups.yaml:
    discovery:
        -
            sysObjectID:
                - .1.3.6.1.2.1.33
            sysDescr_regex:
                - '/CS121/i'
                - '/CS141/i'

    # snmpwalk -v2c -c X 10.1.90.20 1.3.6.1.2.1.1.2
    iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.2.1.33

It looks like sysDescr_regex takes precedence over sysObjectID? 

What would be the best way to fix this?

### Output of ./validate.php

```txt
-
```

### Device info

Generex UPS

### Discovery output

```txt
$ ./discovery.php -h 1621  -d
LibreNMS Discovery
SQL[select `migration` from `migrations` order by `id` desc limit 1 [] 0.38ms] 
  
SQL[select count(*) as aggregate from `migrations` [] 0.57ms] 
  
SQL[select version() [] 0.3ms] 
  
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.11.0-83-g9a1a3d86f (2024-12-08T13:13:56+01:00)
DB Schema | 2024_11_22_135845_alert_log_refactor_indexes (311)
PHP       | 8.3.6
Python    | 3.12.3
Database  | MariaDB 10.11.8-MariaDB-0ubuntu0.24.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.4.pre2
===========================================
DEBUG!
LibreNMS config cache cleared and config reloaded.  
SQL[select `config_name`, `config_value` from `config` [] 0.44ms] 
  
SQL[select * from `graph_types` [] 0.24ms] 
  
SQL[SELECT * FROM `devices` WHERE disabled = 0 AND `device_id` = '1621' ORDER BY device_id DESC [] 0.57ms] 
  
10.1.90.20 1621 generic SQL[select * from `devices` where `device_id` = ? limit 1 [1621] 0.45ms] 
  
SQL[select * from `devices_attribs` where `devices_attribs`.`device_id` = ? and `devices_attribs`.`device_id` is not null [1621] 0.38ms] 
  
[FPING] '/usr/bin/fping' '-e' '-q' '-c' '3' '-p' '500' '-t' '500' '-O' '0' '10.1.90.20'
  
response: 10.1.90.20 : xmt/rcv/%loss = 3/3/0%, min/avg/max = 6.48/7.79/10.1  
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Pu' 'udp:HOSTNAME:161' 'SNMPv2-MIB::sysObjectID.0']  
SNMPv2-MIB::sysObjectID.0 = SNMPv2-SMI::mib-2.33
  
  
Modules status: Global+  
OS  
Device  

#### Load disco module core ####
Attempting to initialize OS: generic  
OS initialized: LibreNMS\OS\Generic  
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Pu' '-On' 'udp:HOSTNAME:161' 'SNMPv2-MIB::sysObjectID.0' 'SNMPv2-MIB::sysDescr.0' 'SNMPv2-MIB::sysName.0']  
.*.*.0 = .*.2.1.33
.*.*.0 = ABB SNMP Agent
.*.*.0 = UPS-X-Y-Z
```

### Poller output

```txt
-
```

**Comment by PipoCanaja** [comment]
Hi @rudybroersma 
1.3.6.1.2.1.33 is the base OID of UPSMIB. So this is not at all specific to this vendor or device. That's why both OID and sysdescr are used. 
Feel free to update the YAML (if new device is basically behaving the same as the old one) or create a new os (if not).

**Comment by rudybroersma** [comment]
> Hi @rudybroersma 1.3.6.1.2.1.33 is the base OID of UPSMIB. So this is not at all specific to this vendor or device. That's why both OID and sysdescr are used. Feel free to update the YAML (if new device is basically behaving the same as the old one) or create a new os (if not).

I see. So sysDescr and sysObjectID should both match (AND operator). Not OR.
The card itself hasn't changed, still the same model. 

I'll work on a tiny PR. Thanks
