### ISSUE TITLE
Duplicate entries of devices when displaying Locations with Special-Characters on the Global Map

### ISSUE THREAD

**Issue by Lucheni** [librenms/librenms#1683]
Devices drawn on the **Global Map** gives a consistent amount of duplicates that seemingly differs per address used in **Override sysLocation**:

The the locations have swedish characters in them. So maybe something is up with the handling of characters. I set the location to London, United Kingdom for one of the devices, it was moved to the right location without any duplicates.

**Comment by f0o** [comment]
Please provide some examples so we can try to reproduce it

**Comment by laf** [comment]
Proposing to close in 48 hours unless some examples can be provided.

**Comment by Lucheni** [comment]
I sent f0o some details regarding this incident over irc. The only example address I found where it could be replicated belonged to a customer so did not want to post the address in public.

**Comment by f0o** [comment]
Sorry I didnt get to it yet, last weeks were a mess.

@laf I've some examples from @Lucheni - all of which had Swedish special characters.
I wonder if a htmlentities or similar would solve this issue

**Comment by laf** [comment]
Can you note paste some edited versions up that maintain the chars causing problems?

**Comment by laf** [comment]
I've tested:

Skarpögatan 6-8, Box 27819, 115 27 Stockholm, Sverige

With no issues.

**Comment by laf** [comment]
Still unable to replicate this with examples from @Lucheni :(

**Comment by laf** [comment]
This #1963 may have resolved this. Please feel free to re-open if not.
