### ISSUE TITLE
No dBm operating range for Cisco Catalyst 3560x48 Cisco IOS 15.0(2)SE2 (UNIVERSALK9) 

### ISSUE THREAD

**Issue by Lucheni** [librenms/librenms#1684]
![dbm range limit_cat3560x48_cisco ios 15 0 2 se2 universalk9](https://cloud.githubusercontent.com/assets/5095269/9259167/ad1cf04a-41ff-11e5-916d-eb8fb561dca8.png)

The same Switch model but only the one with IOS version Cisco IOS 12.2(55)SE5 (UNIVERSALK9) gets assigned a dBm range. Not sure if a problem with the newer Cisco IOS 15.0(2)SE2 (UNIVERSALK9) version or LibreNMS.

**Comment by Rosiak** [comment]
Same transceivers in both of them or?

**Comment by Lucheni** [comment]
Tried: snmpwalk xx.xx.xx.xx -v 2c -c public -m CISCO-ENTITY-SENSOR-MIB

But got the following message: *snmpwalk 10.0.10.20 -v 2c -c public -m CISCO-ENTITY-SENSOR-MIB
No log handling enabled - turning on stderr logging Cannot find module (CISCO-ENTITY-SENSOR-MIB): At line 0 in (none) iso.3.6.1.2.1.1.1.0 = STRING: "Cisco IOS Software, C3560E Software (C3560E-UNIVERSALK9-M), Version 15.0(2)SE2, RELEASE SOFTWARE (fc1) Technical Support: http://www.cisco.com/techsupport Copyright (c) 1986-2013 by Cisco Systems, Inc. Compiled Tue 05-Feb-13 12:04 by prod_rel_team"*

**Comment by SaaldjorMike** [comment]
I've got some Catalyst WS-C3560E-12SD, all running firmware 15.0(2)SE2 (same firmware as you). For all dBm sensors in across the multiple 3560E's, I also see a problem with fetching the low+high limits for the sensors.

@Lucheni: Have you tested using a newer firmware since you created this issue?

Checking the data available through SNMP (using `snmptable`) shows that the values are not returned from the switch when using the CISCO-ENTITY-SENSOR-MIB:
```
SNMP table: CISCO-ENTITY-SENSOR-MIB::entSensorValueTable

 entSensorType entSensorScale entSensorPrecision entSensorValue entSensorStatus entSensorValueTimeStamp entSensorValueUpdateRate entSensorMeasuredEntity
       celsius          units                  1            267              ok         318:19:44:29.40              600 seconds                       ?
       voltsDC          units                  2              0              ok         318:19:44:29.40              600 seconds                       ?
       amperes          milli                  1            388              ok         318:19:44:29.40              600 seconds                       ?
           dBm          units                  1            -13              ok         318:19:44:29.40              600 seconds                       ?
           dBm          units                  1            -40              ok         318:19:44:29.40              600 seconds                       ?
       celsius          units                  1            403              ok         318:19:44:29.32              600 seconds                       ?
       voltsDC          units                  2            327              ok         318:19:44:29.32              600 seconds                       ?
       amperes          milli                  1            201              ok         318:19:44:29.32              600 seconds                       ?
           dBm          units                  1            -20              ok         318:19:44:29.32              600 seconds                       ?
           dBm          units                  1            -94              ok         318:19:44:29.32              600 seconds                       ?
```
```
SNMP table: CISCO-ENTITY-SENSOR-MIB::entSensorThresholdTable

 entSensorThresholdSeverity entSensorThresholdRelation entSensorThresholdValue entSensorThresholdEvaluation entSensorThresholdNotificationEnable
                      major             greaterOrEqual                     740                        false                                false
                      minor             greaterOrEqual                     700                        false                                false
                      minor                lessOrEqual                       0                        false                                false
                      major                lessOrEqual                     -40                        false                                false
```

**Comment by Rosiak** [comment]
Any news on this @Lucheni ?

**Comment by Lucheni** [comment]
Unfortunately no, @Rosiak 

Will be a firmware upgrade on the site late March, Early April. Can see if the newest OS levels resolves the issue.

**Comment by Rosiak** [comment]
Closing as we assume this is fixed in newer firmware, I have been unable to verify this tho'.
