### ISSUE TITLE
Discovery : CPU, Memory, Session usage on Sonciwall

### ISSUE THREAD

**Issue by Calvario** [librenms/librenms#1686]
Hello,

Is it possible to add the following OIDs for os "sonicwall" :

CPU usage as percent
OID = 1.3.6.1.4.1.8741.1.3.1.3.0
Return = iso.3.6.1.4.1.8741.1.3.1.3.0 = Counter32: 1

Memory usage as percent
OID = 1.3.6.1.4.1.8741.1.3.1.4.0
Return = iso.3.6.1.4.1.8741.1.3.1.4.0 = Counter32: 11

Maximum Connections
OID = 1.3.6.1.4.1.8741.1.3.1.1.0
Return = iso.3.6.1.4.1.8741.1.3.1.1.0 = Counter32: 96000

Current Connections
OID = 1.3.6.1.4.1.8741.1.3.1.2.0
Return = iso.3.6.1.4.1.8741.1.3.1.2.0 = Counter32: 1127

Thanks.

**Comment by Rosiak** [comment]
Hi @Calvario,
Is this still relevant?
If so, I'll get it done.

**Comment by Calvario** [comment]
Hello @Rosiak,
Yes, it still relevant, but the PR #1957 do the two first request.

**Comment by laf** [comment]
Please provide the output of `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .`
