### ISSUE TITLE
Update Hipchat transport to use API 2.0 by default

### ISSUE THREAD

**Issue by MLWALK3R** [librenms/librenms#1688]
Update hipchat transport to support their new 2.0 API by default and update the documentation for it too.

**Comment by laf** [comment]
The webui is pretty straight forward, you only need to enter the first three details which are simple enough. Changing to v2 of API might not change how we ask for info though :)

We can look at using the new API. Just have to redo some code I expect.

**Comment by shimamizu** [comment]
Did 2587 ever get fully deployed? It looks to me like it still doesn't work when I try in the current LibreNMS branch. I'm wanting to use v2. This currently works in my production Observium btw, but not in my LibreNMS.

**Comment by laf** [comment]
moved to https://community.librenms.org/t/feature-request-update-hipchat-transport-to-use-api-2-0-by-default/736

**Comment by laf** [comment]
Support has just been merged in.
