### ISSUE TITLE
php memory_limit not applied for one graph

### ISSUE THREAD

**Issue by fbouynot** [librenms/librenms#16905]
### The problem

When reaching `/poller/performance`, the per-module line does not load.
![image](https://github.com/user-attachments/assets/e516a311-fcb3-4e84-af10-4104f27c3f5a)

If I click on the placeholder link that replace the daily graph, and then open in a new tab the `Show RRD Command` link, I receive a `504 Gateway Time-out`.
At the same time, I have the following log in `librenms.log`:

```
escapeshellcmd(): Command exceeds the allowed length of 2097152 bytes {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): escapeshellcmd(): Command exceeds the allowed length of 2097152 bytes at /opt/librenms/includes/html/graphs/graph.inc.php:75)"} 
```

The php memory limit looks in place everywhere.
![image](https://github.com/user-attachments/assets/09803aac-7d1d-454e-bb10-fe5bd76bc29d)

### Output of ./validate.php

```txt
2024-12-20 16:51:25 librenms@librenms-monitoring:~ [master] $ ./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.12.0-8-g3c4056cc9 (2024-12-20T09:16:39+01:00)
DB Schema | 2024_10_20_154356_create_qos_table (310)
PHP       | 8.3.14
Python    | 3.13.0
Database  | MariaDB 10.11.10-MariaDB
RRDTool   | 1.9.0
SNMP      | 5.9.4.pre2
===========================================

[OK]    Composer Version: 2.8.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No python wrapper pollers found
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### Anything in the logs that might be useful for us?

I could display this graph a few times (2-3) though, I don't know why it passed.
I think I alwayd had the issue.

**Comment by PipoCanaja** [comment]
@fbouynot The answer must be  in the PHP config somewhere. You probably have a bit of config that is not updated somehow. Can be FPM, CLI, Apache, etc.
