### ISSUE TITLE
Allow multiple devices with same hostname

### ISSUE THREAD

**Issue by miken32** [librenms/librenms#1692]
We monitor equipment at remote client sites using NAT to get to the equipment behind a router. If we want to monitor multiple devices with the same hostname, we are unable to.

The first step in the solution would be to use the hostname and port number in any checks for duplicates, rather than just the hostname. Beyond that, some differentiation in the UI would be desirable, to tell different devices apart.

**Comment by miken32** [comment]
```diff
--- a/includes/functions.php
+++ b/includes/functions.php
@@ -269,7 +269,7 @@ function addHost($host, $snmpver, $port = '161', $transport = 'udp', $quiet = '0
 
     list($hostshort) = explode(".", $host);
     // Test Database Exists
-    if (dbFetchCell("SELECT COUNT(*) FROM `devices` WHERE `hostname` = ?", array($host)) == '0') {
+    if (dbFetchCell("SELECT COUNT(*) FROM `devices` WHERE `hostname` = ? AND port = ?", array($host, $port)) == '0') {
         if ($config['addhost_alwayscheckip'] === TRUE) {
             $ip = gethostbyname($host);
         } else {
```

**Comment by f0o** [comment]
@miken32 wouldnt it be easier to place a poller-box behind the NAT so you wouldnt need the NAT any more? (ref: Distributed Poller Setup)

**Comment by laf** [comment]
Non-unique host names are going to introduce other issues, they expected to be unique in a lot of areas which would mean more updates than just the initial addhost 

I'm not a fan of trying to support this if I'm honest and would suggest either pointing additional hostnames to the end ip or use came records or as @f0o has mentioned, distributed polling.

**Comment by miken32** [comment]
Distributed polling would definitely be the answer, if we could convince clients to pay for more hardware! I'll look at scripting some changes to the hosts file and see what I can do with that I guess.

**Comment by masonke** [comment]
This might help, I have been running my distributed pollers on VMs and they are performing well. No need for a standalone system

**Comment by tuxis-ie** [comment]
Isn't a Raspberry Pi good enough as a remote poller?

**Comment by laf** [comment]
Polling yes, however because it's arm based then the rrd files it creates would be incompatible if you run intel chips in your rrdcached box.

**Comment by laf** [comment]
@miken32 feel free to re-open this if necessary.
