### ISSUE TITLE
Add polled IP address to the overview

### ISSUE THREAD

**Issue by masonke** [librenms/librenms#1698]
It would be handy to have the ip address that was polled added to the lists and overview pages. The IP address of the interface is displayed when you drill down, but knowing what address was polled would be great.

**Comment by paulgear** [comment]
:+1:

**Comment by f0o** [comment]
:+1:

**Comment by laf** [comment]
Can you provide more information, overview pages and lists are quite generic :(

**Comment by laf** [comment]
Proposing to close in 48 hours.

**Comment by masonke** [comment]
Go ahead and close now

**Comment by laf** [comment]
Happy to actually implement the update, just genuinely need more info as it's not clear what you're after :)

**Comment by masonke** [comment]
Oh, I know you would, but am in the hospital for a bit and won't be able to get the info for a week or so. 

I can open a new one later with all the details in one shot. 

Thanks!

**Comment by paulgear** [comment]
I think we should leave this open until at least Sunday. :-)

**Comment by laf** [comment]
I'm unsure what Sunday has to do with this. If someone has the info to be able to get the issue fixed just pop it into here so it can be done.

**Comment by tuxis-ie** [comment]
I would like to see it only on the device-page itself, as it will clutter the rest of the overviews, IMHO.

**Comment by laf** [comment]
Are we talking about having the IP of what the DNS was resolved to? We don't store this information, I guess we could but I'm really not certain if it's worth storing the value of this.

Anyone else?

**Comment by tuxis-ie** [comment]
It would be the IP that the snmp-client talked to. So it should be stored, not requested upon view.

**Comment by laf** [comment]
What's the need for this? I don't see the benefit if I'm honest.

**Comment by tuxis-ie** [comment]
Me neither, but IF this would be implemented, I would like it not to be too visual.

**Comment by masonke** [comment]
It would be for troubleshooting, to help when discovery finds a device and puts it in by name. Plus, if someone screws up a DNS or hosts entry, it is easier to figure out what to fix.
~KEM

**Comment by laf** [comment]
I don't personally see the benefit of this seeing as we would need to then store the IP of the resolved domain. I'll leave this to someone else to add functionality for if they see fit.

**Comment by laf** [comment]
Tagging #2559

**Comment by adambialy** [comment]
Hi. How about having same system like in nagios? So for example you have two fields to fill when you adding device name and ip address. Later the ip address will be preferred in polling device over name. If someone wants fqdn will be able type same record into both fields. How about that?

**Comment by laf** [comment]
Tagging #2598

**Comment by adambialy** [comment]
Hi. How about having same system like in nagios? So for each host you got hostname and ip address(or fqdn). In this case librenms will poll ip address(or fqdn) rather than name but messages/error reporting will mention name rather than ip address.

**Comment by paulgear** [comment]
@adambialy I think that's a very different suggestion to what this issue is about; this issue is just about keeping a log of which IP address(es) the configured name resolved to at the time of last poll.

**Comment by rlphnger** [comment]
Just having the last polled IP in the device overview, maybe under "System Name", would be really neat. People who need it, will know where to find it. And people who only uses DNS, they shouldn't be too bothered with it being there, as it won't be very flashy.
I myself would really like that. Would be good for troubleshooting and if there is a DNS problem.
