### ISSUE TITLE
Standard Globe map

### ISSUE THREAD

**Issue by macbook8** [librenms/librenms#1720]
When I enable Standard Globe map and receive error message as below: 

Unable to set property 'data' of undefined or null reference 

Please advise.

Thanks!

**Comment by laf** [comment]
Can you post your config for the map you've enabled please.

**Comment by macbook8** [comment]
## Have a look in includes/defaults.inc.php for examples of settings you can set here. DO NOT EDIT defaults.inc.php!

### Database config
$config['db_host'] = "localhost";
$config['db_user'] = "librenms";
$config['db_pass'] = "XXXXXXXX";
$config['db_name'] = "librenms";
$config['db']['extension'] = 'mysqli';// mysql or mysqli

### Memcached config - We use this to store realtime usage
$config['memcached']['enable']  = FALSE;
$config['memcached']['host']    = "localhost";
$config['memcached']['port']    = 11211;

### Locations - it is recommended to keep the default
#$config['install_dir']  = "/opt/librenms";

### This should *only* be set if you want to *force* a particular hostname/port
### It will prevent the web interface being usable form any other hostname
#$config['base_url']        = "http://librenms.company.com";

### Enable this to use rrdcached. Be sure rrd_dir is within the rrdcached dir
### and that your web server has permission to talk to rrdcached.
#$config['rrdcached']    = "unix:/var/run/rrdcached.sock";

### Default community
$config['snmp']['community'] = array("public");

### Authentication Model
$config['auth_mechanism'] = "mysql"; # default, other options: ldap, http-auth
#$config['http_auth_guest'] = "guest"; # remember to configure this user if you use http-auth

### List of RFC1918 networks to allow scanning-based discovery
#$config['nets'][] = "10.0.0.0/8";
#$config['nets'][] = "172.16.0.0/12";
#$config['nets'][] = "192.168.0.0/16";

# following is necessary for poller-wrapper
# poller-wrapper is released public domain
$config['poller-wrapper']['alerter'] = FALSE;
# Uncomment the next line to disable daily updates
#$config['update'] = 0;

$config['update'] = 0;
$config['enable_billing'] = 1;

# Map
$config['front_page'] = "pages/front/globe.php";
# $config['front_page']       = "pages/front/map.php";

**Comment by laf** [comment]
Are you device addresses real addresses?

Overall I'd highly suggest ensuring php-curl is installed and then setting:

```php
$config['front_page'] = 'pages/front/tiles.php';
$config['geoloc']['latlng'] = true;
```

**Comment by laf** [comment]
@macbook8 if this hasn't resolved the issue for you then feel free to re-open this.
