### ISSUE TITLE
Add 'oxidized' http_source support to LibreNMS

### ISSUE THREAD

**Issue by killsudo** [librenms/librenms#1723]
The end goal is to allow LibreNMS users to setup a standalone 'Oxidized' box let LibreNMS and Oxidized communicate only via api calls back and forth. This will allow for the automatic backup of devices added to LibreNMS via Oxidized. If the device is disabled/removed from LibreNMS then the config backups stop. No more managing devices to be backed up separately in 'Oxidized' when LibreNMS is already our 'front-end' to config backups.

https://github.com/ytti/oxidized#source-http

Extend the LibreNMS api to provide a list of devices to Oxidized to backup via its source-http function.

Extend the LibreNMS api to provide a 'group' which the device belongs?

Allow LibreNMS to extract the device model which is already learned from polling and supply that to Oxidized. IE JunOS / IOS / NX-OS etc.

Add LibreNMS $config option to provide a default User/Pass word for Oxidized to use on devices.
Add LibreNMS $config option to provide a default connection type 'ssh or telnet' for Oxidized to use on devices.

Add per device over-ride option to enable/disable 'config backup'
Add per device over-ride option to change Oxidized User/Pass
Add per device over-ride option to change Oxidized connection type 'ssh or telnet'

When successful the 'Oxidized' backup routine will be dynamic on each run by leveraging LibreNMS information to learn the device hostname / model / group / input to capture configs from relevant devices.

Issues: 'Groups'
Should we allow devices to be manually added to a group?
Should we enable/disable config backups on a whole group?
Should a 'group' be able to over-ride the default username/password supplied to the Oxidized.

Currently we leverage rancid 'groups' to create 'Core Routers' / 'Core Switches' / 'Internal Firewalls' / 'Customer Firewalls' / 'Rack Switches'. This helps to keep the configuration repo organized when viewing from a web browser or running scripts against a directory to extract certain lines from configs.

Zenoss handles this by allowing us to tag a 'group' of devices with a 'rancid' group which all physical devices in that group inherit. When Zenoss generates the router.db file the proper devices are sorted into rancid groups which with their own router.db file.

See  'Rancid zProperties' @ http://mwallraf.github.io/ZenPacks.TwoNMS.Rancid/

**Comment by masonke** [comment]
How would we handle checking for config changes when a trap or syslog event comes in? Or, would that stay with Oxidized?

**Comment by killsudo** [comment]
For anyone else coming across this, LibreNMS already has an api endpoint for returning the devices.

The user+pass is stored on the Oxidized server. Unknown os types are ignored.

http://docs.librenms.org/API/API-Docs/#api-route-21

~ $ curl -H 'X-Auth-Token: 96c06188146cfcd6894c541958c92c25' http://monitor.xxx.net/api/v0/oxidized
[
    {
        "hostname": "localhost",
        "os": "linux"
    },
    {
        "hostname": "csw3.xxx.net",
        "os": "ios"
    },
    {
        "hostname": "csw1.xxx.net",
        "os": "ios"
    },
    {
        "hostname": "csw2.xxx.net",
        "os": "ios"
    },
    {
        "hostname": "csw4.cybercon.net",
        "os": "ios"
    },
    {
        "hostname": "rsws1d.xxx.net",
        "os": "ios"
    },
    {
        "hostname": "s2casw",
        "os": "junos"
    },
    {
        "hostname": "cs27sw1.xxx.net",
        "os": "ios"
    },

**Comment by laf** [comment]
@killsudo I'm going to be adding some more support for oxidized, just going through some of your points - hope I understand what you mean by them.

> Extend the LibreNMS api to provide a 'group' which the device belongs?

Can do, using the device grouping ok? Or the device type?

> Allow LibreNMS to extract the device model which is already learned from polling and supply that to Oxidized. IE JunOS / IOS / NX-OS etc.

Is that not done via the os we export?

> Add LibreNMS $config option to provide a default User/Pass word for Oxidized to use on devices.

I'd probably say you should just do this in the default oxidized config no?

> Add LibreNMS $config option to provide a default connection type 'ssh or telnet' for Oxidized to use on devices.

Can do that in Oxidized and we don't generate oxidized config (maybe we could).

> Add per device over-ride option to enable/disable 'config backup'

Yup.

> Add per device over-ride option to change Oxidized User/Pass

I'm wary of storing credentials in LibreNMS :/

> Add per device over-ride option to change Oxidized connection type 'ssh or telnet'

Does it support this per device?

> Issues: 'Groups'
> Should we allow devices to be manually added to a group?
> Should we enable/disable config backups on a whole group?
> Should a 'group' be able to over-ride the default username/password supplied to the Oxidized.

Grouping support with these features is a bit tricker as we don't have that level of customisation but it is possible.

> Zenoss handles this by allowing us to tag a 'group' of devices with a 'rancid' group which all physical devices in that group inherit. When Zenoss generates the router.db file the proper devices are sorted into rancid groups which with their own router.db file.

We could add the ability to provide tags to device groups to make it more useable elsewhere. @f0o any thoughts on extending device groups out so we could say create a device group to match X devices and then allow to tag that group as 'core routers' to be used in oxidized?

**Comment by f0o** [comment]
Sounds easy to do. Just to clarify, by matching X devices, do you mean assigning a group over a handfull of device_id's ?

I might get a tag-draft done today while waiting for my plane

**Comment by laf** [comment]
@killsudo Aside from storing credentials which we are reluctant to do, have we now covered all of your queries on this now?

**Comment by Rosiak** [comment]
@killsudo 
Any news on this?
