### ISSUE TITLE
Restricted user see information about other routers, if one of his routers is in same Subnet as other routers.

### ISSUE THREAD

**Issue by eikik87** [librenms/librenms#1732]
Hi,

I want to use Librenms to give my customers ability to view their routers or connections. I only give my customer access to his router. But when interface of his router has same subnet as another router, that I have not given my customer the ability to view. He will see the information about another interface that as same Subnet.

My problem is there are alot of routers with same subnet. For example RFC 1918 numbers.

![image](https://cloud.githubusercontent.com/assets/13901674/9405992/23ae755c-47ec-11e5-9f88-d9aa9c7876c6.png)

I really need to be able to turn off this feature globally on normal users.

**Comment by f0o** [comment]
Should be possible
