### ISSUE TITLE
Transport : Pushover content message use alert template

### ISSUE THREAD

**Issue by Calvario** [librenms/librenms#1733]
Hello,

Is it possible to change the Pushover transport method to manage the "alert template" for personalized alert message ?

Thanks

**Comment by f0o** [comment]
Please clarify. I dont understand the request/issue

**Comment by Calvario** [comment]
When I receive a notification in Pushover, the message is "Faults xxxxxxxx".

But I have defined an alert template that works perfectly by email but not by Pushover.

**Comment by f0o** [comment]
Ah ok, i'll take a look later today

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
