### ISSUE TITLE
Feature Request: Add GPS/NTP support for Microsemi SyncServer

### ISSUE THREAD

**Issue by RobsanInc** [librenms/librenms#1739]
LibreNMS Team,

The Microsemi (previously Symmetricom) NTP server uses a Linux based OS with an additional MIB for gathering NTP and GPS statistics.  I would like support added for the SYMM-SMI-MIB.  LibreNMS discovers this device as a Linux server, but I would like to change that to 'Timing'.  I think 'Timing' would be more appropriate than NTP or 'Server' because it is a broader scope that could include PTP, IRIG, etc.

This would be a good example to use for expanding the "How do I add support for a new OS?" section of the FAQ.  The "Basic recognition of EdgeOS" is a pretty simple example for adding a new device OS but it doesn't go into any detail about new MIB support or adding graphs to device tabs.

Here is the output from:

./discovery.php -h HOSTNAME -d -m os
http://www.rzatek.com/librenms/sync-server_disc

./poller.php -h HOSTNAME -d -r -m system,os
http://www.rzatek.com/librenms/sync-server_poll

The MIB:
http://www.rzatek.com/librenms/SYMM-SMI-MIB

Syncserver snmp walk, looks like the tabular SYMM-SMI-MIB::symmTTM is all that's needed:

http://www.rzatek.com/librenms/sync-server_walk

32X32 Icon:
http://www.rzatek.com/librenms/microsemism.png

Thanks,
Rob

**Comment by laf** [comment]
I've done the detection for now.

Can you let us know what you want graphing with regards to the timing side of things please?

**Comment by laf** [comment]
No further info provided.
