### ISSUE TITLE
REST API: Ability to Obtain Connections/Relationships

### ISSUE THREAD

**Issue by jekhokie** [librenms/librenms#1752]
I would like to be able to obtain relationships between devices using the REST API - in other words, if I have a particular interface/port discovered via the API, I would like to be able to find out what other device the particular interface/port is connected to.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
