### ISSUE TITLE
Ports are reversed if map elements moved

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#1754]
the description of ports should change respectively if devices placed on the other side.

http://snag.gy/DAol5.jpg

http://snag.gy/mnJFv.jpg
http://snag.gy/ddtDU.jpg

**Comment by laf** [comment]
I'm not sure we can fix this per se, the label is just one string and visjs doesn't appear to have an option to keep it from moving. You can set it to be horizontal which then doesn't do this but the labels tend to collide, try this in config.php (you can also make other changes to get it how you want):

```php
$config['network_map_vis_options'] = '{
  layout:{
      randomSeed:2
  },
  "edges": {
    "smooth": {
        enabled: false
    },
    font: {
        size: 12,
        color: "red",
        face: "sans",
        background: "white",
        strokeWidth:3,
        align: "horizontal",
        strokeWidth: 2
    }
  },
  "physics": {
    "forceAtlas2Based": {
      "gravitationalConstant": -800,
      "centralGravity": 0.03,
      "springLength": 50,
      "springConstant": 0,
      "damping": 1,
      "avoidOverlap": 1
    },
    "maxVelocity": 50,
    "minVelocity": 0.01,
    "solver": "forceAtlas2Based",
    "timestep": 0.30
  }
}';
```

**Comment by vitalisator** [comment]
Answer from vis, developer:
"Hi, This is not possible, the labels are independent of which side they are on, nor will this be supported. I would suggest using the arrows of the edges to indicate direction. Regards, Alex"

could it be a solution for us to draw an arrow in one edge of connection, if the arrows are in line (with the ">" arrow in the label, indicate the right direction?

**Comment by laf** [comment]
I'm not quite clear on what you mean by that, regardless of what we draw the text is rotated once you move a device to the other side of the linked device.

**Comment by vitalisator** [comment]
see #1787

**Comment by laf** [comment]
Merged in :)
