### ISSUE TITLE
Refresh Disabled

### ISSUE THREAD

**Issue by fran-nlt** [librenms/librenms#1763]
![captura](https://cloud.githubusercontent.com/assets/13962782/9475003/5676891a-4b3a-11e5-8f1a-2827d96211e5.PNG)

Hi
The Refresh is Disabled, when click refresh not happens nothing

**Comment by laf** [comment]
We have certain pages which refresh is disabled on, as this looks like the overview page with widgets then this is one of them as that particular page refreshes the widgets automatically.

**Comment by fran-nlt** [comment]
Thanks!
