### ISSUE TITLE
NFSen integration Top-Talkers display

### ISSUE THREAD

**Issue by ipguru99** [librenms/librenms#1764]
I got NFSen integrated! We had been using flow-tools.. but I would really like to get Top Talkers into the Netflow tab of librenms. I can provide testing on a ton of Cisco devices if needed.. or any other help to get this done. Thanks!!

**Comment by laf** [comment]
@ipguru99 if you would be willing to share your directory structure and the rrd files that show top talkers I'm sure we can add this.

**Comment by ipguru99** [comment]
That is my problem...I can get the info with nfdump, but I don't know how
to get it into an RRD file. HERE
<http://uknof.uknof.org.narkive.com/k7c54ocg/generate-an-rrd-from-nfdump>
is a link that I thought could get me started, but I am just a networking
guy ;-)

A simple 'nfdump' and an 'rrdtool update blah.rrd' could do it, but I don't
know how to tie all that together? The interface is so smooth, I would love
to give my customers something inside the interface, rather than have them
go to some homemade crap I can give them..

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by ipguru99** [comment]
Hello!

Turns out my customers like having this data outside of Nacho (LibreNMS). There is a lot of data available through Nacho, so they have told me they like keeping it separate.. and NFSen used by their Help Desk is not always open (very unlike LibreNMS). 

I can close this issue.. or you guys can.. either way, please just let me know what I can do. This NMS rocks!!
