### ISSUE TITLE
UCD-SNMP-MIB rather than HOST-RESOURCES-MIB

### ISSUE THREAD

**Issue by tychota** [librenms/librenms#1768]
Hi,

former observium user so except dumb question :)

Long time ago, I made a little patch, just for my installlation:

``` diff
--- /opt/observium/includes/discovery/storage/host-resources-mib.inc.php>   (révision 6350)
+++ /opt/observium/includes/discovery/storage/host-resources-mib.inc.php>   (copie de travail)
@@ -21,7 +21,8 @@
   if ($debug && count($cache_discovery['host-resources-mib'])) { print_vars($cache_discovery['host-resources-mib']); }
 }

-if (count($cache_discovery['host-resources-mib']))
+if (false)
 {
   echo(" $mib ");

@@ -105,7 +106,8 @@
     unset($deny, $fstype, $descr, $size, $used, $units, $path, $dsk, $hc);
   }
 }
-else if (count($cache_discovery['ucd-snmp-mib']))
+else
 {
   // Discover 'UCD-SNMP-MIB' if 'HOST-RESOURCES-MIB' empty.
   $mib = 'UCD-SNMP-MIB';
```

This was in order to replace default HOST-RESOURCES-MIB by UCD-SNMP-MIB  that perform better on a btrfs filesystem.

Is it a simple way of enabling a btrfs compliant MIB for storage in LibreNms ??

**Comment by tychota** [comment]
I should say that whatever LibreNms do, it is not working for me: 

Now i have only thoose disk dicovered:
``` 
/		
/boot		
/dev/shm		
/run		
/run/lock		
/sys/fs/cgroup
```
instead of all the btrfs mount:

Debugging further:

```snmpwalk -cpublic -v2c localhost .1.3.6.1.2.1.25.2.3.1.3```
produces
```
HOST-RESOURCES-MIB::hrStorageDescr.1 = STRING: Physical memory
HOST-RESOURCES-MIB::hrStorageDescr.3 = STRING: Virtual memory
HOST-RESOURCES-MIB::hrStorageDescr.6 = STRING: Memory buffers
HOST-RESOURCES-MIB::hrStorageDescr.7 = STRING: Cached memory
HOST-RESOURCES-MIB::hrStorageDescr.8 = STRING: Shared memory
HOST-RESOURCES-MIB::hrStorageDescr.10 = STRING: Swap space
HOST-RESOURCES-MIB::hrStorageDescr.31 = STRING: /
HOST-RESOURCES-MIB::hrStorageDescr.34 = STRING: /boot
HOST-RESOURCES-MIB::hrStorageDescr.40 = STRING: /run
HOST-RESOURCES-MIB::hrStorageDescr.42 = STRING: /dev/shm
HOST-RESOURCES-MIB::hrStorageDescr.43 = STRING: /run/lock
HOST-RESOURCES-MIB::hrStorageDescr.44 = STRING: /sys/fs/cgroup
```
while 

```snmpwalk -v 2c -c public localhost .1.3.6.1.4.1.2021.9.1.2```
produces
```
UCD-SNMP-MIB::dskPath.1 = STRING: /
UCD-SNMP-MIB::dskPath.2 = STRING: /home
UCD-SNMP-MIB::dskPath.3 = STRING: /var
UCD-SNMP-MIB::dskPath.4 = STRING: /boot
UCD-SNMP-MIB::dskPath.5 = STRING: /dev/vg/home
```

Second result IS what I attented to be.
But maybe you guys have a better solution (for example one that also carry btrfs submodules), allowing me to set up alerts if ```/home/xxxx/``` go over his quota.

**Comment by tychota** [comment]
Maybe it is just better to do a btrfs agent, like there is a drbd one ?

**Comment by laf** [comment]
Thanks for the info @tychota. Will have to work something out here on how we can do this.

**Comment by paulgear** [comment]
@tychota So is the difference here that /home and /dev/vg/home are not show in the UCD MIB?

**Comment by tychota** [comment]
Exactly the contrary . They **are** shown in UCD but not in host ressources. Host ressources has a poor for lvm (afaik)  and btrfs based partition. 

Observium had some support for this (actually just need to force a condition with `if (false)` abd do some other changes : hacky but works. Libremns doesn't have such support. 

I have no time for know to send a PR.

**Comment by arjitc** [comment]
was just about to report this, having pretty much the same issue wherein the LVMs aren't detected.

**Comment by laf** [comment]
Possible resolved with http://docs.librenms.org/Support/FAQ/#why-are-some-of-my-disks-not-showing. Closing until further info provided
