### ISSUE TITLE
NSD & Unbound Agent

### ISSUE THREAD

**Issue by tychota** [librenms/librenms#1769]
I hope you won't consider this as dumb question.
# Context

I run a private open dns resolver that is properly rate limited. I get a bunch of scripts that rate limit some type of DNS Query and adapt themselves when a new DDOS comes. Then they provides a custom fail-to-ban that temporally ban or set a very hight rate limit for IP that are part of the DDOS.

As you can see, it is quite experimental stuff so a good monitoring is vital for this.
# Feature Request

Back to the time I used observium, there were a Unbound agent.
I think in the same time it could be useful to do a NSD one.

What do you guys think ?
Never did agent, is it hard to do /time consuming ??

**Comment by f0o** [comment]
Hi @tychota,

It depends if you need alerting or not.
If it's only graphing that you need, then have a look at existing munin-plugins for nsd/unbound stats.
The Unix-Agent can execute most munin-plugins and autograph them, it's very easy and munin provides a lot of user-contributed plugins.

However, you want the addition of Alerting you need to code an own unix-agent module.
Have a look at some existing modules in `includes/polling/unix-agent/`.
It's important for Alerting that you store the values of anything you want to monitor in the MySQL.
I suggest having a table unbound or similar to store your values, I dont think you can squeeze that in somewhere else.

**Comment by tychota** [comment]
Is it something you want upstream (in core).
If I do a PR, should I structure it into a module or just include it with other agent ??

**Comment by laf** [comment]
@tychota We would love any contributions to be submitted back to us so we can improve the software.

**Comment by f0o** [comment]
@tychota Whether to use a module or the agent is entirely up to you. If you're in an environment that doesn't permit the agent then naturally the module is the only way to go.

If you decide on doing an agent that's not part of the munin-plugins, please submit the PR towards the librenms-agent repository instead of this one.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
