### ISSUE TITLE
"PROBLEM ... got better" instead of "RECOVERY"

### ISSUE THREAD

**Issue by rasssta** [librenms/librenms#1770]
Switch log:
Aug 27 01:51:09  311622 %LINEPROTO-5-UPDOWN: Line protocol on Interface GigaEthernet0/10, changed state to down

Libre alert log:
2015-08-27 01:55:18	<device>	#1: GigaEthernet0/10;	Cust Port status up/down	Alert

At 10:17ish I disabled the port on the switch so it became admin down (conf t -> int gi0/10 -> shutdown)

It then became Better(!)...

2015-08-27 10:21:01	<device>	Cust Port status up/down	Better

...and issued a mail with the following info:

PROBLEM: Alert for device <device> - Cust Port status up/down got better
Severity: critical

Timestamp: 2015-08-27 10:21:01
Unique-ID: 465
Rule: Cust Port status up/down

Alert sent to: NOC <mail>

Followed by:

2015-08-27 10:21:03	<device>	Cust Port status up/down	Ok

But no RECOVERY mail.

**Comment by f0o** [comment]
I hope this issue can be resolved with this very simple patch:
```patch
diff --git a/alerts.php b/alerts.php
index fafc909..7a0f7af 100755
--- a/alerts.php
+++ b/alerts.php
@@ -193,7 +193,7 @@ function RunFollowUp() {
             $state = 4;
         }
 
-        if ($state > 0) {
+        if ($state > 0 && $n > 0) {
             $alert['details']['rule'] = $chk;
             if (dbInsert(array('state' => $state, 'device_id' => $alert['device_id'], 'rule_id' => $alert['rule_id'], 'details' => gzcompress(json_encode($alert['details']), 9)), 'alert_log')) {
                 dbUpdate(array('state' => $state, 'open' => 1, 'alerted' => 1), 'alerts', 'rule_id = ? && device_id = ?', array($alert['rule_id'], $alert['device_id']));
```

Please Apply it and report back :)

**Comment by laf** [comment]
@rasssta have you been able to test this?

**Comment by rasssta** [comment]
Oh rite, yeah I actually had the same scenario today and it worked like supposed to (using this patch). So this can be closed/merged! :)

**Comment by f0o** [comment]
Awesome, will PR this up after breakfast :+1:

**Comment by f0o** [comment]
Closing in favour of the PR #1817
