### ISSUE TITLE
Apple Logo

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#1775]
Awaiting answer of Apple Inc. regarding the usage of their logo.

Keeping this one open to avoid questions from users and as 'reminder'

Tagging #1773 #1774

**Comment by rickheil** [comment]
Perhaps the Mac Logo might work? There is already some guidelines on using it.

https://developer.apple.com/softwarelicensing/agreements/maclogo.php

**Comment by Rosiak** [comment]
Proposing to close this one as I don't see this being a problem.
