### ISSUE TITLE
Graphs -NAN

### ISSUE THREAD

**Issue by fran-nlt** [librenms/librenms#1778]
Hi
I Install LibreNMS with the Installation Guide, but not Graphs

![captura](https://cloud.githubusercontent.com/assets/13962782/9530866/cdc28fc4-4cd8-11e5-8599-56a3f1137840.PNG)
![captura2](https://cloud.githubusercontent.com/assets/13962782/9530888/eeedecfc-4cd8-11e5-9524-431c19808c4d.PNG)

**Comment by fran-nlt** [comment]
![captura](https://cloud.githubusercontent.com/assets/13962782/9530912/0e33a584-4cd9-11e5-92a0-782b124c9677.PNG)

Cron.d/librenms

**Comment by fran-nlt** [comment]
![captura](https://cloud.githubusercontent.com/assets/13962782/9531046/feecd3f6-4cd9-11e5-85ed-18edef7438b4.PNG)

**Comment by Rosiak** [comment]
ls -la /opt/librenms/rrd/

**Comment by fran-nlt** [comment]
Thanks
I changed the propietary this directory.
I wait for moment

**Comment by fran-nlt** [comment]
Not but no very important.
Localhost no graphs
Device add yes graphs

**Comment by laf** [comment]
@fran-nlt If you are getting graphs for devices you've added after localhost then this is down to permissions. Please do:

```bash
chown -R librenms:librenms /opt/librenms/rrd/
```

**Comment by fran-nlt** [comment]
@laf yes, i apply this command, but not graphs in the
