### ISSUE TITLE
Initial Install created duplicate key entry

### ISSUE THREAD

**Issue by TheCrockett** [librenms/librenms#1780]
[root@librenms]# php build-base.php

WARNING: Cannot execute query (INSERT INTO `graph_types` (`graph_type`, `graph_subtype`, `graph_section`, `graph_descr`, `graph_order`) VALUES('device', 'bits', 'netstats', 'Total Traffic', 0),('device', 'hr_users', 'system', 'Users Logged In', 0),('device', 'ucd_load', 'system', 'Load Averages', 0),('device', 'ucd_cpu', 'system', 'Detailed Processor Usage', 0),('device', 'ucd_memory', 'system', 'Detailed Memory Usage', 0),('device', 'netstat_tcp', 'netstats', 'TCP Statistics', 0),('device', 'netstat_icmp_info', 'netstats', 'ICMP Informational Statistics', 0),('device', 'netstat_icmp_stat', 'netstats', 'ICMP Statistics', 0),('device', 'netstat_ip', 'netstats', 'IP Statistics', 0),('device', 'netstat_ip_frag', 'netstats', 'IP Fragmentation Statistics', 0),('device', 'netstat_udp', 'netstats', 'UDP Statistics', 0),('device', 'netstat_snmp', 'netstats', 'SNMP Statistics', 0),('device', 'temperatures', 'system', 'Temperatures', 0),('device', 'mempools', 'system', 'Memory Pool Usage', 0),('device', 'processors', 'system', 'Processor Usage', 0),('device', 'storage', 'system', 'Filesystem Usage', 0),('device', 'hr_processes', 'system', 'Running Processes', 0),('device', 'uptime', 'system', 'System Uptime', 0),('device', 'ipsystemstats_ipv4', 'netstats', 'IPv4 Packet Statistics', 0),('device', 'ipsystemstats_ipv6_frag', 'netstats', 'IPv6 Fragmentation Statistics', 0),('device', 'ipsystemstats_ipv6', 'netstats', 'IPv6 Packet Statistics', 0),('device', 'ipsystemstats_ipv4_frag', 'netstats', 'IPv4 Fragmentation Statistics', 0),('device',  'fortigate_sessions',  'firewall',  'Active Sessions',  0), ('device',  'screenos_sessions',  'firewall',  'Active Sessions',  0), ('device',  'fdb_count',  'system',  'MAC Addresses Learnt',  0),('device', 'cras_sessions', 'firewall', 'Remote Access Sessions', 0);
): Duplicate entry 'device-bits-netstats' for key 'PRIMARY'

**Comment by TheCrockett** [comment]
What I find interesting is:

[root@librenms]# fgrep -Rl device-bits-netstats
[root@librenms]#

(no hits)

**Comment by TheCrockett** [comment]
I do have observium installed as well, and it seems that it may be picking up files from there

[root@librenms]# strace php  build-base.php  2>&1  |grep obs
read(4, "DIR /opt/observium/mibs/synology"..., 4096) = 179
read(4, "DIR /opt/observium/mibs/dell\nDNO"..., 4096) = 1751
read(4, "DIR /opt/observium/mibs/vmware\nV"..., 4096) = 435
read(4, "DIR /opt/observium/mibs\nHP-ICF-A"..., 4096) = 4096
read(4, "DIR /opt/observium/mibs/checkpoi"..., 4096) = 249
read(4, "DIR /opt/observium/mibs/hp\nNETSW"..., 4096) = 3907
read(4, "DIR /opt/observium/mibs/lsi\nLSI-"..., 4096) = 118
read(4, "DIR /opt/observium/mibs/net-snmp"..., 4096) = 675
read(4, "DIR /opt/observium/mibs/fireeye\n"..., 4096) = 62
read(4, "DIR /opt/observium/mibs/rfc\nSIP-"..., 4096) = 4096
read(4, "DIR /opt/observium/mibs/cisco\nCI"..., 4096) = 4096
read(4, "DIR /opt/observium/mibs/riverbed"..., 4096) = 125

**Comment by laf** [comment]
@TheCrockett I'd suggest checking your config.php in /opt/librenms/. It seems like you might be pointing db details to your observium db.

**Comment by TheCrockett** [comment]
Yep; thought of that: 

[root@librenms]# grep db  config.php
$config['db_host'] = 'localhost';
$config['db_user'] = 'librenms';
$config['db_pass'] = 'REDACTED';
$config['db_name'] = 'librenms';

And just because this would be my next question...:

[root@hrpixnagios01 librenms]# grep libre config.php|grep opt
$config['install_dir'] = "/opt/librenms";

**Comment by laf** [comment]
@TheCrockett Is this a fresh install? Probably worth dropping the DB and starting again.

Also, just checking, mysql strict mode on or off? Run ./validate.php to check.

**Comment by TheCrockett** [comment]
I've run the convert.sh script, and the error is going away. 

I'll see if I can set up fresh and duplicate; otherwise maybe it's too late in the day for this.
