### ISSUE TITLE
Global MAP

### ISSUE THREAD

**Issue by fran-nlt** [librenms/librenms#1783]
HI
In the Global Map not reference my device but yes in the locations (top page)

**Comment by laf** [comment]
http://docs.librenms.org/Extensions/Globe-Frontpage/

You need to set:

$config['geoloc']['latlng'] = true;

@paulgear, @f0o , @Rosiak - shall we enable this by default now? Mapping seems to ok for most people.

**Comment by f0o** [comment]
:+1:

**Comment by fran-nlt** [comment]
Thanks!
failure just a few meters but this good 
![captura](https://cloud.githubusercontent.com/assets/13962782/9546209/4807c982-4d67-11e5-80be-f0a482f3824e.PNG)
