### ISSUE TITLE
Change formatting of the Eventlog widget

### ISSUE THREAD

**Issue by rasssta** [librenms/librenms#1786]
"End of Datetime" to "start of Message" takes up like 70% of my screen width if I have the widget use the full width of my screen. This should be optimized since currently "Hostname" and "Type" in most cases are very short. For me it's swX-popY and NULL in 95% of the cases.

Also, for the cases where the full Message can't be seen in the widget (or well, for all messages) it would be nice with mouseover/hover text that has the full Message text.

Edit: Same goes for the syslog widget as well!

**Comment by Rosiak** [comment]
Can you post a screenshot?

**Comment by rasssta** [comment]
<img width="1555" alt="screen shot 2015-08-30 at 17 48 40" src="https://cloud.githubusercontent.com/assets/4455235/9568070/7dc2f61c-4f3f-11e5-99e9-320193d0ac14.png">
