### ISSUE TITLE
MIB FortiAnalyzer

### ISSUE THREAD

**Issue by fran-nlt** [librenms/librenms#1790]
Hi
I added Fortianalyzer but is generic device
I Added MIB Fortianalyzer in the /opt/librenms/mibs
I ran Discovery but the system not recognized this device

Do I have to run some additional command?

**Comment by Rosiak** [comment]
Code has to be written to support this device.
Can you provide a SNMPWALK from the device?

**Comment by fran-nlt** [comment]
I download MIB for the page the Fortinet.
I don´t understading tell me

**Comment by fran-nlt** [comment]
I need apply more commands in the CLI of librenms?

**Comment by fran-nlt** [comment]
Hi @Rosiak 
root@librenms:/home/nlt# snmpwalk -v 2c -c nlt faz_oficina
iso.3.6.1.2.1.1.1.0 = STRING: "FAZ"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.12356.103.3.20
iso.3.6.1.2.1.1.3.0 = Timeticks: (216548574) 25 days, 1:31:25.74
iso.3.6.1.2.1.1.4.0 = STRING: "Carlos Flores"
iso.3.6.1.2.1.1.5.0 = STRING: "FAZ_NLT"
iso.3.6.1.2.1.1.6.0 = STRING: "Providencia, Chile"
iso.3.6.1.2.1.1.7.0 = INTEGER: 0
iso.3.6.1.2.1.2.1.0 = INTEGER: 4
iso.3.6.1.2.1.2.2.1.1.1 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.1.2 = INTEGER: 2
iso.3.6.1.2.1.2.2.1.1.3 = INTEGER: 3
iso.3.6.1.2.1.2.2.1.1.4 = INTEGER: 4
iso.3.6.1.2.1.2.2.1.2.1 = STRING: "port1"
iso.3.6.1.2.1.2.2.1.2.2 = STRING: "port2"
iso.3.6.1.2.1.2.2.1.2.3 = STRING: "port3"
iso.3.6.1.2.1.2.2.1.2.4 = STRING: "port4"
iso.3.6.1.2.1.2.2.1.3.1 = INTEGER: 6
iso.3.6.1.2.1.2.2.1.3.2 = INTEGER: 6
iso.3.6.1.2.1.2.2.1.3.3 = INTEGER: 6
iso.3.6.1.2.1.2.2.1.3.4 = INTEGER: 6
iso.3.6.1.2.1.2.2.1.4.1 = INTEGER: 1500
iso.3.6.1.2.1.2.2.1.4.2 = INTEGER: 1500
iso.3.6.1.2.1.2.2.1.4.3 = INTEGER: 1500
iso.3.6.1.2.1.2.2.1.4.4 = INTEGER: 1500
iso.3.6.1.2.1.2.2.1.5.1 = Gauge32: 1895825408
iso.3.6.1.2.1.2.2.1.5.2 = Gauge32: 1895825408
iso.3.6.1.2.1.2.2.1.5.3 = Gauge32: 1895825408
iso.3.6.1.2.1.2.2.1.5.4 = Gauge32: 1895825408
iso.3.6.1.2.1.2.2.1.6.1 = Hex-STRING: 00 0C 29 97 90 BC
iso.3.6.1.2.1.2.2.1.6.2 = Hex-STRING: 00 0C 29 97 90 C6
iso.3.6.1.2.1.2.2.1.6.3 = Hex-STRING: 00 0C 29 97 90 D0
iso.3.6.1.2.1.2.2.1.6.4 = Hex-STRING: 00 0C 29 97 90 DA
iso.3.6.1.2.1.2.2.1.7.1 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.7.2 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.7.3 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.7.4 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.8.1 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.8.2 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.8.3 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.8.4 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.9.1 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.2.2.1.9.2 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.2.2.1.9.3 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.2.2.1.9.4 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.2.2.1.10.1 = Counter64: 3248906179
iso.3.6.1.2.1.2.2.1.10.2 = Counter64: 55993662
iso.3.6.1.2.1.2.2.1.10.3 = Counter64: 55993602
iso.3.6.1.2.1.2.2.1.10.4 = Counter64: 55993542
iso.3.6.1.2.1.2.2.1.11.1 = Counter64: 7074315
iso.3.6.1.2.1.2.2.1.11.2 = Counter64: 932424
iso.3.6.1.2.1.2.2.1.11.3 = Counter64: 932423
iso.3.6.1.2.1.2.2.1.11.4 = Counter64: 932422
iso.3.6.1.2.1.2.2.1.12.1 = Counter64: 0
iso.3.6.1.2.1.2.2.1.12.2 = Counter64: 0
iso.3.6.1.2.1.2.2.1.12.3 = Counter64: 0
iso.3.6.1.2.1.2.2.1.12.4 = Counter64: 0
iso.3.6.1.2.1.2.2.1.13.1 = Counter64: 0
iso.3.6.1.2.1.2.2.1.13.2 = Counter64: 0
iso.3.6.1.2.1.2.2.1.13.3 = Counter64: 0
iso.3.6.1.2.1.2.2.1.13.4 = Counter64: 0
iso.3.6.1.2.1.2.2.1.14.1 = Counter64: 0
iso.3.6.1.2.1.2.2.1.14.2 = Counter64: 0
iso.3.6.1.2.1.2.2.1.14.3 = Counter64: 0
iso.3.6.1.2.1.2.2.1.14.4 = Counter64: 0
iso.3.6.1.2.1.2.2.1.15.1 = Counter32: 0
iso.3.6.1.2.1.2.2.1.15.2 = Counter32: 0
iso.3.6.1.2.1.2.2.1.15.3 = Counter32: 0
iso.3.6.1.2.1.2.2.1.15.4 = Counter32: 0
iso.3.6.1.2.1.2.2.1.16.1 = Counter64: 411634231
iso.3.6.1.2.1.2.2.1.16.2 = Counter64: 468
iso.3.6.1.2.1.2.2.1.16.3 = Counter64: 468
iso.3.6.1.2.1.2.2.1.16.4 = Counter64: 468
iso.3.6.1.2.1.2.2.1.17.1 = Counter64: 3135273
iso.3.6.1.2.1.2.2.1.17.2 = Counter64: 6
iso.3.6.1.2.1.2.2.1.17.3 = Counter64: 6
iso.3.6.1.2.1.2.2.1.17.4 = Counter64: 6
iso.3.6.1.2.1.2.2.1.18.1 = Counter64: 0
iso.3.6.1.2.1.2.2.1.18.2 = Counter64: 0
iso.3.6.1.2.1.2.2.1.18.3 = Counter64: 0
iso.3.6.1.2.1.2.2.1.18.4 = Counter64: 0
iso.3.6.1.2.1.2.2.1.19.1 = Counter64: 0
iso.3.6.1.2.1.2.2.1.19.2 = Counter64: 0
iso.3.6.1.2.1.2.2.1.19.3 = Counter64: 0
iso.3.6.1.2.1.2.2.1.19.4 = Counter64: 0
iso.3.6.1.2.1.2.2.1.20.1 = Counter64: 0
iso.3.6.1.2.1.2.2.1.20.2 = Counter64: 0
iso.3.6.1.2.1.2.2.1.20.3 = Counter64: 0
iso.3.6.1.2.1.2.2.1.20.4 = Counter64: 0
iso.3.6.1.2.1.2.2.1.21.1 = Gauge32: 0
iso.3.6.1.2.1.2.2.1.21.2 = Gauge32: 0
iso.3.6.1.2.1.2.2.1.21.3 = Gauge32: 0
iso.3.6.1.2.1.2.2.1.21.4 = Gauge32: 0
iso.3.6.1.2.1.2.2.1.22.1 = OID: ccitt.0.0
iso.3.6.1.2.1.2.2.1.22.2 = OID: ccitt.0.0
iso.3.6.1.2.1.2.2.1.22.3 = OID: ccitt.0.0
iso.3.6.1.2.1.2.2.1.22.4 = OID: ccitt.0.0
iso.3.6.1.2.1.2.2.1.23.1 = NULL
iso.3.6.1.2.1.2.2.1.23.2 = NULL
iso.3.6.1.2.1.2.2.1.23.3 = NULL
iso.3.6.1.2.1.2.2.1.23.4 = NULL
iso.3.6.1.2.1.4.1.0 = INTEGER: 2
iso.3.6.1.2.1.4.2.0 = INTEGER: 64
iso.3.6.1.2.1.4.3.0 = Counter32: 10090563
iso.3.6.1.2.1.4.4.0 = Counter32: 0
iso.3.6.1.2.1.4.5.0 = Counter32: 0
iso.3.6.1.2.1.4.6.0 = Counter32: 0
iso.3.6.1.2.1.4.7.0 = Counter32: 0
iso.3.6.1.2.1.4.8.0 = Counter32: 0
iso.3.6.1.2.1.4.9.0 = Counter32: 10076383
iso.3.6.1.2.1.4.10.0 = Counter32: 7083228
iso.3.6.1.2.1.4.11.0 = Counter32: 0
iso.3.6.1.2.1.4.12.0 = Counter32: 0
iso.3.6.1.2.1.4.13.0 = INTEGER: 0
iso.3.6.1.2.1.4.14.0 = Counter32: 2324
iso.3.6.1.2.1.4.15.0 = Counter32: 1162
iso.3.6.1.2.1.4.16.0 = Counter32: 0
iso.3.6.1.2.1.4.17.0 = Counter32: 0
iso.3.6.1.2.1.4.18.0 = Counter32: 0
iso.3.6.1.2.1.4.19.0 = Counter32: 0
iso.3.6.1.2.1.4.20.0 = NULL
iso.3.6.1.2.1.4.20.1.1.192.168.20.123 = IpAddress: 192.168.20.123
iso.3.6.1.2.1.4.20.1.2.192.168.20.123 = INTEGER: 1
iso.3.6.1.2.1.4.20.1.3.192.168.20.123 = IpAddress: 255.255.255.0
iso.3.6.1.2.1.4.20.1.4.192.168.20.123 = INTEGER: 1
iso.3.6.1.2.1.4.20.1.5.192.168.20.123 = INTEGER: 65535
iso.3.6.1.2.1.4.22.1.1.1.192.168.20.1 = INTEGER: 1
iso.3.6.1.2.1.4.22.1.2.1.192.168.20.1 = Hex-STRING: 08 5B 0E 6C 86 58
iso.3.6.1.2.1.4.22.1.3.1.192.168.20.1 = IpAddress: 192.168.20.1
iso.3.6.1.2.1.4.22.1.4.1.192.168.20.1 = INTEGER: 3
iso.3.6.1.2.1.5.1.0 = Counter32: 4594
iso.3.6.1.2.1.5.2.0 = Counter32: 47
iso.3.6.1.2.1.5.3.0 = Counter32: 171
iso.3.6.1.2.1.5.4.0 = Counter32: 0
iso.3.6.1.2.1.5.5.0 = Counter32: 0
iso.3.6.1.2.1.5.6.0 = Counter32: 0
iso.3.6.1.2.1.5.7.0 = Counter32: 0
iso.3.6.1.2.1.5.8.0 = Counter32: 4423
iso.3.6.1.2.1.5.9.0 = Counter32: 0
iso.3.6.1.2.1.5.10.0 = Counter32: 0
iso.3.6.1.2.1.5.11.0 = Counter32: 0
iso.3.6.1.2.1.5.12.0 = Counter32: 0
iso.3.6.1.2.1.5.13.0 = Counter32: 0
iso.3.6.1.2.1.5.14.0 = Counter32: 20679
iso.3.6.1.2.1.5.15.0 = Counter32: 0
iso.3.6.1.2.1.5.16.0 = Counter32: 16256
iso.3.6.1.2.1.5.17.0 = Counter32: 0
iso.3.6.1.2.1.5.18.0 = Counter32: 0
iso.3.6.1.2.1.5.19.0 = Counter32: 0
iso.3.6.1.2.1.5.20.0 = Counter32: 0
iso.3.6.1.2.1.5.21.0 = Counter32: 0
iso.3.6.1.2.1.5.22.0 = Counter32: 4423
iso.3.6.1.2.1.5.23.0 = Counter32: 0
iso.3.6.1.2.1.5.24.0 = Counter32: 0
iso.3.6.1.2.1.5.25.0 = Counter32: 0
iso.3.6.1.2.1.5.26.0 = Counter32: 0
iso.3.6.1.2.1.6.1.0 = INTEGER: 1
iso.3.6.1.2.1.6.2.0 = INTEGER: 200
iso.3.6.1.2.1.6.3.0 = INTEGER: 120000
iso.3.6.1.2.1.6.4.0 = INTEGER: -1
iso.3.6.1.2.1.6.5.0 = Counter32: 13695
iso.3.6.1.2.1.6.6.0 = Counter32: 16332
iso.3.6.1.2.1.6.7.0 = Counter32: 1154
iso.3.6.1.2.1.6.8.0 = Counter32: 17656
iso.3.6.1.2.1.6.9.0 = Gauge32: 2
iso.3.6.1.2.1.6.10.0 = Counter32: 2406601
iso.3.6.1.2.1.6.11.0 = Counter32: 3044156
iso.3.6.1.2.1.6.12.0 = Counter32: 8643
iso.3.6.1.2.1.6.14.0 = Counter32: 0
iso.3.6.1.2.1.6.15.0 = Counter32: 33054
iso.3.6.1.2.1.7.1.0 = Counter32: 7642364
iso.3.6.1.2.1.7.2.0 = Counter32: 22195
iso.3.6.1.2.1.7.3.0 = Counter32: 0
iso.3.6.1.2.1.7.4.0 = Counter32: 4030920
iso.3.6.1.2.1.25.1.1.0 = Timeticks: (216548584) 25 days, 1:31:25.84
iso.3.6.1.2.1.25.1.2.0 = Hex-STRING: 07 DF 08 1F 0C 0B 12 00 2D 03 00
iso.3.6.1.2.1.25.1.3.0 = INTEGER: 0
iso.3.6.1.2.1.25.1.4.0 = ""
iso.3.6.1.2.1.25.1.5.0 = Gauge32: 0
iso.3.6.1.2.1.25.1.6.0 = Gauge32: 0
iso.3.6.1.2.1.25.1.7.0 = INTEGER: 0
iso.3.6.1.2.1.25.2.2.0 = INTEGER: 2059688
iso.3.6.1.2.1.25.2.3.1.1.1 = INTEGER: 1
iso.3.6.1.2.1.25.2.3.1.1.2 = INTEGER: 2
iso.3.6.1.2.1.25.2.3.1.1.3 = INTEGER: 3
iso.3.6.1.2.1.25.2.3.1.1.4 = INTEGER: 4
iso.3.6.1.2.1.25.2.3.1.2.1 = OID: iso.3.6.1.2.1.25.2.1.2
iso.3.6.1.2.1.25.2.3.1.2.2 = OID: iso.3.6.1.2.1.25.2.1.3
iso.3.6.1.2.1.25.2.3.1.2.3 = OID: iso.3.6.1.2.1.25.2.1.4
iso.3.6.1.2.1.25.2.3.1.2.4 = OID: iso.3.6.1.2.1.25.2.1.4
iso.3.6.1.2.1.25.2.3.1.3.1 = STRING: "Physical Memory"
iso.3.6.1.2.1.25.2.3.1.3.2 = STRING: "Swap Memory"
iso.3.6.1.2.1.25.2.3.1.3.3 = STRING: "Compact Flash Disk"
iso.3.6.1.2.1.25.2.3.1.3.4 = STRING: "Internal Hard Disk"
iso.3.6.1.2.1.25.2.3.1.4.1 = INTEGER: 1024
iso.3.6.1.2.1.25.2.3.1.4.2 = INTEGER: 1024
iso.3.6.1.2.1.25.2.3.1.4.3 = INTEGER: 4096
iso.3.6.1.2.1.25.2.3.1.4.4 = INTEGER: 4096
iso.3.6.1.2.1.25.2.3.1.5.1 = INTEGER: 2059688
iso.3.6.1.2.1.25.2.3.1.5.2 = INTEGER: 2076536
iso.3.6.1.2.1.25.2.3.1.5.3 = INTEGER: 129010
iso.3.6.1.2.1.25.2.3.1.5.4 = INTEGER: 20641452
iso.3.6.1.2.1.25.2.3.1.6.1 = INTEGER: 2041056
iso.3.6.1.2.1.25.2.3.1.6.2 = INTEGER: 183368
iso.3.6.1.2.1.25.2.3.1.6.3 = INTEGER: 17441
iso.3.6.1.2.1.25.2.3.1.6.4 = INTEGER: 4777031
iso.3.6.1.2.1.25.2.3.1.7.1 = Counter32: 0
iso.3.6.1.2.1.25.2.3.1.7.2 = Counter32: 0
iso.3.6.1.2.1.25.2.3.1.7.3 = Counter32: 0
iso.3.6.1.2.1.25.2.3.1.7.4 = Counter32: 0
iso.3.6.1.2.1.25.3.2.1.1.1 = INTEGER: 1
iso.3.6.1.2.1.25.3.2.1.2.1 = OID: iso.3.6.1.2.1.25.3.1.3
iso.3.6.1.2.1.25.3.2.1.3.1 = STRING: "CPU Processor"
iso.3.6.1.2.1.25.3.2.1.4.1 = OID: ccitt.0.0
iso.3.6.1.2.1.25.3.2.1.5.1 = INTEGER: 2
iso.3.6.1.2.1.25.3.2.1.6.1 = Counter32: 0
iso.3.6.1.2.1.25.3.3.1.1.1 = OID: ccitt.0.0
iso.3.6.1.2.1.25.3.3.1.2.1 = INTEGER: 0
iso.3.6.1.2.1.31.1.1.1.1.1 = STRING: "port1"
iso.3.6.1.2.1.31.1.1.1.1.2 = STRING: "port2"
iso.3.6.1.2.1.31.1.1.1.1.3 = STRING: "port3"
iso.3.6.1.2.1.31.1.1.1.1.4 = STRING: "port4"
iso.3.6.1.2.1.31.1.1.1.2.1 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.2.2 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.2.3 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.2.4 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.3.1 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.3.2 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.3.3 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.3.4 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.4.1 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.4.2 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.4.3 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.4.4 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.5.1 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.5.2 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.5.3 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.5.4 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.6.1 = Counter64: 3248926912
iso.3.6.1.2.1.31.1.1.1.6.2 = Counter64: 55993662
iso.3.6.1.2.1.31.1.1.1.6.3 = Counter64: 55993602
iso.3.6.1.2.1.31.1.1.1.6.4 = Counter64: 55993542
iso.3.6.1.2.1.31.1.1.1.7.1 = Counter64: 7074513
iso.3.6.1.2.1.31.1.1.1.7.2 = Counter64: 932424
iso.3.6.1.2.1.31.1.1.1.7.3 = Counter64: 932423
iso.3.6.1.2.1.31.1.1.1.7.4 = Counter64: 932422
iso.3.6.1.2.1.31.1.1.1.8.1 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.8.2 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.8.3 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.8.4 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.9.1 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.9.2 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.9.3 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.9.4 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.10.1 = Counter64: 411650182
iso.3.6.1.2.1.31.1.1.1.10.2 = Counter64: 468
iso.3.6.1.2.1.31.1.1.1.10.3 = Counter64: 468
iso.3.6.1.2.1.31.1.1.1.10.4 = Counter64: 468
iso.3.6.1.2.1.31.1.1.1.11.1 = Counter64: 3135458
iso.3.6.1.2.1.31.1.1.1.11.2 = Counter64: 6
iso.3.6.1.2.1.31.1.1.1.11.3 = Counter64: 6
iso.3.6.1.2.1.31.1.1.1.11.4 = Counter64: 6
iso.3.6.1.2.1.31.1.1.1.12.1 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.12.2 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.12.3 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.12.4 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.13.1 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.13.2 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.13.3 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.13.4 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.14.1 = INTEGER: 1
iso.3.6.1.2.1.31.1.1.1.14.2 = INTEGER: 1
iso.3.6.1.2.1.31.1.1.1.14.3 = INTEGER: 1
iso.3.6.1.2.1.31.1.1.1.14.4 = INTEGER: 1
iso.3.6.1.2.1.31.1.1.1.15.1 = Gauge32: 10000
iso.3.6.1.2.1.31.1.1.1.15.2 = Gauge32: 10000
iso.3.6.1.2.1.31.1.1.1.15.3 = Gauge32: 10000
iso.3.6.1.2.1.31.1.1.1.15.4 = Gauge32: 10000
iso.3.6.1.2.1.31.1.1.1.16.1 = INTEGER: 2
iso.3.6.1.2.1.31.1.1.1.16.2 = INTEGER: 2
iso.3.6.1.2.1.31.1.1.1.16.3 = INTEGER: 2
iso.3.6.1.2.1.31.1.1.1.16.4 = INTEGER: 2
iso.3.6.1.2.1.31.1.1.1.17.1 = INTEGER: 1
iso.3.6.1.2.1.31.1.1.1.17.2 = INTEGER: 1
iso.3.6.1.2.1.31.1.1.1.17.3 = INTEGER: 1
iso.3.6.1.2.1.31.1.1.1.17.4 = INTEGER: 1
iso.3.6.1.2.1.31.1.1.1.18.1 = ""
iso.3.6.1.2.1.31.1.1.1.18.2 = ""
iso.3.6.1.2.1.31.1.1.1.18.3 = ""
iso.3.6.1.2.1.31.1.1.1.18.4 = ""
iso.3.6.1.2.1.31.1.1.1.19.1 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.31.1.1.1.19.2 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.31.1.1.1.19.3 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.31.1.1.1.19.4 = Timeticks: (0) 0:00:00.00

**Comment by laf** [comment]
PR done to add basic detection, when #1815 is merged please update and run a full discovery of the devices.

**Comment by fran-nlt** [comment]
Do you want the file MIB?

**Comment by laf** [comment]
Got it already thanks :)

**Comment by fran-nlt** [comment]
Thanks!
FAZ is registered in the LibreNMS

**Comment by laf** [comment]
Excellent :)
