### ISSUE TITLE
Include all nagios-plugins

### ISSUE THREAD

**Issue by raptureveteran** [librenms/librenms#1792]
I'm trying to move our companies notifications server from Icinga to LibreNMS. The issue I am having though is that I followed the documentation to a T on adding the services and then nagios services to config.php and added what was said to add to cron.d file but I only see 16 services to use

config.php file
$config['show_services']           = 1;
$config['nagios_plugins']   = "/usr/lib64/nagios/plugins/";

Screen of services menu
http://i.imgur.com/JL4XHXc.png

As you can see below, there are far more services than what this menu shows

http://i.imgur.com/xOxqXi8.png

My goal is to essentially be able to use these plugins on LibreNMS

**Comment by truongexp** [comment]
Could you please show me how to do ?
I had the above issue but still not be resolved.
Thanks in advance.
