### ISSUE TITLE
Reverting back to old homepage/main/overview layout?

### ISSUE THREAD

**Issue by arjitc** [librenms/librenms#1795]
I currently have this http://i.imgur.com/8pRIylv.png since a few commits, I'd like to change back to to the older one, any idea howto?

**Comment by laf** [comment]
@arjitc $config['front_page'] = 'default.inc.php';

Can I ask why?

**Comment by arjitc** [comment]
Hmm, with the map on the page I somehow end up scrolling into the map instead of scrolling below the page when I use my laptops tackpads 2 finger scroll.

**Comment by laf** [comment]
@arjitc I've pr'd a fix as that is annoying, you now need to click the map to activate zooming.

**Comment by arjitc** [comment]
Yup, it was pretty annoying since I had the map on the top and the other boxes below, I'll pull it in and revert back to the original config once it's merged in.Thanks @laf :+1:
