### ISSUE TITLE
Tidy autodiscovery configuration

### ISSUE THREAD

**Issue by paulgear** [librenms/librenms#18]
We have the following configuration variables influencing autodiscovery:
- $config['nets'][]
- $config['autodiscovery']['nets-exclude'][]
- $config['autodiscovery'][$method] (for $method in 'xdp', 'ospf', 'bgp', 'snmpscan')
This probably needs to be consolidated, and some utility functions used to determine whether each module should be activated.

**Comment by laf** [comment]
@paulgear 

Can you provide more information on what you mean by this?

**Comment by laf** [comment]
Anything more on this, I'm unsure what the issue needs us to fix.

$config['nets'][]
$config['autodiscovery']['nets-exclude'][]

These are both used to decide if a host being auto discovered should or should not be added.

$config['autodiscovery']$method  (i.e xdp, bgp, ospf) are all checked in the discovery files to ensure the user wants them run.

**Comment by paulgear** [comment]
I'll have another look through this.  My only thought now is that 'nets' probably just needs to move inside 'autodiscovery'.

**Comment by laf** [comment]
'net's is already in the discover_new_device() function, we check if the IP is in net-excludes first then in nets second.

**Comment by laf** [comment]
Prod

**Comment by paulgear** [comment]
Will look at this on the weekend.

**Comment by paulgear** [comment]
$config['nets'] is only used for autodiscovery, so ideally, it should be moved in there.  However, because it's used in config.php by default, I don't think this is worth changing.  It would take more effort to provide a good user experience around it than I think is warranted.

**Comment by laf** [comment]
Just to clear this up, discover_new_device() is only used in autodiscovery code:

```bash
[root@localhost librenms]# grep discover_new_device ./* -R
./includes/discovery/functions.inc.php:function discover_new_device($hostname, $device='', $method='', $interface='') {
./includes/discovery/functions.inc.php:}//end discover_new_device()
./includes/discovery/discovery-arp.inc.php:    // Even though match_network is done inside discover_new_device, we do it here
./includes/discovery/discovery-arp.inc.php:    $remote_device_id = discover_new_device($name, $device, 'ARP');
./includes/discovery/discovery-protocols.inc.php:                    $remote_device_id = discover_new_device($fdp['snFdpCacheDeviceId'], $device, 'FDP', $interface);
./includes/discovery/discovery-protocols.inc.php:                    $remote_device_id = discover_new_device($cdp['cdpCacheDeviceId'], $device, 'CDP', $interface);
./includes/discovery/discovery-protocols.inc.php:                    $remote_device_id = discover_new_device($lldp['lldpRemSysName'], $device, 'LLDP', $interface);
./includes/discovery/discovery-protocols.inc.php:        $remote_device_id = discover_new_device($name, $device, 'OSPF');
./includes/discovery/bgp-peers.inc.php:                    $remote_device_id = discover_new_device($name, $device, 'BGP');
[root@localhost librenms]#
```
