### ISSUE TITLE
Take a look at contributors agreement text

### ISSUE THREAD

**Issue by laf** [librenms/librenms#1820]

**Comment by f0o** [comment]
Alerting tag?

**Comment by paulgear** [comment]
@laf What do I need to look at here?

**Comment by SaaldjorMike** [comment]
Any clarification regarding exactly what we need here?

**Comment by laf** [comment]
It was job who raised it so probably best asking him.

**Comment by SaaldjorMike** [comment]
Tagging @job

**Comment by job** [comment]
This can be closed, i don't remember what this was about
