### ISSUE TITLE
To much temperature sensor for HP Switch 2920-24G results in 296 seconds polling

### ISSUE THREAD

**Issue by muahdib69** [librenms/librenms#1834]
Hello, 

as reported on IRC my HP 2920-24G switch has 5 temperature sensors, but over 50 are checked.

The output of:
./discovery.php -h HOSTNAME -d -m 

is here: https://dpaste.de/YBtY

I just changed the community string. 

Thank you,
Best

**Comment by Tawmu** [comment]
I am also seeing this on our 2920-48G.

The first 4 temp sensors are showing values, but the rest up to sensor 59 is showing "NaN°C"

**Comment by Tawmu** [comment]
Turns out this isn't a Libre problem. The device actually reports 58 sensors via SNMP.

**Comment by laf** [comment]
Yeah but if they don`t return valid data then we should be excluding them anyway.

**Comment by laf** [comment]
In fact if you have the output from snmp that would be good, the link in the original issue has now expired

**Comment by Tawmu** [comment]
@laf please see SNMP Walk here: https://bpaste.net/show/192b578b2933

You'll be interested in:
ENTITY-SENSOR-MIB::entPhySensorValue.12006 = INTEGER: 0
through to
ENTITY-SENSOR-MIB::entPhySensorValue.12059 = INTEGER: 0

**Comment by Tawmu** [comment]
FYI all, I just updated my 2920-24G (J9278A) to the latest firmware (WB.15.18.0006, ROM WB.15.05) and the extra sensors were removed from LibreNMS on the next discovery cycle.

Looks like this was a HP problem.

**Comment by paulgear** [comment]
Thanks for reporting back, @Tawmu!
