### ISSUE TITLE
It seems I can not search for MAC addresses connected to the HP switches.

### ISSUE THREAD

**Issue by muahdib69** [librenms/librenms#1835]
It only shows their own mac in the web interface. (e.g. a Switch with 52 ports shows 52 macs, but they are all its own.)

Output of:
snmpwalk -v2c -c public HOSTNAME 1.3.6.1.2.1.17.4.3.1

is here:
https://dpaste.de/kGe3

Thank you
Best
Ray

**Comment by markuspachali** [comment]
Hi Ray,
yes, that is correct. At the moment the MAC-Adress table of switches are not imported. A feature request for that is open:
https://github.com/librenms/librenms/issues/1196

Best regards,
Markus
