### ISSUE TITLE
Maps through proxy question

### ISSUE THREAD

**Issue by adammmmm** [librenms/librenms#1843]
Hi!

I've got a question regarding the use of maps through a proxy. Our LibreNMS device is located in a management network with internet access only through proxy. I haven't found a way to get the maps (Global Map/World Map) to work, Global one is all grey, the world one is all white.
Might not be LibreNMS related but running normal os updates and git update works. Maybe all I'm after is  a global proxy setting in Linux.

**Comment by f0o** [comment]
Hi adammmmm,

Both maps use your browser's settings to connect to the internet. If you can browse google &co you should be able to display them.

Please shout if otherwise

On September 4, 2015 9:37:02 AM GMT+02:00, adammmmm <notifications@github.com> wrote:
>Hi!
>
>I've got a question regarding the use of maps through a proxy. Our
>LibreNMS device is located in a management network with internet access
>only through proxy. I haven't found a way to get the maps (Global
>Map/World Map) to work, Global one is all grey, the world one is all
>white.
>Might not be LibreNMS related but running normal os updates and git
>update works. Maybe all I'm after is  a global proxy setting in Linux.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/1843

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by adammmmm** [comment]
Hmmm, ok got it, not running any browser on the LibreNMS device though, it's just an ubuntu server, maybe I just need to scour the web to find how.
Or is it the client browsing the map who needs the proxy settings?

**Comment by f0o** [comment]
Sorry if it was unclear, I meant the client browser

On September 4, 2015 9:44:54 AM GMT+02:00, adammmmm <notifications@github.com> wrote:
>Hmmm, ok got it, not running any browser on the LibreNMS device though,
>it's just an ubuntu server, maybe I just need to scour the web to find
>how.
>Or is it the client browsing the map who needs the proxy settings?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/1843#issuecomment-137667883

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by adammmmm** [comment]
Ah, understood, that's why. Thanks for the clarification, will have to see if we can get that sorted in the proxy then! Thank you and keep the great work up!

**Comment by f0o** [comment]
If you need a server side solution, you can download most of the tiles and geodata directly from openstreetmaps.org and host it yourself. However we provide no such docs on how to do that. You'll need to work with their docs instead. Bare in mind, I'm unaware of anybody doing this yet. If you succeed please share a guide so we can enhance our docs :)

On September 4, 2015 9:49:12 AM GMT+02:00, adammmmm <notifications@github.com> wrote:
>Ah, understood, that's why. Thanks for the clarification, will have to
>see if we can get that sorted in the proxy then! Thank you and keep the
>great work up!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/1843#issuecomment-137670150

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
