### ISSUE TITLE
Not polling DOM values on JunOS MX960

### ISSUE THREAD

**Issue by bartdebruijn** [librenms/librenms#1844]
I'm having trouble reading DOM values from optics from my JunOS MX960 (12.2)

I can do an snmpwalk with the correct OID and it will return the value, e.g.: iso.3.6.1.4.1.2636.3.60.1.1.1.1.5.516 = INTEGER: -581

However, it will not display this, or any dBm measurements for JunOS devices at all in LibreNMS. It works for Cisco 7600 just fine. I've enabled MIB polling for the device, but that makes no difference.

Any ideas?

**Comment by Rosiak** [comment]
Please provide a SNMPWALK from the device and we'll look at it.

**Comment by bartdebruijn** [comment]
Hi Rosiak,

I think the issue is with the ./discovery.php module. The oid's show up in the snmpwalk just fine.

**Comment by bartdebruijn** [comment]
bartdb@librenms-p01:/opt/librenms$ /usr/bin/snmpwalk -v2c -c XXXXX -m JUNIPER-MIB -M /opt/librenms/mibs udp:XXXXXXXXX:161 1.3.6.1.4.1.2636.3.60.1.1.1.1.5
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.526 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.527 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.528 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.529 = INTEGER: -208
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.530 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.531 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.534 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.535 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.536 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.537 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.538 = INTEGER: -466
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.539 = INTEGER: -209
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.540 = INTEGER: -619
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.541 = INTEGER: -612
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.542 = INTEGER: -468
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.543 = INTEGER: -490
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.544 = INTEGER: -633
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.545 = INTEGER: -592
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.546 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.547 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.548 = INTEGER: -339
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.549 = INTEGER: -352
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.550 = INTEGER: -644
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.551 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.552 = INTEGER: -498
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.553 = INTEGER: -353
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.554 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.555 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.556 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.557 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.558 = INTEGER: -608
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.559 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.560 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.561 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.562 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.563 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.564 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.565 = INTEGER: -572
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.566 = INTEGER: 0
JUNIPER-SMI::jnxMibs.60.1.1.1.1.5.567 = INTEGER: 0

**Comment by laf** [comment]
this was merged in #3741
