### ISSUE TITLE
grouping of things other than devices? And the ability to add maintenance for singular devices

### ISSUE THREAD

**Issue by Alastair-VOIPUNLIMITED** [librenms/librenms#1845]
Hey guys!

Wondering if it would be sensible to also have the ability to group ports or anything else.

For example we would like to be able to alert on some BGP sessions status changing but not others on some devices. We have many interconnects with other companies and would like to be able to create a separate alerts for each if they go down. (different email for each) 

On another note is it possible to have the functionality where we can set maintenance to a particular node within a group, setting it to ignore sometimes isn't practical. 

On another side note, would it be helpful if during maintenance windows for devices the device still logs on Libre as per norm but just doesn't alert? This is for a situation where we change many things within a data centre and want to use libre to make sure everything is back up however we wont know until the maintenance window has expired and possibly may get spammed when it does. 

Thanks All, these may not be practical for all users though. Let me know if this needs to be in 3 different issues.  

Alastair

**Comment by Rosiak** [comment]
Tagging @f0o since he's up-to-speed regarding the alerting.

**Comment by f0o** [comment]
@Alastair-VOIPUNLIMITED please split it up in seperate issues.

I can PR your 3rd request by today evening.

The other two require some more thinktank'ing

**Comment by Alastair-VOIPUNLIMITED** [comment]
On it now, thank you

**Comment by Rosiak** [comment]
Can this be closed?
Since #1859 and #1860 exists.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-grouping-of-things-other-than-devices-and-the-ability-to-add-maintenance-for-singular-devices/735
