### ISSUE TITLE
CentOS vm image?

### ISSUE THREAD

**Issue by laf** [librenms/librenms#1849]
Hi All,

We currently provide an Ubuntu image for people to download and get started quickly. Would a CentOS version be of benefit, would you have picked CentOS over Ubuntu?

Maintaining both wouldn't really be much extra work so I'm happy to maintain that if it would benefit others.

**Comment by Tawmu** [comment]
I'd have picked CentOS over Ubuntu for our install since it follows a more stable release cycle and fits in better with UNIX infrastructure.

I'm sure a lot of people would prefer CentOS over Ubuntu in Enterprise environments since people tend to standardise on particular distros.

**Comment by Lucheni** [comment]
+1
