### ISSUE TITLE
Adding Cisco CBQoS support

### ISSUE THREAD

**Issue by adaniels21487** [librenms/librenms#1851]
I'm going to take a look at this bad boy..

**Comment by xUmaRix** [comment]
I need CBQoS support for librenms too

**Comment by adaniels21487** [comment]
Its looking good so far.
Supports nested policies for both ingress and egress.
![image](https://cloud.githubusercontent.com/assets/13431617/10709207/c7f6a092-7a66-11e5-872b-3988dba8ffc6.png)

**Comment by laf** [comment]
Awesome work :) Planning a PR soon? :D

**Comment by Wickusb** [comment]
I see someone was working on this. Can we also verify the stats is the same as on observium and perhaps torrus

**Comment by adaniels21487** [comment]
Hi @Wickusb,
I am unaware how this compares with other NMS as I dont use them but please feel free to try this out from https://github.com/adaniels21487/librenms/tree/feature/Cisco-CBQOS
if you can suggest any improvements I'd be happy to work them in.

Thanks,
Aaron

**Comment by Wickusb** [comment]
Hi @adaniels21487 

Sorry to be asking seeing as im new to git. How can i merge only your cbqoq into the current version im using

thanks

**Comment by adaniels21487** [comment]
Hi @Wickusb,
This has worked for me.

1. Add my git repository to your local repository, in this example I have called the repository adaniels:
```git remote add adaniels https://github.com/adaniels21487/librenms.git```

2. Pull the branch replacing local with what you would like to name the branch locally:
```git fetch adaniels feature/Cisco-CBQOS:local```

3. Checkout the branch:
```git checkout local```

4. Once you are in the branch you will need to modify your database
```mysql -u <user> -p librenms < sql-schema/000.sql```

5. The Cisco-CBQoS discovery module is NOT on by default, you will need to turn it on for your desired devices under: Device -> Edit -> Modules -> Discovery Modules.

Once you have had enough, going back to your main branch should be as easy as:
```git checkout master```

but this will **not** remove the database changes, to do this you will need to manually remove the component and component_prefs tables.

**Please make a good backup before you start as this will modify your database, if you dont feel comfortable potentially destroying you installation, don't do it.**

HTH,
Aaron

**Comment by xUmaRix** [comment]
After enable CBQoS module i cannot find CBQoS menu from the header.

**Comment by adaniels21487** [comment]
Hi @xUmaRix,
After enabling the CBQOS discovery module you will need to complete a discovery to find the policy and class maps. You can do this manually with:
/opt/librenms/discovery.php -h *HOST* -m cisco-cbqos
You should see something along the lines of:

```
Cisco-CBQOS: .........
```

You should see + for new classes found and . if a previously discovered class was found.
If you dont have a + or . here please re-run the above command with -d at the end and send me the output to lists@daniels.id.au

If you see a + or . you should see CBQoS as a submenu (like the screenshot above) attached to the port that contains the QOS policy.

Thanks,
Aaron

**Comment by xUmaRix** [comment]
tq for the clarification. :)

Cisco-CBQOS: ++++++++++
Discovered in 144.7 seconds

**Comment by tylerapplebaum** [comment]
Hey guys. Will this be added into the main branch? 

@adaniels21487 have you created a pull request so we can all enjoy this?

**Comment by adaniels21487** [comment]
Hi @tylerapplebaum.
This PR depends on #1650 which is currently being reviewed. as soon as that is done I will submit a PR for this issue.

Thanks,
Aaron
