### ISSUE TITLE
poller-service stopped working after reboot

### ISSUE THREAD

**Issue by adammmmm** [librenms/librenms#1858]
I'm guessing it has to do with the reverting of mysql locks I saw in the changelog.
/var/log/syslog contains
poller-service: INFO: Starting poller-service
poller-service: ERROR: MySQL query error; Is your schema up to date?
Then it's terminated and respawned and keeps looping.

The schema - and librenms - is up to date.
I realize poller-service is considered experimental but the difference in our environment has been amazing. Processors' have run on 20% instead of 40% and the device has been 10 degrees celsius colder compared to with cron jobs.

**Comment by f0o** [comment]
Have a look at the outstanding PR #1838 and report back if it works or not.
You'd help a lot in doing so to get that PR merged asap.

**Comment by adammmmm** [comment]
Would be happy to help. Im not really too git savvy. How to try that PR without breaking anything else?

**Comment by f0o** [comment]
The easiest way is to get yourself in a 'detached head' state. This will prevent updates from happening and potentially break things.
Very important is, once we merge the PR you must revert all changes. Please dont forget this or you wont get any updates anymore at all!

So here's the way I use for my tests:
```shell
git remote add clinta https://github.com/clinta/librenms.git
git remote update
git checkout origin/master
git checkout -b PollerServiceTest
git merge clinta/poller-service2  #(This may ask you some input, it doesnt need to be anything reasonable)
```

To come back to the upstream's branch you only need to issue:
```shell
git stash
git checkout master
./daily.sh
```

All these commands should go through without errors/warnings. If at some stage they do end up in warnings or errors please stop and paste the entire output of your shell so we can help you sort things out again.

**Comment by adammmmm** [comment]
All commands worked, it didn't fix the issue though, still outputs the same MySQL query error. Let me know if there's any output you need.

**Comment by f0o** [comment]
Please tell @clinta in his PR and follow his instructions. Mention the commands you issued as well so you two are on the same page :)

**Comment by clinta** [comment]
Fixed in 6a5fc68

**Comment by Rosiak** [comment]
@adammmmm 
Please confirm if we can close this issue.

**Comment by adammmmm** [comment]
@Rosiak I was unsure of the policy regarding closing issues before the fixes were merged to master, but yeah, it's fixed in clintas branch which I'm running, so I'm fine with closing it!

**Comment by adammmmm** [comment]
now merged
