### ISSUE TITLE
Ability to group things other than devices for alerting?

### ISSUE THREAD

**Issue by Alastair-VOIPUNLIMITED** [librenms/librenms#1859]
Hey guys!

Wondering if it would be sensible to also have the ability to group ports or anything else.

For example we would like to be able to alert on some BGP sessions status changing but not others on some devices. We have many interconnects with other companies and would like to be able to create a separate alerts for each if they go down. (different email for each)

This would increase the flexibility of Libre 100 fold.

Cheers :)

Alastair

**Comment by paulgear** [comment]
:+1: Sounds good, although fine tuning how it would work will take some effort.

**Comment by laf** [comment]
Not sure I'm reading this right but you can group based on anything that has a relationship back to a device by device_id.

So for ports %ports.ifName LIKE 'Ethernet3/@' would work.

**Comment by laf** [comment]
No further info provided. @Alastair-VOIPUNLIMITED Let us know if my last response doesn't cover what you were after.
