### ISSUE TITLE
Maintenance windows for singular devices?

### ISSUE THREAD

**Issue by Alastair-VOIPUNLIMITED** [librenms/librenms#1860]
Hi team!

Would it be possible to have the functionality where we can set maintenance to a particular node within a group, setting it to ignore sometimes isn't practical.

Maybe a set into maintenance mode button somewhere on the device screen?

I have no idea how much work these "issues" ive raised entail but I hope that other people would find them useful too, enough to make them viable options :)

Alastair

**Comment by f0o** [comment]
'Maybe a set into maintenance mode button somewhere on the device screen?'
That should be possible.

I will take a look at it when I got some time today

On September 7, 2015 10:20:38 AM GMT+02:00, Alastair-VOIPUNLIMITED <notifications@github.com> wrote:
>Hi team!
>
>Would it be possible to have the functionality where we can set
>maintenance to a particular node within a group, setting it to ignore
>sometimes isn't practical.
>
>Maybe a set into maintenance mode button somewhere on the device
>screen?
>
>I have no idea how much work these "issues" ive raised entail but I
>hope that other people would find them useful too, enough to make them
>viable options :)
>
>Alastair
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/1860

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-maintenance-windows-for-singular-devices/734
