### ISSUE TITLE
Real Memory for ESXi 5.5 reported as storage, should be memory.

### ISSUE THREAD

**Issue by juhovan** [librenms/librenms#1862]
Hello,

I'm monitoring two ESXi 5.5 hosts and one 6.0 host.
For 5.5 hosts the Real Memory (= RAM) is reported as storage instead of memory.
For 6.0 host it works as intended.

I did check the difference in poller.php's debug output and it seems that hrStorageType is translated to hrStorageTypes.20 for 5.5 and to hrStorageRam for 6.0 which is probably causing this.

**Comment by Rosiak** [comment]
Hi @juhovan,

Can you provide some SNMP data from a 5.5 and 6.0 install?

**Comment by juhovan** [comment]
snmpwalks:
6.0: https://hiekkalaatikko.eu/qzmp
5.5: https://hiekkalaatikko.eu/5Ypz

Let me know if you need anything else

**Comment by laf** [comment]
Pastes have expired, can you provide non-expiring pastes pls.

**Comment by Rosiak** [comment]
No response, closing.
