### ISSUE TITLE
update failure notifications

### ISSUE THREAD

**Issue by XxPatrickxX** [librenms/librenms#1863]
With the automated patching if everything runs successfully, everything is good. If there is a problem, there is no current notification in the GUI. For example, if we look at https://stats.librenms.org/ there are large number of dbschema version 58's still. I was one of them until I started to dig into the update process.

If I interactively ran "php daily.php -f update" and error had occurred preventing me from update, but there was no notification anywhere in the product.

Error Message:
InnoDB Buffersize too small.
Current size: 1024 MiB
Minimum Required: 1319.109375 MiB
To ensure integrity, we're not going to pull any updates until the buffersize has been adjusted.

After updating innodb_buffer_poll_size to over the needed 1319MB and restarting the mysql service everything ran cleanly but I'm assuming as the MySQL install defaults to 384MB...this is likely an issue with others who are currently running dbschema 58.

**Comment by f0o** [comment]
If you define a default contact, you should get it emailed. We're working on a messaging system where we can feed notifications to the users on the UI.

**Comment by Rosiak** [comment]
@f0o With the notification system in place, where are we at now?

**Comment by f0o** [comment]
Can do!

**Comment by laf** [comment]
Should be all sorted with the fix to updates + notification system and logging of daily.sh
