### ISSUE TITLE
How to get port up / down alerts per port

### ISSUE THREAD

**Issue by mail3dexter** [librenms/librenms#1864]
Currently it is sending alarm alarm per device (merged). I wanted to know if it can send alert only for specific port.

E.g.
Device : ABC
Port : 1/1/0 (currently down) 1/1/1 (currently down) 1/1/2 (currently down)

If port 1/1/0 comes up, it should send alert only for specific port 1/1/0 stating that its up.
The Up alert should not contains all other ports which were already up.

If this feature is already present, the please let me know the proper alert rule to create.

**Comment by laf** [comment]
@mail3dexter Sorry for the late reply. This is only possible by creating one rule per port at present.

**Comment by f0o** [comment]
Correct.
The alerting system benefits from generalized rulesets and are aggregated on a per-device basis to bring some degree of overview'ability to it.

If you need explicit alerts for some interfaces, it's best to create dedicated rules for these.

Different grouping methods are requested and will be implemented in future.

If you require this ASAP, please join IRC for a chat or two to find the ideal solution for your usecase.
Feel free to query me (f0o)

**Comment by mail3dexter** [comment]
Atleast can we you highlight the port in the email like make it bold/italic which has caused the alert in the list of ports?

**Comment by laf** [comment]
In my alerts we only get the ports that match the alert anyway so if I say show me ports with more than 60% usage and 10 ports on a switch do that then I see all 10 within the alert not the 24 that the switch might have.

**Comment by mail3dexter** [comment]
Right but that logic cannot be true everytime. For e.g. I have a 48 port switches which 5 ports are already down (since it is not connected anywhere). But if a port which was working went down, it shows me that these are 6 ports which went down which is kind of confusing because we need to figure out which was that port. So rather while sending alert, it should make that particular port as bold/Italic due to which alert was generated so that we can know which one was that.

These will not impact much if you have less number of ports in devices but think of juniper VC switches or Cisco stackable switches where librenms would see 500's of ports on single switch and out of which may be 50 are already down and then someday we get alert that 1 more went down then its hard to figureout.

Sorry for late reply..

**Comment by mail3dexter** [comment]
1 more suggestion,
Can't we check Ping and or SNMP uptime to declare a device as down rather than a simple ping ?

**Comment by laf** [comment]
We do use both icmp and snmp unless you disabled the icmp checks.

As for your other comment that's not the way the alerting system works. You will get a notification that the alert has got worse but we can't show the difference.
