### ISSUE TITLE
Inventory discovery broken on JunOS devices

### ISSUE THREAD

**Issue by Tatermen** [librenms/librenms#1865]
For a while now, I've had a slightly annoying problem whereby Juniper devices on our network were having their hardware and port information re-discovered over and over again. The eventlog is filled with memory pools and CPUs being added and removed. Another symptom is that the "Inventory" for all our Juniper devices is filled with hundreds, sometimes thousands of identical entries. For example:

![image](https://cloud.githubusercontent.com/assets/8707177/9761759/98bd53ae-56f6-11e5-84be-ca866d0d03c3.png)

I've found the reason for this at least. In includes/discovery/entity-physical.php on line 77, a MySQL query is made to determine whether it is an existing entry to be updated or a new one to be inserted. This appears to be based on matching a variable, $entPhysicalIndex against the column of the same name in the entPhysical table.

The problem appears to be caused by the entPhysicalIndex column in the table being an int(11), whereas the $entPhysicalIndex variable contains a string of dotted numbers. The string of dotted numbers never matches the integer that finally ends up in the database, so it is always seen as a new piece of hardware and gets inserted into the table. For example:

```
1.1.0.0 = midplane
2.1.0.0 = PEM 0 / PEM 0
2.2.0.0 = PEM 1 / PEM 1
6.1.0.0 = FEB ACX1100 / FEB ACX1100
7.1.0.0 = FPC @ 0/*/* / FPC @ 0/*/*
8.1.1.0 = PIC: 8x 1GE(LAN) RJ45 @ 0/0/* / PIC: 8x 1GE(LAN) RJ45 @ 0/0/*
8.1.2.0 = PIC: 4x 1GE(LAN) SFP, RJ45 @ 0/1/* / PIC: 4x 1GE(LAN) SFP, RJ45 @ 0/1/*
9.1.0.0 = Routing Engine / Routing Engine
20.1.1.0 = MIC: 8x 1GE(LAN) RJ45 @ 0/0/* / MIC: 8x 1GE(LAN) RJ45 @ 0/0/*
20.1.2.0 = MIC: 4x 1GE(LAN) SFP, RJ45 @ 0/1/* / MIC: 4x 1GE(LAN) SFP, RJ45 @ 0/1/*
```
Versus what's in the table:
```
+------------------+-------------------------------+-------------------------------+
| entPhysicalIndex | entPhysicalDescr              | entPhysicalName               |
+------------------+-------------------------------+-------------------------------+
|               11 | midplane                      | midplane                      |
|               21 | PEM 0                         | PEM 0                         |
|               22 | PEM 1                         | PEM 1                         |
|               61 | FEB ACX1100                   | FEB ACX1100                   |
|               71 | FPC @ 0/*/*                   | FPC @ 0/*/*                   |
|               81 | PIC: 8x 1GE(LAN) RJ45 @ 0/0/* | PIC: 8x 1GE(LAN) RJ45 @ 0/0/* |
|               91 | Routing Engine                | Routing Engine                |
|              201 | MIC: 8x 1GE(LAN) RJ45 @ 0/0/* | MIC: 8x 1GE(LAN) RJ45 @ 0/0/* |
+------------------+-------------------------------+-------------------------------+
```

**Comment by Tatermen** [comment]
Tested by adding a line to includes/discovery/entity-physical calling the dbMakeQuery() function and echoing it terminal. The query it makes which never matches anything is:
```
SELECT entPhysical_id FROM `entPhysical` WHERE device_id = '72' AND entPhysicalIndex = '1.1.0.0'
```

**Comment by adammmmm** [comment]
Seen the same issue with our juniper devices.

**Comment by dorkmatt** [comment]
Also see same issue with Juniper devices

**Comment by adammmmm** [comment]
Is there a lot of work needed to fix this? I'd be happy to test if any coding person is willing to give it a shot!

**Comment by gcotone** [comment]
Same here.

**Comment by Tatermen** [comment]
As it will likely mean changing the database schema, I suspect it's probably not straight forward. Every function that references that table will need to be checked and possibly modified.

**Comment by gcotone** [comment]
Not necessarily. There's already some code to parse it as int:

            if ($device['os'] == 'junos') {
                // $entPhysicalIndex appears as a numeric OID fragment
                // (string), so convert it to an "integer" for the
                // validation step below since it is stored in the DB as
                // an integer. This should be fixed.
                list($first,$second)            = explode('.', $entPhysicalIndex);
                $entPhysicalIndexNoDots         = $first.$second;
                $valid[$entPhysicalIndexNoDots] = 1;

**Comment by Tatermen** [comment]
Wrote a fix, pull 2466.

**Comment by laf** [comment]
Thanks @Tatermen :)
