### ISSUE TITLE
Leaflet widget settings

### ISSUE THREAD

**Issue by spaprzycki** [librenms/librenms#1867]
There is currently no way to configure user-specific "center location" and zoom level on Leaflet map widget.

**Comment by spaprzycki** [comment]
latest db schema incorporates 'settings' column in users_widgets - perfect place to keep this user-specific info. I will be working on settings page for leaflet that will store this and obviously a way to retrieve this in the map.

**Comment by f0o** [comment]
Have a look at https://github.com/librenms/librenms/blob/master/html/includes/common/generic-graph.inc.php

`$widget_settings` contains the interpreted json-object stored in that column.
`defined('show_settings')` becomes true if the user clicks on the settings-icon for the widget.
`<form class="form" onsubmit="widget_settings(this); return false;">` is all you need to convert the form's content to a json and set it to the database.

Those 3 things are the basics, If you need to define javascript functions within the widget, use `$unique_id` to add some randomization to the function's name (please use it for id's and classes as well to avoid collisions!)

I can help you via IRC to get this working. Docs will follow when the settings API is fully finished.
