### ISSUE TITLE
'Globe Map' and 'World Map' widgets are mixed around

### ISSUE THREAD

**Issue by spaprzycki** [librenms/librenms#1868]
Strange one - when selecting widgets for dashboard 'globe map' and 'world map' are mixed around. When selecting 'World Map' widget globe.inc.php is loaded and when selecting 'Globe Map' widget worldmap.inc.php is loaded.
To me it looks like a simple mistake within database schema - versions 059 and 060, so fixing it would be as simple as renaming 'widget_title' as follows:
UPDATE widgets SET widget_title = 'World map' WHERE widget = 'worldmap'
UPDATE widgets SET widget_title = 'Globe map' WHERE widget = 'globe'

I am happy to create next version of .sql file (069.sql at the time of writing this) with above two statements unless one of the core developers wants to do it for easiness of merging.

**Comment by f0o** [comment]
If possible do it as `070.sql` - PR #1869 introduces `069.sql`

**Comment by spaprzycki** [comment]
fix merged to master (#1874). closing
