### ISSUE TITLE
Pulse Secure

### ISSUE THREAD

**Issue by chrisgfx** [librenms/librenms#1870]
Hi,

I want to add the recognition to the Pulse Secure devices in LibreNMS but I'm lack of enough information to do have specific working graphs.
I have passed a lot of hours to reverse engine the code without success.
Please find below the attached files with all the information to find the reason my graphs ares "red".

Thank you! :-)

![pulse1](https://cloud.githubusercontent.com/assets/14213615/9782786/12b59762-57a0-11e5-9b6f-cb90f58283ca.png)
![pulse2](https://cloud.githubusercontent.com/assets/14213615/9782787/12bd8b5c-57a0-11e5-9b7b-c958b1469a0e.png)
![pulse3](https://cloud.githubusercontent.com/assets/14213615/9782785/12b48c82-57a0-11e5-9968-b04f036d1374.png)

**Comment by f0o** [comment]
Hi,

if you want to code yourself, have a look at http://docs.librenms.org/Support/FAQ/#faq8

Otherwise I can have a look at it when I got time, could you provide snmp access to that device if so?
feel free to send me a mail to f0o@librenms.org so the internet wont know ;)

**Comment by chrisgfx** [comment]
Hi,

I finally succeed in the addition of Pulse Secure device! :-)
I will share the new files and propose to update the documentation with a specific part.

**Comment by laf** [comment]
Brilliant, thanks for helping make the software better :)

**Comment by Rosiak** [comment]
Hi @chrisgfx,
What's the status on this one?

**Comment by chrisgfx** [comment]
Hi Rosiak,

Sorry, I didn't have time to made the changes before. After 2 weeks of validation in production, all is fine.
So I've just created the Pull Request #2053

**Comment by SaaldjorMike** [comment]
Since the PR is merged now, I'm closing this one.
