### ISSUE TITLE
Script to fast and default install

### ISSUE THREAD

**Issue by joubertredrat** [librenms/librenms#1871]
Hi,

A few months ago I created this script to easy installation of librenms.

https://github.com/joubertredrat/librenms-faststart

In season @f0o asked to improve the script on this https://github.com/librenms/librenms/pull/1176
But I have no time, for I'm with many projects in my work, but I wanted this script would improve and help more people to install librenms.

So who can collaborate and help improve this script, we appreciate

**Comment by Gorian** [comment]
feel free to hit me up in IRC, I'd be more than happy to assist with bash scripts. If i ever get enough time I may work on this myself at some point. Too bad this was buried too far, good idea.

**Comment by laf** [comment]
Closing down

**Comment by joubertredrat** [comment]
@Gorian for me I think should have a script or a way for easy installation, but nobody liked the idea, then I gave up.

If there is a need in the future, I can either make a new script or update the current one.

**Comment by laf** [comment]
I've been using a crude script in the packer.io setup I'm building to automate the provisioning of vm images. Probably worth combining them all - will post back here when I've pushed the start of it.

**Comment by joubertredrat** [comment]
> I've been using a crude script in the packer.io setup I'm building to automate the provisioning of vm images. Probably worth combining them all - will post back here when I've pushed the start of it.

@laf is a Good idea, because you can provide fast install in environments that can't have virtualization, as mine example, I run Librenms in ArubaCloud, it is already an virtualized environment

**Comment by Gorian** [comment]
laf: sounds good to me. I'll help with that too :)
