### ISSUE TITLE
Query elasticsearch and display/graph information received

### ISSUE THREAD

**Issue by spaprzycki** [librenms/librenms#1877]
This this tracking issue for development of new feature. I will attempt to develop integration with elasticsearch (https://www.elastic.co) in order to allow querying various information about hosts from elasticsearch.

My initial use case is to incorporate Netflow information that I collect using pmacct (http://www.pmacct.net) and store in elasticsearch into LibreNMS, so following info is available per host:
- Top talkers (sources)
- Top destinations
- Protocol/port breakdown

In initial phase I am looking to implement table display and hopefully graphing using appropriately licensed Javascript chart library, but in later phase we could also investigate viability of alerting on certain triggers.

I am aiming to make elasticsearch module flexible, so it can easily be re-used for pulling anything that's stored in elastic.

**Comment by f0o** [comment]
:+1:

**Comment by Rosiak** [comment]
:+1:

**Comment by chrisgfx** [comment]
:+1:

**Comment by paulgear** [comment]
:+1:, although I prefer nfdump to pmacct, since it's a lot easier to set up.

**Comment by chrisgfx** [comment]
@spaprzycki
When I tried ELK with Netflow I set up ELK / PMACCT and also Netflow with only the Logstash plugin but with dictionnaries to let the traffic to be converted in a Human format (protocol, AS number, GEO Maps, etc.).
So if you would like me to share my tests just drop me an email. :smirk:

**Comment by f0o** [comment]
@spaprzycki any news on this? :)

**Comment by Rosiak** [comment]
Any news? @spaprzycki

**Comment by laf** [comment]
No further info provided.
