### ISSUE TITLE
Discovery Module crashing SNMPD on ESXI 6.0 

### ISSUE THREAD

**Issue by MLWALK3R** [librenms/librenms#1882]
Noticed if ipv6-addresses module is disabled it stops snmpd crashing on ESXI if it's enabled it crashes (obv).

**Comment by SaaldjorMike** [comment]
I've tried the following:
* ESXi 5.1, with ipv6-address discovery module enabled: snmpd crashes within maximally a few days.
* ESXi 6.0, with ipv6-address discovery module enabled: snmpd crashes within maximally a few days.
* ESXi 6.0, with ipv6-address discovery module disabled: snmpd has not crashed for 13+ days so far.

I assume my ESXi 6.0 machines with the ipv6-address module disabled will run perfectly fine from now on, but will poste here if I again experience issues.

**Comment by rgormley** [comment]
@SaaldjorMike at the risk of sounding a novice, where are you disabling IPv6 in ESXi?

**Comment by SaaldjorMike** [comment]
@rgormley You can disable the ipv6-addresses discovery module by going to `/device/device=X/tab=edit/section=modules/` (replace X with your device ID) or by going to the device in the UI -> device settings -> Modules.

**Comment by laf** [comment]
Not sure this is something we can fix. Work around is as above.
