### ISSUE TITLE
Globe-Fontpage doesnt look fancy

### ISSUE THREAD

**Issue by arjitc** [librenms/librenms#1884]
Hello,
When using Globe-Fontpage (http://docs.librenms.org/Extensions/Globe-Frontpage/), it results with the following, looks not so good..

![2015-09-12_22-15-49](https://cloud.githubusercontent.com/assets/363587/9832565/5f0a6e1e-599c-11e5-9c86-7002eb7bb0b0.png)

**Comment by Rosiak** [comment]
Hi @arjitc 
Have you tried the new tiles.php?

**Comment by spaprzycki** [comment]
I am half way there with turning top X ports/devices into proper widgets for tiles.

**Comment by laf** [comment]
Awesome :)

**Comment by arjitc** [comment]
@rosiak mmm I had used it a while back, I'll give it a try again now, had switched back to default.php for a while

**Comment by Rosiak** [comment]
@arjitc 
Please let us know if this resolves your issue.

**Comment by Rosiak** [comment]
Hi @arjitc,
#1903 has now been merged, so device-summ-vert and horiz are now available as widgets.

**Comment by laf** [comment]
Closing, feel free to re-open if this still doesn't work for you.
