### ISSUE TITLE
notes field for devices and ports?

### ISSUE THREAD

**Issue by Alastair-VOIPUNLIMITED** [librenms/librenms#1897]
Hi Guys!

Wondering if it would be helpful for those who have larger networks to have a notes field/box somewhere on port pages and device pages on the web gui.

This would enable us for example to chuck in all details for a circuit or device, eg. contact details, reference numbers, attached port or interconnect details for reference. LibreNMS is becoming a very powerful tool on which we are relying more and more.

I keep throwing feature requests I apologise ;)

Thank you

Alastair

**Comment by masonke** [comment]
That has some interesting possibilities
~KEM

**Comment by Rosiak** [comment]
Hi @Alastair-VOIPUNLIMITED ,

Makes perfectly sense from my POV.
How does this quick mock-up do?

![notes](https://cloud.githubusercontent.com/assets/6378934/9859899/244d19d2-5b29-11e5-8555-e2aa871f89a1.png)

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

:+1: to the mock-up

On September 14, 2015 9:40:42 PM GMT+02:00, "Søren Rosiak" <notifications@github.com> wrote:
>Hi @Alastair-VOIPUNLIMITED ,
>
>Makes perfectly sense from my POV.
>How does this quick mock-up do?
>
>![notes](https://cloud.githubusercontent.com/assets/6378934/9859899/244d19d2-5b29-11e5-8555-e2aa871f89a1.png)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/1897#issuecomment-140185964

- --
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJPBAEBCgA5BQJV98yhMhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikg
PGYwb0BsaWJyZW5tcy5vcmc+AAoJEJMZKtVWOFzBjfIP/0eCX8QIISEGjJJlgfF+
8wGSL19ztZAfopj7ANbGHh2yzBV2jbmdWOglaDWmRazbhjZK9D8n+SWpEq520hQH
fQXg9IHxgsdPHrSbsET5gg5Z+RImnX5rDcK4RVtOwu+AuhSGUDpWkfWz1mTfr+YU
ejWiGU8yIoEbb8bSDHKHGRAFMvnFA7mgAdMC8JROmnx+d2+JivQzaRFr9cTR7rh1
1dgmAMOJcG1SObaHFL6fJwHTmqujVCiFA9mfIe4Lmyn1e/yQumDNQM2ZfXUvpgby
snPRHxTLRYEDvwGbwFceWv4c7CZljTJWlMhBELUoatfmt/0LmuEJwlEdtPSZ6sOC
KoRh0uTekwYSFAjtfHlDuIxyqPuLXGlkBAQRsNroa7VKKGgFVWYZXeQCDy+D4kx4
atewXyQFl6iwJoDWrhBW58uoyhgLxTE1A3XC7IoPz7PEJM5EJC5W1ZKr55r1fII8
NCrZDGamNduCNEz7Yn0s7MvJMyAy2pdP2kXFUQm7CdMsDW8V8uv/ewPIuZv5H+dp
RGlm8WZ8uzpocdBapbR9vNEgI1dZ2XEeL8DY2GehJb/gCg3T0+Mu+g+x+Wu1bOQo
YfWWsUU2dl1ikgaCsel6k/PobTLQI4KCukhMK/Rk/Vh6/1VhpvzfLaKsl7V6it5t
XFotC6juPRJHeee8vixnr6aS
=9qG4
-----END PGP SIGNATURE-----

**Comment by Rosiak** [comment]
@Alastair-VOIPUNLIMITED what do you think about my example?
If it's OK with you, I'll move on.

**Comment by Alastair-VOIPUNLIMITED** [comment]
Hey Rosiak,

Sorry for my late reply, i was off for a couple days and this slipped the net.

That mock up looks really great, is it possible to do something similar for ports too? probably ALOT more work so might be worth seeing if others would find it helpful too, :)


Cheers

Alastair

**Comment by Rosiak** [comment]
Will see if I can close this one before new year :)

**Comment by Rosiak** [comment]
Closing.
