### ISSUE TITLE
Working NginX/PHP-FPM config for Ubuntu

### ISSUE THREAD

**Issue by bartdebruijn** [librenms/librenms#1904]
This works for Ubuntu, needs to be added to the docs:

=> /etc/nginx/fastcgi_params

fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  HTTPS              $https if_not_empty;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

\# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param  REDIRECT_STATUS    200;

=> /etc/nginx/sites-enabled/default

server {
 listen 80;
 server_name 1.2.3.4; # Yes I access it via IP, Change to domain if required
 root        /opt/librenms/html;
 index       index.php;
 location / {
  disable_symlinks off;
  try_files $uri $uri/ @librenms;
 }
 location ~ \.php {
  include fastcgi_params;
  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  fastcgi_split_path_info ^(.+\.php)(/.+)$;
  fastcgi_pass unix:/var/run/php5-fpm.sock;
 }
 location ~ /\.ht {
  deny all;
 }
 location @librenms {
  rewrite ^api/v0(.*)$ /api_v0.php/$1 last;
  rewrite ^(.+)$ /index.php/$1 last;
 }
}

**Comment by MLWALK3R** [comment]
To get the RHEL guide working on Ubuntu all that needed changing is   **include fastcgi.conf;** to **include fastcgi_params;**
```
server {
 listen      80 default_server;
 root        /opt/librenms/html;
 index       index.php;
 access_log  /opt/librenms/logs/access_log;
 error_log   /opt/librenms/logs/error_log;

 location / {
  try_files $uri $uri/ @librenms;
 }
 location ~ \.php {
  include fastcgi_params;
  fastcgi_split_path_info ^(.+\.php)(/.+)$;
  fastcgi_pass unix:/var/run/php5-fpm.sock;
 }
 location ~ /\.ht {
  deny all;
 }
 location @librenms {
  rewrite ^api/v0(.*)$ /api_v0.php/$1 last;
  rewrite ^(.+)$ /index.php/$1 last;
 }
}

```

**Comment by rlex** [comment]
@MLWALK3R you missed 
```
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
```
in php location, it opens with white page without that parameter.

**Comment by MLWALK3R** [comment]
@rlex That's the config I'm using and it works without that (spooky).

**Comment by Diftraku** [comment]
I found myself using MariaDB+nginx+PHP5-FPM with the following nginx configs successfully:
```
server {
        listen 80;
        server_name librenms;
        root /opt/librenms/html;
        index index.php;

        ##
        # Logging
        ##
        access_log /var/log/nginx/librenms.access.log;
        error_log  /var/log/nginx/librenms.error.log;

        location / {
                try_files $uri $uri/ /index.php;
        }

        ##
        # PHP-FPM
        ##
        include php.conf;
}
```

And php.conf is simply:
```
location ~ \.(php)$ {
    fastcgi_keep_conn on;
    fastcgi_pass   unix:/var/run/php5-fpm.sock;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include        fastcgi_params;
}
```

I have done some pre-eliminary testing to run LibreNMS on nginx+HHVM and so far there are some incompatibilities between PHP-FPM and HHVM that bork the setup a bit, I won't hijack this issue but will create one to track it separately.

**Comment by loganmarchione** [comment]
> I found myself using MariaDB+nginx+PHP5-FPM with the following nginx configs successfully:


@Diftraku, did you have any issues getting graphs to work on Ubuntu+MariaDB+Nginx? I'm running the same setup and can't get any graphs. Did you follow the steps in the docs? See my issue [here](https://github.com/librenms/librenms/issues/2045)...

**Comment by khobbits** [comment]
One thing to note:
rewrite ^api/v0(.*)$ /api_v0.php/$1 last;

This needs to be:
rewrite api/v0(.*)$ /api_v0.php/$1 last;

Or the API won't work.

**Comment by laf** [comment]
@khobbits 

Thanks. We've actually only just had a PR to remove the ^. Do you have your install in /opt/librenms?

https://github.com/librenms/librenms/commit/f52e7cb92ffc28447ba25c577c6e6eea1168409f

**Comment by khobbits** [comment]
Yep, I do.  I can't imagine many people actually would need to use the api, I'm only using it to register alert status with prtg (we're trying to go emailless and have a single alerting dashboard)

**Comment by laf** [comment]
I'll flag this to the other user and see if they can comment on why they removed the ^.

Thanks for fixing the bug, wouldn't say it's a major one as I know of a number of people using the API without issues they just must not use those particular filters. The API is still quite new / early in development, if you're starting to use it and find it doesn't do what you need then we'd love to see it improved and extended :)

**Comment by laf** [comment]
@paszczus would you be able to comment on this further. Your change and the one proposed by @khobbits conflict so we'd like to make sure we get the correct version for people to use.

**Comment by paszczus** [comment]
@laf thanks for asking me. I have tested this and with "^" API is not working. I am unable to get nodes for oxidized with ^. I have just tested this again, so please don`t add it to docs.
I am using debian 8.2 with nginx.

**Comment by laf** [comment]
@paszczus Ok so it should be as @khobbits has said:

`rewrite api/v0(.*)$ /api_v0.php/$1 last;`

Unless I misunderstood you?

**Comment by paszczus** [comment]
Yes, my current config (which should be already in docs?) is like that: 

rewrite api/v0(.*)$ /api_v0.php/$1 last;

**Comment by paszczus** [comment]
yep, it`s already in docs but for RHEL/CentOS

https://github.com/librenms/librenms/commit/f52e7cb92ffc28447ba25c577c6e6eea1168409f

**Comment by laf** [comment]
@paszczus you're right. Sorry for bothering you.

@khobbits the docs show the example without the ^ for the CentOS install guide, have you seen docs elsewhere? If you are looking at your local install then it's because you will need to update. The docs were updated about 4 weeks ago.

**Comment by khobbits** [comment]
Yep, I installed about 6 weeks ago.
I fixed the bug loudly, and the master branch is correct.  The examples in this thread above, without that change will not work at, and will return 404 errors.
I was just leaving a note in case this example was copied to docs without that update.
