### ISSUE TITLE
Daily update not working

### ISSUE THREAD

**Issue by anderssonpof** [librenms/librenms#1905]
Hi,

Noticed last week that I didn't get daily updates. Made a manual one to get up to the latest and hoped it would kick in again after that, but that doesn't seem to be the case.

Currently on: 9bda8b6

Config.php line:
``` $config['update'] = 1;```

cron.d:
```15   0    * * *   root    sh /opt/librenms/daily.sh >> /dev/null 2>&1```

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi

The cronjob changed, please remove the 'sh' infront of the path.

If that still doesnt do the trick then paste us the output of daily.sh please.

On September 15, 2015 1:28:51 PM GMT+02:00, anderssonpof <notifications@github.com> wrote:
>Hi,
>
>Noticed last week that I didn't get daily updates. Made a manual one to
>get up to the latest and hoped it would kick in again after that, but
>that doesn't seem to be the case.
>
>Currently on: 9bda8b6
>
>Config.php line:
>``` $config['update'] = 1;```
>
>cron.d:
>```15   0    * * *   root    sh /opt/librenms/daily.sh >> /dev/null
>2>&1```
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/1905

- --
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJPBAEBCgA5BQJV+AFfMhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikg
PGYwb0BsaWJyZW5tcy5vcmc+AAoJEJMZKtVWOFzBjOEP/RTXlch197rnxBUyfdEJ
xHvQmmEcq3web7BHhnqFF94Tr7Az4rVPpBy9zm9/T6VJsBbwQPNy65Z9+cG6mFdn
+EVdrTw9BiDDpiRQCsgdQiwY5lK58VVUr9H6cn44bW7jC+b7z1dPpVNGYEgHHJhB
JOUXtOX+Jbt11mSGrU0Iv+X2WzwbxUOtmbX4GqfAkPyr+ZlJedNNzRfiOteFYw/n
2rO7UzorJ566WO00tstL3pkMoItRi8GBtAfUpzWAs4SImPAeN8b3ddReHwrlOF7j
vBkVbCQl8HPLvpCUYEOlnHo7N3f838wfynezCECPI1TTzJtT3sNf8oyYwq0vLGJh
dJxJ8BcawMvLWrOKPSekx4vJApALoSpGnZTj+Ad8A8Qlt35PG3keq3gxVYhRpg6Q
cnQnEg9pgKzRqfEVLVUnER2lFL9HQZvVDQOoMh6RGM9RKUXyLqQLPzcRJPIkckce
cGASONOq2ZqFOXJHwrJV8Dn40gRxpXLtO5pPx4eHcf8QMemZriq0Lf46UyjyMk7y
HKoQhCeTJrN9w8K5TN/kJcn5jLtMlVVRBYUOFTlCCTF283Xd+soBjx34XXdUdN3J
YO5hvSNmYTX0IdBb7hIucsYU5VFovBgrm1YKZ255urVGGt4sQ+jQnGsZkWaU1Kf9
8LDLO9Sf9EdVAXYDNf1C7gcL
=O0wT
-----END PGP SIGNATURE-----

**Comment by anderssonpof** [comment]
@f0o 
Changed the line in cron but stil didn't update last night.

Ran daily.sh manually and got this:

```InnoDB Buffersize too small.
Current size: 128 MiB
Minimum Required: 134.3125 MiB
To ensure integrity, we're not going to pull any updates until the buffersize has been adjusted.```

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Well there you got your reason ;)

Increase the buffer size of your innodb and you're all fine. I'd set it to 512MiB to start with.

On September 16, 2015 10:38:45 AM GMT+02:00, anderssonpof <notifications@github.com> wrote:
>@f0o
>Changed the line in cron but stil didn't update last night.
>
>Ran daily.sh manually and got this:
>
>```InnoDB Buffersize too small.
>Current size: 128 MiB
>Minimum Required: 134.3125 MiB
>To ensure integrity, we're not going to pull any updates until the
>buffersize has been adjusted.```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/1905#issuecomment-140672173
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJPBAEBCgA5BQJV+StAMhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikg
PGYwb0BsaWJyZW5tcy5vcmc+AAoJEJMZKtVWOFzBvUUP/RYKoHMUq08nkv63G3Dx
wflBhip+mCphWnKkc3nUQGlYqtc9suulET0ODn/Um35e+XrbqVrO0v4eYzZYgmFW
yIeqxmnERT2y/GZOO9g9bVrw8IzSLD4vtJV5TPQWNfAXEpnIhs/NMkSp512B2+pz
6Af/1AJujxqOe8N3gfAd0rp9kh1T/X2A84JTcXhKh2Vz+Ag5doOs0r77QusGY4pQ
bAQoLH1rc+dkMHCPKF6ACABSUPZGstrX9h+BpBT/olP13yFKptH5+ABUVDMr2/R6
AGz2r2jgosWDq4WwPhtNK2yHMMISJ5jZszjbQ6yHZVjZ1N4EGTVp43CaAwXAyUOG
aRrHn+uQ8lfUXoGV2st8njg8FB5kYWiup0Dmt4B81ZkkOqPqrXTNtLAWDtaWO/7l
ji6J8z85fHzRF3vlLROGcxrnp1Pc76sJvtLzisjhu6Ss/lKZAhPya8JY519siAyE
m4WVGYIH7OGHkxDb4bIQkYyiQHQL1uyxmn1xsq0VvwumgpwbCUwSkRvn4z1HXyq+
i80S9hJ8Yxg1gSxy/PSg3P5jlMsh9eRQZnbPx+L7sEf/rUSS16xJcFM34w7obvW/
b65fVvA63a2of/iIF/0BxVdBzvNl1cfG4JYr/ZwVARuYVswDWLtXTbDkUu7F6O0N
FGT2+1bYR4uCf7anwxPKIjB7
=TG/7
-----END PGP SIGNATURE-----

**Comment by anderssonpof** [comment]
Yea :)

Tried the following:

service mysql stop
added innodb_log_buffer_size = 512M to /etc/mysql/my.cnf

then did: 
cd /var/lib/mysql
mv ib_logfile0 ib_logfile0.bak
mv ib_logfile1 ib_logfile1.bak
service mysql start

Logged into mysql and got the following:
show variables like 'innodb_buffer%';
+------------------------------+-----------+
| Variable_name                | Value     |
+------------------------------+-----------+
| innodb_buffer_pool_instances | 1         |
| innodb_buffer_pool_size      | 134217728 |
+------------------------------+-----------+
2 rows in set (0.00 sec)

No change in size?

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Oh man moving the ib_logfiles is hazardous!

Also the correct setting is:
`innodb_buffer_pool_size = 512M`

:)

On September 16, 2015 10:55:47 AM GMT+02:00, anderssonpof <notifications@github.com> wrote:
>Yea :)
>
>Tried the following:
>
>service mysql stop
>added innodb_log_buffer_size = 512M to /etc/mysql/my.cnf
>
>then did:
>cd /var/lib/mysql
>mv ib_logfile0 ib_logfile0.bak
>mv ib_logfile1 ib_logfile1.bak
>service mysql start
>
>Logged into mysql and got the following:
>show variables like 'innodb_buffer%';
>+------------------------------+-----------+
>| Variable_name                | Value     |
>+------------------------------+-----------+
>| innodb_buffer_pool_instances | 1         |
>| innodb_buffer_pool_size      | 134217728 |
>+------------------------------+-----------+
>2 rows in set (0.00 sec)
>
>No change in size?
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/1905#issuecomment-140676214
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJPBAEBCgA5BQJV+S+qMhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikg
PGYwb0BsaWJyZW5tcy5vcmc+AAoJEJMZKtVWOFzBvLcP/2JHeFul5TZ0PrXvrvYU
Nz0622usDb2dzdojJDk6Z/GawX0xsKtwWG0Al0O06h+kd+cMdVYk4SKGk+5Ujibm
7/F3nGd3a+yk4zMHcSNgV82M1PCMeEaVmwXvGNLyfycUV6p6v9e2J02jik25VrbE
SieZJaEjsnNhcGjKHCnj8mzqKFiuh28t1jAnL+eyDTQsUgFhMHDB9Z/Yd1GIMywS
S7Plw7XsjDPrj0i6eHy6l/wi/Vdj5IXIiFkZCejth9ybOAx6f+dYiStKmzWMwk5J
7st9Hozxjhx7NdZFRrMXQw3FxRPOSDMhMMCC4BKjy/d4ZxvYPzGfW1i/H2LK9Opj
TQ7w0dbyMspmBndPlOnvm8kQkvo5frD9eO3YoSDMvFIJ5cWPzbI0hhLN4RAvmCi1
5BSFKE/sPOz2dKknNEuvtWcUEDB05lQJjL6PQLpFBjfG/jlefY66BtjCAeNUliTj
5Zl77Fii0/ORDFCP0TY6LyEhaUva5WXJ6Vwf3Bxf/yfFO8yn1grUwcGveEzcVGV7
9kCvWiZ+CKH5IhSwNIdtdhZHTGKtFpfG5BNBWbdAQZX2Lyhb3LcSx6ZypaI9LWt6
DV8wAVuCpZDP86kSCbyy1fzf6tggYZPkltv4LxTNEU74e92TKIVzihmm6DiofQHV
27jTyIqkly4TSMMoM8a21tG9
=pYzW
-----END PGP SIGNATURE-----

**Comment by anderssonpof** [comment]
That solved it.
Thanks!
