### ISSUE TITLE
Mikrotik active AAA sessions

### ISSUE THREAD

**Issue by acidsas** [librenms/librenms#1908]
Can someone add a graph for the active AAA sessions (pppoe/pptp/hotspot/etc). Here is the oid — 1.3.6.1.4.1.9.9.150.1.1.1.0
I think it's already done for CISCO.

I can provide access to a Mikrotik if needed.

**Comment by Rosiak** [comment]
Hi @acidsas ,
Can you post the SNMP data?
Just a request for that OID and the result.

**Comment by acidsas** [comment]
Hi @Rosiak 
Here you go...
snmpwalk -c public -v2c sr1.xxxxx.com 1.3.6.1.4.1.9.9.150.1.1.1.0
SNMPv2-SMI::enterprises.9.9.150.1.1.1.0 = Gauge32: 461

**Comment by laf** [comment]
This is potentially possible with @paulgear MIB poller. Prob worth waiting for v2 to be released on that.

**Comment by paulgear** [comment]
MIB-based polling was merged recently, but I couldn't find any reference to that OID in the code, so I added the MIB and reference to it in PR #2784.
