### ISSUE TITLE
OpenStreetMap show to many devices.

### ISSUE THREAD

**Issue by thomasraabo** [librenms/librenms#1910]
I only have a total of two devices in my test setup.

But on the google map it shows a total of 8 devices on the map.

There are no dublicate entries in the db etc..

**Comment by laf** [comment]
@thomasraabo Can you provide a screenshot? Are the actual devices on the map duplicates of each other?

**Comment by thomasraabo** [comment]
http://snag.gy/Kuu7s.jpg

Every device is there 4 times.
