### ISSUE TITLE
Graylog integration and working with Cisco and Cisco SMB

### ISSUE THREAD

**Issue by thomasraabo** [librenms/librenms#1911]
It seems Cisco will not put in full hostname in syslog packet ( no RFC support )

So we need a way for LibreNMS to use IP if specified

http://netmgmt-c002.net.xxxx.com/device/device=10.0.6.4/
 
Converting from hostname edge-sw-1.xxxx to ip 10.0.6.4 when it integrates with graylog

**Comment by laf** [comment]
This is not so simple to fix. The issue I see is we don't have a hostname = ip recorded somewhere, we have a list of IPs on the device but these can be duplicated depending on your setup. Looking up the IP for each hostname in the graylog lookup is probably too much.

We would potentially need to lookup the IP on discovery and record that to use.

Anyone else see another way?

**Comment by mail3dexter** [comment]
@thomasraabo : Try to put an host entry in /etc/hosts for the switch which is not sending its name. I think it will be replaced by its name. I think i have tried this in past and it had worked. Try it and let us know.
