### ISSUE TITLE
Discussion: CentOS 7.x is a bit trickier to setup "correctly".  What needs updating?

### ISSUE THREAD

**Issue by MindTooth** [librenms/librenms#1912]
Hi,

The past few days, I've been hammering at getting LibreNMS running on CentOS 7.x.  (I started to add Gitweb on the old one, so I wanted to start fresh).  However, the CentOS guide provided in the docs are far from complete, at least for CentOS 7.x that is.  It don't touches SELinux, and the RRDCached page don't work because the `librenms` is not in the `nginx` group.  Which I believe is do to the fact that NGINX is run as the `nginx`user/group.

My observations so far:
* CentOS 7.x is a total different beast to tackle.  At least with SELinux set to `Enforcing`.
* With SELinux enabled (which is recommended), there are a few more steps to take before making fping, RRDCached and NGINX work.
* The `librenms` should be part of the `nginx` group, and not the `apache` group.  (At least for me, not being a member of the  `apache` group doesn't do much.)
* vixie-cron is replaced by cronie.
* Maybe guide towards enabling both the MariaDB and NGINX repo for a more updated experience.
* Tweak the rrdcached.service file. (I needed to change the `-s` option to `nginx`.  Not sure this is only because of SELinux, but I couldn't detect any audit problems.)

My goal with this issue, is to create a discussion on what _you_ prefer as the best way.  And if me updating the docs are of interest.
I've personally outlined mine above, and made it work after several trials..  SELinux is not recommended to be disabled, or set to `Permissive`.

Thought?

My own changes: https://gist.github.com/MindTooth/5c461d36981f4ffcfb2c

**Comment by laf** [comment]
It's really difficult to provide full config for every permutation people may run so in some ways the docs are a pointer to get people running with the standard lamp setup. 

We have looked at other docs systems that support templates as a lot of the install docs are duplicated with only minor changes. 

We accept pr's updating the docs :)

**Comment by MindTooth** [comment]
What's your stance on SELinux?  The guide won't work without configure it or disable it.  I have not tried with Apache.  But I guess that won't work either as the guide use a none-native path for the web server.

I'll see if I put up some PR's when the times come :-)  Currently just happy I made it work on CentOS and SELinux enabled.  A more than a few hours spent :-P

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

I've a policy in evaluation currently. However it cant be shipped before we get the automated .deb and .rpm builds done to ensure the correct policy is loaded for the used setup.

Cheets,
Daniel / f0o


On September 22, 2015 7:43:34 AM GMT+02:00, "Birger J. Nordølum" <notifications@github.com> wrote:
>What's your stance on SELinux?  The guide won't work without configure
>it or disable it.  I have not tried with Apache.  But I guess that
>won't work either as the guide use a none-native path for the web
>server.
>
>I'll see if I put up some PR's when the times come :-)  Currently just
>happy I made it work on CentOS and SELinux enabled.  A more than a few
>hours spent :-P
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/1912#issuecomment-142186052
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJPBAEBCgA5BQJWAPHFMhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikg
PGYwb0BsaWJyZW5tcy5vcmc+AAoJEJMZKtVWOFzB/ZAP/RtU5DovvPpng05hGPxC
5/x4Abz/5oJ4gCIV4aQ7xvtHByezV3AuCdm/pElhjLO3sVy54G7lyrqVun2XEvRe
RnE0fbIxfydUG3oY7dTCYXshmiHcrc5fM+9lyK6+4x6Q3eUjZiaUBvBsLYt9JCUd
1Dr1MePP0/MY4+j9GLj4lrvKOMwcZus746FZBkrbxmH1C0pQwXH4ZbQ/ZC8iUliK
LI1UNaGNhHV4JjwHgoqv9qJ48lGP+5+ekYxDPTl88fI5ORtntNlQnsf7X9kU0jp/
U9EAdlEE7psWbf09lHppe0g7IP5DQlzgJMb6eTZ6kYuEV/EaGrwKnVE1vkXQkDco
ENCWUKi880/eQuftib+lfjpyR++VrM2OLDHg/2DUamBjG2P6AYS5Nu2zGtb00wBV
4W2WnwMLxn3c1Ym5gRz3Qg4zXvZ1+jLjUYWJ/4o/GI8USQhcj5/XimkRRg/f4xvZ
rIdRqrwoG8ZZK2mErdqVRBEvAKERTewQxlqEOGxKOsK7wNLfrDMPMD/elQpdRFwL
DwECMcszoF020rW46QkNNDEj7w/iUP29TB9jNWLlz6RHZxUCKDKf98eOKzQtHuvr
nOVQ+GjVes0TQLfM5C3IWG1K4+HC+IjlaiCjgp7HKQknKc0vnIzrsTvIjuP224Wy
1o4KdRSQOBqYl7ED7n3ScDU1
=k4jH
-----END PGP SIGNATURE-----

**Comment by MindTooth** [comment]
#2043 should alleviate the issues :+1:

**Comment by f0o** [comment]
#2043 Merged :)
