### ISSUE TITLE
Alerting not send email and push message

### ISSUE THREAD

**Issue by 21let** [librenms/librenms#1918]
In the settings I have set Alerting Settings if I click on the "test transport", email or push notification using pushbullet works and get the message. The problem is failure device (Down, reboot etc.), No message me arrive. The outage alerts are displayed alert rules in the rule of UP / DOWN allowed.

**Comment by f0o** [comment]
Do you have correct timezones set?
Double check that the zone on your mysql-server is the same as on the librenms box and also set in the php.ini

**Comment by 21let** [comment]
Default timezone is "Europe/Prague".

This is alert rules:
![image](https://cloud.githubusercontent.com/assets/13964136/9926213/e6d2ef7c-5d13-11e5-9b14-a283311f59fd.png)

**Comment by laf** [comment]
If its sending via other transports then I wouldn`t expect it to be timezone issue. 

Have you checked your mail logs?

**Comment by 21let** [comment]
Over the next transport are not working. I have set up email and pushbullet. When you click the Test button TRANSPORT, email and pushbullet is delivered. It looks like a problem that does not work properly send through CRON scripts. According to the screenshots I have alert rules set correctly, right?

**Comment by 21let** [comment]
Problem solved.
The problem was /etc/cron.d/librenms where alert.php at me for some unknown reason to me occurred alert.ph file so that it follows the current /etc/cron.d/librenms

33  */6   * * *   root    /opt/librenms/discovery.php -h all >> /dev/null 2>&1
*/5  *    * * *   root    /opt/librenms/discovery.php -h new >> /dev/null 2>&1
*/5  *    * * *   root    /opt/librenms/cronic /opt/librenms/poller-wrapper.py 16
15   0    * * *   root    /opt/librenms/daily.sh >> /dev/null 2>&1
*    *    * * *   root    /opt/librenms/alerts.php >> /dev/null 2>&1
