### ISSUE TITLE
Drawing Graph Error

### ISSUE THREAD

**Issue by Blade-of-Grass** [librenms/librenms#1934]
A fresh install of LibreNMS does not seem to be able to draw any graph. Every graph is blank with the title "Error Drawing Graph".

Any ideas?

Results of debugging a graph page (php errors) http://pastebin.com/cZSnr49X

**Comment by masonke** [comment]
Make sure all the files in rrd directory are owned by librenms. That has helped me in the past
~KEM

**Comment by Rosiak** [comment]
Please run the validate.php script and post the output.

**Comment by Blade-of-Grass** [comment]
[OK]      config.php tested ok
    [OK]      Database connection successful
    [OK]      fping has been found

**Comment by laf** [comment]
chown -R librenms:librenms /opt/librenms/rrd

**Comment by Blade-of-Grass** [comment]
rrd is already owned by librenms and is empty.

**Comment by Rosiak** [comment]
Is the cronjob setup correct? 
Also do you see anything in /opt/librenms/logs/librenms.log?

**Comment by Blade-of-Grass** [comment]
Librenms.log doesn't seem to exist, only access and error logs are in that directory. 
I see no cronjobs for user librenms.
On Sep 19, 2015 5:07 PM, Søren Rosiak <notifications@github.com> wrote:Is the cronjob setup correct? 
Also do you see anything in /opt/librenms/logs/librenms.log?

**Comment by Rosiak** [comment]
Sounds like you missed some steps.

Please go through:
http://docs.librenms.org/Installation/Installation-(RHEL-CentOS)/ 
or 
http://docs.librenms.org/Installation/Installation-(Debian-Ubuntu)/ 

And verify that you followed those steps.

**Comment by Blade-of-Grass** [comment]
You are correct, I missed the last two steps.

Thank you for the help!
