### ISSUE TITLE
Disable ICMP Check On Polling

### ISSUE THREAD

**Issue by vectr0n** [librenms/librenms#1936]
I know this won't fit everyone's situation, but for me I have other monitoring for ping reply. I know things like Cacti are able to use the snmp as a validation the host is up. This would not be desirable for people with heavy CPU loads, for me this is not the case. So having the option to disable the ICMP checking on polling would be a great help. Thanks

**Comment by 127-0-0-1** [comment]
+1 for this feature

**Comment by GordSpence** [comment]
+1 as well. We've got lots of remote servers behind firewalls that we don't necessarily want to have ping available on.

**Comment by tgreer** [comment]
Yarg +1

**Comment by laf** [comment]
I have a quick test if anyone wants to give it a go, this only provides global disabling of icmp checking. If the feedback is positive then I'll extend this out to do it on a per device basis.

```
cd /opt/librenms
git remote add laf https://github.com/laf/librenms
git remote update laf
git checkout issue-1936
```

Then set this in config.php:

`$config['icmp_check'] = false;`

When you want to get back to the upstream just do:

```
git checkout master
```

**Comment by tgreer** [comment]
Currently running @laf's copy, all seems well.

**Comment by vectr0n** [comment]
Also running @laf's copy without issues.

**Comment by 127-0-0-1** [comment]
All is good. Thanks.

**Comment by f0o** [comment]
@laf PR-worthy? :)

**Comment by laf** [comment]
@f0o Yeah, I'd like to add the option to disable it per device though as well. I'll add that tonight + update docs.

**Comment by f0o** [comment]
:+1:

**Comment by laf** [comment]
All done.

For those running this already you can do:

`git pull`

If you want to test further - if not you can go back to upstream with:

`git checkout master`
