### ISSUE TITLE
Device and port notes don't honour new lines

### ISSUE THREAD

**Issue by laf** [librenms/librenms#1939]
![image](https://cloud.githubusercontent.com/assets/3941142/9982406/53f8b746-5fd3-11e5-8376-03cd1fd0789a.png)

**Comment by Rosiak** [comment]
The perfect fit for this task would be a editor like this.
http://summernote.org/#/

Or perhaps that's way "over-target"?

**Comment by laf** [comment]
lol, possibly ott unless we have a use elsewhere for it :)

**Comment by f0o** [comment]
Arent there any lightweight "what you see is what you get" editors in js? We dont require rendering outside the editor if that makes it easier

**Comment by laf** [comment]
I'm sure there are some yeah :)
