### ISSUE TITLE
Server CPU graph

### ISSUE THREAD

**Issue by XxPatrickxX** [librenms/librenms#1971]
Can we update the Overview tab for a system (https://librenms.mydomain.local/device/device=xxx/tab=overview/) to show the CPU graph found on (https://librenms.mydomain.local/graphs/type=device_processor/device=xxx/to=1442948100/from=1442861700/)? With systems showing 20+ logical processors the Overview tab cpu listing isn't too informative.

**Comment by Rosiak** [comment]
Has this been fixed with the introduction of the collapsed CPU graphs?
If so let's close this one.
