### ISSUE TITLE
Make graphs transparent 

### ISSUE THREAD

**Issue by arjitc** [librenms/librenms#1972]
Currently the graph has a white(?) background when being displayed, this makes it look a bit weird, any way to make it transparent?

![2015-09-23_01-08-05](https://cloud.githubusercontent.com/assets/363587/10029462/a17fedaa-618f-11e5-8b8c-629e25ecc067.png)

**Comment by laf** [comment]
That actually looks like it's css doing it. 

Check: html/css/styles.css

line 686

We have a lot of crap css from before we used bootstrap which needs to go, this looks like one of them.

**Comment by arjitc** [comment]
Hmm, removed line 686 and it's still white (I hope it isn't cloudflare caching too much)

http://i.imgur.com/OYWyHxj.png

**Comment by arjitc** [comment]
Ah when line 686 is removed the mini graphs which appear on mouse over go transparent as well :/

**Comment by laf** [comment]
![image](https://cloud.githubusercontent.com/assets/3941142/10044608/40355c0a-61f4-11e5-9105-0b527a56a8e8.png)

Look at my developer console, removed the background color. For popover will probably just need to add another css class to add white bg back in.

**Comment by laf** [comment]
This looks like it's now as requested.
