### ISSUE TITLE
Weird spacing in settings menu

### ISSUE THREAD

**Issue by SaaldjorMike** [librenms/librenms#1984]
See large gap between API and Refresh disabled:
https://i.imgur.com/iKWPZhu.png

**Comment by laf** [comment]
What page? This is alert settings page:

![image](https://cloud.githubusercontent.com/assets/3941142/10044635/7380151e-61f4-11e5-8b9d-a98b32ce1422.png)

**Comment by Rosiak** [comment]
Hmm, can't reproduce this.

**Comment by SaaldjorMike** [comment]
It is when just viewing the front page (tiles if that matters).
Seems to be ok in Firefox, but not in Chrome (Version 45.0.2454.99 (64-bit) on OS X).

**Comment by laf** [comment]
Still ok for me in Chrome :(

Version 45.0.2454.99 (64-bit) on OS X

**Comment by SaaldjorMike** [comment]
Ok, seems to actually be an issue when using other zoom levels in my browser. Due to the small width of my screen I get a top menubar like this: https://i.imgur.com/N2YrO6M.png
Typically I'd just zoom out to like 90% zoom level, then it seems there is space enough for the menubar: https://i.imgur.com/t2IOTrA.png
But at 90% zoom level: https://i.imgur.com/Jy6DVhW.png (look below API)
And at 67% zoom level: https://i.imgur.com/EsvKbPh.png (look below Authlog)

Any ideas?

**Comment by Rosiak** [comment]
Status on this one?

**Comment by SaaldjorMike** [comment]
Lets close this one for now.
