### ISSUE TITLE
LibreNMS on nginx+HHVM

### ISSUE THREAD

**Issue by Diftraku** [librenms/librenms#1996]
So far, I have a working nginx configuration I am using for LibreNMS and switching over to HHVM was easy. See below for the nginx config (and a similar issue, #1904, for getting LibreNMS running with nginx+PHP-FPM):
```
server {
        listen 80;
        server_name librenms;
        root /opt/librenms/html;
        index index.php;

        ##
        # Logging
        ##
        access_log /var/log/nginx/librenms.access.log;
        error_log  /var/log/nginx/librenms.error.log;

        location / {
                try_files $uri $uri/ /index.php;
        }

        ##
        # HHVM
        ##
        include hhvm.conf;
}
```

The only difference to the issue mentioned before, HHVM does not provide a ```ORIG_SCRIPT_FILENAME``` to the PHP-script. A one-liner to the ``hhvm.conf`` at least gets the stuff running:
```
fastcgi_param  ORIG_SCRIPT_FILENAME $document_root$fastcgi_script_name;
```
While it is similar to ``SCRIPT_FILENAME``, I believe this will get us at least somewhere. The next issue is the lack of SNMP extension on HHVM.

So, to conclude:
* LibreNMS runs beautifully with nginx+PHP-FPM
* HHVM is a special case and thus requires tweaking your nginx configuration
* Lack of an SNMP-extension built into HHVM prevents further testing

**Comment by laf** [comment]
How's it running with HHVM?

**Comment by Diftraku** [comment]
So far: not running, much. The lack of php-snmp extension seems to be the more major one so far.

**Comment by f0o** [comment]
@Diftraku As far as I know, we dont use the PHP SNMP extension at all. We use the snmpget, snmpwalk and snmpbulkwalk executables instead.

**Comment by f0o** [comment]
I'll give it a whirl later today, maybe I get some luck with it :)

**Comment by Diftraku** [comment]
So far, I had to alter ``html/install.php`` to not check for the SNMP extension. Also, ``$_POST['stage']`` is assigned without checking if it is even set, causing a NOTICE (due to how I have set up my error reporting on HHVM.)

After tweaking the installer, it runs through without a hitch and only thing I had to change on my finished setup was to force a protocol agnostic ``base_url`` (``//host.tld``) as the default kept using HTTPS when it was not explicitly enabled.

**Comment by f0o** [comment]
Well, for me it worked drop-in-replaceable.
I'll run some more tests but I didnt had to adjust much at all.

Granted, I already use HTTP and HTTPS install so I've had `//1.2.3.4/` in the config by default.

I've also switched the CLI to hhvm, will observe what happens throughout the day

**Comment by f0o** [comment]
So I ran a quick siege on the nginx and here are the first findings:

To the environment:
- The Network
 - OpenStack virtual network, same subnet, no router in between.
 - Speed test involving 10G download from LibreNMS Box to Siege averaged at 155.26 Mbit/s
- The Siege server
 - 8 Cores, Intel Xeon E312xx (Sandy Bridge), (Fam 6, Mod 42)
 - 16Gb of RAM
 - Red Hat `virtio_net` Network Adapter
 - Debian Jessie
 - Siege 3.0.5
- The LibreNMS Box
 - 4 Cores, Intel Xeon E312xx (Sandy Bridge), (Fam 6, Mod 42)
 - 4Gb of RAM
 - Red Hat `virtio_net` Network Adapter
 - Debian jessie
 - Nginx 1.6.2 using LibreNMS' nginx config
 - HHVM 3.9.1 using default package-mantainer's config with the addition of an include-path
 - PHP5-FPM 5.6.13 using default package-mantainer's config

```text
Siege on static, autoindexing nginx:

Transactions:                  60000 hits
Availability:                 100.00 %
Elapsed time:                 132.54 secs
Data transferred:              21.57 MB
Response time:                  0.55 secs
Transaction rate:             452.69 trans/sec
Throughput:                     0.16 MB/sec
Concurrency:                  250.06
Successful transactions:       60000
Failed transactions:               0
Longest transaction:           63.17
Shortest transaction:           0.00


HHVM:

Transactions:                  59956 hits
Availability:                  99.93 %
Elapsed time:                 142.88 secs
Data transferred:             435.64 MB
Response time:                  0.52 secs
Transaction rate:             419.62 trans/sec
Throughput:                     3.05 MB/sec
Concurrency:                  219.50
Successful transactions:       59956
Failed transactions:              44
Longest transaction:           63.43
Shortest transaction:           0.00


FPM:

NOTE: The test was aborted due to excessive socket failures, despite claiming to be config'able there are no docs whatsoever on doing so. Please extrapolate the results.

Transactions:                   1414 hits
Availability:                  55.89 %
Elapsed time:                   3.17 secs
Data transferred:              10.46 MB
Response time:                  0.15 secs
Transaction rate:             446.06 trans/sec
Throughput:                     3.30 MB/sec
Concurrency:                   65.39
Successful transactions:        1414
Failed transactions:            1116
Longest transaction:            0.65
Shortest transaction:           0.00
```

**Comment by laf** [comment]
Do we need to take anything from this issue or can we close?

**Comment by Diftraku** [comment]
I'd say we can safely close this as resolved, just need to document it on the wiki/docs.
