### ISSUE TITLE
Fix HTML for checkboxes on diverse pages (i.e. login)

### ISSUE THREAD

**Issue by juhovan** [librenms/librenms#1999]
It's very annoying that you can't click the text so I'll change it to a label.
I couldn't find any other check boxes with the same issue so just changing this one.

This introduces another problem because labels' font-weight is the to 700 by bootstrap and it looks funny, will open separate issue about that because I'm thinking it should be changed system wide.

![]
(https://hiekkalaatikko.eu/owncloud/index.php/s/7dPjUr9Klv5grQz/download)

**Comment by Rosiak** [comment]
#2001 fixed.
