### ISSUE TITLE
ARP autodiscovery eventlog anomalies

### ISSUE THREAD

**Issue by paulgear** [librenms/librenms#20]
The ARP autodiscovery as at c1f8a5c2ae0e8999d67f49bd1144bc18c164a01f is working, but produces entries like this in the event log:

2013-11-02 16:45:20 	eth3	Device autodiscovered through ARP on r1.example.com
2013-11-02 16:45:19 		Device autodiscovered through ARP on r2.example.com

The entry should show the name of the host discovered.  I should also work out why sometimes the interface is shown and sometimes it isn't.

**Comment by f0o** [comment]
Can this be closed?

**Comment by laf** [comment]
Tidy up time :) Any more info on can this be closed down?

**Comment by laf** [comment]
Proposing that this is closed. Any objections?

**Comment by paulgear** [comment]
I don't feel strongly about it, but since there's an unexplained issue that we haven't got to the bottom of, my inclination is to keep it open.  Github sorts by date by default, so if you just ignore it it will slowly migrate to the bottom of the list. :-)

**Comment by laf** [comment]
My 'issue' with bug reports like this though are when they are so old and no further info has been given to help track things down then we're kind of stuck with an open issue that may never get closed off. No one else has commented or reported the same so far in the last 18 months. 

Me and f0o go through once in a while trying to clean up stale issues :)

**Comment by f0o** [comment]
Seeing it the same as @laf, also would like to add that out of my own habit (and I'm sure others do the same) the first thing I do when I'm on some project at github is to have a look at the open-issue Number in relation to the issue-age. Although this does not yet apply to us, we shouldnt fancy piling up old issues. Nothing is wrong with having a Needs-Verification or Needs-Info tag and after some time closing it with the note that the issuer can reopen if the error persists.
(just my 2 cents)

**Comment by laf** [comment]
Ok closing this, as always feel free to re-open it but for this issue as I see it:

1. The name has been added a bit ago which was part of the issue.

2. The interface name appearing looked impossible in the way the old code worked but now it's different anyway so possibly a mute point.
