### ISSUE TITLE
Git Pulll

### ISSUE THREAD

**Issue by fran-nlt** [librenms/librenms#2011]
Hi
I apply git pul today
I now a problem whith WebPage.(WebUI)
I the reboot the machine and WebPage works

**Comment by fran-nlt** [comment]
![captura](https://cloud.githubusercontent.com/assets/13962782/10136252/e3de1e2c-65c9-11e5-9265-dba5d8381611.PNG)

The page is loading, but reboot and works

**Comment by f0o** [comment]
No idea what you mean, sorry

as a side node, it's not advised to use `git pull`, please use `daily.sh` instead to update your install

**Comment by fran-nlt** [comment]
sorry
I update the software with gitpull, now I need to reboot the machine to access the website, since it is loading

How do I use dayli.sh?

**Comment by f0o** [comment]
you just run `/opt/librenms/daily.sh`

**Comment by fran-nlt** [comment]
Yo aplique daily.sh, pero la pagina web queda cargando, despues de funcionar correctamente

**Comment by f0o** [comment]
mira a tu logs, un update no rompe la instalacion normalmente :/

**Comment by f0o** [comment]
la pagina te respueste algo? o solo esta blanco? repuesta algo como HTTP 500?

**Comment by fran-nlt** [comment]
Solo esta cargando.
No muestra ningun error.

Reinicio la maquina virtual y vuelve a funcionar, realizo dos o cinco clicks, y vuelva a quedar cargando

**Comment by f0o** [comment]
no lo puedo reproducir, mira a tu logs.
el web-server tiene que escribir algo en tu logs.

**Comment by fran-nlt** [comment]
[Mon Sep 28 10:57:21.087559 2015] [core:notice] [pid 7154] AH00094: Command line: '/usr/sbin/apache2'

**Comment by laf** [comment]
Can we stick to english please, others can help out :)

Is this ok to close now?

**Comment by fran-nlt** [comment]
Yes
Close nos please.

The problem is the server, low RAM

Thanks!
