### ISSUE TITLE
Configurable threshold for Overview Globe

### ISSUE THREAD

**Issue by sradvan** [librenms/librenms#2016]
HI all,

We track a lot of sites in a small corner of the planet, hence our maps get cluttered very easily.

Would it be possible to have some sort of configuration for the overview globe, perhaps to only show problem sites (in red), or the ability to configure a threshold for map items to appear?

Thank you,

**Comment by f0o** [comment]
:+1: will work on this

**Comment by f0o** [comment]
Side-Note: Does the worldmap widget work with configuring the viewpoint and zoom factor so entire NZ is in filling the screen/widget ?
Regardless, will add a switch to only show recently rebooted and/or down devices :)

**Comment by sradvan** [comment]
At this point we aren't running LibreNMS so I can't answer your specific question, but we've come up against this issue in other software. This feature would be of huge benefit to us, and take us a step closer toward planning a deployment.

Thank you for jumping on this!

**Comment by f0o** [comment]
@sradvan feel free to have a look at our https://demo.librenms.org (demo/demo) and either change the current dashboard or create a new fresh one for your testing and playing regarding the worldmap widget.

My proposed PR will cover both globe and worldmap anyways. However the WorldMap widget is much more sophisticated than the Globe.

I will link the PR here once proposed.

**Comment by f0o** [comment]
Been a long time, I dont have a PR-worthy patch. 

Releasing my Tag, maybe somebody else takes over. Sorry

**Comment by laf** [comment]
I'll pick this up soon. Shouldn't be too difficult to just add a toggle switch for the widget with only show down devices?
