### ISSUE TITLE
Slow polling on EX4550

### ISSUE THREAD

**Issue by tobiasa1** [librenms/librenms#2017]
I have two EX4550 stacks with 3 x ex4550-32f in each VC.

One of my stacks takes around 900 seconds to poll, causing issues with graph peaks and alarms.
The other stack is finished in around 250-300 seconds.

From poll-log:
sw1	2015-09-29 11:32:10	General	934.00
sw2  2015-09-29 11:31:00	General	264.50

If I run the poller against sw1 manually it's stuck for most of the time at "Caching Oids: ifEntry" and "Caching Oids: ifEntry ifxEntry".

Each VC has 3x40 ports (32+8) making it around 120xSFP+ in total.

The configuration on both VC's are almost identical except for sw1 being vrrp master.

Any idea how to troubleshoot this further?

Br,
Tobias

**Comment by laf** [comment]
I'd run the snmpbulkwalk command you see in poller that grabs ifEntry data and time that, I expect you are going to see that most of the time is waiting for data back from the device.

**Comment by xtyjan** [comment]
Also experiencing this. Last poller time was 565s. We get some really big peaks in our interface graphs from time to time
Tobiasa1, did you find a solution?

**Comment by tobiasa1** [comment]
Hi,
I found 2 flapping ports in my stack that caused ~60% CPU usage, after disabling them I managed to get the poller time down to ~270s.

I've no graph issues anymore but I still think it's way too long poller time, it most be possible to optimize this by ignoring the data that is not used for example.

/T

**Comment by laf** [comment]
That's good news @tobiasa1 :)

For reducing poll times you can either disable unused / unneeded modules or create an snmp view on the device to restrict what OID's are looked up.

**Comment by Rosiak** [comment]
Any news?

**Comment by tobiasa1** [comment]
The issue is back on my end, even after disabling all flapping interfaces.
I have about 700 ports including sub-interfaces and polling time is 999s+ which make it currently unusable in LibreNMS. Same hardware as when I created this issue (3*ex4550-32f in VC).
RE1 CPU: 15%, RE2 CPU: 40%

Any idea how this can be optimized?

**Comment by laf** [comment]
Have any of the updates we've done helped? Check the performance doc to see if any of the tweaks there help.
