### ISSUE TITLE
Ubiquiti EdgeRouter Platform is not recognized

### ISSUE THREAD

**Issue by paszczus** [librenms/librenms#2019]
I have Ubiquiti EdgeRouter PoE and EdgeRouter PRO added to LibreNMS but "Platform" field is empty for them.

Here is full debug for EdgeRouter PRO:

LibreNMS 2015.master Poller
commit d8e71a3b24db314fa54c8c39b9b39ff510fa74db

DEBUG!
Starting polling run:

SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE '172.16.114.4' ORDER BY `device_id` ASC] 
SQL[SELECT * FROM `devices` WHERE `device_id` = '7'] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '7'] 172.16.114.4 7 edgeos 

SQL[INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('3','3','0','1.89','2.64','2.21','7',NOW())] DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:172.16.114.4:161 sysObjectID.0
SNMPv2-SMI::enterprises.41112.1.5

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -OQUs -m SNMPv2-MIB -M /opt/librenms/mibs udp:172.16.114.4:161 sysUpTime.0 sysLocation.0 sysContact.0 sysName.0
sysUpTime.0 = 94:8:53:37.95
sysLocation.0 = \"K\"
sysContact.0 = \"biuro@foo.opole.pl\"
sysName.0 = ComeIn

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:172.16.114.4:161 sysDescr.0
EdgeOS v1.7.0rc2.4781606.150616.1222

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Oqvn -m SNMPv2-MIB -M /opt/librenms/mibs udp:172.16.114.4:161 sysObjectID.0
.1.3.6.1.4.1.41112.1.5

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -OUqv -m SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs udp:172.16.114.4:161 snmpEngineTime.0
8153618

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Oqv -m HOST-RESOURCES-MIB -M /opt/librenms/mibs udp:172.16.114.4:161 hrSystemUptime.0
94:8:54:50.85

Using hrSystemUptime (94:8:54:50.85)
[RRD Disabled]RRD[update /opt/librenms/rrd/172.16.114.4/uptime.rrd N:8153690] Uptime: 94 days, 8h 54m 50s

Hardware:  Version: v1.7.0rc2.4781606.150616.1222 Features:  Serial: 
[RRD Disabled]RRD[update /opt/librenms/rrd/172.16.114.4/poller-perf.rrd N:0.665] [RRD Disabled]RRD[update /opt/librenms/rrd/172.16.114.4/ping-perf.rrd N:2.21] Polled in 0.665 seconds
Updating 172.16.114.4
Array
(
    [uptime] => 8153690
    [last_polled] => Array
        (
            [0] => NOW()
        )

    [last_polled_timetaken] => 0.665
    [last_ping] => Array
        (
            [0] => NOW()
        )

    [last_ping_timetaken] => 2.21
)

SQL[UPDATE `devices` set `uptime` ='8153690',`last_polled` =NOW(),`last_polled_timetaken` ='0.665',`last_ping` =NOW(),`last_ping_timetaken` ='2.21' WHERE `device_id` = '7'] UPDATED!

SQL[SELECT * FROM device_groups ORDER BY name] 
SQL[SELECT DISTINCT(alert_schedule.schedule_id) FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '7' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1] 
SQL[SELECT * FROM device_groups ORDER BY name] 
SQL[SELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '7' ) || alert_map.target = '7'  )]  #1:
SQL[SELECT state FROM alerts WHERE rule_id = '1' && device_id = '7' ORDER BY id DESC LIMIT 1] 
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'devices' && COLUMN_NAME = 'device_id'] 
SQL[SELECT * FROM devices WHERE (devices.device_id = '7') && ( (  ( devices.status = 0  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  )  )  = "1")]  NOCHG  #2:
SQL[SELECT state FROM alerts WHERE rule_id = '2' && device_id = '7' ORDER BY id DESC LIMIT 1] 
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'devices' && COLUMN_NAME = 'device_id'] 
SQL[SELECT * FROM devices WHERE (devices.device_id = '7') && (devices.uptime < "300"  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  = "1")]  NOCHG  #3:
SQL[SELECT state FROM alerts WHERE rule_id = '3' && device_id = '7' ORDER BY id DESC LIMIT 1] 
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'bgpPeers' && COLUMN_NAME = 'device_id'] 
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'devices' && COLUMN_NAME = 'device_id'] 
SQL[SELECT * FROM bgpPeers,devices WHERE (bgpPeers.device_id = devices.device_id && bgpPeers.device_id = '7') && (bgpPeers.bgpPeerState != "established"  &&   (  ( devices.status = 1  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  )  )  = "1")]  NOCHG  #4:
SQL[SELECT state FROM alerts WHERE rule_id = '4' && device_id = '7' ORDER BY id DESC LIMIT 1] 
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'bgpPeers' && COLUMN_NAME = 'device_id'] 
SQL[SELECT * FROM bgpPeers WHERE (bgpPeers.device_id = '7') && (bgpPeers.bgpPeerFsmEstablishedTime < "300"  &&  bgpPeers.bgpPeerState = "established")]  NOCHG  #5:
SQL[SELECT state FROM alerts WHERE rule_id = '5' && device_id = '7' ORDER BY id DESC LIMIT 1] 
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'ports' && COLUMN_NAME = 'device_id'] 
SQL[SELECT * FROM ports WHERE (ports.device_id = '7') && ( (  ( ports.ifOperStatus = "down"  &&  ports.ifAdminStatus != "down"  &&   (  ( ports.deleted = 0  &&  ports.ignore = 0  &&  ports.disabled = 0 )  )  )  )  = "1")]  NOCHG  #6:
SQL[SELECT state FROM alerts WHERE rule_id = '6' && device_id = '7' ORDER BY id DESC LIMIT 1] 
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'ports' && COLUMN_NAME = 'device_id'] 
SQL[SELECT * FROM ports WHERE (ports.device_id = '7') && ( (  (  ( ports.ifInOctets_rate * 8 )  / ports.ifSpeed )  * 100 )  >= "80")]  NOCHG  #7:
SQL[SELECT state FROM alerts WHERE rule_id = '7' && device_id = '7' ORDER BY id DESC LIMIT 1] 
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'sensors' && COLUMN_NAME = 'device_id'] 
SQL[SELECT * FROM sensors WHERE (sensors.device_id = '7') && (sensors.sensor_current > sensors.sensor_limit)]  NOCHG  #8:
SQL[SELECT state FROM alerts WHERE rule_id = '8' && device_id = '7' ORDER BY id DESC LIMIT 1] 
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'sensors' && COLUMN_NAME = 'device_id'] 
SQL[SELECT * FROM sensors WHERE (sensors.device_id = '7') && (sensors.sensor_current < sensors.sensor_limit_low)]  NOCHG 

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','172.16.114.4','1443526753.5737','0.768','1','public\n')] ./poller.php 172.16.114.4 2015-09-29 13:39:14 - 1 devices polled in 0.768 secs

MySQL: Cell[1/0s] Row[19/0.02s] Rows[10/0.03s] Column[0/0s] Update[1/0.02s] Insert[2/0.03s] Delete[0/0s]

**Comment by paszczus** [comment]
Ok, it`s already reported to Ubiquiti here: 
http://community.ubnt.com/t5/EdgeMAX/Please-add-model-number-to-SNMP-mibs/m-p/1362493#U1362493

and here: 
https://community.ubnt.com/t5/EdgeMAX/Feature-request-Minor-improvement-to-SNMP-for-NMS-monitoring/m-p/1261094

**Comment by Rosiak** [comment]
Suppose we close this issue.

**Comment by paszczus** [comment]
For now yes. Ubiquiti has replied "Yeah this is on our TODO list and we'll need to see when we can get to it. Thanks for the feedback."
