### ISSUE TITLE
RRD failed with status -1

### ISSUE THREAD

**Issue by justnx** [librenms/librenms#2021]
Some of my mysql App checks seems broken after running some time, rrdcache throwing following error messages:
```text
Sep 29 14:20:24 monitoring rrdcached[8054]: queue_thread_main: rrd_update_r (/opt/librenms/rrd/mail-01/app-mysql-10.rrd) failed with status -1. (/opt/librenms/rrd/mail-01/app-mysql-10.rrd: found extra data on update argument: -1:1:0:0:0:1369011:0:317428413:664663776:122:1549:0:0:0:0:1016306:2219:0)
Sep 29 14:20:24 monitoring rrdcached[8054]: queue_thread_main: rrd_update_r (/opt/librenms/rrd/mail-02/app-mysql-13.rrd) failed with status -1. (/opt/librenms/rrd/mail-02/app-mysql-13.rrd: found extra data on update argument: -1:0:0:0:0:1368825:0:310433475:649005071:25:1549:0:0:0:0:987602:2166:0)
Sep 29 14:20:26 monitoring rrdcached[8054]: queue_thread_main: rrd_update_r (/opt/librenms/rrd/localhost/app-mysql-31.rrd) failed with status -1. (/opt/librenms/rrd/localhost/app-mysql-31.rrd: found extra data on update argument: -1:21:0:52:0:251:0:3892103:3831477:195:2979:0:0:0:0:3171:3007:0)
```

Example output of xinetd service:
```text
<<<app-memcached>>>
a:1:{s:15:"localhost:11211";a:24:{s:3:"pid";i:2594;s:6:"uptime";i:1038220;s:7:"threads";i:4;s:4:"time";i:1443530021;s:12:"pointer_size";i:64;s:19:"rusage_user_seconds";i:32;s:24:"rusage_user_microseconds";i:828000;s:21:"rusage_system_seconds";i:27;s:26:"rusage_system_microseconds";i:220000;s:10:"curr_items";i:3;s:11:"total_items";i:1376;s:14:"limit_maxbytes";i:134217728;s:16:"curr_connections";i:7;s:17:"total_connections";i:3939;s:21:"connection_structures";i:9;s:5:"bytes";i:365;s:7:"cmd_get";i:458;s:7:"cmd_set";i:1376;s:8:"get_hits";i:0;s:10:"get_misses";i:458;s:9:"evictions";i:0;s:10:"bytes_read";i:193368;s:13:"bytes_written";i:7347119;s:7:"version";s:6:"1.4.13";}}
<<<mysql>>>
a0:0
a1:0
a2:0
a3:0
a4:-1
a5:-1
a6:-1
a7:-1
a8:-1
a9:-1
aa:-1
ab:-1
ac:-1
ad:-1
ae:-1
af:-1
ag:-1
ah:-1
ai:-1
aj:-1
ak:-1
al:-1
am:-1
an:-1
ao:-1
ap:-1
aq:-1
ar:-1
as:-1
at:-1
au:-1
av:-1
aw:-1
ax:-1
ay:-1
az:-1
b0:-1
b1:-1
b2:-1
b3:-1
b4:0
b5:10950
b6:0
b7:62
b8:192
b9:129
ba:400
bb:1265
bc:400
bd:694
be:0
bf:33
bg:0
bh:0
bi:2
bj:1929
bk:2
bl:250
bm:128
bn:1087521
bo:0
bp:0
bq:0
br:0
bs:0
bt:25
bu:33139664
bv:26562
bw:2062
bx:0
by:985683
bz:227
c0:502
c1:33554432
c2:3749124
c3:2219
c4:1549
c5:1017091
c6:122
c7:0
c8:0
c9:0
ca:0
cb:0
cc:0
cd:1
ce:0
cf:0
cg:0
ch:1370091
ci:0
cj:0
ck:0
cl:227
cm:1369208
cn:11721
co:6
cp:665154378
cq:317673254
cr:8388608
cs:-1
ct:-1
cu:-1
cv:1010
cw:32768
cx:0
cy:3160
cz:549845
d0:-1
d1:-1
d2:-1
d3:-1
d4:-1
d5:-1
d6:1
d7:-1
d8:-1
d9:-1
da:-1
db:-1
dc:-1
dd:-1
de:-1
df:-1
dg:-1
dh:-1
di:17433
dj:3518
dk:0
dl:10604
dm:277
dn:7438
do:401
dp:0
dq:70
dr:7375713
ds:0
dt:0
du:0
dv:2208
dw:4700
dx:-1
dy:-1
dz:-1
e0:-1
e1:-1
e2:-1
e3:-1
e4:-1
e5:-1
e6:-1
e7:-1
e8:-1
e9:-1
ea:-1
eb:-1
ec:-1
ed:-1
ee:-1
ef:-1
eg:0
eh:12244992
ei:67108864
ej:14
ek:13
<<<nginx>>>

1
0
1
0
14138
```

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

To me that looks like an issue within rrdcached rather than LibreNMS.

Perhaps filesystem caused?

- - f0o


On September 29, 2015 2:26:24 PM GMT+02:00, Julian Sternberg <notifications@github.com> wrote:
>Some of my mysql App checks seems broken after running some time,
>rrdcache throwing following error messages:
>Sep 29 14:20:24 monitoring rrdcached[8054]: queue_thread_main:
>rrd_update_r (/opt/librenms/rrd/mail-01/app-mysql-10.rrd) failed with
>status -1. (/opt/librenms/rrd/mail-01/app-mysql-10.rrd: found extra
>data on update argument:
>-1:1:0:0:0:1369011:0:317428413:664663776:122:1549:0:0:0:0:1016306:2219:0)
>Sep 29 14:20:24 monitoring rrdcached[8054]: queue_thread_main:
>rrd_update_r (/opt/librenms/rrd/mail-02/app-mysql-13.rrd) failed with
>status -1. (/opt/librenms/rrd/mail-02/app-mysql-13.rrd: found extra
>data on update argument:
>-1:0:0:0:0:1368825:0:310433475:649005071:25:1549:0:0:0:0:987602:2166:0)
>Sep 29 14:20:26 monitoring rrdcached[8054]: queue_thread_main:
>rrd_update_r (/opt/librenms/rrd/localhost/app-mysql-31.rrd) failed with
>status -1. (/opt/librenms/rrd/localhost/app-mysql-31.rrd: found extra
>data on update argument:
>-1:21:0:52:0:251:0:3892103:3831477:195:2979:0:0:0:0:3171:3007:0)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2021
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJPBAEBCgA5BQJWCoXIMhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikg
PGYwb0BsaWJyZW5tcy5vcmc+AAoJEJMZKtVWOFzBnfMP+wb5HWqDYLNR/ViFjq+L
47jsPP63HlIOd0cWlmbBFvojhL/K62X2gskQGxoEet8vjY3TyhmmzqhzmJrDIm/J
KODS2iUIKy9NQGjozcPmLcU1VpdykoH7tp9XHYvqjOi23gIdXXNAc0UV8NcqEMl6
yykdx+NQMvEL5BwVPiozHWmuCGdNlpuo/xQUZTGxCj+9tVKPMyWqgE0Gs4vw1lZi
g+H2EqGnqfU++T1wQICs7et+GPdtNoVpg5TpvL9hDMLQYBr12F6I9yyt4rPJ3WKK
z6LsIOpt1klrrmuPDjwTNzMp+rHfMLSU0fdz59CqCpQ8u2MuOxQYn44B4xifAqAJ
Oajh8HEgqIiCDGVwcGTZXHZ/he5N0gTu50lAKCNxDh+D7wOjVWMzar9jle+26vRq
yHVrv+HVKlGRO/twShnRI0Lp6/cK173KOjYIqbuNnfqPVnwnNM7Fayggd5jdonJj
H8ahf2+KijeBKCsSifC6Hoki7e7W0WUunVXMCxM4Pa/JYysceKnaDp/c9Ok+bPQM
BFyigD7U2Lkw+0fs2t/hRUtK9gWtnomVX37x003qiQ1H6kTCahmeiW+vcflpqzDX
0ITDr5ktX0VaDsFp3qGBatPKtdJTzvw9tLFzC62maBjfo1h9h58oBECsmv6Wr/Nw
0qZon451la5BaKtecWVJzeWv
=1kZD
-----END PGP SIGNATURE-----

**Comment by justnx** [comment]
since the update arguments are less than the output of xinetd i assume its the poller processing task.

**Comment by f0o** [comment]
@justnx what's your current version? (`git log -n 1` + DB Schema taken from the /about/ page`)

**Comment by justnx** [comment]
commit 98a93690a730f475bd49a035d9b12ffe0a417ead
Merge: b7d297e 75119b1

DB-Version: 98a9369

**Comment by justnx** [comment]
It's just broken since a few days btw. a week ago it worked just fine

**Comment by laf** [comment]
@justnx 

Sorry for the delay, can you try these two mysql polling files in turn, see which one resolves the issue:

https://raw.githubusercontent.com/librenms/librenms/987634e4639d40390ca3399a3e414800b23d7d68/includes/polling/applications/mysql.inc.php


https://raw.githubusercontent.com/librenms/librenms/b273e04241b1fd79d979afcce953fdc7c0cad87e/includes/polling/applications/mysql.inc.php

Report back if either fixes the issue.

**Comment by fr33tux** [comment]
I got the same problem since the automatic update between the 22 and 23th of September.
My installation is running on Ubuntu 14.04, rrdtool 1.4.7. Other data retrieved from the agent works fine.

Above mysql.inc.php files doesn't fix the problem : 
- the first one does nothing different,
- the second one shows a grey part : https://up2sha.re/file?l=rZFZMWeltfgA.png

**Comment by paszczus** [comment]
Same problem here. I am able to get values from rpm and apache, but cannot from temperature and mysql. telneting on 6556 returns everything, but in libreNMS i have graphs with no data

**Comment by f0o** [comment]
I'm still puzzled, on the demo (being on upstream code) has no issues at all...
MySQL app keeps graphing ever since it got added a long while ago

Could you all post your OS+rrdtool version (preferably including the exact package).

I'll spin some VMs up with your OS's and let it run for a while

**Comment by paszczus** [comment]
I am running Debian 8.2 with rrd{cached,tool} 1.4.8-1.2

**Comment by jazzysmooth** [comment]
I no longer have graphs for the local host nor remote.  
Local is ubuntu 14.04.3, rrdtool version 1.4.7

**Comment by samyscoub** [comment]
Same problem with remote mysql host : 

`/opt/librenms/rrd/librenms/app-mysql-20.rrd: found extra data on update argument`

Have you found the problem ?

**Comment by samyscoub** [comment]
You have to unset the `$fields` variable because there is values from other plugins inside and the count of elements inside the array is greater than the number of fields expected by rrdtool_update

$values = array();
+ unset($fields);
foreach ($mapping as $k => $v) {
    $fields[$k] = isset($map[$v]) ? $map[$v] : (-1);
}
