### ISSUE TITLE
Enhancement: Allign dashboard menu && widgets

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#2047]
![screen shot 2015-10-02 at 21 41 08](https://cloud.githubusercontent.com/assets/6378934/10256015/6dc8fee0-694e-11e5-8839-2172b2164912.png)

For some reason this hurt's my eyes.

**Comment by f0o** [comment]
Actually that was intended :D

**Comment by Rosiak** [comment]
lol, oh well.

**Comment by SaaldjorMike** [comment]
While where at it, also alignment of the column-picker in the "Alerts" widget seems to be centered: https://i.imgur.com/V9rsbvx.png

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On the widgets, i think we should remove the center tag

On October 6, 2015 10:13:13 PM GMT+02:00, Mike Rostermund <notifications@github.com> wrote:
>While where at it, also alignment of the column-picker in the "Alerts"
>widget seems to be centered: https://i.imgur.com/V9rsbvx.png
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2047#issuecomment-145984746
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJPBAEBCgA5BQJWFL1nMhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikg
PGYwb0BsaWJyZW5tcy5vcmc+AAoJEJMZKtVWOFzBCTUQAJJPLpZT4U9UYrJWdo2F
uTPwsLXWG208Ya3guveGUx9yC5Uv76qYImmy5A4anbiS7Pnl6Zl+SNOXU2aajbC6
fxBzCawe5lmEAGQfREKygfddEE9IjeVYhCD1Por84qtAPYsI+3+iAjGN3WKJr+o+
EJxUQlN1M08ZdsK+H/B9dFEa5/VFdgelO+O8BS0YZ4DF94RaBCpmDc8TETqBXQ7R
2gIKplKgNcwyEjhnlM01l6WI0ie52JGoOgvAUs/lltyq8/pI748jIfdH3tOovevF
cljCyIoQ7HYMNoWythMwmLEZVbgWF+BF6ELxVKCjaniN7fJqU6AknzqE6+G/l9FQ
XkwywXBG20QUlG9gjePCqnzAGM0TW+LpIwtkoDdVEhtIYnioRLWtfLKQf5x8Ti+N
gpQ2Q8km/ObqeeLIw1Q8KYzUcWUp3utEkNOZhWWR1ycT0Zk27fGpd5XvebMeRvcy
LBoeJxbROtKW3KXiir9InbQqHGaTpnRuXIwrCaugPT8Pmg5MxAN4EmGucf8F0xce
QsW4YIJnHckD3gcFIRrlB3Q8kMcshlAaQGsn2NsgQR6cQaBAhid88UfiJqdLh/Zq
DConbVKBAfPOVPDyczdR6JgT8c//bnZ46uubs3+v0B/kMIO5GsDj+QqnWKHfw9Py
qpn5zv8eb+zafDDs1MfFLfd5
=J0nJ
-----END PGP SIGNATURE-----

**Comment by Rosiak** [comment]
Closing since this alignment is intended.
