### ISSUE TITLE
HipChat alerting

### ISSUE THREAD

**Issue by masonke** [librenms/librenms#2050]
Questions on how to get hipchat to work as an alerting service. 
1) The docs say to use the gui, which is fine, but what hipchat supplies and librenms wants are not clear. 
2) In the CLI example, there are options such as text, how is that set in the gui?

For the room 'librenms', hipchat supplies me with this api url. Using the curl test, it works. 
https://api.hipchat.com/v2/room/7654321/notification?auth_token=a1b2c3d4e5f6g7
The user is Librenms, which should be pretty straight forward.

I have tried 
Putting the entire string in the "Hipchat API URL" field and the name librenms in the "Room ID", did not work. 
Putting the entire string in the "Hipchat API URL" field and the name 7654321 in the "Room ID", did not work. 
Changed the v2 in the string to v1 for both cases, no difference.
Tried using the example CLI configs, swapping in my values, no workie.
Any ideas?

For the options, what is the syntax to say text and red? 

Thanks

**Comment by f0o** [comment]
We use the APIv1 of HipChat as by the time of writing the transport their v2 was still beta.
https://www.hipchat.com/docs/api/method/rooms/message

This means you need a v1 API-Token as well.

**Comment by masonke** [comment]
Any idea how to request a v1 token then? As far as I can see, the site only gives v2 tokens.
~KEM

**Comment by f0o** [comment]
From HipChat's API Access page:
```text
Note: These access tokens can only be used with the beta API version 2. If you want to use API version 1, which is what most integrations today will expect, you'll need to get an API token from your group administrator.
```

**Comment by masonke** [comment]
Thank you, 

I just found that as this email arrived. It was nicely buried in the docs.


~KEM
