### ISSUE TITLE
Feature Request: Leverage various tools from the RIPE API

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#2051]
- Whois
- Abuse Finder
- Geolocate
- Looking Glass
etc.

https://stat.ripe.net/docs/data_api

**Comment by Rosiak** [comment]
Quick example, thoughts?:

![screen shot 2015-10-03 at 00 33 35](https://cloud.githubusercontent.com/assets/6378934/10259311/0773475e-6967-11e5-826e-bc2e4a60dd37.png)

**Comment by f0o** [comment]
:+1:

**Comment by laf** [comment]
:+1:
