### ISSUE TITLE
Device availability in percentage based on variable metrics (uptime, ping avg, poller avg, ...)

### ISSUE THREAD

**Issue by chrisgfx** [librenms/librenms#2063]
Hi,

Do you know if it is possible to retrieve an availability percentage for devices, based on ping, uptime or something else within the LibreNMS Poller ?
I could be interesting to have that information in numbers and not only in color like it is in the availabily widget. :smiley:

**Comment by f0o** [comment]
doesnt the availability widget show you the numbers of down-hosts as well?

**Comment by chrisgfx** [comment]
yes, but my idea is more a percentage within an interval of time to see for exemple if the device is available for 99.9% as expected.
So I was wondering if we could use the graph uptime or ping success to aggregate and compute this percentage number.

**Comment by f0o** [comment]
:+1:

**Comment by chrisgfx** [comment]
I think it will be possible with the Netstats ICMP Statistics with the ratio between IN and OUT ICMP messages.

Need to check the differents values of the graphs to see wich one is the most acurate.

**Comment by laf** [comment]
Can you not use the data in device_perf table that generates the performance data for each device?

**Comment by chrisgfx** [comment]
Great. It's exactly what I need! Thank you for the advice.

I will update with the new functionnality soon. :wink:
