### ISSUE TITLE
Traffic Bills calculating wrong.

### ISSUE THREAD

**Issue by Mattz0r** [librenms/librenms#2066]
Hello,

It appears for some reason my bills are generating the wrong values for the traffic used within a period.

![cvelwky](https://cloud.githubusercontent.com/assets/2264823/10341237/d622baf6-6d0b-11e5-8085-62a06eb5f65e.png)

As you can see, the graph barely goes above 5Mbps, let alone 57Mbps.

Not quite sure how this is calculated, but I also have another example here:

![bii1f5x](https://cloud.githubusercontent.com/assets/2264823/10341381/5aba3fdc-6d0c-11e5-91db-262f2b98b80c.png)

If you need any further info, please let me know!

Cheers,

Matt

**Comment by Mattz0r** [comment]
Let me try to describe this in a bit more detail.

Take the first image:

This graph shows that the traffic spikes to an average of 5Mbps per day.

The monthly graph, shows that the average speed is 56Mbps, with a total downloaded of 8.2TB

![xkwawh9](https://cloud.githubusercontent.com/assets/2264823/10350965/f1fd4e48-6d3e-11e5-87fd-a7fb2ef01c3b.png)

In order to download 8.2TB, it would take about 160 days at a constant non stop 5Mbps. Which this graph doesn't indicate, nor does it span that far.

I hope this helps.

Matt

**Comment by Justmeccsn** [comment]
I am seeing the same issue. 

Bandwidth graph (which the switchport monitor shows as being correct)
![graph 1](https://cloud.githubusercontent.com/assets/15629409/10906955/c6f0eaa4-821d-11e5-8357-df46d38a4bed.png)

Billing Graph shows the 95th at 280mbps after spiking to almost 1gbps:
![billing-graph](https://cloud.githubusercontent.com/assets/15629409/10906993/2acb9150-821e-11e5-8522-a8645a061148.png)

Bill Summary
CDR / 95th Bill

2015-11-01 to 2015-11-30 
Measured 280Mbps of 100Mbps (280.17%) @ 95th %ile

I traced the port id and the measurements in are correct:

MariaDB [librenms]> select * from  bill_ports where bill_id = '41';
+---------+---------+---------------------+
| bill_id | port_id | bill_port_autoadded |
+---------+---------+---------------------+
|      41 |    1231 |                   0 |
|      41 |    1280 |                   0 |
+---------+---------+---------------------+
2 rows in set (0.00 sec)

Measurements:

|    1231 | 2015-09-01 10:35:14 | 86987639015 | 1837326 |
|    1231 | 2015-09-01 10:40:14 | 86989528435 | 1889420 |
|    1231 | 2015-09-01 10:45:17 | 86991427290 | 1898855 |
|    1231 | 2015-09-01 10:50:18 | 86993290856 | 1863566 |
|    1231 | 2015-09-01 10:55:17 | 86995125163 | 1834307 |
|    1231 | 2015-09-01 11:05:18 | 86999039245 | 3914082 |
|    1231 | 2015-09-01 11:10:18 | 87000883866 | 1844621 |
|    1231 | 2015-09-01 11:15:13 | 87002796871 | 1913005 |
|    1231 | 2015-09-01 11:20:15 | 87004758380 | 1961509 |
|    1231 | 2015-09-01 11:25:12 | 87006549068 | 1790688 |
|    1231 | 2015-09-01 11:30:14 | 87008392013 | 1842945 |

Same for the ports out:

|    1231 | 2015-10-23 05:40:33 | 1283072243786 |      41458 |
|    1231 | 2015-10-23 05:45:32 | 1283072279106 |      35320 |
|    1231 | 2015-10-23 05:50:33 | 1283072361509 |      82403 |
|    1231 | 2015-10-23 05:55:34 | 1283072415767 |      54258 |
|    1231 | 2015-10-23 06:00:36 | 1283072478676 |      62909 |
|    1231 | 2015-10-23 06:05:31 | 1283072517930 |      39254 |
|    1231 | 2015-10-23 06:10:32 | 1283072560608 |      42678 |
|    1231 | 2015-10-23 06:15:31 | 1283072605013 |      44405 |
|    1231 | 2015-10-23 06:20:33 | 1283072643963 |      38950 |
|    1231 | 2015-10-23 06:25:32 | 1283072772893 |     128930 |
|    1231 | 2015-10-23 06:30:33 | 1283072811082 |      38189 |
|    1231 | 2015-10-23 06:35:34 | 1283072867532 |      56450 |
|    1231 | 2015-10-23 06:40:32 | 1283072908826 |      41294 |
|    1231 | 2015-10-23 06:45:33 | 1283072951807 |      42981 |
|    1231 | 2015-10-23 06:50:33 | 1283073000386 |      48579 |

The PORTS table records the correct information as well:

MariaDB [librenms]> select * from ports where port_id = '1231';
+---------+-----------+-----------------+-------------------+--------------------+------------------+------------------+-----------+-----------+----------+---------+------------+--------------------+-------------------+-------------+--------------+---------------+------------+-------+--------+-------------------------+---------------+------------+---------------------+--------+---------+-------+------------+-------------+--------+----------+----------+---------+-------------------+---------------+---------------------+------------------------+--------------------+-------------------------+-----------------------+-----------------------+--------------+------------------+---------------+--------------------+---------------------+--------------------+----------------+---------------------+----------------------+---------------------+------------+-----------------+------------------+-----------------+-------------+------------------+-------------------+------------------+--------------+-----------------+------------------+-----------------+---------------+------------------+-------------------+------------------+------------+------------+-------------+
| port_id | device_id | port_descr_type | port_descr_descr  | port_descr_circuit | port_descr_speed | port_descr_notes | ifDescr   | ifName    | portName | ifIndex | ifSpeed    | ifConnectorPresent | ifPromiscuousMode | ifHighSpeed | ifOperStatus | ifAdminStatus | ifDuplex   | ifMtu | ifType | ifAlias                 | ifPhysAddress | ifHardType | ifLastChange        | ifVlan | ifTrunk | ifVrf | counter_in | counter_out | ignore | disabled | detailed | deleted | pagpOperationMode | pagpPortState | pagpPartnerDeviceId | pagpPartnerLearnMethod | pagpPartnerIfIndex | pagpPartnerGroupIfIndex | pagpPartnerDeviceName | pagpEthcOperationMode | pagpDeviceId | pagpGroupIfIndex | ifInUcastPkts | ifInUcastPkts_prev | ifInUcastPkts_delta | ifInUcastPkts_rate | ifOutUcastPkts | ifOutUcastPkts_prev | ifOutUcastPkts_delta | ifOutUcastPkts_rate | ifInErrors | ifInErrors_prev | ifInErrors_delta | ifInErrors_rate | ifOutErrors | ifOutErrors_prev | ifOutErrors_delta | ifOutErrors_rate | ifInOctets   | ifInOctets_prev | ifInOctets_delta | ifInOctets_rate | ifOutOctets   | ifOutOctets_prev | ifOutOctets_delta | ifOutOctets_rate | poll_time  | poll_prev  | poll_period |
+---------+-----------+-----------------+-------------------+--------------------+------------------+------------------+-----------+-----------+----------+---------+------------+--------------------+-------------------+-------------+--------------+---------------+------------+-------+--------+-------------------------+---------------+------------+---------------------+--------+---------+-------+------------+-------------+--------+----------+----------+---------+-------------------+---------------+---------------------+------------------------+--------------------+-------------------------+-----------------------+-----------------------+--------------+------------------+---------------+--------------------+---------------------+--------------------+----------------+---------------------+----------------------+---------------------+------------+-----------------+------------------+-----------------+-------------+------------------+-------------------+------------------+--------------+-----------------+------------------+-----------------+---------------+------------------+-------------------+------------------+------------+------------+-------------+
|    1231 |        20 | cust            | CUST | NULL               | NULL             | NULL             | ge-0/0/14 | ge-0/0/14 | NULL     |     530 | 1000000000 | NULL               | NULL              |        1000 | up           | up            | fullDuplex |  NULL | NULL   | Cust:  | NULL          | NULL       | 2015-11-03 10:40:23 | 267    |         |     0 |       NULL |        NULL |      0 |        0 |        0 |       0 | NULL              | NULL          | NULL                | NULL                   |               NULL |                    NULL | NULL                  | NULL                  | NULL         |             NULL |          NULL |               NULL |                NULL |               NULL |           NULL |                NULL |                 NULL |                NULL |          0 |               0 |                0 |               0 |           0 |                0 |                 0 |                0 | 359288711470 |    359286397350 |          2314120 |            7688 | 1294635222542 |    1294635115934 |            106608 |              354 | 1446547223 | 1446546922 |         301 |
+---------+-----------+-----------------+-------------------+--------------------+------------------+------------------+-----------+-----------+----------+---------+------------+--------------------+-------------------+-------------+--------------+---------------+------------+-------+--------+-------------------------+---------------+------------+---------------------+--------+---------+-------+------------+-------------+--------+----------+----------+---------+-------------------+---------------+---------------------+------------------------+--------------------+-------------------------+-----------------------+-----------------------+--------------+------------------+---------------+--------------------+---------------------+--------------------+----------------+---------------------+----------------------+---------------------+------------+-----------------+------------------+-----------------+-------------+------------------+-------------------+------------------+--------------+-----------------+------------------+-----------------+---------------+------------------+-------------------+------------------+------------+------------+-------------+
1 row in set (0.00 sec)

I reset the data for the bill, and then looked again at the bill_data:

MariaDB [librenms]> select * from  bill_data where bill_id = '41';
+---------+---------------------+--------+------------+------------+-----------+
| bill_id | timestamp           | period | delta      | in_delta   | out_delta |
+---------+---------------------+--------+------------+------------+-----------+
|      41 | 2015-11-03 10:01:17 |      0 |          0 |          0 |         0 |
|      41 | 2015-11-03 10:01:56 |     39 |          0 |          0 |         0 |
|      41 | 2015-11-03 10:06:04 |    248 |          0 |          0 |         0 |
|      41 | 2015-11-03 10:11:07 |    303 |          0 |          0 |         0 |
|      41 | 2015-11-03 10:15:16 |    251 | 8791554817 | 8790363734 |   1191083 |
|      41 | 2015-11-03 10:16:29 |     75 | 8768974240 | 8768620767 |    353473 |
|      41 | 2015-11-03 10:21:06 |    279 | 8772861869 | 8770300896 |   2560973 |
|      41 | 2015-11-03 10:26:05 |    300 | 8770976819 | 8770455290 |    521529 |
|      41 | 2015-11-03 10:31:11 |    307 | 8776722478 | 8775988147 |    734331 |
|      41 | 2015-11-03 10:36:04 |    294 | 8770895056 | 8770399406 |    495650 |
+---------+---------------------+--------+------------+------------+-----------+

It is not recording the correct details, judging by the in_delta. 

Bill history shows the same issues with a large overuse recorded:

MariaDB [librenms]> select * from  bill_history where bill_id = '41';
+--------------+---------+---------------------+---------------------+---------------------+-----------+--------------+-----------+--------------+--------------+--------------+---------------+-----------+----------+--------------+-----------------+------------------+----------------+---------------+----------------+------+
| bill_hist_id | bill_id | updated             | bill_datefrom       | bill_dateto         | bill_type | bill_allowed | bill_used | bill_overuse | bill_percent | rate_95th_in | rate_95th_out | rate_95th | dir_95th | rate_average | rate_average_in | rate_average_out | traf_in        | traf_out      | traf_total     | pdf  |
+--------------+---------+---------------------+---------------------+---------------------+-----------+--------------+-----------+--------------+--------------+--------------+---------------+-----------+----------+--------------+-----------------+------------------+----------------+---------------+----------------+------+
|           48 |      41 | 2015-10-01 00:01:43 | 2015-09-01 00:00:00 | 2015-09-30 23:59:59 | CDR       |    100000000 |  13188748 |            0 |        13.19 |      1335015 |      13188748 |  13188748 | out      |      4303470 |               0 |                0 |   215186135746 | 1161948319682 |  1377134455428 | NULL |
|          137 |      41 | 2015-11-01 00:02:24 | 2015-10-01 00:00:00 | 2015-10-31 23:59:59 | CDR       |    100000000 | 235443295 |    135443295 |       235.44 |    235443295 |        582938 | 235443295 | in       |    131211481 |               0 |                0 | 44113137120561 |   40248028773 | 44153385149334 | NULL |
|          230 |      41 | 2015-11-03 10:18:19 | 2015-11-01 00:00:00 | 2015-11-30 23:59:59 | CDR       |    100000000 | 935319548 |    835319548 |       935.32 |    935319548 |         37963 | 935319548 | in       |    153367066 |               0 |                0 |    17558984501 |       1544556 |    17560529057 | NULL |
+--------------+---------+---------------------+---------------------+---------------------+-----------+--------------+-----------+--------------+--------------+--------------+---------------+-----------+----------+--------------+-----------------+------------------+----------------+---------------+----------------+------+
3 rows in set (0.00 sec)

Billing poller shows the correct data being polled and received from the switch:

Bill : ------
Array
(
    [0] => Array
        (
            [bill_id] => 41
            [port_id] => 1231
            [bill_port_autoadded] => 0
            [device_id] => 20
            [port_descr_type] => cust
            [port_descr_descr] =>-
            [port_descr_circuit] => 
            [port_descr_speed] => 
            [port_descr_notes] => 
            [ifDescr] => ge-0/0/14
            [ifName] => ge-0/0/14
            [portName] => 
            [ifIndex] => 530
            [ifSpeed] => 1000000000
            [ifConnectorPresent] => 
            [ifPromiscuousMode] => 
            [ifHighSpeed] => 1000
            [ifOperStatus] => up
            [ifAdminStatus] => up
            [ifDuplex] => fullDuplex
            [ifMtu] => 
            [ifType] => 
            [ifAlias] => Cust: -
            [ifPhysAddress] => 
            [ifHardType] => 
            [ifLastChange] => 2015-11-03 10:10:24
            [ifVlan] => 267
            [ifTrunk] => 
            [ifVrf] => 0
            [counter_in] => 
            [counter_out] => 
            [ignore] => 0
            [disabled] => 0
            [detailed] => 0
            [deleted] => 0
            [pagpOperationMode] => 
            [pagpPortState] => 
            [pagpPartnerDeviceId] => 
            [pagpPartnerLearnMethod] => 
            [pagpPartnerIfIndex] => 
            [pagpPartnerGroupIfIndex] => 
            [pagpPartnerDeviceName] => 
            [pagpEthcOperationMode] => 
            [pagpDeviceId] => 
            [pagpGroupIfIndex] => 
            [ifInUcastPkts] => 
            [ifInUcastPkts_prev] => 
            [ifInUcastPkts_delta] => 
            [ifInUcastPkts_rate] => 
            [ifOutUcastPkts] => 
            [ifOutUcastPkts_prev] => 
            [ifOutUcastPkts_delta] => 
            [ifOutUcastPkts_rate] => 
            [ifInErrors] => 0
            [ifInErrors_prev] => 0
            [ifInErrors_delta] => 0
            [ifInErrors_rate] => 0
            [ifOutErrors] => 0
            [ifOutErrors_prev] => 0
            [ifOutErrors_delta] => 0
            [ifOutErrors_rate] => 0
            [ifInOctets] => 359261227256
            [ifInOctets_prev] => 359253172178
            [ifInOctets_delta] => 8055078
            [ifInOctets_rate] => 26672
            [ifOutOctets] => 1294631733737
            [ifOutOctets_prev] => 1294631443934
            [ifOutOctets_delta] => 289803
            [ifOutOctets_rate] => 960
            [poll_time] => 1446545424
            [poll_prev] => 1446545122
            [poll_period] => 302
            [hostname] => --------
            [sysName] =>-------
            [community] =>-------
            [authlevel] => 
            [authname] => 
            [authpass] => 
            [authalgo] => 
            [cryptopass] => 
            [cryptoalgo] => 
            [snmpver] => v2c
            [port] => 161
            [transport] => udp
            [timeout] => 
            [retries] => 
            [bgpLocalAs] => 
            [sysObjectID] => .1.3.6.1.4.1.2636.1.1.1.2.31
            [sysDescr] => Juniper Networks
            [sysContact] => root@router.com
            [version] => 12.3R6.6
            [hardware] => Juniper EX4200
            [features] => 
            [location] => -------
            [os] => junos
            [status] => 1
            [status_reason] => 
            [uptime] => 10328018
            [agent_uptime] => 0
            [last_polled] => 2015-11-03 10:10:33
            [last_poll_attempted] => 
            [last_polled_timetaken] => 31.08
            [last_discovered_timetaken] => 32.95
            [last_discovered] => 2015-11-03 06:35:14
            [last_ping] => 2015-11-03 10:10:33
            [last_ping_timetaken] => 4.36
            [purpose] => 
            [type] => network
            [serial] => ------
            [icon] => 
            [poller_group] => 0
            [override_sysLocation] => 0
            [notes] => 
        )

Hope this helps diagnosing the issue.

**Comment by cdominte** [comment]
Quick update on this, it seems that the previous port that was reporting erroneous bill usage started to work fine half way through December, however the issue moved to another port:

![graph 2](https://cloud.githubusercontent.com/assets/3835669/12511717/66677bc6-c10b-11e5-8d47-2f8cb2f3faa4.png)

As you can see there is not bandwidth on the port, however the bill calculation is completely wrong. The port was disconnected in December but the current usage shows 148453.23% overusage

![image](https://cloud.githubusercontent.com/assets/3835669/12511776/d7fd3e4c-c10b-11e5-9360-f588bc1dd090.png)

**Comment by MHammett** [comment]
Me too?

95th% exceeds the maximum.

![librenms traffic bill](https://cloud.githubusercontent.com/assets/12503490/12646740/6af6001e-c597-11e5-8f9c-e5f724f708e7.PNG)

**Comment by f0o** [comment]
Odd haven't seen that on my installs yet, using billing all the time

**Comment by Mattz0r** [comment]
I must say, that since I've come back to looking at my NMS, I've not seen this issue - However, I don't know if it's still about....

**Comment by richardlawley** [comment]
Some of the issues mentioned here are fixed by #3123, this definitely includes the disconnected port issue mentioned by @cdominte.  @MHammett, your issue looks like it might be the same, since your screenshot indicates that one of your ports are down.  The bug that was fixed means that when a port is down, it constantly reports the same traffic rate.  You can check this by:
* Get the port_id of the down port (click the red interface name and look for /port=XXXX/ in the URL
* Run the following query in mysql: `select * from port_in_measurements where port_id = XXXX and timestamp between '2016-01-01' AND '2016-02-01'`.  Repeat for the port_out_measurements table.  If you can find consecutive rows where counter does not increment but delta is non-zero then it is the same problem.

If you could confirm whether this is the case, that would be good.

**Comment by laf** [comment]
Thanks @richardlawley. The fix makes total sense and with the improvements you've made to the indexes and queries things should be a whole heap better.

**Comment by laf** [comment]
Feel free to re-open.
