### ISSUE TITLE
Widget: Top worst latency devices (from smokeping)

### ISSUE THREAD

**Issue by paszczus** [librenms/librenms#2067]
It will be cool if there will be such a widget which will show which devices are having problems with latency.

**Comment by paulgear** [comment]
:+1:

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by paszczus** [comment]
Hello,
It will be cool to have this FR implemented.

**Comment by laf** [comment]
moved to https://community.librenms.org/t/feature-request-widget-top-worst-latency-devices-from-smokeping/733
