### ISSUE TITLE
Problems with Nexus5548 setting invalid states on interfaces

### ISSUE THREAD

**Issue by masonke** [librenms/librenms#2068]
In the event log, interfaces on the 5548 keep setting invalid states. 
If the interface is not connected (up/dn) then the state will show ifDuplex: unknown -> NULL. 
If the interface is connected and operating (up/up), it will show ifDuplex: fullDuplex -> NULL

Any ideas?
![nx_interface_states](https://cloud.githubusercontent.com/assets/1863778/10346300/8342b98a-6cfc-11e5-87d4-39c38b5661b2.png)

cisco Nexus5548 Chassis ("O2 32X10GE/Modular Universal Platform Supervisor")

**Comment by laf** [comment]
We will need an output from ./poller.php -h HOSTNAME -r -d -m ports to see what's going on here.

**Comment by masonke** [comment]
I will grab that tonight
~KEM

**Comment by masonke** [comment]
This slipped through the cracks, will do this tomorrow

**Comment by masonke** [comment]
My apologies, finally got this done and neutralized the data

**Comment by laf** [comment]
pastebin.com is fine.

**Comment by laf** [comment]
No further info provided. Closing.
