### ISSUE TITLE
Service Monitoring

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#207]
Hi!

I know there is working code based on nagios-plugins that handles checks for network services. Even Up/Down alerts work *per se*!

However, Observium sais they're dropping support/development of it...

How about LibreNMS? Will we revive Service-Monitoring?

**Comment by laf** [comment]
Is this something that can be closed down now @f0o or is it separate to the alerting system still.

**Comment by paulgear** [comment]
Didn't we integrate a newer version of check_mk into the agent a while back?

**Comment by f0o** [comment]
I'd like to keep it open as reminder to fix the entire nagios-plugins integration. It's a slow progress :S

**Comment by Lonecrowe** [comment]
So you actually want to allow for the nagios plugins to execute?

So are you talking about remotely accessible services such as DNS, FTP, HTTP, NFS, SSH, TELNET etc?  

Or are you talking about local windows and linux services etc?

**Comment by f0o** [comment]
> So are you talking about remotely accessible services such as DNS, FTP, HTTP, NFS, SSH, TELNET etc?
that :)

**Comment by Lonecrowe** [comment]
Yeah I'm 100% for that.  Not sure if you really need to create a graph for it though.  It'll add a lot of overhead by adding all these new services.  Maybe just for alerting? The response time and configurations for each service check would just include each something simple.  I don't think it needs to be as elaborate as Nagios but maybe 

# of times failed before alert
# timeout in seconds (or ms) before considered bad
# repeat alert if flapping? Meaning don't alert if status keeps going up and down Y / N 

Etc

**Comment by f0o** [comment]
@Lonecrowe 
actually everything you described already exists in current upstream.

This issue is to remind us that the way the services currently work is junk-ish and it needs an entire recode. And while at it, graph execution-times for the checks because why not ;)

**Comment by Lonecrowe** [comment]
I've not seen any service checks from server side in the program.  Is it something you have to config manually? Or are you talking about the modules that auto discover certain things?

**Comment by f0o** [comment]
In config:
`$config['show_services']           = 1;  # Enable Services on menu`

And add `check-services.php` to the cron (interval can same as poller)

**Comment by Lonecrowe** [comment]
Oh thanks I'll check it out.

**Comment by Lonecrowe** [comment]
This is very good and very handy.  Especially if you can view all your services in one list for example you look through all your SSH services or HTTP services.  This would be a huge undertaking to keep up with this though as its like trying to convert librenms into something as huge as Nagios.   I think its possible in a distributed model down the road but I wouldn't want to rely on nagios' plugins for it.  Probably better to start writing your own service type checks.

**Comment by paulgear** [comment]
@Lonecrowe I don't agree that we shouldn't rely on Nagios' plugins for service checks.  Many of them are quite good, and in general I think we should be aiming to integrate existing products rather than reinvent them.

**Comment by Lonecrowe** [comment]
The trend is for nagios to die ..  how long do you think the plugins will be supported down the road?  Well i guess you are right.  So many people use them right now and they work for the most part.  

I guess integrating them into this with a nice gui interface with the parameter options listed in a tooltip or something would help.  Need to make it as easy as possible for the end user to use them.

**Comment by paulgear** [comment]
A lot of people want Nagios to die, but not a lot of compelling alternatives have arisen.  By integrating their checks into LibreNMS, I think we've addressed one of its big shortcomings (the user interface).

**Comment by spinza** [comment]
I also use this and it's useful. Tells me quickly if key services are up. Often a service may have an issue but not the device per se.

**Comment by locobox** [comment]
I'm a little confused, all I'd like to do is monitor services (either a specific services, some, or all services on a windows host/server).  Is this possible with LibreNMS?

I have an instance of Nagios doing this already, but I'd really like to replace nagios with LibreNMS--the only thing holding me back is the monitoring of services for my 130 Windows servers.

**Comment by laf** [comment]
We support nagios service checks so in theory anything you can do with nagios you should be able to do with us. It's basic at present but does seem to work ok: http://docs.librenms.org/Extensions/Services/

I'd recommend you jumping on irc or creating another issue if you have issues as responses only show up to those who've subscribed here and check back.
