### ISSUE TITLE
macro usage in alert templates

### ISSUE THREAD

**Issue by Mattz0r** [librenms/librenms#2071]
Heyup,

Wondering if it would be somehow possible to include the use of %macros.custom from within the config.php within the alert templates?

This would help with the evolution of the alerting system, with html based emails and including graphs.

The outcome is that, I want to generate the unix time subtracting 6 hours, into the variable, for example:

$config['alert']['macros']['rule']['6hr'] = 'time() - 21600';

I could then use from=%macros.6hr within the graph image link, to generate a 6hr graph.

Hope this is enough information.

**Comment by laf** [comment]
@Mattz0r I'm still not sure that's going to do what you need as that's the same as just doing -6h in the graph url. You need to do a calculation really on the %value.poll_time, something like %value.poll_time - 21600 which I don't think is possible right now @f0o?

**Comment by Mattz0r** [comment]
Looks like we got around this by using from=end-6h

Can mark this one as closed for now then.
