### ISSUE TITLE
[API] Add the state filter on the alert list documentation

### ISSUE THREAD

**Issue by PandaWawawa** [librenms/librenms#2074]
Hi guys !
On the api alerts list, i can see a parameter to filter the state of fetched alerts
But it seems that there is no route on the api_v0 file to pass it

**Comment by laf** [comment]
Without checking the code is it not:

https://librenms.org/api/v0/alerts?state=1

**Comment by PandaWawawa** [comment]
Oh my bad, I thought it was a POST request but it's a GET...^^'
Maybe we can change the doc to show it on the example ? 
like : 
curl -H 'X-Auth-Token: YOURAPITOKENHERE' https://librenms.org/api/v0/alerts?state=1

**Comment by laf** [comment]
@PandaWawawa Pull requests accepted :)
