### ISSUE TITLE
Memory graphs not rendering

### ISSUE THREAD

**Issue by tgreer** [librenms/librenms#2077]
Systems are OpenBSD (5.2 and 5.5)

ucd_mem.rrd isn't being generated because of a lack of response (attribute @laf)

Attached:
Screenshot showing issu
Pastebin of &debug=true on the relevant graph.php
Pastebin of output of ./poller.php -h gw1.ixn.tsone.net.uk -d -r -m ucd-mib 

![screenshot](https://cloud.githubusercontent.com/assets/4996098/10368213/27784658-6dcc-11e5-9aef-6c923c08d725.PNG)

https://www.irccloud.com/pastebin/zzvNnSAO/

https://www.irccloud.com/pastebin/uQP2x0OO/

**Comment by f0o** [comment]
Doesnt seem like OpenBSD supports UCD-MIB from the ouput

```
/usr/bin/snmpget -v2c -c snmpcommunity -OQUs -m UCD-SNMP-MIB -M /opt/librenms/mibs udp:gw1.ixn.tsone.net.uk:161 memTotalSwap.0 memAvailSwap.0 memTotalReal.0 memAvailReal.0 memTotalFree.0 memShared.0 memBuffer.0 memCached.0
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: memTotalSwap.0

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: memAvailSwap.0

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: memTotalReal.0

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: memAvailReal.0

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: memTotalFree.0

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: memShared.0

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: memBuffer.0

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: memCached.0
```

**Comment by tgreer** [comment]
So, should this MIB be disabled for OpenBSD targets then?

**Comment by paulgear** [comment]
@tgreer Is this any different since we merged #2430?

**Comment by laf** [comment]
Closing due to no further feedback.

**Comment by pep-un** [comment]
Hello, 
I got the same problem with different version of OpenBSD : 
![capture d ecran de 2018-02-12 08-45-53](https://user-images.githubusercontent.com/8629097/36087171-3302044c-0fd1-11e8-8c8d-6be8fa98cff1.png)

Do you have a way to fix that or to disable the graph properly. 

You will find some debug in this pastbin : 

- PHP debug : https://zb.accelance.net/?374d988eeaee6b8f#2nk1L2OVpJkVwRY4gn1uw+mXDe54g3uRVQI8HyyCVfo=
- SQL debug : https://zb.accelance.net/?83aba167896313c3#om/eZJPi7PLiaWPayvRGPDdwaLMDTO9mFe8OxzzI4jU=
- Pooling debug : https://zb.accelance.net/?a4184a770595f2ba#/i27OEL/o28TdPcU+QeBlB84cks/aULri6wa6jfE/Og=

Best Regards,

**Comment by murrant** [comment]
Please don't comment on old closed issues.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
