### ISSUE TITLE
HTTPS detection

### ISSUE THREAD

**Issue by TNAJanssen** [librenms/librenms#2078]
Please use correct detection of SSL on https://github.com/librenms/librenms/blob/60c195fc79c19c4a089031332ee797e8941c9d9a/includes/definitions.inc.php#L1720

Like https://github.com/symfony/http-foundation/blob/master/Request.php#L1172

**Comment by f0o** [comment]
You should be using `$config['base_url'] = '//librenms.example.org/';` anyways

**Comment by laf** [comment]
I'd agree that base_url really should be used. We can use this in non-web facing areas of the code base then.

@TNAJanssen Was there a particular use case here?

**Comment by f0o** [comment]
Proposing closure or retagging as discussion

**Comment by TNAJanssen** [comment]
Sorry for the late reaction, i already used the base_url but that still uses the same code to check http and https.

As my server uses ($_SERVER['HTTPS'] = 'off') for not enabling ssl it replaces http with https.

So this issue should ben open

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

The detection wont alter the example I pasted above. That example works for both protocols as it is agnostic.



On October 23, 2015 10:49:21 AM GMT+02:00, Alexander Janssen <notifications@github.com> wrote:
>Sorry for the late reaction, i already used the base_url but that still
>uses the same code to check http and https.
>
>As my server uses ($_SERVER['HTTPS'] = 'off') for not enabling ssl it
>replaces http with https.
>
>So this issue should ben open
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2078#issuecomment-150516356
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5MhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikgPGYwb0Bs
aWJyZW5tcy5vcmc+BQJWKfTgAAoJEJMZKtVWOFzBfa4P/jHeicLg9kL8oY5jDrtU
5qQVJl7GEyxSo3bxrOeVky+vKvXZIKEvUoJLxNlMkumqvGQ+P3f5OBZ1LIqQgIHY
/HnNYymWYtttzHr1n2gSufueCEbAIoSByHnomTWAM4/+++8yLMhyl93cQteHWTRj
7s/fh9KdIrmbCAHIWEcLrIG6mhXb3+UnikWVklvnkB3UOL/Ik5r4rLLx18QJ5RBk
JH5sHqT5PQ4xBQlZo4EZT+AEXQIz/XdGGs3ROqf4aj8qrC+BqBLiyaZCwvRCmSiZ
gR/EVoj0o7nUbYv1BSyNwK5rU/WA5+MXIFOgBtbRcOlxTtFZK5IFUsseDiC31FWA
aucTkJIY28k9CKjFdPnCM6nC59JAek3/P5024iWOxtam47SF9ErmEiJ4wLIwBwjJ
MepcP4ikpFxw6SV5kQNlDd5+pgMQeM/63VgY/Cu8WEX0sEF/vlUOwVv6y0F1Tm4Y
ZtvLwuyNOT12JpqUEnUjPajZtbwYQHvOUY3DLhzSsD/b21e6umkItVB+/eI7k5l7
hdT7qw69PJ55BtWqqUGxyxd7bm4qKbOXe+jQai2MJI/1r38uhugzQ5juaf2Tthad
L57f4QHtoEaluMjMyZuJD5K1FfdNtVDM8XBwJ0b+1OElk407rYv8wf3Xm0nFuJaE
RsthYfG/xz9X12bF9wW5p4C2
=zepX
-----END PGP SIGNATURE-----

**Comment by laf** [comment]
@TNAJanssen I'm not quite sure what you mean by this. A couple of installs I've used with both http and https set in config have always worked fine. Are you seeing issues after setting base_url with certain links being generated?

**Comment by laf** [comment]
@TNAJanssen Feel free to reopen this issue, we need more information on the issue you are seeing though before continuing.
