### ISSUE TITLE
ARP Table not working

### ISSUE THREAD

**Issue by cyablo** [librenms/librenms#2080]
Hello,

I am evaluating some Network-Monitoring Software. Before LibreNMS I tried Observium.

I have a couple of HP ProCurve J9147A Switches and 2 Netgear Switches which worked absolutely fine with Observium. With LibreNMS the ARP Table for each single Port is not working. The Table is always empty. The Function Overview -> ARP Tables also only seems to show me the first Port of every monitored Device or something like that.

Greets

Daniel

**Comment by cyablo** [comment]
This is one of the HP Switches, there are definetly around half of the Ports in use with Clients.

![sha-switch1-2](https://cloud.githubusercontent.com/assets/3456720/10424119/a8b84396-70cc-11e5-89f6-fe230b28a3c1.PNG)

![sha-switch1](https://cloud.githubusercontent.com/assets/3456720/10424086/5e6e1c98-70cc-11e5-90fb-32901c65cbb8.png)

**Comment by f0o** [comment]
What does `/usr/bin/snmpbulkwalk -v2c -c __MYCOMMUNITY__ -Oq  -m IP-MIB -M /opt/librenms/mibs udp:__MYDEVICE__:161 ipNetToMediaPhysAddress` return?

**Comment by cyablo** [comment]
Here it is.

snmpbulkwalk -v2c -c public -Oq -m IP-MIB -M /opt/librenms/mibs udp:sha-switch1:161 ipNetToMediaPhysAddress

IP-MIB::ipNetToMediaPhysAddress.174.192.168.83.10 0:50:56:ad:bb:d6
IP-MIB::ipNetToMediaPhysAddress.174.192.168.83.61 0:50:56:ad:74:51
IP-MIB::ipNetToMediaPhysAddress.174.192.168.83.64 78:48:59:aa:65:11

snmpbulkwalk -v2c -c public -Oq -m IP-MIB -M /opt/librenms/mibs udp:sha-switch1:161 ipNetToPhysicalPhysAddress

IP-MIB::ipNetToPhysicalPhysAddress.174.ipv4."192.168.83.10" 0:50:56:ad:bb:d6
IP-MIB::ipNetToPhysicalPhysAddress.174.ipv4."192.168.83.61" 0:50:56:ad:74:51
IP-MIB::ipNetToPhysicalPhysAddress.174.ipv4."192.168.83.64" 78:48:59:aa:65:11

Ive just noticed that the Search-Feature in Observoium i used was using the FDB Data, so this is more related to this Issue: https://github.com/librenms/librenms/issues/1196

My HP Switch's FDB Table can be polled with:

snmpwalk -v 2c -c public sha-switch1 BRIDGE-MIB::dot1dTpFdbTable

Never realized where the Search-Data in Observium was coming from. Sorry for that!

**Comment by f0o** [comment]
Upstream issue is #1196

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/arp-table-empty/13339/1
