### ISSUE TITLE
Total graph peering + transit distinguishable colours

### ISSUE THREAD

**Issue by andrekeller** [librenms/librenms#2086]
Hi,

in the total graph for ports of type peering + transit, it would be nice to make peering traffic and transit traffic distinguishable by color. 

You could then integrate this overall "external" traffic graph into a dashboard and see whats going on on the first sight.

Any thoughts?

Regards

**Comment by paulgear** [comment]
:+1:

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by andrekeller** [comment]
Yes this is still an improvement we would like to see.

```
Version      6bc7b19 - Wed Feb 01 2017 00:05:35 GMT+0100
DB Schema    #157
```

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #197](https://github.com/librenms/librenmsv2/issues/197) via [**ZenHub**](https://www.zenhub.com/)
