### ISSUE TITLE
SMS Alerts for Librenms

### ISSUE THREAD

**Issue by starnetwork** [librenms/librenms#2089]
Hi,
I suggest to add some SMS Alerts using SMS gateways working via http get requests
My Recommendation:
1. https://www.clickatell.com
example: 
http://api.clickatell.com/http/sendmsg?api_id=xxxx&user=xxxx&password=xxxx&to=xxxx&text=xxxx
2. http://playsms.org
Example: 
http://playsms.org/index.php?app=ws&u=user&h=xxxx&op=pv&to=0505999333&msg=xxxx

regards,
StarNetwork

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Meanwhile adding this transport, you could already use it via the API transport.

Will read into clickatell's docs in the afternoon.

Cheers
F0o

On October 9, 2015 10:56:59 AM GMT+02:00, starnetwork <notifications@github.com> wrote:
>Hi,
>I suggest to add some SMS Alerts using SMS gateways working via http
>get requests
>My Recommendation:
>1. https://www.clickatell.com
>example:
>http://api.clickatell.com/http/sendmsg?api_id=xxxx&user=xxxx&password=xxxx&to=xxxx&text=xxxx
>2. http://playsms.org
>Example:
>http://playsms.org/index.php?app=ws&u=user&h=xxxx&op=pv&to=0505999333&msg=xxxx
>
>regards,
>StarNetwork
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2089

- --
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJPBAEBCgA5BQJWF4xaMhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikg
PGYwb0BsaWJyZW5tcy5vcmc+AAoJEJMZKtVWOFzBy7IP/3R9YF5BIaeDlX9XYWd8
Q94/zJPZJ7Aifihi2f3T9r8sXGoBVvOm4ZCmE67jqXdCIjcryGYOkwSbnh0ayGT3
3CFaeu2IiRc9qkglwKw8E+0mZxrflyX8vA+HKujYsQs4wRxjsdWkobzeKJS1v4qB
O3dNkpD6lJwD8eHZLUu/LGNAsMbMajwH/bWgEwbtRUE+nL2WkWqQUKZlL1I+mr+G
gQrhrmdWYDQhTObR52e9XH35uxf6f+nb3herMFpRr8LfDOQaPtrFvoja48bifRBk
BC/EkT1TYMuCe3nQNt8Brk/QjmgJC0Q2D6tnbUtkEvyWh/GYMpZEEoBRPCrZaJBY
91M9VBygWPiIffLEmnCsscit9k7KcJLZPFK+FoGXrxNiUr8YzCEkNojqAG/JzB8m
AsnQgyap4HQ2LpFZP2cDfxf2LEbzMIzYOzHE8JN4VCWhPl/LTdDngPyXX3OPye98
MP2nK+dEJ6z9dh9uV0ldOGKpMp1dn+rjdxzs6dShOXU4XZIHcaPsep9DInC7GxNC
/XxJ8/mIRYfxhsWoLS3xCMlG2Re7TNOXR+zxBNEfWqHi+75lcIdbl972qLLjg6gV
WzJy0YElICq/NEVcHuL/Xf21uZCq95iuKCjSpzDRjWSGe0myRftd+zOUKhKYOnKU
OTe63v+tfitv6qYPNoBp7Eb5
=U4eU
-----END PGP SIGNATURE-----

**Comment by starnetwork** [comment]
Thanks!
Clickatell: https://www.clickatell.com/downloads/http/Clickatell_HTTP.pdf
PlaySMS: https://github.com/antonraharja/playSMS/blob/master/documents/development/WEBSERVICES.md

**Comment by starnetwork** [comment]
thanks for your positive help, please check my comment at: https://github.com/librenms/librenms/pull/2104

**Comment by f0o** [comment]
Close as it's PR'd :)
