### ISSUE TITLE
Recognize HP1920 switches as Comware and not as Generic Device

### ISSUE THREAD

**Issue by JF3** [librenms/librenms#2090]
Similar to #801 my new HP1920-16G is not recognized as a Comware device. The corresponding SNMP oid seems to be 
` iso.3.6.1.2.1.1.1.0 = STRING: "1920-16G Switch Software Version 5.20.99, Release 1108
Copyright(c)2010-2015 Hewlett-Packard Development Company, L.P." `
Could you match that, too?

Thanks!

**Comment by laf** [comment]
Can you provide the sysObjectID?

You can do this via snmp or just run:

`./discovery.php -h HOSTNAME -d -m os`

**Comment by JF3** [comment]
Hope this helps:
```
OS: DEBUG: SNMP Auth options =  -v3 -n '' -l 'authNoPriv' -a 'MD5' -A '' -u 'librenms'
/usr/bin/snmpget -v3 -n '' -l 'authNoPriv' -a 'MD5' -A '' -u 'librenms' -Ovq -M /opt/librenms/mibs udp:hpsw1:161 SNMPv2-MIB::sysDescr.0
1920-16G Switch Software Version 5.20.99, Release 1108
Copyright(c)2010-2015 Hewlett-Packard Development Company, L.P.

DEBUG: SNMP Auth options =  -v3 -n '' -l 'authNoPriv' -a 'MD5' -A '' -u 'librenms'
/usr/bin/snmpget -v3 -n '' -l 'authNoPriv' -a 'MD5' -A '' -u 'librenms' -Ovqn -M /opt/librenms/mibs udp:hpsw1:161 SNMPv2-MIB::sysObjectID.0
.1.3.6.1.4.1.25506.11.1.165
```
(from discovery.php, passphrase redacted.)
