### ISSUE TITLE
Show sysName in widgets instead of ip addresses

### ISSUE THREAD

**Issue by paszczus** [librenms/librenms#2091]
We have almost all devices added by ip addresses and it would be cool if we could display them by names instead of ips

**Comment by f0o** [comment]
Which widgets are you talking about?

**Comment by paszczus** [comment]
Top x devices, Top x interfaces. But i would like to see descriptions instead of ips whenever it is possible, as mail notifications etcetera. This one is the easiest place i guess

**Comment by compuguy** [comment]
This would help with devices that do not have a resolved DNS domain (i.e. switches, routers, etc). That and showing the DNS and or sysname in the availability map widget.

**Comment by jmoore2016** [comment]
Hello, I am trying to get this working in the latest version and it does not seem to work. I uncommented the line in /includes/default.inc.php and added it to config.php with no luck. Do you have any advice?
