### ISSUE TITLE
Visual issues with legend on some graphs using rrdtool 1.4.7

### ISSUE THREAD

**Issue by SaaldjorMike** [librenms/librenms#2092]
After #1748 I get the following legend for port_errors: https://i.imgur.com/U32gW7r.png

**Comment by f0o** [comment]
I knew something was wrong.. I get those `STACK` lines in almost every graph :/

**Comment by SaaldjorMike** [comment]
Reopening this, due to the fix being reverted.

**Comment by paulgear** [comment]
@SaaldjorMike when was the fix reverted?  I'm looking through PRs and not finding it...

**Comment by paulgear** [comment]
Ah - found it in 54db5be7f10cd20f6c391f2b6c31c97a0cbec2c6

**Comment by SaaldjorMike** [comment]
Not sure we're there yet, as there are still "STACK" text in the bottom of my graphs. Here's some examples:
https://i.imgur.com/KpanUvY.png - Interface Errors
https://i.imgur.com/cpG4Xmw.png - Interface Non Unicast
https://i.imgur.com/nTW8jpR.png - device_bits graph
