### ISSUE TITLE
pfsense categorised as server but it's a firewall

### ISSUE THREAD

**Issue by markuspachali** [librenms/librenms#2095]
Hi all,

in /opt/librenms/includes/definitions.inc.php Line 216 pfsense is mapped as type server, but it's a firewall which is based on FreeBSD. Wouldn't it make sense to change the type to firewall?

Best regards,
Markus

**Comment by SaaldjorMike** [comment]
Thanks for reporting @markuspachali. Your request has been merged now, so this issue can be closed. :)

**Comment by markuspachali** [comment]
Perfect, many thanks! :)
