### ISSUE TITLE
ARP autodiscovery settings

### ISSUE THREAD

**Issue by paulgear** [librenms/librenms#21]
Need to decide whether it's a good idea to turn on ARP autodiscovery by default.  LibreNMS is supposed to autodiscover things, but ARP autodiscovery might be a bit intensive.  On my home install it reported on the first run of the autodiscovery: "21 devices discovered in 223.9 secs".  On large networks a discovery like this could run for hours.

One option might be to limit the number of devices autodiscovered in a single run.  However, because discovery only runs once every 6 hours, it might take a very long time to effectively discover a moderate-sized network.

To mitigate this, should we set a target time for full discovery, and then calculate how many hosts based on the size of the ARP tables?  I could see myself trying to get too clever here...

**Comment by laf** [comment]
Quite an old issue this now.

In reality are we actually seeing arp discovery issues? I've seen a few people on irc say they use it on a decent scale (no idea on numbers) and it just works?

I'd like to propose to close this if possible @paulgear

**Comment by paulgear** [comment]
Yeah - probably not much point in leaving it open; the default of off makes good sense to me.
