### ISSUE TITLE
Alert timestamps not updated upon new fault

### ISSUE THREAD

**Issue by Mattz0r** [librenms/librenms#2101]
It appears that if I have a switch, that already has an existing fault alerted against it, and a second fault is raised, the alert timestamp is not updated.

It would also be handy to have a per fault timestamp, for if a fault has been going on for say 3 hours, and a new one comes on, then it'd be two different timestamps, would help to  manage and prioritise things to look into, etc.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
