### ISSUE TITLE
speed updates not being reflected with regards to alerts.

### ISSUE THREAD

**Issue by Mattz0r** [librenms/librenms#2102]
When I update the speed of a port via the devices edit page, with [X] X being the number of Mbits, the device sees the update, but the alert doesn't.

For example: 

2015-10-10 15:20:16 	1/0/13 speed: 2 -> 12
2015-10-10 17:35:29 	1/0/13 speed: 12 -> 15
https://imgur.com/Mp75Ypd

If you need any further information, let me know.

**Comment by f0o** [comment]
Please paste the rule too :)

**Comment by Mattz0r** [comment]
%macros.dynamic_out_speed > %ports.port_descr_speed && %ports.port_descr_speed != "NULL" 

%macros.dynamic_in_speed > %ports.port_descr_speed && %ports.port_descr_speed != "NULL" 

$config['alert']['macros']['rule']['dynamic_out_speed'] = '(%ports.ifOutOctets_rate*8/1000000)';
$config['alert']['macros']['rule']['dynamic_in_speed'] = '(%ports.ifInOctets_rate*8/1000000)';

**Comment by Mattz0r** [comment]
the ifOutOctets_rate should have a * after it.

**Comment by Rosiak** [comment]
any input om this @f0o ?

**Comment by f0o** [comment]
Sorry totally forgot about this issue. Will test it on our test system

**Comment by Mattz0r** [comment]
How'd we get on? xD

**Comment by ipguru99** [comment]
If it is any help, I just tested it tonight and it still works for me. Here is what I have in my config.php:
`$config['alert']['macros']['rule']['port_in_perc'] = '((%ports.ifInOctets_rate*8)/%ports.ifSpeed)*100';
$config['alert']['macros']['rule']['port_out_perc'] = '((%ports.ifOutOctets_rate*8)/%ports.ifSpeed)*100';
#
$config['alert']['macros']['rule']['dynamic_out_speed'] = '(%ports.ifOutOctets_rate*8/1000000)';
`
My Rule for the alert looks like this:
`%macros.dynamic_out_speed > %ports.port_descr_speed`

If there is anything else I can show, please let me know

**Comment by Mattz0r** [comment]
It seems this has been resolved, with fixing another problem that I had :) - I've marked this as closed!
