### ISSUE TITLE
Make graphs in widgets clickable

### ISSUE THREAD

**Issue by SaaldjorMike** [librenms/librenms#2103]
E.g. clicking on the graph in a widget with device_processor, takes you to:
```
/graphs/to=1444506000/device=204/type=device_processor/from=1444419600/legend=yes/
```

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Sounds reasonable :+1:

On October 10, 2015 9:42:10 PM GMT+02:00, Mike Rostermund <notifications@github.com> wrote:
>E.g. clicking on the graph in a widget with device_processor, takes you
>to:
>```
>/graphs/to=1444506000/device=204/type=device_processor/from=1444419600/legend=yes/
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2103
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5MhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikgPGYwb0Bs
aWJyZW5tcy5vcmc+BQJWGWp2AAoJEJMZKtVWOFzB2aMP/3OyihmcokAvyt3oX25O
Y14188uyiYGAeplWShnuNXaMd2misxXjuxyKzvaiv1757TS4LyQYoaM2MsTz3ghr
AEzRwvi52oNMDn6g/LMKqTXdvO6o8Mmilrop/diyVnBqTbW25Wh4fWtDmmfjb3s+
9V3Wl+74F93vuhn0ms9C8FtohCIhCqm7qLIkZ7qqxCXHxaPtRGTWeBZu/zsp8XKi
jGRf6vFLUwZd2L3XpCC2ue0Len7OVoSXJLKu9f9a0k6a3Pcc9Uq6bhVA2GbhMExp
us5zCVZ5T8aaDjjRf4L9M1+wRpVFvAsLc+LBAS8y6tybTDTXOhTbxzf1BUHbOsLh
WVBcbhXvW9q0y9PmB+uUK7TzQ8qIIABJtMvTfmiFIq0y6f39FPn4UPYFXJSlQQAm
jwa8mY12izVpRl2kuyQXkECLGRygbEnR9CzzoyRhijEdjLKJgl9OcUz0fdw/KZ8q
GlA3ExmyuogGoHBYD2jkW/OPQgy7D+PG5ttdmYXFHNlKd+kzUZ4HRcrrpgw4haZM
iDmCuT4lSZCBYAhFNiZXvvuiUFZjZsqgjdC/tXuZkdZYL+4pwo0S+4FYk5DLPseX
23YsP41mg3xOkYwKlUyn1mIHvD5wFJ7koyn9xOJjCO5eCP2VuupAA8IeU+UcuuGM
SBOtTaFJR0BZ2w04NHdY2spE
=m8cN
-----END PGP SIGNATURE-----

**Comment by paulgear** [comment]
Big :+1: from me

**Comment by laf** [comment]
Was done a bit ago.
