### ISSUE TITLE
Don`t allow device to be added twice

### ISSUE THREAD

**Issue by paszczus** [librenms/librenms#2105]
I have a Linux router which is having multiple ips (for every vlan) and while doing discovery it`s being added as new device for another ip. The only solution for now that i found is to leave those duplicated entries and set to ignore and disable.

**Comment by masonke** [comment]
I have a similar problem with ESX 5.5 hosts that have multiple interfaces and using the same procedure
~KEM

**Comment by laf** [comment]
This is honestly why you should use hostnames. We provide the ability for people to add devices via IP as it's a highly requested feature but it also means that we can't 100% validate for duplicate devices.

**Comment by masonke** [comment]
Actually, all my devices are by host name, but discovery keeps adding them by ip. 

Right now I have to use /etc/hosts as we rebuild our DNS infrastructure (don't ask). That may have an impact on this. 

Sent from my phone, please excuse typos

**Comment by paszczus** [comment]
@laf this one host is also added by hostname, but then it`s beeing added by IP automaticly.

Can`t you use some uniq id like serial number or check if there is already added host with same mac as discovered on newly find device?

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

SerialNo & co dont exist for *nix devices and also for unsupported devices they are unavailable. Don't think that's a good way to avoid duplicates. I do support the DNS way, making sure there is only one device with same forward and backward dns entry.

Mac might be possible with a performance penalty as we need to crawl entire IF-MIB before adding the device and calculate a score value on duplicate mac-entries.

My decaffeinated 2cents :)



On October 12, 2015 9:02:55 AM GMT+02:00, paszczus <notifications@github.com> wrote:
>@laf this one host is also added by hostname, but then it`s beeing
>added by IP automaticly.
>
>Can`t you use some uniq id like serial number or check if there is
>already added host with same mac as discovered on newly find device?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2105#issuecomment-147304689
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5MhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikgPGYwb0Bs
aWJyZW5tcy5vcmc+BQJWG1+3AAoJEJMZKtVWOFzBCk4P/jQiK2txxWmbmO025ymY
uXf6BFiQ1KOMx2OiDQFiorVNgF7ZYkUI4in+zMjYloTIUuQcf3hDQynfDmh8Whlk
jMe5YGb2ylq8GJUJgEulPElWIL6C0ztcmiQkTXglBY0Nc+gh6delbRguIEU2u2sB
7JPR2fhlieJVkf9PwXaUlUVwqJWXfdDzDGIFpDdhC8kKsniZtcP8m3uvJ2tcIF8p
Mihj4TEeUOHn7SYR6+dw/8w7+L//Udm0SDTjzxrMDWaOjBcqzuEQs/kmz2hl8rOy
9svdIUJS1lft2vw+/vY3vW3CgDQlk3+n8HK4WmDCLXGol7tS5LDB9JcBOFp7RW8/
0AZUaa7T7zwXf/i9/LO7tgsThKStwcIVJZCUZKTP6cmylaHoAk3kZBmjhukA7vDK
DT/CpBqp0wAe37ejV/i2ZrYVG4M1KUX7hihmigSTGWm4Xk4mK1G8wKH9BenT4oiI
1rfXMNGy7854ID+tJKmNukBr5+5HX+YOzjXc61/4n1qIIN7vhw6HcIr9v7KRIMAY
wMl8Z1dp1CTALxvWApbHr4mcijxcYnLCmvTeU4sLbP+Vu/9esxvIpN1jhXhP6R32
JY+IDL9IqW5lgVoyWJY8J5/xN/gPQNmmAAFnSc+mTY2HPYaojLTgH930a6YZAPTx
wlVce0L8ymyCfIXXlQ4vawid
=tWPw
-----END PGP SIGNATURE-----

**Comment by masonke** [comment]
Just a data point. For my systems, in the case of 8 esx systems and 3 nexus, I deleted the entries I added by name and renamed the ones discovered by ip. The next day, they were rediscovered by ip again. 

Disabling the discovered devices is the only way I can find to stop it. 

I am using /etc/hosts for reverses, so that may have a bearing on this

Sent from my phone, please excuse typos
>

**Comment by f0o** [comment]
Did you (all) set `$config['addhost_alwayscheckip']   = true;`  in your configs?

If not, that might be the reason for duplicates.

From the docs of it:
`$config['addhost_alwayscheckip']  = FALSE;   # TRUE - check for duplicate ips even when adding host by name. FALSE- only check when adding host by ip.`

**Comment by laf** [comment]
I wonder if this is as simple as the order of the discovery modules. For duplicate detection in the IPs we already do we rely on having discovered those. If autodiscovery runs before IPvX discovery runs then we don't yet have the IPs to detect duplicates against. If this is the case we may be able to move the module order around - need to investigate a little more.

**Comment by masonke** [comment]
I have that set on all the pollers and RRD/GUI box.
~KEM

**Comment by laf** [comment]
@masonke have `$config['addhost_alwayscheckip']` set?

**Comment by masonke** [comment]
Yes   $config['addhost_alwayscheckip'] = true;  is set
~KEM

**Comment by f0o** [comment]
Spinning up some VMs to reproduce this scenario

**Comment by masonke** [comment]
Is there some information that I can pull from my system that would help you?
~KEM

**Comment by laf** [comment]
Ok, from what I can see the only way this could happen is if the IP that is being added doesn't exist in the Ipv4_addresses table because either ipv4_addresses discovery is disabled OR the device with the IP doesn't respond back to the ipv4_addresses discovery process so we don't know the IP and can't detect it.

The only thing we can do is have an option for you to disable adding devices by IP only.

**Comment by masonke** [comment]
I will check in the morning, but I am sure the same IP address is being used for the devices added by host name and the ones being discovered.


~KEM

**Comment by masonke** [comment]
I actually have 3 entries for some devices, IP, short name, and fqdn. Using prdlexvrtesx007 as the example, here is what I have in the database:


The device has only one IP address, and there is a host entry as prdlexvrtesx007. The entry for prdlexvrtesx007 was originally and IP address and I did a rename.php to fix it.

Not sure how to pull the IP address in SQL for each entry, if that is important.

Any ideas?

~KEM

**Comment by laf** [comment]
@masonke The above doesn't have any DB output :)

The query we run to get the IPs and then check they don't already exist is:

```
    SELECT *
    FROM ipv4_mac as m, ports as i
    WHERE m.port_id = i.port_id
    AND i.device_id = ?
    AND i.deleted = 0
    AND NOT EXISTS (
        SELECT * FROM ipv4_addresses a
        WHERE a.ipv4_address = m.ipv4_address
    )
    GROUP BY ipv4_address
    ORDER BY ipv4_address
```

Replace ? with the device_id

**Comment by masonke** [comment]
Sorry, this has been one of those weeks. Here is the missing output 
mysql> select * from devices WHERE `sysname` LIKE 'prdlexvrtesx007';
+-----------+--------------------------------+-----------------+------------+---------------------+
| device_id | hostname                       | sysName         | version    | last_discovered     |
+-----------+--------------------------------+-----------------+------------+---------------------+
|       629 | prdlexvrtesx007.vistaprint.net | prdlexvrtesx007 | ESXi 5.5.0 | 2015-10-14 02:59:47 |
|       789 | prdlexvrtesx007                | prdlexvrtesx007 | ESXi 5.5.0 | 2015-10-15 12:41:16 |
|       937 | 10.89.220.107                  | prdlexvrtesx007 | ESXi 5.5.0 | 2015-10-07 19:04:27 |
+-----------+--------------------------------+-----------------+------------+---------------------+
3 rows in set (0.00 sec)

Working on grabbing that query for you

**Comment by masonke** [comment]
Just tried your query sequentially using each of the device_id. And each time it came back empty

**Comment by laf** [comment]
@masonke You'd need to delete the two devices that have been auto discovered before running that last query.

**Comment by paszczus** [comment]
Today i have changed addressation on one tower and then librenms has discovered new addresses as new devices (which is ok) but it has added same devices many times. Please look at attachement.
![zrzut ekranu 2015-10-18 o 16 12 22](https://cloud.githubusercontent.com/assets/1582475/10564404/4ffdbf56-75b3-11e5-81e3-fb36175ff20a.png)

**Comment by paszczus** [comment]
Ok, so it would be good for me if libreNMS can check if there is already a device with same hostnamel/IP. As you can see on my previous attachment that same device with ip "172.16.126.98" has been added multiple times. IMO it should be checked before adding it to database like that:

SELECT hostname from devices WHERE hostname = '172.16.126.98' and if there is already an entry for that libreNMS will not add it again. As far i know right now this check is only for FQDN hostname instead of IPs right? Sorry if i am wrong

**Comment by laf** [comment]
irc comments to save repeating:

12:23 <@laf> paszczus: It's already done at the start of addHost but looking at the code this isn't enough
12:25 <@laf> here's me adding the same host twice at the same time:
12:26 <@laf> ./addhost.php host2 librenms v2c
12:26 <@laf> Trying community librenms ...
12:26 <@laf> Added device host2 (18)
12:26 <@laf> ./addhost.php host2 librenms v2c
12:26 <@laf> Trying community librenms ...
12:26 <@laf> Added device host2 (17)
12:26 <@laf> it's a race condition
12:26 <@laf> both attempts have done the query for duplicates before an insert is done leading to the addHost script continuing and adding the device in
12:26 <@laf> we need a second duplicate test doing just before insert
12:27 <@laf> that race condition isn't even just milliseconds, it's all down to how slow devices are to respond to ping and snmp, the slower they are the longer the time window duplicates are possible

**Comment by masonke** [comment]
Ouch, makes sense.

If I delete my duplicated discovered by IP that I disabled, could this race condition cause them to be re-discovered?

~KEM

**Comment by masonke** [comment]
Just found this set of duplicates. This switch has only one IP and was auto discovered by libranms. 

Interesting that the device ID are sequential, makes sense if there is a race condition.

device_id,hostname,sysname,os,poller_group
777,dpk-voip-2821-1.mydomain.net,dpk-voip-2821-1.mydomain.net,ios,7
778,dpk-voip-2821-1.mydomain.net,dpk-voip-2821-1.mydomain.net,ios,7
779,dpk-voip-2821-1.mydomain.net,dpk-voip-2821-1.mydomain.net,ios,7
780,dpk-voip-2821-1.mydomain.net,dpk-voip-2821-1.mydomain.net,ios,7
781,dpk-voip-2821-1.mydomain.net,dpk-voip-2821-1.mydomain.net,ios,7
782,dpk-voip-2821-1.mydomain.net,dpk-voip-2821-1.mydomain.net,ios,7



~KEM
