### ISSUE TITLE
Suggestion, organize defaults.inc.php file by functional section

### ISSUE THREAD

**Issue by masonke** [librenms/librenms#2106]
It would be very handy and make it easier to understand if the defaults.inc.php
 was organized into sections used by the various components. This isn't re-coding anything, just shuffling the files into logical sections

For example, having sections that are
Common
Dist Pollers
GUI
API
Etc

Using this, if I want to disable a discovery module, is it a change I need to make in all devices (common), the pollers (Dist Pollers), etc.

Similarly, adding a community string, memcachd setting, rrdcachd, etc

**Comment by laf** [comment]
I'm not sure I understand if there is a question in this?

**Comment by masonke** [comment]
Sorry, would it be possible to do this?  

Sent from my phone, please excuse typos

**Comment by laf** [comment]
It would be fine to organise the defaults.inc.php :)

**Comment by masonke** [comment]
Ok, let me get it started and then ask for help with the parts I do not know
~KEM

**Comment by laf** [comment]
:+1:

**Comment by Rosiak** [comment]
@masonke any news?

**Comment by masonke** [comment]
None,

Due to personal reasons I have not even started this
~KEM

**Comment by f0o** [comment]
:+1: on organizing it. Less mess more awesome :D

**Comment by laf** [comment]
Closing, no further feedback provided. We should have all needed options documented that this isn't too much of an issue.
