### ISSUE TITLE
Avergage packet size on ports graph ?

### ISSUE THREAD

**Issue by xbeaudouin** [librenms/librenms#2111]
Hi,

I was looking forward to support a graph with Average packet size .
Seems that can be done with some "tricky" computations like : 
ifInOctets  /ifInUCastPkts + ifInNUcastPkts (between 2 polls)
and same with Output packets.
Looking forward on how to add this into Librenms, but need advice.

**Comment by laf** [comment]
lol, I'm unsure if you just made a mistake in saying about adding this to Observium, you're trolling or are being serious :)

**Comment by f0o** [comment]
I hope it was a mistake or a troll lol

**Comment by xbeaudouin** [comment]
Sorry I have "looked" a the code of one of my old Observium running on the same host as my Librenms and saw... That this feature was not (yet) on Librenms.
I can code it, just have to figure where and how to add this kind of graph.
I fixed the original ticket. Sorry about the unwanted troll !

**Comment by f0o** [comment]
Uhm... You've signed the Contributor's Agreement on 6/10/2015 with commit https://github.com/librenms/librenms/commit/10c597225dcc55909f0182abb8db21db386a7e75 - That `old Observium` better be before `r3250`

**Comment by xbeaudouin** [comment]
Hum I have some stuff like this http://pix.toile-libre.org/?img=1444651626.png, according to the code from the observium commity this feature can be good.
Since it seems it is done only by data manipulation, it can be good to add it (even if it "may" be not accurate).

**Comment by laf** [comment]
@xbeaudouin You can't contribute code that you view from observium, the best way for this feature would be for someone else to add support based on your description of your request. I'm sure someone else will pick this up at some stage.

**Comment by xbeaudouin** [comment]
@laf I don't want to cut and paste de code from observium, just to know how can I compute another graph based on the data that is on the RRD.
We currently have (I think), between 2 poll / rrd interval :
- Number of data gathered (n)
- Number of unicast packets  (upkt)
- Number of non-unicast packets (npkt)
Simple way to make the stats is : av_psize = n / (npkt + upkt).

Now I just want to add this kind of graph (this is not Observium (C)(R)(tm) stuff, but simple compute).

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Xavier by mentioning Obs you've brought us in a complicated situation.

We cant/wont comment on anything obs related, let alone giving advice on how to code for/from/in/ontop/... it.

We have to ensure that the contribution's agreement stays valid and enforce it where needed.

I hope you dont take it personally, feel free to join IRC to discuss this indepth.

Proposing closure of this issue.

- - f0o

On October 12, 2015 3:30:20 PM GMT+02:00, Xavier Beaudouin <notifications@github.com> wrote:
>@laf I don't want to cut and paste de code from observium, just to know
>how can I compute another graph based on the data that is on the RRD.
>We currently have (I think), between 2 poll / rrd interval :
>- Number of data gathered (n)
>- Number of unicast packets  (upkt)
>- Number of non-unicast packets (npkt)
>Simple way to make the stats is : av_psize = n / (npkt + upkt).
>
>Now I just want to add this kind of graph (this is not Observium
>(C)(R)(tm) stuff, but simple compute).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2111#issuecomment-147400865
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5MhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikgPGYwb0Bs
aWJyZW5tcy5vcmc+BQJWG7b4AAoJEJMZKtVWOFzBmTwP/R0xEfher3wrWg/+Esey
TwyZmj7Lv2S+S/MIRWCLHb9BVEpBCybdWkyIOS75pi74pzbVgwC/HnxX60Dw2BPP
LYGOlsFkI2oLkHuIVwtVDEG+a6b5lhP0a1NAQf/tSNpsy76aKn3bQRdv7KL1sNGJ
BrZeYMbLntxI2jCrBuaFi/p/oRKKVIaOS6jGlVxE6RpW7Pm3YyBTwlNLGRsS010z
u1qBn83v4hoU53lRN6TdjSkqSynoKzuQV7H/6dbAv2htbUJLRIfcvqlpBKRE620F
9LGK6WJEKv/q8gVUrxlSHh0R6oergvnnCK8pVZ/4llJ0paO0K6Dw7z+xXo0bLJPO
YyWDglaSsaJJ7CbCgkiQHRmoObaBP74lc50A/olNkME0niGKcTd7UxqARo77EfNE
qI/BmKDOhEnkEBXCz+4KpEE87b5XcZgwqo2BC9scovsgnan1eS94mRenDCnQChDJ
qRbK5BRQ2ojmwMdrKFP44RQnwXFtRhz6E3cDcHAr5owawboy2poBJbrbKXwM1unb
gV3z63jYWD9qq/zonSZFncBsClGhsiVz9LcJCIkoN8UnN42QMkU9q9fjqur9Yj1m
7r8i1I204brYw+Pmdx/ZUL+NhtV/+XaDfYxfUpT8cCZswG0PqmThgmFXQuJyv2A7
rgM9/ghduC6khz8ysLvuNZ5j
=eTnU
-----END PGP SIGNATURE-----

**Comment by laf** [comment]
@xbeaudouin Unfortunately we have a set of rules in place for contributions which we must stick to to avoid any contact or issue with/from obs..

In this particular instance the best option is for someone else to code this up. For future contributions from yourself which we really would love to see, would need to be done based on your own work and not looking at code from obs..... I'm afraid it's just the way it is for us.

**Comment by xbeaudouin** [comment]
ok so close.
