### ISSUE TITLE
Cisco Wireless clients

### ISSUE THREAD

**Issue by ipguru99** [librenms/librenms#2115]
I can get graphs for the hundreds of our AIR-AP1242AG-A-K9's. But what I can't get are the number of clients currently associating with them. I think I have all the information on how to graph it, but I don't know what to do with it. 

MIB CISCO-DOT11-ASSOCIATION-MIB 
Object cDot11ActiveWirelessClients 
OID 1.3.6.1.4.1.9.9.273.1.1.2.1.1 
Type Gauge32 

 i..and here is what I get:

x@librenms:~# snmpwalk -cxxxx  -v1 xxxx-ap01 .1.3.6.1.4.1.9.9.273.1.1.2.1.1.1
iso.3.6.1.4.1.9.9.273.1.1.2.1.1.1 = Gauge32: 7

...and I know there are currently 7 people associated.. 

Where can I go from here? Thanks to everyone working on this. It has become my standard for clients that need an NMS!

**Comment by laf** [comment]
mib-based polling will be your best bet but it's in between 'betas' at present.

@paulgear any update on the newer version?

**Comment by paulgear** [comment]
The code & doc are pretty much ready to go, I think.  It's just waiting on the schema changes decision.  But I think we might be better off just pushing through the current outstanding PRs before dealing with the schema issue.

**Comment by paulgear** [comment]
@ipguru99 I think we should be able to achieve this now through the MIB-based poller.  What OS do your Cisco wireless controllers show up as?

**Comment by ipguru99** [comment]
Thanks Paul! I ended up changing line 32:
  if ($device['os'] == 'ios' && $device['type'] == 'wireless')

at "/opt/librenms/includes/polling/wifi.inc.php" in order to get my Cisco 1242's (and 1262's.. and 2702's) to show up. It works great now. 

I have been watching your progress on the mib-based polling. I have a bunch of Windows hosts for a customer of mine being monitored by JFFNMS. I would like to add those Windows hosts (and hence the eagle-eye watching of the mib-based polling). I can get drive sizes and network traffic. I just need those services.. The services now are ok, but they are really hard for HelpDesk people to read (there isn't any real way to track what host is being looked at when everything points to localhost.. I can figure it out, but they don't pay me to sit in front of a monitor and watch things ;-)

I tried to follow the instructions in the documentation, and I finally got all the way to step 7, but I can't tell what is being polled.. what is being graphed (nothing that I can see). 

I keep their installation up to date, just haven't had a chance to try to take another run at it. 

This interface is a beauty.. VERY easy to show CIO/CTO's and show them how good free software can be!! Please continue the great work!!

**Comment by Rosiak** [comment]
This this one addressed it.
#3286
