### ISSUE TITLE
how monitor proxmox v4.x?

### ISSUE THREAD

**Issue by alex1528** [librenms/librenms#2123]
- perl proxmox 
keys on reference is experimental at /usr/share/perl5/PVE/API2Client.pm line 142.
501 Method 'GET /cluster/ha/config' not implemented

thanks

**Comment by f0o** [comment]
bit more details please? I've no clue where that message is from or what PVE/API2Client.pm is.
It's not part of LibreNMS as far as I can tell...

**Comment by f0o** [comment]
Tagging: @tuxis-ie

**Comment by laf** [comment]
I'm guessing it's the code on the proxmox box itself. I'll take a look at mine tonight.

**Comment by tuxis-ie** [comment]
Proxmox 4.0 has a new clustering-thingy. The call being done here is to determine which name to give the cluster this proxmox-host is in..

**Comment by alex1528** [comment]
yes, the cluster structure had changed of the PVE's v4.x, so there will be follow up? 
thanks a lot!

**Comment by tuxis-ie** [comment]
Yes, I'll check it out.

-- 
Mark Schouten
Tuxis Internet Engineering
mark@tuxis.nl / 0318 200208

**Comment by tuxis-ie** [comment]
https://github.com/librenms/librenms-agent/pull/12 Fixes this!

**Comment by f0o** [comment]
Merged https://github.com/librenms/librenms-agent/pull/12
