### ISSUE TITLE
Generic Device

### ISSUE THREAD

**Issue by fran-nlt** [librenms/librenms#2130]
Hi
I add Fortigate 70D, but is Generic Device.

I added addhost.php and after used discovery.php -h all

![captura](https://cloud.githubusercontent.com/assets/13962782/10463525/7799eb3a-71bb-11e5-9c8c-71bc74f1b010.PNG)

**Comment by fran-nlt** [comment]
i solved added the IP the Firewall in the /etc/hosts.conf

**Comment by laf** [comment]
@fran-nlt Did you add it with -f from addhost.php? If so that would have forced it to be added without checking it would have worked.

**Comment by fran-nlt** [comment]
yes, I addhost with -f

**Comment by laf** [comment]
@fran-nlt Ok, that flag is to force the device to be added without any checks. Unless you really need to use it then don't :)
