### ISSUE TITLE
Feature Request: Ability to "hide" the menubar

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#2136]
As the title states.

**Comment by f0o** [comment]
Append /bare=yes/ ?

**Comment by Rosiak** [comment]
@f0o would be cool to have a "arrow" which one is able to hide and unhide the menubar with using some js.

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Regardless of the UI part, would that /bare=yes/ work?

I'm sure adding an icon for that goes quick ;)

On October 15, 2015 12:23:09 PM GMT+02:00, "Søren Rosiak" <notifications@github.com> wrote:
>@f0o would be cool to have a "arrow" which one is able to hide and
>unhide the menubar with using some js.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2136#issuecomment-148344329
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5MhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikgPGYwb0Bs
aWJyZW5tcy5vcmc+BQJWH37kAAoJEJMZKtVWOFzBbiwP+wT7KD/ORmrS5qWMEvhk
SrXEBrc7GLJvfeexcsFsoDf/m3dXRmHuBf3oxFtwcjlo5uUrWOE1oXt/uKD3nF3P
BX4Suw4zrg7ZgPP1Obt12d8rlTbKk3w2P0JYUdYn+pWZDrMUXIYc7R/nTRGD5sSz
5okxrzKx7j5mNF7zDuIZwxHGkH4ZNg22PnR/0fhIurBTwwYsePGhWGX24GT1Kfdk
o8WeP50ooUikrxBqCaprxlZowipnd4rKo3gBnkL/Yk9q8Kzp2+Nhf3BZqYfYUnzT
6PcdDV89krOVTJW84SpVF6x2JHcD9tKU4upYHFJZIL5DpYhU19LgvNgkRJGfX1Vj
1FEIO2fUxLYwNrWPCkEo9eIVoSRh2VFjKwUo9QOfCI7KL5qmW5N2576c/EsWqRsn
MV7k3pGwhDOuwKzQhq1putFqV0l+p9sFWAXUHbBN3u81+sgh9j/fqL2LBPc2qUUZ
DyFT+gjNrW6nXDt0SXaEBYQ5thyqgV+jS6dE+y9u6fvDQz54zMCwhmxJWbQBpJ03
WDj5kgul5f2k5IgD4b3Fdr+MUu97nR5CYdIh2g2H+NV0ff+Lf5SHhZzKh6uBmQ1q
rqYEGL64eIEsA2x7zvhOHCka0gGUzT/aCb0kr/gv6tBi40bZlaxQa46HGh9aKZ6k
alt6ABCUyAyBu8kIzrr+5iFW
=2vaS
-----END PGP SIGNATURE-----

**Comment by Rosiak** [comment]
Yup bare would work!

**Comment by laf** [comment]
Relevant still or can we close?

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #173](https://github.com/librenms/librenmsv2/issues/173) via [**ZenHub**](https://www.zenhub.com/)
