### ISSUE TITLE
Enhancement: Leaflet be able to disable grouping

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#2141]
Be able to disable the grouping of units so they doesn't end up like this:
![screen shot 2015-10-14 at 23 01 39](https://cloud.githubusercontent.com/assets/6378934/10497743/ddbfe5f6-72c7-11e5-83e8-89ab4bd4d3ef.png)

**Comment by laf** [comment]
If all the locations are exactly the same then all that would happen is you'd see only one device.

**Comment by Rosiak** [comment]
Yeah I guess that's true.

**Comment by SaaldjorMike** [comment]
I think it would be nice if it was possible to specify how close devices should be before they are grouped together.

**Comment by SaaldjorMike** [comment]
Proposing to close this if @Rosiak is ok with the PR #2170 that gives the user the ability to influence how close they have to be before grouping.

**Comment by laf** [comment]
:+1: as I think this will be the best you can get :)

**Comment by SaaldjorMike** [comment]
Roger, closing it then. @Rosiak feel free to reopen if you have any other ideas. :-)
