### ISSUE TITLE
Enhancement: Make LibreNMS "health" widget

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#2143]
Make a widget which is able to tell if install is up2date etc.

**Comment by Rosiak** [comment]
Not sure if this should be a widget or just something that's done with the incoming notification system.

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #158](https://github.com/librenms/librenmsv2/issues/158) via [**ZenHub**](https://www.zenhub.com/)
