### ISSUE TITLE
Clean Installation - can't add devices

### ISSUE THREAD

**Issue by starnetwork** [librenms/librenms#2152]
Hi,
after clean installation on CentOS 7, I cant' add devices
even the local device, got
No reply on community mycommunitycode using v2c
Could not reach localhost with given SNMP community using v2c
I try also with another devices, same...

any suggestion, where I can start from?

Regards,

**Comment by fran-nlt** [comment]
Do you config /etc/snmpd.conf with rocommunity public 127.0.0.1?

**Comment by Rosiak** [comment]
Hi @starnetwork ,
Can you please run the validate.php, and post the output here?

**Comment by starnetwork** [comment]
[root@monitor1 librenms]# php validate.php
[OK]      config.php tested ok
[OK]      Database connection successful
[OK]      fping has been found

**Comment by starnetwork** [comment]
thanks @fran-nlt , you give me the direction, I updated this file settings and it's work now

**Comment by vaibhavkholase** [comment]
hi starnetwork,
Hi I have checked php php.config and got below notice & warnings but could not resolved it.
So Could you please help in this.

PHP Notice:  Undefined index: SERVER_NAME in /opt/observium/config.php on line 35
PHP Notice:  Undefined index: SERVER_PORT in /opt/observium/config.php on line 35
PHP Warning:  Illegal string offset 'timeout' in /opt/observium/config.php on line 72
PHP Warning:  Illegal string offset 'retries' in /opt/observium/config.php on line 73
PHP Warning:  Illegal string offset 'debug' in /opt/observium/config.php on line 74
PHP Warning:  Illegal string offset 'debug' in /opt/observium/config.php on line 104
