### ISSUE TITLE
GPS coordinates directly from SNMP location

### ISSUE THREAD

**Issue by SaaldjorMike** [librenms/librenms#2153]
Would be nice if LibreNMS could grab the exact GPS coordinates (if they are set) directly from SNMP location without using sites like Google Maps to convert address to coordinates:
E.g. like: "Streetname 1, 5000 Odense, Denmark [55.380946, 10.357106]"
This is due to the fact that the approximate coordinates for an address is not always as precise as I'd like it to be, since the address being looked up may span a large area.

EDIT: being able to manually set the lat/lng in webui would probably also make sense to support.

**Comment by Rosiak** [comment]
:+1:

**Comment by f0o** [comment]
:+1:

**Comment by alex1528** [comment]
:+1:
