### ISSUE TITLE
Unauth/public dashboards

### ISSUE THREAD

**Issue by SaaldjorMike** [librenms/librenms#2154]
Would be nice if you could make certain dashboards available for viewing without authenticating though a simple HTTP GET. This would fit perfectly in with devices like: http://blog.airtame.com/the-easiest-way-to-display-your-dashboard-on-screen/ or any similar setup where a NOC has screens that will just show some URL.

**Comment by SaaldjorMike** [comment]
As @f0o pointed out, this is already possible by using an url like:
https://librenms.example.org/overview/dashboard=1?username=guest&password=guest&bare=yes

**Comment by cleonte** [comment]
This one seems broken?
