### ISSUE TITLE
Add device by different port 

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#2157]
Hi, If a Router named R1 has f0/0: 10.0.0.1 and f0/1: 20.0.0.1, when I add 10.0.0.1, and adding 20.0.0.1 is also possible. Is this a bug ? :)

**Comment by Mattz0r** [comment]
I believe there is a discussion similar to this at #2105 ?

**Comment by wzhsunn** [comment]
:) Thank you all very much !
