### ISSUE TITLE
[API] Add a check request method with the add_edit_rule function 

### ISSUE THREAD

**Issue by PandaWawawa** [librenms/librenms#2158]
Currently you can't edit a rule without modify it name
I'm want to modify the verification to only check the availability of the name on the add 
and on the edit, check the availability of the name only if the founded alert id != edited alert id

**Comment by PandaWawawa** [comment]
It seems that I just have to check on the rule_id parameter to see if it's an edit call or not
no need for request method

**Comment by laf** [comment]
merged
