### ISSUE TITLE
Enhancement: Device menu makeover 

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#2165]
I think we need to do something about this device menu soon, I'm considering introducing more tabs but not before we have found a way to deal with this visual issue.

Perhaps @arjitc got idea's / input?

![screen shot 2015-10-16 at 23 02 49](https://cloud.githubusercontent.com/assets/6378934/10553390/8a7a12a6-745a-11e5-8668-386eedfa7547.png)

**Comment by Rosiak** [comment]
Some more input, this is based on a "naked" boostrap but you get the idea.
And ofc. the margin between the lines should be smaller.

![screen shot 2015-10-16 at 23 56 35](https://cloud.githubusercontent.com/assets/6378934/10554185/ad38c952-7461-11e5-91f6-7bd84160483d.png)

**Comment by arjitc** [comment]
Maybe we can work on a navbar to the left of the page? Like a vertical navbar?

**Comment by arjitc** [comment]
OR a simper option at the moment would be to merge the 3 of the last 4 icons into a dropdown called Connect (SSH, Telnet and the other one) and Settings as it's own button

**Comment by adaniels21487** [comment]
I am in the same boat.
Over at #2196 I am looking for somewhere to display the information. First I created my own tab 'Call Manager' when I hit this issue, no room.
Then I added it to the Applications menu, but it doesnt really belong there either as these seems to be components of the unix-agent.

My thoughts are fairly drastic. I think we could do with some major consolidation of the device menu's into a few major categories.
At a high level I see something along the lines of:
- Overview - The summary page.
- Hardware - Physical components of a device. Health, Ports, Inventory, etc.
- Software - Most other things we poll that aren't hardware. SLA'a, Routing, Graphs, VM's, Applications, Performance, etc.
- Administration - Event Logs, Syslog, Alerts, Alert Stats, Notes, etc.
- MAP - Like it is today.

Anything new would go into an existing category.
Thoughts?

Aaron

**Comment by paulgear** [comment]
@adaniels21487 I think you're right in that a major change is necessary, but we need to be careful that a) it is intuitive and adds little inconvenience for existing users, and b) it preserves backwards compatibility for URLs, so that people don't have to change their bookmarks.

**Comment by Rosiak** [comment]
v2 should address this.
