### ISSUE TITLE
Enhancement: Global menu makeover

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#2168]
Perhaps remove the text from the logo so only the square is visible?
Perhaps remove the font-awesome icons in the menubar

![menubar23](https://cloud.githubusercontent.com/assets/6378934/10555189/94f882a6-746b-11e5-9f8d-cb69f298bff6.png)
![menutest2](https://cloud.githubusercontent.com/assets/6378934/10555188/94f73b8a-746b-11e5-9eea-7aeba588c9d4.png)

**Comment by adaniels21487** [comment]
Hi Rosiak,
I have been looking at this too. I was thinking:
- Small Screens - Icon only - Wrap the label in a div with hidden-sm
- Medium Screen - Text only - add hidden-md to the icon
- Large Devices - shrink the left/right padding on .nav>li>a to 12px. At the moment we dont even fit on a large (1200w screen)

Thanks,
Aaron

**Comment by paulgear** [comment]
:+1: to that suggestion, @adaniels21487

**Comment by Rosiak** [comment]
@adaniels21487 Sounds reasonable!
