### ISSUE TITLE
the Globe map can't open the settings's options

### ISSUE THREAD

**Issue by alex1528** [librenms/librenms#2169]
the Globe map can't open the settings's options
like the Worldmap,can set the Initial Latitude or Initial Longitude or Initial Zoom.

**Comment by laf** [comment]
Globe doesn't have these options available and I don't think we really will be continuing much support for the Globe map due to it's limitations.

**Comment by alex1528** [comment]
Thanks, I want to zoom in or out for the some region,like only show the China Region.
![2](https://cloud.githubusercontent.com/assets/12593499/10558644/20b71a84-750a-11e5-8784-ee50d6f109fe.png)

**Comment by laf** [comment]
Why not just use the Worldmap?

**Comment by alex1528** [comment]
the Worldmap can't display the device location,like this
![3](https://cloud.githubusercontent.com/assets/12593499/10559252/ec8e8232-751e-11e5-91db-0c0e062e80ed.png)
where i missing something ? how can  i fix that?
thanks

**Comment by laf** [comment]
The addresses need to be resolvable within Google maps and the following set in config.php:

`$config['geoloc']['latlng'] = true;`

**Comment by alex1528** [comment]
It's fix. Thanks
