### ISSUE TITLE
Graphs related

### ISSUE THREAD

**Issue by mail3dexter** [librenms/librenms#2171]
Is there a way to center 0th value like if we consider this case http://prntscr.com/8s97bx , there is a big bold line indicating 95% of inbound traffic (got to know from IRC). 

I basically want that bold line to be on 0th position becoz it sometimes looks confusing.

Also, is there a way to generate graphs / change graph views to unidirectional? I mean rather than plotting download going up and upload going downwards, why not plot on just 2 axis +x and +y with overlapped fashion ?

**Comment by laf** [comment]
This is the best I could come up with:

Before:

![image](https://cloud.githubusercontent.com/assets/3941142/10805290/80dce1ec-7dc4-11e5-9bd1-8bca7d8263cf.png)

After:

![image](https://cloud.githubusercontent.com/assets/3941142/10805296/8ab8aff2-7dc4-11e5-9f7b-f367c800d497.png)

With this:

```
$rrd_options .= ' CDEF:flat=inB0,0,*';
$rrd_options .= ' LINE3:flat#000000';
```

If however you just mean you want to get rid of the 95% line then we can probably add an option to remove that line.

**Comment by paulgear** [comment]
@mail3dexter This might be a simple fix if you can explain in more detail how you want the graphs to look.  Even just a graph you've marked up by hand in the GIMP or something would be fine.

**Comment by mail3dexter** [comment]
I am taking about the line which is there at +11M in http://prntscr.com/8s97bx which shows inbound average i guess. So either it should be on both ends or it should be just in center. Drawing bold line like this is confusing.

**Comment by SaaldjorMike** [comment]
@mail3dexter What LibreNMS version, db schema and rrdtool version are you running? You can find it all on the `/about/`page.
I got the 95th percentile on both in and out, e.g.:
https://i.imgur.com/lXikwIf.png

**Comment by mail3dexter** [comment]
Sorry for late reply. My librenms was not getting updated. I have installed a newer copy which gets updated and this issue is fixed now.. Thanks everyone for help.
