### ISSUE TITLE
Add Bintec SNMP MIB

### ISSUE THREAD

**Issue by nielsraijer** [librenms/librenms#2178]
Hi, we have a fair number of Bintec routers in the field and they cannot usefully be polled by LibreNMS. Would you consider adding the MIB and do the other things necessary to make this work? The MIB can be downloaded from http://www.bintec-elmeg.com/en/Downloads-Management-Information-Base-MIB-for-SNMP-Manager-648.html

If you need SNMP Walk data, or access to a Bintec device, let me know.

**Comment by laf** [comment]
@nielsraijer please add the device and provide the output of:

```php
./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -d -r -m system,os
```

**Comment by nielsraijer** [comment]
Hi Neil,

Thanks very much for looking at this case.

> @nielsraijer please add the device and provide the output of:
> 
> ./discovery.php -h HOSTNAME -d -m os
> ./poller.php -h HOSTNAME -d -r -m system,os

root@server2:/opt/librenms# ./discovery.php -h comsave-amsterdam -d -m os
LibreNMS 2014.master Discovery

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
SQL[SELECT revision FROM `dbSchema`] 
SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE 'comsave-amsterdam' ORDER BY device_id DESC] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '8'] comsave-amsterdam 8 generic DEBUG: SNMP Auth options =  -v2c -c public
/usr/bin/snmpget -v2c -c public -Ovq -M /opt/librenms/mibs udp:comsave-amsterdam:161 SNMPv2-MIB::sysDescr.0
RS123w

DEBUG: SNMP Auth options =  -v2c -c public
/usr/bin/snmpget -v2c -c public -Ovqn -M /opt/librenms/mibs udp:comsave-amsterdam:161 SNMPv2-MIB::sysObjectID.0
.1.3.6.1.4.1.272.4.201.82.78.79.48.0.0

| RS123w | .1.3.6.1.4.1.272.4.201.82.78.79.48.0.0 | DEBUG: SNMP Auth options =  -v2c -c public
/usr/bin/snmpget -v2c -c public -Osqnv -M /opt/librenms/mibs udp:comsave-amsterdam:161 ENTITY-MIB::entPhysicalMfgName.1
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: .1.3.6.1.2.1.47.1.1.1.1.12.1


DEBUG: SNMP Auth options =  -v2c -c public
/usr/bin/snmpget -v2c -c public -Osqnv -m NETONIX-SWITCH-MIB -M mibs:mibs/netonix/ udp:comsave-amsterdam:161 firmwareVersion.0
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: .1.3.6.1.4.1.99999.1.0


DEBUG: SNMP Auth options =  -v2c -c public
/usr/bin/snmpget -v2c -c public -Oqv -M /opt/librenms/mibs udp:comsave-amsterdam:161 1.3.6.1.4.1.674.10895.3000.1.2.100.1.0
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: iso.3.6.1.4.1.674.10895.3000.1.2.100.1.0


DEBUG: SNMP Auth options =  -v2c -c public
/usr/bin/snmpget -v2c -c public -Oqv -M /opt/librenms/mibs udp:comsave-amsterdam:161 .1.3.6.1.4.1.39165.1.6.0
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: iso.3.6.1.4.1.39165.1.6.0



OS: DEBUG: SNMP Auth options =  -v2c -c public
/usr/bin/snmpget -v2c -c public -Ovq -M /opt/librenms/mibs udp:comsave-amsterdam:161 SNMPv2-MIB::sysDescr.0
RS123w

DEBUG: SNMP Auth options =  -v2c -c public
/usr/bin/snmpget -v2c -c public -Ovqn -M /opt/librenms/mibs udp:comsave-amsterdam:161 SNMPv2-MIB::sysObjectID.0
.1.3.6.1.4.1.272.4.201.82.78.79.48.0.0

| RS123w | .1.3.6.1.4.1.272.4.201.82.78.79.48.0.0 | DEBUG: SNMP Auth options =  -v2c -c public
/usr/bin/snmpget -v2c -c public -Osqnv -M /opt/librenms/mibs udp:comsave-amsterdam:161 ENTITY-MIB::entPhysicalMfgName.1
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: .1.3.6.1.2.1.47.1.1.1.1.12.1


DEBUG: SNMP Auth options =  -v2c -c public
/usr/bin/snmpget -v2c -c public -Osqnv -m NETONIX-SWITCH-MIB -M mibs:mibs/netonix/ udp:comsave-amsterdam:161 firmwareVersion.0
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: .1.3.6.1.4.1.99999.1.0


DEBUG: SNMP Auth options =  -v2c -c public
/usr/bin/snmpget -v2c -c public -Oqv -M /opt/librenms/mibs udp:comsave-amsterdam:161 1.3.6.1.4.1.674.10895.3000.1.2.100.1.0
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: iso.3.6.1.4.1.674.10895.3000.1.2.100.1.0


DEBUG: SNMP Auth options =  -v2c -c public
/usr/bin/snmpget -v2c -c public -Oqv -M /opt/librenms/mibs udp:comsave-amsterdam:161 .1.3.6.1.4.1.39165.1.6.0
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: iso.3.6.1.4.1.39165.1.6.0



SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='',`last_discovered_timetaken` ='0.130' WHERE `device_id` = '8'] Discovered in 0.130 seconds


SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','comsave-amsterdam','1445373292.3093','0.180','1')] ./discovery.php comsave-amsterdam 2015-10-20 22:34:52 - 1 devices discovered in 0.180 secs
MySQL: Cell[1/0s] Row[1/0s] Rows[1/0s] Column[0/0s] Update[1/0.05s] Insert[1/0.04s] Delete[0/0s]

root@server2:/opt/librenms# ./poller.php -h comsave-amsterdam -d -r -m system,osLibreNMS 2014.master Poller

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'comsave-amsterdam' ORDER BY `device_id` ASC] 
SQL[SELECT * FROM `devices` WHERE `device_id` = '8'] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '8'] comsave-amsterdam 8 generic 

SQL[INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('3','0','100','','','','8',NOW())] Unpingable
SQL[SELECT * FROM device_groups] 
SQL[SELECT DISTINCT(alert_schedule.schedule_id) FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '8' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1] 
SQL[SELECT * FROM device_groups] 
SQL[SELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '8' ) || alert_map.target = '8'  )] 

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','comsave-amsterdam','1445373329.2804','0.626','1','server2\n')] ./poller.php comsave-amsterdam 2015-10-20 22:35:29 - 1 devices polled in 0.626 secs

MySQL: Cell[1/0s] Row[2/0s] Rows[4/0s] Column[0/0s] Update[0/0s] Insert[2/0.05s] Delete[0/0s]


-- 
Niels Raijer
niels@fusix.nl

**Comment by laf** [comment]
Thanks @nielsraijer and sorry for the delay on this. The poller output doesn't look complete.

If possible, can we get access to at least one of these units so we can get what we need? If so, please email team AT librenms.org. I'm not going to get chance to take a look at this for probably a week but someone else might pick it up in the meantime.

**Comment by nielsraijer** [comment]
Hi,

Of course. I will send a mail to the team address explaining how to access one of these routers.

Thanks so far!

Niels


> On 28 okt. 2015, at 23:09, Neil Lathwood <notifications@github.com> wrote:
> 
> Thanks @nielsraijer and sorry for the delay on this. The poller output doesn't look complete.
> 
> If possible, can we get access to at least one of these units so we can get what we need? If so, please email team AT librenms.org. I'm not going to get chance to take a look at this for probably a week but someone else might pick it up in the meantime.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
Niels Raijer
niels@fusix.nl

**Comment by Rosiak** [comment]
Mailed them regarding their logo.

**Comment by laf** [comment]
Will be merged shortly.

If you need more from this then we may need access to a device.
