### ISSUE TITLE
dashboard widgets should be able to be applied to groups

### ISSUE THREAD

**Issue by cusco** [librenms/librenms#2179]
Hi,

So I just created a group with a bunch of devices...

Now I would like to create a dashboard with only the devices in this group

Widgets such as: Availability-map; Device-summary; Top-devices; Top-interfaces; Eventlog (and possible others) should be able to filter for a single group of devices...?

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #159](https://github.com/librenms/librenmsv2/issues/159) via [**ZenHub**](https://www.zenhub.com/)

**Comment by superchunk2000** [comment]
This would be a very useful feature.
