### ISSUE TITLE
Brocade ServerIron / ADX update for CPU and RAM

### ISSUE THREAD

**Issue by xbeaudouin** [librenms/librenms#2180]
Hi,

Check the following update on my fork :: 

https://github.com/xbeaudouin/librenms/commit/25206115e93721ace903a135803734351652296d

It will add ServerIron XL and Brocade ADX memory pool and CPU usage.

**Comment by laf** [comment]
Thanks @xbeaudouin but we would need this submitting as a pull request.

**Comment by laf** [comment]
Closing this.

Please feel free to submit a pull request.
