### ISSUE TITLE
Disk LibreNMS

### ISSUE THREAD

**Issue by fran-nlt** [librenms/librenms#2181]
Hello!
I have a question.
When disk space of librenms is full, the system will stop store information or overwrite the old information

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

It depends.
Rrd is fixed size so it wont go bigger the more data you store, however if you're out of space you obviously cant add new devices.

If your entire OS runs out of space, all sort of funky things will happen anyways.


On October 20, 2015 4:41:01 PM GMT+02:00, fran-nlt <notifications@github.com> wrote:
>Hello!
>I have a question.
>When disk space of librenms is full, the system will stop store
>information or overwrite the old information
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2181
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5MhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikgPGYwb0Bs
aWJyZW5tcy5vcmc+BQJWJlcBAAoJEJMZKtVWOFzB6zEP/2pShB6a5rssrC5u0GNe
xvv+WfahkqMd79pjosg3JrjiI96RYd/v0QpW2srbxP2inyvtsJJg40YJMNY5FdC5
pLs7l/5jgHbbNS4ApDm1x86TDN5/pBLQIdBbazBs3LSfeytl5ffRfh7I8CgrmKQp
dr0HbD9k+i+Q8hHg2FzJWEXic5RcGVBTGoCTnmYpAGYblIIDiR2YkYLJIj7K44TR
+YdjuSe7q/fIRjSa6y2VKUDOA6wZrYZdN7ceTwqIU84fUCN32CrY39TjQMlyZ5Hr
fin9sQN1AQL8644R3jiF6a9IRZiFJgRL2bI3UTCoFx/3jPWMu2ASMkQH8Ti3j/nw
rH8+7uQM2Pr9O0W7GNYuv1yfr9p/QV5SayjlFYJvXOU0oU7c96SjNKta4xaMOPHH
M6jB16D8w+KDi/hDWdzdjaacHvl09SuNcYBBZOOGk63cid0JTPc5XR9S3bCP4zpY
LxcgbKK/F4uR4E0B/xFx7PxxUeIgB4yVa1z4Z4Z9ygPbuJixeWCoE/8rsVVvHG6l
TbDu6v6fiM95vTamhnCa2s0baotR5bEowpuyQxT396KN5CSe0MYbPN1myEtclE4O
dytckbWiiKIMDnQ/DRJyUYSBgmg2+gvQ3GqwZxvIEYr1hdoyjXxNJ2trgG8nQ8rU
ocC4860plxH5MOPIK2Ey6kNk
=2E6I
-----END PGP SIGNATURE-----

**Comment by fran-nlt** [comment]
Thanks!
Close Please
