### ISSUE TITLE
Netonix MIB Update

### ISSUE THREAD

**Issue by mayheart** [librenms/librenms#2187]
PR1476 added in support for Netonix WISP switches.

It has since broke with version 1.3 of their software, as they got an official PIN now.

version 1.3 mib:
http://forum.netonix.com/firmware/NETONIX-SWITCH-MIB.dat

**Comment by mayheart** [comment]
Still not working 100%. Discovery sees the firmwareVersion.0 value with the new MIB but the device still says "Generic"

Discovery: http://pastebin.com/hVyUD9wg
Poller: http://pastebin.com/ST6vfxFV

Any points on what could be wrong?

**Comment by laf** [comment]
We will need to add some additional code to update detection as adding a new MIB won't change the way that works.

**Comment by murrant** [comment]
The MIB at the URL above has been updated to include a proper enterprise ID.  Please update the MIB in LibreNMS and detection will work.  (I tested this on my local instance)

**Comment by ehk20** [comment]
It's now detected as 'Netonix' but it's not graphing cpu/memory and other interesting stuff (like fan speed, voltage and poe for example). 

Espen
