### ISSUE TITLE
Distro script diswork

### ISSUE THREAD

**Issue by valentin2105** [librenms/librenms#2190]
Hello,

I use LibreNms from few month and really like it,

But I have a small problem to get the Distro of my Linux's servers,

The distro script downloaded on the repo, get this error on Librenms :

![selection_001](https://cloud.githubusercontent.com/assets/12403145/10679292/6911dd16-7963-11e5-81eb-ac74773e61bd.png)

Have you an idea ?

Thanks for this awesome application.

**Comment by laf** [comment]
Have you made /usr/local/bin/distro executable?

If so, can you run it manually on the command line of the linux server you are monitoring and paste the full output.

**Comment by valentin2105** [comment]
Thanks for you answer,

Yeah, it is executable :

![selection_001](https://cloud.githubusercontent.com/assets/12403145/10685050/a4e42384-79a0-11e5-88c9-621037447ee1.png)

**Comment by laf** [comment]
Check your snmpd.conf file, it should look like:

`extend .1.3.6.1.4.1.2021.7890.1 distro /usr/local/bin/distro`

**Comment by valentin2105** [comment]
I have exactly the same thinks on me snmpd.conf !

**Comment by laf** [comment]
Can you post your snmpd.conf (change communities). The error you get above is probably related to something in snmpd.conf as Debian detection should be perfectly fine.

**Comment by f0o** [comment]
'Exec format error' is known to me as architecture mixup. Is your snmpd 32bit and your bash 64bit ?

I only know that error string from multiarch crosscompile fun...

**Comment by valentin2105** [comment]
My snmpd.conf : 

``` com2sec readonly  default         public
group MyROGroup v2c        readonly
view all    included  .1                               80
access MyROGroup ""      any       noauth    exact  all    none   none
syslocation Your Country 
syscontact Admin <admin@email.com>
#Distro Detection
extend .1.3.6.1.4.1.2021.7890.1 distro /usr/local/bin/distro ```

I have installed snmp from apt-get on an x64_86 Debian 8, so I think no problem ?

**Comment by laf** [comment]
I'm not sure what this could be :(

**Comment by f0o** [comment]
I must check my installs when home

**Comment by f0o** [comment]
@laf I really think its the extend line. Snmpd has 2 different params for binaries and scripts afaik.
Can you double check that please? I'm currently on the way across berlin back home heh

**Comment by valentin2105** [comment]
I just paste your extend line in my snmpd.conf, it is exactly the same, and the the distro script work in Observium.
It's really strange ^^

**Comment by laf** [comment]
@valentin2105 Whilst I'm sure it doesn't make a difference can you try replacing the first line of the distro script with:

`#!/usr/bin/env bash`

**Comment by valentin2105** [comment]
Thanks a lot guy ! it's work !

I <3 libreNMS ! =)

**Comment by laf** [comment]
Thanks for confirming @valentin2105. I've submitted a PR to fix this.
