### ISSUE TITLE
the different devices can't allow to add?

### ISSUE THREAD

**Issue by alex1528** [librenms/librenms#2191]
hi,
here have some devices, use the same ip, with the different snmp port
got this error:
Adding host x.x.x.x community public port 33003 using udp
Already got host x.x.x.x

maybe thie issue related of the rrd per device, it's use the ip to create the device of rrd directory.

sorry, description not clear

**Comment by laf** [comment]
We don't support adding devices with the same name I'm afraid even if the port is different.

You will need to create a new hostname pointing to the same IP to do what you need.

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Perhaps worth to mention that you could host a poller-maschine past the NAT to monitor all the devices as well.
But that really depends on your overall situation.



On October 23, 2015 10:21:48 AM GMT+02:00, Neil Lathwood <notifications@github.com> wrote:
>We don't support adding devices with the same name I'm afraid even if
>the port is different.
>
>You will need to create a new hostname pointing to the same IP to do
>what you need.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2191#issuecomment-150508426
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5MhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikgPGYwb0Bs
aWJyZW5tcy5vcmc+BQJWKe9rAAoJEJMZKtVWOFzBunoP/2U/VThjT6iyb3E1Wa3a
idKWRwhf70crZ5wWChWeu3i/KcWqcZh0hDyRkO7Eg4plgaAnp1KTYlvJ6ae6sLUp
KPLoQyFuBVUkSPOxjY8ancNU33/KnJ/QoLWUWzg0ngSRXcjmmwTATIKzxNWtGJ3g
fPdSwbBn31c8ZMxaT4yOJdrZctkm5Wpdq52Bnv2llP79ivdtddAklNImpPUqq6Ow
9eSBm4S0CRyeIhwItFudPyi8IK/syOF93hQpQMkSvmZ7j95dby0iHsvJj9jUYt12
CWCGHs3mBGDLjw3CS3300zam2gLEJUQjvwJlbwHDVRdEdGEKaaOGXOuDuX4/X5S4
tO+PJktv95FqklsMGRklEBSML19at2GcOa5K4rTXzRVIHmc1qQOj82pGD78tp9jL
v3Lrrn0TkkXDm6wOW6REhi+FubKH/4ICzWCKI4rv9xOWsUulR+mEODc9r062mjZ2
RaiYnmyHuBIbPke9SM0h+1nAbQPqrhMtXlO75RroJ/zWO6LQkELlIBos1d1rwK8N
FuNgT0WuGe1KdL3jN+Q8aXTJryyF4myIYPLr+HJ3qtuaL9LPns1nXzY5k6LR0x7E
7aebUf1u0DvJ6cdAfqTNaQ89YuMPFBFp/Zu6OVgnCZG/+kKTlPOvzACHeSUBTOBd
XO28rUe5kyP6kO0SBuRWWs6j
=DxgD
-----END PGP SIGNATURE-----

**Comment by alex1528** [comment]
why not add support the IP options or description when add device?
like in cacti,it's have a description and hostname, and can use the same hostname of the IP address.
in my cases, the hostname can't to resolve the correct IP address here.

thanks.

**Comment by laf** [comment]
We already support adding by IP address.

**Comment by alex1528** [comment]
sorry, it's missing description for the add devices
![1](https://cloud.githubusercontent.com/assets/12593499/10715803/72c454cc-7b5e-11e5-97dc-cd058bf9ab2c.png)
and,the RRD directory is different on the IP address?
![2](https://cloud.githubusercontent.com/assets/12593499/10715818/dd79c07c-7b5e-11e5-8e49-6fa05ec9eee7.png)

**Comment by laf** [comment]
Yeah we don't support that and that would potentially be a big job and not sure it's something we would look to do.

Anyone else have any thoughts @librenms/core-team

**Comment by laf** [comment]
Keep tagging core-team when I mean @librenms/reviewers

**Comment by Rosiak** [comment]
I'm not a fan of this, but to some extent we could add a option to look at the sysName too?(Even though the business case for this change is very poor). I don't think we should take it further than this.

**Comment by alex1528** [comment]
I don't think so, if the device is more up,I do not believe that each device is certainly not independent of the IP address.

**Comment by laf** [comment]
Sorry I'm not 100% on what you mean by that last reply.

**Comment by alex1528** [comment]
Sorry, poor english. i want to use chinese. :(
so, each device uses a separate IP address ,it's unrealistic, if not using DNS to separation the devices.
in my case, have a lot of the devices in NAT Env, by only use one public ip address for those devices. it's use the same ip address, with the different snmp port per devices.

**Comment by laf** [comment]
Thanks for clarifying :)

I'm not sure this is something we will change, we already have two options that address this and adding further code in to allow duplicates is just not how the base code works :(

1. Use hostnames that point to the same IP but with different ports.
2. Setup a distributed poller behind the nat device which will poll all of those devices.

**Comment by alex1528** [comment]
Thank you for listening to me talk :)
If available that, I will test...

**Comment by laf** [comment]
No problem.

#1 is all controlled by yourself

#2 We have docs on how to set this up: http://docs.librenms.org/Extensions/Distributed-Poller/

**Comment by laf** [comment]
Closing, feel free to re-open if you have any further questions.
