### ISSUE TITLE
Availability-map widget is smaller than map size

### ISSUE THREAD

**Issue by paszczus** [librenms/librenms#2192]
![nmsava](https://cloud.githubusercontent.com/assets/1582475/10690665/8ff0e894-7983-11e5-89b3-85903f8510b0.png)

**Comment by SaaldjorMike** [comment]
You can edit the size of the tiles in widget settings.

**Comment by paszczus** [comment]
Ah, indeed. So there is no auto-resize function :) thanks!

**Comment by f0o** [comment]
Not yet that is :)

Hope to see an update that ties the actual size of the widget with the gridster system we use for plugins. Volunteers for coding it? :D

**Comment by laf** [comment]
Will be more responsive in v2
