### ISSUE TITLE
Adding Cisco CallManager metrics

### ISSUE THREAD

**Issue by adaniels21487** [librenms/librenms#2196]
Hi All,
I have been building some Discovery/Poller modules that query a Cisco Call Manager server via PerfMon, just like RTMT.

I have 3 modules so far which gather various metrics:
- CUCM-Basic
  - DB Replication State
  - Service Initialization State
  - Calls Active + Video + Encrypted
  - Annunciator Resources - Total / Active
  - MTP Resources - Total / Active
  - Transcoder Resources - Total / Active
  - VC Bridge Resources - Total / Active
  - VC Confereces - Total / Active
  - Multicast MOH - Total / Active
  - Unicast MOH - Total / Active
  - SW Conferencing Resources - Total / Active
  - HW Conferencing Resources - Total / Active
  - Conferences Active - SW / HW
- CUCM-ELCAC - Bandwidth Per Location
  - Voice - Total / Active
  - Video - Total / Active
  - Immersive Video - Total / Active
- CUCM-SIP - Per Trunk
  - Total Calls
  - Video Calls

I am working on adding:
- H323 Trunks
- \Cisco CallManager System Performance\CallsRejectedDueToThrottling
- \Cisco Hunt Pilots
  - CallsQueued
  - QueueCallsAbandoned
  - QueueCallsRingNoAnswer
- Gateways - Investigate what is available (Voice/Video?)
  - MGCP
    - FXS
    - FXO
    - T1
    - PRI
  - H323
- Device Registration - Graph on Overview Tab
  - Phones
  - Gateways
  - Media Resources
  - Other Stations
- Phones - Graph on Overview Tab
  - Registered
  - Partially Registered
  - Failed Registrations
- Services - New Tab
  - Status
  - Uptime

The question is: what else.
What would be helpful to monitor that is not on this list.

Let me know and I'll add it..

Thanks,
Aaron

**Comment by laf** [comment]
I don't personally have a need for these but thank you for putting the effort in to get support added :)

**Comment by joseaugustocardoso** [comment]
sounds very good. 
Share with us the progress. :)

**Comment by jcounsell1222** [comment]
it would be helpful to view the active calls on a voice router.

**Comment by adaniels21487** [comment]
Hi @jcounsell1222,
How do you get calls into your voice router and from there into Call Manager?

This module tracks MGCP connections and SIP/H323 trunks from a Call Manager Point of view and LibreNMS already tracks ISDN PRI channels in use on a voice router.

Thanks,
Aaron

**Comment by jcounsell1222** [comment]
@adaniels21487 i am not really part of the Voice team, more of a network engineer, so we take care of the voice routers but dont configure them for the voice side. i was looking over the libre GUI and i was not able to figure out how to track the calls and alert on them if there was an issue. is that something that can be done? i assume that when you say it tracks the PRI if it stops showing calls over the PRI we can alert on that?

**Comment by adaniels21487** [comment]
Hi @jcounsell1222. If you send me your router config (lists at daniels.id.au) I can let you know which module your request belongs in. Currently neither module alerts on trunks, they only do utilisation.

Aaron

**Comment by joseaugustocardoso** [comment]
I have this need too

**Comment by nktl** [comment]
+1

**Comment by adaniels21487** [comment]
Thanks for the prompt. I'll look at cleaning this up over the next month or so..

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-adding-cisco-callmanager-metrics/894

**Comment by jordanrkirby** [comment]
Hi - was there any progress made on this?
We have a fairly large estate of managed CUCM/CUC/CUXN/Expressway systems that we would like to monitor with LibreNMS.

I'd really like to have a copy of the code in any state so I've got something to work from rather than starting from scratch.

Thanks

**Comment by nktl** [comment]
Have you still got the code somewhere by any chance? It would be super useful to have it.
