### ISSUE TITLE
Port search combination ignored + up don't show any results

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#2201]
if I want to see all ignored but in state up ports, there isn't any result.
http://imgur.com/k0bPnRb

**Comment by laf** [comment]
@vitalisator I've submitted a PR to fix this but I'm not sure if we will merge or not. It looks like ports that are UP are specific about leaving out ignored, deleted or disabled ports. If we fix this for you it may just open up queries from people saying we don't want to see those types of ports when they select to see all up ports.
