### ISSUE TITLE
Syslog-ng is only showing '%' in the program field and no message in the 'msg' field.

### ISSUE THREAD

**Issue by johngriegerjr** [librenms/librenms#2205]
Syslog-ng is displaying syslog messages properly from other devices but not from a Cisco 2960G switch.  Here is the output from the database showing what is stored.  I did a tcpdump on the LibreNMS server and can see the full syslog messages coming from the switch but the messages are not making it into the MySQL database.

mysql> select * from syslog where device_id=2;
+-----------+----------+----------+--------+------+---------------------+---------+------+------+
| device_id | facility | priority | level  | tag  | timestamp           | program | msg  | seq  |
+-----------+----------+----------+--------+------+---------------------+---------+------+------+
|         2 | local6   | notice   | notice | b5   | 2015-10-25 20:59:32 | %       |      | 1357 |
|         2 | local6   | notice   | notice | b5   | 2015-10-25 21:11:16 | %       |      | 1422 |
|         2 | local6   | notice   | notice | b5   | 2015-10-25 21:21:32 | %       |      | 1478 |
|         2 | local6   | info     | info   | b6   | 2015-10-25 21:22:10 | %       |      | 1482 |
|         2 | local6   | notice   | notice | b5   | 2015-10-25 21:22:41 | %       |      | 1486 |
|         2 | local6   | err      | err    | b3   | 2015-10-25 21:23:08 | %       |      | 1487 |
|         2 | local6   | info     | info   | b6   | 2015-10-25 21:23:17 | %       |      | 1488 |
|         2 | local6   | err      | err    | b3   | 2015-10-25 21:23:41 | %       |      | 1489 |
|         2 | local6   | notice   | notice | b5   | 2015-10-25 21:25:01 | %       |      | 1501 |
|         2 | local6   | err      | err    | b3   | 2015-10-25 21:25:04 | %       |      | 1502 |
|         2 | local6   | notice   | notice | b5   | 2015-10-25 21:40:20 | %       |      | 1579 |
|         2 | local6   | notice   | notice | b5   | 2015-10-25 22:05:46 | %       |      | 1694 |
+-----------+----------+----------+--------+------+---------------------+---------+------+------+
12 rows in set (0.00 sec)

**Comment by laf** [comment]
Just given this a quick test and it seems ok for me.

Can you provide:

IOS version (feel free to email me neil AT librenms.org if that's sensitive).
Syslog-ng config
Switch config for logging and timestamp setup (again email if needs be).

**Comment by johngriegerjr** [comment]
Hi Neil,

Here's the info....

# IOS Version:
Switch   Ports     Model              SW Version          SW Image                 
\------     \-----       \-----                              \----------                   \----------               
*    1      24          WS-C2960G-24TC-L   15.0(2)SE6            C2960-LANBASEK9-M    

# Syslog-ng config:
@version: 3.5
@include "scl.conf"
@include "\`scl-root`/system/tty10.conf"

\# First, set some global options.
options {
        chain_hostnames(off);
        flush_lines(0);
        use_dns(no);
        use_fqdn(no);
        owner("root");
        group("adm");
        perm(0640);
        stats_freq(0);
        bad_hostname("^gconfd$");
};

########################
\# Sources
########################
source s_sys {
       system();
       internal();
};

source s_net {
        tcp(port(514) flags(syslog-protocol));
        udp(port(514) flags(syslog-protocol));
};

########################
\# Destinations
########################
destination d_librenms {
        program("/opt/librenms/syslog.php" template ("$HOST||$FACILITY||$PRIORITY||$LEVEL||$TAG||$YEAR-$MONTH-$DAY $HOUR:$MIN:$SEC||$MSG||$PROGRAM\n") template-escape(yes));
};

########################
\# Log paths
########################
log {
        source(s_net);
        source(s_sys);
        destination(d_librenms);
};

###
\# Include all config files in /etc/syslog-ng/conf.d/
###
@include "/etc/syslog-ng/conf.d/*.conf"


# Switch config:
service timestamps log datetime localtime
logging buffered errors
logging trap debugging
logging facility local6
logging host <librenms IP address>

**Comment by laf** [comment]
Thanks, I'll replicate tomorrow and give it a whirl.

**Comment by laf** [comment]
@johngriegerjr That works for me still :( Only difference is I tested against a 12.x release and on CentOs 7 for the syslog box, looks like you are using Ubuntu / Debian?

For more debugging, can you edit syslog.php and uncomment:

`#logfile($line);`

You will need to then restart syslog, generate a new syslog message and checking /opt/librenms/logs/librenms.log and you should see something like:

`1.1.1.1||local6||notice||notice||b5||2015-10-28 20:47:44||%SYS-5-CONFIG_I: Configured from console by neil.lathwood on vty0 (1.1.1.1)||`

**Comment by johngriegerjr** [comment]
I think the /opt/librenms/syslog.php file might be the problem. Mine doesn't have the #logfile($line); entry and when I put it in (without the hash tag) and restarted syslog-ng I didn't see any syslog messages in the /opt/librenms/logs/librenms.log file.  I'm using the Ubuntu virtual machine that I downloaded from the LibreNMS site

VirtualBox Appliance
Ubuntu 14.04.1 LTS tarball (1.2G)
md5sum: fbbc266a96899b1c1d94ce67b7c72d2d
sha256sum: 514c4b456e29d604786ab404f1814209206a42fee9973320551926086ee5a9e0

#/opt/librenms/syslog.php

root@ubuntu-librenms:~# cat /opt/librenms/syslog.php 
#!/usr/bin/env php
<?php

/**
 * Observium
 *
 *   This file is part of Observium.
 *
 * @package    observium
 * @subpackage syslog
 * @author     Adam Armstrong <adama@memetic.org>
 * @copyright  (C) 2006 - 2012 Adam Armstrong
 *
 */

require 'includes/defaults.inc.php';
require 'config.php';
require 'includes/definitions.inc.php';
require_once 'includes/syslog.php';
require_once 'includes/dbFacile.php';
require_once 'includes/common.php';
require_once 'includes/functions.php';
$i = "1";

$s = fopen('php://stdin','r');
while ($line = fgets($s)) {
    #logfile($line);
    list($entry['host'],$entry['facility'],$entry['priority'], $entry['level'], $entry['tag'], $entry['timestamp'], $entry['msg'], $entry['program']) = explode("||", trim($line));
    process_syslog($entry, 1);
    unset($entry);
    unset($line);
    $i++;
}
root@ubuntu-librenms:~#

**Comment by laf** [comment]
Just to be sure. Please run ./daily.sh to update. chmod 777 librenms.log and try again.

**Comment by johngriegerjr** [comment]
I haven't solved this but I think I found the problem? It's with the way the Cisco switch is sending the syslog messages.  Here's what I did to come to this conclusion.

1. Stopped the syslog-ng service ```'service syslog-ng stop'```
2. Enabled syslog debugging ```'syslog-ng -Fevd'```
3. Looked for differences in the way the syslog messages were formatted.

**Cisco Switch Syslog Not Working:**
Incoming log entry; line='<179>```260:``` Oct 29 09:13:10: %LINK-3-UPDOWN: Interface GigabitEthernet0/3, changed state to down'

**Cisco ASA Syslog Working:**
Incoming log entry; line='<164>Oct 29 2015 09:13:17: %ASA-4-106023: Deny icmp src Outside:216.143.242.126 dst inside:192.168.168.6 (type 5, code 1) by access-group "Outside_access_in" [0x0, 0x0]\x0a'

As you can see the switch is sending syslogs with three numbers followed by a colon then the date timestamp.  I thought the three numbers were the problem so I looked for a way to remove them. What I found is they are a syslog counter. I turned them off on the switch by using the ```'no logging message-counter syslog'``` command. Unfortunately that didn't work.

This is what the logs look like after removing the syslog counter:

**Cisco Switch Syslog Still Not Working:**
Incoming log entry; line='<179>```:``` Oct 29 09:46:29: %LINK-3-UPDOWN: Interface GigabitEthernet0/11, changed state to down'

**Cisco ASA Syslog Working:**
Incoming log entry; line='<164>Oct 29 2015 09:46:32: %ASA-4-411001: Line protocol on Interface GigabitEthernet0/0, changed state to up\x0a'

As you can see although the switch stopped sending the syslog counter it is still inserting a colon before the date timestamp and I think this is causing the problem.  Is there a way I can change the way LibreNMS accepts the syslogs to accept this?

Thank you,
John

**Comment by laf** [comment]
Have you still got logfile($line); uncommented?

Also, librenms.log is the default log file but if you've changed it then check the new log file.

If this is also now correct then you really should see something in the logs after restarting syslog-ng. We really need to see the output from the logfile() function so we can replicate this.

**Comment by johngriegerjr** [comment]
I was putting logfile($line); at the end of the syslog.php file previously, outside of the curly braces, which explains why I wasn't seeing anything in the /opt/librenms/logs/librenms.log. I didn't see the commented first line in the while statement (#logfile($line);) before. Anyways I was able to get the logfile() function to log to the librenms.log file.  Here is what it has in it.

1.1.1.1||local4||warning||warning||a4||2015-11-05 09:51:30||Deny icmp src Outside:1.2.3.4 dst inside:5.6.7.8 (type 5, code 1) by access-group \"Outside_access_in\" [0x0, 0x0]||%ASA-4-106023

2.2.2.2||local7||notice||notice||bd||2015-11-05 09:51:32||%LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/3, changed state to down||

2.2.2.2||local7||err||err||bb||2015-11-05 09:51:33||%LINK-3-UPDOWN: Interface GigabitEthernet0/3, changed state to down||

2.2.2.2||local7||err||err||bb||2015-11-05 09:51:35||%LINK-3-UPDOWN: Interface GigabitEthernet0/3, changed state to up||

2.2.2.2||local7||notice||notice||bd||2015-11-05 09:51:36||%LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/3, changed state to up||

1.1.1.1||local4||warning||warning||a4||2015-11-05 09:51:46||Deny icmp src Outside:1.2.3.4 dst inside:5.6.7.8 (type 5, code 1) by access-group \"Outside_access_in\" [0x0, 0x0]||%ASA-4-106023

1.1.1.1||local4||warning||warning||a4||2015-11-05 09:51:54||Deny icmp src Outside:1.2.3.4 dst inside:5.6.7.8 (type 5, code 1) by access-group \"Outside_access_in\" [0x0, 0x0]||%ASA-4-106023

ubuntu-librenms||syslog||notice||notice||2d||2015-11-05 09:52:00||syslog-ng shutting down; version=\'3.5.3\'||syslog-ng

1.1.1.1 is an ASA firewall that I'm seeing the logs correctly from
2.2.2.2 is the 2960G switch that only shows % in the syslog messages

Thanks for your patience!!

**Comment by markuspachali** [comment]
If it helps:
I'd the same problem. In Cisco IOS the name of the "application" starts with a "%", and it seems that somewhere in the processing chan syslog-ng -> PHP-Script of LibreNMS -> MySQL the "%" is handled in a way that causes the described problem. If I musst guess "%" is not escaped at a position where it should be.
To handle that I'd written a little filter in syslog-ng to replace every "%" with nothing, and after that the messages appeared in the database.

**Comment by johngriegerjr** [comment]
@markuspachali 

Thank you Markus! Your work around has fixed the issue for now. I'm now seeing the syslog messages in the db and on the webpage. Here is what my '/etc/syslog-ng/syslog-ng.conf' file looks like for others that may need to do this.

@version: 3.5
@include "scl.conf"
@include "`scl-root`/system/tty10.conf"

\# First, set some global options.
options {
        chain_hostnames(off);
        flush_lines(0);
        use_dns(no);
        use_fqdn(no);
        owner("root");
        group("adm");
        perm(0640);
        stats_freq(0);
        bad_hostname("^gconfd$");
};

########################
\# Sources
########################
source s_sys {
       system();
       internal();
};

source s_net {
        tcp(port(514) flags(syslog-protocol));
        udp(port(514) flags(syslog-protocol));
};

########################
\# Destinations
########################
destination d_librenms {
        program("/opt/librenms/syslog.php" template ("$HOST||$FACILITY||$PRIORITY||$LEVEL||$TAG||$YEAR-$MONTH-$DAY $HOUR:$MIN:$SEC||$MSG||$PROGRAM\n") template-escape(yes));
};


```########################
\# Replace %
########################

rewrite r_rewrite_subst{
    subst("%", "", value("MESSAGE"), flags("global"));
};
```
########################
\# Log paths
########################
log {
        source(s_net);
        source(s_sys);
```        rewrite(r_rewrite_subst); ```
        destination(d_librenms);
};

###
\# Include all config files in /etc/syslog-ng/conf.d/
###
@include "/etc/syslog-ng/conf.d/*.conf"

**Comment by mkratz** [comment]
I had this same issue too, thanks @johngriegerjr I applied the same changes that you did and it works perfectly well.

**Comment by murrant** [comment]
This must be some sort of issue with escaping the %?
What the rewrite does is replace "%" with "" in the message data.

**Comment by murrant** [comment]
@mkratz @johngriegerjr Do you guys happen to be running PHP 7?  Can you test the pull request I just sent? (you can just apply the changes to include/syslog.php)
