### ISSUE TITLE
Problem with Kyocera and Toner's graphs

### ISSUE THREAD

**Issue by valentin2105** [librenms/librenms#2206]
Hi,

Sorry for open some issues, but I'm migrating all my observium's device to LibreNMS  !

Everythings work fine but I have a problem with my printer's toners.

Printers are some Kyocera FS-C2126MFP, who work fine with Observium.

I'm not an snmp master, so debugging is quite difficult for me ...

- discovery.php -h kyocera -d -m toner : http://pastebin.com/FrYquLAd

- poller.php -h kyocera -d -r -m toner : http://pastebin.com/wmy9FAm5

The toner's graph say "error drawing graph".

( I migrate all my RRD folder from observium).

Thanks a lot for you software and your help !

**Comment by laf** [comment]
@valentin2105 

Do you have $config['enable_printers'] set to enabled in your config?

From the output it doesn't look like it. If you enable that it will give you some more debug in ./discovery so if it still doesn't work please re-run the discovery command and post here.

**Comment by valentin2105** [comment]
Hi,
I haven't enable printers in config file,

After doing this, the toner's graph disworks again, and the output of discovery don't look very diffrents, 

Here the output of disovery : 
http://pastebin.com/T8rG9ZC9

Thanks a lot !

**Comment by laf** [comment]
@valentin2105 

What's the config option you set exactly? The code for the toner discovery outputs Toner : before it does anything else and I'm not seeing that in your discovery output.

**Comment by valentin2105** [comment]
@laf 
This is the config option I set in /opt/librenms/config.php

$config['enable_printers']; 

It is correct ?

**Comment by laf** [comment]
@valentin2105 

Close:

`$config['enable_printers'] = true;`

**Comment by valentin2105** [comment]
Thanks @laf ...
I need to read better your documentation  !

Thanks for you reactivity !

**Comment by laf** [comment]
No probs @valentin2105 does it work now?

**Comment by valentin2105** [comment]
Perfectly with my 2 kyocera ! =)
My 38 devices are on LibreNMS Now !

**Comment by laf** [comment]
Awesome :)
