### ISSUE TITLE
Feature Request: Set default dashboard for new users

### ISSUE THREAD

**Issue by simonholmbring** [librenms/librenms#2216]
When creating a new shared dashboard, it would be great to be able to set this dashboard as default for new users, so the new user doesn't see the "placeholder-widget" in the dashboard.

I propose that this can either be a setting when editing the user, "set default dashboard" - dropdown and select available shared dashboards.
OR
When creating a shared dashboard, have a checkbox "make this dashboard default for new users"?

I'd prefer the first option because it gives flexibility to create different dashboards, and assigning them to users, i.e management-dashboard, servicedesk-dashboard, etc.

**Comment by laf** [comment]
Option 1 seems more logical.

Question on this, are you expecting a shared dashboard to be selected and copied so that the new user can fully update it (it becomes private) or actually share the original one so only one dashboard exists and new users can't update it if it's read-only but can if it's shared writeable?

**Comment by paulgear** [comment]
I think we should have a default dashboard that is used if no others are assigned, and allow admins to customise whether their users get a private or shared dashboard.

**Comment by simonholmbring** [comment]
I would expect the admin to be able to "assign" a dashboard to a user, the user does not need to be able to update this dashboard.

Basically, I'm planning on using this for two purposes.
1. Servicedesk Dashboard with a dummy user on a TV in our NOC
2. Management User to login and check status.

Both users with read only profile, so should not be able to change anything.

**Comment by vizay** [comment]
From an organizational point of view I'd say it's very logical if the admin can specify a shared dashboard as the default dashboard for new users (i.e not private and not editable).

In addition to this, an option for each specific user to change their default dashboard to something else (if allowed by the admin) would give full flexibility around the dashboards.

New users wouldn't have to hit a white wall and waste time figuring out what they want on their dashboard, and at the same time they can modify this once they're more familiar with the system.

At the same time, if the admin only want the users to see one dashboard as default that would still be possible. Typical use case for this would be in larger organizations where you want to make sure that the 1st line and 2nd line are all viewing the same base information, minimizing the risk of something being missed.
