### ISSUE TITLE
Empty Overall Traffic for switches

### ISSUE THREAD

**Issue by atdtn** [librenms/librenms#2217]
In Overview tab, empty overall traffic for snmp devices (switches). For PC with smpd it's working.
On observium overall traffic shows on any device.
![screenshot_27102015_001](https://cloud.githubusercontent.com/assets/12551051/10757830/1336524a-7cb6-11e5-92d2-abe871e7bbe8.png)

**Comment by laf** [comment]
I've removed the observium screenshot as we try and avoid any contact with their product.

I've helped somebody else with similar, I believe some of the interfaces listed are what will cause issues like the management ones.

Try adding those to config.php as bad_if to see. An example:

`$config['bad_if'][] = 'mgmt';`

Once done, re run poller for that device: `./poller.php -h HOSTNAME -d -r -m ports`

If that works, let us know.

**Comment by atdtn** [comment]
$config['bad_if'][] = 'mgmt';
$config['bad_if'][] = 'management';

Run ./poller.php -h 172.16.2.2 -d -r -m ports

Interfaces mgmt and management hide from ports, but graph still empty.
On graph details:
![screenshot_27102015_006](https://cloud.githubusercontent.com/assets/12551051/10758539/9e30a28e-7cba-11e5-9a10-d8e40fa4f618.png)

**Comment by laf** [comment]
Can you right click the graph, get the image url and go to that, add &debug=true and post the output onto dpaste.de and link here please.

**Comment by laf** [comment]
p.s It could be still some other interfaces like default, management- something (can't quite see that last port).

**Comment by atdtn** [comment]
https://dpaste.de/4J1W

**Comment by atdtn** [comment]
The same with Dlink switches
![screenshot_27102015_007](https://cloud.githubusercontent.com/assets/12551051/10759003/7f169900-7cbd-11e5-9b42-aeacd1c02a4f.png)

**Comment by laf** [comment]
@atdtn for the output you sent it could be that no data exists for that port. Would you be able to upload all the rrd files for that host somewhere so we can test?

**Comment by atdtn** [comment]
All rrd files in tgz
https://hdata.eu/index.php/s/o8zIoPE9szv7TDC

**Comment by laf** [comment]
The rrd  port-1029.rrd does look like it's logging no traffic hence that graph is blank.

Can you do the same as you did for that port but with the traffic overview and paste the output onto dpaste.de

**Comment by atdtn** [comment]
I don't see this port (29)  in Ports tab, 28 is last port on x650

**Comment by laf** [comment]
That's just the id of the port and not necessarily a port such as Gi0/29.

If you go to the overview tab, right click on the overview traffic graph, get the url to the graph and go to that whilst adding &debug=true then post that output.

**Comment by atdtn** [comment]
Found it

![screenshot_27102015_008](https://cloud.githubusercontent.com/assets/12551051/10760983/e8fb8b1e-7cc7-11e5-9af1-258fce4d57df.png)

**Comment by laf** [comment]
Need the info from my last post ^^

**Comment by atdtn** [comment]
https://dpaste.de/VsR1

**Comment by laf** [comment]
That looks like the previous output, is that definitely the output from the traffic overview graph rather than a specific port?

**Comment by atdtn** [comment]
port-1029.rrd file for port with index 1029 with name Management,
how i can view overview for this port? i don't see this port in Ports tab, only in ports settings  with oper=down.

**Comment by laf** [comment]
Click Overview for the device, near the bottom right you have Overall traffic (it's in one of your screenshots :))

**Comment by atdtn** [comment]
Then https://dpaste.de/VsR1 it's right output :)

**Comment by laf** [comment]
Wow, something is seriously not right then as that's only attempting one port. In the list, what is the port before that one and can you get me the output for a traffic graph for just that port.

**Comment by atdtn** [comment]
Neil, check your mail, i gave you access to librenms site with this devices.

**Comment by laf** [comment]
@atdtn can you email the output of:

`SELECT * FROM `ports` WHERE `device_id` = 2;`

please.

**Comment by laf** [comment]
Ok this is simply because of:

`$config['device_traffic_descr'][] = '/:\d+/';`

I've been through that same fix for tobiasa before as well :(

So, we either need to remove this from the list of things to filter on as it always seems to affect D-Link and some Extreme stuff. Worst that is going to happen is we will include additional interfaces in the traffic overview graph for a device. If that happens we can get some more specific regexes that filter those rather than having a generic filter.

@librenms/core-team thoughts?
