### ISSUE TITLE
Overview tab.

### ISSUE THREAD

**Issue by atdtn** [librenms/librenms#2218]
It is possible to make Overview tab more user friendly?
not enough summary CPU load graph and normal memory usage graph.
And it would be great make resource usage bar, as observium.

![screenshot_27102015_004](https://cloud.githubusercontent.com/assets/12551051/10758212/94482be0-7cb8-11e5-9b8b-6d4f34cd5c63.png)

**Comment by laf** [comment]
I think we need a bit of a revamp in general. A lot of LIbreNMS is moving along nicely but the WebUI doesn't get much love.

So with this are you referring to summarising the processors so rather than list them all we do an aggregated view?

Using the normal rrdtool graphs for memory pools?

**Comment by atdtn** [comment]
![screenshot_27102015_003](https://cloud.githubusercontent.com/assets/12551051/10758647/67853f78-7cbb-11e5-9c19-072cac78d65e.png)

This small processor ghraph, move above Processors and make it bigger. THe same with memory

**Comment by Alucardfh** [comment]
I agree summarizing CPUs would be beneficial for the readability of the overview page.
And also should give a performance boost by having less graphs to render.

As you can see below having all the core on the overview just clutter the screen

![toomanycpus](https://cloud.githubusercontent.com/assets/1701397/11035229/db3aac46-86e8-11e5-8622-bc57407c0b76.PNG)

**Comment by Rosiak** [comment]
Closing due to #2470 being merged.
