### ISSUE TITLE
Add Geist GBB15 SNMP MIB

### ISSUE THREAD

**Issue by diegonix** [librenms/librenms#2219]
Add Geist GBB15 SNMP MIB
Environment monitor device
*temperature
*umidity
*dew point

has internal sensors and support up to four external sensors.
mib: http://1drv.ms/1k79ebM

**Comment by Rosiak** [comment]
./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -r -f -d -m os
An snmpwalk of the device:
snmpbulkwalk -v2c -c COMMUNITY HOSTNAME .
