### ISSUE TITLE
Add Edge-Core SNMP MIB

### ISSUE THREAD

**Issue by diegonix** [librenms/librenms#2221]
Add Edge-core ECS4610 L3 Switch SNMP MIB support

mib: http://www.edge-core.com/temp/ec_download/1447/ECS4610-50T.zip

**Comment by kamils85** [comment]
Hello,
+1 for adding EdgeCore switches

All requested details below.

[ECS Discovery.txt](https://github.com/librenms/librenms/files/601418/ECS.Discovery.txt)
[ECS Poller.txt](https://github.com/librenms/librenms/files/601419/ECS.Poller.txt)
[ECS SNMPWALK.txt](https://github.com/librenms/librenms/files/601420/ECS.SNMPWALK.txt)
