### ISSUE TITLE
ADD Schneider CP UPS SNMP MIB

### ISSUE THREAD

**Issue by diegonix** [librenms/librenms#2222]
ADD Schneider CP UPS  devices SNMP MIB

mib: http://1drv.ms/208zyTN

**Comment by Rosiak** [comment]
./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -r -f -d -m os
An snmpwalk of the device:
snmpbulkwalk -v2c -c COMMUNITY HOSTNAME .
