### ISSUE TITLE
is_port_valid case sensitivity

### ISSUE THREAD

**Issue by ciscoqid** [librenms/librenms#2223]
In is_port_valid, the ifDescr value is lowercased initially and then checked against the bad_if array with strstr, meaning that the bad_if array contents must be lowercase as well, which is not documented.  I think it would be simpler to remove the strtolower and use stristr instead of strstr.  The same seems to make sense for bad_iftype, which currently checks without any transformation.  The regexp method already appends 'i' to the regex.  If the change is not accepted, then the documentation should indicate only lowercase values should be provided in the bad_if list.

**Comment by laf** [comment]
Sounds like a good idea :)

Is this something you can contribute?
