### ISSUE TITLE
Temperature Sensors

### ISSUE THREAD

**Issue by sarcasym** [librenms/librenms#2224]
I'm testing several different environmental monitors, Watchdog 15 

http://www.itwatchdogs.com/temperature-humidity-climate-monitor-watchdog-15-p71.html 
and 
AVTech Alert 3E http://www.avtech.com/Products/Environment_Monitors/Room_Alert_3E.htm

Neither of which are playing nice when added to LibreNMS.

The MIBs for the Watchdog are downloadable from the device, I can share them if needed, and AVTech MIBs were posted here https://groups.google.com/forum/#!searchin/librenms-project/avtech/librenms-project/_JYqnbo74k4/t9GCUm9yGQAJ

If there is something I can do to assist in getting these added please let me know. Even just a hefty push in a particular direction would be helpful.

Thanks!

**Comment by laf** [comment]
@sarcasym Are you ok with PHP? If so, we can provide some guidance on adding this.

**Comment by sarcasym** [comment]
I'm fairly competent with PHP and what I don't know I can make up.

**Comment by murrant** [comment]
@sarcasym I'm not sure which sensors you went with, but the the Room Alert 3E should be supported now (only for temperature sensors at this time) now.

**Comment by murrant** [comment]
@sarcasym I have added support for other Avtech devices recently.
I can add support for the RoomAlert 3E if you send me an snmpwalk of the device:
`snmpwalk -v 1 -c COMMUNITY DEVICE 1.3.6.1.4.1`

**Comment by sarcasym** [comment]
Is there something I need to do in LibreNMS to import the new device list? I'm not sure I am running version c138093.

**Comment by murrant** [comment]
@sarcasym run ./daily.sh as the librenms user in /opt/librenms.  Probably run ./validate.php after to make sure everything is ok.

http://docs.librenms.org/General/Updating/

**Comment by Rosiak** [comment]
What's the status on this?
