### ISSUE TITLE
Feature Request - Disable Alert Notifications Globally

### ISSUE THREAD

**Issue by Lonecrowe** [librenms/librenms#2360]
Since we don't have any parent/child relationships is an entire site is experiencing issues we have a plethora of alerts coming in via email.  

For example there are some routing issues taking place on the internet today making some of our subnets unreachable so it is constantly flapping and alerting us all day.  Instead of needing to disable manually 20-30 devices I'd like to manually disable the alerts until the problem is done.  

I'd like the option to click a button.  Maybe a widget can be made for this for the dashboard?  A small set of 4-6 buttons each with some form of control that will disable only alerting.  Or have icons for other functions.  Maybe the slider buttons for General alert settings?

**Comment by laf** [comment]
Can do a simple on / off switch if that is of use?

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

You should be able to suppress those alerts by adding an alert-schedule

- - f0o

On 28 October 2015 21:48:39 CET, Roy Fokker <notifications@github.com> wrote:
>Since we don't have any parent/child relationships is an entire site is
>experiencing issues we have a plethora of alerts coming in via email.
>
>For example there are some routing issues taking place on the internet
>today making some of our subnets unreachable so it is constantly
>flapping and alerting us all day.  Instead of needing to disable
>manually 20-30 devices I'd like to manually disable the alerts until
>the problem is done.
>
>I'd like the option to click a button.  Maybe a widget can be made for
>this for the dashboard?  A small set of 4-6 buttons each with some form
>of control that will disable only alerting.  Or have icons for other
>functions.  Maybe the slider buttons for General alert settings?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2360
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5MhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikgPGYwb0Bs
aWJyZW5tcy5vcmc+BQJWMTX2AAoJEJMZKtVWOFzBx7kP/irCUtdlKww6wAeBjG7G
hn4j0yx8hkM7SqNRjVq3uHW4kUqTU6w3lAqF7Bx8+2OD/v2ehPR1PJGEXuL4zxUQ
eNS3N0cc9dXsdp/SNC+Ku5HJ8eChYUXugn4ziMHbcnWiV0nvyollyp2mjbAhpKXI
jYK0GTYxkWcn+gwPzBRIGRP1HzF3n/cfE+vm82coRgCugWQ/L2JajUONTxYBQ73P
kya9LnXKGtWSU7D3IAgVP+Ta8LmipvLEdc2cQwBbAg9JGiJyxjA9cT+lQj731xpf
T7tO9Dy1nHb4gk2uV0t+eeBngjVuhDNL5HhTA2t7YZ7YOsrY2ftSpatZVeObJp9z
K7jdkZkKxjKnmhsDhd7l16C+3qqKRz0MZIyukZ3AR207J82rIKVuTLv0ojbx9VQ1
Kq8zYH2h3qUaC9PBK1VdaAB+EmaOwNRLhZeb6N1lL8CHFJB7EZ2EPjpXHfkEJg1A
dbZhUoq/jFW7L/2scM+1BTHUsT5q9U+BfJlPmrgNN4oFJH+wGjOg8Xt0n3lpRuAU
Ab5qXIAYwf+e+IW90BxKCa4wvm/dMfnskFBZ9604R07gieaE00BA/PFMErQ4nMLx
MLmd28GHCMvED0M1rncl61ksCHVHhYrxZx48gsBwRrNRbuMkaW6nEmZAjZcB/FT7
pLarXMWaaFnvZao5C0niyje2
=o5PW
-----END PGP SIGNATURE-----

**Comment by Lonecrowe** [comment]
Yes just a slider on off would do.  A widget would be nice too of controls to do other functions such as restart apache,  mysql or other services maybe?

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

What's wrong with using the alert-schedule?

- -f0o



On 29 October 2015 16:10:45 CET, Roy Fokker <notifications@github.com> wrote:
>Yes just a slider on off would do.  A widget would be nice too of
>controls to do other functions such as restart apache,  mysql or other
>services maybe?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2360#issuecomment-152209464
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5MhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikgPGYwb0Bs
aWJyZW5tcy5vcmc+BQJWMjd5AAoJEJMZKtVWOFzBCe4P/Rrqz5wIGrFpSo7UjRBf
n5kFHFz32XuZW0KysTI/GO1mPzA30L/ZtYjKCf44PmoOqsUbaf9hBIoduk/L4N4j
Yi3k7nFbLbXeBYu2TIFQAGERXbHG+9O93HbbrGnULF8YX47FQd4EarLWjECBEvjy
nblgdZ2N/VlhSCtnbikCG7L3dgKkF8rzthqlzxGgld9wxQWQtEyUaDX5QJUcaURV
5l3KvxGgzWcOM21wXC/Lw6/drqadfsuzcOKUStqLlbgp+/JjDVivry7CF+AqvNQB
3kE8WdeEBhCyIQ9m5/2i95NJKUC6gUxxDOcx7HJwy0tT1vCxEB5oy2oqWw4Ae/dO
dTPt7VNuXE7SDSE2T8e+0a8QiBtQ/OLwJKpMzJuETni9Efl1kIEQTEHEpOy7J2Fd
SjeV1E6p2VeVkuQ+uEEdpImCCpY7518Bpx93UVQ1Z2SqsxCflhcf10FtSw4PtWzM
MZ5YbIS46Q1tzxFuNbRXXpPX9kYnGMOgOTplkgxCU5GnFrnVO0zLl8pMLnQubayg
1bbfoulWiKSCR7dAK6gj4ShIT3fE76SKQeDJ63cZ97ISUwZW5vQKLsBu5l5XcUQD
B109nu+UCxAhYNOCazy75NuBjjttL8sNBJxrjxUqmQRkLf0NGN6tQFI+UkOcavzd
l0hreIAQhKEhTsUUzl4R+dkJ
=dCXK
-----END PGP SIGNATURE-----
