### ISSUE TITLE
NX-OS memory, power, disk (flash) and fan support

### ISSUE THREAD

**Issue by ciscoqid** [librenms/librenms#2371]
I am trying to see how to get memory pool info, storage (flash usage) and fan speed added to the NX-OS device type.  From my review of snmpwalk output from a 3064-T (here: https://www.dropbox.com/s/2g5xb0ekw6jopq7/nxos-snmpwalk.txt?dl=0), I see no evidence fan speed sensors are exposed via SNMP, just operational info via the FRU MIB.  It may be possible via their XML API, but I don't think that is something LibreNMS is ready to do. Maybe one day. Including information on fabric extender modules when installed would be nice, too, but the one I am looking at has none.  I know NX-OS has had spotty SNMP support, but it looks like we can add at least a few items.

Memory is here:

CISCO-PROCESS-MIB::cpmCPUMemoryUsed.1 = Gauge32: 2348264 kilo-bytes
CISCO-PROCESS-MIB::cpmCPUMemoryFree.1 = Gauge32: 1316976 kilo-bytes

Power is here:

CISCO-ENTITY-FRU-CONTROL-MIB::cefcPowerRedundancyMode.470 = INTEGER: redundant(2)
CISCO-ENTITY-FRU-CONTROL-MIB::cefcPowerRedundancyMode.471 = INTEGER: redundant(2)
CISCO-ENTITY-FRU-CONTROL-MIB::cefcPowerUnits.470 = STRING: CentiAmps @ 12V
CISCO-ENTITY-FRU-CONTROL-MIB::cefcPowerUnits.471 = STRING: CentiAmps @ 12V
CISCO-ENTITY-FRU-CONTROL-MIB::cefcTotalAvailableCurrent.470 = INTEGER: 4200
CISCO-ENTITY-FRU-CONTROL-MIB::cefcTotalAvailableCurrent.471 = INTEGER: 4200
CISCO-ENTITY-FRU-CONTROL-MIB::cefcTotalDrawnCurrent.470 = INTEGER: 2910
CISCO-ENTITY-FRU-CONTROL-MIB::cefcTotalDrawnCurrent.471 = INTEGER: 2910
CISCO-ENTITY-FRU-CONTROL-MIB::cefcFRUPowerAdminStatus.22 = INTEGER: on(1)
CISCO-ENTITY-FRU-CONTROL-MIB::cefcFRUPowerAdminStatus.470 = INTEGER: on(1)
CISCO-ENTITY-FRU-CONTROL-MIB::cefcFRUPowerAdminStatus.471 = INTEGER: on(1)
CISCO-ENTITY-FRU-CONTROL-MIB::cefcFRUPowerOperStatus.22 = INTEGER: on(2)
CISCO-ENTITY-FRU-CONTROL-MIB::cefcFRUPowerOperStatus.470 = INTEGER: on(2)
CISCO-ENTITY-FRU-CONTROL-MIB::cefcFRUPowerOperStatus.471 = INTEGER: on(2)
CISCO-ENTITY-FRU-CONTROL-MIB::cefcFRUCurrent.22 = INTEGER: -2910
CISCO-ENTITY-FRU-CONTROL-MIB::cefcFRUCurrent.470 = INTEGER: 4200
CISCO-ENTITY-FRU-CONTROL-MIB::cefcFRUCurrent.471 = INTEGER: 4200
CISCO-ENTITY-FRU-CONTROL-MIB::cefcMaxDefaultInLinePower.0 = INTEGER: 0 miliwatts

Flash is here (truncated -- see full dump for more):

CISCO-FLASH-MIB::ciscoFlashDevicesSupported.0 = Gauge32: 1
CISCO-FLASH-MIB::ciscoFlashDeviceSize.1 = Gauge32: 1895170048 bytes
CISCO-FLASH-MIB::ciscoFlashDeviceSize.2 = Gauge32: 20971520 bytes
CISCO-FLASH-MIB::ciscoFlashDeviceSize.3 = Gauge32: 104857600 bytes
CISCO-FLASH-MIB::ciscoFlashDeviceSize.4 = Gauge32: 0 bytes

**Comment by Rosiak** [comment]
This still a problem?
