### ISSUE TITLE
DNS going down breaks the entire system

### ISSUE THREAD

**Issue by ilar** [librenms/librenms#2374]
Could we maybe use IPs to monitor systems on the network, or at least add an option to choose between a static mode and a resolved mode? Maybe a fallback mode, where if the host can't be resolved, it attempts the last known IP address?

Even if everything is up and working, any sort of DNS issue instantly breaks LibreNMS completely.

**Comment by masonke** [comment]
This is one of the reasons we use /etc/hosts for the critical devices.  If DNS has a problem, the tools still work. 
~KEM

**Comment by ilar** [comment]
Definitely a good idea I'll be stealing, though I think we should probably have a 'proper' method for dealing with it, unless there's a convincing reason not to.

**Comment by ciscoqid** [comment]
On 11/1/15 12:20 PM, Steffan Pease wrote:
>
> Definitely a good idea I'll be stealing, though I think we should 
> probably have a 'proper' method for dealing with it, unless there's a 
> convincing reason not to.
>

Perhaps cache host lookups in the database for a bit to check if host 
lookups fail?

Mark

-- 
Mark D. Nagel, CCIE #3177 Emeritus <mnagel@willingminds.com>
Principal Consultant, Willing Minds LLC (http://www.willingminds.com)
cell: 949-279-5817, desk: 714-495-4001, fax: 714-844-4698

** For faster support response time, please
** email support@willingminds.com or call 714-495-4000

**Comment by masonke** [comment]
It is not too bad, the routers and other infrastructure devices do not change often. We use salt to keep all the pollers in sync
~KEM

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Use IPs ?

Or is that too trivial?

Dont get the reason/meaning behind this issue. Is it just a discussion on how to make DNS HA ?

F0o

On 1 November 2015 22:30:27 CET, Kevin <notifications@github.com> wrote:
>It is not too bad, the routers and other infrastructure devices do not
>change often. We use salt to keep all the pollers in sync
>~KEM
>
>> On Nov 1, 2015, at 15:20, Steffan Pease <notifications@github.com>
>wrote:
>>
>> Definitely a good idea I'll be stealing, though I think we should
>probably have a 'proper' method for dealing with it, unless there's a
>convincing reason not to.
>>
>> —
>> Reply to this email directly or view it on GitHub
><https://github.com/librenms/librenms/issues/2374#issuecomment-152860440>.
>>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2374#issuecomment-152865312
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5MhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikgPGYwb0Bs
aWJyZW5tcy5vcmc+BQJWNw+VAAoJEJMZKtVWOFzBKygQAIkP1UeX/J8ZXRkgMkvj
1sSzVTjF+/gAXqfGSmyURaYZk8Rpvi75I8YceDxeA/bn5z7q1eqkw67JOY3VrHAb
NV6gX1iJAsh2vz6ZOEInlCKOxBoUTyfokbUNEVqE/S4w3CvvPwMIeSd6fqlQ7WJ1
H1cfX1nwwypWrj+NDHKXyOy/bhpJqpydAZ3Gza7aL5/VoQvxJndxwF0oKlHr47B4
Iv6O+VyU/NV3IfXx/240tdowpYVmiXSpINwCTUWPFjn5KGZxOV7qVOsAelnVZxW7
A1KRz8jJhHnPyZrBxQQcsviAOax59b8RuFpgmGP+t0qZsEhaNIEIkvRJ1sOZivgG
1xDpfn3SoKVuKZT12Pv62zxzomVj/rTcA7QFtMMOIAlNG+x9BMf7v46ekSo6lNQw
mjk53KSl+zStlSiOoUxNS2+et42AnYYs0Rgk6OGADWxkXkx3DETgJG4QlkEwk5Xu
/H9arn0yj0WQgmbjXQ0puNL0f2ZmpZgNOnBD5RnvS7Ubyn/P/T74CIggZOysctF0
MTscCaaQVd0AIq+0EDIYitMR9D9Ybs9i2bLYoFat/6fH1UvBUeqxmFyMnFO9fWk+
HFxcLMsdCla6uXtp6+AQLuPAX0URhh5DDwWk3bHzxchJfkJOA3c2upRSwyHmgebj
smEVDhR+t2W4c2r2yj4ODCN0
=Dcwr
-----END PGP SIGNATURE-----

**Comment by Rosiak** [comment]
I'm still not sure this issue should be adressed by LibreNMS.
A proper DNS caching solution would be the thing in this case.

Something like DNSMASQ for example.
http://www.thekelleys.org.uk/dnsmasq/doc.html
Or
https://github.com/kenshinx/godns

**Comment by laf** [comment]
I'd certainly say that a local dns server is the way to fix it. Trying to do this in code re-invents the wheel and probably won't be done as well.

**Comment by ilar** [comment]
The problem with that is that using a local DNS server is the entire issue. If the local DNS server goes down or has issues- the exact situation you have LibreNMS for- libreNMS breaks completely. It's entirely useless as a monitoring tool in any situation with local DNS. That's a pretty major issue, I feel.

**Comment by laf** [comment]
This is the same as any other monitoring system using dns resolution and I've never come across one that cache records. 

I really don't see this being an an issue for us let alone a big issue. Running a stable dns platform shouldn't be a challenge. 

You might find someone else wants this and picks up the challenge and contribute the code.

**Comment by ilar** [comment]
Can I ask what monitoring systems you know of that rely on dns resolution to identify boxes? I know PTRG and Nagios do not.

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

But neither does LibreNMS.

I dont get the point of this issue :S

I run LibreNMS using IPs only just fine, as well as some smaller installs with DNS. I prefer IP over DNS as well because of said resolution issues l.

- - f0o

On 2 November 2015 16:26:52 CET, Steffan Pease <notifications@github.com> wrote:
>Can I ask what monitoring systems you know of that rely on dns
>resolution to identify boxes? I know PTRG and Nagios do not.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2374#issuecomment-153052312
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5MhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikgPGYwb0Bs
aWJyZW5tcy5vcmc+BQJWN4GIAAoJEJMZKtVWOFzB6yAP/RwiIg597w+YRx+y9oD5
iZkujfVvSis0es54NL85XWWILXScQhwLtFA2F+7c9ELYx3D7CtJVe2H0IcRRT00t
z7Gc4BkQBVhDb+3YsBkntqW3RIi+LECeZASmMfT95SbBsz/52QemYwJg1rLNE1sS
++dZeRCuzm25EXWGeOgCLuzbp//c83HsFCPtm/D6aKJuNOhZuh6OTg0Lo7TaXg+B
0aWpC9bxyNjUeqM8oLFNY0+NSVHTgL4yB+j1Jm2TLrmWVR5cltpN03zlw73V0AyO
lW1KDGovKAKdHiUcet+r4UXs46vw/3a1CLzwOGZKkT2lGuyB4K01wXBVM33cltm4
VuslLc7Qubq5ZkkekmthQUmqST2IOoNBqwpOJRPW4gixnQX2YWIUB6cICXRdK3sP
GCJL8+ZBJJxk8MLm/uhDpfHiIUV63xHPksUq9bA9q0foroSYq+Fe91TMJABdHNuw
BkauzAGItr7Ms2I8K/rYieA+0AqgJoV2ihM0oWHIfbiHRRrNh1IWwe48VeDjjJZN
jQUtS4j1SF1WdfOSTlzlpm0K2qwuGwud6sAPA/o7An2BSM2xwAtDPU1LgblVTjRk
pbqFoxCKFWlBXiRZK8eK0JwwI7TusAhcHqbbNa9WpQK46lrh8Leo2nKfHIFot10R
g1lnc5iSqh4v+9fecyVyjGLT
=SWr/
-----END PGP SIGNATURE-----

**Comment by ilar** [comment]
Really? Hmm. Something, somewhere, is badly messed up on my monitoring box then, it could never add devices by IP.

**Comment by laf** [comment]
Nagios does, zabbiz does, I'm pretty certain when I tested opennms and zennos both did. 

You know you can add devices by IP directly right?

**Comment by paulgear** [comment]
I'm fully with @laf on this one; if your local DNS caching or slave server is not stable, you've got more problems than running an NMS.  This is one of the reasons why our fork base didn't (doesn't?) support add via IP.  DNS is a fundamental Internet service, and it's not that hard to make it reliable.  Even if the local service goes down, you should have a backup in your /etc/resolv.conf that points to one that does work.

**Comment by ilar** [comment]
I guess it's just a difference in opinion in the end then- I feel like a monitoring system shouldn't have such a massive external dependency, no matter how stable/reliable the service tends to be. Just because the service itself is reliable, that doesn't mean your network will be able to receive it faithfully- the whole reason you have monitoring, imo.

Cheers.

**Comment by paulgear** [comment]
@ilar For avoidance of doubt, even if you don't like being dependent on DNS, there are two alternatives available to you: use /etc/hosts entries for everything (you can generate DNS from these, or vice versa), or add devices via IP.

Personally, I don't recommend either of these; my approach is that if DNS is broken, my network is broken.

**Comment by laf** [comment]
To clarify @ilar. I've not said that other NMS' have a dependency on hostnames (i.e you can't use IPs), I've said that when hostnames are used they won't have their own caching mechanism which is what this issue was asking us to do. That is the part that we're saying is out of scope for LibreNMS and needs to be dealt with by users.
