### ISSUE TITLE
Housekeeping in Librenms

### ISSUE THREAD

**Issue by abilashv** [librenms/librenms#2388]
First of all hats off to all the developers who make this tool so great ! 
It would be very helpful for an environment with 500+ hosts, if there is an utility php to 
1. Cleanup old / never used rrd files 
2. Stale database entries 
3. Clean up old alert,syslog and event logs according to the age .
Just an optional things but it will be become very handy in long run  :) :+1:

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I think 2nd and 3rd are already dealt with in the daily cronjob

On 5 November 2015 09:52:52 CET, abilashv <notifications@github.com> wrote:
>First of all hats off to all the developers who make this tool so great
>!
>It would be very helpful for an environment with 500+ hosts, if there
>is an utility php to
>1. Cleanup old / never used rrd files
>2. Stale database entries
>3. Clean up old alert,syslog and event logs according to the age .
>Just an optional things but it will be become very handy in long run
>:) :+1:
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2388
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5MhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikgPGYwb0Bs
aWJyZW5tcy5vcmc+BQJWOxlBAAoJEJMZKtVWOFzBmY4P/1nVW+t+GNbaGPURxcWp
utluVeIRGl00NG+Y2xcZps+MMFPvkp1U7/sKhRXEkHY+j1ZSDBAaBNCe+CVMAzhf
4bzR++EfWVsKXATMGTNIMWYoXW4ZnJmPziHU9HCCkvGh2g+cFjGf8zvOkUe8Y0XH
EN7CGivpO0GhHzU80gZVGrXCMDdgfHt4r8KovzCAazQE0GWTQDJTJBqGWg4AkPS+
ftO2LE8VecQLXTnFbXcXX2xBzInJ4mcAaciT5NfThSsux4Ydcooo8g+fouYVpt0n
Q6kqLSy119cwF+4DYbWlNWu5jGN+mDE/YJWMD7NoJLYa6pO0ErYViVkbqI5IENad
8gfH0pjrU4JO/D7hMuYoomCHpGOQU8zu4lBiS5xwXBCcMIxtNK6vmlOIQm8e/X48
qdJQQoxab84G4PK5u7w6K8aeJj2G6OQRBE+MXw3fTxBI/HjRATeyFrD8+bCnDM6Z
02CudJdL/HjvJWl7GaHB/ov0cnbXtn7LeroIcXEbJrcz7foKoCefnhRWz3v6qmGH
TMCapUrT4PwBn3CARV9ZdPsz3hNMlEuLmWqtceqnnYSYVEOiDF52Fr5bB2ARpDeM
PYIJ65LukZkrzJx+gw7hde6A4xb+NTVj/mgC0xe4U096wXycOwnB5iorBgfdydpl
KMrKXvUoTf6RNi0Kq7ROguF4
=DW7d
-----END PGP SIGNATURE-----

**Comment by abilashv** [comment]
Thanks for the reply f0o !
an option to clean old rrd files according to age will also be so useful.

**Comment by Rosiak** [comment]
:+1: 
Should be integrated in the current daily job

**Comment by abilashv** [comment]
Awesome..Thank you Rosiak !!
