### ISSUE TITLE
Map widget cannot be resized

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#2390]
Add some CSS or JS glue to allow resizing of the Map.

My attempt with re-setting the container's height via JS didnt work. Somebody with JS/CSS background should do it.

**Comment by Rosiak** [comment]
Is this still a problem?

**Comment by SaaldjorMike** [comment]
The map still does not adjust the height according to the widget height, so I'd say yes.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
