### ISSUE TITLE
add devices by file

### ISSUE THREAD

**Issue by aauvinet** [librenms/librenms#2391]
Hello,

I am testing Observium and LibreNMS.
Libre NMS is very  good tools but i have a issue :

In Observium, it's possible to add devices by file.
It is not possible in librenms,  i don't find to make it.

Is it possible to add devices in LibreNMS ?

**Comment by Rosiak** [comment]
You can add devices through the web interface, and though the command line using the addhost.php file.

**Comment by aauvinet** [comment]
Ok.
But it's for mass import ..
For example.
I would like imported more than one devices.
Five hundred.....

In observium. I can add hosts with argument a file.
In the file, there are all devices.
Line by line.
Add_host.php <file>

Not possible in livrenms



-------- Message d'origine --------
De : Søren Rosiak <notifications@github.com>
Date : 05/11/2015 15:58 (GMT+01:00)
À : librenms/librenms <librenms@noreply.github.com>
Cc : AUVINET Andre <Andre.AUVINET@nantesmetropole.fr>
Objet : Re: [librenms] add devices by file (#2391)


You can add devices through the web interface, and though the command line using the addhost.php file.

**Comment by laf** [comment]
@aauvinet 

So you have to create a file something along the lines of:

hostname, v1, public

?

If so, why don't you just do:

/opt/librenms/addhost.php hostname v1 public

Then run:

`sh add.sh`

**Comment by aauvinet** [comment]
Yes.
Good idea....
I don't think at this.
I will test tomorrow.
Thanks for this idea.





Envoyé de mon Galaxy Note 4 d'Orange


-------- Message d'origine --------
De : Neil Lathwood <notifications@github.com>
Date : 05/11/2015 20:45 (GMT+01:00)
À : librenms/librenms <librenms@noreply.github.com>
Cc : AUVINET Andre <Andre.AUVINET@nantesmetropole.fr>
Objet : Re: [librenms] add devices by file (#2391)


@aauvinet<https://github.com/aauvinet>

So you have to create a file something along the lines of:

hostname, v1, public

?

If so, why don't you just do:

/opt/librenms/addhost.php hostname v1 public

Then run:

sh add.sh

**Comment by aauvinet** [comment]
I close this issue

**Comment by nickermire** [comment]
I agree with laf, this is a serious issue. This tool isn't ready for the enterprise if you're unable to import/export a large number of devices. I cannot spend my time adding 1000s of devices one at a time.

**Comment by laf** [comment]
I'm not sure we do agree, especially on this being a serious issue. As you've not actually given any info on what you want to do all I can do for now is say:

Export: MySQL Queries or use the API

Import: Script ./addhost.php, use auto discovery, snmp-scan or make use of the API calls.

I'm actually not even sure what a comment of enterprise ready

**Comment by shimamizu** [comment]
Enterprise ready meaning able to bulk import large amounts of devices easily. My environment only has 1,000 devices, but I know other teams at my workplace have tens of thousands. They may not want to set it to auto discovery for a subnet, so for them that may not be the most viable choice. 

Also a good question, if you set auto discovery, can you set it so that certain auto discovered subnets automatically add to a specific distributed poller group? Obviously enterprise level of thousands of devices will want to have multiple poller groups and not be a single box install.

**Comment by murrant** [comment]
`cat hosts.txt|xargs -I{} ./addhost.php {}`, done, thousands imported

You can also you `./snmp-scan.py` to add entire subnets. You could set up a cron job to run this if you like. All the auto-discovery methods are much better though.

@shimamizu a specific poller group as a command line option to snmp-scan.py is a good idea, you should put in a feature request.

**Comment by shimamizu** [comment]
https://community.librenms.org/t/add-poller-group-option-for-snmp-scan-py-config-php/2828
