### ISSUE TITLE
Feature Request: Automatic group devices based on locations

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#2392]
Just a quick thought.
Could be cool to be able to automatically(when activated ofc) create device groups based on location.

Say I have 4 devices, 2 in Berlin 2 in Munich.
The following device groups would be created:
EMEA->Germany->Berlin
EMEA->Germany->Munich

And include the listed devices.

**Comment by f0o** [comment]
:+1:

This sounds like something I can do while idling at the airport tmr. I'd group by comma seperated field in the sysLocation (and overrides). That good?

**Comment by Rosiak** [comment]
Moved to community site.
