### ISSUE TITLE
Feature Request: Tree-like structure for navigating devices/groups

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#2393]
Device Location/Group Tree structure, perhaps a widget or something(Not sure of the implementation but just a idea).

Example:
![lt3ai](https://cloud.githubusercontent.com/assets/6378934/10971699/d68df63c-83d5-11e5-9e73-572fe7c5c09c.jpg)

**Comment by Rosiak** [comment]
https://github.com/jonmiles/bootstrap-treeview looks suitable for the job

**Comment by doesterhuizen** [comment]
Question:

What can be done to get this feature bumped up the list for development?

Is there a donation that can be made?

Thanks

**Comment by laf** [comment]
We don't accept donations, things are worked on when people have the time or motivation for that feature.

Me personally, this isn't something I'm fussed about so it's unlikely I will work on it - others might though.

**Comment by laf** [comment]
You should also use the react button in the first post of this issue to indicate you want it.

**Comment by Rosiak** [comment]
Moved to community site.
