### ISSUE TITLE
Support for Wireless hardware controlled by a FortiGate Firewall

### ISSUE THREAD

**Issue by simonholmbring** [librenms/librenms#2394]
I would like to see further support for Wireless Hardware controlled by a FortiGate Firewall.

Today FortiAPs are added/managed by FortiGate firewalls, and all interface statistics and counters are reported by the FortiGate (at least that's what it looks like when I look through their MIB).

But when polled by LibreNMS these interfaces don't show up.

**Comment by fran-nlt** [comment]
+1

**Comment by simonholmbring** [comment]
Any comments on this? From what I can see in the latest mibs (newer than the ones shipped with LibreNMS), there is interface support for ap's controlled by a fortigate firewall. So basically I'm guessing these "just" needs to be classified someway to also show up in the inventory and LibreNMS?

**Comment by jcbailey2** [comment]
I'm interested in taking a stab at this.. What are you looking for? Just the tunnel interface statistics, or the wireless-specific stats? Client count, channel, TX power, etc?

Are you more interested in a per VAP view, or per physical AP?

**Comment by simonholmbring** [comment]
Hi JCBailey,

First of all to see that there are AP's connected to the Fortigate, second, to see client count, channel, ssid's being broadcasted, power, and interface stats.

I would like to see per physical AP.

/Simon

**Comment by simonholmbring** [comment]
@jcbailey2 Guessing the stab didn't pan out? :)

**Comment by micush** [comment]
+1

Have logs of these access points. Would like to inventory them.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-support-for-wireless-hardware-controlled-by-a-fortigate-firewall/732
