### ISSUE TITLE
Poll FDB tables and allow searching for MAC addresses

### ISSUE THREAD

**Issue by aauvinet** [librenms/librenms#2398]
Hello,
I have the same issue :+1: 
Poll FDB tables and allow searching for MAC addresses #1196

I have lot of Cisco switch, I need to find @mac of host / port / vlan , for exemple personal computer...

In observium, it's possible and it's very well.

see the picture

20151106 Rosiak:
Removed obs... picture

**Comment by Rosiak** [comment]
Please don't post material from obs..., I've just removed the picture from your post.

**Comment by aauvinet** [comment]
Ok, sorry

**Comment by SaaldjorMike** [comment]
Closing this as this is a duplicate of #1196 which you also refer to yourself.

**Comment by aauvinet** [comment]
Ok,
Excuse me for the duplicate.
