### ISSUE TITLE
Virtual Machine Image

### ISSUE THREAD

**Issue by supertylerc** [librenms/librenms#24]
Virtual Machine image should be created to help users try LibreNMS with minimal effort.

**Comment by Peter2121** [comment]
Is there any progress? The old image is not available as FTP server seems to be down.

**Comment by jacobgardiner** [comment]
I can probably create a vagrant environment fairly easily, although it's mainly used for development environments - it may also be an easy way to setup & install the latest version

**Comment by Peter2121** [comment]
I would like to test it on VMware or VirtualBox, I have no Vagrant now. 
I think that many people are like me ;)

**Comment by laf** [comment]
I've got a virtual box appliance. I'll post the link shortly

**Comment by Peter2121** [comment]
Cool, thank you :)

**Comment by laf** [comment]
https://www.irccloud.com/pastebin/y3Z5HvIb

The and zipper the appliance files. Vmdk can be used with vmware.

**Comment by laf** [comment]
That's supposed to say the tgz and zip files are for virtualbox appliance.

**Comment by laf** [comment]
I'm now closing this as the downloads page is now online:

http://www.librenms.org/downloads.html
