### ISSUE TITLE
Billing details for previous billing periods - only for traffic data, but not for 95-th percentile

### ISSUE THREAD

**Issue by mitkodotcom** [librenms/librenms#2402]
Hello,

It seems there is no practical way to display the 95-th percentile billing for any previous month, only for the current one. If you wish to bill your customer, you have to be awake on the last date of the month at 23:59:59 in order to capture the Monthly View. Quite annoying for 31-st of December ...

If you click on Ports / Traffic Bills / Previous Billing Period, you can see the bill for the last month, but only as total numbers. If you click on bill's description, the information for the _current_ billing period is displayed, not for the previous one.

In "Historical usage" if you click on some period's "Show details" icon, only the traffic data (up/download) is displayed, but not bits per second.

So far I am dealing with this situation by opening the current period, right-clicking on the Monthly View image, then View Image, then manually changing from= and to= timestamps with the beginning and the end of the previous month. Any suggestions for an easier way?

Regards,
Mitko

**Comment by richardlawley** [comment]
You CAN view this information.  Clicking Previous Billing Period in the Bills List displays the totals for each customer.  To view the detailed information, including the graphs, click on the bill, then click Historical Usage, then click the Graph icon next to the month you wish to view.

Please note that if you're taking the image from the Quick Graphs page and altering the URL, this is NOT accurate enough data for billing purposes.  It runs off the RRD data for the ports, which at the default archive resolution only contains 5 minute data for 7 days, which is insufficient to calculate an accurate 95% figure for the month.  The "Historical Usage" and "Accurate Graphs" views both use the billing information stored in the database, which has the required resolution.

It would perhaps be better if clicking on the bill from the "Previous Billing Period" view took you directly to the Historical Usage page, but the functionality you're asking for is present.
