### ISSUE TITLE
Limiting users' access to plugins

### ISSUE THREAD

**Issue by mitkodotcom** [librenms/librenms#2403]
Hello,

If I create an account for a client to monitor its usage, the user has unlimited access to the Weathermap and Vlan_Search plugins, which both reveal too much private and sensitive information. Is it possible to limit client's access to the entire plugin system until the plugins are mature enough to take into consideration users' access rights to devices and ports?

Regards,
Mitko

**Comment by laf** [comment]
Plugins are disappearing in v2.
