### ISSUE TITLE
Feature-Request: Support for Sophos UTM Firewall Appliance

### ISSUE THREAD

**Issue by markuspachali** [librenms/librenms#2404]
Hi all,
are there any plans to support Sophos UTM Firewall appliances (virtual and/or physical edition)? At the moment the boxes are discovered as normal Linux servers.
Best regards,
Markus

**Comment by laf** [comment]
If it's just detection then please link to the output of:

./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -d -r -m system,os

Using dpaste.de

**Comment by markuspachali** [comment]
Output from discovery.php:
https://dpaste.de/S0t6

Output from poller.php:
https://dpaste.de/9TaJ

I hope that helps.

**Comment by Rosiak** [comment]
On it.
Mailed Sophos regarding permission to use logo. 
Will PR basic support tomorrow or Wednesday.

**Comment by Rosiak** [comment]
@markuspachali - can you please repost the pastes, they've expired :(

**Comment by wizzycom** [comment]
Hello. I am also interested on this. 

[root@ares librenms]# ./poller.php -h 10.70.25.30 -d -r -m system,os
LibreNMS 2015.master Poller
commit 6e70c230831aa496987a9563cd01bfd4f7953956

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE '10.70.25.30' ORDER BY `device_id` ASC] ./poller.php 10.70.25.30 2015-11-28 08:46:55 - 0 devices polled in 0.016 secs

MySQL: Cell[0/0s] Row[0/0s] Rows[1/0s] Column[0/0s] Update[0/0s] Insert[0/0s] Delete[0/0s]
[root@ares librenms]# ./discovery.php -h fw.wizzycom.awmn -d -m os
LibreNMS 2015.master Discovery
commit 6e70c230831aa496987a9563cd01bfd4f7953956

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1]
SQL[SELECT revision FROM `dbSchema`] DB Schema already up to date.

SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE 'fw.wizzycom.awmn' ORDER BY device_id DESC]
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '6'] fw.wizzycom.awmn 6 linux  (unix)
OS: DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Ovq -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 SNMPv2-MIB::sysDescr.0
MIB search path: /opt/librenms/mibs
Cannot find module (MTA-MIB): At line 0 in (none)
Cannot find module (NETWORK-SERVICES-MIB): At line 0 in (none)
Cannot find module (SCTP-MIB): At line 0 in (none)
Linux fw.wizzycom.awmn 3.12.40-26.gc80f187.rb1-smp64 #1 SMP Wed Sep 30 19:29:45 UTC 2015 x86_64

DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Ovqn -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 SNMPv2-MIB::sysObjectID.0
MIB search path: /opt/librenms/mibs
Cannot find module (MTA-MIB): At line 0 in (none)
Cannot find module (NETWORK-SERVICES-MIB): At line 0 in (none)
Cannot find module (SCTP-MIB): At line 0 in (none)
.1.3.6.1.4.1.8072.3.2.10

| Linux fw.wizzycom.awmn 3.12.40-26.gc80f187.rb1-smp64 #1 SMP Wed Sep 30 19:29:45 UTC 2015 x86_64 | .1.3.6.1.4.1.8072.3.2.10 | DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Oqvn -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 ENTITY-MIB::entPhysicalDescr.1
MIB search path: /opt/librenms/mibs
Cannot find module (MTA-MIB): At line 0 in (none)
Cannot find module (NETWORK-SERVICES-MIB): At line 0 in (none)
Cannot find module (SCTP-MIB): At line 0 in (none)
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Oqv -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 .1.3.6.1.4.1.39165.1.6.0
MIB search path: /opt/librenms/mibs
Cannot find module (MTA-MIB): At line 0 in (none)
Cannot find module (NETWORK-SERVICES-MIB): At line 0 in (none)
Cannot find module (SCTP-MIB): At line 0 in (none)
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Oqv -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 SML-MIB::product-Name.0
MIB search path: /opt/librenms/mibs
Cannot find module (MTA-MIB): At line 0 in (none)
Cannot find module (NETWORK-SERVICES-MIB): At line 0 in (none)
Cannot find module (SCTP-MIB): At line 0 in (none)
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Osqnv -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 ENTITY-MIB::entPhysicalMfgName.1
MIB search path: /opt/librenms/mibs
Cannot find module (MTA-MIB): At line 0 in (none)
Cannot find module (NETWORK-SERVICES-MIB): At line 0 in (none)
Cannot find module (SCTP-MIB): At line 0 in (none)
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Osqnv -m IEEE802dot11-MIB -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 dot11manufacturerName.5
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Osqnv -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 HOST-RESOURCES-MIB::hrSystemInitialLoadParameters.0
MIB search path: /opt/librenms/mibs
Cannot find module (MTA-MIB): At line 0 in (none)
Cannot find module (NETWORK-SERVICES-MIB): At line 0 in (none)
Cannot find module (SCTP-MIB): At line 0 in (none)
"root=/dev/disk/by-label/root vga=791 rootflags=data=ordered splash=silent
"

DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -OqvU -m CAREL-ug40cdz-MIB -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 roomTemp.0
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Osqnv -m NETONIX-SWITCH-MIB -M mibs:mibs/netonix/ udp:fw.wizzycom.awmn:161 firmwareVersion.0
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Osqnv -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 ENTITY-MIB::entPhysicalMfgName.1
MIB search path: /opt/librenms/mibs
Cannot find module (MTA-MIB): At line 0 in (none)
Cannot find module (NETWORK-SERVICES-MIB): At line 0 in (none)
Cannot find module (SCTP-MIB): At line 0 in (none)
No Such Object available on this agent at this OID


SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='firewall',`last_discovered_timetaken` ='1.423' WHERE `device_id` = '6'] Discovered in 1.423 seconds


SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','fw.wizzycom.awmn','1448693241.3017','1.472','1')] ./discovery.php fw.wizzycom.awmn 2015-11-28 08:47:22 - 1 devices discovered in 1.472 secs
MySQL: Cell[1/0s] Row[1/0s] Rows[1/0s] Column[0/0s] Update[1/0.03s] Insert[1/0.01s] Delete[0/0s]


=============================================================================

[root@ares librenms]# ./poller.php -h fw.wizzycom.awmn -d -r -m system,os
LibreNMS 2015.master Poller
commit 6e70c230831aa496987a9563cd01bfd4f7953956

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'fw.wizzycom.awmn' ORDER BY `device_id` ASC]
SQL[SELECT * FROM `devices` WHERE `device_id` = '6']
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '6'] fw.wizzycom.awmn 6 linux (unix)

SQL[INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('','','','','','','6',NOW())] DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 sysObjectID.0
SNMPv2-SMI::enterprises.8072.3.2.10

DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -OQUs -m SNMPv2-MIB -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 sysUpTime.0 sysLocation.0 sysContact.0 sysName.0
sysUpTime.0 = 4:9:48:01.10
sysLocation.0 = Computer Room
sysContact.0 = Wizzy
sysName.0 = FW

DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 sysDescr.0
Linux fw.wizzycom.awmn 3.12.40-26.gc80f187.rb1-smp64 #1 SMP Wed Sep 30 19:29:45 UTC 2015 x86_64

DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Oqvn -m SNMPv2-MIB -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 sysObjectID.0
.1.3.6.1.4.1.8072.3.2.10

DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -OUqv -m SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 snmpEngineTime.0
380881

DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Oqv -m HOST-RESOURCES-MIB -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 hrSystemUptime.0
4:22:56:04.54

Using hrSystemUptime (4:22:56:04.54)
[RRD Disabled]RRD[update /opt/librenms/rrd/fw.wizzycom.awmn/uptime.rrd N:428164] Uptime: 4 days, 22h 56m 4s
DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Oqv -m UCD-SNMP-MIB -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 .1.3.6.1.4.1.2021.7890.1.3.1.1.6.100.105.115.116.114.111
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Oqv -m UCD-SNMP-MIB -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 .1.3.6.1.4.1.2021.7890.1.101.1
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Oqv -m MIB-Dell-10892 -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 .1.3.6.1.4.1.674.10892.1.300.10.1.9.1
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c wizzyc0m
/usr/bin/snmpget -v2c -c wizzyc0m -Oqv -m MIB-Dell-10892 -M /opt/librenms/mibs udp:fw.wizzycom.awmn:161 .1.3.6.1.4.1.674.10892.1.300.10.1.11.1
No Such Object available on this agent at this OID


Hardware: Generic x86 64-bit Version: 3.12.40-26.gc80f187.rb1-smp64 Features:  Serial:
[RRD Disabled]RRD[update /opt/librenms/rrd/fw.wizzycom.awmn/poller-perf.rrd N:0.485] Polled in 0.485 seconds
Updating fw.wizzycom.awmn
Array
(
    [uptime] => 428164
    [last_ping] => Array
        (
            [0] => NOW()
        )

    [last_ping_timetaken] =>
    [last_polled] => Array
        (
            [0] => NOW()
        )

    [last_polled_timetaken] => 0.485
)

SQL[UPDATE `devices` set `uptime` ='428164',`last_ping` =NOW(),`last_ping_timetaken` ='',`last_polled` =NOW(),`last_polled_timetaken` ='0.485' WHERE `device_id` = '6'] UPDATED!

SQL[SELECT * FROM device_groups ORDER BY name]
SQL[SELECT DISTINCT(alert_schedule.schedule_id) FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '6' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1]
SQL[SELECT * FROM device_groups ORDER BY name]
SQL[SELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '6' ) || alert_map.target = '6'  )]  #1:
SQL[SELECT state FROM alerts WHERE rule_id = '1' && device_id = '6' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'devices' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM devices WHERE (devices.device_id = '6') && ( (  ( devices.status = 0  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  )  )  = "1"        )]  NOCHG  #2:
SQL[SELECT state FROM alerts WHERE rule_id = '2' && device_id = '6' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'devices' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM devices WHERE (devices.device_id = '6') && (devices.uptime < "300"  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  = "1"    )]  NOCHG  #3:
SQL[SELECT state FROM alerts WHERE rule_id = '3' && device_id = '6' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'bgpPeers' && COLUMN_NAME = 'device_id']
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'devices' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM bgpPeers,devices WHERE (bgpPeers.device_id = devices.device_id && bgpPeers.device_id = '6') && (bgpPeers.bgpPeerState != "established"  &&   (  ( devices.status = 1  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  )  )  = "1")]  NOCHG  #4:
SQL[SELECT state FROM alerts WHERE rule_id = '4' && device_id = '6' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'bgpPeers' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM bgpPeers WHERE (bgpPeers.device_id = '6') && (bgpPeers.bgpPeerFsmEstablishedTime < "300"  &&  bgpPeers.bgpPeerState = "established")]  NOCHG  #5:
SQL[SELECT state FROM alerts WHERE rule_id = '5' && device_id = '6' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'ports' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM ports WHERE (ports.device_id = '6') && ( (  ( ports.ifOperStatus = "down"  &&  ports.ifAdminStatus != "down"  &&   (  ( ports.deleted = 0  &&  ports.ignore = 0  &&  ports.disabled = 0 )  )  )  )  = "1"  )]  NOCHG  #6:
SQL[SELECT state FROM alerts WHERE rule_id = '6' && device_id = '6' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'ports' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM ports WHERE (ports.device_id = '6') && ( (  (  ( ports.ifInOctets_rate * 8 )  / ports.ifSpeed )  * 100 )  >= "80"    )]  NOCHG  #7:
SQL[SELECT state FROM alerts WHERE rule_id = '7' && device_id = '6' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'sensors' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM sensors WHERE (sensors.device_id = '6') && (sensors.sensor_current > sensors.sensor_limit)]  NOCHG  #8:
SQL[SELECT state FROM alerts WHERE rule_id = '8' && device_id = '6' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'sensors' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM sensors WHERE (sensors.device_id = '6') && (sensors.sensor_current < sensors.sensor_limit_low)]  NOCHG  #9:
SQL[SELECT state FROM alerts WHERE rule_id = '9' && device_id = '6' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'ports' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM ports WHERE (ports.device_id = '6') && ( (  (  ( ports.ifInOctets_rate * 8 )  / ports.ifSpeed )  * 100 )  > "50" )]  NOCHG

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','fw.wizzycom.awmn','1448693291.1783','0.597','1','ares.wizzycom.awmn\n')] ./poller.php fw.wizzycom.awmn 2015-11-28 08:48:11 - 1 devices polled in 0.597 secs

MySQL: Cell[1/0s] Row[21/0.05s] Rows[12/0.02s] Column[0/0s] Update[1/0.01s] Insert[2/0.02s] Delete[0/0s]
[root@ares librenms]#

**Comment by gardar** [comment]
How's the status on this? Is there any additional information needed?

I've attached the MIB containing definitions of the Sophos UTM SNMP Notifications provided by Sophos if that's of any help.

[ASTARO-MIB.txt](https://github.com/librenms/librenms/files/238441/ASTARO-MIB.txt)

**Comment by laf** [comment]
Base support added

**Comment by laf** [comment]
Had to revert this as other linux devices were being picked up.

Can someone provide us with snmp access to a unit to test?

**Comment by KieronG** [comment]
I can provide readonly snmp access to a unit for your testing

**Comment by laf** [comment]
We've actually had access and it doesn't look like we have a way to identify them from snmp alone. Someone else was raising this with the vendor to see if they can fix it.

**Comment by KieronG** [comment]
thanks for the update.
