### ISSUE TITLE
Windows Server SNMP polling issue -- disk total size & usage shown as '0'

### ISSUE THREAD

**Issue by amitfocis** [librenms/librenms#2406]
I've got serveral Win hosts in my environment. Ranging from Win7 to Windows Server 2012 R2.

LibreNMS seems to have some problems with a few of these win servers - specifically with the disk space. It returns as "0". 

Here is the poller debug log: http://pastebin.com/65V4vCGS

Lines 143, 144 and 146 correctly pick up the 3 drives on the Windows Server. The 'array' starting at line 169 also correctly shows all the disk size and the disk usage as well.

However, there's another set of arays at line 258, 284 and 318 -- in all these arrays the disk size, disk usage etc are all zero 0.

As a result the LibreNMS Web interface also shows the disk usage 0%.

I am also monitoring this system using NagiosXI and Observium -- they don't seem to have this issue so it appears this is specific to LibreNMS.

I think this may be a bug.

**Comment by amitfocis** [comment]
Also thought I'd add -- 24 hours later, there seem to be some sporadic data in the graph. It looks like data is collected a few times, but for the most part it shows 0%.
![untitled](https://cloud.githubusercontent.com/assets/12567648/11049052/72f22714-87a0-11e5-8a66-cbec1e507615.png)

**Comment by laf** [comment]
@amitfocis can you provide us the output from:

```php
./discovery.php -h HOSTNAME -d -m storage
./poller.php -h HOSTNAME -r -d -m storage
```

**Comment by amitfocis** [comment]
Hi,

It appears this is an issue with windows SNMP service becoming overwhelmed with multiple queries. Looks like it isn't as robust as say.. snmpd.

Please close this, this isn't a problem with LibreNMS.

**Comment by laf** [comment]
We could possibly add some small delays to storage polling for windows?

**Comment by Rosiak** [comment]
@amitfocis 
Any comments on the suggestion?

**Comment by amitfocis** [comment]
Hi, I think it's best to leave it. SNMP is being deprecated in Windows with WMI being favoured in its place. Also in my test lab i have multiple things hitting 1 windows host every minute (probably not the best config) which contributes to the problem.

Thanks for following up!

**Comment by matthewaaronthacker** [comment]
If anybody else stumbles on this thread while trying to troubleshoot Libre and Windows servers, all you need to do to fix this problem is set the snmp timeout in Libre to 10 seconds. It isn't that Windows is becoming overwhelmed, it's just slow gathering disk and memory info to send back. A 10 second timeout will allow it to reply in time before Libre gives up.
$config['snmp']['timeout'] = 10;
