### ISSUE TITLE
missing cpu/memory info for ubiquity unifi APs

### ISSUE THREAD

**Issue by ehk20** [librenms/librenms#2407]
I've just migrated from Observium and the only slight regret is that we no longer get cpu and memory graphs for our APs. It appears these came via the FROGFOOT-RESOURCES-MIB which doesn't appear in LibreNMS so it would be nice if it could be added.

**Comment by SaaldjorMike** [comment]
Tomorrow I'll make sure I'll power on a UniFi AP and one of the following days take a look at this issue.

**Comment by ehk20** [comment]
Can confirm these graphs are now back.
