### ISSUE TITLE
Arbitrary graph comparison view

### ISSUE THREAD

**Issue by ehk20** [librenms/librenms#2408]
I realise this is a pretty major feature request but I have a suggestion which, from experience, can be a very helpful troubleshooting tool:

A generated view of on-the-fly user-select graphs sharing the same time axis. By this I mean a processes whereby the user can select any graph in a view for 'comparison', in a similar way you can on some shopping sites, and after done so for two or more graphs can then go to a resulting page containing all selected graphs.

The important part here is that rather than just being a generic 'custom graph collection' that I pre-configure behind the scenes it can be built up as your are investigating an issue: ie. As I'm looking into the load history on device X I realise I want to see how it may relate to traffic on device Y and temperature recorded by UPS Z, so I tick a 'compare' box on each of those as I go through them to then bring them up on a comparison screen where they are aligned along the same time axis.

**Comment by paulgear** [comment]
:+1: That's a great idea.

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #174](https://github.com/librenms/librenmsv2/issues/174) via [**ZenHub**](https://www.zenhub.com/)
