### ISSUE TITLE
Hide neighbours on interfaces by default

### ISSUE THREAD

**Issue by Alucardfh** [librenms/librenms#2409]
Hi,

When an interface has a large number of neighbours, having the whole list displayed render the page quite difficult to read.

Would it make sense to have the list displayed in a block that can be toggled from hidden to visible by a clic or with a button ?

![interfaceneighbors](https://cloud.githubusercontent.com/assets/1701397/11035472/91d10f94-86ea-11e5-8b90-7ca3b16727ef.PNG)

**Comment by Tawmu** [comment]
I agree. To be honest I didn't really see the benefit of this on a lot of our devices (firewalls/core switches) so the ability to disable it even would be good.

**Comment by Rosiak** [comment]
I agree too, doesn't make sense in big environments with overlapping subnets etc.

**Comment by laf** [comment]
We do have a config option to disable all of that:

`$config['enable_port_relationship'] =false;`

**Comment by Alucardfh** [comment]
Ok, that's a suitable workaround if you are not interested at all in this feature.

I have made a PR #2460 to show a way of doing what I suggested.
