### ISSUE TITLE
Make graphs use more space on large resolutions

### ISSUE THREAD

**Issue by Alucardfh** [librenms/librenms#2410]
Hi,

Most of the rrd graphs render quite small on large resolutions.
It start to get quite noticeable from 1920x1080 but in 2550x1440 some graphs pages don't even use half the screen width.

Would it be possible to have the graphs scale according to the available space ?

![webuisizegraphs](https://cloud.githubusercontent.com/assets/1701397/11035584/477ca9b6-86eb-11e5-85d2-e92073e80e1f.PNG)

![webuisizegraphs2](https://cloud.githubusercontent.com/assets/1701397/11035585/4a763b78-86eb-11e5-9713-28be451b734d.PNG)

**Comment by laf** [comment]
@Alucardfh I can't see a way to do this presently. We use a lazy load for images so we have to specify the width and height to do that. We'd need the browser width in php to do a calc on what size to display which is only possible by passing the width via another ajax call.

@librenms/reviewers - thoughts?

**Comment by Alucardfh** [comment]
Could the resolution be retrieved at login and stored in session ?
This way it would be available from php.

**Comment by laf** [comment]
I guess we could but this seems a bit hacky and won't be useful when resizing the browser.

**Comment by paulgear** [comment]
This is definitely something I'd like to see stay on our radar to improve.

**Comment by Alucardfh** [comment]
Ok I gave some thoughts on this and tried using an ajax call to store browser width and height in session in this PR #2461.

I only worked on print-graphrow.inc.php as it was the most obvious for me to start with.

The formula I used to calculate the width of each graph might need tuning.
