### ISSUE TITLE
netscaler-vsvr not finding the vservers

### ISSUE THREAD

**Issue by masonke** [librenms/librenms#2413]
Running virtual Netscaler version 11, which might be the problem. The netscaler-vsvr module is enabled, but the vservers are never discovered. 

The Netscaler mib in the /opt/librenms/mibs is NS-MIB, the new one fromthe Netscaler is NS-MIB-SMIV2-MIB.
Ran ./poller.php -h my-netscaler-a -m netscaler-vsvr -d and it looks like something changed in the MIB
vserverEntry = No Such Object available on this agent at this OID

Full run below.

Any ideas? We can test this if someone has a fix. Plus, I have the MIB file, but not sure how to make sure it is legally added to the repository,

librenms@librepoller-a:~$ ./poller.php -h my-netscaler-a -m netscaler-vsvr -d
Unlinked OID in IPATM-IPMC-MIB: marsMIB ::= { mib-2 57 }
Undefined identifier: mib-2 near line 18 of /usr/share/mibs/ietf/IPATM-IPMC-MIB
Bad operator (INTEGER): At line 73 in /usr/share/mibs/ietf/SNMPv2-PDU
Expected "::=" (RFC5644): At line 493 in /usr/share/mibs/iana/IANA-IPPM-METRICS-REGISTRY-MIB
Expected "{" (EOF): At line 651 in /usr/share/mibs/iana/IANA-IPPM-METRICS-REGISTRY-MIB
Bad object identifier: At line 651 in /usr/share/mibs/iana/IANA-IPPM-METRICS-REGISTRY-MIB
Bad parse of OBJECT-IDENTITY: At line 651 in /usr/share/mibs/iana/IANA-IPPM-METRICS-REGISTRY-MIB
LibreNMS 2015.master Poller
commit 725fc56f410030562d3e818142774a86ed3a66f8

DEBUG!
Starting polling run:

SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'my-netscaler-a' ORDER BY `device_id` ASC] my-netscaler-a 1024 netscaler

SQL[INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('3','3','0','1.68','3.15','2.58','1024',NOW())] DEBUG: SNMP Auth options =  -v2c -c mycommunitystring
/usr/bin/snmpget -v2c -c mycommunitystring -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs -t 1 -r 5 udp:my-netscaler-a:161 sysObjectID.0
SNMPv2-SMI::enterprises.5951.1

Netscaler VServers
DEBUG: SNMP Auth options =  -v2c -c mycommunitystring
/usr/bin/snmpbulkwalk -v2c -c mycommunitystring -OQUs  -m NS-ROOT-MIB -M /opt/librenms/mibs -t 1 -r 5 udp:my-netscaler-a:161 vserverEntry
vserverEntry = No Such Object available on this agent at this OID

SQL[SELECT \* FROM `netscaler_vservers` WHERE `device_id` = '1024'] RRD[update ././my-netscaler-a/poller-perf.rrd N:0.663 --daemon 10.70.201.41:42217] RRD[update ././my-netscaler-a/ping-perf.rrd N:2.58 --daemon 10.70.201.41:42217] Polled in 0.663 seconds
Updating my-netscaler-a
Array
(
    [last_ping] => Array
        (
            [0] => NOW()
        )

```
[last_ping_timetaken] => 2.58
[last_polled] => Array
    (
        [0] => NOW()
    )

[last_polled_timetaken] => 0.663
```

)

SQL[UPDATE `devices` set `last_ping` =NOW(),`last_ping_timetaken` ='2.58',`last_polled` =NOW(),`last_polled_timetaken` ='0.663' WHERE `device_id` = '1024'] UPDATED!

SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1024' && (devices.hostname REGEXP "wnd" &&) LIMIT 1]
SQL[SELECT DISTINCT(alert_schedule.schedule_id) FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '1024' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1024' && (devices.hostname REGEXP "wnd" &&) LIMIT 1]  #3:
SQL[SELECT state FROM alerts WHERE rule_id = '3' && device_id = '1024' ORDER BY id DESC LIMIT 1]
SQL[SELECT \* FROM devices WHERE (devices.device_id = '1024') && (devices.hostname REGEXP "rack"  &&  devices.status = "0"  &&  devices.status_reason = "icmp"     )]  NOCHG  #5:
SQL[SELECT state FROM alerts WHERE rule_id = '5' && device_id = '1024' ORDER BY id DESC LIMIT 1]
SQL[SELECT \* FROM devices WHERE (devices.device_id = '1024') && (devices.hostname REGEXP "wnd-idf"    &&  devices.status = "0"        &&  devices.status_reason = "icmp"           )]  NOCHG  #6:
SQL[SELECT state FROM alerts WHERE rule_id = '6' && device_id = '1024' ORDER BY id DESC LIMIT 1]
SQL[SELECT \* FROM devices WHERE (devices.device_id = '1024') && (devices.hostname REGEXP "core"        &&  devices.hostname NOT REGEXP "dbctcore"    &&  devices.status = "0"    &&  devices.status_reason = "icmp"   )]  NOCHG  #8:
SQL[SELECT state FROM alerts WHERE rule_id = '8' && device_id = '1024' ORDER BY id DESC LIMIT 1]
SQL[SELECT \* FROM processors,devices WHERE (processors.device_id = devices.device_id && processors.device_id = '1024') && (processors.processor_usage > "90"    &&  devices.hardware REGEXP "cisco"   )]  NOCHG  #9:
SQL[SELECT state FROM alerts WHERE rule_id = '9' && device_id = '1024' ORDER BY id DESC LIMIT 1]
SQL[SELECT \* FROM devices,mempools WHERE (devices.device_id = mempools.device_id && devices.device_id = '1024') && (devices.hardware REGEXP "cisco"    &&  mempools.mempool_perc > "98"    &&  devices.hostname NOT REGEXP "gre"    &&  devices.hostname NOT REGEXP "mpls"   )]  NOCHG

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','my-netscaler-a','1447185995.4408','3.513','1','librepoller-a\n')] ./poller.php my-netscaler-a 2015-11-10 15:06:39 - 1 devices polled in 3.513 secs

MySQL: Cell[3/0.62s] Row[6/0.29s] Rows[6/0.26s] Column[0/0s] Update[1/0.05s] Insert[2/0.25s] Delete[0/0s]
OK u:0.00 s:0.00 r:0.99
OK u:0.00 s:0.00 r:1.04
librenms@librepoller-a:~$

**Comment by laf** [comment]
@masonke Can you provide the NS-MIB-SMIV2-MIB file please?

**Comment by masonke** [comment]
[NS-MIB-smiv2_mib.txt](https://github.com/librenms/librenms/files/34383/NS-MIB-smiv2_mib.txt)

**Comment by masonke** [comment]
Here you go

**Comment by laf** [comment]
Thanks, some of the fields have changed. Would it be possible to have snmp access to a device?

If not, can you at least provide the output from the below but if you replace mibs/NS-MIB with the one you've linked to.

`/usr/bin/snmpbulkwalk -v2c -c mycommunitystring -OQUs -m NS-ROOT-MIB -M /opt/librenms/mibs -t 1 -r 5 udp:my-netscaler-a:161 vserverEntry`

**Comment by masonke** [comment]
Let me see what I can do with access, that might be tough.  I can grab the snmpbulkwalk later today.
~KEM

**Comment by masonke** [comment]
I am screwing this up somehow. With NS-MIB-SMIV2-MIB in /opt/librenms/mibs and ran 
/usr/bin/snmpbulkwalk -v2c -c mycommunitystring -OQUs -m NS-MIB-SMIV2-MIB -M /opt/librenms/mibs -t 1 -r 5 udp:my-netscaler-a:161 vserverEntry

I ended up with this error

MIB search path: /opt/librenms/mibs
Cannot find module (NS-MIB-SMIV2-MIB): At line 11 in (none)
vserverEntry: Unknown Object Identifier (Sub-id not found: (top) -> vserverEntry)

**Comment by laf** [comment]
:)

use the command I sent across, the NS-MIB-SMIV2-MIB is just the name of the file, the actual MIB name is NS-ROOT-MIB

**Comment by masonke** [comment]
Here you go

/usr/bin/snmpbulkwalk -v2c -c mycommunitystring -OQUs -m NS-ROOT-MIB -M /opt/librenms/mibs -t 1 -r 5 udp:my-netscaler-a:161 vserverEntry

returned
vserverEntry = No Such Object available on this agent at this OID

**Comment by laf** [comment]
:(

Any joy with us being able to get access?

**Comment by masonke** [comment]
Trying, may need to go through a webex session, if that would work

**Comment by masonke** [comment]
Used snmpbulkget and it worked
/usr/bin/snmpbulkget -v2c -c mycommunitystring -OQUs -m NS-ROOT-MIB -M /opt/librenms/mibs -t 1 -r 5 udp:my-netscaler-a:161 vserverEntry

curConfigVservers.0 = 423
vsvrBindCount.0 = 785
vsvrSvcGrpBindCount.0 = 391
curConfigLbVservers.0 = 381
curConfigGslbVservers.0 = 0
totSpilloverCount.0 = 0
csPipolicyName = No more variables left in this MIB View (It is past the end of the MIB tree)

**Comment by masonke** [comment]
The problem is this netscaler is using partitions. On using without partitions, things work normally.

**Comment by laf** [comment]
We would need the output for both a working and non-working device from:

`snmpbulkwalk -Onet -v2c -c COMMUNITY HOSTNAME .`

**Comment by laf** [comment]
No further info provided, closing.

**Comment by jimmelville** [comment]
Hi

I would also like to help with this issue. I have v11 and v10 netscalers so will provide the config. Can I share an obfuscated output with you privately?

Thanks

**Comment by laf** [comment]
Can you not share an obfuscated output publicly, it's a lot easier.

**Comment by banananananananana** [comment]
@laf 

I have Citrix Netscalers version 10.5/11... I am able to provide anything you need.

**Comment by laf** [comment]
This needs to be raised on the community forum
