### ISSUE TITLE
default.php front page not showing any output for "Global Read" accounts

### ISSUE THREAD

**Issue by adammmmm** [librenms/librenms#2415]
We're using the "old" default.php instead of tiles. The accounts of type "Global Read" don't see any output on Alertlog, Eventlog and the Up/Down boxes. Looked at default.php which seems to check the userlevel and making sure it equals or is larger than 10, while apparently Global Read is 5. So it should go for the "else" stanza, which doesn't seem to output any data in this environment.
![image001](https://cloud.githubusercontent.com/assets/12120653/11088034/6ccc3324-885f-11e5-8295-642eb3c39a3e.png)

**Comment by adammmmm** [comment]
Apparently even though it's called Global Read, I need to add device access for every device, which seems a bit weird, but at least it's a workaround.

**Comment by Rosiak** [comment]
May I ask why you are preferring the default.php over tiles.php?

**Comment by adammmmm** [comment]
Sure, first off, I can't find the same type of "Device Down/Device rebooted" widget in tiles, while the availability map sort of fills the same role, you still have to mouseover a red/orange square to find out which device is having a problem.
I also prefer the alertlog entries instead of the alert notifications that's used in tiles.php, takes less screen estate.
Finally, when trying to create a "global"(NOC) tiles dashboard it doesn't seem to play too well with different screen resolutions.
In my personal opinion, default.php does everything well without having to configure much, you get the information you need at a glance, so I appreciate the option to run it is still there!

**Comment by adammmmm** [comment]
Just an update, the red Device Down box isn't coming up for Global Read even though device access is added for every device, the "Device Rebooted" are all appearing.

**Comment by laf** [comment]
PR submitted.

The boxes and alert log are easy to add as widgets.

I've also done a PR to make the dashboard responsive which should fix the different sized windows.
