### ISSUE TITLE
DHCP APP Fortigate

### ISSUE THREAD

**Issue by fran-nlt** [librenms/librenms#2416]
Hi
I have Fortigate with DHCP enabled.
In LibreNMS I can select a APP for the monitoring, but not viewed DHCP

![sin titulo](https://cloud.githubusercontent.com/assets/13962782/11092362/86f1463e-8861-11e5-9261-192baec5123f.jpg)

**Comment by laf** [comment]
@fran-nlt The apps are for installing check_mk on the end device but this doesn't include dhcpd support anyway. What is it you want to monitor from dhcpd?

**Comment by fran-nlt** [comment]
I would like to display the IP addresses that are available for assignment.

**Comment by paulgear** [comment]
:+1:

**Comment by Rosiak** [comment]
We could perhaps use newly introduced http://docs.librenms.org/Extensions/Component/

@fran-nlt 
Could you supply some more data from the device itself?

**Comment by fran-nlt** [comment]
Yes, i can download official MIB from the WebSite

**Comment by fran-nlt** [comment]
Or what you need :)

**Comment by Rosiak** [comment]
I would like SNMP data from the device itself.

**Comment by Rosiak** [comment]
No info, closing.
