### ISSUE TITLE
Application updated fails

### ISSUE THREAD

**Issue by nenad007** [librenms/librenms#2426]
When I select a application to monitor the Query exeucted is:

INSERT INTO `applications` (`device_id`,`app_type`) VALUES ('1','nginx')

This fails, because the table require for app_status and app_instance a Value that is not null.

016.sql > ALTER TABLE  `applications` ADD  `app_status` VARCHAR( 8 ) NOT NULL ;
067.sql > ALTER TABLE `applications` ADD COLUMN `app_instance` varchar(255) NOT NULL;

Fix:
ALTER TABLE `applications` MODIFY COLUMN  `app_status` VARCHAR( 8 );
ALTER TABLE `applications` MODIFY COLUMN `app_instance` VARCHAR(255);

**Comment by f0o** [comment]
we should fix the query to include empty string values instead of NULL.

**Comment by nenad007** [comment]
fixed:

ALTER TABLE applications MODIFY COLUMN app_status VARCHAR( 8 ) DEFAULT '';
ALTER TABLE applications MODIFY COLUMN app_instance VARCHAR(255) DEFAULT '';
