### ISSUE TITLE
High CPU

### ISSUE THREAD

**Issue by joseaugustocardoso** [librenms/librenms#2431]
A virtual setup with 8 CPU core (2.0 GHz) and 16GB RAM for "only" 200 hosts can be performance issue?

Have moments that all 8 cores are with 100% of usage.

Its normal?

(https://cloud.githubusercontent.com/assets/15846428/11169118/0514c5b4-8b95-11e5-95bb-9da981aa480c.png)

**Comment by SaaldjorMike** [comment]
Load seems quite high. What is your total poll time? (Can be found at `/pollers/tab=pollers/`)

**Comment by joseaugustocardoso** [comment]
Poller Name	Devices Polled	Total Poll Time	Last Ran
RIO-SRMG-0603	201	2454 Seconds	2015-11-15 18:15:56

(https://cloud.githubusercontent.com/assets/15846428/11170769/2abd8d16-8bc5-11e5-9d0f-0fffb15e056c.png)

**Comment by joseaugustocardoso** [comment]
My environment have more 400 devices, totalling 600, but if I have problem with 200, I cant add more...

**Comment by SaaldjorMike** [comment]
That is for sure the problem. The poller runs every 5 minutes (300 seconds), and it seems like your poller takes more than 30 minutes to finish. What does the `/poll-log/` page show you? Are there any particular devices that are very slow to poll? Need to make sure polling time is below that 300 seconds mark, which can be done by either adding more cores and/or by disabling polling modules you dont use.

**Comment by joseaugustocardoso** [comment]
I can identify that are very slow (up to 900sec) was device with a lot of components, eg. Cisco Catalyst 6500, Nexus 5000 and 7000, Cisco 2900 with a lot of voice cards, Nexus 1000v. Other "simple" devices are fast to poll. I will try to disable polling modules.

**Comment by joseaugustocardoso** [comment]
Have a way to do that for all devices? (disable polling modules)

**Comment by SaaldjorMike** [comment]
You can disable poller modules globally. See more on: http://docs.librenms.org/Support/Poller%20Support

**Comment by joseaugustocardoso** [comment]
If I disable globally, can I enable for specific device latter?

**Comment by laf** [comment]
Yes you can

We poll all those device types with no issues on time.

**Comment by praburaj1985** [comment]
in my server is not showing the memory, processor and storage
