### ISSUE TITLE
Change the way alerts works

### ISSUE THREAD

**Issue by paszczus** [librenms/librenms#2433]
Hello,
I am using LibreNMS for a month and the only thing which drives me nuts is alerting system.
When one of device goes offline for few hours i`m getting e-mail about it every X minutes (by default  minutes). I have change it to 15 minutes but still there are many e-mails if device is down for a day.
Alerts are sent to gmail account and it looks like gmail is blocking e-mails for a time if there are too many of them. Now i`m getting e-mails about server which is already UP that is down and e-mails are from yesterday.
Is there any way to change those alerts to nagios-like?
In nagios first e-mail comes after 5 minutes, next after 10, next after 20, next after 40, next after 80 minutes etcetera... IMHO it`s much better way than this one in LibreNMS.

**Comment by SaaldjorMike** [comment]
You can set "Max alerts" to however many alerts you would like. AFAIK, we do not currently have a way to send alerts with different intervals for the same alert.

**Comment by laf** [comment]
Tagging #1314 

This functionality is already planned afaik. I'm closing this issue but it's now referenced for f0o in the issue number he's tracking.

**Comment by laf** [comment]
This is supposed to be closed as it's tagged in another issue.
