### ISSUE TITLE
Global Alert Rules

### ISSUE THREAD

**Issue by vectr0n** [librenms/librenms#2440]
I created a global alert rule and it showed under the global alert rules as it should, but it did not show under all the devices like a global rule should. I deleted the global alert rule and re-added it, now the rule shows under each device, but does not show under the global alert rules. 
Here is a ss of the rule being added: http://i.imgur.com/4vCqawm.png

**Comment by vectr0n** [comment]
It would seem disabling memcached resolves this issue, but someone might want to look into this issue a bit more.

**Comment by f0o** [comment]
Memcache has a 5minute retention time and isnt flushed on changes. This is likely the issue

**Comment by vectr0n** [comment]
That's already been determined but thanks.......

-------- Original message --------

**Comment by vectr0n** [comment]
With the help from people on IRC, this was already determined to be the issue.
