### ISSUE TITLE
Can't remove interface by bill 

### ISSUE THREAD

**Issue by HostioSolutions** [librenms/librenms#2446]
Some bill ports will random duplicate and can't remove see:
https://i.gyazo.com/70fa41e47ff547938561626be5928e8d.png

**Comment by laf** [comment]
What browser are you using @HostioSolutions?

**Comment by HostioSolutions** [comment]
Chrome but on IE still not working.

Do you have skype i can show you ?

**Comment by laf** [comment]
I don't use it I'm afraid. What version of LibreNMS are you using? Either check /about/ page in webui or git log -n 1 in cli.

**Comment by HostioSolutions** [comment]
LibreNMS is an autodiscovering PHP/MySQL-based network monitoring system.
Version	6e1e6b6
DB Schema	#75
Apache	2.4.7 (Ubuntu)
PHP	5.5.9-1ubuntu4.14
MySQL	5.5.46-0ubuntu0.14.04.2
RRDtool	1.4.7

**Comment by laf** [comment]
That's recent enough. We'll take a look but an initial check with Chrome earlier and I couldn't replicate the issue.

**Comment by laf** [comment]
Billing has undergone a big overhaul a bit ago, closing as no longer relevant most likely
