### ISSUE TITLE
API feature request: list devices by "Device Groups"

### ISSUE THREAD

**Issue by cultcom** [librenms/librenms#2451]
I defined some device groups for our network equipment and would like to have an API path to request those devices.

**Comment by Rosiak** [comment]
Are you asking for a API path to request a list of existing groups or a path to request devices in a specific group?

**Comment by laf** [comment]
I think the latter.

**Comment by laf** [comment]
Or both actually, makes more sense.

**Comment by cultcom** [comment]
I asked for a list of devices within a specific group, but actually both options make sense.

**Comment by laf** [comment]
The PR should cover it all don't worry :)
