### ISSUE TITLE
Active Directory nested groups not working

### ISSUE THREAD

**Issue by cultcom** [librenms/librenms#2452]
with "active_directory" authentication nested group membership seems to be ignored.

User is in group A

Group A is in Group "APP_LibreNMS_User"

$config['auth_ad_groups']['APP_LibreNMS_User']['level'] = 5;

--> does not work.

**Comment by fstern** [comment]
So basically you have another group inside the APP_LibreNMS_User group?

**Comment by ciscoqid** [comment]
This might help with nested group enumeration:

   
http://stackoverflow.com/questions/12313922/ldap-nested-group-filter-for-microsoft-ad

Mark

-- 
Mark D. Nagel, CCIE #3177 Emeritus <mnagel@willingminds.com>
Principal Consultant, Willing Minds LLC (http://www.willingminds.com)
cell: 949-279-5817, desk: 714-495-4001, fax: 714-844-4698

** For faster support response time, please
** email support@willingminds.com or call 714-495-4000

**Comment by cultcom** [comment]
@fstern: yes, that is a quite typical role mapping schema

@ciscoqid: that filter is working quite well for old 2.2 apache ldap filter, but I don't know how it could help me with the librenms config

**Comment by fstern** [comment]
Thanks, I'll have a look at this.
