### ISSUE TITLE
Transparent graph background on overlib graphs of minigraphs

### ISSUE THREAD

**Issue by SaaldjorMike** [librenms/librenms#2453]
Going to `/device/device=210/tab=ports/view=minigraphs/graph=bits/` will show larger graph when mouse is over the mini-graphs. The graph background seems to be transparent instead of white.

**Comment by SaaldjorMike** [comment]
Same goes for `/routing/protocol=bgp/` when hovering over the local+peer ip address.

**Comment by paulgear** [comment]
Seems we could close this one, @SaaldjorMike

**Comment by SaaldjorMike** [comment]
Yeah. Both cases are fixed.
