### ISSUE TITLE
Feature Request: Device Flap Detection

### ISSUE THREAD

**Issue by vectr0n** [librenms/librenms#2459]
I think it would be helpful for a lot of people if LibreNMS is able to detect a flagging device and not complain about that device taking a long time to poll, this is due to the device flapping. Have the ability to send alerts for a device that is flapping would be handy.
.

**Comment by x3m** [comment]
+1

**Comment by vizay** [comment]
+1 to the idea.

However on a more practical level, wouldn't it be hard to identify a flapping device if polling is done once every 300 seconds?

**Comment by f0o** [comment]
@vizay :+1: that's exactly what I just thought of as well while reading OP

**Comment by Rosiak** [comment]
Don't we already have the data in device_perf?

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-device-flap-detection/731
