### ISSUE TITLE
Alerts Widget

### ISSUE THREAD

**Issue by vectr0n** [librenms/librenms#2463]
I have come across a cosmetic error in the alerts widget. The box does not extend down to the bottom of the alerts like it should, please see screenshot.
http://i.imgur.com/h8lgWNZ.png

**Comment by laf** [comment]
You just need to expand the box itself. Unfortunately it doesn't appear that we can resolve this. The tile library we use have an open issue to enable call backs to resize the content in widgets but it's not available yet so I think we're kind of stuck unless someone re-implements the library we use.

**Comment by Rosiak** [comment]
Did #2414 fix this?

**Comment by f0o** [comment]
@rosiak nope

**Comment by laf** [comment]
#2414 won't have fixed it. Last time I checked the tile library doesn't support callbacks so when widgets are resized we can perform updates.

**Comment by laf** [comment]
Unfortunately the library still doesn't support this so I'm closing the issue.
