### ISSUE TITLE
Expose a group in the api for Oxidized

### ISSUE THREAD

**Issue by murrant** [librenms/librenms#2464]
I'm looking for a way to expose a single group for each device in the api to oxidized.  The goal is to be able to set authentication in Oxidzed for groups of devices.  To do that I need a group defined, right now they are all just default.

The problem is oxidized allows only one group per device and LibreNMS allows many.  We could have documentation that specifies specific naming of groups such as "oxidized_routers" to be exposed by the oxidized api and if there are multiple groups then have some logic to pick just one.  The only problem is that leaves a lot of room for misconfiguration.

Another route could be to add specific UI to set the Oxidized group and require that per device, but that requires user intervention for each device and doesn't allow usage of the neat group definitions in LibreNMS.

Any thoughts or suggestions on how to solve this?

**Comment by murrant** [comment]
This is the feature I'm looking to take advantage of in Oxidized.

"Introduce group level configuration for auth"
https://github.com/ytti/oxidized/commit/34af261b7928ba7d62496d2d87fbe64b1badc930

**Comment by SaaldjorMike** [comment]
:+1: for the possibility of having groups exposed using the API. I have different credentials for different groups of devices.

**Comment by chrisgfx** [comment]
Hi,

I posted a issue in Oxidized about the same request of feature and the developers told me about the same needs asked in LibreNMS.

Any news of this feature with the API ?

**Comment by Rosiak** [comment]
Thoughts @librenms/reviewers ?

**Comment by murrant** [comment]
I'll test it later this week.  Thanks Neil!

**Comment by SaaldjorMike** [comment]
@murrant See the following link for a sample config on how to specify the http source inside Oxidized to match the groups returned by LibreNMS:
https://github.com/ytti/oxidized/issues/259#issuecomment-170661830
Feel free to contact me if you need help setting it up.
