### ISSUE TITLE
Add message when acknowledging alert

### ISSUE THREAD

**Issue by x3m** [librenms/librenms#2472]
Hi,

Don't you think it's good to be able to add note/comment when acknowledging alert. Even to add multiple of notes/comments with timestamps. 

This way rest of the team will be aware what is the situation about it and how things develop with the time.

I don't know why such simple feature is not available :) am I the only one that thinks it's good?

**Comment by SaaldjorMike** [comment]
:+1:

**Comment by samyscoub** [comment]
:+1:

**Comment by x3m** [comment]
Let's hope that some of the devs will implement it soon :)

**Comment by Rosiak** [comment]
:+1:

**Comment by f0o** [comment]
:+1: might have chance to draft something tomorrow

**Comment by laf** [comment]
Please check #2596 for some more info on what to add.

**Comment by Alastair-VOIPUNLIMITED** [comment]
+1

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-add-message-when-acknowledging-alert/875

**Comment by laf** [comment]
Pull request now in for this: https://github.com/librenms/librenms/pull/8433
