### ISSUE TITLE
Alert rules regexes not matching correctly

### ISSUE THREAD

**Issue by mayu30687** [librenms/librenms#2473]
Alert rule having the following expression ports.ifDescr ~ "Eth.*net" should match Ethernet. However  the rule fails to match the correct pattern. 

Looking at the code in alerts.inc.php, the function GenSql which converts the configured alert rules into Sql queries.

The pretty_rule in that function expands "\*" in the alert rule to " * ". This breaks the regex pattern.
Presently if there is any "\*" operator in the alert rule it will cause the regex to fail.

Please have a look at this issue. Feel free to close if this is an expected behavior or if there is another way to configure "*" operator in the regex pattern

**Comment by f0o** [comment]
The `*` character is reserved for arithmetic. It denotes Multiplication, hence why we suggest `@` as wildcard.
