### ISSUE TITLE
Get alert notifications when muted alerts becomes better

### ISSUE THREAD

**Issue by rasssta** [librenms/librenms#2477]
So, let's assume I have a switch where 3 ports are down since they are enabled waiting for the customer(s) to enable their end. When one of the customers enable their link I want to get a notification for this.

This is currently solved by modifying alerts.php with the following:
+    foreach (dbFetchRows('SELECT alerts.device_id, alerts.rule_id, alerts.state FROM alerts WHERE alerts.state != 2 && alerts.state > 0 && alerts.open = 0') as $alert) {
+    foreach (dbFetchRows('SELECT alerts.device_id, alerts.rule_id, alerts.state FROM alerts WHERE alerts.state > 0 && alerts.open = 0') as $alert) {

Please make this behaviour configurable, if it isn't made default, since I'm sure someone else is interested in this feature.

**Comment by laf** [comment]
@f0o thoughts on this?

**Comment by remydb** [comment]
+1

**Comment by f0o** [comment]
Well... to be honest this was the default behaviour, if you ack the alert no followups or checks.

But then the IRC went on fire and I changed it a couple of months ago...

I personally prefer not being annoyed if I know that i.e. a fiber is down and the LACP keeps flapping over 4-8 ports....

So.. Config'able is doable, just dont want to have to change it in 2-3 months again haha

**Comment by laf** [comment]
This should be possible by using the ifOperStatus_prev state to check that it was down but is now up and the ifAdminStatus is up.
