### ISSUE TITLE
Cisco PIX not discovered properly

### ISSUE THREAD

**Issue by zamolxe** [librenms/librenms#2478]
For whatever reason the Cisco PIX running pixos 8.0 is reporting the sysDescr as following
```Cisco Cisco PIX Security Appliance Version 8.0(4)```
and discovery is expecting to start with "Cisco PIX"...
anyhow, here is the patch for fixing this issue
```
--- includes/discovery/os/pix.inc.php.orig	2015-11-21 10:19:34.014227065 +0000
+++ includes/discovery/os/pix.inc.php	2015-11-21 10:22:48.794213353 +0000
@@ -1,7 +1,7 @@
 <?php
 
 if (!$os) {
-    if (preg_match('/^Cisco\ PIX/', $sysDescr)) {
+    if (preg_match('/Cisco\ PIX/', $sysDescr)) {
         $os = 'pixos';
     }
 }
```
/Alex

**Comment by SaaldjorMike** [comment]
@zamolxe Will you be submitting a PR yourself?

**Comment by zamolxe** [comment]
@SaaldjorMike I would prefer that someone else will do it as I am not so familiar with this process for the time being.
