### ISSUE TITLE
Bug in alerting, applies white spaces for some unknown reason

### ISSUE THREAD

**Issue by rasssta** [librenms/librenms#2479]
The alert rule:
|151117 23:20:30| < rasm> %ports.port_descr_type = "core" && %macros.port_usage_perc >= "70" && %ports.ifType = "ethernetCsmacd" && %ports.ifDescr != "TGigaEthernet1/1"

The ifDescr, for an interface alarming, in the db:
|151117 23:22:58| < rasm>  ifDescr: TGigaEthernet1/1
|151117 23:23:01| < rasm> from the db

Running debug...
|151117 23:23:43| @laf rasm: If you run ./poller.php -h HOSTNAME -d -r -m system

...show:
|151117 23:28:09| < rasm> ports.ifDescr != "TGigaEthernet1 / 1" )

|151117 23:33:34| @laf f0o, seems the alert rules get expanded in the sql query. See the example above. DB stores fine as %ports.ifDescr != "TGigaEthernet1/1" but on debug it shows as TGigaEthernet 1 / 1. If you get chance to look at it that would be awesome

**Comment by f0o** [comment]
The reason is `maths` :/
The `/` is reserved for the divider operation.

Feel free to suggest a workaround

**Comment by laf** [comment]
Config option to disable maths functions? Not everyone needs it?

Alternatively maths functions have to be wrapped like _/_ or _*_ something like that? Would need to announce out that change so the first option is the easy win here but someone could get stuck with needing maths functions and ports with / in them :)

**Comment by f0o** [comment]
We can also try not adding spaces, not sure how SQL likes that though

**Comment by f0o** [comment]
For the log: obviously `*` is used for multiplication.

**Comment by laf** [comment]
This doesn't appear to be an issue anymore:

```
Rule #83 (test TGigaEthernet1/1):
SQL[SELECT state FROM alerts WHERE rule_id = '83' && device_id = '148' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM ports WHERE (ports.device_id = '148') && (ports.ifDescr != "TGigaEthernet1/1" )]

```
