### ISSUE TITLE
Create a 'stable' branch that tracks latest release

### ISSUE THREAD

**Issue by vrillusions** [librenms/librenms#2484]
For people like me that don't want to live on the bleeding edge but have project auto update.  Some way to tell librenms "Autoupdate to the latest released version".  Few different ways of doing that.  I just mentioned making a new `stable` branch as that's the first thing that came to mind.  Also a quick search turned up a way to tell git to [checkout latest tag](http://stackoverflow.com/a/22857288)

**Comment by f0o** [comment]
No prob :)
