### ISSUE TITLE
Alerting rules 

### ISSUE THREAD

**Issue by hari2ulinux** [librenms/librenms#2486]
HI, 

I have installed librenms on my ubuntu machine. I am new to librenms. Can anyone provide  with examples to create alerting rules in librenms. Rules like alerting when swap, physical memory usage is above threshold, alerting when tunnel,port,system goes  down, alerting when cpu usage is high , alering when inbound and outbound traffic through particular port is high etc etc.

Also can be have graphs in the alert mail same as in cacti.

**Comment by laf** [comment]
@hari2ulinux 

If you add the generic alert rules we provide they should give you a starting ground for customising them to do what you need.

You can include links to the graphs - I'd suggest stopping by our IRC channel and asking in there. I know of one user who has done this.

**Comment by hari2ulinux** [comment]
Hi Neil,

Thanks. Can you please provide links or some examples or faq to configure
alert rules.

Thanks in advance

**Comment by f0o** [comment]
Rtfm ;)
http://docs.librenms.com/Extensions/Alerting/

When you have no rules and browse to the rules page there is also a big button that will create you a handfull of default rules

**Comment by laf** [comment]
Please feel free to log onto our IRC channel and we can help further.
