### ISSUE TITLE
Feature Request - Make Temperature Sortable 

### ISSUE THREAD

**Issue by Lonecrowe** [librenms/librenms#2492]
The "Current" temperature needs to be sortable under Health/Temperature.  I know there are internal and external temps which make it a little confusing but sometimes its handy to be able to just click on the title heading to sort by that heading.  In most cases people will be looking for the highest temps.  

Possibly even a sortable option to find the highest temp closest to its range max.

**Comment by paulgear** [comment]
:+1: It looks like temperature, fan speed, and voltage are all the old-style tables; we need to change them to use bootgrid.
