### ISSUE TITLE
Alert for IPMI module not reachable

### ISSUE THREAD

**Issue by x3m** [librenms/librenms#2493]
It often happens, when you need the IPMI module to access a server, it's not accessible... 

How to actually get an alarm triggered when access/ping to IPMI module is no longer available?

**Comment by laf** [comment]
What info do you see from ipmi in LibreNMS at present (I no longer have a box with it on to test).

**Comment by x3m** [comment]
Hi,

I'm still using observium as my main NMS and exploring LibreNMS as replacement so I still don't have running LibreNMS setup, but will soon have it. 

Right now I've added one IPMI module to a server 192.168.0.103 in https://demo.librenms.org/ but nothing happened, although the credentials are pretty valid - I don't see anything happening related to that IPMI... Might be normal in the demo?

**Comment by laf** [comment]
ipmitool needs installing which I expect it's not on demo. @f0o would you mind installing?

**Comment by svennd** [comment]
IPMI does work here (you get allot of extra info on the machines, hardware wise), though you get no alarm or error when connection (info) is not working, I could change my interface to 123.123.123.123 and it just said oke updated. (not a active ip here)

@x3m ipmi is about the same information as the last observium community version, though in observium they have upgraded the options so you can choose lan settings (ipmi version and such) I have ipmi on most machines and I don't see any difference.  (I also did not need the extra options)

It would be nice if the login data could be checked if you update/insert it.

**Comment by x3m** [comment]
I'm sure the IPMI will be working in LibreNMS, but what to do about Alarming when IPMI is not reporting/not reachable? What are the options to get this? Observium is not having it either AFAIK.

**Comment by laf** [comment]
@x3m I've just taken a look and we store the results in the DB for IPMI. 

We don't however store the last timestamp in the DB, we could add an auto updating column that just updates to NOW() when an insert or update is run then you can base your rule on sensors that haven't updated in > 5m or something similar.

**Comment by x3m** [comment]
Might do the job :)

**Comment by x3m** [comment]
@laf Could you provide and example, how an alarm can be created to achieve this?

**Comment by laf** [comment]
You will need to create a macro such as:

$config['alert']['macros']['rule']['sensors_test'] = '(%sensors.lastupdate < %macros.past_30m)';

Then the rule would be: %macros.sensors_test = "1" + whatever other checks you want such as %sensors.type = 'ipmi'
