### ISSUE TITLE
Feature Request: IPAM Integration

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#2494]
- For NIPAP, PHPIpam or similar, using their API's.

**Comment by f0o** [comment]
:+1:

**Comment by Rosiak** [comment]
Could fetch usage stats for some subnets as a start.
http://phpipam.net/api-documentation/

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by rockyluke** [comment]
> LibreNMS  | f6fc5fdf71d51e3158fe785e5d1e0daeb04214f9
> DB Schema | 157
> PHP       | 5.6.29-0+deb8u1
> MySQL     | 10.1.20-MariaDB-1~jessie
> RRDTool   | 1.4.8
> SNMP      | NET-SNMP 5.7.2.1

I think @Rosiak has made a very good feature request.

**Comment by Rosiak** [comment]
Moved to community site.
