### ISSUE TITLE
Add Real Time polling of interface errors

### ISSUE THREAD

**Issue by masonke** [librenms/librenms#2497]
It would make troubleshooting a lot easier if there was a way to watch a realtime graph of the errors on an interface.  For simple L1/L2 testing, we would not need to give access to the switch or router when SFP or cables need to be replaced.

**Comment by jcounsell1222** [comment]
i second this. would make troubleshooting issues on an interface level much easier.

**Comment by paulgear** [comment]
:+1:

**Comment by laf** [comment]
Closing. Already linked to from another issue.
