### ISSUE TITLE
Feature request Agent for BIND 9.6.1+ stats server

### ISSUE THREAD

**Issue by nenad007** [librenms/librenms#2499]
A agent for the BIND statistics server (since 9.6.1) would be great.

**Comment by f0o** [comment]
What's the gain?
Doesnt that server also just trigger rndc stats and present it in xml?

Thats the same source of information that we use now, parsing the xml than the bare source sounds like unecessary overhead to me

**Comment by nenad007** [comment]
No, it's completely different, since 9.10 the old stats fromat v2 is no longer available, there exist only the new v3 format that can be accessed over statistics channel in xml or json format. 

https://www.isc.org/blogs/bind-9-10-statistics-troubleshooting-and-zone-configuration/

**Comment by f0o** [comment]
Legit, will dig into it

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
