### ISSUE TITLE
Update functionality

### ISSUE THREAD

**Issue by paulgear** [librenms/librenms#25]
tooms pointed me to https://github.com/midgetspy/Sick-Beard/blob/development/sickbeard/versionChecker.py, which implements checking of the installed version of a package against the current version in github.  The overall approach it uses is something like this:
- get commit id of local head: git rev-parse HEAD
- get name of current branch: git symbolic-ref -q HEAD
- get list of commits from github: https://api.github.com/repos/librenms/librenms/commits

One can also compare 2 commits and tell someone how far behind or ahead of the HEAD of a branch they are: http://developer.github.com/v3/repos/commits/

I think we should put some checks like this in the about page or the system overview status box eventually.

**Comment by f0o** [comment]
Is this still relevant or did it obsolete?

**Comment by laf** [comment]
I kind of made it obsolete by popping the 7 chars of the sha hash in the about us page so we can quickly check what version a users on. 

This seemed a bit ott.

**Comment by paulgear** [comment]
Yeah - I think we can just close this; @laf has done some good work on making the about box give useful info, and auto-update works.
