### ISSUE TITLE
Enhancement in alerting

### ISSUE THREAD

**Issue by mail3dexter** [librenms/librenms#2500]
Alerting content doesn’t specify detailed information.
The initial alert nor the recovery alert doesn’t specify any details about the port which is recovered. It just gives generalized output.

Is it possible to separately specify or mark (bold/italic/color) the port which has caused this alert?

E.G.:

Device r1-jpr-sw1 recovered from Port Status
Changed (From Up --> To Down)
Severity: critical
Time elapsed: 9m 12s
**port_id => 473; ifDescr => ge-0/0/0;**
Timestamp: 2015-11-25 03:05:06
Unique-ID: 548
Rule: Port Status Changed (From Up --> To Down)
Alert sent to: NOC

**Comment by f0o** [comment]
Thats the default 'One-Size-Fit-All' template. You can define own templates and access all details from the incident as we do a snapshot of the db-tables when an incident happens.

We got that covered in the docs though, if you dont think they're usefull then please help us enhance them :)

**Comment by f0o** [comment]
Proposing close in 48h
