### ISSUE TITLE
Add `advanced Inputfield` to Alert-Rules for expert users 

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#2504]
Just a textarea or inputfield, nothing fancy, no UI interpretation - people using this are _required_ to know what they're doing

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
