### ISSUE TITLE
Enhancement: Provide more alert rule examples

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#2506]
For the docs.
Fire away!

**Comment by hlmtre** [comment]
// send an alert if the device is a server and the storage is above the warning level
%storage.storage_perc > %storage.storage_perc_warn && %devices.type = "server"

**Comment by Rosiak** [comment]
VMware LAG
```
%devices.os = "vmware" && %ports.ifType = "ieee8023adLag" && %ports.ifDescr !~ "Link Aggregation @, load balancing algorithm: Source ip address hash"
```

**Comment by f0o** [comment]
High Memory:
`%macros.device_up = "1" && %mempools.mempool_perc >= "90" && %mempools.mempool_descr = "Virtual@"`

High CPU (per core usage, not overall):
`%macros.device_up = "1" && %processors.processor_usage >= "90"	`

**Comment by Rosiak** [comment]
%macros.port_usage_perc >= "80" && 
%port.port_descr_type != "client" && 
%ports.ifType != "softwareLoopback" &&

**Comment by fubecka** [comment]
There aren't any examples of using regex in the alerts, I'd love if someone could include a few of those.
