### ISSUE TITLE
Alert for CPU and RAM

### ISSUE THREAD

**Issue by fran-nlt** [librenms/librenms#2509]
Hi
I Can´t create alert for the CPU is over 80%
I Can´t create alert for the RAM is over 80%

Some help please

**Comment by fran-nlt** [comment]
Hi
The Alert of CPU is Work
But the RAM don´t work.

Some Example?

**Comment by f0o** [comment]
Memory:
`%mempools.mempool_perc >= "80" && %mempools.mempool_descr ~ "@irtual@"`

CPU:
`%processors.processor_usage > "90"`

These rules may only work for servers but they're a good start :)

**Comment by fran-nlt** [comment]
Thanks.
Look Please
Alert For CPU is Work

![1](https://cloud.githubusercontent.com/assets/13962782/11426450/2d201104-943b-11e5-8f72-152d944ce4fe.JPG)
![2](https://cloud.githubusercontent.com/assets/13962782/11426452/317757ee-943b-11e5-8689-2e7e137e008a.JPG)

**Comment by f0o** [comment]
I doubt the CPU alert will work, your processor_descr has an invalid value.

**Comment by fran-nlt** [comment]
@irtual@  but my image is Main Memory I must change for this @ain @emory??

**Comment by fran-nlt** [comment]
Thanks!
is Work!

**Comment by fran-nlt** [comment]
![1](https://cloud.githubusercontent.com/assets/13962782/11427780/989cf52e-9444-11e5-8fc6-dc0c999cf2cb.JPG)

**Comment by f0o** [comment]
:+1:
