### ISSUE TITLE
Muted Alerts

### ISSUE THREAD

**Issue by vectr0n** [librenms/librenms#2512]
It would seem that muted alerts do not clear themselves after the device has come back online. I had 3 alerts muted, and they did not clear till I unmuted them. All the devices have been back up and running for days now and graphing just fine. If you need any other information don't hesitate to ask.

**Comment by f0o** [comment]
Tested against upstream and cant reproduce :/
Checked the code and it doesnt bother about the alert status as long as it's not 0 (which means it's already resolved).

Can you give us any more info about it? (as much as possible)

**Comment by laf** [comment]
Proposing to close in 48 hours.

@vectr0n if you have any information on this then please re-open the issue.
