### ISSUE TITLE
Not getting CPU and Memory on Huawei switches

### ISSUE THREAD

**Issue by x3m** [librenms/librenms#2520]
Hi,

I'm not getting memory usage and cpu usage graphs for Huawei S6700 and S5710 devices. On observium that I was also testing I'm having those graphs.

What could be the reason?

**Comment by Rosiak** [comment]
Probably the code that hasn't been written yet.
Could you please post the output of an SNMPWALK, I'll have a look then.

**Comment by x3m** [comment]
Done, 

find attached file.
[snmpwalk-hua-s5710.txt](https://github.com/librenms/librenms/files/46566/snmpwalk-hua-s5710.txt)

**Comment by x3m** [comment]
Did you manage to work on this?

**Comment by Rosiak** [comment]
Hi @x3m 
Sorry I've been busy with work and personal stuff. 
Won't be able to look at it before Sunday earliest.

**Comment by laf** [comment]
@x3m what would be helpful as well is the output of:

```bash
./discovery.php -h HOSTNAME -d
./poller.php -h HOSTNAME -d -r
```

**Comment by x3m** [comment]
Hi,

here is the output of both.

[poller-results.txt](https://github.com/librenms/librenms/files/49693/poller-results.txt)
[discovery-results.txt](https://github.com/librenms/librenms/files/49692/discovery-results.txt)

**Comment by laf** [comment]
@x3m 

I'm hoping the tagged PR will fix this. Once it's merged if you can update and re-run a full discovery / poller for one of the devices and see that would be great. If it still doesn't work then we need another debug output again.

**Comment by x3m** [comment]
Yes, 

after the last git pull, it's now working properly. Thanks.

**Comment by x3m** [comment]
One, maybe small glitch is with the names of the CPU and Mem pools.

Here is screenshot from Obs, where the names seem more logical, and also from Libre, where the names are not ok.

![librenms names of cpuandmem](https://cloud.githubusercontent.com/assets/741774/11561350/889d86f8-99cf-11e5-846b-699004cd5cdc.png)
![obs names of cpuandmem](https://cloud.githubusercontent.com/assets/741774/11561349/889d4224-99cf-11e5-9536-5c08536e76e3.png)

**Comment by SaaldjorMike** [comment]
Hi @x3m 
I've removed one of your screenshots.
Please dont post pictures from obs. Try instead to describe what sort of behaviour you'd like.

**Comment by x3m** [comment]
Okay, 

I'm expecting my Processors and Memory pools to have proper names, like "MPU Board 0" instead of the ones that is coming now "S6700-24-EI........" which is quite long.

**Comment by x3m** [comment]
Can we do something about this, or if the issue remains closed, nobody will pay attention anymore?

**Comment by SaaldjorMike** [comment]
Hi @x3m, As this is a separate issue I'd open a new issue for what you describe.
