### ISSUE TITLE
Python errors reported by mail

### ISSUE THREAD

**Issue by bpetit** [librenms/librenms#2521]
Hi,

There are regular mail sent to librenms user on my librenms master instance:
```text
From librenms@myserver  Thu Nov 19 21:10:27 2015
Return-Path: <librenms@myserver>
X-Original-To: librenms
...skipping...
Received: by myserver (Postfix, from userid 999)
        id 838C1BF6F6; Mon, 30 Nov 2015 14:25:47 +0100 (CET)
From: root@myserver (Cron Daemon)
To: librenms@myserver
Subject: Cron <librenms@myserver>    /opt/librenms/cronic /opt/librenms/poller-wrapper.py 16
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/opt/librenms>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=librenms>
Message-Id: <20151130132547.838C1BF6F6@myserver>
Date: Mon, 30 Nov 2015 14:25:47 +0100 (CET)

Cronic detected failure or error output for the command:
/opt/librenms/poller-wrapper.py 16

RESULT CODE: 0

ERROR OUTPUT:
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/librenms/poller-wrapper.py", line 257, in printworker
    worker_id, device_id, elapsed_time = print_queue.get()
AttributeError: 'NoneType' object has no attribute 'get'
```
I use a distributed poller in addition to the master instance. May be it's linked...

I'm using latest version of librenms on the master instance, commit 82272d0c8832d2f3ce3d4a369f95f7d09084038e

and commit b58c178f1bc1d4df9eb71ab177c99699809d6e43 on the distant poller.

Some graph are also never drawn, for example, on some devices:
```
storage-hrstorage-_dev_da0s4d,_mounted_on___.rrd
```
file is present and graph is well drawn, but:
```
storage-hrstorage-_dev_da0s4d,_mounted_on___config.rrd
storage-hrstorage-_dev_md17,_mounted_on___tmp.rrd
storage-hrstorage-_dev_md18,_mounted_on___var_rundb.rrd
storage-hrstorage-_dev_da0s3d,_mounted_on___var_tmp.rrd
storage-hrstorage-_dev_da0s3e,_mounted_on___var.rrd
```
are never created, whereas they are created and correctly modified for other devices.

All those devices are Juniper EX3300 running on Junos 12.3R11.2 polled by the distributed poller.

I wonder if this issue and the errors sent in the emails are linked.

Any idea ?

Thanks for you work and your time

**Comment by laf** [comment]
This looks like poller-wrapper.py isn't able to use distributed polling due to memcached. What happens when you run it manually?

**Comment by bpetit** [comment]
On the distributed poller:

root@poller:/opt/librenms# ./poller-wrapper.py
Registered as Node joining Master myserver

INFO: starting the poller at 2015-12-01 12:35:21 with 16 threads, slowest devices first
INFO: worker Thread-3 finished device 49 in 4 seconds
INFO: worker Thread-4 finished device 50 in 5 seconds
INFO: worker Thread-2 finished device 51 in 12 seconds
INFO: worker Thread-1 finished device 55 in 17 seconds
INFO: poller-wrapper polled 4 devices in 18 seconds with 16 workers
Finished 1448973340.41.

On the master:

root@myserver:/opt/librenms# ./poller-wrapper.py
Registered as Master
INFO: starting the poller at 2015-12-01 13:35:58 with 16 threads, slowest devices first
INFO: worker Thread-1 finished device 20 in 5 seconds
INFO: worker Thread-2 finished device 18 in 5 seconds
INFO: poller-wrapper polled 2 devices in 6 seconds with 16 workers
Wait for all poller-nodes to finish
Clearing Locks
59 Locks Cleared
Clearing Nodes
Finished 1448973364.7.

Most of the graphs are well drawn, using distributed polling. Stranger: 60% of the devices polled by the distributed poller present no problem at all.

Thanks again.

**Comment by f0o** [comment]
The error within python's threading library concerns me. It's not an issue with distributed polling so not an issue with memcached (or it's availability) either..

this is reall odd... Best to jump on IRC and ask `job` who wrote the script about it. I dont speak native Python sadly :S

**Comment by f0o** [comment]
Naive interpretation of the error:

The Thread#17 (so 16th worker thread I guess?) Could not access the shared resources as the main thread already closed the queue and removed the resources.

Some python-guru might know it better though.

**Comment by laf** [comment]
For the devices you are missing rrd files for can you pastebin the output from:

```bash
./discovery.php -h HOSTNAME -d
./poller.php -h HOSTNAME -d -r 
```

Also probably worth making sure both installs are on the same version to be safe.

**Comment by bpetit** [comment]
Of course:

./discovery.php -h switch3 -d

[test-discovery.txt](https://github.com/librenms/librenms/files/49520/test-discovery.txt)

./poller.php -h switch3 -d -r

[test-poller.txt](https://github.com/librenms/librenms/files/49536/test-poller.txt)

One thing I didn't notice earlier is the stderr output:

MIB search path: /opt/librenms/mibs/junos
Cannot find module (NOTIFICATION-LOG-MIB): At line 0 in (none)
Cannot find module (DISMAN-EVENT-MIB): At line 0 in (none)
Cannot find module (DISMAN-SCHEDULE-MIB): At line 0 in (none)
Cannot find module (MTA-MIB): At line 0 in (none)
Cannot find module (NETWORK-SERVICES-MIB): At line 0 in (none)
Cannot find module (UCD-DISKIO-MIB): At line 0 in (none)
Cannot find module (UCD-DLMOD-MIB): At line 0 in (none)
Cannot find module (LM-SENSORS-MIB): At line 0 in (none)
Cannot find module (UCD-SNMP-MIB): At line 0 in (none)
Cannot find module (UCD-DEMO-MIB): At line 0 in (none)
Cannot find module (NET-SNMP-AGENT-MIB): At line 0 in (none)
Cannot find module (IPV6-ICMP-MIB): At line 0 in (none)
Cannot find module (IPV6-TCP-MIB): At line 0 in (none)
Cannot find module (IPV6-UDP-MIB): At line 0 in (none)
Cannot find module (NET-SNMP-PASS-MIB): At line 0 in (none)
Cannot find module (NET-SNMP-EXTEND-MIB): At line 0 in (none)
Cannot find module (NET-SNMP-VACM-MIB): At line 0 in (none)
Cannot find module (Juniper-Products-MIB): At line 0 in (none)
sysUpTime.0: Unknown Object Identifier (Sub-id not found: (top) -> sysUpTime)
MIB search path: /opt/librenms/mibs
Cannot find module (MTA-MIB): At line 0 in (none)
Cannot find module (NETWORK-SERVICES-MIB): At line 0 in (none)

Could this be related ?

Thanks,

**Comment by laf** [comment]
That shouldn't cause any issues.

I can see you are running rrdcached. Can you post your config for rrdcached + rrdtool (full info -> got to /settings/ in the webui and search for both that strings).

**Comment by bpetit** [comment]
Yes:

On the master:

rrdtool	/usr/bin/rrdtool
rrdtool_version	 1.4
rrdcached_dir	.
rrdcached	127.0.0.1:42217
rrd_dir	/opt/librenms/rrd

On the distributed poller:

$config['rrdtool_version'] = 1.5;
$config['rrdcached']    = "myserver:42217";
$config['rrd_dir']	= "/opt/librenms/rrd";
$config['rrdcached_dir'] = ".";

This makes me remember I use rrdtool 1.4 on the master. During the setup it seemed not problematic to me as long as it is the distributed poller that talks remotely to rrdcached (and thus who has to use rrdtool > 1.5) but maybe it is ?

**Comment by laf** [comment]
@bpetit Are you actually running rrdtool 1.5 on master (and the poller)? If not then you need to change the poller config to version 1.4 AND make sure the poller can access the rrd directory over a shared filesystem.

Or, ensure you are actually running rrdtool 1.5 on the master.

**Comment by bpetit** [comment]
I was running rrdtool 1.5 on the poller, and rrdtool 1.4 on the master. I use rrdcached setup instead of a shared fs.

I just upgraded rrdtool to 1.5 on the master and have set the rrdtool version to 1.5 in config.php.

I'm not sure it may change anything. All faulty devices (the ones that lack rrd files) are polled by the distributed poller on which rrdtool was already in version 1.5 (and I had $config['rrdtool_version'] = 1.5; in config.php). Am I missing something ?

There is some fresh rrdcached logs about that problem:

Dec  3 13:40:28 myserver rrdcached[5681]: handle_request_update: stat (/opt/librenms/rrd/././switch4/storage-hrstorage-_dev_da0s4d,_mounted_on___config.rrd) failed.
Dec  3 13:40:28 myserver rrdcached[5681]: handle_request_update: stat (/opt/librenms/rrd/././switch4/storage-hrstorage-_dev_da0s3e,_mounted_on___var.rrd) failed.
Dec  3 13:40:28 myserver rrdcached[5681]: handle_request_update: stat (/opt/librenms/rrd/././switch4/storage-hrstorage-_dev_md17,_mounted_on___tmp.rrd) failed.

It seems like the emails sent to librenms on the master and the missing rrd files are two different problems. Should I create a second issue to deal with missing rrds ?

Anyway, it is really strange that storage-hrstorage-_dev_*,_mounted_on___*.rrd *are* created for some other devices (as I said, same devices, same JunOS version, same snmp config)

Thanks for you help,

**Comment by laf** [comment]
Are all the devices handled by that one single poller? As you didn't have rrdtool 1.5 on the master then the rrd files would never have been created so I can only assume you had a single setup to start with before moving to a distributed setup and it's since then some rrd files haven't been created.

**Comment by bpetit** [comment]
I have 22 devices polled. 20 are polled by the distributed poller. 2 are polled by the master instance.
Only 6 devices have graphs missing (like the ones I told you). All other devices seem alright.

I was using rrdtool 1.4 on the master instance but I've always been using rrdtool 1.5 on the distributed poller. Now I use rrdtool 1.5 everywhere but nothing has changed.

Thanks.

**Comment by bpetit** [comment]
Any news ?

Thanks,

**Comment by laf** [comment]
I think this is best to jump into IRC and try and catch one of us. Trying to diagnose this over github will be time consuming.

**Comment by laf** [comment]
Closing, please feel free to jump on irc to discuss.
