### ISSUE TITLE
Airfiber fixes for throughput and interface graphing

### ISSUE THREAD

**Issue by digitalcohesion** [librenms/librenms#2528]
Airfiber devices don't display throughput properly when graphed.

It seems using the default snmpwalk provides the wrong oids for the data we need. 
I found something on the UBNT forum about using 64bit counters and these OIDs 
rxOctets: .1.3.6.1.4.1.41112.1.3.3.1.6.1 
txOctets: .1.3.6.1.4.1.41112.1.3.3.1.7.1

I'm not sure about those IDs specifically, but it does look like the right data is there somewhere and it is listed as Counter64

**Comment by SaaldjorMike** [comment]
Can this be closed due to the fix in PR #2544 ?

**Comment by laf** [comment]
Think I linked to the wrong issue. Closing as it does fix this :)
