### ISSUE TITLE
Smokeping integration fails when smokeping is configured for less than 20 pings

### ISSUE THREAD

**Issue by thepacmanfan** [librenms/librenms#2532]
If smokeping is configured for less than 20 pings, the integrated graph drawing fails on the first nonexistant ping data. For instance, if smokeping is configured for 10 pings, graph drawing will fail with "ERROR: No DS called 'ping11' in '/path/to/data.rrd' "

**Comment by paulgear** [comment]
I've run into this before and will sort out a PR shortly.

**Comment by Rosiak** [comment]
@paulgear Are you on this or should we remove you from this task?

**Comment by paulgear** [comment]
I started making a patch and then got sidetracked. :-)  I'll have a look now.

**Comment by Rosiak** [comment]
Fixed #2676
