### ISSUE TITLE
Feature Request: Checkpoint Gaia OS Support

### ISSUE THREAD

**Issue by kreggz** [librenms/librenms#2533]
Checkpoint 21700 and Management servers are being detected as Linux 

I am assuming because it sees a linux kernel then it must be a server
2.6.18-92cp
2.6.18-92cpx86_64

**Comment by SaaldjorMike** [comment]
Hi @kreggz 

Please provide output from the following (remove any sensitive data):
```bash
./discovery.php -h HOSTNAME -d
./poller.php -h HOSTNAME -d -r 
```

**Comment by Tatermen** [comment]
FYI, Check Point Gaia is based on Red Hat Enterprise Linux 5.2.

**Comment by Rosiak** [comment]
Any news @kreggz ?

If not I propose we close this in 48 hrs.

**Comment by Rosiak** [comment]
Closing.
Please reopen when you have the required information.

**Comment by JeppeF82** [comment]
could this be reopened? I think it would be great with checkpoint support. Limited php skills, but I think basic discovery and a limited set of graphs to begin with should be within reach. Would also like to contribute :)

**Comment by laf** [comment]
Please provide the required info within 48 hours.

**Comment by JeppeF82** [comment]
I need some more time to test this, hopefully i'll have some working code early next week.

**Comment by mariushovind** [comment]
Hello, can this be opened again?
I have added the output requested, ip adresses are removed.

[discovery.txt](https://github.com/librenms/librenms/files/340974/discovery.txt)
[poller.txt](https://github.com/librenms/librenms/files/340975/poller.txt)
