### ISSUE TITLE
Using Proxmox Plugin

### ISSUE THREAD

**Issue by starnetwork** [librenms/librenms#2546]
Hi,
few things regarding to Proxmox Plugin
1. I added $config['enable_proxmox'] = 1;
to the config file, but I still don't see anything that related to Proxmox Extension at External Settings / System plugins Pages
2. fixing for Agent setup:
cp check_mk_xinetd /etc/xinetd.d/check_mk
should be: cp check_mk_xinetd /etc/init.d/check_mk
3. now after Agent setup is done on Proxmox node, how I should add this device to the librenms, as standard snmp settings? / special hostname and community ID?
any other things to do?

Regards,

**Comment by f0o** [comment]
No 2. Is correct. It's a xinetd config not an initscript

On 3 December 2015 11:18:22 CET, starnetwork <notifications@github.com> wrote:
>Hi,
>few things regarding to Proxmox Plugin
>1. I added $config['enable_proxmox'] = 1;
>to the config file, but I still don't see anything that related to
>Proxmox Extension at External Settings / System plugins Pages
>2. fixing for Agent setup:
>cp check_mk_xinetd /etc/xinetd.d/check_mk
>should be: cp check_mk_xinetd /etc/init.d/check_mk
>3. now after Agent setup is done on Proxmox node, how I should add this
>device to the librenms, as standard snmp settings? / special hostname
>and community ID?
>any other things to do?
>
>Regards,
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2546

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by laf** [comment]
@starnetwork you need to add the device to LibreNMS as normal. The proxmox device needs to be running snmp. Once added, ensure in the device settings that the agent for polling is enabled and that you select proxmox from the applications list:

http://docs.librenms.org/Extensions/Proxmox/

**Comment by starnetwork** [comment]
are you sure?
root@server12:/opt/librenms-agent# cp check_mk_xinetd /etc/xinetd.d/check_mk
cp: cannot create regular file `/etc/xinetd.d/check_mk': No such file or directory
and also:
how /etc/init.d/xinetd restart will work if we didn't add it to the init.d in any step of the guide here: http://docs.librenms.org/Extensions/Agent-Setup/ ?

**Comment by laf** [comment]
You probably need to install xinetd

**Comment by starnetwork** [comment]
Hi, 
thanks for that, installed, after that I added the Proxmox as snmp to the librenms
but it's add it as Generic x86 64-bit Linux 2.6.32-43-pve
I still don't see in the librenms gui any mention for Proxmox Extension at External Settings / System plugins or any other Pages, any reason?

**Comment by laf** [comment]
@starnetwork You need to enable the proxmox plugin for the device, if you edit the device and go to applications (I think)

**Comment by starnetwork** [comment]
Hi,
you mean for?
cp /opt/librenms-agent/proxmox /usr/lib/check_mk_agent/local/proxmox
chmod +x /usr/lib/check_mk_agent/local/proxmox
I did it...

**Comment by laf** [comment]
Nope :)

You'll be better off jumping on irc for us to help. Freenode ##librenms

**Comment by laf** [comment]
Nope :)

You'll be better off jumping on irc for us to help. Freenode ##librenms

**Comment by laf** [comment]
Closing this, please feel free to pop into our irc channel for help with this.
