### ISSUE TITLE
mib path error

### ISSUE THREAD

**Issue by mjsteckel** [librenms/librenms#2548]
Might be a upstream bug in net-snmp-utils, but looks strange to me. 

Note that snmpget can not find the specified MIB when the path is not included with the -m option.

Do I have something borked or is this something else?

---

[root@librenms librenms]# uname -a
Linux librenms.citywisper.co 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[root@librenms librenms]# snmpget --version
NET-SNMP version: 5.7.2

[root@librenms librenms]# sestatus 
SELinux status:                 disabled

[root@librenms librenms]# /usr/bin/snmpget -v1 -c public -Osqnv -m UBNT-AirFIBER-MIB -M /opt/librenms/mibs udp:10.0.10.240:161 fwVersion.1
MIB search path: /opt/librenms/mibs
Cannot find module (UBNT-AirFIBER-MIB): At line 35 in (none)
fwVersion.1: Unknown Object Identifier (Sub-id not found: (top) -> fwVersion)

[root@librenms librenms]# ls -l /opt/librenms/mibs/UBNT-AirFIBER-MIB 
-rw-r--r-- 1 root root 72009 Sep 18 15:58 /opt/librenms/mibs/UBNT-AirFIBER-MIB

[root@librenms librenms]# /usr/bin/snmpget -v1 -c public -Osqnv -m /opt/librenms/mibs/UBNT-AirFIBER-MIB -M /opt/librenms/mibs udp:10.0.10.240:161 fwVersion.1
v3.2-beta4.28355.150918.1133

[root@librenms librenms]# /usr/bin/snmpget -v1 -c public -Osqnv -m /opt/librenms/mibs/UBNT-AirFIBER-MIB udp:10.0.10.240:161 fwVersion.1
v3.2-beta4.28355.150918.1133

**Comment by laf** [comment]
I reckon that's an issue with the UBNT mibs If i'm honest :/

**Comment by mjsteckel** [comment]
I can easily believe that that is the case.Though it does seem a bit odd that the -M option does not work, but explicitly including the path to the mib with the -m option does. ie the following works 
"-m /opt/librenms/mibs/UBNT-AirFIBER-MIB"

I am a complete newbie when it comes to snmp,.. so please forgive the basic questions...

How do the snmp utils maps the data received from a device to a device specific mib file? I'm guessing there is a string in the snmp data received from a device that maps to the filename of the mib. With this bit of info I should be able to debug the data returned and compare it to the data in the mib.

**Comment by laf** [comment]
snmp maps numerical OIDs to names usually via the MIB. The device doesn't tell you what MIB to use, you have to tell snmp what MIB you want to use.

**Comment by mjsteckel** [comment]
Thanks. That's what I expected but appreciate the confirmation.

**Comment by laf** [comment]
Closing this, feel free to re-open if you have any further questions.
