### ISSUE TITLE
LibreNMS interface error question

### ISSUE THREAD

**Issue by jcounsell1222** [librenms/librenms#2550]
Hey guys, i could not find anything in documentation about this but i was wondering if i could get some info here. i was looking at the interface error graph and trying to figure out why the count is so much higher than what the interface counter on the switch is. is there anyway to break down what the errors are in libre?

**Comment by Rosiak** [comment]
Are you sure the number in the graph is not micro?

Like 800m

**Comment by jcounsell1222** [comment]
so in our case its showing 3.6m. is that something that can be changed to a better number like a 1 to 1 ratio.

**Comment by f0o** [comment]
@jcounsell1222 I'm not sure. The value you see is the rate over time, not an absolute datapoint. I think thats just how RRD is. But I might be mistaken

**Comment by laf** [comment]
It is possible using CDEF:

http://forums.cacti.net/viewtopic.php?t=8168

Patches greatly accepted if you would like :)

**Comment by jcounsell1222** [comment]
i would be more than happy to help you guys out but programing is not my strong suit. i am sure i can figure out something in the interim. thanks for all that you guys do!!
