### ISSUE TITLE
Enhancement: Sort device ports

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#2553]
![yada](https://cloud.githubusercontent.com/assets/6378934/11575145/d8afb3f6-9a0f-11e5-9a6e-230cd34f297e.png)

**Comment by paulgear** [comment]
What sort of device is that?

**Comment by laf** [comment]
Ports are sorted by ifIndex at present. What would you want them to be sorted by?

**Comment by Rosiak** [comment]
Well, I guess that makes sense.
I'm not sure which direction we should move in, and if we should.

But for this case it would be nice to be able to sort them by ifName, but I'm very well aware that's not the case for everyone.

```
mysql> select ifIndex,ifName from ports where device_id = 2;
+---------+---------+
| ifIndex | ifName  |
+---------+---------+
|       1 | lo      |
|       2 | eth0    |
|       3 | eth1    |
|       4 | eth2    |
|       5 | eth1.10 |
|       6 | eth1.42 |
|       7 | eth1.40 |
|       8 | eth1.30 |
|       9 | eth1.20 |
|      10 | sit0    |
|      11 | tun0    |
|      12 | eth1.50 |
+---------+---------+
12 rows in set (0.00 sec)

mysql> select ifIndex,ifName from ports where device_id = 2 order by ifName;
+---------+---------+
| ifIndex | ifName  |
+---------+---------+
|       2 | eth0    |
|       3 | eth1    |
|       5 | eth1.10 |
|       9 | eth1.20 |
|       8 | eth1.30 |
|       7 | eth1.40 |
|       6 | eth1.42 |
|      12 | eth1.50 |
|       4 | eth2    |
|       1 | lo      |
|      10 | sit0    |
|      11 | tun0    |
+---------+---------+
```

**Comment by laf** [comment]
Config option or a vote?

My preference is as it is now :)

**Comment by paulgear** [comment]
Config option.

**Comment by Rosiak** [comment]
Not sure if this is worth proceeding with, I honestly don't care :)

**Comment by f0o** [comment]
I'm with laf, current ifIndex makes sense to me so no reason to change from my pov.

Side-Q: could one use bootgrid tables for this page? If so the issue would become obsolete as bootgrid sorts it any way user demands it.

**Comment by paulgear** [comment]
@f0o :+1: to moving that to bootgrid

**Comment by Rosiak** [comment]
Will be addressed in v2
