### ISSUE TITLE
i18n usage and multi language translation

### ISSUE THREAD

**Issue by samyscoub** [librenms/librenms#2556]
Hello,

is it possible to add the i18n support into librenms for multi language feature ?

**Comment by f0o** [comment]
I'm sure its possible but it might be a long and big process. I wouldnt know where to start really :S

**Comment by samyscoub** [comment]
First you can extract every label into a global language file.

I think thaht a framework like this can make the job :

https://github.com/Philipp15b/php-i18n

**Comment by f0o** [comment]
PR's welcome :)

**Comment by Rosiak** [comment]
This will not be something I will invest time in.
But as @f0o states, PR's are welcome.

**Comment by laf** [comment]
This is being done in v2 and will be supported from day one - will just need people to add translation support
