### ISSUE TITLE
Increase global search limit

### ISSUE THREAD

**Issue by Justmeccsn** [librenms/librenms#2557]
Global search does not display all the results, as it has a limit on the number of results displayed. 

Can you please increase the limit, or make it easier for users to change the value via a global config option. 

Thanks,
Cat

**Comment by Rosiak** [comment]
Should be pretty trivial, the limit today is 8 and is defined in ajax_search.
I think a global_config option is reasonable.

**Comment by f0o** [comment]
:+1: on config

**Comment by SaaldjorMike** [comment]
Also :+1: on a config option
