### ISSUE TITLE
Add IP field into devices table even if hostname is DNS reachable

### ISSUE THREAD

**Issue by samyscoub** [librenms/librenms#2559]
Hi,

when you add the ```$config['mydomain']``` option into librenms config, hostname is filled with dns name and the IP address information is forgotten.

Into the Web UI, hostname is only visible with its DNS name.

Is it possible to change the Database model to add a 'ipaddress' field into the 'devices' table and display it into Web interface when this information is available ?

- When DNS name is available, it woulb be great to display DNS Name + IPAddress into the Web UI
- When DNS name is not available, juste display the IP address of the device.

Thanks

**Comment by Kivit** [comment]
I'd love to have hostname + IP address on the Web UI.

**Comment by f0o** [comment]
:+1: perhaps something for 2016Q1 ?

**Comment by rlphnger** [comment]
Really hoping for this in 2016/Q1, as it would be great to be able to see both hostname and ip from WebUI.

**Comment by laf** [comment]
Tagged this into #1698.

Considered duplicate so closing.
