### ISSUE TITLE
cisco SG500 os and vendor don't get identified 

### ISSUE THREAD

**Issue by flatterlight** [librenms/librenms#2561]
Librenms don't get the OS and vendor from Cisco SG500-28 switches.
latest librenms version, switch os: 1.4.1.3

if you need more information feel free to ask.

**Comment by Rosiak** [comment]
Just a note:
Works fine on SG300.

![screen shot 2015-12-05 at 13 10 16](https://cloud.githubusercontent.com/assets/6378934/11607697/8ffa11ae-9b51-11e5-8165-825709f0018c.png)

**Comment by flatterlight** [comment]
with my sg220-26 it looks better

**Comment by flatterlight** [comment]
with my SG220 it looks better

![Uploading sg220.jpg…]()

**Comment by laf** [comment]
@flatterlight is this resolved? If not we'd like to make sure it does work.

**Comment by flatterlight** [comment]
my last status is like described.
I will setup the hardware in the next days again, to report back

**Comment by laf** [comment]
If you can provide the output of:

```bash
./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -d -r -m system,os
```

**Comment by flatterlight** [comment]
Hi,
I've set up librenms from scratch, so here are the asked outputs.
discovery -> http://pastebin.com/0vQ7KTjE
poller -> http://pastebin.com/T456EdiA
If you need more infos, feel free to ask.
