### ISSUE TITLE
Allow sorting by address or description in IPv4 & IPv6 address search

### ISSUE THREAD

**Issue by paulgear** [librenms/librenms#2563]
Currently it's disabled; I had a quick hack at this and couldn't come up with something I was happy with.  Will come back to it when I have more time.

**Comment by f0o** [comment]
Search by address or subnet can be done with converting the ips to integers. Might be a pain to do now afterwards, afaik the ips are text at the moment

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-improve-search-search-ipv4-6/663
