### ISSUE TITLE
red marker on map issue

### ISSUE THREAD

**Issue by aauvinet** [librenms/librenms#2567]
Hello,

I have a issue with a red marker :
- On the first picture, we can see more devices down
- On don't see the red market on the map.

![librenms](https://cloud.githubusercontent.com/assets/15667014/11623633/8005d322-9cce-11e5-85b9-4195ce25fbb2.png)

When  I zoom on the map, I can see the red marker when device is down.

![librenms2](https://cloud.githubusercontent.com/assets/15667014/11623637/85f0f0a0-9cce-11e5-89fb-1f30927dd610.png)

I woold like see the red market on the map , not when I don't zoom the map.

Is it possible ?

André

**Comment by SaaldjorMike** [comment]
If anyone were to pick this up, I'd suggest also making sure that groupings of devices are kept in a green colour if all is ok, and not change to yellow+red if there are many devices.

**Comment by aauvinet** [comment]
:+1:

**Comment by aauvinet** [comment]
Hello,
This isn't work for me....

For exemple,  More devices is down where is the number 44. it is orange because there is lot of devices but no because is down...

![2015-15-12-librenms](https://cloud.githubusercontent.com/assets/15667014/11806574/6397e0c6-a314-11e5-9d06-222d9f236c95.png)

If I zoom 
Wee can see the devices are down.

![2015-15-12-librenms2](https://cloud.githubusercontent.com/assets/15667014/11806619/ad2724c2-a314-11e5-96d3-bb9f15e5940f.png)

I would like the red marker / number on the first picture.

Excuse me for my bad english.
I hope what you understand me.
Cdlt,

**Comment by aauvinet** [comment]
I do :  
./daily.sh for update the librenms on my server.

**Comment by SaaldjorMike** [comment]
@aauvinet The new PR is not merged yet, which is why you still see the same old behaviour.

**Comment by aauvinet** [comment]
Ok....
I wait quietly
