### ISSUE TITLE
VMWare ESXi 5.5 mempool info is stored in storage table

### ISSUE THREAD

**Issue by Kivit** [librenms/librenms#2569]
LibreNMS is storing the memory related data inside mysql table "storage" instead of "mempool".
Hope I described my problem clearly enough. I'll try to answer if you guys have any questions.

2x servers running:
VMware ESXi 5.5.0 build-1331820 VMware, Inc. x86_64
1x server running:
VMware ESXi 5.5.0 build-2068190 VMware, Inc. x86_64
Hardware is different on all 3 (so it can't be hardware specific problem).

mysql export of storage table data that should be in mempool table:

-- Dumping data for table `storage`

INSERT INTO `storage` (`storage_id`, `device_id`, `storage_mib`, `storage_index`, `storage_type`, `storage_descr`, `storage_size`, `storage_units`, `storage_used`, `storage_free`, `storage_perc`, `storage_perc_warn`, `storage_deleted`) VALUES
(26, 6, 'hrstorage', 10, 'hrStorageTypes.20', 'Real Memory', 77207953408, 1024, 22769856512, 54438096896, 29, 60, 0),
(36, 5, 'hrstorage', 10, 'hrStorageTypes.20', 'Real Memory', 68689395712, 1024, 45610459136, 23078936576, 66, 60, 0),
(46, 4, 'hrstorage', 10, 'hrStorageTypes.20', 'Real Memory', 34347589632, 1024, 19170832384, 15176757248, 56, 60, 0);

**Comment by Kivit** [comment]
Output for the mentioned 3 servers:

./discovery.php -h HOSTNAME -d -r -m storage
http://pastebin.com/UGqQg1Su
http://pastebin.com/H8ggRbwD
http://pastebin.com/tQkU4YEK

./poller.php -h HOSTNAME -d -r -m storage
http://pastebin.com/ikhufQC9
http://pastebin.com/ErhbmTez
http://pastebin.com/JbPi0xsz

Links are in order.

**Comment by laf** [comment]
Sorry would you mind also providing the output of:

```php
./discovery.php -h HOSTNAME -d -m mempools
./poller.php -h HOSTNAME -r -d -m mempools
```

**Comment by Kivit** [comment]
Sure.

./discovery.php -h HOSTNAME -d -m mempools
http://pastebin.com/Ly58qYSB
http://pastebin.com/1zCHwyVM
http://pastebin.com/ui0fspwm

./poller.php -h HOSTNAME -r -d -m mempools
http://pastebin.com/RcixNyeA
http://pastebin.com/VjCHPYjc
http://pastebin.com/xaisqYrJ

**Comment by laf** [comment]
PR has been done for this. If you want to test then please ensure you have a clean working directory:

```bash
cd /opt/librenms
git remote add laf https://github.com/laf/librenms
git remote update laf
git checkout issue-2569
./discovery.php -h HOSTNAME -d -m storage,mempools
```

If this works (and retains the data for memory but in the correct section) then please report back.
