### ISSUE TITLE
Allow custom info to be added via API call to Notes section

### ISSUE THREAD

**Issue by djtecha** [librenms/librenms#2570]
I was thinking it would be a really nice feature if I could craft a script that could be run on a client and update a field in librenms. For instance we have custom binary versions and I would simply like to be able to create a table with the SW and version number like so.

Puppet: 4.2
JDK: 7.0
MISC: 3.3

I was thinking this could just be a free form that leaves it up to the user to craft their script in the correct manner and plug it into the notes section.

**Comment by f0o** [comment]
:+1:
