### ISSUE TITLE
Hipchat Integration not working

### ISSUE THREAD

**Issue by benjaminburzan** [librenms/librenms#2574]
I have been trying to get the Hipchat integration to work. 
Here is what I am doing:

1) Testing the API call using curl - this works without problems
```
curl -X "POST" "https://api.hipchat.com/v1/rooms/message?auth_token=<my_auth_token>" \
	-H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" \
	--data-urlencode "room_id=<my_room_id>" \
	--data-urlencode "message=Sample Message" \
	--data-urlencode "from=LibreNMS"
```
2) Adding those data to the Alert Settings (using the web interface)
```
Hipchat URL: https://api.hipchat.com/v1/rooms/message?auth_token=<my_auth_token>
Room ID: <my_room_id>
From: LibreNMS
```
_and leaving the configuration options field blank_

3) When I hit `Test transport`, the button color turns red

Can you help me out with this issue?
Thank you !
Ben

**Comment by f0o** [comment]
Do you have php's curl extension installed?

**Comment by benjaminburzan** [comment]
Yes, I have php5-curl installed. Is there any kind of log I can look into? The error_log doesn't provide any message regarding this issue ..

**Comment by f0o** [comment]
Just to make sure, after installing the curl extension did you restart apache/fpm/... ?

As for logs, edit your cronjob and make the alerts.php job log to file. It will be noisy if curl fails.
Bare in mind that the alerts job honours all the delay/interval/count options from your alerts so you might not be able to trigger it OnDemand.

**Comment by benjaminburzan** [comment]
I restarted (in my case) nginx again just to double check that I really did. 
Thanks @f0o for your hint with alerts.php. I'll check the output and let you know what happened.

**Comment by f0o** [comment]
Ah for nginx you must restart the php-fpm service :)

**Comment by benjaminburzan** [comment]
Yep, I did that too :-)

**Comment by benjaminburzan** [comment]
Here is the message I am getting.
```
Issuing Alert-UID #68/1: ; ; mail => OK; ; ; pushbullet => OK; ; ; ; hipchat => string(103) "API 'https://api.hipchat.com/v1/rooms/message?auth_token=<my_auth_token>' returned Error"
string(8) "Params: "
string(89) "Return: {"error":{"code":400,"type":"Bad Request","message":"Unknown message format: ."}}"
ERROR; 
```
Did anyone or you @f0o set the message format? I guess in the filed I left blank.

**Comment by laf** [comment]
@benjaminburzan Can you try this patch please:

https://gist.github.com/laf/922e1ba47c3dbe476b85

**Comment by benjaminburzan** [comment]
How do I apply this patch? I tried it with `git apply --check gistfile1.txt` and got `fatal: corrupt patch at line 43`.

**Comment by laf** [comment]
You might just need to add new line to the file

**Comment by benjaminburzan** [comment]
Ok I'm able to apply the patch and its working! I receive the test notification in my hipchat room. Great stuff, thank you for you help!

**Comment by laf** [comment]
@benjaminburzan I will submit a PR to fix this, you will at some stage most likely need to remove the patch (git checkout includes/alerts/transport.hipchat.php) when the patch is officially merged in.

**Comment by benjaminburzan** [comment]
@laf Great, thanks!
