### ISSUE TITLE
Can not add any Widget to Dashboard

### ISSUE THREAD

**Issue by dhavalsoni88** [librenms/librenms#2576]
I've just installed fresh LibreNMS version "8a1573a". after login to admin area 1st time, I am trying to create Dashboard. when I select any widget from "Select Widget Drop down menu", i am not getting "Add Widgets" button enable.

**Comment by laf** [comment]
@dhavalsoni88 The add widget button isn't actually a button, when you select the widget you want it dynamically adds it in.

If you don't see the widget being added do you see any errors or anything in the browsers console?

**Comment by dhavalsoni88** [comment]
No, it did not show any error or anything on browser console.

**Comment by laf** [comment]
@dhavalsoni88 Do you have mysql strict mode on?

Widgets work in general for people so this is something specific to your setup - have you followed the instructions correctly when installing?

**Comment by dhavalsoni88** [comment]
MySQL Strict mode is disabled on server:

mysql> SELECT @@GLOBAL.sql_mode;
+-------------------+
| @@GLOBAL.sql_mode |
+-------------------+
|                   |
+-------------------+

**Comment by laf** [comment]
Try the dashboard on demo:

demo.librenms.org
u/p: demo

If it doesn't work there then it has to be your browser, if it does then it's got to be your install.

**Comment by dhavalsoni88** [comment]
Yes I can see the dashboard of demo server, but can you please suggest why my dashboard is not working even after fresh installation?

my System Specs is as below:
CentOS 6.7, 4 Gig RAM, 2 vCPU, Apache 2.2.15, PHP 5.3.3, MySQL 5.5.46 and RRD 1.4.7

PHP modules installed on my system:
apc
apcu
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
gmp
gv
hash
iconv
igbinary
json
libxml
mbstring
mcrypt
memcache
memcached
mongo
msgpack
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib

**Comment by laf** [comment]
PHP 5.3.3 - upgrade. We try and support at least 5.4 but 5.3 is pushing it - released just over 5 years ago.

**Comment by Rosiak** [comment]
Just a note I have installs running on PHP 5.3.3 with no issues.

**Comment by dhavalsoni88** [comment]
Its fixed now, I've increased PHP memory limit to 256 MB and post_max_size = 20M.

**Comment by Rosiak** [comment]
Proposing closing this, any objections @laf ?
