### ISSUE TITLE
IPMI allow interface type and userlevel

### ISSUE THREAD

**Issue by djtecha** [librenms/librenms#2578]
So coming from observium I realize we don't have the same IPMI options available such as setting the UserLevel and Interface which is blocking me from associating the IPMI tool to a server.
![screenshot from 2015-12-08 11-04-21](https://cloud.githubusercontent.com/assets/3084627/11665324/a2041768-9d9b-11e5-9ce6-3b96fc412e90.png)

**Comment by laf** [comment]
Can you provide access to an ipmi setup for us to work on this?

**Comment by djtecha** [comment]
This should be the standard for all dell servers using an idrac card. I unfortunately do not have gear I could donate for testing.

**Comment by djtecha** [comment]
Can I do anything to help this move along? I need to be able to pass the user level to something other then administrator.

ipmitool -I lanplus -U root -H <HOST> -L USER chassis status

**Comment by justinthegeek** [comment]
I've got access to an idrac that I would be willing to help test/fix the ipmi scanning. I would love to see my power usage in librenms :)

**Comment by rasssta** [comment]
+1

**Comment by rasssta** [comment]
quick fix: change the default value 'imb' to 'lanplus' in $DIR/includes/polling/ipmi.inc.php

**Comment by djtecha** [comment]
Looks like the config option was added for lanplus doing somthing like:

$config['ipmi']['type'] = array();
$config['ipmi']['type'] = "lanplus";

in the config.php. But debuging using "./poller.php -h websrv-1 -d -r -f -m ipmi" I get a blank value:

Fetching IPMI sensor data...SNMP[/usr/bin/ipmitool -I  -c  -H websrv-1 -U 'librenms' -P 'passwd' -L USER sdr 2>/dev/null]

You'll see that there should be lanplus after the -I according to includes/polling/ipmi.inc.php:

        if ($config['own_hostname'] != $device['hostname'] || $ipmi['host'] != 'localhost') {
            $remote = " -H " . $ipmi['host'] . " -U '" . $ipmi['user'] . "' -P '" . $ipmi['password'] . "' -L USER";
        }

**Comment by laf** [comment]
type is taken from the device override in the webui - but it has no option :(

We also document the above config options but don't use them!!

**Comment by laf** [comment]
Re looked at this, type is expecting an array, change your config to:

`$config['ipmi']['type'] = array('lanplus');`

**Comment by djtecha** [comment]
This still seems to fail. 

SQL[SELECT * FROM sensors WHERE device_id = '96' AND poller_type='ipmi'] 
Array
(
)
Fetching IPMI sensor data...SNMP[/usr/bin/ipmitool -I  -c  -H websrv-1 -U 'librenms' -P 'pass' -L USER sdr 2>/dev/null]

 done.

>> Runtime for poller module 'ipmi': 0.0158 seconds

**Comment by djtecha** [comment]
actually... when I use the sensors tab it includes it:

/usr/bin/ipmitool -I lanplus -H websrv-1 -U 'librenms' -P 'pass' -L USER sensor 2>/dev/null|sort]

So, maybe this is more of a bug in running this:

poller.php -h websrv-1 -d -r -f -m ipmi

**Comment by laf** [comment]
A discovery has to run after the config changed - has that happened?

**Comment by djtecha** [comment]
yes, I was working on another bug where I saw this now working for sensors. But after the discovery it sadly is still blank.

**Comment by laf** [comment]
`select * from devices_attribs where device_id=X;`

What's the output of that?

**Comment by djtecha** [comment]
+-----------+-----------+---------------+---------------------------+---------------------+
| attrib_id | device_id | attrib_type   | attrib_value              | updated             |
+-----------+-----------+---------------+---------------------------+---------------------+
|       217 |        96 | ipmi_hostname | websrv-1.idrac.com | 2016-12-08 13:13:01 |
|       218 |        96 | ipmi_password | pass          | 2016-12-08 13:13:01 |
|       219 |        96 | ipmi_username | librenms                  | 2016-12-08 13:13:02 |
+-----------+-----------+---------------+---------------------------+---------------------+

**Comment by djtecha** [comment]
it shows up when I do a discovery, just not when I run the poller.

**Comment by djtecha** [comment]
Ok, well my bad. This totally works. Long story short the machine I was testing against became a VM during my testing. So the code is solid, but it looks like the docs might need an update: http://docs.librenms.org/Support/Configuration/#ipmi

**Comment by laf** [comment]
Docs are correct.
