### ISSUE TITLE
Add option to disable 'recovery' message for alert

### ISSUE THREAD

**Issue by ekoyle** [librenms/librenms#2579]
It would be very useful to be able to disable the recovery message for a given alert, for example the recovery on "Device rebooted".

**Comment by f0o** [comment]
@laf how do we go on the UI?
The backend is finished and works

**Comment by laf** [comment]
Not looked into it anymore than just "it won't fit"

**Comment by towster** [comment]
upvote?
=)

**Comment by laf** [comment]
Use the 👍 in the top right of the first post.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-add-option-to-disable-recovery-message-for-alert/729

**Comment by laf** [comment]
This is now available for testing: https://github.com/librenms/librenms/pull/8430
