### ISSUE TITLE
LLDP issues with switch

### ISSUE THREAD

**Issue by djtecha** [librenms/librenms#2581]
So I'm trying to get lldp working to build a network map for a cisco switch and it appears that the SQL is not querying correctly.

(
    [17] => Array
        (
            [lldpRemChassisIdSubtype] => macAddress
            [lldpRemChassisId] => 20 47 47 7D D6 8C 
            [lldpRemPortIdSubtype] => macAddress
            [lldpRemPortId] => 20 47 47 7D D6 8C 
            [lldpRemPortDesc] => Interface   2 as eth0
            [lldpRemSysName] => query-5
            [lldpRemSysDesc] => Linux query-5 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64
            [lldpRemSysCapSupported] => 00 00 
            [lldpRemSysCapEnabled] => 00 00 
        )

)
SQL[SELECT `device_id` FROM `devices` WHERE `sysName` = 'query-5' OR `hostname` = 'query-5'] 
SQL[SELECT `port_id` FROM `ports` WHERE (`ifDescr` = 'Interface   2 as eth0' OR `ifName` = 'Interface   2 as eth0' OR `ifDescr` = '20 47 47 7D D6 8C ' OR `ifName` = '20 47 47 7D D6 8C ') AND `device_id` = '21'] 
SQL[SELECT * FROM `ports` WHERE `device_id` = '118' AND `ifIndex` = '44'] Array

Now if I run that SQL I return zero results which is why I believe it's not updating. I can change ifName to ifPhysAddress and it will return the correct port_id, but I also have to remove the spaces from the mac address like so:

MariaDB [librenms]> SELECT `port_id` FROM `ports` WHERE (`ifDescr` = 'Interface   2 as eth0' OR `ifName` = 'Interface   2 as eth0' OR `ifDescr` = '20 47 47 7D D6 8C ' OR `ifPhysAddress` = '2047477DD68C') AND `device_id` = '21';
+---------+
| port_id |
+---------+
|     238 |
+---------+

**Comment by laf** [comment]
Can you provide us access to the device running lldp so we can debug this?

**Comment by djtecha** [comment]
Sadly I cannot as this is all enterprise gear. But I can tell you this is a standard CentOS 7 server running lldp connected to a Cisco catalyst37xxStack running Cisco IOS 12.2(58)SE2 (IPBASEK9). I can also see the lldp neighbor showing up on the switch and have this working in observium if that helps narrow the issue to the code.

**Comment by laf** [comment]
Without kit we can't go changing the code as that may just fix this issue but break it for anyone else :/

**Comment by djtecha** [comment]
Am I wrong in believing that "SELECT `port_id` FROM `ports` WHERE (`ifDescr` = ? OR `ifName` = ? OR `ifDescr` = ? OR `ifName` = ?) AND `device_id` = ?', array($if, $if, $id, $id, $remote_device_id)" Wouldn't actually fetch the MAC address though? Or is it the fact that the lldpRemPortDesc is posting the wrong string? Like, does this feature link by MAC or by hostname & port name?

**Comment by laf** [comment]
That would return the port_id based on a port existing in the DB that has the descr returned by the lldp lookup. So it links (or in this particular query) based on what it expects to see in ifName or ifDescr

**Comment by djtecha** [comment]
Right so when the port description uses "Interface   2 as eth0" I would assume this fails to link as it should just be eth0:

hassis id: 782b.cb1c.70fe
Port id: 782b.cb1c.70fe
Port Description: Interface   2 as eth0
System Name: query-5

System Description: 
Linux query-5 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64

Time remaining: 119 seconds
System Capabilities - not advertised
Enabled Capabilities - not advertised
Management Addresses:
    IPV6: A00::26F0:89E1:B67F:0
Auto Negotiation - not supported
Physical media capabilities - not advertised
Media Attachment Unit type - not advertised
Vlan ID: - not advertised

**Comment by djtecha** [comment]
I think I need to get my env to fix that Description or the code should be using a regex in the sql.

**Comment by laf** [comment]
I've tested this on a Cisco switch to a Proxmox hypervisor and it works as expected. The lldpRemPortDesc returned is eth0 so the port can be matched fine.

I'm wondering if this is more that your lldp response returns Interface 2 as eth0 and that needs resolving. We probably could add another item to the query and include the lldpRemPortId / mac check.

**Comment by Rosiak** [comment]
Just for info:
LLDP working fine here, between Edgerouter and Cisco SMB sw.

**Comment by djtecha** [comment]
Yea I dug into this more. Looking at the observium code it looks that if ALL else fails there is a MAC check performed. I also was looking into why lldp is even adding that extra string but I couldn't find anything useful as to how to modify the output. It's coming from CentOS7 so there's something weird going on as I agree that it should just be the interface name IE. eth0

**Comment by laf** [comment]
We can add an additional check in for macs. As I've got it running here now I can see what's happening.

Leave it with us.

**Comment by djtecha** [comment]
Awesome, thanks for the quick response. Good community here!
