### ISSUE TITLE
LibreNMS custom Macros

### ISSUE THREAD

**Issue by jcounsell1222** [librenms/librenms#2583]
i am trying to create a Macro that tells me if a device is down. i want it to look and check for the reason to be ICMP and and for it to be in the type firewall or network. i created the following macro and added it to the web front end in the config.php file:

$config['alert']['macros']['rule']['device_down'] = '%devices.status = "0" and %devices.status_reason = "icmp" and (%devices.type = "network" or %devices.type = "firewall")';

in the alert GUI i have %macros.device_down ="1"

we have devices that should be caught by this( i checked the DB) and a few devices match this but no alerts are hitting.

**Comment by laf** [comment]
Not tested but:

```php
$config['alert']['macros']['rule']['device_down'] = '(%devices.status = "0" && %devices.status_reason = "icmp" && (%devices.type = "network" || %devices.type = "firewall"))';
```

**Comment by jcounsell1222** [comment]
so it looks like maybe macros.device_down already exists. is there a config file other than the config.php that defines this? another location for macros? i created the following fining that the other already existed and this is not doing what i had hoped. 

$config['alert']['macros']['rule']['network_device_down'] = '(%devices.status = "0" && %devices.status_reason = "icmp" && (%devices.type = "network" || %devices.type = "firewall"))';

**Comment by laf** [comment]
The initial macros are stored in the DB but putting the entry in config.php should overwrite the initial value.

I've just tested your rule but changed icmp to snmp and it works perfectly fine for me. The single network device I have in my test lab which is down (due to snmp) alerts. Can you screenshot your actual alert rule you've created.

**Comment by jcounsell1222** [comment]
![screen shot 2015-12-08 at 4 41 30 pm](https://cloud.githubusercontent.com/assets/15875372/11669421/97c5ae68-9dca-11e5-9913-efb55efaeed6.png)

**Comment by laf** [comment]
Looks good, post the end of the output which shows the queries for rules of a device you expect this to match:

`./poller.php -h HOSTNAME -d -r -m system,os`

**Comment by jcounsell1222** [comment]
select 
d.hostname
,d.type
,d.status
,d.status_reason
from devices d
where d.status = '0' and d.status_reason ='icmp' and (d.type = 'network' or d.type = 'firewall')


![screen shot 2015-12-08 at 4 44 43 pm](https://cloud.githubusercontent.com/assets/15875372/11669501/05a9ea5c-9dcb-11e5-8ef2-c19192ca4d19.png)

**Comment by laf** [comment]
That's not the query that's actually run by poller though. What commit version are you on?

**Comment by jcounsell1222** [comment]
sorry about that, i am not sure what commit version. i know our pollers are set to search for the newest code and update each night if new code is out.

jac@prdwndsrenms001:/opt/librenms$ ./poller.php -h HOSTNAME -d -r -m system,os
LibreNMS 2015.master Poller
commit 2e10a5d4f61d58b36b49cc1fc6376071304215e0

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'HOSTNAME' ORDER BY `device_id` ASC] ./poller.php HOSTNAME 2015-12-08 21:45:21 - 0 devices polled in 0.293 secs

MySQL: Cell[0/0s] Row[0/0s] Rows[1/0s] Column[0/0s] Update[0/0s] Insert[0/0s] Delete[0/0s]
jac@prdwndsrenms001:/opt/librenms$

**Comment by laf** [comment]
You need to replace HOSTNAME with the devices hostname :)

commit is recent so that's fine.

**Comment by jcounsell1222** [comment]
librenms@prdwndsrenms005:~$ ./poller.php -h orr-pa500-b -d -r -m system,os
LibreNMS 2015.master Poller
commit a2d97f4283c7a920904fa953cf677db92df189e8

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'orr-pa500-b' ORDER BY `device_id` ASC]
SQL[SELECT * FROM `devices` WHERE `device_id` = '1147']
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '1147'] orr-pa500-b 1147 panos

SQL[INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('3','0','100','','','','1147',NOW())] Unpingable
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "CORE"  ) LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "GRE") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "netscaler") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "MPLS") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.hostname REGEXP "wnd" ) LIMIT 1]
SQL[SELECT DISTINCT(alert_schedule.schedule_id) FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '1147' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "CORE"  ) LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "GRE") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "netscaler") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "MPLS") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.hostname REGEXP "wnd" ) LIMIT 1]
SQL[SELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '1147' ) || alert_map.target = '1147'  )]  #3:
SQL[SELECT state FROM alerts WHERE rule_id = '3' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM devices WHERE (devices.device_id = '1147') && (devices.hostname REGEXP "rack"  &&  devices.status = "0"  &&  devices.status_reason = "icmp"         )]  NOCHG  #6:
SQL[SELECT state FROM alerts WHERE rule_id = '6' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM devices WHERE (devices.device_id = '1147') && (devices.hostname REGEXP "core"        &&  devices.hostname NOT REGEXP "dbctcore"    &&  devices.status = "0"    &&  devices.status_reason = "icmp"         )]  NOCHG  #8:
SQL[SELECT state FROM alerts WHERE rule_id = '8' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM processors,devices WHERE (( devices.device_id = processors.device_id ) && processors.device_id = '1147') && (processors.processor_usage > "90"    &&  devices.hardware REGEXP "cisco"     )]  NOCHG  #13:
SQL[SELECT state FROM alerts WHERE rule_id = '13' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM devices WHERE (devices.device_id = '1147') && (devices.hostname REGEXP "idf"  &&  devices.status = "0"  &&  devices.status_reason = "icmp"   )]  NOCHG  #16:
SQL[SELECT state FROM alerts WHERE rule_id = '16' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM ports WHERE (ports.device_id = '1147') && ( (  (  ( ports.ifInOctets_rate * 8 )  / ports.ifSpeed )  * 100 )  >= "85"    &&  ports.port_descr_type REGEXP mpls  &&  ports.ifAdminStatus = "up"       )]  NOCHG  #20:
SQL[SELECT state FROM alerts WHERE rule_id = '20' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM ports WHERE (ports.device_id = '1147') && ( (  (  ( ports.ifInOctets_rate * 8 )  / ports.ifSpeed )  * 100 )  >= "85"  &&  ports.ifAdminStatus = "up"    &&  ports.port_descr_type REGEXP "internet"   )]  NOCHG  #26:
SQL[SELECT state FROM alerts WHERE rule_id = '26' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[]  NOCHG

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','orr-pa500-b','1449666486.0435','1.061','1','prdwndsrenms005\n')] ./poller.php orr-pa500-b 2015-12-09 08:08:07 - 1 devices polled in 1.061 secs

MySQL: Cell[11/0.03s] Row[19/0.02s] Rows[7/0.01s] Column[0/0s] Update[0/0s] Insert[2/0s] Delete[0/0s]

**Comment by laf** [comment]
I don't see that rule being run there :/

Are you mapping the alert rule to a device or device group?

**Comment by jcounsell1222** [comment]
no i dont have any rule mappings setup.

**Comment by laf** [comment]
I'm out of ideas @f0o?

**Comment by f0o** [comment]
That macro works for me :S

**Comment by f0o** [comment]
@jcounsell1222  Run this in your SQL: (Substitute the `?` with an device's ID that you know should be matching)
`SELECT * FROM devices WHERE (devices.device_id = ?) && ( (  ( devices.status = "0"  &&  devices.status_reason = "icmp"  &&   ( devices.type = "network"  ||  devices.type = "firewall" )  )  )  = 1)`

**Comment by jcounsell1222** [comment]
using the same alert as well?

**Comment by f0o** [comment]
I used:
```php
$config['alert']['macros']['rule']['network_device_down'] = '(%devices.status = "0" && %devices.status_reason = "icmp" && (%devices.type = "network" || %devices.type = "firewall"))';
```

**Comment by jcounsell1222** [comment]
if i run that i get the device back that i would expect.

![screen shot 2015-12-09 at 1 01 08 pm](https://cloud.githubusercontent.com/assets/15875372/11693822/f5ef0624-9e74-11e5-97c9-08e00d3fda77.png)

**Comment by f0o** [comment]
Then something must be funky with your mappings. (did you add any or did you leave it blank or..?)

Try removing the rule and re-adding it.

**Comment by jcounsell1222** [comment]
so currently the rule looks like this. ill try killing it an adding it back.

![screen shot 2015-12-09 at 1 05 54 pm](https://cloud.githubusercontent.com/assets/15875372/11693978/a8e089f6-9e75-11e5-8ac8-6bea0a811482.png)
![screen shot 2015-12-09 at 1 06 06 pm](https://cloud.githubusercontent.com/assets/15875372/11693981/aad619d8-9e75-11e5-9066-098585629ec1.png)

**Comment by jcounsell1222** [comment]
in the database it looks like all my rules have a device_id of -1. is that typical?

![screen shot 2015-12-09 at 1 10 17 pm](https://cloud.githubusercontent.com/assets/15875372/11694104/3b3b455c-9e76-11e5-9fac-a9f53ad379a8.png)

**Comment by f0o** [comment]
Yes, -1 means all devices

**Comment by jcounsell1222** [comment]
ok cool. i recreated the rule. here is what it looks like currently.

![screen shot 2015-12-09 at 1 16 06 pm](https://cloud.githubusercontent.com/assets/15875372/11694273/1adb77fe-9e77-11e5-9ffe-29d231c42a09.png)

**Comment by f0o** [comment]
Looks correct so far :)

**Comment by jcounsell1222** [comment]
still not alerting. hmmmm wonder what i am missing here. this will not only fire on new hosts that go down but on hosts that are currently in the down state correct?

**Comment by f0o** [comment]
Correct

**Comment by f0o** [comment]
Can you do above poller command again for a host that should be matching the rule and paste it again? (sorry for the redundancy)

**Comment by jcounsell1222** [comment]
librenms@prdwndsrenms005:~$ ./poller.php -h orr-pa500-b -d -r -m system,os
LibreNMS 2015.master Poller
commit a2d97f4283c7a920904fa953cf677db92df189e8

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'orr-pa500-b' ORDER BY `device_id` ASC]
SQL[SELECT * FROM `devices` WHERE `device_id` = '1147']
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '1147'] orr-pa500-b 1147 panos

SQL[INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('3','0','100','','','','1147',NOW())] Unpingable
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "CORE"  ) LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "GRE") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "netscaler") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "MPLS") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.hostname REGEXP "wnd" ) LIMIT 1]
SQL[SELECT DISTINCT(alert_schedule.schedule_id) FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '1147' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "CORE"  ) LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "GRE") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "netscaler") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "MPLS") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.hostname REGEXP "wnd" ) LIMIT 1]
SQL[SELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '1147' ) || alert_map.target = '1147'  )]  #3:
SQL[SELECT state FROM alerts WHERE rule_id = '3' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM devices WHERE (devices.device_id = '1147') && (devices.hostname REGEXP "rack"  &&  devices.status = "0"  &&  devices.status_reason = "icmp"         )]  NOCHG  #6:
SQL[SELECT state FROM alerts WHERE rule_id = '6' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM devices WHERE (devices.device_id = '1147') && (devices.hostname REGEXP "core"        &&  devices.hostname NOT REGEXP "dbctcore"    &&  devices.status = "0"    &&  devices.status_reason = "icmp"         )]  NOCHG  #8:
SQL[SELECT state FROM alerts WHERE rule_id = '8' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM processors,devices WHERE (( devices.device_id = processors.device_id ) && processors.device_id = '1147') && (processors.processor_usage > "90"    &&  devices.hardware REGEXP "cisco"     )]  NOCHG  #13:
SQL[SELECT state FROM alerts WHERE rule_id = '13' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM devices WHERE (devices.device_id = '1147') && (devices.hostname REGEXP "idf"  &&  devices.status = "0"  &&  devices.status_reason = "icmp"   )]  NOCHG  #16:
SQL[SELECT state FROM alerts WHERE rule_id = '16' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM ports WHERE (ports.device_id = '1147') && ( (  (  ( ports.ifInOctets_rate * 8 )  / ports.ifSpeed )  * 100 )  >= "85"    &&  ports.port_descr_type REGEXP mpls  &&  ports.ifAdminStatus = "up"       )]  NOCHG  #20:
SQL[SELECT state FROM alerts WHERE rule_id = '20' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM ports WHERE (ports.device_id = '1147') && ( (  (  ( ports.ifInOctets_rate * 8 )  / ports.ifSpeed )  * 100 )  >= "85"  &&  ports.ifAdminStatus = "up"    &&  ports.port_descr_type REGEXP "internet"   )]  NOCHG  #27:
SQL[SELECT state FROM alerts WHERE rule_id = '27' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[]
SQL[INSERT INTO `alert_log` (`state`,`device_id`,`rule_id`)  VALUES ('0','1147','27')]
SQL[UPDATE `alerts` set `state` ='0',`open` ='1' WHERE device_id = '1147' && rule_id = '27']  OK

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','orr-pa500-b','1449685500.2429','1.014','1','prdwndsrenms005\n')] ./poller.php orr-pa500-b 2015-12-09 13:25:01 - 1 devices polled in 1.014 secs

MySQL: Cell[11/0.01s] Row[19/0.01s] Rows[7/0.01s] Column[0/0s] Update[1/0.02s] Insert[3/0.02s] Delete[0/0s]

**Comment by jcounsell1222** [comment]
also no apology required you guys are helping me :)

**Comment by f0o** [comment]
Cant find it in the output, what the hoth ...

**Comment by f0o** [comment]
Wait I spot something disturbing
`SQL[]` << That is a bad thing!

**Comment by jcounsell1222** [comment]
its odd but after i ran that it seemed to fire off an alert on the specific device that i ran the command on.

**Comment by laf** [comment]
Is the SQL[] that f0o spotted as it shows in your console (i.e nothing between the brackets?)

**Comment by f0o** [comment]
it seemed? Do you see it as a fault?
Does it magically work all of a sudden?

If not, shout so I can spin up a VM to fit your setup and recreate a condition upon it

**Comment by jcounsell1222** [comment]
yes it does look like a line has SQL[] with nothing in the brackets. that was run from one of the many pollers that we have. if i run it from the front end webserver i get the following. 

ibrenms@prdwndsrenms001:~$ ./poller.php -h orr-pa500-b -d -r -m system,os
LibreNMS 2015.master Poller
commit a2d97f4283c7a920904fa953cf677db92df189e8

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'orr-pa500-b' ORDER BY `device_id` ASC]
SQL[SELECT * FROM `devices` WHERE `device_id` = '1147']
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '1147'] orr-pa500-b 1147 panos

SQL[INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('3','0','100','','','','1147',NOW())] Unpingable
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "CORE"  ) LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "GRE") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "netscaler") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "MPLS") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.hostname REGEXP "wnd" ) LIMIT 1]
SQL[SELECT DISTINCT(alert_schedule.schedule_id) FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '1147' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "CORE"  ) LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "GRE") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "netscaler") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.sysName REGEXP "MPLS") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='1147' && (devices.hostname REGEXP "wnd" ) LIMIT 1]
SQL[SELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '1147' ) || alert_map.target = '1147'  )]  #3:
SQL[SELECT state FROM alerts WHERE rule_id = '3' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM devices WHERE (devices.device_id = '1147') && (devices.hostname REGEXP "rack"  &&  devices.status = "0"  &&  devices.status_reason = "icmp"         )]  NOCHG  #6:
SQL[SELECT state FROM alerts WHERE rule_id = '6' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM devices WHERE (devices.device_id = '1147') && (devices.hostname REGEXP "core"        &&  devices.hostname NOT REGEXP "dbctcore"    &&  devices.status = "0"    &&  devices.status_reason = "icmp"         )]  NOCHG  #8:
SQL[SELECT state FROM alerts WHERE rule_id = '8' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM processors,devices WHERE (( devices.device_id = processors.device_id ) && processors.device_id = '1147') && (processors.processor_usage > "90"    &&  devices.hardware REGEXP "cisco"     )]  NOCHG  #13:
SQL[SELECT state FROM alerts WHERE rule_id = '13' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM devices WHERE (devices.device_id = '1147') && (devices.hostname REGEXP "idf"  &&  devices.status = "0"  &&  devices.status_reason = "icmp"   )]  NOCHG  #16:
SQL[SELECT state FROM alerts WHERE rule_id = '16' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM ports WHERE (ports.device_id = '1147') && ( (  (  ( ports.ifInOctets_rate * 8 )  / ports.ifSpeed )  * 100 )  >= "85"    &&  ports.port_descr_type REGEXP mpls  &&  ports.ifAdminStatus = "up"       )]  NOCHG  #20:
SQL[SELECT state FROM alerts WHERE rule_id = '20' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM ports WHERE (ports.device_id = '1147') && ( (  (  ( ports.ifInOctets_rate * 8 )  / ports.ifSpeed )  * 100 )  >= "85"  &&  ports.ifAdminStatus = "up"    &&  ports.port_descr_type REGEXP "internet"   )]  NOCHG  #27:
SQL[SELECT state FROM alerts WHERE rule_id = '27' && device_id = '1147' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM devices WHERE (devices.device_id = '1147') && ( (  ( devices.status = "0"  &&  devices.status_reason = "icmp"  &&   ( devices.type = "network"  ||  devices.type = "firewall" )  )  )  = "1" )]
SQL[SELECT * FROM `users`]
SQL[SELECT attrib_value FROM devices_attribs WHERE attrib_type = 'override_sysContact_bool' AND device_id = '1147']
SQL[SELECT sysContact FROM devices WHERE device_id = '1147']
SQL[SELECT user_id FROM devices_perms WHERE access_level >= 0 AND device_id = '1147']
SQL[SELECT `level` FROM `users` WHERE `username` = 'librenms']
SQL[SELECT `level` FROM `users` WHERE `username` = 'kem']
SQL[SELECT `level` FROM `users` WHERE `username` = 'dashboard']
SQL[SELECT `level` FROM `users` WHERE `username` = 'jkarimi']
SQL[SELECT `level` FROM `users` WHERE `username` = 'uz']
SQL[SELECT `level` FROM `users` WHERE `username` = 'wnditops']
SQL[SELECT `level` FROM `users` WHERE `username` = 'netops']
SQL[SELECT `level` FROM `users` WHERE `username` = 'chrwilliams']
SQL[SELECT `level` FROM `users` WHERE `username` = 'jcounsell']
SQL[SELECT `level` FROM `users` WHERE `username` = 'dtuttle']
SQL[SELECT `level` FROM `users` WHERE `username` = 'fnasraoui']
SQL[SELECT `level` FROM `users` WHERE `username` = 'paivazian']
SQL[SELECT `level` FROM `users` WHERE `username` = 'bbradford']
SQL[SELECT `level` FROM `users` WHERE `username` = 'dmorin']
SQL[SELECT `level` FROM `users` WHERE `username` = 'apuig']
SQL[SELECT `level` FROM `users` WHERE `username` = 'dvaliant']
SQL[SELECT `level` FROM `users` WHERE `username` = 'sojalehto']
SQL[SELECT `level` FROM `users` WHERE `username` = 'sburgess']
SQL[SELECT `level` FROM `users` WHERE `username` = 'dwakabayashi']
SQL[SELECT `level` FROM `users` WHERE `username` = 'tviapiano']
SQL[SELECT `level` FROM `users` WHERE `username` = 'kfrederick']
[�I�V��;\'�6��\0����1o7:\0>�ޢ{�˙��N��q+��(��f��E������:�}�M��JT�	���K.G�~mK��R���Hnt.����8�(��H�$T�u�g�{�bqSk/�j+��,�5�J�T0��{uye��n�f߈@�Zm��i����M��pҰ��D�7/�DL[�#��`�=K�e�\n�;�6��7��%lq�K���I�a-�b\Z���Fo�Þ��>;�
                     \'��*t`l�~�Z�(���b-�X�ei:�D?��AC�|d��Y%IoI�m�ݿp
                                                                    R�Z�--�\\<�W�Ӱo�J�0ԡT�#e�V�\Z���Ϡ\ns8s���jg�9�x]ٵp��B�*h�Rh�G��\"+a�p�v\"8)��5��`�����\r��x��=ħ?\Z��MHӡ��-�2l��9�P�����yA�سtb��G���j�X��\"��4\Z�q�Ļ)���i4~{jw�Da�1�}����/m�2�j��a��:���N�B�]
                                                             ����R�|�-���4I�A���8)�aa�j��I:�i/�d�\r&Y��\\��Dei�%���5�JP~�U���7آ��O��jZi$�`���4�?��E��q&qJ���Y㏋���p>g�<(jL2&ش��	��z�X�ju�ڢ��R�N�b�{r{\Z)�6�0����\0%*	')]
SQL[UPDATE `alerts` set `state` ='1',`open` ='1' WHERE device_id = '1147' && rule_id = '27']  ALERT

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','orr-pa500-b','1449685424.1913','1.295','1','prdwndsrenms001\n')] ./poller.php orr-pa500-b 2015-12-09 18:23:45 - 1 devices polled in 1.295 secs

MySQL: Cell[12/0.01s] Row[42/0.02s] Rows[7/0.01s] Column[0/0s] Update[1/0.05s] Insert[3/0.01s] Delete[0/0s]
librenms@prdwndsrenms001:~$ ./poller.php -h tko-voip-2911 -d -r -m system,os
LibreNMS 2015.master Poller
commit a2d97f4283c7a920904fa953cf677db92df189e8

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'tko-voip-2911' ORDER BY `device_id` ASC] ./poller.php tko-voip-2911 2015-12-09 18:28:31 - 0 devices polled in 0.007 secs

**Comment by f0o** [comment]
```
...
SQL[SELECT * FROM devices WHERE (devices.device_id = '1147') && ( (  ( devices.status = "0"  &&  devices.status_reason = "icmp"  &&   ( devices.type = "network"  ||  devices.type = "firewall" )  )  )  = "1" )]
...
```

Now that's more like it!

**Comment by f0o** [comment]
Do you have some caching or multiple SQLs or something that could be holding stale information so that the rule wasnt made aware to the pollerbox?

**Comment by jcounsell1222** [comment]
i am not sure. i was not involved with the setup on these boxes. just in the process of getting the alerts configured. i can check with the individual that setup the boxes and get back to you with that info.

**Comment by f0o** [comment]
Important thing is that the macro works :)

**Comment by laf** [comment]
memcache on each local box? That could cause that.

**Comment by jcounsell1222** [comment]
we might have that on each box. would you thin it should only be on the front end?

**Comment by laf** [comment]
@jcounsell1222 it's more beneficial on the web front end to speed things up. It would also help overall for a single poller box but distributed you either need to switch it off or run a single instance that all pollers talk too.

**Comment by jcounsell1222** [comment]
good to know, looks like we have some internal cleanup to do here. ill report back on that after we have finished. thanks for you help on this guys its really appreciated.

**Comment by laf** [comment]
Np. Feel free to re-open this if you still have issues.
