### ISSUE TITLE
Stop debug output for polling outputting binary

### ISSUE THREAD

**Issue by laf** [librenms/librenms#2584]
Crashes numerous clients now :/

**Comment by f0o** [comment]
Binary is fun!

But no, you're right.. what's your proposal though?

**Comment by laf** [comment]
I don't have any, posted as last night I had my shell crash four times in a row :/

**Comment by f0o** [comment]
I use `less` :X

**Comment by laf** [comment]
We could replace the debug output when we see INSERT INTO `alert_log` with a message saying an alert_log was added. No real info is gleaned from that insert anyway.
