### ISSUE TITLE
FEATURE REQUEST - alert acknowledgment emails

### ISSUE THREAD

**Issue by Alastair-VOIPUNLIMITED** [librenms/librenms#2596]
Hi guys,

Me again unfortunately, 

We have a very large network all plugged into Libre, with multiple sys admins and users.

When an alert is acknowledged we all get the email however we then chase eachother to ask what was wrong and what the fix was.

Was wondering if it would be sensible or if others might find it helpful too if...

When an alert acknowledgment is clicked (mute button) a window pops up in which the user can write a small explanation and detail to the syscontact/overridden syscontact of that device, which is then included in the alert acknowledgment email that gets sent out?

Thanks all :) 

Alastair

**Comment by f0o** [comment]
:+1:

On 10 December 2015 12:47:40 CET, Alastair-VOIPUNLIMITED <notifications@github.com> wrote:
>Hi guys,
>
>Me again unfortunately, 
>
>We have a very large network all plugged into Libre, with multiple sys
>admins and users.
>
>When an alert is acknowledged we all get the email however we then
>chase eachother to ask what was wrong and what the fix was.
>
>Was wondering if it would be sensible or if others might find it
>helpful too if...
>
>When an alert acknowledgment is clicked (mute button) a window pops up
>in which the user can write a small explanation and detail to the
>syscontact/overridden syscontact of that device, which is then included
>in the alert acknowledgment email that gets sent out?
>
>Thanks all :) 
>
>Alastair
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2596

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Alastair-VOIPUNLIMITED** [comment]
![5555](https://cloud.githubusercontent.com/assets/11542248/11714906/6982a648-9f35-11e5-9053-4188869ea313.PNG)

would be great if next to acknowledge column we had a column for "acknowledged by" where it puts the user who did it :)

**Comment by SaaldjorMike** [comment]
:+1:

**Comment by x3m** [comment]
Already asked for the same: https://github.com/librenms/librenms/issues/2472

would be really appreciated if such feature appears anytime soon.

**Comment by laf** [comment]
Closing as is a duplicate. Putting a note in the other issue to check this for showing user who ack'd

**Comment by laf** [comment]
Pull request now in place for this feature: https://github.com/librenms/librenms/pull/8433
