### ISSUE TITLE
ESX 6.0u1 port error stats incorrect

### ISSUE THREAD

**Issue by petracvv** [librenms/librenms#2599]
We are evaluating Librenms for our environment and noticed that on our newer ESX6.0 hosts librenms was displaying millions of port errors on every physical port. Example:
![vmport](https://cloud.githubusercontent.com/assets/3154784/11726251/640179a2-9f43-11e5-83c0-b3b830a80739.png)

If I do an snmp-walk on that host, the error count is very low and is not changing or increasing. See relevant data:
```
IF-MIB::ifDescr.1 = STRING: Device vmnic0 at 32:00.0 ixgbe
IF-MIB::ifDescr.2 = STRING: Device vmnic1 at 32:00.1 ixgbe
IF-MIB::ifDescr.3 = STRING: Device vmnic2 at 136:00.0 ixgbe
IF-MIB::ifDescr.4 = STRING: Device vmnic3 at 136:00.1 ixgbe

IF-MIB::ifInErrors.1 = Counter32: 523
IF-MIB::ifInErrors.2 = Counter32: 527
IF-MIB::ifInErrors.3 = Counter32: 1179
IF-MIB::ifInErrors.4 = Counter32: 2223
```

We have some older hosts running ESX 5.5 in our environment that I added to librenms earlier today that do not have any packet errors listed so far.

Maybe Librenms is reading the wrong field for ESX6.0?

**Comment by laf** [comment]
Those values aren't what you expect :) It's not millions it's milli and is showing you the values you see returned via snmp.

It doesn't look wrong to me. If you don't see the same on 5.5 then check snmp, I expect you just don't have any errors on the port showing.

**Comment by masonke** [comment]
Looking at the vmnic0 graph, are there currently  .00014444 Packet Errors/Sec In, with an Avg of .00164/sec and a max of .01319/sec ?
~KEM

**Comment by laf** [comment]
@petracvv Feel free to re-open this if you have any further queries.

**Comment by petracvv** [comment]
@laf Thanks for the clarification. Just to make sure I understand, Librenms is calculating a packet error rate from the snmp error count and the number of packets coming in/out?

**Comment by laf** [comment]
The rate comes from the difference between two polls and the time between them rather than the packets.
