### ISSUE TITLE
have you plan to extension alert template Placeholders?

### ISSUE THREAD

**Issue by kaoru290** [librenms/librenms#2604]
i want to setting template more flexible.
e.g. http://myserver/device/device=<DEVICE_ID>/tab=port/port=<PORT_ID>/
i think PORT_ID is not exist in alert template Placeholders.

**Comment by laf** [comment]
You can use port_id in the foreach faults loop:

{foreach %faults}  #%key: %value.string http://example.com/device/blah=%value.port_id \r\n{/foreach}{/if}

**Comment by kaoru290** [comment]
@laf thanks.
i will attempt it.
