### ISSUE TITLE
Feature Request: Weathermap widgets (or image viewer) in dashboard

### ISSUE THREAD

**Issue by pmcnabb** [librenms/librenms#2606]
It'd be nice to be able to include Weathermaps as widgets on a dashboard. Since they are really just static images, maybe a generic image widget would handle this feature (and any other external images the user may wish to include on a dashboard).

**Comment by f0o** [comment]
:+1: imageviewer comes in handy for xkcd as well!

**Comment by Rosiak** [comment]
:+1: to a "generic" solution.
