### ISSUE TITLE
Setup IPSLA

### ISSUE THREAD

**Issue by jcounsell1222** [librenms/librenms#2607]
hey Guys,

i have devices running IPSLAs for jitter on voice gateways. i have confirmed on the pollers that the cisco-sla module is on (see below) but i am still not seeing anything in the sla table on the Libre database. anyone have any idea on this? thanks in advance for all your help.

$config['poller_modules']['cisco-sla'] = 1;

**Comment by Cheeze-It** [comment]
This probably wouldn't be a bad idea to put in for both Cisco IPSLA and for Juniper RPM functionality.

That way the largest vendors that have the kind of monitoring can be developed for.

**Comment by laf** [comment]
@jcounsell1222 please provide the output via dpaste.de of:

```bash
./discovery.php -h HOSTNAME -d -m cisco-sla
./poller.php -h HOSTNAME -r -d -m cisco-sla
```

@Cheeze-It missed this last night! If this works then we just need to get RPM done.

**Comment by Cheeze-It** [comment]
So I haven't really tested this out yet. Mainly because I just haven't gotten a chance but I was kinda thinking in my head.

Would it be cool to have anything that has to do with Cisco IPSLA/Juniper RPM to be under the "health" tab on the main page as well under the device. Maybe name it something like "SLA Monitoring". Maybe orient it similarly to where one graph is one SLA operation. That way multiple SLA operations can be in one page and they can be clickable like the other graphs under "health".

**Comment by jcounsell1222** [comment]
root@prdwndsrenms001:/opt/librenms# ./discovery.php -h ven-core-b -d -m cisco-sla
LibreNMS 2015.master Discovery
commit 6cfe0c4b3fd4bafd5148096b746f9694b9c06001

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1]
SQL[SELECT revision FROM `dbSchema`] DB Schema already up to date.

SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE 'ven-core-b' AND poller_group IN(0) ORDER BY device_id DESC] ./discovery.php ven-core-b 2015-12-14 13:17:54 - 0 devices discovered in 0.076 secs
MySQL: Cell[1/0s] Row[1/0s] Rows[1/0s] Column[0/0s] Update[0/0s] Insert[0/0s] Delete[0/0s]
root@prdwndsrenms001:/opt/librenms#







root@prdwndsrenms001:/opt/librenms# ./poller.php -h ven-core-b -r -d -m cisco-sla
LibreNMS 2015.master Poller
commit 6cfe0c4b3fd4bafd5148096b746f9694b9c06001

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'ven-core-b' ORDER BY `device_id` ASC]
SQL[SELECT * FROM `devices` WHERE `device_id` = '498']
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '498'] ven-core-b 498 ios (cisco)

SQL[INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('3','3','0','101','101','101','498',NOW())] DEBUG: SNMP Auth options =  -v2c -c wPeZ6kiG42oZhg
/usr/bin/snmpget -v2c -c wPeZ6kiG42oZhg -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs -t 1 -r 5 udp:ven-core-b:161 sysObjectID.0
SNMPv2-SMI::enterprises.9.1.283

DEBUG: SNMP Auth options =  -v2c -c wPeZ6kiG42oZhg
/usr/bin/snmpget -v2c -c wPeZ6kiG42oZhg -Otv -M /opt/librenms/mibs -t 1 -r 5 udp:ven-core-b:161 sysUpTime.0
sysUpTime.0: Unknown Object Identifier (Sub-id not found: (top) -> sysUpTime)

DEBUG: SNMP Auth options =  -v2c -c wPeZ6kiG42oZhg
/usr/bin/snmpbulkwalk -v2c -c wPeZ6kiG42oZhg -OUsqt  -m +CISCO-RTTMON-MIB -M /opt/librenms/mibs -t 1 -r 5 udp:ven-core-b:161 ciscoRttMonMIB.ciscoRttMonObjects.rttMonCtrl.rttMonLatestRttOperTable
MIB search path: /opt/librenms/mibs
Cannot find module (MTA-MIB): At line 0 in (none)
Cannot find module (NETWORK-SERVICES-MIB): At line 0 in (none)
rttMonLatestRttOperCompletionTime.40000 0
rttMonLatestRttOperCompletionTime.40001 20
rttMonLatestRttOperCompletionTime.40002 0
rttMonLatestRttOperCompletionTime.40003 121
rttMonLatestRttOperCompletionTime.40004 0
rttMonLatestRttOperCompletionTime.40006 138
rttMonLatestRttOperCompletionTime.40008 101
rttMonLatestRttOperCompletionTime.40010 121
rttMonLatestRttOperCompletionTime.40012 101
rttMonLatestRttOperCompletionTime.40014 121
rttMonLatestRttOperCompletionTime.40015 6
rttMonLatestRttOperSense.40000 notConnected
rttMonLatestRttOperSense.40001 ok
rttMonLatestRttOperSense.40002 notConnected
rttMonLatestRttOperSense.40003 ok
rttMonLatestRttOperSense.40004 notConnected
rttMonLatestRttOperSense.40006 ok
rttMonLatestRttOperSense.40008 ok
rttMonLatestRttOperSense.40010 ok
rttMonLatestRttOperSense.40012 ok
rttMonLatestRttOperSense.40014 ok
rttMonLatestRttOperSense.40015 ok
rttMonLatestRttOperApplSpecificSense.40000 0
rttMonLatestRttOperApplSpecificSense.40001 0
rttMonLatestRttOperApplSpecificSense.40002 0
rttMonLatestRttOperApplSpecificSense.40003 0
rttMonLatestRttOperApplSpecificSense.40004 0
rttMonLatestRttOperApplSpecificSense.40006 0
rttMonLatestRttOperApplSpecificSense.40008 0
rttMonLatestRttOperApplSpecificSense.40010 0
rttMonLatestRttOperApplSpecificSense.40012 0
rttMonLatestRttOperApplSpecificSense.40014 0
rttMonLatestRttOperApplSpecificSense.40015 0
rttMonLatestRttOperSenseDescription.40000
rttMonLatestRttOperSenseDescription.40001
rttMonLatestRttOperSenseDescription.40002
rttMonLatestRttOperSenseDescription.40003
rttMonLatestRttOperSenseDescription.40004
rttMonLatestRttOperSenseDescription.40006
rttMonLatestRttOperSenseDescription.40008
rttMonLatestRttOperSenseDescription.40010
rttMonLatestRttOperSenseDescription.40012
rttMonLatestRttOperSenseDescription.40014
rttMonLatestRttOperSenseDescription.40015
rttMonLatestRttOperTime.40000 324724194
rttMonLatestRttOperTime.40001 324724197
rttMonLatestRttOperTime.40002 324724194
rttMonLatestRttOperTime.40003 324724206
rttMonLatestRttOperTime.40004 324724194
rttMonLatestRttOperTime.40006 324742208
rttMonLatestRttOperTime.40008 324742195
rttMonLatestRttOperTime.40010 324742195
rttMonLatestRttOperTime.40012 324742195
rttMonLatestRttOperTime.40014 324742195
rttMonLatestRttOperTime.40015 324725206
rttMonLatestRttOperAddress.40000 "00 00 00 00 "
rttMonLatestRttOperAddress.40001 "00 00 00 00 "
rttMonLatestRttOperAddress.40002 "00 00 00 00 "
rttMonLatestRttOperAddress.40003 "00 00 00 00 "
rttMonLatestRttOperAddress.40004 "00 00 00 00 "
rttMonLatestRttOperAddress.40006 "00 00 00 00 "
rttMonLatestRttOperAddress.40008 ""
rttMonLatestRttOperAddress.40010 ""
rttMonLatestRttOperAddress.40012 ""
rttMonLatestRttOperAddress.40014 ""
rttMonLatestRttOperAddress.40015 "00 00 00 00 "


SQL[SELECT * FROM `slas` WHERE `device_id` = '498' AND `deleted` = 0 AND `status` = 1] [RRD Disabled]RRD[update ././ven-core-b/poller-perf.rrd N:1.623 --daemon 10.70.201.41:42217] [RRD Disabled]RRD[update ././ven-core-b/ping-perf.rrd N:101 --daemon 10.70.201.41:42217] Polled in 1.623 seconds
Updating ven-core-b
Array
(
    [last_ping] => Array
        (
            [0] => NOW()
        )

    [last_ping_timetaken] => 101
    [last_polled] => Array
        (
            [0] => NOW()
        )

    [last_polled_timetaken] => 1.623
)

SQL[UPDATE `devices` set `last_ping` =NOW(),`last_ping_timetaken` ='101',`last_polled` =NOW(),`last_polled_timetaken` ='1.623' WHERE `device_id` = '498'] UPDATED!

SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='498' && (devices.sysName REGEXP "CORE"  ) LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='498' && (devices.sysName REGEXP "GRE") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='498' && (devices.sysName REGEXP "netscaler") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='498' && (devices.sysName REGEXP "MPLS") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='498' && (devices.sysName REGEXP "voip" ) LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='498' && (devices.hostname REGEXP "wnd" ) LIMIT 1]
SQL[SELECT DISTINCT(alert_schedule.schedule_id) FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '498' || alert_schedule_items.target = 'g5' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='498' && (devices.sysName REGEXP "GRE") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='498' && (devices.sysName REGEXP "netscaler") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='498' && (devices.sysName REGEXP "MPLS") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='498' && (devices.sysName REGEXP "voip" ) LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='498' && (devices.hostname REGEXP "wnd" ) LIMIT 1]  #3:
SQL[SELECT * FROM devices WHERE (devices.device_id = '498') && (devices.hostname REGEXP "rack"  &&  devices.status = "0"  &&  devices.status_reason = "icmp"         )]  NOCHG  #6:
SQL[SELECT * FROM devices WHERE (devices.device_id = '498') && (devices.hostname REGEXP "core"        &&  devices.hostname NOT REGEXP "dbctcore"    &&  devices.status = "0"    &&  devices.status_reason = "icmp"         )]  NOCHG  #8:
SQL[SELECT * FROM processors,devices WHERE (( devices.device_id = processors.device_id ) && processors.device_id = '498') && (processors.processor_usage > "90"    &&  devices.hardware REGEXP "cisco"     )]  NOCHG  #13:
SQL[SELECT * FROM devices WHERE (devices.device_id = '498') && (devices.hostname REGEXP "idf"  &&  devices.status = "0"  &&  devices.status_reason = "icmp"   )]  NOCHG  #16:
SQL[SELECT * FROM ports WHERE (ports.device_id = '498') && ( (  (  ( ports.ifInOctets_rate * 8 )  / ports.ifSpeed )  * 100 )  >= "85"    &&  ports.port_descr_type REGEXP mpls  &&  ports.ifAdminStatus = "up"       )]  NOCHG  #20:
SQL[SELECT * FROM ports WHERE (ports.device_id = '498') && ( (  (  ( ports.ifInOctets_rate * 8 )  / ports.ifSpeed )  * 100 )  >= "85"  &&  ports.ifAdminStatus = "up"    &&  ports.port_descr_type REGEXP "internet"   )]  NOCHG  #27:
SQL[SELECT * FROM devices WHERE (devices.device_id = '498') && ( (  ( devices.status = "0"  &&  devices.status_reason = "icmp"  &&   ( devices.type = "network"  ||  devices.type = "firewall" )  )  )  = "1"   )]  NOCHG

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','ven-core-b','1450099100.7658','1.678','1','prdwndsrenms001\n')] ./poller.php ven-core-b 2015-12-14 13:18:22 - 1 devices polled in 1.678 secs

MySQL: Cell[11/0s] Row[13/0s] Rows[8/0.01s] Column[0/0s] Update[1/0s] Insert[2/0s] Delete[0/0s]
root@prdwndsrenms001:/opt/librenms#

**Comment by tylerapplebaum** [comment]
Hey guys, I'm interested in this functionality as well.

**Comment by Rosiak** [comment]
Cisco IP-SLA is already in place and tested, be sure to have ```$config['enable_sla'] ``` set.
<img width="502" alt="screen shot 2016-07-12 at 20 45 09" src="https://cloud.githubusercontent.com/assets/6378934/16779210/945db728-4871-11e6-8abb-be70583c9abc.png">

Only Juniper RPM missing - I don't have access to such a device sadly.

**Comment by pereyrdi** [comment]
Hi, I enable it and still dont see any values from slas.

[root@librenms librenms]# ./discovery.php -h coreipsla -d -m cisco-sla

LibreNMS Discovery
Version info:
Commit SHA: d526a16042418d27f3404de28d98118bc67bef57
DB Schema: 157
PHP: 7.0.14
MySQL: 5.5.52-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2
DEBUG!
SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
DB Schema already up to date.
SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE 'core2-wan-ipsla' ORDER BY device_id DESC] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '165'] 
core2-wan-ipsla 165 ios SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '165' AND `attrib_type` = 'poll_mib' ] 

Modules status: Global+ OS+ Device  
#### Load disco module cisco-sla ####

>> Runtime for discovery module 'cisco-sla': 0.0000 seconds
#### Unload disco module cisco-sla ####

SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '165' AND `attrib_type` = 'poll_mib' ] 
SQL[UPDATE `devices` set `last_discovered` =NOW(),`last_discovered_timetaken` ='0.004' WHERE `device_id` = '165'] 
Discovered in 0.004 seconds

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('discover','core2-wan-ipsla','1494516579.8997','0.096','1','librenms\n')] 
./discovery.php coreipsla 2017-05-11 12:29:40 - 1 devices discovered in 0.096 secs
SNMP: Get[0/0.00s] Walk [0/0.00s]
MySQL: Cell[3/0.00s] Row[0/-0.00s] Rows[2/0.00s] Column[0/0.00s] Update[1/0.06s] Insert[1/0.06s] Delete[0/0.00s]


Any idea ?
