### ISSUE TITLE
Enhancement: WebUI - Bulk delete devices

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#2608]
Convert the existing UI to a bulk method.
Perhaps by simply just using a table instead of a dropdown.

**Comment by Rosiak** [comment]
I think this fits the task:
http://www.jquery-bootgrid.com/Examples#selection

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #161](https://github.com/librenms/librenmsv2/issues/161) via [**ZenHub**](https://www.zenhub.com/)
