### ISSUE TITLE
LLDP discovery on devices with absent lldpRemSysName field

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#2614]
have here some enterasys G3G124-24P (Rev 06.03.08.0012) without lldpRemSysName information in snmp. 

/usr/bin/snmpbulkwalk -v2c -c public -O QUs -M /opt/librenms/mibs -m LLDP-MIB udp:10.131.30.232:161 lldpRemoteSystemsData
lldpRemChassisIdSubtype.0.23.2 = macAddress
lldpRemChassisId.0.23.2 = "20 B3 99 0A 6B DE "
lldpRemPortIdSubtype.0.23.2 = interfaceName
lldpRemPortId.0.23.2 = "ge.1.24"
lldpRemSysCapSupported.0.23.2 = "00 00 "
lldpRemSysCapEnabled.0.23.2 = "00 00 "

but it should be possible to work with lldpRemChassisId (MAC) and get the Host Name  from Database right?
Do we store MAC addresses per device or per Port?

**Comment by laf** [comment]
lol, we've only just merged a PR in that deals with lldpRemPortId having a mac address stored as well. Should be easy to add another element to the query:

https://github.com/librenms/librenms/commit/8ed1a50657579fae079ab3401a6d6614db69d21f
