### ISSUE TITLE
IRC alerts fail

### ISSUE THREAD

**Issue by hlmtre** [librenms/librenms#2624]
When attempting to send alerts to the IRC transport, the bot appropriately joins the channel, but never says anything, or responds to commands.

**Comment by hlmtre** [comment]
I'm actually working on this -- can it be assigned to me?

**Comment by f0o** [comment]
IRC Bot is working fine here, complaining about all sorts of things:
```
08:25:25 LibreNMS | Alert for device dns.int - High Mem - Rule: High Mem - Faults:
08:25:26 LibreNMS | #1 mempool_id => 39; mempool_descr => Virtual memory;
```

**Comment by SaaldjorMike** [comment]
@hlmtre Can you provide your IRC settings from the config file?
`grep irc /opt/librenms/config.php`
Remember to remove any sensitive information.

**Comment by laf** [comment]
Ditto. Do you have:

`$config['irc_alert_chan'] = '#netalerts';` set?

**Comment by hlmtre** [comment]
Certainly.

    $config['irc_host'] = "prod-srv";
    $config['irc_port'] = 6667;
    $config['irc_chan'] = "#networks";

`prod-srv` is pingable from the librenms box (it is an IRC server hosted on my network).

http://aql.ink/6dCoFUML.png

That's all Mr Bot does.

**Comment by laf** [comment]
@hlmtre You need the config I mentioned above.

**Comment by f0o** [comment]
More importantly, you need to tell the bot to actually care about alerts..
http://docs.librenms.org/Extensions/IRC-Bot/
`$config['irc_alert']	= true;`

otherwise it wont do anything

**Comment by hlmtre** [comment]
Apologies, I didn't get from the docs that the alerting functionality had to be explicitly enabled; I thought that that was the basic purpose of the IRC bot and all that was required for that was 

    $config['irc_host'] = "myserver";
    $config['irc_port'] = myport;
    $config['irc_chan'] = "#mynetwork";



damn damn damn damn
