### ISSUE TITLE
Some graphs not drawn for QNAP storage

### ISSUE THREAD

**Issue by markuspachali** [librenms/librenms#2625]
Hi all,
I have a little problem with the storage and memory graph on the right top of the website for a QNAP Turbo NAS TS-809U running OS 4.2.0. For the memory graph it says "Error drawing graph" and for the storage nothing is display. The strange thing is, that on the host overview page in the sections "Memory Pools" and "Storage" everything is displayed as expected. If I click on "Show RRD Command" for the memory graph the RRDTool Output is "ERROR: opening '/opt/librenms/rrd/$HOSTNAME/ucd_mem.rrd': No such file or directory", which is correct, the file isn't there.
The Processor usage graph on the right top is displayed and rendered as expected.

I do not have that problem with any other host, so it doesn't looks like a general issue.

Im running LibreNMS on CentOS 7.1 with latest updates and RRDTool version 1.4.8.

Does anyone have an idea what could be the problem?

Best regards,
Markus

**Comment by Rosiak** [comment]
Hi @markuspachali 
Please run the validate.php

**Comment by markuspachali** [comment]
Hi @Rosiak 
validate.php runs without errors:
[root@librenms librenms]# ./validate.php
[OK]      config.php tested ok
[OK]      Database connection successful
[OK]      fping has been found
[root@librenms librenms]#

**Comment by laf** [comment]
I expect it's similar to another issue we had as we can show different memory/storage graphs on different pages :/

Can you go to Health -> Overview page for the device. Click on both the memory and Disk usage graphs, then on the new page -> Show RRD Command and paste the output onto dpaste.de and link here.

**Comment by markuspachali** [comment]
I have Physical Memory, Virtual Memory and Swap Space. I've selected Physical Memory as an example. If you need also the others please let me know:
https://dpaste.de/64W0

For Storage there are three mount points. I've selected /mnt/HDA_ROOT, if you need also the others, please let me know:
https://dpaste.de/JY4D

**Comment by laf** [comment]
You should have an overview graph for memory and storage, rather than drilling down if you stay on the health -> overview page.

**Comment by markuspachali** [comment]
Nope, if I click Health -> Memory I see three graphs for that host (Physical, Swap and Virtual) and if I click on Health -> Storage I see also three graphs for the three discovered mount points. There is no combined graph for no device.

**Comment by laf** [comment]
Ah you're clicking the heading, click the actual graph which shows everything in one.

**Comment by markuspachali** [comment]
Okay, I was in the wrong section. I'd selected health from the top bar and not from the host overview.

Memory:
https://dpaste.de/D0EZ

Storage/Disk usage:
https://dpaste.de/eE5i

**Comment by laf** [comment]
@markuspachali 

Please try this, edit includes/definitions.inc.php and find this line:

`$os = 'qnap';`

Below:

`$config['os'][$os]['ifXmcbc'] = 1;`

Add this:

```php
$config['os'][$os]['over'][0]['graph'] = 'device_processor';
$config['os'][$os]['over'][0]['text']  = 'Processor Usage';
$config['os'][$os]['over'][1]['graph'] = 'device_ucd_memory';
$config['os'][$os]['over'][1]['text']  = 'Memory Usage';
$config['os'][$os]['over'][2]['graph'] = 'device_storage';
$config['os'][$os]['over'][2]['text']  = 'Storage Usage';
```

And try again.

**Comment by markuspachali** [comment]
Neil: Thanks for that. I will do that as soon as I'm back home from my trip to Munich on Monday evening.

Von meinem iPhone gesendet

**Comment by markuspachali** [comment]
@laf 
I've added the lines. There are good and bad news. The storage graph is now displayed, but the graph for the memory is still not working. I think the problem is, that QNAP does not support the UCD MIB and so there are also no UCD graphs which can be used. In the rrd folder I have the following files:
-rw-rw-r--. 1 librenms librenms 123K Dec 23 14:30 hr_processes.rrd
-rw-rw-r--. 1 librenms librenms 123K Dec 23 14:30 hr_users.rrd
-rw-rw-r--. 1 librenms librenms 1.9M Dec 23 14:30 ipSystemStats-ipv4.rrd
-rw-rw-r--. 1 librenms librenms 1.9M Dec 11 15:35 ipSystemStats-ipv6.rrd
-rw-rw-r--. 1 librenms librenms 243K Dec 23 14:30 mempool-hrstorage-1.rrd
-rw-rw-r--. 1 librenms librenms 243K Dec 23 14:30 mempool-hrstorage-10.rrd
-rw-rw-r--. 1 librenms librenms 243K Dec 23 14:30 mempool-hrstorage-3.rrd
-rw-rw-r--. 1 librenms librenms 1.9M Dec 23 14:30 netstats-ip.rrd
-rw-rw-r--. 1 librenms librenms 1.2M Dec 23 14:30 netstats-tcp.rrd
-rw-rw-r--. 1 librenms librenms 483K Dec 23 14:30 netstats-udp.rrd
-rw-rw-r--. 1 librenms librenms 483K Dec 23 14:30 ospf-statistics.rrd
-rw-rw-r--. 1 librenms librenms 123K Dec 23 14:30 ping-perf.rrd
-rw-rw-r--. 1 librenms librenms 123K Dec 23 14:30 poller-perf.rrd
-rw-rw-r--. 1 librenms librenms 1.8M Dec 23 14:30 port-1.rrd
-rw-rw-r--. 1 librenms librenms 1.8M Dec 23 14:30 port-2.rrd
-rw-rw-r--. 1 librenms librenms 1.8M Dec 23 14:30 port-3.rrd
-rw-rw-r--. 1 librenms librenms 1.8M Dec 23 14:30 port-4.rrd
-rw-rw-r--. 1 librenms librenms 123K Dec 23 14:30 processor-hr-768.rrd
-rw-rw-r--. 1 librenms librenms 123K Dec 23 14:30 processor-hr-769.rrd
-rw-rw-r--. 1 librenms librenms 243K Dec 23 14:30 storage-hrstorage-_mnt_HDA_ROOT.rrd
-rw-rw-r--. 1 librenms librenms 243K Dec 23 14:30 storage-hrstorage-_mnt_ext.rrd
-rw-rw-r--. 1 librenms librenms 243K Dec 23 14:30 storage-hrstorage-_share_MD0_DATA.rrd
-rw-rw-r--. 1 librenms librenms 123K Dec 23 14:30 uptime.rrd

For me it looks like the mempool files have to be used instead the UCD files.

Best regards,
Markus

**Comment by laf** [comment]
Sorry for the delay, I've submitted a PR that will fix this. Once it's merged you will need to revert the change you did above `git checkout -- includes/definitions.inc.php` and then run ./daily.sh

**Comment by markuspachali** [comment]
@laf Many thanks! I can confirm, that the graphs are now displayed as expected :)
