### ISSUE TITLE
PowerWalker Devices

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#2626]
MIBs: http://www.powerwalker.com/index.php?page=nmc&lang=en
`sysObject.0 => enterprises.935.10.1`
`sysDesc.0 => Network Management Card for UPS`
`sysObjectID.0 => .1.3.6.1.4.1.935.10.1`

walk pending

**Comment by Rosiak** [comment]
Mailed them regarding their logo.

**Comment by f0o** [comment]
Thanks!

**Comment by Rosiak** [comment]
@f0o Able to supply a walk?

**Comment by f0o** [comment]
still now sign of it :<
