### ISSUE TITLE
Ever devices

### ISSUE THREAD

**Issue by krzysztofpuchala** [librenms/librenms#2628]
MIBS: http://ever.eu/uploads/product/links/3deb8cdb9f62b4cf533d16433d3a9caf68e6ebe6.txt
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.9797.1.2.1.1.0
iso.3.6.1.2.1.1.3.0 = Timeticks: (299217718) 34 days, 15:09:37.18
iso.3.6.1.2.1.1.4.0 = STRING: "Kontakt do administratora"
iso.3.6.1.2.1.1.5.0 = STRING: "Nazwa"
iso.3.6.1.2.1.1.6.0 = STRING: "Lokalizacja"
iso.3.6.1.2.1.1.7.0 = INTEGER: 72

**Comment by laf** [comment]
Can you provide the debug output from:

```bash
./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -d -r -m system,os
```

**Comment by krzysztofpuchala** [comment]
LibreNMS 2015.master Discovery
commit 271f0591e84f17e7a51a6bd0644666a6c9ef254c

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
SQL[SELECT revision FROM `dbSchema`] DB Schema already up to date.

SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE '192.168.10.199' ORDER BY device_id DESC] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '2'] 192.168.10.199 2 generic DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Ovq -M /opt/librenms/mibs udp:192.168.10.199:161 SNMPv2-MIB::sysDescr.0
Karta Zarzadzajaca Ever SNMP/HTTP

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Ovqn -M /opt/librenms/mibs udp:192.168.10.199:161 SNMPv2-MIB::sysObjectID.0
.1.3.6.1.4.1.9797.1.2.1.1.0

| Karta Zarzadzajaca Ever SNMP/HTTP | .1.3.6.1.4.1.9797.1.2.1.1.0 | DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Osqnv -M /opt/librenms/mibs udp:192.168.10.199:161 ENTITY-MIB::entPhysicalMfgName.1

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Oqv -M /opt/librenms/mibs udp:192.168.10.199:161 SML-MIB::product-Name.0

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Oqv -M /opt/librenms/mibs udp:192.168.10.199:161 1.3.6.1.4.1.674.10895.3000.1.2.100.1.0

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Oqv -M /opt/librenms/mibs udp:192.168.10.199:161 .1.3.6.1.4.1.39165.1.6.0

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Oqvn -M /opt/librenms/mibs udp:192.168.10.199:161 ENTITY-MIB::entPhysicalDescr.1
OS: DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Ovq -M /opt/librenms/mibs udp:192.168.10.199:161 SNMPv2-MIB::sysDescr.0
Karta Zarzadzajaca Ever SNMP/HTTP

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Ovqn -M /opt/librenms/mibs udp:192.168.10.199:161 SNMPv2-MIB::sysObjectID.0
.1.3.6.1.4.1.9797.1.2.1.1.0

| Karta Zarzadzajaca Ever SNMP/HTTP | .1.3.6.1.4.1.9797.1.2.1.1.0 | DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Osqnv -M /opt/librenms/mibs udp:192.168.10.199:161 ENTITY-MIB::entPhysicalMfgName.1

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Oqv -M /opt/librenms/mibs udp:192.168.10.199:161 SML-MIB::product-Name.0

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Oqv -M /opt/librenms/mibs udp:192.168.10.199:161 1.3.6.1.4.1.674.10895.3000.1.2.100.1.0

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Oqv -M /opt/librenms/mibs udp:192.168.10.199:161 .1.3.6.1.4.1.39165.1.6.0

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Oqvn -M /opt/librenms/mibs udp:192.168.10.199:161 ENTITY-MIB::entPhysicalDescr.1


SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='power',`last_discovered_timetaken` ='0.295' WHERE `devi--Więcce_id` = '2'] Discovered in 0.295 seconds


SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','192.168.10.199','1--Więc450557355.2425','0.316','1')] ./discovery.php 192.168.10.199 2015-12-19 21:35:55 - 1 devices discovered in 0.316 secs--WMySQL: Cell[1/0s] Row[1/0s] Rows[1/0s] Column[0/0s] Update[1/0.02s] Insert[1/0s] Delete[0/0s]
-------
LibreNMS 2015.master Poller
commit 271f0591e84f17e7a51a6bd0644666a6c9ef254c

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE '192.168.10.199' ORDER BY `device_id` ASC] 
SQL[SELECT * FROM `devices` WHERE `device_id` = '2'] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '2'] 192.168.10.199 2 generic 

SQL[INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('3','3','0','1.69','3.74','2.66','2',NOW())] DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:192.168.10.199:161 sysObjectID.0
SNMPv2-SMI::enterprises.9797.1.2.1.1.0

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -OQUs -m SNMPv2-MIB -M /opt/librenms/mibs udp:192.168.10.199:161 sysUpTime.0 sysLocation.0 sysContact.0 sysName.0
sysUpTime.0 = 39:3:57:47.65

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:192.168.10.199:161 sysDescr.0
Karta Zarzadzajaca Ever SNMP/HTTP

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Oqvn -m SNMPv2-MIB -M /opt/librenms/mibs udp:192.168.10.199:161 sysObjectID.0
.1.3.6.1.4.1.9797.1.2.1.1.0

DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -OUqv -m SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs udp:192.168.10.199:161 snmpEngineTime.0
DEBUG: SNMP Auth options =  -v1 -c public
/usr/bin/snmpget -v1 -c public -Oqv -m HOST-RESOURCES-MIB -M /opt/librenms/mibs udp:192.168.10.199:161 hrSystemUptime.0

Using SNMP Agent Uptime (39:3:57:47.65)
[RRD Disabled]RRD[update /opt/librenms/rrd/192.168.10.199/uptime.rrd N:3383867] Uptime: 39 days, 3h 57m 47s
Generic :(

Hardware:  Version:  Features:  Serial: 
[RRD Disabled]RRD[update /opt/librenms/rrd/192.168.10.199/poller-perf.rrd N:0.565] [RRD Disabled]RRD[update /opt/librenms/rrd/192.168.10.199/ping-perf.rrd N:2.66] Polled in 0.565 seconds
Updating 192.168.10.199
Array
(
    [uptime] => 3383867
    [last_ping] => Array
        (
            [0] => NOW()
        )

    [last_ping_timetaken] => 2.66
    [last_polled] => Array
        (
            [0] => NOW()
        )

    [last_polled_timetaken] => 0.565
)

SQL[UPDATE `devices` set `uptime` ='3383867',`last_ping` =NOW(),`last_ping_timetaken` ='2.66',`last_polled` =NOW()--Więc,`last_polled_timetaken` ='0.565' WHERE `device_id` = '2'] UPDATED!

SQL[SELECT * FROM device_groups ORDER BY name] 
SQL[SELECT DISTINCT(alert_schedule.schedule_id) FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedu--Więcle.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '2' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1] 
SQL[SELECT * FROM device_groups ORDER BY name] 
SQL[SELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.d--Więcisabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '2' ) || alert_map.target = '2'  )] 

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','192.168.10.19--Więc9','1450557391.3959','0.573','1','cacti\n')] ./poller.php 192.168.10.199 2015-12-19 21:36:31 - 1 devices polled in 0.--W573 secs

MySQL: Cell[1/0s] Row[2/0s] Rows[4/0s] Column[0/0s] Update[1/0s] Insert[2/0.02s] Delete[0/0s]

**Comment by Rosiak** [comment]
@krzysztofpuchala 
The pastes has expired :(

**Comment by Rosiak** [comment]
Will reopen when valid pastes appear.
