### ISSUE TITLE
PHP7.0-FPM Docs

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#2629]
Hi,

I'm running PHP7.0-FPM from dotdeb on my install and it works great.

Only bumps so far:
- PEAR needs to be installed manually with the gopear.phar
- PEAR's includepath needs to be added to fpm's php.ini as well as cli's php.ini
- DotDeb's php-packages have a different naming convention so dependencies are to be substituted from `php5-*` to either `php-*` or `php7.0-*`
- NetIPv4 and NetIPv6 are to be installed via pear, no package for it.
- Nginx's fpm-socket changed due to DotDeb's naming convention to `unix:/run/php/php7.0-fpm.sock;`
- Uninstall `php5-*` with `--purge` _BEFORE_ installing php7.0!

Keeping those points in mind the transition is very smooth. No service disruption where suffered in the making of this checklist ;)

As for performance improvements: I see none.

As for "what doesn't work":
- Accurate Greaphs, Historical Graphs and Transfer graphs from Billing due to a bug in JpGraph (it cant figure that 7.0.0 is greater than 5.1.0) #2631

**Comment by laf** [comment]
Is this needed still, anything for the docs?
