### ISSUE TITLE
Enhancement: Update bootstrap

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#2634]

**Comment by f0o** [comment]
Again? :D

**Comment by Rosiak** [comment]
@f0o 
Yuz! v3.3.6 is the latest now, we're on v3.3.5!!

**Comment by laf** [comment]
If it's not needed then I'd recommend leaving it. We have so many other elements that depend on it now it's difficult to 100% test compatibility

**Comment by Rosiak** [comment]
Agree @laf , closing for now.
