### ISSUE TITLE
New device: Ligowave LigoPTP

### ISSUE THREAD

**Issue by ekoyle** [librenms/librenms#2636]
I have some Ligowave LigoPTP 5-23 MiMo devices that are being discovered as generic devices.

Here is the discovery output:
[ligoptp_discovery.txt](https://github.com/librenms/librenms/files/64303/ligoptp_discovery.txt)

Here is the output of snmpwalk -Oqn:
[ligoptp_snmpwalk.txt](https://github.com/librenms/librenms/files/64288/ligoptp_snmpwalk.txt)

**Comment by Rosiak** [comment]
Tagging @SaaldjorMike 
Not sure if we should create a separate "os" for PTP or just rewrite the existing so it covers more than just the Infinity ones.
