### ISSUE TITLE
Mirth MIB

### ISSUE THREAD

**Issue by tylerapplebaum** [librenms/librenms#2639]
The MIB and OIDLIB are attached in the ZIP file. Is this something you'll support?

Thanks,

Tyler

**Comment by laf** [comment]
You've not linked to a mib. However that alone isn't what we need and we will need to know what it is you want to see out of it.

**Comment by tylerapplebaum** [comment]
[Mirth.zip](https://github.com/librenms/librenms/files/67031/Mirth.zip)

I'm looking for the Mirth connect channel stats in table form:

  MIRTH-MIB|mirth connect channel stats: #[1.3.6.1.4.1.29009.2.2.1.3.1.1.1]

**Comment by laf** [comment]
We will need the output of `snmpbulkwalk -Onet -v2c -c COMMUNITY HOSTNAME .` to progress this further.

**Comment by tylerapplebaum** [comment]
[Mirth.txt](https://github.com/librenms/librenms/files/520523/Mirth.txt)

It's attached. Thanks for sticking with this one!

**Comment by laf** [comment]
Sorry about this, can you confirm more info on what Mirth is, what is the name of the actual OS.

**Comment by tylerapplebaum** [comment]
@laf - Mirth is an HL7 interface engine. It's Java software with Apache that runs on Linux. The shell is rather locked down, so I can't do much from the console.

https://en.wikipedia.org/wiki/Mirth_Connect

An NMAP scan gives these details:

Device type: general purpose
Running: Linux 2.6.X
OS CPE: cpe:/o:linux:linux_kernel:2.6
OS details: Linux 2.6.9 - 2.6.18

**Comment by laf** [comment]
Thanks, pr submitted.
