### ISSUE TITLE
Config error causes alert spam

### ISSUE THREAD

**Issue by silverwizard** [librenms/librenms#2640]
I added a transport rule for Nagios compatible alerts to our local LibreNMS install. When it got to the Nagios alert it errored (I'd made a typo), and didn't increment the correct variables. Therefore when it got here:
            if (dbInsert(array('state' => $state, 'device_id' => $alert['device_
id'], 'rule_id' => $alert['rule_id'], 'details' => gzcompress(json_encode($alert
['details']), 9)), 'alert_log')) {
                dbUpdate(array('state' => $state, 'open' => 1, 'alerted' => 1), 'alerts', 'rule_id = ? && device_id = ?', array($alert['rule_id'], $alert['device_id']));
            }

It didn't run the dbUpdate command since the array didn't increment - meaning every single minute it would spam out the alert every time. It should be logging the error, and then carrying on.

I don't really have a sense of the internals of LibreNMS (and no time to commit to the project) but that's the trace I did to find the error.

**Comment by f0o** [comment]
That sounds more like you got an interval running. That code part doesnt care about the success or failure of a transport

On 17 December 2015 21:13:23 CET, silverwizard <notifications@github.com> wrote:
>I added a transport rule for Nagios compatible alerts to our local
>LibreNMS install When it got to the Nagios alert it errored (I'd made a
>typo), and didn't increment the correct variables Therefore when it got
>here:
>   if (dbInsert(array('state' => $state, 'device_id' => $alert['device_
>id'], 'rule_id' => $alert['rule_id'], 'details' =>
>gzcompress(json_encode($alert
>['details']), 9)), 'alert_log')) {
>dbUpdate(array('state' => $state, 'open' => 1, 'alerted' => 1),
>'alerts', 'rule_id = ? && device_id = ?', array($alert['rule_id'],
>$alert['device_id']));
>            }
>
>It didn't run the dbUpdate command since the array didn't increment -
>meaning every single minute it would spam out the alert every time It
>should be logging the error, and then carrying on
>
>I don't really have a sense of the internals of LibreNMS (and no time
>to commit to the project) but that's the trace I did to find the error
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2640

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by laf** [comment]
I can confirm that this is the case. When testing new transports if they don't function correctly then the alert is never sent so it will continue to re-attempt each minute.

**Comment by f0o** [comment]
How can i reproduce this?

**Comment by laf** [comment]
I had the issue before the last update to the hipchat transport, I had that configured and got continuous mail alerts as that transport was ok but hipchat wasn't.

That's from memory but I think that's what it was.

**Comment by silverwizard** [comment]
I added the wrong file to the Nagios transport and caused this error

**Comment by f0o** [comment]
Just to be 100% sure here, can you paste me exactly what config parameter you used - would really like to recreate the same situation. Also please tell us your LibreNMS version as well.

**Comment by silverwizard** [comment]
I had /var/spool/nagios in the nagios transport (which was been good, until that became a directory)

Version	d385a6a

**Comment by laf** [comment]
This was resolved a while ago, transports now log the status when sending.
