### ISSUE TITLE
Palo Alto Firewall Global Protect connected users

### ISSUE THREAD

**Issue by jcounsell1222** [librenms/librenms#2641]
Hey guys,

i was wondering if i am missing something here. i am trying to see if Libre can show active connected global protect users connected to a palo alto firewall. similar to the command "show global-protect-gateway current-user".

thanks in advance.

**Comment by Rosiak** [comment]
@jcounsell1222 
Can you supply a SNMPWALK with mibs loaded?

**Comment by Rosiak** [comment]
@jcounsell1222 any news?

**Comment by FTBZ** [comment]
Added Active GlobalProtect Tunnels graph to PANOS #4654
