### ISSUE TITLE
Poller performance improvement for sensors - beta testers needed

### ISSUE THREAD

**Issue by laf** [librenms/librenms#2643]
https://github.com/laf/librenms/tree/sensors-perf

This branch is currently upto date with LibreNMS master. For me with devices that have a large number of sensors (> 100) I get a saving of around 5-10 seconds per device:

![image](https://cloud.githubusercontent.com/assets/3941142/11896516/fd09096c-a57e-11e5-9797-5f243f36641e.png)

The poll_sensor call has been updated in a big way and I'd like to see if this affects other devices if anyone is willing to try it?

**Comment by f0o** [comment]
On it :)

**Comment by Rosiak** [comment]
merged #2637

**Comment by laf** [comment]
This isn't the same thing
