### ISSUE TITLE
Cambium do not give ifAlias or ifName - Api Search via ifDescr

### ISSUE THREAD

**Issue by cchance27** [librenms/librenms#2644]
As per  our convo on the IRC, i create this issue because the Cambium 450's do not return ifName or ifAlias only ifDescr, and as such we can't access their interfaces via the API...

I'm hoping you will be able to add the ability to the API to search via the ifDescr as an alternate.

Below is an example of the db for one of the devices.

MariaDB [librenms]>  SELECT ifName,ifDescr,IfAlias FROM ports where device_id=49;
+--------+--------------------+---------+
| ifName | ifDescr            | IfAlias |
+--------+--------------------+---------+
| NULL   | Cambium 10/100 FEC | None    |
| NULL   | Canopy MultiPoint  | None    |
+--------+--------------------+---------+

**Comment by laf** [comment]
Once this is merged in, you can just append ?ifDescr=true to the API call.
