### ISSUE TITLE
EDP Discovery Integration (extremenetworks)

### ISSUE THREAD

**Issue by cchance27** [librenms/librenms#2646]
Do you need access (working on it) or just a sample of the snmp walk from the EDP discovery? I've attached it below it seems pretty straight forward its basically just a snmp table of neighboring switches.

extremeEdpNeighborName(3)
extremeEdpNeighborSoftwareVersion(4)
extremeEdpNeighborSlot(5)
extremeEdpNeighborPort(6)
extremeEdpEntryAge(7)

I walked one of my switches

snmpwalk -v 2c -c xxxxxx 172.16.0.11      1.3.6.1.4.1.1916.1.13.2

SNMPv2-SMI::enterprises.1916.1.13.2.1.3.1017.0.0.0.4.150.39.190.77 = STRING: "SITEASW-1"
SNMPv2-SMI::enterprises.1916.1.13.2.1.3.1018.0.0.0.4.150.54.209.37 = STRING: "SITEBSW-1"
SNMPv2-SMI::enterprises.1916.1.13.2.1.3.1021.0.0.0.4.150.55.39.22 = STRING: "SITECSW-1"
SNMPv2-SMI::enterprises.1916.1.13.2.1.3.1022.0.0.0.4.150.52.203.77 = STRING: "SITEDSW-1"
SNMPv2-SMI::enterprises.1916.1.13.2.1.3.1023.0.0.0.4.150.52.169.38 = STRING: "SITEESW-1"
SNMPv2-SMI::enterprises.1916.1.13.2.1.3.1031.0.0.0.4.150.153.88.238 = STRING: "SITEFSW-02"
SNMPv2-SMI::enterprises.1916.1.13.2.1.3.1032.0.0.0.4.150.153.66.231 = STRING: "SITEGSW-01"

SNMPv2-SMI::enterprises.1916.1.13.2.1.4.1017.0.0.0.4.150.39.190.77 = STRING: "15.3.1.4"
SNMPv2-SMI::enterprises.1916.1.13.2.1.4.1018.0.0.0.4.150.54.209.37 = STRING: "15.3.1.4"
SNMPv2-SMI::enterprises.1916.1.13.2.1.4.1021.0.0.0.4.150.55.39.22 = STRING: "15.3.1.4"
SNMPv2-SMI::enterprises.1916.1.13.2.1.4.1022.0.0.0.4.150.52.203.77 = STRING: "15.3.1.4"
SNMPv2-SMI::enterprises.1916.1.13.2.1.4.1023.0.0.0.4.150.52.169.38 = STRING: "15.3.1.4"
SNMPv2-SMI::enterprises.1916.1.13.2.1.4.1031.0.0.0.4.150.153.88.238 = STRING: "15.6.2.12"
SNMPv2-SMI::enterprises.1916.1.13.2.1.4.1032.0.0.0.4.150.153.66.231 = STRING: "15.6.2.12"

SNMPv2-SMI::enterprises.1916.1.13.2.1.5.1017.0.0.0.4.150.39.190.77 = INTEGER: 1
SNMPv2-SMI::enterprises.1916.1.13.2.1.5.1018.0.0.0.4.150.54.209.37 = INTEGER: 1
SNMPv2-SMI::enterprises.1916.1.13.2.1.5.1021.0.0.0.4.150.55.39.22 = INTEGER: 1
SNMPv2-SMI::enterprises.1916.1.13.2.1.5.1022.0.0.0.4.150.52.203.77 = INTEGER: 1
SNMPv2-SMI::enterprises.1916.1.13.2.1.5.1023.0.0.0.4.150.52.169.38 = INTEGER: 1
SNMPv2-SMI::enterprises.1916.1.13.2.1.5.1031.0.0.0.4.150.153.88.238 = INTEGER: 1
SNMPv2-SMI::enterprises.1916.1.13.2.1.5.1032.0.0.0.4.150.153.66.231 = INTEGER: 1

SNMPv2-SMI::enterprises.1916.1.13.2.1.6.1017.0.0.0.4.150.39.190.77 = INTEGER: 24
SNMPv2-SMI::enterprises.1916.1.13.2.1.6.1018.0.0.0.4.150.54.209.37 = INTEGER: 24
SNMPv2-SMI::enterprises.1916.1.13.2.1.6.1021.0.0.0.4.150.55.39.22 = INTEGER: 15
SNMPv2-SMI::enterprises.1916.1.13.2.1.6.1022.0.0.0.4.150.52.203.77 = INTEGER: 23
SNMPv2-SMI::enterprises.1916.1.13.2.1.6.1023.0.0.0.4.150.52.169.38 = INTEGER: 18
SNMPv2-SMI::enterprises.1916.1.13.2.1.6.1031.0.0.0.4.150.153.88.238 = INTEGER: 11
SNMPv2-SMI::enterprises.1916.1.13.2.1.6.1032.0.0.0.4.150.153.66.231 = INTEGER: 11

SNMPv2-SMI::enterprises.1916.1.13.2.1.7.1017.0.0.0.4.150.39.190.77 = INTEGER: 42
SNMPv2-SMI::enterprises.1916.1.13.2.1.7.1018.0.0.0.4.150.54.209.37 = INTEGER: 34
SNMPv2-SMI::enterprises.1916.1.13.2.1.7.1021.0.0.0.4.150.55.39.22 = INTEGER: 43
SNMPv2-SMI::enterprises.1916.1.13.2.1.7.1022.0.0.0.4.150.52.203.77 = INTEGER: 50
SNMPv2-SMI::enterprises.1916.1.13.2.1.7.1023.0.0.0.4.150.52.169.38 = INTEGER: 40
SNMPv2-SMI::enterprises.1916.1.13.2.1.7.1031.0.0.0.4.150.153.88.238 = INTEGER: 10
SNMPv2-SMI::enterprises.1916.1.13.2.1.7.1032.0.0.0.4.150.153.66.231 = INTEGER: 47

**Comment by laf** [comment]
I'm not sure that is a full walk of the correct table. Try:

snmpwalk -v 2c -c xxxxxx 172.16.0.11  -M /opt/librenms/mibs/ -m EXTREME-BASE-MIB extremeEdpEntry

We really could do with access if possible, it would simplify the whole thing.

**Comment by cchance27** [comment]
Ya i'm trying to arrange access, but need permissions from management to do it... in the meantime here you go... looks about the same

[root@librenms ~]# snmpwalk -v 2c -c xxxxxxxx 172.16.0.11 -M /opt/librenms/mibs/ -m EXTREME-BASE-MIB extremeEdpEntry

EXTREME-EDP-MIB::extremeEdpNeighborName.1017.'.....'.M' = STRING: "SITEASW-1"
EXTREME-EDP-MIB::extremeEdpNeighborName.1018.'.....6.%' = STRING: "SITEBSW-1"
EXTREME-EDP-MIB::extremeEdpNeighborName.1021.'.....7'.' = STRING: "SITECSW-1"
EXTREME-EDP-MIB::extremeEdpNeighborName.1022.'.....4.M' = STRING: "SITEDSW-1"
EXTREME-EDP-MIB::extremeEdpNeighborName.1023.'.....4.&' = STRING: "SITEESW-1"
EXTREME-EDP-MIB::extremeEdpNeighborName.1031.'......X.' = STRING: "SITEFSW-02"
EXTREME-EDP-MIB::extremeEdpNeighborName.1032.'......B.' = STRING: "SITEGSW-01"
EXTREME-EDP-MIB::extremeEdpNeighborSoftwareVersion.1017.'.....'.M' = STRING: "15.3.1.4"
EXTREME-EDP-MIB::extremeEdpNeighborSoftwareVersion.1018.'.....6.%' = STRING: "15.3.1.4"
EXTREME-EDP-MIB::extremeEdpNeighborSoftwareVersion.1021.'.....7'.' = STRING: "15.3.1.4"
EXTREME-EDP-MIB::extremeEdpNeighborSoftwareVersion.1022.'.....4.M' = STRING: "15.3.1.4"
EXTREME-EDP-MIB::extremeEdpNeighborSoftwareVersion.1023.'.....4.&' = STRING: "15.3.1.4"
EXTREME-EDP-MIB::extremeEdpNeighborSoftwareVersion.1031.'......X.' = STRING: "15.6.2.12"
EXTREME-EDP-MIB::extremeEdpNeighborSoftwareVersion.1032.'......B.' = STRING: "15.6.2.12"
EXTREME-EDP-MIB::extremeEdpNeighborSlot.1017.'.....'.M' = INTEGER: 1
EXTREME-EDP-MIB::extremeEdpNeighborSlot.1018.'.....6.%' = INTEGER: 1
EXTREME-EDP-MIB::extremeEdpNeighborSlot.1021.'.....7'.' = INTEGER: 1
EXTREME-EDP-MIB::extremeEdpNeighborSlot.1022.'.....4.M' = INTEGER: 1
EXTREME-EDP-MIB::extremeEdpNeighborSlot.1023.'.....4.&' = INTEGER: 1
EXTREME-EDP-MIB::extremeEdpNeighborSlot.1031.'......X.' = INTEGER: 1
EXTREME-EDP-MIB::extremeEdpNeighborSlot.1032.'......B.' = INTEGER: 1
EXTREME-EDP-MIB::extremeEdpNeighborPort.1017.'.....'.M' = INTEGER: 24
EXTREME-EDP-MIB::extremeEdpNeighborPort.1018.'.....6.%' = INTEGER: 24
EXTREME-EDP-MIB::extremeEdpNeighborPort.1021.'.....7'.' = INTEGER: 15
EXTREME-EDP-MIB::extremeEdpNeighborPort.1022.'.....4.M' = INTEGER: 23
EXTREME-EDP-MIB::extremeEdpNeighborPort.1023.'.....4.&' = INTEGER: 18
EXTREME-EDP-MIB::extremeEdpNeighborPort.1031.'......X.' = INTEGER: 11
EXTREME-EDP-MIB::extremeEdpNeighborPort.1032.'......B.' = INTEGER: 11
EXTREME-EDP-MIB::extremeEdpEntryAge.1017.'.....'.M' = INTEGER: 46
EXTREME-EDP-MIB::extremeEdpEntryAge.1018.'.....6.%' = INTEGER: 39
EXTREME-EDP-MIB::extremeEdpEntryAge.1021.'.....7'.' = INTEGER: 19
EXTREME-EDP-MIB::extremeEdpEntryAge.1022.'.....4.M' = INTEGER: 50
EXTREME-EDP-MIB::extremeEdpEntryAge.1023.'.....4.&' = INTEGER: 52
EXTREME-EDP-MIB::extremeEdpEntryAge.1031.'......X.' = INTEGER: 16
EXTREME-EDP-MIB::extremeEdpEntryAge.1032.'......B.' = INTEGER: 13

**Comment by cchance27** [comment]
anyone get a chance to look into this? Any further info needed?

**Comment by laf** [comment]
If you can provide us the output of `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .` that will help

**Comment by laf** [comment]
Not further info provided

**Comment by ellisway** [comment]
hi can this issue be reopened

i have a data set for 2 devices connected together running with lldp and edp located at the following address

https://gist.github.com/ellisway/66570136d6af0da410d54d632ca5f79a

ellis

**Comment by laf** [comment]
I suggest you open a thread on the community forum.
