### ISSUE TITLE
Feature request: permissions on sensors

### ISSUE THREAD

**Issue by jviersel** [librenms/librenms#2650]
Currently, i can give users permissions on network interfaces (ports) instead of the full device. But for sensors i can only give access to the full device. On devices like powerbars, i would like to limit this to just the assigned powerport (sensor).

**Comment by Rosiak** [comment]
Hi,

We are cleaning up the issues here on GitHub, all feature requests will be moved to:
https://community.librenms.org/c/feature-requests

Hence the closure of this issue.
