### ISSUE TITLE
missed MIBs

### ISSUE THREAD

**Issue by tsypa** [librenms/librenms#2652]
php poller.php -d -r -m snmp -h localhost
MIB search path: /opt/librenms/mibs
Cannot find module (MTA-MIB): At line 1 in (none)
Cannot find module (NETWORK-SERVICES-MIB): At line 1 in (none)

**Comment by f0o** [comment]
I dont think `-m snmp` does anything...

**Comment by laf** [comment]
No but we do indeed get those warnings. Whilst it's not an actual issue it is annoying so think we should merge in the PR that adds these mibs.
