### ISSUE TITLE
Feature Request: Navigation Menu for Weathermaps

### ISSUE THREAD

**Issue by elleryweber** [librenms/librenms#2656]
The PHP Weathermap 'plugin' for Observium has a custom navbar include that allows quick selection of maps that have been created. Is this something that could be easily incorporated into LibreNMS?

I submitted this issue with the plugin creator (https://github.com/librenms-plugins/Weathermap) and he suggested that I post it over here.

Thanks!

**Comment by f0o** [comment]
:+2:

**Comment by Rosiak** [comment]
I made this at some point, is this good or should we proceed for a version more integrated in the menubar?
![screen shot 2015-12-21 at 18 29 57](https://cloud.githubusercontent.com/assets/6378934/11936882/0a96164e-a811-11e5-9010-e8e10fa6e727.png)

**Comment by elleryweber** [comment]
I think this looks great, personally. Is this just what appears when you
click on the plugin entry?

EW



--- Ellery Weber

**Comment by masonke** [comment]
Looks good, easy to use. 
👍

**Comment by huegelc** [comment]
Hi, how does this work?

**Comment by huegelc** [comment]
Got it, thx. But instead of using all maps on a single page I think it would be better to have a submenu with the different maps like here: http://blog.best-practice.se/2014/07/using-php-weathermap-with-observium.html

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-navigation-menu-for-weathermaps/728
