### ISSUE TITLE
Uptime % in a day/month/year for devices

### ISSUE THREAD

**Issue by arjitc** [librenms/librenms#2658]
Would be nice to have this feature/stat as well, perhaps under Availability?

EDIT: Just further clarifying, I mean in text based stats for this, uptime in %, last downtime (timestamp), current uptime (in hours) and last downtime duration

**Comment by Rosiak** [comment]
@arjitc 
Think this is the same as #2139 is asking for, right?

**Comment by arjitc** [comment]
Ah yes, it's the same @Rosiak  . Closing this one :)
