### ISSUE TITLE
Export graphs option

### ISSUE THREAD

**Issue by arjitc** [librenms/librenms#2659]
Would be nice to have a option to export graphs as currently right click & save gets a graph with a transparent background which looks pretty weird in many image viewers.

**Comment by paulgear** [comment]
:+1:
Are you suggesting that the export would force a coloured background?

**Comment by arjitc** [comment]
Yup exactly @paulgear

**Comment by pecharmin** [comment]
:+1:  An export feature - may also with template support - would be a great thing :)
I currently gather graph data using scripts, but that's not so fancy :(

**Comment by paulgear** [comment]
For the record, there's always the API for pulling graphs out...

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #165](https://github.com/librenms/librenmsv2/issues/165) via [**ZenHub**](https://www.zenhub.com/)
