### ISSUE TITLE
monitoring active directory

### ISSUE THREAD

**Issue by fran-nlt** [librenms/librenms#2661]
Hi
I need monitoring active directory of Windows Server
I need view user login
Avality of Service

Is possible?

**Comment by murrant** [comment]
You can monitor availability with the services monitoring: 
config.php:
```
$config['show_services'] = 1;
```
/etc/cron.d/librenms.nonroot.cron:
```
*/5   *    * * *   librenms    /opt/librenms/check-services.php >> /dev/null 2>&1
````

Then add ldap in the services section and configure it for your server(s).

To view user login, you will have to collect and collate windows security audit logs.  You might be able to use something like Graylog for this.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by laf** [comment]
No further info provided
