### ISSUE TITLE
Allow line graphs instead of stacked area graphs.

### ISSUE THREAD

**Issue by masonke** [librenms/librenms#2662]
For some of the graphs, they would make more sense to use lines instead of stacked areas to display the data. For instance, on the mysql connections, a glance at the graph gives the impression that there are 3,400 connections in use, yet the max is 1,600. If this was a line graph, it would be much easier to interpret. 

Would it be possible to add a switch or check box to switch to line graphs?

Thanks
![mysql-connections](https://cloud.githubusercontent.com/assets/1863778/11934572/1a71fb0e-a7d1-11e5-80e7-a59e5d9a7a7f.jpg)

**Comment by paulgear** [comment]
That graph really should be a line graph always, from my reading of the metrics; I can't see any of them which warrant stacking.

**Comment by masonke** [comment]
Not many should be stacked graphs,lines would make more sense
~KEM

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-allow-line-graphs-instead-of-stacked-area-graphs/727
