### ISSUE TITLE
poller.php doesn't properly parse unix process output when the TIME column has days in it

### ISSUE THREAD

**Issue by mneth1** [librenms/librenms#2664]
My current commit level from the git show command: commit ac46c70f7ed52d76a12e8823b0aa43d1cf2bcf45

When processes have used enough cpu TIME that they get into days, they begin to show the numbers of days with a hyphen before the standard time. Example from the output poller.php gets (which is the same TIME reported by ps -ef on the server):
(mysql,94989836,90144172,54-03:43:19,2468) /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib64/mysql/plugin --user=mysql

From the ps command man page explaining it:
"cputime     TIME      cumulative CPU time, "[DD-]hh:mm:ss" format."
The optional DD- part is when the process cpu time is in the days range.

I've attached the output from the command "./poller.php -h HOSTNAME -d -r -m unix-agent". If you search for process ID 2468 (which is /usr/sbin/mysqld) you can see the output above but that process info isn't in the INSERT into the process table. I spoke to @laf in the IRC channel and he suggested I open this issue.

[pollerOutput.txt](https://github.com/librenms/librenms/files/68941/pollerOutput.txt)

**Comment by mneth1** [comment]
For what it's worth, I seem to have fixed it by changing line 101 of $installDir/includes/polling/unix-agent.inc.php to this:
$process = preg_replace('/\((.*),([0-9]*),([0-9]*),([0-9]*-)?([0-9\:]*),([0-9]*)\)\ (.*)/', '\\1|\\2|\\3|\\4\\5|\\6|\\7', $process);

**Comment by f0o** [comment]
Can you PR that ? :)

**Comment by mneth1** [comment]
I actually don't have my own fork or anything, I was just tinkering with the files I pulled down to see if I could figure it out. I'm not entirely positive that regex is totally correct, either.

**Comment by laf** [comment]
This was fixed in #4653
