### ISSUE TITLE
Cisco OTV Poller

### ISSUE THREAD

**Issue by adaniels21487** [librenms/librenms#2665]
Discovery / Poller module to monitor Cisco OTV.

Team,
I would like to create this one as an 'application', which allows a global, and per-device view of OTV links. Are applications reserved for the unix agent only, or can I use them for this kind of thing as well?

Thanks,
Aaron

**Comment by paulgear** [comment]
@adaniels21487 Worth dropping into IRC ##librenms to discuss this; I think we need to provide a framework for allowing this without requiring people to re-implement that functionality for each module.

**Comment by adaniels21487** [comment]
As discussed on IRC.

The global menu:
![image](https://cloud.githubusercontent.com/assets/13431617/12280193/bff2764a-b9d7-11e5-90f0-ecd1c85af4b6.png)

The global apps page - there is only one device here (127.0.0.4) but if there were more they would apper below this table.
![image](https://cloud.githubusercontent.com/assets/13431617/12280208/da0bb942-b9d7-11e5-8002-d8a6e3efa2c1.png)

The device specific page has the table as well as some graphs.
![image](https://cloud.githubusercontent.com/assets/13431617/12280237/14772508-b9d8-11e5-91c2-db4fde7ca22a.png)

**Comment by paulgear** [comment]
Outcome of IRC discussion was that routing or plugins would probably be more appropriate locations for this.

**Comment by adaniels21487** [comment]
Indeed, Routing it is..

![image](https://cloud.githubusercontent.com/assets/13431617/12411326/727861b2-bec9-11e5-8230-1369a786b762.png)

![image](https://cloud.githubusercontent.com/assets/13431617/12411340/880825da-bec9-11e5-99b5-e96dfd8cb34c.png)
