### ISSUE TITLE
Strip quotes in ifAlias

### ISSUE THREAD

**Issue by PhilipOlsson** [librenms/librenms#2666]
We have quotes/ "" in many interface descriptions/ifAlias which prevents the "Port Description Parser" code from parsing those interfaces. 
There also seems to be some attempt to escape those quotes since we get '\' in the interface descriptions where quotes are supposed to be. 

Should be simple enough to replicate on any device with just inserting quotes / '"'  in any interface description.

A good way to handle this might be to strip quotes completely in ifAlias parsing code? 

See the attached pic for a example of an interface where it is actually '" "' enclosing the text and not '\' 
![image](https://cloud.githubusercontent.com/assets/16412082/11974003/2c00a196-a960-11e5-87fc-34f178934168.png)

**Comment by paulgear** [comment]
@PhilipOlsson Are you able to provide the output as reported by snmwalk so we can work out what's going on?

**Comment by PhilipOlsson** [comment]
Hi @paulgear, 

It seems that either net-snmp or the IOS appends '\'

snmpwalk -c public-v2c -M mibs/ -m +ALL device.local  
IF-MIB::ifAlias.9841 = STRING: \"COAX SYD1\"

You should see the same on any IOS device that has quotes in the ifAlias

**Comment by paulgear** [comment]
Thanks @PhilipOlsson
