### ISSUE TITLE
CTRL-click / middle mouse click on links opens target URL in current and new tab

### ISSUE THREAD

**Issue by RichiH** [librenms/librenms#2667]
If I open a link in a new tab, I have a reason to do so.

Sadly, many new-ish JS web UIs tend to open the target URL in the current tab as well, and LibreNMS is falling into the same trap.

**Comment by f0o** [comment]
Which links are you referring to?

**Comment by RichiH** [comment]
For example, any link on the left side of the lists of:
* http://librenms.foo/devices/type=network/
* http://librenms.foo/device/device=X/tab=ports/

**Comment by Rosiak** [comment]
Unable to reproduce this in: 
- Chrome Version 47.0.2526.106 (64-bit)
- Firefox 43.0.1 Build-ID 	20151216175450
- Safari Version 9.0.2 (11601.3.9)

**Comment by RichiH** [comment]
* http://foo/device/device=240/tab=ports/
* Click 1. FastEthernet0/1
* Reproduced using Chrome 46.0.2490.86 (64-bit)

**Comment by paulgear** [comment]
I reproduced this on Firefox 43.0 (64-bit) on Ubuntu Linux using the ports page on my switch, but only with Ctrl-Click.  Middle button click works as expected.

**Comment by Alucardfh** [comment]
Reproduced with middle click and ctrl+click on Chrome 47.0.2526.106 (Windows).
But right click/open in new tab doesn't produce the issue.

My guess is that this is related to the onclick tag that is used, like in 

https://github.com/librenms/librenms/blob/master/html/includes/print-interface.inc.php#L40

```php
echo "<tr style=\"background-color: $row_colour;\" valign=top onmouseover=\"this.style.backgroundColor='$list_highlight';\" onmouseout=\"this.style.backgroundColor='$row_colour';\" style='cursor: pointer;'>
    <td valign=top width=350 onclick=\"location.href='".generate_port_url($port)."'\">";
```

It would need replacing by a JS function that differentiate the actual button/keys that were pressed.
