### ISSUE TITLE
Add spanning tree (STP, RSTP, MSTP) support

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#2673]
It would be nice to have some spanning tree information inside librenms.
That would improve troubleshooting with STP related problems.
The most of STP information could be taken from BRIDGE-MIB, RSTP-MIB.

On the bridge (device) side we could have something like that in the new device STP tab:
- STP protocol (STP, RSTP, MSTP, ...)
- STP version
- Time since last topology change (e.g. 3 Days, 23:42:09)
- Amount of topology changes 
- Cost to root, root port, stp priority, root hello time, device hello time, and so on...

On the Port side:
- STP port role (root, designated, blocked, disabled, ...)
- Information about BPDU's on that port (rx, tx, invalid, amount, and so on...) 

Nice additional features inside LibreNMS could be then:
- mark the recent 24h topology changes on availability map widget (like reboots)
- mark blocked ports or show them in device-summary widget
- show STP related information on network map, maybe creation of different map views (like STP or connection View) to avoid map overload with visual things.

**Comment by markuspachali** [comment]
:+1:

**Comment by jcounsell1222** [comment]
I agree this would be a pretty cool feature to have.

**Comment by Lucheni** [comment]
+1

**Comment by vitalisator** [comment]
please assign to me...

**Comment by fubecka** [comment]
Piling on here as well, would love to have this.
