### ISSUE TITLE
visjs issues with overlapping links

### ISSUE THREAD

**Issue by djtecha** [librenms/librenms#2682]
There is an issue where if you have 2 edges between the same 2 nodes you get overlapping labels. Here I have 2 cables connected between a server and switch so it doesn't render great.

![map](https://cloud.githubusercontent.com/assets/3084627/12059085/3507368e-af09-11e5-943b-5ae67e0601cf.png)

**Comment by djtecha** [comment]
current layout:

$config['network_map_vis_options'] = '{
  layout:{
    improvedLayout: true
  },
  "edges": {
    "arrows": {
        "to": { 
            enabled: true,
            "scaleFactor": .25
        }
    },
    font: {
        align: "middle",
        strokeColor: "red",
        background: "black",
        size: 12
    },
    selfReferenceSize: true, 
    "color": {
        "color": "red",
        "hover": "#848484"
    },
    "dashes": true,
    "scaling": {
        "min": 3,
        "max": 3
    },
    "smooth": {
        enabled: true,
        type: "cubicBezier"
    },
  },
  "physics": {
    "forceAtlas2Based": {
      "gravitationalConstant": -180,
      "centralGravity": 0.01,
      "springLength": 800,
      "springConstant": 0,
      "damping": 1,
      "avoidOverlap": 1
    },
    "maxVelocity": 50,
    "minVelocity": 0.01,
    "solver": "forceAtlas2Based",
    "timestep": 0.30
  }
}';

**Comment by laf** [comment]
You can alter the config for visjs using the variable you mentioned above.

It also has an in built editor if you set `$config['network_map_vis_options'] = '{ configure": {}, }';`
