### ISSUE TITLE
GUI Search fails to return proper results

### ISSUE THREAD

**Issue by digitalpilotnm** [librenms/librenms#2683]
LibreNM version: 	041f9a1

When using the GUI search to search for ports, the returned choices are not complete.
For example, if one types in   hv003  to see all ethernet ports related to hv003, the dynamic search drop down only returns 1 choice, when there are 4 choices.
If one searches for  hv002  one gets two choices out of 4.

Here is what the SQL db shows

mysql> select ifAlias, ifDescr  from ports where ifalias like '%hv003%';
+-------------------------+---------------------+
| ifAlias                 | ifDescr             |
+-------------------------+---------------------+
| DRAC-hv003-dell-r720    | GigabitEthernet0/11 |
| hv003-dell-r720-mgnt    | GigabitEthernet0/22 |
| hv003-dell-r720-storage | GigabitEthernet0/24 |
| hv003-dell-r720-public  | GigabitEthernet0/26 |
+-------------------------+---------------------+
4 rows in set (0.01 sec)

All four of those choices should appear.  The only one to appear is 
DRAC-hv003-dell-r720

hv001, hv002, hv003 are all on the same device

**Comment by paulgear** [comment]
I sort-of reproduced this.  I started typing a port name which I know exists on my switch; it didn't find it first try, but when I backspaced over the last character and retyped it, it appeared.  Not sure what to make of that.

**Comment by digitalpilotnm** [comment]
Hi,  Tried that and it doesn't make any difference.  no matter what combo I
try it won't find all 4 interfaces
Anything I can do to help debug ??

**Comment by ekoyle** [comment]
I replaced typeahead.bundle.min.js with the version from https://github.com/corejavascript/typeahead.js and everything seems to be happier now...

It sounds like typeahead.js is no longer maintained: https://github.com/twitter/typeahead.js/issues/1424

**Comment by digitalpilotnm** [comment]
did you just grab that specific file and overright the older one with it ?
  or ??

**Comment by laf** [comment]
@digitalpilotnm we have a PR to fix this so hang fire :)

**Comment by digitalpilotnm** [comment]
Hi, just did a git pull and can confirm that this issue now appears to be
resolved.

Thank you
