### ISSUE TITLE
Wrong uptime

### ISSUE THREAD

**Issue by jarischaefer** [librenms/librenms#2686]
One of my boxes has 160 days of uptime, according to LibreNMS. Running uptime via SSH reports 527 days, though.

I have lots of other boxes with less than 300 days of uptime reporting properly.

The monitoring server runs LibreNMS 8aecf71 on Ubuntu 14.04. The target runs snmpd 5.4.3 on Debian 7.

**Comment by paulgear** [comment]
This happens when you restart snmpd without restarting the system.  LibreNMS is just reporting what Net-SNMP tells it.

**Comment by jarischaefer** [comment]
Turns out you're right. Manually snmpwalking clearly shows the wrong uptime. It seems to be caused by an unsigned 32 bit integer in SNMP. For anyone else stumbling upon this, uptime is stored as 1/100th of a second, which limits the total uptime to 2^32 - 1 divided by 86400 (= one day) divided by 100 (1/100th to seconds) = 497 days.
