### ISSUE TITLE
db devices.sysname string error

### ISSUE THREAD

**Issue by digitalpilotnm** [librenms/librenms#2689]
Current release.
When changing the hostname of a cisco device, the code does not update the database properly.

hostname blah01.router.city.planet
Old name in sql db  devices.sysname  = " blah01.router.bigCityName.planet"

change the hostname

hostname blah01.rtr.lax
new string in sql db devices.sysname = "blah01.rtr.laxbigCityName.planet"

If the new string is shorter, only length(new string) is replaced in the db.

**Comment by laf** [comment]
I'm not sure I understand your example.

**Comment by digitalpilotnm** [comment]
lets say the initial string is 50 chars in length.
one then changes the hostname on the device and that new string is only 20
chars long.

libre will store the new 20 chars and leave the remaining old 30 chars as
part of the data stored in the db.

so if you have an initial name of       blahblah-01-lax-rtr-rack-01
and then change it on the device to  new-rtr-01-lax

what will be in the database is
new-rtr-01-laxx-rtr-rack-01

"x-rtr-rack-01" is the latent OLD string that should have been removed when
the new string was stored.

**Comment by f0o** [comment]
Double check that it's not snmpd doing that.

On 4 January 2016 17:07:03 CET, digitalpilotnm <notifications@github.com> wrote:
>lets say the initial string is 50 chars in length.
>one then changes the hostname on the device and that new string is only
>20
>chars long.
>
>libre will store the new 20 chars and leave the remaining old 30 chars
>as
>part of the data stored in the db.
>
>so if you have an initial name of       blahblah-01-lax-rtr-rack-01
>and then change it on the device to  new-rtr-01-lax
>
>what will be in the database is
>new-rtr-01-laxx-rtr-rack-01
>
>"x-rtr-rack-01" is the latent OLD string that should have been removed
>when
>the new string was stored.
>
>On Mon, Jan 4, 2016 at 4:21 AM, Neil Lathwood
><notifications@github.com>
>wrote:
>
>> I'm not sure I understand your example.
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/librenms/librenms/issues/2689#issuecomment-168650937>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2689#issuecomment-168718375

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by digitalpilotnm** [comment]
Hi Daniel,
How do I send you a beer ? :)
Looks like the cisco is concat'ing domain-name and hostname to form sysName.
Thank you

**Comment by Rosiak** [comment]
Closing
