### ISSUE TITLE
Proposal to remove device_perf table + pages

### ISSUE THREAD

**Issue by laf** [librenms/librenms#2692]
MySQL isn't really designed to store this much data on large installs. I'm proposing we remove support for this.

**Comment by Rosiak** [comment]
I agree this causes issues on many install's, I rarely use this function, but I do think that we still need something like this. Perhaps leverage influx mby?

**Comment by f0o** [comment]
Or make it opt-in per device?

On 4 January 2016 17:25:42 CET, "Søren Rosiak" <notifications@github.com> wrote:
>I agree this causes issues on many install's, I rarely use this
>function, but I do think that we still need something like this.
>Perhaps leverage influx mby?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2692#issuecomment-168723573

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SaaldjorMike** [comment]
I'd say that as long as data is stored in MySQL, this should be off by default. Opt-in per device would be fine for me.

**Comment by SaaldjorMike** [comment]
On my install the device_perf table contains 1,1 GB out of the entire database size of 1,8 GB. Removing the table or leaving it as opt-in would for sure reduce the size quite a lot.

**Comment by ekoyle** [comment]
Can this data be accessed through the web UI?  If not, I agree that deleting it would be the best approach.  See also PR #2755 .  My device_perf table had grown to ~2.5GB since November, but it shrank to ~250 MB after fixing daily.php and setting $config['device_perf_purge'] = 7; (and waiting like 10 minutes for the script to finish).

**Comment by f0o** [comment]
Thanks @ekoyle for #2755 :)

**Comment by paulgear** [comment]
I personally would like to see this deprecated in favour of the ping-perf & poller-perf measurements.

**Comment by SaaldjorMike** [comment]
+1 to deprecating this

**Comment by masonke** [comment]
+1 to deprecation
