### ISSUE TITLE
Don't report ports down/errors when the device is down

### ISSUE THREAD

**Issue by paulgear** [librenms/librenms#27]
At the moment if a device goes down, it can result in port errors or ports down being displayed in addition to the device down.  The code should exclude down devices from any further alerts (like reboots, port errors, ports down, etc.).

**Comment by f0o** [comment]
Is this solved with the new alerting?

**Comment by laf** [comment]
Any more info on this issue or can we consider closing it down @paulgear

**Comment by paulgear** [comment]
@f0o This was never an alerting thing; it was just appearing in the event log.

**Comment by f0o** [comment]
Ah ok, this wasnt clear from the original issue text - gonna have a look at eventlogs

**Comment by laf** [comment]
Is this still occurring?

I've checked the eventlog for multiple devices I have that are down and the last and only eventlog message is about the device going down but no mention of ports.

**Comment by paulgear** [comment]
I'll have to have another look; please leave this open for now.  I'll add a label so you can exclude it from your list.

**Comment by laf** [comment]
Proposing to be closed.

**Comment by paulgear** [comment]
This is still a problem.  See attached screenshot - you can see the port that connects to my VoIP box down on the switch, and the VoIP box itself has a device down, then it also has two port downs on the VoIP box.  The last two should not be shown.
![screenshot from 2015-05-22 09 04 58](https://cloud.githubusercontent.com/assets/107222/7760731/acd22180-0061-11e5-8b5e-f4e9d6c5b02c.png)

**Comment by laf** [comment]
Much easier with the info :) #1106
