### ISSUE TITLE
HP/3Com MIB Updates

### ISSUE THREAD

**Issue by ve6mad** [librenms/librenms#2702]
Hi all, would it be possible to use the H3C MIBs for Comware OS devices? Looking in the os polling config (comware.inc.php), I see the line: 
$hardware = snmp_get($device, 'sysObjectID.0', '-OQsv', 'SNMPv2-MIB:HH3C-PRODUCT-ID-MIB', '+'.$config['install_dir'].'/mibs/h3c');
However, the h3c folder did not exist after the git clone install. I have added that folder and all the MIBs, and after running a rediscovery of the devices, I don't see any changes. I am looking in particularly for Fiber dBM and voltages. Those values are located in HH3C-ENTITY-EXT-MIB and HH3C-TRANSCEIVER-INFO-MIB. Am I missing something? My devices are HP 1910-24, HP 1920-24 and HP 5500 switches.
Thanks!

**Comment by Rosiak** [comment]
Is this still relevant?
