### ISSUE TITLE
Port name containing HTML Special Chars like < or >

### ISSUE THREAD

**Issue by Kliwer** [librenms/librenms#2703]
Hello. If port name contains html special char like < or > it is not shown correctly - it is used as HTML tag in the code. Using htmlspecialchars() fixes this. Please correct this.

**Comment by f0o** [comment]
Haha priceless.
Will take care of it asap

**Comment by f0o** [comment]
turns out it's a bit more complicated due to the bad codebase we inherited ...
Got it almost settled, just one thing keeps altering the ifLabel back for some reason

**Comment by Rosiak** [comment]
@f0o Able to finish the mentioned PR or?

**Comment by laf** [comment]
I've added two functions clean() and display() to clean input and display output - we can use display() here to deal with this now.

**Comment by Kliwer** [comment]
On version: 969b963 - Thu Dec 15 2016 09:23:25 GMT+0100 this problem still exists.

**Comment by laf** [comment]
Can you actually provide some more info on this, poller debugs, output from the device?

**Comment by Kliwer** [comment]
![libre](https://cloud.githubusercontent.com/assets/11368153/21266866/3088571e-c3a8-11e6-85d3-9a651ee534b8.png)
This is how it looks. "<pppoe-mlody>" is the interface name. 
I'll add debug and output later.

**Comment by genabi** [comment]
This is a potential XSS problem - SNMP response can be crafted to load an unwanted JS into browser
