### ISSUE TITLE
Choose title for graph widget

### ISSUE THREAD

**Issue by wiad** [librenms/librenms#2707]
As it is now, the title of the graph widget is set to "device / port / graph_type". It would be great if I could freely choose which attribute/attributes to use when setting the title for the widget, or even set a title myself. 

I would like to be able to make the title more descriptive, as the port name often does not reveal what the port is used for. So being able to choose for example "port_descr_type", or setting title manually, would make it easier to understand what the graphs in the widget is representing.

**Comment by Rosiak** [comment]
Merged #2884
