### ISSUE TITLE
Add Infoblox device

### ISSUE THREAD

**Issue by wiad** [librenms/librenms#2708]
The infoblox appliance is widely used as an enterprise-grade dns/dhcp/ipam service provider, would be great to have support in librenms for dhcp and dns statistics. MIBs are available from Infoblox.

**Comment by chrisgfx** [comment]
Hi,

If you look at the documentation, you have all the necessary information to implement that. ;-)

LibreNMS is an open project growing with individual contributions. :-)

**Comment by wiad** [comment]
Had a go at this, created pull request:

librenms/librenms#2801

**Comment by Rosiak** [comment]
Closing due to #2801
