### ISSUE TITLE
Notifications section doesn't seem to use base_path

### ISSUE THREAD

**Issue by adamboutcher** [librenms/librenms#2709]
The notifications buttons dont have the correct URL generated and seem to be using relative root i.e. / rather than the base_path variable from the config.

**Comment by SaaldjorMike** [comment]
@adamboutcher Can you provide a screenshot to show exactly what buttons you mean and what url they give you?

**Comment by adamboutcher** [comment]
If you run LibreNMS under a directory rather than a subdomain, the "Show Archives" button doesnt include the folder name and when you mark a notification as read it redirects to the wrong url i.e.

my libreNMS instance runs in monitoring.mydomain.tld/librenms/
but the links/url generated by the notifications page is monitoring.mydomain/tld/notifications instead of monitoring.mydomain.tld/librenms/notifications

The menu and footer links are fine.

I believe the edits are needed here...
/librenms/html/pages/notifcations.inc.php : Line 115
/librenms/html/pages/notifcations.inc.php : Line 167
/librenms/html/pages/notifcations.inc.php : Line 211
/librenms/html/pages/notifcations.inc.php : Line 230
