### ISSUE TITLE
Discover CDP Neighbors by IP

### ISSUE THREAD

**Issue by Snpbond** [librenms/librenms#2715]
CDP discovery is failing for me and it appears to be because it's attempting to discover by hostname and not IP.

```
discovering agnes-server-2960-4
name lookup of agnes-server-2960-4 failed
696, cdp, 0, agnes-server-2960-4, GigabitEthernet0/1, cisco WS-C2960-24TT-L, Cisco IOS Software, C2960 Software (C2960-
LANBASE-M), Version 12.2(35)SE5, RELEASE SOFTWARE (fc1)
```

I found on Line 58 of librenms/includes/discovery/discovery-protocols.inc.php it's attempting to add by cdpCacheDeviceId

Here is my CDP Array

```
(
            [cdpCacheAddressType] => ip
            [cdpCacheAddress] => 0A C1 D4 F9 
            [cdpCacheVersion] => Cisco IOS Software, C2960 Software (C2960-LANBASE-M), Version 12.2(35)SE5, RELEASE SOF
TWARE (fc1)
            [cdpCacheDeviceId] => agnes-server-2960-4
            [cdpCacheDevicePort] => GigabitEthernet0/1
            [cdpCachePlatform] => cisco WS-C2960-24TT-L
            [cdpCacheCapabilities] => 00 00 00 28 
            [cdpCacheVTPMgmtDomain] => 
            [cdpCacheNativeVLAN] => 1
            [cdpCacheDuplex] => fullduplex
            [cdpCacheLastChange] => 461:14:13:56.04
        )
```

The cdpCacheAddress converted from Hex is the switch IP, if I run the discover_new_device function with that converted IP then it seems to start crawling CDP Neighbors correctly. Would it be possible to have a config switch to discover based on CachedAddress instead of DeviceId?

**Comment by markuspachali** [comment]
Jep, you need a working DNS resolution (or /etc/hosts) for the hostname of the switch. Otherwise it will not work.

**Comment by paulgear** [comment]
It looks like this is currently a limitation of the CDP discovery code. We'll see what we can do about it.

**Comment by patrickfish** [comment]
Same issue here...unfortunately DNS is out of my control.

**Comment by laf** [comment]
pr merged
