### ISSUE TITLE
REST integration with LibreNMS and Oxidized Fails With SELinux

### ISSUE THREAD

**Issue by jharms** [librenms/librenms#2716]
Possible inclusion for the FAQ or doco relating to Oxidized/LibreNMS integration. Not a bug as such.

When the LibreNMS PHP scripts attempt to invoke the REST API with oxidized, it fails on RHEL/CENTOS. Based on debugging the PHP code within LibreNMS we had to:

1. Confirm PHP include files for LibreNMS are permitted to allow_url_fopen in php.ini (as well as generally)

2. Configure SELinux to permit outbound connections by the web server: 
setsebool -P httpd_can_network_connect 1

Once these settings were set, it worked as expected.

**Comment by laf** [comment]
I've created a PR to document checking allow_url_fopen.

We suggest to disabled SELinux so unless someone comes up with full docs on a working SELinux then we won't add in the one suggestion of adding this one config option for it.
