### ISSUE TITLE
install.php suggests the wrong install command for PEAR

### ISSUE THREAD

**Issue by nguillaumin** [librenms/librenms#2725]
Hi,

`install.php` doesn't detect PEAR on my system, but the suggested commands to install it are wrong and are referencing `mcrypt` instead, see screenshot:

![librenms-install](https://cloud.githubusercontent.com/assets/762512/12214435/ceeaa43a-b6e7-11e5-969c-7c0ee3ef6e2c.png)

**Comment by nguillaumin** [comment]
I'm on Arch Linux / PHP 7 by the way if that helps. Not sure why PEAR is not detected correctly, I'll raise a separate ticket if I find the cause.

**Comment by f0o** [comment]
You can install pear manually. And yes the command it suggests is wrong. We don't have a guide for arch. Feel free to help us out there.

**Comment by f0o** [comment]
Also php7 is not fully supported. I did some tests and fixed things i ran into but likely not all

**Comment by nguillaumin** [comment]
I fixed the pear issue (specific to my system), this bug report is more about the "comments" column being wrong by suggesting to install `mcrypt` to fix the pear issue.

I believe amending L. 234 on https://github.com/librenms/librenms/blob/master/html/install.php#L234 should fix it.
