### ISSUE TITLE
Device support: APC Netbotz 200 (NBRK0200). No sensors output realy nor switched outlets

### ISSUE THREAD

**Issue by NEO-AMiGA** [librenms/librenms#2732]
Hi there.

Libre doesn't recognise sensors connected to a Netbotz 200. It doesn't pick up on the output relay nor switched outlet either. Screenshot from APC*s interface and libre  attaced.

Pastebin of snmpwalk: http://pastebin.com/5L8pEY5U

<img width="763" alt="screen shot 2016-01-10 at 00 05 41" src="https://cloud.githubusercontent.com/assets/16628243/12218898/f1639d78-b72d-11e5-9e71-a41789785cf8.png">
<img width="767" alt="screen shot 2016-01-09 at 23 55 02" src="https://cloud.githubusercontent.com/assets/16628243/12218869/91da89b2-b72c-11e5-901e-2bd0ff2178fd.png">
<img width="1434" alt="screen shot 2016-01-10 at 00 05 48" src="https://cloud.githubusercontent.com/assets/16628243/12218897/f15c3e70-b72d-11e5-8d61-9bda3e030de4.png">

**Comment by tfra** [comment]
same problem here.. just installed LibreNMS today, so still an issue in latest version..

**Comment by tfra** [comment]
i have looked around a bit.. os: "netbotz" is defined in linux.inc.php, but the sysObjectId for my device does not match those defined in there. 

i created a new file "netbotz.inc.php" with the following content: 
```
<?php

if (!$os) {
     if (strstr($sysObjectId, '.1.3.6.1.4.1.5528.100.20.10.2014') || strstr($sysObjectId, '.1.3.6.1.4.1.5528.100.20.10.2016') || strstr($sysObjectId, '.1.3.6.1.4.1.318.1.3.8.4')) {
            $os = 'netbotz';
        }
}
```

rediscover device and it is now a "netbotz" instead of "apc". 

Next step: verify that temp etc is being grafed..

**Comment by tfra** [comment]
oids have changed from the original implementation of netbotz.. netbotz 200 uses other oids.. 

I have it working at my place now: 

Mods / additions: 
**/opt/librenms/html/images/os/netbotz200.png** (currently just a copy of netbotz.png)

**/opt/librenms/includes/definitions.inc.php**
```
$os = 'netbotz200';
$config['os'][$os]['text']             = 'Netbotz 200 Environment sensor';
$config['os'][$os]['type']             = 'environment';
$config['os'][$os]['icon']             = 'netbotz200';
$config['os'][$os]['over'][0]['graph'] = 'device_temperature';
$config['os'][$os]['over'][0]['text']  = 'Temperature';
$config['os'][$os]['over'][1]['graph'] = 'device_humidity';
$config['os'][$os]['over'][1]['text']  = 'Humidity';
```

**/opt/librenms/includes/discovery/os/netbotz200.inc.php**
```
<?php

if (!$os) {
     if (strstr($sysObjectId, '.1.3.6.1.4.1.318.1.3.8.4')) {
            $os = 'netbotz200';
        }
}
```

**/opt/librenms/includes/discovery/sensors/temperatures/netbotz200.inc.php**
```
<?php

if ($device['os'] == 'netbotz200') {
    $oids = snmp_walk($device, '1.3.6.1.4.1.318.1.1.10.3.13.1.1.2', '-Osqn', '');
    d_echo($oids."\n");

    $oids = trim($oids);
    if ($oids) {
        echo 'NetBotz 200 ';
        foreach (explode("\n", $oids) as $data) {
            list($oid,$descr) = explode(' ', $data, 2);
            $split_oid        = explode('.', $oid);
            $temperature_id   = $split_oid[(count($split_oid) - 1)];
            $temperature_oid  = ".1.3.6.1.4.1.318.1.1.10.3.13.1.1.3.$temperature_id";
            $temperature      = snmp_get($device, $temperature_oid, '-Ovq');
            $descr            = str_replace('"', '', $descr);
            $descr            = preg_replace('/Temperature  /', '', $descr);
            $descr            = trim($descr);
            if ($temperature != '0' && $temperature <= '1000') {
                discover_sensor($valid['sensor'], 'temperature', $device,
                    $temperature_oid, $temperature_id, 'netbotz200',
                    $descr, '1', '1', null, null, null, null, $temperature);
            }
        }
    }
}
```

**/opt/librenms/includes/discovery/sensors/humidity/netbotz200.inc.php**
```
<?php

if ($device['os'] == 'netbotz200') {
    $oids = snmp_walk($device, '1.3.6.1.4.1.318.1.1.10.3.13.1.1.2', '-Osqn', '');
    d_echo($oids."\n");

    $oids = trim($oids);
    if ($oids) {
        echo 'Netbotz 200 ';
        foreach (explode("\n", $oids) as $data) {
            list($oid,$descr) = explode(' ', $data, 2);
            $split_oid        = explode('.', $oid);
            $humidity_id      = $split_oid[(count($split_oid) - 1)];
            // tempHumidSensorHumidValue
            $humidity_oid = '.1.3.6.1.4.1.318.1.1.10.3.13.1.1.6.'.$humidity_id;
            $humidity     = snmp_get($device, "$humidity_oid", '-Ovq', '');
            $descr        = str_replace('"', '', $descr);
            $descr        = trim($descr);
            if ($humidity >= 0 && $descr <> "Err") {
                discover_sensor($valid['sensor'], 'humidity', $device,
                    $humidity_oid, $humidity_id, 'netbotz200',
                    $descr, '1', '1', null, null, null, null, $humidity);
            }
        }

        unset($data);
    }

    unset($oids);
}
```

**Comment by laf** [comment]
Please provide the output of: `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .`

**Comment by NEO-AMiGA** [comment]
netbotz01. Sensors connected to this one. 
netbotz02. Dry contact inputs configured
[netbotz02.txt](https://github.com/librenms/librenms/files/558196/netbotz02.txt)
[netbotz01.txt](https://github.com/librenms/librenms/files/558195/netbotz01.txt)
