### ISSUE TITLE
Device support: APC Smart-UPS VT 40 kVA missing sensors and in-proper data

### ISSUE THREAD

**Issue by NEO-AMiGA** [librenms/librenms#2733]
Hi there.

All sensors for the Smart-UPS VT 40 kVA doesn't show up after adding the device. Here's a raw paste from another nms of what I'd expect to monitor:

Output Status       onLine
Battery Replace (last 2001-04-01)       noBatteryNeedsReplacing
Diagnostics Results (last 2016-01-06)       ok

Temperature
Battery     20.4C

Voltage
Battery Actual Voltage      219V
Battery Nominal Voltage     192V
Bypass Phase 1      227V
Bypass Phase 2      230V
Bypass Phase 3      228V
Input 1 Phase 1     228V
Input 1 Phase 2     229V
Input 1 Phase 3     229V
Output Phase 1      230V
Output Phase 2      231V
Output Phase 3      231V

Current
Input 1 Phase 1     9.3A
Input 1 Phase 2     9A
Input 1 Phase 3     7.7A
Output Phase 1      8A
Output Phase 2      2A
Output Phase 3      16A

Frequency
Input 1     50Hz
Output      50Hz

Capacity
Battery Capacity        100%
Output Phase 1 Load     17%
Output Phase 2 Load     3%
Output Phase 3 Load     32%

Runtime
Battery Runtime Remaining

Pastebin of snmpwalk: http://pastebin.com/UizMXJen

Screenshot of current status in libre
<img width="1437" alt="screen shot 2016-01-10 at 00 11 32" src="https://cloud.githubusercontent.com/assets/16628243/12218919/cc56ec32-b72e-11e5-8b68-397e409a7b52.png">

**Comment by NEO-AMiGA** [comment]
snmpbulkwalk -OUneb -v2c -c public hostname .

[ups.txt](https://github.com/librenms/librenms/files/558207/ups.txt)

**Comment by laf** [comment]
Can you please test: #5558

**Comment by NEO-AMiGA** [comment]
Small note. Not showing near all sensors.

**Comment by laf** [comment]
Post in the pull request rather than here.

**Comment by laf** [comment]
Post in the pull request rather than here.

Oh and more info other than not showing near all sensors would help.

**Comment by kakopedreros** [comment]
Hi, i'm just read this post, i hace 2 APC Smart-UPS RT 10000 XL 3 Phase UPS.

What can i do for help in testing. Or just wait until this patch it is available?

**Comment by laf** [comment]
@kakopedreros https://github.com/librenms/librenms/issues/5558

**Comment by kakopedreros** [comment]
Done!

The UPS is a APC Smart-UPS RT 10000 XL 3 Phase UPS with 3-phase input and 1-phase output.

Doesn't shows the 3-phase input, or the 1-phase output.

I checkout the issue-5558 from the NerdBlender repository.

The SNMP walk is this:  http://pastebin.com/1WJeFF1J

And the this a screenshoot of the sensors:
<img width="1466" alt="captura de pantalla 2017-03-11 a las 20 12 12" src="https://cloud.githubusercontent.com/assets/4590300/23827668/1dbb4312-0697-11e7-8501-024e2cc5b211.png">

And this are a screenshoot of the resent events:

<img width="694" alt="captura de pantalla 2017-03-11 a las 20 13 26" src="https://cloud.githubusercontent.com/assets/4590300/23827673/3849a6d8-0697-11e7-9358-9ddb37a5cd3b.png">

**Comment by laf** [comment]
@kakopedreros You should post comments in the pull request.

**Comment by kakopedreros** [comment]
ok.

**Comment by kakopedreros** [comment]
removed. My bad.

**Comment by laf** [comment]
Merged in.
