### ISSUE TITLE
Device support: APC PDU AP8981. Not all items recoginsed and configured

### ISSUE THREAD

**Issue by NEO-AMiGA** [librenms/librenms#2735]
Hello

Not all sensors and what more for the APC AP8981 PDU's are recognised and configured. These PDU's can be connected in single mode and in chained mode. In chained mode up to 4 PDU's can share the same network uplink. I will attached two pastebins of snmpwalks of these puppies; one in single mode and one where a second unit is chained from the first.

The expected behaviour would be that all chained deviced shows up under the configured device and labeled with a Unit <n> prefix. 

One thing that would be cool would be to in some way see all outlets as well and properly named as in the snmp info. Sort of like ports or something. 

Here's a raw paste of what I see in another nms for a pdu that has a second unit chained to it:

Status Indicators
Unit 1 Power Supply 1       normal
Unit 1 Power Supply 2       normal
Unit 1 Power Supply Alarm       normal
Unit 2 Power Supply 1       normal
Unit 2 Power Supply 2       normal
Unit 2 Power Supply Alarm       normal

Voltage
Unit 1 Phase 1      232V
Unit 1 Phase 2      234V
Unit 1 Phase 3      232V
Unit 2 Phase 1      233V
Unit 2 Phase 2      234V
Unit 2 Phase 3      232V

Current
Unit 1 Phase 1      1.3A
Unit 1 Phase 2      0.9A
Unit 1 Phase 3      0A
Unit 2 Phase 1      3A
Unit 2 Phase 2      0A
Unit 2 Phase 3      0A

Power
Unit 1 Phase 1      280W
Unit 1 Phase 2      200W
Unit 1 Phase 3      0W
Unit 2 Phase 1      660W
Unit 2 Phase 2      0W
Unit 2 Phase 3      0W

Apparent power
Unit 1 Output       510VA
Unit 2 Output

snmpwalk of single unit: http://pastebin.com/ktBCM3UG
snmpwalk of two units chained: http://pastebin.com/863Vgu8w

Screenshot of what libre sees today
<img width="1417" alt="screen shot 2016-01-10 at 00 20 10" src="https://cloud.githubusercontent.com/assets/16628243/12218948/10d2a9ae-b730-11e5-9f12-029b999e6d14.png">

**Comment by laf** [comment]
If this isn't doing what you want now please provide the output of:

`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .`

**Comment by NEO-AMiGA** [comment]
Attached.

[r05pdu01.txt](https://github.com/librenms/librenms/files/558216/r05pdu01.txt)

**Comment by geordish** [comment]
Is this still a problem?

**Comment by NEO-AMiGA** [comment]
Yes. All I see now for the PDU's is one single Voltage input.

**Comment by laf** [comment]
Please update and see if the latest master fixes things for you.

**Comment by laf** [comment]
Feel free to reply once you've tested the latest master and we can re-open if this is not working for you.
