### ISSUE TITLE
Device support: HW-group Poseidon 3266. Not recognised

### ISSUE THREAD

**Issue by NEO-AMiGA** [librenms/librenms#2736]
Hello

The Poseidon 3266 isn't recognised, shows up as a generic device. Sadly I fail to do a proper snmpwalk of it that picks up all attached sensors. Another nms similar to libre picks them up though. HW-group have 3rd party info on their site:

http://www.hw-group.com/software/pd_snmp_en.html

Let me know if you need me to snmpwalk it and if so what's the proper command would be.

Screenshot from libre:
<img width="1418" alt="screen shot 2016-01-10 at 00 28 59" src="https://cloud.githubusercontent.com/assets/16628243/12219000/660ff074-b731-11e5-8cbc-884441c65212.png">

**Comment by Rosiak** [comment]
The output from this should be useable as a start:
```
snmpwalk -v2c -c COMMUNITY 192.168.15.101 .
```

**Comment by NEO-AMiGA** [comment]
Ah! Thanks man. I missed that "." at the end, it did wonders. =) 

snmpwalk: http://pastebin.com/rjLCDcY0

**Comment by Rosiak** [comment]
Perfect.
As far as I can read, the MIB needs to be downloaded from the device itself.
Can you help out with this part?

I'll look at it in the morning.

**Comment by NEO-AMiGA** [comment]
Ah, yes. SOrry... had that in mind but forgot. Attached. And here's OID's from the device:

Poseidon family SNMP OID description
----------------------------------------------------------------------------------------

Poseidon Device Values:
-------------------------------------------------------
.1.3.6.1.2.1.1.1.0	Device description (string)
.1.3.6.1.2.1.1.5.0	Device name (string)

Dry Contact Inputs
-------------------------------------------------------
.1.3.6.1.4.1.21796.3.3.1.1.2.1	Contact Input 1 state (integer, 1=Off, 2=On)
.1.3.6.1.4.1.21796.3.3.1.1.2.3	Contact Input 3 state (integer, 1=Off, 2=On)

.1.3.6.1.4.1.21796.3.3.1.1.3.1	Dry Contact Input 1 name (R/W string)
.1.3.6.1.4.1.21796.3.3.1.1.4.1	Dry Contact Input 1 Alarm state (integer)


Sensor
-------------------------------------------------------
.1.3.6.1.4.1.21796.3.3.3.1.6.1 	Sensor 1  current value *10 (integer)
.1.3.6.1.4.1.21796.3.3.3.1.6.2	Sensor 2  current value *10 (integer)
.1.3.6.1.4.1.21796.3.3.3.1.6.10	Sensor 10 current value *10 (integer)

.1.3.6.1.4.1.21796.3.3.3.1.2.1 	Sensor 1 name (R/W string)
.1.3.6.1.4.1.21796.3.3.3.1.2.2 	Sensor 2 name (R/W string)

.1.3.6.1.4.1.21796.3.3.3.1.4.1 	Sensor 1 state (integer, 0=Invalid, 1=Normal, 2=AlarmState, 3=Alarm)
.1.3.6.1.4.1.21796.3.3.3.1.5.1	Sensor 1 current value, units included (string)

.1.3.6.1.4.1.21796.3.3.3.1.8.1	Sensor 1 unique ID (integer)
.1.3.6.1.4.1.21796.3.3.3.1.9.1	Sensor 1 units (integer, 0=°C, 1=°F, 2=°K, 3=%, 4=V, 5=mA, 6=unknown, 7=pulse, 8=switch)


Outputs
-------------------------------------------------------
.1.3.6.1.4.1.21796.3.3.2.1.2.1	Output 1 state (R/W integer, 1=Off, 2=On)	
.1.3.6.1.4.1.21796.3.3.2.1.2.2	Output 2 state (R/W integer, 1=Off, 2=On)	

.1.3.6.1.4.1.21796.3.3.2.1.3.1	Output 1 name (R/W string)


For more details, analyze MIB file or check detailed device’s manual..
[poseidon.mib.zip](https://github.com/librenms/librenms/files/83887/poseidon.mib.zip)

**Comment by Rosiak** [comment]
Could you also supply a walk with the mib loaded? Thx.

**Comment by NEO-AMiGA** [comment]
Here you go: http://pastebin.com/mm9HcY1n

...i think? =) 

Cheers

**Comment by Rosiak** [comment]
Perfect, thanks
