### ISSUE TITLE
Device support: Synology rs2212+ and 812rp not properly configured

### ISSUE THREAD

**Issue by NEO-AMiGA** [librenms/librenms#2738]
Hello

Libre doesn't recognise and configure a Synology RS2212+ properly.

This particular unit also have an expansion chassis attached to it. The expected behaviour is to see all disks in main + expansion and graph health and temp of them. Status of all fans, memory, processors and such. 

Also have an 812rp+. There it finds some units but it doesn't store/save graphs for the disks and it feels icomplete. For that unit I couldn't snmpwalk, gives me oid error. Odd. Can send incomplete if ok.

snmpwalk: http://pastebin.com/66DBLeHr

Some of the info libre finds for the 2212+:
<img width="1417" alt="screen shot 2016-01-10 at 01 17 58" src="https://cloud.githubusercontent.com/assets/16628243/12219181/0dde7266-b738-11e5-965a-1265f5634e07.png">

The 812:
<img width="1429" alt="screen shot 2016-01-10 at 01 20 22" src="https://cloud.githubusercontent.com/assets/16628243/12219209/45c619c6-b739-11e5-9561-89f67c325c93.png">

**Comment by murrant** [comment]
Can you just `snmpwalk system` on the other device?
