### ISSUE TITLE
Some or all versions of CentOS devices are missing system graphs in web interface

### ISSUE THREAD

**Issue by Kivit** [librenms/librenms#2748]
Can confirm that CentOS 4.9 and CentOS 6.7 are missing graphs from web interface, but the graphs exist when using URL to manually visit them (Cannot confirm if newer CentOS versions have the same problem).
Graphs are missing from: **/device/device=2/tab=graphs/group=system/**
(the 'system' group is not available in web interface under CentOS machines).

Manually visiting these following URL's show the graphs:
Running Processes: 
/graphs/type=device_hr_processes/device=25/to=1452506400/from=1452420000/
Users Logged In: 
/graphs/type=device_hr_users/device=25/to=1452506400/from=1452420000/
Context Switches: 
/graphs/type=device_ucd_contexts/device=25/to=1452506400/from=1452420000/
Detailed Processor Usage: 
/graphs/type=device_ucd_cpu/device=25/to=1452506400/from=1452420000/
Interrupts: 
/graphs/type=device_ucd_interrupts/device=25/to=1452506400/from=1452420000/
System I/O Activity: 
/graphs/type=device_ucd_io/device=25/to=1452506400/from=1452420000/
Load Averages: 
/graphs/type=device_ucd_load/device=25/to=1452506700/from=1452420300/
Detailed Memory Usage: 
/graphs/type=device_ucd_memory/device=25/to=1452506700/from=1452420300/
Swap I/O Activity: 
/graphs/type=device_ucd_swap_io/device=2/to=1452506700/from=1452420300/
System Uptime: 
/graphs/type=device_uptime/device=25/to=1452506700/from=1452420300/

**Comment by markuspachali** [comment]
That does not look like a general problem with CentOS. I've checked some of our CentOS 6.7 and 7.2 systems and on all all graphs are displayed as expected.

**Comment by Kivit** [comment]
In that case, any information I can provide you to help me troubleshoot this?

**Comment by paulgear** [comment]
@Kivit A couple of questions: 1. If you go to /device/device=2/tab=graphs/, do you see a "System" section? 2. Is the LibreNMS/check_mk agent enabled on this system?

**Comment by Kivit** [comment]
1. That is exactly what I was trying to describe, I don't have "System" section. BUT all of the graphs that SHOULD be there, can be viewed directly visiting specific URL corresponding to that graph (ex: If I visit this URL directly (device=25 being my centos and device_ucd_load being avg. load):
/graphs/type=device_ucd_load/device=25/to=1452506700/from=1452420300/ 
then the graph is there and I can see all of the data).

2. No.


I Think my english is too poor to correctly describe my problem.

**Comment by paulgear** [comment]
@Kivit I think you've described the problem just fine, and I'll see if I can work out what's going on.  Could you please: 1) make sure you're running the latest version by manually running daily.sh, and 2) send us the output of ```bash
./poller.php -h HOSTNAME -d``` (please sanitise the output, as it contains potentially sensitive information such as IP addresses, MACs, and SNMP community strings).  If you're not comfortable to post it on a public pastebin, then please email it as an attachment to team@librenms.org.

**Comment by Kivit** [comment]
@paulgear
I've replaced sensitive information:
http://pastebin.com/Q0Fj5uqR

**Comment by Rosiak** [comment]
Status?
I could imagine this is due to snmpd.conf

**Comment by Rosiak** [comment]
@Kivit 
Any news?
