### ISSUE TITLE
Ubiquiti Airmax values - suggested fixed ranges

### ISSUE THREAD

**Issue by gr0mit1** [librenms/librenms#2749]
The airmax values currently auto-scale, generating in many cases strange graphs.

Here are my recommendations (based on my experience as a WISP operator) on what these ranges should be fixed to in order to be easier on the eye and to make trends more visible:

ubntRadioFreq.1          This value depends on freq band in use. Leave for the moment.
ubntRadioTxPower.1   0 dBm to 50 dBm
ubntRadioDistance.1   Leave auto-scaling.  Looks like this reports in metres.
ubntRadioRssi.1.1     ??   }  Best to have these on one graph with Chain 0 and Chain1 in different colours
ubntRadioRssi.1.2      ??  }
but not sure what the units are on these values !
ubntWlStatSignal.1   -20 dBm to -100 dBm
ubntWlStatRssi.1    ???  not sure quite what this value represents.
ubntWlStatCcq.1    0 to 100%
ubntWlStatNoiseFloor.1  -110 dBm to -50 dBm
ubntWlStatTxRate.1   0 to Max-value  } Best to have these on one graph with Tx and Rx in different colours
ubntWlStatRxRate.1 0 to Max-value   }
ubntWlStatStaCount.1 Leave to auto-scale.  Number of connected stations.
ubntAirMaxQuality.1   0 to 100%
ubntAirMaxCapacity.10 to 100%

![screenshot 2016-01-11 11 36 58](https://cloud.githubusercontent.com/assets/11898403/12232568/ae69c7ba-b857-11e5-8360-d40fb70055be.png)

Hope this is of help.  Others please feel free to chip in and expoint or correct anything!

**Comment by laf** [comment]
I have a branch for you to test (it's roughly upto date with our latest upstream), if you can test and report back that would be ace. Please note this only includes the changes to min/max. The ones where it needs to be two graphs into one needs to be a separate issue.

```bash
cd /opt/librenms
git remote add laf https://github.com/laf/librenms
git remote update laf
git checkout issue-2749
```

Give it a try, if it's right let me know. When you want to go back then do:

```bash
cd /opt/librenms
git checkout master
```

**Comment by gr0mit1** [comment]
Hi Neil
Thanks so much for this.

It looks very good actually!  I'm missing AirMax Capacity graphs though...

There is a question over Radio Overall RSSI which seems to report
postitive integers rather than dBm (which would be negative) so I need
to look into the Ubiquiti MIB in more detail.

If you want to take a look at the results let me know and I can give you
access.


Best Regards

Tim Robinson
TxRx Communications Ltd
+44 1256 810630
