### ISSUE TITLE
Issue: Fortigate processor information

### ISSUE THREAD

**Issue by asynet** [librenms/librenms#2751]
Since 29th December, when I upgraded LibreNMS just running the daily.sh script, I don't get information from the processors of my fortigates 200B, 1240B and 1000D v5.0 and v5.2. Previously I had this information. On the 60C's and 60D's I get this information.

**Comment by laf** [comment]
Please post the output of:

`./poller.php -h HOSTNAME -d -r -f -m processors`

**Comment by asynet** [comment]
xxxxx@GBR-DEV-NMS-001:/opt/librenms$ sudo ./poller.php -h edf-fw-mia-200b-1 -d -r -f -m processors
LibreNMS 2015.master Poller
Version info:
Commit SHA: d5cbb21c9e868163d1c1b5de6eb10b402a1a7737
DB Schema: 88
PHP: 5.6.14-0+deb8u1
MySQL: 5.5.46-0+deb8u1
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2.1

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'edf-fw-mia-200b-1' ORDER BY `device_id` ASC]
SQL[SELECT * FROM `devices` WHERE `device_id` = '104']
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '104'] edf-fw-mia-200b-1 104 fortigate

SQL[INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('3','3','0','104','117','112','104',NOW())] DEBUG: SNMP Auth options =  -v2c -c 24z3UrhW7qRJvBx
/usr/bin/snmpget -v2c -c 24z3UrhW7qRJvBx -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:edf-fw-mia-200b-1:161 sysObjectID.0
SNMPv2-SMI::enterprises.12356.101.1.2003


SQL[SELECT * FROM processors WHERE device_id = '104'] Processor Fortinet integrated CPU module (NPUs built into device)... DEBUG: SNMP Auth options =  -v2c -c 24z3UrhW7qRJvBx
/usr/bin/snmpget -v2c -c 24z3UrhW7qRJvBx -O Uqnv -m "" -M /opt/librenms/mibs udp:edf-fw-mia-200b-1:161 FORTINET-FORTIGATE-MIB::fgProcessorUsage.2
0

0%
[RRD Disabled]RRD[update /opt/librenms/rrd/edf-fw-mia-200b-1/processor-fortigate-fixed-0.rrd N:0]
SQL[UPDATE `processors` set `processor_usage` ='0' WHERE `processor_id` = '226'] [RRD Disabled]RRD[update /opt/librenms/rrd/edf-fw-mia-200b-1/poller-perf.rrd N:0.830] [RRD Disabled]RRD[update /opt/librenms/rrd/edf-fw-mia-200b-1/ping-perf.rrd N:112] [RRD Disabled]RRD[update /opt/librenms/rrd/edf-fw-mia-200b-1/ping-perf.rrd N:112] Polled in 0.830 seconds
Updating edf-fw-mia-200b-1
Array
(
    [last_ping] => Array
        (
            [0] => NOW()
        )

    [last_ping_timetaken] => 112
    [last_polled] => Array
        (
            [0] => NOW()
        )

    [last_polled_timetaken] => 0.830
)

SQL[UPDATE `devices` set `last_ping` =NOW(),`last_ping_timetaken` ='112',`last_polled` =NOW(),`last_polled_timetaken` ='0.830' WHERE `device_id` = '104'] UPDATED!

SQL[SELECT * FROM device_groups ORDER BY name]
SQL[SELECT alert_schedule.schedule_id FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '104' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1]
SQL[SELECT * FROM device_groups ORDER BY name]
SQL[SELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '104' ) || alert_map.target = '104'  )]  #1:
SQL[SELECT state FROM alerts WHERE rule_id = '1' && device_id = '104' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'devices' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM devices WHERE (devices.device_id = '104') && ( (  ( devices.status = 0  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  )  )  = "1")]  NOCHG  #2:
SQL[SELECT state FROM alerts WHERE rule_id = '2' && device_id = '104' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'devices' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM devices WHERE (devices.device_id = '104') && (devices.uptime < "300"  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  = "1")]  NOCHG  #3:
SQL[SELECT state FROM alerts WHERE rule_id = '3' && device_id = '104' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'bgpPeers' && COLUMN_NAME = 'device_id']
SQL[SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_NAME = 'devices' && COLUMN_NAME LIKE "%\_id"]
SQL[SELECT * FROM bgpPeers,devices WHERE (( devices.device_id = bgpPeers.device_id ) && bgpPeers.device_id = '104') && (bgpPeers.bgpPeerState != "established"  &&   (  ( devices.status = 1  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  )  )  = "1")]  NOCHG  #4:
SQL[SELECT state FROM alerts WHERE rule_id = '4' && device_id = '104' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'bgpPeers' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM bgpPeers WHERE (bgpPeers.device_id = '104') && (bgpPeers.bgpPeerFsmEstablishedTime < "300"  &&  bgpPeers.bgpPeerState = "established")]  NOCHG  #6:
SQL[SELECT state FROM alerts WHERE rule_id = '6' && device_id = '104' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'ports' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM ports WHERE (ports.device_id = '104') && ( (  (  ( ports.ifInOctets_rate * 8 )  / ports.ifSpeed )  * 100 )  >= "80")]  NOCHG  #7:
SQL[SELECT state FROM alerts WHERE rule_id = '7' && device_id = '104' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'sensors' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM sensors WHERE (sensors.device_id = '104') && (sensors.sensor_current > sensors.sensor_limit)]  NOCHG  #8:
SQL[SELECT state FROM alerts WHERE rule_id = '8' && device_id = '104' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'sensors' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM sensors WHERE (sensors.device_id = '104') && (sensors.sensor_current < sensors.sensor_limit_low)]  NOCHG

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','edf-fw-mia-200b-1','1453127259.5402','0.874','1','GBR-DEV-NMS-001\n')] ./poller.php edf-fw-mia-200b-1 2016-01-18 14:27:40 - 1 devices polled in 0.874 secs

MySQL: Cell[1/0s] Row[18/0.02s] Rows[10/0.01s] Column[0/0s] Update[2/0s] Insert[2/0s] Delete[0/0s]

**Comment by Rosiak** [comment]
Hmm - looks like it receives the information:
```
UPDATE processors set processor_usage ='0' WHERE processor_id = '226'
```

**Comment by SaaldjorMike** [comment]
@asynet Could you please try running `./validate.php` from within the /opt/librenms directory, then paste the output here.

**Comment by asynet** [comment]
xxx@GBR-DEV-NMS-001:/opt/librenms$ sudo ./validate.php
Version info:
Commit SHA: f170a1ab77f5d642ea8ce72fb53a9459176304f7
DB Schema: 100
PHP: 5.6.17-0+deb8u1
MySQL: 5.5.46-0+deb8u1
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2.1

[WARN]    You don't have $config["user"] set, this most likely needs to be set to librenms
[OK]      Database connection successful
[OK]      fping has been found

**Comment by thomasraabo** [comment]
i got  the same issue #2963

**Comment by Rosiak** [comment]
@rucarrol 
Have you seen this on any of your Fortigate devices?(I suppose not since, you are the one who changed the disco)

**Comment by laf** [comment]
Can someone having this issue explain what they are missing, the initial post looks like the graphs are there but no data is logged?

We also need (using something like dpaste.de) the output of:

./discovery.php -h HOSTNAME -d -m processors
./poller.php -h HOSTNAME -d -m processors -r -f

**Comment by thomasraabo** [comment]
There is no data on the graphs ... But the graphs are there.

Discovery: https://filedump.zitcom.dk/download/8449/cd50b7de87/fg-log-dis
Poller: https://filedump.zitcom.dk/download/8450/5a69df1705/fg-log-pol

**Comment by laf** [comment]
@rucarrol 

Can you take a look at this please, the code you contributed in Dec 2015 looks to be causing some issues for people. Looking at the discovery / polling debug and the updated code. It appears that in the for loop you are referencing the OID with incremental values upto the cpu count but the debug output shows the OID has a random number at the end rather than say 0 - 14.

**Comment by thomasraabo** [comment]
@laf 

Laf could we just not go back to working code?

**Comment by laf** [comment]
I'd like to give @rucarrol 24 more hours to look into otherwise yes we will.

**Comment by thomasraabo** [comment]
@laf 

Okay ...

**Comment by paulgear** [comment]
@laf @rucarrol Which commit/PR was that?

**Comment by laf** [comment]
https://github.com/librenms/librenms/pull/2613
