### ISSUE TITLE
MySQL Agent

### ISSUE THREAD

**Issue by Evaldnet** [librenms/librenms#2756]
I have an issue where the mysql agent says 
"The MySQL extension is not loaded"

I that I can see it's trying to use mysql when the system only have mysqli.

**Comment by ekoyle** [comment]
Look in config.php:
$config['db']['extension'] = 'mysqli';// mysql or mysqli

**Comment by f0o** [comment]
Hi we are planning on dropping support for those applications and push more the integration with munin-plugins.

Have a look at the upstream munin plugin repository and grab their MySQL monitoring script.

Cheers,
f0o

**Comment by masonke** [comment]
f0o,
Just for my own knowledge, why the switch?
~KEM

**Comment by f0o** [comment]
It's just a multitude of work involved in writing own application pollers and graphers when there is already a great simple product (munin) that has a lot of poller scripts available. Thus we already have support for arbitrary munin scripts.

**Comment by masonke** [comment]
Thank you, that makes total sense!
~KEM
