### ISSUE TITLE
Sending alerts to Flapjack - Improved documentation

### ISSUE THREAD

**Issue by compuguy** [librenms/librenms#2757]
I'm trying to tie in alerts generated to flapjack, but the documentation for the nagios compatible transport is limited (on both sides).

**Comment by f0o** [comment]
:+1: looking forward

**Comment by laf** [comment]
@compuguy Are you contributing the updates to the docs?

What is missing?

**Comment by compuguy** [comment]
@laf How to send alerts to a remote flapjack server (without running it on the same server as flapjack is on).

**Comment by laf** [comment]
Don't think that's possible, we do it through a local fifo file.

It flapjack as an API then another transport could be written.

**Comment by laf** [comment]
No further info provided.
