### ISSUE TITLE
Better detection UniFi Switches

### ISSUE THREAD

**Issue by adamboutcher** [librenms/librenms#2759]
Hi,

I know the UniFi Switch range is still new/developing and the SNMP output isn't complete, but could you write in some support to pull the model and FW (like the edge switch)

This is the OID where I can see an initial difference.
iso.3.6.1.2.1.1.1.0 = STRING: "USW-24P-250, 3.3.15.3976, Linux 3.6.5"

This seems to be in the structure of DEVICE MODEL, FIRMWARE, OS

There will be at least 4 models
USW-24P-250 = UniFi Switch 24port 250watt
USW-24P-500 = UniFi Switch 24port 500watt
USW-48P-500 = UniFi Switch 48port 500watt
USW-48P-750 = UniFi Switch 48port 750watt

and if rumours are correct there will be a 5th (guessing with this)
USW-8P-150 = UniFi Switch 8port 150watt

**Comment by laf** [comment]
We already try and get hardware and version out, can you provide the output of:

`./poller.php -h HOSTNAME -d -r -f -m os`

The oid: iso.3.6.1.2.1.1.1.0 is this from a specific mib.

**Comment by adamboutcher** [comment]
'''
LibreNMS 2015.master Poller
Version info:
Commit SHA: e380cc5100753e69e9e57dd6a2e3f93be3cdcdf2
DB Schema: 90
PHP: 5.6.14-0+deb8u1
MySQL: 10.0.22-MariaDB-0+deb8u1
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2.1

DEBUG!
Starting polling run:


SQL[[0;33mSELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'switch-us24-f0f.net.icfl.org' ORDER BY `device_id` ASC[0m] 
SQL[[0;33mSELECT * FROM `devices` WHERE `device_id` = '14'[0m] 
SQL[[0;33mSELECT * FROM devices_attribs WHERE `device_id` = '14'[0m] switch-us24-f0f.net.icfl.org 14 edgeswitch 

SQL[[0;33mINSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('3','3','0','1.15','1.24','1.18','14',NOW())[0m] DEBUG: SNMP Auth options =  -v1 -c icfl_net_J8y!
/usr/bin/snmpget -v1 -c icfl_net_J8y! -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:switch-us24-f0f.net.icfl.org:161 sysObjectID.0
SNMPv2-SMI::enterprises.4413

DEBUG: SNMP Auth options =  -v1 -c icfl_net_J8y!
/usr/bin/snmpget -v1 -c icfl_net_J8y! -OQnUs -m SNMPv2-MIB:HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs udp:switch-us24-f0f.net.icfl.org:161 sysUpTime.0 sysLocation.0 sysContact.0 sysName.0 sysDescr.0 sysObjectID.0
sysUpTime.0 = 10:0:29:10.00
sysLocation.0 = 
sysContact.0 = 
sysName.0 = switch-us24-f0fEDU-Comms
sysDescr.0 = USW-24P-250, 3.3.15.3976, Linux 3.6.5
sysObjectID.0 = enterprises.4413

DEBUG: SNMP Auth options =  -v1 -c icfl_net_J8y!
/usr/bin/snmpget -v1 -c icfl_net_J8y! -OQnUs -m HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs udp:switch-us24-f0f.net.icfl.org:161 snmpEngineTime.0 hrSystemUptime.0
snmpEngineTime.0 = 35774735

Using SNMP Agent Uptime (10:0:29:10.00)
hrSystemUptime or sysUpTime looks like to have rolled, using snmpEngineTime instead[[0;31mRRD Disabled[0m]RRD[[0;32mupdate /opt/librenms/rrd/switch-us24-f0f.net.icfl.org/uptime.rrd N:35774735[0m] Uptime: 1 years, 49 days, 1h 25m 35s

Hardware:  Version:  Features:  Serial: 
[[0;31mRRD Disabled[0m]RRD[[0;32mupdate /opt/librenms/rrd/switch-us24-f0f.net.icfl.org/poller-perf.rrd N:0.482[0m] [[0;31mRRD Disabled[0m]RRD[[0;32mupdate /opt/librenms/rrd/switch-us24-f0f.net.icfl.org/ping-perf.rrd N:1.18[0m] [[0;31mRRD Disabled[0m]RRD[[0;32mupdate /opt/librenms/rrd/switch-us24-f0f.net.icfl.org/ping-perf.rrd N:1.18[0m] Polled in 0.482 seconds
Updating switch-us24-f0f.net.icfl.org
Array
(
    [uptime] => 35774735
    [last_ping] => Array
        (
            [0] => NOW()
        )

    [last_ping_timetaken] => 1.18
    [last_polled] => Array
        (
            [0] => NOW()
        )

    [last_polled_timetaken] => 0.482
)

SQL[[0;33mUPDATE `devices` set `uptime` ='35774735',`last_ping` =NOW(),`last_ping_timetaken` ='1.18',`last_polled` =NOW(),`last_polled_timetaken` ='0.482' WHERE `device_id` = '14'[0m] UPDATED!

SQL[[0;33mSELECT * FROM device_groups ORDER BY name[0m] 
SQL[[0;33mSELECT alert_schedule.schedule_id FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '14' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1[0m] 
SQL[[0;33mSELECT * FROM device_groups ORDER BY name[0m] 
SQL[[0;33mSELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '14' ) || alert_map.target = '14'  )[0m] 

SQL[[0;33mINSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','switch-us24-f0f.net.icfl.org','1453114010.4003','0.508','1','lin-mon01p\n')[0m] ./poller.php switch-us24-f0f.net.icfl.org 2016-01-18 10:46:50 - 1 devices polled in 0.508 secs

MySQL: Cell[1/0s] Row[3/0s] Rows[4/0s] Column[0/0s] Update[1/0s] Insert[2/0s] Delete[0/0s]
'''

**Comment by murrant** [comment]
@adamboutcher is this resolved after updating?

**Comment by adamboutcher** [comment]
The UniFi Switch's now show their "platforms"  :-) Although they still show as EdgeSwitch under "Operating System"

**Comment by murrant** [comment]
@adamboutcher That is correct isn't it?  They are both the same base OS, just slightly different.

**Comment by adamboutcher** [comment]
The UniFi switches run Linux with part of the edge switch on top, there
isn't any direct access to the edge switch software so while technically
they share parts of the is, they are very different management wise.

**Comment by murrant** [comment]
@adamboutcher Yeah, but as far as SNMP is concerned they should act the same right?  The only reason to have separate OS's is if they needed to be handled differently.  (even then some could be done if there was minor differences)

We aren't really concerned with the management interface.

**Comment by adamboutcher** [comment]
No bother, just as they're developing the range of switches, things might
change in the future as well as the os not being the same overall.

Just seemed intuitive to have it as UniFi switch along with the APs being
UniFi.

But you do have a valid point and things can be changed in the future in
line with changes UBNT make.

Sent via my mobile.

**Comment by murrant** [comment]
@adamboutcher You can make a group to put them all together.

Thanks, closing.
