### ISSUE TITLE
When using Active Directory auth, the dashboards are empty

### ISSUE THREAD

**Issue by masonke** [librenms/librenms#2761]
AD 2012, Ubuntu 14.04, Librenms 8baf724 

When I change from mysql to ad for authentication, none of the dashboard widgets have data in them. Everyone is allowed to login, with a specific group having level 10 access. This group is a nested group, so not sure if that matters.
Also tried a group that I am a direct member of, with no difference. 
Also 
Anyone have an Idea on what I am doing wrong?  

Here are the config bits. 

$config['auth_mechanism'] = "mysql"; 
$config['auth_mechanism'] = "active_directory"; 

$config['auth_ad_url'] = "ldaps://wndusdc01.mycompany.net";
$config['auth_ad_check_certificates'] = 0; // or 0
$config['auth_ad_domain'] = "mycompany.net";
$config['auth_ad_base_dn'] = "dc=mycompany,dc=net";
#$config['auth_ad_groups']['Domain Admins']['level'] = 10;
$config['auth_ad_groups']['Tech Ops Infrastructure']['level'] = 10;
$config['auth_ad_require_groupmembership'] = 0;

**Comment by laf** [comment]
This will be because we no longer have users stored in mysql so we can't provide the user id's needed for all of the dashboard stuff.

When I did the Radius auth module I made sure that worked, we can back port that to the AD auth module as well I should think.

**Comment by masonke** [comment]
Ah, that makes sense. In that case,i will use the Radius method, we have ACS tied into AD
~KEM

**Comment by vizay** [comment]
@laf I added a patch to the AD auth in november that specifically checks if the user exists in the db, and if not, adds a "dummy" user just for cases like getting the dashboard working amongst other things.

Has something changed since then that breaks this?

**Comment by laf** [comment]
@vizay I'm not sure but I've updated the authentication module to support it a little better including purging old / unused users.

**Comment by masonke** [comment]
You folks rock!  Will test this tomorrow when i am in the office
~KEM

**Comment by laf** [comment]
@masonke it's not merged yet.

**Comment by masonke** [comment]
Ah, ok


~KEM
