### ISSUE TITLE
Alerts for port flaps are far too verbose with Mellanox switches

### ISSUE THREAD

**Issue by ernstae** [librenms/librenms#2769]
Greetings,

We've been using LibreNMS with Mellanox switches for a while, and are having good results.  However, the alerting does seem to have some issues.
When one port on a switch flaps, we get an alert with _all_ of the ports.
This seems less helpful than it could (limiting to the specific port that flaps).

```
LibreNMS BOT [2:21 PM] 
Alert for device ib-switch - Port status up/down got worse
Severity: critical
Timestamp: 2016-01-14 14:16:01
Unique-ID: 859
Rule: Port status up/down
Faults:
 #1: port_id => 2782; ifDescr => mgmt1; 
 #2: port_id => 2784; ifDescr => IB1/20; 
 #3: port_id => 2785; ifDescr => IB1/19; 
 #4: port_id => 2786; ifDescr => IB1/21; 
 #5: port_id => 2787; ifDescr => IB1/24; 
 #6: port_id => 2788; ifDescr => IB1/23; 
 #7: port_id => 2789; ifDescr => IB1/22; 
 #8: port_id => 2790; ifDescr => IB1/26; 
 #9: port_id => 2791; ifDescr => IB1/25; 
 #10: port_id => 2792; ifDescr => IB1/27; 
 #11: port_id => 2795; ifDescr => IB1/33; 
 #12: port_id => 2796; ifDescr => IB1/32; 
 #13: port_id => 2797; ifDescr => IB1/31; 
 #14: port_id => 2798; ifDescr => IB1/34; 
 #15: port_id => 2799; ifDescr => IB1/30; 
 #16: port_id => 2800; ifDescr => IB1/29; 
 #17: port_id => 2801; ifDescr => IB1/28; 
 #18: port_id => 2809; ifDescr => IB1/11; 
 #19: port_id => 2811; ifDescr => IB1/2; 
 #20: port_id => 2812; ifDescr => IB1/1; 
 #21: port_id => 2813; ifDescr => IB1/3; 
 #22: port_id => 2814; ifDescr => IB1/6; 
 #23: port_id => 2815; ifDescr => IB1/5; 
 #24: port_id => 2816; ifDescr => IB1/4; 
 #25: port_id => 2817; ifDescr => IB1/8; 
 #26: port_id => 2818; ifDescr => IB1/7; 
Alert sent to: NOC <>

LibreNMS BOT [2:27 PM] 
Alert for device ib-switch- Port status up/down got better
Severity: critical
Timestamp: 2016-01-14 14:22:02
Unique-ID: 860
Rule: Port status up/down
Faults:
 #1: port_id => 2782; ifDescr => mgmt1; 
 #2: port_id => 2784; ifDescr => IB1/20; 
 #3: port_id => 2785; ifDescr => IB1/19; 
 #4: port_id => 2786; ifDescr => IB1/21; 
 #5: port_id => 2787; ifDescr => IB1/24; 
 #6: port_id => 2788; ifDescr => IB1/23; 
 #7: port_id => 2789; ifDescr => IB1/22; 
 #8: port_id => 2790; ifDescr => IB1/26; 
 #9: port_id => 2791; ifDescr => IB1/25; 
 #10: port_id => 2792; ifDescr => IB1/27; 
 #11: port_id => 2795; ifDescr => IB1/33; 
 #12: port_id => 2796; ifDescr => IB1/32; 
 #13: port_id => 2797; ifDescr => IB1/31; 
 #14: port_id => 2798; ifDescr => IB1/34; 
 #15: port_id => 2799; ifDescr => IB1/30; 
 #16: port_id => 2800; ifDescr => IB1/29; 
 #17: port_id => 2801; ifDescr => IB1/28; 
 #18: port_id => 2811; ifDescr => IB1/2; 
 #19: port_id => 2812; ifDescr => IB1/1; 
 #20: port_id => 2813; ifDescr => IB1/3; 
 #21: port_id => 2814; ifDescr => IB1/6; 
 #22: port_id => 2815; ifDescr => IB1/5; 
 #23: port_id => 2816; ifDescr => IB1/4; 
 #24: port_id => 2817; ifDescr => IB1/8; 
 #25: port_id => 2818; ifDescr => IB1/7; 
Alert sent to: NOC <>
```

**Comment by f0o** [comment]
`Port status up/down got worse` based on that information i guess all of those ports are down as it's a follow-up alert for an existing incident.

Anyways, you can and should define your own alert template anyways. The default template is a famous one-size-fit-all approach which likely doesn't fit in all situations.

**Comment by laf** [comment]
Also worth checking the eventlog for that device, it may be that we are seeing the ports as down due to bad snmp response.

**Comment by laf** [comment]
Any feedback @ernstae?

**Comment by f0o** [comment]
I still dont see the issue.
Based on his 2 pastes I can only conclude this situation:

* device has an ongoing incident about N ports being down
* paste1 shows the same incident going worse, meaning N+1 ports are now down. Still the same alert, condition just worsens.
* paste2 shows yet again the same incident however it got better, meaning N-1 ports are now down.

This is all still 1 single incident/alert. If it includes porta meant to be down you must ignore them or exclude them manually from your rule.

That being said, I dont see a bug here.

Correct me if I'm wrong :)

**Comment by ernstae** [comment]
@f0o and @laf 

The issue was that when *one* port goes down, I get alerts that are showing me as though *all* ports go down. 
This seems to happen on Mellanox equipment, because my Juniper gear reports as expected.

For instance, today, I rebooted one server, and got this:

`
LibreNMS BOT [3:11 PM] 
Alert for device sx1036 - Port status up/down got worse
Severity: warning
Timestamp: 2016-01-27 15:06:01
Unique-ID: 942
Rule: Port status up/down
Faults:
 #1: port_id => 672; ifDescr => mgmt1; 
 #2: port_id => 673; ifDescr => Eth1/9/1; 
 #3: port_id => 674; ifDescr => Eth1/9/2; 
 #4: port_id => 677; ifDescr => Eth1/11; 
 #5: port_id => 678; ifDescr => Eth1/14; 
 #6: port_id => 679; ifDescr => Eth1/13; 
 #7: port_id => 681; ifDescr => Eth1/15; 
 #8: port_id => 682; ifDescr => Eth1/18; 
 #9: port_id => 688; ifDescr => Eth1/26; 
 #10: port_id => 691; ifDescr => Eth1/23/3; 
 #11: port_id => 692; ifDescr => Eth1/23/4; 
 #12: port_id => 693; ifDescr => Eth1/21; 
 #13: port_id => 694; ifDescr => Eth1/22; 
 #14: port_id => 695; ifDescr => Eth1/19; 
 #15: port_id => 696; ifDescr => Eth1/20; 
 #16: port_id => 697; ifDescr => Eth1/10/1; 
 #17: port_id => 698; ifDescr => Eth1/10/2; 
 #18: port_id => 699; ifDescr => Eth1/10/3; 
 #19: port_id => 700; ifDescr => Eth1/10/4; 
 #20: port_id => 701; ifDescr => Eth1/8; 
 #21: port_id => 703; ifDescr => Eth1/6; 
 #22: port_id => 708; ifDescr => Eth1/27/1; 
 #23: port_id => 711; ifDescr => Eth1/27/4; 
 #24: port_id => 713; ifDescr => Eth1/32; 
 #25: port_id => 714; ifDescr => Eth1/31; 
 #26: port_id => 715; ifDescr => Eth1/34; 
 #27: port_id => 716; ifDescr => Eth1/33; 
Alert sent to: NOC <>`

followed by a repeat of the same message with the only change being _"s|worse|better|g"_

I can attempt to build my own template, but suspect that this is being reported in the _faults_ array, since the default template is likely just the same thing -- foreach faults -- print something.

**Comment by laf** [comment]
As per previous comment: Also worth checking the eventlog for that device, it may be that we are seeing the ports as down due to bad snmp response.

**Comment by laf** [comment]
No further info provided.
