### ISSUE TITLE
I want to give "AcceptedPrefixes_delta"

### ISSUE THREAD

**Issue by kaoru290** [librenms/librenms#2770]
I will using for BGP alerting.
Do you have any ideas?

mysql> show columns from bgpPeers_cbgp;
+----------------------+-------------+------+-----+---------+-------+
| Field                | Type        | Null | Key | Default | Extra |
+----------------------+-------------+------+-----+---------+-------+
| device_id            | int(11)     | NO   | PRI | NULL    |       |
| bgpPeerIdentifier    | varchar(64) | NO   | PRI | NULL    |       |
| afi                  | varchar(16) | NO   | PRI | NULL    |       |
| safi                 | varchar(16) | NO   | PRI | NULL    |       |
| AcceptedPrefixes     | int(11)     | NO   |     | NULL    |       |
| DeniedPrefixes       | int(11)     | NO   |     | NULL    |       |
| PrefixAdminLimit     | int(11)     | NO   |     | NULL    |       |
| PrefixThreshold      | int(11)     | NO   |     | NULL    |       |
| PrefixClearThreshold | int(11)     | NO   |     | NULL    |       |
| AdvertisedPrefixes   | int(11)     | NO   |     | NULL    |       |
| SuppressedPrefixes   | int(11)     | NO   |     | NULL    |       |
| WithdrawnPrefixes    | int(11)     | NO   |     | NULL    |       |
+----------------------+-------------+------+-----+---------+-------+

**Comment by laf** [comment]
Sorry can you provide more information on what you mean?

**Comment by kaoru290** [comment]
@laf 
It is "My BGP Router :: BGP :: :: Prefixes_ipv4unicast"
![2582242-905949876907c9e4f742057864261508a84a484f](https://cloud.githubusercontent.com/assets/6907084/12381354/d1ea5c30-bdcb-11e5-8244-6ef94d7c27a4.png)

I want to alerting with "Prefix +100 or -100"
regards.

**Comment by laf** [comment]
You don't need a delta for that, AcceptedPrefixes in the bgpPeers_cbgp table is the value shown in the graph so you just need to create a rule which checks that table and then alerts based on being over or under a threshold.

**Comment by ekoyle** [comment]
If I understand correctly, @kaorukit wants an alert if the number of
prefixes increases or decreases by more than a certain amount (+/-100) from
the previous poll.

Is bgpPeers_cbgp.AcceptedPrefixes the total number of accepted prefixes or
the number accepted/removed since the last poll?

**Comment by laf** [comment]
@kaoru290 is this what you need?

AcceptedPrefixes is the total number of accepted prefixes at the time we polled

**Comment by kaoru290** [comment]
Sorry about the delay.

@ekoyle rights.
I want to give the bgpPeers_cbgp.AcceptedPrefixes and previous poll value.

**Comment by kaoru290** [comment]
thank you!
I will attempt it!
