### ISSUE TITLE
Enterasys N3 Switch is recognised as a generic device

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#2771]
I added a Enterasys N3 switch on LibreNMS and it got recognised as a Generic device. Here is the debug output.

sudo php discovery.php -h 10.10.4.4 -d -m os  
LibreNMS 2015.master Discovery
commit c1380935cfe28c51c5d5977fbcddcb4f10144cec

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
SQL[SELECT revision FROM `dbSchema`] DB Schema already up to date.

SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE '10.10.4.4' ORDER BY device_id DESC] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '95'] 10.10.4.4 95 enterasys 
OS: DEBUG: SNMP Auth options =  -v2c -c xxxxx
/usr/bin/snmpget -v2c -c xxxxx -Ovq -M /opt/librenms/mibs udp:10.10.4.4:161 SNMPv2-MIB::sysDescr.0
Enterasys Networks, Inc. N3 Chassis Rev 07.62.01.0007 02/28/2012--11:59 ofc

DEBUG: SNMP Auth options =  -v2c -c xxxxx
/usr/bin/snmpget -v2c -c xxxxx -Ovqn -M /opt/librenms/mibs udp:10.10.4.4:161 SNMPv2-MIB::sysObjectID.0
.1.3.6.1.4.1.5624.2.1.53

| Enterasys Networks, Inc. N3 Chassis Rev 07.62.01.0007 02/28/2012--11:59 ofc | .1.3.6.1.4.1.5624.2.1.53 | DEBUG: SNMP Auth options =  -v2c -c xxxxx
/usr/bin/snmpget -v2c -c xxxxx -Osqnv -M /opt/librenms/mibs udp:10.10.4.4:161 ENTITY-MIB::entPhysicalMfgName.1
No Such Instance currently exists at this OID

DEBUG: SNMP Auth options =  -v2c -c xxxxx
/usr/bin/snmpget -v2c -c xxxxx -Oqv -M /opt/librenms/mibs udp:10.10.4.4:161 1.3.6.1.4.1.674.10895.3000.1.2.100.1.0
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c xxxxx
/usr/bin/snmpget -v2c -c xxxxx -Oqv -M /opt/librenms/mibs udp:10.10.4.4:161 SML-MIB::product-Name.0
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c xxxxx
/usr/bin/snmpget -v2c -c xxxxx -Oqvn -M /opt/librenms/mibs udp:10.10.4.4:161 ENTITY-MIB::entPhysicalDescr.1
No Such Instance currently exists at this OID

SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='network',`last_discovered_timetaken` ='1.364' WHERE `device_id` = '95'] Discovered in 1.364 seconds

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','10.10.4.4','1452850939.216','1.405','1')] discovery.php 10.10.4.4 2016-01-15 11:42:20 - 1 devices discovered in 1.405 secs
MySQL: Cell[1/0s] Row[1/0s] Rows[1/0s] Column[0/0s] Update[1/0.03s] Insert[1/0.03s] Delete[0/0s]

**Comment by breeman1** [comment]
Just thought I should show what the screen looks like.
![image](https://cloud.githubusercontent.com/assets/16717388/12351214/b92a70fc-bb84-11e5-97ef-7b58ecaa0a77.png)

**Comment by laf** [comment]
That's been detected as an Enterasys device, what is it you are missing?

**Comment by breeman1** [comment]
You are right, I guess I was impatiently waiting for it to disappear from the Generic Tab under Devices where it was stuck for some reason. What is interesting though is that this device platform; being the N3 switch, also suffers from the poller getting stuck at the "ports" module. Should I open another issue for that?
[N3_Switch.txt](https://github.com/librenms/librenms/files/94595/N3_Switch.txt)

**Comment by laf** [comment]
Should also be fixed now with latest merge.
