### ISSUE TITLE
Remove Sensitive Information from poller.php log file

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#2778]
Hi,

Just thinking it makes sense to capture this - given some IRC chat and debugging from this week. It would be nice to have the sensitive / private information from the poller.php log file removed ... or really, not placed there to start with (i.e. self-sanitize before writing to the log). Just makes sharing log files easier / smoother.

I don't think there is any sensitive information in the discovery.php log file, but the same thought would apply there.

Thanks!

**Comment by paulgear** [comment]
:+1: I've been meaning to try this for some time; I've got two ideas so far: 1) a flag which we can set on polling & discovery which tells it to anonymise; this would likely be more effort to implement, but would be able to be more intelligent. 2) A program which filters the output from discovery/polling and just replaces known strings with equivalent known strings.

Both solutions would need to know about specific things that we'd like anonymised, like IP addresses, MAC addresses, SNMP community strings, etc.  And I can see them failing (e.g. when MAC addresses are decimal encoded in OIDs), but at least it would be something...

**Comment by arrmo** [comment]
Yep, makes complete sense. Wondering if there is an easier way (to start at least). It seems like most (?) of the information is in the SQL commands -> keep the info in the real access, but remove it in the log output?

Just a thought.
