### ISSUE TITLE
Ability to Un-Register MIBs

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#2779]
Hi,

When working through custom MIBs, it can definitely be the case that some items get added that are not really desired in the end (particularly sub-items). It would be great to have a function to un-register / remove MIBs, just like MIBs can be registered.

Perhaps there is a way to do this already?

Thanks!

**Comment by paulgear** [comment]
There's no way to do this at present.  It was in my mind to add it, but I can't promise any timeframe.

**Comment by arrmo** [comment]
NP, makes sense. Perhaps capture in the documentation what needs to be done (i.e. the 3 tables that need to be removed, and then sq085.sql to be run)?

Thanks!

**Comment by paulgear** [comment]
@arrmo You shouldn't remove the tables; the following should be sufficient to clear out all your MIB settings:
```SQL
delete from `mibdefs`;
delete from `device_mibs`;
delete from `device_oids`;
delete from `graph_types` where `graph_section` = 'mib';
```

**Comment by arrmo** [comment]
Makes sense - thanks!

**Comment by f0o** [comment]
Can this be closed then?

**Comment by arrmo** [comment]
Yep - closing it. Thanks!
