### ISSUE TITLE
Custom MIBs Not Showing up in MIB Associations

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#2780]
Hi,

Posting this to make sure it's captured, though it may be as designed. I have some custom MIBs working, and I now see the graphs (patch from Paul - thanks!). But these custom items do not show up in MIB associations (which I assume they should?).

Thanks!

**Comment by paulgear** [comment]
@arrmo I think we'll need to have another look at your tables to work this out.

**Comment by arrmo** [comment]
Sure, NP! Funny thing is, I deleted those three tables, to see if that would clean things up. Updated to the latest code (git pull) ... ran discovery and poller -> and I can't get the tables to recreate now. Yep, likely me ... ;-).

Thanks!

**Comment by arrmo** [comment]
OK, got the tables all working again - fat finger on my side. But a few oddities,
- MIB associations is blank, even though there are MIB graphs. This shouldn't be the case, should it?
- I have data that is a table (i.e. two temperature entries, MB and CPU) ... but they are being plotted together somehow.

Thanks!

**Comment by arrmo** [comment]
FYI, also - after the latest updates ... MIB graphs do not seem to be refreshing / updating. Just letting you know, will also dig here to see if i can help figure it out!

Thanks.

**Comment by paulgear** [comment]
@arrmo If you want me to see what's going on, please email me the output from:
```SQL
select * from `mibdefs`;
select * from `device_mibs`;
select * from `device_oids`;
select * from `graph_types` where `graph_section` = 'mib';
```

**Comment by arrmo** [comment]
Sure! On it's way ... ;-).

Thanks!

BTW, I do plan to dig into the code a bit as well, see if I can help here. Folks are extremely helpful here, want to try to do what I can.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
