### ISSUE TITLE
Process (Custom) SNMP Data in poller file (custom.inc.php)

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#2782]
Hi,

Perhaps a future feature, but it would be nice to be able to process the SNMP data in the (os?) custom inc.php file - perhaps some data shaping / modification between when the SNMP data is retrieved, and when it is stored to the database.

Just a thought.

Thanks!

**Comment by Rosiak** [comment]
Hi,

We are cleaning up the issues here on GitHub, all feature requests will be moved to:
https://community.librenms.org/c/feature-requests

Hence the closure of this issue.
