### ISSUE TITLE
Make date formatting consistent

### ISSUE THREAD

**Issue by paulgear** [librenms/librenms#279]
Date formatting in the codebase is completely ad-hoc.  Need to add some config options and use them consistently.

**Comment by laf** [comment]
Can we confirm where we want to use this?

Reason I ask is things like the billing section and the graphs use date() in varying different ways so we would end up with quite a large number of config options which are basically just imitating exactly what date() does.

Checking each of the new config options from the Pr associated with this shows:

Y-m-d H:i:s - used in 3 3rd party modules now and that's it. Updating them to use our config options isn't really realistic is it?

H:i:s - This isn't used anywhere at the moment.

If this is to display in the WebUI then does it not make more sense to use the date as we store it in MySQL?

**Comment by paulgear** [comment]
I haven't looked at exactly how we store the dates in MySQL, but I would hope it's in a format-independent form.  Agreed updating 3rd party code isn't a great idea, but I think we should strive to be as consistent as possible and use as few different formats as possible.

**Comment by laf** [comment]
It's not 100% consistent iirc. Most use yyyy-mm-dd hh:mm:ss but I think I've seen at least one table that doesn't follow this but can't remember 100%.

Let's agree on a format we display to the users:

Eventlog: 19th Apr 2015 00:33:04
Alerts: 2015-05-17 03:23:00

I'd probably say follow the alerts, it's how it's stored in the DB and doesn't require any post processing.

Eventlog looks nice.....

@f0o / @paulgear

**Comment by f0o** [comment]
I'm for numeric date/time representations

**Comment by paulgear** [comment]
Obligatory reference: https://xkcd.com/1179/

Honestly, is there *any* reason at all not to use Y-m-d H:i:s everywhere?

**Comment by laf** [comment]
@paulgear if #1110 is ok then would be good to close this :)

**Comment by laf** [comment]
Bump.
