### ISSUE TITLE
Bills not reading deltas from Cisco switch

### ISSUE THREAD

**Issue by chopkins84** [librenms/librenms#2799]
For the last couple of days, the bills we have for ports on Cisco switches have been logging the total bandwidth on the interface, rather than the delta since the previous snapshot(which is currently zero). This has resulted in bills of 50Gbps+ being logged, even though the graphs for the interfaces are recording the correct bandwidths. Running version 2728bca

**Comment by laf** [comment]
So you've not updated in that time then so that rules out changes in the code. Any changes to MySQL, strict mode?

Can you run ./validate.php and check the output.

**Comment by chopkins84** [comment]
Here's the output:

[OK]      config.php tested ok
[FAIL]    We have found some files that are owned by a different user than librenms, this will stop you updating automatically and / or rrd files being updated causing graphs to fail:

(big list of files here)

[OK]      Database connection successful
[FAIL]    Your Innodb buffer size is not big enough...
InnoDB Buffersize too small.
Current size: 128 MiB
Minimum Required: 180.25 MiB
To ensure integrity, we're not going to pull any updates until the buffersize has been adjusted.
Config proposal: "innodb_buffer_pool_size = 256M"
[OK]      fping has been found

**Comment by chopkins84** [comment]
No changes to mysql in weeks

**Comment by laf** [comment]
You could do with resolving the the innodb_buffer_pool_size.

Is this happening for all bills and all ports and on the ones it's happening on is it doing it all the time?

**Comment by chopkins84** [comment]
Okay, I've repaired the pool size

We have a couple of bills set up - one is a combination of several Brocade ports, and one several Cisco ports. It's doing it on two of the four Cisco ports it seems. 

The output for one of them is

            [ifInOctets] => 1759426597250
            [ifInOctets_prev] => 1759426597250
            [ifInOctets_delta] => 0
            [ifInOctets_rate] => 0
            [ifOutOctets] => 20389559591669
            [ifOutOctets_prev] => 20389559564427
            [ifOutOctets_delta] => 27242
            [ifOutOctets_rate] => 90

but what I'm seeing in the DB are

  bill_id: 3
timestamp: 2016-01-18 11:05:04
   period: 225
    delta: 1759426597378
 in_delta: 1759426597250
out_delta: 128

**Comment by laf** [comment]
Do you get that high a delta all the time though or is it only occasionally?

**Comment by chopkins84** [comment]
|       3 | 2016-01-12 22:05:05 |    300 |            192 |             0 |            192 |
|       3 | 2016-01-12 22:10:05 |    301 |            256 |             0 |            256 |
|       3 | 2016-01-12 22:16:42 |    422 |            256 |             0 |            256 |
|       3 | 2016-01-12 22:20:53 |    256 | 22148944101101 | 1759426597250 | 20389517503851 |
|       3 | 2016-01-12 22:26:43 |    375 | 22148944101101 | 1759426597250 | 20389517503851 |
|       3 | 2016-01-12 22:30:05 |    203 |  1759426597747 | 1759426597250 |            497 |
|       3 | 2016-01-12 22:35:05 |    301 |  1759426597811 | 1759426597250 |            561 |
|       3 | 2016-01-12 22:40:06 |    301 |  1759426597378 | 1759426597250 |            128 |

It started then and hasn't gone back down. We did maintenance on a router during the above times, which is why we're prepared to overlook the two massively outlying rows, but since then the in_delta has just been consistently 1759426597250

**Comment by laf** [comment]
@chopkins84 you could try setting delta and in_delta to 0 for the last entry in that table and also for delta in the port_in_measurements table for the last entry. It uses the previous value by the looks of it.

**Comment by chopkins84** [comment]
That's cleared it up. I'll have to go back and repair the previous records. So this is a bug, then? If it's not taking the delta at the time it's running then it's not using the true live results that it's getting from SNMP when the cron runs

**Comment by laf** [comment]
I'd have to check into it more. It's quite possible that we got a bad response from the snmp request, this can happen when links are brought up / shutdown or the device is busy dealing with genuine traffic so de-prioritises the snmp request and we get the wrong values back.

**Comment by chopkins84** [comment]
How do I get it to recalculate the overage?

**Comment by laf** [comment]
I'm not sure again without checking through the code I'm afraid :(

**Comment by chopkins84** [comment]
Okay, thanks. If you could check and get back to me I'd be grateful as the bills are now unusable

**Comment by laf** [comment]
So it looks like you can't fix the bill_data info as that is collected at the time. You would either need to manually edit the values to what you would have expected to see or just remove the bad data.

For bill_history, you can remove this months bill_history entry once the above has been done and then when ./billing-calculate.php is run from cron it will update everything.

**Comment by chopkins84** [comment]
Thanks. I've already purged the entries from the bill_data and recalculated the combined deltas. I'll take a look at the bill_history table and feed back

**Comment by chopkins84** [comment]
The individual bills have been repaired, but the combined bill covering all of the ports has recreated the row with a huge bill. Is there a different table that handles the combined bills' data?

**Comment by laf** [comment]
bill_data is used to calculate bill_history I believe so maybe some bad data still exists in bill_data?

**Comment by chopkins84** [comment]
Thanks. I've found the erroneous data and removed it.

**Comment by richardlawley** [comment]
Looking at the constant deltas in the data you posted above, this might be the same bug I just fixed in #3123 - if the interface counters don't increase (e.g. the port is down), the previous delta value is reported constantly instead of 0.

**Comment by laf** [comment]
Thanks @richardlawley :)
