### ISSUE TITLE
Licensing review

### ISSUE THREAD

**Issue by paulgear** [librenms/librenms#28]
Observium seems to be a bit of a licensing minefield.  The overall Observium license for the revision from which LibreNMS was forked is GPLv3 or later, but there are a number of components included which may be in conflict with this.  Candidates include:
- JpGraph (html/includes/jpgraph): QPL 1.0 license
- MIBS (mibs): unknown/various
- html/graph-realtime.php: BSD (original?)
- html/includes/collectd/: GPLv2 only
- html/includes/tcpdf/fonts/dejavu-fonts-ttf-2.33: some sort of BSD?
- overLIB (html/js/overlib_mini.js): modified Artistic 1.0?
- scripts/*/mysql: GPLv2 only
- check_mk (scripts/observium_agent*): GPLv2

Licenses which are OK according to http://www.gnu.org/licenses/license-list.html:
- html/css/bootstrap.css: Apache v2.0
- html/includes/tcpdf: LGPL v3
- SortTable (html/js/sorttable.js: X11
- Color.php (includes/console_colour.php): MIT
- dbFacile (includes/dbFacile.php): MIT
- PHPMailer (includes/phpmailer): LGPL
- scripts/*/apache: GPLv2 or later
- Cacti (scripts/removespikes.php): GPLv2 or later
- jQuery (various locations): MIT or GPLv2
- HTML5 Shiv (html/js/html5.js): MIT or GPLv2

**Comment by laf** [comment]
I think doc/General/Acknowledgement.md gets us to a place where we have documented most of the licenses for the 3rd party sofware we use.

We now just need to start work on getting rid of the non-compatible code or moving it into other repos which I know @f0o has started on.

**Comment by adaniels21487** [comment]
I have an 'out there' suggestion to MIB licensing.
Dont use them...

If modules were re-written to use OID's, the MIB's would be unnecessary.
This would also shrink the codebase by half.

Aaron

**Comment by laf** [comment]
:)

That's one way to do it. I do see and find the benefit that names are used from a code reading / debugging perspective though.

**Comment by adaniels21487** [comment]
Would comments and debugging messages be an acceptable substitute?

**Comment by laf** [comment]
That would only help reading code, the debugging process when running poller.php and or discovery.php would still need 'translating' @librenms/reviewers

**Comment by f0o** [comment]
Hrm correct me if I'm wrong: didnt we agree on he 2015 summit that we would split off the MIBs into a submodule when it becomes feasable?
Looking at it now, with the new daily.sh we might already be at that point where we can split it off without causing service disruption on the installs.
This would surely make the numeric/named OID discussion obsolete - or am I mistaken?

I think over at @QuxLabs we have a WIP that has 4-5 submodules managing diverse parts.
I will check the internal git when back from office and repor

**Comment by f0o** [comment]
Sorry the bus when full speed and I misclicked.... GH isnt very mobile friendly :(

**Comment by laf** [comment]
Is this something we can close now.
