### ISSUE TITLE
Alert rules adding unnecessary spaces in regular expressions

### ISSUE THREAD

**Issue by fubecka** [librenms/librenms#2803]
When creating an alert rule using the Like operator, unnecessary spaces are added to the MySQL query for the rule check. For example, if you create the rule: `%ports.ifAlias ~ "\\|.*\\|"` the MySQL query that is created is `ports.ifAlias REGEXP "\\|. * \\|"`. This query can be seen by running the command `./poller.php -h HOSTNAME -d -r -f -m os`.

**Comment by Rosiak** [comment]
Tagging @f0o

**Comment by f0o** [comment]
Duplicate: https://github.com/librenms/librenms/issues/2479

No solution avail. Feel free to suggest something.

Closing due to duplication
