### ISSUE TITLE
Leaflet, print list instead of a crowded area.

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#2805]
Print a box with a list instead of this grouping, this happens when multiple devices is placed on the same location.

![screen shot 2016-01-18 at 22 38 19](https://cloud.githubusercontent.com/assets/6378934/12403464/476264d6-be34-11e5-8fca-f27745dc0c33.png)

**Comment by f0o** [comment]
:+1:

**Comment by aauvinet** [comment]
:+1:

**Comment by SaaldjorMike** [comment]
:+1:

**Comment by Rosiak** [comment]
Moved to community site.
