### ISSUE TITLE
wdget summarizing groups

### ISSUE THREAD

**Issue by cusco** [librenms/librenms#2811]
Hi,

We have a few remote locations with independent small networking setup. Each of these networks connects to us via VPN and as such we can monitor its devices on libresnmp.

Now we created a few groups to be able to view these network's devices.

Would it be possible to have a widget that would show some stuff grouping by group?

Say a widget like availability map that allows me to select a filter or a group!
That way I could have a display with say, 10 widgets each one for a different group!

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #162](https://github.com/librenms/librenmsv2/issues/162) via [**ZenHub**](https://www.zenhub.com/)
