### ISSUE TITLE
Entities don't work in alert templates

### ISSUE THREAD

**Issue by murrant** [librenms/librenms#2819]
For example, when using %devices.status or %storage.storage_perc, it is not resolved.

From what I can tell, in alerts.php RunJail(), only the data in $obj array is available, so when the code is evaluated. $devices['status'] is empty (and indeed $devices is empty).

**Comment by f0o** [comment]
Please re-read the docs about it. The way you use it is not going to work and its not a bug

**Comment by murrant** [comment]
Ahah, a fresh day and it makes a little more sense, the entities only are for the rules, templates only has access to specific information.  (as can be found in the code).  I can't have as informative of a alert as I would like, but that is ok. Something like this:
```
%hostname down {if %count > 1}for %elapsed{/if}
https://librenms/device/device=%device_id
```
