### ISSUE TITLE
API list_devices and other device related functions return empty data

### ISSUE THREAD

**Issue by szatam** [librenms/librenms#2821]
API list_devices and other device related functions return empty data. It's caused by json_encode failing (utf8 error) to encode the newly added 'ip' varbinary column from the 'devices' table (/sql-schema/092.sql) introduced with 49adff3895da01866a2d65376728c64b4e40f530
/api_v0.php/api/v0/devices?type=all -> no errors, empty string

**Comment by laf** [comment]
That's really odd, I get a response back here but just no ip. PR inbound anyway.

**Comment by szatam** [comment]
Thanks, that was amazingly quick! :+1:
