### ISSUE TITLE
Geist Watchdog

### ISSUE THREAD

**Issue by thaslym** [librenms/librenms#2826]
Geist Watchdog not showing sensors.
[librenms.txt](https://github.com/librenms/librenms/files/98983/librenms.txt)

**Comment by compuguy** [comment]
I can confirm this as well with a WatchDog 100, firmware v1.5.4. No temperature or water sensors show up. The device allows me to download a set of mibs that I can provide if needed.

**Comment by laf** [comment]
Ideally what we would need is access to a device to add support, can someone provide this?

**Comment by compuguy** [comment]
My workplace has a Watchdog 100, but I obviously cannot provide access to it. I can send you the MIBS that are provided with the latest firmware for the Watchdog 100.

**Comment by thaslym** [comment]
Its a environment monitor, here is a screenshot of how it need to be...
![geist](https://cloud.githubusercontent.com/assets/16812835/12542738/e4e7e37a-c348-11e5-8c9a-488a5f99daae.png)

**Comment by laf** [comment]
Please don't post obs... screenshots :/

Access to the device makes life a lot easier to add support. If someone can provide us this then we can fix the issue a lot quicker.

**Comment by Rosiak** [comment]
Any news @thaslym ?

**Comment by thaslym** [comment]
Still nothing...

**Comment by thaslym** [comment]
can give MIB, will it help?

**Comment by thaslym** [comment]
here is the mib file in txt 




[watchdog.txt](https://github.com/librenms/librenms/files/133694/watchdog.txt)

**Comment by laf** [comment]
@thaslym can you provide us snmp access to a device. It will be much quicker if you can.

**Comment by murkel-ohman** [comment]
@laf I have a Watchguard 15 that I could give you snmp access to.  I believe it uses the same MIB's but I don't have a 100 to verify that.  However, I am getting the same result where the sensors are not showing.

**Comment by laf** [comment]
@murkel-ohman That would be awesome. If you can provide details to neil @ librenms.org please that would be great.

**Comment by murkel-ohman** [comment]
Fantastic, thanks!  I have sent the information.

**Comment by Rosiak** [comment]
@laf Had a chance to look at it or?

**Comment by laf** [comment]
No access to the device anymore.

**Comment by slm4996** [comment]
@laf  I have a Watchdog 15 (BB-TH-P), while I am unable to provide snmp access I can provide a snmpwalk dump if that would be of any assitance.

**Comment by slm4996** [comment]
snpwalk with the geist MIBs loaded:
```
SNMPv2-MIB::sysDescr.0 = STRING: Watchdog 15
SNMPv2-MIB::sysObjectID.0 = OID: GEIST-V4-MIB::watchdog100
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (363732) 1:00:37.32
SNMPv2-MIB::sysContact.0 = STRING:
SNMPv2-MIB::sysName.0 = STRING: Watchdog 15
SNMPv2-MIB::sysLocation.0 = STRING:
SNMPv2-MIB::sysServices.0 = INTEGER: 72
IF-MIB::ifNumber.0 = INTEGER: 1
IF-MIB::ifIndex.0 = INTEGER: 1
IF-MIB::ifDescr.0 = STRING: eth0
IF-MIB::ifType.0 = INTEGER: ethernetCsmacd(6)
IF-MIB::ifMtu.0 = INTEGER: -32768
IF-MIB::ifSpeed.0 = Gauge32: 2140510208
IF-MIB::ifPhysAddress.0 = STRING: d8:80:39:3d:31:6d
IF-MIB::ifAdminStatus.0 = INTEGER: up(1)
IF-MIB::ifOperStatus.0 = INTEGER: up(1)
IF-MIB::ifLastChange.0 = Timeticks: (0) 0:00:00.00
IF-MIB::ifInOctets.0 = Counter32: 0
IF-MIB::ifInUcastPkts.0 = Counter32: 0
IF-MIB::ifInNUcastPkts.0 = Counter32: 0
IF-MIB::ifInDiscards.0 = Counter32: 0
IF-MIB::ifInErrors.0 = Counter32: 0
IF-MIB::ifInUnknownProtos.0 = Counter32: 0
IF-MIB::ifOutOctets.0 = Counter32: 0
IF-MIB::ifOutUcastPkts.0 = Counter32: 0
IF-MIB::ifOutNUcastPkts.0 = Counter32: 0
IF-MIB::ifOutDiscards.0 = Counter32: 0
IF-MIB::ifOutErrors.0 = Counter32: 0
IF-MIB::ifOutQLen.0 = Gauge32: 0
IF-MIB::ifSpecific.0 = OID: SNMPv2-SMI::zeroDotZero
GEIST-V4-MIB::productTitle.0 = STRING: Watchdog 15
GEIST-V4-MIB::productVersion.0 = STRING: 3.2.0
GEIST-V4-MIB::productFriendlyName.0 = STRING: Watchdog 15
GEIST-V4-MIB::productMacAddress.0 = Hex-STRING: D8 80 39 3D 31 6D   [..9=1m]
GEIST-V4-MIB::productUrl.0 = IpAddress: 10.0.1.3
GEIST-V4-MIB::deviceCount.0 = INTEGER: 1
GEIST-V4-MIB::temperatureUnits.0 = INTEGER: 0
GEIST-V4-MIB::internalIndex.1 = INTEGER: 1
GEIST-V4-MIB::internalSerial.1 = STRING: E8D880393D316DC3
GEIST-V4-MIB::internalName.1 = STRING: Watchdog 15
GEIST-V4-MIB::internalAvail.1 = Gauge32: 1
GEIST-V4-MIB::internalTemp.1 = INTEGER: 757 0.1 Degrees
GEIST-V4-MIB::internalHumidity.1 = INTEGER: 37 %
GEIST-V4-MIB::internalDewPoint.1 = INTEGER: 476 0.1 Degrees
GEIST-V4-MIB::internalDewPoint.1 = No more variables left in this MIB View (It is past the end of the MIB tree)
```

**Comment by stavrosg** [comment]
Any update on this? I got 2 of these

**Comment by stavrosg** [comment]
Got them kind of working. defined the os, it gets picked up. Trying to get the sensors. installed the mib and it only shows 7 in the gui for the device. snmptranslate returns was more. Curious how you link the sensors to the graphs.

**Comment by laf** [comment]
This PR should give you some ideas: https://github.com/librenms/librenms/pull/5356/files

**Comment by stavrosg** [comment]
Got it mostly working. Thanks the PR helped a lot.

Anyone wants the files, let me know.

**Comment by laf** [comment]
You need to submit the files as a pull request. See our docs on the process.

**Comment by laf** [comment]
No further info provided
