### ISSUE TITLE
ARP search result issue.

### ISSUE THREAD

**Issue by ebym** [librenms/librenms#2827]
ARP Search result doesn't show the access switch, access switch port information While searching for ip/mac address. Whilst community edition of Observium 0.15.6.6.6430 show access switch name.

On access switch, mac-address table show the end device connected port and core switch show the port of core sw connected to access switch.

![librenms-arp-search png](https://cloud.githubusercontent.com/assets/16803049/12477111/a4dc9818-c053-11e5-8c6d-2e61dd0481c7.png)

Thanks,
Eby

**Comment by laf** [comment]
Please no screenshots from Obs...

**Comment by ebym** [comment]
Thanks,

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-arp-search-result-issue/726
