### ISSUE TITLE
SELECT @@innodb_buffer_pool_size not supported on older MySQL

### ISSUE THREAD

**Issue by ciscoqid** [librenms/librenms#2831]
The daily.php script relies on the query "SELECT @@innodb_buffer_pool_size" and will fail if the variable is not supported as seems to be the case when MySQL lives on a CentOS 5 server (all else seems to work fine in that environment).

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 24374506
Server version: 5.0.95 Source distribution

mysql> SELECT @@innodb_buffer_pool_size;
ERROR 1193 (HY000): Unknown system variable 'innodb_buffer_pool_size'

Manual updates are possible via git pull and discovery.php -h none, but auto-update cannot work  Interestingly, the variable does exist, just doesn't select that way for some reason (still researching).

mysql> SELECT @@innodb_buffer_pool_size;
ERROR 1193 (HY000): Unknown system variable 'innodb_buffer_pool_size'
mysql> show variables like 'innodb_buffer_pool_size';
+-------------------------+-----------+
| Variable_name           | Value     |
+-------------------------+-----------+
| innodb_buffer_pool_size | 134217728 |
+-------------------------+-----------+
1 row in set (0.00 sec)

**Comment by laf** [comment]
MySQL 5.0! Wow. Whilst we don't have a minimum supported config I'd go out on a limb and say MySQL 5.0 wouldn't be on such list if we did ( @librenms/reviewers ?).

However saying that, that safety check may not even be needed now. It was what we thought fixed the ALTER devices schema issue but as we found out over the last 48 hours this isn't the case. We now have what we believe is the proper fix and we _could_ remove the innodb buffer check.

I'm just not sure if we should or not as I don't know the full implications of having a full innodb buffer.

**Comment by paulgear** [comment]
I don't think we should invest a lot of time in supporting older software like MySQL 5.0, but if it's a simple condition check that doesn't seem like a big deal.  Or maybe even the "show variables like" syntax will work on all versions?

**Comment by ciscoqid** [comment]
On 1/21/2016 4:45 PM, Paul Gear wrote:
>
> I don't think we should invest a lot of time in supporting older software like MySQL
> 5.0, but if it's a simple condition check that doesn't seem like a big deal. Or maybe
> even the "show variables like" syntax will work on all versions?
>

I agree, except CentOS 5 is still alive (barely) and in some cases for now it is still our
simplest place to host MySQL.  Still, it you said it was not supported, I am sure I could
replace with MariaDB easily enough.  I would rather that be explicit, that's all :).

Thanks,
Mark

-- 
Mark D. Nagel, CCIE #3177 Emeritus <mnagel@willingminds.com>
Principal Consultant, Willing Minds LLC (http://www.willingminds.com)
cell: 949-279-5817, desk: 714-495-4001, fax: 714-844-4698

** For faster support response time, please
** email support@willingminds.com or call 714-495-4000

**Comment by laf** [comment]
CentOS 5 is only receiving maintenance updates so like MySQL 5 I'd say wouldn't be on our compatibility list :)

@ciscoqid Is a patch something you can contribute to get this working for you?

**Comment by laf** [comment]
We no longer check for this on daily only validate so shouldn't be an issue anymore
