### ISSUE TITLE
Device Group

### ISSUE THREAD

**Issue by chrisgfx** [librenms/librenms#2832]
Hi,

It seems Group is not sent by the API but only the default one to Oxidized.

curl -H 'X-Auth-Token: 3302bdf4014b9c81f3c686af9a6c5c60' http://10.33.200.15/api/v0/devicegroups/Firewalls
{
    "status": "error",
    "message": "Found 2 in group Firewalls",
    "count": 2,
    "devices": [
        {
            "device_id": "4"
        },
        {
            "device_id": "5"
        }
    ]

"device_id": "4" and 5 are eva_fw_3rd and eva_fw_5rd.

curl -H 'X-Auth-Token: 3302bdf4014b9c81f3c686af9a6c5c60' http://10.33.200.15/api/v0/oxidized
[
    {
        "hostname": "eva_sw_5rd",
        "os": "ios",
        "group": "Network"
    },
    {
        "hostname": "eva_sw_3rd",
        "os": "ios",
        "group": "Network"
    },
    {
        "hostname": "eva_fw_5rd",
        "os": "junos",
        "group": "Network"
    },
    {
        "hostname": "eva_fw_3rd",
        "os": "junos",
        "group": "Network"

**Comment by chrisgfx** [comment]
Sorry, Network is the default Group defined in LibreNMS with the Global Settings

**Comment by laf** [comment]
Not sure I understand what you mean by this.  Have you created your oxidized groups in config.php? If so what's the config you've used.

**Comment by chrisgfx** [comment]
I understood my mistake! I believed Device Group defined with the GUI in Librenms was the ones sent to Oxidized, but I read carefully the documentation and I know learn that we can define groups only used by Oxidized and more freely as I hope ! Great! :satisfied:
Will try tomorrow morning. :+1:
