### ISSUE TITLE
Discovery / Polling Issues with latest Updates?

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#2833]
Hi,

I actually hesitate raising this, as it really seems like this would be on my side (as others have not commented) - and I have gone back and forth a few times ... :-(. But in case it's a wider issue - I did a git pull yesterday, updating to some of the latest code changes. Now when I run discovery or polling (pointing at a specific host) ... nothing really happens (it runs, but very little output). I also noticed that in the device groups, some of my groups have gone away now.

Have other seen this? Any suggestions of how to get this working again?

FYI, I did try to go back to the older commit, but it doesn't work either. Perhaps my database has gotten broken somehow?

Thanks!

**Comment by laf** [comment]
Post the output of:

```bash
./discovery.php -h HOSTNAME -d
./poller.php -h HOSTNAME -d -r -f
```

For one device and let's see.

**Comment by arrmo** [comment]
You bet! Here it is ...

1) Discovery
LibreNMS 2015.master Discovery
Version info:
Commit SHA: aec0453c76f130cb7ef2d4aafef3fc5360245e69
DB Schema: 93
PHP: 5.5.9-1ubuntu4.14
MySQL: 5.5.46-0ubuntu0.14.04.2
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1]
SQL[SELECT revision FROM `dbSchema`] DB Schema already up to date.

SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE 'ix2.home' ORDER BY device_id DESC] ./discovery.php ix2.home 2016-01-21 13:36:42 - 0 devices discovered in 0.013 secs
MySQL: Cell[1/0s] Row[3/0s] Rows[1/0s] Column[0/0s] Update[0/0s] Insert[0/0s] Delete[0/0s]

2) Poller
LibreNMS 2015.master Poller
Version info:
Commit SHA: aec0453c76f130cb7ef2d4aafef3fc5360245e69
DB Schema: 93
PHP: 5.5.9-1ubuntu4.14
MySQL: 5.5.46-0ubuntu0.14.04.2
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'ix2.home' ORDER BY `device_id` ASC] ./poller.php ix2.home 2016-01-21 13:38:28 - 0 devices polled in 0.011 secs

MySQL: Cell[0/0s] Row[2/0s] Rows[1/0s] Column[0/0s] Update[0/0s] Insert[0/0s] Delete[0/0s]


Yes, that's all there is ... ;-). This device was working before - graphs and all.


Thanks!

**Comment by laf** [comment]
Jump on irc?

**Comment by arrmo** [comment]
Will - in about 2 hours if that's OK ... is that too late? Just stepping in to a work meeting.

Hate when work gets in the way of fun ... ;-).

**Comment by laf** [comment]
Not at all, just ping me when you're on.

**Comment by arrmo** [comment]
Will do - thanks! No idea what TZ anyone is in ... :-).

**Comment by laf** [comment]
We need to get some eventlog added to log when devices are deleted. Please keep this issue open.
