### ISSUE TITLE
Graphs not showing after LibreNMS update

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#2838]
Hi,

I successfully upgraded to version 1aad82c, db schema 93 in our lab install and I noticed that the traffic graphs are no longer visible. I checked the config.php for spaces and I couldn't find any. Can you please suggest where I will need to look.

![image](https://cloud.githubusercontent.com/assets/16717388/12505836/e077a9ea-c0f2-11e5-899d-130fb27aef9d.png)

![image](https://cloud.githubusercontent.com/assets/16717388/12505786/8dcc8490-c0f2-11e5-9c13-4fe3d6a06471.png)

**Comment by laf** [comment]
Can you run ./validate.php first and fix any errors you see.

**Comment by laf** [comment]
@breeman1 any info?

**Comment by breeman1** [comment]
Hi Laf,

I ran the "validate.php" as you suggested and it failed with a lot of files having root as a owner which I fixed. It looks like running the "git pull --quiet" command changes some file ownership but that as it may, after changing the ownership manually, validation did not find any errors; however I am still experiencing the same issue with graphs not showing.

![image](https://cloud.githubusercontent.com/assets/16717388/12548629/5d792152-c360-11e5-838e-89cf1b20449e.png)

![image](https://cloud.githubusercontent.com/assets/16717388/12548702/ee624cde-c360-11e5-89b9-e9a5d5e41837.png)

**Comment by laf** [comment]
You need to wait 10 mins after changing permissions.

if it still doesn't work then right click on a graph, copy the image url (not the url - needs to be the image url). Go to that in a browser and add &debug=true to the end. Paste the output on dpaste.de or similar.

**Comment by breeman1** [comment]
I waited for more than that time and it is still the same. What I noticed is that on Google Chrome the image handler does not even show at all. See below. I have attached the debug files for your reference. 
The PHP debug is here, https://dpaste.de/W7d2 and the SQL debug here https://dpaste.de/uV1t.

I really appreciate your help.

![image](https://cloud.githubusercontent.com/assets/16717388/12550568/5d908c18-c36d-11e5-8cf1-def65e9c0700.png)

**Comment by laf** [comment]
@breeman1 Those aren't the output we need :) Check my reply again and it will tell you what we need.

**Comment by breeman1** [comment]
Sorry, please see this then, https://dpaste.de/WPKU. Is that what you are looking for?

**Comment by laf** [comment]
Yup:

"command returned 0 (ERROR: Unable to connect to rrdcached: No such file or directory )"

You've got rrdcached configured but it's not allowing connections. Either disable rrdcached support or get rrdcached working :)

**Comment by breeman1** [comment]
I actually noticed it in the debug dump I sent you. The issue was that rrdcached was not installed. I installed it and configured it properly and now it works, well so of. I am still getting the "Error Drawing Graph" message for the Overall traffic graphs on the Overview Tab of the Enterasys switches, the traffic under the Ports Tab works though. Other devices work properly. Please have a look at the dump; https://dpaste.de/YOjN,  and see if you can figure out what could the issue. Thanks.

![image](https://cloud.githubusercontent.com/assets/16717388/12557787/21fb04bc-c395-11e5-8ee1-306016507795.png)

**Comment by laf** [comment]
Can you provide a list of port names for this device please:

`SELECT ifName,ifDescr,ifAlias FROM ports WHERE device_id=X;`

**Comment by breeman1** [comment]
See here for port names; https://dpaste.de/FrQ9.

**Comment by breeman1** [comment]
Hi Laf,

Just wanted to find out if you've had the chance to look into this yet?

**Comment by laf** [comment]
Sorry not had a chance, can you reprovide the info as the dpaste link has expired.

**Comment by breeman1** [comment]
Hi @laf,

Here is the output of the port names; https://dpaste.de/Xcd7

**Comment by Rosiak** [comment]
Is this still a problem?

**Comment by breeman1** [comment]
Yes, it is still an issue for me. As you will note in my last comment on the 25th of January that the graph legend shows no data for this particular switch.

**Comment by laf** [comment]
We will need a non-expiring paste please, others have all gone now.

**Comment by breeman1** [comment]
Hi @laf ,

D you have suggestions of the ones I can use?

**Comment by laf** [comment]
pastebin.com?

**Comment by breeman1** [comment]
Here is the link for the output you last requested, http://pastebin.com/TvUtCrRM. Let me know should require additional info.

**Comment by laf** [comment]
right click on a graph, copy the image url (not the url - needs to be the image url). Go to that in a browser and add &debug=true to the end. Paste the output on pastebin.com or similar.

**Comment by breeman1** [comment]
Here is the output as requested, http://pastebin.com/sjDCUkZL

**Comment by laf** [comment]
Can you also provide the output of:

`SELECT ifName,ifDescr,ifAlias,ifType FROM ports WHERE device_id=X;`

**Comment by syunusic** [comment]
Sorry, I know this is not my support case, but I have the same problem (Centos 7, rrdtool 1.4.8-9, version 9d62339, DB Schema 107). Here it is the problem:
"...COMMENT:'\n' CDEF:inB= CDEF:ou..."
And then it says:
"command returned 0 (ERROR: String ends after the = sign on 'CDEF:inB=' )"
The whole paste is here: http://pastebin.com/csFBX7KT

**Comment by breeman1** [comment]
Here you go, http://pastebin.com/iiM3T0j4

**Comment by breeman1** [comment]
Hi @laf 

I am running a fresh install of LibreNMS on Ubuntu 16.04 and the issue with this Entersys switch has worsened a bit in a sense that the traffic graphs have disappeared again. This issues manifest itself with or without rrdcached running unlike in earlier versions of LibreNMS. Adding &debug=true at the end of the URL (**https://x.x.x.x/graph.php?height=45&width=150&to=1469720700&device=2&type=device_bits&from=1469634300&legend=no&popup_title=&bg=FFFFFF00&debug=true**)does not work as it cuase webpage to timeout with the "**Fatal error: Maximum execution time of 300 seconds exceeded in /opt/librenms/includes/rrdtool.inc.php on line 131**" error. See below;
![snap15](https://cloud.githubusercontent.com/assets/16717388/17221608/ca677e46-54f4-11e6-81c2-dd8d4e097364.png)
![snap16](https://cloud.githubusercontent.com/assets/16717388/17221638/ec7a35dc-54f4-11e6-8025-ebfdddbc4a46.png)
![snap17](https://cloud.githubusercontent.com/assets/16717388/17221639/ec9da120-54f4-11e6-80af-7756906cf7c0.png)
![snap18](https://cloud.githubusercontent.com/assets/16717388/17221640/eca13c54-54f4-11e6-80e8-4b2c2fc05341.png)

Please let me know should you require further info.

**Comment by breeman1** [comment]
I may as well add that navigating the Enterasys screens is quite slow I suppose for the same reasons.

**Comment by Rosiak** [comment]
Sorry to bother you again @breeman1 , but has the latest updates to Libre made any changes for you?

**Comment by breeman1** [comment]
Hi @Rosiak,

No, not in terms of rgraphs rendering however I have noticed significant improvement in the loading times of affected devices pages. Previously the it would takes anything between 1 to 3 minutes (I measured this) for the devices overview page to load when clicking on these Enterasys switches. The loading time significantly problematic on devices runniing on N3 and N7 Enterasys plartform and not so much on other plartforms from the same vendor. I updated my install yesterday therefore it is fairly current and below is the screenshot of the device overview for one of the affected devices. I have also captured the image URL of the same device with &debug=true at the end which is available here; http://pastebin.com/BqfH6ZGu

![snap39](https://cloud.githubusercontent.com/assets/16717388/18090903/182085a6-6ec7-11e6-90ec-d4dee3cc5c60.png)

**Comment by laf** [comment]
What happens if you run `rrdtool graph /tmp/H08WIHXRkkCAUD4Z.png -g --alt-autoscale-max --rigid -E --start 1472475900 --end 1472562300 --width 150 --height 45 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal -c CANVAS#FFFFFF00 --only-graph --font LEGEND:7:DejaVuSansMono --font AXIS:6:DejaVuSansMono --font-render-mode normal COMMENT:' Now Avg Max' COMMENT:'\n' CDEF:inB= CDEF:outB= CDEF:octets=inB,outB,+ CDEF:doutB=outB,-1,* CDEF:inbits=inB,8,* CDEF:outbits=outB,8,* CDEF:bits=inbits,outbits,+ CDEF:doutbits=doutB,8,* VDEF:95thin=inbits,95,PERCENT VDEF:95thout=outbits,95,PERCENT CDEF:d95thoutn=doutbits,-1,* VDEF:d95thoutn95=d95thoutn,95,PERCENT CDEF:d95thoutn95n=doutbits,doutbits,-,d95thoutn95,-1,*,+ VDEF:d95thout=d95thoutn95n,FIRST VDEF:totin=inB,TOTAL VDEF:avein=inbits,AVERAGE VDEF:totout=outB,TOTAL VDEF:aveout=outbits,AVERAGE VDEF:tot=octets,TOTAL COMMENT:' \n' HRULE:999999999999999#FFFFFF:'Total In ' GPRINT:inbits:LAST:%6.2lf%s GPRINT:inbits:AVERAGE:%6.2lf%s GPRINT:inbits:MAX:%6.2lf%s GPRINT:totin:%6.2lf%sB COMMENT:'\n' HRULE:999999999999990#FFFFFF:' Out' GPRINT:outbits:LAST:%6.2lf%s GPRINT:outbits:AVERAGE:%6.2lf%s GPRINT:outbits:MAX:%6.2lf%s GPRINT:totout:%6.2lf%sB COMMENT:'\n' HRULE:999999999999990#FFFFFF:' Agg' GPRINT:bits:LAST:%6.2lf%s GPRINT:bits:AVERAGE:%6.2lf%s GPRINT:bits:MAX:%6.2lf%s GPRINT:tot:%6.2lf%sB COMMENT:'\n' HRULE:0#999999 --daemon unix:/var/run/rrdcached.sock`

**Comment by breeman1** [comment]
Hi @laf,
It this the information that  you are looking for? The last line reads; **Segmentation fault (core dumped)**
![snap40](https://cloud.githubusercontent.com/assets/16717388/18091953/cc4057a2-6eca-11e6-8146-9d156416f4bf.png)

I was meaning to mention in my previous post that the page loading times on these affected devices are significantly faster now in a region of 2 to 5 seconds when before the update; they were in the region of 1 to 3 minutes as mentioned. Great work and well done on sorting that issue out with the latest release.

**Comment by laf** [comment]
Maybe bump your rrdtool version up, if you can try 1.6

**Comment by laf** [comment]
Is that running rrdcached 1.6 as well?

You'll also need to ensure you specify the config version of rrdcached.

**Comment by breeman1** [comment]
Yes it is, see below;
![snap43](https://cloud.githubusercontent.com/assets/16717388/18097947/712e4cfa-6ee0-11e6-88ae-9736bcce4bf5.png)
![snap44](https://cloud.githubusercontent.com/assets/16717388/18097950/7561bf6e-6ee0-11e6-8151-ac14c1f72145.png)
![snap45](https://cloud.githubusercontent.com/assets/16717388/18097954/78cc0678-6ee0-11e6-8c1d-3c27f9ba81de.png)

**Comment by laf** [comment]
Are all of those interfaces vlan / virtual interfaces?

**Comment by breeman1** [comment]
Yes, here's is some screenshots.
![snap39](https://cloud.githubusercontent.com/assets/16717388/18120103/41bc6e42-6f5e-11e6-859a-ec9dd706e46a.png)
![snap40](https://cloud.githubusercontent.com/assets/16717388/18120110/49635cbe-6f5e-11e6-8b74-0d58115a74ea.png)

**Comment by laf** [comment]
I think virtual are excluded usually. I'll take a look.

**Comment by Rosiak** [comment]
Hi, @breeman1 
Issue resolved?
You mentioned that in #3263 :)

**Comment by breeman1** [comment]
Yes, the config change that @murrant provided seems to have solve the graphing issue for me. Here's the post  in case anyone is interested;

Add this code to your config.php to fix.

$config['bad_if'] = array_diff($config['bad_if'], array('ras'));

**Comment by murrant** [comment]
@laf thoughts about dropping ras from bad_if upstream?

**Comment by laf** [comment]
We don't have any ports with ras in so it doesn't affect us but it may be just better documenting it
