### ISSUE TITLE
Host data incorrect, all graphs have errors

### ISSUE THREAD

**Issue by itayk290** [librenms/librenms#2842]
I'm running Ubuntu 14.04 inside an LXC container, using br0 to bridge my NMS container to my main network. I've tried librenms as a virtual machine (prebuilt by librenms) and it works correctly. When I tried following the installation instructions, I have not been able to set up the same way. I noticed certain files inside /opt/librenms were owned by root instead of librenms, so I corrected them all according to what I found in validate.php

When I run validate.php:
Version info:
Commit SHA: 81fdfa6aa93c8d1c7d410321a8c5249d931541cc
DB Schema: 6
PHP: 5.5.9-1ubuntu4.14
MySQL: 5.5.46-0ubuntu0.14.04.2
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

[OK]      Database connection successful
[OK]      fping has been found

I get lots of PHP errors in debug, for instance:
Array ( [errno] => 8 [errstr] => Undefined index: influxdb [errfile] => /opt/librenms/includes/influxdb.inc.php [errline] => 15 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchrow_sec [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 331 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchrow [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 332 )
Array ( [errno] => 8 [errstr] => Undefined index: update_sec [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 216 )
Array ( [errno] => 8 [errstr] => Undefined index: update [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 217 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchrows_sec [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 276 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchrows [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 277 )
Array ( [errno] => 8 [errstr] => Undefined variable: navbar [errfile] => /opt/librenms/html/includes/print-menubar.php [errline] => 26 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchcell_sec [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 365 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchcell [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 366 )
Array ( [errno] => 8 [errstr] => Undefined variable: param [errfile] => /opt/librenms/html/includes/print-menubar.php [errline] => 139 )
Array ( [errno] => 8 [errstr] => Undefined index: _ObjCacheSkell [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 47 )
Array ( [errno] => 8 [errstr] => Undefined index: _ObjCache [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 51 )
Array ( [errno] => 8 [errstr] => Undefined index: ports [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 60 )
Array ( [errno] => 8 [errstr] => Undefined index: params [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 98 )
Array ( [errno] => 8 [errstr] => Undefined index: params [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 98 )
........ etc

I'm very close to just using the virtual machine, but I'd really rather have it as a container.
Anything I can try?

**Comment by laf** [comment]
Those are just php notices rather than actual errors.

please jump on our irc channel, it'll be easier :)

**Comment by itayk290** [comment]
I got it working! It turned out all I needed to do was start the cron job by copying it into the directory specified in the installation notes. I just misread it!
Thank you!
