### ISSUE TITLE
Create VM Parent host on machine summary

### ISSUE THREAD

**Issue by djtecha** [librenms/librenms#2843]
So currently you can see what VMs a host has given the "Virtual Machines" tab, but what about the other way around? For instance I'm looking at VM-1 and need to know what it's parent machine is? It would be cool to have a link to the parent VM vs trying to track things down the other way.

**Comment by laf** [comment]
I'm assuming you mean when you also have the VM in LibreNMS as a monitored device? At present we don't have any link between a VM and host apart from within the Virtual Machines tab but this just simply lists the VM.

In the vminfo table, does vmwVmDisplayName match up with the hostname at all?

**Comment by djtecha** [comment]
Well, since the VM never knows what the parent is I would assume we would have to do the linking in librenms. For instance a simple mysql select to find the parent host. Like if I'm a VM then so a select from the VM tab table. 

something like:

select device_id from vminfo where vmwVmDisplayName = 'VM NAME';

**Comment by laf** [comment]
Indeed, does vmwVmDisplayName match to hostnames or sysNames?

**Comment by djtecha** [comment]
"select * from devices where hostname" in my case, mainly because I stripped the FQDN to get VM linking working from the parent.

**Comment by laf** [comment]
I'm still unsure if you are confirming that hostname or sysName in the devices table matches the vmwVmDisplayName? Even if it's missing the FQDN then we can provide config options for that.

**Comment by djtecha** [comment]
well I'm matching on the hostname column from the devices table. So, I would believe it matches to hostname as the sysName column holds the FQDN vs. just the hostname.

**Comment by djtecha** [comment]
so the join would be something like this:

 select a.device_id, b.device_id FROM vminfo a inner join devices b on a.vmwVmDisplayName = b.hostname where b.hostname = '<VM MACHINE NAME>;

then I can use the device_id in the first culume here to link

**Comment by lowinger42** [comment]
A different solution I use for KVM is to install LLDP in both host and all guests. Autodiscovery will then find out parent/VM and update the maps (and can be seen in the 'lldpdcli show neigbours' 

I think you need the distributed switch in ESXi to get LLDP support....

**Comment by laf** [comment]
Thanks @lowinger42. This is more about linking the vms we log for vmware. We already have a relationship in the tables for xDP discovered devices :)
