### ISSUE TITLE
Sensor Under Limit (Alerts Off?)

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#2847]
Hi,

In the main tab, Alerts widget - I have an alarm, for "Sensor under limit" on one machine. A couple thoughts,
1) Is there a way to click on this, to see exactly which sensor it's flagging? I ask this because,
2) When I go to that machine, I only see one sensor in red, but it's one where I have set Alerts off. So it shouldn't be an issue, and also shouldn't be red (perhaps use gray for disabled alerts?).

Thoughts?

Thanks!

**Comment by laf** [comment]
1) You can click on the + next to the hostname - that will expand and show you what the alert matched.

2) Can you show a screenshot?

**Comment by arrmo** [comment]
Man, I clicked around like an idiot - that was the one thing I missed! Yep, works ... :-).

OK, it's doing it now - it seems like the alarm shows up when the reading is NaNV (which isn't all the time). Here is what is under the alarm (click),
#1: sensor_id => '14', sensor_oid => '1.3.6.1.4.1.2021.13.16.4.1.3.14', sensor_descr => 'in5'

And some attachments,
1) AlarmList - shows the alarm noted above (for in5) on the alarms.
2) Voltages - the voltage listings, with the red (alarmed) NaNV for this voltage
3) HealthSettings - shows that the Alert for in5 is to disabled.

Make sense?

Thanks!


![healthsettings](https://cloud.githubusercontent.com/assets/8756384/12538254/fb0b9dd0-c29a-11e5-9109-c48d5e17039d.jpg)
![alarmlist](https://cloud.githubusercontent.com/assets/8756384/12538255/fb0d9892-c29a-11e5-9cc3-3c7d97e6d704.jpg)
![voltages](https://cloud.githubusercontent.com/assets/8756384/12538253/fb0bbb12-c29a-11e5-9ed3-aff83e04d2e3.jpg)

**Comment by laf** [comment]
Ok so it's the fact that you've set that sensor to ignore but it's still generating an alert. I think this is simply that the default rule doesn't check %sensors.sensor_alert = 1. If it's set to not alert it will be 0 so if you add that to the rule and give it another try.

**Comment by arrmo** [comment]
Seems to fix the issue - thanks! Should this be added to the global rule, for both limits (over / under)?

**Comment by laf** [comment]
Yes, we will get it sorted  - unless you want to PR it :)

**Comment by arrmo** [comment]
Sure - will do!

On international travel right now, will do it when I return. Thanks!

**Comment by arrmo** [comment]
Thanks! Sorry, I was going to get to it - will be back home this Saturday ... :(.

**Comment by laf** [comment]
It's cool, was a simple fix so I just PRd it up :)
