### ISSUE TITLE
librenms unable to run in subdirectory

### ISSUE THREAD

**Issue by LeslieCarr** [librenms/librenms#285]
LibreNMS is unable to run in a subdirectory.  

In my case, I need this because I'm attempting to run it in a VM environment, with a nginx proxy, and the subdirectory redirects you to the proper VM.  

The two things I have noticed are broken - the images directory & when you login, it redirects you to the domain name.  

Thanks!

**Comment by laf** [comment]
Hi @LeslieCarr, I'm closing this issue for now. If more people enquire about us supporting it then we can re-open and take a longer look.

If you want to re-open it then please feel free.

**Comment by jeremykraemer** [comment]
Hi,
I'm a old Observium user who hoped librenms found this lack ... 
My need is to put several supervisor (like Naemon, Librenms, ...) on the same server, and each other in different sub folders (/naemon, /librenms, ...). The / being reserved to a common dashboard.

**Comment by laf** [comment]
I can have another go at getting this to work but I'm just not sure when at the moment :(

**Comment by jeremykraemer** [comment]
No problem, I understand. Thx !

**Comment by paulgear** [comment]
I think it is worth leaving this one open, since it is clearly a common use-case and would be nice to have if we can manage it.
