### ISSUE TITLE
how to use DISMAN-PING-MIB file to accomplish remote ping ?

### ISSUE THREAD

**Issue by panjun0417** [librenms/librenms#2855]
sos .....
thanks for any suggestion.....

**Comment by laf** [comment]
What is it you are actually wanting to do with this?

**Comment by panjun0417** [comment]
indeed,I just want to use snmp and DISMAN-TRACEROUTE-MIB to get traceroute message between two cisco routers,but I do not know what to. so I want to learn how to use net-snmp in ubuntu and  CISCO-PING-MIB to accomplish remote ping in cisco router firstly.

**Comment by panjun0417** [comment]
http://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/13383-21.html
I follow the example script and know how to use ping mib. now I am vexed at how to accomplish traceroute...
