### ISSUE TITLE
daily.sh aborts with an error due to a substitution issue.

### ISSUE THREAD

**Issue by dirkx** [librenms/librenms#2857]
https://github.com/librenms/librenms/blob/master/daily.sh) aborts with an error:

   /opt/librenms/daily.sh: 45: /opt/librenms/daily.sh: Bad substitution

due to that line having a typo. That line can be removed safely.

Dw.

PS: and perhaps the standard crontab examples should output to a log file like /opt/libnms/logs/crontabs.. etc - rather than /dev/null to catch issues like this (or reopen a log file within the (wrapper) scripts).

**Comment by f0o** [comment]
Line 45 `    cnd=${cnf,,}` is not a typo, it converts everything to lowercase by Bash4.x onwards

**Comment by dirkx** [comment]
Right - but I am not seeing 'cnd' being used anywhere else in the script ? 

And I am getting the error  /opt/librenms/daily.sh in a default/bare bones install (where cnf is usually empty as there is no distributed poller configured in it.

**Comment by f0o** [comment]
you're right on that one, it's not supposed to be `cnd` but `cnf`. PRing
