### ISSUE TITLE
Large number of excess sensors

### ISSUE THREAD

**Issue by khobbits** [librenms/librenms#2859]
https://dl.dropboxusercontent.com/u/3214230/2016-01-25_15-31-18.png

Device has 5 sensors, librenms polls 60. 

poll: [lotasensors.txt](https://github.com/librenms/librenms/files/103436/lotasensors.txt) - https://gist.github.com/khobbits/de42fc93ffd4750d6ca6#file-poller-txt

discovery: 
[lotasensors2.txt](https://github.com/librenms/librenms/files/103452/lotasensors2.txt) - https://gist.github.com/khobbits/de42fc93ffd4750d6ca6

~~
Version: 858dbfbe79a47fc8eb6dfee94d2052e445de46f2 - (with a tiny cosmetic .html change)
DB Schema: 94
PHP: 5.3.3
MySQL: 5.1.73-log
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.5

[OK]      Database connection successful
[OK]      fping has been found

**Comment by laf** [comment]
Told a lie on this one, can you also provide:

./discovery.php -h HOSTNAME -d -m sensors

**Comment by khobbits** [comment]
Interesting, I just did:

bash-4.1$ ./discovery.php -h 53 -d -m sensors > lotasensors2.txt
No log handling enabled - turning on stderr logging
Cannot find module (SCTP-MIB): At line 1 in (none)

**Comment by laf** [comment]
According to the snmp output those are valid sensors. I've done a PR that will allow you to filter those out using regexes. Once that's merged in you can add a config option (as per the docs) to filter these out. They should then disappear on the next discovery run.

**Comment by khobbits** [comment]
Not the sexiest regex, but I ended up going with:
```$config['bad_entity_sensor_regex'][] = '/Chassis.([1-9][0-9]+|0?[6-9]).Temperature/';```
Can confirm #2862 mitigates this issue.
