### ISSUE TITLE
Cisco switch - VLAN traffic stats and port stats don't match.

### ISSUE THREAD

**Issue by ebym** [librenms/librenms#2869]
Cisco 2960, IOS 12.2

Issue 1;
When checking virtual interface graphs, it show very little traffic (2MB) compared to the "access port" traffic belong to that particular VLAN.

It should be total IN & Out of all "access ports" minus traffic of uplink port(Trunk)

Issue 2;
Virtual interface graphs only show In traffic, Out traffic is 0.

To confirm the issues, i have deleted the device (including rrd files) and added the device after Libre server and Switch reboot.

![cisco2960-vlan-traffic png](https://cloud.githubusercontent.com/assets/16803049/12606401/4a1a7144-c4f3-11e5-8266-afc1e3f619cb.png)

**Comment by PhilipOlsson** [comment]
Have you verified that your counters actually work as you want?

This is most likely a issue with your device and not LibreNMS since I have actually never seen a Cisco Catalyst behave as you want.

**Comment by murrant** [comment]
VLAN interfaces only show traffic that is routed through the CPU, not CEF.  This basically restricts it to packets bound to the switch itself.

LibreNMS is accurately displaying the data provided by the switch.

**Comment by laf** [comment]
Closing, feel free to comment more but I believe @PhilipOlsson and @murrant have summed the response to this well.
