### ISSUE TITLE
PHP Errors after JAN 26 udpate...

### ISSUE THREAD

**Issue by plazarch** [librenms/librenms#2871]
After the JAN 26 update LibreNMS started clocking trying to load pages.  Set up debugging, sql debug looks ok.  PHP Debug has MANY errors.  I completely deleted the librenms directory and did a git clone and fresh install with no improvement:

Array ( [errno] => 8 [errstr] => Undefined index: influxdb [errfile] => /opt/librenms/includes/influxdb.inc.php [errline] => 15 )
Array ( [errno] => 8 [errstr] => Undefined offset: 1 [errfile] => /opt/librenms/html/includes/vars.inc.php [errline] => 29 )
Array ( [errno] => 8 [errstr] => Use of undefined constant yes - assumed 'yes' [errfile] => /opt/librenms/html/includes/vars.inc.php [errline] => 31 )
Array ( [errno] => 8 [errstr] => Undefined offset: 1 [errfile] => /opt/librenms/html/includes/vars.inc.php [errline] => 29 )
Array ( [errno] => 8 [errstr] => Use of undefined constant yes - assumed 'yes' [errfile] => /opt/librenms/html/includes/vars.inc.php [errline] => 31 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchrows_sec [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 276 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchrows [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 277 )
Array ( [errno] => 8 [errstr] => Undefined index: sess_id [errfile] => /opt/librenms/html/includes/authenticate.inc.php [errline] => 65 )
Array ( [errno] => 8 [errstr] => Undefined index: token [errfile] => /opt/librenms/html/includes/authenticate.inc.php [errline] => 65 )
Array ( [errno] => 8 [errstr] => Undefined offset: 1 [errfile] => /opt/librenms/html/includes/authentication/mysql.inc.php [errline] => 38 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchrow_sec [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 331 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchrow [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 332 )
Array ( [errno] => 8 [errstr] => Undefined variable: navbar [errfile] => /opt/librenms/html/includes/print-menubar.php [errline] => 26 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchcell_sec [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 365 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchcell [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 366 )
Array ( [errno] => 8 [errstr] => Undefined variable: param [errfile] => /opt/librenms/html/includes/print-menubar.php [errline] => 139 )
Array ( [errno] => 8 [errstr] => Undefined index: _ObjCacheSkell [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 47 )
Array ( [errno] => 8 [errstr] => Undefined index: _ObjCache [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 51 )
Array ( [errno] => 8 [errstr] => Undefined index: ports [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 60 )
Array ( [errno] => 8 [errstr] => Undefined index: params [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 98 )
Array ( [errno] => 8 [errstr] => Undefined index: params [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 98 )
Array ( [errno] => 8 [errstr] => Undefined variable: used_sensors [errfile] => /opt/librenms/html/includes/print-menubar.php [errline] => 333 )
Array ( [errno] => 8 [errstr] => Undefined variable: sep [errfile] => /opt/librenms/html/includes/print-menubar.php [errline] => 357 )
Array ( [errno] => 8 [errstr] => Undefined variable: sep [errfile] => /opt/librenms/html/includes/print-menubar.php [errline] => 369 )
Array ( [errno] => 2 [errstr] => array_keys() expects parameter 1 to be array, null given [errfile] => /opt/librenms/html/includes/print-menubar.php [errline] => 374 )
Array ( [errno] => 2 [errstr] => Invalid argument supplied for foreach() [errfile] => /opt/librenms/html/includes/print-menubar.php [errline] => 374 )
Array ( [errno] => 8 [errstr] => Undefined index: menu [errfile] => /opt/librenms/html/includes/plugins.inc.php [errline] => 49 )
Array ( [errno] => 8 [errstr] => Undefined index: notifications [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 60 )
Array ( [errno] => 8 [errstr] => Undefined index: params [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 98 )
29 total PHP issues / errors.

Should have added this:
Running on Ubuntu 12.04.5 LTS (latest updates)

root@web002:/opt/librenms# ./validate.php 
Version info:
Commit SHA: 3e97875d77fd02104dd6060f6260e394adaea673
DB Schema: 94
PHP: 5.3.10-1ubuntu3.21
MySQL: 5.5.47-0ubuntu0.12.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.4.3

[OK]      Database connection successful
[OK]      fping has been found

**Comment by f0o** [comment]
Undefined index are no errors but merely notices.

On 27 January 2016 14:38:22 CET, plazarch <notifications@github.com> wrote:
>After the JAN 26 update LibreNMS started clocking trying to load pages 
>Set up debugging, sql debug looks ok  PHP Debug has MANY errors  I
>completely deleted the librenms directory and did a git clone and fresh
>install with no improvement:
>
>Array ( [errno] => 8 [errstr] => Undefined index: influxdb [errfile] =>
>/opt/librenms/includes/influxdbincphp [errline] => 15 )
>Array ( [errno] => 8 [errstr] => Undefined offset: 1 [errfile] =>
>/opt/librenms/html/includes/varsincphp [errline] => 29 )
>Array ( [errno] => 8 [errstr] => Use of undefined constant yes -
>assumed 'yes' [errfile] => /opt/librenms/html/includes/varsincphp
>[errline] => 31 )
>Array ( [errno] => 8 [errstr] => Undefined offset: 1 [errfile] =>
>/opt/librenms/html/includes/varsincphp [errline] => 29 )
>Array ( [errno] => 8 [errstr] => Use of undefined constant yes -
>assumed 'yes' [errfile] => /opt/librenms/html/includes/varsincphp
>[errline] => 31 )
>Array ( [errno] => 8 [errstr] => Undefined index: fetchrows_sec
>[errfile] => /opt/librenms/includes/dbFacilemysqliphp [errline] => 276
>)
>Array ( [errno] => 8 [errstr] => Undefined index: fetchrows [errfile]
>=> /opt/librenms/includes/dbFacilemysqliphp [errline] => 277 )
>Array ( [errno] => 8 [errstr] => Undefined index: sess_id [errfile] =>
>/opt/librenms/html/includes/authenticateincphp [errline] => 65 )
>Array ( [errno] => 8 [errstr] => Undefined index: token [errfile] =>
>/opt/librenms/html/includes/authenticateincphp [errline] => 65 )
>Array ( [errno] => 8 [errstr] => Undefined offset: 1 [errfile] =>
>/opt/librenms/html/includes/authentication/mysqlincphp [errline] => 38
>)
>Array ( [errno] => 8 [errstr] => Undefined index: fetchrow_sec
>[errfile] => /opt/librenms/includes/dbFacilemysqliphp [errline] => 331
>)
>Array ( [errno] => 8 [errstr] => Undefined index: fetchrow [errfile] =>
>/opt/librenms/includes/dbFacilemysqliphp [errline] => 332 )
>Array ( [errno] => 8 [errstr] => Undefined variable: navbar [errfile]
>=> /opt/librenms/html/includes/print-menubarphp [errline] => 26 )
>Array ( [errno] => 8 [errstr] => Undefined index: fetchcell_sec
>[errfile] => /opt/librenms/includes/dbFacilemysqliphp [errline] => 365
>)
>Array ( [errno] => 8 [errstr] => Undefined index: fetchcell [errfile]
>=> /opt/librenms/includes/dbFacilemysqliphp [errline] => 366 )
>Array ( [errno] => 8 [errstr] => Undefined variable: param [errfile] =>
>/opt/librenms/html/includes/print-menubarphp [errline] => 139 )
>Array ( [errno] => 8 [errstr] => Undefined index: _ObjCacheSkell
>[errfile] => /opt/librenms/includes/object-cacheincphp [errline] => 47
>)
>Array ( [errno] => 8 [errstr] => Undefined index: _ObjCache [errfile]
>=> /opt/librenms/includes/object-cacheincphp [errline] => 51 )
>Array ( [errno] => 8 [errstr] => Undefined index: ports [errfile] =>
>/opt/librenms/includes/object-cacheincphp [errline] => 60 )
>Array ( [errno] => 8 [errstr] => Undefined index: params [errfile] =>
>/opt/librenms/includes/object-cacheincphp [errline] => 98 )
>Array ( [errno] => 8 [errstr] => Undefined index: params [errfile] =>
>/opt/librenms/includes/object-cacheincphp [errline] => 98 )
>Array ( [errno] => 8 [errstr] => Undefined variable: used_sensors
>[errfile] => /opt/librenms/html/includes/print-menubarphp [errline] =>
>333 )
>Array ( [errno] => 8 [errstr] => Undefined variable: sep [errfile] =>
>/opt/librenms/html/includes/print-menubarphp [errline] => 357 )
>Array ( [errno] => 8 [errstr] => Undefined variable: sep [errfile] =>
>/opt/librenms/html/includes/print-menubarphp [errline] => 369 )
>Array ( [errno] => 2 [errstr] => array_keys() expects parameter 1 to be
>array, null given [errfile] =>
>/opt/librenms/html/includes/print-menubarphp [errline] => 374 )
>Array ( [errno] => 2 [errstr] => Invalid argument supplied for
>foreach() [errfile] => /opt/librenms/html/includes/print-menubarphp
>[errline] => 374 )
>Array ( [errno] => 8 [errstr] => Undefined index: menu [errfile] =>
>/opt/librenms/html/includes/pluginsincphp [errline] => 49 )
>Array ( [errno] => 8 [errstr] => Undefined index: notifications
>[errfile] => /opt/librenms/includes/object-cacheincphp [errline] => 60
>)
>Array ( [errno] => 8 [errstr] => Undefined index: params [errfile] =>
>/opt/librenms/includes/object-cacheincphp [errline] => 98 )
>29 total PHP issues / errors
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2871

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by plazarch** [comment]
Ok, any other explanation for why pages wont' fully load?  Browser just 
keeps clocking until it reaches the meta refresh time, refreshes and 
keeps clocking.  On pages with graphs no graphs are drawn.

On 01/27/2016 07:56 AM, Daniel Preussker wrote:
> Undefined index are no errors but merely notices.
>
> On 27 January 2016 14:38:22 CET, plazarch <notifications@github.com> 
> wrote:
> >After the JAN 26 update LibreNMS started clocking trying to load pages
> >Set up debugging, sql debug looks ok PHP Debug has MANY errors I
> >completely deleted the librenms directory and did a git clone and fresh
> >install with no improvement:
> >
> >Array ( [errno] => 8 [errstr] => Undefined index: influxdb [errfile] =>
> >/opt/librenms/includes/influxdbincphp [errline] => 15 )
> >Array ( [errno] => 8 [errstr] => Undefined offset: 1 [errfile] =>
> >/opt/librenms/html/includes/varsincphp [errline] => 29 )
> >Array ( [errno] => 8 [errstr] => Use of undefined constant yes -
> >assumed 'yes' [errfile] => /opt/librenms/html/includes/varsincphp
> >[errline] => 31 )
> >Array ( [errno] => 8 [errstr] => Undefined offset: 1 [errfile] =>
> >/opt/librenms/html/includes/varsincphp [errline] => 29 )
> >Array ( [errno] => 8 [errstr] => Use of undefined constant yes -
> >assumed 'yes' [errfile] => /opt/librenms/html/includes/varsincphp
> >[errline] => 31 )
> >Array ( [errno] => 8 [errstr] => Undefined index: fetchrows_sec
> >[errfile] => /opt/librenms/includes/dbFacilemysqliphp [errline] => 276
> >)
> >Array ( [errno] => 8 [errstr] => Undefined index: fetchrows [errfile]
> >=> /opt/librenms/includes/dbFacilemysqliphp [errline] => 277 )
> >Array ( [errno] => 8 [errstr] => Undefined index: sess_id [errfile] =>
> >/opt/librenms/html/includes/authenticateincphp [errline] => 65 )
> >Array ( [errno] => 8 [errstr] => Undefined index: token [errfile] =>
> >/opt/librenms/html/includes/authenticateincphp [errline] => 65 )
> >Array ( [errno] => 8 [errstr] => Undefined offset: 1 [errfile] =>
> >/opt/librenms/html/includes/authentication/mysqlincphp [errline] => 38
> >)
> >Array ( [errno] => 8 [errstr] => Undefined index: fetchrow_sec
> >[errfile] => /opt/librenms/includes/dbFacilemysqliphp [errline] => 331
> >)
> >Array ( [errno] => 8 [errstr] => Undefined index: fetchrow [errfile] =>
> >/opt/librenms/includes/dbFacilemysqliphp [errline] => 332 )
> >Array ( [errno] => 8 [errstr] => Undefined variable: navbar [errfile]
> >=> /opt/librenms/html/includes/print-menubarphp [errline] => 26 )
> >Array ( [errno] => 8 [errstr] => Undefined index: fetchcell_sec
> >[errfile] => /opt/librenms/includes/dbFacilemysqliphp [errline] => 365
> >)
> >Array ( [errno] => 8 [errstr] => Undefined index: fetchcell [errfile]
> >=> /opt/librenms/includes/dbFacilemysqliphp [errline] => 366 )
> >Array ( [errno] => 8 [errstr] => Undefined variable: param [errfile] =>
> >/opt/librenms/html/includes/print-menubarphp [errline] => 139 )
> >Array ( [errno] => 8 [errstr] => Undefined index: _ObjCacheSkell
> >[errfile] => /opt/librenms/includes/object-cacheincphp [errline] => 47
> >)
> >Array ( [errno] => 8 [errstr] => Undefined index: _ObjCache [errfile]
> >=> /opt/librenms/includes/object-cacheincphp [errline] => 51 )
> >Array ( [errno] => 8 [errstr] => Undefined index: ports [errfile] =>
> >/opt/librenms/includes/object-cacheincphp [errline] => 60 )
> >Array ( [errno] => 8 [errstr] => Undefined index: params [errfile] =>
> >/opt/librenms/includes/object-cacheincphp [errline] => 98 )
> >Array ( [errno] => 8 [errstr] => Undefined index: params [errfile] =>
> >/opt/librenms/includes/object-cacheincphp [errline] => 98 )
> >Array ( [errno] => 8 [errstr] => Undefined variable: used_sensors
> >[errfile] => /opt/librenms/html/includes/print-menubarphp [errline] =>
> >333 )
> >Array ( [errno] => 8 [errstr] => Undefined variable: sep [errfile] =>
> >/opt/librenms/html/includes/print-menubarphp [errline] => 357 )
> >Array ( [errno] => 8 [errstr] => Undefined variable: sep [errfile] =>
> >/opt/librenms/html/includes/print-menubarphp [errline] => 369 )
> >Array ( [errno] => 2 [errstr] => array_keys() expects parameter 1 to be
> >array, null given [errfile] =>
> >/opt/librenms/html/includes/print-menubarphp [errline] => 374 )
> >Array ( [errno] => 2 [errstr] => Invalid argument supplied for
> >foreach() [errfile] => /opt/librenms/html/includes/print-menubarphp
> >[errline] => 374 )
> >Array ( [errno] => 8 [errstr] => Undefined index: menu [errfile] =>
> >/opt/librenms/html/includes/pluginsincphp [errline] => 49 )
> >Array ( [errno] => 8 [errstr] => Undefined index: notifications
> >[errfile] => /opt/librenms/includes/object-cacheincphp [errline] => 60
> >)
> >Array ( [errno] => 8 [errstr] => Undefined index: params [errfile] =>
> >/opt/librenms/includes/object-cacheincphp [errline] => 98 )
> >29 total PHP issues / errors
> >
> >
> >---
> >Reply to this email directly or view it on GitHub:
> >https://github.com/librenms/librenms/issues/2871
>
> -- 
> Sent from my Android device with K-9 Mail. Please excuse my brevity.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/librenms/librenms/issues/2871#issuecomment-175638638>.Web 
> Bug from 
> https://github.com/notifications/beacon/AQIrBAQlH6xFO1J4MOC80jO75WhASbxtks5peMQggaJpZM4HNad7.gif
>
>
> -- 
> This message has been scanned for viruses and
> dangerous content by *MailScanner* <http://www.mailscanner.info/>, and is
> believed to be clean. 


-- 
This message has been scanned for viruses and
dangerous content by MailScanner, and is
believed to be clean.

**Comment by arjitc** [comment]
Running out of PHP memory by chance?

**Comment by laf** [comment]
check your system logs and check what running processes you have.

Current code base works on countless systems so this will be specific to your env.

**Comment by plazarch** [comment]
I don't think it is:

memory_limit = 700M

and everything was working fine for a little over a year on Observium 
and for the past week on LibreNMS until the auto update last night / 
this morning.

I only have 5 hosts monitoring, and since I did a clean install I only 
have the localhost being monitored.

On 01/27/2016 09:57 AM, Arjit Chaudhary wrote:
>
> Running out of PHP memory by chance?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/librenms/librenms/issues/2871#issuecomment-175705474>.Web 
> Bug from 
> https://github.com/notifications/beacon/AQIrBPdgO5AjlOCn0aWVvAipg59zk211ks5peOB_gaJpZM4HNad7.gif
>
>
> -- 
> This message has been scanned for viruses and
> dangerous content by *MailScanner* <http://www.mailscanner.info/>, and is
> believed to be clean. 


-- 
This message has been scanned for viruses and
dangerous content by MailScanner, and is
believed to be clean.

**Comment by plazarch** [comment]
Sorry to waste everyones time.  I was a dumba$$ and didn't do the 1 
piece of troubleshooting that ended up being the issue.  Restarted my 
browser and it all started working.  Thank you all for the quick replies 
though.


On 01/27/2016 10:18 AM, Paul T. Lazarchik wrote:
> I don't think it is:
>
> memory_limit = 700M
>
> and everything was working fine for a little over a year on Observium 
> and for the past week on LibreNMS until the auto update last night / 
> this morning.
>
> I only have 5 hosts monitoring, and since I did a clean install I only 
> have the localhost being monitored.
>
> On 01/27/2016 09:57 AM, Arjit Chaudhary wrote:
>>
>> Running out of PHP memory by chance?
>>
>> —
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/librenms/librenms/issues/2871#issuecomment-175705474>.Web 
>> Bug from 
>> https://github.com/notifications/beacon/AQIrBPdgO5AjlOCn0aWVvAipg59zk211ks5peOB_gaJpZM4HNad7.gif
>>
>>
>> -- 
>> This message has been scanned for viruses and
>> dangerous content by *MailScanner* <http://www.mailscanner.info/>, 
>> and is
>> believed to be clean. 
>


-- 
This message has been scanned for viruses and
dangerous content by MailScanner, and is
believed to be clean.

**Comment by laf** [comment]
No problem, glad it's sorted.
