### ISSUE TITLE
Calix E7 DSL/GPON Integration?

### ISSUE THREAD

**Issue by cchance27** [librenms/librenms#2873]
Right now their being detected as generic devices, none of the dsl or gpon interfaces are detected, any chance someone can look into adding them 
[snmp-mibs.zip](https://github.com/librenms/librenms/files/107077/snmp-mibs.zip)

Mibs are attached

**Comment by laf** [comment]
We need the output from:

./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -r -f -d -m os

**Comment by murrant** [comment]
This is an E7 with just ethernet interfaces, I can provide both DSL and GPON outputs if needed.
Discovery: http://pastebin.com/1YDP2E6m
Poller: http://pastebin.com/6czYRuzm
SNMPwalk: http://pastebin.com/MFJWgz7w

**Comment by cchance27** [comment]
From a E7 with VDSL

Discovery: http://pastebin.com/hLBnxxpK
Poller: http://pastebin.com/gymyeVXe

**Comment by Rosiak** [comment]
@murrant Is on this.

**Comment by murrant** [comment]
I haven't started on it but I did research graphing xDSL data on xDSL ports.  Here are my notes:
**Displayable xDSL variables**
e7VdslPortLineState.20101
e7VdslPortStatsProtocol.20101
e7VdslPhysTransmissionMode.20101.upstream
e7VdslPhysTransmissionMode.20101.downstream

**Graphable xDSL variables**
e7VdslPortCurrTxRate.20101
e7VdslPortCurrRxRate.20101
e7VdslPhysCurrSnrMargin.20101.upstream
e7VdslPhysCurrSnrMargin.20101.downstream
e7VdslPhysCurrAtn.20101.downstream
e7VdslPhysCurrAtn.20101.upstream
e7VdslPhysCurrOutputPwr.20101.downstream
e7VdslPhysCurrOutputPwr.20101.upstream
e7VdslPhysInterleaveDelay.20101.downstream
e7VdslPhysInterleaveDelay.20101.upstream
e7VdslPhysImpulseNoiseProtection.20101.downstream
e7VdslPhysImpulseNoiseProtection.20101.upstream

**Comment by Rosiak** [comment]
@murrant Do you know if we can close this?

**Comment by murrant** [comment]
We have basic Ethernet stats from these ports.  But not DSL/fiber stats.  So maybe.

There is also an issue with port poll time.  These devices can have hundreds of ports.  But that should probably be a separate issue.

**Comment by Rosiak** [comment]
Think we should keep this one open or?
