### ISSUE TITLE
Memory not discovered for ESXi 6.0 hosts

### ISSUE THREAD

**Issue by mtehonica** [librenms/librenms#2876]
VMware ESXi 6.0 hosts are not discovering/collecting/displaying memory utilization information.  It doesn't display any sort of memory info for the hosts, no memory graph at all (as opposed to having a blank graph or an error on the graph).  I can provide any necessary troubleshooting info, just let me know what is useful.

**Comment by Rosiak** [comment]
Struggling to find the right OIDs in ESX 6.0.

HOST-RESOURCES-MIB is useless in this case.

@librenms/reviewers Any input?

**Comment by mtehonica** [comment]
Does this help at all?

http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1013445

**Comment by tylerapplebaum** [comment]
Mine is working fine.

![2016-02-01 13_25_53-am-esxi-01 - health - librenms](https://cloud.githubusercontent.com/assets/8419153/12731780/60a11e70-c8e7-11e5-9c7a-c8cbc3f5e7cf.png)

**Comment by Rosiak** [comment]
@tylerapplebaum 
I suppose that's not ESX 6.0?

**Comment by tylerapplebaum** [comment]
It sure is.

[root@ESXi-01:~] vmware -vl
VMware ESXi 6.0.0 build-2494585
VMware ESXi 6.0.0 GA
[root@ESXi-01:~]

**Comment by Rosiak** [comment]
Odd.
No work on:
```
VMware ESXi 6.0.0 build-2809209
VMware ESXi 6.0.0 GA
```

**Comment by mtehonica** [comment]
Very odd.
No workie on:
`[root@esxi01:~] vmware -vl`
`VMware ESXi 6.0.0 build-3029758`
`VMware ESXi 6.0.0 Update 1`

**Comment by tylerapplebaum** [comment]
The difference may be that I have the ESXi Host Client fling installed. Other than that it's a stock ESXi install.

**Comment by mtehonica** [comment]
Can host memory information possibly be discovered through vCenter (as long as you discover your vCenter server through LibreNMS, of course)?

**Comment by novakin** [comment]
I have no graph at all with lastest ESXI

`VMware ESXi 6.0.0 build-3380124
VMware ESXi 6.0.0 Update 1
`

**Comment by hackman61** [comment]
Same problem, in  	VMware ESXi 6.0.0 (build-3620759)  version .

**Comment by realgreef** [comment]
Same problem here also, VMware ESXi 6.0.0 (build-3620759) version

**Comment by f0o** [comment]
Can it reproduce with VMware ESXi 6.0.0 (build-3620759)

**Comment by hackman61** [comment]
@tylerapplebaum I have just added ESXi Host Client fling installed , no change for me.
 I precise that it is Dell image of esxi, I don't know if it can help.

**Comment by f0o** [comment]
@hackman61 whats the precise version string of it?

**Comment by zimmertr** [comment]
Does not work for me either on:

Version: 2016.03.02
Build number: 3617585
Build type: release
Branch: vsphere60u2

**Comment by crcro** [comment]
if you have vcenter 6u2 there is a known bug that stops snmp after 2 polls, it is supposed to be fixed in the next release

**Comment by laf** [comment]
If someone with a non-working setup can provide `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .` that might help.

**Comment by zimmertr** [comment]
@laf https://gist.github.com/zimmertr/d2ebb8214386323dfcdbf0525f4baa62

**Comment by hackman61** [comment]
https://gist.github.com/hackman61/f6b182f37a440456bdc2f1d694d48930

**Comment by laf** [comment]
Thanks for both of these. They don't report the memory as we expect.

Can you see if an `snmpwalk against .1.3.6.1.4.1.6876.3.2.1` provides anything?

**Comment by Rosiak** [comment]
I'm pretty confident this is an issue with VMware, at least it was last time I tested.
So not much to do from our side.

**Comment by laf** [comment]
That OID is specific to vmware mib, if it contains what we need then we can fix it. If not then it's not something we can fix.

**Comment by crcro** [comment]
https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2144598

**Comment by laf** [comment]
lol well found @crcro.

Closing for now, if someone checks the OID I posted above and it works then comment back and we'll re-open.

**Comment by f0o** [comment]
#5774 Reopening!

**Comment by f0o** [comment]
so quick walk shows me:

SNMPv2-SMI::enterprises.6876.3.2.1.0 Returns available Memory (VMWare MIB)
HOST-RESOURCES-MIB::hrMemorySize.0 Returns available Memory as well

hrStorage has no `Real Memory` entry.

My version: VMware ESXi 6.0.0 build-3620759

**Comment by crcro** [comment]
i think that this is a known bug of esxi 5.5.x and 6.0.x

**Comment by crcro** [comment]
vm kb: 2144598

**Comment by laf** [comment]
Closing again, no further discussion and the issue has already been covered
