### ISSUE TITLE
Rename graphs on dashboards

### ISSUE THREAD

**Issue by mtehonica** [librenms/librenms#2877]
I would love to be able to rename the graphs (titles) on dashboards.  For example, instead of 192.168.1.1 / port_bits, I'd like to name this WAN.  Or instead of, esxi01 / device_processor, I'd like to rename it ESXi01 CPU Utilization.

**Comment by f0o** [comment]
Should be easy to do, might have time for it during lunch tomorrow

**Comment by mtehonica** [comment]
Working great, much appreciated!
