### ISSUE TITLE
Add BDCOM detection

### ISSUE THREAD

**Issue by tobiasa1** [librenms/librenms#2878]
Our BDCOM switches are not detected with logo/device type/health.

Please let me know if you need remote access for troubleshooting.

First 50 lines from snmpwalk:
```
iso.3.6.1.2.1.1.1.0 = STRING: "BDCOM(tm) S2524C Software, Version 2.1.0A Build 5721
Compiled: 2011-11-1 15:57:26 by SYS
ROM: System Bootstrap,Version 0.3.2,Serial num:27072980
"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.3320.1.185.0
iso.3.6.1.2.1.1.3.0 = Timeticks: (2841269636) 328 days, 20:24:56.36
iso.3.6.1.2.1.1.4.0 = STRING: "my syscontact"
iso.3.6.1.2.1.1.5.0 = STRING: "my hostname"
iso.3.6.1.2.1.1.6.0 = STRING: "my syslocation"
iso.3.6.1.2.1.1.7.0 = INTEGER: 2
iso.3.6.1.2.1.1.8.0 = Timeticks: (2841269637) 328 days, 20:24:56.37
iso.3.6.1.2.1.1.9.1.2.1 = OID: iso.3.6.1.4.1.3320.1.185.0
iso.3.6.1.2.1.1.9.1.3.1 = STRING: "BDCOM(tm) S2524C Software, Version 2.1.0A Build 5721
Compiled: 2011-11-1 15:57:26 by SYS
ROM: System Bootstrap,Version 0.3.2,Serial num:27072980
"
iso.3.6.1.2.1.1.9.1.4.1 = Timeticks: (2841269638) 328 days, 20:24:56.38
iso.3.6.1.2.1.2.1.0 = INTEGER: 25
iso.3.6.1.2.1.2.2.1.1.1 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.1.2 = INTEGER: 2
iso.3.6.1.2.1.2.2.1.1.3 = INTEGER: 3
iso.3.6.1.2.1.2.2.1.1.4 = INTEGER: 4
iso.3.6.1.2.1.2.2.1.1.5 = INTEGER: 5
iso.3.6.1.2.1.2.2.1.1.6 = INTEGER: 6
iso.3.6.1.2.1.2.2.1.1.7 = INTEGER: 7
iso.3.6.1.2.1.2.2.1.1.8 = INTEGER: 8
iso.3.6.1.2.1.2.2.1.1.9 = INTEGER: 9
iso.3.6.1.2.1.2.2.1.1.10 = INTEGER: 10
iso.3.6.1.2.1.2.2.1.1.11 = INTEGER: 11
iso.3.6.1.2.1.2.2.1.1.12 = INTEGER: 12
iso.3.6.1.2.1.2.2.1.1.13 = INTEGER: 13
iso.3.6.1.2.1.2.2.1.1.14 = INTEGER: 14
iso.3.6.1.2.1.2.2.1.1.15 = INTEGER: 15
iso.3.6.1.2.1.2.2.1.1.16 = INTEGER: 16
iso.3.6.1.2.1.2.2.1.1.17 = INTEGER: 17
iso.3.6.1.2.1.2.2.1.1.18 = INTEGER: 18
iso.3.6.1.2.1.2.2.1.1.19 = INTEGER: 19
iso.3.6.1.2.1.2.2.1.1.20 = INTEGER: 20
iso.3.6.1.2.1.2.2.1.1.21 = INTEGER: 21
iso.3.6.1.2.1.2.2.1.1.22 = INTEGER: 22
iso.3.6.1.2.1.2.2.1.1.23 = INTEGER: 23
iso.3.6.1.2.1.2.2.1.1.24 = INTEGER: 24
iso.3.6.1.2.1.2.2.1.1.25 = INTEGER: 25
iso.3.6.1.2.1.2.2.1.2.1 = STRING: "GigaEthernet0/1"
iso.3.6.1.2.1.2.2.1.2.2 = STRING: "GigaEthernet0/2"
iso.3.6.1.2.1.2.2.1.2.3 = STRING: "GigaEthernet0/3"
iso.3.6.1.2.1.2.2.1.2.4 = STRING: "GigaEthernet0/4"
iso.3.6.1.2.1.2.2.1.2.5 = STRING: "GigaEthernet0/5"
iso.3.6.1.2.1.2.2.1.2.6 = STRING: "GigaEthernet0/6"
iso.3.6.1.2.1.2.2.1.2.7 = STRING: "GigaEthernet0/7"
```

**Comment by Rosiak** [comment]
Please provide a full walk.

**Comment by tobiasa1** [comment]
@Rosiak 
https://0bin.net/paste/E0wXKG-mxaE1LKd6#4cYWmYtqMjqzZIcBs6Hpwcr+Dp2AJWhVgkJup5hQ-sL

**Comment by Rosiak** [comment]
Mailed them regarding the logo.
Will see if I can come up with some regex foo.

**Comment by laf** [comment]
What's the actual OS on the device called as bdcom is the hardware vendor.

**Comment by tobiasa1** [comment]
@laf 
I haven't seen any name on the OS. I think it's just called BDCOM OS or BDOS.

```
A2#show version 
BDCOM(tm) S2524C Software, Version 2.1.0A Build 5721
Copyright by Shanghai Baud Data Communication CO. LTD.
Compiled: 2011-11-1 15:57:26 by SYS_5721, Image text-base: 0x80008000
ROM: System Bootstrap, Version 0.3.2, Serial num:S27072980
System image file is "Switch.bin"
(RISC) processor with 65536K bytes of memory, 8192K bytes of flash
```

**Comment by PhilipOlsson** [comment]
BDCOM have a lot of different ways to identify their OS, it is not really consistent and their boxes are frequently relabeled, for example this is a ''Teleste G48S' that really is a BDCOM.


SNMPv2-MIB::sysDescr.0 = STRING: Teleste Corporation Internetwork Operating System Software
G48S Series Software, Version 2.1.1B Build 31848, RELEASE SOFTWARE
Compiled: 2015-11-26 18:0:32 by SYS
ROM: System Bootstrap, Version 0.3.8
Serial num:S25060775, ID num:25060775

SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.3320.1.143.0
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (54820388) 6 days, 8:16:43.88
SNMPv2-MIB::sysContact.0 = STRING:
SNMPv2-MIB::sysName.0 = STRING: superduperswitch
SNMPv2-MIB::sysLocation.0 = STRING:
SNMPv2-MIB::sysServices.0 = INTEGER: 2
SNMPv2-MIB::sysORLastChange.0 = Timeticks: (54820389) 6 days, 8:16:43.89
SNMPv2-MIB::sysORID.1 = OID: SNMPv2-SMI::enterprises.3320.1.143.0
SNMPv2-MIB::sysORDescr.1 = STRING: Teleste Corporation Internetwork Operating System Software
G48S Series Software, Version 2.1.1B Build 31848, RELEASE SOFTWARE
Compiled: 2015-11-26 18:0:32 by SYS
ROM: System Bootstrap, Version 0.3.8
Serial num:S25060775, ID num:25060775


SysObjectID is probably the most reliable?

**Comment by tobiasa1** [comment]
Any update?

**Comment by laf** [comment]
Merged.
