### ISSUE TITLE
More widget options for dashboards

### ISSUE THREAD

**Issue by mtehonica** [librenms/librenms#2879]
It would be great if there were more widget options for the dashboards.  A few that come to mind are some type of "gauge", similar to a gas gauge/circle, that would "fill up" from 0% to 100% for things like storage device utilization.  Also, maybe something simple like a box that changes color based on values, 0-30% is red, 30-70% is yellow and 70+ is green.

These are two options that come from using Dashing and the different options they provide.

**Comment by f0o** [comment]
Something like: http://webshifted.com/sGlide/ ?

**Comment by mtehonica** [comment]
Yup, I could deal with those.

**Comment by florianbeer** [comment]
You can enable [InfluxDB exports](http://docs.librenms.org/Extensions/InfluxDB/) of LibreNMS data and then construct your Dashboard (even multiple rotating ones) in [Grafana](http://grafana.org/download/). It's should be a pretty straightforward setup and you'd immediately get all the graphing options you could wish for.

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #175](https://github.com/librenms/librenmsv2/issues/175) via [**ZenHub**](https://www.zenhub.com/)
