### ISSUE TITLE
NaN representations

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#2883]
Slightly annoyed by these.

But, can we do it different, pros/cons?
![screen shot 2016-01-28 at 23 55 42](https://cloud.githubusercontent.com/assets/6378934/12661588/c1a42764-c61a-11e5-9550-ec97dd0fcdec.png)

**Comment by laf** [comment]
Annoyed by which bit? It displaying NaNV?

**Comment by Rosiak** [comment]
The fact that the color is red and that it's displaying NaN rather than 0.
Disclaimer: Have not looked at the code at all.

**Comment by SaaldjorMike** [comment]
I have several sensors where the low+high limits are returning the same values (which is bogus), which gives a red colour also. Maybe we should change the default colour if we don't know actual limits?
