### ISSUE TITLE
Unexpected behavior in Create new alert rule

### ISSUE THREAD

**Issue by kaorukit** [librenms/librenms#2885]
I config new alert rule.
![2626687-efd8228aa7f6a84f0f474f547730d8c3e8885d4e](https://cloud.githubusercontent.com/assets/16931225/12671687/c0d58522-c6b4-11e5-858c-acc550606ed7.png)

modified it.
![2626689-d8f44acc466a3dd50498909aa0bbaa7269151245](https://cloud.githubusercontent.com/assets/16931225/12671691/c5bcdc70-c6b4-11e5-83e7-50fb4033b765.png)

green tag is separate.
do you have any ideas?

**Comment by laf** [comment]
Is your ifAlias genuinely uplink|wan or are you searching for ifAlias that is uplink OR wan?

**Comment by f0o** [comment]
I can reproduce this cosmetic issue. It doesnt rewrite the rule though (at least not for me)

**Comment by kaorukit** [comment]
@laf I want  searching for uplink OR wan.
@f0o thank you for reproduce. will you fixed this issue?

**Comment by f0o** [comment]
Well if the separation of the term in the UI is what annoys you then I'm not sure I can fix it.
I'm terrible with javascript haha.

However, I'm sure someone else can pick this up :)

**Comment by kaorukit** [comment]
@f0o haha. i see!
I am waiting expectantly!

**Comment by laf** [comment]
Was fixed and merged
