### ISSUE TITLE
Discovery failures not visible on librenms interface

### ISSUE THREAD

**Issue by khobbits** [librenms/librenms#2886]
Librenms does a good job of being able to find and add other connected network devices, sometimes however it fails, by no fault of it's own.

This is often because the hostname of a machine doesn't match it's dns, or maybe because while the device has lldp enabled, it doesn't have snmp turned on.

I'd like to see a page on the web interface which lists all the devices the discovery process finds, and tries to scan (excluding those matching the existing config.php discovery exclusions).

Relevant information would be:
"device name" "[device information/ip/hostname]" "source device name" "source device port"

This would allow you to go out, chase a cable, and fix up your badly configured network device, that somehow made it onto your network, without a valid ip address, or stock hostname.

This would also allow users to tidy up their discovery, by realising that librenms is trying to scan devices that it will not be able to find, allowing users to explicitly ignore them in the config.php

Edit:
@laf seems to think the discovery failures, is a bug, and should be displayed on the event log.

**Comment by laf** [comment]
Is the information in eventlog not enough for this? I'm not sure building an entire page just to show that info is worth it if it's there already?

**Comment by khobbits** [comment]
Is there a way to see this information in the event log?  What filter would I use?

**Comment by laf** [comment]
"discovery of" I think should show it, you can be more specific based on the type of protocol used but if you try that first then whittle it down.

**Comment by khobbits** [comment]
I don't believe these discovery failures are being properly logged.  Searching for a device that has failed, doesn't show up in the log at all, and "discovery of" returned no matches.

Shall we classify this as a logging bug, and I'll open a different issue regarding the possible interface addition?

**Comment by Misch-** [comment]
I also don't see any discovery failures being logged searching for that, or any events about discovery in the event log at all for that matter. 

I'd really like a solution to know about devices that are on your network but not responding to SNMP, so they can be fixed or added to an ignore list. I think some consideration needs to be made, so that a user can have an entire view of devices on their network. I think I'm going to be diving in and implementing this in one way or another. Thoughts?

**Comment by laf** [comment]
We already try and log about these but includes/discovery/functions.inc.php line 68 but it also probably needs adding to an else on line 72.

However you won't get specific information about it being snmp, dns or anything like that merely just that it failed to add. The addHost function doesn't return that type of info so if you needed it that would also need updating.

You're more than welcome to contribute something like this.

**Comment by Misch-** [comment]
Made the small change you mentioned and this works good enough for me now. Thanks!

https://github.com/librenms/librenms/pull/3759

**Comment by khobbits** [comment]
Along with having this information available (currently hidden away where nobody will find it), I think it's somewhat important to draw attention to it.

There are a few reasons for this:
- The current status makes librenms look incompetent - I had a colleague try to install this on another site, and it's auto discovery failed to make some important jumps due to hostname mismatches.  This incomplete status, with the user trying to 'fix' the scan by manually adding an additional 5 hosts, but still missing network convergence on the network map, made this product look flawed, when in truth, it was his inconsistent naming.
- Network growth - Networks grow naturally, you might not always remember to add devices to librenms manually, but if something is slightly off with configuration it may not show up automatically (my engineers often forget to update the internal dns with new switch hostnames)
- Network security - While this one is less important, because it's easier to hide a switch/device on the network.  If someone adds a rouge network device to the network, that librenms can see via discovery, this being highlighted on the interface could save the day.

I would imagine this working by having another option in the devices menu, along with a number, similar to how 'errored' ports show up in the port menu.  This would at least highlight there are install problems to resolve.

Additionally, some people might have a large number of devices being detected, like workstations or phones they may not specifically want showing up, and will not show up for some reason.  Having a large number of these devices slows down discovery significantly, and resolving these, by say ignoring the ip phone ip ranges, goes a long way to fixing this problem.

**Comment by murrant** [comment]
@khobbits  this is implemented now isn't it?

**Comment by khobbits** [comment]
@murrant only the hidden search, not the visibility, see my last message. (Unless you know something I don't)

**Comment by Misch-** [comment]
One way of going about this might just be querying the database for all discovery failures since the last 'discover.php -all' scan. In my case, doing that and only looking at failed ARP discovery, then only querying for unique messages, worked pretty well. Was able to generate an HTML page daily to show devices that have failed to discover on our management vlan. A proposed page might be able to work similarly, the problem with reporting on non-arp discoveries, is that it will find a ton of failures outside your configured SNMP scan subnet ranges. I just wanted information on specific subnets. So maybe that can be addressed somehow as well. I would highly recommend having a seperate page for failed discoveries, it's actually pretty huge for security and network management I think.

**Comment by murrant** [comment]
The event log will contain messages when it adds or fails to add a device.

**Comment by khobbits** [comment]
@murrant If you are trying to use librenms in a production environment and routinely have time to read through all of the event log, rather than using it as a post-event discovery tool, you probably should go ask your boss for some more responsibilities, because you've certainly got too much free time. :tongue: 

I've got so many servers and tools I need to use in my day to day work, that I don't have time to look at something, unless it's slapping me in the face going "READ ME NOW, Administrator intervention is required!".

Properly presenting relevant data is kinda the purpose of this project.  If presentation was worth nothing, we'd be just dumping snmpwalk data into text files and calling it a day.

**Comment by laf** [comment]
You could probably just create an alert rule
