### ISSUE TITLE
Disable eventlog entries for ignored devices

### ISSUE THREAD

**Issue by bartdebruijn** [librenms/librenms#2887]
Currently, under "Device Settings", there are options to "disable" and/or "ignore" a device.

Once you "ignore" a device, the device will not generate alerts. However, it will still fill up the eventlog.

The use case is that I have a bunch of office switches and I don't really want to fill up the eventlog with entries each day that people turn their computers on and off again at the end of the day.

Would it be possible to include an option to disable eventlog, under "Device Settings" ?

Thanks.

**Comment by Rosiak** [comment]
Hi,

We are cleaning up the issues here on GitHub, all feature requests will be moved to:
https://community.librenms.org/c/feature-requests

Hence the closure of this issue.
