### ISSUE TITLE
Unresolvable lldp/cdp neighbours.

### ISSUE THREAD

**Issue by khobbits** [librenms/librenms#2888]
I have probably 400 devices that show up up on lldp, that librenms can see through lldp that it doesn't add.
390 of these, are workstations and voip phones that aren't running snmp.
To make the discovery stage quicker, I added the ranges these devices sit in, to my config.php excludes, but sometimes it would be useful to be able to search for "voipphone-ext234" and see what switch it is plugged into.

Currently librenms has no way for me to search for these devices, other than to open each device, switch to the neighbours tab, and see if I can see the device listed.  This is quite time consuming, so it would actually be easier to crawl under desks tracing cables.

What I'm proposing, is that in addition to the 'monitored devices', there was also a 'unmonitored device' page, which provides a searchable list of all the devices detected during discovery, and the devices they are attached to.

A bolt on to this feature could be a filter to hide 'excluded' devices, to uncover those sneaky devices that are attached to your network, that you either aren't expecting or are misconfigured.  While watching a ./discovery.php run this morning, I noticed that netmon has located 7 switches in my network that their device name doesn't resolve to a valid ip address, because someone installed the device without properly configuring it.

https://www.dropbox.com/s/ivvjwyw2lr6qa1u/2016-01-29_10-08-11.png?dl=0
https://www.dropbox.com/s/qz8ocvhaoveu4nz/2016-01-29_10-30-22.png?dl=0

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by khobbits** [comment]
This is a feature request, rather than an issue.  Request still stands.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-unresolvable-lldp-cdp-neighbours/725
