### ISSUE TITLE
stp messages while stp disabled

### ISSUE THREAD

**Issue by radi242** [librenms/librenms#2889]
Hello,
seems there is a problem with stp messages occuring in eventlog, while stp is disabled both on the device and under "modules" section for this particular device. So even if the device still would generate some stp events, I suppose librenms to ignore it.

Device in question is Zyxel VDSL2 multiplexer connected to ethernet switch (STP is disabled on this switchport too).

I'm observing following messages, maximum message interval nominally does not exceed a few hours.

2016-01-29 12:50:20	vdsl1	stp	STP root port changed: 40304 > 0
2016-01-29 12:50:20	vdsl1	stp	STP designated root changed: 0000000181fa > 000000000000
2016-01-29 12:45:21	vdsl1	stp	STP root port changed: 0 > 40304
2016-01-29 12:45:21	vdsl1	stp	STP designated root changed: 000000000000 > 0000000181fa

**Comment by radi242** [comment]
I must also say that these messages are related to unrealistic events - such STP topology changes are unlikely to happen in this scenario.  So it seems like to be completely random based.

**Comment by vitalisator** [comment]
@radi242 have you deactivated the poller module under device settings too or just the discovery module?

**Comment by radi242** [comment]
vitalisator, thanks for the hint, I've in fact overlooked that the same page consists settings for both pooler/discovery for STP. Turned this off there and messages are gone.
I wonder why device with disabled STP in internal configuration generates such messages but it may be just a bug in a snmp stack of this equipment.  But what is most important, problem is solved at the moment so thanks again.

**Comment by laf** [comment]
We might need to look at the poller then. It shouldn't run any queries if we haven't discovered Data

**Comment by radi242** [comment]
I tried to enable debug on this Zyxel device but seems that it's not available, at least for ordinary user. So I was unable to verify if there is something going on under the hood. Perhaps it just provides some garbage and poller caught it while being enabled.

**Comment by vitalisator** [comment]
@laf 
the code care about that, but stp data was discoverd before and only discover module was deactivated after.


    if ($stp_db['bridgeAddress'] && $stp['bridgeAddress']) {
        // Logging if designated root changed since last db update
        if ($stp_db['designatedRoot'] != $stp['designatedRoot']) {
            log_event('STP designated root changed: '.$stp_db['designatedRoot'].' > '.$stp['designatedRoot'], $device, 'stp');
        }
        
        // Logging if designated root port changed since last db update
        if ($stp_db['rootPort'] != $stp['rootPort']) {
            log_event('STP root port changed: '.$stp_db['rootPort'].' > '.$stp['rootPort'], $device, 'stp');
        }

We could deactivate poller when discovery is deactivated, but someone would keep them running without discovery.

**Comment by paulgear** [comment]
@vitalisator It seems completely reasonable to me to disable STP polling if STP discovery is disabled.

**Comment by laf** [comment]
We have the same with anything we have discovery and polling modules for.

I'd personally say not to link disco -> polling modules as it will remove flexibility. For instance we disable bgp discovery from normal runs but have a separate discovery cron which checks for bgp every hour. If we linked the two together then us disabling bgp discovery would disable polling of bgp. I realise we are talking about stp here but it would / could be the same.

Maybe we need a purge data button?

**Comment by vitalisator** [comment]
I suggest we can close this, so the original issue is closed.
