### ISSUE TITLE
Alerting issues - down device worsens

### ISSUE THREAD

**Issue by ekoyle** [librenms/librenms#2893]
I have been noticing an issue for a while where a down device will alert as expected until after the final alert (based on max alert count), at which point it claims the device has 'worsened' and starts sending me an alert at every interval.  Looking at the alerts_log entries for these 'worsened' alerts, details contains a compressed empty string.

The alert rule is:
#1  Devices up/down %macros.device_down = "1"   critical

Max: 3
Delay: 600
Interval: 3600

I've been looking at the alerting for a couple days, and it is a bit confusing in a couple places.

It looks like the db doesn't really have a way to differentiate between a previous event that has been recovered (and therefore should be left alone indefinitely) and a new event matching the same rule, and I'm wondering if this could be causing the duplicate states PR #2881 is addressing.

The alerts table contains some basic state (including 'open' which is somewhat mysterious to me... is it just a flag to indicate that an alert may need to be sent?).  There is also the alerts_log table which appears to be doing some magic beyond just logging, including keeping track of state.

I have tried to get rid of some of the magic numbers in https://github.com/ekoyle/librenms/tree/alerts_constants , which helps some, although I'm hoping there is a better way to do this in PHP.

**Comment by f0o** [comment]
https://github.com/f0o/glowing-tyrion/blob/master/DEVELOPMENT.md

I must disagree with some of your changes, having all states to be a call is useless computation in my POV and switching away from strict comparisson to loose, typeless, comparisson is hostile when you can clearly predict the datatype.
Also, the function may echo an error when presented with unknown or out-of-scope usage but will still return NULL. This together with loose comparisson means that whenever the source array is unavailable, the function will return 'recovered' state as `0 == NULL` afaik.

**Comment by ekoyle** [comment]
Thank you for the docs.

I don't like the function calls either.

I originally planned to use an array, but AFAICT, it would require a
'global' statement for each variable in each function that uses them along
with the import.

PHP is not my primary programming language, so I'm sure there is a better
way; I just don't know what it is ;).

**Comment by f0o** [comment]
We could use Constants to make the states and such more humanreadable. Those wont affect exectime and are still typed.
If thats what you're after...

Dont get me wrong, I highly appreciate somebody taking a look at my alerting code, more eyes see better :)

**Comment by ekoyle** [comment]
How hard would it be to use something other than 0 for ok/recovered?  I
know it would be a big change, but it seems like comparisons with 0 are
extremely error prone in PHP, and the whole type issue would be moot if 0
wasn't a valid state.

**Comment by ekoyle** [comment]
@f0o: does this look better? -> https://github.com/ekoyle/librenms/tree/alerts_constants

**Comment by f0o** [comment]
It's a step forward but i don't see the necessity for the class construct. Plain constants with `define()` should work just as well. Or was there a specific reason for the class?

**Comment by ekoyle** [comment]
It just looked cleaner to me and reduces clutter in the global namespace.

I don't have a very strong opinion on it, but it was easier to type using
the class construct and it assures that we can't accidentally add an
unrelated constant with the same prefix.

AlertState::WORSE vs ALERT_STATE_WORSE

**Comment by f0o** [comment]
Yeah that's a legit reason. Was just wondering out of curiousity

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
