### ISSUE TITLE
serach for IP in global search

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#2897]
since we store the IP address in devices table it would be nice to add this field to global search.

**Comment by laf** [comment]
Duplicate #1173

**Comment by vitalisator** [comment]
@laf what I mean is not searching for interface IP adresses, is for device IP address.
That is more basic one.

**Comment by laf** [comment]
I'd still class it as the same as a user is typing in the IP, where we search is just a back end query. The other issue is tagged back to this so we can grab the info you've explained :)
