### ISSUE TITLE
Weathermap stopped working

### ISSUE THREAD

**Issue by adamboutcher** [librenms/librenms#2901]
So I use the [Weathermap Plugin](https://github.com/librenms-plugins/Weathermap) but it stopped working last night.

I haven't changed anything with the OS nor LibreNMS other than the nightly auto-updates.

The weathermap generates but it doesn't display any data, I was wondering if any of your recent updates may changed something significant as the plugin hasnt had any changes to it for a number of days.

Thanks

**Comment by f0o** [comment]
Please use https://github.com/BarbarossaTM/Weathermap/tree/port_id until it's merged upstream

**Comment by SaaldjorMike** [comment]
Closing this as PR has been merged.

**Comment by adamboutcher** [comment]
thanks.
