### ISSUE TITLE
Support for munin multigraph plugins

### ISSUE THREAD

**Issue by SaaldjorMike** [librenms/librenms#2903]

**Comment by f0o** [comment]
Can you give me an example plugin please?

**Comment by SaaldjorMike** [comment]
@f0o Yeah ofc. I'm trying to use the following plugin:
https://raw.githubusercontent.com/shuque/bind9stats/7f1030a7683d3075dcc31d0b6e05e83d0f8bbd19/bind9stats.py
Which yields the config: http://0bin.net/paste/NkFWtTCno7syMghH#olysev5mnIE44N7CGiqzTBkP65zNtxcoZzxiLZEsyVI
And for values: http://0bin.net/paste/Lel4tJgpLWZvat2I#y1BhEpvL0-1WjwJIqpP4WE5haK9RwnZJz+Ccp/ZulPs

Basically this is a plugin which contain information about multiple graphs whereas it looks like we currently only support simple munin plugins where we only have data for one graph.

**Comment by f0o** [comment]
Ah that format should be easy to add, will see what I can come up with on monday's lunch break

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
