### ISSUE TITLE
Ports graphs not showing up on various devices

### ISSUE THREAD

**Issue by masonke** [librenms/librenms#2907]
Taking this from the IRC

On various devices, including cisco routers, switches, and netscalers, the polling works, but the graphs for the interfaces are never created. In some locations the graphs for similar devices like netscalers are working.

On all the broken devices the graphs show "Error Drawing Graph" the debug shows
RRDTool Output ERROR: String ends after the = sign on 'CDEF:inB=' 

Looking in syslog, I find this message for various devices and files spooling.

Feb  1 10:31:04 prdwndsrenms001 rrdcached[7513]: queue_thread_main: rrd_update_r (/data/librenms/rrd/././bda-agg-a/port-526780160.rrd) failed with status -1. (/data/librenms/rrd/././bda-agg-a/port-526780160.rrd: illegal attempt to update using time 1454338371 when last update time is 1454340509 (minimum one second step))

I deleted the /data/librenms/rrd/././bda-agg-a/port-* files to see what would happen. The files were created, and the errors returned.

I disabled cisco-cbqos without change

Ideas?

Ubuntu 14.0.4

 ./validate.php
Version info:
Commit SHA: cf55f4efd646456eac595d00af1069602bd1b156
DB Schema: 98
PHP: 5.5.9-1ubuntu4.14
MySQL: 5.5.44-0ubuntu0.14.04.1-log
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

[OK]      Database connection successful
[OK]      fping has been found
librenms@prdwndsrenms001:~$

**Comment by laf** [comment]
I think you said you're on a distributed setup. This looks like your rrdcached box and pollers are out of sync time wise. please ensure they are all in the same timezone and ntp syncd.

**Comment by f0o** [comment]
I agree seems like time sync issue

**Comment by masonke** [comment]
Will do, thank you
~KEM

**Comment by laf** [comment]
Feel free to re-open/comment.

**Comment by masonke** [comment]
Turns out time sync was not a bad theory. We had san problems due to an hba driver that caused writes to slow to a crawl intermittently. For some reason this messed up the rrdcached on the distributed pollers. 

On the pollers, once I stopped the rrdcached service, did a git pull and then started rrdcached, things started working.

Thank you for you help
