### ISSUE TITLE
BGP Local and Peer Addresses don't honour web_mouseover

### ISSUE THREAD

**Issue by adaniels21487** [librenms/librenms#2914]
Hi Team,
When I navigate to: Routing -> BGP, the local and peer addresses show the overlib graphs, even when: ```$config['web_mouseover']=false```.
This is also true for Device -> Routing -> BGP.

![image](https://cloud.githubusercontent.com/assets/13431617/12764966/0b8556c4-ca48-11e5-9217-97a4adf0c8f0.png)

**Comment by laf** [comment]
Fixed in #2915 . Thanks @adaniels21487 :)
