### ISSUE TITLE
Add Raspberry Pi

### ISSUE THREAD

**Issue by SirMaple** [librenms/librenms#2916]
Would it be possible to add Raspberry Pi monitoring using the librenms-agent to LibreNMS so the CPU temperature and voltages can be monitored?

Here's a good starting point  -> http://youresuchageek.blogspot.co.uk/2013/01/howto-raspberry-pi-monitor-your.html 

I couldn't get it to work. If testing is needed I'm more than happy to help as I have 3 different versions of Pi's I can test with.

Apologies if this is not the correct place to make this request, first time using github.

**Comment by laf** [comment]
Kind of stopped when I saw obs... :)

However you'd be better off doing this via check_mk with munin. @f0o, I'm not 100% sure what's needed (we have no docs) on getting munin script working, if you can drop some notes in I can test it and doc it up.

Basically we can use the bash script from that link then to bring the data in we need:

```bash
#!/bin/bash
#set -x
echo "<<<app-raspberry>>>"
# CPU Frequency
expr `vcgencmd measure_clock arm|cut -f 2 -d "="` / 1000000
# CORE Frequency
expr `vcgencmd measure_clock core|cut -f 2 -d "="` / 1000000
# CORE Voltage
vcgencmd measure_volts core|cut -f 2 -d "="|cut -f 1 -d "V"
# SoC Temp
vcgencmd measure_temp|cut -f 2 -d "="| cut -f 1 -d "'"
```

**Comment by arjitc** [comment]
Hmm, shouldn't the sensors package work on ARM / RasberryPI as well ? (sensors / sensors_lm) and then return this data back?

**Comment by f0o** [comment]
@laf munin will definitely work. I'd be surprised if there isn't already a plugin for it

**Comment by laf** [comment]
@f0o, do we not need some extra stuff for the graphing part?

**Comment by arrmo** [comment]
Hi,

Don't want to sidetrack this, so I can open a new issue if it makes sense ... but are others having issues  with "reliability" of polling Raspberry Pi? I'm (too) regularly seeing an alert saying that my RaspberryPi device is down, but it's not ... I can manually snmpwalk it, and it is up.

Thanks!

**Comment by laf** [comment]
@f0o do you have any info on adding new munin graphs so we can get a doc up?

**Comment by f0o** [comment]
no we dont need anything extra for graphing,

following a simple template:

```bash
#!/bin/bash
if [ "$1" = "config" ]; then
        echo 'graph_title Some title'
        echo 'graph_args --base 1000 -l 0' #not required
        echo 'graph_vlabel Some label'
        echo 'graph_scale no' #not required, can be yes/no
        echo 'graph_category system' #Choose something meaningful, can be anything
        echo 'graph_info This graph shows something awesome.' #Short desc
        echo 'foobar.label Label for your unit' # Repeat these two lines as much as you like
        echo 'foobar.info Desc for your unit.'
        exit 0
fi
echo -n "foobar.value " $(date +%s) #Populate a value, here unix-timestamp
```

**Comment by laf** [comment]
That's all I needed, just want to create a doc for people to use.

**Comment by Rosiak** [comment]
Think #4057 closes this :)

**Comment by laf** [comment]
Yeah just want to document munin stuff still :(

**Comment by Rosiak** [comment]
Ah, sorry!
