### ISSUE TITLE
is_mib_poller_enabled() function needs updating

### ISSUE THREAD

**Issue by laf** [librenms/librenms#2918]
At present it returns false if you have it globally disabled.

Order probably should be:

Check device
if not true or false (i.e empty as it's not been overridden)
Check global

**Comment by laf** [comment]
Been checking into this and if you disable mib polling globally and enable it for a single host then it won't run mib polling from what I can see.

Is there any reason we check if the device has mib polling enabled within the mib poller. Normally polling modules leave that to poller.php but if you run the poller with -m MODULE then it will still run it. Imho we should consider sticking to that way.

@paulgear

**Comment by masonke** [comment]
I agree, it is consistent with the other modules and lets you control what will have mib polling enabled. Currently we are going through our cisco devices to shut off the AAA mib, when all we want to have MIB polling is a small group. Globally turning it on can cause a lot of headaches and unintended consequences.

**Comment by laf** [comment]
bump

**Comment by paulgear** [comment]
The reason we can't do it with the usual module method is because the MIB poller data is accessed from other modules.  #3443 created to reverse the order of global & device-based.
