### ISSUE TITLE
Muted alerts don't update

### ISSUE THREAD

**Issue by remydb** [librenms/librenms#2920]
We've experienced the following:
- A device is added to LibreNMS
- The device has 6 ports down and creates a port down alert (using the default port up/down rule)
- We mute the alert and in the alerts tab for the device it shows 6 ports down
- Now, we disable 2 of the ports in the configuration, causing it to not match the port up/down rule anymore. This is where we expect the 2 ports to get removed from the alert notification on the device page.
- The 2 ports stay listed in the alert

If we press the red button next to the alert (to acknowledge it completely?), on the next poller run the alert will come back with only the 4 ports that are actually down listed.

So, are alerts just not updated at all if you mute them? Is that by design?

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
