### ISSUE TITLE
API is not showing device information

### ISSUE THREAD

**Issue by chrisgfx** [librenms/librenms#2921]
Hi,

I don't know if the API seems to have a Bug since the last release or the new year or if there is a new way to use it :

**curl -H 'X-Auth-Token: YOURAPITOKENHERE' https://librenms.org/api/v0/devices/localhost**
Showing nothing for a real device and an error if I put a devices that doesn't exists

**curl -H 'X-Auth-Token: YOURAPITOKENHERE' https://librenms.org/api/v0/devices/**
All is fine, devices and detailed information are showed

I tried to compare the version of api_functions.inc.php and /api/v0.php files but without success.

Thanks,
Christophe

**Comment by chrisgfx** [comment]
I troubleshoot and I found the issue : IP address is in a wrong format with function get_device() but ok in function list_devices().
I will try to figure out why. Maybe device_by_id_cache($device_id) with a recent change?

**Comment by chrisgfx** [comment]
Array
(
    [status] => ok
    [devices] => Array
        (
            [0] => Array
                (
                    [device_id] => 1
                    [hostname] => hostname
                    [sysName] => sysName
****                    [ip] => ▒i▒
****
                    [community] => public
                    [authlevel] =>
                    [authname] =>
                    [authpass] =>
                    [authalgo] =>
                    [cryptopass] =>
                    [cryptoalgo] =>
                    [snmpver] => v2c
                    [port] => 161
                    [transport] => udp
                    [timeout] =>
                    [retries] =>
                    [bgpLocalAs] =>
                    [sysObjectID] => enterprises.9.1.1208
                    [sysDescr] => Cisco IOS Software, C2960X Software (C2960X-UNIVERSALK9-M), Version 15.2(2)E1, RELEASE SOFTWARE (fc3)
                    [sysContact] => sysContact
                    [version] => 15.2(2)E1
                    [hardware] => cat29xxStack
                    [features] => UNIVERSALK9
                    [location] => location
                    [os] => ios
                    [status] => 1
                    [status_reason] =>
                    [ignore] => 0
                    [disabled] => 0
                    [uptime] => 3885656
                    [agent_uptime] => 0
                    [last_polled] => 2016-02-04 16:00:17
                    [last_poll_attempted] =>
                    [last_polled_timetaken] => 15.46
                    [last_discovered_timetaken] => 9.73
                    [last_discovered] => 2016-02-04 12:34:29
                    [last_ping] => 2016-02-04 16:00:17
                    [last_ping_timetaken] => 5.13
                    [purpose] =>
                    [type] => network
                    [serial] => serial
                    [icon] =>
                    [poller_group] => 0
                    [override_sysLocation] => 0
                    [notes] =>
                    [port_association_mode] => 1
                )

        )

**Comment by chrisgfx** [comment]
Just checked on an old version (81fdfa6) and it's working even if the IP field is incorrect.
function get_device() is the same than actually. :-/

**Comment by f0o** [comment]
That's likely caused by the binary ip field

**Comment by chrisgfx** [comment]
I checked the format in the DB and as it is the same field for the two API function device, I believed it was due to another specific function.

**Comment by chrisgfx** [comment]
It seems you are true. Bad datas in IP field in the DB. I just changed one field to the real IP format and it was later updated to the resolved IP in the right format (?) but not human readable.
Function Device API is working again! :-)

I will check tomorrow on the other environment and hope to close this issue.

**Comment by chrisgfx** [comment]
After erasing the IP fields in the DB, all is working again! :-)

**Comment by laf** [comment]
This will need a patch on our side.

**Comment by chrisgfx** [comment]
Great, as the problem appears again after several hours! :-(

Thanks!
