### ISSUE TITLE
Option to disable disabled port graphs

### ISSUE THREAD

**Issue by cchance27** [librenms/librenms#2922]
Something i hope can be fixed easily, can someone please look into adding an option that we can set to hide disconnected/inactive ports on the device ports page... 

Theirs nothing like opening a 48 port switch ports page and seeing it sit their generate 80 blank images, and then finally the last 8 ports of graphs with actual traffic.

I'd love it if there was an option i could set to hide them by default, with a toggle on the page to "show inactive ports" and then it generates all the useless empty graphs/ports.

**Comment by SaaldjorMike** [comment]
:+1:

**Comment by Rosiak** [comment]
:+1:

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
