### ISSUE TITLE
Error show list - Devices -> Firewall

### ISSUE THREAD

**Issue by 21let** [librenms/librenms#2929]
When you click on Devices -> Firewall in datatable only displays text Loading ... please find attached a screenshot of Google Chrome console. Can you advise on what could be the problem?

![image](https://cloud.githubusercontent.com/assets/13964136/12809076/522b8ea2-cb1c-11e5-8934-39d0e265da9a.png)

**Comment by 21let** [comment]
![image](https://cloud.githubusercontent.com/assets/13964136/12809115/a9a79978-cb1c-11e5-8869-6fceace354f6.png)

**Comment by laf** [comment]
If you do:

```sql
SELECT * FROM devices WHERE type='firewall';
```

Do you have any output that looks escaped or needs to be?

**Comment by 21let** [comment]
This command I listed all 12 entries firewalls. I look at the table and all I see is that with these firewalls are SN listed in quotation marks ( "), I do not know if this can not be a problem.

**Comment by 21let** [comment]
Problem solved. The Location was stated in the coding LATIN (Czech) (ž).
