### ISSUE TITLE
Sensors are deleted/added for every polling cycle

### ISSUE THREAD

**Issue by adammmmm** [librenms/librenms#2930]
Since #2862 the sensors for our Cisco ASR1002 and ASR1004's are getting added and deleted for every poll. The actual librenms server isn't having its sensors added/deleted though.

Let me know if you need any more input!

**Comment by Rosiak** [comment]
General info:
Friend of mine is also having issues with Cisco ME3400 and some HP stuff.

**Comment by laf** [comment]
Please post the output of:

./discovery.php -h HOSTNAME -d -m sensors

**Comment by adammmmm** [comment]
[sensor-debug.txt](https://github.com/librenms/librenms/files/119020/sensor-debug.txt)
Here you go!
