### ISSUE TITLE
NetFlow Configuration?

### ISSUE THREAD

**Issue by mtehonica** [librenms/librenms#2931]
Is there any documentation on configuring NetFlow in LibreNMS?  I see that it's listed as a supported feature on the website but I don't see how to add a collector for it?

**Comment by chrisgfx** [comment]
As far as I know it was in the pipe by someone but it was not finished.

**Comment by laf** [comment]
http://docs.librenms.org/Support/Configuration/?highlight=nfsen#external-integration

That's what we have at the moment.

**Comment by mtehonica** [comment]
OK, thanks for the help guys.
