### ISSUE TITLE
Ability to disable recovery alerts on a rule by rule basis 

### ISSUE THREAD

**Issue by SirMaple** [librenms/librenms#2933]
Would it be possible to add a toggle to each alert rule to disable recovery alerts?

I currently use syslog to detect link/port down events on a my switches. The recovery alert that is sent is misleading in this case as it simply means the syslog msg is no longer found in the last 5 minutes of msg's and the port is in fact still down. 

For sensors, cpu, and others the recovery alert makes sense.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by laf** [comment]
This is now available for testing: https://github.com/librenms/librenms/pull/8430
