### ISSUE TITLE
adva discovery module should use SNMP functions, not call directly.

### ISSUE THREAD

**Issue by adaniels21487** [librenms/librenms#2934]
In: includes/discovery/sensors/temperatures/adva.inc.php
I stumbled across this:

	$temperature_chassis = trim(shell_exec($config['snmpget'] . " -M " . $config['mibdir'] . " -O qv -$snmpver -c $community $hostname:$port $oid_chassis"));
    $temperature_stm16 = trim(shell_exec($config['snmpget'] . " -M " . $config['mibdir'] . " -O qv -$snmpver -c $community $hostname:$port $oid_stm16"));
    $temperature_hss1 = trim(shell_exec($config['snmpget'] . " -M " . $config['mibdir'] . " -O qv -$snmpver -c $community $hostname:$port $oid_hss1"));
    $temperature_hss2 = trim(shell_exec($config['snmpget'] . " -M " . $config['mibdir'] . " -O qv -$snmpver -c $community $hostname:$port $oid_hss2"));
    echo("Adva Chassis ");
	
Is there any reason this can't use the built-in SNMP functions such as snmp_get() ?
I am happy to fix it up, but I dont have an adva to test against. Does anyone have an adva?

Aaron

**Comment by SaaldjorMike** [comment]
This should for sure be using the `snmp_get()` function.

**Comment by laf** [comment]
No reason, it's just legacy code.

**Comment by Rosiak** [comment]
All this code is commented out.
Shouldn't we just remove the file?

**Comment by adaniels21487** [comment]
good catch, I didnt see that.
yes, cruft removal is good.

**Comment by SaaldjorMike** [comment]
PR merged
