### ISSUE TITLE
Device synology RT1900ac not detected properly

### ISSUE THREAD

**Issue by Djf2884** [librenms/librenms#2937]
Hello Guys,

I have a router Synology RT1900ac that is not detected properly, ports are detected as 10Mbps instead of Gigabit, Sensors are not properly detected neither and is suspect that some other issues are here and there.

It's generating some uncorrect alarms due to port utilization over threshold.

How can i help u to identify the device and all parameter properly?

Thx :)

**Comment by laf** [comment]
I expect the 10Mbps issue is because the device is reporting that back to us so until we allow manually setting the port speed then we possibly can't resolve that.

Can you provide us remote snmp access to the device?

**Comment by Djf2884** [comment]
How can i do that ? By reporting the discovery log ?

**Comment by Djf2884** [comment]
Here is the snmpwalk, in case it's not what is expected here, please let me know.
[snmpwalk_res.txt](https://github.com/librenms/librenms/files/119121/snmpwalk_res.txt)

**Comment by Rosiak** [comment]
Hmm.
IF-MIB::ifSpeed.1 = Gauge32: 10000000
IF-MIB::ifHighSpeed.1 = Gauge32: 10

**Comment by Rosiak** [comment]
You can now manually override this until Synology decides to fix it.
This is done under Device>Device Settings>Port Settings.

**Comment by Djf2884** [comment]
Thx u 😀 that permit to solve my issue
