### ISSUE TITLE
Issues with adding hosts

### ISSUE THREAD

**Issue by MonsieurC** [librenms/librenms#2938]
HI everyone!

I want to add two switches but LibreNMS tells me that they already exist. The strange thing is, when i use delhost.php, it says that the devices don't exist, which is kind of confusing.
Adding any other devices than these two particular switches works perfectly fine.
As i am a perfect noob regarding SQL, i didn't try to look into the databse to see any errors.
What can i do to fix this?
Thanks.

**Comment by laf** [comment]
Are you adding by hostname or IP?

If by IP then we check the IP table to make sure the device doesn't already exist so it could be that.

If it's hostname then it should be fine as long as the hostname isn't the same.

**Comment by MonsieurC** [comment]
I'm adding by IP. 
So if i understand correctly, if the addresses of the switches are the table ipv4_address, it could prevent me form adding them ? If i delete the occurences of the concerned switches in this table, will it help to fix my problem ?

**Comment by laf** [comment]
That's correct about the table. deleting the IP concerned will allow you to add the other device but isn't a fix.

Really you should be using hostnames :)

**Comment by MonsieurC** [comment]
Thanks a lot for your reply, i close the issue.
