### ISSUE TITLE
Dashboard Autorotation

### ISSUE THREAD

**Issue by mtehonica** [librenms/librenms#2941]
It would be nice to be able to a a "view" where you could rotate through multiple dashboards every X minutes.  That way if you had a Network dashboard and an Infrastructure dashboard, etc, you could see them all on a screen every few minutes.  I realize there are probably plugins for browsers that could accomplish this, but it would be nice if it was built into the web gui.

**Comment by f0o** [comment]
:+1:

On 5 February 2016 12:14:55 CET, mtehonica <notifications@github.com> wrote:
>It would be nice to be able to a a "view" where you could rotate
>through multiple dashboards every X minutes.  That way if you had a
>Network dashboard and an Infrastructure dashboard, etc, you could see
>them all on a screen every few minutes.  I realize there are probably
>plugins for browsers that could accomplish this, but it would be nice
>if it was built into the web gui.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2941

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mtehonica** [comment]
Any chance this feature is simple to implement and would happen sometime soon?  Or is this a bigger undertaking?

**Comment by Rosiak** [comment]
:+1: 
@mtehonica Since this is a project where we invest our free time, we cannot give you an estimate on when this will be implemented. What we can do is ofc. shout in here, when it's assigned to one and when one will start working on this.

**Comment by mtehonica** [comment]
Yup, completely understand, thanks for all the hard work!

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #164](https://github.com/librenms/librenmsv2/issues/164) via [**ZenHub**](https://www.zenhub.com/)
