### ISSUE TITLE
CPU no Graph

### ISSUE THREAD

**Issue by fran-nlt** [librenms/librenms#2943]
Hi
The CPU for the Firewall Fortinet is not working
Look please

![a3](https://cloud.githubusercontent.com/assets/13962782/12849598/39049c8c-cbff-11e5-9a05-0b31b2ccd74e.JPG)
![a2](https://cloud.githubusercontent.com/assets/13962782/12849596/38e20b86-cbff-11e5-9ae2-b67bc9ff0d6f.JPG)
![a1](https://cloud.githubusercontent.com/assets/13962782/12849597/39010a7c-cbff-11e5-88ef-e82f5d4bf8cc.JPG)

**Comment by Rosiak** [comment]
Duplicate, please add your info to this issue #2751
