### ISSUE TITLE
Alert for RAM

### ISSUE THREAD

**Issue by fran-nlt** [librenms/librenms#2944]
HI
The Rule for the RAM is not working
look it

The name of RAM is Main Memory
![a1](https://cloud.githubusercontent.com/assets/13962782/12852777/7d16829a-cc0f-11e5-8ab8-9e7fac512c96.png)

The Rule
![a2](https://cloud.githubusercontent.com/assets/13962782/12852800/97f36e7a-cc0f-11e5-81f0-769f3b4e86f5.JPG)

The Example in the docs.librenms.org
High memory usage: %macros.device_up = "1" && %mempools.mempool_perc >= "90" && %mempools.mempool_descr = "Virtual@"

Thanks!

**Comment by f0o** [comment]
The docs example is explicitly for linux servers, you have to adjust the desc to match Main instead of Virtual

**Comment by fran-nlt** [comment]
Yes, in the image number 2 is configured this format, but not work

**Comment by laf** [comment]
You need to use like and equals in your rule

**Comment by laf** [comment]
Like not equals :/

**Comment by fran-nlt** [comment]
I changed now

![a1](https://cloud.githubusercontent.com/assets/13962782/12855131/6994d7aa-cc1c-11e5-9ad1-c25efea67771.JPG)

**Comment by fran-nlt** [comment]
Dont work :(

**Comment by f0o** [comment]
That's because of your single quote inside the double quote

**Comment by fran-nlt** [comment]
sorry IS
A) Main@
B) 'Main@'
C) ´Main@´

The System add double quotes "xxxxx"

**Comment by f0o** [comment]
Don't add any quotes yourself. The backend will do it for you.

**Comment by fran-nlt** [comment]
Ok, I delete the rule and create new, but the system add only double quotes.

![a1](https://cloud.githubusercontent.com/assets/13962782/12856284/ebfc8d0e-cc22-11e5-9b6b-5f0a2c64d45f.JPG)
![a2](https://cloud.githubusercontent.com/assets/13962782/12856306/096778ea-cc23-11e5-9b1f-cbb0a54c2317.JPG)
![a3](https://cloud.githubusercontent.com/assets/13962782/12856324/1891c79e-cc23-11e5-8a93-748665379354.JPG)

**Comment by fran-nlt** [comment]
Thanks!
Work Now
![a1](https://cloud.githubusercontent.com/assets/13962782/12856357/4bce0bae-cc23-11e5-9387-a3a65a35516d.JPG)
