### ISSUE TITLE
Netflow addition with ELK stack

### ISSUE THREAD

**Issue by Stalker71** [librenms/librenms#2952]
Hi,

Here's a quick way to implement a netflow dashboard in LibreNMS with a Plugins page :
- Use ELK (Elasticsearch, Logstash, Kibana) to collect netflow traffic
- _we use the netflow plugin in Logstash_ (several others solutions can be found on the WEB)
- _if the amount of flows is big, a dedicated server is better_
- Configure a dashboard with all the visualizations needed
- Insert the Iframe HTML code given by Kibana on the plugins page

That's all!  :satisfied:

Drill Down is even available

**Comment by f0o** [comment]
So.... you want a widget that accepts HTML to include the iframe from Kibana?

**Comment by chrisgfx** [comment]
I believe it will be useful for everyone asking about Netflow in LibreNMS.

I thought first about the Plugins feature, like it is done with WeatherMap.
So maybe, a simple way to configure it could be with an input box in which we paste the Iframe HTML code.

A widget could be use with Dashboard rotating feature as Netflow visualizations take a lot of space on the browser.

**Comment by mtehonica** [comment]
Yeah I could also see this being useful.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
