### ISSUE TITLE
WebUI Rewrite. Looking feedback and offers to help

### ISSUE THREAD

**Issue by laf** [librenms/librenms#2965]
Hey Everyone,

So internally we've been discussing moving LibreNMS forward. Things haven't slowed down since Paul created the fork in 2013 - in fact they are going from strength to strength which is absolutely amazing to see: https://www.openhub.net/p/librenms/commits/summary
In the last 12 months alone, 50% of all the commits have happened :o

Over this time some things have changed, we've introduced new and exciting functionality such as an API, Alerting system and Distributed polling amongst more. The WebUI has undergone a couple of changes and is now mostly using Bootstrap v3, however..........a lot of this is still all based on the inherited code base which we want to move away from. Discussions are happening about a poller/discovery rewrite as well but a WebUI rewrite is in more advanced stages.

As we're an open source group, we've decided to open up this discussion to the wider community to gather your feedback and opinions but above all your help. Below are some thoughts on what the rewrite will provide and also some of downsides.

Positives:
- WebUI / API Will be re-written from the ground up.
- API will be used for all calls for data - no direct SQL queries in WebUI. This is achieved internally so no additional http calls are needed to query the API.
- New layout and template.
- Using Laravel for framework, Dingo for API framework.
- Supports varying authentication models so adding LDAP support is as easy as composer install X and custom modules can be written to do things like Radius authentication.
- Unit testing is possible so we can ensure breaking changes don't make it into master.
- Alternative DB's available (just not from a polling/discovery perspective - poller/discovery rewrite will fix that).
- Various addon's available to Laravel, memcached support, redis, etc.
- Move to using object oriented programming.

Downsides:
- Will require php 5.5.9 and above. However we should be able to maintain backwards compatibility with the old WebUI so you can choose which one to use.
- API will change a bit but again, the current v0 API can stay in place and the new one can move to v1.
- Time!

So what are the next steps?

- We need to decide on a template to use that satisfies most needs.
- We need to lay down the structure of how the code base and API will work.
- A lot of existing config and functions will need to be ported over to the new code format.
- Pages need to be converted over.
- Gather feedback, what do you like / want / hate about the idea.

As part of the decision on what Framework to use, we have a quick demo online which you are free to try (self-registration):

http://web02.lathwood.uk/register

The only page that does anything is /devices at the moment, this loads up a couple of devices using the API internally. It's not up there to be a fully functional test more just to make sure Laravel can do what we want it to (it appears it can) and to try out templates.

Please feel free to let us know what your thoughts are in here or on irc.

If you would like to help with this work then please also let us know, we are looking for people who can help with the coding, design, testing and possibly documentation.

**Comment by alejandroparedero** [comment]
+1 for testing. Also it would be a great idea to enable multilanguage support.

**Comment by laf** [comment]
@alejandroparedero Laravel has support for Localization:

https://laravel.com/docs/5.2/localization

**Comment by iamenderst** [comment]
The demo page comes up empty in Chrome and Firefox for me.
FF 44.0.1, Chrome 48.0.2564.103 m, Even Edge is getting no love.
Anyone else?

**Comment by alejandroparedero** [comment]
@laf great so first it's needed to port the english language to laravel and then its possible to create translations. Hope collaborate.

@iamenderst Me too, may be is still setting it up

**Comment by laf** [comment]
Can you both try again now - thanks for spotting it :)

**Comment by iamenderst** [comment]
I get the login page now, thanks.

**Comment by murrant** [comment]
Looks interesting.  Definitely ++ for unit tests.  Would the plan to be to develop in a branch or in master with an option to switch to the new ui?  Tested on mobile, seems to scale down nicely.

Did remind me of one thing. The menu needs to be flattened so there are less sub menus.

**Comment by laf** [comment]
I think dev would need to be done in a new repo in full as we will be merging commits often so don't want to have the pull request full for librenms/librenms

As for the menu, that theme did just have one sub menu initially but we've mimicked for testing the current system. If we reduced the # of sub menu's then people may miss the quick links. However that's what this issue is for, feedback and we will go with the general consensus in the end.

**Comment by tobiasa1** [comment]
Really good news. I think this is needed for LibreNMS to move forward.
We will get a lot of stuff "for free" by using a framework like Laravel.

+1

**Comment by jvoisin** [comment]
I've got a stackstace on http://web02.lathwood.uk/devices :/

**Comment by murrant** [comment]
jvoisin: you get that when you /api/devices doesn't return any devices. (not high enough permissions for your user)

**Comment by laf** [comment]
@jvoisin permissions updated.

**Comment by adaniels21487** [comment]
I too have the permissions issue.

This is a good move :+1:

**Comment by laf** [comment]
Permissions updated. Let me see if I can fix it perm.

**Comment by laf** [comment]
Sorted, new registrations will now be admin by default.

**Comment by scottscreations** [comment]
just heard about the rewrite, https://almsaeedstudio.com/themes/AdminLTE/index2.html might be something to consider, its open source and documentation is pretty nice.

**Comment by murrant** [comment]
I looked at a lot of Bootstrap admin themes and AdminLTE does seem quite nice.  I also found this: https://github.com/acacha/adminlte-laravel

**Comment by vizay** [comment]
This sounds like a really interesting idea.

Would definitely help out in any way possible (dev, testing etc).
Will follow this closely :)

**Comment by ekoyle** [comment]
If you are starting from the ground up anyway, have you considered the possibility of using a different language?

**Comment by f0o** [comment]
For the UI php is quite good. Perl is just a nightmare securitywise and python cant survive without nested try/catch ;)

Granted, I'm biased on python's abilities but what I said about perl is very true. I can link you some nice talks and presentations of current upstream perl nightmares.

- on the backend/poller side though -
Here we can talk again, something slim like Go or plain C would be great. Have true threads and a daemon would be nice...

**Comment by laf** [comment]
@ekoyle, yes we've tested AngularJS and something else, these can be a pain to actually get running for people and the fact the whole front end would have to be rewritten in JS is a bit off putting as we may not get the contributions going forward. I don't think we've seen a single good enough reason to switch from php at the moment.

**Comment by vizay** [comment]
One should also remember that the more separated backend and frontend becomes (using API instead of direct calls  for example) the easier it is to look at migrating one part to new technology.

I'd say focusing on getting a new front end, that's based on object orientation, simplicity and beautiful code is the way to move forward at this moment. Although PHP seldom is my personal language of choice for anything really (Python baby!!!), I have to admit that it would do the job exceptionally well for this, especially if we go for a framework like laravel :)

Once that's done focus can be shifted towards the back end and what to improve there :)

**Comment by scottscreations** [comment]
I am surprised no one has shared their love for node. I am a PHP and Perl dev and with php7 out we should target 7 with this rewrite...LTS servers will suffer but when do we expect this to come out? 

Staying with PHP, the code from now should be easy enough to move to the new if needed. 

I really liked how easy librenms has been to setup, very easy and I think this is because it was in PHP.

 Now I am not sure how much time i can devote to this but would like to help because we use this product in a few school districts and at my workplace and want to make sure librenms stays awesome.

**Comment by laf** [comment]
Thanks @scottscreations.

Laravel has a PHP 5.9 min requirement. What is specific to 7 that wouldn't work in 5.9 and above?

**Comment by scottscreations** [comment]
just thinking performance, but laravel is the framework i would use.

**Comment by vizay** [comment]
laravel has a really big upside compared to a lot of other frameworks and in extension, also other languages.

It's really simple and beautiful in how you use it. It's very readable and they seem to work very hard keeping that as a philosophy.

**Comment by laf** [comment]
Oh ok, so that's more a case of if we make sure it's 100% compatible with php7 then the user benefits but it will be ok all the way down to 5.9?

**Comment by laf** [comment]
So the feedback has been positive. I'll get a new repo created within librenms and get an initial dev branch up and running.

Will switch over to using the AdminLTE dashboard for this one.

**Comment by adaniels21487** [comment]
I have a few discussion points I'd like to float.
would you like them here or as issues in the new repo?

**Comment by laf** [comment]
Here for now will be best please @adaniels21487 

So AdminLTE quickly thrown together: 

http://web05.lathwood.uk/

If you've registered for web02 link then the same details will work. I've not bothered to get the same details as web02 in it but /devices works as before.

**Comment by adaniels21487** [comment]
1. Client Side Graphing
Something like Highcharts, DyGraph, etc.
Have an API to extract data from whatever storage engine is used (rrd/influx/etc) and present it in a common format to be graphed client side.
Most of these libraries also have refresh functions to re-pull via AJAX. No more refresh in 300 seconds.

2. Co-locate module code
I would like to see module code self-contained and separated from core.
Eg. ./modules/mempools should include poller, discovery, html code and any supporting functions that the module requires.

3. Collection Engines
I'd like to introduce the concept of collection engines. These are classes for collecting data from the environment.
Getting the structure and design pattern right is key here so we can easily add other engines in the future. I am thinking REST, TELNET, SSH, WMI, etc.
We already have code for:
    - the SNMP engine for collecting data via SNMP
    - LOCAL engine for running LOCAL commands

4. Componenets (or something like it)
I have been composing an issue to discuss the future direction of the component feature. What it all boils down to is that many things would be easier if every module has a component, we would know what is attached to each device.

**Comment by laf** [comment]
Thanks for the info. 

#1 is planned as this will be needed to get influx fully integrated. 

The others all seem related to polling/discovery. That's not part of this at present although it has been talked about doing a rewrite of those so stay tuned on that front.

**Comment by laf** [comment]
I'm closing this issue as we are now up and running on the other branch. Please direct any issues there:

https://github.com/librenms/librenmsv2/

https://github.com/librenms/librenmsv2/blob/develop/docs/General/Contributing.md

We are running Scrutinizer and PHPUnit tests.

I'll be creating some issues and a roadmap shortly.

**Comment by alangregory** [comment]
+1 for Laravel, +1 for [HHVM](http://hhvm.com/) compatibility

**Comment by laf** [comment]
@alangregory https://travis-ci.org/librenms/librenmsv2/jobs/111993125

Early days but hhvm is in the travis ci config to perform tests against.

**Comment by laf** [comment]
This issue is now locked. Please feel free to feedback within the librenms/librenmsv2 repo.
