### ISSUE TITLE
Ignore XDP entries a la ['bad_if_regexp']?

### ISSUE THREAD

**Issue by jongaynor** [librenms/librenms#2968]
Discovery times on segments with IP phones and access points that participate in CDP/LLDP are very high (end devices such as these outnumber infrastructure hardware by a factor of 50-to-1). The logic that's been written to ignore interface types and interface regex would ameliorate this. Can this be put on the radar as a 'nice to have?'

Thanks for all of the amazing work!

**Comment by laf** [comment]
Working on this. Needs #2967 to be merged as it will conflict though.

**Comment by laf** [comment]
We have varying ways that we pull data out of CDP / LLDP, ifIndex, SySName, ChassisId. Which would you like to match on to regex against?

**Comment by jongaynor** [comment]
Bear with me - I've only got CDP examples to pick through here. Ideally I'd love to filter based on the 'cdpCachePlatform' SNMP value. This appears to get stored during discovery as 'remote_platform':

_SQL[UPDATE `links` set `remote_platform` ='Cisco IP Phone 7942',`_ . . . 

Is this remote_platform value xDP agnostic? That looks like a good candidate.
