### ISSUE TITLE
Autodiscover - better duplicate detection required

### ISSUE THREAD

**Issue by jawaidbazyar** [librenms/librenms#2975]
Auto-discover worked for me, though too well - we have a complex meshed topology for our core network, which means OSPF and BGP rings, subrings, etc.

Autodiscovery "discovered" each of my routers multiple times, based on the number of adjacencies with other routers in this mesh.

I would say, the autodiscover code needs to be able to detect duplicates on the basis of some unique ID - perhaps the router's hostname, or, OSPF router-id. The Interface IP is just not sufficient outside a linear or pure hierarchical network.

Thanks!

**Comment by laf** [comment]
Working on this. Needs #2967 to be merged as it will conflict though.

**Comment by paulgear** [comment]
I found recently when I deleted a couple of devices to test this that it brought back some duplicates for devices with only 1 IP address.  This was a little unexpected, and I wonder whether there's something else going on; I'll dig into it when I have time and reopen the bug if I find something concrete.

**Comment by boudreau** [comment]
Hi, I find I have the same problem has the original poster. Was there any follow up on this issue?

**Comment by laf** [comment]
I don't believe so.
