### ISSUE TITLE
Can't add hosts

### ISSUE THREAD

**Issue by andryukha** [librenms/librenms#2980]
Hi,

Since updated to latest version today by daily.sh I can't add a host to librenms by web UI and command line. Here is an example:
librenms# sudo -u librenms ./addhost.php -f PRM-URSH-CR1 public v2c 161 udp
Trying community public ...
MIB: registering
     CISCO-AAA-SESSION-MIB::ciscoAAASessionMIB
librenms# sudo -u librenms ./discovery.php -h PRM-URSH-CR1 -d
LibreNMS 2015.master Discovery
Version info:
Commit SHA: 9cca64de4c9d9e5e758325a80243112c98dad26a
DB Schema: 100
PHP: 5.5.9-1ubuntu4.14
MySQL: 5.5.47-0ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
SQL[SELECT revision FROM `dbSchema`] DB Schema already up to date.

SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE 'PRM-URSH-CR1' ORDER BY device_id DESC] ./discovery.php PRM-URSH-CR1 2016-02-11 10:04:35 - 0 devices discovered in 0.059 secs
MySQL: Cell[1/0s] Row[3/0s] Rows[1/0s] Column[0/0s] Update[0/0s] Insert[0/0s] Delete[0/0s]

The host is reachable by ICMP and SNMP:
librenms#ping PRM-URSH-CR1 -c 1
PING PRM-URSH-CR1 (10.3.9.1) 56(84) bytes of data.
64 bytes from PRM-URSH-CR1 (10.3.9.1): icmp_seq=1 ttl=253 time=40.3 ms

--- PRM-URSH-CR1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 40.392/40.392/40.392/0.000 ms

librenms# snmpwalk -v2c -c public PRM-URSH-CR1
iso.3.6.1.2.1.1.1.0 = STRING: "Cisco IOS Software, C800 Software (C800-UNIVERSALK9-M), Version 15.4(3)M4, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2015 by Cisco Systems, Inc.
Compiled Sun 27-Sep-15 08:36 by prod_rel_team"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.9.1.1852
iso.3.6.1.2.1.1.3.0 = Timeticks: (56417704) 6 days, 12:42:57.04

**Comment by laf** [comment]
I can still add devices:

```bash
-bash-4.2$ ./addhost.php host10 librenms v2c
Trying community librenms ...
Added device host10 (9)
```

Please run ./validate.php from within your install directory as root.

**Comment by andryukha** [comment]
There was some file rights mismatch, I fixed it and executed daily.sh again.
Here is validation result after:
/opt/librenms# ./validate.php 
Version info:
Commit SHA: 9cca64de4c9d9e5e758325a80243112c98dad26a
DB Schema: 100
PHP: 5.5.9-1ubuntu4.14
MySQL: 5.5.47-0ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

[OK]      Database connection successful
[OK]      fping has been found

But still can't add a host:

/opt/librenms# sudo -H -u librenms ./addhost.php PRM-URSH-CR1 public v2c 161 udp
Trying community public ...
MIB: registering
     CISCO-AAA-SESSION-MIB::ciscoAAASessionMIB

root@librenms:/opt/librenms# sudo -H -u librenms ./discovery.php -h PRM-URSH-CR1 -d
LibreNMS 2015.master Discovery
Version info:
Commit SHA: 9cca64de4c9d9e5e758325a80243112c98dad26a
DB Schema: 100
PHP: 5.5.9-1ubuntu4.14
MySQL: 5.5.47-0ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
SQL[SELECT revision FROM `dbSchema`] DB Schema already up to date.

SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE 'PRM-URSH-CR1' ORDER BY device_id DESC] ./discovery.php PRM-URSH-CR1 2016-02-11 13:15:22 - 0 devices discovered in 0.040 secs
MySQL: Cell[1/0s] Row[3/0s] Rows[1/0s] Column[0/0s] Update[0/0s] Insert[0/0s] Delete[0/0s]

**Comment by laf** [comment]
I'd suggest jumping onto our irc channel

**Comment by laf** [comment]
Mysql restart fixed the issue.
