### ISSUE TITLE
MIB FortiManager

### ISSUE THREAD

**Issue by fran-nlt** [librenms/librenms#2983]
Hi
I add FortiManager 300d to LibreNMS but detect as Generic

**Comment by laf** [comment]
please provide the output of:

```bash
./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -d -m os -r -f
```

**Comment by fran-nlt** [comment]
]0;root@librenms: /opt/librenmsroot@librenms:/opt/librenms# ./discovery.php -h fmg_australis -d -m os
LibreNMS 2015.master Discovery
commit e9b53896cb20fb72571fc05f9f9434c64240ef7b

DEBUG!

SQL[[0;33mSELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1[0m] 
SQL[[0;33mSELECT revision FROM `dbSchema`[0m] DB Schema already up to date.

SQL[[0;33mSELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE 'fmg_australis' ORDER BY device_id DESC[0m] 
SQL[[0;33mSELECT * FROM devices_attribs WHERE `device_id` = '61'[0m] fmg_australis 61 generic DEBUG: SNMP Auth options =  -v2c -c nlt
/usr/bin/snmpget -v2c -c nlt -Ovq -M /opt/librenms/mibs udp:fmg_australis:161 SNMPv2-MIB::sysDescr.0
Fortimanager

DEBUG: SNMP Auth options =  -v2c -c nlt
/usr/bin/snmpget -v2c -c nlt -Ovqn -M /opt/librenms/mibs udp:fmg_australis:161 SNMPv2-MIB::sysObjectID.0
.1.3.6.1.4.1.12356.103.1.3004

| Fortimanager | .1.3.6.1.4.1.12356.103.1.3004 | DEBUG: SNMP Auth options =  -v2c -c nlt
/usr/bin/snmpget -v2c -c nlt -Osqnv -M /opt/librenms/mibs udp:fmg_australis:161 ENTITY-MIB::entPhysicalMfgName.1
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c nlt
/usr/bin/snmpget -v2c -c nlt -Oqv -M /opt/librenms/mibs udp:fmg_australis:161 1.3.6.1.4.1.674.10895.3000.1.2.100.1.0
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c nlt
/usr/bin/snmpget -v2c -c nlt -Oqv -M /opt/librenms/mibs udp:fmg_australis:161 .1.3.6.1.4.1.39165.1.6.0
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c nlt
/usr/bin/snmpget -v2c -c nlt -Oqv -M /opt/librenms/mibs udp:fmg_australis:161 SML-MIB::product-Name.0
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c nlt
/usr/bin/snmpget -v2c -c nlt -Oqvn -M /opt/librenms/mibs udp:fmg_australis:161 ENTITY-MIB::entPhysicalDescr.1
No Such Object available on this agent at this OID


OS: DEBUG: SNMP Auth options =  -v2c -c nlt
/usr/bin/snmpget -v2c -c nlt -Ovq -M /opt/librenms/mibs udp:fmg_australis:161 SNMPv2-MIB::sysDescr.0
Fortimanager

DEBUG: SNMP Auth options =  -v2c -c nlt
/usr/bin/snmpget -v2c -c nlt -Ovqn -M /opt/librenms/mibs udp:fmg_australis:161 SNMPv2-MIB::sysObjectID.0
.1.3.6.1.4.1.12356.103.1.3004

| Fortimanager | .1.3.6.1.4.1.12356.103.1.3004 | DEBUG: SNMP Auth options =  -v2c -c nlt
/usr/bin/snmpget -v2c -c nlt -Osqnv -M /opt/librenms/mibs udp:fmg_australis:161 ENTITY-MIB::entPhysicalMfgName.1
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c nlt
/usr/bin/snmpget -v2c -c nlt -Oqv -M /opt/librenms/mibs udp:fmg_australis:161 1.3.6.1.4.1.674.10895.3000.1.2.100.1.0
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c nlt
/usr/bin/snmpget -v2c -c nlt -Oqv -M /opt/librenms/mibs udp:fmg_australis:161 .1.3.6.1.4.1.39165.1.6.0
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c nlt
/usr/bin/snmpget -v2c -c nlt -Oqv -M /opt/librenms/mibs udp:fmg_australis:161 SML-MIB::product-Name.0
No Such Object available on this agent at this OID

DEBUG: SNMP Auth options =  -v2c -c nlt
/usr/bin/snmpget -v2c -c nlt -Oqvn -M /opt/librenms/mibs udp:fmg_australis:161 ENTITY-MIB::entPhysicalDescr.1
No Such Object available on this agent at this OID


SQL[[0;33mUPDATE `devices` set `last_discovered` =NOW(),`type` ='',`last_discovered_timetaken` ='0.548' WHERE `device_id` = '61'[0m] Discovered in 0.548 seconds


SQL[[0;33mINSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','fmg_australis','1455279793.5653','0.558','1')[0m] ./discovery.php fmg_australis 2016-02-12 09:23:14 - 1 devices discovered in 0.558 secs
MySQL: Cell[1/0s] Row[1/0s] Rows[1/0s] Column[0/0s] Update[1/0s] Insert[1/0s] Delete[0/0s]
]0;root@librenms: /opt/librenmsroot@librenms:/opt/librenms# 
]0;root@librenms: /opt/librenmsroot@librenms:/opt/librenms# ./poller [K
poller.php           poller-service.py    
poller-service.init  poller-wrapper.py    
]0;root@librenms: /opt/librenmsroot@librenms:/opt/librenms# ./poller.php -h fmg_australis -d -m os -r -f
LibreNMS 2015.master Poller
commit e9b53896cb20fb72571fc05f9f9434c64240ef7b

DEBUG!
Starting polling run:


SQL[[0;33mSELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'fmg_australis' ORDER BY `device_id` ASC[0m] 
SQL[[0;33mSELECT * FROM `devices` WHERE `device_id` = '61'[0m] 
SQL[[0;33mSELECT * FROM devices_attribs WHERE `device_id` = '61'[0m] fmg_australis 61 generic 

SQL[[0;33mINSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('3','3','0','22.6','23.1','22.8','61',NOW())[0m] DEBUG: SNMP Auth options =  -v2c -c nlt
/usr/bin/snmpget -v2c -c nlt -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:fmg_australis:161 sysObjectID.0
SNMPv2-SMI::enterprises.12356.103.1.3004

Generic :(

Hardware:  Version:  Features:  Serial: 
[[0;31mRRD Disabled[0m]RRD[[0;32mupdate /opt/librenms/rrd/fmg_australis/poller-perf.rrd N:0.472[0m] [[0;31mRRD Disabled[0m]RRD[[0;32mupdate /opt/librenms/rrd/fmg_australis/ping-perf.rrd N:22.8[0m] Polled in 0.472 seconds
Updating fmg_australis
Array
(
    [last_ping] => Array
        (
            [0] => NOW()
        )

    [last_ping_timetaken] => 22.8
    [last_polled] => Array
        (
            [0] => NOW()
        )

    [last_polled_timetaken] => 0.472
)

SQL[[0;33mUPDATE `devices` set `last_ping` =NOW(),`last_ping_timetaken` ='22.8',`last_polled` =NOW(),`last_polled_timetaken` ='0.472' WHERE `device_id` = '61'[0m] UPDATED!

SQL[[0;33mSELECT * FROM device_groups ORDER BY name[0m] 
SQL[[0;33mSELECT alert_schedule.schedule_id FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '61' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1[0m] 
SQL[[0;33mSELECT * FROM device_groups ORDER BY name[0m] 
SQL[[0;33mSELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '61' ) || alert_map.target = '61'  )[0m]  #1:
SQL[[0;33mSELECT state FROM alerts WHERE rule_id = '1' && device_id = '61' ORDER BY id DESC LIMIT 1[0m] 
SQL[[0;33mSELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'devices' && COLUMN_NAME = 'device_id'[0m] 
SQL[[0;33mSELECT * FROM devices WHERE (devices.device_id = '61') && ( (  ( devices.status = 0  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  )  )  = "1"            )[0m]  NOCHG  #2:
SQL[[0;33mSELECT state FROM alerts WHERE rule_id = '2' && device_id = '61' ORDER BY id DESC LIMIT 1[0m] 
SQL[[0;33mSELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'devices' && COLUMN_NAME = 'device_id'[0m] 
SQL[[0;33mSELECT * FROM devices WHERE (devices.device_id = '61') && (devices.uptime < "300"  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  = "1"          )[0m]  NOCHG  #3:
SQL[[0;33mSELECT state FROM alerts WHERE rule_id = '3' && device_id = '61' ORDER BY id DESC LIMIT 1[0m] 
SQL[[0;33mSELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'bgpPeers' && COLUMN_NAME = 'device_id'[0m] 
SQL[[0;33mSELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_NAME = 'devices' && COLUMN_NAME LIKE "%\_id"[0m] 
SQL[[0;33mSELECT * FROM bgpPeers,devices WHERE (( devices.device_id = bgpPeers.device_id ) && bgpPeers.device_id = '61') && (bgpPeers.bgpPeerState != "established"  &&   (  ( devices.status = 1  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  )  )  = "1")[0m]  NOCHG  #4:
SQL[[0;33mSELECT state FROM alerts WHERE rule_id = '4' && device_id = '61' ORDER BY id DESC LIMIT 1[0m] 
SQL[[0;33mSELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'bgpPeers' && COLUMN_NAME = 'device_id'[0m] 
SQL[[0;33mSELECT * FROM bgpPeers WHERE (bgpPeers.device_id = '61') && (bgpPeers.bgpPeerFsmEstablishedTime < "300"  &&  bgpPeers.bgpPeerState = "established")[0m]  NOCHG  #5:
SQL[[0;33mSELECT state FROM alerts WHERE rule_id = '5' && device_id = '61' ORDER BY id DESC LIMIT 1[0m] 
SQL[[0;33mSELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'ports' && COLUMN_NAME = 'device_id'[0m] 
SQL[[0;33mSELECT * FROM ports WHERE (ports.device_id = '61') && ( (  ( ports.ifOperStatus = "down"  &&  ports.ifAdminStatus != "down"  &&   (  ( ports.deleted = 0  &&  ports.ignore = 0  &&  ports.disabled = 0 )  )  )  )  = "1"        )[0m]  NOCHG  #7:
SQL[[0;33mSELECT state FROM alerts WHERE rule_id = '7' && device_id = '61' ORDER BY id DESC LIMIT 1[0m] 
SQL[[0;33mSELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'sensors' && COLUMN_NAME = 'device_id'[0m] 
SQL[[0;33mSELECT * FROM sensors WHERE (sensors.device_id = '61') && (sensors.sensor_current > sensors.sensor_limit)[0m]  NOCHG  #8:
SQL[[0;33mSELECT state FROM alerts WHERE rule_id = '8' && device_id = '61' ORDER BY id DESC LIMIT 1[0m] 
SQL[[0;33mSELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'sensors' && COLUMN_NAME = 'device_id'[0m] 
SQL[[0;33mSELECT * FROM sensors WHERE (sensors.device_id = '61') && (sensors.sensor_current < sensors.sensor_limit_low)[0m]  NOCHG  #9:
SQL[[0;33mSELECT state FROM alerts WHERE rule_id = '9' && device_id = '61' ORDER BY id DESC LIMIT 1[0m] 
SQL[[0;33mSELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'processors' && COLUMN_NAME = 'device_id'[0m] 
SQL[[0;33mSELECT * FROM processors WHERE (processors.device_id = '61') && (processors.processor_usage >= "86"   )[0m]  NOCHG  #14:
SQL[[0;33mSELECT state FROM alerts WHERE rule_id = '14' && device_id = '61' ORDER BY id DESC LIMIT 1[0m] 
SQL[[0;33mSELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'mempools' && COLUMN_NAME = 'device_id'[0m] 
SQL[[0;33mSELECT * FROM mempools WHERE (mempools.device_id = '61') && (mempools.mempool_descr REGEXP "Main.*"    &&  mempools.mempool_perc >= "85" )[0m]  NOCHG 


SQL[[0;33mINSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','fmg_australis','1455279820.6548','0.509','1','librenms\n')[0m] ./poller.php fmg_australis 2016-02-12 09:23:41 - 1 devices polled in 0.509 secs

MySQL: Cell[1/0s] Row[20/0.01s] Rows[12/0.01s] Column[0/0s] Update[1/0s] Insert[2/0s] Delete[0/0s]
]0;root@librenms: /opt/librenmsroot@librenms:/opt/librenms#
