### ISSUE TITLE
Add Aggregate Totals in gprint area

### ISSUE THREAD

**Issue by slother** [librenms/librenms#2989]
In Total Graph for ports of type : Transit/Peering we can see values for each port in graph legend, but there is no "Total" for all of them. Example:

![aggregate totals](https://cloud.githubusercontent.com/assets/17193609/13001952/eb2b6218-d16a-11e5-9930-0aa51c42a470.png)

**Comment by Rosiak** [comment]
:+1:

**Comment by f0o** [comment]
Already exists, add '/noagg=0/' or similar

On 13 February 2016 21:25:21 CET, "Søren Rosiak" <notifications@github.com> wrote:
>:+1: 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2989#issuecomment-183747507

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by laf** [comment]
Doesn't work on peering/transit page :/

**Comment by slother** [comment]
Yes, it doesn't work on peering/transit page. So far as workaround I changed varable in common.inc.php to have it enabled globally.

**Comment by laf** [comment]
What did you change out of interest?

**Comment by slother** [comment]
It's a dirty change, I'm no programmer ;) In includes/graphs/common.inc.php just changed $noagg varable to false:

if (isset($_GET['noagg'])) {
    $noagg = ((bool) $_GET['noagg']);
}
else {
    $noagg = false;
}

It would be nice if you could set it globally in config

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by taking-care-of-business** [comment]
Hello,

I have aggregated my transit and peering ports, but I would also like to have them show the sum of all the ports as mentioned above. 

![transit-nototals](https://cloud.githubusercontent.com/assets/24301416/22704666/7f544198-ed36-11e6-8770-ca6bd627d1d9.png)

**Comment by taking-care-of-business** [comment]
Let me know what additional info is needed for your team to look into it further.

**Comment by chasgames** [comment]
Any news on this? I would also very much like this feature.

**Comment by MrBlueSkye** [comment]
+1

**Comment by chasgames** [comment]
Well putting $graph_array['noagg'] = false; into pages seems to work.

How about we support a config variable ? something like inside
html/includes/print-interface-graphs.inc.php

```$graph_array['noagg'] = $config['graph_type']['noagg'];```

What do you think @laf shall i make a pull request?

**Comment by laf** [comment]
@chasgames you can do. This type of thing would be better as a graph option the user can set but we are a bit away from doing that so could be a temp option for now.
