### ISSUE TITLE
Barracuda Spam Filter support

### ISSUE THREAD

**Issue by CaptainLame** [librenms/librenms#2993]
A saw that basic Barracuda load balancer support was in but nothing for the Spam Firewall units.
Here are the MIBs from Barracuda for the BSF units: https://techlib.barracuda.com/display/bsfv51/barracuda+spam+firewall+snmp+mib
https://techlib.barracuda.com/display/BSFv51/Barracuda+Reference+MIB

Is there any other data that would be needed? I have a BSF 600 that I admin, so no problem getting data.

**Comment by Rosiak** [comment]
@CaptainLame 
Can you post a snmpwalk with mibs loaded and without?
I'll sort it out then

**Comment by CaptainLame** [comment]
Attached is with no Barracuda MIBS loaded.
When I put the Barracuda MIBs in ~/.snmp/mibs and run this:
`snmpwalk -v2c -c <community> -m ALL bsf1 1.3.6.1.4.1.20632`
it returns this:
`Barracuda-REF::barracuda = No Such Object available on this agent at this OID`
I also tried:
`snmpwalk -v2c -c <community> -m ~/.snmp/mibs/Barracuda-REF-MIB:~/.snmp/mibs/Barracuda-SPAM-MIB  bsf1 1.3.6.1.4.1.20632`
And it returned the same error as above.
I could very well be doing something wrong command-wise; typically I'm just checking if a device will respond to SNMP, then I load it in our dying Zenoss install.
I can snmpget sub-values of the 1.3.6.1.4.1.20632 tree as shown in the Syntax section of this page: https://techlib.barracuda.com/BSF/SNMPGuide#

Attachment: [bsf.nomib.txt](https://github.com/librenms/librenms/files/128293/bsf.nomib.txt)

**Comment by Rosiak** [comment]
Looks incomplete, could you please try:
```
snmpwalk -v2c -c COMMUNITY HOSTNAME .
```

**Comment by CaptainLame** [comment]
Certainly. Please see attached. Thanks for looking into this.
[bsf.walk.txt](https://github.com/librenms/librenms/files/129432/bsf.walk.txt)

**Comment by Rosiak** [comment]
This still look like a incomplete walk to me, not returning anything referred on their website.

**Comment by Rosiak** [comment]
Closing
