### ISSUE TITLE
Unable to view "All Ports" page

### ISSUE THREAD

**Issue by wwardcollective** [librenms/librenms#2995]
Hello.

I am having an issue viewing the 'All Ports' page. It returns a 500 error when using the browsers developer tools. I am able to view the other ports pages such as errors and disabled.

![image](https://cloud.githubusercontent.com/assets/13353930/13022542/44622476-d1b0-11e5-99f9-299d384ff459.png)

I am not sure what is the issue is as I have been digging through the PHP (I am an extreme novice of PHP).

![image](https://cloud.githubusercontent.com/assets/13353930/13022644/ceb9f298-d1b0-11e5-811f-312bc90af3f1.png)

**Comment by laf** [comment]
Increase the max mem in php.ini. Can't remember the config option

**Comment by wwardcollective** [comment]
I will try that. In the next couple hours.

**Comment by wwardcollective** [comment]
"memory_limit ="

Bumping this value from the default 128M to 1024M (might be overkill) did the trick for me.

Thank you, a lot.
