### ISSUE TITLE
Dashboard graphs should filter "spikes"

### ISSUE THREAD

**Issue by mtehonica** [librenms/librenms#2996]
I have a dashboard to show network throughput and it appears that something caused a "spike".  Not sure if it was a reporting issue from my device or a legitimate network bandwidth spike but that's not my concern.  (This is a home internet connection which is 300mpbs / 20mbps)

My issue is that now my graphs become useless because all my "real" data is washed out by this spike.  Can the graphs be tailored to only show 95th percentile or something?  See screenshot here: http://imgur.com/I8BvPeP

**Comment by laf** [comment]
Please see: http://docs.librenms.org/Extensions/RRDTune/

And also the scripts/removespikes.php can remove spikes from existing graphs.

**Comment by mtehonica** [comment]
Worked great, didn't know that existed!  Thanks!
