### ISSUE TITLE
/ports/ repeats ports

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#30]
Hi,

the /ports/ view is displaying each port twice.

I didnt dig into it yet but wanted to let you know of it for the log ;)

Cheers

**Comment by f0o** [comment]
So this issue just occurred again.

I figured out why, it's an issue with the Memcached check within `html/pages/ports.inc.php`

Working on a fix.

**Comment by gadago** [comment]
Not sure if it's related to this, but I also get duplicate BGP/iBGP and OSPF entries under routing.

**Comment by f0o** [comment]
The best fix for this particular issue is to remove the memcached checks on `ports.inc.php`. It has no use whatsoever. It was meant to relief the MySQL from pulling so much data but it's healthier for the SQL to handle one big `*` query than potentially hundreds `*` queries with 1 result each. So the Memcache pulling that's done afterwards will always just create duplicates. I will make a PR to remove those 3-4 lines.

@gadago it seems to be an unrelated similarity, the routing display makes no use of Memcached so it's duplications have a different cause...
