### ISSUE TITLE
Monitor via SSH

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#3000]
Hi,

Is there any way to monitor a machine that supports SNMP, but I can only access via SSH? Wanting to monitor (RAID) on a remote machine that I use for backups.

Thanks!

**Comment by laf** [comment]
I'm not sure I understand this question. Do you mean snmp can't be accessed remotely so you need to do it over ssh? You'd need to just establish an ssh tunnel on the LibreNMS box and then it's business as normal.

**Comment by arrmo** [comment]
Yep, agreed - you have it correct!

Is there a way to set up a fixed (always on) SSH link (tunnel) ... perhaps as a service? This would handle it, I agree there.

Thanks!

**Comment by bsiders** [comment]
Although slightly different, I was hoping this was a request for monitoring over SSH using SOAP; like in PRTG

**Comment by f0o** [comment]
@bsiders there is a different issue regarding your request, I'm currently on phone so dont have it at hand but use the search until I get to a laptop later today

**Comment by ekoyle** [comment]
Maybe use socksify and run ssh as a socks proxy?  First, find a way to run `ssh -D127.0.0.1:12345 host` persistently.

If everything should go over the proxy, you could use a wrapper script to run the commands in your crontab:

```sh
#!/bin/sh

exec /usr/bin/env SOCKS_SERVER=127.0.0.1:12345 socksify $@

```

then something like

```
*/5 * * * * /path/to/wrapper /opt/librenms/poller-wrapper.php
```

in your crontab.

**Comment by ekoyle** [comment]
Maybe that wouldn't work with the mysql connection, though.

**Comment by laf** [comment]
No further info provided but this doesn't look like a LibreNMS issue to fix.
