### ISSUE TITLE
Email via Office365 (Exchange Online)

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#3001]
Hi,

I'm trying to send email via Exchange Online, but I can't get it working ... perhaps the sending email address is the issue (it HAS to match to the account).

Has anyone gotten this working? And to that end ... if I go to the Global Settings, Alerting Settings - should Test Transport not send a test email? At least for me it doesn't seem to be.

Thanks!

**Comment by laf** [comment]
I can't see why it wouldn't work with O365. Do you have the correct settings for using it's smtp service?

**Comment by arrmo** [comment]
I believe so ... :-). I am using it to send email from the command line, seems to work fine.

But perhaps I'm being an idiot here (distinct possibility!). If I hit "Test Transport" ... should it send a test email? Just making sure it should be doing what I assume.

Thanks!

**Comment by doogieconsulting** [comment]
I was having similar issues, couldn't get the messages to send at all so i setup postfix as a relay. Authenticates without issue and is fairly secure so long as it can only relay from LibreNMS host.

**Comment by arrmo** [comment]
Hi,

That makes sense, but is it really a solution? Why not try to fix the root cause, and not need an intermediary email server?

Thanks!

**Comment by murrant** [comment]
@arrmo https://technet.microsoft.com/en-us/library/dn554323(v=exchg.150).aspx

**Comment by arrmo** [comment]
Hi,

Yep, I have this working from other applications - just not sure the email is connecting properly from LibreNMS. Any debug info available for the test email perhaps?

Thanks!

**Comment by f0o** [comment]
Sadly no, the best you can do in debugging is installing postfix as relay... SMTP is being handled by a 3rd party SMTP-Class which isnt well implemented in regards to debugging...
For the log, php's own mail() is just a wrapper to sendmail.

**Comment by laf** [comment]
You can change:

"            $mail->SMTPDebug  = false;" in

includes/functions.php

Set it to false. Then run ./alerts.php -d to get some debug info (you may need to stop alerts in cron to catch triggering an alert).

**Comment by arrmo** [comment]
Hi,

Thanks for the pointer. Changed the setting as you note, and disabled alerts in cron. Then ran alerts.php - lots of SQL output, but also the following mixed in,

Issuing Alert-UID #4611/1: ; ; mail => ERROR

Any possible way to get more details? I did notice that there is an SMTPDebug variable also in includes/phpmailer/class.phpmailer.php ... should this be changed also?

Thanks!

**Comment by laf** [comment]
Can you post the output? I expect it to show ERROR as it's not returning what we expect anymore due to the debug.

**Comment by arrmo** [comment]
OK, I take it back - it seems to be working now. A recent update seems to have added an entry for "From email address" ... correct? This one is key for Exchange Online, and seems to have fixed the issue. I'm not sure why, but I don't seem to be getting updates daily - but I manually did a git pull, and now this is there => fixes the issue.

Thanks!!!

**Comment by f0o** [comment]
Git pull = bad!!!
Use daily.sh instead please
