### ISSUE TITLE
Device Configuration Hierarchy

### ISSUE THREAD

**Issue by adaniels21487** [librenms/librenms#3002]
This issue proposes a device configuration hierarchy.
This is a system where a devices configuration is built from a combination of configuration elements stored in 3 levels: Global, Group, Device

In this system an array of configuration information is built by:
1. The array is initially populated with all the Global configuration.
2. Array elements are overwritten if set at the group level, where the device is a member.
   - If a device is member of multiple groups, these are processed in alphabetical order (or a priority field can be added to groups).
3. Array elements are overwritten if set at the device level.

This gives us the ability to set default values (global level) and modify them if needed, at any point in the hierarchy.

All device configuration in (Device -> Edit): Device Settings, SNMP, Alert Settings, IPMI, Misc. should be migrated.

Thanks,
Aaron

**Comment by murrant** [comment]
@adaniels21487 I agree it would be great if this was designed with v2 in mind and backported to v1.

**Comment by adaniels21487** [comment]
@murrant,
I am a bit snowed under at work this week. I'll get something to you over the weekend.

Aaron

**Comment by adaniels21487** [comment]
@murrant take a look at https://github.com/adaniels21487/librenms/tree/feature/devconfighierarchy for what I was planning.

**Comment by murrant** [comment]
I was thinking of something that would merge all those into the same table and allow for arbitrary relations. (user for example)

**Comment by adaniels21487** [comment]
@murrant 
So you are looking at all config not just device?

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/device-configuration-hierarchy/837
