### ISSUE TITLE
Debug to File

### ISSUE THREAD

**Issue by adaniels21487** [librenms/librenms#3003]
d_echo()  should have a configuration option to output log messages to file.
when enabled, the function should be able to determine where it is being called from and should log to the corresponding location:

- poller - ./logs/poller-$device['hostname'].log
- discovery - ./logs/discovery-$device['hostname'].log
- gui - ./logs/gui.log

LibreNMS should also include a sample logrotate configuration file which will rotate these and existing log files.

**Comment by laf** [comment]
I'm not sure I'm a fan of this personally. I can't see where it would be of use. just mho.

**Comment by adaniels21487** [comment]
Hi Mate,
My best use case is developing on the GUI side.
Currently I do a d_echo to see what a variable is holding and it vanishes into the ether.

As I play, I am finding that there is not too much that actually uses d_echo. most things still use:
```if ($debug) {```

So, what I am proposing would only be useful if a whole lot of other work happened to make all debug's use d_echo.

This kind of logging is easily available in laravel so with the rewrite being planned, I am not sure this is worth the effort...

Aaron

**Comment by laf** [comment]
Hey, I use the function logfile() we have to write to logs/librenms.log from the webui when I'm debugging stuff.

**Comment by adaniels21487** [comment]
Ha! I didnt even know that this function existed.
I'm happy to close this issue. is that ok with you @laf.

**Comment by laf** [comment]
Fine by me :)
