### ISSUE TITLE
Image for Overall Trafikk and Processor don't show.  Empty src=""

### ISSUE THREAD

**Issue by MindTooth** [librenms/librenms#3006]
![image](https://cloud.githubusercontent.com/assets/35828/13043053/d654fdba-d3c5-11e5-93ac-ce64ec3e8b4d.jpeg)

Take a look on the picture, and you'll see.  If I hover, I get the correct image, but not when viewing the device itself.

I'm using the latest version of LibreNMS.

**Comment by laf** [comment]
Run ./validate.php and if no issues reported then right click where the image should be, copy _image url_, paste into browser and add &debug=true. Paste the output onto dpaste.de and link here.

**Comment by MindTooth** [comment]
I'm sorry.

The only error reported is the NGINX log directory is owned by other user.

I can't copy img url, because it's blank.  I only get my main URL (https://hulder/) when I try to copy and paste using the right click in Firefox.  Adding debug doesn't do a think.

I'm using PHP 7.  And I can't remember if the problem occurred before the upgrade.

**Comment by laf** [comment]
Check your browsers javascript console. Not sure if php 7 would cause this but I'm sure @f0o has tested it ok.

**Comment by MindTooth** [comment]
![image](https://cloud.githubusercontent.com/assets/35828/13068589/1c939162-d47d-11e5-99ee-7684cc1387b2.jpeg)

The only two errors I receive.  I find it strange that the src tag to be empty.  I can't load the graph inside the data-original tag either.

**Comment by laf** [comment]
If you do what I mentioned earlier with the graph.php url from data-original it will / should give us some output.

**Comment by MindTooth** [comment]
I had "File not found" when opened it in one of my browser IIRC. (I combine Windows and OS X on work somethings, so I don't remember the specific browser atm.  I'll report back on monday.)

**Comment by laf** [comment]
so graph.php?blah...... was 404? What web server are you using?

**Comment by MindTooth** [comment]
Yeah.  I'm using NGINX with PHP 7.0, and MariaDB.

**Comment by laf** [comment]
If it's a 404 then it sounds like the rewrites aren't correct.

**Comment by MindTooth** [comment]
I'll take a look on Monday when I return for work.  Don't have the configs easily at hand.

Thanks for the help so far :+1:

**Comment by laf** [comment]
np. it's the only thing I can think it would be.

**Comment by MindTooth** [comment]
My bad:
<pre>graph /tmp/Ke8vLTF8sDgLfHaS.png -g -l 0 -u 100 -E --start 1456044000 --end 1456130400 --width --height -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --only-graph --font LEGEND:7:DejaVuSansMono --font AXIS:6:DejaVuSansMono --font-render-mode normal COMMENT:'Now Min Max Avg\l' DEF:ds0=/opt/librenms/rrd/172.16.1.9/processor-procurve-fixed-0.rrd:usage:AVERAGE DEF:ds0min=/opt/librenms/rrd/172.16.1.9/processor-procurve-fixed-0.rrd:usage:MIN DEF:ds0max=/opt/librenms/rrd/172.16.1.9/processor-procurve-fixed-0.rrd:usage:MAX LINE1.25:ds0#CC0000:' ' AREA:ds0#CC000020 GPRINT:ds0:LAST:%5.2lf%s GPRINT:ds0min:MIN:%5.2lf%s GPRINT:ds0max:MAX:%5.2lf%s GPRINT:ds0:AVERAGE:'%5.2lf%s\n' HRULE:0#555555

command returned 0 (ERROR: width below 10 pixels )

graph /tmp/Ke8vLTF8sDgLfHaS.png -g --alt-autoscale-max --rigid -E --start 1456044000 --end 1456130400 --width --height -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --only-graph --font LEGEND:7:DejaVuSansMono --font AXIS:6:DejaVuSansMono --font-render-mode normal HRULE:0#555555 --title='Draw Error'

command returned 0 (ERROR: width below 10 pixels ) </pre>

**Comment by MindTooth** [comment]
Disabling lazy don't do much.  Figured I would test that.

**Comment by laf** [comment]
I thought you said going to graph.php in a browser produced a 404?

**Comment by MindTooth** [comment]
I forgot to remove the /device/etc.-part before /graph.php.  Now I get an "error with image" without &debug=truer not the URL.

**Comment by Rosiak** [comment]
Still the same or found a solution?
