### ISSUE TITLE
Empty Graphs for Ports (eth0)

### ISSUE THREAD

**Issue by sennico** [librenms/librenms#3008]
I recently setup LibreNMS and my graphs look good expect for ports which are still not populating, specially eth0. I have attached my php debug and SQL debug below. Any ideas?

`SQL Debug
select config_name,config_value from config
select * from graph_types
SELECT * FROM `plugins` WHERE `plugin_active` = '1'
DELETE FROM `session` WHERE `session_expiry` < '1455549369'
SELECT * FROM `session` WHERE `session_username` = '' AND session_value=''
SELECT username,password FROM `users` WHERE `username`= 'sennico'
SELECT `level` FROM `users` WHERE `username` = 'sennico'
SELECT `user_id` FROM `users` WHERE `username` = 'sennico'
SELECT * FROM devices_perms WHERE user_id = '1'
SELECT * FROM ports_perms WHERE user_id = '1'
SELECT * FROM bill_perms WHERE user_id = '1'
SELECT COUNT(service_id) FROM services WHERE service_status = '0'
SELECT COUNT(port_id) FROM `ports` WHERE `ifOperStatus` = 'down' AND `ifAdminStatus` = 'up' AND `ignore` = '0'
SELECT COUNT(*) FROM `links`
SELECT COUNT(bgpPeer_id) FROM bgpPeers AS B where (bgpPeerAdminStatus = 'start' OR bgpPeerAdminStatus = 'running') AND bgpPeerState != 'established'
SELECT 1 from `packages` LIMIT 1
SELECT `type`,COUNT(`type`) AS total_type FROM `devices` AS D WHERE 1 GROUP BY `type` ORDER BY `type`
SELECT * FROM device_groups ORDER BY name
SELECT D.device_id,location FROM devices AS D GROUP BY location ORDER BY location
SELECT COUNT(*) FROM ports AS I, devices AS D WHERE I.`deleted` = '0' AND D.`device_id` = I.`device_id` AND I.`ignore` = '0' AND D.`ignore` = '0' AND (I.`ifInErrors_delta` > '0' OR I.`ifOutErrors_delta` > '0')
SELECT COUNT(*) FROM ports AS I, devices AS D WHERE I.`deleted` = '0' AND D.`device_id` = I.`device_id` AND (I.`ignore` = '1' OR D.`ignore` = '1')
SELECT * FROM `ports` AS P, `devices` as D WHERE P.`deleted` = '1' AND D.device_id = P.device_id
SELECT sensor_class,COUNT(sensor_id) AS c FROM sensors GROUP BY sensor_class ORDER BY sensor_class
SELECT DISTINCT(`app_type`) AS `app_type` FROM `applications` ORDER BY `app_type`
SELECT COUNT(bgpPeer_id) from `bgpPeers` LEFT JOIN devices AS D ON bgpPeers.device_id=D.device_id WHERE D.device_id IS NOT NULL
SELECT COUNT(ospf_instance_id) FROM `ospf_instances` WHERE `ospfAdminStat` = 'enabled'
SELECT COUNT(cef_switching_id) from `cef_switching`
SELECT COUNT(vrf_id) from `vrfs`
SELECT `C`.`id`,`C`.`device_id`,`C`.`type`,`C`.`label`,`C`.`status`,`C`.`disabled`,`C`.`ignore`,`C`.`error`,`CP`.`attribute`,`CP`.`value` FROM `component` as `C` LEFT JOIN `component_prefs` as `CP` on `C`.`id`=`CP`.`component` WHERE ( `type` = 'Cisco-OTV' )
SELECT COUNT(*) from `plugins` WHERE plugin_active = '1'
select count(notifications.notifications_id) from notifications where not exists( select 1 from notifications_attribs where notifications.notifications_id = notifications_attribs.notifications_id and notifications_attribs.user_id = '1')
select count(notifications.notifications_id) from notifications inner join notifications_attribs on notifications.notifications_id = notifications_attribs.notifications_id where notifications_attribs.key = "sticky" && notifications_attribs.value = 1
SELECT `device_id` FROM `ports` WHERE `port_id` = '6'
SELECT * FROM `ports` WHERE `port_id` = '6'
SELECT * FROM `devices` WHERE `device_id` = '8'
SELECT COUNT(`device_id`) FROM `devices` WHERE `last_polled` <= DATE_ADD(NOW(), INTERVAL - 15 minute) AND `ignore` = 0 AND `disabled` = 0 AND status = 1
36 total SQL queries run.`

`PHP Debug
Array ( [errno] => 8 [errstr] => Undefined index: influxdb [errfile] => /opt/librenms/includes/influxdb.inc.php [errline] => 15 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchrows_sec [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 276 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchrows [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 277 )
Array ( [errno] => 8 [errstr] => Undefined index: sess_id [errfile] => /opt/librenms/html/includes/authenticate.inc.php [errline] => 65 )
Array ( [errno] => 8 [errstr] => Undefined index: token [errfile] => /opt/librenms/html/includes/authenticate.inc.php [errline] => 65 )
Array ( [errno] => 8 [errstr] => Undefined offset: 1 [errfile] => /opt/librenms/html/includes/authentication/mysql.inc.php [errline] => 38 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchrow_sec [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 331 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchrow [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 332 )
Array ( [errno] => 8 [errstr] => Undefined variable: navbar [errfile] => /opt/librenms/html/includes/print-menubar.php [errline] => 26 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchcell_sec [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 365 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchcell [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 366 )
Array ( [errno] => 8 [errstr] => Undefined variable: param [errfile] => /opt/librenms/html/includes/print-menubar.php [errline] => 139 )
Array ( [errno] => 8 [errstr] => Undefined index: _ObjCacheSkell [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 47 )
Array ( [errno] => 8 [errstr] => Undefined index: _ObjCache [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 51 )
Array ( [errno] => 8 [errstr] => Undefined index: ports [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 60 )
Array ( [errno] => 8 [errstr] => Undefined index: params [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 98 )
Array ( [errno] => 8 [errstr] => Undefined index: params [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 98 )
Array ( [errno] => 8 [errstr] => Undefined variable: used_sensors [errfile] => /opt/librenms/html/includes/print-menubar.php [errline] => 333 )
Array ( [errno] => 8 [errstr] => Undefined variable: sep [errfile] => /opt/librenms/html/includes/print-menubar.php [errline] => 357 )
Array ( [errno] => 8 [errstr] => Undefined variable: sep [errfile] => /opt/librenms/html/includes/print-menubar.php [errline] => 369 )
Array ( [errno] => 2 [errstr] => array_keys() expects parameter 1 to be array, null given [errfile] => /opt/librenms/html/includes/print-menubar.php [errline] => 374 )
Array ( [errno] => 2 [errstr] => Invalid argument supplied for foreach() [errfile] => /opt/librenms/html/includes/print-menubar.php [errline] => 374 )
Array ( [errno] => 8 [errstr] => Undefined index: menu [errfile] => /opt/librenms/html/includes/plugins.inc.php [errline] => 49 )
Array ( [errno] => 8 [errstr] => Undefined index: notifications [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 60 )
Array ( [errno] => 8 [errstr] => Undefined index: params [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 98 )
Array ( [errno] => 8 [errstr] => Undefined index: widescreen [errfile] => /opt/librenms/html/pages/graphs.inc.php [errline] => 7 )
Array ( [errno] => 8 [errstr] => Undefined index: device [errfile] => /opt/librenms/html/pages/graphs.inc.php [errline] => 29 )
Array ( [errno] => 8 [errstr] => Undefined variable: auth [errfile] => /opt/librenms/html/includes/graphs/port/auth.inc.php [errline] => 3 )
Array ( [errno] => 8 [errstr] => Undefined index: rewrite_if [errfile] => /opt/librenms/includes/rewrites.php [errline] => 94 )
Array ( [errno] => 8 [errstr] => Undefined index: port [errfile] => /opt/librenms/includes/common.php [errline] => 648 )
Array ( [errno] => 8 [errstr] => Undefined index: port [errfile] => /opt/librenms/includes/common.php [errline] => 648 )
Array ( [errno] => 8 [errstr] => Undefined index: port [errfile] => /opt/librenms/includes/common.php [errline] => 648 )
Array ( [errno] => 8 [errstr] => Undefined index: port [errfile] => /opt/librenms/includes/common.php [errline] => 648 )
Array ( [errno] => 8 [errstr] => Undefined index: port [errfile] => /opt/librenms/includes/common.php [errline] => 648 )
Array ( [errno] => 8 [errstr] => Undefined index: port [errfile] => /opt/librenms/includes/common.php [errline] => 648 )
Array ( [errno] => 8 [errstr] => Undefined index: port [errfile] => /opt/librenms/includes/common.php [errline] => 648 )
Array ( [errno] => 8 [errstr] => Undefined index: port [errfile] => /opt/librenms/includes/common.php [errline] => 648 )
Array ( [errno] => 8 [errstr] => Undefined index: port [errfile] => /opt/librenms/includes/common.php [errline] => 648 )
Array ( [errno] => 8 [errstr] => Undefined index: port [errfile] => /opt/librenms/includes/common.php [errline] => 648 )
Array ( [errno] => 8 [errstr] => Undefined index: port [errfile] => /opt/librenms/includes/common.php [errline] => 648 )
Array ( [errno] => 8 [errstr] => Undefined index: port [errfile] => /opt/librenms/includes/common.php [errline] => 648 )
Array ( [errno] => 8 [errstr] => Undefined index: port [errfile] => /opt/librenms/includes/common.php [errline] => 648 )
Array ( [errno] => 8 [errstr] => Undefined index: port [errfile] => /opt/librenms/includes/common.php [errline] => 648 )
Array ( [errno] => 8 [errstr] => Undefined index: port [errfile] => /opt/librenms/includes/common.php [errline] => 648 )
Array ( [errno] => 8 [errstr] => Undefined index: legend [errfile] => /opt/librenms/html/pages/graphs.inc.php [errline] => 138 )
Array ( [errno] => 8 [errstr] => Undefined index: previous [errfile] => /opt/librenms/html/pages/graphs.inc.php [errline] => 149 )
Array ( [errno] => 8 [errstr] => Undefined index: showcommand [errfile] => /opt/librenms/html/pages/graphs.inc.php [errline] => 158 )
Array ( [errno] => 8 [errstr] => Undefined index: legend [errfile] => /opt/librenms/html/includes/functions.inc.php [errline] => 506 )
Array ( [errno] => 8 [errstr] => Undefined index: showcommand [errfile] => /opt/librenms/html/pages/graphs.inc.php [errline] => 186 )
49 total PHP issues / errors.`

**Comment by laf** [comment]
Please run ./validate.php

**Comment by sennico** [comment]
Version info:
[WARN]    Your install is out of date: 8a3c685997cdc358b25f0096006dabf14921c318
DB Schema: 100
PHP: 5.6.11-1ubuntu3.1
MySQL: 10.0.23-MariaDB-0ubuntu0.15.10.1
RRDTool: 1.5.4
SNMP: NET-SNMP version: 5.7.3

[OK]      Database connection successful
sennico@ns505382:/opt/librenms$

**Comment by laf** [comment]
Right click a graph, get the _image url_ and paste into browser, add &debug=true to the end and paste the output.

**Comment by sennico** [comment]
OK u:0.05 s:0.01 r:0.06
graph /tmp/MiYq7vVmJ8d4QbCX.png --alt-autoscale-max --rigid -E --start 1455466500 --end 1455552900 --width 1296 --height 300 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal DEF:outoctets=/opt/librenms/rrd/localhost/port-id6.rrd:OUTOCTETS:AVERAGE DEF:inoctets=/opt/librenms/rrd/localhost/port-id6.rrd:INOCTETS:AVERAGE DEF:outoctets_max=/opt/librenms/rrd/localhost/port-id6.rrd:OUTOCTETS:MAX DEF:inoctets_max=/opt/librenms/rrd/localhost/port-id6.rrd:INOCTETS:MAX CDEF:octets=inoctets,outoctets,+ CDEF:doutoctets=outoctets,-1,* CDEF:outbits=outoctets,8,* CDEF:outbits_max=outoctets_max,8,* CDEF:doutoctets_max=outoctets_max,-1,* CDEF:doutbits=doutoctets,8,* CDEF:doutbits_max=doutoctets_max,8,* CDEF:inbits=inoctets,8,* CDEF:inbits_max=inoctets_max,8,* VDEF:totin=inoctets,TOTAL VDEF:totout=outoctets,TOTAL VDEF:tot=octets,TOTAL VDEF:95thin=inbits,95,PERCENT VDEF:95thout=outbits,95,PERCENT CDEF:d95thoutn=doutbits,-1,* VDEF:d95thoutn95=d95thoutn,95,PERCENT CDEF:d95thoutn95n=doutbits,doutbits,-,d95thoutn95,-1,*,+ VDEF:d95thout=d95thoutn95n,FIRST COMMENT:'bps Now Ave Max 95th %\n' AREA:inbits_max#D7FFC7: AREA:inbits#90B040: LINE:inbits#608720:'In ' GPRINT:inbits:LAST:%6.2lf%s GPRINT:inbits:AVERAGE:%6.2lf%s GPRINT:inbits_max:MAX:%6.2lf%s GPRINT:95thin:%6.2lf%s\n AREA:doutbits_max#E0E0FF: AREA:doutbits#8080C0: LINE:doutbits#606090:'Out' GPRINT:outbits:LAST:%6.2lf%s GPRINT:outbits:AVERAGE:%6.2lf%s GPRINT:outbits_max:MAX:%6.2lf%s GPRINT:95thout:%6.2lf%s\n GPRINT:tot:'Total %6.2lf%sB' GPRINT:totin:'(In %6.2lf%sB' GPRINT:totout:'Out %6.2lf%sB)\l' LINE1:95thin#aa0000 LINE1:d95thout#aa0000

command returned 0 (1377x397 )

-rw-rw-r-- 1 www-data www-data 15273 Feb 15 11:20 /tmp/MiYq7vVmJ8d4QbCX.png

**Comment by MindTooth** [comment]
I hate to ask, but care to post a picture?  So I can see it it's related to my [own](3006) problem.

**Comment by sennico** [comment]
Sure @MindTooth, this is my eth0 Interface graph

![graph php](https://cloud.githubusercontent.com/assets/8100969/13075211/89b75608-d477-11e5-87c3-96c12924b50c.png)

**Comment by MindTooth** [comment]
Thank you :+1: Not related though.  Good luck :-)

**Comment by sennico** [comment]
not sure about the etiquette for bumping an issue so its its frowned upon sorry for being a jerk.

**Comment by sennico** [comment]
@laf Just noticed that one graph has a tiny bit of data but the rest still remain blank under eth0. Not sure if that changes anything 
![2016-02-23_22-06-13](https://cloud.githubusercontent.com/assets/8100969/13274549/1012fe20-da7a-11e5-867c-2799fff6415a.jpg)

**Comment by laf** [comment]
Well that shows you are getting data but normally it's 0. Are you actually expecting to see network traffic on this port?

**Comment by sennico** [comment]
Yea there's been hundreds of GBs over the last couple weeks that would have gone through.

**Comment by laf** [comment]
Check your snmpd.conf, you may be restricting the options returned.

**Comment by laf** [comment]
Please re-open with further information if you need further help
