### ISSUE TITLE
Hosts added twice with hostname + FQDN

### ISSUE THREAD

**Issue by TheBigfoot** [librenms/librenms#3012]
We have set up LibreNMS following the documentation and added several hosts.
We have added the hosts by the hostname, now we do see several entries with the full host name FQDN which is probably coming from the auto discovery. Unfortunately this ends now with multiple hosts beeing twice in our system.

How is this controlled if hosts are added a second time, because, we do not see this for all hosts. 

$config['discovery_by_ip'] is not defined at all.

How would be the proper suggestion to get rid of this problem?

Thanks in advance!

**Comment by MindTooth** [comment]
I've seen this as well.  In our case, only the ESXI hosts get added as multiple servers.

**Comment by paulgear** [comment]
I've seen this as well once; will try to replicate when I get a chance.

**Comment by craig** [comment]
I'm pretty sure this is caused by lldpd autodiscovery.
