### ISSUE TITLE
Frontend complains about failing to update/acknowledge/etc

### ISSUE THREAD

**Issue by ekoyle** [librenms/librenms#3015]
It looks like #2936 introduced some regressions throughout the web interface.

The javascript library you are using treats responses differently based on their content-type, and many of the pages are returning a simple string rather than javascript.   This is especially evident when acknowledging an alert, etc. as the page will present the user with an error even though the operation succeeded.

**Comment by ekoyle** [comment]
The following restored the old behavior in the places we noticed it the most:

    librenms@librenms:~$ git diff html/ajax_form.php
    diff --git a/html/ajax_form.php b/html/ajax_form.php
    index 3851d5b..87913a3 100644
    --- a/html/ajax_form.php
    +++ b/html/ajax_form.php
    @@ -29,7 +29,7 @@ if (!$_SESSION['authenticated']) {
     
     if (preg_match('/^[a-zA-Z0-9\-]+$/', $_POST['type']) == 1) {
         if (file_exists('includes/forms/'.$_POST['type'].'.inc.php')) {
    -        header('Content-type: application/json');
    +        //header('Content-type: application/json');
             include_once 'includes/forms/'.$_POST['type'].'.inc.php';
         }
     }
    librenms@librenms:~$

**Comment by laf** [comment]
Fixed.
