### ISSUE TITLE
Interfaces containing 'irtual' are not polled

### ISSUE THREAD

**Issue by shamsway** [librenms/librenms#3016]
In https://github.com/librenms/librenms/blob/master/includes/functions.php, function "is_port_valid", the code below skips interfaces containing the string 'irtual'.  By default ESX returns interfaces that contain this string, so there is probably a better way to accomplish this.  I know cisco will return virtual interfaces that are typically not polled, but ideally there is a way to give the user a choice about how they want this handled.

`
    if (strstr($port['ifDescr'], "irtual")) {
        $valid = 0;
    }`

**Comment by murrant** [comment]
That could probably be converted to $config['os']['cisco']['bad_if'] = "irtual"; in definitions.php, but I have no idea which OS it should be applied to.

**Comment by laf** [comment]
Or just $config['bad_if'][] = 'irtual';

**Comment by Rosiak** [comment]
bad_if fixes this, closing

**Comment by paulgear** [comment]
Did anyone actually change the code to fix this?  It looks like it's still unconditionally ignoring bad_if if "irtual" is anywhere in the description.
