### ISSUE TITLE
Mac OSX

### ISSUE THREAD

**Issue by amartins** [librenms/librenms#3017]
LibreNMS is not sorting OSX El Capitan (10.11.3) as an Apple icon. 

Darwin Sulla.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
Operating System	Generic Device
Object ID	enterprises.8072.3.2.255

**Comment by Rosiak** [comment]
./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -r -f -d -m os
An snmpwalk of the device:
snmpbulkwalk -v2c -c COMMUNITY HOSTNAME .

**Comment by amartins** [comment]
Hey @Rosiak,

Please find the requested information below:

root@itacoatiara:/opt/librenms# ./discovery.php -h itaipu -d -m os
LibreNMS 2015.master Discovery
Version info:
Commit SHA: f236741e49dce4494df8bd69a410445de2793542
DB Schema: 117
PHP: 5.6.20-0+deb8u1
MySQL: 5.5.49-0+deb8u1
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2.1

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1]
SQL[SELECT revision FROM `dbSchema`] DB Schema already up to date.

SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE 'itaipu' ORDER BY device_id DESC]
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '8'] itaipu 8 generic /usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs udp:HOSTNAME:1161 SNMPv2-MIB::sysDescr.0Darwin Sulla.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

/usr/bin/snmpget -v2c -c COMMUNITY -Ovqn -M /opt/librenms/mibs udp:HOSTNAME:1161 SNMPv2-MIB::sysObjectID.0.*.4.1.8*

| Darwin Sulla.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64 | .1.3.6.1.4.1.8072.3.2.255 | /usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:1161 1.3.6.1.4.1.674.10895.3000.1.2.100.1.0No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Osqnv -M /opt/librenms/mibs udp:HOSTNAME:1161 ENTITY-MIB::entPhysicalMfgName.1No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:1161 SNMPv2-SMI::enterprises.14988.2No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:1161 .1.3.6.1.4.1.39165.1.6.0No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqvn -M /opt/librenms/mibs udp:HOSTNAME:1161 ENTITY-MIB::entPhysicalDescr.1No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:1161 SML-MIB::product-Name.0No Such Object available on this agent at this OID


OS: /usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs udp:HOSTNAME:1161 SNMPv2-MIB::sysDescr.0Darwin Sulla.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

/usr/bin/snmpget -v2c -c COMMUNITY -Ovqn -M /opt/librenms/mibs udp:HOSTNAME:1161 SNMPv2-MIB::sysObjectID.0.*.4.1.8*

| Darwin Sulla.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64 | .1.3.6.1.4.1.8072.3.2.255 | /usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:1161 1.3.6.1.4.1.674.10895.3000.1.2.100.1.0No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Osqnv -M /opt/librenms/mibs udp:HOSTNAME:1161 ENTITY-MIB::entPhysicalMfgName.1No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:1161 SNMPv2-SMI::enterprises.14988.2No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:1161 .1.3.6.1.4.1.39165.1.6.0No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqvn -M /opt/librenms/mibs udp:HOSTNAME:1161 ENTITY-MIB::entPhysicalDescr.1No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:1161 SML-MIB::product-Name.0No Such Object available on this agent at this OID


SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '8' AND `attrib_type` = 'poll_mib' ]
SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='server',`last_discovered_timetaken` ='2.742' WHERE `device_id` = '8'] Discovered in 2.742 seconds


SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','itaipu','1466215043.7455','2.800','1')] ./discovery.php itaipu 2016-06-17 22:57:26 - 1 devices discovered in 2.800 secs
MySQL: Cell[1/0s] Row[4/0s] Rows[0/0s] Column[0/0s] Update[1/0s] Insert[1/0s] Delete[0/0s]
root@itacoatiara:/opt/librenms# ./poller.php -h itaipu -r -d -d -m os
LibreNMS 2015.master Poller
Version info:
Commit SHA: f236741e49dce4494df8bd69a410445de2793542
DB Schema: 117
PHP: 5.6.20-0+deb8u1
MySQL: 5.5.49-0+deb8u1
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2.1

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'itaipu' ORDER BY `device_id` ASC]
SQL[SELECT * FROM `devices` WHERE `device_id` = '8']
SQL[SELECT * FROM `vrf_lite_cisco` WHERE `device_id` = '8']
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '8'] itaipu 8 generic
/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:HOSTNAME:1161 sysObjectID.0SNMPv2-SMI::enterprises.8*

/usr/bin/snmpget -v2c -c COMMUNITY -OQnUst -m SNMPv2-MIB:HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs udp:HOSTNAME:1161 sysUpTime.0 sysLocation.0 sysContact.0 sysName.0 sysObjectID.0sysUpTime.0 = 44729469
sysLocation.0 = Itaipu, Niter..i Rio de Janeiro, Brazil
sysContact.0 = alessandromartins@me.com
sysName.0 = Sulla.local
sysObjectID.0 = enterprises.8*

/usr/bin/snmpget -v2c -c COMMUNITY -OvQ -m SNMPv2-MIB:HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs udp:HOSTNAME:1161 sysDescr.0Darwin Sulla.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

/usr/bin/snmpget -v2c -c COMMUNITY -OQnUst -m HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs udp:HOSTNAME:1161 snmpEngineTime.0 hrSystemUptime.0snmpEngineTime.0 = 447295
hrSystemUptime.0 = 173123049

Using hrSystemUptime (1731230s)
[RRD Disabled]RRD[update /opt/librenms/rrd/itaipu/uptime.rrd N:1731230] Uptime: 20 days, 53m 50s
Generic :(

Hardware:  Version:  Features:  Serial:

SQL[SELECT * FROM device_groups ORDER BY name]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='8' && (devices.hostname REGEXP "mgemal") LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='8' && (devices.hostname REGEXP "terabyterj") LIMIT 1]
SQL[SELECT `device_group_id` FROM `device_group_device` WHERE `device_id`='8'] [RRD Disabled]RRD[update /opt/librenms/rrd/itaipu/poller-perf.rrd N:1.515] Polled in 1.515 seconds
Updating itaipu
Array
(
    [uptime] => 1731230
    [last_polled] => Array
        (
            [0] => NOW()
        )

    [last_polled_timetaken] => 1.515
)

SQL[UPDATE `devices` set `uptime` ='1731230',`last_polled` =NOW(),`last_polled_timetaken` ='1.515' WHERE `device_id` = '8'] UPDATED!

SQL[SELECT `device_group_id` FROM `device_group_device` WHERE `device_id`='8']
SQL[SELECT alert_schedule.schedule_id FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '8' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1]
SQL[SELECT `device_group_id` FROM `device_group_device` WHERE `device_id`='8']
SQL[SELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '8' ) || alert_map.target = '8'  )]

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','itaipu','1466215209.6994','1.887','1','itacoatiara.2sec.com.br\n')] ./poller.php itaipu 2016-06-17 23:00:11 - 1 devices polled in 1.887 secs

MySQL: Cell[3/0s] Row[6/0s] Rows[5/0.01s] Column[3/0s] Update[1/0.01s] Insert[1/0.02s] Delete[0/0s]
root@itacoatiara:/opt/librenms#

**Comment by amartins** [comment]
[snmpbulkwalk.txt](https://github.com/librenms/librenms/files/321551/snmpbulkwalk.txt)
