### ISSUE TITLE
Web UI issues

### ISSUE THREAD

**Issue by MonsieurC** [librenms/librenms#3022]
Good morning everyone !

I have a couple of issues since last week regarding the WebUI.
First issue: when i try to add or modify an alert rule or a device group or use the acknowledge button on the alert, i am prompted with an error message :
![error_alert](https://cloud.githubusercontent.com/assets/16794051/13102966/6342c5ee-d552-11e5-89ea-5ee2fd73bd19.JPG)
The strange thing is that the alert or group is correctly created and works perfectly fine.
The second, which is related to the first one i think, is that when i edit a rule (alert or group), for changing any parameter, the name of rule is deleted. I have to edit it a second time and re enter the name of the rule again.
I have no idea where to look to fix this.
Any ideas ?

**Comment by Ultra2D** [comment]
I am seeing this behaviour too. 

Also, when editing old rules, they are parsed incorrectly:
`%devices.uptime &lt; &quot;300&quot; &amp;&amp; %devices.disabled = &quot;0&quot; &amp;&amp; %devices.ignore = &quot;0&quot; &&x`
in stead of
`%devices.status != "1" && %devices.disabled = "0" && %devices.ignore = "0" `

Furthermore, Max, Delay and Interval do not show any value on the rule overview page or when editing a rule, although they do exist in the database:
> {"mute":false,"count":"-1","delay":300,"invert":false,"interval":300}

**Comment by laf** [comment]
Duplicate #3015
