### ISSUE TITLE
STP alerting

### ISSUE THREAD

**Issue by Ultra2D** [librenms/librenms#3023]
The addition of STP is great!

I am trying to generate an alert on topology changes:
> %stp.timeSinceTopologyChange < "300"

That should generate an alert when a topology change occurred the last 5 minutes, but it does not work as expected. It seems like the less than comparison does not work on this value. timeSinceTopologyChange is a varchar(32) (utf8_general_ci) in the database. Alerts stop only if the first three characters of the string are higher than 300, so for example 17869886 still generates an alert.

**Comment by laf** [comment]
If you wouldn't mind testing this schema change:

```sql
ALTER TABLE  `stp` CHANGE  `timeSinceTopologyChange`  `timeSinceTopologyChange` INT UNSIGNED NOT NULL
```

**Comment by Ultra2D** [comment]
Not at all, and it looks like you nailed it.

**Comment by vitalisator** [comment]
@Ultra2D, please notice that on root bridges timeSinceTopologyChange could have ever 0 value

**Comment by Ultra2D** [comment]
@vitalisator, I am not saying my test is even a good way to check for STP changes, it's just that I stumbled upon a timestamp that gets compared as a string, which will be fixed.
