### ISSUE TITLE
Canon iR-ADV printers not recognized (+ solution)

### ISSUE THREAD

**Issue by GeorgesDick** [librenms/librenms#3025]
Hello.

I'm currently evaluating libreNMS, and it seems that it is unable to recognize my Canon printers. Browsing source code I discovered a file named "includes/discovery/os/canonprinter.inc.php" with a "Canon MF" test. I added a "Canon iR", and now my printers are successfully recognized.

Now, my "includes/discovery/os/canonprinter.inc.php" file look like:

<?php
if (!$os) {
    // Canon Multifunction Printer/Scanner
    if (strstr($sysDescr, 'Canon MF')) {
        $os = 'canonprinter';
    }
    if (strstr($sysDescr, 'Canon iR')) {
        $os = 'canonprinter';
    }
}

Hope it helps,
Georges

**Comment by 21let** [comment]
Perfect, thank you. I also need to monitoring the copying machine Canon iR and iR ADV (see. IR-ADV C3325i and iR 2520)

**Comment by GeorgesDick** [comment]
Thanks!

**Comment by 21let** [comment]
Canon printer irc3325 is discovered Vendor "GENERIC" :-(

![image](https://cloud.githubusercontent.com/assets/13964136/13802926/ff4e01ca-eb40-11e5-9ca8-9ad74dc2ed10.png)

**Comment by murrant** [comment]
@21let This is issue #3236, it is only the icon, we are working on a fix.
