### ISSUE TITLE
'Issue alerts to admins' not working when '%devices' is used

### ISSUE THREAD

**Issue by Ultra2D** [librenms/librenms#3027]
First off, this might be an edge case.

Alerting settings:
Issue alerts to admins = yes
Issue alerts to sysContact = no
Send alerts to default contact only = no
Default contact = empty

In this case, as soon as a rule includes %devices, alerts are not sent via the mail transport. I created a test rule that sends emails every minute. After adding a `%devices.hostname = "<host>"` filter to it, no email are sent (even after re-enabling the rule). The alerts do get logged:
> Issuing Alert-UID #488616/1: ; ; mail => OK; ; ; ; ; ; ;

The cause seems to be that $alert['details']['rule'] does not exist (the only subarray is $alert['details']['interval']), and GetContacts returns no contacts, see https://github.com/librenms/librenms/blob/c72d8cca84db76c6e37c970df81f3d2de929688f/includes/alerts.inc.php#L286 .

Another example, which emails alerts for localhost, but not for any switch at all:
> %devices.status = "1" && %devices.disabled != "1" && %devices.ignore != "1"

**Comment by f0o** [comment]
Will test it tomorrow

**Comment by laf** [comment]
If you've not updated today, please do so and try again.

**Comment by Ultra2D** [comment]
Actually, I have already updated a couple of times today.

**Comment by Ultra2D** [comment]
This is quite similar to #3062 , but in my case mail is logged as successful in the event log, but postfix does not log anything.
Only enabling "Send alerts to default contact only" with a valid address does not help, while other email alerts still arrive.

**Comment by Ultra2D** [comment]
Works with both "Send alerts to default contact only"  and "Issue alerts to admins".
