### ISSUE TITLE
sysContact updated every 5th minute

### ISSUE THREAD

**Issue by tobiasa1** [librenms/librenms#3032]
After 00.15 tonight (17 Feb), I have a few devices that is updating sysContact every 5th minute which created many new rows in the event log at every poller run.

I have only seen this behavior on devices where sysContact is not only an e-mail address but also includes the contact name. For example: Sven Svensson <sven@svensson.local>.

**Comment by f0o** [comment]
Pull, should be fixed now

On 17 February 2016 20:50:37 CET, Tobias Andersson <notifications@github.com> wrote:
>After 00.15 tonight (17 Feb), I have a few devices that is updating
>sysContact every 5th minute which created many new rows in the event
>log at every poller run.
>
>I have only seen this behavior on devices where sysContact is not only
>an e-mail address but also includes the contact name. For example: Sven
>Svensson <sven@svensson.local>.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/3032

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tobiasa1** [comment]
Yup, works. :)
