### ISSUE TITLE
Distributed polling "Eternal Master" condition

### ISSUE THREAD

**Issue by pblasquez** [librenms/librenms#3033]
There is a condition that can be created in which the master node is never allowed to exit and begin polling again.

For example, if:
 - you have 3 pollers total
 - two of those pollers each have a device that take >300s to poll (assuming 5m cronjobs)
 - the other poller becomes master

This master node is now bound in a non-polling condition until a window appears in which both of the other nodes finish, which might never happen depending on the overlap timings.

Practically, this means that at least 2 pollers are needed for each polling group in order to assure polling occurs for that group in the case that one poller is stuck as an eternal master.

It would make more sense to either: have (a) dedicated master(s), allow the master node to run multiple wrappers, or design a masterless architecture.

**Comment by f0o** [comment]
The way it is now is almost masterless. The master only exists to ensure no double polling occurs and to be a last resort when communications fail while polling. In case of lost memcached connection the pollers will finish their current task and quit, handing over all the rest to the master to poll.

Not sure how to orchestrate nodes that cant talk to eachother to not double poll devices in these situations.

Open for discussion :)

**Comment by laf** [comment]
I'd honestly say the easiest fix is to fix the devices not polling within 300 seconds. We obviously don't know your network but I've never come across that issue. 3 pollers covering over 3000 devices.

**Comment by pblasquez** [comment]
Setting individual poller.php cronjobs for the >300s devices is my current workaround, but this is a lot to track and remember.

Is it really the right answer to say that distributed polling is only supported if all polling times are <300s?  My environment is only ~1100 devices but some of them are very old/poor performing, and they will not be replaced so long as they do their job.

The only problem is that I cannot yet think of a better way. Hoping someone reads this issue and has an epiphany.

**Comment by pblasquez** [comment]
I have found a compromise that works for me, if I let the master continue spawning poller-wrappers instead of dying this works fine for me.

If I created a pull request with a configuration setting for this would that be acceptable?

**Comment by laf** [comment]
@librenms/reviewers?

We chatted about this on irc last night and I'm not a fan of the proposed solution as it will just mean poller-wrappers continue to spawn even when devices are still polling. When this happens on single pollers it creates problems with graphs in traffic and who knows what else other things going wrong (dbUpdates being called out of sequence maybe, consumes resources meaning an OOM is more likely).

**Comment by paulgear** [comment]
I'm not a fan of continuing to spawn poller-wrappers either (although there's nothing to stop @pblasquez creating a local customisation to support this).  I think a better option might be to create a separate poller for slow devices, give it a much larger number of threads, and then manually assign all of the > 300s devices to that group.

**Comment by pblasquez** [comment]
@paulgear It seems the code allows for honoring poller groups without participating in distributed polling ... in that I can try assigning 1 polling group per poller and turning off distributed polling, if only for the "slow poller".

Will report back.

**Comment by pblasquez** [comment]
Ok so that did the trick and I will use this method until a better one comes along.  I will need to make a PR for discovery.php but it is a minor change.  Thanks all.

**Comment by pblasquez** [comment]
This is fixed with #3086
