### ISSUE TITLE
CBQoS policies not detected (no graphs displayed)

### ISSUE THREAD

**Issue by mikeysgi** [librenms/librenms#3038]
I have enabled the cbqos discovery module for a cisco 4331 router (also tried it on a 2911), the discovery process showed that it detected the mibs, and the components section shows the qos policies, but in the cbqos graphing tab nothing is displayed.

please see attached screen shots for system info 

![cbqos screen](https://cloud.githubusercontent.com/assets/17320509/13152828/b8ed2f54-d636-11e5-9794-8feca708e898.png)
![components](https://cloud.githubusercontent.com/assets/17320509/13152836/c3552712-d636-11e5-9e53-fa06ef5b3470.png)
![version](https://cloud.githubusercontent.com/assets/17320509/13152851/d1993f20-d636-11e5-8d5f-3faa2a9d4f72.png)

Thanks for any help!

**Comment by laf** [comment]
@adaniels21487 anything you can help with on this?

**Comment by adaniels21487** [comment]
Hi @mikeysgi
Discovery appears to be doing its thing but there are no policies being shown.
Can you please pastebin the debug output of a discovery and poller cycle for the device.

Aaron

**Comment by mikeysgi** [comment]
Hi @adaniels21487 
here is the discovery debug http://pastebin.com/Bvf8DzZ0
and the poller debug http://pastebin.com/n1t5bBhK

thanks for looking in to this!
mike

**Comment by adaniels21487** [comment]
Hi @mikeysgi 
These are private pastes and I cant see them. Are you able to open them up, otherwise please unicast to lists@daniels.id.au

**Comment by mikeysgi** [comment]
@adaniels21487 
sorry I changed them to public now

**Comment by adaniels21487** [comment]
Hi @mikeysgi,
Ok, discovery looks good it is finding 2 policies one each on ifindex 2 and 3.
in the polling paste I can see several of these:
    ERROR: Unable to connect to rrdcached: Permission denied

I dont know if they are an issue with your environment but I suspect they are more of an issue running the poller as a different user.

But that got me thinking. I have not tested this with rrdcached, and the select policy code does test if the rrd exists.
I am guessing that in an rrdcached environment the rrd is not in this location:
    $config['rrd_dir'].'/'.$device['hostname'].'/port-'.$port['ifIndex'].'-cbqos-*.rrd'

I will look at a patch to test existance another way.
To make sure I am barking up the right tree, can you please confirm that the RRD's are not in that location.

Thanks,
Aaron

**Comment by laf** [comment]
At present we don't do any file checks through rrdcached so that is correct at the moment.

**Comment by adaniels21487** [comment]
I found the issue, $options was not re-initialised so the filter being applied was for a different module the filters components.

the PR fixes this and also no longer tests for RRD existance.

**Comment by mikeysgi** [comment]
@adaniels21487 @laf 
thank you both for your help, working great now!

**Comment by breeman1** [comment]
I wonder if you can help me as my policy class maps are not being graphed; only the class-default is graphed, with CBQOS enabled. See attached image.

![image](https://cloud.githubusercontent.com/assets/16717388/13810654/98cdb22c-eb79-11e5-9c4b-8cb756b8fdc9.png)

It then ran discovery and poller instances with debuging turn on and it looks like the values for these policy class maps are being retrieved. 
See the logs here, https://dpaste.de/8Rbn and here, https://dpaste.de/BhSk. 

I will appreciate your help in finding out why they are not being graphed.

**Comment by laf** [comment]
Please run ./validate.php

**Comment by breeman1** [comment]
![image](https://cloud.githubusercontent.com/assets/16717388/13816001/600858fe-eb95-11e5-97ad-e4fe8960291d.png)

**Comment by breeman1** [comment]
![image](https://cloud.githubusercontent.com/assets/16717388/13816135/d896b892-eb95-11e5-9532-66cf02c08f92.png)

**Comment by adaniels21487** [comment]
Hi @breeman1,
The discovery and poller looks good, the system is collecting the data.
Is it possible you are not looking at the correct policy?

The initial screenshot you sent was of the Shape_WAN policy, this only contains one class, class-default. To see the classes in the child policy: Egress_Encrypted_Flow_Separation you need to select it at the top of the page.

Can you please post a screenshot of the Egress_Encrypted_Flow_Separation policy:
![image](https://cloud.githubusercontent.com/assets/13431617/13829418/9fe6daea-ec12-11e5-9094-c4044f8ee22b.png)

Thanks,
Aaron

**Comment by breeman1** [comment]
Brilliant, it works. I had clicked on the little expansion + sign instead of clicking the actual policy name. Thank you for your help:).
