### ISSUE TITLE
Add totals to aggregated graphs

### ISSUE THREAD

**Issue by tobiasa1** [librenms/librenms#3039]
It would be nice to have total aggregated traffic in the legend of aggregated graphs (customers, transit, transit/peering, peering). That would make it much easier to see peak traffic, ATH etc.

Something like this: :grinning: 

![aggr](https://cloud.githubusercontent.com/assets/5029241/13170320/8047aa16-d6eb-11e5-947d-8163442613e8.png)

**Comment by laf** [comment]
Duplicate #2989
