### ISSUE TITLE
Two Factor authentication - Being able to use the same 6 digit pin code many times.

### ISSUE THREAD

**Issue by eikik87** [librenms/librenms#3042]
The only reason for Two Factor authentication is to prevent a hacker from being able to brake into your system with one attack. So for example my user and pass, might get keylogged. But my phone that has to be stolen in order to generate a 6 digit key is needed aswell.

But I can use same 6 digit pin code generated by the google app using the two factor authentication many times. So 1 keylogger is going to get both my password and pin code.

Why am I able to use the same Pin code using your 2FA many times, and what does it offer me rather then just more complex way of generating 6 digit password or pin code.

I don't see the security in this. Is there a way to improve this? Or am I not setting this 2FA up correctly?

Or at least do you know the time it takes the pin code I used to expire and become invalid? And is there a way to reduce that time limit down?

**Comment by f0o** [comment]
Try changing the otpWindow constant in html/includes/authentication/twofactor.lib.php to 0.
That will break RFC mandated sync windows and enforce new tokens every time.

On 19 February 2016 21:57:03 CET, eikik87 <notifications@github.com> wrote:
>The only reason for Two Factor authentication is to prevent a hacker
>from being able to brake into your system with one attack. So for
>example my user and pass, might get keylogged. But my phone that has to
>be stolen in order to generate a 6 digit key is needed aswell.
>
>But I can use same 6 digit pin code generated by the google app using
>the two factor authentication many times. So 1 keylogger is going to
>get both my password and pin code.
>
>Why am I able to use the same Pin code using your 2FA many times, and
>what does it offer me rather then just more complex way of generating 6
>digit password or pin code.
>
>I don't see the security in this. Is there a way to improve this? Or am
>I not setting this 2FA up correctly?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/3042

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by eikik87** [comment]
I did that, changed nothing. I can use the same key over and over again.

**Comment by f0o** [comment]
Will test after lunch

**Comment by eikik87** [comment]
Any news?

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
