### ISSUE TITLE
cronic script problem on FreeBSD

### ISSUE THREAD

**Issue by mayheart** [librenms/librenms#3048]
For cronic can we get the script helper changed from 

#!/bin/bash to

#!/usr/bin/env bash

This shouldn't break the script on other platforms.

**Comment by murrant** [comment]
@mayheart are you running multiple versions of bash or something?

**Comment by mayheart** [comment]
bash isn't part of the default OS on FreeBSD, it's an additional package which gets installed to /usr/local/bin

**Comment by murrant** [comment]
Wouldn't it be better to just `ln -s /usr/local/bin/bash /bin/bash`?

I usually only see /usr/bin/env used when the executable can be switched by a tool (such as python).  This does add the ability for bash to be found anywhere in $PATH, which could lead to unexpected or insecure behavior.

Just want to make sure before accepting this change...

**Comment by laf** [comment]
We use env in all other scripts hence the initial suggestion I expect. I'd personally not be concerned over $PATH misuse.

**Comment by murrant** [comment]
sounds fine.
