### ISSUE TITLE
Restricted user seeing information about routers he does not have access too under Devices/Ports

### ISSUE THREAD

**Issue by eikik87** [librenms/librenms#3055]
I want to give my customers access to use Librenms. But I only want to limit the user to see specific routers.

When I do that, and log in as that user. Under Devices/Ports on the device, I can see information on the right side about routers within the same Subnet or using same RFC 1918 subnet. Then it lists up our MGMT IP addresses/hostnames that we use in Librenms.

So for example Vlan 1, that is on many routers. And they all have 192.168.1.0/24 subnet. So that router sees every single other router information because they are using same IP subnet.

That is ok, except I only want the routers he has access to too be listed up there. Not those he does not have access too.

There is one other router in this picture that is 'bold' that he has access too. And it is active link. Other routers are just gray and not link.

![image](https://cloud.githubusercontent.com/assets/13901674/13215853/4a946186-d950-11e5-928a-1bd2d13ef3a9.png)

**Comment by eikik87** [comment]
Temp fix for this for me, is to disable port relationship. Thanks to Laf, I put this in config.php '$config['enable_port_relationship'] = false;'. And this feature is gone. Works for me. I couldn't wait longer for fix on this.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
