### ISSUE TITLE
SNMP-SCAN list the IP addresses. Give more info then just * . - +

### ISSUE THREAD

**Issue by eikik87** [librenms/librenms#3058]
While I'm scanning, I get alot of " \* - . " That is actually very helpfull information while doing the scan, if you could add the information what IP address gets *, what IP address gets -, what ip address gets .

That is actually very good information and tells me a lot of things, for example SNMP community on that device might not be configured correctly. Or accesslist is needed to be fixed. So if you could add behind for example "-", what IP address that is, I could go into that device and fix the config that makes it fail to get scanned correctly.

Easily fixable in the script myself. Just thought you wanted to add it, as I'm pretty sure many people would find it helpful.

For example, change the snmp-scan.php 

```
    if ($test['result'] === false) {
        echo '.';
      **  echo "$host\n";**
        continue;
    }
    if (ip_exists($host)) {
        $stats['known']++;
        echo '*';
       ** echo "$host\n";**
        continue;
    }
    foreach (array('udp','tcp') as $transport) {
        if ($device_id !== false && $device_id > 0) {
            $stats['added']++;
            echo '+';
           ** echo "$host\n";**
        } else if ($device_id === 0) {
            $stats['failed']++;
            echo '-';
```

*\*                echo "$host\n";**
                break;

Will give you easier information to read.

If you would then add information about each into a log that user could read and work with to go over his routers. Would be very helpful.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by eikik87** [comment]
I'm no longer using the 'SNMP-Scan', as we built a system using API to inject devices into Librenms to be monitored. But other then that the Script could use some facelift in my opinion. Because it is troublesome to scan 1000 devices and you don't know what device was not scanned into the system or for what reason. You only see huge list of + - . etc. That tells me nothing when I come next day and try to go into the devices to fix the reason why the devices were not scanned into the system. But you can close this if you want, not a problem for me anymore.
