### ISSUE TITLE
No Email for "Devices up/down"

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#3062]
Hi,

Just to understand ... should an email be sent for the alert "Devices up/down" (assuming email is configured of course)? I'm getting email for sensor excursions, etc. ... but not for this particular alert.

Thanks!

**Comment by laf** [comment]
Yes it should.

**Comment by arrmo** [comment]
OK, digging a bit more in parallel - for the machines that aren't raising this flag, the sysContact (email) address is not set. But, under General Alerting settings I have entered "Send alerts to default contact only" (and set an email address). But I still see under these machines the error

Could not issue critical alert for rule 'Devices up/down' to transport 'mail'

Perhaps it's not accepting the setting for default contact only?

**Comment by arrmo** [comment]
OK, that's not it ... :-(. I went in and disabled "Issue alerts to sysContact" => only try to send to the default contact, still the same error message. Will keep looking.

**Comment by Ze7a** [comment]
Hi,

I have the same problem.

Recent events:
2016-02-23 04:55:02	Could not issue critical alert for rule 'Devices up/down' to transport 'mail'
2016-02-23 04:50:12	Device status changed to Down

------

But the alert issue 'SWAP usage' works well: 
2016-02-23 04:57:01	Issued critical alert for rule 'SWAP usage' to transport 'mail'

**Comment by laf** [comment]
Either of you willing to give me access to your install?

**Comment by arrmo** [comment]
FYI, still having an issue with this in the latest release (yep, ran daily.sh to update). One machine is alerting, but the other is now saying "Could not issue recovery for rule 'Devices up/down' to transport 'mail'" ... recovery? it's supposed to just send an email like the other, no?

BTW, is there a also a setting to say (effectively) ... only send email on state change, not every 5 minutes if a machine stays down? ... :-).

Thanks!

**Comment by murrant** [comment]
@arrmo Did you run daily.sh on both?

Also, to not have recurring alerts, set the interval to 0 instead of 5 minutes on the rule.

**Comment by arrmo** [comment]
Yep, ran on both. It seems like the setting did not take effect until after the (monitored) machine came back, then it all cleared out.

Thanks!
