### ISSUE TITLE
Add Huawei Server RH8100 V3

### ISSUE THREAD

**Issue by jhonkim** [librenms/librenms#3075]
Download mib file https://github.com/jhonkim/nirs.git

**Comment by Rosiak** [comment]
Can you supply a snmpwalk from the device?

**Comment by jhonkim** [comment]
Yes, snmpwalk working

**Comment by jhonkim** [comment]
./discovery.php -h HOSTNAME -d -m os

DEBUG!

SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '1' AND `attrib_type` = 'poll_mib' ] MIB: registering
snmptranslate -M /opt/librenms/mibs -m HUAWEI-SERVER-iBMC-MIB HUAWEI-SERVER-iBMC-MIB::enterprises.2011.2.235 2>/dev/null
This doesn't look like a MIB:
MIB: Could not find HUAWEI-SERVER-iBMC-MIB::enterprises.2011.2.235

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.39165.1.6.0No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 SML-MIB::product-Name.0No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 1.3.6.1.4.1.674.10895.3000.1.2.100.1.0No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Osqnv -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalMfgName.1No Such Object available on this agent at this OID

OS: /usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0Hardware management system

**Comment by Rosiak** [comment]
What OS is running on this thing?(Something like iDrac or ILO?)

**Comment by jhonkim** [comment]
The Intelligent Baseboard Management Controller (iBMC) is a control unit used to manage servers, and it complies with the management specification Intelligent Platform Management Interface 2.0 (IPMI2.0) of the server field.

**Comment by Rosiak** [comment]
Could you please attach a paste of the following command?
```
snmpbulkwalk -v2c -c COMMUNITY HOSTNAME .
```

**Comment by Rosiak** [comment]
Any news?
