### ISSUE TITLE
[Question] AutoLogin to show dasbhoard

### ISSUE THREAD

**Issue by alejandroparedero** [librenms/librenms#3080]
Hello there.

Is there any method to autologin to LibreNMS sending the parameters directly from URL? 

I'd like to integrate the dashboard on a iframe in another monitoring tool and actually is aksing for credentials each time I open the frame.

As far as I read the API method is called via "curl" and return some JSON information.

Thank you.

**Comment by f0o** [comment]
Append `username` and `password` parameters.

Ensure strong SSL before doing this ;)

On 24 February 2016 12:42:37 CET, Alejandro Paredero <notifications@github.com> wrote:
>Hello there.
>
>Is there any method to autologin to LibreNMS sending the parameters
>directly from URL? 
>
>I'd like to integrate the dashboard on a iframe in another monitoring
>tool and actually is aksing for credentials each time I open the frame.
>
>As far as I read the API method is called via "curl" and return some
>JSON information.
>
>Thank you.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/3080

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by alejandroparedero** [comment]
It works like a charm! Thank you @f0o  !!
