### ISSUE TITLE
ipv6 counters

### ISSUE THREAD

**Issue by papage** [librenms/librenms#3084]
Hi all,

On a Cisco 4500X and maybe other switches as well, the ipv6 traffic on VLAN ifs, can not be measured with the classic counters that are used for ipv4 traffic. The classic counters on VLAN interfaces only include ipv4 traffic
Ex. on a VLAN interface with ipv6, the traffic counters can be found on ipIfStatsHCOutOctets.ipv6 tree and not the classic IfHCOutOctets.

Is it possible to add to the interface graphs, the above mib (when ipv6 is enabled on a interface and when the switch is a 4500X - and perhaps others)?

Regards,
Sp

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
