### ISSUE TITLE
Proper way to update distributed poller enviroment?

### ISSUE THREAD

**Issue by masonke** [librenms/librenms#3085]
This is a question for clarity

What is the proper way to perform updates is a distributed poller environment? Having all the pollers and the master updating the schema and other database changes can cause some race conditions. 

What we are doing is running daily.sh on the Master and git pull after on the pollers. Is that the right way to do this?
Thanks!

**Comment by laf** [comment]
We personally have everything on manual and when we want to update we do:

Update web server.
Run schema update
Update all pollers with new code

We run daily.sh on one of the pollers but with updates disabled.

**Comment by f0o** [comment]
Our setup is updated similar.
- Cronjobs on pollers are halted
- Schema is applied on webserver
- Code is pulled on all parties

DB-cleanup is being executed via daily on the webserver as well

**Comment by murrant** [comment]
Maybe we should implement a lock for schema updates?

**Comment by laf** [comment]
Closing as was more a discussion than something that needs fixing.
