### ISSUE TITLE
Graph timestamp issue

### ISSUE THREAD

**Issue by mail3dexter** [librenms/librenms#3087]
I have set UTC in my php.ini and graphs are showing it properly.

However, when I select a time range for graph, suppose last 6 hours, it shows the graphs for last 6 hours but the date/time above the graph is showing as per local computer's date/time and not in UTC.

This is an example where in the graphs are in UTC where the date/time shown in from/to above graphs are showing in IST as my computer's clock is in IST.
http://prntscr.com/a7nj6u

This creates problem/confusion while selecting timerange

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by Rosiak** [comment]
No response, closing.
