### ISSUE TITLE
[Bugfix proposal] INSERT INTO 'devices' error when adding a new device

### ISSUE THREAD

**Issue by gcoeugnet** [librenms/librenms#3090]
Hi,

I'm testing the last version of librenms (2016/02). When I try to add a new device with WebUI, nothing appears in the device list. Checking database logs, this request appears : 

```
2016-02-25T13:36:27.879035Z454640 Query begin
2016-02-25T13:36:27.879233Z454640 Query INSERT INTO `devices` (`hostname`,`sysName`,`community`,`port`,`transport`,`status`,`snmpver`,`poller_group`,`status_reason`,`port_association_mode`,`os`)  VALUES ('172.16.0.247','172.16.0.247','sarra','161','udp','1','v2c','0','','ifIndex','comware')
2016-02-25T13:36:27.879341Z454640 Query rollback
```

However, trying this request directly in the database failed with : 
```
mysql> INSERT INTO `devices` (`hostname`,`sysName`,`community`,`port`,`transport`,`status`,`snmpver`,`poller_group`,`status_reason`,`port_association_mode`,`os`)  VALUES ('172.16.0.247','172.16.0.247','sarra','161','udp','1','v2c','0','','ifIndex','comware');
ERROR 1366 (HY000): Incorrect integer value: 'ifIndex' for column 'port_association_mode' at row 1
```

I think that's a bug. Available for more information.
Regards,
Guillaume.

**Comment by gcoeugnet** [comment]
Column 'port_association_mode' is describe as this in the database : 
`| port_association_mode     | int(11)          | NO   |     | 1       |              |`

A table port_association_mode exists with ifIndex value : 
```
mysql> select * from port_association_mode;
+--------+---------+
| pom_id | name    |
+--------+---------+
|      1 | ifIndex |
|      2 | ifName  |
|      3 | ifDescr |
|      4 | ifAlias |
+--------+---------+
```

**Comment by gcoeugnet** [comment]
Keeping on working on this issue I find something else. To make it works, I modify the code of "includes/functions.php" like this : 
```
function createHost($host, $community = NULL, $snmpver, $port = 161, $transport = 'udp', $v3 = array(), $poller_group='0', $port_assoc_mode = 'ifIndex') {
    global $config;
    $host = trim(strtolower($host));

    $poller_group=getpollergroup($poller_group);

# HERE
        if ($port_assoc_mode == "ifIndex") { $port_assoc_mode = 1; }
# /HERE

    $device = array('hostname' => $host,
        'sysName' => $host,
        'community' => $community,
        'port' => $port,
        'transport' => $transport,
        'status' => '1',
        'snmpver' => $snmpver,
        'poller_group' => $poller_group,
        'status_reason' => '',
        'port_association_mode' => $port_assoc_mode,
    );
...
```
This leads to another error (by repporting generated SQL request into database) : 
```
mysql> INSERT INTO `devices` (`hostname`,`sysName`,`community`,`port`,`transport`,`status`,`snmpver`,`poller_group`,`status_reason`,`port_association_mode`,`os`)  VALUES ('172.16.0.247','172.16.0.247','sarra','161','udp','1','v2c','0','','1','comware');
ERROR 1364 (HY000): Field 'ip' doesn't have a default value
```
Indeed, regarding the devices table, the IP field is tagged as "NOT NULL" but this field isn't filled by the createHost function above. I modifed it again like this (only for testing !!) : 
```
function createHost($host, $community = NULL, $snmpver, $port = 161, $transport = 'udp', $v3 = array(), $poller_group='0', $port_assoc_mode = 'ifIndex') {
    global $config;
    $host = trim(strtolower($host));

    $poller_group=getpollergroup($poller_group);
# HERE
        if ($port_assoc_mode == "ifIndex") { $port_assoc_mode = 1; }
# /HERE
    $device = array('hostname' => $host,
        'sysName' => $host,
        'community' => $community,
        'port' => $port,
        'transport' => $transport,
        'status' => '1',
# HERE ALSO
        'ip' => '172.16.0.247',
# /HERE ALSO
        'snmpver' => $snmpver,
        'poller_group' => $poller_group,
        'status_reason' => '',
        'port_association_mode' => $port_assoc_mode,
    );
...
```
which now works : 
```
mysql> select * from devices;
|         2 | 172.16.0.247 | 172.16.0.247 | 172.16.0.247 | sarra     | NULL      | NULL     | NULL     | NULL     | NULL       | NULL       | v2c     |  161 | udp       |    NULL |    NULL | NULL       | NULL        | NULL     | NULL       | NULL    | NULL     | NULL     | NULL     | comware |      1 |               |      0 |        0 |   NULL |            0 | NULL        | NULL                |                  NULL |                      NULL | NULL            | NULL      |                NULL | NULL    |      | NULL   | NULL |            0 |                    0 | NULL  |                     1 |
```
So there're two issues here regarding my tests : 

1. the port_association_mode type is wrong or badly filled (string given instead of an integer). The foreign key should be take in charge.
2. the ip field isn't filled by the createHost function while it is required regarding the DB scheme

Still available for more information or if i made any misstakes in my analyze...

**Comment by gcoeugnet** [comment]
Looking any further inside the code (which I'm discovering cause I'm a new librenms user) I found a deviceArray() function which makes the conversion between port_association_mode given as string and port_association_mode converted as integer. But the device array containing device description doesn't seem to be used while creating host ( in addHost() function) : 

To solve both issues, I proposed you this patch for include/functions.php file : 
```
295c295
<                                 $device_id = createHost ($host, NULL, $snmpver, $port, $transport, $v3, $poller_group, $port_assoc_mode);
---
>                                 $device_id = createHost ($host, NULL, $snmpver, $port, $transport, $v3, $poller_group, $port_assoc_mode, $ip);
321c321
<                                 $device_id = createHost ($host, $community, $snmpver, $port, $transport,array(),$poller_group, $port_assoc_mode);
---
>                                 $device_id = createHost ($host, $community, $snmpver, $port, $transport,array(),$poller_group, $device['port_association_mode']);
571c571
< function createHost($host, $community = NULL, $snmpver, $port = 161, $transport = 'udp', $v3 = array(), $poller_group='0', $port_assoc_mode = 'ifIndex') {
---
> function createHost($host, $community = NULL, $snmpver, $port = 161, $transport = 'udp', $v3 = array(), $poller_group='0', $port_assoc_mode = 'ifIndex', $ip) {
576d575
<
582a582
>       'ip' => $ip,
```

which seems to do the job. I let you consider or reject this proposal :)

**Comment by murrant** [comment]
@gcoeugnet  any chance we could get that in a pull request.  It is hard to evaluate in a raw diff.
You can create a new change right from the github ui by clicking the edit (pencil) button on the file.

**Comment by gcoeugnet** [comment]
Sure, done. :)
I add another change, which can be make better maybe, about the default value of $port_assoc_mode for function createHost. Setted up with "ifIndex" may have surely failed because of the string given instead of an integer.

**Comment by murrant** [comment]
Well, I'm not sure why you didn't have port_assoc_mode set, maybe a cached version of an older webui.

Added a check before inserting the device, can you test?

**Comment by gcoeugnet** [comment]
I've tested, it's ok for me like this too.
Will you informed Neil L. about your proposal, he starts looking at my pull request ?
There is still the issue regarding the ip which is missing when device is added. Do you have access to pull requests ?

**Comment by murrant** [comment]
No problem, I'll close your PR and create a new one from my changes.

**Comment by gcoeugnet** [comment]
Ok, just don't forget to fix in #3100 the missing $ip too ;-)

**Comment by murrant** [comment]
@gcoeugnet I'm not sure that should be changed.  It should be filled in by the discovery I think.

**Comment by gcoeugnet** [comment]
The only thing I notice is that without $ip we get this error while device insertion : `ERROR 1364 (HY000): Field 'ip' doesn't have a default value` due to the "NOT NULL" attribute of the database.
