### ISSUE TITLE
Strange relation under Device/Ports/ARP Table 'Remote device'

### ISSUE THREAD

**Issue by eikik87** [librenms/librenms#3094]
For some reason this Remote Device lists up in the mac address table of completely unrelated router. Also happens for limited user that should not see information about that router. Cause that 'Remote device' isn't a router that he is allowed to see. 

![image](https://cloud.githubusercontent.com/assets/13901674/13349636/174cd418-dc73-11e5-8b44-ada70a2df20f.png)

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by eikik87** [comment]
I fixed this by setting "$config['enable_port_relationship'] = false;" in the config.php file. The other issue is if you have 'ARP' table, it will list up these 'Remote device' and 'Remote interface', but those devices have nothing related to each other. My fix to that is to disable Arp poll and clear the arp in SQL.
