### ISSUE TITLE
Web link to device by hostname instead device_id

### ISSUE THREAD

**Issue by aauvinet** [librenms/librenms#3095]
Hello,
I use Centreon/Nagvis  also,  I need to link Nagvis to LibreNms.
I would like create a link with the Hosname instead the device_id, which is not know of Nagvis.
But the Hostname  is...

For exemple :²
http://librenms.nantes.net/device/device=9/ 

By/and 

librenms.nantes.net/device/hostname=loop0-pn-bellevue.reseau.nantes.net/

Both would to be Ok.

Cdlt,

**Comment by laf** [comment]
This already works, just use device=HOSTNAME instead of hostname=HOSTNAME.
