### ISSUE TITLE
Poller using 32-bit mibs for F5 machines, incorrectly graphing speed over 100 mbps

### ISSUE THREAD

**Issue by metroshica** [librenms/librenms#3101]
Looks like LibreNMS is using 32-bit mibs for polling F5 machines. I've attached a screenshot of the graphs of one of our loadbalancers. As you can see, around 100 mbps it seems that the counter wraps around, causing LibreNMS to graph the bandwidth incorrectly. For reference, this is on a BIG-IP 2000 box, running 11.6 firmware.
![screen shot 2016-02-26 at 11 24 13 am](https://cloud.githubusercontent.com/assets/7684916/13361464/0294ad12-dc7c-11e5-94ac-56e1566bc9c5.png)

**Comment by awlx** [comment]
Same problem here. Only real-time polling works.

**Comment by awlx** [comment]
Ports poller debug output:
https://paste.fedoraproject.org/438708/22313314/

**Comment by laf** [comment]
We need the output of `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .`

**Comment by laf** [comment]
So this is apparently fixed in ver 12.x for F5. We advise users to update to that version.

https://devcentral.f5.com/questions/64-bit-counter-on-big-ip-3900-47496

**Comment by awlx** [comment]
Simply upgrading an production env to a new major version is not really a task I want to do for a NMS to work tbh.

**Comment by laf** [comment]
Still waiting on the snmpbulkwalk output requested previously but the effort to implement a fix for this may be too great at this point in time.

**Comment by awlx** [comment]
I sent you the requested output via IRC :).

**Comment by laf** [comment]
What name?

**Comment by awlx** [comment]
Sail0r

**Comment by metroshica** [comment]
Just wanted to confirm that LibnreNMS is now graphing bandwidth correctly on F5s running 12.x. We've had this issue with incorrect graphs for months but since our upgrade a couple weeks ago we're looking good. I totally get not being unable to upgrade production loadbalancers, just wanted to add that the upgrade does fix the problem though.

**Comment by laf** [comment]
This is my attempt at a fix: https://github.com/laf/librenms/tree/issue-3101

Feel free to test.

**Comment by awlx** [comment]
Looks great so far!
http://i.imgur.com/CFyJThP.png

**Comment by laf** [comment]
lol, no way that worked!

**Comment by awlx** [comment]
Well it did ;).
