### ISSUE TITLE
Juniper MIB Update

### ISSUE THREAD

**Issue by direktorn** [librenms/librenms#3104]
Hi, 
We rely on Juniper equipment for most of our core networks, both switches and firewalls. 

Some issues we are having is that Libre does not support routing instances that limits us to enable OSPF support in LibreNMS. 

Another issue with the Juniper MIB packade is that it does not read VLAN description correctly. (Ethernet ports work however well) 

From a FW point of view (SRX) it would be helpful to gather some FW specific logs, ie. open sessions, IPSEC tunnels (To be able to create an alarm if a tunnel goes down for example)

**Comment by laf** [comment]
Are you able to provide us snmp access to any of these devices?

**Comment by Rosiak** [comment]
Any news?

**Comment by direktorn** [comment]
I wish I was able to do that but atm that is not possible. However Juniper has the same code in their virtual product that can be downloaded for free (eval) for vSRX and vMX

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by Rosiak** [comment]
I don't have time to fiddle with an appliance for now.
If you can provide access to one that would be preferred.

Closing for now, feel free to reopen if you can provide access to one.
