### ISSUE TITLE
Alerts for all devices when checking on %devices.hostname

### ISSUE THREAD

**Issue by Ultra2D** [librenms/librenms#3105]
Today I updated the code from https://github.com/librenms/librenms/commit/d9dcebb878706ce3ce01c23e018f11a9963707ea to https://github.com/librenms/librenms/commit/5149a9439713dae578a9916cfdcb2820841189bf and now the following rule matches all devices:
> %devices.hostname = "switch01.example.com" && %devices.status = "1" 

The alert emails are sent, so this does fix #3027.

**Comment by laf** [comment]
Can you do an update again now please.

**Comment by Ultra2D** [comment]
Fixed, thanks. 

Only now the status on the rules page is ok (green check mark), even though there is an active alert. Should I create a new issue for that?

**Comment by laf** [comment]
Give it a bit of time, see if it clears first.

**Comment by Ultra2D** [comment]
Nope, same behaviour for multiple rules. I am pretty sure this stopped working after upgrading today.

**Comment by Ultra2D** [comment]
All rules are in a success state (as they should be).

When creating a new rule `%devices.status = "1" && %devices.hostname = "switch.example.com"` with max=-1, delay=60 and interval=300, emails are sent every five minutes (five emails as of now), but the check mark is still green.

In the source: `<span id='alert-rule-102' class='glyphicon glyphicon-ok glyphicon-large text-success'></span>`

**Comment by laf** [comment]
I can't replicate this. Mine show as Red X.

Please can you provide the following:

```bash
git status
./validate.php
```

- The full alert rule including options.
- If you have a template associated.
- Your general alert and mail alerting config.

**Comment by Ultra2D** [comment]
This might be me doing something unexpected.

If you look at https://github.com/librenms/librenms/blob/b2d2346962dee13cd57f097a9e8ea13dde6fb287/html/includes/print-alert-rules.php#L158 , it only checks 1 entry, the one with the highest id.

The database is logging the state of all devices though, even though only one is critical (as per %devices.hostname):
> 49734 	20 	102 	0 	0 	0 	2016-03-02 09:07:01
49741 	14 	102 	0 	0 	0 	2016-03-02 09:07:01
49740 	15 	102 	0 	0 	0 	2016-03-02 09:07:01
49739 	6 	102 	0 	0 	0 	2016-03-02 09:07:01
49738 	4 	102 	0 	0 	0 	2016-03-02 09:07:01
49737 	22 	102 	0 	0 	0 	2016-03-02 09:07:01
49736 	21 	102 	0 	0 	0 	2016-03-02 09:07:01
49735 	19 	102 	0 	0 	0 	2016-03-02 09:07:01
49754 	1 	102 	0 	0 	0 	2016-03-02 09:07:01
49733 	2 	102 	0 	0 	0 	2016-03-02 09:07:01
49732 	11 	102 	0 	0 	0 	2016-03-02 09:07:01
49742 	7 	102 	0 	0 	0 	2016-03-02 09:07:01
49743 	17 	102 	0 	0 	0 	2016-03-02 09:07:01
49753 	18 	102 	0 	0 	0 	2016-03-02 09:07:01
49752 	13 	102 	0 	0 	0 	2016-03-02 09:07:01
49751 	23 	102 	1 	1 	1 	2016-03-02 09:07:01
49750 	12 	102 	0 	0 	0 	2016-03-02 09:07:01
49749 	3 	102 	0 	0 	0 	2016-03-02 09:07:01
49748 	8 	102 	0 	0 	0 	2016-03-02 09:07:01
49747 	5 	102 	0 	0 	0 	2016-03-02 09:07:01
49746 	16 	102 	0 	0 	0 	2016-03-02 09:07:01
49745 	10 	102 	0 	0 	0 	2016-03-02 09:07:01
49744 	9 	102 	0 	0 	0 	2016-03-02 09:07:01
