### ISSUE TITLE
Availability Map Timing

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#3108]
Hi,

I'm sure this is captured somewhere, but I have been hunting around and can't find it ... :-(.

Where / how do you adjust timing for the availability map (i.e. how long after a machine comes back up that the color changes from red to yellow, or yellow to green)?

Thanks!

**Comment by Rosiak** [comment]
This is what you are looking for:
$config['uptime_warning']

**Comment by arrmo** [comment]
Yep, that's it - thanks! Grep'd and found it, it's in includes/defaults.inc.php.

Unfortunately this is a file tracked in git, so changing it locally can cause update issues. If I add this to config.php, will that take precedence?

Thanks again.

**Comment by Rosiak** [comment]
@arrmo 
You should add it in config.php not in defaults, and yes this will take precedence :)

**Comment by arrmo** [comment]
Will do - thanks!
