### ISSUE TITLE
Laser RX/TX for Juniper not detected

### ISSUE THREAD

**Issue by trufflebear** [librenms/librenms#3112]
Hello,

we are using Juniper EX4500 which should display all SFP+ Laser Stats(RX/TX Level). Debug from discovery.php:

LibreNMS 2015.master Discovery
Version info:
Commit SHA: 5e9bbea801aff9fd8daf807cceb4a2393ff1701e
DB Schema: 6
PHP: 5.6.17-0+deb8u1
MySQL: 10.0.23-MariaDB-0+deb8u1
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2.1

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
SQL[SELECT revision FROM `dbSchema`] DB Schema already up to date.

Sensors:  ENTITY-SENSOR: Caching OIDs: entPhysicalDescr/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs  -m CISCO-ENTITY-SENSOR-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 entPhysicalDescrentPhysicalDescr = No Such Object available on this agent at this OID

 entPhysicalName/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs  -m CISCO-ENTITY-SENSOR-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 entPhysicalNameentPhysicalName = No Such Object available on this agent at this OID

 entPhySensorType/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs  -m ENTITY-SENSOR-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 entPhySensorTypeentPhySensorType = No Such Object available on this agent at this OID

 entPhySensorScale/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs  -m ENTITY-SENSOR-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 entPhySensorScaleentPhySensorScale = No Such Object available on this agent at this OID

 entPhySensorPrecision/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs  -m ENTITY-SENSOR-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 entPhySensorPrecisionentPhySensorPrecision = No Such Object available on this agent at this OID

 entPhySensorValue/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs  -m ENTITY-SENSOR-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 entPhySensorValueentPhySensorValue = No Such Object available on this agent at this OID

SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '1' AND `attrib_type` = 'ipmi_hostname' ] Temperatures: Including: /opt/librenms/includes/discovery/sensors/temperatures/akcp.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/aos-device.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/apc.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/areca.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/avaya-ers.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/avtech.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/cisco-envmon.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/ciscowlc.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/cometsystem-p85xx.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/dell.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/dnos-ftos-s-series.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/drac.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/dsm.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/equallogic.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/extreme.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/fiberhome.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/ftos-c-series.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/ftos-e-series.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/hpilo.inc.php
HP_ILO /usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Osqn  -M /opt/librenms/mibs udp:HOSTNAME:161 1.3.6.1.4.1.232.6.2.6.8.1.2.1.*.*.*.2.1 No Such Object available on this agent at this OID

Including: /opt/librenms/includes/discovery/sensors/temperatures/ibmnos.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/ipoman.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/ironware.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/junos.inc.php
JunOS /usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Osqn  -m JUNIPER-MIB -M /opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.*.4.1.2*.*.0.0 0
.*.4.1.2*.*.0.0 35
.*.4.1.2*.*.0.0 30
.*.4.1.2*.*.0.0 40
.*.4.1.2*.*.0.0 0
.*.4.1.2*.*.1.0 0
.*.4.1.2*.*.2.0 0
.*.4.1.2*.*.3.0 0
.*.4.1.2*.*.0.0 33
.*.4.1.2*.*.0.0 35
.*.4.1.2*.*.1.0 0
.*.4.1.2*.*.2.0 0
.*.4.1.2*.*.3.0 0
.*.4.1.2*.*.4.0 0
.*.4.1.2*.*.1.0 0
.*.4.1.2*.*.2.0 0
.*.4.1.2*.*.3.0 0
.*.4.1.2*.*.4.0 0
.*.4.1.2*.*.0.0 36
.*.4.1.2*.*.0.0 38
.*.4.1.2*.*.1.0 0
.*.4.1.2*.*.0.0 32
.*.4.1.2*.*.0.0 36

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.1.1.0.0midplane

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.1.1.0.00

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.2.1.0.0PEM 0

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.2.1.0.035

Discover sensor: 1.3.6.1.4.1.2636.3.1.13.1.7.2.1.0.0, 2.1.0.0, junos, PEM 0, snmp, , 

SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'snmp' AND `sensor_class` = 'temperature' AND `device_id` = '1' AND sensor_type = 'junos' AND `sensor_index` = '2.1.0.0'] 
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = 'temperature' AND `device_id` = '1' AND `sensor_type` = 'junos' AND `sensor_index` = '2.1.0.0'] ./usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.2.2.0.0PEM 1

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.2.2.0.030

Discover sensor: 1.3.6.1.4.1.2636.3.1.13.1.7.2.2.0.0, 2.2.0.0, junos, PEM 1, snmp, , 

SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'snmp' AND `sensor_class` = 'temperature' AND `device_id` = '1' AND sensor_type = 'junos' AND `sensor_index` = '2.2.0.0'] 
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = 'temperature' AND `device_id` = '1' AND `sensor_type` = 'junos' AND `sensor_index` = '2.2.0.0'] ./usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.2.4.0.0PEM 3

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.2.4.0.040

Discover sensor: 1.3.6.1.4.1.2636.3.1.13.1.7.2.4.0.0, 2.4.0.0, junos, PEM 3, snmp, , 

SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'snmp' AND `sensor_class` = 'temperature' AND `device_id` = '1' AND sensor_type = 'junos' AND `sensor_index` = '2.4.0.0'] 
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = 'temperature' AND `device_id` = '1' AND `sensor_type` = 'junos' AND `sensor_index` = '2.4.0.0'] ./usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.4.1.0.0Left Fan Tray

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.4.1.0.00

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.4.1.1.0Front Fan

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.4.1.1.00

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.4.1.2.0Middle Fan

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.4.1.2.00

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.4.1.3.0Rear Fan

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.4.1.3.00

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.7.2.0.0FPC: DPC 4x 10GE R @ 1/*/*

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.7.2.0.033

Discover sensor: 1.3.6.1.4.1.2636.3.1.13.1.7.7.2.0.0, 7.2.0.0, junos, FPC: DPC 4x 10GE R @ 1/*/*, snmp, , 

SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'snmp' AND `sensor_class` = 'temperature' AND `device_id` = '1' AND sensor_type = 'junos' AND `sensor_index` = '7.2.0.0'] 
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = 'temperature' AND `device_id` = '1' AND `sensor_type` = 'junos' AND `sensor_index` = '7.2.0.0'] ./usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.7.3.0.0FPC: DPC 4x 10GE R @ 2/*/*

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.7.3.0.035

Discover sensor: 1.3.6.1.4.1.2636.3.1.13.1.7.7.3.0.0, 7.3.0.0, junos, FPC: DPC 4x 10GE R @ 2/*/*, snmp, , 

SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'snmp' AND `sensor_class` = 'temperature' AND `device_id` = '1' AND sensor_type = 'junos' AND `sensor_index` = '7.3.0.0'] 
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = 'temperature' AND `device_id` = '1' AND `sensor_type` = 'junos' AND `sensor_index` = '7.3.0.0'] ./usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.8.2.1.0PIC: 1x 10GE(LAN/WAN) @ 1/0/*

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.8.2.1.00

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.8.2.2.0PIC: 1x 10GE(LAN/WAN) @ 1/1/*

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.8.2.2.00

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.8.2.3.0PIC: 1x 10GE(LAN/WAN) @ 1/2/*

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.8.2.3.00

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.8.2.4.0PIC: 1x 10GE(LAN/WAN) @ 1/3/*

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.8.2.4.00

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.8.3.1.0PIC: 1x 10GE(LAN/WAN) @ 2/0/*

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.8.3.1.00

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.8.3.2.0PIC: 1x 10GE(LAN/WAN) @ 2/1/*

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.8.3.2.00

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.8.3.3.0PIC: 1x 10GE(LAN/WAN) @ 2/2/*

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.8.3.3.00

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.8.3.4.0PIC: 1x 10GE(LAN/WAN) @ 2/3/*

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.8.3.4.00

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.9.1.0.0Routing Engine 0

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.9.1.0.036

Discover sensor: 1.3.6.1.4.1.2636.3.1.13.1.7.9.1.0.0, 9.1.0.0, junos, Routing Engine 0, snmp, , 

SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'snmp' AND `sensor_class` = 'temperature' AND `device_id` = '1' AND sensor_type = 'junos' AND `sensor_index` = '9.1.0.0'] 
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = 'temperature' AND `device_id` = '1' AND `sensor_type` = 'junos' AND `sensor_index` = '9.1.0.0'] ./usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.9.2.0.0Routing Engine 1

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.9.2.0.038

Discover sensor: 1.3.6.1.4.1.2636.3.1.13.1.7.9.2.0.0, 9.2.0.0, junos, Routing Engine 1, snmp, , 

SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'snmp' AND `sensor_class` = 'temperature' AND `device_id` = '1' AND sensor_type = 'junos' AND `sensor_index` = '9.2.0.0'] 
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = 'temperature' AND `device_id` = '1' AND `sensor_type` = 'junos' AND `sensor_index` = '9.2.0.0'] ./usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.10.1.1.0FPM Board

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.10.1.1.00

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.12.1.0.0CB 0

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.12.1.0.032

Discover sensor: 1.3.6.1.4.1.2636.3.1.13.1.7.12.1.0.0, 12.1.0.0, junos, CB 0, snmp, , 

SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'snmp' AND `sensor_class` = 'temperature' AND `device_id` = '1' AND sensor_type = 'junos' AND `sensor_index` = '12.1.0.0'] 
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = 'temperature' AND `device_id` = '1' AND `sensor_type` = 'junos' AND `sensor_index` = '12.1.0.0'] ./usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.5.12.2.0.0CB 1

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m JUNIPER-MIB -M +/opt/librenms/mibs/junos udp:HOSTNAME:161 1.3.6.1.4.1.2636.3.1.13.1.7.12.2.0.036

Discover sensor: 1.3.6.1.4.1.2636.3.1.13.1.7.12.2.0.0, 12.2.0.0, junos, CB 1, snmp, , 

SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'snmp' AND `sensor_class` = 'temperature' AND `device_id` = '1' AND sensor_type = 'junos' AND `sensor_index` = '12.2.0.0'] 
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = 'temperature' AND `device_id` = '1' AND `sensor_type` = 'junos' AND `sensor_index` = '12.2.0.0'] .Including: /opt/librenms/includes/discovery/sensors/temperatures/junose.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/lm-sensors.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/mgeups.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/mikrotik.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/netapp.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/netbotz.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/netonix.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/observernms-custom.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/papouch-tme.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/pcoweb.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/powerconnect.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/qnap.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/rfc1628.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/sentry3.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/siklu.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/sub10.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/supermicro.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/xups.inc.php
Including: /opt/librenms/includes/discovery/sensors/temperatures/zyxel-ies.inc.php
Array
(
    [junos] => Array
        (
            [2.1.0.0] => 1
            [2.2.0.0] => 1
            [2.4.0.0] => 1
            [7.2.0.0] => 1
            [7.3.0.0] => 1
            [9.1.0.0] => 1
            [9.2.0.0] => 1
            [12.1.0.0] => 1
            [12.2.0.0] => 1
        )

)

SQL[SELECT * FROM sensors AS S, devices AS D WHERE S.sensor_class='temperature' AND S.device_id = D.device_id AND D.device_id = '1' AND S.poller_type = 'snmp'] 2.1.0.0 -> junos
2.2.0.0 -> junos
2.4.0.0 -> junos
7.2.0.0 -> junos
7.3.0.0 -> junos
9.1.0.0 -> junos
9.2.0.0 -> junos
12.1.0.0 -> junos
12.2.0.0 -> junos

Humidity : Including: /opt/librenms/includes/discovery/sensors/humidity/akcp.inc.php
Including: /opt/librenms/includes/discovery/sensors/humidity/apc.inc.php
Including: /opt/librenms/includes/discovery/sensors/humidity/ipoman.inc.php
Including: /opt/librenms/includes/discovery/sensors/humidity/mgeups.inc.php
Including: /opt/librenms/includes/discovery/sensors/humidity/netbotz.inc.php
Including: /opt/librenms/includes/discovery/sensors/humidity/pcoweb.inc.php
Including: /opt/librenms/includes/discovery/sensors/humidity/sentry3.inc.php

SQL[SELECT * FROM sensors AS S, devices AS D WHERE S.sensor_class='humidity' AND S.device_id = D.device_id AND D.device_id = '1' AND S.poller_type = 'snmp'] 
Voltages: Including: /opt/librenms/includes/discovery/sensors/voltages/apc.inc.php
Including: /opt/librenms/includes/discovery/sensors/voltages/areca.inc.php
Including: /opt/librenms/includes/discovery/sensors/voltages/drac.inc.php
Including: /opt/librenms/includes/discovery/sensors/voltages/dsm.inc.php
Including: /opt/librenms/includes/discovery/sensors/voltages/eatonups.inc.php
Including: /opt/librenms/includes/discovery/sensors/voltages/gamatronicups.inc.php
Including: /opt/librenms/includes/discovery/sensors/voltages/ipoman.inc.php
Including: /opt/librenms/includes/discovery/sensors/voltages/linux.inc.php
Including: /opt/librenms/includes/discovery/sensors/voltages/mgeups.inc.php
Including: /opt/librenms/includes/discovery/sensors/voltages/mikrotik.inc.php
Including: /opt/librenms/includes/discovery/sensors/voltages/netonix.inc.php
Including: /opt/librenms/includes/discovery/sensors/voltages/netvision.inc.php
Including: /opt/librenms/includes/discovery/sensors/voltages/rfc1628.inc.php
Including: /opt/librenms/includes/discovery/sensors/voltages/sentry3.inc.php
Including: /opt/librenms/includes/discovery/sensors/voltages/siklu.inc.php
Including: /opt/librenms/includes/discovery/sensors/voltages/supermicro.inc.php
Including: /opt/librenms/includes/discovery/sensors/voltages/xups.inc.php

SQL[SELECT * FROM sensors AS S, devices AS D WHERE S.sensor_class='voltage' AND S.device_id = D.device_id AND D.device_id = '1' AND S.poller_type = 'snmp'] 
Frequencies: Including: /opt/librenms/includes/discovery/sensors/frequencies/apc.inc.php
Including: /opt/librenms/includes/discovery/sensors/frequencies/eatonups.inc.php
Including: /opt/librenms/includes/discovery/sensors/frequencies/ipoman.inc.php
Including: /opt/librenms/includes/discovery/sensors/frequencies/mgeups.inc.php
Including: /opt/librenms/includes/discovery/sensors/frequencies/netvision.inc.php
Including: /opt/librenms/includes/discovery/sensors/frequencies/raritan.inc.php
Including: /opt/librenms/includes/discovery/sensors/frequencies/rfc1628.inc.php
Including: /opt/librenms/includes/discovery/sensors/frequencies/xups.inc.php

SQL[SELECT * FROM sensors AS S, devices AS D WHERE S.sensor_class='frequency' AND S.device_id = D.device_id AND D.device_id = '1' AND S.poller_type = 'snmp'] 
Current: Including: /opt/librenms/includes/discovery/sensors/current/apc.inc.php
Including: /opt/librenms/includes/discovery/sensors/current/eatonpdu.inc.php
Including: /opt/librenms/includes/discovery/sensors/current/eatonups.inc.php
Including: /opt/librenms/includes/discovery/sensors/current/gamatronicups.inc.php
Including: /opt/librenms/includes/discovery/sensors/current/ipoman.inc.php
Including: /opt/librenms/includes/discovery/sensors/current/mgeups.inc.php
Including: /opt/librenms/includes/discovery/sensors/current/netvision.inc.php
Including: /opt/librenms/includes/discovery/sensors/current/raritan.inc.php
Including: /opt/librenms/includes/discovery/sensors/current/rfc1628.inc.php
Including: /opt/librenms/includes/discovery/sensors/current/sentry3.inc.php
Including: /opt/librenms/includes/discovery/sensors/current/xups.inc.php

SQL[SELECT * FROM sensors AS S, devices AS D WHERE S.sensor_class='current' AND S.device_id = D.device_id AND D.device_id = '1' AND S.poller_type = 'snmp'] 
Power: Including: /opt/librenms/includes/discovery/sensors/power/dsm.inc.php
Including: /opt/librenms/includes/discovery/sensors/power/extreme.inc.php
 EXTREME-BASE-MIB Including: /opt/librenms/includes/discovery/sensors/power/ipoman.inc.php
Including: /opt/librenms/includes/discovery/sensors/power/raritan.inc.php
Including: /opt/librenms/includes/discovery/sensors/power/rfc1628.inc.php

SQL[SELECT * FROM sensors AS S, devices AS D WHERE S.sensor_class='power' AND S.device_id = D.device_id AND D.device_id = '1' AND S.poller_type = 'snmp'] 
Fanspeeds : Including: /opt/librenms/includes/discovery/sensors/fanspeeds/areca.inc.php
Including: /opt/librenms/includes/discovery/sensors/fanspeeds/dell.inc.php
Including: /opt/librenms/includes/discovery/sensors/fanspeeds/drac.inc.php
Including: /opt/librenms/includes/discovery/sensors/fanspeeds/equallogic.inc.php
Including: /opt/librenms/includes/discovery/sensors/fanspeeds/extreme.inc.php
Including: /opt/librenms/includes/discovery/sensors/fanspeeds/lmsensors.inc.php
Including: /opt/librenms/includes/discovery/sensors/fanspeeds/mikrotik.inc.php
Including: /opt/librenms/includes/discovery/sensors/fanspeeds/netonix.inc.php
Including: /opt/librenms/includes/discovery/sensors/fanspeeds/qnap.inc.php
Including: /opt/librenms/includes/discovery/sensors/fanspeeds/supermicro.inc.php

SQL[SELECT * FROM sensors AS S, devices AS D WHERE S.sensor_class='fanspeed' AND S.device_id = D.device_id AND D.device_id = '1' AND S.poller_type = 'snmp'] 
Battery Charge: Including: /opt/librenms/includes/discovery/sensors/charge/apc.inc.php
Including: /opt/librenms/includes/discovery/sensors/charge/dsm.inc.php
Including: /opt/librenms/includes/discovery/sensors/charge/rfc1628.inc.php

SQL[SELECT * FROM sensors AS S, devices AS D WHERE S.sensor_class='charge' AND S.device_id = D.device_id AND D.device_id = '1' AND S.poller_type = 'snmp'] 
Load: Including: /opt/librenms/includes/discovery/sensors/load/apc.inc.php
Including: /opt/librenms/includes/discovery/sensors/load/dsm.inc.php
Including: /opt/librenms/includes/discovery/sensors/load/rfc1628.inc.php

SQL[SELECT * FROM sensors AS S, devices AS D WHERE S.sensor_class='load' AND S.device_id = D.device_id AND D.device_id = '1' AND S.poller_type = 'snmp'] 
States: Including: /opt/librenms/includes/discovery/sensors/states/cisco.inc.php
Including: /opt/librenms/includes/discovery/sensors/states/dell.inc.php
Including: /opt/librenms/includes/discovery/sensors/states/drac.inc.php
Including: /opt/librenms/includes/discovery/sensors/states/dsm.inc.php
Including: /opt/librenms/includes/discovery/sensors/states/equallogic.inc.php
Including: /opt/librenms/includes/discovery/sensors/states/pcoweb.inc.php
Including: /opt/librenms/includes/discovery/sensors/states/rfc1628.inc.php

In the repository there is a MIB which should match:
https://github.com/librenms/librenms/blob/master/mibs/junos/mib-jnx-dom.txt

Thanks for help beforehand!
kind regards

**Comment by Rosiak** [comment]
Tagging #1844

**Comment by Rosiak** [comment]
Closing this in, keep track in the other issue listed.
