### ISSUE TITLE
Billing Module Inefficiencies

### ISSUE THREAD

**Issue by richardlawley** [librenms/librenms#3115]
We've been having some big performance problems on our LibreNMS installation related to MySQL, and I've tracked this down to the Billing module.  The core of the problem is the `port_in_measurements` and `port_out_measurements` tables - these are queried twice each per port, simply to obtain the last counter value for each.  This is a very expensive query, as there's no index which helps this query, resulting in a filesort which takes a long time when there is a large amount of history.  This resulted in our poll_billing process taking a very long time (>30 mins), which means there are many copies of it trying to run the same expensive queries, which killed performance.

I started looking at improving the code for looking up the last counter, but I realised that as far as I can tell, these tables are *only* used for this purpose, and therefore anything other than the most recent row is pointless to store.  On our install, the bill_data table is 480MB while the port_in_measurements and port_out_measurements tables are both nearly 600MB each.  This causes separate problems with the auto-updater refusing to run because of the "InnoDB Buffersize too small" error.

Unless I am wrong, all of these problems could be fixed by doing the following:
* Create new table to hold latest counter values for each port
* Populate from old port_in_measurements and port_out_measurements
* Drop port_in_measurements and port_out_measurements

I'm happy to submit this as a PR, but before I do this I'd prefer to get input from the team on whether this looks like the right thing to do.  I cannot find any references to these tables other than in the billing polling code, and the reset button for the bill.  It could theoretically be used to look up the individual port usage on a bill, but this currently is not done, and if necessary could be done using the RRD files.

If there's a good reason for these tables to exist in their current form, I would suggest:
* Using a table for the last counter values (as above) in addition to the individual tables

OR
* Adding an index on (port_id, timestamp)
* Combining the tables (can't see a reason for these to be separate, and it reduces the number of queries)
* Improving the getLastPortCounters code to remove unnecessary queries and limit the resultset.

Again, I'm happy to submit this as a PR.

**Comment by richardlawley** [comment]
In addition to the problems with port_in_measurements and port_out_measurements, bill_data should really have an index as well, as the latest value from here is also used as part of the poller (though I think this could be removed).  My preference would be a primary key on (bill_id, timestamp).

Adding a primary key would improve performance for displaying billing information.  Unfortunately, the performance problems which caused multiple pollers to run simultaneously earlier, combined with the lack of primary key, have caused duplicate rows to be added in our installation, and I suspect we are not alone, so duplicate rows would need to be dealt with before adding a key.  The primary key would also prevent duplicate pollers running in future (or at least cause the second one to crash out with an error).

**Comment by richardlawley** [comment]
The other person who has had similar issues may well be my colleague, I decided to investigate further and see if I could fix as I get the alerts from the overloaded server!

I've got a PR waiting to go which solves the performance problems by:
* Adding indexes to bill_data, port_in_measurements and port_out_measurements (non-unique)
* Optimising the queries used in the polling

I'd not addressed the additional tables as was waiting to find out which direction you preferred to take.  I can submit this PR now and make additional changes if you like, I'm already running it as it made our installation usable again.

Here's my comments on your suggestions:

I don't see much point in combining 1 *and* 2, and I don't really see much point in leaving the old data in place.  The in/out deltas are stored in bill_data - the only thing the extra tables allows is the ability to view individual port billing usage.  I would expect that in the majority of cases if a customer queries usage, the accurate totals from bills together with the RRD files which show the breakdown should be sufficient.  I would imagine the majority of users only have a single port per bill anyway.  If you did want to keep the data anyway, then I would at least recommend combining it into a single table, for both space and query efficiency.

3 sounds useful, and would also be applicable to bill_data should we drop the individual tables, since the monthly data is summarised into bill_history anyway, so it may be desirable to drop data older than X.

Removing the duplicate data is a little tricky - it's not always possible to determine what the surviving row should be!  Here's an example from my DB:

```
> select * from bill_data where bill_id = 140 and timestamp = '2016-02-27 18:51:56';
+---------+---------------------+--------+-----------+----------+-----------+
| bill_id | timestamp           | period | delta     | in_delta | out_delta |
+---------+---------------------+--------+-----------+----------+-----------+
|     140 | 2016-02-27 18:51:56 |   6131 | 469361156 | 22900039 | 446461117 |
|     140 | 2016-02-27 18:51:56 |   6131 | 469361156 | 22900039 | 446461117 |
|     140 | 2016-02-27 18:51:56 |   6131 |    863286 |    91603 |    771683 |
+---------+---------------------+--------+-----------+----------+-----------+
```

The simplest option would be to keep the first row in each group.  Without a primary key this is tricky, but could be accomplished by adding an autonumber.

**Comment by laf** [comment]
You've obviously looked at it a lot more than I have so we're happy to take your position on things :)

You are correct 1 + 2 is pointless as port_X_measurements tables are redundant so only 1 is needed.

**Comment by richardlawley** [comment]
Ok, but we still need to decide between keeping the port measurements history (even if we change the structure to make it more efficient) or dropping it and just retaining the last counter values.

If we keep the data, I'll create bill_port_measurements which will replace port_in_measurements and port_out_measurements.  If we don't, I'll create bill_port_last_measurements which only holds the latest counter value.

**Comment by laf** [comment]
@richardlawley dropping is fine, you've made the valid point that it is totally useless data and from a quick check I agree :)

**Comment by richardlawley** [comment]
I've got this all done now.  I don't really have a fancy way of removing the duplicate rows from bill_data, so I've gone with a simplistic approach:

1.  Add temporary id autonumber pkey field
2.  Remove all rows from each port_id,timestamp group other than the one with min(id)

My rationale was simply by looking at some of my duplicate data:

```
> SELECT bill_data.* 
FROM bill_data
      INNER JOIN (SELECT bill_id, timestamp, MIN(id) as first_id 
FROM bill_data GROUP BY bill_id, timestamp HAVING COUNT(id) > 1 LIMIT 100) q
          ON bill_data.bill_id = q.bill_id AND bill_data.timestamp = q.timestamp;
+---------+---------+---------------------+--------+-------------+-------------+-------------+
| id      | bill_id | timestamp           | period | delta       | in_delta    | out_delta   |
+---------+---------+---------------------+--------+-------------+-------------+-------------+
| 1349017 |       1 | 2015-10-25 01:55:01 |    302 |     1056680 |      478213 |      578467 |
| 1349108 |       1 | 2015-10-25 01:55:01 |      1 |   639269459 |   566435735 |    72833724 |
| 1349019 |       3 | 2015-10-25 01:55:04 |    301 |  5590774102 |  3407117458 |  2183656644 |
| 1349110 |       3 | 2015-10-25 01:55:04 |      1 | 52523303300 | 28855487498 | 23667815802 |
| 5717573 |       3 | 2016-02-24 02:11:45 |    856 | 13158878125 |  8551520419 |  4607357706 |
| 5717597 |       3 | 2016-02-24 02:11:45 |    307 | 13158878125 |  8551520419 |  4607357706 |
| 5722125 |       3 | 2016-02-24 05:24:45 |    617 |  7937959682 |  5103820812 |  2834138870 |
| 5722130 |       3 | 2016-02-24 05:24:45 |    618 |  7937959682 |  5103820812 |  2834138870 |
| 1349020 |       4 | 2015-10-25 01:55:05 |    301 |  6484119949 |  4778770722 |  1705349227 |
| 1349111 |       4 | 2015-10-25 01:55:05 |      1 | 76340010356 | 58974347323 | 17365663033 |
| 5809236 |       4 | 2016-02-27 13:35:59 |    607 |  7071568813 |  2769891499 |  4301677314 |
| 5809256 |       4 | 2016-02-27 13:35:59 |    181 |  7071568813 |  2769891499 |  4301677314 |
| 1349021 |       5 | 2015-10-25 01:55:06 |    300 |  2758456661 |  1855488248 |   902968413 |
| 1349112 |       5 | 2015-10-25 01:55:06 |      1 | 38320977743 | 21992384041 | 16328593702 |
| 5735317 |       5 | 2016-02-24 14:52:54 |    216 |  3361699933 |  1939693247 |  1422006686 |
| 5735335 |       5 | 2016-02-24 14:52:54 |    218 |  3361699933 |  1939693247 |  1422006686 |
| 5786004 |       5 | 2016-02-26 04:47:48 |    490 |  9063250204 |  4398969855 |  4664280349 |
| 5786009 |       5 | 2016-02-26 04:47:48 |     93 |  9063250204 |  4398969855 |  4664280349 |
| 5722358 |       6 | 2016-02-24 05:34:18 |    364 |  3266390417 |  1277950011 |  1988440406 |
| 5722362 |       6 | 2016-02-24 05:34:18 |    154 |  3266390417 |  1277950011 |  1988440406 |
| 5725321 |       6 | 2016-02-24 07:30:47 |    799 |  4173011553 |  3446546397 |   726465156 |
| 5725322 |       6 | 2016-02-24 07:30:47 |    799 |  4173011553 |  3446546397 |   726465156 |
| 5730543 |       6 | 2016-02-24 11:27:50 |    586 |  5496486380 |  4214099844 |  1282386536 |
| 5730551 |       6 | 2016-02-24 11:27:50 |    587 |  5496486380 |  4214099844 |  1282386536 |
| 1349023 |       7 | 2015-10-25 01:55:07 |    299 |   129242409 |   116967800 |    12274609 |
| 1349114 |       7 | 2015-10-25 01:55:07 |      0 |  1525504406 |  1295648438 |   229855968 |
| 5689516 |       7 | 2016-02-23 01:46:13 |    622 |  2308770613 |  2189405985 |   119364628 |
| 5689518 |       7 | 2016-02-23 01:46:13 |    622 |  2308770613 |  2189405985 |   119364628 |
| 5720974 |       7 | 2016-02-24 04:33:49 |    385 |  1086725624 |  1081421793 |     5303831 |
| 5720979 |       7 | 2016-02-24 04:33:49 |    386 |  1112272029 |  1106968198 |     5303831 |
| 5725388 |       7 | 2016-02-24 07:36:46 |    768 |  1829666714 |  1786878489 |    42788225 |
| 5725449 |       7 | 2016-02-24 07:36:46 |    315 |  1829666714 |  1786878489 |    42788225 |
| 5735483 |       7 | 2016-02-24 14:55:46 |    248 |  2872454432 |  2858342066 |    14112366 |
```

In the rows I examined, the first one always looked like the right one to keep - the later ones sometimes had smaller periods but the same deltas.  There's a very real chance that some incorrect data will be left by this process.  However, what's there already is MORE incorrect and will be over-reporting bandwidth usage.  If you disagree or have comments, please speak up, as this isn't undoable!  Run the query on your own system to see if you have any duplicate data (this will be very slow unless you have schema update 106 applied!).

This now complete and in [my local branch](https://github.com/richardlawley/librenms/tree/billing-perf-2).  I'm going to do some more testing tomorrow before submitting a PR.  I also want to address #3133 - the schema update for this change on my low-power VM takes 15 mins to run.

**Comment by laf** [comment]
I've run:

```sql
SELECT bill_data.*  FROM bill_data       INNER JOIN (SELECT bill_id, timestamp, MIN(bill_id) as first_id  FROM bill_data GROUP BY bill_id, timestamp HAVING COUNT(bill_id) > 1 LIMIT 100) q           ON bill_data.bill_id = q.bill_id AND bill_data.timestamp = q.timestamp;
```

As the one provided used a non-existent column (id). I get zero results so i guess I'm the lucky one :)

I'm more than happy with your proposal and thank you so much for all of your work.

@librenms/reviewers anyone else with comments?
