### ISSUE TITLE
Blank values in certain places

### ISSUE THREAD

**Issue by mail3dexter** [librenms/librenms#3116]
Hello, 
I have noticed that there are unknown values/ blank gaps in librenms menus.

1. http://prntscr.com/a9e288 (After Voltage, it is blank)
2. http://prntscr.com/a9e2wu (This is alert notification menu)

**Comment by f0o** [comment]
2nd is the button to expand the alert, that's not-fixable I guess.

1st I've no idea

**Comment by mail3dexter** [comment]
Still seeing in menu http://prntscr.com/ajbn0w

**Comment by laf** [comment]
Feel free to submit a PR to resolve this.
