### ISSUE TITLE
Assign alert templates per transport

### ISSUE THREAD

**Issue by ekoyle** [librenms/librenms#3125]
I think it would be very useful to be able to assign a default alert template per-transport.  This would make it possible to handle the different formats expected by different transports (ie. a template for html emails with links and maybe even inline graphs, a template for transports that only handle text, and a separate template for each transport that have quirky syntax for links).

Any thoughts on the best way to go about this without interfering with the per-rule alert template mappings?

I am considering adding a column for transport (default null), and if null use for all transports, then the same for the rule and using the most specific (use something like 'order by rule, transport nulls last' and take the first result).  Currently, transport would need to be a string since we don't have anything else to map it to.

**Comment by ekoyle** [comment]
The template is rendered before it is passed to the transport, so it would still be done in alerts.php...  It would really just be a matter waiting until ExtTransports() to get the appropriate template.

An alternative could be to expose the transport to the template.  Then, we would just need to move the call to FormatAlertTpl() into the foreach in ExtTransports().  Then I can add appropriate logic in the template to do what I want.

**Comment by ekoyle** [comment]
@laf: something like https://github.com/ekoyle/librenms/commit/2a15f1189442eb28424e6c3516cd704b13c761c7 maybe (I haven't tested yet)?

**Comment by laf** [comment]
I'd honestly expect there is more to it than just that, if you want to contribute this then please feel free :)

Don't forget the WebUI to allocate templates to transports.

Transports need to maintain backwards compatibility with no template being allocated to it.

Also think about how you then deal with different templates per rule and transport.

**Comment by ekoyle** [comment]
Apparently the templating foo doesn't currently support quoted strings in if statements (the quotes get escaped and cause a syntax error).

**Comment by ekoyle** [comment]
I'm willing to call this resolved by #3148 .

**Comment by ekoyle** [comment]
Doh... still open...
