### ISSUE TITLE
VRF Lite support

### ISSUE THREAD

**Issue by laf** [librenms/librenms#3127]
Hi Folks,

Over the last week we've had to revert some of the code that made up the vrf lite pull request. This so far is:

bgp polling and discovery
arp discovery

At present we are classing vrf lite support as non-functional.

@HenocKA. Please be aware of these issues. We may be in a position where more of this code has to be reverted.

**Comment by HenocKA** [comment]
I'm sorry for this. I was a little busy these days. I submit a PR as soon as possible. Thanks

**Comment by HenocKA** [comment]
@laf I pushed code correct vrf lite support

**Comment by Tristan-Labbe** [comment]
Hi @laf,

I'm working with @Henocka on the vrf lite pull request. 
Do you know if the last release of @Henocka is functionnal ? 
If it's OK, when can you merge it to the project ?  

Thank you

**Comment by Rosiak** [comment]
Afaik this is supported now, should we close it @librenms/reviewers ?
