### ISSUE TITLE
User IDs not stored for LDAP authentication

### ISSUE THREAD

**Issue by pblasquez** [librenms/librenms#3128]
When using LDAP authentication, the SESSION variable stores a user_id value but this value is not stored in the user table.  I have confirmed that this breaks Shared Dashboard functionality, not sure what else at this point.

Is the right solution to update the Shared Dashboard code to not require user ids? Do we need a new user-state table based on current logins and user id joins should point there instead?

**Comment by Ultra2D** [comment]
How are the user ids used? Could you point me at the right spot in the Shared Dashboard code?
#3178 might possibly help by introducing get_user($user_id) for LDAP.

**Comment by laf** [comment]
With the rewrite I don't think there is any point in trying to refactor this code.
