### ISSUE TITLE
Alerts stop showing hostname/IP address when you put in $config['force_ip_to_sysname']    = true;

### ISSUE THREAD

**Issue by eikik87** [librenms/librenms#3131]
Just what the title says, simply turn on this and Alerts stop showing Hostname.

this is what I see with it on true
 http://postimg.org/image/4n6ovewvl/
 this is with it on false
http://postimg.org/image/xq5idin4b/

**Comment by f0o** [comment]
Can you provide a generated email for both cases?
Trying to make it down where the issue is.

**Comment by eikik87** [comment]
This is the email I got when I had force_ip_to_sysname = True
###
Alert for device 10.151.13.87 - Port utilisation over threshold
Severity: critical
Timestamp: 2016-03-03 14:14:35
Unique-ID: 121495
Rule: Port utilisation over threshold
Faults:
  #1: port_id => 45264; ifDescr => Dialer0; Alert sent to: NOC <x@x>
 ###

This is the email I got it with on false.

###

Alert for device 10.151.66.3 - Port utilisation over threshold
Severity: critical
Timestamp: 2016-03-03 13:00:23
Unique-ID: 121173
Rule: Port utilisation over threshold
Faults:
  #1: port_id => 13718; ifDescr => Dialer0; Alert sent to: NOC <eirikurk@vodafone.is> 

###

It did not have effect on the emails. It only reports the IP address of the device.

**Comment by eikik87** [comment]
I guess the alerts are trying to lookup the ip addresses in DNS? Instead of using the hostname of the router. I'm otherwise not sure.

**Comment by laf** [comment]
Maybe two sides to this.

the initial issue is it's the webui alerts widget displaying nothing rather than the forced sysName.

Alerting doesn't use this function to do the lookup for hostname.

**Comment by eikik87** [comment]
I think I found the fix, or at least it worked for me. 

I edited the /opt/librenms/html/includes/table/alerts.inc.php

I changed 

$sql = "SELECT `alerts`.*, `devices`.`hostname` AS `hostname`,`alert_rules`.`rule` AS `rule`, `alert_rules`.`name` AS `name`, `alert_rules`.`severity` AS `severity` $sql";

Too
$sql = "SELECT `alerts`.*, `devices`.`sysName` AS `hostname`,`alert_rules`.`rule` AS `rule`, `alert_rules`.`name` AS `name`, `alert_rules`.`severity` AS `severity` $sql";

And the Alerts is now displaying my devices sysName instead of empty spaces.

**Comment by laf** [comment]
Unfortunately that's only a fix for you or people who want sysName to be used. The real fix is elsewhere :(
