### ISSUE TITLE
PPP Interface showing high load -

### ISSUE THREAD

**Issue by eikik87** [librenms/librenms#3132]
It seems only be very wrong with 'output'
![image](https://cloud.githubusercontent.com/assets/13901674/13457321/7ca682c4-e05f-11e5-92ea-6cda733ddf2c.png)

This does not show in the overall graph view. That is fine. But ATM Interface, that is the REAL physical interface, does not show any traffic at all.
![image](https://cloud.githubusercontent.com/assets/13901674/13457335/9708f354-e05f-11e5-8cb1-6a02fd313bab.png)

This is what happens to top interfaces with many PPP interfaces.
![image](https://cloud.githubusercontent.com/assets/13901674/13457351/a83d5a3e-e05f-11e5-828b-a0cee2af8278.png)

If I look at real time
![image](https://cloud.githubusercontent.com/assets/13901674/13457411/0df57f0a-e060-11e5-9958-a98f10bbd8c2.png)

This is what it looks like on the router
![image](https://cloud.githubusercontent.com/assets/13901674/13457426/2a272d90-e060-11e5-9115-498f4dc66746.png)

**Comment by laf** [comment]
please provide the output of:

```bash
./poller.php -h HOSTNAME -d -r -f -m ports
```

**Comment by eikik87** [comment]
[git3132.txt](https://github.com/librenms/librenms/files/154604/git3132.txt)

**Comment by laf** [comment]
The device looks like it's spitting out bad data:

            [ifInOctets] => 4106056246
            [ifOutOctets] => 2539542108
            [ifHCInOctets] => 1395675463614
            [ifHCOutOctets] => 29305109860996700

Compare that to a device of mine that's doing about the same traffic level:

            [ifInOctets] => 2459934838
            [ifOutOctets] => 1927611390
            [ifHCInOctets] => 14201621815414
            [ifHCOutOctets] => 13664218579966

We use HC counters where possible and the values returned from your device seem abnormal. This is data returned directly from snmp so I'm not sure what we can do here.

**Comment by eikik87** [comment]
I think you are right, well spotted. Found same type of router but it is using different firmware. 

Seems that these types of routers + Firmware have this issue. I will try to upgrade one of them and see if this problem goes away.

C887VAM-K9 c800-universalk9-mz.SPA.154-3.M1.bin
C887VAM-K9 c800-universalk9-mz.SPA.155-1.T1.bin
C898EAG-LTE-GA-K9 c800-universalk9-mz.SPA.154-3.M1.bin

**Comment by laf** [comment]
Good old cisco :)

**Comment by eikik87** [comment]
Verified, problem went away from one router I did upgrade on. Thanks for the help.
