### ISSUE TITLE
Prevent Duplicate Schema Updates

### ISSUE THREAD

**Issue by richardlawley** [librenms/librenms#3133]
DB Schema updates are currently performed both from daily.sh and discovery.php.  If a schema update takes long enough (e.g. 106 from #3129) then it's possible for two copies of this to run.  In my case, I was running daily.sh manually when cron ran discovery.php, but if an update takes >5 minutes then discovery.php is going to stack up, running multiple copies.

In the case of 106, the end result is not too harmful - duplicate indexes are added.  Future updates may have a more problematic outcome.

The simplest fix to this is to prevent discovery.php from running DB updates (perhaps it could print a warning saying that a DB update is required).  A more advanced approach would be to detect another update in process and fail.

**Comment by f0o** [comment]
Sadly true. I mentioned removing the schema-update from discovery but I guess it went under in other conversation/discussion hehe.

Let's restart the discussion here.

I would like to remove it from disco and entirely let it up to daily.sh to update things

**Comment by richardlawley** [comment]
I would agree.  I'd prefer something which could prevent the running of concurrent updates, but not sure how to reliably do that as my initial though (lock tables) failed.

It would probably be worth adding a function to check if there's an outstanding update, and print this as a warning in discovery, in case people were previously using it to run updates.

**Comment by laf** [comment]
I'm not for / against having the schema update run from discovery however I do believe the reason it's there is to safe guard against people just doing a git pull. If someone updates the codebase that relies on a schema change that doesn't run then the potential for polling / discovery to fail is there.

Adding a warning in discovery isn't the best option either as not everyone has mail set up correctly to receive from cron so these warnings would disappear whilst polling/discovery failed.

I'm not aware that discovery running schema has caused us issues (yes it has the potential to and yes it certainly has the high possibility with the billing schema changes). Mysql supports locking doesn't it - f0o you tried it on distributed polling or similar if I recall, it may not have worked there but it could work here.

**Comment by richardlawley** [comment]
I tried locking earlier, as I thought that was the easy option, but you can't update tables you didn't lock, and you have to lock all the tables you need at once.  I tried by locking dbSchema, but then the update scripts fail (although when a schema update fails, the version number still increments!).  

In theory you could lock ALL tables, which would stop the web UI, pollers and other scripts from doing anything while the script runs (though you'd still potentially have old versions of the scripts running).

You could display a banner in the UI if the DB is out of date, together with instructions for running the update.

**Comment by laf** [comment]
As we are moving to Laravel for the front end, this performs database migrations where you right your schema updates in php so you can rollback. I'm not sure how it handles concurrent calls for schema updates but we can test that.

If it works well then their is probably no point in trying to fix the legacy system (or we utilise the Laravel feature into the core codebase).

For now to deal with queries that may take a while to run - it's a total hack - would be to only run one schema update that we know could run for a while to the sql file and add something like this before it:

```sql
UPDATE `dbSchema` SET `version`=xxx;
```

That way that schema change will be skipped for any subsequent runs. As you know from testing, if a schema update fails anyway the version number increments regardless so I'm not sure I see a downside to this.

**Comment by richardlawley** [comment]
The downside of that is that if there's a subsequent schema update that depends on the long-running one, it will break.  For example, 107 removes an index added in 106.  Daily.sh starts running 106, and prematurely marks it as done.  Discovery starts running update, skips 106, runs 107 which fails because the item it's going to operate on does not yet exist.

If you've got something longer-term sorted, then I would suggest just putting up warning messages in the UI for out of date DB, and removing the update from the discovery process.  The only way this can go wrong is for someone to manually run the daily.sh just before it gets run by cron.

**Comment by laf** [comment]
The initial schema update process would continue to add 107 though as it only checks the db at the start of the cycle so actually in this case the only time it would absolutely fail is if both 106 and 107 failed but if either would have failed anyway then the end result is the same, dbSchema version is 107 but 107 isn't applied.

Actually it can also go wrong by someone running git pull at 09:54 for instance and not running the schema update manually (php includes/schema/update.php). Discovery and polling could fail from then until someone fixed it or daily.sh runs 14 hours later. This is a more likely scenario we will find ourselves in than long running schema queries which for 105+ schema updates - I'm not aware of any reported issues.

So really the question should be, with the proposed change are we going to be in a worse or better position than now?

**Comment by richardlawley** [comment]
Removing it from discovery does appear to cause more issues, so I'm going to leave this for now and just make it so that my pending schema update can run concurrently using the hack of updating the version before running.

It does seem that the majority of the potential issues are related to people incorrectly manually updating - perhaps the update procedure should not be advertised as using git pull, but running a script which does that and the update.

If you're happy not doing anything more then this can be closed.

**Comment by ekoyle** [comment]
Would it be a reasonable hack to just use flock() on the schema update file?  Or is this a problem across pollers in a multi-poller installation as well?

**Comment by ekoyle** [comment]
We could also look at using mysql advisory locks (GET_LOCK()/RELEASE_LOCK()).

Something like:

```php
function schema_update() {
    $result=dbFetchRow("SELECT GET_LOCK('schema_update', 10) AS lock_status;");
    if ($result['lock_status'] !== '0') {
        return FAILURE;
    }
    $ret = do_schema_update();
    dbRun("SELECT RELEASE_LOCK('schema_update');");
    return $ret;
}
```

**Comment by richardlawley** [comment]
I wasn't aware of this feature of MySQL, but this looks like an ideal solution.  If a schema update is in progress, wait a short time, and exit if the update failed.

**Comment by laf** [comment]
Closing this down. We don't see this issue in the wild
