### ISSUE TITLE
Device: EX2500

### ISSUE THREAD

**Issue by barhom** [librenms/librenms#3140]
Attached snmpwalk of Juniper ex2500

[ex2500.snmpwalk.txt](https://github.com/librenms/librenms/files/156977/ex2500.snmpwalk.txt)

You can add the following to: includes/definitions.inc.php
```
//Juniper ex2500 switch
$os = 'juniperex2500';
$config['os'][$os]['text']             = 'Juniper EX2500';
$config['os'][$os]['type']             = 'network';
$config['os'][$os]['icon']             = 'junos';
$config['os'][$os]['over'][0]['graph'] = 'device_bits';
$config['os'][$os]['over'][0]['text']  = 'Device Traffic';
```

And the following file: includes/discovery/os/junex2500.inc.php
```
<?php

if (!$os) {
    if (strstr($sysObjectId, '.1.3.6.1.4.1.1411.102')) {
        $os = 'juniperex2500';
    }
}
```

This will make the EX2500 discoverable as a network device and ports will start to be mapped.

Please note that EX2500 seems to have issues with ifAlias as they are not a part of the snmpwalk.

**Comment by laf** [comment]
Support was merged in.
