### ISSUE TITLE
More control of Email alerts for Normal User.

### ISSUE THREAD

**Issue by eikik87** [librenms/librenms#3143]
Greetings,

My plan is to give customer the ability to view their routers in Libre. He will be 'Normal User'. Only being able to see x amount of routers. He only sees syslog for those devices and the alerts, that works fine. But the alerts to email option does not work for normal user. So I either have to have global read user or admin user.

But the thing is Admin user / Global read user does not want to get spammed with emails from 1000 devices about threshold alarms or lan ports flapping for example. So that option is pointless unless you have very limited things you want to monitor from alerts -> email. But that would be useful for the Normal User. Cause he is actually affected by those things and he will be able to pinpoint the problem without having to call us to tell what his problem is. 

So is there any ways for me to be able to control users. And even the user himself would be able to turn it on or off if he wants to get the alerts in his email. Even though he is just a 'Normal User'. 

Also I have few admins, and maybe some of those admins don't want the email, but some do. So the option of controlling per user, would be very cool.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
