### ISSUE TITLE
/routing/protocol=cef/ - Random picture with flashing colors.

### ISSUE THREAD

**Issue by eikik87** [librenms/librenms#3144]
I have no idea what that is. Maybe someone should look at that and resolve it. It sure does not make any sense to me.

**Comment by laf** [comment]
It's a hangup from the fork. With no real way to display the cef data I'm not sure it's worth an issue - consider it an easter egg.

**Comment by eikik87** [comment]
Why not disable cef polling information, if librenms can't display it yet? Seems to be bit pointless and confusing.

**Comment by laf** [comment]
data might be useful to someone. feel free to disable it on your install

**Comment by eikik87** [comment]
If that picture is useful for anyone then he needs to be checked. Otherwise the data might be good. But ye I have disabled it in my setup. Just figured it is maybe good idea to fix that flashing picture before some guy gets seizure.
