### ISSUE TITLE
Cisco WAP121 not detecting

### ISSUE THREAD

**Issue by laf** [librenms/librenms#3145]
https://twitter.com/FabMaurel/status/705424918167601152

**Comment by DjMomo** [comment]
`root@synology-librenms:/opt/librenms#` ./discovery.php -h ap-main.lan -d -m os
LibreNMS 2015.master Discovery
fatal: Not a git repository (or any of the parent directories): .git
Version info:
Commit SHA: 
DB Schema: 6
PHP: 7.0.3-5+deb.sury.org~trusty+1
MySQL: 5.5.44-MariaDB
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
SQL[SELECT revision FROM `dbSchema`] DB Schema already up to date.

SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE 'ap-main.lan' ORDER BY device_id DESC] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '7'] ap-main.lan 7 edgeswitch 
OS: /usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0Linux *-lvl7-dev, Cisco Small Business WAP121 (WAP121-E-K9), Version * Wed Oct 17 00:19:29 EDT 2012

/usr/bin/snmpget -v2c -c COMMUNITY -Ovqn -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysObjectID.0.*.4.1.4*

| Linux 2.6.21.5-lvl7-dev, Cisco Small Business WAP121 (WAP121-E-K9), Version 1.0.2.3 Wed Oct 17 00:19:29 EDT 2012 | .1.3.6.1.4.1.4413.1.1.28 | /usr/bin/snmpget -v2c -c COMMUNITY -Oqvn -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalDescr.1WAP121 Wireless-N Access Point with Single Point Setup

/usr/bin/snmpget -v2c -c COMMUNITY -Osqnv -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalMfgName.1Cisco Small Business


SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='wireless',`last_discovered_timetaken` ='0.448' WHERE `device_id` = '7'] Discovered in 0.448 seconds


SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','ap-main.lan','1457022926.6299','0.573','1')] ./discovery.php ap-main.lan 2016-03-03 16:35:27 - 1 devices discovered in 0.573 secs
MySQL: Cell[1/0s] Row[3/0s] Rows[1/0s] Column[0/0s] Update[1/0.03s] Insert[1/0s] Delete[0/0s]`

and 

`root@synology-librenms:/opt/librenms#` ./poller.php -h ap-main.lan -d -r -f -m os
LibreNMS 2015.master Poller
fatal: Not a git repository (or any of the parent directories): .git
Version info:
Commit SHA: 
DB Schema: 6
PHP: 7.0.3-5+deb.sury.org~trusty+1
MySQL: 5.5.44-MariaDB
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'ap-main.lan' ORDER BY `device_id` ASC] 
SQL[SELECT * FROM `devices` WHERE `device_id` = '7'] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '7'] ap-main.lan 7 edgeswitch 

SQL[INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('3','3','0','0.44','0.50','0.46','7',NOW())] /usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 sysObjectID.0SNMPv2-SMI::enterprises.4*

/usr/bin/snmpget -v2c -c COMMUNITY -OQnUst -m SNMPv2-MIB:HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 sysUpTime.0 sysLocation.0 sysContact.0 sysName.0 sysDescr.0 sysObjectID.0sysUpTime.0 = 180793100
sysLocation.0 = </system-location></system></dataset><rc>0</rc><counter>1</counter></lsql_result>

sysContact.0 = </system-contact></system></dataset><rc>0</rc><counter>1</counter></lsql_result>

sysName.0 = wapbc4150
sysDescr.0 = Linux *-lvl7-dev, Cisco Small Business WAP121 (WAP121-E-K9), Version * Wed Oct 17 00:19:29 EDT 2012
sysObjectID.0 = enterprises.4*

/usr/bin/snmpget -v2c -c COMMUNITY -OQnUst -m HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 snmpEngineTime.0 hrSystemUptime.0snmpEngineTime.0 = 2287
hrSystemUptime.0 = No Such Object available on this agent at this OID

Using SNMP Agent Uptime (1807931s)
[RRD Disabled]RRD[update /opt/librenms/rrd/ap-main.lan/uptime.rrd N:1807931] Uptime: 20 days, 22h 12m 11s

Hardware:  Version:  Features:  Serial: 
[RRD Disabled]RRD[update /opt/librenms/rrd/ap-main.lan/poller-perf.rrd N:0.735] [RRD Disabled]RRD[update /opt/librenms/rrd/ap-main.lan/ping-perf.rrd N:0.46] Polled in 0.735 seconds
Updating ap-main.lan
Array
(
    [uptime] => 1807931
    [last_ping] => Array
        (
            [0] => NOW()
        )

    [last_ping_timetaken] => 0.46
    [last_polled] => Array
        (
            [0] => NOW()
        )

    [last_polled_timetaken] => 0.735
)

SQL[UPDATE `devices` set `uptime` ='1807931',`last_ping` =NOW(),`last_ping_timetaken` ='0.46',`last_polled` =NOW(),`last_polled_timetaken` ='0.735' WHERE `device_id` = '7'] UPDATED!

SQL[SELECT * FROM device_groups ORDER BY name] 
SQL[SELECT alert_schedule.schedule_id FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '7' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1] 
SQL[SELECT * FROM device_groups ORDER BY name] 
SQL[SELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '7' ) || alert_map.target = '7'  )] 

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','ap-main.lan','1457023015.0392','0.819','1','synology-librenms\n')] ./poller.php ap-main.lan 2016-03-03 16:36:55 - 1 devices polled in 0.819 secs

MySQL: Cell[1/0s] Row[4/0.01s] Rows[4/0.01s] Column[0/0s] Update[1/0.02s] Insert[2/0.04s] Delete[0/0s]`



There is a bug on sysLocation and sysContact values too.

WAP121 MIB file is available on Cisco Website : https://software.cisco.com/download/release.html?mdfid=284152657&softwareid=283415686&release=1.0.6.2&relind=AVAILABLE&rellifecycle=&reltype=latest

LibreNMS runs in a Docker container on Synology NAS.

**Comment by DjMomo** [comment]
Bug on sysContact and sysLocation if fields are empty on WAP121.

<img width="605" alt="capture d ecran 2016-03-03 a 17 45 39" src="https://cloud.githubusercontent.com/assets/4518584/13501665/d6713354-e167-11e5-877e-1599bea9cf54.png">

**Comment by laf** [comment]
Thanks.

What is the OS these devices run?

**Comment by DjMomo** [comment]
I don't know, but I uppose it's under Linux (Linux 2.6.21.5-lvl7-dev).

But after a firmware upgrade of my AP (v1.0.2.3 to v1.0.6.2) these 2 problems of empty fields disapears.

**Comment by DjMomo** [comment]
One thing, MIB file is missing. It can be downloaded here : https://software.cisco.com/download/release.html?mdfid=284152657&softwareid=283415686&release=1.0.6.2

**Comment by laf** [comment]
Thanks. We might just have to label these as ciscowap.

The mib file, I download earlier. Most of those mibs we have, the CISCO-WLAN-ACCESS-POINT-REF-MIB.my one is just a device model mib.

**Comment by DjMomo** [comment]
On Cisco website, WAP121 and WAP321 products came from Small Business series. But there are really tagged "Cisco" and not "Linksys".

You have to use ciscosbWLANAP.my MIB file for theses AP, located in same tar archive than CISCO-WLAN-ACCESS-POINT-REF-MIB.my.

**Comment by laf** [comment]
Thanks, that file is to provide a lot more info than the basic detection.

What out of that file would you like as we can try and add that to our mib polling.

**Comment by murrant** [comment]
It looks like this is getting mis-discovered as a Ubiquiti Edgeswitch.

**Comment by laf** [comment]
Merged in.
