### ISSUE TITLE
UPDATE: Data Domain support

### ISSUE THREAD

**Issue by cmc0619** [librenms/librenms#3159]
I got this far. Polling is a bit of a mess...

#includes/definitions.inc.php
$os = 'datadomainemc';
$config['os'][$os]['type']             = 'storage';
$config['os'][$os]['group']            = 'storage';
$config['os'][$os]['text']             = 'EMC Data Domain';
$config['os'][$os]['icon']             = 'datadomain';
$config['os'][$os]['over'][0]['graph'] = 'device_bits';
$config['os'][$os]['over'][0]['text']  = 'Device Traffic';
$config['os'][$os]['over'][1]['graph'] = 'device_processor';
$config['os'][$os]['over'][1]['text']  = 'CPU Usage';
$config['os'][$os]['over'][2]['graph'] = 'device_mempool';
$config['os'][$os]['over'][2]['text']  = 'Memory Usage';
$config['os'][$os]['over'][3]['graph'] = 'device_storage';
$config['os'][$os]['over'][3]['text']  = 'Storage Usage';

#includes/discovery/os/datadomainemc.inc.php
<?php

if (!$os) {
    if (strstr($sysObjectId, '.1.3.6.1.4.1.19746')) {
        $os = 'datadomainemc';
    }
}

#includes/polling/os/datadomainemc.inc.php
<?php

$version = trim(snmp_get($device, "sysDescr.0", "-OQv", "SNMPv2-MIB"),'"');
$hardware = "EMC/" . trim(snmp_get($device, "sysObjectID.0", "-OQv", "DATA-DOMAIN-MIB"),'"');
$hostname = trim(snmp_get($device, "sysName.0", "-OQv", "SNMPv2-MIB"),'"');

My data domain boxes aren't being recognized.  Possible we can get an update?
[DATA_DOMAIN-5.7.0.10.mib.txt](https://github.com/librenms/librenms/files/157945/DATA_DOMAIN-5.7.0.10.mib.txt)

root@ubuntu-librenms:/opt/librenms/includes# snmpwalk -v2c -c ... <IP>
iso.3.6.1.2.1.1.1.0 = STRING: "Data Domain OS 5.7.0.4-513368"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.19746.3.1.28 <--- dd640. Not recognized :( Also, no dd620
iso.3.6.1.2.1.1.3.0 = Timeticks: (8632109) 23:58:41.09
iso.3.6.1.2.1.1.4.0 = STRING: "it@company.com"
iso.3.6.1.2.1.1.5.0 = STRING: "systemname.company.com"
iso.3.6.1.2.1.1.6.0 = STRING: "Street, City, State"
iso.3.6.1.2.1.1.7.0 = INTEGER: 72
iso.3.6.1.2.1.1.8.0 = Timeticks: (2) 0:00:00.02
iso.3.6.1.2.1.1.9.1.2.1 = OID: iso.3.6.1.6.3.10.3.1.1
iso.3.6.1.2.1.1.9.1.2.2 = OID: iso.3.6.1.6.3.11.3.1.1
iso.3.6.1.2.1.1.9.1.2.3 = OID: iso.3.6.1.6.3.15.2.1.1
iso.3.6.1.2.1.1.9.1.2.4 = OID: iso.3.6.1.6.3.1
iso.3.6.1.2.1.1.9.1.2.5 = OID: iso.3.6.1.2.1.49
iso.3.6.1.2.1.1.9.1.2.6 = OID: iso.3.6.1.2.1.4
iso.3.6.1.2.1.1.9.1.2.7 = OID: iso.3.6.1.2.1.50
iso.3.6.1.2.1.1.9.1.2.8 = OID: iso.3.6.1.6.3.16.2.2.1
iso.3.6.1.2.1.1.9.1.3.1 = STRING: "The SNMP Management Architecture MIB."
iso.3.6.1.2.1.1.9.1.3.2 = STRING: "The MIB for Message Processing and Dispatching."
...

**Comment by Rosiak** [comment]
Hi @cmc0619 
Are you gonna PR this?

**Comment by cmc0619** [comment]
Hi. I don't know what a PR is.  :( And I doubt it's ready for prime time.  I just kind of got started but I'm sure it's lacking the spit and polish a pro could do to it.  I'm not a developer.  Just a network engineer who knows a little SNMP and how to follow basic directions.  I was hoping someone could give it a once over and finish it and put it in?

Date: Fri, 11 Mar 2016 13:53:11 -0800
