### ISSUE TITLE
Alerting: Describe what has recovered

### ISSUE THREAD

**Issue by Mattz0r** [librenms/librenms#3165]
Example:

You have an alert for a switch, where the rule is this:

%macros.dynamic_out_speed > %ports.port_descr_speed && %ports.port_descr_speed > "0"

This is then linked to a switch, which has 48 ports, say for example 10 ports are currently in alert, and one of the ports recover, the recovery email just indicates that the switch has recovered, but doesn't describe what port/element has recovered.

If you need any further info, please let me know.

**Comment by Mattz0r** [comment]
$config['alert']['macros']['rule']['dynamic_out_speed'] = '(%ports.ifOutOctets_rate*8/1000000)';
$config['alert']['macros']['rule']['dynamic_in_speed'] = '(%ports.ifInOctets_rate*8/1000000)';

**Comment by Mattz0r** [comment]
@f0o - Any progress on this one at all?

**Comment by Mattz0r** [comment]
@f0o don't suppose you have an update at all? Something I'd quite like doing.

**Comment by f0o** [comment]
Did you had any chance to get me that data I asked for in IRC? Am currently in between jobs so time is almost nonexistent for setting up own testlabs :(

**Comment by Mattz0r** [comment]
@f0o Yeah, working on it today, hopefully!

**Comment by f0o** [comment]
\o/

**Comment by Mattz0r** [comment]
@f0o I'm having problems, where by when I update the speed of a port, it gets recognised everywhere apart from existing alerts, so I can't really figure out if it works properly lol >_<

**Comment by laf** [comment]
Recovery emails should now show you details.
