### ISSUE TITLE
AVTech RoomAlert 4E Support?

### ISSUE THREAD

**Issue by Dr-Juice** [librenms/librenms#3166]
Please let me know if this isn't the correct area for this.  But I have some AVTech RoomAlert 4E temp monitors that aren't drawing temperature graphs.  Are the devices supported?

![temp error](https://cloud.githubusercontent.com/assets/17650680/13534952/a0209f8a-e205-11e5-976e-ace0c2ef5a7d.jpg)

Any help you can give would be appreciated.  If you need any additional info, please let me know.

My system stats are:
![system stats](https://cloud.githubusercontent.com/assets/17650680/13535008/eb252b72-e205-11e5-9b9a-d0c50b2d48e2.JPG)

**Comment by murrant** [comment]
It's not supported yet, send me the output from this snmpwalk, I can look at adding it.
```
snmpwalk -v 1 -c COMMUNITY -m +/opt/librenms/mibs/avtech/ROOMALERT4E.MIB DEVICE enterprises
```

There is also a problem that it is impossible to discover the type of connected modules via SNMP.  For now we've just assume they are all temperature sensors.  We might have to come up with some way to specify that down the road.

**Comment by Dr-Juice** [comment]
Thanks for the reply!  

Here's the info you requested.  If you need anything else, please let me know.

[roomalert 4e snmpwalk.txt](https://github.com/librenms/librenms/files/159229/roomalert.4e.snmpwalk.txt)

**Comment by murrant** [comment]
@Dr-Juice Oopsie, something went wrong there.  Try the snmpwalk I posted up top (I edited it so you don't need any mibs).

**Comment by Dr-Juice** [comment]
Sure thing.  Here you go.

[roomalert 4e snmpwalk.txt](https://github.com/librenms/librenms/files/159281/roomalert.4e.snmpwalk.txt)

**Comment by murrant** [comment]
@Dr-Juice can you please test that and report back?  Thanks.

**Comment by Dr-Juice** [comment]
Thanks a lot for the superfast turnaround!  What would be the best way for me to test this commit for you?  I ran ./daily.sh, but I don't think that is the method to download the new changes.  Do I have to pull from git again?

**Comment by murrant** [comment]
@Dr-Juice You'll need to re-discover the devices.  You can do this in the gui under device settings.

This code is merged now, so running ./daily.sh should pull it in.  If you run `git log`, you should see the commits in the list to verify you have it.

**Comment by Dr-Juice** [comment]
Thanks.  When I run the daily.sh update script I get a "Fail" on updating to the latest codebase.  I've tried multiple things to fix, figuring it might be a permissions issue..  Everything has the correct ownership, according to the validate function.

Here's the daily.sh capture
![daily update](https://cloud.githubusercontent.com/assets/17650680/13583716/f49f4372-e480-11e5-82a5-c57c2e95f5ff.JPG)

And here's the results of the validate
![validate](https://cloud.githubusercontent.com/assets/17650680/13583717/fdb02260-e480-11e5-834f-790ed443e5ea.JPG)

I did have the daily updater disabled, but had enabled it this morning when trying to test the commit.   That's when I started to see the Fail message.

Do any services need to be disabled first?

**Comment by laf** [comment]
Check in /opt/librenms/logs/librenms.log, it should log what's going on there.

**Comment by Dr-Juice** [comment]
Thanks.  In the librenms.log, there's just polling info there, but I found this in the daily.log.  

_Fetching notifications
[ Mon, 07 Mar 2016 17:17:57 -0500 ] http://www.librenms.org/notifications.rss (3)
[ Mon, 07 Mar 2016 17:17:58 -0500 ] misc/notifications.rss (5)
[ Mon, 07 Mar 2016 17:17:58 -0500 ] Updating DB  Done
Returned: 0
Updating to latest codebase
error: Your local changes to the following files would be overwritten by merge:
	AUTHORS.md
	doc/Extensions/RRDTune.md
	doc/Extensions/Syslog.md
	doc/General/Acknowledgement.md
	doc/General/Changelog.md
	doc/Installation/Installation-(RHEL-CentOS).md
	html/css/styles.css
	html/includes/graphs/generic_multi_seperated.inc.php
	html/includes/modal/new_alert_rule.inc.php
	html/includes/print-map.inc.php
	html/includes/print-menubar.php
	includes/alerts.inc.php
	includes/definitions.inc.php
	includes/discovery/functions.inc.php
	includes/discovery/os/linux.inc.php
	includes/discovery/sensors/fanspeeds/lmsensors.inc.php
	includes/discovery/sensors/temperatures/avtech.inc.php
	includes/discovery/sensors/temperatures/lm-sensors.inc.php
	includes/discovery/sensors/voltages/linux.inc.php
	includes/syslog.php
	tests/SyslogTest.php
Please, commit your changes or stash them before you can merge.
Aborting
Returned: 1
Updating SQL-Schema

Returned: 0
Updating submodules

Returned: 0
Cleaning up DB

Returned: 0
Fetching notifications
[ Mon, 07 Mar 2016 20:07:30 -0500 ] http://www.librenms.org/notifications.rss (3)
[ Mon, 07 Mar 2016 20:07:31 -0500 ] misc/notifications.rss (5)
[ Mon, 07 Mar 2016 20:07:31 -0500 ] Updating DB  Done
Returned: 0
_

**Comment by murrant** [comment]
@Dr-Juice run `git status`  to see if  you have modified files preventing the update.  If you do you can fix them individually with `git checkout <filename>` or in a blanket way with `git reset --hard HEAD`.

**Comment by Dr-Juice** [comment]
Good news: the "blanket way" suggestion worked and LibreNMS successfully downloaded the update.   Also, upon rediscovering, the sensors and labels were returned, but no temperature data is being logged, it seems.

![sensor data](https://cloud.githubusercontent.com/assets/17650680/13604176/926ad15a-e50f-11e5-9bb0-d1fc8e010908.JPG)

**Comment by murrant** [comment]
@Dr-Juice Does it have data now?  This is how it looks immediately after the sensors are discovered untill you get a few points of data.

**Comment by Dr-Juice** [comment]
Hi Tony
No, there is no data that is being logged yet, from what I can find.

**Comment by murrant** [comment]
@Dr-Juice Please run ./validate.php

**Comment by Dr-Juice** [comment]
Ok.  Here's the log.

[screen.txt](https://github.com/librenms/librenms/files/163867/screen.txt)

I've since fixed the ownership of the librenms folder back to librenms:librenms per the user docs and ran another ./validate.php to verify the permissions were set properly.

The device has been set to rediscover.  I'll check back in a couple of hours to see if the data is being logged.

**Comment by murrant** [comment]
@Dr-Juice Ok, I made too many changes at the same time.  This should be all fixed up.  Please run ./daily.php and check again.

**Comment by murrant** [comment]
@Dr-Juice One more thing, the bug in the code would have made some incorrect DB entries.  To clean these up run this on your librenms database:
`DELETE  FROM `sensors` WHERE `sensor_class` LIKE 'environment'`

**Comment by laf** [comment]
That will delete all env sensors, add AND device_id=X

**Comment by murrant** [comment]
@laf  It will?  I didn't think sensor_class=environement was valid.  What happened was device_type got filled into sensor_class.  I think sensor_class should be one of (charge, current, fanspeeds, frequencies, humidity, load, power, states, temperatures, voltages)

**Comment by laf** [comment]
Ah ok, I just assumed it was valid and the query was wrong :)
