### ISSUE TITLE
Global Read privileges in WebUI, bits that need hiding

### ISSUE THREAD

**Issue by mkratz** [librenms/librenms#3175]
* Billing Page
  * Add Bill button and UI enabled (should probably be disabled/hidden)
  * Edit button showing against each billable interface (should probably be hidden)
* Edit/Delete dashboard showing on main page for shared dashboard (should probably be hidden, at least for shared dashboards).

**Comment by laf** [comment]
The buttons on the dashboard don't allow non-admin or non-owners to edit or delete things so not sure we really need to change anything else.
