### ISSUE TITLE
Drop support for PHP mysql extension in favor of mysqli

### ISSUE THREAD

**Issue by ekoyle** [librenms/librenms#3186]
The PHP mysql extension has been deprecated in favor of mysqli since PHP version 5.5.0, which was released 20 Jun 2013.  Perhaps we should drop support to reduce complexity?  Are there still people using php < 5.5?

**Comment by laf** [comment]
Yup, we support down to 5.3 at present.

**Comment by richardlawley** [comment]
It looks like [mysqli was introduced as a native driver in 5.3](http://php.net/manual/en/mysqli.installation.php), so everyone supported should be able to use it.

**Comment by laf** [comment]
I'm not sure the complexity is worth worrying about.
