### ISSUE TITLE
Address with a slash.

### ISSUE THREAD

**Issue by MilanVolf** [librenms/librenms#3190]
Hello, Please correct the following error:

When a device at a forward slash (Lukas 184/1, Prague 3, CZ)

and does not link the main toolbar: Device> Locations> Lukas 184/1, Prague 3, CZ

Error occurs:
Error 404

Thank you.

**Comment by ekoyle** [comment]
Is this just a matter of urlencoding the street address in a URL somewhere?

**Comment by MilanVolf** [comment]
URL street it generates:

/devices/location=Lukasova+184%2F1%2C+Praha+3%2C+CZ/

**Comment by geordish** [comment]
I can't replicate this. Using your example, it works as expected.

Are you on the latest version?

**Comment by laf** [comment]
Also can't replicate. Please ensure you are running an upto date install. If the problem still happens please reopen this.

**Comment by MilanVolf** [comment]
Yes, I am on the latest version. The problem remains.

**Comment by MilanVolf** [comment]
I attach another screenshot:
[step 1](http://milan.cege.cz/librenms/1.jpg)
[step 2](http://milan.cege.cz/librenms/2.jpg)

**Comment by MilanVolf** [comment]
Resolved.

I did not set the apache server: AllowEncodedSlashes On
