### ISSUE TITLE
Alerting/Feature Request: Embed images into email

### ISSUE THREAD

**Issue by Mattz0r** [librenms/librenms#3192]
Heyup,

Would it be possible to have images embedded into the emails, using base64 or something, so that images can be loaded irrespective of connection used (At the moment I have it restricted to local VPN range only). However, this isn't ideal.

I hope I've described this well enough..

Cheers

EDIT: Can't be in data:uri format, otherwise gmail webmail will reject the images.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-embed-images-into-email/874
