### ISSUE TITLE
Allow Librenms to identify Dell Networking N4032F as network device

### ISSUE THREAD

**Issue by jsdrakes** [librenms/librenms#3196]
Currently LibreNMS identifies my Dell Networking N4032F switch stack as a generic device.  Can it be updated to reflect that I am using a networking device?

Here is the output from the discovery os debug command as requested:

./discovery.php -m os -h bsdc3.sellingsource.com -d
LibreNMS 2015.master Discovery
Version info:
Commit SHA: 03d8345b472cb4408434a8dcb7834ff05ba83689
DB Schema: 106
PHP: 5.4.41-0+deb7u1
MySQL: 5.5.43-0+deb7u1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.4.3

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
SQL[SELECT revision FROM `dbSchema`] DB Schema already up to date.

SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE 'bsdc3.sellingsource.com' ORDER BY device_id DESC] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '22'] bsdc3.sellingsource.com 22 generic /usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0Dell Networking N4032F, *, Linux 3.7.10-449339c5

/usr/bin/snmpget -v2c -c COMMUNITY -Ovqn -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysObjectID.0.*.*95.3044

| Dell Networking N4032F, 6.2.7.2, Linux 3.7.10-449339c5 | .1.3.6.1.4.1.674.10895.3044 | /usr/bin/snmpget -v2c -c COMMUNITY -Osqnv -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalMfgName.1

/usr/bin/snmpget -v2c -c COMMUNITY -Oqvn -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalDescr.1

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 1.3.6.1.4.1.674.10895.3000.1.2.100.1.0"Dell Networking N4032F"

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.39165.1.6.0No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 SML-MIB::product-Name.0No Such Object available on this agent at this OID

OS: /usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0Dell Networking N4032F, *, Linux 3.7.10-449339c5

/usr/bin/snmpget -v2c -c COMMUNITY -Ovqn -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysObjectID.0.*.*95.3044

| Dell Networking N4032F, 6.2.7.2, Linux 3.7.10-449339c5 | .1.3.6.1.4.1.674.10895.3044 | /usr/bin/snmpget -v2c -c COMMUNITY -Osqnv -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalMfgName.1

/usr/bin/snmpget -v2c -c COMMUNITY -Oqvn -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalDescr.1

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 1.3.6.1.4.1.674.10895.3000.1.2.100.1.0"Dell Networking N4032F"

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.39165.1.6.0No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 SML-MIB::product-Name.0No Such Object available on this agent at this OID

SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='server',`last_discovered_timetaken` ='0.344' WHERE `device_id` = '22'] Discovered in 0.344 seconds

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','bsdc3.sellingsource.com','1457476595.2049','0.374','1')] ./discovery.php bsdc3.sellingsource.com 2016-03-08 14:36:35 - 1 devices discovered in 0.374 secs
MySQL: Cell[1/0s] Row[3/0s] Rows[1/0s] Column[0/0s] Update[1/0s] Insert[1/0s] Delete[0/0s]

**Comment by ekoyle** [comment]
Do you know what they call the OS on these switches?

**Comment by jsdrakes** [comment]
I believe they are calling this Dell Networking OS version 6
