### ISSUE TITLE
Alerting: Separate Speed for Upload and Download

### ISSUE THREAD

**Issue by Mattz0r** [librenms/librenms#3198]
Heyup,

Would like to request that the ability to differ between upload speed thresholds and download speed thresholds, for the alerting system mainly.

This means, that for example, on our ports we'd probably have a higher threshold for inbound than we do outbound, we'd want to know when the ports are doing more than expected.

Is this something that can be easily added?

Cheers,

Matt

**Comment by Mattz0r** [comment]
@f0o seems have created a dirty hack for this, till it can become a bit more tidier.

$config['alert']['macros']['rule']['inbound'] = '%ports.port_descr_speed != "" && %macros.dynamic_in_speed > SUBSTRING_INDEX(%ports.port_descr_speed,"/",-1)';
$config['alert']['macros']['rule']['outbound'] = '%ports.port_descr_speed != "" && %macros.dynamic_out_speed > SUBSTRING_INDEX(%ports.port_descr_speed,"/",1)';


This within config.php

This assumes that you set the port speed in the description to something like [50/20]

This means 50Mbps Outbound and 20Mbps Inbound.

You can then use, as per my example macros.outbound =1 and macros.inbound =1 as your Alert Rule.

Hopefully it can become a bit more tidier before put into the main code base, but a quick work-around none the less :)

**Comment by cnu80** [comment]
Hi, thanks for the "dirty hack". How can I check the utilization of the upload and download does not reach more than 80%? 

I don't understand how I can use the macro  "macros.outbound =1" to build an alert rule. thanks, Cheers cnu
