### ISSUE TITLE
Syslog shows "]" in the column program

### ISSUE THREAD

**Issue by evrisko** [librenms/librenms#3199]
This is a problem after the upgrade librenms. Syslog cisco ios.
![syslog-c7600](https://cloud.githubusercontent.com/assets/16538050/13635021/5449a4e0-e60a-11e5-9c1f-b22a626cb87a.png)
dump
Facility local7 (23), Severity info (6)
Msg: 3876: ]: Mar  9 12:03:54.374 UTC: %SEC-6-IPACCESSLOGS: list MNGMNT denied 120.62.186.12 2 packets
librenms.log 
172.16.0.1||local7||info||info||be||2016-03-09 03:58:25||Mar  9 11:58:24.145 UTC: %SEC-6-IPACCESSLOGS: list MNGMNT denied 120.62.186.12 1 packet ||]

**Comment by murrant** [comment]
@evrisko Can you post your syslog destination line?  It looks like you are missing the || separator between the date and the message.

**Comment by evrisko** [comment]
destination d_librenms {
        program("/opt/librenms/syslog.php" template ("$HOST||$FACILITY||$PRIORITY||$LEVEL||$TAG||$YEAR-$MONTH-$DAY $HOUR:$MIN:$SEC||$MSG||$PROGRAM\n") template-escape(yes));
};

**Comment by murrant** [comment]
@evrisko ir you look at the line you sent (this is what is received by the parser).  The program part is set to "]" before LibreNMS even receives it.  I'm not sure if the problem is in syslog-ng or the device config.   But the destination line you posted looks correct.   We might have to check what input your syslog daemon receives.

**Comment by evrisko** [comment]
@murrant this dump syslog msg with cisco 3750me
Msg: 142399: Mar  9 16:15:10.650 UTC: %PLATFORM_ENV-1-DUAL_PWR: Faulty internal power supply A detected
and there is no "]:" and program show correct.
Syslog configured identically on devices.

**Comment by murrant** [comment]
@evrisko I expect your message to look like this: `172.16..1||local7||info||info||be||2016-03-09 03:58:25||%SEC-6-IPACCESSLOGS: list MNGMNT denied 120.62.186.12 1 packet ||`

What device is this?

**Comment by evrisko** [comment]
@murrant cisco 7606

**Comment by murrant** [comment]
@evrisko You must have `logging timestamp` set on your devices.  I'll make a change to the parser to accommodate for that.

I still have no idea where the "]" is coming from, but we can ignore that.
