### ISSUE TITLE
10Gbps link shown as 10bps

### ISSUE THREAD

**Issue by rgormley** [librenms/librenms#3208]
Cisco 500X-24 - ports tab shows link speed of 10bps for both up and down interfaces (up shows as 10bps fullDuplex).

GigE ports show correctly: 1Gbps.

Not sure if this is a SNMP/MIB issue or other bug.

**Comment by Rosiak** [comment]
What does the device report when you try ask it via. SNMP?

**Comment by rgormley** [comment]
Hmm:

`
iso.3.6.1.2.1.2.2.1.5.62 = Gauge32: 100000000
iso.3.6.1.2.1.2.2.1.5.63 = Gauge32: 1000000000
...
iso.3.6.1.2.1.2.2.1.5.107 = Gauge32: 10
iso.3.6.1.2.1.2.2.1.5.108 = Gauge32: 10
iso.3.6.1.2.1.2.2.1.5.109 = Gauge32: 10
iso.3.6.1.2.1.2.2.1.5.110 = Gauge32: 10
`

So the 100mbps and 1gbps links are interpreted correctly. Garbage in, garbage out?

**Comment by murrant** [comment]
What version of SNMP are you use?

**Comment by rgormley** [comment]
v2c is what is being used, but I will try v3 and report back.

**Comment by rgormley** [comment]
Nice, thank you!
