### ISSUE TITLE
LDAP Authenticated bind

### ISSUE THREAD

**Issue by b4** [librenms/librenms#3209]
Our LDAP server does not support anonymous binds, so it's unfortunately more difficult to do LDAP here.

Need the ability to specify a user to bind as before querying the LDAP server.

**Comment by simonholmbring** [comment]
@b4 I had a similar problem, what I ended up doing is letting apache handle the AD/LDAP-authentications, via mod_authnz_ldap. It's not as pretty though...

**Comment by darkounet** [comment]
🆙

**Comment by bahamut45** [comment]
:up:

**Comment by BarbarossaTM** [comment]
I'm in the process of reworking and unifying the entire auth stuff, I'll have a look at specifying a bind dn/pass as well.

**Comment by xdaxdb** [comment]
I'm faced with the same problem. Could solving this be as easy as adding a line or two using ldap_bind() instead of just ldap_connect().

http://php.net/manual/en/function.ldap-bind.php

**Comment by laf** [comment]
Closing in favour of #5089
