### ISSUE TITLE
Feature Request: Devices group that I can assign user permission to view

### ISSUE THREAD

**Issue by eikik87** [librenms/librenms#3220]
Greetings,

Lets say I have a group of devices, that I could name Company1. That group would always hold all the devices and I could then just simply give a user permission to be able to view that specific group. Then I could also add individual devices for that user to see.

It would not be requirement for a device to be in a group, but instead I would be able to sort routers into specific groups.

This would give me much better user control and overview what devices specific user is able to view.

**Comment by BerndKammlott** [comment]
i whould also like to see this feature :+1:

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-devices-group-that-i-can-assign-user-permission-to-view/724
