### ISSUE TITLE
Cisco dBm - Don't add sensor if interface is shut

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#3232]
If the interface is shut, we don't care about the dBm on it, therefor we shouldn't monitor it.

**Comment by laf** [comment]
How you going to handle interfaces that get shutdown and re-enabled, if we cleanup the sensors in between will people lose data?

**Comment by Rosiak** [comment]
No clue yet :) 
Problem as of now is that when the if get's shut, values change and therefor triggers the high/low alarms.

**Comment by laf** [comment]
Anyway to map it to the interface so we can tie the rule into it?

**Comment by Rosiak** [comment]
#3068
