### ISSUE TITLE
How to test transport?

### ISSUE THREAD

**Issue by drukpa** [librenms/librenms#3234]
Is there any way to test the transport api.

**Comment by f0o** [comment]
Uhm, there's a button next to each transport labeled 'test transport'. Or do you mean something else?

**Comment by drukpa** [comment]
There is no button labeled 'test transport' . I am viewing this under
Global Settings > Alerting
Or is that button available at some other pages.

On Mon, Mar 14, 2016 at 12:49 PM, Daniel Preussker <notifications@github.com

**Comment by laf** [comment]
That's the correct page. If you don't see it then you most likely aren't upto date on your install. Please updated.

**Comment by drukpa** [comment]
Thank You. My current *Version is ed2e072*

**Comment by laf** [comment]
That's about 8 months old. Run ./daily.sh as the librenms in /opt/librenms

**Comment by drukpa** [comment]
Thank you. I did it and it works perfectly. (*I have set the autoupdate on
and seems like it didn't update*)

Is it possible to display graphs for user with specific device & interfaces
on the dashboard? I am able to add graph widgets but looks like it only
support device name. If its possible to assign the interface also?

**Comment by laf** [comment]
Please create a separate issue for this as it's not related to the original issue but yes you can add port graphs for the device + port name.
