### ISSUE TITLE
Oxidized configuration GUI - HTML syntax

### ISSUE THREAD

**Issue by Lucheni** [librenms/librenms#3235]
![capture](https://cloud.githubusercontent.com/assets/5095269/13744139/2ba57156-e9e6-11e5-87c0-705323503afe.JPG)

Have had this issue for some time but have not had time to dig deeper into it. When integrating Oxidized into my LibreNMS I get HTML syntax displayed, this happens both for "Show version" and "Show diff".

Has anyone else stumbled upon this and assist to help the issue or is this a newly found issue?

Best regards,
Lucheni

**Comment by laf** [comment]
What's your oxidized config set to, I expect you might be pointing it to the wrong url?

**Comment by Lucheni** [comment]
Thanks for the super quick response :+1: 

$config['oxidized']['url']             = 'http://127.0.0.1:8888';

Should it be something else?

**Comment by murrant** [comment]
For some reason the response is html instead of json.  This could be a bug in oxidized, what version are you running?

**Comment by murrant** [comment]
@Lucheni Also, can you try going to the oxidized webui and clicking on "versions" on this device.  Then click "configuration".

You should get your config (with html formatting).
Then go up and add this on the end of the url and hit enter: `&format=text`
It should be text.

Post that url here so I can check it.

**Comment by Lucheni** [comment]
Somehow I managed to completely destroy my oxidized setup whilst updating it to verify it was not related to the old version. But I was running a very old version, so you were probably right.
