### ISSUE TITLE
OS Icons getting stuck

### ISSUE THREAD

**Issue by murrant** [librenms/librenms#3236]
We merged PR 3076 awhile ago.

Currently, what happens is we update the icon during discovery only if the os was changed or if the database icon field was previously null.  (Setting the icon to null in the database, fixes the issue)

I suspect device os might be getting set somewhere else, but I don't know where that could be.

The other issue, is that the icon field was originally implemented as a way for users to override the icon.  But there was never any gui for it.  Is it important to try to preserve this functionality?

**Comment by laf** [comment]
I think if the icon field is null it will still only update if the device is up, I have a number of NULL entries for devices that are marked as down.

I don't think we need to worry about allowing people to set an icon in the WebUI, we should control that imho.

**Comment by murrant** [comment]
@laf: Any idea how the os is getting changed and the icon is not?

**Comment by laf** [comment]
Os will only get changed on a discovery where no matter what it was before, it _should_ be set to the one it discovers then.

**Comment by laf** [comment]
See if that PR works for you.

Basically split out the OS and Icon update check.
