### ISSUE TITLE
Cisco 3850/3650 as wireless controller

### ISSUE THREAD

**Issue by ipguru99** [librenms/librenms#3238]
The Cisco 3850/3650 are "converged" L3 switches. They have wireless controllers and wired L3 ports. The current discovery doesn't recognize this, so there is no way to discover the AP's or wireless client information. It looks like the AIRESPACE MIBS could handle this.. and the code here: includes/polling/os/ciscowlc.inc.php seems like it would work. I can help with any testing needed.

Thanks!

**Comment by Rosiak** [comment]
@ipguru99: Are you still available for testing?

**Comment by ipguru99** [comment]
Sure! I have several customers running 3850's with LibreNMS monitoring
them.. how can I help?

**Comment by murrant** [comment]
Can someone provide a `snmpwalk -Oneb .` to me for one of these devices acting as a WLC?  Either posted here or privately to me.  (contact me on irc)

**Comment by ipguru99** [comment]
Hi Tony,

Running right now.. I will attach here as soon as it is done.. and thanks!

On Apr 27, 2017 10:02 PM, "Tony Murray" <notifications@github.com> wrote:

Can someone provide a snmpwalk -Oneb . to me for one of these devices
acting as a WLC? Either posted here or privately to me. (contact me on irc)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/librenms/librenms/issues/3238#issuecomment-297894776>,
or mute the thread

**Comment by laf** [comment]
@ipguru99 Can you please update your install and see if you have the relevant data you need please.

**Comment by ipguru99** [comment]
Hi Neil,

Maybe I need to re-discover my 3850's? My install is current as of the 4th
and I don't see anything different.

On May 5, 2017 4:21 PM, "Neil Lathwood" <notifications@github.com> wrote:

@ipguru99 <https://github.com/ipguru99> Can you please update your install
and see if you have the relevant data you need please.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/librenms/librenms/issues/3238#issuecomment-299578915>,
or mute the thread

**Comment by laf** [comment]
No we merged 4 days ago and discovery would have run by now. Was hoping this may have got caught up in the update.

We'll need the walk asked for earlier then still.

**Comment by ipguru99** [comment]
Will do.. I posted it earlier in an email. Is there a better place for me
to put it? It's about 7Mb not compressed, if I remember correctly..

**Comment by laf** [comment]
You can post it here. GitHub allows uploading of files.

**Comment by ipguru99** [comment]
..and of course, I didn't even think about that..
Here it is!
[snmpwalk_for_3850_as_WLC.txt](https://github.com/librenms/librenms/files/999094/snmpwalk_for_3850_as_WLC.txt)
