### ISSUE TITLE
custom snmp oid

### ISSUE THREAD

**Issue by guilhermefigueiredo** [librenms/librenms#3247]
Hi Librenms!
 
 Congrats to fork!
 It's better than observium!

 but I wonder if you would like to add an option for us to add our own oids snmp

 such as custom oids on observium

Best Regards!

**Comment by paulgear** [comment]
Please see http://docs.librenms.org/Extensions/MIB-based-polling/ for information about how to do this.  It's still officially alpha, but many people are using it successfully.

**Comment by moengoet** [comment]
Hi, is there anyway I can do the custom oid like it is in this ref http://www.maartenmoerman.nl/?p=649

I saw my MIKROTIK-MIB file doesn't contain any custom OID value that I need to display. Can someone advise me how to add., for example, a custom oid of my queue tree:
name=.1.3.6.1.4.1.14988.1.1.2.2.1.2.16779234 
bytes=.1.3.6.1.4.1.14988.1.1.2.2.1.7.16779234

Thanks
