### ISSUE TITLE
Feature Request: Disable unpolled warning

### ISSUE THREAD

**Issue by Hypfer** [librenms/librenms#3249]
Since I want to monitor workstations which aren't online 24/7 it would be nice to disable the "not polled for more than 15 Minutes" message. Maybe even on a per device level.

**Comment by spinza** [comment]
If the device is down it should not warn. It is only supposed to warn for devices that are up but not being polled.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by Rosiak** [comment]
No response, closing.
