### ISSUE TITLE
Add Redback LNS MIB

### ISSUE THREAD

**Issue by barto95100** [librenms/librenms#3251]
I have a device REDBACK ERICSSON SE100
Librenms just recognize de interface port and not CPU, memory, pop session etc 

I have the mob for this device

this is the result for the command ./discovery.php -m os,processors,mempools  -h redback -d : 

LibreNMS 2015.master Discovery
Version info:
Commit SHA: d54fd994b6e38fdcedfc799f3070783f95537cd0
DB Schema: 6
PHP: 5.5.9-1ubuntu4.14
MySQL: 10.1.12-MariaDB-1~trusty
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1]
SQL[SELECT revision FROM `dbSchema`] DB Schema already up to date.

SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE 'lns-cbv.sccnf.fr' ORDER BY device_id DESC]
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '80'] lns-cbv.sccnf.fr 80 redback
OS: /usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0Redback Networks SmartEdge OS Version SEOS-*-Release
Built by sysbuild@eussjlx7008.sj.us.am.ericsson.se Tue Sep 24 10:07:19 PDT 2013

/usr/bin/snmpget -v2c -c COMMUNITY -Ovqn -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysObjectID.0.*.4.1.2352.1.12

| Redback Networks SmartEdge OS Version SEOS-11.1.2.9-Release
Built by sysbuild@eussjlx7008.sj.us.am.ericsson.se Tue Sep 24 10:07:19 PDT 2013 | .1.3.6.1.4.1.2352.1.12 | /usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 1.3.6.1.4.1.674.10895.3000.1.2.100.1.0No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Osqnv -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalMfgName.1No Such Object available on this agent at this OID

Processors : Including: /opt/librenms/includes/discovery/processors/aos-device.inc.php
Including: /opt/librenms/includes/discovery/processors/infinity.inc.php
Including: /opt/librenms/includes/discovery/processors/netonix.inc.php
Including: /opt/librenms/includes/discovery/processors/pbn.inc.php
Including: /opt/librenms/includes/discovery/processors/ciscosb.inc.php
Including: /opt/librenms/includes/discovery/processors/sonicwall.inc.php
Including: /opt/librenms/includes/discovery/processors/avaya-ers.inc.php
Including: /opt/librenms/includes/discovery/processors/junose.inc.php
Including: /opt/librenms/includes/discovery/processors/unifi.inc.php
Including: /opt/librenms/includes/discovery/processors/powerconnect.inc.php
Including: /opt/librenms/includes/discovery/processors/pulse.inc.php
Including: /opt/librenms/includes/discovery/processors/ironware.inc.php
Including: /opt/librenms/includes/discovery/processors/watchguard.inc.php
Including: /opt/librenms/includes/discovery/processors/fortigate.inc.php
Including: /opt/librenms/includes/discovery/processors/vrp.inc.php
Including: /opt/librenms/includes/discovery/processors/ios.inc.php
Including: /opt/librenms/includes/discovery/processors/fiberhome.inc.php
Including: /opt/librenms/includes/discovery/processors/nos.inc.php
Including: /opt/librenms/includes/discovery/processors/screenos.inc.php
Including: /opt/librenms/includes/discovery/processors/datacom.inc.php
Including: /opt/librenms/includes/discovery/processors/netscaler.inc.php
Including: /opt/librenms/includes/discovery/processors/zywall.inc.php
Including: /opt/librenms/includes/discovery/processors/procurve.inc.php
Including: /opt/librenms/includes/discovery/processors/junos.inc.php
Including: /opt/librenms/includes/discovery/processors/serveriron.inc.php
Including: /opt/librenms/includes/discovery/processors/hrdevice.inc.php
 hrDevice: /usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs  -m HOST-RESOURCES-MIB:HOST-RESOURCES-TYPES -M /opt/librenms/mibs udp:HOSTNAME:161 hrDevicehrDevice = No Such Object available on this agent at this OID

/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs  -m HOST-RESOURCES-MIB:HOST-RESOURCES-TYPES -M /opt/librenms/mibs udp:HOSTNAME:161 hrProcessorLoadhrProcessorLoad = No Such Object available on this agent at this OID

Including: /opt/librenms/includes/discovery/processors/radlan.inc.php
Including: /opt/librenms/includes/discovery/processors/extreme.inc.php

SQL[SELECT COUNT(*) FROM `processors` WHERE `device_id` = '80' AND `processor_type` != 'ucd-old']
SQL[SELECT * FROM `processors` WHERE `device_id`  = '80']
Memory : Including: /opt/librenms/includes/discovery/mempools/aos-device.inc.php
Including: /opt/librenms/includes/discovery/mempools/infinity.inc.php
Including: /opt/librenms/includes/discovery/mempools/netonix.inc.php
Including: /opt/librenms/includes/discovery/mempools/pbn.inc.php
Including: /opt/librenms/includes/discovery/mempools/sonicwall.inc.php
Including: /opt/librenms/includes/discovery/mempools/avaya-ers.inc.php
Including: /opt/librenms/includes/discovery/mempools/ironware-dyn.inc.php
Including: /opt/librenms/includes/discovery/mempools/hp-procurve.inc.php
/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs  -m NETSWITCH-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/hp udp:HOSTNAME:161 hpLocalhpLocalMem = No Such Object available on this agent at this OID

/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs  -m NETSWITCH-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/hp udp:HOSTNAME:161 hpGlobalhpGlobalMem = No Such Object available on this agent at this OID

Including: /opt/librenms/includes/discovery/mempools/unifi.inc.php
Including: /opt/librenms/includes/discovery/mempools/pulse.inc.php
Including: /opt/librenms/includes/discovery/mempools/fortigate.inc.php
Including: /opt/librenms/includes/discovery/mempools/vrp.inc.php
Including: /opt/librenms/includes/discovery/mempools/fiberhome.inc.php
Including: /opt/librenms/includes/discovery/mempools/cmp.inc.php

SQL[SELECT COUNT(*) FROM `mempools` WHERE `device_id` = '80' AND `mempool_type` = 'cemp'] Including: /opt/librenms/includes/discovery/mempools/nos.inc.php
Including: /opt/librenms/includes/discovery/mempools/screenos.inc.php
Including: /opt/librenms/includes/discovery/mempools/cemp.inc.php
Including: /opt/librenms/includes/discovery/mempools/hrstorage.inc.php
/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs  -m HOST-RESOURCES-MIB:HOST-RESOURCES-TYPES:NetWare-Host-Ext-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 hrStorageEntryhrStorageEntry = No Such Object available on this agent at this OID

Including: /opt/librenms/includes/discovery/mempools/netscaler.inc.php
Including: /opt/librenms/includes/discovery/mempools/zywall.inc.php
Including: /opt/librenms/includes/discovery/mempools/junos.inc.php
Including: /opt/librenms/includes/discovery/mempools/serveriron.inc.php
Including: /opt/librenms/includes/discovery/mempools/powerconnect-cpu.inc.php
Including: /opt/librenms/includes/discovery/mempools/extreme.inc.php

SQL[SELECT * FROM `mempools` WHERE `device_id`  = '80']

SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='',`last_discovered_timetaken` ='0.207' WHERE `device_id` = '80'] Discovered in 0.207 seconds

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','lns-cbv.sccnf.fr','1458082670.3773','0.234','1')] ./discovery.php lns-cbv.sccnf.fr 2016-03-15 23:57:50 - 1 devices discovered in 0.234 secs
MySQL: Cell[1/0s] Row[5/0s] Rows[3/0s] Column[0/0s] Update[1/0s] Insert[1/0s] Delete[0/0s] @

**Comment by barto95100** [comment]
this is the old : 

**1.3.6.1.4.1.2352.2.27.1.2.5.3.0**

and the snmpwalk : 

iso.3.6.1.2.1.1.1.0 = STRING: "Redback Networks SmartEdge OS Version SEOS-11.1.2.9-Release
Built by sysbuild@eussjlx7008.sj.us.am.ericsson.se Tue Sep 24 10:07:19 PDT 2013"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.2352.1.12

iso.**3.6.1.4.1.2352.2.27.1.2.5.3.0** = Gauge32: 661

**Comment by laf** [comment]
Can you provide us access to a device to add better support?

**Comment by barto95100** [comment]
Hi,

it's not possible because it's in production...

But If you want I send you MIB

**Comment by laf** [comment]
It's much easier to code against real data so we can make sure it's done correctly.

**Comment by f0o** [comment]
Can get one of those for you next week @laf

**Comment by Rosiak** [comment]
Any news on this one?
