### ISSUE TITLE
Dashboard with sub interface graphs

### ISSUE THREAD

**Issue by drukpa** [librenms/librenms#3253]
I wanted to have a dashboard for each users, where they can view only the details(interface traffic) associated with the  subinterface from which they are subscribed to the service. If anyone could help me with this.

**Comment by laf** [comment]
I'm not clear on what you want here.

Users can create dashboards and add interface graphs to the dashboard. If they are restricted users then they should only be able to add graphs for what they have access to.

**Comment by drukpa** [comment]
I got this solved. Thank You.
