### ISSUE TITLE
Error Drawing Graph

### ISSUE THREAD

**Issue by backstube** [librenms/librenms#3259]
Hi,
on our Ubuntu 14.04.4 LTS box running LibreNMS only one system currently is being monitored: localhost. For several days now all graphs show the above mentioned error. Also memory and storage bars stay dark red. All looks very much like the images over at #2108.

Here is the validate run output:

> Version info:
> Commit SHA: 271e767077994dc7db7fa227e003e5c3e84eec34
> DB Schema: 107
> PHP: 5.5.9-1ubuntu4.14
> MySQL: 5.5.47-0ubuntu0.14.04.1
> RRDTool: 1.4.7
> SNMP: NET-SNMP version: 5.7.2
> 
> [OK]      Database connection successful

Webserver is apache 2.4.7 which runs smoothly.

The only one thing LibreNMS does bring up is the processor type, just below the processors graph on the Overview pane. The graph itself and all other meters show nothing.

If I append `&debug=true` to the device overview page, I get reasonably okay looking SQL queries. On the PHP side, I get this:

> Array ( [errno] => 8 [errstr] => Undefined index: influxdb [errfile] => /opt/librenms/includes/influxdb.inc.php [errline] => 15 )
> Array ( [errno] => 8 [errstr] => Undefined index: fetchrows_sec [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 276 )
> Array ( [errno] => 8 [errstr] => Undefined index: fetchrows [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 277 )
> Array ( [errno] => 8 [errstr] => Undefined index: sess_id [errfile] => /opt/librenms/html/includes/authenticate.inc.php [errline] => 65 )
> Array ( [errno] => 8 [errstr] => Undefined index: token [errfile] => /opt/librenms/html/includes/authenticate.inc.php [errline] => 65 )

Lots of them. 201 in total, with variations.

Does anyone have a clue what's going on here? I'd be happy to get pushed in the right direction. Thanks in advance! Oh and please ask if anything is unclear or if further details are needed.

**Comment by paulgear** [comment]
The PHP undefined index warnings are normal; please make sure you're up-to-date by running ./daily.sh from /opt/librenms, and then use the link to display the RRD command & paste the results.

**Comment by paulgear** [comment]
Oh, also please run ./validate.php and see if it notes any problems.

**Comment by backstube** [comment]
Hi Paul,
thanks for your speedy reply!
The validate.php output is already in my original post. No errors here afaics.

The other one you mentioned runs on a daily basis (hence the name) and it did that last night according to logfile `/opt/librenms/logs/daily.log`. I ran it manually right now, here's the output:

```
librenms@myhost:~$ ./daily.sh
Updating to latest codebase                        OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
```

What do you mean by this:

> ... and then use the link to display the RRD command & paste the results.

in your previous post?

Cheers.

**Comment by laf** [comment]
Right click a graph, select copy _IMAGE_ url, add &debug=true to the end and paste the results here.

**Comment by backstube** [comment]
Hi laf, ah, that one. Thanks.

Here it is:

graph /tmp/mT3ISeCZllM5p2Me.png -g --alt-autoscale-max --rigid -E --start 1458081000 --end 1458167400 --width 490 --height 163 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal COMMENT:' Now Avg Max' COMMENT:'\n' CDEF:inB= CDEF:outB= CDEF:octets=inB,outB,+ CDEF:doutB=outB,-1,* CDEF:inbits=inB,8,* CDEF:outbits=outB,8,* CDEF:bits=inbits,outbits,+ CDEF:doutbits=doutB,8,* VDEF:95thin=inbits,95,PERCENT VDEF:95thout=outbits,95,PERCENT CDEF:d95thoutn=doutbits,-1,* VDEF:d95thoutn95=d95thoutn,95,PERCENT CDEF:d95thoutn95n=doutbits,doutbits,-,d95thoutn95,-1,*,+ VDEF:d95thout=d95thoutn95n,FIRST VDEF:totin=inB,TOTAL VDEF:avein=inbits,AVERAGE VDEF:totout=outB,TOTAL VDEF:aveout=outbits,AVERAGE VDEF:tot=octets,TOTAL COMMENT:' \n' HRULE:999999999999999#FFFFFF:'Total In ' GPRINT:inbits:LAST:%6.2lf%s GPRINT:inbits:AVERAGE:%6.2lf%s GPRINT:inbits:MAX:%6.2lf%s GPRINT:totin:%6.2lf%sB COMMENT:'\n' HRULE:999999999999990#FFFFFF:' Out' GPRINT:outbits:LAST:%6.2lf%s GPRINT:outbits:AVERAGE:%6.2lf%s GPRINT:outbits:MAX:%6.2lf%s GPRINT:totout:%6.2lf%sB COMMENT:'\n' HRULE:999999999999990#FFFFFF:' Agg' GPRINT:bits:LAST:%6.2lf%s GPRINT:bits:AVERAGE:%6.2lf%s GPRINT:bits:MAX:%6.2lf%s GPRINT:tot:%6.2lf%sB COMMENT:'\n' HRULE:0#999999

command returned 0 (ERROR: String ends after the = sign on 'CDEF:inB=' )

OK u:0.04 s:0.01 r:0.05
graph /tmp/mT3ISeCZllM5p2Me.png -g --alt-autoscale-max --rigid -E --start 1458081000 --end 1458167400 --width 490 --height 163 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal HRULE:0#555555 --title='Error Drawing Graph'


command returned 0 (571x220 )


Runtime 0.11926794052124 secs
MySQL: Cell 0/0s Row 5/0.001s Rows 4/0s Column 0/0s

**Comment by laf** [comment]
That's got no rrd file referenced in it. Do you not see any graphs at all?

What version of rrdtool. I can only say that you've got something mis-configured. We run 14.04 at work with no issues - maybe retry the install docs.

**Comment by laf** [comment]
Proposing to close in 48 hours.

**Comment by happicamper** [comment]
Sorry for commenting although it is already closed issue, but is there any latest solution for this error `ERROR: String ends after the = sign on 'CDEF:inB='` I'm running centos 7 with `rrdtool 1.4.8`. My problem is there is a graph but no statistics or drawings being showed. Delete this comment if inappropriate thanks.

**Comment by laf** [comment]
no graphs at all?

Have you followed any of the FAQ's or debug information in this issue?

**Comment by happicamper** [comment]
@laf I decided to install a fresh copy of LibreNMS and followed the instructions [here.](http://docs.librenms.org/Installation/Installation-CentOS-7-Apache/)
And now everything works. 
Maybe I misconfigured a lot of permission on my first deployment. 
Thank you very much.

**Comment by kc7aad** [comment]
I have had a small install running fine for several weeks (~8 now), but when I added a new client a couple of days ago, it is now showing the red storage, memory and processor graphs. I use the debug syntax, and it reports:
graph /tmp/IMBWPht47bzNAMmL -l 0 -u 100 -E --start 1518012600 --end 1518099000 --width 1512 --height 306.33333333333 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal COMMENT:' Size Used %age\l' --daemon unix:/var/run/rrdcached.sock

command returned (OK u:0.01 s:0.01 r:0.00 )

graph /tmp/IMBWPht47bzNAMmL --alt-autoscale-max --rigid -E --start 1518012600 --end 1518099000 --width 1512 --height 306.33333333333 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal HRULE:0#555555 --title='Error Drawing Graph' --daemon unix:/var/run/rrdcached.sock

command returned (1593x365 OK u:0.10 s:0.04 r:0.12 )


Runtime 0.179s
SNMP [0/0.00s]: Get[0/0.00s] Getnext[0/0.00s] Walk[0/0.00s] MySQL [12/0.00s]: Cell[0/0.00s] Row[2/0.00s] Rows[8/0.00s] Column[1/0.00s] Update[0/0.00s] Insert[0/0.00s] Delete[1/0.00s] RRD [0/0.00s]: Update[0/0.00s] Create [0/0.00s] Other[0/0.00s]

I don't see anything that looks awry to my untrained eye! But I also don't know what to look at! My validate.php returns with:
====================================
Component | Version
--------- | -------
LibreNMS  | 1.36-44-g9777963
DB Schema | 234
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.33-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Database connection successful
[OK]    Database schema correct
[FAIL]  We have found some files that are owned by a different user than librenms, this will stop you updating automatically and / or rrd files being updated causing graphs to fail.
        [FIX] chown -R librenms:librenms /opt/librenms
        Files:
         /opt/librenms/.mysql_history


I'm not sure how to fix this yet. Does anyone have any thoughts on how to resolve this?
Also.. Other previously added devices are showing graphs as expected, and as they have for the last several weeks. Just not new ones!


Thanks.
Rod
