### ISSUE TITLE
Install docs need updating for CentOS 7!

### ISSUE THREAD

**Issue by laf** [librenms/librenms#326]
Main thing is remove welcome.conf from /etc/httpd/conf.d/

Require all granted is also needed in librenms.conf

Also NoDecode for AllowEncodedSlashes

**Comment by joubertredrat** [comment]
Hi guys,

@laf, I will try to create script to easy install on debian/ubuntu and CentOS6/7, if I can I post here

**Comment by f0o** [comment]
@laf isnt this covered by now?

**Comment by laf** [comment]
I don't think so @f0o. The docs don't mention welcome.conf I don't think.

**Comment by f0o** [comment]
`Require all granted` seems to be only used in `mod_authz_core` but I cant find any directive related to it in the config nor in the .htaccess.

Where did you want it to be mentioned?

**Comment by laf** [comment]
This is what is needed @f0o:

  <Directory "/opt/librenms/html/">
    AllowOverride All
    Options FollowSymLinks MultiViews
    Require all granted
  </Directory>

Without you get 403 errors.
