### ISSUE TITLE
Ports types not shown on Enterasys switches

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#3263]
Hi,

I have an issue where the port types and numbers (ifNames) are shown on the Enterasys switches in the GUI; only ifDescr is shown although looking at the discovery and polling command debugs; ifNames are being picked up. Please help, the discovery dump is here, https://dpaste.de/giys and teh poller dump here, https://dpaste.de/moOD. The screenshot is below;

![image](https://cloud.githubusercontent.com/assets/16717388/13854091/8338c704-ec72-11e5-8f57-9adfabf19e24.png)

**Comment by murrant** [comment]
Add this code to your config.php to fix.
```
$config['bad_if'] = array_diff($config['bad_if'], array('ras'));
```

**Comment by breeman1** [comment]
HI @murrant 

The code you provided does not seem to fix the issue. I re-read my initial post and I can see what caused the confusion, sorry, my bad. I meant to say "I have an issue where the port types and numbers (ifNames) are **NOT** shown on the Enterasys switches in the GUI..." instead of "I have an issue where the port types and numbers (ifNames) are shown on the Enterasys switches in the GUI..."  
Below is the screenshot of a portion of the ./discovery.php -h x.x.x.x -d -m ports command and I have highlighted in arrows the information I need to be displayed in the GUI over and above the ifDescr information which is already being displayed.

![snap2](https://cloud.githubusercontent.com/assets/16717388/18224854/0958fdd0-71e4-11e6-88c1-ca71720fb717.png)

**Comment by breeman1** [comment]
Wait, I can actually see a lot more ports now being displayed on the Enterasys switches after this change, however I am still not getting the ifNames information being displayed. This change also seems to have resolved the problems I raised in issue [https://github.com/librenms/librenms/issues/2838](url), see below;

![snap2](https://cloud.githubusercontent.com/assets/16717388/18226673/6361433e-720f-11e6-8a72-35a2cf6cacdf.png)
