### ISSUE TITLE
Component API PUT

### ISSUE THREAD

**Issue by djtecha** [librenms/librenms#3264]
Is there a way to add a component via the API? Tried looking at the MiB php and my head started to spin. I'm just looking to add a SW version to the components table for a server.

**Comment by laf** [comment]
No only reading component data from the api is possible at present.

@adaniels21487 is this something we should and can add in?

**Comment by adaniels21487** [comment]
@djtecha @laf 
This should be fairly trivial to add, I will pull something together this week.

If you are developing with components you should take a look at #3272 to see whats being planned.

**Comment by adaniels21487** [comment]
@djtecha @laf 
Does this meet your needs, can we close this request?
