### ISSUE TITLE
Sorting on device summary page not respecting numerical values

### ISSUE THREAD

**Issue by djtecha** [librenms/librenms#3265]
For Instance if you sort by name you would get the following order:

test-1
test-10
test-11
test-8
test-9

**Comment by murrant** [comment]
Probably can just need array_multisort() with natural order

**Comment by laf** [comment]
We just do a sort in mysql, post sorting again for putting the data in bootgrid is possible, is it worth it?

**Comment by murrant** [comment]
Hmm, it is definitely not correct to sort it in before returning to bootgrid.  Changing the sort order or column will just mess up the order again anyway.

I looked and I'm not sure if there is an easy way to do a natural sort with bootgrid.

**Comment by laf** [comment]
We just return an array in the code before outputting via Json so it could just be done before being Json encoded

**Comment by murrant** [comment]
That still wouldn't help.  It needs to be done in javascript.

**Comment by YukonRob** [comment]
I put all my devices in by IP so this affects me greatly. Would love to see this fixed. I tried to update device ip's with leading zero's to fix the sorting but ran into the octal compatibility conversion.

**Comment by laf** [comment]
Closing this as it doesn't appear we can resolve this.
