### ISSUE TITLE
Optimize Graph Loads/Refreshes

### ISSUE THREAD

**Issue by jawaidbazyar** [librenms/librenms#3270]
When viewing a page with a lot of graphs on it (for example, a Ports view of all the ports on a router), the initial page load takes forever as the page tries to load hundreds of graphs.

On a refresh (every 5 minutes?) this also takes an extraordinary amount of time; it also causes the rendering of the page to change and the view to bounce around a lot.

I suggest several optimizations:

1) before a graph is loaded, have the DIV the image resides in pre-sized so that the browser rendering engine doesn't have to re-render the page when the image does load.
2) Do not attempt to load a graph image unless the DIV it loads into is visible (i.e., currently showing in the browser window)
3) on a refresh, mark the images as "dirty", but reload only the images visible in the current browser window. This way the browser would not re-render the whole page, disturbing the current view.

All this behavior would boil down to pre-sizing the DIVs, having a "Dirty" flag on the DIV, and only loading the image if the DIV is visible.

**Comment by f0o** [comment]
We have exactly what you describe already.

Are you running a very old version perhaps?

On 20 March 2016 17:43:24 CET, jawaidbazyar <notifications@github.com> wrote:
>When viewing a page with a lot of graphs on it (for example, a Ports
>view of all the ports on a router), the initial page load takes forever
>as the page tries to load hundreds of graphs.
>
>On a refresh (every 5 minutes?) this also takes an extraordinary amount
>of time; it also causes the rendering of the page to change and the
>view to bounce around a lot.
>
>I suggest several optimizations:
>
>1) before a graph is loaded, have the DIV the image resides in
>pre-sized so that the browser rendering engine doesn't have to
>re-render the page when the image does load.
>2) Do not attempt to load a graph image unless the DIV it loads into is
>visible (i.e., currently showing in the browser window)
>3) on a refresh, mark the images as "dirty", but reload only the images
>visible in the current browser window. This way the browser would not
>re-render the whole page, disturbing the current view.
>
>All this behavior would boil down to pre-sizing the DIVs, having a
>"Dirty" flag on the DIV, and only loading the image if the DIV is
>visible.
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/3270

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jawaidbazyar** [comment]
My version says "beb4091".

**Comment by f0o** [comment]
Most recent version so far is: bcafac560c2a1a45ddb5e227d45e6dc4644a1a88 (2 days ago, master branch)
Most recent tagged release is: 03d8345b472cb4408434a8dcb7834ff05ba83689 (14 days ago)

I suggest updating your install, a lot of cool stuff happened :)

**Comment by jawaidbazyar** [comment]
I will.

I do actually see the desired behavior on a Device overview page, but not on a ports list page.

**Comment by f0o** [comment]
I'm currently only on my phone, i will double check your behaviour when I'm home again. Who knows, might be a bug after all

**Comment by Tatermen** [comment]
I've encountered this myself with stacked switches. It seems to be caused by the way LibreNMS generates the graphs, which appears to be to - PHP tells rrdtool to read from an RRD file and generate a graph in /tmp with a random filename (eg. /tmp/1EapgsBXYwnM9qV7.png), which PHP then serves to the viewer and afterwards deletes from /tmp

On devices with a lot of ports, this causes a high I/O load as each RRD file is read from, and a graph written to disk and then deleted. For example, three stacked 48 port switches means 144+ interfaces, which means LibreNMS shows 4 graphs for each port, so 576 or more png files generated, written to disk and then deleted.

A simple fix if you are getting this is to make /tmp a RAM disk. via something like this in your fstab:

`tmpfs                /tmp                 tmpfs      noexec,size=512M      0 0`

A proper fix would be to have RRDtool output the graphs to STDOUT so it's not writing anything to disk.

**Comment by laf** [comment]
I've tested outputting rrdtool graph to stdout and printing this straight to the browser.

I have a limited test setup on a vm in virtual box with only a handful of ports. However I've not seen a constant reduction in speed to say using stdout over writing a file and reading it is better.

If you fancy trying it here's a patch against the latest branch as of now: https://gist.github.com/laf/ae523f478f57e6a462fe90b228cec49d

**Comment by laf** [comment]
Switching to svg graphs provides a speed boost but as no further discussion has been had then this issue is closed.
