### ISSUE TITLE
Add possibility to disabling/enabling modules by device groups

### ISSUE THREAD

**Issue by marvin4242** [librenms/librenms#3273]
Hello,

I don't need some modules on all my devices ( Ports polling on access switches, ...).
I can manualy disable them, but I have one thousand swtches...

It could be great to have the possibilty to disabling/enabling modules by device groups.

Thanks

**Comment by vitalisator** [comment]
:+1:

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by imraro** [comment]
It seems that it has not been implemented yet.
