### ISSUE TITLE
Monitoring Kerio Operator

### ISSUE THREAD

**Issue by reverzer** [librenms/librenms#3275]
We switched from Observium to LibreNMS.
Some servers we monitor are Kerio Operator servers and LibreNMS isn't showing any disk, CPU and RAM information on the Kerio Operator servers while we didn't had this issue with Observium.

Are there other people with this problem?

Fred

**Comment by mkruyswijk** [comment]
i can try, did you install anything specific with regards to the SNMP deamon?

**Comment by reverzer** [comment]
No I didn't.
When you installed Kerio Operator the system is in read only mode, so the only thing you can do is turn on snmp in the webinterface of Operator.

Like I said everything was working fine in Observium.

**Comment by Rosiak** [comment]
@reverzer 
The fact that "everything is working on obs.." doesn't help us much. Years have gone and lots of water have passed under the bridge..

That being said, can you supply us with a SNMPWALK or similar?

**Comment by laf** [comment]
Please feel free to re-open this once you can provide the information needed.
