### ISSUE TITLE
Possible "bug" in rendering CBQoS graphs

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#3278]
Hi,

I enabled CBQoS on my Cisco WAN routers and it is working great except a bit of confusion when it comes to the graphs are rendered. As an example, in the image below the Red class-map is shown as generally having a lower thrcoughput in actual graphs while it the highest according the the graph legend. In this case, the "Now" throughput of the Pink class-map is 1.61 Meg while in the graph is close to 22 Meg. Am I interpreting these values correctly or is there a possible in graph rendition? 

![image](https://cloud.githubusercontent.com/assets/16717388/13955495/91b50674-f04d-11e5-93be-06763cb342ee.png)

**Comment by geordish** [comment]
Hi @breeman1, I think you are interpenetrating the graphs wrong. The values are stacked on top of each other. You don't want to look at 0 to the top, you want to look at just the gap that the area occupies. Ie from around 20-22meg (This graph is pretty hard to read values from!)

**Comment by laf** [comment]
Proposing to close in 24 hours.

**Comment by breeman1** [comment]
HI @geordish . I do not think I am interpreting the graphs incorrectly. Below is another graph from one of the other routers we poll and the graphs look OK to me.

![snap50](https://cloud.githubusercontent.com/assets/16717388/14136442/35eaa616-f663-11e5-87a1-a56209b7d757.png)

**Comment by breeman1** [comment]
I tried understanding the "suspect" graph again today and I still do not think it is rendering the policy classes correctly. I think the pink graph should swap places with the red one at least judging by the values shown at the bottom of the legend. Is my thinking not correct here?


![snap51](https://cloud.githubusercontent.com/assets/16717388/14136640/22e9479c-f664-11e5-9d71-80402883cff4.png)

**Comment by laf** [comment]
I think you are reading the graphs wrong, the values match up for what is shown (it's a stacked graph). That doesn't mean the the graph looks right though and it may be possible to change things round but as for data being represented - I believe it's correct.

**Comment by adaniels21487** [comment]
Hi @breeman1 

The stacked graph is intended to demonstrate each class adding up to the total throughput.
If you want to see what it looks like as a line graph without the stack, try this:
In the file: html/includes/graphs/port/cbqos_traffic.inc.php

Change Line 60, From:

	$rrd_additions .= " AREA:MOD" . $count . "#" . $color . ":'" . str_pad(substr($components[$id]['label'],0,15),15) . "'" . $stack;
	
To:

	$rrd_additions .= " LINE1.25:MOD" . $count . "#" . $color . ":'" . str_pad(substr($components[$id]['label'],0,15),15) . "'";

**Comment by breeman1** [comment]
HI @adaniels21487,

Ok, now I understand. The "without the stack" modification looks more like what I was expecting with the stacked graph. It would be great if we had the option to toggle between the two options including perhaps in future an ability to toggle between the class graphs themselves.

![snap52](https://cloud.githubusercontent.com/assets/16717388/14143458/a262c012-f68b-11e5-909e-6a1e0f527ff1.png)

**Comment by adaniels21487** [comment]
@breeman1 @laf 
Do we still need this one. I propose closure.

**Comment by laf** [comment]
Only if we're changing the graphs to lined instead stack, I'll leave it upto you to decide :)

**Comment by breeman1** [comment]
I think we can close this, however It would be great if consideration can be made toward having a button within the CBQoS screen to enable toggling between the two graph types. That way one can choose the graph type/rendering that suits their needs best. Thanks.
