### ISSUE TITLE
syslog not working

### ISSUE THREAD

**Issue by mkruyswijk** [librenms/librenms#3282]
Hi all,

thank you very much for the very impressive tookit. currently trying to get the syslog working. i have seen an already closed ticket about the "%" problem. tried to see if that was my case, but it wasn't.
i seem to receive the logmessages, but i am not able to find them back in the webgui.

when i enable logging, this is what i get in the librenms.log
s01-switch-3750||local7||notice||notice||bd||2016-03-23 15:04:17||Mar 23 14:04:11.834: SYS-5-CONFIG_I: Configured from console by maartenk on vty0 (192.168.128.165)||151352

any ideas why i am not seeing this in the webgui?

**Comment by laf** [comment]
Does s01-switch-3750 match a hostname or sysname in your install?

**Comment by laf** [comment]
Proposing to close in 48 hours.

**Comment by mkruyswijk** [comment]
hi, Yes it does match on the hostname. I can put it in a sys name to be sure? is there a filter that filters out syslog messages that do not match any available hostname? if so, how does that work with devices added by IP?

**Comment by mkruyswijk** [comment]
receiving alerts now. just matching the sysname was not enough. i really had to put in the ip in DNS. when all matched, it started to work.
