### ISSUE TITLE
Tagged vlan ports not being displayed on vlans page.

### ISSUE THREAD

**Issue by khobbits** [librenms/librenms#3285]
While the ports page, shows all vlans a port is on, including tagged.  With a mix of tagged and untagged vlans, only the untagged ports show.

Ie:
vlan 1000
   name "Lan"
   untagged 1-40
   tagged 41
   no ip address
   exit

vlan 1001
   name "Wifi"
   untagged 41
   tagged 1-40
   no ip address
   exit

The only port shown to be on the 'wifi' vlan, would be port 41, and all other ports would show as 'lan' vlan.

**Comment by laf** [comment]
I think you will have to provide more information than this with screenshots

**Comment by ciscoqid** [comment]
I can do that -- see the same behavior on a Procurve, for example.  In
this display, 252 should be tagged on all ports 152 is untagged on, and
a lot more tags should be seen on other VLANs for various trunks.  The
VLANs show up properly in the port display page, though.

Regards
Mark



On 3/25/16 4:17 AM, Neil Lathwood wrote:
>
> I think you will have to provide more information than this with
> screenshots
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/librenms/librenms/issues/3285#issuecomment-201243701>
>
> This message has been scanned by CanIt-PRO.

-- 
Mark D. Nagel, CCIE #3177 Emeritus <mnagel@willingminds.com>
Principal Consultant, Willing Minds LLC (http://www.willingminds.com)
cell: 949-279-5817, desk: 714-495-4001, fax: 714-844-4698

** For faster support response time, please
** email support@willingminds.com or call 714-495-4000

**Comment by khobbits** [comment]
![2016-03-26_14-27-15](https://cloud.githubusercontent.com/assets/428811/14060518/e5726b44-f35e-11e5-9c13-3acff78f97d6.png)

**Comment by ciscoqid** [comment]
I just uploaded mine as well -- I for some reason did not see any updates from the thread and was out of town, sorry!

**Comment by khobbits** [comment]
Looks much better:

![image](https://cloud.githubusercontent.com/assets/428811/19309364/36a8d740-907c-11e6-8e65-d78929122764.png)

**Comment by murrant** [comment]
@mpoinsignon No need to comment on old issues.

We found your issue on Discord and it was that you were using snmpv3 and were not allowing the vlan-1, vlan-5 contexts.

**Comment by YenzRanger** [comment]
@murrant 
He wasn't the guy on discord yesterday - that was me ;)

@mpoinsignon 
For me it was a cisco device which only showed untagged ports like in your screenshot. After running `./discovery.php -d -m vlans -h 192.168.8.34` I saw many authentication errors in the response. If you have the same problem you can find some commands which pointed me into the right direction here: https://support.solarwinds.com/Success_Center/User_Device_Tracker_(UDT)/SNMPv3_BRIDGE-MIB_commands_need_to_be_added_to_Cisco_devices

For me `snmp-server group YourGroupName v3 priv context vlan- match prefix` was enough to fix it.
