### ISSUE TITLE
Feature request: disable / ignore checkbox for device in group view

### ISSUE THREAD

**Issue by johanreinalda** [librenms/librenms#3287]
It would be useful to replicate the device edit 'ignore" and 'disable" functionality in the group view. This would make it a lot simpler to do those actions on a group of devices. Javascript to disable/ignore all in one fell swoop would be even more awesome!

Thanks for considering.

Johan

**Comment by Rosiak** [comment]
Hi,

We are cleaning up the issues here on GitHub, all feature requests will be moved to:
https://community.librenms.org/c/feature-requests

Hence the closure of this issue.
