### ISSUE TITLE
Sensor Alerts even if interface is admin down

### ISSUE THREAD

**Issue by digitalpilotnm** [librenms/librenms#3289]
Cisco 6506 SUP-V720-3CXL
Libre is alerting for sensor under-limit on interfaces that are in a ADMIN DOWN state
ergo     
interface G1/2  
shutdown

If the interface is ADMIN DOWN, there there should NOT be any sensor readings on that interface, and no alerts.

**Comment by laf** [comment]
sensors aren't tied to interfaces so we can't do this.

**Comment by laf** [comment]
This is also a duplicate from an issue you've previously opened: #1065

**Comment by digitalpilotnm** [comment]
I just put sensor data into ticket 1065.
