### ISSUE TITLE
Alerts happen with sensors even if "alerting disabled"

### ISSUE THREAD

**Issue by digitalpilotnm** [librenms/librenms#3290]

**Comment by digitalpilotnm** [comment]
If I go into this specific device, Cisco 6506, and select HEALTH and then TURN OFF alerts for specific interface (tx power, rx power, current bias, etc)  Libre still sends out alert emails for those interfaces

**Comment by laf** [comment]
you need to update you rule to also check sensor_alert equals 1 (i.e alerts turned on)

**Comment by digitalpilotnm** [comment]
no affect    still alerts

**Comment by laf** [comment]
Post your rule.

**Comment by laf** [comment]
Please feel free to re-open this once you provide your alert rule.
