### ISSUE TITLE
Feature Request: Add device dependencies to alerting

### ISSUE THREAD

**Issue by mrunkel** [librenms/librenms#3293]
It would be great to be able to suppress alerts if a parent device is down.

For example, if devices B & C can't be reached because device A is down, when device A goes down, don't alert on B & C.

To accomplish this, we:
- Need to build a UI to allow the configuration of dependencies.
  - should allow for both upstream and downstream configuration (meaning that you should be able to define both parents and children on devices.
- Need to build logic into alerting system to suppress alerts when parents are down.
- Should still log check failure locally

Bonus points: suggest parent by doing a traceroute to new device?

**Comment by paulgear** [comment]
This would be a great feature to have :-)

**Comment by barryodonovan** [comment]
Is anyone working on this feature?
I thought I remembered seeing a suggestion somewhere of automating parent child discovery using traceroute but I can't find it now.

This would be a very useful feature (even manually entry of dependencies) and I'd like to help implement it if necessary.

**Comment by barryodonovan** [comment]
I have been looking at this with an eye to getting something done on it over xmas.

Does anyone have a preference for where the device parent data might be stored? I was considering using an attrib_type 'parent_device' with an attrib_value of 'parent_device_id' in devices_attribs table. This would allow for easy storage of multiple parents per device and should be easy to integrate into an pre-alert check.

I also considered the possibility of in some way using some of the information already gathered about device ports, either by tagging a port as a 'parent_link' port or using the port data to auto-build a parent relationship table. This might over complicate things though.

Does anyone have any thoughts on this before I get too far in?

**Comment by laf** [comment]
I've got no objection to using the attrib_type but I would say that I could see this expanding out and if so, devices_attribs wouldn't cut it long term so I'd also have no issue in having a new table to future proof the support. I'm also not sure how well devices_attribs play with alerting (@f0o?)

As for ports, we should already have the data to do relationships but how would you work out what was the dependant device?

**Comment by barryodonovan** [comment]
@laf Not entirely sure if it would work but was thinking along the following lines:

if (device_down) {
  check_all_neighbors(device)
}
function check_all_neighbors(device) {
  find_all_neighbors(device) {
    foreach (neighbors) {
      if (!device_known_down) {
        is_up_down(neighbor) {
          if (neighbor_is_up) {
            alert(device is down)
            exit
          }
          add_to_device_known_down(neighbor)
        }
      }
    } // all neighbors are down
    foreach (neighbors) {
      check_all_neighbors(neighbor)
    }
  }
}

The obvious advantage to this kind of dependency check would be that it requires no special advance knowledge of relationships, it just limits alerting to the first device in a tree that librenms sees as down...

**Comment by laf** [comment]
Out of interest, how would it work if device a is dependant on device b and device a is polled, seen as down and then we go to alert but the dependancy checker looks at the status of b and it's not yet been polled in this cycle but was up previously?

**Comment by barryodonovan** [comment]
I could see three options:
1. Prioritise polling of dependencies to expedite alerting. 
2. Wait until poller cycle is complete and then process alerts.
3. Carry out stand-alone, eg ping or smtpstatus, status checks on dependencies during an alert process.

3 would be my preference since alerting is not excessively delayed but the current poller cycle structure is not modified. The only change to current processes might be to compile a hash table of host status and age of the status. This may be done already for the availability map or it may help to reduce the cost of generating the availability map.

**Comment by laf** [comment]
We have last_ping for the datetime stamp of when we last did a ping check.

Would we want to only create an alert for the top of the tree device or all and then only send an alert for the top of the tree device?

**Comment by barryodonovan** [comment]
I definitely think we only want to alert the top of the tree.

Is there any benefit to creating alerts on other devices? I could see a benefit to illustrating the extent of the tree within the alert sent, eg top of tree plus 7 other devices or:

ALERT:
Affected devices:
...............Device A
.....Device B.......Device D
Device C..............Device E
....................Device F...Device G.

(apologies for formatting)



________________________________

**Comment by laf** [comment]
The question was more around do we show the 'notification' in the webui for all of them (I'd say we should) but alerts themselves only send to top of the tree device (again I'd say we should).

All imho.

**Comment by barryodonovan** [comment]
Sorry, got you.

Yes, everything should show down in GUI but only alert on top of tree.

I'm hoping to get into it next week, once I have something I do a PR.

Barry

________________________________

**Comment by mgs4332** [comment]
Hey all!

Did this ever take off? We're looking into LibreNMS and this is actually a really big key feature we're looking to use and take advantage of.

Thanks!

Mike

**Comment by laf** [comment]
Not yet

**Comment by FrostByghte** [comment]
I've just installed LibreNMS after checking out a LOT of different network monitoring packages.  LibreNMS is by far one of the easiest to setup....but this feature would eliminate a ton of noise during an alert.  Or perhaps I have missed something and there is another way to not be alerted 5 times when a key router drops? :)

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/host-dependencies/651
