### ISSUE TITLE
Alert Log detail column sub-optimal

### ISSUE THREAD

**Issue by mrunkel** [librenms/librenms#3295]
On the alert log page, the unlabled "detail" column is very unintuitive.

![screenshot 2016-03-28 08 12 59](https://cloud.githubusercontent.com/assets/3205232/14072180/a63e3cfe-f4bd-11e5-8958-19cc1fbb5644.png)

From my viewpoint the problems are as follows:
- It's wasteful. That's a lot of white space on a page
- It's unclear what it is, or how it works.
  - The + doesn't appear until you mouse over it
  - For almost every row, clicking on the + does nothing since most checks have no alert data.
- When additional data is displayed, it's displayed under the device column

My suggestion
- remove the column completely
- display the + next to the device name when there is only additional data to display, for all other rows, don't display it all.

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #166](https://github.com/librenms/librenmsv2/issues/166) via [**ZenHub**](https://www.zenhub.com/)
