### ISSUE TITLE
Feature [Telegram]

### ISSUE THREAD

**Issue by carson20** [librenms/librenms#3297]
Can there be a feature that can message rather then emailing the status or when a router or switch goes down  via telegram bot that can be created for admin ?

**Comment by mrunkel** [comment]
Looks like it is possible. https://core.telegram.org/bots/api

**Comment by carson20** [comment]
https://github.com/librenms/librenms/issues/3297#issuecomment-202943728
@mrunkel yes with bot but if they implement in a gui where a user or admin can place the token and use  that could be as simple and better then sending sms

**Comment by jdoclot** [comment]
I think that will be a great feature to have Telegram Messaging notifications for LibreNMS

**Comment by Rosiak** [comment]
Duplicate #2114
