### ISSUE TITLE
Column sorting

### ISSUE THREAD

**Issue by XxPatrickxX** [librenms/librenms#330]
Adding column sorting for the views available under the Health area.

For example:
https://librenms.example.org/health/metric=storage/view=detail/ -  sort by storage/usage/% used.
https://librenms.example.org/devices/ - sort by platform/os/uptime

**Comment by laf** [comment]
PR in place to cover this now #671.

Needs pages to be swapped over.

**Comment by laf** [comment]
Support is now to be able to do this and we have another issue in place to start going through converting some of the pages. Closing this now.
