### ISSUE TITLE
Qualys SSL LABS API Integration

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#3307]
https://github.com/ssllabs/ssllabs-scan/blob/stable/ssllabs-api-docs.md
Would this be in people's interest?

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I would :D

On 30 March 2016 17:41:15 CEST, "Søren Rosiak" <notifications@github.com> wrote:
>https://github.com/ssllabs/ssllabs-scan/blob/stable/ssllabs-api-docs.md
>Would this be in people's interest?
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/3307
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5MhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikgPGYwb0Bs
aWJyZW5tcy5vcmc+BQJW+/REAAoJEJMZKtVWOFzB488P/AnBSUVZnjy7HeTBI6TK
7oDV6o8Ancb/P/Rl8StMYvkYKhOhb9pnK0604Zcrlzxtkeg9OI/OfC3/IdofO/IS
qtrhcZrV6dYIEG6+sjdYJIQtTENAK+UUXVPPlJy5WQSmq+rwzPpCO+B1ksdQJ1ns
RxWMHGYmlac65nLt6rBVFG++fvP8mZUrFbx6EGg81cnJTTL0hhyzvXiTyRnmHXgR
ILW/iSY5J9v68EtmUDozk+nx2GUjly6BRnLUD09snnqVQ8SlqVE10Xg5y2fVKzhd
MKVYCFJjbzZPUkFAWlQHILqNPeVFynEDcL5Tbv4eTCnaX88rnkzqhupLPlSwXaTf
TZ1HpExdioBTZRVak+jPhFOwDgaW78OjrPyYBSaAgm+B7UJtXiZ0we8XnctF8fec
GAa8XXOc84Va6Zc7sJooq8JN3Y9QMUsrLusQb+c124zl3KjCVezghCycTIZgDd+n
2e1y7O4mvVdMXYWup5/k/Vsn0mgOsMo7OvfZhiLJmP2H6HnrhQJq8dF7ouA9mwV5
zKtqJ85c6nPxccGndYfZYb+V4OkcwYN9MFVxOG2Bg/Ct0CNjmotN/0htRBSc0v56
g0CiXusHd2AqtB41duVNmrs0J3PIXlooP2184X4KedYm1BE7tPLMdWlmSUEdi42T
et+9+UCgiZraE+sVsJtBey9F
=viih
-----END PGP SIGNATURE-----

**Comment by Rosiak** [comment]
Closing as this as just a idea, but no reel need from the community.
