### ISSUE TITLE
CPU Spike in Core while Discovering/SNMP-Scan

### ISSUE THREAD

**Issue by higante702** [librenms/librenms#3313]
Good afternoon all!

I am in a pickle right now. I was tasked (as a network engineer) to build a good monitoring solution. Being new to the game, I looked around and tried my hand at this software. 

I got the graphing portion working, and ran into a problem. Once I fixed the graphing portion (only had 4 devices added via addhost), I started to add about 40 more devices. Once I added those, anytime Librenms is working, my core switches CPU spikes up a bit. Here is an output from our switch:

 Librenms (discovery/SNMP-Scan):

 PID USERNAME  THR PRI NICE   SIZE    RES STATE    TIME   WCPU COMMAND
 1089 root        2  44  -52 72268K 18952K select 178.2H 29.20% sfid
 1091 root        1 132    0 71420K 18776K RUN     27.4H 16.26% pfem
 1088 root        1   8    0 68552K 12140K nanslp  55.4H  8.35% chassism
 3161 root        1   4    0 29904K 14724K pfesta 218:09  5.71% mib2d
 3160 root        1 108    0 23724K 17656K select 170:24  1.03% snmpd
 
Standard:
 
  PID USERNAME  THR PRI NICE   SIZE    RES STATE    TIME   WCPU COMMAND
 1089 root        2  44  -52 72268K 18960K select 179.1H 32.57% sfid
 1088 root        1   4    0 68296K 11884K kqread  55.7H  7.67% chassism
 1091 root        1   8    0 71420K 18776K nanslp  27.6H  3.03% pfem
38577 admin       1  97    0 32044K 23072K select   0:00  0.20% cli
38578 root        1 105    0 43720K  5008K select   0:00  0.13% mgd

I added in the Poller change and basically doubled or tripled the polling rates. 

Any ideas? Id love to continue working with Libre.

**Comment by laf** [comment]
I'm not sure I see much of an issue, we can't control the rate we poll individual devices at so if this is a unit with a poor cpu arch in it or really low resources then your kind of stuck (I've not come across anything LibreNMS can't poll or adds that much load it causes issues) or the snmp stack of the device is erm, poor, that is more likely and can only be fixed by the vendor.

Is this actually causing you issues?

What device is it?

**Comment by higante702** [comment]
It is a pair of Juniper EX4550 switch. When I get back into work on monday
I will try to isolate and identify what could be the culprit. Just seems
like SNMP traffic is doing more to the switch that I think it should be.

**Comment by patrickfish** [comment]
@higante702 what version of Junos?

**Comment by higante702** [comment]
@patrickfish - JUNOS 13.2X51-D35.3

I did open up a case with JTAC to find out what is going on. When LibreNMS
polls the switch (and nothing else is added), the CPU usage goes up about
20%, which normally wouldnt be bad but we are at 50% already.

I know this shouldnt have anything to do with your product, but I am open
to any suggestions that would help me implement it!

Thanks again for reading if you have :)

**Comment by oam7575** [comment]
@higante702 

In a past life I configured an old version of Observium to poll a network of Juniper SSG 140's, Juniper EX2200 switches and Extreme Network switches ( cannot remember the model ) along with regular devices.

The EX2200's all suffered from high CPU during polling the rest of the network was fine.

As this was only a test deployment the solution was to stop polling the EX2200's.

I would try and replicate the high CPU usage with other SNMP tools to confirm that the problem is not with LibreNMS ( or left over code from Observium ) and lean on JTAC for a fix.

**Comment by paulgear** [comment]
My EX2200C doesn't seem to suffer too badly: 
![screenshot from 2016-04-13 10-22-29](https://cloud.githubusercontent.com/assets/107222/14479435/cf43b966-0161-11e6-86e2-f6246680a422.png)

**Comment by oam7575** [comment]
@paulgear 
JunOS version?

Also according to this : http://www.juniper.net/us/en/local/pdf/datasheets/1000388-en.pdf
the EX2200C has 800Mhz ARM CPU
The EX4550 says 1.2Ghz : https://www.juniper.net/assets/fr/fr/local/pdf/datasheets/1000414-en.pdf
but doesn't give any further detail.

**Comment by paulgear** [comment]
I think that doc is wrong; when I first started playing with this switch, I found the CPU was a 1.2 GHz Marvell (see http://libertysys.com.au/blog/three-days-with-junos).  JunOS 12.3R3.4.  Keep in mind this is only a 12-port switch, so enumerating the ports should be less intensive than on larger models.

**Comment by higante702** [comment]
@Paul - thank you for all of your input! I have a ticket open and hopefully
I will get to work with them tomorrow. Mine spikes much more:

[image: Inline image 1]

So once I get some info, i will update the thread.

**Comment by Cheeze-It** [comment]
higante702, have you investigated why your sfid process is high?

I'd much rather point to that being investigated over the SNMP polling high CPU. Your sfid process shouldn't be that high unless there are other perpetuating problems.

**Comment by higante702** [comment]
@All,

I have had the JTAC meeting and here are the facts:

Between 3 different 4550 VC stacks and a 4300 VC stack - All 4550 VC stacks
shows a spike in CPU usage, specifically pfem.

Because JTAC could not find anything else that could have been the cause,
he is under the assumption that the heavy network load + the polling from
Libre is what is causing the problem.

Moving forward he suggested to limit how much Libre is polling. I removed
the device, and only had in the OS module.

The spike still occurred, even though the device is being polled for
minimal information.

I am going to monitor this device with a separate solution, but if anyone
has any ideas I am open.

If there are no updates or ideas, go ahead and close this request.

Thanks guys.

**Comment by Cheeze-It** [comment]
To me if JTAC said that, and you removed Libre polling and the spike still occurred then it's not Libre. Libre is probably causing for some slight loading, but you'd see said loading on the snmpd process as I believe that's what runs the agent. 

If you're seeing pfem and sfid I would immediately look at a layer 2 switching loop and/or lots of changes that require PFE re-programming at high rates. 

Lastly, one can spin up VMs of like Cacti, or Nagios, or something else to verify if they hit the snmpd as hard as Libre does. I would argue Libre can be intensive (as it polls for a lot of info), but snmp agents USUALLY don't use up that much power in most cases.

**Comment by higante702** [comment]
@Cheeze-It Thank you for your input. Management has decided to avoid taxing our core for the time being and I will revisit this at a later time.
