### ISSUE TITLE
Problem to recognize my Synology DS214Play with DSM6

### ISSUE THREAD

**Issue by jdoclot** [librenms/librenms#3314]
Hello,

Librenms don't recognize my synology and it recognize like a generic x86 linux server.

Is it possible to support that?

Thanks

**Comment by laf** [comment]
Please post output of:

./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -r -f -d -m os

**Comment by laf** [comment]
Please re-open this when you have the required output we need.
