### ISSUE TITLE
addhost.php exit values

### ISSUE THREAD

**Issue by tkteun** [librenms/librenms#3315]
Feature request:

I would like to see different return/exit values for addhost.php which I can use in my Ansible script.

At the moment it is quite difficult to see what the script has done since it always exits with 0.
I would like to receive 1 when the host could not be added, I'd prefer to see the reason outputted to the stderr interface.

An exemption to this might be when the host is already present in the database, which currently outputs on stdout:

> Already got host testhost\nAlready got host testhost\n\nLibreNMS 2015.master Add Host Tool\n\n    Usage (SNMPv1/2c): ./addhost.php [-g <poller group>] [-f] [-p <port assoc mode>] <\u001b[1;37mhostname\u001b[0m> [community] [v1|v2c] [port] [udp|udp6|tcp|tcp6]\n    Usage (SNMPv3)   :  Config Defaults : ./addhost.php [-g <poller group>] [-f] [-p <port assoc mode>] <\u001b[1;37mhostname\u001b[0m> any v3 [user] [port] [udp|udp6|tcp|tcp6]\n    No Auth, No Priv : ./addhost.php [-g <poller group>] [-f] [-p <port assoc mode>] <\u001b[1;37mhostname\u001b[0m> nanp v3 [user] [port] [udp|udp6|tcp|tcp6]\n       Auth, No Priv : ./addhost.php [-g <poller group>] [-f] [-p <port assoc mode>] <\u001b[1;37mhostname\u001b[0m> anp v3 <user> <password> [md5|sha] [port] [udp|udp6|tcp|tcp6]\n       Auth,    Priv : ./addhost.php [-g <poller group>] [-f] [-p <port assoc mode>] <\u001b[1;37mhostname\u001b[0m> ap v3 <user> <password> <enckey> [md5|sha] [aes|dsa] [port] [udp|udp6|tcp|tcp6]\n\n        -g <poller group> allows you to add a device to be pinned to a specific poller when using distributed polling. X can be any number associated with a poller group\n        -f forces the device to be added by skipping the icmp and snmp check against the host.\n\t-p <port assoc mode> allow you to set a port association mode for this device. By default ports are associated by 'ifIndex'.\n\t                     For Linux/Unix based devices 'ifName' or 'ifDescr' might be useful for a stable iface mapping.\n\t                     The default for this installation is 'ifIndex'\n\t                     Valid port assoc modes are: ifIndex, ifName, ifDescr, ifAlias\n\n    \u001b[0;31mRemember to run discovery for the host afterwards.\u001b[0m", "stdout_lines": ["Already got host centos.mon", "Already got host centos.mon", "", "LibreNMS 2015.master Add Host Tool", "", "    Usage (SNMPv1/2c): ./addhost.php [-g <poller group>] [-f] [-p <port assoc mode>] <\u001b[1;37mhostname\u001b[0m> [community] [v1|v2c] [port] [udp|udp6|tcp|tcp6]

**Comment by murrant** [comment]
We would be open to a patch for this.  I'm not exactly sure what your requirements are.  If you can be a little more specific, I can try to write it.

**Comment by tkteun** [comment]
Hi Murrant, 
Thanks for your response.
I've thought about it and think the next is reasonable:

**0** : Host added, updated or already exists
**1** : Host could not be added
**2** : Could not parse arguments.

**Comment by murrant** [comment]
0 for already exists doesn't make sense to me as that should be an error.
Updated isn't a possibility I think.
