### ISSUE TITLE
Cisco log with star causing incorrect syslog parsing

### ISSUE THREAD

**Issue by mkratz** [librenms/librenms#3316]
Relates to #2205 and #3099 

One further in parsing Cisco logs that I've noticed is when there's a star character preceding the %.

It causes the timezone to end up in the "program" field, and % and the rest of the output to end up in the "message" field.

e.g.
`2016-04-04 21:26:41	host	TZ	*%LWAPP-3-REPLAY_ERR: 1 wcm: Received replay error on slot 1, WLAN ID 1, count 1 from AP xxxx.xxxx.xxxx.xxxx`

the correct format is (this one has been parsed correctly)
`2016-04-04 20:10:19	host	%LINEPROTO-5-UPDOWN	Line protocol on Interface GigabitEthernet0/5, changed state to up`

Here's two logs directly from a device showing the actual difference in output:

```
Apr  4 20:57:20.720 TZ: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet1/0/41, changed state to up
Apr  4 21:26:41.778 TZ: *%LWAPP-3-REPLAY_ERR: 1 wcm:  Received replay error on slot 1, WLAN ID 1, count 1 from AP xxxx.xxxx.xxxx.xxxx

```

**Comment by mkruyswijk** [comment]
i found that the log with a * is actually caused by the fact that the syslog sender is not time synchronized. when we configured NTP correctly the * was gone

**Comment by murrant** [comment]
Can you uncomment  `#logfile($line);` in syslog.php and check for the line containing the * in logs/librenms.log and post it here?
(don't forget to comment that line again after you collect the info)

**Comment by mkratz** [comment]
@murrant I did that, but nothing is being added to logs/librenms.log

```
/opt/librenms/logs# tail librenms.log
discovery.php all 2016-02-07 18:20:45 - 1 devices discovered in 57.21 secs
discovery.php all 2016-02-07 18:39:18 - 4 devices discovered in 93.49 secs
```

```
/opt/librenms/logs# ls -la librenms.log
-rw-rw-r-- 1 root root 150 Feb  7 18:39 librenms.log
```

/opt/librenms/syslog.php:
```
$s = fopen('php://stdin','r');
while ($line = fgets($s)) {
# uncommented below for testing
    logfile($line);
    list($entry['host'],$entry['facility'],$entry['priority'], $entry['level'], $entry['tag'], $entry['timestamp'], $entry['msg'], $entry['program']) = explode("||", trim($line));
    process_syslog($entry, 1);
```

**Comment by murrant** [comment]
That's because your permissions for librenms.log are wrong and it cannot write to it.  Please change the permissions on the file `chown librenms:librenms /opt/librenms/logs/librenms.log`.  If that fails, you can temporarily allow global write for testing.

**Comment by mkratz** [comment]
Thanks for pointing that out, I've fixed that.

One of the bad logs occurred at 15:20 local time

`2016-04-06 15:20:35	sw1-1a.adl1	TZ	*%LWAPP-3-REPLAY_ERR: 1 wcm: Received replay error on slot 0, WLAN ID 2, count 1 from AP xxxx.xxxx.xxxx`

Here's the output of the log file across that period (doesn't seem to have logged anything):

```
/opt/librenms/discovery.php new 2016-04-06 15:20:01 - 0 devices discovered in 0.077 secs
/opt/librenms/poller.php 2 2016-04-06 15:20:06 - 1 devices polled in 3.564 secs
/opt/librenms/poller.php 10 2016-04-06 15:20:07 - 1 devices polled in 4.641 secs
/opt/librenms/poller.php 11 2016-04-06 15:20:11 - 1 devices polled in 8.575 secs
/opt/librenms/poller.php 9 2016-04-06 15:20:12 - 1 devices polled in 9.218 secs
/opt/librenms/poller.php 4 2016-04-06 15:20:13 - 1 devices polled in 11.05 secs
/opt/librenms/poller.php 5 2016-04-06 15:20:14 - 1 devices polled in 11.45 secs
/opt/librenms/poller.php 8 2016-04-06 15:20:14 - 1 devices polled in 11.95 secs
/opt/librenms/poller.php 6 2016-04-06 15:20:16 - 1 devices polled in 13.54 secs
/opt/librenms/poller.php 3 2016-04-06 15:20:18 - 1 devices polled in 15.58 secs
/opt/librenms/poller.php 7 2016-04-06 15:20:18 - 1 devices polled in 16.04 secs
/opt/librenms/discovery.php new 2016-04-06 15:25:02 - 0 devices discovered in 0.051 secs
/opt/librenms/poller.php 2 2016-04-06 15:25:07 - 1 devices polled in 4.094 secs
/opt/librenms/poller.php 9 2016-04-06 15:25:07 - 1 devices polled in 4.131 secs
/opt/librenms/poller.php 7 2016-04-06 15:25:11 - 1 devices polled in 7.936 secs
/opt/librenms/poller.php 8 2016-04-06 15:25:11 - 1 devices polled in 8.095 secs
/opt/librenms/poller.php 10 2016-04-06 15:25:13 - 1 devices polled in 9.754 secs
/opt/librenms/poller.php 4 2016-04-06 15:25:14 - 1 devices polled in 10.99 secs
/opt/librenms/poller.php 5 2016-04-06 15:25:14 - 1 devices polled in 11.44 secs
/opt/librenms/poller.php 11 2016-04-06 15:25:17 - 1 devices polled in 13.78 secs
/opt/librenms/poller.php 3 2016-04-06 15:25:18 - 1 devices polled in 14.79 secs
/opt/librenms/poller.php 6 2016-04-06 15:25:21 - 1 devices polled in 17.75 secs
```

**Comment by murrant** [comment]
What model of device is this?

**Comment by murrant** [comment]
Also, have you considered issueing `no service timestamps` on your devices?

**Comment by murrant** [comment]
I found this 
```
"*" symbol means time is not authoritative: the software clock is not in sync or has never been set.
```
So disabling timestamps as above (only in the message, you'll still log the time) or setting ntp properly will fix the issue.

**Comment by mkratz** [comment]
@murrant a Cisco 3650 switch that can act as a WLC for Cisco AP's.

The logs prefixed with a * don't seem to occur for everything. NTP is configured correctly.

The logging config used is:

```
service timestamps debug datetime msec
service timestamps log datetime msec localtime show-timezone
```
