### ISSUE TITLE
syslog showing "sequence" numbers instead of program

### ISSUE THREAD

**Issue by mkruyswijk** [librenms/librenms#3317]
having an issue with parsing syslog. in the program list, i only see sequence numbers. not the "lineproto-5-updown" choice:

see below for output of librenms.log:

s03-xxxx-xxxx||local7||notice||notice||bd||2016-04-04 15:18:43||Apr  4 13:18:42.670: LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/32, changed state to up||345735

**Comment by mkruyswijk** [comment]
![screenshot_040416_032226_pm](https://cloud.githubusercontent.com/assets/18033968/14249226/0d14bc08-fa79-11e5-977a-1e567c7e139a.jpg)

**Comment by murrant** [comment]
We actually don't do any processing on that line, since the syslog daemon is sending the program already.  '345735' is added by the syslog daemon. 

Post a snippet from your syslog config and I'll see if I can figure what the issue is. It could be sent from the device as well.

**Comment by mkruyswijk** [comment]
Hi Murrant,

hope this helps.
"@version: 3.3
@include "scl.conf"
@include "`scl-root`/system/tty10.conf"

# Syslog-ng configuration file, compatible with default Debian syslogd
# installation.

# First, set some global options.
options { chain_hostnames(off); flush_lines(0); use_dns(yes); use_fqdn(no);
          owner("root"); group("adm"); perm(0640); stats_freq(0);
          bad_hostname("^gconfd$");
};

source s_net {
        tcp(port(514) flags(syslog-protocol));
        udp(port(514) flags(syslog-protocol));
};

# LIBRENMS
destination d_librenms {
program("/opt/librenms/syslog.php" template ("$HOST||$FACILITY||$PRIORITY||$LEVEL||$TAG||$YEAR-$MONTH-$DAY $HOUR:$MIN:$SEC||$MSG||$PROGRAM\n") template-escape(yes));
};
rewrite r_rewrite_subst{
    subst("%", "", value("MESSAGE"), flags("global"));

};
log {
        source(s_net);
        source(s_src);
        rewrite(r_rewrite_subst);
        destination(d_librenms);
        destination(d_syslog);
};

**Comment by murrant** [comment]
What happens if you remove the rewrite?

Is there a reason you have that in there?

**Comment by mkruyswijk** [comment]
i inserted it due to my searches for a solution. thought it was related to on of the issue's earlier discribed. but it wasn't :(. i have another librenms installation, where we never changed the syslog-ng configuration. and that one shows the same behaviour. if we remove all the rewrites, it doesn't change the behaviour (it only puts back the "%").

**Comment by murrant** [comment]
Well, I added test with your input and it ran correctly...

What version of librenms are you running?  (you can see this on the about page or with `git rev-parse --short HEAD`)

**Comment by mkruyswijk** [comment]
hi Murrant: d0734d7

**Comment by murrant** [comment]
I think the problem is relating to the device not being matched. Which means we don't see it as an ios device, so the log entry is not processed at all.
Try with use_dns(no), otherwise make sure the hostname matches what is in librenms.

**Comment by mkruyswijk** [comment]
i change the DNS settings. but can it have something to do with date? it seems that we are observing this behaviour between 1st of april (30 march everything was still working) and 9th of april. as soon as it became 10th of april, everything started working again. (just changed the dns setting in syslog-ng this morning).

**Comment by murrant** [comment]
I tested with the exact line you posted from April 4th.  I don't think it was a date related issue.  Based on the output, it looks the line isn't processed at all.

**Comment by laf** [comment]
Please feel free to re-open this with more information.
