### ISSUE TITLE
SNMP timeout when adding PDU's

### ISSUE THREAD

**Issue by beeelze** [librenms/librenms#3318]
When I try to add my Powerbars to LibreNMS I continuously get SNMP timeouts (no replies on given community). This is weird because elsewhere on my site I successfully poll Inlet and Outlet information of my Powerbars and update this in my database. 

What could be the reason why LibreNMS is giving me SNMP timeouts while regular snmpwalk and snmpget PHP functions DO works?

**Comment by laf** [comment]
We only use snmp commands on the backend so no difference for us than there is you. We do have snmp timeouts you can change, see docs.librenms.org for more details.

**Comment by beeelze** [comment]
I don't think changing the timeout value will do anything. I was able to add all of my other devices to LibreNMS just fine. All SNMP settings of the powerbars are set correctly.

I guess I'll have to investigate further. Thanks anyway!

**Comment by Lonecrowe** [comment]
There was a small update today for the APC devices - update your install and see if it still does this

**Comment by laf** [comment]
You're experiencing an snmp timeout so adjusting the snmp timeout could well help you out.
