### ISSUE TITLE
change rrd legend in multiport graphs

### ISSUE THREAD

**Issue by momorientes** [librenms/librenms#3319]
It would be nice to change the legend text to display the interface description instead of `Te0/0/0` etc. when plotting multiport graphs.
![](https://cloud.githubusercontent.com/assets/510293/14279910/f34c83f2-fb2f-11e5-8b00-3439dc0bca16.png)

Also it would be a nice feature to show the added min/avg/max values for all ports in the legend.

**Comment by laf** [comment]
The problem with this is interface descriptions can be long, they can also be generic/duplicated on some devices.

Whilst we could add a config option to allow this I don't see a reason personally.

**Comment by f0rkz** [comment]
Honestly, the way it shows now is rather ambiguous. I would enjoy seeing the port description in the legend or what it is now. A configuration setting would be nice.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-change-rrd-legend-in-multiport-graphs/819
