### ISSUE TITLE
Alerting : Use HTML

### ISSUE THREAD

**Issue by mail3dexter** [librenms/librenms#3325]
Enabling HTML formats for email screws up the format because I can see that its just changing Content-Type in the email however the email body doesnt contains the tags and other stuffs of HTML.

**Comment by f0o** [comment]
That needs to be done in your template

On 7 April 2016 14:09:54 CEST, Mayur Patel <notifications@github.com> wrote:
>Enabling HTML formats for email screws up the format because I can see
>that its just changing Content-Type in the email however the email body
>doesnt contains the tags and other stuffs of HTML.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/3325

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
