### ISSUE TITLE
Expandable health submenus on device overview page

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#3326]
![screen shot 2016-04-07 at 18 03 28](https://cloud.githubusercontent.com/assets/6378934/14357939/16831be4-fceb-11e5-8fc6-57481c20ae7d.png)

Instead of displaying all like this.

**Comment by Lonecrowe** [comment]
Me likes

**Comment by Rosiak** [comment]
Would be nice to have a hierarchy, much like we already have with sensors.

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #167](https://github.com/librenms/librenmsv2/issues/167) via [**ZenHub**](https://www.zenhub.com/)
