### ISSUE TITLE
[InfluxDB] Data is added to influxDB as "Strings"

### ISSUE THREAD

**Issue by LaurentDumont** [librenms/librenms#3328]
Hi,

It seems that data from LibreNMS is entered as String in the InfluxDB database. That means that you cannot use any of the aggregation/data manipulation functions in InfluxDB. Things like max/min/derivative require a numerical format. Those are awesome tools when using Grafana to create graphs.

I am using the latest LibreNMS git and the latest InfluxDB release. I have tried debugging the actual data insertion with a good old tcpdump but I cant see the data payload in Wireshark because of HTTPGuzzler? I've also tried uncommenting the `d_echo` in `influxdb.inc.php` but I failed to find where the output went...

If I try to insert data manually to test, it does tell me that the current measurement is stored as Strings 

`ERR: {"error":"field type conflict: input field \"INERRORS\" on measurement \"ports\" is type float64, already exists as type string"}`

Anything else I can do to provide for information?

![capture](https://cloud.githubusercontent.com/assets/8936473/14374585/7ed00e48-fd25-11e5-93fe-1943a8ab020d.PNG)

**Comment by geordish** [comment]
I've got a PR open to correct this: #3320.  I fear there are a lot more issues lurking that I don't have devices to test with.

Unfortunately, the only way I've found to correct the database is to fix the code, then drop it losing all past stats.

It may be possible to rename the database, then write a script to pull values out of the old database, convert it to the correct type, and insert it into a new database.

**Comment by geordish** [comment]
As for the debug statements, they will be displayed when you run poller.php with -d

**Comment by LaurentDumont** [comment]
Ah, I see. Glad to see I wasn't totally crazy! Thanks for all your work! I'll try your PR asap and report back. I'll also look for any data type I can still see as Strings.

Awesome work, thanks a lot! I'll leave the issue open just in case

**Comment by LaurentDumont** [comment]
@geordish I've been running your changes for a bit and I've been running into issues where the poller fails from time to time. I'll try to pull your branch to see if it's something that failed when I copied things over.

**Comment by laf** [comment]
Should be fixed now.
