### ISSUE TITLE
Add offline device

### ISSUE THREAD

**Issue by wiad** [librenms/librenms#3329]
There doesnt seem to be any way (?) to add a device that is currently offline. We have some lab equipment that is offline most of the time, but I still want data from them in LibreNMS when they are online. It seems a bit silly to have to turn them on just to be able to add them to LibreNMS. 

Maybe there could be an option to 'add the device anyway' if LibreNMS can't contact it?

**Comment by LaurentDumont** [comment]
iirc there is a -f flag when adding a host from the command line

**Comment by wiad** [comment]
Ah, missed that - thats quite good enough for me!
