### ISSUE TITLE
I do not see the version LibreNMS.

### ISSUE THREAD

**Issue by MilanVolf** [librenms/librenms#3330]
Can you please advise why I do not see about the version LibreNMS?

See screenshot: [about](http://milan.cege.cz/librenms/about.jpg)

Thank you.

**Comment by murrant** [comment]
Do you have `git` installed?  Did you install from the [docs](http://docs.librenms.org) or from another method?

**Comment by MilanVolf** [comment]
Thank you for advice.

I have 2 servers:
1. WEB
2. APL - which runs cron scripts

WEB server is not installed git.

Resolved.
