### ISSUE TITLE
Cisco Small Business Switch Port Stats incorrect

### ISSUE THREAD

**Issue by air101** [librenms/librenms#3331]
Hello LibreNMS Team,

in our environment we have several cisco small business switches. I think/know there is a display error some 1Gbit Ports there. We have peeks of 15GBIT for 1-2 minutes on several ports. If I check in cacti these peeks are not there. Except that everything is normal. How to solve that issue?

Thanks in advance!

**Comment by laf** [comment]
http://docs.librenms.org/Extensions/RRDTune/
