### ISSUE TITLE
Alerts Not Clearing?

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#3335]
Hi,

A recent issue I have (and a warning up front, this is on PHP7.0, so that may be the real issue!) ... but I'm seeing that alerts are accumulating - never clearing. Have others seen this (just recently)? Also, I keep getting a recurring alert (email), even though the Alert interval is set to zero ... but this may just be because of the non-clearing.

Thanks!

**Comment by f0o** [comment]
Hi,

The repeating email is likely because of the non-clearing.

However, I'm also running php7 but haven't seen this issue.. Do you by chances have sql-strict mode or similar?



On 10 April 2016 18:01:21 CEST, arrmo <notifications@github.com> wrote:
>Hi,
>
>A recent issue I have (and a warning up front, this is on PHP7.0, so
>that may be the real issue!) ... but I'm seeing that alerts are
>accumulating - never clearing. Have others seen this (just recently)?
>Also, I keep getting a recurring alert (email), even though the Alert
>interval is set to zero ... but this may just be because of the
>non-clearing.
>
>Thanks!
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/3335

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by arrmo** [comment]
OK, being an SQL idiot (me that is!) ... is there an easy way to check? Thanks!

**Comment by f0o** [comment]
I think the validate.php should check for that.. 

Sadly am on my phone currently so a bit bad for googling..

**Comment by arrmo** [comment]
NP, that does help quite a bit - digging here, give me a minute .. :)

**Comment by arrmo** [comment]
OK, during PHP7 upgrade, some items didn't get auto-updated ... validate pointed out that php-curl was missing. Fixed, and now validate.php only warns about,

1) [FAIL]    We have found some files that are owned by a different user than librenms, this will stop you updating automatically and / or rrd files being updated causing graphs to fail:

/opt/librenms/includes/alerts/transport.mail.php
/opt/librenms/includes/discovery/os/deliberant.inc.php
/opt/librenms/includes/polling/os/deliberant.inc.php
/opt/librenms/logs
/opt/librenms/logs/librenms.log
/opt/librenms/logs/daily.log
/opt/librenms/sql-schema/108.sql
/opt/librenms/html/images/os/deliberant.png
/opt/librenms/mibs/DELIBERANT-MIB
/opt/librenms/mibs/DLB-802DOT11-EXT-MIB
/opt/librenms/mibs/DLB-GENERIC-MIB
/opt/librenms/mibs/DLB-RADIO3-DRV-MIB
/opt/librenms/mibs/DLB-ATHDRV-STATS-MIB
(REMOVED items inside .git from this list)

2) [WARN]    You have MySQL STRICT_TRANS_TABLES enabled, it is advisable to disable this until full support has been added: https://dev.mysql.com/doc/refman/5.0/en/sql-mode.html

Thoughts?

Thanks!

**Comment by f0o** [comment]
Reown those files and also make sure the .git directory is being reowned.

Regarding 2) go ahead and disable it :)

**Comment by arrmo** [comment]
Reowned the files - no changes. Trying to figure out how to do #2 - working on it!

**Comment by arrmo** [comment]
OK, got it working - disabling STRICT_TRANS_TABLES. Thanks!

But, I did this by setting (inside MySQL),
SET GLOBAL sql_mode = 'modes';

I can't seem to get it working from the config file (my.cnf) - has anyone had any luck with that? I'm sure it's a syntax thing, but no joy getting it right ... :(.

Thanks again!

**Comment by f0o** [comment]
Just adding `sql_mode=''` to the mysql conf under the `[server]` tag does not work?

**Comment by arrmo** [comment]
That works, thanks!

The searching I had done seemed to say to add it to the [mysqld] section, but that failed. Thanks again!
