### ISSUE TITLE
Updating to latest codebase - FAIL

### ISSUE THREAD

**Issue by drukpa** [librenms/librenms#3338]
I have been trying to update librenms, and I see it failed to update to the latest codebase. If anyone could help me.
# /opt/librenms/daily.sh
Updating to latest codebase                       FAIL
Updating SQL-Schema                               OK
Updating submodules                                 OK
Cleaning up DB                                          OK
Fetching notifications                                 OK

**Comment by laf** [comment]
Look at logs/daily.log

**Comment by igorme** [comment]
hi 
I see it failed to update to the latest codebase.

root@mon:/opt/librenms# ./daily.sh
Updating to latest codebase                        FAIL
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK


`Updating to latest codebase
error: Your local changes to the following files would be overwritten by merge:
        AUTHORS.md
        alerts.php
        daily.php
        daily.sh
        doc/API/API-Docs.md
        doc/Extensions/Agent-Setup.md
        doc/Extensions/Alerting.md
        doc/Extensions/Billing-Module.md
        doc/Extensions/Globe-Frontpage.md
        doc/Extensions/InfluxDB.md
        doc/General/Updating.md
        html/api_v0.php
        html/images/os/cambium.png
        html/includes/api_functions.inc.php
        html/includes/authentication/ldap-authorization.inc.php
        html/includes/authentication/ldap.inc.php
        html/includes/collectd/definitions.php
        html/includes/modal/new_alert_rule.inc.php
        html/includes/modal/new_bill.inc.php
        html/includes/print-menubar.php
        html/includes/table/alerts.inc.php
        html/pages/bill/addoreditbill.inc.php
        html/pages/bill/edit.inc.php
        html/pages/bills.inc.php
        html/pages/device/health.inc.php
        html/pages/device/overview.inc.php
        html/pages/device/overview/toner.inc.php
        html/pages/health.inc.php
        html/pages/settings/alerting.inc.php
        includes/alerts/transport.api.php
        includes/alerts/transport.hipchat.php
        includes/alerts/transport.mail.php
        includes/alerts/transport.pagerduty.php
        includes/alerts/transport.pushbullet.php
        includes/alerts/transport.pushover.php
        includes/alerts/transport.slack.php
        includes/billing.php
        includes/defaults.inc.php
        includes/definitions.inc.php
        includes/discovery/functions.inc.php
        includes/discovery/os.inc.php
        includes/discovery/os/canopy.inc.php
        includes/discovery/os/linux.inc.php
        includes/discovery/sensors.inc.php
Please, commit your changes or stash them before you can merge.
error: The following untracked working tree files would be overwritten by merge:
        doc/Installation/Installation-Nginx-(Debian-Ubuntu).md
        html/images/os/canon.png
        html/images/os/cumulus.png
        html/images/os/deliberant.png
        html/images/os/develop.png
        html/includes/graphs/device/cambium_250_dataRate.inc.php
        html/includes/graphs/device/cambium_250_modulationMode.inc.php
        html/includes/graphs/device/cambium_250_receivePower.inc.php
        html/includes/graphs/device/cambium_250_ssr.inc.php
        html/includes/graphs/device/cambium_250_transmitPower.inc.php
        html/includes/graphs/device/cambium_650_dataRate.inc.php
        html/includes/graphs/device/cambium_650_gps.inc.php
        html/includes/graphs/device/cambium_650_modulationMode.inc.php
        html/includes/graphs/device/cambium_650_rawReceivePower.inc.php
        html/includes/graphs/device/cambium_650_ssr.inc.php
        html/includes/graphs/device/cambium_650_transmitPower.inc.php
        html/includes/graphs/device/cambium_epmp_RFStatus.inc.php
        html/includes/graphs/device/cambium_epmp_access.inc.php
        html/includes/graphs/device/cambium_epmp_freq.inc.php
        html/includes/graphs/device/cambium_epmp_gps.inc.php
        html/includes/graphs/device/cambium_epmp_gpsSync.inc.php
        html/includes/graphs/device/cambium_epmp_modulation.inc.php
        html/includes/graphs/device/cambium_epmp_registeredSM.inc.php
        html/includes/graphs/device/canopy_generic_450_linkRadioDbm.inc.php
        html/includes/graphs/device/canopy_generic_450_masterSSR.inc.php
        html/includes/graphs/device/canopy_generic_450_powerlevel.inc.php
        html/includes/graphs/device/canopy_generic_450_ptpSNR.inc.php
        html/includes/graphs/device/canopy_generic_450_slaveHV.inc.php
        html/includes/graphs/device/canopy_generic_450_slaveSNR.inc.php
        html/includes/graphs/device/canopy_generic_450_slaveSSR.inc.php
        html/includes/graphs/device/canopy_generic_crcErrors.inc.php
        html/includes/graphs/device/canopy_generic_errorCount.inc.php
        html/includes/graphs/device/canopy_generic_freq.inc.php
        html/includes/graphs/device/canopy_generic_gpsStats.inc.php
        html/includes/graphs/device/canopy_generic_jitter.inc.php
        html/includes/graphs/device/canopy_generic_radioDbm.inc.php
        html/includes/graphs/device/canopy_generic_regCount.inc.php
        html/includes/graphs/device/canopy_generic_rssi.inc.php
        html/includes/graphs/device/canopy_generic_signalHV.inc.php
        html/includes/graphs/device/canopy_generic_snrHV.inc.php
        html/includes/graphs/device/canopy_generic_whispGPSStats.inc.php
        html/includes/graphs/device/signal.inc.php
        html/includes/graphs/sensor/signal.inc.php
        html/includes/table/bills.inc.php
        html/pages/device/health/signal.inc.php
        html/pages/device/overview/sensors/signal.inc.php
        html/pages/health/signal.inc.php
        includes/alerts/transport.canopsis.php
        includes/discovery/os/cambium.inc.php
        includes/discovery/os/deliberant.inc.php
        includes/discovery/os/developprinter.inc.php
        includes/discovery/os/juniperex2500os.inc.php
        includes/discovery/processors/cambium.inc.php
Please move or remove them before you can merge.
Aborting
Returned: 1
Updating SQL-Schema

Returned: 0
Updating submodules

Returned: 0
Cleaning up DB
Eventlog cleared for entries over 30 days
Performance poller times cleared for entries over 30 days
Device performance times cleared for entries over 7 days
Returned: 0
Fetching notifications
[ Sat, 07 May 2016 12:58:01 +0300 ] http://www.librenms.org/notifications.rss (4                                                                                                                                                             )
[ Sat, 07 May 2016 12:58:02 +0300 ] misc/notifications.rss (6)
[ Sat, 07 May 2016 12:58:02 +0300 ] Updating DB  Done
Returned: 0
`

**Comment by f0o** [comment]
Seems like you changed those files..

You can use git stash to get to the original state and then rerun the daily.sh

On 7 May 2016 12:07:16 CEST, igorme <notifications@github.com> wrote:
>hi 
>I see it failed to update to the latest codebase.
>
>root@mon:/opt/librenms# ./daily.sh
>Updating to latest codebase                        FAIL
>Updating SQL-Schema                                OK
>Updating submodules                                OK
>Cleaning up DB                                     OK
>Fetching notifications                             OK
>
>
>`Updating to latest codebase
>error: Your local changes to the following files would be overwritten
>by merge:
>        AUTHORS.md
>        alerts.php
>        daily.php
>        daily.sh
>        doc/API/API-Docs.md
>        doc/Extensions/Agent-Setup.md
>        doc/Extensions/Alerting.md
>        doc/Extensions/Billing-Module.md
>        doc/Extensions/Globe-Frontpage.md
>        doc/Extensions/InfluxDB.md
>        doc/General/Updating.md
>        html/api_v0.php
>        html/images/os/cambium.png
>        html/includes/api_functions.inc.php
>        html/includes/authentication/ldap-authorization.inc.php
>        html/includes/authentication/ldap.inc.php
>        html/includes/collectd/definitions.php
>        html/includes/modal/new_alert_rule.inc.php
>        html/includes/modal/new_bill.inc.php
>        html/includes/print-menubar.php
>        html/includes/table/alerts.inc.php
>        html/pages/bill/addoreditbill.inc.php
>        html/pages/bill/edit.inc.php
>        html/pages/bills.inc.php
>        html/pages/device/health.inc.php
>        html/pages/device/overview.inc.php
>        html/pages/device/overview/toner.inc.php
>        html/pages/health.inc.php
>        html/pages/settings/alerting.inc.php
>        includes/alerts/transport.api.php
>        includes/alerts/transport.hipchat.php
>        includes/alerts/transport.mail.php
>        includes/alerts/transport.pagerduty.php
>        includes/alerts/transport.pushbullet.php
>        includes/alerts/transport.pushover.php
>        includes/alerts/transport.slack.php
>        includes/billing.php
>        includes/defaults.inc.php
>        includes/definitions.inc.php
>        includes/discovery/functions.inc.php
>        includes/discovery/os.inc.php
>        includes/discovery/os/canopy.inc.php
>        includes/discovery/os/linux.inc.php
>        includes/discovery/sensors.inc.php
>Please, commit your changes or stash them before you can merge.
>error: The following untracked working tree files would be overwritten
>by merge:
>        doc/Installation/Installation-Nginx-(Debian-Ubuntu).md
>        html/images/os/canon.png
>        html/images/os/cumulus.png
>        html/images/os/deliberant.png
>        html/images/os/develop.png
>        html/includes/graphs/device/cambium_250_dataRate.inc.php
>        html/includes/graphs/device/cambium_250_modulationMode.inc.php
>        html/includes/graphs/device/cambium_250_receivePower.inc.php
>        html/includes/graphs/device/cambium_250_ssr.inc.php
>        html/includes/graphs/device/cambium_250_transmitPower.inc.php
>        html/includes/graphs/device/cambium_650_dataRate.inc.php
>        html/includes/graphs/device/cambium_650_gps.inc.php
>        html/includes/graphs/device/cambium_650_modulationMode.inc.php
>        html/includes/graphs/device/cambium_650_rawReceivePower.inc.php
>        html/includes/graphs/device/cambium_650_ssr.inc.php
>        html/includes/graphs/device/cambium_650_transmitPower.inc.php
>        html/includes/graphs/device/cambium_epmp_RFStatus.inc.php
>        html/includes/graphs/device/cambium_epmp_access.inc.php
>        html/includes/graphs/device/cambium_epmp_freq.inc.php
>        html/includes/graphs/device/cambium_epmp_gps.inc.php
>        html/includes/graphs/device/cambium_epmp_gpsSync.inc.php
>        html/includes/graphs/device/cambium_epmp_modulation.inc.php
>        html/includes/graphs/device/cambium_epmp_registeredSM.inc.php
>    html/includes/graphs/device/canopy_generic_450_linkRadioDbm.inc.php
>       html/includes/graphs/device/canopy_generic_450_masterSSR.inc.php
>      html/includes/graphs/device/canopy_generic_450_powerlevel.inc.php
>        html/includes/graphs/device/canopy_generic_450_ptpSNR.inc.php
>        html/includes/graphs/device/canopy_generic_450_slaveHV.inc.php
>        html/includes/graphs/device/canopy_generic_450_slaveSNR.inc.php
>        html/includes/graphs/device/canopy_generic_450_slaveSSR.inc.php
>        html/includes/graphs/device/canopy_generic_crcErrors.inc.php
>        html/includes/graphs/device/canopy_generic_errorCount.inc.php
>        html/includes/graphs/device/canopy_generic_freq.inc.php
>        html/includes/graphs/device/canopy_generic_gpsStats.inc.php
>        html/includes/graphs/device/canopy_generic_jitter.inc.php
>        html/includes/graphs/device/canopy_generic_radioDbm.inc.php
>        html/includes/graphs/device/canopy_generic_regCount.inc.php
>        html/includes/graphs/device/canopy_generic_rssi.inc.php
>        html/includes/graphs/device/canopy_generic_signalHV.inc.php
>        html/includes/graphs/device/canopy_generic_snrHV.inc.php
>       html/includes/graphs/device/canopy_generic_whispGPSStats.inc.php
>        html/includes/graphs/device/signal.inc.php
>        html/includes/graphs/sensor/signal.inc.php
>        html/includes/table/bills.inc.php
>        html/pages/device/health/signal.inc.php
>        html/pages/device/overview/sensors/signal.inc.php
>        html/pages/health/signal.inc.php
>        includes/alerts/transport.canopsis.php
>        includes/discovery/os/cambium.inc.php
>        includes/discovery/os/deliberant.inc.php
>        includes/discovery/os/developprinter.inc.php
>        includes/discovery/os/juniperex2500os.inc.php
>        includes/discovery/processors/cambium.inc.php
>Please move or remove them before you can merge.
>Aborting
>Returned: 1
>Updating SQL-Schema
>
>Returned: 0
>Updating submodules
>
>Returned: 0
>Cleaning up DB
>Eventlog cleared for entries over 30 days
>Performance poller times cleared for entries over 30 days
>Device performance times cleared for entries over 7 days
>Returned: 0
>Fetching notifications
>[ Sat, 07 May 2016 12:58:01 +0300 ]
>http://www.librenms.org/notifications.rss (4                           
>                                                                      )
>[ Sat, 07 May 2016 12:58:02 +0300 ] misc/notifications.rss (6)
>[ Sat, 07 May 2016 12:58:02 +0300 ] Updating DB  Done
>Returned: 0
>`
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/3338#issuecomment-217626018

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by igorme** [comment]
only this is left after git stash running

root@mon:/opt/librenms# git stash
Saved working directory and index state WIP on master: 2e802d8 Merge pull request #3215 from barhom/agreement
HEAD is now at 2e802d8 Merge pull request #3215 from barhom/agreement




`Updating to latest codebase
error: The following untracked working tree files would be overwritten by merge:
        doc/Installation/Installation-Nginx-(Debian-Ubuntu).md
        html/images/os/canon.png
        html/images/os/cumulus.png
        html/images/os/deliberant.png
        html/images/os/develop.png
        html/includes/graphs/device/cambium_250_dataRate.inc.php
        html/includes/graphs/device/cambium_250_modulationMode.inc.php
        html/includes/graphs/device/cambium_250_receivePower.inc.php
        html/includes/graphs/device/cambium_250_ssr.inc.php
        html/includes/graphs/device/cambium_250_transmitPower.inc.php
        html/includes/graphs/device/cambium_650_dataRate.inc.php
        html/includes/graphs/device/cambium_650_gps.inc.php
        html/includes/graphs/device/cambium_650_modulationMode.inc.php
        html/includes/graphs/device/cambium_650_rawReceivePower.inc.php
        html/includes/graphs/device/cambium_650_ssr.inc.php
        html/includes/graphs/device/cambium_650_transmitPower.inc.php
        html/includes/graphs/device/cambium_epmp_RFStatus.inc.php
        html/includes/graphs/device/cambium_epmp_access.inc.php
        html/includes/graphs/device/cambium_epmp_freq.inc.php
        html/includes/graphs/device/cambium_epmp_gps.inc.php
        html/includes/graphs/device/cambium_epmp_gpsSync.inc.php
        html/includes/graphs/device/cambium_epmp_modulation.inc.php
        html/includes/graphs/device/cambium_epmp_registeredSM.inc.php
        html/includes/graphs/device/canopy_generic_450_linkRadioDbm.inc.php
        html/includes/graphs/device/canopy_generic_450_masterSSR.inc.php
        html/includes/graphs/device/canopy_generic_450_powerlevel.inc.php
        html/includes/graphs/device/canopy_generic_450_ptpSNR.inc.php
        html/includes/graphs/device/canopy_generic_450_slaveHV.inc.php
        html/includes/graphs/device/canopy_generic_450_slaveSNR.inc.php
        html/includes/graphs/device/canopy_generic_450_slaveSSR.inc.php
        html/includes/graphs/device/canopy_generic_crcErrors.inc.php
        html/includes/graphs/device/canopy_generic_errorCount.inc.php
        html/includes/graphs/device/canopy_generic_freq.inc.php
        html/includes/graphs/device/canopy_generic_gpsStats.inc.php
        html/includes/graphs/device/canopy_generic_jitter.inc.php
        html/includes/graphs/device/canopy_generic_radioDbm.inc.php
        html/includes/graphs/device/canopy_generic_regCount.inc.php
        html/includes/graphs/device/canopy_generic_rssi.inc.php
        html/includes/graphs/device/canopy_generic_signalHV.inc.php
        html/includes/graphs/device/canopy_generic_snrHV.inc.php
        html/includes/graphs/device/canopy_generic_whispGPSStats.inc.php
        html/includes/graphs/device/signal.inc.php
        html/includes/graphs/sensor/signal.inc.php
        html/includes/table/bills.inc.php
        html/pages/device/health/signal.inc.php
        html/pages/device/overview/sensors/signal.inc.php
        html/pages/health/signal.inc.php
        includes/alerts/transport.canopsis.php
        includes/discovery/os/cambium.inc.php
        includes/discovery/os/deliberant.inc.php
        includes/discovery/os/developprinter.inc.php
        includes/discovery/os/juniperex2500os.inc.php
        includes/discovery/processors/cambium.inc.php
Please move or remove them before you can merge.
`

**Comment by f0o** [comment]
Well at least we got now a list of files you added manually. Let's get rid of them with:

> git add .
> git checkout -b pre-update
> git commit -m cleanup
> git checkout master
> ./daily.sh

That should move all the files to a different branch and save them in a commit. Then switch back to the hopefully clean master and retry update.

Out of interest, any idea why you got so many new files that are in upstream but not at your version? Did you manually copy them over or applied a patch or ..?

**Comment by f0o** [comment]
Repasting my mail as GH swallowed the cmds:

Well at least we got now a list of files you added manually. Let's get rid of them with:

> git add .
> git checkout -b pre-update
> git commit -m cleanup
> git checkout master
> ./daily.sh

That should move all the files to a different branch and save them in a commit. Then switch back to the hopefully clean master and retry update.

Out of interest, any idea why you got so many new files that are in upstream but not at your version? Did you manually copy them over or applied a patch or ..?

**Comment by dragon2611** [comment]
@f0o I get this quite frequently yet I know I'm not editing the files.
Something either causes the files to change or causes GIT to think they have.
