### ISSUE TITLE
Activate Macros

### ISSUE THREAD

**Issue by Fran-libreNMS** [librenms/librenms#3344]
Hi all, 

I'm tring to set one alert rule with macros, but it's not working. I'm using a default macro, then i haven`t to add it in the config.php.  The rule is the following:

%ports.ifAlias = " XXXXXXXX " && %ports.ifDescr = " FastEthernet7/9" &&      %macros.port_usage_perc >= "3"  

It seems as if the macro were not activated.

However , the Alerts rules with MIB working properly. For example:

%ports.ifAlias = "XXXXXXXX" && %ports.ifAdminStatus = "up"

What could be the problem?

Do I have to add any sentence somewhere?

Does the alert is poorly defined ?

Thanks in advance,

**Comment by paulgear** [comment]
It looks like you've got a space before "FastEthernet" at the start of your port name, which likely won't match.

**Comment by Fran-libreNMS** [comment]
Firtsly, thanks for the reponse.

In the real rule there isn't space.

**Comment by Fran-libreNMS** [comment]
Hi Paul,

Is this a correct statement of the rule? The rule doesn't work.

Could you tell me how I can do it?

Thanks,

**Comment by laf** [comment]
I'm not sure you can use / as it is a maths operator, that used to be the case but not sure if it was fixed @f0o?

**Comment by f0o** [comment]
It should've been fixed.

However make sure you add spacing between the numbers/fields and the math-operators. I've experienced mysql being sometimes bitchy when it's all squashed together..

**Comment by laf** [comment]
@Fran-libreNMS please make sure your install is upto date.

**Comment by paulgear** [comment]
Looks reasonable to me; @librenms/reviewers - anyone else got anything to add?

**Comment by paulgear** [comment]
Grrr - looks like I was working on an out-of-date view of this issue; deleting this & last comment.

**Comment by laf** [comment]
Please feel free to re-open this if you have further questions.
