### ISSUE TITLE
Fuji Xerox Docuprint

### ISSUE THREAD

**Issue by oam7575** [librenms/librenms#3347]
Hello,

I am coming over from Observium to LibreNMS. During testing I found our low end Fuji Xerox Docuprint devices were being detected as generic and not displaying toner status correctly.

Adjusting /opt/librenms/includes/discovery/os/xerox.inc.php as follows

<?php

if (!$os) {
    if (strstr($sysDescr, 'Xerox Phaser')) {
        $os = 'xerox';
    }
    if (strstr($sysDescr, 'Xerox WorkCentre')) {
        $os = 'xerox';
    }
   **_ if (strstr($sysDescr, 'FUJI XEROX DocuPrint')) {
        $os = 'xerox';
    }_**
}

Appears to allow LibreNMS to detect the device as a printer and display toner status correctly.
No other adjustments were made.

I have attached a copy of the snmpwalk for one of the devices for reference.

[cp215w_snmp_walk.txt](https://github.com/librenms/librenms/files/214280/cp215w_snmp_walk.txt)

**Comment by laf** [comment]
Can you post the output of:

./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -d -r -f -m os

**Comment by oam7575** [comment]
Hi laf,

I ran the commands and redirected to txt file.
files are attached.

[cp215w_poller_os.txt](https://github.com/librenms/librenms/files/216170/cp215w_poller_os.txt)
[cp215w_discovery_os.txt](https://github.com/librenms/librenms/files/216169/cp215w_discovery_os.txt)
