### ISSUE TITLE
dbm sensor support on Cisco ASR9000 platform

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#3351]
Hi !

Currently on ASR9000 i cannot see sensors dbm value for this cisco platform !

It seems that it is not implementet for this plattform ?!

ftp://ftp.cisco.com/pub/mibs/v2/CISCO-ENTITY-SENSOR-MIB.my

Cisco IOS XR Software, Version 5.3.3

kind regards

kristoferus75

**Comment by Rosiak** [comment]
Can you provide some data?
