### ISSUE TITLE
MAP between 2x ASR9k with tengig links 

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#3353]
Hi !

I use two ASR900 Routers and between this Routers i have two tengig links !

If i use show cdp neighbor -> I can see the routers on both Tengig Interfaces .

But in the librenms map i see only one link and only one interface 

Its important to see two links and two interfaces to have an overview and quick view of the interface utilzation !

Both Interfaces are configured with the same commands ! 

kind regards

kristoferus75

**Comment by laf** [comment]
If you run:

```mysql
select * from links where local_device_id=X OR remote_device_id=X;
```

Replace X with the device ID.

Please post the output.

**Comment by kristoferus75** [comment]
Hi !

You can see that this device have two links but only one link i see in the map ! 

TenGigE0/1/1/1


Database changed
MariaDB [librenms]> select * from links where local_device_id=105 OR remote_device_id=41;
+-----+---------------+-----------------+----------------+--------+----------+-------------------------------+------------------+-------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------+
| id  | local_port_id | local_device_id | remote_port_id | active | protocol | remote_hostname               | remote_device_id | remote_port             | remote_platform       | remote_version                                                                                                            |
+-----+---------------+-----------------+----------------+--------+----------+-------------------------------+------------------+-------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------+
| 191 |          2159 |              39 |           2385 |      1 | cdp      | inxrou01.kabelplus.at         |               41 | TenGigE0/2/0/0          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 193 |          2225 |              39 |           2388 |      1 | cdp      | inxrou01.kabelplus.at         |               41 | TenGigE0/2/0/3          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 492 |         16802 |             105 |           NULL |      1 | cdp      | ME36X-MAE-KTZ-01.kabelplus.at |                0 | TenGigabitEthernet0/1   | cisco ME-3600X-24FS-M | Cisco IOS Software, ME360x Software (ME360x-UNIVERSALK9-M), Version 15.3(3)S5, RELEASE SOFTWARE (fc1)                     |
| 493 |         16803 |             105 |          17147 |      1 | cdp      | ME36X-Manzb-02.kabelplus.at   |               81 | TenGigabitEthernet0/2   | cisco ME-3600X-24CX-M | Cisco IOS Software, ME360x_t Software (ME360x_t-UNIVERSALK9-M), Version 15.3(3)S5, RELEASE SOFTWARE (fc1)                 |
| 494 |         16806 |             105 |           2343 |      1 | cdp      | inxrou01.kabelplus.at         |               41 | TenGigE0/1/1/1          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 495 |         16809 |             105 |          13589 |      1 | cdp      | sw-ggc01.kabelplus.at         |               45 | TenGigabitEthernet2/0/1 | cisco WS-C3750E-24TD  | Cisco IOS Software, C3750E Software (C3750E-UNIVERSALK9-M), Version 15.0(2)SE7, RELEASE SOFTWARE (fc1)                    |
| 496 |         16813 |             105 |           2153 |      1 | cdp      | Upstream-RO-TZE               |               39 | TenGigE0/0/1/0          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 497 |         16815 |             105 |          17474 |      1 | cdp      | ASR9K-MAE-SRV-01.kabsi.at     |               90 | TenGigE0/1/0/3          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 498 |         16817 |             105 |          15763 |      1 | cdp      | ME34-MAE-KTZ-01.kabelplus.at  |               70 | GigabitEthernet0/1      | cisco ME-3400-24FS-A  | Cisco IOS Software, ME340x Software (ME340x-METROIPACCESSK9-M), Version 12.2(58)SE2, RELEASE SOFTWARE (fc1)               |
| 499 |         16818 |             105 |           NULL |      1 | cdp      | sw-unifi-mae-ktz              |                0 | GigabitEthernet0/25     | cisco WS-C3560G-24TS  | Cisco IOS Software, C3560 Software (C3560-IPSERVICESK9-M), Version 15.0(2)SE7, RELEASE SOFTWARE (fc1)                     |
| 500 |         16819 |             105 |           NULL |      1 | cdp      | core01.kabsi.at               |                0 | GigabitEthernet2/3      | cisco CISCO7609       | Cisco IOS Software, c7600s72033_rp Software (c7600s72033_rp-ADVIPSERVICESK9-M), Version 15.0(1)S5, RELEASE SOFTWARE (fc1) |
| 501 |         16822 |             105 |          17369 |      1 | cdp      | me36x-mae-01.net.kabelplus.at |               79 | TenGigabitEthernet0/1   | cisco ME-3600X-24TS-M | Cisco IOS Software, ME360x Software (ME360x-UNIVERSALK9-M), Version 15.3(3)S4, RELEASE SOFTWARE (fc1)                     |
| 502 |         16848 |             105 |           2351 |      1 | cdp      | inxrou01.kabelplus.at         |               41 | TenGigE0/0/1/1          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 503 |         16849 |             105 |          17505 |      1 | cdp      | ASR9K-MAE-SRV-01.kabsi.at     |               90 | TenGigE0/0/1/2          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
+-----+---------------+-----------------+----------------+--------+----------+-------------------------------+------------------+-------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------+


Database changed
MariaDB [librenms]> select * from links where local_device_id=105 OR remote_device_id=41;
+-----+---------------+-----------------+----------------+--------+----------+-------------------------------+------------------+-------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------+
| id  | local_port_id | local_device_id | remote_port_id | active | protocol | remote_hostname               | remote_device_id | remote_port             | remote_platform       | remote_version                                                                                                            |
+-----+---------------+-----------------+----------------+--------+----------+-------------------------------+------------------+-------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------+
| 191 |          2159 |              39 |           2385 |      1 | cdp      | inxrou01.kabelplus.at         |               41 | TenGigE0/2/0/0          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 193 |          2225 |              39 |           2388 |      1 | cdp      | inxrou01.kabelplus.at         |               41 | TenGigE0/2/0/3          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 492 |         16802 |             105 |           NULL |      1 | cdp      | ME36X-MAE-KTZ-01.kabelplus.at |                0 | TenGigabitEthernet0/1   | cisco ME-3600X-24FS-M | Cisco IOS Software, ME360x Software (ME360x-UNIVERSALK9-M), Version 15.3(3)S5, RELEASE SOFTWARE (fc1)                     |
| 493 |         16803 |             105 |          17147 |      1 | cdp      | ME36X-Manzb-02.kabelplus.at   |               81 | TenGigabitEthernet0/2   | cisco ME-3600X-24CX-M | Cisco IOS Software, ME360x_t Software (ME360x_t-UNIVERSALK9-M), Version 15.3(3)S5, RELEASE SOFTWARE (fc1)                 |
| 494 |         16806 |             105 |           2343 |      1 | cdp      | inxrou01.kabelplus.at         |               41 | TenGigE0/1/1/1          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 495 |         16809 |             105 |          13589 |      1 | cdp      | sw-ggc01.kabelplus.at         |               45 | TenGigabitEthernet2/0/1 | cisco WS-C3750E-24TD  | Cisco IOS Software, C3750E Software (C3750E-UNIVERSALK9-M), Version 15.0(2)SE7, RELEASE SOFTWARE (fc1)                    |
| 496 |         16813 |             105 |           2153 |      1 | cdp      | Upstream-RO-TZE               |               39 | TenGigE0/0/1/0          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 497 |         16815 |             105 |          17474 |      1 | cdp      | ASR9K-MAE-SRV-01.kabsi.at     |               90 | TenGigE0/1/0/3          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 498 |         16817 |             105 |          15763 |      1 | cdp      | ME34-MAE-KTZ-01.kabelplus.at  |               70 | GigabitEthernet0/1      | cisco ME-3400-24FS-A  | Cisco IOS Software, ME340x Software (ME340x-METROIPACCESSK9-M), Version 12.2(58)SE2, RELEASE SOFTWARE (fc1)               |
| 499 |         16818 |             105 |           NULL |      1 | cdp      | sw-unifi-mae-ktz              |                0 | GigabitEthernet0/25     | cisco WS-C3560G-24TS  | Cisco IOS Software, C3560 Software (C3560-IPSERVICESK9-M), Version 15.0(2)SE7, RELEASE SOFTWARE (fc1)                     |
| 500 |         16819 |             105 |           NULL |      1 | cdp      | core01.kabsi.at               |                0 | GigabitEthernet2/3      | cisco CISCO7609       | Cisco IOS Software, c7600s72033_rp Software (c7600s72033_rp-ADVIPSERVICESK9-M), Version 15.0(1)S5, RELEASE SOFTWARE (fc1) |
| 501 |         16822 |             105 |          17369 |      1 | cdp      | me36x-mae-01.net.kabelplus.at |               79 | TenGigabitEthernet0/1   | cisco ME-3600X-24TS-M | Cisco IOS Software, ME360x Software (ME360x-UNIVERSALK9-M), Version 15.3(3)S4, RELEASE SOFTWARE (fc1)                     |
| 502 |         16848 |             105 |           2351 |      1 | cdp      | inxrou01.kabelplus.at         |               41 | TenGigE0/0/1/1          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 503 |         16849 |             105 |          17505 |      1 | cdp      | ASR9K-MAE-SRV-01.kabsi.at     |               90 | TenGigE0/0/1/2          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
+-----+---------------+-----------------+----------------+--------+----------+-------------------------------+------------------+-------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------+

**Comment by kristoferus75** [comment]
Hi !  Here the output:

In the map i can see only one link !

select * from links where local_device_id=105 OR remote_device_id=41;


Database changed
MariaDB [librenms]> select * from links where local_device_id=105 OR remote_device_id=41;
+-----+---------------+-----------------+----------------+--------+----------+-------------------------------+------------------+-------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------+
| id  | local_port_id | local_device_id | remote_port_id | active | protocol | remote_hostname               | remote_device_id | remote_port             | remote_platform       | remote_version                                                                                                            |
+-----+---------------+-----------------+----------------+--------+----------+-------------------------------+------------------+-------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------+
| 191 |          2159 |              39 |           2385 |      1 | cdp      | inxrou01.kabelplus.at         |               41 | TenGigE0/2/0/0          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 193 |          2225 |              39 |           2388 |      1 | cdp      | inxrou01.kabelplus.at         |               41 | TenGigE0/2/0/3          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 492 |         16802 |             105 |           NULL |      1 | cdp      | ME36X-MAE-KTZ-01.kabelplus.at |                0 | TenGigabitEthernet0/1   | cisco ME-3600X-24FS-M | Cisco IOS Software, ME360x Software (ME360x-UNIVERSALK9-M), Version 15.3(3)S5, RELEASE SOFTWARE (fc1)                     |
| 493 |         16803 |             105 |          17147 |      1 | cdp      | ME36X-Manzb-02.kabelplus.at   |               81 | TenGigabitEthernet0/2   | cisco ME-3600X-24CX-M | Cisco IOS Software, ME360x_t Software (ME360x_t-UNIVERSALK9-M), Version 15.3(3)S5, RELEASE SOFTWARE (fc1)                 |
| 494 |         16806 |             105 |           2343 |      1 | cdp      | inxrou01.kabelplus.at         |               41 | TenGigE0/1/1/1          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 495 |         16809 |             105 |          13589 |      1 | cdp      | sw-ggc01.kabelplus.at         |               45 | TenGigabitEthernet2/0/1 | cisco WS-C3750E-24TD  | Cisco IOS Software, C3750E Software (C3750E-UNIVERSALK9-M), Version 15.0(2)SE7, RELEASE SOFTWARE (fc1)                    |
| 496 |         16813 |             105 |           2153 |      1 | cdp      | Upstream-RO-TZE               |               39 | TenGigE0/0/1/0          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 497 |         16815 |             105 |          17474 |      1 | cdp      | ASR9K-MAE-SRV-01.kabsi.at     |               90 | TenGigE0/1/0/3          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 498 |         16817 |             105 |          15763 |      1 | cdp      | ME34-MAE-KTZ-01.kabelplus.at  |               70 | GigabitEthernet0/1      | cisco ME-3400-24FS-A  | Cisco IOS Software, ME340x Software (ME340x-METROIPACCESSK9-M), Version 12.2(58)SE2, RELEASE SOFTWARE (fc1)               |
| 499 |         16818 |             105 |           NULL |      1 | cdp      | sw-unifi-mae-ktz              |                0 | GigabitEthernet0/25     | cisco WS-C3560G-24TS  | Cisco IOS Software, C3560 Software (C3560-IPSERVICESK9-M), Version 15.0(2)SE7, RELEASE SOFTWARE (fc1)                     |
| 500 |         16819 |             105 |           NULL |      1 | cdp      | core01.kabsi.at               |                0 | GigabitEthernet2/3      | cisco CISCO7609       | Cisco IOS Software, c7600s72033_rp Software (c7600s72033_rp-ADVIPSERVICESK9-M), Version 15.0(1)S5, RELEASE SOFTWARE (fc1) |
| 501 |         16822 |             105 |          17369 |      1 | cdp      | me36x-mae-01.net.kabelplus.at |               79 | TenGigabitEthernet0/1   | cisco ME-3600X-24TS-M | Cisco IOS Software, ME360x Software (ME360x-UNIVERSALK9-M), Version 15.3(3)S4, RELEASE SOFTWARE (fc1)                     |
| 502 |         16848 |             105 |           2351 |      1 | cdp      | inxrou01.kabelplus.at         |               41 | TenGigE0/0/1/1          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
| 503 |         16849 |             105 |          17505 |      1 | cdp      | ASR9K-MAE-SRV-01.kabsi.at     |               90 | TenGigE0/0/1/2          | cisco ASR9K Series    | Cisco IOS XR Software, Version 5.3.3[Default]                                                                             |
+-----+---------------+-----------------+----------------+--------+----------+-------------------------------+------------------+-------------------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------+

**Comment by kristoferus75** [comment]
How is the status in this isue ?

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by kristoferus75** [comment]
Hi !

We have changed our config to etherchannel -> now it work correct !
