### ISSUE TITLE
Allow %sysName in alert template title

### ISSUE THREAD

**Issue by paszczus** [librenms/librenms#3356]
It would be extremly usefull for people using ip's instead of hostnames.

**Comment by f0o** [comment]
Isnt it already?

**Comment by paszczus** [comment]
Nope

**Comment by Mattz0r** [comment]
Not quite sure why you'd use an IP over a hostname. You could always add the hosts/IP's to the hosts file and do it that way.

I've used %hostname for my titles, works fine.

**Comment by paszczus** [comment]
I have 1300+ devices in my network, using hostname for all of them is quite a problem. It would be great if anyone can add such feature ;)

**Comment by f0o** [comment]
Will do

**Comment by paszczus** [comment]
Yeah, thank you. Looking forward for it ;)

**Comment by paszczus** [comment]
@laf are there any chances to get this change in current librenms or we need to wait for librenmsv2? Thanks

**Comment by laf** [comment]
v2 won't touch back end alerting so that's not relevant there.

I'd hope someone else can pick this up as I'm busy working on v2 at the moment.
