### ISSUE TITLE
Historical Alert log purge?

### ISSUE THREAD

**Issue by adammmmm** [librenms/librenms#3357]
Hi!

I tried to find an option to purge the alert log. When going from Alert to Ok, it's removed from "Notification" although the "Historical Log" seemingly never gets cleared/purged like the eventlog does for instance. It's now up to 45 thousand alerts, since a year back.
Am I just missing the option or is there none at the moment?

**Comment by murrant** [comment]
There is none as far as I know, but you can drop the old alerts from the alert_log table if want.

**Comment by Rosiak** [comment]
Should be pretty trivial to add to the daily job I think?
