### ISSUE TITLE
Bad substitution when running daily.sh

### ISSUE THREAD

**Issue by olivermarshall2** [librenms/librenms#3358]
When I run daily.sh I get told

`./daily.sh: 48: ./daily.sh: Bad substitution`

line 48 is
`cnf=${cnf,,}`

Any ideas why that might be?

Olly

**Comment by laf** [comment]
What distro is this?

**Comment by olivermarshall2** [comment]
Ubuntu 14.something

**Comment by laf** [comment]
Works for me.

Run ./validate.php

**Comment by olivermarshall2** [comment]
That tells me that my codebase is out of date, which I know, and that a few
files have the wrong ownership (some sensor files).

After fixing those it still isn't working.

me@LibreNMS:/opt/librenms$ sudo sh ./daily.sh
Updating to latest codebase                       -e  FAIL
./daily.sh: 48: ./daily.sh: Bad substitution

**Comment by olivermarshall2** [comment]
If I don't use sh as the interpretor I get this;


me@LibreNMS:/opt/librenms$ sudo ./daily.sh
Updating to latest codebase                        FAIL
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK

**Comment by laf** [comment]
Just run ./daily.sh, don't need the sh. If you have that in cron then take a look at the current librenms.nonroot.cron file in your install dir for how it should be now.
