### ISSUE TITLE
Eaton 5PX USP with Network Management Card

### ISSUE THREAD

**Issue by oam7575** [librenms/librenms#3364]
Incorrect device detection.

The 5PX range of Eaton UPS device appear to have been aquired from MGE in 2007.
See this page : http://www.power-solutions.com/ups/mge

This may lead to some odd device detection and OS details depending on the age of the device and if the firmware has been adjusted to display MGE or Eaton.

How the device presents itself is dependant on the Network Management Card
In my case the card is a slightly older model with older firmware ( which AFAIK cannot be upgraded )

adjusting /opt/librenms/includes/discovery/os/eatonups.inc.php as follows

<?php
if (!$os) {
    // Eaton UPS
    if (strstr($sysDescr, 'Eaton 5PX')) {
//        $os = 'eatonups';
        **$os = 'mgeups';**
    }
}

Allows for slightly better device detection ( but this is may not be 100% correct )

I have attached screen shot of the NMC firmware along with output from snmpwalk and commands

./poller.php -h HOSTNAME -d -r -f -m os
./discovery.php -h HOSTNAME -d -m os

![5px_ups_firmware](https://cloud.githubusercontent.com/assets/18411503/14483433/577c4c12-018a-11e6-9818-9b313d298aa6.PNG)

[5px-2000.domain.local.txt](https://github.com/librenms/librenms/files/216415/5px-2000.domain.local.txt)
[eaton_5px_discovery_os.txt](https://github.com/librenms/librenms/files/216413/eaton_5px_discovery_os.txt)
[eaton_5px_poller_os.txt](https://github.com/librenms/librenms/files/216414/eaton_5px_poller_os.txt)

**Comment by oam7575** [comment]
It should also be noted that in older versions of the NMC firmware there is a bug which will cause the NMC to reboot when attempting to poll using SNMP v3

This bug has apparently been resolved in firmware JC or newer
The attached file has release notes from Eaton.


[Release_Note_NetworkMS_JH.txt](https://github.com/librenms/librenms/files/216420/Release_Note_NetworkMS_JH.txt)

**Comment by laf** [comment]
I'm confused with this one, your screenshot shows this as an eaton ups?!

**Comment by oam7575** [comment]
Hi Laf

The unit is branded as an Eaton UPS, however Eaton purchased the MGE product line from Power Solutions in 2007 and renamed it.

Please see this page : http://www.power-solutions.com/ups/mge for more details.

As far as I can tell the NMC still reports mgeups as the OS string.

When LibreNMS is configured to detected the UPS as an Eaton device it failed to display SNMP data correctly.

After adjusting /opt/librenms/includes/discovery/os/eatonups.inc.php to list the OS as mgeups SNMP data started to be displayed.

The problem may be related to incorrect Eaton MIBS??- but I am not sure.

Please check the poller, discovery and complete snmpwalk files attached to my first post - hopefully they can clarify this.

If you need further details let me know what you need or what commands to run and I will try to get it to you.

Cheers.

**Comment by oam7575** [comment]
Looking a bit closer at the Eaton website it appears that there are different mib files for different management cards.

I have attached 2x mib files in TXT format below.
The XUPS_Power_Xpert_Gateway file is for a newer style of management card

[Xups_Power_Xpert_Gateway.mib.txt](https://github.com/librenms/librenms/files/248048/Xups_Power_Xpert_Gateway.mib.txt)


This file XUPS-MIB_Network_Card_MS - is the mib file that matches the older style management card that I have installed in my 5PX

[XUPS-MIB_Network_Card_MS_5PX.txt](https://github.com/librenms/librenms/files/248046/XUPS-MIB_Network_Card_MS_5PX.txt)

Further testing is likely required however this suggests a bug due to MIB file oddness from Eaton.

If you can provide a workflow of files that need changing or MIB files to replace I am happy to test further.

Cheers,

**Comment by oam7575** [comment]
More details

The attached PDF has details on which MIBs are compatible with the NMC installed in my 5PX

Page 122 has the following.

1.3.7 MIB (Management Information Base)
The card is Compatible with following MIBs:
• MIB II (RFC 1213)
• Internet Engineering Task Force (IETF) Standard UPS MIB (RFC 1628)
• EATON Pulsar MIB (ex MGE) V1.7
• EATON Powerware MIB (PowerMib)

Additionally the appendix section 7.2 lists the SNMP objects  and MIB access paths

As previously mentioned I am happy to have a bit of a poke at this to see if I can get it working; but I would need some pointers to get me started.

Cheers,

[66102_User_Manual_English.pdf](https://github.com/librenms/librenms/files/250022/66102_User_Manual_English.pdf)

**Comment by oam7575** [comment]
Pull Request #3572 submitted to hopefully fix up the detection issues and add support for a few more sensors.

First time round for me - let me know if i need to adjust anything.

Cheers.

**Comment by oam7575** [comment]
First attempt at pull request was close enough to a disaster.

Thanks to @laf  and @murrant for the help they provided I have started again and submitted PR #3601 
Hopefully it will be a _little_ bit neater and closer to what is needed.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by Di-Sa** [comment]
Hi,
I have an Eaton EX-2200, with network card, that LibreNMS doesn't recognize: it is seen as Generig Device...
In the MIB tab

**Comment by laf** [comment]
Please provide the info from http://docs.librenms.org/Support/FAQ/#faq8

**Comment by Di-Sa** [comment]
Thanks, here are the infos:
LibreNMS: 192.168.57.220, Eaton EX-2200: 192.168.57.225, Gateway: 192.168.57.254, community: public

Eaton EX-2200 - LibreNMS - Discovery: http://pastebin.com/DQJC5qEL
Eaton EX-2200 - LibreNMS - Poller: http://pastebin.com/3Xrs4FwF
Eaton EX-2200 - LibreNMS - SNMPwalk: http://pastebin.com/ThJhEtR7

**Comment by murrant** [comment]
This seems to be one of the Re-branded MGE UPS's.

Eaton bought MGE's small business devices.
