### ISSUE TITLE
Alert Catalog Emails

### ISSUE THREAD

**Issue by pblasquez** [librenms/librenms#3368]
Would be nice to be able to receive all alerts from the last run in one email as opposed to one email per alert.

Could also be applicable to other transports.

**Comment by laf** [comment]
Not sure how that would work with templates (the default template would be fine I expect) but custom templates wouldn't work as they are bound to a specific rule.

**Comment by Mattz0r** [comment]
I think that would get confusing, and emails would get quite large, depending on what content you have in the email.

I personally prefer it the way it is.

**Comment by murrant** [comment]
I think cataloging only makes sense with email.  I think most other transports work better with individual notifications.

I suspect issue #3293 would be a better resolution than this.

**Comment by pblasquez** [comment]
@Mattz0r One email per device would be fine.
@murrant While I like that idea too, that doesn't solve this issue at all.

For example:  Let's say there is a device that is connected to an internet exchange such as AMSIX or Equinix.  The link to the exchange drops.  I will now receive X emails, where X is the number of BGP sessions I am monitoring.  I would like to receive 1 email with X lines instead.

Make sense?

**Comment by pblasquez** [comment]
Ugh, I did some testing to play around with this and it looks like Alerts ARE cataloged, just per alert+device, instead of a rollup of all into each device.  It's still a gap, but a much smaller one than I thought.

I will close this, and my apologies for the misunderstanding.

**Comment by murrant** [comment]
No problem @pblasquez It's great to have a discussion about these things. That's how things get better.

Thanks for creating the issue.
