### ISSUE TITLE
Unable to add MIBS: A10 Networks

### ISSUE THREAD

**Issue by higante702** [librenms/librenms#3369]
Hello all!

I attempted to follow the guide for adding for adding Basic Support for a new OS:
http://docs.librenms.org/Support/Support-New-OS/

Using said guide, I was able to get an Icon and the A10Networks hardware type, but none of the other MIB information was imported.

I think that I am assuming that it will add in all of the info on its own, but I am having some trouble finding any additional info for a greenhorn like myself.

Any tips would be appreciated, please let me know what I can offer to better explain.

**Comment by laf** [comment]
Not sure what you mean by mib information but by default we don't import anything from mibs. You'll need to use mib polling for that: http://docs.librenms.org/Extensions/MIB-based-polling/

**Comment by higante702** [comment]
Interesting! I am going to looki into that now and post my results.

**Comment by higante702** [comment]
Went into the IRC chat and worked with Dave, Laf, and@Rosiak.

Thank you for all of your help, it worked and I was able to get it in via the /includes/discovery/os/#os.ini.php file.

Only thing now is to set up alerting, but I am sure I will bug in the chat for that.

Thanks all again!
