### ISSUE TITLE
Use same mysql engine for all tables

### ISSUE THREAD

**Issue by elbuit** [librenms/librenms#337]
At this time librenms mix MyISAM and InnoDB tables:

I think that is better to use same engine for all tables:

ALTER TABLE slas ENGINE=InnoDB; 
ALTER TABLE packages ENGINE=InnoDB;
ALTER TABLE munin_plugins_ds ENGINE=InnoDB;
ALTER TABLE munin_plugins ENGINE=InnoDB; 
ALTER TABLE loadbalancer_vservers ENGINE=InnoDB;
ALTER TABLE loadbalancer_rservers ENGINE=InnoDB;
ALTER TABLE ipsec_tunnels ENGINE=InnoDB; 

mysql> SELECT table_name FROM INFORMATION_SCHEMA.TABLES    WHERE TABLE_SCHEMA='librenms' AND engine = 'MyISAM';
+-----------------------+
| table_name            |
+-----------------------+
| ipsec_tunnels         |
| loadbalancer_rservers |
| loadbalancer_vservers |
| munin_plugins         |
| munin_plugins_ds      |
| packages              |
| slas                  |
+-----------------------+

**Comment by laf** [comment]
As we only have 7 tables in MyIsam according to this none of which will benefit from read speed in MyIsam, shall we just convert them over?

**Comment by f0o** [comment]
:+1:

**Comment by laf** [comment]
Sorry for the delay @elbuit. I've just submitted a PR which does exactly what you've suggested + one extra change.

#1178
