### ISSUE TITLE
Losing php session intermittently

### ISSUE THREAD

**Issue by wiad** [librenms/librenms#3372]
I've had this issue ever since I first installed LibreNMS, both with mysql auth driver and AD auth driver. The problem is that I'm getting logged out suddenly and intermittently. There is no pattern in this, sometimes my session is alive for hours and sometimes I'm getting logged out pretty much instantly. Clicking the 'remember me' box makes no difference.

Debugging shows that when the problem occurs the php session is empty when authentication is attempted. After many attempts to solve this it finally seems to work after commenting out the line
`@ini_set('session.gc_maxlifetime', '0');`

in html/includes/authenticate.inc.php. Doesn't make sense to me because the above is supposed to disable session garbage collection entirely, but I'm not very well versed with php sessions. 

Anyone else having problems with this? Anyone more experienced with php sessions that can explain why commenting out the above would solve the problem for me?

**Comment by laf** [comment]
Check the session.save_path in php.ini, make sure it's somewhere writable by web server

**Comment by wiad** [comment]
I've googled a good deal about lost php sessions and the session.save_path is a recurring culprit among them. For me, however, fiddling with this has made no difference.

**Comment by wiad** [comment]
I've been running with my modification for over 12hrs and not had one single logout.

I just removed my comment of 
`@ini_set('session.gc_maxlifetime', '0');`

restarted apache, removed my existing session and logged in. I've had two logouts within one hour. This is on a RHEL7 box. 

I find very little documentation about setting session.gc_maxlifetime to '0', but if noone else is having this problem there must be something in my environment. I've had LibreNMS installed on two separate servers and had the problem on both (both are RHEL7).

**Comment by laf** [comment]
Others have mentioned of similar issues. I'm not sure why that's there from memory so it possibly could be removed.
