### ISSUE TITLE
Config Tab (Oxidized integration) not viewable due to accidental RBAC? 

### ISSUE THREAD

**Issue by Lucheni** [librenms/librenms#3377]
The integration between Oxidized is successfull, only problem is that Global Read nor Normal Users cannot actually view the configurations. The Config Tab does not even display for them.

I have tried letting the Global Read user become a Normal User, and dedicated device access for this specific user account. The per-device-access is working fine, but still no go on viewing the config tab.

**Comment by murrant** [comment]
That is correct.  The thing is, configs can often contain sensitive data.  Because of that we leave access only to global administrators.

What permissions are you trying to achieve.

**Comment by Lucheni** [comment]
Hi!

That is true. 

But in this case the sensitive data belongs to the customer. We are helping them with integrated insight into their environment. The customer in this case is not and should not be managing the settings, but should still able to see the configurations on their devices and when said configurations were last updated.

Maybe there could be a a device-specific administrator that has full rw access to the nodes (including the config tab) or maybe a per account based "Config viewer" checkmark?



Best regards,
Andreas

**Comment by murrant** [comment]
@librenms/reviewers thoughts on this?  How can we best allow Lucheni's use case?

**Comment by Rosiak** [comment]
This would be a nice addition for a user and I certainly see the idea of it.
In regards to how to implement it, it could be fairly simple for each device or a bit more complex taking a subset of devices, group or something like that.

**Comment by murrant** [comment]
I've been thinking about this and I don't think we can change it upstream.  I am willing to give you a patch you can install locally.  FYI, that is likely to block updates at some point.

**Comment by Lucheni** [comment]
Thank you, but if that would mean blocked updates in the future I would probably rather just give the customer Global Admin rights instead. How come you don't think it can be changed upstream? Can this still be a feature request rather than an Issue?

Best regards,

**Comment by Lucheni** [comment]
For anyone wanting to do an out-of-the-box supported workaround, you can set the account to the demo user account type. This enables read access to the configurations but prohibits the user from deleting CI's. 

Best regards,
Lucheni

**Comment by spinza** [comment]
I have hidden senstive info from Oxidized specifically to engage this feature.  Any hints on how to enable this for a read-only user?
