### ISSUE TITLE
Billing Extension - PDU Billing

### ISSUE THREAD

**Issue by Talie5in** [librenms/librenms#3378]
Hey Team,

We currently do PDU Billing per rack (two PDU's a rack, one dirty feed one UPS protected)
We currently do this with a perl script that polls and logs amps,wattage from the OID's (SNMP) on our APC PDU's.

All we do is combine the two avg(wattage) outputs from mysql between the start and end date (first and last of month) and then run the following.

combinedd-avgwatts \* 24 \* days / 1000 = Watt hours used over the month.

All we do is set what the 'paid for usage' is, and the rest is an overrage.

I feel this is a naturate extention to the billing system, and as this data looks like it's arleady logged by polling a APC PDU with LibreNMS should be able to be extended (with relative ease, i think?)

Just as you can add mutiple ports to a bill, you could easily add multiple PDU's to the one 'power' bill.

**Comment by laf** [comment]
This isn't as easy as you might think as we don't have the data really. Anything only in rrd files means it loses it's resolution past 24 hours so it's no longer accurate.

What would need to be done is the same as the port billing module, this is a bit more work but something I think we should do.

**Comment by Talie5in** [comment]
Laf, understand, I think I worked on the assumption this may of been logged in the database.

If there is anything I can provide eg, the query we use to pull the data from our database which we are filling in from polling the OID on the PDU's, let me know.

Already provided the math equation we use :)

Even if you just pull the current (AMPS) we can use math to turn into watts with the correct power factor (may need to use a human enter-able field for the power factor (generally around 0.90)

Although APC PDU's output the power factor in an OID from memory...

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-billing-extension-pdu-billing/723
