### ISSUE TITLE
Autodiscovery doesn't add nodes to network map

### ISSUE THREAD

**Issue by gelato** [librenms/librenms#3379]
Nodes can be added to network map only if i add them manually, network map can't be populated with automatic discovery feature (all discovery options are enabled).
So... Is there a way to fix this?

**Comment by laf** [comment]
Would need to see the output of ./discovery.php -h HOSTNAME -d -m discovery-protocols

for a device which does and doesn't work. please pastebin the output.

**Comment by laf** [comment]
Please feel free to re-open this with the output.

**Comment by gelato** [comment]
This node is manually added to libreNMS and does work correctly:

http://pastebin.com/n3WwnFH8

This was added automatically and doesn't have anything in network map about it, also no health info from it:

http://pastebin.com/iKzBCQXS

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
