### ISSUE TITLE
send alert only once on device status changed to up/down

### ISSUE THREAD

**Issue by beeelze** [librenms/librenms#3380]
I've created two alert rules:

%devices.status != "1" and
%devices.status != "0"

and I set the interval to 0 for not receiving recurring mails when the device's status stays the same for more than 5 minutes. However, I'm still getting alert e-mails every time the system polls again. 

A solution for me would be adding a mail functionality to the 'log_event' function by filtering the $text variable to 'Device status changed to' as I've done with my third party SMS service. But using alerts is much cooler of course.

Why is proposed solution of setting the interval to 0 not working for me?

**Comment by laf** [comment]
You want to set max to 1, interval is how often we will send the alerts, 0 would equate to every 1 minute.

**Comment by arrmo** [comment]
And delay is how long before the initial alert is sent ... correct?

Thanks!

**Comment by laf** [comment]
Yes indeed

**Comment by arrmo** [comment]
Thanks! And one last one ... many of the global rules show Max as -1 => I assume this means no limit, right? So start after delay, and keep sending every interval, correct?

**Comment by laf** [comment]
Yes -1 is unlimited.

**Comment by arrmo** [comment]
Thanks!!!

**Comment by dineshdil** [comment]
I have set it as 0 where it should not send any alert. Right? What needs to be check if it still sending alerts?

**Comment by dineshdil** [comment]
How can we play a sound via GUI if any device up/down or port up/down
