### ISSUE TITLE
Include HH3C mibs

### ISSUE THREAD

**Issue by gcoeugnet** [librenms/librenms#3388]
Hi,

We need to include HH3C MIBS in our libreNMS. I found MIBs files in an unofficial observium repository. As observium is not open source (as far as i know), what do I need to do to include HH3C MIBs support in libreNMS (including polling and discovery) ?

Develop new polling/discovery PHP files are likely to be very close of observium ones... 

Another issue exists [here](https://github.com/librenms/librenms/issues/2702) for H3C MIBs.
Thanks for any informations.

**Comment by laf** [comment]
Don't worry, observium don't own copyright on mibs. However you can download hh3c stuff from hp's website:

https://h10145.www1.hpe.com/downloads/SoftwareReleases.aspx?ProductNumber=JE006A

That's for a HP 1910-24 but they are probably the same across the board.

As for the code, it's understandable that it will be similar to observiums as we are a fork, however you must agree to and sign the contributors agreement. So long as you aren't copying the code from them then you should be fine.

**Comment by gcoeugnet** [comment]
Ok I take a look at this and I'll make a pull request "when it's ready". thanks for quick answer.
