### ISSUE TITLE
Add support for EMC Isilon/OneFS

### ISSUE THREAD

**Issue by kuoirad** [librenms/librenms#3400]
I would like to be able to monitor my Isilon storage cluster.  Would it be possible to have support added?  I've attached the MIBs from EMC.

[ISILON-MIB.txt](https://github.com/librenms/librenms/files/228598/ISILON-MIB.txt)

**Comment by laf** [comment]
Please post the output of:

./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -r -f -d -m os
An snmpwalk of the device:
snmpbulkwalk -v2c -c COMMUNITY HOSTNAME .

**Comment by f0o** [comment]
Might be able to contribute a device for you laf, will paste you the IP on IRC

**Comment by kuoirad** [comment]
I have a sneaking suspicion I did something wrong with discovery and poller based on what the output looks like.  Please let me know if I did.

Thanks!

[discovery_output.txt](https://github.com/librenms/librenms/files/245782/discovery_output.txt)
[poller_output.txt](https://github.com/librenms/librenms/files/245784/poller_output.txt)
[snmpwalk.txt](https://github.com/librenms/librenms/files/245783/snmpwalk.txt)

**Comment by laf** [comment]
Yeah those outputs aren't correct. Is that IP definitely what LIbreNMS knows the device as?

**Comment by kuoirad** [comment]
I don't have it in at the minute, I'd taken it back out since it didn't seem to be working well/right.  Should I add it back in?

**Comment by laf** [comment]
Yeah, you can't do disco/poll if it's not in.

**Comment by kuoirad** [comment]
Sorry.  Here's new ones, after it's been added.

[discovery_output.txt](https://github.com/librenms/librenms/files/245983/discovery_output.txt)
[poller_output.txt](https://github.com/librenms/librenms/files/245984/poller_output.txt)

**Comment by kuoirad** [comment]
Thank you.
