### ISSUE TITLE
Add RLETech FMS Support

### ISSUE THREAD

**Issue by kate66** [librenms/librenms#3402]
Support for environmental sensors (power based) would be helpful, for example the RLE Falcon FMS: http://rletech.com/product-support/fms/ (MIB file is at the site mentioned, let me know what else you may need)

**Comment by laf** [comment]
./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -r -f -d -m os
An snmpwalk of the device:
snmpbulkwalk -v2c -c COMMUNITY HOSTNAME .

**Comment by Rosiak** [comment]
No info, closing.
