### ISSUE TITLE
Add a pages printed graph or numerical output.

### ISSUE THREAD

**Issue by ghost** [librenms/librenms#3407]
When a printer is found, inserting a pages printed readout by default would be benificial.

snmpwalk -v 1 -c public PRINTER .1.3.6.1.2.1.43.10.2
iso.3.6.1.2.1.43.10.2.1.2.1.1 = INTEGER: 4
iso.3.6.1.2.1.43.10.2.1.3.1.1 = INTEGER: 7
iso.3.6.1.2.1.43.10.2.1.4.1.1 = Counter32: 2039
iso.3.6.1.2.1.43.10.2.1.5.1.1 = Counter32: 0
iso.3.6.1.2.1.43.10.2.1.6.1.1 = INTEGER: 1
iso.3.6.1.2.1.43.10.2.1.7.1.1 = INTEGER: 0
iso.3.6.1.2.1.43.10.2.1.8.1.1 = INTEGER: 3
iso.3.6.1.2.1.43.10.2.1.9.1.1 = INTEGER: 600
iso.3.6.1.2.1.43.10.2.1.10.1.1 = INTEGER: 600
iso.3.6.1.2.1.43.10.2.1.11.1.1 = INTEGER: 1667
iso.3.6.1.2.1.43.10.2.1.12.1.1 = INTEGER: 1667
iso.3.6.1.2.1.43.10.2.1.13.1.1 = INTEGER: 1667
iso.3.6.1.2.1.43.10.2.1.14.1.1 = INTEGER: 1667
iso.3.6.1.2.1.43.10.2.1.15.1.1 = INTEGER: 0

This is against an HP LaserJet 400 color M451dn

This is another output
 snmpwalk -v 1 -c public PRINTER iso.3.6.1.2.1.43.10.2.1.4.1.1
iso.3.6.1.2.1.43.10.2.1.4.1.1 = Counter32: 534116

**Comment by Rosiak** [comment]
Hi,

We are cleaning up the issues here on GitHub, all feature requests will be moved to:
https://community.librenms.org/c/feature-requests

Hence the closure of this issue.
