### ISSUE TITLE
Compatibility issue with PHP after updating to Ubuntu Server 16.04

### ISSUE THREAD

**Issue by trick77** [librenms/librenms#3412]
eregi is no more in PHP 7. PR in the works.

**Comment by trick77** [comment]
https://github.com/librenms/librenms/pull/3413

There are a few more in shoutcast-related php files.

**Comment by trick77** [comment]
It looks like addhost.php is not working anymore on 16.04. Any pointers?

**Comment by paulgear** [comment]
Can you post any error messages from addhost?

**Comment by trick77** [comment]
Nothing specific, just 
Could not reach wopr.norad.mil with given SNMP community using v3

**Comment by trick77** [comment]
tcpdump shows no UDP packet is being sent except for the DNS lookup.

**Comment by murrant** [comment]
@trick77 Try to ping the host or snmpwalk from the command line.

**Comment by trick77** [comment]
I had to flag the ip column in the devices table as nullable in order to insert a new host with php 7. I don't understand it either.

**Comment by trick77** [comment]
Here's another one that came with the MySQL upgrade:

Top devices/interfaces won't show up because:

SELECT *, sum(p.ifInOctets_rate + p.ifOutOctets_rate) as total FROM ports as p, devices as d WHERE d.device_id = p.device_id AND unix_timestamp() - p.poll_time <  3600 AND ( p.ifInOctets_rate > 0 OR p.ifOutOctets_rate > 0 ) GROUP BY d.device_id ORDER BY total desc LIMIT 10

#1055 - Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'o11_librenms.p.port_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by laf** [comment]
What version of MySQL and where is that query run from?

**Comment by trick77** [comment]
That would be
mysql  Ver 14.14 Distrib 5.7.12, for Linux (x86_64) using  EditLine wrapper
and the query is run from
html/includes/common/top-devices.inc.php

On a side note, where should into if alerts are not getting cleared?

**Comment by laf** [comment]
What distro are you using?

please create a separate issue for other queries. It's too confusing to bundle them in one.

**Comment by trick77** [comment]
Ubuntu Server 16.04 (see title).

**Comment by f0o** [comment]
It seems you're sql is the source of the issues ( apart from that eregi one)

Double check that you don't have strict mode set etc.

Php7 per se works for me, i don't use smokeping so i didn't run into the eregi..

**Comment by trick77** [comment]
Interesting. Thanks for the pointer.

**Comment by laf** [comment]
php7 works ok. closing this.
