### ISSUE TITLE
Services not working properly in dash device-summary widget

### ISSUE THREAD

**Issue by rasssta** [librenms/librenms#3418]
All services are shown as down, when they are up...

**Comment by f0o** [comment]
That's probably because we changed the state value meanings.. Can checkup on Monday with our work install

On 24 April 2016 14:46:35 CEST, rasssta <notifications@github.com> wrote:
>All services are shown as down, when they are up...
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/3418

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
