### ISSUE TITLE
Install docs - Change suggestion regarding adding a device

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#3421]
We suggest adding the device as root, we should change that to the librenms user(Permissions)

**Comment by laf** [comment]
No folders are created at that stage are they?

**Comment by Rosiak** [comment]
They are when we suggest running the disco - http://docs.librenms.com/Installation/Installation-(RHEL-CentOS)/#add-localhost

**Comment by laf** [comment]
Disco still doesn't create folders does it. It's polling that does iirc

**Comment by Rosiak** [comment]
Looking at it you are right, however it created /opt/librenms/logs/librenms.log which had the wrong permissions.
