### ISSUE TITLE
Feature Request: Ignore interfaces based on ifName value

### ISSUE THREAD

**Issue by thecityofguanyu** [librenms/librenms#3422]
In the way you can:

```
$config['bad_if'][] = "voip-null";
$config['bad_iftype'][] = "voiceEncap";
```

It would be nice if you could:

```
$config['bad_ifname'][] = "port-name";
```

**Comment by pblasquez** [comment]
Do you mean ifAlias?  The logic already uses ifDescr which is usually the same as ifName.

ifAlias is the user-defined description of the port.

**Comment by thecityofguanyu** [comment]
@pblasquez 

>Do you mean ifAlias?

No, I did indeed mean ifName.

>The logic already uses ifDescr which is usually the same as ifName.
>
>ifAlias is the user-defined description of the port.

Correct, although Calix E7s are an exception to this.  

![Calix E7 ports from phpMyAdmin](http://i.imgur.com/vHpjtJg.png)

As you'll see there, ifAlias is still the user-defined description of the port; however, ifDescr is the same as ifAlias rather than being the same as ifName.

But I do understand that this is a bit of an outlier type of situation.

**Comment by pblasquez** [comment]
Understood.  I don't mind putting in a PR for this, will link it once done.
