### ISSUE TITLE
Unable to generate graphs on new network device adds

### ISSUE THREAD

**Issue by PENorris** [librenms/librenms#3424]
Getting RRD tool errors on new switch adds with the following error "RRDTool Output
ERROR: No DS called 'OUTOCTETS' in '/opt/librenms/rrd/sjsoadminc3750g_smstr.co.st-johns.fl.us/port-id2142642.rrd' "  

2 of the interfaces are drawing correctly, but I don't even know where to start on troubleshooting this.
RRDtool is 1.5.5  and Ubuntu 16.04, however the issue was the same on 14.04.  The issue seemed to start after moving to RRDcached if that helps. 

Validate comes back with 
sjcmis@netmon:/opt/librenms$ sudo ./validate.php
Version info:
Commit SHA: 59428bbe447ca9aca9b7f71e48aa50a775563869
DB Schema: 113
PHP: 7.0.4-7ubuntu2
MySQL: 5.7.12-0ubuntu1
RRDTool: 1.5.5
SNMP: NET-SNMP version: 5.7.3

[OK]      Database connection successful
sjcmis@netmon:/opt/librenms$
 
Permissions, are as described in the install.  RRD command is as follows. 

RRDTool Command
rrdtool graph /tmp/NhWgkpygSDNngVlW.png --alt-autoscale-max --rigid -E --start 1461527100 --end 1461613500 --width 1163.7 --height 285 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal DEF:outoctets=/opt/librenms/rrd/sjsoadminc3750g_smstr.co.st-johns.fl.us/port-id2142642.rrd:OUTOCTETS:AVERAGE DEF:inoctets=/opt/librenms/rrd/sjsoadminc3750g_smstr.co.st-johns.fl.us/port-id2142642.rrd:INOCTETS:AVERAGE DEF:outoctets_max=/opt/librenms/rrd/sjsoadminc3750g_smstr.co.st-johns.fl.us/port-id2142642.rrd:OUTOCTETS:MAX DEF:inoctets_max=/opt/librenms/rrd/sjsoadminc3750g_smstr.co.st-johns.fl.us/port-id2142642.rrd:INOCTETS:MAX CDEF:octets=inoctets,outoctets,+ CDEF:doutoctets=outoctets,-1,* CDEF:outbits=outoctets,8,* CDEF:outbits_max=outoctets_max,8,* CDEF:doutoctets_max=outoctets_max,-1,* CDEF:doutbits=doutoctets,8,* CDEF:doutbits_max=doutoctets_max,8,* CDEF:inbits=inoctets,8,* CDEF:inbits_max=inoctets_max,8,* VDEF:totin=inoctets,TOTAL VDEF:totout=outoctets,TOTAL VDEF:tot=octets,TOTAL VDEF:95thin=inbits,95,PERCENT VDEF:95thout=outbits,95,PERCENT CDEF:d95thoutn=doutbits,-1,* VDEF:d95thoutn95=d95thoutn,95,PERCENT CDEF:d95thoutn95n=doutbits,doutbits,-,d95thoutn95,-1,*,+ VDEF:d95thout=d95thoutn95n,FIRST COMMENT:'bps Now Ave Max 95th %\n' AREA:inbits_max#D7FFC7: AREA:inbits#90B040: LINE:inbits#608720:'In ' GPRINT:inbits:LAST:%6.2lf%s GPRINT:inbits:AVERAGE:%6.2lf%s GPRINT:inbits_max:MAX:%6.2lf%s GPRINT:95thin:%6.2lf%s\n AREA:doutbits_max#E0E0FF: AREA:doutbits#8080C0: LINE:doutbits#606090:'Out' GPRINT:outbits:LAST:%6.2lf%s GPRINT:outbits:AVERAGE:%6.2lf%s GPRINT:outbits_max:MAX:%6.2lf%s GPRINT:95thout:%6.2lf%s\n GPRINT:tot:'Total %6.2lf%sB' GPRINT:totin:'(In %6.2lf%sB' GPRINT:totout:'Out %6.2lf%sB)\l' LINE1:95thin#aa0000 LINE1:d95thout#aa0000

**Comment by laf** [comment]
I'd suggest removing the rrd file and let it be recreated

**Comment by laf** [comment]
Feel free to re-open this issue if you are still having issues.
