### ISSUE TITLE
unable to remove a device with no hostname

### ISSUE THREAD

**Issue by jzombory** [librenms/librenms#3429]
I have a device that is coming up with no Hostname in the "Alerts" dashboard and I don't know how to remove it. 

![capture](https://cloud.githubusercontent.com/assets/10948428/14829629/6d0a21d2-0bba-11e6-977e-216cb3840223.PNG)

**Comment by laf** [comment]
This is the query being run:

```mysql
SELECT `alerts`.*, `devices`.`hostname` AS `hostname`, `devices`.`sysName` AS `sysName`,`alert_rules`.`rule` AS `rule`, `alert_rules`.`name` AS `name`, `alert_rules`.`severity` AS `severity`  FROM `alerts` LEFT JOIN `devices` ON `alerts`.`device_id`=`devices`.`device_id`  RIGHT JOIN `alert_rules` ON `alerts`.`rule_id`=`alert_rules`.`id` WHERE 1 AND `alerts`.`state`!=0 ORDER BY timestamp DESC LIMIT 0,10
```

Run that, it should give you the alerts.id, delete those from the DB.

**Comment by f0o** [comment]
Funky stuff...

Is there any way you can reproduce this?

**Comment by laf** [comment]
Never seen it before personally. MySQL strict mode?

**Comment by jzombory** [comment]
Not running MySQL, I'm running MariaDB. Below is the output from the command you wanted me to run. I don't see an output. I have been unable to reproduce it.

librenms-host:/opt/librenms$ sudo mysql -uroot -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 1067418
Server version: 5.5.47-MariaDB-1ubuntu0.14.04.1 (Ubuntu)

Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> SELECT `alerts`.*, `devices`.`hostname` AS `hostname`, `devices`.`sysName` AS `sysName`,`alert_rules`.`rule` AS `rule`, `alert_rules`.`name` AS `name`, `alert_rules`.`severity` AS `severity`  FROM `alerts` LEFT JOIN `devices` ON `alerts`.`device_id`=`devices`.`device_id`  RIGHT JOIN `alert_rules` ON `alerts`.`rule_id`=`alert_rules`.`id` WHERE 1 AND `alerts`.`state`!=0 ORDER BY timestamp DESC LIMIT 0,10
    ->
    ->
    ->
    ->

**Comment by laf** [comment]
You need to add a semi-colon to the end of the query.

**Comment by Rosiak** [comment]
Any news?

**Comment by laf** [comment]
No feedback provided, feel free to comment if you have more info.
