### ISSUE TITLE
Add Alert Rule Email Recipient Mapping

### ISSUE THREAD

**Issue by pblasquez** [librenms/librenms#3431]
I would like to submit a PR to map specific email recipients to specific alert rules. Right now I am planning to:
- Add a sql table to track rule_id->email address line relationship
- Add a UI to allow maintenance of the above table.
- In alerts.inc.php:
  - Pass the rule id to GetContacts() as a 2nd, optional variable
  - Within GetContacts(), if 2nd variable exists, pull matching email addresses from the table and push into the $contacts array.
    --OR--
  - Alternatively, evaluate for email addresses outside of GetContacts and pass an email address array as the 2nd variable, and use it to initialize the $contacts array.

Asking for a green light to begin work on this and also feedback on design.

**Comment by Rosiak** [comment]
Tagging @f0o for input.

**Comment by murrant** [comment]
I'd like to do something similar for slack and other transports.
I'd associate specific contacts with different channels and deliver it there if there is a match.

**Comment by laf** [comment]
f0o has done something in the next alerting revision where within the transports you can be more specific about which alerts go to which transports and possibly others. Would be good to get his input.

**Comment by pblasquez** [comment]
Ok that is good to hear, maybe this is already underway.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-add-alert-rule-email-recipient-mapping/722

**Comment by laf** [comment]
This is now possible
