### ISSUE TITLE
How to get the physical link in a topology map ?

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#3436]
I think librenms got the logical link in the topology map , but how to get the physical link  ?

Is that a complex problem ?

:)

Thank you !

**Comment by laf** [comment]
Is this for xDP or Mac?

**Comment by wzhsunn** [comment]
I can get the logical link by CDP  protocol,  how to get the physical link ( which is real real cable between the two device) .
 I will be very grateful for any helpful advice ! 
:)

**Comment by wzhsunn** [comment]
@laf  Is this message sufficient ?

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by sivadm** [comment]
This is the main reason I like the old map better than the new one. It appears that the new map shows links between two devices as they see each other over a vlan, and I want to be able to show the physical and virtual links (separately) as well as be able to arrange the data and be able to save its presentation.

==========================================================
Component | Version
--------- | -------
LibreNMS  | 0240a95e627873add673055199d43439986632c9
DB Schema | 157
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================
