### ISSUE TITLE
Show values 3 times

### ISSUE THREAD

**Issue by logtron** [librenms/librenms#3450]
Synology and Vmware ESXi 6.0 Maschines present wrong count of CPU, Memory, VM Machines etc.
1 value (real) show 3 values exact the same.

Distributed Polling is active.
![2016-05-02 09_01_07 - librenms](https://cloud.githubusercontent.com/assets/19145058/14948806/88fbdd2a-1044-11e6-87f3-713a24426450.png)

**Comment by laf** [comment]
Please provide the output of:

```bash
./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -d -r -f -m os
```

**Comment by laf** [comment]
Closing due to no information being provided.
