### ISSUE TITLE
PHP issues

### ISSUE THREAD

**Issue by jmaliska** [librenms/librenms#3451]
After the Services pages were updated recently, I found some problems on Services list page and add service dialog. See screenshots:
![0cb58c4e-0bed-11e6-8d80-cbceae387592](https://cloud.githubusercontent.com/assets/16898329/14949662/0fc4ae66-104c-11e6-8ad6-7acd603e6c5d.png)

![de3cfdde-0bec-11e6-84f0-7b7b80093dbb](https://cloud.githubusercontent.com/assets/16898329/14949667/1373bdf4-104c-11e6-9d33-0bf10993f4a8.png)

I did some investigation because it looked like the problem is only on my side and I found that setting short_open_tag to On in php.ini fixed those issues.
I'm just wondering, shouldn't this be in installation manual?
My PHP version is 5.3.3

**Comment by laf** [comment]
You have something absolutely crazy going on with your install - my guess is local changes.

We don't use short php tags _anywhere_ so you don't need to enable that option. I'd run git status to see what your local branch tells you.

**Comment by jmaliska** [comment]
Sorry, but I'm not aware of any local changes, I already tried clean install on Oracle Linux 6 with same result.
All pages were working without problems except the service list and add service dialog.

Git status shows:
```
[root@srv-bra-003 librenms]# git status
# On branch master
# Changed but not updated:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   html/pages/front/default.php
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       mibs/HP-LASERJET-COMMON-MIB
no changes added to commit (use "git add" and/or "git commit -a")
```

The change default.php is because of this issue https://github.com/librenms/librenms/issues/3452

**Comment by laf** [comment]
So we do have short tags :( Some have slipped in on recent PRs. I've just submitted a fix, once it's merged if you update this should be ok.
