### ISSUE TITLE
Boxes on front page shows services as down even if they are up

### ISSUE THREAD

**Issue by jmaliska** [librenms/librenms#3452]
I'm just guessing, but on page html/pages/front/default.php, line 83 there is this select:
``SELECT * FROM `services` AS S, `devices` AS D WHERE S.device_id = D.device_id AND service_status = 'down' AND D.ignore = '0' AND S.service_ignore = '0' AND `D`.`status` = '1' LIMIT ``

When I set `service_status = '2'`, the Dashboard front boxes shows only services which are really down as down, but when it is set to `service_status = 'down'` , also services which are not down are shown as down

**Comment by Rosiak** [comment]
Is this still relevant?

**Comment by laf** [comment]
I'm sure this is all sorted now

**Comment by jmaliska** [comment]
Yes it is, I still have to use my changed default.php in order to see status of services.
Attached is my changed file 
[default.zip](https://github.com/librenms/librenms/files/322141/default.zip)
