### ISSUE TITLE
Features about TRAP and Alerting widget

### ISSUE THREAD

**Issue by gcoeugnet** [librenms/librenms#3475]
Hi,

I would like first as you a question about memcached. I saw [here](http://docs.librenms.org/Extensions/Memcached/), that librenms can be used with memcached. Can you confirm that librenms doesn't support the InnoDB memcached plugin of MySQL which can be found [here](https://dev.mysql.com/doc/refman/5.6/en/innodb-memcached-setup.html) ? Our architect asked us to install this plugin to be used with libreNMS but I'm not sure this is required, regarding the way you develop your db queries...

I would like to know too if you would be interested by a timestamp of the first occurence in the Alerting Widget ? This timestamp is requested by our monitoring team, they use it today in IBM Tivoli to know since how many time a problem occured on a device. At the moment, the widget indicates the timestamp of the last alert but not the first one. I can make a pull request for this features if you agree...

To end, we saw that libreNMS supports only two traps today : linkUp and linkDown by the use of snmpd, snmptt and snmptrap.php. We would like to try to add other traps which lead to add one or more new tables in the database. How can we make this with your advices ? Do we have to propose you a DB schema to support this new traps or do we develop something by ourselves and make a pull request of the finished work ?

Thanks for reading,
Regards,
Guillaume.

**Comment by laf** [comment]
We do have memcached support but I don't recommend using it as write changes aren't shown for around 4 minutes so the webui is out of date.

With regards to that plugin, if it doesn't require any code changes then go for it. 

As for trap support, feel free to discuss what you want to do, we have an open issue about extending traps, please use that for further discussions.

**Comment by f0o** [comment]
About 2nd, have a look at the alert log page. It records all incidents.

On first, like laf indicated the built-in support does very aggressive caching. But i think your dba is not referring to that but to the mysql plugin. I'm not sure if the usage of the innodb/memcached mysql-plugin requires any special queries or not. If the plugin is transparent then LibreNMS is not bothered with its presence. Check with your dba about this.

**Comment by gcoeugnet** [comment]
Hi laf,

About TRAP, maybe you refer to [this issue](https://github.com/librenms/librenms/issues/1380). If so, I'll update it with some comments.
When you say not to use memcache, do you speak about the MySQL innoDB plugin only or even about the [memcached support](http://docs.librenms.org/Extensions/Memcached/) too ? Cause we have both of it in our servers architecture.
For the widget, there'll be a little bit of code change I think, it's not just configuration. we'll probably need to add a new column in the alerts table, a new column in the widget and a little bit of code to manage this timestamp.

Hi f0o, 

We would like to add a "first occurence timestamp" in the widget instead of parsing event log because using this way, our pilots (guys whom are in front of the alert console taking problem in charge) have the information on only one screen (widget), directly in the alert notification. They have hard Service Level Agreements and can't take times to parse event log too often.

About memcached, yes my question is about the mysql inoodb memcached plugins. I already speak about that with my DBA and he told me that if libreNMS isn't using memcached API instruction like describes [here](https://dev.mysql.com/doc/refman/5.6/en/innodb-memcached.html), the plugin is not needed. Looking inside the code, I saw SQL instructions (SELECT/UPDATE/INSERT), no memcached API ones (get/set/incr). So my conclusion is that the MySQL innoDB plugin isn't required, you seem to agree that. Regarding what laf said, I would just like you to confirm that, on the other side, memcached Extension desctribes [here ](http://docs.librenms.org/Extensions/Memcached/) is usable without any out of date things.

Thanks.

**Comment by f0o** [comment]
Heya, ok I understand 2nd more, go for it. Sounds like a good thing!

I personally use the memcached implementation of LibreNMS on most of my installs. It's worth to note that this stores almost every query made and thus changes like adding or editing alert-rules will only become apparent after the `ttl` (by default 4 minutes) pass. This is very annoying for initial setup but as you finish setting up your NMS and only keep it open to view states, alerts, graphs it will work out nicely.

You can change the ttl at wish, I have the 4 minutes for my installs and they drastically reduce SQL queries.

At the risk of repeating myself, do not ever forget about the detail that changes will only become apparent after the ttl expired. Do not attempt to spam F5 or submit multiple things as they are written in realtime but not displayed until ttl is expired. Many people have forgotten this fact and it lead to numerous inconveniences. Also the moment you hit a bug, disable memcached first and see if it persists. Do not attempt to debug while memcached is on, it will make your life considerably more painful.

**Comment by laf** [comment]
Closing - if you have further questions please create a new issue for each topic to discuss rather than one containing multiple items.

Snmp trap discussions to be done in the other open issue.
