### ISSUE TITLE
Services don't work

### ISSUE THREAD

**Issue by pcupac** [librenms/librenms#3476]
OS: CentOS release 6.7 (Final)
LibreNMS version: a7277c4
DB Schema: #107 
Apache 2.2.15 (CentOS) 
PHP 5.3.3 
MySQL 5.1.73 
RRDtool 1.3.8 

$config['show_services'] = 1;
$config['nagios_plugins'] = "/usr/lib64/nagios/plugins";

I assume that the problem in a new php code for services.  Services are entered into the database, check-services.php works perfectly, but on page services I don't have values for Device, Sevice, Changed, Message, Description. On service page I have only two buttons per service, one for insert with text 'name='edit-service> and 'name='delete-service'>.
On all pages librenms does not work with services.

**Comment by laf** [comment]
This is waiting on a PR to be merged and will be fixed.
