### ISSUE TITLE
add a cisco device and after short time a see performance graph from whole day

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#3477]
Hi !

I add a Cisco Device C880 to librenms and after a short time i see Performance graph from whole day !

How is this possible ?

the url is:

/device/device=15/tab=performance/

It sounds magic ?!

date and clock on librenms machine is ok and up to date :-)

The graph goes up and down and i see also loss a short time :-(

kind regards

kristoferus75

**Comment by laf** [comment]
I don't see how this would happen, especially device specific.

I've just added a new device here and don't experience that issue. Can you provide a screenshot and the output of view source for the page please.

**Comment by kristoferus75** [comment]
Hi !

Here the current screenshoot !

kind reagrds
![shoot](https://cloud.githubusercontent.com/assets/18415083/15011905/b94f1706-11f4-11e6-910c-25cb124a1f67.jpg)
![shoot](https://cloud.githubusercontent.com/assets/18415083/15011913/c1fcc3b2-11f4-11e6-818c-8dcd41d4d3e8.jpg)

**Comment by laf** [comment]
Your graphs at the top right show this device has been online for 24 hours as it has data.

**Comment by kristoferus75** [comment]
Hi ! Again ! now i add a new fortigate firewall and magic again a graph from last hours !
![shoot2](https://cloud.githubusercontent.com/assets/18415083/15016023/69c5860a-120f-11e6-8e3c-3249a3b549bf.jpg)

**Comment by laf** [comment]
I'm going to go out on a limb here and say the device must have been added 40 minutes before then. Please screenshot like you did before and show the traffic graphs?

**Comment by kristoferus75** [comment]
Here the traffic from the fortigate firewall from my prev post !
![shoot3](https://cloud.githubusercontent.com/assets/18415083/15019230/80b595e0-121d-11e6-8ade-3ce21c641ae3.jpg)

**Comment by kristoferus75** [comment]
Again :
![shoot4](https://cloud.githubusercontent.com/assets/18415083/15019276/ade1cc5a-121d-11e6-964c-67e8f7d8e320.jpg)

**Comment by laf** [comment]
Have you got your timezone for mysql set different from php?

There is absolutely no way data is made up to generate these graphs, it _has_ to be collected.

**Comment by kristoferus75** [comment]
Hi !

[root@librenms ~]# timedatectl
      Local time: Wed 2016-05-04 17:54:45 CEST
  Universal time: Wed 2016-05-04 15:54:45 UTC
        RTC time: Wed 2016-05-04 15:54:45
       Time zone: Europe/Vienna (CEST, +0200)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: yes
 Last DST change: DST began at
                  Sun 2016-03-27 01:59:59 CET
                  Sun 2016-03-27 03:00:00 CEST
 Next DST change: DST ends (the clock jumps one hour backwards) at
                  Sun 2016-10-30 02:59:59 CEST
                  Sun 2016-10-30 02:00:00 CET

php.ini:
date.timezone = Europe/Vienna

mysql:


SHOW GLOBAL VARIABLES LIKE 'time_zone';
+---------------+--------+
| Variable_name | Value  |
+---------------+--------+
| time_zone     | SYSTEM |
+---------------+--------+

**Comment by laf** [comment]
I've got no other suggestions.

Adding a device for me doesn't result in having any historic data.

The screenshots you've posted all seem to have different times on them so I can't see any correlation.

**Comment by geordish** [comment]
What is the output of the following SQL statements?

``` SQL
 show table status like 'devices';

 select max(device_id) from devices;
```

**Comment by laf** [comment]
Closing, no feedback for a while and still don't see this being possible
