### ISSUE TITLE
Monitor temperatures of Windows host in LibreNMS

### ISSUE THREAD

**Issue by CodaAmok** [librenms/librenms#3478]
I want to monitor temperatures of my Windows host and graph them in LibreNMS. Not much documentation about the sensors poller, I'm not 100% that's applicable to what I want to achieve. I could probably custom script the data source, is it possible to implement a custom data source into LibreNMS for it to draw onto the rrd graphs? If not, kindly nudge me in the right direction on how to get this going.

**Comment by laf** [comment]
Does windows even expose that data over snmp?

If not then you could use check_mk: https://mathias-kettner.de/checkmk_windows.html

I've not heard of anyone using this on Windows. You would then write a script to do what you want + some graphing code on our side.

**Comment by CodaAmok** [comment]
I don't really want to edit any core files of librenms as I want to keep updates as streamlined as possible, would you recommend that writing a plugin would be most appropriate to incorporate a custom data source?

**Comment by laf** [comment]
If it's available over snmp then we'd like to get support. If it's not then using check_mk is the only way which still needs graphing code adding.

**Comment by JonBaldwin** [comment]
If you have an HP or Dell server they both allow temperature monitoring via SNMP.  For HP Servers, for instance, I installed the HPE Management Agents, HPE WBEM Agent, SNMP service, SNMP WMI Integration, and HP System Management Homepage.  

No changes are needed in LibreNMS, just rediscover the server when you are done.

**Comment by CodaAmok** [comment]
Interesting, whilst SFSNMP looks dead in development there are some executables lurking around on the net. Hopefully the OIDs are unique and don't conflict, will report back if any good.

On a scale of 1-5, how complicated would you say writing your own SNMP agent would be? 1 being novice coder, 5 being fully seasoned.

**Comment by laf** [comment]
No further info provided

**Comment by XxPatrickxX** [comment]
Windows unfortunately doesn't have the capability natively.
SpeedFan with the the SNMP plugin can expose this.
1) Install SpeedFan (http://www.almico.com/sfdownload.php)
2) Install SNMP Plugin (https://wp.biesma.net/speedfan-snmp-sfsnmp)

Starting OID's
Temperature: .1.3.6.1.4.1.30503.1.5.x
Fans:        .1.3.6.1.4.1.30503.1.6.x
Voltages:    .1.3.6.1.4.1.30503.1.7.x

**Comment by alejandrombc** [comment]
I cant configure the SNMP plugin. I try to do snmpwalks to the OID's related to SpeedFan and is always empty. I am using windows 7 as a machine test.

You guys know how to correctly install the SNMP plugin for SpeedFan?.


Cheers.
