### ISSUE TITLE
Set icmp timeout per device

### ISSUE THREAD

**Issue by wiad** [librenms/librenms#3488]
Cacti has this feature and we've had to use it with some of our devices before we moved to librenms. There is a global setting:
`['fping_options']['timeout']`

But it would be nice to be able to set this per device, as you can with snmp timeout.

**Comment by Rosiak** [comment]
Hi,

We are cleaning up the issues here on GitHub, all feature requests will be moved to:
https://community.librenms.org/c/feature-requests

Hence the closure of this issue.

**Comment by VictorJ76** [comment]
The feature was integrated ? I didnt found info in documentations.
