### ISSUE TITLE
FTOS s60 support !!

### ISSUE THREAD

**Issue by shahzaibcb** [librenms/librenms#3491]
we've recently deployed dell FTOS s60 as snmp agent but cpu / memory is not being monitored by librenms, for that we need custom mibs provided by dell. How can we enable these custom mibs for s60 in librenms ?

**Comment by laf** [comment]
Do you have or where can we find the mibs?

**Comment by shahzaibcb** [comment]
Hi laf,

You can find .tar / .zip mibs for all series in mentioned below link. In our case it would be s60 and s50.

https://www.force10networks.com/CSPortal20/KnowledgeBase/Documentation.aspx

**Comment by Rosiak** [comment]
Can you please provide a snmpwalk of the f10-chassis mib?

**Comment by shahzaibcb** [comment]
Can you please provide me command to run snmpwalk on ft10-chassis-mib ? I've used built-in snmps all the time, so no expertise with custom run :(

**Comment by laf** [comment]
https://github.com/librenms/librenms/issues/new That has the commands of the info we need.
