### ISSUE TITLE
API get_graph_generic_by_hostname bug

### ISSUE THREAD

**Issue by pheinrichs** [librenms/librenms#3493]
get_graph_generic_by_hostname seems to only work with hostname, Doesn't output anything when using device_id.

**Comment by f0o** [comment]
Don't think it's a bug, the method states `by_hostname`.

**Comment by pheinrichs** [comment]
@f0o ok, should we create another function for this and or change the docs?
"hostname can be either the device hostname or id" this is in our API docs

**Comment by f0o** [comment]
To be honest I think it's better to introduce `..._by_id` methods.

@laf: what do you say?

**Comment by laf** [comment]
I'd say merge. It's the function name that's not right :( originally all Api calls were via HOSTNAME but blahdeblah added by Id later on.

**Comment by f0o** [comment]
OK, remove blocker :)
