### ISSUE TITLE
Oxidized support when Librenms is running ssl cacerts

### ISSUE THREAD

**Issue by brokerdavelhr** [librenms/librenms#3500]
So I have librenms to run using https - and of course to do so I had to create and use valid cacerts. This works flawlessly and I have had 0 issues. 
However when I added oxidized, and tried to integrate it, I got this:
I, [2016-05-05T11:53:32.590679 #95960]  INFO -- : Oxidized starting, running as pid 95960
F, [2016-05-05T11:53:32.625129 #95960] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized/crash
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

I have tried re-installing the certs, etc but to no avail. 

I am using: 
ubuntu14.04 LTE Trusty
Ruby and ruby-dev 2.1
apache2.47
mysql-server 5.5
all gems updated

I already have this posted on the Oxidized thread - just hoping someone here may have already encountered this before.

**Comment by murrant** [comment]
If Oxidized is on the same machine, I recommend you bind oxidized to the localhost.
```
rest: 127.0.0.1:8888
```
Then set that url in config.php
```
$config['oxidized']['url']  = "http://127.0.0.1:8888";
```

I am also using nginx reverse proxy to access that site from other machines, secured by ssl.

**Comment by brokerdavelhr** [comment]
It has been set that way since the beginning - same thing. 
It is a conflict of oxidized trying to use the wrong ssl certs
In apache:
  SSLCertificateFile /etc/ssl/certs/cacert.pem
  SSLCertificateKeyFile /etc/ssl/private/cakey.pem

Not sure where oxidized looks it up at. Will go through the oxidized files and see if I can find it.

**Comment by murrant** [comment]
Are you using ssl to connect to librenms?
Like this?
```
  http:
    url: https://librenms.domain/api/v0/oxidized
    scheme: https
```

Or are you using an IP?  You must use the domain name for the SSL cert to be valid (unless the IP is on your SSL cert)

You can add an entry to hosts to make that name point to 127.0.0.1 if they are on the same machine.

**Comment by brokerdavelhr** [comment]
Murrant - user error - got it!

Thanks for your help!

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/api-not-working-locally-or-remote-via-curl/11093/4
