### ISSUE TITLE
Services "Missing"

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#3501]
Hi,

Ever since I upgraded my Linux box to Ubuntu 16.04 LTS, I have noticed that the Top-devices widget is empty, and now I noticed that my services list is empty ... even though I can "see" them in my Availability-map widget.

Thoughts? Things to check?

Nope, my MySQL server is not set for strict ... ;). It was, but I changed this to correct other issues.

Thanks!

**Comment by murrant** [comment]
What are the results of `./validate.php` in your librenms directory?

**Comment by arrmo** [comment]
Nothing very exciting - below (and yes, I ran chown ... doesn't fix it. Seems to get messed up on daily updates).

Version info:
Commit SHA: 857f3d68ef2454f52f9c5bfa11124fdec5fc4ede
[WARN]    Your local git contains modified files, this could prevent automatic updates.
Modified files:
html/.htaccess
includes/discovery/os/lenovoemc.inc.php
DB Schema: 114
PHP: 7.0.4-7ubuntu2
MySQL: 5.7.12-0ubuntu1
RRDTool: 1.5.5
SNMP: NET-SNMP version: 5.7.3

[FAIL]    We have found some files that are owned by a different user than librenms, this will stop you updating automatically and / or rrd files being updated causing graphs to fail:
If you don't run a bespoke install then you can fix this by running `chown -R librenms:librenms /opt/librenms`
/opt/librenms/.git/index

[OK]      Database connection successful

Thoughts?

Thanks!

**Comment by laf** [comment]
Add /debug=true/ to the services page and paste the sql and php output onto pastebin or similar.

The only way permissions change is running anything as non-librenms user. Daily updates don't and can't update permissions. Check your cron to make sure that everything is running as the correct user.

**Comment by arrmo** [comment]
You bet! Here you go,
1) SQL, http://pastebin.ubuntu.com/16263233/
2) PHP: http://pastebin.ubuntu.com/16263252/

And on the crontab, it's running as root (the default, no?).

Thanks!

**Comment by laf** [comment]
What's the output of: `SELECT * FROM devices AS D, services AS S WHERE D.device_id = S.device_id GROUP BY D.hostname ORDER BY D.hostname`

**Comment by arrmo** [comment]
It's an error message ... ;). Below,

ERROR 1055 (42000): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'librenms.D.device_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

Thanks!

**Comment by laf** [comment]
I'm unsure why we aren't picking up your sql_mode in validate.php but we highly recommend still disabling sql strict mode.

**Comment by arrmo** [comment]
Hi,

Hmmm .. I did disable this, right after the upgrade. Or at least I think I did ... ;). Here is what I see - strict mode is off, no?

mysql> SELECT @@GLOBAL.sql_mode;
+-----------------------------------------------------------------------------------------------------------------------+
| @@GLOBAL.sql_mode                                                                                                     |
+-----------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-----------------------------------------------------------------------------------------------------------------------+

Thanks!

**Comment by f0o** [comment]
Afaik sql_mode should be empty. I will check with our galera cluster in a bit.

On 8 May 2016 19:04:34 CEST, arrmo <notifications@github.com> wrote:
>Hi,
>
>Hmmm .. I did disable this, right after the upgrade. Or at least I
>think I did ... ;). Here is what I see - strict mode is off, no?
>
>mysql> SELECT @@GLOBAL.sql_mode;
>+-----------------------------------------------------------------------------------------------------------------------+
>| @@GLOBAL.sql_mode                                                    
>                                                |
>+-----------------------------------------------------------------------------------------------------------------------+
>|
>ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
>|
>+-----------------------------------------------------------------------------------------------------------------------+
>
>Thanks!
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/3501#issuecomment-217733209

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by f0o** [comment]
We only got: NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

On 8 May 2016 19:04:34 CEST, arrmo <notifications@github.com> wrote:
>Hi,
>
>Hmmm .. I did disable this, right after the upgrade. Or at least I
>think I did ... ;). Here is what I see - strict mode is off, no?
>
>mysql> SELECT @@GLOBAL.sql_mode;
>+-----------------------------------------------------------------------------------------------------------------------+
>| @@GLOBAL.sql_mode                                                    
>                                                |
>+-----------------------------------------------------------------------------------------------------------------------+
>|
>ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
>|
>+-----------------------------------------------------------------------------------------------------------------------+
>
>Thanks!
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/3501#issuecomment-217733209

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by laf** [comment]
Yup, needs to be off completely.

**Comment by arrmo** [comment]
That works - thanks guys! Seems the upgrade to Ubuntu 16.04 changed some of this (when MySQL was upgraded). I took out part of the strict mode, but I admit - I wasn't sure what all needed to be removed. It may be good to note this somewhere for folks.

Thanks again!

**Comment by laf** [comment]
It's in our install docs :)

**Comment by arrmo** [comment]
Sorry! I did go through them, obviously missed it - my fault!
