### ISSUE TITLE
Add graphing for Junos SRX Firewall session objects

### ISSUE THREAD

**Issue by pblasquez** [librenms/librenms#3502]
I would like to be able to graph the following mib tree:

snmpwalk -v2c -c community host.name .1.3.6.1.4.1.2636.3.39.1.12.1.1.1
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.2.0 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.2.18 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.3.0 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.3.18 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.4.0 = Gauge32: 15
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.4.18 = Gauge32: 4
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.5.0 = Gauge32: 75
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.5.18 = Gauge32: 75
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.6.0 = Gauge32: 293217
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.6.18 = Gauge32: 304086
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.7.0 = Gauge32: 524288
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.7.18 = Gauge32: 524288
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.8.0 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.8.18 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.9.0 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.9.18 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.10.0 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.10.18 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.11.0 = STRING: "node0"
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.11.18 = STRING: "node1"
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.12.0 = Gauge32: 293217
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.12.18 = Gauge32: 304086
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.13.0 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.13.18 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.14.0 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.14.18 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.15.0 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.39.1.12.1.1.1.15.18 = Gauge32: 0

Mapped from the Junos command:

show snmp mib walk decimal .1.3.6.1.4.1.2636.3.39.1.12.1.1.1
jnxJsSPUMonitoringFPCIndex.0 = 0
jnxJsSPUMonitoringFPCIndex.18 = 0
jnxJsSPUMonitoringSPUIndex.0 = 0
jnxJsSPUMonitoringSPUIndex.18 = 0
jnxJsSPUMonitoringCPUUsage.0 = 22
jnxJsSPUMonitoringCPUUsage.18 = 6
jnxJsSPUMonitoringMemoryUsage.0 = 75
jnxJsSPUMonitoringMemoryUsage.18 = 75
jnxJsSPUMonitoringCurrentFlowSession.0 = 319087
jnxJsSPUMonitoringCurrentFlowSession.18 = 326950
jnxJsSPUMonitoringMaxFlowSession.0 = 524288
jnxJsSPUMonitoringMaxFlowSession.18 = 524288
jnxJsSPUMonitoringCurrentCPSession.0 = 0
jnxJsSPUMonitoringCurrentCPSession.18 = 0
jnxJsSPUMonitoringMaxCPSession.0 = 0
jnxJsSPUMonitoringMaxCPSession.18 = 0
jnxJsSPUMonitoringNodeIndex.0 = 0
jnxJsSPUMonitoringNodeIndex.18 = 1
jnxJsSPUMonitoringNodeDescr.0 = node0
jnxJsSPUMonitoringNodeDescr.18 = node1
jnxJsSPUMonitoringFlowSessIPv4.0 = 319087
jnxJsSPUMonitoringFlowSessIPv4.18 = 326950
jnxJsSPUMonitoringFlowSessIPv6.0 = 0
jnxJsSPUMonitoringFlowSessIPv6.18 = 0
jnxJsSPUMonitoringCPSessIPv4.0 = 0
jnxJsSPUMonitoringCPSessIPv4.18 = 0
jnxJsSPUMonitoringCPSessIPv6.0 = 0
jnxJsSPUMonitoringCPSessIPv6.18 = 0

**Comment by asteen-nexcess** [comment]
Was this ever added? Thanks!

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-add-graphing-for-junos-srx-firewall-session-objects/721

**Comment by laf** [comment]
Has now been implemented. https://github.com/librenms/librenms/pull/8815#pullrequestreview-128546272
