### ISSUE TITLE
SNMP PHP module support check is outdated

### ISSUE THREAD

**Issue by jean-christophe-manciot** [librenms/librenms#3503]
Ubuntu 16.04 4.4.0-21
librenms commit 857f3d68ef2454f52f9c5bfa11124fdec5fc4ede

Accessing https://librenms.actionmystique.net/install.php:
![php-snmp dependency issue](https://cloud.githubusercontent.com/assets/13176858/15073051/80e2debc-1397-11e6-914c-52b100c94c86.png)
However, **php5-snmp has been replaced by php7.0-snmp**:

- Do you plan on relaxing the dependencies requirements?
- or do I have to create a dummy transitional package php5-snmp depending on the last one?
- or is it impossible to use librenms on the latest Ubuntu distribution because php7.0-snmp would be too fresh?

**Comment by f0o** [comment]
In order:
- yes, php-snmp should be removed
- no, only the UI requires the checks, CLI install will still work
- no, php7 works in my install nicely

**Comment by f0o** [comment]
Update: php7.0-snmp should be fulfilling the dependency. Do you have it installed?

**Comment by jean-christophe-manciot** [comment]
Yes, php7.0-snmp is installed on my system & I cannot pass the first page of GUI installation.

**Comment by f0o** [comment]
Did you by chances installed it after Apache/FPM/CGI has been started? If so you need to restart Apache/FPM/CGI services in order to be active.

**Comment by jean-christophe-manciot** [comment]
Yes.
I performed a:
```
sudo systemctl restart apache2
```
and I am now able to pass the first screen. 
I don't know what you mean by restarting "FPM/CGI". There are no such services here. Maybe they are implemented with different service names.

**Comment by f0o** [comment]
Apache - or - FPM - or - CGI is what I meant :)

Glad it's resolved

**Comment by jean-christophe-manciot** [comment]
:-)
