### ISSUE TITLE
[WARNING] Cannot execute query: Invalid default value for 'datetime'

### ISSUE THREAD

**Issue by jean-christophe-manciot** [librenms/librenms#3504]
Ubuntu 16.04 4.4.0-21
LibreNMS commit 857f3d68ef2454f52f9c5bfa11124fdec5fc4ede
![warning at step 18 in 2nd screen of installation](https://cloud.githubusercontent.com/assets/13176858/15074416/2bbc1676-139f-11e6-8f45-61148e6efc0b.png)
Is that warning at step #18 in the 2nd screen of the installation "Importing MySQL DB" an issue?

**Comment by f0o** [comment]
Please disable MySQL Strict-Mode

**Comment by jean-christophe-manciot** [comment]
OK, but then I suggest you modify your [documentation](http://docs.librenms.org/Installation/Installation-(Debian-Ubuntu)/) which states:
```
If you see a line that starts sql-mode then change this to sql-mode="".
```
There was nothing about "sql-mode" in /etc/mysql/my.cnf, so I supposed it was the default mode.
Adding the line & restarting mysql removes the warning indeed.

**Comment by laf** [comment]
Our docs are open source - you can edit and submit pull requests :)

**Comment by laf** [comment]
updated docs have been PR'd.

**Comment by infotek** [comment]
I also had this issue on ubuntu 16 LTS.  Clarification in the docs may be a good idea.

**Comment by laf** [comment]
The docs are explicit on this for 16.04: http://docs.librenms.org/Installation/Installation-Ubuntu-1604-Apache/#install-configure-mysql
