### ISSUE TITLE
Add support for returning IP addresses w/ ports in the API

### ISSUE THREAD

**Issue by jackson-tim** [librenms/librenms#3505]
Please add support for returning all IP addresses+netmasks for devices when you query ports via the API...

e.g. under:
http://librenms/api/v0/devices/3/ports?columns=*

**Comment by jackson-tim** [comment]
It may be just this easy:

Line 712 in api_functions.inc.php:
`
    // use hostname as device_id if it's all digits
    $device_id   = ctype_digit($hostname) ? $hostname : getidbyname($hostname);
    $ports       = dbFetchRows("SELECT $columns FROM `ports` LEFT JOIN `ipv4_addresses` ON `ports`.`port_id`=`ipv4_addresses`.`port_id` WHERE `device_id` = ? AND `deleted` = '0' ORDER BY `ifIndex` ASC", array($device_id));
`

**Comment by laf** [comment]
Support for this was merged in http://docs.librenms.org/API/API-Docs/#api-route-get_device_ip_addresses.
