### ISSUE TITLE
Availability Map Tile width issues

### ISSUE THREAD

**Issue by murrant** [librenms/librenms#3506]
- Tile width does not seem to save, all the time.  Try setting it multiple times in a row without refreshing the page.
- If you try to set it to the same value, I get an alert saying "ERROR: Could not update" .

@BeryJu

**Comment by BeryJu** [comment]
Will look into it, thanks!

**Comment by f0o** [comment]
Cannot reproduce, works here :S

**Comment by murrant** [comment]
https://youtu.be/kBEelT3rmE8

**Comment by murrant** [comment]
I can't reproduce this anywhere except my production server.
