### ISSUE TITLE
Eaton UPS shows up as generic

### ISSUE THREAD

**Issue by GarlandM** [librenms/librenms#3508]
Eaton 5P 2200 shows up as generic, no info given.

Discovery.php - http://pastebin.com/s1LRY2ME
poller.php - http://pastebin.com/mq2ApYsx

**Comment by oam7575** [comment]
@GarlandM 

Possibly a duplicate of my bug : https://github.com/librenms/librenms/issues/3364

Try adjusting /opt/librenms/includes/discovery/os/eatonups.inc.php as per my issue and see if you have any more luck.

After adjusting rerun your discovery and poller tasks as configured in Cron or wait a few mins.

**Comment by GarlandM** [comment]
I'll give that a try, but it's a brand new UPS (new production)

**Comment by oam7575** [comment]
@GarlandM 

My understanding is that Observium have added support for devices since LibreNMS forked many years ago.

Best bet is to test and feedback for the improvement of LibreNMS

**Comment by oam7575** [comment]
I have been hacking away a little and think I have the detection for low end Eaton 5P / 5PX devices working a bit better.

my fork is here : https://github.com/oam7575/librenms

I will be updating my ticket with a pull request and see what happens.

**Comment by Rosiak** [comment]
Tagging #3572

**Comment by Rosiak** [comment]
Any news?

**Comment by engageant** [comment]
Chiming in to say I'm running into this too on my new Eaton 5P.

**Comment by Rosiak** [comment]
@oam7575 Any news?
