### ISSUE TITLE
Polling a Juniper EX2200 taking an excessive amount of time

### ISSUE THREAD

**Issue by tfgm-bud** [librenms/librenms#3511]
I have several 24 port EX2200 switches that seem to take an excessive amount of time to poll (i.e. 80 seconds).  

The switches themselves do not appear to be overloaded - the routing engine shows 5 to 6% usage.

Switches running JunOS 11.4R9.4.

As a data point, Observium is polling them in about 25 seconds.

**Comment by tfgm-bud** [comment]
One thing that seems a little odd.  When I run:

```
./poller.php -r -f -d -h host -m ports
```
It seem to take quite a while to do:
```
Caching Oids: ifEntry /usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs  -m IF-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 ifEntry
```
Then after that, it seems to do the walk again and it takes a while again:

```
ifXEntry /usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs  -m IF-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 ifXEntry
```
Also, not sure how long the Oids are supposed to be cached -- but ideally they would be cached between runs -- but it seems like every time the poller runs it has to retrieve them.

**Comment by oam7575** [comment]
This issue : https://github.com/librenms/librenms/issues/2017

has some comments relating to an EX4550 with some port flapping.
Fixing the port flapping and disabling unneeded snmp modules appeared to improve the situation somewhat.

**Comment by tfgm-bud** [comment]
@oam7575, I don't think that issue is related.  In https://github.com/librenms/librenms/issues/2017#issuecomment-149456036, @tobiasa1 mentions that the flapping device was causing high cpu usage.  I'm not experiencing any flapping ports or high cpu usage.

**Comment by pblasquez** [comment]
FWIW, I also see high poll times on the Junos SRX platform, with similar comparisons to observium.

Would be interesting to see if we could replicate the optimization you identified.

**Comment by laf** [comment]
I've removed the links and reference to observium.

**Comment by tfgm-bud** [comment]
@laf sorry about that -- didn't know.

@pblasquez, my SRX220 is relatively slow to poll too but since it only has 8 ports, it only takes about 22 seconds to poll.

**Comment by paulgear** [comment]
I have an EX2200C and it doesn't seem to have many dramas polling.  Happy to compare settings if you like.

**Comment by tobiasa1** [comment]
Hi,

@paulgear I think you need at least 300-400 ports to get over the 300 sec polling interval which causes troubles. I compare with my other EX4550 stack with 200 ports that has a polling time of 161.50 seconds.

We need to decrease per port polling time in some way.

**Comment by laf** [comment]
Some improvements were merged a while ago for polling ports speed improvements. Please update and try again.

http://docs.librenms.org/Support/Performance/ may also offer some help.
