### ISSUE TITLE
Services do not recover from Alert

### ISSUE THREAD

**Issue by air101** [librenms/librenms#3512]
Hello LibreNMS Supporter,

I added a few services with nagios-plugins check. The Services show status green but the failed service from 2-3 days ago does not recover itself. How do I fix this?

Alert Rule: 	%services.service_status = "0" 

System is latest Debian 8

Thank you and best regards

**Comment by f0o** [comment]
The state values changed. 0 means now OK whereas anything else means error (1), warning (2), unknown (3) as far as I remember

On 10 May 2016 07:51:09 CEST, air101 <notifications@github.com> wrote:
>Hello LibreNMS Supporter,
>
>I added a few services with nagios-plugins check. The Services show
>status green but the failed service from 2-3 days ago does not recover
>itself. How do I fix this?
>
>Alert Rule: 	%services.service_status = "0" 
>
>System is latest Debian 8
>
>Thank you and best regards
>
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/3512

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by air101** [comment]
Ah okay. Thanks it works now!
