### ISSUE TITLE
Windows Server Freespace shows 0%

### ISSUE THREAD

**Issue by air101** [librenms/librenms#3513]
Hello LibreNMS Support again,

on some Windows Servers (Server 2008 R2) the freespace on some hdds show 0%. Sometimes it is displayed correctly but sometimes it just says 0% free. The Rest of the server looks fine (traffic, cpu, etc)

**Comment by Mattz0r** [comment]
@air101 Do you have any more details, such as logs from the polling output? Further information will be needed in order to provide assistance/find out the cause.

**Comment by air101** [comment]
Sure,

attached is the poller of the device.

In [hrstorage] => Array the size is right, but when it does the sql query, the results are 0.

[sb.txt](https://github.com/librenms/librenms/files/260693/sb.txt)

**Comment by air101** [comment]
Hello,

the problem just exists when the job is run via cronjob. If I do a manual poller: ./poller.php -h hostname then the correct value is read and set. (Storage C:\\ Label:  Serial Number fe18f238: 42%)

**Comment by air101** [comment]
Hello,

any update here? Or do you need more information?

Thanks!

**Comment by laf** [comment]
Please post the output of:

`./poller.php -h HOSTNAME -d -r -f -m storage`

**Comment by laf** [comment]
No further information provided.
