### ISSUE TITLE
Add APP support for NSD, KNOT and More Bind graphs

### ISSUE THREAD

**Issue by akhiq** [librenms/librenms#3517]
Hi,

Can you please have a look at adding support for NSD and KNOT dns servers stats. NSD can export stats in Bind format actually.

Also, why is Bind stats page only shows a single query graph for types of queries stats?, the stats file that it pulls from has much more zone specific details that will be great to see in graphs as well.

Many thanks for your great work by the way,

Regards,
Kareem.

**Comment by Rosiak** [comment]
Hi,

We are cleaning up the issues here on GitHub, all feature requests will be moved to:
https://community.librenms.org/c/feature-requests

Hence the closure of this issue.
