### ISSUE TITLE
Dell N1500 Series Interface Names

### ISSUE THREAD

**Issue by asteen-nexcess** [librenms/librenms#3520]
Is there anyway to rename the interface names coming up under the N1500 series switches?

For example:

_Unit: 1 Slot: 0 Port: 1 Gigabit - Level_ should be Gi1/0/1

Thanks!

**Comment by cschoonover91** [comment]
What OS are they being detected as? DNOS? If so, try adding this to config.php.

# Fix DNOS port names in LibreNMS
$config['os']['dnos']['ifname'] = 1;

**Comment by asteen-nexcess** [comment]
That worked! Thanks!
