### ISSUE TITLE
Support for HP 3PAR

### ISSUE THREAD

**Issue by KieronG** [librenms/librenms#3521]
Hi 

Are there any plans for supporting HP 3Par storage in librenms?

**Comment by f0o** [comment]
Well not plans but if you got a list of mixing features for it and a device we can test against somebody will pick it up :)

**Comment by Rosiak** [comment]
What @f0o said.
@KieronG are you able to supply any information?

Otherwise this issue will be closed.

**Comment by KieronG** [comment]
I can provide the what you need. I'll put it together

**Comment by KieronG** [comment]
Here are the pastbins, let me know if you need anything else.

./discovery.php -h HOSTNAME -d -m os
http://pastebin.com/zWmfWuCD

./poller.php -h HOSTNAME -r -f -d -m os
http://pastebin.com/dFG2m61H

snmpbulkwalk -v2c -c COMMUNITY HOSTNAME 
http://pastebin.com/AaHdW2Pa

**Comment by Rosiak** [comment]
I'll look into it, can you please provide a full snmpwalk?
Try like this:
snmpbulkwalk -v2c -c COMMUNITY HOSTNAME .

**Comment by KieronG** [comment]
the pastebin contains all the text from the snmpwalk
http://pastebin.com/AaHdW2Pa

**Comment by Rosiak** [comment]
@KieronG - Please note the dot in my last comment, after the hostname.

snmpbulkwalk -v2c -c COMMUNITY HOSTNAME .

**Comment by KieronG** [comment]
here you go
http://pastebin.com/uRCj4WsN
