### ISSUE TITLE
Get Parent API

### ISSUE THREAD

**Issue by djtecha** [librenms/librenms#3523]
Currently there is a link on a VM page to send you to the parent KVM machine. It would be sweet to be able to return this information in the get device info api command. Basically, a new key value pair like so:

{
    "status": "ok",
    "devices": [
        {
            "device_id": "2",
            "hostname": "test-1",
            "sysName": "test-1",
            "ip": "10.0.11.131",
            "parent": "test-kvm-1",
        }
    ]
}

**Comment by laf** [comment]
Just been looking at this and we don't list the vm's in list_devices.

Can you show a screenshot of where this link is?

**Comment by laf** [comment]
No further information provided. Closing

**Comment by djtecha** [comment]
Sorry about the delay.
![screenshot from 2016-12-12 10-37-20](https://cloud.githubusercontent.com/assets/3084627/21111720/bad68f52-c057-11e6-998a-0b3b96906488.png)
![screenshot from 2016-12-12 10-37-46](https://cloud.githubusercontent.com/assets/3084627/21111721/bae6069e-c057-11e6-80f1-cfc025c7f44a.png)
