### ISSUE TITLE
Traffic Bills Summary Inbound/Outbound show zero

### ISSUE THREAD

**Issue by dragon2611** [librenms/librenms#3524]
The Current billing period in the traffic bills summary does not show anything for inbound/outbound however if you select the previous billing period the data is populated suggesting it was recorded in the DB.

![current-bill](https://cloud.githubusercontent.com/assets/6185399/15273668/126f7e96-1a99-11e6-835f-4fa4192e7e05.png)
![prev-bill](https://cloud.githubusercontent.com/assets/6185399/15273667/126efad4-1a99-11e6-87d1-3e7bcb460955.png)

**Comment by f0o** [comment]
Cant reproduce :S

**Comment by Mattz0r** [comment]
I'm seeing the same here....

Only happening for ones with a quota though...

![image](https://cloud.githubusercontent.com/assets/2264823/15521225/7e6adfa8-2202-11e6-9bf0-a17628306350.png)

**Comment by dragon2611** [comment]
@f0o I'm usually around on IRC, if you want me to do anything with my installation to help narrow things down give me a prod.

**Comment by f0o** [comment]
I'll check my install after lunch but i can't recall this issue really...

Which schema and commit are you two running?

**Comment by dragon2611** [comment]
:/opt/librenms# git log -1
commit 39fe65ef94a8d3a9023cd405540c74c7aa92a8ba

How do I confirm the Schema version, it should be the current one for that commit but it's possible one of them failed and I didn't notice (I usually just run daily.sh to update)

**Comment by Mattz0r** [comment]
@dragon2611 - You can go to "About Librenms" within your install, which will tell you the commit and schema.

@f0o - I'll check later.

**Comment by f0o** [comment]
Actually I can reproduce this issue on my install now...

**Comment by Mattz0r** [comment]
Okay cool,

Version	39fe65e
DB Schema	#114
Apache	nginx/1.0.15
PHP	5.4.45
MySQL	5.5.45
RRDtool	1.4.7

My environment, just in case you need it.

**Comment by laf** [comment]
Is this still an issue, a lot of work has been done and I'm sure this was resolved.

**Comment by dragon2611** [comment]
It's still showing 0 for in and out on mine under the current month but that could be my install.

**Comment by laf** [comment]
I've just set things up on my home install and don't see this :(

**Comment by Mattz0r** [comment]
Yep, still seeing this! I'm on Version 39fe65e and DB Scheme 115

PHP 5.4.45
MySQL 5.5.45

Not sure if you need any other information?

**Comment by SirMaple** [comment]
I'm also seeing 0 for Inbound and Outbound columns on Quotes only . CDR's are showing correctly.

Commit d1ae83a378a6016a6619f6f13d49209334baf2c0
DB Schema	#132
Apache	2.4.7 (Ubuntu)
PHP	5.5.9-1ubuntu4.19
MySQL	5.5.50-0ubuntu0.14.04.1
RRDtool	1.4.7

Need anymore details about my setup let me know.

**Comment by tobiasa1** [comment]
I've seen this issue as well on some graphs (both CDR and quota).
