### ISSUE TITLE
Notifications not sent after an alert is "unacknowledged"

### ISSUE THREAD

**Issue by tfgm-bud** [librenms/librenms#3526]
When you "ack" an alert in the GUI, a notification is sent that clears the "open" field in the alerts table.

https://github.com/librenms/librenms/blob/master/alerts.php#L157

Later, if you unacknowledge the alert in the GUI, you will not receive followup alert notifications for the alert due to "open" remaining false:

https://github.com/librenms/librenms/blob/master/alerts.php#L169

**Comment by f0o** [comment]
Yeah thats a bug, I will try to form a PR today after dinner

**Comment by f0o** [comment]
This should be fixed now

**Comment by budbach** [comment]
Thanksl
