### ISSUE TITLE
Cisco SMB switches with detection errors

### ISSUE THREAD

**Issue by flatterlight** [librenms/librenms#3529]
I've i.a. 2 Cisco SMB switches monitored by librenms, which are both shown with the same (SG500-28) Platform type/Hardware.
The snmpwalk to both devices, show the following output for the sysDescr. 
`SNMPv2-MIB::sysDescr.0 = STRING: SG500-28 28-Port Gigabit Stackable Managed Switch`
`SNMPv2-MIB::sysDescr.0 = STRING: 26-Port Gigabit Smart Plus Switch`
 
System:
Version: a063d24
DB Schema: #83
Apache: 2.4.6 (CentOS) PHP/5.4.16
PHP: 5.4.16
MySQL: 5.5.47-MariaDB-log
RRDtool: 1.4.8

If more info is needed feel free to ask for it.

**Comment by laf** [comment]
When creating an issue it prompts you for information we need, please provide this.

**Comment by flatterlight** [comment]
`./discovery.php -h HOSTNAME -d -m os`
device1: http://pastebin.com/yeTXkS5c
device2: http://pastebin.com/nUdStmDg
`./poller.php -h HOSTNAME -r -f -d -m os`
device1: http://pastebin.com/qgLEQa2h
device2: http://pastebin.com/fNy4Ww5q
`snmpbulkwalk -v2c -c COMMUNITY HOSTNAME`
device 1: http://pastebin.com/yyU6SzrQ
device 2: http://pastebin.com/qByWnJ8b <- parts

**Comment by laf** [comment]
The poller and discovery outputs contains zero information, you are using the correct hostname in the command aren't you? HOSTNAME is just a place holder.

**Comment by flatterlight** [comment]
I replaced the HOSTNAME with the respective hostnames (one after the other) for the two devices, but with the FQDN, I work with shortnames... my bad

./discovery.php -h HOSTNAME -d -m os
device1: http://pastebin.com/Gjx1Vjc2
device2: http://pastebin.com/JL6QyuQF
./poller.php -h HOSTNAME -r -f -d -m os
device1: http://pastebin.com/uaexCXT2
device2: http://pastebin.com/HCXMDGMy

**Comment by Rosiak** [comment]
I suggest you update your installation and try again, since the code intended for the discovery is already in place.

**Comment by flatterlight** [comment]
I updated my installation to Version	: ebcbd18; DB Schema: #114 and rediscovered the devices. 
The problem still exists.

**Comment by Rosiak** [comment]
@librenms/reviewers Any ideas?

**Comment by laf** [comment]
Will need the fresh polling/discovery debug now install is updated.

**Comment by flatterlight** [comment]
new input as required
./discovery.php -h HOSTNAME -d -m os
device1: http://pastebin.com/BERsAuEW
device2: http://pastebin.com/3chXydKx
./poller.php -h HOSTNAME -r -f -d -m os
device1: http://pastebin.com/FJF3Sh0k
device2: http://pastebin.com/ccTcvhEL
