### ISSUE TITLE
Poller Module Performance rrd does not exist

### ISSUE THREAD

**Issue by Linutux42** [librenms/librenms#3532]
Hi,

Here is an issue I found on my LibreNMS Installation.
I talk about it with Laf on IRC and he told me to post an issue.

Here's the information I can give you : 

-----------------------------------------------------------------------------
Validate :
Version info:
Commit SHA: ebcbd1815d6cb659e099f2e0a046589040062f13
DB Schema: 114
PHP: 5.6.20-0+deb8u1
MySQL: 5.5.47-0+deb8u1
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2.1

[OK]      Database connection successful

------------------------------------------------------------------------------
RRDTool Command
rrdtool graph /tmp/8Ad1xLFMVrMriAa7.png -l 0 -E --start 1463483400 --end 1463569800 --width 1899.9 --height 520.5 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal -l 0 -E --start 1463483400 --end 1463569800 --width 1899.9 --height 520.5 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal COMMENT:'Second... Now Min Max Avg\l' COMMENT:'\l' DEF:0=::AVERAGE DEF:0min=::MIN DEF:0max=::MAX AREA:0#FFF8A3:' ' GPRINT:0:LAST:%5.2lf%s GPRINT:0min:MIN:%5.2lf%s GPRINT:0max:MAX:%5.2lf%s GPRINT:0:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:1=::AVERAGE DEF:1min=::MIN DEF:1max=::MAX AREA:1#FAE16B:' ':STACK GPRINT:1:LAST:%5.2lf%s GPRINT:1min:MIN:%5.2lf%s GPRINT:1max:MAX:%5.2lf%s GPRINT:1:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:2=::AVERAGE DEF:2min=::MIN DEF:2max=::MAX AREA:2#F8D753:' ':STACK GPRINT:2:LAST:%5.2lf%s GPRINT:2min:MIN:%5.2lf%s GPRINT:2max:MAX:%5.2lf%s GPRINT:2:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:3=::AVERAGE DEF:3min=::MIN DEF:3max=::MAX AREA:3#F3C01C:' ':STACK GPRINT:3:LAST:%5.2lf%s GPRINT:3min:MIN:%5.2lf%s GPRINT:3max:MAX:%5.2lf%s GPRINT:3:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:4=::AVERAGE DEF:4min=::MIN DEF:4max=::MAX AREA:4#F0B400:' ':STACK GPRINT:4:LAST:%5.2lf%s GPRINT:4min:MIN:%5.2lf%s GPRINT:4max:MAX:%5.2lf%s GPRINT:4:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:5=::AVERAGE DEF:5min=::MIN DEF:5max=::MAX AREA:5#A9CC8F:' ':STACK GPRINT:5:LAST:%5.2lf%s GPRINT:5min:MIN:%5.2lf%s GPRINT:5max:MAX:%5.2lf%s GPRINT:5:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:6=::AVERAGE DEF:6min=::MIN DEF:6max=::MAX AREA:6#82B16A:' ':STACK GPRINT:6:LAST:%5.2lf%s GPRINT:6min:MIN:%5.2lf%s GPRINT:6max:MAX:%5.2lf%s GPRINT:6:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:7=::AVERAGE DEF:7min=::MIN DEF:7max=::MAX AREA:7#5C9746:' ':STACK GPRINT:7:LAST:%5.2lf%s GPRINT:7min:MIN:%5.2lf%s GPRINT:7max:MAX:%5.2lf%s GPRINT:7:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:8=::AVERAGE DEF:8min=::MIN DEF:8max=::MAX AREA:8#3D8128:' ':STACK GPRINT:8:LAST:%5.2lf%s GPRINT:8min:MIN:%5.2lf%s GPRINT:8max:MAX:%5.2lf%s GPRINT:8:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:9=::AVERAGE DEF:9min=::MIN DEF:9max=::MAX AREA:9#1E6C0B:' ':STACK GPRINT:9:LAST:%5.2lf%s GPRINT:9min:MIN:%5.2lf%s GPRINT:9max:MAX:%5.2lf%s GPRINT:9:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:10=::AVERAGE DEF:10min=::MIN DEF:10max=::MAX AREA:10#B2C8D9:' ':STACK GPRINT:10:LAST:%5.2lf%s GPRINT:10min:MIN:%5.2lf%s GPRINT:10max:MAX:%5.2lf%s GPRINT:10:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:11=::AVERAGE DEF:11min=::MIN DEF:11max=::MAX AREA:11#779DBF:' ':STACK GPRINT:11:LAST:%5.2lf%s GPRINT:11min:MIN:%5.2lf%s GPRINT:11max:MAX:%5.2lf%s GPRINT:11:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:12=::AVERAGE DEF:12min=::MIN DEF:12max=::MAX AREA:12#3E75A7:' ':STACK GPRINT:12:LAST:%5.2lf%s GPRINT:12min:MIN:%5.2lf%s GPRINT:12max:MAX:%5.2lf%s GPRINT:12:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:13=::AVERAGE DEF:13min=::MIN DEF:13max=::MAX AREA:13#205F9A:' ':STACK GPRINT:13:LAST:%5.2lf%s GPRINT:13min:MIN:%5.2lf%s GPRINT:13max:MAX:%5.2lf%s GPRINT:13:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:14=::AVERAGE DEF:14min=::MIN DEF:14max=::MAX AREA:14#00488C:' ':STACK GPRINT:14:LAST:%5.2lf%s GPRINT:14min:MIN:%5.2lf%s GPRINT:14max:MAX:%5.2lf%s GPRINT:14:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:15=::AVERAGE DEF:15min=::MIN DEF:15max=::MAX AREA:15#BEA37A:' ':STACK GPRINT:15:LAST:%5.2lf%s GPRINT:15min:MIN:%5.2lf%s GPRINT:15max:MAX:%5.2lf%s GPRINT:15:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:16=::AVERAGE DEF:16min=::MIN DEF:16max=::MAX AREA:16#907A52:' ':STACK GPRINT:16:LAST:%5.2lf%s GPRINT:16min:MIN:%5.2lf%s GPRINT:16max:MAX:%5.2lf%s GPRINT:16:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:17=::AVERAGE DEF:17min=::MIN DEF:17max=::MAX AREA:17#7A653E:' ':STACK GPRINT:17:LAST:%5.2lf%s GPRINT:17min:MIN:%5.2lf%s GPRINT:17max:MAX:%5.2lf%s GPRINT:17:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:18=::AVERAGE DEF:18min=::MIN DEF:18max=::MAX AREA:18#63522B:' ':STACK GPRINT:18:LAST:%5.2lf%s GPRINT:18min:MIN:%5.2lf%s GPRINT:18max:MAX:%5.2lf%s GPRINT:18:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:19=::AVERAGE DEF:19min=::MIN DEF:19max=::MAX AREA:19#3D3000:' ':STACK GPRINT:19:LAST:%5.2lf%s GPRINT:19min:MIN:%5.2lf%s GPRINT:19max:MAX:%5.2lf%s GPRINT:19:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:20=::AVERAGE DEF:20min=::MIN DEF:20max=::MAX AREA:20#F3AA79:' ':STACK GPRINT:20:LAST:%5.2lf%s GPRINT:20min:MIN:%5.2lf%s GPRINT:20max:MAX:%5.2lf%s GPRINT:20:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:21=::AVERAGE DEF:21min=::MIN DEF:21max=::MAX AREA:21#EB8953:' ':STACK GPRINT:21:LAST:%5.2lf%s GPRINT:21min:MIN:%5.2lf%s GPRINT:21max:MAX:%5.2lf%s GPRINT:21:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:22=::AVERAGE DEF:22min=::MIN DEF:22max=::MAX AREA:22#E1662A:' ':STACK GPRINT:22:LAST:%5.2lf%s GPRINT:22min:MIN:%5.2lf%s GPRINT:22max:MAX:%5.2lf%s GPRINT:22:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:23=::AVERAGE DEF:23min=::MIN DEF:23max=::MAX AREA:23#DC5313:' ':STACK GPRINT:23:LAST:%5.2lf%s GPRINT:23min:MIN:%5.2lf%s GPRINT:23max:MAX:%5.2lf%s GPRINT:23:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:24=::AVERAGE DEF:24min=::MIN DEF:24max=::MAX AREA:24#D84000:' ':STACK GPRINT:24:LAST:%5.2lf%s GPRINT:24min:MIN:%5.2lf%s GPRINT:24max:MAX:%5.2lf%s GPRINT:24:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:25=::AVERAGE DEF:25min=::MIN DEF:25max=::MAX AREA:25#B5B5A9:' ':STACK GPRINT:25:LAST:%5.2lf%s GPRINT:25min:MIN:%5.2lf%s GPRINT:25max:MAX:%5.2lf%s GPRINT:25:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:26=::AVERAGE DEF:26min=::MIN DEF:26max=::MAX AREA:26#8B8D82:' ':STACK GPRINT:26:LAST:%5.2lf%s GPRINT:26min:MIN:%5.2lf%s GPRINT:26max:MAX:%5.2lf%s GPRINT:26:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:27=::AVERAGE DEF:27min=::MIN DEF:27max=::MAX AREA:27#74796F:' ':STACK GPRINT:27:LAST:%5.2lf%s GPRINT:27min:MIN:%5.2lf%s GPRINT:27max:MAX:%5.2lf%s GPRINT:27:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:28=::AVERAGE DEF:28min=::MIN DEF:28max=::MAX AREA:28#5D645A:' ':STACK GPRINT:28:LAST:%5.2lf%s GPRINT:28min:MIN:%5.2lf%s GPRINT:28max:MAX:%5.2lf%s GPRINT:28:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:29=::AVERAGE DEF:29min=::MIN DEF:29max=::MAX AREA:29#434C43:' ':STACK GPRINT:29:LAST:%5.2lf%s GPRINT:29min:MIN:%5.2lf%s GPRINT:29max:MAX:%5.2lf%s GPRINT:29:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:30=::AVERAGE DEF:30min=::MIN DEF:30max=::MAX AREA:30#E6A4A5:' ':STACK GPRINT:30:LAST:%5.2lf%s GPRINT:30min:MIN:%5.2lf%s GPRINT:30max:MAX:%5.2lf%s GPRINT:30:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:31=::AVERAGE DEF:31min=::MIN DEF:31max=::MAX AREA:31#D6707B:' ':STACK GPRINT:31:LAST:%5.2lf%s GPRINT:31min:MIN:%5.2lf%s GPRINT:31max:MAX:%5.2lf%s GPRINT:31:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:32=::AVERAGE DEF:32min=::MIN DEF:32max=::MAX AREA:32#C4384F:' ':STACK GPRINT:32:LAST:%5.2lf%s GPRINT:32min:MIN:%5.2lf%s GPRINT:32max:MAX:%5.2lf%s GPRINT:32:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:33=::AVERAGE DEF:33min=::MIN DEF:33max=::MAX AREA:33#BC1C39:' ':STACK GPRINT:33:LAST:%5.2lf%s GPRINT:33min:MIN:%5.2lf%s GPRINT:33max:MAX:%5.2lf%s GPRINT:33:AVERAGE:'%5.2lf%s\n' COMMENT:'\n' DEF:34=::AVERAGE DEF:34min=::MIN DEF:34max=::MAX AREA:34#B30023:' ':STACK GPRINT:34:LAST:%5.2lf%s GPRINT:34min:MIN:%5.2lf%s GPRINT:34max:MAX:%5.2lf%s GPRINT:34:AVERAGE:'%5.2lf%s\n' COMMENT:'\n'

RRDTool Output
ERROR: Cannot parse DS in 'DEF:0=::AVERAGE'

---------------------------------------------------------------------------------
Looks like there is no rrdfile in this command.
However, I have the files poller-perf-<module>.rrd in each device directory.
It may be the issue ?

Thank you,

**Comment by f0o** [comment]
ERROR: Cannot parse DS in 'DEF:0=::AVERAGE'

Is the issue. That line is malformed for some reason. Not sure why but it's attempting to pull a DS called 0

**Comment by Linutux42** [comment]
Yes, but I cannot see any reference to a rrd file in this command. Mine are stored inside /mnt/data/rrd/ but I can't find the path anywhere in that command line. Isn't that the issue mostly ?

**Comment by geordish** [comment]
The problem is not that the DS is called 0, thats the ID for it. The bit after the = is the path to the RRD. An example line for this would be:

DEF:poller0=/opt/librenms/rrds/xxx/poller-perf-bgp-peers.rrd:poller:AVERAGE 

html/includes/graphs/generic_multi_simplex_seperated.inc.php is the file that generates the graph. This is done from an array that is populated by html/includes/graphs/device/poller_modules_perf.inc.php

I cannot see why this wouldn't be working. Perhaps it is something too do with your RRDs being in a location other than /opt/librenms/rrds ?
Have you got $config['rrd_dir'] set? I presume you do otherwise you would have bigger issues.

**Comment by Linutux42** [comment]
As I said, my rrd files are stored in another location than the default one, and obviously the config['rrd_dir'] is configured crrectly :)
