### ISSUE TITLE
Email alerting not working after switch to AD authentication

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#3533]
after switching all users to AD authentication email are not sent out anymore.
 I see errors like that:

_Could not issue warning alert for rule 'Storage Warning' to transport 'mail' Error: You must provide at least one recipient email address._

on the SQL users Table I see the right user email address .

**Comment by f0o** [comment]
When you use AD, you must use a 'default contact' I'm afraid

On 18 May 2016 16:48:21 CEST, Vitali Kari <notifications@github.com> wrote:
>after switching all users to AD authentication email are not sent out
>anymore.
> I see errors like that:
>
>_Could not issue warning alert for rule 'Storage Warning' to transport
>'mail' Error: You must provide at least one recipient email address._
>
>on the SQL users Table I see the right user email address .
>
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/3533

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vitalisator** [comment]
I will test that tomorrow...

is it possible to use normal behavior for AD user?
where is the code for that logic, so i can read and understand this?

**Comment by vitalisator** [comment]
yes, I can confirm that it works with 'default contact' but not with AD users.
I think this should be fixed.

**Comment by f0o** [comment]
So the users table has emails associated to the accounts and those accounts have at least read privilege on the device in question correct?

**Comment by vitalisator** [comment]
Yes, that is right.
I have three users with email and "level" 5 and 10 in the users table.

**Comment by f0o** [comment]
So you have ticked alert to globals and admins? Otherwise they are not considered

**Comment by vitalisator** [comment]
I works only if I use 'default contact'.
in other cases I see: Could not issue recovery for rule 'Device Down' to transport 'mail' Error: You must provide at least one recipient email address.

here my settings and DB user table:
http://picpaste.de/screenshot-area-2016-05-26-091947-XD1eklyi.png
http://picpaste.de/user-db-VuIWkCxt.png
The user with lower id are local and high id AD-Users

**Comment by vitalisator** [comment]
I want to debug at that point of code:
to see if the user email is loaded from AD

 librenms/includes/alerts.inc.php
---
 297:   $users = get_userlist();
---
but don not know how to print the $users at runtime, any hint?

**Comment by murrant** [comment]
@vitalisator `var_dump()`, or `logfile(var_dump($users), 1)`

**Comment by vitalisator** [comment]
ok, found that 
https://github.com/librenms/librenms/blob/cfdbc6f93d985f37d3a7c2aabff93bd325b56673/html/includes/authentication/active_directory.inc.php#L187
do not return a valid CN if name contains a comma sign inside.

for example this DN would work
_'CN=Jon Doe,DC=domain,DC=local'_ 
but this one not
_'CN=Doe\\, Jon,DC=domain,DC=local'_

so I think the double backslash should be used in get_cn() function to mask a following "," sign.

Where is get_cn() difined?

**Comment by geordish** [comment]
@vitalisator : https://github.com/librenms/librenms/blob/cfdbc6f93d985f37d3a7c2aabff93bd325b56673/html/includes/authentication/active_directory.inc.php#L297-L300

I wonder if adding in a line similar to $dn = str_replace(',','\\,'$dn); would work?

**Comment by vitalisator** [comment]
It seems that there is more broken. With my workaround I see the test Alert, but the really allerts causes still: _Error: You must provide at least one recipient email address._

**Comment by laf** [comment]
Are the email addresses fully formatted? I.e it's not just 'root' or something like that?

**Comment by vitalisator** [comment]
Yes, the email stored in active directory are correct and fully formatted 




On Thu, Jun 30, 2016 at 9:23 AM +0200, "Neil Lathwood" <notifications@github.com> wrote:












Are the email addresses fully formatted? I.e it's not just 'root' or something like that?
