### ISSUE TITLE
Cisco ASR920 (IOS-XE) error messages

### ISSUE THREAD

**Issue by cr1ll3** [librenms/librenms#3537]
Hello,

Each and every time LibreNMS pulls data from our ASR920's our logs are filled with the following (In the device);

May 19 2016 15:06:03.132 CEST: snmp: count not valid
May 19 2016 15:06:03.133 CEST: snmp: count not valid
May 19 2016 15:06:03.133 CEST: snmp: count not valid
May 19 2016 15:06:03.133 CEST: snmp: count not valid
May 19 2016 15:06:03.136 CEST: snmp: count not valid
May 19 2016 15:06:03.136 CEST: snmp: count not valid
May 19 2016 15:06:03.136 CEST: snmp: count not valid
... snip ...

Is there any way to find out which snmp count that isn't valid?

**Comment by laf** [comment]
You'd probably have to run each polling module manually and keep an eye on your logs - also check the firmware you are running, you may find this is fixed in an update.

**Comment by laf** [comment]
Please feel free to feedback and we can re-open this.
