### ISSUE TITLE
Icons missing for some devices

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#3541]
Hi,

I have noticed the device icons for a few of our devices monitoring have gone missing and are now shown as generic. I think the problem started manifestering when for some reason LibreNMS started seeing these devices as down and when they came back, they were then seen as generic device types.Trying to rediscovery the devices concerned does not help. I can change the icon type via the database however I would have thought it should be possible for LibreNMS to update the database automatically seeing that it can pickup the device type when discovering and polling the relevant device. See below for a Cisco firewall example;

![snap7](https://cloud.githubusercontent.com/assets/16717388/15468631/96a93a1a-20e5-11e6-900c-77e5404bdfca.png)

![snap4](https://cloud.githubusercontent.com/assets/16717388/15468642/a660b528-20e5-11e6-9d21-9055a4f9b824.png)

![snap5](https://cloud.githubusercontent.com/assets/16717388/15468654/b3f08560-20e5-11e6-9a6e-28bfa5ff535a.png)

![snap3](https://cloud.githubusercontent.com/assets/16717388/15468660/bbfe54a8-20e5-11e6-8c6d-d649add34843.png)

**Comment by murrant** [comment]
Please update your install (`daily.sh` then `validate.sh`).  A fix for this was added for this some time ago.

http://docs.librenms.org/Support/Configuration/#auto-updates
