### ISSUE TITLE
gen_smokeping.php exits before returnning anything to stdout when librenms is installed under customized path

### ISSUE THREAD

**Issue by sq9mev** [librenms/librenms#3542]
gen_smokeping.php exits before returnning anything to stdout when librenms is installed under different path than default one (/opt/librenms), probably due to wrong order of includes in https://github.com/librenms/librenms/blob/master/scripts/gen_smokeping.php#L15  -as for now customized values in config.php are overwritten by default ones.

**Comment by murrant** [comment]
If librenms is in a non-standard directory, `$config['install_dir']` needs to be set properly in your config.php file.

You will also need to run gen_smokeping.php from within the scripts directory. `cd /opt/librenms/scritps` for example.

**Comment by sq9mev** [comment]
> If librenms is in a non-standard directory, $config['install_dir'] needs to be set properly in your config.php file.

I've set $config['install_dir'] properly - path of the root install dir

> You will also need to run gen_smokeping.php from within the scripts directory. cd /opt/librenms/scritps for example.

Wait, if i use non-standard path, there will be no  /opt/librenms/ at all.

Default install  $config['install_dir'] is set in https://github.com/librenms/librenms/blob/master/includes/defaults.inc.php#L43.

Even if i customize $config['install_dir'] in config.php, it WILL be overwritten with default value from defaults.inc.php because of defaults.inc.php is AFTER config.php in https://github.com/librenms/librenms/blob/master/scripts/gen_smokeping.php#L15

IMHO order of includes in lines 14 and 15 schould be changed:

```
diff --git a/scripts/gen_smokeping.php b/scripts/gen_smokeping.php
index cd4baac..5763f73 100755
--- a/scripts/gen_smokeping.php
+++ b/scripts/gen_smokeping.php
@@ -11,8 +11,8 @@
 * the source code distribution for details.
 */
 
-include_once("../config.php");
 include_once("../includes/defaults.inc.php");
+include_once("../config.php");
 include_once("../includes/definitions.inc.php");
 
 ?>
```

At least this works for me.

**Comment by murrant** [comment]
Oh, I didn't look that close.  Thanks.

I used /opt/LibreNMS in my example because I don't what directory you are using.

Can you send a pull request with that change?  Don't forget the developer agreement.

http://docs.librenms.org/General/Contributing/

Thanks
