### ISSUE TITLE
librenms does not show "operating system" for cisco devices correctly

### ISSUE THREAD

**Issue by radoslawcz** [librenms/librenms#3545]
Newly added cisco devices show only "Cisco IOS" as an operating system. Older devices show exact ios version like for example "Cisco IOS 15.0(2)SE2"

Is this a bug?

**Comment by f0o** [comment]
Which devices is this referring to?

**Comment by radoslawcz** [comment]
These are cisco switches, like 2950, 2960 series.

It looks like this:

http://imgur.com/l5S7uSs

**Comment by murrant** [comment]
Could this have been a poller issue?   Looks like the devices might not have been polled yet.

**Comment by radoslawcz** [comment]
They have been polled. They have been added a few weeks ago and all show "cisco ios" only. However, when you go into "recent events" there is this kind of log 

"2016-05-30 09:20:32 sysDescr -> Cisco IOS Software, C2960S Software (C2960S-UNIVERSALK9-M), Version 15.0(2)SE4, RELEASE SOFTWARE (fc1) Technical Support: http://www.cisco.com/techsupport Copyright (c) 1986-2013 by Cisco Systems, Inc. Compiled Wed 26-Jun-13 02:59 by prod_rel_team"

so operating system is correctly discovered.

**Comment by laf** [comment]
Works fine for my 2960 at home.

Please post as a pastebin link the output of:

```bash
./discovery.php -h HOSTNAME -d -m os
./poller.php -d -r -f -h HOSTNAME -m os
```

**Comment by radoslawcz** [comment]
http://pastebin.com/EqbcfWmh - discovery
 
http://pastebin.com/x9du3H6s - poller

**Comment by murrant** [comment]
I see the poller is seeing a change in hardware and SN:
```
SQL[[0;33mINSERT INTO `eventlog` (`host`,`reference`,`type`,`datetime`,`message`)  VALUES ('63','NULL','system',NOW(),'Hardware -> C29xx Stacking')[0m]
SQL[[0;33mINSERT INTO `eventlog` (`host`,`reference`,`type`,`datetime`,`message`)  VALUES ('63','NULL','system',NOW(),'Serial -> FOC1703....')[0m]
```

Do you happen to have the OS polling module disabled for these devices?
Can you pastebin the results of:
```
./poller.php -r -f -h HOSTNAME
```

**Comment by radoslawcz** [comment]
pastebin results http://pastebin.com/vCzA5zLs

**Comment by murrant** [comment]
It does look like things are properly detected by the poller.

Your install is very old.  Please consider updating your install (`daily.sh` then `validate.sh`). 
http://docs.librenms.org/Support/Configuration/#auto-updates

**Comment by radoslawcz** [comment]
Updating did resolve the problem. Thanks a lot!
