### ISSUE TITLE
Help to understand GenSQL function

### ISSUE THREAD

**Issue by gcoeugnet** [librenms/librenms#3546]
Hi there,

I would like to add a new macro for Output interface charge which would be like the %macros.port_usage_perc
Here is my config.php : 
`$config['alert']['macros']['rule']['portOut_usage_perc'] = '((%ports.ifOutOctets_rate*8)/%ports.ifSpeed)*100';`

Testing it doesn't create an alert. So I take a look in the include/alerts.inc.php. My problem seems to be in ResolveGlues function which contains : 
`function ResolveGlues($tables,$target,$x=0,$hist=array(),$last=array()) {
    if( sizeof($tables) == 1 && $x != 0 ) {
`

Indeed, with my configuration $x is equal to 0 so resolveGlues return "false". I took a look before the call of ResolveGlues, here :
`        if( isset($tables[$i+1]) ) {
            $gtmp = ResolveGlues(array($tables[$i+1]),'device_id');
`

This call doesn't contains enough parameters for 'x' so it should be in $tables. With my configuration $tables is equal to 
`TABLES: array(2) {
  [0]=>
  string(5) "ports"
  [1]=>
  string(6) "/ports"
}
`

This doesn't contain any value for $x. Could you help me to understand how this works ? It's a litlle bit hard to debug without understanding what genSQL() is supposed to do. What am I supposed to find in $tables with this configuration ? Thanks a lot. Regards.

**Comment by f0o** [comment]
GenSQL takes your rule and translate it to a SQL select statement.

ResolveGlues will try to find the appropriate glue records to connect your rule to a device by looking up tables and columns

**Comment by gcoeugnet** [comment]
This is what i expected... 
I try to modify my config from :
`$config['alert']['macros']['rule']['portOut_usage_perc'] =  ((%ports.ifOutOctets_rate*8)/%ports.ifSpeed)*100';`

to 
`
$config['alert']['macros']['rule']['portOut_usage_perc'] = '((%ports.ifOutOctets_rate*8)/ %ports.ifSpeed)*100';`

with a space before the division operator. Now the GenSQL returned me something better :
`SQL: string(123) "SELECT * FROM ports WHERE (ports.device_id = ?) && ( (  (  ( ports.ifOutOctets_rate*8 ) / ports.ifSpeed ) *100 )  > "1"   )"`

Regarding [the doc](http://docs.librenms.org/Extensions/Alerting/#entities), `%macros.port_usage_perc` is equal to `((%ports.ifInOctets_rate*8)/%ports.ifSpeed)*100`

It doesn't contains space before "/". Maybe I respected too much the doc without adding space when it seems to be required ? Do you want me to change the doc and add space before "/" unless i'm wrong ?

**Comment by f0o** [comment]
Oh please update the docs, thats something we changed and I must've missed it. Sorry

**Comment by gcoeugnet** [comment]
Ok, i'll take that in charge tomorrow morning in a pull request. Thanks for your quick answers f0o.
