### ISSUE TITLE
Values in cisco-sla jitter graph

### ISSUE THREAD

**Issue by GuiMouth** [librenms/librenms#3550]
Hi,

I think, it's a request to add some information in the rrd cisco-sla jitter graph.
Today, it seems that only the last RTT is being graphed. 
Screenshot of SLA Jitter graph:
![image](https://cloud.githubusercontent.com/assets/12040321/15517042/f95f6e98-21f5-11e6-946f-18c7c30a5b91.png)

The values I would like are the jitter values and the packet loss.

To begin, am I right in telling this or are the values (jitter avg and packet loss) already graphed for someone ?

If i'm right, I've searched and found these CISCO MIB information : 
#### Jitter average 
in the CISCO-RTTMON-MIB, I find these information : 
`.iso.org.dod.internet.private.enterprises.cisco.ciscoMgmt.ciscoRttMonMIB.ciscoRttMonObjects.rttMonStats.rttMonJitterStatsTable.rttMonJitterStatsEntry.rttMonJitterStatsAvgJitterDS (.1.3.6.1.4.1.9.9.42.1.3.5.1.64)`
and 
`.iso.org.dod.internet.private.enterprises.cisco.ciscoMgmt.ciscoRttMonMIB.ciscoRttMonObjects.rttMonStats.rttMonJitterStatsTable.rttMonJitterStatsEntry.rttMonJitterStatsAvgJitterSD (.1.3.6.1.4.1.9.9.42.1.3.5.1.63)`
wich are the average jitter values in the two ways (in/out).

#### Packet loss
In an other OID I find packets loss information : 
`.iso.org.dod.internet.private.enterprises.cisco.ciscoMgmt.ciscoRttMonMIB.ciscoRttMonObjects.rttMonStats.rttMonJitterStatsTable.rttMonJitterStatsEntry.rttMonJitterStatsPacketLossSD (.1.3.6.1.4.1.9.9.42.1.3.5.1.34)`
and
`.iso.org.dod.internet.private.enterprises.cisco.ciscoMgmt.ciscoRttMonMIB.ciscoRttMonObjects.rttMonStats.rttMonJitterStatsTable.rttMonJitterStatsEntry.rttMonJitterStatsPacketLossDS (.1.3.6.1.4.1.9.9.42.1.3.5.1.35)`
and
`.iso.org.dod.internet.private.enterprises.cisco.ciscoMgmt.ciscoRttMonMIB.ciscoRttMonObjects.rttMonStats.rttMonJitterStatsTable.rttMonJitterStatsEntry.rttMonJitterStatsPacketMIA (.1.3.6.1.4.1.9.9.42.1.3.5.1.37)`

The total of the packet loss is the addition of these 3 values (as mentionned here : [http://docwiki.cisco.com/wiki/IOS_IP_SLAs_UDP_Jitter_Operation_Technical_Analysis])

#### Conclusion
What do you need to implement these values in LibreNMS ?

Thank you to consider my request.
Bye
Gui

`./poller.php -h HOSTNAME -d -m cisco-sla` [debug-poller-SAY-sla.txt](https://github.com/librenms/librenms/files/280314/debug-poller-SAY-sla.txt)
`./discover.php -h HOSTNAME -d -m cisco-sla` [debug-discover-SAY-sla.txt](https://github.com/librenms/librenms/files/280313/debug-discover-SAY-sla.txt)

**Comment by Rosiak** [comment]
Any input @adaniels21487 ?

**Comment by adaniels21487** [comment]
This has been on my todo list for a while..

To add to this list, I would also like to collect these udp-jitter metrics:
MOS - 1.3.6.1.4.1.9.9.42.1.5.2.1.42
ICPIF - 1.3.6.1.4.1.9.9.42.1.5.2.1.43

I have a bit on at the moment, but I will knock something up in the next month or so..

**Comment by GuiMouth** [comment]
Hi,
Thanks for the feedback.
If I can find time I'll try to start coding it if you can guide me on how to implement it.
Should we get these values into the cisco-sla include files ? Or into other new include files ?

**Comment by adaniels21487** [comment]
@GuiMouth 
Each object in the rttMonStats table contains 2 values.
Eg looking at AvgJitterSD, I see:
.1.3.6.1.4.1.9.9.42.1.3.5.1.63.6.4955 33
.1.3.6.1.4.1.9.9.42.1.3.5.1.63.6.393961 32

Do you know what each of these values is for?

**Comment by adaniels21487** [comment]
Hi @GuiMouth 
I can't find any data on the values you reference. does the list below give you what you need?

CSR1000v#sh ip sla statistics 5
IPSLAs Latest Operation Statistics

IPSLA operation id: 5
Type of operation: udp-jitter
        Latest RTT: 1867 milliseconds
Latest operation start time: 06:42:56 UTC Thu Jun 23 2016
Latest operation return code: OK
RTT Values:
        Number Of RTT: 449              RTT Min/Avg/Max: 4/1867/3927 milliseconds
Latency one-way time:
        Number of Latency one-way Samples: 449
        Source to Destination Latency one way Min/Avg/Max: 2/**1816**/3859 milliseconds
        Destination to Source Latency one way Min/Avg/Max: 2/**51**/179 milliseconds
Jitter Time:
        Number of SD Jitter Samples: 127
        Number of DS Jitter Samples: 448
        Source to Destination Jitter Min/Avg/Max: 0/**23**/72 milliseconds
        Destination to Source Jitter Min/Avg/Max: 0/**9**/65 milliseconds
Over Threshold:
        Number Of RTT Over Threshold: 0 (0%)
Packet Loss Values:
        Loss Source to Destination: **549**
        Source to Destination Loss Periods Number: 144
        Source to Destination Loss Period Length Min/Max: 1/3
        Source to Destination Inter Loss Period Length Min/Max: 1/549
        Loss Destination to Source: **0**
        Destination to Source Loss Periods Number: 0
        Destination to Source Loss Period Length Min/Max: 0/0
        Destination to Source Inter Loss Period Length Min/Max: 0/0
        Out Of Sequence: **0**      Tail Drop: **2**
        Packet Late Arrival: **0**  Packet Skipped: 0
Voice Score Values:
        Calculated Planning Impairment Factor (ICPIF): **93**
        MOS score: **1.00**
Number of successes: 1
Number of failures: 0
Operation time to live: Forever

.1.3.6.1.4.1.9.9.42.1.5.2.1.49 - rttMonLatestJitterOperOWAvgSD.5 1816
.1.3.6.1.4.1.9.9.42.1.5.2.1.50 - rttMonLatestJitterOperOWAvgDS.5 51
.1.3.6.1.4.1.9.9.42.1.5.2.1.47 - rttMonLatestJitterOperAvgSDJ.5 23
.1.3.6.1.4.1.9.9.42.1.5.2.1.48 - rttMonLatestJitterOperAvgDSJ.5 9
.1.3.6.1.4.1.9.9.42.1.5.2.1.26 - rttMonLatestJitterOperPacketLossSD.5 549
.1.3.6.1.4.1.9.9.42.1.5.2.1.27 - rttMonLatestJitterOperPacketLossDS.5 0
.1.3.6.1.4.1.9.9.42.1.5.2.1.28 - rttMonLatestJitterOperPacketOutOfSequence.5 0
.1.3.6.1.4.1.9.9.42.1.5.2.1.29 - rttMonLatestJitterOperPacketMIA.5 2
.1.3.6.1.4.1.9.9.42.1.5.2.1.30 - rttMonLatestJitterOperPacketLateArrival.5 0
.1.3.6.1.4.1.9.9.42.1.5.2.1.42 - rttMonLatestJitterOperMOS.5 100
.1.3.6.1.4.1.9.9.42.1.5.2.1.43 - rttMonLatestJitterOperICPIF.5 93

**Comment by GuiMouth** [comment]
Hi @adaniels21487 
You're right. The OID that I found was wrong. They were randomly generated at each loop of the sla test.
The OIDs you gave are the good ones to have correct information ! and we can forget the rttMonStats table !
Thanks
NB : I will test these new OID values on my routers and will re-post a feedback after

**Comment by GuiMouth** [comment]
Hi @adaniels21487 

I'm agree with you for these OID : 
.1.3.6.1.4.1.9.9.42.1.5.2.1.49 - rttMonLatestJitterOperOWAvgSD.5 1816
.1.3.6.1.4.1.9.9.42.1.5.2.1.50 - rttMonLatestJitterOperOWAvgDS.5 51
.1.3.6.1.4.1.9.9.42.1.5.2.1.47 - rttMonLatestJitterOperAvgSDJ.5 23
.1.3.6.1.4.1.9.9.42.1.5.2.1.48 - rttMonLatestJitterOperAvgDSJ.5 9
.1.3.6.1.4.1.9.9.42.1.5.2.1.26 - rttMonLatestJitterOperPacketLossSD.5 549
.1.3.6.1.4.1.9.9.42.1.5.2.1.27 - rttMonLatestJitterOperPacketLossDS.5 0
.1.3.6.1.4.1.9.9.42.1.5.2.1.28 - rttMonLatestJitterOperPacketOutOfSequence.5 0
.1.3.6.1.4.1.9.9.42.1.5.2.1.29 - rttMonLatestJitterOperPacketMIA.5 2
.1.3.6.1.4.1.9.9.42.1.5.2.1.30 - rttMonLatestJitterOperPacketLateArrival.5 0
.1.3.6.1.4.1.9.9.42.1.5.2.1.42 - rttMonLatestJitterOperMOS.5 100
.1.3.6.1.4.1.9.9.42.1.5.2.1.43 - rttMonLatestJitterOperICPIF.5 93

**Comment by adaniels21487** [comment]
Hi Team,
I am about ready to submit a PR for this issue to graph additional metrics for the udp-jitter probe.
The code also allows for other probes to add additional metrics if needed.

As a part 2, I have begun looking at alerting.
First thought was to add an operational status field, probe 1.3.6.1.4.1.9.9.42.1.2.10.1.2 and we are done.
After running this on a couple of deployments, I have seen that the icmp-echo probe works by sending a single ping, and the SLA is marked up or down based on this.
On some SLA's I see the probe going up and down due to CoPP policies and the like which limit and drop ~1% of ICMP traffic.

So, I would like some advice on how the community would like this to proceed. Options:

1. This is not LibreNMS' problem and the probe should find something more reliable to poll.
2. I should also implement an ignore functionality where we can poll the probe but not raise alerts on it.

Going down the route of 2 will require the addition of an ignore field and some html in the edit pages to modify it. Or, I could port this to use the component feature for storage, which already has the ability to ignore individual components?

Any other ideas are welcome...

**Comment by adaniels21487** [comment]
Hi Team,
This has been committed now, please take a look!

**Comment by Rosiak** [comment]
Merged #4006
