### ISSUE TITLE
Delay in graph widget with memcached

### ISSUE THREAD

**Issue by wiad** [librenms/librenms#3559]
With memcached enabled we experience some strange behaviour trying to add graph widgets to dashboards. 

On clicking 'Set' to create the graph (port bits graph) the create form is reset (i.e all values I input disappear) and no graph is shown. No error or status message is shown. However, if I reload the page after a while the graph appears. So it seems that the graph widget is actually created but the db query used to do this is cached by memcached and somehow returning wrong data? Not sure how it works, but if I disable memcached everything works as expected.  

There are also some other quirks that we've seen with memcached, such as users not being able to acknowledge notifications as read. After a while they disappear though, which seems to me be a similar problem and probably also related to memcached.

**Comment by f0o** [comment]
This is expected as any changes made while memcached is enabled will only become effective after the memcached ttl expires.

It's a very basic and aggressive query based caching method

On 25 May 2016 07:43:59 CEST, wiad <notifications@github.com> wrote:
>With memcached enabled we experience some strange behaviour trying to
>add graph widgets to dashboards. 
>
>On clicking 'Set' to create the graph (port bits graph) the create form
>is reset (i.e all values I input disappear) and no graph is shown. No
>error or status message is shown. However, if I reload the page after a
>while the graph appears. So it seems that the graph widget is actually
>created but the db query used to do this is cached by memcached and
>somehow returning wrong data? Not sure how it works, but if I disable
>memcached everything works as expected.  
>
>There are also some other quirks that we've seen with memcached, such
>as users not being able to acknowledge notifications as read. After a
>while they disappear though, which seems to me be a similar problem and
>probably also related to memcached. 
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/3559

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wiad** [comment]
ok, good to know. We'll need to decide if the performance improvement is worth the quirks then. Thanks!

**Comment by f0o** [comment]
As a reference for our largest install we use memcache with a ttl of 3 minutes, no hosts are being added frequently or changes made, this install is plainly for alert-dispatch and graphs of ~1k hosts

On smaller more dynamic installs where hosts are added and removed more frequently I use 1 minute ttl
