### ISSUE TITLE
Billing Poller seems inaccurate.

### ISSUE THREAD

**Issue by dragon2611** [librenms/librenms#3571]
The Billing Poller doesn't seem to be corresponding to the actual traffic on the interface, The quick graphs bear no relation to the supposedly accurate graphs.

Between the Period of 02:00 and 04:00 where the billing poller seems to be claiming 25GB per hour the actual PPPoE session to the ISP was down due to a fault within the carriers network.

![r1](https://cloud.githubusercontent.com/assets/6185399/15621382/6e298010-2458-11e6-941e-3d45d3043a5f.png)
![r2](https://cloud.githubusercontent.com/assets/6185399/15621384/6e445656-2458-11e6-98d4-1091006c48d0.png)
![r3](https://cloud.githubusercontent.com/assets/6185399/15621383/6e427b24-2458-11e6-8cd0-c9211b1a146f.png)

There are also several days where libreNMS will claim 10's of GB usage where as my provider is showing much less usage.

Version	47c22f6
DB Schema	#115
Apache	2.4.10 (Debian)
PHP	5.6.20-0+deb8u1
MySQL	10.0.23-MariaDB-0+deb8u1
RRDtool	1.4.8

**Comment by dragon2611** [comment]
Reset the DB entires just in case something had gotten screwed up.

Will monitor.

**Comment by laf** [comment]
This is most likely due to bad data from the device (you mentioning that the pppoe session was down during bad data steers me towards this). The way we can deal with this for normal graphs is with rrdtune but it's not applicable here in billing.

All we could do is lookup the interfaces speed in the DB and bin off any bad data (or re-use the last known good data).

**Comment by dragon2611** [comment]
I was polling the underlying eth interface not the pop virtual if and I belive the billing poller ignores rrdtune

But yes I am wondering if edgeos is returning junk values

Sent from Nine<http://www.9folders.com/>
________________________________
