### ISSUE TITLE
Services "Type" drop-down menu is empty

### ISSUE THREAD

**Issue by gelato** [librenms/librenms#3574]
The issue is described in the title... The "services" module is on, but "type" drop-down menu is empty.

**Comment by laf** [comment]
Please show a screenshot

**Comment by gelato** [comment]
Sure:
![sc1](https://cloud.githubusercontent.com/assets/1236528/15708863/02cda64c-280a-11e6-881a-895837242144.png)

**Comment by paulgear** [comment]
@gelato, that looks to me like you don't have nagios-plugins-basic or its equivalent installed on your LibreNMS server.

**Comment by laf** [comment]
@gelato Please see http://docs.librenms.org/Extensions/Services/ for getting started with services.
