### ISSUE TITLE
Wrong load-avg value on debian !!

### ISSUE THREAD

**Issue by shahzaibcb** [librenms/librenms#3575]
Hi,

LibreNMS showing load-avg value 40 while our debian server is under 200+ loadavg. Here is the polling output to debug issue :

http://pastebin.com/29nEn9RV

Here you can see the load-avg is http://prntscr.com/balo7p while librenms only showing this http://prntscr.com/balouw .

I am editing this thread, the issue is not only with Linux Debian but also with FreeBSD.

**Comment by shahzaibcb** [comment]
Guys, 

Anyone looked into this issue ?

**Comment by laf** [comment]
Please run this from within /opt/librenms (replace localhost with the device name)

`rrdtool tune rrd/localhost/ucd_load.rrd -a 1min:50000 -a 5min:50000 -a 15min:50000`

Wait 15 mins and let us know if it's resolved.

**Comment by f0o** [comment]
The values look conclusive to me, just off by a power of 10.

However i can't reproduce it in my installs.

Did what laf suggested work?

**Comment by laf** [comment]
I think the issue is that we limit the rrd file to 5000 max val but this is using 30000+

**Comment by shahzaibcb** [comment]
Hi Guys, pardon for the delayed response. I've ran that command will update you in a while !!

Thanks :-)

**Comment by shahzaibcb** [comment]
I wanted  to confirm one thing, should i run this command under high load-avg ? Currently there's not more than 30.0 Load on servers.

**Comment by shahzaibcb** [comment]
Looks like situation got better on executing that command, graph crossed value 60 this time :

http://prntscr.com/bimhne

**Comment by shahzaibcb** [comment]
Guys, any permanent fix ?

**Comment by laf** [comment]
Do you see the correct values now then?
