### ISSUE TITLE
Pseudowires Service Instance Issue

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#3581]
Hi !

In librenms pseudowire only work from one interface to an other interface ! But not if we use service instances to port or to an other service instance = sub interface !

if i choose a device on which pseudowires are configured i see this service instance subinterfaces  

for example:

Gi0/21.SI.2220

and i see the utilization 

but under pseudowires librenms use only the main port and not the right subinterface = Service Instance Interface 

Please fix this issue !

kind regards 

kristoferus75

**Comment by aauvinet** [comment]
I have also a issue with the GUI pseudowire .

see #3581

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by kristoferus75** [comment]
Hi !

The problem is still not solved -> i use the newest software !

which information or debug is nessacery ?

kind regrads

kristoferus75

**Comment by laf** [comment]
We need all the info from: http://docs.librenms.org/Support/FAQ/#faq8

**Comment by aauvinet** [comment]
Hello @laf ,

- In my LibreNMS, I can't see the pseudowire on GUI pseudowire.
But in database , there are lot of data.

****************** Poller on devices ******


*******************Database*********************
mysql> select * from pseudowires LIMIT 50;
+---------------+-----------+---------+----------------+-------------+---------+--------+----------+------------+--------------+-------------+----------------------------------------------------+
| pseudowire_id | device_id | port_id | peer_device_id | peer_ldp_id | cpwVcID | cpwOid | pw_type  | pw_psntype | pw_local_mtu | pw_peer_mtu | pw_descr                                           |
+---------------+-----------+---------+----------------+-------------+---------+--------+----------+------------+--------------+-------------+----------------------------------------------------+
|             7 |        14 |       0 |              0 |       17230 |    2000 |      2 | ethernet | mpls       |            0 |           0 |                                                    |
|             8 |        14 |       0 |              0 |       17230 |    3990 |      3 | ethernet | mpls       |            0 |           0 |                                                    |
|             9 |        14 |       0 |              0 |       17230 |    3990 |     10 | ethernet | mpls       |            0 |           0 |                                                    |
|            10 |        14 |       0 |              0 |       17230 |    3990 |     13 | ethernet | mpls       |            0 |           0 |                                                    |
|            11 |        14 |       0 |              0 |       17230 |    3990 |     15 | ethernet | mpls       |            0 |           0 |                                                    |
|            12 |        14 |       0 |              0 |       17230 |    3990 |     16 | ethernet | mpls       |            0 |           0 |                                                    |
|            13 |        14 |       0 |              0 |       17230 |    3990 |     17 | ethernet | mpls       |            0 |           0 |                                                    |
|            14 |        13 |       0 |              0 |       17230 |    3990 |     17 | ethernet | mpls       |            0 |           0 |                                                    |
|            15 |        13 |       0 |             14 |       17230 |    3990 |     22 | ethernet | mpls       |            0 |           0 |                                                    |
|            16 |        13 |       0 |              0 |       17230 |    3990 |     25 | ethernet | mpls       |            0 |           0 |                                                    |
|            17 |        13 |       0 |              0 |       17230 |    3990 |     27 | ethernet | mpls       |            0 |           0 |                                                    |
|            18 |        13 |       0 |              0 |       17230 |    3990 |     28 | ethernet | mpls       |            0 |           0 |                                                    |
|            19 |        13 |       0 |              0 |       17230 |    3990 |     29 | ethernet | mpls       |            0 |           0 |                                                    |
|            20 |        12 |       0 |              0 |       17230 |    2001 |      2 | ethernet | mpls       |            0 |           0 | RT - Camera - interco oceanet                      |
|            21 |        12 |       0 |              0 |       17230 |    2002 |      3 | ethernet | mpls       |            0 |           0 | RT - DMZ6 - interco                                |
|            22 |        12 |       0 |              0 |       17230 |    3990 |      5 | ethernet | mpls       |            0 |           0 |                                                    |
|            23 |        12 |       0 |             13 |       17230 |    3990 |     11 | ethernet | mpls       |            0 |           0 |                                                    |
|            24 |        12 |       0 |             14 |       17230 |    3990 |     12 | ethernet | mpls       |            0 |           0 |                                                    |
|            25 |        12 |       0 |              0 |       17230 |    3990 |     14 | ethernet | mpls       |            0 |           0 |                                                    |
|            26 |        12 |       0 |              0 |       17230 |    3990 |     16 | ethernet | mpls       |            0 |           0 |                                                    |
|            27 |        12 |       0 |              0 |       17230 |    2003 |     17 | ethernet | mpls       |            0 |           0 |                                                    |
|            28 |        12 |       0 |              0 |       17230 |    3990 |     18 | ethernet | mpls       |            0 |           0 |                                                    |
|            29 |        10 |       0 |              0 |           0 |    3999 |      1 | other    | mpls       |            0 |           0 |                                                    |
|            30 |        10 |       0 |             12 |       17230 |    2001 |      2 | ethernet | mpls       |            0 |           0 |                                                    |
|            31 |        10 |       0 |              0 |       17230 |    2003 |     23 | ethernet | mpls       |            0 |           0 |                                                    |
|            32 |        10 |       0 |             12 |       17230 |    2003 |     24 | ethernet | mpls       |            0 |           0 |                                                    |
|            33 |         9 |       0 |              0 |       17230 |    3990 |      1 | ethernet | mpls       |            0 |           0 |                                                    |
|            34 |         9 |       0 |             13 |       17230 |    3990 |      7 | ethernet | mpls       |            0 |           0 |                                                    |
|            35 |         9 |       0 |             14 |       17230 |    3990 |      8 | ethernet | mpls       |            0 |           0 |                                                    |
|            36 |         9 |       0 |             12 |       17230 |    3990 |     11 | ethernet | mpls       |            0 |           0 |                                                    |
|            37 |         9 |       0 |              0 |       17230 |    3990 |     12 | ethernet | mpls       |            0 |           0 |                                                    |
|            38 |         9 |       0 |              0 |       17230 |    3990 |     13 | ethernet | mpls       |            0 |           0 |                                                    |
|            39 |         8 |       0 |              0 |       17230 |    2004 |      1 | ethernet | mpls       |            0 |           0 | Interco - museum - manifestation  VAN              |
|            40 |         8 |       0 |              0 |       17230 |    3990 |      2 | ethernet | mpls       |            0 |           0 |                                                    |
|            41 |         8 |       0 |              0 |       17230 |    3990 |      3 | ethernet | mpls       |            0 |           0 |                                                    |
|            42 |         8 |       0 |              9 |       17230 |    3990 |      4 | ethernet | mpls       |            0 |           0 |                                                    |
|            43 |         8 |       0 |             12 |       17230 |    3990 |      5 | ethernet | mpls       |            0 |           0 |                                                    |
|            44 |         8 |       0 |             13 |       17230 |    3990 |      6 | ethernet | mpls       |            0 |           0 |                                                    |
|            45 |         8 |       0 |             14 |       17230 |    3990 |      7 | ethernet | mpls       |            0 |           0 |                                                    |
|            46 |         7 |       0 |              0 |       17230 |    3990 |      1 | ethernet | mpls       |            0 |           0 |                                                    |
|            47 |         7 |       0 |              9 |       17230 |    3990 |      3 | ethernet | mpls       |            0 |           0 |                                                    |
|            48 |         7 |       0 |             12 |       17230 |    3990 |      6 | ethernet | mpls       |            0 |           0 |                                                    |
|            49 |         7 |       0 |             13 |       17230 |    3990 |      7 | ethernet | mpls       |            0 |           0 |                                                    |
|            50 |         7 |       0 |             14 |       17230 |    3990 |      8 | ethernet | mpls       |            0 |           0 |                                                    |
|            51 |         7 |       0 |             10 |       17230 |    2003 |      9 | other    | mpls       |            0 |           0 |                                                    |
|            52 |         7 |       0 |              8 |       17230 |    3990 |     10 | ethernet | mpls       |            0 |           0 |                                                    |
|            53 |         6 |       0 |              0 |           0 |    3996 |     12 | other    | mpls       |            0 |           0 |                                                    |
|            54 |         6 |       0 |             14 |       17230 |    2000 |     13 | ethernet | mpls       |            0 |           0 | EoMPLS - Vlan tetra > OPC-2 rue de grande bretagne |
|            55 |         6 |       0 |             12 |       17230 |    2002 |     14 | ethernet | mpls       |            0 |           0 | Interco RT - DGRN Dmz6                             |
|            56 |         6 |       0 |             13 |       17230 |    3990 |     21 | ethernet | mpls       |            0 |           0 |                                                    |
+---------------+-----------+---------+----------------+-------------+---------+--------+----------+------------+--------------+-------------+----------------------------------------------------+
50 rows in set (0.00 sec)



*******************GUI **********************

It's no OK

**Comment by aauvinet** [comment]
When I do discovery manually, devices is discover, and script add pseudowire in database.

It's strange....  At this time, There a are only one pseudowire in GUI .....While I have several


*********************************

root@test-observium:/opt/librenms# php discovery.php  -h loop0-pn-tourbretagne.reseau.nantes.net  -m cisco-pw -vv
LibreNMS Discovery
Version info:
Commit SHA: 1fb8135133c704b7edfba0f922f7ad7bb728650c
DB Schema: 159
PHP: 5.4.45-0+deb7u7
MySQL: 5.5.54-0+deb7u2
RRDTool: 1.4.7
SNMP: NET-SNMP 5.4.3
DEBUG!
SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1]
DB Schema already up to date.
SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE 'loop0-pn-tourbretagne.reseau.nantes.net' ORDER BY device_id DESC]
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '6']
loop0-pn-tourbretagne.reseau.nantes.net 6 ios SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '6' AND `attrib_type` = 'poll_mib' ]

Modules status: Global+ OS+ Device
#### Load disco module cisco-pw ####
SQL[SELECT * FROM `pseudowires` WHERE `device_id` = '6']
SNMP[/usr/bin/snmpbulkwalk -v2c -c 'public' -OQUs -m CISCO-IETF-PW-MPLS-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:loop0-pn-tourbretagne.reseau.nantes.net:161 cpwVcID]
cpwVcID.1 = 3996
cpwVcID.2 = 2000
cpwVcID.3 = 2002
cpwVcID.6 = 2100
cpwVcID.7 = 3990
cpwVcID.8 = 3990
cpwVcID.10 = 3990
cpwVcID.12 = 3990
cpwVcID.13 = 3990
cpwVcID.15 = 2005
cpwVcID.16 = 2006
cpwVcID.17 = 2004
cpwVcID.18 = 3990

SNMP[/usr/bin/snmpbulkwalk -v2c -c 'public' -OQUs -m CISCO-IETF-PW-MPLS-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:loop0-pn-tourbretagne.reseau.nantes.net:161 cpwVcName]
cpwVcName.1 = pseudowire100002
cpwVcName.2 = Vlan2000
cpwVcName.3 = Vlan2002
cpwVcName.6 = Vlan2100
cpwVcName.7 = pseudowire100001
cpwVcName.8 = pseudowire100001
cpwVcName.10 = pseudowire100001
cpwVcName.12 = pseudowire100001
cpwVcName.13 = pseudowire100001
cpwVcName.15 = Vlan2005
cpwVcName.16 = Vlan2006
cpwVcName.17 = Vlan2004
cpwVcName.18 = pseudowire100001

SNMP[/usr/bin/snmpbulkwalk -v2c -c 'public' -OQUs -m CISCO-IETF-PW-MPLS-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:loop0-pn-tourbretagne.reseau.nantes.net:161 cpwVcType]
cpwVcType.1 = other
cpwVcType.2 = ethernet
cpwVcType.3 = ethernet
cpwVcType.6 = ethernet
cpwVcType.7 = ethernet
cpwVcType.8 = ethernet
cpwVcType.10 = ethernet
cpwVcType.12 = ethernet
cpwVcType.13 = ethernet
cpwVcType.15 = ethernet
cpwVcType.16 = ethernet
cpwVcType.17 = ethernet
cpwVcType.18 = ethernet

SNMP[/usr/bin/snmpbulkwalk -v2c -c 'public' -OQUs -m CISCO-IETF-PW-MPLS-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:loop0-pn-tourbretagne.reseau.nantes.net:161 cpwVcPsnType]
cpwVcPsnType.1 = mpls
cpwVcPsnType.2 = mpls
cpwVcPsnType.3 = mpls
cpwVcPsnType.6 = mpls
cpwVcPsnType.7 = mpls
cpwVcPsnType.8 = mpls
cpwVcPsnType.10 = mpls
cpwVcPsnType.12 = mpls
cpwVcPsnType.13 = mpls
cpwVcPsnType.15 = mpls
cpwVcPsnType.16 = mpls
cpwVcPsnType.17 = mpls
cpwVcPsnType.18 = mpls

SNMP[/usr/bin/snmpbulkwalk -v2c -c 'public' -OQUs -m CISCO-IETF-PW-MPLS-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:loop0-pn-tourbretagne.reseau.nantes.net:161 cpwVcDescr]
cpwVcDescr.1 =
cpwVcDescr.2 = EoMPLS - Vlan tetra > OPC-2 rue de grande bretagne
cpwVcDescr.3 = Interco RT - DGRN Dmz6
cpwVcDescr.6 =
cpwVcDescr.7 =
cpwVcDescr.8 =
cpwVcDescr.10 =
cpwVcDescr.12 =
cpwVcDescr.13 =
cpwVcDescr.15 = EoMPLS - Usine eau - Vlan 1000
cpwVcDescr.16 = Eompls-ucopia-filaire
cpwVcDescr.17 = Interco EoMPLS - DMZ evnmt -
cpwVcDescr.18 =

SNMP[/usr/bin/snmpbulkwalk -v2c -c 'public' -OQUs -m CISCO-IETF-PW-MPLS-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:loop0-pn-tourbretagne.reseau.nantes.net:161 cpwVcMplsPeerLdpID]
cpwVcMplsPeerLdpID.1 =
cpwVcMplsPeerLdpID.2 = 172.30.0.9:0
cpwVcMplsPeerLdpID.3 = 172.30.0.7:0
cpwVcMplsPeerLdpID.6 = 172.30.0.13:0
cpwVcMplsPeerLdpID.7 = 172.30.0.2:0
cpwVcMplsPeerLdpID.8 = 172.30.0.3:0
cpwVcMplsPeerLdpID.10 = 172.30.0.7:0
cpwVcMplsPeerLdpID.12 = 172.30.0.9:0
cpwVcMplsPeerLdpID.13 = 172.30.0.4:0
cpwVcMplsPeerLdpID.15 = 172.30.0.8:0
cpwVcMplsPeerLdpID.16 = 172.30.0.3:0
cpwVcMplsPeerLdpID.17 =
cpwVcMplsPeerLdpID.18 = 172.30.0.8:0

SQL[SELECT device_id from ipv4_addresses AS A, ports AS I WHERE A.ipv4_address='' AND A.port_id=I.port_id]
SQL[SELECT port_id from ports WHERE `ifDescr`='pseudowire100002' AND `device_id`='6']
.SQL[SELECT device_id from ipv4_addresses AS A, ports AS I WHERE A.ipv4_address='172.30.0.9' AND A.port_id=I.port_id]
SQL[SELECT port_id from ports WHERE `ifDescr`='Vlan2000' AND `device_id`='6']
.SQL[SELECT device_id from ipv4_addresses AS A, ports AS I WHERE A.ipv4_address='172.30.0.7' AND A.port_id=I.port_id]
SQL[SELECT port_id from ports WHERE `ifDescr`='Vlan2002' AND `device_id`='6']
.SQL[SELECT device_id from ipv4_addresses AS A, ports AS I WHERE A.ipv4_address='172.30.0.13' AND A.port_id=I.port_id]
SQL[SELECT port_id from ports WHERE `ifDescr`='Vlan2100' AND `device_id`='6']
.SQL[SELECT device_id from ipv4_addresses AS A, ports AS I WHERE A.ipv4_address='172.30.0.2' AND A.port_id=I.port_id]
SQL[SELECT port_id from ports WHERE `ifDescr`='pseudowire100001' AND `device_id`='6']
.SQL[SELECT device_id from ipv4_addresses AS A, ports AS I WHERE A.ipv4_address='172.30.0.3' AND A.port_id=I.port_id]
SQL[SELECT port_id from ports WHERE `ifDescr`='pseudowire100001' AND `device_id`='6']
.SQL[SELECT device_id from ipv4_addresses AS A, ports AS I WHERE A.ipv4_address='172.30.0.7' AND A.port_id=I.port_id]
SQL[SELECT port_id from ports WHERE `ifDescr`='pseudowire100001' AND `device_id`='6']
.SQL[SELECT device_id from ipv4_addresses AS A, ports AS I WHERE A.ipv4_address='172.30.0.9' AND A.port_id=I.port_id]
SQL[SELECT port_id from ports WHERE `ifDescr`='pseudowire100001' AND `device_id`='6']
.SQL[SELECT device_id from ipv4_addresses AS A, ports AS I WHERE A.ipv4_address='172.30.0.4' AND A.port_id=I.port_id]
SQL[SELECT port_id from ports WHERE `ifDescr`='pseudowire100001' AND `device_id`='6']
.SQL[SELECT device_id from ipv4_addresses AS A, ports AS I WHERE A.ipv4_address='172.30.0.8' AND A.port_id=I.port_id]
SQL[SELECT port_id from ports WHERE `ifDescr`='Vlan2005' AND `device_id`='6']
.SQL[SELECT device_id from ipv4_addresses AS A, ports AS I WHERE A.ipv4_address='172.30.0.3' AND A.port_id=I.port_id]
SQL[SELECT port_id from ports WHERE `ifDescr`='Vlan2006' AND `device_id`='6']
.SQL[SELECT device_id from ipv4_addresses AS A, ports AS I WHERE A.ipv4_address='' AND A.port_id=I.port_id]
SQL[SELECT port_id from ports WHERE `ifDescr`='Vlan2004' AND `device_id`='6']
.SQL[SELECT device_id from ipv4_addresses AS A, ports AS I WHERE A.ipv4_address='172.30.0.8' AND A.port_id=I.port_id]
SQL[SELECT port_id from ports WHERE `ifDescr`='pseudowire100001' AND `device_id`='6']
.

>> Runtime for discovery module 'cisco-pw': 0.1790 seconds
#### Unload disco module cisco-pw ####

SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '6' AND `attrib_type` = 'poll_mib' ]
SQL[UPDATE `devices` set `last_discovered` =NOW(),`last_discovered_timetaken` ='0.193' WHERE `device_id` = '6']
Discovered in 0.193 seconds

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('discover','loop0-pn-tourbretagne.reseau.nantes.net','1490600734.5586','0.254','1','test-observium\n')]
discovery.php loop0-pn-tourbretagne.reseau.nantes.net 2017-03-27 09:45:34 - 1 devices discovered in 0.254 secs
SNMP: Get[0/0.00s] Walk [6/0.16s]
MySQL: Cell[29/0.02s] Row[2/0.00s] Rows[5/0.00s] Column[0/0.00s] Update[1/0.00s] Insert[1/0.00s] Delete[0/0.00s]
root@test-observium:/opt/librenms#

**Comment by laf** [comment]
Tagging into #2387 as it seems to be related.
