### ISSUE TITLE
port not shown in alert

### ISSUE THREAD

**Issue by momorientes** [librenms/librenms#3583]
Hi,

I have configured an alert: `%macros.port_usage_perc >= "80" && %devices.sysName ~ "XX" || %devices.sysName ~ "XY" `
If the alert triggers no information on the port is shown, even if expanding with the '+' symbol.
![2016-06-01-165137_5760x1200_scrot](https://cloud.githubusercontent.com/assets/510293/15714211/f344c1d2-2819-11e6-96bd-6123436c2d46.png)

**Comment by laf** [comment]
I've checked using this rule and don't have this issue.

Can you post the output of:

`./validate.php`

**Comment by momorientes** [comment]
```
Version info:
Commit SHA: 66f8a7e071dd8446478769a8afb324aef950263c
DB Schema: 117
PHP: 5.5.9-1ubuntu4.17
MySQL: 5.5.47-0ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

[OK]      Database connection successful
[WARN]    Your RRD directory is not set to 0775, please check our installation instructions
```
something seems strange with the warning:
```
ll | grep rrd
drwxr-xr-x 367 librenms librenms 20480 Jun  8 10:57 rrd/
```

**Comment by laf** [comment]
I genuinely can't replicate this.

Anyone else having this issue?

**Comment by f0o** [comment]
The rule is the issue,

Without using braces the logic goes:
(Port usage AND hostname1) OR hostname2

So only hostname1 will be checked for the usage and hostname2 will always be in alert unless hostname1 is in alert.

For these straightforward rules just use the mapping rather than appending and/or's

**Comment by laf** [comment]
Thanks @f0o.

Closing as not something we can fix.
