### ISSUE TITLE
Samsung printer profiles

### ISSUE THREAD

**Issue by BloodyIron** [librenms/librenms#3584]
@laf on IRC advised me to create a ticket/issue for Samsung printer profiles. I have a Samsung C410W, connecting to it via SNMP v3. I'm getting some info, but nothing printer centric, such as toner levels. I get CPU/RAM and a few other things though.

**Comment by laf** [comment]
Can you post the output of:

```bash
./discovery.php -h HOSTNAME -d -m toner
./poller.php -h HOSTNAME -d -r -f -m toner
```

**Comment by BloodyIron** [comment]
Discovery : http://pastebin.com/kfKe5KvH

Poller : http://pastebin.com/wdZan9CL

**Comment by laf** [comment]
Looks like it's purely because the printer isn't detected as a printer. I've submitted a pull request to resolve this, once it's merged and you're updated please try again. If it still doesn't work please re-run those commands.

**Comment by BloodyIron** [comment]
which build is it in? I'm on 2728bca

**Comment by BloodyIron** [comment]
Oh, looks like I got it now. Removed and re-added device. 10 minutes later not getting ink info though.

But it does seem to be getting the device name in the title.
