### ISSUE TITLE
Add support for Avtech RoomAlert3E

### ISSUE THREAD

**Issue by engageant** [librenms/librenms#3585]
Requested command output: http://pastebin.com/rx9JfSuX

Please add support for the RoomAlert3E - currently, my temp graph shows solid red with no real values.
![capture](https://cloud.githubusercontent.com/assets/3442922/15718833/41d26814-27fb-11e6-8a6f-7e0d4c83af93.PNG)

Thank you!

**Comment by Rosiak** [comment]
./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -r -f -d -m os
An snmpwalk of the device:
snmpbulkwalk -v2c -c COMMUNITY HOSTNAME .

**Comment by engageant** [comment]
The output of those commands are in the pastebin link in the OP, as requested.

**Comment by Rosiak** [comment]
@engageant The snmpwalk looks like it's missing a lot.

**Comment by engageant** [comment]
The device only supports SNMP v1.  I believe this is the case with all Avtech products.

**Comment by laf** [comment]
We already detect avtech kit so this is a sensors issue, please post the output of:

```bash
./discovery.php -h HOSTNAME -d -m sensors
```

**Comment by murrant** [comment]
@Rosiak Nope, that is everything.  I think I've said before that the snmp on these devices is terrible :P

**Comment by murrant** [comment]
@engageant Can you test the PR I just sent?

You can get the diff here:
https://github.com/librenms/librenms/pull/3599.diff

**Comment by laf** [comment]
That adds additional support rather than fixing temps doesn't it though?

**Comment by murrant** [comment]
The device was detected as  avtech OS, but the sensors were not supported.

**Comment by engageant** [comment]
@murrant - please forgive my git ignorance - how would I grab that PR?

**Comment by murrant** [comment]
@engageant The link I posted downloads a diff you can apply to librenms with `patch -p1 < 3599.dff`
The link again: https://github.com/librenms/librenms/pull/3599.diff

After you are done testing, `git checkout .` to reset back to master/HEAD.  (If you skip this step, your automatic updates will stop)

**Comment by engageant** [comment]
Thanks.  I applied the patch and tested;still no valid graph. I also tried
deleting and re-adding that device, no change.  Let me know if you need
additional command output.

**Comment by murrant** [comment]
@engageant please pastebin the output of (with the patch applied)
```
./discovery.php -h HOSTNAME -d -m sensors
```

**Comment by engageant** [comment]
@murrant : http://pastebin.com/LenLV7ZE

**Comment by laf** [comment]
Looks fine.  Probably worth running ./validate.php

**Comment by murrant** [comment]
@engageant Your discovery had not re-run yet.  Check now after running ./discovery.php.

**Comment by engageant** [comment]
OK, I'm getting valid data from the sensors now.  Not sure why this didn't work the first go-round.  Is there any way to report degrees Fahrenheit instead of Celsius? Both values are actually present in the SNMP data:

**iso.3.6.1.4.1.20916.1.9.1.1.1.1.0 = INTEGER: 2606** <-celsius
**iso.3.6.1.4.1.20916.1.9.1.1.1.2.0 = INTEGER: 7890**<-fahernheit
iso.3.6.1.4.1.20916.1.9.1.1.1.3.0 = STRING: "Room Temp"
iso.3.6.1.4.1.20916.1.9.1.1.2.1.0 = INTEGER: 2893
iso.3.6.1.4.1.20916.1.9.1.1.2.2.0 = INTEGER: 8407
iso.3.6.1.4.1.20916.1.9.1.1.2.6.0 = STRING: "Rack Temp"
iso.3.6.1.4.1.20916.1.9.1.2.1.0 = INTEGER: 0
iso.3.6.1.4.1.20916.1.9.1.2.2.0 = STRING: "AC Blower"
iso.3.6.1.4.1.20916.1.9.3.1.0 = ""

**Comment by murrant** [comment]
@engageant Librenms only supports celsius at this time.  I definitely can't see a reason to store anything other than celsius in the  database as it is a simple calculation to get Fahrenheit.

Feel free to open a ticket about displaying Fahrenheit.  Perhaps someone in the community will help you get it implemented.
