### ISSUE TITLE
Demo Not working

### ISSUE THREAD

**Issue by JohnnyFK** [librenms/librenms#3591]
I am interested in LibreNMS and want to checkout the demo.  I just get a "MySQL Error" when I click on the demo.

I have tried this with EI and Edge.  Sorry I'm on a new machine.  Haven't installed any other browsers yet.

**Comment by zanechua** [comment]
Same here.

**Comment by f0o** [comment]
Rebooting server, dmesg shows some disk issues.

**Comment by laf** [comment]
Feel free to use my dev box in the meantime:

https://web01.lathwood.uk
u: nmsdemo
p: nmsdemo

That will also give you access to our new v2 webui which is currently in development:

https://web05.lathwood.uk

**Comment by zanechua** [comment]
@laf 

Not sure if it's just me but your sites are loading really slowly. Sometimes timing out for me.

**Comment by f0o** [comment]
Reopening for personal reminder

**Comment by zanechua** [comment]
The official demo seems to be working now?

**Comment by Rosiak** [comment]
Fixed.

**Comment by FTBZ** [comment]
Down again "502 Bad Gateway"

**Comment by f0o** [comment]
Fixed, fpm somewhat died

**Comment by FTBZ** [comment]
You're the best, thanks.
