### ISSUE TITLE
Look into Oxidized reload_nodes call during auto-addhost

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#3592]
Seems like it's only doing it's thing during manual addhost?

**Comment by laf** [comment]
Code indicates it runs anytime a device is added not based on the method.

**Comment by murrant** [comment]
It doesn't actually work for some reason. I took a look at it at one point, but couldn't figure out why.

**Comment by murrant** [comment]
Oddly, it does seem to work for the previously added device when adding the next device.  So it could be some sort of race condition.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by murrant** [comment]
This is still an issue.  I couldn't figure out how to fix it when I investigated.

**Comment by laf** [comment]
Is this still an issue?

If it is, are we sure it's not an issue on the oxidized end? The code runs only when a device is added and we only serve the devices from the db for the api call so seems odd that this wouldn't work all the time.
