### ISSUE TITLE
Syslog.php loose the connection and not check mysql connection

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#3594]
Hi !

I use syslog in librenms it works sometime and sometimes not ! We debug the problem and see that syslog.php loose the connection to mysql and not check if the connection is not available ! as workaround we use /etc/php.ini mysqli.reconnect = On so that it work all the time but we not know if there are sideeffects in librenms ! Please help !

kind regards 

kristoferus75

**Comment by laf** [comment]
That to me says your mysql connection is going away, check your mysql servers log files for why.

**Comment by kristoferus75** [comment]
Hi !

I see mothing only connect and the wotking librenms connections

I have enabeld log in mariadb -> enabel query log !

tail -f /var/log/mariadb/query.log

What steps are nessacery to find the problem ?

kind regards
