### ISSUE TITLE
Riverbed logo 

### ISSUE THREAD

**Issue by anden4380** [librenms/librenms#3603]
is it possible to change the icon for rivebed to this [https://www.google.dk/imgres?imgurl=https://lh4.googleusercontent.com/-AbHPBY-pHIY/AAAAAAAAAAI/AAAAAAAABJ0/nPb0V5-zUqw/s0-c-k-no-ns/photo.jpg&imgrefurl=http://plus.google.com/u/0/115416552916607089128&h=250&w=250&tbnid=Ug1oGuU99igoAM:&tbnh=151&tbnw=151&docid=-ExtyMWsyIuZoM&itg=1&usg=__1113M9SZTLyZQzRtL829o9TLIEM=] ? today it doesn't look to good [http://imgur.com/LL4qDe3]

**Comment by murrant** [comment]
![image](https://cloud.githubusercontent.com/assets/39462/15920581/81097dca-2de0-11e6-8f07-3e46cb6069a2.png)

Which would be better?  I can't say the logo is particularly good as a 32x32 icon.  I prefer the orange text with transparent background.

**Comment by anden4380** [comment]
it will be the orange text with transparent background
