### ISSUE TITLE
Add support for HWg-STE Ethernet thermometer

### ISSUE THREAD

**Issue by MatGit5** [librenms/librenms#3606]
Please add support for HWg-STE Ethernet thermometer

http://www.hw-group.com/products/HWg-STE/STE_ip_temperature_sensor_en.html

[snmpwalk.txt](https://github.com/librenms/librenms/files/300389/snmpwalk.txt)
[discovery.txt](https://github.com/librenms/librenms/files/300388/discovery.txt)
[poller.txt](https://github.com/librenms/librenms/files/300387/poller.txt)

[HWg-STE_OID.txt](https://github.com/librenms/librenms/files/300393/HWg-STE_OID.txt)
[HWg-STE.mib.txt](https://github.com/librenms/librenms/files/300400/HWg-STE.mib.txt)

**Comment by Rosiak** [comment]
@MatGit5 Could you please try to see if it's possible to get more out of the SNMPWALK part?
Pretty sure it holds more information than that.

**Comment by MatGit5** [comment]
snmpwalk.
2 temperature sensors attached,
Temperature reported in Celsius, once in string value and then in Integer x 10.
[snmpwalk-sensors.txt](https://github.com/librenms/librenms/files/310673/snmpwalk-sensors.txt)

**Comment by Rosiak** [comment]
This still doesn't look like complete output.
Can you please post the output of this command?

```
snmpbulkwalk -On -v2c -c COMMUNITY HOSTNAME .
```

**Comment by MatGit5** [comment]
Actually, seems like this device does not support/respond to snmp bulk... maybe it will with a newer firmware.
It has two inputs that accept temperature and humidity sensors.
It is possible that other variants of HWg devices provide more info.
Please check out the demo here: http://ste.hwg.cz

**Comment by laf** [comment]
If you add the device as v1 then it won't use bulkwalk.
