### ISSUE TITLE
New custom service file for check_proc 

### ISSUE THREAD

**Issue by ghost** [librenms/librenms#3609]
I am using the nagios plugin (installed via yum) check_proc.  When using the command as a service, it is returning an unknown option:

[root@librenms librenms]# ./check-services.php -d
DEBUG!

Nagios Service - 5
Request:  /usr/lib64/nagios/plugins/check_procs -H localhost -C httpd
/usr/lib64/nagios/plugins/check_procs: invalid option -- 'H'
Perf Data - None.
Response: Usage:
check_procs -w <range> -c <range> [-m metric] [-s state] [-p ppid]
 [-u user] [-r rss] [-z vsz] [-P %cpu] [-a argument-array]
 [-C command] [-k] [-t timeout] [-v]
[root@librenms librenms]# http://i.imgur.com/8xWsOLm.jpg

This is how the service is setup in the WebGUI:
http://i.imgur.com/8xWsOLm.jpg

**Comment by paulgear** [comment]
I've got some patches for services checks in the works - should be ready in the next week or so; I will include this in them if no one gets to them sooner.

**Comment by f0o** [comment]
I'm not sure if check_proc is that usefull here, you will only be able to check for local processes of the poller machine.

Using the agent is a better way to monitor processes and their usages

**Comment by paulgear** [comment]
@f0o Agreed; I do wonder how many people would actually use this functionality...

**Comment by matept** [comment]
I was just going to use it for some testing and learning about the nagios plugin system with LibreNMS.  I asked about it in the IRC channel, and laf said to put in a ticket, so I did.

If it doesn't make sense, no big deal.

Thanks

**Comment by laf** [comment]
To be fair I didn't realise the check_proc didn't support remote hosts so we can't fix this anyway.
