### ISSUE TITLE
No network mapping and resource polling for autodiscovered nodes

### ISSUE THREAD

**Issue by gelato** [librenms/librenms#3618]
LibreNMS in current version can't gather info on CPU/Memory/Disk of autodiscovered nodes, also autodiscovered nodes are not visible in network map.

The issue is reproduceable - you have to setup new install of librenms, add your router manually and then start discovery (autodiscovery won't work without adding router first) - you will see all available information from the router and no information from autodiscovered nodes. But if you try to manually add one of already discovered by autodiscovery node manually - it will be added correctly and supply all information it can.

**Comment by laf** [comment]
I'm not sure I see that this happens, the code for discovering resources is the same for manually or auto-discovered hosts.

**Comment by gelato** [comment]
I can provide you with ansible role i wrote to deploy librenms - to show that this issue is easily reproduced. And i believe that code is the same, but still - issue exists. No health reports for autodiscovered nodes, no services check, no network mapping.
Daily updates are on and as i stated - i install librenms through ansible (manual installation type).

**Comment by laf** [comment]
Personally I'd like to here from others if they see the same issue before investigating further. 

Is this via a particular auto discover method?

**Comment by gelato** [comment]
@laf Yes, snmpscan.
And i noticed that it only uses v2c snmp scan on autodiscovery, while i vae v3 setted up.
No configs help:
$config['snmp']['community'] = array("public");
$config['snmp']['timeout'] = 1;            # timeout in seconds
$config['snmp']['retries'] = 5;            # how many times to retry the query
$config['snmp']['transports'] = array('udp', 'tcp');
$config['snmp']['version'] = "v3";         # Default version to use
$config['snmp']['port'] = 161;
$config['snmp']['v3'][0]['authlevel'] = "authPriv";  # noAuthNoPriv | authNoPriv | authPriv
$config['snmp']['v3'][0]['authname'] = "user";           # User Name (required even for noAuthNoPriv)
$config['snmp']['v3'][0]['authpass'] = "123";               # Auth Passphrase
$config['snmp']['v3'][0]['authalgo'] = "MD5";            # MD5 | SHA
$config['snmp']['v3'][0]['cryptopass'] = "123";             # Privacy (Encryption) Passphrase
$config['snmp']['v3'][0]['cryptoalgo'] = "DES";

I think it is connected:

http://jira.observium.org/browse/OBSERVIUM-857

Mine librenms also never tries snmp v3 - only v2c via autodiscovery.

SQL[SELECT * FROM `stp` WHERE `device_id` = '41'] /usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m RSTP-MIB -M /opt/librenms/mibs -t 1 -r 5 udp:HOSTNAME:161 dot1dStpProtocolSpecification.0No Such Object available on this agent at this OID

**Comment by vitalisator** [comment]
that line:
_SQL[SELECT * FROM stp WHERE device_id = '41'] /usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m RSTP-MIB -M /opt/librenms/mibs -t 1 -r 5 udp:HOSTNAME:161 dot1dStpProtocolSpecification.0No Such Object available on this agent at this OID_

says only that your device has no stp (Spanning Tree) implemented in MIB. That has no relationship to autodiscovery.

**Comment by laf** [comment]
No further info provided, closing.
