### ISSUE TITLE
Some Tripplite Poweralert values off by order of magnitude 

### ISSUE THREAD

**Issue by Fohdeesha** [librenms/librenms#3633]
Tripplite UPS Poweralert detection and polling is working very well these days however some values are still 10% of what they should be reading (they need to be multiplied by ten).

On my SMART2200RMXL2U and SMART1500RM2U the values that are off by ten times are Output Voltage, Output Current (possibly input and Battery current as well but my UPS doesn't display these values), and also Input and Output Frequency. 

Here's a picture to make the issue clear - http://i.imgur.com/oSyimoh.png

Thanks!

**Comment by murrant** [comment]
Can you please post the output of this command?
```
snmpbulkwalk -On -v2c -c COMMUNITY HOSTNAME .
```

**Comment by Fohdeesha** [comment]
Here's the output - http://pastebin.com/xWBQFSxn

I dug a little in an attempt to do a pull request myself, and I found that poweralert UPS devices use the generic rfc1628 UPS sensor type (for instance  includes/discovery/sensors/frequencies/rfc1628.inc.php)

The scaling is handled in those rfc1628.inc.php definition files, however they are incorrect for a few values on Tripplite equipment. I can't directly fix the scaling in rfc1628.inc.php as it would obviously then break other devices using that generic sensor type that currently have correct scaling, so I believe we need to create a new poweralert.inc.php sensor type (for frequency, current, etc), duplicate over the rfc1628 file and change the scaling as needed. 

Where I got stuck was then finding wherever in LibreNMS it actually defines what sensor type/files a device should use, because those would obviously need to be then pointed to the new sensor file. I found one instance in includes/defaults.inc.php ($config['modules_compat']['rfc1628']['poweralert'] = 1;) but that was it

**Comment by murrant** [comment]
It might not be as simple as that @laf :/
@Fohdeesha what version of firmware are you running?

**Comment by laf** [comment]
@murrant you mean it's different based on the firmware?

If firmware version is available to us I can update to check based on that.

**Comment by Fohdeesha** [comment]
@laf @murrant I'm running the latest Poweralert Local software 12.04.0055, this connects to UPS's locally over USB, and exposes it via SNMP on the network via the poweralert software. So it's a bit different than purchasing the tripplite SNMPWEBCARD that you install directly into their UPS and has network SNMP connectivity. However, the OID's "should" all be the same according to tripplite. I guess it is possible the scaling could be different between the two, but I don't have an snmpwebcard to test
