### ISSUE TITLE
Cannot modify dashboards after disabling AD auth

### ISSUE THREAD

**Issue by compuguy** [librenms/librenms#3634]
I disabled AD authentication because of limitations with the current ui. Currently edits to the dashboard are delayed and/or refused:

`ERROR: Could not update dashboard XX`

Or

`Error updating user dashboard config`

Edits done to the dashboard appear ~5 minutes later.

**Comment by pblasquez** [comment]
I ran into something similar and ended up having to assign the dashboard owner to an existing user as the AD id did not match up with anything in the users table.

Let me know if you need the exact table/column to change.

**Comment by laf** [comment]
Sounds like you've got memcached enabled, db queries are cached for 4 mins. You can either change this value, disable memcached or live with that.

**Comment by compuguy** [comment]
That was what I was suspecting, turned it down to 2 minutes, seems to have fixed the issue.
