### ISSUE TITLE
Centos 7 - VM Permission issue

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#3635]
Had to change permissions on /var/lib/php/session/ before being able to log in.

**Comment by laf** [comment]
I've just booted a cloned image in virtualbox and can login with no issues.

If you think it's an issue please feel free to provide an updated image.

**Comment by Rosiak** [comment]
Perm's is set to root:apache, should be root:nginx?
Let me know if you agree, I'll try to ship a new image then.

**Comment by scratchfury** [comment]
Changing root:apache to root:nginx fixed it for me.  I am not sure if /var/lib/php/wsdlcache/ needs to be changed too, but I changed that as well.

**Comment by thiagoc** [comment]
I think this occurs when you do a "yum update". Anyway, the right thing to do here is create a separate directory for it. See this: https://www.centos.org/forums/viewtopic.php?t=48750#p207122

**Comment by laf** [comment]
New image released.
