### ISSUE TITLE
Not logging overlapping IP addresses for interfaces on the same devices

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#3636]
```
GNS3-Router#
*Jun 11 01:10:19.731: %SYS-5-CONFIG_I: Configured from console by console
GNS3-Router#sh ip int brie
Interface              IP-Address      OK? Method Status                Protocol
FastEthernet0/0        10.1.1.1        YES manual up                    up      
Loopback1              192.168.1.1     YES manual up                    up      
Loopback2              192.168.1.1     YES manual up                    up      
Loopback3              192.168.1.1     YES manual up                    up      
```

<img width="950" alt="skaermbillede 2016-06-11 kl 01 14 04" src="https://cloud.githubusercontent.com/assets/6378934/15981139/d791bf58-2f71-11e6-95a8-a4fc920de3e0.png">

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
