### ISSUE TITLE
Authentication with LDAP/AD

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#3642]
Hi,

I am not sure if this question has been asked before however I need to get users to be authenticated by LDAP/AD when accessing LibreNMS but be authorized locally by assigning group memberships on the LibreNMS install instead of relying on LDAP/AD to do this. 

For an example; I want to be able to create a group A locally with level 7 and assign users "helpdesk", "it_support" and create group B with level 10 and assign user "admin" while all these users are being authenticated via LDAP/AD.

The reason for the request is that the LDAP/AD administration is not under our control and we do not want to create an extra burden/complications to LDAP/AD sys-admins by requesting them to assign certain users to certain groups. 

It this possible with the current setup?

**Comment by laf** [comment]
I don't personally use ldap/ad auth but I don't think so - seems that we rely on the groups to be returned from ldap.

Others may know more than me on this one.

**Comment by murrant** [comment]
I don't believe so.

Probably your only option would be to add all users individually into your config.php file.  This would allow you to manually control access and with some clear commets/formatting might not be too bad to maintain.

**Comment by breeman1** [comment]
Hi @murrant 

What would be the syntax to add the relevant users in the config.php?

**Comment by laf** [comment]
I've not come across anyway to add users to config.php if what was meant by that being people being able to login to the webui.

**Comment by murrant** [comment]
Yeah, sorry, I was thinking of groups.

**Comment by oam7575** [comment]
Perhaps a silly question; but you mention groups, helpdesk, it_support, admin.
Are there existing groups in AD that you can leverage?

If the it_support guys are already part of an `ou-admin` level group for supporting workstations - can to leverage that?

For admin users do you have an existing DC admin / Server admin group?

I would imagine that your helpdesk guys don't have full DC / Server admin rights but some limited sub set of permissions....???

**Comment by breeman1** [comment]
What would be ideal for us would be to continue adding users locally on LibreNMS including assigning them appropriate permission levels and only use AD for authentication-only purposes in a sense that a user would have to exist on both the LibreNMS and AD to successfully authenticate. However in an event of AD not being available, then user authentication would default to local database.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-authentication-with-ldap-ad/836
