### ISSUE TITLE
Errors creating tables

### ISSUE THREAD

**Issue by candlerb** [librenms/librenms#3647]
(Ubuntu 16.04, mysql-server 5.7.12, librenms 850170e0)

Problem 1: the eventlog table was not created.

WARNING: Cannot execute query (CREATE TABLE IF NOT EXISTS `eventlog` ( `event_id` int(11) NOT NULL AUTO_INCREMENT, `host` int(11) NOT NULL DEFAULT '0', `datetime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `message` text CHARACTER SET latin1, `type` varchar(64) CHARACTER SET latin1 DEFAULT NULL, `reference` varchar(64) CHARACTER SET latin1 NOT NULL, PRIMARY KEY (`event_id`), KEY `host` (`host`) ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
): Invalid default value for 'datetime'

Solution: change default to "0000-01-01 00:00:00" in `sql-schema/001.sql` and `build.sql`

Problem 2: other errors are reported, but it's not clear what they are.

~~~
035 -> 036 ... done (1 errors).
040 -> 041 ... done (1 errors).
047 -> 048 ... done (3 errors).
054 -> 055 ... done (1 errors).
055 -> 056 ... done (2 errors).
072 -> 073 ... done (2 errors).
108 -> 109 ... done (1 errors).
109 -> 110 ... done (4 errors).
110 -> 111 ... done (1 errors).
~~~

For example: there is no "alert_schedule" table created. It seems this ought to exist according to `sql-schema/036.sql`, but it does not according to `build.sql`

**Comment by laf** [comment]
Do you have mysql strict mode on? If so I'd suggest you disable this and re-import.

**Comment by f0o** [comment]
Do you by chance have strict mode enabled?

On 13 June 2016 10:24:44 CEST, Brian Candler <notifications@github.com> wrote:
>(Ubuntu 16.04, mysql-server 5.7.12, librenms 850170e0)
>
>Problem 1: the eventlog table was not created.
>
>WARNING: Cannot execute query (CREATE TABLE IF NOT EXISTS `eventlog` (
>`event_id` int(11) NOT NULL AUTO_INCREMENT, `host` int(11) NOT NULL
>DEFAULT '0', `datetime` datetime NOT NULL DEFAULT '0000-00-00
>00:00:00', `message` text CHARACTER SET latin1, `type` varchar(64)
>CHARACTER SET latin1 DEFAULT NULL, `reference` varchar(64) CHARACTER
>SET latin1 NOT NULL, PRIMARY KEY (`event_id`), KEY `host` (`host`) )
>ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
>): Invalid default value for 'datetime'
>
>Solution: change default to "0000-01-01 00:00:00" in
>`sql-schema/001.sql` and `build.sql`
>
>Problem 2: other errors are reported, but it's not clear what they are.
>
>~~~
>035 -> 036 ... done (1 errors).
>040 -> 041 ... done (1 errors).
>047 -> 048 ... done (3 errors).
>054 -> 055 ... done (1 errors).
>055 -> 056 ... done (2 errors).
>072 -> 073 ... done (2 errors).
>108 -> 109 ... done (1 errors).
>109 -> 110 ... done (4 errors).
>110 -> 111 ... done (1 errors).
>~~~
>
>For example: there is no "alert_schedule" table created. It seems this
>ought to exist according to `sql-schema/036.sql`, but it does not
>according to `build.sql`
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/3647

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by f0o** [comment]
Haha laf, quick fella

**Comment by laf** [comment]
@f0o only just though :)

**Comment by candlerb** [comment]
Thanks, fixed this now:

~~~
# cat /etc/mysql/mysql.conf.d/librenms.cnf
[mysqld]
# Librenms does not like STRICT_TRANS_TABLES:
# [WARN]    You have MySQL STRICT_TRANS_TABLES enabled, it is advisable to disable this until full support has been added: https://dev.mysql.com/doc/refman/5.0/en/sql-mode.html

sql_mode = "ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
~~~

Blasted away the database and recreated. Now I just get one error from `build_base.php`:

~~~
108 -> 109 ... done (1 errors).
~~~

**Comment by laf** [comment]
Errors aren't necessarily an issue. We have limitations with the current schema system which is being addressed long term.
