### ISSUE TITLE
Problems creating new alert templates

### ISSUE THREAD

**Issue by HendrikF** [librenms/librenms#3650]
## Steps to reproduce
Click on the edit pencil next to a template, but you do not have to edit anything.
Next close the modal and click on "Create new alert template".

## Problem
In the edit modal the previously viewed template is filled in, but when clicking on "Create template" it updates the previously viewed template instead of creating a new one.

I doubt, that the template is intended to be prefilled, but apart from that the creation should work.

**Comment by laf** [comment]
Thanks for letting us know.

**Comment by HendrikF** [comment]
No problem, only lost 2 templates ;)

Keep up the otherwise very good work! :+1:
