### ISSUE TITLE
Right place for Port (SFP) DOM/DDM information

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#3654]
I want to implement some SFP Port information (RX,TX,voltage,current) information on an PBN device.
Has some one used that, an what will be the right place in the code and the GUI for the graphs?
on the Ports page or Health?

The SNMP information for an particular port looks like that:
snmpwalk -v2c -c public -m NMS-IF-MIB kx-test-rt1 ifSfpParameterTable
...
NMS-IF-MIB::txPower.23 = INTEGER: -5
NMS-IF-MIB::rxPower.23 = INTEGER: -5
NMS-IF-MIB::temperature.23 = INTEGER: 9516
NMS-IF-MIB::vlotage.23 = INTEGER: 32835
NMS-IF-MIB::curr.23 = INTEGER: 8642
NMS-IF-MIB::ifSfpParameterEntry.7.23 = STRING: "PBN             "
...

**Comment by laf** [comment]
@vitalisator 

Should be able to do that via the sensors module, temperature and voltage.

**Comment by vitalisator** [comment]
@laf, I would like to see that information port based, not device based.
make more sense If a device has 48port with each 5 metrics. I wonder if someone has done that before so I can see some examples.

**Comment by laf** [comment]
You can see that on per port basis:

![image](https://cloud.githubusercontent.com/assets/3941142/16034989/9f785896-320c-11e6-8c08-d0a2f539b844.png)

That's not tied into the ports table but the sensors section is exactly where these things do belong.

**Comment by vitalisator** [comment]
@laf, thanks. Will try to dig into on my next free time :-)

**Comment by vitalisator** [comment]
@laf, what is the difference between 
includes/discovery/sensors/dbm.inc.php
and
includes/discovery/sensors/signal.inc.php

I found no folder for dbm, was it used before?

**Comment by laf** [comment]
dbm was added by @Rosiak for future use, it's not currently doing anything.

signal is for wireless devices mostly.

**Comment by laf** [comment]
Do you need anything further on this or can we close?
