### ISSUE TITLE
Only "uptime" shows in influxdb, also RRD graphs stop updating

### ISSUE THREAD

**Issue by fattylewis** [librenms/librenms#3656]
Hi,

I know support for influxdb is "alpha at best", but i just thought id make you guys aware that currently if you enable influxdb then the RRD graphs stop updating and also only a devices "uptime" is sent through to influxdb.

I can add any logs or try anything as this is a test box if need be. 

This is on a CentOS 7 machine. Running latest master of librenms and tested with latest influxdb (Also tested with version mentioned in the librenms docs - 0.9.4)

EDIT

I have just noticed that by changing the transport to UDP instead of http, the RRD graphs have started updating again?

**Comment by laf** [comment]
This sounds like a local issue as mine works fine.

`./poller.php -h HOSTNAME -d -r`

See what is output - I expect you will see an error

**Comment by fattylewis** [comment]
When the influxdb transport is set to http, i get the following error:

```
END
PHP Fatal error:  Call to undefined function GuzzleHttp\Handler\curl_reset() in /opt/librenms/lib/influxdb-php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 77

Fatal error: Call to undefined function GuzzleHttp\Handler\curl_reset() in /opt/librenms/lib/influxdb-php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 77

```

Then when i set hte influxdb to "udp" the poller completes but not additional data is sent to influx.

I imagine this is something im doing wrong.

**Comment by laf** [comment]
What version of php? I'm going to guess 5.4 or lower?

**Comment by fattylewis** [comment]
You would be correct. 

PHP 5.4.16

**Comment by laf** [comment]
The influxdb php library we use is 5.5 or newer so you will need to disable influx support or upgrade php
