### ISSUE TITLE
Oxidized::version not found for only 1 device, diffs work

### ISSUE THREAD

**Issue by bsiders** [librenms/librenms#3658]
Hey, I have an issue with Oxidized in which only 1 device, an ASA, that used to have the config versions displayed, is now unable to display any version

On my oxidized instance, everything appears to work fine.
On the LibreNMS side, all devices except this one ASA work fine.
The ASA simply states "version not found" for any of my 50 versions, however if I were to click the diff/compare, I get the diffs between the versions. I cannot see the full configuration as I used to

http://i.imgur.com/xXKv1n5.png And I could click diffs and see proper output, but cant see the whole config.

Please let me know what I can do to help or if I need to re-explain.

**Comment by laf** [comment]
Does the oxidized webui work for this device?

**Comment by bsiders** [comment]
Yes, no issues on the oxidized end.

The strange part is on LibreNMS, the version diffs work. Shows only diffs between version configs

But when trying to view individual versions/full config, receive version not found for all.

**Comment by bsiders** [comment]
I have tried re-adding the device to both oxidized and librenms with the same result. I have updated the oxidized gem to the latest as well.

**Comment by bsiders** [comment]
I've just redeployed Oxidized entirely, fresh and up-to-date.

Same result, all but this ASA show up on LibreNMS. Diffs work as described before, but the full config simply returns "version not found" 100% functioning as intended from the Oxidized-web,

**Comment by laf** [comment]
Can you post your oxidized config

**Comment by bsiders** [comment]
`---
interval: 3600
log: /home/oxidized/.config/oxidized/log
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: omitted:8888
vars: {}
groups: {}
input:
  default: ssh
  debug: /home/oxidized/.config/oxidized/debug
  ssh:
    secure: false
output:
  default: git
  git:
    user: user
    email: user@omitted.com
    repo: "/home/oxidized/.config/oxidized/devices.git"
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4
model_map:
  cisco: ios
hooks:
  post-commit:
    type: exec
    events: [node_success, post_store]
    cmd: 'cd /home/oxidized/.config/oxidized/devices.git && git push -f -q origin master'`

**Comment by laf** [comment]
Thanks, can you post the line from the csv source that contains this device - feel free to mask info

**Comment by bsiders** [comment]
asa_ipaddress : asa : user : password : password

Nothing had changed for months, just one morning I noticed this issue, previous day there was no issue. I have the daily updates disabled, but updated librenms today with no change.

**Comment by laf** [comment]
I can't replicate this :(

We call: `/node/version?node_full=HOSTNAME&format=json`

We use the oid value from this to display the default config by:

`/node/version/view?node=HOSTNAME&group=GROUPNAME&oid=OID&date=DATE&num=TOTAL&format=text`

TOTAL = the number of configs we see in the first call above.
GROUPNAME if you use groups (doesn't look like you do)
OID and DATE should be in the output of the first call.

If you can provide access to your LibreNMS I can take a further look.

**Comment by bsiders** [comment]
Which LibreNMS file contains the logic for Oxidized?

I confirm that the OID is correct for the call and the latest ASA config version.

There are only 2 versions since I've re-deployed Oxidized and the "Show diff" function works from inside LibreNMS WebGUI. 

It shows the "Last sync" as current, I can on Oxidized, re-sync and the LibreNMS updates the "Last sync" field correctly. Sync status: success and following fields are accurate.

**Comment by laf** [comment]
The file is `html/pages/device/showconfig.inc.php`

Can you post the output of those two api calls I mentioned earlier?

**Comment by bsiders** [comment]
/node/version/view?node=HOSTNAME&group=GROUPNAME&oid=OID&date=DATE&num=TOTAL&format=text

I filled in the details here, except for the GroupName.
Returns version not found

I removed the &group=GROUPNAME entirely.
It shows the config.

I think we are on to something, it seems LibreNMS might be putting in a blank/invalid group when its not needed.

It's odd because this just happened one day and neither Oxidized nor Libre had been updated in the past months.

Enable the return of groups to Oxidized has been set to No
Set the default group returned has been blank
Reload Oxidized nodes list, each time has been set to No

Enable Oxidized support Yes
URL is correct
Enable config versioning access Yes

**Comment by laf** [comment]
Try this patch:

```bash
diff --git a/html/pages/device/showconfig.inc.php b/html/pages/device/showconfig.inc.php
index 7ae4bd5..587cd56 100644
--- a/html/pages/device/showconfig.inc.php
+++ b/html/pages/device/showconfig.inc.php
@@ -176,7 +176,7 @@ if (is_admin()) {
                 $text = file_get_contents($url); // fetch diff
             } else {
                 // fetch current_version
-                $text = file_get_contents($config['oxidized']['url'].'/node/version/view?node='.$oxidized_hostname.'&group='.(!empty($node_info['group']) ? $node_info['group'] : '').'&oid='.$current_c
+                $text = file_get_contents($config['oxidized']['url'].'/node/version/view?node='.$oxidized_hostname.''.(!empty($node_info['group']) ? '&group='.$node_info['group'] : '').'&oid='.$curren
             }
         }
         else {  // just fetch the only version
```

**Comment by bsiders** [comment]
/node/version/view?node=HOSTNAME&group=GROUPNAME&oid=OID&date=DATE&num=TOTAL&format=text

I filled in the details here, except for the GroupName.
Returns version not found

I removed the &group=GROUPNAME entirely.
It shows the config.

I think we are on to something, it seems LibreNMS might be putting in a blank/invalid group when its not needed.

It's odd because this just happened one day and neither Oxidized nor Libre had been updated in the past months.

Enable the return of groups to Oxidized has been set to No
Set the default group returned has been blank
Reload Oxidized nodes list, each time has been set to No

Enable Oxidized support Yes
URL is correct
Enable config versioning access Yes

**Comment by bsiders** [comment]
Same result.

I additionally tried omitted the reference to the group in that line you edited with no change either.

**Comment by laf** [comment]
That patch does what you said worked for you in that it doesn't put &group= in it.

I think you'll need to start putting some echo statements in that file and output things as the script goes along to find the issue. I can't replicate this and with what you've said so far that patch should resolve the initial config retrieval.

**Comment by murrant** [comment]
I wonder. What is the output of `$config['oxidized']['url'].'/node/show/'.$oxidized_hostname.'?format=json'` if you visit that in the browser (with the proper things filled in).  Particularly, what does it return for group?

**Comment by bsiders** [comment]
null is returned for group, on this particular device as well as others.

"group":null

**Comment by murrant** [comment]
That means there would be no group name in your url.  Like this:
`/node/version/view?node=HOSTNAME&group=&oid=OID&date=DATE&num=TOTAL&format=text`

**Comment by bsiders** [comment]
Is there a way to see what LibreNMS is trying to display? or see what URL it ended up trying to use?

**Comment by laf** [comment]
You will need to put some echo statements in the file mentioned earlier to output what we use.

**Comment by bsiders** [comment]
It appears LibreNMS was not attempting to resolve the node dns name and reverted to use the ip address as the node name in the url

I changed the Oxidized node to the IP instead of hostname and was able to view the config again on libre.

I cannot confirm if it was a unknown DNS change or still a LibreNMS hiccup. I'm going to bet something changed on DNS without anyone saying anything.

I appreciate the time and assistance.
