### ISSUE TITLE
Device Graphs for Total Traffic, CPU, Memory, etc through the API

### ISSUE THREAD

**Issue by Jaredn** [librenms/librenms#3666]
It appears that the API can't provide device level graphs for things like Total Device Traffic, CPU, Memory, Storage, etc (pretty much all of the stuff provided on the main page view of a single device).  The only graphs I ever get in response to get_graphs is:

```
  "graphs": [
    {
      "desc": "Poller Time",
      "name": "device_poller_perf"
    },
    {
      "desc": "Ping Response",
      "name": "device_ping_perf"
    },
    {
      "desc": "Running Processes",
      "name": "device_hr_processes"
    },
    {
      "desc": "Users Logged In",
      "name": "device_hr_users"
    },
    {
      "desc": "ICMP Statistics",
      "name": "device_netstat_icmp"
    },
    {
      "desc": "ICMP Informational Statistics",
      "name": "device_netstat_icmp_info"
    },
    {
      "desc": "IP Forwarding Statistics",
      "name": "device_netstat_ip_forward"
    },
    {
      "desc": "SNMP Statistics",
      "name": "device_netstat_snmp"
    },
    {
      "desc": "SNMP Packet Type Statistics",
      "name": "device_netstat_snmp_pkt"
    },
    {
      "desc": "TCP Statistics",
      "name": "device_netstat_tcp"
    },
    {
      "desc": "UDP Statistics",
      "name": "device_netstat_udp"
    },
    {
      "desc": "System Uptime",
      "name": "device_uptime"
    }
  ]
```

I think there would need to be an update to get_graphs in order to return all of the actually available graphs (and / or the ability to graph them through the API like graph.php does in the GUI).  

In my opinion anything that works through graph.php should be available through the API, so that 3rd party apps can integrate in a more meaningful way.  I'm writing a tool which is integrating data from many sources (LibreNMS included), and it would be great to be able to get some of the high level graphs/data that Libre polls already for a device.  

Is this something that would be fairly easy to implement, or would it be a larger refactor than it's worth?

**Comment by laf** [comment]
That api call is a big mis leading, it's basically all the registered graphs for that device that aren't necessarily standard.

The api call accepts :type: in the url and you should be able to just pass what you want on so a call for https//nms.lathwood.uk/api/v0/devices/localhost/device_processor results in http://www.lathwood.co.uk/proc.png

When you go to a graph in your browser you would see something like `type=device_processor`, use that same type within the api call.

**Comment by laf** [comment]
No response provided.
