### ISSUE TITLE
Add CLI support to upgrade from snmpv2 to snmpv3 on existing hosts

### ISSUE THREAD

**Issue by siffland** [librenms/librenms#3674]
I googled and googled and could not find where this could be done (so if it can please forgive this request).  We are rolling out snmpv3 and need to upgrade all of our librenms clients.  This would be so much easier from the CLI.  I dont want to lose any historical data by removing the node and simply being able to upgrade all 400 machine en mass from the CLI would be swell.

Thanks,
Sean

**Comment by laf** [comment]
You mean change the snmp details from v2 to v3? You can do that via a SQL query - if you need help just ask.

**Comment by siffland** [comment]
I do need help.  I wish i had crazy mad sql skills but i don't.  But i can log in the database and poke around so if i get a query to run i can do it.

thanks,

Sean

**Comment by laf** [comment]
Please backup your devices table before you carry on.

If you want to update all devices then do this (changing the values marked with %%%%)

`UPDATE devices SET authlevel='%%authlevel%%', authname='%%authname%%', authpass='%%authpass%%', authalgo='%%authalgo%%', cryptopass='%%cryptopass%%', cryptoalgo='%%cryptoalgo%%', snmpver='v3';`

Some of those values won't be used for instance if the authlevel is NoAuthNoPriv then you only need to update the snmpver column.

If you only want to change it on some devices then you need to add a `WHERE hostname LIKE '%_something_%` before the ;

**Comment by siffland** [comment]
that worked great thanks.
