### ISSUE TITLE
Device Groups only allows one rule

### ISSUE THREAD

**Issue by murrant** [librenms/librenms#3683]
This rule returns all devices instead of one device.
`%devices.device_id > "0" && %sensors.sensor_id < "179" &&`

Looking at the SQL:
`SELECT DISTINCT(devices.device_id) FROM devices,sensors WHERE devices.device_id > 0 AND sensors.sensor_id = 179`

Because of DISTINCT(**devices**.device_id), it only selects from that table.

Thoughts @f0o ?

**Comment by f0o** [comment]
I'll have to test this. It should return unique device_id's based on the query's condition.

But you're right, the SQL misses a glue! Likely a bug. Odd that it didnt show up earlier, I got many group definitions based on port-descr, uname's, apps, ...

Will check my install

**Comment by f0o** [comment]
Can reproduce. It seems my rules only worked because the devices table came last.

Lucky this is a small fix. Needs to add the resolveglue function from alerting into it

**Comment by f0o** [comment]
Oh boy, the join variable exists but it's missing in the select query... what happened there heh

**Comment by murrant** [comment]
I noticed that :-)

**Comment by f0o** [comment]
making the PR now
