### ISSUE TITLE
Graph Widget inner image height

### ISSUE THREAD

**Issue by alangregory** [librenms/librenms#3687]
After 07455a6e0affec9ce53efae6dac027b9531b5b95 , graphs widget doesn't take 100% height anymore.
Before
![rsz_before](https://cloud.githubusercontent.com/assets/1170503/16195263/2604ec6e-36cf-11e6-96cb-16e9245a6121.png)
After
![rsz_after](https://cloud.githubusercontent.com/assets/1170503/16195266/2b063e66-36cf-11e6-8b47-38b2421a02d9.png)

**Comment by Rosiak** [comment]
Is this still an issue?

**Comment by alangregory** [comment]
Yes, can't do a high density dashboard, to much with space at bottom.
I think it's because of https://github.com/librenms/librenms/commit/07455a6e0affec9ce53efae6dac027b9531b5b95#diff-95e9f312d3fe082bb4efd6acfb0fc2f1R1872
