### ISSUE TITLE
How to upgrade an "offline" LibreNMS install

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#3695]
HI,

I would appreciate being guided on the best approach to properly and update/upgrade a LibreNMS install that is not connected to the internet. It is possible or rather permissible to just clone the online repository from my laptop (with internet access), copy the repository to the USB flash disk and manually copy the files to the server running LibreNMS?

**Comment by laf** [comment]
You can do that, just need to make sure permissions are correct and you put the rrd and config.php files/folders back to the new install once done.

**Comment by breeman1** [comment]
How will the updating of the database be handled in this case. Would it be a matter of just running the daily.php script?

**Comment by murrant** [comment]
@breeman1 You could also set up a new git remote in the offline computer and merge from that.

**Comment by f0o** [comment]
I suggest:
1) clone to medium
2) replace old install with new clone, retain logs and rrd dirs as well as config
3) run .`/daily.sh post-pull`
