### ISSUE TITLE
All maintenance windows are shown as "Lapsed"

### ISSUE THREAD

**Issue by HendrikF** [librenms/librenms#3699]
All maintenance windows we created are shown as Lapsed and therefore can not be edited.

Screenshot: http://prntscr.com/bjghmf
The time on the machine running LibreNMS was `Mi 22. Jun 09:55:06 CEST 2016`.

Can someone confirm this?

Versions:
```
Version	f952e49
DB Schema	#117
Apache	2.4.10 (Debian)
PHP	5.6.22-0+deb8u1
MySQL	10.0.25-MariaDB-0+deb8u1
RRDtool	1.4.8
```

**Comment by f0o** [comment]
Check that your OS timezone, MySQL timezone and PHP's timezone are all correct

**Comment by HendrikF** [comment]
MySQL:
```
+--------------------+---------------------+
| @@global.time_zone | @@session.time_zone |
+--------------------+---------------------+
| SYSTEM             | SYSTEM              |
+--------------------+---------------------+
```
PHP:
```
date.timezone => Europe/Berlin => Europe/Berlin
```
/etc/timezone: `Europe/Berlin`

Seems all fine

**Comment by HendrikF** [comment]
Even if I create a window beginning and ending in two days, LibreNMS shows it as Lapsed. And this should not be affected by time zones.

**Comment by budbach** [comment]
+1

**Comment by murrant** [comment]
The "map to" could be related to the recent device group changes.  Should that be a separate issue?

**Comment by budbach** [comment]
@murrant sorry - I updated code and that part of the issue seemed to go away.  Still have the "lapsed" issue though.

**Comment by murrant** [comment]
Ok, thanks for the update.

**Comment by laf** [comment]
PR submitted for the lapsed issue.

I don't see an issue with the groups though, appear ok for me.

**Comment by HendrikF** [comment]
I can confirm that this is only a bug with the WebUI. Today we did the maintenance and LibreNMS did not send alert mails.

Are we able to edit/delete maintenance windows with this bug fixed?
