### ISSUE TITLE
Memory alter, without buffers and cache

### ISSUE THREAD

**Issue by siffland** [librenms/librenms#3706]
I am trying to write a memory alert.  If the memory is greater than 85% used then alert.  I can get this to work using mempool-perc, the problem is i need this rule to work minus the buffers and cache.  I see on the detailed memory graph it shows (-sh, bu .ca).  Can i write a rule around this.  Currently most of my servers trigger a 85% mempool_perc rule since they buffer as much as they can, but most are only really using about 25% of memory.  But the Virtual includes the buffers/cache

Thanks,

Sean

**Comment by laf** [comment]
I think -Sh bu .ca are within the rrd file so we can't alert on that.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
