### ISSUE TITLE
Ports page empty

### ISSUE THREAD

**Issue by jerebernard** [librenms/librenms#3710]
Hello,

I'm in the last version of librenms and when I click on "Ports > All Ports" the page is empty.
the redirection goes to http://server/ports but nothing on the screen.
This is the firebug result : 
`<html>
<head></head>
<body></body>
</html>`

Body is empty.

When I click on Ports > Errored" the body is not empty the page is ok.

Can someone help me with this ?
Regards,

**Comment by jerebernard** [comment]
Issue solved : Memory issue
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 573440 bytes) in /opt/librenms/html/pages/ports/list.inc.php on line 71, referer: http://server/ports/debug=yes/

**Comment by jerebernard** [comment]
In fact the issue is not link with the RAM but more with PHP bug.
Anyone to help with this or any guy with the same issue ?

**Comment by jerebernard** [comment]
In /etc/php5/apache1/php.ini we changed memory from 128 MB to 512 MB and restart apache and it work.
But when we click on all ports page load all ports and a page which contained 50 or 100 entries.
I have 6000 ports so the load is huge.

**Comment by laf** [comment]
Ports page is not paginated so you need to allocate more ram as you've done.

We have an issue open to add this support already #2705
