### ISSUE TITLE
cURL 'PATCH' says "message": "Device field to patch has not been supplied"

### ISSUE THREAD

**Issue by beeelze** [librenms/librenms#3716]
Hi,

I've been working with the API of LibreNMS and I'm very pleased with how things work. There is however one thing I don't understand, and that is about updating a device field through the API. It gives me the error in the subject of this issue. This is the command I run:

curl -X PATCH -d '{"field": "notes", "data": "nice device"}' -H 'X-Auth-Token: xxxxxxx' http://librenms.mydomain.net/api/v0/devices/hostname

Is this a bug?

**Comment by laf** [comment]
```bash
 curl -X PATCH -d '{"field": "notes", "data": "test"}' -H 'X-Auth-Token: 967abffc8e85bcae5f39ffd35rwefdsef' http://DOMAINapi/v0/devices/localhost
{
    "status": "ok",
    "message": "Device notes field has been updated"
}
```

Works for me.

[root@www ~]# curl -V
curl 7.15.5

**Comment by beeelze** [comment]
root@server$ curl -V
curl 7.35.0

var_dump('php://input') returns NULL. I've set both allow_url_fopen and allow_url_include to 'On' and restarted my Apache2 server. Still no luck.

**Comment by laf** [comment]
Validate your install.

**Comment by beeelze** [comment]
@laf What do I need to validate/verify?

**Comment by laf** [comment]
http://docs.librenms.org/Support/FAQ/#faq18

**Comment by beeelze** [comment]
I guess I have to update my install:

root@server:/opt/librenms# ./validate.php 
Version info:
[WARN]    Your install is out of date: 207a7e1caaeaa088c0edf4a72a79d1a01731770d
DB Schema: 6
PHP: 5.5.9-1ubuntu4.17
MySQL: 5.5.49-0ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

[OK]      Database connection successful
[OK]      fping has been found

**Comment by laf** [comment]
I'm not sure what else to suggest, it works for me :(

**Comment by beeelze** [comment]
Yeah, but you don't know why ^^ All I know is that LibreNMS gets the raw data send with CURL PATCH with 

$data = json_decode(file_get_contents('php://input'), true);
var_dump($data); // returns NULL

I've been searching around, but could not a solution for this. Any other ideas?

**Comment by f0o** [comment]
Can only speak for nginx. Not sure if this might be an apache oddity or so :S

**Comment by beeelze** [comment]
I'm out of ideas as well, I guess I'll have to do regular UPDATE queries to the libreNMS database then as a work-around ;-(

**Comment by laf** [comment]
My tests are all in Apache.

Check your apache version supports PATCH and that your apache config is EXACTLY correct.

**Comment by beeelze** [comment]
How do I check that? I googled some myself and found that I need to apply

<Limit GET POST PUT DELETE PATCH>
  Allow from all
</Limit>

to my .htaccess file, doesn't do much so far.

**Comment by laf** [comment]
Check our install docs, pay particular attention to the version of apache you are running and in turn what the config should be.

**Comment by beeelze** [comment]
The problem has been resolved, I did a lot to fix other things along the way, so I don't know which step did the final blow :-) I think it had to do with the fact that, since my upgrade to PHP 5.6, the wrong php.ini file was loaded by apache2. I changed from 

/etc/php5/apache2/php.ini

to

/etc/php/5.6/apache2/php.ini
