### ISSUE TITLE
weird graphs on last commit

### ISSUE THREAD

**Issue by crcro** [librenms/librenms#3727]
After last commit on git, there are some issues with the detail page of a device like: aggregate traffic graph is not shown, ports graph have weird AR/size

Version	692c29c
DB Schema	#118
Apache	2.4.6 (CentOS) PHP/5.4.16
PHP	5.4.16
MySQL	5.5.47-MariaDB
RRDtool	1.4.8

![bad_graph](https://cloud.githubusercontent.com/assets/3048315/16382622/4c183828-3c8a-11e6-9f0e-e8ea45a54275.jpg)

**Comment by laf** [comment]
I don't think anything has been merged to do with this.

I'd suggest forcing a full browser refresh.

**Comment by crcro** [comment]
@laf ... you're right, on different workstation is all good
