### ISSUE TITLE
PHP Memory Usage

### ISSUE THREAD

**Issue by TheBigfoot** [librenms/librenms#3728]
Hi together,
I ran today into an issue with LibreNMS and I wanted to ask if this is plausible.

We found LibreNMS crashing with PHP out of Memory:
`PHP Fatal error:  Allowed memory size of 262144 bytes exhausted`

When calling the dashboard PHP crashed with this every time. Our LibreNMS is handling ~550 Hosts with ~7100 Ports. Webserver is Apache 2.4 with PHP 5.6. 

We figured out it was working with PHP memory_limit 270MB. To avoid problems we have set this now to 1GB..

What is the expected memory_limit for PHP with different environments?

**Comment by laf** [comment]
There is no hard and fast rule with this, you just need to keep an eye on it and adjust where necessary.

1Gb will be (way) more than enough I'd have thought.
