### ISSUE TITLE
RRDCache on Ubuntu Server 16.04

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#3735]
Hi,

I am trying to install LibreNMS on a fresh install of Ubuntu 16.04. I am wanting to improve disk I/O performance and am wondering if RRDCached will help in this regard. Has anyone tried this setup as I see the content of the RRDCached config files looks different in 16.04 than it did in 14.04 making this guide here, https://groups.google.com/forum/#!topic/librenms-project/jGndVhkgdEY kind of redundant.

Your help will be appreciated. Thanks.

**Comment by spinza** [comment]
Running RRDCached on Ubuntu 16.04, but this is not really an issue? This is more of support request.

**Comment by breeman1** [comment]
Well, when I deployed LibreNMS on Ubuntu 14.04 the disk I/O was a serious challenge for us leading to gaps in traffic graphs until we installed RRDCached as per the guide mentioned in my first post with performance improving by almost 40%. I would like to emulate the same; if possible, with Ubuntu 16.04 before rolling the install out to production.

**Comment by spinza** [comment]
Just install and use.   Though posting an issue on github is not the way to get support...

**Comment by paulgear** [comment]
Here's how I have rrdcached configured on my development system.  Following is the contents of `/etc/default/rrdcached`, minus comments - anything you don't see here can be commented out and left as the default:
```
DAEMON=/usr/bin/rrdcached
WRITE_TIMEOUT=1800
WRITE_JITTER=1800
BASE_PATH=/opt/librenms/rrd/
JOURNAL_PATH=/var/lib/rrdcached/journal/
PIDFILE=/var/run/rrdcached.pid
SOCKFILE=/var/run/rrdcached.sock
SOCKGROUP=librenms
BASE_OPTIONS="-B -F"
```
