### ISSUE TITLE
Juniper VLAN numbers are incorrect

### ISSUE THREAD

**Issue by BradHooper** [librenms/librenms#3740]
The Juniper VLAN numbers shown in LibreNMS are not the same as VLAN-IDs configured on the device.

[vlan-discovery.txt](https://github.com/librenms/librenms/files/338183/vlan-discovery.txt)
[vlan-snmpbulkwalk.txt](https://github.com/librenms/librenms/files/338196/vlan-snmpbulkwalk.txt)

Happy to provide SNMP Access.

VLAN 515 (Customer-Transport-Account-1752) is a good example.

dot1qVlanStaticName.17 = Customer-Transport-Account-1752

These VLAN numbers are not configured on the device and never have been. 

```
Vlan 7  Customer-Colo-Account1662   
Vlan 10 Customer-Colo-Account1659   
Vlan 11 Customer-Colo-Account1666   
Vlan 12 Customer-Colo-Account1691   
Vlan 13 Customer-Colo-Account1738   
Vlan 16 Customer-Colo-Account1721   
Vlan 17 Customer-Transport-Account-1752
```

**Comment by laf** [comment]
We don't use a juniper mib for this so we will need to add better support, access would be great.

If you can catch us on irc that would be brill.

**Comment by laf** [comment]
Can you double check if this is still an issue. If it is please provide the output of `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .`

**Comment by BradHooper** [comment]
Isn't fixed on the VLAN page however on the ports page the VLAN is now shown correctly. I can get you an snmpwalk if still required.

![screenshot from 2016-10-23 11-11-20](https://cloud.githubusercontent.com/assets/5325740/19622886/9443b6f2-9911-11e6-94f7-68069fc88a7a.png)

![screenshot from 2016-10-23 11-12-52](https://cloud.githubusercontent.com/assets/5325740/19622890/aa2ab218-9911-11e6-98c1-0fe660727ca4.png)

**Comment by laf** [comment]
Can you show more of a screenshot? That just indicates to me that one port is tagged vlan 521 but on that device you have a vlan 31 called Customer-OOB-Account-1825

**Comment by BradHooper** [comment]
There is no VLAN 31. 

VLAN name Customer-OOB-Account-1825 is actually VLAN 521

**Comment by laf** [comment]
I think this will be easier if you can provide the output of:

`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .`

**Comment by BradHooper** [comment]
Emailed you laf. Can provide it to anyone else the requires.

**Comment by laf** [comment]
Sorry for the delay. Can you test #6597

Should resolve it for you.

**Comment by BradHooper** [comment]
Sorry for the delay. I've tested this. The VLAN numbers are now correct however the interfaces attached to VLANs are incorrect. I have emailed you with discovery and snmpwalks.

**Comment by techhelper1** [comment]
Please look into this as we are affected as well.
