### ISSUE TITLE
Application page

### ISSUE THREAD

**Issue by crcro** [librenms/librenms#3746]
The main Apps page is generated ok but the graphs shown are empty (if you click them everything is ok).
The Subpage of Apps (like PowerDNS app) does not show any graph for host, just a list of host that have PowerDNS monitoring enabled.

Version	2faa266
DB Schema	#119
Apache	2.4.6 (CentOS) PHP/5.4.16
PHP	5.4.16
MySQL	5.5.47-MariaDB
RRDtool	1.4.8
![app_mainpage](https://cloud.githubusercontent.com/assets/3048315/16438838/8c34ce30-3dbb-11e6-9523-ae28a202e209.png)
![apps_subpage](https://cloud.githubusercontent.com/assets/3048315/16438837/8c34a3ce-3dbb-11e6-8312-38cd52306dcd.png)

**Comment by murrant** [comment]
Are you sure data is being collected?
I think this requires the unix-agent right now: http://docs.librenms.org/Extensions/Agent-Setup/

**Comment by crcro** [comment]
data is collected.
here is the php debug for the /apps/ url:
http://pastebin.com/v01wYPCn

**Comment by murrant** [comment]
Looks like you are missing common.inc.php...

```include_once(/opt/librenms/includes/common.inc.php): failed to open stream: No such file or directory
 include_once(): Failed opening '/opt/librenms/includes/common.inc.php' for inclusion 
```

**Comment by crcro** [comment]
it looks like the only common.inc.php is available at __install_dir__/html/includes/ not in __install_dir__/includes/

i've changed the include_once, no more err in debug but the output is still the same.

./validate.php output:

Version info:
Commit SHA: fdf68a83b32135f669fc250dfe865614ed01bc75
[WARN]    Your local git contains modified files, this could prevent automatic updates.
Modified files:
    html/includes/graphs/application/nfs-stats.inc.php
    html/pages/device/apps/nfs-stats.inc.php
    includes/device-groups.inc.php
    includes/polling/applications/nfs-stats.inc.php
DB Schema: 123
PHP: 5.4.16
MySQL: 5.5.47-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2

[OK]      Database connection successful
[root@NCAERoDC01gra01 librenms]#

**Comment by murrant** [comment]
Thanks, try `./poller.php -h <hostname> -m unix-agent,applications -d -r -f`

**Comment by crcro** [comment]
output of your request:
http://pastebin.com/pVq4UKeW

**Comment by murrant** [comment]
ntpclient has no data:` ntpclient-6.rrd N:U:U:U:U:U` because this device isn't running ntpclient, only ntpd. (which is expected)

PowerDNS, does have data and should be working.  Did you figure out the common.inc.php missing issue?

**Comment by crcro** [comment]
close via #3954
