### ISSUE TITLE
AvTech 3E internal temperature sensors devisor = 1

### ISSUE THREAD

**Issue by davburns** [librenms/librenms#3750]
LibreNMS graphed all of our AVTech 3E environment sensors as having temperatures around 0.2C.

I see that avtech_add_sensor() assumes a divisor of 100 if a sensor is a temperature sensor.

Setting divisor=1 in the 3E internal paragraph in tempratures/avtech.inc.php line 39, fixes this for our specific devices.  (I'd be happy to make a pull request for that one line.)

However, I don't have any other models of AVTech devices or their external sensors, so I'm not sure if a more general solution (perhaps, if discovery time raw temperature > 100, then set divisor = 100; or perhaps comparing the C sensor to the F sensor) would be better.

This isn't for a new device, but perhaps this walk of 1.3.6.1.4.1.20916 will be useful anyway:

.1.3.6.1.4.1.20916.1.9.1.1.1.1.0 = INTEGER: 21
.1.3.6.1.4.1.20916.1.9.1.1.1.2.0 = INTEGER: 71
.1.3.6.1.4.1.20916.1.9.1.1.1.3.0 = STRING: "Internal Sensor"
.1.3.6.1.4.1.20916.1.9.1.2.1.0 = INTEGER: 0
.1.3.6.1.4.1.20916.1.9.1.2.2.0 = STRING: "Switch Sen 1"
.1.3.6.1.4.1.20916.1.9.3.1.0 = ""

**Comment by murrant** [comment]
In the settings for the RoomAlert 3E, under the SNMP section there is a setting to "Use 2 digit SNMP".

The default is unchecked.  If you uncheck this, the 100 divisor will be correct.

(Sorry about this but the SNMP implementation on these devices is absolutely terrible)

**Comment by davburns** [comment]
Oh!  That worked well.  Thanks!  

(Yes, it's annoying that AVTech didn't just expose 1x and 100x in separate OIDs.  But maybe this issue will help the next person that searches...)
