### ISSUE TITLE
MySQL App Graph Not Updating

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#3751]
Similar to this item,
https://github.com/librenms/librenms/issues/3731#issuecomment-229381148

I set this all up, installed it ... and waited ... ;). Apache graph updates, works fine - but not so for MySQL. Yep, I did create and configure /usr/lib/check_mk_agent/local/mysql.cnf - but still no joy.

Any things to look at to debug this?

Thanks!

**Comment by arrmo** [comment]
Hi,

I do see this comment in the documentation - but not sure what mode the poller is in now,
NOTE: This only applies to the PHP-Version of the Statistics-poller. There's work being done in porting this script to Python, a different configuration file (if any) will apply.

So - is the current instruction correct, or has this changed?

Thanks!

**Comment by laf** [comment]
telnet to the check_mk port and see if you see <<mysql>>

If not, run the mysql script on your agent directly and see what that outputs.

**Comment by arrmo** [comment]
Too funny - that's exactly what I was trying yesterday, was still digging in to the response ... :). Yep, telnet works, but the mysql script output is a bit odd - below,

<<<mysql>>>
The MySQL extension is not loaded

Huh? The extension looks to be loaded to me (from phpinfo()). I also re-confirmed, both php-cli and php-mysql are installed.

Thoughts?

Thanks!

**Comment by laf** [comment]
What version of php? If it's 7 then this script uses mysql_connect so probably needs updating to mysqli_connect

**Comment by arrmo** [comment]
Yep, php7 - default with Ubuntu 16.04. No issues here changing it ... do you expect other changes? I can try to wade my way through.

Thanks!

**Comment by laf** [comment]
We should just update it to mysqli. If you want to do that it would be ace.

**Comment by arrmo** [comment]
Will work through it - not quite as simple as changing all mysql_xxx to mysqli -> for some items (like query), the parameter order changes ... :(

**Comment by arrmo** [comment]
OK, got it working ... :). What's the best way to get this to you, for checkout / testing? Don't want to overwrite the php5 version.

Thanks!

**Comment by Compizfox** [comment]
Same problem here. The `mysql` script for the UNIX agent seems to use the deprecated `mysql` PHP extension, instead of `mysqli` or `PDO`.

As the `mysql` extension is removed in PHP7, it doesn't work for PHP7.

**Comment by laf** [comment]
@arrmo 

Submit a pull request and just overwrite the php5 version. mysqli is backwards compatible and everyone should have that module loaded.

**Comment by arrmo** [comment]
Sure, will do - one minor note ... I didn't mess with / fix the SSL connection, as I don't have the ability to test it here (but the rest is all working for me - but by all means check it out!).

Now, as I struggled with this last time a bit - clearly not a git expert! ... ;). Let me make sure I do this right ... fork, apply my updates to my repository, then pull request. Do I have that right.

Coding seems easy to me, relative to configuration management ... LOL.

**Comment by laf** [comment]
That's right yes, as it's just one single file it's easy enough to just click edit in github on it, paste your new file contents and overwrite then submit the PR from there.

**Comment by arrmo** [comment]
Easy for you to say ... ;)

Will do, thanks!

**Comment by arrmo** [comment]
OK, pull request in place - if I did it right .. :)

**Comment by laf** [comment]
This was merged in.
