### ISSUE TITLE
Allow searching of Inventory

### ISSUE THREAD

**Issue by kate66** [librenms/librenms#3755]
The ability to search for component serial numbers has been something that I have needed. If this is integrated I would be extremely happy. Additionally, the ability to configure a rule to fire when it locates a specific serial number would be awesome to go with the auto-discovery feature. :D

**Comment by laf** [comment]
/inventory/ in the webui allows searching - are you referring to having a search on the specific device page as that seems a bit ott as it's usually quite a small page to just use the browser find.

As for alerting you can do this with something like `%macro.device = 1 && %entPhysical.entPhysicalSerialNum = 'YOURSERIAL'`

**Comment by kate66** [comment]
Wow, I totally missed that somehow. Thanks! :) Maybe a "More" button near the global search bar, after you click it you can choose what you would like to search? (Inventory / Devices / Ports / etc)

**Comment by laf** [comment]
I don't think we will be extending the search out further for v1 so I'll tag this for v2.

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #171](https://github.com/librenms/librenmsv2/issues/171) via [**ZenHub**](https://www.zenhub.com/)
