### ISSUE TITLE
new applications

### ISSUE THREAD

**Issue by crcro** [librenms/librenms#3760]
Hi, 

I tried to add a new application monitoring to my librenms installation through net-snmp extend and local script.
Did the snmp part and i got values if i do a snmpwalk.
Added a new file in /opt/librenms/includes/polling/applications and under the applications tab on host i can see it. I've enabled it and now it is showing in the Apps menu, but when entering the application page it shows no graph (i checked the rrd file and it is created under the /opt/librenms/rrd/<<hostname>>/<<rrd_file>>

I'm missing something or where could i find some information about adding new applications monitors?

Regards,

**Comment by laf** [comment]
run `./validate.php`

**Comment by crcro** [comment]
Version info:
Commit SHA: 6956ed787003ff532df7d93cfb6ee0c290162f2b
[WARN]    Your local git contains modified files, this could prevent automatic updates.
Modified files:
html/pages/apps/default.inc.php
librenms.nonroot.cron
DB Schema: 121
PHP: 5.4.16
MySQL: 5.5.47-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2

[FAIL]    We have found some files that are owned by a different user than librenms, this will stop you updating automatically and / or rrd files being updated causing graphs to fail:
If you don't run a bespoke install then you can fix this by running `chown -R librenms:librenms /opt/librenms`
/opt/librenms/.git/index

[OK]      Database connection successful

**Comment by crcro** [comment]
Figured out all the necessary pages needed to get a new application.
Still having the followind polling issue:

if i run from librenms host the snmpwalk everything is ok:
snmpwalk -v2c -c NCAERoDC01nas01 nas01 .1.3.6.1.4.1.8072.1.3.2.4
NET-SNMP-EXTEND-MIB::nsExtendOutLine."nfsstat".1 = STRING: 502
NET-SNMP-EXTEND-MIB::nsExtendOutLine."nfsstat".2 = STRING: 0
NET-SNMP-EXTEND-MIB::nsExtendOutLine."nfsstat".3 = STRING: 3
NET-SNMP-EXTEND-MIB::nsExtendOutLine."nfsstat".4 = STRING: 0
NET-SNMP-EXTEND-MIB::nsExtendOutLine."nfsstat".5 = STRING: 40
NET-SNMP-EXTEND-MIB::nsExtendOutLine."nfsstat".6 = STRING: 5
NET-SNMP-EXTEND-MIB::nsExtendOutLine."nfsstat".7 = STRING: 416
NET-SNMP-EXTEND-MIB::nsExtendOutLine."nfsstat".8 = STRING: 18
NET-SNMP-EXTEND-MIB::nsExtendOutLine."nfsstat".9 = STRING: 10
NET-SNMP-EXTEND-MIB::nsExtendOutLine."nfsstat".10 = STRING: 0
NET-SNMP-EXTEND-MIB::nsExtendOutLine."nfsstat".11 = STRING: 10
NET-SNMP-EXTEND-MIB::nsExtendOutLine."nfsstat".12 = STRING: 0
NET-SNMP-EXTEND-MIB::nsExtendOutLine."nfsstat".13 = STRING: 0
NET-SNMP-EXTEND-MIB::nsExtendOutLine."nfsstat".14 = STRING: 0
NET-SNMP-EXTEND-MIB::nsExtendOutLine."nfsstat".15 = STRING: 0


If I run the  /opt/librenms/poller.php -r -f -dd -h 42 it throws: 

SQL[SELECT * FROM `applications` WHERE `device_id`  = '42']  nfsstat/usr/bin/snmpget -v2c -c COMMUNITY -O qv -m NET-SNMP-EXTEND-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.8072.1.3.2.4No Such Object available on this agent at this OID

**Comment by crcro** [comment]
i found the issue, i was blind, changed from snmp_get to snmp_walk in polling script and everything works.

**Comment by tomlobato** [comment]
@crcro "Figured out all the necessary pages needed to get a new application."
any doc about this or you found it in the hard way?

**Comment by crcro** [comment]
@tomlobato ... hard way. you can do a search after “os-updates” in librenms files ... and should return a couple o files that you should create in order to have a new app in the polling/webui

**Comment by tomlobato** [comment]
@crcro tks!
