### ISSUE TITLE
Nagios check_snmp and mikrotik signal graphs

### ISSUE THREAD

**Issue by wizzycom** [librenms/librenms#3770]
Hello.

I have configured some services for polling signal strength via snmp from a mikrotik device. Everything works as expected (command results and alerting) but I am facing some issues with graphing.

Here are the results of **check-services.php -d** : 

DEBUG!

SQL[SELECT \* FROM `devices` AS D, `services` AS S WHERE S.device_id = D.device_id ORDER by D.device_id DESC] 
Nagios Service - 1
Request:  /usr/lib64/nagios/plugins/check_snmp -H 10.70.25.234 -C public -o 1.3.6.1.4.1.14988.1.1.1.2.1.3.0.12.66.102.140.141.6 -c -80: 
Perf Data - None.
Perf Data - DS: iso.3.6.1.4.1.14988.1.1.1.2.1.3.0.12.66.102.140.141.6, Value: -65, UOM: 
Response: SNMP OK - -65 
Service DS: {
    "iso.3.6.1.4.1.14988.1.1.1.2.1.3.0.12.66.102.140.141.6": ""
}
RRD[create /opt/librenms/rrd/cronus.lan.local/services-1.rrd  DS:iso.3.6.1.4.1.14988.1.1.1.2.1.3.0.12.66.102.140.141.6:GAUGE:600:0:U RRA:AVERAGE:0.5:1:2016 RRA:AVERAGE:0.5:6:1440 RRA:AVERAGE:0.5:24:1440 RRA:AVERAGE:0.5:288:1440  RRA:MIN:0.5:1:720 RRA:MIN:0.5:6:1440     RRA:MIN:0.5:24:775     RRA:MIN:0.5:288:797  RRA:MAX:0.5:1:720 RRA:MAX:0.5:6:1440     RRA:MAX:0.5:24:775     RRA:MAX:0.5:288:797  RRA:LAST:0.5:1:1440 ] **ERROR: Invalid DS name**
RRD[update /opt/librenms/rrd/cronus.lan.local/services-1.rrd N:-65] 
Nagios Service - 2
Request:  /usr/lib64/nagios/plugins/check_snmp -H 10.70.25.234 -C public -o .1.3.6.1.4.1.14988.1.1.1.2.1.3.212.202.109.18.54.105.7 -c -80:
Perf Data - None.
Perf Data - DS: iso.3.6.1.4.1.14988.1.1.1.2.1.3.212.202.109.18.54.105.7, Value: -60, UOM: 
Response: SNMP OK - -60 
Service DS: {
    "iso.3.6.1.4.1.14988.1.1.1.2.1.3.212.202.109.18.54.105.7": ""
}
**ERROR: opening '/opt/librenms/rrd/cronus.lan.local/services-1.rrd': No such file or directory**

No rrd file is generated. I don't know if the result ( it is always negative ) can cause this issue...
Can you assist ?

Regards
Kostantinos

**Comment by geordish** [comment]
The problem is with the name that it is trying to use to store the data with.

Try passing  -l <label> with your arguments. I think it should help

**Comment by wizzycom** [comment]
Hello geordish.

Thank you fro you reply and the tip!!
I just set the -l argument and the debug now shown no errors :

DEBUG!

SQL[SELECT * FROM `devices` AS D, `services` AS S WHERE S.device_id = D.device_id ORDER by D.device_id DESC] 
Nagios Service - 1
Request:  /usr/lib64/nagios/plugins/check_snmp -H 10.70.25.234 -C public -o 1.3.6.1.4.1.14988.1.1.1.2.1.3.0.12.66.102.140.141.6 -l mtxrWlRtabStrength -c -80: 
Perf Data - None.
Perf Data - DS: mtxrWlRtabStrength, Value: -63, UOM: 
Response: SNMP OK - mtxrWlRtabStrength -63 
Service DS: {
    "mtxrWlRtabStrength": ""
}
RRD[update /opt/librenms/rrd/cronus.local.lan/services-1.rrd N:-63] 

RRD files were created, but still the graphs show "Error Drawing Graph". The rrd error was : 

RRDTool Output
ERROR: Cannot parse DS in 'DEF:DS=/opt/librenms/rrd/cronus.local.lan/services-1.rrd:iso.3.6.1.4.1.14988.1.1.1.2.1.19.212.202.109.18.54.105.7:AVERAGE'

For anyone facing this issue please follow the instructions given by geordish then delete and re-create the services


Thank you once again geordish.

**Comment by geordish** [comment]
So the RRD's are created with a minimum value of 0. This means that storing negative values isn't going to work!

This diff will set the minimum value of created RRDs to undefined for the services, meaning any value is allowed. You will need to delete any RRDs that were created following applying this patch.

Unsure about creating a PR. Will this negatively affect other things? @laf @murrant etc...

```diff
diff --git a/includes/services.inc.php b/includes/services.inc.php
index fa40a33..c5eb0c9 100644
--- a/includes/services.inc.php
+++ b/includes/services.inc.php
@@ -158,7 +158,7 @@ function poll_service($service) {
                 }
                 else {
                     // Not a counter, must be a gauge
-                    $rra .= " DS:".$k.":GAUGE:600:0:U";
+                    $rra .= " DS:".$k.":GAUGE:600:U:U";
                 }
             }
             rrdtool_create ($rrd_filename, $rra . $config['rrd_rra']);
```

**Comment by wizzycom** [comment]
Yes I just noticed that there are no values on graphs....

**Comment by geordish** [comment]
@wizzycom if you don't want to apply that patch, you can probably do something like the following:

rrdtool tune /opt/librenms/rrd/xxxx/services-2.rrd --minimum mtxrWlRtabStrength:U

**Comment by wizzycom** [comment]
Ok I'll give it a try.

It seens that the graph is working now ( don;t know what happened ) but it looks strange. Vertical graph values are between 59 and 59,5...
I will give it a shot.

**Comment by wizzycom** [comment]
I did try it and it works. The only thing is that the graph scaling does not begin from 0 but from -59. 
I also tried...
rrdtool tune /opt/librenms/rrd/cronus.local.lan/services-9.rrd -i mtxrWlRtabStrength:-100
rrdtool tune /opt/librenms/rrd/cronus.local.lan/services-9.rrd -a mtxrWlRtabStrength:0

...but the vertical scaling remains the same. Maybe it's not possible to disable auto-scaling...
 
Sorry for the whole trouble but I don't have any experience on RRD

**Comment by wizzycom** [comment]
Is it posible to implement this check on polling ?

Based on xirrus device I have made some changes for routeros : 

I have added in **/opt/librenms/includes/polling/os/routeros.inc.php** the following : 

include 'includes/polling/wireless/routeros.inc.php';

I created **/opt/librenms/includes/polling/wireless/routeros.inc.php**

<?php
$rrd_filename = $config['rrd_dir'] . "/" . $device['hostname'] . "/mikrotik-rssi.rrd";
$radios = snmpwalk_cache_oid($device, 'MIKROTIK-MIB::mtxrWlRtabAddr', array(), 'MIKROTIK-MIB');
$rssi_rx = snmpwalk_cache_oid($device, 'MIKROTIK-MIB::mtxrWlRtabStrength', array(), 'MIKROTIK-MIB');
$rssi_tx = snmpwalk_cache_oid($device, 'MIKROTIK-MIB::mtxrWlRtabTxStrength', array(), 'MIKROTIK-MIB');
$associations=array();
foreach($radios as $idx => $radio) {
    $radioName = $radio['mtxrWlRtabAddr'];
    $associations[$radioName]=0;
    $rrd_filename = $config['rrd_dir'] . "/" . $device['hostname'] . "/mikrotik_stats-$radioName.rrd";
    if (!is_file($rrd_filename)) {
        rrdtool_create($rrd_filename, " --step 300 DS:rssi_rx:GAUGE:600:-150:0 DS:rssi_tx:GAUGE:600:-150:0 ".$config['rrd_rra']);
    }
    rrdtool_update($rrd_filename, array(
                                    'rssi_rx'=>$rssi_rx[$idx]['realtimeMonitorAverageRSSI_RX'],
                                    'rssi_tx'=>$rssi_tx[$idx]['realtimeMonitorAverageRSSI_TX'],
                                  ));
}
// cleanup
unset($rrd_filename); unset($radios); unset($rssi_rx); unset($rssi_tx); ($radioName);
$graphs['mikrotik_rssi_rx'] = TRUE;
$graphs['mikrotik_rssi_tx'] = TRUE;

Also **/opt/librenms/html/includes/graphs/device/routeros_rssi_rx.inc.php** and **routeros_rssi_tx.inc.php** which are almost the same, I attach only routeros_rssi_rx.inc.php

<?php
require 'includes/graphs/common.inc.php';
$pallette = array(
    1  => 'FF0000',
    2  => '0000FF',
    3  => '00FF00',
    4  => 'FF00FF',
    5  => '000000',
    6  => 'FFFF00',
    7  => 'C0C0C0',
    8  => '800000',
    9  => '808000',
    10 => '008000',
    11 => '00FFFF',
    12 => '008080',
    13 => '000080',
    14 => '800080',
    15 => 'FF69B4',
    16 => '006400'
);
$rrd_options .= ' -E ';
$rrd_options .= " COMMENT:'Signal RSSI RX          Cur     Min    Max\\n'";  
$radioId=1;
foreach(glob($config['rrd_dir'].'/'.$device['hostname'].'/mikrotik_rssi_rx-*.rrd') as $rrd) {             
    // get radio name
    preg_match("/mikrotik_stats-("*".rrd/", $rrd, $out);
    list(,$radioId)=$out;
    // build graph
    $color=$pallette[$radioId];
    //$descr        = "iap$radioId             ";
    $rrd_options .= " DEF:rssi_rx=$rrd:rssi_rx:AVERAGE";        
    $rrd_options .= " LINE2:rssi_rx#".$color.":'".$descr."'";     
    $rrd_options .= " GPRINT:rssi_rx:LAST:'%5.0lf'";     
    $rrd_options .= " GPRINT:rssi_rx:MIN:'%5.0lf'";     
    $rrd_options .= " GPRINT:rssi_rx:MAX:'%5.0lf'\\l";     
    $radioId++;
}//end foreach


RRD files are created by the poller, but I am looking for a way to display them, I am not a coder and  I am a little bit confused. Any help will be appreciated

Thanks

**Comment by spinza** [comment]
This looks interesting to me as well.

**Comment by laf** [comment]
It might be better for you to use the MIB polling, this will auto graph: http://docs.librenms.org/Extensions/MIB-based-polling/

**Comment by wizzycom** [comment]
For signaling, I use 'Services" because coding is too much to handle, but the graphs are broken. As suggested I used rrdtool tune and I was able to graph negative values, but the graph is almost unreadable because there is no way to set the limits I want on graph scaling, so I get a blue area that covers the graph between values I get from snmp.
If I use MIB polling, is there any way to set limits and be able to choose what is going to be graphed ?

**Comment by paulgear** [comment]
I've got a fix in progress for the negative values and probably the graph scaling as well.  Hopefully will have it ready to PR in a few days.

**Comment by wizzycom** [comment]
Hello guys.

I know that there are a lot to be done, but did you manage to take a look on this ?
With the latest version no graphs are created at all

**Comment by laf** [comment]
It's probably easier to just add native support for this. What's the OID for the signal?

**Comment by wizzycom** [comment]
Hello

For two random interfaces
.1.3.6.1.4.1.14988.1.1.1.2.1.3.0.12.66.102.140.141.6
.1.3.6.1.4.1.14988.1.1.1.2.1.3.212.202.109.18.54.105.7

This is what the Mikrotik MIB contains 

`mtxrWlRtabStrength OBJECT-TYPE
    SYNTAX Integer32
    MAX-ACCESS read-only
    STATUS current
    DESCRIPTION "dBm"
    ::= { mtxrWlRtabEntry 3 }`

**Comment by laf** [comment]
Can you get the output of: `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .` pls.

**Comment by wizzycom** [comment]
Attached.

[snmp.txt](https://github.com/librenms/librenms/files/713372/snmp.txt)

**Comment by laf** [comment]
Doesn't include 1.3.6.1.4.1.14988.1.1.1.2.1.3 for some reason, can you swap `.` for that and re-post pls.

**Comment by wizzycom** [comment]
Sorry I forgot to issue the `.`

[snmp.txt](https://github.com/librenms/librenms/files/713414/snmp.txt)

**Comment by spinza** [comment]
Happy to assist/test as well.

**Comment by laf** [comment]
Can either of you test #5498 please.

**Comment by wizzycom** [comment]
Will do

**Comment by wizzycom** [comment]
Ok. I tried it on another mikrotik device

Graphs appeared but still not working. Also all interfaces are in one graph but this is not an issue.... I attache some logs... discovery, polling and rrdinfo on two interfaces
[logs.txt](https://github.com/librenms/librenms/files/713588/logs.txt)

**Comment by laf** [comment]
You have to give it 15 minutes to populate data - did you leave it at least that long?

**Comment by laf** [comment]
That output shows it's working:

```
Checking (snmp) signal wlan3-Nasos Signal... 
Checking (snmp) signal wlan1-VL_Electronics Signal... 
-73 dBm
RRD[update /opt/librenms/rrd/10.70.25.235/sensor-signal-routeros-6.rrd N:-73]
SQL[UPDATE `sensors` set `sensor_current` ='-73',`sensor_prev` ='-74',`lastupdate` =NOW() WHERE `sensor_class` = 'signal' AND `sensor_id` = '12'] 
-73 dBm
RRD[update /opt/librenms/rrd/10.70.25.235/sensor-signal-routeros-4.rrd N:-73]
SQL[UPDATE `sensors` set `sensor_current` ='-73',`sensor_prev` ='-74',`lastupdate` =NOW() WHERE `sensor_class` = 'signal' AND `sensor_id` = '13'] 
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = 'airflow' AND `device_id` = '2'] 
```

**Comment by wizzycom** [comment]
It does not just work. It works like a charm !!!!

I just need to understand how it worked so in the future I just want to be able to add other sensors from the interfaces for example CCQ etc and also how hard is to change the appearance of the graph, for example to fill the space between the current value and 0 with color

**Comment by laf** [comment]
We have support for a variety of sensors so adding signal was easy (we have base support for this). If other information fits in with our current sensors then typically it's just one file to create - see the PR.

If they don't fit in with sensors then it may be a bit more of a pain. What is CCQ?

**Comment by wizzycom** [comment]
It is a link quality counter counted in percentage... I just updated #5498
