### ISSUE TITLE
Can't delete device

### ISSUE THREAD

**Issue by murrant** [librenms/librenms#3783]
We've had issues deleting devices reported, but we can't reproduce the problem.
We suspect the issue is related to PR #3745, but we are not sure how.

Looking for users that can reproduce the problem to provide either a database dump of these tables: devices, sensors_to_state_indexes, sensors, state_indexes, state_translations or the entire database.

Please contact us on IRC or leave a note here.

**Comment by dgerasimov** [comment]
I have that problem. Can't delete devices.

**Comment by laf** [comment]
Can you provide the required database dump of the tables listed above.

**Comment by murrant** [comment]
Can users with this issue test PR #3805 and report back?  Thanks.
