### ISSUE TITLE
HP 1810 - J9450A - crash on polling with certain firmware versions

### ISSUE THREAD

**Issue by oam7575** [librenms/librenms#3789]
Hello Everyone,

This is mostly an FYI notice for users of LibreNMS.

HP J9450A Network Switches - 1810-24G with firmware versions 2.14 or older will sometimes crash or reboot when being polled by some SNMP management software.

I am currently experiencing this myself.

Firmware 2.21 is currently released and can be downloaded from this page 
https://h10145.www1.hpe.com/Downloads/SoftwareReleases.aspx?ProductNumber=J9450A&lang=en&cc=us&prodSeriesId=3963985

**Comment by laf** [comment]
What OS do we detect these as, we might be able to do a check before running the snmp query and not do it if firmware version is <= 2.14

**Comment by oam7575** [comment]
Hi Laf,

I upgraded the firmware to 2.21 after making the initial post.

I was still seeing some crashing so have temporarily disabled SNMP on the switch as the crashing was impacting operations.

Currently the device is detected as follows

HP ProCurve 1810G - 24 GE, P.2.21, eCos-2.0, CFE-2.1
System Name	procurve j9450a
Resolved IP	172.16.1.1
Hardware	ProCurve 1810G - 24 GE
Operating System	HP ProCurve P.2.21
Serial	CN#########
Object ID	enterprises.11.2.3.7.11.104


The release notes ( PDF ) : http://h20564.www2.hpe.com/portal/site/hpsc/public/kb/docDisplay/?docId=c05168240

On page 9 says the following

Version P.2.14
Crash
CR_0000152728 The switch unexpectedly reboots when being discovered by certain network
management software, such as Observium. It occurs when the switch incorrectly processes the
SNMP Get of lldpRemSysDesc from the network management software


I should note that my LibreNMS install is behind the current release.

At this time my plan is to 
* Upgrade LibreNMS to current.
* Over the weekend re enable SNMP 
* Walk the device with discover / polle / snmpbulkwalk
* Monitor and log to try and catch the crash in action again.


Question 
The release notes for 2.21 suggest there is a problem with the lldp.
Can Link Layer Discovery be disabled per device in LibreNMS ??

**Comment by laf** [comment]
you can turn off discovery-protocols in the Webui for that particular device (Under Edit -> Modules).

**Comment by oam7575** [comment]
Hi Laf,

Have not taken further action with this switch yet.
However some research suggests that other HP switches might have similar issues.

I have found firmware release notes for other HP switches with similar notes about crashing when polling  lldpRemSysDesc

I intend to log a case with HP and see what they come back with.

**Comment by laf** [comment]
We can't fix this I'm afraid, if the device is crashing on purely a snmpget for lldpRemSysDesc then all we can say is disable auto-discovery on this device.
