### ISSUE TITLE
IPSEC tunnels never marked as inactive

### ISSUE THREAD

**Issue by neokjames** [librenms/librenms#3791]
Hi,

There appears to be an issue where IPSEC tunnels are always 'active', even when they are destroyed.

For example I have tunnels (Cisco ASA) I know are inactive, but when looking at LibreNMS, they are showing as 'active', therefore if alerting is configured based on something like
%ipsec_tunnels.tunnel_status != "active"
it never triggers.

This is easily tested, if you have any devices terminating an IPSEC tunnel, have a look at the device in LibreNMS and you will find it displays ALL tunnels as 'active'. Take one of the tunnels down and nothing ever triggers it to mark as 'inactive', therefore it will remain as 'active' in LibreNMS.

The way this was discovered is I was trying to alert when an IPSEC tunnel is no longer active, but due to the above it doesn't seem to work.

**Comment by oam7575** [comment]
Tested on Juniper SSG5 test device running a ScreenOS 6.3 variant.

The IPSEC tunnels are un-numbered and bound to a bridge group interface
LibreNMS lists the tunnel interfaces under the ports list

When configured with the following alert 
	%macros.port_down = "1"

An alert is triggered when a tunnel goes down.

Note: There is probably a better way of doing this.

**Comment by laf** [comment]
From when I've looked into tunnels before on Cisco ASA's - when they are down on the ASA they no longer get reported via SNMP. Test it and see.

As for IPSEC appearing in Juniper ports list - they must be responding back on IF-MIB with those as there is no correlation in the code between ports and tunnels

**Comment by neokjames** [comment]
laf - yes this is what I've seen too, but is there a way we can detect if a tunnel marked as 'active', no longer gives any data back, then it gets marked as inactive, or something to that effect? I'm not sure how that would be achieved at this point

I think the Juniper issue above is an entirely different thing to this issue. With an ASA, the IPSEC Tunnels are very different to a port configuration - different MIB.

**Comment by laf** [comment]
I think it's literally as simple as snmp reports back all active tunnels so we record them, once they are down snmp doesn't so we delete them. I've not found a way to resolve this I'm afraid.

**Comment by neokjames** [comment]
laf - yes, sort of, when the tunnels are down it doesn't actually delete them either I noticed.

Can you think of a way I can monitor a tunnel? Perhaps an alert macro to check based on if the IP has active tunnel? then we could use something like

%ipsec_tunnels.tunnel_status != "active" && %ipsec_tunnels.remote_address = "whatever"

**Comment by laf** [comment]
I don't think we can alert on this, tunnel_status is always active as no other state exists. If the tunnel is down and is removed from the database. If you tried to say %ipsec_tunnels.remote_address != "ip.ip.ip.ip" then it would just match on all other tunnels.

I think you're stuck on this one.
