### ISSUE TITLE
Router port graph boken

### ISSUE THREAD

**Issue by alexab-git** [librenms/librenms#3796]
Hi, 
I have a problem with one of the router ports graph.
Interface traffic graph shows garbage, although the same port pps graph or realtime graph are normal.
Also no arp table or ip address for this port (GigabitEthernet0/0/0)

![screen1_e1](https://cloud.githubusercontent.com/assets/20340028/16657185/31f03c10-446a-11e6-98b5-c10ead4d5a46.png)
![screen3](https://cloud.githubusercontent.com/assets/20340028/16656723/7292f296-4468-11e6-91c3-a0ac0d208c90.png)
![screen2](https://cloud.githubusercontent.com/assets/20340028/16656720/7011ced4-4468-11e6-9b85-ca65c5449fbd.png)

**Comment by laf** [comment]
snmpv1 by any chance?

**Comment by alexab-git** [comment]
Nope, SNMP v2c in device settings.  I will run tcpdump on librenms server and check it.
Hardware - cisco2951
Gig 0/0/0 - EHWIC-1GE-SFP-CU module.

My guess that there is a problem with MIB and/or discovery.
We run old cacti installation on the same host that runs librenms and there is no problem with gig 0/0/0 port graph in cacti, so this is hardly network/settings/device related.

**Comment by alexab-git** [comment]
It turned out that the poller.php receives the correct data.
I  compared data from librenms database and RRD file.

**from database:**
```
"ifInOctets": 3768619991602
"ifOutOctets": 613426904304
```

**from RRD:**
```
ds[INOCTETS].last_ds = "3768619991602"
ds[INOCTETS].value = NaN
ds[OUTOCTETS].last_ds = "613426904304"
ds[OUTOCTETS].value = 1.3140268627e+07

```
Any idea why the value field in RRD file could be NaN ?

**Comment by alexab-git** [comment]
Okay, i have found why the graph is broken.
RRD data source max value for interface gig 0/0/0 IN and OUT octets is set to 1 250 000.

Interface gig 0/0/0
rrdtool info /opt/librenms/rrd/MYHOST/port-id14.rrd   | egrep '(INO|OUTO)' | grep max
ds[INOCTETS].max = 1.2500000000e+06
ds[OUTOCTETS].max = 1.2500000000e+06

Interface gig 0/2
rrdtool info /opt/librenms/rrd/MYHOST/port-id13.rrd   | egrep '(INO|OUTO)' | grep max
ds[INOCTETS].max = 1.2500000000e+10
ds[OUTOCTETS].max = 1.2500000000e+10

Any advice where to look next ? Problem with mibs, discovery?

**Comment by laf** [comment]
The only way max is set to  1.2500000000e+06 is if you've used the tune option, however this should tune the max size to be the ifSpeed value so for a 1G port  it should be 1.2500000000e+07 afaik. Is the port showing as the correct ifSpeed in the DB? If not, overwrite the ifSpeed in the webui and re-run rrdtune script.

**Comment by alexab-git** [comment]
ifSpeed in database is 1000000000 (1Gbps)

I have used the "Enable RRD Tune for all ports" option while trying to fix the issue.
URL: /device/device=3/tab=edit/section=misc/

Now i've enable RRD tune option in port setting URL: /device/device=3/tab=edit/section=ports/
But max value is RRD file is still set to 1.2500000000e+06

**Comment by laf** [comment]
You have to manually run the tune rrd script, see the docs for details.

**Comment by alexab-git** [comment]
Running the rdd tune script fixed the problem.
I thought that switching on the rrd tune option in web-ui is enough.
Thanks for help!

**Comment by laf** [comment]
http://docs.librenms.org/Extensions/RRDTune/

It does say that it will only take effect when a port speed changes :)
