### ISSUE TITLE
LibreNMS webGUI errors after Apache update

### ISSUE THREAD

**Issue by Compizfox** [librenms/librenms#3810]
Hi,

After the latest update of Apache on Debian testing (Apache 2.4.20-2 --> 2.4.23-1), all LibreNMS pages except the frontpage fail with the error `File not found.`. So, for example, `https://example.com/librenms/` works, but `https://example.com/librenms/devices/` does not.

In `/var/log/apache2/error.log` I found the following error being emitted after trying to visit a LibreNMS page: 

    AH01071: Got error 'Primary script unknown\n',

I use php7-fpm with mod_proxy_fcgi to tie it to Apache.

I tested this on two servers (both running Debian Testing, php-fpm and librenms) and found the exact same behaviour on both servers: LibreNMS worked before the update, but after the update I get the aforementioned error.

I wasn't sure if this was a bug in Apache or in LibreNMS, but I decided to fill a bug report here because other websites/webapps still work fine.

If you need more information or testing I will gladly try to help.

**Comment by laf** [comment]
Sounds like you've not set the base url in config.php or .htaccess isn't updated seeing as you are running in a sub directory - which whilst work means you have to do both of the aforementioned things.

However in general, no it's unlikely to be a bug with LibreNMS

**Comment by Compizfox** [comment]
Thanks for you reaction.

You're right; since I'm running LibreNMS in a subdirectory, I have to set the base URL in `config.php` and `.htaccess`.

Except, I already did that, and before the Apache update, it worked fine this way. It was only after the Apache update (2.4.20 --> 2.4.23) that things went wrong.

I tested this on two different servers and both show the exact same problem after updating Apache.

**Comment by laf** [comment]
I don't have access to a 2.4.20 install to test so can't offer anything further.

You'll need to wait to see if anyone else can shed some light on it.

**Comment by Compizfox** [comment]
For testing purposes, I hosted LibreNMS directly on a subdomain instead of in a subdirectory. The problem persists.

**Comment by blaaat** [comment]
Had the same problem, modified the htaccess from: 

RewriteRule ^(.*)$ index.php/$1/
to: 
RewriteRule ^(.*)$ index.php

Which seems to work, haven't tested everything.

**Comment by Compizfox** [comment]
Thanks @blaaat, that seems to work!

I think you forgot a character (` *` ) though? My original line reads

    RewriteRule ^(.*)$ index.php/$1/

And I changed it to:

    RewriteRule ^(.*)$ index.php

**Comment by blaaat** [comment]
You're right. Github styled the * away; edited my comment with code tags.

**Comment by Compizfox** [comment]
I noticed that this fix, despite working perfectly, has never been committed. Should I create a pull request for this?

**Comment by laf** [comment]
Only if that is genuinely an issue and a fix.

**Comment by Compizfox** [comment]
Well, I don't know under what circumstances this issue occurs; so far only @blaaat and me have reported it. But I can confirm that this *does* fix the issue for me without any side effects.

I have no idea why that `/$1/` should or shouldn't be there or why it causes problems in @blaaat's and my case.

**Comment by blaaat** [comment]
I haven't noticed any site affects till now. No clue about what the /$1/ should do.

**Comment by Compizfox** [comment]
I see this is fixed now 👍
