### ISSUE TITLE
Email (notification) fails when MySQL down

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#3813]
Hi,

"Normal" notification emails (machines, etc. up and down) work fine on my system ... but, when mysql goes down, the email that are sent out are bouncing. It seems they are not using the same settings / configuration for some reason?

Looking more closely, these notifications are being sent to a different email address for some reason, not aligned to the alert settings?

Thanks!

**Comment by f0o** [comment]
If the SQL is down, all sorts of funky things can happen. I'm surprised it sends any mails at all when it's down, that shouldn't be possible I'd say

**Comment by arrmo** [comment]
That makes sense, and agreed - so perhaps not have it try to send an email?

**Comment by f0o** [comment]
Like i said, I'm surprised it does as the information is stored in MySQL. It shouldn't be doing anything at all if the SQL is down.

**Comment by laf** [comment]
closing, if mysql can't connect librenms issues a die so no scripts will continue to run.
