### ISSUE TITLE
ibm-amm PSU states

### ISSUE THREAD

**Issue by rbax82** [librenms/librenms#3824]
I'd like to get the power supply states added to the ibm-amm template. Please let me know what you need from me to accomplish this.
http://pastebin.com/maLVb2wV

**Comment by rbax82** [comment]
snmpwalk
http://pastebin.com/JGAKb3S2

**Comment by Rosiak** [comment]
Nothing useful in the walk you supplied.
Is this a complete walk?

**Comment by rbax82** [comment]
my bad, here's the complete walk
http://pastebin.com/qci3wM4D
