### ISSUE TITLE
ibm-amm blower state needs a small fix

### ISSUE THREAD

**Issue by rbax82** [librenms/librenms#3825]
http://puu.sh/pYcra/20e26fb2a4.png
In the MIB for this device the following is specified:
  OBJECT-TYPE
                   SYNTAX  INTEGER {
                     unknown(0),
                     good(1),
                     warning(2),
                     bad(3)
                   }

**Comment by murrant** [comment]
This is the mapping that is in the code:
https://github.com/librenms/librenms/blob/master/includes/discovery/sensors/states/ibm-amm.inc.php#L33

The real problem might be that you ran pre-merged code (which did have the wrong values) which added the translations to your database.  Now the incorrect mappings are stored in your database.

You are probably the only one that will ever have this issue, so probably the correct thing to do is to have you fix your incorrect databases.

I think this will do the trick:
```
DELETE FROM `state_translations` WHERE `state_index_id` IN (SELECT `state_index_id` FROM `state_indexes` WHERE `state_name` LIKE 'blower%State');
DELETE FROM `state_indexes` WHERE `state_name` LIKE 'blower%State'
```

They should get added with the correct translations after the next discovery.

**Comment by rbax82** [comment]
MariaDB [librenms]> DELETE FROM `state_indexes` WHERE `state_name` LIKE 'blower%State'
    -> ;
ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`librenms`.`sensors_to_state_indexes`, CONSTRAINT `sensors_to_state_indexes_ibfk_2` FOREIGN KEY (`state_index_id`) REFERENCES `state_indexes` (`state_index_id`))

**Comment by rbax82** [comment]
Now I get this aftrer a poller run: http://puu.sh/pZ71Z/c6fb1879f9.png

**Comment by murrant** [comment]
Looks like you can't delete them in that order, now you'll need this:

```
DELETE FROM `state_translations` WHERE `state_translations`.`state_index_id` NOT IN (SELECT `state_indexes`.`state_index_id` FROM `state_indexes`);
```

On an unmodified box, you can run:
```
DELETE FROM `state_indexes` WHERE `state_name` LIKE 'blower%State';
DELETE FROM `state_translations` WHERE `state_translations`.`state_index_id` NOT IN (SELECT `state_indexes`.`state_index_id` FROM `state_indexes`);
```

**Comment by rbax82** [comment]
The mmblade.mib doesn't look like it got added to librenms' mib repo...

**Comment by murrant** [comment]
The mib isn't needed, but I only recall blade.mib being used.

**Comment by rbax82** [comment]
We're good.
