### ISSUE TITLE
HP Toner graph error

### ISSUE THREAD

**Issue by crcro** [librenms/librenms#3826]
In older versions worked ok but now i've seen that the toner graph is no longer working.
Printer is HP MFP M477fdw

graph rrd command output:

RRDTool Command
rrdtool graph /tmp/prG0zAJPx95xMcGI.png --alt-autoscale-max --rigid -E --start 1468180800 --end 1468267200 --width 1712.7 --height 490.5 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal -l 0 -E COMMENT:'Toner level Cur Min Max\n'

RRDTool Output
OK u:0.00 s:0.01 r:0.00 

librenms:
Version	121781c - Invalid Date
DB Schema	#123
Apache	2.4.6 (CentOS) PHP/5.4.16
PHP	5.4.16
MySQL	5.5.47-MariaDB
RRDtool	1.4.8

**Comment by laf** [comment]
What do you mean by no longer working?

**Comment by crcro** [comment]
it was working in an older version (i don't recall which one). now in the latest version it is showing a red small graph in the upper right corner and an empty big graph with the posted rrd command

**Comment by laf** [comment]
`./validate.php` please

**Comment by crcro** [comment]
[root@NCAERoDC01gra01 librenms]# ./validate.php 
Version info:
Commit SHA: c88706531b4eadd40f4b4053b0ce6d5f098fe3af
DB Schema: 123
PHP: 5.4.16
MySQL: 5.5.47-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2

[OK]      Database connection successful
[root@NCAERoDC01gra01 librenms]#

**Comment by laf** [comment]
Right click the graph, copy IMAGE url, add &debug=true to the end, pastebin the output.

**Comment by crcro** [comment]
php debug: http://pastebin.com/TtdpJUZp
sql debug: http://pastebin.com/nCSNLqmh

**Comment by laf** [comment]
No rrd file is being used for input here.

What's the full url (minus your domain) to the graph page for this?

**Comment by crcro** [comment]
url: graphs/to=1468964400/device=51/type=device_toner/from=1468878000/legend=yes/

**Comment by crcro** [comment]
@laf ... found what was wrong ... must put $config['enable_printers'] = 1; in config.php for fully enable printers details.

my bad, sorry for wasting your time
