### ISSUE TITLE
Juniper RPM Support

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#3830]
#2607

Cisco IP-SLA support is already in place - people are asking for Juniper RPM, which should be similar.

**Comment by Cheeze-It** [comment]
So, the way that this generally works on Juniper is the following.

Here is the sample configuration of the test:

set services rpm probe best-effort test test-to-router probe-type udp-ping-timestamp
set services rpm probe best-effort test test-to-router target address <destination IP>
set services rpm probe best-effort test test-to-router probe-count 1
set services rpm probe best-effort test test-to-router source-address <source IP>

This is a pretty generic test here. For what it's worth though there are a few things to keep in mind when it comes to pulling this from the OID. Juniper actually did something that one could see as good or bad (depending on how one views things). They took the probe "owner" and probe "test" and turned them into decimal notation and appended them to the OID. Then at the very end the actual OID information is given. So an example of how the above would look is like this.

<redacted>@<redacted> show services rpm probe-results
    Owner: best-effort, Test: test-to-router
    Target address: <redacted>, Source address: <redacted>, Probe type: udp-ping-timestamp, Test size: 1 probes
    Probe results:
      Request timed out, Tue Jul 19 21:07:36 2016
    Results over current test:
      Probes sent: 1, Probes received: 0, Loss percentage: 100.00000
    Results over last test:
      Probes sent: 1, Probes received: 0, Loss percentage: 100.00000
    Results over moving average:
      Probes sent: 6, Probes received: 0, Loss percentage: 100.00000
    Results over all tests:
      Probes sent: 149, Probes received: 0, Loss percentage: 100.00000


The OID results of (some) of the information up from above looks like this:

SNMPv2-SMI::enterprises.2636.3.50.1.2.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.2.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.2 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.2.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.3 = Gauge32: 6
SNMPv2-SMI::enterprises.2636.3.50.1.2.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.4 = Gauge32: 113
SNMPv2-SMI::enterprises.2636.3.50.1.2.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.2.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.2 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.2.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.3 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.2.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.4 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.2.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.2.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.2 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.2.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.3 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.2.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.4 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.84.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.85.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.86.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.87.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.88.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.89.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.90.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.91.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.92.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.93.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.94.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.95.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.96.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.97.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.98.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.99.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.100.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.101.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.102.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.103.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.104.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.105.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.106.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.107.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.108.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.109.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.110.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.111.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.112.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.113.1 = Gauge32: 1
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.84.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.85.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.86.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.87.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.88.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.89.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.90.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.91.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.92.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.93.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.94.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.95.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.96.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.97.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.98.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.99.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.100.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.101.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.102.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.103.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.104.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.105.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.106.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.107.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.108.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.109.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.110.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.111.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.112.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.3.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.113.1 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.84.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.85.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.86.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.87.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.88.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.89.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.90.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.91.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.92.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.93.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.94.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.95.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.96.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.97.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.98.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.99.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.100.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.101.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.102.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.103.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.104.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.105.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.106.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.107.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.108.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.109.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.110.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.111.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.112.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.113.1 = Gauge32: 100
SNMPv2-SMI::enterprises.2636.3.50.1.5.1.4.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.114.1 = Gauge32: 100


Now one thing to keep in mind is that Juniper did ASCII to decimal and appended it. So when one converts the very first line it looks like this:

2636.3.50.1.2.1.2.11.98.101.115.116.45.101.102.102.111.114.116.14.116.101.115.116.45.116.111.45.114.111.117.116.101.114.1 = [2636][3]2[1][2][1][2][11]best-effort[14]test-to-router[1]

Now it's pretty obvious to see that the "owner" and the "test" are appended and when translated back actually gives the name of the test being ran. This should be pretty easy to do a conversion of. However in this output the [11] and [14] are not static variables. Between Junipers I wasn't able to get a consistent number. I don't know why to be honest, and that might be a JUNOS thing. Either way it does actually work however. When there is information then more stats show up.

The MIB can be seen here (http://www.oidview.com/mibs/2636/JUNIPER-RPM-MIB.html) and the page that Juniper themselves provides is here (https://www.juniper.net/techpubs/software/topics/concept/mib-rpm-junos-overview.html). The actual MIB that Juniper themselves provide can be found here (https://www.juniper.net/techpubs/software/topics/concept/mib-jnx-rpm.txt). 

If more info is needed/examples needed please let me know. I'd be willing to help in any way I can :)

Thank you LibreNMS team.

**Comment by BradHooper** [comment]
+1 This would be great

**Comment by dorkmatt** [comment]
+1

**Comment by mobbeduo** [comment]
+1

**Comment by zurazzansi** [comment]
+1

**Comment by laf** [comment]
Folks please use the +1 ability in the first post.

**Comment by Rosiak** [comment]
Moved to community site.
