### ISSUE TITLE
IBM-AMM Temp Disco

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#3832]
Is bugged, this is the UI after the initial disco.
Haven't had time to look at it yet, just registered this issue.
<img width="1022" alt="screen shot 2016-07-12 at 23 10 14" src="https://cloud.githubusercontent.com/assets/6378934/16784043/31c3e734-4887-11e6-8a43-677fe76b53a0.png">

**Comment by rbax82** [comment]
The OID being used is incorrect.

**Comment by rbax-idx** [comment]
Negative, not as smart as I thought I was.

**Comment by murrant** [comment]
Fixed in #3866
