### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by suknight** [librenms/librenms#3833]
I finished the 6 stages steps from the web browser and i am stuck at this step:
Trying to run "php validate.php" and "php addhost.php localhost public v2c" i get this error- <h2>MySQL Error</h2> .
Why do i get this error ?
OS: Linux Mint 18

**Comment by laf** [comment]
This is purely because the details you have in config.php don't work, double check the mysql details (use them to login yourself).

**Comment by suknight** [comment]
While configuring in browser i got  a message "We couldn't create the config.php file, please create this manually before continuing by copying the below into a config.php in the root directory of your install (typically /opt/librenms/)" So i just copy pasted and created config.php.
As you said looks like the password field was left blank under ###Database config. Now able to get librenms from localhost. Thank you.
