### ISSUE TITLE
Exclude interfaces from poller/discovery

### ISSUE THREAD

**Issue by melniks1** [librenms/librenms#3834]
Hi
I have got a problem with adding D-Link DES-3200 rev A/B and 1228/ME switches with vlan_trunk enabled.
Main problem is that when i enable vlan_trunk option it creates 4094 tagged vlan interfaces on trunk ports and all of them are available through snmp, so when i use autodiscovery/poller it takes quite a lot of time to finish process and causes 100% cpu usage on switch.
Trying to solve this problem i added option to ingnore l2vlan type interface:
$config['bad_iftype'][]= 'l2vlan';
But even with this option rrd files are created for ignored interfaces causing high disk usage and ports still being polled. In debug file i see this:

    [4781] => Array
        (
            [ifDescr] => D-Link DES-3200-28 R1.84 802.1Q Encapsulation Tag 3758
            [ifName] => 802.1Q Encapsulation Tag 3758
            [ifType] => l2vlan
        )
     SQL[INSERT  #INTO `ports` (`device_id`,`ifIndex`,`ifName`)  VALUES ('74','5116','802.1Q Encapsulation Tag 3758')]
     SQL[SELECT * FROM `ports` WHERE `device_id` = '74' AND `port_id` = '124682'] Adding: 802.1Q Encapsulation Tag 3758(5116)(124682)ignored ifType : l2vlan (matched: l2vlan )

So is there any chance to exclude this interfaces from autodiscovery and poller?

**Comment by laf** [comment]
If the device genuinely reports back those interfaces from IF-MIB then we have no choice but to walk them as we do a bulk walk.

The bad_iftype won't add the interface to the db so shouldn't then create any files. Did you set that option _after_ a discovery had run, if so re-run discovery then go to -> Ports -> Deleted in webui and purge all ports.

**Comment by melniks1** [comment]
Yes, i`m doing it like this: 
adding $config['bad_iftype'][]= 'l2vlan'; to defaults.inc.php
then addhost.php 192.168.1.1
after that discovery.php -h 192.168.1.1
Still all interfaces are being added to db and after i run poller rrd files are created for each interface.
Accessing webui->Ports causing application to hang because of high cpu load coming from mysql process.

**Comment by laf** [comment]
Please provide pastebin.com links for:


```bash
./discovery.php -h HOSTNAME -d -m ports
./poller.php -h HOSTNAME -r -f -d -m ports
```

**Comment by melniks1** [comment]
There is pastebin for discovery process:
http://pastebin.com/QsZLxR9X
Debug log file for poller process weights about 40Mb. Maybe i can pastebin certain lines?

**Comment by melniks1** [comment]
I`ve made pastebin from another switch. Still i`ve got $config['bad_iftype'][]= 'l2vlan'; in defaults.inc.php and still ports with iftype l2vlan being added to db and rrd files created in rrd directory:
discovery debug log:
http://pastebin.com/S3MiDz9S

poller debug log:
http://pastebin.com/aJ1k85zX

**Comment by laf** [comment]
Your install isn't currently upto date, please update and re-run those commands.

**Comment by melniks1** [comment]
Hello.
I`ve got version pulled from git e9bce1d - Tue Jul 19 2016 01:37:37 GMT+0300
And even then i`ve got all interfaces in rrd and db.

**Comment by laf** [comment]
We need the output from the commands still.

**Comment by laf** [comment]
No further info provided.

**Comment by nicolay-l** [comment]
It seems cause at includes/functions.php at 1087 line:
 
        if ($device['os'] == "dlink") {
            $valid = 1;
        } 
   all dlink os ports are valid!
That is bug or feature?
