### ISSUE TITLE
Add alert ACK's to eventlog and more

### ISSUE THREAD

**Issue by croax** [librenms/librenms#3835]
It would be really nice if the following features would be added to the alerting mechanism:

If someone ACK's an alert then it would show in the eventlog who ACK'd it and when. 

Add a free text space in the Alerts dashboard to add notes when an alert is ACK'd. Purpose of this would be to add for instance an incident ticketing number or some other information that would be relevant to the alert. I would recommend 

In screenshot "alert-not-ackd.png" you'll see a custom made UI that has been made in-house with my company - this is how an alert looks like before someone ACK's it

![alert-not-ackd](https://cloud.githubusercontent.com/assets/1641054/16803957/cce518f2-48f8-11e6-9654-540f4921ecb7.png)

In screenshot "alert-ackd.png" you'll see how the alert looks like after it's been ACK'd.

![alert-ackd](https://cloud.githubusercontent.com/assets/1641054/16803958/cce5a092-48f8-11e6-8c61-4d21efa01930.png)

There you can see we have a "note" column that shows when the alert was ACK'd, who ACK'd it and some text which is optional. It would be amazing to have this information in the alerts dashboard. This is being used by our NOC and has really helped us with traceability on incidents and alerts and also helps us see who was the first to respond to the alert.

FYI the UI is only pulling information from another monitoring system and displaying them in a manner that suits us AND it has an audit log for every operation performed but same principle applies.

Best regards,
Daniel

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #176](https://github.com/librenms/librenmsv2/issues/176) via [**ZenHub**](https://www.zenhub.com/)
