### ISSUE TITLE
 ./validate.php is fail

### ISSUE THREAD

**Issue by yandre-yandre** [librenms/librenms#3836]
root@ubuntu77:/opt/librenms# ./validate.php
[FAIL]    Syntax error in config.php

how to make solved ?

**Comment by paulgear** [comment]
Hi @yandre-yandre, as the script says, you have an error in your config.php file.  Use `php -l config.php` to help you find it.  Please visit our IRC channel (##librenms on Freenode, or use https://webchat.freenode.net/) for help rather than opening issues here.
