### ISSUE TITLE
 ./daily.sh 

### ISSUE THREAD

**Issue by yandre-yandre** [librenms/librenms#3837]
root@ubuntu77:/opt/librenms# ./daily.sh
grep: config.php: No such file or directory
Updating SQL-Schema                                FAIL
Updating submodules                                OK
Cleaning up DB                                           FAIL
Fetching notifications                                 FAIL

how to make solved ?

**Comment by paulgear** [comment]
Hi @yandre-yandre, this will be for the same reason as #3836 - please follow the instructions I gave there.
