### ISSUE TITLE
2 factor Authentication + Radius

### ISSUE THREAD

**Issue by sarlacpit** [librenms/librenms#3838]
First of all I am loving LibreNMS and what it brings to the table.

I have 2 factor authentication enabled on my radius server however when using LibreNMS it is authenticating with the OTP before sending the login details again. As such the One Time Password has already been used which causes a authentication failure.  Has anyone else had this issue? The 2FA works fine on other Radius enabled tools like Nagios. 

If I take off the 2fa from my individual radius account and log in it works fine.
Does LibreNMS cache the authentication credentials and reuse them? 

Here is a debug from the radius server which show what appear to be 2 separate postings of the auth details. For security, I have starred out the sent passwords... 

[2factorfail.txt](https://github.com/librenms/librenms/files/364238/2factorfail.txt)

**Comment by sarlacpit** [comment]
Is there anything I can do to provide more information or perform more debug?

Thanks

**Comment by laf** [comment]
I expect this is the way the authentication system works in general as we make a call everytime a page is loaded.

It would take a fair amount of work to fix this as most auth module are just additional to what's there already, I'll be honest and say it's unlikely we will spend time fixing this. V2 Webui will take care of this as we make use of Laravel for authentication but that doesn't help you here.

**Comment by sarlacpit** [comment]
Thanks Laf, I thought that may have been the case.
Looking forward to trying V2 Webui.

Thanks again :)

**Comment by laf** [comment]
We might have this resolved if #4134 gets merged so keep an eye on it.

**Comment by sarlacpit** [comment]
oooh thank you.

**Comment by murrant** [comment]
#6286 Might have fixed this.  Can someone test?

**Comment by laf** [comment]
please feel free to comment if you need further help
