### ISSUE TITLE
How do i change librenms from 'localhost' to 'localhost/librenms'

### ISSUE THREAD

**Issue by suknight** [librenms/librenms#3846]
My present /etc/apache2/sites-available/librenms.conf , with this config i could get librenms run from localhost
```
<VirtualHost *:80>
  DocumentRoot /opt/librenms/html/
  ServerName  MyHostname
  CustomLog /opt/librenms/logs/access_log combined
  ErrorLog /opt/librenms/logs/error_log
   AllowEncodedSlashes NoDecode
     <Directory "/opt/librenms/html/">
  Require all granted
    AllowOverride All
    Options FollowSymLinks MultiViews
  </Directory>
</VirtualHost>
```
By adding ``Alias /librenms /opt/librenms/html `` before  ``<Directory "/opt/librenms/html/">`` in the above config, i am able run it from ``localhost/librenms`` in the web browser but at the same time it is also running from ``localhost`` too.  I don't want it to run from ``localhost`` but only from ``localhost/librenms``.

The information here http://docs.librenms.org/Extensions/Sub-Directory/ is bit vague.
It says "For Debian distributions (Ubuntu, etc.) place the directives in /etc/apache2/sites-available/default "  whats default here ? i got only-`` 000-default.conf  default-ssl.conf  librenms.conf `` in ``/etc/apache2/sites-available`` directory . And does the ``The RewriteBase directive in html/.htaccess`` instructions in that link refers to the one in ``/opt/librenms/html/.htaccess`` ?

OS: Linux Mint 18
Apache version: Apache/2.4.18

**Comment by gcoeugnet** [comment]
Hi,

The default configuration file of Apache is named 000-default.conf on a debian based distribution which Linux Mint is. default-ssl.conf is the HTTPS default file which you don't seem to use. The file you should edit to make this work should be librenms.conf which serve the librenms website. 

Yes, the file .htaccess file used in the doc refers to /opt/librenms/html/.htaccess

Regarding your problem, why do you want to access your librenms website with "/librenms" ? Can't you use Name Virtual Hosts and access your librenms website from http://librenms.yourdomain.tld and your other website from http://otherwebsite.yourdomain.tld ?

**Comment by suknight** [comment]
@gcoeugnet  hi,
The problem is if i get it running on localhost/librenms it is also running from localhost at the same time.
And about the virtual hosts , how can i use Name Virtual Hosts and access librenms website from http://librenms.yourdomain.tld ?
If i give `` ServerName http://librenms.example.com`` as a directive i still couldn't get it from browser when i point it to librenms.example.com.
Is there anything else i have to do ?

**Comment by gcoeugnet** [comment]
Setting Apache's directive "ServerName" to librenms.example.com isn't enough, you have to ensure too that DNS resolution works. There must be a record librenms.example.com which resolve your librenms server IP adress.

[Here](http://httpd.apache.org/docs/2.2/en/vhosts/name-based.html) is a reference doc... Please check that your librenms server is correctly resolve by your DNS (or hosts file).

If you really want to access your website through localhost/librenms, you can do this :
- Change DocumentRoot to /opt
- Add the Alias /librenms /opt/librenms/html

I don't recommand it, it's not a best practice I think, but I tested it on my server, it is ok but you'll have to restrict access to /opt directory (or make it be served by the default Apache VH. And you'll have to take care of your Order Allow/Deny directives cause the login page will be accessible through localhost/librenms but other pages could lead to AH01630 "client denied by server configuration".

**Comment by laf** [comment]
This question is related to web server config rather than LibreNMS so I'm going to close it.

Feel free to continue to discuss this further but it's not something for us to fix.
