### ISSUE TITLE
possible bug on bill calculate

### ISSUE THREAD

**Issue by joubertredrat** [librenms/librenms#385]
Hi, 

I'm using Librenms on testing and recently I started to use bill usage, works fine, but in some moments is very wrong, as examples in images in two different bills.

https://i.imgur.com/x0CPEOJ.jpg
https://i.imgur.com/SkL4IE2.jpg

I don't know if this is a bug and if is on calculate or showing data.

I hope helped

**Comment by laf** [comment]
Any more feedback on the data we need @joubertredrat?

**Comment by f0o** [comment]
Propose closing due to too little information. @joubertredrat can reopen it again later if needed.
