### ISSUE TITLE
Pick Service to use as data source when adding graph widget

### ISSUE THREAD

**Issue by armadaazteca** [librenms/librenms#3851]
If I have a device with 2 or more services, when I try to create a graph widget on my dashboard the only options available to configure in the form are: 
- Title
- Graph type (Here is when I can pick "Service")
- Range
- Device

So I can't choose which of the 2 services I want to graph, and it always takes the oldest one added. Would be nice to either list all available services on the "Graph Type" dropdown, or (which I think would be best) if the user selects "Service" as type, then add an extra field where I can specify which service I want to use.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
