### ISSUE TITLE
Not able to add Juniper Devices.

### ISSUE THREAD

**Issue by blortox** [librenms/librenms#3858]
I'm not able to add a varity of devices to LibreNMS. We're trying to bring up a POF to see what it is like for monitoring our network and as to whether it would be a good successor to Cacti.

However, when trying to add our EX4300's, 4200's, 4600's, SRX210's, 240's, 1500's & our MX104's. It's not adding them (No error messages are coming up on the webui)

I'm able to get a response when i use snmpwalk from the cli (on the LibreNms Server)

[root@NMS librenms]# snmpwalk -v3 -l authPriv -u rtap-snmp -a MD5 -A passhere -x DES -X passhere 192.168.30.1:161 E 1.3.6.1.4.1.2636.3.1.13.1.8

SNMPv2-SMI::enterprises.2636.3.3.1.1.1.3 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.3.1.1.1.4 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.3.1.1.1.6 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.3.1.1.1.7 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.3.1.1.1.8 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.3.1.1.1.9 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.3.1.1.1.10 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.3.1.1.1.11 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.3.1.1.1.12 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.3.1.1.1.15 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.3.1.1.1.16 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.3.1.1.1.21 = Gauge32: 0
SNMPv2-SMI::enterprises.2636.3.3.1.1.1.22 = Gauge32: 0

When i try to use the addhost.php file, i get the following:

[root@NMS librenms]# ./addhost.php 192.168.30.1 ap v3 rtap-snmp passhere passhere md5 des 161 udp
Trying v3 parameters root/noAuthNoPriv ... 
No reply on credentials root/noAuthNoPriv using v3
Trying v3 parameters rtap-snmp/authPriv ... 
Trying v3 parameters root/noAuthNoPriv ... 
No reply on credentials root/noAuthNoPriv using v3
Trying v3 parameters rtap-snmp/authPriv ... 
We couldn't add this device, please check the snmp details
 

Does anyone have a solution.

All of the devices are running above junos version 11.4
SRX device provided as example is running 12.1

TIA.

**Comment by laf** [comment]
Try the webui.

**Comment by blortox** [comment]
Sorry @laf should have elaborated.

I have used the webui, and there were no error messages coming up (as stated in the second paragraph)

`Trying v3 parameters rtap-snmp/authPriv ...` comes up after attempting to add the device, however it doesn't actually do anything after this.

**Comment by blortox** [comment]
@laf In reply to ##LibreNMS.

I've added an txt file of the stout when running the addhost.php script with with $debug=true;.

[add_host_debug.txt](https://github.com/librenms/librenms/files/378396/add_host_debug.txt)

**Comment by laf** [comment]
Update and all should be good.

**Comment by blortox** [comment]
Can now add Juniper devices.

Thanks @laf
