### ISSUE TITLE
Unable to poll FortiGate interfaces in FortiOS 5.4.1

### ISSUE THREAD

**Issue by jleavers** [librenms/librenms#3859]
Hi,

- Interfaces are not recorded / graphed in FortiOS 5.4.1.
- No port entries in database for device ID.
- Ports are listed in inventory tab, but there is no Ports tab.
- CPU/memory graphing still works.
- Interfaces were recorded / graphed in 5.4.0 with no problems.
- Discovery/poller debug (5.4.0): http://pastebin.com/jBWumYgj
- Discovery/poller debug (5.4.1): http://pastebin.com/wxuCq7Gr

What other information would help in diagnosing this problem?

Thanks

**Comment by laf** [comment]
Need disco / polling debug with -m ports not -m os.

**Comment by jleavers** [comment]
Ah yes. Pastebin links updated.

**Comment by jleavers** [comment]
Update from Fortinet: 

> I have done some research and I have found in our internal database that there were made some design changes on Fortios 5.4.1 regarding SNMP.
> 
> In reference to the reported change in SNMP query result for ifDescr, the change was made in order to comply with RFC 1213. Here's short snippet from the documentation:
> 
> A textual string containing information about the
> interface. This string should include the name of
> the manufacturer, the product name and the version
> of the hardware interface...
> 
> Since the physical interface name does not comply with the description above, the ifDescr field was changed to the the value configured by the parameter "set description" on all interfaces. This will not be rolled back to the previous behavior on version 5.4 and earlier.

**Comment by jleavers** [comment]
Armed with this information - this works:

```
conf sys int
   edit port1
      set description "DESC" # This is the 'Comment' field in the GUI - separate to 'Alias'
   next
end
```

The problem is the poller still falls over if it gets to an interface for which you can't set a description (e.g. modem) - so none of the subsequent interfaces are polled.

It would be good if it could skip problem interfaces and continue.

**Comment by laf** [comment]
Can this be closed then?

**Comment by jleavers** [comment]
I guess so, root cause was a change by Fortinet not a LibreNMS bug!

**Comment by jpplante** [comment]
How does one use the information provided to get the Fortigate 5.4.1 interface statistics to start collecting?

**Comment by jleavers** [comment]
I had to configure every interface with both a description and an alias - after that it started working without any LibreNMS changes.

```
conf sys int
   edit port1
      set description "LAN"
      set alias "LAN"
   next
end
```

**Comment by jpplante** [comment]
ok perfect.  Thank you for the clarification.

**Comment by amisense** [comment]
Resolved!
Added value to "description" (Comment in GUI) and picked up all ports on discovery.
Thanks,

**Comment by geordish** [comment]
Adding the following to config.php should also resolve this.
```php
$config['os']['fortigate']['empty_ifdescr']    = 1;
```

**Comment by xdroop** [comment]
Ugly script to take a FortiOS config file and output the commands necessary to populate both the "Description" and "Alias" fields if they are not already populated: [here](https://wiki.xdroop.com/space/FortiOS/5.4/LibreNMS+Interface+Graphs+Have+No+Names)

(Having done this, it might have been better just to put it up on GitHub. Huh.)
