### ISSUE TITLE
Allow more than one email for alerts

### ISSUE THREAD

**Issue by vectr0n** [librenms/librenms#3860]
I had mentioned on IRC the other day how it would be helpful to have the ability to specify more than one email address for alerting purposes. I have ran into a few instances where an end user needs to receive the alerts along with the admin at the same time. Also for situations where different departments need to get alerts for specific hosts as well as the admin. I know this can be done via email filtering, but I don't see why I should set something that "complex" up when I think other people could benefit from having the option to specify more than one email for alerts.

**Comment by f0o** [comment]
Just create users with privileges to the device/port in question.

This does not work with the contact override.

**Comment by vectr0n** [comment]
I have users with privileges to the device, and correct email under the user. Only the snmp contact is sent an alert, and no attempts in mail logs to send email to users email.

**Comment by laf** [comment]
I think it's fairly trivial to just add an explode(',') if we detect a comma to support multiple email addresses.
