### ISSUE TITLE
Cisco DMVPN - missing IPSEC tunnels

### ISSUE THREAD

**Issue by skaarup1986** [librenms/librenms#3862]
Hi,

I'm having issues with Librenms not adding all of my DMVPN tunnels to the dashboard under Routing->IPSEC Tunnels.     
When i do SNMPWALK with "CISCO-IPSEC-FLOW-MONITOR-MIB cikeTunnelEntry "  its shows all the tunnels but they are not all showing up in librenms. 

Please let me know if you need anything from me to debug this issue.

**Comment by laf** [comment]
please pastebin the output of: `./poller.php -h HOSTNAME -d -r -f -m cipsec-tunnels`

**Comment by Rosiak** [comment]
This could be related to a counter issue in the cipSecTunnelTable, I'm digging a bit into this.

**Comment by Rosiak** [comment]
Just tested on csr1000v-universalk9.16.02.02 the issue I experienced seems fixed here.
Problem was that counters in the cipSecTunnelTable got reset after a while, which resulted in bad data.

I saw the issue in:
c7200-adventerprisek9-mz.152-4.S4
c7200-adventerprisek9-mz.152-4.S7
c7200-adventerprisek9-mz.153-3.XB12
csr1000v-universalk9.03.11.04.S.154-1.S4-std

I have a hub-to-spoke setup with 1 hub and 3 spokes working, all graphs looks ok!

**Comment by skaarup1986** [comment]
Hi,
here you go:  http://pastebin.com/GrFSWxtZ

**Comment by laf** [comment]
pastebin link has expired.

**Comment by laf** [comment]
Please provide an updated pastebin link

**Comment by laf** [comment]
Please feel free to comment with the info required and we can re-open
