### ISSUE TITLE
IPv6 eBGP sessions not showing

### ISSUE THREAD

**Issue by eddielenton** [librenms/librenms#3863]
Heyo

IPv6 eBGP sessions don't appear under the routing section of Libre, specifically here 
https://librenms.exampledomain.com/routing/protocol=bgp/type=external/

IPv6 iBGP appears to be working fine however at this page
https://librenms.exampledomain.com/routing/protocol=bgp/type=external/

**Comment by Rosiak** [comment]
Odd, I have a install where this works just fine

**Comment by eddielenton** [comment]
Could it be due to the device we are getting the information from? It is running IOS-XE.

**Comment by Rosiak** [comment]
The eBGP sessions I see is fetched from a 4500X running IOS-XE too.

**Comment by eddielenton** [comment]
Looks like this may be an issue with the version of IOS-XE, closing this off :)
