### ISSUE TITLE
Reg: Maipu Network Switch

### ISSUE THREAD

**Issue by madhuneal** [librenms/librenms#3867]
Hi Team, 

I've tried to add maipu network switch, but vendor logo is unknown? also, Operating System type is Generic Device? 

Can you please let me know if anything needs to change in the backend code or anything related with web UI? 

I look forward to hearing from you guys. 

Many Thanks,
Madhu

**Comment by laf** [comment]
It needs support adding, when you went to create this issue the template has instructions on what's needed:

https://github.com/librenms/librenms/issues/new

**Comment by madhuneal** [comment]
Hi Laf, 

Yes, I went through with instructions but no luck ;( - Please find the discovery.php out log below. 

root@mrt:/opt/librenms# ./discovery.php -h office-ring-out -d -m os
LibreNMS 2015.master Discovery
Version info:
Commit SHA: e9bce1d322a94a100c3a716d50f538df48da61c1
DB Schema: 118
PHP: 5.5.9-1ubuntu4.17
MySQL: 5.5.50-0ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1]
SQL[SELECT revision FROM `dbSchema`] DB Schema already up to date.

SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE 'office-ring-out' ORDER BY device_id DESC]
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '6'] office-ring-out 6 generic /usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0MyPower (R) Operating System Software
MyPower S3400 version *.6(R)(integrity), compiled on May 14 2014, 16:34:01
Copyright (C) 2009 Maipu Communication Technology Co., Ltd. All Rights Reserved.

/usr/bin/snmpget -v2c -c COMMUNITY -Ovqn -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysObjectID.0.*.4.1.5*

| MyPower (R) Operating System Software
MyPower S3400 version 6.4.5.1.6(R)(integrity), compiled on May 14 2014, 16:34:01
Copyright (C) 2009 Maipu Communication Technology Co., Ltd. All Rights Reserved. | .1.3.6.1.4.1.5651.1.102.21 | /usr/bin/snmpget -v2c -c COMMUNITY -Oqvn -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalDescr.1No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Osqnv -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalMfgName.1No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 1.3.6.1.4.1.674.10895.3000.1.2.100.1.0No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 SML-MIB::product-Name.0No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-SMI::enterprises.14988.2No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.39165.1.6.0No Such Object available on this agent at this OID


#### Load disco module os ####
/usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0MyPower (R) Operating System Software
MyPower S3400 version *.6(R)(integrity), compiled on May 14 2014, 16:34:01
Copyright (C) 2009 Maipu Communication Technology Co., Ltd. All Rights Reserved.

/usr/bin/snmpget -v2c -c COMMUNITY -Ovqn -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysObjectID.0.*.4.1.5*

| MyPower (R) Operating System Software
MyPower S3400 version 6.4.5.1.6(R)(integrity), compiled on May 14 2014, 16:34:01
Copyright (C) 2009 Maipu Communication Technology Co., Ltd. All Rights Reserved. | .1.3.6.1.4.1.5651.1.102.21 | /usr/bin/snmpget -v2c -c COMMUNITY -Oqvn -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalDescr.1No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Osqnv -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalMfgName.1No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 1.3.6.1.4.1.674.10895.3000.1.2.100.1.0No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 SML-MIB::product-Name.0No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-SMI::enterprises.14988.2No Such Object available on this agent at this OID

/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.39165.1.6.0No Such Object available on this agent at this OID


>> Runtime for discovery module 'os': 0.202 seconds
#### Unload disco module os ####


SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '6' AND `attrib_type` = 'poll_mib' ]
SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '6' AND `attrib_type` = 'poll_mib' ] MIB: registering
snmptranslate -M /opt/librenms/mibs -IR -m all enterprises.5651.1.102.21 2>/dev/nullSNMPv2-SMI::enterprises.5*

SNMP translated: all::enterprises.5651.1.102.21 -> SNMPv2-SMI::enterprises.5651.1.102.21
     SNMPv2-SMI::enterprises.5651.1.102.21
Array
(
)
MIB: Could not load definition for SNMPv2-SMI::enterprises.5651.1.102.21


SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='network',`last_discovered_timetaken` ='2.201' WHERE `device_id` = '6'] Discovered in 2.201 seconds


SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','office-ring-out','1469190211.1497','2.261','1')] ./discovery.php office-ring-out 2016-07-22 17:53:33 - 1 devices discovered in 2.261 secs
MySQL: Cell[1/0s] Row[5/0s] Rows[0/0s] Column[0/0s] Update[1/0s] Insert[1/0s] Delete[0/0s]
root@mrt:/opt/librenms#

root@mrt:/opt/librenms# ./poller.php -h office-ring-out -r -f -d -m os
LibreNMS 2015.master Poller
Version info:
Commit SHA: e9bce1d322a94a100c3a716d50f538df48da61c1
Commit Date: 2016-07-18 23:37:37 +0100
DB Schema: 118
PHP: 5.5.9-1ubuntu4.17
MySQL: 5.5.50-0ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'office-ring-out' ORDER BY `device_id` ASC]
SQL[SELECT * FROM `devices` WHERE `device_id` = '6']
SQL[SELECT * FROM `vrf_lite_cisco` WHERE `device_id` = '6']
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '6'] office-ring-out 6 generic

SQL[INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('3','3','0','0.89','1.34','1.06','6',NOW())] /usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 sysObjectID.0SNMPv2-SMI::enterprises.5*

/usr/bin/snmpget -v2c -c COMMUNITY -OQnUst -m SNMPv2-MIB:HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 sysUpTime.0 sysLocation.0 sysContact.0 sysName.0 sysObjectID.0sysUpTime.0 = 1982900
sysLocation.0 = No.07,Krishna complex, Tilak Road, Tirupathi 517501
sysContact.0 = SkynetOnline Solutions.
sysName.0 = 102.9
sysObjectID.0 = enterprises.5*

/usr/bin/snmpget -v2c -c COMMUNITY -OvQ -m SNMPv2-MIB:HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 sysDescr.0MyPower (R) Operating System Software
MyPower S3400 version *.6(R)(integrity), compiled on May 14 2014, 16:34:01
Copyright (C) 2009 Maipu Communication Technology Co., Ltd. All Rights Reserved.

/usr/bin/snmpget -v2c -c COMMUNITY -OQnUst -m HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 snmpEngineTime.0 hrSystemUptime.0snmpEngineTime.0 = No Such Object available on this agent at this OID
hrSystemUptime.0 = No Such Object available on this agent at this OID

Using SNMP Agent Uptime (19829s)
[RRD Disabled]RRD[update /opt/librenms/rrd/office-ring-out/uptime.rrd N:19829] Uptime: 5h 30m 29s

#### Load poller module os ####
Generic :(

Hardware:  Version:  Features:  Serial:

>> Runtime for poller module 'os': 0.00046300888061523 seconds
#### Unload poller module os ####

[RRD Disabled]RRD[update /opt/librenms/rrd/office-ring-out/poller-perf-os.rrd N:0.00046300888061523]
SQL[SELECT * FROM device_groups ORDER BY name]
SQL[SELECT `device_group_id` FROM `device_group_device` WHERE `device_id`='6'] [RRD Disabled]RRD[update /opt/librenms/rrd/office-ring-out/poller-perf.rrd N:0.529] [RRD Disabled]RRD[update /opt/librenms/rrd/office-ring-out/ping-perf.rrd N:1.06] Polled in 0.529 seconds
Updating office-ring-out
Array
(
    [uptime] => 19829
    [last_ping] => Array
        (
            [0] => NOW()
        )

    [last_ping_timetaken] => 1.06
    [last_polled] => Array
        (
            [0] => NOW()
        )

    [last_polled_timetaken] => 0.529
)

SQL[UPDATE `devices` set `uptime` ='19829',`last_ping` =NOW(),`last_ping_timetaken` ='1.06',`last_polled` =NOW(),`last_polled_timetaken` ='0.529' WHERE `device_id` = '6'] UPDATED!

SQL[SELECT `device_group_id` FROM `device_group_device` WHERE `device_id`='6']
SQL[SELECT alert_schedule.schedule_id FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '6' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1]
SQL[SELECT `device_group_id` FROM `device_group_device` WHERE `device_id`='6']
SQL[SELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '6' ) || alert_map.target = '6'  )]

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','office-ring-out','1469190292.3854','0.596','1','mrt\n')] ./poller.php office-ring-out 2016-07-22 17:54:52 - 1 devices polled in 0.596 secs

MySQL: Cell[1/0s] Row[4/0s] Rows[6/0s] Column[3/0s] Update[1/0s] Insert[2/0s] Delete[0/0s]

Please let me know how to add new OS with vendor image.

Many Thanks,
Madhu
