### ISSUE TITLE
Juniper BGP neighbours not all discovered properly

### ISSUE THREAD

**Issue by BradHooper** [librenms/librenms#3877]
It appears that not all BGP peers on Juniper devices are making their way into the bgpPeers_cbgp table.

Attachment shows two peers. One works and the other doesn't. Both are configured the same however only one shows.

Also noticed there is a small typo on one of the SQL updates which stops updating astext changes to existing peers.

Happy to provide full outputs but over email.

[bgp-peers.txt](https://github.com/librenms/librenms/files/382446/bgp-peers.txt)

**Comment by laf** [comment]
Is this a disco output or polling?

What's the type in the SQL update

**Comment by BradHooper** [comment]
Can't find the typo no.

Checking BGP peer 103.26.68.65 Array
(
    [0] => Array
        (
            [device_id] => 23
            [bgpPeerIdentifier] => 103.26.68.65
            [afi] => ipv4
            [safi] => unicast
            [AcceptedPrefixes] => 0
            [DeniedPrefixes] => 0
            [PrefixAdminLimit] => 0
            [PrefixThreshold] => 0
            [PrefixClearThreshold] => 0
            [AdvertisedPrefixes] => 0
            [SuppressedPrefixes] => 0
            [WithdrawnPrefixes] => 0
            [AcceptedPrefixes_delta] => 0
            [AcceptedPrefixes_prev] => 0
            [DeniedPrefixes_delta] => 0
            [DeniedPrefixes_prev] => 0
            [AdvertisedPrefixes_delta] => 0
            [AdvertisedPrefixes_prev] => 0
            [SuppressedPrefixes_delta] => 0
            [SuppressedPrefixes_prev] => 0
            [WithdrawnPrefixes_delta] => 0
            [WithdrawnPrefixes_prev] => 0
            [context_name] => 
        )

)

Checking BGP peer 103.26.68.112 Array
(
)

**Comment by BradHooper** [comment]
Ah sorry forgot there was a debug function.

Checking BGP peer 103.26.68.65 established
start
7
207
75691
74975
2173927
948435
103.26.68.150OK u:0.00 s:0.00 r:7.37
RRD[[0;32mupdate /opt/librenms/rrd/snip/bgp-103.26.68.65.rrd N:207:7:74975:75691:2173927 --daemon unix:/var/run/rrdcached/rrdcached.sock[0m] 
SQL[[0;33mUPDATE `bgpPeers` set `bgpPeerState` ='established',`bgpPeerAdminStatus` ='start',`bgpPeerFsmEstablishedTime` ='2173927',`bgpPeerInUpdates` ='7',`bgpLocalAddr` ='103.26.68.150',`bgpPeerOutUpdates` ='207' WHERE `device_id` = '23' AND `bgpPeerIdentifier` = '103.26.68.65'[0m] 
SQL[[0;33mSELECT * FROM bgpPeers_cbgp WHERE `device_id` = '23' AND bgpPeerIdentifier = '103.26.68.65'[0m] Array
(
    [0] => Array
        (
            [device_id] => 23
            [bgpPeerIdentifier] => 103.26.68.65
            [afi] => ipv4
            [safi] => unicast
            [AcceptedPrefixes] => 0
            [DeniedPrefixes] => 0
            [PrefixAdminLimit] => 0
            [PrefixThreshold] => 0
            [PrefixClearThreshold] => 0
            [AdvertisedPrefixes] => 0
            [SuppressedPrefixes] => 0
            [WithdrawnPrefixes] => 0
            [AcceptedPrefixes_delta] => 0
            [AcceptedPrefixes_prev] => 0
            [DeniedPrefixes_delta] => 0
            [DeniedPrefixes_prev] => 0
            [AdvertisedPrefixes_delta] => 0
            [AdvertisedPrefixes_prev] => 0
            [SuppressedPrefixes_delta] => 0
            [SuppressedPrefixes_prev] => 0
            [WithdrawnPrefixes_delta] => 0
            [WithdrawnPrefixes_prev] => 0
            [context_name] => 
        )

)

Checking BGP peer 103.26.68.112 established
start
39
272
104096
102053
2959318
3122
103.26.68.150OK u:0.00 s:0.00 r:5.61
RRD[[0;32mupdate /opt/librenms/rrd/snip/bgp-103.26.68.112.rrd N:272:39:102053:104096:2959318 --daemon unix:/var/run/rrdcached/rrdcached.sock[0m] 
SQL[[0;33mUPDATE `bgpPeers` set `bgpPeerState` ='established',`bgpPeerAdminStatus` ='start',`bgpPeerFsmEstablishedTime` ='2959318',`bgpPeerInUpdates` ='39',`bgpLocalAddr` ='103.26.68.150',`bgpPeerOutUpdates` ='272' WHERE `device_id` = '23' AND `bgpPeerIdentifier` = '103.26.68.112'[0m] 
SQL[[0;33mSELECT * FROM bgpPeers_cbgp WHERE `device_id` = '23' AND bgpPeerIdentifier = '103.26.68.112'[0m] Array
(
)

**Comment by BradHooper** [comment]
That fix did the trick laf. I can't see any adverse effects across the whole installation.

I have noticed IPv6 peers don't enter the bgpPeers table as well.

**Comment by laf** [comment]
Got an example IPv6 address for me to check?

**Comment by BradHooper** [comment]
2001:504:13::140

**Comment by laf** [comment]
@BradHooper ok branch all up to date again. I've completely deleted the rrd files and db entries and left things to pick up - for me, that works fine.

If you want to test again then make sure you have a clean git setup and then do:

`git checkout issue-3877; git pull laf issue-3877`

**Comment by laf** [comment]
PR now all submitted and ready to go.
