### ISSUE TITLE
Heavy mysql disk I/O usage: possible improvements

### ISSUE THREAD

**Issue by candlerb** [librenms/librenms#3879]
This is librenms 42a8c272, running inside an ubuntu 16.04 VM (ganeti), mysql 5.7.13, and configured to use rrdcached. The underlying storage is a hard drive.

Monitoring a not particularly large network: 23 devices, 2805 ports (of which 493 up, 487 down, 76 disabled/shutdown)

Even with rrdcached the polling cycle is hitting the disk very hard. Here is the graph from [netdata](https://github.com/firehol/netdata/wiki) showing high proportion in iowait state for about 2.5 minutes out of every 5:

![image](https://cloud.githubusercontent.com/assets/44789/17129553/bb63faea-530b-11e6-8568-5dd32bdabeb5.png)

Running 'iotop' shows that the main source of disk activity is mysql. My suspicion is that it is doing lots of small writes in separate transactions, all being flushed to disk separately.

Turning on mysql query logging:

~~~
mysql> set global general_log_file='/tmp/mysql.log';
Query OK, 0 rows affected (0.00 sec)

mysql> set global log_output='file';
Query OK, 0 rows affected (0.00 sec)

mysql> set global general_log=on;
Query OK, 0 rows affected (0.02 sec)
~~~

This gives the following overall results for a 5 minute period:

~~~
# grep '^2016-07-26T07:3[0-4]' /tmp/mysql.log | awk '{print $3,$4}' | sort | uniq -c
     41 Change user
     32 Connect librenms@localhost
     71 Init DB
     42 Query DELETE
     46 Query INSERT
  11682 Query SELECT
   6865 Query UPDATE
     46 Query begin
     47 Query commit
    163 Query select
      2 Query set
      1 Query update
     32 Quit
~~~

Looking at the begin/commit pairs, these seem to wrap a single insert, which alternates between these:

~~~
2016-07-26T07:27:24.214313Z  190 Query  begin
2016-07-26T07:27:24.214517Z  190 Query  INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','12','1469518019.0874','25.12','1','librenms\n')
2016-07-26T07:27:24.214731Z  190 Query  commit
~~~

~~~
2016-07-26T07:27:24.359709Z  193 Query  begin
2016-07-26T07:27:24.359864Z  193 Query  INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('','','','','','','3',NOW())
2016-07-26T07:27:24.360045Z  193 Query  commit
~~~

I'm not worried about SELECT since the database should be small enough to remain in memory, so that leaves the UPDATEs:

~~~
# grep '^2016-07-26T07:3[0-4]' /tmp/mysql.log | egrep 'INSERT INTO `(device_perf|perf_times)`' | wc -l
46
~~~

Now looking at the UPDATEs:

~~~
# grep '^2016-07-26T07:3[0-4].*UPDATE' /tmp/mysql.log | cut -c40-80 | sort | uniq -c | sort -rn | head
   2326 UPDATE `ports_statistics` set `ifInNUcast
   1936 UPDATE `ports_stp` set `priority` ='128',
   1421 UPDATE `ports` set `poll_time` ='14695182
    573 UPDATE `ports` set `poll_time` ='14695183
    332 UPDATE `ports` set `poll_time` ='14695184
     84 UPDATE `sensors` set `sensor_current` ='1
     42 UPDATE `session` set `session_value` ='0q
     25 UPDATE `sensors` set `sensor_current` ='3
     15 UPDATE `sensors` set `sensor_current` ='2
     14 UPDATE `stp` set `protocolSpecification`
~~~

If mysql has autocommit on, then I think each of these will be flushed to disk separately.

As an experiment I [changed the flushing behaviour](http://dev.mysql.com/doc/refman/5.5/en/innodb-parameters.html#sysvar_innodb_flush_log_at_trx_commit):

~~~
mysql> set global innodb_flush_log_at_trx_commit=0;
Query OK, 0 rows affected (0.01 sec)
~~~

and this has made a huge reduction in iowait:

![image](https://cloud.githubusercontent.com/assets/44789/17130741/fc014f5c-5311-11e6-84ec-ee82ed5289c7.png)

It means I could lose up to 1 second's worth of data if the system crashes, which of course, I don't care about at all :-)

So I make the following suggestions for improvements:

* It may work better to batch updates for a device into a single transaction (or it may not, especially if the transaction is open for a long time)

* In the documentation, point to the `innodb_flush_log_at_trx_commit` option and suggest people try it

**Comment by candlerb** [comment]
For completeness: here is the graph of disk I/O ops per second before the change:

![image](https://cloud.githubusercontent.com/assets/44789/17130893/bd7e2ccc-5312-11e6-8f2e-1411fccfc400.png)

And after:

![image](https://cloud.githubusercontent.com/assets/44789/17130913/d4f2a0ea-5312-11e6-8199-b84828441eb4.png)

**Comment by crcro** [comment]
i think that this is way the VM edition should be only use for rapid deployment for test.
if you want to use it in production environment you should install your own software and clone the git repo

**Comment by candlerb** [comment]
Sorry if I was not clear: I am not using a VM download of librenms. Rather I did the following:

1. Create an empty VM in our existing ganeti cluster
2. Install Ubuntu 16.04.1 from scratch, using the server x86_64 ISO.
3. Inside that, create a 16.04 lxd container
4. Install librenms inside that container, following the manual installation instructions (git clone etc)

Ultimately librenms will move to dedicated hardware - the VM is for initial testing. (This is the reason for putting it inside a container: the container can easily be migrated, without having to run a full-fat VM on the monitoring server)

But in any case, I believe that everything I've posted above is equally valid whether librenms is running in a VM or on dedicated hardware. `fsync` will propagate through to the underlying platform by means of write barriers.

**Comment by laf** [comment]
We've run innodb_flush_log_at_trx_commit=2; at work for a while now. I'm trying 0 to see if that makes any difference. Unfortunately we aren't IO constrained so I don't expect to see a difference here.

**Comment by candlerb** [comment]
Good suggestion, I've just compared with 2 as well.

Before (`innodb_flush_log_at_trx_commit=0`):

![image](https://cloud.githubusercontent.com/assets/44789/17138627/0fabba5c-5339-11e6-9b97-0ab6c8c210f9.png)

After (`innodb_flush_log_at_trx_commit=2`):

![image](https://cloud.githubusercontent.com/assets/44789/17138765/b414a1d0-5339-11e6-97a8-1cdb4b17610b.png)

iowait is the purple area. It looks a bit higher with 2 than 0 (but still much better than with the default of 1)

**Comment by f0o** [comment]
I've it set to 2 as well, running on a galera multi-master setup with a handfull of independent librenms installs.

We occasionally hit I/O despite being ssd-only. But this happens almost exclusively when applying alter-statements in the schema.

**Comment by laf** [comment]
I've put together a doc that has some performance improvement recommendations in it which includes this: #3882

Thanks for feeding back.
