### ISSUE TITLE
Proposed doc update

### ISSUE THREAD

**Issue by laf** [librenms/librenms#388]
So I've moved the docs (merged files from doc and wiki) into a structure:

https://github.com/laf/librenms/wiki

https://github.com/laf/librenms/tree/docs

Obviously this changes the way things work at the moment so we need to work out the best way forward (if any changes are needed).

* Any links from /doc/ before will no longer work.

* Contributing to the wiki will be a bit harder. People can edit the wiki directly still but can't add to the directory structure, this can only be done by pushing directly to the github url for the wiki which is restricted.

* When the wiki is updated, it will need someone to pull the changes into the /doc/ submodule and submit a PR.

Anyone see a better way of doing this?

**Comment by f0o** [comment]
`When the wiki is updated, it will need someone to pull the changes into the /doc/ submodule and submit a PR.`

Are you sure about this?

Unless you specify a specific commit hash to the submodule, it should just pull the most recent version. So it shouldnt require any PRs on the repo.

Or am I mistaken?

**Comment by laf** [comment]
I could be wrong but it actually seems worse than that.

Checking out my repo and switching to the docs branch, you have to run git submodule init and then git submodule update.

It also doesn't seem to pull out the latest version from the wiki.

If anyone else has got experience of how submodules should work that would be good.

**Comment by laf** [comment]
I really like @f0o find of: http://librenms-master.readthedocs.org/en/latest/

This works really well, is searchable and has built in support for github via webhooks. @paulgear if you are happy with this approach then could you create an account on RTD?

The docs would then still be available in /docs/ but would get pushed out to something like docs.librenms.org and maybe disable the wiki?

**Comment by f0o** [comment]
RTD moved to http://librenms.readthedocs.org/

**Comment by f0o** [comment]
This can be closed :)

**Comment by laf** [comment]
Indeed :)
