### ISSUE TITLE
Syslogs not showing for devices added using hostnames

### ISSUE THREAD

**Issue by filipVisko** [librenms/librenms#3891]
I've set up a few clients to send syslogs to our LibreNMS box which is using rsyslog.

While the syslogs are being received by the box from each device, the only syslogs that are viewable from the librenms webpage are from the sole device that was added using an IP address.

**Comment by laf** [comment]
Most likely because we aren't receiving the logs with the hostname or the IP we are seeing isn't the IP the hostname responded on.

**Comment by nerdalertdk** [comment]
I have an similar problem, vmware 6, don't return ip on ports so the syslog script can't find the host

![image](https://cloud.githubusercontent.com/assets/3426495/17417838/b51a2f60-5a95-11e6-80c5-a2ae5268b4cf.png)

info:
VMware ESXi 6.0.0 build-3620759
VMware ESXi 6.0.0 Update 2

possible work around is use "Resolved IP" form overview since it findes the ip adress

**Comment by laf** [comment]
We don't use port info for syslog lookup, it's based on device hostname, sysname or IP

**Comment by nerdalertdk** [comment]
include/syslog.php
```php
function get_cache($host, $value) {
    global $dev_cache;

    if (!isset($dev_cache[$host][$value])) {
        switch ($value) {
        case 'device_id':
            // Try by hostname
            $ip = inet_pton($host);
            $dev_cache[$host]['device_id'] = dbFetchCell('SELECT `device_id` FROM devices WHERE `hostname` = ? OR `sysName` = ? OR `ip` = ?', array($host, $host, $ip));
            // If failed, try by IP
            if (!is_numeric($dev_cache[$host]['device_id'])) {
                $dev_cache[$host]['device_id'] = dbFetchCell('SELECT `device_id` FROM `ipv4_addresses` AS A, `ports` AS I WHERE A.ipv4_address = ? AND I.port_id = A.port_id', array($host));
            }
            break;

        case 'os':
            $dev_cache[$host]['os'] = dbFetchCell('SELECT `os` FROM devices WHERE `device_id` = ?', array(get_cache($host, 'device_id')));
            break;

        case 'version':
            $dev_cache[$host]['version'] = dbFetchCell('SELECT `version` FROM devices WHERE `device_id`= ?', array(get_cache($host, 'device_id')));
            break;

        default:
            return null;
        }//end switch
    }//end if

    return $dev_cache[$host][$value];

}//end get_cache()
```

the esxi boks has no record in ipv4_address since librnms don't get the info from snmp

**Comment by laf** [comment]
I'm still not sure what you are getting at here.

From syslog we should be able to select the device from the IP or hostname of it, those are looked up using hostname, sysname and IP in the devices table. The check for ipv4_address is a fall back and a bad(ish) one at that as you can have the same IP on more than one device.

You could uncomment the logfile line in syslog.php, restart syslog and read logs/librenms.log to see what is being passed across.

**Comment by nerdalertdk** [comment]
I am getting the syslog data from my vmware server to syslog-ng (added an file destination) but VMware is returning it's IP addres as host, so librenms don't know where to link the data since the fallback of looking into ip4_adress fails

it just send the data to null (I think, can't find it in MySQL)

The ip field in my database is just some random string.
Look like this "c4f5kr4" (I'm not at my Er på vej! Now so can't check

Will try and uncomment the line

**Comment by laf** [comment]
The IP is used, ip in the devices table is varbinary to store IPs. We resolve the hostname to an IP then store this - in the webui it should show you the IP:

![image](https://cloud.githubusercontent.com/assets/3941142/17449564/55ef2086-5b53-11e6-88fc-17cd217d393c.png)

So the only way this still wouldn't work is if the IP sent from vmware doesn't match the IP in the DB.

**Comment by nerdalertdk** [comment]
Hi again,

just turn logging on, now i'm seeing this in librenms.log, so data is comming my way, and host ip is correct.

`19X.XX.XX.21||local4||debug||debug||a7||2016-08-05 22:45:25||verbose vpxa[7864BB70] [Originator@6876 sub=VpxaHalCnxHostagent opID=WFU-6657d60e] [WaitForUpdatesDone] Received callback||Vpxa`

sadly i'm also seeing this

`2016-08-06 00:43:02   SYSLOG-NG   Syslog connection accepted; fd=\'17\', client=\'AF_INET(19X.XX.XX.21:47871)\', local=\'AF_INET(0.0.0.0:514)\'
2016-08-06 00:43:02   SYSLOG-NG   Syslog connection closed; fd=\'17\', client=\'AF_INET(19X.XX.XX.21:52291)\', local=\'AF_INET(0.0.0.0:514)\'
2016-08-06 00:43:02   SYSLOG-NG   I/O error occurred while reading; fd=\'17\', error=\'Connection reset by peer (104)\'`

**Comment by laf** [comment]
Closing if it's now working.
