### ISSUE TITLE
%devices.uptime email template

### ISSUE THREAD

**Issue by tuksaur** [librenms/librenms#3892]
trying to print %devices.uptime in email template.
value "%value.uptime" prints "NOC.uptime". NOC is default email (noc_alerts@...)

**CURRENT TEMPLATE:**
%title
Severity: %severity {if %state == 0}Time elapsed: %elapsed {/if}
Timestamp: %timestamp
Unique-ID: %uid
Rule: {if %name}%name{else}%rule{/if}
{if %faults}Faults:
{foreach %faults}  #%key: %value.string {/foreach}{/if}
Alert sent to: {foreach %contacts}%value <%key> {/foreach}
**Uptime: %value.uptime**

Link: http://[DEVICE_NAME]/device/device=%hostname/

**EMAIL RESULT:**
Alert for device [DEVICE_NAME] - Uptime
Severity: warning 
Timestamp: 2016-07-28 12:46:03
Unique-ID: 14544
Rule: Uptime
Faults:
 #1: sysDescr => Cisco IOS Software,
C800 Software (C800-UNIVERSALK9-M), Version 15.3(3)M3, RELEASE SOFTWARE
(fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2014 by Cisco Systems, Inc.
Compiled Wed 28-May-14 07:24 by prod_rel_team;  
Alert sent to: NOC <noc_alerts@...> 
**Uptime: NOC.uptime**

Link: http://[DEVICE_NAME]/device/device=[DEVICE_NAME]/

Any way to get the device's uptime printed to email template through global variable or %value.uptime?

**Comment by Rosiak** [comment]
#3893
