### ISSUE TITLE
Syslog formatting for Linux systems

### ISSUE THREAD

**Issue by florianbeer** [librenms/librenms#3924]
I am collecting several Linux syslogs (rsyslog on Debain & Ubuntu) on my monitoring machine and feeding them to LibreNMS. Some messages are not formatted correctly when written to the database, so I get parts of the message written into the program name column etc.

This issue is to let you know, that I am trying to work out those problems in my fork and will be submitting a pull request referencing this issue as soon as I'm satisfied with my outcome.

**Comment by florianbeer** [comment]
I've found the line that's messing up my syslog imports: https://github.com/librenms/librenms/blob/master/includes/syslog.php#L90

The fix was actually already implemented in 49be12423820706874f653e2f0c075c0000cdea0 but then reverted in fb9224d507d88635452470255095e2b11e28daa4. Discussion is here #3036

It seems the line was introduced in this ancient commit 2778e4b90d8a0d38f11b9e6fb29332fae57d19f5 but subsequently all other `if`/`elseif` statements where removed and only the catchall remains. That's why messages like the following get their program name overwritten:
```
Aug  1 20:00:38 hostname dovecot: lda(user@example.org): sieve: msgid=<2036587170037.F15ACB0006B@example.org>: stored mail into mailbox 'INBOX'
```
The resulting program name is `lda(user@example.org)`, other examples of wrong program names are:

- `( CD / && RUN-PARTS --REPORT /ET`
- `AUTH-WORKER(10015)` thousands of them since it includes the number
- `CONNECT FROM [192.169.2.1]` also thousands of them since it includes a connecting IP
- `WWW[1123]` 
- ...

All of those lines have their program name set correctly, but it gets overwritten by this weird regex parsing. I just don't know which use case this should have. The proposed fix was to only overwrite the program name if it is empty. That solution works great for me on 9 different servers.

Please @paulgear, @laf re-consider checking for empty program name before letting this regex parse the line. The current way is just not usable at all.

**Comment by laf** [comment]
I'm not a user of the syslog side so it's not something I'm going to really spend much time on I'm afraid.

**Comment by florianbeer** [comment]
Well, I can attest that the fix in 49be124 actually works. I've been running that code for several days now and it produces very structured logs with no parsing errors. I can only speak for the *nix server side of things here, since currently I don't have any routers or switches connected to this monitoring box, but since the change is in the `if ($os == 'linux')` branch of the code, I'd say it is safe to use.

If you agree, I can make another pull request, that re-introduces the check.

**Comment by murrant** [comment]
@florianbeer go ahead an make a PR for it.  We have some pretty good test for the syslog stuff, so you should be able to tell if it messes anything up.  You might also want to add some test cases.

**Comment by laf** [comment]
No further feedback provided + syslog was refactored from what 49be124 would fix anyway.
