### ISSUE TITLE
Question Missing CPU, Inventory and Model# with Allied Telesis switches x-series

### ISSUE THREAD

**Issue by claytonhubbard** [librenms/librenms#3931]
When adding Allied Telesis switches, the CPU graphs are missing as well as the model#. A bonus will be to get inventory added as well. What would be the best approach to add this support in LibreNMS for this?

**Comment by laf** [comment]
To provide access to the device or provide an snmpwalk with the relevant MIBs loaded.

**Comment by laf** [comment]
@claytonhubbard Bump

**Comment by mattie47** [comment]
@claytonhubbard  FYI I've been adding support for x-series under https://github.com/librenms/librenms/pull/7670

I haven't looked at inventory support yet though.
