### ISSUE TITLE
Recognize HP1810 switches as Comware and not as Generic Device

### ISSUE THREAD

**Issue by rtkmcarse** [librenms/librenms#3933]
Can the detection be updated for HP1810 switches do they are not detected as Generic Device?
```

/usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0HP 1820-8G Switch J9979A, PT.01.14, Linux 3.6.5-79c95a77, U-Boot 2012.10-00116-g3ab515c (Jul 30 2014 - 10:52:01)

/usr/bin/snmpget -v2c -c COMMUNITY -Ovqn -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysObjectID.0.*.*.*

| HP 1820-8G Switch J9979A, PT.01.14, Linux 3.6.5-79c95a77, U-Boot 2012.10-00116-g3ab515c (Jul 30 2014 - 10:52:01) | .1.3.6.1.4.1.11.2.3.7.11.167 | /usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 1.3.6.1.4.1.674.10895.3000.1.2.100.1.0No Such Object available on this agent at this OID
```

**Comment by Rosiak** [comment]
Isn't it Procurve/Aruba and not Comware?

**Comment by rtkmcarse** [comment]
@Rosiak You may be correct. Now that I go back and look deeper.
I have several, and am willing to provide whatever details needed to fix.

**Comment by paulgear** [comment]
1810s are definitely ProCurve, and not CLI-manageable; 1910s are Comware (sort of - the CLI is not really supported).

**Comment by mcarse** [comment]
There is also a typo on my part, which is that I need 1820's not (as the output says).
I can't edit the bug title, but can we get 1820's identified as ProCurve please?

**Comment by Rosiak** [comment]
Can you supply the sysObjectId for this device?
Seems obfuscated in the output shown.

**Comment by mcarse** [comment]
Ran 'discovery.php -h hostname -d -m os' and this is what it reports. Haven't obfuscated. Anything else I can provide?


```
/usr/bin/snmpget -v2c -c COMMUNITY -Ovqn -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysObjectID.0.*.*.*

| HP 1820-8G Switch J9979A, PT.01.14, Linux 3.6.5-79c95a77, U-Boot 2012.10-00116-g3ab515c (Jul 30 2014 - 10:52:01) | .1.3.6.1.4.1.11.2.3.7.11.167 | /usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 1.3.6.1.4.1.674.10895.3000.1.2.100.1.0No Such Object available on this agent at this OID
```

**Comment by laf** [comment]
Please provide all of the information asked for when creating an issue: https://github.com/librenms/librenms/issues/new
