### ISSUE TITLE
Add hw-group STE 2 Smart Ethernet Thermometer

### ISSUE THREAD

**Issue by flotpg** [librenms/librenms#3934]
HW Group STE 2 is not recognised, can you please add it

- vendor link: ste2 hw group
- ./discovery.php -h HOSTNAME -d -m os: http://pastebin.com/LLmxq8TW
- ./poller.php -h HOSTNAME -r -f -d -m os: http://pastebin.com/4YJQpF0r
- snmpbulkwalk -On -v2c -c COMMUNITY HOSTNAME .: http://pastebin.com/wQPpgjFk
- mib downloaded from device: http://pastebin.com/BKuECkZW
- snmpwalk with mib loaded: http://pastebin.com/vzUhyxQK

I see you've already added hw group's poseidon modell...

Thx a lot.

**Comment by flotpg** [comment]
Please let me know if I can contribute more details/etc...
Thx.

**Comment by laf** [comment]
The walks haven't been done with `-On` as requested.

**Comment by DennisSc** [comment]
Have you tried something like this as a group pattern:

%devices.sysObjectID ~ "iso.3.6.1.4.1.21796.4.9"

(enter into group pattern fields as follows: pattern: devices.sysObjectID, condition: like, value: "iso.3.6.1.4.1.21796.4.9")

does it work? What is displayed in device overview under "Object ID"?

regards

**Comment by flotpg** [comment]
Sorry, now the walk with -On:
http://pastebin.com/puiyYHuD

**Comment by flotpg** [comment]
<img width="943" alt="screen shot 2016-08-16 at 16 40 08" src="https://cloud.githubusercontent.com/assets/20798074/17702932/33ad2722-63d0-11e6-83de-a6869afcdd89.png">

**Comment by DennisSc** [comment]
ah ok - then try adding a new group with pattern as follows:

%devices.sysObjectID ~ "enterprises.21796.4.9"

regards

**Comment by flotpg** [comment]
Ok, thx

What do I have to do?

**Comment by crcro** [comment]
@flotpg ... the ste2 support was merged ... can you please give it a try and some feedback (i don't have this device to test on it)

**Comment by flotpg** [comment]
Hey crcro,
thx a lot for your work. updated now... seems to be still generic. 
Btw. I got a response from the vendor which states the STE2 is not snmp v2 compatible (or not fully) and the recommend to use v1.

I re-added it as v1 and did a ./discovery -h FQDN

Devices is recognized as server, set it manually to environment. Seems that the sensors are not recognized..
<img width="1290" alt="screen shot 2016-08-21 at 12 44 22" src="https://cloud.githubusercontent.com/assets/20798074/17836732/0a77a7ee-679d-11e6-97fc-69a48a91dee3.png">

**Comment by flotpg** [comment]
This table is from the device's web interface.
<img width="1054" alt="screen shot 2016-08-21 at 12 48 38" src="https://cloud.githubusercontent.com/assets/20798074/17836748/9be18344-679d-11e6-87c1-022a997d5d80.png">

**Comment by crcro** [comment]
@flotpg ... another fix was merged ... can you please update and test again.

**Comment by flotpg** [comment]
hey crcro, updated, re-added the device. Seems to not work:
<img width="1264" alt="screen shot 2016-08-22 at 10 50 00" src="https://cloud.githubusercontent.com/assets/20798074/17848908/6fd57616-6856-11e6-808f-043d85843140.png">

./discovery.php -d -h ste2-01
http://pastebin.com/7Up2SZVR

anything else i can contribute?

**Comment by crcro** [comment]
@flotpg updated the code, please rediscovery your host and check again ... sorry for headaches

**Comment by flotpg** [comment]
hey crcro, didn't work... how can I check if have the same source?
It's still generic... now with less information shown...re-added (snmp v1), discovery -h fqdn:

**Comment by flotpg** [comment]
./discovery.php -h HOSTNAME -d -m os: http://pastebin.com/badvN5tN
./poller.php -h HOSTNAME -r -f -d -m os: http://pastebin.com/w3XMMWfT

talked to the vendor, v2 support is incomplete, shell use snmp v1...

**Comment by crcro** [comment]
run ./daily.sh from your install dir

**Comment by flotpg** [comment]
i did, and i also did a git pull to make sure...

**Comment by crcro** [comment]
could give that device internet access (only for snmp) and create a snmp community to query the device?

**Comment by flotpg** [comment]
community: public
ip: 83.171.138.212
udp port 61

**Comment by crcro** [comment]
@flotpg ... fix merged, please run ./daily.sh and rediscover your device

**Comment by flotpg** [comment]
@crcro "2016-08-24 11:33:58	Device Icon changed generic => hwg"

So device is now recognised as hw-group with correct vendor logo - thx a lot... 

But the sensors aren't listed!

**Comment by crcro** [comment]
@flotpg ... got it fully working, PR submitted, you can now disable the access to the device, thanks!

**Comment by flotpg** [comment]
thx @crcro , disabled... waiting for the code ;)

**Comment by crcro** [comment]
@flotpg ... code merged

**Comment by flotpg** [comment]
@crcro you nailed it. Thank you very much! Works great now
<img width="1883" alt="screen shot 2016-08-24 at 16 07 51" src="https://cloud.githubusercontent.com/assets/20798074/17933611/102a73ea-6a15-11e6-9b83-fe3e8c21d24d.png">

**Comment by crcro** [comment]
@flotpg gladly .... you can close the issue then :)

**Comment by flotpg** [comment]
Done :)
