### ISSUE TITLE
HP Laserjet Toner Levels Missing

### ISSUE THREAD

**Issue by mzac** [librenms/librenms#3960]
I have a HP Laserjet 1518NI and LibreNMS is not picking up the toner levels

<pre>
root@pi:/opt/librenms# snmpwalk -v1 -c public hplj 1.3.6.1.2.1.43.11.1.1
iso.3.6.1.2.1.43.11.1.1.2.1.1 = INTEGER: 1
iso.3.6.1.2.1.43.11.1.1.2.1.2 = INTEGER: 1
iso.3.6.1.2.1.43.11.1.1.2.1.3 = INTEGER: 1
iso.3.6.1.2.1.43.11.1.1.2.1.4 = INTEGER: 1
iso.3.6.1.2.1.43.11.1.1.3.1.1 = INTEGER: 1
iso.3.6.1.2.1.43.11.1.1.3.1.2 = INTEGER: 2
iso.3.6.1.2.1.43.11.1.1.3.1.3 = INTEGER: 3
iso.3.6.1.2.1.43.11.1.1.3.1.4 = INTEGER: 4
iso.3.6.1.2.1.43.11.1.1.4.1.1 = INTEGER: 3
iso.3.6.1.2.1.43.11.1.1.4.1.2 = INTEGER: 3
iso.3.6.1.2.1.43.11.1.1.4.1.3 = INTEGER: 3
iso.3.6.1.2.1.43.11.1.1.4.1.4 = INTEGER: 3
iso.3.6.1.2.1.43.11.1.1.5.1.1 = INTEGER: 3
iso.3.6.1.2.1.43.11.1.1.5.1.2 = INTEGER: 3
iso.3.6.1.2.1.43.11.1.1.5.1.3 = INTEGER: 3
iso.3.6.1.2.1.43.11.1.1.5.1.4 = INTEGER: 3
iso.3.6.1.2.1.43.11.1.1.6.1.1 = STRING: "Black Cartridge HP CB540A"
iso.3.6.1.2.1.43.11.1.1.6.1.2 = STRING: "Cyan Cartridge HP CB541A"
iso.3.6.1.2.1.43.11.1.1.6.1.3 = STRING: "Magenta Cartridge HP CB543A"
iso.3.6.1.2.1.43.11.1.1.6.1.4 = STRING: "Yellow Cartridge HP CB542A"
iso.3.6.1.2.1.43.11.1.1.7.1.1 = INTEGER: 18
iso.3.6.1.2.1.43.11.1.1.7.1.2 = INTEGER: 18
iso.3.6.1.2.1.43.11.1.1.7.1.3 = INTEGER: 18
iso.3.6.1.2.1.43.11.1.1.7.1.4 = INTEGER: 18
iso.3.6.1.2.1.43.11.1.1.8.1.1 = INTEGER: 2829492
iso.3.6.1.2.1.43.11.1.1.8.1.2 = INTEGER: 2388612
iso.3.6.1.2.1.43.11.1.1.8.1.3 = INTEGER: 2103943
iso.3.6.1.2.1.43.11.1.1.8.1.4 = INTEGER: 2112011
iso.3.6.1.2.1.43.11.1.1.9.1.1 = INTEGER: 2320184
iso.3.6.1.2.1.43.11.1.1.9.1.2 = INTEGER: 2006434
iso.3.6.1.2.1.43.11.1.1.9.1.3 = INTEGER: 1767312
iso.3.6.1.2.1.43.11.1.1.9.1.4 = INTEGER: 1774089
</pre>

<pre>
root@pi:/opt/librenms# ./discovery.php -d -h 5 -m toner
LibreNMS 2015.master Discovery
Version info:
Commit SHA: c63728c55281fa119af56ca13b9d395641817e01
DB Schema: 126
PHP: 5.6.24-0+deb8u1
MySQL: 5.5.50-0+deb8u1
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2.1

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1]
SQL[SELECT revision FROM `dbSchema`] DB Schema already up to date.

SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `device_id` = '5' ORDER BY device_id DESC]
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '5'] hplj 5 jetdirect  (printer)
#### Load disco module toner ####

>> Runtime for discovery module 'toner': 0.001 seconds
#### Unload disco module toner ####

SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '5' AND `attrib_type` = 'poll_mib' ]
SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='printer',`last_discovered_timetaken` ='0.003' WHERE `device_id` = '5'] Discovered in .003 seconds

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','5','1470332209.8307','0.121','1')] ./discovery.pp 5 2016-08-04 13:36:49 - 1 devices discovered in 0.121 secs
MySQL: Cell[1/0s] Row[4/0s] Rows[1/0s] Column[0/0s] Update[1/0.05s] Insert[1/0.02s] Delete[0/0s]
</pre>

My validate.php
<pre>
Version info:
Commit SHA: 9d6e2e54669fb3cc7446f6b065087f0076b68d11
DB Schema: 126
PHP: 5.6.24-0+deb8u1
MySQL: 5.5.50-0+deb8u1
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2.1
</pre>

**Comment by crcro** [comment]
please check to see if you have enabled the printer support in config.php by adding:

$config['enable_printers']              = 1;

**Comment by mzac** [comment]
Thanks, this has fixed it.  I'm just surprised that this is set to 0 by default?
