### ISSUE TITLE
Raspberry Pi Volts, Temp, Clock

### ISSUE THREAD

**Issue by mzac** [librenms/librenms#3962]
It would be nice to be able to graph the voltage, temperature and clock values of a raspberry pi.  This would be done through an application using the agent.

I was testing Observium before I moved to LibreNMS and they already have this feature as part of the observium_agent

20160408 Rosiak
No content related to OBS, please.

**Comment by crcro** [comment]
@mzac if you provide access to some pi i could write some snmp extend code to get your info

**Comment by Rosiak** [comment]
#4057
