### ISSUE TITLE
Multiple authentication hosts?

### ISSUE THREAD

**Issue by b4** [librenms/librenms#3965]
Sorry if this is already a feature - but I am not seeing it documented anywhere.

Is it possible to specify multiple hostnames for a specified authentication method?

We are using RADIUS and we'd like the ability to fall back to a secondary if the primary is down.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
