### ISSUE TITLE
How Add dBm Grahps To Alcatel

### ISSUE THREAD

**Issue by jgaitansmk** [librenms/librenms#3968]
Hello dear team of LibreNMS,
in the first place want to congratulate them on their excellent work and dedication in creating a very full tool such as LibreNMS, amazed with the platform. -

Tell them that I'm currently trying to create a level Optical Sensor for the Alcatel equipment, create a Script based on which you have created for Juniper but it does not work, basically create a file called alcatel.inc.php in the /opt/librenms/includes/discovery/sensors/dbm directory, as shown above use as basis the file junos.inc.php.

I share the Script you believe if I made an error when creating it or if I may suggest that further step should I get the Script to work me if work me with like will share them the file for their upcoming publications. I am attentive to your comments, in advance thank you for your prompt and valuable help.

---

root@LibreNMS1:/opt/librenms/includes/discovery/sensors/dbm# more alcatel.inc.php

```
<?php
/*
 * LibreNMS
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.  Please see LICENSE.txt at the top level of
 * the source code distribution for details.
 * Formula: 10 * log10 (uWatts*0.0001)
 */

if ($device['os'] == 'timos' || $device['os_group'] == 'Timos') {
    echo 'TimOs - Alcatel';
    $multiplier= 1;
    $divisor = 1;
    foreach ($timos_oids as $index => $entry) {
        if (is_numeric($entry['tmnxDDMRxOpticalPower'])) {
            $oid = '.1.3.6.1.4.1.6527.3.1.2.2.4.31.1.21.1.'.$index;
            $descr = dbFetchCell('SELECT `ifDescr` FROM `ports` WHERE `ifIndex`= ? AND `device_id` = ?', array($index, $device['device_id'])) . ' R
x Power';
            $limit_low = 10 * log10 (($entry['tmnxDDMRxOpticalPowerLowWarning'])*0.0001);
            $warn_limit_low = 10 * log10 (($entry['tmnxDDMRxOpticalPowerLowAlarm'])*0.0001);
            $limit = 10 * log10 (($entry['tmnxDDMRxOpticalPowerHiWarning'])*0.0001);
            $warn_limit = 10 * log10 (($entry['tmnxDDMRxOpticalPowerHiAlarm'])*0.0001);
            $current = $entry['tmnxDDMRxOpticalPower'];
            $entPhysicalIndex = $index;
            $entPhysicalIndex_measured = 'ports';
            discover_sensor($valid['sensor'], 'dbm', $device, $oid, 'rx-'.$index, 'timos', $descr, $multiplier_ten, $conversor_uWatts_to_mWatts, $c
onversor_lognatural_to_log10_base, $limit_low, $warn_limit_low, $warn_limit, $limit, $current, 'snm
p', $entPhysicalIndex, $entPhysicalIndex_measured);
        }

                if (is_numeric($entry['tmnxDDMTxOutputPower'])) {
            $oid = '.1.3.6.1.4.1.6527.3.1.2.2.4.31.1.21.1.'.$index;
            $descr = dbFetchCell('SELECT `ifDescr` FROM `ports` WHERE `ifIndex`= ? AND `device_id` = ?', array($index, $device['device_id'])) . ' R
x Power';
            $limit_low = 10 * log10 (($entry['tmnxDDMTxOutputPowerLowWarning'])*0.0001);
            $warn_limit_low = 10 * log10 (($entry['tmnxDDMTxOutputPowerLowAlarm'])*0.0001);
            $limit =10 * log10 (($entry['tmnxDDMTxOutputPowerHiWarning'])*0.0001);
            $warn_limit = 10 * log10 (($entry['tmnxDDMTxOutputPowerHiAlarm'])*0.0001);
            $current = $entry['tmnxDDMTxOutputPower'];
            $entPhysicalIndex = $index;
            $entPhysicalIndex_measured = 'ports';
            discover_sensor($valid['sensor'], 'dbm', $device, $oid, 'tx-'.$index, 'timos', $descr, $multiplier, $divisor, $limit_low, $warn_limit_l
ow, $warn_limit, $limit, $current, 'snm
p', $entPhysicalIndex, $entPhysicalIndex_measured);
        }

    }

}
```

**Comment by laf** [comment]
Group would be timos as well btw.

Most likely the reason why it doesn't work is because the juniper code uses a pre-cache file: includes/discovery/sensors/pre-cache/junos.inc.php

You can use this to populate `$timos_oids`.

I've not checked the rest of the code.

**Comment by jgaitansmk** [comment]
Thank you for your answer, 
I created the file alcatel.inc.php within the pre-cache directory, but it does not work, I endorse the code file that you think, indeed mention that I have started to monitor a Juniper MX960 but does not show the optical levels.

Who else could do to plot the Alcatel optical levels, since this I would serve of base to remove optical levels for equipment Huawei ATN950 and CX600. Stay attentive to their comments, appreciate your help.

--

root@LibreNMS1:/opt/librenms/includes/discovery/sensors/pre-cache# more alcatel.inc.php
<?php
/*
 * LibreNMS
 *
 * Copyright (c) 2016 Neil Lathwood <neil@lathwood.co.uk>
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.  Please see LICENSE.txt at the top level of
 * the source code distribution for details.
 */

if ($device['os'] == 'Timos') {

    echo 'Pre-cache Timos: ';

    $timos_oids = array();
    echo 'Caching OIDs:';

    $junos_oids = snmpwalk_cache_multi_oid($device, 'tmnxDDMTxBiasCurrent', $oids, 'TIMETRA-PORT-MIB.mib', $config['mib_dir'].':'.$
config['mib_dir'].'/');

}

**Comment by laf** [comment]
timos is case sensitive, you need to use timos and not Timos.

**Comment by jgaitansmk** [comment]
I can not make it work... A suggestion :) , i create sensor in Pre-cache but no work.

**Comment by laf** [comment]
Paste your updated code on pastebin.com or similar

**Comment by jgaitansmk** [comment]
Ok, i added the links that i make to dbm Sensor to Alcatel Lucent, the other cuestion if should I use basic entity of Cisco to make this Sensor?

/opt/librenms/includes/discovery/sensors/dbm/alcatel.inc.php

http://pastebin.com/27x4Ph0b

--
Thanks in advance for your valuable assistance.

**Comment by dorkmatt** [comment]
@jgaitansmk is this work still progressing? I too would be interested in TiMOS optical support.

**Comment by jgaitansmk** [comment]
Hello @dorkmatt , how are you?, coment that I change of work and have no access to Alcatel equipment, so it no longer I could continue with this project, I leave the Link of paste bin if your can get better results.

http://pastebin.com/27x4Ph0b

Anything to your orders.

**Comment by laf** [comment]
We need the correct info to add support, we can't accept code not submitted properly after an agreement is signed.
