### ISSUE TITLE
AirOS 7 Devices not getting full information

### ISSUE THREAD

**Issue by quake101** [librenms/librenms#3987]
#### Please note

> Please read this information carefully.

[ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
Yes

[ ] Please include all of the information between the `====================================` section of `./validate.php`.
====================================
Version info:
[WARN]    Your install is out of date: 2d23867a70adb22524486116dd97f84305e3b2fd (Fri, 05 Aug 2016 23:57:36 +0000)
DB Schema: 126
PHP: 5.3.3
MySQL: 5.1.73
RRDTool: 1.3.8
SNMP: NET-SNMP version: 5.5

====================================

[ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)

[ ] Please provide as much detail as possible.
AirOS 7 Devices do not have any radio information (signal, quality, power, etc). AirOS 5.x devices list everything.

Here is a pastebin of a ./discovery.php -d on one of the AirOS 7 devices.
http://pastebin.com/zhaqSrRY

Pastebin of ./poller.php -h HOSTNAME -r -f -d -m os
http://pastebin.com/b5zMfkgu

Pastebin of snmpwalk
http://pastebin.com/guTKuAGy

The devices I'm trying to monitor are:
rocket 5ac prism
nanobeam 5ac 19

**Comment by laf** [comment]
The snmpwalk isn't in the correct format for us.

However I'm not sure it will give us what we need anyway. Can you get us the output of:

`./poller.php -h HOSTNAME -d -r -f -m wifi`

**Comment by quake101** [comment]
http://pastebin.com/c5gL3gQg

**Comment by laf** [comment]
Have you got the wifi polling module disabled? That output seems to show things working and trying to create the rrd files.

**Comment by quake101** [comment]
@laf I don't, I have a stock install that's monitoring a few other Ubiquiti products as well.

With that said, I see what you're saying and ended up rebooting the server and it's graphing the missing data now. No idea what caused it...

Thanks for all the help!
