### ISSUE TITLE
snmp-scan.php does not use net-exclude from config.php

### ISSUE THREAD

**Issue by jmoore2016** [librenms/librenms#4000]
When you invoke snmp-scan.php without arguments it uses the "nets" definitions from config.php. However, it does not use the "nets-exclude" definitions from config.php.

**Comment by f0o** [comment]
Correct

**Comment by jmoore2016** [comment]
> [14:19] <jmoore> I have the following in my config.php:
> [14:19] <jmoore> $config['nets-exclude'][] = '10.120.4.0/29'; $config['nets'][] = '10.120.4.0/24';
> [14:19] <jmoore> Should this prevent snmp-scan.php from scanning 10.120.4.1?

@f0o

**Comment by laf** [comment]
Yes it should.

**Comment by jmoore2016** [comment]
Ok, it is not ignoring the /29. Should any options be passed to snmp-scan.php?
