### ISSUE TITLE
addhost.php -f does not skip the icmp check

### ISSUE THREAD

**Issue by adamgent** [librenms/librenms#4001]
====================================
Version info:
Commit SHA: f1268848b06ef61ca55acbed5cc382b60b307efa
DB Schema: 118
PHP: 7.0.9
MySQL: 5.5.47-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2

====================================

When trying to add a device that is not yet available (e.g. for bulk-add), using the -f flag in addhost.php does not skip the ICMP host check as stated in the help text and adding the device fails.

-f forces the device to be added by skipping the icmp and snmp check against the host.

[root@nms0 librenms]# ./addhost.php -f testhost.example.com public
We couldn't add this device:
  Could not ping testhost.example.com

**Comment by adamgent** [comment]
Further update:

the above stated output is given when the host can be reached via ICMP, just not SNMP.

**Comment by murrant** [comment]
Thanks for the report!
