### ISSUE TITLE
Launch should open new tab/window

### ISSUE THREAD

**Issue by mzac** [librenms/librenms#4008]
When clicking the 'Launch' option from the gear when looking at a device, it would be better if the link was opened in a new tab/window.

Also, the 'launch' wording doesn't feel descriptive enough.  Maybe it should be HTTP/HTTPS?

**Comment by laf** [comment]
I think http/https is as ambiguous as Launch. Maybe 'Web'.

This is something you can submit as a PR if you feel it should be changed.
