### ISSUE TITLE
Deleting ASR9k device does not remove mempool usage information

### ISSUE THREAD

**Issue by jmoore2016** [librenms/librenms#4009]
Hello, when I delete an ASR9k device, the corresponding Memory information data is still left in the UI and orphaned.

If you go to Health --> Memory you see the original memory info from the various CPUs/cards on the ASR9k.

**Comment by laf** [comment]
mempools have a device_id column so there is no reason why this would occur. I've tested it on a device here and it works as expected.

I'm closing for now but if you find that you can repeat this please respond back and we will re-open.
