### ISSUE TITLE
Detecting Synology DS214play

### ISSUE THREAD

**Issue by SchneidersJelle** [librenms/librenms#4020]
I just started using LibreNMS. I added all my devices but my Synology DS214play isn't fully detected.

When I was using Observium I had the temperature charts of my HDD and CPU included, but it doesn't seem te be available in LibreNMS, am I missing something?

**Comment by Rosiak** [comment]
Hey @SchneidersJelle ,
Please read the GitHub issue pre-text before creating a issue without any information :)
With that being said, I don't belive we have code supporting that, yet. Could you please supply us with a paste of the following(Sensitive info filtered ofc):
```
snmpbulkwalk -On -v2c -c COMMUNITY HOSTNAME .
```

**Comment by SchneidersJelle** [comment]
Hi,
Sorry for not providing enough information.

Here the output of snmpbulkwalk:
[output.txt](https://github.com/librenms/librenms/files/411988/output.txt)
