### ISSUE TITLE
Potential community forum

### ISSUE THREAD

**Issue by laf** [librenms/librenms#4021]
Hi Folks,

Looking for some input in us utilising a community forum: https://community.librenms.org

Feel free to just drop a 👍  or 👎  against this or if you have comments to make please do so here.

**Comment by Rosiak** [comment]
👍

**Comment by florianbeer** [comment]
👍

**Comment by crcro** [comment]
👍

**Comment by lowinger42** [comment]
:thumbsup:

**Comment by f0o** [comment]
:+1:

**Comment by jgaitansmk** [comment]
🤘

2016-08-11 13:52 GMT-06:00 Daniel Preussker <notifications@github.com>:

**Comment by BradHooper** [comment]
:+1: Google Groups is too disjointed

**Comment by killengage** [comment]
👍

**Comment by vitalisator** [comment]
:+1:

**Comment by laf** [comment]
Live now.
