### ISSUE TITLE
IRC Bot can't auth when using LDAP

### ISSUE THREAD

**Issue by Sparc0** [librenms/librenms#4023]
I just installed Librenms and was trying out the IRC bot when i noticed i can't auth when i use LDAP authentication.

**Comment by laf** [comment]
Did you try the patch I posted last night?

https://www.irccloud.com/pastebin/KVZO4ZmH/

**Comment by Sparc0** [comment]
[Thu, 11 Aug 2016 00:02:43 +0200] Connected
[Thu, 11 Aug 2016 00:03:00 +0200] auth ( 'sparco' )
PHP Fatal error:  Uncaught Error: Call to undefined function get_userid() in /opt/librenms/irc.php:483
Stack trace:
#0 /opt/librenms/irc.php(325): ircbot->_auth(Array)
#1 /opt/librenms/irc.php(311): ircbot->proceedCommand('auth', 'sparco')
#2 /opt/librenms/irc.php(285): ircbot->handleCommand()
#3 /opt/librenms/irc.php(169): ircbot->getData()
#4 /opt/librenms/irc.php(121): ircbot->init()
#5 /opt/librenms/irc.php(735): ircbot->__construct()
#6 {main}
  thrown in /opt/librenms/irc.php on line 483

**Comment by laf** [comment]
Add:

`require_once $config['install_dir'].'/html/includes/authentication/'.$config['auth_mechanism'].'.inc.php';`

To irc.php underneath the last require_once around line 27.

**Comment by Sparc0** [comment]
it's not crashing anymore. But i still get Who are you again when i try to auth.

**Comment by f0o** [comment]
Can give it a shot at office, we use AD - that should be similar.

On 12 August 2016 21:13:24 CEST, Simon Skog <notifications@github.com> wrote:
>it's not crashing anymore. But i still get Who are you again when i try
>to auth.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/4023#issuecomment-239535349

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by laf** [comment]
Do you have `$config['auth_ldap_emailattr']` set as we expect to see the email address from ldap.

**Comment by Sparc0** [comment]
Yes i have it laf. No luck

**Comment by laf** [comment]
You could add:

`print_r($user);` just below `$user = get_user($user_id);`

**Comment by Sparc0** [comment]
[Sat, 20 Aug 2016 00:57:13 +0200] auth ( 'sparco' )
Array
(
    [username] => sparco
    [realname] => Anon
    [user_id] => 690000010
    [email] => 
)

Seems it cant get my mail from my ldap. I have to double check my ldap connection.
