### ISSUE TITLE
WAN interface does returns zero values for traffic throughput on Cisco 1900 router

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#4025]
Hi,

I have a Cisco 1900 series router which used to properly report traffic throughput on its WAN interfaces  before I upgraded to the later version of LibreNMS. However now it is reporting zero values on its two WAN interfaces however I am sure there it traffic going through these interfaces as that same traffic is aggregated on the LAN Gig interface has no issues.

The output of ./discovery.php -h HOSTNAME -d -m ports is shown here http://pastebin.com/Fmh5pbzG
The output of ./poller.php -h HOSTNAME -r -f -d -m ports is shown here http://pastebin.com/8Rv7N0Qm

![snap19](https://cloud.githubusercontent.com/assets/16717388/17565860/6140b316-5f39-11e6-8e83-df3d3553675d.png)

**Comment by Rosiak** [comment]
Could you just post a screenshot or something like that?

**Comment by laf** [comment]
If you check logs/daily.log - you can see what version you went from and to so we can see if anything was changed in between. I don't recall any port polling stuff changing though for at least a month.

**Comment by breeman1** [comment]
@laf the logs/daily.log is here; http://pastebin.com/9ZLnStX0 I do not see though which version I went from to which. All the other Cisco routers are reporting their links data correctly so I don't discount the issue being with this particular router.
@Rosiak here are the screenshots that may help;
![snap20](https://cloud.githubusercontent.com/assets/16717388/17582752/a2e60720-5fad-11e6-9933-a72e4b7745b5.png)
![snap21](https://cloud.githubusercontent.com/assets/16717388/17582852/2ba9c0c4-5fae-11e6-85b0-fad98510790f.png)
![snap22](https://cloud.githubusercontent.com/assets/16717388/17582794/bb356dca-5fad-11e6-8d7f-8c19faa1cb55.png)
![snap24](https://cloud.githubusercontent.com/assets/16717388/17582801/c44ea3ae-5fad-11e6-8591-aa54ef7a2918.png)

**Comment by murrant** [comment]
Can you run an snmpwalk against your device and pastebin that?
`snmpwalk -v2c -c COMMUNITY -On udp:HOSTNAME:161 .`

**Comment by breeman1** [comment]
Pastebin won't accept files larger 512Kb it seems so I have the output of the command in pdf and here it is.
[snmpwalk.pdf](https://github.com/librenms/librenms/files/413586/snmpwalk.pdf)

**Comment by murrant** [comment]
Why are the interface stats so far out of range?
```
ifHCInOctets.1 = 8879341932329
```
Not sure I understand what is going on here.  Cisco SNMP bug?

**Comment by laf** [comment]
What's your 'WAN' port here?

**Comment by breeman1** [comment]
It's port 4 and 5 labelled Serial0/0/0 and Serial0/0/1 respectively. Hope this is the information you are looking for.

**Comment by laf** [comment]
You say that this used to work but your screenshot seems to show that at least for a month it's not been working, when did it stop and can you show a screenshot indicating that?

**Comment by laf** [comment]
I think I can see what's up, can you please get me the output of:

`SELECT hardware FROM devices WHERE device_id=X;`

Replace X with the device id.

**Comment by breeman1** [comment]
![snap25](https://cloud.githubusercontent.com/assets/16717388/17649357/f22475be-6233-11e6-9eb4-3d06b2bb0fce.png)

**Comment by breeman1** [comment]
Hi @laf 

This is a new install of LibreNMS which is replacing the one we had before so all the devices have been re-added afresh. The old install where this was working has since been decommissioned from our production network fortunately since it was running as a VM machine which was archived, I was able to get the screens you need. See below;
![snap26](https://cloud.githubusercontent.com/assets/16717388/17649795/41eb490c-623d-11e6-8037-57238d492bb1.png)
![snap29](https://cloud.githubusercontent.com/assets/16717388/17649801/4bfc4a0e-623d-11e6-8558-cfdb47bcdd7e.png)
![snap28](https://cloud.githubusercontent.com/assets/16717388/17649803/57ab45a8-623d-11e6-820a-148c21915b16.png)
![snap27](https://cloud.githubusercontent.com/assets/16717388/17649807/6686c4a8-623d-11e6-9072-b15ae5bef70a.png)
![snap31](https://cloud.githubusercontent.com/assets/16717388/17649809/722b36ae-623d-11e6-801a-9f8fd922e17d.png)
