### ISSUE TITLE
Ceph application overview graphs don't work

### ISSUE THREAD

**Issue by murrant** [librenms/librenms#4046]
#### Please note

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

It looks like this has been broken for a long time.  The graphs look for `$vars['osd']` and `$vars['pool']` which are not set for the apps overview page.

@tuxis-ie

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by murrant** [comment]
Reported for another user.  I have no info.

**Comment by thanegill** [comment]
I can conform that I do have this issue. No graphs are being displayed.

![screen shot 2018-01-02 at 2 35 50 pm](https://user-images.githubusercontent.com/1141680/34502834-423fcc90-efca-11e7-97d4-76023cdc5864.png)
