### ISSUE TITLE
Add process-list from unix-agent

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#405]
Hi,

currently a bunch of useful information returned by Check_MK is going to waste.

The current codebase even has a process-list parser that even runs through the unix-agent's output but it's data is just discarded.

I'm working on a very simple addition to allow storage of the current processes with PID, VSZ, RSS, PCPU, User, Command.

PR should be inbound in some hours ;)

**Comment by wzhsunn** [comment]
how to monitor a process ?

**Comment by f0o** [comment]
Do you mean get the processlist or alerting upon it?
If 1st: simply update your check_mk with the newly shipped one from librenms repo (or upstream innovation branch from mathias kettner), install xinetd and config it if not done yet, poll and done :)

If 2nd: This is a tricky one! It is possible now, but you will have to invert your interpretation of the alert. So Alert becomes recovery and vice versa. I'm going to PR an update to the alerting in a bit to include rule-names in templates, inverted alerts and other minor changes. PR interval for alerting is a bit slow because it requires a lot of testing as people may rely on it.

**Comment by wzhsunn** [comment]
Thank you very much for your reply and my English is poor .
I think my mean is * 2nd *. 
I want to monitor a single process e.g. apache or iis or mysql etc.

**Comment by f0o** [comment]
That is possible but it will send you 'Recovery' email if you check for existing alert.

If you want to check process+memory then it will be fine.
Use alert-rules to add the alert, the table is called processes.

Example for memory check would be:
`processes.command ~ 'mysqld' && processes.vzs > 524288`
This alerts if mysqld uses more than 512MByte virtual memory.

**Comment by wzhsunn** [comment]
OK, I will have a try. Thank you very much ! :) .

**Comment by f0o** [comment]
Closing this issue because it's been merged in #410 - Feel free to comment on questions or simply join IRC
