### ISSUE TITLE
Detect Ubuntu?

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#4050]
Sorry for the (potentially?) dumb question, but to this item ... https://github.com/librenms/librenms/pull/4018

Is Ubuntu somehow detected (or supposed to be)? I have a machine that shows as,
Linux XXXXXXXX 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64

But the OS is detected as,
Linux 4.4.0-28-generic

Thanks!

**Comment by crcro** [comment]
actually that PR was only for the device os icon
to detect the os type you should include the snmp extended script named distro from librenms-agent

**Comment by arrmo** [comment]
Gotcha - thanks!

Yep, added it, and now the OS is detected ... reports as Linux 4.4.0-31-generic (Ubuntu 16.04). Icon is still the generic Linux icon though ... should it be? Likely just me ... :(.

Thanks again.

**Comment by laf** [comment]
Try forcing a browser refresh.

**Comment by arrmo** [comment]
Yep, that (mostly ... ;)) worked. Thanks! I had to close the browser, and re-open, but it took care of one (of two) machines.

And that's the interesting thing. This worked, so I thought ... "great, let me do this to a second machine also". But very odd, the second machine didn't work. Looking at the Recent Events for the two machines though, I see the following,

1) This machine worked great ...
2016-08-13 00:33:21	Device Icon changed linux => ubuntu	
2016-08-12 21:15:03	OS Features -> Ubuntu 16.04

2) And this one, not so much ... :),
2016-08-13 06:48:46	OS Features -> Ubuntu 16.04

On the second one ... no Icon changed line. 

Bit of thinking / debugging - was able to get it to work => need to re-run discovery. No issue, but capturing it here for others, in case they see this same thing. All is good now ... :+1: 

Thanks!
