### ISSUE TITLE
Error Drawing Graphs

### ISSUE THREAD

**Issue by beschen** [librenms/librenms#4051]
Was able to add a device, Cisco 6500 via SNMPv3 and all of the values appear to be showing up and I can even do the live view graphing. What isn't working is all of the other graphs. 

[root@librenms librenms]# php validate.php
====================================
Version info:
Commit SHA: 503260f8a494de5ed57f2be48bb97c69f81e7cc9
DB Schema: 118
PHP: 5.3.3
MySQL: 5.1.73
RRDTool: 1.3.8
SNMP: NET-SNMP version: 5.5

====================================
[OK]      Database connection successful

These are the two errors that I am seeing. Please let me know what other information is needed for troubleshooting.

ERROR: String ends after the = sign on 'CDEF:inB='
ERROR: opening '/opt/librenms/rrd/r-mdf-2/netstats-icmp.rrd': No such file or directory

http://pastebin.com/1fucgMUx

**Comment by laf** [comment]
Please provide the output of ./validate.php - post as pastebin links, please don't post output directly into issues, it's extremely difficult to read.

**Comment by beschen** [comment]
Here is the most recent ./validate.php

http://pastebin.com/WcFDt2Ng

**Comment by laf** [comment]
Please update your install.

Also update rrdtool to 1.4.3 or later.

**Comment by beschen** [comment]
Updating rrdtool fixed my problem. Thank you

**Comment by praburaj1985** [comment]
==========================================================
Component | Version
--------- | -------
LibreNMS  | 508c27345089d2c1e8e6291d067798854a23b241
DB Schema | 151
PHP       | 5.5.9-1ubuntu4.20
MySQL     | 5.5.53-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful

But am not get the graph
