### ISSUE TITLE
SNMP Extension

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#4053]
My apologies - this is not really an issue, rather a question, but not sure how else to ask it. Not a high priority by any means!

I got OS detection working, adding the needed script and SNMP Extension on the client machines, but trying to understand ... is there a list anywhere of the extensions (i.e. to avoid overlap of SNMP information / OIDs)? I searched the documentation, but can't find anything (likely missed it though, sorry).

Thanks!!!

**Comment by crcro** [comment]
there are a very few snmp extend script right now.
the oid used is actually generated by translating the word used in snmp extend line (like distro, nfs-stats, osupdate), so if there is no duplicate word you should be fine.

if the list of snmp extend plugins grows then maybe a list would help

**Comment by arrmo** [comment]
Sounds reasonable to me - thanks!

I admit, digging a bit, as I want to also provide information back from Tomato and ASUS-Merlin (custom firmware for my router(s)). Having a bit of "fun" figuring out the syntax of this command ... but starting to see that even Ubuntu is not providing it back through NET-SNMP-EXTEND-MIB, rather only UCD-SNMP-MIB (I think). Seems that NET-SNMP-EXTEND-MIB uses the name (e.g. distro), whereas UCD-SNMP-MIB uses the OID - but again, I may be wrong.

Thanks for the pointers!

**Comment by arrmo** [comment]
Happily have some updates working here (Tomato and ASUSWRT-Merlin firmware) - will submit the icons later today (pull request).

Thanks for all the help! Closing this now, to clean up.
