### ISSUE TITLE
RRDTool 1.3.8 does not create RRD's in CentOS < 7

### ISSUE THREAD

**Issue by vladsol** [librenms/librenms#4054]
Version info:
Commit SHA: 503260f8a494de5ed57f2be48bb97c69f81e7cc9
DB Schema: 126
PHP: 5.3.3
MySQL: 5.1.73
RRDTool: 1.3.8
SNMP: NET-SNMP version: 5.5

OS is CentOS 6.8

Freshly installed LibreNMS.
I have added some devices but after discovery and polling, all sub-dirs in "rrd" folder are empty =(
The problem is "-O" option, added to rrdtool command. In RRDtool 1.4.3 there is no such option.

**Comment by laf** [comment]
You will need to upgrade to a later version of rrdtool.

**Comment by vladsol** [comment]
I understand that ve

**Comment by vladsol** [comment]
For CentOS 6.x there is no repos with rrdtool > 1.3.8, as i see.
So all users need to build rrdtool from source.

**Comment by vladsol** [comment]
For CentOS 6.x there is no repos with rrdtool > 1.3.8, as i see.
So all users need to build rrdtool from source. 
It's not very convenient, IMHO :)
I propose #4067
