### ISSUE TITLE
require paths :: use absolute paths relative to install_dir instead of relative paths 

### ISSUE THREAD

**Issue by adriansev** [librenms/librenms#4055]
Hi! It would seem that all require directives have relative paths. 
I would like to argue that this is wrong as it restricts the locations of html directory.
(not everyone will make a unique server for librenms)
I think that it would be beneficial to everyone if all require paths would be relative to install_dir
Thank you for taking this into consideration.
Adrian

**Comment by laf** [comment]
Can you explain and show what you are trying to achieve.

We already support running in sub directories and alternative locations.

**Comment by adriansev** [comment]
Hi! i have lots of errors similar to :   
[Sun Aug 14 12:20:16 2016] [error] [client 128.141.144.220] File does not exist: /var/www/html/js, referer: http://monitor.spacescience.ro/librenms/   
also for css and images directories 
the main (git clone) librenms is put in a custom directory and the html dir is symlinked to /var/www/html/librenms  ; this is centos 6
As far i can tell the problem with those errors and many other to come is that instal_dir variable is not
used as a reference path for finding the needed data ...
Did i get something wrong?
Thank you for help!!
Adrian

**Comment by laf** [comment]
Post your config.php setup but this just strikes me as running in a sub dir - check our docs we have an example on how to set it up.

**Comment by adriansev** [comment]
Hi! I am aware of http://docs.librenms.org/Extensions/Sub-Directory/ but still i still have errors like : 
[Sun Aug 14 23:26:17 2016] [error] [client 93.158.41.64] File does not exist: /var/www/html/js, referer: http://monitor.spacescience.ro/librenms/
[Sun Aug 14 23:26:17 2016] [error] [client 93.158.41.64] File does not exist: /var/www/html/images/librenms_logo_light.png, referer: http://monitor.spacescience.ro/librenms/

my config is this : 
$config['db_host'] = 'localhost';
$config['db_user'] = ...........
$config['db_pass'] = .................
$config['db_name'] = 'librenms';
$config['db']['extension'] = 'mysqli';// mysql or mysqli

$config['memcached']['enable']  = FALSE;
$config['memcached']['host']    = 'localhost';
$config['memcached']['port']    = 11211;

$config['user'] = 'librenms';

$config['install_dir']  = "/export/librenms";

$config['snmp']['community'] = array("iss-ro");

$config['auth_mechanism'] = "mysql"; # default, other options: ldap, http-auth
#$config['http_auth_guest'] = "guest"; # remember to configure this user if you use http-auth

$config['nets'][] = "172.20.0.0/24";
$config['poller-wrapper']['alerter'] = FALSE;
$config['update'] = 0;
$config['rrd_purge'] = 0;
$config['fping'] = "/usr/sbin/fping";

Thank you for help!
Adrian

**Comment by laf** [comment]
Try:

`$config['base_url'] = 'http://monitor.spacescience.ro/librenms/';`

**Comment by adriansev** [comment]
Thanks a lot!! this did the trick .. now i have to see why i cannot authenticate ...
i did 
./adduser.php adrian tmppass 10 adrian.sevcenco@spacescience.ro
but it fails to authenticate .. and the logs directory from install_dir is empty .. any idea about this and where to look for problems?
also, when i try to discover a subnet i get this : 
-bash-4.1$ ./snmp-scan.php r 172.20.0.0/24
Range: 172.20.0.0/24
................PHP Fatal error:  Uncaught InvalidPortAssocModeException: Invalid port association_mode 'ifIndex'. Valid modes are:  in /export/librenms/includes/functions.php:278
Stack trace:
#0 /export/librenms/snmp-scan.php(71): addHost('172.20.0.17', '', 161, 'udp', 0)
#1 /export/librenms/snmp-scan.php(143): perform_snmp_scan(Object(Net_IPv4))
#2 {main}
  thrown in /export/librenms/includes/functions.php on line 278

what port association should i use? in this subnet there are switches,ipmi and raid cards ..
Thank you!!
Adrian

**Comment by laf** [comment]
Run as root user `./validate.php`

**Comment by adriansev** [comment]
[root@monitor librenms]# ./validate.php 
====================================
Version info:
[WARN]    Your install is out of date: 503260f8a494de5ed57f2be48bb97c69f81e7cc9 (Fri, 12 Aug 2016 21:02:56 +0000)
[WARN]    Your local git contains modified files, this could prevent automatic updates.
Modified files:
    html/.htaccess
DB Schema: 
PHP: 7.1.0beta2
MySQL: 5.5.51
RRDTool: 1.5.5
SNMP: NET-SNMP version: 5.5

====================================
[OK]      Database connection successful

**Comment by murrant** [comment]
Hmm, I wonder, if your database got built correctly? What does this return?
```sql
SELECT * FROM `port_association_mode`
```

**Comment by murrant** [comment]
Still having issues?

**Comment by laf** [comment]
Feel free to respond when you have more info.
