### ISSUE TITLE
McAfee SIEM Nitro - OS support

### ISSUE THREAD

**Issue by adaniels21487** [librenms/librenms#4059]
Hi Team,
I am adding OS support for McAfee SIEM Nitro applicnces.
The nitro suite contains a component called the Application Correlation Engine or ACE. This is reported as ACE in the sysDescr,

There is some legacy code that claims that every device with `ACE` in the sysDescr is a Cisco ACE.

```
./includes/discovery/os/acsw.inc.php
    if (strstr($sysDescr, 'ACE')) {
        $os = 'acsw';
    }
```

I plan to remove this ``if`` shortly.
If someone has a device that relies on this particular `if`, please let me know. We will need to be a little more specific.

Aaron

**Comment by laf** [comment]
No way to just use sysObjectID?

**Comment by adaniels21487** [comment]
The new PR uses the sysObjectID and ```./includes/discovery/os/acsw.inc.php``` also uses sysObjectID but for some reason Adam had this ```if``` in there as well.
