### ISSUE TITLE
LLDP links associating port based on lldpRemChassisID instead of lldpRemPortID

### ISSUE THREAD

**Issue by ekoyle** [librenms/librenms#4069]
After a message on the mailing list and also noticing bad port associations in my installation, I noticed that in discovery-protocols.inc.php, we are using the wrong LLDP variable for port association.  I'll submit a patch after some testing.

**Comment by mkruyswijk** [comment]
I am still seeing this issue on our installation, is this incorperated in the "mainstream" installation now? we do have automatic update on.

**Comment by murrant** [comment]
What version does `./validate.php` say you are on?

**Comment by mkruyswijk** [comment]
./validate.php 
====================================
Version info:
Commit SHA: 111d967e7da0b6b33f24c1d5439c9ea146ccce4b

**Comment by ekoyle** [comment]
@mkruyswijk: can you run `./discovery.php -d -m discovery-protocols -h <hostname>` for the host that is giving you the unexpected data?

**Comment by mkruyswijk** [comment]
Hi Eldon,
 
I can, is there any way of sharing that info, with a little bit of discretion?
 
Kind regards,
maarten

**Comment by ekoyle** [comment]
@mkruyswijk: You can email it to me directly if that works.  Same username at gmail.  Otherwise, I'm open to suggestions.

**Comment by ekoyle** [comment]
I looked over @mkruyswijk's data, and it appears that part of the problem is the names his devices are reporting cannot be correlated.  His Port ID's are not port MAC, port descr, etc. but rather `NAME DEVICETYPE Slot(NN) Port(NN)`.

I think to support this properly, we would need to start storing lldpLocPort* data somewhere to search on (which would be more proper than the current approach).

@mkruyswijk: as a workaround, are your able to change the LLDP Port ID on the remote device to something that will match the SNMP ifName or ifDescr the device is reporting?  (If you can find the remote port in the web UI, you can see the ifName/ifDescr there, or to be sure you can get the id from the URL, then look at the row in the db: `select ifName, ifDescr from ports where port_id = <id>`)

**Comment by laf** [comment]
No further info provided
