### ISSUE TITLE
looking for the "OS Updates" script

### ISSUE THREAD

**Issue by DennisSc** [librenms/librenms#4078]
Hello,

I am trying to set up "Applications" monitoring, specifically OS updates on a few linux hosts.
The manual says:

> "OS Updates
> A small shell script that checks your system package manager for any available updates (supports yum/apt-get/zypper package managers).
> 
> Extend SNMP
> 
> Copy the shell script to the desired host (the host must be added to LibreNMS devices)"

But I have searched around and for the life of it cannot find the mentioned script.
Does anyone have an idea where to look for it?

regards

**Comment by crcro** [comment]
Hi,

it is in the librenms-agent repo under the snmp directory.

Regards,

**Comment by DennisSc** [comment]
OK found it, and OS updates monitoring is running now. :+1:  
Thanks a lot.
