### ISSUE TITLE
Storage and Memory % empty

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#408]
Hi,

I'm monitoring mostly servers (debian, gentoo, centos, ...) and on the overview of each device I have missing % on Memory (Phys, Virt, Swap) and on Storage (all mount points). CPU shows up fine.

Just to clear it, I dont mean the graphs, those are good - I mean the small bar next to the graphs on the device's overview page.

Am I the only one?

**Comment by paulgear** [comment]
I haven't seen this - got a screenshot?

**Comment by f0o** [comment]
https://i.imgur.com/wHYByxF.png

**Comment by f0o** [comment]
Update:

It works on my gentoo's but not on my CentOS or Debians... odd...

**Comment by laf** [comment]
I looked at this the other day in your screenshot and couldn't figure out what you meant - now I get it.

Works for me on CentOS! I'll try and look at the code to see if it's possible to be different per OS.

**Comment by f0o** [comment]
My CentOS is a 7.0.1406 and my debians are upstream wheezy.. if it matters..

**Comment by f0o** [comment]
Turns out it's one of those mis-implemented memcache usage.
I will rewrite the way librenms uses memcache when I got time+motivation. A hot-fix here would be to simply remove the memcache code.. meh..

**Comment by praburaj1985** [comment]
please help me out am not able to view the health of the localhost
