### ISSUE TITLE
HP Procurve/Aruba cannot be discovered

### ISSUE THREAD

**Issue by anden4380** [librenms/librenms#4089]
Can not discover HP ProCurve / Aruba switches more after update to firmware 16.02

**Comment by Rosiak** [comment]
Please paste the sysDescr

**Comment by anden4380** [comment]
iso.3.6.1.2.1.1.1.0 = STRING: "HP J9773A 2530-24G-PoEP Switch, revision YA.16.02.0008, ROM YA.15.19 (/ws/swbuildm/spokane_qt_qaoff/code/build/lakes(swbuildm_spokane_qt_qaoff_spokane_qt))"

**Comment by crcro** [comment]
please provide output of following commands as pastebin links:

snmpbulkwalk -On -v2c -c COMMUNITY HOSTNAME .

**Comment by anden4380** [comment]
Pastebin will not take it so i have upload it to my webserver
[http://ongo-bongo.dk/HP.txt](
http://ongo-bongo.dk/HP.txt)

**Comment by crcro** [comment]
@anden4380 ... the PR was merged ... can you please give it a try and some feedback (i don't have this device to test on it)

**Comment by anden4380** [comment]
Sorry it is not wokring still the same "Generic Device"

**Comment by crcro** [comment]
@anden4380 ... please provide ./validate.php output 
also if it is possibile to give snmp access to the device?

**Comment by Rosiak** [comment]
I'll take it with @anden4380 .

**Comment by Rosiak** [comment]
@anden4380 Confrims that it works, closing.
