### ISSUE TITLE
Error drawing graph

### ISSUE THREAD

**Issue by xtyjan** [librenms/librenms#4093]
Hello

I have a device that I for some reason deleted from librenms and then re-added with the same name. The problem is now it won't graph any interfaces. Graphs like memory and CPU works fine

All other devices works, and even new ones. So I don't think there is a problem with the installation

Here is the RRD output from the graph "total traffic"
http://imgur.com/a/pVApB

bash-4.1$ ./validate.php
[OK]      config.php tested ok
[OK]      Database connection successful
[OK]      fping has been found

I have run ./daily.sh

Regards

**Comment by laf** [comment]
That's not the entire output of validate typically, do you not have anything like mysql connection?

**Comment by xtyjan** [comment]
I have tried as root and user account librenms and the output is still the same

[root@#### ~]# cd /opt/librenms/
[root@#### librenms]# ./validate.php
[OK]      config.php tested ok
[OK]      Database connection successful
[OK]      fping has been found
[root@#### librenms]# su librenms
bash-4.1$ ./validate.php
[OK]      config.php tested ok
[OK]      Database connection successful
[OK]      fping has been found

**Comment by laf** [comment]
Your install is extremely old. Please update.

**Comment by Rosiak** [comment]
Any news?

**Comment by laf** [comment]
Feel free to comment on this when you have updated
