### ISSUE TITLE
powerdns-recursor over agent is broken

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#4094]
there no rrd is generated if unix plugin is used.

**Comment by vitalisator** [comment]
fix one bug in #4095 but there is more wrong

./poller.php -h kx-dns-01.cmn.local -m unix-agent,applications -d
...
 powerdns-recursorArray
(
    [all-outqueries] => 2067538
    [answers-slow] => 38876
    [answers0-1] => 485508
    [answers1-10] => 79616
    [answers10-100] => 821927
    [answers100-1000] => 323173
    [cache-entries] => 168616
    [cache-hits] => 485018
    [cache-misses] => 1264082
    [case-mismatches] => 0
    [chain-resends] => 51185
    [client-parse-errors] => 0
    [concurrent-queries] => 0
    [dlg-only-drops] => 0
    [dont-outqueries] => 3
    [edns-ping-matches] => 0
    [edns-ping-mismatches] => 0
    [failed-host-entries] => 1083
    [ipv6-outqueries] => 0
    [ipv6-questions] => 0
    [malloc-bytes] => 0
    [max-mthread-stack] => 52584
    [negcache-entries] => 22412
    [no-packet-error] => 1134
    [noedns-outqueries] => 2068124
    [noerror-answers] => 1735988
    [noping-outqueries] => 0
    [nsset-invalidations] => 955
    [nsspeeds-entries] => 3206
    [nxdomain-answers] => 631425
    [outgoing-timeouts] => 67219
    [over-capacity-drops] => 0
    [packetcache-entries] => 171586
    [packetcache-hits] => 631022
    [packetcache-misses] => 1749052
    [policy-drops] => 0
    [qa-latency] => 99886
    [questions] => 2380122
    [resource-limits] => 0
    [server-parse-errors] => 0
    [servfail-answers] => 12709
    [spoof-prevents] => 0
    [sys-msec] => 312848
    [tcp-client-overflow] => 0
    [tcp-clients] => 0
    [tcp-outqueries] => 590
    [tcp-questions] => 48
    [throttle-entries] => 15
    [throttled-out] => 11844
    [throttled-outqueries] => 11844
    [unauthorized-tcp] => 0
    [unauthorized-udp] => 0
    [unexpected-packets] => 0
    [unreachables] => 525
    [uptime] => 1332927
    [user-msec] => 865556
)
RRD[create /opt/librenms/rrd/kx-dns-01.cmn.local/app-powerdns-recursor-21.rrd --step 300 DS:all-outqueries:DERIVE:600:0:U DS:answers-slow:DERIVE:600:0:U DS:answers0-1:DERIVE:600:0:U DS:answers1-10:DERIVE:600:0:U DS:answers10-100:DERIVE:600:0:U DS:answers100-1000:DERIVE:600:0:U DS:cache-entries:GAUGE:600:0:U DS:cache-hits:DERIVE:600:0:U DS:cache-misses:DERIVE:600:0:U DS:case-mismatches:DERIVE:600:0:U DS:chain-resends:DERIVE:600:0:U DS:client-parse-errors:DERIVE:600:0:U DS:concurrent-queries:GAUGE:600:0:U DS:dlg-only-drops:DERIVE:600:0:U DS:dont-outqueries:DERIVE:600:0:U DS:edns-ping-matches:DERIVE:600:0:U DS:edns-ping-mismatches:DERIVE:600:0:U DS:failed-host-entries:GAUGE:600:0:U DS:ipv6-outqueries:DERIVE:600:0:U DS:ipv6-questions:DERIVE:600:0:U DS:malloc-bytes:GAUGE:600:0:U DS:max-mthread-stack:GAUGE:600:0:U DS:negcache-entries:GAUGE:600:0:U DS:no-packet-error:DERIVE:600:0:U DS:noedns-outqueries:DERIVE:600:0:U DS:noerror-answers:DERIVE:600:0:U DS:noping-outqueries:DERIVE:600:0:U DS:nsset-invalidations:DERIVE:600:0:U DS:nsspeeds-entries:GAUGE:600:0:U DS:nxdomain-answers:DERIVE:600:0:U DS:outgoing-timeouts:DERIVE:600:0:U DS:over-capacity-drops:DERIVE:600:0:U DS:packetcache-entries:GAUGE:600:0:U DS:packetcache-hits:DERIVE:600:0:U DS:packetcache-misses:DERIVE:600:0:U DS:policy-drops:DERIVE:600:0:U DS:qa-latency:GAUGE:600:0:U DS:questions:DERIVE:600:0:U DS:resource-limits:DERIVE:600:0:U DS:security-status:GAUGE:600:0:U DS:server-parse-errors:DERIVE:600:0:U DS:servfail-answers:DERIVE:600:0:U DS:spoof-prevents:DERIVE:600:0:U DS:sys-msec:DERIVE:600:0:U DS:tcp-client-overflow:DERIVE:600:0:U DS:tcp-clients:GAUGE:600:0:U DS:tcp-outqueries:DERIVE:600:0:U DS:tcp-questions:DERIVE:600:0:U DS:throttle-entries:GAUGE:600:0:U DS:throttled-out:DERIVE:600:0:U DS:throttled-outquerie:DERIVE:600:0:U DS:too-old-drops:DERIVE:600:0:U DS:unauthorized-tcp:DERIVE:600:0:U DS:unauthorized-udp:DERIVE:600:0:U DS:unexpected-packets:DERIVE:600:0:U DS:unreachables:DERIVE:600:0:U DS:uptime:DERIVE:600:0:U DS:user-msec:DERIVE:600:0:U RRA:AVERAGE:0.5:1:2016 RRA:AVERAGE:0.5:6:1440 RRA:AVERAGE:0.5:24:1440 RRA:AVERAGE:0.5:288:1440  RRA:MIN:0.5:1:720 RRA:MIN:0.5:6:1440     RRA:MIN:0.5:24:775     RRA:MIN:0.5:288:797  RRA:MAX:0.5:1:720 RRA:MAX:0.5:6:1440     RRA:MAX:0.5:24:775     RRA:MAX:0.5:288:797  RRA:LAST:0.5:1:1440  -O] 
RRDtool Output: OK u:0.00 s:0.00 r:0.86
RRD[update /opt/librenms/rrd/kx-dns-01.cmn.local/app-powerdns-recursor-21.rrd N:2067538:38876:485508:79616:821927:323173:168616:485018:1264082:0:51185:0:0:0:3:0:0:1083:0:0:0:52584:22412:1134:2068124:1735988:0:955:3206:631425:67219:0:171586:631022:1749052:0:99886:2380122:0:U:0:12709:0:312848:0:0:590:48:15:11844:11844:U:0:0:0:525:1332927:865556] 
RRDtool Output: ERROR: Invalid DS name
...
@murrant, any idea what the cause for RRDtool error is?

**Comment by laf** [comment]
Is the rrd file created?

**Comment by murrant** [comment]
The dsname is too long.

**Comment by vitalisator** [comment]
@laf, no RRD is not created.
@murrant, from rrdcreate man page:
...
ds-name is the name you will use to reference this particular data source from an RRD. A ds-name must be 1 to 19 characters long in the characters [a-zA-Z0-9_].
...

so i understand that only underscore is allowed but not minus. and of course 19 characters max.
So I will try to change that and test...

**Comment by vitalisator** [comment]
#4103 should solve last problem
