### ISSUE TITLE
Linux Devices suddenly changed to Synology DSM

### ISSUE THREAD

**Issue by GordSpence** [librenms/librenms#4105]
> Please read this information carefully.

- [ ] Is your install up to date? Yes

- [ ] Please include all of the information between the ====================================
Version info:
[WARN]    Your install is out of date: 2ced4ced25ca3eab341a857a1dae20a1fd1d149a (Thu, 18 Aug 2016 14:36:23 +0000)
DB Schema: 127
PHP: 5.3.3
MySQL: 5.1.73
RRDTool: 1.3.8
SNMP: NET-SNMP version: 5.5

====================================

- [ ] Please provide as much detail as possible.

Logged in this morning to discover that all of our Linux servers are now being detected as 'Synology DMS' (CentOS and Ubuntu alike).

At Murrant's sugggestion in IRC, we tried switching strstr to strpos in linux.inc.php, then re-discovering the devices - no change, unfortunately, so we've reverted the tweak.

Auto-updating is enabled on the server for LibreNMS, and the change appears to have happened this morning based on the logs, and the "recent events" on the devices in the GUI.

librenms.log shows this, otherwise it's normal:

> /opt/librenms/discovery.php all 2016-08-18 06:48:37 - 71 devices discovered in 935.5 secs

I've attached a poller debug to see if we can make sense of it from there:
[poller-debug-clean.txt](https://github.com/librenms/librenms/files/425382/poller-debug-clean.txt)

I don't believe that we've made any changes to the system recently - haven't even added a new device for a week or two, let alone messing with any code.

Let me know if there's any more info you'd like me to pull to help troubleshoot this.

**Comment by f0o** [comment]
Marking #4044 as potential cause

**Comment by f0o** [comment]
Reverted in #4107 
Everything should be back to normal tomorrow
