### ISSUE TITLE
Pakedge Network Gear Support - Feature Request

### ISSUE THREAD

**Issue by tuksaur** [librenms/librenms#4108]
**Feature Request**

Is there a way we can get more information from Pakedge Networking equipment? currently memory and processor usage aren't available. Are there MIBs that can be manually installed to add this functionality? Pakedge claims that they don't have, nor provide, proprietary MIBs; previously inquired.

**Comment by crcro** [comment]
please provide output of following commands as pastebin links:

./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -r -f -d -m os
snmpbulkwalk -On -v2c -c COMMUNITY HOSTNAME .

**Comment by Rosiak** [comment]
No response, closing.
