### ISSUE TITLE
Make use of Check_MK

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#411]
Hi,

as seen in #405 and #207, I'd like to bring System-Data into LibreNMS.

We already got the ideal basis, Check_MK (AKA Unix-Agent)!
It uses a very modular core that allows the administrator to monitor literally anything s/he can write into a script.
A lot of data like Software-Raid status, Process-List (#405), ... is going to waste currently.

My Idea is to add a general table called 'check_mk' and store all non-RRD'able data from check_mk into it, so the GUI can visualize it on it's own.

A couple of use-cases (including before mentioned) could be:
- Software-Raid Status
- Process List
- Peripheral Status (USB, Serial, ... Devices)
- IP-Tables/Firewall Status
- Anything that one could imagine

Note that we can Alert on all these things as well. (i.e. missing process)

Any comments? suggestions? feedback? rants? cookies?

**Comment by laf** [comment]
No real comments on this myself although I think it's a good idea to do. I run it in my testing environment if you want me to help test in anyway.

**Comment by laf** [comment]
Things are moving on with this so no need to keep it open.
