### ISSUE TITLE
Allow selection of old availability map

### ISSUE THREAD

**Issue by paulgear** [librenms/librenms#4118]
Without trying to diminish the work done by @crcro on the latest availability map, I'd really like to have an option to use the old version.  They serve two different purposes, and the old one was much easier for me to see at a glance what was going on.  As @vitalisator pointed out in #4043, the boxes being scalable on the old version made it more suitable to larger networks.

**Comment by crcro** [comment]
@paulgear ... maybe something like a webui setting? to choose between simple (old view) and details (new view)?

**Comment by murrant** [comment]
I think this is only a problem with the widget right?  The full page is fine?

**Comment by crcro** [comment]
#paulgear ... what do you mean being scalable on old version? it's true the new ones are larger than the old ones but for me it was a pain to click the right one on high res monitors ... no margin, spacing, padding

**Comment by paulgear** [comment]
@murrant I didn't even realise there was a full page version. :-)
@crcro The no margin, no spacing was precisely what made it good for seeing a compact overview and fitting in a lot of hosts.  Changes in the red/green pattern were what it was designed to show.  I never really used it for clicking on individual hosts - the devices page or search box are better for that, IMO.

**Comment by crcro** [comment]
@paulgear ... the old view is back for you to choose :)

**Comment by crcro** [comment]
@paulgear you are ok with the old view now?

**Comment by paulgear** [comment]
Sorry for the late response - the option for the compact version is good enough for me.  I may submit a PR later to allow the size of the box to be changed like it used to be.

**Comment by vitalisator** [comment]
@paulgear, I resizing option for widget would be nice. :+1
