### ISSUE TITLE
RRDTool breakdown

### ISSUE THREAD

**Issue by absolutejam** [librenms/librenms#4124]
Hey guys,

I've recently discovered LibreNMS and I'm blown away with how awesome it is out of the box.

Since networking is an addition to what I primarily look after (servers don't tend to work without networking infrastructure) I've never really dealt that much with networking metrics. Is there anywhere I can find a good breakdown on what the built in metrics collections and graphs are showing, and possibly how to tweak/add to them to find what I want? I know there's quite a lot of working parts, like the poller but I'm not sure suite what it all means to me as a sysadmin, and once I get a better idea id like to make full use of the InfluxDB integration for Grafana and alerting.

Thanks for your time and work on this awesome project! Hopefully I'll be able to contribute back in the near future.

**Comment by murrant** [comment]
Unfortunately, the only way to look that info up is by looking at the code.

But you might want to just jump right into InfluxDB/Grafana and review what is there:
http://docs.librenms.org/Extensions/InfluxDB/

**Comment by laf** [comment]
Feel free to stop by on irc to ask any questions.
