### ISSUE TITLE
PHP session contains user login credentials

### ISSUE THREAD

**Issue by ekoyle** [librenms/librenms#4127]
mneth in IRC reported that ibrenms is storing passwords in the PHP session file.  I think this is an unnecessary security risk.

It looks like every page request will call reauthenticate() with a chained call to authenticate() if there is no cookie.  It looks like this is the only place where the password is used.  Should this be using a local variable instead of $_SESSION? It appears to be set around [html/includes/authenticate.php line 39-47](https://github.com/librenms/librenms/blob/bf2c522c899a41c726830d5bc63f95dc8f6e7a72/html/includes/authenticate.inc.php#L39) and then only used on line 64.
#### Please note

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by f0o** [comment]
Correct, one of the many relics we inherit.

This will not be present in v2 :)

Luckily the attack vector for this implies a breach into the filesystem of the nms's server. At which point one could easily drain a database dump and break the terribly outdated pw-lib we use.

I guess I'm the pessimist again.

Not saying we shouldn't fix this! Likely just an 'if' and drop the pwd storage ;)

On 19 August 2016 19:20:47 CEST, Eldon Koyle <notifications@github.com> wrote:
>mneth in IRC reported that ibrenms is storing passwords in the PHP
>session file.  I think this is an unnecessary security risk.
>
>It looks like every page request will call reauthenticate() with a
>chained call to authenticate() if there is no cookie.  It looks like
>this is the only place where the password is used.  Should this be
>using a local variable instead of $_SESSION? It appears to be set
>around [html/includes/authenticate.php line
>39-47](https://github.com/librenms/librenms/blob/bf2c522c899a41c726830d5bc63f95dc8f6e7a72/html/includes/authenticate.inc.php#L39)
>and then only used on line 64.
>
>#### Please note
>
>> Please read this information carefully.
>
>- [x] Is your install up to date? [Updating your
>install](http://docs.librenms.org/General/Updating/)
>- [ ] Please include all of the information between the
>`====================================` section of `./validate.php`.
>- [ ] If you would like us to add a new device then please provide the
>information asked for
>[here](http://docs.librenms.org/Support/FAQ/#faq20)
>- [x] Please provide as much detail as possible.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/4127

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ekoyle** [comment]
The if w/o pw storage didn't work, sadly.  Apparently the $_COOKIE['token'] is only used when you check the 'remember me' box; so it currently reauthenticates on every page hit.

My biggest concern is that this remembers our central (ie. not DB) creds, which is not cool.

**Comment by f0o** [comment]
Yeah I agree

Perhaps just having an uid present should be enough to reauthenticate from $_SESSION

**Comment by ekoyle** [comment]
It seems like it should be reasonable to just trust `$_SESSION['authenticated']` and only try the auth foo if it is unset/false, right?

**Comment by f0o** [comment]
Yeah

**Comment by ekoyle** [comment]
Hey, I saw this got reverted by #4422, @murrant or @laf: could one of you please re-open this one?

**Comment by murrant** [comment]
Yes, LDAP/AD reauthorization requiring a password needs to be solved before this can be done...

**Comment by ekoyle** [comment]
When you say reauthorization, are we calling authenticate() for authorization?

I would assume that once we got a valid session, we would not need to reauthenticate or reauthorize until the session expires.

**Comment by laf** [comment]
Unfortunately ldap / ad require you to pass username/password to be able to bind the connection before we can do queries, that means we still need those :(

**Comment by crcro** [comment]
maybe create a bind for ad/ldap in config.php that has nothing to do with the webui user?

**Comment by ekoyle** [comment]
A bind user is common practice, so I don't see a problem with that; however there are authentication methods that do not provide any kind of directory service (ie. SAML2, etc.).  Would it be better to cache a user's attributes it the users table on login and not require lookup services?  This would have the added benefit of not requiring LDAP/AD to be reachable by librenms to send out alerts.

Speaking of alerts... how on earth are we sending alerts to LDAP users?  There is no session to associate with, and email addresses aren't stored in the database; do email alerts not work for LDAP users?

**Comment by laf** [comment]
We're open to any suggestions.

I've got limited ability to test things like LDAP and AD as I don't run them :(

**Comment by jonathon-k** [comment]
Once a user has authenticated, what more do we need to query from the LDAP or AD server?

**Comment by murrant** [comment]
You need to query group membership.

**Comment by jonathon-k** [comment]
So... I am thinking something like https://github.com/librenms/librenms/compare/master...jonathon-k:issue/4127_AuthenticationUpdates  I would appreciate thoughts....

**Comment by ekoyle** [comment]
@laf or @murrant: could you reopen this again, since #4608 was reverted?

I wish github would automatically do that...

**Comment by ekoyle** [comment]
Does anyone have ideas on how to find volunteers to test changes to the authentication code?  I don't think there is an easy way to set up a test environment that could test against so many different auth modules.

For future reference, reverted by #5252.

**Comment by laf** [comment]
We can put a shout out on twitter, post on community + irc.

**Comment by murrant** [comment]
@ekoyle FYI, due to recent changes with the AD auth module (adding a bind user) and pulling user preferences out of the users table.  This should be viable to accomplish now.

Care to dust off the code and try again?

**Comment by ekoyle** [comment]
I keep meaning to look at this.  I think the problem was with the
two-factor auth.

**Comment by laf** [comment]
That's been updated again so we definitely should take another look.
