### ISSUE TITLE
Sonus Networks GSX & SBC MIBS

### ISSUE THREAD

**Issue by allano337** [librenms/librenms#4135]
#### Please note

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.
Manufactures site:
https://support.sonus.net/display/SBXDOC41/Retrieving+Sonus+Enterprise+MIB+OIDs

MIBS are below:
[gsx.zip](https://github.com/librenms/librenms/files/427934/gsx.zip)

[sbc.zip](https://github.com/librenms/librenms/files/427940/sbc.zip)

Will be glad to test.

Thanks

**Comment by crcro** [comment]
@allano337 please provide:

./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -r -f -d -m os
snmpbulkwalk -On -v2c -c COMMUNITY HOSTNAME .

**Comment by allano337** [comment]
Here is the information requested, please let me know if you need anything else.

[gsx snmp.zip](https://github.com/librenms/librenms/files/431244/gsx.snmp.zip)
[gsx results.txt](https://github.com/librenms/librenms/files/431245/gsx.results.txt)
[SBC results.txt](https://github.com/librenms/librenms/files/431246/SBC.results.txt)

**Comment by crcro** [comment]
@allano337 ... initial support code merged

**Comment by allano337** [comment]
crcro see your response and wondered what it means as I looked in /opt/librenms/mibs and don't see Sonus listed. thanks

**Comment by laf** [comment]
You don't always need mibs or will see the file name, update and see if the device is now detected correctly.

**Comment by allano337** [comment]
added one device, system says it's generic operating system and no Sonus icon 

Version	383c50b - Wed Aug 24 2016 00:12:20 GMT-0700

**Comment by allano337** [comment]
hmm, wonder why my system hasn't updated? I did use the command to pull out the patch last week

**Comment by Rosiak** [comment]
It's in the master now, please run daily.sh and check the output.

**Comment by allano337** [comment]
updating to latest codebase failed

**Comment by Rosiak** [comment]
@allano337 , looks into logs/daily.log.
Otherwise jump on IRC as it is much easier to help using synchronous communication.

**Comment by Rosiak** [comment]
Confirmed it works on IRC, closing.
