### ISSUE TITLE
Markdown for alert templates

### ISSUE THREAD

**Issue by benwa** [librenms/librenms#4144]
Markdown is tried and tested for easy writing. The markup is non-offensive, so it will look fine whether the alerts are set to HTML or not and to other services beside email.

If Liquid templating is also added, we'll have a richer set of features as well.  There is a PHP version of Liquid [here](https://github.com/kalimatas/php-liquid).

**Comment by Rosiak** [comment]
Hi,

We are cleaning up the issues here on GitHub, all feature requests will be moved to:
https://community.librenms.org/c/feature-requests

Hence the closure of this issue.
