### ISSUE TITLE
ntpd server app is not working properly

### ISSUE THREAD

**Issue by seitzbg** [librenms/librenms#4152]
#### Please note

> Please read this information carefully.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
Yes
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
Version info:
Commit SHA: f750db64fe34f9f22e5c00a8649642b0724d5f7e
DB Schema: 128
PHP: 5.6.24
MySQL: 10.1.16-MariaDB
RRDTool: 1.5.6
SNMP: NET-SNMP version: 5.7.3
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

I have added the ntpd server application per the documentation by extended SNMPD.  I see the data in the librenms debug output  but it is writing (literally) to a file called app.rrd and no graphs appear.

I have attached the debug output.
[ntp-gps1.fiber.house.debug.txt](https://github.com/librenms/librenms/files/428846/ntp-gps1.fiber.house.debug.txt)

**Comment by rbax82** [comment]
still not working for me
