### ISSUE TITLE
Availability Map blanks the screen on empty services selection

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#4154]
Hi,

First of all I would like to mention that the new availability-map is a cool feature, well done:). 
The issue I am experiencing though is that when I select services in its pull-down menu; in my case I do not have any service configured yet, then I just get blank white screen. Even the pull down dissappears meaning I cannot revert back. The only way to get back to the availability map for devices is to logout and login again. The issue affects the dashboard as well when it occurs. See below;

![snap35](https://cloud.githubusercontent.com/assets/16717388/17837649/8d5fa3f8-67b8-11e6-8eb8-c32fef6d32fc.png)

![snap34](https://cloud.githubusercontent.com/assets/16717388/17838193/0660a26c-67c7-11e6-8647-b9d0746764e2.png)

![snap36](https://cloud.githubusercontent.com/assets/16717388/17837655/b5b06ac2-67b8-11e6-955a-6128b2202921.png)

![snap37](https://cloud.githubusercontent.com/assets/16717388/17837659/c2cd84ce-67b8-11e6-8ef1-66e7baf4cba7.png)

**Comment by crcro** [comment]
do you have any services currently monitored? for the third image you have only devices

**Comment by breeman1** [comment]
@crcro 
As mentioned in my initial post, I do not have any services being monitored yet. I do not think this bar 
![snap39](https://cloud.githubusercontent.com/assets/16717388/17849826/dd755cd2-685a-11e6-9ab6-3ff3cb40111c.png)
should disappear even though the screen might be blank due to no services being monitored. In my case this means I have to logout and back in again to see it and the devices being monitored.
