### ISSUE TITLE
Enabled / Disabled switch graph glitch

### ISSUE THREAD

**Issue by Andreser** [librenms/librenms#4156]
The Enabled/Disabled switch button is displaying incorrectly in my LibreNMS setup since yesterday, I don't know if this has something to do with a recent update.
Attached are the Enabled and Disabled screenshots.
![Enabled]
(https://cloud.githubusercontent.com/assets/17357163/17838308/df257afe-67a0-11e6-9861-c038b512b179.png)
![Disabled]
(https://cloud.githubusercontent.com/assets/17357163/17838307/df22e6cc-67a0-11e6-9207-b4c919f46339.png)

**Comment by laf** [comment]
I don't see this on my install. Try demo.librenms.org and see if it happens there.

You'll also need to provide more info than this, browser version + the debug info we ask for when you create an issue.

**Comment by Andreser** [comment]
Yes, It also happens to me with the demo.librenms.org website.
It doesn't happen using firefox on the same computer neither in my site nor in the demo site.
Below further debugging info:

**Browser Version:**
Chromium 51.0.2704.79 Built on Ubuntu 16.04, running on LinuxMint 18

**PHP Debug**
Array ( [errno] => 8 [errstr] => Undefined index: enable [errfile] => /opt/librenms/includes/influxdb.inc.php [errline] => 15 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchrows_sec [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 276 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchrows [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 277 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchrow_sec [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 331 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchrow [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 332 )
Array ( [errno] => 8 [errstr] => Undefined index: update_sec [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 216 )
Array ( [errno] => 8 [errstr] => Undefined index: update [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 217 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchcell_sec [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 365 )
Array ( [errno] => 8 [errstr] => Undefined index: fetchcell [errfile] => /opt/librenms/includes/dbFacile.mysqli.php [errline] => 366 )
Array ( [errno] => 8 [errstr] => Undefined variable: param [errfile] => /opt/librenms/html/includes/print-menubar.php [errline] => 152 )
Array ( [errno] => 8 [errstr] => Undefined index: _ObjCacheSkell [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 47 )
Array ( [errno] => 8 [errstr] => Undefined index: _ObjCache [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 51 )
Array ( [errno] => 8 [errstr] => Undefined index: ports [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 60 )
Array ( [errno] => 8 [errstr] => Undefined index: params [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 98 )
Array ( [errno] => 8 [errstr] => Undefined index: params [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 98 )
Array ( [errno] => 8 [errstr] => Undefined index: menu [errfile] => /opt/librenms/html/includes/plugins.inc.php [errline] => 58 )
Array ( [errno] => 8 [errstr] => Undefined index: notifications [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 60 )
Array ( [errno] => 8 [errstr] => Undefined index: params [errfile] => /opt/librenms/includes/object-cache.inc.php [errline] => 98 )
Array ( [errno] => 8 [errstr] => Undefined index: page_number [errfile] => /opt/librenms/html/includes/print-alert-rules.php [errline] => 154 )
Array ( [errno] => 8 [errstr] => Undefined index: invert [errfile] => /opt/librenms/html/includes/print-alert-rules.php [errline] => 202 )
Array ( [errno] => 8 [errstr] => Undefined index: interval [errfile] => /opt/librenms/html/includes/print-alert-rules.php [errline] => 213 )
Array ( [errno] => 8 [errstr] => Undefined index: invert [errfile] => /opt/librenms/html/includes/print-alert-rules.php [errline] => 202 )
Array ( [errno] => 8 [errstr] => Undefined index: interval [errfile] => /opt/librenms/html/includes/print-alert-rules.php [errline] => 213 )
23 total PHP issues / errors.


**SQL Debug**
select config_name,config_value from config
select * from graph_types
SELECT * FROM `plugins` WHERE `plugin_active` = '1'
DELETE FROM `session` WHERE `session_expiry` < '1471818312'
SELECT * FROM `session` WHERE `session_username` = 'andy' AND session_value='75qa0m523g563q04lk2rh8gpu0'
SELECT `level` FROM `users` WHERE `username` = 'andy'
SELECT `user_id` FROM `users` WHERE `username` = 'andy'
UPDATE `session` set `session_value` ='75qa0m523g563q04lk2rh8gpu0',`session_expiry` ='1474410312' WHERE session_auth='OhoEjxxGnVF79OzA'
SELECT * FROM devices_perms WHERE user_id = '1'
SELECT * FROM ports_perms WHERE user_id = '1'
SELECT * FROM bill_perms WHERE user_id = '1'
SELECT service_status, count(service_status) as count FROM services GROUP BY service_status
SELECT COUNT(port_id) FROM `ports` WHERE `ifOperStatus` = 'down' AND `ifAdminStatus` = 'up' AND `ignore` = '0'
SELECT COUNT(*) FROM `links`
SELECT COUNT(bgpPeer_id) FROM bgpPeers AS B where (bgpPeerAdminStatus = 'start' OR bgpPeerAdminStatus = 'running') AND bgpPeerState != 'established'
SELECT * FROM device_groups ORDER BY name
SELECT 1 from `packages` LIMIT 1
SELECT `type`,COUNT(`type`) AS total_type FROM `devices` AS D WHERE 1 GROUP BY `type` ORDER BY `type`
SELECT D.device_id,location FROM devices AS D GROUP BY location ORDER BY location
SELECT COUNT(*) FROM ports AS I, devices AS D WHERE I.`deleted` = '0' AND D.`device_id` = I.`device_id` AND I.`ignore` = '0' AND D.`ignore` = '0' AND (I.`ifInErrors_delta` > '0' OR I.`ifOutErrors_delta` > '0')
SELECT COUNT(*) FROM ports AS I, devices AS D WHERE I.`deleted` = '0' AND D.`device_id` = I.`device_id` AND (I.`ignore` = '1' OR D.`ignore` = '1')
SELECT * FROM `ports` AS P, `devices` as D WHERE P.`deleted` = '1' AND D.device_id = P.device_id
SELECT sensor_class,COUNT(sensor_id) AS c FROM sensors GROUP BY sensor_class ORDER BY sensor_class
SELECT DISTINCT(`app_type`) AS `app_type` FROM `applications` ORDER BY `app_type`
SELECT DISTINCT(`app_instance`) FROM `applications` WHERE `app_type` = 'apache' ORDER BY `app_instance`
SELECT DISTINCT(`app_instance`) FROM `applications` WHERE `app_type` = 'bind' ORDER BY `app_instance`
SELECT DISTINCT(`app_instance`) FROM `applications` WHERE `app_type` = 'memcached' ORDER BY `app_instance`
SELECT DISTINCT(`app_instance`) FROM `applications` WHERE `app_type` = 'mysql' ORDER BY `app_instance`
SELECT COUNT(bgpPeer_id) from `bgpPeers` LEFT JOIN devices AS D ON bgpPeers.device_id=D.device_id WHERE D.device_id IS NOT NULL
SELECT COUNT(ospf_instance_id) FROM `ospf_instances` WHERE `ospfAdminStat` = 'enabled'
SELECT COUNT(cef_switching_id) from `cef_switching`
SELECT COUNT(vrf_id) from `vrfs`
SELECT `C`.`id`,`C`.`device_id`,`C`.`type`,`C`.`label`,`C`.`status`,`C`.`disabled`,`C`.`ignore`,`C`.`error`,`CP`.`attribute`,`CP`.`value` FROM `component` as `C` LEFT JOIN `component_prefs` as `CP` on `C`.`id`=`CP`.`component` WHERE ( `type` = 'Cisco-OTV' )
SELECT COUNT(*) from `plugins` WHERE plugin_active = '1'
select count(notifications.notifications_id) from notifications where not exists( select 1 from notifications_attribs where notifications.notifications_id = notifications_attribs.notifications_id and notifications_attribs.user_id = '1')
select count(notifications.notifications_id) from notifications inner join notifications_attribs on notifications.notifications_id = notifications_attribs.notifications_id where notifications_attribs.key = "sticky" && notifications_attribs.value = 1
SELECT COUNT(id) FROM alert_rules ORDER BY id ASC
SELECT * FROM alert_rules ORDER BY id ASC LIMIT 0,50
SELECT * FROM alerts WHERE rule_id = '1' ORDER BY `state` DESC, `id` DESC LIMIT 1
SELECT * FROM alerts WHERE rule_id = '2' ORDER BY `state` DESC, `id` DESC LIMIT 1
SELECT * FROM alerts WHERE rule_id = '3' ORDER BY `state` DESC, `id` DESC LIMIT 1
SELECT * FROM alerts WHERE rule_id = '4' ORDER BY `state` DESC, `id` DESC LIMIT 1
SELECT * FROM alerts WHERE rule_id = '5' ORDER BY `state` DESC, `id` DESC LIMIT 1
SELECT * FROM alerts WHERE rule_id = '6' ORDER BY `state` DESC, `id` DESC LIMIT 1
SELECT * FROM alerts WHERE rule_id = '7' ORDER BY `state` DESC, `id` DESC LIMIT 1
SELECT * FROM alerts WHERE rule_id = '8' ORDER BY `state` DESC, `id` DESC LIMIT 1
SELECT * FROM alerts WHERE rule_id = '9' ORDER BY `state` DESC, `id` DESC LIMIT 1
SELECT COUNT(`device_id`) FROM `devices` WHERE `last_polled` <= DATE_ADD(NOW(), INTERVAL - 15 minute) AND `ignore` = 0 AND `disabled` = 0 AND status = 1
48 total SQL queries run.

**Comment by laf** [comment]
I've tested:

Chromium: Version 54.0.2837.0 (64-bit)

Chrome: Version 52.0.2743.116 (64-bit)

both on mac os x.

I'd suggest updating Chromium.

**Comment by Andreser** [comment]
Installed last Google Chrome version on same OS and problem disappeared. Still happening with chromium.
I'm not having this issue on an Identical OS (Linux Mint 18 up to date) on another computer with chromium (same chromium version). I would say it's closed unless it happens again with another user...
