### ISSUE TITLE
Real Time Graphs broken

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#4161]
#### Please note

> Please read this information carefully.

- [ x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
- [ x ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ x ] Please provide as much detail as possible.

====================================
Version info:
Commit SHA: b1cfaa7ec08a262265ae671f9f7da2527dd91776
Passwort: 
[WARN]    Your local git contains modified files, this could prevent automatic updates.
Modified files:
    html/images/librenms_logo_light.png
DB Schema: 128
PHP: 5.6.19-0+deb8u1
MySQL: 5.5.47-0+deb8u1
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2.1

====================================

after updates in the last two days (do not know which commit is responsible) the real time graphs do not working anymore. In firefox 47.0 on linux I see that error:
 Your browser does not support the type SVG! You need to either use Firefox or download the Adobe SVG plugin. 
same result under Chromium Version 51.0.2704.79 Built on Ubuntu 14.04, running on LinuxMint 17.3 (64-bit)

**Comment by BradHooper** [comment]
I'm seeing the same thing using Chromium (Ubuntu 16.04) and using Dolphin on Android. Both worked previously.

**Comment by vitalisator** [comment]
@laf , have still the same issue.
@BradHooper , did #4162 solved your problem?

**Comment by BradHooper** [comment]
Yes it did @vitalisator 
Run ./daily.sh as librenms
