### ISSUE TITLE
SVG Plugin 

### ISSUE THREAD

**Issue by jguida** [librenms/librenms#4166]
![librenms](https://cloud.githubusercontent.com/assets/15660828/17867450/ef484854-6880-11e6-8779-3a1c2818938b.JPG)
Hi, I'm trying to watch a graphical interface in real time and gives me the following error:

"Your browser does not support the type SVG! You need to use Firefox Either or download the Adobe SVG plugin."

It's the same with all browsers, and until last week worked.

Thank you.

**Comment by laf** [comment]
Update, should be fine now.

**Comment by jguida** [comment]
Thanks.!!
