### ISSUE TITLE
Real time graphing failure

### ISSUE THREAD

**Issue by FocuSTech16** [librenms/librenms#4167]
Switch port real time graph indicates "Your browser does not support the type SVG! You need to either use Firefox or download the Adobe SVG plugin."  This has been observed on multiple browsers (Firefox, Chrome, IE, and Safari) and OS's (Windows and Mac).  We verified that LibreNMS is up to date.  I was able to recreate the issue on the demo site https://demo.librenms.org/device/device=41/tab=port/port=63496/view=realtime/.

**Comment by lowinger42** [comment]
Same problem here, checked the browser console, the backend responds with status code 500.

GET http://librenms/graph-realtime.php?type=bits&id=89&interval=2 500 (Internal Server Error)

Checking apache logfile for above error:

[Mon Aug 22 21:05:12.566328 2016] [:error] [pid 37393] [client 192.168.168.33:51475] PHP Fatal error:  Call to undefined method LibreNMS\\ClassLoader::mapClass() in /opt/librenms/html/graph-realtime.php on line 23, referer: http://librenms.int.abundo.se/device/device=9/tab=port/port=89/view=realtime/

**Comment by SaaldjorMike** [comment]
Closing this as it should already be fixed with PR #4162
