### ISSUE TITLE
Is there any topo map ?

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#417]
I found this https://github.com/laf/weathermap, but it is not as beautiful as librenms.
php weathermap is good and very usefull but its editor is ugly.

If I need a feature like this ,what should I do ?

**Comment by f0o** [comment]
I think we only have the weathermap currently... if you know an alternative, feel free to contribute it as a plugin :)

**Comment by wzhsunn** [comment]
OK, Thank you for your reply .
