### ISSUE TITLE
Defunct 'sh' processes under apache in recent builds

### ISSUE THREAD

**Issue by jkrauska** [librenms/librenms#4170]
#### Please note

Was using current release, but got lots of defunct sh processes.
Version	7b93b56 - Mon Aug 22 2016 15:59:59 GMT-0700

Walked back a few versions and this went away.

Does Not Occur:
27c1c72b19d53cd94d67c436a1a39917d1884a43
Date:   Mon Aug 22 11:46:22 2016 +0100

Does Occur:
e80a385b7f66aad6b959660f557cbfbca4bbf66e
Date:   Mon Aug 22 10:32:05 2016 -0500
(which does lots of rrdtool things -- and 'remove full path for remote commands')
Seems probable.

The dates are out of order, but git -p log puts 27c1 AFTER e80a.

Please advise or provide suggestions on how to further debug?

Cheers.

**Comment by murrant** [comment]
Can you show your process list with the defunct processes? `ps aux|grep defunct` for example

**Comment by jkrauska** [comment]
`root@librenms:/opt/librenms# git checkout e80a385
Previous HEAD position was 27c1c72... Fixed realtime graphs (#4162)
HEAD is now at e80a385... RRDtool dual process (remote creation/check) (#4104)
root@librenms:/opt/librenms# service apache2 restart
(load a page with graphs)

www-data 15473  1.0  0.5 345732 22552 ?        S    04:48   0:00  \_ /usr/sbin/apache2 -k start
www-data 15498  0.0  0.0      0     0 ?        Z    04:48   0:00  |   \_ [sh] <defunct>
www-data 15522  0.0  0.0      0     0 ?        Z    04:48   0:00  |   \_ [sh] <defunct>
www-data 15532  0.0  0.0      0     0 ?        Z    04:48   0:00  |   \_ [sh] <defunct>
www-data 15555  0.0  0.0      0     0 ?        Z    04:48   0:00  |   \_ [sh] <defunct>
www-data 15612  0.0  0.0      0     0 ?        Z    04:48   0:00  |   \_ [sh] <defunct>
www-data 15624  0.0  0.0      0     0 ?        Z    04:48   0:00  |   \_ [sh] <defunct>
www-data 15636  0.0  0.0      0     0 ?        Z    04:48   0:00  |   \_ [sh] <defunct>
www-data 15648  0.0  0.0      0     0 ?        Z    04:48   0:00  |   \_ [sh] <defunct>
www-data 15660  0.0  0.0      0     0 ?        Z    04:48   0:00  |   \_ [sh] <defunct>
www-data 15674  0.0  0.0      0     0 ?        Z    04:48   0:00  |   \_ [sh] <defunct>

root@librenms:/opt/librenms# ps auxf | grep  defunct | wc -l
72

root@librenms:/opt/librenms# git checkout 27c1c72
Previous HEAD position was e80a385... RRDtool dual process (remote creation/check) (#4104)
HEAD is now at 27c1c72... Fixed realtime graphs (#4162)
root@librenms:/opt/librenms# service apache2 restart

(load a page with graphs)
root@librenms:/opt/librenms# ps auxf | grep  defunct | wc -l
0

`

**Comment by adammmmm** [comment]
Seems to occur with nginx too, 8650 defunct (sh) processes here.

**Comment by laf** [comment]
Can you post your distro version, php versions and web server versions please?

**Comment by adammmmm** [comment]
nginx/1.4.6
php 5.5.9-1ubuntu4.14
ubuntu 14.04.1

**Comment by laf** [comment]
Can replicate. Will see what we can do

**Comment by murrant** [comment]
This is happening in the rrdtool_graph() function, or code near that.   I'll be looking in to it today.

**Comment by jkrauska** [comment]
Debian GNU/Linux 8
PHP 5.6.20-0+deb8u1 (cli) (built: Apr 27 2016 11:26:05)
apache2                           2.4.10-10+deb8u4

**Comment by jkrauska** [comment]
I can confim that commit 228857d2daafe68542177b023eeafdb5db9da4bb fixed the issue. Thanks @murrant

**Comment by murrant** [comment]
Thanks @laf  he did most of the work, I just sent a PR for him :)

**Comment by adammmmm** [comment]
228857d got rid of most of them, restarted php-fpm, ended up on 0 zombies. Then checked back an hour or two later, and have 11 new.

**Comment by laf** [comment]
Just keep an eye on it for now, I'm pretty confident the fix - fixed it.

It's worth upgrading to php 7, this appears to be the same bug we've seen before and only effects 5.5 and 5.6 :(

**Comment by jkrauska** [comment]
@laf I too am still seeing these but in much fewer numbers.  The first fix did reduce them 10x, but I'm still getting a few defuncts after several page loads.

```www-data  7176  3.0  0.6 347512 25996 ?        S    18:46   0:03  \_ /usr/sbin/apache2 -k start
www-data  7359  0.0  0.0      0     0 ?        Z    18:46   0:00  |   \_ [sh] <defunct>
www-data  7413  0.0  0.0      0     0 ?        Z    18:46   0:00  |   \_ [sh] <defunct>
www-data  7502  0.0  0.0      0     0 ?        Z    18:46   0:00  |   \_ [sh] <defunct>
www-data  7704  0.0  0.0      0     0 ?        Z    18:46   0:00  |   \_ [sh] <defunct>
www-data  7773  0.0  0.0      0     0 ?        Z    18:46   0:00  |   \_ [sh] <defunct>
www-data  7791  0.0  0.0      0     0 ?        Z    18:46   0:00  |   \_ [sh] <defunct>
www-data  8428  0.0  0.0      0     0 ?        Z    18:47   0:00  |   \_ [sh] <defunct>```

**Comment by basn** [comment]
i Have the same, alot of defunct processes after running for a little while running under php7 also.
Ubuntu 16.04 with nginx and php7.

www-data 18660  0.3  0.2 370760 22852 ?        S    09:50   0:02  \_ php-fpm: pool www
www-data 20411  0.0  0.0      0     0 ?        Z    09:59   0:00  |   \_ [sh] <defunct>

etc.

**Comment by murrant** [comment]
Please make sure you are up to date.  If you are still having this issue, post your version.

**Comment by basn** [comment]
====================================
Version info:
Commit SHA: 7ad946f85d686a4ecd9df7a799b04823e0f462b0
DB Schema: 134
PHP: 7.0.8-0ubuntu0.16.04.2
MySQL: 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP version: 5.7.3

====================================
[OK]      Database connection successful



Still happening.

**Comment by murrant** [comment]
@basn We'll need more detail, because I don't think it is possible in the code right now.  I'd suggest starting a new issue with your detailed info.  Thanks.

**Comment by olds463** [comment]
I'm still seeing this issue aswell.

CentOS7, php 7.1.6-1, php-fpm, nginx

====================================
Component | Version
--------- | -------
LibreNMS  | 1.30-69-g5dfff22
DB Schema | 204
PHP       | 7.1.6
MySQL     | 10.1.25-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

**Comment by murrant** [comment]
Update your rrdtool.

**Comment by olds463** [comment]
Still persists after compiling 1.7.0
