### ISSUE TITLE
Set SNMP Status when Polling fails

### ISSUE THREAD

**Issue by air101** [librenms/librenms#4172]
Hello Everyone,

is this feature available yet? I'd like to set an snmp status for my machine (own snmp id) when polling for a specific device fails.

Thank you and Best Regards

**Comment by laf** [comment]
Sorry it's not clear what you mean by this?

**Comment by air101** [comment]
Sorry if I was unclear.

When I set an alarm, for example: port up/down, I want to modify local maschines oid snmp status to warning/error when the alarm is triggered.

**Comment by laf** [comment]
You mean use snmpset to change the device itself, if so we can't do that.

**Comment by air101** [comment]
yes thats what i mean. Oh what a shame if thats not possible

**Comment by crcro** [comment]
i think that librenms scope is to monitor not to configure the device :) this would imply another level of security ...

**Comment by Rosiak** [comment]
We had a talk around at similar subject months ago, I still think this is out of scope for LibreNMS. I suggest we close this for now, but thanks for bringing it up anyways!
