### ISSUE TITLE
[Info] SNMP polling 32bits VS 64bits

### ISSUE THREAD

**Issue by gcoeugnet** [librenms/librenms#4174]
Hi,

I presented LibreNMS to our supervision team. One of them which work on Cacti told me a strange thing that I would like to verify with you. It would appear that LibreNMS isn't using correct variable entries for its polling. For instance : uptime or 10Gbits ports usage.

This guy spoke me about 32bits VS 64bits variables. 32bits variables which seems to be used for uptime isn't large enough to contain uptime greater than 400 days... Are you aware of this and do I have to care about this nor LibreNMS already used 64bits counters ?

[Looking on the web](http://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/26007-faq-snmpcounter.html) lead me to this post which is related to this "issue" of 64bits.

Thanks a lot.
Guillaume.

**Comment by laf** [comment]
We default to 64bit counters, especially for ports. You must be using snmp v2c/v3 for 64bit to work.

**Comment by florianbeer** [comment]
Unfortunately according to my research SNMP can never display uptime over 497 days, because `HOST-RESOURCES-MIB::hrSystemUptime` reports hundreds of seconds since device poweron as 32bit integer value.

There is also `sysUpTimeInstance` but this reports time since restart of your SNMP daemon so it can sometimes report a lower uptime than the device actually has.

**Comment by gcoeugnet** [comment]
Thanks for replies.

According to what @florianbeer said, the HOST-RESOURCES-MIB::hrSystemUptime is using a 32 bits integer. I suppose you get your info [here ](https://thwack.solarwinds.com/thread/42524) !? This issue can't be solved easily by just probing another OID.

The most important thing for me is that 64bits OIDs are used for ports monitoring :) 

I'll discuss the uptime issue with my Cacti guy and will re-opened this issue if require to add information to solve the uptime problem. Most of our equipments have uptime greater than 497 days.

Thanks to both of you.
