### ISSUE TITLE
Incorrect toner levels

### ISSUE THREAD

**Issue by realnakrul** [librenms/librenms#4177]
Hi
We have Ricoh MP C2051 and the toner level is incorrect. Could somebody fix it, please?
./discovery.php -h HOSTNAME -d -m os
http://pastebin.com/6bABk8bj
./discovery.php -h HOSTNAME -d -m toner
http://pastebin.com/a7pbYjP9
./poller.php -h HOSTNAME -r -f -d -m toner
http://pastebin.com/7v7TesNG
snmpbulkwalk -On -v2c -c COMMUNITY HOSTNAME
http://pastebin.com/3hvtkwiU

Also is it possible to add printed pages count device page? Can I do it without coding? I am new to LibreNMS...
Thanks in advance.

**Comment by crcro** [comment]
unfortunately the docs from ricoh  states that -3 is returned for anything between 1-100% of toner level and -100 when toner is empty, so nothing real can get out for this ricoh model

**Comment by realnakrul** [comment]
Dear Crcro
Thank you for your reply, but I can get correct toner levels from the following OIDs:
2453: enterprises.367.3.2.1.2.24.1.1.2.1 Black Toner
2454: enterprises.367.3.2.1.2.24.1.1.2.2 Cyan Toner
2455: enterprises.367.3.2.1.2.24.1.1.2.3 Magenta Toner
2456: enterprises.367.3.2.1.2.24.1.1.2.4 Yellow Toner
2457: enterprises.367.3.2.1.2.24.1.1.3.1 Black Toner
2458: enterprises.367.3.2.1.2.24.1.1.3.2 Cyan Toner
2459: enterprises.367.3.2.1.2.24.1.1.3.3 Magenta Toner
2460: enterprises.367.3.2.1.2.24.1.1.3.4 Yellow Toner
2465: enterprises.367.3.2.1.2.24.1.1.5.1 90
2466: enterprises.367.3.2.1.2.24.1.1.5.2 20
2467: enterprises.367.3.2.1.2.24.1.1.5.3 20
2468: enterprises.367.3.2.1.2.24.1.1.5.4 100 
I compared them to levels from printer web GUI and they are OK
![capture](https://cloud.githubusercontent.com/assets/21193002/17918756/ca8602fa-69d8-11e6-8f0a-1b2ed1431df6.JPG)

**Comment by crcro** [comment]
hmm they are using different oids ... will code a fix and push it soon

**Comment by realnakrul** [comment]
Dear Crcro
Sorry for late reply.
Fix doesn't work :(

date
Sun Aug 28 10:34:18 GST 2016
git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

./discovery.php -h HOSTNAME -d -m toner
http://pastebin.com/WtYFFRKQ - it still shows original OIDs... Probably os is not ricoh, but nrg. I tried to change it myself, but no luck. I am not skilled in PHP...

**Comment by crcro** [comment]
@realnakrul ... new code submitted, please rediscover your device and leave some feedback, thanks.

**Comment by realnakrul** [comment]
Dear Crcro
Thank you for update. It's getting better, but not working properly yet. I can see correct toner names on the device LibreNMS page, but all levels are zero.
![zero](https://cloud.githubusercontent.com/assets/21193002/18079173/561f8252-6ea0-11e6-84ba-02d60c8b17da.JPG)
./poller.php -h HOSTNAME -r -f -d -m toner
http://pastebin.com/qPYWWLHV

**Comment by realnakrul** [comment]
Dear Crcro
I tried your fix from PR #4273. It doesn't work. I think the issue is in polled OIDs. For example:

#### Load poller module toner ####

SQL[SELECT * FROM toner WHERE device_id = '10'] Checking toner Black Toner... /usr/bin/snmpget -v2c -c COMMUNITY -OUqnv -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.367.3.2.1.2.24.1.1.5.190
INF %

But OID should be enterprises.367.3.2.1.2.24.1.1.5.1
Something wrong with $toner_oid = ".1.3.6.1.4.1.367.3.2.1.2.24.1.1.5.$index"; Probably... I am not skilled with PHP...

**Comment by crcro** [comment]
@realnakrul ... that $index is getting the value: 1:

SQL[SELECT * FROM toner WHERE device_id = '10'] Checking toner Black Toner... /usr/bin/snmpget -v2c -c COMMUNITY -OUqnv -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.367.3.2.1.2.24.1.1.5.1 = 90%
INF %

i've pushed another fix for polling

**Comment by laf** [comment]
Fixed in #4273
