### ISSUE TITLE
ntpd-server agent non functional

### ISSUE THREAD

**Issue by rbax82** [librenms/librenms#4187]
https://nms.baxterit.net/device/device=10/tab=apps/app=ntpd/
demo:demo
http://sprunge.us/iVST

**Comment by Tatermen** [comment]
What happens when you run the following commands:

```
/usr/sbin/ntpq -c rv
/usr/sbin/ntpdc -c iostats
```

**Comment by crcro** [comment]
@rbax82  ntp-server and ntp-client agent scripts and librenms webui updates where submitted, waiting merge.

**Comment by laf** [comment]
Merged. Please retry.
