### ISSUE TITLE
Feature Request: Flag for re-discovery

### ISSUE THREAD

**Issue by mzac** [librenms/librenms#4206]
Not sure if this would be possible, but when looking at a device and clicking on the gear icon, it would be interesting to have an option to flag the device for re-discovery.

This could be useful in the case that you have made changes on the device that require discovery (new hardware, software upgrade, etc) .

This would probably require either a new column in the device database or a new table that could list devices that are scheduled for re-discovery.

Then, when the 'new' discovery cron job runs every 5 minutes, it could also verify this flag and re-discover those devices.  The flag would then need to be cleared once the device is re-discovered.

**Comment by crcro** [comment]
@mzac there is already .. but it is under snmp tab in settings/edit

**Comment by Rosiak** [comment]
Is this what you are looking for?

<img width="934" alt="screen shot 2016-08-25 at 19 29 36" src="https://cloud.githubusercontent.com/assets/6378934/17979329/48b14f14-6afa-11e6-82ca-a8cb27d1c482.png">

**Comment by mzac** [comment]
Ah yes that is it, I guess I missed it!

**Comment by Rosiak** [comment]
Perfect, closing.
