### ISSUE TITLE
PHP CPU pegged

### ISSUE THREAD

**Issue by ciscoqid** [librenms/librenms#4207]
I have been seeing a php process stuck at 100% CPU frequently recently.  I had just been killing it initially thinking it was an anomaly, but today it was wedged again so I ran strace.  This sequence is spinning:

getdents(4, /* 0 entries */, 32768)     = 0
open("/opt/librenms/includes/discovery/sensors/temperatures/dnos-ftos-s-series.inc.php", O_RDONLY) = 5
fstat(5, {st_mode=S_IFREG|0644, st_size=1013, ...}) = 0
fstat(5, {st_mode=S_IFREG|0644, st_size=1013, ...}) = 0
fstat(5, {st_mode=S_IFREG|0644, st_size=1013, ...}) = 0
mmap(NULL, 1013, PROT_READ, MAP_SHARED, 5, 0) = 0x7f73e5128000
munmap(0x7f73e5128000, 1013)            = 0
close(5)                                = 0

It is not clear to me yet why this is looping, but I think it may be triggered by the discover_sensor call within the script.  At least that is the only line I can imagine would lead to this, but then this seems like a fairly common pattern in discovery modules.

**Comment by murrant** [comment]
I have a fix ready (#4210) and it is just waiting for testing.  It should be merged tomorrow.

**Comment by laf** [comment]
Merged, thanks for reporting.

**Comment by murrant** [comment]
This could be a different bug.

**Comment by laf** [comment]
@ciscoqid Can you confirm this is now resolved?

**Comment by ciscoqid** [comment]
On 8/29/2016 1:34 PM, Neil Lathwood wrote:
>
> @ciscoqid <https://github.com/ciscoqid> Can you confirm this is now resolved?
>
I have not seen it recur in past few days -- was happening constantly prior to that, so
let's go with yes!

Thanks,
Mark

-- 
Mark D. Nagel, CCIE #3177 Emeritus <mnagel@willingminds.com>
Principal Consultant, Willing Minds LLC (http://www.willingminds.com)
cell: 949-279-5817, desk: 714-495-4001, fax: 714-844-4698

** For faster support response time, please
** email support@willingminds.com or call 714-495-4000

**Comment by ciscoqid** [comment]
I guess I spoke too soon.  This has continued to happen sporadically.  Same sort of behavior, but not always the same file.  The one I just killed showed this in strace.

getdents(4, /* 0 entries */, 32768)     = 0
open("/opt/librenms/includes/discovery/sensors/temperatures/zyxel-ies.inc.php", O_RDONLY) = 5
fstat(5, {st_mode=S_IFREG|0644, st_size=1146, ...}) = 0
fstat(5, {st_mode=S_IFREG|0644, st_size=1146, ...}) = 0
fstat(5, {st_mode=S_IFREG|0644, st_size=1146, ...}) = 0
mmap(NULL, 1146, PROT_READ, MAP_SHARED, 5, 0) = 0x7f53e1200000
munmap(0x7f53e1200000, 1146)            = 0
close(5)                                = 0
