### ISSUE TITLE
Monitoring devices with dynamic IPs

### ISSUE THREAD

**Issue by pereljon** [librenms/librenms#4209]
Is it possible to monitor devices with dynamic (DHCP) IPs?

Specifically, if a device's IP address changes and it is added with its new IP address, is LibreNMS able to recognize both IPs have the same MAC address and update the IP address of the device to the new address?

Thanks
JP

**Comment by murrant** [comment]
Yes, just use DNS names.  update the DNS.

You can even use DDNS to update the DNS names.  https://en.wikipedia.org/wiki/Dynamic_DNS

**Comment by laf** [comment]
And just to cover it off, if you can't use hostnames then the only way is to rename the device using ./renamehost.php

**Comment by pereljon** [comment]
Thanks. DNS names makes sense, but the rename script is good to know in case we change DNS names in the future.
