### ISSUE TITLE
ntpd agent graphs not showing all values

### ISSUE THREAD

**Issue by seitzbg** [librenms/librenms#4211]
#### Please note

> Please read this information carefully.
- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
  Yes
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
  Version info:
  Commit SHA: 3d0edb46ccf0e832480c2bd22369cb94c24b4ed6
  DB Schema: 130
  PHP: 5.6.24
  MySQL: 10.1.16-MariaDB
  RRDTool: 1.5.6
  SNMP: NET-SNMP version: 5.7.3
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.
  Not seeing values for all of the items on the graph: https://www.bsd-unix.net/seitz/screenshots/LibreNMS_2016-08-25_22-15-52.png

Poller output: https://www.bsd-unix.net/seitz/private/ntp-gps1.fiber.house.poller.txt

**Comment by crcro** [comment]
@seitzbg ... ntp-server and ntp-client agent scripts and librenms webui updates where submitted, waiting merge.

**Comment by crcro** [comment]
@seitzbg ... agent scripts and webui PR were merge, please check it now

**Comment by seitzbg** [comment]
Looks like the iostats command should be this in the agent:

ntpdc -n -c iostats

vs 

$BIN_NTPQ -c iostats localhost

**Comment by crcro** [comment]
i'm using the ntpq command not the ntpdc

**Comment by seitzbg** [comment]
[seitz@ntp-gps1 ~]$ ntpq -c iostats
***Command `iostats' unknown

[seitz@ntp-gps1 ~]$ ntpdc -c iostats
time since reset:     2067258
receive buffers:      10
free receive buffers: 9
used receive buffers: 0
low water refills:    1
dropped packets:      0
ignored packets:      69380
received packets:     4360238
packets sent:         235338
packets not sent:     0
interrupts handled:   2466755
received by int:      2466755

**Comment by seitzbg** [comment]
Also to note my apps->ntpd page is blank :(

https://www.bsd-unix.net/seitz/screenshots/firefox_2016-09-11_18-39-56.png

**Comment by crcro** [comment]
from your image you are running and old version of librenms, please update it
also please tell the ntpd version (the above scripts where tested against 4.2.8p8)
on my systems ntpdc -c iostats returns:
localhost: timed out, nothing received
***Request timed out

**Comment by seitzbg** [comment]
My host runs CentOS7:
ntp-4.2.6p5-22.el7.centos.2.x86_64

Fedora 24 runs a 4.2.6p5 as well so it seems that function is quite new for ntpq.

Ran daily.sh to update.

**Comment by rbax82** [comment]
So I moved everything from the unix agent to the snmp extension just to find that it is broken :(
 https://nms.baxterit.net/apps/app=ntp-server/ demo:demo

**Comment by crcro** [comment]
@rbax82 ... i see a lot of graphs not working on your demo, please post the output for ./validate.php

@seitzbg ... i'll put a fix for older versions in place

**Comment by crcro** [comment]
@seitzbg ... i submitted a fix for ntp-server check it out for your deployment:
https://github.com/librenms/librenms-agent/pull/61/files

**Comment by seitzbg** [comment]
This does not work due to how ntpd prints out the version, maybe try this instead:
`ntpq --version |awk '{print $2}'`

On my host ntpd --version prints out:
`[root@ntp-gps1 ~]# ntpd --version
ntpd 4.2.6p5

exit 0
`

**Comment by seitzbg** [comment]
After the above I get:
```
[root@ntp-gps1 snmp]# ./ntpd-server.sh
1
-23.021
0.002
0.000
0.002

2131766
10
9
0
0
69380
4496873
243225
```

**Comment by seitzbg** [comment]
apps -> ntpd still blank FYI.

**Comment by crcro** [comment]
you should see ntp server not ntpd in apps.
if you still see ntpd you have an old version of webui

**Comment by seitzbg** [comment]
No I have the latest, but I had to go into applications and check ntp server, it didn't get rid of 'ntpd' :)  Lets see if they populate now.

**Comment by seitzbg** [comment]
https://www.bsd-unix.net/seitz/screenshots/firefox_2016-09-12_14-41-15.png

**Comment by rbax-idx** [comment]
Yup, still borked.

**Comment by seitzbg** [comment]
Had to change snmpd.conf to extend 'ntp-server' and i'm getting some values but some are still NaN.  Not sure the data is lining up in SNMP properly. Is this right?

```
NET-SNMP-EXTEND-MIB::nsExtendCommand."ntp-server" = STRING: /etc/snmp/ntpd-server.sh
NET-SNMP-EXTEND-MIB::nsExtendArgs."ntp-server" = STRING:
NET-SNMP-EXTEND-MIB::nsExtendInput."ntp-server" = STRING:
NET-SNMP-EXTEND-MIB::nsExtendCacheTime."ntp-server" = INTEGER: 5
NET-SNMP-EXTEND-MIB::nsExtendExecType."ntp-server" = INTEGER: exec(1)
NET-SNMP-EXTEND-MIB::nsExtendRunType."ntp-server" = INTEGER: run-on-read(1)
NET-SNMP-EXTEND-MIB::nsExtendStorage."ntp-server" = INTEGER: permanent(4)
NET-SNMP-EXTEND-MIB::nsExtendStatus."ntp-server" = INTEGER: active(1)
NET-SNMP-EXTEND-MIB::nsExtendOutput1Line."ntp-server" = STRING: 1
NET-SNMP-EXTEND-MIB::nsExtendOutputFull."ntp-server" = STRING: 1
NET-SNMP-EXTEND-MIB::nsExtendOutNumLines."ntp-server" = INTEGER: 14
NET-SNMP-EXTEND-MIB::nsExtendResult."ntp-server" = INTEGER: 0
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ntp-server".1 = STRING: 1
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ntp-server".2 = STRING: -23.860
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ntp-server".3 = STRING: 0.001
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ntp-server".4 = STRING: 0.000
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ntp-server".5 = STRING: 0.001
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ntp-server".6 = STRING:
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ntp-server".7 = STRING: 2146569
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ntp-server".8 = STRING: 10
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ntp-server".9 = STRING: 9
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ntp-server".10 = STRING: 0
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ntp-server".11 = STRING: 0
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ntp-server".12 = STRING: 69380
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ntp-server".13 = STRING: 4528260
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ntp-server".14 = STRING: 245062
```

**Comment by crcro** [comment]
@seitzbg ... please post the raw output of ntpdc -c iostats

**Comment by seitzbg** [comment]
```
[seitz@ntp-gps1 ~]$ ntpdc -c iostats
time since reset:     2149717
receive buffers:      10
free receive buffers: 9
used receive buffers: 0
low water refills:    1
dropped packets:      0
ignored packets:      69380
received packets:     4534953
packets sent:         245471
packets not sent:     0
interrupts handled:   2564580
received by int:      2564580
```

**Comment by rbax-idx** [comment]
FYI;
That command doesn't work under FreeBSD 10.3

**Comment by seitzbg** [comment]
Looks like FBSD 10 has newer ntp of course:

(6:32pm) [seitz@triton] [~] > /usr/bin/ntpq --version
ntpq 4.2.8p8-a (1)

**Comment by crcro** [comment]
the FBSD should be ok with the actual script available into repository (as it was tested with 4.2.8p8, under linux instead)

**Comment by rbax82** [comment]
>./validate.php
====================================
Version info:
Commit SHA: a8efda8f309b23d574a58506448b2a5023715e5d


DB Schema: 133
PHP: 5.4.16
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2

**Comment by seitzbg** [comment]
```
ntpq -c rv
associd=0 status=04f8 leap_none, sync_uhf_radio, 15 events, no_sys_peer,
version="ntpd 4.2.6p5@1.2349-o Tue May 31 10:28:54 UTC 2016 (1)",
processor="x86_64", system="Linux/3.10.0-327.28.2.el7.x86_64", leap=00,
stratum=1, precision=-23, rootdelay=0.000, rootdisp=1.000, refid=PPS,
reftime=db83388d.ef1cf8b2  Tue, Sep 13 2016 22:46:37.934,
clock=db83388e.daa07e25  Tue, Sep 13 2016 22:46:38.854, peer=37023, tc=4,
mintc=3, offset=-0.001, frequency=-23.178, sys_jitter=0.001,
clk_jitter=0.000, clk_wander=0.001
```

**Comment by crcro** [comment]
updated the shell script to be easier to match exact values:
https://github.com/librenms/librenms-agent/pull/62/files

please deactivate any instance of ntp-server in webui and make sure that the associated rrd file is removed, after that re-enable the app to make a clean start

**Comment by rbax82** [comment]
It's working on my Linux servers! =)
https://nms.baxterit.net/apps/app=ntp-server/ demo:demo

**Comment by seitzbg** [comment]
Doesn't work on mine since ntpd --version output is not just the version hence why I suggested ntpq --version.

**Comment by crcro** [comment]
@rbax82 ... i see some graph not working on your website, did you removed old rrd files?

@seitzbg ... doesn't matter, mine doesn't print version only, both commands print exactly the same:

NCAERoDC01ntp01:/opt # ntpq --version
ntpq 4.2.8p8@1.3265-o Thu Jun 16 07:27:50 UTC 2016 (1)
NCAERoDC01ntp01:/opt # ntpd --version
ntpd 4.2.8p8@1.3265-o Thu Jun 16 07:27:44 UTC 2016 (1)
NCAERoDC01ntp01:/opt #

can you please post the raw output of ntpd/ntpq --version

**Comment by rbax82** [comment]
@crcro I deleted the device and re-added it.

**Comment by seitzbg** [comment]
```
[seitz@ntp-gps1 ~]$ ntpd --version
ntpd 4.2.6p5

exit 0
[seitz@ntp-gps1 ~]$ ntpq --version
ntpq 4.2.6p5
[seitz@ntp-gps1 ~]$ ntpdc --version
ntpdc 4.2.6p5
```

**Comment by crcro** [comment]
a little update pushed again in shell script

**Comment by duccxx** [comment]
K

**Comment by crcro** [comment]
is this fixed now for everyone? can be closed?

**Comment by laf** [comment]
No further info provided
