### ISSUE TITLE
Auth debug

### ISSUE THREAD

**Issue by Luc3as** [librenms/librenms#4221]
Hello, I have 2 questions, first,  I am trying to setup auth of librenms to Active directory, I am user from observium and I know , when I tried to setup auth with ldap in observium , there was debug option with authentication and it really helped me with setup of config. 
when I try to open IP of librenms with debug ?debug=yes or /debug=yes/  I just get warning Login error
Authentication Failed.

And I would need to see some config with AD auth configured and working. I know I now have some errors in config.

here is part from auth section, I dont know what format should users have and other options. 

I tried to copy config from observium through LDAP mechanism, again with no luck. I know LDAP connection from server is working, tested with ldapsearch command and get results from AD.

$config['auth_mechanism'] = "active_directory";    // default, other options: ldap, http-auth, please see documentation for config help

$config['auth_ad_url']                      = "ldaps://dc.tntel.local";
$config['auth_ad_check_certificates']       = 0; // or 0
$config['auth_ad_domain']                   = "tntel.local";
$config['auth_ad_base_dn']                  = "dc=tntel,dc=local";
$config['auth_ad_groups']['Domain Admins']['level'] = 10;
$config['auth_ad_groups']['Domain Users']['level']   = 7;
$config['auth_ad_require_groupmembership']  = 0;
$config['active_directory']['users_purge']  = 14;//Purge users who haven't logged in for 14 days.
$config['auth_ad_binduser']     = "observium";
$config['auth_ad_bindpassword'] = "pass";
$config['auth_ldap_cache_ttl']  = 300;

[FAIL]    Syntax error in config.php
====================================
Version info:
Commit SHA: 15b0cd68ea05e913e94e28d1e8daee69c08cfd8f
DB Schema: 130
PHP: 7.0.9
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2

====================================
[OK]      Database connection successful

thanks

**Comment by laf** [comment]
We have auth debug disabled until you logged in, sounds silly but we don't want to expose this information to people if they are unauthenticed.

The fact you have syntax error is a bad start anyway, run `php -ln config.php` to see where it is and resolve that.

In the meantime, have you checked our docs for authentication, we most likely don't have the same options as obs..... http://docs.librenms.org/Extensions/Authentication/

**Comment by laf** [comment]
Please feel free to reply back if you need more info.
