### ISSUE TITLE
Match wildcard syslog alerts

### ISSUE THREAD

**Issue by bitency** [librenms/librenms#4223]
Hi,

We trying to match all Syslog log entries with a Alert rule:

Wildcard are not working:
Tried:
%syslog.msg = "." &&
%syslog.msg = "@" &&
%syslog.msg = "*" &&

%syslog.msg = "test123" && - works correctly if the message is "test123"

**Comment by laf** [comment]
You're using equals. Switch to like

**Comment by florianbeer** [comment]
Nice idea! May I ask what kinds of events you set alerts on? There are so many different syslog messages that it's kinda hard to choose what to configure without getting too many alerts.

**Comment by bitency** [comment]
Fixed with rule: %syslog.msg ~ "@" &&

> Nice idea! May I ask what kinds of events you set alerts on? There are so many different syslog messages that it's kinda hard to choose what to configure without getting too many alerts.

We have another script (mail piping) with rules for alerting to Pushover.

**Comment by FTBZ** [comment]
I want to implement a similar syslog setup with our equipments, but how to suppress a waring with a syslog message? When pushing the "Acknowledge" button, the alert remains in the list and can't be suppressed. SNMP messages are automatically suppressed when the alert is resolved, but syslog isn't returning an OK stat. How to handle this with the alerting system?

**Comment by florianbeer** [comment]
> We have another script (mail piping) with rules for alerting to Pushover.

I'm sorry, but that didn't answer my question.  
I am curious what kind of events you are alerting on, what is the content of the syslog message that would trigger an alert.

**Comment by FTBZ** [comment]
> I am curious what kind of events you are alerting on, what is the content of the syslog message that would trigger an alert.

In our case, we use syslog to catch messages that's not sent through SNMP for Cisco devices especially. We catch these kinds of messages:

- Loopguard
- State to down/up for monitored port on device
- BPDU guard
- Flapping MAC
- ...

**Comment by f0o** [comment]
We used to have a rule defined on the demo that alerts on auth-fail syslog entries. Seems to have gotten lost sadly. I'll recreate it after lunch

**Comment by bitency** [comment]
Same alerts here.

+ BGP down/up
+ BGP message for routing table sizes
+ Login from SSH/console

**Comment by florianbeer** [comment]
Thank you

**Comment by f0o** [comment]
Well who would've guessed, the mentioned auth-fail rule is in the docs!

http://docs.librenms.org/Extensions/Alerting/#examples

**Comment by bitency** [comment]
I create now a alert for syslog:

%syslog.msg ~ "@" && %syslog.device_id != "1" && %syslog.timestamp >= %macros.past_5m
Max alerts: 1
Delay and interval: 0
Severity: OK

%macros.past_1m doesn't work?

**Comment by FTBZ** [comment]
@f0o, I used the documentation like your example for implementing our rules. But when the alert occurs, how to clear it when the problem was solved?

**Comment by laf** [comment]
@FTBZ That rule will clear after 5 minutes as it's limited within the rule. You need to ensure your timezones in php and mysql match otherwise this doesn't work well.

**Comment by FTBZ** [comment]
@laf I checked SQL and it's using the system time zone:

> [root@librenms ~]# date
Tue Aug 30 17:06:31 CEST 2016
[root@librenms ~]# mysql -e "SELECT @@global.time_zone;"
+--------------------+
| @@global.time_zone |
+--------------------+
| SYSTEM             |
+--------------------+
[root@librenms ~]# mysql -e "SELECT NOW();"
+---------------------+
| NOW()               |
+---------------------+
| 2016-08-30 17:06:59 |
+---------------------+

When you say it's cleared after 5 minutes, it's based on Delay/interval values or it's hard coded?

**Comment by laf** [comment]
It's based on the dynamic translation of the macro so last5m will just be 5 minutes ago.

**Comment by FTBZ** [comment]
@laf thanks! It's working but it's not exactly what I expected. Based on your information I searched for an entity that can check if mute was pressed or not. I want to get all syslog in alerts but to be able to clear manually if an alert need to disappear.

Workflow should be:

1. Syslog alert appears
2. Email notifications are sent
3. Problem is checked/solved
4. Alert is manually cleared

**Comment by laf** [comment]
I very much doubt that will work as a new alert hasn't actually been raised at that point so the rule will eval to true because state doesn't = 2 - it doesn't exist at all at this stage.

We have no way of clearing alerts manually, the idea of the alerting system is that you either fix the issue so the alert clears or you ack it. If you were able to clear it manually it would just re-appear on the next polling run as we will still see the eval of that rule as true.
