### ISSUE TITLE
Feature Request: APC UPS stats via USB connection

### ISSUE THREAD

**Issue by mzac** [librenms/librenms#4230]
I'd love it if I had the time to write this, but I'm not sure where to start.  

I have a APC UPS connected via a UPS cable and I can use the apcupsd tools to query the UPS.

Would it be easy to write a wrapper application to take the output of this tool and create all the UPS graphs, states, etc via SNMP?

<pre>
root@pi3:~# /sbin/apcaccess
APC      : 001,037,0918
DATE     : 2016-08-27 16:21:54 -0400
HOSTNAME : pi3
VERSION  : 3.14.12 (29 March 2014) debian
UPSNAME  : UPS1
CABLE    : USB Cable
DRIVER   : USB UPS Driver
UPSMODE  : Stand Alone
STARTTIME: 2016-08-04 15:02:43 -0400
MODEL    : Back-UPS XS 1300 LCD
STATUS   : ONLINE
LINEV    : 120.0 Volts
LOADPCT  : 17.0 Percent
BCHARGE  : 100.0 Percent
TIMELEFT : 37.2 Minutes
MBATTCHG : 25 Percent
MINTIMEL : 5 Minutes
MAXTIME  : 0 Seconds
SENSE    : Medium
LOTRANS  : 88.0 Volts
HITRANS  : 139.0 Volts
ALARMDEL : No alarm
BATTV    : 26.9 Volts
LASTXFER : Low line voltage
NUMXFERS : 4
XONBATT  : 2016-08-22 12:39:53 -0400
TONBATT  : 0 Seconds
CUMONBATT: 13 Seconds
XOFFBATT : 2016-08-22 12:39:55 -0400
SELFTEST : NO
STATFLAG : 0x05000008
SERIALNO : 8B0839RXXXXX
BATTDATE : 2016-01-02
NOMINV   : 120 Volts
NOMBATTV : 24.0 Volts
NOMPOWER : 780 Watts
FIRMWARE : 836.H8 .D USB FW:H8
END APC  : 2016-08-27 16:22:00 -0400
</pre>

**Comment by Rosiak** [comment]
Munin perhaps?

**Comment by crcro** [comment]
or could be snmp extend script with some shell scripting for output parsing on the host that has that ups attached
