### ISSUE TITLE
Development of new applications

### ISSUE THREAD

**Issue by KristijanL** [librenms/librenms#4232]
Hi, I'm trying to write an application for librenms but I have issues with getting data from unix-agent. While debuging I noticed that unix-agent successefully got all the information from the telnet request but said data was not provided to the application [app].inc.php.

```
#############
telnet IP 6556
.....
<<<postfix_mailq>>>
Mail queue is empty
<<<local>>>
<<<postgres>>>
pg.CONNECTIONS=19
Connection closed by foreign host.
#############

./poller.php -h IP -vd

#### Load poller module unix-agent ####
LibreNMS UNIX Agent:
SQL[^[[0;33mSELECT attrib_value FROM devices_attribs WHERE `device_id` = '23' AND `attrib_type` = 'override_Unixagent_port' ^[[0m] execution time: 105msRRD[^[[0;32mupdate IP/agent.rrd N:105 --daemon unix:/var/run/rrdcached/rrdcached.sock^[[0m]
RRDtool Output: OK u:0.01 s:0.02 r:0.64
Array
(
    [] =>
    [check_mk] => Version: 1.2.2p2

.....

   [local] =>
    [app] => Array
        (
            [postgres] => pg.CONNECTIONS=19
        )

    [postgres] => pg.CONNECTIONS=19
)
#############

./poller.php -h IP -m applications -dv
....

#### Load poller module applications ####
SELECT * FROM `applications` WHERE `device_id`  = '23'


SQL[SELECT * FROM `applications` WHERE `device_id`  = '23']
Postgres Missing


 Runtime for poller module 'applications': 0.0021622180938721 seconds
#############
```

Kind regards,
Kristijan

**Comment by KristijanL** [comment]
my changes
https://github.com/KristijanL/librenms/commit/f056782104d62a5fb1b1a74cecca0dbe8a511a8d

**Comment by laf** [comment]
Have you selected postresql in the applications list for that device (Click edit device -> Applications).

**Comment by KristijanL** [comment]
yes i have.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
