### ISSUE TITLE
Cisco UCS support

### ISSUE THREAD

**Issue by realnakrul** [librenms/librenms#4252]
Hi
Could somebody add Cisco UCSC-C220-M4S to LibreNMS, please? MIBs can be found here: http://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/sw/mib/c-series/b_UCS_Standalone_C-Series_MIBRef/b_UCS_Standalone_C-Series_MIBRef_chapter_01.html
./discovery.php -h HOSTNAME -d -m os
http://pastebin.com/UZKRSa16
./poller.php -h HOSTNAME -r -f -d -m os
http://pastebin.com/WWhAHJhe
snmpbulkwalk -On -v2c -c COMMUNITY HOSTNAME
http://pastebin.com/SXL0Kc0j

**Comment by Rosiak** [comment]
Could you do a walk with CISCO-UNIFIED-COMPUTING-COMPUTE-MIB loaded? :)

**Comment by realnakrul** [comment]
Hi
Sure. Here is it:
http://pastebin.com/64jExVVW
I did it with following MIBs loaded:
![capture](https://cloud.githubusercontent.com/assets/21193002/18079378/5906b12e-6ea1-11e6-860e-5f0f52b74603.JPG)

**Comment by realnakrul** [comment]
Dear Rosiak
Thank you so much. Could you add some more details to the device, please. I mean inventory, temperature, RAM, storage...

**Comment by Rosiak** [comment]
Hi @realnakrul 
Sorry for closing the issue, I just created a post on out community site instead, to discuss what we needed to monitor.
Could you be a bit more specific on what you would like to see graphed/monitored?
There are so much information available on the UCS device.

**Comment by realnakrul** [comment]
No issues :)
Could you kindly start with inventory?

**Comment by Rosiak** [comment]
@adaniels21487 is working on something :)
