### ISSUE TITLE
Email alerts not working "Error: You must provide at least one recipient email address."

### ISSUE THREAD

**Issue by FTBZ** [librenms/librenms#4253]
Hello,

I'm unable to make the alerts to work by email. The alert setting seems to be correct because the "Test transport" is working, I get the test mail.

When looking at the Event log, I see this kind of messages:

> Could not issue warning alert for rule 'Sensor under limit' to transport 'mail' Error: You must provide at least one recipient email address.

An idea?

Thanks!

**Comment by laf** [comment]
Post screenshot of your alert settings

**Comment by FTBZ** [comment]
Thanks.

![screen shot 2016-08-29 at 15 11 49](https://cloud.githubusercontent.com/assets/1927109/18052514/13faaf6e-6dfb-11e6-9597-0332aa846953.png)
![screen shot 2016-08-29 at 15 11 55](https://cloud.githubusercontent.com/assets/1927109/18052516/141b0232-6dfb-11e6-939c-4fddecbfa7fe.png)
![screen shot 2016-08-29 at 15 12 04](https://cloud.githubusercontent.com/assets/1927109/18052515/14183e4e-6dfb-11e6-856c-6d258e2ad365.png)

**Comment by laf** [comment]
In those settings as you have send alerts to default contact only then it will just use that. If you've set it after the alert was issued then this will explain it and you can disable 'Updates to contact email addresses not honoured'.

**Comment by FTBZ** [comment]
Oh! That's right, alarms was configured before default contact. And I did not really understand the definition of the option "Updates to contact email addresses not honoured"... Excellent analysis, it's working fine. Thanks a lot.
