### ISSUE TITLE
Understanding the difference of the values between Cacti and LibreNMS

### ISSUE THREAD

**Issue by FTBZ** [librenms/librenms#4254]
Hello,

We're trying to replace Cacti by LibreNMS but I noticed that the values returned by the two systems are really different.

This is an example for our Internet connection:

![librenms](https://cloud.githubusercontent.com/assets/1927109/18052929/56612fde-6dfd-11e6-8ab9-e6ea287a379f.png)
![cacti](https://cloud.githubusercontent.com/assets/1927109/18052654/ec9ce968-6dfb-11e6-98ee-7fcd61301778.png)

When using the real time in LibreNMS, I get the same value as Cacti. 

An idea?

Thanks

**Comment by FTBZ** [comment]
Same thing with specific plugins for Cisco Wireless and Cisco ASA:
![vpn](https://cloud.githubusercontent.com/assets/1927109/18063793/ccc10760-6e2c-11e6-888d-94acc07ff074.png)
![wifi](https://cloud.githubusercontent.com/assets/1927109/18063794/ccc42684-6e2c-11e6-8cd9-7668fd02d77f.png)

Why having value with decimal point?

**Comment by laf** [comment]
Are you doing 1 min polling in cacti?

**Comment by FTBZ** [comment]
Yes, Cacti polling is every minute.

**Comment by laf** [comment]
That 'could' explain the differences, I see the same when running polling at 5 min and 1 min intervals.

A link can be doing 8Gbs but show as 5Gbps on the 5 mins average.

**Comment by FTBZ** [comment]
Yes, but in this case the link was busy at ~200Mbps all the day. The information from Cacti is correct based on our firewall monitoring comparaison. But the information from LibreNMS is completely wrong.

LibreNMS does a 5m average like Cacti?

Thanks for your time.

**Comment by FTBZ** [comment]
Yesterday evening I updated our installation to the latest build and it seems to have corrected the problem:

![cacti](https://cloud.githubusercontent.com/assets/1927109/18078961/9907b52e-6e8e-11e6-9859-7edb0ab87fd8.png)
![librenms](https://cloud.githubusercontent.com/assets/1927109/18078962/99232804-6e8e-11e6-96db-1fe5f565347a.png)

The initial installation was made Friday, I don't know if you're corrected something that can explain that issue. I will wait a few days and compare values again with Cacti.

**Comment by laf** [comment]
We've not fixed anything in the last week to do with this but you've answered your own question. snmpv1 - It's limited to 125Mb/s, anything more and traffic drops off.
