### ISSUE TITLE
Ubiquiti AC Gen 2 Mib update

### ISSUE THREAD

**Issue by TyShawn76** [librenms/librenms#4266]
Ubiquiti has updated their MIBs for their Gen 2 UAP devices. I was hoping to have the updated MIBs updated in Libre. I am including the information from UBNT in a beta forum.

http://community.ubnt.com/t5/UniFi-Wireless-Beta/Gen2-New-SNMP-MIB-Firmware/m-p/1606428#U1606428

Hi all,
 
I have a test firmware with improved SNMP MIB support. We added our own MIB to the already existing ones. This should provide significantly more information, especially about radio and BSS statistics. This is based on the upcoming 3.7.7 release, so should be pretty stable. Let us know if you find any issues!
 
The MIBs can be found here:
http://dl.ubnt-ut.com/snmp/UBNT-MIB
http://dl.ubnt-ut.com/snmp/UBNT-UniFi-MIB
 
This firmware is only for gen2 devices (UAP-AC-Lite/AC-LR/AC-Pro/AC-EDU)
http://dl.ubnt-ut.com/snmp/gen2-tinysnmp-3.7.x.bin | 0c8aa0e855455405ec8197b5e46c01fb

**Comment by Rosiak** [comment]
Is this Beta? If so I think we should wait till an actual release.

**Comment by TyShawn76** [comment]
Yes it's in beta at this moment.

**Comment by Rosiak** [comment]
Don't get me wrong, but I don't think we should introduce support for something that is in a beta stage. But that's just my opinion. 
@librenms/reviewers ?

**Comment by TyShawn76** [comment]
I totally respect those views and if that's the direction then I can wait :). Is there a link or a guide I can look at if I want to try and get this working on my own for testing?

**Comment by Rosiak** [comment]
You could maybe look at #721, but it's a fairly old commit just fyi.

**Comment by TyShawn76** [comment]
Cool many thanks for your time and wisdom.

**Comment by laf** [comment]
I'd be happy to see it introduced personally.

**Comment by florianbeer** [comment]
Yes! That would be so incredibly handy. Especially channel utilization and number of connected clients per radio.

**Comment by Rosiak** [comment]
@TyShawn76 Could you please post a snmpwalk with these new mibs loaded?

**Comment by TyShawn76** [comment]
Can you check the forums for me please needed some info. Then I can supply you with the info you seek from me.

**Comment by TyShawn76** [comment]
>

**Comment by TyShawn76** [comment]
`.1.3.6.1.2.1.1.1.0 = STRING: "Linux 3.3.8 #1 Mon Aug 22 10:00:05 PDT 2016 mips"
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.10002.1
.1.3.6.1.2.1.1.3.0 = Timeticks: (49466000) 5 days, 17:24:20.00
.1.3.6.1.2.1.1.4.0 = STRING: "unset"
.1.3.6.1.2.1.1.5.0 = STRING: "AC-Lite-ROA"
.1.3.6.1.2.1.1.6.0 = STRING: "unset"
.1.3.6.1.2.1.1.7.0 = INTEGER: 79
.1.3.6.1.2.1.1.8.0 = Timeticks: (3700) 0:00:37.00
.1.3.6.1.2.1.1.9.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.1.9.1.1.2 = INTEGER: 2
.1.3.6.1.2.1.1.9.1.1.3 = INTEGER: 3
.1.3.6.1.2.1.1.9.1.1.4 = INTEGER: 4
.1.3.6.1.2.1.1.9.1.1.5 = INTEGER: 5
.1.3.6.1.2.1.1.9.1.2.1 = OID: .1.3.6.1.6.3.1
.1.3.6.1.2.1.1.9.1.2.2 = OID: .1.3.6.1.2.1.31
.1.3.6.1.2.1.1.9.1.2.3 = OID: .1.3.6.1.4.1.41112.1.2.5
.1.3.6.1.2.1.1.9.1.2.4 = OID: .1.3.6.1.4.1.10002.1.1.1.31
.1.3.6.1.2.1.1.9.1.2.5 = OID: .1.2.840.10036
.1.3.6.1.2.1.1.9.1.3.1 = STRING: "The MIB module for SNMP entities"
.1.3.6.1.2.1.1.9.1.3.2 = STRING: "The MIB module to describe generic objects for network interface sub-layers"
.1.3.6.1.2.1.1.9.1.3.3 = STRING: "The MIB module for Ubiquiti entities."
.1.3.6.1.2.1.1.9.1.3.4 = STRING: "The MIB module to describe system resources"
.1.3.6.1.2.1.1.9.1.3.5 = STRING: "The MIB module for IEEE 802.11 entities."
.1.3.6.1.2.1.1.9.1.4.1 = Timeticks: (3700) 0:00:37.00
.1.3.6.1.2.1.1.9.1.4.2 = Timeticks: (3700) 0:00:37.00
.1.3.6.1.2.1.1.9.1.4.3 = Timeticks: (3700) 0:00:37.00
.1.3.6.1.2.1.1.9.1.4.4 = Timeticks: (3700) 0:00:37.00
.1.3.6.1.2.1.1.9.1.4.5 = Timeticks: (3700) 0:00:37.00
.1.3.6.1.2.1.2.1.0 = INTEGER: 7
.1.3.6.1.2.1.2.2.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.1.2 = INTEGER: 2
.1.3.6.1.2.1.2.2.1.1.3 = INTEGER: 3
.1.3.6.1.2.1.2.2.1.1.4 = INTEGER: 4
.1.3.6.1.2.1.2.2.1.1.5 = INTEGER: 5
.1.3.6.1.2.1.2.2.1.1.6 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.1.7 = INTEGER: 7
.1.3.6.1.2.1.2.2.1.2.1 = STRING: "lo"
.1.3.6.1.2.1.2.2.1.2.2 = STRING: "ath1"
.1.3.6.1.2.1.2.2.1.2.3 = STRING: "ath0"
.1.3.6.1.2.1.2.2.1.2.4 = STRING: "wifi0"
.1.3.6.1.2.1.2.2.1.2.5 = STRING: "br0"
.1.3.6.1.2.1.2.2.1.2.6 = STRING: "eth0"
.1.3.6.1.2.1.2.2.1.2.7 = STRING: "wifi1"
.1.3.6.1.2.1.2.2.1.3.1 = INTEGER: 24
.1.3.6.1.2.1.2.2.1.3.2 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.3.3 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.3.4 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.3.5 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.3.6 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.3.7 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.4.1 = INTEGER: 16436
.1.3.6.1.2.1.2.2.1.4.2 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.4.3 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.4.4 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.4.5 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.4.6 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.4.7 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.5.1 = Gauge32: 4294967295
.1.3.6.1.2.1.2.2.1.5.2 = Gauge32: 4294967295
.1.3.6.1.2.1.2.2.1.5.3 = Gauge32: 4294967295
.1.3.6.1.2.1.2.2.1.5.4 = Gauge32: 4294967295
.1.3.6.1.2.1.2.2.1.5.5 = Gauge32: 4294967295
.1.3.6.1.2.1.2.2.1.5.6 = Gauge32: 4294967295
.1.3.6.1.2.1.2.2.1.5.7 = Gauge32: 4294967295
.1.3.6.1.2.1.2.2.1.6.1 = ""
.1.3.6.1.2.1.2.2.1.6.2 = Hex-STRING: 44 D9 E7 92 3B 6C 
.1.3.6.1.2.1.2.2.1.6.3 = Hex-STRING: 44 D9 E7 91 3B 6C 
.1.3.6.1.2.1.2.2.1.6.4 = ""
.1.3.6.1.2.1.2.2.1.6.5 = Hex-STRING: 44 D9 E7 90 3B 6C 
.1.3.6.1.2.1.2.2.1.6.6 = Hex-STRING: 44 D9 E7 90 3B 6C 
.1.3.6.1.2.1.2.2.1.6.7 = ""
.1.3.6.1.2.1.2.2.1.7.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.7.2 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.7.3 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.7.4 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.7.5 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.7.6 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.7.7 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.2 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.3 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.4 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.5 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.6 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.7 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.9.1 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.9.2 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.9.3 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.9.4 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.9.5 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.9.6 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.9.7 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.10.1 = Counter32: 1264
.1.3.6.1.2.1.2.2.1.10.2 = Counter32: 979467696
.1.3.6.1.2.1.2.2.1.10.3 = Counter32: 281058466
.1.3.6.1.2.1.2.2.1.10.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.10.5 = Counter32: 96968617
.1.3.6.1.2.1.2.2.1.10.6 = Counter32: 2391635815
.1.3.6.1.2.1.2.2.1.10.7 = Counter32: 0
.1.3.6.1.2.1.2.2.1.11.1 = Counter32: 16
.1.3.6.1.2.1.2.2.1.11.2 = Counter32: 7397883
.1.3.6.1.2.1.2.2.1.11.3 = Counter32: 1705719
.1.3.6.1.2.1.2.2.1.11.4 = Counter32: 36935032
.1.3.6.1.2.1.2.2.1.11.5 = Counter32: 1092303
.1.3.6.1.2.1.2.2.1.11.6 = Counter32: 17816601
.1.3.6.1.2.1.2.2.1.11.7 = Counter32: 0
.1.3.6.1.2.1.2.2.1.12.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.12.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.12.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.12.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.12.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.12.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.12.7 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.2 = Counter32: 6099
.1.3.6.1.2.1.2.2.1.13.3 = Counter32: 464
.1.3.6.1.2.1.2.2.1.13.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.7 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.2 = Counter32: 6099
.1.3.6.1.2.1.2.2.1.14.3 = Counter32: 464
.1.3.6.1.2.1.2.2.1.14.4 = Counter32: 1015091
.1.3.6.1.2.1.2.2.1.14.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.7 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.7 = Counter32: 0
.1.3.6.1.2.1.2.2.1.16.1 = Counter32: 1264
.1.3.6.1.2.1.2.2.1.16.2 = Counter32: 3384792333
.1.3.6.1.2.1.2.2.1.16.3 = Counter32: 3285809309
.1.3.6.1.2.1.2.2.1.16.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.16.5 = Counter32: 174639537
.1.3.6.1.2.1.2.2.1.16.6 = Counter32: 1498864025
.1.3.6.1.2.1.2.2.1.16.7 = Counter32: 0
.1.3.6.1.2.1.2.2.1.17.1 = Counter32: 16
.1.3.6.1.2.1.2.2.1.17.2 = Counter32: 14263743
.1.3.6.1.2.1.2.2.1.17.3 = Counter32: 2597771
.1.3.6.1.2.1.2.2.1.17.4 = Counter32: 15205864
.1.3.6.1.2.1.2.2.1.17.5 = Counter32: 1060489
.1.3.6.1.2.1.2.2.1.17.6 = Counter32: 10113102
.1.3.6.1.2.1.2.2.1.17.7 = Counter32: 0
.1.3.6.1.2.1.2.2.1.18.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.18.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.18.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.18.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.18.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.18.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.18.7 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.2 = Counter32: 10
.1.3.6.1.2.1.2.2.1.19.3 = Counter32: 49
.1.3.6.1.2.1.2.2.1.19.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.7 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.2 = Counter32: 12420
.1.3.6.1.2.1.2.2.1.20.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.4 = Counter32: 161877
.1.3.6.1.2.1.2.2.1.20.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.7 = Counter32: 0
.1.3.6.1.2.1.2.2.1.21.1 = Gauge32: 0
.1.3.6.1.2.1.2.2.1.21.2 = Gauge32: 0
.1.3.6.1.2.1.2.2.1.21.3 = Gauge32: 0
.1.3.6.1.2.1.2.2.1.21.4 = Gauge32: 4095
.1.3.6.1.2.1.2.2.1.21.5 = Gauge32: 0
.1.3.6.1.2.1.2.2.1.21.6 = Gauge32: 1000
.1.3.6.1.2.1.2.2.1.21.7 = Gauge32: 4095
.1.3.6.1.2.1.2.2.1.22.1 = OID: .0.0
.1.3.6.1.2.1.2.2.1.22.2 = OID: .0.0
.1.3.6.1.2.1.2.2.1.22.3 = OID: .0.0
.1.3.6.1.2.1.2.2.1.22.4 = OID: .0.0
.1.3.6.1.2.1.2.2.1.22.5 = OID: .0.0
.1.3.6.1.2.1.2.2.1.22.6 = OID: .0.0
.1.3.6.1.2.1.2.2.1.22.7 = OID: .0.0
.1.3.6.1.2.1.11.1.0 = Counter32: 832466
.1.3.6.1.2.1.11.2.0 = Counter32: 832435
.1.3.6.1.2.1.11.3.0 = Counter32: 6
.1.3.6.1.2.1.11.4.0 = Counter32: 24
.1.3.6.1.2.1.11.5.0 = Counter32: 0
.1.3.6.1.2.1.11.6.0 = Counter32: 0
.1.3.6.1.2.1.11.8.0 = Counter32: 0
.1.3.6.1.2.1.11.9.0 = Counter32: 0
.1.3.6.1.2.1.11.10.0 = Counter32: 0
.1.3.6.1.2.1.11.11.0 = Counter32: 0
.1.3.6.1.2.1.11.12.0 = Counter32: 0
.1.3.6.1.2.1.11.13.0 = Counter32: 38227
.1.3.6.1.2.1.11.14.0 = Counter32: 0
.1.3.6.1.2.1.11.15.0 = Counter32: 161454
.1.3.6.1.2.1.11.16.0 = Counter32: 671006
.1.3.6.1.2.1.11.17.0 = Counter32: 0
.1.3.6.1.2.1.11.18.0 = Counter32: 0
.1.3.6.1.2.1.11.19.0 = Counter32: 0
.1.3.6.1.2.1.11.20.0 = Counter32: 0
.1.3.6.1.2.1.11.21.0 = Counter32: 515498
.1.3.6.1.2.1.11.22.0 = Counter32: 0
.1.3.6.1.2.1.11.24.0 = Counter32: 0
.1.3.6.1.2.1.11.25.0 = Counter32: 0
.1.3.6.1.2.1.11.26.0 = Counter32: 0
.1.3.6.1.2.1.11.27.0 = Counter32: 0
.1.3.6.1.2.1.11.28.0 = Counter32: 832436
.1.3.6.1.2.1.11.29.0 = Counter32: 0
.1.3.6.1.2.1.11.30.0 = INTEGER: 2
.1.3.6.1.2.1.11.31.0 = Counter32: 0
.1.3.6.1.2.1.11.32.0 = Counter32: 0`

**Comment by murrant** [comment]
You will need to `snmpwalk .` to include the vendor specific data.

**Comment by TyShawn76** [comment]
I'm waiting on @Rosiak to help me with that output, unless you know the command I would need to provide that data.

**Comment by TyShawn76** [comment]
Do these help at all?

I ran this command
`snmpbulkwalk -v2c -c xxxxxxxx -OQUs -m UBNT-UniFi-MIB -M /opt/librenms/mibs udp:10.X.X.2:161 .`
`Timeout: No Response from udp:10.X.X.2:161`

Then I ran.

` snmpbulkwalk -v1 -c xxxxxxxxx -OQUs -m UBNT-MIB -M /opt/librenms/mibs udp:10.X.X.2:161 .`
`snmpbulkwalk: Cannot send V2 PDU on V1 session (Sub-id not found: (top) -> )`



[Archive.zip](https://github.com/librenms/librenms/files/453342/Archive.zip)

**Comment by TyShawn76** [comment]
[SNMPWalk.txt](https://github.com/librenms/librenms/files/453879/SNMPWalk.txt)

**Comment by jquagga** [comment]
In case it helps, I ran the same snmpwalk command as @TyShawn76.  However this is on a AC-Pro Gen 2 running the latest production firmware (it's no longer in beta).  


[snmpwalk.txt](https://github.com/librenms/librenms/files/493252/snmpwalk.txt)

**Comment by ekoyle** [comment]
From your snmpwalk output, it looks like these also use IEEE802dot11-MIB

**Comment by TyShawn76** [comment]
It does look like its using that MIB as well.

**Comment by jquagga** [comment]
Here's a snmpwalk including the IEEE802dot11-MIB.  
[snmpwalk.txt](https://github.com/librenms/librenms/files/508460/snmpwalk.txt)

**Comment by TyShawn76** [comment]
@jquagga Just to verify when you ran your poll you had three devices connected to your AP?

UBNT-UniFi-MIB::unifiVapNumStations.0 = INTEGER: 0
UBNT-UniFi-MIB::unifiVapNumStations.1 = INTEGER: 3

**Comment by jquagga** [comment]
Yep, 3 on 5Ghz, 0 on the 2.4. 

The house has 3 APs. Usually only devices in the playroom connect to that AP. I had an iPhone and 2 laptops while polling. 

The AP also has one device connected on the Secondary LAN port and bridged in, but thata not reported here I don't believe.

**Comment by TyShawn76** [comment]
GREAT!! I wanted to verify I was looking at the right lines, what command did you run to get that output?

**Comment by jquagga** [comment]
The same as you except -m +ALL after adding the UBNT mibs and all of librenms's MIBs to my local SNMP directory. And I did a > snmpwalk.txt at the end to filter out the error messages and get a cleaner text file.

**Comment by jquagga** [comment]
I would imagine the desire here is to have full mib support the same way airfiber/airmax do.  However, it is possible to configure the normal wifi poller to poll a couple of SNMP oids and get the client counts on the 2.4/5GHZ basestations.  

I essentially re-purposed the code in the file for symbol devices and set it to poll unifi os's.  This probably isn't usable without a conditional check.  I would think if these oids return blank (as it would for unifi switches / routers / Gen1 UAPs) then this should be skipped.  

```diff
diff --git a/includes/polling/wifi.inc.php b/includes/polling/wifi.inc.php
index 3159978..3d413b9 100644
--- a/includes/polling/wifi.inc.php
+++ b/includes/polling/wifi.inc.php
@@ -61,8 +61,18 @@ if ($device['type'] == 'network' || $device['type'] == 'firewall' || $device['ty
         $wificlients1 = snmp_get($device, '.1.3.6.1.4.1.388.11.2.4.2.100.10.1.18.1', '-Ovq', '""');
 
         echo (($wificlients1 + 0).' clients on wireless connector, ');
+    } else if ($device['os'] == 'unifi') {
+        echo 'Checking Unifi Wireless clients... ';
+
+        $wificlients1 = snmp_get($device, '.1.3.6.1.4.1.41112.1.6.1.2.1.8.0', '-Ovq', '""');
+        $wificlients2 = snmp_get($device, '.1.3.6.1.4.1.41112.1.6.1.2.1.8.1', '-Ovq', '""');
+
+        echo (($wificlients1 + 0).' clients on radio0, '.($wificlients2 + 0)." clients on radio1\n");
+
     }
 
+
+
     if (isset($wificlients1) && $wificlients1 != '') {
         $tags = array(
             'rrd_def'   => 'DS:wificlients:GAUGE:600:-273:1000',
```

**Comment by laf** [comment]
That's perfectly fine :) If you can submit a PR that would be ace.

**Comment by TyShawn76** [comment]
Gen 1 APs also will return data it was added a couple of days after the Gen 2 info released.

**Comment by TyShawn76** [comment]
Something is a little strange. On the UAP AC Pro I see the 2.4 band but nothing on the 5G. On my Lite I see both bands.

AC Pro
![screen shot 2016-10-12 at 6 08 20 am](https://cloud.githubusercontent.com/assets/21324034/19306218/9be95f2e-9042-11e6-954e-46f6548f4699.png)
![graph php](https://cloud.githubusercontent.com/assets/21324034/19306222/a1c69d26-9042-11e6-8eb0-7d450f247427.png)

AC Lite
![screen shot 2016-10-12 at 6 09 17 am](https://cloud.githubusercontent.com/assets/21324034/19306230/acd1fc56-9042-11e6-89e3-f22d541de0a4.png)
![graph-1 php](https://cloud.githubusercontent.com/assets/21324034/19306234/b365d36c-9042-11e6-8f7c-3e16c01b906c.png)

**Comment by jquagga** [comment]
You have more than one SSiD configured correct?  I determined after I put that code together it'll work for 1 SSID. If you have more than one, it needs more logic behind it. I was going to try and fix it if I have time

**Comment by jquagga** [comment]
So let me write down what I think would be the solution to this but it's beyond my ability to code.  

Ubiquiti reports clients on a SSID/radio basis.  The existing code assumed one VAP so .1.3.6.1.4.1.41112.1.6.1.2.1.8.0 is the 2.4ghz and .1.3.6.1.4.1.41112.1.6.1.2.1.8.1 is the 5Ghz.  However if you have say two SSID, then .0 is 2.4ghz - SSID 1, and .1 is 2.4ghz - SSID 2.  There would be a .2 and .3 which would have the 5ghz SSID 1 and SSID 2 entries.  Unifi supports up to 4 SSID so that's 8 total oids (one for each band).  

What I think could work is to snmpget .1.3.6.1.4.1.41112.1.6.1.2.1.9.$index which will have a value of "ng" or "na" (2.4 or 5ghz).  Then assign the value of .1.3.6.1.4.1.41112.1.6.1.2.1.8.$index to either $wificlients1 or $wificlients2 depending on the value of 1.3.6.1.4.1.41112.1.6.1.2.1.9.$index.  The .9 oid is the band, .8 is the number of clients.

**Comment by TyShawn76** [comment]
Thats correct I have a main and guest network on the AC Pro.

**Comment by jquagga** [comment]
I have a pull request pending which should correct the client counts. #4794 I've also coded up the shell of mib parsing for the channel utilisation mib polling and graphing. I'm remote today but hopefully I can test that over the weekend and get a PR filed for that as well.

**Comment by jquagga** [comment]
Ok, so here's where I'm at now and probably need someone else's input.  MIB polling of the Wireless Capacity works great.  Graphing doesn't work through libreNMS and that's what I think I need some help working on.  

[This gist has the patch as I have it now.](https://gist.github.com/jquagga/714b4add942472734339da3356d183ef)  It's not ready for a PR since the graphing doesn't work in browser.  However I believe from the poller output, the rrdfiles, and the graphs I generate outside of Librenms that the polling is working great.  The patch adds the Unifi MIB, and polls it for 8 oids related to Wireless Capacity (Total, Used by Others, Self TX and Self RX) x 2 since there are two radios.  I then try to generate two graphs, one per radio. 

Manually with rrdtool I can generate this:

![graph](https://cloud.githubusercontent.com/assets/5832772/19438890/ed5cb436-9449-11e6-8321-47838ae83bc6.png)

That's generated by:
```bash
rrdtool graph 'graph1.png' \
--width '400' \
--height '100' \
--start end-1d \
-u 100 -l 0 -r \
'DEF:Others=ubnt-unifi-mib.rrd:Radio0OtherBss:LAST' \
'DEF:SelfRX=ubnt-unifi-mib.rrd:Radio0CuSelfRx:LAST' \
'DEF:SelfTX=ubnt-unifi-mib.rrd:Radio0CuSelfTx:LAST' \
'AREA:Others#FF3333:Others' \
'STACK:SelfRX#0066FF:SelfRX' \
'STACK:SelfTX#00FFFF:SelfTX'
```

And that looks about right from the data I'm getting from SNMP (yes, SelfTX is always tiny compared to RX on any band - not sure why that is).  

I've tried two different ways to graph.  RadioCU_0 is using essentially a modified graphing strategy from Airfiber.  For RadioCU_1, I tried to use @murrant's generic_multi.inc.php but clearly I'm missing something.  Neither graph generates in libreNMS.

**Comment by laf** [comment]
Best posting the debug output from the show rrdtool command in the webui for the graphs.

**Comment by jquagga** [comment]
Strangely when I do that, all I get is this strange square.  I'm guessing that means rrdtool isn't called at all, but I'm not sure why.  
![screenshot](https://cloud.githubusercontent.com/assets/5832772/19439411/f2e3e01c-944b-11e6-9e59-fdcab90b94ec.png)

**Comment by murrant** [comment]
This usually means there was a php error or something.
