### ISSUE TITLE
Syslog coloring rules

### ISSUE THREAD

**Issue by realnakrul** [librenms/librenms#4270]
Hi
Most of my experience with network monitoring comes from Solarwinds. So I have one suggestion. Is it possible to color syslog messages according to severity level? Something like that:
![clipboard_e85f032f7e2b4a7bb6f57cf70733edaee](https://cloud.githubusercontent.com/assets/21193002/18079515/43e1e3ee-6ea2-11e6-8417-7c6c84a5ae5c.png)
Now LibreNMS uses small icons, but they are not catch the eye as color and it is easy to miss something important. Of course I can use filter, but it is a different story

**Comment by laf** [comment]
Should be easy enough yes.

**Comment by laf** [comment]
Something like this:

![image](https://cloud.githubusercontent.com/assets/3941142/18108007/459e167a-6f02-11e6-8547-f009ef4c70a1.png)

**Comment by realnakrul** [comment]
Exactly, may be with some more colors (yellow for Warning (4) severity)

**Comment by laf** [comment]
It was just an example :) I don't use syslog so just chucked some junk in quickly.
