### ISSUE TITLE
Feature Request: Availability Map - Filter based on Device Groups, and custom Title

### ISSUE THREAD

**Issue by ErnstVS** [librenms/librenms#4275]
It would be nice if it was possible to filter results in the availability map to match the Device Groups.

It would also be really great if you could give the widget a custom title to match what set of devices it contained.

Thanks in advance.

**Comment by Rosiak** [comment]
@crcro Anything you would like to work on? :)

**Comment by crcro** [comment]
@Rosiak ... i will take a look for device groups, but for custom title i don't see any widget supporting this

**Comment by Rosiak** [comment]
@crcro Generic graph widgets support afaik.

**Comment by crcro** [comment]
@Rosiak ... this can be closed?

**Comment by Rosiak** [comment]
I guess the custom title part is still to-be-done.

**Comment by ErnstVS** [comment]
@crcro 

Just a quick question, where do i select what device-group to use on the map ? 

I tried editing my map but still only have title and show - it is enabled in global settings and im running version 58599e9 - Tue Sep 06 2016 19:00:05 GMT+0200

Thanks in advance.
Ernst

**Comment by laf** [comment]
The pr referencing this request hasn't been merged yet.

**Comment by ErnstVS** [comment]
Thanks laf, that explains why :)

**Comment by smounives** [comment]
Availability map for services can't use Filter, can you add this feature?
