### ISSUE TITLE
AD auth - userPrincipalName

### ISSUE THREAD

**Issue by mzac** [librenms/librenms#4281]
In the current active_directory.inc.php, there seems to be only support for sAMAccountName, would it be possible to also add userPrincipalName?  This could be selected in the config with an option such as:

$config['auth_ad_uid']            = "userPrincipalName";
or
$config['auth_ad_uid']            = "SAMAccountName";

**Comment by murrant** [comment]
@mzac what is the reason you would want to use userPrincipalName over SAMAccountName?

I'd rather we just switch to UPN, if it is desirable, than add an option.

**Comment by mzac** [comment]
In our organization we are trying to standardize on logins to our different systems and userPrincipalName has become the popular option.  Also, our UPN and SAN are not the same they are like this:

UPN: first.last@domain.com
SAN: domain\flast

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-ad-auth-userprincipalname/720

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/ad-auth-userprincipalname/11333/1
