### ISSUE TITLE
new added device not showing description from edit 

### ISSUE THREAD

**Issue by allano337** [librenms/librenms#4284]
#### Please note

> Please read this information carefully.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ x] Please provide as much detail as possible.

I manually added a Sonus Networks device and when you look at the devices on web GUI the device has the IP and then under it is the description you give the device in edit. the newly added Sonus device 
I let it lnms run over night and it still didn't propagate. I deleted it and waited then added it back and it still won't put the description in
![screenshot007](https://cloud.githubusercontent.com/assets/20955418/18100682/ca78e2ce-6ea0-11e6-8e3a-2ab2400aa611.jpg)

[poller core debug for Sonus Networks device.txt](https://github.com/librenms/librenms/files/445558/poller.core.debug.for.Sonus.Networks.device.txt)

**Comment by allano337** [comment]
looking at other devices the description in the edit looks to be changed as system name which isn't being updated/applied for the Sonus Networks device

**Comment by laf** [comment]
That was an easy one, your device isn't returning a sysName:

`sysName.0 =`

That's what we use to show the second line.

**Comment by allano337** [comment]
oh man, guess I need to get the Sonus engineer to do it properly, I thought it was tied to the description as I was putting the name there on other devices, but now see the error of my way! thx again

**Comment by allano337** [comment]
we can close this
