### ISSUE TITLE
URL rewrite problems with mysql application

### ISSUE THREAD

**Issue by shockre** [librenms/librenms#4288]
My installation is up to date:

Version info:
Commit SHA: f59cfa3b17c58998857ca43d6a5507f7edc09044
DB Schema: 131
PHP: 7.0.10
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2

=

I've enabled unix-agent module and added mysql application to several hosts.
The graphs are showing fine, no problems there, but when, for example, click on 'queries' or 'innodb' tab, the graphs don't show because the rewrite is wrong.

This is the starting URL for mysql app:
http://librenms.foo.boo/device/device=17/tab=apps/

This I get when I clik on queries:
http://librenms.foo.boo/device/device=17/tab=apps//device/device=17%2Ftab%3Dapps%2F/app=mysql/app_section=queries/

And this one is the correct URL:
http://librenms.foo.boo/device/device=17/tab=apps/app=mysql/app_section=queries/

Here is my nginx conf (taken from the official page):

server {
 listen      80;
 server_name librenms.foo.boo;
 root        /opt/librenms/html;
 access_log  /opt/librenms/logs/access_log;
 error_log   /opt/librenms/logs/error_log;
 location / {
  try_files $uri $uri/ @librenms;
 }
 location ~ \.php$ {
  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  include fastcgi_params;
  fastcgi_split_path_info ^(.+\.php)(/.+)$;
  fastcgi_pass unix:/var/run/php-fpm.sock;
 }
 location ~ /\.ht {
  deny all;
 }
 location @librenms {
  rewrite api/v0(.*)$ /api_v0.php/$1 last;
  rewrite ^(.+)$ /index.php?$1 last;
 }
}

It would be great to access all the graphs just by clicking and not editing the URL to be able to view the graphs :)

Thank you in advance.

**Comment by laf** [comment]
I can't replicate this.

Even on demo: https://demo.librenms.org/device/device=1/tab=apps/app=mysql/app_section=queries/

**Comment by laf** [comment]
Actually looking at your config your rewrite isn't as our install docs. Please re-check.

**Comment by shockre** [comment]
Damn my eyes, I had 'location ~ .php$' with the extra '$'.
Somehow slipped my sight, its working fine now.
Thank you and sorry to waste your time.
