### ISSUE TITLE
Cisco ASA Remote Access Sessions graph has wrong informations

### ISSUE THREAD

**Issue by FTBZ** [librenms/librenms#4293]
Cacti graph:
![cacti-asa](https://cloud.githubusercontent.com/assets/1927109/18130210/6409bbbe-6f8e-11e6-93fb-81f8acafe566.png)

LibreNMS graph:
![librenms-asa](https://cloud.githubusercontent.com/assets/1927109/18130225/7129681c-6f8e-11e6-933b-b3e97490aa8c.png)

- The values appear inverted between "SSLVPN Tunnels" and "Clientless VPN"
 - Note that Cisco named this "Annyconnect Client" and "Clientless SSL VPN" in recent ASDM version
- Numbers with point is not possible
- Negative values are not possible

**Comment by Rosiak** [comment]
I've seen the same weirdness.
