### ISSUE TITLE
Cisco Wireless LAN Controller add ability to graph by SSID

### ISSUE THREAD

**Issue by FTBZ** [librenms/librenms#4294]
LibreNMS graphs only the total clients for all SSID:
![graph php](https://cloud.githubusercontent.com/assets/1927109/18130701/62c69a9a-6f90-11e6-94e1-7b49c6ad380d.png)
- Cacti can graph all SSDI individually, if LibreNMS take only the number of clients by SSID it can be on the same graph. Cacti uses multiple graphs because it's showing many other information like association status and blacklisting.
- IMO, radio1 is a wrong information but not sure.
  - On the WLC GUI, Cisco uses "Active Clients" and "Number of Clients"

**Comment by FTBZ** [comment]
Found more information, a method to get this information is to :

**- Get a list of all SSID association:** 

`snmpwalk -v 2c -c COMMUNITY WLC 1.3.6.1.4.1.14179.2.1.4.1.7`

**- It will return a string for each association with the SSID name:**

```
SNMPv2-SMI::enterprises.14179.2.1.4.1.7.0.27.99.20.176.137 = STRING: "SSID1"

SNMPv2-SMI::enterprises.14179.2.1.4.1.7.0.109.82.45.174.110 = STRING: "SSID2"

SNMPv2-SMI::enterprises.14179.2.1.4.1.7.0.109.82.243.110.102 = STRING: "SSID1"

SNMPv2-SMI::enterprises.14179.2.1.4.1.7.0.136.101.73.76.228 = STRING: "SSID1"

SNMPv2-SMI::enterprises.14179.2.1.4.1.7.8.109.65.224.87.106 = STRING: "SSID3"

```

Now the question is, what's the best way to store these information and to graph them? Can we add a loop parsing all lines that will increment a counter?

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-cisco-wireless-lan-controller-add-ability-to-graph-by-ssid/719
