### ISSUE TITLE
Cisco Wireless LAN Controller add ability to graph by number of AP

### ISSUE THREAD

**Issue by FTBZ** [librenms/librenms#4295]
LibreNMS has an Access Point submenu when adding a Cisco WLC. It's showing individual information from each AP. It's really great, but a missing feature will be to have a new graph, showing the total number of AP online.

**Comment by network-guy** [comment]
It does graph the total number of APs, and presumably it only supplies the number of APs that are online.

**Comment by FTBZ** [comment]
hu, where? I checked all menus and didn't see a single graph indicating the total number of AP from this WLC.

**Comment by PENorris** [comment]
Right here. 
![capture](https://cloud.githubusercontent.com/assets/16704208/18596284/60ab76bc-7c16-11e6-9adb-6c4339c9bc91.PNG)

**Comment by FTBZ** [comment]
Thanks! @Rosiak has shown me this on IRC. This graph must be added to the wireless page, but the source code for WLC seems to have some problem to solve before adding it to a better page.

Has example, the "Number of clients" graph presents on this page is not the same has the "Number of clients" graph on the wireless page. It's using two different RRD files without exactly the same value.

**Comment by laf** [comment]
Is this now fixed for you?

**Comment by laf** [comment]
You didn't need to go off and do it @murrant :)

**Comment by murrant** [comment]
Trying to fill out wireless sensor types :-)
