### ISSUE TITLE
Infoblox DNS Performance graph returns no metrics

### ISSUE THREAD

**Issue by FTBZ** [librenms/librenms#4299]
The Infoblox DNS Performance graph is returning no metrics. The DHCP messages graph is working fine, but not DNS Performance:

![graph](https://cloud.githubusercontent.com/assets/1927109/18142103/6043f98a-6fbc-11e6-8d75-af8c21df4b37.png)

**Comment by Rosiak** [comment]
Talked with @FTBZ , no bugs everything works as intended :)
Closing as agreed.
