### ISSUE TITLE
Arista EOS Watts to dbm conversion for usable graphs

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#4302]
Exactly like #1661
 just for `$os = 'arista_eos';`

**Comment by f0o** [comment]
Clearing assignment due to time issue

**Comment by Rosiak** [comment]
Got any data?

**Comment by rasssta** [comment]
Yes. I have a walk. Where do you want it?

**Comment by laf** [comment]
pastebin the link here pls.

**Comment by laf** [comment]
Ideally: `snmpbulkwalk -Onet -v2c -c COMMUNITY HOSTNAME .`

**Comment by rasssta** [comment]
too much text for pastebin. any other options?

**Comment by rasssta** [comment]
[arista.walk.txt](https://github.com/librenms/librenms/files/518578/arista.walk.txt)

**Comment by rasssta** [comment]
There you go. Some stuff has been censored but the important stuff is still there.
