### ISSUE TITLE
add logo network devices 

### ISSUE THREAD

**Issue by divelgrom** [librenms/librenms#4303]
Hi. please add logo for network devices of vendor "opzoon"

**Comment by Rosiak** [comment]
Hi @divelgrom 
Please follow the instructions listed in the issue template.

<img width="657" alt="screen shot 2016-09-01 at 12 29 07" src="https://cloud.githubusercontent.com/assets/6378934/18164355/b83e7dda-703f-11e6-8a0c-8f10b6bf6732.png">

**Comment by crcro** [comment]
@divelgrom i don't see any opzoon devices in the definitions. please provide as @Rosiak indicated the data required for adding the opzoon support

**Comment by Rosiak** [comment]
No response, closing.
