### ISSUE TITLE
Billing

### ISSUE THREAD

**Issue by search4u2003** [librenms/librenms#4304]
# 

Version info:
Commit SHA: 60332cd919ec59cb3413030692b50b3bda1657b4
[WARN]    Your local git branch is not master, this will prevent automatic updates.
DB Schema: 130
PHP: 7.0.9
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2
# 

[OK]      Database connection successful

Billing seems to work fine, however as the month changed overnight, billing for new month i.e. for september 2016 billing is not working, I see zero traffic in Inbound and Outbound

Also in  event log TYPE is showing null, whereas previously it was showing system or network device name, below is the error found in event log.

2016-09-01 19:38:01 shared  NULL    Could not issue critical alert for rule 'Service up/down' to transport 'mail' Error: You must provide at least one recipient email address.

**Comment by laf** [comment]
I'm pretty certain billing takes until the next day to start showing so please re-check on the 2nd. 

With regards to your other issue in here. Please create a separate issue.

**Comment by search4u2003** [comment]
Thx Laf will do the same.

**Comment by search4u2003** [comment]
Laf billing section is still in same state nothing is happening.

**Comment by Rosiak** [comment]
Had reports from @Mattz0r , @vectr0n another bloke on IRC - regarding issue with billing.

**Comment by vectr0n** [comment]
It's fine, doesn't seem to update till the 2nd day as @laf mentioned above.

**Comment by laf** [comment]
@search4u2003 have you checked again on the 2nd - well that is if you've set the 1st to be the start of a new billing month.

**Comment by search4u2003** [comment]
Yes I have checked on 2nd Inbound and outbound traffic is showing 0, whereas total is being calculated correctly.

**Comment by laf** [comment]
I've tested this and still can't see an issue.

Please post screenshot of the /bills/ page.

**Comment by search4u2003** [comment]
As requested find the screenshot of /bills/ page.
![bills](https://cloud.githubusercontent.com/assets/18137450/18344043/612ab4de-75d3-11e6-96d5-9bf792d22b32.gif)

**Comment by search4u2003** [comment]
As requested find the screenshot of /bills/ page.
![Uploading Bills.gif…]()

**Comment by laf** [comment]
Is this still an issue?

**Comment by laf** [comment]
No further response provided
