### ISSUE TITLE
Event Log

### ISSUE THREAD

**Issue by search4u2003** [librenms/librenms#4307]
====================================
Version info:
Commit SHA: 60332cd919ec59cb3413030692b50b3bda1657b4
[WARN]    Your local git branch is not master, this will prevent automatic updates.
DB Schema: 130
PHP: 7.0.9
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2

====================================
[OK]      Database connection successful

In event log TYPE is showing null, whereas previously it was showing system or network device name, below is the error found in event log.

2016-09-01 19:38:01 shared NULL Could not issue critical alert for rule 'Service up/down' to transport 'mail' Error: You must provide at least one recipient email address.

Cisco ASR ethernet  port has been administratively shutdown, however we keep on getting notification of port up and down in evetenlog.

**Comment by search4u2003** [comment]
![libre_email_settings](https://cloud.githubusercontent.com/assets/18137450/18206844/1fe33b7c-7146-11e6-88f6-cc617ba0e2dd.gif)
![libre_general_settings](https://cloud.githubusercontent.com/assets/18137450/18206845/1fe5e638-7146-11e6-98d6-4e0ec52fb4ed.gif)

Find the General as well as email settings.

**Comment by laf** [comment]
If this is for an alert that was triggered before you added a default email then turn on updates to contact email addresses not honoured.

**Comment by search4u2003** [comment]
yes

**Comment by laf** [comment]
Yes what?

**Comment by search4u2003** [comment]
alert was triggered before i had added the default email.

**Comment by laf** [comment]
Have you now enabled the option I said about then?

**Comment by search4u2003** [comment]
yes i did enabled the option

**Comment by laf** [comment]
Then you should no longer have the issue.

**Comment by search4u2003** [comment]
I created a test server where the emails are getting triggered to mail transport.

However when I restore DB of my existing setup, issue related to mail transport continues, it seems some data related table is not getting updated because of which this issue is been observed in live setup.

**Comment by laf** [comment]
So the only difference between your live and test setup is the DB? Unless you are missing tables then this is most likely a config option. You'll need to compare between the two to check

**Comment by search4u2003** [comment]
Dear Laf, 

I have reconfigured Librenms from scratch, this time I added the default contact before the alert was triggered but then too alerts are not getting generated i have attached the Email and General Settings screen shot for your reference.
![libre_email_settings](https://cloud.githubusercontent.com/assets/18137450/18416018/85f73492-7824-11e6-9fab-c7aa28046b05.gif)
![libre_general_settings](https://cloud.githubusercontent.com/assets/18137450/18416019/85fe637a-7824-11e6-9058-214239816c42.gif)

**Comment by laf** [comment]
And what does the eventlog say?

You know you still have to configure sendmail on your server? That's out of scope for us but you need to have a fully functioning /usr/sbin/sendmail.

**Comment by laf** [comment]
No further info provided.
