### ISSUE TITLE
snmp simulator

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#431]
http://snmpsim.sourceforge.net/simulation-based-on-mibs.html
Maybe we can simulator data like this, but I only simulator with the example:
```
mib2dev.py --mib-module=SNMPv2-MIB --start-oid=1.3.6.1.2.1.1.1 
--stop-oid=1.3.6.1.2.1.1.8
```
If I want simulator a cisco device, what should I do ?  
Thank you !

**Comment by f0o** [comment]
Hi,

I would use GNS3 to create a couple of cisco devices on my network.

It's not really simulating but more like emulating.

**Comment by laf** [comment]
That  looks pretty interesting :)

**Comment by wzhsunn** [comment]
YES, very pretty interesting :).
