### ISSUE TITLE
No image

### ISSUE THREAD

**Issue by Setsuneh** [librenms/librenms#4310]
Hi,

I've just installated LibreNMS on a new VPS. No problem, but no images on index, or others pages. Can I resolve this problem?

Version info:
Commit SHA: f278a9281cf769b679b09c4fedbb41e2ca6a5b84
DB Schema: 118
PHP: 7.0.10-1~dotdeb+8.1
MySQL: 10.1.17-MariaDB-1~jessie
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2.1

Thanks ! :)

**Comment by crcro** [comment]
please paste the ./validate.php output

**Comment by Setsuneh** [comment]
Already posted :)

`./validate.php
====================================
Version info:
Commit SHA: f278a9281cf769b679b09c4fedbb41e2ca6a5b84
DB Schema: 118
PHP: 7.0.10-1~dotdeb+8.1
MySQL: 10.1.17-MariaDB-1~jessie
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2.1

====================================
[OK]      Database connection successful`

**Comment by laf** [comment]
Set `$config['base_url'] = '/';` or set it to your full url.

**Comment by laf** [comment]
Feel free to reply back if you need any further help

**Comment by alanbouz** [comment]
thanks @laf this is works for me!
