### ISSUE TITLE
Add logo for Foundry Networks switches

### ISSUE THREAD

**Issue by allano337** [librenms/librenms#4311]
Please add logo for Foundry Networks equipment, logo and discovery & poller of 4802 & 2402 equipment.

#### Please note

> Please read this information carefully.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x ] Please provide as much detail as possible.

![logo-foundry](https://cloud.githubusercontent.com/assets/20955418/18186894/4e0dc270-705a-11e6-9b7c-749e70bcfe70.gif)

[foundry 4802 discovery.txt](https://github.com/librenms/librenms/files/450853/foundry.4802.discovery.txt)
[foundry 4802 poller.txt](https://github.com/librenms/librenms/files/450852/foundry.4802.poller.txt)
[foundry 2402 discovery.txt](https://github.com/librenms/librenms/files/450854/foundry.2402.discovery.txt)
[foundry 2402 poller.txt](https://github.com/librenms/librenms/files/450855/foundry.2402.poller.txt)

**Comment by crcro** [comment]
logo should be 32x32px ... i couldn't find anything remotely that can be used for foundry networks

**Comment by allano337** [comment]
I took the logo and made it 32x16, will that work?

![logo-foundry 32x16](https://cloud.githubusercontent.com/assets/20955418/18218383/1f366e08-7117-11e6-9ffe-e600cbaa039c.jpg)

**Comment by Rosiak** [comment]
I've added a logo in the PR, so I guess that'll do for now.

**Comment by crcro** [comment]
@Rosiak ... mad cutting skill 👍
