### ISSUE TITLE
undefined function rrdtool_pipe_open() in /opt/librenms/scripts/tune_port.php

### ISSUE THREAD

**Issue by pereljon** [librenms/librenms#4314]
I'm getting the following error when I try to run the tune_port.php script.

1. I am in the librenms home directory when I run the command:
`scripts/tune_port.php -h firewall.private  -p *
`
2. I get the following error.
```
PHP Fatal error:  Uncaught Error: Call to undefined function rrdtool_pipe_open() in /opt/librenms/scripts/tune_port.php:8
Stack trace:
#0 {main}
  thrown in /opt/librenms/scripts/tune_port.php on line 8
```

I'm assuming that the rrdtool_pipe_open() function should be in the includes/rrdtool.inc.php file. However, this function does not exist there. Has it been renamed?

Thanks
JP

**Comment by adaniels21487** [comment]
Hi @pereljon 
I believe the function has changed to: rrdtool_initialize();
I will submit a PR shortly.

Aaron
