### ISSUE TITLE
ICMP Service - No Round-Trip Graph

### ISSUE THREAD

**Issue by cyablo** [librenms/librenms#4315]
Im using the ICMP Service to Ping my Devices that dont support SNMP. I have a Graph for Packet loss but the ones for Round Trip are completely empty...
![icmp](https://cloud.githubusercontent.com/assets/3456720/18195945/de83194c-70ee-11e6-8af9-2305d48885a8.PNG)

**Comment by Rosiak** [comment]
Odd, works fine here.
Have you validated your install?

**Comment by cyablo** [comment]
Yarp, validate.php shows no Errors.

**Comment by adaniels21487** [comment]
@cyablo 
Can you please supply a pastebin of:
```./check-services.php -d```

**Comment by cyablo** [comment]
Here you go:

http://termbin.com/gy0l

**Comment by adaniels21487** [comment]
Hi @cyablo
Sorry for the delay. Just looking at your pastebin, I see that the nagios script appears to be inserting comma's (,) in the response, which makes it an invalid number:

Perf Data - DS: rta, Value: **17,060**, UOM: ms
Perf Data - DS: pl, Value: 0, UOM: %
Perf Data - DS: rtmax, Value: **19,671**, UOM: ms
Perf Data - DS: rtmin, Value: **15,078**, UOM: ms
Response: OK - xxx.xxx.xxx.xxx: rta **17,060**ms, lost 0%

So, a couple of questions:

1. are you able to run the nagios check_ script by hand and confirm you can see the comma there as well.
2. if you ping this device, how long does it take. are we talking 19 ms, or 19 thousand ms (19 seconds).

Thanks,
Aaron

**Comment by cyablo** [comment]
No Problem :)

1. Which Script should I run? I can only find check_***.inc.php Files, which are not intended to run standalone I think.

2. We are talking about ms, not seconds. In this Case, its the Google DNS to check if my Internet Connection is up, which is responding in about 19 ms.

**Comment by adaniels21487** [comment]
This is where you have your nagios scripts installed. The default path is: /usr/lib/nagios/plugins

Eg: ```/usr/lib/nagios/plugins/check_icmp 8.8.8.8```

**Comment by cyablo** [comment]
THX, here it is:

root@cybobserv:/opt/librenms# /usr/lib/nagios/plugins/check_icmp 8.8.8.8
OK - 8.8.8.8: rta 20,787ms, lost 0%|rta=20,787ms;200,000;500,000;0; pl=0%;40;80;; rtmax=24,004ms;;;; rtmin=16,049ms;;;;

BTW: Im using Debian 8 on this Machine.

**Comment by adaniels21487** [comment]
Yep, there is your issue. The nagios script has comma's in the statistics.
With a comma it isnt a string and can't be graphed.

What version of nagios-plugins are you running. In my debian 8.4 box, I have:

```
adaniels@dev:~/www/librenms$ dpkg -l nagios-plugins   
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name               Version        Architecture   Description
+++-==================-==============-==============-==========================================
ii  nagios-plugins     2.1.1-1        all            transitional dummy package (nagios-plugins
```

And no comma's:

```
adaniels@dev:~/www/librenms$ /usr/lib/nagios/plugins/check_icmp 8.8.8.8
OK - 8.8.8.8: rta 43.335ms, lost 0%|rta=43.335ms;200.000;500.000;0; pl=0%;40;80;; rtmax=50.755ms;;;; rtmin=38.031ms;;;;
```

**Comment by cyablo** [comment]
Same Version here, maybe has something to do with localization of Debian? In German, the Comma would be correct and the Point incorrect for seperating the decimal place.

root@cybobserv:/opt/librenms# dpkg -l nagios-plugins
Gewünscht=Unbekannt/Installieren/R=Entfernen/P=Vollständig Löschen/Halten
| Status=Nicht/Installiert/Config/U=Entpackt/halb konFiguriert/
         Halb installiert/Trigger erWartet/Trigger anhängig
|/ Fehler?=(kein)/R=Neuinstallation notwendig (Status, Fehler: GROSS=schlecht)
||/ Name                                                  Version                         Architektur                     Beschreibung
+++-=====================================================-===============================-===============================-===============================================================================================================
ii  nagios-plugins                                        2.1.1-1                         all                             transitional dummy package (nagios-plugins to monitoring-plugins)

**Comment by adaniels21487** [comment]
Hi @librenms/reviewers, seeking direction here.
In the german localization, the nagios plugin replaces the period (.) with a comms (,). Of course RRDtool doesnt like this.
As I see it, the options are:

1. ask that users use a localization that utilise a period (.) as the delimiter.
2. do a str_replace on the response

I am not familiar with localizations but a quick search shows the only 2 options are , and .
https://en.wikipedia.org/wiki/Decimal_mark

Thoughts?
Aaron

**Comment by Rosiak** [comment]
I feel like that even though it's a fairly simple fix I don't think we should do it.
I vote for 1.

**Comment by geordish** [comment]
You could run the script as:

 LC_NUMERIC="en_US.UTF-8" /usr/lib/nagios/plugins/check_icmp 8.8.8.8

that should put periods in place of commas for that script run.

**Comment by Rosiak** [comment]
@librenms/reviewers closing thought?

**Comment by laf** [comment]
2 seems easier all round.

**Comment by murrant** [comment]
That is pretty annoying.  I prefer the solution out forth by @geordish

**Comment by paulgear** [comment]
I definitely think we should be setting the locale environment to be what RRDtool needs it to be in order to work correctly.

**Comment by adaniels21487** [comment]
Hi Team,
I have been digging on this a little.
I am concerned that a large number of users may not have en_US installed.
From what I can tell, the C and POSIX locales are installed on all systems by default and uses a period as a separator, using this may be a better option:

```LC_NUMERIC="C" /usr/lib/nagios/plugins/check_icmp 8.8.8.8```

Can you please confirm that the C locale is installed on your machines and what you think of this idea:

```
adaniels@dev:~/www/librenms$ locale -a
C
C.UTF-8
de_DE.utf8
en_AU.utf8
POSIX
```

Thanks,
Aaron

**Comment by laf** [comment]
centos 7 + for giggles mac os x both have C

**Comment by cyablo** [comment]
Debian 8 = C + Posix installed by default.
