### ISSUE TITLE
Alerts syslog runs every 5 min instead 1 min.

### ISSUE THREAD

**Issue by bitency** [librenms/librenms#4316]
**I create a custom alert macro:**
`$config['alert']['macros']['rule']['past_1m'] = 'DATE_SUB(NOW(),INTERVAL 1 MINUTE)';`

**and our alert rule:**
`%syslog.msg ~ "@" && %syslog.timestamp >= %macros.past_1m`

The cron (alerts.php) runs every minute but the query voor the syslog alerts executed only every 5 minutes (10:05, 10:10, 10:15, 10:20 ... ) (enabled mysql query log to verify):

`SELECT * FROM syslog WHERE (syslog.device_id = '2') && (syslog.msg REGEXP ".*"        &&  syslog.timestamp >=  ( DATE_SUB( NOW() ,INTERVAL 1 MINUTE )  )  )`

**Comment by laf** [comment]
What is your interval in the rule set to? None of what you have posted dictates how often the rule is run, default is 5 minutes iirc.

**Comment by bitency** [comment]
Max alerts = -1
Delay = 0
Interval = 0

**Comment by laf** [comment]
0 is the same as default so 5 minutes.
