### ISSUE TITLE
95th percentile counted wrong

### ISSUE THREAD

**Issue by tobiasa1** [librenms/librenms#4318]
Hi!

My 95th percentile graph is not counting it right. It's about half of the real value.
Example graphs:
https://tobiasa.se/pub/95th.png
https://tobiasa.se/pub/95th2.png

Here you see the trend before the bad calculation showed up:
https://tobiasa.se/pub/history.png

Compare to Cacti which shows the right 95th value:
https://tobiasa.se/pub/cacti.png

Let me know if any more information is needed.

Version info:
Commit SHA: f278a9281cf769b679b09c4fedbb41e2ca6a5b84
DB Schema: 131
PHP: 5.6.24-0+deb8u1
MySQL: 5.5.50-0+deb8u1
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2.1

/Tobias

**Comment by laf** [comment]
What links are those graphs from?

**Comment by tobiasa1** [comment]
Hi @laf 

They are from:
https://librenms/graph.php?type=bill_bits&id=X&from=1470509464&to=1473187864&width=1000&height=200&total=1

Shown in:
https://librenms/bill/bill_id=X/view=quick/

**Comment by laf** [comment]
I can't duplicate this, both my home and work installs seem to show the correct values.

![image](https://cloud.githubusercontent.com/assets/3941142/18324687/a7363118-7535-11e6-8237-1ab9e0352aa7.png)

**Comment by tobiasa1** [comment]
This is still causing a lot of billing troubles for us. Is there any update on this?
Let me know if you need any debug data and I'll provide it.

**Comment by tobiasa1** [comment]
Another issue we have seen are zero bytes 95th:
![graph](https://cloud.githubusercontent.com/assets/5029241/18611002/809d4560-7d2c-11e6-944d-0ab99d8bd659.png)

Not sure if this is related to #3524 ?

**Comment by f0o** [comment]
Issue was due to wrong snmp ifspeed reporting. The billing-poll limits the data to the ifspeed. His ports were reporting 1G and the bills all flatline at 1G. Once changed to 10G the bills got the correct data accounted.
