### ISSUE TITLE
[Enhancement] Alert update

### ISSUE THREAD

**Issue by gcoeugnet** [librenms/librenms#4323]
Hi,

As already refered [here](https://github.com/librenms/librenms/issues/2920) there is maybe a lake of details update when an alert, port down for instance, has another port becoming down. The alert detail (which list port down) isn't updated with the news port down id.

![sans titre](https://cloud.githubusercontent.com/assets/17470139/18206833/bc6aa034-7128-11e6-972a-031846d0b0d7.png)

As far as I can see in the code, it works as designed. In /opt/librenms/includes/alerts.inc.php, there is no dbUpdate with detail if `$doalert = 1 and chk['state']=1` (line 190, function RunRules). Only "NOCHG" is echoed. Would it be possible to add a dbUpdate here to update fault details ? 

I tried a little by adding this two lines under the `echo "NOCHG"` but without success :

```
$extra = gzcompress(json_encode(array('contacts' => GetContacts($qry), 'rule'=>$qry)), 9);
dbUpdate(array('details' => $extra), 'alerts', 'device_id = ? && rule_id = ?', array($device,$rule['id']));
```

Datas seem to contain images (maybe the one displayed when mouse get over the port name/id) and I didn't succeed in getting the fault ports list to update it. What's your point about detail update and do you have any tips to help me update the fault port list ?

Regards,
Guillaume.

**Comment by f0o** [comment]
That should be handled by the follow-up routines. I'll check it over weekend
