### ISSUE TITLE
Saving Port Settings updates only first 198 ports.

### ISSUE THREAD

**Issue by eggwall** [librenms/librenms#4324]
Under the Port Settings page, when displaying "250" or "All" interface, only the first 198 ports are actually updated when Saving.

For example, we have a switch with 233 ports.  If I ignore or disable all ports and save, only the first 198 ports are actually updated, and ports 199+ are unchanged.  The remaining ports have to be changed using the option to display "50" or "100" ports at a time.

This is a newly added device, and I used "toggle" to ignore every port.  The toggle button checks all 233 boxes.

![2016-09-02 10_15_47- settings - librenms](https://cloud.githubusercontent.com/assets/21957129/18210683/f79b09be-70f6-11e6-8038-a4ebdc8a7b56.png)

After pressing Save, only 198 were updated.  If I change to 50 at a time, and go to the last 2 pages, it verifies ports 199-233 were not updated to be ignored.

![2016-09-02 10_18_06 - settings - librenms](https://cloud.githubusercontent.com/assets/21957129/18210698/0ad53e96-70f7-11e6-8df9-5b87e59061e2.png)

====================================
Version info:
Commit SHA: f278a9281cf769b679b09c4fedbb41e2ca6a5b84
DB Schema: 118
PHP: 7.0.8-0ubuntu0.16.04.2
MySQL: 10.0.25-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP version: 5.7.3

====================================

**Comment by laf** [comment]
Check your web server logs, I expect you are hitting max memory in php

**Comment by laf** [comment]
If it's not the max mem check max post items. Feel free to reply back but I'm confident it's a php setting issue.

**Comment by eggwall** [comment]
You are correct, it was the php post items.

I updated this line in /etc/php/7.0/apache2/php.ini from 1000 to 1500.
max_input_vars = 1500

Thanks.
