### ISSUE TITLE
Juniper - SA device support

### ISSUE THREAD

**Issue by rbax-idx** [librenms/librenms#4328]
Please add support for this device.
discovery:
http://sprunge.us/JYEZ
poller:
http://sprunge.us/CHJA
snmpbulkwalk:
http://sprunge.us/iKTT
MIB: http://sprunge.us/NCjV

Thank you!

**Comment by Rosiak** [comment]
Are these similar to Pulse Secure devices?

**Comment by rbax-idx** [comment]
That is exactly what this is. :)

**Comment by rbax-idx** [comment]
I'm guess the mib  is already there, just the device needs to be associated to it?

**Comment by geordish** [comment]
From the install docs, the SNMP walk you've provided is from a training/eval VM, and not something for use in production:

http://www.juniper.net/techpubs/software/ive/va/guides/j-sa-va-7.0-spvirtualappliance.pdf

"The DTE is targeted at demonstration, initial evaluation, and training purposes. DTE is not a
supported product; Pulse Secure Support will not assist you with any questions or problems. If
you are interested in the DTE, contact your Pulse Secure sales team or reseller."

It looks like the appropriate version that should be added is the SPE

"The SPE is targeted for service providers who are interested in provisioning remote access
solution for a large number of customers."

I'm unsure if the DTE would be worth adding, but the following patch should do it.
```php
--- a/includes/discovery/os/pulse.inc.php
+++ b/includes/discovery/os/pulse.inc.php
@@ -13,4 +13,7 @@ if (!$os) {
     if (strstr($sysDescr, 'Pulse Connect Secure')) {
         $os = 'pulse';
     }
+    if (strstr($sysDescr, 'Juniper Networks,Inc,VA-DTE')) {
+        $os = 'pulse';
+    }
 }
```

**Comment by rbax-idx** [comment]
If someone could add that code, that woyld be great. FYI: http://www.juniper.net/techpubs/software/ive/releasenotes/j-sa-sslvpn-7.2R4-supportedplatforms.pdf
