### ISSUE TITLE
Monitor NUT (UPS)

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#4340]
Hi,

I have done some hunting for this, but likely missed it - sorry if I did!

Just a quick (and possibly dumb) question - is it possible to monitor NUT (UPS) from LibreNMS?

Thanks!

**Comment by Rosiak** [comment]
```
./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -r -f -d -m os
snmpbulkwalk -On -v2c -c COMMUNITY HOSTNAME .
```

And we can make it happen :-)

**Comment by crcro** [comment]
something similar is already requested: #4230

**Comment by arrmo** [comment]
Yep, agreed - NUT vs. apcupsd, but very similar. Close this then?

Thanks!

**Comment by crcro** [comment]
actually ... please post the output of NUT to checkout

**Comment by arrmo** [comment]
Sure, NP! Attached below. Note that the first line (SSL complaint) - more info on that here (http://askubuntu.com/questions/468632/nut-ups-and-ssl-certificates) ... but basically, ignore it ... :).

pi@raspberrypi:~ $ upsc APCUPS
Init SSL without certificate database
battery.charge: 99
battery.charge.low: 10
battery.charge.warning: 50
battery.date: not set
battery.mfr.date: 2007/05/11
battery.runtime: 337
battery.runtime.low: 120
battery.type: PbAc
battery.voltage: 13.6
battery.voltage.nominal: 12.0
device.mfr: APC
device.model: Back-UPS ES 550
device.serial: 3B0719X55476
device.type: ups
driver.name: usbhid-ups
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 2
driver.parameter.port: /dev/usb/hiddev0
driver.version: 2.7.2
driver.version.data: APC HID 0.95
driver.version.internal: 0.38
input.sensitivity: high
input.transfer.high: 139
input.transfer.low: 88
input.transfer.reason: input voltage out of range
input.voltage: 122.0
input.voltage.nominal: 120
ups.beeper.status: disabled
ups.delay.shutdown: 20
ups.firmware: 840.B2.D
ups.firmware.aux: B2
ups.load: 25
ups.mfr: APC
ups.mfr.date: 2007/05/11
ups.model: Back-UPS ES 550
ups.productid: 0002
ups.serial: 3B0719X55476
ups.status: OL CHRG
ups.timer.reboot: 0
ups.timer.shutdown: -1
ups.vendorid: 051d

Thanks!

**Comment by crcro** [comment]
the following data seems to be available to apc upsmon:

battery.charge: 99
battery.charge.low: 10
battery.charge.warning: 50
battery.runtime: 337
battery.runtime.low: 120
battery.voltage: 13.6
battery.voltage.nominal: 12.0
input.sensitivity: high
input.transfer.high: 139
input.transfer.low: 88
input.voltage: 122.0
ups.load: 25

do you need something more than that?
i'm thinking writing a script for both of them, or better to make 2 different ones?

**Comment by arrmo** [comment]
Very close I'd say - much of that is not really needed, agree with you there. Just a few that perhaps should be included - thoughts?

Model
Serial Number
Status (online, on battery, etc.)

Thanks!

**Comment by crcro** [comment]
maybe as some description on graphs, otherwise i cannot see how to graph the serial number :)), agree on the status but for that i would need the exact output for that states to match on

**Comment by arrmo** [comment]
Yes, agreed! I was thinking description also, not plotting serial number ... :).

On the Status - perhaps some info here? https://github.com/networkupstools/nut/blob/5d98d5536699222bc93c58c1e6f6df43dc9bfcff/docs/config-notes.txt

Or, just capture it as a string, but allow alarming based on it then (i.e. take care of it in alarm logic, on the user)?

Thanks!

**Comment by arrmo** [comment]
A reference here that may help (for extracting data)?
https://forum.pfsense.org/index.php?topic=80981.0

**Comment by arrmo** [comment]
Hi,

First of all - thanks very much! Really appreciate this.

I have it "set-up", but not quite working. May be me. I had to make a couple changes to the script (remove stderr output, given the NUT warning now about SSL), and some minor path updates ... but then the script runs, and I also checked snmpwalk, output as below,

NET-SNMP-EXTEND-MIB::nsExtendExecType."ups-nut" = INTEGER: exec(1)
NET-SNMP-EXTEND-MIB::nsExtendRunType."ups-nut" = INTEGER: run-on-read(1)
NET-SNMP-EXTEND-MIB::nsExtendStorage."ups-nut" = INTEGER: permanent(4)
NET-SNMP-EXTEND-MIB::nsExtendStatus."ups-nut" = INTEGER: active(1)
NET-SNMP-EXTEND-MIB::nsExtendOutput1Line."ups-nut" = STRING: 10
NET-SNMP-EXTEND-MIB::nsExtendOutputFull."ups-nut" = STRING: 10
NET-SNMP-EXTEND-MIB::nsExtendOutNumLines."ups-nut" = INTEGER: 9
NET-SNMP-EXTEND-MIB::nsExtendResult."ups-nut" = INTEGER: 0
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".1 = STRING: 10
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".2 = STRING: 20
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".3 = STRING: PbAcid
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".4 = STRING: CPS
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".5 = STRING: usbhid-ups
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".6 = STRING: 30
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".7 = STRING: 30
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".8 = STRING: 20
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".9 = STRING: OL

But ... no joy in the plots in LibreNMS. I do see this in Apps now, but the output is "blank" (all -nan). Thoughts? Things to check?

Thanks again!

**Comment by crcro** [comment]
please run ups-nut.sh and paste the output

**Comment by arrmo** [comment]
Sure! Here it is,
10
20
PbAcid
CPS
usbhid-ups
30
30
20
OL

Things you want me to check?

**Comment by arrmo** [comment]
BTW, here is the change I made to the one line (throw out stderr),
CMD1=`$BIN_UPSC $UPSC_CMD 2>/dev/null | $BIN_SED "1 d" | $BIN_TR '\n' '|' | $BIN_TR -d ' '`

Thanks!

**Comment by crcro** [comment]
make that line: CMD1=$BIN_UPSC $UPSC_CMD 2>/dev/null | $BIN_TR '\n' '|'

**Comment by arrmo** [comment]
Ummm ... with that command all output is blank. Is it really supposed to end with a pipe? And no `'s for the command output?

Thanks!

**Comment by crcro** [comment]
my bad:

CMD1=`$BIN_UPSC $UPSC_CMD 2>/dev/null | $BIN_TR '\n' '|'`

**Comment by arrmo** [comment]
NP! OK, slightly different output (different values, but we can figure that out later). Here is the script output (leading space now),
 100
 10
 300
 12
 ups
 usbhid-ups
 20
 30
 450

Still no joy in LibreNMS application though - thoughts?

**Comment by crcro** [comment]
now please post the current output from your upsc, i think something changed more than that first line, i think that i will change the script to match words instead of lines as it is not too flexible

**Comment by arrmo** [comment]
Sure, NP! Here it is,
Init SSL without certificate database
battery.charge: 100
battery.charge.low: 10
battery.charge.warning: 20
battery.mfr.date: CPS
battery.runtime: 2460
battery.runtime.low: 300
battery.type: PbAcid
battery.voltage: 13.7
battery.voltage.nominal: 12
device.mfr: CPS
device.model: UPS CP850AVRLCD
device.type: ups
driver.name: usbhid-ups
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 2
driver.parameter.port: /dev/usb/hiddev0
driver.version: 2.7.2
driver.version.data: CyberPower HID 0.3
driver.version.internal: 0.38
input.transfer.high: 140
input.transfer.low: 90
input.voltage: 123.0
input.voltage.nominal: 120
output.voltage: 123.0
ups.beeper.status: enabled
ups.delay.shutdown: 20
ups.delay.start: 30
ups.load: 19
ups.mfr: CPS
ups.model: UPS CP850AVRLCD
ups.productid: 0501
ups.realpower.nominal: 450
ups.status: OL
ups.test.result: Done and warning
ups.timer.shutdown: -60
ups.timer.start: 0
ups.vendorid: 0764

**Comment by crcro** [comment]
@arrmo ... i no longer see device.serial?

**Comment by arrmo** [comment]
Sorry, jumped from one machine to another - different UPS's, one reports serial, the other doesn't. Perhaps default to N/A if not reported?

**Comment by crcro** [comment]
@arrmo ... np ... it's good to know ... changed the shell script:
https://github.com/librenms/librenms-agent/pull/63/files

**Comment by arrmo** [comment]
OK, tried it - two things,
1) I had to change a few lines. Not a biggie, just so you know.
BIN_UPSC='/bin/upsc'
BIN_CAT='/bin/cat'
BIN_GREP='/bin/grep'

2) The output now,
Init SSL without certificate database
100
10
2460
13.7
12
UPSCP850AVRLCD
Unkown
120
123.0
20

And on LibreNMS, they all look like the following (just two of them selected here) - thoughts?
Remaining time: 13.7 (SN:12)
Charge: 13.7 (SN:12)

Thanks!

**Comment by crcro** [comment]
Made some other changes in the parameters orders, please check it.

**Comment by arrmo** [comment]
Sure. Output from script is below,
100
10
2460
13.7
UPSCP850AVRLCD
Unkown
12
120
121.0
21

(minor - typo in Unkown). But I think it's on the "other" side (i.e. poller) - here's why I say that. I updated the script, items above, and then manually run poller.php. Now the output in LibreNMS is like this,
Remaining time: 13.7 (SN:UPSCP850AVRLCD)

But all variables (e.g. Remaining time, Load, Battery voltage, etc.) => they all seem to say 13.7.

Thoughts?

Thanks!

**Comment by crcro** [comment]
can you post the output of:
snmpwalk -v2c -c COMMUNITY HOST NET-SNMP-EXTEND-MIB::nsExtendOutLine.\"ups-nut\"

**Comment by arrmo** [comment]
OK, but 13.7 is not the name, right? Here is the output!
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".1 = STRING: /home/rmorris/ups-nut.sh: line 23: /tmp/output_nut: Permission denied
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".2 = STRING: 100
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".3 = STRING: 10
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".4 = STRING: 2460
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".5 = STRING: 13.7
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".6 = STRING: UPSCP850AVRLCD
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".7 = STRING: Unkown
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".8 = STRING: 12
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".9 = STRING: 120
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".10 = STRING: 121.0
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".11 = STRING: 21

**Comment by crcro** [comment]
ok ... so there is a permission error, you should fix that by using /home/rmorris/output_nut instead of /tmp/output_nut and run again snmpwalk -v2c -c COMMUNITY HOST NET-SNMP-EXTEND-MIB::nsExtendOutLine.\"ups-nut\"

**Comment by arrmo** [comment]
Yep, just noticed that as well ... :). When I run it manually (bash) - no issues at all, seems to be only when run by snmp. But what's also odd - /tmp has full (777) permissions. Very odd.

Changing to point to my home directory doesn't help either, as it's snmp running the script. Same error. Still odd ... /tmp is writeable by all.

**Comment by crcro** [comment]
push another update in which i removed the need of that file, please put that in place and post the snmpwalk again :)

**Comment by arrmo** [comment]
That works better! ... :). Here you go,
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".1 = STRING: 100
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".2 = STRING: 10
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".3 = STRING: 2460
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".4 = STRING: 13.7
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".5 = STRING: UPSCP850AVRLCD
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".6 = STRING: Unknown
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".7 = STRING: 12
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".8 = STRING: 120
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".9 = STRING: 123.0
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".10 = STRING: 21

Ran poller ... but I think I may have to wait a few cycles (say, 10-15 min?) for the -nan values to update properly? I admit, exactly not sure how those get updated.

**Comment by crcro** [comment]
now the output seems right :)
the updates to rrd files are made by the includes/polling/applications/ups-nut.inc.php file 
i recommend that first you disable the ups nut app entirely and make sure that any rrd file regarding it (apps-ups-nut*.rrd) are removed, then re-enable the app on host to start clean

**Comment by arrmo** [comment]
Yep, that helped - remove and re-enabled cleaned it up. Thanks! A few notes, now that updates are showing up,
1) Remaining Time - perhaps convert to minutes? 2400 seconds is less obvious ... ;-).
2) Load - seems to be in the SNMP data, but this plot is blank (and -nan). The only one doing this.
3) Battery Voltage - works great, but perhaps don't include battery.charge.low? This is just the UPS threshold when to flag issues (and it's charge, not voltage).
4) Charge - also seems to work great. I need to pull the plug (not there right now), to see it update / work, but I expect it will.
5) Input Voltage - nominal is great, but input voltage seems to be using battery voltage (battery.voltage.nominal)?

Thanks again.

**Comment by crcro** [comment]
1) done, in the latest PR from librenms
2) Should also be fixed
3) removed the battery.charge.low
4) Should work :)
5) Fixed

both latest submit to librenms-agent and #4448 must be applied
note: you must disable and enable the app again due to changes in the value numbers

**Comment by arrmo** [comment]
Hi,

A couple FYI items (as I pulled the plug on the UPS tonight, to check it),
- the input voltage drops to zero (as it should) in upsc, but not in LibreNMS
- would make sense to use status to show Online (OL) vs. On Battery (OB)?

Thanks!

**Comment by crcro** [comment]
app code merged, this can be closed?
