### ISSUE TITLE
Availability map widget issue

### ISSUE THREAD

**Issue by realnakrul** [librenms/librenms#4345]
Hi
Availability map widget on the dashboard always shows devices with small icons. Like this:
![1](https://cloud.githubusercontent.com/assets/21193002/18238948/ad0a7138-7352-11e6-8ba6-2a47695c2621.JPG)
Even if I change tile width (I tried different values)
![2](https://cloud.githubusercontent.com/assets/21193002/18238965/e5791006-7352-11e6-8f13-ee191cd4398c.JPG)
But in Overview -> Maps -> Availability it looks like this:
![3](https://cloud.githubusercontent.com/assets/21193002/18239227/e7b624f6-7354-11e6-82da-c16f487e99ba.JPG)
Is it a bug? What is the use of the tile width?

**Comment by laf** [comment]
This is intended, the dashboard gives a more consolidated view.

**Comment by realnakrul** [comment]
Why do we need tile width then? It doesn't work and confising.

**Comment by laf** [comment]
It's for the old availability map

**Comment by realnakrul** [comment]
With old availability map it doesn't work also...
As for me tiles should contain device name at least. Otherwise you have to click on it to understand which device has an issue.
Also I think it would be nice if Device Group Filter can be applied to the Availability map widget. For example you will see only devices with issues. Which is more useful for overview I think...

**Comment by crcro** [comment]
will lookup that tile setting issue.
in widget everything is consolidated, so you cannot display large icons like in direct page, but you can keep your cursor over the box and a description will appear including device name and uptime.
