### ISSUE TITLE
RRDTool 1.6.0 actually does not have a remote tune command through rrdcached

### ISSUE THREAD

**Issue by mmarchand** [librenms/librenms#4356]
#### Please note

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

While debugging why my >100gb/s port-channels rrds weren't getting properly updated, 
Running librenms debug rrd tune command by hand gave me : 

```
rrdtool tune bb1.xxx/port-id795668.rrd --maximum INOCTETS:25000000000 --maximum OUTOCTETS:25000000000 --maximum INERRORS:25000000000 --maximum OUTERRORS:25000000000 --maximum INUCASTPKTS:25000000000 --maximum OUTUCASTPKTS:25000000000 --maximum INNUCASTPKTS:25000000000 --maximum OUTNUCASTPKTS:25000000000 --maximum INDISCARDS:25000000000 --maximum OUTDISCARDS:25000000000 --maximum INUNKNOWNPROTOS:25000000000 --maximum INBROADCASTPKTS:25000000000 --maximum OUTBROADCASTPKTS:25000000000 --maximum INMULTICASTPKTS:25000000000 --maximum OUTMULTICASTPKTS:25000000000 --daemon a.b.c.d:42217 
ERROR: opening 'bb1.xxx/port-id795668.rrd': No such file or directory

```
so I investigated rrdtool source code to find out why it tried to open a local file,
this lead me to the conclusion that rrdtool actually does not (yet) support a remote "tune" command so it can't be used just remotely :( 
(check https://github.com/oetiker/rrdtool-1.x/blob/master/src/rrd_daemon.c#L2555 )

Yes there is a basic daemon option support in their code, I believe it is being used to make sure to "flushcached" any remote data before attempting to modify the "local" file (probably to save data in case of shared filesystems), but sadly no remote rrdcached support to modify the RRD structure.

I don't think there is any simple fix for librenms of course and most likely nothing should be changed in librenms code because it is supported that way in RRDTool, but it's probably worth noting in the documentation that it will only work with a shared filesystem :(

**Comment by murrant** [comment]
Looks like it works like other commands did prior to 1.5...  still deciding what to do about it.  Probably updating the docs is correct at the least.

**Comment by laf** [comment]
I've covered it in my docs pr that's in the queue btw.

**Comment by murrant** [comment]
Docs updated, thanks for the report.
