### ISSUE TITLE
Feature Request: webui availability map (choosing more than one group)

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#4366]
Hi,

In a scenario where there are many device groups configured on the system, I think it would be great to have the ability to select more than one group in the pull down menu on the availability map page. For an example, if I have defined groups for firewalls (Fortigate, Juniper, Cisco), servers (Windows, Linux) and routers (Huawei, Cisco), I may be interested in only displaying the availability map for firewalls (Juniper) and routers (Cisco) in one dashboard and not the rest. Someone else may want to only display servers (Windows) and routers (Huawei) in one dashboard and so on. I suppose this can be accomplished using the device groups feature itself however it is a bit cumbersome and limits flexibility somewhat. 
Hope it makes sense

**Comment by crcro** [comment]
Then you could create a device group that makes the selection as desired and then select that device group from the availability map to display :)

**Comment by breeman1** [comment]
Yes it can be done that way, however flexibility for end-users without admin rights to create their own customized dashboards is a nice to have :)

**Comment by crcro** [comment]
i think that this can be closed
