### ISSUE TITLE
Billing bug - ports removed, still showing traffic !!!

### ISSUE THREAD

**Issue by ebym** [librenms/librenms#4368]
`librenms version 2a2be95.`

Last month I've removed interfaces from a quota based bill, even without a valid port, the billing is showing 15GB traffic from Sept 1 - 7 th!!!.

The mentioned interfaces are on HPE comware 5 based switch.

After removing the ports from the bill, i ran `./daily.sh` to ensure librenms is uptodate.

It would be nice to have a feature to archive billing data for future reference.

**Comment by laf** [comment]
Your install is 2530 commits behind master - please update.

**Comment by ebym** [comment]
When I run ./daily.sh it says ok. I'm not using git, is there any other way ?.

**Comment by laf** [comment]
If you've copied the files directly then you will need to grab the latest ones and copy them in place. you really should switch to git.

**Comment by ebym** [comment]
i've installed using git only. even after running ./daily.sh it show the same version !!!.

> root@linuxadmin-virtual-machine:/opt/librenms# ./daily.sh 
> Updating SQL-Schema                                OK
> Updating submodules                                OK
> Cleaning up DB                                     OK
> Fetching notifications                             OK
> root@linuxadmin-virtual-machine:/opt/librenms# 

Do i have any other option ?.

**Comment by ebym** [comment]
update; When i do `git pull`, i'm getting a strange error for includes/defaults.inc.php file. The file i have and on github are the same !!! not sure why it is giving this error.

> 
> remote: Counting objects: 16959, done.
> remote: Compressing objects: 100% (52/52), done.
> Receiving objects: 100% (16959/16959), 8.65 MiB | 2.33 MiB/s, done.
> remote: Total 16959 (delta 6574), reused 6555 (delta 6555), pack-reused 10352
> Resolving deltas: 100% (12830/12830), completed with 1271 local objects.
> From https://github.com/librenms/librenms
>    2a2be95..a8efda8  master     -> origin/master
>  * [new branch]      revert-4134-issue-4127 -> origin/revert-4134-issue-4127
> From https://github.com/librenms/librenms
>  * [new tag]         201602     -> 201602
>  * [new tag]         201603     -> 201603
>  * [new tag]         201604     -> 201604
>  * [new tag]         201605     -> 201605
>  * [new tag]         201606     -> 201606
>  * [new tag]         201607     -> 201607
>  * [new tag]         201608     -> 201608
>  * [new tag]         20160828   -> 20160828
> Updating 2a2be95..a8efda8
> error: Your local changes to the following files would be overwritten by merge:
> 	includes/defaults.inc.php
> Please, commit your changes or stash them before you can merge.
> Aborting

**Comment by ebym** [comment]
If this helps someone, here is how i managed to update to the latest version. Continuing from previous post. 

1. run `git commit,` which will bring nano on ubuntu, remove `#` from the `includes/defaults.inc.php` line and save.
2. when completed, run `./validate.php`, if it tells you about file ownership other than librenms, then you need to run `chown -R librenms:librenms /opt/librenms`. (git pull changed ownership updated files to root)
3. finally run `./daily.sh`. This will take a while to complete.

when i run `git status` it says, 

```
#On branch master
# Your branch is ahead of 'origin/master' by 2 commits.
```

I'll keep updating on the initial issue.

**Comment by ebym** [comment]
`Version: 66fea7b - Tue Sep 13 2016 20:16:56 GMT+0530`

Transfer Graph show 0 traffic from since librenms update. However Accurate Graph show a steady 54kbp traffic and Quick Graph show 54kbps usage in Billing view and 0bps usage in 24 Hour View.

![selection_229](https://cloud.githubusercontent.com/assets/16803049/18607677/3d66abdc-7cf1-11e6-9ed6-928d6a711f52.png)

![selection_230](https://cloud.githubusercontent.com/assets/16803049/18607679/466664b6-7cf1-11e6-9dc8-dee7c1219230.png)

**Comment by laf** [comment]
Are you still experiencing this?

**Comment by ebym** [comment]
No graph issues since October 2016.

**Comment by Harpreetsinghbedi** [comment]
Hello,

I have created a bill with LibreNMS but graphs are showing 0.

Is there any cron file in LibreNMS to update the bill graph data?

Please let me know, which cron file i need to setup for update bill graph data.
