### ISSUE TITLE
Review Package-Dependencies

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#437]
Hi,

I've been deploying an awful amount of poller-hosts recently and I got to look at the package-dependencies:
`libapache2-mod-php5 php5-cli php5-mysql php5-gd php5-snmp php-pear snmp graphviz php5-mcrypt php5-json apache2 fping imagemagick whois mtr-tiny nmap python-mysqldb snmpd mysql-client php-net-ipv4 php-net-ipv6 rrdtool git`

I can't explain where or even if we use: `php5-snmp imagemagick graphviz mtr-tiny nmap php-pear`

I know that `php-pear` is required in case `php-net-ipv4` and/or `php-net-ipv6` doesnt exist, to install it via pear.

Does anybody know what the packages in question are used for?

**Comment by laf** [comment]
mtr-tiny and nmap are used in the netcmd.php script but not used outside of that.

snmp isn't used at all afaik.

not sure if imagemagic and graphviz are needed for jpgraph?

**Comment by f0o** [comment]
Re: netcmd.php

From a quick grep only whois is really used by LibreNMS. nmap and mtr are available codewise but not used anywhere... 

Re: imagemagic and graphviz, I'm not sure.. Debian's `libphp-jpgraph` https://packages.debian.org/wheezy/libphp-jpgraph doesnt list it as dependencies, only `php-gd` :S

**Comment by laf** [comment]
I'd say keep the bits that are used by netcmd.php as they could be useful.

I guess remove the others if they aren't needed.

**Comment by laf** [comment]
Hi @f0o, looking to close this unless we are going to remove any of the listed packages for install.

**Comment by f0o** [comment]
Closing
