### ISSUE TITLE
Add addtional Device Settings Types

### ISSUE THREAD

**Issue by allano337** [librenms/librenms#4373]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x ] Please provide as much detail as possible.

Would like to see SBC or Session Border Controller, Voice Gateway and MUX added to the list of device settings  types

Thank you

**Comment by laf** [comment]
Device settings types? Do you mean things like firewalls, servers, network, etc? If so these are designed to be grouped together and I don't see us extending them out to include specific groups as suggested.

**Comment by allano337** [comment]
yes like servers and firewalls which these could be classified as such, would make grouping devices better especially to bring more folks from the Telecom world ie(Sonus Networks) in instead of using What's Up or other type monitoring of nms

**Comment by laf** [comment]
That's too granular a list for us I think ( @librenms/reviewers ?)

If they can be summarised into one group or two we would consider it

**Comment by allano337** [comment]
if it's too granular for the base code, I believe you stated that you would show how we could add them to our system on irc yesterday.

**Comment by laf** [comment]
I think I was assuming you meant new device support. The best option for you would be to create device groups.

**Comment by allano337** [comment]
ok, will close ticket
