### ISSUE TITLE
TrippLite SNMPWEBCARD values off by 10x

### ISSUE THREAD

**Issue by loginwastaken** [librenms/librenms#4391]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

SNMPWEBCARD with version 12.06.0068.11852.11851 reports incorrect values for battery voltage, output current, input frequency, output frequency and bypass frequency. Values are 10x what they should be. 

here is the snmpbulkwalk output
http://pastebin.com/JMAzn8J8

**Comment by crcro** [comment]
i think this can be closed as the fix (#4495) was merged?

**Comment by loginwastaken** [comment]
output voltage is now 12v instead of 120v. The rest are correct.

**Comment by crcro** [comment]
fix for voltages was submitted/merge last night

**Comment by laf** [comment]
@loginwastaken please run `./validate.php` and pastebin the output if this is still not working for you after an update.

**Comment by loginwastaken** [comment]
http://picpaste.com/ups-XvkVx7o7.png

So close. Bat voltage is 10x high. The rest are fine.

**Comment by loginwastaken** [comment]
http://pastebin.com/CMvm32HE

Still off.
