### ISSUE TITLE
Monitoring Cisco ACI APICS

### ISSUE THREAD

**Issue by cliff-ha** [librenms/librenms#4396]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.

`====================================`
Version info:
Commit SHA: d6d2ff84991825d79a8df85a18c765895ca0962d
DB Schema: 118
PHP: 7.0.10
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2

`====================================`
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)

The MIB files for APIC, can be found here:
http://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/1-x/mib/list/mib-support.html#apic-mibs

I would like to monitor Cisco ACI APIC, but when
- [x] Please provide as much detail as possible.
  i add it I only see this SNMP information:
  Device Icon changed => generic  
  sysContact
  sysObjectID
  sysName
  sysDescr
  Location

If i do a snmpwalk i get alot more SNMP information there are not shown.

**Comment by laf** [comment]
@cliff-ha The text above tells you what we need to add a new device, please follow the link and provide what's asked for.

**Comment by cliff-ha** [comment]
I have just updated the information.

**Comment by laf** [comment]
I'm not seeing any discovery, polling or snmp walk outputs.

**Comment by cliff-ha** [comment]
Sorry, I missed that.

I have attached a snmpwalk and discovery.
[discovery -h -d.txt](https://github.com/librenms/librenms/files/466687/discovery.-h.-d.txt)
[snmpwalk APIC.txt](https://github.com/librenms/librenms/files/466688/snmpwalk.APIC.txt)

**Comment by laf** [comment]
This walk isn't in the format we need, please provide the information as per the link in your first post.

**Comment by cliff-ha** [comment]
[SNMPwalk.txt](https://github.com/librenms/librenms/files/663807/SNMPwalk.txt)
[Discovery.txt](https://github.com/librenms/librenms/files/663808/Discovery.txt)
[Poller.txt](https://github.com/librenms/librenms/files/663809/Poller.txt)
I have just created the files in the correct format

**Comment by cliff-ha** [comment]
Is it possiable to add any information about the PSU's, to make it possible to monitor if one of them is down?

This information is the S/N of the PSU:
.1.3.6.1.2.1.47.1.1.1.1.11.10548 = STRING: ""
.1.3.6.1.2.1.47.1.1.1.1.11.10608 = STRING: ""

**Comment by laf** [comment]
Does it have the state information in the mib? S/N isn't helpful.

**Comment by laf** [comment]
No further info provided.
