### ISSUE TITLE
Data restore error

### ISSUE THREAD

**Issue by search4u2003** [librenms/librenms#4398]
When i restore my DB i get below error

Error
SQL query:
ALTER TABLE `alert_log`
  ADD PRIMARY KEY (`id`),
  ADD KEY `rule_id` (`rule_id`),
  ADD KEY `device_id` (`device_id`),
  ADD KEY `time_logged` (`time_logged`)
MySQL said: Documentation
#1062 - Duplicate entry '0' for key 'PRIMARY'

**Comment by laf** [comment]
Are you restoring to a blank database?

**Comment by laf** [comment]
No further info provided.
