### ISSUE TITLE
SYSLOG Messages from the Future!

### ISSUE THREAD

**Issue by adamboutcher** [librenms/librenms#4399]
Hi,

Can we have an option that will either disallow or prune syslog messages with the incorrect date in them? Some of our devices push syslog to LibreNMS prior to NTP correcting the time, so it appears with a date in the future, days, months and years ahead rather than a few hours...

An option to prune them would be useful as the current syslog view is full of incorrect details.

**Comment by laf** [comment]
You can delete syslog data directly in MySQL. I don't see a need for us to create something which deals with data being sent with incorrect times.

**Comment by adamboutcher** [comment]
We can but it would be a daily/weekly/hourly script depending on the frequency.

If the times/dates were dealt with LibreNMS on the time of arrival then time/date mismatch wouldn't be an issue and actually be more useful as a log view as if the NMS and remote devices time differ then searching the logs is actually near useless.

For the sake of a few lines within the syslog handler, I can't see why this wouldn't be a smarter move?

**Comment by laf** [comment]
What about different timezone, logs could appear to be sent from a future date but be from a different TZ.

Feel free to add support for this but it shouldn't be our job to decide to store the data or not - if it's wrong and we delete users data then this isn't good.

Alternatively, use something like Graylog2.

**Comment by florianbeer** [comment]
You can just exchange `timereported` with `timegenerated` in your syslog template (e.g. `/etc/rsyslog.d/30-librenms.conf `) to get consistent timestamps from servers with different local timezones.

http://www.rsyslog.com/what-is-the-difference-between-timereported-and-timegenerated/

**Comment by laf** [comment]
Closing as no further info provided.
