### ISSUE TITLE
Cisco ACI spine/leaf switch error

### ISSUE THREAD

**Issue by cliff-ha** [librenms/librenms#4403]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
# 

Version info:
Commit SHA: d1ae83a378a6016a6619f6f13d49209334baf2c0
DB Schema: 118
PHP: 7.0.10
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2
# 
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)

Location of mib files:
http://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/1-x/mib/list/mib-support.html#switch-mibs
- [x] Please provide as much detail as possible.

I am having problems with my Cisco ACI spine/leaf switches, on the fabric port LibreNMS are seeing both the physical port and a Vlan subinterface.
My problem is when I set a port to admin down in the configuration the physical port goes down and the errors are removed, but the vlan subinterface is showing as down and creates an alarm.
<img width="1159" alt="screen shot 2016-09-11 at 23 37 17" src="https://cloud.githubusercontent.com/assets/22104621/18420708/5ac1461e-7879-11e6-953f-56bea2b11b49.png">

**Comment by geordish** [comment]
Would ignoring the VLAN completely subinterfaces work for this? If so, then you could try something like here:
http://docs.librenms.org/Support/Configuration/#interfaces-to-be-ignored

The following may be a good starting point for you.
```php
$config['bad_if_regex'][] = "/^[0-9]+\.Ethernet[0-9]+/[0-9]\.[0-9]$/"; 
```

**Comment by cliff-ha** [comment]
I would prerfer not to remove the information because we have other devices where we are having subinterfaces on interfaces called ethernet.

We have an old Observium installation running and here the subinterfaces on the switches are not showing.
Can the differens be that it is using different MIB's?

**Comment by geordish** [comment]
Maybe...
```php
$config['bad_iftype'][] = "VLAN Subif";
```

**Comment by cliff-ha** [comment]
I have done the configuration and they are now removed.
