### ISSUE TITLE
No ports found on Nexus 9000 / ACI switches after update

### ISSUE THREAD

**Issue by thomasraabo** [librenms/librenms#4408]
I no longer see any ports in librenms

discovery.php does not find the ports

Have attached output of discovery and snmpwalk ( snmpwalk does see ports)
[snmp-walk.txt](https://github.com/librenms/librenms/files/467198/snmp-walk.txt)
[discovery.txt](https://github.com/librenms/librenms/files/467199/discovery.txt)

[root@NETMGMT-C002 librenms]# ./validate.php
====================================
Version info:
Commit SHA: 9aaea7e64e00971c4a1c6c9294403b6aa61643d8
DB Schema: 132
PHP: 5.4.16
MySQL: 5.5.47-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2

====================================
[OK]      Database connection successful

**Comment by laf** [comment]
This device is not returning any ifDescr so by default we exclude them.

Try this in config.php `$config['os']['nxos']['empty_ifdescr'] = true;`

**Comment by thomasraabo** [comment]
Almost works.

But no interface names "ethernet" and overview is screwed.

<img width="692" alt="2" src="https://cloud.githubusercontent.com/assets/8310015/18467724/68a70e70-79a1-11e6-8db3-bdc42a0fd3c1.png">
<img width="1022" alt="1" src="https://cloud.githubusercontent.com/assets/8310015/18467723/689d7efa-79a1-11e6-9dbe-edaf5939f17c.png">

**Comment by thomasraabo** [comment]
any?

**Comment by laf** [comment]
People respond when they can.

You will need to update the discovery and poller debug output for the ports module and provide those as pastebin links.

**Comment by thomasraabo** [comment]
I Will do that later today.

Thomas

**Comment by thomasraabo** [comment]
Here is the debugs for discovery and poller

[poller.txt](https://github.com/librenms/librenms/files/475333/poller.txt)
[discovery.txt](https://github.com/librenms/librenms/files/475332/discovery.txt)

**Comment by thomasraabo** [comment]
Laf need any other information?

**Comment by thomasraabo** [comment]
Tried $port['ifDescr'] = $port['ifName']; <-- in functions.php but that did not help

It seems that Cisco removed ifDescr from Cisco ACI firmware - and only populate ifName

So we somehow need a way to make ifDescr =  ifName on ACI devices ...   

IF-MIB::ifName.436207616 = STRING: Ethernet1/1
IF-MIB::ifName.436211712 = STRING: Ethernet1/2
IF-MIB::ifName.436215808 = STRING: Ethernet1/3
IF-MIB::ifName.436219904 = STRING: Ethernet1/4
IF-MIB::ifName.436224000 = STRING: Ethernet1/5
IF-MIB::ifName.436228096 = STRING: Ethernet1/6
IF-MIB::ifName.436232192 = STRING: Ethernet1/7
IF-MIB::ifName.436236288 = STRING: Ethernet1/8
IF-MIB::ifName.436240384 = STRING: Ethernet1/9
IF-MIB::ifName.436244480 = STRING: Ethernet1/10
IF-MIB::ifName.436248576 = STRING: Ethernet1/11
IF-MIB::ifName.436252672 = STRING: Ethernet1/12
IF-MIB::ifName.436256768 = STRING: Ethernet1/13
IF-MIB::ifName.436260864 = STRING: Ethernet1/14
IF-MIB::ifName.436264960 = STRING: Ethernet1/15
IF-MIB::ifName.436269056 = STRING: Ethernet1/16

IF-MIB::ifDescr.436240384 = STRING: 
IF-MIB::ifDescr.436244480 = STRING: 
IF-MIB::ifDescr.436248576 = STRING: 
IF-MIB::ifDescr.436252672 = STRING: 
IF-MIB::ifDescr.436256768 = STRING: 
IF-MIB::ifDescr.436260864 = STRING: 
IF-MIB::ifDescr.436264960 = STRING: 
IF-MIB::ifDescr.436269056 = STRING: 
IF-MIB::ifDescr.436273152 = STRING: 
IF-MIB::ifDescr.436277248 = STRING: 
IF-MIB::ifDescr.436281344 = STRING: 
IF-MIB::ifDescr.436285440 = STRING: 
IF-MIB::ifDescr.436289536 = STRING: 
IF-MIB::ifDescr.436293632 = STRING: 

I just dont know where to begin.

**Comment by laf** [comment]
Try setting:

`$config['os']['nxos']['ifname'] = true`

**Comment by thomasraabo** [comment]
That worked.

What is the logic behind it?

**Comment by laf** [comment]
Ask Cisco, they decided to not send ifDescr :/

However this just forces that device type to use ifName for the 'label'

**Comment by thomasraabo** [comment]
created a ticket with cisco... thanks.
