### ISSUE TITLE
APC NetBotz Rack Monitor 200 Does not Poll correctly

### ISSUE THREAD

**Issue by upcboy** [librenms/librenms#4415]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.

- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

Polling my APC NetBotz Rack Monitor 200 does not give Temperature/Humidity there is a netbotz OS it seems but it does not detect this device nor its sensors that are attached.

Below are the results from discovery.php and poller.php 

====================================
Version info:
Commit SHA: 9e85f24b000ed158ca11fdb6890bb986c2063967
DB Schema: 118
PHP: 7.0.10
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2
====================================

[discovery.txt](https://github.com/librenms/librenms/files/467797/discovery.txt)
[poller.txt](https://github.com/librenms/librenms/files/467796/poller.txt)

**Comment by Rosiak** [comment]
Please post the output of:
```
snmpbulkwalk -On -v2c -c COMMUNITY HOSTNAME .
```

**Comment by upcboy** [comment]
Attached is the output of snmpbulkwalk -On -v2c -c COMMUNITY HOSTNAME .
[snmpbulkwalk.txt](https://github.com/librenms/librenms/files/468054/snmpbulkwalk.txt)

**Comment by crcro** [comment]
can you post the output of snmpwalk with loaded mibs?

**Comment by upcboy** [comment]
Can you tell me how I would do that?

**Comment by crcro** [comment]
first you must find the necessary MIB (mainly from APC site) and then edit your snmp.conf and add the APC mibs there like:

 mibs +YOUR-MIB
 mibs +YOUR2-MIB

or run:

snmpwalk -m +YOUR-MIB

**Comment by murrant** [comment]
@upcboy, can you update LibreNMS and test?

**Comment by upcboy** [comment]
It looks to be polling the Humidity and Temperature correctly now! Thank you for your help!
