### ISSUE TITLE
Graphing interface errors over time instead of per-second.

### ISSUE THREAD

**Issue by network-guy** [librenms/librenms#4416]
Currently the interface errors graphs show errors per second. This is not very helpful much of the time when it's recording 200 millionths of an error per second. It would be a lot more helpful to see errors over time instead. It should make it easier to tell when errors are incrementing over time. Is this something that could be implemented, either to replace the current errors/sec graph or as an option to replace it?

**Comment by murrant** [comment]
I'm not trying to be rude, but why would you care about 1 error in 23 days?  At what level is it significant?

**Comment by network-guy** [comment]
I don't care about a small number of errors. That's kinda my point. But when I'm looking at the graphs, I've got one device that's throwing about 10 CRC errors per day, and it's showing about 6-8 spikes per day and nothing the rest of the time. The spikes are recorded as errors/second, and since there is less than 1/sec averaged out, it's graphing it as a very small number. See the attached screenshot.

I would much rather see it graphed as total interface errors over time, instead of errors per second (similar to the uptime graph if you need a comparison). This way I can see the total interface errors and can see how they have incremented over time.

![interface-errors](https://cloud.githubusercontent.com/assets/18373118/18454266/fa1f7750-7908-11e6-8ab9-b394b8c2f034.PNG)

**Comment by laf** [comment]
Wouldn't those 6 spikes be still there though but with a value of 1 for each?

**Comment by network-guy** [comment]
There would be an increment, but it would be 1 error at a time, it wouldn't be spikes of less than one error. What I have in mind is a graph that would display the total interface errors over time instead of having a spike when some errors occurred. It would be easier to see a large jump in errors IMO since the line on the graph would have a steep incline.
