### ISSUE TITLE
Alerting for Disk IO

### ISSUE THREAD

**Issue by mfeuhrer** [librenms/librenms#4417]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

Yes, this is a brand new installation
- [ ] Please include all of the information between the 

`====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

I went to IRC today to get some help in setting up alerts for Disk IO. After talking there, I found that Disk IO can be accessed using the ucd_diskio Entity, however, I have learned that these values are not stored, and as such, alerting can not be performed. I was directed here to ask that Disk IO data values be stored and made available for alerting, as that will greatly aid in some of the issues my team is trying to identify and isolate. Thank you!

**Comment by nerdalertdk** [comment]
Check out "services" they can pretty much all nagios plugins

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-alerting-for-disk-io/691
