### ISSUE TITLE
A new feature

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#442]
Like this :  I can select a process from a device and set alerts on it when memory > 100M or is not alive

**Comment by f0o** [comment]
Hi @wzhsunn, 

you mean a button as a shortcut to create the alert-rule?

**Comment by wzhsunn** [comment]
Yes,  I think this is very useful .

**Comment by laf** [comment]
I'm not sure this will be that workable @wzhsunn as we'd end up with buttons all over the show for creating new alerts :(
