### ISSUE TITLE
Infoblox NIOS is recognised as Linux Server

### ISSUE THREAD

**Issue by FTBZ** [librenms/librenms#4420]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.

Since the past week, Infoblox appliances are recognised as Linux Server. Fix in NIOS discovery #4389 seems to be no enough.

http://pastebin.com/raw/DdzzDwRy

**Comment by murrant** [comment]
Thanks for the info, made it easy to correct the tests.
