### ISSUE TITLE
LibreNMS has no overall traffic for Fortigate version 5.4.1

### ISSUE THREAD

**Issue by Noosrep** [librenms/librenms#4421]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

Since updating my Fortigate 80D from version 5.4.0 to version 5.4.1, I don't have any overall traffic since I performed the update on friday.
![image](https://cloud.githubusercontent.com/assets/22166557/18464492/b7f69f96-7991-11e6-9c89-2d79245382bb.png)

I'm guessing this has something to do with this reported bug: [https://github.com/librenms/librenms/issues/3859](this reported bug)

I have checked if my installation was up to date, but issueing the ./daily.sh command resulted in:
```
Updating to latest codebase                        FAIL
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
```
So my ./validate also gives an error:
```
Version info:
[WARN]    Your install is out of date: 2489e70d8a3c34ae5c00204264dc01f41a22ada4 (Sun, 31 Jul 2016 17:46:15 +0200)
DB Schema: 126
PHP: 7.0.8-0ubuntu0.16.04.1
MySQL: 10.0.25-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP version: 5.7.3
[OK]      Database connection successful
```

Is there another way I can update my installation and generate the graph again? Note, I'm a first time user of LibreNMS so I'm not sure which logfiles, code etc you need.

**Comment by laf** [comment]
Check logs/daily.log to see why it couldn't up date.

**Comment by Noosrep** [comment]
That results in following output:
```
Updating to latest codebase
fatal: unable to access 'https://github.com/librenms/librenms.git/': Could not resolve host: github.com
Returned: 1
Updating SQL-Schema

Returned: 0
Updating submodules

Returned: 0
Cleaning up DB
Device performance times cleared for entries over 7 days
Returned: 0
Fetching notifications
[ Tue, 13 Sep 2016 08:55:16 +0000 ] http://www.librenms.org/notifications.rss (1)
[ Tue, 13 Sep 2016 08:55:16 +0000 ] misc/notifications.rss (5)
[ Tue, 13 Sep 2016 08:55:16 +0000 ] Updating DB  Done
Returned: 0
```
Looks like the problem lies in the fatal error. Perhaps something that is blocked in my network?

**Comment by Noosrep** [comment]
LibreNMS is up to date now:
```
Updating to latest codebase                        OK
Updated from 2489e70d8a3c34ae5c00204264dc01f41a22ada4 to ec9383be60f12881baff3f264f2b3f9cf39e0abb OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK

```

**Comment by Noosrep** [comment]
No update yet? Don't see any errors in the logfiles so any help would be appreciated

**Comment by laf** [comment]
Have you followed what the issue said to do that you linked to?

**Comment by Noosrep** [comment]
Didn't see the new comments in that thread! The graphs are updating again. For future reference, I issued following commands for each of my interfaces:
conf sys int
   edit port1
      set description "LAN"
      set alias "LAN"
   next
end
