### ISSUE TITLE
Documentation: Apache application missing instructions

### ISSUE THREAD

**Issue by mzac** [librenms/librenms#4424]
In the documentation for the Apache application, it should be mentioned that the server status module and config needs to be added/modified.

<pre>
a2enmod status
</pre>

Edit /etc/apache2/mods-enabled/status.conf

```
ExtendedStatus On
<Location /server-status>
    SetHandler server-status
    Order deny,allow
    Deny from all
    Allow from 127.0.0.1 ::1
</Location>

```

Reload apache

```
/etc/init.d/apache2 reload
```

or

```
systemctl reload apache2
```

**Comment by laf** [comment]
This is something you can easily contribute :)

**Comment by laf** [comment]
No further info provided
