### ISSUE TITLE
Devices and graphs suddenly missing

### ISSUE THREAD

**Issue by brandonegbert** [librenms/librenms#4425]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

```
./validate.php
====================================
Version info:
Commit SHA: a8efda8f309b23d574a58506448b2a5023715e5d
DB Schema: 133
PHP: 5.5.9-1ubuntu4.14
MySQL: 5.5.47-MariaDB-1ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

====================================
[OK]      Database connection successful
[WARN]    You have the old alerting system enabled - this is to be deprecated on the 1st of June 2015: https://groups.google.com/forum/#!topic/librenms-project/1llxos4m0p4
```

All of my devices and graphs are no longer displaying in the web GUI.  The Statistics section of about LibreNMS lists them as still being there.  I have an error about a schema update in daily.log:

```
[ Mon, 12 Sep 2016 00:15:10 -0400 ] Updating DB  Done
Returned: 0
Updating to latest codebase

Returned: 0
Updated from 195a8ee3493d6bd6c777c383f22d2b4956a283bf to ec9383be60f12881baff3f264f2b3f9cf39e0abb

Returned: 0
Updating SQL-Schema
-- Updating database schema
132 -> 133 ... done (1 errors).
-- Done
```

**Comment by laf** [comment]
Just update, - ./daily.sh as librenms user.
