### ISSUE TITLE
Add support for Arris Cadant C4 CMTS

### ISSUE THREAD

**Issue by docsiswantsthis** [librenms/librenms#4434]
snmpwalk, poller and discover output here:
https://mega.nz/#!TNYwlLLA!lL2FlP2EYNvlipsyesMgt1q7YNh_GPFpqAgtGDMHKyU
unzip pass provided to laf via IRC.
Warning! Text file contains more than a million lines.

Regarding OS name, I'm not sure and can't find anywhere if Arris calls their OS something, a "show version" command run on the CMTS yields some card info and "Chassis Type: C4". 

The main metric we're looking for that's missing from the generic SNMP polling that LibreNMS does is offline/online modem counts on each Cable MAC. An example is OID .1.3.6.1.4.1.4998.1.1.20.2.26.1.1.536870914 pulls offline modem info for Cable MAC 1.

**Comment by crcro** [comment]
you should post the password for that file :) unless @laf would like to work on it

**Comment by docsiswantsthis** [comment]
@crcro I'd like to provide it however I'd prefer not sharing it publicly, if possible. Let me know what the most appropriate way to send it to you guys is.

**Comment by laf** [comment]
Yeah I have the pw if anyone gets round to adding support (I'll do it at the weekend if no one else picks up). Hit me up on irc for pw.

**Comment by laf** [comment]
What was your name on irc - I can't remember :(

**Comment by docsiswantsthis** [comment]
That's a good question, perhaps cmtsguy or something along those lines? Are you looking for the logs?

**Comment by laf** [comment]
I've submitted a pr to add detection.

As for offline/online modem counts on each Cable MAC, the OID you have given is one of many in that output and doesn't mean anything to me. Do you have a MIB we can use to see what the data is?

**Comment by docsiswantsthis** [comment]
Yes, I've requested them and will get back to you with the MIB.

**Comment by docsiswantsthis** [comment]
Well that was fast.
[CMTS_V08.02.00.97mibs.zip](https://github.com/librenms/librenms/files/645881/CMTS_V08.02.00.97mibs.zip)

**Comment by laf** [comment]
Their's like 40 files in that :) If you can get me the name of the OID then we can look into it further.

**Comment by laf** [comment]
No further info provided.

**Comment by docsiswantsthis** [comment]
I'll get back to you on this, I haven't forgotten about it.
