### ISSUE TITLE
Is there some sample of creating  alerts or  creating alert template ?

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#445]
.

**Comment by f0o** [comment]
Alert-rules are being created using the wizzard in the GUI.

Alert-templates are documented in the docs (http://docs.librenms.org/Extensions/Alerting/)

**Comment by f0o** [comment]
Worth to mention that the limitations of the template-syntax are lifted. We now support unlimited nested controls and we can access the entire scope of informations to an alert. %value.dbfield is the correct syntax. Default uses %value.string which is a very general consolidation of the available information.

**Comment by f0o** [comment]
@wzhsunn if you dont have any issue with alerting/rules/templates, please close this issue :)

**Comment by wzhsunn** [comment]
Your Info is very useful, I test it and debug  now .

**Comment by wzhsunn** [comment]
I try this :

Create new alerts rule :
```
%processes.command ~ "@mysqld@"
```

run 
```
php poller.php -h 1

php discovery.php -h 1

php alerts.php
```

And I open the 
```
http://localhost:8080/alerts/
```
There is no alerts about the rule .

I debug it and found that the table processes is empty .

What's the problem ?

**Comment by f0o** [comment]
Do you have check_mk on the host and the unix-agent plloer module enabled?

**Comment by wzhsunn** [comment]
OK, sorry , I will try in IRC .
