### ISSUE TITLE
Overlapping instances of discovery -h new

### ISSUE THREAD

**Issue by candlerb** [librenms/librenms#4459]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [X] Please provide as much detail as possible.

Discovery of new devices (`-h new`) is launched from cron every 5 minutes. But if the discovery takes longer than 5 minutes, then you get multiple instances running concurrently, all trying to discover the same devices.

```
root@pc13:~# ps auxwww | grep disc
librenms  9120  0.0  0.0   4508   716 ?        Ss   11:00   0:00 /bin/sh -c    /opt/librenms/discovery.php -h new >> /dev/null 2>&1
librenms  9122  0.0  0.1 282516 26984 ?        S    11:00   0:01 php /opt/librenms/discovery.php -h new
librenms 14480  0.0  0.0   4508   680 ?        Ss   11:05   0:00 /bin/sh -c    /opt/librenms/discovery.php -h new >> /dev/null 2>&1
librenms 14481  0.0  0.1 282516 26240 ?        S    11:05   0:00 php /opt/librenms/discovery.php -h new
root     15071  0.0  0.0  11284   928 ?        S+   11:05   0:00 grep --color=auto disc
```

And then:

```
root@pc13:~# ps auxwww | grep disc
librenms  9120  0.0  0.0   4508   716 ?        Ss   11:00   0:00 /bin/sh -c    /opt/librenms/discovery.php -h new >> /dev/null 2>&1
librenms  9122  0.0  0.1 282516 26984 ?        S    11:00   0:02 php /opt/librenms/discovery.php -h new
librenms 14480  0.0  0.0   4508   680 ?        Ss   11:05   0:00 /bin/sh -c    /opt/librenms/discovery.php -h new >> /dev/null 2>&1
librenms 14481  0.0  0.1 282648 26876 ?        S    11:05   0:00 php /opt/librenms/discovery.php -h new
librenms 20118  0.0  0.0   4508   796 ?        Ss   11:10   0:00 /bin/sh -c    /opt/librenms/discovery.php -h new >> /dev/null 2>&1
librenms 20120  0.0  0.1 282136 25740 ?        S    11:10   0:00 php /opt/librenms/discovery.php -h new
root     20179  0.0  0.0  11284  1016 ?        S+   11:10   0:00 grep --color=auto disc
```

Load average continues to climb.

Note: discovery _is_ actually taking place, in that devices are slowing being categorised properly. But there are multiple discovery processes running and `strace -f -p <pid>` shows they are all doing work. I suspect this will collapse if it continues.

Once it got up to four concurrent discovery jobs, I did the following to stop collapse:

```
update devices set last_discovered=now() where status=1;
```

(since I know that the first discovery process already did a select() which retrieved all the new devices waiting to be discovered). This meant the next 5-minute process terminated quickly as it had no work to do.

Now, to cause this to happen I have an arguably unrealistic scenario: I have 12 librenms instances running on the same physical hardware, which is a quad-core i7, all doing their discovery at the same time, and all discovering the same devices.

But I still think librenms should be made robust against this issue (e.g. consider what happens if you add 1000 devices and then `discovery.php -h new` runs from cron)

A simple workaround would be to set last_discovered to the current time as soon as you _start_ the discovery, so that subsequent `discovery.php -h new` calls will skip them.

**Comment by laf** [comment]
If you have a fix, submit it for inclusion.

**Comment by laf** [comment]
Been thinking about this tonight and other than a rewrite, we have a few options:

1. Create a lock file when running -h new so we don't run again if it exists. Has the problem that if discovery crashes then -h new will no longer run (we could invalidate the lock fail on daily.sh runs if it's > 24 hours old or something).

2. Do nothing. This isn't a common issue and others don't seem to hit it.

3. Update the devices last_discovered time before we start discovery_device() for it. This would mean it would not be picked up as new if discovery was interrupted in anyway but would be discovered within the next 6 hours anyway.

@librenms/reviewers Thoughts? 2 and 3 are easy fixes but 1 seems a bit better.

**Comment by paulgear** [comment]
My feeling is that introducing lock files could create as many problems as it solves, and if we're going to deal with them in daily.sh, then we could have up to 24 hours lag in discovery, whereas option 3 would have a maximum of 6 hours (by default).  In addition, if we could reliably detect whether discovery failed or succeeded, we could reverse the last_discovered time change on failed discoveries to cut that down even further.  By taking approach 3, we are automatically preventing the next '-h new' discovery from overlapping on the same device.

**Comment by laf** [comment]
We use a lock file with perfect success in alerts.php. It would also only be used for -h new so as per option 3 the device would be discovered within the 6 hours anyway. Yes it could stop other new devices from being discovered but that would only happen if discovery crashed without completing which we don't see happening especially with all the testing we do for new code. 

I can't think of any reliable way for us to determine discovery didn't complete without going down a rabbit hole of hacks to compliment a hack in the first place for 3. So for that choice we should just do the basic hack of setting the date or nothing at all imho

**Comment by paulgear** [comment]
If you're confident you can make lock files work reliably, then go for it. :-)

**Comment by laf** [comment]
I've added functions to centralize locking in #6469. If that gets merged it will be as easy as adding a set_lock('new-discovery') to the -h new call.
