### ISSUE TITLE
toner not graphing in one area

### ISSUE THREAD

**Issue by BloodyIron** [librenms/librenms#4464]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

====================================
Version info:
Commit SHA: 4eb896005004d59c89753cdf795274ee2379a56b
DB Schema: 133
PHP: 5.5.9-1ubuntu4.19
MySQL: 5.5.52-0ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

====================================
[OK]      Database connection successful

Some of the toner graphs don't generate correctly, some do. In this case, I think it's the toner usage graph. When I "show RRD command", I get the following:

RRDTool Command
rrdtool graph /tmp/xJrT0xuApiQlYxyR.png -l 0 -u 100 -E --start 1473962700 --end 1474049100 --width 1728 --height 490.5 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal COMMENT:' Cur Max\n' DEF:toner1=/opt/librenms/rrd/IP.OF.HOST.REDACTED/toner-1.rrd:toner:AVERAGE LINE1:toner1#000000:'Black Toner S/N :REDACTED' AREA:toner1#92b7d3: GPRINT:toner1:LAST:'%5.0lf%%' GPRINT:toner1:MAX:%5.0lf%%\\l

RRDTool Output
ERROR: I don't understand 'RUM-1412' in command: 'LINE1:toner1#000000:Black Toner S/N :REDACTED'. 

Not sure what to do

**Comment by crcro** [comment]
please provide output of:

./poller.php -h <<your_host>>
./discovery.php -h <<your_host>>

**Comment by BloodyIron** [comment]
LibreNMS Poller
Version info:
Commit SHA: 4eb896005004d59c89753cdf795274ee2379a56b
Commit Date: 1474019784
DB Schema: 133
PHP: 5.5.9-1ubuntu4.19
MySQL: 5.5.52-0ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

Starting polling run:

HOSTIP.REDACTED 19 samsungprinter (printer)
Using hrSystemUptime (1405s)
Uptime: 23m 25s
Module [ unix-agent ] disabled globally.

#### Load poller module os ####

Hardware: C410 Series Version:  Features:  Serial: REDACTED

>> Runtime for poller module 'os': 0.13024687767029 seconds
#### Unload poller module os ####


#### Load poller module ipmi ####

>> Runtime for poller module 'ipmi': 0.00053286552429199 seconds
#### Unload poller module ipmi ####


#### Load poller module sensors ####

>> Runtime for poller module 'sensors': 0.0012331008911133 seconds
#### Unload poller module sensors ####


#### Load poller module processors ####
Processor CPU... 0%

>> Runtime for poller module 'processors': 0.047371864318848 seconds
#### Unload poller module processors ####


#### Load poller module mempools ####
Mempool RAM: 44.77% 

>> Runtime for poller module 'mempools': 0.054413080215454 seconds
#### Unload poller module mempools ####


#### Load poller module storage ####

>> Runtime for poller module 'storage': 0.00029802322387695 seconds
#### Unload poller module storage ####


#### Load poller module netstats ####
 IP TCP UDP ICMP SNMP IP-FORWARD

>> Runtime for poller module 'netstats': 0.32311010360718 seconds
#### Unload poller module netstats ####


#### Load poller module hr-mib ####
 Processes Users

>> Runtime for poller module 'hr-mib': 0.047152042388916 seconds
#### Unload poller module hr-mib ####


#### Load poller module ucd-mib ####

>> Runtime for poller module 'ucd-mib': 0.14371013641357 seconds
#### Unload poller module ucd-mib ####


#### Load poller module ipSystemStats ####


>> Runtime for poller module 'ipSystemStats': 0.06694483757019 seconds
#### Unload poller module ipSystemStats ####


#### Load poller module ports ####
Caching Oids: dot3StatsDuplexStatusvalidvalidvalid
Port : Embedded Ethernet Controller, 10/100 Mbps, v1.0, UTP RJ-45, connector A1, 100 full duplex (1 / #228) VLAN == Embedded Ethernet Controller, 10/100 Mbps, v1.0, UTP RJ-45, connector A1, 100 full duplexbps(16kbps/17.8kbps)bytes(46.8kB/52.2kB)pkts(9.46pps/9.5pps)
Port : Loopback Interface (2 / #229) VLAN == Loopback Interfacebps(6.44kbps/12.8kbps)bytes(18.8kB/37.7kB)pkts(4.67pps/10.6pps)
Port : Embedded Ethernet Controller, 10/100 Mbps, v1.0, UTP RJ-45, connector A1, 100 full duplex (3 / #230) VLAN == Embedded Ethernet Controller, 10/100 Mbps, v1.0, UTP RJ-45, connector A1, 100 full duplexbps(0bps/880bps)bytes(0B/2.58kB)pkts(0pps/0pps)

>> Runtime for poller module 'ports': 0.29066300392151 seconds
#### Unload poller module ports ####


#### Load poller module bgp-peers ####

>> Runtime for poller module 'bgp-peers': 0.0011610984802246 seconds
#### Unload poller module bgp-peers ####


#### Load poller module junose-atm-vp ####

>> Runtime for poller module 'junose-atm-vp': 0.00050115585327148 seconds
#### Unload poller module junose-atm-vp ####


#### Load poller module toner ####
Checking toner Black Toner S/N :CRUM-REDACTED... 67 %
Checking toner Cyan Toner S/N :CRUM-REDACTED... 14 %
Checking toner Magenta Toner S/N :CRUM-REDACTED... 9 %
Checking toner Yellow Toner S/N :CRUM-REDACTED... 0 %

>> Runtime for poller module 'toner': 0.37185502052307 seconds
#### Unload poller module toner ####


#### Load poller module ucd-diskio ####

>> Runtime for poller module 'ucd-diskio': 0.00036406517028809 seconds
#### Unload poller module ucd-diskio ####


#### Load poller module wifi ####


>> Runtime for poller module 'wifi': 0.00027203559875488 seconds
#### Unload poller module wifi ####


#### Load poller module ospf ####
Processes:  Areas:  Ports:  Neighbours: 


>> Runtime for poller module 'ospf': 0.22227501869202 seconds
#### Unload poller module ospf ####


#### Load poller module cisco-ipsec-flow-monitor ####

>> Runtime for poller module 'cisco-ipsec-flow-monitor': 0.00027012825012207 seconds
#### Unload poller module cisco-ipsec-flow-monitor ####


#### Load poller module cisco-remote-access-monitor ####

>> Runtime for poller module 'cisco-remote-access-monitor': 0.00010490417480469 seconds
#### Unload poller module cisco-remote-access-monitor ####


#### Load poller module cisco-cef ####

>> Runtime for poller module 'cisco-cef': 0.00025796890258789 seconds
#### Unload poller module cisco-cef ####


#### Load poller module cisco-sla ####

>> Runtime for poller module 'cisco-sla': 0.14018297195435 seconds
#### Unload poller module cisco-sla ####


#### Load poller module cisco-mac-accounting ####

>> Runtime for poller module 'cisco-mac-accounting': 0.00028204917907715 seconds
#### Unload poller module cisco-mac-accounting ####


#### Load poller module cipsec-tunnels ####

>> Runtime for poller module 'cipsec-tunnels': 0.11955881118774 seconds
#### Unload poller module cipsec-tunnels ####


#### Load poller module cisco-ace-loadbalancer ####

>> Runtime for poller module 'cisco-ace-loadbalancer': 0.062770843505859 seconds
#### Unload poller module cisco-ace-loadbalancer ####


#### Load poller module cisco-ace-serverfarms ####

>> Runtime for poller module 'cisco-ace-serverfarms': 0.057255983352661 seconds
#### Unload poller module cisco-ace-serverfarms ####


#### Load poller module netscaler-vsvr ####

>> Runtime for poller module 'netscaler-vsvr': 0.00032496452331543 seconds
#### Unload poller module netscaler-vsvr ####


#### Load poller module aruba-controller ####

>> Runtime for poller module 'aruba-controller': 0.00036096572875977 seconds
#### Unload poller module aruba-controller ####


#### Load poller module entity-physical ####


>> Runtime for poller module 'entity-physical': 0.00031805038452148 seconds
#### Unload poller module entity-physical ####


#### Load poller module applications ####

>> Runtime for poller module 'applications': 0.00019097328186035 seconds
#### Unload poller module applications ####


#### Load poller module cisco-asa-firewall ####

>> Runtime for poller module 'cisco-asa-firewall': 0.00011992454528809 seconds
#### Unload poller module cisco-asa-firewall ####

Module [ mib ] disabled globally.

#### Load poller module cisco-voice ####

>> Runtime for poller module 'cisco-voice': 5.0067901611328E-5 seconds
#### Unload poller module cisco-voice ####


#### Load poller module cisco-cbqos ####

>> Runtime for poller module 'cisco-cbqos': 0.00017499923706055 seconds
#### Unload poller module cisco-cbqos ####


#### Load poller module stp ####


>> Runtime for poller module 'stp': 0.046292066574097 seconds
#### Unload poller module stp ####


#### Load poller module cisco-otv ####

>> Runtime for poller module 'cisco-otv': 0.00051689147949219 seconds
#### Unload poller module cisco-otv ####


#### Load poller module ntp ####

>> Runtime for poller module 'ntp': 5.5074691772461E-5 seconds
#### Unload poller module ntp ####


#### Load poller module services ####

>> Runtime for poller module 'services': 4.1007995605469E-5 seconds
#### Unload poller module services ####

uptime netstat_ip netstat_ip_frag netstat_tcp netstat_udp netstat_icmp netstat_icmp_info netstat_snmp netstat_snmp_pkt hr_processes hr_users Polled in 2.740 seconds
UPDATED!


MySQL: Cell[1/0s] Row[8/0s] Rows[34/0s] Column[3/0s] Update[13/0.04s] Insert[2/0.01s] Delete[0/0s]

**Comment by BloodyIron** [comment]
LibreNMS Discovery
Version info:
Commit SHA: 4eb896005004d59c89753cdf795274ee2379a56b
DB Schema: 133
PHP: 5.5.9-1ubuntu4.19
MySQL: 5.5.52-0ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

REDACTED.IP 19 samsungprinter  (printer)
#### Load disco module os ####

>> Runtime for discovery module 'os': 0.269 seconds
#### Unload disco module os ####

#### Load disco module ports ####
...

>> Runtime for discovery module 'ports': 0.152 seconds
#### Unload disco module ports ####

#### Load disco module ports-stack ####


>> Runtime for discovery module 'ports-stack': 0.037 seconds
#### Unload disco module ports-stack ####

#### Load disco module entity-physical ####

Caching OIDs: entPhysicalEntry entAliasMappingIdentifier

>> Runtime for discovery module 'entity-physical': 0.118 seconds
#### Unload disco module entity-physical ####

#### Load disco module processors ####
 hrDevice: .

>> Runtime for discovery module 'processors': 0.141 seconds
#### Unload disco module processors ####

#### Load disco module mempools ####
hrStorage : .

>> Runtime for discovery module 'mempools': 0.181 seconds
#### Unload disco module mempools ####

#### Load disco module cisco-vrf-lite ####

>> Runtime for discovery module 'cisco-vrf-lite': 0.000 seconds
#### Unload disco module cisco-vrf-lite ####

#### Load disco module ipv4-addresses ####
s.s.s.

>> Runtime for discovery module 'ipv4-addresses': 0.212 seconds
#### Unload disco module ipv4-addresses ####

#### Load disco module ipv6-addresses ####


>> Runtime for discovery module 'ipv6-addresses': 18.24 seconds
#### Unload disco module ipv6-addresses ####

Module [ route ] disabled globally.

#### Load disco module sensors ####
Pre-cache: 
 ENTITY-SENSOR: Caching OIDs: entPhySensorType entPhySensorScale entPhySensorPrecision entPhySensorValue
Temperatures: 
Humidity : 
Voltages: 
Frequencies: 
Current: 
Power: 
Fanspeeds : 
Battery Charge: 
Load: 
States: 
dBm: 
Signal: 

>> Runtime for discovery module 'sensors': 25.37 seconds
#### Unload disco module sensors ####

#### Load disco module storage ####
hrStorage : 

>> Runtime for discovery module 'storage': 0.496 seconds
#### Unload disco module storage ####

#### Load disco module hr-device ####
.....

>> Runtime for discovery module 'hr-device': 0.464 seconds
#### Unload disco module hr-device ####

#### Load disco module discovery-protocols ####
 CISCO-CDP-MIB:  LLDP-MIB:  OSPF Discovery: enabled


>> Runtime for discovery module 'discovery-protocols': 0.391 seconds
#### Unload disco module discovery-protocols ####

#### Load disco module arp-table ####


>> Runtime for discovery module 'arp-table': 0.099 seconds
#### Unload disco module arp-table ####

Module [ discovery-arp ] disabled globally.

#### Load disco module junose-atm-vp ####

>> Runtime for discovery module 'junose-atm-vp': 0.000 seconds
#### Unload disco module junose-atm-vp ####

#### Load disco module bgp-peers ####
No BGP on host
FIN BGP 



>> Runtime for discovery module 'bgp-peers': 0.099 seconds
#### Unload disco module bgp-peers ####

#### Load disco module vlans ####
IEEE8021-Q-BRIDGE-MIB VLANs : 

>> Runtime for discovery module 'vlans': 0.098 seconds
#### Unload disco module vlans ####

#### Load disco module cisco-mac-accounting ####

>> Runtime for discovery module 'cisco-mac-accounting': 0.000 seconds
#### Unload disco module cisco-mac-accounting ####

#### Load disco module cisco-pw ####

>> Runtime for discovery module 'cisco-pw': 0.000 seconds
#### Unload disco module cisco-pw ####

#### Load disco module cisco-vrf ####

>> Runtime for discovery module 'cisco-vrf': 0.000 seconds
#### Unload disco module cisco-vrf ####

#### Load disco module cisco-sla ####

>> Runtime for discovery module 'cisco-sla': 0.000 seconds
#### Unload disco module cisco-sla ####

#### Load disco module vmware-vminfo ####

>> Runtime for discovery module 'vmware-vminfo': 0.000 seconds
#### Unload disco module vmware-vminfo ####

#### Load disco module libvirt-vminfo ####

>> Runtime for discovery module 'libvirt-vminfo': 0.000 seconds
#### Unload disco module libvirt-vminfo ####

#### Load disco module toner ####
Jetdirect U.UU

>> Runtime for discovery module 'toner': 1.097 seconds
#### Unload disco module toner ####

#### Load disco module ucd-diskio ####


>> Runtime for discovery module 'ucd-diskio': 0.099 seconds
#### Unload disco module ucd-diskio ####

#### Load disco module services ####


>> Runtime for discovery module 'services': 0.000 seconds
#### Unload disco module services ####

#### Load disco module charge ####

>> Runtime for discovery module 'charge': 5.507 seconds
#### Unload disco module charge ####

Module [ cisco-cbqos ] disabled globally.

#### Load disco module stp ####


>> Runtime for discovery module 'stp': 0.047 seconds
#### Unload disco module stp ####

#### Load disco module cisco-otv ####

>> Runtime for discovery module 'cisco-otv': 0.000 seconds
#### Unload disco module cisco-otv ####

#### Load disco module ntp ####

>> Runtime for discovery module 'ntp': 4.315 seconds
#### Unload disco module ntp ####

Discovered in 47.63 seconds

MySQL: Cell[1/0s] Row[40/0.01s] Rows[24/0.01s] Column[0/0s] Update[17/0.04s] Insert[1/0s] Delete[0/0s]

**Comment by crcro** [comment]
please post them as pastebin links :)

**Comment by BloodyIron** [comment]
... I just posted the whole thing as you asked so it's visible without an external source... so... no, please use the info I provided as you requested

**Comment by crcro** [comment]
you realize that your are asking for help, right? 
pastebin are easier to read and to find the issue than a formatted github comment don't you think?

**Comment by BloodyIron** [comment]
Yes. And I'm trying to avoid arguing here, but realize that while I know yours (and others) time is precious, so is mine. I've provided the info requested, and I'm not going to just bark on command. I'm sorry the info isn't on pastebin, but that's life, you don't always get what you want.

If you want to help, the info is there. I know you probably don't like what I have to say, but I have work I need to get to too, which is why I was avoiding having to explain this, but I guess I have to.

Either way, whatever help happens, is appreciated, and please keep in mind we all have our own priorities too.

**Comment by laf** [comment]
@BloodyIron That is an extremely rude response to someone who is doing nothing more than trying to help you when they don't have to. Everyone's time is precious but when you're asking for help then you need to go the extra mile and not the other way round.

@crcro has kindly submitted a fix for this, a big thank you to him
