### ISSUE TITLE
Autoupdate is failing

### ISSUE THREAD

**Issue by mail3dexter** [librenms/librenms#4466]
====================================
Version info:
[WARN]    Your install is out of date: 58599e95ba48f55ecea2fc9e5ac29b5e44318e31 (Tue, 06 Sep 2016 17:00:05 +0000)
[WARN]    Your local git contains modified files, this could prevent automatic updates.
Modified files:
    includes/defaults.inc.php
DB Schema: 132
PHP: 5.3.3
MySQL: 5.1.73
RRDTool: 1.3.8
SNMP: NET-SNMP version: 5.5

====================================  

I had changed the default graph type from detail to basic as some of the juniper network devices are in stack/virtual-chassis and hence it shows me 8 * 50 ports = 400 ports on single page due to which it takes time to render graphs.

[abc@librenms-adc librenms]$ git diff
diff --git a/includes/defaults.inc.php b/includes/defaults.inc.php
index c3cda71..96eab62 100644
--- a/includes/defaults.inc.php
+++ b/includes/defaults.inc.php
@@ -169,7 +169,7 @@ $config['show_locations_dropdown'] = 1;
 // Enable Locations dropdown on menu
 $config['show_services'] = 0;
 // Enable Services on menu
-$config['ports_page_default'] = 'details';
+$config['ports_page_default'] = 'basic';
 // eg "details" or "basic"
 // Adding Host Settings
 $config['addhost_alwayscheckip']   = false;   # TRUE - check for duplicate ips even when adding host by name. FALSE- only check when adding host by ip. 

Is there any way by which I can retain that config and also auto upgrade?

**Comment by crcro** [comment]
i think that you should make you configuration in config.php not in includes/default.inc.php, so i suggest that you revert back and changes to it and make $config['ports_page_default'] = 'basic'; change into /opt/librenms/config.php

**Comment by Rosiak** [comment]
Make changes to config.php, not defaults.inc.php as this will break updates.
Closing.
