### ISSUE TITLE
snmpd high cpu usage causing unable to fetch data !!

### ISSUE THREAD

**Issue by shahzaibcb** [librenms/librenms#4467]
Hi,

We're polling around 10+ FreeBSD-10 servers but one of it is randomly breaking its polling, on checking it we found that if we try to validate host , it gives no response error :- 
http://prntscr.com/ciubes

On checking the effected node we found that snmp process is taking really high CPU usage on it :- 
http://prntscr.com/ciufow

We further checked our Host node to see if validation has any error but found none :- 
http://prntscr.com/ciu9fz

PS: Please take a note that all 10 servers are using same services & under same load but the only difference is that affected one under high SNMP usage.

Thanks.
Shahzaib

**Comment by crcro** [comment]
from your print screen i see a high load, maybe there is something wrong with the HDD or FS of that host?

**Comment by shahzaibcb** [comment]
Hi,
We've rebooted server to check if it fixes it & now its not showing no response error & snmp process looks OK with usage now. I guess, i'll close the ticket now.

Thanks for your help on it !!
