### ISSUE TITLE
Ports & graph mismatch !!

### ISSUE THREAD

**Issue by shahzaibcb** [librenms/librenms#4468]
Hi,

I'd like to inform that we've recently started experiencing the issue where Port speed under Ports tab only shows 1Gbps realtime traffic while the same Port speed under its graph shows accurate traffic (8Gbps). Here is the sample links to check :- 

 http://prntscr.com/ciuj8r == showing wrong speed
http://prntscr.com/ciujuo == showing correct speed

This issue was not there week back, so i think some recent update caused it.

Thanks.
Shahzaib

**Comment by crcro** [comment]
link in romania 8gbps :) nicey :D

**Comment by shahzaibcb** [comment]
should i consider it as security threat ? :-| :)

**Comment by crcro** [comment]
i know, vox :)
not really, romanian here :D

**Comment by shahzaibcb** [comment]
wow great, may i ask your name please ? :-) 

It'd be really kind of you if i can add you over skype & have some chit chat :-)

**Comment by shahzaibcb** [comment]
another issue to report, here we've another Dell S60 switch which randomly polls & breaks. Here i tried validating it and encountered error "Unpingable" while ping is working :- 

http://prntscr.com/civ14i

That's how its randomly breaks:- 
 http://prntscr.com/civ1wt

**Comment by crcro** [comment]
i think for the dell s60 you should open another issue.
just drop me an email at crc [at] nuamchefazi [.] ro ;)
