### ISSUE TITLE
Ubiquity UniFi Switches showing Wrong uptime

### ISSUE THREAD

**Issue by TyShawn76** [librenms/librenms#4470]
I just added two Unifi Switches to my network and LibreNMS is showing the wrong uptime for the switches. Ob..... is showing the correct uptime along with the SNMP walk showing the right uptime. When I add the device as brand-new it shows up fine for a duration of time but after a little bit it changes and adds about 150 days to the uptime.

Version	4eb8960 - Fri Sep 16 2016 05:56:24 GMT-0400
DB Schema	#133
Apache	2.4.10 (Raspbian)
PHP	5.6.24-0+deb8u1
MySQL	10.0.26-MariaDB-0+deb8u1
RRDtool	1.4.8

1so.3.6.1.2.1.1.1.0 = STRING: "USW-24P-250, 3.7.17.5220, Linux 3.6.5"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.4413
iso.3.6.1.2.1.1.3.0 = Timeticks: (25677000) 2 days, 23:19:30.00
iso.3.6.1.2.1.1.4.0 = ""
iso.3.6.1.2.1.1.5.0 = STRING: "CoreSwitch-US-24-250W"
iso.3.6.1.2.1.1.6.0 = ""
iso.3.6.1.2.1.1.7.0 = INTEGER: 2
![screen shot 2016-09-16 at 5 14 55 pm](https://cloud.githubusercontent.com/assets/21324034/18601538/6509b05a-7c31-11e6-94b4-63458e443fd8.png)

Obs. screenshot removed /Rosiak

**Comment by crcro** [comment]
i think that it is a bug in the firmware? polling for snmpEngineTime.0 returns that strange value (on 2 edgeswitches that i could test, running 1.6.0 firmware) but the sysUpTime.0 return the correct value on my case (49 days)

**Comment by TyShawn76** [comment]
These switches are the Unifi switch line, not the Edgeswitch line. But it is strange that you see it there. I am also lost as to how Obser..... able to gather the correct info thats what has my mind blown.

**Comment by crcro** [comment]
pushed some changes to ignore snmpEngineTime as valid uptime for ubnt

**Comment by TyShawn76** [comment]
I did a  sudo ./daily.sh but no new update any idea how long before I can test the change?

**Comment by crcro** [comment]
it is still under Pull request, not merged into the master branch.
You can edit the file manually based on diff or wait for the merge to be done.

**Comment by TyShawn76** [comment]
Thanks guys verified this is also fixed on the Unifi switch side too.
