### ISSUE TITLE
Random polling issue !!

### ISSUE THREAD

**Issue by shahzaibcb** [librenms/librenms#4471]
Hi,
We're trying to fetch Dell S60 switch graphs but LibreNMS is not able to poll it in sequence, it randomly breaks. Here i tried validating the S60 switch and encountered error "Unpingable" while ping is working :-

http://prntscr.com/civ14i

That's how its randomly breaking:- 
http://prntscr.com/civ1wt

Thanks.
Shahzaib

**Comment by laf** [comment]
Check the poller module graphs to see what's taking a while but in general this doesn't look to be an issue in librenms.
