### ISSUE TITLE
Error Drawing Graph for Storage and Processor

### ISSUE THREAD

**Issue by benjaminburzan** [librenms/librenms#4475]
Hi,

I am getting an `Error Drawing Graph` for Storage Usage and Processor Usage but _not_ for Memory Usage. Help is much appreciated, details attached below:
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.

```
Version info:
Commit SHA: 45e41ad02e4dae2074c061356f559f8a33fc11d8
DB Schema: 133
PHP: 5.5.9-1ubuntu4.19
MySQL: 5.5.49-MariaDB-1ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2
====================================
[OK]      Database connection successful
```
- [-] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.
- If I append &debug=true to the **device storage graph page** (`https://hostname.com/graphs/to=1474106100/device=15/type=device_storage/from=1474019700/legend=yes/&debug=true`), I get okay looking SQL queries. On the PHP side, I get this:
  [http://pastebin.com/MmSEVBvJ](http://pastebin.com/MmSEVBvJ)
-  If I append &debug=true to the **graph image url** (`https://hostname.com/graph.php?to=1474106700&device=15&type=device_storage&from=1474020300&legend=yes&height=481&width=1507.5&debug=true`), I get the following output:
  [http://pastebin.com/PgVx1v2j](http://pastebin.com/PgVx1v2j) 

Thank you for your help!
Ben

**Comment by martnst** [comment]
Any updates on this would be nice.

**Comment by crcro** [comment]
@martnst ... for which device? please post a pastebin link with the output of 

./discovery.php -h your-host

maybe the device doesn't return anything for cpu load and storage on snmp ....

**Comment by laf** [comment]
No further info provided, closing.
