### ISSUE TITLE
Not showing system temp !!

### ISSUE THREAD

**Issue by shahzaibcb** [librenms/librenms#4476]
Hi,
 i wanted help about temperature monitoring, if i telnet the server over 6556 it shows IPMI data with CPU temperature but not showing it in the graph :- 

telnet == http://prntscr.com/cj0bpf
graph == http://prntscr.com/cj0qcz

PS: Its a FreeBSD server

Thanks.
Shahzaib

**Comment by crcro** [comment]
did you enable ipmi for that host?

**Comment by shahzaibcb** [comment]
yes we did & also provided IPMI user/pass

**Comment by crcro** [comment]
please provide pastebin with output of:

./poller.php -h your_host -m ipmi -d

**Comment by shahzaibcb** [comment]
Here it is : http://pastebin.com/1KH5AiTc

**Comment by crcro** [comment]
you should edit that file and remove sensitive that (like ip/host/user/pass) ;)

**Comment by shahzaibcb** [comment]
I just edited the link ;) . Where should i specify it ?

**Comment by crcro** [comment]
in the ip field, i think, like: 

ip_of_host:6556

**Comment by shahzaibcb** [comment]
do you mean here ? http://prntscr.com/cjofjt

**Comment by crcro** [comment]
yes, in that field, put the ip followed by :6556

**Comment by shahzaibcb** [comment]
Done, still same issue : http://prntscr.com/cjrlp9

Here i added it :- 
http://prntscr.com/cjrm2v

**Comment by crcro** [comment]
can you please post now the output results as pastebin links of:

./poller.php -h your_host -m ipmi -d
./discovery.php -h your_host -m ipmi -d

**Comment by shahzaibcb** [comment]
There you go : http://pastebin.com/NBpRBr0g

**Comment by crcro** [comment]
@shahzaibcb ... could you provide me on email user/pass for ipmi to try to poll the device for testing as from the output provided the ipmi doesn't return anything

**Comment by laf** [comment]
It's also worth running the ipmi command manually to see if it actually responds.

**Comment by laf** [comment]
No further information provided. Please feel free to comment and re-open.

**Comment by shahzaibcb** [comment]
@crcro please provide me your email i'll sent IPMI details there.

**Comment by Nik1000111** [comment]
Hello,
I'm facing same problem...

I think there's an issiue with ipmitool call command....

I'll add an image.
It shows command used by libreNMS to call for information
And then i've installed ipmi tools and pooled with them
(btw, this is a testing enviroment, so im not worried about passwords or IPs :D)
![image](https://cloud.githubusercontent.com/assets/25576269/22634760/aaf85618-ec2d-11e6-87c5-ecf46c9dba91.png)

**Comment by laf** [comment]
Pretty sure #5749 fixes this. Please update and try again
