### ISSUE TITLE
VyOS devices suddenly appears as Vyatta devices

### ISSUE THREAD

**Issue by sliddjur** [librenms/librenms#4486]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the ==== `
Version info:
Commit SHA: 669a2d2b55040fc14961c1bb9cbe51641ef0adb4
DB Schema: 134
PHP: 5.5.14
MySQL: 10.0.22-MariaDB
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.3
`
section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

On the 7th of september 01:10am CEST our devices changed reported OS in librenms from vyos to vyatta. This causes problems when feeding oxidized with os-info into groups.

From device/device=21/tab=logs/:
```
2016-09-07 01:10:46	System	OS Features -> VyOS 1.1.5
2016-09-07 01:10:25	System	Device OS changed vyos => vyatta
2016-09-07 01:10:25	System	Device Icon changed vyos => vyatta
```

From device/device=21/tab=overview/:
```
Vyatta VyOS 1.1.5
System Name	vyosrouter001
Resolved IP	1.1.1.1
Operating System	Vyatta 1.1.5 (VyOS 1.1.5)
```

**Comment by murrant** [comment]
I don't understand why the same OS is defined twice.  We run discovery alphabetically now, that is why it changed...

I'd suggest using model_map in your oxidized config while we get this sorted.
```yaml
model_map:
  vyatta: vyos
```

**Comment by sliddjur** [comment]
@murrant thanks for tips, we are already doing that. It only tells oxidized to handle vyos os the same way as vyatta os. 

The problem is that we have different auth on vyos and vyatta, so we need to have them set apart by different groups, which LibreNMS is supposed to do.

**Comment by murrant** [comment]
Oh, ok.  Good to know,  thanks.
