### ISSUE TITLE
Redesign 'add device' log

### ISSUE THREAD

**Issue by benwa** [librenms/librenms#4496]
Instead of using multiple alerts to show the log of adding a new host, perhaps a list-group with different context colors would be nicer.

[CodePen Mockup](http://codepen.io/_benwa/pen/vXXvVm?editors=1000#0)

**Comment by murrant** [comment]
:+1:

**Comment by Rosiak** [comment]
Go PR it! :)

**Comment by benwa** [comment]
Could you point me to where the code for this is?

**Comment by Rosiak** [comment]
html/pages/addhost.inc.php

**Comment by benwa** [comment]
Ah damn, it's using `print_error` and `print_message` in [`includes\common.php`](https://github.com/librenms/librenms/blob/184715c3241e1ead6a1788fbe59ea494fe7a64e8/includes/common.php#L119-L135).
That would break a lot of other things.

**Comment by murrant** [comment]
I've wanted to add a link to the new device on this page.
