### ISSUE TITLE
Fortinet icon

### ISSUE THREAD

**Issue by realnakrul** [librenms/librenms#4498]
Hi
Current Fortinet icon looks too big.
![capture](https://cloud.githubusercontent.com/assets/21193002/18665529/bf3a98fa-7f38-11e6-8a2e-3a9d612856f0.JPG)
I thing we should replace it with the smaller one (attached)
![fortinet](https://cloud.githubusercontent.com/assets/21193002/18665564/edb526b4-7f38-11e6-81d8-9151d52e6304.png)

**Comment by crcro** [comment]
you could submit a PR yourself :)
