### ISSUE TITLE
Ubiquiti AirFiber new MIB v3.2.1

### ISSUE THREAD

**Issue by Ftelf** [librenms/librenms#4500]
There is an updaded MIB for UBNT AirFiber FW v3.2.1 from 2016-03-11
[https://www.ubnt.com/download/airfiber/default/default/airfiber-af-5x-firmware-v321](https://www.ubnt.com/download/airfiber/default/default/airfiber-af-5x-firmware-v321)
[https://www.ubnt.com/downloads/firmwares/airfiber5X/v3.2.1/UBNT-MIB.txt](https://www.ubnt.com/downloads/firmwares/airfiber5X/v3.2.1/UBNT-MIB.txt)

Most significant change is added entries:
rxPower0
rxPower1
for RSSI

Could you please update the librenms. I have did the changes locally, but seems like I would have to alter my rrd files manually.

**Comment by Rosiak** [comment]
Hi,

We are cleaning up the issues here on GitHub, all feature requests will be moved to:
https://community.librenms.org/c/feature-requests

Hence the closure of this issue.
