### ISSUE TITLE
MySQL graphs

### ISSUE THREAD

**Issue by kbechler** [librenms/librenms#4520]
MySQL connection graph stacks all values. I think these values should be visualised as lines, not stack to be useful. Especially "Max connections" and "Max used connections" seems to be useless when stacked.

**Comment by laf** [comment]
How does this look instead?

![image](https://cloud.githubusercontent.com/assets/3941142/18817433/03615dac-8358-11e6-874a-b829d63b72bb.png)

```bash
diff --git a/html/includes/graphs/application/mysql_connections.inc.php b/html/includes/graphs/application/mysql_connections.inc.php
index 31ed1f1..f7e36c9 100644
--- a/html/includes/graphs/application/mysql_connections.inc.php
+++ b/html/includes/graphs/application/mysql_connections.inc.php
@@ -48,4 +48,4 @@ $colours   = 'mixed';
 $nototal   = 1;
 $unit_text = 'Connections';

-require 'includes/graphs/generic_multi_simplex_seperated.inc.php';
+require 'includes/graphs/generic_multi_line.inc.php';
```

**Comment by kbechler** [comment]
Looks great! That's exactly what I wanted to have.

**Comment by laf** [comment]
kk, submitting a PR now.
