### ISSUE TITLE
Add Device: Cisco ASA Sourcefire module

### ISSUE THREAD

**Issue by PENorris** [librenms/librenms#4522]
Attaching new device details.

http://pastebin.com/aEn6W7mr

Device is a standalone module that lives inside new Cisco ASA X series firewalls and performs L7 inspection/IPS/IDS

Cisco badging would be appropriate

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by Rosiak** [comment]
Could you add a snmpwalk from the device?

**Comment by laf** [comment]
No further info provided.
