### ISSUE TITLE
Virtual servers endpoint for the API

### ISSUE THREAD

**Issue by MauJFernandezUVR** [librenms/librenms#4527]
Hi, I have an application consuming the API for some devices graphs, I just tried to do the same for the virtual servers of a NetScaler load balancer but there's no endpoint for that, for now I'll try to extract them by using the direct URL to the image, but using the API would be really appreciated.

Thanks.

**Comment by laf** [comment]
Do you have a link in the webui to a graph you want? Don't need the full url with hostname just / and beyond

**Comment by MauJFernandezUVR** [comment]
Sorry for the delay @laf, this is the last part of the URL /graphs/to=1477427400/id=1366/type=netscalervsvr_bits/from=1477341000/

**Comment by laf** [comment]
@MauJFernandezUVR 

Sorry for the delay. Please try this patch (although I'm not 100% sure it will solve the issue at the moment). It will take 1 poll cycle for the db to be updated. Using the [get_graphs](http://docs.librenms.org/API/API-Docs/#api-route-5) should have the graphs you want so you can then call [get_port_graphs](http://docs.librenms.org/API/API-Docs/#api-route-6):

```
diff --git a/includes/polling/netscaler-vsvr.inc.php b/includes/polling/netscaler-vsvr.inc.php
index 91a301d..27d7297 100644
--- a/includes/polling/netscaler-vsvr.inc.php
+++ b/includes/polling/netscaler-vsvr.inc.php
@@ -116,6 +116,12 @@ if ($device['os'] == 'netscaler') {
                 echo ' U';
             }

+            $graphs['netscalervsvr_bits']    = true;
+            $graphs['netscalervsvr_conns']   = true;
+            $graphs['netscalervsvr_hitmiss'] = true;
+            $graphs['netscalervsvr_pkts']    = true;
+            $graphs['netscalervsvr_reqs']    = true;
+
             echo "\n";
         }//end if
     }//end foreach

```

**Comment by MauJFernandezUVR** [comment]
Hi @laf, I just tried the patch and although it now works great for getting the graphs using the [http://docs.librenms.org/API/API-Docs/#api-route-5](get_graphs) (output below), what I'm trying to get are Virtual Servers, not Ports, so using [http://docs.librenms.org/API/API-Docs/#api-route-6](get_port_graphs) won't work right now, I think we need a new endpoint for these Virtual Servers maybe? Something like `/api/v0/devices/netscalerhostname/vserver/1366/device_netscalervsvr_bits` (the 1366 is the ID I get when I see the graph from the webUI `/graphs/to=1477427400/id=1366/type=netscalervsvr_bits/from=1477341000/`)

_get_graphs output_:
```
    {
      "desc": null,
      "name": "device_netscalervsvr_bits"
    },
    {
      "desc": null,
      "name": "device_netscalervsvr_conns"
    },
    {
      "desc": null,
      "name": "device_netscalervsvr_hitmiss"
    },
    {
      "desc": null,
      "name": "device_netscalervsvr_pkts"
    },
    {
      "desc": null,
      "name": "device_netscalervsvr_reqs"
    },
```


Thanks.

**Comment by laf** [comment]
is id=1366 not the device id?

**Comment by MauJFernandezUVR** [comment]
No, for example, this is the URL from the webUI that shows me the different graphs for that Virtual Server `/device/device=29/tab=loadbalancer/type=netscaler_vsvr/vsvr=2170/` and this is the URL when I enter any of those graphs `/graphs/to=1479834600/id=2170/type=netscalervsvr_bits/from=1479748200/`. Notice the `id=2170`, it's from the Virtual Server.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-virtual-servers-endpoint-for-the-api/1066
