### ISSUE TITLE
PHP Seg Faulting on NTP Module

### ISSUE THREAD

**Issue by Blorpy** [librenms/librenms#4532]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release. 
`Yes`
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
`Version info:
Commit SHA: 52d6d0d9df722962eb9e3047b10150c914c31d12
DB Schema: 136
PHP: 5.3.3
MySQL: 5.1.73
RRDTool: 1.5.6
SNMP: NET-SNMP version: 5.5`
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.
`A few times a day some devices will fail polling, and show up as unpolled in the web interface. Going to the CLI and running ./poller.php -d -h <device> shows the following:`

#### Load poller module ntp ####

SQL[SELECT `C`.`id`,`C`.`device_id`,`C`.`type`,`C`.`label`,`C`.`status`,`C`.`disabled`,`C`.`ignore`,`C`.`error`,`CP`.`attribute`,`CP`.`value` FROM `component` as `C` LEFT JOIN `component_prefs` as `CP` on `C`.`id`=`CP`.`component` WHERE  ( `type` = 'ntp' AND `disabled` = '0' AND `ignore` = '0' AND `device_id` = '69' )] /usr/bin/snmpbulkwalk -v3 -n '' -l 'authPriv' -a 'SHA' -A 'redacted' -u 'snmpuser' -x 'AES' -X 'redacted' -Osqn -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.9.9.168.1.2.1.1.*.*.*.1.2.43235 1
.*.*.*.1.3.43235 *
.*.*.*.1.4.43235 123
.*.*.*.1.5.43235 *
.*.*.*.1.6.43235 123
.*.*.*.1.7.43235 0
.*.*.*.1.8.43235 4
.*.*.*.1.9.43235 1
.*.*.*.1.10.43235 10
.*.*.*.1.11.43235 10
.*.*.*.1.12.43235 -20
.*.*.*.1.13.43235 "12 00 8F 50 "
.*.*.*.1.14.43235 "22 E4 F5 48 "
.*.*.*.1.15.43235 "47 50 53 00 "
.*.*.*.1.16.43235 "00 00 00 04 14 93 42 64 "
.*.*.*.1.17.43235 "21 74 D2 F4 22 E4 F5 68 "
.*.*.*.1.18.43235 "00 00 00 A1 22 E4 F5 60 "
.*.*.*.1.19.43235 "12 00 28 14 22 EA FB 9C "
.*.*.*.1.20.43235 1929578843
.*.*.*.1.21.43235 255
.*.*.*.1.22.43235 0
.*.*.*.1.23.43235 "12 00 90 90 "
.*.*.*.1.24.43235 "00 00 00 01 "
.*.*.*.1.25.43235 "15 E1 00 80 "
.*.*.*.1.26.43235 8
.*.*.*.1.27.43235 1
.*.*.*.1.28.43235 1929578843
.*.*.*.1.29.43235 2

RRD[update /opt/librenms/rrd/lab-asw2/ntp-.rrd N:U:0:0:0]

Component: 78
    Index:      
    Peer:       :
    Stratum:    1.3.6.1.4.1.9.9.168.1.2.1.1.9.  = 
    Offset:     1.3.6.1.4.1.9.9.168.1.2.1.1.23. = 0
    Delay:      1.3.6.1.4.1.9.9.168.1.2.1.1.24. = 0
    Dispersion: 1.3.6.1.4.1.9.9.168.1.2.1.1.25. = 0
Segmentation fault

I haven't been able to find any pattern to what is causing this. I can run the poller a few times, and the third time it will succeed without the segfault.

**Comment by laf** [comment]
Is there any possibility of upgrading php from 5.3? That's such an old version now, it would be good to see if this occurs with a newer version. 5.4 at least but the newer the better.

**Comment by Blorpy** [comment]
Moved to 5.6.26, I'll give it a full day and see if the issues is still present.

**Comment by laf** [comment]
Feel free to respond back if you are still having issues.
