### ISSUE TITLE
Pagerduty transport via API key

### ISSUE THREAD

**Issue by compuguy** [librenms/librenms#4542]
> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

My workplace currently uses librenms in a pseudo airgapped network, and we also use pagerduty. The current workflow for pagerduty requires the user logged into librenms, to go to the pagerduty site, which is not possible on our network. Is there a way to manually insert the api key into the interface, without having add the transport manually via the config.php (as mentioned here: http://docs.librenms.org/Extensions/Alerting/#transports-pagerduty)

**Comment by laf** [comment]
See if you have pagerduty config items in your DB first: `select * from config where config_name LIKE 'alert.%pagerduty%'\G`

If you do, update the config_value settings where needed.

If not, you need to have:

```bash
*************************** 1. row ***************************
             config_id: 454
           config_name: alert.transports.pagerduty
          config_value:
        config_default:
          config_descr: Pagerduty transport - put your API key here
          config_group: alerting
    config_group_order: 0
      config_sub_group: transports
config_sub_group_order: 0
         config_hidden: 0
       config_disabled: 0
*************************** 2. row ***************************
             config_id: 455
           config_name: alert.pagerduty.account
          config_value:
        config_default:
          config_descr: Pagerduty account name
          config_group: alerting
    config_group_order: 0
      config_sub_group: transports
config_sub_group_order: 0
         config_hidden: 0
       config_disabled: 0
*************************** 3. row ***************************
             config_id: 456
           config_name: alert.pagerduty.service
          config_value:
        config_default:
          config_descr: Pagerduty service name
          config_group: alerting
    config_group_order: 0
      config_sub_group: transports
config_sub_group_order: 0
         config_hidden: 0
       config_disabled: 0
```

**Comment by compuguy** [comment]
@laf Took a look at that query, and it looks like we have all three rows

`*************************** 1. row ***************************
             config_id: 454
           config_name: alert.transports.pagerduty
          config_value:
        config_default:
          config_descr: Pagerduty transport - put your API key here
          config_group: alerting
    config_group_order: 0
      config_sub_group: transports
config_sub_group_order: 0
         config_hidden: 0
       config_disabled: 0
*************************** 2. row ***************************
             config_id: 455
           config_name: alert.pagerduty.account
          config_value:
        config_default:
          config_descr: Pagerduty account name
          config_group: alerting
    config_group_order: 0
      config_sub_group: transports
config_sub_group_order: 0
         config_hidden: 0
       config_disabled: 0
*************************** 3. row ***************************
             config_id: 456
           config_name: alert.pagerduty.service
          config_value:
        config_default:
          config_descr: Pagerduty service name
          config_group: alerting
    config_group_order: 0
      config_sub_group: transports
config_sub_group_order: 0
         config_hidden: 0
       config_disabled: 0`

**Comment by compuguy** [comment]
@laf Got it working on our end, though it would make it straight forward to have manual entry for API Key, account name in the webui.

**Comment by laf** [comment]
You can configure it via config.php - I should have said that :(
