### ISSUE TITLE
Port status Alerts

### ISSUE THREAD

**Issue by search4u2003** [librenms/librenms#4546]
# 

Version info:
Commit SHA: 60332cd919ec59cb3413030692b50b3bda1657b4
[WARN]    Your local git branch is not master, this will prevent automatic updates.
DB Schema: 118
PHP: 7.0.10
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2
# 

[OK]      Database connection successful

![alerts](https://cloud.githubusercontent.com/assets/18137450/18758326/29d5f8b6-8115-11e6-88c8-c78072b82212.gif)

I'm not getting port status alerts vai transport mail, since this port status alert turned red.

other alerts are working properly.

**Comment by laf** [comment]
Check the eventlog for the device that should have triggered it.

**Comment by laf** [comment]
No further info provided.
