### ISSUE TITLE
SNMPv3 Security

### ISSUE THREAD

**Issue by sarlacpit** [librenms/librenms#4555]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

Installed yesterday morning in a firewelled environment will not allow me to connect servers to Github repos.

- [x] Please include all of the information between the `====================================` section of `./validate.php`.

Version info:
Commit SHA: 
[WARN]    Your local git branch is not master, this will prevent automatic updates.
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>
DB Schema: 134
PHP: 7.0.8-0ubuntu0.16.04.2
MySQL: 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP version: 5.7.3

- [x] Please provide as much detail as possible.

Hi, I have noticed a small issue for me but it may be a bigger issue for some. 
I installed the server yesterday and whilst watching the processes and resources being used in the ever so useful htop, I could see the snmpwalk command and the SNMPv3 password in plain text.

I have attached it below, beneath the smudges are the SNMPv3 password and the name of the node.

![snmpv3](https://cloud.githubusercontent.com/assets/9213736/18779409/d91cad32-8170-11e6-9d42-03e6d4d8c543.png)

I suspect it is more of an snmpwalk issue though as the process underneath the highlighted process is the same node with the password omitted. However, I thought it prudent to let you know.

Many thanks

**Comment by laf** [comment]
We have to pass the credentials over to snmp calls which are all shell exec so we can't really do much about this I'm afraid. It shouldn't be an issue really though as installs like NMS' should be restricted access in the first place.
