### ISSUE TITLE
Memory sensors still monitored after modules have removed (IPMI)

### ISSUE THREAD

**Issue by zamolxe** [librenms/librenms#4556]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the Version info:
Commit SHA: c8e9e281ae18d9fdcd2c1773f15b21b0176920d4
DB Schema: 136
PHP: 5.4.16
MySQL: 5.5.47-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

I the following situation which not sure if should be marked as a bug of feature request.
Recently updated the memory on one Supermicro machine, and some of the DIMM's have been removed and bigger ones added. After this I started getting alerts for "Sensor under limit"...
#1: sensor_id => 14; sensor_oid => DIMMC1 Temp; sensor_descr => DIMMC1 Temp; 
#2: sensor_id => 33; sensor_oid => DIMMD1 Temp; sensor_descr => DIMMD1 Temp; 
Considering that those slot's are not in use anymore, I have tried rediscovery of the machine, with no success , also the gui doesn't provide any options to removed those non existing/used sensors.
I think those entries are being pulled from the IPMI, but correct me if i'm wrong.

Any sugestions for solutions would be appreciated

/Alex

**Comment by laf** [comment]
Please post the output of the following on to non-expiring pastebins:

```bash
./discovery.php -h HOSTNAME -d
./poller.php -h HOSTNAME -r -f -d
```

**Comment by zamolxe** [comment]
You have below the discovery and poller outputs (I've censored the hostnams, usernames and passwords)

http://pastebin.com/5FeFAZtf
http://pastebin.com/vUaMDnU9

/Alex

**Comment by laf** [comment]
Can you test #4582 please?

http://docs.librenms.org/Support/FAQ/#how-can-i-test-another-users-branch

**Comment by zamolxe** [comment]
I've tried it out... Re-discovered the machine, but no change yet.
So far I see that the removed modules are not discovered anymore, but in the health tab, they are still there and alerting continues.

Discovery in debug mode only for sensors:
http://pastebin.com/cNCgddsu

/Alex

**Comment by laf** [comment]
Looks like they still are discovered - I think it's because they are returned by ipmi still but with values of na.

**Comment by laf** [comment]
Can you get me the output of:

```mysql
SELECT * FROM sensors AS S, devices AS D WHERE S.sensor_class='temperature' AND S.device_id = D.device_id AND D.device_id = '13';
```

**Comment by zamolxe** [comment]
Sorry for the delay, was afk for a bit. Here you have the sql output:
http://pastebin.com/CiwtPg4G

**Comment by laf** [comment]
I've updated my branch, if you switch back to it and do `git pull` then please re-run discovery for the device in question.

**Comment by zamolxe** [comment]
Done, same issue
Here is the discovery with -m sensors
http://pastebin.com/H9tUFtSm

/Alex

**Comment by laf** [comment]
My bad :( I totally didn't push the latest commit!

If you git pull in my branch you should end up on: 26f392d33d4a799410875326f43a3b42e3bd0d75

**Comment by zamolxe** [comment]
Yep, not we have results. The removed DIMM's are gone now.
Thanks
