### ISSUE TITLE
Add support for Eaton Power Xpert

### ISSUE THREAD

**Issue by kate66** [librenms/librenms#4562]
Please add support for Eaton UPSes. I have included the MIBs along with each command requested in the wiki.

Let me know if you need anything from me.

[eaton.zip](https://github.com/librenms/librenms/files/490525/eaton.zip)

**Comment by murrant** [comment]
What kind of device is this?  Is it a UPS?  It looks like some kind of server.

**Comment by kate66** [comment]
Yes it is a UPS

**Comment by kate66** [comment]
Also, upon detecting the correct OS it added 137 phases for input current and 135 output current phases. Only three of each are actually in-use/reporting anything.

**Comment by laf** [comment]
Do you have the output of `./discovery.php -h HOSTNAME -d -m sensors` (pastebin pls)

**Comment by kate66** [comment]
Here you go! http://pastebin.com/HC5bXRFy (Expires in 24h)

**Comment by murrant** [comment]
fixed in #4640
