### ISSUE TITLE
Please add detection for MGE Comet UPS systems

### ISSUE THREAD

**Issue by kate66** [librenms/librenms#4568]
The git diff and a 'cat' of my created file are below.

librenms@nms:~$ git diff 
diff --git a/includes/discovery/os/mgeups.inc.php b/includes/discovery/os/mgeu
index 6da3039..a126cb8 100644
--- a/includes/discovery/os/mgeups.inc.php
+++ b/includes/discovery/os/mgeups.inc.php
@@ -13,4 +13,7 @@ if (!$os) {
     if ($sysDescr == 'MGE UPS SYSTEMS - Network Management Proxy') {
         $os = 'mgeups';
     }
+    if (preg_match('/^Comet/', $sysDescr)) {
+        $os = 'mgeups';
+    }
 }
diff --git a/tests/OSDiscoveryTest.php b/tests/OSDiscoveryTest.php
index 1523cb9..36611f0 100644
--- a/tests/OSDiscoveryTest.php
+++ b/tests/OSDiscoveryTest.php
@@ -801,6 +801,7 @@ class DiscoveryTest extends \PHPUnit_Framework_TestCase
         $this->checkOS('mgeups', 'mgeups-galaxy');
         $this->checkOS('mgeups', 'mgeups-evolution');
         $this->checkOS('mgeups', 'mgeups-proxy');
+        $this->checkOS('mgeups', 'mgeups-comet');
     }
 
     public function testMicrosemitime()
librenms@nms:~$ cat tests/snmpsim/mgeups-comet.snmprec 
1.3.6.1.2.1.1.1.0|4|Comet
librenms@nms:~$

**Comment by kate66** [comment]
Note, I have the preg_match as at least on mine, there is a space after "Comet" in sysDescr.

**Comment by kate66** [comment]
Also, for proper support of Phase # on the Comet series, I propose the change below.

My reasoning is that if there are multiple phases, and you are using the number of results returned to fiber that out, why reference some other MIB when you can simply reference the MIB that contains the results?

Note, in the Comet series the results of snmpwalk 1.3.6.1.4.1.705.1.7.1 returns the number of phases as a value: .1.3.6.1.4.1.705.1.7.1.0 = INTEGER: 3

diff --git a/includes/discovery/sensors/current/mgeups.inc.php b/includes/disc
index 521abc6..dd85bd9 100644
--- a/includes/discovery/sensors/current/mgeups.inc.php
+++ b/includes/discovery/sensors/current/mgeups.inc.php
@@ -3,7 +3,7 @@
 // MGE UPS
 if ($device['os'] == 'mgeups') {
     echo 'MGE ';
-    $oids = trim(snmp_walk($device, '1.3.6.1.4.1.705.1.7.1', '-OsqnU'));
+    $oids = trim(snmp_walk($device, '1.3.6.1.4.1.705.1.7.2.1.5', '-OsqnU'));
     d_echo($oids."\n");
 
     $numPhase = count(explode("\n", $oids));
@@ -33,7 +33,7 @@ if ($device['os'] == 'mgeups') {
         discover_sensor($valid['sensor'], 'current', $device, $current_oid, $
     }//end for
 
-    $oids = trim(snmp_walk($device, '1.3.6.1.4.1.705.1.6.1', '-OsqnU'));
+    $oids = trim(snmp_walk($device, '1.3.6.1.4.1.705.1.6.2.1.6', '-OsqnU'));
     d_echo($oids."\n");
 
     $numPhase = count(explode("\n", $oids));

**Comment by kate66** [comment]
```
librenms@nms:~$ git diff
diff --git a/includes/discovery/os/mgeups.inc.php b/includes/discovery/os/mgeups.inc.php
index 6da3039..a126cb8 100644
--- a/includes/discovery/os/mgeups.inc.php
+++ b/includes/discovery/os/mgeups.inc.php
@@ -13,4 +13,7 @@ if (!$os) {
     if ($sysDescr == 'MGE UPS SYSTEMS - Network Management Proxy') {
         $os = 'mgeups';
     }
+    if (preg_match('/^Comet/', $sysDescr)) {
+        $os = 'mgeups';
+    }
 }
diff --git a/includes/discovery/sensors/current/mgeups.inc.php b/includes/discovery/sensors/current/mgeups.inc.php
index 521abc6..dd85bd9 100644
--- a/includes/discovery/sensors/current/mgeups.inc.php
+++ b/includes/discovery/sensors/current/mgeups.inc.php
@@ -3,7 +3,7 @@
 // MGE UPS
 if ($device['os'] == 'mgeups') {
     echo 'MGE ';
-    $oids = trim(snmp_walk($device, '1.3.6.1.4.1.705.1.7.1', '-OsqnU'));
+    $oids = trim(snmp_walk($device, '1.3.6.1.4.1.705.1.7.2.1.5', '-OsqnU'));
     d_echo($oids."\n");
 
     $numPhase = count(explode("\n", $oids));
@@ -33,7 +33,7 @@ if ($device['os'] == 'mgeups') {
         discover_sensor($valid['sensor'], 'current', $device, $current_oid, $index, $type, $descr, '10', '1', $lowlimit, $lowwarnlimit, $warnlimit, $limit, $cur
     }//end for
 
-    $oids = trim(snmp_walk($device, '1.3.6.1.4.1.705.1.6.1', '-OsqnU'));
+    $oids = trim(snmp_walk($device, '1.3.6.1.4.1.705.1.6.2.1.6', '-OsqnU'));
     d_echo($oids."\n");
 
     $numPhase = count(explode("\n", $oids));
diff --git a/tests/OSDiscoveryTest.php b/tests/OSDiscoveryTest.php
index 1523cb9..36611f0 100644
--- a/tests/OSDiscoveryTest.php
+++ b/tests/OSDiscoveryTest.php
@@ -801,6 +801,7 @@ class DiscoveryTest extends \PHPUnit_Framework_TestCase
         $this->checkOS('mgeups', 'mgeups-galaxy');
         $this->checkOS('mgeups', 'mgeups-evolution');
         $this->checkOS('mgeups', 'mgeups-proxy');
+        $this->checkOS('mgeups', 'mgeups-comet');
     }
 
     public function testMicrosemitime()
librenms@nms:~$ cat tests/snmpsim/mgeups-comet.snmprec 
1.3.6.1.2.1.1.1.0|4|Comet
librenms@nms:~$

**Comment by laf** [comment]
I can't comment on switching from `1.3.6.1.4.1.705.1.6.1` to `1.3.6.1.4.1.705.1.6.2.1.6` as I don't use those units but I'd be nervous about changing it in case it breaks existing setups for people.

`1.3.6.1.2.1.1.1.0|4|Comet` is fine but really the `Comet` part should be a fuller sysDescr output to match what the device throws back. If it genuinely is just `Comet` then fine.

We have some new functions for OS detection, this code has been done against the older method which has probably updated now. The new file would look like:

```php
<?php

if (str_contains($sysDescr, array('Pulsar M', 'MGE UPS SYSTEMS - Network Management Proxy'))) {
    $os = 'mgeups';
}

if (starts_with($sysDescr, array('Galaxy ', 'Evolution ', 'Comet'))) {
    $os = 'mgeups';
}
```

**Comment by kate66** [comment]
The sysDescr is simply Comet, otherwise I would have done something a little smarter. Additionally, choosing to count the number of MIBs in 1.3.6.1.4.1.705.1.6.2.1.6 instead of 1.3.6.1.4.1.705.1.6.1 should give the same result as I am directly counting the number of phases instead of using another MIB to attempt to correctly guess the number of phases in the system.

Is the original creator of that code active somewhere so we can figure out why he did it the way that he did?

**Comment by laf** [comment]
We inherited this code base so if you feel it's a good change then we can go with it.

Like I said about Comet - if that's all it is then that's fine.

Are you submitting the pull request @kate66 :)

**Comment by kate66** [comment]
Issue complete with PR
