### ISSUE TITLE
New device support for Amazon EC2 instance

### ISSUE THREAD

**Issue by rbax82** [librenms/librenms#4570]
Hello, please add support and maybe a logo for the Amazon EC2 instance of linux. =)
Hostname: pulse - OS: Linux 4.4.19-29.55.amzn1.x86_64/x86_64 - CPU: Intel Xeon (2400.072 MHz) - Processes: 111 - Uptime: 1h 1m - Users: 1 - Load Average: 0.00 - Memory Usage: 178.40MB/995.44MB (17.92%) - Disk Usage: 6.09GB/11.14GB (54.62%)

./discovery.php -h HOSTNAME -d -m os
http://pastebin.com/gpPth1t1
./poller.php -h HOSTNAME -r -f -d -m os
http://pastebin.com/Q5FFrCTT
snmpbulkwalk -Onet -v2c -c COMMUNITY HOSTNAME
too big for pastebin, http://sprunge.us/YGUG

**Comment by crcro** [comment]
can you provide the output of cat /etc/os-release?

**Comment by laf** [comment]
Unless /etc/os-release contains something for us. I'm expecting it won't so this is most likely not something we can support.

**Comment by crcro** [comment]
maybe there is something in os-release that will identify this as a custom os for amazon ... i don't have any amazon instance to check

**Comment by laf** [comment]
One I have doesn't have os-release - it's at least a year old so not sure if it's different now

**Comment by rbax82** [comment]
~>cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2016.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2016.03"
PRETTY_NAME="Amazon Linux AMI 2016.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2016.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

**Comment by crcro** [comment]
@rbax82 ... icon added, you must enable the distro snmp agent on host
