### ISSUE TITLE
Feature Request: Device Group permissions

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#4576]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

It would be great if we could have a feature to lock a user/s to a device group over and above the the current permissions under User Permissions screen that provides one the ability to assign a User to a certain Device, Interface and Bill entities.
![snap1](https://cloud.githubusercontent.com/assets/16717388/18809399/90b9a508-827a-11e6-81df-7f2037e8863f.png)
![snap2](https://cloud.githubusercontent.com/assets/16717388/18809400/987b1574-827a-11e6-803d-555f2528ef2a.png)

**Comment by murrant** [comment]
Yeah, but the problem is, it is possible to create groups that change without the admins knowledge.  Say you base a group on sysName and someone updates that the group changes.  Adding security implications to that might be a bad idea.

That's why I would like to rename to Dynamic Groups, so people know more specifically.  Maybe we could have static groups too where users select devices specifically and have a way to convert a current dynamic group to a static one...

**Comment by breeman1** [comment]
I had only thought of groups based on OS and Hardware features as those do not change often but I see your point and it makes sense. How would Dynamic groups work exactly?

**Comment by murrant** [comment]
Our device groups are dynamic.  They are updated each time a device is polled.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by breeman1** [comment]
This is not really a critical issue and I have not looked into further in the new code base.
