### ISSUE TITLE
Windows server 2008/2012 R2 graph Support 

### ISSUE THREAD

**Issue by gugansankar** [librenms/librenms#4580]
While trying to add either my Windows server 2012 R2 or Window server 2008 R2. Both are not showing all the data. Even OS detected as like "Operating System    Microsoft Windows (Multiprocessor)". Seems some issues with Windows templates I guess.

Should I need to make any changes in the configuration/mib ?. Please help.

![inout1 1](https://cloud.githubusercontent.com/assets/4958813/18813548/5d6decc6-831b-11e6-8b82-6930f906a435.png)

Output of  discovery.php:
http://pastebin.ubuntu.com/23228148/

./poller.php output:
http://pastebin.ubuntu.com/23228150/

**Comment by crcro** [comment]
@gugansankar ... what do you mean by it's not showing all data?

**Comment by gugansankar** [comment]
Fyi, Currently I'm moving my monitoring system from Observium to Librenms. Where In observium, it detects the OS version correctly for Windows machines and also it shows some more data like "Status Indicators and Temperature".  But its not present in LibreNMS. 

Below is my observium graph for your reference. 

![inout2 1](https://cloud.githubusercontent.com/assets/4958813/18815520/0d9c20e6-8352-11e6-9eb1-f0f719a9cadf.png)

**Comment by laf** [comment]
Please don't post screenshots of obs...

**Comment by gugansankar** [comment]
To give clear info to him, I pasted the screenshot. Anyway, you've removed it, i think so. Could you please help me on why some data missing on our LibeNMS ?. Do I need to add any specific template/MIBs in the configuration ? .

**Comment by crcro** [comment]
@gugansankar ... on what kind of hardware is that windows installed?

**Comment by laf** [comment]
The poller output was run wrong:

```bash
./poller.php -h app1-fr-xxxx.com -r -f -d
```

**Comment by gugansankar** [comment]
@laf  Sorry, I run the command wrongly. Please find the poller output on the below link.

http://pastebin.ubuntu.com/23232565/

@crcro I'm not sure about the hardware details. Since I don't have server access. But its a physical machine. will try to get the details for you soon.

**Comment by gugansankar** [comment]
Any chance to check this ?.

**Comment by laf** [comment]
Please be patient, people help when they can.

Provide the output of:

`snmpbulkwalk -Onet -v2c -c COMMUNITY HOSTNAME .`

Also - What version of Windows is this for?

**Comment by gugansankar** [comment]
Ok, I'm using Windows Server 2012R2. Attached data for your reference Winserver2012R2. Even its not showing hardware information correctly for Windows Server 2008r2 also.

[win2012stg.txt](https://github.com/librenms/librenms/files/495843/win2012stg.txt)

**Comment by laf** [comment]
The output you've provided there for me is detected ok. An update was done at the end of Sept for Windows so maybe that has resolved your issue - can you confirm please.

**Comment by laf** [comment]
No further info provided.
