### ISSUE TITLE
QNAP Sensors description missing and default thresholds not set,

### ISSUE THREAD

**Issue by zamolxe** [librenms/librenms#4586]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [X] Please provide as much detail as possible.

QNAP snmp sensor description is missing and default thresholds for max and min are 0,
causing alerts to be issued for hdd temps and fan speeds.
HW: QNAP TS-659
OS: QTS-4.2.0 (2016-03-11)

http://pastebin.com/JKjYXzhc

**Comment by laf** [comment]
Can you show a screenshot of where you mean for the description?

**Comment by zamolxe** [comment]
You have below attached the screenshot's...
Let me know if you need more info.

<img width="1420" alt="screen shot 2016-09-25 at 23 17 01" src="https://cloud.githubusercontent.com/assets/1435948/18818316/6cefbd90-8376-11e6-89db-324ed611c40f.png">

<img width="691" alt="screen shot 2016-09-25 at 23 16 39" src="https://cloud.githubusercontent.com/assets/1435948/18818317/6d07513a-8376-11e6-8ed4-4c29561c8b12.png">

**Comment by crcro** [comment]
qnap doesn't return anything for temperature low/high warning.
sensors are added with 0, checking this out on my qnap

**Comment by zamolxe** [comment]
I've noticed this by snmpwalking the qnap. I was assuming that some defaults can be "guessed" by default. Anyway could be nice to get some description of the sensors at least, since that's provided by snmp.

**Comment by crcro** [comment]
i saw that also, writting fix right now :)

**Comment by zamolxe** [comment]
Great! Highly appreciated 👍
