### ISSUE TITLE
Cisco SG300 series does not return graphs via API using port_bits.

### ISSUE THREAD

**Issue by Brooniee** [librenms/librenms#4594]
> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
  8b68429 - Sun Sep 25 2016 16:01:58 GMT+0100
- [x] Please include all of the information between the `====================================` section of `./validate.php`.

Version info:
Commit SHA: 8b68429a0619c627256c31299765ffddb2bdd9dd
DB Schema: 138
PHP: 5.5.9-1ubuntu4.17
MySQL: 5.5.49-0ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

API call port_bits returns no data on Cisco SG300

curl -H 'X-Auth-Token: hidden' http://hidden/api/v0/devices/hidden/ports/gi1/port_bits

Querying port returns data fine:
curl -H 'X-Auth-Token: hidden' http://hidden/api/v0/devices/hidden/ports/gi1
{
    "status": "ok",
    "port": null
}

Other devices work perfectly fine, just this switch.

Graphs display fine within librenms, populated with data.

**Comment by Brooniee** [comment]
@laf 

Believe I've found the cause of this

When querying:
http://librenms.yyy/api/v0/devices/xxx/ports/gigabitethernet1/port_bits

I get nothing

but if I add an "id" of the port on to the end of it:

http://librenms.yyy/api/v0/devices/xxx/ports/gigabitethernet1/port_bits?id=zzz

it responds fine

this happens with the port name being gigabitetherenet1 or gi1

happens on any port on this switch though, not just gi1.

**Comment by laf** [comment]
Not sure why setting ?id would do anything as we don't use that in the code.

You can pass ?ifDescr=true as this seems most likely that the device doesn't have ifName set.

**Comment by laf** [comment]
No further feedback provided
