### ISSUE TITLE
accessing GUI for librenms

### ISSUE THREAD

**Issue by wahidshah** [librenms/librenms#4598]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================

I installed librenms just afew days ago. now I have a lot of problems with its comand line shell. If you know any way for getting GUI of 
librenms. please help me!
I installed the update version of librenms on centOS 7 but it gives some errors when i configure it.
if you want more information i'll give that to you.
================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by crcro** [comment]
please post pastebin link to output ok ./validate.php

**Comment by wahidshah** [comment]
i did not understand you?

**Comment by crcro** [comment]
get into your librenms dir, and run ./validate.php from cli
save the output of that command to pastebin site and post the generate link here so we can see

**Comment by laf** [comment]
I'd also suggest you re-visit the install docs.

**Comment by wahidshah** [comment]
Thanks! I'll try installation once again.
