### ISSUE TITLE
Adding CPU,Fan and temperature to F5 hardware

### ISSUE THREAD

**Issue by boudreau** [librenms/librenms#4599]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by boudreau** [comment]
====================================
Version info:
Commit SHA: 8b68429a0619c627256c31299765ffddb2bdd9dd
DB Schema: 138
PHP: 7.0.10
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2

====================================

**Comment by crcro** [comment]
please post a pastebin link with the output of:

./discovery.php -h HOSTNAME -d
./poller.php -h HOSTNAME -r -f -d
snmpbulkwalk -Onet -v2c -c COMMUNITY HOSTNAME .

**Comment by boudreau** [comment]
http://pastebin.com/CzVR28Sg
http://pastebin.com/bQguUb93

**Comment by laf** [comment]
pastebin links have expired. Please repost with the output from all three commands above.

**Comment by laf** [comment]
No further info provided.
