### ISSUE TITLE
Etherlike statistics DB updates

### ISSUE THREAD

**Issue by garryshtern** [librenms/librenms#4601]
Hi,

Currently, etherlike statistics are used to generate RRD, only.  Is it a huge effort to add this to the MySQL, as well and allow alerting on these?

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the ====================================
  Version info:
  Commit SHA: 8b68429a0619c627256c31299765ffddb2bdd9dd
  DB Schema: 138
  PHP: 5.3.3
  MySQL: 5.1.73
  RRDTool: 1.3.8
  SNMP: NET-SNMP version: 5.5
# 

[OK]      Database connection successful
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by laf** [comment]
Probably not difficult, just time :)

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
