### ISSUE TITLE
VyOS support

### ISSUE THREAD

**Issue by dmbaturin** [librenms/librenms#461]
VyOS (http://vyos.net), which is a fork of now dead Vyatta Core, will be changing its SNMP OID from the old one inherited from Vyatta (30803) to its own (44641).
Could you add support for it? If you need anything from me, like a logo image in specific format/size, please let me know.
Thanks!

**Comment by laf** [comment]
Hey dmbaturin, thanks for getting in touch.

From looking at the code for vyatta / VyOS, they are detected by the sysDescr value from SNMP so we don't actually use 30803.

As for logo, this is the current one we are using:

https://github.com/librenms/librenms/blob/master/html/images/os/vyos.png

If that needs updating, then provide a link to the new one and we can update. Image size is 40px x 40px.

Here is our PR that added support for VyOS if you want to take a look at the specific bits of code:

https://github.com/librenms/librenms/pull/351/files

**Comment by dmbaturin** [comment]
Oh, cool, I was under impression that PEN is used there. The logo is fine, we didn't change it since then.

**Comment by laf** [comment]
No worries, good luck with the project @dmbaturin

**Comment by dmbaturin** [comment]
Speaking of the logo, I made a slightly nicer less pixelized version of the icon: http://baturin.org/files/vyos_icon.png

**Comment by laf** [comment]
Just merged that new logo in, many thanks @dmbaturin :)

**Comment by dmbaturin** [comment]
Wait. This one is 32x32. Should I redo it in 40x40?

**Comment by laf** [comment]
No it's ok, most of the others are 32x32 actually so not sure why this wasn't!
