### ISSUE TITLE
Add detection + support for Sinetica UPSController devices

### ISSUE THREAD

**Issue by kate66** [librenms/librenms#4613]
This is a UPS device.

[generic-10.10.11.84.snmpwalk.txt](https://github.com/librenms/librenms/files/494440/generic-10.10.11.84.snmpwalk.txt)
[poller-10.10.11.84.txt](https://github.com/librenms/librenms/files/494439/poller-10.10.11.84.txt)
[discovery-10.10.11.84.txt](https://github.com/librenms/librenms/files/494438/discovery-10.10.11.84.txt)

**Comment by kate66** [comment]
[Mitsubishi.zip](https://github.com/librenms/librenms/files/495934/Mitsubishi.zip)

**Comment by laf** [comment]
I've submitted basic detection for this and assumed it supports rfc1628 for ups sensors.

I also couldn't even find what manufacturer this was so no logo - any idea?

The mitsubishi logo is the UPS-MIB one we have but actually different, as such we can't use that as it will conflict.

**Comment by kate66** [comment]
Monitoring of voltage/etc is missing. I checked the Mitsubishi MIB and discovered that it hides them in 1.3.6.1.4.1.13891
http://pastebin.com/kE8qwwU4
