### ISSUE TITLE
Quanta detection broken

### ISSUE THREAD

**Issue by tobiasa1** [librenms/librenms#4614]
Hi,

Since PR #4552 the Quanta detection is broken and now discovered as Generic Device VxWorks 6.6.
I think str_contains has to be case-sensitive.

/Tobias

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

====================================
Version info:
Commit SHA: 7b4988aab79cac8bd3f129c802d1bf3e6fbb1e82
DB Schema: 138
PHP: 5.6.24-0+deb8u1
MySQL: 5.5.50-0+deb8u1
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2.1

====================================
[OK]      Database connection successful

**Comment by laf** [comment]
PR has been submitted.

Can you get us the output of `./poller.php -h HOSTNAME -r -f -d -m os` please. We have full unit testing in place but a lot of tests are just based on the code so until we get full sysDescr + sysObjectID's some of them aren't useful.

**Comment by tobiasa1** [comment]
Here you go: https://tobiasa.se/priv/quanta.txt

**Comment by laf** [comment]
Thanks - adding a test so we can pick this up in future.

In your own time, if you get us the full output from:

`snmpbulkwalk -Onet -v2c -c COMMUNITY HOSTNAME .`

Maybe even with additional mibs loaded then we can simulate this device for future support.

**Comment by f0o** [comment]
This walk is taken from my QuxLabs rack, I had to redact MAC, VLAN and Port-Desc but the rest should be good. I redacted at bulk, so the same real mac has the same redacted mac and so on.

[quanta.lb4m.walk.txt](https://github.com/librenms/librenms/files/497392/quanta.lb4m.walk.txt)

**Comment by laf** [comment]
Thanks @f0o

**Comment by laf** [comment]
All sorted.
