### ISSUE TITLE
Availability map widget can not remove disabled or ignored 

### ISSUE THREAD

**Issue by anden4380** [librenms/librenms#4621]
Availability map widget now shows disabled and ignored devices i need to remove thes devices from the view. and if i go under settings for the view and select "Disabled/ignores" and set it to yes then they are still showed but in red insted

**Comment by crcro** [comment]
put disabled/ignored on no and try again

**Comment by anden4380** [comment]
Have try same problem and i have updated 

Set to yes: http://ongo-bongo.dk/YES.PNG

Set to no: http://ongo-bongo.dk/NO.PNG

**Comment by crcro** [comment]
found the issue, pushed fix

**Comment by anden4380** [comment]
Thanks :-) no problem

**Comment by anden4380** [comment]
Still not working still show Disabled and ignored devices

**Comment by laf** [comment]
@anden4380 have you updated?

**Comment by anden4380** [comment]
Yes

**Comment by crcro** [comment]
Can you please change from widget settings the ignored/disabled to yes and then back to no

**Comment by anden4380** [comment]
yes same as yesterday :-)

**Comment by crcro** [comment]
strange, on my install it works properly, with yes:

<img width="536" alt="screen shot 2016-09-28 at 2 09 12 pm" src="https://cloud.githubusercontent.com/assets/3048315/18911348/3cf9a798-8585-11e6-8ab6-86e009e1f5ad.png">

with no:

<img width="397" alt="screen shot 2016-09-28 at 2 09 28 pm" src="https://cloud.githubusercontent.com/assets/3048315/18911355/42eb9184-8585-11e6-8d45-41bd26f97f62.png">

**Comment by anden4380** [comment]
Yes but all but all disabled devices goes to down on the map insted of just remove
