### ISSUE TITLE
Fortigate 30E - ports not showing

### ISSUE THREAD

**Issue by amisense** [librenms/librenms#4624]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [Y] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
====================================
Version info:
Commit SHA: 7b4988aab79cac8bd3f129c802d1bf3e6fbb1e82
[WARN]    Your local git contains modified files, this could prevent automatic updates.
Modified files:
    mibs/FORTINET-CORE-MIB.mib
DB Schema: 138
PHP: 7.0.8-0ubuntu0.16.04.2
MySQL: 10.0.25-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP version: 5.7.3
====================================
- [ ] Please provide as much detail as possible.
Fortinet Fortigate 30E - ports not showing. Inventory shows Ethernet ports but port name is blank.
OS: Fortinet Fortigate v5.4.1 (build1064) 
Object ID 	enterprises.12356.101.1.306

Working ok for -
30D - Fortinet Fortigate v5.2.4 (build0688) - enterprises.12356.101.1.304
50B - Fortinet Fortigate v4.0.4 (build0313) - enterprises.12356.101.1.502
60C - Fortinet Fortigate v5.0.12 (build0318) - enterprises.12356.101.1.615

[FGT_30E_discovery.txt](https://github.com/librenms/librenms/files/495201/FGT_30E_discovery.txt)
[FGT_30E_poller.txt](https://github.com/librenms/librenms/files/495202/FGT_30E_poller.txt)

Thanks,

**Comment by Rosiak** [comment]
Pretty sure it's related to #3859 and #4421.

**Comment by laf** [comment]
please see the related issues.

**Comment by amisense** [comment]
Thanks Rosiak for the posts.
Added value to "Description" and all ports picked up on discovery run.
