### ISSUE TITLE
Not all dnos dell N2000/3000/4000 are supported

### ISSUE THREAD

**Issue by zamolxe** [librenms/librenms#4627]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [X] Please provide as much detail as possible.

Some of the Dell N2000/3000/4000 are missing
Below is the complete includes/discovery/os/dnos.inc.php build based on the oids provided by dell openmanage
[OpenManage Network Manager 6 Device Drivers and OSs Supported.pdf](https://github.com/librenms/librenms/files/495460/OpenManage.Network.Manager.6.Device.Drivers.and.OSs.Supported.pdf)

```
<?php

if (!$os) {
    if (strstr($sysObjectId, '.1.3.6.1.4.1.6027.1.')) {
        $os = 'dnos';
    }
    if (strstr($sysObjectId, '.1.3.6.1.4.1.674.10895.3042')) {  // N4032
        $os = 'dnos';
    }
    if (strstr($sysObjectId, '.1.3.6.1.4.1.674.10895.3044')) {  // N4032F
        $os = 'dnos';
    }
    if (strstr($sysObjectId, '.1.3.6.1.4.1.674.10895.3045')) {  // N4064
        $os = 'dnos';
    }
    if (strstr($sysObjectId, '.1.3.6.1.4.1.674.10895.3046')) {  // N4064F
        $os = 'dnos';
    }
    if (strstr($sysObjectId, '.1.3.6.1.4.1.674.10895.3053')) {  // N2024
        $os = 'dnos';
    }
    if (strstr($sysObjectId, '.1.3.6.1.4.1.674.10895.3054')) {  // N2048
        $os = 'dnos';
    }
    if (strstr($sysObjectId, '.1.3.6.1.4.1.674.10895.3055')) {  // N2024P
        $os = 'dnos';
    }
    if (strstr($sysObjectId, '.1.3.6.1.4.1.674.10895.3056')) {  // N2048P
        $os = 'dnos';
    }
    if (strstr($sysObjectId, '.1.3.6.1.4.1.674.10895.3057')) {  // N3024
        $os = 'dnos';
    }
    if (strstr($sysObjectId, '.1.3.6.1.4.1.674.10895.3058')) {  // N3048P
        $os = 'dnos';
    }
    if (strstr($sysObjectId, '.1.3.6.1.4.1.674.10895.3059')) {  // N3024P
        $os = 'dnos';
    }
    if (strstr($sysObjectId, '.1.3.6.1.4.1.674.10895.3060')) {  // N3024P
        $os = 'dnos';
    }
    if (strstr($sysObjectId, '.1.3.6.1.4.1.674.10895.3061')) {  // N3024F
        $os = 'dnos';
    }
}
```

/Alex

**Comment by cschoonover91** [comment]
@laf has a PR out on refactoring this (#4572). Based on his work, the provided code is out of date. May need to wait until the PR is merged before adding the new OIDs into the array.

**Comment by zamolxe** [comment]
No worries, I've been running my version of file for about 1year, never had the time to actually request and update here until now. 
Thanks!

**Comment by murrant** [comment]
Any reason we can' t just check for `.1.3.6.1.4.1.674.10895`??

**Comment by laf** [comment]
Powerconnect has `.1.3.6.1.4.1.674.10895.3000.1.2.100.1.0` which would also match those. We could just exclude those but we can't be sure we won't impact something else.

**Comment by BryannaM** [comment]
Just to add to this we have a Dell N1548P and it is not detected and it has a different ObjectID then even the ones asked to be added. I attached a screenshot to show this. 
![2016-10-06_10h17_57](https://cloud.githubusercontent.com/assets/22663346/19158530/b4f2d3b2-8bae-11e6-8c0c-8ae8557e3d01.png)
