### ISSUE TITLE
Clone and installation of master branch yields SQL errors.

### ISSUE THREAD

**Issue by mchasteen** [librenms/librenms#463]
So I cloned the master branch of the rep It seems like there is a lot of SQL errors relating to dbInsert function calls.  I ran the build-base.php and it in turn called update.php to update the database to the most current schema.  It looks like there are a lot of insert function calls missing fields that have no default or NULL value and subsequently a lot of SQL error.  It appears that the tables have been expanded but not the code.  Is this just me?  Is there something I missed?

I am running LibreNMS on a LAMP stack on OpenSuSE 13.2.

**Comment by laf** [comment]
This maybe due to mysql running in strict mode (believe this is a newer default):

mysql> SELECT @@GLOBAL.sql_mode;

If you disable that things will be ok. I'd like to fix it though so if you have the output of the build-base.php that would be handy.

**Comment by mchasteen** [comment]
I fixed the base.sql already so that things will be happy.  I changed the values in the fifth field the graph_order field on the INSERT line to int values.  I actually submitted a pull until I started poking around a little more and realized that the update.php just wrote over all the changes I made.  Is it just me or does it drop all the graph types that were imported?

I've been trying to make this work in strict mode as I don't particularly like taking DBs out of strict mode.  I've gone through a few of the dbInsert function calls scattered about and added in function arguments with default values.

**Comment by laf** [comment]
update.php loops through all the sql files in sql-schema/*.sql and plays them through one by one so their is a good chance data inserted in an earlier file is cleared out and re-done. It's done this way so new sql schema / data changes can be made and installs will update to using it.

I imagine the WebUI has a good number of issues with strict mode.

**Comment by f0o** [comment]
Related PR: #450 

@mchasteen can you open a PR for the authors.md and afterwards another for build.sql &co ?

I suppose quite a lot of schemas(schematas?) have to be updated as well to allow strict-mode.
Potentially some UI components as well... Cleaning up code is fun, isnt it? ;)

**Comment by laf** [comment]
I've edited dbFacile.php to log errors back from MySQL and chucked my setup into strict mode.

I'll review the logs tomorrow and post them somewhere, anyone wanting to help fix them can get involved.

Now the question, is this best fixed in the code (i.e where we normally would have a blank insert or update but the column has NOT NULL do we pass a value across (zero for instance), set a default for column of say zero again or change it to NOT NULL? Thoughts?

**Comment by mchasteen** [comment]
Sorry I haven't gotten back.

I think I fixed most of the SQL errors relating to discovery and polling.  I have our devices doing discovery and polling without SQL errors now (for the most part).  I'll submit a pull request.

I fixed a lot of instances where a null value was passed to dbFacile.php but not in a particularly pretty way.  For some I just wrote a foreach loop that would unset null values.

**Comment by laf** [comment]
Thanks, I won't get chance to go through the pr until tomorrow unless someone gets to it first. 

I'm thinking we can potentially fix a lot of this in the db schema rather than code although I'm not sure which way is the recommended way. I'll take a better look tomorrow and comment back.

**Comment by laf** [comment]
PR #521 has sorted a lot of this, thanks for the fixes @mchasteen and @f0o
