### ISSUE TITLE
port values not working for blank ifName

### ISSUE THREAD

**Issue by darkphantam** [librenms/librenms#4630]
Trying to find a way to pull a device interfaces 95th percentile from a graph or interface... does this not exist? I mean the graphs have it from rrd, but i don't see a way to actually grab the statistics from the interface or mib... I need to pull a report on a bunch of interfaces to show their utilization % but doesn't seem to be an API way to get at that info.

Turns out this should be possible but because canopy doesn't supply ifName the lookup doesn't work....

Support was added to the graphs to do lookup for ifDescr/ifAlias but apparently this wasn't included for the code for port statistics.

Example
http://1.1.1.1/api/v0/devices/ace450-1/ports/Canopy%20Multipoint/port_bits?ifDescr=true&height=100&width=450
 i get a reply of an image but if i run 

http://1.1.1.1/api/v0/devices/ace450-1/ports/Canopy%20Multipoint
 i get status:ok port: null

for reference http://1.1.1.1/api/v0/devices/ace450-1/ports returns which could probably also use some cleaning up.

{
  "status": "ok",
  "err-msg": "",
  "count": 2,
  "ports": [
    {
      "ifName": null
    },
    {
      "ifName": null
    }
  ]
}

**Comment by darkphantam** [comment]
Updated the issue after some clarification with LAF over IRC.

**Comment by laf** [comment]
We use ifName as the lookup field in the db. I'm reluctant to change this as people using the existing api call won't expect a different result if we find a port with the name they passed but as ifAlias or ifDescr.

We would be better to try and fix the blank ifName for the device. Please provide the output of `./poller.php -h HOSTNAME -d -r -f -m ports`

**Comment by laf** [comment]
Closing as no further information provided.

Also /api/v0/ports/DEVICE isn't a valid api call.
