### ISSUE TITLE
Error graphing data

### ISSUE THREAD

**Issue by Heliery** [librenms/librenms#4631]
Hi,

I'm french student and I apologize in advance for my mistakes in english.
I've a problem with the graphs of librenms wich doesn't appear. I looked my validate.php and i've this : 

====================================
Version info:
[WARN]    Your install is out of date: 8b68429a0619c627256c31299765ffddb2bdd9dd (Sun, 25 Sep 2016 15:01:58 +0000)
[WARN]    Your local git contains modified files, this could prevent automatic updates.
Modified files:
    snmp.conf.example
DB Schema: 138
PHP: 5.3.3
MySQL: 5.5.47-MariaDB
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.5

====================================
[OK]      Database connection successful
[FAIL]    /var/run/rrdcached/rrdcached.sock doesn't appear to exist, rrdcached test failed
[FAIL]    fping location is incorrect or bin not installed

I just installed rrdtool and i don't understand why rrdcached.sock doesn't exist and why my graphs doesn't appear on my browser.

Thanks you in advance for your help.

**Comment by murrant** [comment]
Is the rrdcached service started?  You can also disable rrdcached in your config by removing or commenting the line:
```
#$config['rrdcached']    = "unix:/var/run/rrdcached/rrdcached.sock";
```

**Comment by Heliery** [comment]
Yes, the rrdcached service is started, and that is the location of the socket.
I'll commenting and uncommenting the line with restart to see if there is any change

**Comment by Heliery** [comment]
I did a new install of rrdtool, with this tutorial : http://docs.librenms.org/Extensions/RRDCached/ and I've again my graphs.
But there is the same problem, they can't be draw. I think it's because the data aren't spend on my server.
How can i resolve it ?

**Comment by laf** [comment]
Please post the output of a fresh `./validate.php` run, if you've now fixed rrdtool you should see different output.

**Comment by laf** [comment]
Also a screenshot of one of the devices main pages in question would help.

**Comment by Heliery** [comment]
That's my ./validate.php : 
`[root@CEStestCIS librenms]# ./validate.php
====================================
Version info:
[WARN]    Your install is out of date: 8b68429a0619c627256c31299765ffddb2bdd9dd (Sun, 25 Sep 2016 15:01:58 +0000)
[WARN]    Your local git contains modified files, this could prevent automatic updates.
Modified files:
    snmp.conf.example
DB Schema: 138
PHP: 5.3.3
MySQL: 5.5.47-MariaDB
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.5

====================================
[OK]      Database connection successful
[FAIL]    fping location is incorrect or bin not installed
`
And that's a screenshot of my devices 
![screenshot_2](https://cloud.githubusercontent.com/assets/22475303/18905333/f840ae2a-8562-11e6-83a2-91c26e850848.png)

**Comment by laf** [comment]
Please fix the FAIL. I expect after things will work.

**Comment by laf** [comment]
If you only just fixed it - wait 15 minutes.

**Comment by Heliery** [comment]
I've the same error, you don't have any idea ?

**Comment by laf** [comment]
Post the output ./validate.php again

**Comment by Heliery** [comment]
This is it : 

====================================
Version info:
Commit SHA: 20a3b555abcfdbb98bcda40c48ef1ed3bfd15747
[WARN]    Your local git contains modified files, this could prevent automatic updates.
Modified files:
    snmp.conf.example
DB Schema: 140
PHP: 5.3.3
MySQL: 5.5.47-MariaDB
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.5

====================================
[OK]      Database connection successful

**Comment by laf** [comment]
Do you have the cron job setup?

I'd probably suggest you revisit the install docs, the fact you got to this point with numerous config errors that are covered at install time means you may have missed other critical steps that validate hasn't picked up on.

**Comment by laf** [comment]
No further info provided.
