### ISSUE TITLE
RRDTool Segfault / Traffic Stats Issue

### ISSUE THREAD

**Issue by network-guy** [librenms/librenms#4634]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

Version info:
Commit SHA: 4f90d389c6c53998f0bc8bec16877caf519c5780
DB Schema: 138
PHP: 7.0.8-0ubuntu0.16.04.2
MySQL: 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP version: 5.7.3
# 

[OK]      Database connection successful

I have two devices that are showing a break in traffic statistics every ~6 hours. There is nothing in the device logs or polling logs to indicate a problem. Looking in /var/log/messages I see messages around the same timeframe as the break in stats with the following messages:

Sep 27 09:43:48 librenms kernel: rrdtool[22068]: segfault at 0 ip 00007f502640aecb sp 00007ffe8f427070 error 6 in librrd.so.4.3.5[7f50263d4000+51000]
Sep 27 09:44:24 librenms kernel: rrdtool[22136]: segfault at 0 ip 00007f286112eecb sp 00007ffe52920cb0 error 6 in librrd.so.4.3.5[7f28610f8000+51000]

Again this is only 2 devices, everything else is working fine. Any ideas besides deleting the device and RRD files and re-adding?

Mike

**Comment by murrant** [comment]
Do you use rrdcached?

**Comment by network-guy** [comment]
No, I am not using rrdcached.

**Comment by laf** [comment]
Every 6 hours indicates discovery, however we don't use rrd there so that may just be coincidence.

Maybe try updating rrdtool version?

**Comment by network-guy** [comment]
I updated to 1.5.6. I'll see if that helps.

**Comment by murrant** [comment]
On my setup I get segfaults from rrdtool when I don't use rrdcached.

**Comment by tosiara** [comment]
I have downloaded VMDK and get this errors in syslog just out of the box:
```
root@librenms:~# journalctl | grep rrdtool
Oct 05 16:40:04 librenms kernel: rrdtool[4356]: segfault at 0 ip 00007fe173729ecb sp 00007fff008d7ac0 error 6 in librrd.so.4.3.5[7fe1736f3000+51000]
Oct 05 16:40:59 librenms kernel: rrdtool[4671]: segfault at fffffffffffffff8 ip 00007f87e01127f0 sp 00007ffc3f9e0f00 error 5 in librrd.so.4.3.5[7f87e00f7000+51000]
Oct 05 16:41:29 librenms kernel: rrdtool[4680]: segfault at fffffffffffffff8 ip 00007f1cccb057f0 sp 00007ffeef0ff360 error 5 in librrd.so.4.3.5[7f1cccaea000+51000]
Oct 05 16:41:59 librenms kernel: rrdtool[4684]: segfault at fffffffffffffff8 ip 00007f405d0507f0 sp 00007ffe1082e330 error 5 in librrd.so.4.3.5[7f405d035000+51000]
Oct 05 16:42:29 librenms kernel: rrdtool[4691]: segfault at fffffffffffffff8 ip 00007fbc2948f7f0 sp 00007ffe6e393d90 error 5 in librrd.so.4.3.5[7fbc29474000+51000]
Oct 05 16:43:00 librenms kernel: rrdtool[4715]: segfault at fffffffffffffff8 ip 00007f06e83677f0 sp 00007ffd81038950 error 5 in librrd.so.4.3.5[7f06e834c000+51000]
Oct 05 16:43:30 librenms kernel: rrdtool[4722]: segfault at fffffffffffffff8 ip 00007fb93ae047f0 sp 00007ffef2ddc720 error 5 in librrd.so.4.3.5[7fb93ade9000+51000]
Oct 05 16:44:00 librenms kernel: rrdtool[4726]: segfault at fffffffffffffff8 ip 00007f9f106eb7f0 sp 00007ffcc758c350 error 5 in librrd.so.4.3.5[7f9f106d0000+51000]
Oct 05 16:44:30 librenms kernel: rrdtool[4733]: segfault at fffffffffffffff8 ip 00007f3cc2c827f0 sp 00007ffc6c9418e0 error 5 in librrd.so.4.3.5[7f3cc2c67000+51000]
```

**Comment by laf** [comment]
Have you updated?

**Comment by tosiara** [comment]
You mean ubuntu dist-upgrade?

**Comment by laf** [comment]
librenms

**Comment by tosiara** [comment]
I use this version: `12c4b8a - Wed Oct 05 2016 11:09:46 GMT+0300` - which was the latest available

**Comment by oyvellef** [comment]
Same problem here;

Fresh Ubuntu 16.04, installed and updated all packages today, and installed LibreNMS fresh. Added one device (Cisco ASA) and started seeing the segfaults whenever I view the dashboard. The "smaller" traffic graphs (mouseover the device) are missing, while the main ones seem OK.

LibreNMS Version: aac9b73c9136d1027595b5f630b6f4d4071ff331
DB Schema: 148
PHP: 7.0.8-0ubuntu0.16.04.3
MySQL: 5.7.12-0ubuntu1.1
RRDTool: 1.5.5
SNMP: NET-SNMP 5.7.3

**Comment by murrant** [comment]
If you get the specific rrdtool command that segfaults and run it on the command line, does it still segfault?

Appending /debug to the url or clicking the show command button on graphs will help get the rrdtool command.

**Comment by oyvellef** [comment]
Yes, if I run the rrdtool in the shell (As root) it segfaults. Attached a screenshot showing failed graphs and the rrdtool command.

![2016-11-07 10_21_35-librenms](https://cloud.githubusercontent.com/assets/1540368/20052476/73c78420-a4d4-11e6-8536-e4a8045c782d.png)

**Comment by oyvellef** [comment]
I added a Cisco 3650 switch to the same LibreNMS instance, that works fine, with no segfaults, and the mouseover graphs are displayed correctly.

Is there any debugging I can do to pinpoint this? I'm thinking the SNMP data collected from the ASA may have a different format than from the switch, thus causing the segfaults when rrdtool tries to render it?

**Comment by murrant** [comment]
Sure, the command that is segfaulting, remove parts of the command line until it runs without segfaulting.  Perhaps try adding the rest back after you find the offending bit and report back here.

This may end up being a bug in rrdtool.

**Comment by laf** [comment]
Try updating rrdtool as well.

**Comment by oyvellef** [comment]
Seems the two first CDEF causes the segfault, "CDEF:inB= CDEF:outB=" If I run rrdtool without these I do not get the segfault. 

I've got minimal experience with rrdtool, so I do not know if this is supposed to work with those empty CDEF. Looks like there should be a pair of DEF's in there first, that get the rrd data for the CDEF to to the math on?

I'm looking into upgrading rrdtool, but there is no backport of 1.6 to the Ubuntu 16.04 LTS distro I'm running, so I will have to do some surgery to get the new rrdtool in there.

**Comment by murrant** [comment]
Thanks for digging, it does seem like there should be something after the equals.   I'll look at the code and see.

**Comment by murrant** [comment]
I need to know what graph this is.  I looked at the code, and this looks like it is an issue when no rrds are supplied to the graph code

**Comment by laf** [comment]
I'm guessing overall traffic graph, we exclude a number of ports by default in that (i.e virtual) so some devices end up with no ports being shown.

**Comment by oyvellef** [comment]
The failing graph is named "device traffic", and is indeed the overall traffic for the device.

The device polled is a Cisco ASA firewall context (Cisco's virtualization on the ASA platform), running latest 9.6 code.

**Comment by murrant** [comment]
So, if overall traffic has no ports supplied, what is the best way to handle that?

**Comment by laf** [comment]
@oyvellef add this to config.php:

```php
unset($config['device_traffic_iftype']);
$config['device_traffic_iftype'][] = '/loopback/';
$config['device_traffic_iftype'][] = '/tunnel/';
$config['device_traffic_iftype'][] = '/mpls/';
$config['device_traffic_iftype'][] = '/ieee8023adLag/';
$config['device_traffic_iftype'][] = '/l2vlan/';
$config['device_traffic_iftype'][] = '/ppp/';
```

**Comment by laf** [comment]
@murrant html/includes/graphs/device/bits.inc.php - runs through a couple of loops to exclude certain ports. Virtual is one of the defaults which is most likely used here.

**Comment by oyvellef** [comment]
@laf  Thanks - I've added it to my config, but it does not change anything as far as I can tell. Overall traffic graphs still missing.

I also tried to comment out all the types except l2vlan, but it still fails. 

Do I need to delete the rrd files for this to take effect?

**Comment by laf** [comment]
No you don't need to delete files.

`select port_id, ifType from ports where device_id=X;`

Replace X with the device id.

**Comment by laf** [comment]
@oyvellef any further feedback?

**Comment by oyvellef** [comment]
@laf Sorry, been away for the last week, will look at this when onsite again this week.

**Comment by Banjer** [comment]
I'm running in to the same problem after an update for ubuntu server 14.04 to 16.04.
Is there any progress?

**Comment by oyvellef** [comment]
Looked at this again today, 

@laf - Looks like I have only l2vlan interfaces on this device;
`mysql> select port_id, ifType from ports where device_id=1;
+---------+--------+
| port_id | ifType |
+---------+--------+
|       1 | l2vlan |
|       2 | l2vlan |
|       3 | l2vlan |
|       4 | l2vlan |
|       5 | l2vlan |
|       6 | l2vlan |
|       7 | l2vlan |
|       8 | l2vlan |
|       9 | l2vlan |
|      10 | l2vlan |
|      11 | l2vlan |
|      12 | l2vlan |
+---------+--------+
12 rows in set (0.00 sec)`

So, I unset everything but l2vlan in config.php, and that fixed my mission graphs. I now have the overall graphs rendered just fine. Not sure why it fails when the query lists no other interfaces?

Added this to the end of my config.php;

`unset($config['device_traffic_iftype']);
$config['device_traffic_iftype'][] = '/loopback/';
$config['device_traffic_iftype'][] = '/tunnel/';
$config['device_traffic_iftype'][] = '/mpls/';
$config['device_traffic_iftype'][] = '/ieee8023adLag/';
#$config['device_traffic_iftype'][] = '/l2vlan/';
$config['device_traffic_iftype'][] = '/ppp/';`

**Comment by moxli** [comment]
Hi everyone,
I ran into this issue today.
No traffic graphes are shown at all, everything else seems to work as intended.

Setup:
Ubuntu 16.04 (fresh install)
All packages up2date
Device: Juniper EX2200 Junos Version 15.1R3.6 (only device added so far)

----------------------

root@ubuntu:/opt/librenms# ./validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | 4d0832e4120984fa25de24a8c7367a9e59036799
DB Schema | 190
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

[OK]    Database connection successful
[OK]    Database schema correct

-----------------------------

root@ubuntu:/opt/librenms# journalctl | grep rrdtool
May 15 14:14:27 ubuntu kernel: rrdtool[15764]: segfault at 0 ip 00007f65b2950ecb sp 00007ffe111151b0 error 6 in librrd.so.4.3.5[7f65b291a000+51000]
May 15 14:14:36 ubuntu kernel: rrdtool[15770]: segfault at 0 ip 00007fc49d217ecb sp 00007fff9cdf3320 error 6 in librrd.so.4.3.5[7fc49d1e1000+51000]

----------------------------

Can someone help me out? I am not able to track down the issue.
