### ISSUE TITLE
Creating new BGP connection and deleting old is not reflected in Routing TAB

### ISSUE THREAD

**Issue by ipguru99** [librenms/librenms#4635]
![librenms-copmany-bgp-peers-debug-1](https://cloud.githubusercontent.com/assets/13969224/18880318/191c1150-849d-11e6-80cd-53c119177e2f.png)

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [ N] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release. (Got the Okay from @laf to open anyway)
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

Version info:
[WARN]    Your install is out of date: e8b5c7fe66a7f7781a743c76f2af158faf62c89a (Wed, 14 Sep 2016 03:23:52 +0000)
[WARN]    Your local git contains modified files, this could prevent automatic updates.
Modified files:
    alerts.php
DB Schema: 133
PHP: 5.5.9-1ubuntu4.16
MySQL: 5.5.49-0ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

If customer adds new AND removes old BGP connections, the old connection stays in the Routing TAB with this message: No Such Instance currently exists at this OID

@laf had me run a discovery bgp-peers debug and I also attached what it looks like in the GUI
[librenms-company-bgp-peers-debug.txt](https://github.com/librenms/librenms/files/495945/librenms-company-bgp-peers-debug.txt)

**Comment by laf** [comment]
I've submitted a pull request to hopefully fix this.

However it would be good if could compare the output of these two mysql queries. The second one should include the stale bgpPeer whilst the first shouldn't. Replace device_id= '1' with the actual device id:

```
SELECT * FROM bgpPeers WHERE device_id = '1' AND context_name ='';

SELECT * FROM bgpPeers WHERE device_id = '1' AND (context_name ='' OR context_name IS NULL);
```

**Comment by ipguru99** [comment]
I just ran both of those queries and that is exactly what happened.

The second query includes the stale statement with the bgpPeerState showing
'exists' on the good one and the stale one shows 'No Such Instance
currently exists at this OID'

Thanks!

If there is anything else I can do to help test this, please let me know..
thanks again, Neil!

**Comment by laf** [comment]
Just update and all should be well :)
