### ISSUE TITLE
Brother printer shows 150% toner level

### ISSUE THREAD

**Issue by compuguy** [librenms/librenms#4637]
> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

This was discussed in #3030, but the fix only works with brother printers that just have an os of "brother". Our multifunction brother printer has an os of "	Brother Printer Firmware Ver.H" which pull request #4526 does not recognize.

We are on Version	dc26f09 - Mon Sep 26 2016 17:34:54 GMT-0400

**Comment by crcro** [comment]
your device is recognized as brother printer?
please post a pastebin link to output of:

./discovery.php -h your-device -r -d -m os

**Comment by compuguy** [comment]
@crcro Here's the discovery output

https://gist.github.com/compuguy/5d8626ed375d0d0474d7323ae5f5c007

**Comment by crcro** [comment]
in printer's webui do you see toner levels? 
from what i found some brother doesn't export toner level, and from standard printer oid you get only -3 as value

**Comment by compuguy** [comment]
@crco Yes, except for the one that is really empty (0%), the rest output 150% in the UI.

**Comment by JamesonFinney** [comment]
I'm seeing this in the poll log of my Brother printer:
 `[RRD Disabled]SQL[UPDATE `toner` set `toner_current` ='150',`toner_capacity` ='-2' WHERE `toner_id` = '12'] `

It's been a while since I've worked with PHP, but it looks as though it always displays toner_current as 150, and varies toner_capacity between 0 and -3.

**Comment by crcro** [comment]
@compuguy ... can you please tell me the current levels reported in printer's menu for toners, to make a match based on values returned on snmp?

**Comment by compuguy** [comment]
@crcro Sure, here's the current toner levels from the interface:

`Toner Cyan (C)**
(30.00%)
Toner Magenta (M)**
(30.00%)
Toner Yellow (Y)**
(30.00%)
Toner Black (BK)**
(0.00%)`

**Comment by compuguy** [comment]
@crcro Here is the output from toner levels using the discovery script (./discovery.php -h *hostname* -d -m toner)

https://gist.github.com/compuguy/3a2f478ef0de5d0214c0664b1d22e89c

**Comment by crcro** [comment]
@JamesonFinney ... what capacity is reported by the printer for that toner?

**Comment by JamesonFinney** [comment]
@crcro @compuguy and I are working with the same printer. 

There's a [http://serverfault.com/questions/422483/looking-for-toner-level-oid-for-nagios-snmp-for-brother-9460](Server Fault article) that seems to be relevant to this. We're getting -3 on our cartridges at 30%, and 0 for the cartridge that is empty. We don't have a full cartridge at this time to test with.

**Comment by compuguy** [comment]
@crcro @JamesonFinney A coworker was able to find information on both outputs on toner, and its apparently pretty limited. Brother doesn't provide downloads for mibs, you have to contact them via email.

http://oid-info.com/get/1.3.6.1.2.1.43.11.1.1.9
http://oid-info.com/get/1.3.6.1.2.1.43.11.1.1.8

https://help.brother-usa.com/app/answers/detail/a_id/52976/kw/mib/session/L3RpbWUvMTQ3NTAwMzM1NS9zaWQvaEpYVDRJX20%3D

**Comment by crcro** [comment]
@JamesonFinney ... that was my thinking ... -3 => 30%, 0 = 0, but that's all or maybe there are others like -2 = 20%, -7 = 70% ... stupid but there is a possibility.

**Comment by JamesonFinney** [comment]
The system is a Brother MFC-L8850CDW.
```
LibreNMS Discovery
Version info:
Commit SHA: dc26f097b06aa3836a540ce6743d8f33b3dc9ea0
DB Schema: 138
PHP: 5.5.9-1ubuntu4.19
MySQL: 5.5.52-MariaDB-1ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

DEBUG!
SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1]
SQL[SELECT revision FROM `dbSchema`]
DB Schema already up to date.
SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `device_id` = '23' ORDER BY device_id DESC]
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '23']
brother 23 brother  (printer)
#### Load disco module os ####
SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0]
Brother NC-8600h, Firmware Ver.H  ,MID 8CE-515,FID 2

SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Ovqn -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysObjectID.0]
.*.4.1.24*.1

| Brother NC-8600h, Firmware Ver.H  ,MID 8CE-515,FID 2 | .1.3.6.1.4.1.2435.2.3.9.1 |
SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Oqvn -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalDescr.1]
No Such Object available on this agent at this OID


>> Runtime for discovery module 'os': 0.147 seconds
#### Unload disco module os ####

SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '23' AND `attrib_type` = 'poll_mib' ]
SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='printer',`last_discovered_timetaken` ='0.148' WHERE `device_id` = '23']
Discovered in 0.148 seconds

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','23','1475006731.8762','0.199','1')]
./discovery.php 23 2016-09-27 20:05:32 - 1 devices discovered in 0.199 secs
MySQL: Cell[1/0s] Row[4/0s] Rows[1/0s] Column[0/0s] Update[1/0.02s] Insert[1/0.01s] Delete[0/0s]
```

**Comment by crcro** [comment]
same as @compuguy :)
can you post a pastebin link with full output, to find a thing to match only this brother model from all others ...

**Comment by JamesonFinney** [comment]
Perhaps I wasn't clear earlier. @compuguy and I are coworkers; we're working with the exact same printer. We were examining the system earlier to see if the fix for issue #3030 gave us valid ink levels. Unfortunately, it did not.

**Comment by crcro** [comment]
my bad :) ok, please provide a full ./discovery.php -d of the host to find a way to match this one apart of other brother printers and prepare a fix.

**Comment by JamesonFinney** [comment]
No worries. I've put the full discovery data on [PasteBin](http://pastebin.com/ZrvxvN7p).

**Comment by compuguy** [comment]
On 3680849 but the toner levels are still displaying 150%.
![librenms](https://cloud.githubusercontent.com/assets/864349/19088703/54e85ba0-8a45-11e6-98bb-86af24a27cd3.png)

**Comment by murrant** [comment]
Should be fixed now, reopen if it is not.

**Comment by compuguy** [comment]
@murrant I'll check when I get into the office on Monday.
