### ISSUE TITLE
Elevated CPU on switches During Port Scan from LibreNMS

### ISSUE THREAD

**Issue by GinoM** [librenms/librenms#4643]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X ] Please include all of the information between the ====================================
Version info:
Commit SHA: efc4d59324e07faa5bb315686743499f3b8856d2
DB Schema: 139
PHP: 5.4.45-0+deb7u4
MySQL: 5.5.50-0+deb7u2
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.4.3

====================================
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

Scanning causes unusually high CPU Usage on Juniper EX4200 Series switches
I have experienced this across multiple JunOS Releases

**Comment by laf** [comment]
The only thing you can do here is disable some polling modules.

The rest is down to juniper really. We don't hit devices that hard so unless they've got a sucky CPU in them or really bad COP policies then they should be fine.

**Comment by GinoM** [comment]
OK, thanks for the response, its an older switch, I'm sure its junipers
fault, however I don't get elevated CPU with other network monitoring
softwares just LibreNMS

Gino


On Tue, Sep 27, 2016, at 08:06 PM, Neil Lathwood wrote:
> The only thing you can do here is disable some polling modules.
> The rest is down to juniper really. We don't hit devices that hard so
> unless they've got a sucky CPU in them or really bad COP policies then
> they should be fine.
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
>


Links:

  1. https://github.com/librenms/librenms/issues/4643#issuecomment-249982358

**Comment by DennisSc** [comment]
https://en.wikipedia.org/wiki/Observer_effect_(physics)

I am monitoring some 400MHz Intel CPU routers which do not show any CPU increase at all when being polled. But then again, the manufacturer's management software itself relies heavily on snmp so maybe its just the snmp implementation of your juniper switch causing that cpu load increase.

regards

**Comment by laf** [comment]
I expect the other software you use doesn't monitor half as much as what we do automatically.

I'd suggest disabling some polling modules that you don't need to lower the impact on the end device.
