### ISSUE TITLE
Support for F5 LTM + GTM Pools and Pool Traffic

### ISSUE THREAD

**Issue by GinoM** [librenms/librenms#4644]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the ====================================
  Version info:
  Commit SHA: efc4d59324e07faa5bb315686743499f3b8856d2
  DB Schema: 139
  PHP: 5.4.45-0+deb7u4
  MySQL: 5.5.50-0+deb7u2
  RRDTool: 1.4.7
  SNMP: NET-SNMP version: 5.4.3
# 
- [x] If you would like us to add a new device then please provide the information asked for [here]
  https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/bigip-external-monitoring-implementations-11-4-0/8.html
- [x] Please provide as much detail as possible.

Would like to be able to monitor LTM Pool traffic loads and Traffic Per VIP inside LibreNMS

right now LTM and GTM Devices from F5 don't really show any details except for the primary uplink interfaces, VirtualIP traffic and Pool traffic loads would be ideal.

This feature works in AKIPS, SolarWinds and OpenNMS

I am running BigIP OS Release 11.6.1

**Comment by laf** [comment]
You will need to provide us a full snmpwalk of the device with the relevant mibs loaded.

**Comment by GinoM** [comment]
hmm, having a problem where a full walk seems to hang at TCP-MIB::tcpOutRsts.0 = Counter32 xyz
not sure, but I can do walks against specific MIBS just fine,  perhaps I'm doing my walk wrong I am typing
`snmpwalk -v2c -c foo -M /opt/librenms/mibs/ ltmserver.local`

I tried removing the TCP-MIB and IPV6-TCP-MIB and that seems to fix the walk, strange behavior however.. i'll paste the output

**Comment by GinoM** [comment]
got it working had to set a very long timeout
` snmpwalk -v2c -c dcnas.ask -M /etc/snmp/mibs/:/usr/share/snmp/mibs/ lb1a.las1.neten
g.ask.com -r 10 -t 120`

**Comment by adaniels21487** [comment]
Hi Team,
I started work on this one a few months ago at: https://github.com/adaniels21487/librenms/tree/feature/bigip
The MIB is very nasty, see here:
https://ccie-or-null.net/2014/01/06/poll-individual-virtual-server-statistics-on-f5-ltms-using-snmp/

I have a bit on at the moment but I could get to this in a month or so.
if someone else needs this more urgently, feel free to take it over.

Aaron

**Comment by adaniels21487** [comment]
Hi Team,
So this one is about 80% there. I am pulling LTM VS, Pool and Pool Member details. and graphing connections at the VS and Pool Member level. Feel free to take a look at:
https://github.com/adaniels21487/librenms/tree/feature/bigip

Thanks,
Aaron

**Comment by laf** [comment]
Great work @adaniels21487 :)

I've not looked at the code in detail but the only thing I'd say at the moment is (imho) we shouldn't be adding more poller/discovery modules that are specific to vendors, we've inherited some of those and added some in the past. This probably should be in a loadbalancer poller module and we can then move the cisco-ace one into it as well.

**Comment by laf** [comment]
Should be resolved now.
