### ISSUE TITLE
need to separate authentication from authorization and clean up auth code

### ISSUE THREAD

**Issue by ekoyle** [librenms/librenms#4646]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

I keep running into issues caused by the legacy authentication code that was inherited.  I think it is time to do some major cleanup, however I don't think we can do it right without making backwards-incompatible configuration changes.
1. We need to separate authentication and authorization
   - Allow users to select different methods for each, ie. HTTP authentication with LDAP authorization
2. Remove duplicate code
   - ad-authorization.inc.php is a copy of active-directory.inc.php
   - ldap-authorization.inc.php is a copy of ldap.inc.php
   - ldap authorization should be made generic enough to support active directory LDAP
3. remove any dependencies from alerts/polling on authentication code
   - cache email addresses in database instead of hitting authentication module?
   - allow users to override data from directory?

How would we accomplish this without breaking config format, or how do we alert users before making config changes?

**Comment by ekoyle** [comment]
Also, I just looked and it seems that with AD authentication, the ports page on a single device authenticated over 580 times... with 580 separate LDAPS connections...  The SSL overhead alone on that is insane.  My authentication servers do not need this kind of load, and I'm sure it doesn't help responsiveness for the web UI...  (another justification to accept #4608, amirite?)

**Comment by murrant** [comment]
I'm sure all those connections are from the graphs.  They are all generated in separate connections...

**Comment by ekoyle** [comment]
Yes, and also other various resources.  It seems like remembering that we
have authenticated would be a more reasonable approach, though.  I was
blown away by the sheer volume of requests.  I'm lucky our AD admins
haven't blocked me yet.

-- 
Eldon

**Comment by pblasquez** [comment]
I am also seeing these problems, and have isolated most of it to the get_userlist() function  in html/includes/authentication/ldap.inc.php.

This function dumps your entire LDAP DB to an array, then iterates that array for the one username it is looking for.

It does this for all calls, without caching.  The main issue I saw was in the association of usernames to dashboards, as it calls get_userlist() for every single dashboard. This was causing huge bursts of LDAP traffic.  I have locally patched this to bypass the get_user() call on the get_dashboards() function and replace it with a static value.

**Comment by murrant** [comment]
In ad auth, I removed anything that called get_userlist() and searched for one entry with a direct ldap query.  

At any rate, some caching would probably do wonders.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/need-to-separate-authentication-from-authorization-and-clean-up-auth-code/1161
