### ISSUE TITLE
Cannot add device using the GUI but it works on the CLI.

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#4655]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

Hi,

I am having issues adding the device using the GUI while adding the same device using the CLI works without issues; see below. What could I be wrong?
![snap1](https://cloud.githubusercontent.com/assets/16717388/18912642/c9dafd30-8583-11e6-9c76-960ebdcccfcd.png)

![snap2](https://cloud.githubusercontent.com/assets/16717388/18912594/8288da74-8583-11e6-83d0-7060626790a5.png)

![snap3](https://cloud.githubusercontent.com/assets/16717388/18912645/cdf3e0bc-8583-11e6-8244-1d61371aa340.png)

**Comment by laf** [comment]
Try specifying v2c on the cli.

The webui and cli are both the same in regards to what they do (same code base)

**Comment by breeman1** [comment]
Hi @laf ,

I can add the device fine on the CLI, the problem I'm having is with the GUI. We have noticed this issue after giving GUI access to our system support users who should be able to add devices via GUI and they were getting the same error massages. These users do not have access to the CLI.
![snap4](https://cloud.githubusercontent.com/assets/16717388/18913260/319b5656-8587-11e6-9a9b-d3e11e908265.png)
What I also noticed is that upon deleting the same device on the GUI and readding it via the CLI, the device number increments as though it was never deleted. You will see in the above screenshot that it became 116 while it was 115 in the previous one. Not a big deal but just thought I should bring it to your attention.
![snap5](https://cloud.githubusercontent.com/assets/16717388/18913328/8e8ecd8e-8587-11e6-9c2d-ead539454e93.png)

**Comment by laf** [comment]
Those are just IDs and will increment every time a device is added.

Make sure no special characters are in the community string, aside from that I'm not sure. It's the same code base so it doesn't seem possible that one can react differently.

**Comment by breeman1** [comment]
Hmm, It is weird as there are no special characters in community string.

**Comment by breeman1** [comment]
The point you mentioned about special characters in community strings helped me a lot as I wondering why I was not able to able to add this device via SNMPv3 on the CLI. I changed the the authentication and password credentials to normal text and everything worked:). I have been troubleshooting this problem the whole day. The GUI still does not work though.

**Comment by laf** [comment]
I don't know what else to suggest. I don't personally see this issue and we've not had reports of it from others.

**Comment by breeman1** [comment]
I did some further testing and the following is what I found.

- On the CLI, a community string with special characters can be added successfully if enclosed in single quotes. Without single quotes it does not work for reasons you mentioned.

![snap1](https://cloud.githubusercontent.com/assets/16717388/18946774/ac2f196c-8630-11e6-8df7-f1aff6681455.png)


- On the GUI, adding the same host with or without single quotes on the community string does not work
![snap2](https://cloud.githubusercontent.com/assets/16717388/18945905/d75ff114-862c-11e6-98f4-ceddeffe1b96.png)
![snap3](https://cloud.githubusercontent.com/assets/16717388/18945914/dd94fbce-862c-11e6-9929-e384cfdcba13.png)

- However when I click on the "**Force add - No ICMP or SNMP checks performed**" tick box, then I am able to add the device successfully via the GUI.
![snap4](https://cloud.githubusercontent.com/assets/16717388/18945969/291dd408-862d-11e6-9315-d3c46c365410.png)
![snap5](https://cloud.githubusercontent.com/assets/16717388/18945976/3003926c-862d-11e6-85eb-e59bb3270ac3.png)

**Comment by Ftelf** [comment]
The same, it started few days ago, also any device cannot be edited. It says that is has been updated, but in reality nothing is saved.

**Comment by laf** [comment]
I've just tested adding a device on latest master with no issues.

I think you guys are going to have to share some more details like transport, port, community, snmp version. Without this we can't test further.

**Comment by allano337** [comment]
I just added a new device that has $ in the community without any issues via the GUI. I did the snmpwalk first via CLI and it worked too. Yes you need to put '$' in the command via CLI.
we're running on: Centos 7
Version	e3bdc2f - Wed Sep 28 2016 23:40:41 GMT-0700
DB Schema	#140
Apache	nginx/1.6.3
PHP	5.4.16
MySQL	10.0.25-MariaDB
RRDtool	1.4.8

**Comment by laf** [comment]
Thanks for access.

So this is because you've got STRICT_TRANS_TABLES enabled - the validate output pasted above isn't the full thing.

Please disable that as per our install docs.

**Comment by breeman1** [comment]
HI @laf , I am not sure to who your reply is address to. In my case the STRICT_TRANS_TABLES is turned off as per below.
![snap1](https://cloud.githubusercontent.com/assets/16717388/18987808/c5e7586e-8703-11e6-8177-e72f32098111.png)
Please let me know what other information you need as I believe the pictures I have shared reflect all the information you require. My community is @bH$$Epq

**Comment by laf** [comment]
Whoever "Ftelf" is on irc.

If that's not you, we need the info I asked for above.

**Comment by laf** [comment]
Have you tried a more simple community to see? I expect it's something to do with the @ or $ symbols.

**Comment by breeman1** [comment]
Ok that is not me:).

**Comment by breeman1** [comment]
Using single quotes works in the CLI and so I would have expected that using the same logic of inserting single quotes should work as well on the GUI, but it doesn't as I showed using the screenshot in my earlier post.

**Comment by breeman1** [comment]
Will it feasible to investigate an option of accepting alpha-numeric community strings via the GUI? The servers we were wanting to add fall outside our domain and therefore we cannot easily request the communities to be changed.

**Comment by allano337** [comment]
You don't use the single quotes in the GUI for the community only in the CLI.  What happens when you perform the snmpwalk, if it fails more than likely it's a firewall issue. You can add devices by forcing them as you stated but it's bypassing snmp.

**Comment by breeman1** [comment]
So I tried to redo this whole exercise in our lab setup where we have a LibreNMS VM that has direct access to the internet and I am getting similar results where;
![snap4](https://cloud.githubusercontent.com/assets/16717388/19014266/1b83899c-87e9-11e6-92dd-00d78aa5db29.png)
- Adding a device via CLI works for both scenarios when we tested with two community strings; public and @bH$$Epq. The only exception is that the later community string has to be enclosed in single quotes to be accepted, see below.
![snap2](https://cloud.githubusercontent.com/assets/16717388/19014272/3ab0e0d0-87e9-11e6-82ab-34341f78c4e6.png)
![snap5](https://cloud.githubusercontent.com/assets/16717388/19014275/4487f71a-87e9-11e6-8687-a209dd9da3a5.png)

On the GUI nothing works except when you click on the "Force add - No ICMP or SNMP checks performed" tick box (last two screenshoots below) as explained earlier. Once the device is added either via the CLI or the GUI with the "Force add - No ICMP or SNMP checks performed enabled, then the device is discovered and polled normally. 
![snap1](https://cloud.githubusercontent.com/assets/16717388/19014293/e8a8fbdc-87e9-11e6-8936-eeb22261706a.png)
![snap3](https://cloud.githubusercontent.com/assets/16717388/19014294/ecc6a732-87e9-11e6-98a2-0549262d9d12.png)
![snap6](https://cloud.githubusercontent.com/assets/16717388/19014295/f54829bc-87e9-11e6-8e11-69486b43f509.png)
![snap7](https://cloud.githubusercontent.com/assets/16717388/19014296/fa901dbc-87e9-11e6-9ad9-1ef4ae7f2245.png)

**Comment by allano337** [comment]
As previously stated, what do you get when you do an snmpwalk on the devices from the CLI?

**Comment by laf** [comment]
So I've tested this using `@bH$$Epq` and it still works for me in the webui.

However cli doesn't, it appears to convert that name to `@bH19980Epq`.

Working on it.

**Comment by laf** [comment]
Ok so 19980 is from the $$: `echo $$`

So this is really as simple as the user HAS to wrap the community in quotes. We can't do anything as it comes through to php like that.

I'll update the docs and fix the edit device which did have an issue due to non-numerical value for poller_group.

**Comment by laf** [comment]
Doc fix and snmp edit fix submitted.

**Comment by bh** [comment]
WTF? Just unsubscribed ;-)

**Comment by laf** [comment]
lol sorry :(

**Comment by breeman1** [comment]
I managed to track the source of our problems with adding the devices via the GUI. It was a PHP security setting where we had disabled the ability of PHP to execute shell commands. The culprit function is `shell_exec` in `disable_functions` portion of the /etc/php/7.0/cli/php.ini and /etc/php/7.0/apache2/php.ini files. You can close this issue and thanks everyone for your help :)
