### ISSUE TITLE
RRD traffic graphs stopped working

### ISSUE THREAD

**Issue by DennisSc** [librenms/librenms#4657]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible. 

```

====================================
Version info:
Commit SHA: edbb6ae0e3b624d1116af5796527cbbc2f2568df
DB Schema: 140
PHP: 5.6.23-0+deb8u1
MySQL: 10.0.25-MariaDB-0+deb8u1
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2.1

====================================
[OK]      Database connection successful
```

Hello,
this is more troubleshooting that a software issue, I'm afraid, so I apologize in advance.
Recently, I replaced the mainboard of the hypervisor running my libreNMS virtual machine instance, and since that downtime (libreNMS was shut off for 3 hours, between around 18:00 and 21:00), all my RRD port traffic graphs started showing no traffic (old data was still there, just no new data), on all devices. 
I checked permissions of /opt/librenms and did a chown -R librenms:librenms to be sure, checked ./validate.php output, updated via daily.sh and manually via git clone, tried rediscovering some devices via GUI and CLI (many times) which didn't make any change... the RRD files are there, rrdtool is working (at least the info command). AFAIK I do not have rrdcached running.

I already tried deleting and re-adding one device and this helped for this particular device, traffic data started to appear again - but historical data was of course lost in the process. I also looked at one port's RRD file with rrdtool, and it really contains only "NaN" as values since the time of hardware replacement. I don't want to delete and re-add all devices, especially those which are polling services, and I want to keep my historical data if ever possible.

(How the *#!$ can this even happen with that fat virtualization layer in between hardware and librenms? well, anyway). My best guess is that a change in the physical network port configuration of the virtualization host (which of course is also monitored as a librenms device) triggered something bad inside librenms when polling this "changed" device, and all rrd traffic graphs (or the "thing" that polulates them with data?) went haywire as a result.

Below is a screenshot of a device whose rrd graphs stopped working:
![nms1](https://cloud.githubusercontent.com/assets/11349712/18925835/c62bcb88-85b5-11e6-9f50-5dc2c0a84755.PNG)

And here is a screenshot showing the other, deleted and re-added device which apparently works again:
![nms2](https://cloud.githubusercontent.com/assets/11349712/18925872/eadda42e-85b5-11e6-87eb-9a395c59c3d9.PNG)

How did things get broke? What can I do to debug and/or fix this?

Regards,

Dennis

**Comment by laf** [comment]
Clock change?

I expect if you run `./poller.php -h HOSTNAME -d -r -f -m os`

Get one of the rrdtool update commands from that output and run it - see what it says.

**Comment by DennisSc** [comment]
Wow. Indeed,

> 
ERROR: /opt/librenms/rrd/HOSTNAME/ping-perf.rrd: illegal attempt to update using time 1475088262 when last update time is 1475100006 (minimum one second step)

The system time is correct, though... is the difference of 11774 in seconds? Then I should be up and running by three hours from now... :) Or what time do I need to change?

regards

**Comment by laf** [comment]
I think it is in seconds

At some stage the time has changed, even if it was for one poll before shifting back to the correct time means rrd files are now out of sync.

**Comment by DennisSc** [comment]
It was seconds, and is now back in sync. I'd swear that the time on the "old" system was not off by one day, and I also set up the bios clock and also have ntpd set up, but something somehow must have glitched for one poller cycle (and 24 hours into the future) when the system booted up first time with the new hardware.

Thanks a lot for your help.
