### ISSUE TITLE
ASA Sub-Interfaces don't display in the overall device traffic graph

### ISSUE THREAD

**Issue by network-guy** [librenms/librenms#4662]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

====================================
Version info:
[WARN]    Your install is out of date: 6fdcf8a6da74dd50afb630e26a931417127753f1 (Tue, 27 Sep 2016 21:31:16 +0000)
DB Schema: 139
PHP: 7.0.8-0ubuntu0.16.04.2
MySQL: 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP version: 5.7.3

====================================
[OK]      Database connection successful

LibreNMS does collect stats for these interfaces, but it only graphs physical interfaces on the overall device traffic graph on the main device page. I have several contexts that consist entirely of sub-interfaces so there is no data in this graph. The ports page lists them as `VLAN Subif` and they are stored in the database as `l2vlan` if that helps.

Actually looking at other devices, it appears this may be by design and this may be just a corner case.

**Comment by laf** [comment]
This config show you what types are ignored in that graph:

```php
$config['device_traffic_iftype'][] = '/loopback/';
$config['device_traffic_iftype'][] = '/tunnel/';
$config['device_traffic_iftype'][] = '/virtual/';
$config['device_traffic_iftype'][] = '/mpls/';
$config['device_traffic_iftype'][] = '/ieee8023adLag/';
$config['device_traffic_iftype'][] = '/l2vlan/';
$config['device_traffic_iftype'][] = '/ppp/';

$config['device_traffic_descr'][] = '/loopback/';
$config['device_traffic_descr'][] = '/vlan/';
$config['device_traffic_descr'][] = '/tunnel/';
$config['device_traffic_descr'][] = '/bond/';
$config['device_traffic_descr'][] = '/null/';
$config['device_traffic_descr'][] = '/dummy/';
```

So to include them you can do this in config.php:

```php
unset($config['device_traffic_iftype']);
$config['device_traffic_iftype'][] = '/loopback/';
$config['device_traffic_iftype'][] = '/tunnel/';
$config['device_traffic_iftype'][] = '/virtual/';
$config['device_traffic_iftype'][] = '/mpls/';
$config['device_traffic_iftype'][] = '/ieee8023adLag/';
$config['device_traffic_iftype'][] = '/ppp/';
```

**Comment by laf** [comment]
Tagging to document this. Do not close.

**Comment by network-guy** [comment]
Thanks @laf. I didn't notice that in the docs.

**Comment by laf** [comment]
Docs done.
