### ISSUE TITLE
failed login (auths) logging to syslog

### ISSUE THREAD

**Issue by pinchasMT** [librenms/librenms#4669]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by pinchasMT** [comment]
i would like to request a feature to log failed auth to syslog to be able to setup fail2ban 

similar to:
https://github.com/poweradmin/poweradmin/issues/191
https://ww.sd.vc/wp/2016/02/03/poweradmin-und-fail2ban/

greatly appreciated

**Comment by laf** [comment]
What's wrong with the authlog table that does this?

**Comment by pinchasMT** [comment]
fail2ban monitors log files, i don't think it can monitor sql table

will be happy to be corrected if i"m wrong

if someone knows how to configure fail2ban to monitor sql please share

thank you

**Comment by laf** [comment]
Are you mean to syslog itself. I'm not sure how we can do that from the webui to be honest and it seems something that's not really in scope for us to really do.

**Comment by compuguy** [comment]
Odd, we have alerts from syslog from failed logins, without fail2ban. It is possible.

**Comment by pinchasMT** [comment]
please see
https://ww.sd.vc/wp/2016/02/03/poweradmin-und-fail2ban/

basically 2 lines in config
$syslog_use = true;
$syslog_ident = 'librenms';
and with these settings php will log to local syslog (the host that is running librenms) attempted failed login

**Comment by laf** [comment]
You should consider turning that into a doc we can include.

**Comment by pinchasMT** [comment]
once librenms outputs login errors to syslog, i definitely will

**Comment by laf** [comment]
Closing. Detecting failed logins is already possible.
