### ISSUE TITLE
Javascript errors after clean install

### ISSUE THREAD

**Issue by danielfaulknor** [librenms/librenms#4675]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x ] Please provide as much detail as possible.

I have just installed librenms and I get no styles when I access the GUI post install.

I see the following errors:
(index):68Uncaught ReferenceError: updateResolution is not defined(anonymous function) @ (index):68
(index):126 Uncaught ReferenceError: toastr is not defined(anonymous function) @ (index):126
(index):129 Uncaught ReferenceError: $ is not defined

====================================
Version info:
Commit SHA: e17c34bb7934a96178ebcbd8839f79984796747e
DB Schema: 118
PHP: 7.0.11
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2

====================================

**Comment by laf** [comment]
Please try setting `$config['base_url'] = '/';` or whatever the path to your install is in config.php.

**Comment by danielfaulknor** [comment]
i ended up switching from nginx to apache and it came right
