### ISSUE TITLE
snmp3 noAuthNoPriv doesn't honor included user name (authname)

### ISSUE THREAD

**Issue by Zaxmy** [librenms/librenms#4677]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please provide as much detail as possible.

includes/snmp.inc.php uses hardcoded '-u root' as username, overriding user input

**Comment by laf** [comment]
Thanks for submitting the fix.
