### ISSUE TITLE
PulseSecure appliances are not discovered

### ISSUE THREAD

**Issue by pentium90** [librenms/librenms#4680]
Hi librenms,

In includes/discovery/os/pulse.inc.php string for $sysDescr ('Pulse Connect Secure') is incorrect. Our Pulse devices will only be discovered after I changed string to only 'Pulse Secure', because SNMPv2-SMI::mib-2.1.1.0 returns:

sysDescr.0 = STRING: Pulse Secure, LLC,Pulse Connect Secure,VA-SPE,8.2R1 (build 41241)
sysDescr.0 = STRING: Pulse Secure,LLC,SA-2500,8.0R13 (build 38659)
sysDescr.0 = STRING: Pulse Secure,LLC,SA-6500,8.0R13 (build 38659)

There is also a newer MIB file for Pulse devices (REVISION "201607071610Z") - see attached files.

######################################
Version info:
[WARN]    Your install is out of date: e17c34bb7934a96178ebcbd8839f79984796747e (Thu, 29 Sep 2016 19:25:27 +0000)
[WARN]    Your local git contains modified files, this could prevent automatic updates.
Modified files:
    includes/discovery/os/pulse.inc.php
    mibs/PULSESECURE-PSG-MIB
DB Schema: 140
PHP: 7.0.8-0ubuntu0.16.04.2
MySQL: 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP version: 5.7.3
######################################

[pulse.inc.php.txt](https://github.com/librenms/librenms/files/503180/pulse.inc.php.txt)
[PULSESECURE-PSG-MIB.txt](https://github.com/librenms/librenms/files/503181/PULSESECURE-PSG-MIB.txt)

Best regards

Stephan

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by Stalker71** [comment]
Hi Stephan,

When I created this module last year it worked on real device and on the virtual one.
So far, it still work for us in production. Maybe you have another version as Pulse was just another company out of Juniper. ;-)

So maybe the best way to fix it is to put a "or" instead or delete the old variable match.

**Comment by murrant** [comment]
It would be great if you could post sysDescr and sysObjectID pairs so we can improve the tests.

**Comment by laf** [comment]
Please provide the info as requested in the issue template: http://docs.librenms.org/Support/FAQ/#faq20

**Comment by pentium90** [comment]
>Please provide the info as requested in the issue template: http://docs.librenms.org/Support/FAQ/#faq20

Some data attached:
[MAG-2600_walk.txt](https://github.com/librenms/librenms/files/508358/MAG-2600_walk.txt)
[VA_SPE_walk.txt](https://github.com/librenms/librenms/files/508359/VA_SPE_walk.txt)
[SA-2500_walk.txt](https://github.com/librenms/librenms/files/508355/SA-2500_walk.txt)
[SA-6500_walk.txt](https://github.com/librenms/librenms/files/508356/SA-6500_walk.txt)
[VA-SPE_poller.txt](https://github.com/librenms/librenms/files/508357/VA-SPE_poller.txt)
[VA-SPE_discovery.txt](https://github.com/librenms/librenms/files/508360/VA-SPE_discovery.txt)
[SA-2500_poller.txt](https://github.com/librenms/librenms/files/508362/SA-2500_poller.txt)
[SA-2500_discovery.txt](https://github.com/librenms/librenms/files/508361/SA-2500_discovery.txt)
[SA-6500_poller.txt](https://github.com/librenms/librenms/files/508364/SA-6500_poller.txt)
[SA-6500_discovery.txt](https://github.com/librenms/librenms/files/508363/SA-6500_discovery.txt)

**Comment by laf** [comment]
Are all these different products? Do they do the same thing, same os? You need to give us a bit more info to work this out - I'm not a user of Pulse products nor do I know anything about them.

**Comment by pentium90** [comment]
All of them are different variants of same product (Neoteris/Juniper/Pulse Secure client-to-site VPN gateway) with same OS (called IVE, a hardened Redhat) but different versions, running on different x86 hardware (RAM, CPU, HDD). [https://www.pulsesecure.net/base/images/kb-images/kb-files/techpubs/software/ive/guides/howtos/SA-IC-MAG-SNMP-Monitoring-Guide.pdf](url)

**Comment by laf** [comment]
So we should be renaming this from pulse to ive then?

**Comment by pentium90** [comment]
no, Pulse is ok, only the logo should be updated from Juniper to PulseSecure too:
https://media.licdn.com/mpr/mpr/shrink_200_200/AAEAAQAAAAAAAAQYAAAAJDczYzI4YTdjLWQxYzktNDlkOS1hZWZiLTA2OGExOWU4MjBlYg.png
but this is all just cosmetic: the issue is in "includes/discovery/os/pulse.inc.php" string for $sysDescr ('Pulse Connect Secure')
