### ISSUE TITLE
Cannot delete host because of sensors_to_state_indexes foreign key

### ISSUE THREAD

**Issue by ekoyle** [librenms/librenms#4685]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

TyShawn on IRC was unable to delete a host because the device was referenced by a sensor that was referenced by sensors_to_state_indexes .  For some reason, mysql would not allow me to delete the row referenced in the sensors even though the fkey constraint is 'ON DELETE CASCADE'.

Did we intend to start using foreign key constraints in librenms?

**Comment by laf** [comment]
We've had foreign keys on the sensors states tables for a while now. I've never seen it stop a device being deleted though.

**Comment by ekoyle** [comment]
I wonder if it was a bug in mysql/mariadb (maybe on arm?).  I could see all
the fkey constraints were set to cascade on delete, but it did not allow
that row to be deleted (although other rows were presumably deleted as
expected, as it was only the one host that could not be deleted).

**Comment by laf** [comment]
https://github.com/librenms/librenms/pull/3805 ?

**Comment by ekoyle** [comment]
Similar issue, however it had the new constraint added by #3805.  mysql was
not acting as advertised.

**Comment by laf** [comment]
I'd propose to close, we've not had other reports of the same.

**Comment by ekoyle** [comment]
@TyShawn76: Do you want me to help you try to recreate this issue, or just assume that it was a strange mysql thing that won't happen again?

**Comment by TyShawn76** [comment]
@ekoyle If you need access we can workout some SSH access for you.

**Comment by ekoyle** [comment]
I don't think this is reproducible.  @TyShawn76: let us know if it happens again
