### ISSUE TITLE
Meraki AP always issues alerts for device rebooted

### ISSUE THREAD

**Issue by zamolxe** [librenms/librenms#4691]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [X] Please provide as much detail as possible.

After fixing #4625, now these devices trow device rebooted alerts.
If you need any debugging outputs/logs, please let me know.

/Alex

**Comment by laf** [comment]
Is this on the dashboard showing they've rebooted or actual alerts themselves?

**Comment by zamolxe** [comment]
Both. I've notice the alerts first after the upgrade that fixed the device up/down.

**Comment by zamolxe** [comment]
Update: Alerts are gone now, but overview page (alerts widget) is still displaying it.

**Comment by Rosiak** [comment]
You mean the availability widget or?

**Comment by zamolxe** [comment]
I mean the alerts widget. See attached screen shot.

<img width="1327" alt="screen shot 2016-10-13 at 22 08 56" src="https://cloud.githubusercontent.com/assets/1435948/19365256/355a84da-9192-11e6-9288-10101f3ad0f9.png">

**Comment by zamolxe** [comment]
Just tried the changes you've done, and unfortunately no improvement.

**Comment by laf** [comment]
imho you will need to exclude unifi from the uptime alert (%devices.os not equals "unifi")

**Comment by eajohnson70** [comment]
This is still an issue on the Alerts widget.

**Comment by YukonRob** [comment]
I added a %devices.uptime > "0" to the rule and it did the trick so far.
