### ISSUE TITLE
Better description in Recovery email for Services

### ISSUE THREAD

**Issue by ipguru99** [librenms/librenms#4701]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [ Y] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

Version info:
Commit SHA: 0856c5675e0b8ecf17b1fcc99df0d685fc3d92a9
[WARN]    Your local git contains modified files, this could prevent automatic updates.
Modified files:
    alerts.php
DB Schema: 140
PHP: 5.5.9-1ubuntu4.16
MySQL: 5.5.49-0ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

I think it was @laf that already patched this. My "validate.php" output above shows the alerts.php being modified because of the patch. 

The patch was for a Recovery email for a Service to include a way to spit out the Hostname (or was it just the state.. I am not 100% sure). Attached is the patch applied to alerts.php.  Have been running this alerts.php for at least a week.. Thanks!
[LibreNMS-alerts-patch.txt](https://github.com/librenms/librenms/files/505460/LibreNMS-alerts-patch.txt)

**Comment by ipguru99** [comment]
Thanks @laf!

Because my customer is running with that patched alerts.php, I tell them to do this:

;cd /opt/librenms
;git checkout HEAD alerts.php && chown -R librenms:librenms /opt/librenms
;git pull
# 
# diff alerts.php /root/alerts-patched.php
#
;git apply < patch1.txt
# Watch for the diff to be null 
# when it is, you don't need to run this anymore 

I just did this and the patch still isn't in there.. or am I just goofy and not understanding that it won't be in there yet? Thanks again for all of this work.. best NMS I have used in a long time!

**Comment by laf** [comment]
It's not been merged yet so you'll need to keep that patch in place until it is

**Comment by ipguru99** [comment]
Excellent.. that's what I was thinking.   Thanks again!
