### ISSUE TITLE
discovery-arp module not working with ASR 9010

### ISSUE THREAD

**Issue by jmoore2016** [librenms/librenms#4709]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.
# 

LibreNMS Version: b0ffbe331392fe7842d2eced35c75615c490e1fc
DB Schema: 141
PHP: 5.6.24-0+deb8u1
MySQL: 5.5.50-0+deb8u1
RRDTool: 1.4.8
# SNMP: NET-SNMP 5.7.2.1

I have ran discovery.php for the arp-table module and the discovery-arp module. It seems that arp-table module is finding the arp tables but they are not being stored in SQL.

I was asked by f0o on IRC to run the following to patch an issue with arp-table OID:

> [14:17] -GH-LibreNMS:##librenms- [librenms] f0o opened pull request #4707: fix: arp-table discovery of iosxr (master...f0o-arp-discovery-iosxr) https://git.io/vPY7D
> [14:17] @f0o jmoore: would you mind running `git remote update && git checkout origin/f0o-arp-discovery-iosxr` and then run the discovery.php again?

See .rar archive of the snmpwalk I was asked to open this issue up with:
[http://jcm.me/owncloud/index.php/s/KXn03AWPXTS9601](http://jcm.me/owncloud/index.php/s/KXn03AWPXTS9601)

Can someone take a look and let me know how I can get ARP discovery working?

**Comment by laf** [comment]
Can you provide this in tar, tgz or even zip format? rar is just a pain :(

**Comment by jmoore2016** [comment]
[http://jcm.me/owncloud/index.php/s/Lshkw1mQ8tshrIh](http://jcm.me/owncloud/index.php/s/Lshkw1mQ8tshrIh )is the link to the ZIP.

**Comment by worton** [comment]
Looks to me same thing as is happening in https://github.com/librenms/librenms/issues/4559#issuecomment-252343837

**Comment by laf** [comment]
Link is not showing :(

**Comment by laf** [comment]
Arp discovery has been refactored since this post so try again, however closing as no further info provided.
