### ISSUE TITLE
Empty multi-level drop down in Devices navbar menu 

### ISSUE THREAD

**Issue by frdmn** [librenms/librenms#4713]
> Please read this information carefully.

- [X] Is your install up to date?
- [X] Please include all of the information between the `====================================` section of `./validate.php`:
    - Version `638f610 - Tue Oct 04 2016 09:27:46 GMT+0200`
    - DB Schema `#141`
    - Apache `nginx/1.4.6`
    - PHP `5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1`
    - MySQL `5.6.32-78.1`
    - RRDtool `1.4.7`
- [X] Please provide as much detail as possible:
    ![](https://cloud.githubusercontent.com/assets/944459/19069511/94084f98-8a27-11e6-9e78-ab2dcc9cb678.gif)

---

When you start with a clean installation and no devices, the second level drop down menus are empty but still appear. 

I think it would be visually more appealing to the users if LibeNMS hides the second level completely when there are no devices yet.

Let me know if you need further details

**Comment by f0o** [comment]
:+1:
