### ISSUE TITLE
Feature Request: Display hostname instead of ip addresses when force_ip_to_sysname is enabled

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#4715]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

There are various places in the GUI where I think displaying hostnames or sysnames instead of ip addresses would come in handy. Like when searching for an ip address as shown below, one might want to zoom in on a particular device whilst doing the search, but it not that easy remembering the ip addresses of all the devices particularly when you many on your install. The second scenario was when trying to edit User Permissions, being able to assign by sysname would be great as I have `$config['force_ip_to_sysname']    = true;` in my config file.

![snap6](https://cloud.githubusercontent.com/assets/16717388/19071978/10f5c61a-8a33-11e6-8f4c-adedd610a985.png)
![snap3](https://cloud.githubusercontent.com/assets/16717388/19071983/1b4b57e2-8a33-11e6-85f1-39f55a21af20.png)
![snap4](https://cloud.githubusercontent.com/assets/16717388/19071989/20144e0a-8a33-11e6-84db-3ca17f1220c0.png)

**Comment by laf** [comment]
I'm confused by this, force_ip_to_sysname (whilst a confusing name) basically converts something to sysName, we only use that for hostname. So any device you add with a fqdn will just display that, if it's added by IP then we switch to use sysName instead of this flag is enabled.

So the title for this is confusing as we will never use hostname instead of IP as they are both the same and depend on how you add the device.

Do you mean that you have some areas of the web interface not honouring that feature?

**Comment by breeman1** [comment]
So most of our devices were added by ip and when we turned on the force_ip_to_sysname feature the ip were converted into hostnames in some areas of the GUI. Areas like the Availability-Map work as expected however as I showed using arrows in my previous post some areas of the GUI still diplay devices using ip addresses, the exception being only true if the devices were added bu hostname to begin with. I would have thought all areas where the device are listed should use the functionality if enabled of course. As an example, when searching for IPv4 addresses, in the pull-down menu in the top left hand side All devices display as ip addresses except those which were added by their respective hostnames. Likewise in the Edit User Permissions screen.

**Comment by laf** [comment]
Can you provide areas that this still needs addressing in as some things have now been fixed.

**Comment by breeman1** [comment]
Hi @laf,

I am still experiencing this issue even on the latest code base;
![image](https://cloud.githubusercontent.com/assets/16717388/25703601/89c03432-30d6-11e7-9a62-ee98f392f66c.png)
**User Permissions screen**
![image](https://cloud.githubusercontent.com/assets/16717388/25703630/a2377980-30d6-11e7-8c93-711704007bb6.png)
**IP address search screen**
![image](https://cloud.githubusercontent.com/assets/16717388/25703668/c1df7b7a-30d6-11e7-8809-79fcb2d4d1b3.png)

**Comment by laf** [comment]
I realise it's still got issues, my question was for you to say which pages still have issues.

I've gone through and hopefully caught all the remainder - can you please test my linked pull request.

**Comment by breeman1** [comment]
It works @laf , well at least on the pages that I am aware of where it was not working. Thank you.
