### ISSUE TITLE
Feature request: Add ability to change name of a sensor belonging to a device

### ISSUE THREAD

**Issue by ThinkPadNL** [librenms/librenms#4722]
It would be great if i could change the name of a sensor belonging to a device.

For example my ESXi host has a few volumes, one of them is my SSD.
It is now called: "/vmfs/volumes/284820eca0830ffd08a" and i would like to change it to "256GB SSD" which is much more clear. For now it doesn't seems to be supported, as i was told on IRC.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
