### ISSUE TITLE
Problem gathering contacts for SMTP alert

### ISSUE THREAD

**Issue by d0teater** [librenms/librenms#4728]
# Summary

I've configured alerting with the mail transport via SMTP. The "test transport" button delivers a test message, but real alerts produce an error. _**Please let me know what other information I can provide.**_ 
# Error (from device event log)

> Could not issue critical alert for rule 'Test rule - my test rule' to transport 'mail' Error: You must provide at least one recipient email address.
# System info:

> LibreNMS Version: 12c4b8acb23b7346f2a5e9ab061f3f8970cbfc5e
> DB Schema: 141
> PHP: 7.0.8-0ubuntu0.16.04.3
> MySQL: 10.0.27-MariaDB-0ubuntu0.16.04.1
> RRDTool: 1.5.5
> SNMP: NET-SNMP 5.7.3
# Alerting Settings

http://i.imgur.com/Kkfuj8T.png
# alert.php output

> $ ./alerts.php -d
> DEBUG!
> Start: Wed, 05 Oct 2016 17:30:53 -0700
> RunFollowUp():
> SQL[SELECT alerts.device_id, alerts.rule_id, alerts.state FROM alerts WHERE alerts.state != 2 && alerts.state > 0 && alerts.open = 0]
> RunAlerts():
> SQL[SELECT alerts.device_id, alerts.rule_id, alerts.state FROM alerts WHERE alerts.state != 2 && alerts.open = 1]
> RunAcks():
> SQL[SELECT alerts.device_id, alerts.rule_id, alerts.state FROM alerts WHERE alerts.state = 2 && alerts.open = 1]
> SQL[SELECT alert_log.id,alert_log.rule_id,alert_log.device_id,alert_log.state,alert_log.details,alert_log.time_logged,alert_rules.rule,alert_rules.severity,alert_rules.extra,alert_rules.name FROM alert_log,alert_rules WHERE alert_log.rule_id = alert_rules.id && alert_log.device_id = '1' && alert_log.rule_id = '1' && alert_rules.disabled = 0 ORDER BY alert_log.id DESC LIMIT 1]
> SQL[SELECT `device_group_id` FROM `device_group_device` WHERE `device_id`='1']
> SQL[SELECT alert_rules.\* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '1' ) || alert_map.target = '1'  )]
> SQL[SELECT attrib_value FROM devices_attribs WHERE attrib_type = "disable_notify" && device_id = '1']
> SQL[SELECT hostname, sysName, location, purpose, notes, uptime FROM devices WHERE device_id = '1']
> SQL[SELECT `template`,`title`,`title_rec` FROM `alert_templates` JOIN `alert_template_map` ON `alert_template_map`.`alert_templates_id`=`alert_templates`.`id` WHERE `alert_template_map`.`alert_rule_id`='1']
> **Issuing Alert-UID #1/2: ; ; mail => ERROR: You must provide at least one recipient email address.**
> SQL[SELECT \* FROM `devices` WHERE `device_id` = '1']
> SQL[SELECT \* FROM `vrf_lite_cisco` WHERE `device_id` = '1']
> SQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`message`)  VALUES ('1','1','NULL','NULL',NOW(),'Could not issue critical alert for rule \'Test rule - my test rule\' to transport \'mail\' Error: You must provide at least one recipient email address.')]
> ; ; ; ; ; ; ; ;
> SQL[UPDATE `alerts` set `open` ='0' WHERE rule_id = '1' && device_id = '1']
> End  : Wed, 05 Oct 2016 17:30:53 -0700

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php`.
- [X] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [X] Please provide as much detail as possible.

**Comment by laf** [comment]
We've merged some more debug options for alerting in the webui. Go to the device -> click the menu for that device on the right and select capture -> alerts.

**Comment by d0teater** [comment]
Thanks! Here's the result of an alert capture

>Rule name: Test rule - my test rule
Alert rule: %devices.hostname = "foobar" 
Alert query: SELECT * FROM devices WHERE (devices.device_id = ?) && (devices.hostname = "foobar" )
Rule match: no match

>Found 1 contacts to send alerts to.
NOC<<admin@mydomain.com>>

>Found 1 transports to send alerts to.
Transport: mail`

**Comment by laf** [comment]
I expect you set a contact after the alert so turn on honour alert contact setting or create a new rule to test as at present that device isn't triggering an alert

**Comment by laf** [comment]
No further info provided
