### ISSUE TITLE
Feature Request - Billing Quota Options (Combined, In Only, Out Only)

### ISSUE THREAD

**Issue by MattComwire** [librenms/librenms#4730]
Billing should have Options on how to Quota Bill.
Combined (As it is currently), Inbound Only, Outbound Only.

Screenshot of section being talked about.

![billing_quota](https://cloud.githubusercontent.com/assets/22467593/19137455/8f21c2b2-8bbb-11e6-9ace-61594dfa5227.png)

**Comment by Rosiak** [comment]
Hi,

We are cleaning up the issues here on GitHub, all feature requests will be moved to:
https://community.librenms.org/c/feature-requests

Hence the closure of this issue.
