### ISSUE TITLE
Alert on aggregate CPU usage

### ISSUE THREAD

**Issue by jeroendevries** [librenms/librenms#4732]
I'm looking for a way to send an alert on aggregate CPU usage. We now have an alert configured on %processors.processor_usage, but we get lots of false alerts in our 4 core machine, because 1 core has high usage, where other have low usage at the mean time. So, I'd like to create an alert on average CPU usage across the 4 cores.
Is that possible, and how do I do that?  I've looked into making a custom macro for this, but I don't have a way there to sum the usages of the 4 cores there as far as I can see.

**Comment by laf** [comment]
This isn't possible at present I'm afraid.

**Comment by jeroendevries** [comment]
Ok, to bad, then we'll work around it. Thanks for the quick reply!

**Comment by mboharevic** [comment]
Hi,

Have you found any solution for aggregate cpu alert over snmp?

It might be possible with an agent or nagios nrpe plugin.
