### ISSUE TITLE
Add OS support for moxa

### ISSUE THREAD

**Issue by Zaxmy** [librenms/librenms#4733]
I am working on this, will add support so librenms  can detect NPort5610 family of serial console switches

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please provide as much detail as possible.

**Comment by laf** [comment]
Merged
