### ISSUE TITLE
Top Menu Alignment Issue

### ISSUE THREAD

**Issue by search4u2003** [librenms/librenms#4734]
Version info:
Commit SHA: 0856c5675e0b8ecf17b1fcc99df0d685fc3d92a9
[WARN]    Your local git branch is not master, this will prevent automatic updates.
DB Schema: 140
PHP: 7.0.11
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2

====================================
[OK]      Database connection successful

![libre_menu](https://cloud.githubusercontent.com/assets/18137450/19149980/3977f76a-8be2-11e6-9845-cdbdac124fca.gif)

Since the new update we have observed Top Menu Alignment issue as you can see in the above screenshot, dashboard menu is half visible, same is been observed in all pages of the librenms application.

Regards
Ashwin

**Comment by laf** [comment]
Update, this was fixed a couple of days ago.

**Comment by search4u2003** [comment]
I have ran the update several times but no success yet.

**Comment by laf** [comment]
Repost the output of validate.php - the version you posted earlier is 4 days old so was pre-fix.
