### ISSUE TITLE
Librenms haven't  ability to display the Graylog messages with timezone correction

### ISSUE THREAD

**Issue by andryukha** [librenms/librenms#4736]
Graylog integration is a great feature, but Graylog stores original messages with UTC timestamps. So now I see Event Log in GMT+3 format (as it defined in both php.ini) but Graylog messages in UTC as it transferred from graylog server.
Could you please add this feature to graylog integration in config.php as option
$config['graylog']['timezone']  = 'Europe/Moscow';
for example?

**Comment by laf** [comment]
We don't currently do any manipulation of timezone with the date / time we get from Graylog so we display it as it's sent to us.

Are you saying that your logs are UTC but you would like to view them in your local timezone? I don't see us being able to add one config option as what about people in different countries within one business?

**Comment by andryukha** [comment]
Hi Neil,
Of course i didn't mean that you should add timezone correction only for Moscow.
It's only the sample how it looks in my local configs.
I mean the the ability to change timezone worldwide.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-librenms-havent-ability-to-display-the-graylog-messages-with-timezone-correction/690

**Comment by laf** [comment]
Can you please test #7799
