### ISSUE TITLE
Lost BGP monitoring on Cisco ASR 1001's

### ISSUE THREAD

**Issue by networkprogrammer** [librenms/librenms#4747]
Our SNMP monitoring of ASR 1001's seemed to have stopped BGP information from being picked up. We stopped getting BGP information little after midnight. An alert for bgp session down was sent. 

LibreNMS seems to think that BGP is currently down. This however is not true when looking at the ASR itself.

**Comment by laf** [comment]
Please upgrade your install

**Comment by networkprogrammer** [comment]
I believe I am at the latest version.

Version	9298304 - Thu Oct 06 2016 14:21:20 GMT-0700
DB Schema	#142
Apache	nginx/1.10.0
PHP	7.0.8-0ubuntu0.16.04.3
MySQL	10.0.27-MariaDB-0ubuntu0.16.04.1
RRDtool	1.5.5

**Comment by networkprogrammer** [comment]
I take that back. Looks good now. Thanks!
