### ISSUE TITLE
Alert when multiple service errors occurred

### ISSUE THREAD

**Issue by FTBZ** [librenms/librenms#4761]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

LibreNMS Version: 1f0395df6ebb9b7fa8206e65ca55e9222ccd45f8
DB Schema: 142
PHP: 7.0.10
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2

<h2>Alert when multiple service errors occurred</h2>

I've setup some services to check with the nagios plugins (HTTP, SMTP, LDAPS). I added an alert rules to match these services errors, but I noticed an annoying thing. When a first service goes to an errored state and an altert is triggered, when a second service is errored the altert only includes the first service and ignores the second.

And same thing when two services have an error in the same time and the alert occurs including the two services, when one of the two services return an OK state, the alert continues to include the two services even if one is back to normal since many hours.

First service goes down:
![screen shot 2016-10-10 at 09 38 18](https://cloud.githubusercontent.com/assets/1927109/19229379/5896bb48-8ecd-11e6-93d1-93a567153310.png)

Alert is correct:
![screen shot 2016-10-10 at 09 41 38](https://cloud.githubusercontent.com/assets/1927109/19229445/d71dc592-8ecd-11e6-8cb9-02e1cc8193f1.png)

A second service goes down:
![screen shot 2016-10-10 at 09 43 48](https://cloud.githubusercontent.com/assets/1927109/19229465/0e8957ee-8ece-11e6-8b9f-05a19376c00c.png)

Alert only shows the first service and not the second:
![screen shot 2016-10-10 at 09 51 18](https://cloud.githubusercontent.com/assets/1927109/19229620/253e4994-8ecf-11e6-9927-59fb30844b9f.png)

I didn't noticed this issue before, but probably because only one service was down at the same time. Perhaps I didn't use it correctly? Need I to create one alert rule by service?

**Comment by laf** [comment]
@f0o any input to this. It doesn't appear as though the RunFollowUp() is doing anything here. I can create two service checks, clear out alerts and alert_log tables, fail one service run ./check-services.php, poller.php then alerts.php and get alerted. But if I fail a second service on the same device and re-run those it doesn't get 'worse'.

It's not running through RunFollowUp() as `SELECT alerts.device_id, alerts.rule_id, alerts.state FROM alerts WHERE alerts.state != 2 && alerts.state > 0 && alerts.open = 0` is empty for me.

**Comment by f0o** [comment]
I'll have a look over the week (famous last words ;)

**Comment by laf** [comment]
Can you re-test this as I think it was fixed.

**Comment by FTBZ** [comment]
Will try on the next monthly release. Thanks.

**Comment by FTBZ** [comment]
Tested in deep, and it's working fine! Alerts become worse or better and notifications are sent correctly.
