### ISSUE TITLE
Feature request: ability to set recurring maintenance windows (during backup hours for example)

### ISSUE THREAD

**Issue by flotpg** [librenms/librenms#4762]
It would help us a lot to set a daily/recurring maintenance window in LibreNMS. 
During the backup hours a few of our VMs are not accessible because of the snapshots that are taken. In this tim, for example from 00:00-01:00 AM i want to disable alerts (for all devices  if possible.)

If this is the wrong place for FR please let me know, thx.

**Comment by laf** [comment]
Duplicate #4480
