### ISSUE TITLE
New "pattern" -- (1.3.6.1.2.1.47.1.1.1.1.9) entPhysicalFirmwareRev

### ISSUE THREAD

**Issue by jmoore2016** [librenms/librenms#4763]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

I need to add an OID to be usable as a "Pattern:" in device groups and rules.
The OID is 1.3.6.1.2.1.47.1.1.1.1.9. This would function similar to how devices.version uses 1.3.6.1.2.1.47.1.1.1.1.10, this would be devices.firmware and would work in a like-manner. Is it possible for me to do this myself with an already documented method? I saw this: http://docs.librenms.org/Extensions/MIB-based-polling/#how-to-add-a-new-device-mib but it seems to be related to adding new mibs for graphing. I need to check the value, not graph the result.

**Comment by murrant** [comment]
This already exists: `entPhysical.entPhysicalFirmwareRev`.
