### ISSUE TITLE
Adding support for Samsung ML series printer

### ISSUE THREAD

**Issue by jquagga** [librenms/librenms#4767]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php`.

LibreNMS Version: ead6b5b8ac7b05f36780eb6727648dc69a5d6c4d
DB Schema: 142
PHP: 7.0.11
MySQL: 10.1.17-MariaDB
RRDTool: 1.5.6
SNMP: NET-SNMP 5.7.3

- [X] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)

http://pastebin.com/m0P8EFPZ - Discovery
http://pastebin.com/tub9nE8a - Poller
http://pastebin.com/T1RmZtHu - SNMPWALk

**Please note these are AFTER applying the diff attached below.**

- [X] Please provide as much detail as possible.

Good day LibreNMS folks,

I'm trying to add support for my Samsung ML-2850ND printer.  The first part of that I think I have working nicely.  
```diff
diff --git a/includes/discovery/os/samsungprinter.inc.php b/includes/discovery/os/samsungprinter.inc.php
index 4738f20..2ae610f 100644
--- a/includes/discovery/os/samsungprinter.inc.php
+++ b/includes/discovery/os/samsungprinter.inc.php
@@ -1,5 +1,5 @@
 <?php
 
-if (str_contains($sysDescr, array('Samsung CLX', 'Samsung SCX', 'Samsung C', 'Samsung S'))) {
+if (str_contains($sysDescr, array('Samsung CLX', 'Samsung SCX', 'Samsung C', 'Samsung S', 'Samsung ML'))) {
     $os = 'samsungprinter';
 }
```

So once that lands, the device switches from a Generic device to a Samsung Printer. I get the Serial Number and the model make and it identifies the device as a printer.  However the toner graphing does not work and if I look at the output from discover / poller, it doesn't look like it's getting any of the toner info.  I'm not sure why; the SNMPwalk shows the OIDs and the data there.  So that's the part that is still a mystery to me.  

I'd be happy to provide any other information needed to help get the toner graphing up and running and device support added.

**Comment by jquagga** [comment]
As requested by @laf, here's the discover / poller debug.  I ran the same commands listed in issue #3584

http://pastebin.com/qL7R7Ry4 - Discovery Debug
http://pastebin.com/YU4yQ4AX - Poller Debug

**Comment by crcro** [comment]
from the discovery debug there seems to be no toner information, do you have information about toners in printer webmenu?

**Comment by jquagga** [comment]
It's a monochrome printer and it does report the information via SNMP on the appropriate OIDs.  I just can't get it to respond to the snmpwalk the toner discovery function uses.  However:

I've been playing with it and I can get it to report a snmpwalk command if I don't specific a OID and grep for it or if I snmpwalk with the numerical OID:

/usr/bin/snmpwalk -v1 -c public -OsqnU -M /opt/librenms/mibs udp:scribe.internal:161 .1.3.6.1.2.1.43.12.1.1.2.1.1         .1.3.6.1.2.1.43.12.1.1.2.1.1 1

So something seems up with the mib.  Is it perhaps an issue that the mib is the SNMPv2-SMI but this printer uses SNMP v1?

**Comment by jquagga** [comment]
Ok, I've gotten it to work but I'm unsure how to resolve this in a fashion suitable for inclusion in LibreNMS.  

If I snmpwalk SNMPv2-SMI::mib-2.43.12.1.1.2.1, the printer returns nothing for that OID.  However if I add an index of .1 it responds nicely.  So snmpwalk SNMPv2-SMI::mib-2.43.12.1.1.2.1**.1** works great.  

This is what I changed in toner.inc.php but it's not suitable for everyone.

```diff
diff --git a/includes/discovery/toner.inc.php b/includes/discovery/toner.inc.php
index 049f81f..9581aa4 100644
--- a/includes/discovery/toner.inc.php
+++ b/includes/discovery/toner.inc.php
@@ -3,9 +3,9 @@
 $valid_toner = array();
 
 if ($device['os_group'] == 'printer') {
-    $oids = trim(snmp_walk($device, 'SNMPv2-SMI::mib-2.43.12.1.1.2.1 ', '-OsqnU'));
+    $oids = trim(snmp_walk($device, 'SNMPv2-SMI::mib-2.43.12.1.1.2.1.1 ', '-OsqnU'));
     if (!$oids) {
-        $oids = trim(snmp_walk($device, 'SNMPv2-SMI::mib-2.43.11.1.1.2.1 ', '-OsqnU'));
+        $oids = trim(snmp_walk($device, 'SNMPv2-SMI::mib-2.43.11.1.1.2.1.1 ', '-OsqnU'));
     }
 
     d_echo($oids . "\n");
```

**Comment by jquagga** [comment]
Actually would this work?  

The existing process isn't changed until you get through both passes of oid with nothing.  At that point, we try once more with an index of 1 for stupid printers like this one.

CC @laf since you helped me with this at the start of the day :-)

```diff
diff --git a/includes/discovery/toner.inc.php b/includes/discovery/toner.inc.php
index 049f81f..5b0ba64 100644
--- a/includes/discovery/toner.inc.php
+++ b/includes/discovery/toner.inc.php
@@ -7,6 +7,10 @@ if ($device['os_group'] == 'printer') {
     if (!$oids) {
         $oids = trim(snmp_walk($device, 'SNMPv2-SMI::mib-2.43.11.1.1.2.1 ', '-OsqnU'));
     }
+    // Try once more with an index of 1
+    if (!$oids) {
+        $oids = trim(snmp_walk($device, 'SNMPv2-SMI::mib-2.43.12.1.1.2.1.1 ', '-OsqnU'));
+    }
 
     d_echo($oids . "\n");
 ```

**Comment by crcro** [comment]
please set snmp to v2 and try again, submitted PR to support ML series

**Comment by jquagga** [comment]
Yep, I tried again with snmpv2 and still no luck without the addition of explicit check of .1 as explained in a prior post.  I even tried snmpv3 but the result is always the same (this is the v2c output but v1 and v3 are the same):

```
#### Load disco module toner ####
SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OsqnU -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-SMI::mib-2.43.12.1.1.2.1 ]
.*.*.* No Such Instance currently exists at this OID

SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OsqnU -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-SMI::mib-2.43.11.1.1.2.1 ]
.*.*.* No Such Instance currently exists at this OID

SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OsqnU -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-SMI::mib-2.43.12.1.1.2.1.1 ]
.*.*.*.1 1
```

Here you can see the first poller items return nothing; the addition of the .1 results in a result of 1.  After that everything pulls in fine.  I get the toner serial number and state / remaining toner.

**Comment by crcro** [comment]
there is something strange as i can see the SNMPv2-SMI::mib-2.43.12.1.1.2.1 returns and index of 1 and then it should get SNMPv2-SMI::mib-2.43.12.1.1.2.1.1 for the toner

**Comment by jquagga** [comment]
Yes, I don't know why it doesn't return data from SNMPv2-SMI::mib-2.43.12.1.1.2.1 either.  I'm willing to try any suggestions.  Explicitly pulling SNMPv2-SMI::mib-2.43.12.1.1.2.1.1 checks the box and makes things work.

**Comment by crcro** [comment]
there is any new firmware available for the printer? maybe it's something buggy with snmp implementation ... i pushed some code for it, but i find it dirty :) so a cleaner way would be if printer would response as supposed to snmp queries...

**Comment by jquagga** [comment]
Yeah, I thought of that as well and I did do a firmware update yesterday but it hasn't changed the behavior which is (I feel as well buggy).  The printer firmware (even updated) is 6 years old but the printer is working fine so, it keeps on going.    

If you don't want to commit the buggy extra code I understand that as well and can simply do without.  I can either keep my work around in the local base or just not track the printer via SNMP.  I mostly use LibreNMS for network information and adding the printer because I could.  I'm sure it'll always yell at me when the toner is getting low.

**Comment by jquagga** [comment]
I'm afraid toner reporting does not work on the code committed. My toner levels just dropped to 0%.

**Comment by jquagga** [comment]
@crcro @murrant It looks like there is a small typo on line 19 of toner.inc.php The oid should basically match the oid on line 43 only with an index set to one. I've corrected it on my local install and that's restored my toner reporting.

**Comment by murrant** [comment]
@jquagga Thanks for the report, I changed that.  But I'm still very curious.

What does `snmpwalk -v2c -c COMMUNITY HOSTNAME Printer-MIB::prtMarkerSuppliesLevel` give you on the Samsung ML?

**Comment by jquagga** [comment]
```
bes:~/working% snmpwalk -v2c -c public scribe.internal Printer-MIB::prtMarkerSuppliesLevel                                                                      Printer-MIB::prtMarkerSuppliesLevel.1.1 = INTEGER: 82                           
bes:~/working% snmpwalk -v2c -c public scribe.internal Printer-MIB::prtMarkerColorantMarkerIndex                                                                Printer-MIB::prtMarkerColorantMarkerIndex.1.1 = INTEGER: 1                      
bes:~/working% snmpwalk -v2c -c public scribe.internal Printer-MIB::prtMarkerSuppliesMarkerIndex                                                                Printer-MIB::prtMarkerSuppliesMarkerIndex.1.1 = INTEGER: 1
```

So ... with that output, I'm not sure why the original code wasn't working?

**Comment by murrant** [comment]
The original code queries those with a .1 appended.  Perhaps that is what the printer doesn't like.
