### ISSUE TITLE
Pulse icon is 200x200 instead of 32x32

### ISSUE THREAD

**Issue by jgilmour** [librenms/librenms#4776]
html/images/os/pulse.png is showing 200x200 instead of 32x32 like the other png's. This causes the pulse secure devices to look a bit odd when viewing all devices. 

![screen shot 2016-10-11 at 3 27 07 pm](https://cloud.githubusercontent.com/assets/440911/19285220/3d7b8230-8fc7-11e6-80dd-051d3a0bcb7d.png)

> .../html/images/os# file pulse.png
> pulse.png: PNG image data, 200 x 200, 8-bit/color RGB, non-interlaced

**Comment by jgilmour** [comment]
wow fixed 3 hours ago. well played, librenms, well played.

**Comment by laf** [comment]
Shouldn't have made it in in the first place - thanks for reporting :)
