### ISSUE TITLE
LANCOM AP leads to very big RRD data size

### ISSUE THREAD

**Issue by nextl00p** [librenms/librenms#4789]
The polled device is a LANCOM L-310agn Wireless AP. It creates very big data inside the rrd directory.

Here is the ouput of discovery.php in Debug-Mode: http://pastebin.com/caaq9maN It just got stuck after the last message.

Here is the content of the rrd directory of the device http://pastebin.com/RT1hX8rq

**Comment by murrant** [comment]
I'm not sure I understand why mib-polling is enabled for this device...

**Comment by nextl00p** [comment]
This device is not recognised by librenms

**Comment by laf** [comment]
Please post the output of:

`./validate.php`

Also:

`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .`

**Comment by nextl00p** [comment]
`./validate.php 
==========================================================
LibreNMS Version: 5569884f7f714bc6ff6131c55ea718fbd4e0cc1e
DB Schema: 145
PHP: 7.0.11
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2
==========================================================

[WARN]  Your install is out of date, last update: Sun, 16 Oct 2016 14:58:48 +0000
[OK]    Database connection successful
`
snmpbulkwalk results in a timeout
`Timeout: No Response from 10.155.53.42`

I can send the full output to you in a PM. Don't want to publish personal data.

**Comment by laf** [comment]
The snmpwalk, you need to set the correct community

**Comment by laf** [comment]
Is this the full output you sent? Have you tried setting `-t 600` for timeout?

**Comment by murrant** [comment]
Is this snmp v1? If so, you'll need to use just snmpwalk (not snmpbulkwalk)

**Comment by laf** [comment]
He's got some data out and emailed it but it's timing out.

**Comment by nextl00p** [comment]
No it's v2c. I use -t 600 now. It still hangs at the same location now already for half an hour.

Is the device faulty?

**Comment by laf** [comment]
Not necessarily.

If you can get us the output of:

```bash
snmpget -OUneb -v2c -c COMMUNITY HOSTNAME sysObjectID.0 sysName.0 sysDescr.0
```

We can then add basic detection and see if it still does the same thing.

**Comment by laf** [comment]
No further info provided

**Comment by nextl00p** [comment]
Our WiFI infrastructure consists only of Lancom APs. I think the issue was an outdated firmware. All APs which had this problematic behaviour run on an older version than the others. So I give you the snmpget output of an other AP which is also not recognised, but does not have this problematic behaviour.

`snmpget -OUneb -v2c -c public 10.xxx.xxx.xxx sysObjectID.0 sysName.0 sysDescr.0
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.2356.11.8.103
.1.3.6.1.2.1.1.5.0 = STRING: xxxan_A2_S_2gn5n
.1.3.6.1.2.1.1.1.0 = STRING: LANCOM L-322agn dual Wireless 9.20.0566 / 13.05.2016 4002568618100376
`
