### ISSUE TITLE
QNAP VioStor NVR 

### ISSUE THREAD

**Issue by toma2711** [librenms/librenms#4796]
Hi,

We are getting odd memory usages on two QNAP/VioStor NVR units we have in service. On LibreNMS, it shows a memory usage of 99% however when we look at the internal reporting tools built into the QNAP, it reports 3%. Could you please update the MIB for the QNAP NVR's.

We have 2 x Turbo NAS VS-12164UPro+ and both are doing the same thing. I can provide the MIB where necessary but cannot attach it here. You already have basic support for the QNAP NAS series but the NVR's are part of the enterprise security range so have a different OS.

Cheers,
Tom Atkinson

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by toma2711** [comment]
We have version 7ea7bd4 and auto-update enabled

**Comment by laf** [comment]
You've got a very old install, please update and test again.

**Comment by toma2711** [comment]
Hi, 

I have tried to update and it is refusing to update?

We get the following from executing validate.php:
[WARN] Your local git contains modified files, this could prevent automatic updates.
Modified files:
.gitignore
.scrutinizer.yml
.travis.yml
AUTHORS.md
README.md
addhost.php
adduser.php
alerts.php
billing-calculate.php
build-base.php
check-services.php
config.php.default
config_to_json.php
contrib/generate-iplist.php
cronic
daily.php
daily.sh
..... and it looks like every other file in the tree

However we have not modified any of the files in the system. Could you please advise?

Kind Regards

**Comment by crcro** [comment]
if you are pretty sure that you didn't change manually any file you could do a git reset --hard in /opt/librenms directory, after that ./validate.php (fix any error/warning you have there) and try ./daily.sh after that.

**Comment by toma2711** [comment]
Good Afternoon.

We ran the commands that you suggested and it is now staying up to date. Thank you for that. 

Could somebody please advise on the issue that this was raised about now? The issue is still concurring, and in fact is worse. I can no longer see hard drive temperatures or fan speeds. It also appears that the traffic graph is incorrect.

I have attached a screenshot of the devices overview screen.

Kind Regards,
Tom


![capture](https://cloud.githubusercontent.com/assets/22841709/19643886/9db35be2-99e4-11e6-82ab-e7052d9094fa.PNG)

**Comment by laf** [comment]
Please pastebin the outputs for:

```bash
./discovery.php -h HOSTNAME -d
./poller.php -h HOSTNAME -d -r -f
```

**Comment by toma2711** [comment]
@laf Is there a way I can send this by a private means? The output contains some sensitive information

**Comment by laf** [comment]
Anonymise the data and post it up.

**Comment by toma2711** [comment]
[poller-output.txt](https://github.com/librenms/librenms/files/557887/poller-output.txt)
[discovery-output.txt](https://github.com/librenms/librenms/files/557888/discovery-output.txt)

@laf Attached,

Cheers,
Tom

**Comment by laf** [comment]
We will need the output from: `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .`

**Comment by laf** [comment]
No further info provided so closing.
