### ISSUE TITLE
Plot Wireless Traffic (Single Plot)

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#4810]
Hi,

Sorry if this is a dumb question, but no luck finding it so far ... :(.

I have a few wireless routers, and would like to look at 2.4 GHz and 5.0 GHz traffic for all of them on one plot (to see the mix, and if I should move any of the routers). Does this capability exist already?

Thanks!

**Comment by laf** [comment]
I don't believe it does no - it might for ubnt stuff but I don't have any to test.

**Comment by arrmo** [comment]
Gotcha. Or perhaps another way to skin this ... can I somehow select a custom set of ports, just plot them against each other on a single (line) plot?

Thanks!

**Comment by laf** [comment]
You can with traffic graphs but I don't believe it's supported elsewhere at the moment.

**Comment by arrmo** [comment]
OK, thanks! Will play with it - trying to figure out how to get them on a single plot.

**Comment by murrant** [comment]
@arrmo Can you just look at the traffic on the ethernet?  or do you want separate lines for each band on the same graph?

**Comment by arrmo** [comment]
Would like to compare them, if possible - to be able to understand the traffic allocation between bands, and locations. Make sense?

Thanks!

**Comment by laf** [comment]
@murrant is this something that is covered in your new code?

**Comment by murrant** [comment]
We don't have any rate sensors yet.  They likely would need a counter type rrd.

**Comment by laf** [comment]
https://github.com/librenms/librenms/blob/master/LibreNMS/Device/WirelessSensor.php#L160

Is that not rate in this sense?

**Comment by laf** [comment]
@murrant bump

**Comment by murrant** [comment]
@laf it is, but it is wrong and also, no devices use that sensor.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/improve-wireless-collection-and-graphing-code/453/47
