### ISSUE TITLE
Smokeping integration, graph error, permission denied

### ISSUE THREAD

**Issue by tslytsly** [librenms/librenms#4814]
Hi All,

So far, very impressed with LibreNMS, installed from pre-built VM.
Most things are working fine.
I followed this info on installing and integrating SmokePing: [https://github.com/thepacmanfan/librenms/blob/master/doc/Extensions/Smokeping.md#install-and-integrate-smokeping-debianubuntu](url)
Smokeping is working, I can navigate to its webpage and see the graphs fine, LibreNMS has sent the device info to Smokeping and there is a Ping tab for each monitored device.
So the integration is also fine.

However, in the LibreNMS Ping tab all the graphs show errors. If I look at the RRD command output, the response is `ERROR: rrdcached: /var/lib/smokeping/network/10_10_10_2.rrd: Permission denied`
All the RRD files are owned by the Smokeping user and in /var/lib/smokeping.
I have CHMOD 777 -R the whole dir and still get the error.

Any help would be great.

Thanks

**P.S. validate info:**

LibreNMS Version: 5569884f7f714bc6ff6131c55ea718fbd4e0cc1e
DB Schema: 145
PHP: 7.0.8-0ubuntu0.16.04.3
MySQL: 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP 5.7.3

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by laf** [comment]
It's an rrdcached thing rather than LibreNMS. You need to set rrdcached up to be able to read the files in the other directory.

**Comment by tslytsly** [comment]
> @laf It's an rrdcached thing rather than LibreNMS. You need to set rrdcached up to be able to read the files in the other directory.

Thanks for the lightening fast response! :)
Any idea where I might find more info on how to do this? I'm only a beginner on rrdcached.

thanks

**Comment by laf** [comment]
I don't use it for more than normal graphs personally.

Have you checked the owner that rrdcached runs as has access to those files for smokeping? Maybe check the rrdcached logs

**Comment by tslytsly** [comment]
According to top rrdcached is running as root. (I didn't set this up, was already configured in the image I downloaded)
Also, I have set all the files in the smokeping dir as 777 so any user should be able to mess with them.
Can't see any errors in the rrdcached log.

**Comment by tslytsly** [comment]
In addition, are we sure this is an rrdcached problem?
The only reason that

**Comment by tslytsly** [comment]
oops, didn't mean to close it...

**Comment by laf** [comment]
I've got no further hints to fix it but `ERROR: rrdcached: /var/lib/smokeping/network/10_10_10_2.rrd: Permission denied` says it's rrdcached telling us there's an issue so it needs resolving there most likely.

**Comment by tslytsly** [comment]
@laf 
Thanks for you input so far, it is appreciated.
Could it not be the way LibreNMS is trying to call the info using rrdtool that is causing the issue?

If I copy the command from the web interface and paste it into an SSH terminal as the librenms user it doens't return an error, it returns a PNG file, which is what I think the web interface is expecting?

It only seems to return an error when the web-interface calls the command.

It would be helpful to know how LibreNMS is trying to get the info so I can try and replicate?

**Comment by laf** [comment]
The command it gives you in the webui is all it's trying to access (I assume it had --daemon on) so running it from webui to cli is no different except the user you've done it as.

**Comment by tslytsly** [comment]
Hmm... this is the command:
`rrdtool graph /tmp/bZgWqa8F9s9jeFfk.png -l 0 -r -E --start 1476614700 --end 1476701100 --width 1728 --height 316.66666666667 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal COMMENT:' RTT Loss SDev RTT\:SDev\l' DEF:median0=/var/lib/smokeping/network/10_10_10_2.rrd:median:AVERAGE CDEF:dm0=median0,UN,0,median0,IF DEF:loss0=/var/lib/smokeping/network/10_10_10_2.rrd:loss:AVERAGE CDEF:ploss0=loss0,20,/,100,* DEF:pin0p1=/var/lib/smokeping/network/10_10_10_2.rrd:ping1:AVERAGE CDEF:p0p1=pin0p1,UN,0,pin0p1,IF DEF:pin0p2=/var/lib/smokeping/network/10_10_10_2.rrd:ping2:AVERAGE CDEF:p0p2=pin0p2,UN,0,pin0p2,IF DEF:pin0p3=/var/lib/smokeping/network/10_10_10_2.rrd:ping3:AVERAGE CDEF:p0p3=pin0p3,UN,0,pin0p3,IF DEF:pin0p4=/var/lib/smokeping/network/10_10_10_2.rrd:ping4:AVERAGE CDEF:p0p4=pin0p4,UN,0,pin0p4,IF DEF:pin0p5=/var/lib/smokeping/network/10_10_10_2.rrd:ping5:AVERAGE CDEF:p0p5=pin0p5,UN,0,pin0p5,IF DEF:pin0p6=/var/lib/smokeping/network/10_10_10_2.rrd:ping6:AVERAGE CDEF:p0p6=pin0p6,UN,0,pin0p6,IF DEF:pin0p7=/var/lib/smokeping/network/10_10_10_2.rrd:ping7:AVERAGE CDEF:p0p7=pin0p7,UN,0,pin0p7,IF DEF:pin0p8=/var/lib/smokeping/network/10_10_10_2.rrd:ping8:AVERAGE CDEF:p0p8=pin0p8,UN,0,pin0p8,IF DEF:pin0p9=/var/lib/smokeping/network/10_10_10_2.rrd:ping9:AVERAGE CDEF:p0p9=pin0p9,UN,0,pin0p9,IF DEF:pin0p10=/var/lib/smokeping/network/10_10_10_2.rrd:ping10:AVERAGE CDEF:p0p10=pin0p10,UN,0,pin0p10,IF DEF:pin0p11=/var/lib/smokeping/network/10_10_10_2.rrd:ping11:AVERAGE CDEF:p0p11=pin0p11,UN,0,pin0p11,IF DEF:pin0p12=/var/lib/smokeping/network/10_10_10_2.rrd:ping12:AVERAGE CDEF:p0p12=pin0p12,UN,0,pin0p12,IF DEF:pin0p13=/var/lib/smokeping/network/10_10_10_2.rrd:ping13:AVERAGE CDEF:p0p13=pin0p13,UN,0,pin0p13,IF DEF:pin0p14=/var/lib/smokeping/network/10_10_10_2.rrd:ping14:AVERAGE CDEF:p0p14=pin0p14,UN,0,pin0p14,IF DEF:pin0p15=/var/lib/smokeping/network/10_10_10_2.rrd:ping15:AVERAGE CDEF:p0p15=pin0p15,UN,0,pin0p15,IF DEF:pin0p16=/var/lib/smokeping/network/10_10_10_2.rrd:ping16:AVERAGE CDEF:p0p16=pin0p16,UN,0,pin0p16,IF DEF:pin0p17=/var/lib/smokeping/network/10_10_10_2.rrd:ping17:AVERAGE CDEF:p0p17=pin0p17,UN,0,pin0p17,IF DEF:pin0p18=/var/lib/smokeping/network/10_10_10_2.rrd:ping18:AVERAGE CDEF:p0p18=pin0p18,UN,0,pin0p18,IF DEF:pin0p19=/var/lib/smokeping/network/10_10_10_2.rrd:ping19:AVERAGE CDEF:p0p19=pin0p19,UN,0,pin0p19,IF DEF:pin0p20=/var/lib/smokeping/network/10_10_10_2.rrd:ping20:AVERAGE CDEF:p0p20=pin0p20,UN,0,pin0p20,IF CDEF:pings0=20,p0p1,UN,p0p2,UN,+,p0p3,UN,+,p0p4,UN,+,p0p5,UN,+,p0p6,UN,+,p0p7,UN,+,p0p8,UN,+,p0p9,UN,+,p0p10,UN,+,p0p11,UN,+,p0p12,UN,+,p0p13,UN,+,p0p14,UN,+,p0p15,UN,+,p0p16,UN,+,p0p17,UN,+,p0p18,UN,+,p0p19,UN,+,p0p20,UN,+,- CDEF:m0=p0p1,p0p2,+,p0p3,+,p0p4,+,p0p5,+,p0p6,+,p0p7,+,p0p8,+,p0p9,+,p0p10,+,p0p11,+,p0p12,+,p0p13,+,p0p14,+,p0p15,+,p0p16,+,p0p17,+,p0p18,+,p0p19,+,p0p20,+,pings0,/ CDEF:sdev0=p0p1,m0,-,DUP,*,p0p2,m0,-,DUP,*,+,p0p3,m0,-,DUP,*,+,p0p4,m0,-,DUP,*,+,p0p5,m0,-,DUP,*,+,p0p6,m0,-,DUP,*,+,p0p7,m0,-,DUP,*,+,p0p8,m0,-,DUP,*,+,p0p9,m0,-,DUP,*,+,p0p10,m0,-,DUP,*,+,p0p11,m0,-,DUP,*,+,p0p12,m0,-,DUP,*,+,p0p13,m0,-,DUP,*,+,p0p14,m0,-,DUP,*,+,p0p15,m0,-,DUP,*,+,p0p16,m0,-,DUP,*,+,p0p17,m0,-,DUP,*,+,p0p18,m0,-,DUP,*,+,p0p19,m0,-,DUP,*,+,p0p20,m0,-,DUP,*,+,pings0,/,SQRT CDEF:dmlow0=dm0,sdev0,2,/,- CDEF:s2d0=sdev0 CDEF:ploss_all=0,ploss0,+,1,/ CDEF:dm_all=0,dm0,+,1,/ CDEF:sd_all=0,s2d0,+,1,/ CDEF:dmlow_all=dm_all,sd_all,2,/,- AREA:dmlow_all AREA:sd_all#AAAAAA::STACK LINE1:dm_all#CC0000:'Average ' VDEF:avmed=dm_all,AVERAGE VDEF:avsd=sd_all,AVERAGE CDEF:msr=dm_all,POP,avmed,avsd,/ VDEF:avmsr=msr,AVERAGE GPRINT:avmed:'%5.1lf%ss' GPRINT:ploss_all:AVERAGE:'%5.1lf%%' GPRINT:avsd:'%5.1lf%Ss' GPRINT:avmsr:'%5.1lf%s\l'`

Returns the usual error in the Ping tab, pasted into terminal returns a graph picture.

What user does libreNMS execute this command as please?

**Comment by laf** [comment]
That doesn't look like it's got the rrdcached daemon command. It needs --daemon YOURCONFIG appended.

The web server user will run the command so that depends on your distro + web server of choice.

**Comment by tslytsly** [comment]
OK. do you know where I can edit the this? I assume it is a config file and/or option in the config.php?

**Comment by laf** [comment]
If you've enabled rrdcached then on the end of the rrdtool command you just need --daemon YOURCONFIG so --daemon 192.168.0.1:42217 or whatever you specified in config.php

**Comment by tslytsly** [comment]
Thanks for the extra info.

It seems that rrdcached came pre-installed as a socket and I haev to use this: `--daemon unix:/var/run/rrdcached.sock`
I now get the same error I see in the web ui.

I have added the librenms user to the smokeping group, I have chmod the smokeping rrd files to 777, I have tried executing the command as root and everytime I get the same error: `ERROR: rrdcached: /var/lib/smokeping/network/10_10_10_2.rrd: Permission denied`

I'm really not sure what else to do now. it's obviously a permissions issue, but what permissions and where I can work out.

**Comment by tslytsly** [comment]
Still no joy with this, I messed about with the rrdcached settings and broke all the other graphs :)
I have put all that back and still cannot get the smokeping graphs to work.

**Comment by Rosiak** [comment]
Did you get around this one and can we close or?

**Comment by tslytsly** [comment]
Hi @Rosiak ,

No, smokeping is working and I can navigate to the graphs in the smokeping page.
But from within LibreNMS I still get the error.

**Comment by eberlut** [comment]
For anyone stumbling upon the same error (as I did), it seems to stem from the fact that all documentation recommend to use -B which restrict rrdcached to a single base directory (typically /opt/librenms/rrd) while with the Smokeping integration you're trying to also read from e.g. /opt/smokeping/data/.

After removing the -B switch from rrdcached invokation, it works fine. Having all your rrds in the same base directory should also work around this.

Indeed it is not a bug in LibreNMS but documentation could be updated to make it clearer due to the specific setup LibreNMS encourage.

**Comment by tslytsly** [comment]
Thanks @eberlut that did it! 👍 
Appreciate everyone's comments, I understand it's not a LibreNMS bug as such, but agree with eberlut that the docs could have been better.
Closing

**Comment by Rosiak** [comment]
Feel free to contribute to the docs @eberlut @tslytsly so you can help people in the future.

**Comment by tslytsly** [comment]
Will do @Rosiak
