### ISSUE TITLE
Missing config lines in the documentation for manual install

### ISSUE THREAD

**Issue by EvilIgor** [librenms/librenms#4815]
Hi
There is missing some lines in the documentation for manual install

`firewall-cmd --permanent --zone=public --add-service=http`
`systemctl restart firewalld.service`

Before 
[http://docs.librenms.org/Installation/Installation-CentOS-7-Apache/#web-installer](url)

/Chris

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by laf** [comment]
I wouldn't say it's missing it personally, we can't be expected to give the options for varying systems outside of what we provide. firewalld, iptables, etc.

Maybe some info on what ports to open on a firewall. Feel free to submit a pull request.

**Comment by laf** [comment]
No respond provided.
