### ISSUE TITLE
apc ups extend missing?

### ISSUE THREAD

**Issue by mzac** [librenms/librenms#4818]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ X] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

LibreNMS Version: 3bee2811b86672002483840113c4be518099e522
DB Schema: 145
PHP: 5.6.26-0+deb8u1
MySQL: 5.5.52-0+deb8u1
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2.1

In issue #4402 APC UPS via usb was added, however when I go to edit a host, choose the applications tab I do not see the option for 'UPS-apcups' I only see the 'UPS-nut'

Is something missing? Am I missing something?

I added the snmp extend line in my snmpd.conf

**Comment by laf** [comment]
#4402 mentions that apc-nut is the script to go with this - have you tried it?

**Comment by Compizfox** [comment]
@laf Does that mean I can use the `apc-nut` script for monitoring `apcupsd`? I don't use `nut`.

I have exactly the same problem. [The documentation](http://docs.librenms.org/Extensions/Applications/#ups-apcups) says that I need to check/enable the `ups-apcups` application in the web interface, but it is simply not there.

**Comment by laf** [comment]
Pass, I don't use the applications support or any APC/UPS polling.

**Comment by laf** [comment]
Closing this though as no response from the original author

**Comment by Mdleal** [comment]
Should I create a new ticket? I am having the same issue and after comparing the NUT UPS application it is missing the polling file as well.  The application does not looking complete.

**Comment by laf** [comment]
Feel free
