### ISSUE TITLE
IRC Bot not working.

### ISSUE THREAD

**Issue by basn** [librenms/librenms#4822]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [ X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ X] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

==========================================================
LibreNMS Version: 7833c286ffc468b55657b42f32b5f4899ce18714
DB Schema: 145
PHP: 7.0.8-0ubuntu0.16.04.3
MySQL: 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP 5.7.3
==========================================================

IRCBot not showing anything, it starts you can authenticate but it does not work.

<@x> .auth freber
< librenms> Token sent!
<@x> .auth ID
<@x> .status devices
< librenms> Devices:  ( up,  down,  ignored,  disabled)
<@x> .device device port
< librenms> Error: Permission denied.

it does not show anything special when i run debug either.

To test load an ircbot and test should not work out of the box.

**Comment by laf** [comment]
Do you have the patch I sent you on irc?

**Comment by basn** [comment]
Sorry, i seem to misplaced it somewhere...
