### ISSUE TITLE
Missing ppp interfaces RouterOS

### ISSUE THREAD

**Issue by tslytsly** [librenms/librenms#4829]
Hi,

We have 70+ Mikrotik RouterOS devices to monitor, mostly RB2011s.
Most of these connect to the internet using PPPoE, so monitoring this interface is very important.

I've noticed that only one is correctly showing in the ports tab, on a CCR1009 router.
All the rest don't show up.
As an example, if I snmp walk one router's if table (.1.3.6.1.2.1.2.2) I can see all 13 interfaces in my MIB browser, including the PPPoE interface which is number 13.
I can also see all the data about it, status, speed, mtu, etc.

However the same device in librenms shows only 12 interfaces, the 11 physical ports and the bridge.

Any ideas why this might be happening? 

Thanks
Tom

EDIT to add LibreNMS info:
==========================================================
LibreNMS Version: 5569884f7f714bc6ff6131c55ea718fbd4e0cc1e
DB Schema: 145
PHP: 7.0.8-0ubuntu0.16.04.3
MySQL: 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP 5.7.3
==========================================================

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by geordish** [comment]
PPP interfaces by default are ignored.

If you want to add them in, try adding the following to your config.php
```php
unset($config['device_traffic_iftype']);
$config['device_traffic_iftype'][] = '/loopback/';
$config['device_traffic_iftype'][] = '/tunnel/';
$config['device_traffic_iftype'][] = '/virtual/';
$config['device_traffic_iftype'][] = '/mpls/';
$config['device_traffic_iftype'][] = '/ieee8023adLag/';
$config['device_traffic_iftype'][] = '/l2vlan/';
```

**Comment by tslytsly** [comment]
Ah, thanks for the link, now I understand what those options do.

It's not that the ppp interface is not being included in the overall traffic graph, it's not in the device's port list _at all_.

It's like LibreNMS doesn't see it when it scans the device, although in my MIB browser it is in the if table.

Any ideas on why this interface isn't showing in the ports tab?

**Comment by laf** [comment]
```php
unset($config['bad_if']);
$config['bad_if'][] = 'voip-null';
$config['bad_if'][] = 'virtual-';
$config['bad_if'][] = 'unrouted';
$config['bad_if'][] = 'eobc';
$config['bad_if'][] = 'lp0';
$config['bad_if'][] = '-atm';
$config['bad_if'][] = 'faith0';
$config['bad_if'][] = 'container';
$config['bad_if'][] = 'async';
$config['bad_if'][] = 'plip';
$config['bad_if'][] = '-physical';
$config['bad_if'][] = 'container';
$config['bad_if'][] = 'unrouted';
$config['bad_if'][] = 'bluetooth';
$config['bad_if'][] = 'isatap';
$config['bad_if'][] = 'ras';
$config['bad_if'][] = 'qos';
$config['bad_if'][] = 'span rp';
$config['bad_if'][] = 'span sp';
$config['bad_if'][] = 'sslvpn';
```

**Comment by tslytsly** [comment]
Thanks @laf that was spot on.
Just so I understand what this bit of config does... There are, by default, a set of interface types that are ignored by LibreNMS.
By adding `unset($config['bad_if']);` I am telling the server to ignore the default settings and use whatever I put in config.php.
By then listing everything already in the default except `pppoe-` I'm effectively just enabling PPPoE type interfaces.
Thanks for the help.

**Comment by laf** [comment]
Correct. It's a hack but we have no other way at the moment :(

**Comment by tslytsly** [comment]
hey, it works!
Just for the record I am pleasantly surprised with how much of LibreNMS "just works".
For free open source it's pretty good. 👍 @laf
