### ISSUE TITLE
Weird 20Gbit graphs on a 1Gbit interface

### ISSUE THREAD

**Issue by huegelc** [librenms/librenms#4830]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

Hi,

LibreNMS Version: fb677beb721ae06dbabe79e0485ffc331079f41e
DB Schema: 144
PHP: 7.0.8-0ubuntu0.16.04.3
MySQL: 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP 5.7.3

I´ve noticed some strange graph pikes on a 1Gbit interface reaching out to almost 20Gbit (see screenshot)
The device is an EX2200 Juniper Switch.
<img width="1887" alt="librenms firefox today at 16 21 27" src="https://cloud.githubusercontent.com/assets/6955465/19522857/e9c72010-9618-11e6-9eee-2bed7645a0e3.png">

The port belongs to a aggregated interface (4Gbit) 
<img width="1834" alt="librenms firefox today at 16 32 25" src="https://cloud.githubusercontent.com/assets/6955465/19523093/c8ccb7a2-9619-11e6-85c3-f01a63681520.png">

Any hints how to fix this weird graphs? Thank you.

**Comment by laf** [comment]
http://docs.librenms.org/Support/FAQ/#faq15

http://docs.librenms.org/Extensions/RRDTune/

If you still have issues please comment back and we will re-open
