### ISSUE TITLE
Some rrd files not owned by librenms

### ISSUE THREAD

**Issue by tslytsly** [librenms/librenms#4836]
Every time I run `./vaildate.php` i get this error:
` We have found some files that are owned by a different user than librenms, this will stop you updating automatically and / or rrd files being updated causing graphs to fail:`

when I look, the odd rrd is owned by root.
I run the suggested `chown -R librenms:librenms /opt/librenms  ` and all is well.

but it keeps happening, any thoughts as to why?

Thanks

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by laf** [comment]
Basically don't run any commands in the librenms as root, run them all as librenms user.

**Comment by laf** [comment]
I'd highly recommend questions like this are asked on our community site (https://community.librenms.org) or IRC.

**Comment by tslytsly** [comment]
Righto thanks. 👍
