### ISSUE TITLE
Add 'over' graphs to SAF device dashboard

### ISSUE THREAD

**Issue by barryodonovan** [librenms/librenms#4839]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

I am proposing to add the device_ping_perf and device_Rx_Level graphs as 'over' (don't know better descriptive name) graphs to the dashboard page of SAF Technica devices for quick appraisal.

**Comment by laf** [comment]
Merged
