### ISSUE TITLE
[Feature Request/Enhancement] Billing email reports

### ISSUE THREAD

**Issue by BenRoeves** [librenms/librenms#4849]
It would be very useful if the monthly generated bills could be emailed out as reports. Or even as a single summary if easier? Is this something easy to add?
Alternative could also be an export to pdf/csv?

Cheers,
Ben

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-billing-email-reports/688
