### ISSUE TITLE
Add support for Perle IOLAN SCS Console Server

### ISSUE THREAD

**Issue by ke-mccormick** [librenms/librenms#4851]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by laf** [comment]
Please complete the information asked for above - DO NOT DELETE IT.

**Comment by ke-mccormick** [comment]
And back to the original question....

Currently comes up as Generic and unknown vendor.

https://www.perle.com/products/iolan-scs-terminal-server.shtml

Here is a link to the SNMP MIB.

https://www.perle.com/downloads/software/iolan/perle-sds.mib

**Comment by laf** [comment]
Would you like us to add a new device?

**Comment by ke-mccormick** [comment]
Yes please.

**Comment by laf** [comment]
Then please read the info at the top and follow it.

**Comment by laf** [comment]
When you have the information we need please open a new issue.
