### ISSUE TITLE
Do not show (red) alert notification if alerts were muted

### ISSUE THREAD

**Issue by huegelc** [librenms/librenms#4854]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.
# 

LibreNMS Version: c182cb07287bacbe22c3c4114aa6ed3e8c197b6c
DB Schema: 148
PHP: 7.0.8-0ubuntu0.16.04.3
MySQL: 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP 5.7.3
# 

[OK]    Database connection successful

If there are only muted alerts, it does not make sense to display the red status in the navbar.

**Comment by laf** [comment]
Unfortunately the way things works means we can't do that. We limit the results of the alerts by 1 and then set it to show as failed if the alerts are muted or alerting as can't then check if all alerts are muted or not.

Other than retrieving the data in the webui for all alerts for that rule and then doing checks I don't see a way around it. Happy for someone else to check though.

**Comment by laf** [comment]
Closing, don't think this is fixable as is.
