### ISSUE TITLE
World Map Request

### ISSUE THREAD

**Issue by TyShawn76** [librenms/librenms#4856]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [Y ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
  LibreNMS Version: c182cb07287bacbe22c3c4114aa6ed3e8c197b6c
  DB Schema: 148
  PHP: 5.6.26-0+deb8u1
  MySQL: 5.5.52-0+deb8u1
  RRDTool: 1.4.8
  SNMP: NET-SNMP 5.7.2.1
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.
  On the world map it would be great if the map would try to auto center to the most center area of all locations. Currently I have sites in two cities in my state, and my map centers on my city and not the center most area of the state causing me to have to move the map constanly to the the other locations. It would be great if the map would auto zoom so it would give you the best view possible.

**Comment by laf** [comment]
You should be able to do that by setting the lat/lng coords:

http://docs.librenms.org/Extensions/Globe-Frontpage/#world-map

**Comment by TyShawn76** [comment]
Correct I can the request was for automation at this point.

**Comment by adammmmm** [comment]
Agree! I have my map to only show "down" devices, would be great if the map was  zoomed in on them when they occurred. And take the initial lat/lng coords by default if no host is visible.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-world-map-request-auto-center/687
