### ISSUE TITLE
after daily.sh run still out of date

### ISSUE THREAD

**Issue by huegelc** [librenms/librenms#4862]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

``` 
root@librenms:~# ./validate.php
==========================================================
LibreNMS Version: bc7b5d7e51de49dc2fd2cd55d0c0f99bb52fb609
DB Schema: 148
PHP: 7.0.8-0ubuntu0.16.04.3
MySQL: 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP 5.7.3
==========================================================

[WARN]  Your install is out of date, last update: Mon, 24 Oct 2016 08:48:13 +0000
[OK]    Database connection successful
root@librenms:~# exit
exit
librenms@librenms:~$ ./daily.sh
Updating to latest codebase                        OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
librenms@librenms:~$ sudo -s
root@librenms:~# ./validate.php
==========================================================
LibreNMS Version: bc7b5d7e51de49dc2fd2cd55d0c0f99bb52fb609
DB Schema: 148
PHP: 7.0.8-0ubuntu0.16.04.3
MySQL: 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP 5.7.3
==========================================================

[WARN]  Your install is out of date, last update: Mon, 24 Oct 2016 08:48:13 +0000
[OK]    Database connection successful
```

Somethings wrong but can´t find the source of the issue.

**Comment by laf** [comment]
That commit isn't one of ours so you've either switched to using your own branch or have switched to someone else's.

Depending on your setup running `git checkout master` will get you back.

**Comment by huegelc** [comment]
I´ve rolled back to a earlier release. Please bare with me but I´m new to git stuff. I needed to change some html/css files:
```
Modified files:
    html/css/bootstrap.min.css
    html/css/light.css
    html/css/styles.css
    html/images/librenms_logo_light.png
 ```

How can I use the daily updates but keep the changes I´ve made? Thank you

**Comment by laf** [comment]
You can't. If our updates don't change those file then it will update. As soon as we do though updates will stop. You'll need to handle this yourself by possibly maintaining your own branch but it won't be automatic

**Comment by huegelc** [comment]
OK, thank you. Wouldn´t be easier to have a template dir which can be ignored in git. Right now it´s not possible to have custome themes and use daily updates, right?

**Comment by laf** [comment]
Only in the way I've described above. Feel free to create an issue with that feature request.
