### ISSUE TITLE
Top Menu Alignment Issue

### ISSUE THREAD

**Issue by search4u2003** [librenms/librenms#4867]
[root@librenms librenms]# ./validate.php
==========================================================
LibreNMS Version: 7ca80410d56d519d1353aae107bee715962ba46f
DB Schema: 144
PHP: 7.0.11
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful

![libre_menu](https://cloud.githubusercontent.com/assets/18137450/19149980/3977f76a-8be2-11e6-9845-cdbdac124fca.gif)

Since the new update we have observed Top Menu Alignment issue as you can see in the above screenshot, dashboard menu is half visible, same is been observed in all pages of the librenms application.

As suggested in the last post by Laf I did performed a update but it dint help me, later I visited http://webchat.freenode.net/ where I was suggested to take the backup of rrd and log file and delete the /opt/librenms and Clone repo, it did succeeded but once the daily.sh cron job ran, again the problem occurred.

Regards
Vicky

**Comment by laf** [comment]
Are you using the monthly releases? If so this will be fixed this coming Sunday.

If not, then this is because your install hasn't updated still. If this is the case, run ./daily.sh and check what logs/daily.log says.

**Comment by search4u2003** [comment]
Hi Laf,

Below is the default cron job set in /etc/cron.d/librenms.

15   0    * * *   librenms    /opt/librenms/daily.sh >> /dev/null 2>&1

**Comment by laf** [comment]
No the cron is fine but your install isn't upto date. Check logs/daily.log to see why

**Comment by search4u2003** [comment]
Hi Laf,

Have checked the logs and dint find any problems or issue in daily.log.

Do u wan me to attach the daily.log file here.

**Comment by laf** [comment]
Feel free to pastebin it + the output of ./validate.php

**Comment by search4u2003** [comment]
[daily.docx](https://github.com/librenms/librenms/files/552658/daily.docx)


[root@librenms librenms]# ./validate.php
==========================================================
LibreNMS Version: 7ca80410d56d519d1353aae107bee715962ba46f
DB Schema: 144
PHP: 7.0.11
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful

**Comment by laf** [comment]
You're on the monthly release, you'll need to wait until Sunday before this is fixed.
