### ISSUE TITLE
API call to services only returns last device

### ISSUE THREAD

**Issue by tijmenNL** [librenms/librenms#4876]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.

LibreNMS Version: 8da3b1f813e6737205bbb55f5aac09948116cd2c
DB Schema: 148
PHP: 5.4.45-1~dotdeb+7.1
MySQL: 5.1.73-1+deb6u1
RRDTool: 1.4.3
SNMP: NET-SNMP 5.4.3

- [x] Please provide as much detail as possible.

Hi,

If I use the API to list the services I only get them for the last device, not for all devices.

I do:
```
curl -H 'X-Auth-Token: xxx' https://url/api/v0/services 
```

If I should get them for all devices (what I suspect) this seems a bug. I can make a PR fixing this.

**Comment by laf** [comment]
Thanks :)
