### ISSUE TITLE
Component status widget not working

### ISSUE THREAD

**Issue by huegelc** [librenms/librenms#4877]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.
```
LibreNMS Version: 8da3b1f813e6737205bbb55f5aac09948116cd2c
DB Schema: 148
PHP: 7.0.8-0ubuntu0.16.04.3
MySQL: 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP 5.7.3
```
The component status widget seems to be broken. Also the settings can´t be changed.
 I have about 6 devices running.

![librenms_status](https://cloud.githubusercontent.com/assets/6955465/19681859/5d575360-9aab-11e6-8987-05be4f791dfa.png)

Please advise how to provide more debug information. Thank you.

**Comment by laf** [comment]
Do you have any components? These are usually cisco only at the moment but I expect you don't as it works for me.

It also doesn't have any settings to edit.

**Comment by huegelc** [comment]
I have only Juniper components and yes, the settings can´t be edited.

**Comment by laf** [comment]
So the widget is working as expected then.
