### ISSUE TITLE
[Feature Request] Support for %placeholders in procedure URL in alert rules

### ISSUE THREAD

**Issue by sliddjur** [librenms/librenms#4879]
- [X] Please include all of the information between the `====================================` section of `./validate.php`.

LibreNMS Version: 8da3b1f813e6737205bbb55f5aac09948116cd2c
DB Schema: 148
PHP: 5.5.14
MySQL: 10.0.22-MariaDB
RRDTool: 1.4.7
SNMP: NET-SNMP 5.7.3
- [X] Please provide as much detail as possible.

It would be nice to have support for %placeholder variables in procedure URL. So that you can use the ones mentioned in the doc for alerting; http://docs.librenms.org/Extensions/Alerting/#syntax_1 .
Especially alert rule name/id, hostname, sysname, title, description.

**Comment by clay584** [comment]
Yes please.  This would be very useful to me as well.

**Comment by laf** [comment]
Use the ability in the top right of the first post to up vote this. Comments don't help :)

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-support-for-placeholders-in-procedure-url-in-alert-rules/686
