### ISSUE TITLE
Add detection for Dell KVM 1082DS

### ISSUE THREAD

**Issue by tobiasa1** [librenms/librenms#4881]
Dell IP KVM 1082DS

discovery: https://tobiasa.se/priv/dellkvm/discovery.txt
poller: https://tobiasa.se/priv/dellkvm/poller.txt
snmpbulkwalk: https://tobiasa.se/priv/dellkvm/snmpbulkwalk.txt

LibreNMS Version: ef8aa9134ae5fd06680b214d19cd3553fad57694
DB Schema: 148
PHP: 5.5.9-1ubuntu4.20
MySQL: 5.5.44-0ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP 5.7.2

[OK]    Database connection successful

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by laf** [comment]
What's the name of the firmware / os for these?

**Comment by tobiasa1** [comment]
Not sure about OS name, but the firmware file is called  FL0639-DELL-1.32.0.24546.fl
