### ISSUE TITLE
Empty port values from D-Link DGS-1100-24  - Error: OID not increasing

### ISSUE THREAD

**Issue by aparedero** [librenms/librenms#4890]
- [x] Is your install up to date? Yes
- [x] Please include all of the information between the section of `./validate.php`.

```
LibreNMS Version: 1504c04fee903f6e129e8aaf53d6469da7e835b5
DB Schema: 148
PHP: 7.0.11
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2
```

Hi there,

I'm trying to polling a D-Link DGS-1100-24 but the port graphs are not showing. 

After executing manually the poller.php command I see this output related:

```
#### Load poller module ports ####
Caching Oids: dot3StatsDuplexStatusvalidvalidvalidvalidvalidvalidvalidvalidvalidvalidvalidvalidvalidvalidvalidvalidvalidvalidvalidvalidvalidvalidvalidvalid
Port : D-Link Corporation DGS-1100-24 1.01.018 Port 1 (1 / #195) dot3Duplex VLAN == 1D-Link Corporation DGS-1100-24 1.01.018 Port 1bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port : D-Link Corporation DGS-1100-24 1.01.018 Port 2 (2 / #196) dot3Duplex VLAN == 801D-Link Corporation DGS-1100-24 1.01.018 Port 2bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port : D-Link Corporation DGS-1100-24 1.01.018 Port 3 (3 / #197) dot3Duplex VLAN == 801D-Link Corporation DGS-1100-24 1.01.018 Port 3bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port : D-Link Corporation DGS-1100-24 1.01.018 Port 4 (4 / #198) dot3Duplex VLAN == 801D-Link Corporation DGS-1100-24 1.01.018 Port 4bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port : D-Link Corporation DGS-1100-24 1.01.018 Port 5 (5 / #199) dot3Duplex VLAN == 801D-Link Corporation DGS-1100-24 1.01.018 Port 5bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port : D-Link Corporation DGS-1100-24 1.01.018 Port 6 (6 / #200) dot3Duplex VLAN == 801D-Link Corporation DGS-1100-24 1.01.018 Port 6bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (7 / #201) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (8 / #202) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (9 / #203) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (10 / #204) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (11 / #205) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (12 / #206) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (13 / #207) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (14 / #208) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (15 / #209) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (16 / #210) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (17 / #211) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (18 / #212) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (19 / #213) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (20 / #214) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (21 / #215) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (22 / #216) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (23 / #217) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
Port :  (24 / #218) dot3Duplex VLAN == 801bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)
```

If I execute an snmpwalk command from libreNMS server it outputs about 1280 lines but is incomplete and shows that error:

```
Error: OID not increasing: SNMPv2-SMI::mib-2.17.4.3.1.1.160.29.72.251.13.200
 >= SNMPv2-SMI::mib-2.17.4.3.1.1.84.184.10.125.157.123

```

[snmpwalk.txt](https://github.com/librenms/librenms/files/555332/snmpwalk.txt)

Adding -Cc attribute (do not check returned OIDs are increasing) the snmpalk outputs the complete sequence, about 2600 lines
[snmpwalkCc.txt](https://github.com/librenms/librenms/files/555331/snmpwalkCc.txt)

And last, executing snmpbulkwalk shows a timeout at line 32

```
[root@libreNMS 172.255.255.251]# snmpbulkwalk -OUneb -v2c -c SNMPDatioNeehohp 172.255.255.251
.1.3.6.1.2.1.1.1.0 = STRING: DGS-1100-24 Gigabit Ethernet Switch
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.171
.1.3.6.1.2.1.1.3.0 = Timeticks: (375570377) 43 days, 11:15:03.77
.1.3.6.1.2.1.1.4.0 = STRING: 
.1.3.6.1.2.1.1.5.0 = STRING: SwitchTest
.1.3.6.1.2.1.1.6.0 = STRING: Switchtest
.1.3.6.1.2.1.1.7.0 = INTEGER: 8
.1.3.6.1.2.1.2.1.0 = INTEGER: 24
.1.3.6.1.2.1.2.2.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.1.2 = INTEGER: 2
.1.3.6.1.2.1.2.2.1.1.3 = INTEGER: 3
.1.3.6.1.2.1.2.2.1.1.4 = INTEGER: 4
.1.3.6.1.2.1.2.2.1.1.5 = INTEGER: 5
.1.3.6.1.2.1.2.2.1.1.6 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.1.7 = INTEGER: 7
.1.3.6.1.2.1.2.2.1.1.8 = INTEGER: 8
.1.3.6.1.2.1.2.2.1.1.9 = INTEGER: 9
.1.3.6.1.2.1.2.2.1.1.10 = INTEGER: 10
.1.3.6.1.2.1.2.2.1.1.11 = INTEGER: 11
.1.3.6.1.2.1.2.2.1.1.12 = INTEGER: 12
.1.3.6.1.2.1.2.2.1.1.13 = INTEGER: 13
.1.3.6.1.2.1.2.2.1.1.14 = INTEGER: 14
.1.3.6.1.2.1.2.2.1.1.15 = INTEGER: 15
.1.3.6.1.2.1.2.2.1.1.16 = INTEGER: 16
.1.3.6.1.2.1.2.2.1.1.17 = INTEGER: 17
.1.3.6.1.2.1.2.2.1.1.18 = INTEGER: 18
.1.3.6.1.2.1.2.2.1.1.19 = INTEGER: 19
.1.3.6.1.2.1.2.2.1.1.20 = INTEGER: 20
.1.3.6.1.2.1.2.2.1.1.21 = INTEGER: 21
.1.3.6.1.2.1.2.2.1.1.22 = INTEGER: 22
Timeout: No Response from 172.255.255.251
```

**Comment by laf** [comment]
Can you provide the full output of `./poller.php -h HOSTNAME -d -r -f -m ports` as well pls.

**Comment by aparedero** [comment]
Good morning @laf , here is the poller.php output you requested.

[pollerWithDebug.txt](https://github.com/librenms/librenms/files/561368/pollerWithDebug.txt)

**Comment by laf** [comment]
We don't seem to get back the full results from ifEntry, indicates a timeout:

```bash
SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUst -m IF-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 ifEntry]
Timeout: No Response from udp:172.255.255.251:161
ifIndex.1 = 1
ifIndex.2 = 2
ifIndex.3 = 3
ifIndex.4 = 4
ifIndex.5 = 5
ifIndex.6 = 6
ifIndex.7 = 7
ifIndex.8 = 8
ifIndex.9 = 9
ifIndex.10 = 10
ifIndex.11 = 11
ifIndex.12 = 12
ifIndex.13 = 13
ifIndex.14 = 14
ifIndex.15 = 15
ifIndex.16 = 16
ifIndex.17 = 17
ifIndex.18 = 18
ifIndex.19 = 19
ifIndex.20 = 20
ifIndex.21 = 21
ifIndex.22 = 22
ifIndex.23 = 23
ifIndex.24 = 24
ifDescr.1 = D-Link Corporation DGS-1100-24 1.01.018 Port 1
ifDescr.2 = D-Link Corporation DGS-1100-24 1.01.018 Port 2
ifDescr.3 = D-Link Corporation DGS-1100-24 1.01.018 Port 3
ifDescr.4 = D-Link Corporation DGS-1100-24 1.01.018 Port 4
ifDescr.5 = D-Link Corporation DGS-1100-24 1.01.018 Port 5
ifDescr.6 = D-Link Corporation DGS-1100-24 1.01.018 Port 6
```

You can try setting the snmp timeout for that device (edit device -> snmp).

You could also try setting the max repeaters: http://docs.librenms.org/Support/Performance/#snmp-max-repeaters

**Comment by aparedero** [comment]
Hi @laf 

I updated on LibreNMS -> edit device -> snmp and now I see graphs from ports so I didn't need extend the timeout from SNMP for obtaining the info. Maybe that was corrected on any recent update so the critical issue can be marked as closed.

btw, exploring different tabs I see that LibreNMS only obtains the main VLAN on each port (on HP swithces this is the "PVID" parameter on Access/Trunk/Hybrid port) and do not declare the Trunk/Hybrid ports

For Example the port Gi1/0/1 is a trunk port working as a Hybrid port (Access and trunk at the same time) having VLAN40 as access and VLAN20 and 30 as trunk. LibreNMS only shows VLAN40
![image](https://cloud.githubusercontent.com/assets/20164509/20426016/8c055f1a-ad7d-11e6-9671-f2e257e65032.png)

This could be considered on another Issue?

**Comment by laf** [comment]
Yes please a separate issue is needed for that.

**Comment by aparedero** [comment]
@laf I need to reopen again. I don't know what happen but graphs just dissapeared again

Here is a video of the issue. This is with a new instance of LibreNMS from Ubuntu's OVA on Download page: Just forced daily.sh script and added the device in order to confirm that is reproducible in any enviorment:
https://www.youtube.com/watch?v=NqEy1QPZ5Oc

There is the same error with snmpalk, only if I attach -Cc command we receive the complete SNMP output

**Comment by laf** [comment]
No video and no debug output as before, please provide this information.

**Comment by aparedero** [comment]
My bad laf,

 The problem is that LibreNMS are not showing correctly this device and looks that the entire web stop while load info from database.

- [x] Is your install up to date? 
- [x] Please include all of the information between the `==` section of `./validate.php`.
Component | Version
--------- | -------
LibreNMS  | 09767f7e95d425772760481a1b36cae57d6dea4a
DB Schema | 151
PHP       | 7.0.12
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

- [ ] Please provide as much detail as possible.

Attaching poller.php info
[debug_poller.txt](https://github.com/librenms/librenms/files/630493/debug_poller.txt)

Atacching snmpwalk WITHOUT -Cc command: Throws error
Error: OID not increasing: SNMPv2-SMI::mib-2.17.4.3.1.1.248.50.228.187.215.3
 >= SNMPv2-SMI::mib-2.17.4.3.1.1.232.247.36.37.121.182
[debug_snmpwalk.txt](https://github.com/librenms/librenms/files/630494/debug_snmpwalk.txt)

Atacching snmpwalk WITH -Cc command
[debug_snmpwalk_cc.txt](https://github.com/librenms/librenms/files/630495/debug_snmpwalk_cc.txt)

Error in LibreNMS, almost all graphs empty:
https://www.youtube.com/watch?v=NqEy1QPZ5Oc

If need more info please let me know.
My bad laf,

 The problem is that LibreNMS are not showing correctly this device and looks that the entire web stop while load info from database.

- [x] Is your install up to date? 
- [x] Please include all of the information between the `==` section of `./validate.php`.
Component | Version
--------- | -------
LibreNMS  | 09767f7e95d425772760481a1b36cae57d6dea4a
DB Schema | 151
PHP       | 7.0.12
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

- [ ] Please provide as much detail as possible.

Attaching poller.php info
[debug_poller.txt](https://github.com/librenms/librenms/files/630493/debug_poller.txt)

Atacching snmpwalk WITHOUT -Cc command: Throws error
Error: OID not increasing: SNMPv2-SMI::mib-2.17.4.3.1.1.248.50.228.187.215.3
 >= SNMPv2-SMI::mib-2.17.4.3.1.1.232.247.36.37.121.182
[debug_snmpwalk.txt](https://github.com/librenms/librenms/files/630494/debug_snmpwalk.txt)

Atacching snmpwalk WITH -Cc command
[debug_snmpwalk_cc.txt](https://github.com/librenms/librenms/files/630495/debug_snmpwalk_cc.txt)

Error in LibreNMS, almost all graphs empty:
https://www.youtube.com/watch?v=NqEy1QPZ5Oc

If need more info please let me know.

**Comment by laf** [comment]
Is this still an issue for you?

The poller output is still showing a timeout so this does indicate it's a device issue, you could try using snmp v1 as a test but overall you should potentially raise this with d-link

**Comment by laf** [comment]
No response provided.
