### ISSUE TITLE
Changing user password does not work

### ISSUE THREAD

**Issue by paszczus** [librenms/librenms#4892]
# -bash-4.2$ ./validate.php 

LibreNMS Version: b89ebabeccbd7948aa0f54e9736d602e78bb2126
DB Schema: 148
PHP: 5.4.16
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
# SNMP: NET-SNMP 5.7.2

[OK]    Database connection successful

--- PROBLEM ---

I have noticed that after changing password for user it does not work.
I have checked DB entries and password is changed in DB but user is unable to login using new password.

**Comment by jonathon-k** [comment]
Is this when changing the password as an admin in edit-user or through the user settings page?

**Comment by paszczus** [comment]
As admin in edit-user mode

**Comment by laf** [comment]
That works fine for me.

**Comment by jonathon-k** [comment]
Which authentication module are you using?

**Comment by laf** [comment]
No further info provided.
