### ISSUE TITLE
Cannot change poller group via editing the device

### ISSUE THREAD

**Issue by drakej** [librenms/librenms#4893]
# 

LibreNMS Version: b89ebabeccbd7948aa0f54e9736d602e78bb2126
DB Schema: 148
PHP: 5.6.26
MySQL: 5.1.73
RRDTool: 1.4.8
# SNMP: NET-SNMP 5.7.2

We added distributed polling setup with two pollers running on different hosts. After this change was made, our intention was to move over certain devices that can't be reached by one poller because of a firewall. Unfortunately whenever I use the edit device aspect of the GUI, it won't take the change due to SNMP polling failing from the group it's currently in behind the firewall. We remedy this by modifying it directly in the database which makes it work.

I would propose a button or toggle of some sort to prevent the immediate SNMP check which will always fail if it's not in the correct poller group. At the very least if one is changing the poller group, it should attempt to poll it on the remote host and let the change take place without blocking it due to a local SNMP check failing.

**Comment by laf** [comment]
You can change the group for the device under edit device -> snmp -> Poller Group. If the webui doesn't have access to perform icmp / snmp lookups then hit the Don't perform ICMP or SNMP checks checkbox first.

If you don't see those options then you need to set the `$config['distributed_poller'] = true;` option on the webui box.

We have no way to 'poll' the device in realtime for remote pollers.
