### ISSUE TITLE
HTML support is broken in Notes Widget

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#4898]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [ x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ x ] Please provide as much detail as possible.

LibreNMS Version: b89ebabeccbd7948aa0f54e9736d602e78bb2126
DB Schema: 148
PHP: 5.6.24-0+deb8u1
MySQL: 5.5.52-0+deb8u1
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2.1

Since 2-3 weeks notes widget show html as text.
Is something changed here?

https://snag.gy/G7PLz3.jpg

**Comment by laf** [comment]
This was from a security update we did that now strips out html tags. Will have to work some of allowing that but not <script> tags

**Comment by f0o** [comment]
Maybe we can implement markdown or other formating engines to avoid raw HTML. This might even come handy for alerting :D
