### ISSUE TITLE
Does the Alert Enable/Disable for anyone else?

### ISSUE THREAD

**Issue by mchasteen** [librenms/librenms#490]
Maybe it's just me, but it seems that the alert Enable/Disable toggle switch thing doesn't actually disable alerts for that rule.

**Comment by laf** [comment]
@f0o is the man for alerts, it's possible the status of the rule isn't checked before sending out follow up alerts.

If he's not managed to get to it tomorrow I'll take a look.

**Comment by f0o** [comment]
Will check up on it tmr :)

**Comment by mchasteen** [comment]
Because I don't know what I am doing, I added a possible fix in commit 3add9f71de7d93d7c691ec91658d2e5425d85a6b in the PR for issue 463.  I created a branch for issue-490 and then switched back to issue-463, then got annoyed with email alerts, so I merged it in.

**Comment by f0o** [comment]
Your solution was on the right way, however I disliked how it still pulled all the SQL info prior skipping it.

PR has been submitted where the dispatcher will only select alerts whose rules are not disabled.

Thanks for noticing :)
