### ISSUE TITLE
Alerts Modification

### ISSUE THREAD

**Issue by search4u2003** [librenms/librenms#4900]
==========================================================
LibreNMS Version: 7ca80410d56d519d1353aae107bee715962ba46f
DB Schema: 148
PHP: 7.0.12
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful

I need to know where do i have to make changes to customize mail alerts, as current alerts are not a bit confusing, so need to do some custom modification to mail alerts.

Current Mail Alerts.

Subject:   Alert for device name - Port status up/down

Body
Alert for device name - Port status up/down Severity: critical Timestamp: 2016-10-30 14:40:46 Unique-ID: 952 Rule: Port status up/down Faults: #1: port_id => 169; ifDescr => TenGigabitEthernet1/0/1; Alert sent to: XYZ

Modified to Mail Alerts:-

Subject:  Trouble - Device Name (If port is down)
Subject:  Clear - Device Name (If port is UP)

Body

Trouble - Device Name
Message
Message: Interface 'GigabitEthernet0/0/0-"Port Number"' is down.
Device: Name
Category: Device
Error Condition: Trouble
Generated at: Oct 29,2016 08:04:31 AM

**Comment by laf** [comment]
You can do this with templates: http://docs.librenms.org/Extensions/Alerting/#templates

You won't be able to have subjects like that though.

**Comment by f0o** [comment]
Templates so support custom titles for alert and recovery.

`Trouble %hostname` should work
