### ISSUE TITLE
Cisco-CIMC Error causes segmentation fault in discovery module

### ISSUE THREAD

**Issue by runekausland** [librenms/librenms#4902]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by runekausland** [comment]
There is a bug in the Cisco-CIMC that causes dicovery.php to crash.

CIMC version: 1.4(3c)

./discovery.php -d -v -h <host> -m entity-physical
Cisco-CIMC Error...

Please log an issue on github with the following information:
-----------------------------------------------
Subject: CIMC Unknown Table: 
Description: The entity-physical module discovered an unknown CIMC table.
A dump of its contents is below:
Array
(
    [2] => 
)
-----------------------------------------------

Segmentation fault

==========================================================
LibreNMS Version: 6996576a9034967926cac18434a9d5171b18e906
DB Schema: 148
PHP: 7.0.11
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2
==========================================================

**Comment by laf** [comment]
Disable this module for now.

Please comment out line 594 in includes/discovery/entity-physical/cimc.inc.php and try again.

**Comment by runekausland** [comment]
That works:
594 #    $component->setComponentPrefs($device['device_id'], $components);

./discovery.php host.example.com 2016-10-31 10:31:35 - 1 devices discovered in 7.403 secs
MySQL: Cell[1/0s] Row[45/0.01s] Rows[3/0s] Column[0/0s] Update[33/0.03s] Insert[106/0.11s] Delete[0/0s]

**Comment by laf** [comment]
please create a separate issue for that.
