### ISSUE TITLE
Syntax to customize Subject of email alert

### ISSUE THREAD

**Issue by search4u2003** [librenms/librenms#4912]
LibreNMS Version: 7ca8041
DB Schema: 148
PHP: 7.0.12
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2

[OK] Database connection successful

========================================================

Please provide syntax to customize the template whereby Subject of Email alert includes below information -

device name   port no.    port status UP / Down

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by laf** [comment]
This isn't possible as more than one port can be part of the alert.

Feel free to add this request to #1314
