### ISSUE TITLE
Tripplite PDUs end up creating endless phases (2 million and counting)

### ISSUE THREAD

**Issue by kate66** [librenms/librenms#4921]
- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php`.
LibreNMS Version: 6996576a9034967926cac18434a9d5171b18e906
DB Schema: 148
PHP: 5.5.9-1ubuntu4.19
MySQL: 5.5.49-MariaDB-1ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP 5.7.2
===========
It appears to be endlessly polling for the phases that do not exist until finally filling the hard drive with RRDs. I will update this with a discovery dump once this is complete.

[tripplite-snmp.txt](https://github.com/librenms/librenms/files/565516/tripplite-snmp.txt)
[poller-tripplite.txt](https://github.com/librenms/librenms/files/565515/poller-tripplite.txt)

**Comment by kate66** [comment]
And a copy of discovery.

[discovery-tripplite.txt](https://github.com/librenms/librenms/files/565517/discovery-tripplite.txt)

**Comment by laf** [comment]
Using this snmpwalk and one we already have i can't replicate this :(

You might need to provide two consecutive discovery logs so we can see where it's adding them in then deleting them.

@librenms/reviewers anyone else see anything in the code that might cause this?

**Comment by murrant** [comment]
Something with the validate array??  I'll try to get my apc PR re-done...

**Comment by murrant** [comment]
@kate66 Need two discovery logs.  It seems one adds the sensors and the next one deletes them...

**Comment by laf** [comment]
Feel free to comment with the info needed.

**Comment by mayheart** [comment]
It's a bad implementation of SNMP on TrippLite's part. @laf  what version was running on the card you tested?

12.04.0047 and below suffers from this bug. I suspect it has something to do with this:

Error: OID not increasing: SNMPv2-SMI::mib-2.33.1.5.2.0
 >= SNMPv2-SMI::mib-2.33.1.5.1.0

/usr/local/bin/snmpwalk -v1 -c 'public' -OsqnU -M /opt/librenms/mibs:/opt/librenms/mibs/poweralert udp:ruskview-ups01.local.lan:161 .1.3.6.1.2.1.33.1.5.2.0
.1.3.6.1.2.1.33.1.5.1.0 599

That oid is the phase counter, for some reason it responds with 599 after that error.

I've attached discover and snmpwalk from both a new gen and old gen TrippLite for comparison.

[newtrippwalk.txt](https://github.com/librenms/librenms/files/1243690/newtrippwalk.txt)
[oldtrippdiscover.txt](https://github.com/librenms/librenms/files/1243691/oldtrippdiscover.txt)
[oldtrippwalk.txt](https://github.com/librenms/librenms/files/1243692/oldtrippwalk.txt)
[newtripp.txt](https://github.com/librenms/librenms/files/1243693/newtripp.txt)
