### ISSUE TITLE
Load Graphs: Error Drawing Graphs

### ISSUE THREAD

**Issue by huegelc** [librenms/librenms#4924]
```
LibreNMS Version: 667ba601accfef67f11bdd787ab18980771df8bb
DB Schema: 148
PHP: 7.0.8-0ubuntu0.16.04.3
MySQL: 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP 5.7.3


[OK]    Database connection successful
[WARN]  Your local git contains modified files, this could prevent automatic updates.
Modified files:
    html/images/librenms_logo_light.png

```
For our Juniper network devices we do not see any load graphs:
![devices_-_librenms_loaderror](https://cloud.githubusercontent.com/assets/6955465/19926049/cb9b3218-a0f2-11e6-9fdb-5d7769119646.png)

Also the diskIO graphs are broken.
![devices_-_librenms_diskio](https://cloud.githubusercontent.com/assets/6955465/19926064/d94c13fa-a0f2-11e6-835c-3c0738b58ef5.png)

Thanks

**Comment by laf** [comment]
Not sure I'd expect load and disk graphs for Juniper kit. Anyone else use juniper stuff to know?

**Comment by laf** [comment]
No further info provided
