### ISSUE TITLE
connect librenms with grafana

### ISSUE THREAD

**Issue by shadialsalamat** [librenms/librenms#4925]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by shadialsalamat** [comment]
hallo 
i download 
grafana 
librenms 
influxdb 
everyrhing work good but i want to connect librenms with grafana is that possible _
if yes how can i do that

**Comment by laf** [comment]
You can enable influxdb support in LibreNMS then use grafana to use that data.

Github issues are for bugs and features, please ask for help on https://community.librenms.org or on IRC: Freenode ##librenms
