### ISSUE TITLE
[Feature request] matrix alerting

### ISSUE THREAD

**Issue by TJuberg** [librenms/librenms#4927]
It would be very nice if support for alerting via [Matrix](http://matrix.org/) could be added.
As far as I know, no one has written a client SDK in php yet, however the [Drupal integration](https://www.drupal.org/project/matrix_api) might be useful 

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-matrix-alerting/1050
