### ISSUE TITLE
Some Windows hosts are not showing disk utilization / properties

### ISSUE THREAD

**Issue by gilrim** [librenms/librenms#4929]
DO NOT DELETE THIS INFORMATION.

```
==========================================================
LibreNMS Version: 6bed6cbea187b1a59b3cd049a3aa29ca6081723d
DB Schema: 148
PHP: 7.0.8-0ubuntu0.16.04.3
MySQL: 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP 5.7.3
==========================================================
```

I've got a bunch of windows boxes added, and for most of them things are working smoothly. But I've also got a few five units that doesn't update its storage details for the C:\ drive. I'm including screenshots and discover/poller/snmp outputs - are there anything else I could provide to help identify what's happening?

From just looking at the snmp responses it seems that windows is providing the data, but librenms is messing up parsing it?

![2016_11_03_ _selection_001](https://cloud.githubusercontent.com/assets/434698/19962219/efe8904c-a1b6-11e6-8eeb-40f2ba1aca43.png)
![screenshot at 2016-11-03 11 13 23](https://cloud.githubusercontent.com/assets/434698/19962226/f5e8c264-a1b6-11e6-9193-6e6c34a01f02.png)
[poller-notrofl.txt](https://github.com/librenms/librenms/files/568651/poller-notrofl.txt)
[discovery-notrofl.txt](https://github.com/librenms/librenms/files/568650/discovery-notrofl.txt)

**Comment by laf** [comment]
This looks to be an issue with the device, it's not returning data:

```
    [storage_id] => 872
    [device_id] => 147
    [storage_mib] => hrstorage
    [storage_index] => 2
    [storage_type] => hrStorageFixedDisk
    [storage_descr] => C:\\ Label:  Serial Number 4c65395d
    [storage_size] => 0
    [storage_units] => 0
    [storage_used] => 0
    [storage_free] => 0
    [storage_perc] => 0
    [storage_perc_warn] => 60
    [storage_deleted] => 0
    [units] =>
    [used] => 0
    [size] => 0
    [free] => 0
```

Used and size shouldn't be 0.

Not sure this is something we can fix.

**Comment by gilrim** [comment]
I'm trying to make sense of the poller-log, but while I do find the numbers your referring to on lines 241-257, I also find it on the lines 321-327. There the numbers haven't been calculated yet, but both disksize and untilization is listed..
I've assumed that the numbers that's injected to the rrd's are calculated from the snmp data?

**Comment by laf** [comment]
We will need to see polling debug for both a working and non-working time.

**Comment by gilrim** [comment]
Strangely enough, this host seems to be reporting the correct stats now, see attached poller-log. The other drives seen in the heidisql screenshot, are still reporting disk consumption sporadically or not at all:
![screenshot at 2016-11-17 12 35 00](https://cloud.githubusercontent.com/assets/434698/20387938/e06434de-acc2-11e6-804e-ff86836b6d97.png)

**Comment by laf** [comment]
We really need to see both a working and non-working poller debug.

**Comment by gilrim** [comment]
trying again - with better description in filenames :)
[poller-notrofl_storage_broken.txt](https://github.com/librenms/librenms/files/599505/poller-notrofl_storage_broken.txt)
[Uploading poller-notrofl_storage_working.txt…]()

**Comment by geordish** [comment]
When trying to obtain the data for C:, Line 233 in the broken poll show that when requested it doesn't respond with the data that is needed. Because of this everything gets updated with 0's.

When F:, is then polled a little later on line 262, you can see that the data is returned this time.

Maybe the windows SNMP agent is a bit flaky, or maybe librenms causes a bit too much load with its polling. Are other graphs affected?

You could try increasing the SNMP timeout value in config.php to see if this helps.
http://docs.librenms.org/Support/Configuration/#snmp-settings

**Comment by laf** [comment]
No response provided.
