### ISSUE TITLE
Geolocation on pollers causes duplicates because of caching and race conditions

### ISSUE THREAD

**Issue by drakej** [librenms/librenms#4930]
==========================================================
LibreNMS Version: 6bed6cbea187b1a59b3cd049a3aa29ca6081723d
DB Schema: 148
PHP: 5.6.26
MySQL: 5.1.73
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2
==========================================================

After turning on $config['geoloc']['latlng'] = true; in config.php, it creates a ton of duplicates inside of the locations DB table.

I found two problems with the setup. 

First, the query to check for an existing location in the function location_to_latlng (includes/polling/functions.inc.php) runs a dbFetchRow query against the cache (why would you ever want to do that if it's a check for existing data in the DB?!).

The second problem occurs even if you do turn off the memcached usage for the call via the 3rd argument being set to true. There's a race condition because devices are polled and updated asynchronously and if two devices in the same location both check the locations table for a preexisting row before either of them write the result of the google lookup, it creates duplicates.

You need to first off, turn off the memcached usage, which is really an amazing mistake, might want to blacklist that developer from contributing because their skill is lacking.

Second you need to make sure that the locations table provides a locking mechanism to prevent multiple reads at the same time from this particular check. This is probably going to be something that isn't easy given I would expect the need to make the actual dbFetchRow call to support a full table lock on reads since the code treats this as a critical section without actually locking it!

You might want to consider reeducation when it comes to locking mechanics. These things are vital when working with databases and parallel programming. Nobody has any business writing code using parallel processing and async methodology if they don't understand how locks work.

**Comment by laf** [comment]
I'm actually not sure how to respond to this.

You may or may not be aware of our history but in general we inherited a pretty horrible code base and people have worked to improve it, is it perfect still - no, will it ever be - probably not.

'That' developer who added memcached did so quickly to fix an utterly broken memcache code base so it's a hell of a lot better than it was. And no, we won't blacklist them, they've contributed a hell of a lot to this project.

Duplicate information in the locations table is hardly a major issue, are you seeing 1,00's of duplicates?

We appreciate feedback but please be constructive, telling us to blacklist contributors from the project when you in turn haven't contributed anything isn't going to do anything but annoy people.

We look forward to seeing your pull requests to fix these issues.

**Comment by drakej** [comment]
Fair enough. I do not know of your history and I haven't contributed yet because well, I've only been evaluating the project and utilizing it for a few days at my day job. I'm working on a pull request and code change to address this issue, stay tuned.

**Comment by f0o** [comment]
Not sure what to say either. Yes you are right that nothing on the DB handlers are suited for parallel computing. This is mainly due to the sequential polling that was used back when it was Observium. Job came and wrote that awesome threading wrapper out of necessity and ofc the db-handlers didn't change to suit this new usage. Not so much later we forked away.

We devs are very tired of hot fixing one thing aftet another and specially laf+murrant are doing amazing work on rewriting the entire thing into a more sane format with LibreNMSv2.

Open Source is a community effort, if you can help and know how to make the db-handlers better please do and submit a PR or just a diff/patch.

**Comment by drakej** [comment]
I ran into a problem with it because the database layer starts a transaction which frees up the lock before the insert is attempted. When I disable the transaction setup in that dbInsert routine, the problem is fixed with LOCK TABLE and UNLOCK TABLES as expected. Still looking into a way to solve this that doesn't require completely changing the database layer as  a whole.

**Comment by drakej** [comment]
#4931 Added, hope it's up to standards :)

**Comment by laf** [comment]
It's got a small code formatting issue (we run to PSR-2 standards) but aside from that it works so thanks.

**Comment by drakej** [comment]
I give up, you're clearly a group of individuals that don't like outsiders helping

**Comment by laf** [comment]
Erm, yes that's exactly what this project is about but thanks for stopping by.
