### ISSUE TITLE
Line break is not working when creating a template

### ISSUE THREAD

**Issue by yurylinebreak** [librenms/librenms#4932]
\n nor \r\n is working for line break when sending to email. 

screenshot of template example where line break is not working https://snag.gy/58OD2s.jpg

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by laf** [comment]
I've just tested this and actually you don't need `\r\n` or `\n` it works by just formatting the alert like:
```
Testing 123

End here
```

Which gives:

![image](https://cloud.githubusercontent.com/assets/3941142/19997628/d652e21e-a25f-11e6-8ec7-20e0055ffcf2.png)

If this isn't working for you, what browser and version? What OS are you using for your desktop? Do you have html enabled alerts enabled?

**Comment by yurylinebreak** [comment]
Laf, thank you for your reply. I just tried it like that and this is not working for me still. I am using latest version of chrome on Windows. I am not sure how to enable html alerts....

**Comment by laf** [comment]
I don't use windows. Hopefully someone else can test for you.

**Comment by yurylinebreak** [comment]
laf I disabled html alerts and now line break is working! No \r\n or \n is needed. Thank you!
