### ISSUE TITLE
services.inc.php is escaping things, causing issues with services that allow things like regex as arguments

### ISSUE THREAD

**Issue by Gorian** [librenms/librenms#4934]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

Component|Version
-------------|-------------
LibreNMS | 6bed6cbea187b1a59b3cd049a3aa29ca6081723d
DB Schema | 148
PHP | 7.0.11
MySQL | 5.5.50-MariaDB
RRDTool | 1.4.8
SNMP | NET-SNMP 5.7.2

https://github.com/librenms/librenms/blob/master/includes/services.inc.php#L206

the check_service function runs the check command through `escapeshellcmd`, which escapes all the things for safe execution. This is great, except that some services, like check_http include a `--regex` option. In my case, I have a REST API that returns an empty set in json, like `{"C":"V"}`. I want check_http to return OK if it receives this response. the argument `--regex="\{\"C\"\:\"V\"\}"` does exactly what I want, however the regex string is being escaped by `escapeshellcmd`, resulting in the following instead: `--regex=\{"C":"V"\}`

You can see here:
![image](https://cloud.githubusercontent.com/assets/1012176/19988646/8d833de4-a1de-11e6-963c-f91d7f119a05.png)

if there was a way to safely escape user input, while allowing service checks with more complex arguments,that would be awesome. 

Full service_params string: `--ssl --method="POST" --content-type="application/json" --url="/query"  --regex="\{\"C\":\"V\"\}"`

Command working correctly in CLI:
![image](https://cloud.githubusercontent.com/assets/1012176/19988890/25866e58-a1e0-11e6-872d-1efc6927cb8a.png)

**Comment by laf** [comment]
This is going to get funky to fix :/

**Comment by Gorian** [comment]
yeah, I know. That's why I submitted an issue instead a pull request. You obviously don't want to remove the escaping for security reasons. I don't know my PHP well enough to implement a fix quickly, but from a logical point of view I'm thinking you can implement some sort of argument parsing, and seperate the arguments into an array with 2 parts. The arguments (short,  `-v` and long `--regex`, for example), and then the parameters to the arguments, either `-r "\{\"C\":\"V\"\}"`  or `--regex="\{\"C\":\"V\"\}"`, and then "build" your parameters by passing the arguments (not the parameters to them) through `escapeshellcmd`, and then then parameters though [escapeshellarg](http://php.net/manual/en/function.escapeshellarg.php). functionally, you'd end up with something like this:
```
    $check_cmd = $config['nagios_plugins'] . "/check_" . $service['service_type'] . " -H " . ($service['service_ip'] ? $service['service_ip'] : $service['hostname']);
    foreach ($args as $i => $arg){
        $check_cmd .= " " . escapeshellcmd($arg['arg']) . escapeshellarg($arg['param']);
    }
```

The code probably isn't correct, but may give an idea of what may be a solution.

`

**Comment by laf** [comment]
I'm not sure how best to approach this. How do we split the user input from service_params into an arg list?

@librenms/reviewers thoughts?

**Comment by adaniels21487** [comment]
One option...
We could move escapeshellcmd($command) from check_service into the catchall in poll_service, like so:

```
    // If we do not have a cmd from the check script, build one.
    if ($check_cmd == "") {
        $check_cmd = $config['nagios_plugins'] . "/check_" . $service['service_type'] . " -H " . ($service['service_ip'] ? $service['service_ip'] : $service['hostname']);
        $check_cmd .= " " . $service['service_param'];
        $check_cmd = escapeshellcmd($check_cmd);
    }
```

and then duplicate in each specific check_script. Eg: includes/services/check_dhcp.inc.php:

```
<?php
$check_cmd = $config['nagios_plugins'] . "/check_dhcp ".$service['service_param'];
$check_cmd = escapeshellcmd($check_cmd);
```

This way one could customise check_http.inc.php as needed without affecting other checks.

**Comment by laf** [comment]
@adaniels21487 escapeshellcmd is the issue though in the first place, this escapes json data being passed over :(

**Comment by Gorian** [comment]
any update on this?

**Comment by laf** [comment]
could you test this patch:

```
diff --git a/includes/services.inc.php b/includes/services.inc.php
index a96ad47..695f1ab 100644
--- a/includes/services.inc.php
+++ b/includes/services.inc.php
@@ -200,13 +200,18 @@ function poll_service($service)

 function check_service($command)
 {
+global $config;
     // This array is used to test for valid UOM's to be used for graphing.
     // Valid values from: https://nagios-plugins.org/doc/guidelines.html#AEN200
     // Note: This array must be decend from 2 char to 1 char so that the search works correctly.
     $valid_uom = array ('us', 'ms', 'KB', 'MB', 'GB', 'TB', 'c', 's', '%', 'B');

     // Make our command safe.
-    $command = 'LC_NUMERIC="C" '. escapeshellcmd($command);
+        $p_config = HTMLPurifier_Config::createDefault();
+        $p_config->set('Cache.SerializerPath', $config['temp_dir']);
+        $purifier = new HTMLPurifier($p_config);
+
+    $command = 'LC_NUMERIC="C" '. $purifier->purify($command);

     // Run the command and return its response.
     exec($command, $response_array, $status);

```

**Comment by laf** [comment]
No further info provided. Closing for now, feel free to respond once tested
