### ISSUE TITLE
Fix detection of Edgerouter

### ISSUE THREAD

**Issue by systeembeheerder** [librenms/librenms#4936]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [X] Please provide as much detail as possible.
LibreNMS Version: aac9b73c9136d1027595b5f630b6f4d4071ff331
DB Schema: 148
PHP: 7.0.8-0ubuntu0.16.04.3
MySQL: 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.6
SNMP: NET-SNMP 5.7.3

The EdgeRouter 8 Port is not detected by LibreNMS. Exact model:

`admin@ubnt:~$ show version`
`Version:      v1.9.0`
`Build ID:     4901118`
`Build on:     08/04/16 11:39`
`Copyright:    2012-2016 Ubiquiti Networks, Inc.`
`HW model:     EdgeRouter 8-Port`
`HW S/N:       24A43CB000AA`
`Uptime:       11:12:35 up 2 days, 21:23,  2 users,  load average: 0.03, 0.07, 0.06`

Gives as SNMP system description:
`# snmpwalk -v2c -c snmpstring  edgerouterfqdn  | grep -i iso.3.6.1.2.1.1.1.0`
`iso.3.6.1.2.1.1.1.0 = STRING: "EdgeRouter"`

which is not picked up by [master/includes/discovery/os/edgeos.inc.php](https://github.com/librenms/librenms/blob/master/includes/discovery/os/edgeos.inc.php)
Changing line 5 from
`    'EdgeRouter Lite',`
to
`    'EdgeRouter',`
fixed this.

Thanks in advance.

**Comment by laf** [comment]
We need the full sysDescr and sysObjectID. Can you provide the output of:

`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .`

**Comment by systeembeheerder** [comment]
Hi laf,
Here you go: http://pastebin.com/ehAXfZAw
