### ISSUE TITLE
Add further support for airFiber

### ISSUE THREAD

**Issue by salvadorb** [librenms/librenms#4941]
Hi LibreNMS team,
It's Salvador Bertenbreiter from Ubiquiti Networks.
I installed your software a few days ago and I really like it. 

I have added a few airFibers that I am monitoring works like a charm. That being said, I think there are a few extra statistics could be useful for users (if they are already included sorry, I wasn't able to find those into the LibreNMS interface)
1.3.6.1.4.1.41112.1.3.2.1.2        - tx Modulation

1.3.6.1.4.1.41112.1.3.2.1.43      - Ethernet DATA port speed and duplex

1.3.6.1.4.1.41112.1.3.2.1.47      - DFS hits

Here are the snmpwalk outputs

Tx Modulation Currently in 8X
librenms@librenms:~$ snmpwalk -Os -v1 -c opticsnmp 192.168.12.131 1.3.6.1.4.1.41112.1.3.2.1.2
iso.3.6.1.4.1.41112.1.3.2.1.2.1 = INTEGER: 8

Ethernet DATA port speed
librenms@librenms:~$ snmpwalk -Os -v1 -c opticsnmp 192.168.12.131 1.3.6.1.4.1.41112.1.3.2.1.43
iso.3.6.1.4.1.41112.1.3.2.1.43.1 = STRING: "1000Mbps-Full"

DFS Hits (Currently no DFS hit)

librenms@librenms:~$ snmpwalk -Os -v1 -c opticsnmp 192.168.12.131 1.3.6.1.4.1.41112.1.3.2.1.47
iso.3.6.1.4.1.41112.1.3.2.1.47.1 = INTEGER: 0

**Comment by laf** [comment]
Can you provide the output of:

```bash
snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .
```

**Comment by salvadorb** [comment]
Sure. Here it is:

librenms@librenms:~$ snmpwalk -OUneb -v1 -c public 192.168.12.131 
.1.3.6.1.2.1.1.1.0 = STRING: "Linux 2.6.33 #1 Mon Nov 30 14:15:06 CST 2015 armv5tejl"
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.10002.1
.1.3.6.1.2.1.1.3.0 = Timeticks: (665885700) 77 days, 1:40:57.00
.1.3.6.1.2.1.1.4.0 = STRING: "salvador"
.1.3.6.1.2.1.1.5.0 = STRING: "AF"
.1.3.6.1.2.1.1.6.0 = STRING: "AF"
.1.3.6.1.2.1.1.7.0 = INTEGER: 79
.1.3.6.1.2.1.1.8.0 = Timeticks: (647075100) 74 days, 21:25:51.00
.1.3.6.1.2.1.1.9.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.1.9.1.1.2 = INTEGER: 2
.1.3.6.1.2.1.1.9.1.1.3 = INTEGER: 3
.1.3.6.1.2.1.1.9.1.1.4 = INTEGER: 4
.1.3.6.1.2.1.1.9.1.2.1 = OID: .1.3.6.1.6.3.1
.1.3.6.1.2.1.1.9.1.2.2 = OID: .1.3.6.1.2.1.31
.1.3.6.1.2.1.1.9.1.2.3 = OID: .1.3.6.1.4.1.10002.1.1.1.31
.1.3.6.1.2.1.1.9.1.2.4 = OID: .1.3.6.1.4.1.41112
.1.3.6.1.2.1.1.9.1.3.1 = STRING: "The MIB module for SNMP entities"
.1.3.6.1.2.1.1.9.1.3.2 = STRING: "The MIB module to describe generic objects for network interface sub-layers"
.1.3.6.1.2.1.1.9.1.3.3 = STRING: "The MIB module to describe system resources"
.1.3.6.1.2.1.1.9.1.3.4 = STRING: "Ubiquiti Networks MIB module "
.1.3.6.1.2.1.1.9.1.4.1 = Timeticks: (647075100) 74 days, 21:25:51.00
.1.3.6.1.2.1.1.9.1.4.2 = Timeticks: (647075100) 74 days, 21:25:51.00
.1.3.6.1.2.1.1.9.1.4.3 = Timeticks: (647075100) 74 days, 21:25:51.00
.1.3.6.1.2.1.1.9.1.4.4 = Timeticks: (647075100) 74 days, 21:25:51.00
.1.3.6.1.2.1.2.1.0 = INTEGER: 7
.1.3.6.1.2.1.2.2.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.1.2 = INTEGER: 2
.1.3.6.1.2.1.2.2.1.1.3 = INTEGER: 3
.1.3.6.1.2.1.2.2.1.1.4 = INTEGER: 4
.1.3.6.1.2.1.2.2.1.1.5 = INTEGER: 5
.1.3.6.1.2.1.2.2.1.1.6 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.1.7 = INTEGER: 7
.1.3.6.1.2.1.2.2.1.2.1 = STRING: "lo"
.1.3.6.1.2.1.2.2.1.2.2 = STRING: "sit0"
.1.3.6.1.2.1.2.2.1.2.3 = STRING: "eth0"
.1.3.6.1.2.1.2.2.1.2.4 = STRING: "air0"
.1.3.6.1.2.1.2.2.1.2.5 = STRING: "eth0.12"
.1.3.6.1.2.1.2.2.1.2.6 = STRING: "air0.12"
.1.3.6.1.2.1.2.2.1.2.7 = STRING: "br1"
.1.3.6.1.2.1.2.2.1.3.1 = INTEGER: 24
.1.3.6.1.2.1.2.2.1.3.2 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.3.3 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.3.4 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.3.5 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.3.6 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.3.7 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.4.1 = INTEGER: 16436
.1.3.6.1.2.1.2.2.1.4.2 = INTEGER: 1480
.1.3.6.1.2.1.2.2.1.4.3 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.4.4 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.4.5 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.4.6 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.4.7 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.5.1 = Gauge32: 0
.1.3.6.1.2.1.2.2.1.5.2 = Gauge32: 0
.1.3.6.1.2.1.2.2.1.5.3 = Gauge32: 10000000
.1.3.6.1.2.1.2.2.1.5.4 = Gauge32: 0
.1.3.6.1.2.1.2.2.1.5.5 = Gauge32: 10000000
.1.3.6.1.2.1.2.2.1.5.6 = Gauge32: 0
.1.3.6.1.2.1.2.2.1.5.7 = Gauge32: 0
.1.3.6.1.2.1.2.2.1.6.1 = ""
.1.3.6.1.2.1.2.2.1.6.2 = ""
.1.3.6.1.2.1.2.2.1.6.3 = Hex-STRING: 00 27 22 DA AF XX 
.1.3.6.1.2.1.2.2.1.6.4 = Hex-STRING: 02 27 22 DA AF XX 
.1.3.6.1.2.1.2.2.1.6.5 = Hex-STRING: 00 27 22 DA AF XX 
.1.3.6.1.2.1.2.2.1.6.6 = Hex-STRING: 02 27 22 DA AF XX 
.1.3.6.1.2.1.2.2.1.6.7 = Hex-STRING: 02 27 22 DA AF XX 
.1.3.6.1.2.1.2.2.1.7.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.7.2 = INTEGER: 2
.1.3.6.1.2.1.2.2.1.7.3 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.7.4 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.7.5 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.7.6 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.7.7 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.2 = INTEGER: 2
.1.3.6.1.2.1.2.2.1.8.3 = INTEGER: 2
.1.3.6.1.2.1.2.2.1.8.4 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.5 = INTEGER: 2
.1.3.6.1.2.1.2.2.1.8.6 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.7 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.9.1 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.9.2 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.9.3 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.9.4 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.9.5 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.9.6 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.9.7 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.10.1 = Counter32: 4613
.1.3.6.1.2.1.2.2.1.10.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.10.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.10.4 = Counter32: 2204109624
.1.3.6.1.2.1.2.2.1.10.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.10.6 = Counter32: 213632788
.1.3.6.1.2.1.2.2.1.10.7 = Counter32: 202607721
.1.3.6.1.2.1.2.2.1.11.1 = Counter32: 35
.1.3.6.1.2.1.2.2.1.11.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.11.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.11.4 = Counter32: 147912443
.1.3.6.1.2.1.2.2.1.11.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.11.6 = Counter32: 2755875
.1.3.6.1.2.1.2.2.1.11.7 = Counter32: 217587
.1.3.6.1.2.1.2.2.1.12.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.12.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.12.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.12.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.12.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.12.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.12.7 = Counter32: 2538273
.1.3.6.1.2.1.2.2.1.13.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.7 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.7 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.7 = Counter32: 0
.1.3.6.1.2.1.2.2.1.16.1 = Counter32: 4613
.1.3.6.1.2.1.2.2.1.16.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.16.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.16.4 = Counter32: 124001158
.1.3.6.1.2.1.2.2.1.16.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.16.6 = Counter32: 23530204
.1.3.6.1.2.1.2.2.1.16.7 = Counter32: 22650294
.1.3.6.1.2.1.2.2.1.17.1 = Counter32: 35
.1.3.6.1.2.1.2.2.1.17.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.17.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.17.4 = Counter32: 722432
.1.3.6.1.2.1.2.2.1.17.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.17.6 = Counter32: 219925
.1.3.6.1.2.1.2.2.1.17.7 = Counter32: 219922
.1.3.6.1.2.1.2.2.1.18.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.18.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.18.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.18.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.18.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.18.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.18.7 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.5 = Counter32: 2
.1.3.6.1.2.1.2.2.1.19.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.7 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.7 = Counter32: 0
.1.3.6.1.2.1.2.2.1.21.1 = Gauge32: 0
.1.3.6.1.2.1.2.2.1.21.2 = Gauge32: 0
.1.3.6.1.2.1.2.2.1.21.3 = Gauge32: 1000
.1.3.6.1.2.1.2.2.1.21.4 = Gauge32: 1000
.1.3.6.1.2.1.2.2.1.21.5 = Gauge32: 0
.1.3.6.1.2.1.2.2.1.21.6 = Gauge32: 0
.1.3.6.1.2.1.2.2.1.21.7 = Gauge32: 0
.1.3.6.1.2.1.2.2.1.22.1 = OID: .0.0
.1.3.6.1.2.1.2.2.1.22.2 = OID: .0.0
.1.3.6.1.2.1.2.2.1.22.3 = OID: .0.0
.1.3.6.1.2.1.2.2.1.22.4 = OID: .0.0
.1.3.6.1.2.1.2.2.1.22.5 = OID: .0.0
.1.3.6.1.2.1.2.2.1.22.6 = OID: .0.0
.1.3.6.1.2.1.2.2.1.22.7 = OID: .0.0
.1.3.6.1.2.1.11.1.0 = Counter32: 204049
.1.3.6.1.2.1.11.2.0 = Counter32: 204032
.1.3.6.1.2.1.11.3.0 = Counter32: 8
.1.3.6.1.2.1.11.4.0 = Counter32: 8
.1.3.6.1.2.1.11.5.0 = Counter32: 0
.1.3.6.1.2.1.11.6.0 = Counter32: 0
.1.3.6.1.2.1.11.8.0 = Counter32: 0
.1.3.6.1.2.1.11.9.0 = Counter32: 0
.1.3.6.1.2.1.11.10.0 = Counter32: 0
.1.3.6.1.2.1.11.11.0 = Counter32: 0
.1.3.6.1.2.1.11.12.0 = Counter32: 0
.1.3.6.1.2.1.11.13.0 = Counter32: 22654
.1.3.6.1.2.1.11.14.0 = Counter32: 0
.1.3.6.1.2.1.11.15.0 = Counter32: 38712
.1.3.6.1.2.1.11.16.0 = Counter32: 165329
.1.3.6.1.2.1.11.17.0 = Counter32: 0
.1.3.6.1.2.1.11.18.0 = Counter32: 0
.1.3.6.1.2.1.11.19.0 = Counter32: 0
.1.3.6.1.2.1.11.20.0 = Counter32: 0
.1.3.6.1.2.1.11.21.0 = Counter32: 177905
.1.3.6.1.2.1.11.22.0 = Counter32: 0
.1.3.6.1.2.1.11.24.0 = Counter32: 0
.1.3.6.1.2.1.11.25.0 = Counter32: 0
.1.3.6.1.2.1.11.26.0 = Counter32: 0
.1.3.6.1.2.1.11.27.0 = Counter32: 0
.1.3.6.1.2.1.11.28.0 = Counter32: 204033
.1.3.6.1.2.1.11.29.0 = Counter32: 0
.1.3.6.1.2.1.11.30.0 = INTEGER: 2
.1.3.6.1.2.1.11.31.0 = Counter32: 0
.1.3.6.1.2.1.11.32.0 = Counter32: 0

**Comment by laf** [comment]
I have a bit of feeling of deja vu here from #4918 :)

That output doesn't contain the OID's you want us to graph.

**Comment by salvadorb** [comment]
Yup. So it would be awesome to monitor real LAN speed, cause currently LibreNMS shows 10mbps

**Comment by laf** [comment]
Sure but we really need to see an snmpwalk showing that output.

**Comment by laf** [comment]
Feel free to comment back if you get the info we need
