### ISSUE TITLE
Feature Request: Alerting to Serena Business Manager

### ISSUE THREAD

**Issue by Gorian** [librenms/librenms#4942]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | 1840310f811653653f21622501c6b8d3b50594b7
DB Schema | 148
PHP       | 7.0.11
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

Could someone add support to send alerts to Serena Service Manager?

http://www.serena.com/index.php/en/products/it-service-management-itsm-itil/serena-service-manager/benefits/

http://help.serena.com/doc_center/sbm/ver11_1/composer/help.html

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-alerting-to-serena-business-manager/1051
