### ISSUE TITLE
OSPF data not being polled

### ISSUE THREAD

**Issue by bmhughes** [librenms/librenms#4943]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**## validate.php output**
Component | Version
--------- | -------
LibreNMS  | `1840310f811653653f21622501c6b8d3b50594b7`
DB Schema | 148
PHP       | 5.4.16
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.2

I hope someone may be able to help here as i've spent several hours looking at this and can't see why this isn't happening.

I have a monitored Cisco 2851 and 3750 (both IOS15) that for whatever reason won't populate their OSPF data, the 2851 that was added some time ago did have OSPF data but it was old and also duplicated as if I had multiple OSPF processed running when I one have the one. The 3750 I added 24 hours ago has everything collected apart from the OSPF data. 

Deleting and recreating the 2851 produces the same result as the 3750, everything barring OSPF.

When deleting the original 2851 host I ran in #4685 which had multiple foreign keys with delete restrict set which I assume the changes in #3805 should have deleted, upon manually removing the restrict constraints I was able to delete the host without issue. The new constraint with delete cascade was present and all the old device data does appear to have been removed.

I also witnessed #4768 whereby I have a lot of entries for almost every device with nothing but zeroes present, i've cleaned them out as mentioned in the other issue and this hasn't made any difference.

Having looked at the OSPF polling code i'm not sure that actual SNMP polling is being perfored as a manual `snmpwalk` shows all data is present and avaliable. 

The old 2851 OSPF data which was also duplicated, one set had a context of `null` and the other an empty string. I'm assuming this relates to the code below and seeing as I have no VRFs configured that at one point the OSPF polling module did indeed run.

`if (key_exists('vrf_lite_cisco', $device) && (count($device['vrf_lite_cisco']) != 0)) {
    $vrfs_lite_cisco = $device['vrf_lite_cisco'];
} else {
    $vrfs_lite_cisco = array(array('context_name' => null));
}`

I stood this box upon around 18 months ago and its been on nightly updates ever since then.

Sorry to bother but i've spent several hours looking at this tonight and I can't see any reason why the OSPF module won't poll but then again i'm no PHP dev. A manual poller.php run with just the OSPF module with `-d` and `-v` flags doesn't shed any light or throw any errors and neither does the poller log so i'm out of ideas.

**Comment by bmhughes** [comment]
Also to add i've just stood up a test copy of the appliance and it also doesn't appear to be collecting OSPF data either.

**Comment by laf** [comment]
A fix was merged in, please comment back if this isn't fixed still.
