### ISSUE TITLE
add support for enable/disable modules per os

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#4946]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

I wonder if we have that feature already.

If we could deactivate or activate module (discover or poller) in definitions.inc.php per os.
This could speed up all discovery/polling process and eliminate incompatibility issues.

e.g. I have problem with an device os that hangs on storage discover module. So actually I need to deactivate that per device or global.

**Comment by Rosiak** [comment]
I fully agree that this would be a great addition 👍

**Comment by vitalisator** [comment]
I suggest that the override rule should be:
1. global
2. os based
3. device based

so that device based setting overwrite the both other.
The question is how is the best way to implement that. In definitions.inc.php or in the GUI.
In the GUI would make more work and additional table in SQL, but is then user friendly
ideas?

**Comment by laf** [comment]
Feel free to just have users overwrite things in config.php, webui will be too complicated at present.

**Comment by Gorian** [comment]
Might I suggest 

1. defaults
2. global
3. os based
4. device based

Most the defaults are pretty sane, I'd just like an option to have the check_mk agent enabled by default on new hosts

**Comment by vitalisator** [comment]
just to clarify what I mean:

1. defaults (global) - include/defaults.inc.php exist
2. os based - include/definitions.inc.php ToDo
3. device based - GUI (table devices_attribs)  exist

@Gorian, for me sounds that defaults and global are the same.

**Comment by vitalisator** [comment]
Something like that:

$config['os'][$os]['discovery_modules']['storage']              = 1;
in include/definitions.inc.php to activate the storage discovery module under specific os section

$config['os'][$os]['discovery_modules']['storage']              = 0; to deactivate


respective for the poller:
$config['os'][$os]['poller_modules']['stp']              = 1;
$config['os'][$os]['poller_modules']['stp']              = 0;


The question, for me at which place to evaluate that variables. I think it should be the same place at which we  do the device based (database query to devices_attribs) evaluation at the moment.
So we can first evaluate the os based (if exist) and then overwrite it with device based (if exist)

any comments or hints?

**Comment by vitalisator** [comment]
I noticed that we need a option in the GUI to unset (reset) device based poller/discovery.
without that the logic never works.

At the moment we have tree states her:
1. unset (no entry at database)
2. on
3. off

but we have no possibility to unset (delete database entry) in the GUI.
That would means os based module activation would never utilized after the the device based module is once activated.

What means more work :-(
