### ISSUE TITLE
Dashboards menu relocation / auto-hiding feature

### ISSUE THREAD

**Issue by Andreser** [librenms/librenms#4950]
It would be useful for screen real estate reasons to be able to somehow hide / auto hide or relocate the Dashboards menu. That way we would be saving at least 10px for otherwise wasted useful dashboard information.
Maybe it could be moved to the menu bar, where you could select the various dashboards with a drop down menu?
I know it's not pretty, but I'm sure the design can be improved, maybe icons downsized too.
There goes my example idea:
![librenms_menubar_dashb](https://cloud.githubusercontent.com/assets/17357163/20034098/2fd249d8-a391-11e6-82ef-6cf575c304d3.png)

**Comment by f0o** [comment]
You can just append `/bare=yes/` to your URL. That's how we got our NOC screens set with various dashboards in fullscreen

**Comment by Andreser** [comment]
That doesn't work -at least for me- in the general dashboard screen. It does work when viewing a particular device dashboard. 
To clarify, I don't want the "menu bar" hidden, only the "dasboard menu", which I copy-pasted over the right side of the "menu bar" as an example of what could be done with it.

**Comment by laf** [comment]
The navbar has no room for the dashboard features - not everyone has widescreens.

Would be happy to address this in v2.

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #194](https://github.com/librenms/librenmsv2/issues/194) via [**ZenHub**](https://www.zenhub.com/)
