### ISSUE TITLE
API call for Edit Device to add SysContact ID for Alerts

### ISSUE THREAD

**Issue by gugansankar** [librenms/librenms#4954]
I'm unable to find a solution to add mail ID for alerting using API.

My approach is to set separate mail ID for group of devices. For example, DB machines alert goes to DB team, Network device alerts to Network/IT team and so on.

When I checked the docs, it says to add the mail ID in individual device "SysContact" section using Web UI.

But I need to add the mail IDs using API. Is this possible?. If so, please share the link or example api url.

**Comment by laf** [comment]
I totally forget we have a PATCH called to devices so you can do this already: http://docs.librenms.org/API/API-Docs/#api-route-update_device_field

I'll be submitting an update though to allow multiple fields in one go.
