### ISSUE TITLE
Specific OIDs for specific devices

### ISSUE THREAD

**Issue by papage** [librenms/librenms#4959]
Hi all,

This is a feature request. Librenms has the MIB support feature where you can register a MIB with a device and librenmswill poll and graph the mib. This is known to create many useless graphs, and can clog both the librenms server and the devices.

So,I believe it would be useful to have an "Add OID" feature that will be applied on a specific device or device family (sysObjectId match) that will let us graph the particular OIDs that we need. 

For starters, a statement in the config.php file, would do the job and avoid GUI work.

Thank you,
Spiros

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by murrant** [comment]
The MIB graphing is beta.

**Comment by laf** [comment]
Not sure what OID you've tried in mib polling but if you're more specific with it then the most you will get is the table of one type rather than many many responses.

I.e instead of ifEntry you can specify ifAlias to only get the aliases for each interface. You can't get just one interfaces ifAlias (well, I have tested - it might be possible to specify ifAlias.0 for instance - give that a try).

**Comment by papage** [comment]
Hi,

Well my case, was that I needed the dhcp leases and logged in users from a mikrotik,  playing wifi portal.
One OID is casnActiveTableEntries from CISCO-AAA-SESSION-MIB and the other was mtxrDHCPleasecount from microtik MIB. 

These are just examples. There are numerous times where I need a specific OID and would be nice to have an easy way to enable it for a specific device or device group.

I enabled MIB polling and librenms started graphing all the MIB entries, that didn't really make any sense. I'm glad that the "MIB polling" feature exists, even if its beta, but I just thought that enabling specific OIDs would interest many admins and at the same time, it would not be very difficult to implement via config file.

Thanx,
Sp

**Comment by pent1** [comment]
I had to disable CISCO-SUBSCRIBER-SESSION-MIB because of useless graphs it generates.
"add oid" feature would be super useful.

is there any other way to graph only .1.3.6.1.4.1.9.9.786.1.2.1.1.5.1.52690955.1 ??

**Comment by laf** [comment]
What is that oid?

**Comment by pent1** [comment]
its total current BNG session on CISCO IOS-XR
and there is one more usefull oid for activated sessions : 1.3.6.1.4.1.9.9.786.1.2.1.1.5.1.52690955.9

**Comment by laf** [comment]
Can you give the named OID pls.

**Comment by pent1** [comment]
iaf, 
snmpget returns  CISCO-SUBSCRIBER-SESSION-MIB::csubAggStatsUpSessions.physical.52690955.ipDhcpv4Subscriber = Gauge32: 15012 sessions.

if its not what you are asking, please point how should i get named OID.

**Comment by laf** [comment]
Have you tried registering CISCO-SUBSCRIBER-SESSION-MIB::csubAggStatsUpSessions.physical.52690955.ipDhcpv4Subscriber for mib polling?

**Comment by pent1** [comment]
cant figure out which part should I include here:
$extra_mibs = array(
        "csubAggStatsUpSessions" => "CISCO-SUBSCRIBER-SESSION-MIB"
         );
this way I have 200+ oids graphed.

**Comment by laf** [comment]
@paulgear any ideas?

**Comment by paulgear** [comment]
Any chance of access to a device which supports this?  That would make it a lot easier to work out.

But I think if you put "ipDhcpv4Subscriber" there instead of "csubAggStatsUpSessions" it might just work.

**Comment by pent1** [comment]
paul,
not sure about access, but I tried your suggestion and it did not work.

**SNMP[snmptranslate -M /opt/librenms/mibs -IR -m CISCO-SUBSCRIBER-SESSION-MIB CISCO-SUBSCRIBER-SESSION-MIB::ipDhcpv4Subscriber 2>/dev/null]

This doesn't look like a MIB: 
MIB: Could not find CISCO-SUBSCRIBER-SESSION-MIB::ipDhcpv4Subscriber**

maybe you can help to avoid checking of whether it is MIB or not and skip to just snmpget ?

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-specific-oids-for-specific-devices/684

**Comment by MrBlueSkye** [comment]
Bump
