### ISSUE TITLE
[Question] Integrate LibreNMS with OTRS

### ISSUE THREAD

**Issue by huegelc** [librenms/librenms#4960]
Hi,

just wanted to ask if there any plans to integrate LIbreNMS with OTRS (or other Helpdesk solutions) in the future? We do use some legacy OpenNMS installations that can raise a ticket in OTRS but on the long run we want to migrate to LIbreNMS. 
Thank you

**Comment by Rosiak** [comment]
Hi @huegelc,
I recently created osTicket transport support.
If OTRS has an easy REST API I'll be happy to take a look at that too.

**Comment by alythemonk** [comment]
This would be huge. We would be considering this as well at my work where we are looking for this combo of LibreNMS and OTRS ! Thanks. 😄

**Comment by Rosiak** [comment]
@alythemonk Do you have any link for their REST API documentation?

**Comment by alythemonk** [comment]
Yeah its on their site, available in HTML and PDF, check out:

Perl based API: https://otrs.github.io/doc/api/otrs/stable/Perl/index.html
JS based API: https://otrs.github.io/doc/api/otrs/stable/JavaScript/index.html

Hope that this helps ! Thanks.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-integrate-librenms-with-otrs/683
