### ISSUE TITLE
Alerts for deleted device

### ISSUE THREAD

**Issue by x1hash** [librenms/librenms#4969]
I seem to be getting notification alerts relative to a device that is no longer existent, I've configured HipChat based notifications to be sent to a channel (this works flawlessly). However we've run into an issue where a device was reporting as 'down', as the device was no longer required it was removed, however the notifications seem to continue rolling in.

I am presuming because the server was removed prior to the server returning back to normal, the alert is somehow stuck in the database.

====================================

The notification being sent to our channel:

LibreNMS	5:41 PM
Alert for device  - Devices up/down
Severity: critical
Timestamp: 2016-11-10 15:58:26
Unique-ID: 24453
Rule: Devices up/down
Faults:
  #1: sysObjectID => .1.3.6.1.4.1.8072.3.2.10; sysDescr => Linux server2.domain.com 2.6.18-508.el5.lve0.8.89 #1 SMP Sat Oct 22 13:01:40 EDT 2016 x86_64; 
Alert sent to: NOC <>

====================================

LibreNMS automatic daily updates is enabled and working correctly.

librenms]# ./validate.php 
[OK]      config.php tested ok
[OK]      Database connection successful
[OK]      fping has been found
` section of `./validate.php`.

**Comment by laf** [comment]
Your install is massively out of date. Please update before opening issues.

**Comment by laf** [comment]
Feel free to comment once you've updated.
