### ISSUE TITLE
[Question] Avarage packet size per interface possible?

### ISSUE THREAD

**Issue by huegelc** [librenms/librenms#4970]
Hi,

in order to have a more insight look at the interface level, we need to the know the packet sizes. Is there a way to have that included in LibreNMS?
Thank you

**Comment by laf** [comment]
If it's available via snmp it should be, you need to provide more info on the device and also the snmpwalk command we ask for in the request for new OS when creating an issue.

**Comment by huegelc** [comment]
Sorry about that. Here is the info:

Juniper EX/MX/SRX.

```
xxxxx> show snmp mib walk 1.3.6.1.2.1.16.1.1.1 | match 523
etherStatsIndex.523 = 523
etherStatsDataSource.523 = ifIndex.523
etherStatsDropEvents.523 = 0
etherStatsOctets.523 = 28841183
etherStatsPkts.523 = 99493
etherStatsBroadcastPkts.523 = 136
etherStatsMulticastPkts.523 = 70739
etherStatsCRCAlignErrors.523 = 0
etherStatsUndersizePkts.523 = 0
etherStatsOversizePkts.523 = 0
etherStatsFragments.523 = 0
etherStatsJabbers.523 = 0
etherStatsCollisions.523 = 0
etherStatsPkts64Octets.523 = 1473221
etherStatsPkts64Octets.631 = 2439523
etherStatsPkts64Octets.673 = 2439523
etherStatsPkts64Octets.711 = 1635239
etherStatsPkts64Octets.712 = 1635239
etherStatsPkts65to127Octets.523 = 20946
etherStatsPkts128to255Octets.523 = 3770
etherStatsPkts256to511Octets.523 = 155035
etherStatsPkts512to1023Octets.523 = 8395
etherStatsPkts1024to1518Octets.523 = 5860
etherStatsOwner.523
etherStatsStatus.523 = 1

{master:0}
````

**Comment by laf** [comment]
Which value(s) do you want from that list?

We need a full walk from: http://docs.librenms.org/Support/FAQ/#what-information-do-you-need-to-add-a-new-os

**Comment by huegelc** [comment]
I just saw this was addressed https://github.com/librenms/librenms/pull/2125 already but closed due conflicts with ob.

**Comment by laf** [comment]
Don't worry about that, if someone else writes the code it's not an issue.

**Comment by laf** [comment]
No further info provided.
