### ISSUE TITLE
New Device request - Cyberoam CR200iNG

### ISSUE THREAD

**Issue by filipVisko** [librenms/librenms#4973]
This is the firewall we use but are not able to add it to LibreNMS.

Please let me know what other info do you need.

[CYBEROAM-MIB.txt](https://github.com/librenms/librenms/files/583973/CYBEROAM-MIB.txt)

**Comment by laf** [comment]
When you create an issue it has some default text which tells you what we need to add support for a new device/os, please create a new issue and follow those instructions.
