### ISSUE TITLE
Add additional disk support

### ISSUE THREAD

**Issue by laf** [librenms/librenms#4975]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

https://www.reddit.com/r/LibreNMS/comments/5b387n/adding_additional_storage_for_polling/

Use of dskTable which fails:

http://pastebin.com/XXAnCN3i

Adding: disk /mnt/stnerrot 10000
disk /mnt/install 10000
disk /mnt/holding 10000
disk /mnt/backup 10000

Then makes it do:

http://pastebin.com/UgZY7bsy

We should make use of this info as a normal storage poll doesn't pick all partitions up: http://pastebin.com/1h4RzeNU

**Comment by CodaAmok** [comment]
## Updated pastebins with no expiry ##
Use of dskTable which fails: http://pastebin.com/9ELf7usZ
Then makes it do: http://pastebin.com/03LvynhC
We should make use of this info as a normal storage poll doesn't pick all partitions up:  http://pastebin.com/29YHjDbv

**Comment by laf** [comment]
@CodaAmok I've hopefully added support that will now pick up the additional disks, if you fancy giving this pull request a try that would be ace.

**Comment by CodaAmok** [comment]
@laf Thank you... newb question: how do I do that? Is it best to do this on a separate install or if I overwrite my current /opt/librenms setup can I jump back onto master branch easily enough?

**Comment by laf** [comment]
@CodaAmok 

You should be able to do:

```bash
cd /opt/librenms
wget https://patch-diff.githubusercontent.com/raw/librenms/librenms/pull/4993.diff
git apply 4993.diff
```

Then run manual discovery: `./discovery.php -h HOSTNAME -d -m storage`

See if the new disk is detected, if it is then wait 15 mins for graphs. If it isn't post the output of the discovery command above.

To revert just:

```bash
cd /opt/librenms
git stash save
```

**Comment by CodaAmok** [comment]
Great, thanks for all your help! On Reddit you suggested me contributing with code - I'd love to but perhaps money if there's a facility in place for this?

**Comment by laf** [comment]
We don't take money :) We have run an indiego campaign last year and we may at some stage do another but no plans yet. 

https://community.librenms.org/t/would-like-to-help-the-librenms-project/190
