### ISSUE TITLE
[FeatureRequest]Add port group based on pattern

### ISSUE THREAD

**Issue by huegelc** [librenms/librenms#4976]
Hi,

it would be nice if we have a port group feature (like that one for devices) based on pattern like :
````
%macros.device_up = "1" && %ports.ifName = "ae0" 
````
for all aggregated links. 
Right now you are limited on the port description which ports are "Customer/Transit/Peering etc.

Would it be possible to have this implemented?

Thx.

**Comment by laf** [comment]
See our docs, you can write a custom parser to group ports.

**Comment by huegelc** [comment]
I´m afraid you misunderstood me (or I didn´t understood you as I´m not that keen with php).  This means either way I have to edit the port description,right? 
We have about 5000 (aggregated ports) where we cannot change the description that easy. 
A faster way to group this ports are by the port type eg. aggregated interfaces are called aeX (Juniper) (where x stands for the port number) and PoX (Cisco)

It would be much more flexible to have something like the device groups:
```
%macros.device_up = "1"  && %devices.sysName ~ "core" && %ports.ifName  ~  "ae" (or Po)
```
to group all aggregated ports of core switches inside the WebUI.

Please correct me if I´m wrong.

**Comment by laf** [comment]
The custom parser allows you to write your own code to group ports how you like.

**Comment by huegelc** [comment]
You must understand I´m a network guy and not a coder. I looked at the handy feature to group devices based on patterns inside the WebUI and presumed that it would be just like that easy to have this feature based on port types.

**Comment by laf** [comment]
I personally don't see a need for port groups at present.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-add-port-group-based-on-pattern/682
