### ISSUE TITLE
Dell PowerConnect 6024 Switch

### ISSUE THREAD

**Issue by hreeder** [librenms/librenms#4977]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

LibreNMS Version 1.21 from the releases.
Our Dell PowerConnect 6024 switch detects as an Avaya Ethernet Routing Switch, with little more information about it.

Validate.php output
Version isn't detected because the install is from https://github.com/jarischaefer/docker-librenms, which uses [the release](https://github.com/librenms/librenms/archive/1.21.tar.gz) rather than a git clone.
```
LibreNMS Version: 
DB Schema: 148
PHP: 7.0.12-1+deb.sury.org~xenial+1
MySQL: 10.1.18-MariaDB-1~jessie
RRDTool: 1.5.5
SNMP: NET-SNMP 5.7.3
```

Capture Outputs:
[Discovery](https://gist.githubusercontent.com/hreeder/9ab4d9dad56a34133c8d37e5bd7dd174/raw/e495b406bc1ed6b280dbe09b92b0a7f970fa0024/Discovery)
[Poller](https://gist.githubusercontent.com/hreeder/9ab4d9dad56a34133c8d37e5bd7dd174/raw/e495b406bc1ed6b280dbe09b92b0a7f970fa0024/Poller)
[SNMP](https://gist.githubusercontent.com/hreeder/9ab4d9dad56a34133c8d37e5bd7dd174/raw/e495b406bc1ed6b280dbe09b92b0a7f970fa0024/SNMP)

**Comment by Mattz0r** [comment]
If it helps, we have Dell PowerConnect 6248 which are discovered correctly.
