### ISSUE TITLE
Alert template create error

### ISSUE THREAD

**Issue by 21let** [librenms/librenms#4978]
Hello,

I created a template alert, the treatment I always get the error: Error failed to update ... (see. screenshot). If the template edit any text, then přeuložení occasionally lead. I have a template directed at hipchat room, but here my jumps error ERROR 204 or the alert message is empty.

![image](https://cloud.githubusercontent.com/assets/13964136/20236702/24b56a40-a8bd-11e6-96c7-fb6f53089d0b.png)

![image](https://cloud.githubusercontent.com/assets/13964136/20236830/20342a88-a8c2-11e6-8d9d-ef91ef2e6de6.png)

**Comment by laf** [comment]
When you create an issue we have a template of text you need to read and complete. Please open another issue and follow the instructions

**Comment by 21let** [comment]
I am sorry,

I missed the end of the unfinished IF
Thank you
