### ISSUE TITLE
getHostOS() - OS icons don't change to specific logo if OS name ($os) contains capital letters

### ISSUE THREAD

**Issue by czilian** [librenms/librenms#4981]
Dear all,

came across this problem: in order to cater for multiple models of the same brand I started to use OS names ($os) like "advaFSP3kR7" or "advaFSP150GEx". All works except that the custom logo is not updated in the DB and stays 'generic'.
Changing the OS name to all small "advafsp3kr7" (and all the respective references), also the OS icon is properly updated. 
Although I changed everything to small in my branch, it would be nicer being able to also use capital letters in OS names.

Thx
CZ

**Comment by laf** [comment]
`$os` isn't meant to support multiple models, what's the reason you are going down that path?

This may be easier to discuss in irc.

**Comment by czilian** [comment]
the example given refers to two different device types; DWDM and MetroE Switch. Here I guess it's clear. But even within the switch category, different mibs are used and different OIDs within (e.g. PTP timing support for LTE).  I am making use of your new mib folder structure together with the respective OS based scripts in separate files instead of trying to create brand specific larger scripts with many IF conditions to cater for the different types/models. I believe it makes it better manageable. The different devices have different SW release lifecycle. Troubleshooting and extensions are easier done in a smaller context.
Just opened it here under "issue" because it is a small bug. Ok, no more conceptual talk here. Maybe to be continued in IRC. Thx.
