### ISSUE TITLE
EdgeRouter OS Detection Breaks With SNMP Description

### ISSUE THREAD

**Issue by mrjester888** [librenms/librenms#4982]
- Please include all of the information between the Component | Version
LibreNMS  | dd640af53048448381edc69d4fd9517bbace9187
DB Schema | 149
PHP       | 7.0.12
MySQL     | 10.1.18-MariaDB
RRDTool   | 1.5.6
SNMP      | NET-SNMP 5.7.3

- Please provide as much detail as possible.
When a SNMP description is set, discovery detects the OS as generic.  
```
set service snmp description "any text"

./discovery.php -h <host> -d -m os

SQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`message`)  VALUES ('6','6','NULL','system',NOW(),'Device OS changed edgeos => generic')]
SQL[UPDATE `devices` set `os` ='generic' WHERE device_id='6']
Changed OS! : generic
SQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`message`)  VALUES ('6','6','NULL','system',NOW(),'Device Icon changed edgeos => generic')]
SQL[UPDATE `devices` set `icon` ='generic' WHERE device_id='6']
Changed Icon! : generic'
```
When SNMP description is removed, discovery detects the OS as edgeos

```
delete service snmp description

./discovery.php -h <host> -d -m os

SQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`message`)  VALUES ('4','4','NULL','system',NOW(),'Device Icon changed generic => edgeos')]
SQL[UPDATE `devices` set `icon` ='edgeos' WHERE device_id='4']
Changed Icon! : edgeos
```

Tested on ER-Pro and ER-X with the same behavior.

**Comment by laf** [comment]
I've added an FAQ entry for this as we can't fix this other than trying to use sysObjectID's for detection. For some reason UBNT have decided that setting that value will have it override sysDescr which I've not seen before.
