### ISSUE TITLE
Long discovery and polling times on Enterasys N7 Switches

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#4988]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

I have noticed that the discovery and polling times of our Enterasys switches based on the N7 plartform have increased significantly since around the 13th of October after updating our install. The polling times were as high as 999 seconds according to the poller log, until we modified the value of the "Max repeaters" to be 50 which improved matters. However the polling times are still fairly highcompared to what they used to be; which was not above 2 minutes, as shown below. The problematic switches have a lot of virtual interfaces which I am not sure is a contributing factor to this issue.

![snap4](https://cloud.githubusercontent.com/assets/16717388/20266592/7d10ed54-aa7f-11e6-8c73-d10fbcf62150.png)
![snap8](https://cloud.githubusercontent.com/assets/16717388/20266926/ead38b52-aa80-11e6-8f8a-7c963a579989.png)
![snap7](https://cloud.githubusercontent.com/assets/16717388/20266621/a9289a54-aa7f-11e6-8366-fe6f38f16c0a.png)
![snap2](https://cloud.githubusercontent.com/assets/16717388/20266643/c96b865a-aa7f-11e6-97c4-80655a221364.png)
![snap5](https://cloud.githubusercontent.com/assets/16717388/20266625/afff8860-aa7f-11e6-8641-71cccbb73d45.png)
![snap1](https://cloud.githubusercontent.com/assets/16717388/20266651/d300560a-aa7f-11e6-8091-42f9bdc4a24e.png)

The output of the discovery command gets stuck on the output as shown below,
![snap6](https://cloud.githubusercontent.com/assets/16717388/20266808/77612b66-aa80-11e6-8866-b006d30b4cd3.png)

**Comment by laf** [comment]
I'm struggling to see most of the info in those pictures. The polling time graph is missing the legend so you can't see what module is taking the longest.

We will also need the output of `./poller.php -h DEVICE -r -f -d`

**Comment by breeman1** [comment]
Sorry about that, I had compressed the images to save bandwidth.
![snap7](https://cloud.githubusercontent.com/assets/16717388/20303465/2981f5d8-ab34-11e6-914f-423bf0f87dd0.png)
![snap2](https://cloud.githubusercontent.com/assets/16717388/20303469/30420f2a-ab34-11e6-9542-11b56cf45e7c.png)
![snap5](https://cloud.githubusercontent.com/assets/16717388/20303480/3b9d11a8-ab34-11e6-8913-02cec30296d2.png)
![snap1](https://cloud.githubusercontent.com/assets/16717388/20303483/3e6056b6-ab34-11e6-872f-42f15ba1c95e.png)
The discovery command stops at this screen
![snap6](https://cloud.githubusercontent.com/assets/16717388/20303665/28e21350-ab35-11e6-8f57-1f237d1281d1.png)

Here's the output of the poller command,
[poller_device.zip](https://github.com/librenms/librenms/files/591739/poller_device.zip)

**Comment by laf** [comment]
So a few things.

Check logs/daily.log to see what version you went from and to at the time of the increase so we can see what was changed. It would also be good to get the same info when the times decreased again.

Have you enabled any additional support like influxdb at that time?

Are you sure that 50 for max repeaters is ok? You should time the results of a query with varying numbers to see as 50 could give negative performance.

For now, if you don't need things like stp / osp info then I'd suggest disabling those.

Any software updates to the device? Check eventlog again around the time of the increase to see.

**Comment by breeman1** [comment]
Since our Production instance is an offline install; I normally issue a git pull from an internet connect machine and update the offline (Production server) install by running rsync between the two servers and issuing a `./daily.sh post-pull` command to update. I suspect this is the reason I cannot see the version information that you refer to in the daily.log, see below.
![snap5](https://cloud.githubusercontent.com/assets/16717388/20482682/9f73a360-aff6-11e6-87c8-0e622b20841e.png)

I do not have influxdb enabled so I doubt that is an issue.
I have set the max-repeaters value to 35 after having tried 10, 20 and 30 with 10 being the worst in terms of not seemingly changing anything in poller duration figures. I get more or less the same results with this value set at 35 as compared to when it was set at 50.
![snap4](https://cloud.githubusercontent.com/assets/16717388/20483412/9574098c-affa-11e6-9865-444f78a89ddf.png)
I have turned off STP however I noticed that there is a STP tab showing on the GUI for this device.
![snap1](https://cloud.githubusercontent.com/assets/16717388/20483430/a7fb88c8-affa-11e6-8297-831846235115.png)
![snap9](https://cloud.githubusercontent.com/assets/16717388/20483609/9ef407ea-affb-11e6-941b-0241aaa09f46.png)

No software updates were done on these devices.
I noticed recently that upon issuing the `./daily.sh post-pull` the output has some warning relating the piece of code that was suggested to me by @murrant on issue no: #3263. 
![snap2](https://cloud.githubusercontent.com/assets/16717388/20483864/0c0da718-affd-11e6-9eef-9106cdb3511d.png)
Here is that code;
![snap3](https://cloud.githubusercontent.com/assets/16717388/20483789/a920273e-affc-11e6-89eb-a6f39f307cd6.png)
Is this code still relevant or has it been catered for in some other part of the application?

**Comment by laf** [comment]
You could be interested in checking out #5805

**Comment by breeman1** [comment]
Hi @laf 
How do I easily apply this patch without doing the copy and paste which is undesirable?

**Comment by laf** [comment]
Instructions in https://community.librenms.org/t/looking-for-testers-for-port-polling-update/524

**Comment by breeman1** [comment]
I cannot seem to connect to this branch, see below.
![image](https://cloud.githubusercontent.com/assets/16717388/22744110/07551d94-ee25-11e6-98ab-9cbe094dace8.png)

**Comment by laf** [comment]
use https://github.com/laf/librenms.git instead of git@github.com:/laf/librenms.git

**Comment by breeman1** [comment]
Ok, the patch is implemented now around the time shown by an arrow in the graph below. I will leave it runnig for about a week or so to if it improves the polling times of this switch;
![image](https://cloud.githubusercontent.com/assets/16717388/22788878/ea29b37c-eee9-11e6-8a87-a27d31ed7b2b.png)

**Comment by breeman1** [comment]
@laf it does not look like it is having a desired effect in my case. The poller time still shows an almost 800 seconds peak even after the change, see below with an arrow showing the time we made the change yesterday,
![image](https://cloud.githubusercontent.com/assets/16717388/22817148/3fe3ca26-ef6e-11e6-9a63-f46dd22bb6b2.png)
What is also picked up is that a whole lot of ports which were down are longer shown in the Device Overview screen. Is this an expected behavior of the patch? These ports show as deleted under the "Ports" -> "Deleted" main menu. As can be seen on the screenshot below, a number of ports that are down 127 however only 3 are shown in an Overview page.
![image](https://cloud.githubusercontent.com/assets/16717388/22817267/e1735b54-ef6e-11e6-8f03-8cfbe9497351.png)
Lastly, how do I revert/remove the patch seamlessly?

**Comment by breeman1** [comment]
I managed to revert the patch and I see that the previously down interfaces which were missing are now back.
![image](https://cloud.githubusercontent.com/assets/16717388/22817905/c56736b6-ef72-11e6-9ead-9e2395479302.png)

**Comment by laf** [comment]
I think you'll need to get us the output we ask for in point 3 to take this further.

**Comment by breeman1** [comment]
Which info you asked did I not provide?

**Comment by laf** [comment]
Everything listed in point 3 link at the top in the first issue.

**Comment by breeman1** [comment]
Hi @laf ,
Here is the output of this command, could not load them on pastebin because of size.

[enterasys_ho_discovery.txt](https://github.com/librenms/librenms/files/773939/enterasys_ho_discovery.txt)
[enterasys_ho_poller.txt](https://github.com/librenms/librenms/files/773940/enterasys_ho_poller.txt)
The discovery command above stalls at this line `SNMP[[0;36m/usr/bin/snmpbulkwalk -Cr10  -v2c -c COMMUNITY -OQUs --hexOutputLength=0 -m Q-BRIDGE-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 dot1qVlanCurrentEgressPorts[0m]` and does nothing for hours; I literally had to kill it after a few hours. I think it this behavior that is the cause of the message about the discovery process not completing in time; see below,
![snap11](https://cloud.githubusercontent.com/assets/16717388/22927910/5926c302-f2bc-11e6-8645-0c1e1244441b.png)
 
The snmpbulkwalk command does not seem to work for some reason; see below,
![snap9](https://cloud.githubusercontent.com/assets/16717388/22927694/73df83ec-f2bb-11e6-94ff-2bc7596999f1.png)

Let me know should you need additional information.

**Comment by laf** [comment]
I assume you get the same results if you run that command directly?

**Comment by breeman1** [comment]
By directly I assume you mean running the command from where the file is installed?
![snap13](https://cloud.githubusercontent.com/assets/16717388/22928532/a1da26fe-f2bf-11e6-915b-0a84c53f004b.png)
![snap14](https://cloud.githubusercontent.com/assets/16717388/22928536/a3b75e60-f2bf-11e6-9508-ba896a002b6b.png)

**Comment by laf** [comment]
No this one: `/usr/bin/snmpbulkwalk -Cr10 -v2c -c COMMUNITY -OQUs --hexOutputLength=0 -m Q-BRIDGE-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 dot1qVlanCurrentEgressPorts`

**Comment by breeman1** [comment]
Ok, here's the output;
[dot1qVlanCurrentEgressPorts.txt](https://github.com/librenms/librenms/files/774100/dot1qVlanCurrentEgressPorts.txt)
I ran the command like this and I see the file is just growing and growing. 
![snap15](https://cloud.githubusercontent.com/assets/16717388/22929710/ba555842-f2c5-11e6-8f9e-a50f1e4612e9.png)

**Comment by laf** [comment]
I'd suggest you disable the vlan discovery module on these devices.

**Comment by breeman1** [comment]
Hi @laf ,
The network team disabled snmp on this device as it could not bear the load. It literally caused the CPU to run at about 80% to 90% and thus affected the switch traffic throughput including causing random traffic discards. 

Fortunately we have another model which is exactly the same but with far fewer VLANs and ports configured. However this switch displays exactly the same behavior to that of the original one in that discovery does not finish, even when the VLAN module is turned off. I had to stop the `/usr/bin/snmpbulkwalk -OUneb -v2c -c` and the `/usr/bin/snmpbulkwalk -Cr10 -v2c -c community -OQUs --hexOutputLength=0 -m Q-BRIDGE-MIB -M /opt/librenms/mibs` commands as the files I am piping their outputs to just kept on growing and growing; here's the truncated outputs for your reference.

[entera_snmpbulk_N7.txt](https://github.com/librenms/librenms/files/803638/entera_snmpbulk_N7.txt)
[dot1qVlanCurrentEgressPorts_N7_truncated.txt](https://github.com/librenms/librenms/files/803625/dot1qVlanCurrentEgressPorts_N7_truncated.txt)
[entera_discovery_N7.txt](https://github.com/librenms/librenms/files/803626/entera_discovery_N7.txt)
[entera_poller_N7.txt](https://github.com/librenms/librenms/files/803627/entera_poller_N7.txt)

This issue looks to be affecting the N-series Enterasys switches as the above commands work as intended on the C-series range. The polling times on this switch are quite acceptable though;
![snap17](https://cloud.githubusercontent.com/assets/16717388/23362005/456d2096-fcfc-11e6-8189-a5bf28e9dfe5.png)
![snap18](https://cloud.githubusercontent.com/assets/16717388/23362010/4afb3728-fcfc-11e6-9b34-861360285833.png)
![snap19](https://cloud.githubusercontent.com/assets/16717388/23362013/4e2ced2e-fcfc-11e6-8c16-6d20816b3961.png)

**Comment by laf** [comment]
That's really odd as /usr/bin/snmpbulkwalk -Cr10 -v2c -c community -OQUs --hexOutputLength=0 -m Q-BRIDGE-MIB -M is only run with the vlan discovery module enabled - are you sure you have switched this off?

**Comment by laf** [comment]
In fact definitely not, your discovery output shows the vlan module is enabled so turning that off will help here.

It would be worth speaking to Enterasys to ask them why the device is responding back with so much data for that query.

**Comment by laf** [comment]
No response so closing off. Please provide any updated information.
