### ISSUE TITLE
Devices grouping

### ISSUE THREAD

**Issue by 21let** [librenms/librenms#4989]
Missing the ability to add devices to the group. Device Group to not being addressed. It would be appropriate to add devices into groups, eg. In accordance behalf of clients or departments.

**Comment by laf** [comment]
I've struggled to understand what the question is here, but if it's can we add devices to groups then you do that by defining device groups, new ones which match will be auto added.

If you are asking to have some form of button to add to an existing device group then this isn't something we should support imho. Device groups are meant to be dynamic.

**Comment by 21let** [comment]
I'm sorry (google translator) :-)

Yes, I would like to add devices to groups, but through key, as is the case with other surveillance systems. I can create any number of groups, and to them via a button or bulk add certain devices.

The current solution groups is incomprehensible to me when I have a group to create rules and then rely on the fact that the device is added to the group. In my better when I get over groups overview.

**Comment by laf** [comment]
We try and avoid users having to manually set things up so the group works by creating rules and does work well once you try a few rules.

The only way I see us having something were users add devices to groups is for setting things like group snmp details but that may be restricted to a single group per device.

**Comment by 21let** [comment]
I tried, but it is not correct. Pity must ever come a time when even adding to the groups do not dynamically :-) Thank you very much for your time and explanations.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-devices-grouping/681
