### ISSUE TITLE
Canon ir3325i - counter + resolved IP?

### ISSUE THREAD

**Issue by 21let** [librenms/librenms#4990]
![image](https://cloud.githubusercontent.com/assets/13964136/20273420/7fc572a6-aa91-11e6-8c30-9b09f7138368.png)

At Canon IR3325i I not see Resolved IP. This printer can also see an overview of the toners, printer how many copies (counter)?

**Comment by laf** [comment]
For the IP, run this in your bash shell (but replace the domain name with the devices hostname):

```bash
php -r "print_r(dns_get_record('lathwood.co.uk', DNS_A));"
```

We already have a request for page count (#3407)

**Comment by Rosiak** [comment]
No further info, closing.
Feel free to reopen.
