### ISSUE TITLE
Apache SNMP extend not working - fix proposal

### ISSUE THREAD

**Issue by mevertse** [librenms/librenms#4995]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php`.
LibreNMS  | 5f8e5e7d3a8b0c877a6d32e1404df468e34db5bf
DB Schema | 149
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [X] Please provide as much detail as possible.

Enabling Apache as application and adding it to the SNMP config like to docs explain, gives no results. The graphs remain empty.
Running poller.php with debug shows that now results are returned, also the script is not started through snmp, as can be seen by the last modified time on /tmp/apache-snmp.

We can find the OID:
snmptranslate -On NET-SNMP-EXTEND-MIB::nsExtendOutputFull.\"apache\"

Which results in:
.1.3.6.1.4.1.8072.1.3.2.3.1.2.6.97.112.97.99.104.101

After updating includes/polling/applications/apache.inc.php with this OID the graphs are filling with information. Only the 'Hits' graph remains empty, still working on this one.

**Comment by laf** [comment]
What does: `/etc/snmp/apache-stats.py` show?

**Comment by mevertse** [comment]
/etc/snmp/apache-stats.py
379921
3050015744
.00110412
1229942
.308893
2479.8
8028.03
1
9
9
0
0
1
0
0
0
0
0
0
140

**Comment by florianbeer** [comment]
Is the librenms user allowed to execute /etc/snmp/apache-stats.py ?

**Comment by mevertse** [comment]
Yes, we are receiving the stats in LibreNMS after changing the proposed OID.
We are missing 'Hits', the other graphs are working.

**Comment by laf** [comment]
Using the oid shouldn't be needed as the translation from name to oid should work (assuming it's correct).

**Comment by mevertse** [comment]
The original file had:
nsExtendOutputFull.6.97.112.97.99.104.101

So it was already without the name 'apache'. I tried with nsExtendOutputFull."apache" and that is not working yet.

**Comment by Tawmu** [comment]
I'm also seeing this issue with a brand new LibreNMS install from this morning.

**Comment by laf** [comment]
This doesn't appear to be an issue and is working as expected. Please update both librenms, the librenms-agent scripts and ensure that snmpd.conf isn't restricted.
