### ISSUE TITLE
APC AP7722 01 missing current graph

### ISSUE THREAD

**Issue by stokbaek** [librenms/librenms#5007]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

Hello our older APC AP7722 01 is missing current graph. This means we getting a draw error on the overview window. Our newer APC devices are working fine.

[discovery.txt](https://github.com/librenms/librenms/files/594480/discovery.txt)
[poller.txt](https://github.com/librenms/librenms/files/594482/poller.txt)
[snmpwalk.txt](https://github.com/librenms/librenms/files/594483/snmpwalk.txt)

**Comment by laf** [comment]
Odd with this one.

Either.

  - The device doesn't support the data we expect to see.
  - The snmpwalk wasn't complete.
  - It uses a different oid.

Can you get the output of: `./discovery.php -h HOSTNAME -d -m sensors` and pastebin the output pls.

**Comment by stokbaek** [comment]
It comes with some MIBs that couldn't be found. I included them in the pastebin.

http://pastebin.com/ezaBq0nz

**Comment by laf** [comment]
Not sure what you mean by that but I still don't see the output we expect.

The snmpwalk command shouldn't need mibs and would just walk the entire tree.

**Comment by laf** [comment]
Any further info?

**Comment by stokbaek** [comment]
Sorry if I missed something. But what more information do I need to supply. I can see the MIB errors only happens if I run the command and pipe output into file. I have made a new pastebin link without the MIB errors as this does not seem to have anything with the issue at hand.

http://pastebin.com/f8JEcQL0

**Comment by laf** [comment]
The outputs from before didn't contain the information we expect to see for APC devices. I've not checked the latest paste

**Comment by laf** [comment]
pastebin has been removed :(
