### ISSUE TITLE
Email alerts not working with AD authentication

### ISSUE THREAD

**Issue by SKUZ-ee** [librenms/librenms#5012]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
==========================================================
Component | Version
--------- | -------
LibreNMS  | c46de37197b7b7db70f50c5ef7a3f00c423789f4
DB Schema | 150
PHP       | 5.5.9-1ubuntu4.20
MySQL     | 5.5.49-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2
==========================================================

- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

Email alerts stops working when AD authentication is enabled. Eventlog gives the following error: Could not issue critical alert for rule 'Service up/down' to transport 'mail' Error: You must provide at least one recipient email address. This error is encountered on both my Librenms test boxes running Ubuntu 14.04 and 16.04.

Doing a test mail transport, it is able to send the test mail to all users in the AD group. Even with only one user being a member of the AD group, no alerts are sent.

The setup is the following: A "Networking" AD group contains three user accounts each with assigned email addresses.
In config.php, the following is added: $config['auth_ad_groups']['Networking']['level'] = 10;

Alerting settings: https://drive.google.com/open?id=0B8WCN9DjlJUca1pXajQxYXNGMlk
Alert capture: https://drive.google.com/open?id=0B8WCN9DjlJUcYkw4X3JMaUZFek0
Alert rules: https://drive.google.com/open?id=0B8WCN9DjlJUcNENsSGd6VWdDYTg

**Comment by bjorntimmer** [comment]
I've got exactly the same issue. When doing an alert capture it sees the mail addresses but it's not sending out the mails to the admins. Sending alerts to the syscontact is working.
