### ISSUE TITLE
Router discovered 8 times

### ISSUE THREAD

**Issue by athompso** [librenms/librenms#5025]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

```
Component | Version
--------- | -------
LibreNMS  | e469aa97b002d6df61b95936bb712389e058c9d7
DB Schema | 151
PHP       | 7.0.12
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
```

What I'm seeing is that one of the core routers, which has two VRFs and multiple IP addresses, is being multiply-discovered and so far I have eight (8) instances of it that aren't being merged.  See screencap, attached.
![image](https://cloud.githubusercontent.com/assets/887417/20457648/46560b12-ae55-11e6-908b-92dbe6c72fed.png)
My understanding is that this should be autodetected and these should all be one device.

**Comment by laf** [comment]
set `$config['allow_duplicate_sysName'] = false;`

**Comment by Rosiak** [comment]
I belive @laf comment solves this.
