### ISSUE TITLE
Add support for DCN switches

### ISSUE THREAD

**Issue by kamils85** [librenms/librenms#5031]
**Add support for DCN switches. Unfortunately I cannot find anywhere how the OS is called...**

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.

Component | Version
--------- | -------
LibreNMS  | 42123010c821b54b13601e2d53dc16253e53264e
DB Schema | 151
PHP       | 7.0.8-3ubuntu3
MySQL     | 10.0.25-MariaDB-1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

http://www.dcnglobal.com/index.html

discovery, poller and snmpwalk attached
[DCN support.txt](https://github.com/librenms/librenms/files/603424/DCN.support.txt)
![dcn](https://cloud.githubusercontent.com/assets/23239006/20481538/eba77d2e-afe7-11e6-8cc3-d1535e06e1c8.png)

> SWS4#sh version 
>   S4600-52P-SI Device, Compiled on Jun 06 16:24:54 2016
>   sysLocation xxx
>   CPU Mac 00:03:0f:64:40:dd
>   Vlan MAC 00:03:0f:64:40:dc
>   SoftWare Version 7.0.3.5(R0241.0101)
>   BootRom Version 7.2.16
>   HardWare Version 1.0.1
>   CPLD Version N/A
>   Serial No.:SW045010FB16000330
>   Copyright (C) 2001-2016 by Digital China Networks Limited.
>   All rights reserved
>   Last reboot is cold reset.
>   Uptime is 16 weeks, 3 days, 13 hours, 20 minutes
> SWS4#
> 

> SWS4#sh vendor
> NAME            LEN          VALUE
> ------------    -----        ------------------------------
> SwitchName      12           S4600-52P-SI 
> VersionPre      0             
> VendNameEn      30           Digital China Networks Limited 
> VendNameBr      3            DCN 
> VendWWW         28           http://www.dcnetworks.com.cn 
> VendLocate      5            China 
> CopyRight       58           Copyright (C) 2001-2016 by Digital China Networks Limited. 
> VendContact     12           400-810-9119 
> WebLogo         2729         
> WebLogin        8683         
> WebFacebd       21104        
> WebBG           14685        
> WebLang         2            cn 
> VendorOid       16           1.3.6.1.4.1.6339 
> DeviceOid       26           1.3.6.1.4.1.6339.1.1.1.280 
> KeyNeed         4            0 
> BaseMac         6            00 03 0f 03 00 00 
> CliStyle        3            0 
> HsrpNeed        4            0 
> DevType(ID)     4            280 
> ChassisCard     0             
> FileVersion     7            10.9.11 
> IMGPrefix       0             
> RomPrefix       0             
> HardWarePre     0             
> Prompt          0             
> UserName        0             
> PassWord        0             
> ManageIP        0            
> NeedLicense     6            NO

**Comment by laf** [comment]
The snmpwalk needs to have certain params passed, can you please re-run this:

`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .`

**Comment by kamils85** [comment]
That's the snmpbulkwalk result attached below.

[dcn-snmpbulkwalk.txt](https://github.com/librenms/librenms/files/603715/dcn-snmpbulkwalk.txt)

**Comment by kamils85** [comment]
Just managed to get the MIB from the distribution. Attached below.

[DCN_private_2.1.32.mib.zip](https://github.com/librenms/librenms/files/604316/DCN_private_2.1.32.mib.zip)

**Comment by laf** [comment]
What 'os' would you say these run? We need a name that is not typically the vendor name.

**Comment by kamils85** [comment]
According to the DCN Partner, the OS it's called "SoftWare" (and the show version confirms that).
Because the name is very generic, I would recommend to use "dcn-software" as the OS name?

If I find the proper name (if there is one...) I will open a new request to change it.

**Comment by kamils85** [comment]
Anything else I can provide to get this added to LibreNMS?

Thanks
