### ISSUE TITLE
Dependencies missing in init.php

### ISSUE THREAD

**Issue by khumche** [librenms/librenms#5039]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [X] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | 7e578d5e9d3b4a91044d2c5fb58ee67605f744c7
DB Schema | 151
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

After the last commit, Junos polling is broken, because the init.php is missing a require

I made a fix here
https://github.com/khumche/librenms/commit/7e578d5e9d3b4a91044d2c5fb58ee67605f744c7

PHP Fatal error:  Uncaught Error: Call to undefined function rewrite_junos_hardware() in /opt/librenms/includes/polling/os/junos.inc.php:10
Stack trace:
#0 /opt/librenms/includes/polling/os.inc.php(5): include()
#1 /opt/librenms/includes/polling/functions.inc.php(260): include('/opt/librenms/i...')
#2 /opt/librenms/poller.php(134): poll_device(Array, Array)
#3 {main}
  thrown in /opt/librenms/includes/polling/os/junos.inc.php on line 10

**Comment by murrant** [comment]
Thanks for the quick report.  A fix will be merged shortly.

I'd let you merge it in, but since this is time sensitive, I'll get it pushed.
