### ISSUE TITLE
Trying to update

### ISSUE THREAD

**Issue by robgnet** [librenms/librenms#5041]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

librenms@librenms:~$ sh daily.sh
PHP Notice:  Undefined index: install_dir in Command line code on line 1
daily.sh: 152: daily.sh: Syntax error: redirection unexpected
librenms@librenms:~$

**Comment by Lucheni** [comment]
Another case here but with the **GUI not functioning.**

**./daily.sh (as librenms user) gives:**
-bash-4.1$ ./daily.sh
PHP Parse error:  syntax error, unexpected '[' in /opt/librenms/lib/influxdb-php/vendor/guzzlehttp/psr7/src/functions.php on line 77
Updating SQL-Schema                                FAIL
Updating submodules                                OK
Cleaning up DB                                     FAIL
Fetching notifications                             FAIL

**validate (as root ) gives**:
[root@host librenms]# ./validate.php
PHP Parse error:  syntax error, unexpected '[' in /opt/librenms/lib/influxdb-php/vendor/guzzlehttp/psr7/src/functions.php on line 77
