### ISSUE TITLE
Don't show other user's device groups in menu

### ISSUE THREAD

**Issue by florianbeer** [librenms/librenms#5045]
Component | Version
--------- | -------
LibreNMS  | ccb76a7de9f2d4e34938d9b78d38328aee7addcd
DB Schema | 151
PHP       | 5.6.28-1~dotdeb+7.1
MySQL     | 5.5.53-0+deb7u1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.4.3

Given multiple device groups for different "Normal users" (customers) they can see other user's device groups in the menu. Seems the permissions are only set on device level and not for the menu:

* Overview > Maps > Device Groups Maps
* Devices > Device Groups

**Comment by laf** [comment]
We don't have permissions for device groups, users can't get to the devices within them though.

**Comment by florianbeer** [comment]
Sure, they can't see devices they don't have permissions for. But I'd rather not have different customers see who else is using my monitoring system via the groups menu. Even if it leads to an empty devices page.

**Comment by bpetit** [comment]
Would it be possible, as an alternative, to create settings that permit or prohibit a specific user to view the device groups and the device groups map items ? It would be nice for the plugins item too.

Thanks

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-dont-show-other-users-device-groups-in-menu/680
