### ISSUE TITLE
OpenBSD wrong Uptime

### ISSUE THREAD

**Issue by stanley71** [librenms/librenms#5047]
Component | Version
--------- | -------
LibreNMS  | 6708c7cb8127035e48fbd5e9684daa901c744fc4
DB Schema | 151
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

In the devices lists OpenBSD's uptimes are wrong (46yrs+)
After running 
./poller.php -r -f -m os  -h [HOSTNAME] -d
I see:
snmpEngineTime.0 = 1479826906
hrSystemUptime.0 = 640800

Using hrSystemUptime (6408s)
hrSystemUptime or sysUpTime looks like to have rolled, using snmpEngineTime insteadRRD[update /opt/librenms/rrd/[hostname]/uptime.rrd N:1479826906]
[RRD Disabled]Uptime: 46 years, 337 days, 15h 1m 46s
Modules status: Global+ OS  Device  
#### Load poller module os ####
Hardware: amd64
Version: 6.0
Features: GENERIC#2148
Serial: 

How do I get the right uptime?

**Comment by laf** [comment]
We need the output of poller.php as a pastebin or similar

**Comment by stanley71** [comment]
http://pastebin.com/NRv91KfA

**Comment by alythemonk** [comment]
I also have the exact same problem with two openbsd boxes. I expect a few more at work will have the same problem when monitoring shifts to librenms

**Comment by Rosiak** [comment]
Looks to me like snmpEngineTime returns the actual time, rather than the uptime.
Smells like OpenBSD/SNMPD bug.

**Comment by laf** [comment]
Assuming my sleepy brain did this right, please test this patch:

```
diff --git a/includes/polling/core.inc.php b/includes/polling/core.inc.php
index 0473f8d..1e8cf05 100644
--- a/includes/polling/core.inc.php
+++ b/includes/polling/core.inc.php
@@ -43,7 +43,7 @@ if (empty($uptime)) {
     }//end if
 }//end if

-if ($device["os"] != "edgeswitch") {
+if (starts_with($device['os'], array('edgeswitch', 'openbsd')) === false) {
     if ($snmp_uptime > $uptime && is_numeric($snmp_uptime)) {
         $uptime = $snmp_uptime;
         d_echo('hrSystemUptime or sysUpTime looks like to have rolled, using snmpEngineTime instead');

```

**Comment by stanley71** [comment]
This works as a charm!
Created a /opt/librenms/uptimepatch with your patch as body
Then ran git apply uptimepatch
And after a refresh the correct time was showed in the webgui.
Thanks Laf!

**Comment by alythemonk** [comment]
This is awesome. I'll give it a shot later today or verify when it's part of the daily build. Thanks LAF !



[https://d3pv4gq91q59qh.cloudfront.net/images/6624/30748/images/566758f91e829.jpeg?override=1449614636]
Aly S Dharshi           B.Sc. Computer Science, RHCE


Technology Strategist


m. 780 722 3461                 t. 780 428 5226


e. aly@dharshi.ca<mailto:aly@dharshi.ca>                w. alydharshi.com<https://esig.ly/links/170277>



[https://d3pv4gq91q59qh.cloudfront.net/images/6624/30748/icons/566759f7239bf.png]<https://esig.ly/links/170280>         [https://d3pv4gq91q59qh.cloudfront.net/images/6624/30748/icons/566759f7439f5.png] <https://esig.ly/links/170282>                [https://d3pv4gq91q59qh.cloudfront.net/images/6624/30748/icons/56679c968bad4.png] <https://esig.ly/links/170304>




If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

[https://d3pv4gq91q59qh.cloudfront.net/images/6624/30748/icons/leaf-icon-sml.gif]Think before you print.




On Dec 2, 2016, at 3:39 AM, Stanley van Dijk <notifications@github.com<mailto:notifications@github.com>> wrote:


This works as a charm!
Created a /opt/librenms/uptimepatch with your patch as body
Then ran git apply uptimepatch
And after a refresh the correct time was showed in the webgui.
Thanks Laf!

-

**Comment by laf** [comment]
@stanley71 when #5111 is merged in you will need to run (as librenms user) `git checkout includes/polling/core.inc.php` then `./daily.sh`

**Comment by stanley71** [comment]
@laf Thanks. I've done the command you gave and updated. This is working!
