### ISSUE TITLE
LibreNMS GUI not opening

### ISSUE THREAD

**Issue by mail3dexter** [librenms/librenms#5052]
Hello Guys,

One of my LibreNMS servers are down. When I try to open its GUI via IP address or via FQDN, it opens as blank page.
Upon checking httpd error_log and access_log, I found nothing. However when I tried checking daily.log I saw this error:

PHP Parse error:  syntax error, unexpected '[' in /opt/librenms/lib/influxdb-php/vendor/guzzlehttp/psr7/src/functions.php on line 77 

I ran daily.sh and validate.php manually and got this error:

[a@librenms]$ sudo ./daily.sh
PHP Parse error:  syntax error, unexpected '[' in /opt/librenms/lib/influxdb-php/vendor/guzzlehttp/psr7/src/functions.php on line 77
Updating SQL-Schema                                FAIL
Updating submodules                                OK
Cleaning up DB                                     FAIL
Fetching notifications                             FAIL

[a@librenms-adc librenms]$ sudo ./validate.php
PHP Parse error:  syntax error, unexpected '[' in /opt/librenms/lib/influxdb-php/vendor/guzzlehttp/psr7/src/functions.php on line 77

I have other servers and all are running same PHP version and HTTPd version, dont know why this has come up with this server only.

[a@librenms-adc librenms]$ httpd -v
Server version: Apache/2.2.15 (Unix)
Server built:   Nov 18 2016 23:48:55
[a@librenms-adc librenms]$ php -v
PHP 5.3.3 (cli) (built: Aug 11 2016 20:33:53)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

**Comment by mail3dexter** [comment]
This got solved.
I manually did git pull and found there were lots of files not updated. I think the auto-update feature somehow got broke in between while updating files hence not all files were updated.

[a@librenms-adc librenms]$ sudo git pull
remote: Counting objects: 59, done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 59 (delta 25), reused 3 (delta 3), pack-reused 2
Unpacking objects: 100% (59/59), done.
From https://github.com/librenms/librenms
   0da39d9..2fdcf93  laf-patch-1 -> origin/laf-patch-1
   f488e0b..db240cb  master     -> origin/master
Updating f488e0b..db240cb
Fast-forward
 .codeclimate.yml                              |   10 +-
 discovery.php                                 |    4 +-
 html/ajax_search.php                          |    4 +-
 html/graph.php                                |   12 ++--
 html/includes/common/availability-map.inc.php |   18 ++--
 html/includes/common/eventlog.inc.php         |    2 +-
 html/includes/print-menubar.php               |    1 -
 html/includes/table/eventlog.inc.php          |    5 +-
 html/index.php                                |    6 +-
 html/pages/eventlog.inc.php                   |   10 +-
 includes/dbFacile.php                         |  101 +++++-----------------
 includes/definitions.inc.php                  |   27 ++++--
 includes/discovery/functions.inc.php          |    2 +-
 includes/functions.php                        |  113 +++++++++++++++++++++++++
 includes/init.php                             |   10 +--
 includes/polling/functions.inc.php            |    4 +-
 includes/snmp.inc.php                         |   19 ++--
 poller.php                                    |    8 +-
 tests/bootstrap.php                           |    1 -
 19 files changed, 209 insertions(+), 148 deletions(-)
[a@librenms-adc librenms]$ sudo ./validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | db240cb4eb2a70507e1d746e3a832fb24a741d31
DB Schema | 151
PHP       | 5.3.3
MySQL     | 5.1.73
RRDTool   | 1.3.8
SNMP      | NET-SNMP 5.5
========================================================== 

Was this the right way to fix this?

**Comment by laf** [comment]
Yes that's fine, broken update the other day.
