### ISSUE TITLE
Auth screen using http-auth shows logon.inc.php page instead of default 

### ISSUE THREAD

**Issue by elbuit** [librenms/librenms#5053]
Hi.
I've runing a librenms using http-auth and since today update it doesn't works properly.
Librenms shows auth page (logon.inc.php) and don't show main page when you have logged in.

It's a cosmetic issue because you can go trough easily writing any word in the username field.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by laf** [comment]
Can confirm the same, I'd advise to roll back a few commits for now.

**Comment by laf** [comment]
Is this still an issue?

**Comment by elbuit** [comment]
Yes,  Neil.
I've updated right now and It's still hapenning. 
------------------------------------------------------------
Version	163a171 - Fri Dec 09 2016 22:29:30 GMT+0100
DB Schema	#151
Web Server	Apache/2.2.22 (Debian)
PHP	5.4.45-0+deb7u5
MySQL	10.0.27-MariaDB-0+deb8u1
RRDtool	1.5.5
--------------------------------------------------------------

**Comment by laf** [comment]
Sorry :( I'll get an environment setup to test

**Comment by laf** [comment]
Can you try this patch pls:

```php
diff --git a/html/includes/authenticate.inc.php b/html/includes/authenticate.inc.php
index d4b7b2c..e3a5db3 100644
--- a/html/includes/authenticate.inc.php
+++ b/html/includes/authenticate.inc.php
@@ -42,6 +42,8 @@ if (isset($_POST['username']) && isset($_POST['password'])) {
 } elseif (isset($_GET['username']) && isset($_GET['password'])) {
     $_SESSION['username'] = clean($_GET['username']);
     $_SESSION['password'] = $_GET['password'];
+} elseif (isset($_SERVER['REMOTE_USER'])) {
+    $_SESSION['username'] = $_SERVER['REMOTE_USER'];
 }

 if (!isset($config['auth_mechanism'])) {

```

**Comment by elbuit** [comment]
It works fine.

You can close this bug.
Thanks Neil.

**Comment by laf** [comment]
I've submitted the fix, once it's merged in you may need to revert this patch to update again.
