### ISSUE TITLE
PHP Fatal error:  require(): Failed opening required 'Net/IPv4.php'

### ISSUE THREAD

**Issue by jean-christophe-manciot** [librenms/librenms#5054]
Ubuntu 16.10 4.8
```
/opt/librenms$ sudo ./validate.php
PHP Warning:  require(Net/IPv4.php): failed to open stream: No such file or directory in /opt/librenms/includes/init.php on line 39
PHP Fatal error:  require(): Failed opening required 'Net/IPv4.php' (include_path='.:/usr/share/php') in /opt/librenms/includes/init.php on line 39

/opt/librenms$ sudo -u librenms ./validate.php
PHP Warning:  require(Net/IPv4.php): failed to open stream: No such file or directory in /opt/librenms/includes/init.php on line 39
PHP Fatal error:  require(): Failed opening required 'Net/IPv4.php' (include_path='.:/usr/share/php') in /opt/librenms/includes/init.php on line 39
```

**Comment by laf** [comment]
Please follow the install instructions, you've missed two library Net::IPv4 and Net::IPv6.

**Comment by jean-christophe-manciot** [comment]
Please read my post carefully before closing it abruptly and believing that everyone but you does a correct job:
```
apt search ipv4 | grep php
php-net-ipv6/yakkety,yakkety,now 1.3.0b1-1build1 all [installed]
```
There is no more php-net-ipv4 in Ubuntu **yakkety**.

**Comment by jean-christophe-manciot** [comment]
So, it is not available anymore on official Canonical repositories, but we can manually download it from [launchpad](https://launchpad.net/ubuntu/yakkety/+package/php-net-ipv4).

**Comment by jean-christophe-manciot** [comment]
Now it's OK:
```
/opt/librenms$ sudo -u librenms ./daily.sh
Updating to latest codebase                        OK
Updated from ccb76a7de9f2d4e34938d9b78d38328aee7addcd to db240cb4eb2a70507e1d746e3a832fb24a741d31 OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
actionmystique@samsung-ubuntu:/opt/librenms$ sudo ./validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | db240cb4eb2a70507e1d746e3a832fb24a741d31
DB Schema | 151
PHP       | 7.0.8-3ubuntu3
MySQL     | 5.7.16-0ubuntu0.16.10.1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.8.dev
==========================================================

[FAIL]  We couldn't find the following php extensions, please ensure they are installed:
snmp
[OK]    Database connection successful
[FAIL]  The poller has never run, check the cron job
```

**Comment by laf** [comment]
You must have gone through the install instructions and had an issue at that point then so why was your question not framed differently?

Your original post contains nothing more than a version number and the output of validate. The validate output shows the module you were missing and our docs have the steps for installing this.  Those docs do state they are for Ubuntu 16.04 where these modules are available.

Feel free to contribute some documentation if you think this needs to be clearer.

**Comment by laf** [comment]
Oh and for future, please read the notice when creating issues in future, it's clear about the information we ask for.

**Comment by jean-christophe-manciot** [comment]
"You must have gone through the install instructions and had an issue at that point then so why was your question not framed differently?"
Because I had LibreNMS correctly installed & working fine on Ubuntu 16.04 before I upgraded to 16.10....

**Comment by laf** [comment]
Then I'll repeat my last two comments:

"Feel free to contribute some documentation if you think this needs to be clearer."

"Oh and for future, please read the notice when creating issues in future, it's clear about the information we ask for."

Of which the last line says:

"Please provide as much detail as possible."
