### ISSUE TITLE
ups-nut Issues / Updates

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#5057]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ X] Please include all of the information between the `====================================` section of `./validate.php`.
- [ X] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ X] Please provide as much detail as possible.

Hi,

Working with ups-nut, found a few items. I don't mind taking care of some of them, but also want to make sure we agree on how to fix this - as I don't want to break something else. Here is what I'm seeing,
0) Just so you know - Remaining Time and Charge, work great!
1) Load: the data seems to be missing (all -nan). I updated to the latest version of the ups-nut.sh, perhaps there is a data misalignment now? I had data before, but now it's -nan (but other data is present).
2) Battery Voltage: Current is there, works fine. Should Nominal also be included, as it's in the SNMP output?
3) Input Voltage: Input works fine, but Nominal is the battery nominal voltage ... not the input nominal voltage. Again, perhaps misalignment? Input nominal is in the output also.

These I can fix - if it's OK. No issues here. But before that, a bit bigger issue ... :(. I use two apps, their changes to snmpd.conf are a bit different, as you can see below,
#Distro Detection
extend .1.3.6.1.4.1.2021.7890.1 distro /usr/bin/distro
#NUT UPS Data
extend ups-nut /home/rmorris/ups-nut.sh

So Distro puts the data at a fixed OID - which helps (more on that below), whereas ups-nut is only in NET-SNMP-EXTEND-MIB::nsExtendObjects ... the problem with that? Well, I also want to use ups-nut on my router, but it only supports SNMP exec, not extend (i.e. a bit older implementation. I have that configured like below,
exec .1.3.6.1.4.1.2021.7890.1 distro /opt/etc/distro
exec ups-nut /tmp/root/ups-nut.sh

The first line works, due to the fixed OID - so in other words, extend or exec are both OK. But not for the second one ... so can we add a fixed OID here also, so both extend and exec work? If you're OK with this ... do you have a proposed OID? I can make all the needed changes (I think ... ;)), but wanted to agree on the approach (OID for ups-nut, so exec or extend work).

Hopefully this all makes sense.

Thanks!

**Comment by arrmo** [comment]
Hi,

A bit of digging - and I see the issue. Checked vs. distro (another app), and there it does a check for different SNMP support / compatibility ... NET-SNMP-EXTEND-MIB, UCD-SNMP-MIB, or "exec" (fixed OID). Will try to add in a similar approach here - as this is needed, not all clients support the first approach.

Thanks!

**Comment by arrmo** [comment]
Hi,

OK, got my local changes pretty much working - and supporting both extend and exec SNMP options. Data seems to be going to rrd files correctly (and updated alignment to script, the number of outputs was misaligned).

Only odd thing I'm fighting with is the plots - I have corrected them also, and seem to get a single output from one device, which is odd of course. Is there an easy way to see what is in the rrd file, to make sure it's right?

Thanks!

**Comment by arrmo** [comment]
OK, found the issue. It was old data in the rrd files (where the number of arguments was not quite right, and the plots were misaligned as a consequence). Working now, from extend or exec - life is good ... :).

I won't add a PR for this yet, as it will add to my current PR (PR #5063), and I think that would add confusion ... agreed?

Thanks!

**Comment by laf** [comment]
It will yes because you are submitting pull requests from master. Take a read in our docs on how to branch out and submit fixes separately.

**Comment by arrmo** [comment]
Sure, will use a branch, no issues here. Thanks!

**Comment by laf** [comment]
Can this be closed now?

**Comment by arrmo** [comment]
Yep - thanks!
