### ISSUE TITLE
Can't modify or create alert rules

### ISSUE THREAD

**Issue by SKUZ-ee** [librenms/librenms#5058]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | 6890a71be43dc6d0aa54aa77585471babe5a1da5
DB Schema | 151
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

![librenms-creating or modifying rules error](https://cloud.githubusercontent.com/assets/23202704/20588208/8131cde0-b1e1-11e6-80c1-148c1b6acc74.JPG)

**error_log has the following:**
[Thu Nov 24 01:07:52.250974 2016] [:error] [pid 2969] [client 192.168.1.13:52829] PHP Fatal error:  Uncaught Error: Call to undefined function GenSQL() in /opt/librenms/html/includes/forms/create-alert-item$

I can no longer modify or create new alert rules in LibreNMS. When saving the rule, I always get the following error: "An error occurred creating this alert." This error happens on all my LibreNMS installations new and old that have been running and working for a few months. Even this new LibreNMS install that I did today have the same issue. I tried to use different browsers, cleared cache and still the same.

Thank you for checking.

**Comment by laf** [comment]
Confirmed.
