### ISSUE TITLE
Accessing Weathermap Editor results in 500 error

### ISSUE THREAD

**Issue by adamgent** [librenms/librenms#5060]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.
==========================================================
Component | Version
--------- | -------
LibreNMS  | 48b0e53a54732af03f0cf742047db21da47e86e4
DB Schema | 151
PHP       | 7.0.9
MySQL     | 5.5.47-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful

An update within the last few days has made accessing the weathermap plugin "editor" pages trigger an error 500, with the below trace from PHP;

[24-Nov-2016 11:48:58 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function dbDelete() in /opt/librenms/html/includes/authenticate.inc.php:22
Stack trace:
#0 /opt/librenms/html/plugins/Weathermap/editor.php(54): require_once()
#1 {main}
  thrown in /opt/librenms/html/includes/authenticate.inc.php on line 22

**Comment by adamgent** [comment]
As an update - we are now also running the latest code from librenms-plugins/Weathermap with no change in error state.

**Comment by adamgent** [comment]
Fixed by @laf - changes to librenms-plugins/weathermap to match up with core changes made to LibreNMS

**Comment by laf** [comment]
If anyone else comes across this please update the weathermap plugin.
