### ISSUE TITLE
Request for adding new OS/MIB

### ISSUE THREAD

**Issue by mr50986** [librenms/librenms#5061]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

- [x] Please include all of the information between the Component | Version

LibreNMS  | 6890a71be43dc6d0aa54aa77585471babe5a1da5
DB Schema | 151
PHP       | 5.6.17-0+deb8u1
MySQL     | 5.5.47-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)

Discover: http://pastebin.com/wYmzhCAJ
Poller: http://pastebin.com/QFtFbaVC
snmpwalk: http://pastebin.com/vRSGhLSc

- [x] Please provide as much detail as possible.

It's a chassibased EDFA with a controller/management unit and an EDFA card, it runs on Linux kernel (Linux (none) 2.6.12-h1940 #419 Thu Jan 23 11:31:34 CST 2014 armv4tl).
I wish to monitor (Input/Output) signallevels and powerlevels for the EDFA card. On this particular unit there is the possibility to add up to four edfa cards/modules.

Here is what documentation the suppliers has shipped with the unit.
[EDFA.zip](https://github.com/librenms/librenms/files/611462/EDFA.zip)

**Comment by FTBZ** [comment]
If you check your snmpwalk, it seems that your card returns only generic information which are useless?

**Comment by mr50986** [comment]
Did you read the document in the zipfile?
Not sure how that works, but the information i would like to see in LibreNMS is possible to get from a montoring program snmpwalking the unit with the MIB files provided.

**Comment by FTBZ** [comment]
What's the name of your EDFA manufacturer? Didn't find it in the documentation or I'm wrong?

**Comment by mr50986** [comment]
It's an fs.com product with PN#: FS-1U-R-EDFA
http://www.fs.com/products/35951.html

**Comment by laf** [comment]
Not sure what to do here. The sysObjectId belongs to another company, sysDescr is useless and none of the other data allows detection as an FS product.

We could create a generic edfa OS but it seems wrong.

**Comment by laf** [comment]
@librenms/reviewers anyone else?

**Comment by paulgear** [comment]
The fs.com site doesn't work for me at all.  When they're squatting on someone else's OID, that makes it a bit tricky.  With the current state of polling/discovery, I don't think we've got much choice than to use something like a generic EDFA OS.

**Comment by laf** [comment]
No further info contributed to discussion
