### ISSUE TITLE
How to get line protocol status, CRC number , input errors and out errors ? thank you!

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#5064]
R1#show interfaces 
FastEthernet0/0 is up, **line protocol is up** 
  Hardware is AmdFE, address is cc01.3a4e.0000 (bia cc01.3a4e.0000)
  Internet address is 10.0.0.2/8
  MTU 1500 bytes, BW 100000 Kbit, DLY 100 usec, 
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, loopback not set
  Keepalive set (10 sec)
  Full-duplex, 100Mb/s, 100BaseTX/FX
  ARP type: ARPA, ARP Timeout 04:00:00
  Last input never, output 00:00:04, output hang never
  Last clearing of "show interface" counters never
  Input queue: 0/75/0/0 (size/max/drops/flushes); Total output drops: 0
  Queueing strategy: fifo
  Output queue: 0/40 (size/max)
  5 minute input rate 0 bits/sec, 0 packets/sec
  5 minute output rate 0 bits/sec, 0 packets/sec
     0 packets input, 0 bytes
     Received 0 broadcasts, 0 runts, 0 giants, 0 throttles
     **0 input errors, 0 CRC,** 0 frame, 0 overrun, 0 ignored
     0 watchdog
     0 input packets with dribble condition detected
     8 packets output, 1427 bytes, 0 underruns
     **0 output errors,** 0 collisions, 0 interface resets
     0 babbles, 0 late collision, 0 deferred
     0 lost carrier, 0 no carrier
     0 output buffer failures, 0 output buffers swapped out

**Comment by wzhsunn** [comment]
@laf   Could you help me ?

**Comment by Rosiak** [comment]
Afaik proto status is not available through SNMP.
Input / output errors is already graphed.
<img width="362" alt="screen shot 2016-11-28 at 20 23 57" src="https://cloud.githubusercontent.com/assets/6378934/20682504/9faaa38a-b5a8-11e6-8ab1-2c662a991c92.png">

**Comment by wzhsunn** [comment]
Thank you for your reply, I also want to know how to get proto status by snmpget or snmpwalk .

**Comment by wzhsunn** [comment]
Maybe it is not right , there is no crc .
https://supportforums.cisco.com/discussion/11917151/mapping-crc-oids-interface-ports

**Comment by Rosiak** [comment]
So I guess we can close this issue?

**Comment by wzhsunn** [comment]
Am I right ?

**Comment by Rosiak** [comment]
Closing.

Proto status and CRC errors specific counters are not available, hence no works need to be done as we already graph ifErrors.
