### ISSUE TITLE
Alerting Based on Application Status / Variables

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#5068]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ X] Please include all of the information between the `====================================` section of `./validate.php`.
- [ X] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [X ] Please provide as much detail as possible.

One item that may be nice (and may exist, but I have been trying to use it with no luck unfortunately) - alerting based on values / variables inside applications. For example, create an alert when os_updates is greater than some threshold.

Thanks!

**Comment by laf** [comment]
Take a look at the applications mysql table, see if it's got what you want in there and then base your alert on that data.

**Comment by arrmo** [comment]
OK, will try to fiddle with it. I was looking the right place it seems - that's good .. :). Trying this for os_updates, I do see 4 rows in the table, with device_id matching the right machines. But still trying to find the actual data (all I see is app_state = UNKNOWN). Will keep digging, thanks!

**Comment by laf** [comment]
If that's all that's in there then you might be out of look at the moment.

Applications support isn't 100% so it's possible the info isn't logged to the DB.

**Comment by arrmo** [comment]
NP, thanks for the pointers. Do we close this, or leave it for future enhancement? Whatever you prefer is fine with me.

**Comment by laf** [comment]
I'd say leave it, it should be something that works.

**Comment by arrmo** [comment]
Sorry, missed this going by somehow ... :-(. I see app_state, but that's not showing the number of OS Updates that are pending - is it?

Thanks!
