### ISSUE TITLE
Monitoring Processes on Linux and potentially Windows Servers

### ISSUE THREAD

**Issue by alythemonk** [librenms/librenms#5069]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Yes it is. Please see results of validate.php

- [X] Please include all of the information from validate.php
==========================================================
LibreNMS Version: fe59396a092426a54871c73df989da52cbce9f31
DB Schema: 151
PHP: 7.0.12
MySQL: 5.6.32-78.1-56-log
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2
==========================================================

- [X] Please provide as much detail as possible.

I am trying to monitor processes with librenms. If , for example, on my mysql server, the mysqld or myself_safe were to disappear or fail and not be listed in ps -ef, the librenms system should raise an alert.

 I am new to Librenms and alerting, the docs seem sparse, and I am willing to add this knowledge to the docs online. I have tried filters such the following in alerts but to no avail:

	%devices.status = "1" && %devices.hostname ~ "priv-db" && %processes.command ~ "mysqld" && %processes.command ~ "mysqld_safe" && %processes.user = "mysql" && %processes.user = "root"
This is simply firing off a validation of the rule ... Thanks for any guidance.

**Comment by laf** [comment]
I'm not sure this is possible. You can't only check that the process name doesn't exist in the mysql on a per row output not collectively.

**Comment by alythemonk** [comment]
Sorry Laf didn't quite understand you. Are you saying that we can't monitor on a per process basis ? Or we have to add another processes item to the mix ? 

How would you solve this sort of problem ? Maybe I am looking at this the wrong way ?

**Comment by Gorian** [comment]
as a different approach - have you tried using the nagios service checks yet? They default / base install of plugins includes mysql checking, and the default LibreNMS rules will throw alerts based on the service checks. For most service based checking, I tend to use the service checks where I can.

**Comment by laf** [comment]
You can monitor per process but you can't monitor that a process doesn't exist as we check each process separately and not as a collective. So a rule of %something.process_name != 'me' will match every process that doesn't contain 'me' (totally made up example).

**Comment by alythemonk** [comment]
Hmm ... okay, I will try the services way as Gorian suggest and also see if I can do something more creative with the alerting rules. Thanks.

**Comment by Gorian** [comment]
@alythemonk good luck! FYI, you can find me in the ##librenms irc channel if you have any questions about the service checks :)

**Comment by alythemonk** [comment]
Thanks G-man ! Services worked better :) I like it better that the agent check for MySQL.
