### ISSUE TITLE
Unable to add Aruba Instant 'virtual' controller

### ISSUE THREAD

**Issue by DervMan** [librenms/librenms#5073]
I'm successfully polling each AP individually but want collective stats for all the AP's combined. This is supported on the Aruba Instant side of things. I can SNMPWALK the Instant IP successfully so know SNMP between LibreNMS and the IAP is good. However LibreNMS reports the following. 

`php addhost.php lon-aruba-instant ******* v2c
Could not connect, please check the snmp details and snmp reachability
`
`snmpwalk -v 2c -c ***** lon-aruba-instant  system
SNMPv2-MIB::sysDescr.0 = STRING: ArubaOS (MODEL: 335), Version 6.5.0.0-4.3.0.0
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.14823.1.2.71
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (178840746) 20 days, 16:46:47.46
SNMPv2-MIB::sysContact.0 = STRING:
SNMPv2-MIB::sysName.0 = STRING: LON-F3-AP01
SNMPv2-MIB::sysLocation.0 = STRING: London
SNMPv2-MIB::sysServices.0 = INTEGER: 72
`
I'm monitoring two Aruba Controllers and that works perfectly.

`==========================================================
Component | Version
--------- | -------
LibreNMS  | 7bb329661ff38b379fc2cb77ce1921ad99b729ed
DB Schema | 151
PHP       | 5.4.16
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================
`

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by laf** [comment]
I'm not clear on what you are after here.

**Comment by DervMan** [comment]
All I'm after is for Aruba Instant AP's to work the same way as Aruba Controller. As things stand I can't even add an Aruba Instant to LibreNMS, it errors out despite SNMP working.

**Comment by laf** [comment]
Post the output asked for under adding a new device as per point 3 above.

**Comment by DervMan** [comment]
1 & 2 don't show anything useful as I can't even add the device to LibreNMS.

[http://pastebin.com/nzk8vtgn](url)
[http://pastebin.com/8ZBnKCMW](url)
[http://pastebin.com/BK4JV26M](url)

**Comment by laf** [comment]
I just used your snmpwalk to add this device and it was detected ok.

The fact you can't even add it (even devices we don't recognise can be added) means you're either supplying the wrong snmp details or the community you are using has special chars in that are being escaped or mis-treated. If this is the case try and more simple community.

**Comment by laf** [comment]
No further info provided
