### ISSUE TITLE
Storage mounts not being ignored.

### ISSUE THREAD

**Issue by mcarse** [librenms/librenms#5075]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
Component | Version
--------- | -------
LibreNMS  | 7bb329661ff38b379fc2cb77ce1921ad99b729ed
DB Schema | 151
PHP       | 7.0.13-1+deb.sury.org~xenial+1
MySQL     | 5.7.16-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

Storage devices that are ignored in config.php or default.inc.php are not being ignored.
$config['ignore_mount'][] = '/dev'; is defined in defaults.inc.php.
/dev is being polled, reported, and alert devices.

This showed up with commit: //github.com/librenms/librenms/commit/42123010c821b54b13601e2d53dc16253e53264e

Previously, mounts /var/dhcpd/dev and /dev were being ignored.

**Comment by laf** [comment]
@mcarse be good if you can test my branch in #5076

**Comment by mcarse** [comment]
Running this PR, my devices are still not respecting the "ignored mounts".

**Comment by laf** [comment]
My bad :(

Just pushed an update which fixes this.The commit (7dbe8e06dfaecaeb95203e8bc2534fa35052eb67) shows the change, you can apply just that to the branch you tested or pull in the update.

**Comment by mcarse** [comment]
7dbe8e0 fixes the issue. Thanks for the help.
