### ISSUE TITLE
validate.php giving timezone error

### ISSUE THREAD

**Issue by TyShawn76** [librenms/librenms#5078]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [Y ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ Y] Please include all of the information between the `====================================` section of `./validate.php`.
[FAIL]  You have a different system timezone (EST) specified to the php configured timezone (UTC), please correct this.
- [ N] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ Y] Please provide as much detail as possible.

Brand new install on Ubuntu 16.0.4. Once I run the validate command I get the error listed above. I had the IRC team verify my Time zones and they are as followed.

System
Time zone: America/New_York (EST, -0500)
/etc/php5/apache2/php.ini and /etc/php5/cli/php.ini
Defines the default timezone used by the date functions ; http://php.net/date.timezone      date.timezone = America/New York

**Comment by Gorian** [comment]
Hi @TyShawn76. To clean up your issue, use [x], no spaces, instead of [ Y] and [ N]. This is special (markdown)[https://guides.github.com/features/mastering-markdown/] that creates check boxes.

Also, at the end of the task-list, please paste everything BETWEEN the equal signs. It should look like this:
![image](https://cloud.githubusercontent.com/assets/1012176/20690812/90044728-b581-11e6-97cf-990d23389c7c.png)

Thanks!

**Comment by TyShawn76** [comment]
Sorry about that @Gorian. The change of adding _ between New_York fixed my issue. Could someone update the help guide so other users won't fall to the same trap?

**Comment by Gorian** [comment]
@TyShawn76 no problem ^.^

I have updated the documentation
