### ISSUE TITLE
PowerWalker UPS NMC card support

### ISSUE THREAD

**Issue by jjonssondk** [librenms/librenms#5080]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

==========================================================
Component | Version
--------- | -------
LibreNMS  | 3390be5107955e61d74f93a94eca8787911294ac
DB Schema | 151
PHP       | 7.0.12-1~dotdeb+8.1
MySQL     | 10.0.27-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

[OK]    Database connection successful

Would like to have support for PowerWalker UPS NMC card and the following:

UPS Temperature
Input Voltage
Output Voltage
Output Frequency
Output Load (%)

Battery Status
Battery Capacity (%)
Battery Voltage
Battery Time on Battery

SNMP walk:  https://mega.nz/#F!rBMjgLbZ!78DoUo4hq4lkFx5bECcCWg
MIB file: http://www.powerwalker.com/index.php?page=nmc&lang=en

**Comment by laf** [comment]
We need the info asked for in http://docs.librenms.org/Support/FAQ/#faq20

**Comment by laf** [comment]
I've started this.

We currently don't have support for time on battery, what shall we call this group - i.e we have voltage, temperature, dbm, what shall we use here?

The mib also has support for  upsEstimatedMinutesRemaining and  upsEstimatedChargeRemaining, we can add these but what group should they be put into?

@librenms/reviewers or anyone else have any thoughts?

**Comment by laf** [comment]
Needs #5247 for the new function in snmp.inc.php - will continue once that's merged.
