### ISSUE TITLE
Support for IgniteNet MetroLinq 60 GHz wireless link

### ISSUE THREAD

**Issue by jjonssondk** [librenms/librenms#5085]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

==========================================================
Component | Version
--------- | -------
LibreNMS  | 3390be5107955e61d74f93a94eca8787911294ac
DB Schema | 151
PHP       | 7.0.12-1~dotdeb+8.1
MySQL     | 10.0.27-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

[OK]    Database connection successful

SNMP MIB file and SNMP walk, poller and discovery: https://mega.nz/#F!DVshGLBK!UwDB3PvLXnwMEJjlDvKxZw

**Comment by laf** [comment]
We need the info asked for in http://docs.librenms.org/Support/FAQ/#faq20

**Comment by laf** [comment]
What OS do these run or what should we use to refer to them as?

**Comment by keefe007** [comment]
The other NMS added ignitenet support recently.  Can you check their implementation?

**Comment by keefe007** [comment]
Here's a walk from a device.  Let me know if you need anything else.  This is a wireless p2p radio.

.1.3.6.1.2.1.1.1.0 = ""
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.47307
.1.3.6.1.2.1.1.3.0 = Timeticks: (34516952) 3 days, 23:52:49.52
.1.3.6.1.2.1.1.4.0 = ""
.1.3.6.1.2.1.1.5.0 = STRING: "ABC-XYZ-PTP"
.1.3.6.1.2.1.1.6.0 = ""
.1.3.6.1.2.1.2.1.0 = INTEGER: 4
.1.3.6.1.2.1.2.2.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.1.2 = INTEGER: 2
.1.3.6.1.2.1.2.2.1.1.3 = INTEGER: 3
.1.3.6.1.2.1.2.2.1.1.4 = INTEGER: 4
.1.3.6.1.2.1.2.2.1.2.1 = STRING: "eth0"
.1.3.6.1.2.1.2.2.1.2.2 = STRING: "eth1"
.1.3.6.1.2.1.2.2.1.2.3 = STRING: "wlan0"
.1.3.6.1.2.1.2.2.1.2.4 = STRING: "wlan1"
.1.3.6.1.2.1.2.2.1.8.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.2 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.3 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.4 = INTEGER: 7
.1.3.6.1.2.1.2.2.1.10.1 = Counter32: 4294967295
.1.3.6.1.2.1.2.2.1.10.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.10.3 = Counter32: 24689198
.1.3.6.1.2.1.2.2.1.10.4 = Counter32: 1521271
.1.3.6.1.2.1.2.2.1.11.1 = Counter32: 7012069
.1.3.6.1.2.1.2.2.1.11.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.11.3 = Counter32: 641543
.1.3.6.1.2.1.2.2.1.11.4 = Counter32: 2671
.1.3.6.1.2.1.2.2.1.13.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.1 = Counter32: 11077
.1.3.6.1.2.1.2.2.1.14.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.16.1 = Counter32: 23561242
.1.3.6.1.2.1.2.2.1.16.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.16.3 = Counter32: 422299177
.1.3.6.1.2.1.2.2.1.16.4 = Counter32: 2242247328
.1.3.6.1.2.1.2.2.1.17.1 = Counter32: 148136
.1.3.6.1.2.1.2.2.1.17.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.17.3 = Counter32: 3293592
.1.3.6.1.2.1.2.2.1.17.4 = Counter32: 15552368
.1.3.6.1.2.1.2.2.1.19.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.3 = Counter32: 98
.1.3.6.1.2.1.2.2.1.20.4 = Counter32: 0
.1.3.6.1.2.1.25.1.1.0 = Timeticks: (34520704) 3 days, 23:53:27.04
.1.3.6.1.4.1.2021.4.5.0 = INTEGER: 255544
.1.3.6.1.4.1.2021.4.6.0 = INTEGER: 175784
.1.3.6.1.4.1.2021.4.13.0 = INTEGER: 0
.1.3.6.1.4.1.2021.4.14.0 = INTEGER: 4352
.1.3.6.1.4.1.2021.4.15.0 = INTEGER: 13164
.1.3.6.1.4.1.2021.9.1.1.1 = INTEGER: 1
.1.3.6.1.4.1.2021.9.1.1.2 = INTEGER: 2
.1.3.6.1.4.1.2021.9.1.2.1 = STRING: "/jffs"
.1.3.6.1.4.1.2021.9.1.2.2 = STRING: "/tmp"
.1.3.6.1.4.1.2021.9.1.6.1 = INTEGER: 0
.1.3.6.1.4.1.2021.9.1.6.2 = INTEGER: 127772
.1.3.6.1.4.1.2021.9.1.7.1 = INTEGER: 0
.1.3.6.1.4.1.2021.9.1.7.2 = INTEGER: 127584
.1.3.6.1.4.1.2021.9.1.8.1 = INTEGER: 0
.1.3.6.1.4.1.2021.9.1.8.2 = INTEGER: 188
.1.3.6.1.4.1.2021.9.1.9.1 = INTEGER: 0
.1.3.6.1.4.1.2021.9.1.9.2 = INTEGER: 1
.1.3.6.1.4.1.2021.9.1.10.1 = INTEGER: 0
.1.3.6.1.4.1.2021.9.1.10.2 = INTEGER: 1
.1.3.6.1.4.1.2021.10.1.1.1 = INTEGER: 1
.1.3.6.1.4.1.2021.10.1.1.2 = INTEGER: 2
.1.3.6.1.4.1.2021.10.1.1.3 = INTEGER: 3
.1.3.6.1.4.1.2021.10.1.2.1 = STRING: "Load-1"
.1.3.6.1.4.1.2021.10.1.2.2 = STRING: "Load-5"
.1.3.6.1.4.1.2021.10.1.2.3 = STRING: "Load-15"
.1.3.6.1.4.1.2021.10.1.3.1 = STRING: "1.01"
.1.3.6.1.4.1.2021.10.1.3.2 = STRING: "1.02"
.1.3.6.1.4.1.2021.10.1.3.3 = STRING: "1.05"
.1.3.6.1.4.1.2021.10.1.4.1 = STRING: "1"
.1.3.6.1.4.1.2021.10.1.4.2 = STRING: "5"
.1.3.6.1.4.1.2021.10.1.4.3 = STRING: "15"
.1.3.6.1.4.1.2021.10.1.5.1 = INTEGER: 101
.1.3.6.1.4.1.2021.10.1.5.2 = INTEGER: 102
.1.3.6.1.4.1.2021.10.1.5.3 = INTEGER: 105
.1.3.6.1.4.1.2021.11.50.0 = Counter32: 106268
.1.3.6.1.4.1.2021.11.51.0 = Counter32: 0
.1.3.6.1.4.1.2021.11.52.0 = Counter32: 213114
.1.3.6.1.4.1.2021.11.53.0 = Counter32: 68613844
.1.3.6.1.4.1.2021.11.59.0 = Counter32: 800371054
.1.3.6.1.4.1.2021.11.60.0 = Counter32: 120801557
.1.3.6.1.4.1.47307.1.1.1.0 = STRING: "ML-60-35
"
.1.3.6.1.4.1.47307.1.1.2.0 = STRING: "1"
.1.3.6.1.4.1.47307.1.1.3.0 = STRING: "1.1.4-8811-77ba97a
"
.1.3.6.1.4.1.47307.1.2.1.0 = INTEGER: 2
.1.3.6.1.4.1.47307.1.2.2.1.1.1 = INTEGER: 1
.1.3.6.1.4.1.47307.1.2.2.1.1.2 = INTEGER: 2
.1.3.6.1.4.1.47307.1.2.2.1.2.1 = STRING: "eth0"
.1.3.6.1.4.1.47307.1.2.2.1.2.2 = STRING: "eth1"
.1.3.6.1.4.1.47307.1.2.2.1.3.1 = INTEGER: 1000
.1.3.6.1.4.1.47307.1.2.2.1.3.2 = INTEGER: 0
.1.3.6.1.4.1.47307.1.2.2.1.4.1 = INTEGER: 2
.1.3.6.1.4.1.47307.1.2.2.1.4.2 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.1.0 = INTEGER: 2
.1.3.6.1.4.1.47307.1.4.2.1.1.1 = INTEGER: 1
.1.3.6.1.4.1.47307.1.4.2.1.1.2 = INTEGER: 2
.1.3.6.1.4.1.47307.1.4.2.1.2.1 = INTEGER: 1
.1.3.6.1.4.1.47307.1.4.2.1.2.2 = INTEGER: 1
.1.3.6.1.4.1.47307.1.4.2.1.3.1 = STRING: "US"
.1.3.6.1.4.1.47307.1.4.2.1.3.2 = STRING: "US"
.1.3.6.1.4.1.47307.1.4.2.1.4.1 = INTEGER: 5240
.1.3.6.1.4.1.47307.1.4.2.1.4.2 = INTEGER: 64800
.1.3.6.1.4.1.47307.1.4.2.1.5.1 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.2.1.5.2 = INTEGER: 9
.1.3.6.1.4.1.47307.1.4.2.1.6.1 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.2.1.6.2 = INTEGER: 8
.1.3.6.1.4.1.47307.1.4.2.1.7.1 = INTEGER: 28
.1.3.6.1.4.1.47307.1.4.2.1.7.2 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.2.1.8.1 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.2.1.8.2 = INTEGER: 1
.1.3.6.1.4.1.47307.1.4.2.1.9.1 = INTEGER: 1
.1.3.6.1.4.1.47307.1.4.2.1.9.2 = INTEGER: 1
.1.3.6.1.4.1.47307.1.4.2.1.10.1 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.2.1.10.2 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.2.1.11.1 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.2.1.11.2 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.2.1.12.1 = INTEGER: 1
.1.3.6.1.4.1.47307.1.4.2.1.12.2 = INTEGER: 1
.1.3.6.1.4.1.47307.1.4.2.1.13.1 = STRING: "Backup Link"
.1.3.6.1.4.1.47307.1.4.2.1.13.2 = STRING: "ABC-XYZ-PTP"
.1.3.6.1.4.1.47307.1.4.2.1.14.1 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.2.1.14.2 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.3.1.1.1 = INTEGER: 1
.1.3.6.1.4.1.47307.1.4.3.1.1.2 = INTEGER: 2
.1.3.6.1.4.1.47307.1.4.3.1.2.1 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.3.1.2.2 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.3.1.3.1 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.3.1.3.2 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.3.1.4.1 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.3.1.4.2 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.3.1.5.1 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.3.1.5.2 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.3.1.6.1 = INTEGER: 0
.1.3.6.1.4.1.47307.1.4.3.1.6.2 = INTEGER: 128955
End of MIB

**Comment by laf** [comment]
Have you removed any information from this as it's missing at least sysDescr. You can mask data you don't want to appear but please don't remove it.

**Comment by laf** [comment]
@jjonssondk ?

**Comment by laf** [comment]
Feel free to comment when you have more info.

**Comment by jjonssondk** [comment]
New file in https://mega.nz/#F!DVshGLBK!UwDB3PvLXnwMEJjlDvKxZw

Hope there is what you need.

IgniteNet MetroLinq is 60 GHz with 5 GHz Point to Point link (Wireless)

**Comment by J0hnpR** [comment]
> What OS do these run or what should we use to refer to them as?

HeliOS - Linux based firmware
