### ISSUE TITLE
Cisco Small Business Long Polling and Device UP/Down

### ISSUE THREAD

**Issue by air101** [librenms/librenms#5086]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [X] Up2date.
- [x] Component | Version
--------- | -------
LibreNMS  | 3390be5107955e61d74f93a94eca8787911294ac
DB Schema | 151
PHP       | 5.6.17-0+deb8u1
MySQL     | 5.5.47-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

Hello Supporters,

I have several Cisco Small Business SG500 Switches which take a long time to Report to LibreNMS (which then reports Device up/down). Some are stacked which take eventually even more time to complete polling. I've disabled all unused ports but it seems that it doesn't run any faster. Is this a known issue?

Thank you and best Regards

**Comment by laf** [comment]
Not aware of it being a known issue. Have you tried the suggestions in: http://docs.librenms.org/Support/Performance/

We would need the full output of a poller + debug - you can use the capture system within the webui for this.

**Comment by laf** [comment]
No further info provided

**Comment by air101** [comment]
Sorry for my late response. Here is the poller and discovery log.
[libre.zip](https://github.com/librenms/librenms/files/648272/libre.zip)

**Comment by laf** [comment]
Have you tried the suggestions in the doc I linked to?

Your poll shows that ports and stp are the two biggest modules for time taken. If you can disable stp that will get you < 200 seconds for that one device. You may even be able to get that down more by following the suggestions I linked to.

**Comment by laf** [comment]
No further info provided.
