### ISSUE TITLE
APC status request for upsAdvBatteryReplaceIndicator 

### ISSUE THREAD

**Issue by boudreau** [librenms/librenms#5088]
Most APC smart-UPS have this indicator with the OID .1.3.6.1.4.1.318.1.1.1.2.2.4.0
With response 1 : battery = OK and 2: battery needs replacement/failed self-test

Can we add this feature on the Overview of the UPS screen?

Like a button green/red depending on the status?

Thanks

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by Rosiak** [comment]
Could you please test this PR ^^?

**Comment by boudreau** [comment]
Look like it working on my site, even detected a bad battery already.

Thanks
