### ISSUE TITLE
LDAP enhancements (bind, recursive, SSL)

### ISSUE THREAD

**Issue by jallakim** [librenms/librenms#5089]
Hi,

The LDAP authentication module should get support for binddn (i..e not binding as the user logging in), recursive lookups (nested groups) and SSL.

 1. `auth_ldap_binddn` and `auth_ldap_bindpw` should be used if present. Relevant for when you have a LDAP setup where users can't bind as themselves to check the password.
 2. `auth_ldap_recursive` and `auth_ldap_recursive_maxdepth` should be used if present. Useful if a user is a member of a group that is a member of a group that you're doing the lookup in. `auth_ldap_objectclass` should also probably be included in this.
 3. SSL should be an option. Currently it assumes `ldap://` when doing the bind, and the next-best thing is to use StartTLS (with `auth_ldap_starttls = 'require'`), but that isn't really secure.

**Comment by jallakim** [comment]
I see that 1) is a duplicate of #3209.

**Comment by Gorian** [comment]
I use `$config['auth_ad_binduser']` and `$config['auth_ad_bindpassword']`

Also, you can use ldaps. I specify an ldaps address in `$config['auth_ad_url']`, as 

```php
$config['auth_ad_url']                     = "ldaps://dc1.example.com ldaps://dc2.example.com ldaps://dc3.example.com";
$config['auth_ad_check_certificates']      = false;  // require a valid ssl certificate
```

**Comment by jallakim** [comment]
@Gorian, are you saying that you're using `$config['auth_mechanism'] = "active_directory";` against a normal LDAP server? (i.e. OpenLDAP).

**Comment by jallakim** [comment]
Doesn't seem like that's possible, since `active_directory.inc.php` assumes `usename@domain` in the connect string, and neither `active_directory.inc.php` nor `ldap.inc.php` uses each others `auth_` attributes. Hence the discussion over in #3209 is still a valid request.

**Comment by alythemonk** [comment]
I had tried to jam the php bind function in LDAP.inc.php. But I didn't have much success. I'll give it another try by adding the bind based php LDAP function with some updated variables like you've proposed and see if it's a simple fix.

**Comment by alythemonk** [comment]
Tried a sub to the bind function in php and it didn't work ! :(

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-ldap-enhancements-bind-recursive-ssl/679
