### ISSUE TITLE
Two Factor not working when using LDAP

### ISSUE THREAD

**Issue by jallakim** [librenms/librenms#5094]
Hi,

Two Factor authentication does not work (i.e. it's not initialized) when using LDAP. Haven't tested with other authentication sources, but as long as they don't create a database entry in the `users` table, it won't work (which is suspect is common for most of them?).

It's the [`dbUpdate` that fails](https://github.com/librenms/librenms/blob/043de43365e2feda3cc883d18f537dffcb7e1a2d/html/pages/preferences.inc.php#L150), since there are no row having a `username` value that matches `$_SESSION['username']`.

**Comment by jallakim** [comment]
```
Component | Version
--------- | -------
LibreNMS  | 3390be5107955e61d74f93a94eca8787911294ac
DB Schema | 151
PHP       | 7.0.13-1~dotdeb+8.1
MySQL     | 5.7.13-6
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
```

**Comment by jallakim** [comment]
Not sure where/how this should be handled, but new users signing in via LDAP should be added as a user in the database (w/o password being stored). That goes for the rest of the authentication methods as well (AD/RADIUS/etc).

**Comment by laf** [comment]
We add users to the DB for quite a few auth methods. I'd say it's more of a work around than a fix but you're free to do the same for this auth module.

**Comment by laf** [comment]
No further info provided

**Comment by jallakim** [comment]
@laf, what more info should be provided? There is no need for more information -- just a PR from Someone™ that fixes it (and yes, I have it on my TODO-list). Issue should be kept open until it's resolved?
