### ISSUE TITLE
Being able to ignore devices in eventlog.

### ISSUE THREAD

**Issue by basn** [librenms/librenms#5095]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [X] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | 043de43365e2feda3cc883d18f537dffcb7e1a2d
DB Schema | 151
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.27-MariaDB-0ubuntu0.16.04.1
RRDTool   |  1.5.5
SNMP      | NET-SNMP 5.7.3

I have two devices that are spamming my eventlog with events thats not an issue but i still want them to be in librenms but i want to ignore them so i can have a useful eventlog.

**Comment by Rosiak** [comment]
Hi,

We are cleaning up the issues here on GitHub, all feature requests will be moved to:
https://community.librenms.org/c/feature-requests

Hence the closure of this issue.
