### ISSUE TITLE
./discovery.php -h all stop after first device.

### ISSUE THREAD

**Issue by xbeaudouin** [librenms/librenms#5097]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | 043de43365e2feda3cc883d18f537dffcb7e1a2d
DB Schema | 151
PHP       | 5.4.45-0+deb7u5
MySQL     | 5.5.53-0+deb7u1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.4.3

Seems on my work librenms, when doing ./discovery.php -h all, it stop after the first device discovered.:

```
 ./discovery.php -h all
LibreNMS Discovery
Version info:
Commit SHA: 043de43365e2feda3cc883d18f537dffcb7e1a2d
DB Schema: 151
PHP: 5.4.45-0+deb7u5
MySQL: 5.5.53-0+deb7u1
RRDTool: 1.4.7
SNMP: NET-SNMP 5.4.3
lb2-d.XXX.net 146 linux  (unix)

#### Load disco module os ####

>> Runtime for discovery module 'os': 0.1930 seconds
#### Unload disco module os ####


#### Load disco module ports ####
..............

>> Runtime for discovery module 'ports': 0.1200 seconds
#### Unload disco module ports ####


#### Load disco module ports-stack ####


>> Runtime for discovery module 'ports-stack': 0.0110 seconds
#### Unload disco module ports-stack ####


#### Load disco module entity-physical ####

Caching OIDs: entPhysicalEntry entAliasMappingIdentifier

>> Runtime for discovery module 'entity-physical': 0.0580 seconds
#### Unload disco module entity-physical ####


#### Load disco module processors ####
 hrDevice: UCD Old: .

>> Runtime for discovery module 'processors': 0.0930 seconds
#### Unload disco module processors ####


#### Load disco module mempools ####


>> Runtime for discovery module 'mempools': 0.0710 seconds
#### Unload disco module mempools ####


#### Load disco module cisco-vrf-lite ####

>> Runtime for discovery module 'cisco-vrf-lite': 0.0000 seconds
#### Unload disco module cisco-vrf-lite ####


#### Load disco module ipv4-addresses ####
s.s.s.s.s.s.s.s.s.s.s.

>> Runtime for discovery module 'ipv4-addresses': 0.3530 seconds
#### Unload disco module ipv4-addresses ####


#### Load disco module ipv6-addresses ####


>> Runtime for discovery module 'ipv6-addresses': 0.0400 seconds
#### Unload disco module ipv6-addresses ####

Module [ route ] disabled globally.


#### Load disco module sensors ####
Pre-cache: 
 ENTITY-SENSOR: Caching OIDs: entPhySensorType entPhySensorScale entPhySensorPrecision entPhySensorValue
Temperatures: 
Humidity : 
Voltages: 
Frequencies: 
Runtime: 
Current: 
Power: 
Fanspeeds : 
Battery Charge: 
Load: 
States: 
dBm: 
Signal: 

>> Runtime for discovery module 'sensors': 0.3110 seconds
#### Unload disco module sensors ####


#### Load disco module storage ####
..

>> Runtime for discovery module 'storage': 0.1440 seconds
#### Unload disco module storage ####


#### Load disco module hr-device ####


>> Runtime for discovery module 'hr-device': 0.0420 seconds
#### Unload disco module hr-device ####


#### Load disco module discovery-protocols ####
 CISCO-CDP-MIB:  LLDP-MIB:  OSPF Discovery: enabled


>> Runtime for discovery module 'discovery-protocols': 0.0790 seconds
#### Unload disco module discovery-protocols ####


#### Load disco module arp-table ####
```

**Comment by Rosiak** [comment]
SQL[SELECT M.* from ipv4_mac AS M, ports AS I WHERE M.port_id=I.port_id AND I.device_id='4' AND M.context_name=''] 
SQL[SELECT * FROM `ports` WHERE `device_id` = '4' AND `ifIndex` = '2'] 
PHP Fatal error:  Call to undefined function array_column() in /opt/librenms/includes/discovery/arp-table.inc.php on line 62

Fatal error: Call to undefined function array_column() in /opt/librenms/includes/discovery/arp-table.inc.php on line 62
