### ISSUE TITLE
Application data not work

### ISSUE THREAD

**Issue by starnetwork** [librenms/librenms#5100]
Hi,
just added device and add Application for Apache and MySQL and it's not show any data on the graphs of the Apache / MySQL

1. librenms version is up-to date
[root@monitor1 librenms]# sudo -u librenms sh ./daily.sh
Updating to latest codebase                        OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK

2. am checking Debian 14.04 LTS server,
all resources monitoring via SNMP are working and updated, only the application monitoring are not
I did the tests inside the Debain server and running
server1:~$ /usr/lib/check_mk_agent/local/mysql
and
server1:~$ /etc/snmp/apache-stats.py
and I got the data, for example:
server1:~$ /etc/snmp/apache-stats.py
739
46320640
1.18153
953
.775446
48605.1
62680.2
2
8
8
0
0
1
0
0
1
0
0
0
140

magento@ip-172-31-40-18:~$ /usr/lib/check_mk_agent/local/mysql
<<<mysql>>>
a0:61474031
a1:36502
a2:20580883
a3:7490011
a4:-1
a5:-1
a6:-1
a7:-1
a8:-1
a9:-1
aa:8191
ab:0
ac:7724
ad:0
ae:18616141
af:246945
ag:4138432
ah:1514910
ai:-1
aj:-1
ak:-1
al:-1
am:-1
an:-1
ao:-1
ap:-1
aq:0
ar:-1
as:0
at:0
au:-1
av:-1
aw:-1
ax:0
ay:0
az:0
b0:9140689
b1:7319005
b2:7796454
b3:6343386004
b4:8
b5:43826532
b6:19
b7:44
b8:400
b9:15902
ba:300
bb:1024
bc:400
bd:2
be:309
bf:43
bg:0
bh:7
bi:1
bj:283
bk:1
bl:151
bm:8
bn:344232
bo:-1
bp:-1
bq:0
br:-1
bs:0
bt:1061
bu:3758864
bv:72499617
bw:15938288
bx:11961021
by:595635
bz:5163
c0:11582
c1:16777216
c2:100590767
c3:2538651
c4:1329318
c5:16533817
c6:120567
c7:2
c8:0
c9:1069
ca:9367
cb:588
cc:0
cd:16803
ce:164033
cf:1833415
cg:0
ch:2203578
ci:39
cj:1673627
ck:144368968
cl:3544119
cm:4080575
cn:1618194
co:84
cp:116387803336
cq:60187615111
cr:8388608
cs:0
ct:-1
cu:-1
cv:-1
cw:32768
cx:0
cy:0
cz:-1
d0:-1
d1:-1
d2:-1
d3:-1
d4:-1
d5:-1
d6:-1
d7:-1
d8:-1
d9:-1
da:-1
db:-1
dc:-1
dd:-1
de:-1
df:-1
dg:-1
dh:1
di:16909706
dj:8412665
dk:0
dl:0
dm:2320178
dn:555817358
do:809870677
dp:1827459
dq:130797133
dr:7215139951
ds:1805
dt:0
du:0
dv:19003036
dw:190934752
dx:-1
dy:-1
dz:-1
e0:-1
e1:-1
e2:-1
e3:0
e4:-1
e5:-1
e6:-1
e7:-1
e8:-1
e9:-1
ea:-1
eb:-1
ec:-1
ed:-1
ee:-1
ef:-1
eg:0
eh:5807104
ei:16777216
ej:255921
ek:25

but it's still not show any data at Libernms side

./validate.php data:
[root@monitor1 librenms]# ./validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | 87de5607df1d73838f3c35e8e6c4eb6169db3b90
DB Schema | 151
PHP       | 7.0.12
MySQL     | 10.0.28-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful

any advice?

**Comment by laf** [comment]
Please post the output of `./poller.php -h HOSTNAME -r -f -d -m applications`

I have a feeling this may have been fixed though. I've just tested and it works for me.

**Comment by starnetwork** [comment]
Please:

[root@monitor1 librenms]# ./poller.php -h snmp.surplustechmart.com -r -f -d -m applications
LibreNMS Poller
Version info:
Commit SHA: 9f8f8b6c263fcaff0864467de8a08b8925ca4592
Commit Date: 1486022300
DB Schema: 157
PHP: 7.0.12
MySQL: 10.0.29-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2
DEBUG!
Starting polling run:

SQL[SELECT * FROM `devices` WHERE `disabled` = 0 AND `hostname` = 'snmp.surplustechmart.com' ORDER BY `device_id` ASC]
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '18']
Hostname: snmp.surplustechmart.com
Device ID: 18
OS: linux (unix)

SQL[INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('3','3','0','149','149','149','18',NOW())]
SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro udp:HOSTNAME:161 sysObjectID.0]
SNMPv2-SMI::enterprises.8*

SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -OQnUst -m SNMPv2-MIB:HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro udp:HOSTNAME:161 sysUpTime.0 sysLocation.0 sysContact.0 sysName.0 sysObjectID.0]
sysUpTime.0 = 549620433
sysLocation.0 = Sitting on the Dock of the Bay
sysContact.0 = Me <me@example.org>
sysName.0 = ip-172-31-40-18
sysObjectID.0 = enterprises.8*

SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -OvQ -m SNMPv2-MIB:HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro udp:HOSTNAME:161 sysDescr.0]
Linux ip-172-31-40-18 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64

SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -OQnUst -m HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro udp:HOSTNAME:161 snmpEngineTime.0 hrSystemUptime.0]
snmpEngineTime.0 = 5496205
hrSystemUptime.0 = 655290812

Using hrSystemUptime (6552908s)
RRD[update /opt/librenms/rrd/snmp.surplustechmart.com/uptime.rrd N:6552908]
[RRD Disabled]Uptime: 75 days, 20h 15m 8s
SQL[SELECT `lat`,`lng` FROM `locations` WHERE `location`='Sitting on the Dock of the Bay' LIMIT 1]
Google geocode engine being used
Bad lat / lng received
Modules status: Global+ OS  Device
#### Load poller module applications ####
SQL[SELECT * FROM `applications` WHERE `device_id`  = '18']
SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -O qv -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro udp:HOSTNAME:161 nsExtendOutputFull.6.97.112.97.99.104.101]
4617881
270281027584
.00126289
5488990
.841299
49240.6
58529.2
1
9
9
0
0
1
0
0
0
0
0
0
140

 apacheRRD[update /opt/librenms/rrd/snmp.surplustechmart.com/app-apache-1.rrd N:4617881:270281027584:.00126289:5488990:.841299:49240.6:58529.2:1:9:9:0:0:1:0:0:0:0:0:0:140]
[RRD Disabled] mysqlRRD[update /opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd N:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1]
[RRD Disabled]RRD[update /opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2-status.rrd N:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1]
[RRD Disabled]

>> Runtime for poller module 'applications': 0.3296 seconds
#### Unload poller module applications ####

RRD[update /opt/librenms/rrd/snmp.surplustechmart.com/poller-perf-applications.rrd N:0.32962989807129]
[RRD Disabled]### Start Device Groups ###
SQL[SELECT * FROM device_groups ORDER BY name]
SQL[SELECT `device_group_id` FROM `device_group_device` WHERE `device_id`='18']
Groups Added:
Groups Removed:
### End Device Groups ###
SQL[SELECT `graph` FROM `device_graphs` WHERE `device_id` = '18']
uptime RRD[update /opt/librenms/rrd/snmp.surplustechmart.com/poller-perf.rrd N:2.303]
[RRD Disabled]RRD[update /opt/librenms/rrd/snmp.surplustechmart.com/ping-perf.rrd N:149]
[RRD Disabled]Polled in 2.303 seconds
Updating snmp.surplustechmart.com
SQL[UPDATE `devices` set `uptime` ='6552908',`last_ping` =NOW(),`last_ping_timetaken` ='149',`last_polled` =NOW(),`last_polled_timetaken` ='2.303' WHERE `device_id` = '18']
UPDATED!
#### Start Alerts ####
SQL[SELECT `device_group_id` FROM `device_group_device` WHERE `device_id`='18']
SQL[SELECT alert_schedule.schedule_id FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '18' ) && ((alert_schedule.recurring = 0 AND (NOW() BETWEEN alert_schedule.start AND alert_schedule.end)) OR (alert_schedule.recurring = 1 AND (alert_schedule.start_recurring_dt <= date_format(NOW(), '--%d') AND (end_recurring_dt >= date_format(NOW(), '--%d') OR end_recurring_dt is NULL OR end_recurring_dt = '0000-00-00' OR end_recurring_dt = '')) AND (date_format(now(), '%H:%i:%s') BETWEEN `start_recurring_hr` AND end_recurring_hr) AND (recurring_day LIKE CONCAT('%',date_format(now(), ''),'%') OR recurring_day is null or recurring_day = ''))) LIMIT 1]
SQL[SELECT `device_group_id` FROM `device_group_device` WHERE `device_id`='18']
SQL[SELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '18' ) || alert_map.target = '18'  )]
#### End Alerts ####
SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','snmp.surplustechmart.com','1486032439.0047','2.338','1','monitor1.liveuptime.com\n')]
./poller.php snmp.surplustechmart.com 2017-02-02 12:47:21 - 1 devices polled in 2.338 secs
SNMP: Get[5/0.80s] Walk [0/0.00s]
MySQL: Cell[3/0.00s] Row[1/0.00s] Rows[8/0.00s] Column[3/0.00s] Update[1/0.00s] Insert[2/0.00s] Delete[0/0.00s]

**Comment by laf** [comment]
To me for apache that looks right.

I don't see data for the other apps. Can you go to one of the apache graphs and click show rrd info and paste it here.

**Comment by laf** [comment]
no further info provided

**Comment by starnetwork** [comment]
Hi,
no graphs for both Apache and MySQL / DB
in ssh the tests looks OK, and the Librenms is up-to date
Please re-open that.

**Comment by laf** [comment]
You haven't provided the info I asked for in the last response before closing.

**Comment by starnetwork** [comment]
Hi,
I can please send you access info in private?

**Comment by laf** [comment]
No, you can anonymise hostnames if you like but that should be the only sensitive thing there.

**Comment by starnetwork** [comment]
mean access to the server so you can see the info directly...

**Comment by laf** [comment]
I don't need access:

"Can you go to one of the apache graphs and click show rrd info and paste it here."

**Comment by starnetwork** [comment]
Here:
RRDTool Command
rrdtool graph /tmp/OfbfydkSnVGklvxL.png -l 0 -E --start 1486894200 --end 1486980600 --width 1712.7 --height 300.33333333333 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal -l 0 -E --start 1486894200 --end 1486980600 --width 1712.7 --height 300.33333333333 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal DEF:kbyte_o=/opt/librenms/rrd/shop.fashanga.co.il/app-apache-3.rrd:kbyte:AVERAGE CDEF:kbyte=kbyte_o,8,* AREA:kbyte#CDEB8B: COMMENT:'Kbps Now Ave Max\n' LINE1.25:kbyte#006600:' ' GPRINT:kbyte:LAST:%6.2lf%s GPRINT:kbyte:AVERAGE:%6.2lf%s GPRINT:kbyte:MAX:%6.2lf%s\n COMMENT:\n

RRDTool Output
1793x369 OK u:0.06 s:0.01 r:0.07

**Comment by starnetwork** [comment]
as for MySQL:
RRDTool Command
rrdtool graph /tmp/zJrYRpwG2EXpvuOA.png --alt-autoscale-max --rigid -E --start 1486894200 --end 1486980600 --width 1712.7 --height 300.33333333333 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal --alt-autoscale-max --rigid -E --start 1486894200 --end 1486980600 --width 1712.7 --height 300.33333333333 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal COMMENT:'Connections Now Min Max Avg\l' DEF:ds0=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:MaCs:AVERAGE DEF:ds0min=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:MaCs:MIN DEF:ds0max=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:MaCs:MAX DEF:ds1=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:MUCs:AVERAGE DEF:ds1min=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:MUCs:MIN DEF:ds1max=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:MUCs:MAX DEF:ds2=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:ACs:AVERAGE DEF:ds2min=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:ACs:MIN DEF:ds2max=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:ACs:MAX DEF:ds3=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:AdCs:AVERAGE DEF:ds3min=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:AdCs:MIN DEF:ds3max=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:AdCs:MAX DEF:ds4=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:TCd:AVERAGE DEF:ds4min=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:TCd:MIN DEF:ds4max=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:TCd:MAX DEF:ds5=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:Cs:AVERAGE DEF:ds5min=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:Cs:MIN DEF:ds5max=/opt/librenms/rrd/snmp.surplustechmart.com/app-mysql-2.rrd:Cs:MAX LINE1.25:ds0#CC0000:'Max Connection ' GPRINT:ds0:LAST:%5.2lf%s GPRINT:ds0min:MIN:%5.2lf%s GPRINT:ds0max:MAX:%5.2lf%s GPRINT:ds0:AVERAGE:'%5.2lf%s\n' LINE1.25:ds1#008C00:'Max Used Conne ' GPRINT:ds1:LAST:%5.2lf%s GPRINT:ds1min:MIN:%5.2lf%s GPRINT:ds1max:MAX:%5.2lf%s GPRINT:ds1:AVERAGE:'%5.2lf%s\n' LINE1.25:ds2#4096EE:'Aborted Client ' GPRINT:ds2:LAST:%5.2lf%s GPRINT:ds2min:MIN:%5.2lf%s GPRINT:ds2max:MAX:%5.2lf%s GPRINT:ds2:AVERAGE:'%5.2lf%s\n' LINE1.25:ds3#73880A:'Aborted Connec ' GPRINT:ds3:LAST:%5.2lf%s GPRINT:ds3min:MIN:%5.2lf%s GPRINT:ds3max:MAX:%5.2lf%s GPRINT:ds3:AVERAGE:'%5.2lf%s\n' LINE1.25:ds4#D01F3C:'Threads Connec ' GPRINT:ds4:LAST:%5.2lf%s GPRINT:ds4min:MIN:%5.2lf%s GPRINT:ds4max:MAX:%5.2lf%s GPRINT:ds4:AVERAGE:'%5.2lf%s\n' LINE1.25:ds5#36393D:'New Connection ' GPRINT:ds5:LAST:%5.2lf%s GPRINT:ds5min:MIN:%5.2lf%s GPRINT:ds5max:MAX:%5.2lf%s GPRINT:ds5:AVERAGE:'%5.2lf%s\n' HRULE:0#555555

RRDTool Output
1793x439 OK u:0.07 s:0.01 r:0.08

**Comment by laf** [comment]
Can you confirm that you've got the latest application files from the librenms/librenms-agent/ repo please.

I've set this up on my test install and it works perfectly fine.

**Comment by starnetwork** [comment]
Hi,
for example in Apache, I did from wget https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/apache-stats.py -O /etc/snmp/apache-stats.py

as I see at http://docs.librenms.org/Extensions/Applications/#apache

it's OK or I should take it from other location?

**Comment by laf** [comment]
No that's fine, please verify the md5sum:

`d11462964b4332e0165bb6b9e30a1e4a  /etc/snmp/apache-stats.py`

Please also run `/etc/snmp/apache-stats.py` manually and pastebin the output again. Also what Apache version?

**Comment by starnetwork** [comment]
Hi,
1. yes:
[root@server1 ~]# md5sum /etc/snmp/apache-stats.py
d11462964b4332e0165bb6b9e30a1e4a  /etc/snmp/apache-stats.py

2. version:
[root@server1 ~]# httpd -v
Server version: Apache/2.4.25 (Unix)
Server built:   Dec 29 2016 09:58:15

3. run the file show:
[root@server1 ~]# /etc/snmp/apache-stats.py
Traceback (most recent call last):
  File "/etc/snmp/apache-stats.py", line 63, in <module>
    params[fields[0]] = fields[1]
IndexError: list index out of range

**Comment by laf** [comment]
Can you edit line 63 of that file and replace it with: `params[fields[0]] = '' if fields[1] is None else fields[1]`

**Comment by starnetwork** [comment]
[root@server1 custombuild]# /etc/snmp/apache-stats.py
Traceback (most recent call last):
  File "/etc/snmp/apache-stats.py", line 63, in <module>
    params[fields[0]] = '' if fields[1] is None else fields[1]
IndexError: list index out of range

**Comment by laf** [comment]
Try replacing it with this. Make sure you get the indentation correct:

```python
                try:
                        params[fields[0]] = fields[1]
                except:
                        params[fields[0]] = ''
```

**Comment by starnetwork** [comment]
[root@server1 librenms-agent]# python /etc/snmp/apache-stats.py
Traceback (most recent call last):
  File "/etc/snmp/apache-stats.py", line 63, in <module>
    params[fields[0]] = fields[1]
IndexError: list index out of range

**Comment by laf** [comment]
Looks like you've not applied that properly as line 63 before was that line and should now be try:

**Comment by starnetwork** [comment]
how can we check it?
at the beginning I used the original file with the same md5 signature

**Comment by laf** [comment]
Try this file although I've not tested I got the white space formatting right.

https://gist.githubusercontent.com/laf/a7c98204e9b6b42cb8e1c71b84109a3b/raw/1c7368a6d326c62d8cf149422f2237cbb3050460/gistfile1.txt

**Comment by starnetwork** [comment]
Thanks, I did it and got this error:
[root@server1 ~]# /etc/snmp/apache-stats.py
  File "/etc/snmp/apache-stats.py", line 63
    try:
       ^
IndentationError: unindent does not match any outer indentation level

**Comment by laf** [comment]
You'll need to fix the indentation on that line.

**Comment by starnetwork** [comment]
thanks, but how?
I take the file you sent me "As is"
something else I need to do?
am not python developer

**Comment by laf** [comment]
You don't need to be a developer to do that. Try this file:

https://gist.githubusercontent.com/laf/a7c98204e9b6b42cb8e1c71b84109a3b/raw/035ba5c41beb408cbafb34d0fd0c79524c17f5bc/gistfile1.txt

**Comment by starnetwork** [comment]
Thanks!
now it's look like it's work but no data on Librenms for both Apache or MySQL

[root@server1 custombuild]# /etc/snmp/apache-stats.py
9626
518522880
.0994985
36694
.262332
14131
53866.9
1
9
9
0
0
1
0
0
0
0
0
0
440

[root@server1 local]# /usr/lib/check_mk_agent/local/mysql
<<<mysql>>>
a0:108
a1:7
a2:0
a3:0
a4:-1
a5:-1
a6:-1
a7:-1
a8:-1
a9:-1
aa:-1
ab:-1
ac:-1
ad:-1
ae:-1
af:-1
ag:-1
ah:-1
ai:-1
aj:-1
ak:-1
al:-1
am:-1
an:-1
ao:-1
ap:-1
aq:-1
ar:-1
as:-1
at:-1
au:-1
av:-1
aw:-1
ax:-1
ay:-1
az:-1
b0:-1
b1:-1
b2:-1
b3:-1
b4:0
b5:309207
b6:0
b7:25
b8:155
b9:161
ba:2000
bb:65535
bc:2000
bd:1
be:0
bf:3
bg:0
bh:2
bi:1
bj:3
bk:1
bl:151
bm:4
bn:40953
bo:-1
bp:-1
bq:0
br:-1
bs:0
bt:4592
bu:232819672
bv:5201229
bw:161260
bx:0
by:16167
bz:19746
c0:44277
c1:268435456
c2:5510404
c3:22922
c4:22809
c5:5379496
c6:212
c7:0
c8:0
c9:0
ca:0
cb:0
cc:0
cd:23338
ce:0
cf:36007
cg:0
ch:54826
ci:0
cj:32
ck:2235445
cl:21364
cm:60757
cn:58004
co:6
cp:9147151217
cq:604526238
cr:16777216
cs:-1
ct:-1
cu:-1
cv:-1
cw:32768
cx:0
cy:0
cz:-1
d0:-1
d1:-1
d2:-1
d3:-1
d4:-1
d5:-1
d6:1
d7:-1
d8:-1
d9:-1
da:-1
db:-1
dc:-1
dd:-1
de:-1
df:-1
dg:-1
dh:-1
di:222755
dj:247
dk:0
dl:0
dm:55
dn:37188736
do:2228039230
dp:0
dq:26438327
dr:17024200988
ds:2
dt:0
du:0
dv:22922
dw:22930
dx:-1
dy:-1
dz:-1
e0:-1
e1:-1
e2:-1
e3:-1
e4:-1
e5:-1
e6:-1
e7:-1
e8:-1
e9:-1
ea:-1
eb:-1
ec:-1
ed:-1
ee:-1
ef:-1
eg:0
eh:24489984
ei:134217728
ej:0
ek:0

**Comment by laf** [comment]
You need to wait 15 minutes.

**Comment by starnetwork** [comment]
1. MySQL is OK for long time

2. I did, still no data on Librenms for both Apache or MySQL

**Comment by laf** [comment]
Please pastebin the output of http://docs.librenms.org/Support/FAQ/#faq20

**Comment by starnetwork** [comment]
Please: 
http://text.starltd.net/view/2167e5bb#nFafmuAkneMHNEi4pnwzc0J4auUpXS31

**Comment by starnetwork** [comment]
Please: 
http://text.starltd.net/view/2167e5bb#nFafmuAkneMHNEi4pnwzc0J4auUpXS31

**Comment by laf** [comment]
Those poller/debugs contain no information so the device is either disabled or you used the wrong hostname

**Comment by starnetwork** [comment]
but I have some of the information, Screenshot for example:
![shop fashanga co il-librenms](https://cloud.githubusercontent.com/assets/626945/23628806/37c4213e-02be-11e7-8121-17a157213a99.png)

**Comment by laf** [comment]
I can only tell you what I see, try using the device id instead of the hostname.

**Comment by starnetwork** [comment]
Discover: http://text.starltd.net/view/91456b05#2cRkGrOVfW90sgrRSPubez0MfwuSBHlA

poller: http://text.starltd.net/view/a42ef312

**Comment by murrant** [comment]
@starnetwork you seem to have configured the my SQL script through the agent, but did not unable the unix-agent polling module.

Either enable that or switch to the SNMP extend method (recently added)

**Comment by starnetwork** [comment]
Hi,
just verified that Unix Agent is installed and work, and the module is Enabled for this device
about the switch to the SNMP extend method, who can I do that?
didn't find the docs...

**Comment by laf** [comment]
The unix agent is definitely showing as disabled there. Please show a screenshot of your modules settings page for this device.

You may also want to test: https://github.com/librenms/librenms/pull/6277

**Comment by laf** [comment]
No further info provided.
