### ISSUE TITLE
Graphs not plotting

### ISSUE THREAD

**Issue by alythemonk** [librenms/librenms#5103]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

 [X] Please provide as much detail as possible.

RRDTOOL version = 1.6.0
OS = CentOS 7

Services and Agent Based Application graphs are not plotting. Here is an example of the rrdtool:

file missing: 
RRDTool Command
rrdtool graph /tmp/4b3kKK2ATxMpb5x4.png --alt-autoscale-max --rigid -E --start 1480524300 --end 1480610700 --width 1550.7 --height 503 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal -l 0 -E --start 1480524300 --end 1480610700 --width 1550.7 --height 503 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal COMMENT:'Packets/se... Now Min Max Avg\l' COMMENT:'\l'

RRDTool Output
OK u:0.00 s:0.00 r:0.00 

Another example:

RRDTool Command
rrdtool graph /tmp/vIZ1d3NtBcIDiZDc.png --alt-autoscale-max --rigid -E --start 1480524600 --end 1480611000 --width 1550.7 --height 503 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal --alt-autoscale-max --rigid -E --start 1480524600 --end 1480611000 --width 1550.7 --height 503 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal COMMENT:'Connections Now Min Max Avg\l' COMMENT:'\l' DEF:ds0=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:MaCs:AVERAGE DEF:ds0min=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:MaCs:MIN DEF:ds0max=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:MaCs:MAX DEF:ds1=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:MUCs:AVERAGE DEF:ds1min=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:MUCs:MIN DEF:ds1max=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:MUCs:MAX DEF:ds2=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:ACs:AVERAGE DEF:ds2min=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:ACs:MIN DEF:ds2max=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:ACs:MAX DEF:ds3=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:AdCs:AVERAGE DEF:ds3min=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:AdCs:MIN DEF:ds3max=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:AdCs:MAX DEF:ds4=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:TCd:AVERAGE DEF:ds4min=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:TCd:MIN DEF:ds4max=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:TCd:MAX DEF:ds5=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:Cs:AVERAGE DEF:ds5min=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:Cs:MIN DEF:ds5max=/opt/librenms/rrd/priv-db01.int.myvdc.cloud/app-mysql-84.rrd:Cs:MAX LINE1.25:ds0#CC0000:'Max Connections ' GPRINT:ds0:LAST:%5.2lf%s GPRINT:ds0min:MIN:%5.2lf%s GPRINT:ds0max:MAX:%5.2lf%s GPRINT:ds0:AVERAGE:'%5.2lf%s\n' LINE1.25:ds1#008C00:'Max Used Connections ' GPRINT:ds1:LAST:%5.2lf%s GPRINT:ds1min:MIN:%5.2lf%s GPRINT:ds1max:MAX:%5.2lf%s GPRINT:ds1:AVERAGE:'%5.2lf%s\n' LINE1.25:ds2#4096EE:'Aborted Clients ' GPRINT:ds2:LAST:%5.2lf%s GPRINT:ds2min:MIN:%5.2lf%s GPRINT:ds2max:MAX:%5.2lf%s GPRINT:ds2:AVERAGE:'%5.2lf%s\n' LINE1.25:ds3#73880A:'Aborted Connects ' GPRINT:ds3:LAST:%5.2lf%s GPRINT:ds3min:MIN:%5.2lf%s GPRINT:ds3max:MAX:%5.2lf%s GPRINT:ds3:AVERAGE:'%5.2lf%s\n' LINE1.25:ds4#D01F3C:'Threads Connected ' GPRINT:ds4:LAST:%5.2lf%s GPRINT:ds4min:MIN:%5.2lf%s GPRINT:ds4max:MAX:%5.2lf%s GPRINT:ds4:AVERAGE:'%5.2lf%s\n' LINE1.25:ds5#36393D:'New Connections ' GPRINT:ds5:LAST:%5.2lf%s GPRINT:ds5min:MIN:%5.2lf%s GPRINT:ds5max:MAX:%5.2lf%s GPRINT:ds5:AVERAGE:'%5.2lf%s\n' HRULE:0#555555

RRDTool Output
1631x642 OK u:0.09 s:0.00 r:0.10 

Where the values are -nan. The ones with Error Drawing Graph:

RRDTool Command
rrdtool graph /tmp/WeG10Y7qcgrezum3.png --alt-autoscale-max --rigid -E --start 1480524600 --end 1480611000 --width 1550.7 --height 503 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal --alt-autoscale-max --rigid -E --start 1480524600 --end 1480611000 --width 1550.7 --height 503 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal COMMENT:'Connections Now Min Max Avg\l' COMMENT:'\l' DEF:ds0=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:MaCs:AVERAGE DEF:ds0min=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:MaCs:MIN DEF:ds0max=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:MaCs:MAX DEF:ds1=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:MUCs:AVERAGE DEF:ds1min=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:MUCs:MIN DEF:ds1max=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:MUCs:MAX DEF:ds2=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:ACs:AVERAGE DEF:ds2min=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:ACs:MIN DEF:ds2max=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:ACs:MAX DEF:ds3=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:AdCs:AVERAGE DEF:ds3min=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:AdCs:MIN DEF:ds3max=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:AdCs:MAX DEF:ds4=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:TCd:AVERAGE DEF:ds4min=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:TCd:MIN DEF:ds4max=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:TCd:MAX DEF:ds5=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:Cs:AVERAGE DEF:ds5min=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:Cs:MIN DEF:ds5max=/opt/librenms/rrd/priv-db02.int.myvdc.cloud/app-mysql-88.rrd:Cs:MAX LINE1.25:ds0#CC0000:'Max Connections ' GPRINT:ds0:LAST:%5.2lf%s GPRINT:ds0min:MIN:%5.2lf%s GPRINT:ds0max:MAX:%5.2lf%s GPRINT:ds0:AVERAGE:'%5.2lf%s\n' LINE1.25:ds1#008C00:'Max Used Connections ' GPRINT:ds1:LAST:%5.2lf%s GPRINT:ds1min:MIN:%5.2lf%s GPRINT:ds1max:MAX:%5.2lf%s GPRINT:ds1:AVERAGE:'%5.2lf%s\n' LINE1.25:ds2#4096EE:'Aborted Clients ' GPRINT:ds2:LAST:%5.2lf%s GPRINT:ds2min:MIN:%5.2lf%s GPRINT:ds2max:MAX:%5.2lf%s GPRINT:ds2:AVERAGE:'%5.2lf%s\n' LINE1.25:ds3#73880A:'Aborted Connects ' GPRINT:ds3:LAST:%5.2lf%s GPRINT:ds3min:MIN:%5.2lf%s GPRINT:ds3max:MAX:%5.2lf%s GPRINT:ds3:AVERAGE:'%5.2lf%s\n' LINE1.25:ds4#D01F3C:'Threads Connected ' GPRINT:ds4:LAST:%5.2lf%s GPRINT:ds4min:MIN:%5.2lf%s GPRINT:ds4max:MAX:%5.2lf%s GPRINT:ds4:AVERAGE:'%5.2lf%s\n' LINE1.25:ds5#36393D:'New Connections ' GPRINT:ds5:LAST:%5.2lf%s GPRINT:ds5min:MIN:%5.2lf%s GPRINT:ds5max:MAX:%5.2lf%s GPRINT:ds5:AVERAGE:'%5.2lf%s\n' HRULE:0#555555

RRDTool Output
ERROR: rrdc_fetch: Got 292 lines, expected 295 

Any tips on how to move forward ? Thanks.

Cheers,

ASD.

**Comment by laf** [comment]
You've completely ignored the information we ask for when creating an issue. Please provide this and change the output of the above to pastebin links, a wall of text is hard to read.

**Comment by aparedero** [comment]
@alythemonk I suggest to check permissions of /opt/libre/rrd directory and subdirectories of devices affected

**Comment by alythemonk** [comment]
Here is the output of validate.php taken as user librenms:

==========================================================
Component | Version
--------- | -------
LibreNMS  | 09767f7e95d425772760481a1b36cae57d6dea4a
DB Schema | 151
PHP       | 7.0.13
MySQL     | 5.6.32-78.1-56-log
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.2
==========================================================

[FAIL]  We have found some files that are owned by a different user than librenms, this will stop you updating automatically and / or rrd files being updated causing graphs to fail:
If you don't run a bespoke install then you can fix this by running `chown -R librenms:librenms /opt/librenms`
	 /opt/librenms/logs/access_log
	 /opt/librenms/logs/error_log
[OK]    Database connection successful
-bash-4.2$ 

Okay so here is a pastebin

http://pastebin.com/SZwH33Ws

Plus I haven't had much luck, in fact I did a full drop of the db and cleaned out the /opt/librenms, and did a clean install. But these graphs are still not plotting. In the previous install I had noticed that the files such as:

app-mysql-15.rrd 

where I assuming 15 is the device id weren't updated when I deleted and re-added the device. If my assumption is correct. This is something I compared by looking at the DB vrs this sort of file naming structure. Thanks.

Cheers,

ASD.

**Comment by Gorian** [comment]
just an FYI, it asks for the info BETWEEN the equal signs... if you paste the info BETWEEN, without including the equal signs, it pasts cleaner ;)

**Comment by systeembeheerder** [comment]
> some files that are owned by a different user than librenms, this will stop you updating automatically and / or rrd files being updated causing graphs to fail

It looks like you are saving your Apache log files in a librenms subdir. Although this is documented in http://docs.librenms.org/Installation/Installation-Ubuntu-1604-Apache/ I recommend to save them to the apache2 log dir  /var/log/apache2/

**Comment by Rosiak** [comment]
Can we close this issue? Seems related to local issues.

**Comment by alythemonk** [comment]
Yes. Thanks.



[https://d3pv4gq91q59qh.cloudfront.net/images/6624/30748/images/566758f91e829.jpeg?override=1449614636]
Aly S Dharshi           B.Sc. Computer Science, RHCE


Technology Strategist


m. 780 722 3461                 t. 780 428 5226


e. aly@dharshi.ca<mailto:aly@dharshi.ca>                w. alydharshi.com<https://esig.ly/links/170277>



[https://d3pv4gq91q59qh.cloudfront.net/images/6624/30748/icons/566759f7239bf.png]<https://esig.ly/links/170280>         [https://d3pv4gq91q59qh.cloudfront.net/images/6624/30748/icons/566759f7439f5.png] <https://esig.ly/links/170282>                [https://d3pv4gq91q59qh.cloudfront.net/images/6624/30748/icons/56679c968bad4.png] <https://esig.ly/links/170304>




If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

[https://d3pv4gq91q59qh.cloudfront.net/images/6624/30748/icons/leaf-icon-sml.gif]Think before you print.




On Dec 21, 2016, at 1:14 PM, S?ren Rosiak <notifications@github.com<mailto:notifications@github.com>> wrote:


Can we close this issue? Seems related to local issues.

-
