### ISSUE TITLE
Add support for CounterBasedGauge64 SNMP objects

### ISSUE THREAD

**Issue by cfiske** [librenms/librenms#5105]
The CounterBasedGauge64 SNMP object type (defined in MIB HCNUM-TC) is not currently supported, which results in the object being treated as a counter instead of a gauge and thus incorrect values (almost always 0) are reported.

In this case I am polling an F5 load balancer device. From F5-BIGIP-SYSTEM-MIB:

sysStatClientCurConns OBJECT-TYPE
        SYNTAX CounterBasedGauge64
        MAX-ACCESS read-only
        STATUS current
        DESCRIPTION
                "The current connections from client-side to the system."
        ::= { sysGlobalStat 8 }

And from the MIB tab in LibreNMS:

F5-BIGIP-SYSTEM-MIB	sysStatClientCurConns	sysStatClientCurConns	.1.3.6.1.4.1.3375.2.1.1.2.1.8.0	0	0	2016-11-30 19:04:51

I -think- it's just a matter of adding another conditional match in includes/snmp.inc.php but I don't know the code well enough to say for sure.

**Comment by laf** [comment]
@paulgear something you can fix?

**Comment by paulgear** [comment]
CounterBasedGauge64 seems an odd construct...  But yeah - should be straightforward to add support.  It might be a few days before I get to look at it, though.

**Comment by laf** [comment]
@cfiske can you try this patch:

```
diff --git a/includes/snmp.inc.php b/includes/snmp.inc.php
index 5568345..6ba9a66 100644
--- a/includes/snmp.inc.php
+++ b/includes/snmp.inc.php
@@ -861,6 +861,7 @@ function oid_rrd_type($oid, $mibdef)

         case 'Counter32':
         case 'Counter64':
+        case 'CounterBasedGauge64':
             return 'COUNTER:600:0:U';

         case 'Gauge32':

```

Seems counter is the best one to use here rather than gauge. Let us know how you get on.

**Comment by cfiske** [comment]
Will give it a try, though my take from reading the MIB is that it's intended to provide 64-bit gauge functionality rather than counter. Thanks for the patch!

**Comment by laf** [comment]
Just move the new line below `case 'Guage32':` then.

**Comment by laf** [comment]
@cfiske have you tested this further?

**Comment by laf** [comment]
No further info provided
