### ISSUE TITLE
IOS-XR -- Tranceiver power optical levels not showing correct dBm values

### ISSUE THREAD

**Issue by taking-care-of-business** [librenms/librenms#5106]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | 9b62f9e2a110f64b79612d066992637e181a8645
DB Schema | 151
PHP       | 5.3.3
MySQL     | 5.1.73
RRDTool   | 1.3.8
SNMP      | NET-SNMP 5.5

I am evaluating LibreNMS (fresh install, never used LibreNMS before) and I am polling Cisco ASR9000's. I am able to detect the XFP/SFP power optical levels in mW, and I see there was an entry to convert the results from mW to dBm (as Cisco MIBs sends out optical receiver power levels as mW). The entry can be found here: https://github.com/librenms/librenms/issues/1641 

I see graph entries for dBm power levels, but it's essentially ` mW * 1000 ` using the dBm as units, instead of ` 10 * log10(mW) ` 

Attached is a screen capture of the optical power graph claiming to be in dBm, and below is the IOS-XR output (tidbit from the ` show controllers <interface> phy ` command) showing both, mW and dBm results.

` Rx Power:  0.60460 mW (-2.18532 dBm) `

![librenms-rx-dbm-graph-notcorrect](https://cloud.githubusercontent.com/assets/24301416/20807303/6398f66e-b7cc-11e6-9a34-ebf6b0d67b9a.PNG)

` Tx Power:  0.47400 mW (-3.24222 dBm) `

![librenms-tx-dbm-graph-notcorrect](https://cloud.githubusercontent.com/assets/24301416/20807304/639b7dc6-b7cc-11e6-8133-0cb1b5836c43.PNG)

**Comment by laf** [comment]
The code in place to do the conversion only does so if it's IOS-XR and the description of the sensor is `Transceiver (R|T)x` which doesn't appear to be the case here so we might need to extend that check out.

Please post the output on pastebin or similar for the following:
```
./discover.php -h HOSTNAME -d -m sensors
./poller.php -h HOSTNAME -r -f -m sensors -d
```

**Comment by taking-care-of-business** [comment]
Requested output:
`http://pastebin.com/hNRdpVX6`

**Comment by geordish** [comment]
I've created a patch to try and fix this (#5119) Feel free to give it a try.

You can follow these instructions to pull in my branch: http://docs.librenms.org/Support/FAQ/#how-can-i-test-another-users-branch

**Comment by taking-care-of-business** [comment]
Thank you for the patch geordish.
I followed the instructions and I believe I got it correct, however I do not see a change in dBm readings (still the same as it was before applying the patch)..

I have attached a snapshot of the dBm I am seeing (post-patch install), as well as the pulling the patch from your github repo (first time doing it, let me know if I missed a step).

![librenms-dbm-readings-asr9k](https://cloud.githubusercontent.com/assets/24301416/20934932/e4981e0c-bbaa-11e6-904e-2381a3a4dada.PNG)

Patch installation output: http://pastebin.com/qi0zZjcU

**Comment by geordish** [comment]
You can check what branch you are on by issuing the command 'git branch'. Your commands look OK.

The problem is likely you have a bunch of duff sensor data in the database that needs correcting. You can either add/remote the device - will remove all historic data (I think - @laf might be able to confirm). Or try and remove it from the database. The following query might work, but don't blame me if it explodes!
DELETE FROM sensors WHERE sensor_class = 'power' AND sensor_type = 'cisco-entity-sensor';

Following the SQL you would need to run a discovery again to re-find the metrics.

**Comment by taking-care-of-business** [comment]
You are correct, adding and removing the device worked. Results looks a lot better...
I will do this to the other remaining ASR9k's I have added into LibreNMS and update this issue in the next few days on the progress.

I appreciate your time and effort geordish! Thank you!

![librenms-dbm-readings-asr9k-looksbetter](https://cloud.githubusercontent.com/assets/24301416/20937777/69025e54-bbb6-11e6-8604-82cca17088b2.PNG)

**Comment by taking-care-of-business** [comment]
Hey geordish,

I re-installed LibreNMS instance (for different reasons), and I re-applied your patch into this new install. 
The patch initially worked, where the correct readings were shown.. but then after a few minutes, it reverted back to the incorrect readings mentioned in the above post.

**Comment by geordish** [comment]
@taking-care-of-business do a 'git pull', and that should correct it for you.

**Comment by taking-care-of-business** [comment]
geordish,

Issue still persists after the ' git pull '. 
After removing the device from LibreNMS (including the device from the rrd/ DIR) and re-adding the same device, the correct dBm measurements come up initially. However, it goes back to the incorrect values again once it does another bulk snmpwalk / when it starts to generate graphs and it never recovers from that state (until I remove and re-add the same node).

I am able to reproduce this behaviour every time.

**Comment by geordish** [comment]
@taking-care-of-business switch back to the main branch, and run ./daily.sh. Should be sorted.

git checkout master
./daily.sh

**Comment by taking-care-of-business** [comment]
No, the issue is not resolved.
Re-install LibreNMS (to avoid any patch confusion). As I stated before, without any plots on the graph, the correct dBm readings appear. The second graphs are being populated, it reverts back to the original readings (mW * 1000).

Attached are snapshots with the correct readings / no graphs, and with the incorrect readings / graphs becoming populated.

I have also included the ./validate.php output as well:


Component | Version
--------- | -------
LibreNMS  | f0fefcfe4fe8a954da99c27f2bbe4b0b6f60c0d3
DB Schema | 151
PHP       | 7.0.13
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2


![librenms-dbm-readings-nographs](https://cloud.githubusercontent.com/assets/24301416/21013742/356477b6-bd29-11e6-8ac1-a640323cf9d3.PNG)
![librenms-dbm-readings-withgraphs](https://cloud.githubusercontent.com/assets/24301416/21013743/35645218-bd29-11e6-9d05-1e9557cd0fbc.PNG)

**Comment by laf** [comment]
We need the output of:

```
./discovery.php -h HOSTNAME -d -m sensors
./poller.php -h HOSTNAME -r -f -d -m sensors
```
As pastebin or similar links

**Comment by taking-care-of-business** [comment]
See attached

[20161208-LibreNMS-5106-Output-2.txt](https://github.com/librenms/librenms/files/639986/20161208-LibreNMS-5106-Output-2.txt)

**Comment by taking-care-of-business** [comment]
Hello,

After sometime, I have manually updated my LibreNMS install from the December 7th 2016 snapshot to the latest as of now (January 26th 2017, 	3fb65da ). The above symptoms are no longer reproducible and everything is working as expected. Graphs are now graphing the correct values and no longer reverting back. Performing a `git pull` and `./daily.sh` have done the trick.

Thank you geordish and laf for your assistance and resolving this bug.

Ticket can be closed off.
