### ISSUE TITLE
Pass newline to API

### ISSUE THREAD

**Issue by djtecha** [librenms/librenms#5110]
Is there any way to pass a newline to the notes api? I tried '\n', '\\n' and all the other fun encoding but the notes tab doesn't respect the newline and just prints those chars.

**Comment by djtecha** [comment]
This is still not working correctly with the latest code. I'm running the following endpoint:

/api/v0/devices/test -d {"field": "notes", "data": "warranty: NA \npostgresql: NA\n"}

**Comment by laf** [comment]
you need to urlencode that \n :)

**Comment by djtecha** [comment]
haha my bad, totally works. Thanks!
