### ISSUE TITLE
Support for nested groups (AD authentication)

### ISSUE THREAD

**Issue by nktl** [librenms/librenms#5112]
This does not work at the moment - users have to be direct members of groups defined in 'auth_ad_groups' parameter (placing a group there does not do anything)

Generally, "MATCHING_RULE_IN_CHAIN" filter should be used to get nested group membership for the user, but this does not work with LibreNMS at the moment. The syntax could be looking a bit like this:

$config['auth_ad_group_filter'] = "(member:1.2.840.113556.1.4.1941:=\$username)"

**Comment by Rosiak** [comment]
Hi,

We are cleaning up the issues here on GitHub, all feature requests will be moved to:
https://community.librenms.org/c/feature-requests

Hence the closure of this issue.
