### ISSUE TITLE
Feature Request: Basic support information

### ISSUE THREAD

**Issue by NerdBlender** [librenms/librenms#5115]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php`.
- [x ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

Something I came across today while dealing with my many Cisco support contracts, it would be nice to have something a bit more than just notes - the ability to enter an end date and a contract / support number and possibly some contact information on a device. Being able to create an alert based on an expiry date would also be useful.

Not a major thing, just something that would be useful

**Comment by Rosiak** [comment]
Links with #2540

**Comment by laf** [comment]
Lol, I was trying to find that issue the other day :/
