### ISSUE TITLE
Using regexp in device groups bugged?

### ISSUE THREAD

**Issue by sliddjur** [librenms/librenms#5118]
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
Yes

- [x] Please include all of the information between the 

```
==========================================================
Component | Version
--------- | -------
LibreNMS  | 09767f7e95d425772760481a1b36cae57d6dea4a
DB Schema | 151
PHP       | 5.5.14
MySQL     | 10.0.22-MariaDB
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.3
==========================================================

```
- [x] Please provide as much detail as possible.

When creating a device group with this pattern: 
`%devices.hostname ~ "[[:digit:]]{5}p-swi"
`

The first time I visit the group in web gui (/devices/group=84/) I see all devices. If I then press refresh within a couple of seconds, I see only half of the devices, if I then press refresh again I only see a couple of devices. In the end it ended up only showing one device.

To retrigger this bug I only changed the pattern a little bit like this `%devices.hostname ~ "[[:digit:]]{5}p-sw"
`

The manual says regexp can be used http://docs.librenms.org/Extensions/Device-Groups/
Regexp manual for mariaDB https://mariadb.com/kb/en/mariadb/regular-expressions-overview/

**Comment by laf** [comment]
Hmm, seems to work for me.

What does running the following query multiple times result in for you: `select count(*) from devices where hostname REGEXP "[[:digit:]]{5}p-swi";`

**Comment by sliddjur** [comment]
@laf  yes that gives me the right amount of devices from the sql query.
However, when using the group in librenms, I get no results.

This is the group I've created. ![capture](https://cloud.githubusercontent.com/assets/10002057/20958543/6f2bd5ee-bc56-11e6-919e-7bb3adeefd66.PNG)

I created a new group, with the same regexp. This successfully shows 22 out of 25 devices. 22 in web gui, and 25 in sql query.

**Comment by sliddjur** [comment]
One thing I noticed when adding another pattern to the rule, it messed up the formatting. Not only in the GUI, but this gets bugged in the database as well. 
![capture](https://cloud.githubusercontent.com/assets/10002057/20961314/c26d0242-bc64-11e6-89b3-6c4e7b9f2ec2.PNG)

Unfortunately it does not help to edit the database manually on that particular rule, even if I only put the rule in the database to %devices.hostname ~ "[[:digit:]]{5}p-swi" ||

**Comment by laf** [comment]
Should be all fixed now.
