### ISSUE TITLE
Add Guacamole Support  (Browser based SSH, Telnet, VNC, RDP)

### ISSUE THREAD

**Issue by marrold** [librenms/librenms#5121]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

It would be nice to have SSH, Telnet, VNC, RDP support, in the browser, straight from LibreNMS. There's an existing project called Guacamole that does exactly this - [https://guacamole.incubator.apache.org](https://guacamole.incubator.apache.org)

As I see it theres a few options-

1) Allow the user to add their own URL to open the Guacamole instance in another tab / window.
2) i) Use the Guacamole libaries to fully embed the session inside LibreNMS
   ii) Adjust autodiscovery to port scan relevant ports and add to Guacamole if they're open. 

I will do some research into this myself but for now heres the issue.

Thanks

**Comment by Gorian** [comment]
could just add some options to define the handlers. I.E. default to "ssh://hostname", but let you redefine it to something else? never used Guacamole, but I assume you can just pass parameters in the URL? Would be more flexible I'd think.

**Comment by pinchasMT** [comment]
+1

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-add-guacamole-support-browser-based-ssh-telnet-vnc-rdp/678
