### ISSUE TITLE
Create table on summary page? Feature Request

### ISSUE THREAD

**Issue by djtecha** [librenms/librenms#5124]
It would be pretty cool to be able to add the components type and label columns to the summary page as right now I have to navigate all the way to edit -> components But this has allowed me to post custom info about a machine in a table form. 
![screenshot from 2016-12-06 16-07-38](https://cloud.githubusercontent.com/assets/3084627/20949445/2c512c7a-bbce-11e6-98e3-80c23f749402.png)

**Comment by djtecha** [comment]
This is also the python script I'm using if anyone wanted their facter information in the components table:
https://gist.github.com/djtecha/20710057e138d476620c94473b4cb3f4

**Comment by adaniels21487** [comment]
HI @djtecha 
This sounds like a cool idea, perhaps the widget should have a filter and even display some/all of the component preferences.

Just a note on your script.
Think of type as a namespace. Discovery modules that utilise components do so using the type field. These modules are written to add and delete components of a certain type as objects are found and removed (usually by SNMP).
As an example, if a discovery module that used the type 'postfix' ran against this device, it would modify your postfix type depending on what it discovered.
For this reason, I would recommend that your script uses a common 'type' and use specific fields to display the data, eg something like:

            TYPE = 'devops_app_ver'
            DATA = '{ "%s": { "type": "%s", "application": "%s", "version": "%s"}}' % (ID, TYPE, BLOB, VER[x])

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-create-table-on-summary-page/677
