### ISSUE TITLE
Email Alerts only for Warnings and not for Critical Alerts

### ISSUE THREAD

**Issue by mr-ravirajput** [librenms/librenms#5129]
Hello,

I have installed LibreNMS and it is working fine. I have one issue and one query. 
issue
I have edited the threshold alert to 90 from 75 and the standard alerts like port down, device down etc are added. However I am getting email notification only for threshold alerts and not for link down for device down. Please advice.
query.
Is there a way to edit the content of the alert that is being send through email.

Thanks 

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by laf** [comment]
You will get alerts via email if you've configured the email transport correctly and the rules are alerting. There is not half way house of some things work and some don't. If a rule doesn't alert, it's simply not matching.

As you've provided no other information we can't help any further including all of the information asked for above.

As for the contents of the emails, you can create templates. Please see our docs.
