### ISSUE TITLE
Juniper ACX5048 and problem with topology map

### ISSUE THREAD

**Issue by penfold1972** [librenms/librenms#5133]
Component | Version
--------- | -------
LibreNMS  | d389069e2edc4604c07de1c23a79211ca732c00b
DB Schema | 150
PHP       | 5.4.16
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

I am playing with a new install of libreNMS and it's working very nicely.

I have some Juniper ACX5048 switches and they seem to have an interface called bme0 and when I pulled up the network map, all of the ACX devices were drawn linked to each other on this non-physical interface. When I did some digging, it appeared that all devices show they have the same MAC address "02:00:00:00:00:0a" on the BME interface.

I edited librenms/html/includes/print-map.inc.php so the line:
                             `M`.`mac_address` NOT IN ('000000000000','ffffffffffff') AND
was changed to:
                             `M`.`mac_address` NOT IN ('000000000000','ffffffffffff','02000000000a') AND
and my maps started being drawn correctly after that.

======================================
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by penfold1972** [comment]
I hope this screenshot illustrates my issue of multiple devices having the same MAC:
![juniper-em0-mac](https://cloud.githubusercontent.com/assets/24441474/21025825/f1e2c50e-bd57-11e6-89f9-036aac99fee8.PNG)
Which ties the wrong devices together on the wrong map:
![wrong-topo-map](https://cloud.githubusercontent.com/assets/24441474/21025958/8caee478-bd58-11e6-8aad-90c9eadfc23c.PNG)
But if I program /librenms/includes/print-map.inc.php to ignore the bogus MACs, then the map displays correctly:
![right-topo-map](https://cloud.githubusercontent.com/assets/24441474/21026050/e811eef0-bd58-11e6-981a-08af5e05619b.PNG)

**Comment by worton** [comment]
Can you  add
|^bme\d|
to your $config['bad_if_regexp'][]
in your config.php?

Juniper has all sorts of virtual management/internal interfaces like this depending on product line. This is pretty much what this config knob should be for so you don't have to change anything in php code.

**Comment by penfold1972** [comment]
With the following line in my config.php file, the topo map behaves the same as before:
$config['bad_if_regexp'][] = "|^bme\d|";

Am I getting the syntax wrong?
