### ISSUE TITLE
Enhancement for (Quick) Links

### ISSUE THREAD

**Issue by pinchasMT** [librenms/librenms#5134]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by pinchasMT** [comment]
![image](https://cloud.githubusercontent.com/assets/17321963/20984549/c04bfcaa-bc8e-11e6-8e76-e2500173cea0.png)

i would like to request an ability to configure these Quick Links, for example "ssh link" we use non-standard ssh port (for security reasons) and therefore be able to set custom port for ssh, for "web link" we need 2 links (http and https) and ability to add DNS suffix. also the ability to remove telnet link when not available, and so on...

side note: i think that users that user librenms are advanced enough not to leave management interfaces (like ssh and webui) on their default values (like ssh on port 22) and therefore will be delighted if these values are customizable

thank you
![image](https://cloud.githubusercontent.com/assets/17321963/20985539/e9ce95ca-bc92-11e6-8931-99114a95dd75.png)
and growing...

**Comment by Gorian** [comment]
+1 this. I'd like to see the ability to customize this more, including being able to change the protocols, for example someone mentioned they'd like to use quacamole or something to connect via SSH.

**Comment by laf** [comment]
Seems this belongs in #5121
