### ISSUE TITLE
Synology DSM, Sensor graphs missing (DSM not detected?)

### ISSUE THREAD

**Issue by E-t-z** [librenms/librenms#5136]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
```
Component | Version                                                                                         
--------- | -------                                                                                         
LibreNMS  |                                                                                                
DB Schema | 151                                                                                             
PHP       | 7.0.13-1+deb.sury.org~xenial+1                                                                  
MySQL     | 5.5.52-MariaDB                                                                                  
RRDTool   | 1.5.5                                                                                           
SNMP      | NET-SNMP 5.7.3
```
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

```
System Name | syno
Resolved IP | 192.168.1.10
Hardware | Generic x86 64-bit
Operating System | Linux 3.10.77
Object ID | enterprises.8072.3.2.10
```
LibreNMS version 1.22

Model: DS916+
DSM version: DSM 6.0.2-8451 Update 5

Detected as "Generic Linux" (Linux syno 3.10.77 #8451 SMP Wed Nov 9 13:45:59 CST 2016 x86_64), as a result no Synology specific MIB's are loaded. 
Which pretty much means, no CPU, Disk and other temperature  or sensor graphs are available.

**Comment by laf** [comment]
We need the info asked for in the "If you would like us to add a new device then please provide the information asked for here" section above.

**Comment by E-t-z** [comment]
I was under impression that Synology devices support was already present?
Fair enough, will provide imfo ASAP.

**Comment by E-t-z** [comment]
http://etz.planet.ee/bulkwalk.txt
http://etz.planet.ee/discovery.txt
http://etz.planet.ee/poller.txt

**Comment by TyShawn76** [comment]
That is very strange on my 1815+ I have all of those measurements available, other than the fan speed. I have the fan state of off and on, but the readings are there.

**Comment by E-t-z** [comment]
Maybe you could run that very same `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME` against yours? Just for an comparision... :)

**Comment by laf** [comment]
Until we add detection no point in comparing :)

**Comment by laf** [comment]
Actually I'm not sure what to suggest here. I doubt "Linux Syno" is default in the sysDescr and is based on the hostname of the device being syno. The usual lookup we do for dsm (synology) doesn't work here.

**Comment by E-t-z** [comment]
Yes, it is OS + Host name (I'm not very creative with host names).

I tested that "o" named product and it detected it.
But I liked LibreNMS flexibility more.

**Comment by E-t-z** [comment]
One way would be check if there is DSM (Disk Station Manager) package installed, but it is a really dirty way as you most likely have to query every Linux reported device for it to make sure, it is not Synology DSM.

```
HOST-RESOURCES-MIB::hrSWInstalledName.1 = STRING: "dsm-admincenter-braswell-bin-6.0-8451-s5"
HOST-RESOURCES-MIB::hrSWInstalledName.2 = STRING: "dsm-braswell-bin-6.0-8451-s5"
HOST-RESOURCES-MIB::hrSWInstalledName.3 = STRING: "libdsm-braswell-bin-6.0-8451-s3"
```

**Comment by laf** [comment]
Those look like vendor specific oids. I'll load the walk up later you sent and check. Thanks :)

**Comment by E-t-z** [comment]
They are from here: http://global.download.synology.com/download/Document/MIBGuide/Synology_DiskStation_MIB_Guide.pdf

And they are vendor specific (Synology specific), see page 14.

**Comment by laf** [comment]
weird, the walk you did earlier doesn't have any data for '.1.3.6.1.4.1.6574' - can you re-run it and see?

**Comment by E-t-z** [comment]
[url=https://postimg.org/image/h7tiync79/][img]https://s18.postimg.org/h7tiync79/Capture.png[/img][/url]

I did from the very same device, not from LibreNMS instance (less in between layers).

**Comment by TyShawn76** [comment]
I hope this help.
[Synology Walk (Librenms).txt](https://github.com/librenms/librenms/files/644449/Synology.Walk.Librenms.txt)

**Comment by TyShawn76** [comment]
I hope this help.

[Synology Walk (Librenms).txt](https://github.com/librenms/librenms/files/644453/Synology.Walk.Librenms.txt)

**Comment by laf** [comment]
It's weird, that walk just doesn't contain anything in .1.3.6.1.4.1.6574

Can you re-run the working one with -OUneb instead of -Os

**Comment by E-t-z** [comment]
Mine does not contain any references to .1.3.6.1.4.1.6574 even with -OUneb

http://etz.planet.ee/snmpwalk-ouneb.txt

`.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.8072.3.2.10` thats why, (at least) mine identifies it as Generic Linux, AFAIK.

**Comment by TyShawn76** [comment]
Here you go.
[Synology Walk Os (Librenms).txt](https://github.com/librenms/librenms/files/644467/Synology.Walk.Os.Librenms.txt)

**Comment by TyShawn76** [comment]
Here you go.

[Synology Walk Os (Librenms).txt](https://github.com/librenms/librenms/files/644468/Synology.Walk.Os.Librenms.txt)

**Comment by laf** [comment]
Can someone try this patch please:

```php
diff --git a/includes/discovery/os/dsm.inc.php b/includes/discovery/os/dsm.inc.php
index 396a0cd..d32041e 100644
--- a/includes/discovery/os/dsm.inc.php
+++ b/includes/discovery/os/dsm.inc.php
@@ -7,6 +7,10 @@ if (starts_with($sysDescr, 'Linux')) {
         'syno_dyn_module',
     );

+    if (snmp_get($device, 'systemStatus.0', '-Osqnv', 'SYNOLOGY-SYSTEM-MIB', 'synology')) {
+        $os = 'dsm';
+    }
+
     if (str_contains(snmp_get($device, 'HOST-RESOURCES-MIB::hrSystemInitialLoadParameters.0', '-Osqnv'), $init_params)) {
         $os = 'dsm';
     }

```

**Comment by E-t-z** [comment]
Patch, apllied...rediscovery initated...we'll see... :)

**Comment by E-t-z** [comment]
Success...all sorts of additional graphs appeared, including connected APC UPS ones.
Only thing is, it gets OS version wrong...
`Synology DSM 3.10.77` while it should be read as `DSM 6.0-8451` via snmp, GUI shows DSM 6.0.2-8451 Update 6, but that missing ".2" is Bug in Synology versioning, so this can be ignored.

**Comment by laf** [comment]
Thanks for confirming, I've submitted the fix as a pull request. When it's merged you might need to revert the patch to be able to update.

**Comment by E-t-z** [comment]
AFAIK, I can revert it right now, unless I plan to run rediscovery on it (it should keep its current state) or adding a new similar device.

**Comment by laf** [comment]
You can indeed but re-discovery will happen within 6 hours and change it back to generic.

**Comment by E-t-z** [comment]
OK, I was not aware about automatic rediscovery in 6 hour intervals, thx for the tip...
