### ISSUE TITLE
Slower poll time with this morning update

### ISSUE THREAD

**Issue by boudreau** [librenms/librenms#5138]
I'm polling 1400+ devices, was working fine all week and finishing in under 4 minutes mark. now it goes over to about 5m40sec.

Any chances the last update slowed the pollers?

Yves

==========================================================
Component | Version
--------- | -------
LibreNMS  | f0fefcfe4fe8a954da99c27f2bbe4b0b6f60c0d3
DB Schema | 151
PHP       | 7.0.12
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by boudreau** [comment]
I update every day at 4h15 EDT.

**Comment by laf** [comment]
`logs/daily.log` will show you the version you went from and to, please post those versions here.

Also, what devices do you poll in general?

**Comment by boudreau** [comment]
Last update this morning:
Updated from 28e35eff76fcf9dcfc1daf1837a65c83f3ac00d1 to f0fefcfe4fe8a954da99c27f2bbe4b0b6f60c0d3

**Comment by boudreau** [comment]
Poll mostly Cisco switches/routers and APC ups (3/4 of our devices) with the rest ASA, F5, ESX, ...

**Comment by laf** [comment]
The only thing that could have had a difference is ceraos updates but you don't mention those.

Have you looked at which devices in general have had an increase? Checked the polling module graphs to see if it's one module?

If this is all devices then it suggests it's in our core code and the only change there was a variable check so I don't see it being an issue in our code. If it's certain devices then you need to check the info above.

**Comment by boudreau** [comment]
I don't see any outstanding devices that are taking longer. I restarted the server also to eliminate some memory leak.
Is there anyway I can try and revert the last update to confirm it the last mod that caused the increase in polling time? A bit of a newbie on git.

thanks

**Comment by laf** [comment]
`git checkout 28e35ef`

**Comment by Rosiak** [comment]
Any news?

**Comment by boudreau** [comment]
got a bit of speedup with sunday's patch, got almost a minute back:

Updated from db2bd62502c9506cd1f082ad5f68e23c0bcae451 to ab29261f0c7c0578fd50ab491056b7f7
db025671

**Comment by laf** [comment]
I have to say, based on that and your initial post I really don't think the issue is within the code base, nothing was merged on Sunday that would improve polling times.
