### ISSUE TITLE
Voltage data from ipmi

### ISSUE THREAD

**Issue by djtecha** [librenms/librenms#5139]
Enabling the ipmi module I would've thought would pull in the voltage data, but it looks like it's only used via the sensors module? Is there a way to get server power usage via an idrac?

**Comment by laf** [comment]
We support voltage in drac via the sensors module. Please pastebin the output of:

```
./discovery.php -h HOSTNAME -d -m sensors
./poller.php -h HOSTNAME -d -m sensors -r -f
```

**Comment by djtecha** [comment]
Ok looks like http://docs.librenms.org/Support/Configuration/#ipmi has impi configs incorrect. Should be wrapped in array like:

$config['ipmi']['type'] = array('lanplus');

**Comment by laf** [comment]
Erm, the examples do show them as arrays. `[]` is shorthand for it.

**Comment by djtecha** [comment]
I'm just pointing out that the example in the docs didn't work until I changed it to that.

**Comment by laf** [comment]
`$config['ipmi']['type'] = array('lanplus');` is the same as `$config['ipmi']['type'][] = "lanplus";`
