### ISSUE TITLE
Need help in adding support for CTCU switches.

### ISSUE THREAD

**Issue by guoming218** [librenms/librenms#5141]
Need help in adding support for CTCU switches.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by laf** [comment]
You want to do it or you want us to do it?

**Comment by guoming218** [comment]
Actually I want you guys to guide me in doing it as i dont know how to do it. I am very new in this :) Thks

**Comment by laf** [comment]
Have you tried the docs from our site?

http://docs.librenms.org/Developing/Support-New-OS/

**Comment by guoming218** [comment]
i got lost after few step :x

**Comment by laf** [comment]
You're going to need to be more specific with what you need help with. Show us what you have so far.

**Comment by guoming218** [comment]
includes/definitions.inc.php

$os = 'CTCU';
$config['os'][$os]['text']             = 'CTCU';
$config['os'][$os]['type']             = 'network';
$config['os'][$os]['icon']             = ''; <---- whats hould i put here?
$config['os'][$os]['over'][0]['graph'] = 'device_bits';
$config['os'][$os]['over'][0]['text']  = 'Device Traffic';
$config['os'][$os]['over'][1]['graph'] = 'device_processor';
$config['os'][$os]['over'][1]['text']  = 'CPU Usage';
$config['os'][$os]['over'][2]['graph'] = 'device_mempool';
$config['os'][$os]['over'][2]['text']  = 'Memory Usage';

//The icon described before is the image we have to create and put in the directory html/images/os

//Don't forget to declare the specific graphs if needed. It will be located near the end of the file.


$config['graph_types']['device']['CTCU_users']['section']         = 'network';
$config['graph_types']['device']['CTCU_users']['order']           = '0';
$config['graph_types']['device']['CTCU_users']['descr']           = 'Active Users';
$config['graph_types']['device']['CTCU_sessions']['section']      = 'network';
$config['graph_types']['device']['CTCU_sessions']['order']        = '0';
$config['graph_types']['device']['CTCU_sessions']['descr']        = 'Active Sessions';

includes/discovery/os/CTCU.inc.php

<?php
if (!$os) {
    if (strstr($sysDescr, 'CTCU')) {
        $os = 'CTCU';
    }
}

includes/discovery/mempools/CTCU.inc.php


<?php
//
// Hardcoded discovery of Memory usage on CTCU devices.
//
if ($device['os'] == 'CTCU') {
    echo 'CTCU-MEMORY-POOL: ';

    $usage = str_replace('"', "", snmp_get($device, 'PULSESECURE-PSG-MIB::iveMemoryUtil.0', '-OvQ'));  (What should i change this to ?PULSESECURE-PSG-MIB)

    if (is_numeric($usage)) {
        discover_mempool($valid_mempool, $device, 0, 'CTCU-mem', 'Main Memory', '100', null, null);
    }
}


includes/discovery/processors/CTCU.inc.php

<?php
//
// Hardcoded discovery of CPU usage on CTCU devices.
//
if ($device['os'] == 'CTCU') {
    echo 'CTCU  : ';

    $descr = 'Processor';
    $usage = str_replace('"', "", snmp_get($device, 'PULSESECURE-PSG-MIB::iveCpuUtil.0', '-OvQ')); (What should i change this to ?PULSESECURE-PSG-MIB)

    if (is_numeric($usage)) {
        discover_processor($valid['processor'], $device, 'PULSESECURE-PSG-MIB::iveCpuUtil.0', '0', 'pulse-cpu', $descr, (What should i change this to ?PULSESECURE-PSG-MIB)
 '100', $usage, null, null);
    }
}


includes/polling/mempools/CTCU-mem.inc.php


<?php

// Simple hard-coded poller for CTCU
echo 'CTCU MemPool'.'\n';

if ($device['os'] == 'CTCU') {
  $perc     = str_replace('"', "", snmp_get($device, "PULSESECURE-PSG-MIB::iveMemoryUtil.0", '-OvQ'));  (What should i change this to ?PULSESECURE-PSG-MIB)
  $memory_available = str_replace('"', "", snmp_get($device, "UCD-SNMP-MIB::memTotalReal.0", '-OvQ'));  (What should i change this to ?UCD-SNMP-MIB)
  $mempool['total'] = $memory_available;

  if (is_numeric($perc)) {
    $mempool['used'] = ($memory_available / 100 * $perc);
    $mempool['free'] = ($memory_available - $mempool['used']);
  }

  echo "PERC " .$perc."%\n";
  echo "Avail " .$mempool['total']."\n";

}

includes/polling/processors/CTCU-cpu.inc.php

<?php
// Simple hard-coded poller for CTCU
echo 'CTCU CPU Usage';

if ($device['os'] == 'CTCU') {
    $usage = str_replace('"', "", snmp_get($device, 'PULSESECURE-PSG-MIB::iveCpuUtil.0', '-OvQ'));  (What should i change this to ?PULSESECURE-PSG-MIB)

    if (is_numeric($usage)) {
        $proc = ($usage * 100);
    }
}

includes/polling/os/CTCU.inc.php

<?php

$version = trim(snmp_get($device, "productVersion.0", "-OQv", "PULSESECURE-PSG-MIB"),'"');          (What should i change this to ?PULSESECURE-PSG-MIB)
$hardware = "CTCU" . trim(snmp_get($device, "productName.0", "-OQv", "PULSESECURE-PSG-MIB"),'"');   (What should i change this to ?PULSESECURE-PSG-MIB)
$hostname = trim(snmp_get($device, "sysName.0", "-OQv", "SNMPv2-MIB"),'"');

$users = snmp_get($device, 'PULSESECURE-PSG-MIB::iveConcurrentUsers.0', '-OQv'); (What should i change this to ?PULSESECURE-PSG-MIB)

if (is_numeric($users)) {
    $rrd_def = 'DS:users:GAUGE:600:0:U';
    $fields = array(
        'users' => $users
    )
    $tags = compact('rrd_def');
    data_update($device, 'CTCU_users', $tags, $fields);
    $graphs['CTCU_users'] = true;
}

$sessions = snmp_get($device, 'PULSESECURE-PSG-MIB::iveConcurrentUsers.0', '-OQv');    (What should i change this to ?PULSESECURE-PSG-MIB)

if (is_numeric($sessions)) {
    $rrd_def = array(
        'DS:sessions:GAUGE:600:0:U',
    }
    $fields = array(
        'sessions' => $sessions
    );
    $tags = compact('rrd_def');
    data_update($device, 'CTCU_sessions', $tags, $fields);
    $graphs['CTCU_sessions'] = true;
}

sql-schema/xxx.sql  <---- what does xxx mean
//check the file number in GitHub

php includes/sql-schema/update.php

INSERT INTO `graph_types`(`graph_type`, `graph_subtype`, `graph_section`, `graph_descr`, `graph_order`) VALUES ('device',  'CTCU_users',  'network',  'Active Users',  '');        (where should i put this 2 lines?)
INSERT INTO `graph_types`(`graph_type`, `graph_subtype`, `graph_section`, `graph_descr`, `graph_order`) VALUES ('device',  'CTCU_sessions',  'network',  'Active Sessions',  '');


html/includes/graphs/device/CTCU_sessions.inc.php


<?php

$rrd_filename = rrd_name($device['hostname'], 'CTCU_sessions');

require 'includes/graphs/common.inc.php';

$ds = 'sessions';

$colour_area = '9999cc';
$colour_line = '0000cc';

$colour_area_max = '9999cc';

$graph_max = 1;
$graph_min = 0;

$unit_text = 'Sessions';

require 'includes/graphs/generic_simplex.inc.php';


html/includes/graphs/device/CTCU_users.inc.php


<?php

$rrd_filename = rrd_name($device['hostname'], 'CTCU_users');

require 'includes/graphs/common.inc.php';

$ds = 'users';

$colour_area = '9999cc';
$colour_line = '0000cc';

$colour_area_max = '9999cc';

$graph_max = 1;

$unit_text = 'Users';

require 'includes/graphs/generic_simplex.inc.php';

**Comment by guoming218** [comment]
includes/definitions.inc.php

$os = 'CTCU';
$config['os'][$os]['text']             = 'CTCU';
$config['os'][$os]['type']             = 'network';
$config['os'][$os]['icon']             = ''; <---- whats hould i put here?
$config['os'][$os]['over'][0]['graph'] = 'device_bits';
$config['os'][$os]['over'][0]['text']  = 'Device Traffic';
$config['os'][$os]['over'][1]['graph'] = 'device_processor';
$config['os'][$os]['over'][1]['text']  = 'CPU Usage';
$config['os'][$os]['over'][2]['graph'] = 'device_mempool';
$config['os'][$os]['over'][2]['text']  = 'Memory Usage';

//The icon described before is the image we have to create and put in the directory html/images/os

//Don't forget to declare the specific graphs if needed. It will be located near the end of the file.


$config['graph_types']['device']['CTCU_users']['section']         = 'network';
$config['graph_types']['device']['CTCU_users']['order']           = '0';
$config['graph_types']['device']['CTCU_users']['descr']           = 'Active Users';
$config['graph_types']['device']['CTCU_sessions']['section']      = 'network';
$config['graph_types']['device']['CTCU_sessions']['order']        = '0';
$config['graph_types']['device']['CTCU_sessions']['descr']        = 'Active Sessions';

includes/discovery/os/CTCU.inc.php

<?php
if (!$os) {
    if (strstr($sysDescr, 'CTCU')) {
        $os = 'CTCU';
    }
}

**Comment by guoming218** [comment]
<?php
if (!$os) {
    if (strstr($sysDescr, 'CTCU')) {
        $os = 'CTCU';
    }
}

includes/discovery/mempools/CTCU.inc.php


<?php
//
// Hardcoded discovery of Memory usage on CTCU devices.
//
if ($device['os'] == 'CTCU') {
    echo 'CTCU-MEMORY-POOL: ';

    $usage = str_replace('"', "", snmp_get($device, 'PULSESECURE-PSG-MIB::iveMemoryUtil.0', '-OvQ'));  (What should i change this to ?PULSESECURE-PSG-MIB)

    if (is_numeric($usage)) {
        discover_mempool($valid_mempool, $device, 0, 'CTCU-mem', 'Main Memory', '100', null, null);
    }
}


includes/discovery/processors/CTCU.inc.php

<?php
//
// Hardcoded discovery of CPU usage on CTCU devices.
//
if ($device['os'] == 'CTCU') {
    echo 'CTCU  : ';

    $descr = 'Processor';
    $usage = str_replace('"', "", snmp_get($device, 'PULSESECURE-PSG-MIB::iveCpuUtil.0', '-OvQ')); (What should i change this to ?PULSESECURE-PSG-MIB)

    if (is_numeric($usage)) {
        discover_processor($valid['processor'], $device, 'PULSESECURE-PSG-MIB::iveCpuUtil.0', '0', 'pulse-cpu', $descr, (What should i change this to ?PULSESECURE-PSG-MIB)
 '100', $usage, null, null);
    }
}

**Comment by guoming218** [comment]
[Draft of the new OS.txt](https://github.com/librenms/librenms/files/645438/Draft.of.the.new.OS.txt)
Hi this is what i had draft :) thks for the help

**Comment by laf** [comment]
Without seeing the output of an snmpwalk then this is all we can suggest:

```
includes/definitions.inc.php

$os = 'ctcu';
$config['os'][$os]['text']             = 'CTCU';
$config['os'][$os]['type']             = 'network';
$config['os'][$os]['icon']             = 'ctcu'; <---- whats hould i put here?
$config['os'][$os]['over'][0]['graph'] = 'device_bits';
$config['os'][$os]['over'][0]['text']  = 'Device Traffic';
$config['os'][$os]['over'][1]['graph'] = 'device_processor';
$config['os'][$os]['over'][1]['text']  = 'CPU Usage';
$config['os'][$os]['over'][2]['graph'] = 'device_mempool';
$config['os'][$os]['over'][2]['text']  = 'Memory Usage';



includes/discovery/os/ctcu.inc.php

<?php

if (str_contains($sysDescr, 'CTCU')) {
    $os = 'ctcu';
}


```

Not all info is needed so you had kept in a load of code relevant for a different OS. If CTCU has the same info available then you need to know what OID's to get that info from. The above should add basic detection for now.

For any further help you'd need the output of what's asked for in:

http://docs.librenms.org/Support/FAQ/#faq20

**Comment by guoming218** [comment]
Thks for the help i will try it now:)

**Comment by guoming218** [comment]
Hi laf, 

I just put out the SNMPWALK. :)
[CTCU-SNMPWALK.txt](https://github.com/librenms/librenms/files/647955/CTCU-SNMPWALK.txt)

**Comment by laf** [comment]
That doesn't look like the information we need from the link I sent, that's a walk without the poller/discovery and relevant snmpwalk flags.

However sysDescr doesn't contain CTCU so you need to do:

```php
ncludes/definitions.inc.php

$os = 'ctcu';
$config['os'][$os]['text']             = 'CTCU';
$config['os'][$os]['type']             = 'network';
$config['os'][$os]['icon']             = 'ctcu'; <---- whats hould i put here?
$config['os'][$os]['over'][0]['graph'] = 'device_bits';
$config['os'][$os]['over'][0]['text']  = 'Device Traffic';
$config['os'][$os]['over'][1]['graph'] = 'device_processor';
$config['os'][$os]['over'][1]['text']  = 'CPU Usage';
$config['os'][$os]['over'][2]['graph'] = 'device_mempool';
$config['os'][$os]['over'][2]['text']  = 'Memory Usage';



includes/discovery/os/ctcu.inc.php

<?php

if (starts_with($sysObjectId, '.1.3.6.1.4.1.4756.0')) {
    $os = 'ctcu';
}
```

I can't see cpu/mem info in the output. Do you have a mib for this device?

**Comment by guoming218** [comment]
[MSW4424A_MIB_v101.txt](https://github.com/librenms/librenms/files/648368/MSW4424A_MIB_v101.txt)
Have:) this is the MIB for that device

**Comment by laf** [comment]
That also doesn't seem to mention anything about memory or cpu. You can try just getting basic os detection working, you might find mem/cpu work via other code we already have

**Comment by guoming218** [comment]
hmm detection is ok right now, hmm the thing is that there is no graphs output. Did i miss out somthing?

**Comment by laf** [comment]
run ./validate.php

**Comment by laf** [comment]
No further info provided
