### ISSUE TITLE
high poller times

### ISSUE THREAD

**Issue by crcro** [librenms/librenms#5144]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Component | Version
--------- | -------
LibreNMS  | dda62d8ce1bead8de62fe7adb10bc696f25e2685
DB Schema | 151
PHP       | 7.0.13
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

[OK]    Database connection successful
[FAIL]  The poller has not run in the last 5 minutes, check the cron job
[FAIL]  Some devices have not completed their polling run in 5 minutes, this will create gaps in data.
        Check your poll log and refer to http://docs.librenms.org/Support/Performance/
	 br01.nuamchefazi.ro
	 acs01.nuamchefazi.ro
	 acs02.nuamchefazi.ro
	 esx07.nuamchefazi.ro
	 esx15.nuamchefazi.ro

i think that one of these 2 pushes made polling times go crazy high:

163a171a756ec97374337439ddff1b36eb92c914
fc941bc14e316d59e81d42c89a283e1ca65d8b8f

everything was ok, but after auto-updating always there are some devices that took more than 5 minutes to poll (randomly)

**Comment by laf** [comment]
Neither of those two commits make sense to cause increase in polling times. 

1. Is it an increase in poll times across all devices? Check the poller module graphs. 

2. Try changing to this commit: git checkout a970a8d

**Comment by laf** [comment]
My home install is still running fc941bc as test. This hasn't seen an increase in poll times.

**Comment by crcro** [comment]
everything ok now running latest version. it was a faulty dns server that was answering to slow to queries. thx @laf
