### ISSUE TITLE
Percona MySQL Cluster and PXC Strict Mode

### ISSUE THREAD

**Issue by alythemonk** [librenms/librenms#5147]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

Yes

- [X] Please include all of the information from validate.php

Component | Version
--------- | -------
LibreNMS  | dda62d8ce1bead8de62fe7adb10bc696f25e2685
DB Schema | 6
PHP       | 7.0.13
MySQL     | 5.7.14-8-57-log
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.2

- [X] Please provide as much detail as possible.

MySQL is throwing the following error in the logs:

WSREP: Percona-XtraDB-Cluster prohibits use of DML command on a table (librenms.perf_times) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER

in /etc/my.cnf the sql-mode is set as per the documentation:

sql-mode=""

Have I missed a configurational step ? This is the percona docs on this matter:

https://www.percona.com/doc/percona-xtradb-cluster/5.7/features/pxc-strict-mode.html

Thanks.

**Comment by laf** [comment]
I guess you want to set that to disabled. We don't currently adhere fully to support strict mode so I'm guessing this is the same for PXC.
