### ISSUE TITLE
Add support for UBNT PicoStation M2

### ISSUE THREAD

**Issue by florianbeer** [librenms/librenms#5150]
- [x] Is your install up to date?
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)

Component | Version
--------- | -------
LibreNMS  | dda62d8ce1bead8de62fe7adb10bc696f25e2685
DB Schema | 151
PHP       | 5.6.29-1~dotdeb+7.1
MySQL     | 5.5.53-0+deb7u1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.4.3

I would like to have UBNT PicoStation M2 added to LibreNMS, so they show up as "Type: Wireless" and also have Wireless stats like UBNT UniFi APs.

There are however a few caveats with the provided infos below:

- My PicoStations M2 are flashed with UniFi firmware and don't run the stock provided AirOS. This is a (kind of) supported process by Ubiquiti and they provide the firmware image to do that.
- This particular PicoStation M2 shows up with "Hardware: Ubiquiti PicoStation M2" and "Operating System: Ubiquiti AirOS 3.7.8.5016.160715.1454" in LibreNMS, I do however also have quite a few of those APs that only show up as "Hardware: Ubiquiti" and "Operating System: Ubiquiti AirOS". I am guessing those are older hardware revisions. I can provide additional discover, poller and snmp infos from one of those devices if needed.

Discovery: http://pastebin.com/MUkjD8wH
Poller: http://pastebin.com/jd1ESJ1W
SNMP: http://pastebin.com/B0wzcbL6

**Comment by murrant** [comment]
`My PicoStations M2 are flashed with UniFi firmware and don't run the stock provided AirOS. This is a (kind of) supported process by Ubiquiti and they provide the firmware image to do that.`

This is tricky.  I don't know that we have a way to detect that.  

This is how we detect ubnt devices right now:
```
if (starts_with($sysObjectId, array('.1.3.6.1.4.1.10002.1', '.1.3.6.1.4.1.41112.1.4')) || str_contains(snmp_get($device, 'dot11manufacturerName.5', '-Osqnv', 'IEEE802dot11-MIB'), 'Ubiquiti')) {
        $os = 'airos';
        if (str_contains(snmp_walk($device, 'dot11manufacturerProductName', '-Osqnv', 'IEEE802dot11-MIB'), 'UAP')) {
            $os = 'unifi';
        } elseif (snmp_get($device, 'fwVersion.1', '-Osqnv', 'UBNT-AirFIBER-MIB', 'ubnt') !== false) {
            $os = 'airos-af';
        }
    } 
```

Any ideas?

**Comment by florianbeer** [comment]
> Any ideas?

Well, not really. But at the moment they just show "Netstats | System | Poller" under "Graphs", I'd be happy if I could get some Wireless stats there as well. NanoStations show a lot of Info (I guess polled via AirOS MIB) and UniFi APs at least show Radio Capacity and Wireless Clients (although it seems to not use the UniFi MIB that's inlcuded with LibreNMS).

Maybe it is possible to show the number of Wireless Clients for PicoStations somehow?

**Comment by murrant** [comment]
Yeah, your Picostation M2 running unifi is polled by the airos mib which does nothing against the unified os.

There doesn't seem to be anyway to detect that the Picostation is running unifi and use the unifi mibs.

If you can come up with a way to detect Picostation m2's running unifi, everything will just work.

**Comment by florianbeer** [comment]
No, PicoStation M2 doesn't have to be detected as UniFi, it would be enough to get the "Wireless" tab under "Graphs". At the moment there is nothing there, even though other AirOS devices (NanoStation LOCO M5) do have a lot of information showing up there.

And as an aside: No UniFi AccessPoint uses the UniFi MIB. The do have some "Wireless" graphs, but nothing shows up for them in MIB associations.

**Comment by jquagga** [comment]
UAPs are polled with the UBNT-UniFi-MIB in librenms. That provides the wifi client count and channel utilization. The problem though I think from your SNMP output is that your picoststion is not reporting anything in that oid range (41112) so even if you detected this as a Unifi AP, you would not get the wifi stats. 

If UBNT would support a version of the Unifi Firmware on that device which supports the added oids, then I think another elseif could be added here after the UAP line to check to see if entries exist for UBNT-UniFi-MIB. But right now, even adding that line wouldn't get you the data.

**Comment by jquagga** [comment]
Yeah, looking at the UBNT page for the Unifi on Picostation hack, they say that it only works up to Unifi Firmware 3.3. Versions after that got too big to fit on the Pico. 3.7 is when they added the expanded oids which added the client count, etc. So I don't think the data you are looking for is exposed in this FW version.

**Comment by florianbeer** [comment]
My controller is running v5.2.9, the PicoStations are on FW 3.7.8.5016 and everything is working just fine. When I've got time I'll try to dig through the snmpwalk output in greater detail and see if there's anything there that we could use.

**Comment by jquagga** [comment]
Cool. If you snmpwalk it with UBNT-UNIFI-MIB what do you get is the question?

**Comment by florianbeer** [comment]
Sadly the answer to your question @jquagga is: nothing. Seems like my old PicoStations just don't supply capacity and clients through SNMP.

Gotta wait for the upcoming UniFi controller integration, that's surely coming very soon :)

**Comment by laf** [comment]
@florianbeer hit me up on irc.
