### ISSUE TITLE
New OS - Works, but can't get stat graph working

### ISSUE THREAD

**Issue by NerdBlender** [librenms/librenms#5151]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

http://pastebin.com/g4RhMYpX

So everything works, but I created a new graph for active http requests, but the graph never displays on the Proxy tab under graphs.

I think i have missed something - but not sure what.

**Comment by laf** [comment]
What do you see?

**Comment by NerdBlender** [comment]
Just a blank page

**Comment by laf** [comment]
Need the output of `./poller.php -h HOSTNAME -r -f -d -m os`

**Comment by NerdBlender** [comment]
http://pastebin.com/NXQ0MVBR

Here you go

**Comment by laf** [comment]
Does look ok, I'd add some echo statements to that new graph file and see if it gets to the point of calling the code.

**Comment by NerdBlender** [comment]
Figured it out: 

Added
$i++;
$config['device_types'][$i]['text'] = 'Proxy';
$config['device_types'][$i]['type'] = 'proxy';
$config['device_types'][$i]['icon'] = 'network.png';

and changed

$config['graph_types']['device']['sgos_average_requests']['section']         = 'Proxy';

to

$config['graph_types']['device']['sgos_average_requests']['section']         = 'proxy';
