### ISSUE TITLE
Global Port Search not working

### ISSUE THREAD

**Issue by Tatermen** [librenms/librenms#516]
Forgive me - I'm not a developer by trade, and am not familiar with using Github.

I decided to migrate from Observium to LibreNMS, but have found one very frustrating problem - the global search function would only find devices and not ports. Problematic as I have 4000+ ports.

When I looked in html/ajax_search.php, I found that the SQL statement used to search for ports is failing on MySQL 5.5:

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS P,`devices`.* AS D FROM `ports` LEFT JOIN `devices` ON  `ports`.`device_id` =' at line 1

I have fixed this by changing line 78 to:

$results = dbFetchRows("SELECT `ports`.* FROM `ports`,`devices` WHERE `ports`.`device_id`=`devices`.`device_id` AND (`ports`.`ifAlias` LIKE '%$search%' OR `ports`.`ifDescr` LIKE '%$search%') LIMIT 8");

There seems to be a similar issue with the BGP search, but it does not concern me so much.

**Comment by laf** [comment]
Thanks for the report @Tatermen 

The fix was a little simpler than that as we still need the results from the devices table to put the hostname down for which port is which.

I've removed the AS P and AS D part of the queries and this now works. I've put a pull request in #517 and will merge shortly.

**Comment by laf** [comment]
This has now been merged in, if you git pull in the directory you installed LibreNMS into then it should now work for you.
