### ISSUE TITLE
Port / bits graph plots bytes instead of bits with Unifi switches

### ISSUE THREAD

**Issue by koenkooi** [librenms/librenms#5163]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? 
- [x] Please include all of the information between the `====================================` section of `./validate.php`.

```
Component | Version
--------- | -------
LibreNMS  | e8022608d43f54307bf379fe1d969972954c600b
DB Schema | 151
PHP       | 5.6.27-0+deb8u1
MySQL     | 10.0.28-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
```
- [x] Please provide as much detail as possible.

I installed librenms yesterday and added some widgets today and noticed that all the legends say 'bits' or uses a lowercase 'b', but the graph for unifi switches actually plots bytes.
To confirm this I ran a wget in a loop:

<img width="1050" alt="schermafbeelding 2016-12-13 om 12 19 12" src="https://cloud.githubusercontent.com/assets/259525/21138546/d719a5f0-c12e-11e6-8407-9dc87f863f91.png">

And that gives me this graph:

![graph](https://cloud.githubusercontent.com/assets/259525/21138543/d10390e0-c12e-11e6-9e7f-f43e3b8ba680.png)

The switch is a Unifi USW-24, the model without POE running the latest firmware (3.7.29.5446).

**Comment by koenkooi** [comment]
The Unifi controller gives me this for the above port:

<img width="1180" alt="schermafbeelding 2016-12-13 om 12 39 12" src="https://cloud.githubusercontent.com/assets/259525/21139022/31800eb0-c131-11e6-8f22-b5dd3e405c8c.png">

**Comment by koenkooi** [comment]
The 'realtime' view does get it correct:

<img width="1440" alt="schermafbeelding 2016-12-13 om 12 42 47" src="https://cloud.githubusercontent.com/assets/259525/21139123/b18bd3fa-c131-11e6-9228-1c1cdf5ecce9.png">

**Comment by laf** [comment]
That's Bits. I don't see any lowercase b in the legend of that graph.

**Comment by koenkooi** [comment]
well, 'bps' is all lowercase, which implies 'bits', when the numbers are actually in bytes.

**Comment by laf** [comment]
I don't see where your graph shows bps either.

Did you add this device as snmp v1?

**Comment by koenkooi** [comment]
![d10390e0-c12e-11e6-9e7f-f43e3b8ba680](https://cloud.githubusercontent.com/assets/259525/21140268/58cd1d0e-c137-11e6-8213-854e2bae17ad.png)

Yes, as SNMPv1:
<img width="719" alt="schermafbeelding 2016-12-13 om 13 24 47" src="https://cloud.githubusercontent.com/assets/259525/21140304/8f740e76-c137-11e6-8ddc-56632464b40c.png">

**Comment by laf** [comment]
Switch to v2, v1 limits at about 125Mbps

**Comment by koenkooi** [comment]
That fixed it, thanks! I mistakenly assumed that the v1 limit for the wifi snmp also applied to the switches, which it doesn't.
