### ISSUE TITLE
Unknown flag passed to -C: I

### ISSUE THREAD

**Issue by boudreau** [librenms/librenms#5164]
While on debug on poller.php, a wrong argument is passed to the snmpbulkwalk:

 ./poller.php -r -d -h 1366  > /tmp/test 2>&1
<...snipped...>
SNMP[^[[0;36m/usr/bin/snmpbulkwalk -Cr20  -v2c -c COMMUNITY  **-CI** -Oq -m CISCO-STACK-MIB -M /var/www/librenms/mibs -t 2 -r 2 udp:HOSTNAME:161 portIfIndex^[[0m]
**Unknown flag passed to -C: I**

SNMP[^[[0;36m/usr/bin/snmpbulkwalk -Cr20  -v2c -c COMMUNITY  **-CI** -OQs -m CISCO-STACK-MIB -M /var/www/librenms/mibs -t 2 -r 2 udp:HOSTNAME:161 portName^[[0m]
**Unknown flag passed to -C: I**
<...snipped...>

Might be a typo, only -Ci is a valid argument for snmpbulkwalk intead of -CI

Component | Version
--------- | -------
LibreNMS  | f0fefcfe4fe8a954da99c27f2bbe4b0b6f60c0d3
DB Schema | 151
PHP       | 7.0.13
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by Gorian** [comment]
FYI, post the information **BETWEEN** the equal signs... not including. It will format a **lot** better
