### ISSUE TITLE
[bug?] false vcore issue alerting

### ISSUE THREAD

**Issue by BloodyIron** [librenms/librenms#5171]
- [Y] -> 508c273 - Tue Dec 13 2016 03:46:48 GMT-0700

Two of the systems being monitored use AMD FX-8320 processors. One of the systems never seems to trigger a vcore over-voltage alert, the other does. libreNMS started alerting this about a month or two ago, so I suspect an update might have changed the behaviour, but I can't reasonably speculate when.

The vcore voltage on the CPU peaks at about 1.3v, which according to some digging ( https://www.reddit.com/r/overclocking/comments/3ahzlx/fx_8320_stock_vcore/ ) should be within tolerable values. This leads me to having to mute the alert repeatedly because I know it's a good value, but muting an alert generally defeats the point of that alert if the value is known-safe.

The CPU is not over-clocked, or modified beyond stock in any way. This is default behaviour.

As such I think this CPU is being incorrectly profiled.

**Comment by laf** [comment]
It's a generic calculation. We'd need to add support for calculating more specific thresholds. For now just update the limits for this device.

**Comment by laf** [comment]
Can you provide what high / low values have been calculated please along with the current value?

**Comment by BloodyIron** [comment]
Ugh I overwrote the bad values on the node, and I can't recall which node was the one that correctly calculated the value. This may mean I have destroyed the evidence by mistake. What should I do?

**Comment by laf** [comment]
Nothing at the moment, mind if we close it until you see it again?

**Comment by BloodyIron** [comment]
This info may be useful, I'm not sure:

Node that automatically generated what appears to be a good vcore high/low:
* low : 0.79
* high : 1.5732

Node that was naughty and generated bad values (I don't have the original high value):
* low : 0.7854 (original generated value)
* high : 1.5 (manually entered), I think the "bad" value was closer to 1.3 or 1.4 though

Is this helpful?

**Comment by laf** [comment]
So based on these values I don't really see anything wrong. Because they are small values the calculated threshold will only ever be small and as we can't get an actual high/low value from snmp then we have to calculate it. I don't think we should change the calculation based on one cpu though.

This is as simple as just changing the thresholds manually where you need to.

**Comment by BloodyIron** [comment]
I recently dusted out one of the servers and now it's reporting fan speed too low, lol, even though it's a good speed. Looks like there are some areas where calculation is a bit hit/miss in other areas too.

**Comment by laf** [comment]
fanspeed calcs are 1.8 * current for hight and 0.8 * current for low. What would you suggest?

**Comment by BloodyIron** [comment]
Well, the two nodes that are being monitored are literally identical hardware, same with the vcore stuff, hence why I think this is worth mentioning. I haven't altered the generated values, so here they are:

Units are RPM.

"Good" node CPU fanspeed:
* Current : 2922
* High : 5259.6
* Low : 2337.6


Misbehaving node CPU fanspeed:
* Current : 2986
* High : 7545.6
* Low : 3353.6


In my case the vcore and CPU fan speed is coming from lmsensors, not IPMI. I'm not sure if that's noteworthy. However it's very weird to see such drastically different values for the CPU fanspeed ranges as well as the vcore, considering they are literally identical systems.

The fanspeed stuff has been recently valuable to me because I received notifications that the fanspeed was going high on one, and in-turn the temps were climbing up there during heavy loads. This meant to me I should dust them out, which definitely helped!

When I first setup LibreNMS to monitor these systems, they might have already had some dust in them, so that might be impacting how the ranges were generated. As such I am drawing a bit of a blank as to what a "better" method here would/could be. Perhaps having it so CPU fanspeed ranges, and how they are calculated, could be tied to CPU temperatures? Since fanspeed is important to keep temperatures down, I'm thinking this might be one of the more reliable ways to generate (or re-generate) acceptable RPM ranges, perhaps?

**Comment by laf** [comment]
I'm not sure we have a better, we can change the calculation but imho I'm not sure we should do. It's not like this is a widespread problem and you have control over adjusting the thresholds.

**Comment by BloodyIron** [comment]
I'm just trying to nip this bud before it _might_ be a problem in the future. I'm not entirely certain of the implications of leaving it be. Perhaps it might mis-inform sysadmins about safe operational parameters? I'm not sure.

**Comment by laf** [comment]
The calculations have been the same since we forked so I don't think this is going to get worse imho.
