### ISSUE TITLE
WAP 321 Platform/OS identification 

### ISSUE THREAD

**Issue by guoming218** [librenms/librenms#5172]
I have 4 WAP 321 being polled by libreNMS. 
One thing that i notices is the one running firmware Version 1.0.6.2 detected as a Linux OS/Platform
The other 3 APs is running on firmware Version 1.0.0.3 detected as Cisco Wireless Acess Point
WAP321-E-K9 which is correct.
How can I correct it?

Component | Version
--------- | -------
LibreNMS  | 969b963180ea42272c5b9c40851c683daf1c6337
DB Schema | 152
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.28-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by laf** [comment]
You've not provided any of the information asked for above

**Comment by guoming218** [comment]
Hi laf,

What other stuff do i need to add here?
thks

guoming

**Comment by laf** [comment]
Point 3 above please.

**Comment by guoming218** [comment]
[details.txt](https://github.com/librenms/librenms/files/658772/details.txt)

[session.txt](https://github.com/librenms/librenms/files/658773/session.txt)


Hi laf,

as requested:) thks for your help.

guoming
