### ISSUE TITLE
switch DELL ForceTen S4810 no CPU or Memory

### ISSUE THREAD

**Issue by cahluor** [librenms/librenms#5174]
Hello,

It seems that I can't have CPU or Memory usage on Dell Force10 S4810 plateform.

My version of Librenms is 
==========================================================
Component | Version
--------- | -------
LibreNMS  | 969b963180ea42272c5b9c40851c683daf1c6337
DB Schema | 152
PHP       | 5.6.24-0+deb8u1
MySQL     | 10.0.26-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

You can find the revellant discovery polling and snmpwalk here : http://pastebin.com/d1Rh7Cnk

It looks like LibreNMS is using a generic "DNOS" modele for Dell Network OS while switchs in the Force10 series have different OID depending if it's E-Series C-Series or S-series.

For processors index for instance : 
 OID used : .1.3.6.1.4.1.674.10895.5000.2.6132.1.1.1.1.4.9.0
should be .1.3.6.1.4.1.6027.3.10.1.2.9.1.5 for the S-series
or .1.3.6.1.4.1.6027.3.8.1.3.7.1.6 for the C-series

Mib information can be found here : https://www.force10networks.com/CSPortal20/TechTips/0016_CPUandMemoryUtilwithSNMP.aspx

Please let me know if I can do other tests

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by NerdBlender** [comment]
I don't suppose anyone has an snmpwalk for the C series or E series, or an S series other than the S4810?

**Comment by cahluor** [comment]
I have a S4048-ON  but no C or E series

Regards,
     Aubin Galinotti

**Comment by laf** [comment]
PRs merged in.
