### ISSUE TITLE
Versioning feature not working with Oxidized?

### ISSUE THREAD

**Issue by nktl** [librenms/librenms#5175]
With:

`$config['oxidized']['features']['versioning'] = true;
`

Not much 'versioning' seems to be happening under 'Config' tab:

![image](https://cloud.githubusercontent.com/assets/17342015/21233767/519af076-c2e8-11e6-9e02-0687ffa572ea.png)

You can just see the latest config, there is no option to view / compare previous versions - this happens on all various devices.

Oxidized uses git back-end I and can browse all the config commit history just fine from there.

Is this by design or am I missing something here?

**Comment by nktl** [comment]
OK, apparently there shoud be 'Config version' dropdown list, as per: https://github.com/librenms/librenms/pull/1842

But I am not seeing this. I am using LDAP authentication and my account has got 'Global Administrative Access'

**Comment by laf** [comment]
You've not provided the info asked for when opening an issue so we can't help further.
