### ISSUE TITLE
Storage Settings doesn't remember warning threshold after remount

### ISSUE THREAD

**Issue by florianbeer** [librenms/librenms#5176]
- [x] Is your install up to date?
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | 969b963180ea42272c5b9c40851c683daf1c6337
DB Schema | 152
PHP       | 5.6.29-1~dotdeb+7.1
MySQL     | 5.5.53-0+deb7u1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.4.3

I have a few servers that mount their backup disks during a nightly backup run and then unmount them after they're finished. Since I set up alarms for disks going over the defined usage threshold (Under Device > Edit >  Storage), I am getting alerts for the backup disks every night since it always looses my custom warning threshold after the disk gets unmounted. The default seems to be 60% but my backup disks are almost always > 80% full.

Is there a way to get LibreNMS to remember custom warning thresholds for storage, even if the disk gets unmounted and re-mounted frequently?

**Comment by laf** [comment]
Only thing we could do is allow config option to change the defaults.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-add-config-option-for-storage-warning-threshold/676
