### ISSUE TITLE
Add support for Dasan Networks GPON OLT V5812G

### ISSUE THREAD

**Issue by kyob** [librenms/librenms#5179]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

If it is possible please add support for **Dasan Networks GPON OLT V5812G**

Outputs:
- [Discovery](http://pastebin.com/f7rEhS8i)
- [Poller](http://pastebin.com/sbY33WK5)
- [SNMP](http://pastebin.com/J84v9sPN)

**Comment by laf** [comment]
What os name can be used for this? Any firmware name they use?

**Comment by kyob** [comment]
@laf Only numbers like 6.07

**Comment by laf** [comment]
Basic detection is being added but if you can provide the snmpwalk again but against  `.1.3.6.1.4.1.6296.9.11` rather than `.` then we can add further info.

**Comment by kyob** [comment]
I got **No Such Object available on this agent at this OID** for **.1.3.6.1.4.1.6296.9.11**

So I did [snmpwalk for .1.3.6.1.4.1.6296.9](http://pastebin.com/RyxT19NS)

**Comment by laf** [comment]
Brill :)

**Comment by aliakcza** [comment]
Is it possible to add support V8240?

      SysInfo (System Information)
      Model Name: V8240_SFU
      Main Memory Size: 1024MB
      Flash Memory Size 8 MB (SPANSION 29GL064N), 32 MB (SPANSION 29GL256N), 32 MB (SPANSION 29GL256N)
      H / W Revision: DS-A5-340-A1
      H / W Address: = [CUT] =
      RTC Information: DS174X
      Serial Number: = [CUT] =
      S / W Compatibility: 3, 7
      Package Version: RP610-003
      NOS Version: 6.10
      B / L Version: 6.04
      PLD Version: 0x11

**Comment by laf** [comment]
Please create a new issue with the info we ask for.
