### ISSUE TITLE
Add support for temperature sensor graph Smart Edge 600

### ISSUE THREAD

**Issue by kyob** [librenms/librenms#5181]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | 969b963180ea42272c5b9c40851c683daf1c6337
DB Schema | 152
PHP       | 7.0.13
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

---
**Temperature sensor graph for Smart Edge 600 (Ericsson)**

OID: 1.3.6.1.4.1.2352.2.4.1.4.1

```bash
snmpbulkwalk -OUneb -v2c -c COMMUNITY HOST .1.3.6.1.4.1.2352.2.4.1.4.1
.1.3.6.1.4.1.2352.2.4.1.4.1.2.13.1 = STRING: "Temperature sensor on slot 1"
.1.3.6.1.4.1.2352.2.4.1.4.1.2.18.1 = STRING: "Temperature sensor on slot 2"
.1.3.6.1.4.1.2352.2.4.1.4.1.2.29.1 = STRING: "Temperature sensor on slot 8 - Processor"
.1.3.6.1.4.1.2352.2.4.1.4.1.2.29.2 = STRING: "Temperature sensor on slot 8 - Exhaust Air"
.1.3.6.1.4.1.2352.2.4.1.4.1.2.29.3 = STRING: "Temperature sensor on slot 8 - Inlet Air"
.1.3.6.1.4.1.2352.2.4.1.4.1.3.13.1 = Gauge32: 0
.1.3.6.1.4.1.2352.2.4.1.4.1.3.18.1 = Gauge32: 38
.1.3.6.1.4.1.2352.2.4.1.4.1.3.29.1 = Gauge32: 48
.1.3.6.1.4.1.2352.2.4.1.4.1.3.29.2 = Gauge32: 37
.1.3.6.1.4.1.2352.2.4.1.4.1.3.29.3 = Gauge32: 30
```

Don't know if it's all necessary information if something missing give me know.

**Comment by laf** [comment]
Please provide the information asked for in point 3 at the top.

**Comment by kyob** [comment]
[discovery](http://pastebin.com/TfhtgkD9)
[poller](http://pastebin.com/HVXuChaR)
[snmpbulkwalk](http://pastebin.com/wxd48dQP)

**Comment by kyob** [comment]
[MIBS for SmartEdge (formerly redback)](https://mega.nz/#!YI0GXIhS!3pYKesTDfI-F6SY06fCBegOhSThiBN0lROHVTvLoVWo)

**Comment by kyob** [comment]
[snmp](http://pastebin.com/c7y9rRma) - updated

**Comment by laf** [comment]
We do need the full output with the commands we ask for. Try using `.1.3.6.1.4.1.2352` instead of `.`

**Comment by kyob** [comment]
@laf full output [snmp](http://pastebin.com/c7y9rRma)
