### ISSUE TITLE
Sub directory nginx reverse proxy

### ISSUE THREAD

**Issue by CodaAmok** [librenms/librenms#5183]
Hello, this is linked to https://github.com/librenms/librenms/issues/285

I set a proxy pass in my nginx conf and set base_url correctly in librenms config.php but I get lots of 404 on many items. The sub directory in the uri persists across hyperlinks but stylesheets, images and many other files get 404.

Looks like there's documentation here for Apache reverse proxy: http://docs.librenms.org/Extensions/Sub-Directory/ but can I assume support hasn't yet been added for nginx?

**Comment by laf** [comment]
We don't need to add support for nginx, it's most likely a config issue in nginx.

Please use community.librenms.org for help as this is outside of the scope for here.
