### ISSUE TITLE
Adding OS detection for older ZyWALL USG 300 firewall.

### ISSUE THREAD

**Issue by wjonker85** [librenms/librenms#5185]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by wjonker85** [comment]
Adding the following to /opt/librenms/includes/discovery/os/zywall.inc.php wil add support for ZyWALL USG 300 with older firmware.

if (strstr($sysObjectId, '.1.3.6.1.4.1.890.1.6')) {
    $os = 'zywall';
}

**Comment by wjonker85** [comment]
==========================================================
Component | Version
--------- | -------
LibreNMS  | eedd8e3c9a2ea57a34e14f3f5c099087b94dba3d
DB Schema | 152
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.28-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

**Comment by laf** [comment]
We need the poller/debug/walk output asked for at the top.

**Comment by wjonker85** [comment]
Information below. The OS should be zywall

Discovery : http://pastebin.com/41hPPbRt
Poller : http://pastebin.com/hqr9SaH3
SNMPWalk : http://pastebin.com/2uCHbFAD
