### ISSUE TITLE
Improve MIB Support of TP-Link L2 Switches

### ISSUE THREAD

**Issue by E-t-z** [librenms/librenms#5186]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.

Component | Version                                                                                         
--------- | -------                                                                                         
LibreNMS  |                                                                                                 
DB Schema | 151                                                                                             
PHP       | 7.0.13-1+deb.sury.org~xenial+1                                                                  
MySQL     | 5.5.52-MariaDB                                                                                  
RRDTool   | 1.5.5                                                                                           
SNMP      | NET-SNMP 5.7.3                
                                                                                                                                             
- [x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

Vendor MIB's:
http://static.tp-link.com/res/down/soft/TL-SG2424_V1_MIB_150713.zip
http://static.tp-link.com/res/down/soft/TL-SG2424_V2_MIB_150714.zip
http://static.tp-link.com/res/down/soft/T2600G-28TS(UN)_V1_MIB_160412.zip

~~Will, be updated with additonal info (faq#20), ASAP.~~

http://etz.planet.ee/discovery.txt
http://etz.planet.ee/poller.txt
http://etz.planet.ee/bulkwalk.txt

Currently no LAG Interface (etherchannel) graphs are shown.

**Comment by laf** [comment]
The snmpwalk doesn't seem to contain any LAG info unless I'm missing it.

Can you re-run using ` .1.3.6.1.4.1.11863.6` instead of `.`

**Comment by E-t-z** [comment]
Bulkwalk result: 
`.1.3.6.1.4.1.11863.6 = No more variables left in this MIB View (It is past the end of the MIB tree)`
