### ISSUE TITLE
Add support for Ericsson-LG Enterprise iPECS ES-3000/3000G

### ISSUE THREAD

**Issue by kyob** [librenms/librenms#5195]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | ab29261f0c7c0578fd50ab491056b7f7db025671
DB Schema | 152
PHP       | 7.0.14
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

**Ericsson-LG Enterprise iPECS ES-3000/3000G**

Outputs:
- [discovery](http://pastebin.com/DTbDuz4p)
- [poller](http://pastebin.com/qnBFBfJu)
- [SNMP](http://pastebin.com/0EATC8i3)

**Comment by laf** [comment]
What OS can these be called?

**Comment by kyob** [comment]
@laf I didn't find any name and I didn't find any firmware to upgrade.

**Comment by laf** [comment]
The snmpwalk doesn't appear to contain the info we need, please ensure the `.` is at the end.

**Comment by kyob** [comment]
Updated: [SNMP](http://pastebin.com/LVbHSWp1)

**Comment by laf** [comment]
That snmpwalk still doesn't have what we need, what command are you using?

**Comment by kyob** [comment]
I have only free account on pastebin.
[Full snmpwalk as file](https://mega.nz/#!9UsgRTzY!NAmGPylDSbUB8LwSuSoDLnw7MDhKMexdA9FyIHq5VDg)
