### ISSUE TITLE
 Add support for Solargate SG2008F

### ISSUE THREAD

**Issue by kyob** [librenms/librenms#5196]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | ab29261f0c7c0578fd50ab491056b7f7db025671
DB Schema | 152
PHP       | 7.0.14
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

**Solargate SG2008F**

Outputs:

- [discovery](http://pastebin.com/D5hxgNs2)
- [poller](http://pastebin.com/ZpxnRhmS)
- [SNMP](http://pastebin.com/h4KEbTCh)

**Comment by Rosiak** [comment]
This is some rebranded OEM switch, as I see it the only way to recognise it, is to check if the sysDescr includes SG2008F?
@librenms/reviewers ?

**Comment by murrant** [comment]
@kyob: Only thing adding support will add is an icon for this.  It basically only reports IF-MIB (ports) which is already displayed by LibreNMS.

@Rosiak yeah, sysObjectID: .0.0 is pretty silly

**Comment by kyob** [comment]
@Rosiak Yes it is rebranded OEM switch.
@murrant I guess there is no "branded" icon for that switch :) 

It looks like the only thing is to search for **SG2008F** in sysDescr as @RobsanInc said.

**Comment by laf** [comment]
Do they have any form of mibs?

**Comment by murrant** [comment]
https://ethernet.microsemi.com/knowledgebase/category/VSC7398%20(SparX-G8e%E2%84%A2)/109

**Comment by laf** [comment]
No further info provided.
