### ISSUE TITLE
SNMP applications not working

### ISSUE THREAD

**Issue by Compizfox** [librenms/librenms#5197]
After not getting any response in my [forum thread](https://community.librenms.org/t/trying-to-get-snmp-applications-working/122/1) I guess I'll open a bug report.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

Yes

- [x] Please include all of the information between the `====================================` section of `./validate.php`.

Component | Version
--------- | -------
LibreNMS  | ab29261f0c7c0578fd50ab491056b7f7db025671
DB Schema | 152
PHP       | 7.0.13-2
MySQL     | 10.0.28-MariaDB-2
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

- [x] Please provide as much detail as possible.

I'm trying to get applications through SNMP extend working. I've added the extend lines in my snmpd.conf, and snmpwalk shows it's working, I think:

	# snmpwalk -v2c -c public localhost NET-SNMP-EXTEND-MIB::nsExtendOutput2Table
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".1 = STRING: 8388608
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".2 = STRING: 8616368245
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".3 = STRING: 8616368245
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".4 = STRING: 202271
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".5 = STRING: 1037
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".6 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".7 = STRING: 332
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".8 = STRING: 3459
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".9 = STRING: 35699
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".10 = STRING: 10707
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".11 = STRING: 14649
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".12 = STRING: 15081
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".13 = STRING: 13512
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".14 = STRING: 773140
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".15 = STRING: 8036
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".16 = STRING: 2705
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".17 = STRING: 78
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".18 = STRING: 23980
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".19 = STRING: 32629
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".20 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".21 = STRING: 8191
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".22 = STRING: 2783
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".23 = STRING: 5377
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".24 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".25 = STRING: 400
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".26 = STRING: 207
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".27 = STRING: 340
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".28 = STRING: 277
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".29 = STRING: 24857
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".30 = STRING: 2103
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".31 = STRING: 711
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".32 = STRING: 16777216
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".33 = STRING: 11393016
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".34 = STRING: 151
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".35 = STRING: 10
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".36 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".37 = STRING: 2
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".38 = STRING: 4
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".39 = STRING: 2159
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".40 = STRING: 16874034
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".41 = STRING: 113
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".42 = STRING: 6
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".43 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".44 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".45 = STRING: 1174
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".46 = STRING: 88823
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".47 = STRING: 15442
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".48 = STRING: 8293
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".49 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".50 = STRING: 5939
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".51 = STRING: 6195
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".52 = STRING: 6
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".53 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".54 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".55 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".56 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".57 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".58 = STRING: 575
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".59 = STRING: 1
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".60 = STRING: 420
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".61 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".62 = STRING: 8338
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".63 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".64 = STRING: 15957431
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".65 = STRING: 270585381
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".66 = STRING: 4557
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".67 = STRING: 1411
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".68 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".69 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".70 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".71 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".72 = STRING: 112500
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".73 = STRING: 8144
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."mysql".74 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".1 = STRING: 7004
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".2 = STRING: 284418048
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".3 = STRING: .0611807
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".4 = STRING: 32592
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".5 = STRING: .214899
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".6 = STRING: 8726.62
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".7 = STRING: 40607.9
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".8 = STRING: U
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".9 = STRING: U
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".10 = STRING: 49
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".11 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".12 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".13 = STRING: 1
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".14 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".15 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".16 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".17 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".18 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".19 = STRING: 0
	NET-SNMP-EXTEND-MIB::nsExtendOutLine."apache".20 = STRING: 100

I've enabled the apache and mysql applications in LibreNMS for that device but the graphs aren't filling up.

The (relevant) output from `./poller.php -h localhost -r -d -m applications` is:

	SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -O qv -M /opt/librenms/mibs udp:HOSTNAME:161 nsExtendOutputFull.6.97.112.97.99.104.101]
	nsExtendOutputFull.6.97.112.97.99.104.101: Unknown Object Identifier (Sub-id not found: (top) -> nsExtendOutputFull)

	 apacheRRD[update /opt/librenms/rrd/localhost/app-apache-1.rrd N:U:U:U:U:U:U:U:U:U:U:U:U:U:U:U:U:U:U:U:U]
	[RRD Disabled] mysqlRRD[update /opt/librenms/rrd/localhost/app-mysql-5.rrd N:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1]
	[RRD Disabled]RRD[update /opt/librenms/rrd/localhost/app-mysql-5-status.rrd N:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1:-1]
	[RRD Disabled]

What's going wrong here?

**Comment by laf** [comment]
The lack of response is most likely because people don't know. Applications are the least developed / used / supported part of the software and haven't had much attention since the fork.

**Comment by laf** [comment]
Please post your snmpd.conf file.

**Comment by Compizfox** [comment]
Of course. The config file is this (I stripped the comments):

	rocommunity  public  

	disk  / 
	load  50 50 50

	syslocation foobar
	syscontact  foo@bar.tld

	sysservices 76

	extend apache /opt/librenms-agent/snmp/apache-stats
	extend mysql /opt/librenms-agent/snmp/mysql-stats

**Comment by laf** [comment]
Can you also confirm your net-snmpd version pls

**Comment by Compizfox** [comment]
My NET-SNMP is still at 5.7.3.

**Comment by laf** [comment]
Can you try:  `/usr/bin/snmpget -v2c -c COMMUNITY -O qv -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.8072.1.3.2.3.1.2.6.97.112.97.99.104.101` Replace community and hostname.

Can you also check if you have anything in /etc/snmp/snmp.conf and if so, try removing that file.

**Comment by Compizfox** [comment]
The contents of my `/etc/snmp/snmp.conf` is this:

    # As the snmp packages come without MIB files due to license reasons, loading
    # of MIBs is disabled by default. If you added the MIBs you can reenable
    # loading them by commenting out the following line.
    mibs :

I tried commenting out that last line but it does not make any difference in the output of `poller.php`.

You command seems to return the correct output:

    "112625
    75809396736
    .00149335
    4132320
    .0272547
    18345.5
    673113
    U
    U
    49
    0
    0
    1
    0
    0
    0
    0
    0
    0
    100"

It also works without the `-M` option and the protocol and port specification, like `snmpget -v2c -c public -O qv illium .1.3.6.1.4.1.8072.1.3.2.3.1.2.6.97.112.97.99.104.101`.

**Comment by laf** [comment]
I've just submitted a patch if you would like to test: https://github.com/librenms/librenms/pull/6277

**Comment by Compizfox** [comment]
Thanks, this seems to be working!
