### ISSUE TITLE
Clearing Alets & Events, and dealing with Syslogs 

### ISSUE THREAD

**Issue by hbadreldin** [librenms/librenms#5201]
Hello Team,

I have installed the latest LibreNMS on Redhat7.

All working OK, but I'm having hard time figuring out how I can clear Alerts and Events? Is it available somewhere where I can clear muted or OK stats? Will they fill the database or they have a rotation?  

What about my Syslog, for how many days will it keep logs before purging them? Is there a place where I can tweak such variables? 

Let me know if you need any information. 

Thanks,
Hosam

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by laf** [comment]
http://docs.librenms.org/Support/Configuration/#cleanup-options

This isn't really an issue, for general questions and help please login to our irc channel or community.librenms.org site.

**Comment by hbadreldin** [comment]
Thanks. Will do the IRC way in the future.
