### ISSUE TITLE
Mac address search fails for VNET or VMs

### ISSUE THREAD

**Issue by djtecha** [librenms/librenms#5202]
Looks like when you search for the mac address of a VM it fails to locate. Same for the VNET attached to the HOST VM. Curious if others are having this same issue?

**Comment by sorano** [comment]
Use the ARP Tables search and enter the MAC then you should be able to locate your VM's

**Comment by djtecha** [comment]
Ahh thanks that works. Is there a reason this aspect is not in the "Global search?"

**Comment by laf** [comment]
Support has to be added, no one's asked for it before.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-add-mac-address-search-to-global-search/675
