### ISSUE TITLE
Add support for Ubiquiti Discovery Protocol in Autodiscovery

### ISSUE THREAD

**Issue by keefe007** [librenms/librenms#5204]
Can you please add support for Ubiquiti's Discovery Protocol in Auto-discovery?

**Comment by laf** [comment]
Any documentation about this?

**Comment by jquagga** [comment]
I'm not sure on this, but for Unifi devices (UAPs) doesn't this service stop once an AP is adopted by a controller?  On my EdgeRouter / Edgeswitch it seems to stay on after configuration, unless I turn it off.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-add-support-for-ubiquiti-discovery-protocol-in-autodiscovery/887
