### ISSUE TITLE
Add support for Liebert eXM UPS

### ISSUE THREAD

**Issue by beerpongchamp** [librenms/librenms#5209]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

==========================================================
Component | Version
--------- | -------
LibreNMS  | 4898617ef52bed41c36ad33afc3a0af5570484c7
DB Schema | 153
PHP       | 7.0.10
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful
[FAIL]  You have a different system timezone (EST) specified to the php configured timezone (UTC), please correct this.

[poller.txt](https://github.com/librenms/librenms/files/666587/poller.txt)
[snmpbulkwalk.txt](https://github.com/librenms/librenms/files/666588/snmpbulkwalk.txt)
[discovery.txt](https://github.com/librenms/librenms/files/666589/discovery.txt)

**Comment by beerpongchamp** [comment]
The unit is currently being polled and has data from the SNMP agent.  It just has incorrect values.  They look to be correct with the exception that the decimal is in the wrong place.  Wattage for power phases is completely wrong and I'm not sure that can be fixed easily.  

I am in the process of trying to find the MIBs for the unit.

**Comment by beerpongchamp** [comment]
[SNMP_upsMibEvents.txt](https://github.com/librenms/librenms/files/668732/SNMP_upsMibEvents.txt)
[SNMP_upsMibParams.txt](https://github.com/librenms/librenms/files/668731/SNMP_upsMibParams.txt)

**Comment by laf** [comment]
This at present is using the rfc1628 (UPS-MIB). The two links you've sent aren't mibs and are just a list of OIDs.

Either the device has proper mibs and we need to use the info from those or it is sending back bad data for rfc1628 mib.

**Comment by laf** [comment]
No further info provided.
