### ISSUE TITLE
Add support for D-Link 6600AP

### ISSUE THREAD

**Issue by hackman61** [librenms/librenms#5210]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | 6d027c57539fab1540917d36373ef0143fffdc1c
DB Schema | 153
PHP       | 5.5.9-1ubuntu4.20
MySQL     | 5.5.52-MariaDB-1ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

Hello,

I want to know if you can integrate this wireless access point : http://www.dlink.com/fr/fr/business-solutions/wireless/wireless-access-points/dwl-6600ap-unified-wireless-n-simultaneous-dual-band-poe-access-point ==> It's a DWL-6600AP

Here are : 

- Discovery : http://pastebin.com/eiVUEyP2
- Poller : http://pastebin.com/aNc17eRF
- Snmpwalk : http://pastebin.com/Sz55A9DY

In attachment the two file for MIBS

Let me know if that not enought for you :) 

[dlinkap6600.txt](https://github.com/librenms/librenms/files/666677/dlinkap6600.txt)
[dlinkref.txt](https://github.com/librenms/librenms/files/666678/dlinkref.txt)

**Comment by laf** [comment]
That snmpwalk output doesn't contain any of the normal snmp info, can you please re-run it and make sure you have the `.` at the end.

Looking at the poller/discovery info - it appears the sysObjectId isn't D-Links so we can't use that and the sysDescr is linux based.

**Comment by hackman61** [comment]
@laf  here is the new snmpwalk : http://pastebin.com/7ZRVXRvA , at the end it gave me a Timeout: No Response from dwl-6600ap.domoce.local

You cannot use this : entPhysicalName.1 = D-Link AP ?

**Comment by laf** [comment]
We possibly could but sysObjectId is much better. We don't detect any other devices using entPhysicalName and that's most likely for a reason.

**Comment by hackman61** [comment]
Ok, thank you :) So at this moment, it's not possible. I will ask D-link to know if they can change them SNMP info for this product.

**Comment by laf** [comment]
Let us know when you have more info from them.
