### ISSUE TITLE
Toggle switches render incorrectly on Blink browsers when zoomed

### ISSUE THREAD

**Issue by jquagga** [librenms/librenms#5219]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php`.
```
==========================================================
Component | Version
--------- | -------
LibreNMS  | 4898617ef52bed41c36ad33afc3a0af5570484c7
DB Schema | 153
PHP       | 7.0.14
MySQL     | 10.1.19-MariaDB
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================
```
- [X] Please provide as much detail as possible.

Good day,

So on recent Blink powered browsers (Chromium and Opera have been tested), if page zoom is applied, then toggle switches render incorrectly.  Here a picture is worth 1000 words so here's two screenshots of Chrome.  The first at 125% which I normally run at and then at 100% (where the problem goes away).  All of the toggles do this, but the about page was a good example.  

This appears to be Webkit / blink specific as I tried this in Firefox and there the switches appeared normal.  

![out-fs8](https://cloud.githubusercontent.com/assets/5832772/21405065/522c4a9a-c792-11e6-9e8b-7caef8a98811.png)

**Comment by laf** [comment]
This looks to be something that needs fixing in bootstrap-switch (nostalgiaz/bootstrap-switch#602) - possibly related.

**Comment by laf** [comment]
I've had a look more into this and one recommended fix doesn't work. I've also looked at an alternative to boostrap-switch and found http://www.bootstraptoggle.com/ but that is also not actively developed for 2 years and we could just come across more issues.

Not sure I see what else we can do at this stage :(

**Comment by jquagga** [comment]
Yeah, I kinda figured this was going to be something Chrome had to fix.  I just wanted to note it in case the question comes up from other folks (or there was some magical fix).  

If you're zoomed more than 100%, it'll do this. So just tell people to un-zoom and move closer to the screen :-).  Or you know, use Firefox.

**Comment by laf** [comment]
Actually - do all toggle switches do this for you? Check some others like the edit device -> modules and see. Maybe we can fix.

**Comment by jquagga** [comment]
Actually you're right, the modules are fine on Device - modules.  The one I notice which is broken is on the About page - the on/off for submitting stats.  
![screenshot-fs8](https://cloud.githubusercontent.com/assets/5832772/22438608/a2db5c42-e6fa-11e6-8929-13f732bc53f5.png)
