### ISSUE TITLE
Alert Rules Parentheses for OR statements

### ISSUE THREAD

**Issue by pblasquez** [librenms/librenms#5220]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x ] Please provide as much detail as possible.

When creating an alert rule with a chain of ORs, my expected behavior is that the ORs will all be evaluated within a set of parentheses.  This is not the behavior of the underlying abstraction right now. Please notice the missing parentheses below:

Example alert rule: `%bgpPeers.bgpPeerAdminStatus = "running" && %bgpPeers.bgpPeerState != "established" && %macros.device_up = "1"    && %bgpPeers.bgpPeerRemoteAs = "1234" || %bgpPeers.bgpPeerRemoteAs = "2345"   || %bgpPeers.bgpPeerRemoteAs = "3456" || %bgpPeers.bgpPeerRemoteAs = "4567"`

Expected SQL:

SELECT * FROM bgpPeers,devices
WHERE ((devices.device_id = bgpPeers.device_id) && bgpPeers.device_id = ?) && (bgpPeers.bgpPeerAdminStatus = "running" && bgpPeers.bgpPeerState != "established" && ((devices.STATUS = 1 && ((devices.disabled = 0 && devices.ignore = 0)))) = "1" && **(bgpPeers.bgpPeerRemoteAs = "1234" || bgpPeers.bgpPeerRemoteAs = "2345" || bgpPeers.bgpPeerRemoteAs = "3456" || bgpPeers.bgpPeerRemoteAs = "4567")** )

Actual SQL:

SELECT * FROM bgpPeers,devices
WHERE ((devices.device_id = bgpPeers.device_id) && bgpPeers.device_id = ?) && (bgpPeers.bgpPeerAdminStatus = "running" && bgpPeers.bgpPeerState != "established" && ((devices.STATUS = 1 && ((devices.disabled = 0 && devices.ignore = 0)))) = "1" && **bgpPeers.bgpPeerRemoteAs = "1234" || bgpPeers.bgpPeerRemoteAs = "2345" || bgpPeers.bgpPeerRemoteAs = "3456" || bgpPeers.bgpPeerRemoteAs = "4567"** )

This causes the alert to fire every time it finds an AS in the list, regardless of the evaluation of the rest of the statement. With parentheses, the entire statement is evaluated in addition to evaluating all of the ORs in one operation, which is the behavior I expect.

I am working around this right now by updating the SQL in the DB manually, however it would be nice if the UI used parentheses by default, or if this is an unusual request, that an option were given.

Please know that I appreciate all the work you guys do!

**Comment by laf** [comment]
What you're seeing is expected behaviour - whether we could fix this by detecting OR's and adding () is another question I guess (we possibly) can.

The advice for people doing what you are doing is to create this as a macro as you can use () within that yourself.

**Comment by pblasquez** [comment]
My concern is that right now, ORs are absolute.  Alerts will trigger on any OR statement that is true, regardless of the beginning of the clause.  So that means tests are very broad with no way to narrow down targets (if you want to test OR conditions).

I have a patch on my local instance to add the parentheses but it is pretty ugly, doing splits, lookaheads and lookbehinds to chop out the ORs in order to insert the parentheses in the right spots.

I guess I'll look into creating a macro to do it instead.

**Comment by laf** [comment]
Feel free to post the code and we and see about including it.

OR's are ok if it's a simple two entity check, anything more and yes people will come across this issue.

**Comment by pblasquez** [comment]
Was able to get this working with just macros, thanks!

For future reference, here was what I used:

`%bgpPeers.bgpPeerState != "established" && %macros.device_up = "1" && %bgpPeers.bgpPeerAdminStatus = "running" && %macros.transit_peer_ases = "1"`

And the macro is as such:

`(%bgpPeers.bgpPeerRemoteAs = "1234" || %bgpPeers.bgpPeerRemoteAs = "2345"   || %bgpPeers.bgpPeerRemoteAs = "3456" || %bgpPeers.bgpPeerRemoteAs = "4567" || %bgpPeers.bgpPeerRemoteAs = "5678")`

**Comment by pblasquez** [comment]
I can share my hatchet job if you like but don't say I didn't warn you! :)

Insert between lines 85 and 86 of includes/alerts.inc.php:

```
    # only need to work on the WHERE statement, so save the beginning as-is
    $or_where = split(' WHERE ', $sql);
    $or_str = $or_where[0] . ' WHERE ';

    # create an array of the OR statements in the WHERE
    $or_arr = split(' \|\| ', $or_where[1]);

    # Declare flag
    $or_flag=0;

    # If we found more than 1 OR statement, add parentheses
    if (isset($or_arr) && count($or_arr) >=2) {
      foreach ($or_arr as $or_seg) {
       # This begins each OR statement with a ( and sets the flag. Repeat after each AND statement.
       # (The beginning of the statement is assumed to always have an AND because defaults)
        if ($or_flag==0) {
          $or_str = $or_str . preg_replace("/ && (?!.* && )/", " && ( ", $or_seg);
          $or_flag=1;
          continue;
        }

        # If we see an AND, the OR sequence must be over (the UI doesn't allow nesting)
        # so close the parentheses and reset the flag
        if (strpos($seg, ' && ')) {
          $or_str = $or_str . " || " . preg_replace("/ && /", " ) && ", $or_seg, 1);
          $or_flag=0;
          continue;
        }

        # Add back the OR for everything in the sequence
        $or_str = $or_str . " || " . $or_seg;
      }

      # If the statement ends without another AND, close parentheses
      if ($or_flag == 1) {
        $or_str = $or_str . " ) ";
      }
    }
    return $or_str;
```

If you actually want to use this or some modified version I'll drop a PR without the comments.

**Comment by laf** [comment]
@pblasquez If you'd like to PR this that would be great. I'd say leave the comments in and probably do it as a function so it's not messing with the current flow.

**Comment by murrant** [comment]
You could just backport the rule editor from v2...

**Comment by laf** [comment]
Didn't think we had an alert rule page for v2 yet.

**Comment by murrant** [comment]
@laf the device group rule editor is the same as the alert rule editor effectively.  But yes, the alerts one hadn't been implemented yet.

**Comment by laf** [comment]
Ok. Regardless this is about how the backend builds the query anyway so not sure the updated ui would help

**Comment by laf** [comment]
If you would like to use OR in alert rules still. We have a new UI for you to test: https://github.com/librenms/librenms/pull/8293
