### ISSUE TITLE
Cant install oxidized by http call

### ISSUE THREAD

**Issue by joseaugustocardoso** [librenms/librenms#5227]
When I trying to configure the oxidized  to read device list on librenms by http, I receving the error:

[oxidized@librenms oxidized]$ oxidized
I, [2016-12-22T15:22:11.129255 #27099]  INFO -- : Oxidized starting, running as pid 27099
I, [2016-12-22T15:22:11.176658 #27099]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2016-12-22T15:22:11.235753 #27099] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
cannot interpret as DNS name: nil
/usr/share/ruby/resolv.rb:1195:in `create': cannot interpret as DNS name: nil (ArgumentError)

**Comment by laf** [comment]
That says to me that one of your devices doesn't resolve dns correctly

**Comment by laf** [comment]
@joseaugustocardoso you can run

`curl -H 'X-Auth-Token: YOUR_TOKEN' https://YOUR_URL/api/v0/oxidized`

To get the output, see if any of the hostnames look incorrect.

**Comment by joseaugustocardoso** [comment]
It working now..
With your command, I saw the correct group name "all" and updated my oxidized config file
Thank you.

**Comment by laf** [comment]
glad you got it working.
