### ISSUE TITLE
Add support for Turbo NAS TS-431

### ISSUE THREAD

**Issue by NK74** [librenms/librenms#5229]
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.

| Component | Version|
| --- | --- |
| LibreNMS   | 5aef36abd653061db7fe547997bac8b87a9f10c6|
| DB Schema | 159 |
| PHP       | 7.0.8-3ubuntu3
| MySQL     | 10.0.28-MariaDB-0ubuntu0.16.10.1
| RRDTool   | 1.6.0
| SNMP      | NET-SNMP 5.7.3

- [x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

![image](https://cloud.githubusercontent.com/assets/17825769/21432838/9cedecce-c86d-11e6-9006-b8045caaabb1.png)

Turbo NAS TS-431 MIB
Discovery : http://pastebin.com/QKF6aT5C
Poller: http://pastebin.com/4P72gP6i
snmpbulkwalk: http://pastebin.com/fBknPQx4

http://pastebin.com/zSfqZJkX
http://www115.zippyshare.com/v/3lzdM7Vo/file.html

**Comment by laf** [comment]
What are you actually asking for here? If this is to add detection for a device then you need to provide the information we ask for at the top.

**Comment by NK74** [comment]
Newly added files 👍

**Comment by NK74** [comment]
Up :)

**Comment by NK74** [comment]
Hi,

Do you have domr news about my device ?

**Comment by laf** [comment]
The snmpwalk doesn't seem to contain the info we need. Did you specify the `.` at the end of the command?

**Comment by NK74** [comment]
Hi @laf ,

snmpbulkwalk : http://pastebin.com/wiK4v6rY

**Comment by laf** [comment]
That's marked as private

**Comment by NK74** [comment]
My apologies...

Try now it's "Unlisted"

**Comment by laf** [comment]
It still doesn't contain things like sysDescr and sysObjectId - what command have you run?

**Comment by NK74** [comment]
snmpbulkwalk -OUneb -v2c -c public 192.168.1.144 . > smpbulwalk.log

**Comment by NK74** [comment]
Now : **snmpwalk -OUneb -v1 -c public 192.168.1.144 > snmpbulkwalk-23-01.log**

http://pastebin.com/VWQxeSCp

**Comment by laf** [comment]
Can you try .1.3.6.1.2.1.1

No sysObjectId in that output still, that's not impossible but I hope they don't exclude it!

**Comment by NK74** [comment]
```
root@nms:~# snmpwalk -OUneb -v2c -c public 192.168.1.144 .1.3.6.1.2.1.1
.1.3.6.1.2.1.1.1.0 = STRING: "Linux TS-X31 4.2.2"
.1.3.6.1.2.1.1.9.1.2.1 = OID: .1.3.6.1.6.3.11.2.3.1.1
.1.3.6.1.2.1.1.9.1.2.2 = OID: .1.3.6.1.6.3.15.2.1.1
.1.3.6.1.2.1.1.9.1.2.3 = OID: .1.3.6.1.6.3.10.3.1.1
.1.3.6.1.2.1.1.9.1.2.4 = OID: .1.3.6.1.6.3.1
.1.3.6.1.2.1.1.9.1.2.5 = OID: .1.3.6.1.2.1.49
.1.3.6.1.2.1.1.9.1.2.6 = OID: .1.3.6.1.2.1.4
.1.3.6.1.2.1.1.9.1.2.7 = OID: .1.3.6.1.2.1.50
.1.3.6.1.2.1.1.9.1.2.8 = OID: .1.3.6.1.6.3.16.2.2.1
.1.3.6.1.2.1.1.9.1.3.1 = STRING: "The MIB for Message Processing and Dispatching."
.1.3.6.1.2.1.1.9.1.3.2 = STRING: "The MIB for Message Processing and Dispatching."
.1.3.6.1.2.1.1.9.1.3.3 = STRING: "The SNMP Management Architecture MIB."
.1.3.6.1.2.1.1.9.1.3.4 = STRING: "The MIB module for SNMPv2 entities"
.1.3.6.1.2.1.1.9.1.3.5 = STRING: "The MIB module for managing TCP implementations"
.1.3.6.1.2.1.1.9.1.3.6 = STRING: "The MIB module for managing IP and ICMP implementations"
.1.3.6.1.2.1.1.9.1.3.7 = STRING: "The MIB module for managing UDP implementations"
.1.3.6.1.2.1.1.9.1.3.8 = STRING: "View-based Access Control Model for SNMP."
.1.3.6.1.2.1.1.9.1.4.1 = Timeticks: (35) 0:00:00.35
.1.3.6.1.2.1.1.9.1.4.2 = Timeticks: (35) 0:00:00.35
.1.3.6.1.2.1.1.9.1.4.3 = Timeticks: (35) 0:00:00.35
.1.3.6.1.2.1.1.9.1.4.4 = Timeticks: (35) 0:00:00.35
.1.3.6.1.2.1.1.9.1.4.5 = Timeticks: (35) 0:00:00.35
.1.3.6.1.2.1.1.9.1.4.6 = Timeticks: (35) 0:00:00.35
.1.3.6.1.2.1.1.9.1.4.7 = Timeticks: (35) 0:00:00.35
.1.3.6.1.2.1.1.9.1.4.8 = Timeticks: (35) 0:00:00.35
```

**Comment by NK74** [comment]
Hi @laf 

Which information is missing ? send me the specified command (i'm newbie with librenms)

**Comment by laf** [comment]
Nothing, this device is not sending back a sysObjectId for us to use to do detection. We will have to look at an alternative.

**Comment by NK74** [comment]
If you need official product MIB file tell me 👍

**Comment by laf** [comment]
Please upload it.

**Comment by NK74** [comment]
Here,

[QNAP-TS-431.zip](https://github.com/librenms/librenms/files/737135/QNAP-TS-431.zip)

**Comment by NK74** [comment]
what's new about this issue @laf

How i can help you ? :)

**Comment by laf** [comment]
This mib has everything in  .1.3.6.1.4.1.24681.1 and your output doesn't contain any data from within that. Try:

`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .1.3.6.1.4.1.24681.1`

**Comment by NK74** [comment]
Hi @laf ,

Here: https://gist.github.com/NK74/f7569aaaa478b860bc9b35c394b9c9a0

**Comment by NK74** [comment]
![cpu](https://cloud.githubusercontent.com/assets/17825769/22687375/0ea1fa3e-ed28-11e6-8d0b-2228319f2fa9.png)

**Comment by NK74** [comment]
Missing HDD temperature output, and HDD SMART status.

![image](https://cloud.githubusercontent.com/assets/17825769/22777804/b5ffc9cc-eeb4-11e6-8e81-225cd80b80a8.png)


## I found on SNMPBULKWALK
**Temperature**

> .1.3.6.1.4.1.24681.1.2.11.1.3.1 = STRING: "44 C/111 F"
> .1.3.6.1.4.1.24681.1.2.11.1.3.2 = STRING: "46 C/114 F"
> .1.3.6.1.4.1.24681.1.2.11.1.3.3 = STRING: "43 C/109 F"
> .1.3.6.1.4.1.24681.1.2.11.1.3.4 = STRING: "-- C/-- F"

or

> .1.3.6.1.4.1.24681.1.4.1.1.1.1.5.2.1.6.1 = INTEGER: 44
> .1.3.6.1.4.1.24681.1.4.1.1.1.1.5.2.1.6.2 = INTEGER: 46
> .1.3.6.1.4.1.24681.1.4.1.1.1.1.5.2.1.6.3 = INTEGER: 43
> .1.3.6.1.4.1.24681.1.4.1.1.1.1.5.2.1.6.4 =

**HDD Product Number**

> .1.3.6.1.4.1.24681.1.2.11.1.5.1 = STRING: "ST2000NM0033-9ZM175"
> .1.3.6.1.4.1.24681.1.2.11.1.5.2 = STRING: "ST2000NM0033-9ZM175"
> .1.3.6.1.4.1.24681.1.2.11.1.5.3 = STRING: "ST2000NM0033-9ZM175"
> .1.3.6.1.4.1.24681.1.2.11.1.5.4 = STRING: "--"

**HDD Size and HDD Status**

> .1.3.6.1.4.1.24681.1.2.11.1.6.1 = STRING: "1863.02 GB"
> .1.3.6.1.4.1.24681.1.2.11.1.6.2 = STRING: "1863.02 GB"
> .1.3.6.1.4.1.24681.1.2.11.1.6.3 = STRING: "1863.02 GB"
> .1.3.6.1.4.1.24681.1.2.11.1.6.4 = STRING: "--"
> .1.3.6.1.4.1.24681.1.2.11.1.7.1 = STRING: "GOOD"
> .1.3.6.1.4.1.24681.1.2.11.1.7.2 = STRING: "GOOD"
> .1.3.6.1.4.1.24681.1.2.11.1.7.3 = STRING: "GOOD"
> .1.3.6.1.4.1.24681.1.2.11.1.7.4 = STRING: "--"

**RAID Status volume**

> .1.3.6.1.4.1.24681.1.2.17.1.2.1 = STRING: "[Volume DataVol1]"
> .1.3.6.1.4.1.24681.1.2.17.1.3.1 = STRING: "EXT4"
> .1.3.6.1.4.1.24681.1.2.17.1.4.1 = STRING: "3.53 TB" (Total volume size)
> .1.3.6.1.4.1.24681.1.2.17.1.5.1 = STRING: "2.93 TB" (Free space on volume)
> .1.3.6.1.4.1.24681.1.2.17.1.6.1 = STRING: "Ready"
>

**Comment by laf** [comment]
You didn't actually ask for any of that information!

**Comment by NK74** [comment]
Hi @laf ,

Sorry i misunderstood, i've write aforementioned the String for missing information on this model

**Comment by NK74** [comment]
Wich file i need to edit for this device snmp output ?

**Comment by laf** [comment]
I don't think this is an issue, please ensure you are upto date and once you are re-provide the full poller and discovery output asked for in point 3.

**Comment by NK74** [comment]
Up to date ...

| Component | Version|
| --- | --- |
| LibreNMS   | d06aaaa222fefc083dd1c60dce1ad1cbbaf8100b|
| DB Schema | 164 |
| PHP       | 7.0.13-0ubuntu0.16.10.1
| MySQL     |  10.0.29-MariaDB-0ubuntu0.16.10.1
| RRDTool   | 1.6.0
| SNMP      | NET-SNMP 5.7.3

**discovery :** https://gist.github.com/NK74/c7ec495b59438667d1be4e6d324da40a
**poller :** https://gist.github.com/NK74/4fe6d362dc086171292ec0c289d3924f
**snmpbulkwalk :** https://gist.github.com/NK74/3d78bbfffa7516175892c11b6ac6419e

**Comment by laf** [comment]
Please run `/usr/bin/snmpwalk -v2c -c COMMUNITY -OUQnt -M /opt/librenms/mibs -t 1 -r 1 udp:HOSTNAME:161 1.3.6.1.4.1.24681.1.2.11.1.3.3.6.1.4` - replace COMMUNITY and HOSTNAME with the relevant details.

Can you also join irc to discuss this pls?

**Comment by NK74** [comment]
Work fine for me 👍 

![image](https://cloud.githubusercontent.com/assets/17825769/23069455/d0057352-f527-11e6-9113-1e25b7ab8916.png)
