### ISSUE TITLE
Enhancement: Add GateOne Terminal Emulator Integration

### ISSUE THREAD

**Issue by clay584** [librenms/librenms#5233]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

It would be a really cool function to add a js keyboard shortcut (quake style) to bring up a GateOne  terminal emulator over Libre. Then use the html5 terminal emulator to log into devices.  You could pass the hostname to GateOne to go ahead and ssh to a node if you are on a node-specific page within Libre.

You could put in a global setting to enable it so those who don't want to use it can still use their client's event handlers like normal.

Gateone: https://github.com/liftoff/GateOne

GateOne integration docs: https://liftoff.github.io/GateOne/Developer/embedding.html

**Comment by clay584** [comment]
GateOne demo 

https://youtu.be/gnVohdlZXVY

**Comment by clay584** [comment]
URL params for SSH'ing directly to a device with gateone.

https://hostname/?ssh=ssh://username@routerHostname

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-add-gateone-terminal-emulator-integration/672

**Comment by laf** [comment]
FYI basic support for this has been added.
