### ISSUE TITLE
Graphs and Traffic arrows Emtpy, RDD files are written and polled.

### ISSUE THREAD

**Issue by Yamakasi** [librenms/librenms#5241]
I have an installation which seems to be validated fine and also has collecting data in it's RRD files but doesn't show anything in it's graphs.

When I add &debug=true to a graph it's URL all is OK at the botton of the debug log.

My validation looks like this:
```

root@netmon-01:/opt/librenms# ./validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | d121e43feb260f327736402dbcbc1b8ab33b6e05
DB Schema | 153
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 5.6.32-78.1-56-log
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================
[OK]    Database connection successful
```

I want to give as much detail as possible but as there are no errors shown and RDD files are perfectly filled (and the poller.php also runs fine and it's cron as well) I wonder what I can check or what could be wrong here.

Ideas are very welcome as this was a working setup and happened after updated to the latest version.
```

./daily.sh also works fine:

root@netmon-01:/opt/librenms# su "librenms" -c "./daily.sh"
Updating to latest codebase                        OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
root@netmon-01:/opt/librenms#
```

**Comment by laf** [comment]
Right click one of the graphs, copy the IMAGE url, add &debug=true to the end and pastebin the output.

**Comment by Yamakasi** [comment]
Hi Laf, here you go:

`graph /tmp/FdXn8xsiITnwZZ8Z.png --alt-autoscale-max --rigid -E --start 1482688200 --end 1482774600 --width 335 --height 156 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal DEF:outoctets=/home/vhosts/netmon.mydomain.net/www/rrd/bcknd-sw-01.mydomain.net/port-id46189.rrd:OUTOCTETS:AVERAGE DEF:inoctets=/home/vhosts/netmon.mydomain.net/www/rrd/bcknd-sw-01.mydomain.net/port-id46189.rrd:INOCTETS:AVERAGE DEF:outoctets_max=/home/vhosts/netmon.mydomain.net/www/rrd/bcknd-sw-01.mydomain.net/port-id46189.rrd:OUTOCTETS:MAX DEF:inoctets_max=/home/vhosts/netmon.mydomain.net/www/rrd/bcknd-sw-01.mydomain.net/port-id46189.rrd:INOCTETS:MAX CDEF:octets=inoctets,outoctets,+ CDEF:doutoctets=outoctets,-1,* CDEF:outbits=outoctets,8,* CDEF:outbits_max=outoctets_max,8,* CDEF:doutoctets_max=outoctets_max,-1,* CDEF:doutbits=doutoctets,8,* CDEF:doutbits_max=doutoctets_max,8,* CDEF:inbits=inoctets,8,* CDEF:inbits_max=inoctets_max,8,* VDEF:totin=inoctets,TOTAL VDEF:totout=outoctets,TOTAL VDEF:tot=octets,TOTAL CDEF:d95thoutn=doutbits,-1,* VDEF:d95thoutn95=d95thoutn,95,PERCENT CDEF:d95thoutn95n=doutbits,doutbits,-,d95thoutn95,-1,*,+ VDEF:d95thout=d95thoutn95n,FIRST VDEF:95thin=inbits,95,PERCENT VDEF:95thout=outbits,95,PERCENT COMMENT:'bps Now Ave Max 95th %\n' AREA:inbits_max#D7FFC7: AREA:inbits#90B040: LINE:inbits#608720:'In ' GPRINT:inbits:LAST:%6.2lf%s GPRINT:inbits:AVERAGE:%6.2lf%s GPRINT:inbits_max:MAX:%6.2lf%s GPRINT:95thin:%6.2lf%s\n AREA:doutbits_max#E0E0FF: AREA:doutbits#8080C0: LINE:doutbits#606090:'Out' GPRINT:outbits:LAST:%6.2lf%s GPRINT:outbits:AVERAGE:%6.2lf%s GPRINT:outbits_max:MAX:%6.2lf%s GPRINT:95thout:%6.2lf%s\n GPRINT:tot:'Total %6.2lf%sB' GPRINT:totin:'(In %6.2lf%sB' GPRINT:totout:'Out %6.2lf%sB)\l' LINE1:95thin#aa0000 LINE1:d95thout#aa0000

command returned (416x253 OK u:0.07 s:0.03 r:0.07 )

-rw-rw-r-- 1 www-data www-data 7756 Dec 26 18:53 /tmp/FdXn8xsiITnwZZ8Z.png graph
Runtime 0.203s
SNMP: Get[0/0.00s] Walk [0/0.00s] MySQL: Cell[3/0.01s] Row[2/-0.01s] Rows[5/0.00s] Column[0/0.00s] Update[0/0.00s] Insert[0/0.00s] Delete[1/0.00s]`

**Comment by laf** [comment]
That looks fine - do you see no data in graphs?

Got a screenshot?

**Comment by Yamakasi** [comment]
Yes I thought the same, here a screenshot:
![port](https://cloud.githubusercontent.com/assets/4869479/21486817/7061e9b6-cbbb-11e6-9860-f0d06dcdc662.PNG)

**Comment by laf** [comment]
That shows to me that data isn't in the rrd files.

Run: `./poller.php -h HOSTNAME -v -r -f -m ports`

You will see some rrdtool update commands, do they say anything? Try copying the command and pasting it into your ssh sessions, see what the response is.

**Comment by Yamakasi** [comment]
OK, this could be as RRD is disabled using the following log, I took a part from as it as was kinda huge as you know.

I asked it before on IRC but didn't got a response, so let's see if you can get something out of it here.

`
 ifOutErrors (0 B) 0 Bps 301 secs

 ifInNUcastPkts (0 B) 0 Bps 301 secs

 ifOutNUcastPkts (0 B) 0 Bps 301 secs

 ifInDiscards (0 B) 0 Bps 301 secs

 ifOutDiscards (0 B) 0 Bps 301 secs

 ifInUnknownProtos (0 B) 0 Bps 301 secs

 ifInBroadcastPkts (0 B) 0 Bps 301 secs

 ifOutBroadcastPkts (0 B) 0 Bps 301 secs

 ifInMulticastPkts (0 B) 0 Bps 301 secs

 ifOutMulticastPkts (0 B) 0 Bps 301 secs
bps(0bps/0bps)bytes(0B/0B)pkts(0pps/0pps)RRD[update /home/vhosts/netmon.mydomain.net/www/rrd/bcknd-sw-01.mydomain.net/port-id46189.rrd N:U:U:0:0:U:U:U:U:0:0:U:0:0:0:0]
[RRD Disabled]SQL[UPDATE `ports` set `poll_time` ='1482810011',`poll_prev` ='1482809710',`poll_period` ='301',`ifLastChange` ='2132',`ifInErrors` ='0',`ifInErrors_prev` ='0',`ifInErrors_rate` ='0',`ifInErrors_delta` ='0',`ifOutErrors` ='0',`ifOutErrors_prev` ='0',`ifOutErrors_rate` ='0',`ifOutErrors_delta` ='0' WHERE `port_id` = '46189']
SQL[UPDATE `ports_statistics` set `ifInNUcastPkts` ='',`ifInNUcastPkts_prev` ='0',`ifInNUcastPkts_rate` ='0',`ifInNUcastPkts_delta` ='0',`ifOutNUcastPkts` ='',`ifOutNUcastPkts_prev` ='0',`ifOutNUcastPkts_rate` ='0',`ifOutNUcastPkts_delta` ='0',`ifInDiscards` ='0',`ifInDiscards_prev` ='0',`ifInDiscards_rate` ='0',`ifInDiscards_delta` ='0',`ifOutDiscards` ='0',`ifOutDiscards_prev` ='0',`ifOutDiscards_rate` ='0',`ifOutDiscards_delta` ='0',`ifInUnknownProtos` ='',`ifInUnknownProtos_prev` ='0',`ifInUnknownProtos_rate` ='0',`ifInUnknownProtos_delta` ='0',`ifInBroadcastPkts` ='0',`ifInBroadcastPkts_prev` ='0',`ifInBroadcastPkts_rate` ='0',`ifInBroadcastPkts_delta` ='0',`ifOutBroadcastPkts` ='0',`ifOutBroadcastPkts_prev` ='0',`ifOutBroadcastPkts_rate` ='0',`ifOutBroadcastPkts_delta` ='0',`ifInMulticastPkts` ='0',`ifInMulticastPkts_prev` ='0',`ifInMulticastPkts_rate` ='0',`ifInMulticastPkts_delta` ='0',`ifOutMulticastPkts` ='0',`ifOutMulticastPkts_prev` ='0',`ifOutMulticastPkts_rate` ='0',`ifOutMulticastPkts_delta` ='0' WHERE `port_id` = '46189']
1 updated`

**Comment by laf** [comment]
As the LibreNMS user run 'rrdtool update /home/vhosts/netmon.mydomain.net/www/rrd/bcknd-sw-01.mydomain.net/port-id46189.rrd'

**Comment by Yamakasi** [comment]
I get ERROR: Not enough arguments on that command, do I miss something ?

**Comment by laf** [comment]
Sorry you need the rest of the command. Look in your output for it. Bunch of 0:U's

**Comment by Yamakasi** [comment]
OK, done, there is no output when I run that, just the commandline that comes back.

**Comment by laf** [comment]
This device isn't returning port information. Please provide the output of the following via pastebin:

`./poller.php -h HOSTNAME -r -f -v -m ports`

**Comment by Yamakasi** [comment]
I already added that information earlier in this report, so that will be
the same.

2016-12-27 22:39 GMT+01:00 Neil Lathwood <notifications@github.com>:

**Comment by laf** [comment]
I don't see that info unless you mean the snippet you posted - we need it all.

**Comment by Yamakasi** [comment]
OK, I will cat it in a file!

2016-12-27 23:36 GMT+01:00 Neil Lathwood <notifications@github.com>:

**Comment by Yamakasi** [comment]
Hereby the output as reqested

[output.txt](https://github.com/librenms/librenms/files/675050/output.txt)

**Comment by laf** [comment]
as i thought it's not returning the info needed.

in mysql pls run `select hardware from devices where device_id=52'`

**Comment by Yamakasi** [comment]
select hardware from devices where device_id=52
    -> ;
+------------------------+
| hardware               |
+------------------------+
| Dell PowerConnect 6024 |
+------------------------+
1 row in set (0.05 sec)


2016-12-28 9:23 GMT+01:00 Neil Lathwood <notifications@github.com>:

**Comment by laf** [comment]
Try adding this to config.php:

`$config['os']['powerconnect']['bad_ifXEntry'][] = 'Dell PowerConnect 6024';`

**Comment by Yamakasi** [comment]
OK will do, but it also happens on pfsense boxes, etc... so do I need to do
that for all devices ?

2016-12-28 22:49 GMT+01:00 Neil Lathwood <notifications@github.com>:

**Comment by laf** [comment]
You see this on all devices you have? If so have you restricted the snmp response as we don't see this anywhere else.

**Comment by Yamakasi** [comment]
I don't have restricted it as far as I know, it can also index the devices
to read is possible. I will check the pFsense boxes first to see what is
wrong there. It has worked this way before my upgrade to the latest
LibreNMS version.

2016-12-28 23:06 GMT+01:00 Neil Lathwood <notifications@github.com>:

**Comment by laf** [comment]
If you know when it stopped working, check logs/daily.log and it will tell you the version you went from and to, post this info.

**Comment by Yamakasi** [comment]
I have a backup from the old install, can I see the version somewhere ?
it's not in Changelog such files.

2016-12-28 23:13 GMT+01:00 Neil Lathwood <notifications@github.com>:

**Comment by laf** [comment]
From the backup do a git status.

**Comment by Yamakasi** [comment]
This won't work as it was a manual download extracted.

2016-12-29 0:05 GMT+01:00 Neil Lathwood <notifications@github.com>:

**Comment by Yamakasi** [comment]
OK, done extra tests and I can simply get data from ports using whatever simple SNMP test tool like Peassler or SNMPtrafficGrapher using the port OID

**Comment by Yamakasi** [comment]
Is there any information about what I can test more ? Simple SNMP just works, please update as  think more people will run into this, sooner or later.

**Comment by laf** [comment]
I'm not sure what else I can suggest, no one else is reporting this and I can't see other than your powerconnect any reason why all graphs stop.

**Comment by Yamakasi** [comment]
true, but all seem to do and as it worked before flawless and other SNMP
software does work I try to find something in the basics of libreNMS so I
can test with the SNMP package only to see if that works and report back.

2017-01-01 17:17 GMT+01:00 Neil Lathwood <notifications@github.com>:

**Comment by Yamakasi** [comment]
This $config['os']['powerconnect']['bad_ifXEntry'][] = 'Dell PowerConnect 6024';

doesn't let me receive any data as well. How can I make sure it does IfEntry instead of IfXEnty with that settings ? I can't find any docs on that array in the config.

**Comment by laf** [comment]
Update your install and try again

**Comment by Yamakasi** [comment]
What has been changed then ? I still have this testinstall available so I
can test out if needed.

2017-01-28 1:44 GMT+01:00 Neil Lathwood <notifications@github.com>:

**Comment by laf** [comment]
Lots of things so it's worth an update

**Comment by Yamakasi** [comment]
OK good to hear! I will give it a try. Thanks!

2017-01-28 11:16 GMT+01:00 Neil Lathwood <notifications@github.com>:

**Comment by laf** [comment]
no further info provided

**Comment by Yamakasi** [comment]
Hi,

Tested it out, same issue. Thanks so far!

2017-02-13 1:08 GMT+01:00 Neil Lathwood <notifications@github.com>:
