### ISSUE TITLE
Dell OMSA - Graphing of Power Consumtion in Watt's

### ISSUE THREAD

**Issue by SanderM2** [librenms/librenms#5242]
I have dell servers with OMSA installed.
I added the smuxpeer in snmpd.conf and librenms is now graphing fan speeds etc.. like expected.

But it's not using  'iso.3.6.1.4.1.674.10892.1.600.30.1.6.1.3'. This is the servers power consumption in Watt.

On IRC (#librenms) I was told I should open an issue for this..

Besides this, I would also like to graph PSU1 power and PSU2 power in volts. Those are privated with
iso.3.6.1.4.1.674.10892.1.600.20.1.6.1.21 and  iso.3.6.1.4.1.674.10892.1.600.20.1.6.1.22

And maybe also the PSU status so I can create alerts if one of the PSU's status has changed? 

Can this be included in an update?

Kind regards,
Sander

**Comment by laf** [comment]
Please provide the info asked for here: http://docs.librenms.org/Support/FAQ/#what-information-do-you-need-to-add-a-new-os

**Comment by SanderM2** [comment]
Output of: ./discovery.php  -h 10.10.1.100 -d -m os
=>  http://pastebin.com/Sk42842v

Output of: ./poller.php -h 10.1.1.100 -r -f -d -m os
=> http://pastebin.com/GE6uz0z6

The output of "snmpbulkwalk -OUneb -v2c -c <snip> 10.10.1.100 ." was too big for pastebin.com. It told me I need to get the pastebin PRO account for that which I didn't do.

So instead I'm sending you the output of : snmpbulkwalk -OUneb -v2c -c <snip> 10.10.1.100 .1.3.6.1.4.1.674.10892.1.600 which should contain all relevant things, right?

=> http://pastebin.com/8YfqzDhH

**Comment by laf** [comment]
Not really, we use the snmpwalk output to simulate the device. Just use any other paste bin style service.

**Comment by SanderM2** [comment]
I tried multiple paste services and all of them fail to work with such a big text. So I asked a friend to put it online on a domain and here's the link : http://www.akke.net/log3431.txt

**Comment by laf** [comment]
From what I can see, this info isn't available. It racks power usage since time rather than power usage now so we'd need to then start tracking the previous value and the times which imho isn't worth doing.

**Comment by SanderM2** [comment]
iso.3.6.1.4.1.674.10892.1.600.30.1.6.1.3 seems to be the current usage in watt, not in time. It's always the same value as I can see in my iDRAC power monitoring page.. In Watts.

iso.3.6.1.4.1.674.10892.1.600.20.1.6.1.21 and iso.3.6.1.4.1.674.10892.1.600.20.1.6.1.22 are PSU1 and PSU2 current voltages in Volt.
