### ISSUE TITLE
Enhancement: Display IPv6 Address in the "Resolved IP" field

### ISSUE THREAD

**Issue by mrjester888** [librenms/librenms#5244]
The device overview page should list the IPv4 and IPv6 addresses of the device.  All of my devices are dual stacked and only the v4 address is presented.

**Comment by Rosiak** [comment]
Hi,

We are cleaning up the issues here on GitHub, all feature requests will be moved to:
https://community.librenms.org/c/feature-requests

Hence the closure of this issue.
