### ISSUE TITLE
Enchancement: Update Synology MIB files

### ISSUE THREAD

**Issue by E-t-z** [librenms/librenms#5245]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

Please update Synology MIB files to latest ones:
http://dedl.synology.com/download/Document/MIBGuide/Synology_MIB_File.zip

**Comment by laf** [comment]
The two mibs we use are already up to date.

No point in including the others as we make no use of them.
