### ISSUE TITLE
Cisco WLC wrong device class

### ISSUE THREAD

**Issue by realnakrul** [librenms/librenms#5250]
Hi
Cisco virtual Wireless Controller appears under 
Devices -> All Devices -> Network 
instead of 
Devices -> All Devices -> Wireless

./discovery.php -h 192.168.1.1 -d -m os         
LibreNMS Discovery
Version info:
Commit SHA: 3b198243d57fe1786fae68548ca258d612966145
DB Schema: 152
PHP: 7.0.8-0ubuntu0.16.04.3
MySQL: 5.7.16-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP 5.7.3
DEBUG!
SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
SQL[SELECT revision FROM `dbSchema`] 
DB Schema already up to date.
SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE '192.168.1.1' ORDER BY device_id DESC] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '18'] 
192.168.1.1 18 ciscowlc 
Modules status: Global+ OS  Device  
#### Load disco module os ####
SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0]
Cisco Controller

SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Ovqn -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysObjectID.0]
.*.*.1631

| Cisco Controller | .1.3.6.1.4.1.9.1.1631 | 
SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Oqvn -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalDescr.1]
Cisco Wireless Controller

>> Runtime for discovery module 'os': 0.1820 seconds
#### Unload disco module os ####

SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '18' AND `attrib_type` = 'poll_mib' ] 
SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='network',`last_discovered_timetaken` ='0.188' WHERE `device_id` = '18'] 
Discovered in 0.188 seconds

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','192.168.1.1','1482826843.0803','0.317','1')] 
./discovery.php 192.168.1.1 2016-12-27 12:20:43 - 1 devices discovered in 0.317 secs
SNMP: Get[3/0.04s] Walk [0/0.00s]
MySQL: Cell[4/0.00s] Row[0/0.00s] Rows[4/0.00s] Column[0/0.00s] Update[1/0.04s] Insert[1/0.02s] Delete[0/0.00s]

**Comment by laf** [comment]
I'd this should be voted on. A WLC = Wireless lan controller so isn't actually a wireless device per se (or is it?) however it does make more sense to me being a wireless type.

If you drum up enough support to change this then we can go ahead.

@librenms/reviewers ?

**Comment by realnakrul** [comment]
Hi, thank you for reply. But in this case we have inconsistent approach. Aruba 7005 wireless controller appears under Wireless by default... Device is absolutely the same as Cisco WLC, just from different vendor.

**Comment by realnakrul** [comment]
Hi and Happy New Year! By the way LibreNMS has firewall category - firewalls are pure Network devices as well. Following this logic - most of the devices are network. As for me only Routers and Switches should be under network. It is unclear with SOHO wireless routers, but enterprise Wireless controller should be under Wireless. IMHO.

**Comment by murrant** [comment]
Seems like sound logic to me :+1:

**Comment by laf** [comment]
I'm not fussed either way but my opinion is that wireless controllers are network devices so should be changed to that.

However you're more than welcome to submit a pull request to change the default so long as you submit one to update the notifications.rss: https://github.com/librenms/librenms.github.io/blob/master/notifications.rss

**Comment by laf** [comment]
If there is no further discussion to be had here then I'll be closing this shortly.

**Comment by realnakrul** [comment]
Hi Laf
Anyway something should be changed.
Cisco WLC -> to wireless (Preferable IMHO)
or
Aruba WLC -> to network

**Comment by laf** [comment]
I've put my opinion above, that's all it is. If others want to change things then your free to submit a pull request. I won't be though as I don't think a WLC should be a wireless device.

**Comment by murrant** [comment]
On second thought, I do agree with laf.  Wireless should have radios, network has an ports.  We can change the Aruba.

**Comment by realnakrul** [comment]
Hi. Wireless controllers has radios - lightweight wireless access points. And by the way you can't SNMP poll lightweight AP, only controller. Think from the enterprise point of view. Otherwise Wireless category will have only small consumer devices.

**Comment by murrant** [comment]
FYI, Cisco's lightweight APs are a small part of the market.

**Comment by realnakrul** [comment]
Hi, it doesn't matter Cisco, Aruba, Ruckus or even Ubiquity. Approach is the same everywhere.

**Comment by murrant** [comment]
We have support for polling all those APs directly.  But, we are getting off topic here.

**Comment by laf** [comment]
If you would like to discuss this further then I suggest creating a conversation on community.librenms.org
