### ISSUE TITLE
Enhancement: Slack alert formatting

### ISSUE THREAD

**Issue by nrcbhermsen** [librenms/librenms#5251]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

Enable Slack markdown codes for alerts by passing the parameter to enable markdown in the text field.
Enable short links via Slack formatting without it getting stripped out since it looks like a tag which would normally get stripped out of the text.

**Comment by Rosiak** [comment]
From what I know markdown is enabled by default, when parsing messages from a bot?

**Comment by Rosiak** [comment]
No response, closing.
