### ISSUE TITLE
Wireless Access Point -> Wireless Type?

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#5254]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ X] Please include all of the information between the `====================================` section of `./validate.php`.
- [ X] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ X] Please provide as much detail as possible.

Hi,

I know I can manually change this (1-by-1), but thinking there should be a better way (and there likely is). For WAP's running, for example, OpenWRT, DD-WRT, ASUSWRT-Merlin, Tomato, etc. ... because they run Linux they show up as a device type of "server" (based on Operating System) - but perhaps based on Platform they could / should be categorized as a device type of "Wireless"?

Thoughts?

I'm fine changing this in the code to help out, just can't figure out what / where to change it ... :(.

Thanks!

**Comment by laf** [comment]
If we have a way to detect these devices then we should - we'd need the output of the info asked for in point 3 above.

**Comment by arrmo** [comment]
Sure, NP! Files attached - for the three commands (discovery, poller and snmpbulkwalk), for both ASUSWRT-Merlin and Tomato. I don't have DD-WRT (that router died), and OpenWRT (not using it) - but start with these two at least? And - perhaps use the output of distro?

Thanks!





[discovery.ASUSWRT-Merlin.txt](https://github.com/librenms/librenms/files/674980/discovery.ASUSWRT-Merlin.txt)
[discovery.Tomato.txt](https://github.com/librenms/librenms/files/674981/discovery.Tomato.txt)
[poller.ASUSWRT-Merlin.txt](https://github.com/librenms/librenms/files/674982/poller.ASUSWRT-Merlin.txt)
[poller.Tomato.txt](https://github.com/librenms/librenms/files/674985/poller.Tomato.txt)
[snmpbulkwalk.ASUSWRT-Merlin.txt](https://github.com/librenms/librenms/files/674983/snmpbulkwalk.ASUSWRT-Merlin.txt)
[snmpbulkwalk.Tomato.txt](https://github.com/librenms/librenms/files/674984/snmpbulkwalk.Tomato.txt)

**Comment by E-t-z** [comment]
Well, running those OS'es does not immediately mean, they are always running as AP's and in case of OpenWRT, it does not even mean it always has Wireless.

Anyway, I can do some OpenWRT dumps if necessary on 2 different devices.
(One is Turris Omnia and other is Inteno).

**Comment by E-t-z** [comment]
OpenWRT (Inteno)

http://etz.planet.ee/Inteno-OpenWRT-poller.txt
http://etz.planet.ee/Inteno-OpenWRT-discovery.txt
http://etz.planet.ee/Inteno-OpenWRT-bulkwalk.txt

Will do, Turris Omnia run later as I first have to re-add it to LibreNMS.

**Comment by arrmo** [comment]
Hi,

No issues here using Network rather than Wireless - agree with your point above. Right now they show up as Server, not sure that's the right selection ... ;).

Thanks!

**Comment by E-t-z** [comment]
As promised earlier, from OpenWRT on Turris Omnia:

http://etz.planet.ee/Turris-OpenWRT-poller.txt
http://etz.planet.ee/Turris-OpenWRT-discovery.txt
http://etz.planet.ee/Turris-OpenWRT-bulkwalk.txt

**Comment by E-t-z** [comment]
About DD-WRT I only found this: https://www.dd-wrt.com/wiki/index.php/SNMP#Known_OID.C2.B4s_via_SNMP

As I have 0 devices with it, cannot unfortunately help with anything else...

**Comment by laf** [comment]
I actually think a lot of these are taken care of if you install the distro script from the librenms-agent repo. However I've added detection for Tomato and AsusWRT-Merlin as we can detect those natively. The others don't appear to offer anyway to do so via snmp.

**Comment by arrmo** [comment]
Thanks! Will give it a try once this is merged - much appreciated.

FYI, I do have the distro script installed (Tomato at least).
