### ISSUE TITLE
WebUI Bug? Disabled ports not showing.

### ISSUE THREAD

**Issue by E-t-z** [librenms/librenms#5256]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.

Component | Version                                                                                                                        
--------- | -------                                                                                                                        
LibreNMS  |                                                                                                                                
DB Schema | 151                                                                                                                            
PHP       | 7.0.14-2+deb.sury.org~xenial+1                                                                                                 
MySQL     | 5.5.52-MariaDB                                                                                                                 
RRDTool   | 1.5.5                                                                                                                          
SNMP      | NET-SNMP 5.7.3    
                                            

- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

On Device summary widget, there are 20 ports (In my case) shown that are Disabled.
When "Disabled" ports are clicked on widget or chosen from dropdown menu, it brings up empty list without any of those ports listed.

Url on adressbar says: http://librenmsaddr/ports/state=admindown/ 
when actually all disabled ports are listed under url 
http://librenmsaddr/ports/state=down/

As an sidenote I have 0 "admin down" ports, so technically I have no Disabled ports at all... 
They are simply down eq. unplugged...virtually or physically.

Is it bug or feature?
It definately looks a bit inconsistent...

**Comment by InsaneSplash** [comment]
I am seeing the same issue presented within my installation. The Device-summary-horiz dashboard widget reports 6 disabled ports. When I select all ports, and filter down to disabled, none are presented in the search results.
