### ISSUE TITLE
Add Support for ArrayNetworks APV 2600 Loadbalance

### ISSUE THREAD

**Issue by wwtc1208** [librenms/librenms#5257]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.
[ArrayNetworks APV Loadbalance.txt](https://github.com/librenms/librenms/files/676672/ArrayNetworks.APV.Loadbalance.txt)

Hi,
I want to know if you can integrate this loadbalance device. 
The Librenms identifies the wrong device.It is recognized as Xirrus ArrayOS  and the port description is different from the actual port description, which is identified by a private MIB Library.

Here are :

Discovery : http://pastebin.com/x1tV9sLw
Poller : http://pastebin.com/q1nECrRr
Snmpwalk : http://pastebin.com/CpDvYriK

In attachment the one file for MIBS
https://github.com/librenms/librenms/files/676672/ArrayNetworks.APV.Loadbalance.txt

**Comment by laf** [comment]
The snmpwalk doesn't have the info from the mib provided, can you re-run the walk but use ` .1.3.6.1.4.1.7564` at the end pls.

**Comment by laf** [comment]
No further info provided. Base detection already added.
