### ISSUE TITLE
Add support for Dell UPS Rack 3750W High Efficiency Online HV

### ISSUE THREAD

**Issue by naokij** [librenms/librenms#5258]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php`.
```
Component | Version
--------- | -------
LibreNMS  | 2fa4a0b7925eed47b17ce8ef06ef2e1667ff1dc5
DB Schema | 153
PHP       | 7.0.9
MySQL     | 5.5.47-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
```
- [x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)

 *  [Discovery](http://pastebin.com/qY8kc8Ek)
 *  [Poller](http://pastebin.com/9thpdDth)
 *  [SNMP](http://pastebin.com/8zEmMr5k)

- [X] Please provide as much detail as possible.
  * [MIB](https://trello-attachments.s3.amazonaws.com/4fdfef3c1dfb47d35b263d5e/585f8449cf95f77c6e5a874e/f472bcc822606bdbf8472a54a7853a38/MibUpsDell.mib)

Let me know if you need more information.

**Comment by naokij** [comment]
Thank you for the commit. I have tried this commit but no power graph generated. 

Here device access information you may want to debug this:

~~~
ups11.emagineconcept.com
snmp v1 community string: Ahjos9ee
~~~

**Comment by laf** [comment]
You

**Comment by laf** [comment]
You didn't ask for power graphs. This was just to add detection

**Comment by laf** [comment]
PR merged
