### ISSUE TITLE
Allow to see information about lapsed maintenance windows

### ISSUE THREAD

**Issue by clay584** [librenms/librenms#5259]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

================================================================

Feature Request:

When looking at lapsed maintenance windows, would it be possible to add functionality to click on it and see the details that are present when you edit a current maintenance window?  It would be nice to be able to click on a lapsed maintenance window and see what devices or device groups, and notes that pertained to that maintenance window.

**Comment by Rosiak** [comment]
Hi,

We are cleaning up the issues here on GitHub, all feature requests will be moved to:
https://community.librenms.org/c/feature-requests

Hence the closure of this issue.
