### ISSUE TITLE
Add Support for Fujitsu DX Storages (MIB included)

### ISSUE THREAD

**Issue by air101** [librenms/librenms#5260]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php`.
Component | Version
--------- | -------
LibreNMS  | 1935c3a84f2b9e4820a86e851bfccf165c6c51b7
DB Schema | 153
PHP       | 5.6.17-0+deb8u1
MySQL     | 5.5.47-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

- [X] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [X] Please provide as much detail as possible.

Discovery, Poller, Walk and MIB File included. I already tried adding it to mibs dir but then my rrd dir went up to 20gig, lol. Thanks already!

[fuj-dx60-s3-discovery.txt](https://github.com/librenms/librenms/files/677122/fuj-dx60-s3-discovery.txt)
[fuj-dx60-s3-poller.txt](https://github.com/librenms/librenms/files/677123/fuj-dx60-s3-poller.txt)
[fuj-dx60-s3-walk.txt](https://github.com/librenms/librenms/files/677124/fuj-dx60-s3-walk.txt)
[FJDARY-E150.zip](https://github.com/librenms/librenms/files/677125/FJDARY-E150.zip)

**Comment by air101** [comment]
Thank you for adding Support for the Device but something is not right. The polling of the device somehow uses all space in rrd folder creating these files/folders:

fjdarye150-SluIndex-855.rrd
fjdarye150-SluIndex-856.rrd
fjdarye150-SluIndex-857.rrd
fjdarye150-SluIndex-858.rrd
fjdarye150-SluIndex-859.rrd
fjdarye150-SluIndex-85.rrd
fjdarye150-SluIndex-860.rrd
fjdarye150-SluIndex-861.rrd
fjdarye150-SluIndex-862.rrd
fjdarye150-SluIndex-863.rrd
fjdarye150-SluIndex-864.rrd
fjdarye150-SluIndex-865.rrd
fjdarye150-SluIndex-866.rrd
fjdarye150-SluIndex-867.rrd
fjdarye150-SluIndex-868.rrd
fjdarye150-SluIndex-869.rrd

etc....

I've disabled the device for now.

**Comment by laf** [comment]
We'd need to see the output of `./poller.php -h hostname -d -r -f` It's not obvious what those are, if they are ports then this is because the device is showing us that many ports. You have options to limit this but without more info we can't help - create a new issue with the info.

**Comment by air101** [comment]
[rz.zip](https://github.com/librenms/librenms/files/693079/rz.zip)
Log attached,
118 MB Log with 1 Poller ;)

**Comment by air101** [comment]
@laf 
Did you have time to look at the problem yet?

Thanks

**Comment by laf** [comment]
Have you enabled mib based polling for this device? It looks like all that information is coming from that. I'd suggest you disable mib polling for it.

**Comment by laf** [comment]
no further information provided
