### ISSUE TITLE
[API] Problem with force_add and addHost function + fix

### ISSUE THREAD

**Issue by PandaWawawa** [librenms/librenms#5261]
Hi everyone,

I just faced a problem using the force_add parameters in the add_device function in api_functions.inc.php

This functions uses the addHost function in includes/functions.php where it checks the $force_add parameter to be '=== true'
Or the add_device function get the force_add post parameter and apply a 'mres()' on it, which transforms it into '1' (which is not '=== true') 

I changed on my side the add_device function
`$force_add    = $data['force_add'] ? mres($data['force_add']) : 0;`
to
`$force_add    = $data['force_add'] ? true : false;`
to get this working

Maybe we can push this change ?

++

**Comment by laf** [comment]
Yeah submit a fix :)

**Comment by dvergur** [comment]
Nice, this is exactly what i needed. Works like a charm.
