### ISSUE TITLE
AlertLog /alert-log page not loading in chrome

### ISSUE THREAD

**Issue by mmarchand** [librenms/librenms#5264]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

In Chrome 57 (and probably before since it has happened for quite a long time now)
Javascript console shows a :  
"Uncaught RangeError: Maximum call stack size exceeded"

**Comment by laf** [comment]
Isn't Chrome 57 a dev release? I'm not sure we should be reacting to issues in a dev piece of software.

**Comment by mmarchand** [comment]
same thing in 55 (just tested here ;)

**Comment by laf** [comment]
I've tested 55 and don't see an issue. What commit # are you on for LibreNMS?

Does the same happen on https://demo.librenms.org/alert-log/ as that also works.

**Comment by mmarchand** [comment]
I am using latest master
it works on the demo site,

I suspect it could be related to the number of devices (I have 4k+) 
I guess Chrome does not want to create a 4k list on the selection list (it does not show here, see screenshot)

https://gyazo.com/7ff062e5647bd6cb5147eb672e0074f1

**Comment by mmarchand** [comment]
Just tested to comment out the 
```
foreach (get_all_devices() as $hostname) {
```
in pages/alert-log.inc.php

and the page loads fine (without the list box of course)

**Comment by mmarchand** [comment]
strange thing, the listbox works in the eventlog page ... so I don't know what's wrong here

**Comment by laf** [comment]
I guess we could change this to be ajax powered input field instead.

**Comment by f0o** [comment]
@mmarchand Do you see anything in chrome's error-console?

**Comment by mmarchand** [comment]
Yes : 
Uncaught RangeError: Maximum call stack size exceeded  (index:1)

**Comment by laf** [comment]
Needs converting to an ajax fed field.
