### ISSUE TITLE
memcached app graphs not populating

### ISSUE THREAD

**Issue by clay584** [librenms/librenms#5265]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

===============================================================

===============================================================

===============================================================

===============================================================

===============================================================

I am unable to get memcached graphs to populate for localhost device (LibreNMS server).  I can snmpwalk it and it returns data as expected.  The memcache application is enabled for localhost, but all the graphs show nan for all values.  Libre logs are clean.  No errors in any of the log files. FWIW, the apache-stats snmp extension works fine.

    [root@overwatch ccurtis]# cat /etc/snmp/snmpd.conf
    com2sec local     localhost        xxxxxxxx
    group MyROGroup  v2c        local
    view all    included  .1                               80
    access MyROGroup ""      any       noauth    prefix      all    none    none
    syslocation xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    syscontact xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    dontLogTCPWrappersConnects yes
    disk / 100000
    load 12 14 14
    extend apache /etc/snmp/apache-stats.py
    extend memcached /etc/snmp/memcached
    [root@overwatch ccurtis]#
    [root@overwatch ccurtis]#
    [root@overwatch ccurtis]# cat /etc/snmp/memcached
    #!/usr/bin/php
    <?php
    $m = new Memcached();
    $m->addServer('localhost', 11211);
    $stats = $m->getStats();

    if(is_array($stats))
    {
      echo("<<<app-memcached>>>\n");
      echo(serialize($m->getStats()));
      echo("\n");
    }
    ?>
    [root@overwatch ccurtis]#
    [root@overwatch ccurtis]#
    [root@overwatch ccurtis]# ls -ls /etc/snmp/memcached
    4 -rwxr-xr-x. 1 root root 214 Dec 29 11:39 /etc/snmp/memcached
    [root@overwatch ccurtis]#
    [root@overwatch ccurtis]#
    [root@overwatch ccurtis]# snmptranslate -On NET-SNMP-EXTEND-MIB::nsExtendOutput1Line.\"memcached\"
    .1.3.6.1.4.1.8072.1.3.2.3.1.1.9.109.101.109.99.97.99.104.101.100
    [root@overwatch ccurtis]#
    [root@overwatch ccurtis]#
    [root@overwatch ccurtis]# snmpwalk -v2c -c xxxxxxxx  localhost .1.3.6.1.4.1.8072.1.3.2.3.1.2.9.109.101.109.99.97.99.104.101.100
    NET-SNMP-EXTEND-MIB::nsExtendOutputFull."memcached" = STRING: <<<app-memcached>>>
    a:1:{s:15:\"localhost:11211\";a:24:{s:3:\"pid\";i:7396;s:6:\"uptime\";i:65467;s:7:\"threads\";i:4;s:4:\"time\";i:1483031649;s:12:\"pointer_size\";i:64;s:19:\"rusage_user_seconds\";i:19;s:24:\"rusage_user_microseconds\";i:509000;s:21:\"rusage_system_seconds\";i:36;s:26:\"rusage_system_microseconds\";i:237000;s:10:\"curr_items\";i:9357;s:11:\"total_items\";i:466771;s:14:\"limit_maxbytes\";i:536870912;s:16:\"curr_connections\";i:10;s:17:\"total_connections\";i:118534;s:21:\"connection_structures\";i:35;s:5:\"bytes\";i:4896640;s:7:\"cmd_get\";i:1676932;s:7:\"cmd_set\";i:466771;s:8:\"get_hits\";i:726066;s:10:\"get_misses\";i:950866;s:9:\"evictions\";i:0;s:10:\"bytes_read\";i:736440980;s:13:\"bytes_written\";i:973764544;s:7:\"version\";s:6:\"1.4.15\";}}
    [root@overwatch ccurtis]#
    [root@overwatch ccurtis]#
    [root@overwatch ccurtis]# php /opt/librenms/validate.php 
    ==========================================================
    Component | Version
    --------- | -------
    LibreNMS  | 2fa4a0b7925eed47b17ce8ef06ef2e1667ff1dc5
    DB Schema | 153
    PHP       | 5.4.16
    MySQL     | 5.5.52-MariaDB
    RRDTool   | 1.4.8
    SNMP      | NET-SNMP 5.7.2
    ==========================================================
    [root@overwatch ccurtis]# /etc/snmp/memcached 
    <<<app-memcached>>>
    a:1:{s:15:"localhost:11211";a:24 {s:3:"pid";i:7396;s:6:"uptime";i:151647;s:7:"threads";i:4;s:4:"time";i:1483117829;s:12:"pointer_size";i:64;s:19:"rusage_user_seconds";i:40;s:24:"rusage_user_microseconds";i:208000;s:21:"rusage_system_seconds";i:73;s:26:"rusage_system_microseconds";i:938000;s:10:"curr_items";i:10107;s:11:"total_items";i:1010571;s:14:"limit_maxbytes";i:536870912;s:16:"curr_connections";i:12;s:17:"total_connections";i:222970;s:21:"connection_structures";i:38;s:5:"bytes";i:5243456;s:7:"cmd_get";i:3355799;s:7:"cmd_set";i:1010571;s:8:"get_hits";i:1405964;s:10:"get_misses";i:1949835;s:9:"evictions";i:0;s:10:"bytes_read";i:1640862986;s:13:"bytes_written";i:1980656777;s:7:"version";s:6:"1.4.15";}}
    [WARN]  Your install is out of date, last update: Wed, 28 Dec 2016 23:07:30 +0000
    [OK]    Database connection successful

**Comment by laf** [comment]
I can't test this as php7 doesn't have memcache support from webtatic.

Can you provide the info from: `./poller.php -h HOSTNAME -d -r -f -m applications` please via pastebin

**Comment by clay584** [comment]
Here you go...

http://pastebin.com/m3q5Yffe

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/memcached-app-graphs-not-populating/13518/1
