### ISSUE TITLE
Get wrong ifDescr and wrong infOperStatus

### ISSUE THREAD

**Issue by wwtc1208** [librenms/librenms#5268]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

Hi,

When I add the device, I get the wrong ifDescr and wrong infOperStatus. Can I get it from private MIB. What I need to do next. Please help me, thanks!
Attached is my screenshot contrast file.

![ifdescr01](https://cloud.githubusercontent.com/assets/24206820/21558729/bab80e6c-ce79-11e6-99e6-b8e6cf3f26a2.png)
![ifdescr02](https://cloud.githubusercontent.com/assets/24206820/21558731/c33d4840-ce79-11e6-8fab-e42cadeeeecf.png)
![infoperstatus01](https://cloud.githubusercontent.com/assets/24206820/21558739/e3e481ee-ce79-11e6-9cb0-a889e9bdc924.png)
![infoperstatus02](https://cloud.githubusercontent.com/assets/24206820/21558744/f285a0ac-ce79-11e6-8d2c-5b9c422bdb34.png)

**Comment by laf** [comment]
Yes we have the ability to use different mibs for ports.

We'd need the output asked for above under adding new device, we would also need the mib if we didn't have it.

**Comment by wwtc1208** [comment]
Hi, 
I have submitted a request to add a new device, and the mib is included in it.
The link is [https://github.com/librenms/librenms/issues/5257](url)
