### ISSUE TITLE
URL encoding with OS version

### ISSUE THREAD

**Issue by tsumaru720** [librenms/librenms#5269]
I've a couple of APC UPSs that expose their OS version as "AOS v3.7.3 / App v3.7.2"

When on the "all devices" list, if you select this from the "Version" drop down and then either try to change the graphs displayed or "Update URL" you get an Apache error which I suspect is because of the existence of "/" in the string.

URL attempted to be generated:

https://librenms.example.com/devices/version=AOS+v3.7.3+%2F+App+v3.7.2/format=list_detail/

Error

<code>
Not Found

The requested URL /devices/version=AOS+v3.7.3+/+App+v3.7.2/format=list_detail/ was not found on this server.
</code>

Everything else seems to work fine

<pre>
==========================================================
Component | Version
--------- | -------
LibreNMS  | c257332ef88f3456291c229a43085bb04fd5f150
DB Schema | 152
PHP       | 5.5.9-1ubuntu4.20
MySQL     | 5.5.53-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2
==========================================================

</pre>

**Comment by laf** [comment]
Odd, I've just tested this and don't have that issue.

What version of Apache and can you post your apache config file pls.

**Comment by tsumaru720** [comment]
@laf 
```
# apachectl -v
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Jul 15 2016 15:34:04
```

```
<VirtualHost *:80>

        ServerName libre.example.com

        RewriteEngine On
        RewriteCond %{HTTPS} off
        RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301]

</VirtualHost>

<VirtualHost *:443>

        ServerName libre.example.com

        SSLEngine on
        SSLCertificateFile **certificate**
        SSLCertificateKeyFile **key**
        SSLCertificateChainFile **intermediate**

        KeepAlive On
        KeepAliveTimeout 5

        DocumentRoot /opt/librenms/html

        <Directory />
                Options FollowSymLinks
                AllowOverride None
        </Directory>
        <Directory /opt/librenms/html/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Require all granted
        </Directory>

        ErrorLog  ${APACHE_LOG_DIR}/libre-error.log
        LogLevel warn
        CustomLog  ${APACHE_LOG_DIR}/libre-access.log combined
        ServerSignature On

</VirtualHost>
```

**Comment by tsumaru720** [comment]
```
root@server:/opt/librenms/html# cat .htaccess 
#  DO NOT CHANGE THIS FILE
#  If you need to change this file, you are doing something wrong.

Options FollowSymlinks Multiviews

RewriteEngine on
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !\.(js|ico|txt|gif|jpg|png|css|php)
RewriteRule ^api/v0(.*)$ api_v0.php/$1 [L]
RewriteCond %{REQUEST_URI} !=/server-status
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !\.(js|ico|txt|gif|jpg|png|css|php)
RewriteRule ^(.*)$ index.php/$1/

AcceptPathInfo On

```

**Comment by tsumaru720** [comment]
Affected URL:

https://libre.example.com/devices/version=AOS+v3.7.3+%2F+App+v3.7.2/format=list_detail/

If i replace the %2F with say an X

https://libre.example.com/devices/version=AOS+v3.7.3+x+App+v3.7.2/format=list_detail/

it loads fine (albeit I get no results, obviously)

**Comment by tsumaru720** [comment]
So turns out I didnt fully read the docs - I was missing the following in my Apache vhost:

`  AllowEncodedSlashes NoDecode`

Thanks for your patience with this @laf
