### ISSUE TITLE
Unifi AP's not showing wireless data

### ISSUE THREAD

**Issue by TyShawn76** [librenms/librenms#5271]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

New Box
==========================================================
Component | Version
--------- | -------
LibreNMS  | 11345e1c73f0ec3bde2fd62b85228cd4fdd4ac5f
DB Schema | 153
PHP       | 5.6.29-0+deb8u1
MySQL     | 10.0.28-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

Old Box
==========================================================
Component | Version
--------- | -------
LibreNMS  | 11345e1c73f0ec3bde2fd62b85228cd4fdd4ac5f
DB Schema | 153
PHP       | 5.6.29-0+deb8u1
MySQL     | 5.5.53-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

I have multiple Gen 1 and Gen 2 Unifi Aps over multiple locations. When I opened a ticket to have the new OID's added to the APS everything was working perfectly APs I noticed the network section never added for the APs. I didn't pay it much mind as I thought I was doing something wrong. A couple of weeks ago I loaded up a new test box and found the same issue, none of the APs would show the network section that housed the information I was looking for. 

Later I loaded a fresh longterm box that I had to run to a site and found the same issue again. None of the APS Gen 1 or Gen 2 will show the network section. Yet I can still poll the test AP without fail. 

I am including two pictures one with the working section and one without.
![screen shot 2016-12-31 at 10 30 28 am](https://cloud.githubusercontent.com/assets/21324034/21578179/ca605704-cf44-11e6-9629-625873731033.jpg)
![screen shot 2016-12-31 at 10 29 58 am](https://cloud.githubusercontent.com/assets/21324034/21578180/ca645fb6-cf44-11e6-8217-a4be4f5736aa.jpg)

**Comment by TyShawn76** [comment]
http://pastebin.com/sLBYq189

**Comment by basn** [comment]
I see this issue on one of my AP's but the other works fine.
The one that works is a AC-Pro (UAP-AC-Pro-Gen2) and the one that does not work is a 
UAP-LR (so gen1)

**Comment by TyShawn76** [comment]
Just to add a bit more detail. The working unit is a Gen 2 AC Pro. The Broken units are a Gen 2 AC lite, Gen 2 AC LR, Gen 1 UAP Pro. My "guess" is the script is only picking up the Gen 2 AC Pro models.

**Comment by murrant** [comment]
Check your database. One has `type` set and the other does not I'd wager.

**Comment by TyShawn76** [comment]
So if I understand what you're saying is the units are not being identified correctly? And the single units that does work correctly was the verify first units when this code was beta. All other units I am looking to add which came after general release doesn't find the right information over multiple boxes is a database or a discovery issue? 

I believe there is a manual workaround as you linked me to, but this many APs and the fact I can reproduce this issue on old and fresh installs has me asking why does the user have to do a two step process.

Can you help me understand my thought process...? I could be looking at this wrong.

**Comment by laf** [comment]
Just update your install, this is now fixed.

**Comment by TyShawn76** [comment]
Ok thanks laf... Have a great day and thank you for all the hard work.

**Comment by TyShawn76** [comment]
http://pastebin.com/T9ba97ui

**Comment by TyShawn76** [comment]
http://pastebin.com/ZcabrU70

**Comment by laf** [comment]
Feel free to provide the output of `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .`

**Comment by TyShawn76** [comment]
Working AP
http://pastebin.com/FYmT8TNp

Broken AP
http://pastebin.com/f675HdVx

Broken AP second location
http://pastebin.com/0tRJK4A5

**Comment by murrant** [comment]
Top and bottom should work.  The middle will not work.  I think #5390 will fix your last one.

**Comment by laf** [comment]
Yeah I didn't check the bottom one but the issue with the middle one _I think_ is #5390

**Comment by TyShawn76** [comment]
I know the post is closed, but I wanted to report this last change did fix my issue for the Gen 1 and Gen 2 devices. 

Thank You

**Comment by murrant** [comment]
Thanks @TyShawn76 lots of little issues contributing.
