### ISSUE TITLE
Mikrotik SWos

### ISSUE THREAD

**Issue by keefe007** [librenms/librenms#5272]
I noticed that Libre detects Mikrotik RouterOS devices properly but not Mikrotik SwOS devices.

For example, the RB260GSP.

**Comment by laf** [comment]
When you create an issue it has a template asking you for information to fill in, please do that.

**Comment by keefe007** [comment]
Here's an snmpwalk of a Mikrotik SWOS device:


.1.3.6.1.2.1.1.1.0 = STRING: "RB260GSP"
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.14988.2
.1.3.6.1.2.1.1.3.0 = Timeticks: (1101248631) 127 days, 11:01:26.31
.1.3.6.1.2.1.1.4.0 = STRING: "noc@domain.com"
.1.3.6.1.2.1.1.5.0 = STRING: "ABC Cutsomer MTIK Swi"
.1.3.6.1.2.1.1.6.0 = STRING: "Public"
.1.3.6.1.2.1.1.7.0 = INTEGER: 2
.1.3.6.1.2.1.2.1.0 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.1.2 = INTEGER: 2
.1.3.6.1.2.1.2.2.1.1.3 = INTEGER: 3
.1.3.6.1.2.1.2.2.1.1.4 = INTEGER: 4
.1.3.6.1.2.1.2.2.1.1.5 = INTEGER: 5
.1.3.6.1.2.1.2.2.1.1.6 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.2.1 = STRING: "Port1"
.1.3.6.1.2.1.2.2.1.2.2 = STRING: "Port2"
.1.3.6.1.2.1.2.2.1.2.3 = STRING: "Port3"
.1.3.6.1.2.1.2.2.1.2.4 = STRING: "Port4"
.1.3.6.1.2.1.2.2.1.2.5 = STRING: "Port5"
.1.3.6.1.2.1.2.2.1.2.6 = STRING: "SFP"
.1.3.6.1.2.1.2.2.1.3.1 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.3.2 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.3.3 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.3.4 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.3.5 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.3.6 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.4.1 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.4.2 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.4.3 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.4.4 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.4.5 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.4.6 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.5.1 = Gauge32: 1000000000
.1.3.6.1.2.1.2.2.1.5.2 = Gauge32: 100000000
.1.3.6.1.2.1.2.2.1.5.3 = Gauge32: 1000000000
.1.3.6.1.2.1.2.2.1.5.4 = Gauge32: 1000000000
.1.3.6.1.2.1.2.2.1.5.5 = Gauge32: 1000000000
.1.3.6.1.2.1.2.2.1.5.6 = Gauge32: 1000000000
.1.3.6.1.2.1.2.2.1.6.1 = Hex-STRING: 4C 5E 0C F4 EC D7
.1.3.6.1.2.1.2.2.1.6.2 = Hex-STRING: 4C 5E 0C F4 EC D7
.1.3.6.1.2.1.2.2.1.6.3 = Hex-STRING: 4C 5E 0C F4 EC D7
.1.3.6.1.2.1.2.2.1.6.4 = Hex-STRING: 4C 5E 0C F4 EC D7
.1.3.6.1.2.1.2.2.1.6.5 = Hex-STRING: 4C 5E 0C F4 EC D7
.1.3.6.1.2.1.2.2.1.6.6 = Hex-STRING: 4C 5E 0C F4 EC D7
.1.3.6.1.2.1.2.2.1.7.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.7.2 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.7.3 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.7.4 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.7.5 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.7.6 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.2 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.3 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.4 = INTEGER: 2
.1.3.6.1.2.1.2.2.1.8.5 = INTEGER: 2
.1.3.6.1.2.1.2.2.1.8.6 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.9.1 = Timeticks: (993404190) 114 days, 23:27:21.90
.1.3.6.1.2.1.2.2.1.9.2 = Timeticks: (721) 0:00:07.21
.1.3.6.1.2.1.2.2.1.9.3 = Timeticks: (800009316) 92 days, 14:14:53.16
.1.3.6.1.2.1.2.2.1.9.4 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.9.5 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.9.6 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.10.1 = Counter32: 1949490121
.1.3.6.1.2.1.2.2.1.10.2 = Counter32: 1311511203
.1.3.6.1.2.1.2.2.1.10.3 = Counter32: 2099701761
.1.3.6.1.2.1.2.2.1.10.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.10.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.10.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.11.1 = Counter32: 2143884405
.1.3.6.1.2.1.2.2.1.11.2 = Counter32: 22010667
.1.3.6.1.2.1.2.2.1.11.3 = Counter32: 659509222
.1.3.6.1.2.1.2.2.1.11.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.11.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.11.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.12.1 = Counter32: 2038074584
.1.3.6.1.2.1.2.2.1.12.2 = Counter32: 78992
.1.3.6.1.2.1.2.2.1.12.3 = Counter32: 19160
.1.3.6.1.2.1.2.2.1.12.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.12.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.12.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.16.1 = Counter32: 1941399549
.1.3.6.1.2.1.2.2.1.16.2 = Counter32: 3334873263
.1.3.6.1.2.1.2.2.1.16.3 = Counter32: 2203823768
.1.3.6.1.2.1.2.2.1.16.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.16.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.16.6 = Counter32: 2516611768
.1.3.6.1.2.1.2.2.1.17.1 = Counter32: 682243290
.1.3.6.1.2.1.2.2.1.17.2 = Counter32: 1199606266
.1.3.6.1.2.1.2.2.1.17.3 = Counter32: 784749816
.1.3.6.1.2.1.2.2.1.17.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.17.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.17.6 = Counter32: 1177616383
.1.3.6.1.2.1.2.2.1.18.1 = Counter32: 279858
.1.3.6.1.2.1.2.2.1.18.2 = Counter32: 688696430
.1.3.6.1.2.1.2.2.1.18.3 = Counter32: 313573
.1.3.6.1.2.1.2.2.1.18.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.18.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.18.6 = Counter32: 689108166
.1.3.6.1.2.1.2.2.1.19.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.6 = Counter32: 0
End of MIB
