### ISSUE TITLE
Serial port graph on cisco 2811 not updating

### ISSUE THREAD

**Issue by wiad** [librenms/librenms#5283]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | cdef7885aabf9e410aa74fca0bbd97ef508b2058
DB Schema | 152
PHP       | 5.4.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

I believe this is the same as #4025. After updating last August serial port graphs on our cisco 2811 boxes stopped updating. After adding this device as a  'bad_ifXEntry' device in definitions.inc.php the graphs started working again. When I just now updated librenms again the graphs stopped updating again. After adding the device as a bad_ifXEntry device again, this time in ios.yaml, it started working. Should the 2811 be added to the bad_ifXEntry array by default?

Also note that the device hardware name is in capitals after my latest update:
```
MariaDB [librenms]> SELECT hardware FROM devices WHERE device_id=46;
+-----------+
| hardware  |
+-----------+
| CISCO2811 |
+-----------+
```

Earlier, in definitions.inc.php, I had the hardware name in lowercase, but now it needs to be in uppercase to work.

**Comment by laf** [comment]
That will have changed from the updates to cisco detection we did a bit ago. It's probably worth adding this as the default and also ignoring case.

Will PR a perm fix now.
