### ISSUE TITLE
Top 5 Interfaces i see 100G Traffic on a device that have max 1Gbps Interface Uplink

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#5287]
Hi !

Currious !

under Top Interfaces i see 100G Traffic but the Device habe a max Uplink Traffic only 1Gbps !

How is this possible ?

Intresting under the same Device -> Weblink -> Device -> Overall Traffic -> the traffic is ok 

![image001](https://cloud.githubusercontent.com/assets/18415083/21592884/c959c402-d111-11e6-901e-97a9eb6c2041.png)

Thanks kind regards kristoferus75

**Comment by laf** [comment]
http://docs.librenms.org/Support/FAQ/#why-do-i-see-traffic-spikes-in-my-graphs
