### ISSUE TITLE
Hardware support request for ZyXel GS1900-8

### ISSUE THREAD

**Issue by wjonker85** [librenms/librenms#5292]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

- [X ] Please include all of the information between the `====================================` section of `./validate.php`.
Component | Version
--------- | -------
LibreNMS  | 75d5e41fd320b077abcff96bdbdaac65a88cffc6
DB Schema | 152
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.28-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [ X] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)

snmpwalk : http://pastebin.com/gYxLx8DU
discovery : http://pastebin.com/5VbK1x7c
poller : http://pastebin.com/x805yMep

- [X ] Please provide as much detail as possible.
Would like support for CPU en memory usage.
Hardware Info :  1.3.6.1.4.1.890.1.15.3.1.11.0
Operating System : Is correct detected in librenms as "ZyXEL Ethernet Switch".
Firmware version : 1.3.6.1.4.1.890.1.15.3.1.6.0
Serial : 1.3.6.1.4.1.890.1.15.3.1.12.0
Memory : 1.3.6.1.4.1.890.1.15.3.2.5.0
CPU Usage : 1.3.6.1.4.1.890.1.15.3.2.4.0
CPU 5sec Usage : 1.3.6.1.4.1.890.1.15.3.2.7.0
CPU 1min Usage : 1.3.6.1.4.1.890.1.15.3.2.8.0
CPU 5min Usage : 1.3.6.1.4.1.890.1.15.3.2.9.0

**Comment by wjonker85** [comment]
Attached the files needed to add CPU and memory support for the ZyXel GS1900-8 switches.
[LibrenmsZynosSupport.zip](https://github.com/librenms/librenms/files/686984/LibrenmsZynosSupport.zip)

**Comment by laf** [comment]
Pastebins removed. Feel free to provide new ones.

**Comment by arrmo** [comment]
Just saw the update on this - I have this switch, can get you the needed info ... if you still want it. What are you after, a snmp output?

**Comment by laf** [comment]
Everything from here: http://docs.librenms.org/Support/FAQ/#faq20

**Comment by arrmo** [comment]
You bet, here you go. BTW, reopen this?
Discovery: https://paste.ubuntu.com/23945334/
Poller: https://paste.ubuntu.com/23945345/
snmpwalk: https://paste.ubuntu.com/23945346/

Thanks!

**Comment by wjonker85** [comment]
Thanks Armo and Laf!

**Comment by arrmo** [comment]
Hi,

Not seeing any CPU or memory related info showing up - should I?

Thanks!
