### ISSUE TITLE
devices: Add OS Detection support for MobileIron Appliance

### ISSUE THREAD

**Issue by vgeannin** [librenms/librenms#5293]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
==========================================================
Component | Version
--------- | -------
LibreNMS  | ce0aa4286c5832f85d523bd456585f7312865bf9
DB Schema | 152
PHP       | 7.0.14
MySQL     | 10.1.20-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

- [x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)

[discovery.txt](https://github.com/librenms/librenms/files/684223/discovery.txt)
[Poller.txt](https://github.com/librenms/librenms/files/684225/Poller.txt)
[snmpbulkwalk.txt](https://github.com/librenms/librenms/files/684219/snmpbulkwalk.txt)

- [x] Please provide as much detail as possible.

**Comment by vgeannin** [comment]
Hi All,

MobileIron Appliance are basically Centos Linux 6 server.
There is two type of appliance : 
 - Core server
 - Sentry server
to determine the type of appliance, yous have to do a snmpwallk on the install software : 
         snmp_walk($device, 'hrSWInstalledName', '-Osqnv', 'HOST-RESOURCES-MIB');
if there is a software call "mobileiron", you have a mobileiron appliance
then to determine the type and version
 for core : you have a software call "mobileiron-core-base"
 for sentry : you have a software call "mi-mics"

The version is after the software name

**Comment by laf** [comment]
We need the information asked for when adding a new device above.

**Comment by vgeannin** [comment]
I add the infos requested

Vincent

**Comment by laf** [comment]
We can't walk the entire host-resource-mib to work out what device type this is. That's way ott.

If they don't provide a MIB we can use then I'm not sure we can add detection for this.

**Comment by vgeannin** [comment]
They don't provide MIB

**Comment by laf** [comment]
@librenms/reviewers anyone else have any thoughts but looks a no go from what I've seen.

**Comment by laf** [comment]
No further information provided and walking an entire tree isn't workable.
