### ISSUE TITLE
Brocade FabricOS not getting Health/Sensors info

### ISSUE THREAD

**Issue by famahmou** [librenms/librenms#5294]
Hello,

ALL my SAN switches (Brocade 6520 & HP Blade SAN) not getting Health info. anyone face this issue before?

here is a sample of one of the switches:
Hardware: Brocade 6548 Switch
**Operating System: Brocade FabricOS v7.2.1b **
Object ID: enterprises.1588.2.1.1.129

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by laf** [comment]
duplicate
