### ISSUE TITLE
Brocade FabricOS not getting Health/Sensors info

### ISSUE THREAD

**Issue by famahmou** [librenms/librenms#5295]
[FabOS-Discovery.txt](https://github.com/librenms/librenms/files/685421/FabOS-Discovery.txt)
[FabOS-Poller.txt](https://github.com/librenms/librenms/files/685423/FabOS-Poller.txt)
[FabOS-snmpwalk.txt](https://github.com/librenms/librenms/files/685422/FabOS-snmpwalk.txt)

Hello,

ALL my SAN switches (Brocade 6520 & HP Blade SAN) not getting Health info. anyone face this issue before?

here is a sample of one of the switches:
Hardware: Brocade 6548 Switch
**Operating System: Brocade FabricOS v7.2.1b **
Object ID: enterprises.1588.2.1.1.129

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the -bash-4.2$ ./validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | 9605043b8fbc231ac9cd36713d9ddb46a34a7375
DB Schema | 152
PHP       | 7.0.14
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

[WARN]  Your install is out of date, last update: Tue, 03 Jan 2017 15:02:23 +0000
[OK]    Database connection successful
-bash-4.2$
- [x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by famahmou** [comment]
==========================================================
Component | Version
--------- | -------
LibreNMS  | 9605043b8fbc231ac9cd36713d9ddb46a34a7375
DB Schema | 152
PHP       | 7.0.14
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

**Comment by laf** [comment]
Please provide the information asked for adding a new device above.

**Comment by famahmou** [comment]
@laf I was able to add the new Device successfully in NMS, I wasnt able to tag it here (github) under "New Device" .
I also update the info above with the "./validate.php"

**Comment by gigeCDN** [comment]
same thing but with a NetIRON router

System Name	netiron cer 2024f-4x
Hardware	snCer2000Family.7
Operating System	Brocade IronWare ce05600d
Serial	************
Object ID	enterprises.1991.1.3.51.7

**Comment by laf** [comment]
Seems the data is in  .1.3.6.1.4.1.1588.2 which doesn't exist in your output. Can you provide the output of: `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .1.3.6.1.4.1.1588.2`

**Comment by famahmou** [comment]
@laf attached the output requested.
[snmpwalk.out.txt](https://github.com/librenms/librenms/files/756060/snmpwalk.out.txt)
