### ISSUE TITLE
Feature Request - Google Map of Device Location on Device Overview Page

### ISSUE THREAD

**Issue by DonovanEsterhuizen** [librenms/librenms#5296]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Feature Request

It would quite helpful to have Google map image of where the device is located on the device overview page of the device.

Thanks

**Comment by laf** [comment]
We already have map support!

**Comment by DonovanEsterhuizen** [comment]
It would be a nice enhancement though...

**Comment by laf** [comment]
What having Google maps instead of what we have?

**Comment by f0o** [comment]
Showing the location on the device page via a map engine is a nice feature. Not sure if I'd like to use Google maps though. Leaflet is very handy and a lot less privacy breaching from my POV

**Comment by laf** [comment]
Ah didn't see the device overview page, still a 👎 from me though as it seems pointless and a waste of space.

**Comment by DonovanEsterhuizen** [comment]
Sleep on it :)

**Comment by DonovanEsterhuizen** [comment]
It wont be pointless its part of the devices overview.

 The lat and long can be pulled from the the syslocation all that is required is map/leaflet to be added to the page. 

Can i be pointed into a direction of how to add it myself?

**Comment by florianbeer** [comment]
I'd actually like this as well. On the left side there seems to be enough space. In my setup, with the device's syslog messages on the right side, there is always a lot of whitespace on the left.

**Comment by Rosiak** [comment]
We could just add it under Devices > Location ?
<img width="623" alt="screen shot 2017-01-04 at 16 04 03" src="https://cloud.githubusercontent.com/assets/6378934/21646692/716a4712-d297-11e6-8209-68dc9ec2027d.png">

**Comment by DonovanEsterhuizen** [comment]
@Rosiak 

Not sure what you mean the idea is to see each device location individually on the device overview page of the device.
