### ISSUE TITLE
Exinda Device Support

### ISSUE THREAD

**Issue by DonovanEsterhuizen** [librenms/librenms#5297]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

We have a wan op devices called Exinda

If we provide snmp access to the device will it possible to add support for this device?

**Comment by laf** [comment]
You can provide the details we need as per the 3rd point above.

**Comment by DonovanEsterhuizen** [comment]
Cool will get the info to you

**Comment by DonovanEsterhuizen** [comment]
Hi 

As requested.

[Exinda-Discovery.txt](https://github.com/librenms/librenms/files/692855/Exinda-Discovery.txt)
[Exinda-Poller.txt](https://github.com/librenms/librenms/files/692856/Exinda-Poller.txt)
[linux-10.245.3.2.txt](https://github.com/librenms/librenms/files/692857/linux-10.245.3.2.txt)

**Comment by DonovanEsterhuizen** [comment]
Hi

Is there anything else that is needed?

Thanks

**Comment by laf** [comment]
Time
