### ISSUE TITLE
New Device: CheckPoint 12400 Firewall shows as Linux Server

### ISSUE THREAD

**Issue by famahmou** [librenms/librenms#5299]
[discovery.txt](https://github.com/librenms/librenms/files/685401/discovery.txt)
[poller.txt](https://github.com/librenms/librenms/files/685399/poller.txt)
[snmpwalk.txt](https://github.com/librenms/librenms/files/685400/snmpwalk.txt)

I added a new CheckPoint Firewall and they show as Linux Servers, I moved them manually as a Firewall but still showing Linux.

**System Name 	pr1fw01
Resolved IP 	10.10.10.1
Hardware 	Generic x86 64-bit
Operating System 	Linux 2.6.18-92cpx86_64**

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `    bash-4.2$ ./validate.php
    ==========================================================
    Component | Version
    --------- | -------
    LibreNMS | 9605043b8fbc231ac9cd36713d9ddb46a34a7375
    DB Schema | 152
    PHP | 7.0.14
    MySQL | 5.5.52-MariaDB
    RRDTool | 1.4.8
    SNMP | NET-SNMP 5.7.2
    ==========================================================

[WARN] Your install is out of date, last update: Tue, 03 Jan 2017 15:02:23 +0000
[OK] Database connection successful
-bash-4.2$`.
- [x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20) [attached]
- [x] Please provide as much detail as possible.

**Comment by laf** [comment]
We need the info asked for in point 3 above for a new device.

**Comment by famahmou** [comment]
@laf I've checked the box for point 3, thanks
