### ISSUE TITLE
Cisco Vendor Icons displaying as Generic

### ISSUE THREAD

**Issue by NetCo-Jan** [librenms/librenms#5301]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

Hi Guys
Need some assistance please, after doing a update of LibreNMS all the Cisco Devices (roughly 200) is now showing the grey question mark as the Vendor Icon.

I have rebooted and ensured that the Validate.php is happy - but still no joy - see attached screenshot. 
This only happened after the last update

librenms@librenms:~$ ./validate.php 
==========================================================
Component | Version
--------- | -------
LibreNMS  | cc8e31d1a194b6bcae0cfdc6ddeee16d779c41a1
DB Schema | 153
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.28-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

![screenshot 353](https://cloud.githubusercontent.com/assets/24909687/21635147/b537b34a-d264-11e6-8490-067e92fbd279.png)

**Comment by anden4380** [comment]
It is not only Cisco also HP

**Comment by aldemira** [comment]
I also have the same problem. Although my servers (windows-linux) have the proper icon.

**Comment by NetCo-Jan** [comment]
Same in my case, Ubuntu and Windows - no problem - only the Cisco Devices. I have two devices that is Disabled there Icons is still normal - as soon as i enable them they also changed to Generic for some odd reason

**Comment by laf** [comment]
Fixed
