### ISSUE TITLE
Update Mikrotik Logo to use the new design.

### ISSUE THREAD

**Issue by InsaneSplash** [librenms/librenms#5305]
Please update the Mikrotik logo with the new design made available by Mikrotik.

[http://designs.mikrotik.com/logo.php](http://designs.mikrotik.com/files/mikrotik_logo.zip)
[http://designs.mikrotik.com/files/mikrotik_logo.zip](http://designs.mikrotik.com/files/mikrotik_logo.zip)

**Comment by InsaneSplash** [comment]
Use only approved MikroTik logo artwork:

- The Logo may only appear in black, reversed out to white, or in Latvian red (Pantone 491)
- The Logo must always be at least 60 pixels in width.
- The Logo must only appear in a horizontal position.
- The Logo must stand alone and may not be combined with any other object, including but not limited to other logos, words, graphics, photos, slogans, numbers, design features, or symbols. The Logo must never be used to represent the word "MikroTik" in text, including in a headline, product-name logotype, or body copy.
- In websites, usage of the PNG image format is recommended, if using JPG no more than 30% compression can be used on the logo file (30% compression = 70% quality = 7/10 in PS)
- To properly stage the Logo, a minimum clearance between the Logo and other elements must be maintained. The cap height of the M in the Logo indicates the measurement of minimum clearance between the Logo and other elements on all sides of the Logo: View here

**Comment by geordish** [comment]
![image](https://cloud.githubusercontent.com/assets/1226821/21933257/8fde63d4-d99c-11e6-912a-ea1190418067.png)
