### ISSUE TITLE
Mikrotik CCR-1016 v6.36.3 'CPU Usage' Graphs disappeared after last update.

### ISSUE THREAD

**Issue by alcore89** [librenms/librenms#5310]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
Component | Version
--------- | -------
LibreNMS  | 82579fbb0405bc65520bc51a73c6e8f564a35079
DB Schema | 153
PHP       | 5.6.24-0+deb8u1
MySQL     | 10.0.26-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
=======================================================

**Comment by laf** [comment]
Please provide the output of `./discovery.php -h HOSTNAME -d -m processors`

**Comment by alcore89** [comment]
After running script everything went back to normal. Issue is fixed. Sorry for bringing the problem here, but I thought it might be more serious, because the graphs disappeared after update. Thanks for fast help, thread may be closed.
