### ISSUE TITLE
"Residue" of deleted devices in DB tables "alerts" and "alert_log"

### ISSUE THREAD

**Issue by cs-1** [librenms/librenms#5318]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

It's up to date.

- [ ] Please include all of the information between the `====================================` section of `./validate.php`.

Component | Version
--------- | -------
LibreNMS  | 036f411e138bff272a15e9b64b7df9f3e7bdedbb
DB Schema | 153
PHP       | 5.5.9-1ubuntu4.20
MySQL     | 5.5.53-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

We experienced a problem with alerts for devices that where not present in the "devices" table of the DB anymore. We could find device_ids in alerts and alert_log that weren't in "devices". Alerts without hostnames etc. would be present in the webui for these ghost devices. Deleting all entries for these ghosts from "alerts" and "alert_log"  fixed the problem. It looks like there might be a glitch in the deletion process for devices.

**Comment by laf** [comment]
I know you might not remember but were these devices you deleted from the webui? I'm wondering if php execution is just timing out due to the volume of data.

**Comment by cs-1** [comment]
Sorry for asking back (language barrier, I suppose ;) ): are you asking whether I deleted the devices from the webui or if they were deleted with some other method? I'm not 100% sure but it's very likely that they were deleted from the webui.

**Comment by laf** [comment]
Yes that's what I was asking :)

**Comment by cs-1** [comment]
Ok, good. :) I'm very sure that they were deleted from the webui because we normally remove devices via webui that have been taken offline on purpose.
