### ISSUE TITLE
Sensor limits changed, cannot customize

### ISSUE THREAD

**Issue by network-guy** [librenms/librenms#5320]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | 036f411e138bff272a15e9b64b7df9f3e7bdedbb
DB Schema | 153
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.28-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

[OK]    Database connection successful

This morning I got sensor under limit alerts for all my 4510R+E switches with Sup8E. The alerts are specifically for the current bias for 10Gb transceivers. The upper and lower limit are both set to 0.131 and when I change it the change never takes. 

![image](https://cloud.githubusercontent.com/assets/18373118/21691354/e0728420-d33d-11e6-88d8-81061d2df4a4.png)

I also had an issue with an ASR 9001 where most of the sensors defaulted to -3276.8, but I was able to change those. 

I looked through the recent merges and didn't notice anything obvious that would change this behavior. Any ideas?

**Comment by laf** [comment]
Have you checked your developer console to see if anything is recoreded?

**Comment by arrmo** [comment]
Hi,

Not exactly the same (or is it?) I have been having issues lately with some temperature sensors. I override the limits, and it works fine ... for a day or two. Then it "loses" my updates. I have done this 3 or 4 times now, and it keeps happening. I initially thought I was just losing it ... ;).

Thanks!

**Comment by arrmo** [comment]
FYI, at least on of the sensors seems to be getting dropped and re-added. No, no idea why ... :). It's a MB sensor, so it's not being removed.

2017-01-08 00:33:06	Sensor Deleted: temperature lmsensors 1 temp1
2017-01-08 12:33:06	Sensor Added: temperature lmsensors 1 temp1

**Comment by laf** [comment]
different issue, please create a separate issue with discovery debugs showing the removal and addition of those sensors.

**Comment by arrmo** [comment]
Sure, will do. Was thinking they may be related - but not, agreed ... new issue.

**Comment by network-guy** [comment]
Looks like the main issue may have been a browser cache problem. Still not sure why my ASR limits changed, but it's been working fine since I reset the values.
