### ISSUE TITLE
Update APC Humidity sensor

### ISSUE THREAD

**Issue by NerdBlender** [librenms/librenms#5325]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

Would it be sensible to assume that if the APC humidity sensor is reading -1, then there is no humidity sensor attached? Happy to create a PR for this if it seems a sensible assumption.

**Comment by laf** [comment]
I'd say so yes, if -1 isn't a valid value then we should skip discovery of that sensor.

Most of the ones I add now all check for values of 0 or GT.
