### ISSUE TITLE
AD or LDAP example

### ISSUE THREAD

**Issue by joseaugustocardoso** [librenms/librenms#5326]
I trying to connect LibreNMS with my AD, but I receiving fail. Have any example for it?

**Comment by joseaugustocardoso** [comment]
Also I cant see the error logs

I used this documentation as reference:
http://docs.librenms.org/Extensions/Authentication/#active-directory-authentication

**Comment by laf** [comment]
I don't use it myself but some links for you to try:

https://groups.google.com/forum/#!searchin/librenms-project/active$20directory%7Csort:relevance

https://www.reddit.com/r/LibreNMS/comments/5cnezz/librenms_configauth_mechanism_active_directory/

**Comment by joseaugustocardoso** [comment]
I got some success, but its strange.. 
I receiving error: 
Login error
Can't contact LDAP server
TLS error -8179:Peer's Certificate issuer is not recognized.

But, if I F5 some times, I can auth with success.

$config['auth_mechanism'] = "active_directory";
$config['auth_ad_url']                     = "ldaps://x.x.x.x";
$config['auth_ad_domain']                  = "domain.net";
$config['auth_ad_base_dn']                 = "dc=domain,dc=net";
$config['auth_ad_check_certificates']      = 0;  // require a valid ssl certificate
$config['auth_ad_debug']                   = 1; // enable for verbose debug messages
$config['active_directory']['users_purge'] = 30;    // purge users who haven't logged in for 30 days.
$config['auth_ad_require_groupmembership'] = 0; // require users to be members of a group listed below

It possible to see any logs?

**Comment by joseaugustocardoso** [comment]
All solved.
just changed 
$config['auth_ad_url'] = "ldaps://x.x.x.x";
to
$config['auth_ad_url'] = "ldap://x.x.x.x";
