### ISSUE TITLE
Autodiscovery: wrong SNMP version detected

### ISSUE THREAD

**Issue by Noirvent** [librenms/librenms#5330]
Our LibreNMS fail to detect the correct version of SNMP to use, using v2c (with "public" community) instead of the v3 for our servers.

Manually specifying SNMPv3 credentials in the host's config of the WebUI works.

The command
```
/opt/librenms/snmp-scan.php -v -r 192.168.22.51/32 -d
```
Give us this output: http://pastebin.com/KdQcYZ1W

Our ./validate.php

```
root@bonvolo:/opt/librenms# ./validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | 1b7d3e0ab89ea1c48af1be13dc4f0c92de58e686
DB Schema | 152
PHP       | 5.6.29-0+deb8u1
MySQL     | 10.0.28-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

[OK]    Database connection successful
```
Our config.php : http://pastebin.com/efq7t1BX

The client snmpd.conf: http://pastebin.com/zx7sPm9y

**Comment by laf** [comment]
If that device responds to both v2c and v3 then the config is tried in order iirc so we will add it by the v2c details first unless they don't respond.

**Comment by laf** [comment]
No further info provided.
