### ISSUE TITLE
BUG: Wrong icon for SmartEdge devices

### ISSUE THREAD

**Issue by kyob** [librenms/librenms#5336]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | d6e260fde6b67c0eb9cbb308d575987cfc6b7db9
DB Schema | 153
PHP       | 7.0.14
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

I saw today that my SmartEdge 600 got "ZTE" icon what is not true because it should be ERICSSON.

Probably connected with https://github.com/librenms/librenms/issues/5181

**Comment by laf** [comment]
We haven't added smartedge support so sounds just like they are being picked up as another vendor. When support is added this will change.
