### ISSUE TITLE
get SLA graph for a device with API 

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#5337]
Hi !

with curl -H 'X-Auth-Token: YOURAPITOKENHERE' https://librenms.org/api/v0/devices/localhost/graphs

I get all available graphs but without the ports !

but the ip sla graphs are missing !

How can i get the ip sla graph for a specific device with api ?

Or is it better to use rrdtool to create a graph because i need only the last month in the graph ?

thanks

kind regrads

kristoferus75

**Comment by laf** [comment]
Do you have a link to the page that you see these on in the first place?

**Comment by kristoferus75** [comment]
i see on this page how it works with rrdtool:

https://oss.oetiker.ch/rrdtool/doc/rrdgraph_examples.en.html

-> Time ranges

or you mean the link of our librenms sla:

192.168.1.200/device/device=12/tab=slas/

rrdtool graph sla.png --alt-autoscale-max --rigid -E --start 1483809900 --end 1483896300 --width 1728 --height 317.66666666667 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal COMMENT:'Round Trip Time Cur Min Max\n' DEF:rtt=/mnt/sdb1/rrd/testdevice.rrd:rtt:AVERAGE VDEF:avg=rtt,AVERAGE LINE1:avg#CCCCFF:'Average':dashes GPRINT:rtt:AVERAGE:%4.1lfms\\l LINE1:rtt#CC0000:'RTT' GPRINT:rtt:LAST:%4.1lfms GPRINT:rtt:MIN:%4.1lfms GPRINT:rtt:MAX:%4.1lfms\\l

**Comment by laf** [comment]
Try device_sla as the graph type.

**Comment by kristoferus75** [comment]
this doesn't work !

**Comment by laf** [comment]
You need to provide more info than it doesn't work, what's the output from the api call? Show us the API call you made (hide the api key and hostname).

**Comment by laf** [comment]
No further info provided.
