### ISSUE TITLE
ADD: Hikvision Camera Device Support

### ISSUE THREAD

**Issue by mirino75** [librenms/librenms#5350]
Hello,

Is it possible add support for Hikvision Cameras? (HW: DS-2CD2132F-I)

I attached HIK-DEVICE-MIB.txt

Thank you

[HIK-DEVICE-MIB.txt](https://github.com/librenms/librenms/files/692323/HIK-DEVICE-MIB.txt)
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by laf** [comment]
Have you tried to add them? I'm sure I added support for this exact camera.

If you have and it's not working, we need the output from point 3 you've not ticked above.

**Comment by mirino75** [comment]
[snmpbulkwalk.txt](https://github.com/librenms/librenms/files/692358/snmpbulkwalk.txt)
[poller_1.txt](https://github.com/librenms/librenms/files/692359/poller_1.txt)
[discovery_1.txt](https://github.com/librenms/librenms/files/692360/discovery_1.txt)

**Comment by laf** [comment]
What do you want adding? That's detected as a hikvision device already.

**Comment by laf** [comment]
For the walk, use ` .1.3.6.1.4.1.39165.1.1` instead of `.`

**Comment by jkldgoefgkljefogeg** [comment]
The IP cameras constantly generate device rebooted alerts (possibly because no SNMP sysUpTime support). I suggest creating a separate device type for IP Cameras. Hikvision has HTTP APIs that is far more useful than the poorly implemented SNMP

**Comment by laf** [comment]
It is because hikvision don't send uptime info, we can't fix that.

**Comment by jkldgoefgkljefogeg** [comment]
Is there any ill effect from changing the default Device rebooted rule to `%devices.uptime < "300" && %macros.device = "1" && %devices.uptime > "1"`?

**Comment by laf** [comment]
Other than the fact that devices could miss out on an alert for when the uptime is 0 or 1 no
