### ISSUE TITLE
LibreNMS loading blank page, daily.sh failed 

### ISSUE THREAD

**Issue by famahmou** [librenms/librenms#5354]
it was working fine the day before 1/7/2017
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php`.
PHP Parse error:  syntax error, unexpected '<<' (T_SL), expecting end of file in /opt/librenms/includes/definitions.inc.php on line 710
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x ] Please provide as much detail as possible.
 ./daily.sh
PHP Parse error:  syntax error, unexpected '<<' (T_SL), expecting end of file in /opt/librenms/includes/definitions.inc.php on line 710
Updating SQL-Schema                                FAIL
Updating submodules                                OK
Cleaning up DB                                     FAIL
Fetching notifications                             FAIL
-----------------------------------------------------------

**Comment by laf** [comment]
I'm guessing you've edited /opt/librenms/includes/definitions.inc.php

`git status`

**Comment by famahmou** [comment]
@laf 
[librenms@pr1vmx06 ~]$ git status
# On branch master
# Your branch is ahead of 'origin/master' by 26 commits.
#   (use "git push" to publish your local commits)
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       validate.php-out
nothing added to commit but untracked files present (use "git add" to track)
[librenms@pr1vmx06 ~]$

**Comment by laf** [comment]
`git log -n 5`

**Comment by famahmou** [comment]
[git-log.txt](https://github.com/librenms/librenms/files/692379/git-log.txt)

**Comment by laf** [comment]
You've got local commits so you've modified some things. If this is intentional then you'll need to work through and fix this yourself. If it's not then you can just `git reset --hard origin/master`

**Comment by murrant** [comment]
This looks like an incomplete `git pull`

`git reset --hard origin/master`  will do the trick  you might also need to remove .mention-bot and tests/snmpsim/gaia1.snmprec

**Comment by laf** [comment]
@murrant the output from git log shows commits that aren't ours.

**Comment by famahmou** [comment]
Thanks! I did the reset and the page is loading properly now.

**Comment by murrant** [comment]
Oops, yes, I see that defintions.inc changes have actually been committed.
