### ISSUE TITLE
overlib_mini.js Requires unsafe-eval

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#5355]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ x] Please provide as much detail as possible.

Hi,

Trying to secure my site / content, and only this one file (overlib_mini.js) requires unsafe-eval (script-src). Perhaps correct this?

Thanks!

**Comment by laf** [comment]
This is a 3rd party library https://github.com/overlib/overlib so not something we can fix.

**Comment by arrmo** [comment]
No problem, makes sense.

Thanks.
