### ISSUE TITLE
Big big pinguin 

### ISSUE THREAD

**Issue by ouafnico** [librenms/librenms#5358]
Hi
it seems a recent update have made a new change, the pinguin image is very very big.

Can you correct it please :)
![capture](https://cloud.githubusercontent.com/assets/807350/21759629/ffff7220-d645-11e6-8e6f-7547fc16a3e1.PNG)

![sans titre](https://cloud.githubusercontent.com/assets/807350/21759609/d8848140-d645-11e6-8807-44d3bfe0453d.png)

Thanks :)

**Comment by laf** [comment]
Just force a browser refresh
