### ISSUE TITLE
ADD: Support dasan V8240

### ISSUE THREAD

**Issue by aliakcza** [librenms/librenms#5359]
Is it possible to add support V8240?

      SysInfo (System Information)
      Model Name: V8240_SFU
      Main Memory Size: 1024MB
      Flash Memory Size 8 MB (SPANSION 29GL064N), 32 MB (SPANSION 29GL256N), 32 MB (SPANSION 29GL256N)
      H / W Revision: DS-A5-340-A1
      H / W Address: = [CUT] =
      RTC Information: DS174X
      Serial Number: = [CUT] =
      S / W Compatibility: 3, 7
      Package Version: RP610-003
      NOS Version: 6.10
      B / L Version: 6.04
      PLD Version: 0x11

.1.3.6.1.2.1.1.1.0 = STRING: "V8240_SFU NOS 6.10/00:d0:cb:83:da:39"
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.6296.1.2.4.1

Component | Version
--------- | -------
LibreNMS  | 3d0cf76e9b1127ba393933ce49c3eaca3e9f4a97
DB Schema | 153
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.28-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

./discovery.php: http://pastebin.com/vKxAAnLB
./poller.php: http://pastebin.com/fC8GQzyG
snmpwalk: http://pastebin.com/sG4WQifJ :)

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by laf** [comment]
Please please please read the information above!

**Comment by aliakcza** [comment]
I updated information, please check :)

**Comment by laf** [comment]
You're still missing the snmpwalk :)

**Comment by aliakcza** [comment]
added :)
