### ISSUE TITLE
cisco logo resizing error

### ISSUE THREAD

**Issue by Johii** [librenms/librenms#5360]
After autoupdating i assume, cisco logo svg pictures have stopped being resized correctly on the /availability-map/ page.

![billede](https://cloud.githubusercontent.com/assets/25009408/21769434/f79fb2d2-d67e-11e6-9ad5-e6849aa59e6a.png)

Component | Version
--------- | -------
LibreNMS  | b3f62183594fb2e17eb1330ffddc2d3fea034166
DB Schema | 152
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.28-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by famahmou** [comment]
I got the same issue with HP, F5, Brocade logos in availability Map

**Comment by Rosiak** [comment]
Can confirm this one too.

**Comment by wiad** [comment]
I can confirm this on Firefox 45.6.0, however Chrome 55.0.2883.87 seems to work fine.

**Comment by laf** [comment]
Please update. THis was fixed earirr
