### ISSUE TITLE
Add support for Dasan Networks GPON OLT V8240_SFU

### ISSUE THREAD

**Issue by millosz222** [librenms/librenms#5361]
Dasan Networks GPON OLT V8240_SFU

SysInfo(System Information)
     Model Name          : V8240_SFU
     Main Memory Size    : 1024 MB
     Flash Memory Size   : 8 MB(SPANSION 29GL064N), 32 MB(SPANSION 29GL256N), 32 MB(SPANSION 29GL256N)
     H/W Revision        : DS-A5-340-A1
     H/W Address         : 00:d0:cb:92:19:a3
     RTC Information     : DS174X
     Serial Number       : MF3RRWF129A0116
     S/W Compatibility   : 3, 7
     Package Version     : RP607-002
     NOS Version         : 6.07
     B/L Version         : 6.26
     PLD Version         : 0x12

ps. 
Dasan V5824G works good 

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by laf** [comment]
You seem to have ignored all of the information above - please read it carefully and re-create an issue.
