### ISSUE TITLE
lmsensors Being Dropped / Re-added

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#5363]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ X] Please include all of the information between the `====================================` section of `./validate.php`.
- [ X] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ X] Please provide as much detail as possible.

Hi,

I have been seeing (motherboard) temp sensors being dropped / re-added - information below from the logs,

2017-01-08 00:33:06	Sensor Deleted: temperature lmsensors 1 temp1
2017-01-08 12:33:06	Sensor Added: temperature lmsensors 1 temp1

Thanks!

**Comment by Rosiak** [comment]
Can you please post the output of 2 runs of the following command:
```
./discovery.php -h HOSTNAME -d -m sensors
```

**Comment by arrmo** [comment]
Sure! Here you go. BTW, the sensors have stayed on now for ~ a day or so. They don't drop all the time, but it's happened enough that it's also not a one time thing.

Thanks!

[sensors-pass1.txt](https://github.com/librenms/librenms/files/695119/sensors-pass1.txt)
[sensors-pass2.txt](https://github.com/librenms/librenms/files/695120/sensors-pass2.txt)

**Comment by laf** [comment]
Neither of those show the removal :( I know this will be a pain but we'll need to see one of those to be able to see what's going on.

I do expect it's the device not responding to the snmp request that's causing it though.

**Comment by arrmo** [comment]
Yep, completely understand and agree. I can keep an eye out for it happening again ... but is there a way to get the needed info post-mortem?

Thanks!

**Comment by laf** [comment]
Not that I can think of :(

**Comment by laf** [comment]
Feel free to provide the info needed and we can re-open

**Comment by arrmo** [comment]
Will do. It happened again the other day, but of course after the fact no logs after the fact .. :(

**Comment by arrmo** [comment]
FYI, happened yet again - I admit, not sure how to debug it. But one observation - it "seems" to happen when a sensor gets down near 0C => sort of appears like this triggers the sensor going away.

I could be wrong - just trying to help out!

**Comment by arrmo** [comment]
Yes, this seems like my issue as well! Maybe I wasn't crazy after all ... LOL.

Thanks!
