### ISSUE TITLE
HP Enclosure blade status

### ISSUE THREAD

**Issue by rpelissi** [librenms/librenms#5366]
Hi,
Is it possible to add to the HP enclosure (C3000 or C7000) the blade information (status on/off)?
I can have some info on the enclosure itself and I see at http://monitoringtt.blogspot.ca/2012/11/monitoring-hp-bladesystem-devices.html that you can also have the state of the blade which could be very useful. I don't really know how I can help, so if you need additional information, please let me know.
Thanks!

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

**Comment by laf** [comment]
Yes, please provide the information asked for in point 3 above.

**Comment by rpelissi** [comment]
Hi,
Here is the results of the validate.php script:

Component | Version
--------- | -------
LibreNMS  | 93b04fdeec55b4b0138f381cb857d1ce1919f64b
DB Schema | 152
PHP       | 7.0.14
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

Find in attachment the different outputs. Let me know if you need anything else.
Thanks again!
[snmpbulkwalk_output.txt](https://github.com/librenms/librenms/files/694737/snmpbulkwalk_output.txt)
[poller_output.txt](https://github.com/librenms/librenms/files/694738/poller_output.txt)
[discovery_output.txt](https://github.com/librenms/librenms/files/694739/discovery_output.txt)
[compaq-mibs.zip](https://github.com/librenms/librenms/files/694740/compaq-mibs.zip)

**Comment by rbax82** [comment]
I'm pretty sure if you configure IPMI support for your device, it will poll this information already...

**Comment by crcro** [comment]
i think that he is requesting something different than it exists: 
at this time you get info for powered blades, the powered off/missing ones you don't get any info.

did i understood correctly @rpelissi ?

**Comment by rpelissi** [comment]
In fact I am thinking that, if it's possible with the data available with the mib, to have a new tab (like the virtual machines tabs when checking an esx host) that will list the blades and their status (on/off, OK/warn, etc). I do not know if it is also possible to have for each blade the current status of their components (fan, temp, number of cpu, disks, ram). I have not check that in detail sorry for that ;)

**Comment by crcro** [comment]
you can't get any fan info for blades afaik because there are no fans on blades. but the current code supports fan/psu/temps reading for the chassis (i have c7000 currently monitored):

<img width="934" alt="screen shot 2017-01-23 at 4 39 42 am" src="https://cloud.githubusercontent.com/assets/3048315/22189574/04db9d56-e126-11e6-9ac4-33f20d61756c.png">

**Comment by laf** [comment]
@rpelissi any further input on this before it's closed?

**Comment by Rosiak** [comment]
No info provided.
