### ISSUE TITLE
Cisco Nexus 9504 BGP Sessions not been discovered

### ISSUE THREAD

**Issue by DonovanEsterhuizen** [librenms/librenms#5377]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.

librenms@librenms:~$ ./validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | 656a1524d2930de1ae5cc168ec192dfa4f0e44cf
DB Schema | 152
PHP       | 7.0.8-0ubuntu0.16.04.1
MySQL     | 10.0.25-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

We have cisco Nexus 9504  with the following 

N9K-C9504
Cisco NX-OS
7.0(3)I2(2b)

Librenms is not discovering the BGP sessions.

Thanks

**Comment by laf** [comment]
please provide the output of `./discover.php -h HOSTNAME -d -m bgp-peers`

**Comment by DonovanEsterhuizen** [comment]
Here you go

librenms@librenms:~$ ./discovery.php -h 10.252.252.1 -d -m bgp-peers
LibreNMS Discovery
Version info:
Commit SHA: 656a1524d2930de1ae5cc168ec192dfa4f0e44cf
DB Schema: 152
PHP: 7.0.8-0ubuntu0.16.04.1
MySQL: 10.0.25-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP 5.7.3
DEBUG!
SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1]
DB Schema already up to date.
SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE '10.252.252.1' ORDER BY device_id DESC]
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '5']
10.252.252.1 5 nxos
Modules status: Global+ OS  Device
#### Load disco module bgp-peers ####
SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Oqvn -m BGP4-MIB -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.2.1.15.2]
64636

AS64636 SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Oq -m CISCO-BGP4-MIB -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 cbgpPeer2RemoteAs]
CISCO-BGP4-MIB::cbgpPeer2RemoteAs No Such Instance currently exists at this OID

SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Oq -m BGP4-MIB -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 BGP4-MIB::bgpPeerRemoteAs]
BGP4-MIB::bgpPeerRemoteAs No Such Instance currently exists at this OID

Peers :
SQL[SELECT * FROM bgpPeers WHERE device_id = '5' AND (context_name = '' OR context_name IS NULL)]

FIN BGP



>> Runtime for discovery module 'bgp-peers': 0.1440 seconds
#### Unload disco module bgp-peers ####

SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '5' AND `attrib_type` = 'poll_mib' ]
SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='network',`last_discovered_timetaken` ='0.149' WHERE `device_id` = '5']
Discovered in 0.149 seconds

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','10.252.252.1','1484042595.6577','0.203','1')]
./discovery.php 10.252.252.1 2017-01-10 10:03:15 - 1 devices discovered in 0.203 secs
SNMP: Get[0/0.00s] Walk [3/0.14s]
MySQL: Cell[3/0.00s] Row[1/0.00s] Rows[5/0.00s] Column[0/0.00s] Update[1/0.01s] Insert[1/0.00s] Delete[0/0.00s]
librenms@librenms:~$

**Comment by laf** [comment]
```
SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Oq -m CISCO-BGP4-MIB -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 cbgpPeer2RemoteAs]
CISCO-BGP4-MIB::cbgpPeer2RemoteAs No Such Instance currently exists at this OID

SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Oq -m BGP4-MIB -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 BGP4-MIB::bgpPeerRemoteAs]
BGP4-MIB::bgpPeerRemoteAs No Such Instance currently exists at this OID
```

Your device isn't responding back to the standard BGP4-MIB Either you're restricting this in snmp views or the device (oddly) doesn't support it.

**Comment by DonovanEsterhuizen** [comment]
We have checked out SNMp and do not have any views configured

**Comment by laf** [comment]
You might want to open a tac case as according to ftp://ftp.cisco.com/pub/mibs/supportlists/nexus9000/Nexus9000MIBSupportList.html CISCO-BGP4-MIB is supported on the 9k devices but yours isn't responding.

**Comment by DonovanEsterhuizen** [comment]
Will log it with TAC and see what they say, thanks

**Comment by laf** [comment]
Feel free to comment back here when you have more info and we can re-open.

**Comment by DonovanEsterhuizen** [comment]
Hi 

When I do the following:

JHB-Teraco# sh snmp internal translate oidorname bgp i get the following:

JHB-Teraco# sh snmp internal translate oidorname bgp
bgp 1.3.6.1.2.1.15
bgpVersion 1.3.6.1.2.1.15.1
bgpLocalAs 1.3.6.1.2.1.15.2
bgpPeerTable 1.3.6.1.2.1.15.3
bgpPeerEntry 1.3.6.1.2.1.15.3.1
bgpPeerIdentifier 1.3.6.1.2.1.15.3.1.1
bgpPeerState 1.3.6.1.2.1.15.3.1.2
bgpPeerAdminStatus 1.3.6.1.2.1.15.3.1.3
bgpPeerNegotiatedVersion 1.3.6.1.2.1.15.3.1.4
bgpPeerLocalAddr 1.3.6.1.2.1.15.3.1.5
bgpPeerLocalPort 1.3.6.1.2.1.15.3.1.6
bgpPeerRemoteAddr 1.3.6.1.2.1.15.3.1.7
bgpPeerRemotePort 1.3.6.1.2.1.15.3.1.8
bgpPeerRemoteAs 1.3.6.1.2.1.15.3.1.9
bgpPeerInUpdates 1.3.6.1.2.1.15.3.1.10
bgpPeerOutUpdates 1.3.6.1.2.1.15.3.1.11
bgpPeerInTotalMessages 1.3.6.1.2.1.15.3.1.12
bgpPeerOutTotalMessages 1.3.6.1.2.1.15.3.1.13
bgpPeerLastError 1.3.6.1.2.1.15.3.1.14
bgpPeerFsmEstablishedTransitions 1.3.6.1.2.1.15.3.1.15
bgpPeerFsmEstablishedTime 1.3.6.1.2.1.15.3.1.16
bgpPeerConnectRetryInterval 1.3.6.1.2.1.15.3.1.17
bgpPeerHoldTime 1.3.6.1.2.1.15.3.1.18
bgpPeerKeepAlive 1.3.6.1.2.1.15.3.1.19
bgpPeerHoldTimeConfigured 1.3.6.1.2.1.15.3.1.20
bgpPeerKeepAliveConfigured 1.3.6.1.2.1.15.3.1.21
bgpPeerMinASOriginationInterval 1.3.6.1.2.1.15.3.1.22
bgpPeerMinRouteAdvertisementInterval 1.3.6.1.2.1.15.3.1.23
bgpPeerInUpdateElapsedTime 1.3.6.1.2.1.15.3.1.24
bgpIdentifier 1.3.6.1.2.1.15.4
bgpRcvdPathAttrTable 1.3.6.1.2.1.15.5
bgpPathAttrEntry 1.3.6.1.2.1.15.5.1
bgpPathAttrPeer 1.3.6.1.2.1.15.5.1.1
bgpPathAttrDestNetwork 1.3.6.1.2.1.15.5.1.2
bgpPathAttrOrigin 1.3.6.1.2.1.15.5.1.3
bgpPathAttrASPath 1.3.6.1.2.1.15.5.1.4
bgpPathAttrNextHop 1.3.6.1.2.1.15.5.1.5
bgpPathAttrInterASMetric 1.3.6.1.2.1.15.5.1.6
bgp4PathAttrTable 1.3.6.1.2.1.15.6
bgp4PathAttrEntry 1.3.6.1.2.1.15.6.1
bgp4PathAttrPeer 1.3.6.1.2.1.15.6.1.1
bgp4PathAttrIpAddrPrefixLen 1.3.6.1.2.1.15.6.1.2
bgp4PathAttrIpAddrPrefix 1.3.6.1.2.1.15.6.1.3
bgp4PathAttrOrigin 1.3.6.1.2.1.15.6.1.4
bgp4PathAttrASPathSegment 1.3.6.1.2.1.15.6.1.5
bgp4PathAttrNextHop 1.3.6.1.2.1.15.6.1.6
bgp4PathAttrMultiExitDisc 1.3.6.1.2.1.15.6.1.7
bgp4PathAttrLocalPref 1.3.6.1.2.1.15.6.1.8
bgp4PathAttrAtomicAggregate 1.3.6.1.2.1.15.6.1.9
bgp4PathAttrAggregatorAS 1.3.6.1.2.1.15.6.1.10
bgp4PathAttrAggregatorAddr 1.3.6.1.2.1.15.6.1.11
bgp4PathAttrCalcLocalPref 1.3.6.1.2.1.15.6.1.12
bgp4PathAttrBest 1.3.6.1.2.1.15.6.1.13
bgp4PathAttrUnknown 1.3.6.1.2.1.15.6.1.14
bgpTraps 1.3.6.1.2.1.15.7
bgpEstablished 1.3.6.1.2.1.15.7.1
bgpBackwardTransition 1.3.6.1.2.1.15.7.2
mplsVpnVrfBgpNbrAddrTable 1.3.6.1.3.118.1.2.4
mplsVpnVrfBgpNbrAddrEntry 1.3.6.1.3.118.1.2.4.1
mplsVpnVrfBgpNbrIndex 1.3.6.1.3.118.1.2.4.1.1
mplsVpnVrfBgpNbrRole 1.3.6.1.3.118.1.2.4.1.2
mplsVpnVrfBgpNbrType 1.3.6.1.3.118.1.2.4.1.3
mplsVpnVrfBgpNbrAddr 1.3.6.1.3.118.1.2.4.1.4
mplsVpnVrfBgpNbrRowStatus 1.3.6.1.3.118.1.2.4.1.5
mplsVpnVrfBgpNbrStorageType 1.3.6.1.3.118.1.2.4.1.6
mplsVpnVrfBgpNbrPrefixTable 1.3.6.1.3.118.1.2.5
mplsVpnVrfBgpNbrPrefixEntry 1.3.6.1.3.118.1.2.5.1
mplsVpnVrfBgpPathAttrPeer 1.3.6.1.3.118.1.2.5.1.1
mplsVpnVrfBgpPathAttrIpAddrPrefixLen 1.3.6.1.3.118.1.2.5.1.2
mplsVpnVrfBgpPathAttrIpAddrPrefix 1.3.6.1.3.118.1.2.5.1.3
mplsVpnVrfBgpPathAttrOrigin 1.3.6.1.3.118.1.2.5.1.4
mplsVpnVrfBgpPathAttrASPathSegment 1.3.6.1.3.118.1.2.5.1.5
mplsVpnVrfBgpPathAttrNextHop 1.3.6.1.3.118.1.2.5.1.6
mplsVpnVrfBgpPathAttrMultiExitDisc 1.3.6.1.3.118.1.2.5.1.7
mplsVpnVrfBgpPathAttrLocalPref 1.3.6.1.3.118.1.2.5.1.8
mplsVpnVrfBgpPathAttrAtomicAggregate 1.3.6.1.3.118.1.2.5.1.9
mplsVpnVrfBgpPathAttrAggregatorAS 1.3.6.1.3.118.1.2.5.1.10
mplsVpnVrfBgpPathAttrAggregatorAddr 1.3.6.1.3.118.1.2.5.1.11
mplsVpnVrfBgpPathAttrCalcLocalPref 1.3.6.1.3.118.1.2.5.1.12
mplsVpnVrfBgpPathAttrBest 1.3.6.1.3.118.1.2.5.1.13
mplsVpnVrfBgpPathAttrUnknown 1.3.6.1.3.118.1.2.5.1.14
mplsVpnVrfBgpNbrGroup 1.3.6.1.3.118.3.1.5
mplsVpnVrfBgpPrefixGroup 1.3.6.1.3.118.3.1.6
ciscoBgpPolAcctMIB 1.3.6.1.4.1.9.9.148
ciscoBgpPolAcctMIBObjects 1.3.6.1.4.1.9.9.148.1
ciscoBgpPolAcctMIBConformance 1.3.6.1.4.1.9.9.148.3
ciscoBgpPolAcctMIBCompliances 1.3.6.1.4.1.9.9.148.3.1
ciscoBgpPolAcctMIBCompliance 1.3.6.1.4.1.9.9.148.3.1.1
ciscoBgpPolAcctMIBGroups 1.3.6.1.4.1.9.9.148.3.2

does this help in any way?

**Comment by laf** [comment]
Nope, look at my output above, bgpPeerRemoteAs is listed in that table but doesn't respond.

**Comment by DonovanEsterhuizen** [comment]
okay found a solution, sort of

the bgp is configured in vrf and thats why we could not poll it we had to apply the config below

snmp-server context MMI vrf MMI
snmp-server mib community-map **yourcommunitystring** context MMI

unfortunately we have another VRf with BGP in it and we have to use another context to with a different community string to poll it has described below in the url

http://packetpushers.net/monitoring-vrfs-on-ios-xr/

I doubt Lirenms support multiple snmp community strings to be used with a single device.
