### ISSUE TITLE
Add support for APC netbotz exp modules.

### ISSUE THREAD

**Issue by sp1rr3** [librenms/librenms#5385]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | 322bebfd7ae8a872a5c59bd5708d018a2e175951
DB Schema | 153
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.28-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

Hi, 
When i add my netbotz 200 it only lists the sensors connected directly connected to it, not the sensors connected to the expansion modules. 

Please see attached pictures:

![libre-netbotz](https://cloud.githubusercontent.com/assets/25038742/21818961/0f555eea-d76a-11e6-991f-93556a5931b1.PNG)
![netbotz](https://cloud.githubusercontent.com/assets/25038742/21818962/0f56b5ba-d76a-11e6-94f0-5219e7fa8d82.PNG)
![all-netbotz](https://cloud.githubusercontent.com/assets/25038742/21819049/5f73bb38-d76a-11e6-804c-9fff7fc5ff59.PNG)

Last picture shows all sensors connected..

I can see them when i snmpwalk it.

For ex : 
1.3.6.1.4.1.318.1.1.10.4.2.3.1.5.0.5 shown in LibreNMS (GX1:5-C3)

Not shown: 1.3.6.1.4.1.318.1.1.10.4.2.3.1.5.1.3 (GT2:3-C5)

**Comment by Rosiak** [comment]
Please provide the info asked:
./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -r -f -d -m os
snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .

**Comment by sp1rr3** [comment]
Hi,
Sorry here is the requested info.
[discovery-os.txt](https://github.com/librenms/librenms/files/697049/discovery-os.txt)
[poller-os.txt](https://github.com/librenms/librenms/files/697051/poller-os.txt)
[snmpwalk.txt](https://github.com/librenms/librenms/files/697050/snmpwalk.txt)

**Comment by sp1rr3** [comment]
Hi, any news on this? laf had any time to check this?

**Comment by laf** [comment]
Please update your install and see if this is now resolved.

**Comment by sp1rr3** [comment]
Hi, 
Sorry to inform you, no success.. same as before.

==========================================================
Component | Version
--------- | -------
LibreNMS  | e67708d1f7b110e1a9c90af49fd40fbe186c8a07
DB Schema | 190
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

**Comment by laf** [comment]
@sp1rr3 Can you test https://github.com/librenms/librenms/pull/6619 please

**Comment by sp1rr3** [comment]
@laf Yeah! success :) 👍 works perfect.
