### ISSUE TITLE
Adding more Mikrotik environment OIDs for graphing

### ISSUE THREAD

**Issue by Cheeze-It** [librenms/librenms#5387]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the 

Component | Version
--------- | -------
LibreNMS  | e95772e5b481c9bffc42922afa0b6cf909197463
DB Schema | 153
PHP       | 5.5.9-1ubuntu4.20
MySQL     | 5.5.53-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

- [ x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.

I would like to put in a request for an update to Mikrotik graphs. Currently the system tempurature (which is usually a motherboard temp) is listed as .1.3.6.1.4.1.14988.1.1.3.10.0. Can we also please get another graph for the following temps as well?

[<user>@<device>] /system health> print 
fan-mode: auto
use-fan: main
active-fan: main
cpu-overtemp-check: yes
cpu-overtemp-threshold: 100C
cpu-overtemp-startup-delay: 1m
voltage: 24V
current: 1626mA
temperature: 40C
cpu-temperature: 53C
power-consumption: 39W
fan1-speed: 0RPM
fan2-speed: 4416RPM

[<user>@<device>] /system health> print oid 
active-fan: .1.3.6.1.4.1.14988.1.1.3.9.0
voltage: .1.3.6.1.4.1.14988.1.1.3.8.0   <--- Currently implemented
temperature: .1.3.6.1.4.1.14988.1.1.3.10.0   <--- Currently implemented
processor-temperature: .1.3.6.1.4.1.14988.1.1.3.11.0   <--- Can we please implement?
current: .1.3.6.1.4.1.14988.1.1.3.13.0   <--- Can we please implement?
power-consumption: .1.3.6.1.4.1.14988.1.1.3.12.0   <--- Can we please implement?
psu1-state: .1.3.6.1.4.1.14988.1.1.3.15.0
psu2-state: .1.3.6.1.4.1.14988.1.1.3.16.0
fan1-speed: .1.3.6.1.4.1.14988.1.1.3.17.0   <--- Can we please implement?
fan2-speed: .1.3.6.1.4.1.14988.1.1.3.18.0   <--- Can we please implement?

Here is how the SNMP walk looks:

ubuntu@ubuntu-librenms:~$ snmpbulkwalk -v 2c -c stuff 10.255.255.254 1.3.6.1.4.1.14988.1.1.3
iso.3.6.1.4.1.14988.1.1.3.8.0 = INTEGER: 240
iso.3.6.1.4.1.14988.1.1.3.9.0 = STRING: "main"
iso.3.6.1.4.1.14988.1.1.3.10.0 = INTEGER: 410
iso.3.6.1.4.1.14988.1.1.3.11.0 = INTEGER: 540
iso.3.6.1.4.1.14988.1.1.3.12.0 = INTEGER: 392
iso.3.6.1.4.1.14988.1.1.3.13.0 = INTEGER: 1630
iso.3.6.1.4.1.14988.1.1.3.14.0 = INTEGER: 1200
iso.3.6.1.4.1.14988.1.1.3.17.0 = INTEGER: 4480
iso.3.6.1.4.1.14988.1.1.3.18.0 = INTEGER: 4616

I also have found the OIDs in the Mikrotik MIB as well:

mtxrHlProcessorTemperature OBJECT-TYPE
    SYNTAX Temperature
    MAX-ACCESS read-only
    STATUS current
    DESCRIPTION ""
    ::= { mtxrHealth 11 }

mtxrHlPower OBJECT-TYPE
    SYNTAX Power
    MAX-ACCESS read-only
    STATUS current
    DESCRIPTION "Watts"
    ::= { mtxrHealth 12 }

mtxrHlCurrent OBJECT-TYPE
    SYNTAX Integer32
    MAX-ACCESS read-only
    STATUS current
    DESCRIPTION "mA"
    ::= { mtxrHealth 13 }

mtxrHlFanSpeed1 OBJECT-TYPE
    SYNTAX DisplayString
    MAX-ACCESS read-only
    STATUS current
    DESCRIPTION "rpm"
    ::= { mtxrHealth 17 }

mtxrHlFanSpeed2 OBJECT-TYPE
    SYNTAX DisplayString
    MAX-ACCESS read-only
    STATUS current
    DESCRIPTION "rpm"
    ::= { mtxrHealth 18 }

**Comment by Lonecrowe** [comment]
Seconded - more Mikrotik stuff will be helpful.

**Comment by geordish** [comment]
I've created a PR to add these sensors. Could do with someone testing it.
