### ISSUE TITLE
LibreNMS & QNAP = [SNMP] DoS detected

### ISSUE THREAD

**Issue by NK74** [librenms/librenms#5389]
Who have a QNAP + LibreNMS ?

My QNAP spam my mailbox with `[SNMP] DoS detected`

![image](https://cloud.githubusercontent.com/assets/17825769/21839836/3ad703a0-d7da-11e6-8ce3-167a628e9143.png)

**Comment by laf** [comment]
Please post question on community.librenms.org or our irc channel. GitHub is for bugs/issues and feature requests.
