### ISSUE TITLE
Ghost (empty) toner discovered and alerted

### ISSUE THREAD

**Issue by tuxi56** [librenms/librenms#5391]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.

```
Component | Version
--------- | -------
LibreNMS  | e95772e5b481c9bffc42922afa0b6cf909197463
DB Schema | 153
PHP       | 7.0.14-1~dotdeb+8.1
MySQL     | 5.5.53-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
```
Hi

For the same device described at https://github.com/librenms/librenms/issues/4404, we have some "ghost" (i.e. empty) extra toner discovered (oid .1.3.6.1.4.1.367.3.2.1.2.24.1.1.5**.5** -> we have already .1 to .4 for our regular toner cartridges, no _fifth_ color added recently). I guess this could be the toner waste collector, but it's value is always at 0 (and our collector is nor empty nor full). 

Here's an extract from the `toner` table in mysql : 

```
+----------+-----------+-------------+------------+-------------------------------------+---------------+----------------+---------------+--------------------+
| toner_id | device_id | toner_index | toner_type | toner_oid                           | toner_descr   | toner_capacity | toner_current | toner_capacity_oid |
+----------+-----------+-------------+------------+-------------------------------------+---------------+----------------+---------------+--------------------+
|       27 |        15 |           1 | jetdirect  | .1.3.6.1.4.1.367.3.2.1.2.24.1.1.5.1 | Toner black   |            100 |           100 |                    |
|       28 |        15 |           2 | jetdirect  | .1.3.6.1.4.1.367.3.2.1.2.24.1.1.5.2 | Toner cyan    |            100 |            50 |                    |
|       29 |        15 |           3 | jetdirect  | .1.3.6.1.4.1.367.3.2.1.2.24.1.1.5.3 | Toner magenta |            100 |            30 |                    |
|       30 |        15 |           4 | jetdirect  | .1.3.6.1.4.1.367.3.2.1.2.24.1.1.5.4 | Toner yellow  |            100 |            30 |                    |
|       40 |        15 |           5 | jetdirect  | .1.3.6.1.4.1.367.3.2.1.2.24.1.1.5.5 |               |            100 |             0 |                    |
+----------+-----------+-------------+------------+-------------------------------------+---------------+----------------+---------------+--------------------+

```

No `toner_descr`, `toner_current` always at 0, thus manually setting it to 100 via mysql doesn't matter, it will be set to 0 at next discovery. 

Is there something I can do to clear the persistent alert generated ?

Thanks a lot :+1:

**Comment by laf** [comment]
We need the output asked for in point 3 above.

**Comment by tuxi56** [comment]
Here's the output : 

- ./discovery.php : http://pastebin.com/Q84UHp1F
- ./pooler.php : http://pastebin.com/niFnGdyd
- snmpbulkwalk : http://pastebin.com/4m4VjxLE

Interesting facts about the snmpbulkwalk : 
- the `toner_oid` `.1.3.6.1.4.1.367.3.2.1.2.24.1.1.5.5` doesn't appear
- line 747 is "Toner usagé" which is the toner waste collector
- lines 746 to 750 and 761 to 765 : the order used to report the cartridges (.1 = black, .2 = waste, .3 = cyan, .4 = magenta, .5 = yellow) is different than the order in the mysql table (.1 = black, .2 = cyan, .3 = magenta, .4 = yellow, .5 = "")
- line 761 is the correct current toner level for black
- line 762 seems to be the current toner waste container (the printer hasn't stopped working, I call the supplier tomorrow to ask for their value)
- line 763 to 765 are the correct current toner level for cyan, magenta and yellow
- lines 776 to 780 contains the English color names used to address https://github.com/librenms/librenms/issues/4404

**Comment by tuxi56** [comment]
Hi (couldn't reply earlier due to GitHub outage) 

Updated to `89a2847 - Fri Jan 13 2017 16:31:11 GMT+0100`, should I re-discover this device to see any changes ? For the moment I still see an empty toner at 0%. 

I replaced the toner waste collector today, no influence on snmpbulkwalk line 762 `.1.3.6.1.2.1.43.11.1.1.9.1.2 = INTEGER: 100`

Can I help with any extra output ?

Thank you

**Comment by laf** [comment]
repost the debug outputs after having updated.
