### ISSUE TITLE
Empty/Null ifName for some devices

### ISSUE THREAD

**Issue by pheinrichs** [librenms/librenms#5392]
Some devices (APC,PDU,etc..) return a null/empty ifName on discovery. 
Having and empty ifName causes issue with loading interface graphs from API. 

Possible solutions (Laf): 

- Override ifName with ifDescr or ifAlias if Null 
- Expose ifDescr / ifAlias to get_port_graphs function

---

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.

**Comment by Lonecrowe** [comment]
Seconded - need this for the APP in development.
