### ISSUE TITLE
AKCP Environmental monitor missing graphs and icon

### ISSUE THREAD

**Issue by eajohnson70** [librenms/librenms#5396]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.

Our AKCP sensorProbe4 is no longer displaying graphs as of an update on 2017-01-06 01:01:19

Recent events on this device:

2017-01-08 19:03:15	Device Icon changed generic => generic.png
2017-01-06 01:01:20	Sensor Deleted: temperature akcp 0 SE Temperature
2017-01-06 01:01:20	Sensor Deleted: temperature akcp 1 SW Temperature
2017-01-06 01:01:20	Sensor Deleted: temperature akcp 2 NW Temperature
2017-01-06 01:01:20	Sensor Deleted: temperature akcp 3 NE Temperature
2017-01-06 01:01:20	Sensor Deleted: humidity akcp 0 SE Humidity
2017-01-06 01:01:20	Sensor Deleted: humidity akcp 1 SW Humidity
2017-01-06 01:01:20	Sensor Deleted: humidity akcp 2 NW Humidity
2017-01-06 01:01:20	Sensor Deleted: humidity akcp 3 NE Humidity
2017-01-06 01:01:19	Device OS changed akcp => generic

Component | Version
--------- | -------
LibreNMS  | e95772e5b481c9bffc42922afa0b6cf909197463
DB Schema | 153
PHP       | 5.6.29
MySQL     | 5.5.48
RRDTool   | 1.3.8
SNMP      | NET-SNMP 5.5

**Comment by laf** [comment]
You've not provided the info in point 3.

**Comment by eajohnson70** [comment]
The link provided does not tell me what info you are requesting.



On Jan 11, 2017, at 11:27 AM, Neil Lathwood <notifications@github.com<mailto:notifications@github.com>> wrote:


You've not provided the info in point 3.

**Comment by Rosiak** [comment]
```
./discovery.php -h HOSTNAME -d -m os
./poller.php -h HOSTNAME -r -f -d -m os
snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .
```

**Comment by eajohnson70** [comment]
LibreNMS Discovery
Version info:
Commit SHA: e95772e5b481c9bffc42922afa0b6cf909197463
DB Schema: 153
PHP: 5.6.29
MySQL: 5.5.48
RRDTool: 1.3.8
SNMP: NET-SNMP 5.5
DEBUG!
SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
DB Schema already up to date.
SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE 'env-01' ORDER BY device_id DESC] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '19'] 
env-01 19 generic SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -Ovq -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0]
sensorProbe4 SP4470 161014

SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -Ovqn -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysObjectID.0]
.*.4.1.3854.1

| sensorProbe4 SP4470 161014 | .1.3.6.1.4.1.3854.1 | 
SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -Oqvn -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalDescr.1]
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: .1.3.6.1.2.1.47.1.1.1.1.2.1


SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -Oqn -m FORTINET-FORTISWITCH-MIB -M /opt/librenms/mibs/fortinet:/opt/librenms/mibs udp:HOSTNAME:161 fsSysVersion.0]
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: .1.3.6.1.4.1.12356.106.4.1.1.0


SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.39165.1.6.0]
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: SNMPv2-SMI::enterprises.39165.1.6.0


SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 SML-MIB::product-Name.0]
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: SML-MIB::product-Name.0


SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.674.10895.3000.1.2.100.1.0]
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: SNMPv2-SMI::enterprises.674.10895.3000.1.2.100.1.0


SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -Osqnv -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalMfgName.1]
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: .1.3.6.1.2.1.47.1.1.1.1.12.1



Modules status: Global+ OS  Device  
#### Load disco module os ####
SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -Ovq -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0]
sensorProbe4 SP4470 161014

SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -Ovqn -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysObjectID.0]
.*.4.1.3854.1

| sensorProbe4 SP4470 161014 | .1.3.6.1.4.1.3854.1 | 
SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -Oqvn -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalDescr.1]
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: .1.3.6.1.2.1.47.1.1.1.1.2.1


SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -Oqn -m FORTINET-FORTISWITCH-MIB -M /opt/librenms/mibs/fortinet:/opt/librenms/mibs udp:HOSTNAME:161 fsSysVersion.0]
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: .1.3.6.1.4.1.12356.106.4.1.1.0


SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.39165.1.6.0]
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: SNMPv2-SMI::enterprises.39165.1.6.0


SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 SML-MIB::product-Name.0]
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: SML-MIB::product-Name.0


SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.674.10895.3000.1.2.100.1.0]
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: SNMPv2-SMI::enterprises.674.10895.3000.1.2.100.1.0


SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -Osqnv -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalMfgName.1]
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: .1.3.6.1.2.1.47.1.1.1.1.12.1



>> Runtime for discovery module 'os': 0.4750 seconds
#### Unload disco module os ####

SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '19' AND `attrib_type` = 'poll_mib' ] 
SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='environment',`last_discovered_timetaken` ='2.086' WHERE `device_id` = '19'] 
Discovered in 2.086 seconds

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','env-01','1484152553.6015','2.117','1')] 
./discovery.php env-01 2017-01-11 11:35:55 - 1 devices discovered in 2.117 secs
SNMP: Get[16/1.75s] Walk [0/0.00s]
MySQL: Cell[3/0.00s] Row[1/0.00s] Rows[4/0.00s] Column[0/0.00s] Update[1/0.01s] Insert[1/0.00s] Delete[0/0.00s]

**Comment by eajohnson70** [comment]
LibreNMS Poller
Version info:
Commit SHA: e95772e5b481c9bffc42922afa0b6cf909197463
Commit Date: 1484076664
DB Schema: 153
PHP: 5.6.29
MySQL: 5.5.48
RRDTool: 1.3.8
SNMP: NET-SNMP 5.5
DEBUG!
Starting polling run:

SQL[SELECT * FROM `devices` WHERE `disabled` = 0 AND `hostname` = 'env-01' ORDER BY `device_id` ASC] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '19'] 
Hostname: env-01
Device ID: 19
OS: generic

SQL[INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('5','5','0','0.80','2.25','1.12','19',NOW())] 
SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 sysObjectID.0]
SNMPv2-SMI::enterprises.3854.1

SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -OQnUst -m SNMPv2-MIB:HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 sysUpTime.0 sysLocation.0 sysContact.0 sysName.0 sysObjectID.0]
sysUpTime.0 = 820045554
sysLocation.0 = REC
sysContact.0 = something@something.com
sysName.0 = env-01
sysObjectID.0 = enterprises.3854.1

SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -OvQ -m SNMPv2-MIB:HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 sysDescr.0]
sensorProbe4 SP4470 161014

SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -OQnUst -m HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 snmpEngineTime.0 hrSystemUptime.0]
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: snmpEngineTime.0


Using SNMP Agent Uptime (8200455s)
  RRD[update /opt/librenms/rrd/env-01/uptime.rrd N:8200455]
[RRD Disabled]Uptime: 94 days, 21h 54m 15s
Modules status: Global+ OS  Device  
#### Load poller module os ####
Generic :(
Hardware: 
Version: 
Features: 
Serial: 

>> Runtime for poller module 'os': 0.0002 seconds
#### Unload poller module os ####

RRD[update /opt/librenms/rrd/env-01/poller-perf-os.rrd N:0.00018882751464844]
[RRD Disabled]### Start Device Groups ###
SQL[SELECT * FROM device_groups ORDER BY name] 
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE  devices.device_id='19' AND (devices.type = "Server" && devices.os = "Linux" ) LIMIT 1] 
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE  devices.device_id='19' AND (devices.type = "Network") LIMIT 1] 
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE  devices.device_id='19' AND (devices.type = "Power") LIMIT 1] 
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE  devices.device_id='19' AND (devices.type = "Server") LIMIT 1] 
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE  devices.device_id='19' AND (devices.type = "Server" && devices.os = "Windows" ) LIMIT 1] 
SQL[SELECT `device_group_id` FROM `device_group_device` WHERE `device_id`='19'] 
Groups Added: 
Groups Removed: 
### End Device Groups ###
RRD[update /opt/librenms/rrd/env-01/poller-perf.rrd N:0.893]
[RRD Disabled]RRD[update /opt/librenms/rrd/env-01/ping-perf.rrd N:1.12]
[RRD Disabled]Polled in 0.893 seconds
Updating env-01
SQL[UPDATE `devices` set `uptime` ='8200455',`last_ping` =NOW(),`last_ping_timetaken` ='1.12',`last_polled` =NOW(),`last_polled_timetaken` ='0.893' WHERE `device_id` = '19'] 
UPDATED!
#### Start Alerts ####
SQL[SELECT `device_group_id` FROM `device_group_device` WHERE `device_id`='19'] 
SQL[SELECT alert_schedule.schedule_id FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '19' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1] 
SQL[SELECT `device_group_id` FROM `device_group_device` WHERE `device_id`='19'] 
SQL[SELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '19' ) || alert_map.target = '19'  )] 
Rule #3 (BGP Session down): 
SQL[SELECT state FROM alerts WHERE rule_id = '3' && device_id = '19' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM bgpPeers,devices WHERE (( devices.device_id = bgpPeers.device_id ) && bgpPeers.device_id = '19') && (bgpPeers.bgpPeerState != "established"  &&   (  ( devices.status = 1  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  )  )  = "1")] 
Status: NOCHG
Rule #4 (BGP Session established): 
SQL[SELECT state FROM alerts WHERE rule_id = '4' && device_id = '19' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM bgpPeers WHERE (bgpPeers.device_id = '19') && (bgpPeers.bgpPeerFsmEstablishedTime < "300"  &&  bgpPeers.bgpPeerState = "established")] 
Status: NOCHG
Rule #8 (Sensor under limit): 
SQL[SELECT state FROM alerts WHERE rule_id = '8' && device_id = '19' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM sensors WHERE (sensors.device_id = '19') && (sensors.sensor_current < sensors.sensor_limit_low  &&  sensors.sensor_alert = "1"  )] 
Status: NOCHG
Rule #19 (Power Devices up/down): 
SQL[SELECT state FROM alerts WHERE rule_id = '19' && device_id = '19' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices WHERE (devices.device_id = '19') && ( (  ( devices.status = 0  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  )  )  = "1"    &&  devices.type = "Power"     )] 
Status: NOCHG
Rule #20 (Network Devices up/down): 
SQL[SELECT state FROM alerts WHERE rule_id = '20' && device_id = '19' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices WHERE (devices.device_id = '19') && ( (  ( devices.status = 0  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  )  )  = "1"  &&  devices.type = "Network"   )] 
Status: NOCHG
Rule #21 (Servers up/down): 
SQL[SELECT state FROM alerts WHERE rule_id = '21' && device_id = '19' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices WHERE (devices.device_id = '19') && ( (  ( devices.status = 0  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  )  )  = "1"  &&  devices.type = "Server"      &&  devices.os NOT REGEXP "Print"   )] 
Status: NOCHG
Rule #22 (Power Device Rebooted): 
SQL[SELECT state FROM alerts WHERE rule_id = '22' && device_id = '19' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices WHERE (devices.device_id = '19') && ( (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  = "1"  &&  devices.type = "Power"    &&  devices.uptime < "300" )] 
Status: NOCHG
Rule #23 (Network Device Rebooted): 
SQL[SELECT state FROM alerts WHERE rule_id = '23' && device_id = '19' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices WHERE (devices.device_id = '19') && ( (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  = "1"  &&  devices.type = "Network"      &&  devices.uptime < "300" )] 
Status: NOCHG
Rule #24 (Server Rebooted): 
SQL[SELECT state FROM alerts WHERE rule_id = '24' && device_id = '19' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices WHERE (devices.device_id = '19') && ( (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  = "1"  &&  devices.type = "Server"    &&  devices.uptime < "300"    &&  devices.os NOT REGEXP "Print"   )] 
Status: NOCHG
#### End Alerts ####
SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','env-01','1484152858.1697','0.934','1','librenms.prp.lcl\n')] 
./poller.php env-01 2017-01-11 11:40:59 - 1 devices polled in 0.934 secs
SNMP: Get[4/0.08s] Walk [0/0.00s]
MySQL: Cell[8/0.00s] Row[9/0.00s] Rows[15/0.01s] Column[3/0.00s] Update[1/0.00s] Insert[2/0.01s] Delete[0/0.00s]

**Comment by eajohnson70** [comment]
snmpbulkwalk: Cannot send V2 PDU on V1 session

**Comment by eajohnson70** [comment]
Looks like this happened before with an update and was remedied days later:

Eventlog entries
2017-01-12 05:29:44	System	Device type changed environment => server
2017-01-08 19:03:15	System	Device Icon changed generic => generic.png
2017-01-06 01:01:20	System	Sensor Deleted: temperature akcp 0 SE Temperature
2017-01-06 01:01:20	System	Sensor Deleted: temperature akcp 1 SW Temperature
2017-01-06 01:01:20	System	Sensor Deleted: temperature akcp 2 NW Temperature
2017-01-06 01:01:20	System	Sensor Deleted: temperature akcp 3 NE Temperature
2017-01-06 01:01:20	System	Sensor Deleted: humidity akcp 0 SE Humidity
2017-01-06 01:01:20	System	Sensor Deleted: humidity akcp 1 SW Humidity
2017-01-06 01:01:20	System	Sensor Deleted: humidity akcp 2 NW Humidity
2017-01-06 01:01:20	System	Sensor Deleted: humidity akcp 3 NE Humidity
2017-01-06 01:01:19	System	Device OS changed akcp => generic
2017-01-06 01:01:19	System	Device Icon changed akcp => generic
2017-01-01 13:01:45	System	Sensor Added: humidity akcp 1 SW Humidity
2017-01-01 13:01:45	System	Sensor Added: humidity akcp 2 NW Humidity
2017-01-01 13:01:45	System	Sensor Added: humidity akcp 3 NE Humidity
2017-01-01 13:01:44	System	Sensor Added: temperature akcp 2 NW Temperature
2017-01-01 13:01:44	System	Sensor Added: temperature akcp 3 NE Temperature
2017-01-01 13:01:44	System	Sensor Added: humidity akcp 0 SE Humidity
2017-01-01 13:01:43	System	Sensor Added: temperature akcp 0 SE Temperature
2017-01-01 13:01:43	System	Sensor Added: temperature akcp 1 SW Temperature
2017-01-01 13:01:42	System	Device Icon changed generic => akcp
2016-12-29 00:55:55	System	Sensor Deleted: temperature akcp 0 SE Temperature
2016-12-29 00:55:55	System	Sensor Deleted: temperature akcp 1 SW Temperature
2016-12-29 00:55:55	System	Sensor Deleted: temperature akcp 2 NW Temperature
2016-12-29 00:55:55	System	Sensor Deleted: temperature akcp 3 NE Temperature
2016-12-29 00:55:55	System	Sensor Deleted: humidity akcp 0 SE Humidity
2016-12-29 00:55:55	System	Sensor Deleted: humidity akcp 1 SW Humidity
2016-12-29 00:55:55	System	Sensor Deleted: humidity akcp 2 NW Humidity
2016-12-29 00:55:55	System	Sensor Deleted: humidity akcp 3 NE Humidity
2016-12-29 00:55:54	System	Device OS changed akcp => generic
2016-12-29 00:55:54	System	Device Icon changed akcp => generic

**Comment by eajohnson70** [comment]
Every time discovery.php runs the device type changes from environment to server as well.

**Comment by eajohnson70** [comment]
Applied patch per @laf on IRC and all's good now:

diff --git a/includes/definitions/akcp.yaml b/includes/definitions/akcp.yaml
index 52f86e3..3a3c5a1 100644
--- a/includes/definitions/akcp.yaml
+++ b/includes/definitions/akcp.yaml
@@ -6,3 +6,4 @@ over:
 discovery:
     - sysDescr:
         - SensorProbe
+        - sensorProbe4
