### ISSUE TITLE
Unifi Switches reporting incorrectly

### ISSUE THREAD

**Issue by TyShawn76** [librenms/librenms#5404]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
==========================================================
Component | Version
--------- | -------
LibreNMS  | 8156fd547f8fddc3e1715ce2d7f40c2c46649068
DB Schema | 153
PHP       | 5.6.29-0+deb8u1
MySQL     | 5.5.53-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================
After today's update to fix an issue with Gen 1 and 2 UAP's not showing users and radio information. My Unifi switches are now reporting as Quanta Linux devices. Prior to this update those devices displayed correctly.

![screen shot 2017-01-11 at 8 54 37 pm](https://cloud.githubusercontent.com/assets/21324034/21874044/79e4ccf6-d840-11e6-965c-d80fa8be482d.jpg)

**Comment by laf** [comment]
Can you provide the output of:

`./discovery.php -h HOSTNAME -d -m os`
`./poller.php -h HOSTNAME -d -m os -r -f`

**Comment by TyShawn76** [comment]
Discovery
http://pastebin.com/3jNbikLA

Poller
http://pastebin.com/EbRspF0c

**Comment by murrant** [comment]
Was it detected as "EdgeSwitch" os before?

**Comment by murrant** [comment]
The code indicates it was, so I've sent a fix.

**Comment by TyShawn76** [comment]
Verified another bug squashed.
