### ISSUE TITLE
Cannot discover VRF's on Cisco VSS 6500 VE and Cisco Nexus 9500

### ISSUE THREAD

**Issue by DonovanEsterhuizen** [librenms/librenms#5406]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
_

librenms@librenms:~$ ./validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | c5a3d82040083e2f366da29958ec8a6b62ba7bbb
DB Schema | 153
PHP       | 7.0.8-0ubuntu0.16.04.1
MySQL     | 10.0.25-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

[OK]    Database connection successful

Im not seeing the vrf tab under device->routing for out Cisco 6500 VSS and Cisco Nexus

I have the following enabled

 Enable VRF Globally
$config['enable_vrfs']                                    = 1; # Enable VRFs
$config['discovery_modules']['cisco-vrf-lite']            = 1;
$config['discovery_modules']['cisco-vrf']                 = 1;

let me know what other information is required

**Comment by laf** [comment]
We need the info in point 3 above.

**Comment by DonovanEsterhuizen** [comment]
Hi

As requested 

[CiscoNexus9504.txt](https://github.com/librenms/librenms/files/703637/CiscoNexus9504.txt)

[vss.txt](https://github.com/librenms/librenms/files/703679/vss.txt)

**Comment by laf** [comment]
Neither of those devices respond back on vrf:

```
#### Load disco module cisco-vrf ####
SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Osqn -m MPLS-L3VPN-STD-MIB -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 mplsL3VpnVrfRD]
.*.*.*.1.4 No Such Object available on this agent at this OID

SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Osqn -m MPLS-VPN-MIB -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 mplsVpnVrfRouteDistinguisher]
.*.*.2.1.3 No Such Object available on this agent at this OID


[DEBUG]
Using MPLS-VPN-MIB
[/DEBUG]

[DEBUG OIDS]

[/DEBUG]
SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Osqn -m MPLS-VPN-MIB -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.3.118.1.2.2.1.2]
.*.*.2.1.2 No Such Object available on this agent at this OID

SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Osqn -m MPLS-VPN-MIB -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.3.118.1.2.1.1.2]
.*.*.1.1.2 No Such Object available on this agent at this OID



SQL[SELECT * FROM ports WHERE device_id = '5'] 
SQL[SELECT * FROM vrfs WHERE device_id = '5'] 


>> Runtime for discovery module 'cisco-vrf': 0.2110 seconds
#### Unload disco module cisco-vrf ####
```

Do you run contexts? If so we don't currently support this #5386

**Comment by DonovanEsterhuizen** [comment]
thanks will have a look.

Appreciate

You can close for now as we run contexts

**Comment by laf** [comment]
You can add them as separate devices as a workaround for now.

**Comment by DonovanEsterhuizen** [comment]
let me try that

**Comment by DonovanEsterhuizen** [comment]
Hang on im bit confused.

If we dont use contexts should Librenms be able to discover the vrf's configured on the device?

**Comment by DonovanEsterhuizen** [comment]
I have removed the contexts now and I still can get vrf information.

I have a standard snmp config as per doc on libre site.

Should I be able to pull the vrf configured on the device now?

**Comment by laf** [comment]
Yes, re-post the info from earlier.

**Comment by DonovanEsterhuizen** [comment]
Are you referring the discovery.php info?

**Comment by DonovanEsterhuizen** [comment]
[vss.txt](https://github.com/librenms/librenms/files/704339/vss.txt)

**Comment by DonovanEsterhuizen** [comment]
Here is my config

snmp-server community communitystring RO 35
snmp-server enable traps snmp authentication linkdown linkup coldstart warmstart
snmp-server enable traps chassis
snmp-server enable traps module
snmp-server enable traps transceiver all
snmp-server enable traps ds1
snmp-server enable traps call-home message-send-fail server-fail
snmp-server enable traps eigrp
snmp-server enable traps casa
snmp-server enable traps tty
snmp-server enable traps ospf state-change
snmp-server enable traps ospf errors
snmp-server enable traps ospf retransmit
snmp-server enable traps ospf lsa
snmp-server enable traps ospf cisco-specific state-change nssa-trans-change
snmp-server enable traps ospf cisco-specific state-change shamlink interface-old
snmp-server enable traps ospf cisco-specific state-change shamlink neighbor
snmp-server enable traps ospf cisco-specific errors
snmp-server enable traps ospf cisco-specific retransmit
snmp-server enable traps ospf cisco-specific lsa
snmp-server enable traps atm subif
snmp-server enable traps bgp
snmp-server enable traps bulkstat collection transfer
snmp-server enable traps config-copy
snmp-server enable traps config
snmp-server enable traps config-ctid
snmp-server enable traps dhcp-snooping bindings
snmp-server enable traps event-manager
snmp-server enable traps frame-relay
snmp-server enable traps frame-relay subif
snmp-server enable traps hsrp
snmp-server enable traps ipmulticast
snmp-server enable traps MAC-Notification change move threshold
snmp-server enable traps msdp
snmp-server enable traps pim neighbor-change rp-mapping-change invalid-pim-message
snmp-server enable traps rf
snmp-server enable traps rtr
snmp-server enable traps slb real virtual csrp
snmp-server enable traps bridge newroot topologychange
snmp-server enable traps stpx inconsistency root-inconsistency loop-inconsistency
snmp-server enable traps syslog
snmp-server enable traps rep
snmp-server enable traps auth-framework sec-violation
snmp-server enable traps memory bufferpeak
snmp-server enable traps flex-links status
snmp-server enable traps csg agent quota-server database
snmp-server enable traps sonet
snmp-server enable traps dial
snmp-server enable traps dot1x auth-fail-vlan guest-vlan no-auth-fail-vlan no-guest-vlan
snmp-server enable traps ethernet cfm cc mep-up mep-down cross-connect loop config
snmp-server enable traps ethernet cfm crosscheck mep-missing mep-unknown service-up
snmp-server enable traps energywise
snmp-server enable traps fru-ctrl ps-output-change status
snmp-server enable traps entity
snmp-server enable traps l2tc threshold sys-threshold
snmp-server enable traps module-auto-shutdown sys-action auto-shutdown
snmp-server enable traps cpu threshold
snmp-server enable traps rsvp
snmp-server enable traps srp
snmp-server enable traps udld link-fail-rpt
snmp-server enable traps udld status-change
snmp-server enable traps vtp
snmp-server enable traps vlancreate
snmp-server enable traps vlandelete
snmp-server enable traps flash insertion removal
snmp-server enable traps c6kxbar intbus-crcexcd intbus-crcrcvrd swbus tm-channel tm-swbus
snmp-server enable traps entity-diag boot-up-fail hm-test-recover hm-thresh-reached scheduled-test-fail
snmp-server enable traps envmon fan shutdown supply temperature status
snmp-server enable traps port-security
snmp-server enable traps vswitch vsl
snmp-server enable traps alarms informational
snmp-server enable traps vlan-mac-limit
snmp-server enable traps errdisable
snmp-server host 10.1.162.68 communitystring
snmp-server host 10.1.5.17 communitystring cpu
snmp-server host 10.1.5.80 communitystring
snmp-server host 10.5.33.202 communitystring
snmp-server host 172.23.112.97 communitystring

**Comment by DonovanEsterhuizen** [comment]
This is weird now, I have tested on another device and I can discover the VRF....

I dont understand why the vrfs wont be discovered on other devices.

I suppose you can close the issue now unless you have any idea's

Thanks for your help appreciate

**Comment by laf** [comment]
vrf lite needs: `$config['enable_vrf_lite_cisco'] = true;`

**Comment by DonovanEsterhuizen** [comment]
I dont have that let me check

**Comment by DonovanEsterhuizen** [comment]
doesnt make a difference if i add that.

will have to investigate more routers 

you can close this

**Comment by laf** [comment]
If you provide the output of `./discovery.php -h HOSTNAME -d -m cisco-vrf-lite,cisco-vrf`

For both devices.

**Comment by DonovanEsterhuizen** [comment]
librenms@librenms:~$ 
librenms@librenms:~$ 
librenms@librenms:~$ 
librenms@librenms:~$ 
librenms@librenms:~$ ./discovery.php -h 10.5.47.250 -d -m cisco-vrf-lite,cisco-vrf
LibreNMS Discovery
Version info:
Commit SHA: e95772e5b481c9bffc42922afa0b6cf909197463
DB Schema: 153
PHP: 7.0.8-0ubuntu0.16.04.3
MySQL: 10.0.28-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP 5.7.3
DEBUG!
SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
DB Schema already up to date.
SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE '10.5.47.250' ORDER BY device_id DESC] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '10'] 
10.5.47.250 10 ios SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '10' AND `attrib_type` = 'poll_mib' ] 

Modules status: Global+ OS+ Device  
#### Load disco module cisco-vrf-lite ####
SQL[SELECT * FROM vrf_lite_cisco WHERE device_id = '10' ] 

>> Runtime for discovery module 'cisco-vrf-lite': 0.0020 seconds
#### Unload disco module cisco-vrf-lite ####

Modules status: Global+ OS+ Device  
#### Load disco module cisco-vrf ####
SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Osqn -m MPLS-L3VPN-STD-MIB -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 mplsL3VpnVrfRD]
.*.*.*.1.4 No Such Object available on this agent at this OID

SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Osqn -m MPLS-VPN-MIB -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 mplsVpnVrfRouteDistinguisher]
.*.*.2.1.3 No Such Object available on this agent at this OID


[DEBUG]
Using MPLS-VPN-MIB
[/DEBUG]

[DEBUG OIDS]

[/DEBUG]
SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Osqn -m MPLS-VPN-MIB -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.3.118.1.2.2.1.2]
.*.*.2.1.2 No Such Object available on this agent at this OID

SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Osqn -m MPLS-VPN-MIB -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.3.118.1.2.1.1.2]
.*.*.1.1.2 No Such Object available on this agent at this OID



SQL[SELECT * FROM ports WHERE device_id = '10'] 
SQL[SELECT * FROM vrfs WHERE device_id = '10'] 


>> Runtime for discovery module 'cisco-vrf': 0.1620 seconds
#### Unload disco module cisco-vrf ####

SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '10' AND `attrib_type` = 'poll_mib' ] 
SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='network',`last_discovered_timetaken` ='0.173' WHERE `device_id` = '10'] 
Discovered in 0.173 seconds

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','10.5.47.250','1484319371.1462','0.217','1')] 
./discovery.php 10.5.47.250 2017-01-13 14:56:11 - 1 devices discovered in 0.217 secs
SNMP: Get[0/0.00s] Walk [4/0.14s]
MySQL: Cell[3/0.00s] Row[2/0.00s] Rows[7/0.02s] Column[0/0.00s] Update[1/0.00s] Insert[1/0.01s] Delete[0/0.00s]
librenms@librenms:~$ ./discovery.php -h 10.252.252.1 -d -m cisco-vrf-lite,cisco-vrf
LibreNMS Discovery
Version info:
Commit SHA: e95772e5b481c9bffc42922afa0b6cf909197463
DB Schema: 153
PHP: 7.0.8-0ubuntu0.16.04.3
MySQL: 10.0.28-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP 5.7.3
DEBUG!
SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
DB Schema already up to date.
SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE '10.252.252.1' ORDER BY device_id DESC] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '5'] 
10.252.252.1 5 nxos 
Modules status: Global+ OS+ Device  
#### Load disco module cisco-vrf-lite ####
SQL[SELECT * FROM vrf_lite_cisco WHERE device_id = '5' ] 

>> Runtime for discovery module 'cisco-vrf-lite': 0.0040 seconds
#### Unload disco module cisco-vrf-lite ####

Modules status: Global+ OS+ Device  
#### Load disco module cisco-vrf ####
SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Osqn -m MPLS-L3VPN-STD-MIB -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 mplsL3VpnVrfRD]
.*.*.*.1.4 No Such Object available on this agent at this OID

SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Osqn -m MPLS-VPN-MIB -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 mplsVpnVrfRouteDistinguisher]
.*.*.2.1.3 No Such Object available on this agent at this OID


[DEBUG]
Using MPLS-VPN-MIB
[/DEBUG]

[DEBUG OIDS]

[/DEBUG]
SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Osqn -m MPLS-VPN-MIB -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.3.118.1.2.2.1.2]
.*.*.2.1.2 No Such Object available on this agent at this OID

SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Osqn -m MPLS-VPN-MIB -M /opt/librenms/mibs/cisco:/opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.3.118.1.2.1.1.2]
.*.*.1.1.2 No Such Object available on this agent at this OID



SQL[SELECT * FROM ports WHERE device_id = '5'] 
SQL[SELECT * FROM vrfs WHERE device_id = '5'] 


>> Runtime for discovery module 'cisco-vrf': 0.1170 seconds
#### Unload disco module cisco-vrf ####

SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '5' AND `attrib_type` = 'poll_mib' ] 
SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='network',`last_discovered_timetaken` ='0.129' WHERE `device_id` = '5'] 
Discovered in 0.129 seconds

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','10.252.252.1','1484319382.2309','0.172','1')] 
./discovery.php 10.252.252.1 2017-01-13 14:56:22 - 1 devices discovered in 0.172 secs
SNMP: Get[0/0.00s] Walk [4/0.11s]
MySQL: Cell[3/0.00s] Row[1/0.00s] Rows[7/0.01s] Column[0/0.00s] Update[1/0.01s] Insert[1/0.00s] Delete[0/0.00s]
librenms@librenms:~$
