### ISSUE TITLE
device type not being set for any new devices

### ISSUE THREAD

**Issue by sysmonk** [librenms/librenms#5412]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.

==========================================================
Component | Version
--------- | -------
LibreNMS  | 78cdca022290f53fce4c2d541d11ecbc2e4c1bde
DB Schema | 153
PHP       | 7.0.14-1~dotdeb+8.1
MySQL     | 10.0.28-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

Librenms stopped setting the device type for new devices added recently. This sounds related to https://github.com/librenms/librenms/blob/master/includes/common.php#L1529 - it's sets the type (and makes any later checks not see that it changed), but does not update the db.

**Comment by laf** [comment]
The type setting isnt done there. It's done here. https://github.com/librenms/librenms/blob/master/includes/discovery/os.inc.php

Please post output onto pastebin for ./discovery.php -h HOSTNAME -d -m os

**Comment by laf** [comment]
Actually don't need this, confirmed, fix being done.
