### ISSUE TITLE
Feature Request under Ports -> Submenu for the Total Graphs

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#5417]
Hi !

We use a lot of Total Graph Ports !

Submenus would be nessacery !

thanks 

kristoferus75

**Comment by laf** [comment]
Can you explain more of what you are after?

**Comment by kristoferus75** [comment]
Total Graphs Port s look like this :
![picture device independent bitmap 1](https://cloud.githubusercontent.com/assets/18415083/21975899/90db9e84-dbcf-11e6-9bbe-ab0abfd902c5.jpg)

Submenu under Port Menu would be nessacery like this:

![picture device independent bitmap 2](https://cloud.githubusercontent.com/assets/18415083/21975931/adee1bbe-dbcf-11e6-9b37-ee8f804dd140.jpg)

**Comment by laf** [comment]
How are we supposed to organise those or do you just mean you would like to see it like the Device Groups is layed out?

**Comment by kristoferus75** [comment]
for example:

If you look to the first picture you see alot of NNI .... ports ->
Each NNI port is directly under ports -> but Id like to have one Menu Entry NNI under Ports and under NNI  there should be the the other NNI-XX Ports (NNI-TEL & NNI-Energie etc ...)

ok ?

**Comment by laf** [comment]
Not something I'd say is worth doing.

**Comment by kristoferus75** [comment]
The problem is that more and more ports are added and that it is not really
clear!
Not really organized :-(

I want to define under ports menu the submenu entries  and then i want to
assign the interface  tags to the submenus

Is my opinion

2017-01-16 18:48 GMT+01:00 Neil Lathwood <notifications@github.com>:

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-under-ports-submenu-for-the-total-graphs/781
