### ISSUE TITLE
total graph legend with description of the interfaces

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#5418]
Hi !

Currently under total graph Legend we see a lot subiterfaces names !

Is it possible to see not the subinterfece names but rather the description of the subinterface or of the port in the legend under the graph ?

Because with a lot of interfaces is it not really clear with the overview !

Thanks

kind regrads

kristoferus75

**Comment by murrant** [comment]
You need to let us know of the device and an example.  A screenshot would be good.  Thanks.

**Comment by kristoferus75** [comment]
Hi ! Here a screenshot ! 
![graph_example](https://cloud.githubusercontent.com/assets/18415083/21954296/1a0af95e-da4d-11e6-8316-aa7c245ffea7.png)

instead of interface name the description of the interface or in case od the Service Instance Interface name the description from the SI Interface 

kind regrads

kristoferus75

**Comment by laf** [comment]
Duplicate of #3319
