### ISSUE TITLE
Procurve switch not detected.

### ISSUE THREAD

**Issue by basn** [librenms/librenms#5422]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | d5296319fbadd41dc5a82cbe4bbc6e3fa82b1cb7
DB Schema | 154
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.28-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

I add the discover for procurve switch that does not get detected.
Everything except the os seems to work all sensors etc seems to be added.
[discover.txt](https://github.com/librenms/librenms/files/704549/discover.txt)

**Comment by laf** [comment]
@basn please provide all the info from point #3 above please :)

**Comment by basn** [comment]
adding what @laf  wanted :)

[hp.txt](https://github.com/librenms/librenms/files/704584/hp.txt)
[poller.txt](https://github.com/librenms/librenms/files/704582/poller.txt)
[discover2.txt](https://github.com/librenms/librenms/files/704583/discover2.txt)

hp is snmpbulkwalk
