### ISSUE TITLE
APC UPS support seems to have been removed?

### ISSUE THREAD

**Issue by rbax82** [librenms/librenms#5428]
APC UPS support seems to have been removed as an application from the webUI. Could it please be put back in?

https://github.com/librenms/librenms-agent/blob/master/snmp/ups-apcups.sh is there and yet the application doesn't appear to be an option in the librenms webUI.

DO NOT DELETE THIS INFORMATION.

Please read this information carefully.
GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z.
You can use our irc channel ##librenms on freenode to ask questions or our community site.

 Is your install up to date? Updating your install
Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
 Please include all of the information between the ==================================== section of ./validate.php.
 If you would like us to add a new device or your device is listed as Generic then please provide the information asked for here
 Please provide as much detail as possible.

**Comment by laf** [comment]
I don't think it's ever been in the list to select from:

https://github.com/librenms/librenms/commits/master/html/pages/device/edit/apps.inc.php

Seems to indicate it's not been removed in the last 12 months.

**Comment by Compizfox** [comment]
@laf That's correct. As explained in #4818, there is an agent script for it. [The documentation](http://docs.librenms.org/Extensions/Applications/#ups-apcups) instructs you to enable the `ups-apcups` application in the web interface, but it is not there.

**Comment by Compizfox** [comment]
Thanks, seems to work (over SNMP too)!
