### ISSUE TITLE
cisco-pw crashs stack of 3750X

### ISSUE THREAD

**Issue by jehrhardt-de** [librenms/librenms#5430]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.

./validate.php 
==========================================================
Component | Version
--------- | -------
LibreNMS  | 370e368ffeaf1ed7b88133a388ebbf66f5e75d5f
DB Schema | 154
PHP       | 7.0.14
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

Hardware 	Catalyst 3750X (WS-C3750X-48T-L)
Operating System 	Cisco IOS 15.2(4)E2 (UNIVERSALK9) 

Crashinfo on the switch contains many entries like
Jan 14 08:07:08.332 Berlin: %SYS-2-INTSCHED: 'may_suspend' at level 4  -Process= "SNMP ENGINE", ipl= 4, pid= 478

We have a stack of two Cisco 3750X. If the modul cisco-pw is enabled, at every discovery the stack master crashs.

Debug output:
 
[discovery-3750X.txt](https://github.com/librenms/librenms/files/705838/discovery-3750X.txt)

**Comment by laf** [comment]
All we are doing is running snmp queries. We run lots of C37xx series devices stacked with varying software trains and don't see this (not the exact version you mention).

I think this is a question for Cisco TAC more than us - for now just disable the module.

**Comment by Rosiak** [comment]
I agree with laf; furthermore I do believe several bug reports exists concerning this issue.
