### ISSUE TITLE
Component Status Log unused

### ISSUE THREAD

**Issue by murrant** [librenms/librenms#5431]
@adaniels21487 The component code saves a message to the component_statuslog table but it specifies a message column and no message column exists.

Also, the log does not seem to be displayed anywhere.

We are trying to clean up the sql queries in LibreNMS.  Do you want to fix this code/SQL up or should it be removed?

**Comment by adaniels21487** [comment]
Hi @murrant 
Thanks for catching this. I will fix the sql queries in the component code.
