### ISSUE TITLE
NWA3560-N & NWA3160-N is detected as firewall should be wireless.

### ISSUE THREAD

**Issue by msjohansen** [librenms/librenms#5432]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date?
- [x] Please include all of the information of `./validate.php`.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.

[discovery.txt](https://github.com/librenms/librenms/files/706002/discovery.txt)
[poller.txt](https://github.com/librenms/librenms/files/706000/poller.txt)
[snmpbulkwalk.txt](https://github.com/librenms/librenms/files/706001/snmpbulkwalk.txt)

**Comment by Rosiak** [comment]
Seems like this is detected as a zywall rather than zyxelnwa due to the sysObjectID.
