### ISSUE TITLE
Vote for new generic OS icon

### ISSUE THREAD

**Issue by murrant** [librenms/librenms#5434]
**Submit icons as comments and vote on them by adding a thumbs up reaction.**

**PLEASE NO OTHER COMMENTS!**  If you would like to discuss something please use the community or irc :)

Icons should be svg and not copyrighted or at least provided under an acceptable license.  Export to a height of 96 pixels for voting here.

You can use any colors you want.

**Comment by murrant** [comment]
![librenms cube faded-o svg](https://cloud.githubusercontent.com/assets/39462/21956015/6021da36-da3c-11e6-885a-89b30a89417e.png)

**Comment by murrant** [comment]
![librenms cube faded-o svg](https://cloud.githubusercontent.com/assets/39462/21956026/9253afe8-da3c-11e6-8111-87b72ae8b927.png)

**Comment by murrant** [comment]
![librenms logo square faded-p svg](https://cloud.githubusercontent.com/assets/39462/21956034/bbdba6ae-da3c-11e6-80b7-1229887a7d2f.png)

**Comment by InsaneSplash** [comment]
![data-mind-map](https://cloud.githubusercontent.com/assets/16985649/21957277/b76e4856-da9b-11e6-9791-b422858143b7.png)

**Comment by InsaneSplash** [comment]
![data-mind-map](https://cloud.githubusercontent.com/assets/16985649/21957285/d99a80c0-da9b-11e6-9a7a-c57f4d86d719.png)

**Comment by InsaneSplash** [comment]
![data-database](https://cloud.githubusercontent.com/assets/16985649/21957310/56382dc6-da9c-11e6-9524-21a25159a025.png)

**Comment by InsaneSplash** [comment]
![editing-vector](https://cloud.githubusercontent.com/assets/16985649/21957345/ed643c8a-da9c-11e6-9c63-38176e683b83.png)

**Comment by laf** [comment]
http://s2.aconvert.com/convert/p3r68-cdx67/eg7xc-lesei.svg

![image](https://cloud.githubusercontent.com/assets/3941142/21967036/3a95352e-db77-11e6-8cea-dd13a275658f.png)

Not sure what the score is with all the odd colours you guys are suggesting :)

**Comment by InsaneSplash** [comment]
:) I took mine from Murray's :) (faded)... I can re-do mine with the above colours?

**Comment by murrant** [comment]
![librenms cube](https://cloud.githubusercontent.com/assets/39462/21985859/5b8a64d4-dbc2-11e6-9259-564b5ab85c9c.png)

**Comment by InsaneSplash** [comment]
![data-mind-map-2](https://cloud.githubusercontent.com/assets/16985649/22080428/42943ea2-ddc8-11e6-850c-9a8531966d1e.png)

**Comment by InsaneSplash** [comment]
![editing-vector-2](https://cloud.githubusercontent.com/assets/16985649/22080493/7ab16b66-ddc8-11e6-9ee3-1bf3852ae01a.png)

**Comment by InsaneSplash** [comment]
![data-database-2](https://cloud.githubusercontent.com/assets/16985649/22080555/adb3845e-ddc8-11e6-8833-277c0121808f.png)

**Comment by InsaneSplash** [comment]
![cube2](https://cloud.githubusercontent.com/assets/16985649/22080703/32ddf358-ddc9-11e6-9f7e-5785d3295070.png)

**Comment by InsaneSplash** [comment]
![editing-vector](https://cloud.githubusercontent.com/assets/16985649/22345419/ae8bec40-e408-11e6-8669-38bfec60a384.png)

**Comment by InsaneSplash** [comment]
![data-database](https://cloud.githubusercontent.com/assets/16985649/22345427/b77eec62-e408-11e6-941b-f14bbea2402d.png)
