### ISSUE TITLE
OpenWRT (Inteno DG400A) detected as Generic Device, instead of Linux

### ISSUE THREAD

**Issue by E-t-z** [librenms/librenms#5437]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.

                                                                            
Component | Version                                                                                                                             
--------- | -------                                                                                                                             
LibreNMS  |                                                                                                                                     
DB Schema | 152                                                                                                                                 
PHP       | 7.0.14-2+deb.sury.org~xenial+1                                                                                                      
MySQL     | 5.5.53-MariaDB                                                                                                                      
RRDTool   | 1.5.5                                                                                                                               
SNMP      | NET-SNMP 5.7.3                                                                                                                      

http://etz.planet.ee/polleros.txt
http://etz.planet.ee/discos.txt
http://etz.planet.ee/bulkwalkos.txt

Suddenly (after deleting and re-adding) this device is detected as Generic Device instead of Linux and is missing platform information as well. 
Rediscovery via GUI does not help.

**Comment by laf** [comment]
I'm pretty certain that openwrt is only detected when using the distro script for librenms-agent.

**Comment by E-t-z** [comment]
Hmm...are you sure?

So far (pre 1.23) it worked just fine and was listed as "generic linux"

https://s30.postimg.org/n7ensiclt/Capture.png

Both are OpenWRT based devices in that picture...and before I decided to remove that device from LibreNMS and re-add it back it was shown as Linux & armv7 as well...

**Comment by murrant** [comment]
It looks like you overrode the sysDescr here.  It does not say it is linux.

**Comment by E-t-z** [comment]
Thanks, will apply that later today and see, what happens :)

**Comment by E-t-z** [comment]
Tested, platform still stays empty....will check further later.

**Comment by E-t-z** [comment]
Interestingly enough, platfoprm information and kernel information still does not appear.

**Comment by laf** [comment]
08:10 <Etz> sysdescr should be .1.3.6.1.2.1.1.1.0
08:10 <Etz> ?
08:12 <Etz> if so, then great it reports freaking hostname in there...
08:12 <Etz> system.sysDescr.0
08:12 <Etz> no wonder then if it does not work anymore...
