### ISSUE TITLE
Can I assign an alert template to an email and another alert template to sms.

### ISSUE THREAD

**Issue by DonovanEsterhuizen** [librenms/librenms#5438]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.

I have a question regarding alerts, 

Can I assign an alert template to an email and another alert template to sms.

The reason for this is that I will be using HTML in them email alerts which will not be supported with sms

**Comment by laf** [comment]
Just as an FYI, I know you asked this on irc but github isn't for help in setting things up, please continue to use IRC or community.librenms.org

You cant' do separate templates but you can use if / else to separate out the response based on which transport was used. This is covered in the docs http://docs.librenms.org/Extensions/Alerting/#templates
