### ISSUE TITLE
Grouping of sensor types into single graph

### ISSUE THREAD

**Issue by tsumaru720** [librenms/librenms#5445]
FEATURE REQUEST

Hi Fellas, 

If, say, when you click on a sensor type like "Temperature" or "Fanspeed" etc, I think it'd be useful to show all of the values in a single graph in addition to each sensor type individually.

For example with Temperature, if you're making changes to your environment and want to see the overall effect these changes are having on temps, its far far easier to visualize if everything is grouped together into a single graph instead of the individual readings.

Example image attached

This shows all CPU/RAM/HDD temps for my system and it can easily be used to see what difference cooling/environment etc have on the host

![5vcfnofjx1ztzrd4](https://cloud.githubusercontent.com/assets/239857/21966794/5e111554-db72-11e6-8bb9-c3b7b0d8d0f8.png)

vs current stack of single images

<pre>
Component | Version
--------- | -------
LibreNMS  | bfe6ce610c58ab301b17451d18abc945564162c5
DB Schema | 154
PHP       | 5.5.9-1ubuntu4.20
MySQL     | 5.5.53-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2
</pre>

**Comment by Gorian** [comment]
if you take that out of the code tags, it will make a markdown table

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-grouping-of-sensor-types-into-single-graph/669
