### ISSUE TITLE
poller-wrapper - ERROR: missing python module: MySQLdb

### ISSUE THREAD

**Issue by wriedel** [librenms/librenms#5451]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20
).
- [x] Please provide as much detail as possible.

Hi Folks,
I am currently in the process of migrating from Observium Professional towards LibreNMS but have issues getting the poller-wrapper.py running. I have attached the Observium version of the wrapper which is just running fine on our setup. I am not skilled enough to re-write the LibreNMS poller-wrapper on my own and just wonder if someone may already looking onto this Python 2.7.13 / Python 3.5.3rc1 related issues?

Thank you,
Wolfgang

root@thor-odd:/opt/librenms# ./poller-wrapper.py 
ERROR: missing the mysql python module:
On ubuntu: apt-get install python-mysqldb
On FreeBSD: cd /usr/ports/*/py-MySQLdb && make install clean

==========================================================
Component | Version
--------- | -------
LibreNMS  | 44071e83b136ef304f192dbea07e093378b8aeb9
DB Schema | 154
PHP       | 7.0.14-2
MySQL     | 10.2.3-MariaDB-10.2.3+maria~sid-log
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================

root@thor-odd:/opt/librenms# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux testing (stretch)
Release:        testing
Codename:       stretch

root@thor-odd:/opt/librenms# pip freeze
chardet==2.3.0
fail2ban==0.9.6
httplib2==0.9.2
pycurl==7.43.0
pygobject==3.22.0
pyinotify==0.9.6
PyMySQL==0.7.9
python-apt==1.1.0b5
python-debian==0.1.29
python-debianbts==2.6.1
reportbug==7.1.2
requests==2.12.4
six==1.10.0
systemd-python==233
unattended-upgrades==0.1
urllib3==1.19.1

**OBSERVIUM:**

root@thor-odd:/etc# python -V
Python 2.7.13

root@thor-odd:/opt/observium# ./poller-wrapper.py
ERROR: missing python module: MySQLdb
On Ubuntu: apt-get install python-mysqldb
On RHEL/CentOS: yum install MySQL-python
On FreeBSD: cd /usr/ports/*/py-MySQLdb && make install clean

root@thor-odd:/opt/observium# sudo apt-get install python3 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.5.1-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@thor-odd:/opt/observium# rm -f /usr/bin/python 
root@thor-odd:/opt/observium# ln -s python3.5 /usr/bin/python 
r
oot@thor-odd:/opt/observium# python -V 
Python 3.5.3rc1

root@thor-odd:/opt/observium# ./poller-wrapper.py 
INFO: starting the poller at 2017/01/16 00:33:59 with 16 threads, slowest devices first
INFO starting alerter.php for 8
INFO finished alerter.php for 8
INFO starting alerter.php for 9
INFO finished alerter.php for 9
INFO: worker Thread-13 finished device 9 in 20 seconds
INFO: worker Thread-12 finished device 8 in 20 seconds

**LibreNMS:**
root@thor-odd:/opt/librenms# python -V 
Python 2.7.13

root@thor-odd:/opt/librenms# ./poller-wrapper.py 
ERROR: missing the mysql python module:
On ubuntu: apt-get install python-mysqldb
On FreeBSD: cd /usr/ports/*/py-MySQLdb && make install clean

root@thor-odd:/opt/librenms# sudo apt-get install python3 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.5.1-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@thor-odd:/opt/librenms# rm -f /usr/bin/python 
root@thor-odd:/opt/librenms# ln -s python3.5 /usr/bin/python 

root@thor-odd:/opt/librenms# python -V 
Python 3.5.3rc1

root@thor-odd:/opt/librenms# ./poller-wrapper.py                              
ERROR: missing the mysql python module:
On ubuntu: apt-get install python-mysqldb
On FreeBSD: cd /usr/ports/*/py-MySQLdb && make install clean

**Comment by laf** [comment]
Please please please do NOT post things from obs.... we don't and won't look at the code.

**Comment by laf** [comment]
I'm not a debian user but have you done `apt-get install python-mysqldb`?

**Comment by wriedel** [comment]
Hi Neil,

yes it’s all installed and working with Obs*
Just the LibreNMS poller-wrapper needs some re-work to deal with newer Python versions.

Wolfgang

**Comment by murrant** [comment]
@wriedel Seems to me as though you only installed the python 3 version of the module.
`sudo apt-get install python2.7-mysqldb` or something like that should do the trick.

Poller-wrapper.py is specifically set to use python2...

**Comment by wriedel** [comment]
Hi Folks,
no that all didn't help as soon you have python3 on your system. 
It's explained over here:
http://stackoverflow.com/questions/4960048/python-3-and-mysql

I did  a quick hack to make it work with python3 and it works now on my system but I am by far not a software developer but maybe this can help someone more knowledgeable in that space as a start.

Many thanks
Wolfgang 

[poller-wrapper-new.py.txt](https://github.com/librenms/librenms/files/709500/poller-wrapper-new.py.txt)

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-support-python3-for-poller-wrapper-others/668
