### ISSUE TITLE
Huawei S2700 discovering problem

### ISSUE THREAD

**Issue by andryukha** [librenms/librenms#5453]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 463b271a0d6197d1eafa82ce3ba1cc281cad6dc1
DB Schema | 154
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.28-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

http://pastebin.com/ukkGaLzk

- [x] Please provide as much detail as possible.

Huawei S2700 switch detects as zyxel:

![screen](https://cloud.githubusercontent.com/assets/17173678/21978868/f1f0d5a6-dbf5-11e6-833d-316bb194a99b.png)

**Comment by laf** [comment]
Please post the information asked for at the top!

**Comment by andryukha** [comment]
Information updated.
