### ISSUE TITLE
FortiGate 5.4.3 no interfaces found.

### ISSUE THREAD

**Issue by thomasraabo** [librenms/librenms#5454]
Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the 

Component | Version
--------- | -------
LibreNMS  | 44071e83b136ef304f192dbea07e093378b8aeb9
DB Schema | 154
PHP       | 5.4.16
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

- [x ] Please provide as much detail as possible.

FortiGate running 5.4.3 does not find any interfaces <-- but the discovery.php does see something with -v

discovery Verbose output:

Will requested debug info
https://filedump.zitcom.dk/download/11102/8b59365863/output4.txt

**Comment by laf** [comment]
Please pastebin this :(

**Comment by murrant** [comment]
I don't see the ports polling module running.  Is it enabled?

**Comment by laf** [comment]
We could just merge #5447 - the fix for this previously is to allow people to set a config option that stops ports with empty ifDescr values from being ignored.

**Comment by thomasraabo** [comment]
So my DB has been populated with
IfAlias , IfName , IfDescr ... 

But it does seem to look like the Cisco N9K is missing IfDescr
