### ISSUE TITLE
Mikrotik RB3011UiAS CPU Usage Graphs 

### ISSUE THREAD

**Issue by manyax** [librenms/librenms#5455]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.

====================================
Version info:
Commit SHA: 4eb896005004d59c89753cdf795274ee2379a56b
DB Schema: 133
PHP: 5.4.16
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2

====================================

CPU graph not working for Mikrotik RB3011UiAS, can it be fixed ?

Here is the `./discovery.php -h HOSTNAME -d -m processors`

`LibreNMS Discovery
Version info:
Commit SHA: 4eb896005004d59c89753cdf795274ee2379a56b
DB Schema: 133
PHP: 5.4.16
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP version: 5.7.2

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1]
SQL[SELECT revision FROM `dbSchema`] DB Schema already up to date.

SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE 'test-mkr' ORDER BY device_id DESC]
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '425'] test-mkr 425 routeros
#### Load disco module processors ####
Including: /opt/librenms/includes/discovery/processors/avaya-ers.inc.php
Including: /opt/librenms/includes/discovery/processors/ciscosb.inc.php
Including: /opt/librenms/includes/discovery/processors/datacom.inc.php
Including: /opt/librenms/includes/discovery/processors/extreme.inc.php
Including: /opt/librenms/includes/discovery/processors/fiberhome.inc.php
Including: /opt/librenms/includes/discovery/processors/fortigate.inc.php
Including: /opt/librenms/includes/discovery/processors/infinity.inc.php
Including: /opt/librenms/includes/discovery/processors/junos.inc.php
Including: /opt/librenms/includes/discovery/processors/junose.inc.php
Including: /opt/librenms/includes/discovery/processors/netonix.inc.php
Including: /opt/librenms/includes/discovery/processors/procurve.inc.php
Including: /opt/librenms/includes/discovery/processors/radlan.inc.php
Including: /opt/librenms/includes/discovery/processors/screenos.inc.php
Including: /opt/librenms/includes/discovery/processors/sonicwall.inc.php
Including: /opt/librenms/includes/discovery/processors/unifi.inc.php
Including: /opt/librenms/includes/discovery/processors/vrp.inc.php
Including: /opt/librenms/includes/discovery/processors/watchguard.inc.php
Including: /opt/librenms/includes/discovery/processors/zywall.inc.php
Including: /opt/librenms/includes/discovery/processors/cambium.inc.php
Including: /opt/librenms/includes/discovery/processors/dnos.inc.php
Including: /opt/librenms/includes/discovery/processors/hpblmos.inc.php
Including: /opt/librenms/includes/discovery/processors/hrdevice.inc.php
 hrDevice: /usr/bin/snmpwalk -v2c -c COMMUNITY -OQUs  -m HOST-RESOURCES-MIB:HOST-RESOURCES-TYPES -M /opt/librenms/mibs udp:HOSTNAME:161 hrDevicehrDeviceIndex.1 = 1
hrDeviceIndex.2 = 2
hrDeviceType.1 = hrDeviceProcessor
hrDeviceType.2 = hrDeviceProcessor
hrDeviceDescr.1 =
hrDeviceDescr.2 =
hrDeviceID.1 = zeroDotZero
hrDeviceID.2 = zeroDotZero
hrDeviceStatus.1 = running
hrDeviceStatus.2 = running
hrDeviceErrors.1 = 0
hrDeviceErrors.2 = 0
hrProcessorFrwID.1 = zeroDotZero
hrProcessorFrwID.2 = zeroDotZero
hrProcessorLoad.1 = 52
hrProcessorLoad.2 = 34

/usr/bin/snmpwalk -v2c -c COMMUNITY -OQUs  -m HOST-RESOURCES-MIB:HOST-RESOURCES-TYPES -M /opt/librenms/mibs udp:HOSTNAME:161 hrProcessorLoadhrProcessorLoad.1 = 52
hrProcessorLoad.2 = 34

Array, .1.3.6.1.2.1.25.3.3.1.2.1, 1, hr, , 1, 52, , 1
Array, .1.3.6.1.2.1.25.3.3.1.2.2, 2, hr, , 1, 34, , 2
Including: /opt/librenms/includes/discovery/processors/ios.inc.php
Including: /opt/librenms/includes/discovery/processors/ironware.inc.php
Including: /opt/librenms/includes/discovery/processors/netscaler.inc.php
Including: /opt/librenms/includes/discovery/processors/nos.inc.php
Including: /opt/librenms/includes/discovery/processors/pbn.inc.php
Including: /opt/librenms/includes/discovery/processors/powerconnect.inc.php
Including: /opt/librenms/includes/discovery/processors/pulse.inc.php
Including: /opt/librenms/includes/discovery/processors/serveriron.inc.php
Including: /opt/librenms/includes/discovery/processors/viprinux.inc.php
Including: /opt/librenms/includes/discovery/processors/adtran-aos.inc.php
Including: /opt/librenms/includes/discovery/processors/aen.inc.php
Including: /opt/librenms/includes/discovery/processors/aos-device.inc.php
Including: /opt/librenms/includes/discovery/processors/avaya-vsp.inc.php
Including: /opt/librenms/includes/discovery/processors/binos.inc.php
Including: /opt/librenms/includes/discovery/processors/binox.inc.php
Including: /opt/librenms/includes/discovery/processors/calix.inc.php
Including: /opt/librenms/includes/discovery/processors/edgeswitch.inc.php

SQL[SELECT COUNT(*) FROM `processors` WHERE `device_id` = '425' AND `processor_type` != 'ucd-old']
SQL[SELECT * FROM `processors` WHERE `device_id`  = '425']

>> Runtime for discovery module 'processors': 0.093 seconds
#### Unload disco module processors ####

SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '425' AND `attrib_type` = 'poll_mib' ]
SQL[UPDATE `devices` set `last_discovered` =NOW(),`type` ='network',`last_discovered_timetaken` ='0.093' WHERE `device_id` = '425'] Discovered in 0.093 seconds

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`)  VALUES ('discover','test-mkr','1484556953.9224','0.129','1')] ./discovery.php test-mkr 2017-01-16 08:55:54 - 1 devices discovered in 0.129 secs
MySQL: Cell[1/0s] Row[5/0s] Rows[2/0s] Column[0/0s] Update[1/0s] Insert[1/0s] Delete[0/0s]
`

**Comment by laf** [comment]
We need both the full poller and debug output - please pastebin it rather than pasting here.

**Comment by manyax** [comment]
Only for processor ?
`./poller.php -h host -r -m processors`
`./discovery.php -h HOSTNAME -d -m processors`

?

**Comment by laf** [comment]
May as well drop the `-m processors` and we need the snmpwalk info from point 3.

**Comment by manyax** [comment]
Can we look for something specific? don't want to paste the whole configuration ..

**Comment by erotel** [comment]
Im test my librenms and mikrotik RB3011 UiAS and cpu graf is ok.

Component  Version

LibreNMS   463b271a0d6197d1eafa82ce3ba1cc281cad6dc1
DB Schema  154
PHP        5.6.27-0+deb8u1
MySQL     5.5.53-0+deb8u1
RRDTool    1.4.8
SNMP       NET-SNMP 5.7.2.1

**Comment by manyax** [comment]
@laf  .. can we filter only the relevant information ? 
@erotel .. what OS version are you running on the RB ?

**Comment by erotel** [comment]
[admin@MikroTik] /system routerboard> pr
       routerboard: yes
             model: RouterBOARD 3011UiAS
     serial-number: 783D05198C80
     firmware-type: ipq8060
  factory-firmware: 3.27
  current-firmware: 3.27
  upgrade-firmware: 3.35

**Comment by laf** [comment]
@manyax really we need the whole snmpwalk to be able to test against our code.

**Comment by manyax** [comment]
Hi laf, please have a look.

discovery
http://pastebin.com/mZQwLs0K
pooler
http://pastebin.com/APAGTeXk
snmpwalk 1st
http://pastebin.com/gGnhRmCx
snmpwalk 2nd part
http://pastebin.com/KbQc4vNE

**Comment by geordish** [comment]
This was fixed a few weeks ago. Please update your install.

**Comment by manyax** [comment]
Version	c37eef3 - Sun Jan 01 2017 16:50:41 GMT+0100
Doesn't work on mine..

**Comment by geordish** [comment]
The fix was committed in 82579fbb0405bc65520bc51a73c6e8f564a35079. If you're on the stable monthly, this won't have made it there yet. Either update to daily, or wait till the next monthly release.

**Comment by manyax** [comment]
Yes, you are right. Thank you!
