### ISSUE TITLE
graph wifi clients for Deliberant DLB APC Button, DLB APC Button AF and DLB APC 2Mi 

### ISSUE THREAD

**Issue by sysmonk** [librenms/librenms#5456]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.

==========================================================
Component | Version
--------- | -------
LibreNMS  | 44071e83b136ef304f192dbea07e093378b8aeb9
DB Schema | 154
PHP       | 7.0.14-1~dotdeb+8.1
MySQL     | 10.0.28-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

Can we please get wifi clients graphed for Deliberant DLB APC Button, DLB APC Button AF and DLB APC 2mi?

Something like this should be enough:
```diff --git a/includes/polling/wifi.inc.php b/includes/polling/wifi.inc.php
index 94a29df..c6be7c9 100644
--- a/includes/polling/wifi.inc.php
+++ b/includes/polling/wifi.inc.php
@@ -88,6 +88,14 @@ if ($device['type'] == 'network' || $device['type'] == 'firewall' || $device['ty
             echo "AP does not supply client counts\n";
         }
         include 'includes/polling/mib/ubnt-unifi-mib.inc.php';
+    } elseif  ($device['os'] == 'deliberant' && str_contains($device['hardware'], "DLB APC Button")) {
+        echo 'Checking Deliberant APC Button wireless clients... ';
+        $wificlients1 = snmp_get($device, '.1.3.6.1.4.1.32761.3.5.1.2.1.1.16.7', '-OUqnv');
+        echo $wificlients1." clients\n";
+    } elseif  ($device['os'] == 'deliberant' && $device['hardware'] == "\"DLB APC 2Mi\"") {
+        echo 'Checking Deliberant APC 2Mi wireless clients... ';
+        $wificlients1 = snmp_get($device, '.1.3.6.1.4.1.32761.3.5.1.2.1.1.16.5', '-OUqnv');
+        echo $wificlients1." clients\n";
     }
 
     // Loop through all $wificlients# and data_update()
```
I'm running this code for a few days now, everything looks ok.

**Comment by laf** [comment]
Please submit this code in a pull request, we can't accept the code until you sign the contributors agreement and then submit the pull request.
