### ISSUE TITLE
Add support to display the CPU and Memory utilization for TP-Link T1600/T2600 series switch

### ISSUE THREAD

**Issue by kyob** [librenms/librenms#5462]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | 22b74ec36308b9784630bb42b004dfc87931b91d
DB Schema | 154
PHP       | 7.0.14
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

**CPU and Memory utilization for TP-Link T1600/T2600 series switch**

1. The OID of ‘tpSysMonitorCpu5Seconds’ is 1.3.6.1.4.1.11863.6.4.1.1.1.1.2.
2. The OID of ‘tpSysMonitorCpu1Minutes’ is 1.3.6.1.4.1.11863.6.4.1.1.1.1.3.
3. The OID of ‘tpSysMonitorCpu5Minutes’ is 1.3.6.1.4.1.11863.6.4.1.1.1.1.4.
4. The OID of ‘tpSysMonitorMemoryUtilization’ is 1.3.6.1.4.1.11863.6.4.1.2.1.1.2.

More info on TP-Link faq: http://www.tp-link.com.pl/faq-1330.html

**Comment by laf** [comment]
Please provide the information asked for in point 3 above.

**Comment by kyob** [comment]
Mea culpa :)

[discovery](http://pastebin.com/8KhtAicS)
[poller](http://pastebin.com/hafbJY1C)
[snmpbulkwalk](https://mega.nz/#!VdkmFZbI!TWM8JZtMGbmrGXQBVfijTR3rmzv-GhacVxBt3Wldeko) on mega.nz becouse pastebin has limit for free accounts
