### ISSUE TITLE
WAN interfaces returning zero values for traffic throughput on Cisco 1900 router after a LibreNMS version upgrade

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#5464]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

![snap8](https://cloud.githubusercontent.com/assets/16717388/21987371/ee7ba520-dc0b-11e6-92e1-c82aeceba03e.png)
Today I update our Production instance of LibreNMS and after a while I notoced that the traffic throughut graphs of the serial (WAN) interfaces of our Cisco 1941 routers are no longer updating.  The original issue which was raised a while back was #4025 and I think the new update somehow broke this fix. I see that the hardware type of these routers is stored slightly differently in the database than it used to be case before.
![snap7](https://cloud.githubusercontent.com/assets/16717388/21987547/b407dd72-dc0c-11e6-8145-796c8ecec141.png)
Previously the value was stored like this;
![snap9](https://cloud.githubusercontent.com/assets/16717388/21987610/ec4921e6-dc0c-11e6-884d-6a58daa7e2db.png)
I have included the rest of the screenshots I took after an update for your reference;
![snap5](https://cloud.githubusercontent.com/assets/16717388/21987656/1a822cd8-dc0d-11e6-88c7-7b66c336390b.png)
![snap5](https://cloud.githubusercontent.com/assets/16717388/21987671/2344b96c-dc0d-11e6-943b-bafd60cafafb.png)
![snap4](https://cloud.githubusercontent.com/assets/16717388/21987679/297bfdae-dc0d-11e6-96bd-9d2606345e39.png)

**Comment by laf** [comment]
Add $config['os'][$os]['bad_ifXEntry'][]   = 'cisco1941/k9'; to config and see.

**Comment by YukonRob** [comment]
Everything I have seems to be doing similar (returning 0's) - started 2 days ago. It started with my cisco devices first (mainly 3560's). 10218 events since yesterday. Version 370e368.
![librenms](https://cloud.githubusercontent.com/assets/17772515/21993305/027e2a8a-dbcf-11e6-83eb-e9adc0002d71.png)
I also have been updating network settings so not sure where to start looking.

**Comment by laf** [comment]
Unrelated, please update your install

**Comment by breeman1** [comment]
Hi @laf 

I have updated the config file with you suggestion but still no change. I have attached the poller and discovery runs for your reference.

[cisco_1941_Discovery.zip](https://github.com/librenms/librenms/files/710195/cisco_1941_Discovery.zip)
[cisco_1941_Poller.zip](https://github.com/librenms/librenms/files/710196/cisco_1941_Poller.zip)

**Comment by laf** [comment]
Did you update $os in the example I gave you?

**Comment by breeman1** [comment]
how do I do that and what should I update it to?

**Comment by breeman1** [comment]
I pasted the config line you gave exactly as it is in the config.php.

**Comment by laf** [comment]
:)

$os is a variable so you need to set that to what the os is. ios I'm guessing for this.

**Comment by breeman1** [comment]
So this is what I now have in my config.php file however still no change. Did I do this correctly?
![snap4](https://cloud.githubusercontent.com/assets/16717388/22015229/d5487aa8-dca9-11e6-8184-b5fd5fadef5f.png)

**Comment by laf** [comment]
Whilst technically yes it should, I would do this:

`$config['os']['ios']['bad_ifXEntry'][] = 'cisco1941/k9';`

**Comment by breeman1** [comment]
I actually tried both options but it still does not work.

**Comment by laf** [comment]
Will be fixed in #5491

**Comment by laf** [comment]
Upgrade and try again.
