### ISSUE TITLE
Please add support for HP J9625A switch.

### ISSUE THREAD

**Issue by JVijsma** [librenms/librenms#5467]
The HP Procurve YAML definition file does not match a HP J9625A switch:
```
SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs:/opt/librenms/mibs/hp udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0]
HP J9625A 2620-24-PoEP Switch, revision RA.16.02.0012, ROM RA.15.13 (/ws/swbuildm/rel_spokane_qaoff/code/build/xform(swbuildm_rel_spokane_qaoff_rel_spokane))
```
Please add 'HP J9625' to "librenms/includes/definitions/procurve.yaml" or the regex '/^HP J96[0-9]{2}[A-B] [0-9]{4}(.*)/' 

Thanks!

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
You can submit that yourself, why not contribute?

**Comment by jody7734** [comment]
This is needed for the entire HP 2620 line of switches J9623A -> J9627A, they all show up as generic.

**Comment by jody7734** [comment]
I added the suggested regex to my ProCurve.yaml and it seems to have worked, updated the repository,
