### ISSUE TITLE
How to monitor SqlServer ?

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#547]
For sample how many user connection ?

**Comment by f0o** [comment]
LibreNMS uses Check_MK (https://mathias-kettner.de/check_mk.html) to gather additional data per device. With Check_MK, LibreNMS can also understand munin-plugins to extend the datasources.

Check_MK is required to listen on port 6556.

Example xinetd-config as well as scripts (including mysql monitor) can be found in `scripts` and `scripts/agent-local` respectively.

**Comment by wzhsunn** [comment]
what im do you use ? May I add you ?  gtalk or skype ?

**Comment by wzhsunn** [comment]
An agent may be not work for me , I only have snmp read rights to get  info from devices .

**Comment by laf** [comment]
I very much doubt that SQL Server will export data over to snmp, you would need to use something like @f0o  has suggested.

**Comment by f0o** [comment]
You may invest a lot of coding and fiddling in writing an snmp extension for your sql-server's snmpd and for librenms' poller.. But that's really a surplus overhead to an agent...

**Comment by wzhsunn** [comment]
I am not sure with it because I saw some one achieve it and it can display sql server  session , cpu, memory, hits and so on .

**Comment by f0o** [comment]
Thats likely to be with the agent

**Comment by wzhsunn** [comment]
I will do some check .
