### ISSUE TITLE
rrdtool permission denied, Ping tab graph.

### ISSUE THREAD

**Issue by tslytsly** [librenms/librenms#5471]
Hi guys,

Running into a permission denied issue again while trying to view smokeping graphs in the Ping tab.

I removed the -B switch in the rrdcached config to allow it to read from multiple dirs.

What I'm seeing now is this:
if the smokeping rrd files have 664 permissions, which seems right, I get the permission denied error when trying to draw the graph. 
The normal smokeping web page can draw the graphs fine.

All the rrds belong to the smokeping user and group.
My librenms, www-data and smokeping users all belong to that group, so should have rw access to the files.

Except I get the permission denied error.

However, if I set the permissions to 777 all is fine.
774 gives the permission denied error.
767 gives the permission denied error.

What user is running the rrd command?

I would appreciate any help getting to the bottom of this.

Thanks

Component | Version
--------- | -------
LibreNMS  | 44071e83b136ef304f192dbea07e093378b8aeb9
DB Schema | 154
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.28-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
Please post this on community.librenms.org or discuss in irc, it's not an issue with the code base but  your setup / permissions.

**Comment by tslytsly** [comment]
@laf will do
