### ISSUE TITLE
Function name conflict rrd_info()

### ISSUE THREAD

**Issue by julienmorot** [librenms/librenms#5478]
Hello team,

Collectd plugin is not working with master, access to collectd tabs gives an apache error 500 in access log file : 
"GET /device/device=30/tab=collectd/ HTTP/1.1" 500 5951 

With PHP debug enabled, I can see the following error : 
PHP Fatal error:  Cannot redeclare rrd_info() in /opt/librenms/html/includes/collectd/functions.php on line 448

sed -i 's/rrd_info/myrrd_info' /opt/librenms/html/includes/collectd/functions.php solved the problem because rrd_info is already part of php-rrd package : 
http://php.net/rrd_info

Thanks,

Julien Morot

**Comment by laf** [comment]
I'd suggest you remove the php-rrd package, we don't use it or rely on it in anyway.

**Comment by julienmorot** [comment]
I can't and probably others users won't be able too.
We rely on php-gd for cacti and probably other users are using different application on the same system (pnp4nagios, etc...) and can't remove php-gd.

**Comment by laf** [comment]
php-gd, you said php-rrd earlier?

**Comment by julienmorot** [comment]
Your're right, I didn't took my coffee! It's php-rrd of course ;)

**Comment by laf** [comment]
So this can be closed?

**Comment by julienmorot** [comment]
It can't be closed. Librenms collectd feature should work as if php-rrd is installed on the system.
The fix is easy, just one function rename and one function call to adapt, nothing that could lead to a regression.

**Comment by sorano** [comment]
Then why not submit the fix yourself if it's that easy?

**Comment by laf** [comment]
I've submitted a fix for this. This is an upstream issue and we can't offer any guarantees that the file won't be updated in the future and break again.
