### ISSUE TITLE
How to auto generate a topology map ?

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#548]
If I have one thousand PCs , switchers , routers, how to auto generate the topology map just like in gns3 ?

**Comment by wzhsunn** [comment]
May be it is like google map divided to some level , if zoom in or out see for detail .

**Comment by laf** [comment]
You could give this a try: https://github.com/mathieupoussin/observium_map_generator/blob/master/graph.py

**Comment by wzhsunn** [comment]
OK , Thank you. I will have a try !
