### ISSUE TITLE
Current (amperage) average graphing for Eaton PDU

### ISSUE THREAD

**Issue by kapsel** [librenms/librenms#5487]
I have some EATON EMOB20 PDU's that are being monitored (Current, amperage) by LibreNMS. Works great, but graphs only shows Cur, Min, and Max - not Average.

It would be really useful with an average amperage measurement when selecting different timespans (i.e. week, month, year), as we use it for billing purposes (kWh per outlet over i.e. a month, from the average amperage usage).

That, or some other clever way of calculating total power usage per port.

Thanks!

```
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
# ./validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | db7c49225de7602378e46472424d2f4d2d0af457
DB Schema | 154
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 5.7.16-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

[WARN]  Your install is out of date, last update: Mon, 16 Jan 2017 19:27:56 +0000
[OK]    Database connection successful
```

**Comment by kapsel** [comment]
Actually, it would be pretty cool if it would not only show average, but also total kWh for that period, similar to how a "Total XXX GB (In XXX GB Out XXX GB)" is shown for traffic graphs.

The voltage, amperage and period is known already, so should be possible to calculate.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/current-amperage-average-graphing-for-eaton-pdu/667
