### ISSUE TITLE
Fail to rename

### ISSUE THREAD

**Issue by joseaugustocardoso** [librenms/librenms#5488]
I trying to rename a device but I receiving a error:

Renaming of device failed . Does your web server have permission to modify the rrd files?

==========================================================
Component | Version
--------- | -------
LibreNMS  | 01148b94f1e8ed253deeee6ecc54776b9b6a40ba
DB Schema | 154
PHP       | 7.0.14
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

[librenms@librenms ~]$ ls -alh /opt/librenms/rrd/
drwxrwxrwx    2 librenms librenms 8.0K Jan 17 10:09 device

[librenms@librenms ~]$ ls -alh /opt/librenms/rrd/device
-rwxrwxrwx    1 librenms librenms 1.8M Jan 17 10:31 port-id16826.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 17 10:09 port-id16827.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 17 09:34 port-id16828.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 17 10:04 port-id16829.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 16 20:16 port-id16830.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 16 19:14 port-id16831.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 16 20:16 port-id16832.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 16 20:16 port-id16833.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 16 20:16 port-id16834.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 16 20:16 port-id16835.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 16 19:15 port-id16836.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 16 20:16 port-id16837.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 16 20:16 port-id16838.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 17 10:31 port-id21044.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 17 09:34 port-id21045.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 17 10:09 port-id21046.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 17 09:58 port-id21047.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 17 09:49 port-id21048.rrd
-rwxrwxrwx    1 librenms librenms 1.8M Jan 17 10:31 port-id21049.rrd

**Comment by laf** [comment]
I'd guess that you haven't setup permissions on the user as per our install docs.

**Comment by laf** [comment]
Also please post this on community.librenms.org or irc. This isn't an issue in the code base.
