### ISSUE TITLE
How to get line(or port) traffic by snmp ?

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#549]
If I have 3 routers A, B ,C 

A =======B
||
||
C

How to get line traffic from A to B and B to A ? (x kBit/s)
How to get frames speed from A to B and B to A ? (x frames/s)

I only have snmp read rights .

**Comment by laf** [comment]
If I understand what you mean by this then surely that's just a case of looking at the port connect A to B?

So for instance if it's A (Gi0/1) -> B (Gi0/2) then in LibreNMS under ports for device A, click on Gi0/1.

**Comment by wzhsunn** [comment]
Thank you !  
Now I am playing with GNS3 .

I want to build a  environment to simulate  some routes , switches and pcs. 

I am not familiar with GNS3 and struggling  with it .
