### ISSUE TITLE
Remove Unwanted Modules Automatically Upon Detection

### ISSUE THREAD

**Issue by Lonecrowe** [librenms/librenms#5494]
Many OS'es will automatically enable all the services and modules per device.  It then creates dummy files that are never used or graphed in each device. 

BGP, OSPF etc
Cisco based modules
Juniper etc
Printer toner 

It should know that if it is a Cisco it does not need to add printer toner or Juniper based modules! 

I'll extrapolate more specifically what we need later.  

For now I'd like to start with the cambium / canopy OS and make sure everything is disabled except the interface/ports and the actual wireless modules.

**Comment by laf** [comment]
imho we should tackle this purely by enabling only the modules needed for the device type. We've started on this already.

One thing we could do would be to disable polling modules when discovery finds no data. The benefits won't be that great though.

**Comment by laf** [comment]
moved to https://community.librenms.org/t/remove-unwanted-modules-automatically-upon-detection/666
