### ISSUE TITLE
RouterOS wireless section support

### ISSUE THREAD

**Issue by caspercat** [librenms/librenms#5499]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

==========================================================

Hi everyone.
I'm using several types of Mikrotik boxes (RB800, RB2011UiAS-2HnD, RB2011UAS-2HnD) as AP.
When I'm pooling it in wifi poller module checks only ClientConunt:
http://pastebin.com/t3C5QWPz
Every time it says that  "No Such Instance currently exists at this OID" and its true, but when I've walk mtxrWlApClientCount.X where X is wireless ifnumber it returnes value - every time on any of my boxes. X is random (I think so) for every box.

It would be nice if there was support for all wireless section from Mikrotik mib, something similar like wireless section polled from Ubiquiti box (Graphs->Wireless).  I've read a lot about that and peoples are looking for support that.
In mikrotik-mib wireless tree are are two sections:
WlRtab - supports mostly client connection parameters
WlApTab - supports wireless interfaces parameters 
I'm interested in second one. Snmpawlk:  [walk.txt](https://github.com/librenms/librenms/files/714048/walk.txt) There is a data for every wireless interface TxRate, RxRate, SSID, BSSID, ClientCount, Freq, Band, NoiseFloor, OverallTxCCQ, AuthClientCount.

Is there a chance to develop that support?

**Comment by caspercat** [comment]
Partially You're working on this changes at #5498 and @spinza writes about in #1232 . Putting data on the relevant port page is also interesting.

**Comment by murrant** [comment]
We are looking for some feedback regarding this.
Please post info here: https://community.librenms.org/t/improve-wifi-collection-and-graphing-code/453

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/improve-wifi-collection-and-graphing-code/453/5
