### ISSUE TITLE
loadbalancer_rservers needs to be removed from devices that do not use it

### ISSUE THREAD

**Issue by Lonecrowe** [librenms/librenms#5500]
- [X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ X] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 67a97f06f6d86935589227cd097f5a6e26201935
DB Schema | 155
PHP       | 5.3.3
MySQL     | 5.1.73
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.5

As discussed on the IRC - There was an old bug that added a "Routing" tab to all equipment that didn't have any form of routing.  It also added graphs that are empty.  It needs to be removed from all devices that do not have routing enabled.

**Comment by crcro** [comment]
maybe if you don't have any device that uses routing then you could empty that table:
delete from `loadbalancer_rservers` where `farm_id`='0' and `StateDescr`=''

currently i have only empty routing so i couldn't find any valid one to be more specific on this issue

**Comment by Lonecrowe** [comment]
Same here no routing (until Mikrotik decides to actually support it via SNMP!)  but I have removed individual devices including their RRD's and they still have the routing tab there.  It shouldn't show up at all if the device doesn't route.  There must be some other areas it is reporting this.

**Comment by laf** [comment]
This is a general issue in that not all modules clean up after themselves but also if a poller/discovery module is disabled then the data is also not cleaned up.

**Comment by laf** [comment]
Moved to #6807
