### ISSUE TITLE
Feature Request: Support for JANITZA Power Meter UMG 604

### ISSUE THREAD

**Issue by wriedel** [librenms/librenms#5505]
Hi Folks,

sorry another one. The JANITZA Power Meter is being discovered as "Generic Device" and it looks like that the existing MIBS are not being used. Not sure if this is of wider interest or if there is any guidance how I can help to get it working myself?

Attached the relevant MIBS

Many thanks,
Wolfgang

[JANITZA-MIB.txt](https://github.com/librenms/librenms/files/714763/JANITZA-MIB.txt)
[UMG604.mib.txt](https://github.com/librenms/librenms/files/714764/UMG604.mib.txt)

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Failed to parse MIB file /usr/share/snmp/mibs
==========================================================
Component | Version
--------- | -------
LibreNMS  | 6df39b9bbdd5e6a0184640f3c328253f09e8bcab
DB Schema | 156
PHP       | 7.0.14-2
MySQL     | 10.2.3-MariaDB-10.2.3+maria~sid-log
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================

[OK]    Database connection successful

**Comment by wriedel** [comment]
[jan-umg-604-snmpwalk.txt](https://github.com/librenms/librenms/files/716657/jan-umg-604-snmpwalk.txt)
attached some more debugs:
[jan-umg-604-discovery.txt](https://github.com/librenms/librenms/files/716658/jan-umg-604-discovery.txt)
[jan-umg-604-poller.txt](https://github.com/librenms/librenms/files/716659/jan-umg-604-poller.txt)

**Comment by laf** [comment]
That snmpwalk has nothing in it :(

**Comment by wriedel** [comment]
I already stared working on it with so please bear with me for some more days while I am trying to get this done myself ;-)

Just wonder if you have an idea how we can visualize harmonics?
Pls see attached screenshot.
![janitza-harmonics](https://cloud.githubusercontent.com/assets/2451855/22779985/377361be-eebd-11e6-8ed7-f5bc1ad55d77.jpg)

snmpwalk for the record: 
[snmpwalk-janitza-umg-604.txt](https://github.com/librenms/librenms/files/763224/snmpwalk-janitza-umg-604.txt)

**Comment by laf** [comment]
That's just voltage so includes/discovery/sensors/voltages/$os.inc.php

**Comment by sm3ulc** [comment]
I get the same problem. Seems some error in the Janitza smnpd. Impossible for the client to traverse the entire tree.

**Comment by laf** [comment]
@wriedel How are you getting on with this? From a previous comment it appears you are going to add the support, is that the case?

**Comment by wriedel** [comment]
Hi @laf,
sorry still on my plate ;-) The admin stuff is done and I am just missing some current code snipped I should use for voltage, current and power (including pre-cache)
/opt/librenms/includes/discovery/sensors/voltages/janitza.inc.php 
Any hints?
Thank you,
Wolfgang

**Comment by laf** [comment]
@wriedel Sorry I'm not sure what you mean by that?

**Comment by wriedel** [comment]
@laf I remember that @murrant did some rework on the APC modules a while back:
https://github.com/murrant/librenms/tree/apc-cleanup

Therefore I just wonder if there is any recommend way of writing sensors as they all look very different from the way they are written:
/opt/librenms/includes/discovery/sensors/voltage
/opt/librenms/includes/discovery/sensors/current
/opt/librenms/includes/discovery/sensors/power

Or which sensor you like most for voltage/current/power?

**Comment by laf** [comment]
They should all be much of the same. I'd pick examples that are the most recent to copy from if that's what you are looking to do?

https://github.com/librenms/librenms/tree/master/includes/discovery/sensors/current

**Comment by laf** [comment]
Need any help with this @wriedel ?

**Comment by laf** [comment]
Please let us know if you need any further help. If you want someone to take over the development then please provide the details we ask for in point 3
