### ISSUE TITLE
Problem with non-standard mysql port

### ISSUE THREAD

**Issue by fenice2** [librenms/librenms#5514]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

I'm having a problem setting a non-standard port for MySQL, I'm trying to connect to a Galera cluster through proxysql. My install is updated on a daily basis and after a question of the mailing list I tried the suggestion of using this format in the config file: $config['db_host'] = '192.168.1.221:6033';

Unfortunately this seems to cause a problem, when I run validate.php with the port set I get the following output:

./validate.php
<h2>MySQL Error</h2>Unknown MySQL server host '192.168.1.221:6033' (-2)[root@mistral

The output from a working set-up connected to the local mysql on the standard port gives this:

==========================================================
Component | Version
--------- | -------
LibreNMS  | 61b73e8a73e145823a3afff0c735e32f1a3c78c0
DB Schema | 155
PHP       | 5.4.16
MySQL     | 10.1.21-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

I think I've done that correctly but If there's anything I've missed then let me know.

Regards

Bill

**Comment by geordish** [comment]
I've created a PR to add a $config['db_port'] option which might help you. Fancy giving it a go?

**Comment by fenice2** [comment]
I initially assumed that was the correct format but no such luck. :)

Yes, I'd certainly like to give it a try, what do I need to do?

Regards


Bill

**Comment by geordish** [comment]
wget https://patch-diff.githubusercontent.com/raw/librenms/librenms/pull/5517.diff 
git apply 5517.diff

**Comment by fenice2** [comment]
OK, I've tried that and the validate.php connects OK to the db but the poller says it can't connect:

==========================================================
Component | Version
--------- | -------
LibreNMS  | 61b73e8a73e145823a3afff0c735e32f1a3c78c0
DB Schema | 155
PHP       | 5.4.16
MySQL     | 10.1.21-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

[WARN]  Your install is out of date, last update: Wed, 18 Jan 2017 18:57:57 +0000
[OK]    Database connection successful
[FAIL]  The poller has not run in the last 5 minutes, check the cron job
[WARN]  Your local git contains modified files, this could prevent automatic updates.
Modified files:
         build-base.php
         html/install.php
         includes/defaults.inc.php
         includes/init.php
         validate.php

and:
-bash-4.2$ /opt/librenms/poller-wrapper.py 2
ERROR: Could not connect to MySQL database!

**Comment by geordish** [comment]
Yeah, I spotted some more problems.

Do git reset --hard HEAD, then run the 2 commands above again.

**Comment by fenice2** [comment]
Same result, validate works and poller can't connect.

**Comment by geordish** [comment]
OK, spotted another problem!

Try again?

**Comment by fenice2** [comment]
Some result, I'm afraid. Validate connects and poller doesn't.

**Comment by geordish** [comment]
Can you double check you are on my latest patch, and try again. This seems to work for me.

**Comment by fenice2** [comment]
Same result. These are the command I ran:

git reset --hard HEAD
HEAD is now at 61b73e8 webui: Update Font Awesome to 4.7.0 (#5476)
wget https://patch-diff.githubusercontent.com/raw/librenms/librenms/pull/5517.diff
git apply 5517.diff

This is the format for the 'port': $config['db_port'] = '6033';

Even if I change the port to the standard 3306 and the host to localhost, it doesn't work, if I remove the db_port line it connects fine to the local server. Have I done anything wrong here?

**Comment by geordish** [comment]
That looks correct. Have you removed the :port from the db_host option?

Try adding the following line around line 93 on poller-wrapper.py, and see if it spits out the right stuff for you.
```python
print "%s %d %s %s" %(db_server, db_port, db_password, db_dbname)
```

**Comment by fenice2** [comment]
Bingo! That did it. :) Why are there no single quotes on that yet where there are the validate script works but the poller doesn't? You can tell I'm not a coder but wouldn't it be better to have the quotes for consistency?

**Comment by geordish** [comment]
I've just submitted an update that will allow the quotes.

You can test it with your original config if you wish!

**Comment by fenice2** [comment]
I've just tested that with the quotes and that also works. Excellent work and many thanks for the quick fix. :)

Just a last couple of questions, if you don't mind. I guess this fix will be in the next nightly update (or shortly thereafter)? Does this pose a problem to the nightly update running?

**Comment by geordish** [comment]
It will (hopefully) be merged soon. I can't give an ETA on how quickly that
will be. As this has the potential to really break peoples installs, it
might take a big longer than usual.

You won't be able to run nightly updates until this is merged in.

**Comment by fenice2** [comment]
I'll leave this update in as it's installed and works for me, the daily updates don't matter to me that much as I'm just using this on my home LAN. Thanks to you and the team for the work on this project.
