### ISSUE TITLE
Need to add the ability to disable auto refresh

### ISSUE THREAD

**Issue by laf** [librenms/librenms#552]
For:

1. Specific pages (like adding devices / users / alert rules / etc).

2. Disable it globally if the user wants.

**Comment by f0o** [comment]
I agree, we should be able to add an URL param and suppress the meta-reload in the main template. That way we can have it disabled on demand at any page and it would be very little code overhead. Dont you think?

**Comment by laf** [comment]
I was thinking maybe javascript :/ Using the meta-reload means you can't stop the page refresh once the page is loaded so if you wanted to pause a page then you'd have to reload the page to do that.

We could add the javascript timer at the bottom of the page then each individual page could disable it by setting a variable or allow the user to hit pause.

**Comment by f0o** [comment]
oh that's nice!
