### ISSUE TITLE
JunOS - Detect SRX Series as Firewall not Network TYPE.

### ISSUE THREAD

**Issue by dneto82** [librenms/librenms#5528]
Hi Friends,

Thanks for your amazing product. 

I want to help in some manner to detect correctly the junos devices of SRX Model (Internet Gateway). Today they are detected as Network Type, not Firewall.

  http://www.juniper.net/techpubs/en_US/junos11.2/topics/reference/mibs/mib-jnx-chas-defines.txt

**Comment by E-t-z** [comment]
Well SRX (100 - 650 series) can be either firewall or router it has two operating modes.

Flow mode -> Firewall
Packet mode -> Router

Exact mode is determined via configuration, see the documentation:
https://kb.juniper.net/InfoCenter/index?page=content&id=KB30461&actp=search

So I would say, network type is pretty appropriate for this particular platform.
Only High-End models work in single, Firewall mode (SRX1400 and upper models)

**Comment by laf** [comment]
Indeed, I don't see this changing. 

You can change device types per device or set $config['os']['junos']['type'] = 'firewall';

**Comment by InsaneSplash** [comment]
Agreed.

**Comment by dneto82** [comment]
Hi guys,

Thanks for the explanation.

@laf I follow your tip. Thanks.
