### ISSUE TITLE
No BGP info for Juniper BGP peers

### ISSUE THREAD

**Issue by BradHooper** [librenms/librenms#5531]
After recent SQL changes ( #5420 ) all BGP peers have been removed from the bgpPeers_cbgp table for all Juniper devices.

This is happening on 20+ devices. Can provide full debug via email/IRC.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | d83d08e2684cbdc6c35fe7ba43dd12c63914767e
DB Schema | 156
PHP       | 7.0.12
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

-bash-4.2$ cat bgpdebug | grep 1.1.1.1
Found peer 1.1.1.1 (AS666)
    [7.ipv4.210.9.30.254.1.1.1.1.1] => Array
peerindex for ipv4 1.1.1.1 is 2
SQL[SELECT COUNT(*) from `bgpPeers` WHERE device_id = '63' AND bgpPeerIdentifier = '1.1.1.1'] 
SQL[UPDATE `bgpPeers` set `bgpPeerRemoteAs` ='666',`astext` ='<snip>' WHERE device_id='63' AND bgpPeerIdentifier='1.1.1.1'] 
.SQL[SELECT COUNT(*) from `bgpPeers_cbgp` WHERE device_id = '63' AND bgpPeerIdentifier = '1.1.1.1' AND afi='ipv4' AND safi='unicast'] 
SQL[INSERT INTO `bgpPeers_cbgp` (`device_id`,`bgpPeerIdentifier`,`afi`,`safi`)  VALUES ('63','1.1.1.1','ipv4','unicast')] 
SQL[SELECT * FROM bgpPeers_cbgp WHERE `device_id` = '63' AND bgpPeerIdentifier = '1.1.1.1'] 
SQL[DELETE FROM `bgpPeers_cbgp` WHERE `device_id` = '63' AND `bgpPeerIdentifier` = '1.1.1.1' AND afi='ipv4' AND safi='unicast']

**Comment by laf** [comment]
Can you try reverting to this commit pls:

9fa8485f23c8acfcdc85984b6ff62a28a1c81dbe

If that works I think what's happened is that this has always been broken but the data could not be deleted before, now that's fixed it is :)

**Comment by BradHooper** [comment]
Yeah understand the delete now works correctly. I've just rolled back and now bgpPeers_cbgp is populating.

**Comment by laf** [comment]
Can you post a debug output for this, an snmpwalk would be ace as well.
