### ISSUE TITLE
Cumulus Networks logo

### ISSUE THREAD

**Issue by dorkmatt** [librenms/librenms#5535]
This is a minor tweak (follow-up from #3237) to improve the Cumulus logo and fix a minor code formatting nit.

| Component | Version |
| --------- | ------- |
| LibreNMS  | 81bde0b8da6c798245a7916ac6e2096a9c4ab1cc |
| DB Schema | 156 |
| PHP       | 7.0.13-0ubuntu0.16.04.1 |
| MySQL     | 5.7.17-0ubuntu0.16.04.1 |
| RRDTool   | 1.5.5 |
| SNMP      | NET-SNMP 5.7.3|

**Comment by Rosiak** [comment]
Hi Matt,

Will you PR this?

**Comment by Rosiak** [comment]
Hey @dorkmatt,
Feel free to PR if when you are back, I'll close the issue for now.
