### ISSUE TITLE
Blank Interfaces.

### ISSUE THREAD

**Issue by mr-ravirajput** [librenms/librenms#5539]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hi,
I have a huawei router with 600 + sub-interfaces. On the last page of this device, I get a lot of blank entries. These blanks can be searched by IPs and only real time graphs are available. 
http://imgur.com/a/7amwr.

Php validate output

http://pastebin.com/FBriPb4A

Thanks
Ravi

**Comment by laf** [comment]
You've not provided any of the info asked for in point 3.

**Comment by mr-ravirajput** [comment]
./discovery.php -h HOSTNAME -d


LibreNMS Discovery
Version info:
Commit SHA: a0f5fe4f3787162773cfb613a8455898e77a9228
DB Schema: 157
PHP: 7.0.14
MySQL: 5.5.52-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2
DEBUG!
SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1]
DB Schema already up to date.
SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE '127.0.0.1' ORDER BY device_id DESC]
./discovery.php 127.0.0.1 2017-01-23 16:40:58 - 0 devices discovered in 0.121 secs
SNMP: Get[0/0.00s] Walk [0/0.00s]
MySQL: Cell[3/0.00s] Row[0/-0.00s] Rows[3/0.00s] Column[0/0.00s] Update[0/0.00s] Insert[0/0.00s] Delete[0/0.00s]


  ./poller.php -h HOSTNAME -r -f -d

LibreNMS Poller
Version info:
Commit SHA: a0f5fe4f3787162773cfb613a8455898e77a9228
Commit Date: 1485108015
DB Schema: 157
PHP: 7.0.14
MySQL: 5.5.52-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2
DEBUG!
Starting polling run:

SQL[SELECT * FROM `devices` WHERE `disabled` = 0 AND `hostname` = '127.0.0.1' ORDER BY `device_id` ASC]
./poller.php 127.0.0.1 2017-01-23 16:41:46 - 0 devices polled in 0.019 secs
SNMP: Get[0/0.00s] Walk [0/0.00s]
MySQL: Cell[2/0.00s] Row[0/-0.00s] Rows[3/0.00s] Column[0/0.00s] Update[0/0.00s] Insert[0/0.00s] Delete[0/0.00s]

For the last one.. there is tons of info.

**Comment by laf** [comment]
Please use pastebin!

Those commands, you need to replace HOSTNAME with the actual hostname!

**Comment by mr-ravirajput** [comment]
Sorry my bad.
The " ./discovery.php -h <replaced hostname with device ip> -d "gave tons of data. I copied it in word and it comes  up to 370 pages. and still the info from top is missing.
Am I still doing something wrong.
Same is the case with rest of the commands...

**Comment by mr-ravirajput** [comment]
The " ./discovery.php -h "replaced hostname with device ip" -d " **

**Comment by laf** [comment]
No it's not wrong, you'll need to find some way to upload it to a pastebin service.

**Comment by laf** [comment]
No further info provided.
