### ISSUE TITLE
Why no pc display on the map ?

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#554]
![qq 20150307201107](https://cloud.githubusercontent.com/assets/528348/6541373/540d358a-c506-11e4-9c33-edc704d75b85.png)

![qq 20150307201149](https://cloud.githubusercontent.com/assets/528348/6541375/6b323d50-c506-11e4-8d77-a68f7befbbfb.png)

Cloud1 dose not display on the map.

Cloud1 is a loopback ip on win7. 

What's the problem ?

**Comment by laf** [comment]
Was r2 learnt by a discovery protocol like cdp? If so I think the map only shows connections between devices auto discovered. Not 100% sure as if have to check the code.

**Comment by wzhsunn** [comment]
cdp = cisco discovery protocol ?
I do not how to use this .

I run like this by hand :
```
php discovery.php -h all
```

```
php poller.php -h all
```

**Comment by wzhsunn** [comment]
How did you simulate a virtual network with some pc and routes ?

I use gns3 follow your helpful hints.

Now I can simulate a cloud with loopback( tap0 on mac) and one or two route.

When I want add a pc in the network, I using vpcs, but I don't know how to enable snmp on vpcs .

**Comment by laf** [comment]
What do you mean by vpcs?

**Comment by wzhsunn** [comment]
I want to add vpcs (https://github.com/GNS3/vpcs) as a device to librenms . 

But how to enable snmp server on it ?

**Comment by laf** [comment]
It doesn't look like vpcs support snmp at all, they provide limited network tools for working with GNS3:

http://sourceforge.net/projects/vpcs/files/0.6/

**Comment by wzhsunn** [comment]
Yes, I should use an vmware guest or virtualbox guest .

I add a Host1 30.0.0.2  (which is win7  running in vmware )  to my network .

The topology map:


![qq 20150309200644](https://cloud.githubusercontent.com/assets/528348/6554572/32fed5b8-c698-11e4-8e97-31bfc0f13442.png)

Librenms  result :

![r1 ports librenms](https://cloud.githubusercontent.com/assets/528348/6554602/9a80590a-c698-11e4-9e26-36a9573c6701.png)


My question is :

1. why dose f0/0 has 3 ports connected ?
2. why dose f1/0 has none ? It connect to Host1.

**Comment by laf** [comment]
f0/0 shows the Win7 host doesn't it? are you saying that f1/0 should be the one showing this connection?

**Comment by wzhsunn** [comment]
I want to set Host1 to be a win7(which is running in vmware), and I setting the win7 network is VMNet1, But I am wrong , I found now win7 is my host pc not in vmware .

**Comment by wzhsunn** [comment]
OK, I found the problem .

The ip is wrong .

I fix the problem.

**Comment by wzhsunn** [comment]
![qq 20150309215224](https://cloud.githubusercontent.com/assets/528348/6556202/dfb5f904-c6a6-11e4-8494-69d2bfc2bd74.png)
![qq 20150309215139](https://cloud.githubusercontent.com/assets/528348/6556207/e84fd7ba-c6a6-11e4-98db-7bf568ad24fe.png)
![qq 20150309215217](https://cloud.githubusercontent.com/assets/528348/6556211/f1c4b676-c6a6-11e4-8c95-5c6f337c2352.png)


Now the port conections are right , 
but why the map doset has f 1/0 ?

**Comment by laf** [comment]
The map only contains links to devices that have been discovered by a discovery protocol so your host won't be included.

This may be something that could be worked on.

**Comment by wzhsunn** [comment]
Oh, thank you !  

I want an topology map for all devices just like you tell me this:
https://github.com/mathieupoussin/observium_map_generator/blob/master/graph.py .

I try it but some database table maybe different .

**Comment by wzhsunn** [comment]
What's difference between [graph.py](https://github.com/mathieupoussin/observium_map_generator/blob/master/graph.py) and this map ?


The  `win7 PC`  not show in `map`, but in `ports list `.

Dose this mean `win7  PC` is not support discovery protocol ?

If so , the ports list has the topology map relations , why not draw the map with prots list ?

**Comment by wzhsunn** [comment]
@laf  Is my question description clear ?

**Comment by laf** [comment]
I'm not sure the difference with graph.py, you would need to check the sql queries it is running and what needs changing.

The win7 pc may support arp auto discovery but I'm not 100% certain.

**Comment by wzhsunn** [comment]
I will try it ! Thank you !
