### ISSUE TITLE
Brocade logo and Hpe pdu problem

### ISSUE THREAD

**Issue by bahadirbirden** [librenms/librenms#5540]
Hi Everyone ,
by using latest version.

Component | Version
LibreNMS  | ba7cdf4b75f2bf6ead0f19c262d8870f9e7fd3a5
DB Schema | 156
PHP       | 5.6.29
MySQL     | 5.6.34
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

1. Having problem with Brocade 300 SAN switch logo.
2. Having problem with HPE iPDU graphs and logo. (It graphs only management interface , there is no voltage, amp information.) ıts normaly using CPQPOWER

[CPQPOWER1.80.MIB.txt](https://github.com/librenms/librenms/files/721120/CPQPOWER1.80.MIB.txt)
![hp_pdu](https://cloud.githubusercontent.com/assets/8821470/22174298/d631de24-dfeb-11e6-8282-106dbc3e3028.PNG)
![brocade_300](https://cloud.githubusercontent.com/assets/8821470/22174297/d63140b8-dfeb-11e6-8c1e-c386455ff202.PNG)

Best Regards

**Comment by laf** [comment]
Please provide all the info asked when creating an issue
