### ISSUE TITLE
Brocade 300

### ISSUE THREAD

**Issue by bahadirbirden** [librenms/librenms#5543]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | ba7cdf4b75f2bf6ead0f19c262d8870f9e7fd3a5
DB Schema | 156
PHP       | 5.6.29
MySQL     | 5.6.34
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

Add support to http://www.brocade.com/en/products-services/storage-networking/fibre-channel/300-switch.html

- discovery
- poller
-  Proper logo viewing

**Comment by laf** [comment]
None of the information we ask for has been provided

**Comment by bahadirbirden** [comment]
How can i give any extra information about logo :) Just Brocade logo.
