### ISSUE TITLE
Feature Request: Asterisk SNMP Support

### ISSUE THREAD

**Issue by ruhrohshingo** [librenms/librenms#5549]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | eca168ea68446936c606d0ed6e29a209e63248eb
DB Schema | 156
PHP       | 5.3.3
MySQL     | 5.1.73
RRDTool   | 1.3.8
SNMP      | NET-SNMP 5.5

- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

Asterisk host discovery paste: http://pastebin.com/y0WTP0uF
Asterisk host poller paste: http://pastebin.com/8WyxcD8C
Asterisk SNMP paste pt1: http://pastebin.com/5c7p0c62
Asterisk SNMP paste pt2: http://pastebin.com/BLifGbf0
Asterisk SNMP paste pt3: http://pastebin.com/Vg6nCCar

- [x] Please provide as much detail as possible.

Deployed Asterisk SNMP monitoring according to http://www.asteriskdocs.org/en/3rd_Edition/asterisk-book-html-chunk/Monitoring_id241628.html.  Following this process, you need to install net-snmp and net-snmp-devel and recompile Asterisk while specifying the addition of the snmp_res.so module.  After compiling Asterisk (and configuring it up all nice - omitting that information as some of it is in house), you need to place the snmp_res.so into the /etc/asterisk/modules.  Unload the snmp_res.so module and then reload it, then make changes to snmpd.conf to make use of the AgentX subagent.

When performing snmpwalk on the LibreNMS host, use v1 or v2c (don't have v3 configured) and use an OID of .1.3.6.1.4.1.22736 to narrow the output to just Asterisk.  The MIB files for Asterisk and Digium are linked below:

Asterisk mib file: http://pastebin.com/8FiynEXD
Digium mib file: http://pastebin.com/xb15E8tw
(both acquired from https://wiki.asterisk.org/wiki/display/AST/Digium+MIB+Definitions and are quite dated.  Haven't found if there is an updated mib for either)

So while I am getting output from snmpwalk for Asterisk, LibreNMS does not have support for it in the web UI.  For the above section, do note that it was output from a host in test so expect a lot of the int type OIDs to have zero or NULL values.

The Asterisk version on the host from the pastebin files above is 11.23.1 (kinda dated) on a CentOS 6.8 2.6.32-642.6.2.el6.x86_64 host.

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Don't have any debug output handy, but can provide as requested.

**Comment by Lonecrowe** [comment]
I love this idea.  Little bit of work involved in configuring your server to be compatible but allowing us to graph VOIP stats would be incredible without needing any sort of agent besides SNMP.

**Comment by laf** [comment]
Moved to: https://community.librenms.org/t/feature-request-asterisk-snmp-support/924
