### ISSUE TITLE
HP Intelligent Modular iPDU

### ISSUE THREAD

**Issue by bahadirbirden** [librenms/librenms#5551]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | ba7cdf4b75f2bf6ead0f19c262d8870f9e7fd3a5
DB Schema | 156
PHP       | 5.6.29
MySQL     | 5.6.34
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

HP Intelligent Modular iPDU having problem with power consuption statistics. We just getting only management interface.

[ipdu.discovery.txt](https://github.com/librenms/librenms/files/721994/ipdu.discovery.txt)
[ipdu.snmbulkwalk.txt](https://github.com/librenms/librenms/files/721997/ipdu.snmbulkwalk.txt)
[ipdu.poller.txt](https://github.com/librenms/librenms/files/721995/ipdu.poller.txt)
[CPQPOWER1.80.MIB.txt](https://github.com/librenms/librenms/files/721996/CPQPOWER1.80.MIB.txt)

![libre2](https://cloud.githubusercontent.com/assets/8821470/22183793/8ceb5d7e-e0ce-11e6-98d1-0d7325d65254.PNG)
![libre](https://cloud.githubusercontent.com/assets/8821470/22183794/8cebc2a0-e0ce-11e6-9a30-c6157e6a0ed7.PNG)
![libre1](https://cloud.githubusercontent.com/assets/8821470/22183792/8ce9cc5c-e0ce-11e6-9c9c-c370a8175bf7.PNG)

Thanks

**Comment by bahadirbirden** [comment]
any update or help ?

**Comment by laf** [comment]
All of the data should be in ` .1.3.6.1.4.1.232.6`, please provide an updated snmpwalk using that OID.

**Comment by murrant** [comment]
@bahadirbirden Your install seems to be out of data too.

**Comment by laf** [comment]
I'm leaving it closed until the data is provided :)

**Comment by bahadirbirden** [comment]
[snmpwalk-232.txt](https://github.com/librenms/librenms/files/892454/snmpwalk-232.txt)

**Comment by bahadirbirden** [comment]
Thank you for your all help. I tested all the voltage, current, power and load's are working perfectly.
:)
