### ISSUE TITLE
ARP Table not working in Chrome browser

### ISSUE THREAD

**Issue by sliddjur** [librenms/librenms#5555]
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      `Version	8f17025 - Sun Jan 22 2017 21:51:24 GMT+0100`
- [x] Please include all of the information between the 
```
Component | Version
--------- | -------
LibreNMS  | 8f17025803d655a7a3e24edfcfe0be57e809b560
DB Schema | 157
PHP       | 5.5.14
MySQL     | 10.0.28-MariaDB
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.3
```

- [x] Please provide as much detail as possible.

`/search/search=arp/` ARP Table is not working in Chrome browser, tested in Windows. ARP Table works in MS Edge and Firefox. 

Also there are duplicate entries of each device in the device list, with no explanation. Selecting different entries of the same device shows no difference in the ARP table.

**Comment by laf** [comment]
Please check your developers console for the browser and check if it has any errors.

**Comment by sliddjur** [comment]
Top is chrome browser "Uncaught rangeerror: maximum call stack size exceeded"

![capture](https://cloud.githubusercontent.com/assets/10002057/22237752/17cd4d5e-e20e-11e6-9f34-a4942b8dc63e.PNG)

**Comment by laf** [comment]
Can't see any of that debug info

**Comment by sliddjur** [comment]
Chrome Version 55.0.2883.87 m (64-bit) and Version 55.0.2883.87 m. No extensions enabled, in incognito.

**Comment by laf** [comment]
No I literally can't see what line that error is on, you've excluded it from the right.

**Comment by sliddjur** [comment]
Line 1? 
![line1](https://cloud.githubusercontent.com/assets/10002057/22295034/c803be4e-e315-11e6-9bf4-c96bcba04561.png)

**Comment by laf** [comment]
Do you have a lot of devices or arp entries (total numbers?)

If you click that error, can you paste the output pls

**Comment by sliddjur** [comment]
@laf Actually its working today. Did you make any changes? I have 6000+ arp records according to librenms. Also I can only see one of each device in the list.

Another related thing, is it possible to get arp-discovered addresses searchable in `/search/search=ipv4/` ?
And `/search/search=ipv4/` seem to search for string rather than IP's. If I search for `172.16.` I get all IP's starting with the given string, which means I potentially can find 65534 IP's. Can we rather search for a subnet with CIDR notation? Like `172.16.0.0/22`

**Comment by laf** [comment]
Nothing has changed that I'm aware of, it's possible something else has resolved that issue but I'm not certain that's the case.

Pls create another issue for the second request
