### ISSUE TITLE
What is the best way to support other language ?

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#556]
Give me some hints . 

For example use a php language lib and so on . 

Thank you !

**Comment by laf** [comment]
We've talked about this slightly on the google groups list, it needs someone to convert the existing text to a system where you can create new language files. Is this something you could contribute?

**Comment by wzhsunn** [comment]
Yes. I saw it on goolge groups but it didn't give a specific  solution .  I think I want to do something if I can .

**Comment by laf** [comment]
It just needs someone to start updating the code, one idea would be say where you had the following text:

'Add Device'

You would then create language files like:

lang/lang_en.inc.php

and have:

$add_device = 'Add Device'

Then include the language file you want to use and every time $add_device is called it uses the version from the language file you specified.

**Comment by wzhsunn** [comment]
This is a good idea!
