### ISSUE TITLE
Huawei SW no plattform information

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#5568]
Hi !

for the hauwei device S5700-52X-LI-48CS-AC  is see no plattform info under devices -> see screenshoot !

which debug is nessacary to implement the plattform information ?

kind regards 

kirstoferus75
![shoot4](https://cloud.githubusercontent.com/assets/18415083/22243258/dac389fa-e226-11e6-8bc3-c6f25234d251.jpg)

**Comment by laf** [comment]
The debug asked for when creating an issue.
