### ISSUE TITLE
new parameter graph for DASAN OLT V5824G

### ISSUE THREAD

**Issue by tom-falkowski** [librenms/librenms#5576]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Is it possible to add a graph for DASAN OLT V5824G, to monitor number of active igmp multicast groups, when OLT is acting as PIM router?

**Comment by laf** [comment]
Most likely, you need to provide all the info we ask for above.

**Comment by tom-falkowski** [comment]
Dasan OLT Poller
http://pastebin.com/VRN4bqny
Dasan OLT Discovery
http://pastebin.com/kE2SupfR

[snmpwalk dasan.txt](https://github.com/librenms/librenms/files/729330/snmpwalk.dasan.txt)

If you'll need anything else just let me know.

**Comment by laf** [comment]
What oid do we need for the info you've asked for?

**Comment by Rosiak** [comment]
No info provided.
