### ISSUE TITLE
Dashboard | Widget Map - Engine Leaflet - Don't loading Up+Down

### ISSUE THREAD

**Issue by dneto82** [librenms/librenms#5585]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

My Version:
==========================================================
Component | Version
--------- | -------
LibreNMS  | 3c0a2109e592e501b9a1ae6746e46cbe132c776a
DB Schema | 157
PHP       | 7.0.14-pl1-gentoo
MySQL     | 5.7.12
RRDTool   | 1.6.01.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================

The problem:

Overview page not loading map, when I have a lot of nodes. 

[Screenshot of Problem](https://ibin.co/3A1qbAU5Nv6K.png)
[Screenshot with only down Devices](https://ibin.co/3A1rF8FM4RjJ.png)

Developer Console showing errors:

[link:](https://ibin.co/3A27SA6EzDpA.png)

Maybe the problem is related with some data of my locations (sysLocation). Because before, everything was working, but when I add more nodes on last days. I'll check again all data of them.

**Comment by dneto82** [comment]
Hi Guys,

As I suspected (and @laf guessed ) , it was really related to my location data. The problem is that despite all other parts of the system are capable of handling atypical characters, maps can't.

I identified two problems in my data, that when fixed in the device, the map came back perfectly:

1. [0,0] Coordinates like this are not interpreted by the map engine. Although they should, as they are point 0 (near to Guine Gulf). 

2. Apostrophe. Here in Brazil the use is common, so we have many localities like cities and municipalities that have the (') in the name, example: "Barbara D' Oeste".

I do not know if it is possible to easily fix the treatment of these characters or if it is worth it. Anyway, it's a lesson.

Thank you for amazing support!

![capture](https://cloud.githubusercontent.com/assets/1860114/22278022/66e3fd36-e2a7-11e6-8d09-4b9599336e65.PNG)

![capture-2](https://cloud.githubusercontent.com/assets/1860114/22278029/6e6a03c0-e2a7-11e6-976e-f1edfbd4eae7.PNG)

![capture2-2](https://cloud.githubusercontent.com/assets/1860114/22278040/7612b57c-e2a7-11e6-8d20-c7d4b0caf0eb.PNG)

![capture-3](https://cloud.githubusercontent.com/assets/1860114/22278041/79fd84b4-e2a7-11e6-8bf0-303b3b7ff2e6.PNG)

![capture-4](https://cloud.githubusercontent.com/assets/1860114/22278047/7ca78570-e2a7-11e6-9922-99366ad1c4d8.PNG)

**Comment by laf** [comment]
I've submitted a pull request to fix [0,0] being valid.

However I can't get the map to break using `'` within the sysLocation - if you can share a fully working (broken) example we can check further.
