### ISSUE TITLE
Add device group support for searching.

### ISSUE THREAD

**Issue by djamp42** [librenms/librenms#5587]
I use devices groups as a way of separating my different sites. I can click on syslog for example and can choose a particular IP i want to view. However, with 1000+ IPs this becomes unmanageable. Device groups solves that problem for the most part. 

Ideally when searching the categories below, i could choose a device group. I  could then choose all the IPs in that group or specify a single one. There might be more, these are just the ones i came across. 

`Syslog, Inventory, Eventlog, IPv4, IPv6, MAC, ARP, Ports Down, Ports Disabled`

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-add-device-group-support-for-searching/665
