### ISSUE TITLE
Hide device groups on the webUI from users that only have access to a few devices

### ISSUE THREAD

**Issue by bpetit** [librenms/librenms#5593]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable 
monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

==========================================================
Component | Version
--------- | -------
LibreNMS  | f060c757cb71204582e961b28cd7496d02118538
DB Schema | 157
PHP       | 5.6.17-0+deb8u1
MySQL     | 5.5.47-0+deb8u1-log
RRDTool   | 1.5.4
SNMP      | NET-SNMP 5.7.2.1
=========================================================

Hi,

On the webUI seen by a user that only has access to 2 devices in the same device group, we can see the list of all device groups in Devices > Device Groups (even the groups that are not concerned by the users devices). The same is true for Overview > Maps > Device Groups Maps.

Is it planned to fix it ?

Thanks for your time.

**Comment by laf** [comment]
Duplicate #5045

**Comment by bpetit** [comment]
Sorry about that. Thanks.
