### ISSUE TITLE
Incorrect bandwidth from Netgear ProSafe

### ISSUE THREAD

**Issue by garlandtech** [librenms/librenms#5614]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X ] Please provide as much detail as possible.
- [X ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 61ec8e663e9cc87d24d12e6dd16e400d00497afb
DB Schema | 157
PHP       | 7.0.14
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

I'm having an issue where I have a Netgear ProSafe fvs336gv3 firewall that I'm monitoring, and for whatever reason I get many alerts about port utilisation over threshold.  When I look at the overview, by going into the device, clicking on ports, and then hovering over the particular interface, I see that the interface is reported as moving >240Pbps (that's petaybytes per second).  It's a 100Mbps interface, which is reported correctly and the graph is correct.  

The attached images show the different numbers.  The Mbps graph looks/appears correct.  It's the Pbps that I know is off.
![2017-01-25 18_21_22-librenms](https://cloud.githubusercontent.com/assets/25358252/22317864/540d0c3c-e32b-11e6-8aa0-9ed993bef80c.jpg)
![2017-01-25 18_20_43-remote thewoolgatherer com - librenms](https://cloud.githubusercontent.com/assets/25358252/22317866/575eba20-e32b-11e6-9ed6-ff7b55fd7b31.jpg)

**Comment by laf** [comment]
We need the info asked for in point 3 above.

**Comment by garlandtech** [comment]
Whoops, sorry about that.  I didn't see it was a link.

Additional information attached.
Thank you!
[wgngwalk.txt](https://github.com/librenms/librenms/files/732588/wgngwalk.txt)
[wgngpoller.txt](https://github.com/librenms/librenms/files/732589/wgngpoller.txt)
[wgngdisco.txt](https://github.com/librenms/librenms/files/732591/wgngdisco.txt)

**Comment by laf** [comment]
I could be wrong but this looks like it's your device: ifHCInOctets.5 = 18446744073057856040

rrd is probably compensating for that but we don't. 

I'm not sure what to suggest here :(

**Comment by garlandtech** [comment]
Being completely new to Libre (used Observium Community prior at one place) and the alerting, how can I set the thresholds and/or how do you calibrate the data?  The graphs all show the data at what I would expect to be right which is ~2mbps, but there is another sensor - maybe it's the ifHCInOctets.5 that is showing in petabytes, which it can't possibly be.  

I'm having issues with other devices that are throwing over/under limit type alerts constantly and I think if I could figure this one out, I can probably fix the other.

Thanks!

**Comment by laf** [comment]
I'm not really sure what you mean here. ifHCInOctets.5 is in the output you provided and shows irregular values for the port. When we write that to rrd I think rrd deals with overflows and so the value output in the graph will be correct. We don't do that so values recorded in the db and in turn displayed in the webui will look wrong.

**Comment by laf** [comment]
No further info provided
