### ISSUE TITLE
ISE Appliance Support - 3415

### ISSUE THREAD

**Issue by NetCo-Jan** [librenms/librenms#5615]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

==========================================================
Component | Version
--------- | -------
LibreNMS  | 59706194bf3b0db2c624014e3168ef2c739aac4f
DB Schema | 157
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

Hi Guys
in the below link support for ISE Was added - however a few upgrades back the definitions was no longer in the include files. 

https://github.com/librenms/librenms/pull/4063

i added them manually (Yeah i know i shouldn't have)  :

[WARN]  Your local git contains modified files, this could prevent automatic updates.
Modified files:
         includes/definitions.inc.php
         includes/polling/os/ise.inc.php

every time i need to update i have to remove the changes update and add them back - is it possible to make them permanent ?

attached is the files and definitions etc including that of the ISE 3415 Appliance. I have also attached a screenshot showing that it does work nicely - fields like sysname/IP has been removed on purpose 

[ise.inc.php.txt](https://github.com/librenms/librenms/files/731688/ise.inc.php.txt)
[ise3415 to be added to definitions.inc.php.txt](https://github.com/librenms/librenms/files/731689/ise3415.to.be.added.to.definitions.inc.php.txt)

![screenshot 378](https://cloud.githubusercontent.com/assets/24909687/22322721/addec1f8-e3a6-11e6-9d5b-c2cebdbcb35a.png)

thank you
Jan

**Comment by laf** [comment]
Definitions are now in includes/definitions/*.yaml.

Looking at the current one for ise, this includes the same (+ extra) sysObjectId's to check so should be fine. You'll need to remove your changes and submit the output we ask for at the top for further help.

**Comment by NetCo-Jan** [comment]
Perfect let me give it a bash
