### ISSUE TITLE
List traffic bills instead of "Create Bill" if available

### ISSUE THREAD

**Issue by BradHooper** [librenms/librenms#5616]
If a port has a Traffic Bill attached then it would be handy to link to the bill on the ports page instead of "Create Bill" link

http://i.imgur.com/Wf1Apbs.png

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
The issue I see with this is that you can assign a port to more than one bill so how do we decide which one to use?

**Comment by BradHooper** [comment]
If a single bill is available then maybe show the billing name, more than one bill then the billing numbers? Otherwise would the "ifcell" div be available to the right of the interface-desc TD be suitable?

**Comment by laf** [comment]
PR inbound.
