### ISSUE TITLE
Recovery mail from Alert '%faults' how to get recovery state not alert state

### ISSUE THREAD

**Issue by K4S1** [librenms/librenms#5618]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `==========================================================
Component | Version
--------- | -------
LibreNMS  | 08edfc60e06a1f79d0d91d5dd89a95f61d3a8945
DB Schema | 157
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================
` section of `./validate.php` which you can run from the cli.
- [X] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [Here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hi

First Thanks for a great program.
I think I found an issue:
I have a Alert template cut down to nothing like this: http://pastebin.com/nmAezsxt 
And Alert response is correct and timing is perfect. looking like so: http://pastebin.com/m3TJRKtb
But when an port, storage or CPU Recovers. And you get the recovery mail from the alert.
Ports will still appear down, storage free space is the same from the Alerts occurred and CPU load is the same from alerts moment not the recovery moment:
so recovery mail looks like so: http://pastebin.com/8tZL9T3B 

I would like to have the last state of the device when I get a mail. not sure is intended or not.
or possible to call %ports.ifOperStatus some like that.

Thanks in advance, hope you understand. If I need to provide more info, please say :)

**Comment by laf** [comment]
moved to https://community.librenms.org/t/feature-request-recovery-mail-from-alert-faults-how-to-get-recovery-state-not-alert-state/664
