### ISSUE TITLE
Large OS icons on Firefox\Linux

### ISSUE THREAD

**Issue by seeker-dsr** [librenms/librenms#5630]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 3fb65da3396b9f94f36c7c109f69a6467131162e
DB Schema | 157
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

Host:  Ubuntu 16.04.1 LTS
Web: nginx/1.10.0 (Ubuntu)

Firefox 50.1.0 Ubuntu Linux. (No problem in Opera)

OS icons (Linux, Fedora) shown as 256x218. generic-device icon - seems normal.

![lnms](https://cloud.githubusercontent.com/assets/8894508/22362417/ea4f1540-e47b-11e6-84f2-5791161722ea.png)

**Comment by laf** [comment]
Force a browser refresh. I'm sure this is just a cached css file

**Comment by murrant** [comment]
Yes, CTRL-F5 will do the trick.  Might want to mention this with the stable release laf

**Comment by laf** [comment]
I'm actually going to add a ?ver=randomdigits to all css/js calls which can then be updated when style sheets change

**Comment by InsaneSplash** [comment]
I think this is only happening with the current changes, but once its all sorted, then we should be ok?

**Comment by laf** [comment]
We've had it before and it will most likely will happen again so may as well try and allow caches to b bypassed.
