### ISSUE TITLE
graylog integration with nginx as SSL/TLS reverse proxy for graylog not working

### ISSUE THREAD

**Issue by zxyz** [librenms/librenms#5632]
thanks for librenms, I really appreciate the work!

unecrypted, direct (not via nginx)  graylog (v. 2.1) integration in librenms (v. 3fb65da - Thu Jan 26 2017 on ubuntu 16.04) is working. using nginx as reverse proxy with SSL/TLS fails.
api access with a browser and nginx to e. g. `https://1.2.3.4/api/system/stats` works.
I tried (not only :) ) the following config:

librenms config.php:
> $config['graylog']['server']   = 'http://1.2.3.4';
> $config['graylog']['port']     = 443;
> $config['graylog']['username'] = 'name';
> $config['graylog']['password'] = 'password';
> $config['graylog']['version']  = '2.1';

graylog/server.conf:
> rest_listen_uri = http://127.0.0.1:9000/api/
> web_listen_uri = http://127.0.0.1:9000/
> web_endpoint_uri = https://test.example.net/api/

nginx site configuration:
> location / {
>  proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
>  proxy_set_header    Host $http_host;
>  proxy_set_header    X-Graylog-Server-URL https://test.example.net/api;
>  proxy_pass          http://127.0.0.1:9000;
> }

I could not find any error logs.

**Comment by laf** [comment]
Should t your URL be https://?

**Comment by zxyz** [comment]
I also tried `https://`, didn't work

**Comment by githubuserx** [comment]
I also tried all of the above combinations (without reverse proxy though) and never could get the graylog integration to work.
I'm running latest librenms and graylog 2.1.2.

**Comment by laf** [comment]
You're adding on /api/ to the proxy which we automatically append in the query builder.

You can set: `$config['graylog']['base_uri'] = '/search/universal/relative';`

**Comment by zxyz** [comment]
@laf, thanks for your help.

I can acces the api with a browser under e. g. `https://1.2.3.4/api/system/stats`. So it's reachable under the expected URL.

Trying `$config['graylog']['base_uri'] = '/search/universal/relative';` or `$config['graylog']['base_uri'] = '/';` didn't help. Also trying various variations in graylog/server.conf like:

`web_endpoint_uri = https://test.example.net/api/`
`web_endpoint_uri = https://test.example.net/`
`#web_endpoint_uri = https://test.example.net/api/`

didn't help.

**Comment by laf** [comment]
I expect this is something along the lines of an invalid cert. Try pasting this into a file in /opt/librenms/

```php
<?php

require 'config.php';

if (isset($config['graylog']['base_uri'])) {
    $graylog_base = $config['graylog']['base_uri'];
} elseif (version_compare($config['graylog']['version'], '2.1', '>=')) {
    $graylog_base = '/api/search/universal/relative';
} else {
    $graylog_base = '/search/universal/relative';
}

$graylog_url = $config['graylog']['server'] . ':' . $config['graylog']['port'] . $graylog_base . '?query=test&range=dasd';

$context = stream_context_create(array(
    'http' => array(
        'header'  => "Authorization: Basic " . base64_encode($config['graylog']['username'].':'.$config['graylog']['password']) . "\r\n" .
                     "Accept: application/json",
    )
));

$messages = json_decode(file_get_contents($graylog_url, false, $context), true);

print_r($messages);

```

Then run `php FILE.php`

**Comment by zxyz** [comment]
@laf thanks, that did the trick!

@githubuserx hopefully this helps you too.

The graylog instance is using letsencrypt certificates (coudl have written that in the initial posting, sry), so **CN** ist the `fqdn`, but in `config.php` I used the private IPv4 adress. The following configuration is working for me now:

> $config['graylog']['server'] = 'https://test.example.net';
> $config['graylog']['port'] = 443;
> $config['graylog']['username'] = 'name';
> $config['graylog']['password'] = 'password';
> $config['graylog']['version'] = '2.1';

actually, using the `fqdn` could have be something that I could have thought of myself...
anyway, maybe adding a line to the documantation about this could help people in the future.

thanks again.

**Comment by githubuserx** [comment]
Thanks to @laf and @zxyz I solved my problem too :) It wasn't the FQDN but the self-signed certificate I use for graylog. I forgot to import the intermediate CA cert into the trust store, which I was able to debug with the help of @laf's script. Maybe a hint in the docs could prevent future issues regarding this.

**Comment by laf** [comment]
@githubuserx @zxyz Glad your issues are resolved. As for docs - these are open and editable, please contribute back.
