### ISSUE TITLE
eventlog: system	Device IP changed to <private IPv4> | system Device IP changed to <public IPv4>

### ISSUE THREAD

**Issue by zxyz** [librenms/librenms#5633]
My eventlog is full of this messages:

> rt-a system Device IP changed to <private IPv4 address>

(timegap of 5-15 minutes, so 1-3 cron job runs)

> rt-a system Device IP changed to <public IPv4 address>

For all my routers (Cisco 2921, Ubiquiti Edge Router, Ubiquiti Edge Router Lite).

The "Resolved IP"	field in the detail page of the devices changes accordingly.
The devices were added by hand with their private IPv4 address.

(librenms 3fb65da - Thu Jan 26 2017 on ubuntu 16.04)

**Comment by f0o** [comment]
Does the DNS reply with only 1 address?

**Comment by zxyz** [comment]
There are both addresses in the DNS (the private and the public IPv4) and that are exactly the legitimate IP addresses which are referenced in librenms.

**Comment by crcro** [comment]
if you added the device using dns entry and your dns is responding with both ip's then it is normal to have this, as librenms dns cache is rebuild from time to time using first ip returned by your dns servers.

you could do:

- add device by private ip not the dns entry
- internal/external dns setup
- view based dns (if your dns server supports this)

**Comment by zxyz** [comment]
The devices were added by hand with their private IPv4 addresses.

**Comment by laf** [comment]
I've submitted some code to tidy up the dnslookup function up a little.

In general though I don't think we have an issue here as we filter the hostname on ip and don't do any dns lookup.

To test I did:

```
php -r "if (filter_var('127.0.0.1', FILTER_VALIDATE_IP, FILTER_FLAG_IPV4) == true || filter_var('127.0.0.1', FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) == true) echo 'test'; "
php -r "if (filter_var('192.168.1.1', FILTER_VALIDATE_IP, FILTER_FLAG_IPV4) == true || filter_var('127.0.0.1', FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) == true) echo 'test'; "
php -r "if (filter_var('8.8.8.8', FILTER_VALIDATE_IP, FILTER_FLAG_IPV4) == true || filter_var('127.0.0.1', FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) == true) echo 'test'; "
```

You can do the same as above but change the first IP with one of yours, it should echo test out, if it doesn't then you'll really need to provide us with the IPs in use.

**Comment by zxyz** [comment]
thanks for the patch @laf. unfortunately it doesn't help.

I changed the two lines in  **includes/functions.php**, restartet the web server, cleared the browser cache (just to be save), waited 15 Minutes and new messages of the same kind still appear.

The IP adresses in question are not these, but of this format: `172.30.0.23` and `92.101.3.121`

the code lines above returns `true` on the machine running librenms for every string in a valid IPv4 format (and for the IPv4 adress actually in use), e. g. using the following 

```
php -r "if (filter_var('1.2.3.4', FILTER_VALIDATE_IP, FILTER_FLAG_IPV4) == true || filter_var('127.0.0.1', FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) == true) echo 'test'; "
```
substituting **1.2.3.4** with e. g. **7.7.7.7** or **6.6.6.6** returns `true`

**Comment by laf** [comment]
Those tests all confirm that the code will be doing what's it's supposed to and that IPs are ignored which will result in the code not executing the eventlog you are seeing.

I've got no further suggestions. @librenms/reviewers anyone else?

**Comment by crcro** [comment]
did you add the device using dns? if yes, and your dns is answering with both ip addresses then this is no issue, is quite the expected behaviour. you could also add to your /etc/hosts file the dns entry with the private ip address and then no dns lookup will be performed.

**Comment by laf** [comment]
I actually thought he was just using IP as he said: The devices were added by hand with their private IPv4 addresses.

**Comment by zxyz** [comment]
I did as @crcro suggested and added the private IPv4 addresses to the hosts file associated with the name which appears as **System Name** in LibreNMS. Didn't help, the `Device IP changed to` messages are still appearing.

And, just to make sure: The devices were added by hand with their private IPv4 addresses.

**Comment by crcro** [comment]
which kind of device are you having this issue? i'm think of some bug in the snmp server implementation on it ...

**Comment by laf** [comment]
I don't think it's an snmp issue, this is all done using dns lookups.

**Comment by crcro** [comment]
even if it is using IP?

**Comment by laf** [comment]
Yes this message is from code that just checks if it's an IP and if it is, skips the dns lookup and if it's not does a dns lookup and compares old ip to new ip

**Comment by crcro** [comment]
this is strange as i have various devices with multiple ip's on them and libre isn't acting this strange. i had same issue with dns entries with multiple ip's tho ...

**Comment by laf** [comment]
Multiple responses on A / AAAA records is expected. This issue I don't think is actually an issue.

**Comment by zxyz** [comment]
@crcro
Cisco 2921, IOS 15.2
Ubiquiti Edge Router Pro, EdgeOS 1.85
Ubiquiti Edge Router Lite. EdgeOs 1.85

**Comment by zxyz** [comment]
@laf 
There are up to three  AAAA records specified for the routers. There are no eventlog messages regarding IPv6 adresses.

BTW: is there a way to exclude these  "Device IP changed to " messges from the eventlog?

**Comment by laf** [comment]
What has AAAA got to do with it when you say you've added the device by ip. You're going to have to clearer and more forthcoming with information for us to help further.

**Comment by zxyz** [comment]
@laf I was trying to give all the information I have. 

crcro  wrote: "i had same issue with dns entries with multiple ip's tho"

So I wanted to let you know, that some of the devices have multiple IPv6 adresses and accordingly multiple AAAA records but don't have the eventlog messages for the IPv6 adresses.

The devices were added by their private IPv4 addresses.

If you need more information please let me know.

**Comment by laf** [comment]
I still don't see how this possible so you'll have to hope someone else takes a look

**Comment by zxyz** [comment]
@laf thank you anyway!

btw: is it possible to exclude these "Device IP changed to " messages from the eventlog?

**Comment by murrant** [comment]
@zxyz perhaps you should supply actual information.  Such as screenshots and the text of the event log entries.

**Comment by zxyz** [comment]
here we go

![libre](https://cloud.githubusercontent.com/assets/14958508/22542016/0e4c9a78-e92a-11e6-89a0-f5e169cb4c57.png)

**Comment by murrant** [comment]
You blocked out the interesting part. 172.31.x.x is a private IP space, surely it is OK to share those IPs.

Also, these appear to be added by name, not IP as you previously said.

**Comment by zxyz** [comment]
They were added by private IPv4. But I renamed them in the web interface, which I totally forgot to mention (really sorry for that!), so that e. g. graylog messages are matched. 

You're right, there is no actual split. But maybe there is no need for that in my use case. From within the LAN the private IPv4 or the global IPv6 Adresss is used by to connect to the routers, and from WAN side the public IPv4 or the IPv6 adress is used. `ssh -4 rt-bb-b` works from LAN and WAN side. 
(BTW. it's not my DNS setup.)

I changed rt-bb-a in the web interface to the private IPv4 address and the messages disappeared for the device. Thats good, but how could I use the devices name to match e. g. graylog messages without the device turning up in the event log? One way would be as mentioned by different people split DNS. But this is not my DNS setup. Are there any other options?

I thought of the name in the webfrontend of beeing a kind of alias and not having the fqdn provided to LibreNMS how does it expand the name with the domain to a fqdn?

thanks again for your hel @murrant!

**Comment by murrant** [comment]
Rename the device again, but use the fqdn.  :-)

**Comment by zxyz** [comment]
thanks murrant, unfortunately that didn't help. The messages still emerge.

**Comment by laf** [comment]
I'm proposing we close this. The log is generated because on each poll a dns lookup returns a different IP. @librenms/reviewers

**Comment by zxyz** [comment]
I just wanted to let you know, I asked the dns admin to remove the double DNS entries of the spare routers for testing and the messages disappeared.
