### ISSUE TITLE
Issue: Generex CS141 discovery

### ISSUE THREAD

**Issue by sirHulda** [librenms/librenms#5634]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 3fb65da3396b9f94f36c7c109f69a6467131162e
DB Schema | 157
PHP       | 5.6.29-0+deb8u1
MySQL     | 5.5.54-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

- [x] Please provide as much detail as possible.

Discovery doesn't work on my CS141 ups card. It works on my cs121 cards though. I checked sysobjectid and the output is "The Cs141 SNMP Agent". After changing "CS141" to "Cs141" in generex-ups.yaml the discovery worked fine.

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

10.2.255.10 389 generic SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0]
The Cs141 SNMP Agent

SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Ovqn -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysObjectID.0]
.*.2.1.33

| The Cs141 SNMP Agent | .1.3.6.1.2.1.33 |

**Comment by sirHulda** [comment]
Hey,
Thanks for  the fix. Now it does discover properly but polling is no go.

Example:
"Checking (snmp) current Output Phase 1..."
.1.3.6.1.2.1.33.1.4.4.1.3.1 = No Such Instance currently exists at this OID
Should be: .1.3.6.1.2.1.33.1.4.4.1.3.1.0 = INTEGER: 104

Full discovery: http://pastebin.com/W01PjH54
Full poll: http://pastebin.com/5dRDxKkB

Thanks

**Comment by FTBZ** [comment]
The Generex support was contacted and I've got a confirmation that's a firmware problem that will be solved in the future 1.50 release planned in two weeks.

**Comment by laf** [comment]
Ignore the above. This still needs fixing.

**Comment by sirHulda** [comment]
Sorry, still not working after #5820 
New disco: http://pastebin.com/SjCN7v6L
New poll: http://pastebin.com/gBHGzt3D

**Comment by sirHulda** [comment]
Generex will fix this in upcoming FW update (v1.50)

**Comment by FTBZ** [comment]
Generex has released the 1.50 firmware, including the fix (not tested at this time):

- Bugfix: SNMP-Agent appends wrong â€œ.0" to OIDs of tabular values [#3341]

**Comment by sirHulda** [comment]
Discovery and polling works fine after 1.50 fw upgrade
