### ISSUE TITLE
Issue with Transit, Peering and Core port

### ISSUE THREAD

**Issue by rockyluke** [librenms/librenms#5648]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

> LibreNMS  | f6fc5fdf71d51e3158fe785e5d1e0daeb04214f9
> DB Schema | 157
> PHP       | 5.6.29-0+deb8u1
> MySQL     | 10.1.20-MariaDB-1~jessie
> RRDTool   | 1.4.8
> SNMP      | NET-SNMP 5.7.2.1

Hello team,

All my network's ports are tagged following your guide : 

- Transit => 'Transit: Level3 (XXXX) {YYYY} [10Gbps]'
- Peering => 'Peering : AMS-IX {YYYY} [1Gbps]'
- Core => 'Core: XXXX [10Gbps]'

In my configuration I have (to present case issue with my network team) : 

```php
$config['core_descr'] = array('CORE', 'Core', 'core');
$config['transit_descr'] = array('TRANSIT', 'Transit', 'transit');
$config['peering_descr'] = array('PEERING', 'Peering', 'peering');
$config['customers_descr'] = array('CUST', 'Cust', 'cust');
```

Am I missing something ?

Thanks a lot for the great work you've all done.

**Comment by laf** [comment]
Using your exact config and the interface descriptions I've tested and confirmed this works fine.

![image](https://cloud.githubusercontent.com/assets/3941142/22399033/8e5b7222-e58b-11e6-9b4a-ca74fe914f16.png)

![image](https://cloud.githubusercontent.com/assets/3941142/22399035/9534b54a-e58b-11e6-9ac9-b419a81da107.png)


Your peering config has an extra space between Peering and `:` but I expect that might just be a mistake.

If you need further help then please join our irc channel or post on community.librenms.org
