### ISSUE TITLE
Integrate LibreNMS with GLPI

### ISSUE THREAD

**Issue by rockyluke** [librenms/librenms#5649]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

> LibreNMS  | f6fc5fdf71d51e3158fe785e5d1e0daeb04214f9
> DB Schema | 157
> PHP       | 5.6.29-0+deb8u1
> MySQL     | 10.1.20-MariaDB-1~jessie
> RRDTool   | 1.4.8
> SNMP      | NET-SNMP 5.7.2.1

Hello team,

Just wanted to ask if there any plans to integrate LIbreNMS with GLPI in the future ? I would be really happy to provide you GLPI functional setup.

Documentation : https://fossies.org/dox/glpi-9.1.2/md_apirest.html

Thanks a lot for the great work you've all done.

**Comment by laf** [comment]
Please create a discussion on https://community.librenms.org/c/feature-requests

This isn't a simple request :(
