### ISSUE TITLE
Validate.php = [FAIL]  You have a different system timezone (UTC) specified to the php configured timezone (CET)

### ISSUE THREAD

**Issue by NK74** [librenms/librenms#5655]
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

| Component | Version |
| --------- | ------- |
| LibreNMS  | 5be1ea9132c5c8b1cf11911cc637644f8b94c14a |
| DB Schema | 157 |
| PHP       | 7.0.13-0ubuntu0.16.04.1 |
| MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1 |
| RRDTool   | 1.5.5 |
| SNMP      | NET-SNMP 5.7.3 |

```
[OK]    Database connection successful
[FAIL]  You have a different system timezone (UTC) specified to the php configured timezone (CET), please correct this.
```

In **/etc/php/7.0/apache2/php.ini** and **/etc/php/7.0/cli/php.ini**
**date.timezone** value is Europe/Paris

**php -i | grep date.timezone**
```
date.timezone => Europe/Paris => Europe/Paris
```

**Comment by laf** [comment]
This is as validate is telling you, your system timezone is different than the php configured.

This isn't a code issue, please discuss this in irc or community.librenms.org
