### ISSUE TITLE
Memory Health/Occupation Linux Machines: cached memory is not considered free/available

### ISSUE THREAD

**Issue by zxyz** [librenms/librenms#5660]
In LibreNMS unter **Health - Memory** the `Physical Memory` and `Virtual Memory`  all my Linux VMs Memory is marked **red**, due to a very high occupation. The VM named **monitor** below shows the following output:

> monitor	Physical memory      7.650GB / 7.800GB           151.520MB	98%
> monitor  Virtual memory        7.650GB / 7.800GB         151.520MB	98%

This is correct, when buffered and cached memory is regarded as occupied.

`free -h` on **monitor** shows:
> `                   total           used          free         shared   buff/cache   available`
> `Mem:           7.8G        1.8G        152M         86M        5.9G            5.6G`

So actually, **monitor** is quite happy with its memory. I would suggest to no use the `free` value but the `available` value for indication (on Linux machines).

Thanks for LibreNMS!

(latest LibreNMS, ubuntu 16.04)

**Comment by laf** [comment]
Most likely a duplicate of #3179 please read it and see

**Comment by zxyz** [comment]
oh, yes it is a dupicate. It flipped through my search. sry for that.

**Comment by laf** [comment]
The other issue is closed as well. Does it answer your question as we've not changed how we do memory graphs since then afaik

**Comment by zxyz** [comment]
@laf thanks for asking. It answered my question but I think I disagree. I think  I'll comment in the other issue.
