### ISSUE TITLE
CISCO CIMC -  Hardware Components vanished

### ISSUE THREAD

**Issue by wriedel** [librenms/librenms#5661]
Hi Folks,

over the last days for most, but not all, CISCO UCS CIMC's the hardware inventory disappeared or sensors got  deleted.
I attach debugs from two similar servers were the inventory is still there and another one where it's gone.

Not sure if this is related to:
SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
and where it's coming from?

[working-discovery-cimc-c420-b.txt](https://github.com/librenms/librenms/files/737453/working-discovery-cimc-c420-b.txt)
[broken-discovery-cimc-c420-a.txt](https://github.com/librenms/librenms/files/737454/broken-discovery-cimc-c420-a.txt)
[broken-poller-cimc-c420-a.txt](https://github.com/librenms/librenms/files/737452/broken-poller-cimc-c420-a.txt)
[working-poller-cimc-c420-b.txt](https://github.com/librenms/librenms/files/737455/working-poller-cimc-c420-b.txt)

//----------------------------------

Also there are so many more CISCO-UNIFIED-COMPUTING MIBS not being used et all?

ll /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING*
-rwxr-xr-x 1 root root  249402 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-AAA-MIB
-rwxr-xr-x 1 root root 1014891 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-ADAPTOR-MIB
-rwxr-xr-x 1 root root  212774 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-BIOS-MIB
-rwxr-xr-x 1 root root    8913 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-BMC-MIB
-rwxr-xr-x 1 root root   51070 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-CALLHOME-MIB
-rwxr-xr-x 1 root root   73857 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-CAPABILITY-MIB
-rwxr-xr-x 1 root root    6133 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-CHANGE-MIB
-rwxr-xr-x 1 root root   30471 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-CIMCVMEDIA-MIB
-rwxr-xr-x 1 root root  129534 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-COMM-MIB
-rwxr-xr-x 1 root root  453738 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-COMPUTE-MIB
-rwxr-xr-x 1 root root   13724 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-CONFIG-MIB
-rwxr-xr-x 1 root root   31181 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-DCX-MIB
-rwxr-xr-x 1 root root   10665 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-DHCP-MIB
-rwxr-xr-x 1 root root   26015 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-DIAG-MIB
-rwxr-xr-x 1 root root   33776 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-DOMAIN-MIB
-rwxr-xr-x 1 root root    5237 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-DPSEC-MIB
-rwxr-xr-x 1 root root   44324 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-EPQOS-MIB
-rwxr-xr-x 1 root root  802746 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-EQUIPMENT-MIB
-rwxr-xr-x 1 root root  316466 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-ETHER-MIB
-rwxr-xr-x 1 root root   22630 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-EVENT-MIB
-rwxr-xr-x 1 root root   26993 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-EXTMGMT-MIB
-rwxr-xr-x 1 root root   85018 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-EXTPOL-MIB
-rwxr-xr-x 1 root root  157768 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-EXTVMM-MIB
-rwxr-xr-x 1 root root   34865 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-FAULT-MIB
-rwxr-xr-x 1 root root   87538 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-FC-MIB
-rwxr-xr-x 1 root root   28427 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-FCPOOL-MIB
-rwxr-xr-x 1 root root  228438 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-FIRMWARE-MIB
-rwxr-xr-x 1 root root    8181 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-FLOWCTRL-MIB
-rwxr-xr-x 1 root root    5257 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-FSM-MIB
-rwxr-xr-x 1 root root   30511 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-GMETA-MIB
-rwxr-xr-x 1 root root   18212 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-GRAPHICS-MIB
-rwxr-xr-x 1 root root    9340 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-HOSTIMG-MIB
-rwxr-xr-x 1 root root   53366 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-IDENT-MIB
-rwxr-xr-x 1 root root    6950 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-IMGPROV-MIB
-rwxr-xr-x 1 root root    7171 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-IMGSEC-MIB
-rwxr-xr-x 1 root root   32529 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-INITIATOR-MIB
-rwxr-xr-x 1 root root   18929 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-IP-MIB
-rwxr-xr-x 1 root root   35702 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-IPPOOL-MIB
-rwxr-xr-x 1 root root   24300 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-IQNPOOL-MIB
-rwxr-xr-x 1 root root    6160 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-ISCSI-MIB
-rwxr-xr-x 1 root root   96901 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-LICENSE-MIB
-rwxr-xr-x 1 root root    4582 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-LLDP-MIB
-rwxr-xr-x 1 root root   66808 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-LSBOOT-MIB
-rwxr-xr-x 1 root root   15569 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-LSMAINT-MIB
-rwxr-xr-x 1 root root   85917 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-LS-MIB
-rwxr-xr-x 1 root root   43878 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-LSTORAGE-MIB
-rwxr-xr-x 1 root root   21013 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-MACPOOL-MIB
-rwxr-xr-x 1 root root    7547 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-MAPPINGS-MIB
-rwxr-xr-x 1 root root   95657 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-MEMORY-MIB
-rwxr-xr-x 1 root root  213244 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-MGMT-MIB
-rwxr-xr-x 1 root root  278408 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-MIB
-rwxr-xr-x 1 root root   31069 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-NETWORK-MIB
-rwxr-xr-x 1 root root   42256 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-NFS-MIB
-rwxr-xr-x 1 root root    2985 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-NOTIFS-MIB
-rwxr-xr-x 1 root root    6340 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-NWCTRL-MIB
-rwxr-xr-x 1 root root   28322 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-OBSERVE-MIB
-rwxr-xr-x 1 root root    6675 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-ORG-MIB
-rwxr-xr-x 1 root root    9279 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-OS-MIB
-rwxr-xr-x 1 root root   14103 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-PCI-MIB
-rwxr-xr-x 1 root root   35354 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-PKI-MIB
-rwxr-xr-x 1 root root  114834 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-POLICY-MIB
-rwxr-xr-x 1 root root   21661 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-PORT-MIB
-rwxr-xr-x 1 root root   52622 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-POWER-MIB
-rwxr-xr-x 1 root root   68563 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-PROCESSOR-MIB
-rwxr-xr-x 1 root root   20470 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-PROC-MIB
-rwxr-xr-x 1 root root   34841 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-QOSCLASS-MIB
-rwxr-xr-x 1 root root    9377 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-QUERYRESULT-MIB
-rwxr-xr-x 1 root root    7133 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-SES-MIB
-rwxr-xr-x 1 root root   12864 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-SOL-MIB
-rwxr-xr-x 1 root root   59740 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-STATS-MIB
-rwxr-xr-x 1 root root  293773 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-STORAGE-MIB
-rwxr-xr-x 1 root root  462417 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-SW-MIB
-rwxr-xr-x 1 root root  174618 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-SYSDEBUG-MIB
-rwxr-xr-x 1 root root   23513 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-SYSFILE-MIB
-rwxr-xr-x 1 root root  994755 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-TC-MIB
-rwxr-xr-x 1 root root   13280 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-TOP-MIB
-rwxr-xr-x 1 root root   38720 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-TRIG-MIB
-rwxr-xr-x 1 root root   21570 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-UUIDPOOL-MIB
-rwxr-xr-x 1 root root    5955 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-VERSION-MIB
-rwxr-xr-x 1 root root  104590 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-VM-MIB
-rwxr-xr-x 1 root root  341367 Jan 18 19:57 /usr/share/snmp/mibs/cisco/CISCO-UNIFIED-COMPUTING-VNIC-MIB

Updating to latest codebase                        OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
==========================================================
Component | Version
--------- | -------
LibreNMS  | 5be1ea9132c5c8b1cf11911cc637644f8b94c14a
DB Schema | 157
PHP       | 7.0.14-2
MySQL     | 10.2.3-MariaDB-10.2.3+maria~sid-log
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================

[OK]    Database connection successful
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        html/images/os/janitza.png
        includes/definitions/janitza.yaml
        includes/discovery/os/janitza.inc.php
        includes/polling/os/janitza.inc.php
        mibs/janitza/
        poller-wrapper-new.py

nothing added to commit but untracked files present (use "git add" to track)

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
I'm not sure if you're discovery files got mixed up but the one labelled working seems to be the broken one and a quick indication seems to show it's purely because that device doesn't respond back with data in the snmp request:

`No Such Object available on this agent at this OID`

**Comment by wriedel** [comment]
Hi laf,
now they're all back again!
Looks like the sensors are coming and going?

2017-01-29 11:53:10 	
System	Sensor Deleted: power cimc mb-input-power MB Input Power

2017-01-29 11:53:04 
System	Sensor Deleted: current cimc mb-input-current MB Input Current

2017-01-29 13:04:37 	
System	Sensor Added: power cimc mb-input-power MB Input Power

2017-01-29 13:04:37 
System	Sensor Added: current cimc mb-input-current MB Input Current

Any good way to trouble shoot why?

**Comment by laf** [comment]
If you can run two discovery debugs and it shows the sensor being removed then added that should be enough.

**Comment by laf** [comment]
Feel free to provide this info when you have it.

**Comment by wriedel** [comment]
just for the record, looks to be a CIMC issue. 
I now had two CIMCs dying at the same time since being polled by LibreNMS but just two out of many. Looks to be the OID of death and time for an firmware upgrade ;-)
