### ISSUE TITLE
CISCO NEXUS - wierd number prefix on port listing

### ISSUE THREAD

**Issue by wriedel** [librenms/librenms#5662]
Hi Folks,

for a CISCO NEXUS box all interface under Ports get prefixed by a number:
83886080. mgmt0
151060481. Vlan1

SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs -m IF-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:HOSTNAME:161 ifDescr]
ifDescr.83886080 = mgmt0
ifDescr.151060481 = Vlan1

SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs -m IF-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:HOSTNAME:161 ifName]
ifName.83886080 = mgmt0
ifName.151060481 = Vlan1

SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs -m IF-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:HOSTNAME:161 ifType]
ifType.83886080 = ethernetCsmacd
ifType.151060481 = propVirtual

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

==========================================================
Component | Version
--------- | -------
LibreNMS  | 5be1ea9132c5c8b1cf11911cc637644f8b94c14a
DB Schema | 157
PHP       | 7.0.14-2
MySQL     | 10.2.3-MariaDB-10.2.3+maria~sid-log
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================

[OK]    Database connection successful

**Comment by laf** [comment]
That's just the ifIndex value isn't it?

**Comment by laf** [comment]
Yes it's just ifIndex. There is a discussion about us dropping showing that here: https://community.librenms.org/t/benefit-of-listing-ifindex-number/467

**Comment by wriedel** [comment]
Hi laf,
good point, yes these numbers are the ifindex ;-)

show interface snmp-ifindex | incl mgmt0
mgmt0           83886080   (0x5000000 )

show interface snmp-ifindex | incl Vlan1   
Vlan1           151060481  (0x9010001 )

Wolfgang
