### ISSUE TITLE
Add support to graph CPU and memory utilization for HP 1910 and 1920.

### ISSUE THREAD

**Issue by manyax** [librenms/librenms#5665]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

==========================================================
Component | Version
--------- | -------
LibreNMS  | f828a927d2126d3b0805f6b7f975f39673303c6a
DB Schema | 157
PHP       | 5.4.16
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

I have several HP 1910 and 1920, is it possible to add CPU and memory graph?
`snmpbulkwalk -OUneb -v2c -c COMMUNITY host-hp1910 .1.3.6.1.4.1.25506.2.6.1.1.1.1.6.8
SNMPv2-SMI::enterprises.25506.2.6.1.1.1.1.6.8 = INTEGER: 7`

Slot 1 CPU usage:
       7% in last 5 seconds
 `snmpbulkwalk -OUneb -v2c -c COMMUNITY host-hp1910 .1.3.6.1.4.1.25506.2.6.1.1.1.1.8.8
.1.3.6.1.4.1.25506.2.6.1.1.1.1.8.8 = INTEGER: 41`

System Total Memory(bytes): 66360240
Total Used Memory(bytes): 27574976
Used Rate: 41%

Same OID for hp1920
`snmpbulkwalk -OUneb -v2c -c COMMUNITY host-hp1920 .1.3.6.1.4.1.25506.2.6.1.1.1.1.6.8
.1.3.6.1.4.1.25506.2.6.1.1.1.1.6.8 = INTEGER: 2`

Slot 1 CPU usage:
       2% in last 5 seconds

`snmpbulkwalk -OUneb -v2c -c COMMUNITY host-hp1920 .1.3.6.1.4.1.25506.2.6.1.1.1.1.8.8
.1.3.6.1.4.1.25506.2.6.1.1.1.1.8.8 = INTEGER: 41`

System Total Memory(bytes): 66211840
Total Used Memory(bytes): 27585120
Used Rate: 41%

**Comment by laf** [comment]
Please provide all the information asked for above.

**Comment by manyax** [comment]
hp1910
discovery http://pastebin.com/vahWCqkE
poller  http://pastebin.com/J9SRuBtz
snmpbulkwalk http://pastebin.com/4vywAA6C

hp1920
discovery http://pastebin.com/W46pmNHG
poller http://pastebin.com/WnywhtyG
snmpbulkwalk http://pastebin.com/gqV1ZLL7
