### ISSUE TITLE
Add support to graph CPU and memory utilization for HP 1910 and 1920.

### ISSUE THREAD

**Issue by manyax** [librenms/librenms#5666]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

==========================================================
Component | Version
--------- | -------
LibreNMS  | f828a927d2126d3b0805f6b7f975f39673303c6a
DB Schema | 157
PHP       | 5.4.16
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

I have several HP 1910 and 1920, is it possible to add CPU and memory graph?

hp1910
discovery http://pastebin.com/vahWCqkE
poller http://pastebin.com/J9SRuBtz
snmpbulkwalk http://pastebin.com/4vywAA6C

hp1920
discovery http://pastebin.com/W46pmNHG
poller http://pastebin.com/WnywhtyG
snmpbulkwalk http://pastebin.com/gqV1ZLL7

**Comment by laf** [comment]
Looks like the snmpwalks are missing all the info from  .1.3.6.1.4.1.25506.2 can you please re-run it with that oid.

**Comment by laf** [comment]
No further info provided
