### ISSUE TITLE
Improve /search/search=ipv4,6

### ISSUE THREAD

**Issue by sliddjur** [librenms/librenms#5670]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
```
Component | Version
--------- | -------
LibreNMS  | f828a927d2126d3b0805f6b7f975f39673303c6a
DB Schema | 157
PHP       | 5.5.14
MySQL     | 10.0.28-MariaDB
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.3
```
- [x] Please provide as much detail as possible.

Is it possible to get arp-discovered addresses searchable in /search/search=ipv4/ ?
And /search/search=ipv4/ seem to search for string rather than IP's. If I search for 172.16. I get all IP's starting with the given string, which means I potentially can find 65534 IP's. Can we rather search for a subnet with CIDR notation? Like 172.16.0.0/22

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-improve-search-search-ipv4-6/663
