### ISSUE TITLE
Support for new device, Fortinet WLAN Management controller 

### ISSUE THREAD

**Issue by sliddjur** [librenms/librenms#5671]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the Component | Version
```
--------- | -------
LibreNMS  | f828a927d2126d3b0805f6b7f975f39673303c6a
DB Schema | 157
PHP       | 5.5.14
MySQL     | 10.0.28-MariaDB
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.3
```

- [x] Please provide as much detail as possible.

My FortiWLC 50D is only detected as a generic device. These are the mib files that came with the device. Would like full support for this device, thanks.

[mibs.tar.gz](https://github.com/librenms/librenms/files/739243/mibs.tar.gz)

**Comment by laf** [comment]
You've not provided any of the information we ask for :(
