### ISSUE TITLE
Device request: Juniper WLC / Trapeze MX (MSS - Mobility System Software)

### ISSUE THREAD

**Issue by sirHulda** [librenms/librenms#5672]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | f828a927d2126d3b0805f6b7f975f39673303c6a
DB Schema | 157
PHP       | 5.6.29-0+deb8u1
MySQL     | 5.5.54-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

Trapeze mibs: [MX096103.mibs.zip](https://github.com/librenms/librenms/files/739284/MX096103.mibs.zip)
Juniper mibs: [WLC096103.mibs.zip](https://github.com/librenms/librenms/files/739271/WLC096103.mibs.zip)
[poller.txt](https://github.com/librenms/librenms/files/739273/poller.txt)
[discovery.txt](https://github.com/librenms/librenms/files/739276/discovery.txt)
[snmpbulkwalk.txt](https://github.com/librenms/librenms/files/739274/snmpbulkwalk.txt)

Hope there is nothing sensitive info left behind :)
I do not know the difference between the mibs. Looks like they are identical but i guess something differs

- [x] Please provide as much detail as possible.
Juniper bought Trapeze a while back and rebranded the devices. Some improvements has been done since then but no major changes.

The files represents a Juniper WLC880R with version 7.7 of the OS. SNMP walks from an WLC-V 9.6 can be provided if needed

.1.3.6.1.2.1.1.2.0 outputs an OID which represents:
Trapeze Mobility Exchange:
1.3.6.1.4.1.14525.3.1.1 = MX-20
1.3.6.1.4.1.14525.3.1.2 = MX-8
1.3.6.1.4.1.14525.3.1.3 = MX-400
1.3.6.1.4.1.14525.3.1.4 = MRX-2
1.3.6.1.4.1.14525.3.1.6 = MX-216
1.3.6.1.4.1.14525.3.1.7 = MX-200

Juniper WLC
.1.3.6.1.4.1.14525.3.3.1 = WLC880R
.1.3.6.1.4.1.14525.3.3.2 = WLC8
.1.3.6.1.4.1.14525.3.3.3 = WLC2
.1.3.6.1.4.1.14525.3.3.4 = WLC800R
.1.3.6.1.4.1.14525.3.3.5 = WLC2800
.1.3.6.1.4.1.14525.3.3.6 = WLC100
.1.3.6.1.4.1.14525.3.3.10 = WLC-V

Reference: https://kb.juniper.net/InfoCenter/index?page=content&id=KB20975 and trpz-reg-devices.my

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
Is this for two separate detections or one? If it's just one which should it be?

**Comment by sirHulda** [comment]
I guess it's just one detection. OS is MSS with Juniper branding. I have both Trapeze and Juniper equipment available for testing if needed

**Comment by murrant** [comment]
@sirHulda This controller does not have any APs attached, so we aren't seeing much useful data in the walk to analyze and add wireless sensors support.

**Comment by sirHulda** [comment]
@murrant Oh ok. Let me get a new walk for you. Perhaps i can get you remote access to a controller...

**Comment by laf** [comment]
@sirHulda Any joy with the walk?

**Comment by Rosiak** [comment]
No info, closing.
