### ISSUE TITLE
Not able to add few of Ubiquiti Switches to librenms.....

### ISSUE THREAD

**Issue by kanwarsing** [librenms/librenms#5681]
Hi Everyone,

I am trying to add Ubiquiti swtiches to the Librenms and while doing that i am able to add half of the Switches with no issue but other half of  Ubiquiti Switches giving me Errors like
 
"Could not connect, please check the snmp details and snmp reachability"
 "SNMP v1: No reply with community public"

I have Compared the configuration of working and Non-working Switches which is exactly same.
please suggest me the solution to this issue.....
Thanks

**Comment by murrant** [comment]
Did you try SNMPv2?

**Comment by laf** [comment]
Please use community.librenms.org or IRC for general help on things.
