### ISSUE TITLE
ZTE-ZXR10 showing 4094 VLANs

### ISSUE THREAD

**Issue by manyax** [librenms/librenms#5684]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

==========================================================
Component | Version
--------- | -------
LibreNMS  | 94bdff3b86e7a5d1e4f213ec8066349286de190e
DB Schema | 157
PHP       | 5.4.16
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

When I press the VLAN button I get all 4094 vlans, even though I only have 2 3 VLANs defined. Can this be filtered somehow.
Is it possible to add CPU, memory and temperature graph for this device ?

poller http://pastebin.com/EtxWm77T
snmpbulkwalk http://pastebin.com/RpDNaYNY

discovery [discovery-ZTE-ZXR10.zip](https://github.com/librenms/librenms/files/741336/discovery-ZTE-ZXR10.zip)

**Comment by laf** [comment]
Please create a separate issue for cpu/mem/temp graphs adding.

**Comment by laf** [comment]
From this output I can only see one vlan:

dot1qVlanStaticName.41 = TestNet

What others are in use?

**Comment by manyax** [comment]
4094 VLAN are shown on the VLAN section on this device. So If I use vlan search plugin, all VLAN will be present on this device. Can this be filtered out ?

![zte](https://cloud.githubusercontent.com/assets/8913821/22865657/14d5f6fe-f169-11e6-842b-383055e819f2.png)

**Comment by laf** [comment]
Sorry my response was in reply to you saying 2/3 vlans configured. I can only see one in that output.

**Comment by manyax** [comment]
I might have only one, I was probably talking about the other ZTE switches that I have in production.

**Comment by laf** [comment]
I don't have any devices that use Q-BRIDGE-MIB to be able to check into this further.

The only option we would have is to exclude entries where dot1qVlanStaticName is NULL. I don't know the wider impact in doing that.

I would say though this is a bug on your device and you should contact the vendor to get them to only return the vlans in use.

As the pastebin links have also been removed we can't look at the snmpwalk to see if we can do anything else to resolve this. Feel free to repaste them and we can re-open.
