### ISSUE TITLE
Enhancement Request: Only graph swap Mempools if there is actual swap space.

### ISSUE THREAD

**Issue by jquagga** [librenms/librenms#5692]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

```
==========================================================
Component | Version
--------- | -------
LibreNMS  | 7b45a23d57e463cec4486580094b3b76aa84dc25
DB Schema | 157
PHP       | 7.1.1
MySQL     | 10.1.21-MariaDB
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================
```
- [X] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

This isn't exactly device specific but I can provide SNMP dumps of a device with no swap if needed.  

- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

So I have a humble enhancement request.  On many systems, SNMP reports a swap Mempool even if the swap size is 0.  I don't have swap on any system, yet I have graphs for it on both my Linux machines and Edgerouters.  What I'd like to suggest is to add a check if the swap Mempool is 0 during discovery and if so, don't poll / graph it.  Or alternatively if there is a desire to keep polling it in case swap appears or is added, then I was hoping it was possible to not graph it if there was none available.  I wasn't able to figure out how the discovery code worked exactly to add this check myself. 

It's absolutely not a big deal.  It's just ... clutter on my dashboards.   

![screenshot-fs8](https://cloud.githubusercontent.com/assets/5832772/22467761/dc1d8108-e793-11e6-8830-ba8333b9a03c.png)

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/enhancement-request-only-graph-swap-mempools-if-there-is-actual-swap-space/662
