### ISSUE TITLE
 Feature Request: MTU mismatch tracker

### ISSUE THREAD

**Issue by wriedel** [librenms/librenms#5695]
Hi Folks,
not sure what you guys think but just had an idea if there is an easy way to get a dump of MTU mismatches? Maybe based on the Vlan_Search plugin we should know which MAC's belongs to which VLAN so we can match and highlight outliers?

Wolfgang

**Comment by laf** [comment]
Can you provide more info on how you think this should work and what data we would be looking up and comparing?

**Comment by crcro** [comment]
maybe from the neighbors adjacency, after that get mtu for those interfaces and compare?

**Comment by wriedel** [comment]
Hi laf,
in contrast to L3 there is no option for fragmentation on L2. Therefore for a given L2 "segment" like a p2p Link, tunnel or VLAN all L2 MTU sizes need to match. As I see we already pull the configured interface MTU size for Ports and visualize it underneath the MAC address in the GUI.
So we should have that data already, right?

Also it looks like that LibreNMS has some kind of basic topology understanding based on discovery (MAC or CDP/LLDP) and we should be able to query the database for all ports of a given "segement" like a VLAN and compare their configured MTU sizes.

Without having a complete topology understanding it may be hard to judge which port MTU is right or wrong but maybe as a start we can build a average and just call out the outliers?
e.g. If all my switch ports for VLAN 123 have a Jumbo MTU of 9200 but my Linux host attached to that VLAN 123 has just an MTU of 1500 this should raise a flag.
If I have a p2p link like a GRE over IPSEC tunnel and have an MTU of 1500 on one end and 1400 on the other, we should raise a inconsistency flag.
I think this may be an extension to show me all port for a given VLAN. Now show me all MTU for that VLAN and flag the once which deviate from the average.

**Comment by murrant** [comment]
@wriedel Your example shouldn't raise a flag in my opinion.  Switch ports with 9200 MTU and hosts with 1500 MTU is ok.  

As long as all endpoints (IP) in an L2 segment have matching MTU and the L2 transport is >= that MTU, everything is fine.  However, if you are sending traffic to the Internet, you'll want 1500 for IPv4.

How do you accurately discover an L2 segment?  I think that is the first problem to solve.
Then you will need to match the correct IP interface MTU and Ethernet interface MTU.
Then how do you determine interfaces that have Internet bound traffic?

**Comment by wriedel** [comment]
@murrant  I fully agree but I wanted to get started without over-complicating things day one. We already group devises into Network and Server so we could build some logic with >= based on this, right? Also let's focus on the L2 Ethernet interface MTU size first else you would need to parse device configs I guess?
I didn't intended to build a reasoning system but I guess there is also an option to utilize the Interface description TAG (CUST, TRANSIT, CORE,...) for that to determine where default MTU sizes are supposed to being used. In fact it's typically all traffic which is leaving the Datacenter which should use 1500 and most of the time MTU > 1500 is just being used inside the DC for backup and storage or within MPLS networks to accommodate the labels space. So people should already know what they're doing ;-)

**Comment by eikik87** [comment]
I think you can create alert that will check all ports for their MTU, And create few conditions that will also check what type of device it is. If MTU is <=1500 %% device is this specific type. For example if port ifAlias = MPLS.

**Comment by laf** [comment]
Moved to; https://community.librenms.org/t/feature-request-mtu-mismatch-tracker/661
