### ISSUE TITLE
Support Radio Capacity for single radio Unifi APs

### ISSUE THREAD

**Issue by mbwall** [librenms/librenms#5696]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
==========================================================
Component | Version
--------- | -------
LibreNMS  | eb82beef152fc836161542ec9e2bb53ce7d8c9d0
DB Schema | 157
PHP       | 7.0.15
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

disovery output: http://pastebin.com/zLN8pWDP
poller output: http://pastebin.com/d7GMHWej

- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Currently the Unifi poller assumes that devices have 2 radios.  Some APs however only have one (2.4GHz), and so the poller errors when trying to get the Radio Capacity for those devices.  

Notice in the poller output:
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: unifiRadioCuTotal.1

If the relevant portions are removed from /includes/polling/mib/ubnt-unifi-mib.inc.php then the result is accurate for a single radio:
unifiRadioCuTotal.0 = 13
unifiRadioCuSelfRx.0 = 3
unifiRadioCuSelfTx.0 = 8
unifiRadioOtherBss.0 = 0

This also means that the Wireless Clients graph always shows 2 Radios, even though the second one will always have values of 0.

I don't have an AP with 2 radios to test, but I think the number may be available by looking in unifiRadioTable ( .1.3.6.1.4.1.41112.1.6.1.1)

**Comment by geordish** [comment]
I'm looking for feedback on WiFi related stuff here:

https://community.librenms.org/t/improve-wifi-collection-and-graphing-code/453/2

Any chance of providing feedback?

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/improve-wifi-collection-and-graphing-code/453/4
