### ISSUE TITLE
ZTE ZXR10 cpu/mem/temp graph

### ISSUE THREAD

**Issue by manyax** [librenms/librenms#5706]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

==========================================================
Component | Version
--------- | -------
LibreNMS  | 94bdff3b86e7a5d1e4f213ec8066349286de190e
DB Schema | 157
PHP       | 5.4.16
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

Is it possible to add CPU, memory and temperature graph for this device ?

poller http://pastebin.com/EtxWm77T
snmpbulkwalk http://pastebin.com/RpDNaYNY

discovery [discovery-ZTE-ZXR10.zip](https://github.com/librenms/librenms/files/741336/discovery-ZTE-ZXR10.zip)

**Comment by geordish** [comment]
Your snmpwalk doesn't appear to have the full data. Did you copy it all?

If you did, try walking the following: .1.3.6.1.4.1.3902

**Comment by manyax** [comment]
[snmpb-ZTE-ZXR10.zip](https://github.com/librenms/librenms/files/750654/snmpb-ZTE-ZXR10.zip)
I thought I did , here it is
snmpbulkwalk -OUneb -v2c -c pass host .1.3.6.1.4.1.3902

**Comment by laf** [comment]
Pastes no longer valid, please provide up to date data.
