### ISSUE TITLE
[bug ?] mouseover popover mini graphs show a non-existent data on Cisco WLC

### ISSUE THREAD

**Issue by johnplv** [librenms/librenms#5708]
I just added the device Cisco WLC 2504, but the mouseover popover mini graphs already shown some data

![wlc-1](https://cloud.githubusercontent.com/assets/7622693/22504879/9f957e10-e889-11e6-800a-6f4a5bb2aec3.png)

Component | Version
--------- | -------
LibreNMS  | 5326cb3bd5745921d686abebb9df26ec4e0c418c
DB Schema | 157
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.28-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
This is simply that a device with the exact same hostname has been added before.

**Comment by johnplv** [comment]
The device is added by ip address
Devices with the same address and name was not used.

**Comment by laf** [comment]
I can say with absolute certainty that the device with same name or ip has been added before. We have code that populates data. If you want to discuss this further pls do so on irc or the community site
