### ISSUE TITLE
Device request: Add support for DASAN Zhone Solutions Switch V2224G-OP

### ISSUE THREAD

**Issue by lsfib** [librenms/librenms#5712]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hello,

Please add to librenms system support for DASAN Zhone Solutions GPON OLT V8102 (simmilar to already added V8240 and V5812G)

Commands output:
Discovery -> http://pastebin.com/DgXhdtYL
Poller -> http://pastebin.com/F6WLauN0
SNMPwalk -> http://pastebin.com/YyRRu1Lu

SWITCH(config)# sh system

          SysInfo(System Information)
     Model Name          : V2224G-OP
     Main Memory Size    : 256 MB
     Flash Memory Size   : 32 MB
     H/W Revision        : DS-C4-38E-A1
     H/W Address         : 00:d0:cb:d8:24:de
     RTC Information     : M41T11
     Serial Number       : MD3RRRG092A0058
     S/W Compatibility   : 4, 3
     NOS Version         : 2.14
     B/L Version         : 01.17.0003
     PLD Version         : 0x08

**Comment by geordish** [comment]
This also seems to be detected fine, what issues are you having?

**Comment by laf** [comment]
No further info provided and device is detected fine.

**Comment by lsfib** [comment]
Sorry, for lack of information from my side.
First time when I had added Switch - on graphs I can see only errors.
I have libreNMS on virtualbox.
But now after weekend it is OK - sorry for wrong info.

One thing strange for me is - why Switch is detected as Server?

**Comment by laf** [comment]
The device is definitely marked as a network device, maybe you've overridden the type in edit device for this one?

**Comment by lsfib** [comment]
Yes, my mistake - thank You.
Sorry, it is new system for my and simple mistake happen.

Thank You one more time for support!
