### ISSUE TITLE
Old map links broken

### ISSUE THREAD

**Issue by sivadm** [librenms/librenms#5716]
I am having a problem with the device map links. After clicking on a device and going to its map, if I try to go to another device by its link on this page, it does not prepend the link with the server and just tries to go to /device/device=xx/tab=map. This happens in Firefox, Chrome, and I even tried IE and Edge (Edge was the fastest of all of them) but none treated them differently. Inspecting the items in firefox showed that these links were //device/device=xx/tab=map. I like this map better than the new one and would like the device links to work. Is there a known fix/workaround?

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the 

Component | Version
--------- | -------
LibreNMS  | 0240a95e627873add673055199d43439986632c9
DB Schema | 157
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [X] This issue is for a WebUI fix or feature 
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
Do you have `$config['base_url']` set in config.php to something other than `/`?

**Comment by sivadm** [comment]
I am not.

**Comment by laf** [comment]
You need to set that variable to be your full path to the install like `$config['base_url'] = 'https://mydomain.com/';`

**Comment by sivadm** [comment]
When I do that everything breaks....

**Comment by laf** [comment]
What do you mean everything breaks? If it does it's most likely because you aren't specifying your actual base url.

**Comment by sivadm** [comment]
Got it.
