### ISSUE TITLE
New installation according to instructions has bad database, unfunctional

### ISSUE THREAD

**Issue by DaSpawn** [librenms/librenms#5720]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

I just installed per your instructions at http://docs.librenms.org/Installation/Installation-Ubuntu-1604-Nginx/

- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | ba2f88ee72f198b3ced1897a9aaa274a6191502c
DB Schema | 157
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

[OK]    Database connection successful
[FAIL]  Discovery has never run, check the cron job
[FAIL]  The poller has never run, check the cron job

- [X] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.

After installing on Ubuntu 16.04.1 LTS just now, I attempted to run the validate script and receieved the errors above.  The crons have not run yet of course as I just installed the system.  I attempted to run the first cron entry manually (/opt/librenms/discovery.php -h all) and the process runs and begins to update databse schema (there was no instructions for installing database so I assumed this would install it).  After getting through 000-157 the discovery completes and (some of the schema changes have errors).  

now if I run validate again I get the same error that discovery/cron has not run, so I tried to do the discovery again and the entire schema process happens yet again.  I tried other cron entries and they fail saying devices table does not exist.

The only SQL data I can find (besides the schema updates) is build.sql;  I tried using that first and made no difference

Is there something missing from the instructions? did I miss something? 

- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
GitHub isn't for general support, please use our irc channel or the community site.

Having said that, it seems like you haven't followed the install instructions so revisit those first.

**Comment by DaSpawn** [comment]
this is not a request for general support, I followed the instructions twice with the same result, I would have not filed this bug report if I did not; the directions were clear to begin with to use the irc channel for support.

**Comment by laf** [comment]
There is no changes between those two versions related to any db / setup.

As for the docs, we aren't missing php build-base.php as it's not a requirement. If you follow the install instructions from start to finish you will get a full populated database and not by magic.

**Comment by DaSpawn** [comment]
of course the database is not populated by magic, it is supposed to be populated when discovery runs but it does not populate a complete properly functioning database, no need to be a condescending, I am trying to report problems with your product and you are treating me like an idiot

I followed the install instructions for Ubuntu 16.04 fully twice and as you said I expected the database to be installed automatically since there was no instructions to do otherwise.  After I ran php build-base.php the system began running fully as expected and I have been able to populate data and the system has been running fine since

you keep ignoring what I am saying insisting there is no problem when there IS a problem if you say that command is not needed and a properly functioning system can not be installed without it (the discovery script keeps starting from schema update 000 every time it is run, but you do not see that or the other error since you pipe all output to null in cron)

the problem the version change fixed was the errors running one of the cron components.  That update fixed those errors which were unrelated to the install problems

I left Observium after customizing (writing MIB processors) and using for years due to how users were treated and ignored, I am wondering if I have made a mistake now

**Comment by laf** [comment]
I don't keep ignoring you, you aren't listening to what I've said. The install instructions are complete and you end up with a fully populated db. This doesn't need discovery or build-base to run, it's taken care of in the web installer.

I've asked you not to use github issues for help, you can feel free to think you are being hard done by but this isn't a support channel here. Discuss on one of the above mentioned mediums and if it turns out to be a bug we can open an issue.

**Comment by laf** [comment]
Oh and just to clarify, users aren't ignored here - take a look at irc, github and the community site, god even outside things like Reddit. Pretty much every single person gets responses and none of them are abusive.

Helping with LibreNMS is a tireless thing to do so if as a user you wouldn't mind actually helping us out by asking for support where we say then things would go a lot smoother.  You can continue to :-1: my responses, it fills me full of joy whilst I continue to help where I can.
