### ISSUE TITLE
Cisco Wireless (2702i's specifically) AP graphs are gone

### ISSUE THREAD

**Issue by ipguru99** [librenms/librenms#5725]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 6bc7b1991e3602675364186aac35962ec038d114
DB Schema | 157
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.28-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

A while ago (sorry, I can't remember the date, it was in irc), I got a hint as to where the Cisco wireless php file was kept and I could put a line in there to make "Wireless" appear in the Graphs section. I think I even opened an issue here (I will try to go back and find that) about Cisco wireless controllers (in the 3850 gear). 

All of the sudden, I was able to just add the AP's and get a wireless clients graph, so I didn't think about it anymore. 

Today, I just added a site with 15 of those 2702's (those were the ones I originally asked about.. as they were connecting to the 3850 and I was looking for support for the 3850's.. that is when I realized I could just add snmp to the 2702's and have them report back wireless clients). 

Anyway, today, I added them and they all selected Network as their Type. I changed them to Wireless and I still don't have a graph for wireless clients. I also went back into the original site.. and those graphs are gone. Click on the Device, Graphs (available now is Netstats,System,Poller). That is where Wireless used to be. 

I have verified the module (wifi) is in the On position. 

Anything else I can help provide, please let me know. This was definitely working at one point. Thanks!!

**Comment by ipguru99** [comment]
Not sure if I am supposed to edit (or post a reply to my own post). Here was the original issue. 

https://github.com/librenms/librenms/issues/3238

But, as I said in the long original post, I didn't really think about it any more.. because it was working. Thanks!

**Comment by laf** [comment]
You need to provide all the info asked for above.

**Comment by ipguru99** [comment]
Sorry about that.. Here is the needed info:

http://pastebin.com/QLEaCv8A - that is discovery
http://pastebin.com/GEq3TpvD - that is poller
http://pastebin.com/eQekujFw - that is snmp

Let me know if I need anything else. This customer has hundreds of 1242's.. and those work great. The 2700's just stopped recently.. 6 months ago it worked for sure.. Thanks!!

**Comment by Rosiak** [comment]
From your poller log, it seems like the device is not returning values.
I can confirm that this works fine on AIR-CAP3702I-E-K9/15.3(3)JD (K9W7)
```
#### Load poller module wifi ####
Checking Aironet Wireless clients... SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -OUqnv -m CISCO-DOT11-ASSOCIATION-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:HOSTNAME:161 cDot11ActiveWirelessClients.1]
No Such Object available on this agent at this OID
 
SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -OUqnv -m CISCO-DOT11-ASSOCIATION-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:HOSTNAME:161 cDot11ActiveWirelessClients.2]
No Such Object available on this agent at this OID
 
0 clients on dot11Radio0, 0 clients on dot11Radio1
 
>> Runtime for poller module 'wifi': 0.0806 seconds
#### Unload poller module wifi ####
```

**Comment by ipguru99** [comment]
Great.. what do I do now? My 2702's are AIR-CAP2702I-A-K9/15.3(3)JN8 (K9W8). I am getting them off the hundreds of 1242's they have (so far I am loving the 2700's). 

The ones that were reporting clients have not moved off their version (same version.. that is why I was telling them to roll out that version) and now they don't work.. so I know something has changed. 

Anything I can do to help discover why this MIB reports nothing?

**Comment by ipguru99** [comment]
Thank you very much Rosiak!! I just looked up 15.3(3)JN8.. it doesn't have the CISCO-DOT11-ASSOCIATION-MIB.. The image you listed for the 2700's does have it. So they must have changed the code on the 3850 controller.. or something!

Thanks.. funny how the JD has it (which is older) and the newer (JNP) also has it.. but the JN series doesn't. Thanks a lot Cisco!! Thanks again to you sir!!
