### ISSUE TITLE
Dashboard - Worldmaps not showing any devices

### ISSUE THREAD

**Issue by wriedel** [librenms/librenms#5727]
Hi Folks,
I have proper syslocation tags [49.5981, 10.9463] which work pretty well inside the device view (Lat / Lng) and clicking on the Map icon point to the right location.

Nevertheless I can't get any devices show up on Worldmap?
Not sure if I am missing something or is there is a bug?

I have the following in config.php
// ----------------------------------
# Leaflet config
$config['map']['engine']                  = "leaflet";
$config['leaflet']['default_lat']         = "49.5981";
$config['leaflet']['default_lng']         = "10.9463";
$config['leaflet']['default_zoom']        = 10;

Thank you,
Wolfgang
==========================================================
Component | Version
--------- | -------
LibreNMS  | 9f8f8b6c263fcaff0864467de8a08b8925ca4592
DB Schema | 157
PHP       | 7.0.14-2
MySQL     | 10.2.3-MariaDB-10.2.3+maria~sid-log
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================

[OK]    Database connection successful
[WARN]  Your local git contains modified files, this could prevent automatic updates.
Modified files:
         includes/discovery/sensors/current/apc.inc.php
         includes/discovery/sensors/load/apc.inc.php
         includes/discovery/sensors/voltages/apc.inc.php

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by sliddjur** [comment]
I had this problem long time ago. The problem was that the database table was encoded in the wrong LANG or something.

**Comment by wriedel** [comment]
@sliddjur do you rember some more details ;-)

I just checked and my database has utf8_general_ci, the dashboard table utf8_general_ci and the widgets table latin1_swedish_ci but I have no idea why.
I changed the widgets table also to utf8_general_ci but still the same issue.
Anyone any idea how I can drill down on this issue?
Thank you,
Wolfgang

**Comment by laf** [comment]
Can you run this mysql query to see if you get data back:

<pre>SELECT DISTINCT(`device_id`),`devices`.`location`,`hostname`,`os`,`status`,`lat`,`lng` FROM `devices`
                    LEFT JOIN `locations` ON `devices`.`location`=`locations`.`location`
                    WHERE `disabled`=0 AND `ignore`=0 AND ((`lat` != '' AND `lng` != '') OR (`devices`.`location` REGEXP '\[[0-9\.\, ]+\]'))
                      AND `status` IN (0,1)
                    ORDER BY `status` ASC, `hostname`;</pre>

**Comment by wriedel** [comment]
here we go:


MariaDB [libre_db]> SELECT DISTINCT(`device_id`),`devices`.`location`,`hostname`,`os`,`status`,`lat`,`lng` FROM `devices` LEFT JOIN `locations` ON `devices`.`location`=`locations`.`location` WHERE `disabled`=0 AND `ignore`=0 AND ((`lat` != '' AND `lng` != '') OR (`devices`.`location` REGEXP '\[[0-9\.\, ]+\]')) AND `status` IN (0,1) ORDER BY `status` ASC, `hostname`;

ERROR 1267 (HY000): Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '='

MariaDB [libre_db]> SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_COLLATION FROM INFORMATION_SCHEMA.TABLES;

+---------------+--------------------+----------------------------------------------------+-------------------+
| TABLE_CATALOG | TABLE_SCHEMA       | TABLE_NAME                                         | TABLE_COLLATION   |
+---------------+--------------------+----------------------------------------------------+-------------------+
| def           | libre_db           | access_points                                      | utf8_general_ci   |
| def           | libre_db           | alert_log                                          | utf8_general_ci   |
| def           | libre_db           | alert_map                                          | utf8_general_ci   |
| def           | libre_db           | alert_rules                                        | utf8_general_ci   |
| def           | libre_db           | alert_schedule                                     | utf8_general_ci   |
| def           | libre_db           | alert_schedule_items                               | utf8_general_ci   |
| def           | libre_db           | alert_template_map                                 | utf8_general_ci   |
| def           | libre_db           | alert_templates                                    | utf8_general_ci   |
| def           | libre_db           | alerts                                             | utf8_general_ci   |
| def           | libre_db           | api_tokens                                         | utf8_general_ci   |
| def           | libre_db           | applications                                       | utf8_general_ci   |
| def           | libre_db           | authlog                                            | utf8_general_ci   |
| def           | libre_db           | bgpPeers                                           | utf8_general_ci   |
| def           | libre_db           | bgpPeers_cbgp                                      | utf8_general_ci   |
| def           | libre_db           | bill_data                                          | utf8_general_ci   |
| def           | libre_db           | bill_history                                       | utf8_general_ci   |
| def           | libre_db           | bill_perms                                         | utf8_general_ci   |
| def           | libre_db           | bill_port_counters                                 | utf8_general_ci   |
| def           | libre_db           | bill_port_counters_tmp                             | utf8_general_ci   |
| def           | libre_db           | bill_ports                                         | utf8_general_ci   |
| def           | libre_db           | bills                                              | utf8_general_ci   |
| def           | libre_db           | callback                                           | utf8_general_ci   |
| def           | libre_db           | cef_switching                                      | utf8_general_ci   |
| def           | libre_db           | ciscoASA                                           | utf8_general_ci   |
| def           | libre_db           | cmpMemPool                                         | utf8_general_ci   |
| def           | libre_db           | component                                          | utf8_general_ci   |
| def           | libre_db           | component_prefs                                    | utf8_general_ci   |
| def           | libre_db           | component_statuslog                                | utf8_general_ci   |
| def           | libre_db           | config                                             | utf8_general_ci   |
| def           | libre_db           | current                                            | utf8_general_ci   |
| def           | libre_db           | customers                                          | utf8_general_ci   |
| def           | libre_db           | dashboards                                         | utf8_general_ci   |
| def           | libre_db           | dbSchema                                           | utf8_general_ci   |
| def           | libre_db           | device_graphs                                      | utf8_general_ci   |
| def           | libre_db           | device_group_device                                | utf8_general_ci   |
| def           | libre_db           | device_groups                                      | utf8_general_ci   |
| def           | libre_db           | device_mibs                                        | utf8_general_ci   |
| def           | libre_db           | device_oids                                        | utf8_general_ci   |
| def           | libre_db           | device_perf                                        | utf8_general_ci   |
| def           | libre_db           | devices                                            | utf8_general_ci   |
| def           | libre_db           | devices_attribs                                    | utf8_general_ci   |
| def           | libre_db           | devices_perms                                      | utf8_general_ci   |
| def           | libre_db           | entPhysical                                        | utf8_general_ci   |
| def           | libre_db           | entPhysical_state                                  | utf8_general_ci   |
| def           | libre_db           | eventlog                                           | utf8_general_ci   |
| def           | libre_db           | fanspeed                                           | utf8_general_ci   |
| def           | libre_db           | frequency                                          | utf8_general_ci   |
| def           | libre_db           | graph_types                                        | utf8_general_ci   |
| def           | libre_db           | graph_types_dead                                   | utf8_general_ci   |
| def           | libre_db           | hrDevice                                           | utf8_general_ci   |
| def           | libre_db           | ipsec_tunnels                                      | utf8_general_ci   |
| def           | libre_db           | ipv4_addresses                                     | utf8_general_ci   |
| def           | libre_db           | ipv4_mac                                           | utf8_general_ci   |
| def           | libre_db           | ipv4_networks                                      | utf8_general_ci   |
| def           | libre_db           | ipv6_addresses                                     | utf8_general_ci   |
| def           | libre_db           | ipv6_networks                                      | utf8_general_ci   |
| def           | libre_db           | juniAtmVp                                          | utf8_general_ci   |
| def           | libre_db           | links                                              | utf8_general_ci   |
| def           | libre_db           | loadbalancer_rservers                              | utf8_general_ci   |
| def           | libre_db           | loadbalancer_vservers                              | utf8_general_ci   |
| def           | libre_db           | locations                                          | utf8_general_ci   |
| def           | libre_db           | mac_accounting                                     | utf8_general_ci   |
| def           | libre_db           | mempools                                           | utf8_general_ci   |
| def           | libre_db           | mibdefs                                            | utf8_general_ci   |
| def           | libre_db           | munin_plugins                                      | utf8_general_ci   |
| def           | libre_db           | munin_plugins_ds                                   | utf8_general_ci   |
| def           | libre_db           | netscaler_vservers                                 | utf8_general_ci   |
| def           | libre_db           | notifications                                      | utf8_general_ci   |
| def           | libre_db           | notifications_attribs                              | utf8_general_ci   |
| def           | libre_db           | ospf_areas                                         | utf8_general_ci   |
| def           | libre_db           | ospf_instances                                     | utf8_general_ci   |
| def           | libre_db           | ospf_nbrs                                          | utf8_general_ci   |
| def           | libre_db           | ospf_ports                                         | utf8_general_ci   |
| def           | libre_db           | packages                                           | utf8_general_ci   |
| def           | libre_db           | perf_times                                         | utf8_general_ci   |
| def           | libre_db           | plugins                                            | utf8_general_ci   |
| def           | libre_db           | poller_groups                                      | utf8_general_ci   |
| def           | libre_db           | pollers                                            | utf8_general_ci   |
| def           | libre_db           | port_association_mode                              | utf8_general_ci   |
| def           | libre_db           | port_in_measurements                               | utf8_general_ci   |
| def           | libre_db           | port_out_measurements                              | utf8_general_ci   |
| def           | libre_db           | ports                                              | utf8_general_ci   |
| def           | libre_db           | ports_adsl                                         | utf8_general_ci   |
| def           | libre_db           | ports_perms                                        | utf8_general_ci   |
| def           | libre_db           | ports_stack                                        | utf8_general_ci   |
| def           | libre_db           | ports_statistics                                   | utf8_general_ci   |
| def           | libre_db           | ports_stp                                          | utf8_general_ci   |
| def           | libre_db           | ports_vlans                                        | utf8_general_ci   |
| def           | libre_db           | processes                                          | utf8_general_ci   |
| def           | libre_db           | processors                                         | utf8_general_ci   |
| def           | libre_db           | proxmox                                            | utf8_general_ci   |
| def           | libre_db           | proxmox_ports                                      | utf8_general_ci   |
| def           | libre_db           | pseudowires                                        | utf8_general_ci   |
| def           | libre_db           | route                                              | utf8_general_ci   |
| def           | libre_db           | sensors                                            | utf8_general_ci   |
| def           | libre_db           | sensors_to_state_indexes                           | utf8_general_ci   |
| def           | libre_db           | services                                           | utf8_general_ci   |
| def           | libre_db           | session                                            | utf8_general_ci   |
| def           | libre_db           | slas                                               | utf8_general_ci   |
| def           | libre_db           | state_indexes                                      | utf8_general_ci   |
| def           | libre_db           | state_translations                                 | utf8_general_ci   |
| def           | libre_db           | storage                                            | utf8_general_ci   |
| def           | libre_db           | stp                                                | utf8_general_ci   |
| def           | libre_db           | syslog                                             | utf8_general_ci   |
| def           | libre_db           | toner                                              | utf8_general_ci   |
| def           | libre_db           | ucd_diskio                                         | utf8_general_ci   |
| def           | libre_db           | users                                              | utf8_general_ci   |
| def           | libre_db           | users_prefs                                        | utf8_general_ci   |
| def           | libre_db           | users_widgets                                      | utf8_general_ci   |
| def           | libre_db           | vlans                                              | utf8_general_ci   |
| def           | libre_db           | vminfo                                             | utf8_general_ci   |
| def           | libre_db           | voltage                                            | utf8_general_ci   |
| def           | libre_db           | vrf_lite_cisco                                     | utf8_general_ci   |
| def           | libre_db           | vrfs                                               | utf8_general_ci   |
| def           | libre_db           | widgets                                            | utf8_general_ci   |

**Comment by wriedel** [comment]
and I have something similar in my librenms.log

/opt/librenms/poller.php 31 2017-02-collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '=' (SELECT DISTINCT(`device_id`),`devices`.`location`,`hostname`,`os`,`status`,`lat`,`lng` FROM `devices`
                    LEFT JOIN `locations` ON `devices`.`location`=`locations`.`location`
                    WHERE `disabled`=0 AND `ignore`=0 AND ((`lat` != '' AND `lng` != '') OR (`devices`.`location` REGEXP '\[[0-9\.\, ]+\]'))
                      AND `status` IN (0,1)
                    ORDER BY `status` ASC, `hostname`)

**Comment by laf** [comment]
```
show create table locations;
show create table devices;
```

**Comment by wriedel** [comment]
MariaDB [(none)]> use libre_db
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [libre_db]> show create table locations;
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table     | Create Table                                                                                                                                                                                                                                                         |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| locations | CREATE TABLE `locations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `location` text NOT NULL,
  `lat` float(10,6) NOT NULL,
  `lng` float(10,6) NOT NULL,
  `timestamp` datetime NOT NULL,
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8 |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

MariaDB [libre_db]> show create table devices;
+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table   | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| devices | CREATE TABLE `devices` (
  `device_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `hostname` varchar(128) CHARACTER SET latin1 NOT NULL,
  `sysName` varchar(128) CHARACTER SET latin1 DEFAULT NULL,
  `ip` varbinary(16) DEFAULT NULL,
  `community` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `authlevel` enum('noAuthNoPriv','authNoPriv','authPriv') CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `authname` varchar(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `authpass` varchar(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `authalgo` enum('MD5','SHA') CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `cryptopass` varchar(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `cryptoalgo` enum('AES','DES','') DEFAULT NULL,
  `snmpver` varchar(4) CHARACTER SET latin1 NOT NULL DEFAULT 'v2c',
  `port` smallint(5) unsigned NOT NULL DEFAULT 161,
  `transport` varchar(16) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'udp',
  `timeout` int(11) DEFAULT NULL,
  `retries` int(11) DEFAULT NULL,
  `bgpLocalAs` varchar(16) CHARACTER SET latin1 DEFAULT NULL,
  `sysObjectID` varchar(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `sysDescr` text CHARACTER SET latin1 DEFAULT NULL,
  `sysContact` text CHARACTER SET latin1 DEFAULT NULL,
  `version` text CHARACTER SET latin1 DEFAULT NULL,
  `hardware` text CHARACTER SET latin1 DEFAULT NULL,
  `features` text CHARACTER SET latin1 DEFAULT NULL,
  `location` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `os` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `status` tinyint(4) NOT NULL DEFAULT 0,
  `status_reason` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `ignore` tinyint(4) NOT NULL DEFAULT 0,
  `disabled` tinyint(1) NOT NULL DEFAULT 0,
  `uptime` bigint(20) DEFAULT NULL,
  `agent_uptime` int(11) NOT NULL DEFAULT 0,
  `last_polled` timestamp NULL DEFAULT NULL,
  `last_poll_attempted` timestamp NULL DEFAULT NULL,
  `last_polled_timetaken` double(5,2) DEFAULT NULL,
  `last_discovered_timetaken` double(5,2) DEFAULT NULL,
  `last_discovered` timestamp NULL DEFAULT NULL,
  `last_ping` timestamp NULL DEFAULT NULL,
  `last_ping_timetaken` double(5,2) DEFAULT NULL,
  `purpose` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `type` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `serial` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `icon` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `poller_group` int(11) NOT NULL DEFAULT 0,
  `override_sysLocation` tinyint(1) DEFAULT 0,
  `notes` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `port_association_mode` int(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`device_id`),
  KEY `status` (`status`),
  KEY `hostname` (`hostname`),
  KEY `sysName` (`sysName`),
  KEY `os` (`os`),
  KEY `last_polled` (`last_polled`),
  KEY `last_poll_attempted` (`last_poll_attempted`)
) ENGINE=InnoDB AUTO_INCREMENT=85 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC |
+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by laf** [comment]
Try this; `ALTER TABLE `locations` CHANGE `location` `location` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;`

**Comment by wriedel** [comment]
@laf OK did some more research on this as I had been running into issues with the syslog table afterwards: MySQL Error: MySQL server has gone away (INSERT INTO `syslog`?
Looks like being common sense to use:
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci

So I made the following changes:
# /etc/mysql/my.conf
#
[client]
default-character-set=utf8mb4
# 
[mysqld]
init_connect         ='SET collation_connection = utf8mb4_unicode_ci'
character_set_server = utf8mb4
collation_server     = utf8mb4_unicode_ci
skip-character-set-client-handshake
# 
[client]
default-character-set = utf8mb4
# 
[mysqld]
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
#
[mysql]
default-character-set = utf8mb4

and altered the database with a bash script:

# dump current database:
mysqldump -u$dbUser -p$dbPasswd libre_db > $db.sql      

var=$(mysql -e 'SELECT CONCAT("ALTER TABLE ", TABLE_NAME," CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;") AS execTabs FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA="libre_db" AND TABLE_TYPE="BASE TABLE"' -u$dbUser -p$dbPasswd )
var+='ALTER DATABASE $db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
echo $var | cut -d " " -f2- | mysql -u$dbUser -p$dbPasswd $db

# check for success
# use $db
# SHOW VARIABLES LIKE 'char%'; SHOW VARIABLES LIKE 'collation%';
mysql -u$dbUser -p$dbPasswd

Now everything looks good and I get syslog as also Worldmap working.
