### ISSUE TITLE
Feature Request - Devices Notes - Only Administrators can use the 'Notes'. 

### ISSUE THREAD

**Issue by eikik87** [librenms/librenms#5729]
I have first level support actively monitoring the 'Alert list', and if they check the alert they can create a trouble ticket about the case. But then they will 'Acknowledge' the alert so it is not in the alert list anymore. And they would write what they did about the alert under 'Notes'. Problem is only Administrators seem to be able to use the 'Notes' section.

This would really help them manage the alert list and people can know the reason why some Alert is 'acknowledged' directly in Librenms system.

**Comment by Rosiak** [comment]
I belive the notes field shouldn't be used for this purpose, what I would rather see is a 'ack' comment section or similar(Could be a feature request).

That said, Global Read users should not be able to anything other than.. read.

**Comment by eikik87** [comment]
We do use another SNMP tool. There are few levels of users. Operator, then Operator 'edit'. I believe that might also be usefull. But if you are working on a NOC or first level support, it is really nice to be able to write notes for each alert or device. This is something that is allowed in our other monitoring tool and helps our support managing the alerts.

**Comment by eikik87** [comment]
But it is up too you if you look at this as a problem or feature request. There are three ways of looking at this.

1. Feature request - Adding another option for 'Global Read' user so he can put little comments next to alerts in order to manage them easier and say what has been done in order to tackle this alert. Or adding more option for user access control.

2. Issue - As this was originally designed this way, most likely for the same reason I'm requesting this too you. As people most of the time have more then 1 people operating in the system and require a way to communicate between each other how they have tackled the alert. Not everybody are a small office with 1 administrator that is the only one watching the alert list. 

3. You can ignore it and keep it this way. But IMO then you don't have much touch into the NOC/First level support.

**Comment by Rosiak** [comment]
@librenms/reviewers ?

**Comment by f0o** [comment]
I agree with @Rosiak about this.
Adding an Ack-Comment would make more sense than allowing Global-Read to have Write privileges (no matter of what kind).

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-devices-notes-only-administrators-can-use-the-notes/660
