### ISSUE TITLE
Device request: Add support for ZyXEL XS3700-24

### ISSUE THREAD

**Issue by millosz222** [librenms/librenms#5730]
Product Model           : XS3700-24
System Name             : XS3700
System Mode             : Standalone
System Location         : Trzciana
System up Time          :   827:24:52 (b18b3c04 ticks)
Bootbase Version        : V1.02 | 08/27/2014
ZyNOS F/W Version       : V4.30(AASS.0) | 07/07/2016
Config Boot Image       : 1
Current Boot Image      : 1
Current Configuration   : 1
RomRasSize              : 8637948

validate
http://pastebin.com/rGWtqSQE

poller
http://pastebin.com/7nhpbR3F

discovery
http://pastebin.com/YsS4W24n

snmp 
https://www.dropbox.com/s/xpbqx2rw64mpd28/snmp%20zyxel.txt?dl=0

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by millosz222** [comment]
we cant monitor processor and memory usage?

**Comment by laf** [comment]
Classing as a duplicate for #5292. Pr is in the queue so should be available soon
