### ISSUE TITLE
Template title does not parse {if} statement

### ISSUE THREAD

**Issue by towster** [librenms/librenms#5731]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

==========================================================
Component | Version
--------- | -------
LibreNMS  | f22f3211d505b0ab69f6e6e6dd439daf9321cdc7
DB Schema | 157
PHP       | 7.0.14
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

I had set alert title to be:
NMS: ALERT %sysName %hostname {if %name}%name{else}%rule{/if}

Title recieved:
NMS: ALERT vg350_telco_01 10.21.33.231 {if Devices up/down}Devices
up/down{else}%macros.device_down = "1"          {/if}

**Comment by laf** [comment]
I don't think you can do conditions in the titles

**Comment by towster** [comment]
I changed my title to simply be:
NMS: ALERT %sysName %hostname %name

**Comment by laf** [comment]
Can we close this then?
