### ISSUE TITLE
Add suport a new device TiMOS, Nokia 7750

### ISSUE THREAD

**Issue by aplalmeida** [librenms/librenms#5733]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run 
from the cli.

Component | Version
--------- | -------
LibreNMS  | f22f3211d505b0ab69f6e6e6dd439daf9321cdc7
DB Schema | 157
PHP       | 5.5.9-1ubuntu4.20
MySQL     | 10.1.19-MariaDB-1~trusty
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
./discovery.php -h HOSTNAME -d
http://pastebin.com/Gsspnazw

./poller.php -h HOSTNAME -r -f -d
http://pastebin.com/saGYggBJ

snmpbulkwalk
https://gist.github.com/aplalmeida/bda109b655bd578b1e847babd94a53ad

- [ ] Please provide as much detail as possible.

add support memory, cpu and disk to this device.

- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by aplalmeida** [comment]
@laf I saw that device has two controllers Active/Standby, maybe this information can help us.

**Comment by Rosiak** [comment]
Can you check if the device responds on these oids:
1.3.6.1.4.1.6527.3.1.2.1.1.1.0
1.3.6.1.4.1.6527.3.1.2.1.1.2.0
1.3.6.1.4.1.6527.3.1.2.1.1.3.0
1.3.6.1.4.1.6527.3.1.2.2.1.8.1.18.0
1.3.6.1.4.1.6527.3.1.2.2.1.8.1.24.0

If not, would it be possible to grant SNMP read access?

**Comment by Rosiak** [comment]
No response, closing.

**Comment by aplalmeida** [comment]
Sorry for delay, I don't if is possible, but bellow de outputs.
1.3.6.1.4.1.6527.3.1.2.1.1.1.0  => iso.3.6.1.4.1.6527.3.1.2.1.1.1.0 = 2
1.3.6.1.4.1.6527.3.1.2.1.1.2.0  => iso.3.6.1.4.1.6527.3.1.2.1.1.2.0 = 268898216
1.3.6.1.4.1.6527.3.1.2.1.1.3.0  => iso.3.6.1.4.1.6527.3.1.2.1.1.3.0 = 2998927360
1.3.6.1.4.1.6527.3.1.2.2.1.8.1.18.0  => iso.3.6.1.4.1.6527.3.1.2.2.1.8.1.18.0 = No Such Object available on this agent at this OID 1.3.6.1.4.1.6527.3.1.2.2.1.8.1.24.0  => iso.3.6.1.4.1.6527.3.1.2.2.1.8.1.24.0 = No Such Instance currently exists at this OID

**Comment by laf** [comment]
Can you please provide an snmpwalk of `1.3.6.1.4.1.6527.3.1.2`

**Comment by laf** [comment]
Feel free to post the info we need and we can re-open this.

**Comment by aplalmeida** [comment]
Sorry for delay, bellow the outputs

1.3.6.1.4.1.6527.3.1.2.1.1.1.0 => iso.3.6.1.4.1.6527.3.1.2.1.1.1.0 = 4

**Comment by laf** [comment]
That's not what we need, we need the full walk from;

`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME 1.3.6.1.4.1.6527.3.1.2`

**Comment by aplalmeida** [comment]
[Uploading bulk-timos.txt…](attach output)

**Comment by laf** [comment]
I'm submitting a PR that will add CPU/Mem support.

I can't find disk info in that output - if you would like further support for this device please provide MIBs.

**Comment by aplalmeida** [comment]
Ok That's perfect, thank you a lot!
