### ISSUE TITLE
Issue with Google API location look-ups

### ISSUE THREAD

**Issue by larryblunk** [librenms/librenms#5736]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | f22f3211d505b0ab69f6e6e6dd439daf9321cdc7
DB Schema | 157
PHP       | 5.5.9-1ubuntu4.20
MySQL     | 5.5.54-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

  Google location lookups do not always works as spaces are not getting replaced with +'s (they are getting removed).  There is an issue in includes/polling/functions.php.inc

        $new_device_location = preg_replace('/[^A-Za-z0-9\-\+]/', '', $device_location); 

should be

        $new_device_location = preg_replace('/[^A-Za-z0-9\-\+]/', '', $new_device_location);

**Comment by InsaneSplash** [comment]
Thanks, I've submitted a PR #5738 to fix this
