### ISSUE TITLE
Device support for HaulPass V60s

### ISSUE THREAD

**Issue by wdst-gcet** [librenms/librenms#5745]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the 
- [x ] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

I was wondering if someone could help me add device support for HaulPass V60s. This is my first time submitting a device and I maybe missing some information. I have attached the files for the poller, snmpwalk, discovery below. Thanks and let me know if you need anything else

<img width="355" alt="vubiq" src="https://cloud.githubusercontent.com/assets/20130657/22576430/5b09a3a6-e989-11e6-9c01-65ded67e452d.png">
[poller_vubiq_v60s.txt](https://github.com/librenms/librenms/files/749411/poller_vubiq_v60s.txt)
[snmpwalk_vubiq_v60s.txt](https://github.com/librenms/librenms/files/749412/snmpwalk_vubiq_v60s.txt)
[discovery_vubiq_v60s.txt](https://github.com/librenms/librenms/files/749413/discovery_vubiq_v60s.txt)
[VUBIQ-RF-MIB.txt](https://github.com/librenms/librenms/files/749414/VUBIQ-RF-MIB.txt)

**Comment by geordish** [comment]
The snmpwalk you have provided seems to have invalid data.

It is reporting things under:
.1.3.6.1.4.1.6330

But should be under:
.1.3.6.1.4.1.46330

I've added some basic detection under #5844 . I'm not sure about the name of the OS I've used for it though. Is there a better name than vubiq?

**Comment by wdst-gcet** [comment]
Thanks for the update! Vubiq is a a company that is making millimeter backhauls for ISPs. There equipment is fairly new. 

Does the invalid data above point to an issue with the MIB file?

**Comment by geordish** [comment]
Its with the implementation on the device.

Here are the reservations for each PEN:

6330
  Microdot Computing Services
    Andrew Smith
      Andy-Smith&microdotcomputingservices.co.uk

46330
  Vubiq Networks
    Aaron Baranoff
      aaron&vubiqnetworks.com

They've accidentally dropped a 4 from the beginning.

**Comment by wdst-gcet** [comment]
Ahhh okay so change the MIB file has nothing to do with this. I need to check with Vubiq and see if they have a fix for mismatch.

Thanks again you guys are great!
