### ISSUE TITLE
Granting access to all AD/LDAP groups

### ISSUE THREAD

**Issue by ivankisic** [librenms/librenms#5750]
I'm using the latest version of LibreNMS and the following configuration:

```
### Authentication Model
$config['auth_mechanism'] = "mysql"; # default, other options: ldap, http-auth
$config['auth_mechanism'] = "active_directory";
$config['auth_ad_url'] = "ldap://REDACTEDIP";
$config['auth_ad_dont_check_certificates'] = 1; // or 0
$config['auth_ad_domain'] = "company.local";
$config['auth_ad_base_dn'] = "dc=company,dc=local";
$config['auth_ad_groups']['admin_group']['level'] = 10;
$config['auth_ad_groups']['visitor_group']['level'] = 5;
$config['auth_ad_require_groupmembership'] = 0;
```

Is there any way to grant access to all company AD groups with one line?

**Comment by FTBZ** [comment]
All group or all AD users? I don't understand why allowing all groups?

You can use $config['auth_ad_global_read'] to add all users to read access only:
http://docs.librenms.org/Extensions/Authentication/#active-directory-authentication

FYI, it's better to use the Community for non-bug question:
https://community.librenms.org

**Comment by laf** [comment]
Thanks @FTBZ Indeed. This should be discussed further on the community site.
