### ISSUE TITLE
Feature request: Windows Disk I/0 over SNMP

### ISSUE THREAD

**Issue by LaurieBuxton** [librenms/librenms#5752]
Hi there, 

First of I love LibreNMS and think it fab and it puts many commercial monitoring systems to shame. 

Can request that you add the ability to add Windows Disk I/O to LibreNMS? I can see that linux machines have this monitoring natively but Windows machines do not (even when you enhance the windows OS SNMP with an agent like with http://www.snmp-informant.com/)

Search all can for this but appears to be unavailable?

Many thanks

Lawrence Buxton,

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x  ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
You need to provide all the info ask for in point 3.

**Comment by wriedel** [comment]
@laf in that context is there a recommended way on how to get insights into Windows machines in general? Like https://www.nsclient.org or so?

**Comment by laf** [comment]
We only use snmp at present

**Comment by LaurieBuxton** [comment]
It is possible to retrieve windows disk I/o via SNMP, but i suspect the OIDs aren't enabled on librenms

**Comment by laf** [comment]
No further information provided. When you can provide the info we ask for in point 3 above we can look into this further.

**Comment by rockyluke** [comment]
Hello,

I'll provide information needed in point 3. I'm really interested in I/O graphs for Windows.

./discovery.php : https://p.libren.ms/view/be8e9f26
./poller.php : https://p.libren.ms/view/c33c56ad
snmpbulkwalk : https://p.libren.ms/view/fcab9296

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/windows-disk-i-0-over-snmp/1132
