### ISSUE TITLE
Device Support for Linksys LGS308P

### ISSUE THREAD

**Issue by dbbestdave** [librenms/librenms#5754]
I'd love to try and get full support for the LINKSYS LGS308P 8-PORT BUSINESS SMART GIGABIT POE+ SWITCH. Today it detects as a "generic" device

Here's the MIBs location:
http://downloads.linksys.com/downloads/firmware/1224702359689/MIBs_LGS300_V1.1.zip

Please let me know if there's anything else I can do to support this request...

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | a19b2614dc94a48a58f6af1176a43d56a1a636f3
DB Schema | 158
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
- [X] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
[308p_discovery.txt](https://github.com/librenms/librenms/files/751443/308p_discovery.txt)
[308p_poller.txt](https://github.com/librenms/librenms/files/751442/308p_poller.txt)
[308p_snmpbulkwalk.zip](https://github.com/librenms/librenms/files/751572/308p_snmpbulkwalk.zip)

- [x] Please provide as much detail as possible.

I'd love to try and get full support for the LINKSYS LGS308P 8-PORT BUSINESS SMART GIGABIT POE+ SWITCH. Today it detects as a "generic" device

Here's the MIBs location:
http://downloads.linksys.com/downloads/firmware/1224702359689/MIBs_LGS300_V1.1.zip

- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by dbbestdave** [comment]
@laf I posted the discover and polIer info, am working on pulling the SNMPBulk data, but it's been running for about 15 minutes so far, and is over 10MB right now. 
Once it's done, I will zip it and attach. Outside of that, what other information do you need?

**Comment by laf** [comment]
Hopefully nothing.

**Comment by dbbestdave** [comment]
@laf SNMPBulkwalk data added to the original post.
Thank you!

**Comment by arrmo** [comment]
Hi,

As part of this - can you also support the LGS308 (just no PoE, that's the "P" version). I can provide the inputs needed if that helps.

Thanks!
