### ISSUE TITLE
Update in daily.sh can break discovery process

### ISSUE THREAD

**Issue by towster** [librenms/librenms#5762]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

-----------
Discovery had been running along just fine until daily.sh ran..
I know this might not happen often where a change that is applied causes issues but should some locking logic be put into the daily.sh to wait until there are no other processes running before doing the update?

-----------
daily.sh output 
------------
```
Updating to latest codebase                        OK
Updated from a29fcea6c7df26dc779815429f268c7ba4422a5a to 424ac80bff355ebcb503d1730928e06cdb70f7af OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
```

-----------
tail of the discovery -h all -d -v output that failed at same time daily.sh ran
-----------
```
SQL[SELECT * FROM sensors AS S, devices AS D WHERE S.sensor_class='fanspeed' AND S.device_id = D.device_id AND D.device_id = '812' AND S.poller_type = 'ipmi'] 
SQL[SELECT * FROM sensors AS S, devices AS D WHERE S.sensor_class='power' AND S.device_id = D.device_id AND D.device_id = '812' AND S.poller_type = 'ipmi'] 
PHP Fatal error:  Uncaught Error: Call to undefined function sensors() in /opt/librenms/includes/discovery/sensors.inc.php:43
Stack trace:
#0 /opt/librenms/includes/discovery/functions.inc.php(144): include()
#1 /opt/librenms/discovery.php(120): discover_device(Array, Array)
#2 {main}
  thrown in /opt/librenms/includes/discovery/sensors.inc.php on line 43

Fatal error: Uncaught Error: Call to undefined function sensors() in /opt/librenms/includes/discovery/sensors.inc.php:43
Stack trace:
#0 /opt/librenms/includes/discovery/functions.inc.php(144): include()
#1 /opt/librenms/discovery.php(120): discover_device(Array, Array)
#2 {main}
  thrown in /opt/librenms/includes/discovery/sensors.inc.php on line 43
```

**Comment by laf** [comment]
I'm not really sure this is worth worrying about to be fair. Distributed polling makes this a pain to fix as you can't just ps aux|grep discovery to see if it's running and until it's not pause things as you may have 5 pollers, only one will run a schema update (or maybe that's done elsewhere) so if poller 1 updates because nothing is happening and the schema is updated, pollers 2-5 may all now fail because they try and write to a table that has been changed or removed but don't have the latest code because they've paused.

**Comment by laf** [comment]
@librenms/reviewers anyone else?

**Comment by laf** [comment]
No further feedback provided
