### ISSUE TITLE
GUI Display issues Login

### ISSUE THREAD

**Issue by TyShawn76** [librenms/librenms#5764]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
==========================================================
Component | Version
--------- | -------
LibreNMS  | 424ac80bff355ebcb503d1730928e06cdb70f7af
DB Schema | 159
PHP       | 5.6.29-0+deb8u1
MySQL     | 5.5.54-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
Multiple sections are off in the GUI most are over Chrome and Safari and one is only over Safari.

Login Screen is a Safari issue only.
![screen shot 2017-02-04 at 7 03 30 am](https://cloud.githubusercontent.com/assets/21324034/22618352/0f7e9778-eaa8-11e6-8cf3-910d54dc0fb8.png)
This shows correctly in Chrome
![screen shot 2017-02-04 at 6 42 52 am](https://cloud.githubusercontent.com/assets/21324034/22618355/1964da54-eaa8-11e6-8276-eb207298fceb.png)

**Comment by laf** [comment]
I think you need to submit these as separate issues.

**Comment by TyShawn76** [comment]
Can you edit the top to login please? Ill make two more topics.

**Comment by TyShawn76** [comment]
Opened three tickets for the issues I found.
