### ISSUE TITLE
GUI Display issue Map

### ISSUE THREAD

**Issue by TyShawn76** [librenms/librenms#5765]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
==========================================================
Component | Version
--------- | -------
LibreNMS  | 424ac80bff355ebcb503d1730928e06cdb70f7af
DB Schema | 159
PHP       | 5.6.29-0+deb8u1
MySQL     | 5.5.54-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================
- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
Multiple sections are off in the GUI most are over Chrome and Safari and one is only over Safari.

Over the World Map the map is pushing over the outline box on both browsers.
![screen shot 2017-02-04 at 6 49 50 am](https://cloud.githubusercontent.com/assets/21324034/22618492/b7ceca94-eaab-11e6-9ea3-7bc3850c5ec9.png)

**Comment by laf** [comment]
That screenshot really isn't helpful. However have you expanded the widget box big enough? Mine works ok:

![image](https://cloud.githubusercontent.com/assets/3941142/22715066/2ed6f6ba-ed87-11e6-967f-4602580cd020.png)

**Comment by TyShawn76** [comment]
Yes if I keep expanding the box the the overlap goes away, but if I decrease the size of the box after a point the map goes past to bottom outline. It acts as if its the top layer vs being the underlying layer.

![screen shot 2017-02-07 at 6 03 09 pm](https://cloud.githubusercontent.com/assets/21324034/22715685/2ca1c63a-ed60-11e6-8a8c-719bc39bdb5b.png)
![screen shot 2017-02-07 at 6 03 35 pm](https://cloud.githubusercontent.com/assets/21324034/22715689/3192813e-ed60-11e6-82d8-ea27280c067a.png)

**Comment by laf** [comment]
You need to have the widget box expanded. The tile system isn't perfect but unless we replace it we are stuck with some small issues like this.
