### ISSUE TITLE
Kyocera tonner graph error

### ISSUE THREAD

**Issue by michelbragaguimaraes** [librenms/librenms#5775]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 8aa2480c05e20f2bd0b975925cef34e5d0a8038f
DB Schema | 159
PHP       | 5.6.30
MySQL     | 10.1.21-MariaDB
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

I am facing this issue with this Kyocera printer colorful, model "ECOSYS P6030cdn".

The Tonner graphs return error. Here follows a few prints:

![capture](https://cloud.githubusercontent.com/assets/8365866/22627044/b42f360c-eba1-11e6-8c1a-84a7b8d369ac.PNG)

![capture2](https://cloud.githubusercontent.com/assets/8365866/22627069/05fe379e-eba2-11e6-8ed9-7e9f39cff601.PNG)

**Comment by Rosiak** [comment]
That is because we are not picking up any info.

Please supply us the output from:
./discovery.php -h HOSTNAME -m toner -d

**Comment by michelbragaguimaraes** [comment]
Here is the return of the command you told me to do:

$ ./discovery.php -h ggab01 -m toner -d
LibreNMS Discovery
Version info:
Commit SHA: 8aa2480c05e20f2bd0b975925cef34e5d0a8038f
DB Schema: 159
PHP: 5.6.30
MySQL: 10.1.21-MariaDB
RRDTool: 1.6.0
SNMP: NET-SNMP 5.7.3
DEBUG!
SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
DB Schema already up to date.
SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE 'ggab01' ORDER BY device_id DESC] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '27'] 
ggab01 27 kyocera 
Modules status: Global+ OS  Device  
#### Load disco module toner ####
Toner: SNMP[/usr/local/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs -m Printer-MIB -M /usr/local/www/librenms/mibs udp:HOSTNAME:161 prtMarkerColorantMarkerIndex]
prtMarkerColorantMarkerIndex.1.1 = 1
prtMarkerColorantMarkerIndex.1.2 = 1
prtMarkerColorantMarkerIndex.1.3 = 1
prtMarkerColorantMarkerIndex.1.4 = 1

SNMP[/usr/local/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs -m Printer-MIB -M /usr/local/www/librenms/mibs udp:HOSTNAME:161 prtMarkerSuppliesLevel]
prtMarkerSuppliesLevel.1.1 = 4600
prtMarkerSuppliesLevel.1.2 = 5600
prtMarkerSuppliesLevel.1.3 = 5300
prtMarkerSuppliesLevel.1.4 = 2400
prtMarkerSuppliesLevel.1.5 = -3

SNMP[/usr/local/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs -m Printer-MIB -M /usr/local/www/librenms/mibs udp:HOSTNAME:161 prtMarkerSuppliesMaxCapacity]
prtMarkerSuppliesMaxCapacity.1.1 = 10000
prtMarkerSuppliesMaxCapacity.1.2 = 10000
prtMarkerSuppliesMaxCapacity.1.3 = 10000
prtMarkerSuppliesMaxCapacity.1.4 = 12000
prtMarkerSuppliesMaxCapacity.1.5 = -2

SNMP[/usr/local/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUsa -m Printer-MIB -M /usr/local/www/librenms/mibs udp:HOSTNAME:161 prtMarkerSuppliesDescription]
prtMarkerSuppliesDescription.1.1 = "TK-562C"
prtMarkerSuppliesDescription.1.2 = "TK-562M"
prtMarkerSuppliesDescription.1.3 = "TK-562Y"
prtMarkerSuppliesDescription.1.4 = "TK-562K"
prtMarkerSuppliesDescription.1.5 = "Waste Toner Box"

SNMP[/usr/local/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUsa -m Printer-MIB -M /usr/local/www/librenms/mibs udp:HOSTNAME:161 prtMarkerColorantValue]
prtMarkerColorantValue.1.1 = "cyan"
prtMarkerColorantValue.1.2 = "magenta"
prtMarkerColorantValue.1.3 = "yellow"
prtMarkerColorantValue.1.4 = "black"

Discover Toner: .1.3.6.1.2.1.43.11.1.1.9.1.1, 1, jetdirect, Cyan, .1.3.6.1.2.1.43.11.1.1.8.1.1, 10000, 46
SQL[SELECT COUNT(toner_id) FROM `toner` WHERE device_id = '27' AND toner_type = 'jetdirect' AND `toner_index` = '1' AND `toner_oid` ='.1.3.6.1.2.1.43.11.1.1.9.1.1'] 
SQL[INSERT INTO `toner` (`device_id`,`toner_oid`,`toner_capacity_oid`,`toner_index`,`toner_type`,`toner_descr`,`toner_capacity`,`toner_current`)  VALUES ('27','.1.3.6.1.2.1.43.11.1.1.9.1.1','.1.3.6.1.2.1.43.11.1.1.8.1.1','1','jetdirect','Cyan','10000','46')] 
+SQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`message`)  VALUES ('27','27','4','toner',NOW(),'Toner added: type jetdirect index 1 descr Cyan')] 
Discover Toner: .1.3.6.1.2.1.43.11.1.1.9.1.2, 2, jetdirect, Magenta, .1.3.6.1.2.1.43.11.1.1.8.1.2, 10000, 56
SQL[SELECT COUNT(toner_id) FROM `toner` WHERE device_id = '27' AND toner_type = 'jetdirect' AND `toner_index` = '2' AND `toner_oid` ='.1.3.6.1.2.1.43.11.1.1.9.1.2'] 
SQL[INSERT INTO `toner` (`device_id`,`toner_oid`,`toner_capacity_oid`,`toner_index`,`toner_type`,`toner_descr`,`toner_capacity`,`toner_current`)  VALUES ('27','.1.3.6.1.2.1.43.11.1.1.9.1.2','.1.3.6.1.2.1.43.11.1.1.8.1.2','2','jetdirect','Magenta','10000','56')] 
+SQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`message`)  VALUES ('27','27','5','toner',NOW(),'Toner added: type jetdirect index 2 descr Magenta')] 
Discover Toner: .1.3.6.1.2.1.43.11.1.1.9.1.3, 3, jetdirect, Yellow, .1.3.6.1.2.1.43.11.1.1.8.1.3, 10000, 53
SQL[SELECT COUNT(toner_id) FROM `toner` WHERE device_id = '27' AND toner_type = 'jetdirect' AND `toner_index` = '3' AND `toner_oid` ='.1.3.6.1.2.1.43.11.1.1.9.1.3'] 
SQL[INSERT INTO `toner` (`device_id`,`toner_oid`,`toner_capacity_oid`,`toner_index`,`toner_type`,`toner_descr`,`toner_capacity`,`toner_current`)  VALUES ('27','.1.3.6.1.2.1.43.11.1.1.9.1.3','.1.3.6.1.2.1.43.11.1.1.8.1.3','3','jetdirect','Yellow','10000','53')] 
+SQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`message`)  VALUES ('27','27','6','toner',NOW(),'Toner added: type jetdirect index 3 descr Yellow')] 
Discover Toner: .1.3.6.1.2.1.43.11.1.1.9.1.4, 4, jetdirect, Black, .1.3.6.1.2.1.43.11.1.1.8.1.4, 12000, 20
SQL[SELECT COUNT(toner_id) FROM `toner` WHERE device_id = '27' AND toner_type = 'jetdirect' AND `toner_index` = '4' AND `toner_oid` ='.1.3.6.1.2.1.43.11.1.1.9.1.4'] 
SQL[INSERT INTO `toner` (`device_id`,`toner_oid`,`toner_capacity_oid`,`toner_index`,`toner_type`,`toner_descr`,`toner_capacity`,`toner_current`)  VALUES ('27','.1.3.6.1.2.1.43.11.1.1.9.1.4','.1.3.6.1.2.1.43.11.1.1.8.1.4','4','jetdirect','Black','12000','20')] 
+SQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`message`)  VALUES ('27','27','7','toner',NOW(),'Toner added: type jetdirect index 4 descr Black')] 
Discover Toner: .1.3.6.1.2.1.43.11.1.1.9.1.5, 5, jetdirect, Waste Toner Box, .1.3.6.1.2.1.43.11.1.1.8.1.5, 100, 50
SQL[SELECT COUNT(toner_id) FROM `toner` WHERE device_id = '27' AND toner_type = 'jetdirect' AND `toner_index` = '5' AND `toner_oid` ='.1.3.6.1.2.1.43.11.1.1.9.1.5'] 
SQL[INSERT INTO `toner` (`device_id`,`toner_oid`,`toner_capacity_oid`,`toner_index`,`toner_type`,`toner_descr`,`toner_capacity`,`toner_current`)  VALUES ('27','.1.3.6.1.2.1.43.11.1.1.9.1.5','.1.3.6.1.2.1.43.11.1.1.8.1.5','5','jetdirect','Waste Toner Box','100','50')] 
+SQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`message`)  VALUES ('27','27','8','toner',NOW(),'Toner added: type jetdirect index 5 descr Waste Toner Box')] 

 Checking valid toner ... 
Array
(
    [jetdirect] => Array
        (
            [.1.3.6.1.2.1.43.11.1.1.9.1.1] => 1
            [.1.3.6.1.2.1.43.11.1.1.9.1.2] => 1
            [.1.3.6.1.2.1.43.11.1.1.9.1.3] => 1
            [.1.3.6.1.2.1.43.11.1.1.9.1.4] => 1
            [.1.3.6.1.2.1.43.11.1.1.9.1.5] => 1
        )

)
SQL[SELECT * FROM toner WHERE device_id = '27'] 
Array
(
    [0] => Array
        (
            [toner_id] => 4
            [device_id] => 27
            [toner_index] => 1
            [toner_type] => jetdirect
            [toner_oid] => .1.3.6.1.2.1.43.11.1.1.9.1.1
            [toner_descr] => Cyan
            [toner_capacity] => 10000
            [toner_current] => 46
            [toner_capacity_oid] => .1.3.6.1.2.1.43.11.1.1.8.1.1
        )

    [1] => Array
        (
            [toner_id] => 5
            [device_id] => 27
            [toner_index] => 2
            [toner_type] => jetdirect
            [toner_oid] => .1.3.6.1.2.1.43.11.1.1.9.1.2
            [toner_descr] => Magenta
            [toner_capacity] => 10000
            [toner_current] => 56
            [toner_capacity_oid] => .1.3.6.1.2.1.43.11.1.1.8.1.2
        )

    [2] => Array
        (
            [toner_id] => 6
            [device_id] => 27
            [toner_index] => 3
            [toner_type] => jetdirect
            [toner_oid] => .1.3.6.1.2.1.43.11.1.1.9.1.3
            [toner_descr] => Yellow
            [toner_capacity] => 10000
            [toner_current] => 53
            [toner_capacity_oid] => .1.3.6.1.2.1.43.11.1.1.8.1.3
        )

    [3] => Array
        (
            [toner_id] => 7
            [device_id] => 27
            [toner_index] => 4
            [toner_type] => jetdirect
            [toner_oid] => .1.3.6.1.2.1.43.11.1.1.9.1.4
            [toner_descr] => Black
            [toner_capacity] => 12000
            [toner_current] => 20
            [toner_capacity_oid] => .1.3.6.1.2.1.43.11.1.1.8.1.4
        )

    [4] => Array
        (
            [toner_id] => 8
            [device_id] => 27
            [toner_index] => 5
            [toner_type] => jetdirect
            [toner_oid] => .1.3.6.1.2.1.43.11.1.1.9.1.5
            [toner_descr] => Waste Toner Box
            [toner_capacity] => 100
            [toner_current] => 50
            [toner_capacity_oid] => .1.3.6.1.2.1.43.11.1.1.8.1.5
        )

)


>> Runtime for discovery module 'toner': 0.2600 seconds
#### Unload disco module toner ####

SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '27' AND `attrib_type` = 'poll_mib' ] 
SQL[UPDATE `devices` set `last_discovered` =NOW(),`last_discovered_timetaken` ='0.264' WHERE `device_id` = '27'] 
Discovered in 0.264 seconds

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('discover','ggab01','1486380054.6227','0.299','1','')] 
./discovery.php ggab01 2017-02-06 09:20:54 - 1 devices discovered in 0.299 secs
SNMP: Get[0/0.00s] Walk [5/0.24s]
MySQL: Cell[8/0.00s] Row[1/0.00s] Rows[5/0.00s] Column[0/0.00s] Update[1/0.00s] Insert[11/0.02s] Delete[0/0.00s]

After this command, all the tonner leves just showed up, but the graphs still with error. Follows a attach to show what is happening:
![capture](https://cloud.githubusercontent.com/assets/8365866/22645584/e12eb1fc-ec4e-11e6-84c9-8efff17718d5.PNG)

**Comment by laf** [comment]
If you've only just run discovery then wait 15 mins for the graphs to appear.

If this all works afterwards then the question is, do you have toner modules turned on for this device?

**Comment by michelbragaguimaraes** [comment]
That was it, my tone module was disabled globally.
My bad. Sorry.
The graphs just started to show me information.
Thank you for the support.

**Comment by thebigsmileXD** [comment]
We experience something similar.
Do you always have to manually execute `./discovery.php -h HOSTNAME -m toner -d` for every printer, and do you have to do it every day by hand, or will it then poll automatically the latest toner information?
