### ISSUE TITLE
Update support for DCN (Digital China Networks) switches

### ISSUE THREAD

**Issue by kamils85** [librenms/librenms#5785]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 33a964cb550db9f9ecb8ef48125d222c2bb80eba
DB Schema | 159
PHP       | 7.0.8-3ubuntu3
MySQL     | 10.0.25-MariaDB-1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Can we update the Platform and Operating System for DCN Switches?
At the moment Platform shows nothing and OS shows just the "Digital China Networks".

I would like this to look like:
Platform: "S5750E-28X-SI-24F-D"
OS: "Digital China Networks 7.0.3.5(R0102.0137)"

OIDs:
 .1.3.6.1.4.1.6339.100.25.1.1.1.0 = STRING: "S5750E-28X-SI-24F-D"
 .1.3.6.1.4.1.6339.100.25.1.1.2.0 = STRING: "7.0.3.5(R0102.0137)"

Many thanks,
K.

**Comment by Rosiak** [comment]
Could you please pastebin the output of the following:
```
./poller.php -h HOSTNAME -m os -d
```

**Comment by kamils85** [comment]
yes, sorry.

http://pastebin.com/nhwp2LFn

**Comment by kamils85** [comment]
I can see the Serial No is also not being populated.

I appreciate if this could be added too. 
.1.3.6.1.2.1.47.1.1.1.1.11.1 = STRING: "SW048110F417000498"
