### ISSUE TITLE
Feature request: Percentage Uptime Graph

### ISSUE THREAD

**Issue by wriedel** [librenms/librenms#5788]
Hi Folks,

currently we visualize the up-time for a device with a constantly increasing graph while most OPS people are keen on five 9's for 99.999 % up-time.

Is there a knob where I can switch the graph to show up-time in percentage as flat line at 100% for 100% availability? 

Thanks,
Wolfgang

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

==========================================================
Component | Version
--------- | -------
LibreNMS  | 389cf5414cf6c0afb904a97581d32d595724f363
DB Schema | 159
PHP       | 7.0.14-2
MySQL     | 10.2.3-MariaDB-10.2.3+maria~sid-log
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================

**Comment by laf** [comment]
Please post feature requests in https://community.librenms.org/c/feature-requests

But no, we don't currently have this option.
