### ISSUE TITLE
NetGear GS728TP Not properly identified

### ISSUE THREAD

**Issue by gardar** [librenms/librenms#5790]
NetGear GS728TP don't seem to get properly recognized.

The description and OID are: 
24-Port Gigabit Smart Switch with PoE and 4 SFP uplinks
.1.3.6.1.4.1.89.1.1.1.3.6.1.4.1.4526.100.4.25

Component | Version
--------- | -------
LibreNMS  | 389cf5414cf6c0afb904a97581d32d595724f363
DB Schema | 159
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [x] discovery: https://gist.github.com/gardar/bc98b3dc3fade5f4a5deb74199e90891
- [x] poller: https://gist.github.com/gardar/9715ff142d375778769fdbe8daaec43d
- [x] snmpbulkwalk: https://gist.github.com/gardar/92baf66604265c527b1696d1a151167a

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by geordish** [comment]
It looks like they have broken their SNMP sysoid value...

.1.3.6.1.4.1.89.1.1.1.3.6.1.4.1.4526.100.4.25

That is 2 Sysoids, jammed together. The first is probably something to do with the SNMP implementation they have taken. The second is correct.
.1.3.6.1.4.1.89.1.1
.1.3.6.1.4.1.4526.100.4.25

I wonder if this is fixed in different firmware versions...

I've added a PR to add detection for this. #5798

**Comment by laf** [comment]
lol, nice work :)
