### ISSUE TITLE
F5 Active/Standby detection request

### ISSUE THREAD

**Issue by thejimmahknows** [librenms/librenms#5799]
Is there a way to add in as a feature request the detection of F5 Active/Standby units?

root@host/opt/librenms# snmpwalk -v 2c -c sysmonr 10.10.0.24 .1.3.6.1.4.1.3375.2.1.14.3
iso.3.6.1.4.1.3375.2.1.14.3.1.0 = INTEGER: 3
iso.3.6.1.4.1.3375.2.1.14.3.2.0 = STRING: "STANDBY"
iso.3.6.1.4.1.3375.2.1.14.3.3.0 = INTEGER: 4
iso.3.6.1.4.1.3375.2.1.14.3.4.0 = STRING: "1/1 standby"
root@host:/opt/librenms# snmpwalk -v 2c -c sysmonr 10.10.0.25 .1.3.6.1.4.1.3375.2.1.14.3
iso.3.6.1.4.1.3375.2.1.14.3.1.0 = INTEGER: 4
iso.3.6.1.4.1.3375.2.1.14.3.2.0 = STRING: "ACTIVE"
iso.3.6.1.4.1.3375.2.1.14.3.3.0 = INTEGER: 0
iso.3.6.1.4.1.3375.2.1.14.3.4.0 = STRING: "1/1 active"

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
/opt/librenms# ./daily.sh 
Re-running /opt/librenms/daily.sh as librenms user
Updating to latest codebase                        OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK

- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
==========================================================
Component | Version
--------- | -------
LibreNMS  | aab1cdac49c97a9c5b28f21af572648861596f09
DB Schema | 159
PHP       | 5.6.29-0+deb8u1
MySQL     | 5.5.54-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
[f5-dcltm01.snmpwalk.txt](https://github.com/librenms/librenms/files/755603/f5-dcltm01.snmpwalk.txt)
[poller-dcltm01.txt](https://github.com/librenms/librenms/files/755602/poller-dcltm01.txt)
[discovery-dcltm01.txt](https://github.com/librenms/librenms/files/755604/discovery-dcltm01.txt)

- [ x] Please provide as much detail as possible.
F5 Load balancing unit usually come in pairs (Active and Standby Unit)

- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
root@host/opt/librenms# snmpwalk -v 2c -c sysmonr 10.10.0.24 .1.3.6.1.4.1.3375.2.1.14.3
iso.3.6.1.4.1.3375.2.1.14.3.1.0 = INTEGER: 3
iso.3.6.1.4.1.3375.2.1.14.3.2.0 = STRING: "STANDBY"
iso.3.6.1.4.1.3375.2.1.14.3.3.0 = INTEGER: 4
iso.3.6.1.4.1.3375.2.1.14.3.4.0 = STRING: "1/1 standby"
root@host:/opt/librenms# snmpwalk -v 2c -c sysmonr 10.10.0.25 .1.3.6.1.4.1.3375.2.1.14.3
iso.3.6.1.4.1.3375.2.1.14.3.1.0 = INTEGER: 4
iso.3.6.1.4.1.3375.2.1.14.3.2.0 = STRING: "ACTIVE"
iso.3.6.1.4.1.3375.2.1.14.3.3.0 = INTEGER: 0
iso.3.6.1.4.1.3375.2.1.14.3.4.0 = STRING: "1/1 active"

**Comment by geordish** [comment]
This should already be detected. Do you not see Active/Standby on the right hand side of the device page with the sensors?

**Comment by laf** [comment]
The debug output indicates this is picked up as well. If you need further help please post on the community site or irc.
