### ISSUE TITLE
now show install.php on access localhost

### ISSUE THREAD

**Issue by sharaujo** [librenms/librenms#5800]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

my problem:

root@monitoracao:/opt/librenms# php validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | a98bfdb6fba5cae4c785b6f8d6efd26473b62046
DB Schema | 159
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

[OK]    Database connection successful
root@monitoracao:/opt/librenms#

when access http://localhost not show http://localhost/install.php

**Comment by laf** [comment]
GitHub isn't for help. Please connect to irc or use the community site. This is however because you e created the config.php and not followed the install docs

**Comment by sharaujo** [comment]
im followed install docs.. but i trying manual installation
