### ISSUE TITLE
Feature request: Tree view widget

### ISSUE THREAD

**Issue by realnakrul** [librenms/librenms#5807]
Hi, it would be nice to have device tree view widget. Something like this (from Solarwinds NPM once again)
![image](https://cloud.githubusercontent.com/assets/21193002/22682376/c9a46eea-ed2b-11e6-8755-932fc81ea8b6.png)
For example I want to have device tree with devices grouped by location. Is it possible?

**Comment by laf** [comment]
Please don't post feature requests here. Searching a little would also yield this has already been asked for:

https://community.librenms.org/t/tree-like-structure-for-navigating-devices-groups/497
https://github.com/librenms/librenms/issues/2393
