### ISSUE TITLE
Add support for HP ProCurve 1810G-24 (J9450A)

### ISSUE THREAD

**Issue by NK74** [librenms/librenms#5808]
DO NOT DELETE THIS INFORMATION.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

| Component | Version|
| --- | --- |
| LibreNMS   | 5aef36abd653061db7fe547997bac8b87a9f10c6|
| DB Schema | 159 |
| PHP       | 7.0.8-3ubuntu3
| MySQL     | 10.0.28-MariaDB-0ubuntu0.16.10.1
| RRDTool   | 1.6.0
| SNMP      | NET-SNMP 5.7.3

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Discovery:**
https://gist.github.com/NK74/f85a95ef41224ca541fa69a72f4e636d

**Poller:**
https://gist.github.com/NK74/260e31db1a4837d91ce707d8b6672452

**Snmpbulkwalk:**
https://gist.github.com/NK74/07a7ed2f5cb0a9e29b79b6efbca97c7e

**Comment by NK74** [comment]
No cpu / memory
![prtscr capture_2](https://cloud.githubusercontent.com/assets/17825769/22686641/22651acc-ed25-11e6-9158-b99699a9bd53.jpg)

**Comment by NK74** [comment]
No CPU / Memory

**Comment by geordish** [comment]
From the walk you have provided, it doesn't appear that this device reports CPU or memory information via SNMP.

Procurce CPU OID: .1.3.6.1.4.1.11.2.14.11.5.1.9.6.1.0 
Procurve free memory OID: .1.3.6.1.4.1.11.2.14.11.5.1.1.2.1.1.1.6.1

**Comment by NK74** [comment]
You're right @geordish test snmp bellow with custom OID.

```
Paessler SNMP Tester 5.2.3 Computername: PC Interface: 192.168.1.33
08/02/2017 09:19:41 (1 ms) : Device: 192.168.1.104
08/02/2017 09:19:41 (2 ms) : SNMP V1
08/02/2017 09:19:41 (3 ms) : Custom OID 1.3.6.1.4.1.11.2.14.11.5.1.9.6.1.0
08/02/2017 09:19:41 (25 ms) : SNMP Datatype: ASN_NULL
08/02/2017 09:19:41 (26 ms) : -------
08/02/2017 09:19:41 (27 ms) : Value: NULL2
08/02/2017 09:19:41 (28 ms) : Done
Paessler SNMP Tester 5.2.3 Computername: PC Interface: 192.168.1.33
08/02/2017 09:19:49 (2 ms) : Device: 192.168.1.104
08/02/2017 09:19:49 (3 ms) : SNMP V1
08/02/2017 09:19:49 (4 ms) : Custom OID 1.3.6.1.4.1.11.2.14.11.5.1.1.2.1.1.1.6.1
08/02/2017 09:19:49 (16 ms) : SNMP Datatype: ASN_NULL
08/02/2017 09:19:49 (18 ms) : -------
08/02/2017 09:19:49 (19 ms) : Value: NULL2
08/02/2017 09:19:49 (20 ms) : Done
```

**Comment by laf** [comment]
Can we close this then?

**Comment by NK74** [comment]
Issued
