### ISSUE TITLE
Blank Interfaces in NMS

### ISSUE THREAD

**Issue by mr-ravirajput** [librenms/librenms#5809]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hello @laf 

I am re-creating the issue which was closed here

https://github.com/librenms/librenms/issues/5539#issuecomment-274295238

All the required details are now given

![blank interfaces](https://cloud.githubusercontent.com/assets/24430380/22686238/51517208-ed49-11e6-92dc-3baf695c3f41.png)
![validate php](https://cloud.githubusercontent.com/assets/24430380/22686237/514e99b6-ed49-11e6-8362-4a5d7372c639.png)

[discovery logs.docx](https://github.com/librenms/librenms/files/757173/discovery.logs.docx)
[poller logs.docx](https://github.com/librenms/librenms/files/757174/poller.logs.docx)
[snmp logs.docx](https://github.com/librenms/librenms/files/757175/snmp.logs.docx)

discovery

https://gist.github.com/mr-ravirajput/184b6e751447ad2af1b5e11f97c461a7

Poller log
https://gist.githubusercontent.com/mr-ravirajput/1221f0dbb60db0780a600bbc51f56e79/raw/e828909c5c0f2e3ee7fd29b17265acac002ff0b0/Blank%2520Interfaces%2520poller%2520log.rtf

snmp logs

https://gist.githubusercontent.com/mr-ravirajput/9f9974d23c5d4a6c175952a6826bdf85/raw/3b31d99515fdef191e8f534d06171dea462ce232/Blank%2520Interfaces%2520snmp%2520log.rtf

Please advise.

**Comment by laf** [comment]
It's not inserting the ports correctly. What's the output of this in mysql:

`SELECT @@global.sql_mode;`

**Comment by mr-ravirajput** [comment]
===========================================

MariaDB [librenms]> SELECT @@global.sql_mode;
+-------------------+
| @@global.sql_mode |
+-------------------+
|                   |
+-------------------+
1 row in set (0.00 sec)

MariaDB [librenms]>

===================================================================

**Comment by laf** [comment]
Using your data I only get one and that's because of the snmpwalk data.

Please share obfuscated output of config.php so we can see what options you are running.

**Comment by mr-ravirajput** [comment]
https://gist.github.com/mr-ravirajput/7a94496c63b9eb2ac2e03fa98c8f7cee

**Comment by laf** [comment]
I still can't replicate this :(

I'd suggest doing `delete from ports where device_id=X;` and doing a rediscover and leaving the poller to run a couple of times.

**Comment by mr-ravirajput** [comment]
just for knowledge, after this activity will the port ids change or will remain the same

**Comment by laf** [comment]
the port ids in the DB will change so you will lose graphs but I don't have any other suggestions for you as the data you've provided works as expected.

**Comment by mr-ravirajput** [comment]
I can track the specific ports that are missing.. will it be possible to delete only those and then start rediscovery..

**Comment by laf** [comment]
Yes you can try that.

**Comment by mr-ravirajput** [comment]
can you please share the command to do that..

**Comment by laf** [comment]
`delete from ports where device_id=X AND port_id IN (a,b,c);`

X = device id
a, b, c is a comma separated list of port ids

**Comment by geordish** [comment]
I tried with your data, and also couldn't replicate this issue.

I was thinking it might be some kind of memory or max execution limit?

**Comment by laf** [comment]
Both poller and discovery  outputs make it to the end so not sure on that one.

**Comment by mr-ravirajput** [comment]
If an interface missing in UI can b searched in both these files, then this would indicate what? I have not done this, just asking

**Comment by laf** [comment]
It is most likely that it's marked as deleted in the database so won't show in the webui unless you go to ports -> deleted.

**Comment by mr-ravirajput** [comment]
I tried this, not sure if this makes sense. If I search a missing interface in schema I am able to locate it
Missing interface : http://imgur.com/a/XAZex
In data base: http://imgur.com/a/Gz7yZ
Will this be of any help

**Comment by laf** [comment]
`select * from ports where port_id=31937;`

**Comment by mr-ravirajput** [comment]
MariaDB [librenms]> select * from ports where port_id=31937;
+---------+-----------+-----------------+------------------+--------------------                                                                                       +------------------+------------------+---------+---------------------------+---                                                                                       -------+---------+---------+--------------------+-------------------+-----------                                                                                       --+--------------+-------------------+---------------+--------------------+-----                                                                                       -----+-------+--------+---------+---------------+------------+--------------+---                                                                                       -----+---------+-------+------------+-------------+--------+----------+---------                                                                                       -+---------+-------------------+---------------+---------------------+----------                                                                                       --------------+--------------------+-------------------------+------------------                                                                                       -----+-----------------------+--------------+------------------+---------------+                                                                                       --------------------+---------------------+--------------------+----------------                                                                                       +---------------------+----------------------+---------------------+------------                                                                                       +-----------------+------------------+-----------------+-------------+----------                                                                                       --------+-------------------+------------------+------------+-----------------+-                                                                                       -----------------+-----------------+-------------+------------------+-----------                                                                                       --------+------------------+-----------+-----------+-------------+
| port_id | device_id | port_descr_type | port_descr_descr | port_descr_circuit                                                                                        | port_descr_speed | port_descr_notes | ifDescr | ifName                    | po                                                                                       rtName | ifIndex | ifSpeed | ifConnectorPresent | ifPromiscuousMode | ifHighSpee                                                                                       d | ifOperStatus | ifOperStatus_prev | ifAdminStatus | ifAdminStatus_prev | ifDu                                                                                       plex | ifMtu | ifType | ifAlias | ifPhysAddress | ifHardType | ifLastChange | if                                                                                       Vlan | ifTrunk | ifVrf | counter_in | counter_out | ignore | disabled | detailed                                                                                        | deleted | pagpOperationMode | pagpPortState | pagpPartnerDeviceId | pagpPartn                                                                                       erLearnMethod | pagpPartnerIfIndex | pagpPartnerGroupIfIndex | pagpPartnerDevice                                                                                       Name | pagpEthcOperationMode | pagpDeviceId | pagpGroupIfIndex | ifInUcastPkts |                                                                                        ifInUcastPkts_prev | ifInUcastPkts_delta | ifInUcastPkts_rate | ifOutUcastPkts                                                                                        | ifOutUcastPkts_prev | ifOutUcastPkts_delta | ifOutUcastPkts_rate | ifInErrors                                                                                        | ifInErrors_prev | ifInErrors_delta | ifInErrors_rate | ifOutErrors | ifOutErro                                                                                       rs_prev | ifOutErrors_delta | ifOutErrors_rate | ifInOctets | ifInOctets_prev |                                                                                        ifInOctets_delta | ifInOctets_rate | ifOutOctets | ifOutOctets_prev | ifOutOctet                                                                                       s_delta | ifOutOctets_rate | poll_time | poll_prev | poll_period |
+---------+-----------+-----------------+------------------+--------------------                                                                                       +------------------+------------------+---------+---------------------------+---                                                                                       -------+---------+---------+--------------------+-------------------+-----------                                                                                       --+--------------+-------------------+---------------+--------------------+-----                                                                                       -----+-------+--------+---------+---------------+------------+--------------+---                                                                                       -----+---------+-------+------------+-------------+--------+----------+---------                                                                                       -+---------+-------------------+---------------+---------------------+----------                                                                                       --------------+--------------------+-------------------------+------------------                                                                                       -----+-----------------------+--------------+------------------+---------------+                                                                                       --------------------+---------------------+--------------------+----------------                                                                                       +---------------------+----------------------+---------------------+------------                                                                                       +-----------------+------------------+-----------------+-------------+----------                                                                                       --------+-------------------+------------------+------------+-----------------+-                                                                                       -----------------+-----------------+-------------+------------------+-----------                                                                                       --------+------------------+-----------+-----------+-------------+
|   31937 |         4 | NULL            | NULL             | NULL                                                                                                      | NULL             | NULL             | NULL    | GigabitEthernet1/0/1.3900 | NU                                                                                       LL     |     634 |    NULL | NULL               | NULL              |        NUL                                                                                       L | NULL         | NULL              | NULL          | NULL               | NULL                                                                                            |  NULL | NULL   | NULL    | NULL          | NULL       |            0 |                                                                                               |         |     0 |       NULL |        NULL |      0 |        0 |        0                                                                                        |       1 | NULL              | NULL          | NULL                | NULL                                                                                                          |               NULL |                    NULL | NULL                                                                                                         | NULL                  | NULL         |             NULL |          NULL |                                                                                                      NULL |                NULL |               NULL |           NULL                                                                                        |                NULL |                 NULL |                NULL |       NULL                                                                                        |            NULL |             NULL |            NULL |        NULL |                                                                                                    NULL |              NULL |             NULL |       NULL |            NULL |                                                                                                    NULL |            NULL |        NULL |             NULL |                                                                                                     NULL |             NULL |      NULL |      NULL |        NULL |
+---------+-----------+-----------------+------------------+--------------------                                                                                       +------------------+------------------+---------+---------------------------+---                                                                                       -------+---------+---------+--------------------+-------------------+-----------                                                                                       --+--------------+-------------------+---------------+--------------------+-----                                                                                       -----+-------+--------+---------+---------------+------------+--------------+---                                                                                       -----+---------+-------+------------+-------------+--------+----------+---------                                                                                       -+---------+-------------------+---------------+---------------------+----------                                                                                       --------------+--------------------+-------------------------+------------------                                                                                       -----+-----------------------+--------------+------------------+---------------+                                                                                       --------------------+---------------------+--------------------+----------------                                                                                       +---------------------+----------------------+---------------------+------------                                                                                       +-----------------+------------------+-----------------+-------------+----------                                                                                       --------+-------------------+------------------+------------+-----------------+-                                                                                       -----------------+-----------------+-------------+------------------+-----------                                                                                       --------+------------------+-----------+-----------+-------------+
1 row in set (0.00 sec)

**Comment by mr-ravirajput** [comment]
https://gist.githubusercontent.com/mr-ravirajput/9adcaf1a566b90a3493fd51db4408681/raw/88470c9670bebcfdbbd91a9c1528dcfa8e0bfc8b/Blank%2520Interfaces%2520port%2520search%2520log.rtf

**Comment by laf** [comment]
That interface doesn't appear in the the discovery or poller output and in fact the device_id in the port output isn't the same so your either confusing things by talking about different devices or it's because the only port you found was for a different device.

I'm genuinely at a loss in what is causing this, your data is fine as two people have tested it now.

**Comment by mr-ravirajput** [comment]
Really sorry i gave this for some other device. here is the correct one. I am able to see this in poller logs.

https://gist.githubusercontent.com/mr-ravirajput/a499e2e18920e06ae5ca958a3ee71a04/raw/f4e2d37c0f2fe4da29a3eab26867b6a68d8fd772/gistfile1.txt

**Comment by mr-ravirajput** [comment]
:(
Still the same. Key is changed but still no data
https://gist.githubusercontent.com/mr-ravirajput/84c03df66e0ede57301672ed518c8472/raw/66042da234fc8af2027e87cff0aca81b0b01b9c0/gistfile1.txt.

Out of four core devices. I am facing this issue in three. Will sharing the logs of the one which is working O.K will be of any help.

**Comment by laf** [comment]
Possibly. Are they the same devices?

**Comment by mr-ravirajput** [comment]
yes.. so all three discovery, poller and snmp ?

**Comment by laf** [comment]
Don't bother with snmp for now.

**Comment by mr-ravirajput** [comment]
Discovery : https://gist.githubusercontent.com/mr-ravirajput/1e0377580fcf7485926c2cb084e41bcd/raw/653d13c04923f87fa39b64ccac27a7758010bbb9/gistfile1.txt

Poller : https://gist.githubusercontent.com/mr-ravirajput/065a0b904017c87cf5f2c2ad41665440/raw/5267e584c451c44ce0dc95d5eeabc8c8afc8c27d/gistfile1.txt

Just for reference. This has only 153 interfaces bit less when compared to others.

**Comment by laf** [comment]
Are you finding the number of ports is increasing?

**Comment by laf** [comment]
Any chance you can join our irc channel, this will be easier.

**Comment by mr-ravirajput** [comment]
yes for sure give me 2 min..

**Comment by mr-ravirajput** [comment]
Hi,
I have checked by adding new ports. The port count increases but ports are not shown in UI. I suppose the newly created ports are not being mapped.
Here -> before adding : http://imgur.com/a/JezIx
Here -> after adding: http://imgur.com/a/4Kcx6

Should I try on another clean install?

**Comment by mr-ravirajput** [comment]
The output of mysqldump --compact -d -u root -p librenms > /tmp/sql.sql
https://gist.githubusercontent.com/mr-ravirajput/9a58510deb81a21ca0f401bb5db590f0/raw/6d89a945db070b38bfcb74f73b1280db9bc6ff02/Blank%2520Interfaces%2520sql%2520log.rtf

**Comment by laf** [comment]
Are you still seeing the issue?

**Comment by mr-ravirajput** [comment]
Yes

**Comment by laf** [comment]
On what device then because device_id 16 has 103 ports and isn't increasing at all.

**Comment by mr-ravirajput** [comment]
Id is 15

**Comment by laf** [comment]
I had to remove 18 ports from that device, please see how it goes now.

**Comment by mr-ravirajput** [comment]
This worked .! Can you please advice, the corrective steps. There are two
more devices with same issue.

**Comment by laf** [comment]
`delete from ports where device_id=15 and ifAlias is null;`

Change 15 to the device id in question

**Comment by laf** [comment]
Your logs have been full of:

```
2017-02-10 18:31:05 MySQL Error: MySQL server has gone away (SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '13')
2017-02-10 18:31:05 MySQL Error: MySQL server has gone away (SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '16')
2017-02-10 18:31:05 MySQL Error: MySQL server has gone away (SELECT * FROM `ports` WHERE `device_id` = '3' AND `ifIndex` = '16')
2017-02-10 18:31:06 MySQL Error: MySQL server has gone away (SELECT * FROM `ports_stp` WHERE `device_id` = '3')

```

I'm wondering if this was the start of the issues.

**Comment by mr-ravirajput** [comment]
OK Thanks. Were you able figure out why this happened? . Is this the final
solution ?

On 13-Feb-2017 10:18 PM, "Neil Lathwood" <notifications@github.com> wrote:

delete from ports where device_id=15 and ifAlias is null;

Change 15 to the device id in question

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/librenms/librenms/issues/5809#issuecomment-279449460>,
or mute the thread

**Comment by mr-ravirajput** [comment]
Also validation of install gives discovery fail.

**Comment by mr-ravirajput** [comment]
Any suggestions to prevent this in future?

**Comment by mr-ravirajput** [comment]
Done on all devices. Now working fine.
Thanks a ton for all the efforts.

**Comment by laf** [comment]
Those mysql errors need (or should be looked at). You've got lots of other errors in the mysql logs.
