### ISSUE TITLE
Update network map

### ISSUE THREAD

**Issue by laf** [librenms/librenms#581]

**Comment by laf** [comment]
First attempt:

http://snag.gy/Lnoyk.jpg

Supports either global network /maps/ or individual devices maps.

**Comment by laf** [comment]
Any feedback from anyone on this? PR is probably good to go but interested to hear peoples thoughts on if this is better or not than the existing map.

**Comment by paulgear** [comment]
Do we even have map support exposed in the UI?  I can't see it.  It is definitely a feature I'd like to see re-added, possibly even in the main device screen under the total bits.

**Comment by laf** [comment]
The current map is in and does work but only shows up on devices that have discovered other devices via xDP.

It's a static map of what is connected to that single device and doesn't expand past that. This one will show you the whole network (or with additional coding you could restrict based on location, names, etc).

I'll put a PR together with some screenshots.

**Comment by damardjati** [comment]
Hi, everyone, after last pull from github repo today, the device map doesnt show anything.
could it be something wrong with the update ?

thanks.

**Comment by laf** [comment]
You need to wait for a rediscovery to run or force it:

./discovery.php -h all -mid discovery-protocols

**Comment by laf** [comment]
That's supposed to be -m not -mid

**Comment by laf** [comment]
All done, closing this now.
