### ISSUE TITLE
Adding Switchtec EATON Rectifiers

### ISSUE THREAD

**Issue by ntmanxp** [librenms/librenms#5812]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
root@librenms:/opt/librenms# ./validate.php 
==========================================================
Component | Version
--------- | -------
LibreNMS  | 1fb8135133c704b7edfba0f922f7ad7bb728650c
DB Schema | 159
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

[OK]    Database connection successful
[FAIL]  You have a different system timezone (ART) specified to the php configured timezone (UTC), please correct this.
root@librenms:/opt/librenms# 

- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
Discovery: [https://gist.github.com/ntmanxp/04f855137b0f3c9619e4c047883b33f7#file-gistfile1-txt](url)
Poller: [https://gist.github.com/ntmanxp/c5eb4977780fa12a5d629a6710f6a629#file-poller_switchtec_librenms](url)
SNMPBulk: [https://gist.github.com/ntmanxp/bb37671dba6a77cbcebc57f43c8ebb70#file-snmpbulkwalk_switchtec_librenms](url)
Additional Files: [[https://gist.github.com/ntmanxp/f9370ecf306fdeedc86c9e85e19ecd7d#file-switchtec-files](url)

- [x ] Please provide as much detail as possible.

This is Not EATON UPS, this are EATON Rectifiers.
I tried to get only a few items ( Uptime, Current, Voltage feed to Batteries and Batt Temperature ).
Once discovered, values are OK.
When the poller runs, got different values.

Defined new 'os' like switchtec

Regards
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by geordish** [comment]
All the links you posted 404.

Do you want to share what you created so far. We might be able to spot a mistake.

**Comment by ntmanxp** [comment]
Updated links

**Comment by geordish** [comment]
You're links are still broken:(

https://gist.github.com/ntmanxp/04f855137b0f3c9619e4c047883b33f7#file-gistfile1-txt
https://gist.github.com/ntmanxp/c5eb4977780fa12a5d629a6710f6a629#file-poller_switchtec_librenms
https://gist.github.com/ntmanxp/bb37671dba6a77cbcebc57f43c8ebb70#file-snmpbulkwalk_switchtec_librenms
https://gist.github.com/ntmanxp/f9370ecf306fdeedc86c9e85e19ecd7d#file-switchtec-files

Do they all start out right, and then go wrong? Are the values out by a certain factor (100?)

For your voltage one, you want to change $divisor to 1

You probably don't need the os file.
You probably don't need the    - sysDescr: SC200 Controller line in your YAML

**Comment by ntmanxp** [comment]
geordish,
Links seems fixed from other desktop here.... :(
Yes, I do start right with the 'discovery'. Values are there as expected. Mayby multiplied by 100.
Then, the poller screw things up.
The divisor is careless now, I can do it later ...only if I can see it.
As you can ( or not?) see here:

Current: Corriente de Rectificador SNMP[/usr/bin/snmpget -v2c -c 'public' -Oqv -M /opt/librenms/mibs udp:192.168.0.180:161 1.3.6.1.4.1.1918.2.13.10.50.10.0]
**34**

Discover sensor: 1.3.6.1.4.1.1918.2.13.10.50.10.0, 0, switchtec, Corriente de Rectificador , snmp, , 
SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'snmp' AND `sensor_class` = 'current' AND `device_id` = '48' AND sensor_type = 'switchtec' AND `sensor_index` = '0'] 
SQL[INSERT INTO `sensors` (`poller_type`,`sensor_class`,`device_id`,`sensor_oid`,`sensor_index`,`sensor_type`,`sensor_descr`,`sensor_divisor`,`sensor_multiplier`,`sensor_limit`,`sensor_current`)  VALUES ('snmp','current','48','1.3.6.1.4.1.1918.2.13.10.50.10.0','0','switchtec','Corriente de Rectificador ','1','1','51','34')] 
( 58 inserted )

But at poller time:

#### Load poller module sensors ####
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = 'current' AND `device_id` = '48'] 
SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -OUQnt -M /opt/librenms/mibs udp:HOSTNAME:161 1.3.6.1.4.1.1918.2.13.10.50.10.0]
.*.4.1.19*.50.10.0 = **35**

Checking (snmp) current Corriente de Rectificador ... 
**0 A**

So...I'm lost.
regards

**Comment by geordish** [comment]
That is odd... Check your database to make sure you don't have any extra entries for this inserted maybe?

SELECT * FROM sensors WHERE sensor_class = 'current' AND device_id = '48'

**Comment by ntmanxp** [comment]
It's odd, yes.

The select returns Empty.

**Comment by ntmanxp** [comment]
Well, after digging, I went directly to DB and set the row as expected.
Somehow, the $divisor, $oid, and so on, where like 'cached' by previus tests. And where wrong in the OID expected to poll.
I'll take a look tomorrow and see if still persists the 'normal' expected values.
Thanks

Andres

**Comment by holywyvern** [comment]
The problem goes like this, when we run

```sh
php /opt/librenms/discovery.php -h 192.168.0.1
```

Our discovery adds the sensor with device ID 41:

---
| sensor_id | sensor_deleted | sensor_class | device_id | poller_type | sensor_oid | sensor_index | sensor_type | sensor_descr | sensor_divisor | sensor_multiplier | sensor_current | sensor_limit | sensor_limit_warn | sensor_limit_low | sensor_limit_low_warn | sensor_alert | sensor_custom | entPhysicalIndex | entPhysicalIndex_measured | lastupdate | sensor_prev | 
| -: | -: | - | -: | - | - | - | - | - | -: | -: | -: | -: | -: | -: | -: | -: | - | - | - | - | -: | 
| 60 | 0 | current | 49 | snmp | .1.3.6.1.4.1.1918.2.13.10.50.10.0 | 0 | switchtec | Corriente de Rectificador  | 1 | 1 | 3 | 50 | \N | 10 | \N | 1 | Yes |  |  | 2017-02-11 12:31:42 | 3 | 
| 120 | 0 | current | 41 | snmp | .1.3.6.1.4.1.1918.2.13.10.50.10.0 | 0 | switchtec | Corriente de Rectificador  | 1 | 1 | 435 | 654 | \N | \N | \N | 1 | No | \N | \N | 2017-02-11 12:31:41 | 437 | 


But when the following cron job runs:

```sh
php /opt/librenms/discovery.php -h all
```

It deletes the device ID 41.
The strange part is than the device with ID 49 it's the same OS and same OIDs, even if the minor releases of the OS are different.

Tracing the variables, I detected than on the /includes/functions.inc.php:check_devices() function The $valid array is empty for device with ID 41, and has the following for device ID 49:

```
Array
(
    [current] => Array
        (
            [switchtec] => Array
                (
                    [0] => 1
                )

        )

    [voltage] => Array
        (
            [switchtec] => Array
                (
                    [0] => 1
                )

        )

)
```

**Comment by laf** [comment]
I'd suggest ensuring you are up to date, lots of sensor work and fixes have gone on in the last month.
