### ISSUE TITLE
New Device Support - VANGUARD 3480

### ISSUE THREAD

**Issue by dneto82** [librenms/librenms#5832]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

LibreNMS  | 85591375876e918d228d709d10fb97f7bb131cae
DB Schema | 160
PHP       | 7.0.14-pl1-gentoo
MySQL     | 5.7.12
RRDTool   | 1.6.01.6.0
SNMP      | NET-SNMP 5.7.3

----
Device: VANGUARD 3480
[Product Page]: (http://www.vanguardnetworks.com/products-3480.htm)
[Mibs Download]: (http://www.vanguardnetworks.com/support-downloads-mibs.htm)
[Product Solution Sheet]:(http://www.vanguardnetworks.com/Collateral/Documents/English-US/3480%20ASG%20Solutions%20Sheet.pdf)
[discovery.txt](https://github.com/librenms/librenms/files/761721/discovery.txt)
[poller.txt](https://github.com/librenms/librenms/files/761722/poller.txt)

**Comment by geordish** [comment]
You also need to provide
```
snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .

```

**Comment by dneto82** [comment]
Hi @geordish ,

My last mile ISP have set SNMP V1 devices, so I can't do bulk requests.

I'll request one device to test SNMP v2 or v3. But its possible get the necessary data using V1 until that?

**Comment by laf** [comment]
just use snmpwalk instead.

**Comment by dneto82** [comment]
As requested. My snmpwalk output

[VANGUARD3480.txt](https://github.com/librenms/librenms/files/826785/VANGUARD3480.txt)

**Comment by laf** [comment]
Merged
