### ISSUE TITLE
Duplicate Sensors

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#5839]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ X] Please provide as much detail as possible.
- [ X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hi,

For some reason I seem to have duplicate sensors - pictures attached. I tried removing all sensor related rrd data, and also turning sensors off (discovery and polling both), then back on (after running discovery and poller). No joy.
![image](https://cloud.githubusercontent.com/assets/8756384/22765910/5481f246-ee38-11e6-99b2-45660c683444.png)
![image](https://cloud.githubusercontent.com/assets/8756384/22765921/632100f8-ee38-11e6-96a1-8cd1c280d68a.png)

Thoughts?

Thanks!

**Comment by InsaneSplash** [comment]
Could you attach the debug output from the discovery using the -d option?

**Comment by laf** [comment]
We need the info in point 3

**Comment by laf** [comment]
Oh and btw, if this only started after the patch for sensors dropping was merged then we will most likely just have to remove that patch and you will possibly have to live with sensors being removed and re-added occasionally. lmsensors seems flaky at best.

**Comment by arrmo** [comment]
I'm OK with clearing out historical data to get to the bottom of this, NP. That said ... how do I remove all history of this, sort of clean slate?

And here is the info,
Discovery: https://paste.ubuntu.com/23963255/
Poller: https://paste.ubuntu.com/23963260/
snmpwalk: https://paste.ubuntu.com/23963263/

Thanks!

**Comment by laf** [comment]
`delete from sensors where device_id=35;`
`./discovery.php -h 35 -d -m sensors`

**Comment by arrmo** [comment]
OK, that cleaned it up - thanks!
