### ISSUE TITLE
HUAWEI S5700-52X-LI-48CS-AC  AGAIN DBM VALUES Missing

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#5843]
Hi Laf !

Currently the dbm Values are missing again for this switches ?!

latest librenms update installed :-(

kind regards

kristoferus75

**Comment by laf** [comment]
No info provided

**Comment by kristoferus75** [comment]
Laf Laf !

This is the same switch that works and suddently not !

I thing that is not correct always close issues .

**Comment by laf** [comment]
I am closing your issues because you are literally providing no information for us to help you with

**Comment by kristoferus75** [comment]
What information should i send it works after you implement the calc from
huawei and now suddently no dbm values available no graphs to see  ?

only voltage and temprature of the sensors graphs ?!  We change nothing on
the huawei switch -> no software update no config chage .

i can only revert the update of librenms and im sure it works after
downgrade ...



2017-02-09 23:27 GMT+01:00 Neil Lathwood <notifications@github.com>:
