### ISSUE TITLE
Sensors dBm that High Alarm Threshold eq 0 seems off?

### ISSUE THREAD

**Issue by falkowich** [librenms/librenms#5845]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
==========================================================
LibreNMS  | 61b73e8a73e145823a3afff0c735e32f1a3c78c0
DB Schema | 155
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 5.7.17-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
-------------------------------------------------------------------------------------------------------------------
After some updates we get lots of critical sensor warnings about low dBm on interfaces.
Seems that interfaces that have a High Alarm threshold eq 0 is sorted wrong?

Some debug:

IOS:
           Optical            High Alarm  High Warn  Low Warn   Low Alarm
           Transmit Power     Threshold   Threshold  Threshold  Threshold
Port       (dBm)              (dBm)       (dBm)      (dBm)      (dBm)
---------  -----------------  ----------  ---------  ---------  ---------
Gi1/0/7     -6.0                 0.0        -1.0       -11.0      -12.0
Gi1/0/7     -9.6                -3.0        -4.0       -24.0      -24.9

./discovery.php -h hostname -d (interesting parts)

entPhysicalName.1059 = Gi1/0/7 Transmit Power Sensor
entPhysicalName.1060 = Gi1/0/7 Receive Power Sensor

entSensorThresholdValue.1059.1 = 0
entSensorThresholdValue.1059.2 = -10
entSensorThresholdValue.1059.3 = -110
entSensorThresholdValue.1059.4 = -120
entSensorThresholdValue.1060.1 = -30
entSensorThresholdValue.1060.2 = -40
entSensorThresholdValue.1060.3 = -240
entSensorThresholdValue.1060.4 = -249

Scrot shows strange thresholds on Gi1/0/7 Transmit.

![image](https://cloud.githubusercontent.com/assets/1552705/22784392/269e1de4-eed0-11e6-8efd-54481afa1809.png)

--
Regards Falk

**Comment by laf** [comment]
You need to provide all the info asked for in point 3.

**Comment by kristoferus75** [comment]
I have the same problem suddently with huawei switches !

**Comment by falkowich** [comment]
@laf Sry, I was on an _interesting_ citrix session with no cut'n paste function for the moment..
But now it's updated :)

**Comment by laf** [comment]
I can't see any of the debug information

**Comment by falkowich** [comment]
@laf I included the interesting part from the discovery -d? 

> entSensorThresholdValue.1059.1 = 0
> entSensorThresholdValue.1059.2 = -10
> entSensorThresholdValue.1059.3 = -110
> entSensorThresholdValue.1059.4 = -120
> entSensorThresholdValue.1060.1 = -30
> entSensorThresholdValue.1060.2 = -40
> entSensorThresholdValue.1060.3 = -240
> entSensorThresholdValue.1060.4 = -249

Or do you want the whole debug from the ./discovery.php -h hostname -d?

**Comment by laf** [comment]
We need everything in point 3 to avoid going back and forth.

**Comment by falkowich** [comment]
@laf Ah, sry if feel lazy.. 
I tried to pinpoint the problem. Going to update the debug info asap :)

**Comment by laf** [comment]
Feel free to provide the info when you get it.
