### ISSUE TITLE
Power, temperature and fan speed not shown on Extreme Summit X650

### ISSUE THREAD

**Issue by atdtn** [librenms/librenms#5850]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 8aa2480c05e20f2bd0b975925cef34e5d0a8038f
DB Schema | 160
PHP       | 5.6.13-0+deb8u1
MySQL     | 5.5.46-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
http://pastebin.com/iuk9qEMA
http://pastebin.com/MBgRWBHX
snmp walk part1
http://pastebin.com/N0xcKqcH
snmp walk part2
http://pastebin.com/z6uTN0Sy

- [x] Please provide as much detail as possible.
In http://librenms/mibs/ not shown EXTREME-BASE-MIB
How to add EXTREME-BASE-MIB ?
-rw-r--r-- 1 librenms librenms 776070 Feb 9 18:53 /opt/librenms/mibs/extreme/EXTREME-BASE-MIB
![image](https://cloud.githubusercontent.com/assets/12551051/22796493/2ec154e0-ef03-11e6-8c1c-9d1cd97422aa.png)

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
You need to provide the information asked for when creating an issue and not just remove it :(

**Comment by atdtn** [comment]
Sorry for that. I corrected my message.

**Comment by Rosiak** [comment]
Can you supply a walk of the EXTREME-SYSTEM-MIB with the mib loaded?
