### ISSUE TITLE
Display Routing Table

### ISSUE THREAD

**Issue by network-guy** [librenms/librenms#5852]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
==========================================================
Component | Version
--------- | -------
LibreNMS  | 5919408ad118489c3d3e0e4d15c8c3125d168451
DB Schema | 160
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Has there been any requests for displaying routing tables for layer 3 devices, and maybe monitoring the number of routes in the routing table? I'm trying to minimize the need to log directly into devices to pull information or do basic troubleshooting. This would also allow me to hand off first level troubleshooting to the NOC or help desk.  

It looks like on IOS devices this can be polled using the IP-FORWARD-MIB, I'm not sure about non-Cisco devices. I don't think it would take a ton of effort to implement this (at least for IOS-based devices). I'd be happy to drill into it if nobody else has time, but I don't do much coding and I'm not terribly familiar with the code base.

**Comment by Rosiak** [comment]
We already poll IP-FORWARD-MIB.
You'll find it under:
device/device=X/tab=graphs/group=netstats/

**Comment by laf** [comment]
We already have a route discovery module.

However this is more a feature request than anything else, please post this on the community forums.
