### ISSUE TITLE
Thumbnail hidden out of window

### ISSUE THREAD

**Issue by ouafnico** [librenms/librenms#5853]
Hello

On an uptodate installation, when I move the cursor to the last view on the right, the thumbnail show out of the window.

For example here:

![capture](https://cloud.githubusercontent.com/assets/807350/22821256/98bb8d1c-ef7a-11e6-9b17-aee93a864a8f.PNG)

**Comment by ouafnico** [comment]
Here are the info:

==========================================================
Component | Version
--------- | -------
LibreNMS  | fd7cf79c72e9e9a637661b30559a79163db8214c
DB Schema | 161
PHP       | 7.0.15
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful

About the issue, It's only the last graph on the right, The graph which appear as preview from the mouse is always generated a little on the left of the mouse, but if your mouse if near the window's border the grah is out. When I'm on the left of the graph I still can't view it entierly (and a scrollbar appears).

If I can help somehow :s 

![capture](https://cloud.githubusercontent.com/assets/807350/22821951/98c56bb8-ef7d-11e6-9437-9427e98cec7e.PNG)

**Comment by laf** [comment]
I don't get that issue.

Browser version? Window resolution size?

**Comment by ouafnico** [comment]
Browser, Firefox 51 or chrome 55 tested (Win10).
Windows resolution is 1680x1050.

**Comment by laf** [comment]
The only way I can replicate this is by starting my hover on the very right hand side of the image but in general day to day I don't see this happening.

I don't think we can do much with this as it's a 3rd party library which I don't think is updated anymore.

Proposing to close @librenms/reviewers

**Comment by laf** [comment]
No further info provided
