### ISSUE TITLE
rrd_dir problem 

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#586]
I ask this question for a second time .

I build my develop environment like this :
```
 osx + vagrant + ubuntu1404 
```

Vagrantfile: 

```
config.vm.synced_folder "./librenms", "/opt/librenms", owner:"www-data", group:"www-data"
```

config.php
```
$config['rrd_dir'] = '/opt/librenms_config/rrd';
```

`/opt/librenms_config` file is not a shared file .

But I also got the `Error Drawing Graph` problem .

You say that  ` rrd file`  make a map from file to memory, now I set the `rrd_dir` on the ubuntu1404 and other source code on osx  .

This makes me comfortable to edit the source code .

How to solve this problem ?

**Comment by laf** [comment]
Hi @wzhsunn 

I'm really sorry but I'm unsure what you mean by this. For the error drawing graph, try adding debug=yes to the end of the url.

**Comment by wzhsunn** [comment]
I put source code on my osx pc and shared it with ubuntu1404 which running librenms (At this situation , I can edit my code easily via sublime ).
the file system of osx and ubuntu1404 is different so that the rrd file drawed failed.
But now I config the rrd_dir to put it on ubuntu1404, but the error drawing graph was also there .

**Comment by laf** [comment]
What hardware is Ubuntu on? rrd files have a limitation that you can't just copy them to another architecture so you might be hitting that limit. You would have to export and re-import them to be able to change architecture.

**Comment by wzhsunn** [comment]
Ubuntu1404  is on (vagrant) virtual box. 
Last time when I put librenms on ubuntu1404, every thing work well .

**Comment by wzhsunn** [comment]
I try debug=yes and got this:

```
graph /tmp/q6m27s5Apf6PIqRS.png --alt-autoscale-max --rigid -E --start 1426048999 --end 1426135399 --width 1075 --height 300 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal COMMENT:' Current Average Maximum' COMMENT:'Total' COMMENT:'\n' CDEF:inB= CDEF:outB= CDEF:octets=inB,outB,+ CDEF:doutB=outB,-1,* CDEF:inbits=inB,8,* CDEF:outbits=outB,8,* CDEF:bits=inbits,outbits,+ CDEF:doutbits=doutB,8,* VDEF:95thin=inbits,95,PERCENT VDEF:95thout=outbits,95,PERCENT VDEF:d95thout=doutbits,5,PERCENT VDEF:totin=inB,TOTAL VDEF:avein=inbits,AVERAGE VDEF:totout=outB,TOTAL VDEF:aveout=outbits,AVERAGE VDEF:tot=octets,TOTAL COMMENT:' \n' HRULE:999999999999999#FFFFFF:'Total In ': GPRINT:inbits:LAST:%6.2lf%s GPRINT:inbits:AVERAGE:%6.2lf%s GPRINT:inbits:MAX:%6.2lf%s GPRINT:totin:%6.2lf%sB COMMENT:'\n' HRULE:999999999999990#FFFFFF:' Out': GPRINT:outbits:LAST:%6.2lf%s GPRINT:outbits:AVERAGE:%6.2lf%s GPRINT:outbits:MAX:%6.2lf%s GPRINT:totout:%6.2lf%sB COMMENT:'\n' HRULE:999999999999990#FFFFFF:' Agg': GPRINT:bits:LAST:%6.2lf%s GPRINT:bits:AVERAGE:%6.2lf%s GPRINT:bits:MAX:%6.2lf%s GPRINT:tot:%6.2lf%sB COMMENT:'\n' HRULE:0#999999

command returned 1 (ERROR: String ends after the = sign on 'CDEF:inB=' )

OK u:0.03 s:0.00 r:0.04
graph /tmp/q6m27s5Apf6PIqRS.png --alt-autoscale-max --rigid -E --start 1426048999 --end 1426135399 --width 1075 --height 300 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal HRULE:0#555555 --title='Error Drawing Graph'

command returned 1 (1156x359 )


Runtime 0.10229110717773 secs
MySQL: Cell 0/0s Row 6/0.001s Rows 2/0s Column 0/0s
```

**Comment by wzhsunn** [comment]
I think I found a solution share code with virtual box and my host pc( win or mac) using sshfs .

Routes and win7 draw ok when delete it and add it .

But the localhost  draw with errors .

I don't know why .

**Comment by laf** [comment]
I'm sorry but this is such a custom setup and not something I've got experience in so can't help any further @wzhsunn :(

**Comment by wzhsunn** [comment]
How did you setup yours ? Maybe mine is very tedious.
