### ISSUE TITLE
CentOS7: memcached documentation incorrect(?)

### ISSUE THREAD

**Issue by fenice2** [librenms/librenms#5868]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

I've been considering implementing the distributed poller for a while and finally got round to starting on it today. There does seem to be some missing parts to the documentation for installing memcached on CentOS7 (I couldn't see this but I might just have missed it).

I don't know if these comments apply to earlier release of CentOS but the first thing is that the php bindings for memcached are named: php-pecl-memcached - that doesn't seem to be mentioned in the documentation. There are two versions of the php binding for memcached in the repos - one is php-pecl-memcache (an older version and not updated recently) and the second is the one I listed earlier and spelled with a trailing "d" and that's the most recent version and it also supports more recent versions of php.

After installing memcached I went to look at the config file but the location given in the documentation is not correct for CentOS7, it should be: /etc/sysconfig/memcached

After installing the required  packages I modified config.php to enable memcached and an error popped-up on the libreNMS page saying the following:

"WARNING: You have enabled memcached but have not installed the PHP bindings. Disabling memcached support. Try 'apt-get install php5-memcached' or 'pecl install memcached'. You will need the php5-dev and libmemcached-dev packages to use pecl."

It took me a short while to realise I hadn't restarted nginx (and php-fpm, in my setup), once that was doen memcached was working correctly - it might be worth mentioning the web server needs to be restarted. :)

As I only use this on a home network with not too many devices I was looking at the distributed poller to just achieve a separation of the web UI and the polling functions,  I assume there's no problem doing that with just one poller?

**Comment by laf** [comment]
Please contribute your changes back to the documentation. 

You don't need to run distributed polling to achieve what you want. Just two installs pointing to the same MySQL database and shares rrd directory.

**Comment by fenice2** [comment]
Thanks for your comments about the two installs, I'll take a look at that. 

My apologies, I though documentation went here as well as bugs. How do I contribute the changes to the documentation?

**Comment by laf** [comment]
You can click the edit on GitHub icon on any of our doc pages. It will take you straight to the right page on GitHub and you can follow the flow there.

**Comment by laf** [comment]
No need to be left open
