### ISSUE TITLE
LLDP unable to discover devices by IP

### ISSUE THREAD

**Issue by towster** [librenms/librenms#5869]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

==========================================================
Component | Version
--------- | -------
LibreNMS  | 3c7792a170a0232a64754f3f07fb912ca5fff81b
DB Schema | 162
PHP       | 7.0.14
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

I have a bunch of devices that are seen by name via LLDP but LLDP discovery does not pull the IP address for discovery purposes. This RFC describes the MIB where the IP addresses are available. https://tools.ietf.org/html/rfc2922 and I was able to download the MIB file itself from here http://www.activeexperts.com/admin/mib/RFC/ptopo-mib/ 

The current lldp discovery identifies the device MAC address:
                            [lldpRemChassisId] => A8 97 DC 98 D2 00
Here is output from walk of .1.3.6.1.2.1.79 from one of my devices. Notice the MAC address matches. The IP of the neighbor is "0A 6F 08 9B"

.1.3.6.1.2.1.79.1.1.1.1.5.342519315.0.4958.0 = 4
.1.3.6.1.2.1.79.1.1.1.1.6.342519315.0.4958.0 = "A8 97 DC 98 D2 00 "
.1.3.6.1.2.1.79.1.1.1.1.7.342519315.0.4958.0 = 7
.1.3.6.1.2.1.79.1.1.1.1.8.342519315.0.4958.0 = "44"
.1.3.6.1.2.1.79.1.1.1.1.9.342519315.0.4958.0 = ccitt.0
.1.3.6.1.2.1.79.1.1.1.1.10.342519315.0.4958.0 = 1
.1.3.6.1.2.1.79.1.1.1.1.11.342519315.0.4958.0 = "0A 6F 08 9B "
.1.3.6.1.2.1.79.1.1.1.1.12.342519315.0.4958.0 = 3
.1.3.6.1.2.1.79.1.1.1.1.13.342519315.0.4958.0 = 3
.1.3.6.1.2.1.79.1.1.1.1.14.342519315.0.4958.0 = 2
.1.3.6.1.2.1.79.1.1.1.1.15.342519315.0.4958.0 = 0:0:00:00.00
.1.3.6.1.2.1.79.1.1.1.1.16.342519315.0.4958.0 = 1

**Comment by laf** [comment]
You've not provided any of the information in point 3 :(

**Comment by towster** [comment]
Sorry.. here are the files.. 

[discovery.10.110.200.60.txt](https://github.com/librenms/librenms/files/769867/discovery.10.110.200.60.txt)
[poller.10.110.200.60.txt](https://github.com/librenms/librenms/files/769866/poller.10.110.200.60.txt)
[snmpbulkwalk.10.110.200.60.txt](https://github.com/librenms/librenms/files/769868/snmpbulkwalk.10.110.200.60.txt)

**Comment by towster** [comment]
I cant figure out how to reopen this - just creating new issue
