### ISSUE TITLE
The Eventlog entries is empty when delete a device 

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#587]
![a05 ax2 f3uhnzvef exj41](https://cloud.githubusercontent.com/assets/528348/6599232/9fdb3634-c843-11e4-90a6-93018f518384.jpg)

Alertlog entries has the same problem :

![u1 qruh fsd8 ny1u m7r4](https://cloud.githubusercontent.com/assets/528348/6599255/c46982f8-c843-11e4-8afd-5dc9f852d7f3.jpg)

**Comment by f0o** [comment]
This is a known bug.
Delete device doesnt run a recursive cleanup through all tables.

It will be fixed in near future

**Comment by wzhsunn** [comment]
OK,  I close this  one .

**Comment by ryanmerolle** [comment]
Any recommendations on a join query to figure out what objects are not associated to a devices.  I want to use that to script out my own db cleanup.

**Comment by f0o** [comment]
Join might not work but a Sub-Select may...

Mostly you want to pick those entries that dont have a match on host/device_id from the devices table...

I cant give an example at the moment, sorry
