### ISSUE TITLE
Eventlog loops between Icon -> and Device Icon changed => x

### ISSUE THREAD

**Issue by adammmmm** [librenms/librenms#5873]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 9384d306ac968a2cf727cb0c74853164d15a1e36
DB Schema | 163
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

Since the daily update on feb 11th eventlog is filled with System Icon -> and Device Icon changed => x.png/svg. It seemingly occurs with every kind of device, localhost, cisco and junos tested.
Using poller-service if that has to do with anything. Screenshot shows an example of one device.
![image003](https://cloud.githubusercontent.com/assets/12120653/22875557/b2516c7a-f1cc-11e6-9741-5686843af5ab.png)

**Comment by laf** [comment]
We need the output of `./discovery.php -h HOSTNAME -d -m os`

**Comment by laf** [comment]
Oh and `./poller.php -h HOSTNAME -r -f -d -m os`

**Comment by adammmmm** [comment]
Gimme a minute, need to censor couple things :)

**Comment by laf** [comment]
Think I've found it.

**Comment by adammmmm** [comment]
Cool, here's output otherwise:

[discovery-router.txt](https://github.com/librenms/librenms/files/770485/discovery-router.txt)
[poller-router.txt](https://github.com/librenms/librenms/files/770484/poller-router.txt)

**Comment by InsaneSplash** [comment]
Ive seen the same :)

**Comment by apayne** [comment]
Discovered this exact issue this morning.  It's minor but annoying.  At this point, I'm assuming there has been a change in the latest auto-update leading to it.  You can see it flopping every so many hours - perhaps part of the discovery process is leading to it?
![librenms icon changed issue](https://cloud.githubusercontent.com/assets/85126/22897328/250e7004-f1d8-11e6-9ae1-7c113a432a82.png)

**Comment by laf** [comment]
A pr is already in the queue just waiting to be mergered
