### ISSUE TITLE
RICOH Aficio MP 2352 (print/scan/fax counter,toner level)

### ISSUE THREAD

**Issue by NK74** [librenms/librenms#5875]
DO NOT DELETE THIS INFORMATION.

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

- - - -
| **Component** | **Version**|
| --- | --- |
| LibreNMS   | 4ef0a2d719b54ad1e8f1666667763cb99248dbd1|
| DB Schema | 163 |
| PHP       | 7.0.13-0ubuntu0.16.10.1
| MySQL     | 10.0.29-MariaDB-0ubuntu0.16.10.1
| RRDTool   | 1.6.0
| SNMP      | NET-SNMP 5.7.3

**Discovery:**
https://gist.github.com/NK74/c243817e34f6cb0d5129c829da25c954

**Poller:**
https://gist.github.com/NK74/566f41d6a0be907076159f8149252ee9

**Snmpbulkwalk:**
https://gist.github.com/NK74/4cff9ea638922fe8327941fc37a59a83

Please add this informations:
.1.3.6.1.4.1.367.3.2.1.7.2.3.8.0 = Product number
.1.3.6.1.4.1.367.3.2.1.2.19.1.0 = Printer + Copier 
.1.3.6.1.4.1.367.3.2.1.2.19.2.0 = Printer Black & White 
.1.3.6.1.4.1.367.3.2.1.2.19.3.0 = Fax Black & White 
.1.3.6.1.4.1.367.3.2.1.2.19.4.0 = Copier Black & White 
.1.3.6.1.4.1.367.3.2.1.2.19.5.1.9.27 = Scanner Send
.1.3.6.1.4.1.367.3.2.1.2.19.5.1.9.28 = Fax Transmission

.1.3.6.1.2.1.43.16.5.1.2.1.1 = "Niveau bas : Toner"
.1.3.6.1.4.1.367.3.2.1.2.24.1.1.5.1 = -100 (Empty toner) / 100 full

![image](https://cloud.githubusercontent.com/assets/17825769/22888290/6fc99920-f205-11e6-8f37-d8e01566af48.png)
****

![image](https://cloud.githubusercontent.com/assets/17825769/22887602/fc833a18-f202-11e6-86de-45688819001a.png)

**Comment by laf** [comment]
Please post feature requests on the community forum.
