### ISSUE TITLE
Alerts on access_point.xxx things do not link to the access point (like ports do)

### ISSUE THREAD

**Issue by towster** [librenms/librenms#5878]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Would it be possible to have the Access Point link to the access point page like ports link to the port page? 

![capture](https://cloud.githubusercontent.com/assets/1965956/22890930/5fb335dc-f1d3-11e6-89bb-cdbf5c4b72a1.PNG)

**Comment by laf** [comment]
This really belongs as a feature request!

However please try this patch:

```
diff --git a/html/includes/functions.inc.php b/html/includes/functions.inc.php
index 681930f..2dfef49 100644
--- a/html/includes/functions.inc.php
+++ b/html/includes/functions.inc.php
@@ -1128,6 +1128,11 @@ function alert_details($details)
             $fallback      = false;
         }

+        if ($tmp_alerts['accesspoint_id']) {
+            $fault_detail .= generate_ap_url($tmp_alerts) . ';&nbsp;';
+            $fallback      = false;
+        }
+
         if ($tmp_alerts['type'] && $tmp_alerts['label']) {
             if ($tmp_alerts['error'] == "") {
                 $fault_detail .= ' '.$tmp_alerts['type'].' - '.$tmp_alerts['label'].';&nbsp;';

```

**Comment by towster** [comment]
Thanks for making a patch. It is close. I tested the code. It generates the URL but it is not a link. Here is what it looks like:

<img width="445" alt="alert" src="https://cloud.githubusercontent.com/assets/1965956/22916471/625b7cc4-f244-11e6-81f4-9e347a5fb9b2.png">

**Comment by towster** [comment]
I did a little playing with the code and got it to display nicely.

```
        if ($tmp_alerts['accesspoint_id']) {
            $fault_detail .= generate_ap_link($tmp_alerts,$tmp_alerts['name']) . ';&nbsp;';
            $fallback      = false;
        }

```
![capture](https://cloud.githubusercontent.com/assets/1965956/22937903/a6f6f68c-f29f-11e6-9fe8-1b19b6340800.PNG)
