### ISSUE TITLE
PDU's discovery of outlet banks, but banks then are removed after being polled

### ISSUE THREAD

**Issue by jsdurling** [librenms/librenms#5881]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 4ef0a2d719b54ad1e8f1666667763cb99248dbd1
DB Schema | 163
PHP       | 7.0.14
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.

I had numerous PDU's that were reporting the bank1, bank2, and total polling properly up until midnight on Feb 3.  Since them, I can manually run a discovery and the bank1, bank2, and bank total shows up, and the poller will poll them, but after a period of time, the PDU banks are missing.  Across all the PDU's/

- [X ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
https://gist.github.com/jsdurling/e1630324132b45c88167a884dee103f0

https://gist.github.com/jsdurling/36de6269ded3f5a7f6196f297cda1531

**Comment by laf** [comment]
You haven't provided the information we ask for and instead have provided snippets which are of no use to us.

**Comment by jviersel** [comment]
I experience the same problem with ipoman powerbars. I discovered the sensors are removed during discovery-process for all scanned powerbars, except the last one. If i use a pattern for the hostname while running discovery.php, only the last matching hostname keeps it sensors. When i use an exact hostname, all sensors are added (probably because there's just one hostname in the list of matches).

**Comment by laf** [comment]
We need the info asked for in point 3 above, in this situation with two hosts run at the same time to see the data.

**Comment by jviersel** [comment]
Here's the output of discovery.php for 2 hosts: [discovery.txt](https://github.com/librenms/librenms/files/787739/discovery.txt)

I expect the output of discovery.php to be enough, as the issue is discovery-related. If you also need the output of poller.php, please let me know.

**Comment by jsdurling** [comment]
Yeah, I totally missed what you needed, it was right in front of my face, but I just didn't realize what you were asking for.  :-/  

So, attached are the needed files.  My sincere apologies. 

[pdu.discovery.txt](https://github.com/librenms/librenms/files/794602/pdu.discovery.txt)
[pdu.poller.txt](https://github.com/librenms/librenms/files/794603/pdu.poller.txt)
[pdu.snmpbulkwalk.txt](https://github.com/librenms/librenms/files/794604/pdu.snmpbulkwalk.txt)

**Comment by laf** [comment]
@jviersel I don't think your issue is the same, please test: https://github.com/librenms/librenms/pull/5983

**Comment by murrant** [comment]
Neither of these snmpbulkwalks are correct.  You need the `.` (dot) at the end of the command:
`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .`

**Comment by jsdurling** [comment]
Attaching the correct bulkwalk.  

[pdu.snmpbulkwalk.txt](https://github.com/librenms/librenms/files/800094/pdu.snmpbulkwalk.txt)

**Comment by jsdurling** [comment]
Using the discovery-wrapper.py rather than the standard discovery.php in my crond job appears to fix this. I'll do some additional testing.

**Comment by wdst-gcet** [comment]
We have noticed something similar with our Eaton PDUs. When we discover them using the capture feature in the web UI all the outlets show up. But after a few hours the outlets are deleted. We see this activity in the event viewer. 

<img width="1417" alt="screen shot 2017-02-27 at 7 49 13 pm" src="https://cloud.githubusercontent.com/assets/20130657/23386696/f9dffb10-fd25-11e6-959a-2372758733f3.png">

**Comment by laf** [comment]
@jviersel can you test the patch I linked to above as I think that will fix your problem.

**Comment by laf** [comment]
Pretty sure this is now resolved.
