### ISSUE TITLE
Eventlog Interface names missing

### ISSUE THREAD

**Issue by mjclancyau** [librenms/librenms#5883]
Hi Guys,

Following update recently, the eventlog is now not showing interface names for interface events, as per the below screencap:

![image](https://cloud.githubusercontent.com/assets/11141825/22910135/bd0d12ea-f2a3-11e6-8d0f-c0ee1178d508.png)

The actual interfaces on the device are showing up fine, just not being reflected in the eventlog.

Possibly related to the recent event log changes for severity?  As this is only affecting eventlog I don't think this is related to poller/discovery, so haven't posted the log output here, but let me know if it is needed.

Any help much appreciated.

Kind regards,
Matt

--------------------------------------------------------------------

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the 
```
==========================================================
Component | Version
--------- | -------
LibreNMS  | f03d8b0a30ecac80fbceb839f75c74c3cd1f5e74
DB Schema | 163
PHP       | 7.0.15
MySQL     | 10.1.21-MariaDB
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.5
==========================================================
```
section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by InsaneSplash** [comment]
Hi Matt,

Thanks for the report. It may only be limited to those 2 events.

**Comment by laf** [comment]
I can't see this, the log_event() messages for ports seems fine to me.

**Comment by InsaneSplash** [comment]
I ran some checks against a lab router and I am not able to replicate your issue. Would you mind providing some more detail, ie what device you are checking?

Does your validate.php pass?

**Comment by InsaneSplash** [comment]
Looking at your screenshot again, I see these logs are from the 13th. New events should show up fine now.
Please run a ./daily.sh to make sure you are on the latest code.

**Comment by laf** [comment]
Fairly sure this isn't in the current release, closing.

**Comment by mjclancyau** [comment]
Thanks guys - does seemed to be resolved now on a later daily update.
