### ISSUE TITLE
Could not add new host

### ISSUE THREAD

**Issue by atdtn** [librenms/librenms#5884]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

==========================================================
Component | Version
--------- | -------
LibreNMS  | f03d8b0a30ecac80fbceb839f75c74c3cd1f5e74
DB Schema | 
PHP       | 7.0.15-1~dotdeb+8.1
MySQL     | 10.0.29-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
Clean install.
I get the error "Could not connect, please check the snmp details and snmp reachability" when I try and add any host via cli or web interface. I try to check box "Force add" - no effect.
SQL Strict mode - disabled.

root@debian:/opt/librenms# ./addhost.php localhost community v2c
Could not connect, please check the snmp details and snmp reachability

No problem with snmpd on the host.
root@debian:/opt/librenms# snmpwalk -v2c -c community localhost
SNMPv2-MIB::sysDescr.0 = STRING: Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64

If i run "./discovery.php -d -v -h all" i receive a lot of SQL errors. Link to pastebin:

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

http://pastebin.com/8w1idtYF

**Comment by laf** [comment]
Please use irc or the community forums for general support and help
