### ISSUE TITLE
Cosmetic Issue - Device Name Far away from Icon

### ISSUE THREAD

**Issue by NetCo-Jan** [librenms/librenms#5890]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

librenms@librenms:~$ ./validate.php 
==========================================================
Component | Version
--------- | -------
LibreNMS  | 1e2ab7323948563402203c0ea6de29e39e43787b
DB Schema | 164
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

Hi Guys
know there is people with real problems but i have OCD and the Name of the device is now far away from the icon since last update

would be nice to have it back / closer to Icon - see before and after attachement 
thank you
Jan

![cosmetic issue](https://cloud.githubusercontent.com/assets/24909687/22929197/fccef7e4-f2c2-11e6-9317-8e356caa1a6e.png)

**Comment by NetCo-Jan** [comment]
see attachment

**Comment by laf** [comment]
Varying sizes of icons now make this not possible so we've settled on static sized areas.
