### ISSUE TITLE
Custom thresholds for progress bars

### ISSUE THREAD

**Issue by rpenziol** [librenms/librenms#5895]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

New feature:

As described here: https://community.librenms.org/t/custom-thresholds-for-progress-bars/572
Using storage warning percentage from a devices' edit page to change the progress bars red on the storage health page and the device's overview page.

Additionally, adding the ability to set warning percentages to CPUs and memory pools from a devices 'edit' pages, then using these values to set the red progress bar threshold for their health pages and the device's overview page.

**Comment by rpenziol** [comment]
I have a working solution for this features. Made the issue for tracking purposes.

**Comment by laf** [comment]
Merged in
