### ISSUE TITLE
Export alerting or other results to pdf or excel as reports  

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#590]
I saw that /html/pdf.php.
But how to use it to export some reports ?

**Comment by f0o** [comment]
Do you want pdfs to be created on an alert or do you want to export past alerts (from the log for example) as pdf?

**Comment by wzhsunn** [comment]
Past alerts as pdf .

**Comment by f0o** [comment]
that's not yet possible but I'll put it on my ToDo.

please keep this issue open until I merge the patch for it :)

**Comment by f0o** [comment]
Hrm
`html/pdf.php` wont even work as these requirements arent met:
```php
require_once("includes/tcpdf/config/lang/eng.php");
require_once("includes/tcpdf/tcpdf.php");
```

**Comment by wzhsunn** [comment]
I see.
Thank you !
I am looking forward to that!
I will keep my constant attention for it .

**Comment by laf** [comment]
Exporting to pdf was in the billing section but didn't work so we ripped the code out :)

**Comment by f0o** [comment]
@laf oh I see. was the TCPDF class nonfunctional or what exactly didnt work?

**Comment by laf** [comment]
afaik, it wasn't functioning.

**Comment by f0o** [comment]
I see, I might be able to fix it.. I'll put it on my list :)

**Comment by wzhsunn** [comment]
Thank you !
