### ISSUE TITLE
Librenms identifies Dell PowerConnect M8024-k as generic os 

### ISSUE THREAD

**Issue by infraATE** [librenms/librenms#5905]
Since 05th Frebruary LibreNMS identifies my Dell PoweConnect M8024-k as "generic device". All my M8024-K have been modified from "powerconnect" to "generic os".

Here are the logs :
  2017-02-05 07:00:13 	System	Device status changed to Up from check.
  2017-02-05 06:55:14 	System	Device status changed to Down from icmp check.
  2017-02-05 00:40:03 	System	OS Features ->
  2017-02-05 00:40:02 	System	Device type changed network => server
  2017-02-05 00:38:40 	System	Device OS changed powerconnect => generic
  2017-02-05 00:38:40 	System	Device Icon changed dell.svg => generic.svg

**The discovery.php :**

php discovery.php -m os -h 172.16.204.11 -d

LibreNMS Discovery
Version info:
Commit SHA: 3fd56d729729ad036f6ab948d8f22c611ce58c9b
DB Schema: 164
PHP: 7.0.13
MySQL: 5.5.50-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2
DEBUG!
SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1]
DB Schema already up to date.
SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE '172.16.204.11' ORDER BY device_id DESC]
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '9']
172.16.204.11 9 generic SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0]
PowerConnect M8024-k, *, VxWorks 6.6

SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Ovqn -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysObjectID.0]
.*.4.1.674.10895.3041

| PowerConnect M8024-k, 5.1.10.1, VxWorks 6.6 | .1.3.6.1.4.1.674.10895.3041 |
SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Oqvn -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalDescr.1]

SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 SML-MIB::product-Name.0]
No Such Object available on this agent at this OID

SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Osqnv -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalMfgName.1]

Modules status: Global+ OS  Device
#### Load disco module os ####
SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0]
PowerConnect M8024-k, *, VxWorks 6.6

SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Ovqn -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysObjectID.0]
.*.4.1.674.10895.3041

| PowerConnect M8024-k, 5.1.10.1, VxWorks 6.6 | .1.3.6.1.4.1.674.10895.3041 |
SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Oqvn -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalDescr.1]

SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 SML-MIB::product-Name.0]
No Such Object available on this agent at this OID

SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Osqnv -M /opt/librenms/mibs udp:HOSTNAME:161 ENTITY-MIB::entPhysicalMfgName.1]

>> Runtime for discovery module 'os': 0.2460 seconds with 1176 bytes
#### Unload disco module os ####

SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '9' AND `attrib_type` = 'poll_mib' ]
SQL[UPDATE `devices` set `last_discovered` =NOW(),`last_discovered_timetaken` ='0.597' WHERE `device_id` = '9']
Discovered in 0.597 seconds

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('discover','172.16.204.11','1487158836.0646','0.672','1','*****\n')]
discovery.php 172.16.204.11 2017-02-15 12:40:36 - 1 devices discovered in 0.672 secs
SNMP: Get[10/0.39s] Walk [0/0.00s]
MySQL: Cell[3/0.00s] Row[1/0.00s] Rows[4/0.00s] Column[0/0.00s] Update[1/0.00s] Insert[1/0.00s] Delete[0/0.00s]

I have no issue with my PowerConnect M6220.

**The validate.php** 

php validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | 3fd56d729729ad036f6ab948d8f22c611ce58c9b
DB Schema | 164
PHP       | 7.0.13
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by murrant** [comment]
Hmm, 10895.3042 seems to be a dnos device, so just add this device specifically...
