### ISSUE TITLE
Email sending

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#591]
Is there a document for email config so that it can send email with some interval (for example every Friday) ?

**Comment by f0o** [comment]
Email-Configuration can be found here: http://docs.librenms.org/Extensions/Alerting/#transports-email

Intervals for alerts are defined in the Alert-Rule. However these are minute-specific intervals, so "Alert Every X Minutes".

**Comment by wzhsunn** [comment]
Thank you, I am sorry I didn't read the doc carefully .
