### ISSUE TITLE
Eventlog: temperature events not logged due to wrong quoting

### ISSUE THREAD

**Issue by craig** [librenms/librenms#5916]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
```
Component | Version
--------- | -------
LibreNMS  | e017f7a71b40918909bcc513c491b3ddc2fbc7af
DB Schema | 164
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.54-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
```
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

I've run into an issue: eventlog data from temperature sensors isn't being logged in logs/librenms.log.
I get these messages:

    2017-02-16 03:10:04 MySQL Error: Unknown column 'temperature' in 'field list' (INSERT INTO eventlog (host,device_id,reference,type,datetime,severity,message) VALUES ('1','1','5',temperature,NOW(),'4',' Core 1 above threshold: 44 (> 41.6 )'))

When running the poller command from cmdline: ./poller.php -h TESTHOST -d -r -f -m sensors

I get: 
[RRD Disabled]Alerting for TESTHOST Core 2
SQL[INSERT INTO eventlog (host,device_id,reference,type,datetime,severity,message) VALUES ('1','1','6',temperature,NOW(),'4',' Core 2 above threshold: 43 (> 40 )')]

temperature is not quoted, if you use that sql query with quotes, it works fine.
I've been trying to pinpoint it down and found includes/polling/functions.inc.php, but now it's time for bed. Hopefully this is helpful, good night.

**Comment by laf** [comment]
Do you consistently get this?

**Comment by InsaneSplash** [comment]
Sounds like something @Laf you fixed before?

**Comment by craig** [comment]
Yes, it was happing all the time. However, it's gone now: I deleted the database and recreated it; I can't reproduce it anymore. Theory: the machine crashed while running daily.sh? Anyways, thank you! :)

**Comment by laf** [comment]
@InsaneSplash well fixed because someone reported similar but I couldn't reproduce.
