### ISSUE TITLE
Add CPU graph for Smart Edge 600

### ISSUE THREAD

**Issue by kyob** [librenms/librenms#5917]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | d06aaaa222fefc083dd1c60dce1ad1cbbaf8100b
DB Schema | 164
PHP       | 7.0.15
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

- [discovery.php](https://gist.github.com/kyob/8e2b04af8b00ea8e9debf2f5826a8325)
- [poller.php](https://gist.github.com/kyob/ecf447c2e4d1684bd1599c08157ed76e)
- [snmpwalk](
https://mega.nz/#!tIsmWC6L!Y4wnf3Aa_bWLcfSjCjQLdFLlr2FlwFa4Xcd_zNqv6jg
)

**CPU OID:**

1. rbnCpuMeterFiveSecondAvg **1.3.6.1.4.1.2352.2.6.1.1**
2. rbnCpuMeterOneMinuteAvg **1.3.6.1.4.1.2352.2.6.1.2**
3. rbnCpuMeterFiveMinuteAvg **1.3.6.1.4.1.2352.2.6.1.3**

**Comment by geordish** [comment]
Your snmpwalk doesn't include the full tree. It probably timed out when retrieving it.

Can you try walking .1.3.6.1.4.1.2352?

**Comment by kyob** [comment]
@geordish [.1.3.6.1.4.1.2352](
https://mega.nz/#!od0y3C4J!T0WSZPRHYv-rqwEr7mJF7MYURLmkdjn9nSJzsURQVWs
) but it's not all because I got **timed out**

**Comment by geordish** [comment]
Created PR #5953. Mind testing?

**Comment by kyob** [comment]
After https://github.com/librenms/librenms/pull/5953 has been merge I did daily.sh then validate.php (no errors).

So I remove my device Smart Edge 600 and added again which doesn't help still no graph for CPU.

How can I verify it works?

**Comment by geordish** [comment]
Provide the output of
```
./discovery.php -h HOSTNAME -d -m sensors
```

**Comment by kyob** [comment]
https://gist.github.com/kyob/847a9aaf48dfa706570cae700d23c552

**Comment by laf** [comment]
`./discovery.php -h HOSTNAME -d -m processors` was meant

**Comment by kyob** [comment]
https://gist.github.com/kyob/7704ec639b65a90e7a4b4d06019e5b19

**Comment by laf** [comment]
This shows your device is not responding to the OID .1.3.6.1.4.1.2352.2.6.1.1 which is the oid you gave in your original request as being the CPU

**Comment by kyob** [comment]
But I get this from librenms server:
```
snmpwalk -On -v2c -c COMMUNITY HOST .1.3.6.1.4.1.2352.2.6.1.1
.1.3.6.1.4.1.2352.2.6.1.1.0 = INTEGER: 2
```

**Comment by geordish** [comment]
I've just created a PR to correct this. Want to try it?

**Comment by kyob** [comment]
Yes I did:
`./scripts/github-apply 5926`
and wait for results.

**Comment by kyob** [comment]
The result is: no graph for CPU with enabled sensors module.

**Comment by geordish** [comment]
Sorry, my mistake.

#5967

**Comment by kyob** [comment]
```
./scripts/github-apply 5967
Checking patch includes/discovery/processors/seos.inc.php...
Applied patch includes/discovery/processors/seos.inc.php cleanly.
```
...waiting for results.
