### ISSUE TITLE
list_devices should accept groups search

### ISSUE THREAD

**Issue by gilrim** [librenms/librenms#5928]
to easily display device info from a group, the api function needs to be ammended.

**Comment by gilrim** [comment]
issue resolved by adding the full parameter to the get_devices_by_group

**Comment by gilrim** [comment]
running the testfile now seems broken... l.php:
```
<?php

$init_modules = ['alerts'];
include '/opt/librenms/includes/init.php';

print_r(GetDevicesFromGroup(4,true,true));
```
results in output like:
```
Array
(
    [0] => Array
        (
            [device_id] => 4
        )

    [1] => Array
        (
            [device_id] => 15
        )
```

**Comment by gilrim** [comment]
also, while it was working, the ip column would get utf-encoded directly instead of converted to base10 ip-addresses, like this one:
`"ip": "\n\u0005k\u0005",`

**Comment by laf** [comment]
You mentioned this after the pull request and I said it just needs the ip address column to run through inet6_ntop().

**Comment by laf** [comment]
No further info provided.
