### ISSUE TITLE
Real-time graphing for other graph types && Widgets

### ISSUE THREAD

**Issue by XxPatrickxX** [librenms/librenms#593]
Currently we can use the real-time graph functionality for network interface graphs, it would be useful if this was extended to allow for real-time graphing of system graphs ie CPU/Processes/Memory/ect.

**Comment by paulgear** [comment]
This is a great idea.  I haven't looked in detail at how the data is captured, so it may take longer for certain data items than others.

**Comment by laf** [comment]
It's currently done via snmp.

**Comment by Rosiak** [comment]
I think vis.js might be able to do the job, I'll dig a bit more.

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #157](https://github.com/librenms/librenmsv2/issues/157) via [**ZenHub**](https://www.zenhub.com/)
