### ISSUE TITLE
Feature Request: URL Drop Down

### ISSUE THREAD

**Issue by NetCo-Jan** [librenms/librenms#5944]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

==========================================================
Component | Version
--------- | -------
LibreNMS  | 03d07f978b0762136de047edd40a34fca4586d44
DB Schema | 165
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

Hi Guys
would it be possible to request a feature where you have a drop down for URL;s like the example below:

![image](https://cloud.githubusercontent.com/assets/24909687/23094577/52128312-f604-11e6-9f08-22710b3f8fda.png)
 
this way you can reference Rancid, Multiple Weather Maps or really any URL that you want ? Will save customers from typing URL's wrong and everything is seen as one

thank you
Jan

**Comment by florianbeer** [comment]
So you mean like an additional dropdown menu (called what?) that would hold a list of custom links?
Maybe configured in `config.php` as a simple array (text => URL)?

Should be pretty simple to implement. I guess I could do it in a few minutes.

**Comment by laf** [comment]
Thanks for the request but features need to be posted on the community site: https://community.librenms.org/c/feature-requests

**Comment by NetCo-Jan** [comment]
@laf My Apologies - i will request there, @florianbeer 100% spot on - would be a tidy way to have multiple url's for example in my case - i have WebSVN/Rancid, Gestoip, multiple Weather Maps etc etc. so instead of bookmarks it would be nice to be on a drop down
