### ISSUE TITLE
Detect VM via mac vendor and disable sensors

### ISSUE THREAD

**Issue by mzac** [librenms/librenms#5955]
I had an idea for VM servers.  I have noticed that some of my Ubuntu Linux servers running as VMWare VMs are showing environmental sensors.  Of course these don't report back any valid data so it is basically wasted data and polling cycle.

My idea is that if we see if a system's mac vendor is for example VMWare, we could flag this system as a VM and then disable all environmental sensors?  Not sure this would work but I wanted to throw the idea out there.

Component | Version
--------- | -------
LibreNMS  | 53cf4ad9c8a4e175cc1b4a7f65d6cf0a22b99cff
DB Schema | 165
PHP       | 5.6.29-0+deb8u1
MySQL     | 5.5.54-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ X] Please provide as much detail as possible.
- [ X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
Can you please post requests and discussions over on https://community.librenms.org/c/feature-requests
