### ISSUE TITLE
Cisco wireless devices with hardware matching 'AIR-%' are marked as type network

### ISSUE THREAD

**Issue by towster** [librenms/librenms#5956]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

I have changed them by doing this but I have to redo this when new devices are added. It would be better if we could have them detected properly.

If needed I can add poller or discovery data. Please tell me if you want discovery/poll from one of the 'AIR-%' devices or one of the parent devices.

------
update devices set type="wireless" where hardware like "AIR-%";

insert into devices_attribs ( device_id,attrib_type,attrib_value) select device_id,"override_device_type" as attrib_type,"1" as attrib_value from devices where hardware like "AIR-%" and device_id not in (select distinct device_id from devices_attribs where attrib_type="override_device_type");
---------

**Comment by laf** [comment]
This really belongs on the community site as it's not a bug.

We don't set OS and therefore type in poller and possibly don't have hardware info available at os discovery time.

If this needs it's own OS then it's do-able but you've not said what the os is.
