### ISSUE TITLE
Device Polling - Issue

### ISSUE THREAD

**Issue by NetCo-Jan** [librenms/librenms#5964]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

librenms@librenms:~$ ./validate.php 
==========================================================
Component | Version
--------- | -------
LibreNMS  | ca2662fead1a54ba4f3879863bdb7ced7168016b
DB Schema | 165
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

[OK]    Database connection successful

Hi Guys
need some help, i have converted another customer to LibreNMS - i have a basic "Template" that i use for all of my deployments in terms of memory CPU etc.

At this site however the graphs have allot of missing info, the poller keeps complaining about not polling within 15 min, the list goes down to 2 devices unpolled and then jumps up to 150 odd

I have looked at the performance tunning etc but nothing seems to make a difference - the Web Interface seems fine - any help etc would be highly appreciated

![image](https://cloud.githubusercontent.com/assets/24909687/23164057/fd5f503e-f83d-11e6-84ca-68a09e5f86a4.png)

**Comment by laf** [comment]
Things like this are better in our irc channel otherwise we'll just be back and forth asking questions.

**Comment by NetCo-Jan** [comment]
Let me ask there thank you
