### ISSUE TITLE
Smart Edge 600 - temperature graphs are duplicated

### ISSUE THREAD

**Issue by kyob** [librenms/librenms#5965]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | ca2662fead1a54ba4f3879863bdb7ced7168016b
DB Schema | 165
PHP       | 7.0.15
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

https://github.com/librenms/librenms/issues/5181 **added support for temperature but graphs are duplicated.**

Screenshot from my libreNMS:
![se600-temperature](https://cloud.githubusercontent.com/assets/689112/23164111/d6f07ebc-f835-11e6-9762-faa9a38e49ec.png)

[./discovery.php -h 10.10.10.10 -d -m sensors](https://gist.github.com/kyob/847a9aaf48dfa706570cae700d23c552)

**Comment by laf** [comment]
You've provided none of the information from point 3 above. An snmpwalk is possibly not needed but the other two are.

**Comment by kyob** [comment]
My fault.

- [discovery](https://gist.github.com/kyob/0a05a1ae169ce4659f4259b996cc8471)
- [poller](https://gist.github.com/kyob/bbf6c78ffb80097266dcd3eca25947a7)

**Comment by geordish** [comment]
They are actually two different responses from your device.

The first set is a result of polling:
RBN-ENVMON-MIB::rbnCpuTempDescr

The second is from 
RBN-ENVMON-MIB::rbnEntityTempDescr

I would be loath to remove one of them, in case it breaks for different firmware versions... We could only discover the temperatures for the second if none have been found for the first though...

**Comment by kyob** [comment]
For me it's not a problem. I can have doubled temp graphs :)

**Comment by laf** [comment]
This is definitely something the vendor needs to fix as they are sending other temp info on the rbnCpuTempDescr oid.
