### ISSUE TITLE
Brocade FC interfaces greyed out, has no bandwidth

### ISSUE THREAD

**Issue by thejimmahknows** [librenms/librenms#5970]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
Version	53cf4ad - Mon Feb 20 2017 10:07:53 GMT-0500
DB Schema	#165
Web Server	Apache/2.4.10 (Debian)
PHP	5.6.30-0+deb8u1
MySQL	10.0.29-MariaDB-0+deb8u1
RRDtool	1.4.8
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
root@librenms01:/opt/librenms# ./validate.php 
==========================================================
Component | Version
--------- | -------
LibreNMS  | 53cf4ad9c8a4e175cc1b4a7f65d6cf0a22b99cff
DB Schema | 165
PHP       | 5.6.30-0+deb8u1
MySQL     | 10.0.29-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

[WARN]  Your install is out of date, last update: Mon, 20 Feb 2017 15:07:53 +0000
[OK]    Database connection successful

- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
[fabeven-poller.txt](https://github.com/librenms/librenms/files/791008/fabeven-poller.txt)
[fabeven-discovery.txt](https://github.com/librenms/librenms/files/791009/fabeven-discovery.txt)
[fabeven-snmpwalk.txt](https://github.com/librenms/librenms/files/791689/fabeven-snmpwalk.txt)

- [ x] Please provide as much detail as possible.
Can LibreNMS get the interface stats of a Fibre Channel interface?

![screenshot from 2017-02-21 09-02-15](https://cloud.githubusercontent.com/assets/15802946/23177544/207f8312-f835-11e6-8cdb-b1ffad27f127.png)

- [ x] Please do NOT post more than 10 lines of debug information here, use a 
pastebin service or GitHub Gists.
![screenshot from 2017-02-21 13-12-16](https://cloud.githubusercontent.com/assets/15802946/23178169/714e74fe-f837-11e6-957d-94ce20bae5e6.png)
Also reporting back as Brocade 1000, even though it is a 200E Silkworm
root@librenms01:~# snmpwalk -v1 -c sysmonr fabeven iso.3.6.1.2.1.47.1.1.1.1.2.1
iso.3.6.1.2.1.47.1.1.1.1.2.1 = STRING: "SilkWorm200E"

https://community.brocade.com/dtscp75322/attachments/dtscp75322/fibre/8685/1/53_1000602_02_MIB_v610.pdf

**Comment by laf** [comment]
You can use snmpwalk instead of snmpbulkwalk

**Comment by thejimmahknows** [comment]
Updated with snmpwalk.

**Comment by Rosiak** [comment]
Device reports the interface as down:
```
ifOperStatus.3 = down
ifAdminStatus.3 = down
```

And the device only returns 3 interfaces:
```
ifDescr.1 = lo
ifDescr.2 = eth0
ifDescr.3 = fc0
```

**Comment by laf** [comment]
They probably have there own mib for interfaces

**Comment by thejimmahknows** [comment]
Interesting how fc0 only shows up under ports...These are 16 port swtiches.
![image](https://cloud.githubusercontent.com/assets/15802946/23331725/90278d48-fb39-11e6-8fb3-cab1f57d98dc.png)

**Comment by laf** [comment]
The snmpwalk doesn't seem to contain any other port information than what's listed. If these devices do indeed provide other information over snmp then you'll need to provide the OIDs and mibs needed.

The fc port is also not providing back any traffic info hence you don't see it in LibreNMS.

I think you probably need to speak to Brocade about this first.

**Comment by thejimmahknows** [comment]
I've upgrade to FabricOS 6 and now the ports are showing up. I'll go back
through my notes and figure out which FabricOS version was the one that
started supporting SNMP on the interfaces.

**Comment by thejimmahknows** [comment]
I upgraded the Switch to FabricOS 6.2.2f, which requires incremental upgrades to get there. 5.0.1d -> 5.2.3 -> 5.3.2c -> 6.0.1a -> 6.1.2c -> 6.2.2f. Durning my upgrade I noticed LibreNMS was able to pick up all 16 ports now. I'll go back through my notes and figure out which version ( I believe it was 5.2.3) when LibreNMS was able to pull the interface info.
