### ISSUE TITLE
"Global Read" and "Normal User" permission level users are able to acknowledge alerts

### ISSUE THREAD

**Issue by basic612** [librenms/librenms#5973]
I would expect that non-privileged users should not be able to change the status of alerts.

Thanks for looking :)
-----------------

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

$ ./validate.php 
==========================================================
Component | Version
--------- | -------
LibreNMS  | edc13685356efdd3612efeb5a73ee20af9f5aeac
DB Schema | 165
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

[WARN]  Your install is out of date, last update: Tue, 21 Feb 2017 16:29:22 +0000
[OK]    Database connection successful
$ date
Wednesday 22 February  17:38:06 AEDT 2017

**Comment by FTBZ** [comment]
For me it's not a bug, but a feature...

**Comment by laf** [comment]
Normal users should have access but global read shouldn't as that should be just a read only account.

**Comment by FTBZ** [comment]
We're not using this like that :-/ All our IT crew has access with Global Read and we de not create specific access like needed by the Normal User. But I understand the problem.

**Comment by f0o** [comment]
We handle it similar to @FTBZ which is why global read and user-accounts with permissions to the device have the privilege of clearing alerts. We have a some customer gear which we don't manage but merely provide colocation and monitoring. Those customers have only access to their equipment and should be able to clear their alerts.

**Comment by laf** [comment]
Moved to #6807
