### ISSUE TITLE
CPU and Memory utilisation not graphed on Enterasys switches

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#5974]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

![snap10](https://cloud.githubusercontent.com/assets/16717388/23201491/77bc3262-f8e2-11e6-86e6-ef2e067e555d.png)
![snap9](https://cloud.githubusercontent.com/assets/16717388/23201920/6ebc9b6e-f8e4-11e6-8069-3f739ce562e6.png)

We have quite a number of Enterasys switches on our network and all of these device do not display or graph processor and memory information although it looks like they support that functionality according to this website; https://gtacknowledge.extremenetworks.com/articles/Q_A/HOW-TO-MONITOR-CPU-ON-SECURESTACKS-VIA-MIBS, https://community.extremenetworks.com/extreme/topics/viewing_system_utilization_on_the_securestacks and here; http://forums.cacti.net/viewtopic.php?f=12&t=42279 

I have uploaded discovery, poller and snmpbulkwalk outputs for your reference
[entera_discover.txt](https://github.com/librenms/librenms/files/792618/entera_discover.txt)
[entera_discover_mempool.txt](https://github.com/librenms/librenms/files/792619/entera_discover_mempool.txt)
[entera_discover_processors.txt](https://github.com/librenms/librenms/files/792620/entera_discover_processors.txt)
[entera_poller.txt](https://github.com/librenms/librenms/files/792621/entera_poller.txt)
[entera_poller_mempool.txt](https://github.com/librenms/librenms/files/792622/entera_poller_mempool.txt)
[entera_poller_processors.txt](https://github.com/librenms/librenms/files/792623/entera_poller_processors.txt)
[entera_snmpbulk.txt](https://github.com/librenms/librenms/files/792624/entera_snmpbulk.txt)
I also noticed that the last two digits of the OID mentioned in the includes/definitions/enterasys.yaml file are swapped around when comparing this OID to one listed in websites stated above; see below,
![snap11](https://cloud.githubusercontent.com/assets/16717388/23202982/37f84aa6-f8e9-11e6-9f35-2e3d9bcc1744.png)
I am not an expert on the internals of LibreNMS but I noticed from doing a quick glance of the discovery and poller outputs that it looks like the LibreNMS references the NETSWITCH-MIB and HOST-RESOURCES-MIB files when it looks like it ought to use the `enterasys-resource-utilization-mib`. I downloaded the Enterasys mibs here; http://www.extremenetworks.com/support/policies/mibs/ should you require them. Thanks.

**Comment by geordish** [comment]
Your obfuscation of your SNMPwalk makes things a bit tricky :(

Created a patch at #5976. Mind testing?

**Comment by breeman1** [comment]
HI @geordish 

I applied your patch however I am getting PHP errors when running a discovery command; see attachments below,
![snap9](https://cloud.githubusercontent.com/assets/16717388/23221814/b7221e48-f92e-11e6-88e1-bb1690bddc92.png)

[entera_snmpbulk_test.txt](https://github.com/librenms/librenms/files/794163/entera_snmpbulk_test.txt)
[entera_poller_test.txt](https://github.com/librenms/librenms/files/794164/entera_poller_test.txt)
[entera_discovery_test.txt](https://github.com/librenms/librenms/files/794165/entera_discovery_test.txt)

I tried not to obfuscate the snmpwalk too much this time :).

**Comment by geordish** [comment]
Oops, used a deprecated function.

Try again.

**Comment by breeman1** [comment]
It works @geordish, see below.
![image](https://cloud.githubusercontent.com/assets/16717388/23250787/3a7d64ee-f9b3-11e6-9c12-501c4a952ae7.png)
I see you chosen to use `etsysResourceCpuLoad5sec` for graphing Processors usage; I am not sure if it really adds any tangible value when troubleshooting as it changes quite rapidly. I think we can go for `etsysResourceProcessLoad5min=1.3.6.1.4.1.5624.1.2.49.1.2.1.1.5` which looks more useful to me, provided it is not too much work to somehow graph all three time periods
![image](https://cloud.githubusercontent.com/assets/16717388/23250892/a35e0270-f9b3-11e6-8ce0-84909585a306.png)
The `show system utilization storage` command output two memory pool data, one for RAM/Memory and the other for Flash. 
![image](https://cloud.githubusercontent.com/assets/16717388/23250401/af5280ee-f9b1-11e6-9e44-49dcc3ed97aa.png)
I would really appreciate it if you can also add the graphing of the Flash usage under Memory Pools. 
Just for consistency, it would be great if you could add the CPU and Memory mini graphs in the top bar in the Device Overview screen so it looks similar to the Cisco router output as shown by arrows below;
![image](https://cloud.githubusercontent.com/assets/16717388/23250695/f15f4f2a-f9b2-11e6-9df7-7d7c7ec9c984.png)
Thank you for help in getting the CPU & Memory graphing sorted out on the Enterasys switches.

**Comment by geordish** [comment]
I've updated it with changes asked for.

**Comment by breeman1** [comment]
Thank you so much @geordish :), I will test it just now.
Shouldn't this line; `$oid = '.1.3.6.1.4.1.5624.1.2.49.1.1.1.1.2';` change to `$oid = '.1.3.6.1.4.1.5624.1.2.49.1.1.1.1.4` in the `includes/discovery/processors/enterasys.inc.php` file to reflect the fact that we are now using `etsysResourceCpuLoad5min` instead of `etsysResourceCpuLoad5sec`?

**Comment by geordish** [comment]
That line just needs removing. It is old. Its gone now.

**Comment by breeman1** [comment]
All is good now except that the Internal Flash Storage graph is not being populated. It looks like the values are being read by the discovery function but the poller module reads them as zero. I have included the debug files for your reference.
[entera_poller_test_storage.txt](https://github.com/librenms/librenms/files/797024/entera_poller_test_storage.txt)
[entera_discovery_test_storage.txt](https://github.com/librenms/librenms/files/797025/entera_discovery_test_storage.txt)

![image](https://cloud.githubusercontent.com/assets/16717388/23267686/260e5900-f9f4-11e6-8d70-70c7fe62a71b.png)
![image](https://cloud.githubusercontent.com/assets/16717388/23267690/2a6a3744-f9f4-11e6-8915-9cd9a05d78a8.png)

**Comment by geordish** [comment]
Can you make sure your on my latest patch. I did have some issues with that.

**Comment by breeman1** [comment]
Ah, it works now :). Thanks again @geordish 
![image](https://cloud.githubusercontent.com/assets/16717388/23268944/bb151f9a-f9f7-11e6-8c50-39d306918d00.png)
