### ISSUE TITLE
Distributed poller still need NFS share even if use rrdtool/cache >= 1.5

### ISSUE THREAD

**Issue by xbeaudouin** [librenms/librenms#5975]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 8d528124a948e3166f6b04905383646ee5c08dad
DB Schema | 165
PHP       | 5.6.30-0+deb8u1
MySQL     | 10.0.29-MariaDB-0+deb8u1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.2.1

Currently have a setup with 4 (virtual) machines : 
- storage machine with : rrdcached, memcached, mariadb : 
rrdcached                      1.6.0-1+b1
rrdtool                        1.6.0-1+b1
memcached                      1.4.21-1.1+deb8u1
- 2 poller with same version of rrdtool
- 1 web front with same version rrdtool.

All setup has been done using the http://docs.librenms.org/Extensions/Distributed-Poller/ and http://docs.librenms.org/Extensions/RRDCached/

But the sharing over NFS of rrd files is still needed or the update of data will stop after random amount of times. Then the rrd files stops to be updated.

Is there any good way to get rid of NFS ? (especially on remote poller, like for example on a customer poller machine).

**Comment by laf** [comment]
Please post in https://community.librenms.org/c/help

This isn't strictly an issue for us if you are saying that this works for a period and then stops when you don't have an nfs share setup.

**Comment by laf** [comment]
In fact, have you specified the rrdtool version you are using in config as you've given very little information on your setup other than version numbers of rrdtool being used.
