### ISSUE TITLE
Issues with the Generex UPS card and RFC1628 support

### ISSUE THREAD

**Issue by FTBZ** [librenms/librenms#5977]
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

------------------

Component | Version
--------- | -------
LibreNMS  | a8691680abb479ba7398d520fff01c1cffe228a0
DB Schema | 166
PHP       | 7.0.11
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

------------------

Discovery: http://pastebin.com/t0FNfSDS
Poller: http://pastebin.com/KQHUJHVi
Bulk: http://pastebin.com/sWPM4yBC

------------------

The Generex SNMP Card is a generic UPS card using the RFC1628 implementation in LibreNMS. Globally, it's working, but some glitches make LibreNMS not the best choice to monitor this kind of equipment.

1 - The state sensors are not working and need to be moved to the new format with more relevant sensors (like upsBatteryStatus and upsOutputSource):
<img width="737" alt="screen shot 2017-02-22 at 15 59 49" src="https://cloud.githubusercontent.com/assets/1927109/23216994/1f9c2f8e-f918-11e6-88ec-28534e59835f.png">
The graphs "Seconds on Battery" and "Battery: Estimated minutes remaining" should be moved to the charge section to not lost the data.

2 - At the top right, the "Battery Voltage" isn't working. When clicking on, a permission error is returned:

<img width="1111" alt="screen shot 2017-02-22 at 16 04 37" src="https://cloud.githubusercontent.com/assets/1927109/23217208/c478bdba-f918-11e6-8536-f40cf83c3f49.png">

<img width="638" alt="screen shot 2017-02-22 at 16 08 10" src="https://cloud.githubusercontent.com/assets/1927109/23217321/2015654c-f919-11e6-8a83-d2bd23f00aa4.png">

3 - The load values are not using a correct divisor:
<img width="528" alt="screen shot 2017-02-22 at 16 10 41" src="https://cloud.githubusercontent.com/assets/1927109/23217428/7884478e-f919-11e6-9aee-b51017057315.png">

`sh-4.2# /usr/bin/snmpget -v2c -c COMMUNITY -OsqnU -m UPS-MIB -M /opt/librenms/mibs 10.10.10.10 1.3.6.1.2.1.33.1.4.4.1.5.1
.1.3.6.1.2.1.33.1.4.4.1.5.1 5`

`sh-4.2# /usr/bin/snmpget -v2c -c COMMUNITY -OsqnU -m UPS-MIB -M /opt/librenms/mibs 10.10.10.10 1.3.6.1.2.1.33.1.4.4.1.5.2
.1.3.6.1.2.1.33.1.4.4.1.5.2 4`

`sh-4.2# /usr/bin/snmpget -v2c -c COMMUNITY -OsqnU -m UPS-MIB -M /opt/librenms/mibs 10.10.10.10 1.3.6.1.2.1.33.1.4.4.1.5.3
.1.3.6.1.2.1.33.1.4.4.1.5.3 1`

4 - The voltage values are not using a correct divisor (Input & Output):
<img width="510" alt="screen shot 2017-02-22 at 16 16 13" src="https://cloud.githubusercontent.com/assets/1927109/23217646/4aad6790-f91a-11e6-9690-481c451099c8.png">

`/usr/bin/snmpget -v2c -c UPS -OsqnU -m UPS-MIB -M /opt/librenms/mibs 10.1.22.23 .1.3.6.1.2.1.33.1.3.3.1.3.1 .1.3.6.1.2.1.33.1.3.3.1.3.1 237`

` /usr/bin/snmpget -v2c -c UPS -OsqnU -m UPS-MIB -M /opt/librenms/mibs 10.1.22.23 .1.3.6.1.2.1.33.1.3.3.1.3.2 .1.3.6.1.2.1.33.1.3.3.1.3.2 234`

`/usr/bin/snmpget -v2c -c UPS -OsqnU -m UPS-MIB -M /opt/librenms/mibs 10.1.22.23 .1.3.6.1.2.1.33.1.3.3.1.3.3 .1.3.6.1.2.1.33.1.3.3.1.3.3 235`

On my side I can probably solve the state issue and moving the graphs on a new page, but I don't know how to handle the divisor changes without broken anything and I didn't take a look to the permission issue.

**Comment by FTBZ** [comment]
About the divisors problem, the code use these lines to get the information:

`$divisor = get_device_divisor($device, $pre_cache['poweralert_serial'], 'current');
`

But the file poweralert.inc.php uses an OID that's not a part of the RFC1628 and isn't available on the Generex card.

**Comment by laf** [comment]
That's how the rfc files have been (the variable has changed name in a tidyup but it was still always a poweralert pre-cache variable.

**Comment by FTBZ** [comment]
I am increasingly convinced that it would be simpler to support each of the UPS models individually. Keeping the card as RFC1628, but adding specific support for each UPS manufacturer will be easier to manage the change management of the code without breaking anything for others.

**Comment by laf** [comment]
We have a lot of support for different ups vendors already but only in the last two months was generex introduced to catch all of them that are generex but rebranded.

**Comment by FTBZ** [comment]
Three possibilities (?):

1. Change the code for the RFC to be able to change the divisor for specific models (and probably not only the divisor)
2. Create a specific support for Generex without using the RFC including a way to handle different divisors for different manufacturers
3. Create specific support for each UPS manufacturer "ignoring" the generic card and the RFC

For my own use (big UPS from ABB) and after all these tests including this lost time. I prefer the third possibility.

**Comment by laf** [comment]
@FTBZ  Have these all been resolved once that last PR is merged in?

**Comment by FTBZ** [comment]
@laf yes, soon. I can close now.
