### ISSUE TITLE
update failure when html/.htaccess modified

### ISSUE THREAD

**Issue by ciscoqid** [librenms/librenms#5986]
I received this notice (below).  It is true, but the change was necessary to have fix RewriteBase so the site can be referenced as /librenms within a larger site.  If this file needs to be changed locally and that can block updates, perhaps we need another option to handle that (which is documented)?  I added the path to .gitignore, but if updates are needed that will still cause issues.

Thanks,
Mark

We just attempted to update your install but failed. The information below
should help you fix this.

error: Your local changes to 'html/.htaccess' would be overwritten by merge.
 Aborting.
Please, commit your changes or stash them before you can merge.

**Comment by ciscoqid** [comment]
It actually looks like I am OK if I commit the change as suggested, that just seemed odd at first.  Might still cause other folks grief if they don't get that email.

**Comment by laf** [comment]
This is better discussed on the community site. Editing the htaccess is a requirement for sub directory support and the only way is to commit your local file. 

Changes to htaccess are few and far between, aside from the change yesterday the last one before that was over 18 months ago. If someone has a better suggestion on how to deal with it we're all ears.
