### ISSUE TITLE
How did you setup your gns3 testing ?

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#599]
I can only setup a simple gns3 testing.
 How did you setup gns3 testing ? 
Give me a topology map screenshot please .

**Comment by paulgear** [comment]
Hi @wzhsunn, the issue database really isn't the best place for this.  The issue database is basically for bug reports or enhancement requests.  General help questions are best handled on IRC or the mailing list.  In this case, the GNS3 community forum at https://community.gns3.com/community/forum might be a better choice.

**Comment by wzhsunn** [comment]
OK， thank you .
