### ISSUE TITLE
Auto discovery adding IPMI cards

### ISSUE THREAD

**Issue by cahluor** [librenms/librenms#5992]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Validate : 
==========================================================
Component | Version
--------- | -------
LibreNMS  | 097a8277590b862b715ce86a9600da21eb35ba8f
DB Schema | 167
PHP       | 5.6.30-0+deb8u1
MySQL     | 10.0.29-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

I'am not sure if it's bug, But maybe a tweak for the autodiscovery process.

I have dell servers, with their own IP adresses and FQDN correctly resolved, and they have an idrac card with SNMP enabled.
The idrac card is configured in the IPMI part of the settings for the hosts.

When I use autodiscovery, the idrac card is also added as a separate host, which I think is not usefull because the idrac card is pooled as IPMI.

maybee a check in the autodicovery process, not to add a device if it's name or IP is allready used as IPMI in a host ?

**Comment by laf** [comment]
I'm not sure personally that's the right approach. Seems too much of an edge case to be worth adding that restriction in, especially as we'd need to make it configurable.

How is this being autodiscovered, is it via the discovery-arp process as discovery-protocols needs xDP or OSPF running so I don't expect that works here.

**Comment by laf** [comment]
No further info provided.

**Comment by cahluor** [comment]
oops did not see the reply 12 days ago.
Yes it's discovered via discovery-arp.
as a workaround I disabled snmp on the idrac as it's not used.
