### ISSUE TITLE
LibreNMS does not show all IP addresses

### ISSUE THREAD

**Issue by patrick7** [librenms/librenms#6006]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

validate.php

> Component | Version
> --------- | -------
> LibreNMS  | c5531f70670383530f7f218f6cbb4bd335dbc44a
> DB Schema | 169
> PHP       | 5.6.30-0+deb8u1
> MySQL     | 5.5.54-0+deb8u1
> RRDTool   | 1.4.8
> SNMP      | NET-SNMP 5.7.2.1

Since some time I have the problem that LibreNMS does not show the IP address of all interfaces. Some (both physical and virtual) are OK, but others aren't. I have no idea what the cause could be, as with SNMP walk I see the addresses.

![selection_007](https://cloud.githubusercontent.com/assets/24757877/23334744/bf38478c-fba5-11e6-9687-c2980df4a88c.png)

**Comment by laf** [comment]
You've not provided any of the info asked for In point 3

**Comment by patrick7** [comment]
I think it's not related with my SNMP daemon (all standard debian machines). But I'll get the data.

**Comment by patrick7** [comment]
It seems there's also a problem with ifIndex. I recently added a NIC to a server so ifIndexes have changed. In the database, the interface is still associated with the old ifIndex:

```
mysql> select port_id,ifName,ifIndex from ports where device_id="1";
+---------+------------+---------+
| port_id | ifName     | ifIndex |
+---------+------------+---------+
|     161 | lo         |       1 |
|     162 | eth0       |       2 |
|     163 | eth1       |       3 |
|     164 | eth2       |       4 |
|     165 | eth3       |       5 |
|     166 | eth4       |       6 |
|     167 | eth5       |       7 |
|     168 | eth6       |       8 |
|     169 | eth7       |       9 |
|     170 | dummy0     |      10 |
|     171 | gre0       |      11 |
|     172 | gretap0    |      12 |
|     173 | sit0       |      15 |
|     174 | cust-sit1  |      16 |
|     175 | ovs-system |      18 |
|     176 | ovsbr0     |      19 |
|     177 | bond0      |      20 |
|     178 | public     |      22 |
|     180 | monitoring |      24 |
|     182 | ripeatlas  |      26 |
|     184 | vpn-gre1   |      28 |
|     185 | mgmt       |      30 |
|     186 | vpn-gre2   |      31 |
|     205 | private    |      34 |
|     187 | tun0       |      36 |
|     190 | tun1       |      39 |
+---------+------------+---------+
26 rows in set (0.00 sec)
```
Before, ifIndex = 11 was "gre0". Now, ifIndex = 11 is the new NIC.
Now, LibreNMS is not able to insert the new WIFI NIC as there's already an interface with ifIndex 11:
```
mysql> INSERT INTO `ports` (`device_id`,`ifIndex`,`ifName`)  VALUES ('1','11','wlan0');
ERROR 1062 (23000): Duplicate entry '1-11' for key 'device_ifIndex'
```

**Comment by patrick7** [comment]
I did some more troubleshooting. It's 100% related to the issue named above. IPs and interfaces are totally mixed if any change is made to ifIndex after the first run of LibreNMS.

Is there a way to detect such changes? Removing / Re-adding of the device or MySQL hacks shouldn't be the solution.

**Comment by patrick7** [comment]
Looks like to be related with https://github.com/librenms/librenms/issues/3510

**Comment by laf** [comment]
Closing in preference to #3510
