### ISSUE TITLE
Overlapping graphs on overview tab when using svg graph type

### ISSUE THREAD

**Issue by sorano** [librenms/librenms#6019]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 3f5bf56b557668659e32909204da3a42c6adac09
DB Schema | 170
PHP       | 7.0.15-0ubuntu0.16.04.2
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

( Desktop resolution: 2560x1440 )
Decided to try out the new svg graphs, and since reading the "No doubt some small issues will arise, please let us know if that is the case." I figured I'd report this.

The graphs on overview tab are wider than normal causing them to overlap. (after ctrl+f5)
 
Edit: After testing some more it seems to be specific to IE. In Chrome & normal Firefox the graphs looks normal.

![Overlapping graphs](http://forumbilder.com/images/2017/02/27/overlapping.png)

**Comment by geordish** [comment]
This doesn't look simple to fix...
https://css-tricks.com/scale-svg/
https://gist.github.com/larrybotha/7881691

This seems to work for graphs. The device logo is broken still though. This also doesn't target firefox.
```diff
diff --git a/html/css/dark.css b/html/css/dark.css
index f637463..4fa251c 100644
--- a/html/css/dark.css
+++ b/html/css/dark.css
@@ -1,3 +1,11 @@
+.ie9 img {
+    width: 100%;
+}
+@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
+    img {
+        width: 100%;
+    }
+}
 .fa-nav-icons {
     color: #e30613;
 }
diff --git a/html/css/light.css b/html/css/light.css
index df263b9..4e80032 100644
--- a/html/css/light.css
+++ b/html/css/light.css
@@ -1,3 +1,11 @@
+.ie9 img {
+    width: 100%;
+}
+@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
+    img {
+        width: 100%;
+    }
+}
 .fa-nav-icons {
     color: #383637;
 }
```

**Comment by geordish** [comment]
I can't replicate your issues in Firefox.. only IE.

**Comment by sorano** [comment]
Sorry Dave. My bad, totally forgot that I'm using Firefox Extended Support Release (ESR) here (school environment). I can confirm that when using normal up to date Firefox relase it works fine.

**Comment by laf** [comment]
Have you tested this patch on IE @sorano

**Comment by sorano** [comment]
Tested now in Firefox Extended Support Release and IE. The graphs looks as they should.
