### ISSUE TITLE
QNAP NAS - error drawing graph for storage & cpu

### ISSUE THREAD

**Issue by MBGucky** [librenms/librenms#6020]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

librenms@VM-LibreNMS:~$ ./validate.php 
==========================================================
Component | Version
--------- | -------
LibreNMS  | 698584e14d8c82631662802c17201766f9ae28cc
DB Schema | 170
PHP       | 7.0.15-0ubuntu0.16.04.2
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

[OK]    Database connection successful
librenms@VM-LibreNMS:~$ 

- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
==> http://pastebin.com/Nic1m8f9

- [ x] Please provide as much detail as possible.
QNAP TS-410 & TS-419 Plus, Firmware 4.2.3
On TS-410 graph for storage & cpu not displayed (error drawing graph)
On TS-419 Plus graph for CPU is missing

RRD-commands don't show errors.

Librenms is the appliance from homepage, os ist up-to-date. librenms as well (daily.sh)
Updates from Github have been checked out.

- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by geordish** [comment]
I think there might be a bug on the firmware version you are running. 

From your output:
```
.1.3.6.1.4.1.8072.1.2.1.1.4.0.10.1.3.6.1.4.1.24681.1.2.10.127 = STRING: "HdNumber"
.1.3.6.1.4.1.8072.1.2.1.1.4.0.10.1.3.6.1.4.1.24681.1.2.11.127 = STRING: "SystemHdTable"
.1.3.6.1.4.1.8072.1.2.1.1.4.0.10.1.3.6.1.4.1.24681.1.2.12.127 = STRING: "ModelName"
.1.3.6.1.4.1.8072.1.2.1.1.4.0.10.1.3.6.1.4.1.24681.1.2.13.127 = STRING: "HostName"
.1.3.6.1.4.1.8072.1.2.1.1.4.0.10.1.3.6.1.4.1.24681.1.2.14.127 = STRING: "SysFanNumber"
.1.3.6.1.4.1.8072.1.2.1.1.4.0.10.1.3.6.1.4.1.24681.1.2.15.127 = STRING: "SystemFanTable"
.1.3.6.1.4.1.8072.1.2.1.1.4.0.10.1.3.6.1.4.1.24681.1.2.16.127 = STRING: "SysVolumeNumber"
.1.3.6.1.4.1.8072.1.2.1.1.4.0.10.1.3.6.1.4.1.24681.1.2.17.127 = STRING: "SystemVolumeTable"
```

This doesn't look normal.  It appears to be 2 OIDs stuck together. For example
.1.3.6.1.4.1.8072.1.2.1.1.4.0.10.1.3.6.1.4.1.24681.1.2.10.127 = STRING: "HdNumber"

This is:
.1.3.6.1.4.1.8072.1.2.1.1.4.0.10
and 
.1.3.6.1.4.1.24681.1.2.10.127

The second OID makes sense, as from the MIB:
HdNumber	1.3.6.1.4.1.24681.1.2.10

I suggest checking to see if the vendor is aware of this bug.

**Comment by MBGucky** [comment]
As far as I know all Qnap NAS run the same operating system, regardless of the model. I have upgraded 2 different models to the same and most recent version of the OS and both show now the same error, the CPU is not displayed. I assume, other Qnap customers must have exactly the same issue and I hope that one of them is more qualified than I to address the issue with Qnap.

**Comment by laf** [comment]
https://forum.qnap.com/viewtopic.php?t=108850
That old thread on qnap forum does indicate this was ok at one stage so I'm guessing a firmware update has screwed up snmp for them. Please contact qnap to see what they say.

**Comment by laf** [comment]
No further info provided and does look like a vendor bug
