### ISSUE TITLE
Traffic graphing not working on a Juniper EX4200 stack

### ISSUE THREAD

**Issue by blodan** [librenms/librenms#6034]
Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? 
    Yes, using master from github
- [X] Please include all of the information from validate.php

>Component | Version
>--------- | -------
>LibreNMS  | bbc7d71cf9650da779b89dfd03c7310f2adbc6b7
>DB Schema | 170
>PHP       | 5.6.20
>MySQL     | 5.6.30-log
>RRDTool   | 1.5.5
>SNMP      | NET-SNMP 5.7.3

- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
[librenms-discover-output.txt](https://github.com/librenms/librenms/files/806635/librenms-discover-output.txt)
[librenms-poller-output.txt](https://github.com/librenms/librenms/files/806634/librenms-poller-output.txt)
[librenms-snmpbulkwwalk-output.txt](https://github.com/librenms/librenms/files/806491/librenms-snmpbulkwwalk-output.txt)

- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Issue:
I have a stack consisting of two Juniper EX4200, librenms can find all ports etc, however all traffic graphs are borked and shows 400bytes/s outgoing (eventhough the 10gbit uplink to our cisco switches pushes 1gbps+ at times, thats port ae0.0)

Librenms can however graph the cisco nexus port properly so I can see how much traffic is going through the Juniper uplink, however, the juniper port (ae0.0) does not graph that properly.

**Comment by blodan** [comment]
Adding screenshot of one graph if helps out in anyway
![librenms-graphs](https://cloud.githubusercontent.com/assets/3081981/23402836/9b13331c-fdad-11e6-943b-322995ad988c.jpg)

**Comment by geordish** [comment]
Your poller and discovery logs have not ran correct. You've not entered a valid hostname. It should probably be something like juniper-stack-01-... instead of the IP address.

**Comment by blodan** [comment]
Sorry for not noticing that, uploaded new ones with alot more output.

**Comment by geordish** [comment]
From your output related to the port in the screenshot (I've cut out some junk)

```
[757] => Array
        (
            [ifName] => ae0.0
            [ifHCInOctets] => 430470
            [ifHCOutOctets] => 82015493
```

Those values are not very high at all for a port which is running at >1G. The Out Octets value is only around 80Meg transferred.

Its hard to gauge what is going on as those counters go up, and up, but I would have expected them to be much, much higher.

Are you sure you are looking at the right port? If you are, then I think the issue might be with your device.

**Comment by blodan** [comment]
Yes, it's the right port, and I know the traffic is going through as I can see the traffic on the other side of the uplink on the cisco graph.

I'll look into snmp in junos then if there might be a issue there, thanks! :)

**Comment by blodan** [comment]
Just found why, i guess this just became a feature request, heres from the Juniper FAQ;

>Problem: Logical Interface Statistics Do Not Reflect All Traffic
>
>Description: The traffic statistics for a logical interface do not include all of the traffic.
>
>Solution
>Traffic statistics fields for logical interfaces in show interfaces commands show only control traffic; the >traffic statistics do not include data traffic. You can view the statistics for all traffic only per physical >interface.

So when i create a graph with the multiport_bits_separate type of the included interfaces in ae0;
xe-0/1/0
xe-0/1/1
xe-1/1/0
xe-1/1/1

I'm getting a properly rendered graph. I'm closing the issue.
