### ISSUE TITLE
New install not Draw IP Graph

### ISSUE THREAD

**Issue by maxdie** [librenms/librenms#6038]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable 
monthly release.
Yes update from 02/28/2017
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
==========================================================
Component | Version
--------- | -------
LibreNMS  | db58fea2d2a8b02cc1b3ee55ed088bec9e9682c6
DB Schema | 171
PHP       | 7.0.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful

- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
[poller.txt](https://github.com/librenms/librenms/files/806747/poller.txt)
[snmpbulkwalk.txt](https://github.com/librenms/librenms/files/806749/snmpbulkwalk.txt)
[discovery.txt](https://github.com/librenms/librenms/files/806748/discovery.txt)
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Issue.
Hello.
1. In new installation on CentOS 7 Graphs\Netstat  IP Statistics & IP Fragmentation Statistics not Drawing on device.

![image](https://cloud.githubusercontent.com/assets/26085639/23405189/2b4918e0-fdca-11e6-8d83-42c15838b2da.png)
2. When I install from vmdk downloaded from site this Graph is OK, But when upgrade with daily.sh and re-create device this grap not showing.

Please help recognize this trouble.

Thank You.

**Comment by laf** [comment]
Your validate install isn't the full output/

**Comment by maxdie** [comment]
Hello, again.
new update and validate.

[root@xe2455 librenms]# ./daily.sh
Re-running /opt/librenms/daily.sh as librenms user
Updating to latest codebase                        OK
Updated from db58fea2d2a8b02cc1b3ee55ed088bec9e9682c6 to 179f852c21d3455de70953f8ae8af08a1546a9c6 OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
[root@xe2455 librenms]# ./validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | 179f852c21d3455de70953f8ae8af08a1546a9c6
DB Schema | 171
PHP       | 7.0.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful
[root@xe2455 librenms]#
What the key need for full validation ?

**Comment by maxdie** [comment]
On test -m dist-pollers and  -m rrdcheck all OK.

**Comment by maxdie** [comment]
Update rrdtool to 1.6.0 no change.

**Comment by laf** [comment]
I have these in my install fine for CentOS7 so I expect this is because you are using a restricted snmpd.conf file, please use the one provide within our installation.

**Comment by maxdie** [comment]
[daily.txt](https://github.com/librenms/librenms/files/817673/daily.txt)
[disco.txt](https://github.com/librenms/librenms/files/817669/disco.txt)
[poller.txt](https://github.com/librenms/librenms/files/817671/poller.txt)
[snmp.txt](https://github.com/librenms/librenms/files/817670/snmp.txt)
[validate.txt](https://github.com/librenms/librenms/files/817672/validate.txt)

My new installation from friend. Many device  not graph IP statistic and  IP Fragmentation Statistics only.

Three instalation and three trouble. I dont know what i doing not right.

**Comment by laf** [comment]
For whatever reason the rrd file is attempted to be created in that output so I expect that's being done everytime.

Please run `rrdtool create /opt/librenms/rrd/syn-hyper-02.synercon.local/netstats-ip.rrd --step 300 DS::COUNTER:600:U:100000000000 DS::COUNTER:600:U:100000000000 DS::COUNTER:600:U:100000000000 DS::COUNTER:600:U:100000000000 DS::COUNTER:600:U:100000000000 DS::COUNTER:600:U:100000000000 DS::COUNTER:600:U:100000000000 DS::COUNTER:600:U:100000000000 DS::COUNTER:600:U:100000000000 DS::COUNTER:600:U:100000000000 DS::COUNTER:600:U:100000000000 DS::COUNTER:600:U:100000000000 DS::COUNTER:600:U:100000000000 DS::COUNTER:600:U:100000000000 DS::COUNTER:600:U:100000000000 DS::COUNTER:600:U:100000000000  RRA:AVERAGE:0.5:1:2016 RRA:AVERAGE:0.5:6:1440 RRA:AVERAGE:0.5:24:1440 RRA:AVERAGE:0.5:288:1440  RRA:MIN:0.5:1:720 RRA:MIN:0.5:6:1440     RRA:MIN:0.5:24:775     RRA:MIN:0.5:288:797  RRA:MAX:0.5:1:720 RRA:MAX:0.5:6:1440     RRA:MAX:0.5:24:775     RRA:MAX:0.5:288:797  RRA:LAST:0.5:1:1440`

**Comment by maxdie** [comment]
ERROR: invalid DS format

**Comment by geordish** [comment]
Please try patch at #6088

**Comment by maxdie** [comment]
Thank you very much. Issue is resolved. All Graphs works.

![image](https://cloud.githubusercontent.com/assets/26085639/23587879/e03edaf6-01c5-11e7-9d4b-391e290bf665.png)
