### ISSUE TITLE
Realtime Graph in my fortigate firewall showing higher bandwidth rate from our limited band width

### ISSUE THREAD

**Issue by praburaj1985** [librenms/librenms#6039]
Hi,
 Realtime graph is showing in my librenms showing higher bandwidth rate from our limited band width

In our premises we are having only 16MBps but the realtime graph shows above 26Mbps but in our firewall
shows correctly please help me out this issue.

Regards
M.Prabhuraj

**Comment by laf** [comment]
No debug info provided

**Comment by praburaj1985** [comment]
Hi,
 Please see the below image how to rectified this issue showing the high bandwidth which we are using 16Mbps but its shows more than that how its possible.
![image](https://cloud.githubusercontent.com/assets/22237394/23448511/7b3d2258-fe77-11e6-8a31-005ca03e07e0.png)
