### ISSUE TITLE
WebUI Bug - scaling problems?

### ISSUE THREAD

**Issue by E-t-z** [librenms/librenms#6045]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version                                                                                                                                  
--------- | -------                                                                                                                                  
LibreNMS  |  1.25                                                                                                                                        
DB Schema | 157                                                                                                                                      
PHP       | 7.0.16-3+deb.sury.org~xenial+1                                                                                                           
MySQL     | 5.5.53-MariaDB                                                                                                                           
RRDTool   | 1.5.5                                                                                                                                    
SNMP      | NET-SNMP 5.7.3                                                                                                                           

A screenshot describes it best:

https://s30.postimg.org/6ypiv2btt/Capture.png

Browser is Google Chrome 56.0.2924.87 (64-bit)

**Comment by laf** [comment]
Your install is out of date. Please update.

**Comment by E-t-z** [comment]
Out of date?

It is latest monthly release?

**Comment by laf** [comment]
Try a force refresh then because this was fixed before the monthly release.
