### ISSUE TITLE
Dell vendor shown as Generic

### ISSUE THREAD

**Issue by bputs** [librenms/librenms#6047]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Dell switches are shown as generic device. 
Dell Switch models:  
**Dell Networking X1052 1-10Gb Switch**
Discovery:   https://gist.github.com/87eb9a5912a3f19e6dd7bcc250eca52d.git
Poller:          https://gist.github.com/3f790154e35895d2254b09a869403f14.git
**R1-2210 VRTX 10Gb Switch**
https://gist.github.com/36e42c585566a4bdca3fc03eeb634c97.git

./Validate.php:

LibreNMS  | 6ecb3acc5144aea80821a11bbb5ca715e2e9bdac
DB Schema | 172
PHP       | 7.0.15-0ubuntu0.16.04.2
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

**Comment by laf** [comment]
You've not provided any of the info asked for in point 3.

**Comment by bputs** [comment]
Sorry for tha, was redirected to the 

Dell Networking X1052 1-10Gb Switch
https://gist.github.com/87eb9a5912a3f19e6dd7bcc250eca52d.git
R1-2210 VRTX 10Gb Switch
https://gist.github.com/36e42c585566a4bdca3fc03eeb634c97.git
