### ISSUE TITLE
How to find all Entities on the creating alert page ?

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#605]
May be it is very  useful to find all the Entities on the creating alert page or [give more information](https://groups.google.com/forum/#!topic/librenms-project/6SfZcaPG9s0)  about the entity.  I am not familiar with some protocols and terms .

**Comment by laf** [comment]
Hopefully this has now been addressed in part within the docs at http://docs.librenms.org/Extensions/Alerting/#entities

Can you see if this is helpful and if so, close this issue :)

**Comment by wzhsunn** [comment]
It's very helpful for me! Thank you ! You are so nice .
