### ISSUE TITLE
Graphs do not show for bills 

### ISSUE THREAD

**Issue by MarkehMe** [librenms/librenms#6056]
There is no API endpoint for showing graphs with bills.

Although I can get the graph while logged in from:
 `/graph.php?type=bill_bits&id=1&from=1488286800&to=1490965199&width=1000&height=200&total=1`

The API call does not accept `devices/1/bill_bits?width=500&height=300` (assuming this is only for devices)

Perhaps there is an alternative I'm no aware of.

**Comment by laf** [comment]
GitHub is for bugs only, Please post feature requests in https://community.librenms.org/c/feature-requests but yes, this api call doesn't exist as of today.

**Comment by MarkehMe** [comment]
Oh sorry, I didn't realise.

It doesn't look like new features get added very quickly. Would you accept a pull request?

**Comment by laf** [comment]
Features get added when someone has time to work on them or it's of personal interest so $time varies.

But PR's are much more preferred than a request :)

**Comment by MarkehMe** [comment]
PR #6068
