### ISSUE TITLE
Not possible to add host again after removal

### ISSUE THREAD

**Issue by patrick7** [librenms/librenms#6060]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 7f91fab663a2f3b1991f8ccd35b815e596264b44
DB Schema | 172
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.54-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

After I deleted a host (over the GUI) it's not possible to add it again (GUI/CLI).

> (ZRH)root@monitor:/var/www/xyz/subdomains/librenms# ./delhost.php cr1.location.xyz.li
> Host doesn't exist!

> (ZRH)root@monitor:/var/www/xyz/subdomains/librenms# ./addhost.php cr1.location.xyz.li ap v3 xxx yyy zzz sha aes 
> Already have host cr1.location.xyz.li (cr1)
> 

I don't see the devices in the "devices" table, however there are some other devices with the same "sysName". (cr1.location.xyz.li)

**Comment by laf** [comment]
It is purely because it's got a duplicate sysName, just force add the device.
