### ISSUE TITLE
Add device notes field to Alerts widget on dashboard

### ISSUE THREAD

**Issue by pblasquez** [librenms/librenms#6070]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

Hello,

Would like for someone to do a (hopefully) simple addition of the Device Notes column to the Alerts widget column list.  I have no preference over whether it should be a default column or not, I simply want to display device notes for each alert so my team can track tickets and such.

Thanks!
-Paul

**Comment by laf** [comment]
Please post feature requests at https://community.librenms.org/c/feature-requests
