### ISSUE TITLE
Add Extrahop Appliance as a Supported Device.

### ISSUE THREAD

**Issue by thejimmahknows** [librenms/librenms#6080]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
:/opt/librenms# ./validate.php 
==========================================================
Component | Version
--------- | -------
LibreNMS  | 41824dda15641eeba3f5af00b9d537642fe13e55
DB Schema | 173
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.54-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
[extrahop_discovery.txt](https://github.com/librenms/librenms/files/818019/extrahop_discovery.txt)
[extrahop_poller.txt](https://github.com/librenms/librenms/files/818020/extrahop_poller.txt)
[extrahop_snmpwalk.txt](https://github.com/librenms/librenms/files/818021/extrahop_snmpwalk.txt)

##heres the  MIB
[EXTRAHOP-MIB.txt](https://github.com/librenms/librenms/files/818032/EXTRAHOP-MIB.txt)

- [x] Please provide as much detail as possible.
Request is to add  LibreNMS support for Extrahop Appliances ( https://www.extrahop.com/ )
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by geordish** [comment]
I just loaded your snmpwalk into my install, and it looks fairly well supported. What are you missing?

**Comment by thejimmahknows** [comment]
The 10Gig NIC (eth4+5) are showing connected(bold) but not showing stats. I'm not sure if the SNMP walk contains the serial number, Extrahop Discover Appliance version running, or any other sensors.

Also maybe the logo changes to Extrahops official logo?

**Comment by geordish** [comment]
Ah, I didn't realise it was being picked up as something else for me.

I've created a PR to try and fix the discovery #6097. Would you mind testing?

Also, for the ports, could you run 2 poller debugs for this device spaced about 5 mins apart like so:

./poller.php -r -d -v -f -h <HOST> -m ports

**Comment by thejimmahknows** [comment]
[chaexhop28-1.ports.txt](https://github.com/librenms/librenms/files/821647/chaexhop28-1.ports.txt)
[chaexhop28-1.ports-5minLater.txt](https://github.com/librenms/librenms/files/821669/chaexhop28-1.ports-5minLater.txt)

**Comment by geordish** [comment]
It doesn't look like you have much traffic passing over those links:
```php
    [10] => Array
        (
            [ifName] => eth4
            [ifHCInOctets] => 0
            [ifHCOutOctets] => 0
        )

    [11] => Array
        (
            [ifName] => eth5
            [ifHCInOctets] => 1111719120035
            [ifHCOutOctets] => 0
        )
	// 5 mins later	
	[10] => Array
        (
            [ifName] => eth4
            [ifHCInOctets] => 0
            [ifHCOutOctets] => 0
        )

    [11] => Array
        (
            [ifName] => eth5
            [ifHCInOctets] => 1114171258368
            [ifHCOutOctets] => 0
        )
```

There does seem to be a bit of a bug though. Mind testing out PR #6106, and seeing if you get some traffic on eth5?

**Comment by thejimmahknows** [comment]
Sure thing, just ran the daily.sh

Here's a screen shot of the appliances Admin page showing interfaces stats.
![image](https://cloud.githubusercontent.com/assets/15802946/23625800/692b4892-0278-11e7-8892-cbbd7feb3c1b.png)

**Comment by geordish** [comment]
So that patch hasn't been merged, so you will need to follow the instructions on the request itself to test.

Those stats make sense, if interface 1 is eth0, and interface 2 is eth1 etc.

**Comment by thejimmahknows** [comment]
Ok, I did
```
./scripts/github-apply 6106
Checking patch includes/polling/ports.inc.php...
Applied patch includes/polling/ports.inc.php cleanly.


```

**Comment by thejimmahknows** [comment]
Looks like info is coming in now...no graphs yet..
![image](https://cloud.githubusercontent.com/assets/15802946/23626235/21ee8dd4-027a-11e7-8b56-97793015398b.png)

**Comment by thejimmahknows** [comment]
Cool, and i see you changed the Icon. Thanks! :-p

**Comment by thejimmahknows** [comment]
Was there a way to pull the Version and Serial number from the snmpwalk using the official MIB file? 
![image](https://cloud.githubusercontent.com/assets/15802946/23626441/ec97cf64-027a-11e7-8b79-68137028ca1d.png)

**Comment by geordish** [comment]
30Gbps?! I did a quick calculation which estimated 30Mbps...

No, I couldn't see any of those things in the walk. Looked a bit empty of data other than firmware version, which should be populated.

**Comment by thejimmahknows** [comment]
Interface 5 (eth4) and Interface 6(eth5) are 10Gb NICs.

**Comment by geordish** [comment]
Does these commits fix your issues?

**Comment by thejimmahknows** [comment]
I will check tomorrow.

**Comment by thejimmahknows** [comment]
Looks good! Thanks!

**Comment by Rosiak** [comment]
Problem solved, closing.
