### ISSUE TITLE
Nvidia Agent - All data showing as nan

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#6098]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hi,

I have installed the agent per the recent instructions - enabled it, and do see the data in snmpwalk (below) ... graphs are now being displayed, but without data (i.e. empty), and it's all showing as nan. Thoughts?
NET-SNMP-EXTEND-MIB::nsExtendOutLine."nvidia".1 = STRING: 0,9,25,0,3,0,0,405,135,0,0,33,4,0,0,0,0,0

Pastebin attached,
1) Discovery, https://paste.ubuntu.com/24121336/
2) Poller, https://paste.ubuntu.com/24121339/

Thanks!

**Comment by laf** [comment]
That seems ok to me, run `./validate.php`.

@VVelox any ideas?

**Comment by VVelox** [comment]
yeah, you should not be getting a new line after the string there.... 

Could you post the output from 'nvidia-smi dmon -c 1'?

I am curious if it is formatting the output differently on your system.

**Comment by VVelox** [comment]
Hmm... how long did you give it post adding it? It will take it a few times before it will begin showing up.

From the poller is creating the RRD for GPU 0.

**Comment by arrmo** [comment]
Sure, NP! First off, validate found some errors ... :-(. No idea why, as I pull from github, but some permissions messed up. Fixed that, will see if some of the graphs come back (all graphs broken for just this one machine it seems).

To the command above (nvidia-smi dmon -c 1), here is the output,
```
# gpu   pwr  temp    sm   mem   enc   dec  mclk  pclk
# Idx     W     C     %     %     %     %   MHz   MHz
    0     9    31     0     3     0     0   405   135
```

And, on how long I waited - a couple hours, figured that was sufficient ... no?

Thanks!

**Comment by arrmo** [comment]
OK, my apologies. No idea how this happened, but again some files with the wrong permissions (pulled from git) - once corrected, this working again. Sorry for the red herring.

Thanks!
