### ISSUE TITLE
Alerts for Access_Point entity showing deleted APs. 

### ISSUE THREAD

**Issue by djamp42** [librenms/librenms#6112]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
==========================================================
Component | Version
--------- | -------
LibreNMS  | 6b2a95025001424e59d872ab36f631c2f1fab857
DB Schema | 173
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

Alerts for the Access_Point entity display deleted access points, even if the same access point active exist in the mysql table.

In the access_point table there is a deleted column for access points that no longer exist on the WLC, or the access point name changed. In my case the same physical access point still exists (Same MAC address), but the name changed. When i create alerts it's using the deleted access point name rather then the new active access point name. Both "access points" are in mysql, but the alerts seem to preference the deleted ones.

I manually deleted the deleted ones, and the alerts display correctly. Needs to be fixed to preference active access points. Or deleted = 0

**Comment by laf** [comment]
We don't provide a default alert rule for access points so you can just update your rule to include %access_points.deleted equals "0"
