### ISSUE TITLE
Export to PDF in Alert Logs needs work

### ISSUE THREAD

**Issue by djamp42** [librenms/librenms#6113]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
==========================================================
Component | Version
--------- | -------
LibreNMS  | 6b2a95025001424e59d872ab36f631c2f1fab857
DB Schema | 173
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

The Alert Log Export to PDF does not display any data in the PDF when you search for IP and then Click Export to PDF.

Additionally exporting a PDF does not display the ports that were affected by the alert. It just displays the IP and alert name and time. IT doesn't give you any details about what triggered the alert.

**Comment by laf** [comment]
This feature isn't going to be worked on in v1, it will be available as default in v2.
