### ISSUE TITLE
anynone can see devices groups created by admin

### ISSUE THREAD

**Issue by maniacek** [librenms/librenms#6122]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
LibreNMS | db58fea
DB Schema | 171
PHP | 5.6.30
MySQL | 5.6.35
RRDTool | 1.6.0
SNMP | NET-SNMP 5.7.3
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

If i create device group anyone can see names of goups (but cant see what is in there).

**Comment by laf** [comment]
Duplicate #5045 

Please check open and closed issues. Also it's worth while you checking with people on irc or the community site before posting issues. GitHub issues are for genuine validated bugs.
