### ISSUE TITLE
Applications | Unbound | More Graphs

### ISSUE THREAD

**Issue by dneto82** [librenms/librenms#6125]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hi,

Thank you for provide unbound support. I just create this issue to evaluate the possibility to extend data collected and graphed from unbound.

Suggestions:

- unbound hits - base volume, cache hits, unwanted traffic 
- unbound_queue - to monitor the internal request list 
- unbound_memory - memory usage 
- unbound_by_type - incoming queries by type 
- unbound_by_class - incoming queries by class 
- unbound_by_opcode - incoming queries by opcode 
- unbound_by_rcode - answers by rcode, validation status 
- unbound_by_flags - incoming queries by flags 
- unbound_histogram - histogram of query resolving times 

All these data already get in script, but not graphed.

Reference:
https://www.unbound.net/documentation/howto_statistics.html

**Comment by laf** [comment]
Please post your feature request here: https://community.librenms.org/c/feature-requests
