### ISSUE TITLE
Bad uptime Alcatel switch 6860/6860E

### ISSUE THREAD

**Issue by h2tp** [librenms/librenms#6132]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

> 
> 
> **LibreNMS 	1c48fe3**
> **DB Schema 	173**
> **PHP 	7.0.14-1 dotdeb+8.1**
> **MySQL 	10.0.28-MariaDB-0+deb8u1**
> **RRDTool 	1.4.8**
> **SNMP 	NET-SNMP 5.7.2.1**

Hello everyone

I have a problem with the uptime of the Alcatel 6860 / 6860E switches.

The uptime information is bad.

Would you have an idea?
![alcatel686056y](https://cloud.githubusercontent.com/assets/6437040/23701284/78867576-03f6-11e7-82df-0795149a9d1e.PNG)
![alcatel686056ycli](https://cloud.githubusercontent.com/assets/6437040/23701292/7ce102b2-03f6-11e7-9330-b35771803ca5.PNG)

The OID corresponding to the uptime is: .1.3.6.1.4.1.6486.801.1.2.1.69.1.1.2.1.10

The information returned by snmpwalk is OK:

> iso.3.6.1.4.1.6486.801.1.2.1.69.1.1.2.1.10.6 = Timeticks: (3003341700) 347 days, 14:36:57.00

**Comment by laf** [comment]
You need to provide all the info in point 3

**Comment by Rosiak** [comment]
No further information.

**Comment by h2tp** [comment]
Component | Version
--------- | -------
LibreNMS  | a0abcbb6496def0bacc77fb811064c314c6d087e
DB Schema | 184
PHP       | 7.0.17-1~dotdeb+8.1
MySQL     | 10.0.30-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================
