### ISSUE TITLE
Ports last status changed not working

### ISSUE THREAD

**Issue by laf** [librenms/librenms#6133]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

https://community.librenms.org/t/status-changed-not-displaying-correctly/649/5

**Comment by mbusk** [comment]
Hi
Hope this is what is needed, havn't tried it before.

[ x] Is your install up to date? Updating your install
[ x] Please include all of the information between the ==================================== section of ./validate.php which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 097a8277590b862b715ce86a9600da21eb35ba8f
DB Schema | 167
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 5.7.17-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
[x]Please provide ALL info asked for here.
[x]Please provide as much detail as possible.
[x]Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
[Librenms_discover.txt](https://github.com/librenms/librenms/files/829073/Librenms_discover.txt)
[poller-10.40.0.30.txt](https://github.com/librenms/librenms/files/829079/poller-10.40.0.30.txt)

**Comment by laf** [comment]
Nothing should be needed, it's broke for everyone I think

**Comment by laf** [comment]
Claims on the community site this isn't broke anymore, can confirm it seems ok for me.
