### ISSUE TITLE
Notifications by email to admins isn't working when using Active Directory authentication

### ISSUE THREAD

**Issue by FTBZ** [librenms/librenms#6134]
Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

Component | Version
--------- | -------
LibreNMS  | 1c48fe399f78b7acd93384646ef159c0d00d0ac1
DB Schema | 173
PHP       | 7.0.11
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

When trying to send mails notifications to admins users that are using Active Directory authentication, I noticed that was not working. Based on the @laf debugging by IRC it's seems to be not possible.

<img width="1018" alt="unknown" src="https://cloud.githubusercontent.com/assets/1927109/23708175/568d6276-0415-11e7-97e7-20609c822f24.png">

Debug code:
```
$init_modules = ['alerts'];
include '/opt/librenms/includes/init.php';

print_r(get_userlist());
```

Using this code returns an empty array even if the alerts capture debug is returning the correct informations.

**Comment by FTBZ** [comment]
Not sure that's related to AD, because sysContact isn't working too...

**Comment by laf** [comment]
It is related to AD, we can't auth to get user emails for AD so that will absolutely not work right now.
