### ISSUE TITLE
daily.sh Error

### ISSUE THREAD

**Issue by thebigsmileXD** [librenms/librenms#6146]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
```
Component | Version
--------- | -------
LibreNMS  | 9c780a46cb95db123991cb9e15c049531289156f
DB Schema | 173
PHP       | 7.0.16-1~dotdeb+8.1
MySQL     | 10.0.29-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
```

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Accordingly to http://docs.librenms.org/General/Updating/ i tried to update LibreNMS using `su librenms ./daily.sh`
It gave me following error:
`./daily.sh: 91: ./daily.sh: Syntax error: "(" unexpected (expecting "}")`

**Comment by laf** [comment]
That's not the complete out put of validate.php

Please also run `git status`

**Comment by thebigsmileXD** [comment]
http://pastebin.com/9Da6Wz4c

**Comment by laf** [comment]
You should fix the first FAIL that's occurred about permissions.

Then run `git pull && ./daily.sh`

**Comment by thebigsmileXD** [comment]
```
==========================================================
Component | Version
--------- | -------
LibreNMS  | b4c93cf9e699511196835f739d46f342e76f8d15
DB Schema | 173
PHP       | 7.0.16-1~dotdeb+8.1
MySQL     | 10.0.29-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================
```
Looking good, thanks!
