### ISSUE TITLE
Add os/model modification for oxidized API call

### ISSUE THREAD

**Issue by BlackDex** [librenms/librenms#6148]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | b4c93cf9e699511196835f739d46f342e76f8d15
DB Schema | 173
PHP       | 7.0.16-3+deb.sury.org~xenial+1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

Hello there,

I'm using LibreNMS together with Oxidized, which both works very nice.
The only thing i mis is a way to modify the model/os for a specific hostname.
Currently i'm only able to change/add a group and nothing else.
The problem is that i have a few switches which report as DNOS, and that is correct, but the dnos model doesn't work with oxidized and i need to modify it to be powerconnect. It would be great if i am able to change this using the config.php or something from within the web-gui.

Kind regards,
BlackDex.

**Comment by laf** [comment]
Feature requests go in our community.librenms.org site, however....

This is dealt with in Oxidized:

```
model_map:
  cisco: ios
  juniper: junos
```

**Comment by BlackDex** [comment]
That is true, but this is limited. You can only map all or nothing. Not a specific switch.
In my case, some switches are DNOS and work, others don't and need to be powerconnect for instance.
This is not something which can be done with oxidized. Since LibreNMS provides the list it seems to me it should also provide a correct or at least an adaptable list.

**Comment by laf** [comment]
You said that some switches are reported as DNOS and that's correct but you want them to be changed to powerconnect, you either do that with model mapping in oxidized or we update our detection to pick those devices up as powerconnect in the first place, we will only do that though if those devices ARE powerconnect.

I suggest you stop by IRC to discuss this as Github is for issues only.
