### ISSUE TITLE
[DASAN Zhone Solutions] Please add possibility to discover and read some parameters from GPON ONTs connected to OLT

### ISSUE THREAD

**Issue by lsfib** [librenms/librenms#6149]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hello,

Could You add to LibreNMS possibility to discover and read some values from GPON ONTs.
Below quick description how it is done on DASAN Zhone GPON devices (examples with NET-SNMP):
https://www.dropbox.com/s/ymqgx3p27rpfo9j/DASAN_GPON_ONT_SNMP.pdf?dl=0

As it is in the file - we cannot read values directly from ONT. We need to read it from OLT - which via control channel will read it from ONT - but I think in that way it is easiest to implement.
All SNMP data You can find in sle-gpon-mib.mib but there are a lot of information so could You at first implement few of them:
* Status
* Serial Number
* Distance
* Rx Power
* Profile

At first there need to be possibility to discovery all connected ONTs and add them to the correct port.
I am not sure how will it be better to do - some suggestions:
a) add new TAB to main devices view - GPON ONTs (where we have for example Map/Inventory/Services/etc.)
b) add new TAB when we sellect GPON port for example PORT1-GPON (where we have Graphs/Real time/ARP Table/etc.)
c) somewhere else 

No matter which one could be use I think better will be not to read all information from OLT (ONTs) when we click tab GPON but something like that:
Select main tab "GPON ONT" -> Select correct "GPON PORT" -> then there could be list of ONT with only brief information like (ONU-ID/Status/GPON SN/Distance/RX Powe/PROFILE/Description) -> then after select correct ONT there will be more additional information (in future)

Below example how it could look like:
https://www.dropbox.com/s/cgxihtpzh25maau/ONT_info.pdf?dl=0

Please let me know if You need additional info.
I can also provide You remote access to one of the OLTs if You would like to test - please send me private message.

**Comment by laf** [comment]
You've not provided any info from point 3.

**Comment by lsfib** [comment]
Update:
Discovery -> http://pastebin.com/HKzDC94e
Poller -> http://pastebin.com/4SU2eQ0H
Walk -> http://pastebin.com/Bwgw95sb

**Comment by lsfib** [comment]
one mistake in snmpwalk, correct one -> https://www.dropbox.com/s/uynl4wtyy36yk4y/snmp_walk.txt?dl=0

**Comment by lsfib** [comment]
Hello,

If You need any information or additional explanation about this request please let me know.

Thank You in advance for support

**Comment by laf** [comment]
The snmpwalk doesn't contain any OIDs referenced in the documents: .1.3.6.1.4.1.6296.101.23.3

Once you've provided the info we need we will re-open this.

**Comment by lsfib** [comment]
Hello,

Sorry for late response:
SNMPwalk .1.3.6.1.4.1.6296.101.23.3
https://pastebin.com/jYpjkUB7

SNMPWwalk .1.3.6.1.4.1.6296.101.23
https://www.dropbox.com/s/1fyzueqjzolye8s/snmpwalk_V5824G.log?dl=0

If You need anything more please let me know - sorry one more time for big delay

**Comment by laf** [comment]
This is more than just device detection and requires some core coding. Moved to feature request: https://community.librenms.org/t/dasan-zhone-solutions-please-add-possibility-to-discover-and-read-some-parameters-from-gpon-onts-connected-to-olt/1236
