### ISSUE TITLE
Add Alert-Groups.

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#616]
Manage alerts to be run on a group of heterogene devices. Such as DC, CustA, ClusterA,...

This will require a Page that manages devices into Alert-Groups and a new notation for Alert-Rules to indicate a single target, a global target or a group target.

**Comment by paulgear** [comment]
Sounds like a good idea to me

**Comment by Alastair-VOIPUNLIMITED** [comment]
Definitely, especially when you are attempting to monitor a large number of nodes in groups, are there any updates on this feature? We are keen to start testing :)

Thank you

Alastair

**Comment by f0o** [comment]
it's on top of my todo-list :)

I cant give a specific ETA as my work-schedule is a bit 'on-call'-heavy currently...
However, I got a very early draft running and am just fiddling around the DB-notation for the rules.

What I didnt bother doing so far is the GUI, I suggest a simple multi-select-box with a name... but I'm absolutely not a GUI-maker haha - feel free to suggest something better.

**Comment by laf** [comment]
Happy to pick up the GUI parts as always @f0o. If you give me an idea on how it works and the db schema updates I'll work on something to coincide with you releasing the back end update.

**Comment by Alastair-VOIPUNLIMITED** [comment]
thank you for such a quick response, and for the work done already!

Would that be as a drop down? you could always do it the same way observium did, which is to rely on the user putting in that metric themselves. (screenshot attached)

![capture111](https://cloud.githubusercontent.com/assets/11542248/6801665/c54d2a16-d221-11e4-83ef-8072ee0babe7.PNG)

please bear in mind that our "types" are added ones from us on the back end so we could do it this way, would it would be possible for a GUI way to add "device types" too? instead of auto detection?

Thank you

Alastair

**Comment by laf** [comment]
We're open to suggestions on how to do the UI (or have a go at it yourself if you like :))

As for setting your own device types, from looking at the code we would allow users to break things by doing that (for instance certain polling functions check the device type so if this was no longer set to what was expected then polling wouldn't run).

That doesn't mean we couldn't allow someone to set a secondary device type - @f0o how would that work with your idea for groups?

Alternatively you can set a custom description already per device. You could set the device type you want there then use that in the alerts system.

**Comment by Alastair-VOIPUNLIMITED** [comment]
unfortunately we don't have anybody with experience with UI design, however I believe a few members of the team are quite keen to share various mySQL tweaks and changes that they made on our version of observium if they are applicable to librenms :)

Thank you

Alastair

**Comment by laf** [comment]
@Alastair-VOIPUNLIMITED No probs on the UI side - I end up doing a lot of that anyway so we're covered :)

Would love to see the tweaks they've made, we're a little bit different now on MySQL schema but a large % still remains the same.

Is the API of any use to you? If so and it's missing anything then let me know so I can add it in.

**Comment by f0o** [comment]
I know it's been a while. I apologize I couldn't finish this PR earlier.

I hope it solves your needs although it lacks an UI for now.
Please use with caution as it hasn't been tested indepth yet and a column rename occurred.
Worst case the UI will contain bugs due to the rename.

I've tested the entire Alerting backend and it's working fine.

**Comment by f0o** [comment]
@Alastair-VOIPUNLIMITED do you want a rule to be processed for several groups?

Current PR only covers 1 Group per Rule and N Groups per Device.

**Comment by Alastair-VOIPUNLIMITED** [comment]
That would be fantastic! Would mean a lot fewer alarm checkers!!

Sent from Nine<http://www.9folders.com/>

**Comment by f0o** [comment]
Cheers @Alastair-VOIPUNLIMITED, we just discussed the issue on IRC and came to the conclusion that a different approach will be better.

sadly I've to postpone this feature again, I will try to get a draft done by today but most of the day has already passed :/

**Comment by Alastair-VOIPUNLIMITED** [comment]
Hey team,

That's perfectly fine, we are not in the office until next Tuesday anyway. Thank you for your time on this :)

When we start implementing it ourselves we will no doubt have things to contribute too.

Alastair

Sent from Nine<http://www.9folders.com/>

**Comment by f0o** [comment]
@Alastair-VOIPUNLIMITED We've merged Device-Groups now, These can be mapped to alerts.

Please update your install and check out #722 for details, Or come to IRC if you got questions :)
