### ISSUE TITLE
Added detection for Hirschmann Railswitch

### ISSUE THREAD

**Issue by mail4git38** [librenms/librenms#6161]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 1d80a0d2a689e2f91ed72d614313aabc992529f2
DB Schema | 173
PHP       | 7.0.15
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

discovery : http://pastebin.com/raw/EE9x6Mhj
poller : http://pastebin.com/raw/KKPyCLWN
snmpbulkwalk : https://gist.githubusercontent.com/mail4git38/07dee7f178740860d757a8a99b40e9e1/raw/84bad476937390d2de9315fd20eb8594809ec321/gistfile1.txt

- [X] Please provide as much detail as possible.
Tests are done with Hirschmann Railswitch RS30

- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
Are these the same devices

What OS do they run?

**Comment by mail4git38** [comment]
RS30 is a switch and EAGLE is a firewall. There are both products from Hirschmann (Industrial network devices manufacturer).

They are also both running a dedicated OS, Hirschmann Railswitch OS and Hirschmann EAGLE OS.

**Comment by laf** [comment]
Have you included the debug info from both devices, I only see one?

**Comment by mail4git38** [comment]
You're right. At this time, I've just published the RS30's discovery. 

I have to connect an EAGLE on my network to be able to get the discovery, poller and snmpwalk files.

**Comment by laf** [comment]
I've removed EAGLE info from the request, please post a separate one for that when you have the info.

**Comment by mail4git38** [comment]
Ok to create a new issue when I'll be able to provide requested files.

I should pull the new discovery files for the Hirschmann RS30 in the coming days. 

The files are written but I still need to test them once again.

**Comment by laf** [comment]
Ah ok so you're contributing this yourself. Thanks

**Comment by murrant** [comment]
Fixed by #6207
