### ISSUE TITLE
Fortigate OS 5.4.x does not get any interfaces detected.

### ISSUE THREAD

**Issue by basn** [librenms/librenms#6163]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 1d80a0d2a689e2f91ed72d614313aabc992529f2
DB Schema | 173
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

Since update from fortios 5.2 to 5.4 the ports does not show up and does not get graphed.
Seen this on multiple firewalls, i am unsure if they changed mibs or something like it.
I have access to fortinet support if you need me to download mibs etc.

[snmpbulkwalk.txt](https://github.com/librenms/librenms/files/835040/snmpbulkwalk.txt)
[poller.txt](https://github.com/librenms/librenms/files/835039/poller.txt)
[discovery.txt](https://github.com/librenms/librenms/files/835041/discovery.txt)

**Comment by Rosiak** [comment]
Hi there,
Please check #3859

**Comment by basn** [comment]
Thanks, Rosiak.. :)
