### ISSUE TITLE
Tandberg data EXABYTE MAGNUM 224

### ISSUE THREAD

**Issue by Bernardoni** [librenms/librenms#6172]
Hi, librenms do not dected corretly Tandberrg data tape library model
Device 	Vendor ID 	Product ID 	Serial Number 	Firmware Rev 	SCSI ID:LUN
 Library 	 EXABYTE  	 MAGNUM 224  	 000089010405 	 C304  	 3:1 
 Drive 	 IBM  	 ULTRIUM-HH4  	  1K10083383 	 97F1  	 3:0 

[discovery.txt.gz](https://github.com/librenms/librenms/files/835995/discovery.txt.gz)
[poller.txt.gz](https://github.com/librenms/librenms/files/835993/poller.txt.gz)
[snmpwalk.txt.gz](https://github.com/librenms/librenms/files/835994/snmpwalk.txt.gz)

Thank you in advance.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
The snmpwalk has basically no info in it, I've submitted a pull request to have detection but you won't see any data collected.
