### ISSUE TITLE
Login error authentication failed

### ISSUE THREAD

**Issue by CodaAmok** [librenms/librenms#6183]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

```
==========================================================
Component | Version
--------- | -------
LibreNMS  | dad2a5e9cc0ea3dc5115d2fe2f0d5d5547289ffe
DB Schema | 176
PHP       | 5.5.9-1ubuntu4.21
MySQL     | 5.5.54-MariaDB-1ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2
==========================================================
```

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
`./discovery.php -h CODAAMOKSMON -d | ./pbin.sh`
https://p.libren.ms/view/b13acf02
`./poller.php -h CODAAMOKSMON -r -f -d | ./pbin.sh`
https://p.libren.ms/view/0bc4279b
`snmpbulkwalk -OUneb -v2c -c # CODAAMOKSMON .  | ./pbin.sh`
https://p.libren.ms/view/dc3ffd4f
- [x] Please provide as much detail as possible.

I use a nginx reverse proxy to access LibreNMS so `$config['base_url'] = "/nms/";` and here's my nginx config:

```
        location /nms/ {
                proxy_buffering off;
                proxy_pass http://192.168.0.104/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                auth_basic "Restricted Area";
                auth_basic_user_file /etc/nginx/.htpasswd;
        }
```

I have rebooted both servers (proxy + librenms) and ensured all patched up.

Symptoms:
- I see the red bubble "Login error - authentication failed" when simply loading the login page without attempting to login. Login in using my normal credentials fails reproducing the same red bubble with same text. I created a new user via adduser.php w/ access level 10 and still same issue.
- If I browse to server by IP, I can login successfully. Albeit all template structure and images are broken due to base_url config but I successfully logged in.

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Sadly there's nothing being logged in syslog or /opt/librenms/logs when refreshing the login page or attempting to login (apart from normal POST/GET in access log).

This issue must be caused by a very recent thing as I logged in ~3 days ago and it was fine.

On a separate note, after always logging in (successfully) from domain.tld/nms/, it goes back to the root of the domain address rather than returning me back to domain.tld/nms/. I would expect that after login,it to take me back to whatever is configured in base_url?

**Comment by laf** [comment]
Try setting the full base url?

**Comment by CodaAmok** [comment]
@laf set to "https://domain.tld/nms/" and problem still exists. setting it to "domain.tld/nms/" broke template

**Comment by laf** [comment]
What authentication method?

**Comment by CodaAmok** [comment]
@laf Sorry, forgot to mention that. I just use db auth

**Comment by laf** [comment]
What web server is librenms using?

**Comment by CodaAmok** [comment]
@laf apache

**Comment by laf** [comment]
I've just tested nginx -> apache and it allows me to login ok.

Can you simplify your test and just try against apache to start with?

**Comment by CodaAmok** [comment]
Well that's what I did when I browsed to it via IP which negated proxy,
logs in ok then

**Comment by laf** [comment]
Try: `git checkout 1d243c40c76d34a44b25237b9db00edc9bffd217` and try again.

**Comment by CodaAmok** [comment]
@laf yeah that sorted it :)

**Comment by laf** [comment]
Well not really, we need to work out what's gone on - I can't replicate it to fix though :(

**Comment by CodaAmok** [comment]
Do you want remote access to mine?

**Comment by laf** [comment]
That would be ace. Want to jump in irc to discuss?

**Comment by CodaAmok** [comment]
Thank you, not sure if you've forgotten about the redirect to / after login?

**Comment by laf** [comment]
No: `header('Location: '.$_SERVER['REQUEST_URI'] ?: $config['base_url'], true, 303);` that should switch to base_url if REQUEST_URI isn't set.
