### ISSUE TITLE
API call for graphs not working

### ISSUE THREAD

**Issue by markabrahams** [librenms/librenms#6184]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [?] (it's unclear what info is asked for at this URL) Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | dad2a5e9cc0ea3dc5115d2fe2f0d5d5547289ffe
DB Schema | 176
PHP       | 7.0.16-1~dotdeb+8.1
MySQL     | 10.0.29-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

The API call to this endpoint to produce graphs no longer works:
api/v0/devices/$hostname/ports/$ifName/$type

Apache produces error log message of the form:
[Tue Mar 14 00:55:07.255606 2017] [http:error] [pid 5067] [client 10.1.1.20:35430] AH02428: Empty response header name, aborting request

The problem is in the function get_graph_by_port_hostname() in html/includes/api_functions.inc.php that provides the graphs.  This sets a null response header that causes the error.

The errant call is:
$app->response->headers->set(set_image_type());

as set_image_type() in html/includes/functions.inc.php doesn't return the appropriate value.

Replacing this call with something of the form:
$app->response->headers->set('Content-Type', 'image/png');

eliminates the error.

**Comment by murrant** [comment]
Have you changed your graphs to SVG? Is the API outputting PNG data?

**Comment by markabrahams** [comment]
I haven't tested SVG.  I'm specifically using PNG, and that's what I've verified as broken, although it looks as though SVG would suffer the same fate.

**Comment by markabrahams** [comment]
Submitted PR (#6186) for this, which adds a get_image_type() function that returns a string that can be passed in to the Slim headers set method.

**Comment by laf** [comment]
Thanks @markabrahams. I refactored your code slightly but aside from that it was perfect. Thanks.
