### ISSUE TITLE
PostgreSQL Support

### ISSUE THREAD

**Issue by b4** [librenms/librenms#619]
PostgreSQL database support, would be nice to support multiple database backends.

**Comment by laf** [comment]
We'd need to convert the schema
Add updating support
Add dbFacile support for pgsql

All not impossible but certainly would be a future thing - that's if someone wants to pick this up :)

**Comment by paulgear** [comment]
It definitely would be great to support PostgreSQL, but I suspect that it will be a big job to convert, since the SQL code is spread throughout the code base.

**Comment by joubertredrat** [comment]
Hi,
instead of dbFacile couldn't be a orm? currently there are several good orm with support multiple databases, similar to this as example, http://www.codeigniter.com/userguide3/database/query_builder.html#selecting-data

**Comment by laf** [comment]
Closing this, work is underway converting the front end to laravel which will support this and then we can sort polling / disco to do the same at which point other backend dbs are supported.

**Comment by jpoa** [comment]
Hey there! Any news on this?

**Comment by laf** [comment]
No one is working on it.

**Comment by murrant** [comment]
@jpoa https://github.com/librenms/librenms/pull/8318
