### ISSUE TITLE
Removed devices do not show user who removed them

### ISSUE THREAD

**Issue by towster** [librenms/librenms#6200]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

I removed a device but my userid does not show as the person who removed it
![capture](https://cloud.githubusercontent.com/assets/1965956/23953996/22e076bc-0964-11e7-9fb2-1e2ee872b6f1.PNG)

**Comment by laf** [comment]
No output of validate provided!

**Comment by laf** [comment]
I've submitted a fix for this but please in future provide the info we ask for.
