### ISSUE TITLE
Polling Issue.

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#621]
I have a port which has been running for a while, today it was shutdown.
But LibreNMS keeps reporting "issues", each time the port is polled the following is printed to the eventlog:
http://snag.gy/57wFp.jpg

Lafwood is seeing the same issue with one of his devices.

I've taken the following from a debug poll:
http://snag.gy/AtJjJ.jpg

**Comment by laf** [comment]
I think I've sorted this in #623 if you want to try the (simple patch).

It looks like those interfaces which are admin down don't have a dot1q vlan or trunk type associated as they are admin down so we now just skip over them.

**Comment by f0o** [comment]
Merged #623

**Comment by Rosiak** [comment]
The issue is still present:
http://snag.gy/CvoIE.jpg

**Comment by laf** [comment]
Done another PR which should fix this again :) #625
