### ISSUE TITLE
Disabled Devices | Still show in Alerts Widget

### ISSUE THREAD

**Issue by dneto82** [librenms/librenms#6213]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

==========================================================
Component | Version
--------- | -------
LibreNMS  | 559a22157f7197576c52542665486585344d78b5
DB Schema | 177
PHP       | 7.0.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.2
==========================================================
Disabled device correctly isn't showed in Summary Widget, WorldMap but still present in Alerts Widget:

![image](https://cloud.githubusercontent.com/assets/1860114/24024163/eae9193a-0a8f-11e7-9d7d-af82ed3e8983.png)

![image](https://cloud.githubusercontent.com/assets/1860114/24024176/0bf177d0-0a90-11e7-8cf0-4b60ff2c2676.png)

Maybe to just make sure to show only enabled devices in Alert widget.

**Comment by laf** [comment]
You need to post your rule as the showing of disabled devices in alerts is down to that and nothing else

**Comment by dneto82** [comment]
Hi @laf . Thanks.

This rule is a default / predefined rule from install.

![image](https://cloud.githubusercontent.com/assets/1860114/24055378/864ecdbe-0b1e-11e7-8f8c-0aaa330846d5.png)

On widget, I'm using these filters:

![image](https://cloud.githubusercontent.com/assets/1860114/24055401/9e5dc2f2-0b1e-11e7-84b5-d491a2fb55d9.png)

I tried to change my rule to include an AND device.status !=0, but without success. Device status is related to Enable/Disabled status right?

![image](https://cloud.githubusercontent.com/assets/1860114/24055450/d49d23f8-0b1e-11e7-9d1d-14ce8eabe320.png)

**Comment by laf** [comment]
I expect this is because the device was down before you disabled it and so the alert is still active as the device is no longer polled due to it being disabled and therefore can't refresh or clear out it's stale alerts.

So the question is really, what should we do in this instance.

Clear out alerts when a device is disabled?
Leave as is?
Hide alerts for disabled devices in the alerts screen?

@librenms/reviewers Thoughts?

**Comment by murrant** [comment]
Hide the alerts, that way if the device is re-enabled, they will still be there.
