### ISSUE TITLE
FreeNAS 9.10 - Storage disks/mounts not discovered

### ISSUE THREAD

**Issue by dragans** [librenms/librenms#6215]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

==========================================================
Component | Version
--------- | -------
LibreNMS  | 3f5bf56b557668659e32909204da3a42c6adac09
DB Schema | 170
PHP       | 7.0.11
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

[Discovery](https://gist.github.com/dragans/8c59c472154234512066849addd7c5f1)
[Poller](https://gist.github.com/dragans/59c69a18f5fe73b2c3ae914c90857b7a)
[SnmpWalk](https://gist.github.com/dragans/64ab7bfd8d00e57654b6a7df9431d81d)

We have two servers with FreeNAS 9.10 on which none of the disks/mounts are discovered by the discovery module but are listed during snmpwalk (example: /mnt/FREENAS-2).

We have a third server with an older installation, FreeNAS 9.3, on which disk/mounts discovery works and finds all the disks on the system.

I already tried to expose the disks as stated in link below, but it didn't work unfortunately.
http://docs.librenms.org/Support/FAQ/#why-are-some-of-my-disks-not-showing

I couldn't find any other issue with similar problem, but I figure that you are already aware of it. Probably it's related to changes in FreeBSD (Our FreeNAS 9.3 runs on FreeBSD 9.3-RELEASE-p28, and FreeNAS 9.10 servers run on FreeBSD 10.3-STABLE).

**Comment by dragans** [comment]
Just realized there is one more difference on 9.10 servers.

9.10 servers are using hardware RAID controllers. Could that break the discovery process on LibreNMS?

**Comment by laf** [comment]
From the discovery output it looks like the device isn't responding to the second snmpwalk request for hrStorageEntry. Can you run this command twice (replace the relevant variables like HOSTNAME and COMMUNITY).

`/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs -m HOST-RESOURCES-MIB:HOST-RESOURCES-TYPES:NetWare-Host-Ext-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 hrStorageEntry`

**Comment by dragans** [comment]
Tried 5-6 times from LibreNMS server CLI, and it worked every time.

OID results are displayed almost instantly when command is executed.

**Comment by laf** [comment]
Using your data this is what I see:

![image](https://cloud.githubusercontent.com/assets/3941142/24245477/e33c6856-0fba-11e7-8423-8fed71ddd59b.png)

**Comment by dragans** [comment]
Yes, those disks/mounts exist on the FreeNAS instance.

Unfortunately, nothing is shown on our side. Just checked LibreNMS DB too, and none of those mounts exist in the DB.

![screen2](https://cloud.githubusercontent.com/assets/15086032/24246178/6d26d550-0fc6-11e7-9ad6-8dbaa9bd7339.png)
![screen1](https://cloud.githubusercontent.com/assets/15086032/24246177/6d26b840-0fc6-11e7-9730-eb0dd9f1f052.png)

**Comment by laf** [comment]
I don't have anymore suggestions I'm afraid other than this is a snmp issue on the device. Using your snmpwalk I get the storage back ok: https://p.libren.ms/view/raw/7671127d

You can see them being registered correctly in that.

**Comment by dragans** [comment]
Well, good news is I found a workaround. :)

It's definitely some bug in FreeNAS. Discovery works OK when using SNMP v1. Older FreeNAS version is using v2, and it is working OK.

Didn't think about trying that before, sorry about that.

Thanks for investigating :)

P.S. Maybe you could mention this workaround for FreeNAS on your wiki if someone else has a similar problem (if you deem it worthy off course). It's possible it relates to other FreeBSD systems too.

**Comment by laf** [comment]
All our docs are available online to be edited so feel free to add an FAQ :)

Hopefully people also search here first.
