### ISSUE TITLE
Feature Request: Loading on page

### ISSUE THREAD

**Issue by joubertredrat** [librenms/librenms#622]
Hi,

I think that is good idea to implement one loading on page similar youtube as example. I Can implement this on librenms

**Comment by Rosiak** [comment]
Ehm could you clarify a bit more?
Or at least show a picture of what you mean.

**Comment by joubertredrat** [comment]
@Rosiak 

http://i.imgur.com/5mvNcBv.png
http://i.imgur.com/xOALyMC.png
http://monitor.kap-no.de

**Comment by f0o** [comment]
Did @laf say smt about what color to use?

**Comment by joubertredrat** [comment]
@f0o , @laf saw blue, if needs to change, we can reopen this and change again :)

**Comment by laf** [comment]
@joubertredrat How are you getting on with this? With the new styles maybe it's worth looking at locking the color of the bar down based on the style chosen.

You can set the css now in html/styles/dark.css, html/styles/light.css or html/styles/mono.css.

**Comment by f0o** [comment]
I agree with @laf 
Btw. red would be nice for the dark theme now hehe

**Comment by f0o** [comment]
any updates @joubertredrat ?
