### ISSUE TITLE
rrdcached - MySQL App -  Error Drawing Graph

### ISSUE THREAD

**Issue by wriedel** [librenms/librenms#6223]
Hi Folks,

if I enable
```
$config['rrdcached']    = "unix:/var/run/rrdcached.sock";
$config['rrdtool_version'] = '1.6.0';
```
everything works smoothly beside the graphs for the MySQL Application.

```
RRDTool Command
rrdtool graph /tmp/uYwinQJWxSQgZGpv --alt-autoscale-max --rigid -E --start 1489880700 --end 1489967100 --width 2124 --height 983.5 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal --alt-autoscale-max --rigid -E --start 1489880700 --end 1489967100 --width 2124 --height 983.5 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal COMMENT:'Connections Now Min Max Avg\l' DEF:ds0=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:MaCs:AVERAGE DEF:ds0min=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:MaCs:MIN DEF:ds0max=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:MaCs:MAX DEF:ds1=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:MUCs:AVERAGE DEF:ds1min=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:MUCs:MIN DEF:ds1max=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:MUCs:MAX DEF:ds2=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:ACs:AVERAGE DEF:ds2min=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:ACs:MIN DEF:ds2max=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:ACs:MAX DEF:ds3=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:AdCs:AVERAGE DEF:ds3min=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:AdCs:MIN DEF:ds3max=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:AdCs:MAX DEF:ds4=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:TCd:AVERAGE DEF:ds4min=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:TCd:MIN DEF:ds4max=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:TCd:MAX DEF:ds5=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:Cs:AVERAGE DEF:ds5min=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:Cs:MIN DEF:ds5max=/opt/librenms/rrd/thor-odd.f1-online.net/app-mysql-43.rrd:Cs:MAX LINE1.25:ds0#CC0000:'Max Connection ' GPRINT:ds0:LAST:%5.2lf%s GPRINT:ds0min:MIN:%5.2lf%s GPRINT:ds0max:MAX:%5.2lf%s GPRINT:ds0:AVERAGE:'%5.2lf%s\n' LINE1.25:ds1#008C00:'Max Used Conne ' GPRINT:ds1:LAST:%5.2lf%s GPRINT:ds1min:MIN:%5.2lf%s GPRINT:ds1max:MAX:%5.2lf%s GPRINT:ds1:AVERAGE:'%5.2lf%s\n' LINE1.25:ds2#4096EE:'Aborted Client ' GPRINT:ds2:LAST:%5.2lf%s GPRINT:ds2min:MIN:%5.2lf%s GPRINT:ds2max:MAX:%5.2lf%s GPRINT:ds2:AVERAGE:'%5.2lf%s\n' LINE1.25:ds3#73880A:'Aborted Connec ' GPRINT:ds3:LAST:%5.2lf%s GPRINT:ds3min:MIN:%5.2lf%s GPRINT:ds3max:MAX:%5.2lf%s GPRINT:ds3:AVERAGE:'%5.2lf%s\n' LINE1.25:ds4#D01F3C:'Threads Connec ' GPRINT:ds4:LAST:%5.2lf%s GPRINT:ds4min:MIN:%5.2lf%s GPRINT:ds4max:MAX:%5.2lf%s GPRINT:ds4:AVERAGE:'%5.2lf%s\n' LINE1.25:ds5#36393D:'New Connection ' GPRINT:ds5:LAST:%5.2lf%s GPRINT:ds5min:MIN:%5.2lf%s GPRINT:ds5max:MAX:%5.2lf%s GPRINT:ds5:AVERAGE:'%5.2lf%s\n' HRULE:0#555555 --imgformat=SVG

RRDTool Output
ERROR: rrdc_fetch: Got 47 lines, expected 1447

```
Any ideas how to drill down on this?

Thanks,
Wolfgang

==========================================================
Component | Version
--------- | -------
LibreNMS  | 12b45f356ea6d642f045f538d47ed7b592e9a3a7
DB Schema | 177
PHP       | 7.0.16-3
MySQL     | 10.2.4-MariaDB-10.2.4+maria~sid-log
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
Do you mean without rrdcached it works fine?

What graph is it that's failing (what url is the page on - no domains needed).

**Comment by wriedel** [comment]
yes, without rrdcached it works fine and just the MySQL Application is affected by rrdcached!
All graphs underneath /apps/app=mysql/ are failing once I enable rrdcached.

**Comment by xbeaudouin** [comment]
Got same error too. Made me crazy !

**Comment by xbeaudouin** [comment]
@laf Since I have same issue on my setup, on the page https://nms/device/device=3/tab=apps/app=mysql/app_section=system/, we have after the mysql is discovered some graphes, THEN it goes with such error (see the screen shot) : 
![capture d ecran 2017-04-03 a 17 33 49](https://cloud.githubusercontent.com/assets/1261517/24617280/c208569a-1893-11e7-86c3-75f6230ddc68.png)

This issue is on all mysql graphes... :/

**Comment by xbeaudouin** [comment]
In fact the RRD file is working correctly, if I remove on the web front all rrdcached info in the configuration file and share rrd files using nfs. 
So there is maybe an issue related to remote rrdcached access.

**Comment by murrant** [comment]
Filed this https://github.com/oetiker/rrdtool-1.x/issues/782 

We'll see what Tobi says.

**Comment by murrant** [comment]
His initial thought is that it may have something to do with the amount of variables in the rrd file.

**Comment by wriedel** [comment]
@murrant  not sure if I get it right but does the "MySQL Application" really uses so much more variables compared to others?

**Comment by murrant** [comment]
Most of our rrds contain 1-4 ds.  MySQL has 78 in one file.  The next highest I could find was NFS which has 58 in one file and 42 in another I think I saw a report of issues with NFS too, so perhaps the max amount with rrdcached is somewhere in there.

**Comment by murrant** [comment]
@wriedel can you please tests #6608 ?
