### ISSUE TITLE
Incomplete CPU and RAM graphing on Enterasys N-series switches

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#6225]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `Component | Version
--------- | -------
LibreNMS  | cd16a071ef6ad59752312b5e0f924b3a62048e47
DB Schema | 177
PHP       | 7.0.8-0ubuntu0.16.04.1
MySQL     | 10.0.25-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3` section of `./validate.php` which you can run from the cli.
- [X ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

[Entera_N3_snmpbulkwalk.txt](https://github.com/librenms/librenms/files/855376/Entera_N3_snmpbulkwalk.txt)
The snmpbulkwalk command does not finish as these switches apparently have issues with VLAN information polling, hence a huge file which I had to kill while running. Probably related to #4988.
[Entera_N3_discovery.txt](https://github.com/librenms/librenms/files/855377/Entera_N3_discovery.txt)
[Entera_N3_poller.txt](https://github.com/librenms/librenms/files/855378/Entera_N3_poller.txt)

This issues is related to the #5974, however on the N-series switches whether be they N3 or N7 modular switches we have a few slots per switches which can each its own CPU and RAM hardware, See below;
![image](https://cloud.githubusercontent.com/assets/16717388/24106041/737f0564-0d8f-11e7-9b9b-a8fd9b34180a.png)
![image](https://cloud.githubusercontent.com/assets/16717388/24106401/6e6e80f8-0d90-11e7-9e39-c8cbf3e06c72.png)
Only one CPU is graphed on this particular switch when in fact it has 3 CPU's (1 per slot). The RAM/Storage entities are not graphed at all even though they exist; as indicated in this post, https://gtacknowledge.extremenetworks.com/articles/Q_A/CPU-N-S-MIBS-QUESTION.
Your help will be appreciated.

**Comment by laf** [comment]
I'm submitting a fix for the proc but mem looks ok. Your snmpwalk doesn't contain the data though so please provide an snmpwalk using this oid: ` .1.3.6.1.4.1.5624.1.2.49`

**Comment by breeman1** [comment]
HI @laf , Sorry for the late reply, I was out of the office for the last few days. As requested, this is the command I ran and the information is attached for your reference, `snmpwalk -c test_string -v2c 192.168.5.1 .1.3.6.1.4.1.5624.1.2.49`
[Entera_N3_snmpwalk.txt](https://github.com/librenms/librenms/files/927789/Entera_N3_snmpwalk.txt)

**Comment by breeman1** [comment]
I have updated to the latest codebase and I can confirm that the "hidden" processors are now being graphed however the mempool polling for these devices; specifically the N-series switches, does not work yet. See attachments below;
[Entera_N3_poller_mempools.txt](https://github.com/librenms/librenms/files/928844/Entera_N3_poller_mempools.txt)
[Entera_N3_discovery_mempools.txt](https://github.com/librenms/librenms/files/928845/Entera_N3_discovery_mempools.txt)

**Comment by laf** [comment]
I've submitted a pull request to fix this, please can you test it? #6458

**Comment by breeman1** [comment]
Thanks @laf ,
The patch works see below.
![image](https://cloud.githubusercontent.com/assets/16717388/25173336/f7626cba-24f3-11e7-9352-0eaf9407ece3.png)
![image](https://cloud.githubusercontent.com/assets/16717388/25173371/1bd44cb2-24f4-11e7-9b09-8896e2e44523.png)

**Comment by breeman1** [comment]
Hi @laf ,

In order to aid readability and effecient troubleshooting, I think it would be great idea to list the discovered "RAM device 1" under their respective Slots since these N-series are modular. I noticed while performing the discovery debug that the MIB uses/displays the Slot numbers like this; 10011001, 10011002, 10011003... for Slot 1, Slot 2, Slot 3 and so on depending on how many modules are installed, see below.
![image](https://cloud.githubusercontent.com/assets/16717388/25174013/57d28ba0-24f6-11e7-8df1-a8d9668f8e29.png)
![image](https://cloud.githubusercontent.com/assets/16717388/25174071/839d99e6-24f6-11e7-9f90-b15ec850656d.png)
Please note that this is slightly different though in C-series switches;
![image](https://cloud.githubusercontent.com/assets/16717388/25174228/fb33e73a-24f6-11e7-8511-e7232dcebe71.png)
![image](https://cloud.githubusercontent.com/assets/16717388/25174240/0102bb0a-24f7-11e7-843c-193d2227b4de.png)

**Comment by laf** [comment]
Adding that in as "Slot: x RAM device 1"

**Comment by breeman1** [comment]
Hi @laf ,

The C-series switches are already graphing the Flash Storage using the same MIB and I noticed that this information is discovered by your pacth, see attached. 
[Entera_N3_poller_mempools_1.txt](https://github.com/librenms/librenms/files/933256/Entera_N3_poller_mempools_1.txt)
[Entera_N3_discovery_mempools_1.txt](https://github.com/librenms/librenms/files/933257/Entera_N3_discovery_mempools_1.txt)
![image](https://cloud.githubusercontent.com/assets/16717388/25174549/fae6bb76-24f7-11e7-9875-c0f08e0d430d.png)


Can you please enable the polling and graphing of this information also for the N-series switches? Thanks.

**Comment by laf** [comment]
You will have to put that as a feature request on the community site, storage can only have one index and this requires two because we have the storage index and the slot number.

**Comment by breeman1** [comment]
I have just created a feature request however I could only upload one picture and could not upload text files showing the debug information I supplied in this issue. The community platform seems a bit limited in feature set or capabilities so I could provide as detailed information as I would have liked, but it could be because I am a new user.

**Comment by breeman1** [comment]
Just to ensure that I understand the index issue. Are you refering to how the information is retrieved via SNMP like shown below?
`etsysResourceStorageDescr.10011001.ram.1 = RAM device 1`
`etsysResourceStorageDescr.10011001.flash.1 = Images & Miscellaneous`
`etsysResourceStorageDescr.10011001.flash.2 = Nonvolatile Data Storage`

**Comment by murrant** [comment]
@breeman1 you can post a link to a non-expiring paste at https://p.libren.ms

**Comment by breeman1** [comment]
Thanks @murrant,

I have just pasted the URLs with required information.

**Comment by breeman1** [comment]
Hi @laf ,

Just wanted to find out if you were able to add the "Slot: x RAM device 1" feature on #6458? I have updated to the latest code base and RAM device 1 entinties are still not sorted by their slot number.

**Comment by laf** [comment]
Done.

**Comment by breeman1** [comment]
Hi @laf ,

Thanks.

I just noticed though that after this update, the C-series Enterasys switches no longer graph the mempools as previously. See below.
**Before the changes**
![image](https://cloud.githubusercontent.com/assets/16717388/25702835/1dcec4c6-30d3-11e7-8c9a-a8942a7c87ac.png)
**After the changes**
![image](https://cloud.githubusercontent.com/assets/16717388/25702855/39008b58-30d3-11e7-9559-46ea931324f0.png)
I also took the screenshot of the switch console;
![image](https://cloud.githubusercontent.com/assets/16717388/25702879/6303e24c-30d3-11e7-9c2e-9d32de0c2ffa.png)
![image](https://cloud.githubusercontent.com/assets/16717388/25703056/3c0c2cd4-30d4-11e7-9dce-b027e57ca95e.png)
I have included the debug files for your reference;
[Entera_C3_snmpbulkwalk.txt](https://github.com/librenms/librenms/files/976059/Entera_C3_snmpbulkwalk.txt)
[Entera_C3_poller_mempools.txt](https://github.com/librenms/librenms/files/976057/Entera_C3_poller_mempools.txt)
[Entera_C3_discovery_mempools.txt](https://github.com/librenms/librenms/files/976058/Entera_C3_discovery_mempools.txt)
