### ISSUE TITLE
NTP application poller missing values in RRD

### ISSUE THREAD

**Issue by tsumaru720** [librenms/librenms#6239]
I've recently added ntp-server and ntp-client application pollers to some of my machines and I'm noticing that not all the values are appearing on the graphs. 

Looking at RRDs their fields are marked as "U"

```
# rrdtool lastupdate app-ntp-client-8.rrd 
 offset frequency jitter noise stability

1490206515: U -1.980 0.195 1.107 U
```
Snippets from pollers: http://pastebin.com/QXGXd8uf

Looking at a poller capture for both ntp-server and ntp-client, the values are returned over SNMP but in the poller rrd update section, it even shows "U"s which suggests its not being passed the values correctly? 

Notable these are the first and last value in both cases...
```
1490206515: U -1.980 0.195 1.107 U
1490206805: U 0.308 -7.662 2.317 0.905 0.058 89078 10 9 0 0 0 7227 U
```
---

DO NOT DELETE THIS INFORMATION.

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 716441eeda921def312f3448de38aa42cf26c50c
DB Schema | 178
PHP       | 5.5.9-1ubuntu4.21
MySQL     | 5.5.53-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

**Comment by tsumaru720** [comment]
Adding a var_dump to my dev poller suggests $ntpserver_data is containing the quotes returned from snmp - which is the first and last value ;)

```
 ntp-serverstring(63) ""3
-0.002
**snip**
8711
8800""
```

Discussion on IRC suggests we should handle removal of the quotes in the poller script itself

**Comment by laf** [comment]
PR merged, thanks for fixing :)
