### ISSUE TITLE
Auto update failed

### ISSUE THREAD

**Issue by tslytsly** [librenms/librenms#6250]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Validate output:
```
Component | Version
--------- | -------
LibreNMS  | 716441eeda921def312f3448de38aa42cf26c50c
DB Schema | 178
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
```

Hi guys,

Got an auto update failed email this morning: 
```
error: Your local changes to the following files would be overwritten by
merge:
	vendor/autoload.php
	vendor/composer/ClassLoader.php
	vendor/composer/autoload_classmap.php
	vendor/composer/autoload_namespaces.php
	vendor/composer/autoload_real.php
	vendor/composer/autoload_static.php
	vendor/composer/installed.json
Please, commit your changes or stash them before you can merge.
Aborting
```

I'm not aware of making any changes to these files?

Any idea what I need to do to resolve this?

Thanks

**Comment by geordish** [comment]
run
```
git reset --hard HEAD
```
then try again.

**Comment by laf** [comment]
Please join our irc channel or use the community site for help, this isn't a bug within the code itself.

**Comment by tslytsly** [comment]
Hi @laf ,
I'm not sure, if I haven't changed those files why would they be different?
I was just wondering if it was a bug with the updating script?

If I'm wrong that's fine, I'll try @geordish suggestion.

**Comment by laf** [comment]
Their's a variety of reasons why you'll have this but afaik it's not due to the daily.sh on it's own, it's usually changing to other branches, testing pull requests or using git on the cli.

**Comment by tslytsly** [comment]
OK, thanks.
