### ISSUE TITLE
No CPU graphing on Cisco 9148 switch whic is based on NX-OS

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#6251]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `Component | Version
--------- | -------
LibreNMS  | 359d5004f2946ea345befabd05f3a8119dca45ae
DB Schema | 181
PHP       | 7.0.8-0ubuntu0.16.04.1
MySQL     | 10.0.25-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

The CPU utilization is not being graphed on LibreNMS even though it is supported by this device. Your help will be appreciated. Please note that we poll this device via SNMPv3 for security reasons without an option to use version 2.
[CiscoNX-OS_discovery.txt](https://github.com/librenms/librenms/files/864766/CiscoNX-OS_discovery.txt)
[CiscoNX-OS_poller.txt](https://github.com/librenms/librenms/files/864767/CiscoNX-OS_poller.txt)
[CiscoNX-OS_snmpbulkwalk.txt](https://github.com/librenms/librenms/files/864768/CiscoNX-OS_snmpbulkwalk.txt)
![image](https://cloud.githubusercontent.com/assets/16717388/24249115/b72b1a9e-0fda-11e7-89c6-f7795342de0f.png)

**Comment by FTBZ** [comment]
I've a SAN fabric using 4x MDS 9148S 16G and it's working. But I'm using release 6.2.x, can be OS related?

**Comment by laf** [comment]
Also running a MDS 9148S 16G 48 FC (1 Slot) on 6.2.x release with no issues.

+ Lots of MDS 9148 FC (1 Slot) with varying release from 5. to 6. with no issues.

**Comment by FTBZ** [comment]
Just noticed the version, 5.0(1a)! This is a very very very very very very very old version.

**Comment by geordish** [comment]
I'm running MDS 9124 (1 Slot) on 5.0a with no issues.

Do you have views configured on this device?

SNMP[[0;36m/usr/bin/snmpget -v3 -n '' -l 'authPriv' -a 'MD5' -A 'String_one' -u 'tester' -x 'AES' -X 'String_two' -Oqv -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:HOSTNAME:161 .1.3.6.1.4.1.9.2.1.58.0[0m]
No Such Object available on this agent at this OID

Your device is not reporting CPU information.

**Comment by breeman1** [comment]
Hi @geordish,
Are you using snmpv2 or snmpv3 on your devices?

**Comment by breeman1** [comment]
Please see the first comment on issue #2872 where I was having issues adding this device via the CLI using the snmpv3. I have dumped the screenshots for your information. Obviosly this is an old install and the CPU and RAM graphing issues have been resolved since then. However it seems that the issue is more related to the snmpv2 versus snmpv3 polling; looking at the old pictures below, rather than it being an OS issue. I am not discounting the later though. In this old issue, the CPU was graphed only when using snmpv2 and not when using snmpv3.
![image](https://cloud.githubusercontent.com/assets/16717388/24288170/081830a4-1085-11e7-8dd2-e135f6a47ccb.png)
![image](https://cloud.githubusercontent.com/assets/16717388/24288175/0cef42e8-1085-11e7-97c4-9e9fec2431db.png)

**Comment by geordish** [comment]
@breeman1 I'm using SNMPv2.

Your device simply isn't responding that it has a CPU. It could be a bug in the SNMP agent, or it could be a misconfiguration, with a view restricting access to that OID.

This is the same in your previous issue. From the discovery you posted:
```
/usr/bin/snmpget -v3 -n '' -l 'authPriv' -a 'MD5' -A 'test123' -u 'nms_user' -x 'AES' -X 'try234' -Oqv -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.9.2.1.58.0
No Such Object available on this agent at this OID
```

**Comment by laf** [comment]
And we use a mix of v2c and v3 (mostly v3). Works fine for all of them.

**Comment by laf** [comment]
@breeman1 any feedback on this, it seems various hardware/software/v2c/v3 users all see this working ok.

**Comment by breeman1** [comment]
Hi @laf, I will close this issue until I can get our network engineer to look into this for me.
