### ISSUE TITLE
Interface Packets stopped working

### ISSUE THREAD

**Issue by fluboi** [librenms/librenms#6252]
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the 
==========================================================
Component | Version
--------- | -------
LibreNMS  | 7146d1780e480bc0ba896de9f1aec7ea627e841d
DB Schema | 182
PHP       | 7.0.16-3
MySQL     | 10.1.21-MariaDB-5+b1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
discovery: https://p.libren.ms/view/93f4a6c9
poller: https://p.libren.ms/view/9a6a2bd8
snmpwalk: https://p.libren.ms/view/b375265d

Interface Packets graphs suddenly stopped working today at 0h20 (UTC+1).

The only thing in the logs that seems ta have a link:
```
[ Thu, 23 Mar 2017 00:15:14 +0100 ] http://www.librenms.org/notifications.rss (12)
[ Thu, 23 Mar 2017 00:15:15 +0100 ] misc/notifications.rss (17)
[ Thu, 23 Mar 2017 00:15:15 +0100 ] Updating DB . Done
```
All my devices are affected (Switch, Debian Jessie, and Debian Stretch). Others graphs are still working.

![librenms_pkts](https://cloud.githubusercontent.com/assets/22664844/24249857/0f6f9d98-0fd5-11e7-97e8-f50bc42a155f.PNG)

**Comment by geordish** [comment]
Can you update your install, and let us know if that fixes your issues.

**Comment by fluboi** [comment]
Yes, it's fixed !
Thanks
