### ISSUE TITLE
Librenms old Poller 

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#6266]
Hi !

We have cloned our librenms machine and i have deleted all old devices with the delethost.php script !

But i see currently under poller still the old poller and in the mariadb database i see also the old poller.

If i want to delete the poller directly under mariadb  this doesn't work !

What is the best way to delete this old poller 

kind regards kristoferus75

**Comment by laf** [comment]
Github is for bugs, please use the community site or IRC. As per my response on IRC:

10:11 <@laf> kristoferus75: you can just delete the rogue entries from the db. If you mean you see them in /pollers/tab=pollers/ then delete them from pollers table
