### ISSUE TITLE
NetBotz Built in Sensor Support

### ISSUE THREAD

**Issue by difi80211g** [librenms/librenms#6269]
Currently Librenms supports the temperature, humity and ethernet state.  Can you add support for the other built in sensors (air flow, audio level, dew point, door status)?  Here are the OIDs i have discovered:

Dew Point (Celsius): .1.3.6.1.4.1.5528.100.4.1.3.1.7.2634294963
Audio Level: .1.3.6.1.4.1.5528.100.4.1.4.1.7.1092397166
Air Flow (meters/minute): .1.3.6.1.4.1.5528.100.4.1.5.1.7.1092459120
Door Status: .1.3.6.1.4.1.5528.100.4.2.2.1.7.18146194

Full OID sets can be found here:
http://pastebin.com/146633Fv

**Comment by laf** [comment]
You've removed the text that explains what we need to add further support for things.
