### ISSUE TITLE
Netbotz Additional Sensors

### ISSUE THREAD

**Issue by difi80211g** [librenms/librenms#6272]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

==========================================================
Component | Version
--------- | -------
LibreNMS  | af2930e0d953e8040ce2ebedd9673b633621e84b
DB Schema | 182
PHP       | 5.5.9-1ubuntu4.20
MySQL     | 5.5.53-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2
==========================================================

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Currently Librenms supports the temperature, humidity and ethernet state. Can you add support for the other built in sensors (air flow, audio level, dew point, door status)? Here are the OIDs i have discovered:

Dew Point (Celsius): .1.3.6.1.4.1.5528.100.4.1.3.1.7.2634294963
Audio Level: .1.3.6.1.4.1.5528.100.4.1.4.1.7.1092397166
Air Flow (meters/minute): .1.3.6.1.4.1.5528.100.4.1.5.1.7.1092459120
Door Status: .1.3.6.1.4.1.5528.100.4.2.2.1.7.18146194

Full OID sets can be found here:
http://pastebin.com/146633Fv

**Comment by laf** [comment]
You opened the same thing yesterday and didn't provide great required information then. Please read the messages when you create an issue and provide what is asked for.

**Comment by difi80211g** [comment]
I am not sure what else I am missing. I ran all the discovery and snmpbulkwalk commands it asked me too. Did it not get uploaded to your servers automatically like the documents says it does?

Greg

**Comment by laf** [comment]
Where the docs say it's uploaded automatically?

But no, you've not uploaded the debug or snmpwalk output.

**Comment by difi80211g** [comment]
On this document that is liked from the instructions:

http://docs.librenms.org/Support/FAQ/#faq20

In the section about running the snmpwalk commands it says

 "These commands will automatically upload the data to LibreNMS servers."

Sorry for the confusion.  Here is the output of the commands:

Discovery: http://pastebin.com/X3HaQP9u

Poller: http://pastebin.com/cyiZcX42

SNMPWALK: http://pastebin.com/A7k78xJq

Is this everything I need to submit to reopen the request?

**Comment by laf** [comment]
I've submitted a pull request for this. It doesn't include the audio sensor as I can't find what measurement this is in. It states unitless so I'm not sure what to do here.

**Comment by f0o** [comment]
Has been merged
