### ISSUE TITLE
No vpdn module for cisco 2921

### ISSUE THREAD

**Issue by LemonLight** [librenms/librenms#6287]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | a776ad5c8a73123822481ac9a246f998395dc4b4
DB Schema | 182
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 5.7.17-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3`

Hi everyone,

I would like to graph my ppp sessions via vpdn module, I saw that vpdn php file exists but I can't find it in poller/discovery module. Is it normal ? 

Thanks in advance for help !

**Comment by laf** [comment]
You can try and `$config['os']['OSNAME']['poller_modules']['cisco-vpdn'] = 1;` in config.php - Replace OSNAME with the actual os, i.e ios, iosxe. Then wait 15 minutes and see if you see the data.

**Comment by LemonLight** [comment]
Ok I am trying your solution, where should I see the result appear ?

**Comment by laf** [comment]
A vpdn tab in the device.

If you don't, please post the output of `./poller.php -h HOSTNAME -d -r -f -m cisco-vpdn` onto https://p.libren.ms

**Comment by LemonLight** [comment]
There is no vpdn tab :/

Here there is the output : https://p.libren.ms/view/4e4e061c

**Comment by laf** [comment]
Has it not appeared yet? If not, check if you have any vpdn-l2tp* files in the rrd folder for this device. If not please run `rrdtool create /opt/librenms/rrd/pe1-qct29.in.izzycom.net/vpdn-l2tp.rrd --step 300 DS:tunnels:GAUGE:600:0:U DS:sessions:GAUGE:600:0:U DS:denied:COUNTER:600:0:100000  RRA:AVERAGE:0.5:1:2016 RRA:AVERAGE:0.5:6:1440 RRA:AVERAGE:0.5:24:1440 RRA:AVERAGE:0.5:288:1440  RRA:MIN:0.5:1:720 RRA:MIN:0.5:6:1440     RRA:MIN:0.5:24:775     RRA:MIN:0.5:288:797  RRA:MAX:0.5:1:720 RRA:MAX:0.5:6:1440     RRA:MAX:0.5:24:775     RRA:MAX:0.5:288:797  RRA:LAST:0.5:1:1440`

**Comment by LemonLight** [comment]
I ran the command but after half an hour there is no vpdn tab yet
Here there is all the vpdn* file path on my server:
`/opt/librenms/html/includes/graphs/device/vpdn_sessions_l2tp.inc.php
/opt/librenms/html/includes/graphs/device/vpdn_tunnels_l2tp.inc.php
/opt/librenms/includes/polling/cisco-vpdn.inc.php`

**Comment by LemonLight** [comment]
And `/opt/librenms/rrd/pe1-qct29.in.izzycom.net/vpdn-l2tp.rrd` obviously

**Comment by geordish** [comment]
What user did you run as? Can you validate your install again?

If everything checks.out, and you still have no data, it might be worth running
```./poller.php -h HOSTNAME -d -f -m cisco-vpdn```
A
As the librenms user.

**Comment by LemonLight** [comment]
I ran as root but I didn't forget execute :
`chmod 664 /opt/librenms/rrd/pe1-qct29.in.izzycom.net/vpdn-l2tp.rrd`
`chown librenms:librenms /opt/librenms/rrd/pe1-qct29.in.izzycom.net/vpdn-l2tp.rrd`

Here the result : https://p.libren.ms/view/ee014b9e

**Comment by laf** [comment]
Can you provide the full output of `./poller.php -h HOSTNAME -d -r -f`

**Comment by LemonLight** [comment]
Sure! https://p.libren.ms/view/0d44a3c8

**Comment by laf** [comment]
Sorry also needs: `$config['poller_modules']['cisco-vpdn'] = 1;` in config.php then re-run that last command.

**Comment by LemonLight** [comment]
No problem : https://p.libren.ms/view/20ab6722

**Comment by LemonLight** [comment]
Oh wait, vpdn just appeared. Looks like `$config['poller_modules']['cisco-vpdn'] = 1;` in config.php has unlocked the situation ! 👍

**Comment by laf** [comment]
Ok, we'll need to fix this permanently.

**Comment by LemonLight** [comment]
I have one more question. Currently, the vpdn module graphs the number of active sessions.
My question is : Is it possible to graph a virtual interface which is generated when a ppp session is going up ? And if possible, identified by their ppp login.

**Comment by laf** [comment]
Possible but you need to create a feature request for this: https://community.librenms.org/c/feature-requests

**Comment by LemonLight** [comment]
Created :)
