### ISSUE TITLE
Transport Uptime Display

### ISSUE THREAD

**Issue by guoming218** [librenms/librenms#6292]
==========================================================
Component | Version
--------- | -------
LibreNMS  | 5d2aa3015396aaa7263236d9aab7046c4f4c8e82
DB Schema | 182
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

For the display of the uptime it is showing eg: Uptime: 2719392.

Can it change into Years, Months, Days, Hours and Mins instead?

Thank you.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
It actually already exists :(

uptime_short
uptime_long

In replacement for uptime

**Comment by laf** [comment]
And is in our docs: http://docs.librenms.org/Extensions/Alerting/#templates-syntax

**Comment by guoming218** [comment]
I am very sorry, i missed it
