### ISSUE TITLE
IPv6-only ESXi server

### ISSUE THREAD

**Issue by claushc** [librenms/librenms#6305]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

> LibreNMS  | acd11955d20737394c978aac3bf465d8e1d6a6b3
> DB Schema | 183
> PHP       | 5.5.9-1ubuntu4.21
> MySQL     | 5.5.54-0ubuntu0.14.04.1
> RRDTool   | 1.4.7
> SNMP      | NET-SNMP 5.7.2

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

[poller-esxi02.txt](https://github.com/librenms/librenms/files/881967/poller-esxi02.txt)

[discovery-esxi02.txt](https://github.com/librenms/librenms/files/881970/discovery-esxi02.txt)

[vmware-esxi02.snmpwalk.txt](https://github.com/librenms/librenms/files/881965/vmware-esxi02.snmpwalk.txt)

- [x] Please provide as much detail as possible.

This log message keeps repeating every five minutes for all my VMware ESXi servers:

>  Device IP changed to fdc3:991a:95c1::fa72:eaff:fef7:dc6

The servers was installed with IPv4 DHCP-assigned addresses, and the IPv6 address was added later.  Later again, the servers was removed from our static-only DHCP, now the DHCP-requests goes unanswered.  Around this time, the message started to show up.  DNS still holds both the old IPv4 address and the new IPv6.

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
Please test this patch: https://p.libren.ms/view/raw/b263c6a0

**Comment by claushc** [comment]
Hello laf,

I applied the patch some fifteen minutes ago, and the duplicate log messages have stopped as expected.

Thank you very much for your help :-)
