### ISSUE TITLE
API token not working

### ISSUE THREAD

**Issue by boudreau** [librenms/librenms#6307]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | acd11955d20737394c978aac3bf465d8e1d6a6b3
DB Schema | 183
PHP       | 7.0.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.5.6
SNMP      | NET-SNMP 5.7.2

The API token does not work:
curl  -H "X-Auth-Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" https://librenms/api/v0/oxidized
{
    "status": "error",
    "message": "API Token is missing or invalid; please supply a valid token"

when I checkout stable version 1.26 it works:

Component | Version
--------- | -------
LibreNMS  | 737865c94f9ac5f5874c71db7cbe91823601570d
DB Schema | 183
PHP       | 7.0.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.5.6
SNMP      | NET-SNMP 5.7.2

curl  -H "X-Auth-Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" https://librenms/api/v0/oxidized
######################################################################## 100.0%[
    {
        "hostname": "xxxxx.xxxxx.xxxx",
        "os": "ios",
        "group": "core"
    },
    {
        "hostname": "xxxx.xxxx.xxxx",
        "os": "ios",
        "group": "core"
    },

**Comment by sorano** [comment]
Works for me on that version.

**Comment by laf** [comment]
Also works for me, I'd suggest posting for help on the community forums or irc.

**Comment by boudreau** [comment]
Look when I apply the PR 1ea7af424babd6f79819972726a304c1f320e80a I can't get my API token to work. It works fine before that one. This feature: bind user for active_directory auth #6255 
breaks my API token, I'm using AD also for authentication. Any possibilities that this influences API tokens?

**Comment by sorano** [comment]
>  I'm using AD also for authentication.  Any possibilities that this influences API tokens?

Yes.

Have you tried creating new API tokens for your users after that PR?

**Comment by boudreau** [comment]
I tried deleting old one, creating new one, disabling  re-enabling. It only work at PR 5d2aa3015396aaa7263236d9aab7046c4f4c8e82
I checkout this PR 5d2aa3015396aaa7263236d9aab7046c4f4c8e82 my tokens work, and I checkout 1ea7af424babd6f79819972726a304c1f320e80a I then get Token is missing or invalid from the same command that was working a minute ago.

**Comment by laf** [comment]
It would really help in future if you provide noteworthy info like that.

I'm assuming the reason is you don't have a bind user setup as per the updated docs:

`It is highly suggested to create a bind user, other wise "remember me", alerting AD users, and the API will not work.`

The issue is that get_user now exists for AD auth so this now fails. Have you tried using (can you?) a bind account.

**Comment by boudreau** [comment]
It says that for the LDAP, is it valid for the AD also?

There is one this I noticed, when I create a new token, it get added to the DB, but it's not listed in the list of token. If I checkout the earlier version and go back it pop back in the list.

I'll look at the possibilities of the bind account if it's possible with AD.

Thanks

**Comment by laf** [comment]
I'm guessing the docs were updated in the wrong place as that commit was for AD.

@murrant?

**Comment by boudreau** [comment]
Hi,
got the bind user working. And it did solve the API problem. 

Thanks guys.

**Comment by murrant** [comment]
Yes you need a bind user, otherwise some things will not work.

**Comment by laf** [comment]
@murrant is the docs for the bind in the wrong place? Shows up under ldap at present.

**Comment by murrant** [comment]
Yep :-(  I was thinking about sending a notification too.

**Comment by Nahatakyan** [comment]
try this
