### ISSUE TITLE
Cisco ASA Odd Discovery 

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#631]
The following shows up in the event log each time all 5515 i have get's discovered, lafwood reports that the same happens on 5512.

http://snag.gy/uvmjv.jpg

**Comment by laf** [comment]
This is due to the entPhySensorScale scale being yocto which we don't covert: http://tools.cisco.com/Support/SNMP/do/BrowseMIB.do?local=en&step=2&mibName=CISCO-FLOW-MONITOR-TC-MIB

We are missing quite a few by the looks of it. I'll add yocto in for now and come back to the others.

**Comment by laf** [comment]
Fix has been submitted in PR #632.

I'd like to keep this issue open though as a reminder to come back and fix the sensor detection at some stage.

**Comment by f0o** [comment]
Merged #632
