### ISSUE TITLE
Discovery Cisco ATM interfaces : empty graph

### ISSUE THREAD

**Issue by thoms27** [librenms/librenms#6311]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================
Component | Version
--------- | -------
LibreNMS  | a6391ed3e8ff0155c9cf78e3efb0c878e08b875e
DB Schema | 183
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================
` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hello,

I activated the discovery of ATM interfaces in commenting out 
$config['bad_if'][] = '-atm';
$config['bad_iftype'][] = 'atmSubInterface';

After rediscovery, the interfaces appear but my graph are toujours empty. The message is "Cannot get data about interface"

Can you help me please ?

Thank you in advance.

Regards,

Thomas V.

**Comment by thoms27** [comment]
Hi,

It's me again ;-)

To complete information, for example, the ifindex value (263) for an ATM subinterface (ATM0/1/0.189-atm subif), the message when I do an realtime is "Cannot get data about interface 263".

root@librenms:/opt/librenms# tcpdump -n -i enp0s3 host x.x.x.x
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on enp0s3, link-type EN10MB (Ethernet), capture size 262144 bytes
10:46:37.007088 IP 10.0.2.15.37142 > 172.20.69.5.161:  C="HOSTING-FLW" GetRequest(32)  .1.3.6.1.2.1.31.1.1.1.6.263
10:46:37.012878 IP 172.20.69.5.161 > 10.0.2.15.37142:  C="HOSTING-FLW" GetResponse(32)  .1.3.6.1.2.1.31.1.1.1.6.263=[noSuchInstance]

Have you got an idea ?

Thanks in advance

**Comment by laf** [comment]
You haven't provided the information asked for above.

Also, you've already got this question open on the community site, you need to be patient for responses.

**Comment by thoms27** [comment]
Hi,

Sorry :-s
