### ISSUE TITLE
error message in discovery don't alway show host and type

### ISSUE THREAD

**Issue by cahluor** [librenms/librenms#6312]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

$ ./validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | 8f0f1ba8b9b0a6f09efeec3a6c980f6a5962870e
DB Schema | 183
PHP       | 5.6.30-0+deb8u1
MySQL     | 10.0.29-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

[OK]    Database connection successful

When doing discovery we have some failure messages in the event log. Theses messages usually give the hostname of the host against which discovery is runned, and the type "discovery"

For instance this message :

2017-03-31 13:13:28	d1b1f6-swcl-245	discovery	LLDP discovery of D1-PVT-EQ01 failed - Check name lookup

in some case, mostly with ARP discovery, hostname and type are 'null' where I think we should have the hostname of the network equipement and type 'discovery'. For instance :

2017-03-31 13:13:28	d1b1f6-swcl-245	discovery	LLDP discovery of D1-PVT-EQ01 failed - Check name lookup

I found that in includes/discovery/functions.inc.php, the function discover_new_device calls log_event with the parameters $device['device_id']  and 'discovery'  except on line 83 where it's called with 'null', 'null' 

here :

catch (Exception $e) {
   log_event("$method discovery of " . $hostname . " ($ip) failed - " . $e->getMessage(), null, null, 5);
}

Is there a reason not to change it to :

catch (Exception $e) {
   log_event("$method discovery of " . $hostname . " ($ip) failed - " . $e->getMessage(), $device['device_id'], 'discovery', 5);
}

??

**Comment by laf** [comment]
Changing to null, 'discovery' yes but we don't have a device (it failed to add at this point).

Are you going to submit an update to this?

Please note that github is for bug reports.

**Comment by cahluor** [comment]
At this point we don't have the new device in $remote_device that right, but in the others cases, like in line 73 where the device can't be added because snmp doesn't connect it's $device which is sent in the "host" parametter.
That is not the new device discovered, but the device from which it is seen, like in arp or lldp discovery.

I report it on github because in the same discovery process some errors messages indicate a device while other messages don't so for me it looks like a bug

**Comment by laf** [comment]
Are you submitting a fix for this?

**Comment by cahluor** [comment]
Yup I can submit a fix as soon as I have a little time.
Never done it so I'll just have to read how it should be done.

**Comment by cahluor** [comment]
pull request 6452 submitted
