### ISSUE TITLE
Device groups / geo locations in menu scrolls, but can't mouseover on the scrollbar

### ISSUE THREAD

**Issue by deepseth** [librenms/librenms#6313]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
`Component | Version
--------- | -------
LibreNMS  | 90be6d1f686abda81b1469cbf63d52110d960e1b
DB Schema | 183
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
`
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

In the drop down menus at the top of the screen, under the Devices menu are sections "Device Groups" and "Geo Locations". With >8 items in either section, the overlay has a scrollbar. While the overlay can be scrolled using a mouse wheel or multitouch touchpad, trying to move the mouse pointer onto the scrollbar results in the whole overlay disappearing.

This is occurring in Windows 10 using Google Chrome Version 56.0.2924.87 (64-bit)

**Comment by deepseth** [comment]
This doesn't occur in Edge version 38.14393.0.0

**Comment by BradHooper** [comment]
I have the same issue using Chromium 56.0.2924.76 on Ubuntu

**Comment by laf** [comment]
Looks like this works as expected in Chrome 57.x

**Comment by deepseth** [comment]
Confirmed, I guess it was a Chrome bug. Cheers!
