### ISSUE TITLE
Device event log doesn't page, limited to 250 entries

### ISSUE THREAD

**Issue by deepseth** [librenms/librenms#6314]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
`Component | Version
--------- | -------
LibreNMS  | 90be6d1f686abda81b1469cbf63d52110d960e1b
DB Schema | 183
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
`
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

In the Logs tab of a device, only the last 250 entries are shown. While there's a search box at the top, this doesn't help if I'm looking for any events occurring at a particular time, rather than a specific type of event.

Enabling paging on this, or allowing to search based on time, would be useful!

**Comment by laf** [comment]
Github issues are for bugs not features, please post this request on here: https://community.librenms.org/c/feature-requests
