### ISSUE TITLE
Version in /about is dated on 0sec UNIX time (1970)

### ISSUE THREAD

**Issue by genabi** [librenms/librenms#6318]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

validate.php:
Component | Version
--------- | -------
LibreNMS  | a0abcbb6496def0bacc77fb811064c314c6d087e
DB Schema | 184
PHP       | 5.6.30
MySQL     | 5.6.35-log
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

Hi,

I've tried to find a solution to this small problem, however my PHP knowledge is too poor: 

There's following code in html/pages/about.inc.php:
`$version_date    = $versions['local_date'];`
I can see that local_date is defined in includes/common.php:
`list($local_sha, $local_date) = explode('|', rtrim(`git show --pretty='%H|%ct' -s HEAD`));`
This command ran on my systems shows proper epoch date:
`$ git show --pretty='%H|%ct' -s HEAD`
`a0abcbb6496def0bacc77fb811064c314c6d087e|1491081724`
However on /about page i can see:
`Version	a0abcbb64 - Thu Jan 01 1970 01:00:00 GMT+0100`

**Comment by laf** [comment]
Please post the full output from validate

**Comment by genabi** [comment]
2 systems with similar problem:
FreeBSD 10.3-RELEASE-p17
FreeBSD 11.0-STABLE r314290M
Completely different setups, different locations, both with nginx, php-fpm, oracle-mysql


`==========================================================
Component | Version
--------- | -------
LibreNMS  | a0abcbb6496def0bacc77fb811064c314c6d087e
DB Schema | 184
PHP       | 5.6.30
MySQL     | 5.6.35-log
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================

[OK]    Database connection successful
[WARN]  openssl_random_pseudo_bytes is not being used for user password hashing. This is a recommended function (https://secure.php.net/openssl_random_pseudo_bytes)
[FAIL]  Discovery has not completed in the last 24 hours, check the cron job`




Another installation, where the same problem occurs:
(yes, I have tried bot fixes, didn't have time to repair sql issues, this is a lab install)
`==========================================================
Component | Version
--------- | -------
LibreNMS  | a0abcbb6496def0bacc77fb811064c314c6d087e
DB Schema | 184
PHP       | 5.6.30
MySQL     | 5.6.30
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================

[OK]    Database connection successful
[FAIL]  MySQL tables collation is wrong:  [FIX] http://bit.ly/2lAG9H8
	 bill_port_counters_tmp latin1 latin1_swedish_ci
[FAIL]  MySQL column collation is wrong:  [FIX] https://t.libren.ms/-zdwk
	 authlog user utf8 utf8_general_ci
	 authlog address utf8 utf8_general_ci
	 authlog result utf8 utf8_general_ci
	 eventlog message latin1 latin1_swedish_ci
	 eventlog type latin1 latin1_swedish_ci
	 eventlog reference latin1 latin1_swedish_ci
	 perf_times type latin1 latin1_swedish_ci
	 perf_times doing latin1 latin1_swedish_ci
	 pollers poller_name utf8 utf8_bin
	 port_association_mode name latin1 latin1_swedish_ci
	  and 119 more...
[FAIL]  The poller has not run in the last 5 minutes, check the cron job
[WARN]  Some devices have not been polled in the last 5 minutes.
        You may have performance issues. Check your poll log and see: http://docs.librenms.org/Support/Performance/
	 host-a
	 host-b
	 ubiquiti-uap`

**Comment by genabi** [comment]
FreeBSD 11.0-STABLE r314290M, nginx, php-fpm, oracle-mysql

(it just says this about discovery - everything works fine)
==========================================================
Component | Version
--------- | -------
LibreNMS  | a0abcbb6496def0bacc77fb811064c314c6d087e
DB Schema | 184
PHP       | 5.6.30
MySQL     | 5.6.35-log
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================

[OK]    Database connection successful
[WARN]  openssl_random_pseudo_bytes is not being used for user password hashing. This is a recommended function (https://secure.php.net/openssl_random_pseudo_bytes)
[FAIL]  Discovery has not completed in the last 24 hours, check the cron job

**Comment by genabi** [comment]
FreeBSD 10.3-RELEASE-p17, nginx, php-fpm, oracle-mysql (completely different setup, different dc, etc) 

yes, I have tried bot fixes, didn't have time to repair sql issues, this is a lab install

Component | Version
--------- | -------
LibreNMS  | a0abcbb6496def0bacc77fb811064c314c6d087e
DB Schema | 184
PHP       | 5.6.30
MySQL     | 5.6.30
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

[OK]    Database connection successful
[FAIL]  MySQL tables collation is wrong:  [FIX] http://bit.ly/2lAG9H8
         bill_port_counters_tmp latin1 latin1_swedish_ci
[FAIL]  MySQL column collation is wrong:  [FIX] https://t.libren.ms/-zdwk
         authlog user utf8 utf8_general_ci
         authlog address utf8 utf8_general_ci
         authlog result utf8 utf8_general_ci
         eventlog message latin1 latin1_swedish_ci
         eventlog type latin1 latin1_swedish_ci
         eventlog reference latin1 latin1_swedish_ci
         perf_times type latin1 latin1_swedish_ci
         perf_times doing latin1 latin1_swedish_ci
         pollers poller_name utf8 utf8_bin
         port_association_mode name latin1 latin1_swedish_ci
          and 119 more...
[FAIL]  The poller has not run in the last 5 minutes, check the cron job
[WARN]  Some devices have not been polled in the last 5 minutes.
        You may have performance issues. Check your poll log and see: http://docs.librenms.org/Support/Performance/
         host-a
         host-b
         ubiquiti-uap
