### ISSUE TITLE
Feature request: HTML code dashboard widget

### ISSUE THREAD

**Issue by genabi** [librenms/librenms#6319]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

validate.php:
Component | Version
--------- | -------
LibreNMS  | a0abcbb6496def0bacc77fb811064c314c6d087e
DB Schema | 184
PHP       | 5.6.30
MySQL     | 5.6.35-log
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

Hi,
I find one thing missing from LibreNMS: ability to add own html code to the dashboard. It would be great if it'd be possible to create a widget with <iframe> to put your own html code into. 

For example: If I use 'external image' widget I can put weathermap's png file on my dashboard.  However [network-weathermap ](https://network-weathermap.com/) generates some nice and interactive html files that would be more suited for the dashboard (multiple <a> to different devices/ports, etc).

Hope that the idea isn't dumb and might be useful for others. 

Thanks,
G.

**Comment by laf** [comment]
GitHub is for bugs. Please read above for feature requests
