### ISSUE TITLE
New Device Support -  Eltex LTP-8X

### ISSUE THREAD

**Issue by dragans** [librenms/librenms#6321]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 737865c94f9ac5f5874c71db7cbe91823601570d
DB Schema | 182
PHP       | 7.0.11
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

Discovery
https://gist.github.com/dragans/f3eb5dbaf2a1b406765e2a9d9f05f5ec

Poller
https://gist.github.com/dragans/8dd170cbc080a7c56f175ada0564fd27

SNMP
https://gist.github.com/dragans/942edd1d623bf6de5c03b9bb551f9b19

Device: Eltex LTP-8X
Device webpage: (http://eltex.nsk.ru/en/catalog/ltp-8x.php)
Device datasheet: (http://eltex.nsk.ru/upload/iblock/e77/ltp_gpon_datasheet_en_2.14.0.1036.pdf)
Device MIBS: [eltex-ltp8x.zip](https://github.com/librenms/librenms/files/890502/eltex-ltp8x.zip)

Device is recognized as SERVER, and there are no CPU and RAM usage readings.
Also, interface bandwidth usage is currently read incorrectly.

**Comment by laf** [comment]
I've submitted a PR to add support.

Please note though that I can't see RAM info anywhere. I've assumed the values from ltp8xCPULoadAverage5Minutes needed to be divided by 10 as the test data showed ~240!

What's up with interface data?

**Comment by dragans** [comment]
Sorry, should have explained better about ports.

Ethernet ports seem to be monitored OK, but PON interfaces return insane values (like inbound rate in petabits per second :D ).

I also tried to find some value that would represent RAM usage, but no luck.

I examined the vendor's MIB files again and saw that the definitions were last updated in 2010 and 2012. I guess that the vendor still has a lot of work to do on support for these devices.

**Comment by laf** [comment]
If you are getting bad data on ports then this is just standard IF-MIB so you need to raise this to the vendor.

**Comment by dragans** [comment]
OK, thanks for clarification. Will contact the vendor regarding snmp quirks. On Apr 19, 2017 13:45, Neil Lathwood <notifications@github.com> wrote:If you are getting bad data on ports then this is just standard IF-MIB so you need to raise this to the vendor.
