### ISSUE TITLE
New Device Support- Ciena Switch 3942

### ISSUE THREAD

**Issue by vladutz33** [librenms/librenms#6322]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | a0abcbb6496def0bacc77fb811064c314c6d087e
DB Schema | 184
PHP       | 5.5.9-1ubuntu4.21
MySQL     | 5.5.54-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

Device: Ciena Switch 3942
Product Homepage: http://www.ciena.com/products/3942/
Product MIBs: https://app.box.com/s/r54knwfu089e945t626yl5onwq1rzomp
Product Datasheet: http://media.ciena.com/documents/3942_Service_Delivery_Switch_DS.pdf
Discovery:
https://app.box.com/s/21rrbg5uz3i232fmojesru7n2nuzov9e

Poller:
https://app.box.com/s/hpmstc41bogg56wmixej4i98rdpfddks
SNMP:
https://app.box.com/s/edsv69w169yth5jpb9kidactimxujimy

**Comment by laf** [comment]
I've submitted a pull request to add detection. The mibs link don't actually contain any mibs so we've not been able to use these or add any further info to be picked up.

**Comment by vladutz33** [comment]
Uploaded the latest mibs

**Comment by laf** [comment]
Looks like the snmpwalk doesn't contain any data from ` .1.3.6.1.4.1.1271.2.1.2.1.2.3`, please re-run it using that OID instead of `.`

**Comment by vladutz33** [comment]
I ran it without the dot , here is the output:
https://app.box.com/s/r7dt6kyvtktj8prpq21ww1oslkdb71rx

**Comment by laf** [comment]
I'm not sure what command you ran but that doesn't contain info from 1.3.6.1.4.1.1271.2.1.2.1.2.3, if the device doesn't respond with any data then the mibs are of no use.

please use a normal pastebin service, app.box.com is annoying to download from.

**Comment by esorin0** [comment]
This is what I get when querying that OID:  
iso.3.6.1.4.1.1271.2.1.2.1.2.3 = No Such Object available on this agent at this OID

**Comment by laf** [comment]
When someone can provide us with valid data or what the current oids mean then this issue is closed, we can re-open when further info is provided.
