### ISSUE TITLE
New Device Support - C&C Power Commander

### ISSUE THREAD

**Issue by vladutz33** [librenms/librenms#6323]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | a0abcbb6496def0bacc77fb811064c314c6d087e
DB Schema | 184
PHP       | 5.5.9-1ubuntu4.21
MySQL     | 5.5.54-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

Device: C&C Power Commander Plus
Device Homepage:http://www.ccpower.com/products/commander-plus/
Device MIBs: https://app.box.com/s/ywnktre1ni6poyi8a8guy68cl5rjod06

SNMP:
https://app.box.com/s/n9auob7j4apdiveq2lzj05jub5iudisb
Discovery:
https://app.box.com/s/95r379or5noozrf739yvq4kevmnz2mih
Poller:
https://app.box.com/s/kf50i0by5gnii5utbf9vtcv2mt20g7oh

**Comment by laf** [comment]
All the links are 404, please provide the relevant info we need and we will re-open this.

**Comment by vladutz33** [comment]
Updated links

**Comment by laf** [comment]
I know you've only just uploaded these files (along with the others) but can you please use a pastebin service, this app.box.com is a pain to get the data out via the cli

**Comment by esorin0** [comment]
I do not see the 2 most important parameters for this device: rectifier float voltage and rectifier load current.

**Comment by laf** [comment]
We aren't mind readers, I added the obvious things I could see. I will try and add further support

**Comment by esorin0** [comment]
Yeah, there are only 4-5 numerical parameters this thing puts out. The rest is just configuration. Thank you for your help!

**Comment by laf** [comment]
Please test https://github.com/librenms/librenms/pull/6517

**Comment by esorin0** [comment]
I see the new parameters added, it's just the rectifier voltage needs to be divided by 10. Thanks!
