### ISSUE TITLE
New Device Support - PacketFlux SiteMonitor Base Unit II

### ISSUE THREAD

**Issue by vladutz33** [librenms/librenms#6324]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
Component | Version
--------- | -------
LibreNMS  | a0abcbb6496def0bacc77fb811064c314c6d087e
DB Schema | 184
PHP       | 5.5.9-1ubuntu4.21
MySQL     | 5.5.54-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

Device:PacketFlux SiteMonitor Base Unit II
Device Homepage: http://store.packetflux.com/sitemonitor-base-unit-ii/

MIB:
https://app.box.com/s/vo5syl74hmb3n80k1jww8t7a38xlwbl4

Discovery:
https://app.box.com/s/j10nvizqwqucmpewee3tfuurp0ssubum

Poller:
https://app.box.com/s/ue0mj0ed8sx1wlxu1sfwuk2vbc1fo5ax
SNMP:
https://app.box.com/s/ljyq7rkzpxnadhwvzoqyulot41wuk38d

**Comment by barryodonovan** [comment]
Is anyone looking at implementing this?

**Comment by laf** [comment]
You're more than welcome to pick it up if you like?

**Comment by laf** [comment]
All links are 404, please provide the information needed and we will re-open.

**Comment by vladutz33** [comment]
Updated Links

**Comment by laf** [comment]
I'm submitting base detection, the mibs though have data in  .1.3.6.1.4.1.32050.2.2 which the snmpwalk doesn't. If you can re-run the snmpwalk with `.1.3.6.1.4.1.32050.2.2` to see if we can get any more info in.

**Comment by vladutz33** [comment]
I ran the command it gave me this: 
 snmpwalk -v2c -c public 10.5.0.20 .1.3.6.1.4.1.32050.2.2
iso.3.6.1.4.1.32050.2.1.1.0 = IpAddress: 10.5.0.20
Error: OID not increasing: iso.3.6.1.4.1.32050.2.2
 >= iso.3.6.1.4.1.32050.2.1.1.0

**Comment by laf** [comment]
Ok, well we don't have any further info to detect then :(

**Comment by esorin0** [comment]
The manufacturer does not provide a MIB for this product and they have no plans in doing it. A list of OIDs is available and that's how was implemented in Observium (they wrote some sort of a MIB file in php).

**Comment by laf** [comment]
We can't look at Observium.

If someone can tell me what the OIDs represent we can add support.

**Comment by esorin0** [comment]
From the walk ( https://pastebin.com/UnQKAYia or previous posted files) the only interesting values for anyone are the standard ones and the analog:
iso.3.6.1.2.1.1.1.0 = STRING: "PacketFlux SiteMonitor Base II"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.32050
iso.3.6.1.2.1.1.3.0 = Timeticks: (2706311060) 313 days, 5:31:50.60
iso.3.6.1.2.1.1.4.0 = STRING: "masked"
iso.3.6.1.2.1.1.5.0 = STRING: "masked"
iso.3.6.1.2.1.1.6.0 = STRING: "masked"
iso.3.6.1.2.1.1.7.0 = INTEGER: 7

iso.3.6.1.4.1.32050.2.1.27.2.0 = STRING: "Temperature (0.1C)"
iso.3.6.1.4.1.32050.2.1.27.2.1 = STRING: "Shunt Input (0.1mV)"
iso.3.6.1.4.1.32050.2.1.27.2.2 = STRING: "Power 1 In (0.1V)"
iso.3.6.1.4.1.32050.2.1.27.2.3 = STRING: "Power 2 In (0.1V)"
iso.3.6.1.4.1.32050.2.1.27.2.4 = STRING: "Exp Current (mA)"
iso.3.6.1.4.1.32050.2.1.27.2.5 = STRING: "Relay on Above (0.1C)"
iso.3.6.1.4.1.32050.2.1.27.2.6 = STRING: "Relay on Below (0.1C)"

Please be aware that (0.1) means that those values are multiplied by 10 in output, so they need to be divided by 10 to get the correct value. Thank you!

**Comment by laf** [comment]
PR has been updated now.

**Comment by esorin0** [comment]
Looks great! Thanks!
