### ISSUE TITLE
New Device Support - Tycoon Systems- TPDIN2

### ISSUE THREAD

**Issue by vladutz33** [librenms/librenms#6325]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
Component | Version
--------- | -------
LibreNMS  | a0abcbb6496def0bacc77fb811064c314c6d087e
DB Schema | 184
PHP       | 5.5.9-1ubuntu4.21
MySQL     | 5.5.54-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

Device:TPDIN™ Remote Monitor 
Device Homepage: http://tyconsystems.com/index.php/products/tycon-power/tpdin-monitor-web/751-tpdin-monitor-web2

Device MIB:
http://tyconsystems.com/Assets/TPDIN%20Firmware/TPDIN2-MIB.txt

SNMP:
https://app.box.com/s/6i0nmcufkf48quhmlojbyshximmfwoku

Discovery:
https://app.box.com/s/k1e6r89zt1kndee9vb8i0x85d03yploc

Poller:
https://app.box.com/s/os50t90a4mvj6hvidy7o4da28lv4u2fk

**Comment by laf** [comment]
All links are 404, please provide the information required and we can re-open.

**Comment by vladutz33** [comment]
Updated Links

**Comment by esorin0** [comment]
Looks good. Thanks!
