### ISSUE TITLE
New Device Support - Exalt ExtendAir G2

### ISSUE THREAD

**Issue by vladutz33** [librenms/librenms#6327]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
Component | Version
--------- | -------
LibreNMS  | a0abcbb6496def0bacc77fb811064c314c6d087e
DB Schema | 184
PHP       | 5.5.9-1ubuntu4.21
MySQL     | 5.5.54-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

Device: Exalt ExtendAir G2
Device Homepage: http://www.exaltcom.com/ExtendAir-G2.aspx

Device MIB:
https://app.box.com/s/tsn6841d14wm11tclopa809yeruqdoeh

SNMP:
https://app.box.com/s/fvewfdmb6s1upeo7gc2mvvut7urcnpza

Discovery:
https://app.box.com/s/tvvo68ofh62xy5ubaqd1pul7ste9r3wh

Poller:
https://app.box.com/s/rkkzu8etde7nynflayj77bcjzx5on827

**Comment by laf** [comment]
All links are 404, please provide the information we need and we can re-open.

**Comment by vladutz33** [comment]
Updated Links

**Comment by laf** [comment]
Pull request in, please test and let us know if you can see more sensors that need discovering.

**Comment by esorin0** [comment]
It would be great if you can add Received Signal Level (Internal and Far End Radio), Link Status (Internal) and Temperature (Internal). 'Internal' is referring to device that is queried while 'Far End Radio' is the radio on the other side.
Here is an example: http://pasteboard.co/41a9CCrb.png
Should I ask for adding a feature?

Thank you!

**Comment by laf** [comment]
Please test https://github.com/librenms/librenms/pull/6531

It doesn't contain signal level. We have a new PR in for wireless sensors where this may be more appropriate so I'm going to test it in that.

**Comment by laf** [comment]
Yes I think the new wireless section fits better, I've done the code for that and it seems to work ok.

**Comment by esorin0** [comment]
I have updated the code and forced a discovery. I don't see anything changed. Should I delete and recreate device?

**Comment by laf** [comment]
A rediscovery is all that's needed.

Post the output of `./discovery.php -h HOSTNAME -d -m sensors`

**Comment by laf** [comment]
The wireless sensor PR in the queue adds:

Error Ratio | Rate | Signal | Power | Frequency

Support.

**Comment by esorin0** [comment]
https://pastebin.com/N8B2MPsD

**Comment by laf** [comment]
Looks like you aren't running the code, how are you testing it?

**Comment by esorin0** [comment]
I have updated the code and ran the command. I am not sure what else I
should do to run the code.

**Comment by laf** [comment]
How are you updating the code?

**Comment by esorin0** [comment]
I manually run daily.sh as librenms user.

**Comment by laf** [comment]
It's not been merged yet, the pull request I linked to has details on how to test.

**Comment by laf** [comment]
Should all be good now.
