### ISSUE TITLE
New Device Support - Alvarion BreezeAccess VL

### ISSUE THREAD

**Issue by vladutz33** [librenms/librenms#6328]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

LibreNMS  | a0abcbb6496def0bacc77fb811064c314c6d087e
DB Schema | 184
PHP       | 5.5.9-1ubuntu4.21
MySQL     | 5.5.54-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

Device: Alvarion BreezeaAccess VL
Device Homepage: http://www.alvarion.com/breezeaccess/breezeaccess-vl/

Device MIBs: 
https://app.box.com/s/1muz3f5xtbd3m2w67vvct8yl8jw21rt3

SNMP:
https://app.box.com/s/3ur06qtwhntea1znrow2rirrhvivjx2w

Discovery:
https://app.box.com/s/djrercpzx4niilt1fq2f1stxcfa3ixoq

Poller:
https://app.box.com/s/bk3amfdtngcuy2glsemqne77e367bc2r

**Comment by laf** [comment]
All links 404, please provide the information we need and we can re-open.

**Comment by vladutz33** [comment]
Updated Links

**Comment by esorin0** [comment]
New links:
Discovery: https://p.libren.ms/view/145eb03d
Poller: https://p.libren.ms/view/f1c4a61f  (this one dumps a lot of messages like this  Error in packet /Reason: (noSuchName) There is no such variable name in this MIB.)
SNMP: https://p.libren.ms/view/f1447fdd
I have confirmed data in pastebin is valid, when I wrote this comment.

What would be nice to add is the list of wireless clients connected (names) along with their SNR, as you can see here: http://pasteboard.co/w84Ojq4w.png
Thank you!

**Comment by esorin0** [comment]
There is a note I would make here: these devices have 2 modes: AU (access point) and SU (station, subscriber, radio client). In AP mode it reports all the SU connected, along with their data (SNR etc). In SU mode, it reports just the Average SNR, as you can see here: http://pasteboard.co/wrewctFX.png

I'm also adding the data for a SU device, just in case it is needed:
Discovery: https://p.libren.ms/view/57f85597
Poller: https://p.libren.ms/view/03ee6c6e
SNMP: https://p.libren.ms/view/e4f0ca7d
I have confirmed data in pastebin is valid, when I wrote this comment.
I am not sure if a different implementation is required for AU and SU, that's why I provided info for both. 
Thank you!

**Comment by laf** [comment]
I'm not being funny but you really should have provided this information at the start.

You'll need to post these extra requirements as feature requests now https://community.librenms.org/c/feature-requests

**Comment by esorin0** [comment]
For some reason, all the pastebin links I posted are gone. This is not the first time it is happening to me. I will provide new links in the feature requests.
