### ISSUE TITLE
New Device Support - Eltek SmarPack S

### ISSUE THREAD

**Issue by vladutz33** [librenms/librenms#6330]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | a0abcbb6496def0bacc77fb811064c314c6d087e
DB Schema | 184
PHP       | 5.5.9-1ubuntu4.21
MySQL     | 5.5.54-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

Device: Eltek SmartPack S
Device Datasheet: http://www.eltek.com/download_doc.epl?id=8013&cust=647

Device MIBs:
https://app.box.com/s/wl8yhlazrzzs9mw4a68hv1nk8a3ml4jm

SNMP:
https://app.box.com/s/rdl8wak3zb5gb7z9gt0kb4m0f2sv0kcl

Discovery:
https://app.box.com/s/lcvc61x5is6g7393z6c79fn4ur17re2x

Poller:
https://app.box.com/s/54ua9xv62hse1qu4taoj5rcwk4vitlxi

**Comment by laf** [comment]
All links 404, please provide the info required and we can re-open.

**Comment by vladutz33** [comment]
Updated links

**Comment by bandziorw** [comment]
where is the issue ? # on youregit chechout list ?

**Comment by bandziorw** [comment]
./validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | 6c6499c2fe335e34a11e4f231c9cd5d054d48288
DB Schema | 186
PHP       | 5.6.30-0+deb8u1
MySQL     | 10.0.30-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

[FAIL]  We have found some files that are owned by a different user than librenms, this will stop you updating automatically and / or rrd files being updated causing graphs to fail.
        [FIX] chown -R librenms:librenms /opt/librenms
         /opt/librenms/rrd/localhost
         /opt/librenms/rrd/localhost/ospf-statistics.rrd
         /opt/librenms/rrd/localhost/ucd_diskio-vda2.rrd
         /opt/librenms/rrd/localhost/ucd_diskio-vda1.rrd
         /opt/librenms/rrd/localhost/hr_users.rrd
         /opt/librenms/rrd/localhost/poller-perf-cisco-cef.rrd
         /opt/librenms/rrd/localhost/ucd_load.rrd
         /opt/librenms/rrd/localhost/poller-perf-cisco-voice.rrd
         /opt/librenms/rrd/localhost/ucd_ssCpuRawNice.rrd
         /opt/librenms/rrd/localhost/storage-hrstorage-_.rrd
          and 392 more...
[OK]    Database connection successful
[FAIL]  Database: incorrect column (dbSchema/version)
[FAIL]  Database: missing index (dbSchema/PRIMARY)
[FAIL]  Database: missing column (users/remember_token)
[FAIL]  Database: incorrect column (users/updated_at)
[FAIL]  We have detected that your database schema may be wrong, please report the following to us on IRC or the community site (https://t.libren.ms/5gscd):
         ALTER TABLE `dbSchema` CHANGE `version` `version` int(11) NOT NULL DEFAULT '0';
         ALTER TABLE `dbSchema` ADD PRIMARY KEY (`version`);
         ALTER TABLE `users` ADD `remember_token` varchar(100) NULL AFTER `realname`;
         ALTER TABLE `users` CHANGE `updated_at` `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
[FAIL]  fping should be suid! [FIX] chmod u+s /usr/bin/fping
[FAIL]  fping6 should be suid! [FIX] chmod u+s /usr/bin/fping6

**Comment by laf** [comment]
The snmpwalk doesn't contain any data from .1.3.6.1.2.1.1. which includes sysDescr and sysObjectId for us to add in. Poller and debug doesn't have any data either as I expect you've not run them actually against a device.

Feel free to provide further info and we can re-open.

**Comment by esorin0** [comment]
New links.
Discovery: https://p.libren.ms/view/f1bed02b
Poller: https://p.libren.ms/view/7ca2866f
SNMP: https://p.libren.ms/view/fbf7de10

I have confirmed there are valid data, as reported by your scripts. I do not see any data for .1.3.6.1.2.1.1., as this device seems to report that specific info with different OIDs.
What would be interesting to see is: BatteryVoltage, MainsVolt 1, BatteryCurrent, Power, LoadCurrent, BatteryTemp, TotRectCurrent, BatteryRemCap and the eventual alarms that device might report (we don't have any device in alarm right now, so I cannot provide that kind of output).

Thank you!

**Comment by laf** [comment]
If the device doesn't provide any data for sysObjectId or sysDescr then we can't add support for it.

**Comment by esorin0** [comment]
Fair enough. Thank you!

**Comment by Uleoja** [comment]
I am also interested in getting the smartpack S working.   What would I need to ask Eltek about getting something like this working?  I assume it would be a firmware update that would enable the correct sysObjectId?

**Comment by laf** [comment]
Provide the info in point # 3 above and we can see.

**Comment by Simonk007** [comment]
If u want i can got a direct contact to ELTEK. 
We about 400 ELTEK SP2 i would like to monitor. But Librenms dosn't support. What would i need to make this work..

If u can help me with some info on whats needed, i will contact ELTEK

**Comment by laf** [comment]
The vendor hasn't implemented basic snmp info, sysObjectID and sysDescr are the two are mainly interested in but they should also provide a lot more.
