### ISSUE TITLE
Cisco 3650 NX-OS spiky graphs since ./daily.sh update  on 2017-03-23 00:07

### ISSUE THREAD

**Issue by runekausland** [librenms/librenms#6372]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Since the release my server updated to by daily.sh on 2017-03-23 00:07 I am having issues with spikes and incorrect graphs in my graphs on IOS-XE Cisco 3650 switches. Visually it looks like they are using 32-bit counters on all interfaces, but I do not think they are. SNMPv1 is disabled on the switches. Intermapper SNMP polls the same switches without issues. I do not see this issue on my IOS-XE Cisco 4500x switches. No interfaces show more than 100Mbps load. Overnight from 3.5Gbps load to a spiky 64Mbs average.

Component | Version
--------- | -------
LibreNMS  | 699e99e7954948f869f48018e8fa7ccef2c3c0c7
DB Schema | 184
PHP       | 7.0.17
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

**Comment by runekausland** [comment]
![graph](https://cloud.githubusercontent.com/assets/21310408/24748583/6587d2f4-1ac0-11e7-8f87-b8e38e6068dc.png)

**Comment by mrhoribu** [comment]
FYI, I'm having a similar issue on a few CISCO devices as well. I'll give my info for comparison. One device is a Catalyst 3850 running IOS-XE 3.7.4 and the other a Catalyst 4948 running IOS 12.2(54). I've removed and re-added both devices back with no change. I've also fired up a fresh install of LibreNMS on another box with same results. When you do a realtime graphing of the ports it does show correct stats. It's only the RRD graphs that appear to be out of wack. Would love to see about getting this looked into. Let me know if you need additional help from me.

Component | Version
--------- | -------
LibreNMS  | 7862af20671a2eec051b6d600b2e4c66e618b2ef
DB Schema | 184
PHP       | 5.5.9-1ubuntu4.21
MySQL     | 5.5.54-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

**Comment by laf** [comment]
Try this patch:

https://community.librenms.org/t/cisco-switch-problem/908

**Comment by mrhoribu** [comment]
I found the paste patch. How do I run the patch though, sorry to be so naive.

`	diff --git a/includes/polling/ports.inc.php b/includes/polling/ports.inc.php
index b0c1c22..0771e60 100644
--- a/includes/polling/ports.inc.php
+++ b/includes/polling/ports.inc.php
@@ -213,7 +213,7 @@ if ($device['os'] === 'f5' && (version_compare($device['version'], '11.2.0', '>=
             $port_stats = snmpwalk_cache_oid($device, 'ifXEntry', $port_stats, 'IF-MIB');
         }
         $hc_test = array_slice($port_stats, 0, 1);
-        if (!isset($hc_test[0]['ifHCInOctets']) && !is_numeric($hc_test[0]['ifHCInOctets'])) {
+        if (!isset($hc_test[0]['ifHighSpeed']) && !is_numeric($hc_test[0]['ifHighSpeed'])) {
             $port_stats = snmpwalk_cache_oid($device, 'ifEntry', $port_stats, 'IF-MIB', null, '-OQUst');
         } else {
             foreach ($ifmib_oids as $oid) {
`

**Comment by mrhoribu** [comment]
N/m, google helped. I copied the code into a file in my librenms directory and ran the GIT APPLY PATCH command with no errors. I'll see if that does anything here in the next bit. Thanks.

**Comment by laf** [comment]
That's exactly how to do it :)

**Comment by runekausland** [comment]
Sweet! Thank you so much!

![graph 1](https://cloud.githubusercontent.com/assets/21310408/24773440/80953a0a-1b15-11e7-9d39-6b88be0332e3.png)

**Comment by mrhoribu** [comment]
Yep, working like normal now. Thanks Laf. I take it this patch will eventually make it's way into the main codebase for new installs?

**Comment by laf** [comment]
At present I'm not sure, we might need to work out the best way to do this but for now, glad it's working for you.

**Comment by sorano** [comment]
I'm also suffering from this on a 3850 (Cisco IOS-XE 03.06.04.E RELEASE SOFTWARE (fc2) (UNIVERSALK9)) and decided to try out the patch, however it did not work so well for me.

After the 23rd March:
![](https://i.imgur.com/2SyrEWd.jpg)

After patch:
(saved the content of https://p.libren.ms/view/c1d4930d to /opt/librenms/3850-graph-patch and ran: git apply 3850-graph-patch )

Getting crazy spikes - 6 hour view

![](http://i.imgur.com/wcDn7eP.png)
