### ISSUE TITLE
No Admin when using ad-auth module

### ISSUE THREAD

**Issue by jzombory** [librenms/librenms#6376]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================
Component | Version
--------- | -------
LibreNMS  | b1a414e7858dc9ca4adbf18bae7fb254dfd6a58f
DB Schema | 184
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================
` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

I cannot authenticate with ad-auth module as an admin, i have the groups set up but don't know how to trouble shoot an issue with debug enabled.

what is in config.php

$config['auth_mechanism'] = "active_directory";
$config['auth_ad_url']                     = "ldaps://dc1.mydomain.org ldaps://dc2.mydomain.org";
$config['auth_ad_domain']                  = "mydomian.org";
$config['auth_ad_base_dn']                 = "<dc=mydomain,dc=org>";
$config['auth_ad_check_certificates']      = false;  // require a valid ssl certificate
$config['auth_ad_debug']                   = true; // enable for verbose debug messages
$config['active_directory']['users_purge'] = 30;    // purge users who haven't logged in for 30 days.
$config['auth_ad_require_groupmembership'] = 0; // require users to be members of a group listed below
$config['auth_ad_groups']['domain^admins']['level'] = 10;
$config['auth_ad_groups']['domain^users']['level'] = 7;
#$config['auth_ad_user_filter'] = "(objectclass=user)";
#$config['auth_ad_group_filter'] = "(objectclass=group)";
$config['auth_ad_global_read'] = 1;

With this config, i can authenticate with my ad account but only have read access. the account i am authenticating with had domain admin rights.

**Comment by laf** [comment]
Github isn't for support, please use irc or the community forums.

You can also run `./scripts/auth_test.php`
