### ISSUE TITLE
New device support - RouterOS queues

### ISSUE THREAD

**Issue by jeremyjhall** [librenms/librenms#6383]
It would be great to add support for basic traffic monitoring for 'simple queues' (and perhaps to be followed by regular tree queues) in RouterOS devices. More information about queues in RouterOS can be found here: https://wiki.mikrotik.com/wiki/Manual:Queue

A 'simple queue' consists of the following OIDs:
`name=.1.3.6.1.4.1.14988.1.1.2.1.1.2.2 bytes-in=.1.3.6.1.4.1.14988.1.1.2.1.1.8.2 
      bytes-out=.1.3.6.1.4.1.14988.1.1.2.1.1.9.2 packets-in=.1.3.6.1.4.1.14988.1.1.2.1.1.10.2 
      packets-out=.1.3.6.1.4.1.14988.1.1.2.1.1.11.2 queues-in=.1.3.6.1.4.1.14988.1.1.2.1.1.12.2 
      queues-out=.1.3.6.1.4.1.14988.1.1.2.1.1.13.2` 

Perhaps the queue graphs could be placed under the 'Graphs' tab (/device/device=1/tab=graphs/) ie alongside `Netstats | System | Poller`.  Or, perhaps there should be a new top-level page, eg: `/device/device=1/tab=queues/`. I leave that to your best judgement!

NB: I will happily provide SNMP access to a Mikrotik RouterOS device to assist with any development :-)

SNMPwalk, poller.php output is linked below.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | b1a414e7858dc9ca4adbf18bae7fb254dfd6a58f
DB Schema | 184
PHP       | 5.5.9-1ubuntu4.20
MySQL     | 5.5.53-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2`

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

Discovery.php: https://p.libren.ms/view/raw/d4c41f0f
Poller.php: https://p.libren.ms/view/raw/8678de3b
SNMPwalk: https://p.libren.ms/view/raw/f728cd33

- [x] Please provide as much detail as possible. 
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
Please post feature requests on the community site

**Comment by jeremyjhall** [comment]
Moved to: https://community.librenms.org/t/feature-request-support-routeros-queues/986
