### ISSUE TITLE
Poller/Discovery modules don't match with config.php

### ISSUE THREAD

**Issue by LemonLight** [librenms/librenms#6389]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 5ce9b6b2e82e09925f1fd9722d1f1c247acfad0a
DB Schema | 184
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 5.7.17-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

Hi !

I configured this in `config.php` : 
`$config['poller_modules']['cisco-otv']                    = 0;`
`$config['discovery_modules']['cisco-otv']                 = 0;`

But when I add a new device, it's still enabled : 

Module | Global | OS | Device | Status
------ | ------ | -- | ------ | ------
cisco-otv | Disable | Enabled | Unset | ON

So I guess, because it's enabled on OS, it automatically turns on ? Because for example, for `cisco-asa-firewall`, I have got this when I add my device : 

`$config['poller_modules']['cisco-asa-firewall']                    = 0;`
`$config['discovery_modules']['cisco-asa-firewall']                 = 0;`

Module | Global | OS | Device | Status
------ | ------ | -- | ------ | ------
cisco-asa-firewall | Disable | Unset | Unset | OFF

How can I configure librenms that it chooses the "Global" state as default state ? 

Thanks in advance.

**Comment by laf** [comment]
You need to se this for the OS to be disabled, the order of priory is:

Device then OS then Global.

`$config['os']['asa']['poller_modules']['cisco-asa-firewall'] = 0;`

This isn't a bug though, please post in the community forums or irc if you need help understanding this further.
