### ISSUE TITLE
Mibs for ZoneDirector Ruckus Version	9.13.3.0 build 41

### ISSUE THREAD

**Issue by fran-nlt** [librenms/librenms#6390]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
root@monitoreo:/opt/librenms# ./validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | 5ce9b6b2e82e09925f1fd9722d1f1c247acfad0a
DB Schema | 184
PHP       | 5.5.9-1ubuntu4.16
MySQL     | 5.5.49-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2
==========================================================

[FAIL]  We have found some files that are owned by a different user than librenms, this will stop you updating automatically and / or rrd files being updated causing graphs to fail.
        [FIX] chown -R librenms:librenms /opt/librenms
         /opt/librenms/LibreNMS/Component.php
         /opt/librenms/LibreNMS/Exceptions/InvalidRrdTypeException.php
         /opt/librenms/LibreNMS/Exceptions/DatabaseConnectException.php
         /opt/librenms/LibreNMS/ComposerHelper.php
         /opt/librenms/LibreNMS/RRD
         /opt/librenms/LibreNMS/RRD/RrdDefinition.php
         /opt/librenms/LibreNMS/IRCBot.php
         /opt/librenms/mibs/edgecos
         /opt/librenms/mibs/edgecos/ES3528MO.mib
         /opt/librenms/mibs/radlan
          and 7348 more...
[OK]    Database connection successful
[FAIL]  MySQL column collation is wrong:  [FIX] https://t.libren.ms/-zdwk
         perf_times type latin1 latin1_swedish_ci
         perf_times doing latin1 latin1_swedish_ci
         syslog facility utf8 utf8_general_ci
         syslog priority utf8 utf8_general_ci
         syslog level utf8 utf8_general_ci
         syslog tag utf8 utf8_general_ci
         syslog program utf8 utf8_general_ci
         syslog msg utf8 utf8_general_ci
         users username utf8 utf8_general_ci
         users password utf8 utf8_general_ci
          and 3 more...
[FAIL]  Database: incorrect column (dbSchema/version)
[FAIL]  Database: missing index (dbSchema/PRIMARY)
[FAIL]  Database: incorrect column (users/descr)
[FAIL]  We have detected that your database schema may be wrong, please report the following to us on IRC or the community site (https://t.libren.ms/5gscd):
         ALTER TABLE `dbSchema` CHANGE `version` `version` int(11) NOT NULL DEFAULT '0';
         ALTER TABLE `dbSchema` ADD PRIMARY KEY (`version`);
         ALTER TABLE `users` CHANGE `descr` `descr` char(30) NOT NULL;

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
The Mibs for this version of ZD is not availible
![imagen](https://cloud.githubusercontent.com/assets/13962782/24866803/a9a2ef54-1de1-11e7-8159-aa1b4eea0328.png)

- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
Please post on irc or the community forum, github is for bug reports.

**Comment by laf** [comment]
I'm actually not even sure what this post is for, if it's for updated or new device support then provide all the info we ask for above.

**Comment by fran-nlt** [comment]
Hi, I send the information again?

**Comment by fran-nlt** [comment]
https://p.libren.ms/view/321313e2

**Comment by fran-nlt** [comment]
root@monitoreo:/opt/librenms# ./daily.sh
Re-running /opt/librenms/daily.sh as librenms user
Updating to latest codebase                        OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK
root@monitoreo:/opt/librenms# ./validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | 295d0b405d2ffef591006458a7ce9b7a91bd08a0
DB Schema | 185
PHP       | 5.5.9-1ubuntu4.16
MySQL     | 5.5.49-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful
[FAIL]  MySQL column collation is wrong:  [FIX] https://t.libren.ms/-zdwk
         syslog facility utf8 utf8_general_ci
         syslog priority utf8 utf8_general_ci
         syslog level utf8 utf8_general_ci
         syslog tag utf8 utf8_general_ci
         syslog program utf8 utf8_general_ci
         syslog msg utf8 utf8_general_ci
         users username utf8 utf8_general_ci
         users password utf8 utf8_general_ci
         users realname utf8 utf8_general_ci
         users email utf8 utf8_general_ci
          and 1 more...
[FAIL]  Database: incorrect column (dbSchema/version)
[FAIL]  Database: missing index (dbSchema/PRIMARY)
[FAIL]  Database: incorrect column (users/descr)
[FAIL]  We have detected that your database schema may be wrong, please report the following to us on IRC or the community site (https://t.libren.ms/5gscd):
         ALTER TABLE `dbSchema` CHANGE `version` `version` int(11) NOT NULL DEFAULT '0';
         ALTER TABLE `dbSchema` ADD PRIMARY KEY (`version`);
         ALTER TABLE `users` CHANGE `descr` `descr` char(30) NOT NULL;
root@monitoreo:/opt/librenms#

**Comment by fran-nlt** [comment]
Hi
![imagen](https://cloud.githubusercontent.com/assets/13962782/25129586/138b3816-2415-11e7-99ba-a254e1ac708e.png)
.

**Comment by fran-nlt** [comment]
https://community.librenms.org/t/ruckus-zd-mibs-firmware-version-9-13-3-0-build-41/1020/7
