### ISSUE TITLE
Cannot add IPV6 only host: "Could not connect"

### ISSUE THREAD

**Issue by zxyz** [librenms/librenms#6391]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

>Component | Version
>--------- | -------
>LibreNMS  | 5ce9b6b2e82e09925f1fd9722d1f1c247acfad0a
>DB Schema | 184
>PHP       | 7.0.15-0ubuntu0.16.04.4
>MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
>RRDTool   | 1.5.5
>SNMP      | NET-SNMP 5.7.3
>
>[OK]    Database connection successful
>[OK]    Database schema correct

I added `udp6` to /etc/snmp/snmpd.conf for enabling IPv6:

```
# Change RANDOMSTRINGGOESHERE to your preferred SNMP community string
agentaddress udp:161
agentaddress udp6:161

com2sec readonly  default       COMMUNITY
com2sec6 readonly  default      COMMUNITY

group MyROGroup v2c        readonly
view all    included  .1                               80
access MyROGroup ""      any       noauth    exact  all    none   none

syslocation Station Berlin
syscontact Your Name <your@email.address>

#Distro Detection
extend .1.3.6.1.4.1.2021.7890.1 distro /usr/bin/distro
```
removing `agentaddress udp:161` doesn't help.

the DNS record is as follows: `AAAA    2017:f11:z:123::1`

`snmpwalk -v 2c -c COMMUNITY fqdn.example.net` works:

>"iso.3.6.1.2.1.1.1.0 = STRING: "Linux test 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 >14:51:03 UTC 2017 x86_64"
>iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.8072.3.2.10
>iso.3.6.1.2.1.1.3.0 = Timeticks: (45812431) 5 days, 7:15:24.31"
> [...]

`snmpwalk -v 2c -c COMMUNITY 2017:f11:z:123::1` works to:

>iso.3.6.1.2.1.1.1.0 = STRING: "Linux test 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 >14:51:03 UTC 2017 x86_64"
>iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.8072.3.2.10
>iso.3.6.1.2.1.1.3.0 = Timeticks: (45824807) 5 days, 7:17:28.07
>[...]

`sudo su - librenms -c '/opt/librenms/addhost.php fqdn.example.net COMMUNITY v2c'` results in:

> Could not connect, please check the snmp details and snmp reachability
>  SNMP v2c: No reply with community COMMUNITY

`sudo su - librenms -c '/opt/librenms/addhost.php 2017:f11:z:123::1 COMMUNITY v2c'`

> Could not connect, please check the snmp details and snmp reachability
>  SNMP v2c: No reply with community COMMUNITY

any hints? thanks a lot!

**Comment by laf** [comment]
Please post this in irc or the community forum - github is for bug reports.

**Comment by zxyz** [comment]
sorry!
