### ISSUE TITLE
Blank graph with dnos-cpu

### ISSUE THREAD

**Issue by infraATE** [librenms/librenms#6394]
Hello, all my graph with "dnos-cpu" are blank.
I have no issue with other CPU types (powerconnect, ironware, etc...)

Component | Version
--------- | -------
LibreNMS  | 069020cb80074ccbedc0b285437f8548a207f6b7
DB Schema | 184
PHP       | 7.0.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

You can find the revellant discovery polling here : https://pastebin.com/fPaF7Hf5

Here are some screenshots :
https://snag.gy/f9Eb3y.jpg
https://snag.gy/2pjmaI.jpg

Let me now if you need more informations.

Thanks.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
Please provide all the information asked for in the points above.
