### ISSUE TITLE
Already have host, even though it doesn't!

### ISSUE THREAD

**Issue by tslytsly** [librenms/librenms#6395]
Hi,

I'm trying to add a new device, different DNS name and ip from any other already in the DB, but I am getting an error telling me "Already have host lg-ucp-raicam (OpenWrt)"

now there already are 2 other devices of the same type in the DB, and they call themselves OpenWrt. (Even though they are not, not great SNMP implementation)
But nothing with this hostname or IP.

Thanks

Tom

```
Component | Version
--------- | -------
LibreNMS  | 5ce9b6b2e82e09925f1fd9722d1f1c247acfad0a
DB Schema | 184
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
```

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
Please post on irc or the community forum, github is for bugs only.

**Comment by tslytsly** [comment]
Hi @laf I think this might be a bug. 
My point is that I do not already have this device added, so why am I getting this error. Surely it is a bug?
