### ISSUE TITLE
Blank chart witch dnos-cpu

### ISSUE THREAD

**Issue by infraATE** [librenms/librenms#6402]
Hello,
when dnos-cpu is selected for a device my charts are empty. However, when i make a discovery.php the "processor_usage" value is correct.

Discover Processor: .1.3.6.1.4.1.674.10895.5000.2.6132.1.1.1.1.4.9.0, 0, dnos-cpu, CPU, 1, 34.46, ,
SQL[SELECT COUNT(processor_id) FROM `processors` WHERE `processor_index` = '0' AND `device_id` = '32' AND `processor_type` = 'dnos-cpu']
.SQL[UPDATE `processors` set `processor_descr` ='CPU',`processor_oid` ='.1.3.6.1.4.1.674.10895.5000.2.6132.1.1.1.1.4.9.0',**`processor_usage` ='34.46**',`processor_precision` ='1' WHERE `device_id`='32' AND `processor_index`='0' AND `processor_type`='dnos-cpu']
SQL[SELECT COUNT(*) FROM `processors` WHERE `device_id` = '32' AND `processor_type` != 'ucd-old']

sh daily.sh
Re-running /opt/librenms/daily.sh as librenms user
Updating to latest codebase                        OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK

Component | Version
--------- | -------
LibreNMS  | 069020cb80074ccbedc0b285437f8548a207f6b7
DB Schema | 184
PHP       | 7.0.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

You can find more relevant informations here : https://pastebin.com/RvFiGTA3
As you can see I have some error with "/pbin.sh"

![172 16 43 111-cpu](https://cloud.githubusercontent.com/assets/25792913/24948325/3ea1afd0-1f6a-11e7-946e-3f57a4bd5939.jpg)

![172 16 43 111-cpu-debug](https://cloud.githubusercontent.com/assets/25792913/24948340/48b43402-1f6a-11e7-84d2-0bbdf2b00ad8.jpg)

Let me know if you need more informations.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
You need to provide the poller information - please do so on irc or the community forum as github is for bugs which this isn't confirmed as one yet.

**Comment by infraATE** [comment]
Ok sorry i check on the community forum. :)
Have a good day.
