### ISSUE TITLE
SQL Server Express 2014 check_mssql_health with on LibreNMS

### ISSUE THREAD

**Issue by premtimibrahimi** [librenms/librenms#6409]
Hello,

I installed check_mssql_health on LibreNMS running with Ubuntu 16.04 and I have a little problem.
With the commande line the plugin works fine, I get the correct result. Exemple testing connceted users.
I get this result :

root@srv-loki:/usr/lib/nagios/plugins# ./check_mssql_health --server MSSQLSERVER --username 'premtim\root' --password 'Super2010' --mode connection-time --commit
OK - 0.01 seconds to connect as premtim\root | 'connection_time'=0.01;1;5;;

I tried different --mode like list all databases or current users and have the same result.

When I try to use the check_mssql_health on LibreNMS I get the instructions info.

Sorry for my poor English.

I also used check_mssql_server.py and check_mssql_database.py and they both run fine via terminal command and LibreNMS, but I'm having issues with this one.

![capture](https://cloud.githubusercontent.com/assets/26636768/24981899/0c73eb5c-1fdf-11e7-818c-dc21486ebf69.PNG)

![update](https://cloud.githubusercontent.com/assets/26636768/24981903/11af1696-1fdf-11e7-9871-47cedb93eb56.PNG)

![validate](https://cloud.githubusercontent.com/assets/26636768/24981910/15d1bbd4-1fdf-11e7-91c6-005d985121e9.PNG)

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
You've already started a thread on the community forum, GitHub is for bugs.
