### ISSUE TITLE
New Device - Ericsson LG - UCP100 & UCP600 PBX

### ISSUE THREAD

**Issue by tslytsly** [librenms/librenms#6411]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
```
==========================================================
Component | Version
--------- | -------
LibreNMS  | c5c643f9017d4a9bc53fa16ab549383b9ea772d4
DB Schema | 185
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================
```

# Ericsson LG - UCP100 PBX
Discovery: https://p.libren.ms/view/b62737c9
Poller: https://p.libren.ms/view/e64d81bd
SNMP walk: https://p.libren.ms/view/f7056f1c

# Ericsson LG - UCP600 PBX
Discovery: https://p.libren.ms/view/3b8b6644
Poller: https://p.libren.ms/view/4a9ff65b
SNMP walk: https://p.libren.ms/view/2fb18a28

Happy to get any further info needed or to do testing.

Tom
*edited to fix broken urls
** edited again to fix more broken urls!

**Comment by laf** [comment]
Your links are 404'ing, provide updated info and we can re-open.

**Comment by tslytsly** [comment]
@laf sorry about that, not sure why.
I have fixed the URLs above.
