### ISSUE TITLE
Cisco devices changed to Generic Device

### ISSUE THREAD

**Issue by claushc** [librenms/librenms#6434]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)

Yes, running the daily.sh script daily, but tonight something fishy started to appear.

- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 924b751be46229bec2ff0a33330ef48553fcb80f
DB Schema | 185
PHP       | 5.5.9-1ubuntu4.21
MySQL     | 5.5.54-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

[discovery-as1.ker1.nefnet.dk.txt](https://github.com/librenms/librenms/files/924052/discovery-as1.ker1.nefnet.dk.txt)

[poller-as1.ker1.nefnet.dk.txt](https://github.com/librenms/librenms/files/924053/poller-as1.ker1.nefnet.dk.txt)

[generic-as1.ker1.nefnet.dk.snmpwalk.txt](https://github.com/librenms/librenms/files/924054/generic-as1.ker1.nefnet.dk.snmpwalk.txt)

- [X] Please provide as much detail as possible.

After tonights daily.sh run, LibreNMS decided to report all my Cisco devices as Generic Device, changing device icons and stuff.  This happened to three different types of devices, but I have only included one, since it's probably a very simple problem.

- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
Please update and re-test

**Comment by claushc** [comment]
Problem fixed.  Thank you very much for your help :-)

**Comment by murrant** [comment]
Thanks for the revert @laf any idea what went wrong?

**Comment by laf** [comment]
@murrant I've not looked, I reverted because I didn't have time to check into it and I expected no one else would so rather than let it escalate through people's installs I just reverted the change.

**Comment by network-guy** [comment]
@murrant @laf If it helps, it appears that only classic IOS (3750s, 2960s, 2901s in my case) devices were misidentified. IOS-XE devices were still identifying properly.

**Comment by PENorris** [comment]
@network-guy   I lost all of my IOS-XE equipment to the generic gods.

**Comment by Rosiak** [comment]
Same as @PENorris

**Comment by murrant** [comment]
The regex did not like multi line sysDescr's.  Our tests put everything on one line.

I'll be fixing both issues. Closing this as the change is reverted, but I'll reference it in the PRs.
