### ISSUE TITLE
Regression: PR #6425 breaks PR #2065 (Dell Wireless controllers discovered as Powerconnect Switches)

### ISSUE THREAD

**Issue by fstern** [librenms/librenms#6446]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 5a46e9e34ae7e4a4532f9d6ed6824ae1a5d60e77
DB Schema | 185
PHP       | 5.4.16
MySQL     | 5.5.47-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

I updated to the current version today and noticed that our Dell Wireless controllers were missing data. 

The devices were rediscovered as Dell Powerconnect Switches (which I fixed in PR2065 a while ago) 

Discovery Output: 
Modules status: Global+ OS  Device  
#### Load disco module os ####
SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs:/opt/librenms/mibs/dell udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0]
ArubaOS (MODEL: Dell PowerConnect W-7210 Controller), Version * (55228)

SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Ovqn -M /opt/librenms/mibs:/opt/librenms/mibs/dell udp:HOSTNAME:161 SNMPv2-MIB::sysObjectID.0]
.*.4.1.674.10895.5027

| ArubaOS (MODEL: Dell PowerConnect W-7210 Controller), Version 6.4.4.8 (55228) | .1.3.6.1.4.1.674.10895.5027 | 

>> Runtime for discovery module 'os': 0.2470 seconds with 1584 bytes

Relevant links: 
discovery.php: https://p.libren.ms/view/7127cbef
poller.php: https://p.libren.ms/view/2c2db786
snmpbulkwalk: https://p.libren.ms/view/89118e02

**Comment by murrant** [comment]
Sorry about that, didn't see any devices like this reported to https://stats.librenms.org so I didn't know they existed.  Fix incoming with tests to make sure it won't break in the future ;)

**Comment by fstern** [comment]
Great thanks :) I've enabled usage reporting for our librenms instance.
