### ISSUE TITLE
Avaya ERS 5520 detected as generic device

### ISSUE THREAD

**Issue by flyingdan** [librenms/librenms#6448]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 2b4fb847ee62f35480d18415695898399435a2e9
DB Schema | 185
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

**Links**
discovery - https://p.libren.ms/view/5969a3cf
poller - https://p.libren.ms/view/b6e08359
snmpbulkwalk - https://p.libren.ms/view/c915f8d9

**Issue Description**
**Device:** Avaya Ethernet Routing Switch 5520-48T-PWR  HW:34  FW:6.0.0.10  SW:v6.2.1.003
Switch is being detected as generic device. There is a MIB walker in the management interface and it returns the following information for objects searched by discovery:
sysDescr
Object ID: 1.3.6.1.2.1.1.1
Value: Ethernet Routing Switch 5520-48T-PWR  HW:34       FW:6.0.0.10  SW:v6.2.1.003 BN:03 (c) Avaya Networks

sysObjectID
Object ID: 1.3.6.1.2.1.1.2
Value: 1.3.6.1.4.1.45.3.59.2
The MIB Name for 1.3.6.1.4.1.45.3.59.2 is "sreg-BayStack5520-48T-PWR"

**Comment by murrant** [comment]
Not sure why that would be.  Detection is if sysObjectID starts with .1.3.6.1.4.1.45. and sysDescr contains Ethernet Routing Switch then it is avaya-ers.  That seems to match the data you have provided here.

**Comment by murrant** [comment]
The pastes seem to be missing :/

**Comment by flyingdan** [comment]
I just re-ran them:
discovery - https://p.libren.ms/view/a006bf0a
poller - https://p.libren.ms/view/d1894e3e
snmpbulkwalk - https://p.libren.ms/view/4eafc7b8

It may be that the device is not responding properly. You'll see in the pastes that query results are basically all ```No Such Object available on this agent at this OID```

**Comment by murrant** [comment]
Likely just the discovery trying to check various things. 

I think there might be something wrong with the pastebin service :(  Can you paste it somewhere else for the time being or try manually on the website.

**Comment by flyingdan** [comment]
That's weird, I verified the pastes and they were there. The snmpbulkwalk timed out with no response this time but here are the other two.

[poller.txt](https://github.com/librenms/librenms/files/935036/poller.txt)
[discovery.txt](https://github.com/librenms/librenms/files/935037/discovery.txt)

I'm looking into the devices settings as it seems more and more likely it's not behaving properly.

**Comment by murrant** [comment]
Yeah, it is not responding to SNMP.
sysDescr and sysObjectID are required for discovery:
```
SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Ovq -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysDescr]
No Such Object available on this agent at this OID

SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -Ovqn -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysObjectID]
No Such Object available on this agent at this OID
```

**Comment by flyingdan** [comment]
Alright I figured out the problem. I had to create a MIB view in the device pointing to the correct part of the tree and make sure the view name matches the one in the community.

Thanks for the help.
