### ISSUE TITLE
Geist Watchdog (re-open)

### ISSUE THREAD

**Issue by gstrike** [librenms/librenms#6451]
Hello,

This is a duplicate of #2826, which was closed due to lack of response from the submitter.

If possible I'd like to reopen this.  I have access to a Geist Watchdog 15 device running the latest firmware (3.3.2).  I am willing to provide some type of DMZ access to it for someone working on adding this.

Discovery - https://pastebin.com/ezR8ERp5
Poller - https://pastebin.com/ie7UGhDd
snmpwalk - https://pastebin.com/YXRRGmZZ
MIB (geist_bb_mib.mib) - https://pastebin.com/D7fLF9e7 (This MIB was provided by Geist along with the firmware download at http://www.geistglobal.com/supportfirmware-updates/monitor-firmware).

validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | 2b4fb847ee62f35480d18415695898399435a2e9
DB Schema | 185
PHP       | 7.0.15-1ubuntu4
MySQL     | 10.1.22-MariaDB-
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

I've got some coding skills just a lack of available time on my part.  Please let me know if there's anything I can assist with.

Sincerely,
Greg

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
I'm submitting a pull request to add basic detection as the snmpwalk only contains minimal info. You might need to re-run that and use ` .1.3.6.1.4.1.21239.5.1` instead of `.`

**Comment by adamboutcher** [comment]
I too wouldn't mind some Geist Watchdog support, we have a 1200 Climate Monitor.

I have a hacked script to push key values into Graphite which I've included below. I can provide a walk of the enterprise OIDs and a vague idea of what they are; there are some MIBs somewhere too.

```
#!/bin/bash
#/usr/local/sbin/climateGraph.sh
IP="DEVICE"
COMMUNITY="public"
GRAPHITE="GRAPHITE_HOST"
GPORT="PORT"

stamp=`date +"%s"`

# Main Unit
NAME=`snmpget -v1 -O v -c $COMMUNITY $IP .1.3.6.1.4.1.21239.2.2.1.3.1 | sed -e 's/STRING: \(.*\)/\1/' | tr \  _ | tr -d '()'\"`
TEMP=`snmpget -v1 -O v -c $COMMUNITY $IP .1.3.6.1.4.1.21239.2.2.1.5.1 | sed -e 's/INTEGER: \(.*\)/\1/'`
HUMD=`snmpget -v1 -O v -c $COMMUNITY $IP .1.3.6.1.4.1.21239.2.2.1.6.1 | sed -e 's/INTEGER: \(.*\)/\1/'`
AIRF=`snmpget -v1 -O v -c $COMMUNITY $IP .1.3.6.1.4.1.21239.2.2.1.7.1 | sed -e 's/INTEGER: \(.*\)/\1/'`
LIGH=`snmpget -v1 -O v -c $COMMUNITY $IP .1.3.6.1.4.1.21239.2.2.1.8.1 | sed -e 's/INTEGER: \(.*\)/\1/'`
SOND=`snmpget -v1 -O v -c $COMMUNITY $IP .1.3.6.1.4.1.21239.2.2.1.9.1 | sed -e 's/INTEGER: \(.*\)/\1/'`

#Analogue Sensor (Door)
AIO1=`snmpget -v1 -O v -c $COMMUNITY $IP .1.3.6.1.4.1.21239.2.2.1.11.1 | sed -e 's/INTEGER: \(.*\)/\1/'`
AIO2=`snmpget -v1 -O v -c $COMMUNITY $IP .1.3.6.1.4.1.21239.2.2.1.12.1 | sed -e 's/INTEGER: \(.*\)/\1/'`
AIO3=`snmpget -v1 -O v -c $COMMUNITY $IP .1.3.6.1.4.1.21239.2.2.1.13.1 | sed -e 's/INTEGER: \(.*\)/\1/'`

echo "desktop.climate.$NAME.temp $TEMP $stamp" | nc $GRAPHITE $GPORT
echo "desktop.climate.$NAME.humid $HUMD $stamp" | nc $GRAPHITE $GPORT
echo "desktop.climate.$NAME.airflow $AIRF $stamp" | nc $GRAPHITE $GPORT
echo "desktop.climate.$NAME.light $LIGH $stamp" | nc $GRAPHITE $GPORT
echo "desktop.climate.$NAME.sound $SOND $stamp" | nc $GRAPHITE $GPORT
echo "desktop.climate.$NAME.AIO1 $AIO1 $stamp" | nc $GRAPHITE $GPORT
#echo "desktop.climate.$NAME.AIO2 $AIO2 $stamp" | nc $GRAPHITE $GPORT
#echo "desktop.climate.$NAME.AIO3 $AIO3 $stamp" | nc $GRAPHITE $GPORT

#Added Sensors
NUM_TEMP=`snmpget -v1 -O v -c $COMMUNITY $IP .1.3.6.1.4.1.21239.2.1.8.1.4.0 | sed -e "s/INTEGER: \(.*\)/\1/"`
for i in `seq 1 $NUM_TEMP`; do
        NAME=`snmpget -v1 -O v -c $COMMUNITY $IP .1.3.6.1.4.1.21239.2.4.1.3.$i | sed -e 's/STRING: \(.*\)/\1/' | tr \  _ | tr -d '()'\"`
        TEMP=`snmpget -v1 -O v -c $COMMUNITY $IP .1.3.6.1.4.1.21239.2.4.1.5.$i | sed -e "s/INTEGER: \(.*\)/\1/"`
        echo "desktop.climate.$NAME.temp $TEMP $stamp" | nc $GRAPHITE $GPORT
done
```

**Comment by laf** [comment]
We just need the output of `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .1.3.6.1.4.1.21239`

**Comment by adamboutcher** [comment]
Here you go.
[Geist1200.txt](https://github.com/librenms/librenms/files/943072/Geist1200.txt)

**Comment by adamboutcher** [comment]
We also have a SwiftBase Climate CM-2 Device which is the same physical internals as the Geist1200 but slightly different OS/Firmware.

I've attached an snmpwalk from that which might help more completeness.
[CM2.txt](https://github.com/librenms/librenms/files/943141/CM2.txt)

**Comment by laf** [comment]
If it's a different OS then please submit a new issue with the details we ask for.

**Comment by laf** [comment]
That output contains the OIDs you've shown but aren't what's listed in the GEIST-V4-MIB.

Do you have a mib that uses these values?

**Comment by adamboutcher** [comment]
Hope these help...
[geist_mib_sheetv3-csv.txt](https://github.com/librenms/librenms/files/943411/geist_mib_sheetv3-csv.txt)
[geist_mibv3.txt](https://github.com/librenms/librenms/files/943409/geist_mibv3.txt)

**Comment by laf** [comment]
I've added some health sensors to the PR now. Thanks @adamboutcher

**Comment by gstrike** [comment]
Thank you for taking a look at this!

Here's the output of snmpwalk and a snmpbulkwalk on the Geist Watchdog 15 (WD15).

https://pastebin.com/XM8uAvPC

**Comment by laf** [comment]
I've pushed another commit to add support for the data you've submitted.

**Comment by gstrike** [comment]
@laf, Thank you!  It's pulling data now.

I noticed the temperature and dew point are being graphed in Celsius even though the temperature being reported is the Fahrenheit representation.  The effect is it's saying it's 71C (159F).

This is happening because I have the device set to Fahrenheit in system settings.  If I change the system setting to Celsius everything would match up.  

.1.3.6.1.4.1.21239.5.1.1.7.0 refers to the units being used.  0 = Fahrenheit and 1 = Celsius.  Maybe the quickest way to implement it would be to detect the unit and if it's Fahrenheit, convert it before storing the data?  At least then the data matches the units no matter what the user has decided to set it to?

C = (F - 32) × 5/9

What do you think?

**Comment by laf** [comment]
We don't support data in Fahrenheit, it must be in Celsius.

**Comment by gstrike** [comment]
Are you saying you don't support querying Fahrenheit or storing Fahrenheit?

**Comment by laf** [comment]
Both really, we could possibly do some custom sensor code but we have no way of storing if it's C or F. We can lookup for the sensor but this would mean additional snmp requests which imho isn't worth it as we try and keep polling perform-ant.

**Comment by gstrike** [comment]
@laf Ahhh that makes sense.  I appreciate the work man.  Thank you.
