### ISSUE TITLE
[Feature Request] Yang support

### ISSUE THREAD

**Issue by jean-christophe-manciot** [librenms/librenms#6461]
Yang data models accessed through NetConf/RESTConf/gRPC are taking off. 
They are expected to replace SMI/SNMP in the future. 
Cf. this excellent post by [jason edelman](http://jedelman.com/home/openconfig-data-models-and-apis/) and Ethan Banks' podcasts on [OpenConfig](http://packetpushers.net/openconfig-standardized-models-networking/) and [telemetry](http://packetpushers.net/podcast/podcasts/pq-show-111-yang-telemetry-ietf-98/).

Do you guys have plans to support this new framework?

**Comment by laf** [comment]
This is better to be discussed on https://community.librenms.org/.

GitHub is for bugs and new device requests.
