### ISSUE TITLE
pbin.sh script creates files that expire 

### ISSUE THREAD

**Issue by vladutz33** [librenms/librenms#6465]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
===============================
Component | Version
--------- | -------
LibreNMS  | a0abcbb6496def0bacc77fb811064c314c6d087e
DB Schema | 184
PHP       | 5.5.9-1ubuntu4.21
MySQL     | 5.5.54-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

==========================
When using the pbin.sh script it generates a file on pastebin that expires, and you cannot change it to never expire. I've added some requests for new devices, I couldn't change them to never expire and all the information was lost and I have to upload it again somewhere else.

**Comment by laf** [comment]
When you submitted them this may have been the case but pbin.sh defaults to non-expire and has for a month.
