### ISSUE TITLE
D-Links DGS-3627 Bug LLDP

### ISSUE THREAD

**Issue by roysbike** [librenms/librenms#6473]
Hello. Librenms get fdb system vlan managent. The NMS shows the connections for managing the vlan, but it should show the port number. Observium Shows true

<img width="1389" alt="2017-04-20 12 15 57" src="https://cloud.githubusercontent.com/assets/2388223/25223173/47b3584e-25c3-11e7-9fbb-458790731989.png">
<img width="809" alt="2017-04-20 12 15 49" src="https://cloud.githubusercontent.com/assets/2388223/25223172/47b25ea8-25c3-11e7-9bb4-93a800411c4e.png">

**Comment by laf** [comment]
No information provided that is asked for when creating an issue.

I suggest you also post this on the community site as GitHub is for bugs and new device support, this isn't confirmed as a bug.
