### ISSUE TITLE
Swiftbase Climate CM-2 Device

### ISSUE THREAD

**Issue by adamboutcher** [librenms/librenms#6482]
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
```
==========================================================
Component | Version
--------- | -------
LibreNMS  | 75d62aa068944e17948253781b3805140a98f813
DB Schema | 186
PHP       | 5.4.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================
```

Device walk:
[CM2.txt](https://github.com/librenms/librenms/files/943154/CM2.txt)

Exact same hardware as the Geist IT-Watchdogs 1200/1250 but with a different firmware/os.

**Comment by adamboutcher** [comment]
This is the mib that we are using.
[itw_mib.txt](https://github.com/librenms/librenms/files/945202/itw_mib.txt)

**Comment by laf** [comment]
This doesn't contain any data from `.1.3.6.1.2.1.1` such as sysDescr and sysObjectId. We can't add support without that info.

Feel free to post the data when you have it and we can re-open this.
