### ISSUE TITLE
Enhancement: Add option to disable alerting for normal users with device permissions

### ISSUE THREAD

**Issue by tobiasa1** [librenms/librenms#6499]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | dcc6c96ec4c646feade95eac7f91d402c4dd312b
DB Schema | 186
PHP       | 5.5.9-1ubuntu4.21
MySQL     | 5.5.54-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

When assigning device permissions to a normal user without admin privileges this user are receiving alert e-mails for that specific device and there seems to be no option to disable that. I suggest we add an option in the General Alert Settings tab to Issue alerts to normal users Yes/No

**Comment by f0o** [comment]
I wouldn't call it a bug, it's by design.

if there's a general demand for this feature, I can easily make a PR for this

**Comment by laf** [comment]
I'd definitely say it's a bug. When you assign device permissions to a user they start getting alerts with no way to turn it off other than disabling the rules.
