### ISSUE TITLE
ExtremeXOS v15.3.1.4 cpu usage oid wrong values  

### ISSUE THREAD

**Issue by zombah** [librenms/librenms#6510]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | f31b0a562bc6d68c0e199a6b3faa2ca54b57f60b
DB Schema | 186
PHP       | 7.0.16-1~dotdeb+8.1
MySQL     | 10.0.30-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

Behavior of cpu usage oid for ExtremeXOS changed for devices with version 15.3.1.4 for example, it now reports data of max encountered cpu usage and not 5 min value. Here is comparison:
XOS version: 12.3.3.6
snmpwalk data: SNMPv2-SMI::enterprises.1916.1.32.1.4.1.9.1 = STRING: "4.3"
device cli data: System        3.9  4.1  3.8  4.3  4.3  4.4  4.4 99.9   675.59   11307616.21

XOS version: 15.3.1.4
snmpwalk data: SNMPv2-SMI::enterprises.1916.1.32.1.4.1.9.1 = STRING: "99.9"
device cli data: System        0.0  0.0  0.0  0.0  0.0  0.0  0.0 99.9  3540.85   5697122.74

This leads to wrong graphs showing permanent 100% cpu load for v15.3.1.4 device which ever encountered even short max cpu.

**Comment by laf** [comment]
I'm not sure I'd say this is a bug because a vendor has changed behaviour.

What OID should be used?

**Comment by zombah** [comment]
I don't know yet. iso.3.6.1.4.1.1916.1.32.1.4.1.9.1 was always rock solid until this XOS version.
I will investigate further. Maybe this is snmp bug in this XOS version.

**Comment by laf** [comment]
I'll close for now, please reply with any further info you might find.

**Comment by zombah** [comment]
Just tested with newer version, its definitely just this xos release bug or specific behavior, sorry for noise.

version 12.2.x:
iso.3.6.1.4.1.1916.1.32.1.4.1.5.1 = STRING: "1.5"
iso.3.6.1.4.1.1916.1.32.1.4.1.6.1 = STRING: "1.7"
iso.3.6.1.4.1.1916.1.32.1.4.1.7.1 = STRING: "1.6"
iso.3.6.1.4.1.1916.1.32.1.4.1.8.1 = STRING: "1.7"
iso.3.6.1.4.1.1916.1.32.1.4.1.9.1 = STRING: "1.6"
iso.3.6.1.4.1.1916.1.32.1.4.1.10.1 = STRING: "0.9"
iso.3.6.1.4.1.1916.1.32.1.4.1.11.1 = STRING: "0.4"
iso.3.6.1.4.1.1916.1.32.1.4.1.12.1 = STRING: "39.1"

version 15.3.1.4:
iso.3.6.1.4.1.1916.1.32.1.4.1.2.1 = STRING: "5.6"
iso.3.6.1.4.1.1916.1.32.1.4.1.3.1 = STRING: "5.1"
iso.3.6.1.4.1.1916.1.32.1.4.1.4.1 = STRING: "5.1"
iso.3.6.1.4.1.1916.1.32.1.4.1.5.1 = STRING: "5.1"
iso.3.6.1.4.1.1916.1.32.1.4.1.6.1 = STRING: "4.9"
iso.3.6.1.4.1.1916.1.32.1.4.1.7.1 = STRING: "4.7"
iso.3.6.1.4.1.1916.1.32.1.4.1.8.1 = STRING: "4.7"
iso.3.6.1.4.1.1916.1.32.1.4.1.9.1 = STRING: "99.9"

version 15.3.5.2:
iso.3.6.1.4.1.1916.1.32.1.4.1.5.1 = STRING: "1.5"
iso.3.6.1.4.1.1916.1.32.1.4.1.6.1 = STRING: "1.7"
iso.3.6.1.4.1.1916.1.32.1.4.1.7.1 = STRING: "1.6"
iso.3.6.1.4.1.1916.1.32.1.4.1.8.1 = STRING: "1.7"
iso.3.6.1.4.1.1916.1.32.1.4.1.9.1 = STRING: "1.6"
iso.3.6.1.4.1.1916.1.32.1.4.1.10.1 = STRING: "0.9"
iso.3.6.1.4.1.1916.1.32.1.4.1.11.1 = STRING: "0.4"
iso.3.6.1.4.1.1916.1.32.1.4.1.12.1 = STRING: "39.1"

**Comment by laf** [comment]
No probs, thanks for confirming.
