### ISSUE TITLE
EqualLogic disk state translation

### ISSUE THREAD

**Issue by sorano** [librenms/librenms#6512]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

As we discussed on IRC to solve state translation: #6497

`SELECT `sensors`.*, `state_indexes`.`state_index_id` FROM `sensors` LEFT JOIN `sensors_to_state_indexes` ON sensors_to_state_indexes.sensor_id = sensors.sensor_id LEFT JOIN state_indexes ON state_indexes.state_index_id = sensors_to_state_indexes.state_index_id WHERE `sensor_class` = 'state' AND device_id = 272 ORDER BY `sensor_type`, `sensor_index`+0, `sensor_oid`;`
state_index_id = 313466

`SELECT * FROM state_indexes WHERE state_name = 'eqlDiskStatus';`
313466 | eqlDiskStatus

[10:48] <@laf> DELETE FROM sensors_to_state_indexes WHERE state_index_id=313466;
[10:48] <@laf> DELETE FROM state_indexes WHERE state_name = 'eqlDiskStatus';
[10:48] <@laf> then re-run discovery
[10:49] <sorano> Boom!
[10:50] <sorano> laf delivers as always :)
[10:50] <@laf> ace

**Comment by laf** [comment]
We need to add more checks in `create_state_index()`
