### ISSUE TITLE
New Device Support Buffalo TS3400D

### ISSUE THREAD

**Issue by kkrumm1** [librenms/librenms#6514]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

==========================================================
Component | Version
--------- | -------
LibreNMS  | cdd363f29ebcdb361ca207a379ff9fd450608d62
DB Schema | 186
PHP       | 7.0.17
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful
[OK]    Database schema correct

Pretty sure got support for the Buffalo OS but not this Model TS3400. LibreNMS is not showing any of the drives or CPU and memory and the NIC.

Buffalo TS3400D Discovery https://p.libren.ms/view/410d0973
Buffalo TS3400D Poller https://p.libren.ms/view/bd9c9954
Buffalo TS3400D SNMP Walk https://p.libren.ms/view/593dbf54

**Comment by laf** [comment]
The walk for this device barely contains any data, the issue looks like it's the Buffalo device. I'd suggest contacting the vendor for help
