### ISSUE TITLE
HTTP ERROR 500 / Weathermap Editor

### ISSUE THREAD

**Issue by tracerrx** [librenms/librenms#6519]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X ] Please provide as much detail as possible.
- [X ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

==========================================================
Component | Version
--------- | -------
LibreNMS  | d67d62eacb880163768588fb0c1b879cbcfa77d5
DB Schema | 187
PHP       | 7.0.18
MySQL     | 5.5.47-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

```
2017/04/27 23:03:33 [error] 12180#0: *1377 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function dbDelete() in /opt/librenms/html/includes/authenticate.inc.php:24
Stack trace:
#0 /opt/librenms/html/plugins/Weathermap/editor.php(54): require_once()
#1 {main}
  thrown in /opt/librenms/html/includes/authenticate.inc.php on line 24" while reading response header from upstream, client:
```

**Comment by laf** [comment]
Please post on https://github.com/librenms-plugins/weathermap
