### ISSUE TITLE
Error loading page after login

### ISSUE THREAD

**Issue by joubertredrat** [librenms/librenms#652]
Hi guys,

From my point of view this is serious, when you access and isn't logged, is displayed login form, if you login with success, show index, but when page refresh, Firefox likes and Internet Explorer report that you're trying to send data again, this data is a post from login. I think this is not good because with firebug or another tool is possible to track and intercept data.

I think good idea is have a login form in a separate page, http://demo.librenms.org/login as example.

I will provide this in one branch to test and when is done I will put here

**Comment by f0o** [comment]
Is this still valid?

**Comment by laf** [comment]
It's still valid but I wouldn't class it as serious.

The only aspect that's a concern is data posted from login over http (which is always ill advised), however the data was posted already so if someone is genuinely sniffing between you and the nms then they will already have your login details.

We could beef up the form submission and encrypt in the browser but this is probably not going to work for all auth methods.

**Comment by laf** [comment]
PR #775 should fix this.
