### ISSUE TITLE
Eaton 9PX 2000 RT reporting 4.5% load when it's at 45%.

### ISSUE THREAD

**Issue by boudreau** [librenms/librenms#6521]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | d67d62eacb880163768588fb0c1b879cbcfa77d5
DB Schema | 187
PHP       | 7.0.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.5.6
SNMP      | NET-SNMP 5.7.2

The load divisor is set at 10 by default, it should be set to 1 for this model at least.
The real load of the UPS is 45% the OID does not need to be divided by 10.

```
SQL[UPDATE `sensors` set `sensor_current` ='60',`sensor_prev` ='60',`lastupdate` =NOW() WHERE `sensor_class` = 'frequency' AND `sensor_id` = '79228']
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = 'load' AND `device_id` = '1682']
SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -OUQnt -M /var/www/librenms/mibs:/var/www/librenms/mibs/ups:/var/www/librenms/mibs/mge -t 2 -r 2 udp:HOSTNAME:161 .1.3.6.1.2.1.33.1.4.4.1.5.1]
.*.*.*.1 = 45

Checking (snmp) load Percentage load...
4.5 %
RRD[last xxxxx-lab-eaton1.my.com/sensor-load-rfc1628-501.rrd  --daemon unix:/var/run/rrdcached/rrdcached.sock]
RRD[update xxxxx-lab-eaton1.my.com/sensor-load-rfc1628-501.rrd N:4.5 --daemon unix:/var/run/rrdcached/rrdcached.sock]

InfluxDB data:
sensorArray
(
    [hostname] => xxxxx-lab-eaton1.my.com
    [sensor_class] => load
    [sensor_type] => rfc1628
    [sensor_descr] => Percentage\ load
    [sensor_index] => 501
)
Array
(
    [sensor] => 4.5
)

END

```

**Comment by laf** [comment]
What OS are these detected as?

**Comment by boudreau** [comment]
./poller.php -h 1682 -m os
LibreNMS Poller
Starting polling run:

Hostname: xxxxx-lab-eaton1.my.com
Device ID: 1682
OS: eaton-mgeups (ups)

**Comment by FTBZ** [comment]
Only the load or other values have problems too?

**Comment by FTBZ** [comment]
Can you test this patch: 
https://github.com/librenms/librenms/pull/6566
