### ISSUE TITLE
Location manager

### ISSUE THREAD

**Issue by laf** [librenms/librenms#654]
I'd like to create a location manager so that you can:

Create data centres
 - Store address details.
 - NOC information and contact details.

Create racks and allocate to data centres.
 - Supplier reference details.
 - Internal reference details.
 - Size and specification of rack.

Auto assign + manually assign devices to a rack (based on location field possibly?)
 - Assign actual position within rack.
 - Maybe include information such as what PDU connected to.
 - If no xDP then allow to manually select switch port.

Any other ideas?

**Comment by robje** [comment]
Below are more remarks than ideas. Hopefully still usable.

At work we're using a tool called RackMonkey which does something similar: https://flux.org.uk/projects/rackmonkey/
Maybe this is usable as a starting point.

Challenge I see is form factor, some examples:
- a Dell M1000e blade chassis can hold a combination of blade sizes. From 8 double sized blades to 32 half sized blades and any combination in between.
- Supermicro has 1U pizza boxes holding two servers.
I guess this means that possibilities are endless. Which raises the question how to implement.
