### ISSUE TITLE
New Device Support - NetPower PDU

### ISSUE THREAD

**Issue by guoming218** [librenms/librenms#6547]
Hi all,

Kindly help to add this new device in.

Thanks and appreciated.

Rgds,
guoming

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the ==========================================================
Component | Version
--------- | -------
LibreNMS  | ed432095e5882c49ea460643b05122aabe538734
DB Schema | 187
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.54-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================
` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
[Net-Power PDU Discovery.txt](https://github.com/librenms/librenms/files/969670/Net-Power.PDU.Discovery.txt)
[Net-Power PDU poller.txt](https://github.com/librenms/librenms/files/969671/Net-Power.PDU.poller.txt)
[Net-Power PDU SNMPwalk.txt](https://github.com/librenms/librenms/files/969672/Net-Power.PDU.SNMPwalk.txt)
- [x] Please provide as much detail as possible.
![image](https://cloud.githubusercontent.com/assets/24470844/25607953/7f557b88-2f4b-11e7-8fd1-360a9a6dac96.png)
Net-Power Logo
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by guoming218** [comment]
Hi Laf,

What verification do you need. I can try to provide it if i have.

Rgds,
guoming

**Comment by laf** [comment]
Nothing, it's a flag for us.

**Comment by laf** [comment]
Do you have a link to the vendor and this product?

**Comment by laf** [comment]
We also need the MIBs please

**Comment by guoming218** [comment]
HI Laf,

I cant find the link and MIBs too.
Still trying to search for it.

rgds,
guoming

**Comment by laf** [comment]
Let us know when you have the mib and vendor product link and we can re-open this.
