### ISSUE TITLE
IP Manager

### ISSUE THREAD

**Issue by laf** [librenms/librenms#655]
I'd like to create an IP manager so that you can:

Manually create subnets.
 - Networks will be auto created based on device discovery as normal but disable removal of networks if manually created.
 - Create your larger pool of space and sub-allocate out (how many times should we enable this?)

IP visualisation:
 - Display IP usage for the networks, free space, used.
 - Integrate a RBL lookup to scan for bad IP space.

Anything else?

**Comment by paulgear** [comment]
Think about integrating an existing solution for this.  Good list of possibilities here: http://www.ipv6now.com.au/addresses.php

**Comment by gadago** [comment]
We already use phpIPAM, so would love to see that integrated.

**Comment by laf** [comment]
I'll take a look, the main issue I see is we already have some IP address recording going on, this may not fit in with a 3rd party system.

**Comment by killsudo** [comment]
An idea would be to integrate with phpIpam via the api. Use LibreNMS as a king of the hill to detect vrfs/subnets/vlans and use the phpIpam api to populate that information and eventually remove objects no longer being detect by polls. If the phpIpam guys were interested in expanding the api to allow device adds/delete/changes then you could even populate those values to attach vrfs/vlans/subnets to.

http://sourceforge.net/p/phpipam/code/HEAD/tree/api/

**Comment by Lonecrowe** [comment]
Thanks for the tip on the PHPIPAM I never saw that before.  Pretty cool.

**Comment by paulgear** [comment]
The nice thing about IPAM solutions is there are so many to choose from. ;-)
