### ISSUE TITLE
TrippLite ATSes; Output Source has value "8" when on secondary input

### ISSUE THREAD

**Issue by peelman** [librenms/librenms#6552]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

---

This isn't so much a problem with LibreNMS as a minor issue with TrippLite slightly abusing the RFC1628 MIB for their ATS's.  It appears that since the generic UPS MIB doesn't have provisions for primary/secondary power inputs (only Normal/Bypass/Battery/etc) TrippLite returns "8" for the upsOutputSourceState, which isn't defined in the `UPS-MIB`.

For this device type in particular, a status of "8" should be a warning that throws an alert, since it would indicate a loss of the "primary" power input.  But on other makes/models of UPS-MIB-using devices, if they do something similar, but different, that could pose a problem.

This is pretty trivial, but I'm willing to put a patch in if there's a consensus on a way forward.  

Thoughts?

**Comment by laf** [comment]
Please discuss this on the community site, GitHub is for bugs and new device support of which, as you've said, seems to be a vendor issue rather than an issue for us.
