### ISSUE TITLE
Windows Servers - Voltage Sensors Alert Parameter - Precision issue

### ISSUE THREAD

**Issue by NerdBlender** [librenms/librenms#6559]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hi,

I keep getting voltage alerts for my windows boxes as it thinks the sensors are under limit. 

In discovery the SNMP figures show this for the two PSU's:

voltageProbeReading.1.26 = 230000
voltageProbeReading.1.27 = 230000

The alert settings are:

![image](https://cloud.githubusercontent.com/assets/23742981/25652620/f7271c4e-2fe0-11e7-92d1-cc9b8a555d61.png)

Somehow, the precision of the alert threshold is wrong, or the precision of the sensor passed to the alerting system is wrong.

**Comment by laf** [comment]
You need to provide all the info as requested above. When you've done that we can re-open this issue and take a look.
