### ISSUE TITLE
Cisco WLC 8510: new Wireless Sensors code not displaying per-SSID graphs

### ISSUE THREAD

**Issue by alanbboyd** [librenms/librenms#6560]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

`Component | Version`
`--------- | -------`
`LibreNMS  | 233f8e83b4e44faa26a980f2ccc9f25e882f917e`
`DB Schema | 188`
`PHP       | 7.0.18`
`MySQL     | 5.5.52-MariaDB`
`RRDTool   | 1.4.8`
`SNMP      | NET-SNMP 5.7.2`

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

[wlc_8510_poller.txt](https://github.com/librenms/librenms/files/972811/wlc_8510_poller.txt)
[wlc_8510_discovery.txt](https://github.com/librenms/librenms/files/974679/wlc_8510_discovery.txt)
[wlc_8510_snmpbulkwalk.txt](https://github.com/librenms/librenms/files/974667/wlc_8510_snmpbulkwalk.txt)

- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Reference https://community.librenms.org/t/improve-wireless-collection-and-graphing-code/453/10

I have a Cisco WLC 8510 and some Siklu EH-600TX on the network which take advantage of the new wireless sensors code.

The Siklu are quite happily now displaying information and graphs for SNR, RSSI , Power/Signal & Frequency after a new discovery run:

  2017-05-02 12:25:20	Wireless Sensor Discovered: power siklu 1 Tx Power
  2017-05-02 12:25:20	Wireless Sensor Discovered: frequency siklu 1 Frequency
  2017-05-02 12:25:19	Wireless Sensor Discovered: snr siklu 1 CINR
  2017-05-02 12:25:19	Wireless Sensor Discovered: rssi siklu 1 RSSI

The Cisco 8510 WLC (running s/w version 8.0.133.0) discovered the individual SSIDs after a discovery run:

  2017-05-02 12:15:02	Wireless Sensor Discovered: clients ciscowlc-ssid 24 SSID: TriathlonScotland
  2017-05-02 12:15:02	Wireless Sensor Discovered: clients ciscowlc-ssid 25 SSID: eduroam
  2017-05-02 12:15:02	Wireless Sensor Discovered: clients ciscowlc-ssid 26 SSID: UoS Wi-Fi Setup
  2017-05-02 12:15:02	Wireless Sensor Discovered: clients ciscowlc-ssid 31 SSID: UoS Guest Internet

Although all the "wireless-sensor-clients-ciscowlc-ssid-nn.rrd" files have been created in /opt/librenms/rrd, the graphs are showing no information (all values NaN)

![clients_total_graph](https://cloud.githubusercontent.com/assets/26296446/25653852/9ed27df8-2fe6-11e7-8921-836596da815d.png)
![clients_ssid_example_graph](https://cloud.githubusercontent.com/assets/26296446/25653851/9ebfec38-2fe6-11e7-98d6-5287d3a9d88b.png)

The original total clients graphs (device_ciscowlc_numclients) still works fine - no problems there.

![device_ciscowlc_numclients_graph](https://cloud.githubusercontent.com/assets/26296446/25653856/a88b947e-2fe6-11e7-9c80-9162c9875a31.png)

All other graphs are also working fine. Let me know if you need anything else, thanks.

**Comment by alanbboyd** [comment]
This may help:

`.1.3.6.1.4.1.14179.2.1.1.1.38.[WLAN ID]` 

gives the client count per SSID e.g.

`.1.3.6.1.4.1.14179.2.1.1.1.2.25 "eduroam"`
`.1.3.6.1.4.1.14179.2.1.1.1.38.25 3670`

HTH

Alan

**Comment by murrant** [comment]
The snmpwalk is missing the required data, you'll need to run this:
`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .1.3.6.1.4.1.14179`

**Comment by alanbboyd** [comment]
rrd files from the WLC 8510 don't have any data in them - all values are "NaN" e.g.:

[wlc_8510_wireless-sensor-clients-ciscowlc-ssid-2.rrd.dump.txt](https://github.com/librenms/librenms/files/974631/wlc_8510_wireless-sensor-clients-ciscowlc-ssid-2.rrd.dump.txt)
[wlc_8510_wireless-sensor-clients-ciscowlc-ssid-17.rrd.dump.txt](https://github.com/librenms/librenms/files/974633/wlc_8510_wireless-sensor-clients-ciscowlc-ssid-17.rrd.dump.txt)
[wlc_8510_wireless-sensor-clients-ciscowlc-ssid-25.rrd.dump.txt](https://github.com/librenms/librenms/files/974634/wlc_8510_wireless-sensor-clients-ciscowlc-ssid-25.rrd.dump.txt)
[wlc_8510_wireless-sensor-clients-ciscowlc-ssid-31.rrd.dump.txt](https://github.com/librenms/librenms/files/974632/wlc_8510_wireless-sensor-clients-ciscowlc-ssid-31.rrd.dump.txt)

Sample RRDTool output from one of the graphs:

```
RRDTool Command
rrdtool graph /tmp/brwkYUBu1STDgjwW  -l 0 -E --start 1493757000 --end 1493843400 --width 1611.9 --height 300 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal COMMENT:'Clients                            Cur    Min    Max\n' DEF:sensor=/data/librenms/rrd/wlc.stir.ac.uk/wireless-sensor-clients-ciscowlc-ssid-25.rrd:sensor:AVERAGE LINE1.5:sensor#0000cc:'SSID\: eduroam                ' AREA:sensor#0000cc55 GPRINT:sensor:LAST:'%5.0lf' GPRINT:sensor:MIN:'%5.0lf' GPRINT:sensor:MAX:'%5.0lf'\l --imgformat=SVG

RRDTool Output
1692x369
OK u:0.05 s:0.02 r:0.06
```

One other thing to note - I've now set up our test/dev WLC 2504, and (although there are no clients on it) it is returning values in both the rrd files and the graph. All zeroes for obvious reasons, but appears to be working, e.g.:

[wlc_2504_wireless-sensor-clients-ciscowlc-ssid-1.rrd.dump.txt](https://github.com/librenms/librenms/files/974638/wlc_2504_wireless-sensor-clients-ciscowlc-ssid-1.rrd.dump.txt)

```
RRDTool Command
rrdtool graph /tmp/EwRoRg2FOdNdEFG9  -l 0 -E --start 1493757600 --end 1493844000 --width 1611.9 --height 300 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal COMMENT:'Clients                            Cur    Min    Max\n' DEF:sensor=/data/librenms/rrd/wlc-test.stir.ac.uk/wireless-sensor-clients-ciscowlc-ssid-2.rrd:sensor:AVERAGE LINE1.5:sensor#0000cc:'SSID\: testwlcnet1            ' AREA:sensor#0000cc55 GPRINT:sensor:LAST:'%5.0lf' GPRINT:sensor:MIN:'%5.0lf' GPRINT:sensor:MAX:'%5.0lf'\l --imgformat=SVG

RRDTool Output
1692x369
OK u:0.04 s:0.01 r:0.04
```

**Comment by alanbboyd** [comment]
And the sanitised output from `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .1.3.6.1.4.1.14179`

[wlc_8510_snmpbulkwalk_14179.txt](https://github.com/librenms/librenms/files/974690/wlc_8510_snmpbulkwalk_14179.txt)

Let me know if you need anything else.

**Comment by murrant** [comment]
@alanbboyd still nothing there.  Try walking just `.1.3.6.1.4.1.14179.2.1.1.1.38`

**Comment by alanbboyd** [comment]
Thanks - file below has walks of: `.1.3.6.1.4.1.14179.2.1.1.1.1`, `.1.3.6.1.4.1.14179.2.1.1.1.2` & `.1.3.6.1.4.1.14179.2.1.1.1.38`, which match up respectively with WLAN ID, WLAN SSID & Client Count

[wlc_8510_snmpbulkwalk_14179.2.1.1.1.txt](https://github.com/librenms/librenms/files/975406/wlc_8510_snmpbulkwalk_14179.2.1.1.1.txt)

**Comment by alanbboyd** [comment]
Some additionaI information: I updated to the latest code this morning (`418d2c8feff5b49597a108e5622c8ee7c528a81c`) and ran manual discovery of the 8510 WLC, which then showed the correct count of Connected APs:

![librenms_418d2c_post_discovery](https://cloud.githubusercontent.com/assets/26296446/25698549/3498f10c-30b7-11e7-90ef-d734dff27731.png)

But then after running a manual poll of the WLC, the Connected AP count dropped to zero:

![librenms_418d2c_post_poller](https://cloud.githubusercontent.com/assets/26296446/25698576/486acf3e-30b7-11e7-89d0-2bb0d6e357a7.png)

Re-running the discovery does not restore the AP count, and the client count remains stubbornly absent... The AP list can still be accessed as previously via `/tab=accesspoints/`

CPU utilisation is working a treat now though, thanks!

**Comment by murrant** [comment]
I wonder if you are having snmprec issues.  Can you post `./poller.php -r -f -m wireless -d -h HOSTNAME`

**Comment by alanbboyd** [comment]
No problem, see below

[wlc_8510_poller_wireless.txt](https://github.com/librenms/librenms/files/975978/wlc_8510_poller_wireless.txt)

**Comment by murrant** [comment]
Next, the output of this sql `SELECT * FROM `wireless_sensors` WHERE `device_id` = '465'`

Thanks for your time btw.

**Comment by alanbboyd** [comment]
There you go:

[wlc_8510_sql_wireless_sensors.txt](https://github.com/librenms/librenms/files/976152/wlc_8510_sql_wireless_sensors.txt)

And thanks, happy to help

**Comment by murrant** [comment]
Found the problem, the oids column is too short!

**Comment by alanbboyd** [comment]
Well spotted! You could also (not unreasonably) argue that I have too many SSIDs...
