### ISSUE TITLE
doc addition needed : selinux + nfs-server

### ISSUE THREAD

**Issue by svennd** [librenms/librenms#6561]
Find out + document how to get selinux to play nice with nfs-server extend.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
Is this something you are tackling @svennd ?

**Comment by svennd** [comment]
Yeah, I seen some people having problems on centos 7 that gets a nasty bug : doing a cat on a /proc files is not permitted by an automated proces. (snmpd) mostly its selinux that blocks it, I want to add it to the docs but i just took the quick route and disabled selinux ...

**Comment by f0o** [comment]
audit2why and audit2allow help out. if you need to create a policy file, please paste the plaintext policy and I'll make one for upstream centos7 and include it in the repo

**Comment by svennd** [comment]
Ok, I don't have time + knowledge to fix this, sorry. I disabled selinux, that being the solution for me. That's pretty bad general advice tho. I think snmpd should not normally read from /proc/net/rpc/nfsd and that is why selinux is complaining. I don't know how to write this exception.

But since already two people asked for support, it would be nice if someone could give decent advice.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/update-docs-needed-selinux-nfs-server/1230
