### ISSUE TITLE
API call returns incomplete list of Catalyst C29xx Stack switches

### ISSUE THREAD

**Issue by rkutsel** [librenms/librenms#6570]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
==========================================================
Component | Version
--------- | -------
LibreNMS  | 72a0d8202aa15e4474ae95a904b076c6e5f151e7
DB Schema | 187
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.55-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

I initially posted a feature request but after doing a little bit of digging I'm convinced that this is a bug so API **get_inventory** function works fine as long as the entPhysicalContainedIn="0" which is not the case with cisco stack switches. entPhysicalContainedIn is set to be "1" instead. On a separate note I'm not sure if the following statement needs to be there in the first place as it doesn't seem to have any meaningful effect on the output whatsoever. 
`if (isset($_GET['entPhysicalClass']) && !empty($_GET['entPhysicalClass'])) {
        $sql     .= ' AND entPhysicalClass=?';
        $params[] = mres($_GET['entPhysicalClass']);
    }`

**Comment by rkutsel** [comment]
That's interesting when I remove this portion from the function **get_inventory()**
`    if (isset($_GET['entPhysicalClass']) && !empty($_GET['entPhysicalClass'])) {
        $sql     .= ' AND entPhysicalClass=?';
        $params[] = mres($_GET['entPhysicalClass']);
    }

    if (isset($_GET['entPhysicalContainedIn']) && !empty($_GET['entPhysicalContainedIn'])) {
        $sql     .= ' AND entPhysicalContainedIn=?';
        $params[] = mres($_GET['entPhysicalContainedIn']);
    } else {
        $sql .= ' AND entPhysicalContainedIn="0"';
    }`

I kinda get what I want to see except now I see extra fields for network ports for cisco. For Juniper though, there's no problem at all, still produces the same output.

**Comment by laf** [comment]
You need to pass entPhysicalContainedIn=1 to your API call to make use of the code.

Until this is confirmed as a bug please discuss on irc or the community site.
