### ISSUE TITLE
Device Support: Cisco Integrated Management Controller: Version: 1.5(9d)

### ISSUE THREAD

**Issue by guoming218** [librenms/librenms#6576]
Hi,

Kindly help to look at this version of CIMC on the cisco C260, its not polling properly
hope the info I provided is enough.

Thank you very much.
Rgds,
guoming

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the ==========================================================
Component | Version
--------- | -------
LibreNMS  | 1187d92351f2f56f11a2b8200e4bef10610ec01a
DB Schema | 189
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.54-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================
section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
[CIMC Ver1.5(9d) discovery.txt](https://github.com/librenms/librenms/files/975300/CIMC.Ver1.5.9d.discovery.txt)
[CIMC Ver1.5(9d) poller.txt](https://github.com/librenms/librenms/files/975301/CIMC.Ver1.5.9d.poller.txt)
[CIMC Ver1.5(9d) SNMPWalk.txt](https://github.com/librenms/librenms/files/975302/CIMC.Ver1.5.9d.SNMPWalk.txt)
- [x] Please provide as much detail as possible.
CIMC on libreNMS are not polling correctly.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
This is being detected as cimc, what's the problem you have?

**Comment by laf** [comment]
The snmp walk itself doesn't even contain things like interface details so either the walk isn't complete or your device genuinely isn't sending the data back, maybe you are using snmp views to restrict what info does get sent back.
