### ISSUE TITLE
Device Support: AEG UPS - Generex UPS SNMP adapter 

### ISSUE THREAD

**Issue by guoming218** [librenms/librenms#6577]
Hi,

Kindly help to look at AEG UPS - Generex UPS SNMP adapter , its not polling properly for some of the information, just updated the version to the Latest version:	5.60
hope the info I provided is enough.

Thank you very much.
Rgds,
guoming

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the ==========================================================
Component | Version
--------- | -------
LibreNMS  | 418d2c8feff5b49597a108e5622c8ee7c528a81c
DB Schema | 189
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.54-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================
 section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
[AEG UPS - Generex UPS SNMP adapter discovery.txt](https://github.com/librenms/librenms/files/975498/AEG.UPS.-.Generex.UPS.SNMP.adapter.discovery.txt)
[AEG UPS - Generex UPS SNMP adapter poller.txt](https://github.com/librenms/librenms/files/975499/AEG.UPS.-.Generex.UPS.SNMP.adapter.poller.txt)
[AEG UPS - Generex UPS SNMP adapter SNMPwalk.txt](https://github.com/librenms/librenms/files/975497/AEG.UPS.-.Generex.UPS.SNMP.adapter.SNMPwalk.txt)
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
What does "it's not polling properly for some of the information" mean?

**Comment by guoming218** [comment]
Hi Laf,

It does not poll any health status, in fact, it actually does not have health tab too.

Picture as shown.

![image](https://cloud.githubusercontent.com/assets/24470844/25699808/5d5bb5da-30f7-11e7-9ca3-e4b8f0db46d3.png)

rgds
guoming

**Comment by FTBZ** [comment]
When you're using the Generex web interface, the dashboard is returning all the needed information?

**Comment by guoming218** [comment]
Nope, the dashboard does not return all information, Eg: Battery charge, Voltage, Current, Load, Power, Frequency and State.

**Comment by guoming218** [comment]
Those that i listed out does show those info

**Comment by FTBZ** [comment]
Mhh discovery seems correct, but the poller isn't polling the discovered RFC sensors 🤔

**Comment by laf** [comment]
You have something weird going on with your install. The snmpwalk you've provided has the info and is detected fine.

For you, discovery is finding the sensors and trying to add them, poller is showing that this didn't happen. As this isn't a bug or new device please use either the community site or irc for help.

Try running this in mysql `INSERT INTO `sensors` (`poller_type`,`sensor_class`,`device_id`,`sensor_oid`,`sensor_index`,`sensor_type`,`sensor_descr`,`sensor_divisor`,`sensor_multiplier`,`sensor_limit`,`sensor_current`)  VALUES ('snmp','current','355','.1.3.6.1.2.1.33.1.2.6.0','500','rfc1628','Battery','10','1','0','0');`
