### ISSUE TITLE
pbin.sh throws error

### ISSUE THREAD

**Issue by olivierbeytrison** [librenms/librenms#6579]
pbin.sh is not happy whith the ```[[ ]]``` tests.
switching to /bin/bash solves the issue.

```
Paste endpoint: https://p.libren.ms/api/create
./pbin.sh: 33: ./pbin.sh: [[: not found
./pbin.sh: 37: ./pbin.sh: [[: not found
```

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | bdf1616c76797e9accc0e96d4c28e971d71cfefe
DB Schema | 189
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

**Comment by murrant** [comment]
What shell + version are you using?

**Comment by olivierbeytrison** [comment]
```/bin/sh``` comes from the ```dash``` package on ubuntu 16 (it's a standard install from 16.04 LTS)

```
# dpkg -S /bin/sh
diversion by dash from: /bin/sh
diversion by dash to: /bin/sh.distrib
dash: /bin/sh
```

**Comment by laf** [comment]
Does `#!/usr/bin/env bash` work for you?

**Comment by olivierbeytrison** [comment]
Yep it works ! Thanks
