### ISSUE TITLE
Support for interfaces with "virtual" in the description

### ISSUE THREAD

**Issue by swolski** [librenms/librenms#6581]
The issue was identified when noticing that eth0/1 and eth0/2 on an Adtran 908e were not populating into the ports table due to their description containing the word "Virtual".

functions.php (line 1012-1013) appears to be the culprit since it marks all ports with "irtual" as invalid (with the exception provided for Avaya VSP ports).
```
   } elseif (strstr($port['ifDescr'], "irtual") && strpos($port['ifDescr'], "Virtual Services Platform") === false) {
        $valid = 0;
```
Additional details attached and in the comments.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
==========================================================
Component | Version
--------- | -------
LibreNMS  | bdf1616c76797e9accc0e96d4c28e971d71cfefe
DB Schema | 189
PHP       | 5.5.9-1ubuntu4.21
MySQL     | 5.5.55-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2
==========================================================
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

[librenms-issue-20170504-mysql-output.txt](https://github.com/librenms/librenms/files/976953/librenms-issue-20170504-mysql-output.txt)
[librenms-issue-20170504-discovery-ports-output.txt](https://github.com/librenms/librenms/files/976946/librenms-issue-20170504-discovery-ports-output.txt)

- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by swolski** [comment]
From the discovery:
```
SNMP[/usr/bin/snmpbulkwalk -v3 -n '' -l 'authPriv' -a 'SHA' -A '<scrubbed>' -u 'snmpuser' -x 'DES' -X '<scrubbed>' -OQUs -m IF-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/adtran udp:HOSTNAME:161 ifDescr]
SNMP[/usr/bin/snmpbulkwalk -v3 -n '' -l 'authPriv' -a 'SHA' -A '<scrubbed>' -u 'snmpuser' -x 'DES' -X '<scrubbed>' -OQUs -m IF-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/adtran udp:HOSTNAME:161 ifDescr]
ifDescr.1 = t1 0/1: DS1 Driver (QuadFalc56)
ifDescr.2 = t1 0/2: DS1 Driver (QuadFalc56)
ifDescr.3 = t1 0/3: DS1 Driver (QuadFalc56)
ifDescr.4 = t1 0/4: DS1 Driver (QuadFalc56)
ifDescr.5 = fxo 0/0: FXO
ifDescr.6 = eth 0/1: MAC:PQIII EtsecBasedVirtualEthernet1
ifDescr.7 = eth 0/2: MAC:PQIII EtsecBasedVirtualEthernet1
ifDescr.8 = fxs 0/1: FXS
ifDescr.9 = fxs 0/2: FXS
ifDescr.10 = fxs 0/3: FXS
ifDescr.11 = fxs 0/4: FXS
ifDescr.12 = fxs 0/5: FXS
ifDescr.13 = fxs 0/6: FXS
ifDescr.14 = fxs 0/7: FXS
ifDescr.15 = fxs 0/8: FXS
ifDescr.16 = giga-eth 0/1: MAC:PQIII TSEC1
ifDescr.17 = eth 0/2.20: Ethernet 802.1q Subinterface
ifDescr.18 = ISDN primary-rate interface 1
ifDescr.19 = ppp 1
```

Following suit with the Avaya exception, appending an exception to the "irtual" check in functions.php for this specific case would help out for this specific type of interface:
`&& strpos($port['ifDescr'], "EtsecBasedVirtualEthernet1") === false`

Moving the exceptions to a modifiable configuration might be a more generic improvement if there are other cases like this, but would obviously involve a bit more effort.

**Comment by laf** [comment]
Please test the linked pull request. It already contains the good_if value for this os you need.

**Comment by swolski** [comment]
I just tested it and the change appears to work great.  Thanks for looking at this so quickly!!
