### ISSUE TITLE
rocket.chat alerting does not work/unclear docs ?

### ISSUE THREAD

**Issue by svennd** [librenms/librenms#6588]
I tried to follow the [docs](http://docs.librenms.org/Extensions/Alerting/#rocketchat) but that doesn't seem right. I get the error "You must be logged in to do this.".
So instead of the : 
https://rocket.url/api/v1/chat.postMessage
I used : (its longer)
https://myurl/hooks/aNzyr[...]5/z2GJ3A[...]7yxa

This includes both the auth key and login. However when I use that, the message is not shown, as I pointed out in this pull : https://github.com/librenms/librenms/pull/6281

I get this in a alert.php -d debug run : 
https://pastebin.com/65a7b7i8
I see a empty message popping up;

Currently I am using :  0.55.0-rc.3  (which is slightly outdated)
I have 1 incoming webhook integration to post to 1 channel as a user; with this script : 
```class Script {
  process_incoming_request({ request }) {
    // request.url.hash
    // request.url.search
    // request.url.query
    // request.url.pathname
    // request.url.path
    // request.url_raw
    // request.url_params
    // request.headers
    // request.user._id
    // request.user.name
    // request.user.username
    // request.content_raw
    // request.content

    // console is a global helper to improve debug
    console.log(request.content);

    return {
      content:{
        text: request.content.text
       }
    };

    return {
       error: {
         success: false,
         message: 'Error example'
       }
     };
  }
}
```
Please advice, @ToeiRei since you seem the dev, and its working on your end.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by ToeiRei** [comment]
@svennd the 'rocket URL'  needs to be the "Webhook URL" from your rocket.chat incoming webhook.

Mind providing me a brief run down on your rocket chat webhook config?
In my case I do not use scripting.

**Comment by svennd** [comment]
Ok the webhook URL is correct. As I expected. Thx!

As to my settings of the incoming webhook integration : 
enabled : true
name : God (reall user)
Post to channel : #server-info 
Post as : God
Alias : (unset)
Avatar (unset)
Emoji (unset)
Script Enabled : false (for now)
Script : (see initial post)
Webhook URL : https://my.url/hooks/aNzyrLFx6H2nwdrM5/z2GJ3AfwvFfDpE3W4P3mJT3gtexbYDgxNZSdrNEex4oy7yxa
Token : aNzyrLFx6H2nwdrM5/z2GJ3AfwvFfDpE3W4P3mJT3gtexbYDgxNZSdrNEex4oy7yxa

**Comment by svennd** [comment]
```
 api => string(23) "API 'v0' returned Error"
string(8) "Params: "
string(8) "Return: "
ERROR: HTTP Status code 0
```

mmm, I don't know what I changed, but now the messages do pop-up :/  I do get the above error, but the messages come true now, thx for looking @ToeiRei !

**Comment by ToeiRei** [comment]
As you're running some -RC version I would suspect some bugs not being ironed out. I skimmed the changelog and it seems like something in the APIs was changed/fixed

**Comment by svennd** [comment]
Are you running 0.55.1 ?

**Comment by ToeiRei** [comment]
yes.

**Comment by svennd** [comment]
oke invalid issue :) thx @ToeiRei !
