### ISSUE TITLE
Cisco WLC Graphing Issue for APs and Clients

### ISSUE THREAD

**Issue by network-guy** [librenms/librenms#6591]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

==========================================================
Component | Version
--------- | -------
LibreNMS  | ef3a163db8eea78f8aef6f8fd8889595d6fe97e3
DB Schema | 190
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

[OK]    Database connection successful
[OK]    Database schema correct

It seems a recent pull request (maybe the wireless overhaul) has broken the AP and client count graphs for my Cisco WLC. The graphs in the top right for clients and APs used to work but now displays zero clients and doesn't have any info for AP counts. Additionally, the new "Wireless" menus also show zero clients total and for each SSID.

The individual access points graphs appear unaffected.

Tagging @murrant since he's made most of the wireless changes lately.

**Comment by laf** [comment]
You really need to provide the info we ask for at the top.

**Comment by network-guy** [comment]
<a href="https://gist.github.com/network-guy/94e8c97984073809ea087f805ee1e3a7.js">Poller Data</a>
<a href="https://gist.github.com/network-guy/844f20a5580763f01e5fdb13dc5db0e3.js">Discovery Data</a>
<a href="https://gist.github.com/network-guy/23e4fcc84161ff15949a2440ba2c1072.jss">SNMPwalk</a>

SNMPbulkwalk kept timing out part way through so I did a full SNMP walk. That could be some of the issue. I don't know if that worked properly before or not though.

**Comment by murrant** [comment]
@network-guy The linked files don't appear to contain the intended data.

**Comment by murrant** [comment]
Looks like schema 190 did not get applied properly.
Can you run `./validate.php` and post the output of that?

**Comment by murrant** [comment]
Likely, just running `` ALTER TABLE `wireless_sensors` MODIFY `sensor_oids` TEXT NOT NULL; `` (190.sql) will fix this

**Comment by network-guy** [comment]
Looks like the schema update applied correctly. Here's the output from validate.php:

==========================================================
Component | Version
--------- | -------
LibreNMS  | ef3a163db8eea78f8aef6f8fd8889595d6fe97e3
DB Schema | 190
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

[WARN]  Your install is out of date, last update: Fri, 05 May 2017 14:46:00 +0000
[OK]    Database connection successful
[OK]    Database schema correct

The sensor_oids column appears to be correct too, before running your SQL alter command. And there is data in the sensor_oids column and for the correct device.

| Field                     | Type             | Null | Key | Default           | Extra          |
+---------------------------+------------------+------+-----+-------------------+----------------+
| sensor_oids               | text             | NO   |     | NULL              |                |

MariaDB [librenms]> ALTER TABLE `wireless_sensors` MODIFY `sensor_oids` TEXT NOT NULL;
Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

**Comment by murrant** [comment]
In that case run `` UPDATE `wireless_sensors` set `sensor_oids` ='[\".1.3.6.1.4.1.14179.2.1.1.1.38.1\",\".1.3.6.1.4.1.14179.2.1.1.1.38.2\",\".1.3.6.1.4.1.14179.2.1.1.1.38.3\",\".1.3.6.1.4.1.14179.2.1.1.1.38.4\",\".1.3.6.1.4.1.14179.2.1.1.1.38.5\",\".1.3.6.1.4.1.14179.2.1.1.1.38.6\",\".1.3.6.1.4.1.14179.2.1.1.1.38.7\",\".1.3.6.1.4.1.14179.2.1.1.1.38.17\",\".1.3.6.1.4.1.14179.2.1.1.1.38.18\",\".1.3.6.1.4.1.14179.2.1.1.1.38.19\",\".1.3.6.1.4.1.14179.2.1.1.1.38.20\"]' WHERE `sensor_id`='12' ``

And tell me if you get an error.

Also, run `` SELECT `sensor_oids` FROM `wireless_sensors` WHERE `sensor_id`='12' ``  and make sure the oids match.

**Comment by network-guy** [comment]
Nothing changed on that update.

MariaDB [librenms]> UPDATE `wireless_sensors` set `sensor_oids` ='[\".1.3.6.1.4.1.14179.2.1.1.1.38.1\",\".1.3.6.1.4.1.14179.2.1.1.1.38.2\",\".1.3.6.1.4.1.14179.2.1.1.1.38.3\",\".1.3.6.1.4.1.14179.2.1.1.1.38.4\",\".1.3.6.1.4.1.14179.2.1.1.1.38.5\",\".1.3.6.1.4.1.14179.2.1.1.1.38.6\",\".1.3.6.1.4.1.14179.2.1.1.1.38.7\",\".1.3.6.1.4.1.14179.2.1.1.1.38.17\",\".1.3.6.1.4.1.14179.2.1.1.1.38.18\",\".1.3.6.1.4.1.14179.2.1.1.1.38.19\",\".1.3.6.1.4.1.14179.2.1.1.1.38.20\"]' WHERE `sensor_id`='12';
Query OK, 0 rows affected (0.00 sec)
Rows matched: 1  Changed: 0  Warnings: 0

Actually, just checked and it started working now. I'm not sure what the resolution was, but I'll take the win.

**Comment by murrant** [comment]
I'm guessing the discover you ran for debug earlier updated the value in the db.  Even though the database schema changed, the oids value wouldn't have been fixed until discovery was run.
