### ISSUE TITLE
Temperature info missing from BladeSystem c7000 after librenms update.

### ISSUE THREAD

**Issue by ebym** [librenms/librenms#6599]
DO NOT DELETE THIS INFORMATION.

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? 
- [x] Please include all of the information between the 
Component | Version
--------- | -------
LibreNMS  | acaa29c583049ba31937e40e2b339bbc6851dab7
DB Schema | 190
PHP       | 5.4.45-2+deb.sury.org~precise+2
MySQL     | 5.5.46-0ubuntu0.12.04.2
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.4.3

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.

Temperature info from BladeSystem c7000 Enclosure missing after updating to DB 190 schema from DB 147.

However librenms is still pulling Temperature info for BladeSystem c3000 Enclosure !!!.
Both devices have the same Poller and Discovery Modules enabled.

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Thanks,

**Comment by laf** [comment]
No information provided that we ask for.

**Comment by FTBZ** [comment]
Didn't noticed problems on my side:

<img width="1221" alt="screen shot 2017-05-07 at 14 42 11" src="https://cloud.githubusercontent.com/assets/1927109/25781017/6af89e36-3333-11e7-8bd3-3bec4b79504e.png">

**Comment by ebym** [comment]
I even deleted and added c7000 after an hour, still same problem. Temperature info not pulled. This worked on previous version (db schema 147).

./discovery.php
https://p.libren.ms/view/5e06d8e6

./poller.php
https://p.libren.ms/view/7433f11e

snmpbulkwalk
https://p.libren.ms/view/d7dc3ecf

**Comment by ebym** [comment]
I even deleted and added c7000 after an hour, still same problem. Temperature info not pulled. This worked on previous version (db schema 147).

./discovery.php
https://p.libren.ms/view/5e06d8e6

./poller.php
https://p.libren.ms/view/a4f9dbdb

snmpbulkwalk
https://p.libren.ms/view/55fac83d

Note: removed confidential data from snmpbulkwalk

**Comment by FTBZ** [comment]
You're OA isn't responding with the correct information for the temperature. You're discovery try to get temp data from the card, and it's seems not available:

> Temperature: SNMP[[0;36m/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Osqn -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.232.22.2.3.1.2.1.5[0m]
.*.*.*.1.5 **No Such Instance currently exists at this OID**

I checked on two of my c7000 (Gen 3) and it's working fine. You're poller extraction isn't working, but your snmpbulkwalk shows that you're using a very old OA firmware (3.55 - 27 Mar 2012). The latest supported version include in HPE SPP is 4.60, but I'm not 100% sure that the OA card were the same between the c7000 revision.

**Comment by ebym** [comment]
Earlier this was working for c7000 with same firmware(3.55) till i updated librenms. Temperature info for c3000 with firmware(3.70) is working on both versions !!!. I'm baffled why it isn't working now(db schema 190) on c7000.

On blade cli and web console,  temp, fan, psu, cpu, mem info are showing properly. I'll check if nagios is able to pull these, if so, the problem is not with OA firmware.

**Comment by laf** [comment]
Your snmpwalk doesn't show any data from .1.3.6.1.4.1.232.22.2.3.1.2 range, looking at the code, we've always looked up data from that range so I'm not sure it's a change on our side. The code was changed 9 months ago but that was before schema 147 was available.

**Comment by laf** [comment]
This doesn't seem to be an issue within LibreNMS. If you can provide any further evidence it is then we can re-open and continue looking at it.
