### ISSUE TITLE
Unix Agent on non-Unix OSes

### ISSUE THREAD

**Issue by tulach** [librenms/librenms#6617]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hello,
the original Check_MK agent is available also on Windows platform (see http://mathias-kettner.de/checkmk_windows.html). It works but cannot be used in combination with LibreNMS. This is because of os_group check in librenms/includes/polling/unix-agent.inc.php file.

Could you please consider if it is possible to remove the os_group check?
if ($device['os_group'] == 'unix') ...

Regards

Jiri Tulach

**Comment by laf** [comment]
I doubt it's as simple as that, none of our code is written for non-windows. However github is for bugs / new devices, please post on the community site.

**Comment by tulach** [comment]
That's why I've posted it here. Who else then developers could tell if it is safe? The fact I've managed it working by one hour and successfully monitor MySQL server on Windows doesn't proof anything. And I'm not the one who knows LibreNMS code so well to propose the change. What is the point to post it on community site? Are there more skilled developers to tell if it is a safe change?

**Comment by tulach** [comment]
Could someone please re-open the issue? It seems the "laf" reaction is against what is written here: http://docs.librenms.org/Support/FAQ/#faq20
I just want to solve the issue and not argue with vague statements (i.e. not simple, non-windows code).

**Comment by laf** [comment]
That FAQ is out of date and needs updating, as per the text though at the top when you create an issue this is for bugs and new device support. The community forum is to discuss feature requests, changes and asking for help.

You can of course submit the fix if you like.

**Comment by tulach** [comment]
If you want an issue, here it is:
The unix-agent is not connecting to a device. Module unix-agent is enabled and no tcp connection to a device is made.

**Comment by laf** [comment]
That's not a bug, that's you have issues with something and the community forums is where you should post.

**Comment by tulach** [comment]
It's a bug. I know it because I proposed the fix and the fix is written in my first post. I wanted to discuss the change which is not happening. I'm trying to make LibreNMS better. You are trying to ... what? Piss off contributors? Great. You win. Happy?

**Comment by laf** [comment]
I'm really unsure how much clearer I can be here, github is not for discussing proposed changes - unless you submit the change. It's for reporting bugs (which this is not) or request new device support (which this is not). I've directed you to where you should post this but you seem to not want to do so.

I'm locking this issue now as it's serving no purpose other than wasting both of our time.
