### ISSUE TITLE
Discovery Resets custom values.

### ISSUE THREAD

**Issue by kkrumm1** [librenms/librenms#6618]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `
==========================================================
Component | Version
--------- | -------
LibreNMS  | b0c1885d731edc7f129072fb19f3d48c88cc4d5c
DB Schema | 190
PHP       | 7.0.18
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful
[OK]    Database schema correct

section of `./validate.php` which you can run from the cli.

- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery resets custom values on devices back "0" on Highs and Lows.

**Comment by laf** [comment]
I've just tested and this doesn't happen for me. 

Please change the high / low for a device, show the screenshot and then run `./discovery.php -h HOSTNAME -v -m sensors` and upload it to pastebin or p.libren.ms

**Comment by kkrumm1** [comment]
https://p.libren.ms/view/be56e284
![image](https://cloud.githubusercontent.com/assets/27959419/26038221/e593cb44-38c8-11e7-9f36-f8893d018956.png)

**Comment by laf** [comment]
You used an uppercase V rather than lower. However change that for a -d and re-run

**Comment by kkrumm1** [comment]
https://p.libren.ms/view/42d1ead7

Sorry about that. 

you know Laf if hasn't done it since last week. So I'm not sure what is going now. I don't want to waste your time.

**Comment by laf** [comment]
Can we close then? Your output confirms this isn't happening so I'm not sure what went on for you before.

**Comment by kkrumm1** [comment]
Yes go ahead and close it. Thank you so much for your help.
