### ISSUE TITLE
broken graphs for cisco ws3650

### ISSUE THREAD

**Issue by papage** [librenms/librenms#6627]
Hi all,

After an update in librenms, the graphs for the two cisco ws3650 I have, don't look very good. There is some problem when reading the bytes counters o the switch. This problem exists only for the 3650 and not for the other devices I have.

See the attached graph. If you need more details and debugging, plz tell me what you need, to resolve this. Keep in mind that I had not update librenms for quite some time and after an update last week, the problem appeared. 

Thanx
Spiros

![badgraph](https://cloud.githubusercontent.com/assets/6276532/25895576/276b2546-3589-11e7-88af-904e9481a384.png)

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
Duplicate https://github.com/librenms/librenms/issues/6372
