### ISSUE TITLE
RRD files no longer created on device rrd folder.

### ISSUE THREAD

**Issue by monty2kx** [librenms/librenms#6629]
Hi everyone,

Since an update, (but i don't know which), RRD files are not longer created in _/opt/librenms/rrd/<device>_ folder and graph are in "Error Drawing Graph' on the web UI.

I have suspected a right issue on the rrd folder, but evrything seems to be ok.
This folder is owned by librenms user and group. 
The http user is also in librenms group.

This problem concern only devices added recently. All the old devices are updated correctly.
On the rrd/ folder, a folder is created with the device name, but nothing is created inside.

If I run a : _./poller.php -h cbv-pa7-a9k1-pe-01 -r -f -d_ 

In the output I see lines like

```
uptime netstat_ip netstat_ip_frag netstat_tcp netstat_udp netstat_icmp netstat_icmp_info netstat_snmp netstat_snmp_pkt netstat_ip_forward ipsystemstats_ipv6 ipsystemstats_ipv6_frag RRD[create /opt/librenms/rrd/cisco-a9k1/poller-perf.rrd --step  DS:poller:GAUGE::0:U  RRA:AVERAGE:0.5:1:2016 RRA:AVERAGE:0.5:6:1440 RRA:AVERAGE:0.5:24:1440 RRA:AVERAGE:0.5:288:1440  RRA:MIN:0.5:1:720 RRA:MIN:0.5:6:1440     RRA:MIN:0.5:24:775     RRA:MIN:0.5:288:797  RRA:MAX:0.5:1:720 RRA:MAX:0.5:6:1440     RRA:MAX:0.5:24:775     RRA:MAX:0.5:288:797  RRA:LAST:0.5:1:1440 ]
[RRD Disabled]RRD[update /opt/librenms/rrd/cisco-a9k1/poller-perf.rrd N:121.8]
[RRD Disabled]RRD[create /opt/librenms/rrd/cisco-a9k1/ping-perf.rrd --step  DS:ping:GAUGE::0:65535  RRA:AVERAGE:0.5:1:2016 RRA:AVERAGE:0.5:6:1440 RRA:AVERAGE:0.5:24:1440 RRA:AVERAGE:0.5:288:1440  RRA:MIN:0.5:1:720 RRA:MIN:0.5:6:1440     RRA:MIN:0.5:24:775     RRA:MIN:0.5:288:797  RRA:MAX:0.5:1:720 RRA:MAX:0.5:6:1440     RRA:MAX:0.5:24:775     RRA:MAX:0.5:288:797  RRA:LAST:0.5:1:1440 ]
[RRD Disabled]RRD[update /opt/librenms/rrd/cisco-a9k1/ping-perf.rrd N:1.52]
[RRD Disabled]Polled in 121.8 seconds
```

I don't know how understand the RRD Disabled line.
It say : _create /opt/librenms/rrd/cisco-a9k1/poller-perf.rrd but nothing is created._

If I take the RRD file of an other (similar) device, and copy it to empty folder, the corresponding graph works.

Thank a lot for your advices

Output of validate.php on Debian 8 amd64

Component | Version
--------- | -------
LibreNMS  | b6e18db766bf15bf576d95d569d260c106efbdf6
DB Schema | 190
PHP       | 5.6.30-0+deb8u1
MySQL     | 10.0.30-MariaDB-0+deb8u2
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
Github is for bugs and new devices, please post this on our irc channel or the community site.

**Comment by monty2kx** [comment]
This problem occur after a daily.sh run and with devices created after this update... It can't be consider as a potential bug ?
