### ISSUE TITLE
Please add Cisco SCE 8000 . 

### ISSUE THREAD

**Issue by roysbike** [librenms/librenms#6630]
valide.php problem.

#php -v 
PHP 7.1.4-1+deb.sury.org~trusty+1 (cli) (built: Apr 11 2017 22:45:20) ( NTS )

```
# ./validate.php 
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /mnt/raid10/librenms/includes/common.php:1089
Stack trace:
#0 /mnt/raid10/librenms/validate.php(83): version_info()
#1 {main}
  thrown in /mnt/raid10/librenms/includes/common.php on line 1089

```

https://p.libren.ms/view/3b00fd1f

<img width="1673" alt="2017-05-10 23 20 44" src="https://cloud.githubusercontent.com/assets/2388223/25919404/589169a2-35d7-11e7-8dae-811a67dea0ba.png">

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
You need to provide all the information in point 3!

Also, install php-curl

**Comment by roysbike** [comment]
I installing. But not help. 
https://p.libren.ms/view/047a0be9
