### ISSUE TITLE
Issue running "Post DB Collation/CharacterSet update fixes"

### ISSUE THREAD

**Issue by thejimmahknows** [librenms/librenms#6634]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
Re-running /opt/librenms/daily.sh as librenms user
Updating to latest codebase                        OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK

- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
:/opt/librenms# ./validate.php 
==========================================================
Component | Version
--------- | -------
LibreNMS  | cbb67b35d67b11f44735c70897a15296495f882f
DB Schema | 190
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.54-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

[OK]    Database connection successful
[FAIL]  MySQL column collation is wrong:  [FIX] https://t.libren.ms/-zdwk
	 syslog facility utf8 utf8_general_ci
	 syslog priority utf8 utf8_general_ci
	 syslog level utf8 utf8_general_ci
	 syslog tag utf8 utf8_general_ci
	 syslog program utf8 utf8_general_ci
	 syslog msg utf8 utf8_general_ci
[OK]    Database schema correct

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
N/A
- [x] Please provide as much detail as possible.
Running suggested fix from  [FIX] https://t.libren.ms/-zdwk I recieve
 mysql -p -u librenms librenms < /opt/librenms/sql-schema/171.sql
Enter password: 
ERROR 1054 (42S22) at line 148: Unknown column 'twofactor' in 'users'

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
Please post on irc or community site. GitHub is not for support.

**Comment by laf** [comment]
Please post on irc or community site. GitHub is not for support.
