### ISSUE TITLE
LLDP port mismatches on Mellanox

### ISSUE THREAD

**Issue by electriceel1985** [librenms/librenms#6635]
EDIT: LLDP information shown on Mellanox switch is incorrect and does not match what we see when using command line lldp or snmp query tools. We have confirmed that this only happens on our MX OS switches and LLDP information in LibreNMS is correct on our Cisco and Cumulus switches.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

#########

./validate.php output:

Component | Version
--------- | -------
LibreNMS  | 528a14995a91187c39990902c0a2322966afad59
DB Schema | 190
PHP       | 5.4.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

Files (redacted) attached include:
config.php.redacted
librenms_support_info_redacted.txt (contains requested info from FAQ)
lldpcli_output_redacted.txt
map_image.png
neighbors_screen.png

[config.php.redacted.txt](https://github.com/librenms/librenms/files/993952/config.php.redacted.txt)
[librenms_support_discovery_redacted.txt](https://github.com/librenms/librenms/files/994069/librenms_support_discovery_redacted.txt)
[librenms_support_poller_redacted.txt](https://github.com/librenms/librenms/files/994070/librenms_support_poller_redacted.txt)
[snmpbulkwalk_redacted.txt](https://github.com/librenms/librenms/files/994068/snmpbulkwalk_redacted.txt)
[lldpcli_output_redacted.txt](https://github.com/librenms/librenms/files/993943/lldpcli_output_redacted.txt)
![map_image](https://cloud.githubusercontent.com/assets/3903631/25963792/979125f6-3650-11e7-9b48-27f87cada7b6.png)
![neighbors_screen](https://cloud.githubusercontent.com/assets/3903631/25963791/978dfda4-3650-11e7-8295-50a28cdb878b.png)

**Comment by laf** [comment]
1. Can you split the output we need into three files. 

2. Please provide some actual information on the issue

**Comment by electriceel1985** [comment]
Apologies for the lack of info. Reattached split files to main ticket.

As for the actual issue, if you check out the lldpcli_output_redacted.txt file, and compare the information therein with the map and neighbors screenshots for devices rctor-q[26-28]-[ab], you'll find that the lldp command line utilities don't agree with LibreNMS's understanding of the topology.

The switch in question is the device called 375-rescomp-core-01, which is a Mellanox 1710.

**Comment by laf** [comment]
Can you provide an snmpwalk from a device this one is connected to so we can simulate the setup

**Comment by laf** [comment]
No further information provided.
