### ISSUE TITLE
Support for Cisco cable-modems (EPC3925, EPC3940L)

### ISSUE THREAD

**Issue by jjonssondk** [librenms/librenms#6639]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X ] Please provide as much detail as possible.
- [X ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

```
root@librenms:/opt/librenms# ./discovery.php -h 172.16.254.10 -d | ./pbin.sh
Paste endpoint: https://p.libren.ms/api/create
ifStackStatus: Unknown Object Identifier (Sub-id not found: (top) -> ifStackStatus)
title:
name: root
private: 1
expire: 0
        https://p.libren.ms/view/8a632469
root@librenms:/opt/librenms# ./poller.php -h 172.16.254.10 -r -f -d | ./pbin.sh
Paste endpoint: https://p.libren.ms/api/create
title:
name: root
private: 1
expire: 0
        https://p.libren.ms/view/f0566fb5
root@librenms:/opt/librenms# snmpbulkwalk -OUneb -v2c -c public 172.16.254.10 .  | ./pbin.sh
Paste endpoint: https://p.libren.ms/api/create
title:
name: root
private: 1
expire: 0
        https://p.libren.ms/view/1cc8f5ee

```

root@librenms:/opt/librenms# ./validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | 0338734fe782216c128ee745a8bdea90eff187cd
DB Schema | 190
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.55-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

[OK]    Database connection successful
[FAIL]  Database: incorrect column (dbSchema/version)
[FAIL]  Database: missing index (dbSchema/PRIMARY)
[FAIL]  Database: missing column (users/remember_token)
[FAIL]  Database: missing column (users/updated_at)
[FAIL]  We have detected that your database schema may be wrong, please report the following to us on IRC or the community site (https://t.libren.ms/5gscd):
         ALTER TABLE `dbSchema` CHANGE `version` `version` int(11) NOT NULL DEFAULT '0';
         ALTER TABLE `dbSchema` ADD PRIMARY KEY (`version`);
         ALTER TABLE `users` ADD `remember_token` varchar(100) NULL AFTER `realname`;
         ALTER TABLE `users` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `remember_token`;

**Comment by jjonssondk** [comment]
https://www.dropbox.com/sh/1n7bzr14k0pth1o/AAD8dxgIAcRyxCXuWMKv5S_ta?dl=0

MIB files for at least the following cable-modems and probably some more:

EPC3949A
DPC3940L
EPC3940L
EPC3940A

**Comment by jjonssondk** [comment]
root@librenms:/opt/librenms# ./validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | c6882129e8db9fa2388988f9d501c91a0b1a4fce
DB Schema | 192
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.55-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

[OK]    Database connection successful
[OK]    Database schema correct

**Comment by jjonssondk** [comment]
https://ibb.co/cHL6ha

These values are those that are the most interesting to monitor....

**Comment by laf** [comment]
I've submitted basic detection but from the mibs and your snmpwalk, I can''t find other metrics to graph - can you point me to the OIDs or names in question for the data you want?

**Comment by jjonssondk** [comment]
That is strange ?

The MIBs should contain everything., especially these signal values:
https://ibb.co/cHL6ha

Those are actually the most important to monitor, as they inform how the modem is performing on the cable network...

**Comment by laf** [comment]
Point to where they are in the MIB then or at least in your snmpwalk output.

**Comment by jjonssondk** [comment]
Ok, it looks like the needed MIB is DOCS-IF-MIB according to this:
http://cric.grenoble.cnrs.fr/Administrateurs/Outils/MIBS/?module=DOCS-IF-MIB&fournisseur=CISCO

**Comment by jjonssondk** [comment]
I'm not sure if I got that MIB...

**Comment by jjonssondk** [comment]
https://www.simpleweb.org/ietf/mibs/modules/IETF/txt/DOCS-IF-MIB

**Comment by jjonssondk** [comment]
DOCSIS v3.0 http://mibs.cablelabs.com/MIBs/DOCSIS/DOCS-IF3-MIB-2016-08-04.txt

**Comment by jjonssondk** [comment]
http://mibs.cablelabs.com/MIBs/DOCSIS/

**Comment by laf** [comment]
Ok I've added all but the upstream values as I can't find that in the MIBs or the data.

**Comment by jjonssondk** [comment]
Working great!

But missing Signal to Noise ratio on downstream channels (https://ibb.co/cHL6ha). Both upstream powerlevel and downstream is monitored....

**Comment by laf** [comment]
I've added what I can see, you will need to provide the OID for more support.

**Comment by jjonssondk** [comment]
@laf I'm sorry, but I'm by no mean an expert on SNMP.... Don't know much about it. If I google, this is what I find:
http://mibs.cablelabs.com/MIBs/DOCSIS/DOCS-IFEXT2-MIB-2011-06-23.txt
and
http://cric.grenoble.cnrs.fr/Administrateurs/Outils/MIBS/?oid=1.3.6.1.4.1.4491.2.1.5.1.3.2.1.6

Is that usable ?

**Comment by laf** [comment]
`1.3.6.1.4.1.4491.2.1.5.1.3.2.1.6` isn't in the walk you've given us. You can try a new walk with just `1.3.6.1.4.1.4491.2.1.5.1.3.2.1.6` to see, if it's not returning data though then we can't add it.
