### ISSUE TITLE
No alerts due to php parse error within eval().

### ISSUE THREAD

**Issue by YenzRanger** [librenms/librenms#6641]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

LibreNMS  | 4d0832e4120984fa25de24a8c7367a9e59036799
DB Schema | 190
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

Problem:
Alert templates containting the "-sign causes an php parse error within the eval() function. This leads to no alerts.

Problem exists since commit 0338734fe782216c128ee745a8bdea90eff187cd.
Previous to this commit the template was escape with `addslashes($tpl)` (`includes/alert.inc.php` line 378).
Now it is `str_replace("'", "\'", $tpl)` (line 325).

Reproduce:
Just use a "-sign within the template, e.g. `<a href="https://example.com">visit example.com</a>`

Result:
No alerts, no entries in event log

**Comment by laf** [comment]
We actually need to update the docs, you should use `'` instead of `"`.

`"` is now usable as normal PHP so you can do {if %state == "something or other"}

**Comment by YenzRanger** [comment]
Funnily enough, as soon as I discovered that ~~bug~~ feature I used that to inject PHP code.
Unfortunately it broke my complete alerting system beforehand. (Auto update with the daily.sh script.)

Thumbs up to "need to update the docs".

By the way: Having neither errors nor logs at this point is kinda unlucky. But with the test-template.php script one is actually able to test it.

**Comment by YenzRanger** [comment]
Sry, but I've to reopen this issue. If you're using
`<a href='https://www.example.com'>example.com</a>`
in the template now results in
`<a href=\'https://www.example.com\'>example.com</a>`
(slashes are added).

This results in the browser trying to load `http://%27http://www.example.com'`

So how to properly format HTML mails now?

**Comment by laf** [comment]
So actually you can do `\"`.

@murrant I'm considering reverting the change I made to remove str_replace() call I put in place of addslashes() so we can use `"` within {if} calls. This was to get new functionality but seems at too high a cost right now as it could be breaking templates - we have no way of knowing. So revert or ask people to escape the use of `"` outside of `{if}` calls?

**Comment by murrant** [comment]
@laf: perhaps we need more complex parsing?  should be able to quote strings inside of {} and escape strings in the normal message.

**Comment by laf** [comment]
Reverted, please update
