### ISSUE TITLE
IRC bot auth doesn't work with LDAP authentication

### ISSUE THREAD

**Issue by XioNoX** [librenms/librenms#6642]
After testings and IRC conversation,

When LibreNMS is setup with $config['auth_mechanism'] = "ldap"; IRC bot authentication doesn't work as LibreNMS doesn't know the email tied to a specific user.

**Comment by laf** [comment]
Please submit this as a feature request. IRC bot was only written for mysql auth where we know the users email address. We don't have this with other auth modules (except AD now due it being updated to support this).
