### ISSUE TITLE
<iframe> in note widget doesn't work

### ISSUE THREAD

**Issue by XioNoX** [librenms/librenms#6650]
When creating a dashboard widget note, containing:
```
foo
<iframe src="http://perdu.com/"></iframe>
```
(Also tried with a https website).
The note only shows a white square.
The code above saves in mysql:
> "{"notes":"foo\r\n<iframe src=\"http:\/\/perdu.com\/\"><\/iframe>"}"

And the page's source code looks like this:
![The code looks like this](https://usercontent.irccloud-cdn.com/file/Mgsr0BSZ/Screenshot%20from%202017-05-16%2008-50-27.png)

**Comment by laf** [comment]
Well that was a pain but fixed, if you want to test feel free.

**Comment by XioNoX** [comment]
Iframe works, thanks, but it doesn't fit the "note" box:
![See](https://usercontent.irccloud-cdn.com/file/rUgztQlX/librenms-iframe-note.png)

**Comment by laf** [comment]
I've pushed an update to allow width and height attributes in the iframe.

![image](https://cloud.githubusercontent.com/assets/3941142/26753205/23187178-4859-11e7-916c-f99442b9f225.png)

**Comment by XioNoX** [comment]
Works fine for me, thanks!
