### ISSUE TITLE
New Device: Halon Mail Gateway 

### ISSUE THREAD

**Issue by basn** [librenms/librenms#6652]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 155d9de8dc7e2703ce263d824886a89bd2f2a760
DB Schema | 191
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

Snmp logs:
https://p.libren.ms/view/bcb016d0
https://p.libren.ms/view/8095af85
https://p.libren.ms/view/fe54b632

Mib: http://demo.halon.se/download/HALON-SP-MIB.txt
https://github.com/halon/
http://wiki.halon.se/SNMP <- for more info.

**Comment by jjonssondk** [comment]
Great! Looking forward to support. Best SPAM filter ever!
