### ISSUE TITLE
MIBs Contribution - Latest VMware-mibs-6.5.1 

### ISSUE THREAD

**Issue by guoming218** [librenms/librenms#6659]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the ==========================================================
Component | Version
--------- | -------
LibreNMS  | c40b762e234e9d44266dc276551728a8527326b5
DB Schema | 191
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.55-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================
 section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
[1013445_VMware-mibs-6.5.1-5148165.zip]
Not sure if u guys need this but since this is the latest MIBs i will upload it here :) Cheers.
(https://github.com/librenms/librenms/files/1006601/1013445_VMware-mibs-6.5.1-5148165.zip)
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
You can submit a pull request with the updated mibs :)
