### ISSUE TITLE
Netonix Switch Vlan Information Missing

### ISSUE THREAD

**Issue by Andreser** [librenms/librenms#6663]
I've recently Installed LibreNMS for a Client and noticed when adding a Cisco switch to libreNMS that there is a tab with information about it's vlans. We are a ISP and on our network we use Netonix switches but don't have any VLAN tab on our Netonix Switch page. Our install is up to date.
Is it a MIB problem? 
I did an snmpwalk on my netonix switch and I noticed some info appearing with the names we are using for our vlans, for example:
```
SNMPv2-SMI::mib-2.17.7.1.4.3.1.1.1 = STRING: "Management"
SNMPv2-SMI::mib-2.17.7.1.4.3.1.1.3 = STRING: "OP1"
SNMPv2-SMI::mib-2.17.7.1.4.3.1.1.20 = STRING: `"OP2"
```
Is this a LibreNMS issue or should I contact Netonix for an update on their MIB files?

**Comment by laf** [comment]
We don't have specific support for netonix vlans so if they don't use the standard BRIDGE-MIB then custom support needs adding. Please open a feature request on the community site if that's the case or discuss this on irc / community site.
