### ISSUE TITLE
Add Support for SonicWALL SMA/SRA firmware v8.6.x

### ISSUE THREAD

**Issue by aherbach88** [librenms/librenms#6667]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery - https://p.libren.ms/view/6ec13466
Poller - https://p.libren.ms/view/22c27348
SNMPbulkwalk - https://p.libren.ms/view/aa3fe1b7

After upgrading the firmware on my SRA4600, LibreNMS now shows it as a generic device (another one with the 8.1 firmware works fine, and this one when it had the 8.5 firmware showed normally).

Component | Version
--------- | -------
LibreNMS  | bfa26b8634bbe0a21b65dacea3a4a11371bda45d
DB Schema | 191
PHP       | 7.0.18
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

**Comment by aherbach88** [comment]
The fix now broke the discovery on my firmware 8.1.x device.

**Comment by laf** [comment]
I'm submitting another fix for this.

However can you please please contribute to the stats system (http://docs.librenms.org/General/Callback-Stats-and-Privacy/#how-do-i-enable-stats-submission) it provides us info we can use for testing - at present we had no 8.x versions of data to test against but based on everything we do have, this update should have worked.

**Comment by aherbach88** [comment]
I've turned on stats now, would you like an SNMPbulkwalk for this as well?  I can provide more data if need be.

**Comment by laf** [comment]
If you've got the output of sysObjectId and sysDescr that would be ace otherwise a full walk is fine.

**Comment by aherbach88** [comment]
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.8741.6
SNMPv2-MIB::sysDescr.0 = STRING: Dell SonicWALL SRA 4600 ( 8.1.0.2-14sv)
