### ISSUE TITLE
New sensor state "sysCmSyncStatusId" for F5 OS

### ISSUE THREAD

**Issue by superflip99** [librenms/librenms#6676]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 895801d85522009db5e23ad337812d20efe04960
DB Schema | 191
PHP       | 7.0.19-1~dotdeb+8.1
MySQL     | 10.0.30-MariaDB-0+deb8u2
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

I will add support for a new sensor state sysCmSyncStatusId, where actual Sync State can be viewed.

**Comment by laf** [comment]
Merged in, thanks :)
