### ISSUE TITLE
683a10e breaks ./scripts/auth_test.php

### ISSUE THREAD

**Issue by YenzRanger** [librenms/librenms#6678]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 895801d85522009db5e23ad337812d20efe04960
DB Schema | 192
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

With commit 683a10e723012bf333ba122f225ed960ffed21eb the auth testing script `./scripts/auth_test.php` gets broken.

```
$ ./scripts/auth_test.php -u admin
PHP Fatal error:  Uncaught Error: Call to undefined function get_client_ip() in /opt/librenms/html/includes/authenticate.inc.php:83
Stack trace:
#0 /opt/librenms/includes/init.php(169): require()
#1 /opt/librenms/scripts/auth_test.php(29): require('/opt/librenms/i...')
#2 {main}
  thrown in /opt/librenms/html/includes/authenticate.inc.php on line 83
```

Normal authorization (webui) works fine.

**Comment by laf** [comment]
#6673 fixes this but not yet merged
