### ISSUE TITLE
Atal Etherprobe device snmp support

### ISSUE THREAD

**Issue by telskamp** [librenms/librenms#6684]
Hey Guys,

We use atal etherprobes for monitoring temperatures in some of our server/patch rooms. however the devices are not properly recognized by librenms and also the temprature is not recorded/displayed

We have two different models, please find the outputs for device type EPND-T-INT below
https://www.atal.nl/catalog/product/view/id/16092/
./discovery.php -h HOSTNAME -d | ./pbin.sh https://p.libren.ms/view/7410c72c
./poller.php -h HOSTNAME -r -f -d | ./pbin.sh https://p.libren.ms/view/9b53a8e0
snmpwalk -OUneb -v1-c community HOSTNAME | ./pbin.sh https://p.libren.ms/view/f3d7e8f4

We also have etherprobe2 EP2-T sensor,.
https://www.atal.nl/ethernet-gebaseerd-monitoring-systeem-temperatuur.html
./discovery.php -h HOSTNAME -d | ./pbin.sh https://p.libren.ms/view/84e96338
./poller.php -h HOSTNAME -r -f -d | ./pbin.sh https://p.libren.ms/view/b6964a34
snmpwalk -OUneb -v1-c community HOSTNAME | ./pbin.sh https://p.libren.ms/view/b3e694c8
Please let me know if you need more info

**Comment by laf** [comment]
Would these both be classed as the same devices?

If they have custom info then we need the MIBs as well.

**Comment by telskamp** [comment]
these devices do slightly differ but should both be interpeted as an atal etherprobe device.
As for the Mibs I do seem to have some unfortunately I do not exactly know which mib is needed for what
[etherprobe2MIB.zip](https://github.com/librenms/librenms/files/1018277/etherprobe2MIB.zip)
[EPND-mib-tables.zip](https://github.com/librenms/librenms/files/1018279/EPND-mib-tables.zip)

please let me know if i can be of futher assistance.

Thanks in advance

**Comment by laf** [comment]
So few issues with this (I have submitted basic detection for ethernetprobe2 though).

The first walk has no useable sysObjectID or sysDescr so we can't run detection on it.

The second walk is fine and I've used that to add detection - the issue, it contains no real data so this still won't have temperature sensors. You can try re-running the snmp walk with `.1.3.6.1.4.1.3854` instead of `.`

**Comment by telskamp** [comment]
I am sorry for being a total noob but regarding your  question how do I run the snmp walk with ".1.3.6.1.4.1.3854 instead of ." ?

**Comment by laf** [comment]
`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .1.3.6.1.4.1.3854`

**Comment by telskamp** [comment]
it is a v1 device so i tried:  snmpwalk -OUneb -v1 -c community  hostname .1.3.6.1.4.1.3854 | ./pbin.sh
It seems however to give an empty response

**Comment by telskamp** [comment]
oh wait the etherprobe2 device does give response
https://p.libren.ms/view/6b6c34b1

**Comment by telskamp** [comment]
regarding the other device how would i be able to geneare a snmpwalk which does return  sysObjectID or sysDescr ?

**Comment by laf** [comment]
That's better :)

Looks like the first device just has bad snmp info so you'll need to raise that to the manufacturer.

**Comment by telskamp** [comment]
ok, thanks for your assistance!

**Comment by telskamp** [comment]
so i did some more reading on SNMP and  i think we kind messed up the identifier of the first device ourselves.  The mib says the following about sysdescription:
`- 1.3.6.1.2.1.1.1
        sysDescr OBJECT-TYPE
                SYNTAX DisplayString (SIZE (0..255))
                ACCESS read-only
                STATUS mandatory
                DESCRIPTION
                        "A textual description of the entity.  This value
                        should include the full name and version
                        identification of the system's hardware type,
                        software operating-system, and networking
                        software.  It is mandatory that this only contain
                        printable ASCII characters."`
However running snmpwalk using 1.3.6.1.2.1.1.1 returns the device location (which one of my colleagues once configured) and the firmware version.
i did find however the following:
https://p.libren.ms/view/7039e446
If i am not mistaken this is the part with the sensor information displaying the temperature in Celcius and the high/low limit.

**Comment by laf** [comment]
It's not about the information that's available at the moment, it's about us being able to detect the device is an EtherProbe2 which from the walk you did at the start isn't something we can do:

```
.1.3.6.1.2.1.1.1.0 = STRING: "Schalkweide Serverruimte Firmware Version 4-5-1.21            "
.1.3.6.1.2.1.1.2.0 = OID: .0.32.32.32.32.32.32.32.32.32.32.0.111.110.102.0.77.111.100.66.117.115.0.83.78.77.80.0.67.121.107.108.95
```

.1.3.6.1.2.1.1.1.0 is too generic
.1.3.6.1.2.1.1.2.0 is just wrong.

**Comment by laf** [comment]
I've updated the pull request now to include temp and humidity. Until the vendor fixes snmp in the other device we can't add detection I'm afraid.
