### ISSUE TITLE
Meru support only detects controller bond interface not the AP's

### ISSUE THREAD

**Issue by draconis244** [librenms/librenms#6689]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
You need to provide ALL the information asked for in point 3.

**Comment by laf** [comment]
We can re-open this once you've provided the info.

**Comment by draconis244** [comment]
==========================================================
Component | Version
--------- | -------
LibreNMS  | 2a75083f471f93bb1270d4d1c42bc1264ba5aaf5
DB Schema | 192
PHP       | 7.0.19-1+deb.sury.org~xenial+1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  Your local git contains modified files, this could prevent automatic updates.
Modified files:
	 html/plugins/Test/Test.inc.php
	 html/plugins/Test/Test.php
	 includes/definitions/fortiwlc.yaml
	 includes/definitions/toshiba-tec.yaml

**Comment by draconis244** [comment]
<body>
	<div id="container">
		<h1>A Database Error Occurred</h1>
		<p>Error Number: 2006</p><p>MySQL server has gone away</p><p>SELECT RELEASE_LOCK('nfb8u2ko8ur9ig8b7din376588') AS ci_session_lock</p><p>Filename: libraries/Session/drivers/Session_database_driver.php</p><p>Line Number: 399</p>	</div>
</body>
curl: (56) GnuTLS recv error (-110): The TLS connection was non-properly terminated.
</html>root@librenms:/opt/librenms# 

your mysql database server dropped when I tried to 
./discovery.php -h 10.11.60.2 -d | ./pbin.sh
./poller.php -h 10.11.60.2 -r -f -d | ./pbin.sh
snmpbulkwalk -OUneb -v2c -c public 10.11.60.2 .  | ./pbin.sh

it threw on the last one snmpbulkwalk

**Comment by draconis244** [comment]
[bulk-meru.txt](https://github.com/librenms/librenms/files/1019747/bulk-meru.txt)


the bit that failed

**Comment by draconis244** [comment]
if you need anything else let me know

**Comment by laf** [comment]
Remove the `| ./pbin.sh` and upload the data to an online pastebin service somewhere.

**Comment by draconis244** [comment]
https://www.dropbox.com/s/ko24zzlxpfxhs4q/bulkwalk.txt?dl=0

**Comment by draconis244** [comment]
it's huge 5mb which is probably why your mysql server blobbed out ...it contains all the AP's

**Comment by draconis244** [comment]
https://www.dropbox.com/s/pbdw5tsmj4sz822/mibs.tar.gz?dl=0

**Comment by draconis244** [comment]
here are the mibs that come with the 3200 controller apparently they support all meru wifi controllers and AP's

**Comment by draconis244** [comment]
https://www.dropbox.com/s/ko24zzlxpfxhs4q/bulkwalk.txt?dl=0     and bulkwalk again

**Comment by draconis244** [comment]
https://www.dropbox.com/s/z9se6ko8yf5nq92/meru-bulkwalk.txt?dl=0   here's the snmp download snmp walk from librenms itself

**Comment by draconis244** [comment]
need anything else ? issue says requires info still ?

**Comment by laf** [comment]
Can you provide some information on what it is you actually expect to see?

**Comment by laf** [comment]
No further info provided, please respond and we will re-open the issue.
