### ISSUE TITLE
http_auth_guest broken?

### ISSUE THREAD

**Issue by KristijanL** [librenms/librenms#6697]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
==========================================================
Component | Version
--------- | -------
LibreNMS  | db3a0c26232494c7f3efc13ac71d801af7ba7898
DB Schema | 192
PHP       | 7.0.18
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

after an updated in the last month i am no longer an admin when i login to librenms using this config:
$config['auth_mechanism'] = "http-auth";
$config['http_auth_guest'] = "admin";

select * from users;
| user_id | username  | password  | realname  | email | descr | level | can_modify_passwd | created_at          |
|  1 | admin | x | | x@gmail.com |  | 10 |  1 | 0000-00-00 00:00:00 |

Best Regards,
Kristijan

**Comment by laf** [comment]
Please test https://github.com/librenms/librenms/pull/6699
