### ISSUE TITLE
ILOM oracle M7 detected as Generic Device

### ISSUE THREAD

**Issue by ridhoyp** [librenms/librenms#6702]
Hi,

Is Librenms can monitoring Ilom M7 server? we need to get temperature metrics..

![image](https://cloud.githubusercontent.com/assets/28750276/26311116/52da5be0-3f2d-11e7-8854-a282043dcd2f.png)

Regards,
RidhoYP

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
That screenshot isn't enough info to tell, if no logo shows up then most likely detection doesn't exist.

Please provide ALL the information asked for in point 3 and we can re-open this.

**Comment by ridhoyp** [comment]
https://p.libren.ms/view/060eba05

https://p.libren.ms/view/71c8bfa8

cat snmpm7.txt | ./pbin.sh
Paste endpoint: https://p.libren.ms/api/create
title:
name: monitor
private: 1
expire: 0
        Error: Missing paste text

can i just upload the txt ? because if using pbin.sh directly its timeout

Regards,
RidhoYP

**Comment by laf** [comment]
Yes you can just upload the text file to github

**Comment by ridhoyp** [comment]
Hi,

here is the txt file

[snmpm7.txt](https://github.com/librenms/librenms/files/1021645/snmpm7.txt)

**Comment by laf** [comment]
Can you point me to the OID for the temperature readings you want, the walk has a lot of data in it :(

**Comment by ridhoyp** [comment]
[temperature.oid.txt](https://github.com/librenms/librenms/files/1050772/temperature.oid.txt)

here is the temeprature oids

**Comment by ridhoyp** [comment]
i dont know which is, how to browse the oid, and select what i want? that just an oids, dont give the result like what temperature it is, and the value

**Comment by laf** [comment]
Yeah it's the temperature results that we need. 

That's 900 temperature sensors, I think even if we had the oid we wouldn't add that many sensors, it would slow polling down and make the webui un-responsive.

You'll need to find the specific OIDs you want data for.

**Comment by ridhoyp** [comment]
Hi,

I still couldnt found the OID for temperature, do you know the tools to discover the oid description ? so i can select it and send to you,

Regards,
RidhoYP

**Comment by ridhoyp** [comment]
Hi, 

![image](https://cloud.githubusercontent.com/assets/28750276/26834097/8a2ff618-4afe-11e7-9f6d-9bf9bfa8605a.png)

its already have temperature graph here, i just look it today ,

please close the issue, the librenms is automatically can discover the temperature using IPMI

Regards,
RidhoYP
