### ISSUE TITLE
db query bug

### ISSUE THREAD

**Issue by bahadirbirden** [librenms/librenms#6703]
Component | Version
--------- | -------
LibreNMS  | db3a0c26232494c7f3efc13ac71d801af7ba7898
DB Schema | 192
PHP       | 5.6.30
MySQL     | 5.6.35
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

With the latest version there is a db problem.

2017-05-22 16:30:58 MySQL Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 1' at line 1 ( LIMIT 1)
/usr/local/www/librenms/poller.php 87 2017-05-22 16:30:58 - 1 devices polled in 2.451 secs

problem query
**************
SELECT DISTINCT(devices_locations.device_id) FROM librenms.locations WHERE  devices_locations.device_id='2' AND (devices_locations. = "test") LIMIT 1 locations

the right one must be like

SELECT DISTINCT * FROM librenms.locations WHERE librenms.locations.id='2' AND (librenms.locations.location = "test") LIMIT 1

Best regards

Bahadır Birden

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
That query doesn't look like one that's run from our core setup, it's most likely a bad alert rule or device group.

Please discuss this on irc or the community site.

**Comment by bahadirbirden** [comment]
i will check again.
