### ISSUE TITLE
device support for schneider square d poerlogic

### ISSUE THREAD

**Issue by second-mouse-gets-the-cheese** [librenms/librenms#6709]
Sorry, first time in here - so not sure if this should be under feature request. In short, the smart power utility to our facility has SNMP and web access, and provides some detailed info like load per phase, load per total, etc. Similar to a UPS (also made by APC/Schneider) but the detection and/or mib support seems not to be recognized to show any of that useful data in LibreNMS.

I've captured the Discovery, Poller, and SNMP files per the FAQ#8 and uploaded it here:

http://wikisend.com/download/970684/powerlogic_pm8000.zip

Friendly device name would be PowerLogic PM800 made by Square D also known as Schneider Electric

I'd appreciate any direction or help to get these variables monitored, it would be very helpful. Thank you!

**Comment by laf** [comment]
Can you upload the files to a normal pastebin service (you can use p.libren.ms) to make it easier.

**Comment by second-mouse-gets-the-cheese** [comment]
discovery.txt https://p.libren.ms/view/93db8745

poller.txt https://p.libren.ms/view/d2c3675b

snmpwalk.txt https://p.libren.ms/view/fff87977

Thank you for looking at it!

**Comment by laf** [comment]
Please test #6809. The only thing I think is wrong is Power. The mib says it's kW so I've converted it to W but obviously this is wrong - what value is reported by the device?

![image](https://user-images.githubusercontent.com/3941142/26952778-cc2684c8-4c9e-11e7-80ad-3044a86ec9f8.png)

**Comment by laf** [comment]
@second-mouse-gets-the-cheese Any chance you test this please?

**Comment by second-mouse-gets-the-cheese** [comment]
First, thank you - works great!    Second, this device was installed with the leads backwards by our contractor (long story) so it reports that the KW Load for the building is negative  -373KW for instance right now.    So i actually need to hand edit this to make it think its positive, thats not you reading anythign wrong, the value is coming back negative.    So the device reports toatl KW and total KVA  both show negative  here is what the web interface shows right now:


Instantaneous Readings
PM8 POWER METER
 	6/12/2017 4:24:03 PM
Parameter	Minimum	Present	Maximum
Load Current (A)	 
Ia	0	438	--
Ib	--	452	--
Ic	--	455	483
 
Power	 
Real (kW)	-380	-360	0
Reactive (kVAR)	-84	-79	2
Apparent (kVA)	0	369	389
 
Power Factor Total	0.002 lag	0.977 lag	0.002 lead
 
Voltage, L-L Avg.	470	475	487
Voltage, L-N Avg.	272	274	280
 
Frequency (Hz)	59.94	59.99	


"If you would be so kind as to hint where i can hand edit to flip my negative to positive by hard editing the file i'd appreciate it.  Right now i wont touch it, i want to see if it may graph a negative number (which would be just fine, im trying to monitor trends).   

thanks again.

**Comment by laf** [comment]
So the only way you can manually edit this would be to disable the sensors discovery module for this device and hand edit the DB and change the divisor or multiplier. If you don't disable the discovery module then it will just overwrite that change - this means you won't get any new sensors if we add more support.

Have you tested this PR or does the screenshot look like it's showing the correct values?

**Comment by second-mouse-gets-the-cheese** [comment]
Thank you for that, so i did hand edit the multiplier to -1000 and re-discovered.   All good.   its now graphing too thanks to not being negative.   

Question: if i simply edit the database for this specific device and modify the field " last_discovered_timetaken	= 4.58" to something like 9999999 or change "last_discovered from 2017-06-13 09:30:06 to something in 2099-01-01" wouldn't that trick it to never rediscover and break my custom multiplier? 

 I wasn't sure how to 'disable' a specific sensor's discovery, but figured this would do the trick. I didnt want to delete the discovery files off the file system.

thank you again, its working perfect for our needs

**Comment by laf** [comment]
If you got to the device -> edit -> modules. You can disable sensors module under discovery.

What you changed there will just be overwritten by now.
