### ISSUE TITLE
Application Memcached does not graph app_state UNKNOWN

### ISSUE THREAD

**Issue by felimwhiteley** [librenms/librenms#6711]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
```
Component | Version
--------- | -------
LibreNMS  | 4ea27596d8aefdd0af77917e03111c4142534ea2
DB Schema | 192
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
```
- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
Attempting to monitor the local memcached service locally on a central node that also has 2 distributed pollers, but it is using it's own localo SNMP to query the memcached on itself, using the latest snmp extend script. Returns data no problem, but no graphs ever get data, below is the wrapper script with output from poller wrapper py script using -d & -v options.

- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

```
#### Load poller module applications ####
SQL[SELECT * FROM `applications` WHERE `device_id`  = '43'] 
SNMP[/usr/bin/snmpget -v2c -c 'public' -Oqv -M /srv/librenms/mibs:/srv/librenms/mibs/supermicro udp:172.16.12.54:161 .1.3.6.1.4.1.8072.1.3.2.3.1.2.9.109.101.109.99.97.99.104.101.100]
"<<<app-memcached>>>
a:1:{s:15:\"localhost:11211\";a:24:{s:3:\"pid\";i:-1;s:6:\"uptime\";i:0;s:7:\"threads\";i:0;s:4:\"time\";i:0;s:12:\"pointer_size\";i:0;s:19:\"rusage_user_seconds\";i:0;s:24:\"rusage_user_microseconds\";i:0;s:21:\"rusage_system_seconds\";i:0;s:26:\"rusage_system_microseconds\";i:0;s:10:\"curr_items\";i:0;s:11:\"total_items\";i:0;s:14:\"limit_maxbytes\";i:0;s:16:\"curr_connections\";i:0;s:17:\"total_connections\";i:0;s:21:\"connection_structures\";i:0;s:5:\"bytes\";i:0;s:7:\"cmd_get\";i:0;s:7:\"cmd_set\";i:0;s:8:\"get_hits\";i:0;s:10:\"get_misses\";i:0;s:9:\"evictions\";i:0;s:10:\"bytes_read\";i:0;s:13:\"bytes_written\";i:0;s:7:\"version\";s:0:\"\";}}"

SQL[UPDATE `applications` set `app_state` ='UNKNOWN',`app_status` ='',`timestamp` =NOW() WHERE `app_id` = '10'] 
 memcached()RRD[update 172.16.12.54/app-memcached-10.rrd N:U:U:U:U:U:U:U:U:U:U:U:U:U:U:U:U:U:U --daemon localhost:42217]
RRDtool Output: OK u:0.00 s:0.00 r:1.07
```

**Comment by laf** [comment]
Please ask for help on irc or the community site, github is for bugs only.

**Comment by laf** [comment]
Confirmed bug.

Output needs trim " + string passing to update_application
