### ISSUE TITLE
Sensors under baseline alerts

### ISSUE THREAD

**Issue by dracmic** [librenms/librenms#6712]
DO NOT DELETE THIS INFORMATION.
Hello guys,

I observed after fixing the cooling system of my rack that I get alerts for sensors as Sensors under limit because the temperature gone down with ~10.0 C and I am getting a lot of alerts. Operating system is Linux. The second thing or bug is with Mikrotik Temperature which can be negative because Mikrotik is accepting it (Tested ambient temperature	-30C .. +80C).

Thanks,
Mihai Ursu
> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
You just need to adjust the sensor thresholds in device -> edit -> health.

GitHub is for bugs only, please ask for help on irc or the community site.
