### ISSUE TITLE
3Com Switch 4500 - Add support for CPU and memory. 

### ISSUE THREAD

**Issue by kkrumm1** [librenms/librenms#6715]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the 
==========================================================
Component | Version
--------- | -------
LibreNMS  | d48be5f5070ec54c7874cc97271554f855c1fcf3
DB Schema | 192
PHP       | 7.0.18
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful
[OK]    Database schema correct
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
Discovery: https://p.libren.ms/view/b2d28f8a
Poller: https://p.libren.ms/view/31fea0ce
snmpwalk 1: https://p.libren.ms/view/89b252c0
snmpwalk 2: https://p.libren.ms/view/1aacac4c

OID's for 3com switch 4500's 
1.3.6.1.4.1.43.45.1.6.1.1.1.3 - 1 Minute CPU AVG
1.3.6.1.4.1.43.45.1.6.1.1.1.4 - 5 Minute CPU AVG
1.3.6.1.4.1.43.45.1.6.1.1.1.2 - 5 Second CPU AVG
1.3.6.1.4.1.43.45.1.6.1.2.1.1.3 - Free Memory Remaining
1.3.6.1.4.1.43.45.1.6.1.2.1.1.6 - Number of Memory Allocation Failures
1.3.6.1.4.1.43.45.1.6.1.2.1.1.7 - Memory Allocation Failure Due to no Memory Available
1.3.6.1.4.1.43.45.1.6.1.2.1.1.2 - Total Memory of Device

**Comment by laf** [comment]
we really need the walk

**Comment by kkrumm1** [comment]
SNMP walks added.

**Comment by laf** [comment]
The walks don't include any data from `.1.3.6.1.4.1.43` please re-run it with that.

**Comment by kkrumm1** [comment]
SNMP Walk: https://gist.github.com/kkrumm1/da3b145e9901c16dba29a584ed7d36d3
with .1.3.6.1.4.1.43

**Comment by laf** [comment]
Would you mind testing #6823
