### ISSUE TITLE
F5 BigIP 3600 - issue when polling 

### ISSUE THREAD

**Issue by hbadreldin** [librenms/librenms#6717]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 407c0a4470a062df746d4a423e559a401c81e29d
DB Schema | 192
PHP       | 7.0.19
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

- [X] Please provide as much detail as possible.
#### Load poller module loadbalancers ####
When running Poller.php on F5 BigIP that used to work before the latest updates on your code .

Fatal error: Uncaught Error: Cannot use string offset as an array in /opt/librenms/includes/polling
/loadbalancers/f5-ltm.inc.php:27
Stack trace:
#0 /opt/librenms/includes/polling/loadbalancers.inc.php(13): include()
#1 /opt/librenms/includes/polling/functions.inc.php(274): include('/opt/librenms/i...')
#2 /opt/librenms/poller.php(153): poll_device(Array, '-O qv')
#3 {main}
  thrown in /opt/librenms/includes/polling/loadbalancers/f5-ltm.inc.php on line 27

- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
The last commit to `/opt/librenms/includes/polling/loadbalancers/f5-ltm.inc.php` was April the 13th so it doesn't tie in, line 27 also wasn't changed. You'll need to provide all of the information asked for in point 3 when creating an issue (you've deleted that section). Please provide that info and we can re-open the issue.
