### ISSUE TITLE
Bad request page after a search in the port list and update URL or detail link

### ISSUE THREAD

**Issue by boudreau** [librenms/librenms#6720]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 88a490a969a755c7d33deafb365c74e54768bc7e
DB Schema | 192
PHP       | 7.0.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.5.6
SNMP      | NET-SNMP 5.7.2

When I do a search for a port name in the list of port and I use a "%" as a regexp. 
I can't "update URL" or use the "detail" link, it gives me a bad request page:

I start at this URL: 
https://librenms.mycompany.com/ports/
I put in the port description "purvis-%-ap" to look for certain APs in a building 
It gives me a list of what I want to see, but if I click "update URL"
This is the URL it tries to go to:
https://librenms.mycompany.com/ports/ifAlias=purvis-%25-ap/format=list_basic/
It give Bad request page.

It does the same thing with the "detail" link also.
https://librenms.mycompany.com/ports/ifAlias=purvis-%25-ap/format=list_detail/
Anyway to fix this?

Thanks

**Comment by laf** [comment]
You can possibly try: https://github.com/librenms/librenms/issues/3190

However this isn't a bug, your using sql wildcards to try and match so is outside the scope of how it should work
