### ISSUE TITLE
Graphics erros

### ISSUE THREAD

**Issue by Setsuneh** [librenms/librenms#6727]
Hi,

I've tried to make Dashboard Windows/Ubuntu/Debian. But for the first one, serveral graphics have many errors.
Graphs work on **/devices/devices=** without problems. There's no firewall or blocked port on. Need for Memory usage..

Any issue?

Here is the problem:
[https://img4.hostingpics.net/pics/587219LIBRENMS.png]

**Comment by Rosiak** [comment]
Are you sure the data for these graphs, for these devices, exists?

**Comment by laf** [comment]
GitHub is for bug reports and new devices. Please discuss this on irc or the community forum.
