### ISSUE TITLE
Unknown sysObjectID

### ISSUE THREAD

**Issue by Olen** [librenms/librenms#6729]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

==========================================================
Component | Version
--------- | -------
LibreNMS  | 3b45ea1b37baef930f5e59f8a0396ab1353944b4
DB Schema | 192
PHP       | 7.1.5
MySQL     | 10.1.21-MariaDB
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

That link does not lead to the correct place, I believe...

- [x] Please provide as much detail as possible.

When polling my HP-printer, the device is reporting a strange sysObjectID, and this leads to at least two entries in the logs for each poll.
The printer in question is a HP Photosmart 7520 series.  When doing a manual snmpwalk this is what it reports:
SNMPv2-MIB::sysObjectID.0 = OID: joint-iso-ccitt.3199670112.808464432.808464432.808464432.808464432.808464432.808202338

And in my logs in librenms I see two entries for each poll:
sysObjectID -> joint-iso-ccitt.3199670112.808464432.808464432.808464432.808464432.808464432.808202338 
(see attached screenshot)

![image](https://cloud.githubusercontent.com/assets/203184/26455401/69b61554-416a-11e7-8567-2cad5820d473.png)

**Comment by laf** [comment]
Please provide all info asked for in point 3. We will reopen when it's provided

**Comment by Olen** [comment]
https://p.libren.ms/view/027678fc
https://p.libren.ms/view/d1a94093
https://p.libren.ms/view/554006d7

**Comment by laf** [comment]
Please see if this fixes it, run this mysql query:

```
ALTER TABLE `devices` CHANGE `sysObjectID` `sysObjectID` VARCHAR(128) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;
```
