### ISSUE TITLE
Two small irc-patches

### ISSUE THREAD

**Issue by Olen** [librenms/librenms#6730]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Two small patches to IRCBot.php
The first makes the formatting of UTF-8 recovery messages nicer by shifting the strikethrough one character.  At least with my client and font.

The second changes the irc-alerts to also use the defined templates, not only showing the default message.
This MIGHT cause issues with very long templates (or templates with eg. html).  I guess the best solution would be to be able to define different templates for all transports.  

[IRCBot.UTF8.patch.txt](https://github.com/librenms/librenms/files/1029771/IRCBot.UTF8.patch.txt)
[IRCBot.Template.patch.txt](https://github.com/librenms/librenms/files/1029772/IRCBot.Template.patch.txt)

**Comment by laf** [comment]
Thanks for this, you need to submit he changes via a pull request. We can't accept code that doesn't go through that process.
