### ISSUE TITLE
Cisco IOS PRI detection not working

### ISSUE THREAD

**Issue by trs80** [librenms/librenms#6733]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 337dd4d02ee52e75d1b959dcfff9438403332b3b
DB Schema | 192
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.55-0+deb8u1-log
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

https://github.com/librenms/librenms/blob/master/includes/polling/cisco-voice/cisco-iospri.inc.php#L25 looks for 81 in the snmpwalk_cache_oid_num output, but using print_r I can see that on my system it contains 'ds0'. This is probably because I have `mibdirs +/usr/share/netdisco/mibs/cisco` in my `snmp.conf` which pulls in CISCO-VISM-DSX0-MIB.my that defines the ifType.

Is the correct fix to check for both or work out how to stop the extra MIB being loaded?

**Comment by laf** [comment]
I'd say the best way forward is for us to load the mib and do a check in the code for both.

**Comment by laf** [comment]
Please test #6776

**Comment by trs80** [comment]
Tested, is working.
