### ISSUE TITLE
Enterasys POE polling doesn't work

### ISSUE THREAD

**Issue by trs80** [librenms/librenms#6736]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 337dd4d02ee52e75d1b959dcfff9438403332b3b
DB Schema | 192
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.55-0+deb8u1-log
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

Enterasys switches have slightly munted POE MIBs, rather than using a port index they use module.port - eg this switch is giving results for port 5.48, 6.1. This results in the POE values going into the wrong array in the port_stats array (eg "5.48" rather than "256").

```
POWER-ETHERNET-MIB::pethPsePortPowerPriority.5.48 = INTEGER: low(3)
POWER-ETHERNET-MIB::pethPsePortPowerPriority.6.1 = INTEGER: low(3)
```

Unfortunately the only way I can see to translate them back to an ifIndex is via the ifName array:

`IF-MIB::ifName.256 = STRING: ge.5.48`

Dodgy hacks ahoy. Where would I account for this, somewhere around https://github.com/librenms/librenms/blob/master/includes/polling/ports.inc.php#L250 I guess?

**Comment by trs80** [comment]
Actually reading RFC 3621 the index is defined as { pethPsePortGroupIndex , pethPsePortIndex  } so it is correct to have this breakdown into module (stackable switch in this case) and port within the module. This is a common problem - eg http://www.gsp.com/cgi-bin/man.cgi?section=3&topic=SNMP::Info::CiscoPower "The Info::PowerEthernet class needs a per-device helper function to properly map the pethPsePortTable to ifIndex values." https://sourceforge.net/p/snmp-info/patches/41/

**Comment by kkrumm1** [comment]
I'm in the same boat with HP switches.

**Comment by laf** [comment]
You need to provide all the information asked for in point 3. We will re-open once this info has been provided.

**Comment by trs80** [comment]
discovery: https://p.libren.ms/view/effa4362
poller: https://p.libren.ms/view/6d0c37f1
snmpbulkwalk: http://alfirk.ccgs.wa.edu.au/ipad/snmpbulkwalk-qblock

kkrums' HP snmpbulkwalk: https://gist.github.com/kkrumm1/07639536bb29d001ab7d1eadf920d6d0#file-hp_poe_output

**Comment by laf** [comment]
So it looks like the data we need is in `.1.3.6.1.4.1.5624.1.2.50` from `ENTERASYS-POWER-ETHERNET-EXT-MIB`. If you can finish the walk off with that data we might be able to do something.

**Comment by trs80** [comment]
https://p.libren.ms/view/7d1decd4

It looks similar in that it's module.port again rather than ifIndex. Also it doesn't seem to be supported on the B3/C3 series, only B5 (I don't have any C5).

**Comment by laf** [comment]
Unfortunately the POE support we have at present is Cisco specific. This is going to need a big update to add generic POE support.

I've moved this to https://community.librenms.org/t/enterasys-poe-polling/1713
