### ISSUE TITLE
Add support for Cisco Callmanager registered phones etc.

### ISSUE THREAD

**Issue by trs80** [librenms/librenms#6737]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 337dd4d02ee52e75d1b959dcfff9438403332b3b
DB Schema | 192
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.55-0+deb8u1-log
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

Under 1.3.6.1.4.1.9.9.156.1.5 CISCO-CCM-MIB has various counts, including registered/unregistered/rejected phones, gateways, media devices, CTI devices, voicemail devices. I'm mostly interested in the phones but the others would probably be easy to add too.

Happy to turn this into a feature request, I wasn't clear on whether this was device/OS support or not.

**Comment by laf** [comment]
It's a feature request :)

https://community.librenms.org/c/feature-requests
