### ISSUE TITLE
Timeout with External Script

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#6743]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X ] Please provide as much detail as possible.
- [ X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hi,

OK, I could be wrong, but I assume this is a timeout issue. Trying to use os-updates.sh with a Raspberry PI, so it's pretty slow (~ 10 sec) ... assuming that is causing this issue. If I run the script on the Pi itself, it does work, and provides the correct response as an output. But on LibreNMS (trying to pull the info), it seems to be missing.

Thoughts?

Thanks!

Pastebin for logs,
Discovery: https://paste.ubuntu.com/24703310/
Poller: https://paste.ubuntu.com/24703319/
SNMP: https://paste.ubuntu.com/24703323/
Validate: https://paste.ubuntu.com/24703405/

**Comment by laf** [comment]
GitHub is for bugs and new device requests. Please create a thread on the community forum or ask on irc

**Comment by arrmo** [comment]
OK, NP. I admit, thought this may be a bug - LibreNMS seems to be timing out ... :(.

Thanks.

**Comment by laf** [comment]
You can adjust snmp timeout values if that's what the issue is.

**Comment by arrmo** [comment]
Will do! I went looking for it, didn't find it - but will search again. Thanks!
