### ISSUE TITLE
Reset Sensors

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#6748]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hi,

Not all the debug info here - as it's a question not needing that I think. But yell if I'm wrong.

I upgraded my version of Linux on a client machine, and the sensors seem to have been juggled around - so many of them failing thresholds now. I can manually change all the thresholds, but seems to me better to just reset the sensor information for the client. Is there an easy way to do this?

I tried to turn off the sensor modules (discovery and poller), and run both of these, then turn them back on ... but that didn't seem to do the trick.

Thanks!

**Comment by sorano** [comment]
GitHub issues is for bugs, please do not post issues asking for help or how to do X, Y or Z.

Would be appreciated if you please could close this issue and either post your question on IRC or the community forum.
