### ISSUE TITLE
Feature: Add Searching to Port Type page

### ISSUE THREAD

**Issue by djamp42** [librenms/librenms#6749]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
==========================================================
Component | Version
--------- | -------
LibreNMS  | 6a79d4495f1a5d91d476021b7fb3ab58889e6f80
DB Schema | 192
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

I love the port type feature, but when adding more then a handful of graphs it gets a little overwhelming. It would be nice to be able to search for the following and only have devices matched displayed. Also do not make this an exact match, if i type "LA" only fields i selected with LA anywhere in the selected field would be displayed.  (Don't know what this is called in programing lingo)

Device 	Interface 	  Speed 	Circuit 	Notes

**Comment by laf** [comment]
GitHub is for bugs and new device requests. Please create a thread on the community forum or ask on irc
