### ISSUE TITLE
VLANs not updating on name change

### ISSUE THREAD

**Issue by djamp42** [librenms/librenms#6753]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
==========================================================
Component | Version
--------- | -------
LibreNMS  | dbaad709fe0a3b5f4516b8098982707440996d09
DB Schema | 192
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

I have a Cisco 4900m and 4948. When changing the name of a VLAN on the switch, librenms does NOT update with the new name. I can re-discover the device and see NEW vlans created, but editing existing ones does not work.

**Comment by laf** [comment]
No information provided that's been asked for.

GitHub is for bugs and new device support, please ask for help on the community forums or irc.
