### ISSUE TITLE
New Device: Cisco Unified CM System version: 7.1.5.35901-1

### ISSUE THREAD

**Issue by guoming218** [librenms/librenms#6760]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the ==========================================================
Component | Version
--------- | -------
LibreNMS  | 5af3048a76de6a80461f6af44563493258ea346d
DB Schema | 192
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.55-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================
section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
[Cisco Unified CM discovery.txt](https://github.com/librenms/librenms/files/1041027/Cisco.Unified.CM.discovery.txt)
[Cisco Unified CM Poller.txt](https://github.com/librenms/librenms/files/1041029/Cisco.Unified.CM.Poller.txt)
[Cisco Unified CM SNMPwalk.txt](https://github.com/librenms/librenms/files/1041028/Cisco.Unified.CM.SNMPwalk.txt)
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by trs80** [comment]
So this isn't picked up by the existing CUCM definition as that looks for sysObjectId .1.3.6.1.4.1.9.1.1348 (ciscoUCVirtualMachine) but this has .1.3.6.1.4.1.99.1.1.3.28 which is linuxEMANATEMasterAgent and rather generic.

**Comment by Rosiak** [comment]
fixed in #6813
