### ISSUE TITLE
commit 5af3048a76de6a80461f6af44563493258ea346d breaks distributed pollers

### ISSUE THREAD

**Issue by boudreau** [librenms/librenms#6761]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 79846962814a9be670a966537f52c55ccaa42595
DB Schema | 192
PHP       | 7.0.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.5.6
SNMP      | NET-SNMP 5.7.2

When poller has commit 5af3048a76de6a80461f6af44563493258ea346d active, all rrd files are dumped locally instead of using the master with rrdcached. 

If I checkout the release before on the poller: 48c5e50616aab4a29a72d02391b1294ec9d2aa9e
The rrdcache on the master gets updated and no local RRD file locally on the poller node.

I don't understand why?

**Comment by laf** [comment]
You'll need to provide the info in point 3 so we can see what's happening.

**Comment by boudreau** [comment]
commit 48c5e50616aab4a29a72d02391b1294ec9d2aa9e
./poller.php -h HOSTNAME -r -f -d | ./pbin.sh => https://p.libren.ms/view/0aa4e534
commit master
./poller.php -h HOSTNAME -r -f -d | ./pbin.sh => https://p.libren.ms/view/9ee5febb

**Comment by laf** [comment]
Have you set rrdtool version in config.php?

**Comment by boudreau** [comment]
This is what I have in config.php for rrdtool

more config.php | grep rrdtool
$config['rrdtool_version']                  = "1.6.0";

**Comment by dwynnacs** [comment]
Hi boudreau,

There was a typo introduced into includes/process_config.inc.php where it checks the config variable 'rrdtool_verion' instead of 'rrdtool_version'.

Until this is fixed you can define a 'rrdtool_verion' variable in your config.php and set to anything non-empty.

**Comment by laf** [comment]
Thanks @dwynnacs - all fixed.

**Comment by boudreau** [comment]
Thanks David, 
Works now
