### ISSUE TITLE
force10 switches, wrong info on vlans and no cpu polling

### ISSUE THREAD

**Issue by networkpadawan** [librenms/librenms#6764]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

validate:
Component | Version
--------- | -------
LibreNMS  | f8aadf227b25ff4436859d19062d234ed9134767
DB Schema | 192
PHP       | 7.0.19
MySQL     | 5.5.44-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

daily.sh:
Updating to latest codebase                        OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK

The issue is that on Force10 devices, the vlan informationa appears with a different ID thant the vlan itself:

Vlan 1107787826	instead of Vlan 50
Vlan 1107787876	instead of Vlan 100
Vlan 1107787877	instead of Vlan 101	

And also, no CPU and Memory is fetched. (At least it does not appear in the graphs, all graphs

**Comment by laf** [comment]
You've never or provided the info asked for in point 3. We will reopen this when you have.

**Comment by networkpadawan** [comment]
sorry, here it is:
https://p.libren.ms/view/20f53848
https://p.libren.ms/view/cc0cf67c
https://p.libren.ms/view/5fded688

**Comment by SLMitch** [comment]
Hi,
On my own F10, Vlan is OK for me, but indeed memory and cpu seem's empty.

**Comment by laf** [comment]
Unfortunately that walk doesn't contain any real info for us. Can you run one more walk using `
.1.3.6.1.4.1.` and if that doesn't yield any data then `.1.3.6.1.4.1.674`

**Comment by networkpadawan** [comment]
[oid1.txt](https://github.com/librenms/librenms/files/1065829/oid1.txt)
in attach is the result of .1.3.6.1.4.1.

for the second one, it does not exist
SNMPv2-SMI::enterprises.674 = No Such Object available on this agent at this OID

**Comment by laf** [comment]
@SLMitch what version is your f10 running?

**Comment by laf** [comment]
@networkpadawan can you also provide a walk from `1.3.6.1.2.1.`

**Comment by SLMitch** [comment]
Dell Networking OS 9.10(0.1)  on S4810
Dell Networking OS 9.10(0.1P2) on S3048-ON

**Comment by laf** [comment]
@networkpadawan I wonder the vlan issue is because of the version you run. I'd consider upgrading the firmware first.

**Comment by laf** [comment]
If anyone can get us usable walks of ` .1.3.6.1.4.1.6027` which contains `.1.3.6.1.2.1.1` and `.1.3.6.1.2.1.2.`

**Comment by networkpadawan** [comment]
@laf here it is 
[oid-1.3.6.1.2.1.txt](https://github.com/librenms/librenms/files/1071354/oid-1.3.6.1.2.1.txt)

**Comment by networkpadawan** [comment]
and .1.3.6.1.4.1.6027
[1.3.6.1.4.1.6027.txt](https://github.com/librenms/librenms/files/1072065/1.3.6.1.4.1.6027.txt)

**Comment by networkpadawan** [comment]
any ideas what can be wrong? any more info needed? Can I test something? I have quite a few of these devices installed. Thank you

**Comment by networkpadawan** [comment]
I think I found the issue, FTOS devices are being discovered as DNOS devices.

**Comment by cschoonover91** [comment]
I can confirm VLANs look fine on 9.11(0.0). Can also confirm I'm not getting CPU and memory polling like @SLMitch on 9.11

@networkpadawan : It's not Force10 any more, it's Dell and DNOS9. While we do appear to be missing some data, the discovery classification is correct.

**Comment by networkpadawan** [comment]
@cschoonover91 Dell C300 on 8.x train is still FTOS afaik.

**Comment by laf** [comment]
@networkpadawan Those walks aren't using the correct options, can you re-run with `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .1.3.6.1.2.1.2.`
`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .1.3.6.1.4.1.6027`

**Comment by networkpadawan** [comment]
The output with that command: 
[switch01.txt](https://github.com/librenms/librenms/files/1103530/switch01.txt)

**Comment by laf** [comment]
I'd put two commands in :)

`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .1.3.6.1.2.1.2.`

**Comment by networkpadawan** [comment]
So sorry, thought it was the same example:/ the first one was from 1.3.6.1.4.1.6027, this one is from .1.3.6.1.2.1.2
[2nd.txt](https://github.com/librenms/librenms/files/1103545/2nd.txt)

**Comment by laf** [comment]
Sorry one more: `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .1.3.6.1.2.1.`

**Comment by networkpadawan** [comment]
during the get i got these errors:

Error: OID not increasing: .1.3.6.1.2.1.31.1.2.1.3.1107787826.44876802
 >= .1.3.6.1.2.1.31.1.2.1.3.1107787826.44876802

Error: OID not increasing: .1.3.6.1.2.1.31.1.2.1.3.1107787826.44876802
 >= .1.3.6.1.2.1.31.1.2.1.3.1107787826.44876802

Error: OID not increasing: .1.3.6.1.2.1.31.1.2.1.3.1107787826.44876802
 >= .1.3.6.1.2.1.31.1.2.1.3.1107787826.44876802

here is the full output:
[sw01-1.3.6.1.2.1.txt](https://github.com/librenms/librenms/files/1103629/sw01-1.3.6.1.2.1.txt)

**Comment by laf** [comment]
I won't lie, the ftos/dnos code was a mess, it's not much better in my PR but I think this fixes the broken mem / cpu code we had and also detects the devices as expected.

It would be good if anyone who has these devices can test #6897

@networkpadawan The vlan number issue is an issue from the vendor. They are using random indexes instead of the vlan as the index, we can't fix that and you should complain to the vendor or update to a later code base.

**Comment by networkpadawan** [comment]
how can I test? the build seems to be failing and the git pull is not getting your changes (sorry if its a noob question...) about the vlans, is mostly cosmetic, because if i go on the vlan tab, the vlan description is ok.

**Comment by laf** [comment]
The build itself is fine that's just our CI that has failed. 

Details on how to test are in the pull request description

**Comment by networkpadawan** [comment]
ah ok, how long for the pr to be accepted?
