### ISSUE TITLE
Graphs not populating for some devices

### ISSUE THREAD

**Issue by xXLinNix** [librenms/librenms#6767]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
==========================================================
**Component | Version
--------- | -------
LibreNMS  | cc38930007a2fd82509d1b6aec196b873ad8755a
DB Schema | 193
PHP       | 7.0.18
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  Your local git contains modified files, this could prevent automatic updates.
Modified files:
         poller-wrapper.py

I changed the times in poller-wrapper.py "300" to "120"
The issue was occurring before this change**

- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
**https://p.libren.ms/view/bbe8b262
https://p.libren.ms/view/58e1c555
{error for this command snmpbulkwalk -OUneb -v2c -c public 10.0.6.230 .  | ./pbin.sh**

- [X] Please provide as much detail as possible.
**I have a device's that are not graphing the ports. Some devices are working.  I've checked firmware and NTP.  I can see usage on the broken graphed devices. (see screenshot)
Other devices are graphing fine.  I thought it may have been a time issue but that has been ruled out after updating the timezone and date via NTP.
Here is a screenshot: http://imgur.com/a/BPiBo
NOTE that 10.0.6.230 is the device that is broken.**

- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment]
GitHub is for bugs and new device support. Please post on irc or the community site.
