### ISSUE TITLE
Refreshing device groups on new device (device change/cron)?

### ISSUE THREAD

**Issue by YenzRanger** [librenms/librenms#6768]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 528350177de651691e848dd87d0f2923934a6578
DB Schema | 193
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Brief summary, why this is important to me:
I map my alert rules against device groups in order that not every rule fires an alert on every device.
As a device group I have simple patterns like `%devices.type = "network" &&` (which is more or less static until I manually change the type of a host) or %devices.status != "1" && (which was a test to only view devices that weren't up and running).

With the current solution I've the following problem:
If a new device is added, e.g. a Cisco network switch, it will auto set to device type network, but never shows up in the network device group (with the afore-noted pattern).
So I've a network device which shows up on `/devices/type=network/`, but not on `/devices/group=8/` (group id 8 is `%devices.type = "network" &&`). And because of the missing group membership I'd never get any alerts which are mapped to the network device group.

I've checked if the daily cron job ensures the data integrity, but that isn't the case.

Not sure if this is a bug or a feature request, but in my opinion I would expect the current behavior:
Every time a new device is added/changed/polled it must update its group memberships.
If such a dynamic way of device groups is not wanted (because of computing time), then maybe as a cron job freely configurable via crontab which does the job for all devices and groups.

**Comment by laf** [comment]
Thank you so much for the thorough details - however I have just tested this and it does work as expected so this isn't a bug.

Please post on irc or the community site for further help.

**Comment by YenzRanger** [comment]
Ok, I've opened a topic on the community site: https://community.librenms.org/t/issue-refreshing-device-groups-on-new-device-device-change-cron/1393
