### ISSUE TITLE
Add support for HP 5406zl Power Supply and Fans

### ISSUE THREAD

**Issue by kkrumm1** [librenms/librenms#6788]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the
==========================================================
Component | Version
--------- | -------
LibreNMS  | 4b15713f699db1b68fd30691a6795d639667f0db
DB Schema | 194
PHP       | 7.0.18
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================
[OK]    Database connection successful
[OK]    Database schema correct
` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
Discovery: https://p.libren.ms/view/bd1978ad
Poller: https://p.libren.ms/view/1968585d
SNMP Walk: https://gist.github.com/kkrumm1/eb655e833a3ec50eb9314000bb7f2eab

hpicfSensorDescr 1.3.6.1.4.1.11.2.14.11.1.2.6.1.7
-- Identifies sensors for the chassis fans and power supplies.
hpicfSensorStatus 1.3.6.1.4.1.11.2.14.11.1.2.6.1.4
-- For power supplies, this SNMP object reports a status of "good" when the unit is powered, "bad" when the RPS is unpowered or "notPresent" when the power bay is empty.

HP Link: http://h20564.www2.hpe.com/hpsc/doc/public/display?docId=emr_na-c02597265&sp4ts.oid=3457354

**Comment by laf** [comment]
I've submitted a PR, feel free to test: #6814

**Comment by kkrumm1** [comment]
thank you laf, just did test pull looks like its working.
