### ISSUE TITLE
Wireless support for ExtremeWireless controller

### ISSUE THREAD

**Issue by trs80** [librenms/librenms#6791]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 4b15713f699db1b68fd30691a6795d639667f0db
DB Schema | 194
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.55-0+deb8u1-log
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

MIBs are at https://extrcdn.extremenetworks.com/wp-content/uploads/resources/mibs/mibs.zip in particular the third_party/siemens/HIPATH-WIRELESS-* (also as a side note the existing CTRON mibs could be moved into the enterasys directory). extreme.svg is fine as a the logo. System OID  enterprises.4329.15.1.1.13 

discovery: https://p.libren.ms/view/32830290
poller: too big for pastebin, http://alfirk.ccgs.wa.edu.au/ipad/antennae-a-poller
snmpbulkwalk: too big for pastebin, http://alfirk.ccgs.wa.edu.au/ipad/antennae-a-snmpbulkwalk

**Comment by laf** [comment]
I'm not sure your data includes what we need.Try and re-run it with just  `.1.3.6.1.4.1.4329` specified.

**Comment by trs80** [comment]
Looks like there was an infinite loop at the end of `.1.3.6.1.4.1.4329.15.3.1`, here's the rest: http://alfirk.ccgs.wa.edu.au/ipad/antennae-a-snmpbulkwalk-15.3.2-15.3.30

@murrant I had some questions about how to implement this, in particular is a sensor an AP, an SSID, a radio? Unifi seems to do both SSID and radio. Although for Unifi it seems you still add the individual APs as devices? Can or should I also return a sensor with the total client count, or is that more for implementations that aren't broken down like HP/Cisco?

**Comment by murrant** [comment]
Right now controller access point stuff isn't really integrated with the new wireless sensor code yet. 

Xirrus and ciscowlc implement the current wireless controller code.

**Comment by trs80** [comment]
https://github.com/librenms/librenms/pull/6819

**Comment by murrant** [comment]
Closing this since your initial support was added :)
