### ISSUE TITLE
Spelling mistake in BIND application module

### ISSUE THREAD

**Issue by fjwcash** [librenms/librenms#6794]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ X ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 4b15713f699db1b68fd30691a6795d639667f0db

This file has a spelling mistake in it:

html/pages/device/apps/bind.inc.php:

Missing the "e" in Queries:

[/opt/librenms]# grep -R "Resolver Quiries Sent/Received" *
html/pages/device/apps/bind.inc.php:    'bind_resolver_qrs' => 'Resolver Quiries Sent/Received',

Very simple fix.  :)

**Comment by laf** [comment]
Please submit the fix :)

**Comment by fjwcash** [comment]
Do you need more than this?  I'm very new to GIT:

--- a/html/pages/device/apps/bind.inc.php
+++ b/html/pages/device/apps/bind.inc.php
@@ -34,7 +34,7 @@ $graphs = array(
     'bind_rr_negative' => 'RR Sets Negative',
     'bind_rtt' => 'Resolver RTT',
     'bind_resolver_failure' => 'Resolver Failures',
-    'bind_resolver_qrs' => 'Resolver Quiries Sent/Received',
+    'bind_resolver_qrs' => 'Resolver Queries Sent/Received',
     'bind_resolver_naf' => 'NS Query Status',
     'bind_server_received' => 'Server Queries/Requests Received',
     'bind_server_results' => 'Server Results',

**Comment by laf** [comment]
Nope, that's fine. You can just click edit on the file in github and submit it directly.

https://github.com/librenms/librenms/edit/master/html/pages/device/apps/bind.inc.php

**Comment by fjwcash** [comment]
Okay, done.  See:
https://github.com/librenms/librenms/pull/6795

**Comment by laf** [comment]
Ace :) Just need to sign the CLA and it's all done.

**Comment by fjwcash** [comment]
Signed.
