### ISSUE TITLE
RRD files not removed when deleting device

### ISSUE THREAD

**Issue by laf** [librenms/librenms#68]
When deleting a device from the web interface, the rrd files and directories aren't removed. This will be due to those folders and files being owned by the user that the poller runs as (root).

**Comment by f0o** [comment]
```php
shell_exec("rm -rf ".trim($config['rrd_dir'])."/$host");
```

This is included in `delete_device($id)` (File: `includes/functions.php` Line: 249)

So really the fix relies in POSIX permissions.

I suggest:
1.  create a librenms user
2.  add the httpd's user to the librenms group
3.  let the cronfile run with that uid/gid
4.  let the poller `chmod 775` all new files

If that's too much to ask for, we can add a very ugly `chmod 777` over all newly created rrds. I wouldnt like this!

**Comment by paulgear** [comment]
Let's just forget you ever mentioned chmod 777 and move along. :-)

**Comment by laf** [comment]
lol, also those steps are manual for existing installs.

What about dealing with it in the poller like blahdeblah said? May require another column to the DB though.

**Comment by f0o** [comment]
yes, it requires another column. Not that it would be an issue, I just think that on the long-run we shouldnt let the poller run as root... it's not really sane...

**Comment by paulgear** [comment]
I fully agree that running the poller as root is undesirable, but I think that it may have to due to use of fping.

**Comment by f0o** [comment]
@paulgear : fping has suid flag on upstream debian and centos. This shouldnt be an issue then

I also recall somebody on the IRC saying he uses the cron as nonroot already.. Will ask for bugs or wether it works outofthebox

**Comment by f0o** [comment]
Shorty from IRC said it worked outofthebox, he's running the cronjobs with same user as his apache.

**Comment by laf** [comment]
Is it worth looking at how we can migrate people to running as a non-root user?

One of the challenges will be that we had in the docs to symlink the cron file for quite a while, this means if we updated that file then it would break a lot of installs. We could have a second cron file we reference from now on and have that as part of the instructions creating a librenms user (people can change this user).

Thoughts?

**Comment by paulgear** [comment]
I agree - we need to aim for migrating the poller to non-root.

**Comment by laf** [comment]
@f0o would you mind re-opening the PR you did for this with a few changes:

create a new file called cron.librenms (or another name that fits?) and also add a note to the top:
# Using this cron file requires an additional user on your system, please see install docs.

update the install docs to tell people to copy that new file rather than librenms.cron

Add a note into librenms.cron that says:

# It's recommended not to run this cron anymore - please see cron.librenms

**Comment by laf** [comment]
Ok, tested. works fine. Current installs will continue to function but instructions show how to install with separate user.

**Comment by f0o** [comment]
So, Closing?

**Comment by laf** [comment]
Yeah :)

**Comment by laf** [comment]
Actually, still having issues with it removing rrd files :/

**Comment by laf** [comment]
So @f0o actually I've had to make some changes. The device I tested it on had lax perms so it just deleted :/

umask(0000);

chmod 776 rrd/

With those it now works for me - thoughts?

**Comment by laf** [comment]
All sorted thanks to @f0o :)

**Comment by robimarko** [comment]
Yeah,just messed whole graphing for me.
After I deleted device all of graphing just broke.

**Comment by smounives** [comment]
still have this issue

**Comment by f0o** [comment]
It's most definitely a config issue. Be sure that the user running the GUI has enough privileges to delete files created by the librenms user.

**Comment by murrant** [comment]
FYI, from new install docs:
```
chown -R librenms:librenms /opt/librenms
setfacl -d -m g::rwx /opt/librenms/rrd /opt/librenms/logs
setfacl -R -m g::rwx /opt/librenms/rrd /opt/librenms/logs

#SELinux
semanage fcontext -a -t httpd_sys_content_t '/opt/librenms/rrd(/.*)?'
semanage fcontext -a -t httpd_sys_rw_content_t '/opt/librenms/rrd(/.*)?'
restorecon -RFvv /opt/librenms/rrd/
```
