### ISSUE TITLE
Eventlog is filled with "Sensor updated:" lines

### ISSUE THREAD

**Issue by einarjh** [librenms/librenms#6800]
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
```
==========================================================
Component | Version
--------- | -------
LibreNMS  | 5581c40e1989d32436d06e3161b2bedf115b5c20
DB Schema | 194
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

[OK]    Database connection successful
[OK]    Database schema correct
```
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- no information is asked for there, are you guys sure that's the right anchor?
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
---
My eventlog shows the following line every polling cycle (every five minutes), essentially flooding out all other information:
> Sensor Updated: temperature hddtemp 5 /dev/sdf: Kingston SHPM2280P2H/240 G 

Note the broken UTF-8 character at the end, it seems to be U+FFFD (replacement character), but I'm not sure, it's represented differently in various places. 
The disk is listed as `/dev/disk/by-id/ata-Kingston_SHPM2280P2H_240G_5002xxxxxxxxx` on the system, and hdparm lists it as `Model=Kingston SHPM2280P2H/240G, FwRev=0C4005T2, SerialNo=5002xxxxxxxxx`.
Here are the relevant lines from `./poller.php -h host -d`:
```
Discover sensor: , 5, hddtemp, /dev/sdf: Kingston SHPM2280P2H/240 G �, agent, 1, 1, , 36
SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'agent' AND `sensor_class` = 'temperature' AND `device_id` = '15' AND sensor_type = 'hddtemp' AND `sensor_index` = '5'] 
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = 'temperature' AND `device_id` = '15' AND `sensor_type` = 'hddtemp' AND `sensor_index` = '5'] 
SQL[UPDATE `sensors` set `sensor_oid` ='',`sensor_descr` ='/dev/sdf: Kingston SHPM2280P2H/240 G �',`sensor_multiplier` ='1',`sensor_divisor` ='1',`entPhysicalIndex` ='',`entPhysicalIndex_measured` ='',`user_func` ='' WHERE `sensor_id` = '53'] 
USQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`severity`,`message`,`username`)  VALUES ('15','15','NULL','sensor',NOW(),'3','Sensor Updated: temperature hddtemp 5 /dev/sdf: Kingston SHPM2280P2H/240 G �','')] 
( 0 updated )
SQL[UPDATE `sensors` set `sensor_current` ='36' WHERE `sensor_index` = '5', `sensor_class` = 'temperature', `poller_type` = 'agent', `device_id` = '15'] 
SQL[SELECT * FROM `sensors` WHERE `sensor_index` = '5' AND `device_id` = '15' AND `sensor_class` = 'temperature' AND `poller_type` = 'agent' AND `sensor_deleted` = 0 LIMIT 1]
```
I've tried ignoring the faulty sensor with the following config entry, but it doesn't seem to have any effect:
`$config['bad_entity_sensor_regex'][] = '/\/dev\/sdf: Kingston SHPM2280P2H.+/';`

**Comment by laf** [comment]
Point 3 takes you to text which has:

```
./discovery.php -h HOSTNAME -d | ./pbin.sh
./poller.php -h HOSTNAME -r -f -d | ./pbin.sh
snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh
```

We do need that, however I'm not sure if this should be classed as a bug or not as I expect that this is being sent back from the device. However provide the info asked for and we can take a look, if it's a bug we will re-open.

**Comment by einarjh** [comment]
Ah. I see. The point talked about how to add support for a new OS, so I discounted the information.
You're asking for a public disclosure of a complete inventory of my device, is there a way I can either upload it to a non public place or omit most of it?

**Comment by laf** [comment]
You are more than welcome to sanitise the info, mainly we only need the poller debug and you can add `-m sensors` to that and restrict the data further but I don't personally accept private posting as the onus is on me to fix it then.

**Comment by einarjh** [comment]
I looked at the info from adding `-m sensors` and I couldn't find the lines with the odd unicode character or anything. Looking at the full poller log, I see now that the issue is with the unix-agent, which calls hddtemp, and hddtemp outputs the strange character. 
I'll see if I can either get the unix-agent to sanitize it's output or possibly register a bug for hddtemp.
Thanks for your help!
