### ISSUE TITLE
Incorrect toner levels (constant 50%) for Ricoh C430DN printers, suspect wrong OIDs being used

### ISSUE THREAD

**Issue by irrationalforest** [librenms/librenms#6801]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hi there,

Our fleet of Ricoh printers (mostly C430DN and some 3000 series) all report 50% toner at all times, for all types.
I can see that the following OIDs have sane integers listed when I snmpwalk manually:

```
1.3.6.1.4.1.367.3.2.1.2.24.1.1.5.1 – Black
1.3.6.1.4.1.367.3.2.1.2.24.1.1.5.2 – Cyan
1.3.6.1.4.1.367.3.2.1.2.24.1.1.5.3 – Magenta
1.3.6.1.4.1.367.3.2.1.2.24.1.1.5.4 – Yellow
```

So I suspect that Libre might be looking at a different (possibly incorrect) set?
Any ideas on how to fix this, or if it's a bug etc, would be much appreciated.

Thanks!

```
==========================================================
Component | Version
--------- | -------
LibreNMS  | 5581c40e1989d32436d06e3161b2bedf115b5c20
DB Schema | 194
PHP       | 7.0.18-0ubuntu0.16.04.1
MySQL     | 5.7.18-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================
```

https://p.libren.ms/view/7b9053cd
https://p.libren.ms/view/bbbe366d
https://p.libren.ms/view/26b3164c

**Comment by laf** [comment]
This is more a case of a vendor thinking they know best on snmp and rather than implementing a MIB from the Printer working group they've done it themselves :/

I've submitted a fix anyway

**Comment by irrationalforest** [comment]
Given my experience with Ricoh, I am... profoundly unsurprised. ;)

Thank you very much for submitting the change request, it is much appreciated!

**Comment by irrationalforest** [comment]
Hi laf,

I've tested the changes in the PR from git, which certainly does change the values I'm seeing. They're still a bit weird however, as per the screenshots.
I've walked the values in my post above in order, but they don't seem to match what shows up in Libre now.

Thanks for your help. Nobody gets paid for this, so I really do appreciate the effort.

Kind regards.
![walks](https://user-images.githubusercontent.com/29267039/26962395-0905acda-4d25-11e7-9956-06fa01c4a7e6.JPG)
![libre toner](https://user-images.githubusercontent.com/29267039/26962401-1024f9e4-4d25-11e7-83db-a76ac09b9214.JPG)

**Comment by laf** [comment]
So Ricoh seem to hide the MIBs behind a login, I've requested access but it could be days. Do you have the Ricoh mibs?

**Comment by irrationalforest** [comment]
Hi Laf,

Unfortunately no, I don't have the MIBs.
Perhaps I'm misunderstanding something about how Libre does it's collection, but the values from my snmpwalk seem correct - that is they correspond exactly to the physical Black, Cyan, Magenta, and Yellow toner levels, in that order.
It appears that they are only mixed up in the UI, showing the right value against the wrong colour. Although I still have no idea why there is a fifth toner listed? :)

Is there anything else I can do on my end to assist, or help work through this?
Thanks in advance!

Kind regards.

**Comment by laf** [comment]
The issue is that they have literally re implemented the standard mib in there own way, this means we've got to do specific detection for this now with the added downside of not knowing if this is specific to this ricoh model or software version and in turn breaking other users installs.

**Comment by irrationalforest** [comment]
Ah, I understand - thank you for taking the time to explain the issue.
That's not a great move by Ricoh, for sure!
I'll email their support to see if they can be of any help in getting reliable information. We have ~40 of their printers, so hopefully they might be inclined to provide at least some assistance.

Kind regards.

**Comment by laf** [comment]
Have you heard from the Ricoh support? Contrary to them saying that I'd receive a response in 3 business days, it's been about 5+ with no word.

**Comment by irrationalforest** [comment]
Hi Laf,
Ricoh supposedly escalated the issue a week ago, but I heard nothing back from them.
I have called them again today, and they promised to have their National Technical Services team give me a call back, so I'll update here when that happens.
They also suggested (of course) that we should be using their monitoring solution, which involves a piece of proprietary hardware. That didn't fly.

Kind regards.

**Comment by laf** [comment]
That makes some sense in way they are hiding the MIBs.

Keep us up to date with how you get on.

**Comment by irrationalforest** [comment]
Hi Laf,

I've got the (pretty extensive) proprietary MIBs from Ricoh, which are are marked "confidential" at the bottom of each page. :P

In the Spec 4 document, toner information is on pages 213 and 214. However there's a lot of other useful stuff in there too, much of which is either reported differently or not at all in the Standard MIBs.

Sorry to be a pain, but I've dropped you a quick email to chat about this.

Kind regards.

**Comment by laf** [comment]
As per my reply on email, that's just a pdf with info on how the MIB works.

Without the mib we can't do much further. We can re-open this once more info is provided.

**Comment by irrationalforest** [comment]
Hi Neil,

Sorry for not getting back to you earlier.
You're absolutely right, of course.

I keep emailing Ricoh, but they have now completely stopped responding -
apart from our sales manager.
Sad to say, I think we're going to switch completely away from them for our
printer fleet at the end of the year. There have been other issues, but
this unwillingness to work with anyone on an NMS solution is the straw that
breaks the camel's back.
Not to mention that they keep pushing their own (paid) NMS solution, which
will monitor nothing but Ricoh devices. Leaves a bad taste in one's mouth.

Thanks for all your help, and I'll let you know immediately if they do ever
get back to me with the MIB.
Be well.

Kind regards,
Dominic Ashfield
