### ISSUE TITLE
php-net-ipv4 not available any more on current debian and ubuntu

### ISSUE THREAD

**Issue by Polve** [librenms/librenms#6818]
The documentation states to install php-net-ipv4 among other packages:

> apt-get install libapache2-mod-php7.0 php7.0-cli php7.0-mysql php7.0-gd php7.0-snmp php-pear php7.0-curl snmp graphviz php7.0-mcrypt php7.0-json apache2 fping imagemagick whois mtr-tiny nmap python-mysqldb snmpd php-net-ipv4 php-net-ipv6 rrdtool git

But current debian release (stretch+) and Ubuntu (zesty+) does not include the package any more, so the command fails.

IDK why this package was dropped, but maybe it's best if you include directly in your sources?

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3

zesty isn't an LTS release so we don't currently support it as such, the install docs cover 16.04 and do work. This is the recommended approach.

**Comment by russula** [comment]
LibreNMS needs php-net-ipv4 but this isn’t in the Zesty repositories. Instead we use pear to install it.

`pear install Net_IPV4`
