### ISSUE TITLE
Postgres App 'Totals' graphs show NaN, while individual DBs have working graphs

### ISSUE THREAD

**Issue by RedChops** [librenms/librenms#6821]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 51ccec94c519b32fd098bce27904a8612e224641
DB Schema | 194
PHP       | 7.0.19-1
MySQL     | 10.0.28-MariaDB-2
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
discovery.php: https://p.libren.ms/view/32ec587e
poller.php: https://p.libren.ms/view/b2cea73c
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

As specified in the title: On four separate servers all running the same database configuration, the graphs display the data properly if I click through to the individual databases. If I view the default 'Totals' page, however, all the graphs display NaN.

**Comment by RedChops** [comment]
I would suspect it has to do with the script itself returning values in scientific notation, as seen here:
`NET-SNMP-EXTEND-MIB::nsExtendOutputFull."postgres" = STRING: 22
11382190
6834
710780903
1.69801e+10
0
0
0
0
0
0
0
2.7805e+11
1.34464e+11
1147859078
18357
522737666`

However, my AWK-foo is nonexistent, so I'm not sure how to fix that. The individual databases just have full integer values, no scientific notation there.

**Comment by laf** [comment]
That's possibly got nothing to do with the values returned.

Click the graph that's showing NaN and click show rrd command, pastebin the output you see.

**Comment by RedChops** [comment]
I had fixed this in my own installation between then and now but I forgot to update this bug. What I ended up doing was adding 'OFMT = "%.0f"' to the END block in the postgres script to make sure it didn't return any extended notation numbers. After I did that, all the graphs started drawing properly.

**Comment by laf** [comment]
Can you submit that fix to the librenms-agent repo?

**Comment by RedChops** [comment]
PR is here https://github.com/librenms/librenms-agent/pull/138
