### ISSUE TITLE
'Set global default dashboard id' list empty, even though I have shared dashboards defined

### ISSUE THREAD

**Issue by fseesink** [librenms/librenms#6822]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
```
==========================================================
Component | Version
--------- | -------
LibreNMS  | 6a79d4495f1a5d91d476021b7fb3ab58889e6f80
DB Schema | 194
PHP       | 7.0.18-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

```
- [ x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
`Done, as none asked there.  This link may be out of date, as it lands me on the 'What can I do to help?' section of that page, which doesn't ask for info.`
- [ x ] Please provide as much detail as possible.
`See below.`
- [ x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

## Details

Hope I'm doing this right by including all the info above in the post.
First and foremost, thank you SOOOO much for creating this software.  I have been just giddy with all the features included and it works absolutely fantastically!  (It crushes the 10+ year old hand-built MRTG setup I did and does so much more!)  So again, THANK YOU.  And I will try to help when/where I can.
Second, LibreNMS has been running rock-solid thus far.

As for the issue at hand, I installed LibreNMS last week using the latest release, configuring it to stick to stable releases for now.  Thus far my setup looks like this as I type this:

VM running under VMware ESXi on a Cisco UCS at work
Ubuntu 16.04.2 LTS server
Webserver:  nginx
4 cores
12 GB RAM
293 devices polled (thank you, API!)

I have things configured to use Active Directory (AD) authentication.  I mention this as my research before posting here showed that at different points in the past, using AD authentication was the source of such issues as not being able to create dashboards since users weren't in the MySQL database, etc.  Those issue have all been resolved, but I wonder if this somehow plays into this.

Anyway, key point here is that once I had the basics up and running, I started fine tuning our setup.  I have implemented RRDcached, for example, changed the logo, etc., all working my way through docs like the configuration page:  http://docs.librenms.org/Support/Configuration/

On that page, they mention there is the section
...
```
// This option exists in the web UI, edit it under Global Settings -> webui
$config['webui']['default_dashboard_id'] = 0;
```
`Allows the specification of a global default dashboard page for any user who has not set one in their user preferences. Should be set to dashboard_id of an existing dashboard that is shared or shared(read). Otherwise, the system will automatically create each user an empty dashboard called Default on their first login.`
...

But when I go in the GUI to **Global Settings**, then the **Webui Settings** and look under **Dashboard settings**, the drop-down list shows 'no default dashboard', but no other options.

As an admin, I have created multiple dashboards, and I've tried setting them as 'Shared (Read)' and even just 'Shared', but nothing I do populates this drop-down with any options.

Am I missing something here?  Do I need to specify something in the config.php file?  (And if so, how do I determine the number to put for that variable?)

Or is it, as I suspect, possibly due to the fact I'm using AD authentication, and though there are dummy accounts/etc., somehow this prevents the ability to have dashboards users create from showing up in that drop-down to be used as a possible global default?

Anyway, thanks in advance for any/all insight into this.  And don't hesitate to ask me for further info on this, as I have no trouble digging in.  I am really enjoying working with this software.

**Comment by fseesink** [comment]
Ok, as I'm not one to sit around, kept digging.  Found the link to the community pages and started searching there.  Well lo and behold I found this page:

https://community.librenms.org/t/user-survey-results-may-2017/1229

on which there's a bullet point
`- Ability to set a global default dashboard when using AD authentication (feature doesn't work through GUI).`

So I guess that kinda answers my question to some extent.  It's a known issue.  I'm fine adjusting this in config.php for now.  My only question would be, how do I determine the number to use?  I then went off to find that answer, and while you can get down and dirty and find this number buried in the database in the **dashboards** table, you'll still have to figure out which one if there are multiple with the same name.

Well, for anyone who finds this issue, here's what I found to work for now.  The easy option is to login, then navigate to **Overview** | **Dashboard**.  Now by default you'll land on the URL

<LibreNMSsite>/overview

but if you switch back/forth between dashboards, you'll find for each dashboard the URL changes to

<LibreNMSsite>/overview/dashboard=#

where # is the number of the dashboard.  So find the dashboard you wish to make your global default and note the number shown.

Then, just put this into config.php as
```
$config['webui']['default_dashboard_id'] = #;
```
again, replacing '#' with the actual number.  And voila!

Worked like a charm.

Mind you, I'd still like to have that drop-down list populate with all shared dashboards to make it easier to set (which just looks to be a simple query to generate the appropriate data), but at least this lets me do what I was after:  provide a default dashboard to new users we create.

**Comment by laf** [comment]
Thanks for the detailed issue and responses.

I'm closing this as it looks like you've found the answer - feel to start further threads on the community site.

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/dashboard-home-site-issues/13044/1
