### ISSUE TITLE
validate errors.

### ISSUE THREAD

**Issue by thomasraabo** [librenms/librenms#6826]
==========================================================
Component | Version
--------- | -------
LibreNMS  | 5c58cc011ad5fa8a47f7242ce4cf2df317726a96
DB Schema | 194
PHP       | 5.4.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful
[FAIL]  Database: incorrect column (dbSchema/version)
[FAIL]  Database: missing index (dbSchema/PRIMARY)
[FAIL]  Database: missing column (users/remember_token)
[FAIL]  Database: missing column (users/updated_at)
[FAIL]  We have detected that your database schema may be wrong, please report the following to us on IRC or the community site (https://t.libren.ms/5gscd):
         ALTER TABLE `dbSchema` CHANGE `version` `version` int(11) NOT NULL DEFAULT '0';
         ALTER TABLE `dbSchema` ADD PRIMARY KEY (`version`);
         ALTER TABLE `users` ADD `remember_token` varchar(100) NULL AFTER `realname`;
         ALTER TABLE `users` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `remember_token`;

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
