### ISSUE TITLE
mini graph try to display interfaces in $config['bad_if_regexp'][] 

### ISSUE THREAD

**Issue by boudreau** [librenms/librenms#6839]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | f72e2ce4b1d8a861f4ac6bc3b0463e3e0e88aa62
DB Schema | 195
PHP       | 7.0.17
MySQL     | 10.1.22-MariaDB
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.2

In the port section of an IOS device.

I don't see the interfaces listes under this section in config.php:

$config['bad_if_regexp'][]              = '/^Null[0-9]$/';  
$config['bad_if_regexp'][]              = '/^Loopback[0-9]*$/';  
$config['bad_if_regexp'][]              = '/^StackPort[0-9]$/';  
$config['bad_if_regexp'][]              = '/^StackSub-St[0-9]-[0-9]$/';  
$config['bad_if_regexp'][]              = '/^NDE_vlan[0-9]+$/';  
$config['bad_if_regexp'][]              = '/^Control Plane Interface$/';  

The Null0 and lookback0 show up under the mini graph in the port section.
 
When I look at the mini graph they show up as a red bar graph and on the hover, it mentions  error drawing graph.

They should not show up at all from my point of view.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
