### ISSUE TITLE
Support for HIKVISION camera removed ?

### ISSUE THREAD

**Issue by stylersnico** [librenms/librenms#6841]
Hi,

# Librenms release : 

Component | Version
--------- | -------
LibreNMS  | f72e2ce4b1d8a861f4ac6bc3b0463e3e0e88aa62
DB Schema | 195
PHP       | 5.6.30-0+deb8u1
MySQL     | 10.0.30-MariaDB-0+deb8u2
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

# Hardware : 

HIKVISION camera : DS-2CD2742FWD-IS

# Problem : 
Seems to have been added in previous PR but I don't have any MIBS for HIKVISION in my Librenms installation 

- https://github.com/librenms/librenms/issues?utf8=%E2%9C%93&q=hikvision

This support has been added and removed ?

# MIBS : 

I found some mibs for the camera  : http://www.hikvision.msk.ru/_fr/12/HIK-DEVICE-MIB.txt

Thanks in advance

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
