### ISSUE TITLE
Bug with parsing infeeds on Sentry3 PDU.

### ISSUE THREAD

**Issue by joelsdc** [librenms/librenms#6842]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli:

```
Component | Version
--------- | -------
LibreNMS  | f72e2ce4b1d8a861f4ac6bc3b0463e3e0e88aa62
DB Schema | 195
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
```

- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

Discovery: https://p.libren.ms/view/14abb050
Poller: https://p.libren.ms/view/a51323eb
SNMPWalk: https://p.libren.ms/view/df090d29

- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

When LibreNMS is discovering a Sentry3 PDU, it first looks for the towers, then for the infeeds per tower. This parsing has some problems as it can detect multiple towers, but not infeeds (although there is code to search for possible multiple infeeds)

I have tried to find the problem, and in my test I think the problems could be in the sentry3.inc.php file.

Step 1: Get the towers:

File -> includes/discovery/sensors/current/sentry3.inc.php (line 8):

`$tower_count = snmp_get($device, 'systemTowerCount.0', '-Ovq', 'Sentry3-MIB');`

SNMP equivalent: 

```
root@nms:/opt/librenms# snmpget -v2c -c COMMUNITY -Oqv -M /opt/librenms/mibs:/opt/librenms/mibs/sentry -m Sentry3-MIB udp:172.17.12.248:161 systemTowerCount.0
2
root@nms:/opt/librenms#
```

*** So we have 2 towers.

Step 2: Get the infeeds per tower.

File -> includes/discovery/sensors/current/sentry3.inc.php (line 12):

`$infeed_oids = snmp_walk($device, "infeedID.$towers.1", '-Osqn', 'Sentry3-MIB');`

the index ".1" is hardcoded, therefor any remaining infeeds would never be parsed:

```
Tower index 1:

root@nms:/opt/librenms# snmpwalk -v2c -c COMMUNITY -Osqn -M /opt/librenms/mibs:/opt/librenms/mibs/sentry -m Sentry3-MIB 12pdu1.la2.gogii.net infeedID.1.1
.1.3.6.1.4.1.1718.3.2.2.1.2.1.1 AA
root@nms:/opt/librenms#

Tower index 2:

root@nms:/opt/librenms# snmpwalk -v2c -c COMMUNITY -Osqn -M /opt/librenms/mibs:/opt/librenms/mibs/sentry -m Sentry3-MIB 12pdu1.la2.gogii.net infeedID.2.1
.1.3.6.1.4.1.1718.3.2.2.1.2.2.1 BA
root@nms:/opt/librenms#
```

If we remove the hardcoded ".1" index, then we get the correct list:

```
Tower index 1:

root@nms:/opt/librenms# snmpwalk -v2c -c COMMUNITY -Osqn -M /opt/librenms/mibs:/opt/librenms/mibs/sentry -m Sentry3-MIB 12pdu1.la2.gogii.net infeedID.1
.1.3.6.1.4.1.1718.3.2.2.1.2.1.1 AA
.1.3.6.1.4.1.1718.3.2.2.1.2.1.2 AB
.1.3.6.1.4.1.1718.3.2.2.1.2.1.3 AC
root@nms:/opt/librenms#

Tower index 2:

root@nms:/opt/librenms# snmpwalk -v2c -c COMMUNITY -Osqn -M /opt/librenms/mibs:/opt/librenms/mibs/sentry -m Sentry3-MIB 12pdu1.la2.gogii.net infeedID.2
.1.3.6.1.4.1.1718.3.2.2.1.2.2.1 BA
root@nms:/opt/librenms#
```

Ok, with that little change, we get the correct number of infeeds, I tried running the discovery with that change applied, and it detects 3 infeeds for tower 1 correctly, but there must be more stuff as after discovering/polling, the GUI still shows only 1 infeed per tower.

I'm pretty sure I'm on the right track, I just don't know PHP so it's not easy dig further to find the full solution :(

Please let me know if you need any extra information or if I can help with any tests.

BTW: The Sentry3-MIB shipped with LibreNMS is from 2009, the latest version is from 2016, not sure if that could have anything to do also...

Thank you.

**Comment by laf** [comment]
You should provide your code as a diff to what we have.

If you have the newer MIB, please provide that.

**Comment by joelsdc** [comment]
Hi, 

These are the latest MIBs:

[Sentry3-MIB.txt](https://github.com/librenms/librenms/files/1075928/Sentry3-MIB.txt)
[Sentry4-MIB.txt](https://github.com/librenms/librenms/files/1075927/Sentry4-MIB.txt)

Regarding the patch:

[sentry3_infeed_snmpwalk.patch.txt](https://github.com/librenms/librenms/files/1075948/sentry3_infeed_snmpwalk.patch.txt)

Now, although with that patch, the discover does seem to recognize all the infeeds, and gathers the different data for each one, the GUI still is only showing one infeed for each tower.

Discovery (with patch applied): https://p.libren.ms/view/f642888b (you will see that we have AA, AB, AC for tower 1, and BA for tower 2).

I'm definitely still missing stuff.

Without the patch:

1. Discovery command reports:
* Towers: 2
* Infeeds: AA (tower 1), BA (tower 2)

2. GUI shows:
* Towers: 2
* Infeeds: AA, BA  <<<< (Note: the first infeed out of three is shown for tower 1, which matches what the discovery found)

With the patch:

1. Discovery command reports:
* Towers: 2
* Infeeds: AA (tower 1), AB (tower 1), AC (tower 1), BA (tower 2)

2. GUI:
* Towers: 2
* IInfeeds: AC, BA  <<<< (Note: this time the last infeed is shown, although discovery did detect three infeeds for tower 1)

**Comment by laf** [comment]
I've not looked at your patch yet but from what you've just said, seems like what's passed to discover_sensor() as the $index value isn't unique. Currently `$towers` is being used to populate `$index`, I would change this to be `infeedID.$towers.$infeed_index` to assure uniqueness

**Comment by joelsdc** [comment]
Yup! that is what I did in the patch. And that solves the discovery, but in the GUI, it still shows only 1 infeed.

Looking a little more at the discovery.php output, I found this:

```
Discover sensor: .1.3.6.1.4.1.1718.3.2.2.1.7.1.1, 1, sentry3, Infeed AA, snmp, 100, 1, , 0.75
SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'snmp' AND `sensor_class` = 'current' AND `device_id` = '28' AND sensor_type = 'sentry3' AND `sensor_index` = '1']
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = 'current' AND `device_id` = '28' AND `sensor_type` = 'sentry3' AND `sensor_index` = '1']
SQL[UPDATE `sensors` set `sensor_oid` ='.1.3.6.1.4.1.1718.3.2.2.1.7.1.1',`sensor_descr` ='Infeed AA',`sensor_multiplier` ='1',`sensor_divisor` ='100',`entPhysicalIndex` ='',`entPhysicalIndex_measured` ='',`user_func` ='' WHERE `sensor_id` = '1004']
USQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`severity`,`message`,`username`)  VALUES ('28','28','NULL','sensor',NOW(),'3','Sensor Updated: current sentry3 1 Infeed AA','')]
( 1 updated )

Discover sensor: .1.3.6.1.4.1.1718.3.2.2.1.7.1.2, 1, sentry3, Infeed AB, snmp, 100, 1, , 0
SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'snmp' AND `sensor_class` = 'current' AND `device_id` = '28' AND sensor_type = 'sentry3' AND `sensor_index` = '1']
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = 'current' AND `device_id` = '28' AND `sensor_type` = 'sentry3' AND `sensor_index` = '1']
SQL[UPDATE `sensors` set `sensor_oid` ='.1.3.6.1.4.1.1718.3.2.2.1.7.1.2',`sensor_descr` ='Infeed AB',`sensor_multiplier` ='1',`sensor_divisor` ='100',`entPhysicalIndex` ='',`entPhysicalIndex_measured` ='',`user_func` ='' WHERE `sensor_id` = '1004']
USQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`severity`,`message`,`username`)  VALUES ('28','28','NULL','sensor',NOW(),'3','Sensor Updated: current sentry3 1 Infeed AB','')]
( 1 updated )

Discover sensor: .1.3.6.1.4.1.1718.3.2.2.1.7.1.3, 1, sentry3, Infeed AC, snmp, 100, 1, , 2.25
SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'snmp' AND `sensor_class` = 'current' AND `device_id` = '28' AND sensor_type = 'sentry3' AND `sensor_index` = '1']
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = 'current' AND `device_id` = '28' AND `sensor_type` = 'sentry3' AND `sensor_index` = '1']
SQL[UPDATE `sensors` set `sensor_oid` ='.1.3.6.1.4.1.1718.3.2.2.1.7.1.3',`sensor_descr` ='Infeed AC',`sensor_multiplier` ='1',`sensor_divisor` ='100',`entPhysicalIndex` ='',`entPhysicalIndex_measured` ='',`user_func` ='' WHERE `sensor_id` = '1004']
USQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`severity`,`message`,`username`)  VALUES ('28','28','NULL','sensor',NOW(),'3','Sensor Updated: current sentry3 1 Infeed AC','')]
( 1 updated )
```

As you can see there, although they are 3 different sensors, instead of inserting the new ones, the current one (sensor_id=1004) is being updated every time.

**Comment by joelsdc** [comment]
I'm a little lost, I just don't know how to follow the code because I'm not familiar with the internals of LibreNMS :(

My patch maybe in the right direction, but clearly I'm missing info to get it right.

**Comment by laf** [comment]
Have you tried what I suggested about `$towers` in the `discover_sensor()` call?

I.e:

```
$tmp_index = "infeedID.$towers.$infeed_index";
discover_sensor($valid['sensor'], 'current', $device, $infeed_oid, $tmp_index, 'sentry3', $descr, $divisor, $multiplier, $low_limit, $low_warn_limit, $high_warn_limit, $high_limit, $current);
```

**Comment by laf** [comment]
Your patch confused me as it's the inverse of what's normally expected :)

I've submitted a pull request with what I think is the final fix, please test and let us know.

**Comment by joelsdc** [comment]
Sorry for the late reply, I have been out and wasn't able to test this. I have just updated our installation and I can confirm that the infeeds are all correctly shown now:

![image](https://user-images.githubusercontent.com/16212586/27968484-0d34ec2a-62fc-11e7-9af3-60b3c73ee0c1.png)

Thanks for solving this!
