### ISSUE TITLE
QNAP memory statistic wrong data

### ISSUE THREAD

**Issue by Bernardoni** [librenms/librenms#6844]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | f5931535b4bda751fbd0cfd584b2e98e14d4bc32
DB Schema | 195
PHP       | 7.0.19
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Librenms data information about qnap RAM memory and swap memory (free and used) aare not correct.
See attached image captured from QNAP console and librenms.
![librenms_memory](https://user-images.githubusercontent.com/18052452/27170377-f633642a-51ad-11e7-868b-37e978f4d988.GIF)
![qnap_memory](https://user-images.githubusercontent.com/18052452/27170379-f6360798-51ad-11e7-96f2-ecc0101aa0b5.GIF)
![qnap_memory_graph](https://user-images.githubusercontent.com/18052452/27170380-f6387e74-51ad-11e7-8d8c-98ecd97e6d27.GIF)

**Comment by Bernardoni** [comment]
same qnap storage info from qnap console and librenms page.

thank you
Paolo

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.
