### ISSUE TITLE
Dynamic customisable dashboard

### ISSUE THREAD

**Issue by laf** [librenms/librenms#685]
@paulgear and myself have discussed this a bit but we've not progressed it.

It would be nice to have a fully customisable dashboard (we could then do away with the front page files) where you can add what you want to the frontpage and move them around.

I did some basic work to trial a grid system which you can store placement in the database which works well:

https://github.com/laf/librenms/tree/issue-laf-57

You will need to add something like:

s:358:"[{"col":1,"row":1,"size_x":2,"size_y":2,"w_id":101},{"col":3,"row":1,"size_x":1,"size_y":1,"w_id":102},{"col":1,"row":3,"size_x":1,"size_y":1,"w_id":103},{"col":2,"row":3,"size_x":1,"size_y":1,"w_id":104},{"col":1,"row":4,"size_x":1,"size_y":1,"w_id":105},{"col":2,"row":4,"size_x":1,"size_y":1,"w_id":106},{"col":2,"row":5,"size_x":1,"size_y":1,"w_id":107}]";

To the dashboard_config column for the user then set $config['front_page']       = "pages/front/tiles.php"; in config.php

If anyone fancies picking this up that would be awesome?

**Comment by f0o** [comment]
Brilliant thing!

will have a look at it, is the db on a per-user basis?

**Comment by laf** [comment]
Yup 100%. Stores placement and what ids the tiles in json. I store those in the db at the moment.

**Comment by Rosiak** [comment]
Would love to see this!

**Comment by killsudo** [comment]
Another nice enhancement down the road once you sort this request would be a 'kiosk / NOC' dashboard.

LibreNMS Admin would create a 'kiosk' user with minimal permissions except to read/list devices and health status.

Alternative: Generate a 'Kiosk' url that does not require a user login and only displays this custom dashboard.

The Dashboard is EXTREMELY simple minded. You list two columns, 'Device' , 'Service'.

You list each device and it's polled service in a box and paint both box's in green with black text.

When everything is nice/good/happy the page is a basically a big splash of green.

If a device & service fails 1 to 3(customizable in alert rules) the status could be Yellow. (optional based on difficulty)

If a device & service fails more then 3 checks (again customizable in alert rules) the status would be Red.

A 'Red' device & service would move to the top of the page. (Sort groups green / yellow / red via Alphabetical order)

Now as devices & services fails the Admins/NOC would receive a visual indicator as more and more devices fail indicating an event.

As devices & services restore to normal the Admins/NOC would receive a visual indicator that the environment is returning to a healthy state.

(Don't worry about trying to fit everything on the screen space etc. Just list them and let the red going to top do the magic.)

Now Management / Bosses are happy as they have a visual indicator of NOC health displayed around the NOC's / DataCenters. If the board goes red and NOC monkeys are not scrambling someone can kick them into gear.

The devices and service is critical tho once you are monitoring services. If my dashboard blows up with email servers but only the SMTP service is failing I know that and can quickly narrow my troubleshooting. If ICMP pings start failing across devices that gives me completely different information.

This will be useful until LibreNMS gets the ability to implement Device-Dependencies for Alerts #897 to restrict the flood of informational alerts when certain things fail.

**Comment by Rosiak** [comment]
Made this branch where i will be fooling around:
https://github.com/Rosiak/librenms/tree/dash-test1

Thought's in general:

- Resizable widgets
- Dynamic map size
- Save & Load dash layout from DB
- Add / Remove widgets

**Comment by laf** [comment]
Ok update on this. My branch should now be useable if anyone wants to test. Two options.

1. https://demo.librenms.org
u/p: demo

2. Checkout my repo:
```bash
cd /opt/librenms
git remote add laf https://github.com/laf/librenms.git
git remote update laf
git checkout issue-685
```

Then add this to config.php:

```bash
$config['front_page']       = "pages/front/tiles.php";
```

And now run these queries:
```bash
CREATE TABLE `dashboard_items` (   `dashboard_item_id` int(11) NOT NULL AUTO_INCREMENT,   `user_id` int(11) NOT NULL,   `widget_id` int(11) NOT NULL,   `col` tinyint(4) NOT NULL,   `row` tinyint(4) NOT NULL,   `size_x` tinyint(4) NOT NULL,   `size_y` tinyint(4) NOT NULL,   `title` varchar(255) NOT NULL,   `content` text NOT NULL,   `refresh` tinyint(4) NOT NULL DEFAULT '60',   PRIMARY KEY (`dashboard_item_id`),   KEY `user_id` (`user_id`,`widget_id`) ) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=latin1;
CREATE TABLE `tiles` (  `tile_id` int(11) NOT NULL AUTO_INCREMENT,  `tile_title` varchar(255) NOT NULL,  `tile` varchar(255) NOT NULL,  `base_dimensions` varchar(10) NOT NULL,  PRIMARY KEY (`tile_id`),  UNIQUE KEY `tile` (`tile`)) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;
INSERT INTO `tiles` (`tile_id`, `tile_title`, `tile`, `base_dimensions`) VALUES (4, 'Availability map', 'availability-map', ''), (5, 'Device summary', 'device-summary-horiz', ''), (6, 'Alerts', 'alerts', '6,2');
```

Now go to your overview page and add widgets.

Code needs to be formatted properly, it's all thrown together for now. The include files to generate the widgets need working on, this is a quick hack and slash.
