### ISSUE TITLE
how to get cisco line protocol status ( down or up) ? 

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#6851]
![line-protocol](https://user-images.githubusercontent.com/528348/27194179-35751f12-5234-11e7-943d-6f559ea05a9f.png)

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
