### ISSUE TITLE
Additional sensors for APC IRRP100 Air Conditionners series

### ISSUE THREAD

**Issue by mail4git38** [librenms/librenms#6855]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
==========================================================
Component | Version
--------- | -------
LibreNMS  | 5fa8d3f64c04aef42ab3cb74089b532fbcc82285
DB Schema | 195
PHP       | 7.0.15
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery : https://gist.github.com/mail4git38/b8b2881c9958e4224da0fd18942d44f4
Polling : https://gist.github.com/mail4git38/47700f9927cae44eb6aa3037d5f69eea
SNMP Walk : https://gist.github.com/mail4git38/f1aa610d135c350cc205bd157211998b

I'm working on this issue. I should provide the following informations and sensors : 
- Model Number
- Serial Number
- Firmware Revision
- Operating Mode state
- Temperatures (with Thresholds)
- Humidity
- AirFlow
- Fan Speed
- Pressures
- Voltages
- Alarms sensors
- Runtimes

**Comment by laf** [comment]
@mail4git38 How are you getting on with this? Anything we can help with?

We have recently added the ability to define new sensors via Yaml which you might be able to use here: http://docs.librenms.org/Developing/os/Health-Information/

**Comment by mail4git38** [comment]
@laf Model Number, Serial Number, Operating Mode State, Temperatures, Humidity and Air Flow are already OK. I'm still working on the remaining sensors. It should be done in the following day, if I've enough time at work to do it....

**Comment by laf** [comment]
@mail4git38 I actually submitted a pull request earlier if you want to test it?

**Comment by mail4git38** [comment]
@laf Yes I've integrated your PR 6946. Some of my sensors are already in your yaml file, so I remove my modifications from my issue. I will just add some sensors you have not declared in your PR (fan speed, compressor drive speed and power, runtimes).

 Is there a class for pressure sensors (with Measurement in Pa) ?

**Comment by laf** [comment]
Pa isn't available, we could add that though.

Feel free to take my yaml file, update it and submit it yourself.
