### ISSUE TITLE
Outdated HUAWEI-ENTITY-EXTENT-MIB , dBm readings from Huawei NE20 device failes

### ISSUE THREAD

**Issue by runborg** [librenms/librenms#6860]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
==========================================================
Component | Version
--------- | -------
LibreNMS  | bcaeae5976cd46de47f7d427b2ab9cc8b1c81f86
DB Schema | 195
PHP       | 5.5.9-1ubuntu4.14
MySQL     | 5.5.47-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2
==========================================================

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

After investigating why my Huawei NE20 devices does not get dBm values i found out that the MIB from Huawei might be outdated. 
Looking online i found two mib's where the same oid reports different values. 

mib in Librenms: https://github.com/librenms/librenms/blob/master/mibs/huawei/HUAWEI-ENTITY-EXTENT    (dated:  2003)
new mib:     https://github.com/openstack/compass-core/blob/master/mibs/HUAWEI-ENTITY-EXTENT-MIB.mib     (dated: Friday, July 15, 2011)
(i do not have a reference to the original mib file from huawei.)
Here are a description on the mib from Huawei (Requires login) http://support.huawei.com/enterprise/docinforeader!loadDocument1.action?contentId=DOC1000019424&partNo=1001142

OID definition on RX dBm from the Librenms contained mib:         
>         hwEntityOpticalRxPower   OBJECT-TYPE
>             SYNTAX      Integer32
>             MAX-ACCESS  read-only
>             STATUS      current
>             DESCRIPTION
>                 "The receive power of the optical module. Unit: uW."
>         ::= { hwOpticalModuleInfoEntry 8 }

Table position 8 is updated with this object in the new mib::
>         -- 1.3.6.1.4.1.2011.5.25.31.1.1.3.1.8
>         hwEntityOpticalRxPower OBJECT-TYPE
>             SYNTAX Integer32
>             MAX-ACCESS read-only
>             STATUS current
>             DESCRIPTION
>                 "The receive power of the optical module. Unit: dBm. the value is expanded 100 times,so the real value should be reduced 100 times "
>             ::= { hwOpticalModuleInfoEntry 8 }

I can confirm that on my device table position 8 is indeed dBm readings*100 it correlates 100% with the dBm readouts i collect from my interfaces.   see pastebin in the bottom of my post.

i also find this definition from hwEntityStateTable that looks like 
>        -- 1.3.6.1.4.1.2011.5.25.31.1.1.1.1.22
>         hwEntityOpticalPowerRx OBJECT-TYPE
>             SYNTAX Integer32
>             MAX-ACCESS read-only
>             STATUS current
>             DESCRIPTION
>                 "The optical power(Rx) of the optical module. Unit: uW"
>             ::= { hwEntityStateEntry 22 }
I have not verified that values in this table is indeed real uW readouts.

also see pastebin for raw readouts from my device:  [https://pastebin.com/Yvc5nCsp](https://pastebin.com/Yvc5nCsp)

Inside [includes/discovery/sensors/dbm/vrp.inc.php](https://github.com/librenms/librenms/blob/master/includes/discovery/sensors/dbm/vrp.inc.php) Librenms expect the value to be a positive integer in uW format, and when my device reports in dBm it fails. 

I Don't know the best solution on this and i don't know if any other Huawei devices are using the old mib file. a quickfix for me could be to change the code to reflect the correct dBm readouts, but this might be a bit hackish because i don't know if anything is using the old mib.

**Comment by laf** [comment]
So I'm guessing HUAWEI have screwed something up. We went back and forth with another user over dBm and uW: https://github.com/librenms/librenms/issues/4279

Are you now saying after that they've just updated the MIB to say it's another value, if so that's just stupid as it means people on the old firmware will be uW and people on the new firmware will be dBm with no way for us to tell.

We might be able to do something with the new `1.3.6.1.4.1.2011.5.25.31.1.1.1.1.22` oid in that mib. Can you provide all the info we need in point 3 please. Once we have that we can re-open this issue.
