### ISSUE TITLE
Secure cookies not enabled

### ISSUE THREAD

**Issue by rzig** [librenms/librenms#6866]
Hi. After running a vulnerability scan on my LibreNMS server, I was informed that it did not have secure cookies enabled, which can lead to session hijacking attacks. As of the current version of LibreNMS, secure cookies cannot be enabled in config.php or any other LibreNMS-specific configuration files. To enable secure cookies, the following needs to be added to php.ini:
```
session.cookie_secure = 1
```
This can also be set by running:
```
ini_set('session.cookie_secure', 1);
```

I think it would be good if this was an automatic behavior, and I'd be happy to work on getting an option for secure cookies into config.php if you want.

Thanks for all the hard work!

**Comment by laf** [comment]
I guess you could detect if the site was access over https and enable it automatically. The alternative is as like you've said, to provide a config.php option. If you can submit a PR for this that would be ace.

N

**Comment by rzig** [comment]
I'll work on that. As a temporary patch, adding `ini_set('session.cookie_secure', 1);` to config.php will fix the issue.

**Comment by rzig** [comment]
OK. So, adding `ini_set('session.cookie_secure', 1);` to `config.php` only secures the session identifier cookie. I'll attach a PR that takes care of securing the other cookies, but the only way to get the session cookie secured is by modifying `config.php`, or `php.ini`.

**Comment by murrant** [comment]
rzig: I reviewed `session.cookie_secure` and it appears that it does not enable secure cookies.  It just disables insecure (http) cookies. Am I wrong?

**Comment by rzig** [comment]
That is correct. `session.cookie_secure` will only transmit session cookies over HTTPS, in addition to making the `PHPSESSID` cookie a "secure" cookie. In the [pull request](https://github.com/librenms/librenms/pull/6868), I made sure all cookies would be secure when `$config['secure_cookies']` is `true`.

**Comment by murrant** [comment]
Perhaps.  In my environment, I have nginx configured to redirect http to https and have HSTS enabled.  HSTS is a much more robust way to ensure all your site is only accessed over https.

**Comment by rzig** [comment]
I'm not sure that HSTS forces the cookies to be secure, as I believe that is a setting that can only be enabled in the code. I may be wrong, though.

**Comment by murrant** [comment]
Ok, a little more research there is a bit that instructs the browser to only transmit the data over https.

I'm still wondering if there is a way to avoid having an option and just set it in the correct situations.

**Comment by rzig** [comment]
If we want it to default to secure cookies over HTTPS, and insecure over HTTP, couldn't we just set the default config value of `$config['secure_cookies']` to `$_SERVER["HTTPS"]`? We could just get rid of the config option entirely, but having the option of a manual override could be nice.

**Comment by laf** [comment]
Setting it to `$_SERVER["HTTPS"]` surely is pointless as it just means the cookie is sent when you visit http and https (but securely) which is what happens when you visit https anyway it just means you aren't forcing secure cookies which is what I thought you wanted with this PR?

**Comment by rzig** [comment]
Previously, the cookie was not being sent securely over HTTPS. Secure cookies could be forced by setting `$config['secure_cookies']` to `true`.

**Comment by laf** [comment]
Right sorry I totally misunderstood what you meant. I guess your original PR is actually correct - sorry about that :(

**Comment by rzig** [comment]
No worries:)

**Comment by murrant** [comment]
That would break users that don't use https (usually only internally accessible)

**Comment by rzig** [comment]
It would break HTTP if we force secure cookies by setting `$config['secure_cookies']` to `true`. If we set the default value of `$config['secure_cookies']` to `$_SERVER["https"]` secure cookies will only be used when the server is being accessed by HTTPS. Then, if the sysadmin wants to force secure cookies, they can always do so with `$config['secure_cookies'] = true;`
