### ISSUE TITLE
APPLIANCE NOT FOUND THE INTERFACES NETWORK IN THE VIRTUAL MACHINE (OVA & VMDK

### ISSUE THREAD

**Issue by fgranadosgh** [librenms/librenms#6871]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://opencollective.com/librenms/donate

**Comment by fgranadosgh** [comment]
Hi, I just download both files  (VMDK & OVA) of the LIBRENMS, when I open the Virtual Machine, it boot correctly the ubuntu OS to prompt named 'librenms@librenms:~$", and I want to know what IP address has the VM, it doesnt any interface only show "interface lo",  and ip route list dont show me nothing. That case is like the OS dont have interfaces added.

**Comment by fgranadosgh** [comment]
The same problem in others OS of other pyisical machines.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
