### ISSUE TITLE
SNMP crashing on Vyos

### ISSUE THREAD

**Issue by mevertse** [librenms/librenms#6879]
System information:

Component | Version
--------- | -------
LibreNMS  | fb548a973254d037700df2bec1e509448eba2b79
DB Schema | 195
PHP       | 7.0.18-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

Sinds a couple of weeks SNMP daemon keeps crashing during discovery on some Vyos devices.
Discovery crashed the SNMP during module Storage.

Disabling UCD-DiskIO solved it it seems, we are still investigating.

Could be related to this change?
https://github.com/librenms/librenms/issues/4670

We are using interface descriptions like
Core: Router-Internal [1Gbit]

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
