### ISSUE TITLE
Add support for MFI/ Mport Ubiquiti via ssh

### ISSUE THREAD

**Issue by dracmic** [librenms/librenms#6880]
Hello, 

Can be this added? Or it is possible to help me to integrate as a custom host to read temperature and power from a MPORT/MFI by their label?
What i found is referring to cacti:
https://github.com/madsensh/cacti-mpower

Thanks,
Mihai Ursu

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://opencollective.com/librenms/donate

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3

We don't support anything other than snmp at present, if this data is possible to retrieve over snmp then it can be added but you need to request this as a feature request. If you do want to try and add support then it's best to catch us on IRC or still use the community site to ask questions.
