### ISSUE TITLE
Incorrect Juniper QFX family JunOS version

### ISSUE THREAD

**Issue by nguyh** [librenms/librenms#6885]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://opencollective.com/librenms/donate

Component | Version
--------- | -------
LibreNMS  | 6a79d4495f1a5d91d476021b7fb3ab58889e6f80
DB Schema | 195
PHP       | 7.0.18-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

The OS version pulled for Juniper QFX switch family is incorrect.  The mib .1.3.6.1.2.1.25.6.3.1.2  used in file junos.inc.php  work for EX and MX device but not for QFX. 

Here is the output of snmp: 
Incorrect OS: 
 snmpbulkwalk   -On -v 2c -c ro qfxswitch01 .1.3.6.1.2.1.54.1.1.1.1.4.2
.1.3.6.1.2.1.54.1.1.1.1.4.2 = STRING: "junos-ez-stdlib [11.10.4_1.junos.i386]D40.8]"

Correct OS should be 14.1X53-D40 
snmpbulkwalk  -v 2c -c ro  qfxswitch01 .1.3.6.1.2.1.54.1.1.1.1.4
.1.3.6.1.2.1.25.6.3.1.2.2 = STRING: "junos-ez-stdlib [11.10.4_1.junos.i386]D40.8]"
.1.3.6.1.2.1.25.6.3.1.2.3 = STRING: "JUNOS Kernel Software Suite [14.1X53-D40.8]"
.1.3.6.1.2.1.25.6.3.1.2.4 = STRING: "JUNOS Packet Forwarding Engine Support (qfx-ex-x86-32) [14.1X53-"
.1.3.6.1.2.1.25.6.3.1.2.5 = STRING: "JUNOS Routing Software Suite [14.1X53-D40.8]"
...

Is there way to change the mib to be based of the hardware discovered.

**Comment by laf** [comment]
Do you have: `1.3.6.1.4.1.2636.3.40.1.4.1.1.1.5.0`?

`snmpbulkwalk -v 2c -c ro qfxswitch01 1.3.6.1.4.1.2636.3.40.1.4.1.1.1.5.0`

**Comment by laf** [comment]
I've submitted a pull request using that OID, feel free to test.

**Comment by nguyh** [comment]
it return this. 
snmpbulkwalk -v 2c -c ro qfxswitch01 1.3.6.1.4.1.2636.3.40.1.4.1.1.1.5.0 
iso.3.6.1.4.1.2636.3.40.1.4.1.1.1.5.0 = STRING: "14.1X53-D40.8"

I am not very familiar with git, how to use git to get the update version to test ? 

I did find other issue related vlan and interface association with QFX and modify some source code to test so when I do a git pull  it doesn't work. 

Regards,

**Comment by nguyh** [comment]
Ok, found the instruction to apply the patch, all the QFX switches shows the proper version now. 

Thanks.

**Comment by murrant** [comment]
@nguyh thanks for the feedback, now I can merge the PR :)
