### ISSUE TITLE
Netman UPS snmp-module, displays incorrect values

### ISSUE THREAD

**Issue by sorano** [librenms/librenms#6893]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://opencollective.com/librenms/donate

Component | Version
--------- | -------
LibreNMS  | 5e32474d26cc30c44bad82fc3e926c0183e8e020
DB Schema | 196
PHP       | 7.0.18-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

Operating System	NetMan Plus SWM022-02-20
Object ID	enterprises.5491.6

Noticed some values have been off for quite some time (mid feb 2017) on this device.
http://imgur.com/a/LxZiY

Battery voltage
iso.3.6.1.2.1.33.1.2.5.0 = INTEGER: 2726

Will be displayed as 2726V which seems pretty high ;) (real value should be 272.6V)

iso.3.6.1.2.1.33.1.4.4.1.5.1 = INTEGER: 28  output L1 Load %
iso.3.6.1.2.1.33.1.4.4.1.5.2 = INTEGER: 28  output L2 Load %
iso.3.6.1.2.1.33.1.4.4.1.5.3 = INTEGER: 13  output L3 Load %

Will be displayed as 2.8% when real usage is 28%.

Discovery: https://p.libren.ms/view/9b9a1224
Poller: https://p.libren.ms/view/8332d56d
snmpbulkwalk: https://p.libren.ms/view/fdc80f9c

**Comment by murrant** [comment]
@laf  Found something interesting:  https://github.com/librenms/librenms/commit/ae696dc55c61e15331025f214a34378b23a0ac42

Battery has a divisor of 10, while input voltage has a divisor of 1.  That got lost in the shuffle a long time ago.

**Comment by laf** [comment]
Do you mean precision in that code?

**Comment by murrant** [comment]
yes

**Comment by laf** [comment]
See if the last push is right, mimics the old code now afaics

**Comment by sorano** [comment]
@laf 

I have tested #6905 now and values displayed in LibreNMS are back to normal.

**Comment by murrant** [comment]
Thanks for the feedback @sorano
