### ISSUE TITLE
Alarm Logic Failing (OS Updates)

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#6899]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
```
==========================================================
Component | Version
--------- | -------
LibreNMS  | 5e32474d26cc30c44bad82fc3e926c0183e8e020
DB Schema | 195
PHP       | 7.0.18-0ubuntu0.16.04.1
MySQL     | 5.7.18-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================

```
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
=> I can add this if needed, but not sure this will explain the issue.
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hi,

I seem to be getting a false alarm - could be me (likely), but here is what I am seeing. The alert that is triggering is copied here,
OS Updates: %applications.app_type = "os-updates" && %applications.app_status > "32"

But the alert says,
OS Updates: #1: app_id => '41'

Why is it using app_id? The alarm rule doesn't call for this field at all.

Thanks!

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by arrmo** [comment]
OK, will do - NP. Seems like a bug to me, but I definitely could be wrong. Will try to get it worked out.

Thanks.
