### ISSUE TITLE
Cisco ONS 15454 - Better Support

### ISSUE THREAD

**Issue by taking-care-of-business** [librenms/librenms#6906]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://opencollective.com/librenms/donate

==========================================================
Component | Version
--------- | -------
LibreNMS  | 8d5c3f34f2117c27ee76c0a129c9634a8f065982
DB Schema | 195
PHP       | 7.0.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

[WARN]  Your install is out of date, last update: Mon, 26 Jun 2017 07:27:01 +0000
[FAIL]  We have found some files that are owned by a different user than librenms, this will stop you updating automatically and / or rrd files being updated causing graphs to fail.
        [FIX] chown -R librenms:librenms /opt/librenms
         /opt/librenms/html/plugins/Weathermap/configs
         /opt/librenms/html/plugins/Weathermap/configs/.htaccess
         /opt/librenms/html/plugins/Weathermap/configs/index.php
          and 255 more...
[OK]    Database connection successful
[OK]    Database schema correct
[FAIL]  Discovery has not completed in the last 24 hours, check the cron job
[WARN]  Some devices have not been polled in the last 5 minutes.
        You may have performance issues. Check your poll log and see: http://docs.librenms.org/Support/Performance/
-bash-4.2$ 

We have added a Cisco ONS 15454 node, however we are receiving limited information from it. For instance, we are able to see overall throughput from the device from the line and facility interfaces, but traffic from specific DWDM wavelength's are not shown. In addition, CPU usage, RX/TX optical power levels, etc are also not displayed either (things that would normally show up on a Cisco router). 

Here is a visual of what I see:

![image](https://user-images.githubusercontent.com/24301416/27655211-9500239a-5c12-11e7-8054-6c5c33bb6ef2.png)

Also, is there a way to submit the discovery, poller, and snmpbulkwalk output privately?

**Comment by laf** [comment]
You'll need to anonymise the data and post it up. Reply to this once you've done so and we'll re-open this.

**Comment by taking-care-of-business** [comment]
Hey laf,

I have been prepping my debug info as per " http://docs.librenms.org/Support/FAQ/#faq20 ", I noticed in the pasting my debug output that there is a Create Encyrpted option. 
I'm assuming that only LibreNMS developers have access to this encrypted output, and more secure/private?

If that's the case, I can upload these fairly quick for you as I am expecting this would lessen my concern of anonymizing the output.

**Comment by laf** [comment]
I don't think ours works.

However (personally), I don't like hidden information, it means that you rely solely on those people you give the key to help you which is a burden I don't personally want, yet I might end up fixing this anyway but I don't want to feel like I have to because you've given me the key.

**Comment by taking-care-of-business** [comment]
No problem.

The logs are surprisingly lengthy (some debug logs are 3mb or 6mb)... so it'll be sometime before I can anonymize them and submit it publicly.

Oh, and Happy Canada Day!! :)

**Comment by taking-care-of-business** [comment]
I am having difficulty uploading the files as both, Pastebin and https://p.libren.ms/ , are complaining of large size. As mentioned, some of the output does exceed 3MB.

What other options do I have?

**Comment by laf** [comment]
Upload it using github.com, you can attach files here.

**Comment by taking-care-of-business** [comment]
Discovery output:

[20170714-CISCO-ONS-15454-Discovery Output-2.txt](https://github.com/librenms/librenms/files/1152759/20170714-CISCO-ONS-15454-Discovery.Output-2.txt)

**Comment by taking-care-of-business** [comment]
i still owe you 2 more debugs .. more on its way ...

**Comment by taking-care-of-business** [comment]
SNMP Bulkwalk output:

[20170717-CISCO-ONE-15454-SNMPBulk Output.txt](https://github.com/librenms/librenms/files/1152933/20170717-CISCO-ONE-15454-SNMPBulk.Output.txt)


I'm done with uploading the files.

**Comment by laf** [comment]
Please re-run this snmpwalk as it looks like it's missing a lot of the data we need:

`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .1.3.6.1.4.1.3607.2`

**Comment by taking-care-of-business** [comment]
No problem .. stand by ...

**Comment by taking-care-of-business** [comment]
We may need to close this ticket for the time being. Regrettably, I won't be able to obtain the full, un-timed out snmpbulkwalk output.

I am hoping to revisit this issue next year (unless there is another user with an Cisco ONS platform looking to leverage LibreNMS).
I appreciate you guys looking into this. Again, I am pushing to get this going for my benefit, but this will unfortunately **_take time_**.

**Comment by laf** [comment]
You should try `snmpbulkwalk` and also `-t 5` to change the timeout.

I can see temp and voltage data in here so I'll at least submit the PR for that.

It needs me to add some pre-caching code back in that I've previously removed so might take me a little longer.

**Comment by taking-care-of-business** [comment]
No worries.
Thank you for the follow up.

**Comment by taking-care-of-business** [comment]
I am able to get the required output without any timeouts from another ONS node.

Discovery: https://p.libren.ms/view/ed6748d1
Poller: https://p.libren.ms/view/46d0707d
SNMP Bulkwalk (see attached)
[20170728-CISCOONS15454-SNMPBULKWALK.txt](https://github.com/librenms/librenms/files/1183557/20170728-CISCOONS15454-SNMPBULKWALK.txt)

**Comment by laf** [comment]
Ok, I can only see temp and voltage. If you can see the OID for anything else let me know. Feel free to test the PR.

CPU / Mem looks not supported: https://thwack.solarwinds.com/thread/111366

**Comment by taking-care-of-business** [comment]
Temperature / Voltages look good (see below).

![image](https://user-images.githubusercontent.com/24301416/28823610-6befa7ca-768c-11e7-9894-056a990bbd58.png)

**Comment by taking-care-of-business** [comment]
I have looked around documentation we have, and found that specifically for the ONS 15454 the following MIBs are needed for NMS in general:


```
The following Standard MIB files, included on the CD, must be loaded into your network management system. They are located in the Standard directory.

        BRIDGE-MIB-rfc1493.mib
        DS1-MIB-rfc2495.mib
        DS3-MIB-rfc2496.mib
        ENTITY-MIB-rfc2737.mib
        EtherLike-MIB-rfc2665.mib
        IANAifType-MIB.mib
        IF-MIB-rfc2233.mib
        P-BRIDGE-MIB-rfc2674.mib
        PerfHist-TC-MIB-rfc2493.mib
        Q-BRIDGE-MIB-rfc2674.mib
        RFC1213-MIB-rfc1213.mib
        RFC1253-MIB-rfc1253.mib
        RIPv2-MIB-rfc1724.mib
        RMON-MIB-rfc2819.mib
        RMON2-MIB-rfc2021.mib
        RMONTOK-rfc1513.mib
        SNMP-FRAMEWORK-MIB-rfc2571.mib
        SNMPv2-MIB-rfc1907.mib
        SONET-MIB-rfc2558.mib
        HCNUM-TC.mib
        HC-RMON-rfc3273.mib
        SNMP-TARGET-MIB-rfc3413.mib
        SNMP-NOTIFY-MIB-rfc3413.mib
        SNMP-PROXY-MIB-rfc3413.mib
        SNMP-USER-BASED-SM-MIB-rfc3414.mib
        SNMP-VIEW-BASED-ACM-MIB-rfc3415.mib
        SNMP-MPD-MIB.mib
        INET-ADDRESS-MIB.mib

The CiscoV1 and CiscoV2 directories contain Cisco specific MIB files in SNMPv1 and SNMPv2 formats respectively. Load your network management system with the following MIB files from either one of these directories for successful network management operations.

        CERENT-GLOBAL-REGISTRY.mib
        CERENT-TC.mib
        CERENT-454-MIB.mib
        CERENT-GENERIC-MIB.mib
        CERENT-MSDWDM-MIB.mib
        CERENT-OPTICAL-MONITOR-MIB.mib
        CISCO-OPTICAL-MONITOR-MIB.mib
        CISCO-SMI.mib
        CISCO-VOA-MIB.mib
        CISCO-OPTICAL-PATCH-MIB.mib
        CISCO-VTP-MIB.mib
        CISCO-IGMP-SNOOPING-MIB.mib
        CERENT-FC-MIB.mib
        CERENT-HC-RMON-MIB.mib
        CERENT-ENVMON-MIB.mib
        CERENT-GENERIC-PM-MIB.mib
        CERENT-IF-EXT-MIB.mib

Cisco suggests you load these files from CiscoV2 directory; however if your network management system requires that you load MIB files in SNMPv1 format, use the files in the CiscoV1 directory instead.

The following MIB(s) in CiscoV2 directory support 64-bit counters:

        CERENT-MSDWDM-MIB.mib
        CERENT-FC-MIB.mib
        CERENT-HC-RMON-MIB.mib
        CERENT-GENERIC-PM-MIB.mib



```



Out of the 17 ONS-specific MIBs above, 4 of them are not included in LibreNMS.

CISCO-OPTICAL-MONITOR-MIB.mib (This MIB module defines objects to monitor optical characteristics and set corresponding thresholds on the optical interfaces in a network element)
CISCO-VOA-MIB.mib (This MIB module defines objects to configure and manage the Variable Optical Attenuator (VOA) modules.)
CISCO-OPTICAL-PATCH-MIB.mib (This MIB module is used to configure and monitor the network element view of optical patches between two ports or fibers on the same network element.)
CISCO-IGMP-SNOOPING-MIB.mib

I have attached those 4 MIBs here. 
I'm looking for more information per port, if at all possible (counters [throughput, errors, etc], optical power levels per port, circuit name/description [maybe?? not sure if its obtained via SNMP], etc).

[Cisco-ONS-MIBs-Missing-4.zip](https://github.com/librenms/librenms/files/1209008/Cisco-ONS-MIBs-Missing-4.zip)

**Comment by laf** [comment]
I've fixed an issue in discovery for temp sensors.

As for the other info you want:

Counters - This is ports and is already there. If this is specific to something else then please create a feature request as that's all we support right now.
Optical power levels - I don't see that in the mibs you've provided. If you can find the OID / Name then we can take a look.
Circuit name / description - If this is outside of the typical port description parsing then again, it needs a feature request opening.
