### ISSUE TITLE
Gamatronic UPS not detected

### ISSUE THREAD

**Issue by LozBC** [librenms/librenms#6937]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

==========================================================
Component | Version
--------- | -------
LibreNMS  | 701fbbc29b7a25e215032a6435fac72c06094976
DB Schema | 198
PHP       | 7.0.14
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

**Details**

Gamatronic Power+ UPS is not correctly detected by discovery.php - consequently listed as Generic Server with basic details about UPS nic being recorded. No power data at all.

https://pastebin.com/Ljn8f8Rj

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by laf** [comment]
@murrant kindly picked this up without the additional info so this may now be sorted with #6940

**Comment by murrant** [comment]
Honestly, I was happy to have tiny bit of info he supplied because the old detection was bad and we had no data for them in our user submitted stats (https://stats.librenms.org)

Supply the full requested info does allow us to add more data in the future or verify changes.  So it is always preferred.
