### ISSUE TITLE
API inventory empty for server type

### ISSUE THREAD

**Issue by djtecha** [librenms/librenms#6939]
Currently when I make a call to a server using the API I get a null array for the inventory. If I hit a network device this returns information just fine. I've checked the device in the webui and it has all the CPU info I want on the inventory link, but would like to do this programatically. Any ideas on if this is a known issue?

I've enabled the feature in my config.php

$config['enable_inventory']             = TRUE; # Enable Inventory

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
