### ISSUE TITLE
support mssql by odbc/jdbc [feature]

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#694]
I think to monitor such resource as mssql or oracle or mysql by `ODBC`  is very useful  .

Will you add such a feature and add a mssql monitor just like add a device ?

**Comment by laf** [comment]
Hi @wzhsunn does this need to be by odbc?

I've been speaking to some of the guys at work and we have a load of wmi scripts that can collect data from things like Exchange and SQL. Implementing those would be easy enough.

**Comment by wzhsunn** [comment]
Is it possible for my read only device @laf ?

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
