### ISSUE TITLE
New OS - Gestetner MP C2500 Printer

### ISSUE THREAD

**Issue by LozBC** [librenms/librenms#6948]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Version info:
Commit SHA: 13d047c029aedfc0a44c0d46d15b71502a62402d
Commit Date: 1499130648
DB Schema: 198
PHP: 7.0.14
MySQL: 5.5.52-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2

**Issue**

New OS detection - Gestetner MP C2500 Printer

I believe this is actually simply a rebadged Ricoh MP C2500 which is already fully supported within LibreNMS.

Discovery: https://pastebin.com/mDPWK0a8
Poller: https://pastebin.com/hgwyfc3A
SNMP: https://pastebin.com/J8GNRJyx

**Comment by laf** [comment]
Your snmp walk is just another poller output

**Comment by LozBC** [comment]
Sorry about that - updated link!

**Comment by laf** [comment]
ty
