### ISSUE TITLE
API request - Syslog messages per device

### ISSUE THREAD

**Issue by pheinrichs** [librenms/librenms#6949]
[Requested feature to view syslog messages in mobile app](pheinrichs/myLibreNMS#9) 
Currently I don't see any functions in the api_functions/docs file so looks like this will need to be added. 

---

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This will require pagination support within the api as syslog table won't be a small amount of data.

**Comment by laf** [comment]
I've submitted a PR that will give you this + eventlog, authlog and alert_log.

alert_log will most likely not be much benefit without additional columns being returned from sub queries.

**Comment by pheinrichs** [comment]
Thank you!
This has been added as of PR
#7071
