### ISSUE TITLE
Add support for TP-Link TD-8817 with VDSL-LINE-MIB

### ISSUE THREAD

**Issue by trs80** [librenms/librenms#6954]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Component | Version
--------- | -------
LibreNMS  | 13d047c029aedfc0a44c0d46d15b71502a62402d
DB Schema | 198
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.55-0+deb8u1-log
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

This is an ADSL modem that has line stats, but under 1.3.6.1.2.1.10.97 (VDSL-LINE-MIB) instead of 1.3.6.1.2.1.10.94 (ADSL-LINE-MIB).

discovery: https://p.libren.ms/view/c861fcd2
poller: https://p.libren.ms/view/ef8fef21
snmpbulkwalk: https://p.libren.ms/view/6639c40e

**Comment by laf** [comment]
Is the data mappable from ADSL-LINE-MIB to VDSL-LINE-MIB?

**Comment by trs80** [comment]
Hmm, not directly, rather than have atuc and atur for upstream/downstream, it has them as two entries in the various tables. The most important table (and the only real data) is in cvdslPhysTable 1.3.6.1.4.1.9.10.87.1.1.2

**Comment by laf** [comment]
Ok, please post this as a feature request then on the community forum. @
