### ISSUE TITLE
Total copier and printer counts (A4 / A3, ...)

### ISSUE THREAD

**Issue by 21let** [librenms/librenms#6957]
Hello everyone, Librenms is a great tool. I already have all the necessary features in it, but I certainly would not only welcome the possibility of printing counterparts (printers A4 and A3, ...), most often with Canon IRaC and HP copiers. Can these counters be read somewhere? Remaining toner is not needed for me.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
