### ISSUE TITLE
Add support for: HIMOINSA Power Generator

### ISSUE THREAD

**Issue by kamils85** [librenms/librenms#6964]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Component | Version
--------- | -------
LibreNMS  | 8b627bfec934896462e4d5fb4044ea84cb77a7c1
DB Schema | 199
PHP       | 7.0.15-0ubuntu0.16.10.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.10.1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

Could you please add the support for HIMOINSA Power Generator? 
The SNMP modul attached (very poor by the way) give only a little info for itself.

SNMPWALK: https://pastebin.com/uBEV0jwR
MIB attached.
[HIMOINSAv00.zip](https://github.com/librenms/librenms/files/1124281/HIMOINSAv00.zip)

For some reason I was able to do the snmpwalk only from my PC, not from LibreNMS.
My attempt to add it to LibreNMS also failed as it discovered nothing. 

> DEBUG!
> SQL[SHOW TABLES FROM librenms] 
> DB Schema update started....
> SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
> DB Schema already up to date.
> SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `hostname` LIKE '10.8.8.43' ORDER BY device_id DESC] 
> /opt/librenms/discovery.php 10.8.8.43 2017-07-05 11:15:45 - 0 devices discovered in 0.060 secs
> SNMP: Get[0/0.00s] Walk [0/0.00s]
> MySQL: Cell[3/0.00s] Row[0/-0.00s] Rows[4/0.01s] Column[0/0.00s] Update[0/0.00s] Insert[0/0.00s] Delete[0/0.00s]

I am particularly interested in getting the health status (power, freq, current, fuel status, etc).
I would appreciate your help with this one.

Kamil

**Comment by laf** [comment]
We're happy to add this but we do need the snmpwalk output in the format it would be given using the command we provide. You'll need to provide this before we can add support. Once you have it, link it here and we can re-open the issue.

**Comment by kamils85** [comment]
It happened to be the faulty module I received.

Please find the snmpbulk output here - https://pastebin.com/24CZU9Ln

As I mentioned before I would love to see some health data health (power, freq, current, fuel status, etc).
Anything else please let me know.

**Comment by laf** [comment]
Ok, I've added basic detection.

If you want more you'll have to decode that MIB for me :( It's OID names are cryptic and they don't contain any decent info like a description of the OID, what actual values the data is in (I.e Watts, milliwatts, etc).

**Comment by kamils85** [comment]
I think this may help:
[CCLAN SNMP MANUAL_ENGLISH.pdf](https://github.com/librenms/librenms/files/1284788/CCLAN.SNMP.MANUAL_ENGLISH.pdf)

**Comment by laf** [comment]
It does. Thanks

**Comment by laf** [comment]
I've added what I can to this:

![image](https://user-images.githubusercontent.com/3941142/30252595-2648d5a6-966d-11e7-8b76-6428727fff9c.png)
