### ISSUE TITLE
Fix myql empty graphs 

### ISSUE THREAD

**Issue by pinchasMT** [librenms/librenms#6965]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

references

https://github.com/librenms/librenms/pull/2645/files

https://github.com/librenms/librenms/issues/2021

remote mysql showing empty graphs
mysql  Ver 15.1 Distrib 10.1.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

latest code does not have "unset" (maybe it doesn't need it)
```
$fields = array();
foreach ($mapping as $k => $v) {
    $fields[$k] = (isset($map[$v]) && $map[$v] >= 0) ? $map[$v] : 'U';
}
```

**Comment by pinchasMT** [comment]
i added unset but still empty graphs

**Comment by pinchasMT** [comment]
https://gist.github.com/pinchasMT/6ee7782954a19e6e4962e5dfd423b45a

**Comment by laf** [comment]
Please post on the community site for support on this.

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by pinchasMT** [comment]
https://gist.github.com/pinchasMT/b0577986634d067d3fa144c04ef84321

**Comment by pinchasMT** [comment]
yes in communty too

https://community.librenms.org/t/empty-graphs-in-the-mysql-plugin/180
