### ISSUE TITLE
Proxmox motherboard sensors mis-align after every reboot and require a rediscovery

### ISSUE THREAD

**Issue by BloodyIron** [librenms/librenms#6969]
- [X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

Component | Version
--------- | -------
LibreNMS  | 2ba7093d9caaf3627a721df00a31b667525f6804
DB Schema | 199
PHP       | 5.5.9-1ubuntu4.21
MySQL     | 5.5.55-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

I have LibreNMS monitoring two proxmox cluster nodes. Every time I reboot the nodes the fan speeds and voltages get "mis-aligned". As in, the 3.3v shows up in vcore, etc. I have to rediscover the device each time, and also adjust the min/max values in the health of the device each time. This issue has been going on for months and I haven't seen it get better. I have upgraded proxmox many times, so at this point I'm wagging my finger at LibreNMS at this point, since rediscovery almost resolves it, except again I need to re-set the min/max for each sensor.

Not sure what the cause is, or when this started being a problem, but this leads to a lot of false alerts when I restart a node in a way that I intend to do.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by BloodyIron** [comment]
I have been using the IRC channel, in fact I reported this to you several times on the past on IRC directly.
