### ISSUE TITLE
Upgraded my Ubiquiti UAP-ACHD and it is no longer recognized

### ISSUE THREAD

**Issue by seitzbg** [librenms/librenms#6974]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

laf | It's no longer responding on the oid we use. Create an issue on GitHub and put down that I have the data

Component | Version
--------- | -------
LibreNMS  | aeedf515c5903a56f808e6c3407c9aa371574835
DB Schema | 199
PHP       | 7.0.20
MySQL     | 10.1.24-MariaDB
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

**Comment by murrant** [comment]
You did not provide the data request in point 3 (http://docs.librenms.org/Support/FAQ/#faq20).

We can't really do any troubleshooting without that.

**Comment by laf** [comment]
@murrant. I've got as per the message in the post :)

**Comment by laf** [comment]
I've got it that should have said.

**Comment by laf** [comment]
@seitzbg you mentioned this is a beta firmware I think. I reckon this is better reporting to UBNT at this time. They have no way for us to identify that this is a UAP :(

**Comment by seitzbg** [comment]
Chalk it up to beta firmware I guess... just upgraded to the release version and it works again.

```
SNMP[/usr/bin/snmpwalk -v1 -c COMMUNITY -Osqnv -m IEEE802dot11-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro:/opt/librenms/mibs/dell udp:HOSTNAME:161 do
t11manufacturerProductName]
UAP-AC-HD
UAP-AC-HD
UAP-AC-HD
UAP-AC-HD

SQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`severity`,`message`,`username`)  VALUES ('16','16','NULL','system',NOW(),'3','Device
 OS changed linux => unifi','')]
SQL[UPDATE `devices` set `os` ='unifi' WHERE device_id='16']
SQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`severity`,`message`,`username`)  VALUES ('16','16','NULL','system',NOW(),'3','Device
 type changed server => wireless','')]
SQL[UPDATE `devices` set `type` ='wireless' WHERE device_id='16']
Device type changed to wireless!
Changed OS! : unifi
SQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`severity`,`message`,`username`)  VALUES ('16','16','NULL','system',NOW(),'3','Device
 Icon changed linux.svg => ubiquiti.svg','')]
SQL[UPDATE `devices` set `icon` ='ubiquiti.svg' WHERE device_id='16']
Changed Icon! : ubiquiti.svg

>> Runtime for discovery module 'os': 0.2370 seconds with 6424 bytes
#### Unload disco module os ####

SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '16' AND `attrib_type` = 'poll_mib' ]
SQL[UPDATE `devices` set `last_discovered` =NOW(),`last_discovered_timetaken` ='0.672' WHERE `device_id` = '16']
Discovered in 0.672 seconds

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('discover','192.168.1.175','1500060117.4517','0.699','1','flow1.fiber
.house\n')]
./discovery.php 192.168.1.175 2017-07-14 15:21:58 - 1 devices discovered in 0.699 secs
SNMP: Get[6/0.13s] Walk [1/0.04s]
MySQL: Cell[3/0.00s] Row[1/0.00s] Rows[3/0.00s] Column[0/0.00s] Update[4/0.00s] Insert[5/0.00s] Delete[0/0.00s]
```

**Comment by laf** [comment]
Thanks for confirming.

**Comment by UBNT-cmb** [comment]
Happened upon this looking for why my LibreNMS was showing AC-HD and AC-SHD as Linux hosts. That is a problem in the beta firmware, we'll get that fixed @seitzbg.

**Comment by murrant** [comment]
@UBNT-cmb We'd be happy to accept patches or requests to support new hardware.

**Comment by UBNT-cmb** [comment]
@murrant Thanks. I think in this case the only issue is attributable to missing OIDs for those products in the beta firmware, which is being worked on this week. If not, I'll either open a feature request with specifics, or ideally submit a pull request.

**Comment by murrant** [comment]
@UBNT-cmb specific sysObjectIDs would be much better, we only use that OID to detect UBNT devices because we don't have unique sysObjectIDs per product.  Most manufactures use enterprise_oid.product_class.product_family.product_model or even more grouping to identify products.

This way we can tell what a product is easily
For example, if the sysObjectID starts with:
.1.3.6.1.4.1.10002.1 it's a wireless device
.1.3.6.1.4.1.10002.2 it's a camera

Also, 
.1.3.6.1.4.1.10002.1.1 could be AirMAX and
.1.3.6.1.4.1.10002.1.2 could be UniFi, etc.

Full oid for UAP could be
.1.3.6.1.4.1.10002.1.1.1

or however you deem appropriate.  As long as it is consistent.

Thanks :)
