### ISSUE TITLE
snmpbulkwalk hangs on Eltek Valere power devices

### ISSUE THREAD

**Issue by cron410** [librenms/librenms#6978]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | aeedf515c5903a56f808e6c3407c9aa371574835
DB Schema | 199
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/820bc38b
https://p.libren.ms/view/4ce6675d
snmpbulkwalk just hangs. No output.

- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

I am trying to get more information from our Eltek Valere power devices. They are basically skeleton UPS' with separate batteries, rectifiers, and hot swappable controllers. Logically they operate like a UPS.

We are receiving notifications that "Devices have not been polled" because snmpbulkwalk hangs when scanning this type of device. LibreNMS spawns ~8 snmpbulkwalk processes to scan this device and they all hang. We only have one added to LibreNMS at the moment and it is in our lab environment so we can do whatever we want to this device. I have about 20 more out in the field that are not on the management network yet and that is the end goal. To at least get notifications when power goes out somewhere and hopefully get basic power data in RRD graphs.

snmpwalk -v2c -c public 192.168.1.60 | ./pbin.sh
 https://p.libren.ms/view/f6f96cac
snmpwalk -v2c -c public 192.168.1.60 -Cc | ./pbin
 https://p.libren.ms/view/09ab5cc7

I do have the MIBs from the manufacturer if needed. They came on the CD and they have also been cached on SGI's (yes THAT SGI) FTP server here: ftp://ftp.sgi.com/public/Valere/Rackable%20Valere%20quick-start%20Pack/Valere%20Driver%20CD/MIBS/

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
You forgot the trailing . on your snmpwalk queries.  Try that and if that fails, just snmpwalk enterprises

**Comment by murrant** [comment]
Those mibs seem to be a re-write of the same mib many times...  I hope I'm wrong.

**Comment by cron410** [comment]
snmpwalk -v2c -c public 192.168.1.60 . | ./pbin.sh
https://p.libren.ms/view/7ce41c75

snmpwalk -v2c -c public 192.168.1.60 -Cc . | ./pbin.sh
 https://p.libren.ms/view/2b89cdc1


I'm actually seeing more info now that I look through these SNMPwalks. Sysdescription should be one of the first two strings, or both concatenated together. BC2000 is the controller model number. Eltek Valere is the manufacturer.

**Comment by murrant** [comment]
Do you have the mib that came on the CD?  Those in the link seem to be different versions of the same mib all mixed up.

**Comment by cron410** [comment]
Looks to be all the same ones. I believe that folder on the SGI ftp site is a copy of the CD I have.

[MIBS.zip](https://github.com/librenms/librenms/files/1132121/MIBS.zip)

**Comment by murrant** [comment]
Well, the mibs don't line up with what the device is providing.  This shows module information, noticed out the data is not in the same spot as the mib thinks it should be.
```
VALERE-DC-POWER-MIB::vpwrModuleSerialNumber.1.1 = Wrong Type (should be OCTET STRING): INTEGER: 1
VALERE-DC-POWER-MIB::vpwrModuleSerialNumber.1.2 = Wrong Type (should be OCTET STRING): INTEGER: 1
VALERE-DC-POWER-MIB::vpwrModuleModelNumber.1.1 = Wrong Type (should be OCTET STRING): INTEGER: 1
VALERE-DC-POWER-MIB::vpwrModuleModelNumber.1.2 = Wrong Type (should be OCTET STRING): INTEGER: 2
VALERE-DC-POWER-MIB::vpwrModuleFwVersion.1.1 = STRING: 152086000657
VALERE-DC-POWER-MIB::vpwrModuleFwVersion.1.2 = STRING: 152486003697
VALERE-DC-POWER-MIB::vpwrModuleTestDate.1.1 = STRING: V1000A
VALERE-DC-POWER-MIB::vpwrModuleTestDate.1.2 = STRING: V1000A
VALERE-DC-POWER-MIB::vpwrModuleOperHours.1.1 = Wrong Type (should be Counter32): STRING: "02.22"
VALERE-DC-POWER-MIB::vpwrModuleOperHours.1.2 = Wrong Type (should be Counter32): STRING: "02.22"
VALERE-DC-POWER-MIB::vpwrModuleIdentEntry.6.1.1 = STRING: "06:28:15-06:26:43"
VALERE-DC-POWER-MIB::vpwrModuleIdentEntry.6.1.2 = STRING: "06:13:15-16:37:15"
VALERE-DC-POWER-MIB::vpwrModuleIdentEntry.7.1.1 = Counter32: 13344
VALERE-DC-POWER-MIB::vpwrModuleIdentEntry.7.1.2 = Counter32: 13106

```

**Comment by cron410** [comment]
Do you think contacting the manufacturer is the next step? Last time we called them on the phone to get the latest firmware for these things they acted like we were calling from another planet. 

I also found more info here: https://infoproducts.alcatel-lucent.com/cgi-bin/dbaccessfilename.cgi/DO600000105_V1_LAN%20ETHERNET%20FEATURES%20INST.pdf and search for MIB

**Comment by murrant** [comment]
@cron410 I've added some sensors for the system.  Does that cover what you are looking for?

**Comment by cron410** [comment]
I'll have to check when I have access to that machine at work. Might have to wait until monday.

**Comment by cron410** [comment]
Looks really good now with the logo. How do I turn off traffic graphs for this device type? I am also not sure what discovery and poller modules to turn on so we can get power data. I turned off a lot of things when I was trying to get LibreNMS processes to stop locking up on it.

**Comment by murrant** [comment]
LibreNMS wasn't locking up, it was waiting.

We can set the graphs in in the upper right in the os definition.  We can also define default discovery and poller modules.  FYI, most modules do nothing if the is no data.

**Comment by cron410** [comment]
I wanted to add a new MIB file for these devices. Might have better information. This is for JC2000 and BC2000 Eltek controllers. https://eltek.sharefile.com/app/#/home/shared/fo9fff3c-6dec-4e14-8953-0b8c68ca3b7c the login credentials are noted below the login box.

**Comment by cron410** [comment]
[EltekDcPowerBc2000_V21_2.zip](https://github.com/librenms/librenms/files/1337758/EltekDcPowerBc2000_V21_2.zip)
