### ISSUE TITLE
Crazy traffic graph

### ISSUE THREAD

**Issue by bahirul** [librenms/librenms#6987]
Fresh install librenms and after a few hour, i notice graph value is crazy. I monitor real traffic in my device and only show small traffic.

Attached Screenshot crazzy traffic :

![crazzy-traffic-1](http://i.imgur.com/HNJZUp4.png)

![crazzy-traffic-2](http://i.imgur.com/BKTbWqk.png)

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
