### ISSUE TITLE
Please add Canon page counters

### ISSUE THREAD

**Issue by 21let** [librenms/librenms#6990]
At Librenms I would like to see the number of copies printed on Canon photocopiers and others. At Canon Copiers I have tried that counters can be read from these OIDs:

101 (Total) - 1.3.6.1.4.1.1602.1.11.1.3.1.4.101
112 Total (Black and White/Large) - 1.3.6.1.4.1.1602.1.11.1.3.1.4.112
113 Total (BW/Small) - 1.3.6.1.4.1.1602.1.11.1.3.1.4.113
122 Total (Full Color + Single / large) 1.3.6.1.4.1.1602.1.11.1.3.1.4.122
123 Total Full Color + Single/Small) 1.3.6.1.4.1.1602.1.11.1.3.1.4.123
501 Scan - 1.3.6.1.4.1.1602.1.11.1.3.1.4.501

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
