### ISSUE TITLE
Core port not shown in overview 

### ISSUE THREAD

**Issue by raymonvdm** [librenms/librenms#6993]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

```
Component | Version
--------- | -------
LibreNMS  | 61103938dc691bb7faa0207551c4924e54923bad
DB Schema | 199
PHP       | 7.0.18-0ubuntu0.16.04.1
MySQL     | 5.7.18-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
```

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

https://p.libren.ms/view/4e2ac96a
https://p.libren.ms/view/299195f3
https://p.libren.ms/view/4739e2d1

- [x] Please provide as much detail as possible.

The interface description is set to this (which works for observium)

`interface GigabitEthernet0/23
 description "Core: Raymon[1Gbit](Uplink Raymon) {O000002}"`

But the ports are not shown under Ports -> Core 
The Customers are also not shown Ports -> Customers

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Please test this patch:

https://p.libren.ms/view/raw/2b6bc3e2

**Comment by raymonvdm** [comment]
This issue is solved for me now!

**Comment by murrant** [comment]
laf: the \" is because the " is in the string inputed by the user.

Look at this one: `\"Cust: Raymon[1Gbit](crs2.dro2.raqxs.net Eth3 - Trunk) {O000002}`
