### ISSUE TITLE
Intermintent port polling issue

### ISSUE THREAD

**Issue by XioNoX** [librenms/librenms#6995]
Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date?
Yes, on 1.29
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
```
Component | Version
--------- | -------
LibreNMS  | 3f407a7831e004b6e5d0c0bb334834bb4e032595
DB Schema | 195
PHP       | 5.6.30-0+deb8u1
MySQL     | 10.0.23-MariaDB-log
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
```
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

Some of the outputs have been sent privately to @laf, please let me know if more need to be sent.
I've not been able to capture it when running:
> ./poller.php -h 145 -r -f -d -m ports

So far that command has only properly changed the wrong values to the correct ones. (maybe an issue between the cron and manual execution?)
Is there a way to log the  cron output of the poller for a specific device/module?

- [x] Please provide as much detail as possible.

Since we upgraded from 1.27 to 1.29, the port usages informations stored in the database is intermittently wrong or null. On the other hand, the RRD graphs are always accurate.
This has been happening on at least EX, QFX and MX Juniper devices.
For example, setting in config.php
> $config['debug_port']['11510'] = true;

Logs the following: https://pastebin.com/z9PVdz1n

Please let me know how I can help!

**Comment by laf** [comment]
Please open a discussion on the community site. GitHub is for confirmed bugs or new device support

**Comment by XioNoX** [comment]
What is needed to confirm the bug? How can I troubleshot it more?
Thanks

**Comment by laf** [comment]
You've provided the info needed to me so it's waiting on me to investigate, if you wan someone else to be able to help then you'll need to post the information publicly but until it's a confirmed bug then you should discuss this on the community site.
