### ISSUE TITLE
API: add new hosts with SNMPv3 not working

### ISSUE THREAD

**Issue by superflip99** [librenms/librenms#6998]
Hi

I try to add new hosts with API calls like:
ibrenms@nms:/opt/librenms$ curl --insecure -X POST -d '{"hostname":"test1.xy.at","port":"161","version":"v3","authlevel":"AuthPriv","authname":"username","authpass":"aaaaaaaaaaaaaaaaa","authalgo":"SHA","cryptopass":"bbbbbbbbbbbbbbbbb","cryptoalgo":"AES"}' -H 'X-Auth-Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'  https://nms.mon.dsh.at/api/v0/devices
{
    "status": "error",
    "message": "Could not connect to test1.xy.at, please check the snmp details and snmp reachability"
}
I also tried with different credentials without success - when I use "force_add" the new host is added, but snmpv3 credentials get lost - thereforce maybe there is a relation to issue #6997?

If you need further details for analyzing please let me know.

Thanks,
Philipp

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [yes] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli:
==========================================================
Component | Version
--------- | -------
LibreNMS  | 61103938dc691bb7faa0207551c4924e54923bad
DB Schema | 199
PHP       | 7.0.19-1~dotdeb+8.1
MySQL     | 10.0.30-MariaDB-0+deb8u2
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
