### ISSUE TITLE
User authenticated by http gets the lowest user-level permissions

### ISSUE THREAD

**Issue by elbuit** [librenms/librenms#6999]
DO NOT DELETE THIS INFORMATION.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
==========================================================
Component | Version
--------- | -------
LibreNMS  | 967fb8009235a1b17808aec86ab4a90c17aeb66b
DB Schema | 195
PHP       | 5.4.45-0+deb7u8
MySQL     | 10.0.28-MariaDB-0+deb8u1
RRDTool   | 1.5.6
SNMP      | NET-SNMP 5.4.3
==========================================================

Hi, since I've updated librenms to latest monthly version I'm experimenting a permission issue.
I'm using http-auth for authentication and Ive lost permission to see any device.

My conf:
$config['http_auth_guest'] = "guest"; (wich has a level "1" in users table.)

I've found that this happens since patch:
 "14a143a - fix: Fixed http-auth not honouring http_auth_guest (#6699)"

Lines 76 and 77 in html/includes/authentication/http-auth.inc.php are the responsible for this behaviour:
        'SELECT `level` FROM `users` WHERE `username`=? OR `username`=?',
        array($username, $config['http_auth_guest'])

This select returns user level of the logged user OR http_auth_guest (TWO values instead of one):

mysql> SELECT level FROM users WHERE username='elbuit' OR username='guest';
+-------+
| level |
+-------+
|     1 |
|    10 |
+-------+

Although user elbuit has a level '10'  librenms gets a userlevel of 1 (the first one).

There are two possible solutions:
* Set $config['http_auth_guest'] to a user with the highest level (ie 10)
config.php:
$config['http_auth_guest']="admin" (or other user with level 10) 

* Select the max level from user and http_auth_guest
html/includes/authentication/http-auth.inc.php:76
        'SELECT MAX(`level`) FROM `users` WHERE `username`=? OR `username`=?',

In the second way to solve, If the user exists in librenms (db table users) and have a level higher than $config['http_auth_guest'] user , this user will get this own permission level, otherwise he'll get config http auth level.

The first way to solve could lead us to some security issues.
If you have a user that can authenticate through http basic auth and is NOT defined in librenms, this user will be capable of login into librenms and inherits $config['http_auth_guest'] , so if you have set $config['http_auth_guest']="admin" this userl will get administration permissions.

I think that could be a source of security issues, because we need to limit by http-auth which users will be allowed to authenticate and then add those users to librenms.

This can be avoided removing the OR sentence in SQL ("OR `username`=?' " ) in functions user_exists() , get_userlevel(), get_userid() at html/includes/authentication/http-auth.inc.php
would prevent to login a non-defined user in librenms through http-auth
Then, if a user doesn't exists in librenms dbusers  won't be allowed to login.

I'm open to suggestions.

**Comment by murrant** [comment]
It should not be based on which level is higher.  If the user exists in the DB, it is not a guest.

**Comment by elbuit** [comment]
imagine that a user doesn't exist in db, in that case this user could get more permissions than a existing user.
I think that if a user doesn't exist in db, It shouldn't be allowed to login due to security issues.
But I don't know the consequences if I force all users to have a db entry.

**Comment by murrant** [comment]
the point of the guest level setting is to allow users that don't exist to log in. If that isn't set, they aren't allowed to log in.
