### ISSUE TITLE
adding FibreChannel interface info for brocade 1000 switch

### ISSUE THREAD

**Issue by boudreau** [librenms/librenms#7009]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

LibreNMS  | d30e5660f942154bd72c1b3f6ff3846d3c1b7137
DB Schema | 199
PHP       | 7.0.17
MySQL     | 10.1.22-MariaDB
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.2

there is a table of FC interface fir the brocade 1000 switch at the OID that is not polled:  1.3.6.1.4.1.1588.2.1.1.1.6

What is already detected by librenms:

```
Hardware | Brocade 1000 Switch
Operating System | Brocade FabricOS v8.1.0a
Object ID | enterprises.1588.2.1.1.1
```

An example of this snmp poll for the first interface: 

```
SYSTEM-MIB::swFCPortIndex.1 = INTEGER: 1
SYSTEM-MIB::swFCPortType.1 = INTEGER: other(7)
SYSTEM-MIB::swFCPortPhyState.1 = INTEGER: inSync(6)
SYSTEM-MIB::swFCPortOpStatus.1 = INTEGER: online(1)
SYSTEM-MIB::swFCPortAdmStatus.1 = INTEGER: online(1)
SYSTEM-MIB::swFCPortLinkState.1 = INTEGER: enabled(1)
SYSTEM-MIB::swFCPortTxType.1 = INTEGER: lw(2)
SYSTEM-MIB::swFCPortTxFrames.1 = Counter32: 820536
SYSTEM-MIB::swFCPortRxFrames.1 = Counter32: 820531
SYSTEM-MIB::swFCPortRxC2Frames.1 = Counter32: 0
SYSTEM-MIB::swFCPortRxC3Frames.1 = Counter32: 0
SYSTEM-MIB::swFCPortRxLCs.1 = Counter32: 362508
SYSTEM-MIB::swFCPortRxMcasts.1 = Counter32: 0
SYSTEM-MIB::swFCPortTooManyRdys.1 = Counter32: 0
SYSTEM-MIB::swFCPortNoTxCredits.1 = Counter32: 169373
SYSTEM-MIB::swFCPortRxEncInFrs.1 = Counter32: 0
SYSTEM-MIB::swFCPortRxCrcs.1 = Counter32: 0
SYSTEM-MIB::swFCPortRxTruncs.1 = Counter32: 0
SYSTEM-MIB::swFCPortRxTooLongs.1 = Counter32: 0
SYSTEM-MIB::swFCPortRxBadEofs.1 = Counter32: 0
SYSTEM-MIB::swFCPortRxEncOutFrs.1 = Counter32: 0
SYSTEM-MIB::swFCPortRxBadOs.1 = Counter32: 12
SYSTEM-MIB::swFCPortC3Discards.1 = Counter32: 0
SYSTEM-MIB::swFCPortMcastTimedOuts.1 = Counter32: 0
SYSTEM-MIB::swFCPortTxMcasts.1 = Counter32: 0
SYSTEM-MIB::swFCPortLipIns.1 = Counter32: 0
SYSTEM-MIB::swFCPortLipOuts.1 = Counter32: 0
SYSTEM-MIB::swFCPortLipLastAlpa.1 = Hex-STRING: 00 00 00 00
SYSTEM-MIB::swFCPortWwn.1 = Hex-STRING: 20 00 C4 F5 7C AC 19 C6
SYSTEM-MIB::swFCPortName.1 = STRING: ISL_FERSW4_BHCORE4
SYSTEM-MIB::swFCPortSpecifier.1 = STRING: 0
SYSTEM-MIB::swFCPortFlag.1 = BITS: 00
SYSTEM-MIB::swFCPortBrcdType.1 = INTEGER: e-port(5)
```

Is it possible to add them to the list of ports?

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
