### ISSUE TITLE
Add Support for Ubnt AirFiber Lat/Long Altitude 

### ISSUE THREAD

**Issue by 07stuntar1** [librenms/librenms#7012]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the 
==========================================================
Component | Version
--------- | -------
LibreNMS  | 2bf99c65a06c2952a536557eb4b957e7cc15d554
DB Schema | 199
PHP       | 7.0.20
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================
[OK]    Database connection successful

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery Output:  https://p.libren.ms/view/5009017f
Poller Output:        https://p.libren.ms/view/34a9fe33
SNMP Walk:           https://p.libren.ms/view/8635252f

AirFiber
"gpsSync" "1.3.6.1.4.1.41112.1.3.1.1.8"
"gpsPulse" "1.3.6.1.4.1.41112.1.3.2.1.28"
"gpsFix" "1.3.6.1.4.1.41112.1.3.2.1.29"
"gpsLat" "1.3.6.1.4.1.41112.1.3.2.1.30"
"gpsLong" "1.3.6.1.4.1.41112.1.3.2.1.31"
"gpsAltMeters" "1.3.6.1.4.1.41112.1.3.2.1.32"
"gpsAltFeet" "1.3.6.1.4.1.41112.1.3.2.1.33"
"gpsSatsVisible" "1.3.6.1.4.1.41112.1.3.2.1.34"
"gpsSatsTracked" "1.3.6.1.4.1.41112.1.3.2.1.35"
"gpsHDOP" "1.3.6.1.4.1.41112.1.3.2.1.36"

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
Not sure where this would be displayed.

We could perhaps set sysLocation with the lat/long, but that doesn't quite seem right.

**Comment by 07stuntar1** [comment]
I was just hoping since the wireless shots had GPS data it would be able to be placed on the Map in Librenms.
Thank You

**Comment by murrant** [comment]
You can update sysLocation to do this now.
