### ISSUE TITLE
Tripplite Poweralert new SNMPcard HTML5 Health Data not working

### ISSUE THREAD

**Issue by 07stuntar1** [librenms/librenms#7015]
SNMPCard WEBCARDLX -HTML5 version
Ubuntu 12.04.3 LTS Linux 3.8.13 flash: 3.5G ram: 250168kB processor: armv7l software: PowerAlert 15.00 (0-0001)
System Name	           ups-tripplite-test
Operating System      Tripp Lite PowerAlert 15.00 (0-0001)
Object ID	                   enterprises.850.1.1.1

Seems like the all the Health data is not being graphed from the Tripplite PDU and the UPS is missing current and power data. 

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the 

==========================================================
Component | Version
--------- | -------
LibreNMS  | 282e4b77a5a30271287adf31afe6929747540c8e
DB Schema | 199
PHP       | 7.0.20
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

[OK]    Database connection successful

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

PDU - Missing all Health Data
Discovery Output:    https://p.libren.ms/view/d19efdaa
Poller Output:          https://p.libren.ms/view/b117b1dc
SNMP Walk:             https://p.libren.ms/view/3ebdf8e3

UPS - New one seems to be missing current and power
Discovery Output:   https://p.libren.ms/view/0587f51e
Poller Output:          https://p.libren.ms/view/ef2f28c5  
SNMP Walk:             https://p.libren.ms/view/e1622872

here is the link for the MIBs https://www.tripplite.com/shared/software/Firmware/TRIPPLITE-MIB.zip

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Thank You

**Comment by 07stuntar1** [comment]
@laf Hi, what do I need to do with the Needs-Verification? 
Thank You

**Comment by murrant** [comment]
Needs Verification means a developer needs to go through the data you've provided ;)

**Comment by 07stuntar1** [comment]
@murrant ok Thank You

**Comment by 07stuntar1** [comment]
Hi Just realized the UPS Battery Temperature is reporting wrong also.
Show
Battery |   | 350°C

Thank You

**Comment by laf** [comment]
Poweralert devices should confirm to RFC1628. We have full detection for these if they do. Your second device shows that it's supporting most.

I'd probably suggest you speak to the vendor and ask them why they aren't returning all the data for RFC1628 MIB.

**Comment by 07stuntar1** [comment]
@laf  Thank Yo will do

**Comment by laf** [comment]
If you get any more info on this please reply to this issue and we can re-open.

**Comment by 07stuntar1** [comment]
@laf  I spoke to Tripplite Technical Support for the new SNMP card which is the WEBCARDLX they said.
There Email said 

Yes, the WEBCARDLX requires an additional set of MIB's to be loaded.  See below.  

Load/compile the four individual MIB files onto your NMS in 
    the following order:

    TRIPPLITE.MIB            (Load First)
    TRIPPLITE_PRODUCTS.MIB   (If WEBCARDLX family SNMP/Web Interface 
                              cards will be monitored)
    TRIPPLITE_12X.MIB        (If SNMPWEBCARD family SNMP/Web Interface 
                              cards will be monitored)       
    RFC-1628-UPS.MIB         (Load last, if desired)

    The order is important. Please be sure to load the appropriate MIB files for
    your system in the correct order.

When the card is installed into a UPS is reporting most data (I'm not sure if they added any additional wtih the new MIBs) but for some reason the PDU is not reporting anything to Librenms. IM not sure if I am able to load them into Librenms like they described. 

Thank You

**Comment by murrant** [comment]
That honestly doesn't make much sense.  Many times we don't use mibs at all.  In fact if you were to snmpwalk `.1.3.6.1.2.1.33.1.4.4.1.3` you will get the rfc1628 output current with no mibs loaded.

Looking at the walk you supplied for the PDU there are only two pieces of data that are not standard mib data:
```
.1.3.6.1.2.1.33.1.1.4.0 = STRING: "15.00 (0-0001)"
.1.3.6.1.2.1.33.1.6.1.0 = Gauge32: 0
```
The first one is `UPS-MIB::upsIdentAgentSoftwareVersion.0`, the second one is `UPS-MIB::upsAlarmsPresent.0`  Neither of these are the data you want.

I have several tripplite UPS and we are working to get rid of them. Some supply some data others no data. The best I can guess is the UPS itself supplies the data and the snmpcard/webcard just relay it. 
snmpcards lock up constantly and the java interface works badly. Instead of fixing it they released a new product.

If you can get support to actually help you that might help everyone.

`UPS-MIB::upsObjects` will contain all rfc1628 supplied data.

Until this returns data, we can't do anything to help you.
```
snmpwalk -v2c -c COMMUNITY -M +/opt/librenms/mibs HOSTNAME UPS-MIB::upsObjects
```
or
```
snmpwalk -v2c -c COMMUNITY HOSTNAME .1.3.6.1.2.1.33.1
```

**Comment by 07stuntar1** [comment]
@murrant Hi Sorry for the late reply. We have been working with a Tripplite Engineer. I asked the engineer about walking the PDUs and he said that the new WEBCARDLX cards use Tripplties MIBs and that I would need to load there MIBs into my database in order for it to work. (not sure how to do this)
He said only the base is using RFC1628 MIBs.
He emailed me this 
INSTRUCTIONS FOR LOADING THE TRIPP LITE WEB/SNMP CARD MIBS AND RFC1628 MIB: -------------------------------------------------------------------------------- 1)  Download and uncompress the appropriate MIB package for your operating system (either TRIPPLITE-MIB.zip or TRIPPLITE-MIB.tar.gz) onto your NMS. 
 
    This operation will yield four individual MIB files and this README.TXT file. 
 
2)  Load/compile the four individual MIB files onto your NMS in the following order: 
 
    TRIPPLITE.MIB                        (Load First)     TRIPPLITE_PRODUCTS.MIB   (If WEBCARDLX family SNMP/Web Interface cards will be monitored)     TRIPPLITE_12X.MIB                (If SNMPWEBCARD family SNMP/Web Interface cards will be monitored)            RFC-1628-UPS.MIB                 (Load last, if desired) 
 
    The order is important. Please be sure to load the appropriate MIB


He said after loading this I should see all data being returned.
