### ISSUE TITLE
Error when running snmp-scan.py

### ISSUE THREAD

**Issue by jwmoss** [librenms/librenms#7034]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 550e412808874b6d832d427e62c5977553619b10
DB Schema | 199
PHP       | 7.0.18-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

[OK]    Database connection successful
[OK]    Database schema correct

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.

Unable to run SNMP-Scan.py, see below for config.php and error when running snmp-scan.py as librenms user.

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Config.php: https://pastebin.com/raw/2wsacV4c

root@librenms2:/opt/librenms# sudo su - librenms
$ ./snmp-scan.py -r 192.168.254.0/24
Traceback (most recent call last):
  File "./snmp-scan.py", line 37, in <module>
    from enum import Enum
ImportError: No module named enum

$ python -V
Python 2.7.12

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
