### ISSUE TITLE
Emerson Energy System (ESS) 

### ISSUE THREAD

**Issue by nguyh** [librenms/librenms#7035]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Component | Version
--------- | -------
LibreNMS  | 9dbb6c32628db80ec4faf8d8247c8749d2ba68b2
DB Schema | 199
PHP       | 7.0.18-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

Hi, 

We have Emerson Energy Systems (EES) discovered by librenms but it didn't detect as power unit and appears as linux server category.  Will it be possible to include those ESS in the librenms ? 

Here is the data I gather.  

**discovery.php output**
https://p.libren.ms/view/812db9a5

**Poller.php output**
https://p.libren.ms/view/3016229c

**snmpwalk output**
https://p.libren.ms/view/0a228b03#L22

**Emerson Energy System mib file**
[mib.zip](https://github.com/librenms/librenms/files/1149327/mib.zip)

**Comment by laf** [comment]
Please give https://github.com/librenms/librenms/issues/7128 a test.

**Comment by nguyh** [comment]
Hi @laf 
Just applied the pre-commit for #7128.  I can see now the voltage,current and state.  There is one minor thing, the output of the Rectifiers  are not shown in numerical order.  

![gic-mgmt-jumphosts-connectivity-1](https://user-images.githubusercontent.com/20876052/29056557-ba777c5c-7bd1-11e7-8a9d-43d6e5d14f02.png)

**Comment by laf** [comment]
That's an issue in the webui and not something we can easily resolve as it's based on the sort order done by mysql

**Comment by nguyh** [comment]
@laf

Just look the value of Emerson DC rectifier device  today and here are the 2 issues

Rectifier#x  in current table  shows the wrong value, remain at 0A 
snmpbulkwalk  shows : 
EES-POWER-MIB::psRectifierCurrent.3 = INTEGER: 17476
EES-POWER-MIB::psRectifierCurrent.4 = INTEGER: 17707
EES-POWER-MIB::psRectifierCurrent.5 = INTEGER: 18122
EES-POWER-MIB::psRectifierCurrent.6 = INTEGER: 20230
EES-POWER-MIB::psRectifierCurrent.7 = INTEGER: 17898
EES-POWER-MIB::psRectifierCurrent.8 = INTEGER: 18381

Second issue on the webui upper right the graph remain solid red and when I click on it, the error messages states  "You have insufficient permissions to view this page".

**Comment by laf** [comment]
Should be fixed shortly.
