### ISSUE TITLE
Ubiquiti IPv4 information missing from FDB Table

### ISSUE THREAD

**Issue by salt-lick** [librenms/librenms#7045]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Page
http://localhost/device/device=5/tab=ports/view=fdb/

Device: https://www.ubnt.com/unifi-switching/unifi-switch-2448/

Issue: the IPv4 fields are not being populated. With the same MIBs, OpenNMS is able to associate ports and downstream IPs.

OpenNMS: 

![opennms](http://i.imgur.com/KU9kDoa.png)

```
==========================================================
Component | Version
--------- | -------
LibreNMS  | 534595d71d5ca5ef4dcf98540754a8e3ce90e021
DB Schema | 199
PHP       | 7.0.20
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================
```

https://p.libren.ms/view/3401c38b
https://p.libren.ms/view/d1941aa6
https://gist.github.com/salt-lick/d38e715124c57e4b611d42dd286d52a3

**Comment by murrant** [comment]
Did you look on the arp tab?  Unifiswitch does not seem to supply fdb data.

**Comment by salt-lick** [comment]
The ARP tab is empty. The FDB tab is populated with MAC, Port, and VLAN.

**Comment by murrant** [comment]
OK so
```
EdgeSwitch-SWITCHING-MIB::agentDynamicDsBindingIfIndex[STRING: 0:da:55:b6:d9:d2] = INTEGER: 3
EdgeSwitch-SWITCHING-MIB::agentDynamicDsBindingVlanId[STRING: 0:da:55:b6:d9:d2] = Gauge32: 3
EdgeSwitch-SWITCHING-MIB::agentDynamicDsBindingMacAddr[STRING: 0:da:55:b6:d9:d2] = STRING: 0:da:55:b6:d9:d2
EdgeSwitch-SWITCHING-MIB::agentDynamicDsBindingIpAddr[STRING: 0:da:55:b6:d9:d2] = IpAddress: 10.0.3.103
EdgeSwitch-SWITCHING-MIB::agentDynamicDsBindingLeaseRemainingTime[STRING: 0:da:55:b6:d9:d2] = Timeticks: (4867900) 13:31:19.00

```

**Comment by laf** [comment]
:(

**Comment by salt-lick** [comment]
Where do we stand on this? Is there anything thing I can do to help get this issue closed?

**Comment by murrant** [comment]
Basically, someone needs to write code to collect and process the data from Ubiquiti EdgeSwitch since it doesn't use standard mibs.

**Comment by laf** [comment]
@salt-lick Fancy giving the linked PR a try?

**Comment by salt-lick** [comment]
Actually, I did this morning - just got busy and forgot to update you.

<img width="1004" alt="screen shot 2017-08-22 at 10 24 58 am" src="https://user-images.githubusercontent.com/3297736/29573284-348f44c2-8724-11e7-98fa-9d6289b27849.png">
<img width="1005" alt="screen shot 2017-08-22 at 10 24 46 am" src="https://user-images.githubusercontent.com/3297736/29573283-348c60a4-8724-11e7-99fc-28a7a4c3d97b.png">

Looks like it's pulling correctly.

**Comment by laf** [comment]
Ace, thanks for confirming.

**Comment by zoc** [comment]
Hi guys,

I don't know if I should write into this (closed) ticket or if I should open a new one, but starting with EdgeSwitch 1.7.4.5075842, FDB is not available anymore using the private MIB, but is now available using the standard "Q-BRIDGE-MIB".

Basically, my FDB table was empty, so I renamed edgeswitch.inc.php to edgeswitch.inc.php.dis in include/discovery/fdb-table in order to use the default implementation, and now my FDB table is correctly filled...

**Comment by murrant** [comment]
@zoc You should post on discord or the community site, otherwise it might get missed.
But, please test this: https://github.com/librenms/librenms/pull/8710
