### ISSUE TITLE
Raspberry pi sensors not added 

### ISSUE THREAD

**Issue by Jo0Lz** [librenms/librenms#7057]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Component | Version
--------- | -------
LibreNMS  | 1.29-95-g5c46ad1a7
DB Schema | 199
PHP       | 7.1.6-2ubuntu1
MySQL     | 10.1.24-MariaDB-5
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

Followed [this](https://community.librenms.org/clicks/track?url=http%3A%2F%2Fdocs.librenms.org%2FExtensions%2FApplications%2F%23raspberry-pi&post_id=956&topic_id=430) tutorial. The raspberry.sh script works correctly, and the information is being "discovered", however sensors are not added to the LibreNMS database.

./raspberry.sh 
![image](https://user-images.githubusercontent.com/19903665/28361930-c579ed9e-6c7a-11e7-84f3-a7d18e989eb4.png)

Proof that the values are discovered with an SNMPwalk:
![image](https://user-images.githubusercontent.com/19903665/28363114-7a78455c-6c7f-11e7-9367-c6f66e945433.png)

`jo0lz@domotica:~ $ snmpwalk -Os -v1 -c public domotica .1.3.6.1.4.1.8072.1.3.2.4.1.2.9.114.97.115.112.98.101.114.114.121
iso.3.6.1.4.1.8072.1.3.2.4.1.2.9.114.97.115.112.98.101.114.114.121.1 = STRING: "55.3"
iso.3.6.1.4.1.8072.1.3.2.4.1.2.9.114.97.115.112.98.101.114.114.121.2 = STRING: "1.2688"
iso.3.6.1.4.1.8072.1.3.2.4.1.2.9.114.97.115.112.98.101.114.114.121.3 = STRING: "1.2000"
iso.3.6.1.4.1.8072.1.3.2.4.1.2.9.114.97.115.112.98.101.114.114.121.4 = STRING: "1.2000"
iso.3.6.1.4.1.8072.1.3.2.4.1.2.9.114.97.115.112.98.101.114.114.121.5 = STRING: "1.2250"
iso.3.6.1.4.1.8072.1.3.2.4.1.2.9.114.97.115.112.98.101.114.114.121.6 = STRING: "1200000000"
iso.3.6.1.4.1.8072.1.3.2.4.1.2.9.114.97.115.112.98.101.114.114.121.7 = STRING: "400000000"
iso.3.6.1.4.1.8072.1.3.2.4.1.2.9.114.97.115.112.98.101.114.114.121.8 = STRING: "enabled"
iso.3.6.1.4.1.8072.1.3.2.4.1.2.9.114.97.115.112.98.101.114.114.121.9 = STRING: "disabled"
iso.3.6.1.4.1.8072.1.3.2.4.1.2.9.114.97.115.112.98.101.114.114.121.10 = STRING: "disabled"
iso.3.6.1.4.1.8072.1.3.2.4.1.2.9.114.97.115.112.98.101.114.114.121.11 = STRING: "enabled"
iso.3.6.1.4.1.8072.1.3.2.4.1.2.9.114.97.115.112.98.101.114.114.121.12 = STRING: "enabled"
iso.3.6.1.4.1.8072.1.3.2.4.1.2.9.114.97.115.112.98.101.114.114.121.13 = STRING: "disabled"
`

output of `./discovery.php -h HOSTNAME -d -m sensors`:
https://pastebin.com/025GiY8f

Someone looked into this earlier (https://github.com/librenms/librenms/issues/6803) and as a result, the temperature sensor is now added. However, in the original new device "issue" (https://github.com/librenms/librenms/pull/4057) the voltage, clock frequencies and codec status were also added; this doesn't seem to work. (Tried on two different Pi's, both with different OS - OSMC vs Raspbian -)

This thread is also related to this, and has additional information from two users who have seemingly solved their issue by reverting back https://github.com/librenms/librenms/commit/28e35eff76fcf9dcfc1daf1837a65c83f3ac00d1 and checking.

Edit:
`./discovery.php -h HOSTNAME -d | ./pbin.sh` output: https://p.libren.ms/view/8f87f8ae
`./poller.php -h HOSTNAME -r -f -d | ./pbin.sh` output: https://p.libren.ms/view/213fd6b8
`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh` output: https://p.libren.ms/view/bbaf0e04

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by Jo0Lz** [comment]
Added output for the commands.

**Comment by Jo0Lz** [comment]
The issue is closed, however it does not seem to work on my two raspberry devices. One is running OSMC, one is running Raspbian, but voltages, frequencies and codec values are all returning as 0 on both devices. The raspberry.sh script does return (only) values.

**Comment by arrmo** [comment]
Hmmm ... confused here as well. I have updated LibreNMS to the latest code, and updated raspberry.sh on my RPI. Running the script on the RPi gives me the following,

```
38.5
1.3125
1.2000
1.2000
1.2250
900000000
250000000
enabled
disabled
disabled
enabled
enabled
WMV9=disabled
H264=2
MPG2=disabled
WVC1=disabled
MPG4=2
MJPG=2
WMV9=disabled
WMV9=disabled
H264=enabled
MPG2=1
WVC1=1
MPG4=enabled
MJPG=enabled
WMV9=1
```

But, the output from LibreNMS (after forcing a couple discovery / poller cycles) is below ... thoughts?
![image](https://user-images.githubusercontent.com/8756384/28991338-cf6f2110-794b-11e7-89ef-702673f4af3b.png)

Thanks!

**Comment by laf** [comment]
Please continue the discussion here https://community.librenms.org/t/raspberry-pi-temperature-voltage-freq/430/51
