### ISSUE TITLE
IOS Syslogs - programs not parsed correctly

### ISSUE THREAD

**Issue by EnzoZafra** [librenms/librenms#7076]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Component | Version
--------- | -------
LibreNMS  | 1.26-492-g890164c
DB Schema | 200
PHP       | 7.0.17
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.2

I noticed that for some devices with an 'ios' OS, when parsing the syslogs, it would create a program for each entry. In my case, it looks like its an incrementing index. i.e. if there are 10000 syslog entries there will be 10000 programs. This causes the syslog page to load very slow or sometimes crash the browser because it takes a very long time to execute the query.

Look at this table: https://pastebin.com/WApYR69S
It looks like all of the devices with > 1000 distinct programs has an 'ios' OS, so it probably has something to do with how its parsed.

When I searched through the syslog for device_id = 1224 (device with 165623 distinct programs) this is a snippet of what I found: https://pastebin.com/p0p2jwrE

The first part of each line is the 'program'.

**Comment by murrant** [comment]
Likely the syslog parsing is incorrect.  You can add another test case to the tests/SyslogTest.php file.  That would help a lot.

**Comment by EnzoZafra** [comment]
Hmm, it looks like the switch is purposely sending it as a sequence of numbers? I'm not too sure. Here is the line before it is formatted by the daemon:

> Jul 25 09:20:22 10.0.17.1 1328903: Jul 25 09:20:21.115: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet2/0/15, changed state to up

And this is the line after the daemon:

> 10.0.17.1||23||3||3||1328961:||2017-07-25 09:23:36|| Jul 25 09:23:35.026: %LINK-3-UPDOWN: Interface GigabitEthernet2/0/15, changed state to up||1328961

**Comment by EnzoZafra** [comment]
Here is the edited /tests/SyslogTest.php file: https://github.com/EnzoZafra/librenms/commit/1054b4ddc6c02a91cf68de23cbecf91d6eca0ff1

**Comment by laf** [comment]
Could this be a config option in IOS you have enabled: http://www.cisco.com/c/en/us/td/docs/routers/access/wireless/software/guide/SysMsgLogging.html#wp1054751

**Comment by EnzoZafra** [comment]
Although I didn't see that option in the running-config, it's most likely it. I'll turn it off and see if the problem persists,

**Comment by EnzoZafra** [comment]
Found the setting that was adding the sequence numbers. If anyone is having the same issue try
'no logging message-counter syslog'
