### ISSUE TITLE
Update LibreNMS to grab Arista optic high/low sensor values

### ISSUE THREAD

**Issue by shimamizu** [librenms/librenms#7078]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x ] Please provide as much detail as possible.
- [ x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

#############################################################
I already posted this on the community site and was told to open an issue here
https://community.librenms.org/t/update-librenms-to-grab-arista-optic-high-low-sensor-values/1765
#############################################################

Currently LibreNMS doesn't grab the right values for Arista switch High Alarm / High Warn / Low Alarm / Low Warn thresholds. It just makes guesses based on historic values but isn't grabbing the actual levels the switch uses for alarming. I've checked w/ Arista to find the right way to grab those OID's from the MIB. Please add this to the code so that LibreNMS can correctly alarm based on optic and temperature alarms. 

Step 1) Get the entity value you care about with this MIB: 
snmpwalk -v1 -c [COMMUNITY] [HOSTNAME] 1.3.6.1.2.1.47.1.1.1.1.2

For an example, say you wanted to look at values for optic in 3/29 of a chassis switch: 

snmpwalk -v1 -c [COMMUNITY] [HOSTNAME] 1.3.6.1.2.1.47.1.1.1.1.2 | grep 3/29
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103100113 = STRING: "Ethernet3/29/1"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103100114 = STRING: "Ethernet3/29/2"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103100115 = STRING: "Ethernet3/29/3"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103100116 = STRING: "Ethernet3/29/4"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329100 = STRING: "Xcvr for Ethernet3/29"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329201 = STRING: "DOM Temperature Sensor for Ethernet3/29"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329202 = STRING: "DOM Voltage Sensor for Ethernet3/29"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329210 = STRING: "Lane 0 for Xcvr for Ethernet3/29"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329211 = STRING: "DOM TX Bias Sensor for Ethernet3/29/1"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329212 = STRING: "DOM TX Power Sensor for Ethernet3/29/1"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329213 = STRING: "DOM RX Power Sensor for Ethernet3/29/1"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329220 = STRING: "Lane 1 for Xcvr for Ethernet3/29"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329221 = STRING: "DOM TX Bias Sensor for Ethernet3/29/2"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329222 = STRING: "DOM TX Power Sensor for Ethernet3/29/2"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329223 = STRING: "DOM RX Power Sensor for Ethernet3/29/2"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329230 = STRING: "Lane 2 for Xcvr for Ethernet3/29"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329231 = STRING: "DOM TX Bias Sensor for Ethernet3/29/3"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329232 = STRING: "DOM TX Power Sensor for Ethernet3/29/3"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329233 = STRING: "DOM RX Power Sensor for Ethernet3/29/3"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329240 = STRING: "Lane 3 for Xcvr for Ethernet3/29"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329241 = STRING: "DOM TX Bias Sensor for Ethernet3/29/4"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329242 = STRING: "DOM TX Power Sensor for Ethernet3/29/4"
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329243 = STRING: "DOM RX Power Sensor for Ethernet3/29/4"

To get the thresholds for entities above, you take that last number and then use this: 
.1.3.6.1.4.1.30065.3.12.1.1.1.1.[ENTITY_NUMBER_ABOVE] = Low Warning
.1.3.6.1.4.1.30065.3.12.1.1.1.2.[ENTITY_NUMBER_ABOVE] = Low Critical
.1.3.6.1.4.1.30065.3.12.1.1.1.3.[ENTITY_NUMBER_ABOVE] = High Warning
.1.3.6.1.4.1.30065.3.12.1.1.1.4.[ENTITY_NUMBER_ABOVE] = High Critical

So for example I want the high critical threshold for the above port Transmit power on 3/29/1:
SNMPv2-SMI::mib-2.47.1.1.1.1.2.103329212 = STRING: "DOM TX Power Sensor for Ethernet3/29/1"
So we would use 103329212 for the entity value

The outputs we would get would look like this, note the values don't look correct though! we have to convert them. In order to get the correct values, divide by 10,000 and then convert from mw to dBm. 

SNMPv2-SMI::enterprises.30065.3.12.1.1.1.1.103329212 = INTEGER: 4250
SNMPv2-SMI::enterprises.30065.3.12.1.1.1.2.103329212 = INTEGER: 4575
SNMPv2-SMI::enterprises.30065.3.12.1.1.1.3.103329212 = INTEGER: 19952
SNMPv2-SMI::enterprises.30065.3.12.1.1.1.4.103329212 = INTEGER: 22387

So converting them we get: 
4250 / 10000 => 0.4250mw => -3.7161106995 dBm ~ -3.72 dBm
4575 / 10000  => 0.4575mw => -3.396089016 dBm ~ -3.40 dBm
19952 / 10000  => 1.9952mw => 2.9998643613 dBm ~ 3.00 dbm
22387 / 10000  => 2.2387mw => 3.4986008219 dBm ~ 3.50 dBm

Which matches the output we see on the switch: 
From part of the output in "show interfaces ethernet 3/29/1 transceiver detail "

```
                         High Alarm  High Warn   Low Alarm   Low Warn    
           Tx Power      Threshold   Threshold   Threshold   Threshold   
Port       (dBm)         (dBm)       (dBm)       (dBm)       (dBm)       
-------    ------------  ----------  ----------  ----------  ----------  
Et3/29/1   1.53          3.50        3.00        -3.40       -3.72  
```

**Comment by shimamizu** [comment]
PS, I think you'll want to apply the above logic for the following sensors: 
DOM Temperature Sensor 
DOM Voltage Sensor
DOM TX Bias Sensor
DOM TX Power Sensor
DOM RX Power Sensor

Keep in mind too that for 40G/100G optics, the temperature and voltage will be for the transceiver as a whole and then the TX Bias, TX Power and RX Power will be for each "lane" of breakout the optic supports (aka 4 lanes for 40G optics, 12 lanes for 100G MTP, etc) 

Also the 100G can get kind of funny with it's breakout of lanes too. When running in native 100G mode for the optic, it will only use lanes 2-11. Example: 

```
switch# show run int et 50/1
interface Ethernet50/1
   speed forced 100gfull
   no switchport

switch#show interfaces transceiver | inc 50/
Et50/1     45.87      3.27      0.00     -30.00    -30.00    0:00:02 ago
Et50/2     45.87      3.27      6.26     0.65      -1.19     0:00:02 ago
Et50/3     45.87      3.27      6.24     0.74      -1.14     0:00:02 ago
Et50/4     45.87      3.27      6.17     0.68      -1.39     0:00:02 ago
Et50/5     45.87      3.27      6.21     0.73      -1.26     0:00:02 ago
Et50/6     45.87      3.27      6.32     0.63      -0.93     0:00:02 ago
Et50/7     45.87      3.27      5.62     0.61      -1.57     0:00:02 ago
Et50/8     45.87      3.27      5.93     0.49      -1.84     0:00:02 ago
Et50/9     45.87      3.27      6.27     0.65      -0.86     0:00:02 ago
Et50/10    45.87      3.27      6.05     0.41      -1.81     0:00:02 ago
Et50/11    45.87      3.27      6.28     0.59      -1.67     0:00:02 ago
Et50/12    45.87      3.27      0.00     -30.00    -30.00    0:00:02 ago
```
There are times though when the first and last channel in 100G optics can be used though, if you use "speed forced 10000full" on the individual breakout ports, then you would care about 50/1 and it's TX/RX etc values. 

```
switch# conf t
switch(config)# interface Ethernet50/1-12
switch(config-if-Et50/1-12)#speed forced 10000full
switch(config)# interface Ethernet50/11-12
switch(config-if-Et50/1-12)#shutdown
switch(config-if-Et50/1-12)#show interfaces transceiver | inc 50/
Et50/1     47.60      3.27      5.57     0.48      -3.80     0:00:05 ago
Et50/2     47.60      3.27      5.40     0.69      -2.89     0:00:05 ago
Et50/3     47.60      3.27      5.52     0.66      -4.21     0:00:05 ago
Et50/4     47.60      3.27      5.58     0.63      -3.71     0:00:05 ago
Et50/5     47.60      3.27      5.61     0.61      -3.65     0:00:05 ago
Et50/6     47.60      3.27      5.91     0.55      -3.30     0:00:05 ago
Et50/7     47.60      3.27      5.55     0.82      -3.18     0:00:05 ago
Et50/8     47.60      3.27      5.92     0.47      -3.51     0:00:05 ago
Et50/9     47.60      3.27      5.85     0.68      -2.87     0:00:05 ago
Et50/10    47.60      3.27      6.76     0.73      -3.06     0:00:05 ago
Et50/11    47.60      3.27      0.00     -30.00    -30.00    0:00:05 ago
Et50/12    47.60      3.27      0.00     -30.00    -30.00    0:00:05 ago
```

**Comment by laf** [comment]
I've got access to Arista gear running 100G so will look into this.

**Comment by shimamizu** [comment]
Great, I just wanted to point out the caveats of the lanes as sometimes you aren't using all lanes and don't want to give false alarms for lanes that purposely have no readings. Plus the first time I ever did troubleshooting on a 100G port that was running at 100G native I was *so* confused when I looked at the /1 value and it didn't report light. 

Let me know if I can be of further help for this as well, I had opened an SR w/ Arista folks originally to get help on finding the right MIB's.

**Comment by laf** [comment]
@shimamizu pull request submitted if you'd like to give it a try.

It also cleans up an issue I found with sensors being redetected all the time.

**Comment by shimamizu** [comment]
Just pulled this and got some whitespace errors. I pasted the output of the pull into the pull request comments for you.

**Comment by shimamizu** [comment]
K commented over there again, conversions need to be done on the sensor values received for Tx/Rx Power. See pull request for details.
