### ISSUE TITLE
Geist watchdog 15 - a final attempt 

### ISSUE THREAD

**Issue by banananananananana** [librenms/librenms#7082]
Hi

I see there's been a lot of support requests for the geist environmental sensors. Many of the requests have been closed due to you guys not having access to a geist device.

Well, geist themselves have one accessible on the interwebs.

webgui: http://76.79.48.112
snmpwalk: snmpwalk -v2c -c public 76.79.48.112

I've tried adding the device above to my own librenms install, but it only shows 1 sensor (the one with temp/humid) The other 3 temp sensors are not in my graphs.

Any chance you could add this device?

FYI...The device above shows temperature in fahrenheit - but this can be changed in the device itself to celcius (but it obviously requires a login)

**Comment by murrant** [comment]
I'm guessing the same oid for temperature with a user setting the controls the output.  Genius.

**Comment by banananananananana** [comment]
![image](https://user-images.githubusercontent.com/23183976/29062691-ec0b6836-7c22-11e7-9352-03b09701871b.png)

**Comment by laf** [comment]
He's serious, how we're supposed to work out if the value returned is fahrenheit or celsius is not obvious :(

**Comment by laf** [comment]
So the device actually returns another value to say it's C or F so it's not that bad.

Anyway, PR submitted. The device you linked to provides no real data so most of this is done from the MIB. I tidied up some existing sensors in the code. Give it a try.

**Comment by banananananananana** [comment]
i've added the patch, but i don't know if it actually works -because the public device is unreachable 90% of the time. good job geist.

Added patch

```librenms@librenms1:/opt/librenms$ ./scripts/github-apply 7143
Checking patch includes/common.php...
Hunk #1 succeeded at 1675 (offset 1 line).
Checking patch includes/definitions/discovery/geist-watchdog.yaml...
Checking patch includes/discovery/sensors/airflow/geist-watchdog.inc.php...
Checking patch includes/discovery/sensors/humidity/geist-watchdog.inc.php...
Checking patch includes/discovery/sensors/temperature/geist-watchdog.inc.php...
Checking patch includes/discovery/sensors/voltage/geist-watchdog.inc.php...
Checking patch includes/polling/sensors/pre-cache/geist-watchdog.inc.php...
Checking patch includes/polling/sensors/temperature/geist-watchdog.inc.php...
Checking patch includes/rewrites.php...
Checking patch includes/polling/sensors/temperature/geist-watchdog.inc.php...
Applied patch includes/common.php cleanly.
Applied patch includes/definitions/discovery/geist-watchdog.yaml cleanly.
Applied patch includes/discovery/sensors/airflow/geist-watchdog.inc.php cleanly.
Applied patch includes/discovery/sensors/humidity/geist-watchdog.inc.php cleanly.
Applied patch includes/discovery/sensors/temperature/geist-watchdog.inc.php cleanly.
Applied patch includes/discovery/sensors/voltage/geist-watchdog.inc.php cleanly.
Applied patch includes/polling/sensors/pre-cache/geist-watchdog.inc.php cleanly.
Applied patch includes/polling/sensors/temperature/geist-watchdog.inc.php cleanly.
Applied patch includes/rewrites.php cleanly.
Applied patch includes/polling/sensors/temperature/geist-watchdog.inc.php cleanly.```

the discovery of the device seems like it still only picks up the primary sensor - but not the additional ones.

**Comment by laf** [comment]
Using the device you linked us to only provides one sensor extra, it doesn't respond to any other data.
