### ISSUE TITLE
RSSI on Cisco 4G routers

### ISSUE THREAD

**Issue by maladd3** [librenms/librenms#7090]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Component | Version
LibreNMS | 1.30-5-g9211680
DB Schema | 200
PHP | 7.0.18-0ubuntu0.16.04.1
MySQL | 5.7.19-0ubuntu0.16.04.1
RRDTool | 1.5.5
SNMP | NET-SNMP 5.7.3

https://p.libren.ms/view/16c0c89b
https://p.libren.ms/view/4bbd35cb
For some unknown reason, the third does not upload correctly. I've created a paste and here it is:
https://p.libren.ms/view/b19de180

Can we get support for pulling back the current RSSI on Cisco IR (829 or 809) routers? I believe it works on CradlePoint.

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by maladd3** [comment]
Hopefully that is everything requested. Had some trouble getting some of the stuff to upload.

**Comment by laf** [comment]
Looks like you've done an encrypted paste on the snmpwalk with no key so we can't see the data.

**Comment by maladd3** [comment]
I'm getting an error that it's too large. I've attached the document... 
[output.txt](https://github.com/librenms/librenms/files/1198362/output.txt)

**Comment by laf** [comment]
Do you know the OID / Mib this data is in? I've looked in a few and either your walk doesn't include the data it should or I've not yet found the mib.

**Comment by maladd3** [comment]
I found this online. Does that seem like it helps?

To get the RSSI of connected clients, you will need this OID:

.1.3.6.1.4.1.9.9.273.1.3.1.1.3


Object | cDot11ClientSignalStrength
-- | --
OID | 1.3.6.1.4.1.9.9.273.1.3.1.1.3



http://snmp.cloudapps.cisco.com/Support/SNMP/do/BrowseOID.do?local=en&translate=Translate&objectInput=1.3.6.1.4.1.9.9.273.1.3.1.1.3

**Comment by laf** [comment]
That data isn't in your walk, you will need to run:

`snmpbulkwalk -v2 -cpublic HOSTNAME 1.3.6.1.4.1.9.9.273`

**Comment by maladd3** [comment]
I get 

iso.3.6.1.4.1.9.9.273 = No Such Object available on this agent at this OID

**Comment by maladd3** [comment]
I think it's this one. 

.1.3.6.1.4.1.9.9.661.1.3.4.1.1.1.20

I pulled the RSSI (show cel 1/0 radio) on the switch, as well as the snmpbulkwalk and they both returned -76.

**Comment by laf** [comment]
Thanks for the info.
