### ISSUE TITLE
Purging deleted ports

### ISSUE THREAD

**Issue by ivankisic** [librenms/librenms#7094]
Hi,

When polling information about ports, LibreNMS will keep historical information about removed ports (and the corresponding RRD files), filling up the disk space.

This is of course expected behavior, but some software like Docker will aggressively try to restart its containers, creating hundreds or thousands of interfaces in the process. I've found around 50k deleted ports on the LibreNMS instances I manage, almost all of them because of Docker.

At this point automating its purging is a bit complicated and not something I'd like doing, so I'm wondering:

- Is there an auto-purge method anywhere?
- Can the purge-deleted function be exposed in the API?
- As far as I can see, deleted-ports.inc.php removes database entries, but I can't find the function that removes the RRD files.

====================================
Component | Version
--------- | -------
LibreNMS  | 1.30-5-g9211680
DB Schema | 200
PHP       | 7.0.11
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by ivankisic** [comment]
Hi, I was aiming that this be more of a feature request, or a question whether this might be implemented. Thanks.

**Comment by murrant** [comment]
Check http://docs.librenms.org/Support/Configuration/#cleanup-options
