### ISSUE TITLE
HTML Emails Toggle Reversed

### ISSUE THREAD

**Issue by Impyus** [librenms/librenms#7104]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 1.30-9-gc3627ec
DB Schema | 200
PHP       | 7.0.21
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/0de6685a
https://p.libren.ms/view/4c1e299c
https://p.libren.ms/view/623bed8b

- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

This isn't a high priority issue, but I noticed it and thought I'd report it. The web interface, under Global Settings > Alert Settings > Email Transport. The function of the "Use HTML Emails" toggle appears to be reversed, i.e, I select "No" and I receive HTML formatted alerts, if I select "Yes" then I receive plain text formatted alerts.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3

I've tested this and with it set to No:
`Content-Type: text/plain; charset=utf-8`

with it set to Yes:
`Content-Type: text/html; charset=utf-8`
