### ISSUE TITLE
Add GUI for Alert/Maintenance-Schedules

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#711]
Cheers,

since the introduction of the new alerting system we have a table called `alert_schedule`.  
It expects 3 entries: `device_id`, `start` and `end`.
The `start` and `end` are to be formatted as MySQL timestamps.

This table is used to pause processing of alerts for a defined period of time.

There was discussion of using http://fullcalendar.io/ to manage this.
Personally I think that might be a bit too much. Simple jQuery datepicker should be enough.

Comments?

**Comment by laf** [comment]
fullcalendar.io is ambitious :) The reason I chose it is to create a calendar system for people to check upcoming maintenance schedules rather than creating a scheduled maintenance.

We should add something in soon that just lets you view a list, add a new one and then edit/ delete schedules.

**Comment by laf** [comment]
Also need to add support for this via the api which is easy enough to do :)

**Comment by Rosiak** [comment]
It would be nice to see the following: 
- Alert Schedule Profile
  - ANYDAY 0800-1800
  - MON-FRI 0800-1600
  - Custom etc.

One could then simply use a dropdown to select a schedule instead of messing around in a calender, but if custom is chosen then ofc. The calender makes sense.
One should also be able to create the schedule profiles.

**Comment by laf** [comment]
@f0o 

One question on this:

1. Is it possible to drop device_id from the alert_schedule table and add another table called alert_schedule_items where we associate devices / groups? This will enable someone to multiple items to a single maintenance window rather than per device or group.

**Comment by f0o** [comment]
no problemo :)

**Comment by laf** [comment]
Just a reminder when the dbschema is done to let me know so I can carry on with the webui :)

**Comment by laf** [comment]
@f0o 

DB Schema: https://raw.githubusercontent.com/laf/librenms/issue-711/sql-schema/048.sql

**Comment by laf** [comment]
PR done #835

**Comment by laf** [comment]
This is merged in now.

@Rosiak I've not added the support for time groups as I wasn't 100% sure how best to do this. When you go to create a maintenance window, being able to select Mon - Fri 9-6 wouldn't mean anything as you don't know if it's this week or next.

One thing I could do is add quick links to, this hour, next hour, next 12 hours, next 24 hours if that is useful? Or suggestions on how to implement what you want.
