### ISSUE TITLE
Enhancement: refactoring health info to use yaml for Avaya-ERS

### ISSUE THREAD

**Issue by tslytsly** [librenms/librenms#7117]
I'm going to work on moving the health info from php files to the yaml.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by tslytsly** [comment]
I'm copying the state programming from another yaml.

I noticed this:
```
states:
                        - { descr: other, graph: 1, value: 1, generic: 3 }```
what are the valid values for generic and graph? and what is it for?
(i understand `descr:` and `value:`)

**Comment by tslytsly** [comment]
in addition to the above question, is there a way to exclude an index based on the descr?
Or do I need to do this in PHP?

**Comment by laf** [comment]
graph is just if a graph should be drawn or not, I don't know why we have that so I set mine to 1.

The generic values are documented here: http://docs.librenms.org/Developing/Sensor-State-Support/#logic

Why do you need to exclude an index based on descr? An example might help.

**Comment by tslytsly** [comment]
Thanks for the info.

The ERS reports fan state in this table: ` s5ChasComTable`
But it contains some useless info in addition to the fan states.
Here is a [walk](https://p.libren.ms/view/efd1010e) of the table.

If you look at `s5ChasComDescr` you can see we get the fans and the temp sensor, great. 
We also get a couple of NULLs, some "unavailable" and some useless entries that are just the switch model name.

The fans are always `.6.10 - .6.13` so at the moment I have 4 entries in the yaml, one for each specific fan index, which is not ideal.

What I want to do is walk the table and only keep the fan and temp sensor states.

**Comment by laf** [comment]
Where's the value for fans in that?

**Comment by tslytsly** [comment]
this is the operational state of Fan 1: `s5ChasComOperState.6.10.0 = 5`

**Comment by laf** [comment]
So this is to provide all state info why not just add them all in? If you don't only want fans then we'd have to add some more logic to support that.

**Comment by tslytsly** [comment]
yea, well for now I've just got 4 entries in the yaml file to get the four fan states.
But I'd rather walk the table and get any fans.
Maybe I will just need to do it PHP...

**Comment by laf** [comment]
I mean why not also add the temp sensor and any others in? They would all need the same Status types for that to work.

**Comment by tslytsly** [comment]
Ah I see.
They do all have the same status types. and it does work.
But I also end up with the NULL entries showing.
Some entities on that table are useless, so I don't want to check them.

**Comment by laf** [comment]
up to you then if you want to do this in php :)

You can exclude based on value btw :D

**Comment by tslytsly** [comment]
> You can exclude based on value btw :D
ok, how? ❓

**Comment by laf** [comment]
From the docs :D

```
skip_values (optional): This is an array of values we should skip over.
skip_value_lt (optional): If sensor value is less than this, skip the discovery.
skip_value_gt (optional): If sensor value is greater than this, skip the discovery.
```

If it's just one value then:

```
skip_values: 4
```

If multiple:

```
skip_values:
    - 4
    - 5
```

**Comment by tslytsly** [comment]
Thanks @laf, missed that.

I gave up and used PHP, it's a bit to involved to do with yaml I think.
PR: [#7134](https://github.com/librenms/librenms/pull/7134)

**Comment by laf** [comment]
Merged in - thanks :)
