### ISSUE TITLE
JUNIPER-VLAN-MIB && Q-BRIDGE-MIB issue

### ISSUE THREAD

**Issue by rkutsel** [librenms/librenms#7122]
I was having issues querying my Juniper EX switches running junos 14.1X53-D101. Specifically, I couldn't get VLAN info with JUNIPER-VLAN-MIB. Though I didn't see any issues running it with Q-BRIDGE-MIB. Turns out that Junos ELS doesn't understand JUNIPER-VLAN-MIB. The following is the answer I got from juniper TAC:
 
_Platforms running Junos ELS versions implement Q-BRIDGE-MIB differently from non-ELS. This change now makes our MIB implementation non-standard. This jnxExVlan MIB, is not supported on ELS, so we must rely on  proper Q-BRIDGE-MIB support instead, please check this PR:

https://prsearch.juniper.net/InfoCenter/index?page=prcontent&id=PR1149118_

Looking at the code that takes care of this I'd like to propose changing it 

FROM:

`
$index_to_base = array_flip($base_to_index);

if ($device['os'] === 'junos') {
    require 'includes/discovery/vlans/junos.inc.php';
} else {
    require 'includes/discovery/vlans/q-bridge-mib.inc.php';
    require 'includes/discovery/vlans/cisco-vtp.inc.php';
}
`

TO:
`$index_to_base = array_flip($base_to_index);

if ($device['os'] === 'junos') {
    require 'includes/discovery/vlans/q-bridge-mib.inc.php';
} else {
    require 'includes/discovery/vlans/cisco-vtp.inc.php';
}`

I've tested older junos releases that are non-els and they didn't have problems whatsoever.

**Comment by laf** [comment]
I don't think that's the fix as that basically just removes the junos support added a few months ago.

This might be better:

https://p.libren.ms/view/raw/66ca3620

**Comment by laf** [comment]
Can you please though either continue the discussion in the issue you linked as it appears to be duplicated to that. Or join irc / the community forum to discuss further.
