### ISSUE TITLE
Raritan PDU CPU temperature sensor discovery failure

### ISSUE THREAD

**Issue by Tatermen** [librenms/librenms#7129]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

On the Raritan PX3 PDUs, the CPU temperature sensor has either changed or no longer exists. LibreNMS adds a new CPU temp sensor on every discovery run.

```
Temperature: SNMP[/usr/bin/snmpget -v2c -c 'nocman' -OUQs -m PDU-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/raritan udp:pdu-1-a.concourse3.atlasisp.net:161 unitCpuTemp.0 unitTempLowerWarning.0 unitTempLowerCritical.0 unitTempUpperWarning.0 unitTempUpperCritical.0]
unitCpuTemp.0 = No Such Object available on this agent at this OID
unitTempLowerWarning.0 = No Such Object available on this agent at this OID
unitTempLowerCritical.0 = No Such Object available on this agent at this OID
unitTempUpperWarning.0 = No Such Object available on this agent at this OID
unitTempUpperCritical.0 = No Such Object available on this agent at this OID

Discover sensor: .1.3.6.1.4.1.13742.4.1.3.1.5.0, , raritan, Processor Temp, snmp, 10, 1, , 0
SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'snmp' AND `sensor_class` = 'temperature' AND `device_id` = '194' AND sensor_type = 'raritan' AND `sensor_index` = '']
SQL[INSERT INTO `sensors` (`poller_type`,`sensor_class`,`device_id`,`sensor_oid`,`sensor_type`,`sensor_descr`,`sensor_divisor`,`sensor_multiplier`,`sensor_limit`,`sensor_limit_low`,`sensor_current`,`entity_link_index`)  VALUES ('snmp','temperature','194','.1.3.6.1.4.1.13742.4.1.3.1.5.0','raritan','Processor Temp','10','1','0','0','0','0')]
( 69979 inserted )
+SQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`severity`,`message`,`username`)  VALUES ('194','194','69979','sensor',NOW(),'3','Sensor Added: temperature raritan  Processor Temp','')]
```

![image](https://user-images.githubusercontent.com/8707177/29061773-1a10d40c-7c17-11e7-8ffe-be1dc359ca12.png)

[snmpwalk](https://gist.github.com/Tatermen/d7423badba77c130674de86f91a12f6e)

**Comment by laf** [comment]
Fixed. Thanks to @aldemira
