### ISSUE TITLE
Encoding::UndefinedConversionError - "\xE2" from ASCII-8BIT to UTF-8 for PaloAlto

### ISSUE THREAD

**Issue by CJloHuK** [librenms/librenms#7133]
Hello,

Did an integration of librenms with oxidized (on the same server) and facing an issue while trying to view the config from libre webui.

Encoding::UndefinedConversionError - "\xE2" from ASCII-8BIT to UTF-8 - getting that error.
oxidized displays the config just fine and when I check diffs they are all properly displayed too.

Version | 1.30-42-g40f25aa - Tue Aug 08 2017 23:31:22 GMT+0300

Thanks

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 1.30-43-gece0488
DB Schema | 201
PHP       | 7.0.18-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
