### ISSUE TITLE
Alert emails to LDAP users

### ISSUE THREAD

**Issue by Ultra2D** [librenms/librenms#714]
As far as I can tell the contacts to be alerted (via the email transport) are selected from the users table in the database. LDAP users are not added to the database, so they will not receive alert emails. Am I missing something here?

**Comment by laf** [comment]
That's not always the case :)

You can use these config options to send all alerts to a single contact:

$config['alerts']['email']['default_only'] = FALSE;                // Only send alerts to default-contact
$config['alerts']['email']['default']      = NULL;                 // Default-Contact

@f0o can answer how other contacts are used (override sysContact? email from users tables?)

**Comment by Ultra2D** [comment]
Oops, I assumed that took a username as value. Should have studied the docs (or code) better.

Other contacts ( syscontact, $config["alert"]["admins"] , $config["alert"]["globals"] ) won't work with LDAP though.
For me, this is good enough.

**Comment by f0o** [comment]
This is true as for the part 'LDAP users wont get alerts'.

If you're fit in PHP+LDAP, feel free to paste me a gist on how to obtain a list of authorized LDAP users and I'll add it to the method that gathers contacts for alerts :)

**Comment by Ultra2D** [comment]
Could you replace the SQL queries with get_userlist() and get_userlevel($username) from the files in html/includes/authentication (which need to be included?)? If so, I think it's only necessary to add getting the email address to get_userlist() in ldap.inc.php . Which in turn probably needs to be flexible, by defining the email address attribute name in the config file(s).

**Comment by f0o** [comment]
that's a good hint, I will have a look at it :)

**Comment by f0o** [comment]
tackling this issue today

**Comment by f0o** [comment]
@Ultra2D this issue isnt easily solved. The current LDAP-authmodule lacks a mapping/gathering of email-addresses.
I cant solve this as I dont have any LDAP at hand.

However, PR #734 makes now use of the authmodule's functions to get userlists and permissions, so once the LDAP-module is fixed it will also fix this issue.

Cheers

**Comment by Ultra2D** [comment]
Gathering the email addresses of LDAP users should be easy. I will take a look at it this week.

**Comment by Ultra2D** [comment]
@f0o is there an easy way to generate an alert to test email delivery?

**Comment by f0o** [comment]
easiest is to create an alert like `devices.status = 1` for one device.

**Comment by Ultra2D** [comment]
I thought https://github.com/librenms/librenms/compare/master...Ultra2D:issue-714 would work, but I don't receive emails as admin, only as `$config['alerts']['email']['default']` or as sysContact. Have to take another look next week.

**Comment by paulgear** [comment]
I thought $config['alerts']['email']['default'] was only used for the old alerting framework - am I wrong @f0o ?

**Comment by f0o** [comment]
@paulgear `$config['alerts']['email']['default']` is also honored by the new system :)

**Comment by f0o** [comment]
@Ultra2D hi, any updates on this? Your patch looks quite logical to me and I'd like to merge this if it works.

**Comment by Ultra2D** [comment]
Sorry, haven't looked at it yet. I probably will need to create a separate instance to see how the notification system works without LDAP.

**Comment by f0o** [comment]
@Ultra2D Any updates?

**Comment by Ultra2D** [comment]
I have tested it again, and it works fine now. Feel free to merge.

**Comment by f0o** [comment]
merged, thanks
