### ISSUE TITLE
Update support for Edge-Core switches (edgecos)

### ISSUE THREAD

**Issue by kamils85** [librenms/librenms#7140]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 1.30-49-g38cb8ab
DB Schema | 201
PHP       | 7.0.15-0ubuntu0.16.10.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.10.1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Would it be possible to update the overview page for Edge-Core devices?

1. Change Hardware to show the platform instead of Edge-Core - example: ECS4120-28F) - it's already under Inventory tab in case this helps 
2. Update Operating System to show current version - example: Edge-Core (R01 1.0.2.26)
.1.0.8802.1.1.2.1.5.4795.1.2.2.0 = STRING: "R01"
.1.0.8802.1.1.2.1.5.4795.1.2.3.0 = STRING: "1.0.2.26"
3. Add Serial Number - example: EC1643000198 - already under Inventory tab

![image](https://user-images.githubusercontent.com/23239006/29208495-a0bb12b8-7e8a-11e7-91d9-8d0e449bca0d.png)

./poller.php -h HOSTNAME -m os -d
https://pastebin.com/ymRUGZ3b

snmpwalk
[edgecos-10.150.50.11.snmpwalk.txt](https://github.com/librenms/librenms/files/1217502/edgecos-10.150.50.11.snmpwalk.txt)

There is also a new MIB with the recent firmware, it may be worth adding/updating it.
[ECS4120-Series_v1.0.2.24.mib.zip](https://github.com/librenms/librenms/files/1217508/ECS4120-Series_v1.0.2.24.mib.zip)

Many thanks :)

**Comment by laf** [comment]
Please try the linked PR.

The OIDs you've provided weren't correct and the MIB seems to be hardware specific so I've refactored the OS polling. Please test and let us know.

**Comment by kamils85** [comment]
Looking good to me.

![image](https://user-images.githubusercontent.com/23239006/29249500-dedfb830-8030-11e7-9f4c-f87c6afb021f.png)

Many thanks.
