### ISSUE TITLE
Graphs not updating after attempting to set polling frequency to 1 minute

### ISSUE THREAD

**Issue by WilliamDEdwards** [librenms/librenms#7148]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
==========================================================
Component | Version
--------- | -------
LibreNMS  | 233f8e83b4e44faa26a980f2ccc9f25e882f917e
DB Schema | 188
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/a92b5e9e
https://p.libren.ms/view/2a21ba8b
https://p.libren.ms/view/15306f01
- [x] Please provide as much detail as possible.
I have attempted to increase the polling frequency from 5 minutes to every 1 minute. In order to faciliate this, I have followed the guide (http://docs.librenms.org/Support/1-Minute-Polling/):
- backed up the /opt/librenms/rrd folder;
- changed the cronjob for `poller-wrapper.py` to every 1 minute;
- changed the RRDTool setup (/settings/sub=external/) for rrd step value 60 and rrd heartbeat value 120;
- converted all rrd files: `./scripts/rrdstep.php -h all`

However, graphs aren't updated anymore now. I have tried to revert all these changes and replacing the rrd folder with the backup, but they are still not updated. The devices are being polled though, I can tell from the `/poll-log/`.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

<img width="1273" alt="schermafbeelding 2017-08-12 om 21 48 27" src="https://user-images.githubusercontent.com/12184311/29244107-01f5890a-7fa8-11e7-87ee-6b357aa70096.png">

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
