### ISSUE TITLE
add akcp sensorProbe2

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#7151]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.30-60-g1e4be3b
DB Schema | 203
PHP       | 5.4.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
add akcp sensorProbe2

includes/definitions/akcp.yaml

```
os: akcp
text: 'AKCP SensorProbe'
type: environment
over:
    - { graph: device_temperature, text: temperature }
discovery:
    - sysDescr:
        - SensorProbe
        - sensorProbe2
        - sensorProbe4
        - sensorProbe8
        - securityProbe
```

- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Thanks, I've submitted a pull request for this.

Whilst we do appreciate reports to add new devices, this is such a simple change that it would have been easier and better if you'd have submitted this directly yourself. We have full docs on how to do this.
