### ISSUE TITLE
Core Parsing not working

### ISSUE THREAD

**Issue by dvmennis** [librenms/librenms#7154]
Hello all,

I have been trying to add port parsing to the "core" heading in LibreNMS. Below is what is in my config.php file

**$config['customers_descr']         = array('PLE');
$config['core_descr']              = array('PLE');**

My issue is that the "customer" port page does show the ports labeled as PLE while the "core" page is blank. What do I need to change to make the "core" page work?

More information about config
hardware: Juniper EX4550
port config:
**set interfaces ge-0/0/15 description "Type | Location | Equipment Type | Customer_Name | IP address | Next Hop Port**"

I had to change the includes/port-descr-parser.inc.php  file line 9 to:
**list($type,$descr) = preg_split('/[\|\[\]\{\}\(\)]/', $this_port['ifAlias']);**
bacily I changed the **:** to **|** so that libre understood what to look for. 

Thanks for your help

------------------------------------------------------------------------------------------------------------------
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

====================================
Component | Version
--------- | -------
LibreNMS  | 1.30-65-gdc41c9d
DB Schema | 203
PHP       | 7.0.21
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  Your local git contains modified files, this could prevent automatic updates.
Modified files:
         includes/definitions/ruckuswireless.yaml
         includes/port-descr-parser.inc.php

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
