### ISSUE TITLE
AKCP device Problems open in web interface

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#7155]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.30-68-gf3d7a44
DB Schema | 203
PHP       | 5.4.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.

suddently the akcp device not work -> it is not possible to open devices wthin librenms web interface 
I need to delete the akcp devices -> the devices have 511152 Interfaces  seen after delete in cmd line :

```
bash-4.2$ ./delhost.php 10.254.103.22
Removed interface 511152 (AKCP)
Removed device 10.254.103.22
```

- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by kristoferus75** [comment]
i thing it is a bug i have post it on community.librenms.org

**Comment by laf** [comment]
If it's a bug, provide a reproducible test case including the information we ask for rather than ignoring it.

I've got test data for akcp and it works fine so please use the support channels.
