### ISSUE TITLE
Database: incorrect column (ports/ifTrunk) error after updating

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#7157]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Hi,

I got this error after updating to the latest version of LibreNMS. See below,
![image](https://user-images.githubusercontent.com/16717388/29312381-4f0bba7a-81b5-11e7-9960-bcf6cc6d27d5.png)

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
