### ISSUE TITLE
graphite receives invalid lines for fields without values

### ISSUE THREAD

**Issue by filippog** [librenms/librenms#7166]
We (Wikimedia Foundation) are testing the librenms to graphite integration and found that certain fields without values can make it to graphite and result in invalid lines received:

```
librenms.asw-b-codfw_mgmt_codfw_wmnet.ports.esi.INNUCASTPKTS  1502879264
librenms.asw-b-codfw_mgmt_codfw_wmnet.ports.esi.OUTUCASTPKTS  1502879264
```

I believe the culprit is [includes/graphite.inc.php:39]( https://github.com/librenms/librenms/blob/1f98bf46a594fcdec6e80a6b1ff755c36a88b20e/includes/graphite.inc.php#L39) this case it would be enough to send a zero if the field has no value?

**Comment by laf** [comment]
From that debug, those values are present aren't they? `1502879264`

**Comment by XioNoX** [comment]
I believe 1502879264 is the timestamp, and there should be another value in between *UCASTPKTS and 1502879264.

**Comment by laf** [comment]
In that case, PRs gladly received :)

**Comment by filippog** [comment]
@laf my PHP isn't the best, PTAL to #7176 !

**Comment by laf** [comment]
Works for me :)

You could have done `$v = empty($v) ?: 0;` as shorthand but this works. Thanks again :D

**Comment by filippog** [comment]
Awesome, thanks @laf for the fast turnaround!
