### ISSUE TITLE
graphite doesn't replace whitespace in measurements and fields

### ISSUE THREAD

**Issue by filippog** [librenms/librenms#7167]
Similarly to #7166 the librenms/graphite integration ends up sending invalid lines, in the form of lines with whitespace in the metric name which isn't allowed, e.g.:

```
librenms.cr1-esams_wikimedia_org.storage.storage.hrstorage./dev/md6, mounted on: /tmp.used 10240 1502879405
librenms.cr1-esams_wikimedia_org.storage.storage.hrstorage./dev/md6, mounted on: /tmp.free 3007948800 1502879405
librenms.cr1-esams_wikimedia_org.storage.storage.hrstorage./dev/md7, mounted on: /mfs.used 64665600 1502879405
librenms.cr1-esams_wikimedia_org.storage.storage.hrstorage./dev/md7, mounted on: /mfs.free 2943293440 1502879405
```

In this case I think the whitespace can be replaced with `_`, similarly to what's done for `|`. What do you think?

**Comment by laf** [comment]
If it's invalid with spaces then yes, seems logical. Are you submitting the pull request to fix this?

**Comment by filippog** [comment]
For sure! See #7173 above

**Comment by laf** [comment]
Thanks for spotting and fixing :)
