### ISSUE TITLE
Juniper QFX 10000 showing fan trays showing down

### ISSUE THREAD

**Issue by papatango71** [librenms/librenms#7168]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `root@nms01-eqch2
[/opt/librenms]# ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.30-67-g1f98bf4
DB Schema | 204
PHP       | 7.0.18-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Database connection successful
[OK]    Database schema correct` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

ptopping@PR02.EQLA1> show chassis fan
      Item                      Status   RPM     Measurement
      FPC 0 Tray 0 Fan 0        OK       5000    Spinning at normal speed
      FPC 0 Tray 0 Fan 1        OK       4400    Spinning at normal speed
      FPC 0 Tray 1 Fan 0        OK       5000    Spinning at normal speed
      FPC 0 Tray 1 Fan 1        OK       4400    Spinning at normal speed
      FPC 0 Tray 2 Fan 0        OK       5000    Spinning at normal speed
      FPC 0 Tray 2 Fan 1        OK       4400    Spinning at normal speed

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
