### ISSUE TITLE
Port Graph history lost when change the master and slave fortigate firewall HA Cluster

### ISSUE THREAD

**Issue by smounives** [librenms/librenms#7169]
Hi,
I have 2 FortiGate 200D Firewall and make then in a HA Cluster, and FW01 is the Master, FW02 is the Slave. 
When I change FW02 to the Master and FW01 to the Slave, every port graph history on the LibreNMS is gone. Is this a bug? Or how can I get the graph history back?

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
