### ISSUE TITLE
Raritan PDU Sensors Problems

### ISSUE THREAD

**Issue by Blorpy** [librenms/librenms#7171]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.30-69-g5dfff22
DB Schema | 204
PHP       | 5.4.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.5.6
SNMP      | NET-SNMP 5.7.2
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Have some Raritan PXE PDUs that don't seem to be getting all the appropriate information pulled from them. Frequency always shows 0, and voltage doesn't even show up at all. Current and power are correct. 

Discovery: https://p.libren.ms/view/feb1d2bb
Poller: https://p.libren.ms/view/c18130e3
snmpwalk: https://p.libren.ms/view/67ef5f2f

**Comment by laf** [comment]
The raritan mib uses data from ` .1.3.6.1.4.1.13742.6.3.3.3` which your snmpwalk doesn't include.

If you can provide another walk: `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME  .1.3.6.1.4.1.13742.6`

Once that's been provided, we can re-open this and take another look.

**Comment by Blorpy** [comment]
As requested: https://p.libren.ms/view/df4e775a

**Comment by laf** [comment]
This does look like your device isn't sending the data back we expect to see.

If you can find the OIDs of the data you expect to see we can take a further look.

**Comment by Blorpy** [comment]
Inlet voltage appears to be in .1.3.6.1.4.1.13742.6.5.2.3.1.4.1.1.4, or .1.3.6.1.4.1.13742.6.5.2.3.1.6.1.1.4 if you want signed. 

Inlet Watts = .1.3.6.1.4.1.13742.6.5.2.3.1.4.1.1.5
Inlet VA = .1.3.6.1.4.1.13742.6.5.2.3.1.4.1.1.6
Inlet Power factor = .1.3.6.1.4.1.13742.6.5.2.3.1.4.1.1.7

Frequency doesn't seem to be reported by these units, so I guess thats off the table.

**Comment by laf** [comment]
Please test the linked PR above, this should help.

**Comment by Blorpy** [comment]
Voltage being reported is the same as watts being reported, I think you're polling .5 for the OID when voltage is .4. 

Frequency still shows up even when its 0, I'm not sure if the intent of the PR was to stop this or not.

**Comment by laf** [comment]
Thanks, fixed voltage.

The check for me shows frequency not being added if it was 0 before (it was never actually 0). You'd need to pastebin `./discovery.php -h HOSTNAME -d -m sensors` to see further.

**Comment by Blorpy** [comment]
Heres the output of the sensor discovery: https://p.libren.ms/view/16b77f6f

Voltage seems happy now, its just the weirdness with graphing frequency when its seemingly non-existent.

**Comment by laf** [comment]
Are you sure it's applied the patch ok, that is the output I see but the sensor isn't discovered.

Run: `grep '_numeric($inlet_freque' includes/discovery/sensors/frequency/raritan.inc.php`

If you get no output the patch hasn't applied.

**Comment by Blorpy** [comment]
That returns
<code>if (is_numeric($inlet_frequency)) {</code>

**Comment by laf** [comment]
Very odd. I don't see why that would happen now as inlet_frequency isn't numeric at that point.

**Comment by laf** [comment]
You could add a var_dump($inlet_frequency); above that line in the file and see what is shown in debug

**Comment by Blorpy** [comment]
Shows <code>int(0)</code>

**Comment by laf** [comment]
Can you pastebin the entire frequency file pls

**Comment by Blorpy** [comment]
I deleted the device, RRDs, then re-added it and frequency isn't discovered anymore, and no longer is int(0) shown in the debug output. Not sure what this did to fix it, but looks good now. 

raritan.inc.php: https://p.libren.ms/view/7a180950

**Comment by laf** [comment]
Shouldn't have made any difference :(
