### ISSUE TITLE
Server Tech PDU Sensors Not Detected

### ISSUE THREAD

**Issue by Blorpy** [librenms/librenms#7172]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS | 1.30-69-g5dfff22
DB Schema | 204
PHP | 5.4.16
MySQL | 5.5.52-MariaDB
RRDTool | 1.5.6
SNMP | NET-SNMP 5.7.2
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

I have some server technologies PRO2 PDUs that aren't getting any voltage, current, frequency, or power (watts) sensors shown. These PDUs do support per inlet sensing, but the main concern is just overall inlet sensors for me. 

The devices do show up in librenms as server technologies PDUs, but only traffic is shown. 

Discovery: https://p.libren.ms/view/fe7f9ed0
Poller: https://p.libren.ms/view/f553abd8
snmpwalk: https://p.libren.ms/view/a84c8e81

**Comment by laf** [comment]
Same issue as the last one:

Please provide the output of `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME  .1.3.6.1.4.1.1718.`

Once provided, we can re-open.

**Comment by Blorpy** [comment]
As requested: https://p.libren.ms/view/0d7ff99c

**Comment by laf** [comment]
PR submitted if you fancy testing.

**Comment by Blorpy** [comment]
Looks good, power and frequency appear to be properly reported.
