### ISSUE TITLE
Unable to parse at line 7 if add new device

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#7174]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Version info:
Commit SHA: 96c139ffe2eb7dc2fc75aa18b32d23a085f5fec3
Commit Date: 1502954829
DB Schema: 204
PHP: 5.4.16
MySQL: 5.5.52-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
not possible because device cannot be added
- [x ] Please provide as much detail as possible.
LibreNMS Discovery

- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
```
Fatal error: Uncaught exception 'Symfony\Component\Yaml\Exception\ParseException' with message 'Unable to parse at line 7 (near "<<<<<<< HEAD").' in /opt/librenms/lib/influxdb-php/vendor/symfony/yaml/Parser.php:285
Stack trace:
#0 /opt/librenms/lib/influxdb-php/vendor/symfony/yaml/Yaml.php(72): Symfony\Component\Yaml\Parser->parse('os: akcp?text: ...', false, false, false)
#1 /opt/librenms/includes/common.php(1637): Symfony\Component\Yaml\Yaml::parse('os: akcp?text: ...')
#2 /opt/librenms/includes/common.php(1660): load_all_os(false, false)
#3 /opt/librenms/discovery.php(117): update_os_cache()
#4 {main} thrown in /opt/librenms/lib/influxdb-php/vendor/symfony/yaml/Parser.php on line 285
```
Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by laf** [comment]
You need to reset your git install. Can you PLEASE use IRC or the community site for future help, I have asked you to do this before.
