### ISSUE TITLE
[FEATURE REQUEST] Add support for Logstash

### ISSUE THREAD

**Issue by hron84** [librenms/librenms#7177]
I'd like to see LogStash compatibility not only Graylog2. While Graylog is a very good log management software, Logstash is better at some aspects. We planning to introduce Logstash and LibreNMS too and I'd be happy if they could be best friends.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by hron84** [comment]
@laf why you accept only new device request from GitHub Issues and not new **feature** requests? Logstash is a popular central logging framework and it would be good if LibreNMS could support it.

**Comment by laf** [comment]
This is the choice of the project. It's detailed in the information when you create an issue.

If you link to the FAQ that says to raise feature requests here then we can update it. However no one has said we don't accept feature requests, we do, they need to be posted on the community site though.

**Comment by hron84** [comment]
@laf okay, but your FAQ does not state explicitly you do not accept FRs. On GitHub, there is a common sense that opensource projects accept both issues and feature requests from the community via the issue tracker. So, if your project choose to be different, you should state it in your FAQ to prevent misposting. 

Forums is often favored less by other developers since most project developers are reading and solving issues in GH issue tracker and do not have enough time to follow forums closely. I were in contact with opensource devs who are very active on GH but post once or twice per week to the forum.

**Comment by laf** [comment]
> @laf okay, but your FAQ does not state explicitly you do not accept FRs. On GitHub, there is a common sense that opensource projects accept both issues and feature requests from the community via the issue tracker. So, if your project choose to be different, you should state it in your FAQ to prevent misposting.

But it's stated already quite clearly in the text when you've gone to create the issue:

`If you have a feature request please post this on our community site.`

> Forums is often favored less by other developers since most project developers are reading and solving issues in GH issue tracker and do not have enough time to follow forums closely. I were in contact with opensource devs who are very active on GH but post once or twice per week to the forum. It's not because their intention, just... you know, life stuffs.

And that is the choice they make but that doesn't make it a default or a requirement for all projects. We don't accept feature requests here, I'm sorry you don't agree with it but it's not really up for debate. 

You can see that I'm active on the community site as are some of the other devs.
