### ISSUE TITLE
Config option bad_iftype doesn't ignore interfaces

### ISSUE THREAD

**Issue by tobiasa1** [librenms/librenms#718]
I have added the following lines to my config.php:

```
// Ignore PPP interfaces
$config['bad_iftype'][] = "ppp";
```

Expected behaviour is that all ppp interfaces should be completely ignored and not added to LibreNMS.

However, in my event log I see lines for each new ppp interface being created on my Debian servers:

```
3rd Apr 2015 03:45:05	b1.s1		ifDescr: -> ppp17
2nd Apr 2015 19:50:06	b2.s1		ifDescr: -> ppp26
2nd Apr 2015 19:50:06	b2.s1		ifDescr: -> ppp39
```

The ports seem to get deleted imminently and listed under Deleted Ports.

Please let me know if you need any further information to troubleshoot this.

**Comment by laf** [comment]
I've just done some quick testing so this isn't conclusive but for me:

If a add an ifType to $config['bad_iftype'][] and run discovery and poll then the ports that match get marked as deleted as they existed already.

If I then delete those ports from the db and do another discovery and poll then they get skipped as expected.

Are you seeing new devices have ports marked as bad_iftype added to the db still but marked as deleted? Is it possible for you to add one of the devices fresh and run these manually:

./discovery.php -h <DEVICE>  -d -m ports
./poller.php -h <DEVICE>  -d -m ports

And paste the output onto pastebing?

**Comment by f0o** [comment]
Any update @tobiasa1 ?

**Comment by tobiasa1** [comment]
Hello,

Sorry about the delay.

I'll try to get some output during the weekend. Meanwhile I am using the config option bad_if to match and ignore ppp[0-9]+ which works fine.

Since the issue is only affecting a few interfaces per machine (each machine has around 250-300 ppp interfaces), I think it must be caused by LibreNMS not setting correct ifType for those interfaces, and when it does, it has to delete them afterwards.

I'll get back soon when I've some output for you guys. Thanks.

**Comment by laf** [comment]
Thanks @tobiasa1. For now I'll close this issue and you can re-open when you get to it.
