### ISSUE TITLE
Ubuntu 16.04.3 - LibreNMS Master - Install Errors

### ISSUE THREAD

**Issue by scrublullz** [librenms/librenms#7181]
Good Evening,

I just performed a fresh installation of LibreNMS on Ubuntu 16.04. I followed the Ubuntu + NGinx. 

The first issue I ran into was the SNMP installation on my computer. I was getting the fun "cannot find modules" from SNMP during the database load on the web UI.  I have deployed LibreNMS on Azure and never received these errors previously. I used the standard Ubuntu ISO on this installation into local hardware. To fix these errors, I had to run `sudo download-mibs` to get everything setup. This may be a comment to put in the installation guide if others experience errors.

After the install, I ran `validate.php` and received a bunch of errors (below).
Example: 
```
[FAIL]  Database: missing column (applications/app_state_prev)
[FAIL]  Database: missing column (applications/discovered)
[FAIL]  Database: missing column (applications/timestamp)
```
Full log: hXXps://pastebin[.]com/A3vh2FPi

In order to fix these errors, I had to run the `daily.sh` to rebuild the database and everything worked great from there.

Thank you guys many times over for LibreNMS. It has helped me manage large installations, change resources on numerous VMs to lower or higher requirements and made management easy.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
