### ISSUE TITLE
Cisco ONS sensor under limit alerts as of 08/14

### ISSUE THREAD

**Issue by allano337** [librenms/librenms#7197]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.30.01-84-gb132686
DB Schema | 204
PHP       | 5.4.16
MySQL     | 10.0.28-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.

It seems that on 08/14/2017 both our Cisco ONS's now have an alert which wasn't there previously. These devices are in different cities and one would think something in librenms changed to affect this. Please look into the issue.
Under limit alert on both devices are exactly the same?
#1: sensor_id => '4736', sensor_oid => '.1.3.6.1.4.1.3607.2.80.10.1.30.1', sensor_descr => 'CHASSIS_454 - POWER BUS A'
#2: sensor_id => '4737', sensor_oid => '.1.3.6.1.4.1.3607.2.80.10.1.30.2', sensor_descr => '15454-SA-HD - POWER BUS B'

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by allano337** [comment]
so why it's this a BUG in the software???

**Comment by allano337** [comment]
Would like to know why it’s not a Bug in the code that was updated??

Aalln O.

**Comment by allano337** [comment]
Just so you know the values in the base code need to change, guess that’s not  a bug.

You can read about it on the librenms community site!

Allan O
