### ISSUE TITLE
Tycon TPDIN-SC48-20

### ISSUE THREAD

**Issue by jeffee1** [librenms/librenms#7204]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 1.30.01-106-gd7fc198
DB Schema | 204
PHP       | 5.5.9-1ubuntu4.22
MySQL     | 5.5.57-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

I'm having an issue with this device.  The Tycon TPDIN-SC48-20, It's discovered but the values are off.  
     Temp 1 looks like it should be battery temp, and the decimal position is off shown as 2.41C should be 
     24.1C
     Temp 2 looks like it should be battery status and should be 26%, currently shows 2.6C
     Voltage 1 and 2 are shown as 2.4 volts.  I'm assuming this is POE status and that should be 24 volts?
     Current 1 looks like it should be Load Watts but is represented as 0.6A which should be 6 Watts
     Current 2 looks like it should be Battery volts but is represented as 4.72A which should be 47.2V

I can't find that this has been reported and may be related to the fact that the TPDIN and TPDIN-SC48-20 are slightly different devices.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.
