### ISSUE TITLE
Procurve Router 7102dl and  ProCurve Access Point 530 NA J8986A recognizes as a generic device

### ISSUE THREAD

**Issue by crc540** [librenms/librenms#7218]
LibreNMS recognizes these devices as a generic device and not a hp network device.

![untitled1](https://user-images.githubusercontent.com/31289840/29647164-c8caa6ae-8855-11e7-8ab6-c4617869d9bd.png)

![untitled](https://user-images.githubusercontent.com/31289840/29646907-415a418a-8854-11e7-8047-d4a576557954.png)        
Component | Version
--------- | -------
LibreNMS  | 1.30.01-100-g30c1b79
DB Schema | 204
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================
[OK]    Database connection successful
[OK]    Database schema correct

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by crc540** [comment]
https://p.libren.ms/view/5a695e5a
https://p.libren.ms/view/e2326e56
https://p.libren.ms/view/0b21734f#L39  

I have gave you the info for one I have about 15 of the exact device having the same problem

**Comment by kkrumm1** [comment]
how old is that HP Procurve AP 530?

**Comment by crc540** [comment]
Kevin around 2008. To me my biggest worry is for the Procurve Router 7102dl. I only have one AP530. Thanks for all your help. And if you need more information just let me know

**Comment by kkrumm1** [comment]
That AP brings back memories :)

**Comment by crc540** [comment]
Good or bad

**Comment by kkrumm1** [comment]
It was OK.. it was in my early days in networking.

**Comment by crc540** [comment]
Well that is good then

**Comment by kkrumm1** [comment]
Have missed around with the new Aruba AP's yet?

**Comment by crc540** [comment]
More of a ruckus or xirrus type of guy. But i did play with so arubas before hp took a hold of them

**Comment by laf** [comment]
Detection support has been submitted, if you need more then we will need the relevant mibs for this device.

**Comment by crc540** [comment]
What does this mean laf

**Comment by laf** [comment]
So only basic detection is done this includes ports but nothing else. HP will supply a mib that we can use to reference more data.

**Comment by crc540** [comment]
So I can get you that. Here they are I hope this helps. If you need anything else please let me know. Thanks again laf
[hpicfoid.zip](https://github.com/librenms/librenms/files/1275542/hpicfoid.zip)
[AP530-MIBs-WA-01-18-8-4-06.zip](https://github.com/librenms/librenms/files/1275543/AP530-MIBs-WA-01-18-8-4-06.zip)
[J06_03-Mibs.zip](https://github.com/librenms/librenms/files/1275544/J06_03-Mibs.zip)

**Comment by laf** [comment]
Thanks, only been able to add status of the device and serial / model.

**Comment by crc540** [comment]
Thank you laf

**Comment by crc540** [comment]
So it be in the daily update or do i need to do something special

**Comment by laf** [comment]
Only after it's merged. You can test it from the linked pull request above.

**Comment by crc540** [comment]
I get this error laf 
./scripts/github-apply 7286
<stdin>:153: space before tab in indent.
                     "Hewlett Packard Company
<stdin>:158: space before tab in indent.
                        "This MIB contains device information, contact information, and
<stdin>:366: space before tab in indent.
                SYNTAX      INTEGER {
<stdin>:369: space before tab in indent.
                MAX-ACCESS  read-write
<stdin>:370: space before tab in indent.
                STATUS      current
Checking patch includes/definitions/procurve-wa.yaml...
Checking patch tests/snmpsim/procurve-wa.snmprec...
Checking patch includes/definitions/discovery/procurve-wa.yaml...
Checking patch includes/polling/os/procurve-wa.inc.php...
Checking patch mibs/hp/HP-ICF-WAN-UNIT...
Applied patch includes/definitions/procurve-wa.yaml cleanly.
Applied patch tests/snmpsim/procurve-wa.snmprec cleanly.
Applied patch includes/definitions/discovery/procurve-wa.yaml cleanly.
Applied patch includes/polling/os/procurve-wa.inc.php cleanly.
Applied patch mibs/hp/HP-ICF-WAN-UNIT cleanly.
warning: squelched 22 whitespace errors
warning: 27 lines add whitespace errors.

**Comment by crc540** [comment]
Once I did the update the device have moved from generic to a white blank under the ALL OSes
![untitled](https://user-images.githubusercontent.com/31289840/30121053-8d6eb886-92f8-11e7-81f9-64af09321806.png)

**Comment by laf** [comment]
I'm not sure what you mean by that, works fine using the test data you've provided:

![image](https://user-images.githubusercontent.com/3941142/30129208-23c4545a-933d-11e7-81b5-e0c525b6b70a.png)

I expect it's possibly the mib which hasn't applied on the test.

**Comment by crc540** [comment]
laf when I select the All OSes dropbox I get this and the devices are
![untitled123](https://user-images.githubusercontent.com/31289840/30129399-c90ae408-9313-11e7-8356-6655f7c68e7e.png)
 listed in the blank section between HP-ProCurve and the SonicWall

**Comment by laf** [comment]
I don't get that happening, it might be easier to wait for a merge.

**Comment by crc540** [comment]
Will do and Thank you very much for all your help.

**Comment by laf** [comment]
I've closed the pull request associated with this as has been pointed out to me. You've supplied data for a procurve router and asked for that + wireless access point support.

Please create an issue for each type you need and provide the full data for both.

**Comment by crc540** [comment]
I just need the one for the procurve router please reopen the case please
