### ISSUE TITLE
VLANs register absent on Cisco NX OS Devices

### ISSUE THREAD

**Issue by setiseta** [librenms/librenms#7233]
Created as written in irc chat.
The patch you gave me fixed it.
https://p.libren.ms/view/raw/bc622b2d

**Comment by setiseta** [comment]
the register is here again, and filled with data.
but it seems that data won't get updated anymore.
I have renamed a VLAN hours ago, started rediscover of the device, and the debug command on the shell.
but its still the old name of the VLAN.

**Comment by murrant** [comment]
FYI, discovery is only run every 6hrs by default.

**Comment by setiseta** [comment]
i know, but isn't it running "now" if i go to the edit section of a device an click "rediscover device".
Or if i run ./discovery.php  -m vlans  -h HOSTNAME -d

**Comment by murrant** [comment]
Then you should probably post the debug output of that. Thanks.

**Comment by laf** [comment]
@setiseta Any chance of the debug output asap as we will be doing a small release to fix some bugs, if we don't get any data to test this we can't fix and it will end up waiting until next month :(

**Comment by laf** [comment]
Actually, I'm fairly certain the patch I gave is all that's needed. Nothing else has changed outside of the junos discovery of significance.

**Comment by setiseta** [comment]
this is actual discovery:
https://pastebin.com/kT4WykJW

**Comment by laf** [comment]
You got a device timeout there so the vlans are removed as we can't get the data we need.

**Comment by setiseta** [comment]
ok sorry, have not seen that there was a timeout.
thx for fixing the register tab.
