### ISSUE TITLE
Geist Watchdog 15 temperature graphing incorrect data

### ISSUE THREAD

**Issue by GordSpence** [librenms/librenms#7236]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 1.31
DB Schema | 205
PHP       | 5.3.3
MySQL     | 5.1.73
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.5

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

After the monthly stable update was applied overnight, I've found that my Geist WD-15 temperature is reporting temperature incorrectly in LibreNMS. The Geist WebGUI and snmp are consistent with eachother and line up with other temperature sensors in the room. I suspect it's related to this commit (https://github.com/librenms/librenms/pull/7143) since that's the only change to the geist devices that I can see.

![screen shot 2017-08-28 at 11 44 46 am](https://user-images.githubusercontent.com/8779815/29781183-5ab4a66c-8be6-11e7-99f8-74e702b01672.png)

Here's an example from a bulkwalk: https://gist.github.com/GordSpence/da1297ba076d22e876f8554ad2d84177

I thought at first that the temperature graph might be grabbing from the dewpoint value (.1.3.6.1.4.1.21239.5.1.2.1.7.1), but the values don't seem to line up as far as I can tell, so I can only imagine that the Fahrenheit conversion is unintentionally messing with my Celsius values.

**Comment by murrant** [comment]
I can't really investigate this since you haven't provided the data asked for: http://docs.librenms.org/Support/FAQ/#faq20

Thanks.

**Comment by GordSpence** [comment]
Woops - my apologies.

https://gist.github.com/GordSpence/d6f9b586ece7bc53939ed32c96efb17e
https://gist.github.com/GordSpence/0263c542cf05dbcf2defa78e5e09ce92
https://gist.github.com/GordSpence/038baba711fea4d34d6b276bf213497c

**Comment by murrant** [comment]
@GordSpence can you please test #7239 ?

**Comment by GordSpence** [comment]
@murrant - looks good: I'm getting sensible data now. It renamed the sensor by the looks of things so I lost historical data, but that's not too big a deal for me.

**Comment by GordSpence** [comment]
(thanks for the fix!)

**Comment by murrant** [comment]
The name is based on what you set in the device config I believe.

You should have had a duplicate temperature sensor before.

**Comment by GordSpence** [comment]
Yeah - a duplicate (the current one) appeared while I was running the validate/discover/poller scripts to get the data for this issue. When I applied the fix it dropped the original one from what I can see here. Not a problem for me, but I'm guessing other folks will have the same thing happen when they update.

**Comment by murrant** [comment]
Yeah, thanks.
