### ISSUE TITLE
Vlan's don't get updated

### ISSUE THREAD

**Issue by setiseta** [librenms/librenms#7247]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the ====================================
Component | Version
--------- | -------
LibreNMS  | 1.31.01
DB Schema | 205
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 5.6.36
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
rename a vlan, it never gets updated in the VLAN tab of a device.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
@setiseta Can you test PR #7348

**Comment by setiseta** [comment]
yes i replaced the files, and run a discovery. now they are updated.
Thank you.
