### ISSUE TITLE
New Device - SAF Integra (non W)

### ISSUE THREAD

**Issue by kmpanilla** [librenms/librenms#7249]
SAF has another model in the Integra line-up. It's not the W line.. just called simply the "Integra" as far as I can tell.  I'd like to submit the following so someone can add it to the available devices.

SAF Integra
DISCOVERY: 	https://p.libren.ms/view/1b74f454
POLLER:    	https://p.libren.ms/view/1d017251
SNMPBULKWALK:   https://p.libren.ms/view/e5d4c2a5
MIBS:
 SAF-INTEGRAB:   https://p.libren.ms/view/9fdc752b
 SAF-INTEGRA:    https://p.libren.ms/view/abb7a6db
 SAF-ENTERPRISE: https://p.libren.ms/view/254291e8

Proposed OS Name: SAF Integra

There are three vendor supplied MIBs.  The SAF-INTEGRA and SAF-ENTERPRISE are also required for the SAF-INTEGRAW host which I also requested.

Please let me know if I can provide a live device for testing against, or any other information.

Thanks.

**Comment by laf** [comment]
I'm not sure it's worth splitting these out. I'll add the support to the other PR based on the W model.

**Comment by laf** [comment]
Change of plan, I split them out but in the same PR.
