### ISSUE TITLE
Add support for Cisco SG550XG series

### ISSUE THREAD

**Issue by doc-nl** [librenms/librenms#7250]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.31.01
DB Schema | 205
PHP       | 7.0.19-1
MySQL     | 10.1.26-MariaDB-0+deb9u1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.

sg550xg-8f8t not recognized as Cisco device

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by doc-nl** [comment]
discovery https://pastebin.com/whFxRez8
poller https://pastebin.com/BYTR81Z9

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by doc-nl** [comment]
I did run all scripts, but got errors from the pbin.sh script

**Comment by laf** [comment]
We need the snmpwalk, that's actually the most important thing.

Use another pastebin service if you need to (or github gist)

**Comment by doc-nl** [comment]
https://gist.github.com/doc-nl/995304d3ee55b38d208cd7b7f3480663 here it is

**Comment by doc-nl** [comment]
MIB is downloadable @ https://software.cisco.com/download/release.html?mdfid=286282353&flowid=77045&softwareid=283415684&release=2.3.0.130&relind=AVAILABLE&rellifecycle=&reltype=latest (no account needed)

**Comment by laf** [comment]
Unfortunately the output doesn't actually even contain sysObjectID or sysDescr :(

please pastebin the output of: `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .1.3.6.1.2.1.1.`

**Comment by laf** [comment]
Can you test #7305 - this might fix things for you.

**Comment by doc-nl** [comment]
No #7305 didn't help

The snmpbulkwalk request gives:

.1.3.6.1.2.1.1.1.0 = STRING: "SG550XG-8F8T 16-Port 10G Stackable Managed Switch"
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.9.6.1.90.16.9
.1.3.6.1.2.1.1.3.0 = Timeticks: (152250604) 17 days, 14:55:06.04
.1.3.6.1.2.1.1.4.0 = STRING: "TIB"
.1.3.6.1.2.1.1.5.0 = STRING: "dcn-swip01"
.1.3.6.1.2.1.1.6.0 = STRING: "Datacenter"
.1.3.6.1.2.1.1.7.0 = INTEGER: 6
.1.3.6.1.2.1.1.8.0 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.1.9.1.2.1 = OID: .1.3.6.1.4.1.89.73
.1.3.6.1.2.1.1.9.1.3.1 = STRING: "RS capabilities"
.1.3.6.1.2.1.1.9.1.4.1 = Timeticks: (0) 0:00:00.00

Adding - .1.3.6.1.4.1.9.6.1.90 to includes/definitions/ciscosb.yaml did fix it :)

It does show way too much ten gb interfaces. Only te1/0/1-te1/0/16 are physical there but it's showing te1/0/17-te1/0/48, te2/0/1-te2/0/48 until te8/0/1-te8/0/48

**Comment by doc-nl** [comment]
According to: https://www.cisco.com/c/dam/en/us/td/docs/net_mgmt/prime/infrastructure/3-2/supported/devices/PI32-Supported-Device-List.xlsx

We should add the following OID to that file to support all current Cisco SB switches
 .1.3.6.1.4.1.9.6.1.80 (already there)
 .1.3.6.1.4.1.9.6.1.81 (already there)
 .1.3.6.1.4.1.9.6.1.85 (already there)
 .1.3.6.1.4.1.9.6.1.86
 .1.3.6.1.4.1.9.6.1.90
 .1.3.6.1.4.1.9.6.1.91 
 .1.3.6.1.4.1.9.6.1.95 (already there)
 .1.3.6.1.4.1.9.6.1.96

Stangely enough  .1.3.6.1.4.1.9.6.1.94 from #7305 is not in the file
