### ISSUE TITLE
New Device - A10 Networks ADC

### ISSUE THREAD

**Issue by papatango71** [librenms/librenms#7251]
I have several A10 Networks ADCs that I would like to have LibreNMS monitor.  Below is all the information for them.  If anything is missing please let me know.

root@nms01-eqch2
[/opt/librenms]# ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.31.01
DB Schema | 205
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Database connection successful
[OK]    Database schema correct

DISCOVERY :: https://p.libren.ms/view/e2d75ae2
POLLER :: https://p.libren.ms/view/bdfb408f
SNMPBULKWALK :: https://p.libren.ms/view/5c0ccd8d
MIBS ::
 A10-COMMON-MIB.txt :: https://p.libren.ms/view/a23859c9
 A10-AX-NOTIFICATIONS-V2C.txt :: https://p.libren.ms/view/caad0c82
 A10-AX-MIB.txt :: https://p.libren.ms/view/87c80ce0
 
Please let me know if I can provide a live device for testing against, or any other information.

Thanks.

-Patrick

**Comment by laf** [comment]
The snmpwalk info has nothing in it :(

**Comment by papatango71** [comment]
@laf .... my apologies for the blank snmpwalk.  When I try and run the SNMPBULK command from the Libre server is blows up.

root@nms01-eqch2
[/opt/librenms]# snmpbulkwalk -OUneb -v2c -c R1l3yKa1 10.104.2.28 .  | ./pbin.sh
Paste endpoint: https://p.libren.ms/api/create
title:
name: root
private: 1
expire: 0
	Error: Missing paste text

When I dump the snmpbulkwalk to a file and try and create a link from https://p.libren.ms/ it hands and then comes back with a blank screen.  The snmpbulkwalk for the A10 ADC produces a 17MB file.  I have attached it to this request.  Hopefully this work.
[snmpwalk.txt](https://github.com/librenms/librenms/files/1282948/snmpwalk.txt)

**Comment by laf** [comment]
Question on this, would you want the CPU usage broken down in to cores/cpus as the data you've given us returns 32 values for cpu usage.

It also has an average which we can use, what do you think, all cores or just the average?

**Comment by papatango71** [comment]
@laf we would want to see all the cores broken down.  reason for that is we have seen when a core gets pegged at 100% it doesn't move the average CPU needle to alert that there is an issue.

Thank you.

**Comment by laf** [comment]
That's fine. Thanks for getting back to me.

**Comment by laf** [comment]
PR submitted, please test.

**Comment by papatango71** [comment]
@laf   Checking the system stats now...  So far so good.  Do you think you will be able to add in the SLB component with real server & VIP states and statistics..??

**Comment by laf** [comment]
@papatango71 We have no base support for that so you'll need to create a feature request on the community site.
