### ISSUE TITLE
uidnumber field required for LDAP auth

### ISSUE THREAD

**Issue by hex2a** [librenms/librenms#7256]
- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)

For LDAP authentication, the attribute `uidnumber` is required. (hardcoded eg in `html/includes/authentication/ldap-authorization.inc.php`)
https://github.com/librenms/librenms/blob/20b08cf595925a64a62c358f0c94128ea0933ad4/html/includes/authentication/ldap-authorization.inc.php#L201
https://github.com/librenms/librenms/blob/20b08cf595925a64a62c358f0c94128ea0933ad4/html/includes/authentication/ldap-authorization.inc.php#L230

If this attribute is not set, login fails with a "Invalid credentials" login error, this seems to have occured the first time when upgrading 1.27 > 1.28.

Maybe there is a better way to save the associated id?

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by hex2a** [comment]
Hello,
please reopen this issue as bug report.

**Comment by laf** [comment]
Patch https://p.libren.ms/view/raw/d6e8a73b

**Comment by hex2a** [comment]
Patch is working, thanks

**Comment by hex2a** [comment]
@laf will this patch be included in the next release?
