### ISSUE TITLE
New Device - Toshiba RemotEye4

### ISSUE THREAD

**Issue by kate66** [librenms/librenms#7258]
- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.31.02-3-g4683736
DB Schema | 205
PHP       | 5.5.9-1ubuntu4.22
MySQL     | 5.5.57-MariaDB-1ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/61ce2442
https://p.libren.ms/view/673a733b
https://p.libren.ms/view/00f7a224

To download documentation visit https://www.toshiba.com/tic/tools-resources/resource-library (Uninterruptible Power Systems -> RemotEye 4 -> Download whatever you choose, including MIBs)
The website ONLY authenticates off of an email address, so no need to create a full account or to even validate your email address.

**Comment by laf** [comment]
Submitting a PR but do these values look right as the MIB doesn't say what value the info is in:

![image](https://user-images.githubusercontent.com/3941142/30243947-183c008a-95ac-11e7-9ea2-9e54fb394f4f.png)

PR submitted, feel free to test.

**Comment by kate66** [comment]
The amps look wrong, They look *10. The frequency should also be 60Hz. Volts look accurate.

**Comment by laf** [comment]
Sorry that was an old screenshot, those values are as you would expect to see.
