### ISSUE TITLE
device: Watchdog 100 not showing sensors

### ISSUE THREAD

**Issue by kkrumm1** [librenms/librenms#7266]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the 
`====================================
Component | Version
--------- | -------
LibreNMS  | 1.31.02-6-g6914666
DB Schema | 205
PHP       | 7.0.19
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================
[OK]    Database connection successful
[OK]    Database schema correct
` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Watchdog 100 no longer discovering Sensors for Temp and Humidity and Voltage 

Discovery: https://gist.github.com/kkrumm1/aa2f56bf53b420f7fb9a81af37258096#file-watchdog-100-discovery
Poller: https://gist.github.com/kkrumm1/17052d65b403b3ccb8947b12b429839e#file-watchdog-100-poller
SNMP Walk: https://gist.github.com/kkrumm1/01e534282df713a9fae898b0e6305f0c#file-watchdog-100-snmp-walk

**Comment by laf** [comment]
This device isn't reporting any data back via snmp:

`.1.3.6.1.4.1.21239.5.1 = No more variables left in this MIB View (It is past the end of the MIB tree)`

It should continue past that. You can try running snmpwalk rather than snmpbulkwalk to see if it helps. Or run it with `.1.3.6.1.4.1.21239.5.` instead of `.`

**Comment by kkrumm1** [comment]
https://pastebin.com/GbjPsCHq

this is all im getting back...

**Comment by kkrumm1** [comment]
Resolved after updating to the Aug 2017 firmware update.
