### ISSUE TITLE
New Device - DPS Telecom Netguardian

### ISSUE THREAD

**Issue by taking-care-of-business** [librenms/librenms#7272]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Looking to add DPSTelecom Netguardian units, specifically to monitor environmental statistics (temp, power), alarming, etc.

Unit overview: https://www.dpstele.com/rtu/snmpv3/netguardian/864a/index.php?l=44300001 

Discovery Output: https://p.libren.ms/view/952f0880
Poller Output: https://p.libren.ms/view/7858310a
SNMPWalk Output: https://p.libren.ms/view/5c2291b9

**Comment by taking-care-of-business** [comment]
Attached MIBs:
[DPS_MIBS.zip](https://github.com/librenms/librenms/files/1267103/DPS_MIBS.zip)


Snippet for the 864 G5 unit:


> All devices require DPS_V41.MIB.  Extra needed MIBS detailed below:

....

> -G4/G5 based (DPS_v41v2.mib,  NGD_G45.mib, NGD_G45v2.mib, NGX_G39.mib, NGX_G39v2.mib)
>	NetGuardian 216F
>	NetGuardian 864 G5 
>	NetGuardian G4 
>	NetGuardian G5 
>	NetGuardian 420
>	NetMediator TNT G5

**Comment by laf** [comment]
Just an FYI that this snmp output contains now data in the ` .1.3.6.1.4.1.2682.` which is the OID for this device. You can try re-running the snmpbulkwalk command but use ` .1.3.6.1.4.1.2682.` rather than `.`

**Comment by taking-care-of-business** [comment]
I hope I am typing the command correctly, that said, nothing helpful is coming out unfortunately:


```
-bash-4.2$ snmpbulkwalk -OUneb -v2c -c dps_public hostname-rtu .1.3.6.1.4.1.2682.
.1.3.6.1.4.1.2682.: Unknown Object Identifier (Sub-id not found: enterprises -> )

-bash-4.2$ snmpbulkwalk -OUneb -v2c -c dps_public hostname-rtu 1.3.6.1.4.1.2682.
1.3.6.1.4.1.2682.: Unknown Object Identifier (Sub-id not found: enterprises -> )

-bash-4.2$ snmpbulkwalk -OUneb -v2c -c dps_public hostname-rtu .1.3.6.1.4.1.2682
-bash-4.2$  
```

**Comment by laf** [comment]
Then you'll need to take it up with the manufacturer as that's the starting OID they use for data yet don't return any.

**Comment by laf** [comment]
PR submitted, I've added support for the OIDs in the MIB, been unable to test if they work ok though.

**Comment by taking-care-of-business** [comment]
Patch applied, and I agree with you. I will need to speak to the vendor/investigate further. The SNMP options/configuration on this device is straight forward.
May take some time, but I will go back to this ticket when I have something useful to report.

Thanks!

**Comment by taking-care-of-business** [comment]
Some update: the firmware on the device I used is old, and there appears to be a fix for " linux snmpwalk " output issues in a later releases of the firmware. I am thinking that this could be our problem here.

**Comment by laf** [comment]
Update the firmware and give it a test then I guess.

**Comment by taking-care-of-business** [comment]
Updated firmware to the latest one. Here are the latest discovery/polling/snmpwalk outputs:

Discovery: https://p.libren.ms/view/cc5d1ea7
Polling: ** see attached -- 5MB text file **
SNMPWalk: https://p.libren.ms/view/a72ea6b8

[20171003-POLLER-DPSNETGUARDIAN.log](https://github.com/librenms/librenms/files/1352313/20171003-POLLER-DPSNETGUARDIAN.log)

**Comment by taking-care-of-business** [comment]
Not much has happened on the ticket.
Essentially there are no additional graphs generated, but the output (i.e.: polling output for instance) is more verbose than before. I believe the firmware upgrade did fix the issue with obtaining data from the `.1.3.6.1.4.1.2682.` OID.

**Comment by laf** [comment]
What data are you expecting to see? All useful information in the MIBS is from ` .1.3.6.1.4.1.2682.2` which your device isn't returning. The data in ` .1.3.6.1.4.1.2682.1` according to the MIB doesn't really contain anything useful for us unless we are missing some mibs.

**Comment by laf** [comment]
Feel free to provide more information and we can re-open this.
