### ISSUE TITLE
Refused to display in a frame because it set 'X-Frame-Options' to 'deny'.

### ISSUE THREAD

**Issue by tslytsly** [librenms/librenms#7276]
Hi,

This may be a bug, if not I'm happy to move it to the community site.

I cannot open the realtime port graph any more, this used to work.

Now I get this in Chrome:
![image](https://user-images.githubusercontent.com/17383159/29930435-4d7afdca-8e66-11e7-991d-56fef6c98aab.png)

In firefox I just get a blank screen.

This is in the console:

```
Refused to display 'https://<URL>/graph-realtime.php?type=bits&id=57394&interval=0.25' in a frame because it set 'X-Frame-Options' to 'deny'.
(index):1 GET https://<URL>/graph-realtime.php?type=bits&id=57394&interval=0.25 net::ERR_BLOCKED_BY_RESPONSE
```

If I click on the URL displayed in the console it opens the realtime view in a new tab and works fine.

```
====================================
Component | Version
--------- | -------
LibreNMS  | 1.30-132-g6914666
DB Schema | 205
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Database connection successful
[OK]    Database schema correct
```

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
What versions of browsers? Works for me in Chrome 59.0.3071.115

**Comment by laf** [comment]
Also works in 60.0.3112.113

**Comment by laf** [comment]
In fact looking, this is a server side issue so either your web server is now defaulting to have that turned on or you've got it set to be on: https://geekflare.com/add-x-frame-options-nginx/
