### ISSUE TITLE
Add OS discovery for ServerChecks

### ISSUE THREAD

**Issue by jayceeemperador** [librenms/librenms#7284]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
Discovery: https://p.libren.ms/view/7dc80cbe
Poller: https://p.libren.ms/view/13dba73d
SNMPWalk: https://p.libren.ms/view/0ac61865
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Component | Version
-- | --
LibreNMS | 1.31.03-13-gda0dcda
DB Schema | 205
PHP | 7.0.22
MySQL | 5.5.52-MariaDB
RRDTool | 1.4.8
SNMP | NET-SNMP 5.7.2

We tried, was able to have logo, but we need assistance in creating graphs for our ServersCheck. We want to have graphs for:
1.3.6.1.4.1.17095.3.2.0  - reading from built-in temperature sensor 
1.3.6.1.4.1.17095.3.6.0 – reading from external probe (temperature, flooding, airflow, power failure, fuel level) 
1.3.6.1.4.1.17095.3.10.0 – reading from the external probe (humidity) 

Here is the link to its mib file http://downloads.serverscheck.com/sensors/sensorgateway.mib

Thank you

**Comment by laf** [comment]
So you've already added some code? It would be much better to submit a pull request with what you have and we can help with it.

**Comment by jayceeemperador** [comment]
Only code that we created was an OS file at includes/definitions/ , to have logo. That's all

**Comment by laf** [comment]
You should still submit a PR, no point in us doing the work again.

**Comment by laf** [comment]
Merged in #7308
