### ISSUE TITLE
Cisco - Discovery LLDP - Mib LLDP-EXT-MED-MIB

### ISSUE THREAD

**Issue by aauvinet** [librenms/librenms#7290]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by aauvinet** [comment]
I would like use LLDP-EXT-MED-MIB in discovery-protocols module for retrieve  end devices in Cisco switch.
When i do "php discovery.php -h myswitch -d -m discovery-protocols "

It's LLDP-MIB :  

 LLDP-MIB: SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY  -OQUs -m LLDP-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:HOSTNAME:161 lldpRemoteSystemsData]

But, script don't retrieve lldp informations like LLDP-EXT-MED-MIB.

Cdlt,

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
