### ISSUE TITLE
New Device Request Calix B6-252

### ISSUE THREAD

**Issue by Bryan001** [librenms/librenms#7293]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.31.03-17-ge754e95
DB Schema | 206
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
Discovery  https://p.libren.ms/view/4df099d3
Poller   https://p.libren.ms/view/40b4869c
SNMPWALK https://p.libren.ms/view/46c9949f

I tried the script but wasn't sure how to use the "sensors" section to add this device.
The Ethernet Ports will graph but the DSL ports will not.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations
[b6-mibs8-0.zip](https://github.com/librenms/librenms/files/1285564/b6-mibs8-0.zip)

**Comment by laf** [comment]
Are these the DSL interfaces you want to see:

![image](https://user-images.githubusercontent.com/3941142/30323357-d2e78832-97b4-11e7-9c99-74911af761b5.png)

Or is something else? If it's something else please provide the MIB name and OIDs needed but I'm not sure we will be able to just add support for that.

**Comment by Bryan001** [comment]
Yes sir.  The graphs aren't showing the stats.
![dsl_traffic](https://user-images.githubusercontent.com/31680726/30325251-a264e9be-9789-11e7-9bbc-ebe9df918806.png)

**Comment by Bryan001** [comment]
Here is a DSL Port from the Calix Gui.

![port_info](https://user-images.githubusercontent.com/31680726/30325858-03539340-978c-11e7-8b59-78b7172e02b2.png)

**Comment by laf** [comment]
Your device has either a really bad snmp implementation or you've got timeouts. Barely any ifInOctets are returned and no ifOutOctets are. These should be provided from the standard IF-MIB.

**Comment by laf** [comment]
PR submitted

**Comment by Bryan001** [comment]
I've tried shutting down most of the device's to see if that would help.  I've rebooted librenms.  Here are the icmp stats for the calix blade.  I'm not sure why, but its not pulling the port state anymore.  I deleted and re-added it but not seeing any changes.  

![icmp](https://user-images.githubusercontent.com/31680726/30348095-c933906e-97d3-11e7-8bc6-b0f2a705a65b.PNG)

Here is one that was pulling ethernet stats but never DSL.
![graph](https://user-images.githubusercontent.com/31680726/30348641-b7ac14d6-97d5-11e7-80f1-397c23ef7c21.PNG)

**Comment by laf** [comment]
@murrant How come this was re-opened?

**Comment by murrant** [comment]
Thought it was still being discussed.

**Comment by laf** [comment]
The discussion is mute really as the devices aren't sending the data back due to timeouts.
