### ISSUE TITLE
New Device - Brocade VTM (Virtual Traffic Manager)

### ISSUE THREAD

**Issue by balpoint** [librenms/librenms#7294]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================
Component | Version
--------- | -------
LibreNMS  | 1.31.03-17-ge754e9503
DB Schema | 206
PHP       | 7.0.19-1
MySQL     | 10.1.26-MariaDB-0+deb9u1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
====================================
` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
discovery.php: https://p.libren.ms/view/3945adba
poller.php: https://p.libren.ms/view/29f3991f
snmpbulkwalk: https://p.libren.ms/view/c08d370d
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Can we get support for the Brocade VTM loadbalancer, Libre discovers it as a Linux server rather than a loadbalancer with it's own checks.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
What OS do these run?

**Comment by laf** [comment]
No further info provided. If you can respond to the last comment we can re-open this.
