### ISSUE TITLE
New Device - Alpha FXM/Micro UPS

### ISSUE THREAD

**Issue by kmpanilla** [librenms/librenms#7306]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 1.31.03-25-gec72eb2
DB Schema | 206
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 5.6.36-82.0-log
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

Alpha has a number of UPS units (this one references FXM/Micro) .  
Would love to get support added for these.  

Here are the requested outputs:
DISCOVERY: 	https://p.libren.ms/view/ecacfedd
POLLER: 	https://p.libren.ms/view/52d01e31
BULKWALK: 	https://p.libren.ms/view/8d7e96ba

Public MIB downloaded from Alpha: 035-092-01-REVJ_FXM_V2.00.04_SNMP_MIB.MIB
	https://p.libren.ms/view/b3d2d610
(Designed to work with FXM/Micro units and Ethernet card that are using firmware V2.00.04)

Let me know if I can provide any other info?

**Comment by laf** [comment]
![image](https://user-images.githubusercontent.com/3941142/30344964-489163e6-97fb-11e7-81ef-2bf9823de4cc.png)

This is what I've submitted for support - please take a quick look. I expect some values are wrong but as the mib doesn't tell you the values they are in I've left them as our defaults.

**Comment by kmpanilla** [comment]
Output Frequency and Output Current current should be multiplied by 0.1.  The MIB shows their UNITS are 0.1 Hertz/Amps.

Minutes on battery probably might be better as a counter like an interface.. as it won't be increasing unless you the UPS is on battery? and it's ever incrementing.

What about graphing Battery Capacity?  Looks like it's 0.1 multiplier too.
upsBatteryCapacity.0 = INTEGER: 170 0.1 Amp DC

"Output Source" = line is normal when operating. Can we make that green?

**Comment by laf** [comment]
> Output Frequency and Output Current current should be multiplied by 0.1. The MIB shows their UNITS are 0.1 Hertz/Amps.

Changed.

> Minutes on battery probably might be better as a counter like an interface.. as it won't be increasing unless the UPS is on battery? and it's going to be always incrementing forever and ever when it's on battery.

You mean the graph itself? We can't change the graphs once created unfortunately.


> What about graphing Battery Capacity? Looks like it's 0.1 multiplier too.
> upsBatteryCapacity.0 = INTEGER: 170 0.1 Amp DC

That would be labelled as current. Is that what you'd expect to see?

> "Output Source" = line is normal when operating. Can we make that green?

Done

**Comment by kmpanilla** [comment]
> You mean the graph itself? We can't change the graphs once created unfortunately.

Right, but can you make the default graph similar to interface style counters? Otherwise it'll always be in the red as my UPS has a current lifetime of 2843Min and will until it runs on battery again.  At that point it increments every minute it's on battery, so it might go up to 2844 Minutes. Might be more useful to just show the differences on the graph similar to interface counters rather than a single line that would always be constant at 2843 (in my case) until it increases when on battery. Make sense?

> That would be labelled as current. Is that what you'd expect to see?

That'd be sufficient I think.

**Comment by laf** [comment]
> Right, but can you make the default graph similar to interface style counters? Otherwise it'll always be in the red as my UPS has a current lifetime of 2843Min and will until it runs on battery again. At that point it increments every minute it's on battery, so it might go up to 2844 Minutes. Might be more useful to just show the differences on the graph similar to interface counters rather than a single line that would always be constant at 2843 (in my case) until it increases when on battery. Make sense?

Yes but this is a generic runtime health metric so I'm not sure that's then applicable for other data we collect for other devices.

**Comment by kmpanilla** [comment]
> Yes but this is a generic runtime health metric so I'm not sure that's then applicable for other data we collect for other devices.

Understood.
