### ISSUE TITLE
SAF IntegraB/W Followup

### ISSUE THREAD

**Issue by kmpanilla** [librenms/librenms#7307]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
====================================
Component | Version
--------- | -------
LibreNMS  | 1.31.03-27-g455c721
DB Schema | 206
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 5.6.36-82.0-log
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

On the recent SAF IntegraB/W commit, there's a typo on the discoverWirelessPower() function in LibreNMS/OS/SafIntegraW.php and LibreNMS/OS/SafIntegraB.php. The "Rx Power" should be "Tx Power", and "saf-integra-rx"/"saf-integrab-rx" should be "saf-integra-tx"/"saf-integrab-tx", as you're calling the TX power OID, not the RX power one.

Along those same lines, can we get the RX Power OID added as well? It's a negative value and accessible via integraBradioRxLevel (for IntegraB) and integraWradioRxLevel (for integraW).

Other useful things to graph and the appropriate MIB entries in integraW and integraB:
FEC Load: integraWmodemFecLoad / integraBmodemFecLoad
RX modem modulation: integraWmodemRxModulation / integraBmodemRxModulation
TX modem modulation: integraWmodemTxModulation / integraBmodemTxModulation

If I can provide any other outputs, please let me know.

Thanks for the help!

**Comment by kmpanilla** [comment]
Couple of more issues I'm seeing when pulling up the /devices/ page for these IntegraB and IntegraW hosts:  
1) in the drop down for "All OSes" I dont see the IntegraB or IntegraW listed, just two blank options.  Appears the HTML code just has the options, but no text for them:
<option value="saf-integra-b" ></option>
<option value="saf-integra-w" selected></option>

When I do select one (for instance saf-integra-w) the resulting devices that list have their "Platform" and "Operating System" columns blank.   However, when viewing one of the devices the "Operating System" and "Serial" are matched and filled out.

**Comment by laf** [comment]
I'm submitting a fix for the RX + TX level.

> FEC Load: integraWmodemFecLoad / integraBmodemFecLoad
> RX modem modulation: integraWmodemRxModulation / integraBmodemRxModulation
> TX modem modulation: integraWmodemTxModulation / integraBmodemTxModulation

We have no ability to detect these, feel free to add to the wireless thread on the community site to ask for support to be added.

> in the drop down for "All OSes" I dont see the IntegraB or IntegraW listed, just two blank options. Appears the HTML code just has the options, but no text for them:
> When I do select one (for instance saf-integra-w) the resulting devices that list have their "Platform" and "Operating System" columns blank. However, when viewing one of the devices in detail the "Operating System" and "Serial" are matched and correct.

This is because your os cache is out of date, it only rebuilds every 24 hours so should be nearly cleared by now.

**Comment by murrant** [comment]
@laf modulation is usually a state sensor.

**Comment by kmpanilla** [comment]
@laf Versions still arent showing up on the main devices listing for either Integra options.  Platform is still also blank.

SNMP Output for an IntegraB shows: Prod: Integra;Vers: 3.6.18;Timestamp: 2017-06-12 16:26:01;kernel: 3.15.0;rootfs: 0.0.5;fpga: 0.0.5;devicetree: 0.0.5;P/C: D18BSR03H;S/N: 382920100006
IntegraW shows: Prod: Integra-W;Vers: 3.6.17-mux;Timestamp: 2017-05-24 16:00:47;kernel: 3.15.0;rootfs: 0.0.5;fpga: 0.0.5;devicetree: 0.0.5;P/C: D18WSR03L;S/N: 391340100285

Should be able to match the Version from the "Vers:" column, right?  Platform, maybe the P/C? I dunno.
