### ISSUE TITLE
New Device: IgniteNet FusionSwitch Fiber

### ISSUE THREAD

**Issue by MHammett** [librenms/librenms#7310]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

1.31.03-27-g455c721 - Fri Sep 08 2017 15:22:03 GMT-0500

- [X ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
====================================
Component | Version
--------- | -------
LibreNMS  | 1.31.03-27-g455c721
DB Schema | 206
PHP       | 5.6.30-0+deb8u1
MySQL     | 10.0.32-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
====================================

- [X ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/38fde8a0
https://p.libren.ms/view/85586277
http://indy-librenms.midwest-ix.com/ignitenetwalk.txt  (going to the pastebin crashed)
- [ X] Please provide as much detail as possible.
https://www.ignitenet.com/products/fusionswitch-fiber/

- [X ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
I've submitted a PR for detection. If you have a MIB / can find one we can probably add more info

**Comment by MHammett** [comment]
I just poked IgniteNet. I'll update when I have more.

**Comment by MHammett** [comment]
MIB for switch:  https://www.dropbox.com/s/kw0ig09vgkjyw5z/ES4552BH2.mib?dl=0

MIB (work in progress) for IgniteNet wireless: https://www.dropbox.com/s/eiaixnklv6t25lt/IGNITENET-MIB.mib?dl=0

**Comment by laf** [comment]
@MHammett Added:

![image](https://user-images.githubusercontent.com/3941142/30785649-ff547ed2-a161-11e7-849f-1be8799d43e1.png)

Some of the names aren't great because the OID references two indexes, neither of which contain anything useful.

Let me know if you spot anything else you would want adding.

**Comment by MHammett** [comment]
If they need to fix anything in the MIB, let me know. I can get them to fix it. I don't know enough about SNMP\MIBs to look at them myself and figure it out.

48.3A seems like an awful lot of current. I don't see anything obvious in their switch webUI to report current, so I'm not sure if it's reporting badly or something else.

volts, amps and watts aren't matching up, but again, that may be an issue with what's being reported and not Libre.

**Comment by laf** [comment]
Yeah slight issue on my side, here's an updated one:

![image](https://user-images.githubusercontent.com/3941142/30786535-6c84b24e-a16f-11e7-9329-ad760a6d300c.png)

**Comment by laf** [comment]
@MHammett how does this look now?

**Comment by MHammett** [comment]
Sorry for missing the previous message from @laf. Would the changes be reflected in 1.32-82-gfea6351?
