### ISSUE TITLE
Add support for APC In Row RD CRACs

### ISSUE THREAD

**Issue by Blorpy** [librenms/librenms#7319]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
`Component | Version
--------- | -------
LibreNMS  | 1.31.03-30-g9cafcb6
DB Schema | 206
PHP       | 5.4.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.5.6
SNMP      | NET-SNMP 5.7.2`
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Looking to have support for various sensors for APCs In Row coolers [http://www.apc.com/shop/ca/en/products/InRow-RD-300mm-Fluid-Cooled-208-230V-60Hz/P-ACRD200](http://www.apc.com/shop/ca/en/products/InRow-RD-300mm-Fluid-Cooled-208-230V-60Hz/P-ACRD200). Right now the device is detected as "APC Management Module", and there isn't any sensors shown, only traffic for the NIC. 

Based on digging in the MIB and using snmpwalk, the following is primarily what seems useful, but of course someone might argue:

.1.3.6.1.4.1.318.1.1.13.4.5.2.1.2 = Cooling output (kW)
.1.3.6.1.4.1.318.1.1.13.4.5.2.1.3 = Cooling demand (kW)
.1.3.6.1.4.1.318.1.1.13.4.5.2.1.5 = Airflow (metric, liter/s)
.1.3.6.1.4.1.318.1.1.13.4.5.2.1.7 = Rack inlet temperature (metric, C)
.1.3.6.1.4.1.318.1.1.13.4.5.2.1.9 = Supply air temperature (metric, C)
.1.3.6.1.4.1.318.1.1.13.4.5.2.1.11 = Return air temperature (metric, C)
.1.3.6.1.4.1.318.1.1.13.4.5.2.1.13 = Suction temperature (metric, C)
.1.3.6.1.4.1.318.1.1.13.4.5.2.1.19 = Suction pressure (metric, KPa)
.1.3.6.1.4.1.318.1.1.13.4.5.2.1.21 = Discharge pressure (metric, KPa)
.1.3.6.1.4.1.318.1.1.13.4.5.2.1.22 = Fan speed (percentage)

Discovery: https://p.libren.ms/view/e329d2bf
Poller: https://p.libren.ms/view/0059c697
snmpwalk generic: https://p.libren.ms/view/234272ee
snmpwalk APC MIB: https://p.libren.ms/view/fe5fd03f

**Comment by laf** [comment]
Have a check of these:
![image](https://user-images.githubusercontent.com/3941142/30786392-c0fa4bac-a16c-11e7-91f7-266902abd537.png)

**Comment by Blorpy** [comment]
Couple minor things:

Fanspeed is reported in RPM but it should be percentage, not sure why APC does it this way. Cooling output and cooling demand have one too many zeros on the multiplier, for example when the demand/output is 2400W, it is displayed as 24000W.

**Comment by laf** [comment]
Cooling is returned as kW from the device (according to the mib) and we want it in W so the multiplier should be correct (1000).

Fanspeed. I've removed this as we expect the value in rpm so we can't store %.

**Comment by Blorpy** [comment]
Maybe the issue is that there should be a decimal point in the return value then.

For example when 24 is returned, this implies 2.4kW, but is displayed as 24000W, which is 24kW.

**Comment by laf** [comment]
Sorry you're right, it's in tenths of kW. Updated to x 100.

**Comment by Blorpy** [comment]
Looks good, thanks a million!

**Comment by Blorpy** [comment]
Sorry, actually it looks like both cooling demand and cooling output aren't being graphed. The RRD seems to indicate this is trying to be graphed as RPM?

**Comment by laf** [comment]
What do you mean the rrd indicates this?

**Comment by Blorpy** [comment]
Sorry for not being clear. 

The graphs are working, but the unit in the RRD is shown as RPM when it should be kW.

**Comment by laf** [comment]
Ah yes well spotted. Updated.
