### ISSUE TITLE
New Device - A10 Networks TPS

### ISSUE THREAD

**Issue by papatango71** [librenms/librenms#7343]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

librenms@lax1-admin-inf01
[/opt/librenms]$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.31.03-45-gb4d804f
DB Schema | 206
PHP       | 7.0.20
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Database connection successful
[OK]    Database schema correct

DISCOVERY :: https://p.libren.ms/view/8dd2521e
POLLER :: https://p.libren.ms/view/58ba4f94
SNMPBULKWALK :: https://p.libren.ms/view/8ab2b4a3

MIBS ::
A10-COMMON-MIB.txt :: https://p.libren.ms/view/a23859c9
A10-AX-NOTIFICATIONS-V2C.txt :: https://p.libren.ms/view/caad0c82
A10-AX-MIB.txt :: https://p.libren.ms/view/87c80ce0

**Comment by laf** [comment]
These are already supported. If you want something specific please be descriptive.
