### ISSUE TITLE
New Device - SmartOptics T-Series

### ISSUE THREAD

**Issue by papatango71** [librenms/librenms#7345]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

DISCOVERY :: https://p.libren.ms/view/9c6d020a
POLLER :: https://p.libren.ms/view/3e273b14
SNMPBULKWALK :: [t-series_snmpwalk.txt](https://github.com/librenms/librenms/files/1305441/t-series_snmpwalk.txt)

MIBS::
[RV.txt](https://github.com/librenms/librenms/files/1305407/RV.txt)
[SL-ALARM.txt](https://github.com/librenms/librenms/files/1305409/SL-ALARM.txt)
[SL-ALS-MIB.txt](https://github.com/librenms/librenms/files/1305406/SL-ALS-MIB.txt)
[SL-CHASSIS.txt](https://github.com/librenms/librenms/files/1305405/SL-CHASSIS.txt)
[SL-DCM.txt](https://github.com/librenms/librenms/files/1305408/SL-DCM.txt)
[SL-DRY-CONTACTS.txt](https://github.com/librenms/librenms/files/1305410/SL-DRY-CONTACTS.txt)
[SL-EDFA.txt](https://github.com/librenms/librenms/files/1305411/SL-EDFA.txt)
[SL-ENTITY.txt](https://github.com/librenms/librenms/files/1305412/SL-ENTITY.txt)
[SL-ETH.txt](https://github.com/librenms/librenms/files/1305413/SL-ETH.txt)
[SL-EVENT.txt](https://github.com/librenms/librenms/files/1305414/SL-EVENT.txt)
[SL-L2TOPOLOGY.txt](https://github.com/librenms/librenms/files/1305415/SL-L2TOPOLOGY.txt)
[SL-MAIN.txt](https://github.com/librenms/librenms/files/1305418/SL-MAIN.txt)
[SL-MUX.txt](https://github.com/librenms/librenms/files/1305419/SL-MUX.txt)
[SL-NE.txt](https://github.com/librenms/librenms/files/1305417/SL-NE.txt)
[SL-OPT-APS.txt](https://github.com/librenms/librenms/files/1305416/SL-OPT-APS.txt)
[SL-OSW.txt](https://github.com/librenms/librenms/files/1305420/SL-OSW.txt)
[SL-OTN.txt](https://github.com/librenms/librenms/files/1305426/SL-OTN.txt)
[SL-PM.txt](https://github.com/librenms/librenms/files/1305421/SL-PM.txt)
[SL-PORT.txt](https://github.com/librenms/librenms/files/1305422/SL-PORT.txt)
[SL-RADIUS.txt](https://github.com/librenms/librenms/files/1305425/SL-RADIUS.txt)
[SL-RETIMER.txt](https://github.com/librenms/librenms/files/1305423/SL-RETIMER.txt)
[SL-ROADM.txt](https://github.com/librenms/librenms/files/1305424/SL-ROADM.txt)
[SL-SECU.txt](https://github.com/librenms/librenms/files/1305427/SL-SECU.txt)
[SL-SFP.txt](https://github.com/librenms/librenms/files/1305428/SL-SFP.txt)
[SL-SNTP.txt](https://github.com/librenms/librenms/files/1305429/SL-SNTP.txt)
[SL-TESTS.txt](https://github.com/librenms/librenms/files/1305430/SL-TESTS.txt)
[SL-TRAP.txt](https://github.com/librenms/librenms/files/1305431/SL-TRAP.txt)
[SL-XPDR.txt](https://github.com/librenms/librenms/files/1305432/SL-XPDR.txt)

**Comment by laf** [comment]
Basic detection added. If you want something more specific please let us know. I've looked through the MIBs and can't see anything of interest.
