### ISSUE TITLE
Distributed Poller and validate check

### ISSUE THREAD

**Issue by kmpanilla** [librenms/librenms#7351]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.31.03-47-g529660b
DB Schema | 206
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 5.6.36-82.0-log
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Is it possible to get validate.php to throw an error if distributed_poller and distributed_poller_memcached_host  are set but the python-memcached isn't installed?  That would've saved me 15 minutes of troubleshooting :)

Also on https://docs.librenms.org/Extensions/Distributed-Poller/ you mention for a "full" install you need python-memcached, but nothing about it being required for Poller installs. 

Feel free to resolve or delete. Just thought it might be helpful for someone in the future.

**Comment by laf** [comment]
> Is it possible to get validate.php to throw an error if distributed_poller and distributed_poller_memcached_host are set but the python-memcached isn't installed? That would've saved me 15 minutes of troubleshooting :)

I'm not sure we really can. Different distros, different ways to install python modules and validate is in php.

> Also on docs.librenms.org/Extensions/Distributed-Poller you mention for a "full" install you need python-memcached, but nothing about it being required for Poller installs.

The docs actually say "These requirements are above the normal requirements for a full LibreNMS install." as in in addition to. If you can suggest better wording please submit a pull request, it's easy to edit docs and propose your changes.

**Comment by kmpanilla** [comment]
> I'm not sure we really can. Different distros, different ways to install python modules and validate is in php.

What about calling the python script with a "validate" parameter from validate.php to check to make sure its libraries are available/installed?  Shouldn't that catch all the different distros, etc? 

I'm up and rolling, so no need to keep this open longer if you think it's not worth it.  Thanks for listening.

**Comment by Gorian** [comment]
@laf 

well - we could search for the line in the config indicating the host is a remote poller, and then strip the bin from the shebang of the `poller-wrapper.py` script, attempt to import the module, and see if it's successful. Something like this:
![image](https://user-images.githubusercontent.com/1012176/30567211-274bd8a0-9c84-11e7-8ffd-4b634790fb10.png)
This should replicate the environment that `poller-wrapper.py` is using, in most cases.

**Comment by laf** [comment]
@Gorian if you can do something about it then feel free.

**Comment by laf** [comment]
@kmpanilla can you move this to feature requests on the community site please?
