### ISSUE TITLE
Missing metrics for Avocent PM2000/3000 smart PDUs. 

### ISSUE THREAD

**Issue by fake-name** [librenms/librenms#7356]
I have a Avocent PM3000 series PDU, which is a "smart" outlet strip with per-outlet current monitoring, and switching.

It exposes the monitoring statistics for all the outlets over SNMP, but it appears that avocent has a custom set of MIBs, which are currently missing. Avocent ships their custom `.asn` file [here](https://www.vertivco.com/en-us/support/software-download/it-management/avocent-managed-rack-pdu---pm-1000-2000-3000-software-downloads/), [direct link](http://downloads2.vertivco.com/RackPDU/PM_PDU/MIB_TRAP-MIB/Avocent-PM-MIB_2.0.1.asn).

Sticking the above MIB file into snmpwalk lets you pull a bunch of the interesting end-points:
`durr@monvm:~$ snmpwalk -c <snip>-v 2c 10.1.1.3 -m ./Avocent-PM-MIB_2.0.1.asn PM-MIB::pmPowerMgmtOutletsTableCurrentValue.1.1.1`

Avocent also has a pretty decent documentation page [here](https://vertivco-eng.custhelp.com/app/answers/detail/a_id/10045/~/how-to-pull-avocent-pm3000-3phase-model-pm3024-power-management-data-thru-snmp). 

Note: Avocent was purchased by Emerson Network Power Devices, which then rebranded to "Vertiv".

------

[discovery.php](https://p.libren.ms/view/10847f43)  
[poller.php](https://p.libren.ms/view/77b07ff8)  
[snmpbulkwalk](https://p.libren.ms/view/fec0a6b6)  

Yes, I just git pulled.

```
====================================
Component | Version
--------- | -------
LibreNMS  | 1.31.03-50-gb19b9e9
DB Schema | 206
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================
```

**Comment by fake-name** [comment]
Ok, the above snmpbulkwalk is kind of useless. 

Looking on the [docs page](https://vertivco-eng.custhelp.com/app/answers/detail/a_id/10045/~/how-to-pull-avocent-pm3000-3phase-model-pm3024-power-management-data-thru-snmp), it looks like they locate all their MIBs on `.1.3.6.1.4.1.10418.17.2.*`.

Poking that into `snmpbulkwalk` (`snmpbulkwalk -OUneb -v2c -c <snip> 10.1.1.3 .1.3.6.1.4.1.10418`: https://p.libren.ms/view/b9b29f13

**Comment by fake-name** [comment]
What can I do for the "needs-verification" tag. Is that dependent on someone else verifying?

**Comment by laf** [comment]
From the data you supplied, this is all I can get:

![image](https://user-images.githubusercontent.com/3941142/31299703-9f9b29e8-aae7-11e7-9934-9cfa22b50cc7.png)

**Comment by fake-name** [comment]
You should also get current values, though for the supplied data, I didn't have anything connected, so they're all zero.

Here's the system with some of the outlets connected to servers: https://p.libren.ms/view/6ef91cce

There are multiple values of interest:

 - Wattage per-outlet
 - Wattage per-bank
 - Current per-outlet
 - Current per-bank
 - Power factor
 - PDU temperature
 - (Optional) external sensors - the PDU supports external temperature and humidity sensors.

A number of the values are reported as integers * 10. Things like the watt values and temperature should be divided by 10 to get actual values. The power-factor values should be divided by 100 (power factor is value between 0 and 1). 

Avocent makes a number of these units with variable number of banks. Each bank is a set of 10 outlets. The PDU I have has 2 banks, but they make them also with 1 bank, and I think some with 3 (don't quote me on that).

I have a silly little project that logs the wattages and some other data to a statsd instance [here](https://github.com/fake-name/StatsdWidgets/blob/master/AvoPower/avocent_power_mon.py), that I wrote a bit ago.

**Comment by laf** [comment]
Thanks, that info would have been helpful before :)

Should have pretty much all of what you want except things in pmPowerMgmtSensorsTable which are the optional ones. We don't have a nice way to do this in yaml yet so will need to wait until we do.

**Comment by fake-name** [comment]
Sorry about that, I wasn't sure what was apparent from the MIB outputs. DERP.

The sensors stuff not being supported yet is fine. I don't even have any of them, and since no one else is asking about these things, I'd guess it's not too in-demand.
