### ISSUE TITLE
add new transport 

### ISSUE THREAD

**Issue by Mars399** [librenms/librenms#7361]
Dear Sir:

i added customization transport plugin  Librenms,  the file put in path "/opt/librenms/includes/alerts/"
and change name "transport.customer.php", why i didn't find any GUI Interface on Alert Settings page.

please help me.

Thanks.
BR.,

Mars

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
