### ISSUE TITLE
Brocade VDX 6740 that aren’t recognized correctly

### ISSUE THREAD

**Issue by goodsungki** [librenms/librenms#7362]
Hi, we have multiple Brocade VDX 6740 that aren’t recognized correctly. They appear as generic devices. Those switches are running NOS 6.0.2b.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by goodsungki** [comment]
I've been asked to create an issue in github. Why are you closing...

https://community.librenms.org/t/brocade-vdx-6740-showing-as-generic-device/2127

**Comment by laf** [comment]
Because you've removed the entirety of the template text which you should have read and responded to.

**Comment by goodsungki** [comment]
okay. sorry I didn't see it.
I recreated https://github.com/librenms/librenms/issues/7366
