### ISSUE TITLE
BGP not detected

### ISSUE THREAD

**Issue by saviokmua** [librenms/librenms#7364]
Hello!
I migrated from observium to librenms. But when I added device Extreme x480 and Juniper M80, system detected only OSPF protocol. BGP I can't see in web interface

What am I doing wrong?
Thanks!

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
