### ISSUE TITLE
LLDP of BDCOM S2524D switches is not detected

### ISSUE THREAD

**Issue by Pentium100MHz** [librenms/librenms#7370]
Hello, I have a few BDCOM S2524D switches and LibreNMS does not detect their links using LLDP. I have found out that it uses the wrong MIB (LLDP-MIB instead of NMS-LLDP-MIB). Here is how I fixed it in my system, hopefully this will help fix the bug for everyone.

diff discovery-protocols.inc.php /opt/librenms/includes/discovery/discovery-protocols.inc.php 
<pre>
92c92
< if ($device['os'] == 'pbn' && Config::get('autodiscovery.xdp') === true) {
---
> if (($device['os'] == 'pbn' || $device['os'] == 'bdcom')  && Config::get('autodiscovery.xdp') === true) {
94c94
<     $lldp_array  = snmpwalk_cache_oid($device, 'lldpRemoteSystemsData', array(), 'NMS-LLDP-MIB', 'pbn');
---
>     $lldp_array  = snmpwalk_cache_oid($device, 'lldpRemoteSystemsData', array(), 'NMS-LLDP-MIB', $device['os']);</pre>

After the change, links from BDCOM switches are detected correctly.

**Comment by murrant** [comment]
The second line is unnecessary, the OS's directory is always included.

Perhaps you should send a pull request for this change.  https://docs.librenms.org/Developing/Using-Git/
