### ISSUE TITLE
Huawei oceanstore 2600 v3 device support

### ISSUE THREAD

**Issue by telskamp** [librenms/librenms#7372]
DO NOT DELETE THIS INFORMATION.
- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the  section of `./validate.php` 
Component | Version
--------- | -------
LibreNMS  | 1.31.03-63-g777eb1f
DB Schema | 207
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/47934ea7
https://p.libren.ms/view/13214886
https://p.libren.ms/view/a7fb7a93
- [x ] Please provide as much detail as possible.
Currently we have two huawei Oceanstore machines which are not supported yet, this request is for the first one we have: the Huawei oceanstore 2600 v3.
Please find the information in the links provided, MIBs attatched as well
[Huawei MIB.zip](https://github.com/librenms/librenms/files/1320485/Huawei.MIB.zip)

**Comment by rtfmjoey** [comment]
Hi,

Please find the attached zip file for all OceanStor devices, as this request is for a V3 system, The V3/V3R2 MIB's  should be used. 

Other MIB's are V2/Dorado/T-series compatible.


[Storage Device MIB File and Description.zip](https://github.com/librenms/librenms/files/1323663/Storage.Device.MIB.File.and.Description.zip)

**Comment by laf** [comment]
I've submitted a PR which adds support for this device, only really basic storage is detected though. Not sure what you were expecting to see but the MIBs are limited, where they aren't - we don't have support.
