### ISSUE TITLE
Huawei Oceanstore 5300 v3 device support

### ISSUE THREAD

**Issue by telskamp** [librenms/librenms#7373]
- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the Component | Version
--------- | -------
LibreNMS | 1.31.03-63-g777eb1f
DB Schema | 207
PHP | 7.0.22-0ubuntu0.16.04.1
MySQL | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool | 1.5.5
SNMP | NET-SNMP 5.7.3from the cli.

- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/c85a47d7
https://p.libren.ms/view/f54c0f98
https://p.libren.ms/view/0a1d61b7
- [ x] Please provide as much detail as possible.
This the huawei Oceanstore 5300 v3

**Comment by telskamp** [comment]
[Huawei MIB.zip](https://github.com/librenms/librenms/files/1320499/Huawei.MIB.zip)

**Comment by laf** [comment]
Does this run a totally different Os from your other Oceanstore request?

**Comment by telskamp** [comment]
To be honest I am not 100% sure how different it is (or not)  it do think it is at least based on the same os. In the 2600 v3 librenms does  recognize some NIC s even though not 100%correctly. On  the 5300 it does not discover anyting except for syslocation and sysname

**Comment by laf** [comment]
Detection is the same for 2600 (Same sysObjectID and sysDescr).
