### ISSUE TITLE
HP MSA P2000 device support

### ISSUE THREAD

**Issue by DiEgAle** [librenms/librenms#7381]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.31.03-66-gef9ada9
DB Schema | 207
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 5.7.19-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

https://p.libren.ms/view/ffc9a518
https://p.libren.ms/view/9b6af784
https://p.libren.ms/view/1c898379

- [x] Please provide as much detail as possible.
HP StorageWorks P2000 G3 iSCSI
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Can you provide more information on what you want to see as I don't see a great deal of info in the snmpwalk?

**Comment by DiEgAle** [comment]
Good afternoon

I would like to see statistics on LAN interfaces, LUN sections.

Thank you

**Comment by laf** [comment]
LAN interfaces show up fine for me, the data you've provided only has lo, eth0, sit0 and sl0 (this is ignored due to the defaults). What are you not seeing / expecting to see?

We don't currently gather data for LUNs.

**Comment by DiEgAle** [comment]
Network interfaces are displayed correctly, thank you. I would like to see the information on LUNs, if possible, otherwise thank you very much.

**Comment by laf** [comment]
Feel free to create a feature request on the community site for LUN support.
