### ISSUE TITLE
oxidized git versioning and xml display issue

### ISSUE THREAD

**Issue by tomarch** [librenms/librenms#7382]
Oxidized output is GIT and $config['oxidized']['features']['versioning'] = true;
When viewing config which contain xml code (like pfsense one), there's a charset issue.
This is an example of what i get:
`&lt;pfsense&gt;
	&lt;version&gt;12.0&lt;/version&gt;
	&lt;lastchange/&gt;`

When i set $config['oxidized']['features']['versioning'] = false; the xml display is OK

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.31.03-66-gef9ada9
DB Schema | 207
PHP       | 7.0.22
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
Fresh install of OXIDIZED (installed via "gem").
Output to "git"
$config['oxidized']['features']['versioning'] = true;
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by jerebernard** [comment]
Exactly the same issue

**Comment by laf** [comment]
Is it doing it in the oxidized web ui? https://github.com/ytti/oxidized-web/issues/142

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by mattie47** [comment]
@laf  I think this should be re-opened.

Applying https://github.com/ytti/oxidized-web/pull/151 works in oxidized-web, however

```
&lt;secret hidden&gt;
```

is still observed in the same configs in Librenms. 


Thanks,

Matt
