### ISSUE TITLE
Add Sensor Discovery for Serverscheck/SensorGateway

### ISSUE THREAD

**Issue by jayceeemperador** [librenms/librenms#7383]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
Discovery: https://p.libren.ms/view/7dc80cbe
Poller: https://p.libren.ms/view/13dba73d
SNMPWalk: https://p.libren.ms/view/0ac61865
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Component | Version
-- | --
LibreNMS | 1.31.03-67-gd6ae852
DB Schema | 207
PHP | 7.0.22
MySQL | 5.5.52-MariaDB
RRDTool | 1.4.8
SNMP | NET-SNMP 5.7.2 

We noticed that Observium have features in getting sensor data for the device (temperature, humidity, etc) it would be better if these features were applied to LibreNMS also.

**Comment by laf** [comment]
What sensors are you expecting from this? from the data you've given I can only see:

.1.3.6.1.4.1.17095.3.1.0 = STRING: "24thBR"
.1.3.6.1.4.1.17095.3.5.0 = STRING: "24thWaterlCheck"
.1.3.6.1.4.1.17095.3.9.0 = STRING: "24thTemp-Front"
.1.3.6.1.4.1.17095.3.13.0 = STRING: "24thHumid2"

Not that 24thBR really says what that one is.

**Comment by jayceeemperador** [comment]
>> .1.3.6.1.4.1.17095.3.1.0
This is always the Main Sensor's Internal Temperature Description
>> .1.3.6.1.4.1.17095.3.2.0
This is the Main Sensor's Internal Temperature Value

The other strings are the readings from the external probes ( if have ) starting from 
 .1.3.6.1.4.1.17095.3.5.0 to .1.3.6.1.4.1.17095.3.20.0

If the second to the last number is odd, its the description and if its even, the value

In observium, it usually gets the keyword in its description then translate the value to the correct unit.

**Comment by laf** [comment]
Submitted PR to give temp and humidty.

![image](https://user-images.githubusercontent.com/3941142/32188168-fb6b8e60-bd9e-11e7-8406-65c8f04f7204.png)

If you need anymore please be more specific as the MIB doesn't list what possible sensors can be used.
