### ISSUE TITLE
#707 Breaks Existing LDAP Installs

### ISSUE THREAD

**Issue by supertylerc** [librenms/librenms#739]
#707 may break existing LDAP installs.  It did for me.  Below is the relevant section of config.php:

```php
# Authentication
$config['auth_mechanism'] = 'ldap';
$config['auth_ldap_server'] = 'ldap.example.com';
$config['auth_ldap_prefix'] = 'uid=';
$config['auth_ldap_suffix'] = ',ou=people,dc=example,dc=com';
$config['auth_ldap_groupbase'] = "ou=groups,dc=example,dc=com";
$config['auth_ldap_groups']['administrators']['level'] = 10;
```

The UI reports that authentication failed, but I'm unable to find messages in the logs to indicate why.  I haven't reviewed #707 yet to determine which part of commit 49babf7 broke my LDAP authentication.  I'll investigate and attempt to determine the cause.

**Comment by laf** [comment]
That's odd, reading through the code again and the only place it could change the way it works for existing connections is if someone has $config['auth_ldap_groupmembertype'] set but this isn't currently used shouldn't affect anything.

If you need to roll this change back then feel free and we can work something out with @Ultra2D.

The ldap code does need a rework in general :(

**Comment by supertylerc** [comment]
I've reset to the commit prior to this one and have disabled automatic updates until the issue is fixed.  The lack of verbosity/logging makes it difficult to narrow down.  I may add logging locally, set my rev to 49babf7, and debug the issue locally.

**Comment by Ultra2D** [comment]
Could you try removing '===true' from lines 100 and 157 of html/includes/authentication/ldap.inc.php ? Or adding them locally to commit https://github.com/librenms/librenms/commit/49babf77b86dda682fe1bf3a18c58d4c94de4bee ?
If that works, please run  ldapcompare  -x -h <host> "$config['auth_ldap_group']" memberUid:username from a shell. In my case that will return TRUE for a valid user, and UNDEFINED for an undefined attribute (change memberUid to randomstring). UNDEFINED actually equals to true (unless you add the '==='), which is not really secure.

**Comment by supertylerc** [comment]
Removing `===true` from lines `123` and `157` resolves the issue.  There's no `===true` on line `100`.


`$config['auth_ldap_group']` is not defined in my configuration.  `$config['auth_ldap_groups']` is.  I'm assuming you wanted a response with one of the defined groups in that array.

Also, for the reference of anyone else who comes across this: see below for the actual syntax for running the command as the one suggested above was missing key elements.

```
# ldapcompare -x -h ldap.example.com "cn=admin,ou=groups,dc=adap,dc=tv" memberUid:tyler
TRUE
```

**Comment by supertylerc** [comment]
I just pulled all changes.  I'm even with master (as of this writing), but I've removed the `===true` code from lines `33` and `157`.  Authentication is working again.

**Comment by supertylerc** [comment]
Adding some debugging code reveals that the PHP's `ldap_compare` function is returning -1, which is an error.  I'll dig into this more soon.

**Comment by Ultra2D** [comment]
If `$config['auth_ldap_group']` is not defined, you should not be able to authenticate at all. It is used by `ldap_compare` on line 33. This would correspond to 
`ldapcompare -x -h ldap.example.com "" memberUid:tyler`

`$config['auth_ldap_groups']` is an array to define user levels. Very confusing indeed. Even more so because Observium is using an array in stead of a string for `$config['auth_ldap_group']`.

Anyway, this is how I interpret the code. I could be wrong of course.

**Comment by supertylerc** [comment]
This is the result of `$config['auth_ldap_group']` containing the wrong data.  The current tests do not allow for multiple groups for authentication, which should be allowed.  If I have two groups, `users` and `admins`, I should be able to authenticate differently based on them.  This is working prior to #707 with the following directives (which are displayed in `defaults.inc.php`):

```php
$config['auth_ldap_groupbase'] = "ou=group,dc=example,dc=com";
$config['auth_ldap_groups']['admin']['level'] = 10;
$config['auth_ldap_groups']['pfy']['level'] = 7;
$config['auth_ldap_groups']['support']['level'] = 1;
$config['auth_ldap_groupmemberattr'] = "memberUid";
```

However, the new authentication code only works for one group specified in `$config['auth_ldap_group']`.  I do not use that configuration item because I prefer multiple levels of configuration.

**Comment by f0o** [comment]
Could you paste us a diff or PR the patch?

**Comment by supertylerc** [comment]
`config['auth_ldap_groups']` should be iterated through for authentication.  Observium may do it one way, but this isn't Observium and the way that it's currently done is not confusing.  It also requires you to have a specific group of which all users must be a member in order to authenticate--I don't see a reason to have an additional group solely for authentication if I'm going to use different groups entirely to handle authorization.  Authentication and authorization go hand-in-hand.

**Comment by supertylerc** [comment]
@f0o I can start working on the PR.  I'll try to ensure that I don't break current compatibility.

**Comment by f0o** [comment]
@supertylerc :+1:

**Comment by Ultra2D** [comment]
Iterating the groups sounds fine be me.

**Comment by Ultra2D** [comment]
Could you please try to include `===true`?

**Comment by supertylerc** [comment]
I'm leaving existing code in tact.  It will just iterate `$config['auth_ldap_groups']` if `$config['auth_ldap_group']` is set to the default (which is `cn=groupname,ou=groups,dc=example,dc=com`, a non-functional default).

**Comment by supertylerc** [comment]
See PR #749 for the fix.
