### ISSUE TITLE
skip host for autodiscover

### ISSUE THREAD

**Issue by zunder1990** [librenms/librenms#740]
I have hosts all of the network that dont have SNMP on them. I have arp autodiscover and would like a page that shows all hosts that failed to be added by autodiscover. This would allow me to look at the list and fix snmp on hosts that sould be working or exclude for future  autodiscover. This can start as a simple list on the config.php file but would love to see something in the webUI that show and allow for changes.

**Comment by f0o** [comment]
Should be possible with gui. I'll have a look later today.

**Comment by paulgear** [comment]
The data is already in the event log - just use the search to look for "ARP discovery of".

**Comment by laf** [comment]
I've got a relatively simple fix for this.

We have the ability to force add a device so icmp / snmp isn't checked at the time. We could add a config option which is disabled by default, if enabled any devices that don't exist in the db already will be added.

Pros: Small amount of code needed.
          No additional table needed.

Cons: Won't care what it finds so you could end up with a load of devices that you never want to add.
           Could slow polling down slightly if a lot of devices get added that can't be polled due to bad snmp.

Thoughts?
