### ISSUE TITLE
Edce-Core (EdgeCOS) switches - rename the interface name

### ISSUE THREAD

**Issue by kamils85** [librenms/librenms#7401]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 1.31.03-71-gf24c840
DB Schema | 207
PHP       | 7.0.15-0ubuntu0.16.10.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.10.1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Can we change the name of the interfaces? At present the name of the ethernet interface says Port1, Port2, etc.

I would like them to be: Ethernet 1/1, Ethernet 1/2, etc. as the switch sees them.

![image](https://user-images.githubusercontent.com/23239006/30963698-b9023790-a44e-11e7-921e-eeaad2537aa9.png)

![image](https://user-images.githubusercontent.com/23239006/30963739-e1d5f08a-a44e-11e7-9e68-a3eb0163a1ea.png)

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
