### ISSUE TITLE
Cisco WAP121 discovered as linux server

### ISSUE THREAD

**Issue by tukezor** [librenms/librenms#7402]
Cisco WAP121 devices are discovered as linux intead of ciscowap os.
includes/definitions/ciscowap.yaml contains:
discovery:
    - sysObjectId:
        - .1.3.6.1.4.1.9.6.1.32.321.1
    - sysDescr:
        - 'Cisco Small Business WAP'

I believe the sysObjectId is Cisco WAP321 device's. SysObjectId of WAP121 is: .1.3.6.1.4.1.9.6.1.32.121.1
WAP121 sysDescr: Linux 2.6.21.5-lvl7-dev, Cisco Systems, Inc WAP121 (WAP121-E-K9), Version 1.0.6.5 Wed Oct 12 07:42:51 EDT 2016

For testing purposes I changed the sysObjectId in the ciscowap.yaml file and the WAP121 devices were discovered as ciscowap instead of linux

Validation: https://p.libren.ms/view/408134d8
Discovery: https://p.libren.ms/view/68fd8264
Poller: https://p.libren.ms/view/181610b1
snmpbulkwalk: https://p.libren.ms/view/c85bff70

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
So I've submitted a PR to fix this (please take a look). We seem to have another os called `ciscosmblinux` which detected these as well. That seems to just to be a duplicate so I've removed that one.

**Comment by tukezor** [comment]
Seems to be working correctly now. Thanks!
There is one typo though:  text: 'Cisco Wireless _Acess_ Point'
