### ISSUE TITLE
Configurable 95th percentile 

### ISSUE THREAD

**Issue by laf** [librenms/librenms#7406]
https://community.librenms.org/t/98th-percentile-graphs/2231

This should be a simple case of replacing all occurrences of `95,PERCENT` in html/includes/graphs/ with a user configurable config option like `$config['percentile_value']` and adding it to `doc/Support/Configuration.md`

**Comment by yunchih** [comment]
Hi, I can try taking this.

**Comment by laf** [comment]
Thanks. Give us a shout if you need any help

**Comment by yunchih** [comment]
`95,PERCENT` is always accompanied by a label, like the `95thin` in:
```
html/includes/graphs/generic_multi_bits.inc.php, 56:
$rrd_options .= ' VDEF:95thin=inbits,95,PERCENT';
```

Shall we rename those labels to `percent_thin`, `percent_thout`, etc?  Or just keep it as it is and replace `95,PERCENT` only?

**Comment by murrant** [comment]
You could change the labels to be more consistent.  Let me suggest `percentile_in` and `percentile_out`.
