### ISSUE TITLE
feature request: show ports with errors

### ISSUE THREAD

**Issue by zunder1990** [librenms/librenms#741]
Right now under ports you can show all ports that are disabled or down. I would like to see another one that would show all ports that are having errors.

**Comment by f0o** [comment]
Easy thing, will be PR'd today.

**Comment by zunder1990** [comment]
Thank you

**Comment by f0o** [comment]
Just to be clear here, you want ports that have errors, regardless of when they got picked up ?
Or do you want to have those ports that have just gotten errors within the last poll-cycle ?
Do you want a differentiation between incoming and outgoing errors ?

**Comment by f0o** [comment]
Update: if you only want to see errors from the last poll-cycle without caring about incoming or outgoing, then check `/ports/errors=1/` :)

**Comment by f0o** [comment]
Give me a hit if `/ports/errors=1` is not enough :)

**Comment by zunder1990** [comment]
/ports/errors=1 works for me

**Comment by f0o** [comment]
Thats good, will PR the link after breakfast

**Comment by f0o** [comment]
@zunder1990 set `$ports['errored'] = 1` in the config to get the link :)
