### ISSUE TITLE
Add Palo Alto MIBs and Better Support

### ISSUE THREAD

**Issue by mrjester888** [librenms/librenms#7411]
[PAN OS Discovery](https://p.libren.ms/view/9f9f47c5)
[PAN OS Poller](https://p.libren.ms/view/d27f5785)
[PAN OS SNMP Walk](https://p.libren.ms/view/54fd7ab9)

[Details about supported MIBs](https://www.paloaltonetworks.com/documentation/80/pan-os/pan-os/monitoring/supported-mibs)

[MIBS Attached Here: PAN-MIB-MODULES-8.0.zip](https://github.com/librenms/librenms/files/1346484/PAN-MIB-MODULES-8.0.zip)

The following OIDs should be setup as system graphs.  They show dataplane load.

.1.3.6.1.2.1.25.2.3.1.3.1010 = STRING: Slot-1 Data Processor-0 Packet Descriptors
.1.3.6.1.2.1.25.2.3.1.3.1011 = STRING: Slot-1 Data Processor-0 Hardware Packet Buffers
.1.3.6.1.2.1.25.2.3.1.3.1012 = STRING: Slot-1 Data Processor-0 Software Packet Buffers
.1.3.6.1.2.1.25.2.3.1.3.1110 = STRING: Slot-1 Data Processor-1 Packet Descriptors
.1.3.6.1.2.1.25.2.3.1.3.1111 = STRING: Slot-1 Data Processor-1 Hardware Packet Buffers
.1.3.6.1.2.1.25.2.3.1.3.1112 = STRING: Slot-1 Data Processor-1 Software Packet Buffers
.1.3.6.1.2.1.25.2.3.1.3.1210 = STRING: Slot-1 Data Processor-2 Packet Descriptors
.1.3.6.1.2.1.25.2.3.1.3.1211 = STRING: Slot-1 Data Processor-2 Hardware Packet Buffers
.1.3.6.1.2.1.25.2.3.1.3.1212 = STRING: Slot-1 Data Processor-2 Software Packet Buffers
.1.3.6.1.2.1.25.2.3.1.4.1010 = INTEGER: 128
.1.3.6.1.2.1.25.2.3.1.4.1011 = INTEGER: 2048
.1.3.6.1.2.1.25.2.3.1.4.1012 = INTEGER: 5941
.1.3.6.1.2.1.25.2.3.1.4.1110 = INTEGER: 128
.1.3.6.1.2.1.25.2.3.1.4.1111 = INTEGER: 2048
.1.3.6.1.2.1.25.2.3.1.4.1112 = INTEGER: 7173
.1.3.6.1.2.1.25.2.3.1.4.1210 = INTEGER: 128
.1.3.6.1.2.1.25.2.3.1.4.1211 = INTEGER: 2048
.1.3.6.1.2.1.25.2.3.1.4.1212 = INTEGER: 7173

**Comment by laf** [comment]
What is this data representing?

**Comment by mrjester888** [comment]
In the case of this output, a PA-5000 series, there are 3 data planes which do the pushing of packets.  Packet Descriptors are the pieces that break packets apart for processing.  Buffers are just that.  Too high of utilization in either can lead to serious performance issues.

**Comment by laf** [comment]
We don't have support for recording this information so I think you'll have to post this as a feature request on the community site.
