### ISSUE TITLE
Running LibreNMS in a subdirectory preventing automatic updates

### ISSUE THREAD

**Issue by markuspachali** [librenms/librenms#7412]
Hi all,

I have a little trouble running LibreNMS in a subdirectory. I've followed the following guide to run LibreNMS in a subdirectory of my server:
https://docs.librenms.org/Extensions/Sub-Directory/

That results in not working updated:

bash-4.2$ git pull
Updating edc1368..592e8ac
error: Your local changes to the following files would be overwritten by merge:
	html/.htaccess
Please, commit your changes or stash them before you can merge.
Aborting
bash-4.2$

[root@monitor01 librenms]# ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.31.03-78-g592e8ac
DB Schema | 209
PHP       | 5.4.16
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  Your local git contains modified files, this could prevent automatic updates.
Modified files:
	 html/.htaccess
[FAIL]  Discovery has not completed in the last 24 hours, check the cron job
[root@monitor01 librenms]#

Is this a bug or a feature?

Best regards,
Markus

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by murrant** [comment]
@markuspachali The **warning** is correct.  The change to .htaccess **could** block updates.  If a change is made upstream to .htaccess, it would block updates, but we don't update that file often.  You now get an alert in the app if updates are failing, so you don't even have to baby-sit it really.
