### ISSUE TITLE
Wrong values with HP iPDU

### ISSUE THREAD

**Issue by csirek** [librenms/librenms#7417]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

**Component | Version
--------- | -------
LibreNMS  | 1.32
DB Schema | 209
PHP       | 7.0.8-0ubuntu0.16.04.1
MySQL     | 10.0.25-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

[OK]    Database connection successful
[OK]    Database schema correct
[FAIL]  You have a different system timezone (BST) specified to the php configured timezone (UTC), please correct this.**
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
**https://p.libren.ms/view/9c9af0d8**
**https://p.libren.ms/view/f85b5471**
**https://p.libren.ms/view/08e9144d**

- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Here is two pictures about the problem 
This is the HP GUI: https://ibb.co/mMGDyw
This is the LibreNMS: https://ibb.co/iUNsrG

The problems are:
1: Power box: this values are the "mpduOutputPowerFactor.1.3 = 98" and divided by 100. So please rename this box to Power Factor
2: Load box: Need to divide by 10 this values to get the real load in every segment.
3: Would be nice a "Power usage" box with (Voltage * Current) values, in VA or Watts. Ok, it is a feature request... :)

**Comment by murrant** [comment]
What is mpduOutputPowerFactor?  That doesn't seem right as power is generally in watts, but this seems to be a percent.

**Comment by csirek** [comment]
I think it is the "kW = kVA * power factor". So it is the efficiency of the electrical system.
