### ISSUE TITLE
Geist Watchdog - Temp Unit Conversion Incorrect

### ISSUE THREAD

**Issue by bakerds** [librenms/librenms#7419]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

```
Component | Version
--------- | -------
LibreNMS  | 1.32-1-g738067e
DB Schema | 209
PHP       | 5.5.9-1ubuntu4.22
MySQL     | 5.5.57-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2
```

- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
[poller](https://pastebin.com/R9HrBqRK)
[discovery](https://pastebin.com/sJCFJmyr)
[snmpwalk](https://pastebin.com/2HPADj6v)

- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

There is an issue when the Geist Watchdog is configured in Fahrenheit mode. The SNMP temperature value uses a unit of 0.1 degrees. The Fahrenheit to Celsius conversion happens before the value is converted from tenths of a degree to degrees.

For example,
Real temp : 66.9 F
SNMP value : 669
Graphed value : 35.4 C  (669 F = 354 C)
Correct value : 19.4 C  (66.9 F = 19.4 C)

This can be solved by either
- divide by 10 before converting from F to C
- convert back to F, divide by 10, convert to C again

Thanks!
Dan

**Comment by kkrumm1** [comment]
I had the same issue but it seemed to work after I updated my watchdog.

http://www.geistglobal.com/products/monitor/environmental-monitors/watchdog-100-100-P#

**Comment by laf** [comment]
I'm not sure what we can do about this at present. The code that runs the c -> f conversion is run before the divisor / multiplier as a lot of vendors don't return numerical data so we have to do some parsing first.

Ideally we'd use the callback function we have in place but I don't see that working right now :(
