### ISSUE TITLE
AFTER Update - no visible on dashboards old alert on warning unaknowledged

### ISSUE THREAD

**Issue by laurianemartin** [librenms/librenms#7438]
Hello,

This morning on a dashboard, in the widgets 'alerts', i can't see the old alert on warning unaknowledged.
I show this alert on my device, in alert tab.
I can show the aknowledge alert new and old (critical and warning) +  i can show the new alert on warning unaknowledged.
I have checked my config on my widget it's ok.

Could you help me please?

Version | 1.32-14-ga2b9342 - Thu Oct 05 2017 23:04:17 GMT+0200
-- | --
DB Schema | #210
Web Server | Apache/2.4.7 (Ubuntu)
PHP | 5.5.9-1ubuntu4.19
MySQL | 5.5.50-0ubuntu0.14.04.1
RRDtool | 1.4.7

-----------------
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by kkrumm1** [comment]
What version of LibreNMS are you on?

**Comment by laurianemartin** [comment]
My version is 1.32 (2017-10-01)

**Comment by murrant** [comment]
What authentication method do you use?

Is it AD, did you see this? https://community.librenms.org/t/active-directory-base-dn/2247

**Comment by laurianemartin** [comment]
Is'nt AD, i'm create user manually.
I have do an error, I can't see the alert on the device, in alert tab when this alert is on warning unaknowledged

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by laurianemartin** [comment]
Hello,
I'm don't understand why this issue is closed : 
The problem is only since the upgrade. And only the new alerts are displayed the old alerts aren't display on my dashboard and on my device alerts tab.
Before the upgarde all work fine, and all my alerts are displayed so it's a bug.
Thanks in advance,
