### ISSUE TITLE
Increase Memory Processor IOS Devices

### ISSUE THREAD

**Issue by thoms27** [librenms/librenms#7449]
Hello,

Since I added Cisco IOS devices in librenms, my Memory Processor increase. Above 80% I can't connect me on the device (see below).
![2017-10-09 10_42_01-librenms](https://user-images.githubusercontent.com/20238377/31330402-9181e858-acde-11e7-96ba-e40f8725a240.png)

Cisco Device : 
WS-C3750G-24TS-1U (IOS c3750-ipservices-mz.122-25.SEE2)

Can you help me please ?

Regards,

Thomas V.

**Comment by thoms27** [comment]
Hi,

To complete, It's seem to be a leak of memory : 
sh memory dead totals
                Head    Total(b)     Used(b)     Free(b)   Lowest(b)  Largest(b)
Processor    207DD24    87929564    56503652    31425912    30175128    30926352
      I/O    7400000    12574720     8417344     4157376     4001584     4149576

Dead Proc Summary for: Processor
    PC          Total  Name
0x004D3040        506  hulc_flash init

Regards

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
