### ISSUE TITLE
MySQL Error: Unknown column

### ISSUE THREAD

**Issue by arunkr1** [librenms/librenms#7451]
librenms@nmsdb:~$ ./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 1.32-16-gc927e6d
DB Schema | 210
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Database connection successful
[FAIL]  Database: missing column (component_statuslog/component_id)
[FAIL]  Database: extra column (component_statuslog/component)
[FAIL]  Database: incorrect index (component_statuslog/device)
[FAIL]  We have detected that your database schema may be wrong, please report the following to us on IRC or the community site (https://t.libren.ms/5gscd):
	 ALTER TABLE `component_statuslog` ADD `component_id` int(11) unsigned NOT NULL DEFAULT 'NULL';
	 ALTER TABLE `component_statuslog` DROP `component`;
	 ALTER TABLE `component_statuslog` DROP INDEX `device`, INDEX `device` (`component_id`);
*****
after performing above suggestion getting following error:
logs/librenms.log:2017-10-08 17:55:48 MySQL Error: Unknown column 'component' in 'field list' (INSERT INTO `component_statuslog` (`component`,`status`,`message`)  VALUES ('2088','0',''))

Also having following error in librenms.log
2017-10-09 17:25:32 MySQL Error: Unknown column 'storage.device_size' in 'where clause' (SELECT * FROM storage WHERE (storage.device_id = '2') && (storage.device_size > 80 ))

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
