### ISSUE TITLE
shorthost Target Length is hardcoded

### ISSUE THREAD

**Issue by jof** [librenms/librenms#7452]
# Boilerplate
Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

```
==========================================================
Component | Version
--------- | -------
LibreNMS  | 9009633392f219e01173bd26f1c01b7cf55e6b34
DB Schema | 209
PHP       | 7.0.18-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================
```

# Summary
The `shorthost` function defined in `includes/common.php` enables a variable target length of the short hostname. However, very few to no calls actually set different target lengths.
And importantly, the target length is not a setting exposed to end users.

In our environment, we have some names like router1.long-ish-site-name2.OUR.TLD
While we have many sites with different "router1" hosts. This kind of breaks some of the port_bits graphs, as they all show "router1" as the title.
For some of our longer site names, we would like to get these included in the graph title to make things clear.

# Proposal
We define a new configuration parameter in the global $config array which sets a user-desired target `shorthost` length.
Then, inside of `function shorthost()` we check for this desired length being set, as if so, use that as the target length.

**Comment by laf** [comment]
PR open so closing this.
