### ISSUE TITLE
Differentiate between SNMP down and host down in alert and/or UI

### ISSUE THREAD

**Issue by barryodonovan** [librenms/librenms#7455]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by barryodonovan** [comment]
Not sure where to put the issue! ;-)

-----------------------------------------------
 I was going to add this as a comment to https://github.com/librenms/librenms/pull/7323 but it actually feels like its own issue.


It would be useful to be able to alert on a host that SNMP did not respond but that ICMP is still OK, ie host is not down, just somewhat unresponsive. 

I have many (wireless AP) hosts which don't always respond correctly to SNMP, eg the daemon crashes, but the host continues to pass wireless traffic perfectly well and can be rebooted overnight. I don't need to treat this as a host down event, but I am currently unable to differentiate between SNMP down and host down either on the UI or in alerts.

**Comment by kkrumm1** [comment]
barryodonovan,

here is what I did as a workaround I turned off the default rule device up/down and made a new alert rule like this.  (im not a big fan of that default alert rule its confusing and misleading) anyway, see blow for example...

%macros.device_down = "1" && %devices.status_reason = "icmp"

this rule will only send out alert if the device cant be pinged anymore. 

-Kev

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
