### ISSUE TITLE
Feature Request: add support for powercode bmu and procera traffic shaper

### ISSUE THREAD

**Issue by Lonecrowe** [librenms/librenms#746]
Add Powercode BMU (Router) and Procera Packetlogic Traffic Shaper detection. 

Both are already detected as linux machines and all the pertinent information is already being graphed.  CPU and interface stats etc.  More info can be added later but for now if you could just add the icons for each in the detection instead of a ? icon that would be great.....

www.powercode.com  you can use their little infinity symbol. 
http://www.proceranetworks.com you can use the O in procera as the icon.

**Comment by laf** [comment]
I assume they are just Linux boxes anyway? We'd need an snmpwalk to see what can be used to detect these or access via snmp. Can yo provide these?

**Comment by Lonecrowe** [comment]
For the Powercode BMU it uses its own fork of openwrt I believe. 
The enterprises section  its pretty empty http://pastebin.com/GHpxmfSG
Most of it is all the standard IF-MIB as well as the RFC-1213 stuff.
Pastebin of just the first of the standard walk information.  http://pastebin.com/6ynPaNjG
It literally lists every IP of every device under its arp entries and all the standard stuff.  

Like I said it already works.  Just need to slap an icon on this one.

**Comment by Lonecrowe** [comment]
For the PDU that I use here is the walk of the enterprises section 

http://pastebin.com/sqjX1kJ5

Oddly enough the OID being used works for the current but nothing else.

**Comment by Lonecrowe** [comment]
Procera regular walk of the basic stuff give you this 
http://pastebin.com/Xhahm7ST

The enterprises material is quite extensive and over 8KB worth of text.  Lets just start with this.

**Comment by Lonecrowe** [comment]
Powercode detection is in now - thanks you.  
Just need the exact same for Procera.

**Comment by f0o** [comment]
Reopening as procera is not included yet

**Comment by laf** [comment]
@Lonecrowe Do you have the PACKETLOGIC-MIB available and if so can you pass it on please. The procera will be detected as a Linux box so we need to grab something else to identify it.

**Comment by laf** [comment]
PR done now #773.

@Lonecrowe feel free to give this a try.

**Comment by Lonecrowe** [comment]
Emailing you the Packletlogic MIBs.
