### ISSUE TITLE
way TOO many requests to ldap server

### ISSUE THREAD

**Issue by jerrybailie** [librenms/librenms#7468]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
====================================
Component | Version
--------- | -------
LibreNMS  | 1.32-25-gea79515
DB Schema | 210
PHP       | 7.0.18-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.

We use ldap authentication and for a about a week now, we've been getting the following requests to our LDAP server:

`conn=1242 op=2012 CMP dn="cn=admin,ou=Group,dc=#,dc=#,dc=#" attr="memberUid`

There are a few different cn's requested, not the entire directory, but only a handful: support, admin, pfy..

**Here's the kicker**: Each time it does a request, it repeats for 100's of times, creating 5000+ lines of requests on the LDAP server, and... at a frequency of every few minutes, essentially flooding the disk after a time.

Yea, I've increased the disk size on the LDAP server (it's a VM) and also increased the syslog rotation frequency, but there's obviously something curious going on here.

- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
