### ISSUE TITLE
Poller cannot connect to MySQL via Unix socket

### ISSUE THREAD

**Issue by ZedTheYeti** [librenms/librenms#7469]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.32-26-g3381b40
DB Schema | 210
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

I have set up a brand new LibreNMS instance on Ubuntu Server 16.04.3 LTS with MariaDB on the same host using Unix sockets for the two to communicate (with the below config)
```
$config['db_host'] = 'localhost';
$config['db_port'] = '3306';
$config['db_name'] = 'librenms';
$config['db_socket'] = '/var/run/mysqld/mysqld.sock';
```

validate.php connects to the database fine and so does everything else except poller-wrapper.py. The error information given by poller-wrapper.py is simply "ERROR: Could not connect to MySQL database!". However, editing poller-wrapper.py to actually print the exception info reveals the following traceback and more helpful error message "Unknown MySQL server host '/var/run/mysqld/mysqld.sock'".
```
Traceback (most recent call last):
  File "/opt/librenms/poller-wrapper.py", line 207, in <module>
    db = db_open()
  File "/opt/librenms/poller-wrapper.py", line 97, in db_open
    db = MySQLdb.connect(host=db_server, user=db_username, passwd=db_password, db=db_dbname)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2005, "Unknown MySQL server host '/var/run/mysqld/mysqld.sock' (0)")
```

Looking into [MySQLdb python documentation](http://mysql-python.sourceforge.net/MySQLdb.html), `_mysql.connect()` expects the hostname when connecting, even via unix socket. However, poller-wrapper.py is supplying the path to the socket instead. This change was added in commit b1a414e7858dc9ca4adbf18bae7fb254dfd6a58f
```
if config['db_host'][:5].lower() == 'unix:':
    db_server = config['db_host']
    db_port = 0
elif config['db_socket']:
    db_server = config['db_socket']
    db_port = 0
else:
    db_server = config['db_host']
```

Changing poller-wrapper.py to supply the hostname when `db_socket` is configured fixes this issue. I'm not sure what should be done about the fist if case as it's checking for if `db_host` is set to a unix socket, however this isn't supported by the rest of LibreNMS in my testing.
```
if config['db_host'][:5].lower() == 'unix:':
    db_server = config['db_host']
    db_port = 0
elif config['db_socket']:
    db_server = config['db_host']
    db_port = 0
else:
    db_server = config['db_host']
```

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Please submit a PR with the fix.

**Comment by ZedTheYeti** [comment]
Submitted #7471

**Comment by murrant** [comment]
This isn't correct.  The reason it works is the mysql library tries to connect to standard socket location first.  However, if the socket is in a non-standard location.  It will not work.

This should set the variable `unix_socket` for the mysql connection, I think.

**Comment by ZedTheYeti** [comment]
That is correct, the PR I submitted only fixes cases where the default socket path is used, not the case for non-standard paths (thought it looks to me like neither were working previously). My aim with the PR was to change as little as possible, as I'm not a regular contributor to the project and do not know the codebase. I'll change the PR to explicitly set the `unix_socket` when I have time.

**Comment by Duffyx** [comment]
Is this fixed yet? I'm having trouble connection too my database with de python poller wrapper using non default socket location. I'm on FreeBSD and I get a the exact same error: ERROR: Could not connect to MySQL database!

**Comment by ZedTheYeti** [comment]
@Duffyx It is indeed a bug, pull request #7471 is currently open to fix it.

**Comment by ZedTheYeti** [comment]
This is working for me after PR #7471 was merged.

@Duffyx can you make sure your LibreNMS install is up to date and see if it's fixed for you?

**Comment by Duffyx** [comment]
Its fixed, thanks!
