### ISSUE TITLE
Alert Rules - OR glue missing?

### ISSUE THREAD

**Issue by Tatermen** [librenms/librenms#7479]
When creating an alert rule, there's two types of glue ```&&``` (AND) and ```||``` (OR). I've added rules in the past that used OR, but now I can't see how. Clicking add defaults to an AND glue.

Am I going mad, or missing something obvious?

**Comment by murrant** [comment]
OR was badly broken, so we had to remove it.

If you need OR, you will need to use macros for now.

**Comment by laf** [comment]
If you would like to use OR in alert rules still. We have a new UI for you to test: https://github.com/librenms/librenms/pull/8293
