### ISSUE TITLE
check-services.php shows invalid option -- 'H' while using Nagios plugin check_disk

### ISSUE THREAD

**Issue by thangnguyennang** [librenms/librenms#7492]
**Steps:**
* Go to menu Services > Add Service.
* At box Device: choose "localhost" (note: localhost is host that installed LibreNMS).
* At box Type: choose "disk".
* At box Description: None.
* At box IP Address: None.
* At box Parameters: "-w 100000 -c 50000 -p /".
* On host LibreNMS, run the check check-service.php.

**Result on terminal:**
It shows the error: /usr/local/nagios/libexec/check_disk: invalid option -- 'H'

**My environment:**
* OS: CentOS 7.x
* LibreNMS: 1.32
* Nagios plugins: installed from source.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
