### ISSUE TITLE
GEIST Watchdog 15 does not get temperature and humidity

### ISSUE THREAD

**Issue by luigirosa** [librenms/librenms#7495]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.32-45-g1318e58
DB Schema | 210
PHP       | 7.1.10
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

LibreNMS does not collect temperature and humidity of GEIST Watchdog 15, it collects just uptime, eth traffic using SNMP v1/v2c

The hardware is:
Model: GEIST Watchdog 15
Device type BB-TH-P
Firmware version 3.3.2

The MIB that can be downloaded from the device is the same as librenms/mibs/geist/GEIST-V4-MIB

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by luigirosa** [comment]
Sorry about that, hre's the info

discovery: https://p.libren.ms/view/5b481375
poller: https://p.libren.ms/view/62f76474
snmpwalk: https://p.libren.ms/view/2599646b

**Comment by luigirosa** [comment]
As far as I can see from the output of snmpbulkwalk there are no environment data, very strange.
Tried to reset the device and no result.
Probably a device issue, you can leave this case closed.

**Comment by kkrumm1** [comment]
@luigirosa 

download the newest firmware this is a bug with the watchdog. update to 3.3.3

See here -> http://www.itwatchdogs.com/s_firmware_watchdog100
