### ISSUE TITLE
Alerts-Table Should Show Port Names

### ISSUE THREAD

**Issue by supertylerc** [librenms/librenms#750]
Right now, the alerting system does not display the port/interface name/number when it alerts.  You only see a very generic "Port utilisation over threshold", for example.  The alerting system knows about the actual port number, though, because when I receive the notification via one of the transports the port number is included.

The `/alerts/` page should also show the port name/number along with a link to that port's graphs.

**Comment by laf** [comment]
So this is (secretly) in there, if you hover over hostname it will give you the triggers of that alert (hover over the rule and it will show the rule syntax). Happy to take suggestions on how else to show it, maybe a separate clickable link of some form?

**Comment by supertylerc** [comment]
Sneaky!  Thanks for the pointer!  So armed with that, it also helps explain something else I've been trying to puzzle out: where there's only ever one alert in the list.  I guess the alerting system aggregates them instead of giving each alert its own entry.  And now it makes much more sense on why there's no list of affected ports without hovering over the hostname.

Did I miss this explanation in the docs, or is it just a secret feature?

**Comment by laf** [comment]
I don't think that's anywhere in the docs as we don't have any on Web UI use really - probably should!

But yes if you create a rule that says show all ports down on a device, then it will collate the list of ports down and send one alert. If that's something that needs looking at then @f0o can comment further.

**Comment by supertylerc** [comment]
No, I think aggregating alerts is preferable.  Spam is bad.  :)  What I'm really after is an alternative view of the alerts--one that disaggregates the alerts and has some (minor) additional detail.  Perhaps that wouldn't need to be the default view.  Keep the current view, then have a button for "detailed alerts," where each alert gets disaggregated and inserted into its own row.

**Comment by laf** [comment]
@supertylerc Something along the lines of:

http://pasteboard.co/2oUy3R0o.png

Ignore the crappy html, that can be tidied up.

**Comment by supertylerc** [comment]
@laf yes, except obviously some of those should be on the same line/don't matter.

**Comment by f0o** [comment]
The title is a bit confusing as you dont mean the Alerting System but merely the GUI-table. Always get a heartattack when I read through the open issues heh

**Comment by laf** [comment]
What about something as simple as this @supertylerc. Could easily have a button to enable additional info to see this view.

![image](https://cloud.githubusercontent.com/assets/3941142/7102297/93671538-e073-11e4-8b48-5bdd1ba8eb1f.png)

**Comment by supertylerc** [comment]
That looks good to me!

**Comment by laf** [comment]
PR in place now @supertylerc

**Comment by f0o** [comment]
Merged

**Comment by supertylerc** [comment]
The new additions to the alerts interface are slick!  Thanks, @laf and @f0o!
