### ISSUE TITLE
New Item - Geist Watchdog WD-1000

### ISSUE THREAD

**Issue by gstrike** [librenms/librenms#7502]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

------

Hey guys,

Here's another Geist model (WD-1000) .  It's being correctly detected as Geist, but it's not picking up on the Temperature/Humidity sensors.
```

====================================
Component | Version
--------- | -------
LibreNMS  | 1.32-50-g89ff05e
DB Schema | 211
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

```
Discovery.php - https://p.libren.ms/view/3939aa1a
Poller.php - https://p.libren.ms/view/550a7a1c
snmpbulkwalk - https://p.libren.ms/view/1f35e765

I'm not sure if the MIBs are the same as the WD-15/100's that are already in LIbreNMS, but the WD-1000 MIBs are included with the firmware download here:  http://www.geistglobal.com/supportfirmware-updates/monitor-firmware

Sincerely,
Greg

**Comment by laf** [comment]
The snmpwalk you've provided doesn't contain any data from .1.3.6.1.4.1.21239 which is what the MIB is using you linked to.

We already pull data in from that mib so if the device supported it then it would work. This might be one you need to check with the vendor on.

**Comment by gstrike** [comment]
Hi @laf,

Sorry to reopen this.  When I run the snmpwalk directly on the .21239 OID I do get results.

```
#snmpwalk -v2c -c [censored] 10.240.10.42 enterprises.21239
SNMPv2-SMI::enterprises.21239.2.1.1.0 = STRING: "RSMICRO"
SNMPv2-SMI::enterprises.21239.2.1.2.0 = STRING: "3.16.3"
SNMPv2-SMI::enterprises.21239.2.1.3.0 = STRING: "GS-ENV-02"
SNMPv2-SMI::enterprises.21239.2.1.4.0 = STRING: "00:19:85:E3:3C:91"
SNMPv2-SMI::enterprises.21239.2.1.5.0 = STRING: "http://10.240.10.42"
SNMPv2-SMI::enterprises.21239.2.1.6.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.7.0 = STRING: "GEIST"
SNMPv2-SMI::enterprises.21239.2.1.8.1.2.0 = INTEGER: 1
SNMPv2-SMI::enterprises.21239.2.1.8.1.3.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.4.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.5.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.6.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.7.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.8.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.9.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.10.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.11.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.12.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.13.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.14.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.15.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.16.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.17.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.18.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.19.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.20.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.21.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.22.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.23.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.24.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.25.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.26.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.27.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.28.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.29.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.30.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.31.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.32.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.33.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.34.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.8.1.35.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.1.9.0 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.2.1.2.1 = STRING: "012486B7140000C3"
SNMPv2-SMI::enterprises.21239.2.2.1.3.1 = STRING: "GS-ENV-02"
SNMPv2-SMI::enterprises.21239.2.2.1.4.1 = Gauge32: 1
SNMPv2-SMI::enterprises.21239.2.2.1.5.1 = INTEGER: 16
SNMPv2-SMI::enterprises.21239.2.2.1.6.1 = INTEGER: 61
SNMPv2-SMI::enterprises.21239.2.2.1.7.1 = INTEGER: 33
SNMPv2-SMI::enterprises.21239.2.2.1.8.1 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.2.1.9.1 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.2.1.10.1 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.2.1.11.1 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.2.1.12.1 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.2.1.13.1 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.2.1.14.1 = Gauge32: 0
SNMPv2-SMI::enterprises.21239.2.2.1.15.1 = Gauge32: 0
SNMPv2-SMI::enterprises.21239.2.2.1.16.1 = Gauge32: 0
SNMPv2-SMI::enterprises.21239.2.2.1.17.1 = Gauge32: 0
SNMPv2-SMI::enterprises.21239.2.2.1.18.1 = Gauge32: 0
SNMPv2-SMI::enterprises.21239.2.2.1.19.1 = Gauge32: 0
SNMPv2-SMI::enterprises.21239.2.2.1.20.1 = Gauge32: 0
SNMPv2-SMI::enterprises.21239.2.2.1.21.1 = Gauge32: 0
SNMPv2-SMI::enterprises.21239.2.2.1.22.1 = Gauge32: 0
SNMPv2-SMI::enterprises.21239.2.2.1.23.1 = Gauge32: 0
SNMPv2-SMI::enterprises.21239.2.2.1.24.1 = Gauge32: 0
SNMPv2-SMI::enterprises.21239.2.2.1.25.1 = Gauge32: 0
SNMPv2-SMI::enterprises.21239.2.2.1.26.1 = Gauge32: 0
SNMPv2-SMI::enterprises.21239.2.2.1.27.1 = Gauge32: 0
SNMPv2-SMI::enterprises.21239.2.2.1.28.1 = Gauge32: 0
SNMPv2-SMI::enterprises.21239.2.2.1.29.1 = Gauge32: 0
SNMPv2-SMI::enterprises.21239.2.2.1.30.1 = Gauge32: 0
SNMPv2-SMI::enterprises.21239.2.2.1.31.1 = INTEGER: 0
SNMPv2-SMI::enterprises.21239.2.2.1.32.1 = INTEGER: 32
```

Am I missing something?

~Greg

**Comment by laf** [comment]
No that's right. please provide that walk as indicated by the FAQ. We need it in the correct format.

**Comment by gstrike** [comment]
Hi @laf,

I followed the FAQ when creating the original pastebins above.  I was double checking them and noticed that the snmpwalk (https://p.libren.ms/view/1f35e765) does have the .21239 OID.  Is there something more I should be doing?

Greg

**Comment by murrant** [comment]
@gstrike `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .`  Is what you need to run.  The period at the end is important as that will make it include the .21239 oid ;)

**Comment by gstrike** [comment]
@murrant Thank you for that.  Here's a new paste: https://p.libren.ms/view/8fc2a3ac

**Comment by laf** [comment]
PR submitted, please give #7795 a try.

**Comment by gstrike** [comment]
@laf, I applied #7795 and it looks to be working well.  Thank you so much!  Please let me know if there's anything you'd like me to test.

**Comment by laf** [comment]
Nothing else needed, I've just added a unit test so will merge in once the tests complete.
