### ISSUE TITLE
Update - Ubiquiti UAP-AC-HD

### ISSUE THREAD

**Issue by W90W2A** [librenms/librenms#7504]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Unifi UAP-AC-HD devices on the latest stable firmware branch (3.9.x) have moved from tinysnmp to net-snmp.  This has come with a change to some OIDs.  Currently, the devices are being discovered as generic Linux servers, which is suboptimal, and none of wireless stats are populating.  Believe this also impacts UAP-AC-SHD.

Component | Version
--------- | -------
LibreNMS  | 1.32-52-g04bb65b76
DB Schema | 211
PHP       | 7.0.19-1
MySQL     | 10.1.23-MariaDB-9+deb9u1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

[discovery.php output](https://p.libren.ms/view/32b48a43)
[poller.php output](https://p.libren.ms/view/cd28c405)
[snmpwalk output](https://p.libren.ms/view/0b652d47)

Current MIBS
[UBNT-MIB](http://dl.ubnt-ut.com/snmp/UBNT-MIB)
[UBNT-Unifi-MIB](http://dl.ubnt-ut.com/snmp/UBNT-UniFi-MIB)

**Comment by murrant** [comment]
Oh, Ubiquiti.   Will they ever understand snmp?

sysObjectID is `.1.3.6.1.4.1.8072.3.2.10` the standard Linux sysObjectID and sysDescr is a generic `Linux HOSTNAME 3.14.77 #2 SMP PREEMPT Fri Oct 13 11:19:39 PDT 2017 armv7l`

We were previously using `dot11manufacturerName`  and  `dot11manufacturerProductName` to detect ubnt devices, but those return no data now.

So, either Ubiquiti will need to fix their snmp, or we have to find some way to identify them. @UBNT-cmb

See #6974

**Comment by UBNT-cmb** [comment]
The `dot11manufacturerName` and `dot11manufacturerProductName` returning empty was a bug in beta firmware for AC-HD and AC-SHD at the time. Those return as expected now. 

```
cmb@librenms:~$ snmpwalk -v1 -c public -Osqnv -m IEEE802dot11-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro:/opt/librenms/mibs/dell udp:achd.buechler.lan:161 dot11manufacturerName 
Ubiquiti Networks, Inc.
Ubiquiti Networks, Inc.
Ubiquiti Networks, Inc.
Ubiquiti Networks, Inc.
Ubiquiti Networks, Inc.
Ubiquiti Networks, Inc.
Ubiquiti Networks, Inc.
Ubiquiti Networks, Inc.
Ubiquiti Networks, Inc.
Ubiquiti Networks, Inc.
Ubiquiti Networks, Inc.
cmb@librenms:~$ snmpwalk -v1 -c public -Osqnv -m IEEE802dot11-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro:/opt/librenms/mibs/dell udp:achd.buechler.lan:161 dot11manufacturerProductName 
UAP-AC-HD
UAP-AC-HD
UAP-AC-HD
UAP-AC-HD
UAP-AC-HD
UAP-AC-HD
UAP-AC-HD
UAP-AC-HD
UAP-AC-HD
UAP-AC-HD
UAP-AC-HD
```

am I missing something? I don't generally work on UAP, but will pass along anything that might help to those who do.

**Comment by murrant** [comment]
@UBNT-cmb Sorry, I do see those are there, but the reason it isn't detected is:
First we check if sysObjectID is one of `.1.3.6.1.4.1.10002.1` or `.1.3.6.1.4.1.41112.1.4`  Then we checked dot11manufacturerName.5 to see if it contained Ubiquiti.  .5 doesn't contain data on this device only .30-.33.  I'll change it to a walk and it will work.

But, my previous point was if Ubiquiti set the proper sysObjectID (should start with `.1.3.6.1.4.1.41112`) on all there devices, we wouldn't need the above spaghetti code/extra snmp requests to detect Ubiquiti equipment.

Please pass that on to someone :)

I'll send a patch to make detection work.
