### ISSUE TITLE
poller-wrapper.py unable to connect to mysql database after daily update

### ISSUE THREAD

**Issue by daynedrak** [librenms/librenms#7506]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
====================================
Component | Version
--------- | -------
LibreNMS  | 1.32-53-gee5c223
DB Schema | 211
PHP       | 7.0.23
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Database connection successful
[OK]    Database schema correct
[FAIL]  The poller has not run in the last 5 minutes, check the cron job
[WARN]  Some devices have not been polled in the last 5 minutes.
        You may have performance issues. Check your poll log and see: http://docs.librenms.org/Support/Performance/
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.

After the daily update, LibreNMS began alerting that devices weren't polling. I believe this is related to #7471, as the commit to master for that change was only a few hours previous. 

Manually running poller-wrapper.py results in:

ERROR: Could not connect to MySQL database!

My Libre database is on a different host, so there's no unix socket for it to connect to.

I restored the poller-wrapper.py from the previous days backup and normal operation resumed

- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by addp009** [comment]
poller-wrapper.py line 93 is doing `if  db_socket`, but db_socket is not a variable if you're not using unix sockets.

**Comment by addp009** [comment]
Created PR https://github.com/librenms/librenms/pull/7507 to fix it.

**Comment by penfold1972** [comment]
I added db_socket to the config as equal to zero, which got me past that error, but now I am getting the error "ERROR: Could not load or parse configuration, are PATHs correct?" which doesn't make sense since the file is obviously reading the config to get past the db_socket issue. 
Is there something else I need to have in the config now?

**Comment by daynedrak** [comment]
Saw that PR #7507 had been committed to master, updated, and now everything is running normally again

**Comment by penfold1972** [comment]
It's strange, but I had to remove the config entry setting db_socket = 0, and add your change by hand. This allowed my install to connect to the database and run normally. Then I had to "git stash" and run daily.sh so the system would update the code to current.
It seems to be running normally again for me as well.
