### ISSUE TITLE
Palo Alto MIBS missing

### ISSUE THREAD

**Issue by dagmartin** [librenms/librenms#7508]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
====================================
Component | Version
--------- | -------
LibreNMS  | 1.32-53-gee5c223
DB Schema | 211
PHP       | 7.0.10
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

After the update this night, Palo Alto devices are no longer displaying active sessions, vpn sessions, etc.
This seems to be related to #7483 which refers to Palo Alto MIBS instead of bare OIDs, however the MIBS are not included in the mib directory. I tried adding them manually to the MIB dir and then everything works as expected.

**Comment by FTBZ** [comment]
Work in progress #7509.

Two PR were linked to add the MIB support and only one was merged at this time. Sorry for the drawback.
