### ISSUE TITLE
Eltek Valere Minipack

### ISSUE THREAD

**Issue by barryodonovan** [librenms/librenms#7526]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

I am beginning monitoring of our Eltek Valere Minipack PSUs and find that the OIDs of my devices do not match the sysObjectId for eltek valere in https://github.com/librenms/librenms/pull/6979

OID on my devices is iso.3.6.1.4.1.12148
Even better, there is no sysObjectId nor sysDescription nor indeed anything above iso.3.6.1.4.1.12148.10.2.1.0 !

I'm happy to open a PR and shoehorn this in but it (probably) won't be pretty!

**Comment by barryodonovan** [comment]
@murrant 

Looking closer at this, I believe that https://github.com/librenms/librenms/pull/6979 actually relates to the Valere part of Eltek Valere (guessing two companies merged) as the MIB and OID you use are Valere power inc. 

enterprises.12148 is the OID for Eltek (the eltek part of Eltek Valere) and they have their own MIBS.

Can I propose to rename everything in https://github.com/librenms/librenms/pull/6979 to ValerePower, and create a new EltekAS OS for 12148?

Alternatively is there some way we can merge the two different OIDs into one discovery with some if/else magic and call the whole lot EltekValere?

**Comment by murrant** [comment]
The existing OS is already named valere.  It is still Eltek, so Icon and label should stay.

Likely this will need a new OS.  Please post http://docs.librenms.org/Support/FAQ/#faq20, or feel free to code support and submit it :)

**Comment by barryodonovan** [comment]
So, just to confirm (and avoid confusion):

There will be two OS's, one named valere, and one named eltek.
They will share the same icon and label.

This is fine by me, I've already begun working in that direction.

**Comment by murrant** [comment]
@barryodonovan Can you post the snmpwalk as in http://docs.librenms.org/Support/FAQ/#faq20 ?
I'm curious about the data this is returning.  You can send it to me directly on Discord if you don't want to post publicly.

**Comment by barryodonovan** [comment]
This is just a snippet, it goes on and on, don't think there's much benefit to most of it...


------------------------------------------------
iso.3.6.1.4.1.12148.10.2.1.0 = INTEGER: 1
iso.3.6.1.4.1.12148.10.2.2.0 = INTEGER: 3
iso.3.6.1.4.1.12148.10.2.3.0 = INTEGER: 3
iso.3.6.1.4.1.12148.10.2.4.0 = STRING: "Lightnet"
iso.3.6.1.4.1.12148.10.2.5.0 = STRING: "Cregg"
iso.3.6.1.4.1.12148.10.2.6.0 = STRING: "Micropack System"
iso.3.6.1.4.1.12148.10.2.7.0 = STRING: "144009001286"
iso.3.6.1.4.1.12148.10.2.8.0 = Hex-STRING: 07 DE 0A 07 00 00 00 00 
iso.3.6.1.4.1.12148.10.2.9.0 = INTEGER: 48
iso.3.6.1.4.1.12148.10.2.10.0 = INTEGER: 0
iso.3.6.1.4.1.12148.10.2.11.0 = INTEGER: 0
iso.3.6.1.4.1.12148.10.2.12.0 = INTEGER: 0
iso.3.6.1.4.1.12148.10.2.13.0 = INTEGER: 0
iso.3.6.1.4.1.12148.10.2.14.0 = INTEGER: 0
iso.3.6.1.4.1.12148.10.2.15.0 = INTEGER: 1
iso.3.6.1.4.1.12148.10.2.16.0 = INTEGER: 0
iso.3.6.1.4.1.12148.10.2.17.0 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.1.0 = INTEGER: 1
iso.3.6.1.4.1.12148.10.3.2.1.0 = INTEGER: 1
iso.3.6.1.4.1.12148.10.3.2.2.0 = STRING: "MainsLow   "
iso.3.6.1.4.1.12148.10.3.2.4.0 = INTEGER: 1
iso.3.6.1.4.1.12148.10.3.2.5.0 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.2.6.0 = INTEGER: 1
iso.3.6.1.4.1.12148.10.3.2.7.0 = INTEGER: 1
iso.3.6.1.4.1.12148.10.3.3.0 = INTEGER: 1
iso.3.6.1.4.1.12148.10.3.4.1.2.1 = INTEGER: 1
iso.3.6.1.4.1.12148.10.3.4.1.3.1 = STRING: "MainsVolt 1 "
iso.3.6.1.4.1.12148.10.3.4.1.5.1 = INTEGER: 1
iso.3.6.1.4.1.12148.10.3.4.1.6.1 = INTEGER: 227
iso.3.6.1.4.1.12148.10.3.4.1.7.1 = INTEGER: 280
iso.3.6.1.4.1.12148.10.3.4.1.8.1 = INTEGER: 260
iso.3.6.1.4.1.12148.10.3.4.1.9.1 = INTEGER: 100
iso.3.6.1.4.1.12148.10.3.4.1.10.1 = INTEGER: 80
iso.3.6.1.4.1.12148.10.3.5.1.0 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.5.2.1.2.1 = INTEGER: 3
iso.3.6.1.4.1.12148.10.3.5.2.1.3.1 = INTEGER: 3
iso.3.6.1.4.1.12148.10.3.5.2.1.4.1 = INTEGER: 1
iso.3.6.1.4.1.12148.10.3.5.5.1.1.1 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.5.5.1.2.1 = ""
iso.3.6.1.4.1.12148.10.3.5.5.1.4.1 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.5.5.1.5.1 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.5.5.1.6.1 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.5.5.1.7.1 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.5.5.1.8.1 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.5.5.1.9.1 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.5.7.0 = INTEGER: 52
iso.3.6.1.4.1.12148.10.3.5.9.0 = INTEGER: 52
iso.3.6.1.4.1.12148.10.3.5.11.0 = INTEGER: 52
iso.3.6.1.4.1.12148.10.3.6.1.0 = INTEGER: 93
iso.3.6.1.4.1.12148.10.3.6.2.0 = INTEGER: 52
iso.3.6.1.4.1.12148.10.3.6.3.1.2.1 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.2 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.3 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.4 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.5 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.6 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.7 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.8 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.9 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.10 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.11 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.12 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.13 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.14 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.15 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.16 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.17 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.18 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.19 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.20 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.21 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.22 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.23 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.24 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.25 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.26 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.27 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.28 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.29 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.30 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.31 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.32 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.33 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.34 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.35 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.36 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.37 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.38 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.39 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.40 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.41 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.42 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.43 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.44 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.45 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.46 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.47 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.48 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.49 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.50 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.51 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.3.1.2.52 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.4.0 = INTEGER: 52
iso.3.6.1.4.1.12148.10.3.6.5.1.2.1 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.2 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.3 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.4 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.5 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.6 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.7 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.8 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.9 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.10 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.11 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.12 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.13 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.14 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.15 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.16 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.17 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.18 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.19 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.20 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.21 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.22 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.23 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.24 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.25 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.26 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.27 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.28 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.29 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.30 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.31 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.32 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.33 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.34 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.35 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.36 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.37 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.38 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.39 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.40 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.41 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.42 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.43 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.44 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.45 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.46 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.47 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.48 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.49 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.50 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.51 = INTEGER: 0
iso.3.6.1.4.1.12148.10.3.6.5.1.2.52 = INTEGER: 0

**Comment by murrant** [comment]
@barryodonovan Please pastebin the whole thing and use the exact command that is in the docs.

**Comment by barryodonovan** [comment]
https://p.libren.ms/view/8c71cc12

**Comment by laf** [comment]
I'd probably suggest creating the PR for the new eltek OS and we can take a look

**Comment by laf** [comment]
@barryodonovan how you getting on with this?

**Comment by barryodonovan** [comment]
Haven't had time to turn around in the last 3 weeks!


I'll look at it again monday and make sure it is pushable.



________________________________

**Comment by laf** [comment]
@barryodonovan Any movement on this or anything we can do to help you?

**Comment by barryodonovan** [comment]
@laf
I'm very confused by this, enexus support is working perfectly fine in my production librenms!
( https://github.com/librenms/librenms/pull/7552 )

What else are we waiting on?

**Comment by laf** [comment]
> What else are we waiting on?

You created the issue so I guess you tell us?

**Comment by barryodonovan** [comment]
@laf


I guess my point is that the merge on 7th dec. effectively closed this issue.


Unless you're aware of something outstanding? As I said, it seems to be working perfectly in production for me.


Barry

________________________________

**Comment by laf** [comment]
Closing then.
