### ISSUE TITLE
feature request:ospf autodiscover

### ISSUE THREAD

**Issue by zunder1990** [librenms/librenms#754]
Neil Lathwood said
Ok so we would need to create a new discovery process for ospf as the only work it does at the moment is in the poller which means we can't add discovery code there.

I can see ospfNbrIpAddr in the table, so I guess the process is:

Add ospf detection to includes/discovery/discovery-protocols.inc.php
This should get the ospfNbrIpAddr
Do a reverse dns lookup on the IP
If we get a hostname and it doesn't exist in the db then auto add

**Comment by laf** [comment]
@zunder1990 I've just submitted a PR to get this to work for you. You can always test this by grabbing the changes until the code is merged in.
