### ISSUE TITLE
Pfsense Memory not polling correct info

### ISSUE THREAD

**Issue by kkrumm1** [librenms/librenms#7541]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the 
`====================================
Component | Version
--------- | -------
LibreNMS  | 1.32-77-gc50ddc3
DB Schema | 211
PHP       | 7.0.24
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================
[OK]    Database connection successful
[OK]    Database schema correct
` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery output: https://gist.github.com/kkrumm1/9fa35764b1590fbe62f5e242577eda13#file-pfsense-discovery
Poller output: https://gist.github.com/kkrumm1/f1978ad1b268ab5eac36903e1962b0ba#file-pfsense-poller
SNMP walk: https://gist.github.com/kkrumm1/8763c82040803c2ccad0e95d0dc4c4a0#file-pfsense-snmp-walk

screenshot from Pfsense 
![image](https://user-images.githubusercontent.com/27959419/31974244-1820fa8a-b8f0-11e7-9c52-55879da61f0c.png)

Screenshot from LibreNMS
![image](https://user-images.githubusercontent.com/27959419/31974282-7c75dcda-b8f0-11e7-8662-414314a4ed1f.png)

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by tomarch** [comment]
Pfsense GUI show only used memory (without shared and cache), but librenms show used + shared + cache.
You can see that in the over graph : 
![image](https://user-images.githubusercontent.com/1308821/32091429-6f6bb0ea-baf4-11e7-8c2b-48a5e9416641.png)

**Comment by kkrumm1** [comment]
@tomarch thank you that makes sense :)
