### ISSUE TITLE
Graylog integration with correct range

### ISSUE THREAD

**Issue by guanana** [librenms/librenms#7548]
Component | Version
--------- | -------
LibreNMS  | 1.32-83-ge99ba67
DB Schema | 211
PHP       | 7.1.10
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

Full problem detailed on the forum: https://community.librenms.org/t/graylog-2-2-3-integration-range-problem/2450/6

Basic info:

For Graylog 2.2.3 version you need to manually add the following variable, otherwise you'll get a 404 reply:

$config[‘graylog’][‘base_uri’] = ‘/search/universal/relative’;

The range is not set by default. That means to graylog for every time you click into something (even loading the dashboard if it has the widget), it will first retrieve ALL the logs in the server (in my case more than 4billions) and then filter the first 25 (the filter variable is set by default).

> /opt/librenms/html/includes/common/graylog.inc.php: range: “’ . (isset($_POST[‘range’]) ? mres($_POST[‘range’]) : ‘’) . '”
> 
> /opt/librenms/html/includes/table/graylog.inc.php: $graylog_url = $config[‘graylog’][‘server’] . ‘:’ . $config[‘graylog’][‘port’] . $graylog_base . ‘?query=’ . urlencode($query) . ‘&range=’. $filter_range . $extra_query;
> 

Will be really useful to have a variable to set the default range, something like:

$config[‘graylog’][‘default_range’] = ‘300’;

And then be able on the gui to change the time frame to the specific we need.

Thanks.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by kkrumm1** [comment]
https://github.com/librenms/librenms/pull/7538

**Comment by laf** [comment]
Are you 100% sure that the path in 2.2.3 is just `/search/universal/relative`?

http://docs.graylog.org/en/2.2/pages/configuration/rest_api.html
http://docs.graylog.org/en/2.3/pages/configuration/rest_api.html

Both seem to indicate it's `/api/search/universal/relative` like we already have.

**Comment by laf** [comment]
No further response. Closing unless someone can provide more info on this discussion.
