### ISSUE TITLE
Alerts will not run from cron

### ISSUE THREAD

**Issue by Ultra2D** [librenms/librenms#755]
`includes/device-groups.inc.php` is not included when running `/opt/librenms/alerts.php` from cron. As a work-around, I have changed the cron entry to `*    *    * * *   root    cd /opt/librenms && /opt/librenms/alerts.php >> /dev/null 2>&1`.

**Comment by laf** [comment]
@Ultra2D  yup, you're correct. I assumed this was an issue on my install actually.

@f0o

**Comment by f0o** [comment]
PR'ing in a sec

**Comment by laf** [comment]
All sorted - thanks for the report @Ultra2D + the fix @f0o
