### ISSUE TITLE
IPv4 address info missing for device

### ISSUE THREAD

**Issue by dabuechler** [librenms/librenms#7550]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X ] Please provide as much detail as possible.
- [X ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

validate.php:
====================================
Component | Version
--------- | -------
LibreNMS  | 1.32-91-g51ba934
DB Schema | 212
PHP       | 7.1.10
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

I am attempting to monitor a Casa Systems C100G.  The ipv4-addresses discovery module fails to detect IP addresses on any interface.

Debug of discovery.php -m ipv4-addresses is here:
https://pastebin.com/1BqJDRvm

The gist of it is "No Such Object available on this agent at this OID".  Casa Systems appears to strictly adhere to RFC 4293.  The RFC depreciated ipAddrTable (of which ipAdEntIfIndex and ipAdEntNetMask are columns), and added ipAddressTable in it's place.

The relevant part of RFC 4293 (https://tools.ietf.org/html/rfc4293):
ipAddressEntry OBJECT-TYPE
    SYNTAX     IpAddressEntry
    MAX-ACCESS not-accessible
    STATUS     current
    DESCRIPTION
           "An address mapping for a particular interface."
    INDEX { ipAddressAddrType, ipAddressAddr }
    ::= { ipAddressTable 1 }

IpAddressEntry ::= SEQUENCE {
        ipAddressAddrType     InetAddressType,
        ipAddressAddr         InetAddress,
        ipAddressIfIndex      InterfaceIndex,
        ipAddressType         INTEGER,
        ipAddressPrefix       RowPointer,
        ipAddressOrigin       IpAddressOriginTC,
        ipAddressStatus       IpAddressStatusTC,
        ipAddressCreated      TimeStamp,
        ipAddressLastChanged  TimeStamp,
        ipAddressRowStatus    RowStatus,
        ipAddressStorageType  StorageType
    }

I'm guessing that only the first half (or so) of the table is going to provide useful data, but I did a walk of the table and cut everything after the first 4 addresses in each OID for length.  The full walk of the table on that device is 1200 lines long.  It can be found here:
https://pastebin.com/Gm0ETFpq

If I missed anything or I can answer any questions regarding this issue, please let me know.  Thank you for your time.

**Comment by dabuechler** [comment]
As requested, I am attaching an snmpbulkwalk run by the manufacturer on a 100G in their lab.

[100gwalk.txt](https://github.com/librenms/librenms/files/1463138/100gwalk.txt)

**Comment by laf** [comment]
Is this device even detected correctly in the first place? From the snmpwalk it doesn't appear to be.

If it isn't, what's the OS / firmware name these devices run?

**Comment by laf** [comment]
No further info provided, if you can provide the info we will re-open.
