### ISSUE TITLE
Storage warn % get reset if storage module timeout during a discovery

### ISSUE THREAD

**Issue by tomarch** [librenms/librenms#7565]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.32-99-gd4b2f6e
DB Schema | 212
PHP       | 7.0.23
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

I've this issue with some Windows server (2012R2 with hyperv) which don't answer to hrstorage for long period. : 
![image](https://user-images.githubusercontent.com/1308821/32091846-42adb9a2-baf6-11e7-9eac-b14ee714ed5a.png)
If during this period, there's a automatic discovery (by cron every 8h), then storage warn settings go back to 60%

I've try to increase snmp timeout for windows from default 1sec to 3 sec:
$config['os']['windows']['snmp']['timeout'] = 3;

**Comment by laf** [comment]
You will probably find that the storage was removed and then re-added because of the timeout. You'll need to fix this timeout.

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
