### ISSUE TITLE
Install.php stage set to 6, install process doesn't create mysql tables

### ISSUE THREAD

**Issue by bl4kd3th** [librenms/librenms#7568]
Just finished going through install process on the docs page for Centos (nginx). When I went to http://hostname/install.php, it started me on step 5 of 6 and said that the config.php could not be created. Manually created the config.php file and went to validate. However, actual the install steps for creating user and tables was not completed. Looks like in https://github.com/librenms/librenms/pull/7474 the handling for the $stage is commented out and $stage is set to 6. Once I reversed that change I was able to go back to http://hostname/install.php and go through the normal install process.

Component | Version
--------- | -------
LibreNMS  | 1.32-100-g65b0c8b
DB Schema | 212
PHP       | 7.1.10
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

---

**Comment by ChoiZ** [comment]
I've fix this issue in my Pull Request #7571
