### ISSUE TITLE
AD auth doesn't work

### ISSUE THREAD

**Issue by CZAirwolf** [librenms/librenms#7584]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.33
DB Schema | 213
PHP       | 7.0.19-1
MySQL     | 10.1.26-MariaDB-0+deb9u1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
Update 1.32.01->1.33 broke AD authentication.  Restored active_directory.inc.php from backup -> it works. Auth bind works, user is in specific security group in specific OU.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
Authentication Method: active_directory
AD bind success
Password: 
Authenticate user USERNAME: 
PHP Fatal error:  Uncaught LibreNMS\Exceptions\AuthenticationException: Invalid credentials in /DATADIR/librenms/html/includes/authentication/active_directory.inc.php:52
Stack trace:
#0 /DATADIR/librenms/scripts/auth_test.php(96): authenticate('USERNAME', 'PASSWORD)
#1 {main}
  thrown in /DATADIR/librenms/html/includes/authentication/active_directory.inc.php on line 52

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by murrant** [comment]
Hmm, could probably clean up the output.  But it does say invalid credentials.
