### ISSUE TITLE
HP J9091A Switch 8212zl will not pull interface data

### ISSUE THREAD

**Issue by kkrumm1** [librenms/librenms#7598]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-5-g0cf8c26
DB Schema | 213
PHP       | 7.1.10
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Database connection successful
[OK]    Database schema correct
` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

SNMP WALK: https://gist.github.com/kkrumm1/f3888d6814fad94183f7841475f4ef1b#file-snmp-walk-hp-8212
Discovery:https://gist.github.com/kkrumm1/bffc166df748ca644bca9a04b4fbb3e8#file-discovery-8212
Poller: https://gist.github.com/kkrumm1/1b4a8e051936a532bfb3b533eb672517#file-poller-8212

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by kkrumm1** [comment]
It used pull traffic data but something changed ... I tested on another install of librenms and it doing the something..
![image](https://user-images.githubusercontent.com/27959419/32298684-e9a42254-bf20-11e7-99b9-325b14b26794.png)

**Comment by kkrumm1** [comment]
Missing both. Looks like was working months ago then stopped.

**Comment by kkrumm1** [comment]
> I'd check the logs/librenms.log for any mysql errors. The poller output indicates that the octets are the same as the previous ones for the ports which will mean it looks like no traffic is going across them.

I will check the logs and see, but on two separate installs of Libre shows not traffic being reported.
Yet on that switch, shows traffic.

**Comment by kkrumm1** [comment]
first poll: https://gist.github.com/kkrumm1/07db4ee69e58df4e2b6df8f6c61b0ae4#file-first-poll-8212
second poll 5 min later: https://gist.github.com/kkrumm1/03b0f9155de170fbbdd6ab5a5140ac70#file-gistfile1-txt

check logs no errors in logs

**Comment by laf** [comment]
Those two polls show the _exact_ same info for ifHCInOctets. Unless every single port carried 0 bytes of traffic in those 5 minutes then this device is 'buggered'
