### ISSUE TITLE
Add CPU and Memory detecion for Edge-Core switches

### ISSUE THREAD

**Issue by kamils85** [librenms/librenms#7616]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 1.33-23-gfb45f00
DB Schema | 215
PHP       | 7.0.15-0ubuntu0.16.10.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.10.1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

According to this: https://github.com/librenms/librenms/pull/5466 the CPU support was added but it does not work with ECS4120-28F switches as they use different OID for CPU polling.

Not sure if the memory polling was ever added but it's not working either. 
Can this be added please?

Below the OIDs for CPU/Mem
[edgecos-cpu-mem.txt](https://github.com/librenms/librenms/files/1439351/edgecos-cpu-mem.txt)

Here you can find snmpwalk and up-to-date MIB for ECS: https://github.com/librenms/librenms/issues/7140

Thanks,

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by kamils85** [comment]
Please find all the requested below:

discovery: https://p.libren.ms/view/e60cee9f
poller: https://p.libren.ms/view/a40d0f86
snmpbulk: [edgecos-10.150.50.1.snmpwalk.zip](https://github.com/librenms/librenms/files/1515551/edgecos-10.150.50.1.snmpwalk.zip)
