### ISSUE TITLE
Dell S500 Not supported

### ISSUE THREAD

**Issue by TheMysteriousX** [librenms/librenms#7619]
Discovery: https://p.libren.ms/view/c93a8127
Poller: https://p.libren.ms/view/3221fc03
BulkWalk: Killed your database server when I tried to upload it, so see attachment
[BulkWalk.txt](https://github.com/librenms/librenms/files/1441728/BulkWalk.txt)
 :)

Note that this is a modular chassis - we have ours outfitted with:
Bay 0: S5000-MOD-12xETH10-F
Bay 1: S5000-MOD-12xETH10-F
Bay 2: S5000-MOD-12xETH10-T
Bay 3: Empty

Dell call the OS running on this "Dell Networking OS"
```
Dell Real Time Operating System Software
Dell Operating System Version:  2.0
Dell Application Software Version:  9.11(2.0P0)
Fiber Channel Firmware Version: 'V10.7.0.05.00'
Copyright (c) 1999-2017 by Dell Inc. All Rights Reserved.
Build Time: Thu Apr 27 07:46:32 2017
Build Path: /build/build02/SW/SRC
Dell Networking OS uptime is 10 week(s), 3 day(s), 1 hour(s), 27 minute(s)

System image file is "system://A"

System Type: S5000
Control Processor: Freescale QorIQ P2020 with 2 Gbytes (2147483648 bytes) of memory, core(s) 1.

16M bytes of boot flash memory.

  1 4-module, 4-port GE/TE/FG (SH)
 36 Ten GigabitEthernet/IEEE 802.3 interface(s)
  4 Forty GigabitEthernet/IEEE 802.3 interface(s)
```

```
====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-37-gcc729eb
DB Schema | 215
PHP       | 7.0.24
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================
```
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by TheMysteriousX** [comment]
new-os.php generated this, which has gotten some information to be polled (ports, inventory, vlans) but that's all.

```
os: dell
text: 'Dell Networking OS'
type: network
icon: dell.svg
group: dell
over:
    - { graph: device_bits, text: 'Device Traffic' }
    - { graph: device_processor, text: 'CPU Usage' }
    - { graph: device_mempool, text: 'Memory Usage' }
discovery:
    - sysObjectId:
        - .1.3.6.1.4.1.6027.1.3
```

**Comment by laf** [comment]
I'm wondering if this is due to some older bugs, using your data it detects as dnos for me fine.

Please update your install and try again.

**Comment by TheMysteriousX** [comment]
Seems partially resolved.

I removed the files that new-os.php and it stayed  as dnos through discovery, so that bit is now working OK.

Didn't check in detail as I was just leaving the office for the day, but some graphs were present but empty - notably CPU.

I can recapture the discovery/poller output if that's useful?

**Comment by TheMysteriousX** [comment]
The that oid returns 'no such object'.

It probably does have the information somewhere; I'm having a little trouble getting the MIB to load to decode oids under the force 10 enterprise number. I'm also the time outs while polling certain oids, which is weird. So it might take me a few days to figure out what's what.

**Comment by laf** [comment]
I'd suggest you open a post on the community forums. Detection exists so this is most likely an issue with the device for polling ports.
