### ISSUE TITLE
Add support for Arista power supply state in sensors table

### ISSUE THREAD

**Issue by shimamizu** [librenms/librenms#7621]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

###############

LibreNMS is not currently collecting *any* sensor_class = state alarms for Arista devices. I have spoken to Arista and gotten the MIB's you need to poll in order to get the "Status" column from the CLI output you would see in "show environment power" to be able to alert on Power Supply state. 
Please add this logic into Arista as this will then allow easy creation of Alerts for knowing when a power supply goes bad / loses power on an Arista switch.

Here's the email I got back from Arista TAC requesting information on the MIB to grab this value: 

> Unfortunately we don't have a straightforward way to poll the operating status of specifically PSUs at this time. We do have RFE210545 opened to provided a consolidated PSU MIB, and I have added you to the requesters list for the functionality. The RFE does not currently have a targeted release date, in the mean time you can use the following method which uses each PSUs SNMP index to poll it's operating status with the Entity MIB:
> 
> Find the SNMP Index of the PSUs:
> sq514...16:11:10#show snmp mib walk entPhysicalDesc | egrep "PowerSupply.$"
> ENTITY-MIB::entPhysicalDescr[100711000] = STRING: PowerSupply1
> ENTITY-MIB::entPhysicalDescr[100721000] = STRING: PowerSupply2
> 
> Then append the index to the end of the Enitity-MIBs Operating Status OID (.1.3.6.1.2.1.131.1.1.1.3.), here I have polled directly from the switch, but the same OID can be used with any NMS system or SNMP enabled server:
> sq514...16:12:20#show snmp mib walk .1.3.6.1.2.1.131.1.1.1.3.100711000
> ENTITY-STATE-MIB::entStateOper[100711000] = INTEGER: disabled(2)
> sq514...16:11:27#show snmp mib walk .1.3.6.1.2.1.131.1.1.1.3.100721000
> ENTITY-STATE-MIB::entStateOper[100721000] = INTEGER: enabled(3)
> 
> The returned value will match the status of PSU:
> sq514...16:12:35#show environment power
> Power                                  Input    Output   Output
> Supply  Model                Capacity  Current  Current  Power    Status
> ------- -------------------- --------- -------- -------- -------- -------------
> 1       PWR-460AC-F               460W    0.00A    0.00A     0.0W Power Loss
> 2       PWR-460AC-F               460W    0.41A    6.12A    74.0W Ok
> Total   --                        460W       --       --    74.0W --
> 
> The above output was taken from a 7050S, but this method will work for a device of any RSU. Let me know if you have any questions.

**Comment by shimamizu** [comment]
"Please provide ALL info asked for here." That link says it's for adding new OS, you already have Arista's in LibreNMS which is why I did not provide those outputs. The MIB's needed for Arista's to grab this data are in the quote above from Arista TAC and they are not Arista Model specific, they should work on all models.

**Comment by shimamizu** [comment]
Also one last update: 

> Enabled/Disabled are the only returns you should see from the MIB. You could also see 'Failed' or 'Mismatch' (if you've got the wrong type of PSU installed) for the 'show env power' command, both of those should return 'disabled' for the MIB. In short, 'disabled' would be bad (or at least warrant investigation), and enabled would be good.

**Comment by murrant** [comment]
@shimamizu we use that data to test.  So really this info is needed when adding a new device or additional support for an existing device.

**Comment by shimamizu** [comment]
@murrant got an error trying to upload the requested discovery data (I purged my username and hostname from the paste for confidentiality): 

```
librenms:  -> sudo ./discovery.php -h hostname.removed.com -d | ./pbin.sh
Paste endpoint: https://p.libren.ms/api/create
No log handling enabled - turning on stderr logging
Cannot find module (CPQHOST-MIB): At line 0 in (none)
cpqHoFileSysEntry: Unknown Object Identifier (Sub-id not found: (top) -> cpqHoFileSysEntry)
title: 
name: MY_USERNAME_HERE
private: 1
expire: 0
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.10.2</center>
</body>
</html>
```

**Comment by murrant** [comment]
@shimamizu Too big for that pastebin to handle, can you paste somewhere else?

**Comment by murrant** [comment]
@shimamizu you can dm it to me on Discord.  Make sure to redact anything you feel in sensitive.

**Comment by shimamizu** [comment]
#7625 looks very promising so far!
