### ISSUE TITLE
Cisco UCS FI Detected as Generic

### ISSUE THREAD

**Issue by Blorpy** [librenms/librenms#7624]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
`Component | Version
--------- | -------
LibreNMS  | 1.33-31-gaef1a5f
DB Schema | 215
PHP       | 7.1.10
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.5.6
SNMP      | NET-SNMP 5.7.2`
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Have a Cisco 6248 UCS Fabric Interconnect that is being detected as a generic device as of last night, not sure if a commit broke this or what. I rebooted the fabric interconnect to make sure it wasn't hosed in some interesting way, but it made no difference. I reran discovery on librenms, but its still showing as a generic. 

Discovery: https://p.libren.ms/view/dbf24311
Poller: https://p.libren.ms/view/8e2b51e8

**Comment by murrant** [comment]
@Blorpy This is fixed upstream I think, run ./daily.sh

**Comment by Blorpy** [comment]
I reran daily.sh today just to be sure I had the latest code, and I do, but these devices are still being seen as generic.

**Comment by laf** [comment]
Please post fresh poller / discovery pastes.

**Comment by Blorpy** [comment]
Discovery: https://p.libren.ms/view/c38f9c0f
Poller: https://p.libren.ms/view/488ce6ce

**Comment by laf** [comment]
So this device should be detected as nxos. However in the discovery output sysDescr isn't returned which is what we use.

Does this command give you anything when run manually.

`/usr/bin/snmpget -v3 -n '' -l 'authPriv' -a 'SHA' -A 'AUTH_PASS' -u 'snmpuser' -x 'AES' -X 'PRIV_PASS' -OUQn -M /opt/librenms/mibs udp:HOSTNAME:161 SNMPv2-MIB::sysDescr.0 SNMPv2-MIB::sysObjectID.0`

**Comment by laf** [comment]
Change the AUTH_PASS and PRIV_PASS vars.

**Comment by Blorpy** [comment]
All that's returned is:

`.1.3.6.1.2.1.1.2.0 = .1.3.6.1.4.1.9.12.3.1.3.1062`

**Comment by laf** [comment]
Wow, that's just daft. Try dropping `SNMPv2-MIB::sysObjectID.0` from the command and see.

It works in your poller so not sure why this isn't working here.

**Comment by Blorpy** [comment]
`.1.3.6.1.2.1.1.1.0 = Cisco NX-OS(tm) ucs, Software (ucs-6100-k9-system), Version 5.0(3)N2(3.13a), RELEASE SOFTWARE Copyright (c) 2002-2013 by Cisco Systems, Inc.   Compiled 4/25/2017 7:00:00`

**Comment by laf** [comment]
@murrant https://github.com/librenms/librenms/commit/0d07f8525718ba40ee882496a75b9ba3b6dfc067#diff-f81f3dff36bf04b7a070d642c858e883R98

That seems to cause this.

**Comment by murrant** [comment]
@laf yeah, we can revert to two gets.  It was only a small gain in discovery, no big deal.
