### ISSUE TITLE
New device: dd-wrt WAP

### ISSUE THREAD

**Issue by kkrumm1** [librenms/librenms#7637]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-35-g3dba5cd
DB Schema | 215
PHP       | 7.1.10
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Database connection successful
[OK]    Database schema correct
` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery: https://gist.github.com/kkrumm1/67dd55e8095ba5c52a0ecedf137248a8#file-dd-wrt-discovery
Poller: https://gist.github.com/kkrumm1/78f8756d32bfdc0f5df3c0b99b0848be#file-dd-wrt-poller
SNMP Walk: https://gist.github.com/kkrumm1/242b9d5961e76f63b797c07b7afa5a20

https://www.dd-wrt.com/site/index
https://www.dd-wrt.com/wiki/index.php/SNMP

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
Any ideas on how to detect via snmp that it is running dd-wrt?

**Comment by kkrumm1** [comment]
@murrant good question.

**Comment by murrant** [comment]
I see the distro script supports dd-wrt, maybe just set that up?

**Comment by kkrumm1** [comment]
@murrant where do you see that?

**Comment by laf** [comment]
https://github.com/librenms/librenms-agent/blob/master/snmp/distro#L95

**Comment by kkrumm1** [comment]
well shoot now I gotta figure out how to get that onto dd-wrt. 
#Distro Detection
extend .1.3.6.1.4.1.2021.7890.1 distro /usr/bin/distro

**Comment by kkrumm1** [comment]
Closing my request for no since there is no real way to tell from SNMP that its dd-wrt.

**Comment by arrmo** [comment]
You can't tell from the (dd-wrt) shell that you're on dd-wrt? If you do this, the distro script can be updated.
