### ISSUE TITLE
Issue with "update_device_field" from API, updating the "Type"

### ISSUE THREAD

**Issue by saefr** [librenms/librenms#7639]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

-----------------

Component | Version
--------- | -------
LibreNMS  | 1.33-38-g00470df
DB Schema | 215
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

-----------------

Hi everyone,

I have a problem since a few days with the LibreNMS API, using the "update_device_field" action 

I use this two differents cli commands to update each one of my workstations from a bash script, run from another Linux server in LAN. These commands are 

`curl http://librenms.xxxx/api/v0/devices/$nom.$domaine -X PATCH -d '{"field": ["sysContact","location","ignore","purpose","type","override_sysLocation"], "data": ["support@irvi.fr","'"$localisation"'","1","PC","workstation","1"]}' -H 'X-Auth-Token:XXXXXX'`

`curl http://librenms.xxx/api/v0/devices/$nom.$domaine -X PATCH -d '{"field": "type", "data": "workstation"}' -H 'X-Auth-Token: XXXXXX'`

These twos are working perfectly (no errors, "message": "Device type field has been updated") 
The fields are updating correctly on the web interface, every one of them.

But if you wait a few minutes (2-3 minutes max), all the workstations move themselves to "server" type without any actions from LibreNMS or myself. If i use "Collaboration" or anything like it, the problem seem to be the same, in a span of 3 minutes the field is now "Server".

The only way to move the PC to "Workstation" type is manually, from the web interface, and it works well using this. 

Am i doing it wrong, or it is a real bug from the API ?

Thanks for the answer,

Sebastien

**Comment by laf** [comment]
Only certain fields are updatable in the devices table via the API. Those like you're finding are not will be overwrote on the next poll.

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our IRC channel or the community site: http://docs.librenms.org/Support/FAQ/#faq3
