### ISSUE TITLE
Auto-Discovery Templates

### ISSUE THREAD

**Issue by tardoe** [librenms/librenms#764]
When discovering a device, allow pre-configured templates to be used to enable / disable features on a a per-device basis.

E.g. I might not want Libre to track the multiple full BGP feeds on my border routers or I might not want the 600+ interfaces graphed.

**Comment by f0o** [comment]
Should be possible :)
Will take a look

**Comment by f0o** [comment]
I would like to tie this together with #526 instead.
So it might take a bit before we can merge this.

**Comment by laf** [comment]
What do you need out of the dynamic config system. I've got to rebase that again and I keep putting it off

**Comment by f0o** [comment]
Basically a mapping between discovery & poller modules to device-groups.
We should discuss this on IRC when I'm home again - can prototype smt over the weekend

**Comment by Lonecrowe** [comment]
I was thinking instead of "templates"  you took a "wizard" type approach initially to help people get new devices in.  A page that you input and checked what you wanted to monitor.  There is a question whether it should scan for regular if-mib stuff and if you say yes it scans (sort of like cacti)  and then you pick and choose which interfaces you wish to graph and which stastics with check boxes.  

Then below that there is a manual section to add more.  I'll detail my idea in a new feature request I was planning.  But at the end of the configuration the goal was to be able to save that entire set of code into a template.

**Comment by killsudo** [comment]
This could work by leveraging the 'Generic' device group for additional checks for certain oids/nmap/etc.

Basically any new auto-discovered devices would be dropped into the 'Generic' device group that were not auto-identified on the first poll. When devices resides in the 'Generic' device group LibreNMS could perform additional polls for certain OID's, Processing the output from running processing identified via snmp( .1.3.6.1.2.1.25.4.2.1.2) , Processing the output from installed packages via snmp( #789 ), performing an nmap scan open port / fingerprint, and probing open ports and checking what gets returned (telnet host 25 | then returns Exim 4.85 | Now we know it's at least a Linux box running Exim so we can monitor port 25 service via smtp check) etc.

The LibreNMS admin could decide which 'generic' checks he/she is comfortable allowing for generic devices.

Here we can make a good guess that we found a box running centos with services sshd/httpd/dhcp to monitor then perform additional checks to verify it's rhel or centos etc but we have what we need to setup service monitors.
# snmpwalk -v2c -cpublic pxe.example.net .1.3.6.1.2.1.25.4.2.1.2 | grep -E "sshd|httpd|dhcp"
HOST-RESOURCES-MIB::hrSWRunName.1872 = STRING: "sshd"
HOST-RESOURCES-MIB::hrSWRunName.1946 = STRING: "httpd"
HOST-RESOURCES-MIB::hrSWRunName.4363 = STRING: "dhcpd"
HOST-RESOURCES-MIB::hrSWRunName.7063 = STRING: "httpd"
HOST-RESOURCES-MIB::hrSWRunName.7064 = STRING: "httpd"
HOST-RESOURCES-MIB::hrSWRunName.7066 = STRING: "httpd"
HOST-RESOURCES-MIB::hrSWRunName.7068 = STRING: "httpd"
HOST-RESOURCES-MIB::hrSWRunName.7069 = STRING: "httpd"
HOST-RESOURCES-MIB::hrSWRunName.7072 = STRING: "httpd"
HOST-RESOURCES-MIB::hrSWRunName.7073 = STRING: "httpd"
HOST-RESOURCES-MIB::hrSWRunName.7074 = STRING: "httpd"
HOST-RESOURCES-MIB::hrSWRunName.15445 = STRING: "dhcpd-snmp"
HOST-RESOURCES-MIB::hrSWRunName.20380 = STRING: "sshd"

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
