### ISSUE TITLE
API Authentication succeeds without valid token when using LDAP authentication

### ISSUE THREAD

**Issue by feitingen** [librenms/librenms#7640]
When using LDAP authentication, the API authentication fails to reject invalid access tokens.

I believe this is because the function authToken in html/includes/api_functions.inc.php does:

$username = get_user(…)
if (!empty($username)) 

This will always be true if LDAP is enabled since the function get_user in html/includes/authentication/ldap-authorization.inc.php returns an array:

$userlist[] = array(
‘username’ => $username,
‘realname’ => $realname,
‘user_id’ => $user_id,
‘email’ => $email,
);
This array will always be returned to the authToken function as long as the X-Auth-Token header is set, and it doesn’t matter what it is set to.

This allows anyone full access to the API without a valid token.

**Comment by laf** [comment]
Are you submitting a pull request with a fix for this?

**Comment by feitingen** [comment]
I'm sorry, I should have mentioned that I wasn't planning to.

I'm happy to try, but if someone more familiar with the code makes a fix it is probably better.

**Comment by feitingen** [comment]
PR #7710 fixes this issue better than I could have :)

**Comment by feitingen** [comment]
The PR #7710 didn't fix the issue completely.
The authentication still doesn't fail, but due to the additional checks, no information is available without a token.

For some other reason, a valid token from a valid user is also not getting any information from the API.

I'll cobble together a pull request or two for this in the not too distant future.

**Comment by laf** [comment]
Maybe because the user id returned from the ldap lookup doesn't match the one we have for the API token?

**Comment by laf** [comment]
No further information has been provided so this issue is being closed.

If you have more information to provide then please do so and we will re-open this issue.
