### ISSUE TITLE
Support for devices from NetPing

### ISSUE THREAD

**Issue by YuliaKoroleva** [librenms/librenms#7643]
Hi!
There is a task to connect the device Uniping server solution v3 / SMS to LibreNMS to receive data from temperature, humidity sensors and so on.
Exchange is performed using SNMP v.2 protocol

link to devices http://www.netpingdevice.com/products/uniping-server-solution-v3-sms

The output of ./validate.php:

Component | Version
LibreNMS | 1.32-70-g0f8966a
DB Schema | 211
PHP | 7.0.22-0ubuntu0.16.04.1
MySQL | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool | 1.5.5
SNMP | NET-SNMP 5.7.3

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.
