### ISSUE TITLE
Support for devices NetPIng

### ISSUE THREAD

**Issue by YuliaKoroleva** [librenms/librenms#7644]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x]Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Hi!
There is a task to connect the device Uniping server solution v3 / SMS to LibreNMS to receive data from temperature, humidity sensors and so on.
Exchange is performed using SNMP v.2 protocol
Device - http://www.netpingdevice.com/products/uniping-server-solution-v3-sms
MIB - http://www.netping.ru/Pub/Firmwares/[Pub]%20DKSF%2070.6.6%20MB.mib

Component | Version
LibreNMS  | 1.33-39-g21495a8
DB Schema | 215
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

Discovery.php - https://p.libren.ms/view/6ec607fb
Poller.php - https://p.libren.ms/view/3745676d
snmpbulkwalk - https://p.libren.ms/view/4e3d03b5

I apologize for the inconvenience.

**Comment by kkrumm1** [comment]
You didn't run` ./discovery.php HOSTNAME -d` correcly. 

You need to replace HOSTNAME with the name of your device or ip.

**Comment by YuliaKoroleva** [comment]
Sorry.
Discovery - https://p.libren.ms/view/febfb2aa
Poller - https://p.libren.ms/view/f0f11911
snmpbulwalk -https://p.libren.ms/view/4b7d7272

**Comment by kkrumm1** [comment]
snmpbulwalk -https://p.libren.ms/view/4b7d7272
still not outputting anything

**Comment by YuliaKoroleva** [comment]
Unfortunately, I'm not very good at working with Ubuntu
Most likely I'm doing something wrong, but the output of the command still contains only the line "End of MIB"
Tell me, how to make a report correctly? 
![image](https://user-images.githubusercontent.com/33417415/32450049-ccb84c96-c345-11e7-8226-d9d12acebdfb.png)

**Comment by kkrumm1** [comment]
try this go to the device in web ui and click on settings -> capture then click on SNMP and then RUN that should output SNMP walk then you can copy and paste into pastebin. 
https://docs.librenms.org/#Support/Device-Troubleshooting/

**Comment by YuliaKoroleva** [comment]
Still
![default](https://user-images.githubusercontent.com/33417415/32483853-4549f616-c3d0-11e7-996d-8222191903cf.JPG)

**Comment by laf** [comment]
Maybe the device doesn't support bulkwalk, just do snmpwalk.

**Comment by YuliaKoroleva** [comment]
snmpwalk https://p.libren.ms/view/7d255a33

**Comment by laf** [comment]
Can you take a look at PR #7807 and give it a test please.

**Comment by YuliaKoroleva** [comment]
Data from the sensors connected to the NetPing device can not be obtained as before.


![image](https://user-images.githubusercontent.com/33417415/33334983-557df4b8-d49e-11e7-9f1d-b71fd909baf9.png)

**Comment by kkrumm1** [comment]
@YuliaKoroleva have you updated your install?

**Comment by YuliaKoroleva** [comment]
Сompletely reinstalled the system from the repository

**Comment by laf** [comment]
Forgot this is a no-bulk device. I'm fixing that now.

**Comment by laf** [comment]
Update and run a discovery again, should work now.

**Comment by YuliaKoroleva** [comment]
Thank you!

Now data from sensors connected to the device are available!

![image](https://user-images.githubusercontent.com/33417415/33432806-f8851542-d60b-11e7-9fb0-1631b0401351.png)

**Comment by YuliaKoroleva** [comment]
Good afternoon!

Thermal sensors, humidity sensors and relays connected to the NetPing device transmit information correctly to LibreNTS.

Please help in one more question.

In addition to sensors that transmit information, we still have "dry contact" sensors. "Dry contact" sensors are connected to the device's IO lines, and they also need to be added to the monitoring.

PS
Please, tell us, with whom you can discuss possible cooperation?

**Comment by laf** [comment]
What's the OID for these sensors?

**Comment by YuliaKoroleva** [comment]
Sorry for the delay in reply.
in the attached OID file for managing IO lines.
[OID IO Line.docx](https://github.com/librenms/librenms/files/1551560/OID.IO.Line.docx)

**Comment by YuliaKoroleva** [comment]
Good evening

please tell me when I will complete the work on obtaining data from the IO lines?

I am writing a manual for users on setting up our devices in LibreNMS, most of it is already ready, there is not enough only the section on working with IO lines. Working with OI lines is one of the important aspects of the operation of our devices, so I can not omit this topic.

**Comment by laf** [comment]
No one will give you timescales, this is a community project.

I don't know what IO lines are but these most likely aren't supported by us anyway.
