### ISSUE TITLE
Improve Allied Telesis Support

### ISSUE THREAD

**Issue by mattie47** [librenms/librenms#7652]
I’m trying to add better support for Allied Telesis devices within LibreNMS.

I currently have a fork - https://github.com/mattie47/librenms where I’m trying to do this. I'm hoping to do a PR back to librenms.

Libre currently has very basic support for Allied Telesis, with some mibs circa 2004.

I have the latest:

MIBs - https://github.com/mattie47/librenms/tree/master/mibs/alliedtelesis)
SVGs - 79e2627b4f28d642c5d3a6da250d5d6122536290

At this point I have deleted the “allied.yaml” and “allied.inc.php” which come with libre (Along with AtiL2-MIB, AtiSwitch-MIB) 

I'm currently struggling with the new file (simply a copy of allied.inc.php) I’ve created in /opt/librenms/includes/polling/os/alliedtelesis.inc.php file.

I’ve been trying to modify this accordingly with the current way Allied Telesis do Mibs, but I just don’t understand enough in this area.

Would someone please be able to give me some help?’ 

I'm basically modifying the current allied.inc.php with the new mib information.

Here’s a pastebin of the enterprise mib walk - http://pastebin.com/WjH5d9Q2
**Note:** I’ve run the command with translation, and then without (-On variable).

Here’s just the initial output from a generic SNMP Walk:

```
SNMPv2-MIB::sysDescr.0 = STRING: Allied Telesis router/switch, AW+ v5.4.7-1.5
SNMPv2-MIB::sysObjectID.0 = OID: AT-PRODUCT-MIB::atx93028GTX
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (60019) 0:10:00.19
SNMPv2-MIB::sysContact.0 = STRING: Matt
SNMPv2-MIB::sysName.0 = STRING: d2-x930
SNMPv2-MIB::sysLocation.0 = STRING: <LOCATION>
SNMPv2-MIB::sysServices.0 = INTEGER: 6
SNMPv2-MIB::sysORID.1 = OID: SNMP-FRAMEWORK-MIB::snmpFrameworkMIBCompliance
SNMPv2-MIB::sysORID.2 = OID: SNMP-MPD-MIB::snmpMPDCompliance
SNMPv2-MIB::sysORID.3 = OID: SNMP-USER-BASED-SM-MIB::usmMIBCompliance
SNMPv2-MIB::sysORID.4 = OID: TCP-MIB::tcpMIB
SNMPv2-MIB::sysORID.5 = OID: UDP-MIB::udpMIB
SNMPv2-MIB::sysORID.6 = OID: SNMP-VIEW-BASED-ACM-MIB::vacmBasicGroup
SNMPv2-MIB::sysORDescr.1 = STRING: The SNMP Management Architecture MIB.
SNMPv2-MIB::sysORDescr.2 = STRING: The MIB for Message Processing and Dispatching.
SNMPv2-MIB::sysORDescr.3 = STRING: The management information definitions for the SNMP User-based Security Model.
SNMPv2-MIB::sysORDescr.4 = STRING: The MIB module for managing TCP implementations
SNMPv2-MIB::sysORDescr.5 = STRING: The MIB module for managing UDP implementations
SNMPv2-MIB::sysORDescr.6 = STRING: View-based Access Control Model for SNMP.
SNMPv2-MIB::sysORUpTime.1 = Timeticks: (1) 0:00:00.01
SNMPv2-MIB::sysORUpTime.2 = Timeticks: (1) 0:00:00.01
SNMPv2-MIB::sysORUpTime.3 = Timeticks: (1) 0:00:00.01
SNMPv2-MIB::sysORUpTime.4 = Timeticks: (1) 0:00:00.01
SNMPv2-MIB::sysORUpTime.5 = Timeticks: (1) 0:00:00.01
SNMPv2-MIB::sysORUpTime.6 = Timeticks: (1) 0:00:00.01
```

**From the above output:**
Hardware: atx93028GTX - i.e. AT-x930-28GTX
Software: AW+
Version: 5.4.7-1.5

The following document explains how the Allied Telesis mibs are set up: http://alliedtelesis.com/sites/default/files/snmp_mibs_0.pdf

Any assistance is appreciated.

Thanks,

Matt

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
I can see you've got a thread open on the community site about this, the suggestion was to open a pull request rather than an issue as we can what it is you've done and advise on what is wrong. 

However you don't need to delete the old OS and instead built on it.

**Comment by mattie47** [comment]
@laf 

>However you don't need to delete the old OS and instead built on it.

I deleted it because "allied" isn't correct for the vendor's name. 10 years ago there was a period where Allied Telesis changed names in certain parts of the world from "Allied Telesyn" to Allied Telesis. I suspect for this reason whoever originally created the file called it "allied" to incorporate both names. 

Note that the vendor enterprise OID (.1.3.6.1.4.1.207) is the same.

>I can see you've got a thread open on the community site about this, the suggestion was to open a pull request rather than an issue as we can what it is you've done and advise on what is wrong.

So are you suggesting I submit a PR with it not in a working state? 

All I'm asking for is help with the current mibs in getting the alliedtelesis.inc.php working properly. 

Thanks,

Matt

**Comment by laf** [comment]
So if the OS name needs changing then we need to send an alert out to users but we can cross that bridge when we come to it.

Yes submit the PR so we can comment on it, it's much much easier to see what you are doing rather than having people read through diffs or even find the changes in the first place.
