### ISSUE TITLE
api not found

### ISSUE THREAD

**Issue by daylicron** [librenms/librenms#7664]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

Version 1.33

- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 201605-3592-g13f0b9726
DB Schema | 214
PHP       | 7.0.19-1
MySQL     | 10.1.26-MariaDB-0+deb9u1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

- [] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Hello Ladies and Gentlemen,

I'm running LibreNMS on a Debian 9, apache2 2.4.25, php7 + php7-fpm. This way it's super fast, but the API is not working. Before I upgraded from Debian 8 and php 5.5 it worked fine.

[Here a curl output on the api_v0.php](https://pastebin.com/Nwps02dB)

[Here the rewrite log about the same curl earlier](https://pastebin.com/AWe00FJj)

[Here my .htaccess](https://pastebin.com/sVR09asR)

Here you have my fpm include of the virtual host:
```
        <FilesMatch \.php$>
                SetHandler "proxy:unix:/run/php/php7.0-fpm.sock|fcgi://localhost"
        </FilesMatch>
```

I can access every file in my librenms/html directory, execept the api_v0.php. The file itself is accessable by www-data as i show you below:
```
-rw-r--r-- 1 librenms librenms 11K Oct 25 09:24 html/api_v0.php

librenms@server:/opt/librenms$ groups
librenms www-data

```
The Webgui is working fine. Only the api is not running at all.

Thank you in advance!

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
