### ISSUE TITLE
Cambium Refactor

### ISSUE THREAD

**Issue by pheinrichs** [librenms/librenms#7702]
I would like to open this issue to start the talk for cambium refactoring. 
I've started a branch for concept on my thoughts on the process and what would all need to take place.

https://github.com/pheinrichs/librenms/tree/cambium-refactor

My thoughts on the process is to break down the cambium os to MIB specific groups, if the hardware uses a separate MIB create a new OS for that cambium device. A lot hardware are using separate mibs to handle similar tasks, this is where the messy code comes in currently with the large amount of conditionals.

Where now: 
os Cambium = epmp(CAMBIUM-PMP80211-MIB), 
pmp(WHISP-BOX-MIBV2-MIB), 
ptp650(CAMBIUM-PTP650-MIB,
 ptp250(CAMBIUM-PTP250-MIB)

Refactored would be 
os = epmp
os = pmp
os = ptp650
os = ptp250

Doing so, would then make using the refactored wireless section @murrant  created much easier and reduce the amount of clutter created by the 'cambium' monster I Created.

**Comment by laf** [comment]
You really should just submit a pull request, it's much easier to talk through code when people can see it, see diffs and comment on those sections :)
