### ISSUE TITLE
Brocade ICX False CPU 100% issue ?

### ISSUE THREAD

**Issue by kafej** [librenms/librenms#7708]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the ====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-86-gb79d106
DB Schema | 215
PHP       | 7.0.24
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Database connection successful
[OK]    Database schema correct

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
**https://p.libren.ms/view/478be92d
https://p.libren.ms/view/bc33e54b
https://p.libren.ms/view/0cd78610**

- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hi,

I think there is problem with Brocade ICX devices and processor CPU usage.
![obraz](https://user-images.githubusercontent.com/1838978/32692186-d850464a-c713-11e7-9128-b8448c00a2b4.png)
![obraz](https://user-images.githubusercontent.com/1838978/32692195-ef457abe-c713-11e7-8d5e-732cfe4c6ec9.png)

I have the same false CPU 100% result on every brocade ICX devices...

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by kafej** [comment]
Sorry, I wrote this post two times and forget at second time to paste

**Comment by kafej** [comment]
I find OID for CPU 
.1.3.6.1.4.1.1991.1.1.2.1.50
