### ISSUE TITLE
HP iPDU alerting becauuse of wrong default Voltage limits

### ISSUE THREAD

**Issue by csirek** [librenms/librenms#7727]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 1.33-97-g29fc07f
DB Schema | 215
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

https://p.libren.ms/view/a6b6fa1a
https://p.libren.ms/view/11e4ab7a
https://p.libren.ms/view/0fadc8d0

- [x] Please provide as much detail as possible.

All of our HP iPDU devices are in ALERT state (without any alert rule) because the Health -> Voltage fileds shows us a wrong LOW and HIGH Limit:

Device     Sensor                                     Current    Low Limit High Limit
nlpdu37	MPDU #1 Voltage	￼		229.6V	1953.3V	2642.7V
nlpdu37	MPDU #2 Voltage	￼		229.7V	1954.15V	2643.85V
nlpdu37	MPDU #3 Voltage	￼		229.6V	1953.3V	2642.7V
nlpdu37	MPDU #4 Voltage	￼		229.4V	1954.15V	2643.85V
nlpdu37	MPDU #5 Voltage	￼		229.4V	1953.3V	2642.7V
nlpdu37	MPDU #6 Voltage	￼		229.5V	1954.15V	2643.85V

Looks like the good Limit value are multiplied by 10. 

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
@csirek Limits are guessed when the device is first added.  Unfortunately, voltage for iPDU was not being divided by 10 like it should have been.  This was fixed recently.

Your options to fix: 
1. Go through and manual set the limits under device settings -> health.
2. Delete and re-add the device (will lose historical data)
3. Update limits directly in mysql (only recommended if you have a large amount of these devices)
