### ISSUE TITLE
Distributed poller bug - SQL-Schema / DB Clean Up still runs if daily updates are turned off

### ISSUE THREAD

**Issue by shimamizu** [librenms/librenms#7733]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

@murrant and I have found a bug that needs fixing. 
For distributed poller installs, it should never do:

```Updating SQL-Schema                                OK```

However... it turns out it properly skips this is daily updates are turned on, but still runs it anyway if daily updates are turned off. 

For now the behavior should be that it never runs this on distributed poller installs because there is no remote locking (yet) for these and running it on all pollers is not ideal. 

At some point finding a way to enable remote locking + specifying a single server to do DB updates/clean up would be ideal. For now, we should fix the bug and SQL updates can be run manually. 

Current bug behavior on distributed poller:
Updates turned off: 
```
Checking PHP version                               OK
Updating SQL-Schema                                OK
Cleaning up DB                                     OK
```

Updates turned on: 

```
Checking PHP version                               OK
Updating to latest codebase                        OK
```

**Comment by laf** [comment]
Fixed with #7735
