### ISSUE TITLE
Overlib Mouse Over Issue: Font sizes aren’t consistent

### ISSUE THREAD

**Issue by RobsanInc** [librenms/librenms#7746]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

### ====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-115-g47a36b1
DB Schema | 215
PHP       | 7.1.10
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
N/A
- [x ] Please provide as much detail as possible.
Mouse hover over graphs don't have the same size header font labels.  See the image from my communtiy.librenms.org post, taken from the LibreNMS demo, I have the same issue with my git version.

[https://community.librenms.org/t/overlib-mouse-over-issue-font-sizes-arent-consistent/2597](url)

- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by RobsanInc** [comment]
laf,

The font sizing issue has been corrected but now it's created a new issue.  See the graph formatting problem:

![librenms7761](https://user-images.githubusercontent.com/13755535/32963191-2e3abc06-cb9d-11e7-94ba-04c4a55d1643.png)

**Comment by laf** [comment]
Pushed a fix to include a missing line break
