### ISSUE TITLE
New Comet sensors

### ISSUE THREAD

**Issue by paulierco** [librenms/librenms#7764]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-133-gc9728a1
DB Schema | 215
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 5.5.47-0+deb8u1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

Dear all,

I need your help to register Comet sensors.
Already have one on my desk: [http://www.cometsystem.com/products/reg-T3610](http://www.cometsystem.com/products/reg-T3610)

Mib Tables: [http://www.cometsystem.com/userfiles/file/download/mibtables.zip?time=1510929158&FixForIE=.zip](http://www.cometsystem.com/userfiles/file/download/mibtables.zip?time=1510929158&FixForIE=.zip)

./discovery -h hostname - [https://pastebin.com/C56N4t3z](https://pastebin.com/C56N4t3z)
./poller.php -h hostname - [https://pastebin.com/Fze2AYFq](https://pastebin.com/Fze2AYFq)
snmpbulkwalk - v1 snmp. - Cannot send V2 PDU on V1 session 

Paul

**Comment by laf** [comment]
Use snmpwalk instead then, we need the snmpwalk data to add this device.

**Comment by paulierco** [comment]
snmp walk - [https://pastebin.com/LsGqWc7H](https://pastebin.com/LsGqWc7H)
snmp debug - [https://pastebin.com/JHmF41eN](https://pastebin.com/JHmF41eN)

**Comment by laf** [comment]
For the data you gave us, I can only see humidity and temp, the mibs seem to confirm this.

Please test #7854
