### ISSUE TITLE
PR #7614 break pre-cache in yaml discovery file

### ISSUE THREAD

**Issue by tomarch** [librenms/librenms#7777]
My zywall device have vpn sensor state (from yaml file). Description is made with a pre-cache oid (.vpnConnectionName)
Since the 06/11/2017, the sensors state description appear like "vpn : {{ $vpnConnectionName }}"

I have revert both file includes/discovery/functions.inc.php and includes/discovery/sensors.inc.php from previous version and it work again.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` 
section of `./validate.php` which you can run from the cli.
====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-145-ga56267e
DB Schema | 215
PHP       | 7.0.25
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
Can you please provide this information: http://docs.librenms.org/Support/FAQ/#faq20 ?

**Comment by tomarch** [comment]
Sure !
discovery : https://p.libren.ms/view/9db0b768
poller: https://p.libren.ms/view/a40bf03f
snmpbulkwalk: https://p.libren.ms/view/ec313633
