### ISSUE TITLE
newdevice: Add support for Cisco FTD Devices

### ISSUE THREAD

**Issue by Blorpy** [librenms/librenms#7783]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
`Component | Version
--------- | -------
LibreNMS  | 1.33-148-g67e83cc
DB Schema | 215
PHP       | 7.1.11
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.5.6
SNMP      | NET-SNMP 5.7.2`
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Hoping to get support for the newish Cisco FirePOWER 2100 devices, right now they are detected as a generic device. These are some interesting combination of a Sourcefire device and ASA code. 

Discovery: https://p.libren.ms/view/0899edb4
Poller: https://p.libren.ms/view/bd987b19
snmpwalk: https://p.libren.ms/view/ec0ed01a

Thanks!

**Comment by laf** [comment]
Please see this issue: https://github.com/librenms/librenms/issues/4524

If you can provide some more insight into this then please do share.

**Comment by slinderud** [comment]
@laf What kind of information do you need to add support for this device?
I'm really interested in this as i will be running libre against two of these FWs.

I'm happy to provide you any information you need to add support for this

**Comment by laf** [comment]
#7887 submitted. Basic detection as the data in the walk didn't have anything special in it. Please give it a test.

**Comment by slinderud** [comment]
@laf Thanks for your qucik reply!
Seems like the detection did not work. I've added a debug of the discovery.
[discovery-ros-fw-f2110-1.mgt.osc.local.txt](https://github.com/librenms/librenms/files/1545179/discovery-ros-fw-f2110-1.mgt.osc.local.txt)

**Comment by Blorpy** [comment]
Discovery isn't working for me either, still showing as generic. I'm polling directly into the ASA part/LINA (which is what I provide for discovery/poller output earlier). LINA is what you would want to poll for interface usage. For things like CPU usage, memory usage, environmentals, you would want to poll FTD (which I have not yet provided discovery/poller info for). FXOS on the 2100s isn't really interacted with for configuration, but I think this is the part that varies between series. 

Keep in mind I'm referring to the 2100s, I know the architecture is pretty similar but it might vary enough that this doesn't apply.

**Comment by laf** [comment]
The PR is specific for the data you've provided, if you've applied the patch then you might need to remove  `cache/os_defs.cache` and re-discover.

**Comment by Blorpy** [comment]
Removing the cache mentioned did it, thanks. 

I imagine this issue is good to be closed; support for things like processor usage, memory usage, etc, will likely have to come from polling the Linux part of FTD and not the ASA part of FTD, but this appears platform dependent as well and not something I'd have time to dig into right now...

This PR looks good to me, no issues to note, thanks!

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/cisco-firepower-fpr-2130-shown-as-generic-device/11650/1
