### ISSUE TITLE
Change the Default Alert Email Subject

### ISSUE THREAD

**Issue by terrytibbles** [librenms/librenms#7792]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Hello,

Is it possible to update the default email alert subjects, to something more readable? At the moment I get:

Alert for device <hostname> - Device DOWN
Device <hostname> recovered from Device DOWN

These are slightly modified from the default, as they weren't very meaningful. I would propose:

```
Alert for device <hostname> - Device DOWN
Alert for device <hostname> - Device UP
```

or

```
LibreNMS alert: device <hostname> DOWN
LibreNMS alert: device <hostname> UP
```

Thanks.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
