### ISSUE TITLE
Missing RRD file and directory

### ISSUE THREAD

**Issue by cwgueco** [librenms/librenms#781]
I have installed the librenms package on a Debian linux (7.8) with Apache/2.2.22 (Debian). I have followed the instructions on https://github.com/librenms/librenms/wiki/Installation-%28Debian-Ubuntu%29 using an external MySQL server. Installation is via the web installer (install.php)

After adding a device which was detected and SNMP strings are workings. Graphs are not generated properly as I have this error in the RRDTool output:
ERROR: opening '/opt/librenms/rrd/xxxx/poller-perf.rrd': No such file or directory 

The rrd directory is already set to www-data/www-data ownership but when I add a device, no directory is created in this location. 

Any ideas?

**Comment by laf** [comment]
Hi @cwgueco.

I think those docs are upto date enough but we are switching off the wiki in favour of http://docs.librenms.org

Don't think that will help in this scenario though. Have you got the cron file setup and running correctly?

**Comment by laf** [comment]
Feel free to jump on irc if you need anymore help or re-open this issue if we can help further.

**Comment by cwgueco** [comment]
Thanks for the reply. Checked my installation and forgot to include the cron poller jobs. So far it is graphing for Cisco network devices. Now my next problem is with non-Cisco devices (i.e. HP Comware) which are listed as Generic devices :)

**Comment by laf** [comment]
Should be easy to fix. 

Can you paste an snmbulkwalk to pastebin then link here. Something like:

snmpbulkwalk -v2c -c public -m /opt/librenms/mibs HOSTNAME

**Comment by cwgueco** [comment]
Thanks for the reply. I wil raise another issue related to this.
