### ISSUE TITLE
Aruba IAP Wireless Controller. Shows APs with the same name as the controller. 

### ISSUE THREAD

**Issue by kkrumm1** [librenms/librenms#7824]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-177-g461b39e
DB Schema | 217
PHP       | 7.0.25
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
`====================================
 section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

All AP's are discovered with the same name as the controller. 
![image](https://user-images.githubusercontent.com/27959419/33407041-2c27316e-d535-11e7-8355-148f88f7d465.png)

Discovery Debug: https://gist.github.com/kkrumm1/3ecccf25e0023ca7182b49168cbbe172#file-aurba-discovery-debug
Poller Debug: https://gist.github.com/kkrumm1/bda8f2fd705f12d431a8946f060da5c4#file-aurba-poller-debug
SNMP Walk: https://gist.github.com/kkrumm1/4b3ac4cd9f70606fc2e2ca3182693913#file-aurba-snmp-walk

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
I looked at this and I think we had a discussion. Not sure we can do much about this right now. We don't have anything else to distinguish names.
