### ISSUE TITLE
Table updates tracking

### ISSUE THREAD

**Issue by laf** [librenms/librenms#7831]
Using this to track the PRs done by @crcro so we can make sure that we have all tables.

- [x] alerts / alertlog table #7765
- [x] eventlog table #7793
- [x] syslog table #7796
- [x] devices table #7809
- [x] ports table #7827
- [x] graylog table #7832
- [x] services table #7628
- [x] health table #7834
- [x] wireless table #7836

**Comment by laf** [comment]
@crcro If you can sort those last two out to be in the same format then we can do a code review and merge them all in.

**Comment by crcro** [comment]
@laf ... services I think that are already made by @Rosiak in PR #7628

**Comment by laf** [comment]
Thanks, I've not checked it recently. It needs to have the same style you've proposed (or did you take the proposal from that?).

**Comment by crcro** [comment]
I took the style from last proposal on that PR.

**Comment by crcro** [comment]
@laf ... alert-log table i think that has already the "agreed" form.

**Comment by crcro** [comment]
@laf ... i've pushed the alertlog table into the alert table PR

**Comment by laf** [comment]
@crcro I've made a few comments in a couple of PRs.

My only overall issue is the size of the status coloured box varies wildly. I think we should have a default height to make them more consistent and allow them to grow taller if they need to.

I've merged all the branches together into one branch to make it easier to review:

https://github.com/librenms/librenms/compare/master...laf:table-refresh?expand=1&w=1

**Comment by laf** [comment]
Btw, great work with it :)

**Comment by crcro** [comment]
@laf ... the width should be matched to 7px from .alert-status css class in PR #7765 and the height should be auto adjusted based on parent height from the librenms.js in the same PR.

**Comment by laf** [comment]
@crcro width is fine, it's the height I'm talking about. Should set a min-height value in the css so that it for the most part remains consistent.

**Comment by crcro** [comment]
@laf ... pushed that min-height value and some js check in PR #7765

**Comment by laf** [comment]
So close with this now :) Just a few more comments in some PRs

**Comment by laf** [comment]
@crcro I think it's just the fix the ports layout and we're done with this.

**Comment by laf** [comment]
All merged in. Bit thanks to @crcro and @Rosiak for these.

**Comment by murrant** [comment]
@crco In the devices list, if we click on one of the graph views, we are missing a header now (also there is no pagination, but that was broken before)

After:
![image](https://user-images.githubusercontent.com/39462/34415447-62a8610a-ebb4-11e7-92df-9883cab3f11d.png)

Before:
![image](https://user-images.githubusercontent.com/39462/34415462-734e6310-ebb4-11e7-8a9d-c7a7d49c5839.png)

**Comment by murrant** [comment]
@crcro o In the devices list, if we click on one of the graph views, we are missing a header now (also there is no pagination, but that was broken before)

After:
![image](https://user-images.githubusercontent.com/39462/34415447-62a8610a-ebb4-11e7-92df-9883cab3f11d.png)

Before:
![image](https://user-images.githubusercontent.com/39462/34415462-734e6310-ebb4-11e7-8a9d-c7a7d49c5839.png)

**Comment by crcro** [comment]
@murrant this should fix missing headers PR7981
