### ISSUE TITLE
Add support for FortiGate 600c 

### ISSUE THREAD

**Issue by kafej** [librenms/librenms#7835]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the 

====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-186-ge308287
DB Schema | 217
PHP       | 7.0.24
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Database connection successful
[OK]    Database schema correct

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/8642ffb2
https://p.libren.ms/view/93ca75bc

- [x] Please provide as much detail as possible.

Hi,

Firstly You are so awesome :wink:

I have a feature request. Will be awesome if You can add VPN sessions for FortiClient (I can provide Mib files if needed).

For example in my situation this give me everything I need 1.3.6.1.4.1.12356.101.12.2.
.1.3.6.1.4.1.12356.101.12.2.4.1.3.1 <- this one give me the first active user
.1.3.6.1.4.1.12356.101.12.2.4.1.4.1 <- address from connecting is

and how about enable->disable polices ? You plan to add this too ?

How I can help you with this ?
[MIB.zip](https://github.com/librenms/librenms/files/1521315/MIB.zip)

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by kkrumm1** [comment]
You need to provide SNMPWalk also.

**Comment by kafej** [comment]
No problem.
[snmpbulkwalk.txt](https://github.com/librenms/librenms/files/1522401/snmpbulkwalk.txt)

**Comment by kafej** [comment]
No problem

https://p.libren.ms/view/b17760a8

**Comment by kafej** [comment]
How i can help with verification:
.1.3.6.1.4.1.12356.101.12.2.4.1.3.1 <- this one give me the first active user
.1.3.6.1.4.1.12356.101.12.2.4.1.3.2 <- this one give me the second active user
.1.3.6.1.4.1.12356.101.12.2.4.1.4.1 <- address from user1 connecting is
.1.3.6.1.4.1.12356.101.12.2.4.1.4.2 <- address from user2 connecting is

**Comment by laf** [comment]
I'm afraid you'll need to post these as feature requests on the community site as we don't have base support for any of these metrics.

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
