### ISSUE TITLE
main inventory page not working with chrome, but works with firefox.

### ISSUE THREAD

**Issue by yvesboudreau** [librenms/librenms#7838]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

On chrome Version 62.0.3202.94 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/12088351/33494328-e4ecdcba-d690-11e7-81b2-1d74e116d146.png)

Works on firefox 57.0

![image](https://user-images.githubusercontent.com/12088351/33494392-1e8353a0-d691-11e7-99e0-f91b9b2425c5.png)

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by yvesboudreau** [comment]
Component | Version
--------- | -------
LibreNMS  | 1.33-188-g4a03e78
DB Schema | 219
PHP       | 7.0.20
MySQL     | 10.1.24-MariaDB
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.2

**Comment by yvesboudreau** [comment]
Chrome /debug=yes/ for PHP errors:

[librenms-chrome-inventory-debug.txt](https://github.com/librenms/librenms/files/1522365/librenms-chrome-inventory-debug.txt)

**Comment by kkrumm1** [comment]
Did you increase PHP memory? 
https://docs.librenms.org/#Support/Configuration/#core

**Comment by laf** [comment]
I'd check the developer console, I reckon it's some data in your db not being escaped.

**Comment by yvesboudreau** [comment]
I changed the PHP memory as recommended.
Still seeing the error (not seen the inventory, that is )

Seen this in the dev console on chrome, not sure if it's relevent?

`(index):1 Uncaught RangeError: Maximum call stack size exceeded`

**Comment by zombah** [comment]
Overview->Inventory also not working in Firefox 52.5.3 here,
web console error:
SyntaxError: unterminated string literal

**Comment by laf** [comment]
Please test: https://github.com/librenms/librenms/pull/8110

Details on how to test are in the PR.

**Comment by zombah** [comment]
@laf for me inventory is still empty even with 8110 applied. 
Also checked with my devel librenms which is much smaller inviroment with only ~10 devices and all my browsers even ff 52.5.3 show overview-inventory fine, so it looks like inventory parsing problem to me not browser related.

**Comment by laf** [comment]
@zombah Sorry wasn't directed at you :) It's for @yvesboudreau.

Your issue is different, the error in the console will have a line, in that it will most likely have some bad data like " or ' within a select option, have a look and see if you can spot it.

**Comment by zombah** [comment]
@laf Yes after some thinking and testing it seems i have different problem not connected to this one. Sorry for the noise.

**Comment by laf** [comment]
Marking as won't fix. This will be dealt with in the Webui rewrite.
