### ISSUE TITLE
Bad PSU Temp Values Warnings

### ISSUE THREAD

**Issue by networkpadawan** [librenms/librenms#7849]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-180-gf0a908c
DB Schema | 217
PHP       | 7.0.19
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

[poller.txt](https://github.com/librenms/librenms/files/1526642/poller.txt)
[discovery.txt](https://github.com/librenms/librenms/files/1526643/discovery.txt)
[snmpbulk.txt](https://github.com/librenms/librenms/files/1526650/snmpbulk.txt)

- [x] Please provide as much detail as possible.

I would like to know the current OID´s used to poll psu temperature values for arista?
I´m getting these warnings randomly:
Temperature Power supply sensor under threshold: -100000000 (< 20.3 )
On the next poll it disappears.

- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by kkrumm1** [comment]
You can adjust the High and Low Values in the Web UI in device settings -> Health.

But I think it comes from here. https://github.com/kd7lxl/librenms/blob/9df528979f005fc80bffb213b6b56c2751474a5e/includes/discovery/functions.inc.php

**Comment by networkpadawan** [comment]
I think it´s a bug with arista, because randomly I get -100000 but then it goes back to 29º and stays like that for a while. that´s why im searching for the OID that maps to this value.

**Comment by laf** [comment]
The arista devices just use the standard entity-sensor-mib from `includes/discovery/sensors/entity-sensor.inc.php`

You can see the OIDs in your DB: `SELECT * FROM sensors WHERE device_id=X AND sensor_class='temperature';`

If it's going between -100000 and the correct value then yes, most likely a device bug. We don't see this on ours btw.

**Comment by networkpadawan** [comment]
I think so as well, what eos version are you using?

Also, is there some explanation that you can see for the gaps in the dates for the 2 power supplies?
|      4588 |              0 | temperature  |       331 | snmp        | .1.3.6.1.2.1.99.1.1.1.4.100711101 | 100711101    | entity-sensor | Power supply sensor             |             10 |                 1 |             29 |           70 |              NULL |             20.3 |                  NULL |            1 | No            | 100711101        |                           | 2017-12-05 09:14:35 |        28.5 |           |
|      4594 |              0 | temperature  |       331 | snmp        | .1.3.6.1.2.1.99.1.1.1.4.100721101 | 100721101    | entity-sensor | Power supply sensor             |             10 |                 1 |             29 |           70 |              NULL |            20.65 |                  NULL |            1 | No            | 100721101        |                           | 2017-12-04 20:24:39 |  -100000000 |           |

**Comment by laf** [comment]
4.17.1.1F

The dates only update when values change now rather than every poll. So in essence, that's the last time the sensor value changed.

**Comment by networkpadawan** [comment]
i´m still on 4.12 and 4.16...
that is very strange, I´m polling the value right now and I get SNMPv2-SMI::mib-2.99.1.1.1.4.100721101 = INTEGER: 290 for the last hour, but it still shows:
    4594 |              0 | temperature  |       331 | snmp        | .1.3.6.1.2.1.99.1.1.1.4.100721101 | 100721101    | entity-sensor | Power supply sensor             |             10 |                 1 |             29 |           70 |              NULL |            20.65 |                  NULL |            1 | No            | 100721101        |                           | 2017-12-04 20:24:39 |  -100000000 |           |

But on the librenms dashboard says : Power Supply Sensor Min 29º Avg 29º Max 29º like the -100000000 value is ignored.

**Comment by laf** [comment]
I'm not sure what you're reading here but that mysql output shows the value of 29 which is 290 / 10. The -1000000 is the last previous value it had .

**Comment by networkpadawan** [comment]
So it had a value of -100000000 and now it´s 29, correct? so the average should not be 29 and the min value should not be -100000000, IF i´m thinking correctly:)
this is the what is confusing me now:
![temp](https://user-images.githubusercontent.com/870298/33604372-a1aa305e-d9ad-11e7-9864-76ed5c9aceac.JPG)
the graph seems to be ignoring the last previous value

**Comment by laf** [comment]
-100000 is outside the scope of what we store in rrd so it will just ignore it.

**Comment by networkpadawan** [comment]
ah, so that´s the last different value. to save resources. ok, it makes sense:) thanks for the help
