### ISSUE TITLE
Raritan KVM detected as Raritan PDU

### ISSUE THREAD

**Issue by kedearian** [librenms/librenms#7866]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X ] Please include all of the information between the `

LibreNMS  | 1.33-209-gf7aed1e
DB Schema | 221
PHP       | 7.0.25
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.2

` section of `./validate.php` which you can run from the cli.

- [X ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

Discovery - https://p.libren.ms/view/ed7e2e97
Poller - https://p.libren.ms/view/cac2532b
SNMP - https://p.libren.ms/view/317d6984
Vendor MIB - https://p.libren.ms/view/6e758132

- [X ] Please provide as much detail as possible.

I have a new Raritan Dominion DKX3-116, it shows up as a Raritan PDU instead of a KVM. It's missing the information about ports in use. I believe it's being mis-discovered. 

- [X ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Looks like we need to split a few raritan devices out in to other OS'

**Comment by laf** [comment]
Patience :)

**Comment by laf** [comment]
Ok I've submitted initial detection. However your snmpwalk is missing loads of data. Please provide the output from:

`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .1.3.6.1.4.1.13742`

**Comment by kedearian** [comment]
Attached is the output. Its 176k lines so I don't think pastebin's a great idea.
[raritan-pdu.txt](https://github.com/librenms/librenms/files/1782763/raritan-pdu.txt)

**Comment by kedearian** [comment]
For the KVM I get " .1.3.6.1.4.1.13742 = No Such Object available on this agent at this OID ". Attached is the results from the PDU.
[raritan-pdu.txt](https://github.com/librenms/librenms/files/1782796/raritan-pdu.txt)
