### ISSUE TITLE
device sensors: Aruba 5406 zl2 

### ISSUE THREAD

**Issue by kkrumm1** [librenms/librenms#7870]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the 
```
Component | Version
--------- | -------
LibreNMS  | 1.33-214-g0c36cd7
DB Schema | 222
PHP       | 7.0.25
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
``` 
section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Aruba 5406 zl2 add sensors for Fan state and Power supply state.
The Aruba 5406 zl2 is a new version of the HPE Procurve 5406 zl. I'm not sure if we need to make a new device yaml for this or just add to existing code? 
https://community.hpe.com/t5/ProCurve-ProVision-Based/Aruba-5406R-zl2-Switch-SNMP-Values/td-p/6863424

SNMPWalk: https://gist.github.com/kkrumm1/94fbaa93bcab7d5c6476422fcd091715#file-snmpwalk-5406-zl2
Discovery: https://gist.github.com/kkrumm1/82ec4203c11f1eb4283342a3b91c9e4b#file-5406-zl2-discovery
Poller: https://gist.github.com/kkrumm1/e2fb2942f884732a278fdc5cbff5dcf0#file-5406-zl2-poller

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
@kkrumm1 submitted a PR.

Not sure about changing the os name on this one though
