### ISSUE TITLE
Add Support for Sixnet

### ISSUE THREAD

**Issue by maladd3** [librenms/librenms#7879]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

### 
Component | Version
--------- | -------
LibreNMS  | 1.33-219-gb3f09e7
DB Schema | 222
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 5.7.20-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

discovery - https://p.libren.ms/view/0ba03d8d
poller - https://p.libren.ms/view/87d86c13
snmpbulkwalk - https://p.libren.ms/view/1ff85eac

This is a sixnet switch, by Red Lion.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
I've submitted a pull request to add support for this device:

https://github.com/librenms/librenms/pull/8576

Without a MIB though it gives nothing more than port information.

**Comment by laf** [comment]
https://p.libren.ms/view/raw/3e33d829 more data

**Comment by maladd3** [comment]
You need more data?

**Comment by laf** [comment]
No, I was posting your last one in the issue so it's all together.

**Comment by maladd3** [comment]
Ok, thank you @laf . Just making sure.
