### ISSUE TITLE
VMware ESXi 5.5 - Virtual Machines Tab missing

### ISSUE THREAD

**Issue by kafej** [librenms/librenms#7882]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the ====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-220-g2370072
DB Schema | 222
PHP       | 7.0.24
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Database connection successful
[OK]    Database schema correct
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/ef3c20b7
https://p.libren.ms/view/9cdb7365
https://p.libren.ms/view/1a67c4d2
- [x] Please provide as much detail as possible.
VMware ESXi 5.5 - Virtual Machines Tab missing

snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh doesnt give me want I looked for, but this one:
snmpwalk -v 1 -c public -m ALL  .1
https://p.libren.ms/view/78e58aba
The name of machine: SNMPv2-SMI::enterprises.6876.2.1.1.2.2
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This has been answered before on here and the community forum. Please search on both before posting new issues.

**Comment by kafej** [comment]
Yeh I saw them... but I wasn't able to find someone who point this:

snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME . | ./pbin.sh doesnt give me want I looked for, but this one:
snmpwalk -v 1 -c public -m ALL .1
https://p.libren.ms/view/78e58aba
The name of machine: SNMPv2-SMI::enterprises.6876.2.1.1.2.2
