### ISSUE TITLE
No reading temperature and voltage graphs on mikrotik RouterOS RB952Ui-5ac2nD

### ISSUE THREAD

**Issue by batman84** [librenms/librenms#7888]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
/opt/librenms# ./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-224-gdbeaf3b
DB Schema | 222
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Database connection successful
[OK]    Database schema correct

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

poller 		https://p.libren.ms/view/5ec47efc
discovery 	https://p.libren.ms/view/dbfc83e9
snmpbulwalk 	https://p.libren.ms/view/f494aed9

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
Do you know the oid of the temp and voltage graphs you are looking for?

**Comment by batman84** [comment]
[thinkpad@my.router] /system health> print oid
             active-fan: .1.3.6.1.4.1.14988.1.1.3.9.0
                voltage: .1.3.6.1.4.1.14988.1.1.3.8.0
            temperature: .1.3.6.1.4.1.14988.1.1.3.10.0
  processor-temperature: .1.3.6.1.4.1.14988.1.1.3.11.0
                current: .1.3.6.1.4.1.14988.1.1.3.13.0
              fan-speed: .1.3.6.1.4.1.14988.1.1.3.17.0
             fan-speed2: .1.3.6.1.4.1.14988.1.1.3.18.0
      power-consumption: .1.3.6.1.4.1.14988.1.1.3.12.0
             psu1-state: .1.3.6.1.4.1.14988.1.1.3.15.0
             psu2-state: .1.3.6.1.4.1.14988.1.1.3.16.0
you mean these OIDs?

**Comment by laf** [comment]
Most of those already exist. I believe someone mentioned on Discord that not all Mikrotik support sensors

**Comment by laf** [comment]
I've submitted a PR to add more sensors for RouterOS. However the data you've provided doesn't have any of these in, they aren't returned by the device so I doubt you'll see a difference.
