### ISSUE TITLE
Trend Number of Installed Packages

### ISSUE THREAD

**Issue by supertylerc** [librenms/librenms#789]
Is trending the number of installed packages useful?  I found myself wondering how many have been installed over a period of time, though not for any performance reasons.  It was more of a curiosity.  Would anyone find such trending actually useful (other than satisfying curiosity)?

**Comment by laf** [comment]
We don't use the unix-agent so not for us. Sure it would for some people though :)

**Comment by paulgear** [comment]
Definitely sounds like a useful feature to me.

**Comment by supertylerc** [comment]
I'll start looking into how the unix agent works and adapting the RPM script to provide whatever is necessary to graph the data over time this weekend.

**Comment by paulgear** [comment]
Sounds great, @supertylerc. It would be great if we could keep it generic enough that replacing RPM with dpkg would be viable.

**Comment by laf** [comment]
I could be mistaken but I think @f0o added support for dpkg

**Comment by f0o** [comment]
The dpkg im

**Comment by killsudo** [comment]
You do not need the unit-agent to get a list of installed packages, their type, and when they were installed.

This is completely possible via SNMP and Zenoss leverages it beautifully. You can track installed packages and updates in LibreNMS. Then expanding on that you could alert for known vulnerable packages. This is also helpful if LibreNMS ever add's a 'reporting' feature were users could set the values in a report and LibreNMS would generate the report.

Wanna know how many servers have sshd installed? Easy

Wanna view a list of servers with sshd installed and list packages versions in asc/dsc orders to easily know which box's need a quick update?

# snmpwalk -v2c -cpublic pxe.example.net hrSWInstalled | grep dhcp
HOST-RESOURCES-MIB::hrSWInstalledName.225 = STRING: "dhcp-common-4.1.1-43.P1.el6.centos"
HOST-RESOURCES-MIB::hrSWInstalledName.405 = STRING: "dhcp-4.1.1-43.P1.el6.centos"

# snmpwalk -v2c -cpublic pxe.example.net hrSWInstalled | grep 405
HOST-RESOURCES-MIB::hrSWInstalledIndex.405 = INTEGER: 405
HOST-RESOURCES-MIB::hrSWInstalledName.405 = STRING: "dhcp-4.1.1-43.P1.el6.centos"
HOST-RESOURCES-MIB::hrSWInstalledID.405 = OID: SNMPv2-SMI::zeroDotZero
HOST-RESOURCES-MIB::hrSWInstalledType.405 = INTEGER: operatingSystem(2)
HOST-RESOURCES-MIB::hrSWInstalledDate.405 = STRING: 2014-10-28,15:2:56.0,-5:0

**Comment by f0o** [comment]
@killsudo for what distributions does this apply?

**Comment by f0o** [comment]
Debian Wheezy:
```
snmpwalk -v2c -cpublic localhost HOST-RESOURCES-MIB::hrSWInstalledName
HOST-RESOURCES-MIB::hrSWInstalledName = No Such Object available on this agent at this OID
```

**Comment by killsudo** [comment]
@f0o I don't believe Debian ever bother fixing their net-snmp packages to enable embedded-perl.

This feature works perfect under CentOS/RHEL/etc distros and Juniper etc Network OS's as the Vendors have enabled this MIB to let you pull software info about the installed os via snmp.

I believe Cisco also offers support for it in their OS's if you enable it on the switch. http://tools.cisco.com/Support/SNMP/do/BrowseOID.do?local=en&translate=Translate&objectInput=1.3.6.1.2.1.25.6

Juniper just works

# snmpwalk -v2c -cpublic s2casw.example.net hrSWInstalled | grep JUNOS
HOST-RESOURCES-MIB::hrSWInstalledName.2 = STRING: "JUNOS Base OS boot [14.1X53-D15.2]X53-D15.2]"
HOST-RESOURCES-MIB::hrSWInstalledName.3 = STRING: "JUNOS Kernel Software Suite [14.1X53-D15.2]"
HOST-RESOURCES-MIB::hrSWInstalledName.4 = STRING: "JUNOS Packet Forwarding Engine Support (qfx-ex-x86-32) [14.1X53-"
HOST-RESOURCES-MIB::hrSWInstalledName.5 = STRING: "JUNOS Routing Software Suite [14.1X53-D15.2]"
HOST-RESOURCES-MIB::hrSWInstalledName.6 = STRING: "JUNOS Online Documentation [14.1X53-D15.2]"
HOST-RESOURCES-MIB::hrSWInstalledName.7 = STRING: "JUNOS Crypto Software Suite [14.1X53-D15.2]"
HOST-RESOURCES-MIB::hrSWInstalledName.12 = STRING: "JUNOS Enterprise Software Suite [14.1X53-D15.2]"
HOST-RESOURCES-MIB::hrSWInstalledName.37 = STRING: "JUNOS py-base-i386 [14.1X53-D15.2]"

You could potentially add the support and use it add additional information to devices that support it.

When adding servers you can also use it as a check to determine if it's a rhel/centos and nail down the OS version.

Arch/Gentoo/etc might also support it already but not sure.

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP
