### ISSUE TITLE
LDAP (and AD?) auth getUser does not return level -> API fails

### ISSUE THREAD

**Issue by Ultra2D** [librenms/librenms#7893]
The newly added fake session for API authentication assumes that getUser will also return the user level. It does not for LDAP authentication, and probably neither for AD authentication. I don't know if the API fakes session should be changed (see https://community.librenms.org/t/new-api-restrictions-and-ldap-userlevel-issue/2772/2), or the user level should be added to all getUser functions.

API:
https://github.com/librenms/librenms/blob/9d66d7c8976adc175d1ac9a18537cab4a73cf4d6/html/includes/api_functions.inc.php#L25-L32

LDAP:
https://github.com/librenms/librenms/blob/6b5dccc169d529204066b5174392c8b74bd23bc0/LibreNMS/Authentication/LdapAuthorizer.php#L159-L164

AD:
https://github.com/librenms/librenms/blob/6b5dccc169d529204066b5174392c8b74bd23bc0/LibreNMS/Authentication/ActiveDirectoryAuthorizer.php#L219

**Comment by murrant** [comment]
Hmm, looks like Active Directory does set the level properly, but ldap does not.

So, seems to be a bug in LdapAuthorizer.php

**Comment by Ultra2D** [comment]
Seems quite easy to fix. I have already contributed code in the past, but have not signed the CLA apparently. Will have to do that some other time.
