### ISSUE TITLE
 sysObjectID not updating for Cambium cnPilot

### ISSUE THREAD

**Issue by vinitkhandagle** [librenms/librenms#7894]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

After updating Cambium cnPilot shows as generic Device below is the 
`./discovery.php -h HOSTNAME -d ` output

[PasteBin url of `discovery.php`](https://pastebin.com/5NTtcEqC)

**Comment by pheinrichs** [comment]
I'll try and add proper support for this today.

**Comment by murrant** [comment]
@vinitkhandagle can you provide all info requested?

Especially the snmpwalk?

**Comment by vinitkhandagle** [comment]
information:

discovery.php
https://p.libren.ms/view/0b5e1896

poller.php
https://p.libren.ms/view/d4e0d3e3

snmpbulkwalk
https://p.libren.ms/view/3a9e0a2a
