### ISSUE TITLE
canopy 450/450 frequency not correct

### ISSUE THREAD

**Issue by cchance27** [librenms/librenms#7897]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Ran update last night but noticed when i started testing with our canopy450's the wireless overview for frequency is showing in MHz of 569.000Mhz but it should be 5690.000Mhz seems their may be a division or multiplication error in the way the snmp is being imported to the graph?

(Graph in question is under Wireless/Overview

Version | 1.33-227-gc22c879 - Sun Dec 10 2017 16:40:45 GMT-0400

**Comment by pheinrichs** [comment]
We can change the divisor to fit this. Only issue that I've run into with cambium products is the response from their frequency mibs are all over the board. As per the mib

FSK 5.2, 5.4, 5.7 GHz: OID returns MHz
FSK 900 MHz, 2.4 GHz: OID returns 100's of KHz
OFDM: OID returns 10's of KHz"

@murrant  adding a private method in the class that returns the model divisor?

**Comment by murrant** [comment]
@pheinrichs makes sense to me.

**Comment by murrant** [comment]
@cchance27 can you test #7899 and see if that fixes your divisors?
