### ISSUE TITLE
Update Unix Agent Docs

### ISSUE THREAD

**Issue by supertylerc** [librenms/librenms#790]
There's a minor typo in the configuration required for the `bind` script.  Current documentation is (here)[http://docs.librenms.org/Extensions/Agent-Setup/#bind9named].  It states: "Verify that everything works by executing `rdnc stats && cat /etc/bind/named.stats`."  The command should be `rndc`.  See below.

```
[tyler@yoda]~% which rdnc
/usr/bin/which: no rdnc in (/usr/local/bin:/usr/bin:/home/tyler/bin:/usr/local/sbin:/usr/sbin)
[tyler@yoda]~% which rndc
/usr/sbin/rndc
[tyler@yoda]~%
```

Additionally, the configuration required for the `mysql` agent script is not documented.  Another issue is the lack of documentation on the port and protocol for `xinetd` configuration, which is necessary for configuring `firewalld` in CentOS/RHEL 7 and new Fedora releases.  It's also necessary for `iptables` rules.

**Comment by f0o** [comment]
Do you happen to know the command needed for firewalld ?

the port is 6556 TCP

**Comment by supertylerc** [comment]
I read the source on the script and was able to use our automation to provision `firewalld`.   The command would `firewall-cmd --zone=<zone> --add-port=6556/tcp --permanent --reload`.
