### ISSUE TITLE
Web Installer Stage 2 fails at 180 -> 181

### ISSUE THREAD

**Issue by gpavinteractiv** [librenms/librenms#7904]
I am on Centos 7.4, using php 7.1 from remi's repo and Percona Server 5.7

I followed http://librenms-master.readthedocs.io/Installation/Installation-CentOS-7-Apache/ as install guide with package names changed to point to the correct php version. 

librenms repository git cloned a few hours ago

The  Web Installer fails on stage 2 with only one error :
````
...
180 -> 181 ... done (1 errors).
...
Database schema update failed!
````

There is no error in mysql_error.log, nor in /opt/librenms/logs/error_log

**Comment by laf** [comment]
That's not necessarily an issue. Please post on the community forums or discord.

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by gpavinteractiv** [comment]
Got some help on discord, validate.php reported two issues that got fixed by applying the recommended alter tables : 

````
[root@vs-inf-prd-mon-fr-503 librenms]# ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-229-g92f83c2
DB Schema | 222
PHP       | 7.1.11
MySQL     | 5.7.19-17-log
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Database connection successful
[FAIL]  Database: missing index (applications/unique_index)
[FAIL]  Database: missing index (config/uniqueindex_configname)
[FAIL]  We have detected that your database schema may be wrong, please report the following to us on IRC or the community site (https://t.libren.ms/5gscd):
	[FIX] Run the following SQL statements to fix.
	SQL Statements:
	 ALTER TABLE `applications` ADD UNIQUE `unique_index` (`device_id`,`app_type`);
	 ALTER TABLE `config` ADD UNIQUE `uniqueindex_configname` (`config_name`);
[WARN]  You have not added any devices yet.
	[FIX] You can add a device in the webui or with ./addhost.php
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[root@vs-inf-prd-mon-fr-503 librenms]# 
````
The database shema issues where reported here : https://community.librenms.org/t/report-database-schema-issues-here/945/322
