### ISSUE TITLE
Liebert\Virtiv PDUs missing sensor data

### ISSUE THREAD

**Issue by terryb8s** [librenms/librenms#7907]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.33-229-g92f83c2
DB Schema | 222
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
Discovery https://p.libren.ms/view/27add60a
Poller https://p.libren.ms/view/fdde8e7c
SNMP https://p.libren.ms/view/0b5710c9
- [X] Please provide as much detail as possible.
Unable to get power sensors to show by standard or by using MIB auto discovery even though everthing is present in the /opt/librenms/mibs/liebert/LIEBERT-GP-PDU-MIB file.
Sensors that look to be useful
EntryApTotal
EntryEcNeutral
EntryPwrTotal

There are also a bunch of individual sensors for each power plug on the PDU but because the PDUs can be daisy chained together I dont know if its going to be easy to get this correctly.

Have been able to get some of the info i require by adding this to the YAML (I know this is the incorrect way to do it and have since removed it)
```
register_mibs:
    lgpPduAuxMeasTable: LIEBERT-GP-PDU-MIB
    lgpPduPsTable: LIEBERT-GP-PDU-MIB
```

If you need any extra info I am more than happy to provide it.

- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
You're data doesn't contain any information from the `.1.3.6.1.4.1.476.1.42` OID. Can you re-run the snmpbulkwalk command with that OID instead of `.`

**Comment by interduo** [comment]
@terryb8s

**Comment by PipoCanaja** [comment]
Hi there,
Seems that @terryb8s is gone. If you come back around, don't hesitate to reopen this issue with all the data needed.
Bye
