### ISSUE TITLE
Support for EVDO for cellular devices?

### ISSUE THREAD

**Issue by ssa5** [librenms/librenms#7909]
This is in regards to thread opened at support forums - https://community.librenms.org/t/cisco-wireless-rssi-discovery/2626/6. For Cisco routers , currently in file LibreNMS/OS/Ios.php the wireless RSSI discovery uses c3gCurrentGsmRssi. In our location we use EVDO, which would require c3gCurrentEvDoRssi. In particular, SNMPwalk gives me c3gCurrentEvDoRssi.13 = -88. Would it be possible to add in future support for EVDO along with GSM for cellular?

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.
