### ISSUE TITLE
"From name" not used in mail transport?

### ISSUE THREAD

**Issue by olds463** [librenms/librenms#7910]
Opening issue instead of pull request as i'd like some of the regular contributors to confirm. 

It seems in the WebUI for "Email Transport" the "From name" does not get used. 

In the send_mall() function in includes/functions.php 

`        foreach (parse_email($config['email_from']) as $from => $from_name) {
            $mail->setFrom($from, $from_name);
        }
`

You are not using $config['email_name'] instead are looking to call parse_email which is expecting the "From email address" in WebUI ($config['email_from'] to be in the format of: 

`LibreNMS <user@domain.com>`

Is this field obsolete in the WebUI?

**Comment by murrant** [comment]
Looks like an oversight.  It should probably try both. Feel free to send a fix ;)
