### ISSUE TITLE
API Health is null return

### ISSUE THREAD

**Issue by bagusays** [librenms/librenms#7911]
i use the API for get health. But i receive null value. why?

> http://xxx/api/v0/devices/xxx/health

```
{
    "status": "ok",
    "graphs": [],
    "count": 0
}
```

**Comment by laf** [comment]
Works for me. Please ensure you are on the latest version.

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
