### ISSUE TITLE
Cambium PTP 58500 - OS shows as generic

### ISSUE THREAD

**Issue by YukonRob** [librenms/librenms#7914]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 1.33-237-g79c4274
DB Schema | 224
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
[discovery-10.0.20.26.txt](https://github.com/librenms/librenms/files/1561091/discovery-10.0.20.26.txt)

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by YukonRob** [comment]
While still discovering it seems that the 58300 is also coming up as generic

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by YukonRob** [comment]
Here you go for the 58500. 
https://p.libren.ms/view/f4db51c1
https://p.libren.ms/view/a3d1fcad
https://p.libren.ms/view/e96dde8f

**Comment by laf** [comment]
@pheinrichs following on from your recent refactor of the Cambium ptp products, would this be a new OS or fit into an existing one?

**Comment by pheinrichs** [comment]
@laf this will be a new OS. I'll gladly take care of this but will be away for a week or so. 
The full sysobjectId will work just fine for discovery on this.

**Comment by YukonRob** [comment]
Do you want the same info as above for the 58300? It looks like they are running the same firmware.

**Comment by laf** [comment]
Are we going to end up with an OS per hardware device here? Seems silly to me.

**Comment by pheinrichs** [comment]
The pmp 100-450
hardware is all under a single OS as they all use the same mibs and have the same sysObjectId. But the PTP products have different sysobjectIds and all use different mibs to do the same things.

I'm open to other ideas to improve this but imo this was an easy way to keep it clean.

**Comment by laf** [comment]
We can just load a different mib based on the sysObjectID no?

**Comment by pheinrichs** [comment]
@YukonRob If you could provide me with the sysobjectID or the snmpwalk for the 300 that'd be great.

**Comment by YukonRob** [comment]
Is this enough? I can also upload the full file.
.1.3.6.1.2.1.1.1.0 = STRING: "Cambium PTP 58300 25Mbps PTP Wireless Ethernet Bridge, Version 58300-05-04"
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.17713.5

**Comment by pheinrichs** [comment]
@YukonRob That should work perfect, thanks

**Comment by Linux-Maverick** [comment]
@pheinrichs I have the same issue with Cambium PTP49600, PTP58600, and PTP800 units. Should I create a new issue for them, or provide information here?

**Comment by pheinrichs** [comment]
@Linux-Maverick either is fine, I should be able to take care of those next week. I have a few changes to make on the current PR anywho.

@laf do You care if I just include it all in the current PR after the requested changes you added?

**Comment by laf** [comment]
@pheinrichs All in one is fine but it may slow down merging. It's up to you how you want to do it.

**Comment by Linux-Maverick** [comment]
@pheinrichs I was collecting the various pieces of requested information this morning when I noticed that all of my radios (PTP600 and PTP800) are now listed as "PTP 500" platform and "Cambium PTP 300/500" operating system. I imagine I wasn't seeing any difference after running github-apply last Friday because I should have run a discovery script that cron eventually ran on its own. Anyway, it's getting closer, but in the process LibreNMS also changed some VMware ESXi 6.0, Slackware and Ubuntu boxes from Linux to Cambium PTP 300/500 hosts. Hmm. Something else I neglected to do?

I'm still digging.

**Comment by pheinrichs** [comment]
@Linux-Maverick I do think there is a slight issue with discovery on the branch, I noticed this morning anyway, Most likely related. I could still use the snmpwalk info for the other devices so i can properly add support for those too.

**Comment by Linux-Maverick** [comment]
I have three PTP600 variants, all with system release 600-10-08 firmware loaded, and all 3 have the exact same OID:
.1.3.6.1.2.1.1.1.0 = STRING: "Cambium PTP 58600 Full PTP Wireless Ethernet Bridge, Version 58600-10-08"
.1.3.6.1.2.1.1.1.0 = STRING: "Cambium PTP 58600 Lite PTP Wireless Ethernet Bridge, Version 58600-10-08"
.1.3.6.1.2.1.1.1.0 = STRING: "Cambium PTP 49600 Full PTP Wireless Ethernet Bridge, Version 49600-10-08"

.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.17713.6

Here's the single PTP800 variant that I have:
.1.3.6.1.2.1.1.1.0 = STRING: "Cambium PTP 800 Wireless Ethernet Bridge, Version   800-06-02"
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.17713.8

**Comment by Linux-Maverick** [comment]
@pheinrichs Would the MIBs be of any value to you? If so, how would I get them to you?

**Comment by pheinrichs** [comment]
@Linux-Maverick I've already got them :) no worries.
