### ISSUE TITLE
Syslog issue when changing IP addresses

### ISSUE THREAD

**Issue by kamils85** [librenms/librenms#7915]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 1.33-237-g79c4274
DB Schema | 224
PHP       | 7.0.15-0ubuntu0.16.10.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.10.1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Got a weird one here. I had two devices with IP A: 10.8.8.4 and B: 10.8.8.5 (well I still have them, but that's not the case).
I decided to swap the IP addresses. I used the renamehost.php script to make the changes. All went well and my A became 8.5 and B became 8.4. 

The only issue is, the syslog entries still for A go under B, and for B go under A (in LibreNMS).

Screenshot attached. 
![image](https://user-images.githubusercontent.com/23239006/34032532-e0ddcf8a-e176-11e7-84d1-29c8ef193bf3.png)

Any way to fix it?
K.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
