### ISSUE TITLE
Add Support For Tegile IntelliFlash

### ISSUE THREAD

**Issue by jdub01010101** [librenms/librenms#7921]
Good morning,

Per https://community.librenms.org/t/add-support-for-tegile-sans/2860, I am posting to have Tegile Intelliflash SAN support added to LibreNMS.  

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 1.33-245-gd6d4a3a
DB Schema | 224
PHP       | 7.1.12-2+ubuntu16.04.1+deb.sury.org+2
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

./discovery.php -h HOSTNAME -d | ./pbin.sh -- https://p.libren.ms/view/88bf844f
./poller.php -h HOSTNAME -r -f -d | ./pbin.sh -- https://p.libren.ms/view/86478af5
snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh -- https://p.libren.ms/view/7a42ae49
SNMP MIB -- https://p.libren.ms/view/a984fe91

- [x] Please provide as much detail as possible.

Tegile SANs are Active-Active normally, but our deployment is Active-Passive.  As such there are two controllers.  The pair share an IP but it does not respond to SNMP.  From what I can tell the controllers each need to be monitored separately.

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by theherodied** [comment]
Are the devices being recognized as Tegile already? Do you see anything under the device already?

I'll try to take a look at this and see if I can get it added.

**Comment by theherodied** [comment]
Please provide the entire snmpwalk.

**Comment by jdub01010101** [comment]
Sorry it took so long to get back to you.  The controllers are detected as Generic.  

I am having trouble getting a full snmp walk from the device, and have opened a case with Tegile Support as the SNMP functionality is not acting as expected.

**Comment by jdub01010101** [comment]
I am getting timeouts when walking. Had to increase the timeout time on the snmpwalk command to 10 seconds, though I suspect I could go lower.

The shared IP just times out despite Tegile documentation saying "Tegile recommends using the Array Management IP address when specifying the address of the Tegile array in your SNMP manager software "
Both below used snmpwalk -t10 -v1 -c commstring IPAddress .1 
My "A" Controller: https://p.libren.ms/view/080cef9d
My "B" Controller: https://p.libren.ms/view/08f9e503

**Comment by theherodied** [comment]
Thanks. I'll take a look and see if I can get this working!

**Comment by jdub01010101** [comment]
Thank you for your help.  If there is any movement from Tegile regarding the shared management IP, I will update this.  The output may be different.

**Comment by theherodied** [comment]
What storage do you need to monitor? If you could list the names of the pools/volumes/etc..I'll be more likely to get it right the first time.
Currently I'm seeing:
pool-a                     35% usage
ZebiSystem-A        53% usage
ZebiSystem-B        53% usage

**Comment by jdub01010101** [comment]
Pool-a is the storage that is in use.  I believe the ZebiSystem values are the controllers themselves and their storage for their OS.

**Comment by theherodied** [comment]
How big is pool-a?

**Comment by jdub01010101** [comment]
Pool-a is listed at 21.62TB in my dashboard.

**Comment by theherodied** [comment]
What's strange is when I do the math on the pool size I get 23.77TB. Wondering if it has to do with compression or dedup?

Will you ask support the correct way to calculate size?

**Comment by theherodied** [comment]
Nevermind I got it.

**Comment by murrant** [comment]
Sounds like the dashboard measurement is in TiB, not TB.

**Comment by jdub01010101** [comment]
Also if it helps any my current utilization after dedupe and compression is listed as about 7.5TB in case that correlates with any number you are seeing.

**Comment by theherodied** [comment]
You can test what I have so far with this PR. It's not done yet but I have pool usage and the icon.
https://github.com/librenms/librenms/pull/8464

**Comment by jdub01010101** [comment]
Getting a warning about whitespace errors.

Checking patch html/images/os/tegile.svg...
Checking patch includes/definitions/tegile.yaml...
<stdin>:60: new blank line at EOF.
+
Checking patch includes/discovery/storage/tegile.inc.php...
Checking patch includes/polling/storage/tegile.inc.php...
Applied patch html/images/os/tegile.svg cleanly.
Applied patch includes/definitions/tegile.yaml cleanly.
Applied patch includes/discovery/storage/tegile.inc.php cleanly.
Applied patch includes/polling/storage/tegile.inc.php cleanly.
warning: 1 line adds whitespace errors.

**Comment by theherodied** [comment]
I'll take a look and see what's going on.

**Comment by jdub01010101** [comment]
Cool.  Let me know how else I can help. Leaving work here in a few but I can VPN in tonight if necessary.

**Comment by theherodied** [comment]
How do the projects work in Tegile? How big are they and how much is used? Should these be monitored? I'm guessing the are like volumes in Nimble but not positive.
projectName.3.1 = fileserver
projectName.3.2 = servers
projectName.3.3 = Backups

I see shares as well but it only shows shareDataSize and no used or free.

The PR right now will give Pool usage, the icon, and classify the device as storage.

**Comment by jdub01010101** [comment]
I believe you are right.  The projects are like volumes.  The projects are where I am saving the VMDKs for our VMs.  Each project in my case uses the whole storage.  Basically they give you a way to customize things like dedupe or compression for whatever is in the project.  In my case I only have one pool since our requirements are simple, but someone else might have more than one.  Not sure about the device traffic.  I know that the Tegile tracks that, just not sure if that is a value in SNMP.

**Comment by jdub01010101** [comment]
I ran daily.sh then pulled in the patch with  ./scripts/github-apply 8464.  Good news is that the devices are being recognized as Tegile now and have the appropriate logo.

Bad news is that I am not seeing anything related to storage.  Could the SNMP request be timeing out for the storage components?

**Comment by theherodied** [comment]
It very well could be. You might want to hop on the discord server and
see what others have to say..On Mon, 2018-03-26 at 19:12 +0000, Jacob wrote:

**Comment by theherodied** [comment]
Try ./scripts/github-remove -d
then
./scripts/github-apply 8464

**Comment by theherodied** [comment]
I changed the files to the OS name which is probably causing the old ones to stick around. 

I talked to @laf and he helped fix the discovery issue I had with projects. Polling still needs work as I'm not a programmer and trying to figure it out still.

You can see the progress and contribute if you want at 

https://github.com/theherodied/librenms/blob/theherodied-tegile-2/includes/discovery/storage/intelliflash.inc.php

https://github.com/theherodied/librenms/blob/theherodied-tegile-2/includes/polling/storage/intelliflash.inc.php

**Comment by theherodied** [comment]
Any luck with trying the remove and apply?

Will you post what the web interface shows for project usage? I want to make sure I calculate it correctly.
At this point I'm having a hard time since the projects are of unlimited size.

**Comment by theherodied** [comment]
Also are you seeing interface usage?

**Comment by jdub01010101** [comment]
I removed the patch, ran daily, reapplied and made sure everything was chowned properly.  
I am not seeing anything about projects. No interface usage

![image](https://user-images.githubusercontent.com/6225711/37998895-26e66d7e-31e6-11e8-8834-6cda81c25ed6.png).

**Comment by theherodied** [comment]
@jdub01010101, I'm working on a second PR for the projects. It isn't working currently and isn't ready to test yet.

https://github.com/librenms/librenms/pull/8486

**Comment by theherodied** [comment]
@jdub01010101, pools and projects is working now. Needs more work still.
https://github.com/librenms/librenms/pull/8464

**Comment by jdub01010101** [comment]
I'll give it a try.  I wish I was more help, but I'm not really a programmer.

**Comment by theherodied** [comment]
Neither am I. Just jump in a give it a go. You can hop on the discord server and ask questions. That's how I started a few months ago.
