### ISSUE TITLE
CyberPower ATS with RMCARD205 showing as generic

### ISSUE THREAD

**Issue by tomck** [librenms/librenms#7929]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

```
Component | Version
--------- | -------
LibreNMS  | 1.33-249-g46fe934
DB Schema | 225
PHP       | 7.0.25
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
```

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
(I had to use an archive.org page but I think I got it, the FAQ section seems to be 404ing right now)
Discovery: https://p.libren.ms/view/99e1963a
Poller: https://p.libren.ms/view/ba0f2899
SNMPv3: https://p.libren.ms/view/a894f1b3
- [x] Please provide as much detail as possible.
```
ModelPDU15M10AT
Rating Voltage100-120 V
Rating Current12 A
Hardware Version1.00
Firmware Version1.04
ModelRMCARD205
Hardware Version1.1
Firmware Version1.0.5
Firmware Update Date11/17/2016
```
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

MIBs: https://www.cyberpowersystems.com/product/software/mib-v2-0/
Previous request: https://community.librenms.org/t/add-cyberpower-rmcard205-ups-monitoring-card/902

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Open pull request #7931, please test.

**Comment by tomck** [comment]
I used `github-apply` and ran `./daily.sh`, rediscovered the device, refreshed, waited, refreshed, and there's absolutely no change. I am, however, relatively sure I am doing something wrong, so here's the outputs of [discovery.php](https://p.libren.ms/view/60bd916a) and [poller.php](https://p.libren.ms/view/a42ef1f5).

**Comment by laf** [comment]
Can you provide the OIDs voltage and current are under, I couldn't see any useable data in your walk.

**Comment by tomck** [comment]
Though some research I have found out that voltage at least is output in 1/10 VAC, so I have [gotten a new snmpwalk for the ups](https://p.libren.ms/view/3e13b851) with the command `snmpwalk -v1 -m /opt/librenms/mibs/CPSMIB2017v2.2.MIB -c public 172.16.7.2 iso.3.6.1.4.1.3808`.  Information [from a redditor](https://www.reddit.com/r/homelab/comments/5pdxwb/cyberpower_ups_and_grafana_now_with_snmp/) gave me the numbers to include at the end, and I do see handy lines:
```
CPS-MIB::upsAdvanceInputLineVoltage.0 = Gauge32: 1190
CPS-MIB::upsAdvanceOutputVoltage.0 = Wrong Type (should be Gauge32 or Unsigned32): INTEGER: 1190
```
Matching these allowed me to find in the [-OUneb snmpwalk](https://p.libren.ms/view/22172e0a) the OIDs `.1.3.6.1.4.1.3808.1.1.1.3.2.1.0` for Input and `.1.3.6.1.4.1.3808.1.1.1.4.2.1.0` for Output voltage (which matches the redditor's findings but with a superfluous 0 at the end) and OID `1.3.6.1.4.1.3808.1.1.1.4.2.3.0` for the load percentage (matches what it says in the web panel) as well as `.1.3.6.1.4.1.3808.1.1.1.2.2.4.0` for minutes remaining.

Back to the Automatic Transfer Switch, the new [SNMPWalk -OUneb](https://p.libren.ms/view/8008d70d) and [SNMPWalk with names](https://p.libren.ms/view/6af0b901) has good lines, including information on the environmental sensor we have plugged into the back of the UPS. I really hope this can also be implemented. Most importantly for the ATC itself is `CPS-MIB::atsStatusSelectedSource.0 = INTEGER: sourceB(2)`which is OID `.1.3.6.1.4.1.3808.1.1.5.2.1.2.0` (1 for A, 2 for B).  Most of this can be done with a line for line comparison.

Thanks for all your help, and if there's any way I can help more, let me know. I look forward to testing this.
