### ISSUE TITLE
BGP sessions incorrectly being reported down

### ISSUE THREAD

**Issue by kdohBNY** [librenms/librenms#7937]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
**Yes. Up to date. Doing nightly git updates.** 
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
**====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-253-ge24b55b
DB Schema | 225
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================**
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
**Some of our BGP sessions are now falsely reporting down even though they are established. The output on some of our BGP peers is showing strange output in the "State" field as well on the Routing > BGP page.
Some just say "established" and are green as would be expected. The ones that are falsely reporting down show " established start x y z ... <BGP peer IP>" and are red. Screenshots attached for reference with hostnames removed.**
![librenms_bgp](https://user-images.githubusercontent.com/28956529/34263686-48db6ef0-e63e-11e7-8fa8-b1e9b7fc9a2e.JPG)

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by kdohBNY** [comment]
Forgot to mention that I'm using the default "BGP Down" alert 

BGP Session down | %bgpPeers.bgpPeerState != "established" && %macros.device_up = "1" | critical |   | Max: -1Delay: 0Interval: 300
-- | -- | -- | -- | --

**Comment by mehran-a** [comment]
Have the same problem.
Work around:

%macros.device_up = "1" && %bgpPeers.bgpPeerAdminStatus = "start" && %bgpPeers.bgpPeerState !~ established%

**Comment by kdohBNY** [comment]
Thanks @mehran-a for the tip!

**Comment by laf** [comment]
Update your installs, this was fixed 13 hours ago.

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
