### ISSUE TITLE
4500-X not being picked up properly version / hardware

### ISSUE THREAD

**Issue by laf** [librenms/librenms#794]
https://i.imgur.com/xK49vcU.png

http://pastebin.com/Wskazpc8

**Comment by SaaldjorMike** [comment]
New pastebin url: http://pastebin.com/Yvc14dLv

**Comment by laf** [comment]
Hi @SaaldjorMike. Hopefully this fixes the issue. If you can try this test branch that would be great.

cd /opt/librenms
git remote add laf https://github.com/laf/librenms.git
git remote update
git checkout issue-794
./poller.php -h HOSTNAME -m os

You should hopefully see things correctly in the webui.

If it's not, please do:

./poller.php -h HOSTNAME -m os -d

Edit any sensitive info and post on https://dpaste.de/ or something then link here.

You can switch back to the master branch at any stage (and should)

git checkout master

**Comment by SaaldjorMike** [comment]
This yields the following:
Pastebin: http://pastebin.com/fzG89QkV
Screenshot: https://i.imgur.com/ZTbJ9C5.png

The model name of the switch is WS-C4500X-16, which was what I was hoping for but it seems like that the switch reports an answer that does not really follow the usual way of fetching the hardware model.

**Comment by laf** [comment]
Ok, can you try the following please @SaaldjorMike 

This changes the regex for Cisco to catch the subtle changes from this device. I've tested it on some ASR's, 3750x and Cisco ASAs and it works ok.

cd /opt/librenms
git checkout master
git branch -D issue-794
git remote update
git checkout issue-794
./poller.php -h HOSTNAME -m system,os

You should hopefully see things correctly in the webui.

If it's not, please do:

./poller.php -h HOSTNAME -m system,os -d

Edit any sensitive info and post on https://dpaste.de/ or something then link here.

You can switch back to the master branch at any stage (and should)

git checkout master

**Comment by SaaldjorMike** [comment]
Thanks. This gives me:
https://i.imgur.com/qXz2xIh.png
https://dpaste.de/x4yR

**Comment by laf** [comment]
Should be done now @SaaldjorMike :)

cd /opt/librenms
git remote update
git checkout issue-794
./poller.php -h HOSTNAME -m system,os

**Comment by SaaldjorMike** [comment]
Looks good to me - a lot better than before :)
The poller now gives me (using branch issue-794):
Hardware: Switch System Version: 03.05.01.E RELEASE SOFTWARE (fc2) Features: UNIVERSALK9 Serial:

**Comment by laf** [comment]
Brill. No serial number support atm across all cisco devices. I'll look at that.

Going to run this on our production env for 24 hours and see if it's ok.

**Comment by laf** [comment]
PR now in place.
