### ISSUE TITLE
Nagios plugin - check_haproxy -H %hostname% 

### ISSUE THREAD

**Issue by K4S1** [librenms/librenms#7943]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `
====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-347-g36d6765
DB Schema | 226
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Hi
I was trying to add the service check_haproxy, but had trouble with Libre are forcing a -H %hostname% to the command (/usr/lib/nagios/plugins/check_haproxy) even if I keep the "IP address:" empty from WebUI
I have added "-u http://%IP%/\;csv" to the "Parameters:" field in WebUI

./check-services.php -d
...
Nagios Service - 7
Request:  /usr/lib/nagios/plugins/check_haproxy **-H %Selected Host%** -u http://%IP%/\;csv
**Unknown option: H**
sh: 1: csv: not found
...

/usr/lib/nagios/plugins/check_haproxy --help
https://pastebin.com/vK4V7eEJ
-H is not a varible of check_haproxy.

I checked if I could correct from SQL in services table. but that was not the case.

Anyone can help how to fix ?

Kasper :)

**Comment by K4S1** [comment]
Okay, I think I see now.

librenms/includes/services.inc.php
from line 124
`    // if we have a script for this check, use it.
    $check_script = $config['install_dir'].'/includes/services/check_'.strtolower($service['service_type']).'.inc.php';
    if (is_file($check_script)) {
        include $check_script;
    }
    // If we do not have a cmd from the check script, build one.
    if ($check_cmd == "") {
        $check_cmd = $config['nagios_plugins'] . "/check_" . $service['service_type'] . " -H " . ($service['service_ip'] ? $service['service_ip'] : $service['hostname']);
        $check_cmd .= " " . $service['service_param'];
    }`

and there are no: librenms/includes/services/check_HAproxy.inc.php 
I have no idear how to create the cmd :(
Could someone please point me in right direction how to do this ?
Not sure what documention to look for.

Thanks :)

**Comment by K4S1** [comment]
okay I added a file named librenms/includes/services/check_haproxy.inc.php
with code:
<?php
$check_cmd = $config['nagios_plugins'] . "/check_haproxy ".$service['service_param'];

and I got a bit further.
but now I have a lovely URL to HAproxy "http://%IP%:5000/;cvs"

seems like the ";" are making problems. are outputted like "\;"
when I do:
Request:  /usr/lib/nagios/plugins/check_haproxy -u http://%IP%:5000/\;csv
...
Nagios Service - 7
Request:  /usr/lib/nagios/plugins/check_haproxy -u http://%IP%:5000/\;csv
sh: 1: csv: not found
...

is there a way to remove the "\" ?
it's listed correct in the SQL table services "-u http://%IP%:5000/;csv"

Thanks :)

**Comment by K4S1** [comment]
Can't tell what happen't but now it's working :)
Case closed

I just added:
librenms/includes/services/check_haproxy.inc.php

```
<?php

$check_cmd = $config['nagios_plugins'] . "/check_haproxy " . $service['service_param'];
```

**Comment by kkrumm1** [comment]
@K4S1 just FYI This issue isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by murrant** [comment]
@K4S1 looks like you mostly have it figured out, If you create a pull request we can include this for others:
https://docs.librenms.org/Developing/Using-Git/

Come to discord if you need help https://t.libren.ms/discord

**Comment by K4S1** [comment]
@kkrumm1 figured that out after some digging ;) and closed quickly again. Should I have moved this somehow. ? I'm not 100% sure how to navigate on git.. sorry.

@murrant Hi... Yarh and maybe not :/, have some issues with the state detail view on the check_HAproxy service, have errors all over... When I figure that out, I'll try to figure out how to do a pull request. here on git.
