### ISSUE TITLE
Unifi UAP-ACv2 wireless data not collected

### ISSUE THREAD

**Issue by teamfighter** [librenms/librenms#7960]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Component | Version
--------- | -------
LibreNMS  | 1.33-279-ga391e62
DB Schema | 226
PHP       | 7.1.11
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

./discovery.php -h HOSTNAME -d | ./pbin.sh
https://p.libren.ms/view/0f59e54a
./poller.php -h HOSTNAME -r -f -d | ./pbin.sh
https://p.libren.ms/view/67859c87

So I dont see any wireless metrics for this devices, and there is no graphs (i.e. Error drawing graph) for wireless things. Looks like MIB issue.

**Comment by murrant** [comment]
Looks like you replaced the MIB, breaking it...

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by teamfighter** [comment]
I havent replaced any mibs. That's clean librenms install at clean centos 7 server. Could you please explain what did you mean and how can I fix this issue?

**Comment by teamfighter** [comment]
@murrant FYI
