### ISSUE TITLE
TL-SG2216 2.0 - Bond not recognized

### ISSUE THREAD

**Issue by plepeer** [librenms/librenms#7961]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

- [x ] Please include all of the information between the  

LibreNMS  | 1.33-279-ga391e62
DB Schema | 226
PHP       | 7.1.11-1+ubuntu16.04.1+deb.sury.org+1
MySQL     | 5.6.38
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/c516d6ee
https://p.libren.ms/view/545f7aaa
https://p.libren.ms/view/a3b3ff71

- [ x] Please provide as much detail as possible.
All individual interfaces are shown but not the bonds (LAG)

- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
You're device doesn't send this data within IF-MIB so we don't support it.

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
