### ISSUE TITLE
Change Default Disk Utilization Alert from 60% to 95%

### ISSUE THREAD

**Issue by admiralspark** [librenms/librenms#7975]
Hello,

I'm opening this to ask about moving the default disk utilization warning threshold from 60% to 95%. 60% alerts are insanely low and contribute to alerts being ignored, as well as being a ton of extra work to manually change alert thresholds on every server. 

My PR #7974 changes the default DB threshold to 95% from 60%.

Thoughts?

**Comment by E-t-z** [comment]
IMHO 95% is too high... 75% would be more reasonable.
What I do agree is that 60% is indeed insanely low.

**Comment by laf** [comment]
PR was closed so I'm closing this.
