### ISSUE TITLE
Feature Request : Siklu E Band Radios (70/80GHz)

### ISSUE THREAD

**Issue by Lonecrowe** [librenms/librenms#798]
These are higher end high capacity bridges used by some WISPS.  

The interfaces are pretty standard.  I believe the "HOST" Interface should be considered the primary interface to display.  (I'm in the process of verifying) 

Detection may or may not need to find out if it is a Master or Slave - but I did a DIFF between the outputs of the two and there were no real differences.  

Here is a pastebin of the master's enterprises walk http://pastebin.com/dNYuHCze

If you can add a **Wireless** tab under health and graph these items it would be sufficient.

RADIO-BRIDGE-MIB::rfAverageCinr.1 = INTEGER: 24 (this value can go into the negatives)
RADIO-BRIDGE-MIB::rfAverageRssi.1 = INTEGER: -46 
RADIO-BRIDGE-MIB::rbSysVoltage.0 = INTEGER: 51   (in volts)
RADIO-BRIDGE-MIB::rbSysTemperature.0 = INTEGER: 36  (Celsius)
RADIO-BRIDGE-MIB::rfModulationType.1 = INTEGER: rfModulationQAM-64(3)  (1 2 or 3)

FYI
RSSI = received signal strength indicator which is basically "level of received signal" strength in dBm
CINR = Carrier to Interference+Noise Ratio which is basically "signal to noise ratio" in dB

ACCEPTABLE VALUES:

RSSI from -40 to -85 dBm
-- you want RSSI to be closer to -40 than to -85
-- This radio you want it under -50 for it to be good for this particular radio. 
CINR from 10 to 30 dB
-- you want CINR to be closer to 30 than to 10
-- any value of 20 or more can be considered a "good signal"
-- I believe if the connection is really poor it can go into the negative numbers.  

I'll email the mib.

**Comment by laf** [comment]
Thanks for the details @Lonecrowe 

Would you be able to do an snmpwalk and get:

sysDescr.0 and sysObjectID.0

So we can get some way of identifying the kit.

**Comment by Lonecrowe** [comment]
SNMPv2-MIB::sysDescr.0 = STRING: EH-1200FX
SNMPv2-MIB::sysObjectID.0 = OID: RADIO-BRIDGE-MIB::radioBridgeRoot

**Comment by laf** [comment]
Can you email me the mib again, doesn't look like it's come through.

Also an snmpwalk against RADIO-BRIDGE-MIB::radioBridgeRoot, you might need to do -M /opt/librenms/mibs

**Comment by Lonecrowe** [comment]
mib re-sent.  

I can post that RADIO-BRIDGE walk if you like its quite long.  

Looks like I get some errors during the walk as the siklu mib references 2 other mibs
IEEE8021-CFM-MIB
IEEE8021-Q-BRIDGE-MIB

When I added those it asked for a crap load more.  

They can be found here 
http://www.ieee802.org/1/files/public/MIBs/

**Comment by laf** [comment]
Hi @Lonecrowe 

This doesn't seem to have anyway for us to detect it's an Siklu device.

Could you do an snmpwalk:

snmpwalk -v2c -c COMMUNITY HOSTNAME -M /opt/librenms/mibs -m SNMPv2-MIB .

(please ensure you include the full stop at the end).

**Comment by Lonecrowe** [comment]
Wouldn't this be it?  

SNMPv2-MIB::sysDescr.0 = STRING: **EH-1200FX**  <---model name

Running the walk now with the . and its stillll going.. :)  

Pastebin won't even allow me to paste it because of size limitation! Emailing you results.

**Comment by laf** [comment]
@Lonecrowe 

Ok branch issue-798 is available to test for this:

cd /opt/librenms
git remote laf update
git checkout issue-798

Add the device then allow a disco and poll to run. If it's already added then force a discovery:

./discovery.php -h DEVICE

Temp and voltage will appears in the sensors like normal.

The other three will be under wireless.

**Comment by laf** [comment]
Add rfOperationalFrequency.1

rfInGoodPkts + others around that.

**Comment by laf** [comment]
RADIO-BRIDGE-MIB::rfInPkts.1 = Counter64: 1461258486
RADIO-BRIDGE-MIB::rfInGoodPkts.1 = Counter64: 1461248808
RADIO-BRIDGE-MIB::rfInErroredPkts.1 = Counter64: 9746
RADIO-BRIDGE-MIB::rfInLostPkts.1 = Counter64: 45898
RADIO-BRIDGE-MIB::rfOutPkts.1 = Counter64: 1466332458
RADIO-BRIDGE-MIB::rfInOctets.1 = Counter64: 51064393983452
RADIO-BRIDGE-MIB::rfInIdleOctets.1 = Counter64: 50933750842764
RADIO-BRIDGE-MIB::rfInGoodOctets.1 = Counter64: 111182368692
RADIO-BRIDGE-MIB::rfInErroredOctets.1 = Counter64: 7084145
RADIO-BRIDGE-MIB::rfOutOctets.1 = Counter64: 51064406351184
RADIO-BRIDGE-MIB::rfOutIdleOctets.1 = Counter64: 50934571899803

**Comment by Lonecrowe** [comment]
Thanks.  I think that should be sufficient information for these units.

**Comment by laf** [comment]
Ok, test version available @Lonecrowe if you wouldn't mind:

cd /opt/librenms
git remote update laf
git checkout issue-798
git pull laf issue-798
./discovery.php -h HOSTNAME -d
./poller.php -h HOSTNAME -d

**Comment by Lonecrowe** [comment]
Just need to change operational freq to GHz and everything should be done!

**Comment by laf** [comment]
Ok, hopefully final update has been pushed if you want to try it. Most likely have to remove the two rrd files again though:

siklu-*.rrd

**Comment by laf** [comment]
PR merged now #890
