### ISSUE TITLE
Add OpenWRT device support

### ISSUE THREAD

**Issue by rbax82** [librenms/librenms#7988]
I would like to have OpenWRT distribution support added to this awesome piece of software please.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` 
Component | Version
--------- | -------
LibreNMS  | 1.34
DB Schema | 217
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

- Poller debug: https://p.libren.ms/view/17556739
- Discovery debug: https://p.libren.ms/view/bb9ab717

In case you’re wondering, in order to add support for distro to OpenWRTs SNMPD you must add the following to /etc/config/snmpd
config exec
  option name distro
  option prog /etc/snmp/distro
  option miboid .1.3.6.1.4.1.2021.7890.1

**Comment by laf** [comment]
I'm confused by this. You seem to have given the answer to the issue which lies outside of librenms

**Comment by rbax82** [comment]
I am simply looking for this distro to be added is all.

**Comment by laf** [comment]
It already is by using the distro script we provide. The docs cover the install of this but your issue alludes to you already using this. 

If the distro script isn’t working then please open an issue on the librenms-agent repo

**Comment by rbax82** [comment]
I was really just hoping to get the logo added. ;)

**Comment by laf** [comment]
You should have just said that initially :)
