### ISSUE TITLE
Ubiquiti NB 5AC 16 missing information

### ISSUE THREAD

**Issue by bigmong** [librenms/librenms#7996]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the ====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-295-g0652d7c
DB Schema | 227
PHP       | 7.0.18-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/6249c1de
https://p.libren.ms/view/baee4ff5
https://p.libren.ms/view/d9544e6a

- [x] Please provide as much detail as possible.
Missing the "Hardware" name "NanoBeam 5AC 16" and missing the version from Operating System Version "8.4.3.36160.171117.1234"
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by Zmegolaz** [comment]
Could you test if #8005 solves this?

**Comment by neg2led** [comment]
RE #8005 - NanoBeam is an AirOS product, not a UniFi product, so it won't be affected by that change. There's possibly a similar change required here though?

**Comment by Zmegolaz** [comment]
@neg2led should be fixed in master now, could you update and verify?

**Comment by murrant** [comment]
Just comment here if this not fixed, thanks.
