### ISSUE TITLE
Ubiquiti AP OS Version

### ISSUE THREAD

**Issue by bigmong** [librenms/librenms#7997]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the ====================================
Component | Version
--------- | -------
LibreNMS | 1.33-295-g0652d7c
DB Schema | 227
PHP | 7.0.18-0ubuntu0.16.04.1
MySQL | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool | 1.5.5
SNMP | NET-SNMP 5.7.3
====================================
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/5384b39d
https://p.libren.ms/view/b8da96bf
https://p.libren.ms/view/ff30c489

- [x] Please provide as much detail as possible.
UAP-AC-LR, UAP-OUTDOOR+, and UAP-AC-MESH use
.1.3.6.1.4.1.41112.1.6.3.6.0 = STRING: "3.9.15.8011" as the version of the OS on the APs
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by Rosiak** [comment]
Don't we already do that as we poll the unifiApSystemVersion?

**Comment by murrant** [comment]
@Rosiak #8005 was recently merged, which fixes this.  Just forgot to close the ticket :)
