### ISSUE TITLE
BROCADE SLX 9140

### ISSUE THREAD

**Issue by Bostjan1977** [librenms/librenms#8007]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.33-297-g34ed39c
DB Schema | 227
PHP       | 5.6.30-0+deb8u1
MySQL     | 10.0.32-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
Discovery : https://p.libren.ms/view/d10caec8
Poller : https://p.libren.ms/view/2605245f
SNMP : https://p.libren.ms/view/b1b74637

- [x] Please provide as much detail as possible.

The device is Brocade SLX 9140 L3 switch/router. Since it is a new model with new OS (SLXOS), the existing implementation in LibreNMS doesn't cover all the data.

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by Rosiak** [comment]
Basic support is there. If you are looking for specific metrics please provide some info on where we can find these MIB wise, and create a feature request on https://community.librenms.org

Thanks!
