### ISSUE TITLE
HP Comware network device listed as Generic Device

### ISSUE THREAD

**Issue by cwgueco** [librenms/librenms#801]
Hello,

I have managed to add an HP Comware network device into the system polled with SNMPv2. However, unlike Cisco network devices, this device is listed as "Generic Device". I have uploaded via pastebin the results of snmpbulkwalk for this device. Kinldy check "http://pastebin.com/TaZp3YuA" for the results.

Thanks!

**Comment by laf** [comment]
@cwgueco thanks to @paulgear. this has now been fixed hopefully. Do a git pull in the LibreNMS directory to update.

**Comment by cwgueco** [comment]
Thanks! Did a git pull and deleted/re-added HP Comware network. It is now listed as "HP Comware" in the OS column.

**Comment by paulgear** [comment]
Excellent - thanks for confirming @cwgueco.
