### ISSUE TITLE
RRD Poll graphs

### ISSUE THREAD

**Issue by sanderv32** [librenms/librenms#8011]
As a new feature it would be nice to have RRD graphs of the `Pollers->Pollers`. So not per device but a total poll time graph of one poll cycle.

**Comment by kkrumm1** [comment]
@sanderv32 FYI Feature request are done here. https://community.librenms.org/c/feature-requests

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
