### ISSUE TITLE
LibreNMS community broken ? 

### ISSUE THREAD

**Issue by VictorJ76** [librenms/librenms#8019]
Is LibreNMS community broken ? 
https://community.librenms.org/ 

![image](https://user-images.githubusercontent.com/18124387/34558759-a1ebd104-f13f-11e7-987a-07195a0416f9.png)

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by laf** [comment]
Not for me but please don't create issues for things like this.

**Comment by VictorJ76** [comment]
ok
