### ISSUE TITLE
Adding support for Ruijie devices

### ISSUE THREAD

**Issue by hanserasmus** [librenms/librenms#8021]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-298-gda54444
DB Schema | 227
PHP       | 7.1.11
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
Discovery : https://p.libren.ms/view/c0bec099
Poller: https://p.libren.ms/view/7916d42d
SNMP : https://p.libren.ms/view/18d2f054

- [x] Please provide as much detail as possible.

We have a few Ruijie network devices on our network specifically 6220's and 5750's, which is currently being shown as "servers" rather than network devices.  We would appreciate it a lot if it was possible to have these being correctly displayed as network devices, and added to that list. This will in future help also if we have multiple pollers.  We are aware this is a community driven project, therefor we are not demanding anything, simply asking nicely.

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
The snmpwalk seems to be missing data.  Did you run it with the period at the end?

**Comment by hanserasmus** [comment]
I ran it from the "console" window in the web ui? From the "gear" and then ran it there, gave it a lot of time to finish, and I thought it was finished, then copy and pasted it. Will run it there again?

**Comment by hanserasmus** [comment]
Running it from command line I get the following errors, and have no idea how to fix them:

snmpbulkwalk -OUneb -v2c -c COMMUNITY HOST . > /root/ruijie.txt

Error: OID not increasing: .1.0.8802.1.1.2.1.4.1.1.4.2359061835.15.1
 >= .1.0.8802.1.1.2.1.4.1.1.4.2358846109.17.1

Error: OID not increasing: .1.0.8802.1.1.2.1.4.1.1.4.2359061835.15.1
 >= .1.0.8802.1.1.2.1.4.1.1.4.2103766526.18.1

Error: OID not increasing: .1.0.8802.1.1.2.1.4.1.1.4.2359061835.15.1
 >= .1.0.8802.1.1.2.1.4.1.1.4.1762405819.21.1

Error: OID not increasing: .1.0.8802.1.1.2.1.4.1.1.4.2359061835.15.1
 >= .1.0.8802.1.1.2.1.4.1.1.4.2350196798.22.1

Error: OID not increasing: .1.0.8802.1.1.2.1.4.1.1.4.2359061835.15.1
 >= .1.0.8802.1.1.2.1.4.1.1.4.1957949978.30.1

**Comment by hanserasmus** [comment]
I have run the snmp command as suggested in discord, but the file content is too large for pastes to work, so I am adding the txt file with the data. Sorry if this is not what you wanted, but I could not see another way at this time.
[ruijie.txt](https://github.com/librenms/librenms/files/1603890/ruijie.txt)

**Comment by spencerbutler** [comment]
@hanserasmus Let me know if this resolves any of your issues. If you submit a follow up set of discovery, poller, and snmpwalk data I can add better support.

**Comment by hanserasmus** [comment]
Hi @spencerbutler. Sorry for only replying now.  Thank you for all your and @PipoCanaja 's hard work up to now!

I have added a zip file full of snmpwalk and snmpbuilkwalk results, as well as all the mibs referenced whilst running the commands.

My LNMS install is on the latest version (daily updates) but adding these devices to LNMS still results in only Ruijie OS showing. And only the traffic throughput. It does not show model numbers, or CPU, memory or anything else. 
It also seems that the 6220 snmpbulkwalk is still incomplete. File shows it is about 55k lines, where the 5750 is about double that.

Does this data help at ALL?

**Comment by PipoCanaja** [comment]
Hi @hanserasmus 
Seems that the mibs are completely broken. Here is what I can find : 

MY-SYSTEM-MIB::mySystemHwVersion.0 = STRING: 1.11
MY-SYSTEM-MIB::mySystemSwVersion.0 = STRING: 173619
MY-SYSTEM-MIB::mySystemBootVersion.0 = STRING: 10.4.173619
MY-SYSTEM-MIB::mySystemMIBObjects.24.0 = STRING: "G1H80G0000436"

The last one could be a serial number (but is it the chassis, something else). 

Let me know if these would be usefull. 

No clue about CPU or memory, you need to ask the vendor to do a proper and working mibfile I suppose.
