### ISSUE TITLE
Librenms webpage starts with Failure, parse error

### ISSUE THREAD

**Issue by PetersPlace** [librenms/librenms#8025]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations
Hello, sorry for posting maybe in the wrong area.
For 2 weeks i'am running Librenms with succes on my synology nas with docker
It runs together with mariadb als as container in docker

Now my nas has done update and did a restart. From this time the webpage Iibrenms runs with an error

Parse error: syntax error, unexpected ''] = 1; # Enable Locations on ' (T_CONSTANT_ENCAPSED_STRING) in /opt/librenms/conf.internal.d/config.custom.php on line 4

Restarting the containers does not help, is there any other command to restart it, or any other point to fix it.
Regards
Peter

**Comment by murrant** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

Also, I suggest you read the error you posted.
