### ISSUE TITLE
Not able to change device type

### ISSUE THREAD

**Issue by SotYPL** [librenms/librenms#8027]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.33-299-g6a122f2
DB Schema | 227
PHP       | 7.0.25
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.

I believe one of the recent updates broken my ability to change device type. I had some custom device types added trough config.php ($config[‘device_types’]) and one day devices started to randomly change to “Server”. So I removed my custom added types and tried to add them with higher id but it didn’t help. Now I have them removed completely but I’m not able to change device type to any other built in type. As soon as I change it to Workstation by example it goes back to Server and recent events shows “Device type changed workstation => server”. And even if I change database entry manually to something else than Server it goes back to server as soon as I open this device in browser. Any idea what could cause this?

Logs show this:

MySQL Error: Cannot add or update a child row: a foreign key constraint fails (librenms.device_relationships, CONSTRAINT device_relationship_parent _device_id_fk FOREIGN 
KEY(parent_device_id) REFERENCES devices (device_id) ON DELETE CASCADE) (INSERT INTO device_relationships (parent_device_id,child_device_ id) VALUES (‘0’,‘284’))

It appears every time I try to change device type.

I also just setup new vm with CentOS 7 and installed LibreNMS from scratch following guide and have the same issue for all devices that I added and tried change type from default to something else.

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
You haven't provided any examples at all on how to even replicate this.

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by SotYPL** [comment]
I though that my description was clear enough, sorry if it was not.

The easiest way to replicate this is open settings for any device and try to change its type from detected one to anything else for example from Server to Workstation or Storage to Server. After clicking Save it will show "Device record updated." but when I go Overview recent events show "Device type changed workstation => server" or "Device type changed server => storage" and after going back to settings its type will be back to detected one.

librenms.log have this entry:

MySQL Error: Cannot add or update a child row: a foreign key constraint fails (`librenms`.`device_relationships`, CONSTRAINT `device_relationship_parent
_device_id_fk` FOREIGN KEY (`parent_device_id`) REFERENCES `devices` (`device_id`) ON DELETE CASCADE) (INSERT INTO `device_relationships` (`parent_device_id`,`child_device_
id`)  VALUES ('0','15'))
