### ISSUE TITLE
WatchGuard device listed as Generic Device

### ISSUE THREAD

**Issue by azcobain** [librenms/librenms#803]
Hi,

When adding a WatchGuard device (XTM26-W), it's currently detected as a Generic Device. Here is the snmpbulkwalk output: http://pastebin.com/GNkVRWSf

Thanks.

**Comment by laf** [comment]
Hi @azcobain. Ok I've got a test branch which should fix this for you.

If you wouldn't mind giving it a try that would be great:

cd /opt/librenms
git remote add laf https://github.com/laf/librenms.git
git remote update
git checkout issue-803
./discovery.php -h <DEVICE> -m os

You should hopefully see it say the os has been changed. Check the webui and see.

If it's not, please do:

./discovery.php -h <DEVICE> -m os -d

Edit any sensitive info and post on https://dpaste.de/ or something then link here.

You can switch back to the master branch at any stage (and should)

git checkout master

**Comment by azcobain** [comment]
Unfortunately still seems the same in the web UI. Here is the debug output https://dpaste.de/T8C8

**Comment by laf** [comment]
That dpaste isn't working.

Could you actually do the following please:

./discovery.php -h HOSTNAME -m system,os -d
./poller.php -h HOSTNAME -r -m system,os -d

And also an snmpwalk of:

sysDescr.0 and sysObjectID.0

**Comment by azcobain** [comment]
Here you go...

https://dpaste.de/BQDu
https://dpaste.de/wcM0

Sorry, I'm not sure what you mean by snmpwalk of sysDescr.0 and sysObjectID.0

**Comment by laf** [comment]
hi @azcobain those pastes have all expired. Can you put them back again?

For sysDescr, something like this:

/usr/bin/snmpget -v1 -c public -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:localhost:161 sysDescr.0 sysObjectID.0

**Comment by azcobain** [comment]
Hi @laf, try these.

https://dpaste.de/smaL
https://dpaste.de/wVUC
https://dpaste.de/UhSS

**Comment by laf** [comment]
Hi @azcobain When you get a second if you can try my issue-803 branch again that would be great.

Please ensure you do:

git pull laf issue-803

To get the updated files (it's also now rebased against current master)

**Comment by azcobain** [comment]
Thanks, now detecting the devices :)

**Comment by laf** [comment]
Cool. I'll PR it up :)
