### ISSUE TITLE
New Device Support - IXIA packet brokers

### ISSUE THREAD

**Issue by papatango71** [librenms/librenms#8032]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

librenms@ams1-admin-inf01
[/opt/librenms]$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-304-ge16422a
DB Schema | 227
PHP       | 7.0.20
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Database connection successful
[OK]    Database schema correct

DISCOVERY :: https://p.libren.ms/view/391aa39b

POLLER :: Not working.  Output is to big ( Got a packet bigger than 'max_allowed_packet' bytes ).  How do I work around this..??

SNMPBULKWALK :: Not working.  Output is to big ( Got a packet bigger than 'max_allowed_packet' bytes ).  How do I work around this..??

ANUE-MIB.txt :: https://p.libren.ms/view/e0b1edfb

**Comment by laf** [comment]
You will need to use another pastebin service or upload a text file to this issue. Once you have the data we will re-open.

**Comment by papatango71** [comment]
@Laf, text file attached for the ./discovery.php command.  Please let me know if there is anything else needed in order to add support for this device.

[IXIA.txt](https://github.com/librenms/librenms/files/1616076/IXIA.txt)

**Comment by laf** [comment]
We need all of the files really but at a minimum the snmpwalk - without that, we can't do anything.

**Comment by papatango71** [comment]
@laf, I supplied the requested information.  Would it be possible to re-open this request and get support for IXIA packet brokers added into LibreNMS..??

**Comment by PipoCanaja** [comment]
@papatango71 Support is about to be merged. It is fairly basic but it can be later expanded if necessary.

**Comment by papatango71** [comment]
Sounds good...  Thank you for letting me know.

-Patrick

**Comment by PipoCanaja** [comment]
Hi @papatango71 It is now merged. You can run ./daily.php and discovery again your device. If you update only on stable version, you'll have to wait for next stable release. 
Bye
