### ISSUE TITLE
Ports page fails to load list of ports

### ISSUE THREAD

**Issue by fsmed** [librenms/librenms#8035]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

$ ./daily.sh
Checking PHP version                               OK
Updating to latest codebase                        OK
Updated from e16422a21dbda32673dd49699de27af5c1546e78 to d7b4a30acf3509634a087ec90d8f7feab64fdf39 OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK

Component | Version
--------- | -------
LibreNMS  | 1.33-309-gd7b4a30
DB Schema | 227
PHP       | 7.1.11
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.2

The ports page fails to display any ports, same on all subcategories like disabled or deleted ports. Same problem in both Chrome and Safari.
There's one error in Chrome developer console. Gist contain the specific line with newlines at "select" and stripped of information about snmp locations etc.
https://gist.github.com/fsmed/523188219064e670291f21265a17d4f9
https://i.imgur.com/ky8ypLC.png

**Comment by fsmed** [comment]
Fixed the issue.
We had some interface descriptions starting and ending with ", corrected those and the page loads as it should. Before I corrected them I looked in the db and the quotes were not there but the description ended with a \.

**Comment by Zmegolaz** [comment]
I can't replicate this. Could you please temporarily add the "" back to a description, make sure it's updated (web interface doesn't work), do `snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh` and send the database row of the offending port? It shouldn't impact any polling, just the viewing of the page.

**Comment by fsmed** [comment]
Was able to reproduce it, just putting quotes around some letters wasn't enough, found the description we had previously in backups. With the desc below the ports page is empty again.

(config-if)# desc "netmgmt: bla xe-1/2/3"

# show int eth1/1 desc
-------------------------------------------------------------------------------
Port          Type   Speed   Description
-------------------------------------------------------------------------------
Eth1/1        eth    10G     "netmgmt: bla xe-1/2/3"

MariaDB [librenms]> select ifAlias from ports where ifAlias like '%bla%';
+--------------------------+
| ifAlias                  |
+--------------------------+
| \"netmgmt: bla xe-1/2/3\ |
+--------------------------+

The pbin.sh failed to upload.
h1>A Database Error Occurred</h1>
		<p>Error Number: 2006</p><p>MySQL server has gone away</p><p>SELECT RELEASE_LOCK('lkqvptd8j90m8p51fsnul7l2bb') AS ci_session_lock</p><p>Filename: libraries/Session/drivers/Session_database_driver.php</p><p>Line Number: 399</p>

If it's still required I can upload the snmpwalk output somewhere.
