### ISSUE TITLE
HP Switch port deleted

### ISSUE THREAD

**Issue by anderssonpof** [librenms/librenms#804]
Hi,

Encountered an issue with ports being deleted for some reason.
HP switches version K.15.16.0006 

Here's debugs for poller and discovery for one that gets ports deleted
https://github.com/anderssonpof/Stuff/blob/master/Logs/poller.log
https://github.com/anderssonpof/Stuff/blob/master/Logs/discovery.log

If some information is missing let me know and I'll see what I can do.

**Comment by laf** [comment]
Hi @anderssonpof.

Thanks for the debug info. Would you be able to redo these with:

-m ports

at the end of the commands to limit the output to just the ports poller please?

Thanks,

**Comment by anderssonpof** [comment]
Hi @laf 

Alright, did this for the poller and the ports got added back, but as soon as the cronjob kicked in they got deleted again.
Also added my config.php for reference

https://github.com/anderssonpof/Stuff/blob/master/Logs/poller-m.log
https://github.com/anderssonpof/Stuff/blob/master/Logs/discovery-m.log
https://github.com/anderssonpof/Stuff/blob/master/Logs/config.php

**Comment by laf** [comment]
Really odd @anderssonpof. According to that output the ports aren't marked as deleted but I'm guessing you don't see anything in the web ui?

**Comment by laf** [comment]
I've reviewed the code and can't see where ports would be deleted other than in the same section as them showing to  be undeleted.

Can you run a discovery.php -h <DEVICE> -m ports then check the webui straight after. Then run poller.php -h <DEVICE> -m ports and see if you see them show at any stage. It could be worth removing them from the db and doing a rediscover. This shouldn't be necessary but it's an option.

**Comment by anderssonpof** [comment]
Indeed I find this very odd as well.
I deleted the device and added it again and the problem persists.

I temporarily disabled the cronjobs.
discovery with -m -> ports get back
as soon as i run the poller without -m they get deleted in the webgui
![ports](https://cloud.githubusercontent.com/assets/7721452/7153532/32e2a01a-e34d-11e4-82d3-13f60056d48b.png)
![overview](https://cloud.githubusercontent.com/assets/7721452/7153536/394f90b6-e34d-11e4-88c4-30f5214563ed.png)
![deletedports](https://cloud.githubusercontent.com/assets/7721452/7153537/39702eca-e34d-11e4-838d-88cf8cfae530.jpg)

**Comment by laf** [comment]
Anyway you can get me remote snmp to this device? I can give you an IP that I will be coming from.

Feel free to email neil@librenms.org.

**Comment by anderssonpof** [comment]
I'll look into it, cannot guarantee anything yet. I'll get back to you thursday/friday

**Comment by laf** [comment]
@anderssonpof I think it's one of the poller modules that's running. It maybe crashing your snmp stack. With all but ports modules turned off it works fine. I'm working through to find out the which module it is.

**Comment by laf** [comment]
@anderssonpof Disable ipSystemStats and try again. I'd take a look at your devices logs and possibly report this as a bug to HP as I expect snmp is crashing when we're querying for the oids in that module.

**Comment by anderssonpof** [comment]
@laf Thank you very much for finding that.
I'll what I do with HP, they're usually slow.

**Comment by laf** [comment]
No probs. I'll close this issue. Feel free to re-open on comment if you find any more info for other users.

**Comment by anden4380** [comment]
i also have the same problem i fixed it with adding this two lines to the config.php file i librenms

$config['snmp']['timeout']                         = 20;
$config['snmp']['max-rep']                         = 3;

and after that i have all the interfaces and data

sorry for my bad english

**Comment by laf** [comment]
Thanks for reporting back @anden4380.

That sounds more like your issue was just snmp timing out. I believe the original issue here was that the switch itself's snmp stack was crashing for some reason.

Good to know though and helpful to others I'm sure.

**Comment by anden4380** [comment]
Okay :-)

2015-04-22 22:50 GMT+02:00 Neil Lathwood <notifications@github.com>:

> Thanks for reporting back @anden4380 <https://github.com/anden4380>.
>
> That sounds more like your issue was just snmp timing out. I believe the
> original issue here was that the switch itself's snmp stack was crashing
> for some reason.
>
> Good to know though and helpful to others I'm sure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/librenms/librenms/issues/804#issuecomment-95330766>.
>



-- 
Hilsen Anders Jørgensen
