### ISSUE TITLE
Cisco Catalyst 2960G detected as 3com/A10

### ISSUE THREAD

**Issue by olds463** [librenms/librenms#8049]
LibreNMS  | 1.33-321-geac128a
DB Schema | 228
PHP       | 7.1.6
MySQL     | 10.1.25-MariaDB
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.2

[OK]    Database connection successful
[OK]    Database schema correct

----------------------------

Recently updated via git pull && schema update .. However when I run discovery on an older Cisco Catalyst 2960G it is now detected wrong. Running discovery again it keeps flapping between 3com and A10 networks? 

Detected as 3com output : https://pastebin.com/0PKcbijw
Running again detected as A10: https://pastebin.com/szbpbget

**Comment by laf** [comment]
Remove cache/os_defs.cache and rediscover the devices

**Comment by murrant** [comment]
It is highly suggested to use ./daily.php to update ;)
