### ISSUE TITLE
topology map like phpweather map with traffic in and out 

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#805]
Is it possible to supply such a feature  on current map :
1 . display traffic in and out 
2 . windows device can be displayed in the map 

Thank you !

**Comment by laf** [comment]
hi @wzhsunn. This may be possible on both points. We will have to take a look and see what we can do.

**Comment by wzhsunn** [comment]
Thank you very much . I will look forward for that.

**Comment by laf** [comment]
1. is taken care of hopefully with pr #826

**Comment by wzhsunn** [comment]
very good ! nice work ! I will use gns3 to take a test .

**Comment by wzhsunn** [comment]
The Librenms has a good performance at topology map,thanks for your hard work. And will it be better if  the appearance of the topology map displays like this http://visjs.org/examples/network/03_images.html.  ：）

**Comment by laf** [comment]
PR #1179 will potentially add end devices now. They need to be associated via mac address so a lookup is done through all mac address entries and check if any of those mac addresses are a physical interface, if they are then we now have the two port ids and can relate them.

**Comment by laf** [comment]
This should now be done.

I don't think using images is a good idea, I've read of performance issues with visjs when using custom images on network diagrams.
