### ISSUE TITLE
Bgp-peers discovery module afi-safi values not decoded or empty

### ISSUE THREAD

**Issue by zombah** [librenms/librenms#8051]
This is partialy extends same issue already fixed in PR #8018 

Junos os safi values not decoded, but reported by bgp mib in bgp-peers module discovery:  
`ipv4.5, family inet-mvpn, decode as ipv4.mvpn`  fixed in #8083 

Junos os bgp peers without afi-safi data, shown by bgp mib as bgp peers but without any afi-safi data at all:  
```
family l2vpn,  
family evpn,
family inet flow
```
probably some other junos mib required to decode them and collect stats, need to investigate.

Cisco IOS-XE afi-safi values collected by bgp-peers module but not decoded:
```
ipv4.132, address-family rtfilter unicast, 
ipv4.133, address-family ipv4 flowspec,
25.65, address-family l2vpn vpls, 
25.70, address-family l2vpn evpn, 
```
I will add more data if found and will attach test data later.

[IANA afi list](https://www.iana.org/assignments/address-family-numbers/address-family-numbers.xhtml)  
[IANA safi list](https://www.iana.org/assignments/safi-namespace/safi-namespace.xhtml)
[Juniper JunOS info with all possible afi and safi combos](https://www.juniper.net/documentation/en_US/junos/topics/usage-guidelines/routing-enabling-multiprotocol-bgp.html)

**Comment by laf** [comment]
Fixed in #8083.
