### ISSUE TITLE
Incorrect uptime for PoE Midspan devices

### ISSUE THREAD

**Issue by lfkeitel** [librenms/librenms#8064]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

LibreNMS  | 1.33-326-ge372023
DB Schema | 228
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.1.30-MariaDB-1~xenial
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

A bug showed up this morning where all our PoE Midspan devices were showing uptimes of 24 seconds which is not correct at all. After some investigation, I found the cause to be here: https://github.com/librenms/librenms/blob/master/includes/polling/core.inc.php#L33. The array key is incorrect so it's using the snmpEngineTime which is at 24 on these devices instead of the sysUpTime which is over 42 days. The fix is simply changing `sysUpTime` to `sysUptime`.

**Comment by laf** [comment]
Why not submit a fix rather than create an issue? It would have been quicker to do that :)

**Comment by lfkeitel** [comment]
I'll send a PR. This was more for documentation and reminder for me.
