### ISSUE TITLE
Mismatched PHP Versions

### ISSUE THREAD

**Issue by asteen-nexcess** [librenms/librenms#8067]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

I'm running into an issue where the GUI "About" page is showing a different PHP version than the validate.php script when running from the CLI. 

About Page:

Version | 1.33-335-g7e03905e6 - Tue Jan 09 2018 15:47:33 GMT-0500
-- | --
DB Schema | #228
Web Server | Apache
PHP | 5.4.45
MySQL | 5.6.35-81.0
RRDtool | 1.4.7

CLI validate.php

====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-338-gd515f5043
DB Schema | 228
PHP       | 7.1.10
MySQL     | 5.6.35-81.0
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.5
====================================

It's not a huge issue since it looks like our install is still updating correctly, but is annoying having the PHP version too low errors in the GUI. Any ideas of why this is?

Thanks!

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
