### ISSUE TITLE
Validate Showing Incorrect Status

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#8069]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
```
Component | Version
--------- | -------
LibreNMS  | 1.33-339-ge11e84f2e
DB Schema | 228
PHP       | 7.1.11-0ubuntu0.17.10.1
MySQL     | 5.7.20-0ubuntu0.17.10.1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
```

- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
I may be wrong, but don't believe this is applicable ... this isn't about a device or particular output, rather the poller detection (as below) ... right?
- [X] Please provide as much detail as possible.
From validate.php,
```
[OK]    Database connection successful
[OK]    Database schema correct
[FAIL]  The poller (linuxServer) has not completed within the last 5 minutes, check the cron job.
[FAIL]  fping6 location is incorrect or bin not installed.
        [FIX] Install fping6 or manually set the path to fping6 by placing the following in config.php: $config['fping6'] = '/path/to/fping6';
```
But also, from the syslog (yes, this is within the last 5 min),
```
Jan 10 18:30:01 linuxServer CRON[16404]: (librenms) CMD (   /opt/librenms/cronic /opt/librenms/poller-wrapper.py 16)
Jan 10 18:35:01 linuxServer CRON[21465]: (librenms) CMD (   /opt/librenms/cronic /opt/librenms/poller-wrapper.py 16)
Jan 10 18:40:01 linuxServer CRON[23969]: (librenms) CMD (   /opt/librenms/cronic /opt/librenms/poller-wrapper.py 16)
Jan 10 18:45:01 linuxServer CRON[26428]: (librenms) CMD (   /opt/librenms/cronic /opt/librenms/poller-wrapper.py 16)
Jan 10 18:50:01 linuxServer CRON[28889]: (librenms) CMD (   /opt/librenms/cronic /opt/librenms/poller-wrapper.py 16)
Jan 10 18:55:01 linuxServer CRON[31620]: (librenms) CMD (   /opt/librenms/cronic /opt/librenms/poller-wrapper.py 16)
```

So why is validate.php saying the poller is not running? It seems to be, from syslog ... right?
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by arrmo** [comment]
NP, will do. I admit, not sure why it's not a bug, but I may be misunderstanding. Thanks.

**Comment by murrant** [comment]
@arrmo it is correct.  You likely have multiple poller entries and one is stale.  So it has not polled.  If you visit the validation on the webui it will link you to the poller page where you can delete the stale entry.

**Comment by arrmo** [comment]
That makes sense - thanks for clarifying!
