### ISSUE TITLE
Translate Output graph

### ISSUE THREAD

**Issue by Kaginics** [librenms/librenms#8073]
Hi,
I need to translate the output graph getted buy a curl option.
It's the SVG version, i don't find the way to do that.

**Comment by laf** [comment]
You chose to delete all the text when creating an issue rather than reading it. Please don't do that.

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
