### ISSUE TITLE
Enterasys switches changed to Cambium wireless devices after LibreNMS update

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#8074]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hi,

I noticed that with latest upgrade that all our Enterasys switches; regardless of their plartform, were turned into Cambuim devices and changed from being network to be wireless devices. This happened upon the automatic execution of the discovery cron job. The result was that some of the entities like the CPU and Storage on these devices is no longer being polled. See screenshot below and I have also included the debug files for your reference. By the way, this issue also affected all our HP network printers which were also converted into Cambuim wireless devices. I will appreciate your help.

![image](https://user-images.githubusercontent.com/16717388/34815993-278e4644-f6bc-11e7-8271-db35a6712ba8.png)

![image](https://user-images.githubusercontent.com/16717388/34816089-8122fd44-f6bc-11e7-9d55-1b001fc39df8.png)

![image](https://user-images.githubusercontent.com/16717388/34816104-8c2541de-f6bc-11e7-8d6e-7ca660c71b9d.png)

[enterasys_switch_discovery.txt](https://github.com/librenms/librenms/files/1621827/enterasys_switch_discovery.txt)
[enterasys_switch_poller.txt](https://github.com/librenms/librenms/files/1621828/enterasys_switch_poller.txt)
[enterasys_switch_snmpbulkwalk.txt](https://github.com/librenms/librenms/files/1621829/enterasys_switch_snmpbulkwalk.txt)

**Comment by laf** [comment]
We have pretty extensive os detection tests in place so I'm not sure this is actually an issue on our side.

I took a look anyway and it does seem that you have a custom definition file for cambium:

`172.16.2.10 11 cambium SQL`

From the output shows the actual OS is cambium, we have no such OS:

```
-bash-4.2$ grep 'os: cambium' ./includes/definitions/*.yaml
-bash-4.2$
```

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
