### ISSUE TITLE
Port Errors Page: Port Errors vs Errors Delta

### ISSUE THREAD

**Issue by penfold1972** [librenms/librenms#8079]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

I see that the page listing the devices/ports with errors show the current number of errors reported on the interface. The problem is that there is no indication if the number of errors has increased by a single error or by hundreds/thousands of errors with this display. But it appears that the error rate from the last poll is tracked by the ErrorsIn/Out_delta field.

My request is that the Delta field is displayed as the "Errors In/Out" columns. If there is a need to see the total number of errors on an interface, then those columns can be retained and re-labeled "Total Errors In/Out".

**Comment by penfold1972** [comment]
====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-342-g9a0b06e
DB Schema | 228
PHP       | 7.1.12
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

**Comment by penfold1972** [comment]
> ====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-342-g9a0b06e
DB Schema | 228
PHP       | 7.1.12
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

**Comment by penfold1972** [comment]
I really like the page that shows interfaces with current errors. I just cannot think of a good reason to list the SNMP Counter as the "Error" value over the Error Delta. I am not that concerned about a half duplex management interface having an occasional collision/error, but would be interested in any interface that had a few hundred errors in a polling cycle.
If I see a device that has been up for 160 days and has 2000 in errors, then I have to manually track the errors to know what kind of error rate I am experiencing. It appears the error deltas are being recorded in the database, so it seems like it should be an easy fix to change the columns to use the delta values rather than the counter values. Maybe someone has a good reason to keep the counters on the page, but I can't think of one.

**Comment by laf** [comment]
I actually went to change this but cannot find what you are talking about. The devices -> device -> ports -> errors page doesn't have a textual representation, all errors from what I can see are in the graphs.

Like @kkrumm1 said though, this really is a feature request and is it's not even clear what it is that needs changing (a screenshot would have helped) then I'm closing this.

**Comment by penfold1972** [comment]
![image](https://user-images.githubusercontent.com/24441474/35043539-fd73bf6c-fb5a-11e7-9f66-8260721439df.png)

I've opened as a [https://community.librenms.org/t/port-errors-page-port-errors-vs-errors-delta/3045 Feature Request], but I thought I would include the screenshot here as well.
