### ISSUE TITLE
Export ports search  results as excel 

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#808]
Excel format is more popular at here， can we export export search result as excel ? 

Thank you !

**Comment by paulgear** [comment]
I think CSV would probably be achievable with relative ease, but probably if we supported a spreadsheet format, we would do ODS before Excel.

**Comment by SaaldjorMike** [comment]
I'd say .csv would be perfectly fine and is easy to import in Excel and other spreadsheet softwares.

**Comment by f0o** [comment]
+1 for CSV

**Comment by wzhsunn** [comment]
CSV is ok , would you like to add this feature ?

**Comment by laf** [comment]
CSV export now merged in.

**Comment by wzhsunn** [comment]
Thank you !
