### ISSUE TITLE
Network traffic "Previous" RRD issue

### ISSUE THREAD

**Issue by malicious-cookie** [librenms/librenms#8082]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Validate.php : https://pastebin.com/QTvm7RkQ

Daily.sh : https://p.libren.ms/view/9ce58367

Discovery : https://p.libren.ms/view/998f4ad6

Poller: https://p.libren.ms/view/03294d93

SNMPWALK : causing MySQL error on p.libren.ms, if absolutely needed I can provide via different means

The issue I've ran into is Previous views on "Overall Traffic" RRD graphs. On any server/switch go to the device > Select the graph under "Overall Traffic" > Select "Show Previous" > See "Error Drawing Graph" and if you select "Show RRD Command" you'll see: ERROR: Attempting to reuse 'dpercentile_outXn'  

If you do the same on an individual server interface or switch port the issue does not occur, just on "Overall Traffic". I was sent here per: https://community.librenms.org/t/network-rrd-graph-issue/2981/9

I noticed the same issue occurs on the Official LibreNMS online demo server as well.

**Comment by kkrumm1** [comment]
I have seen this issue also just FYI. Not sure if it issues tho.
