### ISSUE TITLE
Add support for Emerson Network Power NetSure 211

### ISSUE THREAD

**Issue by quartist** [librenms/librenms#8084]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

====================================
Component | Version
--------- | -------
LibreNMS  | 1.35-75-ge372023
DB Schema | 228
PHP       | 7.0.18-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================
Hi,

I would like to request a support of the Emerson Network Power NetSure 211 Power Supply Systems with SCU+ Controller (Standard Control Unit Plus)
Model SCU+: M522B
Currently they’re recognized as Generic Device

https://p.libren.ms/view/04815671
https://p.libren.ms/view/0f3653ea
https://p.libren.ms/view/97ee9cf2

https://www.vertivco.com/globalassets/products/critical-power/dc-power-systems/um1m521bna-rev-ae-scu-controller.pdf

**Comment by PipoCanaja** [comment]
Hi,
It is on the way. Could you please test it with the following command ?
```
./scripts/github-apply 10018
```

Thanx

**Comment by quartist** [comment]
Checking patch includes/definitions/ees.yaml...
error: while searching for:
    - emerson
discovery:
    - sysObjectID:
        - .1.3.6.1.4.1.6302.2.

error: patch failed: includes/definitions/ees.yaml:10
error: includes/definitions/ees.yaml: patch does not apply

**Comment by PipoCanaja** [comment]
The patch was already applied (committed yesterday). So you have to do a ./validate.php and check you are back on the main source, and not with a patch.

**Comment by quartist** [comment]
OK. So I do:
./scripts/github-remove -d
./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.49-105-g9037c07
DB Schema | 2019_02_10_220000_add_dates_to_fdb (132)
PHP       | 7.2.15-1+ubuntu16.04.1+deb.sury.org+1
MySQL     | 5.7.21-20-log
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.8.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct

./daily.sh 
Re-running /opt/librenms/daily.sh as librenms user
Updating to latest codebase                        OK
Updating Composer packages                         OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK

====================================
Component | Version
--------- | -------
LibreNMS  | 1.49-105-g9037c07
DB Schema | 2019_02_10_220000_add_dates_to_fdb (132)
PHP       | 7.2.15-1+ubuntu16.04.1+deb.sury.org+1
MySQL     | 5.7.21-20-log
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.8.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct

after this in includes/definitions/ees.yaml is
discovery:
    - sysObjectID:
        - .1.3.6.1.4.1.6302

**Comment by PipoCanaja** [comment]
exactly correct. 
From here, you do : 
```
rm cache/os_defs.cache
./discovery.php -h <device>
./poller.php -h <device>
```
And you'll be all set.
