### ISSUE TITLE
Updating SmartOptics DCP-2 device support 

### ISSUE THREAD

**Issue by papatango71** [librenms/librenms#8095]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

librenms@nms01-eqch2
[/opt/librenms]$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-350-gd4bd566
DB Schema | 229
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Database connection successful
[OK]    Database schema correct

./discovery.php
https://p.libren.ms/view/5d0792a8

./poller.php
https://p.libren.ms/view/28efec4e

snmpbulkwalk
https://p.libren.ms/view/48c7aa25

The SmartOptics M-Series 1601 shows the state of the PSUs, temperature, & dB levels.  The M-Series DCP-2 does now show any of this.  Below are the SmartOptics MIBs for reference.

![smartoptics_m-series-1610](https://user-images.githubusercontent.com/29801388/35017560-370d0d16-fad2-11e7-9485-08693f9ce7df.jpg)
![smartoptics_m-series-dcp2](https://user-images.githubusercontent.com/29801388/35017561-37242410-fad2-11e7-8ed2-f3414e1c8835.jpg)

[MSERIES-ALARM-MIB.txt](https://github.com/librenms/librenms/files/1637170/MSERIES-ALARM-MIB.txt)
[MSERIES-ENVMON-MIB.txt](https://github.com/librenms/librenms/files/1637171/MSERIES-ENVMON-MIB.txt)
[MSERIES-MIB.txt](https://github.com/librenms/librenms/files/1637172/MSERIES-MIB.txt)
[MSERIES-PORT-MIB.txt](https://github.com/librenms/librenms/files/1637173/MSERIES-PORT-MIB.txt)
[MSERIES-SYSTEM-MIB.txt](https://github.com/librenms/librenms/files/1637174/MSERIES-SYSTEM-MIB.txt)
[MSERIES-TC.txt](https://github.com/librenms/librenms/files/1637175/MSERIES-TC.txt)

**Comment by Rosiak** [comment]
Hey,
I just checked, basically nothing is reported from the device you have pasted hence that information is not picked up. I would probably file a ticket with the vendor.

**Comment by laf** [comment]
It should all be under .1.3.6.1.4.1.30826. You can try re-running the snmpwalk with that at the end instead of the `.`

If it doesn't work then, yeah speak to the vendor.

**Comment by Rosiak** [comment]
Closing, @papatango71 when you have the proper information, post it here and we will reopen the issue.
