### ISSUE TITLE
pre-commit.php issues

### ISSUE THREAD

**Issue by mattie47** [librenms/librenms#8098]
When I try run the pre-commit script, I get issues because of mib SW-MIB:

```
librenms@librenmsdev:~$ ./scripts/pre-commit.php 
Running unit tests... MIB search path: /opt/librenms/mibs
Cannot find module (FCMGMT-MIB): At line 28 in /opt/librenms/mibs/SW-MIB
Did not find 'connUnitPortStatEntry' in module #-1 (/opt/librenms/mibs/SW-MIB)
MIB search path: /opt/librenms/mibs
Cannot find module (FCMGMT-MIB): At line 28 in /opt/librenms/mibs/SW-MIB
Did not find 'connUnitPortStatEntry' in module #-1 (/opt/librenms/mibs/SW-MIB)
MIB search path: /opt/librenms/mibs
```

Deleting the mib fixes things, however this should probably get fixed properly.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
This is fixed in #8066  (although there are issues with NMS-PROCESS-MIB there which are not fixed)
