### ISSUE TITLE
Extreme switch, alert macro, %ports.ifName issue

### ISSUE THREAD

**Issue by MrDragon** [librenms/librenms#8112]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ X] Please provide as much detail as possible.
- [ X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Component | Version
--------- | -------
LibreNMS  | 1.33-358-gbdf02f1
DB Schema | 230
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

I was trying to create an alert rule with "OR" in it (config.php), hence the macro definition, similar to this:
```
$config['alert']['macros']['rule']['test1'] = '%macros.port_down = "1" &&  (
        ( %devices.sysName = "Switch1" && ( %ports.ifName = "2:18" || %ports.ifName = "2:23" ) )
)';
```

Yes, Extreme XOS switches have port names with colons in it :(

Running the "Capture->Poller" to debug/test, you can see that:
```
#### Load poller module ports ####
Caching Oids: SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs -m IF-MIB -M /opt/librenms/mibs udp:HOSTNAME:161 ifXEntry]
ifName.1001 = 1:1
ifName.1002 = 1:2
etc.
```
but I noticed that the SQL query cuts off everything starting at the colon:
```
SQL[SELECT * FROM ports,devices WHERE (( devices.device_id = ports.device_id ) && ports.device_id = '49') && ((((ports.ifOperStatus = "down"  &&  ports.ifAdminStatus != "down"  &&  ((ports.deleted = 0  &&  ports.ignore = 0  &&  ports.disabled = 0)))) = "1"  &&   (
	( devices.sysName = "Switch1"  &&  ( ports.ifName = "2"  ||  ports.ifName = "2" ) )
)) = 1   )] 
```
Now, the "Capture->Alert" still shows things correctly:
```
Alert rule: %macros.test1 = 1   
Alert query: SELECT * FROM ports,devices WHERE (( devices.device_id = ports.device_id ) && ports.device_id = ?) && ((((ports.ifOperStatus = "down"  &&  ports.ifAdminStatus != "down"  &&  ((ports.deleted = 0  &&  ports.ignore = 0  &&  ports.disabled = 0)))) = "1"  &&   (
	( devices.sysName = "Switch1"  &&  ( ports.ifName = "2:18"  ||  ports.ifName = "2:23" ) )
)) = 1   )
Rule match: no match
```

I haven't found out "why" yet - I dimly remember the colon being some separator in the interface description string between keywords like "Peer" or "Transit", but that memory dates back to Observium times - and we're talking about ifName, not ifDescr here.

As a workaround I'm currently using ifIndex (1001,1002,2023,2018, etc.) in the expression, but it would be awesome if ifName could be fixed. Or if someone could point me at where the function is that rewrites the SQL query, I could try my hand at a fix - I just haven't found where that happens (cursory glances...)

Thanks,

Frank

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by MrDragon** [comment]
Apologies - how do I classify this as a bug?
Not being able to use interface names of the format "number-colon-number" in macros is a bug - it works everywhere else.

**Comment by laf** [comment]
Post on the community site.
