### ISSUE TITLE
Edgerouter X - Platform not detected

### ISSUE THREAD

**Issue by thetravellor** [librenms/librenms#8127]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
[root@family librenms]# ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-382-gfbca432
DB Schema | 230
PHP       | 7.0.25
MySQL     | 10.1.30-MariaDB
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Database connection successful
[OK]    Database schema correct

- [X ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
./discovery.php -h edge -d | ./pbin.sh: https://p.libren.ms/view/bf21bfe2
snmpbulkwalk -OUneb -v2c -c public edge . | ./pbin.sh: https://p.libren.ms/view/f6a333bb
./poller.php -h edge.secureconsult.com.au -r -f -d | ./pbin.sh: https://p.libren.ms/view/59fa0408

Also recieved these errors:
Paste endpoint: https://p.libren.ms/api/create
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: tcpHCOutSegs.0

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: tcpHCInSegs.0

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: BRIDGE-MIB::dot1dStpProtocolSpecification.0

- [ X] Please provide as much detail as possible.

Device is a Ubiquiti Edgerouter X running EdgeOS 1.9.7 Hotfix 4
It runs on a MIPSEL Processor
Under the hood Nessus scanner says it runs Linux Kernel 3.10.14-UBNT on Debian 7.11

- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by thetravellor** [comment]
Three pastebin links
https://p.libren.ms/view/bf21bfe2
https://p.libren.ms/view/f6a333bb
https://p.libren.ms/view/59fa0408

**Comment by Rosiak** [comment]
Sadly there's no way to identify that this is edgerouter x(From the SNMP output), same goes with ERL etc. So don't think there's much we can do in this case.

**Comment by thetravellor** [comment]
Hi, isnt the data to identify the product is on the second line of the snmpbulkwalk output?

.1.3.6.1.2.1.1.1.0 = STRING: EdgeOS v1.9.7+hotfix.4.5024279.171006.0255
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.41112.1.5

ubnt OBJECT IDENTIFIER ::= { enterprises 41112 }
ubntEdgeMax OBJECT IDENTIFIER ::= { ubntMIB 5 }

ireasoning mib browser shows that sysObjectID.0 = ubntEdgeMax

Surely at a minimum we can identify the platform as "Ubiquiti EdgeMax" based on the data at hand? Its better than saying nothing at all.

**Comment by murrant** [comment]
We already detect this as EdgeOS.  It doesn't really allow us to differentiate the different models.

From UBNT-MIB:
```
    -- --------------------------------------------------------------------------------
    --                         Ubiquiti Networks Products
    -- --------------------------------------------------------------------------------
    
    ubntAirFIBER OBJECT IDENTIFIER ::= { ubntMIB 3 }
    ubntEdgeMax OBJECT IDENTIFIER ::= { ubntMIB 5 }
    ubntUniFi OBJECT IDENTIFIER ::= { ubntMIB 6 }
    ubntAirVision OBJECT IDENTIFIER ::= { ubntMIB 7 }
    ubntMFi OBJECT IDENTIFIER ::= { ubntMIB 8 }
    ubntUniTel OBJECT IDENTIFIER ::= { ubntMIB 9 }
```

**Comment by Rosiak** [comment]
I tested your walk, your device is already detected as EdgeOS.
