### ISSUE TITLE
Ubiquiti Toughswitch - being recognised as Wireless device (its not)

### ISSUE THREAD

**Issue by thetravellor** [librenms/librenms#8129]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.33-382-gfbca432
DB Schema | 230
PHP       | 7.0.25
MySQL     | 10.1.30-MariaDB
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.2
- [ X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

https://p.libren.ms/view/4c63c765
https://p.libren.ms/view/33fa167f
https://p.libren.ms/view/05c09d31

- [ X] Please provide as much detail as possible.

Device is an 5 port 24vPOE switch: https://www.ubnt.com/accessories/toughswitch/
LibreNMS thinks its a wireless device running AirOS, and only detects its running kernel version as the platform.
Does not seem to graph the interface stats for each switch port either.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
The Toughswitches run AirOS.  Unfortunately, Ubiquiti have abandoned Toughswitches as a product.

There is no way to detect via SNMP if the device is a Toughswitch as far as I can tell.
SNMP does not return port stats.

https://community.ubnt.com/t5/ToughSwitch/SNMP-Issues-with-ToughSwitch/td-p/341320

**Comment by murrant** [comment]
If you have any ideas, we would appreciate them.  But SNMP is not very useful on this product and we know that won't be fixed by the vendor.  Feel free to re-open if can think of something.

**Comment by thetravellor** [comment]
Hi Mate, respectfully I dont agree that Ubiquiti have abandoned the Toughswitch range, and while it only has basic SNMP support it remains on sale globally. The link you provided are various peoples opinions, not an official position by the vendor.

All I was asking was identify the platform correctly, and the data to do this is present in the snmpwalk output I sent you in the pastebin link:

.1.3.6.1.2.1.1.1.0 = STRING: Linux 2.6.32.49 #1 Wed Mar 29 17:47:06 EEST 2017 mips
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.10002.1
.1.3.6.1.2.1.1.3.0 = Timeticks: (43398600) 5 days, 0:33:06.00
.1.3.6.1.2.1.1.4.0 = STRING: unset
**.1.3.6.1.2.1.1.5.0 = STRING: TOUGHSwitch PoE**

**Comment by laf** [comment]
> .1.3.6.1.2.1.1.5.0 = STRING: TOUGHSwitch PoE

That value is sysName which can be changed so isn't reliable enough to allow detection.

**Comment by thetravellor** [comment]
True. I guess you are right, nothing can be done.

**Comment by murrant** [comment]
@thetravellor you can disable the wireless module for these devices in the webui.
