### ISSUE TITLE
No graph with Eth Trunk Sub Interface

### ISSUE THREAD

**Issue by thoms27** [librenms/librenms#8130]
Hello,

I have no graph with Eth Trunk Dot1q sub interface (Eth-Trunk11.200). My device is a Huawei N20E-S2F.
It’s works with the parent interface Eth Trunk 1.
![2018-01-22 16_25_35-172 20 1 15 - ports - librenms](https://user-images.githubusercontent.com/20238377/35228895-2fbe9524-ff92-11e7-8aab-1e6dd94d4aec.png)

Have you got an idea ?

Best regards,

Thomas V.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
