### ISSUE TITLE
cbgp for other vendors (ocnos & cumulus)

### ISSUE THREAD

**Issue by MennoCB** [librenms/librenms#8131]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

I've got two different sort of devices which don't show all the BGP routing information, only showing number of updates but not graphing the number of prefixes.

https://pastebin.com/7ixjQ5Lx   <- IP Infusion OcNOS discovery & poller
https://pastebin.com/500qinN6  <- Cumulus Linux discovery & poller
[bulkwalk_cumulus.txt](https://github.com/librenms/librenms/files/1652267/bulkwalk_cumulus.txt)
[walk_ocnos.zip](https://github.com/librenms/librenms/files/1652608/walk_ocnos.zip)

**Comment by MennoCB** [comment]
[Cumulus-Resource-Query-MIB.txt](https://github.com/librenms/librenms/files/1653754/Cumulus-Resource-Query-MIB.txt)

**Comment by MennoCB** [comment]
snmpbulkwalk -v2c -c public 10.40.1.11 -m /usr/share/snmp/mibs/Cumulus-Resource-Query-MIB.txt > walk_CUMULUS-RESOURCES-MIB

[walk_CUMULUS-RESOURCES-MIB.txt](https://github.com/librenms/librenms/files/1653816/walk_CUMULUS-RESOURCES-MIB.txt)

**Comment by moolinet** [comment]
@PipoCanaja Hi I'm also interested in routing/BGP information of Cumulus devices in Librenms. If you need help for testing let me know :)

**Comment by jozefrebjak** [comment]
@PipoCanaja @MennoCB There is also issue for Huawei VRP, data are discovered but they are not aded to DB **bgpPeers_cbgp**. https://community.librenms.org/t/huawei-ne40e-mk2b-peer-bgp-disappeared-after-system-update/10681/14

**Comment by PipoCanaja** [comment]
@MennoCB  @moolinet I don't think the data is available in the snmpwalk in the Cumulus linux.  
Please attach this exact walk command result so I can replicate the devices and check if there is something doable : 
`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh`

**Comment by MennoCB** [comment]
[snmpbulkwalk.zip](https://github.com/librenms/librenms/files/4676475/snmpbulkwalk.zip)

**Comment by PipoCanaja** [comment]
> @PipoCanaja @MennoCB There is also issue for Huawei VRP, data are discovered but they are not aded to DB **bgpPeers_cbgp**. https://community.librenms.org/t/huawei-ne40e-mk2b-peer-bgp-disappeared-after-system-update/10681/14

Hello @jozefrebjak  Should be OK for ne40e now for cbgp. Could you please check in last master ?

**Comment by jozefrebjak** [comment]
@PipoCanaja do you know what for one NE40 it looks fine, but I need to wait if their graphs will be updated. 

for the second I cant get a successful discovery run. It will stop on 

```
#### Load disco module arp-table ####
communityStringIndexing
SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'COMMUNITY' '-OQUsetX' '-m' 'IP-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/huawei' 'udp:HOSTNAME:161' 'ipNetToPhysicalPhysAddress']
ipNetToPhysicalPhysAddress[4][ipv4]["*"] = ac:8d:34:88:f1:63
etc
etc
etc
Warning: Illegal string offset '' in /opt/librenms/includes/snmp.inc.php on line 678
Cannot create references to/from string offsets {"exception":"[object] (Error(code: 0): Cannot create references to/from string offsets at /opt/librenms/includes/snmp.inc.php:678)"}

In snmp.inc.php line 678:

  Cannot create references to/from string offsets
```

on the second one is there routed a lot of networks.

**Comment by jozefrebjak** [comment]
@PipoCanaja both machines are identical

HardwareNE40E-M2K-B
Operating SystemHuawei VRP 8.190 (V800R011C10SPC100) [V800R011SPH038]

the only load is different.

**Comment by PipoCanaja** [comment]
Hi @MennoCB 
There is nothing about bgp in the Cumulus reply currently. And reading their documentation confirms that they support BGP4-MIB (the standard) when BGP SNMP is enabled. 
So you have to find out how to enable it in FRR, and it will work in LibreNMS out of the box.
Will have a look at ocnos

**Comment by PipoCanaja** [comment]
The ocnos snmpwalk file you provided looks incomplete and not valid. 
Please use the correct command to generate it : 
`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME . > ocnos.list `
and attach the file here.

**Comment by PipoCanaja** [comment]
Hello @MennoCB 
Feel free to re-open this issue if you can provide the required data.
Bye
