### ISSUE TITLE
pi-hole Application snmp extend script

### ISSUE THREAD

**Issue by thetravellor** [librenms/librenms#8135]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.33-384-g87ce23b
DB Schema | 230
PHP       | 7.0.25
MySQL     | 10.1.30-MariaDB
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.2
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

https://p.libren.ms/view/a0b171aa
https://p.libren.ms/view/91b93798
https://p.libren.ms/view/2f059813

- [ x] Please provide as much detail as possible.
hi there I am having trouble getting the pi-hole application monitor to work on Centos 7.4. It worked fine on my old ubuntu 16 server.
I have enabled the application in the librenms web interface, and enable the extend script in the SNMPD config file, and set my pi-hole API in the pi-hole script
This is being done on Centos 7.4 x64
/etc/snmp/snmpd.conf:

#Distro Detection
extend .1.3.6.1.4.1.2021.7890.1 distro /etc/snmp/distro
extend apache /etc/snmp/apache-stats.py
extend osupdate /etc/snmp/os-updates.sh
**extend pi-hole /etc/snmp/pi-hole**
#extend distro /etc/snmp/distro
extend mysql-stats /etc/snmp/mysql-stats
extend smart /etc/snmp/smart -c /etc/snmp/smart.config

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
The script generates an error
./pi-hole
parse error: Invalid numeric literal at line 1, column 10

./pi-hole --debug
[ok] tr bin
[ok] jq bin
[ok] curl bin
[ok] API_URL is set
[ok] API_AUTH_KEY is set
[ok] URL_READ_ONLY is set
[ok] URL_QUERY_TYPE not set

jq --version
jq-1.5

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
You'll need to post this issue in https://github.com/librenms/librenms-agent/
