### ISSUE TITLE
Compatibility with percona cluster.

### ISSUE THREAD

**Issue by quartist** [librenms/librenms#8141]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Hello,

we use Percona-XtraDB-Cluster but LNMS database is not compatible. Percona works in one RW node. We changed base schema and all works good. Could you check new schema and commit to update?
DB changes in validate.php

https://p.libren.ms/view/4fc9eaca
https://p.libren.ms/view/4f0ccd6e
https://www.percona.com/doc/percona-xtradb-cluster/LATEST/features/pxc-strict-mode.html

**Comment by laf** [comment]
I'm not sure what you want to do with this here. If you have schema changes to make please submit them as a pull request as per our docs.

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
