### ISSUE TITLE
Mysql error - null in ports_stp table.

### ISSUE THREAD

**Issue by quartist** [librenms/librenms#8142]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Hello,

in librenms.log we have error like this:
MySQL Error: Incorrect integer value: '' for column 'port_id' at row 1 (UPDATE `ports_stp` set `priority` ='128',`state` ='forwarding',`enable` ='enabled',`pathCost` ='20000',`designatedCost` ='20000',`designatedPort` ='6',`forwardTransitions` ='5',`device_id` ='3',`port_id` ='',`designatedRoot` ='000c30d0dd00',`designatedBridge` ='001b8f7f4700' WHERE `device_id` = '3' AND `port_id` = '')

port_id in update is NULL where in DB schema is mark as NOT NULL: `port_id` int(11) NOT NULL.

https://p.libren.ms/view/4fc9eaca
https://p.libren.ms/view/4f0ccd6e#L1978

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
