### ISSUE TITLE
Interface IDs in traffic bills not updating when device is rediscovered

### ISSUE THREAD

**Issue by LogicalLenny** [librenms/librenms#8144]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 1.35-136-g0a6f113
DB Schema | 231
PHP       | 7.0.25
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

This is an issue with the billing module, so I don't think this is relevant (?). The device in LibreNMS is a Cisco ASA, but I don't think that's relevant. I think this is more about the associated interface IDs not being updated in traffic bills when a rediscover is done.

- [X] Please provide as much detail as possible.

We have a number of traffic bills associated with interfaces on a Cisco ASA. I had to click the "Rediscover Device" button (the reason escapes me right now). I assume this pulled in interfaces with different IDs. The port graphs for the device in LibreNMS were updated as far as I can tell so that they reflect the new interface IDs. However, the interfaces associated with traffic bills were not. 

When it came time to do billing, some customers complaining they were seeing 4x the bandwidth usage. Upon researching, I discovered every bill was associated with the wrong interface.

So I think the interface IDs in traffic bills are not being updated when a device is rediscovered.

- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

I am not sure what debug info to give. I'm not finding anything in the logs. This may be more of a missing "feature" than a bug.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by LogicalLenny** [comment]
I'm confused. How is this not a bug? If you rediscover a device, all of the associated interfaces in billing are wrong. Since there's no way of regenerating a bill, that seems like a pretty huge bug to me.

**Comment by laf** [comment]
That means the ID is changing but doesn't mean it's a bug, you should ask for help with this before posting here. You most likely want to use a different port association mode. There is no reason why a port will change ID unless it's changed it's ifIndex.

**Comment by LogicalLenny** [comment]
I don't mean to be argumentative, but I think we're not really talking about the same thing. I don't need help on how to configure and manage this. I'm saying it's possible to completely break traffic bills, and when that happens they start pulling data from the wrong interface because the ifIndex changes.

That is precisely what is happening. If you do a device rediscover, ifIndex's can (and probably will) be different, because they'll be different in the SNMP response. Enumerated devices (interfaces, disk, etc) are not guaranteed to be the same ID, especially across reboots. In the case of ifIndex, on a busy firewall, existing interfaces can change frequently. We still want the "Lenny" interface to be the "Lenny" interface in port graphs and billing, tho, even if it changes ifIndex. I assume there is code taking this into account for port graphs, because all of my port graphs are the same after the rediscover. Based on traffic patterns, I know for sure that the "Lenny" port graph is for the correct interface, despite it's ifIndex changing.

There is no such code for traffic bills, or it's broken. The "Lenny" interface is no longer the "Lenny" interface because it's ifIndex has changed because of a rediscover. Whatever takes care of this reconciliation for port graphs is not taking care of the same issue in traffic bills. 

I suppose this could be dealt with by saying "Doing a rediscover breaks traffic bills. Deal.". I can accept that, but I was kind of hoping since there's obviously code somewhere to deal with this regarding port graphs, a fix could be put into place to fix ifIndex numbers for traffic bills on rediscover, also.

**Comment by murrant** [comment]
@LogicalLenny not all devices/configs do stupid things with ifIndex.
Go to the bad devices edit settings (under snmp tab) and change port association mode to one appropriate for your device/config.
