### ISSUE TITLE
OS-Updates slow

### ISSUE THREAD

**Issue by tim427** [librenms/librenms#8154]
All my Linux-based servers are SNMP-extended with "os-updates.sh". Sometimes, this scripts takes ages to complete (sometimes 10+ seconds), which results in a time-out on the poller script.

Result: Application OS-Updates will be remove and added later, when the scripts finishes in time, next time the poller requests this value.

As a suggestion/feature-request/discussion, I propose the following procedure:

1. Load the value of "os-updates.txt"
2. Immediately return this "old/previous" value
3. Check for updates in the background and save this to the "os-updates.txt"

Pro: Script return immediately, no time-outs nor high poller-times
Con: The returned value is "old", as in: the previous value.

What do you guys think? Is this acceptable? A improvement?

If so, I could rewrite the "os-update.sh"!

====================================

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
```
Component | Version
--------- | -------
LibreNMS  | 1.33-393-g2755763
DB Schema | 232
PHP       | 7.0.25
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

```
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This belongs in the librenms/librenms-agent repo.

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by arrmo** [comment]
Hi,

Just an FYI, in case it helps (as I had similar issues) - change the timeout for the slow devices that aren't responding in time (Raspberry Pi perhaps?). Fixes the issue ... :).
