### ISSUE TITLE
os type detection request

### ISSUE THREAD

**Issue by merlinke** [librenms/librenms#8159]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations
server:
====================================
Component | Version
--------- | -------
LibreNMS  | 1.35-145-g92e1048
DB Schema | 232
PHP       | 7.0.25
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================
https://p.libren.ms/view/1e529975   <-discovery
https://p.libren.ms/view/425b89e0   <-poller
https://p.libren.ms/view/5cdf6b55    <-snmpwalk

hello, please add this os type as camera.
Also since some devices are getting detected as camera, it would be good to by default include camera type in the selection screen.

Thanks,

**Comment by murrant** [comment]
What is the manufacture and make of this device?

**Comment by merlinke** [comment]
web page: https://www.vivotek.com/website/ib8367a/#views:view=jplist-grid-view
