### ISSUE TITLE
Printers

### ISSUE THREAD

**Issue by FrankyLibre** [librenms/librenms#8171]
After Update to the newest version all printers are now detected as network devices.
Any ideas ???

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by FrankyLibre** [comment]
I dont understand that !!!
We have aprox over 20 Printers and they work in libre before the update and after the update
they are suddenly detected as network devices. So we have no informations about toner.
In the faq is nothing about printers.

And you decide that is not a bug ? Lol

Regards

Frank



-------------------------------------------------------------------------------------------------------------------------------------------------

Von: Neil Lathwood [mailto:notifications@github.com]
Gesendet: Montag, 29. Januar 2018 16:32
An: librenms/librenms <librenms@noreply.github.com>
Cc: Drehmann Frank <f.drehmann@ja-info.com>; Author <author@noreply.github.com>
Betreff: Re: [librenms/librenms] Printers (#8171)


This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by murrant** [comment]
@FrankPetrilli all my printers are working great.  

Please head to https://community.librenms.org or https://t.libren.ms/discord to troubleshoot your problem.

Also, you did not really provide any info and you deleted the section that says DO NOT DELETE.

**Comment by FrankPetrilli** [comment]
@murrant Wrong username, I had no involvement in this issue, though I have contributed to the project before. You meant to mention @FrankyLibre.

**Comment by murrant** [comment]
Bad GitHub, sorry.
