### ISSUE TITLE
Active Directory API tokens

### ISSUE THREAD

**Issue by NerdBlender** [librenms/librenms#8179]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Weird issue, that i /think/ was working until recently. I just restarted my oxidized instance, and got and error, which seems to be related to the API auth token - no worries, I switched from local to AD auth, so I'll just generate a new token - however i now get this:

![image](https://user-images.githubusercontent.com/23742981/35632269-19631b48-069e-11e8-9210-8d4adc564ff6.png)

No users in the dropdown. I read a few of the issues relating to this, can see that it was fixed last year, but note sure why my instance is not working. I tried adding  $config['auth_api_local'] = true; to my config, but there is no difference.

any ideas, not sure what debug information i can provide.

**Comment by laf** [comment]
You need to use a bind user for AD. Docs have the config needed for this.

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by NerdBlender** [comment]
I do have a bind user config:

$config['auth_mechanism'] = "active_directory";
$config['auth_ad_url'] = "ldap://domain.com";
$config['auth_ad_domain'] = "domain.com";
$config['auth_ad_base_dn'] = "dc=domain,dc=com";
$config['auth_ad_check_certificates'] = false;
$config['auth_ad_binduser'] = 'bind@domain.com';
$config['auth_ad_bindpassword'] = 'password!';
$config['auth_ad_timeout'] = 5;
$config['auth_ad_debug'] = false;
$config['auth_ad_require_groupmembership'] = true;
$config['auth_ad_groups']['LibreNMS-RW']['level'] = 10;
$config['auth_ad_groups']['LibreNMS-RO']['level']  = 7;
$config['auth_ad_user_filter'] = "(objectclass=user)";
$config['auth_ad_group_filter'] = "(objectclass=group)";
$config['auth_api_local'] = true;

**Comment by murrant** [comment]
is ldap timing out `$config['auth_ad_timeout'] = 5;`?

**Comment by laf** [comment]
He's fixed it.
