### ISSUE TITLE
Add Support - Ciena Waveserver

### ISSUE THREAD

**Issue by taking-care-of-business** [librenms/librenms#8183]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

====================================
Component | Version
--------- | -------
LibreNMS  | 1.36-80-ga6a1f08
DB Schema | 232
PHP       | 7.0.25
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

Please add support for the Ciena Waveserver device.

https://p.libren.ms/view/d21927f7 (Discovery)
https://p.libren.ms/view/1fee7a29 (Poller)
https://p.libren.ms/view/1bf4f9ca (SNMP Walk)

**Comment by taking-care-of-business** [comment]
I thought I included MIBs in the initial post. Here they are.
[ciena-ws-MIB-files_01-05-00-00.zip](https://github.com/librenms/librenms/files/1708298/ciena-ws-MIB-files_01-05-00-00.zip)

**Comment by PipoCanaja** [comment]
PR added.

**Comment by PipoCanaja** [comment]
@taking-care-of-business Feel free to test PR #9930
