### ISSUE TITLE
Versioned Release  for porting to FreeBSD

### ISSUE THREAD

**Issue by 5u623l20** [librenms/librenms#819]
As a FreeBSD ports committer I was planning on porting this app to FreeBSD. Is there a possibility of releasing a version near soon. I need at least a version released prior to porting this.

**Comment by laf** [comment]
Do you mean an official version number @5u623l20 ?

**Comment by 5u623l20** [comment]
Yes. In terms of GitHub lingo you can say "Releases".

**Comment by laf** [comment]
We should definitely do this.

@paulgear @f0o.

What do you guys think? I'd like to see a 1.0 release if possible.

**Comment by 5u623l20** [comment]
If you guys want to delay 1.0 I am also good with 0.1. But I need a released version. 3:)

**Comment by f0o** [comment]
We need to talk about versioning cycles and policies :)

**Comment by laf** [comment]
@5u623l20 done. v0.1 it is.

**Comment by paulgear** [comment]
Hi @5u623l20 - here's my take: with LibreNMS, we don't really think about versioning.  This is both a hangover from Observium, and a conscious choice in the sense that we want people to stay as close to HEAD git master as possible.  So my preference would be for people who want to distribute it separately to version based on date.

When your build script downloads the source to package it up for FreeBSD, use UTC TZ and set the version to $(date +%Y%m%d.%H%M%S).  That way you always get an increasing version number, and when someone says they're running a particular version number, we can just go back through the git logs and find out which revision that was.  This would minimise the manual effort required to maintain versioning.

Let me know what you think.

**Comment by 5u623l20** [comment]
Sounds good.

**Comment by sthen** [comment]
Hi. As a new LibreNMS user (and OpenBSD developer working on packaging it) I see this from several perspectives. In the end, your project your rules and packagers will usually manage to cope, but I'd like to chip in with my £0.02 worth, mostly from a packager point of view ;-)

As a packager, having "traditional" versioned releases can be very useful. For logistics, I don't know about other OS but I assume that it's pretty common, as it is on BSDs, to download a specific file and check hashes to make sure it has not been altered. Without an upstream release you often end up with a number of different OS packagers preparing their own tar.gz files from various different versions of code and hosting them on random webservers.

Even just tagging versions from time to time would be a big help, providing a useful way to highlight major code changes to those not following the project closely enough to read the whole commit log - this is especially useful around OS release times it can be useful to easily determine whether there have been big changes warranting additional caution or testing.

We sometimes run into problems where projects re-tag things thus changing github's auto-generated tar.gz files (or, though this is less common nowadays, github changing their infrastructure resulting in file changes); so actual uploaded tar.gz releases which don't change after release are often preferable for packagers.

As a developer it's extra work to step back and decide "this code is in a particularly good state, X new feature has been included and had sufficient testing, or Y important bug has been fixed, I want to tag this and prepare a release". But on the other hand, if OS are interested in providing packages anyway, users of those are by definition not going to be tracking git master, so it seems to make sense to have the choice of exact versions of code under control of people involved day-to-day with the project.

**Comment by laf** [comment]
Tagging @paulgear for further comments.

**Comment by paulgear** [comment]
I must admit I'm not impressed by the arguments for versioning at this stage (I fear that I'm turning into the Dev that us Opses are supposed to despise! :-), but I'm open to further discussion.  Let's put this one down to talk about in our semi-proposed meeting.

**Comment by laf** [comment]
I can see an OpenBSD port has gone live via @sthen.

@5u623l20 can you confirm if you need anything more from us to do a port on FreeBSD?

**Comment by 5u623l20** [comment]
I am good with it. If you refer to continue in this versioned manner I will commit the new port. If you refer to a previously mentioned dated version I will need to modify something and eventually will commit too. :)

**Comment by laf** [comment]
Thanks @5u623l20. I'm not sure @paulgear's preference is to maintain a version number.

Not sure how OpenBSD have done it, is it possible to follow their lead?

**Comment by paulgear** [comment]
I hope I've already stated my preference clearly. :-)  But as long as @laf is happy to tag version numbers every once in a while, I'm not that worried.  Perhaps we should just do it once a month on the 1st of the month and call the version YYYY.MM?

**Comment by laf** [comment]
I'm certainly happy to start tagging.

I try and do the changelog weekly / bi-weekly on a sunday. What I'll do is add in a new version to be tagged on the first sunday of each month.

I'd personally like to come up with a better version than just YYYY.MM. I know @f0o has mentioned a format before which sounded good - good enough for me to forget what it is!!

**Comment by laf** [comment]
Ok, so we've agreed the following:

1st Sun of each month I'll tag the new version YYYY.MM. If we have a major release go out and we want to notify people of this then we will release YYYY.MM.DD.

**Comment by pmcnary** [comment]
I am interested in a FreeBSD port also. I am using XinuOS fork of 10.1 OpenServer X.
I am porting some applications and testing others for different porters.
I normally have several FreeBSD 10.1+ and OpenServer X vm's available in various states of install
to test with. 
Be happy to assist especially with testing and debugging problems.
Take care
Paul McNary pmcnary@cameron.net
