### ISSUE TITLE
BGP Peering Graphs showing incorrect values

### ISSUE THREAD

**Issue by kadecole** [librenms/librenms#8191]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.36-16-ga347e7c
DB Schema | 233
PHP       | 7.1.11
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/d8f4c0cb
https://p.libren.ms/view/3298f489
- [x] Please provide as much detail as possible.
BGP Peer Prefix graphs are no longer showing correct prefix counts. 

```
SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -OQUs -m CISCO-BGP4-MIB -M /home/librenms/mibs:/home/librenms/mibs/cisco udp:HOSTNAME:161  cbgpPeer2AcceptedPrefixes.1.4.206.166.8.4.1.1 cbgpPeer2DeniedPrefixes.1.4.206.166.8.4.1.1 cbgpPeer2PrefixAdminLimit.1.4.206.166.8.4.1.1 cbgpPeer2PrefixThreshold.1.4.206.166.8.4.1.1 cbgpPeer2PrefixClearThreshold.1.4.206.166.8.4.1.1 cbgpPeer2AdvertisedPrefixes.1.4.206.166.8.4.1.1 cbgpPeer2SuppressedPrefixes.1.4.206.166.8.4.1.1 cbgpPeer2WithdrawnPrefixes.1.4.206.166.8.4.1.1]
cbgpPeer2AcceptedPrefixes.ipv4."*".ipv4.unicast = 673604
cbgpPeer2DeniedPrefixes.ipv4."*".ipv4.unicast = 0
cbgpPeer2PrefixAdminLimit.ipv4."*".ipv4.unicast = 1048576
cbgpPeer2PrefixThreshold.ipv4."*".ipv4.unicast = 75
cbgpPeer2PrefixClearThreshold.ipv4."*".ipv4.unicast = 75
cbgpPeer2AdvertisedPrefixes.ipv4."*".ipv4.unicast = 40
cbgpPeer2SuppressedPrefixes.ipv4."*".ipv4.unicast = 0
cbgpPeer2WithdrawnPrefixes.ipv4."*".ipv4.unicast = 0
  
RRD[update router1-mgmt/cbgp-206.166.8.4.ipv4.unicast.rrd N:6:6:6:6:6 --daemon unix:/run/rrdcached.sock]
```

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
@kadecole Mind testing this patch please: https://p.libren.ms/view/raw/2a021729

The odd thing with this is that this code looks like it's never worked for the last couple of years and I can't see why it would have broke for you.
