### ISSUE TITLE
All Device Processors got Removed today

### ISSUE THREAD

**Issue by nenad007** [librenms/librenms#8205]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Today morning all Processorr got removed from Librenms for every Device:
Processor Removed: hr 196608 Intel Xeon E31220 @ 3.10GHz 
Processor Removed: hr 196609 Intel Xeon E31220 @ 3.10GHz
...

 ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.36-25-gfa1d9e9
DB Schema | 234
PHP       | 7.2.2
MySQL     | 5.7.21
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Database connection successful
[OK]    Database schema correct

Any Solution for this?

**Comment by dmoldovan123** [comment]
yes all my devices has 1 CPU or none

**Comment by dmoldovan123** [comment]
2018-02-06 00:33:19 | System | Processor Removed: hr 196608 Pentium Dual-Core E5300 @ 2.60GHz
-- | -- | --
  | 2018-02-06 00:33:19 | System | Processor Removed: hr 196609 Pentium Dual-Core E5300 @ 2.60GHz

**Comment by nenad007** [comment]
@murrant
Seems caused by #8066

**Comment by dmoldovan123** [comment]
now all devices have CPUs 

2018-02-06 12:33:19 | System | Processor Discovered: hr 196609 Pentium Dual-Core E5300 @ 2.60GHz

**Comment by dmoldovan123** [comment]
now system is normal

**Comment by nenad007** [comment]
here too, I'm closing this.
