### ISSUE TITLE
Feature Request: Support IBM G8124-E Switch

### ISSUE THREAD

**Issue by Lonecrowe** [librenms/librenms#821]
http://pastebin.com/yKUk3vxd

Standard walk above.  

Let me know if you need the enterprises section.  I don't have the mib handy at the moment.

**Comment by laf** [comment]
I've updated the standard ibmnos poller to fallback to using entPhysicalSerialNum and  entPhysicalSoftwareRev rather than defaulting to nothing.

IBM nos should be detected ok so I'm assuming it's just those values you are missing. This may not resolve it for this switch model - but it might :)

**Comment by Lonecrowe** [comment]
This was for Rosiak I believe.  He wanted to look at them to see if it could be improved.  

It did detect this switch but it shows as down even though one of the management interfaces is up.

**Comment by Lonecrowe** [comment]
Can close this one.  I think it was just the wonky switches that I had.
