### ISSUE TITLE
Adding service checks by API - character escaping problem

### ISSUE THREAD

**Issue by dragans** [librenms/librenms#8218]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Component | Version
--------- | -------
LibreNMS  | 1.36.01
DB Schema | 232
PHP       | 7.0.23
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

Problem is similar to the following issue, only it's occurring when utilizing API call to add a service check - https://github.com/librenms/librenms/issues/4891

As a workaround, we modified html/includes/api_functions.inc.php like this:

> //    $service_param = $data['param'] ? mres($data['param']) : '';
>    $service_param = $data['param'] ? $data['param'] : '';

I had a small chat with murrant yesterday about this. Not using mres function is generally not a good idea, as it could allow a SQL injection (not that big of a issue, as our monitoring is not public hosted). After the commit related to the issue linked above, adding services via http form is not using mres function when inserting data into database and it's not escaping the offending characters.

Problem here actually is that there is no function to remove the added backslash characters when reading the data from the services table.

We can live with our workaround for now. We wanted to consult with you about the plans to fix this issue, as we are creating some ansible scripts for automating service checks via API and would need to modify them if the functions get changed at some point. We could maybe help with code changes, but it would be better to know in which direction to go. :)

You can also find me on discord as dsgagi.

**Comment by laf** [comment]
We need examples to test against or we will have to close the issue.

**Comment by dragans** [comment]
Totally forgot, sorry.

Here are two examples (using check_by_ssh) that we use and that currently work when added with http form.

`
-t 20 -l root --command='/etc/netcast/monitoring/nagios-plugins/check_load -w "$(expr $(nproc) \* 2),$(nproc),$(nproc)" -c "$(expr $(nproc) \* 8),$(expr $(nproc) \* 4),$(expr $(nproc) \* 4)"'
`

`
-t 10 -l root --command='/etc/netcast/monitoring/nagios-plugins/check_mem_c6 -C -f -w 20 -c 10'
`

When adding services via API call, the parameter string is added like below example into database and doesn't execute on remote host because it is executed as below.

`-t 20 -l root --command=\'/etc/monitoring/nagios-plugins/check_load -w \"$(expr $(nproc) \\* 2),$(nproc),$(nproc)\" -c \"$(expr $(nproc) \\* 8),$(expr $(nproc) \\* 4),$(expr $(nproc) \\* 4)\"\'`

`-t 10 -l root --command=\'/etc/netcast/monitoring/nagios-plugins/check_mem_c6 -C -f -w 20 -c 10\'`

**Comment by laf** [comment]
Sorry I mean provide the re-producible api calls. Once we have these we can re-open the issue.

**Comment by dragans** [comment]
Sorry for not responding sooner. Busy schedule at work :smiley: 

Here are example steps for adding CPU LOAD service check via API, that we use on our Linux VMs. We use similar steps to add service checks via ansible scripts.

- create a text file (**/tmp/cpu-load.json** - please replace ip address and command path for your setup) with the following content
`{"type": "by_ssh","ip": "192.168.1.10","desc": "CPU LOAD TEST","param": "-t 20 -l root --command='/path/to/check_load -w \"$(expr $(nproc) \\* 2),$(nproc),$(nproc)\" -c \"$(expr $(nproc) \\* 8),$(expr $(nproc) \\* 4),$(expr $(nproc) \\* 4)\"'"}`

- create a ssh key for librenms user on the monitored server

- execute the API call via curl
`curl -X POST -d @/tmp/cpu-load.json -H 'X-Auth-Token: YOURAPITOKENHERE' https://librenms.org/api/v0/services/192.168.1.10`

By using **nproc** function here, we don't need to edit the service check parameters if the VM's number of vCPU ever changes.

**Comment by dragans** [comment]
Should I open a new issue and link this closed one in it maybe?

**Comment by laf** [comment]
I'm not actually sure we have a fix for this right now. This needs to be really dealt with when we switch to laravel as it should deal with this.

**Comment by dragans** [comment]
That's great! Looking forward to it :-)Thank you for all your work on LibreNMS. CheersOn Apr 28, 2018 00:03, Neil Lathwood <notifications@github.com> wrote:I'm not actually sure we have a fix for this right now. This needs to be really dealt with when we switch to laravel as it should deal with this.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




I'm not actually sure we have a fix for this right now. This needs to be really dealt with when we switch to laravel as it should deal with this.
