### ISSUE TITLE
Auto upgrade breaks LibreNMS

### ISSUE THREAD

**Issue by patrick7** [librenms/librenms#8221]
The LibreNMS installation shows `Error: Missing dependencies, run: composer install --no-dev `
(Multiple installations on debian/ubuntu, different PHP versions). 

I was never using composer...

How to fix?

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by murrant** [comment]
For the record.  You will need to install composer.  (this will be fixed for the monthly released)

This happens when your LibreNMS install has github access but not internet access or some other form of broken internet access.

**Comment by patrick7** [comment]
I'm aware of at least 3 broken instances from 3 separate entities. I don't think we are too stupid to configure internet access. DNS / ICMP / HTTP / Git, whatever is working like a charm. The only broken thing seems to be the upgrade script.

**Comment by murrant** [comment]
Github is not a help forum, it is for confirmed bugs only.  Most installs have updated successfully.  I did not say anything about your ability to configure internet access.

Locking thread. For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
