### ISSUE TITLE
Cisco IOS XE Devices - No CPU Graph after update

### ISSUE THREAD

**Issue by NetCo-Jan** [librenms/librenms#8228]
Hi Guys, 
it seems that somewhere around the start of February after a update all IOS-XE devices CPU graphs stopped working. This is only affecting IOS-XE devices

Attached is a poller debug of one device and some screenshots where CPU graphing was working up to a point and then stopped

Note this is a fairly new install (only 3 weeks old)

please can you assist ? 

[Poller Debug - rbk-cen-ds-01.log](https://github.com/librenms/librenms/files/1705948/Poller.Debug.-.rbk-cen-ds-01.log)
![cpu graph](https://user-images.githubusercontent.com/24909687/35958861-b20b92ae-0cab-11e8-9fa6-b99b93d084de.png)

librenms@librenms:~$ ./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 1.36-44-g9777963
DB Schema | 234
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.33-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Database connection successful
[OK]    Database schema correct
librenms@librenms:~$ 

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by NetCo-Jan** [comment]
![device screenshot](https://user-images.githubusercontent.com/24909687/35959257-7e5af1a0-0cad-11e8-87c1-acd8aed5fbf0.png)

**Comment by olivierbeytrison** [comment]
I can also confirm that we lost all the CPU graph for IOS XE devices on tuesday

**Comment by laf** [comment]
We really need the output from all of these commands: http://docs.librenms.org/Support/FAQ/#faq20

**Comment by olivierbeytrison** [comment]
I'm doing it right now. But I keep getting odd errors using pbin.sh :
A Database Error Occurred
Error Number: 2006
MySQL server has gone away
SELECT RELEASE_LOCK('7f531s4tm342o27cdf54kg2059') AS ci_session_lock
Filename: libraries/Session/drivers/Session_database_driver.php
Line Number: 399

**Comment by olivierbeytrison** [comment]
[Poller](https://gist.github.com/olivierbeytrison/5b49568e2375839f90e585064b513cc7)
[Discovery](https://gist.github.com/olivierbeytrison/ce9fdac31a73b5b029ca7a14c1f3ccd9)
[SNMPWalk](https://gist.github.com/olivierbeytrison/d7b0c381693e1913dfcf2fe7b1e18638)

**Comment by NetCo-Jan** [comment]
Hi

Thank you, this isn’t really a new devices as IOS-XE has been graphing for some time on other installs

**Comment by NetCo-Jan** [comment]
https://p.libren.ms/view/7b05c156    - Discover
https://p.libren.ms/view/7893bfce     - Poller
https://p.libren.ms/view/4a003377    - SNMP Walk

**Comment by murrant** [comment]
Looks like it is collecting data, just not graphing.

**Comment by NetCo-Jan** [comment]
How can we fix this ?

**Comment by NetCo-Jan** [comment]
Hi Guys
as of 12:00 GMT+2 time CPU's started graphing again after running./daily.php
![image](https://user-images.githubusercontent.com/24909687/35986961-315d3498-0d03-11e8-9325-1b80abf19914.png)


Thank you very much for the quick assistance ! Much appreciated

**Comment by murrant** [comment]
just needed to wait?

**Comment by NetCo-Jan** [comment]
Not sure what happens but all 8 IOS-XE devices started graphing at that interval - so im happy :-)
