### ISSUE TITLE
Cisco Catalyst 9300 not correctly recognized

### ISSUE THREAD

**Issue by olivierbeytrison** [librenms/librenms#8244]
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 1.36-63-g16424ef
DB Schema | 235
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.33-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

[Discovery](https://p.libren.ms/view/bf5e8644)
[Poller](https://p.libren.ms/view/350392a5)
[SNMP Walk](https://gist.github.com/olivierbeytrison/64732b1d3ca7e711d6ebe2dafc5b77e4)

The devices is not recognized correctly (Hardware shown as ciscoProducts.2494)

![image](https://user-images.githubusercontent.com/2838126/36092285-1de9377c-0fe7-11e8-928e-b1a91a39eeb0.png)

**Comment by PENorris** [comment]
Same things happens on my new Catalyst 9500 as well.  However, I don't think Cisco has updated their devices mib to include the new Cat 9k line.

**Comment by Rosiak** [comment]
Cisco haven't updated their MIB yet, ftp://ftp.cisco.com/pub/mibs/v2/CISCO-PRODUCTS-MIB.my
So I suggest you push them directly for that.
