### ISSUE TITLE
Maintenance windows allow end date before start date

### ISSUE THREAD

**Issue by bryjane37** [librenms/librenms#8248]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
====================================
Component | Version
--------- | -------
LibreNMS  | 1.36.01
DB Schema | 232
PHP       | 7.0.25-0ubuntu0.16.04.1
MySQL     | 10.0.33-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
When I navigate to the above URL, it takes me to the fact page and defaults to the question "What information do you need to add a new OS?" Since this issue is with maintenance windows, I was not sure what I should add additionally from this FAQ page. Please let me know if I can submit any other information or logs. 

- [ ] Please provide as much detail as possible.
When creating a new maintenance window, the user can enter an end date before the start date. It will display as shown below in the DB, and the window's status will be set to Current. 
SQL QUERY:
SELECT schedule_id, start, end, title from alert_schedule;
OUTPUT:
...
|         255 | 2018-02-16 12:00:00 | 2018-02-13 13:34:00 | Testing backwards maintenance window             |
+-------------+---------------------+---------------------+--------------------------------------------------+

- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
PR's welcome.

I'm tempted to close this to be honest, the webui will start getting an overhaul at some stage and as this isn't actually a problem then I don't think it's worth time to fix right now.

**Comment by laf** [comment]
I'm closing this down. It's not a show stopper and that page will most likely get a refactor at some stage.
