### ISSUE TITLE
Add support for datacore

### ISSUE THREAD

**Issue by Friendbg** [librenms/librenms#8249]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
-- | --
LibreNMS  | 1.36-65-gdf724a7
DB Schema | 235
PHP       | 7.0.27-1+ubuntu16.04.1+deb.sury.org+1
MySQL     | 10.0.33-MariaDB-0ubuntu0.16.04.1
RRDTool | 1.5.5
SNMP | NET-SNMP 5.7.3

[Discovery](https://p.libren.ms/view/0414bc5d)
[Poller](https://p.libren.ms/view/9e4f0677)
[Snmpbulkwalk](https://p.libren.ms/view/4308e801)

I'm using [check_sansymphony](https://exchange.icinga.com/netways/check_sansymphony) - plugin for nagios which detects datacore perfectly - [here are the results](https://p.libren.ms/view/b11fb5fa) from my datacore server.
[Official support for SNMP from datacore](https://www.datacore.com/SSV-Webhelp/SNMP_Support.htm)

**Comment by trcyberoptic** [comment]
Current DataCore MIB: https://p.libren.ms/view/c73844a6

**Comment by Friendbg** [comment]
Thanks @trcyberoptic 

Could you please give quick info how to use it?

Thanks

**Comment by trcyberoptic** [comment]
@Friendbg you can't use it in LNMS, someone needs to add that into the codebase. added that because I also have the same feature request.

**Comment by PipoCanaja** [comment]
@Friendbg @trcyberoptic Yes, we need somebody to jump into this feature request. If you feel doing it, don't hesitate :) LibreNMS is a community project made by us for us. 
This feature request should probably be handled as an "application" in the LibreNMS architecture, as it goes on top of an existing OS (Windows in the case of the current test data in this Issue).
You can see how current applications are designed and start from there.

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11667

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/add-support-for-datacore/11667/1
