### ISSUE TITLE
DELL S4048-ON/S3048-ON healthstate-sensors missing

### ISSUE THREAD

**Issue by cloudprodz** [librenms/librenms#8259]
discovery:
https://defuse.ca/b/ITa6jJXL
poller:
https://defuse.ca/b/VSmXFh0A
snmpbulkwalk:
https://defuse.ca/b/Qz4NUCIu

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
====================================
Component | Version
--------- | -------
LibreNMS  | 1.36-69-g2a4dd70
DB Schema | 235
PHP       | 7.0.25
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Do NOT post observium stuff here.

**Comment by Rosiak** [comment]
Can you provide some information where we can expect to find this information?(MIB wise)

**Comment by theherodied** [comment]
Will this be dependent on the OS? Since it's an ON switch it might be running OS9, OS10, Cumulus Linux, Pica 8, etc....

Will probably need the MIB for the specific OS which I'm guessing in this case is OS9. I was planning on asking for this with Cumulus on a S4048-ON once I reach out to their support.

**Comment by cloudprodz** [comment]
Hi, thanks for the replies. I've uploaded the MIBs for OS9 in https://drive.google.com/open?id=1x10lkW1kOuNvLDZUT8-VTmofJGV6XOi6

**Comment by laf** [comment]
Please use a pastebin service that provides the data raw, the walk here is unusable.

**Comment by cloudprodz** [comment]
Here you go:
[dell-discovery.txt](https://github.com/librenms/librenms/files/1931947/dell-discovery.txt)
[dell-poller.txt](https://github.com/librenms/librenms/files/1931948/dell-poller.txt)
[dell-bulkwalk.txt](https://github.com/librenms/librenms/files/1931949/dell-bulkwalk.txt)

**Comment by cloudprodz** [comment]
[pollingdebug.txt](https://github.com/librenms/librenms/files/2145308/pollingdebug.txt)
[snmpdata.txt](https://github.com/librenms/librenms/files/2145309/snmpdata.txt)
[discoverydebug.txt](https://github.com/librenms/librenms/files/2145310/discoverydebug.txt)
[dnos.yaml.txt](https://github.com/librenms/librenms/files/2145317/dnos.yaml.txt)

I tried making the yaml for a few sensors but I'm having trouble with the poller trying to use 'stack' in the oid itself. Could someone check the syntax and used values?

**Comment by PipoCanaja** [comment]
@cloudprodz 
Could you check https://github.com/librenms/librenms/issues/9603 ? Should cover this issue as well. 
Bye

**Comment by MrXermon** [comment]
@PipoCanaja Dell S4048-ON look good for me with PR #10016.

**Comment by PipoCanaja** [comment]
Seems that support is now OK. Closing this.
