### ISSUE TITLE
creating API tokens silently fails

### ISSUE THREAD

**Issue by DennisSc** [librenms/librenms#8262]
Hi,

I'm having issues with creating API keys in the web GUI. Not sure if this is a bug, or if just my nms instance has gone haywire...

I'm trying to add new API token for a particular user. All user accounts are shown on the API token creation page, and the user accounts are selectable from the pulldown menu, and the random token is generated and displayed just fine - just nothing happens when clicking on the green "Create API token" button (besides of the page being closed). The API token page shows no token after trying to add one.

The token is also not saved to the DB (verified in mysql: no new row was inserted in "api_tokens" table). 

I can, however, copy to clipboard and then manually insert the "generated-but-not-saved" API token into the "api_tokens" table (via mysql INSERT statement, as the librenms mysql user), and this manually added token then works fine - and is shown in the web GUI (including QR code) as well.

Why can't I create/add API tokens on my web GUI - is some setting needed to enable API token generation? (I already checked all log files under /opt/librenms/logs, but found no obvious errors when this happens - I may be looking at the wrong place though)

Anyone have an idea where to start searching?

(edit- just patched+rebooted the whole system but error still persists, I updated tthe current output of validate.php below )

Thanks

_________________________________
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

```
====================================
Component | Version
--------- | -------
LibreNMS  | 1.36-70-gc14efbf
DB Schema | 235
PHP       | 5.6.33-0+deb8u1
MySQL     | 10.0.32-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
====================================
```

- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
I've tested api tokens work so this doesn't seem like a bug.

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by DennisSc** [comment]
Thanks for checking - then I probably have something broken, which I will need to fix locally...
