### ISSUE TITLE
new alert rules save on mysql double quotes

### ISSUE THREAD

**Issue by rgngpp** [librenms/librenms#8264]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Hi 
when I insert a new alert the value is saved in mysql with 4 double quotes.
es. i insert value "90" and the result in gui is %processors.processor_usage >= ""90"" &&
this is record mysql: 
| 16 | -1        | %processors.processor_usage >= ""90""                                                                            | critical | {"mute":false,"count":"1","delay":300,"invert":false,"interval":300}  |        0 | test double             | SELECT * FROM processors WHERE (processors.device_id = ?) && (processors.processor_usage >= ""90"" )
thanks

====================================
LibreNMS  | 1.36-74-g6887d77
DB Schema | 235
PHP       | 7.0.25-0ubuntu0.16.04.1
MySQL     | 10.0.33-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
