### ISSUE TITLE
Primary Key in ports_fdb missing

### ISSUE THREAD

**Issue by vivia11** [librenms/librenms#8266]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

====================================

Component | Version
--------- | -------
LibreNMS  | 1.36-75-g1c5b9d3
DB Schema | 236
PHP       | 7.2.2
MySQL     | 5.7.20-18-57-log
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Database connection successful
[OK]    Database schema correct
[FAIL]  The session directory (localhost:11211) is not writable.

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Hi all,
In the error logs, I'm getting the following error relating to ports_fdb:
**MySQL Error: Percona-XtraDB-Cluster prohibits use of DML command on a table (librenms.ports_fdb) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER (DELETE FROM `ports_fdb` WHERE `device_id` =  '77')**

However looking at past commits I see that with 196.sql, the table was created with a primary key but later dropped in 198.sql. I'm wondering what the reasoning for the removal of the primary key is and if it's possible to add that back in (in order to remove the aforementioned error from the logs).

**Comment by murrant** [comment]
I think there was concerns of overflowing the index, which seems ridiculous with bigint.
I think the index can be re-added.
