### ISSUE TITLE
Alert Templates lacking fine grain controls

### ISSUE THREAD

**Issue by vias79** [librenms/librenms#8291]
First off, love LibreNMS. Great project!

Lacking fine grain controls in Alert templates though. I don't want the kitchen sink in the messages, just the bare minimum for emails to a SMS system.

For instance:
This doesn't work (I only want the bill name, not all info in the faults array):
`
%name: {foreach %faults} {if %value.string == "bill_custid"} %value.string {/if} {/foreach} on %hostname {foreach %faults} {if %value.string == "ifDescr"} %value.string {/if} {/foreach}<br/>
Severity: %severity
Timestamp: %timestamp
`

Indexing it will not work either:
`
%name: %faults.1.bill_custid on %hostname %faults.1.value.ifDescr<br/>
Severity: %severity
Timestamp: %timestamp
`

With kitchen sink I mean this message:
`
Alert for device ume1.dr2.ag1-testswitch - CDR over quota Severity: critical Timestamp: 2018-02-23 21:41:00 Unique-ID: 7353 Rule: CDR over quota Faults: #1: sysObjectID => .1.3.6.1.4.1.25506.11.1.185; sysDescr => HPE Comware Platform Software, Software Version 7.1.045, Release 3115P06 HPE 5130 24G SFP 4SFP+ EI Switch Copyright (c) 2010-2016 Hewlett Packard Enterprise Development LP; bill_id => 3; bill_custid => Nashnet ; port_id => 39069; ifDescr => GigabitEthernet1/0/18; Alert sent to: bill
`

The message I want is:
Quota Exceeded for: Nashnet on ume1.dr2.ag1-testswitch GigabitEthernet1/0/18
Severity: Warning Timestamp: 2018-02-23 21:41:00

/V

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
