### ISSUE TITLE
add support --Fiberhome Router 8000&800

### ISSUE THREAD

**Issue by nwos-gh** [librenms/librenms#8297]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by nwos-gh** [comment]
CPU Usage(OCTET STRING):1.3.6.1.4.1.11408.11.1.1.1.1
Memory Usage(OCTET STRING):1.3.6.1.4.1.11408.11.1.1.1.2
Disk Usage(OCTET STRING):1.3.6.1.4.1.11408.11.1.1.1.11
Temperature(OCTET STRING):1.3.6.1.4.1.11408.11.1.1.1.13
Memory Total Size(OCTET STRING):1.3.6.1.4.1.11408.11.1.1.1.14
Disk Total Size(OCTET STRING):1.3.6.1.4.1.11408.11.1.1.1.15
Fan Status(OCTET STRING):1.3.6.1.4.1.11408.11.1.1.1.10
Fan Speed(OCTET STRING):1.3.6.1.4.1.11408.11.1.1.1.12
Power Status(OCTET STRING):1.3.6.1.4.1.11408.11.1.1.1.6
Power Voltage(OCTET STRING):1.3.6.1.4.1.11408.11.1.1.1.7
Current(OCTET STRING):1.3.6.1.4.1.11408.11.1.1.1.8
Power(OCTET STRING):1.3.6.1.4.1.11408.11.1.1.1.9
Sn Number(OCTET STRING):1.3.6.1.4.1.11408.11.1.1.1.16
OS&Version(OCTET STRING):1.3.6.1.4.1.11408.11.1.1.1.17
CPU Frequency(OCTET STRING):1.3.6.1.4.1.11408.11.1.1.1.18

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by nwos-gh** [comment]
Please help add the support of the above CPU and other content,Thanks!
The appendix is all private MIB library files of FiberHome Technologies.
[FIBERHOME-DATACOMM-MIB.zip](https://github.com/librenms/librenms/files/1773922/FIBERHOME-DATACOMM-MIB.zip)

**Comment by laf** [comment]
You've not provided any of the information from the links above even though you've ticked to say you have.
