### ISSUE TITLE
Email Transport Test Button gives no failure feedback

### ISSUE THREAD

**Issue by zatricky** [librenms/librenms#8298]
- [x] Is your install up to date? [Updating your install]
- [x] Please include all validation information
Given below
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
Relevance is limited. Can send if needed.
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 1.36-89-gf154846
DB Schema | 237
PHP       | 7.0.25-0ubuntu0.16.04.1
MySQL     | 10.0.33-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

At ${serveruri}/settings/sub=alerting/ with a working or non-working mail config, the [ Test transport ] button for Email transport turns green for a few seconds but nothing else. The button turns green regardless of whether or not the configuration is correct or the mail service is working, whereas other transports appear briefly to change their colour red if they are not configured.

See #1758 for related fixed/closed bug.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by zatricky** [comment]
It may be minor - but pretty sure this should be classed as a bug.
