### ISSUE TITLE
Tripp Lite PowerAlert Battery Voltage off by an order of magnitude

### ISSUE THREAD

**Issue by thanegill** [librenms/librenms#8306]
Just as with #5364 Battery Voltage on Tripplite UPS's is off by and order of magnitude 

![screen shot 2018-02-27 at 12 43 54 pm](https://user-images.githubusercontent.com/1141680/36753716-e56e66e8-1bbb-11e8-96a6-5dee0aafbf07.png)

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

```
====================================
Component | Version
--------- | -------
LibreNMS  | 1.37
DB Schema | 237
PHP       | 5.6.33-0+deb8u1
MySQL     | 10.0.32-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
====================================
```

./discovery.php -h 10.10.90.217 -d -m sensors: https://p.libren.ms/view/67a75a06

If more detail is needed let me know.

**Comment by laf** [comment]
You really should raise this to the vendor and tell them to sort this out. We're adding in specific hacks to work around them changing the values reported back between release. This is a standard RFC mib which dictates the values.

**Comment by thanegill** [comment]
When I read the [RFC](http://www.rfc-base.org/txt/rfc-1628.txt). I see the unit as `0.1 Volt DC` wouldn’t that mean that TrippLite is passing back to correct units?
