### ISSUE TITLE
ATS GUDE Device doesn't show green avilable icon on primary power only on secondry power 

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#8308]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` 
section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.37-13-g764abde50
DB Schema | 238
PHP       | 7.1.14
MySQL     | 5.6.39
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.3
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

.1.3.6.1.2.1.1.1.0 = STRING: Auto Transfer Switch
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.28507.4
.1.3.6.1.2.1.1.3.0 = Timeticks: (2788794004) 322 days, 18:39:00.04
.1.3.6.1.2.1.1.4.0 = STRING: 
.1.3.6.1.2.1.1.5.0 = STRING: 
.1.3.6.1.2.1.1.6.0 = STRING: 
.1.3.6.1.2.1.1.7.0 = INTEGER: 72
.1.3.6.1.2.1.2.1.0 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.2.1 = STRING: eth_cf52235
.1.3.6.1.2.1.2.2.1.3.1 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.4.1 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.5.1 = Gauge32: 10000000
.1.3.6.1.2.1.2.2.1.6.1 = STRING: 0:19:32:0:2f:64
.1.3.6.1.2.1.2.2.1.7.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.9.1 = Timeticks: (2788794004) 322 days, 18:39:00.04
.1.3.6.1.2.1.2.2.1.10.1 = Counter32: 2770224957
.1.3.6.1.2.1.2.2.1.11.1 = Counter32: 82357557
.1.3.6.1.2.1.2.2.1.12.1 = Counter32: 91718585
.1.3.6.1.2.1.2.2.1.13.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.1 = Counter32: 256
.1.3.6.1.2.1.2.2.1.15.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.16.1 = Counter32: 506393663
.1.3.6.1.2.1.2.2.1.17.1 = Counter32: 4640095
.1.3.6.1.2.1.2.2.1.18.1 = Counter32: 402500
.1.3.6.1.2.1.2.2.1.19.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.1 = Counter32: 4640095
.1.3.6.1.2.1.2.2.1.21.1 = Gauge32: 0
.1.3.6.1.2.1.2.2.1.22.1 = OID: .0.0
.1.3.6.1.4.1.28507.4.1.1.1.0 = INTEGER: 1
.1.3.6.1.4.1.28507.4.1.1.2.1.2.1 = IpAddress: 195.230.160.26
.1.3.6.1.4.1.28507.4.1.1.2.1.2.2 = IpAddress: 0.0.0.0
.1.3.6.1.4.1.28507.4.1.1.2.1.2.3 = IpAddress: 0.0.0.0
.1.3.6.1.4.1.28507.4.1.1.2.1.2.4 = IpAddress: 0.0.0.0
.1.3.6.1.4.1.28507.4.1.1.2.1.2.5 = IpAddress: 0.0.0.0
.1.3.6.1.4.1.28507.4.1.1.2.1.2.6 = IpAddress: 0.0.0.0
.1.3.6.1.4.1.28507.4.1.1.2.1.2.7 = IpAddress: 0.0.0.0
.1.3.6.1.4.1.28507.4.1.1.2.1.2.8 = IpAddress: 0.0.0.0
.1.3.6.1.4.1.28507.4.1.1.2.1.3.1 = INTEGER: 162
.1.3.6.1.4.1.28507.4.1.1.2.1.3.2 = INTEGER: 0
.1.3.6.1.4.1.28507.4.1.1.2.1.3.3 = INTEGER: 0
.1.3.6.1.4.1.28507.4.1.1.2.1.3.4 = INTEGER: 0
.1.3.6.1.4.1.28507.4.1.1.2.1.3.5 = INTEGER: 0
.1.3.6.1.4.1.28507.4.1.1.2.1.3.6 = INTEGER: 0
.1.3.6.1.4.1.28507.4.1.1.2.1.3.7 = INTEGER: 0
.1.3.6.1.4.1.28507.4.1.1.2.1.3.8 = INTEGER: 0
.1.3.6.1.4.1.28507.4.1.2.1.0 = INTEGER: 1200
.1.3.6.1.4.1.28507.4.1.3.0 = INTEGER: 1
.1.3.6.1.4.1.28507.4.1.4.0 = INTEGER: 1
.1.3.6.1.4.1.28507.4.1.5.0 = INTEGER: 0
.1.3.6.1.4.1.28507.4.1.6.0 = INTEGER: 1
.1.3.6.1.4.1.28507.4.1.4.0 = No more variables left in this MIB View (It is past the end of the MIB tree)
.1.3.6.1.4.1.28507.4.1.4.0 = No more variables left in this MIB View (It is past the end of the MIB tree)
.1.3.6.1.4.1.28507.4.1.4.0 = No more variables left in this MIB View (It is past the end of the MIB tree)
.1.3.6.1.4.1.28507.4.1.4.0 = No more variables left in this MIB View (It is past the end of the MIB tree)
.1.3.6.1.4.1.28507.4.1.4.0 = No more variables left in this MIB View (It is past the end of the MIB tree)
.1.3.6.1.4.1.28507.4.1.4.0 = No more variables left in this MIB View (It is past the end of the MIB tree)
.1.3.6.1.4.1.28507.4.1.4.0 = No more variables left in this MIB View (It is past the end of the MIB tree)
.1.3.6.1.4.1.28507.4.1.4.0 = No more variables left in this MIB View (It is past the end of the MIB tree)

- [ x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

The primary power shows not the green icon available it shows in red 1100#  !

Recent Events:
State sensor Primary power has changed from (1200) to (1100)

thanks
kristoferus75

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by kristoferus75** [comment]
Here the pastebin links:

https://pastebin.com/x3CDmnJe

https://pastebin.com/5c9NEMb5

https://pastebin.com/fg171q6c

**Comment by kristoferus75** [comment]
Hi !
I have now put all our deivices in the librenms  and it seems that there are three different  versions or firmware versions !

One Type of ATS : shows  under Primary  the current Ampere line 2100 in red instead of the icon

State Primary:ON
--
State Secondary:ON
Power Source:PRIMARY
Current Irms=2.1A 24h min=2A max=3A

and one type of ATS seems the old one shows it right with both right available icons  !

and the third type shows nothing :-(

I will paste the different snmp discovery and check if its possible to upgrade the versions !

kind regards 

kristoferus75

**Comment by kristoferus75** [comment]
Hi !

Here the mib file from the ATS which shows the red Ampere :

```
GUDEADS-ETS-MIB DEFINITIONS ::= BEGIN

IMPORTS
	enterprises,
	MODULE-IDENTITY,
	OBJECT-TYPE,
	NOTIFICATION-TYPE,
	Integer32,
	IpAddress
		FROM SNMPv2-SMI
	OBJECT-GROUP,
	NOTIFICATION-GROUP
		FROM SNMPv2-CONF;

gudeads MODULE-IDENTITY
	LAST-UPDATED "200705231244Z"	-- May 23, 2007 12:44:00 PM
	ORGANIZATION "Gude Analog- und Digitalsysteme GmbH"
	CONTACT-INFO
		"http://www.gudeads.com/"
	DESCRIPTION
		""
	REVISION "200705231244Z"	-- May 23, 2007 12:44:00 PM
	DESCRIPTION
		"Initial version."
	-- 1.3.6.1.4.1.28507
	::= { enterprises 28507 }



etsSecondaryPowerChangeEvt NOTIFICATION-TYPE
	OBJECTS {
		etsSecPowAvail}
	STATUS  current
	DESCRIPTION
		"Event is triggered when a secondary power
		changes"
	-- 1.3.6.1.4.1.28507.4.0.2
	::= { etsEvents 2 }

etsSNMPaccess OBJECT IDENTIFIER 
	-- 1.3.6.1.4.1.28507.4.1.1
	::= { etsObjects 1 }

etsTrapCtrl OBJECT-TYPE
	SYNTAX  Integer32 (0..2)
	MAX-ACCESS read-write
	STATUS  current
	DESCRIPTION
		"0 = off
		1 = Ver. 1
		2 = Ver. 2c"
	-- 1.3.6.1.4.1.28507.4.1.1.1
	::= { etsSNMPaccess 1 }


etsTrapIPTable OBJECT-TYPE
	SYNTAX  SEQUENCE OF EtsTrapIPEntry
	MAX-ACCESS not-accessible
	STATUS  current
	DESCRIPTION
		"list of all Trap receiver"
	-- 1.3.6.1.4.1.28507.4.1.1.2
	::= { etsSNMPaccess 2 }


etsTrapIPEntry OBJECT-TYPE
	SYNTAX  EtsTrapIPEntry
	MAX-ACCESS not-accessible
	STATUS  current
	DESCRIPTION
		"an entry containing management
		informations regarding the list of trap
		receivers"
	INDEX {
		etsTrapIPIndex }
	-- 1.3.6.1.4.1.28507.4.1.1.2.1
	::= { etsTrapIPTable 1 }


EtsTrapIPEntry ::= SEQUENCE {

	etsTrapIPIndex Integer32,
	etsTrapIPAddr  IpAddress,
	etsTrapIPPort  Integer32 }


etsTrapIPIndex OBJECT-TYPE
	SYNTAX  Integer32 (1..8)
	MAX-ACCESS not-accessible
	STATUS  current
	DESCRIPTION
		"A unique value, greater than zero, for each receiver slot."
	-- 1.3.6.1.4.1.28507.4.1.1.2.1.1
	::= { etsTrapIPEntry 1 }


etsTrapIPPort OBJECT-TYPE
	SYNTAX  Integer32 (0..1024)
	MAX-ACCESS read-write
	STATUS  current
	DESCRIPTION
		"IP Port specifying one Trap receiver slot.
		A value of  0 disables this slot."
	DEFVAL { 162 }
	-- 1.3.6.1.4.1.28507.4.1.1.2.1.3
	::= { etsTrapIPEntry 3 }


etsTrapIPAddr OBJECT-TYPE
	SYNTAX  IpAddress
	MAX-ACCESS read-write
	STATUS  current
	DESCRIPTION
		"IP Address specifying one Trap receiver slot.
		A value of '00000000'H disables this slot."
	DEFVAL { '00000000'H }
	-- 1.3.6.1.4.1.28507.4.1.1.2.1.2
	::= { etsTrapIPEntry 2 }


gadsETS OBJECT IDENTIFIER 
	-- 1.3.6.1.4.1.28507.4
	::= { gudeads 4 }

-- Scalars and Tables
--

etsObjects OBJECT IDENTIFIER 
	-- 1.3.6.1.4.1.28507.4.1
	::= { gadsETS 1 }

-- Notification Types
--

etsEvents OBJECT IDENTIFIER 
	-- 1.3.6.1.4.1.28507.4.0
	::= { gadsETS 0 }

etsSensors OBJECT IDENTIFIER 
	-- 1.3.6.1.4.1.28507.4.1.2
	::= { etsObjects 2 }

etsIrms OBJECT-TYPE
	SYNTAX  Integer32
	UNITS
		"mA"
	MAX-ACCESS read-only
	STATUS  current
	DESCRIPTION
		"actual rms Current, a value of -9999 indicates
		that data is not available"
	-- 1.3.6.1.4.1.28507.4.1.2.1
	::= { etsSensors 1 }


etsPowerSelect OBJECT-TYPE
	SYNTAX  Integer32
	MAX-ACCESS read-only
	STATUS  current
	DESCRIPTION
		"if 1, power is primary
		if 2, power is secondary"
	-- 1.3.6.1.4.1.28507.4.1.6
	::= { etsObjects 6 }



etsPrimaryPowerChangeEvt NOTIFICATION-TYPE
	OBJECTS {
		etsPrimPowAvail}
	STATUS  current
	DESCRIPTION
		"Event is triggered when a primary power
		changes"
	-- 1.3.6.1.4.1.28507.4.0.1
	::= { etsEvents 1 }

etsPrimPowAvail OBJECT-TYPE
	SYNTAX  Integer32
	MAX-ACCESS read-only
	STATUS  current
	DESCRIPTION
		"not zero if primary Power available"
	-- 1.3.6.1.4.1.28507.4.1.3
	::= { etsObjects 3 }


etsSecPowAvail OBJECT-TYPE
	SYNTAX  Integer32
	MAX-ACCESS read-only
	STATUS  current
	DESCRIPTION
		"not zero if secondary Power available"
	-- 1.3.6.1.4.1.28507.4.1.4
	::= { etsObjects 4 }


etsSecManualSelect OBJECT-TYPE
	SYNTAX  Integer32
	MAX-ACCESS read-only
	STATUS  current
	DESCRIPTION
		"not zero if secondary Power is manually selected"
	-- 1.3.6.1.4.1.28507.4.1.5
	::= { etsObjects 5 }


-- Conformance
--

etsConf OBJECT IDENTIFIER 
	-- 1.3.6.1.4.1.28507.4.3
	::= { gadsETS 3 }

-- Groups
--

etsGroups OBJECT IDENTIFIER 
	-- 1.3.6.1.4.1.28507.4.3.1
	::= { etsConf 1 }

-- Compliance
--

etsCompls OBJECT IDENTIFIER 
	-- 1.3.6.1.4.1.28507.4.3.2
	::= { etsConf 2 }


etsManualSelectEvt NOTIFICATION-TYPE
	OBJECTS {
		etsSecManualSelect}
	STATUS  current
	DESCRIPTION
		"triggered when secondary power is manually
		selected"
	-- 1.3.6.1.4.1.28507.4.0.3
	::= { etsEvents 3 }


etsPowerSelectEvt NOTIFICATION-TYPE
	OBJECTS {
		etsPowerSelect}
	STATUS  current
	DESCRIPTION
		"Event is triggered when power changes
		between primary and secondary"
	-- 1.3.6.1.4.1.28507.4.0.4
	::= { etsEvents 4 }

etsBasicGroup OBJECT-GROUP
	OBJECTS {
		etsPrimPowAvail,
		etsSecPowAvail,
		etsSecManualSelect,
		etsPowerSelect,
		etsTrapCtrl,
		etsTrapIPAddr,
		etsTrapIPPort,
		etsIrms }
	STATUS  current
	DESCRIPTION
		"Basic objects."
	-- 1.3.6.1.4.1.28507.4.3.1.1
	::= { etsGroups 1 }

etsNotificationGroup NOTIFICATION-GROUP
	NOTIFICATIONS {
		etsPrimaryPowerChangeEvt,
		etsSecondaryPowerChangeEvt,
		etsManualSelectEvt,
		etsPowerSelectEvt }
	STATUS  current
	DESCRIPTION
		""
	-- 1.3.6.1.4.1.28507.4.3.1.2
	::= { etsGroups 2 }

END
```

**Comment by kristoferus75** [comment]
Hi !

Her
