### ISSUE TITLE
Need to add divisor: and skip_values: to ees.yaml

### ISSUE THREAD

**Issue by charris54** [librenms/librenms#8323]
Emerson mib EES-POWER-MIB.

DESCRIPTION
            "The first route temperature, stored as 0.001 Celsius degree.
                The integer 2147483647 represents invalid value."

includes/definitions/discovery/ees.yaml
mib: EES-POWER-MIB
modules:
    sensors:
        temperature:
            data:
                -
                    oid: psTemperatureTable
                    num_oid: .1.3.6.1.4.1.6302.2.1.2.7.3.1.2.
                    value: psTemperatureMeasurement
                    divisor: 1000
                    skip_values: 2147483647
                    index: 'psTemperatureMeasurement.{{ $index }}'
                    descr: psTemperatureName
                    skip_value_lt: 0

Component | Version
--------- | -------
LibreNMS  | 1.37-19-g7b6e4f9
DB Schema | 238
PHP       | 7.1.11
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Please just submit this as a pull request, you've already made the changes needed.
