### ISSUE TITLE
Version check does not match compose version output

### ISSUE THREAD

**Issue by dchidell** [librenms/librenms#8324]
Performing new install according to ubuntu 16.04 guide. Validation check against compose fails.

```
librenms@librenms:~$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.37-20-g84b0b32
DB Schema | ?
PHP       | 7.0.25-0ubuntu0.16.04.1
MySQL     | ?
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

[FAIL]  No composer available, please install composer
        [FIX] https://getcomposer.org/
librenms@librenms:~$
```

Compose IS installed. When running version check gives output as below:

```
root@librenms:/opt/librenms# php /opt/librenms/scripts/composer_wrapper.php --version
Composer version @package_branch_alias_version@ (1.0.0-beta2) 2016-03-27 16:00:34
root@librenms:/opt/librenms#
```

This does NOT match the regex found within the Dependencies.php file **LibreNMS/Validations/Dependencies.php**

`preg_match('/Composer (version )?([.0-9]+)/', $composer_output, $matches);`

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This is already known. However your version is ridiculously out of date so remove it and let validate install the correct version

**Comment by dchidell** [comment]
I had followed the guide exactly as well. From what I can tell the composer version which is installed by the apt repo is outdated and results in this error.

In order to resolve this, I did the following (Note: This has been taken from the composer installation documentation, but the install directory and filename has been changed from the default to allow compatibility):

```
apt remove composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php --install-dir=/usr/bin --filename=composer'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
```

This then becomes a documentation issue since the documentation points to installing composer from apt.
