### ISSUE TITLE
Validate shows "The poller (librenms) has not completed within the last 5 minutes", but the poll log is showing fine

### ISSUE THREAD

**Issue by kennethcmc** [librenms/librenms#8325]
[root@LibreNMS-NSVMFarm librenms]# ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.37-20-g84b0b32
DB Schema | 239
PHP       | 7.0.9
MySQL     | 5.5.47-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Composer Version: 1.6.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[FAIL]  The poller (librenms) has not completed within the last 5 minutes, check the cron job.
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.

 
![image](https://user-images.githubusercontent.com/37057173/36956347-dc603584-2068-11e8-9880-2082604be5a8.png)

Find that the librenms is polling the device normally with the correct graphy, however, the validate.php is still showing the error "The poller (librenms) has not completed within the last 5 minutes, check the cron job."

Related librenms.log
/opt/librenms/discovery.php new 2018-03-05 11:20:01 - 0 devices discovered in 0.005 secs
/opt/librenms/poller.php 13 2018-03-05 11:20:04 - 1 devices polled in 3.070 secs
/opt/librenms/poller.php 1 2018-03-05 11:20:05 - 1 devices polled in 3.385 secs
/opt/librenms/poller.php 8 2018-03-05 11:20:06 - 1 devices polled in 4.710 secs
/opt/librenms/poller.php 11 2018-03-05 11:20:06 - 1 devices polled in 5.090 secs
/opt/librenms/poller.php 9 2018-03-05 11:20:07 - 1 devices polled in 5.519 secs
/opt/librenms/poller.php 2 2018-03-05 11:20:07 - 1 devices polled in 5.467 secs
/opt/librenms/poller.php 7 2018-03-05 11:20:07 - 1 devices polled in 5.402 secs
/opt/librenms/poller.php 10 2018-03-05 11:20:07 - 1 devices polled in 5.417 secs
/opt/librenms/poller.php 6 2018-03-05 11:20:07 - 1 devices polled in 5.559 secs
/opt/librenms/poller.php 12 2018-03-05 11:20:07 - 1 devices polled in 5.830 secs
/opt/librenms/poller.php 3 2018-03-05 11:20:07 - 1 devices polled in 6.154 secs
/opt/librenms/discovery.php new 2018-03-05 11:25:01 - 0 devices discovered in 0.034 secs
/opt/librenms/poller.php 13 2018-03-05 11:25:04 - 1 devices polled in 3.051 secs
/opt/librenms/poller.php 1 2018-03-05 11:25:05 - 1 devices polled in 3.187 secs
/opt/librenms/poller.php 10 2018-03-05 11:25:05 - 1 devices polled in 3.935 secs
/opt/librenms/poller.php 7 2018-03-05 11:25:06 - 1 devices polled in 5.015 secs
/opt/librenms/poller.php 12 2018-03-05 11:25:06 - 1 devices polled in 5.481 secs
/opt/librenms/poller.php 6 2018-03-05 11:25:07 - 1 devices polled in 5.424 secs
/opt/librenms/poller.php 8 2018-03-05 11:25:07 - 1 devices polled in 5.417 secs
/opt/librenms/poller.php 2 2018-03-05 11:25:07 - 1 devices polled in 5.481 secs
/opt/librenms/poller.php 11 2018-03-05 11:25:07 - 1 devices polled in 5.496 secs
/opt/librenms/poller.php 9 2018-03-05 11:25:07 - 1 devices polled in 5.655 secs
/opt/librenms/poller.php 3 2018-03-05 11:25:07 - 1 devices polled in 6.330 secs
/opt/librenms/discovery.php new 2018-03-05 11:30:01 - 0 devices discovered in 0.000 secs
/opt/librenms/poller.php 13 2018-03-05 11:30:04 - 1 devices polled in 3.094 secs
/opt/librenms/poller.php 1 2018-03-05 11:30:05 - 1 devices polled in 3.342 secs
/opt/librenms/poller.php 6 2018-03-05 11:30:06 - 1 devices polled in 4.678 secs
/opt/librenms/poller.php 8 2018-03-05 11:30:06 - 1 devices polled in 5.114 secs
/opt/librenms/poller.php 12 2018-03-05 11:30:06 - 1 devices polled in 5.208 secs
/opt/librenms/poller.php 7 2018-03-05 11:30:06 - 1 devices polled in 5.176 secs
/opt/librenms/poller.php 2 2018-03-05 11:30:07 - 1 devices polled in 5.413 secs
/opt/librenms/poller.php 10 2018-03-05 11:30:07 - 1 devices polled in 5.369 secs
/opt/librenms/poller.php 11 2018-03-05 11:30:07 - 1 devices polled in 5.592 secs
/opt/librenms/poller.php 9 2018-03-05 11:30:07 - 1 devices polled in 5.595 secs
/opt/librenms/poller.php 3 2018-03-05 11:30:07 - 1 devices polled in 6.237 secs

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
