### ISSUE TITLE
ipv4 Addresses stays in ipv4_address Table

### ISSUE THREAD

**Issue by rebortg** [librenms/librenms#8326]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the Component | Version
--------- | -------
LibreNMS  | 1.37-20-g84b0b32
DB Schema | 239
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.33-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [-] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- i had a device it holds many ipv4addresses as a router. I delete this device on Friday. Today i want to add new devices, but the ip adresses are still blocked.
- Add Device says:
- Already have host with this IP 1.1.1.1
in global Search and ipv4/v6 Search, i can not find this IP Address.
- mysqldump -u librenms -p --database librenms | grep 1.1.1.1
give me entrys in tables:
ipv4_addresses
ipv4_mac
ipv4_networks

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
