### ISSUE TITLE
RoomAlert 32E external humidity sensors

### ISSUE THREAD

**Issue by Sopsy** [librenms/librenms#8328]
External humidity sensors of Avtech RoomAlert 32E are not detected because they are not defined in the yaml file.

I understand that this same OID might contain some other information as well (eg. power status for power sensors), but it would be useful to at least show them as humidity instead of not showing them at all. If this is the reason for not supporting the humidity sensors, you can close this issue, but I do hope for a fix to this so daily.sh would not freak out due to local changes.

These two patches add support for external humidity sensors. I have been running these on my installation without a problem.

```
--- avtech.inc.php      2018-03-05 17:43:07.283038084 +0100
+++ /opt/librenms/includes/discovery/sensors/pre-cache/avtech.inc.php   2018-03-05 17:35:34.680776493 +0100
@@ -29,6 +29,7 @@
     'ra32-analog' => '/\.1\.3\.6\.1\.4\.1\.20916\.1\.8\.1\.1\.5\.((\d+)\.0)/',
     'ra32-relay' => '/\.1\.3\.6\.1\.4\.1\.20916\.1\.8\.1\.1\.6\.((\d+)\.0)/',
     'ra32-ext-temp' => '/\.1\.3\.6\.1\.4\.1\.20916\.1\.8\.1\.2\.((\d+)\.1\.0)/',
+    'ra32-ext-humidity' => '/\.1\.3\.6\.1\.4\.1\.20916\.1\.8\.1\.2\.((\d+)\.3\.0)/',
     'ra32-switch' => '/\.1\.3\.6\.1\.4\.1\.20916\.1\.8\.1\.3\.((\d+)\.0)/',
     'ra32-wish-temp' => '/\.1\.3\.6\.1\.4\.1\.20916\.1\.8\.1\.4\.((\d+)\.4\.1\.2\.0)/',
 );
```

```
--- avtech.yaml 2018-03-05 17:43:30.770741976 +0100
+++ /opt/librenms/includes/definitions/discovery/avtech.yaml    2018-03-05 17:36:51.875793246 +0100
@@ -128,6 +128,11 @@
                 num_oid: .1.3.6.1.4.1.20916.1.8.1.1.2.1.
                 index: 0
                 descr: Internal Humidity
+              - # RoomAlert 32E/W ext humidity
+                oid: ra32-ext-humidity
+                num_oid: .1.3.6.1.4.1.20916.1.8.1.2.
+                value: value
+                descr: Sensor {{ $id }}
         voltage:
             data:
               - # RoomAlert 32E/W analog
```

```
Component | Version
--------- | -------
LibreNMS  | 1.37-21-g6c3473a
DB Schema | 239
PHP       | 7.0.25-0ubuntu0.16.04.1
MySQL     | 5.7.21-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
```

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
@Sopsy Hi, I suggest you send these changes as a Pull Request so we can merge them in.
https://docs.librenms.org/#Developing/Using-Git/  or you can use the github webui.

**Comment by tssge** [comment]
@murrant there is a problem though. The OID is the same regardless what sensor is installed to that port. So the OID is based on the port number rather than the type of sensor attached.

If a RoomAlert user attaches say a voltage sensor to the said port, well, it will be shown under humidity and so on.

We don't know how to solve this. If you have any ideas how to solve that properly, we can do the proper patch.

**Comment by murrant** [comment]
Probably this is what you are looking for: #7925

**Comment by laf** [comment]
If we have no way of distinguishing between what the sensor is then we can't add native support I'm afraid.

**Comment by Sopsy** [comment]
Yeah, the issue is that there's three types of sensors that report values on the same OID. There's the most popular temp/humidity sensors, then there's temp/active voltage and temp/analog (volts) sensor. And I believe there's no OID that tells which sensor is attached. The sensor type needs to be selected from the RA32E configuration, but it does not affect SNMP in any way. This is also the reason I sent this in as an issue instead of a pull request, as I'm not sure if you'd like to merge this or not.

This is the OID description from the MIB:
"If this sensor is a Temp/Humidity sensor, this value represents the current relative humidity in % Relative Humidity. If this sensor is a Temp/Analog sensor, this value represents the current Voltage reading. If this is a Temp/Active Power sensor, this value represents the current power state (1=Power Detected, 0=No Power Detected)."

I'd say this is bad SNMP configuration from AVTECH. Even a OID telling the sensor type would be enough to distinguish between them...

**Comment by murrant** [comment]
@Sopsy the other option is to bug the vendor to provide a more sane snmp implementation.
They should be using a table: http://net-snmp.sourceforge.net/docs/mibs/NET-SNMP-EXAMPLES-MIB.txt
