### ISSUE TITLE
Dell EMC switches not being detected as DNOS

### ISSUE THREAD

**Issue by kslawrence** [librenms/librenms#8338]
Just added 2x Dell S4128F-ON switches to our inventory and they were detected as generic devices. This meant that oxidized would also not pull configs due to the OS not being set to dnos.

I was able to fix this by changing includes/definitions/dnos.yaml to include the following:

discovery:
    -
        sysObjectID:
            - .1.3.6.1.4.1.6027.1.
         **- .1.3.6.1.4.1.674.11000.5000.100.2.1.7**

This worked fine in my case and the switch OS was correctly detected. I have a feeling the sysObjectID i added may be too specific but I only have these two dnos devices and wasnt sure how much to trim off the end.

Could this be added to the master dnos.yaml file so this will be a permanent change?

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by kkrumm1** [comment]
@kslawrence make PR. Looks like you already have the fix? :)
