### ISSUE TITLE
SNMP community string 'Link$ysRO' saved as 'Link'

### ISSUE THREAD

**Issue by imcdona** [librenms/librenms#8342]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

``
====================================
Component | Version
--------- | -------
LibreNMS  | 1.37-21-g6c3473a
DB Schema | 239
PHP       | 7.0.27
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
``

- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Adding Link$ysRO to the list of SNMP community strings in config.php results in community string being read as 'Link'.

**Steps to reproduce:**

**1.** Add **Link$ysRO** to the list of community strings in config.php
**2.** Navigate to https://librenms.install.tld/settings/
**3.** Note that 'Link$ysRO' displays as '**Link**' in the SNMP communities

**Comment by laf** [comment]
Escape `\$` or wrap it in single quotes.

This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by imcdona** [comment]
If you require a single quote then use single quotes on the included SNMP community strings.

The example provided in the config.php is this:

`$config['snmp']['community']` = `array("public");`

Change the example to this instead:

`'$config['snmp']['community']` = array('public');``
