### ISSUE TITLE
Escaping error - Apostrophe / single-quote in Sysname breaks Worldmap with force_ip_to_sysname set

### ISSUE THREAD

**Issue by cbgsy** [librenms/librenms#8346]
Scenario: A device configured with an apostrophe in SNMP Sysname parameter (in my case a Ubiquiti Airos device), with valid location / GPS coords set is added to LibreNMS configured with force_ip_to_sysname set.  Worldmap geo display on dashboard subsequently appears entirely blank.

Suspect that name is not fully escaped for special characters before passing out to Worldmap data, so suggest changing this, or to parse / remove special characters when Sysname is initially detected / stored (but that may break other parts of course).

Sysname / Hostname should of course be properly formed / defined on devices ideally, but equally, LibreNMS should be able to gracefully handle those cases where it is not outside of a FQDN setup - especially where the configuration of a single rogue device can effectively break the dashboard.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
I've tested this with a `'` in the sysName for a device with  `force_ip_to_sysname` set to true and it works.

You will need to provide an example string which allows us to reproduce this issue.
