### ISSUE TITLE
Support for new device: VIPTELA

### ISSUE THREAD

**Issue by thejimmahknows** [librenms/librenms#8354]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
====================================
Component | Version
--------- | -------
LibreNMS  | 1.37-27-ga0c2783d2
DB Schema | 240
PHP       | 5.6.33-0+deb8u1
MySQL     | 10.1.26-MariaDB-0+deb9u1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.6.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/0d301940
https://p.libren.ms/view/579d8eb4
Standard snmpbulkwalk was not picking up the private OID so I ran it against ( 1.3.6.1.4.1.41916) however pastbin is limited and I can't upload the walk. 
https://gist.github.com/thejimmahknows/d807aa9000e7fb0a9186532c84eeb09f
https://gist.github.com/thejimmahknows/7f5e1909ade8fb0fe010d89258f8a026
There is also a PDF with the MIBs, https://drive.google.com/open?id=1h6v54Dvas-wRu6zCD2Hcb4RaTeqLmO3I

- [x] Please provide as much detail as possible.
Looking to see if Cisco VIPTELA device support could be added to LibreNMS
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
1.3.6.1.4.1.41916 is not enough. We need from  `.1.3.6.1.` to be able to do detection. Let us know when you've got this and uploaded it then we can re-open this.

**Comment by thejimmahknows** [comment]
I believe I got the .1.3.6.1 snmpwalk now.
https://gist.github.com/thejimmahknows/7f5e1909ade8fb0fe010d89258f8a026

**Comment by neokjames** [comment]
I can help with getting this sorted

so far I have working
- Software version (i.e. 17.2.3)
- Hardware/Platform (i.e. vEdge-1000 / vManage NMS)
- Memory usage
- Serial number
- Interface statistics

what I can't get working is CPU as there's no OID for just "CPU utilization %"

MIB entries relating to CPU are:
.iso.org.dod.internet.private.enterprises.viptela.viptela-oper-system.systemStatus.systemStatusCpuUser
.iso.org.dod.internet.private.enterprises.viptela.viptela-oper-system.systemStatus.systemStatusCpuSystem
.iso.org.dod.internet.private.enterprises.viptela.viptela-oper-system.systemStatus.systemStatusCpuIdle

and possibly these for Load Average:
.iso.org.dod.internet.private.enterprises.viptela.viptela-oper-system.systemStatus.systemStatusMin1Avg
.iso.org.dod.internet.private.enterprises.viptela.viptela-oper-system.systemStatus.systemStatusMin5Avg
.iso.org.dod.internet.private.enterprises.viptela.viptela-oper-system.systemStatus.systemStatusMin15Avg

**Comment by neokjames** [comment]
Here's the memory discovery gists:
Polling- includes/polling/mempools/viptela.inc.php
https://gist.github.com/neokjames/9f7ed9dfe00d641e41bb947eefbbdb6b

Discovery- includes/discovery/mempools/viptela.inc.php
https://gist.github.com/neokjames/0cfbfa7f0e14c46e0e03fc239b3e8124

**Comment by neokjames** [comment]
Here's the serial/hardware/version- includes/polling/os/viptela.inc.php
https://gist.github.com/neokjames/0deee9ec184c2b38fc4b040234a81268

**Comment by laf** [comment]
@neokjames It would be ace if you can submit this as a pull request.

**Comment by Rosiak** [comment]
Any update on this?

**Comment by thejimmahknows** [comment]
I am curious as well? Are we able to pull route information or VRRP information from the snmpbulkwalk?

**Comment by PipoCanaja** [comment]
@arnabdutta @thejimmahknows  We don't have the mib files for this device family. If you can add it to current issue, we'll extend support. For now, only serial number and device model will be added. 

@neokjames Thanx for your code snippets. The serial and device model collection will be soon merged. If you have the mib files, please add them here.
