### ISSUE TITLE
New OS: OccamOS System V6.2R4 for BLC 6252 02

### ISSUE THREAD

**Issue by MHammett** [librenms/librenms#8361]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

====================================
Component | Version
--------- | -------
LibreNMS  | 1.37-30-ge3d44c54d
DB Schema | 240
PHP       | 7.0.19-1
MySQL     | 10.1.26-MariaDB-0+deb9u1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
====================================

- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

Bad Link.

- [ ] Please provide as much detail as possible.

https://p.libren.ms/view/af73f654
https://p.libren.ms/view/1be26e09
https://p.libren.ms/view/a4992c2c

I had to limit snmpwalk to .1.3. It would return an error for anything less. (.0.1 = No Such Object available on this agent at this OID). Regardless of how much less you entered, that's what the device returned.

- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by MHammett** [comment]
I've added some pastebins from a related major version.

https://p.libren.ms/view/8e108b86
https://p.libren.ms/view/6de77b29
https://p.libren.ms/view/1611f19e

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11666

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-os-occamos-system-v6-2r4-for-blc-6252-02/11666/1
