### ISSUE TITLE
 new device: VMware-vCenter-Server-Appliance

### ISSUE THREAD

**Issue by rbax82** [librenms/librenms#8374]
I was hoping you could add stats for VMs. As far as I can tell it can pull the same information as what is retrieved from an ESXi host.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
====================================
Component | Version
--------- | -------
LibreNMS  | 1.37-29-gbbd16dd
DB Schema | 240
PHP       | 7.0.25-0ubuntu0.16.04.1
MySQL     | 10.0.34-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/f6194aaf
https://p.libren.ms/view/06d18f62
https://p.libren.ms/view/7849f64b
- [x ] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by rbax82** [comment]
I was only asking if the same MIB that is used to poll ESXi servers also be applied to the VCSA template
