### ISSUE TITLE
ports: New ADSL ports impossible

### ISSUE THREAD

**Issue by tracernz** [librenms/librenms#8382]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

-------------------------------------------------------------------------

[The ADSL-LINE-MIB information is only polled if there exists at least one port in the `ports` table with `ifType=adsl`](https://github.com/librenms/librenms/blob/b5273969a07cdc5be770a069ab36c6548363bc49/includes/polling/ports.inc.php#L242-L246). I cannot find any code that sets `ifType=adsl`, and there isn't any ADSL code in discovery. The ADSL port information is actually stored in the `ports_adsl` table anyway!

I changed the line:
`if ($device['adsl_count'] > '0') {`
to always be true:
`if (1 || $device['adsl_count'] > '0') {`
and sure enough now ADSL line information appears on the ADSL port of my modem (and nowhere else).
```
MariaDB [librenms]> select * from `ports_adsl`;
+---------+---------------------+----------------+-----------------+---------------------+--------------------------+--------------------+-----------------+-----------------------+----------------------------+------------------------+-------------------------+---------------------+--------------------------+------------------------+--------------------+-----------------+-----------------------+----------------------------+
| port_id | port_adsl_updated   | adslLineCoding | adslLineType    | adslAtucInvVendorID | adslAtucInvVersionNumber | adslAtucCurrSnrMgn | adslAtucCurrAtn | adslAtucCurrOutputPwr | adslAtucCurrAttainableRate | adslAtucChanCurrTxRate | adslAturInvSerialNumber | adslAturInvVendorID | adslAturInvVersionNumber | adslAturChanCurrTxRate | adslAturCurrSnrMgn | adslAturCurrAtn | adslAturCurrOutputPwr | adslAturCurrAttainableRate |
+---------+---------------------+----------------+-----------------+---------------------+--------------------------+--------------------+-----------------+-----------------------+----------------------------+------------------------+-------------------------+---------------------+--------------------------+------------------------+--------------------+-----------------+-----------------------+----------------------------+
|      31 | 2018-03-15 20:30:12 | dmt            | interleavedOnly |                     |                          |                0.0 |             0.0 |                   0.0 |                          0 |               88602000 | ........                | DRAYTEK.            | ........                 |               35857000 |                0.5 |             1.6 |                   1.4 |                   88480328 |
+---------+---------------------+----------------+-----------------+---------------------+--------------------------+--------------------+-----------------+-----------------------+----------------------------+------------------------+-------------------------+---------------------+--------------------------+------------------------+--------------------+-----------------+-----------------------+----------------------------+
```

What's the best way to fix? Best I can see is just always try to walk the MIB? Maybe that should be done in discovery instead, and the poller condition fixed to look at `ports_adsl` table?
[The code to fetch data consists of a large number of snmp walk calls](https://github.com/librenms/librenms/blob/b5273969a07cdc5be770a069ab36c6548363bc49/includes/polling/ports.inc.php#L248-L267). Would it be faster to walk the whole MIB tree once and get some extra data that's discarded? I'll be happy to include some test data with the fix.

**Comment by laf** [comment]
I suggest you submit a pull request or open a discussion on the community forum.
