### ISSUE TITLE
Services: Adding one via the API doesn't make it show up in the web interface

### ISSUE THREAD

**Issue by Tawmu** [librenms/librenms#8386]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

```
====================================
Component | Version
--------- | -------
LibreNMS  | 1.37-50-g0491e2e
DB Schema | 244
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.2.12-MariaDB-10.2.12+maria~xenial
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================
```
_____

When adding a new Service via the API (using an IP address, the API forces that but the web interface allows a hostname) it never shows up in the web interface under the server it is assigned to.

It looks as if the API is not putting any id in the device_id column of the Services database table and it is defaulting to 0.

```
"content": "{\n    \"status\": \"ok\",\n    \"message\": \"Service ssh has been added to device :HOSTNAME.fqdn.domain (#15)\"\n}", "content_length": "113", "content_type": "application/json", "cookies": {}, "date": "Thu, 15 Mar 2018 10:48:35 GMT", "json": {"message": "Service ssh has been added to device :HOSTNAME.fqdn.domain (#15)", "status": "ok"}"
```

The host is HOSTNAME.fqdn.domain with device id 22.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
