### ISSUE TITLE
Incorrect discovery|poller on Huawei VRP

### ISSUE THREAD

**Issue by Murz78** [librenms/librenms#8387]
Hi everyone!

There is a problem with Huawei L2 device. 
Does not define a platform, plus does not show neighboring switches.

![image](https://user-images.githubusercontent.com/32451287/37463756-4cbb5b64-2867-11e8-80ca-ff5e37eced4d.png)

Kindly regards

[discovery.txt](https://github.com/librenms/librenms/files/1815346/discovery.txt)
[poller.txt](https://github.com/librenms/librenms/files/1815347/poller.txt)
[SNMP.txt](https://github.com/librenms/librenms/files/1815348/SNMP.txt)

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.
