### ISSUE TITLE
GEIST Watchdog 15 - Cannot discover External Sensors

### ISSUE THREAD

**Issue by diegonix** [librenms/librenms#8393]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

---
The discovery of the GEIST Watchdog 15 (GBB15) FW 3.3.3 is detecting only the internal temperature and humidity sensors. The external sensors is not being detected. This Device has 3 additional temperature sensors.

Device Name: Watchdog 15
Version: 3.3.3

Discover:
https://p.libren.ms/view/d9357d6b

Poller:
https://p.libren.ms/view/028fd34a

snmp:
https://p.libren.ms/view/86a18d82

---
LibreNMS
Version       | 1.37-20-g84b0b32 - Sat Mar 03 2018 19:47:49 GMT-0300
DB Schema | #239
Web Server | nginx/1.10.3
PHP             | 7.0.22-0ubuntu0.16.04.1
MySQL        | 10.0.34-MariaDB-0ubuntu0.16.04.1
RRDtool      | 1.5.5

**Comment by kkrumm1** [comment]
are you running the newest watchdog os? I remember there was a bug in the old firmware.

**Comment by diegonix** [comment]
Yes, I'm running the latest one, Ver. 3.3.3

**Comment by Sacmanxman2** [comment]
+1, as we have a watchdog 100 that has 4 external sensors which are not being discovered either. I'd be happy to provide MIBs and what not, and I know the snmpwalk commands to access those properties.

**Comment by PipoCanaja** [comment]
@diegonix @Sacmanxman2 
The data for this issue are not available anymore. Please post them if the issue is still there. And we'll reopen. 
Bye

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/geist-watchdog-external-sensor-discovery-not-working/11608/1
