### ISSUE TITLE
Support for new device: ECS4610

### ISSUE THREAD

**Issue by diegonix** [librenms/librenms#8394]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

---
LibreNMS already support few families of Edge-Core switches, however ECS4610 Series is not on list yet.

Discover:
https://p.libren.ms/view/37631e23

Poller:
https://p.libren.ms/view/66eeaf87

snmp:
https://p.libren.ms/view/f8ce343e

---
LibreNMS
Version | 1.37-20-g84b0b32 - Sat Mar 03 2018 19:47:49 GMT-0300
DB Schema | #239
Web Server | nginx/1.10.3
PHP | 7.0.22-0ubuntu0.16.04.1
MySQL | 10.0.34-MariaDB-0ubuntu0.16.04.1
RRDtool | 1.5.5

**Comment by spencerbutler** [comment]
These links are all 404's.

**Comment by PipoCanaja** [comment]
Links are dead, so closing this issue. Feel free to reopen and provide fresh data.
