### ISSUE TITLE
Better support for SIAE ALFOplus2

### ISSUE THREAD

**Issue by jozefrebjak** [librenms/librenms#8400]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Please add better support for SIAE ALFOplus2 radio.

Here is captured discovery:
https://p.libren.ms/view/36389b69

Here pooler:
https://p.libren.ms/view/c2ce26ab

Here snmpwalk:
https://p.libren.ms/view/ed912226

Thank you.

Component | Version
LibreNMS  | 1.37-57-g69bedd0
DB Schema | 245
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.34-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

**Comment by laf** [comment]
Thanks for the info but what does better support even mean? Please be specific.

**Comment by jozefrebjak** [comment]
I mean for example, logo of the siae will be good, but I mostly want a Tx, Rx and basically this information from the picture, when it is possible to get. 

![siae](https://user-images.githubusercontent.com/36922215/37512969-d7e99ee8-2903-11e8-9119-2a24d53aeb1f.png)

**Comment by laf** [comment]
Please see if #8953 adds what you want.

**Comment by jozefrebjak** [comment]
@laf. I think that yes. I will look at my siae devices tommorow, how it works.

**Comment by jozefrebjak** [comment]
I am ok with #8953. I am closing this issue.
