### ISSUE TITLE
Rule Issue - Integer Value?

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#8413]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
```
Component | Version
--------- | -------
LibreNMS  | 1.37-68-ga4048f54f
DB Schema | 245
PHP       | 7.1.11-0ubuntu0.17.10.1
MySQL     | 5.7.21-0ubuntu0.17.10.1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
```

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
This is not about a device, rather alert handling of data that is already in the database - so N/A I assume?

- [X] Please provide as much detail as possible.
Will try to! The details are in pastebin (link below) ... but the core issue is an issue I have been fighting with for a while now, with a rule not working - but I think the underlying problem may be the data format of the app_status column. For os-updates (as you can see in the data), I want values above a set threshold (16 in the example), but I'm getting all non-zero values ... unless I cast to an integer. Should this be handled already? Or is this working as desired, and rather the rule capability needs to be extended? I admit, not sure, that's why I ask.

- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
https://paste.ubuntu.com/p/FVGK8HdW3G/

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
Can you post capture the alert rule output?  Under the device, click the gear,  capture, and alerts.

**Comment by laf** [comment]
Can you please post this on the community site.
