### ISSUE TITLE
no power details on Cyberpower UPS monitoring

### ISSUE THREAD

**Issue by jsartorisd127** [librenms/librenms#8419]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 1.37-71-ga83ebdc
DB Schema | 245
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

discovery - https://p.libren.ms/view/8675d37b
poller - https://p.libren.ms/view/2422f539
snmpwalk - https://p.libren.ms/view/ee4be933
snmp with names - https://p.libren.ms/view/01081f10

- [x] Please provide as much detail as possible.

Trying to get battery and power load details from Cyberpower UPS units using RMCard205.  Card support was added in [#7931](https://github.com/librenms/librenms/pull/7931) and my card is detected properly as a power device, but I'm not collecting and graphing any useful power statistics.  I only have basic TCP and UDP network counters.

- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
PR submitted #8551. Please test.
