### ISSUE TITLE
Issues with ipv4 and ipv6 search

### ISSUE THREAD

**Issue by SaaldjorMike** [librenms/librenms#842]
Looks like an issue with:
/html/includes/table/address-search.inc.php

When searching for IPv4 and IPv6 addresses it lists all addresses associated with the selected device and not only matches. Might be an issue related to $tmp_mask and $mask when checking if address is a match on line 57 and line 64.

**Comment by laf** [comment]
I've put together a fix for this. It won't allow searching within subnets I.e looking for 1.1.1.1/32 in a 1.1.1.0/24 range but it's close enough for now.

**Comment by f0o** [comment]
Leaving this open as reminder

**Comment by laf** [comment]
I'm proposing we close this, we aren't going to be able to search for IPs in a specific subnet unless we convert storing IPs to using INET_ATON() which means converting the IP column to unsigned int.
