### ISSUE TITLE
Alerting Rules only apply on default poller node group?

### ISSUE THREAD

**Issue by jorgenaano** [librenms/librenms#8432]
We about 1000 devices monitored with LibreNMS and we have two poller groups.
My problem is that only devices from the default poller group gets on my dashboard. The alerting rules seems to only apply the devices from the default poller group. And I cant understand why?
The device from poller group 1 is registered as down if they are down and all information is available from all devices. So I believe that all the information are correctly in the database.
Any suggestions?

**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by kkrumm1** [comment]
@jorgenaano If you need help please use our Discord server to ask questions or our community site.
https://t.libren.ms/discord
https://community.librenms.org/
