### ISSUE TITLE
New Device/OS: Last Mile Gear CTM

### ISSUE THREAD

**Issue by theredon** [librenms/librenms#8449]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
====================================
Component | Version
--------- | -------
LibreNMS  | 1.37-83-g607a7f801
DB Schema | 246
PHP       | 7.0.27-0+deb9u1
MySQL     | 10.1.26-MariaDB-0+deb9u1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
====================================

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/9aa18b73
https://p.libren.ms/view/dfa724ab
https://p.libren.ms/view/03e97da6

- [X] Please provide as much detail as possible.
This for a Last Mile Gear CTM device which is similar to a Cambium CMM.  These devices provide power injection and timing for Cambium PMP equipment.  https://www.lastmilegear.com/product-category/gps-timing/

- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by kkrumm1** [comment]
@theredon your snmpwalk has no data https://p.libren.ms/view/23164692

**Comment by laf** [comment]
Will re-open when the data has been provided :)

**Comment by theredon** [comment]
Well I feel foolish, probably used the wrong snmp version on the CLI.  I have updated the pastebin with the SNMP information.

**Comment by pheinrichs** [comment]
@theredon I'm working on this ATM. Would you happen to have any mibs for this? I have all the important OID's but would prefer mibs if possible.

**Comment by theredon** [comment]
Here's what I got from the manufacturer.
[CTMMIBV2.zip](https://github.com/librenms/librenms/files/1848499/CTMMIBV2.zip)

**Comment by murrant** [comment]
Isn't this just a Cambium Canopy?  This is really odd...  The MIBs are a copy of the Canopy MIB with the enterprise number changed.

**Comment by theredon** [comment]
It is an third-party replacement for the Cambium CMM.  They may have just re-branded the MIB's, I honestly couldn't tell you.

**Comment by theredon** [comment]
I got to thinking about it more after your message and we have an old CMM in our network as well that shows up as generic.  Maybe we can knock out both.  Digging into our current system it looks like the CTM's and CMM's are both are using the same MIB's so murrant would be correct.
https://p.libren.ms/view/14ae356d
https://p.libren.ms/view/7ee0a926
https://p.libren.ms/view/b63d00a5

**Comment by laf** [comment]
Support has been added.
