### ISSUE TITLE
Support for new device(s) : Patton SIP-Gateway SN4971

### ISSUE THREAD

**Issue by sebvallee** [librenms/librenms#8454]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.37-90-g268e7c1ed
DB Schema | 247
PHP       | 7.0.19-1
MySQL     | 10.1.26-MariaDB-0+deb9u1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
Discovery : https://p.libren.ms/view/8dad610c
Poller : https://p.libren.ms/view/f3e73378
SNMPBulkWalk : Does not launch because only SNMPv1 is available on this OS.
EDIT : I finally got to launch snmpwalk : https://p.libren.ms/view/94e05b7a
- [X] Please provide as much detail as possible.
We would like to be able to supervise the number of calls, and the availability of BRIs on this type of hardware. Would you think is it possible ?
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by kkrumm1** [comment]
@sebvallee 
"SNMPBulkWalk : Does not launch because only SNMPv1 is available on this OS."
We really need that SNMPWalk. Closing until we get the walk.

**Comment by sebvallee** [comment]
I edited my first message with the output of snmpwalk. Is this OK for you ?

**Comment by kkrumm1** [comment]
@sebvallee Yes thank you -

**Comment by PipoCanaja** [comment]
PR #9901 is covering all devices of the SMARTNODE-MIB (Patton SN family) including this one.
