### ISSUE TITLE
New-Device - Multi-Tech FaxFinder VoIP Fax Server

### ISSUE THREAD

**Issue by VanillaNinjaD** [librenms/librenms#8465]
After spending some time trying to figure out how to add support myself I decided to bring it to the community for help.

This product is obviously an Embedded Linux appliance and I'm not sure how to cleanly add support for this device without potentially stomping on legitimate Linux Servers.

I have attached all the items that I saw in the FAQ, please let me know if I have forgotten information (DB is out of sync due to a switch from daily to stable)

Also attached is a link to the vendor provided MIB.

discovery.php
https://p.libren.ms/view/f169dba0

poller.php
https://p.libren.ms/view/65de4e5e

snmpbulkwalk
https://p.libren.ms/view/7e4036b3

MTFF-MIB
https://p.libren.ms/view/63c76dc4

----------------------------------------------------------------------------------------------------------

**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 1.37
DB Schema | 246
PHP       | 7.0.27-0+deb9u1
MySQL     | 10.1.26-MariaDB-0+deb9u1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by spencerbutler** [comment]
@VanillaNinjaD this should be supported now. Let us know if you have any outstanding issues.

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11665

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-multi-tech-faxfinder-voip-fax-server/11665/1
