### ISSUE TITLE
PAgPOperationMode Bug

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#8473]
Scenario:
A port that has been in a etherchannel is shutdown and removed from the etherchannel.
LibreNMS see's this correctly and logs this to the eventlog, however database is never updated hence eventlog is spammed during every polling cycle.

This is due to the device not responding to pagpOperationMode anymore on that port. Somehow we don't catch this in our code, handling the db update, or merely skip this due to the value being null.

**Comment by creolis** [comment]
Yeah, we see this at the moment - see:
<img width="737" alt="screen shot 2018-03-28 at 21 04 11" src="https://user-images.githubusercontent.com/1753505/38050577-cc09016e-32cb-11e8-820b-8c7f94dbddb8.png">

**Comment by murrant** [comment]
Need a ports poller debug to get any idea what is going on.

**Comment by Lukiko** [comment]
Wondering if any progress was made on this or if there is a workaround? Currently have this going on. Getting spammed by two switches every 5 minutes.

Thanks!

**Comment by laf** [comment]
Still need the info asked for above.

**Comment by ChrisAndrade1108** [comment]
Hey Laf, I'm having the same issue. See file attached. Hope this info helps diagnose. 
[Poller.txt](https://github.com/librenms/librenms/files/2337185/Poller.txt)

**Comment by psi-pl** [comment]
same problem here, @ChrisAndrade1108 why @kkrumm1 closed issue? did you solve the problem?

**Comment by slashrjl** [comment]
@kkrumm1 I'm still seeing the issue -- was there a fix for this because there's no link pull request?

**Comment by armstrma** [comment]
@kkrumm1 I'm also seeing this issue. I can provide any info needed.
