### ISSUE TITLE
Support for Buffalo Terastation 3010

### ISSUE THREAD

**Issue by vowywowy** [librenms/librenms#8477]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.37-110-ge814cd8
DB Schema | 247
PHP       | 7.1.15-1+ubuntu16.04.1+deb.sury.org+2
MySQL     | 10.0.34-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
`discovery.php` https://p.libren.ms/view/fada3889
`poller.php` https://p.libren.ms/view/80629fdf
`snmpbulkwalk` https://p.libren.ms/view/66be0308
- [x] Please provide as much detail as possible.

I've got a Buffalo Terastation that I'm trying to monitor but for some reason LibreNMS won't get its info properly. Other monitors, like PRTG for example, have no trouble parsing/detecting it correctly.

It has trouble getting the OS properly and just sets the vendor as "Linux" with its associated defaults. On top of that it is putting sysInfo stuff in single quotes (probably not LibreNMS's fault though). I can override location and device type to be correct, but I can't override vendor and OS detection as far as I can tell.

I'd rather not do some one off overrides for vendor and OS in LibreNMS internals, since I know other NMS solutions can detect it properly and LibreNMS is supposed to have Buffalo support.

All the important stuff like health/usage metrics, inventory, etc. are coming through just fine, it just looks like this device's sysInfo and vendor info parsing isn't happening correctly.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Please test https://github.com/librenms/librenms/pull/8536

**Comment by vowywowy** [comment]
No change on my end. Not sure if I'm testing right, I followed: https://docs.librenms.org/#Support/FAQ/#faq13

`git status` in `/opt/librenms` says:
`On branch device/issue-8477`
`Your branch is up-to-date with 'laf/device/issue-8477'.`
`nothing to commit, working directory clean`

Sorry if I'm doing something incorrect here.

**Comment by laf** [comment]
That's one way to test, run `./discovery.php -h HOSTNAME -m os -d`

**Comment by vowywowy** [comment]
Here: https://p.libren.ms/view/9f99f11d
