### ISSUE TITLE
New Device/OS's: Zhone MALC and CPE's

### ISSUE THREAD

**Issue by theredon** [librenms/librenms#8479]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
====================================
Component | Version
--------- | -------
LibreNMS  | 1.37-110-ge814cd8e3
DB Schema | 247
PHP       | 7.0.27-0+deb9u1
MySQL     | 10.1.26-MariaDB-0+deb9u1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
====================================

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
MALC 719
https://p.libren.ms/view/bc7c49a1
https://p.libren.ms/view/3bd88c02
https://p.libren.ms/view/978a09db

ETHX-3024
https://p.libren.ms/view/5df1d3e5
https://p.libren.ms/view/8ee35498
https://p.libren.ms/view/a18d5c60

ETHX-3044
https://p.libren.ms/view/c6f4d991
https://p.libren.ms/view/6903290a
https://p.libren.ms/view/4679dee0

ETHX-3400
https://p.libren.ms/view/87a3e665
https://p.libren.ms/view/ca4b5061
https://p.libren.ms/view/8861bcc0

- [X] Please provide as much detail as possible.
This is for some Zhone equipment.  According to the manufacturer the MIB's will work for the MALC as well as the ETHX CPE devices.  There is already a Zhone product OS called slms for the Zhone MXK in Libre but I'm not finding anything for these.
[ZNID-MIBS-2017-03-16SW3.1.293.tar.gz](https://github.com/librenms/librenms/files/1852660/ZNID-MIBS-2017-03-16SW3.1.293.tar.gz)

- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by PipoCanaja** [comment]
Hi @theredon 
The data is not available. Please repost it and re-open this issue so we can proceed it. 
Thanx
