### ISSUE TITLE
Mikrotik CCR not showing correct info

### ISSUE THREAD

**Issue by bhesterberg78** [librenms/librenms#8514]
I've been using LibreNMS for a couple years without issue. Autodiscover picks up new equipment great, until now. I had a UBNT EdgeRouter Pro running and it was polling correctly. Graphs reading good, ports correct, no issues. Well I outgrew it and switched to a Mikrotik CCR1036 and since then it's been messed up. Graphs aren't showing anything and the ports are all wrong. It's showing ports that don't exist(that I know of) and not showing ports that do, like it's not showing eth1, but it does show eth2 and ether2, eth3 and ether3, npi0, pni1, loop0, loop1, etc. What happened?

**Comment by crcro** [comment]
npi are from ubiquity hardware. did you do a device rediscovery? also did a purge deleted ports?

**Comment by bhesterberg78** [comment]
I did the rediscovery, but didn't delete ports. I'll try that, thank you!On Apr 5, 2018 9:43 PM, crcro <notifications@github.com> wrote:npi are from ubiquity hardware. did you do a device rediscovery? also did a purge deleted ports?

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
