### ISSUE TITLE
Tagged VLAN HP Procurve not showing in librenms

### ISSUE THREAD

**Issue by mpoinsignon** [librenms/librenms#8516]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
https://pastebin.com/2Ud22rj5
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

The tagged VLAN on HPE 5130 24G 4SFP+ 1-slot HI Switch JH323A Software Version 7.1.045 are not showing on the interfaces
![image](https://user-images.githubusercontent.com/36852664/38423035-0c31a75e-39ad-11e8-8933-b786802ff228.png)

https://p.libren.ms/view/e730ed8d
disvovery_vlan https://pastebin.com/R9X3Qm4H
poller 
[poller.txt](https://github.com/librenms/librenms/files/1884214/poller.txt)
snmpbulkwalk (too big 57MB for pastebin ) https://we.tl/WwFckWBWN8

**Comment by davama** [comment]
We have a 5406zl
> HP J8697A Switch 5406zl, revision K.16.02.0021, ROM K.15.30 (/ws/swbuildm/rel_spokane_qaoff/code/build/btm(swbuildm_rel_spokane_qaoff_rel_spokane)) (Formerly ProCurve)

And we can see the ports where a vlan is tagged
![image](https://i.imgur.com/LLML0RGm.jpg)

Although i cant really tell which is tagged or untagged

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by laf** [comment]
@murrant How come you've re-opened this?

**Comment by murrant** [comment]
I requested the ticket be made, the results look suspect.  Haven't checked it out yet.

**Comment by mpoinsignon** [comment]
Hello,
Still digging into this when I have some free time
The snmp v3 is now disabled on the switch because I thought it could be like this one Tagged vlan ports not being displayed on vlans page. #3285

**Comment by murrant** [comment]
@mpoinsignon The snmpwalk is no longer available.  I can't work on this until it is

**Comment by mpoinsignon** [comment]
Hello,
Sorry, I was away from any computer because of holidays
It is working now 
Thank you for your work, it is very great !
Have a nice day
