### ISSUE TITLE
NETGEAR Switches CPU and memory pollers

### ISSUE THREAD

**Issue by 4uba** [librenms/librenms#8518]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Component | Version
--------- | -------
LibreNMS  | 1.38-14-g831bd01
DB Schema | 247
PHP       | 7.2.2
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

U2FsdGVkX18W0CYuInRZcWtpBQZbGlBzOLL4oA6fNY4=
U2FsdGVkX1+nRUoviNzDvuuR9R+oKP5QTDw0M10gVT4=

Original disscussion: https://community.librenms.org/t/netgear-switches-cpu-and-memory-pollers/3695

Thanks a lot, guys, for you time and attention!

Have a nice weekend!
Igor

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by 4uba** [comment]
Excuse me, guys, my fault. Please re-open this issue. Thanks. Links are below!

Required links:
https://p.libren.ms/view/b63e3b75
https://p.libren.ms/view/7deb5b82

With third I have an error: Got a packet bigger than 'max_allowed_packet' bytes
But, I could paste txt file here:
[output.txt](https://github.com/librenms/librenms/files/1895082/output.txt)

**Comment by laf** [comment]
The output.txt file is the html code from our pastebin service. You'll need to upload the file somewhere like direct to github.

**Comment by laf** [comment]
Drop the `|./pbin.sh` and redirect the output somewhere else then upload the file to this issue.

**Comment by 4uba** [comment]
I have an error, as I mentioned during |./pbin.sh. What should I do?

**Comment by 4uba** [comment]
[output2.txt](https://github.com/librenms/librenms/files/1916027/output2.txt)

Hope it will work! Thanks

**Comment by laf** [comment]
Seems good

**Comment by 4uba** [comment]
How can I verify?

**Comment by CirnoT** [comment]
Please check whether this is working now @4uba

**Comment by PipoCanaja** [comment]
@4uba After a quick check, seems that it is all good now. Closing this.
