### ISSUE TITLE
PMP 450 MIMO & Sector Util 

### ISSUE THREAD

**Issue by mikerev** [librenms/librenms#8519]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

https://p.libren.ms/view/d3da87ab
https://p.libren.ms/view/d41aaa14
https://p.libren.ms/view/a8da5327

Greetings, 

My apologies if this is not the approach to updating existing OSs.

It seems that Cambium PMP devices (PMP 450 here) aren't having the newer MIMO and Sector Utilization metrics collected, specifically   .1.3.6.1.4.1.161.19.3.1.12.2.29 which is a fairly important metric to collect in terms of troubleshooting certain RF related issues. Thanks for any insight. 

http://community.cambiumnetworks.com/t5/PMP-450/15-1-1-450m-Additional-MU-MIMO-statistics/m-p/76417/thread-id/5104

**Comment by laf** [comment]
What are these values? What MIB does the oid `1.3.6.1.4.1.161.19.3.1.12.2.29` belong too?

**Comment by mikerev** [comment]
@pheinrichs thanks for the help, I'll make sure I confirm the mibs the next time I post for a new/updated OS. These would be great (per http://community.cambiumnetworks.com/t5/PMP-450/Monitoring-Utilization-450m-15-1-1/td-p/77136) 

.1.3.6.1.4.1.161.19.3.1.12.2.29

frUtlMedMumimoDownlinkSumimoUtilization
.1.3.6.1.4.1.161.19.3.1.12.2.31

frUtlMedMumimoDownlinkMumimoUtilization
.1.3.6.1.4.1.161.19.3.1.12.2.30
