### ISSUE TITLE
Add support for Ruckus R600/R610/R710

### ISSUE THREAD

**Issue by daniagar** [librenms/librenms#8524]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

https://p.libren.ms/view/19222021 
https://p.libren.ms/view/0af6ffaa 
https://p.libren.ms/view/3a2086a1 

validate.php:
![image](https://user-images.githubusercontent.com/34174425/38467084-ef084012-3b3b-11e8-95c7-70b1ecd7e9c8.png)

Vendor si correctly recognised but no wifi info is available an all 3 platforms. 

Thank you.

**Comment by daniagar** [comment]
https://p.libren.ms/view/19222021 
https://p.libren.ms/view/0af6ffaa 
https://p.libren.ms/view/3a2086a1 

validate.php:
![image](https://user-images.githubusercontent.com/34174425/38467084-ef084012-3b3b-11e8-95c7-70b1ecd7e9c8.png)

====================================
Component | Version
--------- | -------
LibreNMS  | 1.38-18-ga81e2d2
DB Schema | 247
PHP       | 7.1.13
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Composer Version: 1.6.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct

Vendor si correctly recognised but no wifi info is available an all 3 platforms. 

![image](https://user-images.githubusercontent.com/34174425/38467102-6ce6e51a-3b3c-11e8-8f56-4adfd5ff0ce1.png)

If any other info is needed please specify. 

Thank you.

**Comment by daniagar** [comment]
Hello, 

After last night update ZoneDirector controller got the wireless tab and the number of AP's and number of clients graphs as showed below.

![image](https://user-images.githubusercontent.com/34174425/38499517-7c461100-3c10-11e8-91a4-72f047f7620c.png)

The AP's however have now graphs with number of clients but they are not working. Also no CPU or memory graphs:

![image](https://user-images.githubusercontent.com/34174425/38499640-ecc464e0-3c10-11e8-83ec-90093961ee42.png)

**Comment by djamp42** [comment]
I just added CPU support, memory graphs are a little tricky, i might have to have someone help me on that because the ruckus MIBS for total memory are not very descriptive. 

I don't know what you mean by 

> The AP's however have now graphs with number of clients but they are not working.

**Comment by murrant** [comment]
Sometimes you detect the device type then discover the correct data.
Or fetch data for both and discover ones that return data.

**Comment by cchance27** [comment]
will this work with an SCG or vSCG or just zonedirector?

**Comment by murrant** [comment]
I don't really know anything about Ruckus.

**Comment by daniagar** [comment]
[9.12-GA-AP-mibs.zip](https://github.com/librenms/librenms/files/1913203/9.12-GA-AP-mibs.zip)

Hello,

I have upload the MIB's that I found on their site.

Thsnk you.

**Comment by theherodied** [comment]
@djamp42, for the individual APs you could create a separate OS such as ruckus-ap or something similar. It would be similar to what was done to differentiate hiveos-wireless and hiveos-wired.

You would still need a standalone AP or a walk to test with.

**Comment by eimann** [comment]
With vSZ/vSCG connected APs and connected Clients are not working, everything else (CPU, Triaffic, Memory, Disks ...) works fine.

**Comment by daniagar** [comment]
[ruckus.txt](https://github.com/librenms/librenms/files/2054430/ruckus.txt)

@djamp42  I have attached a walk for a R500 standalone AP.
Soon I will get an R600.

**Comment by daniagar** [comment]
[snmpwalk R600.txt](https://github.com/librenms/librenms/files/2064212/snmpwalk.R600.txt)

And also the R600 walk.

**Comment by djamp42** [comment]
@daniagar I'm not a programmer, this should be taken up by someone else.

**Comment by laf** [comment]
It's no longer clear what you need here. None of the last walks contain any usable data.

Please provide the information we ask for in the template, include a MIB and be specific about what it is you want to see.
