### ISSUE TITLE
mib_dir config variable missing - issue with pre-commit.php

### ISSUE THREAD

**Issue by vivia11** [librenms/librenms#8540]
Hello all,

This is what I've noticed recently, and I'm not sure if it is expected behavior or not. This might be related to commit #8429.

When running ./scripts/pre-commit.php, I get the following [output](https://pastebin.com/CbZNrjg9) with my snmp commands.

However, adding:
`$config['mib_dir'] = '/opt/librenms/mibs';` to config.php solves the issue and the pre-commit.php script runs without the odd issue.

Has anyone else been seeing this or is it just me? Maybe this is the expected behaviour?

|Component | Version|
|--------- | -------|
|LibreNMS  | 1.37-158-g7e4bae2|
|DB Schema | 248|
|PHP       | 7.2.2|
|MySQL     | 5.5.56-MariaDB|
|RRDTool   | 1.4.8|
|SNMP      | NET-SNMP 5.7.2|

[OK]    Composer Version: 1.6.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful

**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This should be fixed in #8527

However please pay attention to the template text, Github is for known or validated bugs. Use discord or the community site to discuss issues.
