### ISSUE TITLE
301 Moved Permanently  https://librenms.org/api/v0/

### ISSUE THREAD

**Issue by akbarabdullah1989** [librenms/librenms#8544]
why when accessing api from https://librenms.org/api/v0 the output shown is :
<html>
<head> <title> 301 Moved Permanently </ title> </ head>
<body bgcolor = "white">
<center> <h1> 301 Moved Permanently </ h1> </ center>
<hr> <center> nginx </ center>
</ body>
</ html>

**Comment by kkrumm1** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
