### ISSUE TITLE
Add support for PowerWalker SNMP Card (Not NMC SNMP Card)

### ISSUE THREAD

**Issue by melsom** [librenms/librenms#8564]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information
====================================
Component | Version
--------- | -------
LibreNMS  | 1.38-57-g146fc98
DB Schema | 247
PHP       | 7.0.15-0ubuntu0.16.04.4
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Would like to have added support for PowerWalker SNMP Card (UPS). This is not the same card as the NMC Card, which also has SNMP support. It's recognized as Linux SNMP-System OS.

SNMPWalk:
https://p.libren.ms/view/94349942

Poller:
https://p.libren.ms/view/d8084b5c

Discovery:
https://p.libren.ms/view/d1c7e4ed

MIB:
https://powerwalker.com/index.php?page=snmpmanager&lang=en

**Comment by laf** [comment]
Sorry but I don't see anyway to detect this device.

It uses the standard linux oid and sysdescr + the mib which would possibly be useful is called companyMIB and the upsIdManufacturer oid is blank.

I suggest you hassle the manufacturer to fix their snmp implementation.

**Comment by laf** [comment]
That is, unless you can find any way we can detect this device from the data you've given us.
