### ISSUE TITLE
ePMP GPS up in radio web interface, down in Libre

### ISSUE THREAD

**Issue by mikerev** [librenms/librenms#8567]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

https://p.libren.ms/view/6ee0ec65
https://p.libren.ms/view/0d226761
https://p.libren.ms/view/34574850

![kish](https://user-images.githubusercontent.com/10117960/38838828-a6b6b394-419d-11e8-9778-1c7c50a1b079.png)

**Comment by mikerev** [comment]
@pheinrichs ?

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by mikerev** [comment]
Why was this closed?
