### ISSUE TITLE
New device/OS: Repeatit Trinity Wireless

### ISSUE THREAD

**Issue by LozBC** [librenms/librenms#8577]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

validate.php here:
![image](https://user-images.githubusercontent.com/18052408/38881484-ba0df05c-425f-11e8-81d7-29c61d4cd7aa.png)

Discovery results: https://p.libren.ms/view/ba7b973d
Poller results: https://p.libren.ms/view/cd5b80ab
SNMP results: https://p.libren.ms/view/277eaf27

The SNMP MIB is available publically here: http://www.repeatit.se/product-support/trinity/

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11664

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-os-repeatit-trinity-wireless/11664/1
