### ISSUE TITLE
New device/OS: Motorola PTP Wireless 

### ISSUE THREAD

**Issue by LozBC** [librenms/librenms#8578]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Validation.php here:
![image](https://user-images.githubusercontent.com/18052408/38881759-7f8fc17a-4260-11e8-8a4a-fa135cf7ede5.png)

Discovery here: https://p.libren.ms/view/5defe4ba
Poller here: https://p.libren.ms/view/d98cfb76
SNMP here: https://p.libren.ms/view/002fea80

I am currently unsure of the MIB status (Freely available etc.) for this particular device.

**Comment by laf** [comment]
Just an fyi then without a mib you'd need to provide the OIDs that contain any relevant information otherwise just basic detection will be added.

**Comment by cchance27** [comment]
Issue with the motorola PTP links (now cambium) is they have like a bunch of different mibs and variations based on firmware versions over the years the fact the scanned copy still shows motorola means its an older firmware.

That said their mibs are only available from the site as part of the firmware downloads, and i don't have an active warranty at the moment to grab them...

That said i did find  http://www.snmpcenter.com/mibs-cambium-networks/

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11663

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-os-motorola-ptp-wireless/11663/1
