### ISSUE TITLE
Missing doc for auth_ldap_groupmembertype

### ISSUE THREAD

**Issue by oarmstrong** [librenms/librenms#8586]
Hi there. There doesn't appear to be any documentation for the `auth_ldap_groupmembertype` configuration option. I had to set this to `fulldn` to get LDAP to work correctly with my OpenLDAP server and the only reason I knew about the option was browing the code.

Would it be possible to get some documentation written for that option?

**Comment by kkrumm1** [comment]
This issue has been closed as it isn't classed as a bug or a new device request. You removed all data from the template and didn't read any of it. 
For help and request like this please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by laf** [comment]
@oarmstrong You can edit the docs yourself, please contribute back to the project.
