### ISSUE TITLE
sysContact email address validation

### ISSUE THREAD

**Issue by cron410** [librenms/librenms#8587]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

```
====================================
Component | Version
--------- | -------
LibreNMS  | 1.38-59-g052b9d1
DB Schema | 247
PHP       | 7.0.28-0ubuntu0.16.04.1
MySQL     | 10.0.34-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================
```

Looks like #7814 is still a problem. I just added a bunch of Eaton UPS units to LibreNMS and by default their SNMP syscontact is "Computer Room Manager". Here are my Email Alerting settings:
![image](https://user-images.githubusercontent.com/3082899/39005546-81dcbb80-43ce-11e8-85a1-363493cedec5.png)
and here is the device page of an example unit:
![image](https://user-images.githubusercontent.com/3082899/39005603-a1b44e78-43ce-11e8-9ffb-bbacc9924b58.png)

I get this error in the Recent Events list:
Could not issue critical alert for rule 'Device rebooted' to transport 'mail' Error: You must provide at least one recipient email address.

I would love for LibreNMS to fall back to the default contact when it doesn't find an address in the syscontact field.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
