### ISSUE TITLE
Alert stopped even updated to the latest version

### ISSUE THREAD

**Issue by DR3EVR8u8c** [librenms/librenms#8589]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for new device requests only. Please do not post bugs or ask questions** 

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Hi,
We would like to use LibreNMS to monitor our devices. LibreNMS works great. However, the alert stops after running about a day. I have googled and none of them seems related to my issues.
I also rebuild the server and hopefully it is just because of the configuration mess up. But the alerts stop on the new one as well.

- run daily.sh twice but not helping.
- ./validate.php return no error and this info:
```
====================================
Component | Version
--------- | -------
LibreNMS  | 1.38-60-g8762870
DB Schema | 247
PHP       | 7.0.27
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================
```
- manually run alerts.php -d and output that into [this log file](https://raw.githubusercontent.com/DR3EVR8u8c/studynotes/master/alert.debug)
- the mail transport works when I press "test transport"
- It looks like alert is not raised according to eventlog but Alert Capture shows that at least a rule is matched:
```
Rule name: Sensor under limit - Check Device Health Settings
Alert rule: sensors.sensor_current < sensors.sensor_limit_low AND sensors.sensor_alert = 1 AND macros.device_up = 1
Alert query: SELECT * FROM devices,sensors WHERE (devices.device_id = ? AND devices.device_id = sensors.device_id) AND sensors.sensor_current < sensors.sensor_limit_low AND sensors.sensor_alert = 1 AND (devices.status = 1 && (devices.disabled = 0 && devices.ignore = 0)) = 1
Rule match: matches
```
I have exhausted my ideas and looking forward to your help.
Thanks and regards,
Roger

**Comment by kkrumm1** [comment]
@DR3EVR8u8c Please read this. 
Did someone from discord ask you to open this? 

![image](https://user-images.githubusercontent.com/27959419/39050005-4b0b6bec-4469-11e8-91ba-b9cdc315f7d8.png)
