### ISSUE TITLE
rrdcached filename fix (#839) causes problems if rrd_dir is outside install_dir

### ISSUE THREAD

**Issue by sthen** [librenms/librenms#859]
I had rrdcached configured to keep files (-b) in /var/db/rrd, and set rrd_dir in LibreNMS to /var/db/rrd/librenms; the change in #839 gave the surprising result of looking in nonexistent /var/db/librenms instead.

Would it make sense to have a separate config variable e.g. rrd_cachedir to pass to rrdcached, which could by default be based on rrd_dir, but would allow the user to override if necessary?

**Comment by laf** [comment]
@f0o would you mind taking a look at this one?

**Comment by f0o** [comment]
PRing today

**Comment by f0o** [comment]
@sthen can you please test PR #861 and see if it works?

Apply patch:
```text
git remote add f0o https://github.com/f0o/librenms &&
git remote update f0o &&
git checkout f0o/issue-859
```

Revert changes:
```text
git stash &&
git checkout master
```

Thanks! :)

**Comment by laf** [comment]
@sthen This should now be fixed if you update.

The additional config option is only needed if you are using tcp connections for rrdcached which we assume you aren't as it was all working before.

Sorry for any trouble caused.

**Comment by sthen** [comment]
Sorry I didn't test this diff earlier, thanks for the fix - I can confirm it works for me.
