### ISSUE TITLE
Add forum signup methods

### ISSUE THREAD

**Issue by terrytibbles** [librenms/librenms#8615]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for new device requests only. Please do not post bugs or ask questions** 

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Hello,

This isn't a bug with LibreNMS, but I would like to sign up to the forum and don't use/don't want to use any of the login methods provided. Is it possible to create a local account on the forum, without linking it to an external authentication provider, such as Twitter, Facebook etc.?

Thanks.

**Comment by laf** [comment]
No, we don't want to store credentials and have chosen to rely on 3rd party auth.

Please don't open issues here to ask questions.
