### ISSUE TITLE
Two Alert widgets on dashboard break alert details. 

### ISSUE THREAD

**Issue by djamp42** [librenms/librenms#8624]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for new device requests only. Please do not post bugs or ask questions** 

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
====================================
Component | Version
--------- | -------
LibreNMS  | 1.38-90-gd799600
DB Schema | 248
PHP       | 7.0.28-0ubuntu0.16.04.1
MySQL     | 10.0.34-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================
- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

On the Dashboard i have 2 alert widgets setup, One for Unacknowledged Alerts and one for Acknowledged Alerts.. The issue is with the Alert Detail, if you expand the alert detail on an Acknowledged alert it actually expands the first alert on the unacknowledged panel. I took a screen shot, but it you might have to just setup it up to really see. 
![dashboard alert bug](https://user-images.githubusercontent.com/25335691/39327778-1119d1be-4967-11e8-94e1-cfd1a2afb5da.jpg)

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
