### ISSUE TITLE
Cumulus vlan to port mismatch

### ISSUE THREAD

**Issue by theherodied** [librenms/librenms#8632]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for new device requests only. Please do not post bugs or ask questions** 

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

====================================
Component | Version
--------- | -------
LibreNMS  | 1.38-98-g50935ff
DB Schema | 249
PHP       | 7.2.2
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

When polling a Cumulus switch in this case an edgecore as4610, the vlans to port association are off by 2.

Most everything in a snmpwalk goes as follows:
ifDescr.1 = lo
ifDescr.2 = eth0
ifDescr.3 = swp1
....

However when you get to the dot1qPvid .1 is now swp1 when it should be lo, .2 should be eth0, and .3 should be swp1.

dot1qPvid.1 = 141
dot1qPvid.2 = 5
dot1qPvid.3 = 141
dot1qPvid.4 = 141
dot1qPvid.5 = 141

At this point it appears that all vlan associations are 2 ports off.

Ideally I think we would see
dot1qPvid.1 = 
dot1qPvid.2 = 
dot1qPvid.3 = 141 (swp1 starting here instead of .1)
dot1qPvid.4 = 5
dot1qPvid.5 = 141
dot1qPvid.6 = 141
dot1qPvid.7 = 141

A complete walk can be seen at https://gist.github.com/theherodied/dba2fd38f459bf4b6481f3ec75d92d23

Anyone have an idea on how to work around this? I have also opened a ticket with Cumulus Networks.

**Comment by theherodied** [comment]
disco https://pastebin.com/ftrTc35i
poll https://pastebin.com/Va24wm3z
walk and additional info https://gist.github.com/theherodied/dba2fd38f459bf4b6481f3ec75d92d23

**Comment by laf** [comment]
Bugs go the community site or discord :)

**Comment by laf** [comment]
It's also not clear from the info but if you are saying they are out of order in the snmpwalk then it's a vendor issue.

**Comment by theherodied** [comment]
@laf that's what I get for working on it so late. I opened a case with Cumulus and they described the correct way. I opened this on the community site, hopefully someone knows an easy way to do this.

https://community.librenms.org/t/fix-cumulus-linux-vlan-issues/3907
