### ISSUE TITLE
New device HPE iLo5

### ISSUE THREAD

**Issue by kkrumm1** [librenms/librenms#8635]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for new device requests only. Please do not post bugs or ask questions** 

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `Component | Version
--------- | -------
`LibreNMS  | 1.38-98-g50935ff
DB Schema | 249
PHP       | 7.0.29
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2`
`section of `./validate.php` which you can run from the cli.
- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

SNMPWalk: https://gist.github.com/kkrumm1/eb278a7f004e46f536f2306b635bbb29#file-hpe-ilo5
Poller: https://gist.github.com/kkrumm1/402589bc5cc8b49a7f40c79317f50956#file-hpe-ilo5-poller
Discovery: https://gist.github.com/kkrumm1/32ddf40f68cd352422c552e4a4f5f216#file-hpe-ilo5-discovery

**Comment by Rosiak** [comment]
fixed #8634
