### ISSUE TITLE
 Please add ZTE OLT C320

### ISSUE THREAD

**Issue by bahirul** [librenms/librenms#8637]
Please add ZTE OLT C320 Version V2.1.0 Software, can't discover interface, port show nothing.

**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for new device requests only. Please do not post bugs or ask questions** 

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by Rosiak** [comment]
Please read the issue template before posting here.
<img width="700" alt="screen shot 2018-04-30 at 16 33 09" src="https://user-images.githubusercontent.com/6378934/39432630-38221c82-4c94-11e8-87d9-d13f8d0a9624.png">
