### ISSUE TITLE
LDAP Login with Jumpcloud

### ISSUE THREAD

**Issue by itscassa** [librenms/librenms#864]
Hi all,

I'm currently trying to set up LibreNMS with LDAP authentication.
I also have a Jumpcloud service with LDAP enabled for another LibreNMS instance.

I used the following FAQ: http://support.jumpcloud.com/knowledgebase/articles/474035-configuring-your-application-with-jumpcloud-ldap

When I enter the right login it's giving me a Failed to authenticate error. Though, it seems like it makes a connection, because when I enter incorrect login credentials I'm getting the same error + the error "Invalid credentials".

My current config:
```php
$config['auth_ldap_version'] = 3; # v2 or v3
$config['auth_ldap_server'] = "ldap.jumpcloud.com";
$config['auth_ldap_port']   = 389;
$config['auth_ldap_prefix'] = "uid=";
$config['auth_ldap_suffix'] = ",ou=Users,o={key},dc=jumpcloud,dc=com";
$config['auth_ldap_group']  = "cn=managers,ou=Groups,o={key},dc=jumpcloud,dc=com";
$config['auth_ldap_groupbase']  = "ou=Groups,o={key},dc=jumpcloud,dc=com";
```

Is there anyone currently running LibreNMS with LDAP authentication and Jumpcloud, or is there someone who knows how to set it up?

Thanks!

**Comment by laf** [comment]
Had a check into this today @itscassa and managed to get something working without updating code.

It won't support multiple groups so if you trying to setup different level of users then it might not work for you at the moment.

My config is (although I'd suggest you switch to ldaps for the port):

$config['auth_mechanism'] = "ldap"; # default, other options: ldap, http-auth
unset($config['auth_ldap_group']);
unset($config['auth_ldap_groups']);
$config['auth_ldap_groups']['librenms']['level'] = 10;
$config['auth_ldap_version'] = 3; # v2 or v3
$config['auth_ldap_server'] = "ldap.jumpcloud.com";
$config['auth_ldap_port']   = 389;
$config['auth_ldap_prefix'] = "uid=";
$config['auth_ldap_suffix'] = ",ou=Users,o={id},dc=jumpcloud,dc=com";
$config['auth_ldap_groupbase']  = "cn=librenms,ou=Users,o={id},dc=jumpcloud,dc=com";
$config['auth_ldap_groupmemberattr'] = "memberUid";

**Comment by itscassa** [comment]
@laf Thanks, logging in works now :-)

Though, I can't see any devices. The users are in the tag managers, and I've set the following:

```php
$config['auth_ldap_groups']['managers']['level'] = 10;
$config['auth_ldap_groupbase'] = "cn=managers,ou=Users,o={id},dc=jumpcloud,dc=com";
```

Have you got this working?

**Comment by laf** [comment]
Yeah but you need to drop cn=managers, from the groupbase. It won't work with that in - it does the group lookup later. It needs work to get proper support, for now that was all I could figure out.

**Comment by itscassa** [comment]
So like this?

```php
$config['auth_mechanism'] = "ldap"; # default, other options: ldap, http-auth
unset($config['auth_ldap_group']);
unset($config['auth_ldap_groups']);
$config['auth_ldap_groups']['managers']['level'] = 10;
$config['auth_ldap_version'] = 3; # v2 or v3
$config['auth_ldap_server'] = "ldap.jumpcloud.com";
$config['auth_ldap_port'] = 389;
$config['auth_ldap_prefix'] = "uid=";
$config['auth_ldap_suffix'] = ",ou=Users,o={id},dc=jumpcloud,dc=com";
$config['auth_ldap_groupbase'] = "ou=Users,o={id},dc=jumpcloud,dc=com";
$config['auth_ldap_groupmemberattr'] = "memberUid";
```
Still doesn't works

**Comment by laf** [comment]
Sorry I told a lie, your original groupbase was correct.

I've just retested on mine and can login and see all devices. I did have the same username in my mysql table which I removed and re-tested. Still fine.

Have you definitely enabled ldap support for that user and also switched on global ldap support in JumpCloud?

**Comment by itscassa** [comment]
Fixed by using another group/tag.
