### ISSUE TITLE
New Device/OS: PicOS switch

### ISSUE THREAD

**Issue by rbax82** [librenms/librenms#8645]
Hello,
I would very much appreciate it if you could add support for Pica8 devices to your fantastic software.
The MIBs can be found here: https://docs.pica8.com/display/picos2102cg/Pica8+Private+MIB
Thanks and keep up the great work! =)

**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for new device requests only. Please do not post bugs or ask questions** 

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the ====================================
Component | Version
--------- | -------
LibreNMS  | 1.39-4-gd257fa0
DB Schema | 249
PHP       | 7.0.28-0ubuntu0.16.04.1
MySQL     | 10.0.34-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
./discovery.php -h HOSTNAME -d | ./pbin.sh
https://p.libren.ms/view/09bac14e
./poller.php -h HOSTNAME -r -f -d | ./pbin.sh
https://p.libren.ms/view/bbc4d9af
snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh
https://p.libren.ms/view/494f5188
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by rbax82** [comment]
Do you need anything else from me?

**Comment by rbax82** [comment]
Do you require access to a device of this type in order to get it added to your software or ?

**Comment by laf** [comment]
No, just patience unless you are going to do it yourself. We have a script to make it easier.

**Comment by rbax82** [comment]
I tried it. Unfortunately the new-os script doesn't really support the State sensors which are kind of a must.

**Comment by rbax82** [comment]
https://docs.pica8.com/display/PICOS2111cg/Pica8+Private+MIB might be helpful to whoever ends up tackling this.
