### ISSUE TITLE
BGP info for HPE (comware7) 

### ISSUE THREAD

**Issue by manyax** [librenms/librenms#8649]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for new device requests only. Please do not post bugs or ask questions** 

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
https://p.libren.ms/view/d8f17e7b
- [x ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Is it possible to add support for BGP sessions inside a VRF? 

[discovery.php](https://p.libren.ms/view/2281337a)

[pooler.php](https://p.libren.ms/view/2e1ff2ec)

[snmpbulkwalk](https://p.libren.ms/view/3e46e8ec)

**Comment by Rosiak** [comment]
Hi @manyax 
Could we kindly ask you to create the feature request at our community site?(https://community.librenms.org/c/feature-requests)
Thanks!
