### ISSUE TITLE
Fortigate IPSec (tunnel mode) state

### ISSUE THREAD

**Issue by 4uba** [librenms/librenms#8661]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for new device requests only. Please do not post bugs or ask questions** 

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Component | Version
--------- | -------
LibreNMS  | 1.39-6-g4140796
DB Schema | 249
PHP       | 7.2.2
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

https://p.libren.ms/view/c308e4e5
https://p.libren.ms/view/16342e98
https://p.libren.ms/view/b196ca68

Hi Guys,

Since I have switched from IPSec Interface-based mode to IPSec Tunnel mode, I cannot check the state of connection. Probably, you could update you application with this functionality. 

The names of IPSec Tunnel intefaces are in line 14418 and 4 next. But I do not know which OID determine the state. Would be nice to add the as physical interfaces in the system!

Thanks a lot. Answer all your question if needed.

**Comment by 4uba** [comment]
I found OIDs:

.1.3.6.1.4.1.12356.101.12.2.2.1.2.1 = STRING: "S2S-LAURIER"
.1.3.6.1.4.1.12356.101.12.2.2.1.2.2 = STRING: "S2S-LAV-W1-W1"
.1.3.6.1.4.1.12356.101.12.2.2.1.2.3 = STRING: "S2S-LAV-W2-W1"
.1.3.6.1.4.1.12356.101.12.2.2.1.2.4 = STRING: "S2S-LAURIER-2"
.1.3.6.1.4.1.12356.101.12.2.2.1.2.5 = STRING: "S2S-NUV-DC"
.1.3.6.1.4.1.12356.101.12.2.2.1.2.6 = STRING: "S2S-NUVQC1"
.1.3.6.1.4.1.12356.101.12.2.2.1.3.1 = STRING: "S2S-LAURIER-PH2"
.1.3.6.1.4.1.12356.101.12.2.2.1.3.2 = STRING: "S2S-LAV-W1-W1-PH2"
.1.3.6.1.4.1.12356.101.12.2.2.1.3.3 = STRING: "S2S-LAV-W2-W1-PH2"
.1.3.6.1.4.1.12356.101.12.2.2.1.3.4 = STRING: "S2S-LAURIER-2-PH2"
.1.3.6.1.4.1.12356.101.12.2.2.1.3.5 = STRING: "S2S-NUV-DC-PH2"
.1.3.6.1.4.1.12356.101.12.2.2.1.3.6 = STRING: "S2S-NUVQC1-PH2"

.1.3.6.1.4.1.12356.101.12.2.2.1.20.1 = INTEGER: 1
.1.3.6.1.4.1.12356.101.12.2.2.1.20.2 = INTEGER: 1
.1.3.6.1.4.1.12356.101.12.2.2.1.20.3 = INTEGER: 1
.1.3.6.1.4.1.12356.101.12.2.2.1.20.4 = INTEGER: 1
.1.3.6.1.4.1.12356.101.12.2.2.1.20.5 = INTEGER: 1
.1.3.6.1.4.1.12356.101.12.2.2.1.20.6 = INTEGER: 2

1 = offline
2 = online

I have tested by switching interfaces.

**Comment by 4uba** [comment]
The same OIDs at firewall logs of which I have posted here:
IPSec - Phase 1
.1.3.6.1.4.1.12356.101.12.2.2.1.2.1 = STRING: "S2S-QC-W2-W1"
.1.3.6.1.4.1.12356.101.12.2.2.1.2.2 = STRING: "S2S-SH-W2-W1"
.1.3.6.1.4.1.12356.101.12.2.2.1.2.3 = STRING: "S2S-NUVQC1-PBX"
.1.3.6.1.4.1.12356.101.12.2.2.1.2.4 = STRING: "S2S-GB-W2-W1"
IPSec - Phase 2
.1.3.6.1.4.1.12356.101.12.2.2.1.3.1 = STRING: "S2S-QC-W2-W1-PH2"
.1.3.6.1.4.1.12356.101.12.2.2.1.3.2 = STRING: "S2S-SH-W2-W1-PH2"
.1.3.6.1.4.1.12356.101.12.2.2.1.3.3 = STRING: "S2S-NUVQC1-PBX-PH2"
.1.3.6.1.4.1.12356.101.12.2.2.1.3.4 = STRING: "S2S-GB-W2-W1-PH2"

States:
.1.3.6.1.4.1.12356.101.12.2.2.1.20.1 = INTEGER: 2
.1.3.6.1.4.1.12356.101.12.2.2.1.20.2 = INTEGER: 2
.1.3.6.1.4.1.12356.101.12.2.2.1.20.3 = INTEGER: 2
.1.3.6.1.4.1.12356.101.12.2.2.1.20.4 = INTEGER: 2

**Comment by 4uba** [comment]
We could you IPSec Phase 1 as name!

Thanks!
Igor

**Comment by laf** [comment]
We have no native support for this so please open a feature request on the community forum.
