### ISSUE TITLE
Missing some support for Synology DSM

### ISSUE THREAD

**Issue by laf** [librenms/librenms#867]
https://dl.dropboxusercontent.com/u/9924670/synology/filer.txt

https://dl.dropboxusercontent.com/u/9924670/synology/filer.jpg

https://groups.google.com/forum/#!topic/librenms-project/w-gf99qm0OM

**Comment by f0o** [comment]
We need to make the list public-readable. Cant read the the thread you linked me because i need tovlogon to google although not even subscribed via google...

**Comment by laf** [comment]
One for @paulgear.

The post doesn't have anymore details really. The person reporting it wants to see what's in that screenshot but we don't currently support it.

**Comment by paulgear** [comment]
I'll see what I can do about the mailing list permissions.

**Comment by laf** [comment]
For anyone following this and wants to test Synology DSM temp support for disks / system:

cd /opt/librenms
git remote add laf https://github.com/laf/librenms.git
git remote update laf
git checkout issue-867
./discovery.php -h HOSTNAME -d -m sensors
./poller.php -h HOSTNAME -d -m sensors

If after a few more poller runs the temperature data doesn't appear then please post the output to the discovery and poller commands above.

**Comment by Lonecrowe** [comment]
I'll jump in next week.  I have a few rack/diskstations I can test on.

**Comment by laf** [comment]
Hey @Lonecrowe.

I know you're busy, just wondering if you've had a chance to test this at all?

Thanks

**Comment by Lonecrowe** [comment]
Sorry no another move this weekend and we are still cleaning up the mess it caused hehe. I'm thinking by next week I'll have settled back into my office or earlier hopefully.

**Comment by Lonecrowe** [comment]
Had some time - the temps are working.  Going to wait for it a graph a bit to be sure.

**Comment by Lonecrowe** [comment]
Yeah its all working you can PR this one.

**Comment by laf** [comment]
Brill - thanks @Lonecrowe :)

**Comment by f0o** [comment]
Merged :)
