### ISSUE TITLE
it becomes to be wrong to show the number of the ports in Up status.

### ISSUE THREAD

**Issue by panjun0417** [librenms/librenms#868]
when I  shutdown an port by using 
shutdown comand. The number of disabled ports will increase. but I am so sorry to find that , the number of Up ports does not change.

![pic](https://cloud.githubusercontent.com/assets/3973112/7365919/1c3e3296-edc7-11e4-9a4e-d87caecc25f6.jpg)

**Comment by f0o** [comment]
Mysteriously.
I'll investigate :)

**Comment by f0o** [comment]
Hard nut to crack.. The SQL's look all fine. And I cant reproduce it on my servers.

Can you give us more details please?
What kind of device is it?
What kind of port is it?
Can you provide debug-logs? (open the page as regular, add /debug=yes/ to the URL and click on SQL-Debug, Copy everything and paste it on bpaste.net)

Thanks :)

**Comment by laf** [comment]
Also had a check of this and can't see anything that would cause this issue. 

If you can run these two SQL queries and post the output back that would be helpful.

SELECT ifName,ifAdminStatus,ifOperStatus FROM ports AS I, devices AS D WHERE I.`deleted` = '0' AND D.`device_id` = I.`device_id` AND I.`ignore` = '0' AND D.`ignore` = '0' AND I.`ifOperStatus` = 'up';

SELECT ifName,ifAdminStatus,ifOperStatus FROM ports AS I, devices AS D WHERE I.`deleted` = '0' AND D.`device_id` = I.`device_id` AND I.`ignore` = '0' AND D.`ignore` = '0' AND I.`ifAdminStatus` = 'down';

**Comment by panjun0417** [comment]
the value of  17 ports  in mysql database
![mypic](https://cloud.githubusercontent.com/assets/3973112/7383339/145c10a0-ee50-11e4-842d-6da010bd9100.png)

could it helpful?

**Comment by laf** [comment]
yes @panjun0417, the reason why you are seeing this is what you have two ports showing as admin down (shutdown) but that the link is still up.

You can add device_id to that query to see which device(s) the ports are assoicated with:

```sql
SELECT device_id,ifName,ifAdminStatus,ifOperStatus FROM ports AS I, devices AS D WHERE I.`deleted` = '0' AND D.`device_id` = I.`device_id` AND I.`ignore` = '0' AND D.`ignore` = '0' AND I.`ifAdminStatus` = 'down';
```

What device type is it, os, model number?

**Comment by panjun0417** [comment]
I use GNS3 to simulate the whole network system. and I use c3725 to simulate the router.I just configure FastEthernet0/0  and   FastEthernet0/1 of the router .just like
![4fe87b64-468a-4477-831d-a1be8d88fbc0](https://cloud.githubusercontent.com/assets/3973112/7389821/700f6c86-eea4-11e4-9305-bf05a7e193df.png)
then  I shutdown FastEthernet0/0
![85f9022d-4ce1-458c-924a-b50c2b855a5e](https://cloud.githubusercontent.com/assets/3973112/7389830/88e94c9a-eea4-11e4-8a9e-e268f98b238b.png)

At last I  run 'python poller-wrapper.py'  command.

I try to shutdown FastEthernet0/1 to replace  FastEthernet0/0, but the result does not change.

**Comment by laf** [comment]
We ned to see the results of the SQL query to see the port status.

I'll try and simulate in GNS3 as well though.

**Comment by panjun0417** [comment]
if  I shutdown  FastEthernet0/0.  the ifAdminStatus vlue of FastEthernet0/0 will be down,but the ifOperStatus value of FastEthernet0/0 is still up .

in file '/librenms/html/pages/device/overview.inc.php'  
I Find the code:'
$ports['up']       = dbFetchCell("SELECT COUNT(*) FROM `ports` WHERE device_id = ? AND `ifOperStatus` = 'up'", array($device['device_id']))'

if it should be changed as
'$ports['up']       = dbFetchCell("SELECT COUNT(*) FROM `ports` WHERE device_id = ? AND `ifOperStatus` = 'up' AND `ifAdminStatus` = 'up'", array($device['device_id']));'  ?

**Comment by laf** [comment]
That is indeed one fix but I'd be more interested to find out why a port admin down is still show as ifOp up.

**Comment by f0o** [comment]
I think (from my amateur POV) that IfOperStatus is UP when a LINK exist, i.e. a cable is plugged.
Whereas IfAdminStatus is UP when the OS sets the port into UP mode.

This at least applies to Linux.

**Comment by laf** [comment]
ifAdminStatus is UP when a port is enabled on a router/switch. No cable has to be plugged in. Then as you mentioned, when a cable is plugged in, ifOperStatus turns to up.

**Comment by panjun0417** [comment]
ifOperStatus       ifAdminStatus          meaning
     Up                          Up                 the port is ok
    Down                      Up                 something is wrong
    Down                    Down               the port is down

ifAdminStatus can be set by administartor,but ifOperStatus is readonly. so  if the port is shutdown by administrator, ifOperStatus should change to Down .
I use GNS3 to simulate virtual network. it cause ifOperStatus still up when I shutdown the port. may be this is the difference between the virtual network and actual network.
May be in actual network, it will never happen...
It's  just my personal idea...

**Comment by panjun0417** [comment]
sorry ,something is wrong with the format above.

ifOperStatus ,       ifAdminStatus ,        meaning
Up   ,                    Up ,                          the port is ok
Down  ,                Up,                           something is wrong
Down  ,                Down               ,       the port is down
