### ISSUE TITLE
API - unsuitable content type of response (always text/html)

### ISSUE THREAD

**Issue by mrcnpdlk** [librenms/librenms#8686]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for new device requests only. Please do not post bugs or ask questions** 

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | 1.39-32-ge4bc556
DB Schema | 249
PHP       | 7.0.30-1~dotdeb+8.1
MySQL     | 5.6.31-77.0
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

Calling i.e. https://XXXX/api/v0/ports/4434 returns answer as `text/html` instead of 'application/json'.
I have tested a lot of functions - problem the same.

PS: route /api/v0/devices/:hostname/graphs generates PHP error:
```
PHP message: PHP Fatal error:  require(): Failed opening required '/opt/librenms/html/includes/graphs/get/auth.inc.php' (include_path='.:/usr/share/php') in /opt/librenms/html/includes/graphs/graph.inc.php on line 43
PHP message: [2018-05-10 13:53:58] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: require(): Failed opening required '/opt/librenms/html/includes/graphs/get/auth.inc.php' (include_path='.:/usr/share/php') in /opt/librenms/html/includes/graphs/graph.inc.php:43
```

**Comment by laf** [comment]
This is already known but please don't post bugs here as per the template.

**Comment by mrcnpdlk** [comment]
Ok. Sorry about that. I am not the first and not the last one. Meaby you should remove this template from issue creator.

Does this "known" bug have any issue Id? This one you have closed but I cannot find another one.

**Comment by mrcnpdlk** [comment]
A ok. I have read the instructions but without understanding. A have joined to the community... Sorry one again
