### ISSUE TITLE
ajax_setresolution.php 404's and session files cause ./validate.php to fail

### ISSUE THREAD

**Issue by vowywowy** [librenms/librenms#8689]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for new device requests only. Please do not post bugs or ask questions** 

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Possibly [this commit](https://github.com/librenms/librenms/commit/1ad7f3138b2e0974dc9e07d212807d22aaae3df3), causes initial graphs on device front pages not to render, since ajax_setresolution.php doesn't exist any more.
Also some session files are being created in /opt/librenms/framework/sessions/<random string> which makes validation fail:
```
====================================
Component | Version
--------- | -------
LibreNMS  | 1.39-36-g5236a24dd
DB Schema | 249
PHP       | 7.1.17-1+ubuntu18.04.1+deb.sury.org+1
MySQL     | 10.1.29-MariaDB-6
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.6.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[FAIL]  We have found some files that are owned by a different user than librenms, this will stop you updating automatically and / or rrd files being updated causing graphs to fail.
        [FIX] chown -R librenms:librenms /opt/librenms
        Files:
         /opt/librenms/storage/framework/sessions/mRQ7eetQy1KNoID5PsFXQeAYUxo3wlyYuglyApkh
         /opt/librenms/storage/framework/sessions/1r8PSQzskItUR2bYrN4WMSr33yJFrCLNCU9HRjaG
```

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Github isn't for bug reporting.
