### ISSUE TITLE
New Device: Huawei B2268H CPE (LTE)

### ISSUE THREAD

**Issue by inkweb** [librenms/librenms#8694]
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for new device requests only. Please do not post bugs or ask questions** 

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

    ====================================
    Component | Version
    --------- | -------
    LibreNMS  | 1.39-41-g824ce31
    DB Schema | 249
    PHP       | 7.0.28-0ubuntu0.16.04.1
    MySQL     | 10.1.24-MariaDB-1~precise
    RRDTool   | 1.5.5
    SNMP      | NET-SNMP 5.7.3
    ====================================

Discovery: https://p.libren.ms/view/5962e146
Poller: https://p.libren.ms/view/f56b8ad4
SNMPWalk: https://p.libren.ms/view/43b82ac6

I do not have a MIB, but the relevant OID's are:
oid_1_3_6_1_2_1_31_1_1_1_6_1_, 1.3.6.1.2.1.31.1.1.1.6.1.0, DEFAULT, "Incoming"
oid_1_3_6_1_2_1_31_1_1_1_10_1_, 1.3.6.1.2.1.31.1.1.1.10.1.0, DEFAULT, "Outgoing"
oid_1_3_6_1_4_1_37373_100_1_1_7_, 1.3.6.1.4.1.37373.100.1.1.7.0, DEFAULT, "SINR"

**Comment by inkweb** [comment]
Is there any updates on this device? Do i need to provide more informaion?

**Comment by PipoCanaja** [comment]
Hello @inkweb 
Unfortunately, nobody had time so far to have a look at this device. LibreNMS is an open source project community driven, anybody can contribute. If you want to get things moving faster, the best option is to go for it. The basic discovery and standard sensors usually does not involve any coding at all. 
https://docs.librenms.org/Developing/os/Initial-Detection/
https://docs.librenms.org/Developing/os/Health-Information/
You can start to play with these in your environnement, and come up with a pull request or contact us on discord to get help on how to do it. 
Bye

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11662

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-huawei-b2268h-cpe-lte/11662/1
