### ISSUE TITLE
Support for Acme Packet Net-Net 4500 (possibly others)

### ISSUE THREAD

**Issue by CaptainLame** [librenms/librenms#8701]
Hello. I am trying to add support for an Acme Packet SBC, specifically the 4500 model. It handles VOIP traffic so it has lots of stats such as calls per second on a given realm or current sessions, etc. I'm just shooting for initial hardware monitoring at this point, but all of the data is retrievable via SNMP.
Graphing of the realm data will probably have to be handled by a shell script as a service because it needs to aggregate the stats from several of these SBCs.

MIB package here, the ianaiftype.mib may duplicate information already in the usual base MIBs. 
[acme_4300_mib.zip](https://github.com/librenms/librenms/files/1996363/acme_4300_mib.zip)
Full OID list: [miboids.txt](https://github.com/librenms/librenms/files/1996366/miboids.txt)

**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for new device requests only. Please do not post bugs or ask questions** 

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
====================================
Component | Version
--------- | -------
LibreNMS  | 1.39-44-g3e9f4b3
DB Schema | 249
PHP       | 7.2.5
MySQL     | 5.7.21-21
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.2
====================================

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
These were run with with the MIBS installed at the system level, but before running the new-os.php script
discovery.php -h HOSTNAME -d
https://p.libren.ms/view/7e9b2436 (redacted full host name and location information; redacted IPs and other customer information)

poller.php -h HOSTNAME -r -f -d 
https://p.libren.ms/view/7808002a (redacted full host name and location information)

snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .
https://p.libren.ms/view/35031282
Note: This had to be seriously redacted as it revealed IP addresses, customer, and vendor information which either by law or by contract I cannot publicly share; also as there are nearly 2000 realms configured on the device, I trimmed it to remove repeated data (original file over 63k lines; pruned down to 1682).

- [X] Please provide as much detail as possible.
Discovery files generated by new-os.php and modified to add indexes and processors entry:
Main def: https://p.libren.ms/view/325a5dbe
Sensors: https://p.libren.ms/view/8cb94b28
Discovery with MIBs loaded and above YAML: https://p.libren.ms/view/61986862
Poller run with MIBs loaded and above YAML: https://p.libren.ms/view/b913b30e

So Discovery appears to be getting the defined sensors, but then polling is returning 0 values on them.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11661

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/support-for-acme-packet-net-net-4500-possibly-others/11661/1
