### ISSUE TITLE
Stupid scale_min and scale_max for temp and humidity graphs

### ISSUE THREAD

**Issue by Sopsy** [librenms/librenms#8718]
Is there any reason why temperature and humidity graphs are defined with the current scale_min and max values?

I propose the following change (can do a pull request if needed):
html/includes/graphs/sensor/humidity.inc.php:
$scale_min = '0';
$scale_max = '100';

html/includes/graphs/sensor/temperature.inc.php:
// Remove the following lines completely to enable autoscale
// $scale_min = '0';
// $scale_max = '60';

Of course, even better would be if this could be editable from the WebUI.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by laf** [comment]
Feel free to propose a PR but please don't open issues on github
