### ISSUE TITLE
New Device: Cambium CMM4

### ISSUE THREAD

**Issue by inkweb** [librenms/librenms#8731]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

    ====================================
    Component | Version
    --------- | -------
    LibreNMS  | 1.39-65-g0448c9e
    DB Schema | 250
    PHP       | 7.0.30-0ubuntu0.16.04.1
    MySQL     | 10.1.24-MariaDB-1~precise
    RRDTool   | 1.5.5
    SNMP      | NET-SNMP 5.7.3
    ====================================

Discovery: https://p.libren.ms/view/48a86f72
Poller: https://p.libren.ms/view/b18394ca
SNMPWalk: https://p.libren.ms/view/7ea3383c
MIB: http://support.cambiumnetworks.com/framed/onlinetools/content.CMM4-MIB.html

This device is essentially a switch with with 8 ports and POE injector. The current LibreNMS is detecting and graphing the main 10/100 port, but not the separate switch ports, nor their power state.

**Comment by pheinrichs** [comment]
@inkweb Could you let me know what the output of this OID is?
.1.3.6.1.4.1.161.19.3.6.3.2.0

**Comment by inkweb** [comment]
.1.3.6.1.4.1.161.19.3.6.3.2.0 = STRING: "CMM4 0a-00-3e-e8-12-20"

**Comment by cchance27** [comment]
Cmm4 is a power and gps injection device those ports are passthrough ports not switch ports and not exposed packet info as their is no packet info or throughout because the device doesn’t touch data. All you can get from this device is the gps and power states

**Comment by inkweb** [comment]
unfortunately i do not have a very good template for cacti for the CMM4, so its graphing very little. So you may be correct on this one. however it seems odd that the CMM3 would have per-port data, but the newer CMM4 would not.

**Comment by cchance27** [comment]
Neither has one

The cmm4 ships with a cmm4 and an etherwan switch sometimes

But the cmm itself is just a passthrough injector both the 3 and 4 to my knowledge that’s why the outdoor version ships with a seperate outdoor etherwan switch

**Comment by laf** [comment]
Fixed in #8737
