### ISSUE TITLE
New Device: Cambium CMM3

### ISSUE THREAD

**Issue by inkweb** [librenms/librenms#8732]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

    ====================================
    Component | Version
    --------- | -------
    LibreNMS  | 1.39-65-g0448c9e
    DB Schema | 250
    PHP       | 7.0.30-0ubuntu0.16.04.1
    MySQL     | 10.1.24-MariaDB-1~precise
    RRDTool   | 1.5.5
    SNMP      | NET-SNMP 5.7.3
    ====================================

Discovery: https://p.libren.ms/view/f19e3b76
Poller: https://p.libren.ms/view/bc96850d
SNMPWalk: https://p.libren.ms/view/89c191f3
MIB: http://support.cambiumnetworks.com/framed/onlinetools/content.CMM3-MIB.html

This device is essentially a switch with with 8 ports and POE injector. The current LibreNMS is detecting and graphing the main 10/100 port, but not the separate switch ports. It IS graphing the switch ports power states.

**Comment by cchance27** [comment]
Ummm the cmm3 is not a switch it’s a pass through power and sync device so theirs no traffic to monitor nor are those ports exposed via snmp as they aren’t switch ports

**Comment by inkweb** [comment]
I've got per-port bandwidth usage working fine in Cacti (which i'm trying to replace with LibreNMS). So the data must be there someplace.

**Comment by cchance27** [comment]
From the etherwan or from the cmm itself? Could have sworn the internal ports are passthrough for cmm3/4/5

**Comment by inkweb** [comment]
Ya, each of our 25 CMM3's has 8 individual bandwidth graphs.

**Comment by laf** [comment]
Fixed in #8737
