### ISSUE TITLE
Add host with same host names but different UDP ports

### ISSUE THREAD

**Issue by DGothmin** [librenms/librenms#8739]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

We need to monitor the routers and Switches which is behind the routers. Using NAT with different UDP ports.
I have tried below still no luck, any help?
$config['allow_duplicate_sysName'] = true;

**Comment by laf** [comment]
Don't post for help or bugs here, read the text in the template.
