### ISSUE TITLE
Hi, Please Give Solution For LibreNms Automatic Schedule Reporting on HTML or PDF Data Format

### ISSUE THREAD

**Issue by boopathyct90** [librenms/librenms#8742]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

To create a new device request please use this link: https://github.com/librenms/librenms/issues/new?template=New-Device.md

**Comment by boopathyct90** [comment]
Hi, Please Give Solution For LibreNms Automatic Schedule Reporting on HTML or PDF Data Format

**Comment by laf** [comment]
Please read the template in future. Use discord or the community site.
