### ISSUE TITLE
New Device: UTAX CD 14x5 MFP

### ISSUE THREAD

**Issue by knipp** [librenms/librenms#8752]
I'd like to request support for UTAX CD 14x5 multi function printers. They are pollable via SNMPv3 but only show up as generic device so far. Here are the requested outputs:

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery
https://p.libren.ms/view/a5ff41a0

Poller:
https://p.libren.ms/view/a16a1ecd

SNMP
https://p.libren.ms/view/e56121d7

Additionally, a link to the (user) documentation:
https://www.utax.de//C125712200447418/vwLookupDownloads/IH_CD1435_1445_1455_UK.pdf/$FILE/IH_CD1435_1445_1455_UK.pdf

Currently, I have no access to suitable .SVG, but I can get in touch with the vendor if needed to see what I can do.

Thank you and best regards,

Stefan

**Comment by knipp** [comment]
The vendor wasn't able to provide me with an SVG for the device, and the MIBs they pointed me to are the RFC standard for printers located [here](http://www.rfc-base.org/txt/rfc-1759.txt) - so not sure if that helps at all :/

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-utax-cd-14x5-mfp/11660/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11660
