### ISSUE TITLE
New Device: Citrix NetScaler 410

### ISSUE THREAD

**Issue by leandrojmp** [librenms/librenms#8753]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Result of snmpbulkwalk: [https://p.libren.ms/view/bb357555](https://p.libren.ms/view/bb357555)
Result of discovery.php: [https://p.libren.ms/view/9a156cd6](https://p.libren.ms/view/9a156cd6)
Result of poller.php: [https://p.libren.ms/view/5078eaf1](https://p.libren.ms/view/5078eaf1)

The device is a Citrix NetScaler 410, a SD-WAN appliance.

**Comment by dneto82** [comment]
More details:
https://docs.citrix.com/en-us/netscaler-sd-wan/9-2/hardware-platforms/cb-intro-400-800-2k-3k-con1.html

MIB References:
https://docs.citrix.com/en-us/netscaler-sd-wan/10/snmp.html

**Comment by dneto82** [comment]
Hi friends, I'm also interested in support this device. How can I help?

**Comment by laf** [comment]
https://docs.librenms.org/#Developing/Support-New-OS/

That's the best place to start.

**Comment by leandrojmp** [comment]
Hello, I'm sending the MIB for the Citrix NetScaler SD-WAN.

We would like to see things like the operationg system version, currently it is only bringing the name.

[CITRIX-NetScaler-SD-WAN-MIB.txt](https://github.com/librenms/librenms/files/2189774/CITRIX-NetScaler-SD-WAN-MIB.txt)

**Comment by laf** [comment]
We need an snmpbulkwalk against `.1.3.6.1.4.1.3845` to add anything further.

**Comment by leandrojmp** [comment]
Ok! I will run a snmpbulkwalk and upload the results.

**Comment by leandrojmp** [comment]
Hello, I'm sending the result f the snmpbulkwalk.

I needed to anonymize some information, which I changed to PRIVATESTRINGXXXXXX, and also I needed to change some public IP address from the original ones to 192.XXX.XXX.XXX.

[sdwan-snmpbulkwalk.txt](https://github.com/librenms/librenms/files/2337840/sdwan-snmpbulkwalk.txt)

**Comment by leandrojmp** [comment]
Hello, do you need something else on this issue?

**Comment by PipoCanaja** [comment]
Hi @leandrojmp 
PR #9834 is posted. Feel free to test it.
PipoCanaja

**Comment by PipoCanaja** [comment]
Merged in PR #9834

**Comment by leandrojmp** [comment]
I confirm it is working, I now have information about the serial number, version and sensors.
