### ISSUE TITLE
IPv6 addresses not being picked up on Juniper devices

### ISSUE THREAD

**Issue by Nickmman** [librenms/librenms#8770]
Hello,

I'm having an issue where I have a couple of Juniper devices added and the IPv4 addresses are picked up no problem. However, the IPv6 addresses are not being picked up. The IPv6 BGP sessions are detected, however. But then the local IPv6 address is nowhere to be found.

I can confirm that the IPv6 addresses are available to be polled. I have added the same device to another Network Monitoring Platform and all the IPv6 IPs show up. Currently testing against an MX 104.

Has anyone else noticed this issue? Is there a workaround? Could it be due to missing MIBs?

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
