### ISSUE TITLE
Getting bogus high/low thresholds for Flexoptics 40ge modules

### ISSUE THREAD

**Issue by pozar** [librenms/librenms#8774]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms
[snmpbulkwalk.txt](https://github.com/librenms/librenms/files/2041812/snmpbulkwalk.txt)

/view/03c58a9b
https://p.libren.ms/view/eae0ce49
- [ X] Please provide as much detail as possible.

Getting bad high/low thresholds from SNMP on Junos boxes with 40GE Flexoptics
OIDs are reporting 22.27 dBm for high and 20 dBm for low.  Alas, when queried on the box ...
Physical interface: et-0/0/52
   [...]
    Laser output power high alarm threshold   :  4.4636 mW / 6.50 dBm
    Laser output power low alarm threshold    :  0.1000 mW / -10.00 dBm
    Laser output power high warning threshold :  3.5420 mW / 5.49 dBm
    Laser output power low warning threshold  :  0.1995 mW / -7.00 dBm
   [...]
   ---
High warning is 5.49 dBm and low is -7.00 dBm
Wonder if Libre / MIBs are not understanding about lanes and parsing the wrong OIDs.

- [X ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
