### ISSUE TITLE
Brocade NOS v4.1.3b - virtual chassis

### ISSUE THREAD

**Issue by MHammett** [librenms/librenms#8775]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/c09cdc8f
https://p.libren.ms/view/51a104b1
https://p.libren.ms/view/b9845998

- [x] Please provide as much detail as possible.
Adding additional information for when switch is in virtual chassis mode for "Brocade NOS v4.1.3b"
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/brocade-nos-v4-1-3b-virtual-chassis/11659/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11659
