### ISSUE TITLE
Brocade NOS v4.1.3b - single switch in virtual chassis

### ISSUE THREAD

**Issue by MHammett** [librenms/librenms#8776]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
switch 1
-----
https://p.libren.ms/view/b0c528ca
https://p.libren.ms/view/f61b39c2
https://p.libren.ms/view/397b53f4

switch 2
-----
https://p.libren.ms/view/0a29db7f
https://p.libren.ms/view/2f8e55b4
https://www.dropbox.com/s/nu7vm2kes42v6av/Brocade%20switch%202.txt?dl=0

- [x] Please provide as much detail as possible.
Adding additional information for when switch is in virtual chassis mode for "Brocade NOS v4.1.3b"

I don't get a complete picture of what's happening on my switches in virtual chassis mode. The virtual IP only has one switch and I can't add the individual switches due to the device already being present.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Our devices are based on OS, I expect this is the same OS as #8776 so add the data from this to that issue.

**Comment by MHammett** [comment]
You mean #8775 (this issue is #8776)? Yes, same OS. It's also an OS that currently works in LibreNMS, but only contains information from one switch when they're in the virtual chassis setup. I didn't know what sort of information was contained in the dumps, so I didn't know if Libre was able to get all information from all switches in virtual chassis mode or if each switch needs to be addressed individually.

**Comment by laf** [comment]
So these devices get detected ok?

If you want additional sensors or similar adding then you'll need to be specific about the OIDs they are in otherwise it's not actually clear what you are expecting to see.
