### ISSUE TITLE
Dell Networking N1100 - No/wrong CPU/memory readings

### ISSUE THREAD

**Issue by sirHulda** [librenms/librenms#8778]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Discovery: https://p.libren.ms/view/6c2ae37a
Poller: https://p.libren.ms/view/14b37cbf
SNMP: https://github.com/librenms/librenms/files/2044061/powerconnect-hbg-sw02.snmpwalk.txt
MIB: https://github.com/librenms/librenms/files/2044057/Release.6.4.2.6-mibs.zip

Pic 1: https://user-images.githubusercontent.com/23332970/40602189-2e1bccec-6247-11e8-9ba6-04c75d914e72.PNG
Pic2: https://user-images.githubusercontent.com/23332970/40602296-9609c2aa-6247-11e8-97af-d4099fc8c387.PNG

Memory usage is at 37% for all N1100 devices, we are currently monitoring 40 of them. I suspect that librenms is using the wrong OID.

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11658

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/dell-networking-n1100-no-wrong-cpu-memory-readings/11658/1
