### ISSUE TITLE
Please Add Support for ORVALDI UPS

### ISSUE THREAD

**Issue by jozefrebjak** [librenms/librenms#8780]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Please add support for Orvaldi UPS which is using RFC1628.

Here is the MIB: https://p.libren.ms/view/2b993b03
Here is the CAPTURED DISCOVERY: https://p.libren.ms/view/45594ffa
And there is a SNMP SCAN: https://p.libren.ms/view/235936fa
There is a logo of vendor: https://goo.gl/a6nHB2

Thank you.

**Comment by PipoCanaja** [comment]
@jozefrebjak Ready for testing with ```./scripts/github-apply 10021 ``` .

**Comment by PipoCanaja** [comment]
@jozefrebjak I have a doubt with the objectID sent by the device : 
![Capture d’écran 2019-03-24 à 23 16 16](https://user-images.githubusercontent.com/38363551/54886690-1ae2c280-4e8b-11e9-846d-7672ce7d8db3.png)
Could you confirm the value of 'sysObjectID.0' in your devices ?
