### ISSUE TITLE
Add Occam\Calix OS 8.x

### ISSUE THREAD

**Issue by MHammett** [librenms/librenms#8788]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/6d242bd1
https://p.libren.ms/view/e549466b
https://p.libren.ms/view/ba32046e

- [x] Please provide as much detail as possible.
You support Occam OS (now Calix) older versions, but version 8 is not being recognized as Occam\Calix. It's being detected as generic.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by peelman** [comment]
We're trying to get get rid of our B6's, but they are going to have along tail; so some monitoring would be handy.

**Comment by MHammett** [comment]
@peelman I added some older versions earlier. I just upgraded to 8.0.

https://github.com/librenms/librenms/issues/8359
https://github.com/librenms/librenms/issues/8361
https://github.com/librenms/librenms/issues/8362

**Comment by murrant** [comment]
What would be the correct/best name for the OS?

**Comment by MHammett** [comment]
Calix bought Occam. It was called OccamOS, but obviously post-acquisition, the Occam part has been stripped. However, it hasn't been replaced with CalixOS or anything like that. They appear just seem to call it B6 system, which would be the entire product family, not just the OS. @peelman any thoughts on that?

Here is how a few versions self-identify:

`DeKalb_01_02>show version
OccamOS System V5.5R7 for BLC 6440 01  [shelf:1f0, slot:2]
Kernel build id V5_5R7, made Tue Mar 10 18:31:48 PDT 2009
Booter build id V5_5R7, made Tue Mar 10 18:26:21 PDT 2009

Processor:  440GP Rev. C  at 396 MHz, revision  4.129 (pvr 4012 0481)
VCO: 792 MHz, PLB: 132 MHz, OPB: 66 MHz, EPB: 66 MHz, Sysclk: 33 MHz

Board assembly number is 900032-01, revision  number is D6, type is 1
Serial number is 11467390, MAC address is 00:02:86:00:2a:94
Manufactured by OCCM on 11/19/2004

PLD revision 1.1
FPGA revision FPGA_0: 000.020, FPGA_1: 000.008

Chassis BLC_6012
Hostname DeKalb_01_02, uptime is 59 days, 20:28, load average 1.21, 0.77, 0.65`

`RCH_Slot2>show vers
OccamOS System V6.2R4 for BLC 6440 01  [shelf:fff, slot:2]
Kernel build id V6_2R4, made Wed Nov 10 10:47:57 PST 2010
Booter build id V6_2R4, made Wed Nov 10 10:44:02 PST 2010

Processor:  440GP Rev. C  at 396 MHz, revision  4.129 (pvr 4012 0481)
VCO: 792 MHz, PLB: 132 MHz, OPB: 66 MHz, EPB: 66 MHz, Sysclk: 33 MHz

Board assembly number is 900032-04, revision  number is E1, type is 1
Serial number is 01611540, MAC address is 00:02:86:00:5b:b8
Manufactured by OCCM on 1/7/2006

PLD revision 1.1
FPGA revision FPGA_0: 000.023, FPGA_1: 000.008

Chassis BLC_6012
Hostname RCH_Slot2, uptime is 269 days, 22:35, load average 1.31, 0.60, 0.47`

`Malta_02>show vers
B6 System 7.3 for B6-256  [shelf:fff, slot:15]
Kernel build id 7.3.61.0, made Mon Oct 27 11:41:46 CST 2014
Processor:  405EX Rev. D  at 533.333333 MHz, revision  20.115 (pvr 1291 1473)

Board assembly number is 400-00394, revision  number is 22, type is 1
Top-level assembly is 0320710
Serial number is 211501800257, MAC address is 00:02:86:30:54:99
Manufactured by Calix on 01-21-2015

PLD revision 1.2
FPGA revision FPGA_0: 0.9

Chassis B6-001 Rev: D0 Mfg date:  5/23/2005 serial number: 05571650
Hostname Malta_02, uptime is 57 days, 19:28, load average 3.73, 2.93, 2.83`

`Genoa_01_01>show version
B6 System 8.0 for BLC 6252 02  [shelf:fff, slot:1]
Kernel build id 8.0.40.0, made Thu Sep 7 10:10:45 CST 2017
Processor:  440GP Rev. C  at 396 MHz, revision  4.129 (pvr 4012 0481)
VCO: 792 MHz, PLB: 132 MHz, OPB: 66 MHz, EPB: 66 MHz, Sysclk: 33 MHz

Board assembly number is 900140-04, revision  number is A4, type is 1
Serial number is 02723340, MAC address is 00:02:86:01:84:86
Manufactured by OCCM on 2/3/2007

PLD revision 2.0
FPGA revision FPGA_0: 000.006

Chassis B6-012 Rev: B4 Mfg date:  11/22/2007 serial number: 11787170
Hostname Genoa_01_01, uptime is 5 days, 20:55, load average 5.80, 5.53, 5.50`

**Comment by peelman** [comment]
the `sh vers` still reports OccamOS, so i’d say stick with that for now. Calix hasn’t paid the OS anything but lip service for years now, so i doubt it will see any updates that would change that.

**Comment by MHammett** [comment]
Which versions are you seeing that on? Mine starting with version 7 no longer display Occam OS.

**Comment by peelman** [comment]
Sorry, my phone was cutting off the rest of the notes and I didn't realize you had pasted multiple versions.

Honestly, even seeing the other outputs, I'd still say OccamOS; there isn't really a set of names for them, other than maybe B6_OS or something, which isn't very clear.  The E7 OS is either referred to as EXA or AXOS, depending on the path you're on.  B6 is still limited to Occam or Occam-derived equipment, so I would see now point trying to draw a distinction beyond that.

**Comment by MHammett** [comment]
Seems reasonable.

OccamOS it is.

**Comment by laf** [comment]
I've added detection for the device in the first post as part of the calix model we already have, seems silly to add another OS for an older one that is now part of another company.

**Comment by murrant** [comment]
It has different MIBs...  So I think it warrants a different OS.
