### ISSUE TITLE
Mikrotik: Add number of PPP sessions

### ISSUE THREAD

**Issue by MHammett** [librenms/librenms#8790]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/8fe16fc4
https://p.libren.ms/view/23514be9
https://www.dropbox.com/s/76ddx8zu459gw6k/ICI%20MT%20SNMP.txt?dl=0
- [x] Please provide as much detail as possible.
I'm looking to have LibreNMS graph the number of PPP sessions. The OID is: 1.3.6.1.4.1.9.9.150.1.1.1.0
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
We don't have core support for this so it can't be added. Feel free to create a feature request on the community site.
