### ISSUE TITLE
New Device: Ruckus SmartZone/SmartCell Gateway

### ISSUE THREAD

**Issue by joedacris** [librenms/librenms#8798]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
Here are the MIBs for the SCG/SZ controllers:
[Ruckus_SCG_3.5 .1_GA_Mib_20170407.zip](https://github.com/librenms/librenms/files/2063472/Ruckus_SCG_3.5.1_GA_Mib_20170407.zip)
- [x] Please provide as much detail as possible.
The current ruckuswireless.yaml works with ZoneDirector 1100/1200 devices and for SmartZone is recognized as the correct Ruckus Wireless OS(although recognized as SmartZone hardware type).  However, some graphs are broken because of this - Number of Clients and Connected APs.  I tried importing MIBs and updating yaml but that is simply not enough and would probably benefit others to have this fixed.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 1 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.
