### ISSUE TITLE
Same object ID on different devices 

### ISSUE THREAD

**Issue by DGothmin** [librenms/librenms#8804]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X ] Please provide as much detail as possible.
- [ X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Object ID	.1.3.6.1.4.1.16972

Two devices

TP link router - Model No. TD-W8970
Billion BiPAC 8800NL R2 (5.159.211.24)

[poller-5.159.211.24.txt](https://github.com/librenms/librenms/files/2075202/poller-5.159.211.24.txt)
[discovery-5.159.211.24.txt](https://github.com/librenms/librenms/files/2075203/discovery-5.159.211.24.txt)

[poller-5.159.210.169.txt](https://github.com/librenms/librenms/files/2075205/poller-5.159.210.169.txt)
[discovery-5.159.210.169.txt](https://github.com/librenms/librenms/files/2075206/discovery-5.159.210.169.txt)

both got same ID and recognize as generic device.

Any ideas?

**Comment by laf** [comment]
These are separate devices, please create two separate issues + you haven't provided ALL the info asked for.
