### ISSUE TITLE
Meraki Wireless Dashboard

### ISSUE THREAD

**Issue by pmusolino-rms** [librenms/librenms#8809]
[MERAKI-CLOUD-CONTROLLER-MIB.txt](https://github.com/librenms/librenms/files/2106767/MERAKI-CLOUD-CONTROLLER-MIB.txt)

**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/109b0328 - Discovery
https://p.libren.ms/view/90ff90bb - Poller
 https://p.libren.ms/view/06df5e2d - SNMP

- [x ] Please provide as much detail as possible.
Dashboard gives stats on number of clients, the details of individual APs
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
I've added basic detection, without the MIB we can't see what else is available.

**Comment by pmusolino-rms** [comment]
I can pastebin the MIB or upload it somewhere?

**Comment by laf** [comment]
Attach it to this issue please.

**Comment by pmusolino-rms** [comment]
Attached to initial comment

**Comment by WKilner** [comment]
Did you ever manage to progress this?

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/meraki-wireless-dashboard/11657/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11657
