### ISSUE TITLE
Please add Huawei OceanStor 5500

### ISSUE THREAD

**Issue by natomiast** [librenms/librenms#8814]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Please add support for Huawei OceanStor 5500
Here are mibs: 
[Storage Device MIB File and Description.zip](https://github.com/librenms/librenms/files/2097735/Storage.Device.MIB.File.and.Description.zip)

Thank you.

**Comment by laf** [comment]
Thanks for the new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by natomiast** [comment]
Hello,
I added required information. Please re-open this issue.
Regards
