### ISSUE TITLE
Please add support for "Billion" (BiPAC 8800NL R2)

### ISSUE THREAD

**Issue by DGothmin** [librenms/librenms#8817]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

discovery - https://p.libren.ms/view/feeebd56
Poller - https://p.libren.ms/view/10d6095d
snmpbulkwalk - https://p.libren.ms/view/49ae6929

MIB and OID

[mg-soft mib browser professional edition generic snmp trace for bipac 8800nl r2.pdf](https://github.com/librenms/librenms/files/2105438/mg-soft.mib.browser.professional.edition.generic.snmp.trace.for.bipac.8800nl.r2.pdf)
[bipac 8800nl r2 oid.txt](https://github.com/librenms/librenms/files/2105439/bipac.8800nl.r2.oid.txt)

**Comment by DGothmin** [comment]
[bipac 8800nl r2 oid.txt](https://github.com/librenms/librenms/files/2101803/bipac.8800nl.r2.oid.txt)
[mg-soft mib browser professional edition generic snmp trace for bipac 8800nl r2.pdf](https://github.com/librenms/librenms/files/2101804/mg-soft.mib.browser.professional.edition.generic.snmp.trace.for.bipac.8800nl.r2.pdf)


Please see above OID and MIB details provided by the vendor.

**Comment by laf** [comment]
Is this walk definitely from this device. It's got the same sysObjectID as the TPLink device you requested.

**Comment by DGothmin** [comment]
Hi Laf,

Yes it is, i did found that earlier and open below issue,

https://github.com/librenms/librenms/issues/8804

**Comment by laf** [comment]
Unfortunately then we can't add detection for either of these devices then, the sysObjectIDs are useless as is sysDescr and I can't see any custom OID that would help us.
