### ISSUE TITLE
Please add support for Zyxel VMG1312-B10D

### ISSUE THREAD

**Issue by DGothmin** [librenms/librenms#8818]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

OID - https://support.aa.net.uk/ZyXEL_VMG1312_SNMP
Discovery - https://p.libren.ms/view/56f11f64
Poller - https://p.libren.ms/view/d21c56a5
snmpbulkwalk - https://p.libren.ms/view/260ccb17

**Comment by laf** [comment]
This device is already detected correctly, with the fact the snmpwalk is empty and you've not provided any information about what you expect to see then this is being closed.
