### ISSUE TITLE
Please add support for TP-LINK TD-W8970 

### ISSUE THREAD

**Issue by DGothmin** [librenms/librenms#8819]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Discovery - ./discovery.php -h 5.159.210.169 -d | ./pbin.sh
Poller - https://p.libren.ms/view/3f92260d
SNMPBULKWALK - https://p.libren.ms/view/cfed30c1

Not sure about MIBs.

**Comment by laf** [comment]
Pull request submitted, feel free to test it #8823

**Comment by laf** [comment]
It's not merged, see the pull request for details on how to test.

**Comment by laf** [comment]
Closing, see #8817
