### ISSUE TITLE
Telegram notifications - markdown support (fix)

### ISSUE THREAD

**Issue by e1z0** [librenms/librenms#8820]
Open file: LibreNMS/Alert/Transport/Telegram.php Search for the line: 38

`curl_setopt($curl, CURLOPT_URL, ("https://api.telegram.org/bot{$data['token']}/sendMessage?chat_id={$data['chat_id']}&text=$text"));`

And replace it with:

`curl_setopt($curl, CURLOPT_URL, ("https://api.telegram.org/bot{$data['token']}/sendMessage?chat_id={$data['chat_id']}&text=$text&parse_mode=Markdown"));`

**Comment by laf** [comment]
Please submit a pull request if you have a fix.
