### ISSUE TITLE
Cisco RV345 Gigabit Dual WAN VPN Router

### ISSUE THREAD

**Issue by tjashworth** [librenms/librenms#8834]
Need help adding a new Cisco RV345 Gigabit Dual WAN VPN Router

Discovery, poller and snmpwalk as follows:
[Discovery](https://p.libren.ms/view/ac1394e1)
[Poller](https://p.libren.ms/view/bb942c92)
[snmpwalk](https://p.libren.ms/view/52adb21a)

Thanks!

**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11656

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/cisco-rv345-gigabit-dual-wan-vpn-router/11656/1
