### ISSUE TITLE
Please add Huawei OceanStor 5500

### ISSUE THREAD

**Issue by natomiast** [librenms/librenms#8843]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
         https://p.libren.ms/view/50e5dd28
         https://p.libren.ms/view/1d2189ea
         https://p.libren.ms/view/24051f4a
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Please add support for Huawei OceanStor 5500
Here are mibs:
[Storage.Device.MIB.File.and.Description.zip](https://github.com/librenms/librenms/files/2136085/Storage.Device.MIB.File.and.Description.zip)

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11655

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/please-add-huawei-oceanstor-5500/11655/1
