### ISSUE TITLE
Error importing PowerAlert MIB with PRTG importer

### ISSUE THREAD

**Issue by DarkLogicX** [librenms/librenms#8854]
![mib-imp](https://user-images.githubusercontent.com/15129034/42105587-7ab10aaa-7b96-11e8-927d-89d5750e2485.png)
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
