### ISSUE TITLE
web-installer - Improve error message when database is missing

### ISSUE THREAD

**Issue by mrjester888** [librenms/librenms#886]
During install, the database didn't get created properly.  At the configure database step of the web installer, it gave a generic error "Couldn't connect to the database, please check your details".  It should have indicated "Database not found" or something to that effect.  MySQL gives an informative error when a database is missing.

mysql> use foo
ERROR 1049 (42000): Unknown database 'foo'
mysql>

**Comment by laf** [comment]
Thanks @mrjester888.

I've done a PR to give more info, the section you had an issue with is just the standard mysql can't connect message but that's now included in the response.
