### ISSUE TITLE
result code:5 since Jul 1 on discovery.php -h new

### ISSUE THREAD

**Issue by boudreau** [librenms/librenms#8863]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

To create a new device request please use this link: https://github.com/librenms/librenms/issues/new?template=New-Device.md

Component | Version
--------- | -------
LibreNMS  | 1.41-6-g3269183
DB Schema | 253
PHP       | 7.0.28
MySQL     | 10.1.24-MariaDB
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.2

Hi, I have a cron jobs running for the last 2+ years and since Sundays(Jul 1) last update I'm getting a result code: 5 from the discovery.php -h new

I see no errors, what result code 5, usually had code 0 and no email

Thanks

```
Cronic detected failure or error output for the command:
/usr/bin/timeout --preserve-status 30m /var/www/librenms/discovery.php -h new

RESULT CODE: 5

ERROR OUTPUT:

STANDARD OUTPUT:
LibreNMS Discovery
SNMP [0/0.00s]: Get[0/0.00s] Getnext[0/0.00s] Walk[0/0.00s] MySQL [3/0.00s]: Cell[0/0.00s] Row[0/0.00s] Rows[3/0.00s] Column[0/0.00s] Update[0/0.00s] Insert[0/0.00s] Delete[0/0.00s] RRD [0/0.00s]: Update[0/0.00s] Create [0/0.00s] Other[0/0.00s]

```

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
