### ISSUE TITLE
Error connecting to database

### ISSUE THREAD

**Issue by praburaj1985** [librenms/librenms#8873]
Error connecting to database.
Access denied for user 'USERNAME'@'localhost' (using password: YES)** 
am get the above error while installing the librenms
and am got the ./validate is successfull
====================================
Component | Version
--------- | -------
LibreNMS  | 1.41-8-gd9ceaf7
DB Schema | 253
PHP       | 7.2.6
MySQL     | 10.1.34-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Composer Version: 1.6.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  You have not added any devices yet.
        [FIX] You can add a device in the webui or with ./addhost.php

Please give any one solution.......

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
