### ISSUE TITLE
Centralized monitoring of Poller Versions in Distributed setup

### ISSUE THREAD

**Issue by cchance27** [librenms/librenms#8874]
Theirs currently no way to track what version of software the pollers are running we can see via about the version on the web server but theirs no way from the WEBUI to see the pollers are on. Perhaps adding a checkpoint during the poll that sets the version it was running during the last poll into the poller history tab.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

It's a good idea though, just posted in the wrong place.
