### ISSUE TITLE
Roomalert 24E

### ISSUE THREAD

**Issue by PointPubMedia** [librenms/librenms#8882]
Currently you are supporting some Roomalert device.  We are having a RoomAlert24E and looks like the MIB/autodiscovery is not working fine.

Currently our RoomAlert24E is discovered as a Chatsworth PDU .

We are the one that paid a long time ago to supported these device on observium and we provide all the MIBs.

Let us know if you need them too!

**Comment by PointPubMedia** [comment]
snmpwalk:

`iso.3.6.1.2.1.1.1.0 = STRING: "RoomAlert24E"
iso.3.6.1.2.1.1.2.0 = OID: ccitt.10.43.6.1.4.1
iso.3.6.1.2.1.1.3.0 = Timeticks: (2757376) 7:39:33.76
iso.3.6.1.2.1.1.4.0 = ""
iso.3.6.1.2.1.1.5.0 = STRING: "oomAlert24E"
iso.3.6.1.2.1.1.6.0 = ""
iso.3.6.1.2.1.1.7.0 = INTEGER: 12
iso.3.6.1.2.1.2.1.0 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.1.1 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.2.1 = STRING: "Network"
iso.3.6.1.2.1.2.2.1.3.1 = INTEGER: 6
iso.3.6.1.2.1.2.2.1.4.1 = INTEGER: 1500
iso.3.6.1.2.1.2.2.1.5.1 = Gauge32: 10000000
iso.3.6.1.2.1.2.2.1.6.1 = Hex-STRING: 00 20 4A 89 72 C8
iso.3.6.1.2.1.2.2.1.7.1 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.8.1 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.9.1 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.2.2.1.10.1 = Counter32: 847824
iso.3.6.1.2.1.2.2.1.11.1 = Counter32: 11706
iso.3.6.1.2.1.2.2.1.12.1 = Counter32: 0
iso.3.6.1.2.1.2.2.1.13.1 = Counter32: 0
iso.3.6.1.2.1.2.2.1.14.1 = Counter32: 0
iso.3.6.1.2.1.2.2.1.15.1 = Counter32: 0
iso.3.6.1.2.1.2.2.1.16.1 = Counter32: 571731
iso.3.6.1.2.1.2.2.1.17.1 = Counter32: 2684
iso.3.6.1.2.1.2.2.1.18.1 = Counter32: 191
iso.3.6.1.2.1.2.2.1.19.1 = Counter32: 0
iso.3.6.1.2.1.2.2.1.20.1 = Counter32: 0
iso.3.6.1.2.1.2.2.1.21.1 = Gauge32: 2
iso.3.6.1.2.1.2.2.1.22.1 = NULL
iso.3.6.1.2.1.4.1.0 = INTEGER: 2
iso.3.6.1.2.1.4.2.0 = INTEGER: 31
iso.3.6.1.2.1.4.3.0 = Counter32: 2837
iso.3.6.1.2.1.4.4.0 = INTEGER: 0
iso.3.6.1.2.1.4.5.0 = INTEGER: 0
iso.3.6.1.2.1.4.6.0 = Counter32: 0
iso.3.6.1.2.1.4.7.0 = Counter32: 0
iso.3.6.1.2.1.4.8.0 = INTEGER: 0
iso.3.6.1.2.1.4.9.0 = Counter32: 2843
iso.3.6.1.2.1.4.10.0 = Counter32: 0
iso.3.6.1.2.1.4.11.0 = INTEGER: 0
iso.3.6.1.2.1.4.12.0 = INTEGER: 0
iso.3.6.1.2.1.4.13.0 = INTEGER: 0
iso.3.6.1.2.1.4.14.0 = INTEGER: 0
iso.3.6.1.2.1.4.15.0 = INTEGER: 0
iso.3.6.1.2.1.4.16.0 = INTEGER: 0
iso.3.6.1.2.1.4.17.0 = INTEGER: 0
iso.3.6.1.2.1.4.18.0 = INTEGER: 0
iso.3.6.1.2.1.4.19.0 = INTEGER: 0
iso.3.6.1.2.1.4.20.1.1.172.30.30.6 = IpAddress: 172.30.30.6
iso.3.6.1.2.1.4.20.1.2.172.30.30.6 = INTEGER: 1
iso.3.6.1.2.1.4.20.1.3.172.30.30.6 = IpAddress: 255.255.255.0
iso.3.6.1.2.1.4.20.1.4.172.30.30.6 = INTEGER: 1
iso.3.6.1.2.1.4.20.1.5.172.30.30.6 = INTEGER: 0
iso.3.6.1.2.1.5.1.0 = Counter32: 248
iso.3.6.1.2.1.5.2.0 = INTEGER: 0
iso.3.6.1.2.1.5.3.0 = Counter32: 0
iso.3.6.1.2.1.5.4.0 = Counter32: 0
iso.3.6.1.2.1.5.5.0 = Counter32: 0
iso.3.6.1.2.1.5.6.0 = Counter32: 0
iso.3.6.1.2.1.5.7.0 = Counter32: 0
iso.3.6.1.2.1.5.8.0 = Counter32: 248
iso.3.6.1.2.1.5.9.0 = Counter32: 0
iso.3.6.1.2.1.5.10.0 = Counter32: 0
iso.3.6.1.2.1.5.11.0 = INTEGER: 0
iso.3.6.1.2.1.5.12.0 = INTEGER: 0
iso.3.6.1.2.1.5.13.0 = INTEGER: 0
iso.3.6.1.2.1.5.14.0 = Counter32: 248
iso.3.6.1.2.1.5.15.0 = INTEGER: 0
iso.3.6.1.2.1.5.16.0 = Counter32: 0
iso.3.6.1.2.1.5.17.0 = INTEGER: 0
iso.3.6.1.2.1.5.18.0 = INTEGER: 0
iso.3.6.1.2.1.5.19.0 = INTEGER: 0
iso.3.6.1.2.1.5.20.0 = INTEGER: 0
iso.3.6.1.2.1.5.21.0 = INTEGER: 0
iso.3.6.1.2.1.5.22.0 = Counter32: 248
iso.3.6.1.2.1.5.23.0 = INTEGER: 0
iso.3.6.1.2.1.5.24.0 = INTEGER: 0
iso.3.6.1.2.1.5.25.0 = INTEGER: 0
iso.3.6.1.2.1.5.26.0 = INTEGER: 0
iso.3.6.1.2.1.7.1.0 = Counter32: 1767
iso.3.6.1.2.1.7.2.0 = Counter32: 294
iso.3.6.1.2.1.7.3.0 = Counter32: 769
iso.3.6.1.2.1.7.4.0 = Counter32: 1742
`

**Comment by murrant** [comment]
Odd all other avtech devices have a sysObjectID starting with:

This has .0.10.43.6.1.4.1, which is the sysObjectID listed for chatsworth-pdu

Please provide the info requested here: https://docs.librenms.org/#Support/FAQ/#faq20

**Comment by PointPubMedia** [comment]
https://p.libren.ms/view/5767ea55

https://p.libren.ms/view/0ac3b2e9

Can't run the 3rd command as it'as only v1

**Comment by murrant** [comment]
then just do snmpwalk instead of snmpbulkwalk

**Comment by PointPubMedia** [comment]
https://p.libren.ms/view/825382c6

**Comment by murrant** [comment]
Thanks, info looks ok at glance.
Looks like 24E is not supported in LibreNMS yet, so support would need to be added.

**Comment by murrant** [comment]
@PointPubMedia Oh, is the firmware up to date?  The sysObjectID seems like a bug.

**Comment by PointPubMedia** [comment]
yeah latest firmware 4.1.3

**Comment by PointPubMedia** [comment]
Just have a chat with AVTech and they confirm the bug and of course, they will not change it as the model is EOL

**Comment by PointPubMedia** [comment]
Ohhh... just got a reply.  Looks like they will provide an update to the firmware this week.
I will let you know before you change anything.

**Comment by murrant** [comment]
Interesting, I contacted their support about it perhaps it had an effect.

**Comment by PointPubMedia** [comment]
Got another reply from them.  They will not release any update.

**Comment by PipoCanaja** [comment]
Hi,
Any news on this ? Currently there is no way to identify correctly such device, unfortunatly. Feel free to reopen this case if you get an update.

**Comment by PointPubMedia** [comment]
I think the issue can be fixed in librenms easily.... 
the problem is this line:
.1.3.6.1.2.1.1.5.0 = STRING: "oomAlert24E"

They put oomAlert24E instead of RoomAlert24E and it's probably why you are having issue to recognized this model compared to RoomAlert26E

**Comment by PipoCanaja** [comment]
.1.3.6.1.2.1.1.5.0 is the sysName, this information cannot be used. And we know that .1.3.6.1.2.1.1.2.0 (sysObjectID) is broken (and leads to wrong identification of chatworth-pdu. Only .1.3.6.1.2.1.1.1.0 seems to be really helping us identify this device family. 
But we need a way to avoid the collision with chatworth-pdu still.

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/roomalert-24e/11654/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11654
