### ISSUE TITLE
Spamtitan appliance

### ISSUE THREAD

**Issue by PointPubMedia** [librenms/librenms#8886]
Hi,

We are having 2 VMs running Spamtitan and they provides us the snmp to read to have some stats.

 In addition the following OIDs provide information on the size of the mail queues:

.1.3.6.1.4.1.2021.8.1.101.1 - Active Queue
.1.3.6.1.4.1.2021.8.1.101.2 - Incoming Queue
.1.3.6.1.4.1.2021.8.1.101.3 - Deferred Queue
.1.3.6.1.4.1.2021.8.1.101.4 - Corrupt Queue
.1.3.6.1.4.1.2021.8.1.101.5 - Hold Queue

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/spamtitan-appliance/11653/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11653
