### ISSUE TITLE
LibreNMS showing empty WebPage

### ISSUE THREAD

**Issue by macschon** [librenms/librenms#8892]
Since Yesterday my LibreNMS is not responding, when i click any menu bar, it show empty web page!
![screenshot 464](https://user-images.githubusercontent.com/41071492/42520488-cc7a3928-847f-11e8-8faa-7e89c69517d2.png)
![screenshot 466](https://user-images.githubusercontent.com/41071492/42521486-759cbef2-8482-11e8-9750-7d43a88d1654.png)

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
