### ISSUE TITLE
Cyberpower RMCARD305 (205)

### ISSUE THREAD

**Issue by PointPubMedia** [librenms/librenms#8894]
Trying to add our RMCARD305 into librenms but some graph are not correct like Voltage and current

https://p.libren.ms/view/1f6e983d
https://p.libren.ms/view/54a2edab
https://p.libren.ms/view/7a98d06f

**Comment by laf** [comment]
Can you please not remove the template when creating issues.

Do you have a mib available? Any idea what the OIDs are for the info you want? What's not correct about them

**Comment by PointPubMedia** [comment]
Here's the MIB file.

Have no idea about the OID we need but I think in the MIB file we have a bunch of thing that we can graph.
 
[MIB_v23.zip](https://github.com/librenms/librenms/files/2184168/MIB_v23.zip)

**Comment by davidmnelson** [comment]
@PointPubMedia Go to your CyberPower device in LibreNMS, click the gear icon at top right, click Edit, click SNMP, set it to v1, and save. I've seen the same problem and this fixes it for me.

**Comment by PointPubMedia** [comment]
Ohhh Just realized that I did a little mistake.  It's not a 305 but a 205 model.

And yes, using V1 works ;)

**Comment by PipoCanaja** [comment]
@PointPubMedia 
If setting the device to V1 works but not V2, there is probably a bug in the way the device replies and it will be difficult to correct it without access to the real device. 
Are you OK with the v1 support that is existing right now ? 
If not, could you investigate, as you have the real device, to find out what's wrong with v2 ?

**Comment by PointPubMedia** [comment]
Yeah I'm ok with v1.  It works perfectly as @davidmnelson  said back in august.

**Comment by PipoCanaja** [comment]
@murrant I used the snmpwalk provided in snmpsim and discovered that the translate script does not handle the SNMP "Opaque" data type. If I remove this Opaque line, the snmpwalk translates properly and snmpsim does his job. 
Wondering if this Opaque data could be also the reason why this (and possibly other) devices would work in v1 and not in v2 ?

**Comment by takenalias** [comment]
@PipoCanaja What do you mean by "Opaque" data type. I have one of these UPSs and have it running on snmpv2.

**Comment by murrant** [comment]
@PipoCanaja 1.3.6.1.2.1.33.1.1.3.0 (UPS-MIB::upsIdentUPSSoftwareVersion) should be of type string, soo, nice firmware bug there :D
I fixed the translate script to handle OPAQUE, since I'd never seen it in the wild.
