### ISSUE TITLE
BUG - test-template.php looks broken after #8803

### ISSUE THREAD

**Issue by PipoCanaja** [librenms/librenms#8901]
Hi,

Looks like test-template.php is broken after https://github.com/librenms/librenms/pull/8803 . I tried already most of my templates and rules, doesn't make a difference if the template syntax is the Old or the New one. 

librenms@srv:~$ ./scripts/test-template.php -t 5 -r 9  -h 3
PHP Fatal error:  Uncaught Error: Call to a member function connection() on null in /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1058
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1024): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(859): Illuminate\Database\Eloquent\Model->getConnection()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(818): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(802): Illuminate\Database\Eloquent\Model->newQueryWithoutScopes()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1374): Illuminate\Database\Eloquent\Model->newQuery()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1386): Illuminate\Database\Eloquent\Mod in /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1058

I'll try to narrow down the issue, and update this case.

Bye
PipoCanaja

**Comment by laf** [comment]
Bugs don’t go here
