### ISSUE TITLE
Create generic aggregated graphs

### ISSUE THREAD

**Issue by xpatux** [librenms/librenms#8921]
Hi,
I'm asking for this because #1003 was closed after been opened on librenmsv2 repository, that is actually archived and inactive about a year ago.

Can we put this feature request here?

I would be very useful that functionality with any datasource. But I think that would require sort of structural changes on code.

Is there a plan on this?

**Comment by kkrumm1** [comment]
Feature requests are made here https://community.librenms.org/c/feature-requests
