### ISSUE TITLE
Whitespace in OID in ceraos.inc.php temperature sensor

### ISSUE THREAD

**Issue by kimhaak** [librenms/librenms#8947]
librenms/includes/discovery/sensors/temperature/ceraos.inc.php

There is a whitespace in the OID variable that causes temp to come back as "0".

`$oid = ' .1.3.6.1.4.1.2281.10.1.1.9.0';`

I removed it locally and rediscovered device, worked ok.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

If you have a pull request to submit then please do that alternatively head over to discord.
