### ISSUE TITLE
Support HP iLO

### ISSUE THREAD

**Issue by 127-0-0-1** [librenms/librenms#895]
https://github.com/librenms/librenms/pull/898

**Comment by f0o** [comment]
Posting that patch is fairly contraproductive.

I smell another dmca complaint from adama if we implement hp ilo regardless of your posted patch...

One for @paulgear

**Comment by paulgear** [comment]
Agreed @f0o.  @127-0-0-1, please be aware that any code which is part of Observium or has been posted to Observium sites after svn r3250 is not allowed to be merged into LibreNMS.  Please see http://docs.librenms.org/General/Contributing/ for more information.  I will be deleting the above link shortly.

**Comment by 127-0-0-1** [comment]
Created pull request
https://github.com/librenms/librenms/pull/898

**Comment by paulgear** [comment]
Hi @127-0-0-1,
I'm sorry, but we really cannot accept your pull request.  Our contributor agreement (which you have not signed, as far as I have been able to determine) requires that you have not viewed Observium-licensed code in the process of producing it, which cannot be true in this case.  I will close the PR shortly.
If you would like to advance the project's lack of iLO support, please come and discuss it with us on the mailing list or IRC channel before producing any further code.
Regards,
Paul

**Comment by f0o** [comment]
Merged with #982
