### ISSUE TITLE
wrong sensor discovery for linux server hostname which contains "ntc"

### ISSUE THREAD

**Issue by tomarch** [librenms/librenms#8950]
Hi,

I've some linux server with the string "ntc" int the hostname (for exemple "server-montcherie").
The discovery find some sensors which don't exist.

The faulty code is this line : `if (preg_match("/(Linux).+(ntc)/", $device['sysDescr'])) {`
This line is present in this file:
includes/discovery/sensors/charge/linux.inc.php
includes/discovery/sensors/current/linux.inc.php
includes/discovery/sensors/temperature/linux.inc.php
includes/discovery/sensors/voltage/linux.inc.php

There's not test on the snmp_get result (it return "No Such Instance currently exists at this OID" in my case) before use the discover_sensor function.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
