### ISSUE TITLE
New device/OS: Audiocodes

### ISSUE THREAD

**Issue by tramontano** [librenms/librenms#8954]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

./validate.php
![image](https://user-images.githubusercontent.com/25436631/43280274-bfb60b18-90e6-11e8-8c51-1dde0ed25ec5.png)

Discovery: https://p.libren.ms/view/14166c09
Poller: https://p.libren.ms/view/a741b98f
Snmpwalk: https://p.libren.ms/view/b7c685b7

I've made some tests on a local server based on the link above, but I had no success, probably I'm missing a ton of codes to make it work properly.

**Comment by laf** [comment]
please do  not post links to observium.

You will need to upload the mibs to this issue.

**Comment by tramontano** [comment]
Sorry for that..
The mib files are attached.

Thanks.
[audiocodes.zip](https://github.com/librenms/librenms/files/2283175/audiocodes.zip)

**Comment by PipoCanaja** [comment]
Hello @tramontano 
I am currently working on code to discover audiocode devices. Could you let me know the kind of information you would like to see for your type of device ? 
Please provide me the OIDs directly (in textual form), as I don't have access to your device to do tests. 

Thanx

**Comment by PipoCanaja** [comment]
Hi @tramontano 

Please have a look to https://github.com/librenms/librenms/pull/9362 and let me know if you get the details you are interested in. If not, please send me your OIDs as well as an snmpbulkwalk of your device. 

Thanx

**Comment by PipoCanaja** [comment]
Generic support for audiocode was merged in https://github.com/librenms/librenms/pull/9508 .
