### ISSUE TITLE
renamehost.php loses all node data

### ISSUE THREAD

**Issue by paulgear** [librenms/librenms#896]
On a client test install, I found renaming hosts to be substantially broken; it loses *all* data for that host.  Digging into it a bit now.

**Comment by paulgear** [comment]
It looks like this is due to the rename directory failing.  Not sure why yet.

**Comment by f0o** [comment]
POSIX permissions?

**Comment by laf** [comment]
Is this not a local issue? All the rename does is does a dbUpdate and a move of the folder.

**Comment by paulgear** [comment]
Yeah - the code looks very simple; but the folder did not move correctly.  I'll investigate further as I have the opportunity.

**Comment by f0o** [comment]
Any updates?

**Comment by paulgear** [comment]
Nothing so far

**Comment by laf** [comment]
PR done to safety check the rename.
