### ISSUE TITLE
Device-Dependencies for Alerts

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#897]
Like discussed on the mailing-list (https://groups.google.com/forum/#!topic/librenms-project/SVb0vp2h28Y).

Alerts for devices that go down due to network dependencies on other devices should not be triggered if said top-level device is down.

This is not fully supported yet (without some macro-hacks), I will make this part of dynamic macro definitions.

The idea is to have a macro like `device_core123.localdomain_up` to be part of a rule.

I think it will be easier to implement a general-purpose dynamic macro interpreter instead of hardcoding special calls for these kind of operations. This way we can make rules depend on any other attribute/dataset that LibreNMS knows of.

**Comment by killsudo** [comment]
Zenoss does this via the BRIDGE-MIB and LLDP/CDP info.

Idea's for implementation / starting points can be researched at 

http://blog.zenoss.com/2014/10/new-layer-2-networking-zenpack-now-available/

http://wiki.zenoss.org/ZenPack:Layer2

https://github.com/zenoss/ZenPacks.zenoss.Layer2
