### ISSUE TITLE
Telegram transport stopped working

### ISSUE THREAD

**Issue by BlackListMe** [librenms/librenms#8972]
Hi,

I´ve configered transport for telegram and E-Mail a few weeks ago and everything worked fine so far. But since last week, libreNMS doesn´t transport the alerts via telegram anymore. 

-> Transport via Mail is working
-> Test transport for Telegram generates and successfully sends a message to the group it is configured to send to 
-> No configuration or any settings have been changed 
-> Deleted and reconfigured the transport method without any changes

Any Ideas?

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
