### ISSUE TITLE
Postgresql check

### ISSUE THREAD

**Issue by tboulogne** [librenms/librenms#899]
Hello,

Thanks for your great work. I discover your fork of observium just before install it :).
But i see librenms does not have the local agent to check postgresql as on observium. How could implement this please ?

Thanks for help.

Thierry

**Comment by tboulogne** [comment]
Hello,

I take the code from observium, make some change and make it work on Librenms. It could be interesting to put this into officially into LibreNMS. What do you think ?

Thanks

**Comment by laf** [comment]
Hi @tboulogne.

I'm afraid we can't accept code written for observium unless it was previously released as gplv3 compatible.

**Comment by tboulogne** [comment]
2 questions : how could us know the licence status of the code ? And what is the start point to consider a script is rewrite ? (to make it work i put lot of missing code)

**Comment by laf** [comment]
1. Most likely the license will be in the file, if it's not then you need to consider that it's licensed to Observium and as such we can't use it.

2. If you've based the rewrite off the Observium code then it's not going to work for us. It would need to be written from the ground up without you looking at the Observium code.

However, why not take a look at the postgresql agent from check_mk (https://mathias-kettner.de/checkmk_check_postgres_stat_database.html), the license is compatible for gplv3 and will most likely give you a foundation to get what you want. That can then be submitted :)

**Comment by tboulogne** [comment]
ok,

For now, i get something working for my production. But i will look into a clean solution compatible with GPLV3 when i will have some time to spend. :-)


Thanks for your time.
