### ISSUE TITLE
FortiMail not recognized

### ISSUE THREAD

**Issue by plepeer** [librenms/librenms#8994]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/f4f12dc3
https://p.libren.ms/view/a9e5a839
https://p.libren.ms/view/be9cb77f

- [x ] Please provide as much detail as possible.
Device is not recognized as a FortiMail appliance (in this case it is a virtual appliance).

![image](https://user-images.githubusercontent.com/32596693/43774517-a1be5522-9a49-11e8-9252-93e5949a0b8d.png)

Info on MIBS can be found here (if needed I can get the file for you): 
http://docs-legacy.fortinet.com/fmail/archives/3_0/fortimail-admin/wwhelp/wwhimpl/common/html/wwhelp.htm?context=FortiMail_Online_Help&file=FortiMail_Online_Help-07-19.html

- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by plepeer** [comment]
![image](https://user-images.githubusercontent.com/32596693/43774593-e96b1716-9a49-11e8-9647-49b93341dec3.png)

**Comment by plepeer** [comment]
Correct output of SNMPWalk
https://p.libren.ms/view/5aa54c24

**Comment by plepeer** [comment]
**Platform:**
.1.3.6.1.4.1.12356.105.1.1.0 = STRING: "FortiMail-VM"
**Operating System:**
.1.3.6.1.4.1.12356.105.1.3.0 = STRING: "v6.0,build91,180524 (6.0.0 GA)"

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/fortimail-not-recognized/11652/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11652
