### ISSUE TITLE
FortiNAC Appliance not recognized (formerly Bradford Network Sentry)

### ISSUE THREAD

**Issue by plepeer** [librenms/librenms#8995]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/55270c7e
https://p.libren.ms/view/e41dc3d1
https://p.libren.ms/view/0a8d9c03

- [ x] Please provide as much detail as possible.
Bradford is a NAC solution recently acquired by Fortinet (will be rebranded FortiNAC)
The system information is not displaying correctly. Can you please correct and add the Fortinet logo to it?

- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/fortinac-appliance-not-recognized-formerly-bradford-network-sentry/11651/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11651
