### ISSUE TITLE
DELL EMC SCv3020 Support

### ISSUE THREAD

**Issue by SwimmingFish849** [librenms/librenms#8998]
Hi,

Is it possible to have support for the DELL EMC SCv3020 storage unit? At the moment when adding it comes up as a generic FreeBSD device which doesn’t have a lot of information on it

Here are some of the snippets for you:
SNMP: https://p.libren.ms/view/eda1a4c1
Poller: https://p.libren.ms/view/643c848
Discovery: https://p.libren.ms/view/0e5c9e5d

I believe these are the MIBs for the EMC SCv3020: https://www.dell.com/support/home/uk/en/ukbsdt1/drivers/driversdetails?driverid=rdwfj

Cheers
Matt

**Comment by TheGreatDoc** [comment]
Hi @SwimmingFish849 ,

SNMP is OK but Poller link doesnt exists and the Discovery shows like device not found or something.
Can you recheck both, Discovery and Poller?

Thanks

**Comment by SwimmingFish849** [comment]
Sorry, try this link for the poller:
https://p.libren.ms/view/643c8481

I've re-checked both poller and discovery and getting the same outputs. I've also tried re-adding the device but still the same

Cheers

**Comment by SwimmingFish849** [comment]
Below are the latest runs of all three:
Poller: https://p.libren.ms/view/00e1e129
Discovery: https://p.libren.ms/view/b69e65dc
SNMP: https://p.libren.ms/view/c9a059bb

I'm still having issues with it not detecting anything

**Comment by SwimmingFish849** [comment]
Is there a way to progress this at all?

**Comment by laf** [comment]
You could add it yourself: https://docs.librenms.org/#Developing/Support-New-OS/

**Comment by SwimmingFish849** [comment]
Ah - thank you, I didn't realise. I'll do that - thanks

**Comment by SwimmingFish849** [comment]
I'm a little lost on where i'm going with this sorry, i've run the script mentioned in the above post and things started to go through fine and it then asked things like Do you want to add scAlertTable?

If I say Yes it then asks for Table Info and Value etc. Where do I find that info from?

In the MIB the only details relating to scAlertTable are:

--Alert Table --
    scAlertTable OBJECT-TYPE                            --table of Alert entries
        SYNTAX              SEQUENCE OF ScAlertEntry    --points def Alert entry
        MAX-ACCESS          not-accessible
        STATUS              current
        DESCRIPTION         "Alert Table"
        ::= { storageCenterObjects 46 }

    scAlertEntry OBJECT-TYPE                            --virtual object for Alert
        SYNTAX              ScAlertEntry                --is instance of Alert
        MAX-ACCESS          not-accessible
        STATUS              current
        DESCRIPTION         "an entry in scAlertTable"
        INDEX               {
                                scCtlrIndex,
                                scAlertIndex
                            }
        ::= { scAlertTable 1 }

**Comment by laf** [comment]
That depends on if that table has any data in you want, without the mib we can't really say.

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/dell-emc-scv3020-support/11674/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11674
