### ISSUE TITLE
Disabled ports show in the web ui

### ISSUE THREAD

**Issue by laf** [librenms/librenms#900]
Maybe we consider honouring observiums config option for this:

https://groups.google.com/forum/#!topic/librenms-project/SF5JiY_vscw

If set to false we hide the ports (true by default).

**Comment by exabrial** [comment]
Hmm... the "disabled" option in Observium may refer to "interface disabled" on the device, not the "disabled" (snmp polling) option in the UI.

However, if a device has a state of "notPresent" it just crowds the UI.  The SG500 can have 4 devices in a stack, and there are Fast Ethernet and Gigabit ethernet models. So it has monitoring OIDs for 8 devices, with 52 ports each, leading to an absolute metric crap of load of interfaces (800ish) in the LibreNMS UI.

I would say: just ignore "notPresent" interfaces: Don't poll, don't alert, and don't display them anywhere in the UI.

**Comment by laf** [comment]
The config option you referred to to me says show disabled ports in web ui if set to TRUE.

Not actually recording interfaces that are notPresent is a different thing imho.

**Comment by exabrial** [comment]
That's honestly what the original issue was... Can the author of this ticket change the description?

**Comment by laf** [comment]
I've closed this issue down. Feel free to create a new one with details on the problem.
