### ISSUE TITLE
AD authorization doesn't work

### ISSUE THREAD

**Issue by CZAirwolf** [librenms/librenms#9008]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
LibreNMS  | 1.42.01
DB Schema | 257
PHP       | 7.0.19-1
MySQL     | 10.1.26-MariaDB-0+deb9u1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3

- [x ] Please provide as much detail as possible.
With ":1.2.840.113556.1.4.1941:" inside search filters can't validate other username (binding user works): 
Error: LibreNMS\Exceptions\AuthenticationException thrown!
User is not in one of the required groups or user/group is outside the base dn

Testing with LDAP explorer proved, that this search string doesn't work (search error etc).

Removing this string from filter -> AD auth works again. 
 ActiveDirectoryAuthorizer.php 
-            "(&" . static::userFilter($username) . "(memberOf:1.2.840.113556.1.4.1941:=$group_dn))",
+           "(&" . static::userFilter($username) . "(memberOf=$group_dn))",

- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
