### ISSUE TITLE
Problem with new os devices.

### ISSUE THREAD

**Issue by ArtemKabanov** [librenms/librenms#9009]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations
We have a few Qtech switches on our network. And all this devices are "generic". 
I follow https://docs.librenms.org/#Developing/Support-New-OS/
Take this mib ftp://ftp.qtech.ru/Switch/Access/QSW-2800/MIB's/Qtech_private_2.1.26.mib
https://pastebin.com/tLjtCTKH
Can you help me. What am I doing wrong?

**Comment by laf** [comment]
As you are part way through adding a new os, please just submit a pull request and we can help you there.
