### ISSUE TITLE
Cisco FirePOWER FPR-2130 - Shown as generic device

### ISSUE THREAD

**Issue by norrlandskatten** [librenms/librenms#9012]
Cisco FirePOWER FPR-2130 is not identified as firewall. It comes up as a 'Generic device'.

./discovery.php
https://p.libren.ms/view/2154fa1d

./poller.php
https://p.libren.ms/view/f9108cee

snmpbulkwalk
See attached file. Couldn't add it to pastebin as it was to large.
[snmpbulkwalk.zip](https://github.com/librenms/librenms/files/2285884/snmpbulkwalk.zip)

I tried to remove os_defs.cache and rediscover the device, as sugested here https://github.com/librenms/librenms/issues/7783, but with the same result.

**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
We've covered this one before: https://github.com/librenms/librenms/issues/4524

Never seemed to be a sane way to add support.

**Comment by norrlandskatten** [comment]
It does indeed make your head spin.

I also have a "linux vm" - see output below. I'm not sure how it ties in to the other stuff, I was of the impression that it was only used for management of the actual firewalls.

./discovery.php
https://p.libren.ms/view/bef9f6ef

./poller.php
https://p.libren.ms/view/a62f84f0

snmpbulkwalk
https://p.libren.ms/view/8a84d78d

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11650

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/cisco-firepower-fpr-2130-shown-as-generic-device/11650/1
