### ISSUE TITLE
installed rrdcached and now I get error drawing graph

### ISSUE THREAD

**Issue by hrv231** [librenms/librenms#9028]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
Hello,
I'm having the latest debian running the latest nginx with librenms, everything has been working great so far until I decided to optimize LibreNMS with rrdcached, now I get this from RRD command:

```
RRDTool Command

rrdtool graph /tmp/dDMMPjZ2uDidGe01  --alt-autoscale-max --rigid -E --start 1534441200 --end 1534527600 --width 1843.2 --height 508 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal DEF:outoctets=/opt/librenms/rrd/localhost/port-id399.rrd:OUTOCTETS:AVERAGE DEF:inoctets=/opt/librenms/rrd/localhost/port-id399.rrd:INOCTETS:AVERAGE DEF:outoctets_max=/opt/librenms/rrd/localhost/port-id399.rrd:OUTOCTETS:MAX DEF:inoctets_max=/opt/librenms/rrd/localhost/port-id399.rrd:INOCTETS:MAX CDEF:octets=inoctets,outoctets,+ CDEF:doutoctets=outoctets,-1,* CDEF:outbits=outoctets,8,* CDEF:outbits_max=outoctets_max,8,* CDEF:doutoctets_max=outoctets_max,-1,* CDEF:doutbits=doutoctets,8,* CDEF:doutbits_max=doutoctets_max,8,* CDEF:inbits=inoctets,8,* CDEF:inbits_max=inoctets_max,8,* VDEF:totin=inoctets,TOTAL VDEF:totout=outoctets,TOTAL VDEF:tot=octets,TOTAL CDEF:dpercentile_outn=doutbits,-1,* VDEF:dpercentile_outnp=dpercentile_outn,95,PERCENT CDEF:dpercentile_outnpn=doutbits,doutbits,-,dpercentile_outnp,-1,*,+ VDEF:dpercentile_out=dpercentile_outnpn,FIRST VDEF:percentile_in=inbits,95,PERCENT VDEF:percentile_out=outbits,95,PERCENT COMMENT:'bps      Now       Ave      Max      95th %\n' AREA:inbits_max#D7FFC7: AREA:inbits#90B040: LINE:inbits#608720:'In ' GPRINT:inbits:LAST:%6.2lf%s GPRINT:inbits:AVERAGE:%6.2lf%s GPRINT:inbits_max:MAX:%6.2lf%s GPRINT:percentile_in:%6.2lf%s\n AREA:doutbits_max#E0E0FF: AREA:doutbits#8080C0: LINE:doutbits#606090:'Out' GPRINT:outbits:LAST:%6.2lf%s GPRINT:outbits:AVERAGE:%6.2lf%s GPRINT:outbits_max:MAX:%6.2lf%s GPRINT:percentile_out:%6.2lf%s\n GPRINT:tot:'Total %6.2lf%sB' GPRINT:totin:'(In %6.2lf%sB' GPRINT:totout:'Out %6.2lf%sB)\l' LINE1:percentile_in#aa0000 LINE1:dpercentile_out#aa0000
RRDTool Output

ERROR: rrdcached: /opt/librenms/rrd/localhost/port-id399.rrd: Permission denied
```

- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

The thing is that I followed everything by the docs and I don't understand why is not working. I see permision denied, by who?

When I remove the following two lines from the config.php file everything goes back to normal and shows my graphs:
$config['rrdcached']    = "unix:/var/run/rrdcached.sock";
$config['rrdtool_version'] = '1.6.0';

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
