### ISSUE TITLE
ignore_mount_(removable|network|optical) work differently then suggested in the docs

### ISSUE THREAD

**Issue by simplexify** [librenms/librenms#9047]
The behaviour of the following ignore_mount configuration options as suggested by the documentation is different from the actual behaviour.

```
$config['ignore_mount_removable']  = 1;
$config['ignore_mount_network']    = 1;
$config['ignore_mount_optical']    = 1;
```

Based on the wording of the configuration option (and the docs: https://docs.librenms.org/#Support/Configuration/#storage-configuration), setting these configuration options to 1 (true) seems to suggest that true = enable the ignore option.

The observed behaviour however, is that these options need to be set to 0 for the ignore option to be enabled.

When inspecting the code in includes/discovery/storage/hrstorage.inc.php, this observed behaviour was confirmed:

```
        if (Config::get('ignore_mount_removable', false) && $fstype == 'hrStorageRemovableDisk') {
            d_echo("skip(removable)\n");
            continue;
        }

        if (Config::get('ignore_mount_network', false) && $fstype == 'hrStorageNetworkDisk') {
            d_echo("skip(network)\n");
            continue;
        }

        if (Config::get('ignore_mount_optical', false) && $fstype == 'hrStorageCompactDisc') {
            d_echo("skip(cd)\n");
            continue;
        }
```

Assuming that the intended behaviour is for '1' = enabled, it would appear the above code needs to be updated to say true instead of false?

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

If you have a pull request to submit then please do this, discussing code changes is easier in a pull request.
