### ISSUE TITLE
ArubaOS 8 Support

### ISSUE THREAD

**Issue by mzac** [librenms/librenms#9058]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ X] Please provide as much detail as possible.
- [ X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

This is to add sensors and other supported MIBs for ArubaOS 8.  This OS is quite different from previous Aruba OS versions.

Discovery: https://p.libren.ms/view/9c9c8f50
Poller: https://p.libren.ms/view/b1ceae8d
snmpbulkwalk: Will attach file

Mibs will be attached

**Comment by mzac** [comment]
[aruba-mibs_8.3.0.2_66308.tar.gz](https://github.com/librenms/librenms/files/2311257/aruba-mibs_8.3.0.2_66308.tar.gz)
[arubaos8-snmpwalk.txt](https://github.com/librenms/librenms/files/2311258/arubaos8-snmpwalk.txt)
[standard-mibs_8.3.0.2_66308.tar.gz](https://github.com/librenms/librenms/files/2311259/standard-mibs_8.3.0.2_66308.tar.gz)

**Comment by laf** [comment]
Please provide information on what health information / sensors you want to see data for. Please also provide the OIDs.

**Comment by mzac** [comment]
Here is what I have found, there are probably more but this is a good start.

- All CPUs
1.3.6.1.4.1.14823.2.2.1.1.1
enterprises.14823.2.2.1.1.1.9.1.2.1 = STRING: "Supervisor Card CPU"
enterprises.14823.2.2.1.1.1.9.1.2.8 = STRING: "Network Processor CPU8"
enterprises.14823.2.2.1.1.1.9.1.2.9 = STRING: "Network Processor CPU9"
enterprises.14823.2.2.1.1.1.9.1.2.10 = STRING: "Network Processor CPU10"
enterprises.14823.2.2.1.1.1.9.1.2.11 = STRING: "Network Processor CPU11"
enterprises.14823.2.2.1.1.1.9.1.2.12 = STRING: "Network Processor CPU12"
enterprises.14823.2.2.1.1.1.9.1.2.13 = STRING: "Network Processor CPU13"
enterprises.14823.2.2.1.1.1.9.1.2.14 = STRING: "Network Processor CPU14"
enterprises.14823.2.2.1.1.1.9.1.2.15 = STRING: "Network Processor CPU15"
enterprises.14823.2.2.1.1.1.9.1.2.16 = STRING: "Network Processor CPU16"
enterprises.14823.2.2.1.1.1.9.1.2.17 = STRING: "Network Processor CPU17"
enterprises.14823.2.2.1.1.1.9.1.2.18 = STRING: "Network Processor CPU18"
enterprises.14823.2.2.1.1.1.9.1.2.19 = STRING: "Network Processor CPU19"
enterprises.14823.2.2.1.1.1.9.1.2.20 = STRING: "Network Processor CPU20"
enterprises.14823.2.2.1.1.1.9.1.2.21 = STRING: "Network Processor CPU21"
enterprises.14823.2.2.1.1.1.9.1.2.22 = STRING: "Network Processor CPU22"
enterprises.14823.2.2.1.1.1.9.1.2.23 = STRING: "Network Processor CPU23"
enterprises.14823.2.2.1.1.1.9.1.2.24 = STRING: "Network Processor CPU24"
enterprises.14823.2.2.1.1.1.9.1.2.25 = STRING: "Network Processor CPU25"
enterprises.14823.2.2.1.1.1.9.1.2.26 = STRING: "Network Processor CPU26"
enterprises.14823.2.2.1.1.1.9.1.2.27 = STRING: "Network Processor CPU27"
enterprises.14823.2.2.1.1.1.9.1.2.28 = STRING: "Network Processor CPU28"
enterprises.14823.2.2.1.1.1.9.1.2.29 = STRING: "Network Processor CPU29"
enterprises.14823.2.2.1.1.1.9.1.2.30 = STRING: "Network Processor CPU30"
enterprises.14823.2.2.1.1.1.9.1.2.31 = STRING: "Network Processor CPU31"
enterprises.14823.2.2.1.1.1.9.1.3.1 = INTEGER: 2
enterprises.14823.2.2.1.1.1.9.1.3.8 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.9 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.10 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.11 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.12 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.13 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.14 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.15 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.16 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.17 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.18 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.19 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.20 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.21 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.22 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.23 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.24 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.25 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.26 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.27 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.28 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.29 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.30 = INTEGER: 0
enterprises.14823.2.2.1.1.1.9.1.3.31 = INTEGER: 0

- Fan status
1.3.6.1.4.1.14823.2.2.1.2.1.17
enterprises.14823.2.2.1.2.1.17.1.2.0 = INTEGER: 1
enterprises.14823.2.2.1.2.1.17.1.2.1 = INTEGER: 1
enterprises.14823.2.2.1.2.1.17.1.2.2 = INTEGER: 1
enterprises.14823.2.2.1.2.1.17.1.2.3 = INTEGER: 1

- Power supply
1.3.6.1.4.1.14823.2.2.1.2.1.18
enterprises.14823.2.2.1.2.1.18.1.2.0 = INTEGER: 1
enterprises.14823.2.2.1.2.1.18.1.2.1 = INTEGER: 1

- Temperature
1.3.6.1.4.1.14823.2.2.1.2.1.10.0
enterprises.14823.2.2.1.2.1.10.0 = STRING: "28.00 degrees Celsius (NORMAL)"

- Storage
1.3.6.1.4.1.14823.2.2.1.2.1.14
enterprises.14823.2.2.1.2.1.14.1.2.1 = INTEGER: 1
enterprises.14823.2.2.1.2.1.14.1.2.2 = INTEGER: 1
enterprises.14823.2.2.1.2.1.14.1.2.3 = INTEGER: 1
enterprises.14823.2.2.1.2.1.14.1.2.4 = INTEGER: 2
enterprises.14823.2.2.1.2.1.14.1.2.5 = INTEGER: 2
enterprises.14823.2.2.1.2.1.14.1.3.1 = INTEGER: 2048
enterprises.14823.2.2.1.2.1.14.1.3.2 = INTEGER: 2048
enterprises.14823.2.2.1.2.1.14.1.3.3 = INTEGER: 300
enterprises.14823.2.2.1.2.1.14.1.3.4 = INTEGER: 1535
enterprises.14823.2.2.1.2.1.14.1.3.5 = INTEGER: 5713
enterprises.14823.2.2.1.2.1.14.1.4.1 = INTEGER: 870
enterprises.14823.2.2.1.2.1.14.1.4.2 = INTEGER: 12
enterprises.14823.2.2.1.2.1.14.1.4.3 = INTEGER: 14
enterprises.14823.2.2.1.2.1.14.1.4.4 = INTEGER: 292
enterprises.14823.2.2.1.2.1.14.1.4.5 = INTEGER: 322
enterprises.14823.2.2.1.2.1.14.1.5.1 = STRING: "/"
enterprises.14823.2.2.1.2.1.14.1.5.2 = STRING: "/tmp"
enterprises.14823.2.2.1.2.1.14.1.5.3 = STRING: "/var"
enterprises.14823.2.2.1.2.1.14.1.5.4 = STRING: "/flash"
enterprises.14823.2.2.1.2.1.14.1.5.5 = STRING: "/flash1"

- Number of associated wireless clients
1.3.6.1.4.1.14823.2.2.1.1.3.2.0
enterprises.14823.2.2.1.1.3.2.0 = Gauge32: 558

- Number of access points
1.3.6.1.4.1.14823.2.2.1.1.3.1.0
enterprises.14823.2.2.1.1.3.1.0 = Gauge32: 317

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/arubaos-8-support/11649/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11649
