### ISSUE TITLE
Tycon TPDIN WEB1 - Device add request.

### ISSUE THREAD

**Issue by wispquest** [librenms/librenms#9063]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

Discovery - https://p.libren.ms/view/4a2e32ef

Polling - https://p.libren.ms/view/f352ea2f

SNMP Bulk Walk - https://p.libren.ms/view/e9aed8f2

MIB Link - http://tyconsystems.com/Assets/TPDIN%20Firmware/SNMP%20MIB%20File.txt

- [ X] Please provide as much detail as possible.

There is already a Tycon device supported but this is version 2. I am requesting the version 1 device be added which has completely different ID's, OID's and MIB.

The device OS is incorrectly detected as "ServerCheck"

- [ X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/tycon-tpdin-web1-device-add-request/11648/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11648
