### ISSUE TITLE
Cisco ESW-540-8P (Cisco Small Business) recognized as Generic device

### ISSUE THREAD

**Issue by pojlFDlxCOvZ4Kg8y1l4** [librenms/librenms#9065]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
Discovery: https://p.libren.ms/view/f36847a1
Poller: https://p.libren.ms/view/fbc8ce56
SNMPwalk debug output: https://paste.tech-port.de/?7072c13c52a8ee58#83/a61Wdo+Z2G4SocfmvJT8wcbz3zkG8fEwVRjxojdo= 
I did have some trouble with running the script in the FAQ, is this the output you guys need?
- [X] Please provide as much detail as possible.
Auto discovery adds the switch as a generic device. Disabling SNMP and manually setting the devices' Operating System to "Cisco Small Business" works.
Re-enabling SNMP again works, until the next discovery. That will make the device generic again.
With the switch recognized as generic all interface&VLAN assignments are not recognized properly, e.g. ports g1-g9 all carry the same "Ethernet Interface" name.
With SNMP enabled and Port Association Mode set to ifName (or any other possible value in the given list) the results are the same.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Your output shows this being picked up as cisco smb: https://p.libren.ms/view/fbc8ce56#L21

However, you need to post the snmpwalk for us to look into this more.

**Comment by pojlFDlxCOvZ4Kg8y1l4** [comment]
Updated the first comment with a SNMPwalk pastebin.

**Comment by pojlFDlxCOvZ4Kg8y1l4** [comment]
I've updated the SNMP walk, since the previous link got wiped: 
SNMP: https://pasta.xanderbron.tech/?95444337123f5328#oKlHIsteQUgHpuVuucY2LPbkNIgQqw3a8MZdK4ZFmAk=

And while I was doing that anyways, here's a current discovery and poller walk: 

Discovery: https://pasta.xanderbron.tech/?ab96cdcb653e9919#pr2TJ7iWMcKSrLfxJ3nKs/oG2MqG68Bs88FApCptQao=

Poller: https://pasta.xanderbron.tech/?f57e23ebd99e66fe#dF47mOc2u4roMFDQ7e72bLjG9VlSSkoq0UPIKblDhxg=

**Comment by PipoCanaja** [comment]
Could you use librenms pastbin command instead of xanderbron ? The data you posted is not accessible for some reason. 
Thanx

**Comment by pojlFDlxCOvZ4Kg8y1l4** [comment]
Hi! 
Sorry, I just moved, and the server which ran the pastebin service was offline becaufe of it. 
The pastebin service is behind a geofilter though, US, UK, NL and DE are allowed. 
I've tried it several times since opening this thread, but I keep ending up with nothing but this output: 

Librenms@home-ct-librenms:~$ snmpbulkwalk -OUneb -v2c -c SNMPCOMMUNITY IP . | ./p
bin.sh                                                                                         
Paste endpoint: https://p.libren.ms/api/create                                                 
 title:                                                                                        
name: librenms                                                                                 
private: 1                                                                                     
expire: 0                                                                                      
Error: Missing paste text                                                                      
librenms@home-ct-librenms:~$

Do you know how I can fix this, or how I can upload the snmpwalk manually?

**Comment by PipoCanaja** [comment]
I have now access to the data, will have a look.

**Comment by PipoCanaja** [comment]
@pojlFDlxCOvZ4Kg8y1l4  data is still not complete. Please attach the snmpwalk txt file directly to this issue.

**Comment by laf** [comment]
`SNMPCOMMUNITY` and `IP` should be replaced with the correct details, not sure if you've just masked them. But the error message `Missing paste text` means the snmpbulkwalk command didn't work.

**Comment by laf** [comment]
I've added a PR which might fix this, test info is in the PR: https://github.com/librenms/librenms/pull/10077
