### ISSUE TITLE
Request Support for LigoWave Rapid Fire 5N PTP Radio

### ISSUE THREAD

**Issue by payso8848** [librenms/librenms#9070]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

- [ x] Please provide as much detail as possible.
Ligowave 5-N Rapid Fire PTP Radio.  MIB File: https://www.ligowave.com/wiki/wp-content/uploads/Ligowave-MIBS.zip
First two Octets of IP addresses have been replaced with 000.000.
Ligowave MIB support page https://www.ligowave.com/wiki/faq/ligoptp-how-to-find-oids-and-use-mibs/

- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery https://pastebin.com/ERufDmsw
Poller https://pastebin.com/y74aPr0W
SNMP Walk https://pastebin.com/WtzNPxHT

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11647

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/request-support-for-ligowave-rapid-fire-5n-ptp-radio/11647/1
