### ISSUE TITLE
Ditek UPS - New Device Request

### ISSUE THREAD

**Issue by tomck** [librenms/librenms#9071]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
Discovery: https://p.libren.ms/view/736d7269
Poller: https://p.libren.ms/view/9803964f
snmpbulkwalk: https://p.libren.ms/view/679df8c9
- [x] Please provide as much detail as possible. (two screenshots attached, hoping you can use it to line up data?)
This seems to be the manual, looks like the same interface: http://docplayer.net/30336062-Snmp-web-pro-user-s-manual-management-software-for-uninterruptible-power-supply-systems.html

![screenshot_2018-08-27 snmp web pro](https://user-images.githubusercontent.com/324521/44683178-23653e80-aa0b-11e8-87b7-867d5b5750ab.png)
![screenshot_2018-08-27 snmp web pro 1](https://user-images.githubusercontent.com/324521/44683189-2ceea680-aa0b-11e8-8010-d6722501552e.png)
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

We just bought a Ditek UPS which has SNMP that does not seem to be in Libre. The MIB is here, I don't know if they have others but from their info this is the one for our specific device.

https://www.diteksurgeprotection.com/ups-software/send/32-ups-software/675-rfc1628-mib.html

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by tomck** [comment]
@laf requesting reopen please

**Comment by PipoCanaja** [comment]
Hello @tomck 
This device is now supported via the "Orvaldi" UPS definition. Please reopen if necessary.
Bye
