### ISSUE TITLE
Morningstar Solar Monitor - Device Add Request

### ISSUE THREAD

**Issue by wispquest** [librenms/librenms#9076]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

Discovery - https://p.libren.ms/view/18ca03d4

Polling - https://p.libren.ms/view/c00281f6

Standard SNMP Walk (v1) - https://p.libren.ms/view/40446d71

MIB - http://24.182.13.172:8125/TSMPPTMIB.zip

LOGO - [Morningstar.zip](https://github.com/librenms/librenms/files/2319321/Morningstar.zip)

- [X ] Please provide as much detail as possible.

Device is a Solar power monitor. Currently detected as "Generic Device"

- [ X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11646

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/morningstar-solar-monitor-device-add-request/11646/1
