### ISSUE TITLE
how to get in/out interface traffic trough API

### ISSUE THREAD

**Issue by MeloGit** [librenms/librenms#9113]
Hi everybody,
I'm a beginner in **Librenms API** and I'm trying to get in/out interface traffic values for knowing when during day the interface traffic reach the peak or the maximum of his capacity.
Please I need your help for this issue.

Best regards.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
