### ISSUE TITLE
Support for new device Fiberstore Switches

### ISSUE THREAD

**Issue by sp1rr3** [librenms/librenms#9117]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Hi, 
Please add support for Fiberstore switches this one is a S5850-48T4Q right now its added as a generic device and missing sensors.

discovery.php output - https://p.libren.ms/view/a4134bad
poller.php output - https://p.libren.ms/view/da1a55b4
snmpwalk output - Gets a crash from database with command provided in FAQ

**Comment by laf** [comment]
We need the snmpwalk I'm afraid.

**Comment by murrant** [comment]
Did you try snmpwalk instead of snmpbulkwalk?

**Comment by sp1rr3** [comment]
Here comes the snmpwalk it seems as its the pbin that crashes.
[snmpwalk.txt](https://github.com/librenms/librenms/files/2359902/snmpwalk.txt)

**Comment by murrant** [comment]
This is for a `APC Web/SNMP Management Card`

**Comment by sp1rr3** [comment]
Damm sorry, same filename diffrent folder... here is the correct one.
[snmpwalk.txt](https://github.com/librenms/librenms/files/2361953/snmpwalk.txt)

**Comment by PipoCanaja** [comment]
hi @sp1rr3 
Do you have the mib files for these devices ? 
Thanx
PipoCanaja

**Comment by tsumaru720** [comment]
@PipoCanaja  Depends on the specific model
Vendor has MIBs for S2800 and S3800 available - Can provide a direct download URL from their site if you like?

**Comment by PipoCanaja** [comment]
That would be a good beginning yes. I searched on their website with no success so far.

**Comment by tsumaru720** [comment]
https://img-en.fs.com/file/user_manual/fs-s3800-mibs.zip

**Comment by tsumaru720** [comment]
I think the device I have, whilst is FS.com - wont be detected with your current proposed definition - possibly needs a different OID adding to the FS.yaml? 

`system object id       : 1.3.6.1.4.1.13464.1.3.32.1
`

Attached an SNMP walk from mine which is a S2800-24T4F
[snmp.txt](https://github.com/librenms/librenms/files/2796296/snmp.txt)

**Comment by tsumaru720** [comment]
s5850 for the op
https://img-en.fs.com/file/user_manual/fs-s5850-mibs.zip

**Comment by PipoCanaja** [comment]
Hi,
Thanx for mib files. I did add all the one I could but some are still missing (for the s2800 device for instance, some OIDs are not found in the files we have). 
Anyway, I think we can start from here, and I encourage owner of these devices to contribute code while they have the device in their hands. 
PipoCanaja

**Comment by tsumaru720** [comment]
I've never done a "new os" before, but happy to contribute if I'm given some direction as to what i need to do :D

**Comment by PipoCanaja** [comment]
Basically, you should not even have to create a new one, but only add sensors or data to the discovery process. 

Before that, may be, could you collect snmpwalk for each of your FS devices models ? 
snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh

**Comment by cppmonkey** [comment]
Wish they'd release the mibs for the EDFA/OEO/OLP devices.
Not keen on using Windows only, proprietary software.

We have mibs for 2 revisions, but there are all kinds of errors and mistake in them and half the devices can't be read correctly. Presume that is because we have different card versions?

https://github.com/cppmonkey/librenms/tree/tryin

I am interested to know what you make of these switches though. And have you found the ODM?

Would be happy to help, need to get my head around snmpsim to work on some of FS equipment.

Best of luck

**Comment by daandersson** [comment]
@PipoCanaja I tried to do snmpbulkwalk on our two stacked S3800. I tried -v1 -v2c and -v3 but all give error below. Not always on the exact same OID. Not sure what this can be. Faulty implementation of SNMP in the switches?

Error in packet.
Reason: (genError) A general failure occured
Failed object: .1.3.6.1.2.1.17.6.1.2.1.1.1.16

I uploaded the data anyway, but I suspect snmpbulkwalk was aborted at the failing OID so the run may not be complete.

https://p.libren.ms/view/4d82238f

**Comment by PipoCanaja** [comment]
@daandersson The file seems is as you suspected not complete. None of the specific FS oids are there, so there is nothing we can add to the discovery. 
@cppmonkey The mib file is already in the current PR. Could you run snmpwalk as requested in the Issue, but with an increased timeout value ? 
  snmpbulkwalk -OUneb -v2c -t 20 -c COMMUNITY HOSTNAME .  | ./pbin.sh

If it fails, you could also try :
  snmpwalk -OUneb -v2c -t 20 -c COMMUNITY HOSTNAME .  | ./pbin.sh

We'll see if we get more data.

**Comment by cppmonkey** [comment]
@PipoCanaja I'm just an interested party. I don't have any of the FS switches. Only the DWDM equipment

**Comment by daandersson** [comment]
@PipoCanaja I did some more testing on the S3800s. It seems that this device does not handle snmpbulkwalk nor snmpwalk very well. As far as I can see, the errors always accur on OIDs that are outside the scope of OIDs that are documented by FS (linked by tsumaru720 above). I have issued a support ticket to FS about it. 

For now I instead run snmpwalk on each one of the sub-OIDs documented by FS. Some of the snmpwalks ends in error, but all OIDs in FS document is included. Is it possible for you to use this?

https://p.libren.ms/view/c1529f8a

**Comment by PipoCanaja** [comment]
It seems very buggy indeed. I did some cleaning of the MIB to get it compiling in snmpwalk. 
We now poll the Hardware. software version and the Serial Number, as well as CPU and Memory.

**Comment by PipoCanaja** [comment]
@daandersson 
Could you please try to apply the patch 9734 and see how it goes. Wondering if the real device works now that I get something on the snmpwalk fake data. 

![capture d ecran 2019-01-27 a 23 27 54](https://user-images.githubusercontent.com/38363551/51807788-e0deb100-228b-11e9-84fd-ca8c977c216e.png)

**Comment by daandersson** [comment]
@PipoCanaja I applied patch
`$ sudo ./scripts/github-apply 9734`
then run a new discovery both in UI and with
`$ sudo ./discovery.php -h 3`

Switch is still detected as generic OS, did I do something wrong?

#### Load disco module os ####
OS: Generic Device (generic)
>> Runtime for discovery module 'os': 0.2180 seconds with 9224 bytes
>> SNMP: [3/0.21s] MySQL: [0/0.00s] RRD: [0/0.00s]
#### Unload disco module os ####

**Comment by PipoCanaja** [comment]
try to remove the cache : 
rm ./cache/os_defs.cache

And then run the discovery again.

**Comment by PipoCanaja** [comment]
Did you remove the cache file an run a normal discovery (without the -m os) ?

**Comment by sp1rr3** [comment]
Hi,
I have applied the patch and on my s5850 switches it changes the os. 
but not my 5800. (here is the mib for that one: https://img-en.fs.com/file/user_manual/fs-s5800-8tf12s-mibs.zip ) (model: S5800 8TF12S) can you add that one to please.

**Comment by tsumaru720** [comment]
@sp1rr3 What does "show version" give you for the system object id for the s5800 ?

@PipoCanaja if i apply the patch to test against my s2800, how do i "unapply" it to go back to main after finishing testing?

**Comment by daandersson** [comment]
@PipoCanaja I did not remove the cache before. Tried it now and after that discover.php -h all but as far as I can see there is no difference in how the S3800 switch is presented in UI.

**Comment by sp1rr3** [comment]
@daandersson i removed the cache file and did ./discovery.php -m os -h all and it changed 2 of mine.
@tsumaru720 :
switch-1# show ver
FSOS Software, S5800, Version 5.3.7
Copyright (C) Fiberstore Inc.  All rights reserved.
The current running image is flash:/boot/FSOS-S5800-8-12-v5.3.7.r.bin
Hardware Type is 8TF12S
Hardware Version is 2.0
SDRAM size 1024M
Flash size 2048M
EPLD Version is 1.2
BootRom Version is 7.1.4
Current Web Version is 5.3.7

In Libre: Object ID.1.3.6.1.4.1.27975.99.263

**Comment by daandersson** [comment]
@sp1rr3 the OS changes to FS, this is not the problem on S3800. The problem I have is that memory utilization is not shown as it does for @PipoCanaja in his test (without real switch).

**Comment by PipoCanaja** [comment]
@daandersson @sp1rr3 
The memory should be solved now. Please refresh the patch.

**Comment by PipoCanaja** [comment]
@tsumaru720 
You can refresh, at least you should get the FS logo. 

Please collect snmpwalk as written here and I'll check how it goes with this device : 
https://docs.librenms.org/Support/FAQ/#faq20

**Comment by PipoCanaja** [comment]
You can try again for device 5800. Should get processor and S/N. Memory should be possible as well but will be done later.

**Comment by sp1rr3** [comment]
`root@librenms:/opt/librenms# sudo ./scripts/github-apply 9734
<stdin>:66: trailing whitespace.
                '.1.3.6.1.4.1.27975.1.2.11.' . $index,
<stdin>:82: trailing whitespace.
<?xml version="1.0" encoding="utf-8"?>
<stdin>:83: trailing whitespace.

<stdin>:84: trailing whitespace.
<svg version="1.1" id="åå±_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
<stdin>:85: trailing whitespace.
         viewBox="0 0 275.8 67.3" style="enable-background:new 0 0 275.8 67.3;" xml:space="preserve">
Checking patch LibreNMS/OS/Fs.php...
error: LibreNMS/OS/Fs.php: already exists in working directory
Checking patch html/images/os/fs.svg...
error: html/images/os/fs.svg: already exists in working directory
Checking patch includes/definitions/fs.yaml...
error: includes/definitions/fs.yaml: already exists in working directory
Checking patch includes/discovery/mempools/fs.inc.php...
error: includes/discovery/mempools/fs.inc.php: already exists in working directory
Checking patch includes/polling/mempools/fs-switchmib.inc.php...
Checking patch includes/polling/mempools/fs.inc.php...
error: includes/polling/mempools/fs.inc.php: already exists in working directory
Checking patch includes/polling/os/fs.inc.php...
error: includes/polling/os/fs.inc.php: already exists in working directory
Checking patch mibs/MGMD-STD-MIB...
error: mibs/MGMD-STD-MIB: already exists in working directory
Checking patch mibs/MSTP-MIB...
error: mibs/MSTP-MIB: already exists in working directory
Checking patch mibs/STP-MIB...
error: mibs/STP-MIB: already exists in working directory
Checking patch mibs/fs/ADMIN-MASTER-MIB...
error: mibs/fs/ADMIN-MASTER-MIB: already exists in working directory
Checking patch mibs/fs/ERRP-MIB...
error: mibs/fs/ERRP-MIB: already exists in working directory
Checking patch mibs/fs/GARP-MIB...
error: mibs/fs/GARP-MIB: already exists in working directory
Checking patch mibs/fs/GBNDeviceOEM-MIB...
error: mibs/fs/GBNDeviceOEM-MIB: already exists in working directory
Checking patch mibs/fs/GBNDevicePoe-MIB...
error: mibs/fs/GBNDevicePoe-MIB: already exists in working directory
Checking patch mibs/fs/GBNDeviceSWAPI-MIB...
error: mibs/fs/GBNDeviceSWAPI-MIB: already exists in working directory
Checking patch mibs/fs/GBNDeviceStack-MIB...
error: mibs/fs/GBNDeviceStack-MIB: already exists in working directory
Checking patch mibs/fs/GBNDeviceSwitch-MIB...
error: mibs/fs/GBNDeviceSwitch-MIB: already exists in working directory
Checking patch mibs/fs/GBNL2Dhcp6Snooping-MIB...
error: mibs/fs/GBNL2Dhcp6Snooping-MIB: already exists in working directory
Checking patch mibs/fs/GBNL2DhcpSnooping-MIB...
error: mibs/fs/GBNL2DhcpSnooping-MIB: already exists in working directory
Checking patch mibs/fs/GBNL2PortSecurity-MIB...
error: mibs/fs/GBNL2PortSecurity-MIB: already exists in working directory
Checking patch mibs/fs/GBNL2PppoePlus-MIB...
error: mibs/fs/GBNL2PppoePlus-MIB: already exists in working directory
Checking patch mibs/fs/GBNL2QACL-MIB...
error: mibs/fs/GBNL2QACL-MIB: already exists in working directory
Checking patch mibs/fs/GBNL2Switch-MIB...
error: mibs/fs/GBNL2Switch-MIB: already exists in working directory
Checking patch mibs/fs/GBNL3-MIB...
error: mibs/fs/GBNL3-MIB: already exists in working directory
Checking patch mibs/fs/GBNL3DhcpRelay-MIB...
error: mibs/fs/GBNL3DhcpRelay-MIB: already exists in working directory
Checking patch mibs/fs/GBNL3IPPool-MIB...
error: mibs/fs/GBNL3IPPool-MIB: already exists in working directory
Checking patch mibs/fs/GBNL3If-MIB...
error: mibs/fs/GBNL3If-MIB: already exists in working directory
Checking patch mibs/fs/GBNL3Igmp-MIB...
error: mibs/fs/GBNL3Igmp-MIB: already exists in working directory
Checking patch mibs/fs/GBNL3Ospf-MIB...
error: mibs/fs/GBNL3Ospf-MIB: already exists in working directory
Checking patch mibs/fs/GBNL3PIM-MIB...
error: mibs/fs/GBNL3PIM-MIB: already exists in working directory
Checking patch mibs/fs/GBNL3Rip-MIB...
error: mibs/fs/GBNL3Rip-MIB: already exists in working directory
Checking patch mibs/fs/GBNL3RouteCommon-MIB...
error: mibs/fs/GBNL3RouteCommon-MIB: already exists in working directory
Checking patch mibs/fs/GBNPlatformChassis-MIB...
error: mibs/fs/GBNPlatformChassis-MIB: already exists in working directory
Checking patch mibs/fs/GBNPlatformGNLink-MIB...
error: mibs/fs/GBNPlatformGNLink-MIB: already exists in working directory
Checking patch mibs/fs/GBNPlatformOAM-MIB...
error: mibs/fs/GBNPlatformOAM-MIB: already exists in working directory
Checking patch mibs/fs/GBNPlatformOAMMailalarm-MIB...
error: mibs/fs/GBNPlatformOAMMailalarm-MIB: already exists in working directory
Checking patch mibs/fs/GBNPlatformOAMSntpClient-MIB...
error: mibs/fs/GBNPlatformOAMSntpClient-MIB: already exists in working directory
Checking patch mibs/fs/GBNPlatformOAMSsh-MIB...
error: mibs/fs/GBNPlatformOAMSsh-MIB: already exists in working directory
Checking patch mibs/fs/GBNPlatformOAMSyslog-MIB...
error: mibs/fs/GBNPlatformOAMSyslog-MIB: already exists in working directory
Checking patch mibs/fs/GBNPlatformOAMTelnet-MIB...
error: mibs/fs/GBNPlatformOAMTelnet-MIB: already exists in working directory
Checking patch mibs/fs/GBNServiceCM-MIB...
error: mibs/fs/GBNServiceCM-MIB: already exists in working directory
Checking patch mibs/fs/GBNServiceMACAUTHEN-MIB...
error: mibs/fs/GBNServiceMACAUTHEN-MIB: already exists in working directory
Checking patch mibs/fs/GBNServiceRADIUS-MIB...
error: mibs/fs/GBNServiceRADIUS-MIB: already exists in working directory
Checking patch mibs/fs/GBNServiceRMON-MIB...
error: mibs/fs/GBNServiceRMON-MIB: already exists in working directory
Checking patch mibs/fs/GBNServiceTACACS-MIB...
error: mibs/fs/GBNServiceTACACS-MIB: already exists in working directory
Checking patch mibs/fs/LAG-ARCH-MIB...
error: mibs/fs/LAG-ARCH-MIB: already exists in working directory
Checking patch mibs/fs/LLDPPRIVATE-MIB...
error: mibs/fs/LLDPPRIVATE-MIB: already exists in working directory
Checking patch mibs/fs/MAC-NOTIFICATION-MIB...
error: mibs/fs/MAC-NOTIFICATION-MIB: already exists in working directory
Checking patch mibs/fs/NSCRTV-EPON-ALARM-MGM-MIB...
error: mibs/fs/NSCRTV-EPON-ALARM-MGM-MIB: already exists in working directory
Checking patch mibs/fs/NSCRTV-EPON-IGMP-MGM-MIB...
error: mibs/fs/NSCRTV-EPON-IGMP-MGM-MIB: already exists in working directory
Checking patch mibs/fs/NSCRTV-EPON-PERFORMANCE-STAT-MIB...
error: mibs/fs/NSCRTV-EPON-PERFORMANCE-STAT-MIB: already exists in working directory
Checking patch mibs/fs/NSCRTV-EPON-QOS-MGM-MIB...
error: mibs/fs/NSCRTV-EPON-QOS-MGM-MIB: already exists in working directory
Checking patch mibs/fs/NSCRTV-EPON-SNI-MIB...
error: mibs/fs/NSCRTV-EPON-SNI-MIB: already exists in working directory
Checking patch mibs/fs/NSCRTV-EPON-STP-MGM-MIB...
error: mibs/fs/NSCRTV-EPON-STP-MGM-MIB: already exists in working directory
Checking patch mibs/fs/NSCRTV-EPON-SYSTEM-MIB...
error: mibs/fs/NSCRTV-EPON-SYSTEM-MIB: already exists in working directory
Checking patch mibs/fs/NSCRTV-EPON-VLAN-MGM-MIB...
error: mibs/fs/NSCRTV-EPON-VLAN-MGM-MIB: already exists in working directory
Checking patch mibs/fs/NSCRTV-EPONEOC-EPON-MIB...
error: mibs/fs/NSCRTV-EPONEOC-EPON-MIB: already exists in working directory
Checking patch mibs/fs/PIM-BSR-MIB...
error: mibs/fs/PIM-BSR-MIB: already exists in working directory
Checking patch mibs/fs/SWITCH...
error: mibs/fs/SWITCH: already exists in working directory
Checking patch tests/data/fs.json...
error: tests/data/fs.json: already exists in working directory
Checking patch tests/snmpsim/fs.snmprec...
error: tests/snmpsim/fs.snmprec: already exists in working directory
`

@PipoCanaja i get this error when i try to reapply the patch

**Comment by sp1rr3** [comment]
i dont get cpu or memory on my devices. s5850 or s5800.

**Comment by tsumaru720** [comment]
@PipoCanaja attached (s2800)
[snmpwalk.txt](https://github.com/librenms/librenms/files/2802994/snmpwalk.txt)

**Comment by PipoCanaja** [comment]
@daandersson Correct, I did not find much about temperature, fans, power etc etc. So nothing really interesing to add unfortunately. 
I would suggest to open a case with the vendor to request more data.

**Comment by PipoCanaja** [comment]
@sp1rr3 
Please pbin send for each of your FS devices the following :
./discovery.php -h xxxx -v -d | ./pbin.sh

Thx

**Comment by PipoCanaja** [comment]
@tsumaru720 Your captured file works correctly simulated in the lab. Processor, Memory, Device type, serial number, OS version. This is the most we can get from this SNMP implementation. 
If you don't have it, I would suggest that: 
- Remove all patches
- delete devices
- clear cache
- update librenms
- re-apply patch
- re-add device

**Comment by sp1rr3** [comment]
@PipoCanaja 
Hi,
Here you go :) https://p.libren.ms/view/c7fa4f3f for the s5850 
and https://p.libren.ms/view/aab51ddf for the s5800.

**Comment by PipoCanaja** [comment]
@sp1rr3 Not in the SNMP data exported. As already suggested to others, you should get in touch with the vendor and ask for a proper SNMP support. Until then, we'll try to get the most of what's available.

- 5850 does not reply to any of the 2 OIDs we already support. So please try to find inside snmpwalk if the data is there, and if yes what the OID yes. 
- 5800 reply to the expected OID for 5800, you get both CPU and Memory informations, so this one is all good.

**Comment by sp1rr3** [comment]
Hi @PipoCanaja 
I talked with FS and got theese answers.
1. what OIDs in SNMP to read out temperature and fan status in S5800-8TF12S
--->> Read the temperature information of the device via 'OID：1.3.6.1.4.1.27975.37.1.10.2.1.1—1.3.6.1.4.1.27975.37.1.10.2.1.5'

And CPU / RAM on S58050-48T4Q
Read the RAM and CPU info via ' OID：1.3.6.1.4.1.27975.1.1.12  and 1.3.6.1.4.1.27975.1.2.11 '

**Comment by PipoCanaja** [comment]
OK. Then please provide an snmpwalk for 5850 and I can try to add these.

**Comment by daandersson** [comment]
I talked to FS as well. The S3800 does not (and will not) report temperature over SNMP. 

Regarding the failing snmpwalk on S3800, FS claims there is no issue in the switch and that we should use SNMPB (freeware) software to check the switch OIDs. This is not really a relevant solution, but it seems clear that FS will not do anything about this issue in the S3800 switches.

**Comment by sp1rr3** [comment]
@PipoCanaja 
I just double checked and S5800 seems as the oids are avaible. 
but on the 5850 they seem to be wrong, so i asked them again.

**Comment by PipoCanaja** [comment]
Hi there,
The PR is now accepted into master, so we'll close this issue. If you have some more devices you would like to see inserted, please open a new issue with the proper data as asked.
