### ISSUE TITLE
Wrong timestamp format sent via nagios receiver

### ISSUE THREAD

**Issue by Nesousx** [librenms/librenms#9118]
Hi,

I've been trying to set up a nagios receiver alert transport in order to send LibreNMS alerts to Flapjack. However, I couldn't do it.

It seems that flapjack expects to receive the timestamp format in the UNIX format:

> The line must: - split into at least 9 tab-separated words - contain a unix timestamp in the 2nd word (seconds since epoch) - so just a whole number - the first word (object type) must contain either [HOSTPERFDATA] or [SERVICEPERFDATA].

Source: http://flapjack.io/docs/1.0/usage/Configuring-Nagios/

Currently, LIbreNMS sends a timestamp like below:
`2018-08-31 10:40:44`

According to my research, the file responsible for this is:

`LibreNMS/Alert/Transport/Nagios.php`

and does something like this:

```
    {
        /*
         host_perfdata_file_template=
         [HOSTPERFDATA]\t
         $TIMET$\t
         $HOSTNAME$\t
         HOST\t
         $HOSTSTATE$\t
         $HOSTEXECUTIONTIME$\t
         $HOSTLATENCY$\t
         $HOSTOUTPUT$\t
         $HOSTPERFDATA$
         */

        $format = '';
        $format .= "[HOSTPERFDATA]\t";
        $format .= $obj['timestamp'] . "\t";
        $format .= $obj['hostname'] . "\t";
        $format .= md5($obj['rule']) . "\t"; //FIXME: Better entity
        $format .= ($obj['state'] ? $obj['severity'] : "ok") . "\t";
        $format .= "0\t";
        $format .= "0\t";
        $format .= str_replace("\n", "", nl2br($obj['msg'])) . "\t";
        $format .= "NULL"; //FIXME: What's the HOSTPERFDATA equivalent for LibreNMS? Oo
        $format .= "\n";
        return file_put_contents($opts, $format);
    }
```

Now, I understand that the timestamp comes from the variable `$obj['timestamp']`. However, I have no idea how to modify it. Moreover, I have the feeling that modifying the variable system wide could turn all the timestamps (like for email alerts) to the new Unix format (which is not really human readable).

EDIT: manually sending the line to the named pipe while only replacing "librenms timestamp" by a Unix's one perfectly works.

Would that be possible (and clean?) to edit the nagios.php file so that it converts the already existing timestamp to the UNIX one? Or anything more clever... I am not a developer at all.. and I think I identified and issue, but my solution might not be the good one.

Thanks in advance, and thanks for the great product. :)

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
