### ISSUE TITLE
LibreNMS can`t detect some edge-core switches 

### ISSUE THREAD

**Issue by freedomwarrior** [librenms/librenms#9128]
```
====================================
Component | Version
--------- | -------
LibreNMS  | 1.43-3-gf5f964fd6
DB Schema | 262
PHP       | 7.2.7-0ubuntu0.18.04.2
MySQL     | 10.1.34-MariaDB-0ubuntu0.18.04.1
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.7.2
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

I got some device that discovered as **Generic**, but they are network switches, Edge-Core.
Got around 60 devices, some of them discover correct and some of them not. They are all the same model.
Here is poll off Edge-Core ES3510MA which shown as **Generic**:
`./discovery.php` > https://p.libren.ms/view/58972b13
`./poller.php >` https://p.libren.ms/view/5ac836b8
`snmpbulkwalk` > https://p.libren.ms/view/58376ca4

**Comment by murrant** [comment]
Definitely not the same model (or at least hardware) `1.3.6.1.4.1.259.8.1.11` is not in our current detection list.

**Comment by freedomwarrior** [comment]
Yes, you are right, hw a little bit different. Is it possible to add support for this device?
