### ISSUE TITLE
Search fields don't show only searched-for entries, they just hide the other entries

### ISSUE THREAD

**Issue by fjwcash** [librenms/librenms#913]
Login to LibreNMS.

Go to Devices --> Locations.  You get a multi-page list of all devices at all locations.

Use the Location drop-down to select a specific location.  Click the Search button.

What I expect to happen, is that a new query is made, and only the devices at that location appear in the list, only spanning multiple pages if there's 50+ devices at that location.  If there are fewer than 50, I expect them all to appear on a single page, right below the search fields.

What really happens is that devices that are NOT at that location are simply hidden in the list, and you have to scroll/click through multiple pages until you find where the devices were in the original "all locations" list.  If you search for a location other than the first couple, then the first screen(s) of results is blank!

This makes the search fields (and all of the Devices --> Locations entries) essentially useless.  It doesn't reduce the number of clicks it takes to find devices as you still have to page through them all until you see entries for the specified location.

**Comment by laf** [comment]
Works for me (tm) :) If I got to Devices -> Locations and select a location I only get those devices. If I use the search in Devices I also get a restricted list.

Can you provide desktop OS version, browser version that you are using + any extensions.

**Comment by f0o** [comment]
am I the only one that has no click-able link on the Dropdown-point Locations?

I'm on: Devices -> All Devices; Specify location in the table, click search; Works for me (tm)

**Comment by laf** [comment]
No that's just a #, needs updating.

**Comment by fjwcash** [comment]
On Mon, May 4, 2015 at 11:09 AM, Neil Lathwood <notifications@github.com>
wrote:

> Works for me (tm) :) If I got to Devices -> Locations and select a
> location I only get those devices. If I use the search in Devices I also
> get a restricted list.
>
> Can you provide desktop OS version, browser version that you are using +
> any extensions.
>
​Since everything is better with pictures, see attached.

librenms-locations-01.png shows a search for all devices (top of list).

libre​nms-locations-02.png shows the same page, just the bottom of it, so
you can see the "showing X of Y" numbers.

​librenms-locations-03.png shows the results of searching for a specific
location.  Note how the "showing X of Y" numbers show the same total number
of devices.

librenms-locations-04.png shows the result of click "next page" a few
times.  Still no devices showing.

librenms-locations-05.png shows page 7, the first page to include a device
from the searched-for location.

Server is running Debian 7.

Client is running Kubuntu 14.04 LTS with Google Chrome​ 42.  AdBlock+ is
installed, but disabled for our LibreNMS domain.

​I've also tested with Mozilla Firefox 37.0.1 on the same system, with the
same results.​

And, ​I've tested with Mozilla Firefox 31.6.0 ESR on Windows XP, with the
same results.​

-- 
Freddie Cash
fjwcash@gmail.com

**Comment by laf** [comment]
I'm not seeing any pics in the issue :(

**Comment by fjwcash** [comment]
Oh, replies via e-mail with attachments aren't supported.

I'll attach them here.
![librenms-locations-01](https://cloud.githubusercontent.com/assets/12239012/7461299/0882618c-f25e-11e4-82c3-54588f124ca4.png)
![librenms-locations-02](https://cloud.githubusercontent.com/assets/12239012/7461300/0882e8e6-f25e-11e4-978e-36dcad442d10.png)
![librenms-locations-03](https://cloud.githubusercontent.com/assets/12239012/7461302/0883f0ce-f25e-11e4-994a-fcdb3a219d7c.png)
![librenms-locations-04](https://cloud.githubusercontent.com/assets/12239012/7461301/088301d2-f25e-11e4-8a80-8a846a5b0ec1.png)
![librenms-locations-05](https://cloud.githubusercontent.com/assets/12239012/7461303/0885ed20-f25e-11e4-8663-3d5125b2d0dc.png)

**Comment by fjwcash** [comment]
Whoops, seems the last image is incorrect.  Here's the correct one, showing the one device, on page 7.
![librenms-locations-05](https://cloud.githubusercontent.com/assets/12239012/7461320/4178cf76-f25e-11e4-8e15-7682408cb19b.png)

**Comment by f0o** [comment]
I notice the AJAX returning a fixed (location-agnostic) `count` value but I dont see any indexing of the rows so I'm not sure this is related...

**Comment by laf** [comment]
I can also see this issue with my work install. I'll take a look.

**Comment by laf** [comment]
Ok, so the issue is this when you set a sysLocation override, two entries are created in devices_attribs to indicate this. The way a lot of the code originally worked (and we've moved away from it in some ways) is by grabbing all the data from the DB regardless of if it's needed then run a load of php functions to work out what we do and don't want before presenting to the user. This is inefficient and the reason why people see http 500 errors on Observium installs with large numbers of devices / ports.

That happens less so with LibreNMS now as we process the data at MySQL end - mostly.

In this case we still weren't so whilst the pagination was all done from the SQL results, the actual data returned to the user was potentially different.

I've managed to swap out the php functions and do all of this in MySQL (I think) but it needs testing. For me at work it now functions as you would expect, I can filter by device location even for locations overwritten.

It would be great if others could test this -especially @fjwcash :)

Apply this patch:

https://gist.githubusercontent.com/laf/3f344084f5a80aa64817/raw/b78c7482b3f611891bf248d9fc14e1a73c4d58f3/gistfile1.txt

```bash
cd /opt/librenms
wget https://gist.githubusercontent.com/laf/3f344084f5a80aa64817/raw/b78c7482b3f611891bf248d9fc14e1a73c4d58f3/gistfile1.txt
patch -p1 < gistfile1.txt
rm gistfile1.txt
```

Please let me know how you get on and I'll fix more / create a PR.

**Comment by fjwcash** [comment]
I get the following when applying the patch:

# patch -p1 < gistfile1.txt
patching file html/includes/table/devices.inc.php
patch unexpectedly ends in middle of line
Hunk #5 succeeded at 164 with fuzz 1.

However, when I test the search fields in the web GUI, everything is working correctly / as I expect it to.

Pull up full list of all devices, shows 374 devices split across 8 pages.

Call up a specific location, and it only shows the devices for that location, on a single page.

Call up a different location, and it only shows the devices for that location, split across multiple pages as needed.

So far, looks like it's working correctly.  Hopefully, those patch warnings aren't critical.  :)

Thanks for digging into this.

**Comment by laf** [comment]
No worries. Going to wait for others to give it a try to make sure it's not broken anything else then I'll pr it up.

**Comment by f0o** [comment]
SQL statement looks good to me :+1:

**Comment by laf** [comment]
PR now done #917
