### ISSUE TITLE
please add support for motorola wing

### ISSUE THREAD

**Issue by rokkhan** [librenms/librenms#9141]
Hi,
Please add support for Motorola Wing devices. I have added one and it shows like a symbol device but no information about wireless is shown like when I add a cisco aironet device.

I have runned all the asked scripts, hope it will help.
Discovery -> https://p.libren.ms/view/7c69ae85
Poller -> https://p.libren.ms/view/b1369937
Snmpwalkbulk -> https://p.libren.ms/view/65096f6a

Please feel free to ask any more info if it is needed, I will try to supply all the info.

Thanks a lot!

**Comment by murrant** [comment]
What information are you looking for specifically? do you have a mib?  Did Motorola by Symbol product lines?

**Comment by rokkhan** [comment]
Hi.

I would like to get wireless related info, radios, channel, power, ssid, associated clients...
I attach mibs from wireless AP model AP6532 AP7532 and wireless controller NX9000. 
[AP6532-mibs-5.9.1.5-001R.tar.gz](https://github.com/librenms/librenms/files/2349881/AP6532-mibs-5.9.1.5-001R.tar.gz)
[AP7532-mibs-5.9.1.0-029R.tar.gz](https://github.com/librenms/librenms/files/2349882/AP7532-mibs-5.9.1.0-029R.tar.gz)
[NX9500-mibs-5.9.1.5-001R.tar.gz](https://github.com/librenms/librenms/files/2349883/NX9500-mibs-5.9.1.5-001R.tar.gz)
Wireless AP are adopted from wireless controller, so maybe all this info coul be obtained from wireless controller.

In the beginning the company was Symbol but it was bought by motorola and started to develop their own OS called "Wing". Products are not the same but the origin was Symbol.

Motorola sold their wireless solution to Zebra Technologies, that did not develop too much Wing the few time it was managed by Zebra.

Finally this wireless solution has been bought by Extreme Networks but this wireless solution is still running Wing OS. Extrem has their own wireless solution ExtremeWireles but is not the same product.

For me it is still Motorola, but should be know as Extreme Wing.

Greetings!

**Comment by rokkhan** [comment]
I have also run Discovery, poller and snmpwalk to wireless controller.
Discovery -> https://p.libren.ms/view/b5db7e67
Poller -> https://p.libren.ms/view/b3306bd3
Snmpwalkbulk -> https://p.libren.ms/view/4589fdea
Thanks in advance.

**Comment by TryAztec** [comment]
@murrant Do you currently support these devices?

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11645

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/please-add-support-for-motorola-wing/11645/1
