### ISSUE TITLE
NGINX : update doc and modify plugin

### ISSUE THREAD

**Issue by tboulogne** [librenms/librenms#915]
Hello,

Could you update the doc to add this portion of code for Nginx setup with the unix-agent please ?
````
location /nginx-status {
    stub_status on;
    access_log   off;
    allow 127.0.0.1;
    deny all;
}
````
Regarding unix-agent Nginx plugin, i think it could be interesting to replace 

```
http://localhost/nginx-status
```

by

````
http://127.0.0.1/nginx-status
````

Basically, Nginx don't resolve DNS  for authorization line (allow 127.0.0.1) without additional module.

Thanks for all.

Regards

**Comment by f0o** [comment]
On it, Thanks for the hint :)

**Comment by tboulogne** [comment]
you're wellcome :-).

Le 05/05/2015 09:40, Daniel Preussker a écrit :
>
> On it, Thanks for the hint :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/librenms/librenms/issues/915#issuecomment-98984035>.
>

-- 
TNG CONCEPTS - Formation - Prestations Informatiques - Distribution 
<http://www.tng-concepts.com> 	
	
Mettre la Technologie au service de l'Homme.
Votre exigence. Notre Métier.
Thierry BOULOGNE
Responsable développement
(+33) 5 35 00 53 90 (Fixe)
(+33) 6 43 18 31 19 (Mob.)
Profil viadeo <http://fr.viadeo.com/fr/profile/thierry.boulogne2>

Formation - E-commerce - informatique
www.tng-concepts.com <http://www.tng-concepts.com>
