### ISSUE TITLE
macros not expand to right sql statement when entered as value

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#9155]
when I create a rule 
`eventlog.type = "trap" AND eventlog.datetime >= "macros.past_60m"`

after save the rule it expands to SQL statement:
`SELECT * FROM devices,eventlog WHERE (devices.device_id = ? AND devices.device_id = eventlog.device_id) AND eventlog.type = "trap" AND eventlog.datetime >= "macros.past_60m"`

but should be:
`SELECT * FROM devices,eventlog WHERE (devices.device_id = ? AND devices.device_id = eventlog.device_id) AND eventlog.type = "trap" AND eventlog.datetime >= DATE_SUB(NOW(),INTERVAL 60 MINUTE)`

So it seems a problem in the GUI that the value macros.past_60m is saved as string and not as expanded macro value.

even if i try to change the rule 
`eventlog.type = "trap" AND eventlog.datetime >= "macros.past_60m"`
to
`eventlog.type = "trap" AND  macros.past_60m <= "eventlog.datetime"`
it seems to not working.

we need a possibility to enter a An **Entity Condition Entity** statement additional to **Entity Condition Value**

**Comment by vitalisator** [comment]
ok, found the solution.
placing the macro string into backticks do the right thing 

eventlog.type = "trap" AND eventlog.datetime >= \`macros.past_60m\`

that should be documented somwhere ;-)

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
