### ISSUE TITLE
Issue 913 may have broken device links on search pages

### ISSUE THREAD

**Issue by fjwcash** [librenms/librenms#918]
Since patching LibreNMS to fix issue 913, I can no longer click on Device links on search pages.

To reproduce:

1.  Login to LibreNMS.
2.  Click on Devices --> All Devices
3.  Hover the mouse over all the links on the page that appear.  Note how they all show "device=XXX" at the end.

4.  Select a location from the drop-down.  Click the Search button.
5.  Hover the mouse over all the links on the page.  Note how they all show only "device" at the end now.  The device ID is missing from the links.

At this point, clicking on any of the links takes you to a blank device page.  Clicking the Options link for a device lets you change things like the Type, but when you click Save, you get the "options unchanged, nothing to save" green box.

Here's a screen shot showing the a link as it appears in step 3 above (look at the URL pop-up in the bottom-left of the shot):
![librenms-devices-01](https://cloud.githubusercontent.com/assets/12239012/7476869/2b2729e6-f305-11e4-8cfe-0adc0f3f3734.png)

And here's a screenshot showing the same device, after changing the location field at the top and hitting search  (look at the URL pop-up in the bottom-left of the shot):
![librenms-devices-02](https://cloud.githubusercontent.com/assets/12239012/7476875/3c95e87a-f305-11e4-840b-78299e633bf6.png)

**Comment by laf** [comment]
This was fixed in the full patch which was merged earlier :)

You will need to clear the patch you have installed out and update:

```bash
cd /opt/librenms
git checkout -- html/includes/table/devices.inc.php
git pull
```

**Comment by fjwcash** [comment]
:)  Well, will you look at that.  So it is.  Search results correctly show the device ID in the URL after updating LibreNMS.

I'll have to remember to always do a "git pull" and re-test before entering new issues.  :)

Thanks!
