### ISSUE TITLE
MySQL error after automatic update

### ISSUE THREAD

**Issue by bitency** [librenms/librenms#9187]
After updating automatic LibreNMS update we get this MySQL error:

Unhandled MySQL Error [42S22] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list'

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
