### ISSUE TITLE
VLAN discovery crashes MySQL database after update to v1.43

### ISSUE THREAD

**Issue by petracvv** [librenms/librenms#9191]
We are running LIbrenms in a distributed-polling type deployment. After updating to v1.43, when the full discovery runs on one of our Cisco devices with a large number of VLANs defined, a large delete SQL query is generated causing memory usage on our MySQL server to skyrocket and the kernel to oom-kill the daemon. The query in question from our error logs: https://gist.github.com/petracvv/73a34584d0ad821b49ed18c48af9a763

I traced this down to the query generation code here: https://github.com/librenms/librenms/blob/e9ff8c48b66c7e821617fe9e8a45feb33a0fb2c4/includes/discovery/vlans.inc.php#L94

If I revert the portion of this commit (https://github.com/librenms/librenms/commit/e9ff8c48b66c7e821617fe9e8a45feb33a0fb2c4) dealing with line 94 of the `includes/discovery/vlans.inc.php` file, I no longer see the memory problem on the database server.

Is this something that should be reverted or is it a bug in the new list generation code using `dbGenPlaceholders`?

Let me know if you want more log files or data from a failed run.

**Comment by murrant** [comment]
This issue has been closed as it isn't classed as a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by petracvv** [comment]
So you don't accept bug reports on github? Just device requests?

**Comment by murrant** [comment]
That's what the text said when you deleted when you opened the issue.

**Comment by petracvv** [comment]
Whoops, guess I really didn't pay attention there.
