### ISSUE TITLE
invalid URL scheme when using proxy

### ISSUE THREAD

**Issue by corny** [librenms/librenms#9194]
I am running a reverse proxy that does TLS and forwards requests via HTTP to the librenms host. Since last night I am not able to sign in any more, because the login contains two resources referenced via http:// instead of https://.

My config.php contains:
```php
$config['base_url'] = "https://librenms.example.com";
```

Excerpt of the login page:
```html
    <div class="panel-heading">
        <h3 class="panel-title center-block">
            <img class="logon-logo img-responsive" src="http://librenms.example.com/images/librenms_logo_light.svg">
        </h3>
    </div>
    <div class="panel-body">
        <div class="container-fluid">
            <form class="form-horizontal" role="form" action="http://librenms.example.com/login" method="post" name="logonform">
```

**Comment by MrXermon** [comment]
I have the same problem on my configuration. Would be greate if we could fix this error quickly.

**Comment by MrXermon** [comment]
Semms like there is already a solution:
https://community.librenms.org/t/solved-web-interface-broken-after-update/5377/5

**Comment by corny** [comment]
That's just a workaround. I don't want a self signed certificate because the communication between proxy and LibreNMS is already secured via IPSec.

**Comment by corny** [comment]
@laf Why did you close this issue?

**Comment by murrant** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
