### ISSUE TITLE
Login form using fully qualified URLs

### ISSUE THREAD

**Issue by asmith3006** [librenms/librenms#9215]
The login page has `form action` fields and image `src` fields populated with the full URL (http://domain/login) rather than just the relative path so the `<base ref=` can work its magic. Using the fully qualified URLs makes it very difficult to work behind a reverse proxy. 

Also, even if the output is modified the form processing still redirects you to the wrong URL (fully qualified rather than relative)

I think the file with the issue is [this file](https://github.com/librenms/librenms/blob/master/resources/views/auth/login-form.blade.php) but I don't know how to fix it :(

**Comment by murrant** [comment]
This issue has been closed as it isn't classed as a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

PS https://docs.librenms.org/Support/FAQ/#my-reverse-proxy-is-not-working
