### ISSUE TITLE
Nutanix

### ISSUE THREAD

**Issue by anden4380** [librenms/librenms#9230]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

I have uplaod data for Nutanix,CVM and Prisim i think its all in the same files :-) 

I have attched the MIB for Nutanix,CVM and Prisim 

[nutanix.zip](https://github.com/librenms/librenms/files/2395682/nutanix.zip)

**Comment by laf** [comment]
The zip only appears to contain a mib. We need all the info asked for in the link above.

**Comment by anden4380** [comment]
But have upload poller and discover and snmpbulkwalk 

Can they not be used?

**Comment by laf** [comment]
Where?

**Comment by anden4380** [comment]
i have run this 3 commands again, please see if you have the data :-) 

./discovery.php -h HOSTNAME -d | ./pbin.sh
./poller.php -h HOSTNAME -r -f -d | ./pbin.sh
snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh

**Comment by laf** [comment]
Those commands give you links back, they don't magically appear for us.

**Comment by anden4380** [comment]
Sorry then i have miss understud how to run thes commands :-) 

https://p.libren.ms/view/edb69050
https://p.libren.ms/view/33deeadb

[snmpbulkwalk.txt](https://github.com/librenms/librenms/files/2409709/snmpbulkwalk.txt)

**Comment by sippe2** [comment]
Hyper-converged infrastructure (HCI) values are located under oid 1.3.6.1.4.1.41263.

[NUTANIX-MIB](https://p.libren.ms/view/e8383a75)

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/nutanix/11644/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11644
