### ISSUE TITLE
Cohesity Storage

### ISSUE THREAD

**Issue by SlyngleN** [librenms/librenms#9232]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X
] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Requesting support for Cohesity Storage

MIB file Attached

SNMP Discovery, poller, snmp bulk walk done

[COHESITY-APPLIANCE-MIB.txt](https://github.com/librenms/librenms/files/2395927/COHESITY-APPLIANCE-MIB.txt)

**Comment by laf** [comment]
You have only uploaded a mib. We need all the info asked for in the link above.
