### ISSUE TITLE
Can't enable anonymous usage statistics on LibreNMS

### ISSUE THREAD

**Issue by hrv231** [librenms/librenms#9245]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Hello,

I'm runnning:

Version | 1.43-106-gdaec72f8a - Wed Sep 19 2018 16:05:10 GMT-0700
-- | --
DB Schema | #268
Web Server | nginx/1.10.3
PHP | 7.0.31-1~dotdeb+8.1
MySQL | 10.1.26-MariaDB-0+deb9u1
RRDtool | 1.6.0

and for some reason I can't enable to send anonoymous usage statistics on the About webpage, it shows that it has been enabled, but when I go to any other webpage and return to About, it shows again as OFF.
When I installed LibreNMS long time ago I remember to have disable this at the beginning of the installation.

Thanks for all your work!

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
