### ISSUE TITLE
Add Netgear Switch Support

### ISSUE THREAD

**Issue by Lonecrowe** [librenms/librenms#925]
I set up a netgear switch for you guys to check out.  It has the port forwards and SNMP enabled for you to view.  Details sent in email.  

They use standard IF MIB but also use the private mib below.  

http://www.oidview.com/mibs/4526/NETGEAR-SWITCHING-MIB.html

**Comment by laf** [comment]
PR Done @Lonecrowe. You can close snmp access down.

**Comment by Lonecrowe** [comment]
Sweet I'll check it out.
