### ISSUE TITLE
Add support VMG1312 Zyxel

### ISSUE THREAD

**Issue by loic69chy** [librenms/librenms#9254]
Hi
Please can you suport ZYXEL VMG1312 modem DSL as network device instead of server.
Also 
System description, system name are not good at this moment.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Here's the log file asked
DISCOVER  
https://p.libren.ms/view/f12368e6

POLLER
https://p.libren.ms/view/52944e78

SNMP
https://p.libren.ms/view/43a68257

Thanks for your Help

**Comment by PipoCanaja** [comment]
Bonjour @loic69chy 
Can you confirm that the SNMP data is complete ? When looking at it, there not even a model number provided there, sysDescr contains what seems to be the version of the firmware but not the device. 
A PR is coming to add basic support for this device.
Bonne soirée
