### ISSUE TITLE
discovery.php doesn't honour poller_group from config.php

### ISSUE THREAD

**Issue by fjwcash** [librenms/librenms#926]
I see that addhost.php now correctly sets the poller_group in the devices table in the database when you use -g on the command-line.

However, there isn't a -g option for discovery.php, and it doesn't pick up the poller_group setting from config.php.  Any devices discovered via the command-line using discovery.php use the default poller_group (aka 0) when added to the database.

Running LibreNMS updated yesterday.

I (still) have to manually edit includes/functions.php to set the correct default poller_group for the addHost() and createHost() functions.  This edit has to be done each of the remote pollers in my setup, with a different default set on each one.

Looking at discovery.php, it seems to have the correct code for it to work at the top of the script, but it doesn't.  :(

config.php entries:
`### Distributed Poller-Settings`
`$config['distributed_poller']                   = TRUE;`
`$config['distributed_poller_name']              = file_get_contents('/proc/sys/kernel/hostname');`
`$config['distributed_poller_group']             = 3;`
`$config['distributed_poller_memcached_host']    = 'mylibrenms.host';`
`$config['distributed_poller_memcached_port']    = '11211';`

includes/functions.php edited to use poller_group = '1' in addHost() and createHost() function declarations (instead of the default poller_group = '0').

Running `discover.php -h new -d` shows the following SQL statement:
`SQL[INSERT INTO 'devices' ('hostname','sysName','community','port','transport','status','snmpver','poller_group','os')  VALUES ('t3-42.mydomain','t3-42.mydomain','public','161','udp','1','v2c','1','linux')] `

Note the second-last item.  It should be a 3 as set in config.php, but it's using the default entry from the function declaration.

**Comment by laf** [comment]
I have a feeling you may not be running an upto date version. The current master is definitely patched to support adding groups:

Line 269 of includes/functions.php
```php
function addHost($host, $snmpver, $port = '161', $transport = 'udp', $quiet = '0', $poller_group = '0', $force_add = '0')
```
The subsequent calls for addHost within this all pass poller_group on

Line 523 of includes/functions.php
```php
function createHost($host, $community = NULL, $snmpver, $port = 161, $transport = 'udp', $v3 = array(), $poller_group='0')
```
All calls to this pass on poller_group variables.

```bash
[root@testing librenms]# ./addhost.php -g 15  localhost.localdomain
Trying community public ...
Added device localhost.localdomain (58)

mysql> select poller_group from devices where hostname='localhost.localdomain';
+--------------+
| poller_group |
+--------------+
|           15 |
+--------------+
1 row in set (0.00 sec)
```

I'm not sure where the insert is from as that should only occur when you add a device and doesn't happen on discovery (unless it was auto discovered - can you confirm?) Running a discovery -h new -d will show the following statement and as you can see in mine is using poller_group 15 which is what's in the config:

```php
[root@testing librenms]# ./discovery.php -h new -d
LibreNMS 2014.master Discovery

DEBUG!

SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1]
SQL[SELECT revision FROM `dbSchema`]
SQL[SELECT * FROM `devices` WHERE status = 1 AND disabled = 0 AND `last_discovered` IS NULL AND poller_group='15' ORDER BY device_id DESC] ./discovery.php new 2015-05-07 00:45:39 - 0 devices discovered in 0.003 secs
MySQL: Cell[1/0s] Row[1/0s] Rows[1/0s] Column[0/0s] Update[0/0s] Insert[0/0s] Delete[0/0s]
```

Can you do the following please:

```bash
cd /opt/librenms
git status
git log
```

Paste the output somewhere (edited if needs be).

**Comment by fjwcash** [comment]
Yes, I have the same addHost() and createHost() function declarations.  But, if I run discovery.php, and it auto-discovers hosts via ARP/LLDP, those hosts are added to the database with the default poller_group (aka 0) set.  It doesn't pick up the poller_group setting from config.php and pass that along for auto-discovered hosts.


root@server.sahali:/opt/librenms# git status
# On branch master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	typechange: html/css/bootstrap-datetimepicker.min.css
#	typechange: html/css/font-awesome.css
#	typechange: html/css/font-awesome.min.css
#	typechange: html/css/jquery.bootgrid.min.css
#	typechange: html/css/vis.min.css
#	typechange: html/fonts/FontAwesome.otf
#	typechange: html/fonts/fontawesome-webfont.eot
#	typechange: html/fonts/fontawesome-webfont.svg
#	typechange: html/fonts/fontawesome-webfont.ttf
#	typechange: html/fonts/fontawesome-webfont.woff
#	typechange: html/fonts/fontawesome-webfont.woff2
#	typechange: html/js/bootstrap-datetimepicker.min.js
#	typechange: html/js/jquery.bootgrid.min.js
#	typechange: html/js/moment.min.js
#	typechange: html/js/pace.min.js
#	typechange: html/js/typeahead.bundle.min.js
#	typechange: html/js/vis.min.js
#	modified:   includes/definitions.inc.php
#	modified:   includes/functions.php
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	includes/discovery/os/toshiba.inc.php
#	tq
no changes added to commit (use "git add" and/or "git commit -a")

Here's the top portion (most recent entries) of the log.  As mentioned, running LibreNMS as of Tue May 5:
commit 5f2ccb950787b2c7e52e16cc38a579926db2596d
Merge: ccef73b 1fdf271
Author: Daniel Preussker <f0o@users.noreply.github.com>
Date:   Tue May 5 11:55:07 2015 +0000

    Merge pull request #917 from laf/devices-fix
    
    Fixed devices location filtering

commit 1fdf271470f0736ab625f7e5e729818b624b3e43
Author: laf <neil@lathwood.co.uk>
Date:   Tue May 5 12:54:25 2015 +0100

    Added missing devices. for column reference

commit fa83e1ecea98579af0ccc9824c23791a3d6d80d7
Author: laf <neil@lathwood.co.uk>
Date:   Tue May 5 11:29:59 2015 +0100

    Fixed devices location filtering

**Comment by f0o** [comment]
@fjwcash I see why.
I'll give you a patch to test shortly.

**Comment by fjwcash** [comment]
On Thu, May 7, 2015 at 2:13 PM, Daniel Preussker <notifications@github.com>
wrote:

> @fjwcash <https://github.com/fjwcash> Try this patch please:
>
> diff --git a/includes/discovery/functions.inc.php b/includes/discovery/functions.inc.php
> index 095eb31..f46ecfe 100644--- a/includes/discovery/functions.inc.php+++ b/includes/discovery/functions.inc.php@@ -39,7 +39,7 @@ function discover_new_device($hostname)
>
>      if ( match_network($config['nets'], $ip) )
>      {-      $remote_device_id = addHost ($dst_host,'');+      $remote_device_id = addHost ($dst_host,'',null,null,null,$config['distributed_poller_group']);
>        if ($remote_device_id) {
>          $remote_device = device_by_id_cache($remote_device_id, 1);
>          echo("+[".$remote_device['hostname']."(".$remote_device['device_id'].")]");
> ​​
>
> ​Patch applied.

I'm just in the process of adding a new site/distributed poller to the
config.  Once I've configured up all the switches there, I'll run the
discovery process and let you know how things turn out.

Most likely won't be until tomorrow, though.

Thanks!​

-- 
Freddie Cash
fjwcash@gmail.com

**Comment by f0o** [comment]
@fjwcash  @laf just pointed me that PHP5.x doesnt support NULL parameters anymore.

Here an updated patch:

```diff
diff --git a/includes/discovery/functions.inc.php b/includes/discovery/functions.inc.php
index 095eb31..de62837 100644
--- a/includes/discovery/functions.inc.php
+++ b/includes/discovery/functions.inc.php
@@ -39,7 +39,7 @@ function discover_new_device($hostname)
 
     if ( match_network($config['nets'], $ip) )
     {
-      $remote_device_id = addHost ($dst_host,'');
+      $remote_device_id = addHost ($dst_host, '', '161', 'udp', '0', $config['distributed_poller_group']);
       if ($remote_device_id) {
         $remote_device = device_by_id_cache($remote_device_id, 1);
         echo("+[".$remote_device['hostname']."(".$remote_device['device_id'].")]");
```

**Comment by fjwcash** [comment]
Updated.  Thanks.  I'll let you know how it works.

On Thu, May 7, 2015 at 2:44 PM, Daniel Preussker <notifications@github.com>
wrote:

> @fjwcash <https://github.com/fjwcash> @laf <https://github.com/laf> just
> pointed me that PHP5.x doesnt support NULL parameters anymore.
>
> Here an updated patch:
>
> diff --git a/includes/discovery/functions.inc.php b/includes/discovery/functions.inc.php
> index 095eb31..de62837 100644--- a/includes/discovery/functions.inc.php+++ b/includes/discovery/functions.inc.php@@ -39,7 +39,7 @@ function discover_new_device($hostname)
>
>      if ( match_network($config['nets'], $ip) )
>      {-      $remote_device_id = addHost ($dst_host,'');+      $remote_device_id = addHost ($dst_host, '', '161', 'udp', '0', $config['distributed_poller_group']);
>        if ($remote_device_id) {
>          $remote_device = device_by_id_cache($remote_device_id, 1);
>          echo("+[".$remote_device['hostname']."(".$remote_device['device_id'].")]");
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/librenms/librenms/issues/926#issuecomment-100028333>.
>



-- 
Freddie Cash
fjwcash@gmail.com

**Comment by fjwcash** [comment]
From a clean install of librenms on a new server, config.php has poller_group set to 4.

`addhost.php -4 hostname` works correctly, adding the device to the DB with poller_group set to 4.

`discovery.php -h new` also now work correctly.  :)  Auto-discovered devices are added to the DB with poller_group set to 4.

So far, so good.  Thanks!

**Comment by f0o** [comment]
yay! if you think it works stable, give me a ping here so I can PR the patch :)

**Comment by fjwcash** [comment]
A corollary to this is:  how hard would it be to make `addhost.php` pick up the poller_group from `config.php`, eliminating the need to specify it on the command-line?  That way, adding a host and discovering a host would work the same.  I've caught myself a couple of times forgetting the -g option to addhost.php.

Then everything is set via `config.php`.

**Comment by f0o** [comment]
As Addhost is an administrative tool (and not a job like discovery) I dont think we should suggest the current poller-group as default for it.

But that's just my opinion.

**Comment by laf** [comment]
I'm not sure why we wouldn't :)

If you have poller_group configured then adding a host on that poller means you probably want it to be polled from there. If you don't then specifying -g 0 is probably what people should be doing.

**Comment by fjwcash** [comment]
200 hosts auto-discovered via LLDP/ARP with poller_group correctly picked up via config.php and set in the database.  :)  No errors anywhere that I can see so far.  I'll be testing the patch on a second host later today.


As for addhost.php (IIUC) it's only run as an admin tool via the web GUI, and the host running the web GUI generally wouldn't be considered a distributed poller, so it wouldn't have that set in the config.php.  Whereas the hosts configured as remote pollers won't be running the web GUI and only adding hosts via the command-line.  Or, at least, that's how I'm seeing things right now.

**Comment by fjwcash** [comment]
And another 130-odd hosts auto-discovered at another site, picking up the correct (and different) poller_group from config.php.

Thanks!

**Comment by laf** [comment]
No worries @fjwcash and thanks for reporting back. The patch is now in the master branch so don't forget to remove the patch and update.

As for having ./addhost.php pick up the default poller_group. @f0o and @paulgear let's go for a majority vote on this one :) I say ./addhost.php should honour poller_group by default so if you call without -g then it will use $config['poller_group']. What do you guys say?

**Comment by fjwcash** [comment]
Updated all my remote hosts to bed7c08 and auto-discovery of hosts is correctly pulling the poller_group from config.php.  :)  No manual editing of functions.php required.

**Comment by paulgear** [comment]
I agree with @laf on this one - the principle of least astonishment is that addhost should use $config['poller_group'].

**Comment by laf** [comment]
PR #944 sorts out addhost.php now.

**Comment by f0o** [comment]
Merged :)
