### ISSUE TITLE
daily.sh removed necessary library without updating or reinstalling

### ISSUE THREAD

**Issue by electriceel1985** [librenms/librenms#9260]
daily.sh seems to have removed a necessary library and then failed to update and reinstall it, resulting in downtime.

I fixed this with a big hammer by cloning the library's source in question (myclabs/DeepCopy) with git and placing it where the update process wanted to see it. daily.sh ran fine after. Any insight into why this happened would be helpful. I see a RuntimeException during an attempt to delete a file, but am not certain this would impede update process.

Here is the relevant portion of the daily.sh logs. Apologies for the length. I'm not sure how to create collapsible content.

[ Wed, 19 Sep 2018 00:15:14 ] http://www.librenms.org/notifications.rss (33)
[ Wed, 19 Sep 2018 00:15:14 ] misc/notifications.rss (40)
[ Wed, 19 Sep 2018 00:15:14 ] Updating DB  Done
Returned: 0
Caching PeeringDB data
Peering DB integration disabled
Returned: 0
Updating to latest codebase

Returned: 0
Updating Composer packages
> LibreNMS\ComposerHelper::preInstall
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 0 installs, 16 updates, 7 removals
  - Removing webmozart/assert (1.3.0)
  - Removing phpunit/php-token-stream (1.4.12)
  - Removing phpdocumentor/type-resolver (0.4.0)
  - Removing phpdocumentor/reflection-docblock (3.3.2)
  - Removing phpdocumentor/reflection-common (1.0.1)
  - Removing myclabs/deep-copy (1.7.0)
  - Removing doctrine/instantiator (1.0.5)
  - Updating vlucas/phpdotenv (v2.4.0 => v2.5.1): Downloading (100%)
  - Updating symfony/css-selector (v3.4.14 => v3.4.15): Loading from cache
  - Updating symfony/var-dumper (v3.4.14 => v3.4.15): Loading from cache
  - Updating symfony/process (v3.4.14 => v3.4.15): Downloading (100%)
  - Updating symfony/http-foundation (v3.4.14 => v3.4.15): Downloading (100%)
  - Updating symfony/event-dispatcher (v3.4.14 => v3.4.15): Loading from cache
  - Updating symfony/debug (v3.4.14 => v3.4.15): Downloading (100%)
  - Updating symfony/http-kernel (v3.4.14 => v3.4.15): Downloading (100%)
  - Updating symfony/finder (v3.4.14 => v3.4.15): Loading from cache
  - Updating symfony/console (v3.4.14 => v3.4.15): Loading from cache
  - Updating league/flysystem (1.0.45 => 1.0.47): Downloading (100%)
  - Updating fico7489/laravel-pivot (2.0.6 => 2.3.7): Downloading (100%)
  - Updating psy/psysh (v0.9.7 => v0.9.8):

  [RuntimeException]
  Could not delete /var/www/librenms/vendor/psy/psysh/.editorconfig:

Updating SQL-Schema
PHP Fatal error:  require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66
Returned: 255
Updating submodules

Returned: 0
Cleaning up DB
PHP Fatal error:  require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep
:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66
Returned: 255
Fetching notifications
PHP Fatal error:  require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66
Returned: 255
Caching PeeringDB data
PHP Fatal error:  require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/librenms/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/librenms/vendor/composer/autoload_real.php on line 66
Returned: 255

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by murrant** [comment]
I'm not sure what you've done, probably ran some commands as root.  myclabs/deepcopy is NOT required in any way, it is a development dependency.
