### ISSUE TITLE
Global Variable to Disable HTMLPurifier

### ISSUE THREAD

**Issue by benfrosty** [librenms/librenms#9265]
This is a request for the ability via config.php to disable the HTMLPurifier for service parameters. A simple if exists then skip line 142 in includes/init.php could suffice as my manual testing has confirmed such. 

I need to pass xml/soap via the service parameter field and the HTMLPurifier is stripping the XML out and breaking the service check.  More details in my community [post](https://community.librenms.org/t/soap-xml-check-via-nagios-check-http/5617)

Much appreciated if possible so I do not have to introduce another monitoring tool.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
