### ISSUE TITLE
Please add Nexans Switch 

### ISSUE THREAD

**Issue by emilio1980** [librenms/librenms#9271]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here].
https://p.libren.ms/view/4a46aba6.
https://p.libren.ms/view/17cc803a
https://p.libren.ms/view/7a8ea321

- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Hier are mibs:
[Nexans_MIB_Files_V414.zip](https://github.com/librenms/librenms/files/2427460/Nexans_MIB_Files_V414.zip)

**Comment by PipoCanaja** [comment]
Hi @emilio1980 
You can test the Pull Request for the added support of Nexans Switches. Should me merged into master in a few days/weeks. 
Bye
