### ISSUE TITLE
ldap authentication broken ?

### ISSUE THREAD

**Issue by zamolxe** [librenms/librenms#9295]
For some reason my ldap admin account gets the level=0 in the mysql database at each login, hence no access to devices at all.

Running the ./scripts/auth_test.php -u <ldap_user> says the correct level = 10, which is correct.

Let me know what debug info is required to fix this one...

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
