### ISSUE TITLE
Support for Ericsson RX8200

### ISSUE THREAD

**Issue by tariksedlarevic** [librenms/librenms#9304]
Ericsson RX8200 Integrated Receiver/Decoder:
https://mediasolutions.ericsson.com/cms/wp-content/uploads/2017/08/RX8000-Reference-Guide.pdf

Discovery: https://p.libren.ms/view/fdfce703

Poller: https://p.libren.ms/view/db6c4511

SNMP: https://p.libren.ms/view/b6c39975

MIB:
[librenms_ericrsson_rx8200_mib.zip](https://github.com/librenms/librenms/files/2453675/librenms_ericrsson_rx8200_mib.zip)

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11677

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/support-for-ericsson-rx8200/11677/1
