### ISSUE TITLE
/api/v0/oxidized prints ciscoSMB as ciscosb and it not recognized by oxidized

### ISSUE THREAD

**Issue by aalmenar** [librenms/librenms#9307]
**Please do not post bugs or ask questions**

E, [2018-10-08T18:16:42.834501 #1089] ERROR -- : node {:name=>"192.168.x.x", :model=>"ciscosb", :groups=>nil} raised Oxidized::ModelNotFound with message 'ciscosb not found for node 192.168.x.x'

in oxidized here is the model:

https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ciscosmb.rb

it expects ciscosmb

Regards.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by aalmenar** [comment]
Ir not here, where should bug reports go? On librenms.org says: 

We have a few ways to get in touch, the most responsive and widely used is our Discord server. Please only use GitHub issues for reporting bugs or new devices. Feature requests should be posted on our community forum.
