### ISSUE TITLE
Permissions to access Config tab for non-admin users

### ISSUE THREAD

**Issue by rmagomedov** [librenms/librenms#9314]
Hello,

I have LibreNMS deployment with Oxidized integration. I noticed that users with access levels 'Normal user' or 'Global Read' cannot see and access 'Config' tab to view configuration of selected device. Only users with administrator permissions can have access to it.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
