### ISSUE TITLE
check_http hangs

### ISSUE THREAD

**Issue by Charlietje** [librenms/librenms#9340]
**check_http hangs**

Since today the check-services.php script makes following request and it hangs:
`Request:  '/usr/lib/nagios/plugins/check_http' '-H' 'www.example.com'  '--warning=5' '--critical=60' '--ssl' '--hostname=www.example.com' '--url="/"' '--string="example.com"'`

Everything is quoted.
I reverted to commit 3fc9e334b857b2c94beba0d0347c11a007efdce2.
Everything is working now:
`Request:  /usr/lib/nagios/plugins/check_http -H www.example.com --warning=5 --critical=60 --ssl --hostname=www.example.com --url="/" --string="example"`

**Comment by murrant** [comment]
This issue has been closed as it isn't classed as a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by murrant** [comment]
$  '/usr/lib/monitoring-plugins/check_http' '-H' '8.8.8.8' '--warning=5' '--critical=60' '--ssl' '--hostname=www.google.com' '--url="/"' '--string="html"'
HTTP CRITICAL: HTTP/1.1 400 Bad Request - string '"html"' not found on 'https://www.google.com:443"/"' - 1731 bytes in 0.127 second response time |time=0.127145s;5.000000;60.000000;0.000000;61.000000 size=1731B;;;0
$  '/usr/lib/monitoring-plugins/check_http' '-H' '8.8.8.8' '--warning=5' '--critical=60' '--ssl' '--hostname=www.google.com' '--url=/' '--string="html"'
HTTP CRITICAL: HTTP/1.1 200 OK - string '"html"' not found on 'https://www.google.com:443/' - 12896 bytes in 0.187 second response time |time=0.187275s;5.000000;60.000000;0.000000;61.000000 size=12896B;;;0
$  '/usr/lib/monitoring-plugins/check_http' '-H' '8.8.8.8' '--warning=5' '--critical=60' '--ssl' '--hostname=www.google.com' '--url=/' '--string=html'
HTTP OK: HTTP/1.1 200 OK - 12915 bytes in 0.201 second response time |time=0.201108s;5.000000;60.000000;0.000000;61.000000 size=12915B;;;0

**Comment by Charlietje** [comment]
Correct, removing the double quotes did the trick.

**Comment by laf** [comment]
If you need help post on the community forum.
