### ISSUE TITLE
ad_auth level is always set to 0 in mysql database

### ISSUE THREAD

**Issue by sjap** [librenms/librenms#9345]
Hello,

I've a strange issue. - I'm using auth_ad and the user is able to logon, but cant see any devices.. And it looks like the level in the mysql database is never set to 10, as it should be?

config.php:
$config['auth_ad_groups']['Func_Observium']['level'] = 10

<pre>
./auth_test.php -u librenms -d
User (15985):
  user_id => 15985
  username => librenms
  realname => Librenms User
  email => l
  descr =>
  level => 10
  can_modify_passwd => 0
Groups: CN=Func_Observium,OU=Func Groups,OU=Groups,OU=Administration,DC=int,DC=corp,DC=local
</pre>

<pre>
MariaDB [librenms]> select username, auth_type, level from users;
+----------+------------------+-------+
| username | auth_type        | level |
+----------+------------------+-------+
| admin    | mysql            |    10 |
| librenms | active_directory |     0 |
+----------+------------------+-------+
3 rows in set (0.00 sec)
</pre>

**Comment by sjap** [comment]
@laf I'm missing something?

It works if I change line 192 to: level = 10, in  LibreNMS/Authentication/ActiveDirectoryCommon.php

"$this->getUserlevel($entry['samaccountname'][0])" is also returning 10, but at some point it is not working..

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

If you have a fix please submit a pull request.
