### ISSUE TITLE
[FEATURE] Redesign alert template modal

### ISSUE THREAD

**Issue by crazy-max** [librenms/librenms#9346]
Hi guys,

I have started to work on a redesign of the alert template modal.

The goal is to merge the _Attach template to rules_ modal with the _Alert template_ modal with an enhanced select input. Here is a functional preview :

![image](https://user-images.githubusercontent.com/1951866/47177809-b8086080-d319-11e8-9f6a-c8d8d380eff9.png)

---

![image](https://user-images.githubusercontent.com/1951866/47177857-eb4aef80-d319-11e8-86ff-006a4cd57c85.png)

---

Autocompletion available too :

![image](https://user-images.githubusercontent.com/1951866/47177892-00278300-d31a-11e8-9708-a58a52ac3421.png)

---

I think it will drastically improve the user experience. What do you think ?

**Comment by laf** [comment]
Looks good to me. Closing this through as we only use this for new device support

**Comment by crazy-max** [comment]
Oh ok sorry :)

**Comment by laf** [comment]
It's cool - but honestly the update looks lovely :D

If you wanted to convert that page to Laravel you'd be more than welcome :)

**Comment by crazy-max** [comment]
@laf Ah I feel better now, the code seemed legacy to me and I didn't want to push legacy code anyway ^^
Do you have an example of legacy code migration to Laravel that I could rely on ?

Btw bug/feature support is only on Discord / Community forum ?
I think this is not really a good practice, we would have a better tracking and workflow using the GitHub ticketing tool. This would allow, among other things, the tracking of duplicate outcomes. Far from me to question your practices of course, I just want to give you my vision.

**Comment by laf** [comment]
> Do you have an example of legacy code migration to Laravel that I could rely on ?

I don't think we have any right now. I'm working on the bgp routing page but it's early stages right now.

> Btw bug/feature support is only on Discord / Community forum ?
> I think this is not really a good practice, we would have a better tracking and workflow using the GitHub ticketing tool + [Octobox](https://octobox.io/). This would allow, among other things, the tracking of duplicate outcomes. Far from me to question your practices of course, I just want to give you my vision.

We've used github before and it got to 100's of issues open and basically means the pressure is on maintainers to constantly triage the queue rather than doing code. The community forum is best placed for us as it has a number of people who help other users which you just don't see often on github.
