### ISSUE TITLE
New Device: Cisco Umbrella Virtual Appliance

### ISSUE THREAD

**Issue by HikerDave** [librenms/librenms#9351]
Cisco Umbrella (Commercial OpenDNS) has virtual appliances that you run to re-direct DNS queries to gain insight on your network.  They have recently implemented limited SNMP monitoring.

Link to documentation: [https://docs.umbrella.com/deployment-umbrella/docs/appendix-c-enable-snmp-monitoring](url)

Discovery: [https://p.libren.ms/view/6973d99b](url)
Poller: [https://p.libren.ms/view/fbe3a887](url)
SNMP: [https://p.libren.ms/view/a52ebd8d](url)

I attempted to build a file in includes/definitions/umbrella.yaml with the following:
os: umbrella
text: 'Umbrella Virtual Appliance'
type: server
icon: cisco
over:
    - { graph: device_bits, text: 'Device Traffic' }
    - { graph: device_processor, text: 'CPU Usage' }
    - { graph: device_mempool, text: 'Memory Usage' }
discovery:
    - sysObjectID:
        - .1.3.6.1.4.1.2021.

I am not sure what else needs to be done.

**Comment by laf** [comment]
@HikerDave Just test data if that's all you need from that device.

https://docs.librenms.org/#Developing/os/Test-Units/#example-workflow

If you can grab test data, please submit a pull request.

**Comment by laf** [comment]
No further info provided and no test data.
