### ISSUE TITLE
BGP sessions polling

### ISSUE THREAD

**Issue by mmarchand** [librenms/librenms#936]
on IOS-XR 4.3.x , BGP sessions are not properly polled/discovered:
- some status are incorrect:
For example sessions in state "shutdown" are shown as down (with an alert popping up)
- 32 bits ASN peers are not properly discovered (displays "AS0")
- pure IPv6 sessions are not discovered/polled at all

**Comment by laf** [comment]
Hi @mmarchand 

Can you paste an output online somewhere (please sanitise any sensitive data):

./discovery.php -h HOSTNAME -d -m bgp-peers
./poller.php -h HOSTNAME -d -m bgp-peers

For IPv6, I don't see anything for V6 either so I'll take a look at this.

**Comment by mmarchand** [comment]
here is the discovery : 
https://gist.githubusercontent.com/mmarchand/c7b143aa4351dfcd3bf9/raw/ce6b13c75f0ffdaa75834b402b9a91ecc4d429ee/discovery%20bgp
and the polling: 
https://gist.githubusercontent.com/mmarchand/38f341738cb10c9eab20/raw/3ec3105ee82489f1171e77e4b8daa95553f0ad8c/poller%20BGP

**Comment by laf** [comment]
Hi @mmarchand 

Ok, so the AS0 issue looks to be from your device:

BGP4-MIB::bgpPeerRemoteAs.37.49.236.121 0

That is the response from snmp, the AS number being returned is 0. I can see our BGP4-MIB is out of date, could you test with a newer version please:

```bash
cd /opt/librenms
wget ftp://ftp.cisco.com/pub/mibs/v2/BGP4-MIB.my
mv BGP4-MIB.my mibs/BGP4-MIB
```

Then re-run the poller and discovery commands.

When done, to revert back do:

```bash
cd /opt/librenms
git checkout -- mibs/BGP4-MIB
```

What peer are supposed to be shutdown?

**Comment by mmarchand** [comment]
the new MIB does not seem to help much, here are the logs : 
https://gist.githubusercontent.com/mmarchand/b5c66285f782569d520e/raw/1392d0374f2ca73bc8eeecce9f6449ad301bc315/discover%20BGP%20new%20MIB
https://gist.githubusercontent.com/mmarchand/ffeb7452f94602cf6c33/raw/11d7be48c40e5dac7e760e7931ddb6487b0559d7/poller%20BGP%20new%20MIB

37.49.236.121 should be ASN : 197133
RP/0/RSP0/CPU0:a9k1.dc3#show bgp sum | i 37.49.236.121
37.49.236.121     0 197133 3874847 3487067 1860611005    0    0     3w0d         21

for a shutdown peer, you can check 213.242.120.145 of AS 3356 : 
RP/0/RSP0/CPU0:a9k1.dc3#show bgp sum | i 3356         
213.242.120.145   0  3356 97439145 1813132        0    0    0    35w0d Idle (Admin)
this one is displayed as "BGP down" on librenms homepage

thanks

**Comment by laf** [comment]
@mmarchand 

For AS0, I don't think we can fix that :( SNMP on your device is responding back with the AS number as 0! 

We can however sort the frontpage box, it's showing as down as the check is only done against bgpPeerAdminStatus != 'start' which  matches your status which is 'stop', we need to exclude that from the check.

**Comment by mmarchand** [comment]
I think you can get it with polling 1.3.6.1.4.1.9.9.187.1.2.5.1.11 OID : 
www-data@graph-dc3:/opt/librenms$ snmpwalk -v2c -c *** a9k1.adm.dc3 1.3.6.1.4.1.9.9.187.1.2.5.1.11
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.5.23.24.5 = Gauge32: 6453
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.10 = Gauge32: 6939
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.24 = Gauge32: 35625
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.27 = Gauge32: 42456
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.32 = Gauge32: 34177
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.40 = Gauge32: 39605
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.42 = Gauge32: 8560
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.58 = Gauge32: 8220
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.60 = Gauge32: 8426
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.61 = Gauge32: 8426
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.63 = Gauge32: 5410
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.68 = Gauge32: 20562
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.72 = Gauge32: 8304
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.85 = Gauge32: 42473
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.86 = Gauge32: 33930
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.96 = Gauge32: 41690
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.111 = Gauge32: 43142
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.118 = Gauge32: 16509
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.120 = Gauge32: 52075
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.121 = Gauge32: 197133
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.153 = Gauge32: 8304
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.154 = Gauge32: 29169
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.156 = Gauge32: 15547
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.168 = Gauge32: 20940
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.174 = Gauge32: 32934
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.175 = Gauge32: 32934
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.178 = Gauge32: 8966
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.193 = Gauge32: 33930
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.228 = Gauge32: 24482
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.232 = Gauge32: 198792
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.250 = Gauge32: 51706
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.236.251 = Gauge32: 51706
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.237.3 = Gauge32: 13285
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.237.25 = Gauge32: 46489
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.237.26 = Gauge32: 46489
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.237.29 = Gauge32: 15133
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.237.43 = Gauge32: 2906
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.237.49 = Gauge32: 13335
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.49.237.50 = Gauge32: 2906
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.37.77.36.6 = Gauge32: 44530
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.46.33.93.89 = Gauge32: 3257
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.62.115.40.77 = Gauge32: 1299
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.62.210.17.31 = Gauge32: 65500
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.62.210.18.21 = Gauge32: 65500
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.62.210.175.209 = Gauge32: 65500
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.130.117.20.1 = Gauge32: 174
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.149.11.115.9 = Gauge32: 174
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.195.154.0.14 = Gauge32: 65500
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.195.154.1.3 = Gauge32: 65500
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.195.154.1.5 = Gauge32: 65500
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.195.154.1.7 = Gauge32: 65500
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.195.154.1.37 = Gauge32: 65500
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.195.154.1.39 = Gauge32: 64999
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.195.154.1.155 = Gauge32: 65500
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.195.154.3.249 = Gauge32: 21502
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.1.4.213.242.120.145 = Gauge32: 3356
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.6.104.0.0.0.3.0.0.0.0.16.0.9.177 = Gauge32: 3257
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.0.16 = Gauge32: 6939
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.0.36 = Gauge32: 35625
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.0.39 = Gauge32: 42456
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.0.50 = Gauge32: 34177
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.0.64 = Gauge32: 39605
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.0.66 = Gauge32: 8560
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.0.88 = Gauge32: 8220
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.0.96 = Gauge32: 8426
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.0.97 = Gauge32: 8426
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.0.99 = Gauge32: 5410
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.0.104 = Gauge32: 20562
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.0.114 = Gauge32: 8304
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.0.133 = Gauge32: 42473
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.0.134 = Gauge32: 33930
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.1.17 = Gauge32: 43142
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.1.24 = Gauge32: 16509
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.1.32 = Gauge32: 52075
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.1.83 = Gauge32: 8304
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.1.84 = Gauge32: 29169
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.1.86 = Gauge32: 15547
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.1.104 = Gauge32: 20940
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.1.116 = Gauge32: 32934
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.1.117 = Gauge32: 32934
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.1.120 = Gauge32: 8966
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.1.147 = Gauge32: 33930
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.2.40 = Gauge32: 24482
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.2.50 = Gauge32: 198792
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.2.80 = Gauge32: 51706
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.0.2.81 = Gauge32: 51706
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.1.0.3 = Gauge32: 13285
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.1.0.41 = Gauge32: 15133
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.1.0.67 = Gauge32: 2906
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.1.0.73 = Gauge32: 13335
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.7.248.0.84.0.0.0.0.0.0.0.1.0.80 = Gauge32: 2906
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.9.120.0.2.0.27.0.0.0.0.0.72.0.1 = Gauge32: 174
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.11.200.0.0.0.1.0.0.0.0.0.0.0.2 = Gauge32: 65500
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.11.200.0.0.0.1.0.0.0.0.0.0.0.14 = Gauge32: 65500
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.11.200.0.0.0.1.0.0.0.0.0.0.0.70 = Gauge32: 65500
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.11.200.0.0.0.1.0.0.0.0.0.0.0.186 = Gauge32: 65500
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.11.200.0.1.0.0.0.0.0.0.0.0.0.33 = Gauge32: 65500
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.11.200.4.0.0.2.0.0.0.0.0.0.0.6 = Gauge32: 21502
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.25.0.0.5.0.2.0.2.0.0.0.0.41.209 = Gauge32: 3356
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.32.1.32.0.48.128.9.124.0.0.0.0.0.0.0.1 = Gauge32: 1299
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.42.1.3.224.18.0.0.0.0.0.0.0.0.0.0.5 = Gauge32: 6453
iso.3.6.1.4.1.9.9.187.1.2.5.1.11.2.16.42.2.14.92.0.2.0.2.0.0.0.0.0.0.0.1 = Gauge32: 44530

**Comment by laf** [comment]
Those are from the CISCO-BGP4-MIB, I guess we can update so that we check this MIB first for cisco devices and if nothing exists fall back to the current method.

This might take a little bit of time to organise so please bear with us.

**Comment by mmarchand** [comment]
sure, it probably require a bit of code here, thanks :)
(it probably allows to detect IPv6 sessions too I think , seeing the last entries of the snmpwalk)

**Comment by laf** [comment]
@mmarchand 

Ok, just submitted a PR which hopefully fixes all of this. Now uses CISCO-BGP4-MIB where possible.

If you are able to test that would be ace, this assumes you don't have any custom changes locally:

git remote add laf https://github.com/laf/librenms.git
git remote update laf
git checkout issue-936

Needs a full discovery and poll to pick everything up.

Once done, go back to master by doing:

git checkout master

**Comment by mmarchand** [comment]
sure, I'll test it tonight or tomorrow and report back
thank you

**Comment by laf** [comment]
Don't bother testing this just yet, come across some issues with devices not support CISCO-BGP4-MIB.

**Comment by mmarchand** [comment]
just added the patch here, it seems to work fine with all my BGP routers,
the only issue I can see so far is IPv6 neighbors are displayed like this "20:01:07:f8:00:43:00:00:00:00:00:00:46:51:00:01" but not a big deal
I will let it run with the patch and report back any other issues
thanks

**Comment by laf** [comment]
@mmarchand I wouldn't recommend running it at the moment, I have discovered some bugs which I've mostly fixed. Need to sort the IPv6 side you said above.

**Comment by laf** [comment]
This has been merged in now for a while, aside from one bug which was fixed it looks all good now.
