### ISSUE TITLE
Add/change sorting in device overview

### ISSUE THREAD

**Issue by eb0815** [librenms/librenms#9383]
FEATURE REQUEST

* change/add sorting criteria to display name (as set by force_ip_to_sysname)
* alternately add sorting criteria snmp_sysname

EXPLANATION

When adding devices, they can end up with different hostname entries in the database, sometimes IP, sometimes FQDN, sometimes abbreviated hostnames.

The device overview can be sorted by different criteria atm, which is nice, BUT sorting by "Device" sorts by the device name from the database, not by the display name, which is different if you have "force_ip_to_sysname" set to true. There is no sorting criteria "snmp_sysname".

My request would be to either add or change the sorting criteria to allow sorting by either the snmp_sysname or by the display name (which may or may not be the snmp sysname).

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
