### ISSUE TITLE
Distributed polling setup

### ISSUE THREAD

**Issue by mmarchand** [librenms/librenms#939]
RRDCached configuration : 
when rrdcached is used over TCP, configuration should be : 
$config['rrdcached_dir'] = ".";
if it is empty ( "" ), rrdcached daemon will refuse to update the RRD as it will receive a "/hostname/port-xxx.rrd" path and will refuse it because it considers it as a full (not relative) path

when using remote daemon, it should be checked that all paths sent are relative

**Comment by f0o** [comment]
That's correct and why `$config['rrdcached_dir]` is supposed to contain the relative patch to rrdcached's base-directory.
This should be in the docs.
