### ISSUE TITLE
New device support Sonus SBC 5000

### ISSUE THREAD

**Issue by DGothmin** [librenms/librenms#9416]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery - https://p.libren.ms/view/017c0ddd
Poller - https://p.libren.ms/view/1087b83f
SNMPWALK - https://p.libren.ms/view/e2f45ff7

Do not have much more details,
Thank you

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by DGothmin** [comment]
This might help..

http://www.circitor.fr/Mibs/Mib/S/SONUS-COMMON-MIB.mib

**Comment by laf** [comment]
None of your data has information in it. You need to replace the things like HOSTNAME for your information.
