### ISSUE TITLE
APC Netbotz 250 wireless sensor

### ISSUE THREAD

**Issue by salt-lick** [librenms/librenms#9417]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ X ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/6353e40e
https://p.libren.ms/view/c12b3f26
https://p.libren.ms/view/89916c62

- [ X ] Please provide as much detail as possible.

The Netbotz 250 has the idea of wireless sensors - both temperature and temperature/humidity sensors

Few issues:

- The correct name is not being pulled into Librenms for the wireless sensor. "Wireless Temp Sensor" in this instance
- The wireless sensor does not follow the whatever unit of measure that is set on the device. 
- Nice to have: it would be awesome to have wirelessSensorStatusBattery.1 ( 29 = 2.9V in this instance ) and wirelessSensorStatusRssi.1 ( 83 = 83 % in this instance ) add in as polled OIDs

Image: https://i.imgur.com/PpfiGsn.png

- [ X ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11643

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/apc-netbotz-250-wireless-sensor/11643/1
