### ISSUE TITLE
New Device Support - Dell Blade M610

### ISSUE THREAD

**Issue by DGothmin** [librenms/librenms#9418]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Please add support for Dell M610 Blade server, it picked up now but won't give any monitors,

./discovery.php -h HOSTNAME -d | ./pbin.sh
https://p.libren.ms/view/1a3e4f3c

./poller.php -h HOSTNAME -r -f -d | ./pbin.sh
https://p.libren.ms/view/12e54a60

snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh
https://p.libren.ms/view/162cbf4f

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
> * 
> 
> Please add support for Dell M610 Blade server, it picked up now but won't give any monitors,

What's a monitor?

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11642

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-support-dell-blade-m610/11642/1
