### ISSUE TITLE
Need to add support for Cisco sg550x switches

### ISSUE THREAD

**Issue by tersus222** [librenms/librenms#9419]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
  
[discovery.txt](https://github.com/librenms/librenms/files/2548934/discovery.txt)
[poller.txt](https://github.com/librenms/librenms/files/2548952/poller.txt)

- [ x] Please provide as much detail as possible.
        Added new sg550x switch to librenms. Switch is being classified as a generic device. Older sg500x switches are working ok. Just not the newer versions

.

- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by tersus222** [comment]
Current os version 2.4.0.94

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by tersus222** [comment]
Tried to run the command below but I get an error. Comunity name and ip have been sanitized.

[admin@librenms librenms]$ snmpbulkwalk -OUneb -v2c -c <communityname> <xx.xx.xx.200> .  | ./pbin.sh
Paste endpoint: https://p.libren.ms/api/create
title:
name: admin
private: 1
expire: 0
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.12.2</center>
</body>
</html>

**Comment by laf** [comment]
You'll need to use an alternative pastebin service then

**Comment by tersus222** [comment]
[sg550x-sysObjectid.txt](https://github.com/librenms/librenms/files/2600308/sg550x-sysObjectid.txt)
[sg250x-sysObjectid.txt](https://github.com/librenms/librenms/files/2600309/sg250x-sysObjectid.txt)
