### ISSUE TITLE
Please add support for cisco sg250x switches

### ISSUE THREAD

**Issue by tersus222** [librenms/librenms#9420]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
[discovery.txt](https://github.com/librenms/librenms/files/2549323/discovery.txt)
[poller.txt](https://github.com/librenms/librenms/files/2549324/poller.txt)

- [ x] Please provide as much detail as possible.
Need to add support to librenms for scanning sg250x cisco switches
Current os version 2.4.0.94
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

I would however, add the data to your other issue #9419
