### ISSUE TITLE
Eltek Valere BC2000 state sensors not discovered / polled correctly. 

### ISSUE THREAD

**Issue by salt-lick** [librenms/librenms#9421]
**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ X ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/d26b5559
https://p.libren.ms/view/28d9f88e
https://p.libren.ms/view/2c61971b

- [ X ] Please provide as much detail as possible.
The state sensors are not correctly being discovered / polled. 

This appears to be the newest  / best Eltek BC 2000 mib.

Again, If I need to provide something else, please let me know. 
![Image of Discovered Sensors](https://i.imgur.com/f6V9gyh.png)

- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by cron410** [comment]
I'll be following this issue as well. We have 20-25 BC2000 controllers in our network, only 4 are accessible via network at this time.

**Comment by salt-lick** [comment]
See comment https://github.com/librenms/librenms/issues/6978#issuecomment-332560469 for the latest MIB for the BC2000

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/eltek-valere-bc2000-state-sensors-not-discovered-polled-correctly/11641/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11641
