### ISSUE TITLE
New device - Ekinops

### ISSUE THREAD

**Issue by Najihel** [librenms/librenms#9451]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

---

Hello,

Please add support of Ekinops product (Ekinops 360 Plateform - https://www.ekinops.com/fr/)

OS Name : Ekinops 360

### MGMT2 Card (Old management card) :
* Discovery : https://p.libren.ms/view/02abd6e0
* Poller : https://p.libren.ms/view/de6915ef
* snmpbulkwalk : https://p.libren.ms/view/b001ab73

### MGMT4 Card (New management card) :
* Discovery : https://p.libren.ms/view/7457d7f5
* Poller : https://p.libren.ms/view/e6e6319f
* snmpbulkwalk : https://p.libren.ms/view/9a7a8a90

### Pictures
OS : ![ekinops_icon](https://user-images.githubusercontent.com/1873677/48572998-51bc3100-e90b-11e8-9fb1-771dd23c43b1.png)
Logo : ![ekinops_large](https://user-images.githubusercontent.com/1873677/48572999-5254c780-e90b-11e8-8d1d-35df54d157a8.png)

### MIBs
MIBs : [R63880 MIB files.zip](https://github.com/librenms/librenms/files/2586523/R63880.MIB.files.zip)

**Comment by Najihel** [comment]
Some information : 

### sysName

sysName isn't configurable on the SNMP agent but the hostname is available on OID : 

```
mgnt2GigmLogicalName => iso.3.6.1.4.1.20044.7.1.5
iso.3.6.1.4.1.20044.7.1.5.0 = STRING: "XXXX"
```

### $version

Software version is `5.2.152`

```
mgnt2RinvSoftwarePackage => .1.3.6.1.4.1.20044.7.6.2

iso.3.6.1.4.1.20044.7.6.2.0 = STRING: "MGNT SOFTWARE PACKAGE
     Mnemonic                  :  MGNT2
     Release Name              :  Release 5.2.152
     Release Part Number       :  5XXXX1
     Release Date (yymmdd)     :  140115
     Config Part Number        :  3XXXX1
     Config Date (yymmdd)      :  140115
"
```
### $hardware :

It could be `C600 0XXXX6 - PM-MGNT2 0XXXX9`

#### BackPlane :
```
mgnt2RinvBackpanel => .1.3.6.1.4.1.20044.7.6.8

iso.3.6.1.4.1.20044.7.6.8.0 = STRING: "CHASSIS HARDWARE
       Vendor                    :  EKINOPS
       Mnemonic                  :  C600
       Part Number               :  2XXXX2
       Serial Number             :  0XXXX6
       Date Code (yymmddww)      :  12032613
"
```
#### Management card :
```
mgnt2RinvHwPlatform => .1.3.6.1.4.1.20044.7.6.1

iso.3.6.1.4.1.20044.7.6.1.0 = STRING: "MGNT HARDWARE     
     Vendor Name               :  EKINOPS
     Mnemonic                  :  PM-MGNT2
     Part Number               :  2XXXX2
     Serial Number             :  0XXXX9
     Date Code (yymmddww)      :  11101441
"
```

**Comment by Najihel** [comment]
# Some information for MGMT4 : 

## sysName

sysName isn't configurable on the SNMP agent but the hostname is available on OID : 

**mgnt2GigmLogicalName** => `iso.3.6.1.4.1.20044.7.1.5`

```
iso.3.6.1.4.1.20044.7.1.5.0 = STRING: "XXXX"
```

## $version

Software version is `MGNT4 - 6.3.911`

**mgnt2RinvSoftwarePackage** => .1.3.6.1.4.1.20044.7.6.2

```
iso.3.6.1.4.1.20044.7.6.2.0 = STRING: "MGNT SOFTWARE PACKAGE
    Mnemonic                         :  MGNT4
    Active Release Name              :  Release 6.3.911
    Active Release Part Number       :  5XXXX1
    Active Release Date (yymmdd)     :  180829
    Active Config Part Number        :  3XXXX1
    Active Config Date (yymmdd)      :  180829
    Standby Release Name             :  Release 6.3.910
    Standby Release Part Number      :  5XXXX1
    Standby Release Date (yymmdd)    :  180531
    Standby Config Part Number       :  3XXXX1
    Standby Config Date (yymmdd)     :  180531
"
```

## $hardware :

It could be `C600HC - PM-MGNT4`

### BackPlane :

**mgnt2RinvBackpanel** => `.1.3.6.1.4.1.20044.7.6.8`

```
iso.3.6.1.4.1.20044.7.6.8.0 = STRING: "CHASSIS HARDWARE    
    Vendor                    :  EKINOPS
    Mnemonic                  :  C600HC
    Part Number               :  2XXXX1
    Serial Number             :  001881
    Date Code (yymmddww)      :  14050518
"
```

### Management card :

**mgnt2RinvHwPlatform** => `.1.3.6.1.4.1.20044.7.6.1`

```
iso.3.6.1.4.1.20044.7.6.1.0 = STRING: "MGNT HARDWARE    
    Vendor Name               :  EKINOPS
    Mnemonic                  :  PM-MGNT4
    Part Number               :  2XXXX1
    Serial Number             :  0XXXX9
    Date Code (yymmddww)      :  14070927
"
```

## $serial :

It could be `C600HC 0XXXX1 - PM-MGNT4 0XXXX9`

### BackPlane :

**mgnt2RinvBackpanel** => `.1.3.6.1.4.1.20044.7.6.8`

```
iso.3.6.1.4.1.20044.7.6.8.0 = STRING: "CHASSIS HARDWARE    
    Vendor                    :  EKINOPS
    Mnemonic                  :  C600HC
    Part Number               :  2XXXX1
    Serial Number             :  0XXXX1
    Date Code (yymmddww)      :  14050518
"
```

### Management card :

**mgnt2RinvHwPlatform** => `.1.3.6.1.4.1.20044.7.6.1`

```
iso.3.6.1.4.1.20044.7.6.1.0 = STRING: "MGNT HARDWARE    
    Vendor Name               :  EKINOPS
    Mnemonic                  :  PM-MGNT4
    Part Number               :  2XXXX1
    Serial Number             :  0XXXX9
    Date Code (yymmddww)      :  14070927
"
```

**Comment by Najihel** [comment]
The feature request https://github.com/librenms/librenms/issues/5386 could be very usefull for Ekinops product.

Each specific card have to be request by the SNMP community + slot number.

For example : 
* Management card : public
* Slot 1 : public1
* Slot 2 : public2
* Slot X : publicX

**Comment by logininet** [comment]
Hi Najihel/
Unfortunately, I don't know enough about Ekinops, so maybe you Help me/
I have Ekinops C600HC device/
I  need mips/oid  signals level  and FEC errors for will make graphs in Grafana dashboard/
Do you help me?/
Thanks/

**Comment by Najihel** [comment]
Hi @logininet 

> Each specific card have to be request by the SNMP community + slot number.
> 
> For example :
> 
> * Management card : public
> * Slot 1 : public1
> * Slot 2 : public2
> * Slot X : publicX

So, you need to known the OID which contains the information and you need to convert it. For example on PM1064 the Rx in mW/dBm : 

![image](https://user-images.githubusercontent.com/1873677/69542338-8a193500-0f8b-11ea-9493-970eb48fbd90.png)

![image](https://user-images.githubusercontent.com/1873677/69542346-8e455280-0f8b-11ea-9dab-17d768da1114.png)

You need to request the right documentation to Ekinops support : https://www.ekinops.com/support/ekinops360-support

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11640

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-ekinops/11640/1
