### ISSUE TITLE
cisco-pw set port_id to zero in pseudowires mysql table

### ISSUE THREAD

**Issue by govenka** [librenms/librenms#9468]
Hello,

We have 4 Cisco ASR 9010 and we are using librenms. But when we discovered the ASR, the pseudowires list was empty. I looked iin table pseudowires avec i see port_id to zero in all pseudowires. 

In the page /opt/librenms/html/pages/device/pseudowires.inc.php we see : 

foreach (dbFetchRows('SELECT * FROM pseudowires AS P, ports AS I WHERE P.port_id = I.port_id AND I.device_id = ? ORDER BY I.ifDescr', array($device['device_id'])) as $pw_a) {

then with a port_id to zero in pseudowires table, we have zero record. 

Is there a patch for this ? 

Best regards
Christophe Delaigue

-----------------------------
+---------------+-----------+---------+----------------+-------------+---------+------------+--------------+------------+--------------+-------------+-------------------------------------------------+
| pseudowire_id | device_id | port_id | peer_device_id | peer_ldp_id | cpwVcID | cpwOid     | pw_type      | pw_psntype | pw_local_mtu | pw_peer_mtu | pw_descr                                        |
+---------------+-----------+---------+----------------+-------------+---------+------------+--------------+------------+--------------+-------------+-------------------------------------------------+
|          4875 |       476 |       0 |              0 |       10150 |     999 | 2147483647 | ethernet     | mpls       |            0 |           0 | test999:p2p1                                    |
|          4876 |       476 |       0 |              2 |       10150 |     682 | 2147483647 | ethernetVPLS | mpls       |            0 |           0 | CFI:VPLS_CFI_FTTH02:VFI_CFI_FTTH02              |
|          4877 |       476 |       0 |              5 |       10150 |     682 | 2147483647 | ethernetVPLS | mpls       |            0 |           0 | CFI:VPLS_CFI_FTTH02:VFI_CFI_FTTH02              |
|          4878 |       476 |       0 |              8 |       10150 |     682 | 2147483647 | ethernetVPLS | mpls       |            0 |           0 | CFI:VPLS_CFI_FTTH02:VFI_CFI_FTTH02              |

**Comment by govenka** [comment]
And why we have port_id in pseudowire :) there is no port in a pseudowire ^^

**Comment by govenka** [comment]
Why did you closed the issue ?

**Comment by kkrumm1** [comment]
@govenka Issues don't go here, you need to post this on the community forums or on discord. This is only for new device request. This was outlined when you open this but you didn't read and deleted everything. 
https://community.librenms.org/
