### ISSUE TITLE
New device - NET VISION 7

### ISSUE THREAD

**Issue by overflower83** [librenms/librenms#9473]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

NETVISION 
MIB File: https://www.socomec.com/net-vision-7-software_en.html

Taken from NET VISION 7
Discovery: https://p.libren.ms/view/243ee259
Poller: https://p.libren.ms/view/204cd8a9
SNMP Bulk Walk: https://p.libren.ms/view/4db28bd5

**Comment by danislav** [comment]
Guys, did you manage to take a look at this? That's the SOCOMEC UPS NetVision card.
Let me paste again the files needed to refresh the issue:
MIB FILE: https://p.libren.ms/view/2479a000
Discovery: https://p.libren.ms/view/407d6f22
Poller: https://p.libren.ms/view/0d93098e
SNMP Walk: https://p.libren.ms/view/9bc147e3

For the current netvision yaml file I had to add "armv5tejl" to discover the ups as netvision.

**Comment by overflower83** [comment]
Where did you add the "armv5tejl" exactly in the yaml file?

**Comment by danislav** [comment]
Here: https://p.libren.ms/view/1a891bb3
Is that after the last update of the netvision firmware the card reports the sysDescr as:
"Linux localhost.localdomain 2.6.37.6-lsp-3.2.5_stm24_0012-spear3xx #105 Mon Dec 24 14:49:28 CST 2018 armv5tejl"
Which librenms can not link to netvision.
What is the sysDescr of your netvision?

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-net-vision-7/11639/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11639
