### ISSUE TITLE
Syslog-ng.conf incompatibility version

### ISSUE THREAD

**Issue by nasked** [librenms/librenms#9477]
Hi:
I activated my syslog option a few days ago. At the beginning syslog worked fine, but now syslog screen is blank. I checked configuration and report  that syslog-ng.conf is out of version. syslog-ng.conf start with @version:3.5 but my syslog-ng version is 3.13. Where can i find information to modify my syslog-ng.conf file?

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
