### ISSUE TITLE
inverse option of graph.php is ignored

### ISSUE THREAD

**Issue by mmarchand** [librenms/librenms#948]
in includes/graphs/common.inc.php, it checks for $_GET['inverse'] but in dependant scripts like includes/graphs/generic_data.inc.php it checks for a "if ($inverse)"

I have tested an easy fix which is to add $inverse=1 in common.inc.php : 
if ($_GET['inverse']) { $in = 'out'; $out = 'in'; $inverse=1; } else { $in = 'in'; $out = 'out'; }

it seems to do the job with this

**Comment by laf** [comment]
Hi @mmarchand 

That does indeed look to be an issue or a fix. I'd probably change it to:

```php
if ($_GET['inverse']) {
    $inverse = TRUE;
}
```

Are you going to submit a pull request?
