### ISSUE TITLE
New Device: Delta STS12002SR000A4

### ISSUE THREAD

**Issue by ndoo** [librenms/librenms#9484]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Type: Power
Brand: Delta
MIBs:
[Sensor.mib.txt](https://github.com/librenms/librenms/files/2624202/Sensor.mib.txt)
[Delta-ATS.mib.txt](https://github.com/librenms/librenms/files/2624203/Delta-ATS.mib.txt)

Discovery: https://p.libren.ms/view/65fccba4
Poller: https://p.libren.ms/view/744c44a7
snmpbulkwalk: https://p.libren.ms/view/c39f7be5

**Comment by PipoCanaja** [comment]
Hi @ndoo 
The snmpwalk data you provided is an Ubiquity UAP ... So please reopen this case once you can provide the correct snmpwalk data. 
Thanx
