### ISSUE TITLE
Support for DKTcomega Juma/Forsete Fiber CPE

### ISSUE THREAD

**Issue by jjonssondk** [librenms/librenms#9494]
Please add support for DKTcomega Juma/Forsete Fiber CPEs.

Discovery, Poller, SNMP and MIBs from manufacturer to be found here:
https://mega.nz/#F!6dcSDaqS!gMD3nnU4WmKW34DE_NZkPA

**Comment by jjonssondk** [comment]
https://p.libren.ms/view/517746b2
https://p.libren.ms/view/5edea44f
https://p.libren.ms/view/6cd5b1a1

MIB:
https://dktcomega.com/wp-content/uploads/2017/03/MIB_ver06.zip

**Comment by PipoCanaja** [comment]
Hello @jjonssondk

You can test the PR #9732 and ask for addons or changes if necessary. 

Bye

**Comment by jjonssondk** [comment]
Sorry, I'm not sure what to do?

`$ $ ./scripts/github-apply 5926
Checking patch .github/PULL_REQUEST_TEMPLATE.md...
error: while searching for:

- [ ] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

error: patch failed: .github/PULL_REQUEST_TEMPLATE.md:6
error: .github/PULL_REQUEST_TEMPLATE.md: patch does not apply
Checking patch scripts/github-apply...
error: scripts/github-apply: already exists in working directory
Checking patch scripts/github-remove...
error: scripts/github-remove: already exists in working directory
you have mail
`

**Comment by PipoCanaja** [comment]
Hi,

The PR# is 9732, so "./scripts/github-apply 9732" should apply on top of an up to date LibreNMS server.

Bye

**Comment by PipoCanaja** [comment]
Hi @jjonssondk 
Did you get a chance to test this ? 
Bye
