### ISSUE TITLE
Alert delay and cron start time variation

### ISSUE THREAD

**Issue by Ultra2D** [librenms/librenms#950]
For testing purposes I created an alert that should email every minute. It worked, but sometimes the time between emails was two minutes. Apparently on my system the cron job for alerts.php mostly starts on second 1, but sometimes on second 2 of every minute.
The default alerts have a delay of 300 seconds. The same thing occurs in this case: emails will not always be sent exactly five minutes apart.

I am not sure this needs fixing, but detracting a couple of seconds from the measured delay would probably fix this.

**Comment by f0o** [comment]
This is only fix'able with a daemon running to ensuring precise timing

**Comment by f0o** [comment]
I will add a sliding window to the delay that's configurable so the delay would also be valid for +/-10s (for example)
This doesnt solve the issue but it would make it more unlikely to run into it.

For the long-term a dispatcher-daemon will be more effective.
