### ISSUE TITLE
ddm support for d-ling dgs-3200

### ISSUE THREAD

**Issue by USaidov** [librenms/librenms#9543]
*It  is not showing ddm graphs for d-link dgs-3100. Librenms doesn't even discovers ddm. 
*When i do snmpwalk -Os -c public -v 2c [switch ip] 1.3.6.1.4.1.171.12.72  i'll getting all date related to ddm. 
*Mib for ddm:  DDM-MGMT-MIB: http://ftp.dlink.ru/pub/Switch/DGS-3120-24SC/SNMP/

**Comment by laf** [comment]
Thanks for the new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.
