### ISSUE TITLE
Device Request: Brultech GreenEye Monitor(GEM)

### ISSUE THREAD

**Issue by SirMaple** [librenms/librenms#9549]
How difficult would it be to have the Brultech GEM added to Librenms? Would love to see it added.

Would have to use the btmon.py script written by Matthew Wall. Located here -> http://lancet.mit.edu/mwall/projects/power/releases/mtools-1.1.3/bin/btmon.py

**Comment by laf** [comment]
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by SirMaple** [comment]
I guess this one won't ever happen because the device itself does not have snmp and depends on a script to run on another machine to get the data from the GEM using the btmon.py script.

When I have some spare time in a few months I'll see what I can accomplish.
