### ISSUE TITLE
UniFi sensor support removed in 1.46-57-ge0e3e08bf 

### ISSUE THREAD

**Issue by rasssta** [librenms/librenms#9551]
After the daily script upgraded to 1.46, all UniFi sensors were removed. See attached screenshot.

![image](https://user-images.githubusercontent.com/4455235/50053002-b5659400-012d-11e9-8bac-73ab7759d9fa.png)

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by rasssta** [comment]
New device? It has been supported before 1.46 so I would consider it as a bug that has caused its removal. Or have you removed its support on purpose?

**Comment by TheGreatDoc** [comment]
@rasssta what he means is "issues" in github are only for new device request. For bugs you should go to the community forum.

Said that, murrant already did linking your issue: https://community.librenms.org/t/unifi-switch-no-longer-has-sensors/6529

**Comment by laf** [comment]
It really would help everyone if you just read the template text when creating an issue, it would have told you that this isn't the place for bugs.
