### ISSUE TITLE
PR #9546 results in JunOS platform detection quirks in combination with virtual-chassis

### ISSUE THREAD

**Issue by martijn-schmidt** [librenms/librenms#9554]
Hello,

PR #9546 has resulted in Platform being detected as `Juniper Virtual Chassis Switch` when a set of devices is stacked. Hence, no more possibility to see whether it is for example an EX2300 or EX3400 virtual-chassis.

What do we think about modifying `if (!empty($boxDescr))` to become `if (!empty($boxDescr) && ($boxDescr != "Juniper Virtual Chassis Switch"))` in `includes/polling/os/junos.inc.php` so that we restore the previous functionality? It's possible to build a virtual-chassis of multiple switch models, but only for higher end hardware:

https://www.juniper.net/documentation/en_US/junos/topics/concept/virtual-chassis-ex4200-overview.html#jd0e75

Example:
```
mschmidt@nlrtm1-librenms1:~$ snmpwalk -v2c -cremoved -m JUNIPER-MIB -M /opt/librenms/mibs hostname jnxBoxDescr
JUNIPER-MIB::jnxBoxDescr.0 = STRING: Juniper Virtual Chassis Switch
```

**Comment by kkrumm1** [comment]
FYI you should post this in the community forums or in the discord server. This not for this it’s only for new device requests.

**Comment by murrant** [comment]
Also, if you think you have a fix just create a pull request.
