### ISSUE TITLE
Incorrect traffic bill calculation

### ISSUE THREAD

**Issue by wimg** [librenms/librenms#9564]
It seems https://github.com/librenms/librenms/issues/2066 is not fixed. We're experiencing a similar problem : the average traffic is completely different than the average measured.
In the screenshot below it is obvious that the sum of the average in+out is 1.80 + 2.11 = 3.91kbps but in the usage it is listed as 31.20kbps, almost 10 times as high.
This happens on all our devices.
![image](https://user-images.githubusercontent.com/313511/50188625-7a788180-0322-11e9-8cd0-a915db4da8e5.png)

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
