### ISSUE TITLE
missing documentation: nfsv3 stats application switch

### ISSUE THREAD

**Issue by fionnb** [librenms/librenms#9571]
There is that switch on the device applications page for nfs v3 statistics.
This function, however, is mentioned nowhere in the docs or even in the application section there.
Moreover, not even a google search for "librenms nfsv3 stats" will reveal to you how it is meant to be used. Only extensive searching might finally get experienced users to the original [pull request](https://github.com/librenms/librenms/pull/6320) which itself mentions a shell script using a broken link. After looking some more you might find out that not only the script location has changed but also the script name in the new location. 
Then FINALLY, looking into the [script source](https://github.com/librenms/librenms-agent/blob/master/agent-local/nfsstats), you will find how to configure snmpd to deliver the data needed for the Application switch.

**Comment by kkrumm1** [comment]
Thank you but this is not the place for this.. 

This issue has been closed as it isn't classed as a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by kkrumm1** [comment]
You can report in community.librenms.org or in our discord server. Just post it.

Kevin

> On Dec 21, 2018, at 4:27 AM, fionnb <notifications@github.com> wrote:
> 
> Sorry to bother, but how are bugs meant to be reported here?
> 
> Your FAQ states: Bugs. Found one? We want to know about it.
> 
> Unfortunately, the FAQ leaves out HOW exactly you want to get to know, if not here.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 










CONFIDENTIALITY NOTICE: This email & attached documents may 
contain confidential information. All information is intended only for the 
use of the named recipient. If you are not the named recipient, you are not 
authorized to read, disclose, copy, distribute or take any action in 
reliance on the information and any action other than immediate delivery to 
the named recipient is strictly prohibited. If you have received this email 
in error, do not read the information and please immediately notify sender 
by telephone to arrange for a return of the original documents. If you are 
the named recipient you are not authorized to reveal any of this 
information to any other unauthorized person. If you did not receive all 
pages listed or if pages are not legible, please immediately notify sender 
by phone.
