### ISSUE TITLE
Qos huawei AR2240 no found

### ISSUE THREAD

**Issue by nurhambali** [librenms/librenms#9577]
Hi,

i'am adding device router huawei AR2240 with Huawei VRP 5.160 (V200R005C20SPC200), but i can't show Qos after i check Mib librenms oid : 1.3.6.1.4.1.2011.5.25.32.1.1.5.6.4.1. hwCBQoSPolicyStatClassifierMatchedByte not found, how to solution my problem.

**Comment by kkrumm1** [comment]
You are asking for help this not the place for this. 

This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
