### ISSUE TITLE
Schneider PM8000 support

### ISSUE THREAD

**Issue by salt-lick** [librenms/librenms#9595]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ X ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/4447c4b0
https://p.libren.ms/view/242fa5e3
https://p.libren.ms/view/9bfda79d
- [ X ] Please provide as much detail as possible.

https://www.schneider-electric.com/en/download/document/PM8xxxSchneiderMIB_customer/ - MIBS

- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11638

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/schneider-pm8000-support/11638/1
