### ISSUE TITLE
Widget weirdness in 1.47, and previous dashboards seem to have been deleted

### ISSUE THREAD

**Issue by fake-name** [librenms/librenms#9604]
From the issue template:

> Please do not post bugs 

Uh, what? This is explicitly a bug tracker.

-------

Apparently a new dashboard system has been released? Anyways, it appears it has deleted (or no longer obeys) my existing home-page config:

Steps to replicate:

1. Browse to local LibreNMS install
2. Expect home landing page to still be there.

I had previously configured the homepage graphs via editing `config.php`, e.g. `$config['frontpage']['minigraphs']['ids']    = <stuff>`

Apparently this isn't supported any more? Is there an actual migration path?

I've looked through the recent changelogs, and I can't see anything that indicates this was changing, let alone that the old config interface was just going to explode.

------

Additionally, the replacement widgets seem a bit rough about the edges:

![image](https://user-images.githubusercontent.com/1401239/50580862-d524d980-0e08-11e9-9b4a-9a79a94e5c62.png)

This is a "Top Devices" widget thing, set to display traffic. You can expand the widget width, but the graphs don't expand to fit.

<strike>Additionally, the widget is set to traffic, but the mouse-over pop-up graphs for each widget show CPU usage? If the widget is set to traffic, the mouse-over behaviour should also show traffic. It should behave the same for other settings (response time should show response time in mouseover, etc...).</strike>

Ok, this is still kind of true, but if you mouse over the *name*, you get the CPU stats, and if you mouse over the graph/bar-graph, you get selected value stats. That's pretty fiddly. I'd think it should always show the selected statistic, but I can see arguments each way.

------

If you're editing a widget in the new interface, and you resize it, any unsaved changes to the widget config get erased. E.g:

1. Configure widget. Don't hit "save" yet.
2. Resize widget
3. Whatever you configured then gets deleted.

------

Additionally, there's some weird layout oddness:

![image](https://user-images.githubusercontent.com/1401239/50581154-cdb2ff80-0e0b-11e9-87fd-5d73318fdba5.png)

This is two "Top Devices" widgets immediately adjacent to each other, one displaying CPU load and one displaying free disk space. For some reason, the line height for the CPU widget is slightly greater then the line height for the disk space widget. That means there's a visual disconnect between the two adjacent widgets, and the CPU widget is forced to have a scroll bar.

------

I don't have a screenshot, but I've also managed to completely brain the drag-and-drop interface, and somehow get multiple widgets to be overlayed on top of each other.

------

![image](https://user-images.githubusercontent.com/1401239/50581247-dbb55000-0e0c-11e9-8d8e-f23e2f29da9f.png)

The "Top Interfaces" widget has a **giant** title (that you can't turn off). The "Top Devices" widget has no title. 

Additionally, you can set the top-bar text for the top devices widget, but not the top interfaces widget.

------

![image](https://user-images.githubusercontent.com/1401239/50581445-a447a300-0e0e-11e9-8d60-66c374eb12c3.png)

The entries for the "Device" combobox are sorted by *some order*. I legitimately don't know why they're the order they're in, but it's not lexicographical, natural or alphabetical (is it device addition order?), but it seems to be repeatable.

It'd make sense to me if they were sorted something like [natural order](https://en.wikipedia.org/wiki/Natural_sort_order).

Related: https://github.com/librenms/librenms/issues/9605

------

In general (after fiddling with it for a while), the new widget system is pretty swish, but I wish there was a migration route so I didn't find out that the config interface was being replaced by going to my local LibreNMS install and finding the previous config I had was deleted.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by fake-name** [comment]
Where the heck do you submit bugs if not the bug tracker?

**Comment by laf** [comment]
> Where the heck do you submit bugs if not the github issue tracker that's entire purpose is explicitly submitting bugs?

The community forum.

> Also, discord is **fucking terrible**, it's not an alternative, and I have zero interest creating another account on another random site.

That's your choice.

> > For help please use our Discord server or the community site
> 
> I don't need help, I'm reporting an issue. If you don't use the github issue tracker to track issues, maybe turn it off?

No. We use it for tracking new device support.

**Comment by fake-name** [comment]
> The community forum.

Well, 

1: That's annoying. 
2. It's mentioned literally *nowhere* in the FAQ you link:

> Bugs. Found one? We want to know about it. Most bugs are fixed after being spotted and reported by someone, I'd love to say we are amazing developers and will fix all bugs before you spot them but that's just not true.

That's the entire section on bug reporting.

> That's your choice.

No, discord is objectively terrible for anything like a help forum. **It's completely opaque to search engines**. If I have an issue, and I search for it, even if it's been answered on discord, I'd never know.

**Comment by laf** [comment]
> Well,
> 
> 1: That's annoying.
> 2. It's mentioned literally _nowhere_ in the FAQ you link:

Feel free to edit the docs: https://github.com/librenms/librenms/blob/master/doc/Support/FAQ.md

> No, discord is objectively terrible for anything like a help forum. **It's completely opaque to search engines**. If I have an issue, and I search for it, even if it's been answered on discord, I'd never know.

You can search in discord so yes you would know.

**Comment by fake-name** [comment]
> You can search in discord so yes you would know.

How? I'm legitimately curious. I use google for normal searching. Does Bing index it, or something?

**Comment by fake-name** [comment]
> it is built in search, 

That doesn't help when you're using a normal search engine much now, does it?

Being able to find where to go to find an answer when you're already where you need to go to find the answer is useless. 

The point is discord is completely undiscoverable from the perspective of basically everywhere on the internet *but* discord. I don't think anyone on encountering an issue thinks "I'll search an obnoxious JS-bloated proprietary garbage chat service most known for hosting hordes of annoying "l33t g4m3r" kids and grossly abusing what the word "server" means".   

They use a normal search engine.

------

1. I don't think LibreNMS has ever supported $config['frontpage']['minigraphs']['ids'] I searched the git history.
2. It sounds like you were using some other frontpage before and switched to the widget based "tiles" frontpage. Nothing was deleted.

This was set up a *long* time ago. It was before the home page *was* configurable (because I remember having to fiddle with stuff to change it). Looking about, it appears to [date back to before the observium fork](https://observium.observium.narkive.com/eozXBE77/front-page). 

Given that, I'm not surprised no one remembers it. I'm surprised it kept working, frankly. I suspect that maybe there was a importer at some time in the ancient past, and it created a new dashboard or something, and then the recent rework displaced it or something. Digging through ancient git history, I have no idea what's going on either.

All I know is about 2 weeks ago, the old dashboard config was working fine. 3 days ago, it no longer was. The server this all runs on *might* have had `apt-get dist-upgrade -y` run on it in the interim, but I touched nothing else (I hadn't `ssh`'ed into it for *months* (I use landscape to apply updates)), so ¯\_(ツ)_/¯

Anyways, the dashboard changing is probably specific to my extremely oddball setup. 

Actually, that's another interesting, possibly useful idea: Warn about config stuff that doesn't do anything. I bet I have other legacy crap in my config, and I may not be the only person.

------

> 3. 90% of the issues you mention existed before 1.47 and are bugs in the js library LibreNMS uses. I posted patches for the others already.

To be honest, I wasn't aware you could edit dashboards before just now. 

So reporting bugs on the bug tracker *does* work.

**Comment by laf** [comment]
I'm locking this now as this conversation is not going anywhere.

The short is, we don't accept bug reports here regardless of how you feel a project should be run or use github issues. The fact is, we don't use them like that. Now you can be willing to help and edit the FAQ if you feel it's not clear enough or not, the choice is yours.
