### ISSUE TITLE
Refinement request: It'd be nice if devices were sorted in natural order, rather then lexicographical order

### ISSUE THREAD

**Issue by fake-name** [librenms/librenms#9605]
Consider the following device list:

![image](https://user-images.githubusercontent.com/1401239/50581566-a3fbd780-0e0f-11e9-8307-c5c40aef9fe6.png)

Right now, the "sort by device name" option sorts devices in lexicographical order, so it sorts in order like:

 - 10.1.1.1
 - 10.1.1.100
 - 10.1.1.15
 - 10.1.1.2

This is fairly standard, but it is annoying (and it technically sorts IPs wrong, too). [Natural Sorting](https://en.wikipedia.org/wiki/Natural_sort_order) would order them properly:

 - 10.1.1.1
 - 10.1.1.2
 - 10.1.1.15
 - 10.1.1.100

This would certainly be a nice-to-have for the web UI.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
