### ISSUE TITLE
location "unknown" showing on map

### ISSUE THREAD

**Issue by pcw11211** [librenms/librenms#9609]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org/c/help).**

To create a new device request please use this link: https://github.com/librenms/librenms/issues/new?template=New-Device.md

we have many devices throughout US and they show on our map. there are also few servers that dont have location address because we didn't want to show them on the map. unfortunately if location is not set, it's automatically set as "unknown" (BUG) and then put on map

![image](https://user-images.githubusercontent.com/16885161/50646714-c17e8d80-0f44-11e9-908b-2a1410e3fbde.png)

![image](https://user-images.githubusercontent.com/16885161/50646741-d65b2100-0f44-11e9-93d2-eb0db330ac5c.png)
https://www.google.com/maps/place/42%C2%B013'49.9%22N+83%C2%B044'47.9%22W/@42.2294789,-83.7471954,17.25z/data=!4m5!3m4!1s0x0:0x0!8m2!3d42.230537!4d-83.746643

apparently there is a pond called "unknown" where all our servers reside ... (sunk? or competing with https://natick.research.microsoft.com/ )

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by pcw11211** [comment]
hope u had some laughs ;)

**Comment by kkrumm1** [comment]
No really please help by posting here Please do not post bugs or ask questions

For help and support, you can use our Discord server or our community site.
