### ISSUE TITLE
NAC method lables are not correct

### ISSUE THREAD

**Issue by PENorris** [librenms/librenms#9610]
The methods under NAC tab all show as MAB no matter what the actual switch reports. 
 Here's an example of a port with a MAB device and a Dot1x device.

This occurs on all my Cisco switches regardless of platform, but this one happens to be a 2960x running 15.2 code. 
![mab](https://user-images.githubusercontent.com/16704208/50649250-5c7a6600-0f4b-11e9-9754-d37f06a43860.PNG)
![mab2](https://user-images.githubusercontent.com/16704208/50649261-613f1a00-0f4b-11e9-8b05-2c5ed0b55e29.PNG)

**Comment by kkrumm1** [comment]
This, not the place to talk about this. Please use or discord server or community site 

This issue has been closed as it isn't classed as a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
