### ISSUE TITLE
Emerson-Liebert PDU RPC-1000 

### ISSUE THREAD

**Issue by Luzr** [librenms/librenms#9614]
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/b4675ccd
https://p.libren.ms/view/f61c7607
https://p.libren.ms/view/4a497d85
- [x] Please provide as much detail as possible.
from the support page on the device

Manufacturer | Emerson Network Power
Agent Model | Rack PDU Card
Agent App Firmware Version | 4.D40.1
Agent App Firmware Label | RPC_HID16_4.D40.1_099117
Agent Boot Firmware Version | 4.540.3
Agent Boot Firmware Label | RPC_HID16_4.540.3_054655
Agent Hardware ID | 16
Agent Serial Number | 123456789
Agent Manufacture Date | FEB 08 2010
Agent Ethernet MAC Address (Primary) | 00
Agent Ethernet MAC Address (Secondary) | 00
FDM Version | 1306
GDD Version | 33857
Device ID Sequence | 8.2
Manufacturer support | Liebert.com
SNMP MIB Downloads | [Liebert Software Downloads] (https://www.vertivco.com/en-us/products/brands/liebert/)

- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
how do i get the debug info?

- [x] other info
[SNMP Parameters]
sysDescr,1.3.6.1.2.1.1.1.0
sysObjectID,1.3.6.1.2.1.1.2.0
sysUpTime,1.3.6.1.2.1.1.3.0
sysContact,1.3.6.1.2.1.1.4.0
sysName,1.3.6.1.2.1.1.5.0
sysLocation,1.3.6.1.2.1.1.6.0
lgpAgentIdentManufacturer,1.3.6.1.4.1.476.1.42.2.1.1.0
lgpAgentIdentModel,1.3.6.1.4.1.476.1.42.2.1.2.0
lgpAgentIdentFirmwareVersion,1.3.6.1.4.1.476.1.42.2.1.3.0
lgpAgentIdentSerialNumber,1.3.6.1.4.1.476.1.42.2.1.4.0
lgpAgentDeviceIndex,1.3.6.1.4.1.476.1.42.2.4.2.1.1.1
lgpAgentDeviceId,1.3.6.1.4.1.476.1.42.2.4.2.1.2.1
lgpAgentDeviceManufacturer,1.3.6.1.4.1.476.1.42.2.4.2.1.3.1
lgpAgentDeviceModel,1.3.6.1.4.1.476.1.42.2.4.2.1.4.1
lgpAgentDeviceUnitNumber,1.3.6.1.4.1.476.1.42.2.4.2.1.6.1
lgpAgentDeviceManufactureDate,1.3.6.1.4.1.476.1.42.2.4.2.1.8.1
lgpAgentReboot,1.3.6.1.4.1.476.1.42.2.5.1.0
lgpAgentTelnetEnabled,1.3.6.1.4.1.476.1.42.2.5.2.0
lgpAgentVelocityServerEnabled,1.3.6.1.4.1.476.1.42.2.5.3.0
lgpAgentWebServerMode,1.3.6.1.4.1.476.1.42.2.5.4.0
lgpConditionsPresent,1.3.6.1.4.1.476.1.42.3.2.2.0
lgpPduEntryUsrLabel,1.3.6.1.4.1.476.1.42.3.8.20.1.10.PDU
lgpPduEntrySysAssignLabel,1.3.6.1.4.1.476.1.42.3.8.20.1.15.PDU
lgpPduEntryPositionRelative,1.3.6.1.4.1.476.1.42.3.8.20.1.20.PDU
lgpPduEntrySysStatus,1.3.6.1.4.1.476.1.42.3.8.20.1.25.PDU
lgpPduEntryUsrTag1,1.3.6.1.4.1.476.1.42.3.8.20.1.35.PDU
lgpPduEntryUsrTag2,1.3.6.1.4.1.476.1.42.3.8.20.1.40.PDU
lgpPduEntrySerialNumber,1.3.6.1.4.1.476.1.42.3.8.20.1.45.PDU
lgpPduEntryId,1.3.6.1.4.1.476.1.42.3.8.20.1.5.PDU
lgpPduPsEntryId,1.3.6.1.4.1.476.1.42.3.8.30.20.1.10.PDU.PS
lgpPduPsEntrySysAssignLabel,1.3.6.1.4.1.476.1.42.3.8.30.20.1.15.PDU.PS
lgpPduPsEntryModel,1.3.6.1.4.1.476.1.42.3.8.30.20.1.20.PDU.PS
lgpPduPsEntryWiringType,1.3.6.1.4.1.476.1.42.3.8.30.20.1.25.PDU.PS
lgpPduPsEntryEpInputRated,1.3.6.1.4.1.476.1.42.3.8.30.20.1.30.PDU.PS
lgpPduPsEntryEcInputRated,1.3.6.1.4.1.476.1.42.3.8.30.20.1.35.PDU.PS
lgpPduPsEntryFreqRated,1.3.6.1.4.1.476.1.42.3.8.30.20.1.40.PDU.PS
lgpPduPsEntryEnergyAccum,1.3.6.1.4.1.476.1.42.3.8.30.20.1.50.PDU.PS
lgpPduPsEntrySerialNum,1.3.6.1.4.1.476.1.42.3.8.30.20.1.55.PDU.PS
lgpPduPsEntryFirmwareVersion,1.3.6.1.4.1.476.1.42.3.8.30.20.1.60.PDU.PS
lgpPduPsEntryPwrTotal,1.3.6.1.4.1.476.1.42.3.8.30.20.1.65.PDU.PS
lgpPduPsEntryEcNeutral,1.3.6.1.4.1.476.1.42.3.8.30.20.1.70.PDU.PS
lgpPduPsEntryEcNeutralThrshldOvrWarn,1.3.6.1.4.1.476.1.42.3.8.30.20.1.75.PDU.PS
lgpPduPsEntryEcNeutralThrshldOvrAlarm,1.3.6.1.4.1.476.1.42.3.8.30.20.1.80.PDU.PS
lgpPduPsLineEntryId,1.3.6.1.4.1.476.1.42.3.8.30.40.1.10.PDU.PS.LINE
lgpPduPsLineEntryLine,1.3.6.1.4.1.476.1.42.3.8.30.40.1.15.PDU.PS.LINE
lgpPduPsLineEntryEpLNTenths,1.3.6.1.4.1.476.1.42.3.8.30.40.1.19.PDU.PS.LINE
lgpPduPsLineEntryEpLN,1.3.6.1.4.1.476.1.42.3.8.30.40.1.20.PDU.PS.LINE
lgpPduPsLineEntryEc,1.3.6.1.4.1.476.1.42.3.8.30.40.1.21.PDU.PS.LINE
lgpPduPsLineEntryEcHundredths,1.3.6.1.4.1.476.1.42.3.8.30.40.1.22.PDU.PS.LINE
lgpPduPsLineEntryEcThrshldUndrAlarm,1.3.6.1.4.1.476.1.42.3.8.30.40.1.35.PDU.PS.LINE
lgpPduPsLineEntryEcThrshldOvrWarn,1.3.6.1.4.1.476.1.42.3.8.30.40.1.36.PDU.PS.LINE
lgpPduPsLineEntryEcThrshldOvrAlarm,1.3.6.1.4.1.476.1.42.3.8.30.40.1.37.PDU.PS.LINE
lgpPduPsLineEntryEcAvailBeforeAlarm,1.3.6.1.4.1.476.1.42.3.8.30.40.1.38.PDU.PS.LINE
lgpPduPsLineEntryEcUsedBeforeAlarm,1.3.6.1.4.1.476.1.42.3.8.30.40.1.39.PDU.PS.LINE
lgpPduPsLineEntryEpLL,1.3.6.1.4.1.476.1.42.3.8.30.40.1.60.PDU.PS.LINE
lgpPduPsLineEntryEpLLTenths,1.3.6.1.4.1.476.1.42.3.8.30.40.1.61.PDU.PS.LINE
lgpPduPsLineEntryEcAvailBeforeAlarmHundredths,1.3.6.1.4.1.476.1.42.3.8.30.40.1.62.PDU.PS.LINE
lgpPduRbEntryEpLNTenths,1.3.6.1.4.1.476.1.42.3.8.40.20.1.100.PDU.RB
lgpPduRbEntryPwr,1.3.6.1.4.1.476.1.42.3.8.40.20.1.115.PDU.RB
lgpPduRbEntryAp,1.3.6.1.4.1.476.1.42.3.8.40.20.1.120.PDU.RB
lgpPduRbEntryPf,1.3.6.1.4.1.476.1.42.3.8.40.20.1.125.PDU.RB
lgpPduRbEntryEcHundredths,1.3.6.1.4.1.476.1.42.3.8.40.20.1.130.PDU.RB
lgpPduRbEntryEcThrshldUndrAlm,1.3.6.1.4.1.476.1.42.3.8.40.20.1.135.PDU.RB
lgpPduRbEntryEcThrshldOvrWarn,1.3.6.1.4.1.476.1.42.3.8.40.20.1.140.PDU.RB
lgpPduRbEntryEcThrshldOvrAlm,1.3.6.1.4.1.476.1.42.3.8.40.20.1.145.PDU.RB
lgpPduRbEntryEcAvailBeforeAlarmHundredths,1.3.6.1.4.1.476.1.42.3.8.40.20.1.150.PDU.RB
lgpPduRbEntryEcUsedBeforeAlarm,1.3.6.1.4.1.476.1.42.3.8.40.20.1.160.PDU.RB
lgpPduRbEntryEpLLTenths,1.3.6.1.4.1.476.1.42.3.8.40.20.1.170.PDU.RB
lgpPduRbEntrySysAssignLabel,1.3.6.1.4.1.476.1.42.3.8.40.20.1.20.PDU.RB
lgpPduRbEntryPositionRelative,1.3.6.1.4.1.476.1.42.3.8.40.20.1.25.PDU.RB
lgpPduRbEntrySerialNum,1.3.6.1.4.1.476.1.42.3.8.40.20.1.30.PDU.RB
lgpPduRbEntryModel,1.3.6.1.4.1.476.1.42.3.8.40.20.1.35.PDU.RB
lgpPduRbEntryFirmwareVersion,1.3.6.1.4.1.476.1.42.3.8.40.20.1.40.PDU.RB
lgpPduRbEntryUsrTag1,1.3.6.1.4.1.476.1.42.3.8.40.20.1.41.PDU.RB
lgpPduRbEntryUsrTag2,1.3.6.1.4.1.476.1.42.3.8.40.20.1.42.PDU.RB
lgpPduRbEntryReceptacleType,1.3.6.1.4.1.476.1.42.3.8.40.20.1.45.PDU.RB
lgpPduRbEntryId,1.3.6.1.4.1.476.1.42.3.8.40.20.1.5.PDU.RB
lgpPduRbEntryCapabilities,1.3.6.1.4.1.476.1.42.3.8.40.20.1.50.PDU.RB
lgpPduRbEntryLineSource,1.3.6.1.4.1.476.1.42.3.8.40.20.1.55.PDU.RB
lgpPduRbEntryRcpCount,1.3.6.1.4.1.476.1.42.3.8.40.20.1.60.PDU.RB
lgpPduRbEntryEpRated,1.3.6.1.4.1.476.1.42.3.8.40.20.1.70.PDU.RB
lgpPduRbEntryEcRated,1.3.6.1.4.1.476.1.42.3.8.40.20.1.75.PDU.RB
lgpPduRbEntryUsrLabel,1.3.6.1.4.1.476.1.42.3.8.40.20.1.8.PDU.RB
lgpPduRbEntryFreqRated,1.3.6.1.4.1.476.1.42.3.8.40.20.1.80.PDU.RB
lgpPduRbEntryEnergyAccum,1.3.6.1.4.1.476.1.42.3.8.40.20.1.85.PDU.RB
lgpPduRcpEntryUsrLabel,1.3.6.1.4.1.476.1.42.3.8.50.20.1.10.PDU.RB.RCP
lgpPduRcpEntryControl,1.3.6.1.4.1.476.1.42.3.8.50.20.1.100.PDU.RB.RCP
lgpPduRcpEntryControlLock,1.3.6.1.4.1.476.1.42.3.8.50.20.1.105.PDU.RB.RCP
lgpPduRcpEntryUsrTag1,1.3.6.1.4.1.476.1.42.3.8.50.20.1.15.PDU.RB.RCP
lgpPduRcpEntryEcThrshldUnderAlarm,1.3.6.1.4.1.476.1.42.3.8.50.20.1.150.PDU.RB.RCP
lgpPduRcpEntryEcThrshldOverWarn,1.3.6.1.4.1.476.1.42.3.8.50.20.1.151.PDU.RB.RCP
lgpPduRcpEntryEcThrshldOverAlarm,1.3.6.1.4.1.476.1.42.3.8.50.20.1.152.PDU.RB.RCP
lgpPduRcpEntryEcAvailBeforeAlarmHundredths,1.3.6.1.4.1.476.1.42.3.8.50.20.1.159.PDU.RB.RCP
lgpPduRcpEntryEcAvailBeforeAlarm,1.3.6.1.4.1.476.1.42.3.8.50.20.1.160.PDU.RB.RCP
lgpPduRcpEntryEcUsedBeforeAlarm,1.3.6.1.4.1.476.1.42.3.8.50.20.1.161.PDU.RB.RCP
lgpPduRcpEntryEcCrestFactor,1.3.6.1.4.1.476.1.42.3.8.50.20.1.162.PDU.RB.RCP
lgpPduRcpEntryUsrTag2,1.3.6.1.4.1.476.1.42.3.8.50.20.1.20.PDU.RB.RCP
lgpPduRcpEntryBlinkLED,1.3.6.1.4.1.476.1.42.3.8.50.20.1.200.PDU.RB.RCP
lgpPduRcpEntrySysAssignLabel,1.3.6.1.4.1.476.1.42.3.8.50.20.1.25.PDU.RB.RCP
lgpPduRcpEntryPosition,1.3.6.1.4.1.476.1.42.3.8.50.20.1.30.PDU.RB.RCP
lgpPduRcpEntryType,1.3.6.1.4.1.476.1.42.3.8.50.20.1.40.PDU.RB.RCP
lgpPduRcpEntryLineSource,1.3.6.1.4.1.476.1.42.3.8.50.20.1.45.PDU.RB.RCP
lgpPduRcpEntryId,1.3.6.1.4.1.476.1.42.3.8.50.20.1.5.PDU.RB.RCP
lgpPduRcpEntryCapabilities,1.3.6.1.4.1.476.1.42.3.8.50.20.1.50.PDU.RB.RCP
lgpPduRcpEntryEp,1.3.6.1.4.1.476.1.42.3.8.50.20.1.55.PDU.RB.RCP
lgpPduRcpEntryEpTenths,1.3.6.1.4.1.476.1.42.3.8.50.20.1.56.PDU.RB.RCP
lgpPduRcpEntryEc,1.3.6.1.4.1.476.1.42.3.8.50.20.1.60.PDU.RB.RCP
lgpPduRcpEntryEcHundredths,1.3.6.1.4.1.476.1.42.3.8.50.20.1.61.PDU.RB.RCP
lgpPduRcpEntryPwrOut,1.3.6.1.4.1.476.1.42.3.8.50.20.1.65.PDU.RB.RCP
lgpPduRcpEntryApOut,1.3.6.1.4.1.476.1.42.3.8.50.20.1.70.PDU.RB.RCP
lgpPduRcpEntryPf,1.3.6.1.4.1.476.1.42.3.8.50.20.1.75.PDU.RB.RCP
lgpPduRcpEntryFreq,1.3.6.1.4.1.476.1.42.3.8.50.20.1.80.PDU.RB.RCP
lgpPduRcpEntryEnergyAccum,1.3.6.1.4.1.476.1.42.3.8.50.20.1.85.PDU.RB.RCP
lgpPduRcpEntryPwrOnDelay,1.3.6.1.4.1.476.1.42.3.8.50.20.1.90.PDU.RB.RCP
lgpPduRcpEntryPwrState,1.3.6.1.4.1.476.1.42.3.8.50.20.1.95.PDU.RB.RCP
lgpPduAuxMeasType,1.3.6.1.4.1.476.1.42.3.8.60.15.1.10.PDU.SENSOR.MEAS
lgpPduAuxMeasHumThrshldUndrAlm,1.3.6.1.4.1.476.1.42.3.8.60.15.1.100.PDU.SENSOR.MEAS
lgpPduAuxMeasHumThrshldOvrAlm,1.3.6.1.4.1.476.1.42.3.8.60.15.1.105.PDU.SENSOR.MEAS
lgpPduAuxMeasHumThrshldUndrWarn,1.3.6.1.4.1.476.1.42.3.8.60.15.1.110.PDU.SENSOR.MEAS
lgpPduAuxMeasHumThrshldOvrWarn,1.3.6.1.4.1.476.1.42.3.8.60.15.1.115.PDU.SENSOR.MEAS
lgpPduAuxMeasDrClosureState,1.3.6.1.4.1.476.1.42.3.8.60.15.1.120.PDU.SENSOR.MEAS
lgpPduAuxMeasDrClosureConfig,1.3.6.1.4.1.476.1.42.3.8.60.15.1.125.PDU.SENSOR.MEAS
lgpPduAuxMeasCntctClosureState,1.3.6.1.4.1.476.1.42.3.8.60.15.1.130.PDU.SENSOR.MEAS
lgpPduAuxMeasCntctClosureConfig,1.3.6.1.4.1.476.1.42.3.8.60.15.1.135.PDU.SENSOR.MEAS
lgpPduAuxMeasSensorSysAssignLabel,1.3.6.1.4.1.476.1.42.3.8.60.15.1.15.PDU.SENSOR.MEAS
lgpPduAuxMeasUsrLabel,1.3.6.1.4.1.476.1.42.3.8.60.15.1.20.PDU.SENSOR.MEAS
lgpPduAuxMeasUsrTag1,1.3.6.1.4.1.476.1.42.3.8.60.15.1.25.PDU.SENSOR.MEAS
lgpPduAuxMeasUsrTag2,1.3.6.1.4.1.476.1.42.3.8.60.15.1.30.PDU.SENSOR.MEAS
lgpPduAuxMeasSensorSerialNum,1.3.6.1.4.1.476.1.42.3.8.60.15.1.35.PDU.SENSOR.MEAS
lgpPduAuxMeasTempDegF,1.3.6.1.4.1.476.1.42.3.8.60.15.1.40.PDU.SENSOR.MEAS
lgpPduAuxMeasTempThrshldUndrAlmDegF,1.3.6.1.4.1.476.1.42.3.8.60.15.1.50.PDU.SENSOR.MEAS
lgpPduAuxMeasTempThrshldOvrAlmDegF,1.3.6.1.4.1.476.1.42.3.8.60.15.1.55.PDU.SENSOR.MEAS
lgpPduAuxMeasTempThrshldUndrWarnDegF,1.3.6.1.4.1.476.1.42.3.8.60.15.1.60.PDU.SENSOR.MEAS
lgpPduAuxMeasTempThrshldOvrWarnDegF,1.3.6.1.4.1.476.1.42.3.8.60.15.1.65.PDU.SENSOR.MEAS
lgpPduAuxMeasTempDegC,1.3.6.1.4.1.476.1.42.3.8.60.15.1.70.PDU.SENSOR.MEAS
lgpPduAuxMeasTempThrshldUndrAlmDegC,1.3.6.1.4.1.476.1.42.3.8.60.15.1.75.PDU.SENSOR.MEAS
lgpPduAuxMeasTempThrshldOvrAlmDegC,1.3.6.1.4.1.476.1.42.3.8.60.15.1.80.PDU.SENSOR.MEAS
lgpPduAuxMeasTempThrshldUndrWarnDegC,1.3.6.1.4.1.476.1.42.3.8.60.15.1.85.PDU.SENSOR.MEAS
lgpPduAuxMeasTempThrshldOvrWarnDegC,1.3.6.1.4.1.476.1.42.3.8.60.15.1.90.PDU.SENSOR.MEAS
lgpPduAuxMeasHum,1.3.6.1.4.1.476.1.42.3.8.60.15.1.95.PDU.SENSOR.MEAS

[SNMP Events]
coldStart,1.3.6.1.6.3.1.1.5.1
lgpAgentDeviceCommunicationLost,1.3.6.1.4.1.476.1.42.2.3.0.1
lgpAgentFirmwareUpdateSuccessful,1.3.6.1.4.1.476.1.42.2.3.0.5
lgpAgentFirmwareCorrupt,1.3.6.1.4.1.476.1.42.2.3.0.6
lgpAgentHeartbeat,1.3.6.1.4.1.476.1.42.2.3.0.7
lgpAgentDnsLookupFailure,1.3.6.1.4.1.476.1.42.2.3.0.8
lgpConditionHighTemperature,1.3.6.1.4.1.476.1.42.3.2.1.1
lgpConditionUnderCurrent,1.3.6.1.4.1.476.1.42.3.2.1.182
lgpConditionFirmwareUpdateRequired,1.3.6.1.4.1.476.1.42.3.2.1.187.3
lgpConditionTest01,1.3.6.1.4.1.476.1.42.3.2.1.188.5
lgpConditionRcpBranchBreakerOpen,1.3.6.1.4.1.476.1.42.3.2.1.190.10
lgpConditionRcpBranchFailure,1.3.6.1.4.1.476.1.42.3.2.1.190.5
lgpConditionLowTemperature,1.3.6.1.4.1.476.1.42.3.2.1.2
lgpConditionHighHumidity,1.3.6.1.4.1.476.1.42.3.2.1.3
lgpConditionPowerSupplyFailure,1.3.6.1.4.1.476.1.42.3.2.1.37
lgpConditionUnderVoltage,1.3.6.1.4.1.476.1.42.3.2.1.39
lgpConditionLowHumidity,1.3.6.1.4.1.476.1.42.3.2.1.4
lgpConditionOverCurrent,1.3.6.1.4.1.476.1.42.3.2.1.53
lgpConditionSource1NeutralOverCurrent,1.3.6.1.4.1.476.1.42.3.2.1.53.11
lgpConditionTooManySensors,1.3.6.1.4.1.476.1.42.3.2.1.5423
lgpConditionDoorSwitchOpen,1.3.6.1.4.1.476.1.42.3.2.1.5471
lgpConditionContactClosureOpen,1.3.6.1.4.1.476.1.42.3.2.1.5479
lgpConditionContactClosureClosed,1.3.6.1.4.1.476.1.42.3.2.1.5480
lgpConditionInternalCommunicationFailure,1.3.6.1.4.1.476.1.42.3.2.1.55
lgpConditionSensorsNotDisplayed,1.3.6.1.4.1.476.1.42.3.2.1.6119
lgpEventConditionEntryAdded,1.3.6.1.4.1.476.1.42.3.3.0.1
lgpEventConfigModified,1.3.6.1.4.1.476.1.42.3.3.0.18
lgpEventModuleAdded,1.3.6.1.4.1.476.1.42.3.3.0.19
lgpEventConditionEntryRemoved,1.3.6.1.4.1.476.1.42.3.3.0.2
lgpEventModuleRemoved,1.3.6.1.4.1.476.1.42.3.3.0.20
lgpEventRcpPowerStateChangeOn,1.3.6.1.4.1.476.1.42.3.3.0.21
lgpEventRcpPowerStateChangeOff,1.3.6.1.4.1.476.1.42.3.3.0.22
lgpEventRcpLoadAdded,1.3.6.1.4.1.476.1.42.3.3.0.23
lgpEventRcpLoadRemoved,1.3.6.1.4.1.476.1.42.3.3.0.24
lgpSysNotification,1.3.6.1.4.1.476.1.42.3.7.8.1
lgpSysNormal,1.3.6.1.4.1.476.1.42.3.7.8.2

**Comment by spencerbutler** [comment]
@Luzr please take a look at the [FAQ](https://docs.librenms.org/Support/FAQ/#faq20) for information on getting the debug information to submit. I don't see the requested snmpwalk in your files (the output you put in the issue will not work for our testing). After you have resubmitted your files I will take a look and see if I can get this properly integrated.

**Comment by PipoCanaja** [comment]
@Luzr Issue will be re-opened when the data will be provided. Thanx
