### ISSUE TITLE
Add support for Draytek VigorAP 902

### ISSUE THREAD

**Issue by Sweeny42** [librenms/librenms#9615]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Hoping to categorise correctly the Draytek VigorAP 902. This is currently displaying as a standard Linux device in LibreNMS.** 

Would it be possible to update this particular device with the correct Hardware value (VigorAP 902) and the Draytek logo?

Details of output ./discovery.php: https://p.libren.ms/view/a06014a9
Details of output ./poller.php: https://p.libren.ms/view/19d16f9e
Details of output snmpbulkwalk: https://p.libren.ms/view/cae96791
Details from Draytek reagrding what OID's are supported: https://www.draytek.com/en/faq/faq-management/management.system-maintenance/which-snmp-oids-does-vigor-router-support/ 

If any more information is required I can supply what I can. Many thanks indeed.

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11636

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/add-support-for-draytek-vigorap-902/11636/1
