### ISSUE TITLE
New device: Papouch - Quido ETH 4/4

### ISSUE THREAD

**Issue by bukowski12** [librenms/librenms#9629]
- [x]  Please provide ALL info asked for here.
- [x]  Please provide as much detail as possible.
- [x]  Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Please add support for Papouch - Quido ETH 4/4 4 input , 4 output and thermomether

https://p.libren.ms/view/3b1524f0
https://p.libren.ms/view/7c63b120
https://p.libren.ms/view/1a60e11f

https://www.papouch.com/cz/shop/product/quido-eth-4-4-vstupy-vystupy-teplomer-ethernet/

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-papouch-quido-eth-4-4/11635/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11635
