### ISSUE TITLE
Add NetApp disk support

### ISSUE THREAD

**Issue by laf** [librenms/librenms#963]

**Comment by laf** [comment]
re-opening, more to add.

**Comment by killsudo** [comment]
http://www.oidview.com/mibs/789/NETWORK-APPLIANCE-MIB.html

It's also possible to pull in netapp 'aggregate' detection and percent full. The Aggregate contains the netapp 'volumes' for a group of raid-groups across one or more shelfs.

If you leverage the 'cf' oids you can detect when two netapps are actually clustered and the status of the HA cluster.

It's also possible to build graphs showing nfs/cifs/iscsi/fc i/o stats and connections/etc.

**Comment by killsudo** [comment]
https://github.com/zenoss/ZenPacks.community.NetApp/blob/master/ZenPacks/community/NetApp/libexec/check_netapp

**Comment by killsudo** [comment]
https://github.com/zenoss/ZenPacks.community.NetApp/blob/master/ZenPacks/community/NetApp/modeler/plugins/NetAppFileSystemMap.py
