### ISSUE TITLE
Distributed poller Billing support

### ISSUE THREAD

**Issue by Swashy** [librenms/librenms#9642]
After digging through the code for billing, it appears that billing is more or less incompatible with distributed pollers.

- Billing code has no concept of poller groups
- Consequently a poller will attempt to poll every device regardless of whether it can reach it or not
- When generating billing, it SNMP polls anew for transfer rates rather than pulling from existing information (RRD?)

I'm willing to provide assistance with this feature if someone more in the know can provide some direction on the structure of the poller code. I'm thinking that maybe billing could be rolled into the new librenms-service.py as it polls individual devices. You can obviously see billing attempts to happen globally rather than per device in log output:

```
journalctl -ru librenms.service
...
Jan 10 15:29:27 librenms-distributed librenms-service.py[27853]: Billing(INFO):Polling billing complete
Jan 10 15:29:26 librenms-distributed librenms-service.py[27853]: Poller_10-4(INFO):Polling device 100
Jan 10 15:29:15 librenms-distributed librenms-service.py[27853]: Poller_10-9(INFO):Polling complete 130
Jan 10 15:29:09 librenms-distributed librenms-service.py[27853]: Poller_10-15(INFO):Polling complete 112
Jan 10 15:29:08 librenms-distributed librenms-service.py[27853]: Poller_10-6(INFO):Polling complete 129
Jan 10 15:29:00 librenms-distributed librenms-service.py[27853]: Alerting(INFO):Checking alerts
Jan 10 15:28:50 librenms-distributed librenms-service.py[27853]: Poller_10-15(INFO):Polling device 112
Jan 10 15:28:47 librenms-distributed librenms-service.py[27853]: Poller_10-11(INFO):Polling complete 105
Jan 10 15:28:45 librenms-distributed librenms-service.py[27853]: Poller_10-2(INFO):Polling complete 117
Jan 10 15:28:41 librenms-distributed librenms-service.py[27853]: Poller_10-9(INFO):Polling device 130
```

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

Thanks for wanting to help improve things but can you join the #devel channel on discord to discuss this please.

**Comment by Swashy** [comment]
Gotcha, thanks.
