### ISSUE TITLE
New Device: Coriant Groove G30

### ISSUE THREAD

**Issue by Swashy** [librenms/librenms#9655]
Requesting device support for the Coriant Groove G30

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery: https://p.libren.ms/view/1f56aff4

Poller: https://p.libren.ms/view/e6f49384

SNMPBulkwalk: https://p.libren.ms/view/49deb7ed

Additional Documentation: 
MIBS from observium: https://mibs.observium.org/mib/CORIANT-GROOVE-MIB/
Sales blurb about the device (not sure if this is helpful): https://walkerfirst.com/uploads/files/literature/Coriant%20Groove%20G30.pdf

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by rasssta** [comment]
Let me know if you need help with beta testing of Groove. I will happily help out.

**Comment by nickhilliard** [comment]
support added in https://github.com/librenms/librenms/pull/9843 (commit 00006af66a496d1bece7c14fd9d267d14e704396).

**Comment by PipoCanaja** [comment]
Thanx @nickhilliard. Closing the issue now.
