### ISSUE TITLE
New Device:  Ruckus Unleashed 

### ISSUE THREAD

**Issue by Svenman2** [librenms/librenms#9658]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery: https://p.libren.ms/view/2b0dcee6
Poller: https://p.libren.ms/view/6717461d
SNMPBulkwalk: https://p.libren.ms/view/94c5dae4

Additional Documentation:
Ruckus Unleashed MIBS: [unleashed_mibs_20170704.zip](https://github.com/librenms/librenms/files/2752727/unleashed_mibs_20170704.zip)
ruckus Website: https://support.ruckuswireless.com/software/1672-ruckus-unleashed-ap-200-6-10-1-308-ga-snmp-mibs-zip

Librenms can not see how much client and AP are connected.
![image](https://user-images.githubusercontent.com/29526175/51080681-8fa5bd80-16e0-11e9-8459-bbb66c8a300b.png)

shows a lot of ports but not at which AP or WiFi channel.
![image](https://user-images.githubusercontent.com/29526175/51080678-8288ce80-16e0-11e9-809f-418389cbbc3b.png)

In the Tab Wireless the Ruckus Unleashed does not occur so I miss phy-ruckus here
![image](https://user-images.githubusercontent.com/29526175/51084979-18e5e000-1733-11e9-9029-2daa643471be.png)

validate.php
![image](https://user-images.githubusercontent.com/29526175/51080687-b8c64e00-16e0-11e9-8f5b-e1dc44c547fa.png)

**Comment by utelisysadmin** [comment]
As mentioned in the other thread. I've mostly fixed this in:
https://github.com/librenms/librenms/pull/9684

**Comment by djamp42** [comment]
I have also submitted a pull request, based on @utelisysadmin work, with some tweaks and fixes for some devices not discovering correctly. #9727

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-ruckus-unleashed/11634/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11634
