### ISSUE TITLE
Unable to add ipv6only device

### ISSUE THREAD

**Issue by mikaelfrykholm** [librenms/librenms#9682]
When adding a device via hostname which only has an AAAA record it fails the initial ping check (It seems to try reacablility via fping instead of fping6).

**Comment by mikaelfrykholm** [comment]
Fixed it. The problem was actually the shipping snmpd config file. It silently refuses to respond to snmp requests without a com2sec6 line: 
```
com2sec readonly  default         RANDOMSTRINGGOESHERE
com2sec6 readonly  default         RANDOMSTRINGGOESHERE
```

**Comment by kkrumm1** [comment]
This, not the place to talk about this. Please use our discord server or community site 

This issue has been closed as it isn't classed as a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
