### ISSUE TITLE
Review variables for graphs

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#969]
Some of the variables used for graphing are either redundant or contract eachother.
We need to review them all and possibly rewrite some logic.
Ideally we should not use inverse-logic anywhere (instead of `nototal=1` use `total=0` etc)

**Comment by paulgear** [comment]
Big +1 on getting rid of the inverse-logic variable names.  They are a scourge.

**Comment by laf** [comment]
18 months on, closing as it can't be that important.
