### ISSUE TITLE
f5 - update monitoring or BigIP v13.x

### ISSUE THREAD

**Issue by olivierbeytrison** [librenms/librenms#9710]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Since BigIP vers 13.x the snmp layout has changed. 

Currently the load balancer component doesn't work anymore for f5.

Here's the mib files.
[mibs_f5.tar.gz](https://github.com/librenms/librenms/files/2778043/mibs_f5.tar.gz)

Discovery + Poller : https://gist.github.com/olivierbeytrison/31ae5cede78c171386c016c06bf1671c
snmpwalk (too big for gist) : 
[f5-snmpwalk.txt.gz](https://github.com/librenms/librenms/files/2778080/f5-snmpwalk.txt.gz)

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/f5-update-monitoring-or-bigip-v13-x/11632/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11632
