### ISSUE TITLE
New OS Request - fiberstore(fs.com)

### ISSUE THREAD

**Issue by Cormoran96** [librenms/librenms#9712]
**./discovery.php -h HOSTNAME -d | ./pbin.sh**
https://p.libren.ms/view/1d971906

**./poller.php -h HOSTNAME -r -f -d | ./pbin.sh**
https://p.libren.ms/view/d1231b65

**snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh**
https://p.libren.ms/view/67872cd3

vendor site:
https://www.fs.com

**Comment by PipoCanaja** [comment]
Hi @Cormoran96 
Do you have the MIB files for these devices ?
PipoCanaja

**Comment by Cormoran96** [comment]
No I don't find it.

**Comment by PipoCanaja** [comment]
This Issue was a duplicate of #9117 so let's close it and continue the discussion in the other issue and in the PR #9734
