### ISSUE TITLE
Add support for Linksys LGS318P with POE

### ISSUE THREAD

**Issue by billiaz** [librenms/librenms#9718]
I would like to request support for Linksys LGS318P. Expecially POE seems not to work

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
discovery: https://p.libren.ms/view/afb81fca
poller: https://p.libren.ms/view/96f408ad
snmpwalk: https://p.libren.ms/view/381bf4a8
- [x] Please provide as much detail as possible.
The switch is working but information like POE are not recorded. It can be joined as a Linksys Smart Switch. I found 308P is already been added for the PO3 part. But not the 308P.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by PipoCanaja** [comment]
Hi @billiaz 
The snmpwalk you provide is cut exactly at the beginning of the POE OIDs . That may mean that the device is buggy in his SNMP replies. Could you try to upgrade it to the latest firmware and let us know how it goes ? 
Bye

**Comment by aretakisv** [comment]
Something might went wrong with the first one.
SNMP Walk: https://p.libren.ms/view/59c814c4

**Comment by PipoCanaja** [comment]
Same thing in that one unfortunately. Stops right in the early POE OIDs ...

**Comment by aretakisv** [comment]
I will try to see what is cut off the snmpwalk.
I found also this: http://downloads.linksys.com/downloads/others/MIBs_LGS300%20V1.1.zip 
the official mibs, can these help?

**Comment by PipoCanaja** [comment]
MIB is good to have indeed, but first we need a device that replies to the requests. From what I have in the snmpwalk, the device stops responding during the POE oids. So either there is a bug in your switch firmware version (try upgrading) or there is an issue with the snmpwalk on the machine you use (this seems very unlikely).

**Comment by aretakisv** [comment]
There have been some timeouts during the snmpwalk and that is the reason. Used the -t5 and now i have a 21Mbyte snmpwalk.

Here is my snmpbulkwalk uploaded: https://billias.cc/A7PtR

**Comment by PipoCanaja** [comment]
(or attach the zipped file directly to the github post)

**Comment by aretakisv** [comment]
your paste stolution doesn't accept 21mbytes so here is your gz

[snmpbulkwalk.txt.gz](https://github.com/librenms/librenms/files/3011678/snmpbulkwalk.txt.gz)

**Comment by PipoCanaja** [comment]
@billiaz @aretakisv 
You can test the PR 10075: 
- apply the patch as described in the descr
- delete the cache ``` rm cache/os_defs.cache  ```
- force discovery: ``` ./discovery.php -h <yourLinksysDevice>```
- force polling: ``` ./poller.php -h <yourLinksysDevice>```

**Comment by laf** [comment]
Boom, thanks @PipoCanaja :)
