### ISSUE TITLE
Update Cisco MIB to support new devices (Catalyst 9300)

### ISSUE THREAD

**Issue by jarvismeier** [librenms/librenms#9725]
Cisco has updated their MIBs to support Cisco Catalyst 9300 series switches (identified as ciscoProducts.2494)

The MIB says it hasn't been updated since 2016 but if you perform a search the catalyst 9300 switches show up.  Cisco must suck at updating changelogs.

ftp://ftp.cisco.com/pub/mibs/v2/CISCO-PRODUCTS-MIB.my

discovery:  https://p.libren.ms/view/3200d3ea
poller:  https://p.libren.ms/view/3621dad4
snmpbulk walk:  https://p.libren.ms/view/4f048c8a

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by PipoCanaja** [comment]
Hello,
PR for this change is opened. 
https://github.com/librenms/librenms/pull/9735
(I did change the changelog value manually)

**Comment by PipoCanaja** [comment]
Done

**Comment by rk4an** [comment]
Thanks for the support of Catalyst 9300. I have a C9300-48P version 16.8.1a but missing VLANs, STP and Neighboor tabs.

Any idea please?

**Comment by jarvismeier** [comment]
Try disabling Cisco-otv in modules.  For whatever reason this module causes timeouts in snmp discovery so it doesn’t have enough time to complete.

**Comment by rk4an** [comment]
I will try, thanks 👍
