### ISSUE TITLE
Add support for Pagerduty

### ISSUE THREAD

**Issue by laf** [librenms/librenms#973]

**Comment by f0o** [comment]
Easy transport :)

**Comment by Lonecrowe** [comment]
Oooh that would be saucy.. 

It has an API too I believe as well as an APP.

**Comment by f0o** [comment]
@Lonecrowe are you a PagerDuty user?
Could need a 2nd pair of eyes testing my draft.

**Comment by Lonecrowe** [comment]
Yes we use it and I will test

**Comment by laf** [comment]
:+1: works for me.

**Comment by f0o** [comment]
I'm going to strip out the debugging-statements and submit a PR.
Would be nice if you both could give it another round of tests :)

For ACK, a different PR will be submitted.

**Comment by Lonecrowe** [comment]
Man you move fast.  I'll try and take a look today.

**Comment by Lonecrowe** [comment]
Working well for me.  I was getting information about the alerts.  I'll check it out more next week.  I would like to see the "values" that get reported.  For example it warned me about 
sensor_id => 633; sensor_oid => upsHighPrecOutputCurrent.0; sensor_descr => Current Drawn;

I'd like to see how much current was drawn and what the threshold was.

**Comment by itscassa** [comment]
I've written something like this, but not at the office atm, will check when I'm there once again (~1 month)

**Comment by laf** [comment]
@Itscassa written pager duty support? If so we've already got it now, was merged in a couple of days ago.

**Comment by itscassa** [comment]
@laf Whoops, haven't seen that yet

**Comment by f0o** [comment]
Closing as it's been merged already
