### ISSUE TITLE
New device: D-Link DGS-1210-xx

### ISSUE THREAD

**Issue by marcywi** [librenms/librenms#9730]
can you provide support for the device below? 
i want to get informations about poe, poe load, ...

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/6f967e06
https://p.libren.ms/view/46eefb6f
https://p.libren.ms/view/747a37df#L2221
- [X] Please provide as much detail as possible.
Device Type 		DGS-1210-10P 	
Boot Version 		1.00.016	
Firmware Version 	4.00.064 	
Hardware Version 	C1
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by PipoCanaja** [comment]
Hi @marcywi 
Unfortunately, the vendor does not provide it in the snmpdata you provided. Only the fact that POE is enabled can be gathered. Feel free to re-open if a software update improves SNMP support. 
Bye
