### ISSUE TITLE
Add support for Teldat Devices

### ISSUE THREAD

**Issue by rokkhan** [librenms/librenms#9741]
Hi, 

Please, add support for Teldat routers.

I attach snmpwalkd of the device

Thanks in advance

[teldat.txt](https://github.com/librenms/librenms/files/2798281/teldat.txt)

**Comment by PipoCanaja** [comment]
- [] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

- [] Please provide as much detail as possible.

- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by rokkhan** [comment]
Sorry

Discovery
https://p.libren.ms/view/4f869b10

Poller
https://p.libren.ms/view/9822747d

snmpbulkwalk does not work:

Paste endpoint: https://p.libren.ms/api/create
Error: OID not increasing: .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0
 >= .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0

Error: OID not increasing: .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0
 >= .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0

Error: OID not increasing: .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0
 >= .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0

Error: OID not increasing: .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0
 >= .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0

Error: OID not increasing: .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0
 >= .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0

Error: OID not increasing: .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0
 >= .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0

Error: OID not increasing: .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0
 >= .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0

Error: OID not increasing: .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0
 >= .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0

Error: OID not increasing: .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0
 >= .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0

Error: OID not increasing: .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0
 >= .1.3.6.1.4.1.2007.4.1.2.3.15.3.7.0

title: 
name: root
private: 1
expire: 0
Error: Missing paste text

**Comment by kkrumm1** [comment]
We really need the snmp bulk walk.

**Comment by rokkhan** [comment]
Is this one ok?

[snmpbulkwalk_teldat.txt](https://github.com/librenms/librenms/files/2798907/snmpbulkwalk_teldat.txt)

**Comment by PipoCanaja** [comment]
Looks good now.

**Comment by PipoCanaja** [comment]
Hi @rokkhan 
Could you please provide the mibfiles as well. Support is ongoing but is limited if no mibs are provided (only ports/interfaces as you already have right now, only the logo will be added)

**Comment by rokkhan** [comment]
Hi,

I attach the mib files for two different models. Please, let me know if you need anything else.

Thanks a lot!

[Teldat.zip](https://github.com/librenms/librenms/files/3978817/Teldat.zip)

**Comment by PipoCanaja** [comment]
Hi
Not really much data to add, except serial number and BoardType so far. Feel free to let us know if you see something else. 
Bye
