### ISSUE TITLE
New Device: Eaton 5PX UPS with NetworkMS NIC

### ISSUE THREAD

**Issue by PatoVidal** [librenms/librenms#9742]
- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/69da5b8d
https://p.libren.ms/view/93796c02
https://p.libren.ms/view/ab92a5e3
- [X] Please provide as much detail as possible.
Device: Eaton 5PX 1500
Card Revision: LA
Firmware Revision: LB
My devices get discovered in the beginning but after half an hour or so libre deletes all sensors and "rebrands" them as Generic devices. I have 6 new Eaton 5PX:s and i'm seeing this on all of them.
I have tested both Firmware LA and LB, all cards are Revision LA
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by JQ-KH** [comment]
Same problem here with two Eaton 9PX 3000 with NetworkMS NIC and Firmware LB.
Devices get added ok and as soon as the discovery cronjob runs the sensors get deleted and the device type changes to generic. 
I tried a rediscovery but to no avail. I deleted the devices and everytime I add them now they get discovered as generic devices and no longer as USVs.
Is the initial discovery on "Add device" cached somewhere?

**Comment by JQ-KH** [comment]
Duh! 
Possible cause ist discussed here https://community.librenms.org/t/eaton-9px-ups-issue/3973/4
Seems to be a firmware issue. I will try to contact Eaton and get a statement.

**Comment by PipoCanaja** [comment]
@JQ-KH Any results from them ? 
@PatoVidal The data provided for the snmpwalk command contains random carriage returns making it unusable. If necessary, please reopen this issue, and provided the data as asked  [here](http://docs.librenms.org/Support/FAQ/#faq20).

**Comment by PatoVidal** [comment]
Hi, @PipoCanaja, i reopen the issue.

https://p.libren.ms/view/07b7b379 - Discovery
https://p.libren.ms/view/2ee4e532 - Poller
https://p.libren.ms/view/59e631a1 - SNMPwalk

Device: Eaton 5PX 1500
Card Revision: LA
Firmware Revision: LB

My devices still gets discovered in the beginning (a reboot will do it) but after half an hour or so libre deletes all sensors and "rebrands" them as Generic devices. I have 6 new Eaton 5PX:s and i'm seeing this on all of them.
I have tested both Firmware LA and LB, all cards are Revision LA
They work fine in other NMS systems such as Nagios

/Pato

**Comment by PipoCanaja** [comment]
@PatoVidal 
The Snmpwalk data is not usable. We have CarriageReturns spread all over the file, making it unusable. 
Could you please update the file and have one without CR ?
Thanx

**Comment by PipoCanaja** [comment]
Please re-open the case when the necessary data will be available.

**Comment by dagbdagb** [comment]
1. Eaton Network Card MS (which used in quite a lot of Eaton UPS models) is now EoL. Good riddance, it is also an underpowered piece of junk.


2. Eaton dropped a final(?) firmware update (LD) in december 2019. The releasenotes generally reads as notes from a networking horror story.

BUT: it comes with some really important fixes:

   - ifDescr and SysOid SNMP values corruption    <-  !!!
   - Crash and factory reset on SNMP-Set of SysName
   - Unable to login via SSH if HTTPS is enabled
   - Let Web UI accept '!' sign in the passwords

Release LC contained this gem:
   - Telnet was available even when disabled.


3. For anyone operating Eaton UPSes, the new M2 Gigabit card (drop-in replacement for MS) looks really good. Secure protocols by default.
