### ISSUE TITLE
New device: Avigilon IP camera

### ISSUE THREAD

**Issue by 917huB** [librenms/librenms#9746]
I would like to add monitoring of my [Avigilon](http://avigilon.com) camera systems in LibreNMS. Please find below the data for a [H4A Dome Camera with Self-Learning Video Analytics](http://avigilon.com/products/video-surveillance/cameras/hd-domes).

Avigilon provide MIBs [here](http://avigilon.com/support-and-downloads/for-cameras-and-hardware/firmware-updates-and-downloads/)

I have an request in for permission to use branding, will follow-up when I hear back. 

- [x ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

[https://p.libren.ms/view/0a040087](https://p.libren.ms/view/0a040087)
[https://p.libren.ms/view/5e149a80](https://p.libren.ms/view/5e149a80)
[https://p.libren.ms/view/a3881565](https://p.libren.ms/view/a3881565)

**Comment by kkrumm1** [comment]
Hi,

We need the snmp bulk walk also.

**Comment by 917huB** [comment]
Sorry, can you check again please.[https://p.libren.ms/view/a388156(https://p.libren.ms/view/a388156), I was in the process of editing my link when you commented... there doesn't appear to be a lot of information though.

**Comment by PipoCanaja** [comment]
@917huB 
Looks like you only have the vendor mib data here. Seems surprising that no standard MIB at all are supported (not even sysname etc etc). Could you check how you did the snmpwalk compared to the FAQ ?

**Comment by 917huB** [comment]
Thanks for taking a look at this @PipoCanaja 
I verified my working with other devices in my setup which reported meaningful results, i.e see discovery-ruckus.txt I attached. 

I run the following captures from the web site to avoid any command line user errors. I captured from 2 of my cameras to check it wasn't one specific device returning odd results. 

Please let me know what else I can do to help?


[poller-192.168.50.210.txt](https://github.com/librenms/librenms/files/2999019/poller-192.168.50.210.txt)
[discovery-192.168.50.210.txt](https://github.com/librenms/librenms/files/2999020/discovery-192.168.50.210.txt)

[poller-192.168.50.208.txt](https://github.com/librenms/librenms/files/2999021/poller-192.168.50.208.txt)
[discovery-192.168.50.208.txt](https://github.com/librenms/librenms/files/2999022/discovery-192.168.50.208.txt)
[discovery-ruckus.txt](https://github.com/librenms/librenms/files/2999023/discovery-ruckus.txt)
![Devices - LibreNMS 2019-03-22 22-05-54](https://user-images.githubusercontent.com/22522964/54861910-42048d00-4cef-11e9-8ac6-8c3afc7b1f4c.jpg)

**Comment by PipoCanaja** [comment]
Unfortunately, the SNMP support on these devices is very limited. Only thing that can be added is basically a logo when you discover it. 
You should probably contact the vendor and ask for a proper SNMP implementation.

**Comment by PipoCanaja** [comment]
Hi @917huB 
I am closing this issue because of the lack of MIB data. Feel free to re-open if the vendor improves SNMP support. 
Bye
