### ISSUE TITLE
ifSpeed overwrite

### ISSUE THREAD

**Issue by pubyun** [librenms/librenms#9781]
i would like to manually set  port ifSpeed of HP 5900.
it will auto recovery to the speed read from device.

it works on Nexus 9300.

**Comment by Rosiak** [comment]
Sorry but this is not the place to ask for help.

This issue has been closed as it isn't classed as a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by murrant** [comment]
Sorry for the ping, testing the bot.
