### ISSUE TITLE
New device: Epson network projector

### ISSUE THREAD

**Issue by stefankugler** [librenms/librenms#9782]
I would like to check lamp operation hours of our epson projectors.

discovery: https://p.libren.ms/view/abd3af88
poller: https://p.libren.ms/view/98801abb
bulksnmpwalk: https://p.libren.ms/view/f27b68df

Here are some relevant oids:
https://github.com/AMXAUNZ/amx-snmp-library/blob/master/RmsEpsonProjectorMonitor.axs#L114
https://lists.mathias-kettner.de/pipermail/checkmk-commits/2016-September/016283.html

Thank you!
Stefan

**Comment by trs80** [comment]
Looks like this will need a new device type (projector)?

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-epson-network-projector/11631/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11631
