### ISSUE TITLE
New OS Request: OSMC (Open Source Media Centre)

### ISSUE THREAD

**Issue by SirMaple** [librenms/librenms#9785]
Would like to see OSMC(Open Source Media Centre) added as an OS. 

> ./discovery.php -h HOSTNAME -d | ./pbin.sh -> https://p.libren.ms/view/ef891b70

> ./poller.php -h HOSTNAME -r -f -d | ./pbin.sh -> https://p.libren.ms/view/54fd9d47

> snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh -> https://p.libren.ms/view/0d983add

> Icon -> https://discourse-cdn.osmc.tv/uploads/default/original/2X/4/490dabf57baddbdc08ba95bc77627f269bd4cea9.png

**Comment by murrant** [comment]
Does OSMC (Raspbian) have MIBs?

**Comment by SirMaple** [comment]
No.

It's a custom raspbian distribution but it also runs on its own hardware device as well called the Vero.

**Comment by murrant** [comment]
Isn't this just "linux" then?  We could update the distro script and add an icon show it shows up as Linux (OSMC)... Is that what you are looking for?

**Comment by SirMaple** [comment]
Correct it would just be "Linux".

Updating the distro script should do the trick.

**Comment by murrant** [comment]
Any idea how to check if it is OSMC via the cli?

**Comment by murrant** [comment]
Oh, interesting: http://0pointer.de/blog/projects/os-release.html

**Comment by SirMaple** [comment]
Cool. I didn't even know about the os-release file. That would work. Here is the output:
>osmc@pi4:~$ cat /etc/os-release
PRETTY_NAME="Open Source Media Center"
NAME="OSMC"
VERSION="December 2018"
VERSION_ID="2018.12-1"
ID=osmc
ID_LIKE=debian

>ANSI_COLOR="1;31"
HOME_URL="https://www.osmc.tv"
SUPPORT_URL="https://www.osmc.tv"
BUG_REPORT_URL="https://www.osmc.tv"
osmc@pi4:~$ 

uname also outputs the following:
>osmc@pi4:~$ uname -a
Linux brains 4.14.78-4-osmc #1 SMP PREEMPT Wed Dec 12 17:58:11 UTC 2018 armv7l GNU/Linux
