### ISSUE TITLE
New device EATON ePDU DBQ145412

### ISSUE THREAD

**Issue by barajus** [librenms/librenms#9823]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

discovery: https://p.libren.ms/view/a2ad6d17
poller: https://p.libren.ms/view/eba4036d
bulksnmpwalk: https://p.libren.ms/view/51507ea2

Here is the mib : 
[MIB-eaton.txt](https://github.com/librenms/librenms/files/2864715/MIB-eaton.txt)

**Comment by PipoCanaja** [comment]
Bonjour @barajus 
Feel free to test the PR #9947 
PipoCanaja
