### ISSUE TITLE
New Device : EDFA SNMP Agent V2.0

### ISSUE THREAD

**Issue by romsworld** [librenms/librenms#9826]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

https://p.libren.ms/view/2e858157#L16
https://p.libren.ms/view/9cd7b23e#L5
https://p.libren.ms/view/1218d526

EDFA SNMP Agent V2.0
https://p.libren.ms/view/886d01c3

Thanks,

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by PipoCanaja** [comment]
Hi @romsworld 
Could you please don't link to any data from Observium. You should get the MIBs from the vendor.
Thanx

**Comment by romsworld** [comment]
Hi,

Ok, sorry for link. Please find mib file.
Thanks,
[NSCRTV-ROOT.mib.txt](https://github.com/librenms/librenms/files/2865261/NSCRTV-ROOT.mib.txt)

**Comment by romsworld** [comment]
Hi,

How long do you think it will take to integrate this new equipment?

Thanks lot,

**Comment by PipoCanaja** [comment]
> Hi,
> 
> How long do you think it will take to integrate this new equipment?
> 
> Thanks lot,

Hi @romsworld 
As you can see, the todolist is quite long. The LibreNMS project is volunteers based, so everybody's free to contribute code on either its spare time. We therefore cannot tell you when this new equipment will be integrated. 
PipoCanaja

**Comment by romsworld** [comment]
Hi,

How can convert mib file to an discovery yaml file.
I have read this doc https://docs.librenms.org/Developing/os/Health-Information/, but it's not clear. is it a manual ?

Thanks,

**Comment by cppmonkey** [comment]
I've been working on another EDFA and it has taken me weeks to get to where I am now.
Might be easier for yours, as we have several versions of the same hardware with minor MIB differences

https://github.com/librenms/librenms/compare/master...cppmonkey:tryin

Looking over the MIBs you've provided, it looks to be designed in a more logical way. Don't even need to open it up in a MIBs viewer to see that.

I've been integrating new equipment, as the company I work for use them.

**Comment by jozefrebjak** [comment]
@romsworld  try this PR #9912 there is also implemented EDFA in this PR #9125,
