### ISSUE TITLE
New device: Volt Popprotect

### ISSUE THREAD

**Issue by mailanetworks** [librenms/librenms#9836]
MIB: http://www.volt.ind.br/mibs/popprotect.zip

**Comment by PipoCanaja** [comment]
Hello
Please provide all the details that were requested in the Issue template. Without them, there is nothing we can do.
Bye

**Comment by mailanetworks** [comment]
Hello,

Here:
Discovery:
https://p.libren.ms/view/776fda8d
Poller:
https://p.libren.ms/view/4b19af91
SNMP:
https://p.libren.ms/view/cb5ce8b2

MIB:
http://www.volt.ind.br/mibs/popprotect.zip

Product page:
http://www.volt.ind.br/popprotect.php

**Comment by PipoCanaja** [comment]
Hi @mailanetworks 
It is much better but the snmpwalk seems to be pretty buggy. Could you retry the snmpwalk with the ``` -Cc ``` added in the command line ? That should avoid the "OID not increasing" error. We'll see if we get more data than what you have so far. 
PipoCanaja

**Comment by mailanetworks** [comment]
Hi @PipoCanaja 
snmpwalk with -C added,
-Cc returns error
https://p.libren.ms/view/4e98554b

**Comment by PipoCanaja** [comment]
Could you attach the snmpwalk command you typed ? -Cc is a standard option of snmpwalk ...

**Comment by PipoCanaja** [comment]
Hi
Please reopen issue when the necessary data will be provided.
Bye

**Comment by mailanetworks** [comment]
Hi @PipoCanaja 
Tell me what data you need.
I have since then upgraded librenms and the PHP Libraries, but the results are the same.

Thanks,

**Comment by PipoCanaja** [comment]
Without the result of a complete snmpwalk, the issue cannot be handled. For the moment, the snmpwalk seems incomplete. (Or if it is complete, then the device does not supply any useful information in it that LibreNMS could display).

**Comment by mailanetworks** [comment]
Capture
https://p.libren.ms/view/14bb68c2

SNMP
https://p.libren.ms/view/7aedb2e1

Poller:
https://p.libren.ms/view/3bac770b

And here is the XML file that is being used by Zabbix to monitor this device:
https://p.libren.ms/view/c3188b6a

Thanks,

**Comment by PipoCanaja** [comment]
Hi @mailanetworks 
The SNMPWALK is not complete. The OID for the temperature (for instance) is in the XML file (so I suppose it does exist) but it is not in the snmpwalk. Without a complete snmpwalk, the support cannot be added. 
So snmpwalk should contain at least all the OIDs you expect LibreNMS to discover (you can take them from the XML). 
Once we have a working snmpwalk, this issue will be in the queue for processing. 
Bye
