### ISSUE TITLE
New device: Perle Terminal Servers

### ISSUE THREAD

**Issue by esundberg** [librenms/librenms#9847]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org/c/help).**

To create a new device request please use this link: https://github.com/librenms/librenms/issues/new?template=New-Device.md

**Comment by esundberg** [comment]
Looking to add support for Perle Terminal servers.

Make: Perle IOLan SCS48
System OID: .1.3.6.1.4.1.1966.12
Website: perle.com
SNMP MIB File: https://www.perle.com/downloads/software/iolan/perle-sds.mib
Devices come in 2-48 port terminal servers
You can call the OS: Perle

There might already be some support for perle devices not sure if it's the same devices. https://github.com/librenms/librenms/blob/master/mibs/perle/PERLE-MCR-MGT-MIB


librenms@librenms:~$ ./discovery.php -h 172.16.1.24 -d | ./pbin.sh 
Paste endpoint: https://p.libren.ms/api/create
title: 
name: librenms
private: 1
expire: 0
https://p.libren.ms/view/5b72cb36


librenms@librenms:~$ ./poller.php -h 172.16.1.24 -r -f -d | ./pbin.sh           
Paste endpoint: https://p.libren.ms/api/create
title: 
name: librenms
private: 1
expire: 0
https://p.libren.ms/view/367df499


For snmpbulkwalk i am gettting the following error back from the API Server.

snmpbulkwalk -OUneb -v2c -c ****** 172.16.1.24 . | ./pbin.sh
Paste endpoint: https://p.libren.ms/api/create
Error in packet.
Reason: (genError) A general failure occured
title: 
name: librenms
private: 1
expire: 0

Error Number: 1153</p><p>Got a packet bigger than 'max_allowed_packet' bytes

I will attach this output

**Comment by esundberg** [comment]
[Perle SNMP Walk.txt](https://github.com/librenms/librenms/files/2882798/Perle.SNMP.Walk.txt)

Here is the SNMP Bulk Walk.

Let me know if you need anything else.

**Comment by esundberg** [comment]
Hmmm.. Don't click Close and comment if you want this to stay open

**Comment by PipoCanaja** [comment]
> Perle SNMP Walk.txt

Hi @esundberg. It seems that the pbin did not succeed. Could you attach a file with the data instead of the current file which contains dirty HTML code ? 
Thanx

**Comment by esundberg** [comment]
[perle.snmpbulk.txt](https://github.com/librenms/librenms/files/2886574/perle.snmpbulk.txt)
[perle.snmpwalk.txt](https://github.com/librenms/librenms/files/2886575/perle.snmpwalk.txt)

Here is a SNMPBulkWalk and a SNMP Walk

**Comment by PipoCanaja** [comment]
All right, looks good

**Comment by esundberg** [comment]
@PipoCanaja I would like to help create this if possible. I would just need a little guidance.


Model and OS Version will need to be parsed from: iso.3.6.1.2.1.1.1.0 = STRING: "SCS48, 4.9.G3 (Tue Apr 18 09:37:42 EDT 2017)"

They use the 1st Ethernet MAC as the Device Serial Number: iso.3.6.1.2.1.2.2.1.6.2 = Hex-STRING: 00 80 D4 10 B7 61

![image](https://user-images.githubusercontent.com/14306155/53133071-7c83da00-3537-11e9-84a5-6282850d652c.png)




Am I correct on the following on what needs to be created. Is there any dev docs for new SNMP pollers\sensors.

Update: cache/os_defs.cache 
----Needs to include Supported Device OID's

includes/polling/os/perle.inc.php
--Get SNMP Vaule for Version, Hardware, SN, Features

includes/discovery/sensors/temperature/perle.inc.php:
--Create a Tempature Sensor

include/discovery/sensors/ (Any other sensors power, state, and etc)

includes/definitions/aen.yaml:text: 'Accedian AEN'
--Properly Name the Device. Reference the created poller and discovery Modules.

LibreNMS/OS/Aen.php: * Accedian OS
--Define where to get the Processor Usage what OID

**Comment by esundberg** [comment]
I think i have this done, I just submitted a Pull Request.

No Support for SNMP CPU and Memory Usages

This is just a OS Add for .1.3.6.1.4.1.1966.12 to the existing os called: perle

Added the following lines to includes/definitions/perle.yaml 
    - sysObjectID:
        - .1.3.6.1.4.1.1966

Submitted a snmprec under perle_iolan_scs.snmprec

**Comment by esundberg** [comment]
I realize this might of been a mistake to put the snmprec file as perle_iolan_scs.snmprec when the os is call perle

How do you want me to handle this? Create a new device call perle_iolan_scs?

**Comment by PipoCanaja** [comment]
We'll get to the snmprec after. Let's stabilize the definition file, then we'll see if you have sensors you can add, and then the test files will be made right.

**Comment by PipoCanaja** [comment]
PR here : #9866

**Comment by PipoCanaja** [comment]
OK, PR merged. 
Your device (the one you used for the snmpwalk in this issue) seems to be running an outdated version of firmware, that does not comply with the MIB attached (it is written in the MIB, at least).
If you have a newer box (or an older one updated) feel free to repoen the issue, with snmpwalk attached, and we'll see if we can improve the discovery.
