### ISSUE TITLE
SQL error during for SLA device rediscovery

### ISSUE THREAD

**Issue by jarossi** [librenms/librenms#9851]
#### Load disco module cisco-sla ####
SQL Error! SQLSTATE[HY093]: Invalid parameter number: mixed named and positional parameters (SQL: UPDATE `slas` set `device_id`=117,`sla_nr`=11,`owner`=,`tag`=XX.XX.X.XX,`rtt_type`=echo,`status`=1,`opstatus`=0,`deleted`=0 WHERE `sla_id` = 7) (SQL: UPDATE `slas` set `device_id`=117,`sla_nr`=11,`owner`=,`tag`=XX.XX.X.XX,`rtt_type`=echo,`status`=1,`opstatus`=0,`deleted`=0 WHERE `sla_id` = 7)
  /opt/librenms/includes/discovery/cisco-sla.inc.php:80
  /opt/librenms/includes/discovery/functions.inc.php:179
  /opt/librenms/discovery.php:120

**Comment by jarossi** [comment]
why this was labeled as support-request and then closed by the bot? isn't it a bug?

Regards

Juan.-

**Comment by kkrumm1** [comment]
This is only for new device requests.. it tells you that and also when open the issue it says it again.. please read first.
