### ISSUE TITLE
New device: Dell Storage Center SCv2080 Storage System

### ISSUE THREAD

**Issue by DGothmin** [librenms/librenms#9852]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations
Discovery
https://p.libren.ms/view/3be3f1ab
Poller
https://p.libren.ms/view/2dbef2d8
SNMPbulkWalk
https://p.libren.ms/view/3df8b98d
MIB files has been attached
[MIB2014.01.29.zip](https://github.com/librenms/librenms/files/2888867/MIB2014.01.29.zip)

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-dell-storage-center-scv2080-storage-system/11630/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11630
