### ISSUE TITLE
New Device : Dell Blade - PowerEdge M610

### ISSUE THREAD

**Issue by DGothmin** [librenms/librenms#9853]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations
Discovery - https://p.libren.ms/view/d25b5772
Poller - https://p.libren.ms/view/ff7d02d7
SNMPWalk - https://p.libren.ms/view/a91b4079

SNMP - https://www.dell.com/support/home/uk/en/ukbsdt1/drivers/driversdetails?driverid=r214941

**Comment by cppmonkey** [comment]
Duplicate: https://github.com/librenms/librenms/issues/9418

Also have you tried adding IPMI to the device, either the server entry or the iDRAC? You'll need to enable IMPI within the IDRAC settings on the device and along with adding the IPMI login details on your LibreNMS device

**Comment by DGothmin** [comment]
I have not tried IPMI. I will check if it is possible..

**Comment by DGothmin** [comment]
I have checked and no option for IPMI on Dell Blade

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-dell-blade-poweredge-m610/11629/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11629
