### ISSUE TITLE
New Device: Dell Blade Chassis - PowerEdge M1000e

### ISSUE THREAD

**Issue by DGothmin** [librenms/librenms#9854]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Discovery
https://p.libren.ms/view/63b31cb1
Poller
https://p.libren.ms/view/26d86395
SNMP Walk
https://p.libren.ms/view/3a023031

**Comment by spencerbutler** [comment]
@DGothmin What is not being monitored that you would like to see added?

**Comment by DGothmin** [comment]
@spencerbutler this is a Blade Chassis, A the moment it monitor only Management network card, i would like to monitor 
* What blades populated on which bay 
* Power usage / Fail on chassis
* FAN Status
* Hardware performance
* Temperature Sensor informations
* I/O Module information like network cards ..

**Comment by spencerbutler** [comment]
@DGothmin I'll check it out and see what can be added.

**Comment by MrXermon** [comment]
MIBs can be found here: https://downloads.dell.com/sysman/DCMIB65.zip

**Comment by daniviga** [comment]
This is what I have reported in a (quite) old Observium installation:

![Screenshot from 2019-05-20 15-42-27](https://user-images.githubusercontent.com/1818657/58026055-fc5d1880-7b15-11e9-8f4f-85f76cf0b5ac.png)

**Comment by PipoCanaja** [comment]
fixed in #10310
