### ISSUE TITLE
Alarm colour "Current" in device health menu

### ISSUE THREAD

**Issue by runeka** [librenms/librenms#9855]
Clearing out false positives in device health is time consuming on some platforms. Is it possible to add the same colour alerts that are on the device frontpage to the edit->health page? Making "Current" red if it is alerting and maybe even yellow if it is in warning state for every entity.

In this example 23 would be in red:
Class.            Type.                         Desc.                    Current High Highwarn Lowwarn Low
temperature cisco-entity-sensor Module-1 FRONT **23**   21    18              13            10

If possible, using the same funtionality that is on the frontpage.

**Comment by kkrumm1** [comment]
Sorry but this is not the place to ask for help or request changes.

This issue has been closed as it isn't classed as a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
