### ISSUE TITLE
New Device: CyberPower - PDU41004

### ISSUE THREAD

**Issue by DGothmin** [librenms/librenms#9856]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Mibs: [CyberPower_MIB_v2.6.zip](https://github.com/librenms/librenms/files/2889372/CyberPower_MIB_v2.6.zip)

] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Discovery - https://p.libren.ms/view/079cee6c

Poller - https://p.libren.ms/view/fa4640f3

SNMP Walk - https://p.libren.ms/view/322eec30
MIBs attached

**Comment by DGothmin** [comment]
[CyberPower_MIB_v2.6.zip](https://github.com/librenms/librenms/files/2970251/CyberPower_MIB_v2.6.zip)
Found some MIBs

**Comment by spencerbutler** [comment]
@DGothmin Your snmpwalk link is blank and your discovery.php shows you have some connectivity issues to resolve before LibreNMS can properly monitor your device. 

>Timeout: No Response from udp:10.255.255.68:161

FWIW, this device is currently supported -- so once you resolve the SNMP connection issue, let us know if there is anything missing you'd like to see.
