### ISSUE TITLE
New Device: MRV InReach - LX Series Linux-Based Secure Console Servers

### ISSUE THREAD

**Issue by antechnetwork** [librenms/librenms#9858]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

discovery: https://p.libren.ms/view/80335df2
poller: https://p.libren.ms/view/dfe9130f
snmpwalk: https://p.libren.ms/view/766cbe92

MIBS:
[mrvmibs5.3.2.zip](https://github.com/librenms/librenms/files/2890391/mrvmibs5.3.2.zip)

Thanks

**Comment by PipoCanaja** [comment]
Hi @antechnetwork 
The data you provided is not in the correct format (snmpwalk). Please use exactly the command provided. 
Thanx
