### ISSUE TITLE
Device Type has single quotes

### ISSUE THREAD

**Issue by esundberg** [librenms/librenms#9873]
OpenGear device type of 'OOB Management'

The single quotes probably need to be removed.

librenms@librenms-devel:/opt/librenms/includes/definitions$ cat opengear.yaml 
os: opengear
text: Opengear
type: 'OOB Management'
icon: opengear
mib_dir:
    - opengear
discovery:
    - sysObjectID:
        - .1.3.6.1.4.1.25049.1

**Comment by PipoCanaja** [comment]
Hello @esundberg 
You can directly post a PR for this. That will allow us to discuss it and commit it right away
Thanx
PipoCanaja
