### ISSUE TITLE
New Device: Cisco FirePower 2140

### ISSUE THREAD

**Issue by 07stuntar1** [librenms/librenms#9880]
Hi I just tried to add Cisco Firepower 2140 Security Appliance to LibreNMS and it only shows "octeon"
Generic Device.

Cisco Firepower Threat Defense, Version 6.3.0.1 (Build 85), ASA Version 9.10(1)8
System Nameocteon
IP Address:
Operating SystemGeneric Device
Object ID.1.3.6.1.4.1.9.1.2407

====================================
Component | Version
--------- | -------
LibreNMS  | 1.48.1-85-gee76057
DB Schema | 2019_02_10_220000_add_dates_to_fdb (132)
PHP       | 7.2.14
MySQL     | 5.5.60-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

discovery 
https://p.libren.ms/view/51f4ae7d

poller
https://p.libren.ms/view/db1b7d76

snmpbuilkwalk
https://p.libren.ms/view/d43587bb

Please let me know if you need anything else.
Thank You

**Comment by spencerbutler** [comment]
These files have been verified, and I will submit a PR in the near future.

**Comment by 07stuntar1** [comment]
Thank You

**Comment by spencerbutler** [comment]
@07stuntar1 Here is an initial [commit](#10046) to get some graphs drawn for you. I plan on adding some sensors and state information to it, if I am able. Give that a shot and let me know what you think.

**Comment by 07stuntar1** [comment]
@spencerbutler 
Did I pull down the right configs I ran
./scripts/github-apply 10046

Still no graphs.

**Comment by spencerbutler** [comment]
> @spencerbutler
> Did I pull down the right configs I ran
> ./scripts/github-apply 10046
> 
> Still no graphs.

did you rediscover the device?

**Comment by 07stuntar1** [comment]
I just deleted the device and ran a the discover and poller php script for the ip address
![image](https://user-images.githubusercontent.com/30091711/55205132-b74fe200-5175-11e9-9f5d-531dcd3658d9.png)

**Comment by spencerbutler** [comment]
This is what I get with your snmp data.
![ciscofpr-2140td](https://user-images.githubusercontent.com/5126075/55205562-6524b600-51a1-11e9-9382-5b2d7f1648b7.png)

**Comment by 07stuntar1** [comment]
hmm, weird. I forced discovered and poller walked it and still get the same screen I posted before. what version of snmp are u using? im using v2c. I see that it walks it fine manually.

**Comment by 07stuntar1** [comment]
./scripts/github-apply 10046
Checking patch includes/definitions/ciscofpr.yaml...
error: includes/definitions/ciscofpr.yaml: already exists in working directory
Checking patch tests/data/ciscofpr.json...
error: tests/data/ciscofpr.json: already exists in working directory
Checking patch tests/snmpsim/ciscofpr.snmprec...
error: tests/snmpsim/ciscofpr.snmprec: already exists in working directory

Is that all i needed to do to apply it?

**Comment by spencerbutler** [comment]
@07stuntar1 I would try checking out a new branch, and trying from there.

> git checkout master
> ./daily.sh
> git checkout -b ciscofpr-10046
> ./scripts/github-apply 10046
> ./discovery.php -v -h HOSTNAME

If that is still not adding any new data, please resubmit the discovery/poller/snmpwalk information.

**Comment by 07stuntar1** [comment]
Sweet it seem to have started working overnight. Maybe it way the daily. Thank You!
![image](https://user-images.githubusercontent.com/30091711/55255033-9cc14b80-51fd-11e9-9d27-25db52529631.png)

**Comment by spencerbutler** [comment]
Glad to hear it's working for you. What is your concern with the overall traffic?

**Comment by 07stuntar1** [comment]
I think its only showing the management interface. The ports on the ports page show more
![image](https://user-images.githubusercontent.com/30091711/55268588-3ead5c00-522f-11e9-9a38-6564f5c9a98d.png)

**Comment by hrv231** [comment]
Hi,

I have the same thing, my Firepower 2110 is showing octeon, and I discovered that it's not a problem from LibreNMS, but from Cisco.
Cisco knows about this bug, I don't have the link but it is online.
Just letting you know.

**Comment by PipoCanaja** [comment]
Fixed in #10046
