### ISSUE TITLE
Add option to enable insecure to curl requests

### ISSUE THREAD

**Issue by wtc-jeff** [librenms/librenms#9882]
We have an chat server that runs self signed certificates, to get alerts working I need to edit the Alert Transport php file to add:

curl_setopt ( $curl, CURLOPT_SSL_VERIFYPEER, false);

Every now and then, an update overnight will overwrite the alert transport file and stop the transport from working.

Could there be an option added to the config file? something like: 

$config['curl]['allow_insecure'] = true/false

thanks.

**Comment by kkrumm1** [comment]
👋 @wtc-jeff  sorry but this is not the place to ask for help/request.

This issue has been closed as it isn't classed as a new device request.

For help please use our [Discord server](https://discord.gg/librenms) or the [community site](https://community.librenms.org/c/help): https://docs.librenms.org/Support
