### ISSUE TITLE
Stonegate AKA McAfee NGFW Firewall/VPN

### ISSUE THREAD

**Issue by andryukha** [librenms/librenms#9884]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Component | Version
--------- | -------
LibreNMS  | 1.48.1-85-gee76057
DB Schema | 2019_02_10_220000_add_dates_to_fdb (132)
PHP       | 7.2.14
MySQL     | 5.5.60-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

snmpwalk:  https://p.libren.ms/view/05522e0b
discovery:   https://p.libren.ms/view/47c3ebef
poller:        https://p.libren.ms/view/519592ab

**Comment by andryukha** [comment]
Any news?

**Comment by sp0kky** [comment]
Hi
I've the same problem with my FWs, I've created the yaml file in includes/definition and added MIBS in mibs/ , but when I add the FW it can't find the proper configuration.

**Comment by PipoCanaja** [comment]
@sp0kky : Please open a PR so we can help you on this.

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/stonegate-aka-mcafee-ngfw-firewall-vpn/11628/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11628
