### ISSUE TITLE
Email alerts being sent twice

### ISSUE THREAD

**Issue by cweakland** [librenms/librenms#9885]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

./discovery.php -h HOSTNAME -d | ./pbin.sh  Output: https://p.libren.ms/view/f5b05a91 
./poller.php -h HOSTNAME -r -f -d | ./pbin.sh Output: https://p.libren.ms/view/03aaeef1
./test-alert.php -d -h 30 -r 24  Output: https://p.libren.ms/view/8333e864

- [x] Please provide as much detail as possible.

All alerts weather new or old send two emails. I do not seem to be the only one, other folks in this thread have the same issue:

https://community.librenms.org/t/duplicate-email-alerts/7421/3

This is not a new installation, it has been up for over 2 years. 

- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by kkrumm1** [comment]
Please do not post bugs or ask questions
For help and support you can use our Discord server or our community site.
Please...
