### ISSUE TITLE
[Bug] Alert Notifications page: Sorts only by severity & timsetamp, regardless of column & direction selected

### ISSUE THREAD

**Issue by WascawyWabbit** [librenms/librenms#9892]
THIS IS NOT A HELP REQUEST, IT'S A BUG REPORT.
ADMINS: Before arbitrarily closing this request, please advise how one reports a bug when:
- there's no response from the community
- attempts to log an issue on github in the normal way are bounced by admins.

Thanks.

Alert notification table sorting behaviour not working as expected [validated LibreNMS latest versions 2019-03-01 and back at least 3 weeks]

* clicking any clickable column heading on the alerts notification table results in a sort by priority and then time. repeated clicks do not alter the sorted list.
  sorts by hostname, time of issue type do not work at all
* the acknowledged column is not sortable, but should be, as “show me unacknowledged alerts first” is an entirely reasonable and normal request.

I'm not a PHP coder, but i have found the following so far

licking on a heading in the alert notifications table requests ajax_table.php, with the correct data, e.g. when sorting by hostname, the form data is:

current: 1
rowCount: 50
sort[hostname]: asc
searchPhrase:
id: alerts
device_id: -1

The /opt/librenms/html/ajax_table.php file shows the sort being performed:

if (isset($_REQUEST[‘sort’]) && is_array($_POST[‘sort’])) {
foreach ($_REQUEST[‘sort’] as $k => $v) {
$sort .= " $k $v";
}
}

Then the includes/table/alerts.inc.php file is called (by include_once “includes/table/$id.inc.php”;
).

in alerts.inc.php, the following stanza is responsible for the “no matter what heading the user clicks, ignore them and sort by severity and then timestamp behaviour”:

if (!isset($vars[‘sort’]) || empty($vars[‘sort’])) {
$sort = ‘timestamp DESC’;
} else {
$sort = ‘alert_rules.severity DESC, timestamp DESC’;
}

In /opt/librenms/html/includes:

commenting out line 106 (// $sort = 'alert_rules.severity DESC, timestamp DESC;) in table/alerts.inc.php removed the “always sort by severity then timestamp, no matter what the user asks for” behaviour and gave me sort by time stamp or hostname.

I wasn’t able to sort by severity until i made the following change in common/alerts.inc.php line 232:

was: th data-column-id="severity" /th
now: th data-column-id="severity" Pri /th (angle bracket tags removed so the lines don't get mangled)

I did try removing the data-sortable=“false” tag from the ACK field, but that didn’t work (clicking on the column heading just brought back an empty table). We need a sortable field here.

Sorting the rule field is still not working as it should: clicking that column heading multiple times produces the same result, despite the POST request including the asc / desc directive.

Posts to the community help forum have yielded no results, so this is the only place left to raise this bug report.

**Comment by kkrumm1** [comment]
👋sorry but this is not the place to ask for help/request or bugs. Its says that when you first click the issue button. 

That being said. This is all open and free software IF somebody wants to they will work on the "bug" 
you can't keep demanding somebody fix this. Nobody works here as a job its all volunteer based. 
Bugs are not reported in github they are reported in community forums or discord.

This issue has been closed as it isn't classed as a new device request.

For help please use our [Discord server](https://discord.gg/librenms) or the [community site](https://community.librenms.org/c/help): https://docs.librenms.org/Support
