### ISSUE TITLE
update failed

### ISSUE THREAD

**Issue by Alex7802** [librenms/librenms#9894]
root@bpi-iot-ros-ai:/opt/librenms# ./daily.sh 
Re-running /opt/librenms/daily.sh as librenms user
Updating to latest codebase                        FAIL
Updating Composer packages                         OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK

logs:
Caching PeeringDB data
Peering DB integration disabled
Returned: 0
Updating to latest codebase

Returned: 1

validate:
====================================
Component | Version
--------- | -------
LibreNMS  | 1.48.1-27-gc7c1ca2c5
DB Schema | 2019_01_16_195644_add_vrf_id_and_bgpLocalAs (131)
PHP       | 7.2.9-1+b2
MySQL     | 5.5.57-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.8.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[FAIL]  Database: missing constraint (device_group_device/device_group_device_device_group_id_foreign)
[FAIL]  Database: missing constraint (device_group_device/device_group_device_device_id_foreign)
[FAIL]  Database: missing constraint (wireless_sensors/wireless_sensors_device_id_foreign)
[FAIL]  We have detected that your database schema may be wrong, please report the following to us on Discord (https://t.libren.ms/discord) or the community site (https://t.libren.ms/5gscd):
	[FIX]: 
	Run the following SQL statements to fix.
	SQL Statements:
	 ALTER TABLE `device_group_device` ADD CONSTRAINT `device_group_device_device_group_id_foreign` FOREIGN KEY (`device_group_id`)  REFERENCES `device_groups` (`id`) ON DELETE CASCADE;
	 ALTER TABLE `device_group_device` ADD CONSTRAINT `device_group_device_device_id_foreign` FOREIGN KEY (`device_id`)  REFERENCES `devices` (`device_id`) ON DELETE CASCADE;
	 ALTER TABLE `wireless_sensors` ADD CONSTRAINT `wireless_sensors_device_id_foreign` FOREIGN KEY (`device_id`)  REFERENCES `devices` (`device_id`) ON DELETE CASCADE;

mysql:
Database changed
MariaDB [librenms]>  ALTER TABLE `device_group_device` ADD CONSTRAINT `device_group_device_device_group_id_foreign` FOREIGN KEY (`device_group_id`)  REFERENCES `device_groups` (`id`) ON DELETE CASCADE;
Query OK, 0 rows affected (0.135 sec)              
Records: 0  Duplicates: 0  Warnings: 0

MariaDB [librenms]>  ALTER TABLE `device_group_device` ADD CONSTRAINT `device_group_device_device_id_foreign` FOREIGN KEY (`device_id`)  REFERENCES `devices` (`device_id`) ON DELETE CASCADE;
Query OK, 0 rows affected (0.053 sec)              
Records: 0  Duplicates: 0  Warnings: 0

MariaDB [librenms]>  ALTER TABLE `wireless_sensors` ADD CONSTRAINT `wireless_sensors_device_id_foreign` FOREIGN KEY (`device_id`)  REFERENCES `devices` (`device_id`) ON DELETE CASCADE;
Query OK, 48 rows affected (0.038 sec)             
Records: 48  Duplicates: 0  Warnings: 0

no effect.. error present. please help

**Comment by kkrumm1** [comment]
👋  sorry but this is not the place to ask for help/requests.

This issue has been closed as it isn't classed as a new device request.

For help please use our [Discord server](https://discord.gg/librenms) or the [community site](https://community.librenms.org/c/help): https://docs.librenms.org/Support
