### ISSUE TITLE
Add CPU and Memory utilization for TP-LINK T1600G-52TS

### ISSUE THREAD

**Issue by SirMaple** [librenms/librenms#9896]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

-----
I have both a T1600G-52TS and T1600G-28TS.

CPU and Memory utilization only show up for the T1600G-28TS and not the T1600G-52TS

>./discovery.php  -> https://p.libren.ms/view/a289bca2
>./poller.php -> https://p.libren.ms/view/e03a25fc
>snmpbulkwalk -> https://p.libren.ms/view/185bdb25

**Comment by cppmonkey** [comment]
Strange how TP-Link provide MIB files for the 52TS, but not the 28TS.

I actually have a TL-SG2424 which seems to be identical to the T1600-28TS. Will see what it does and then spin up snmpsim for the 52TS. And I'll test my TPLink TL-SG5412F

**Comment by SirMaple** [comment]
It is very strange. It could have something to do with how the 52TS is detected.

LibreNMS detects the TS28 operating system as "TP-Link JetStream" but the TS52 operating system as "TP-Link Switch". I've attached screenshots.


![screen shot 2019-03-03 at 5 28 42 pm](https://user-images.githubusercontent.com/17034743/53704476-22f29980-3dda-11e9-8bdc-84de9f58c915.png)
![screen shot 2019-03-03 at 5 28 36 pm](https://user-images.githubusercontent.com/17034743/53704475-225a0300-3dda-11e9-93c3-40cc11c47429.png)

**Comment by spencerbutler** [comment]
@SirMaple I'm looking this over now. Can you also provide a trio of files for the 28TS, so I can make a better comparison?

**Comment by SirMaple** [comment]
@spencerbutler 

As requested. Here are the outputs for the 28TS.

> ./discovery.php - https://p.libren.ms/view/da6206ae
>./poller.php - https://p.libren.ms/view/15b6ff17
> snmpbulkwalk - https://p.libren.ms/view/fdb1ad84

**Comment by spencerbutler** [comment]
@SirMaple Thanks for the new files, I will look them over now. 

#9983 is a work in progress to get this fully supported.  If you want to apply that patch on your system and report back that would be appreciated, but is not required.

**Comment by spencerbutler** [comment]
@SirMaple do you have a "health" tab in the UI for your 28TS? are the CPU and Memory stats correct?

**Comment by SirMaple** [comment]
@spencerbutler I do have a "health" tab and the stats are correct. Compared them the switch UI.

**Comment by spencerbutler** [comment]
hrm. Ok, did you add or modify the TPLINK-MIB files by chance? I'm still missing the link between the RFC MIBs and the TPLINK-MIBs. There is something goofy going on, that I have yet to identify.

Will you do me a favor and run an snmpwalk on each of those switches with the -Of (full output) option turned on?

**Comment by SirMaple** [comment]
Snmpwalks as requested:

> 28TS - https://p.libren.ms/view/f91536e3

> 52TS - https://p.libren.ms/view/f8abfc9d

**Comment by PipoCanaja** [comment]
Hello @SirMaple 
Could you update this issue with current status ? 
Thanx

**Comment by SirMaple** [comment]
Issue has been resolved. Not sure how. But CPU useage now shows for the T1600G-52TS.
