### ISSUE TITLE
H3C VLAN information is not working due to wrong MIB

### ISSUE THREAD

**Issue by sajiby3k** [librenms/librenms#9904]
Hi,

For some H3C switches, Q-BRIDGE-MIB cannot get the vlan information from the switches.

The vlan information is stored in HH3C-LswVLAN-MIB.

Is there any way to enable this "HH3C-LswVLAN-MIB" for H3C switches?

The reference so far I got from the internet is -

https://github.com/netdisco/snmp-info/issues/267

Let me know if more information is needed.

**Comment by kkrumm1** [comment]
👋  sorry but this is not the place to ask for help/requests. Talk to us in discord or the community forums.

This issue has been closed as it isn't classed as a new device request.

For help please use our [Discord server](https://discord.gg/librenms) or the [community site](https://community.librenms.org/c/help): https://docs.librenms.org/Support

**Comment by sajiby3k** [comment]
I am just putting some info if somebody can help me. To me it is a issue as for H3C devices, Q-Bridge-mib do not work to get vlan information.

Three are some outputs when I run discovery from Librenms -

ver version1 SNMP[’/usr/bin/snmpbulkwalk’ ‘-v2c’ ‘-c’ ‘COMMUNITY’ ‘-OQUs’ ‘-m’ ‘Q-BRIDGE-MIB’ ‘-M’ ‘/opt/librenms/mibs’ ‘udp:HOSTNAME:161’ ‘dot1qVlanStaticName’]

dot1qVlanStaticName = No Such Object available on this agent at this OID

SNMP[’/usr/bin/snmpbulkwalk’ ‘-v2c’ ‘-c’ ‘COMMUNITY’ ‘-OQUs’ ‘–hexOutputLength=0’ ‘-m’ ‘Q-BRIDGE-MIB’ ‘-M’ ‘/opt/librenms/mibs’ ‘udp:HOSTNAME:161’ ‘dot1qVlanCurrentEgressPorts’]

dot1qVlanCurrentEgressPorts = No Such Object available on this agent at this OID

SNMP[’/usr/bin/snmpbulkwalk’ ‘-v2c’ ‘-c’ ‘COMMUNITY’ ‘-OQUs’ ‘–hexOutputLength=0’ ‘-m’ ‘Q-BRIDGE-MIB’ ‘-M’ ‘/opt/librenms/mibs’ ‘udp:HOSTNAME:161’ ‘dot1qVlanCurrentUntaggedPorts’]

dot1qVlanCurrentUntaggedPorts = No Such Object available on this agent at this OID

But If I do manual snmpwalk -

snmpwalk -Os -v 2c -c XXXX 10.10.10.10 1.3.6.1.4.1.25506.8.35.2.1.1.1.2

enterprises.25506.8.35.2.1.1.1.2.1 = STRING: “defaultvlan”
enterprises.25506.8.35.2.1.1.1.2.100 = STRING: “VLAN100”
enterprises.25506.8.35.2.1.1.1.2.200 = STRING: “VLAN200”
enterprises.25506.8.35.2.1.1.1.2.300 = STRING: “VLAN300”

Let me know if any more info is needed.

**Comment by kkrumm1** [comment]
It’s best if you do this in community forums
