### ISSUE TITLE
H3C - Needs support for HH3C-LswVLAN-MIB

### ISSUE THREAD

**Issue by sajiby3k** [librenms/librenms#9915]
I am just putting some info if somebody can help me. To me it is a issue for H3C devices, Q-Bridge-mib does not work to get vlan information.

The librenms is using wrong MIB to get the vlan information. It should use HH3C-LswVLAN-MIB.

I have already opened issue number #9904 but @kkrumm1 closed it without asking for any information.

Below are some outputs when I run discovery from Librenms -

ver version1 SNMP[’/usr/bin/snmpbulkwalk’ ‘-v2c’ ‘-c’ ‘COMMUNITY’ ‘-OQUs’ ‘-m’ ‘Q-BRIDGE-MIB’ ‘-M’ ‘/opt/librenms/mibs’ ‘udp:HOSTNAME:161’ ‘dot1qVlanStaticName’]

dot1qVlanStaticName = No Such Object available on this agent at this OID

SNMP[’/usr/bin/snmpbulkwalk’ ‘-v2c’ ‘-c’ ‘COMMUNITY’ ‘-OQUs’ ‘–hexOutputLength=0’ ‘-m’ ‘Q-BRIDGE-MIB’ ‘-M’ ‘/opt/librenms/mibs’ ‘udp:HOSTNAME:161’ ‘dot1qVlanCurrentEgressPorts’]

dot1qVlanCurrentEgressPorts = No Such Object available on this agent at this OID

SNMP[’/usr/bin/snmpbulkwalk’ ‘-v2c’ ‘-c’ ‘COMMUNITY’ ‘-OQUs’ ‘–hexOutputLength=0’ ‘-m’ ‘Q-BRIDGE-MIB’ ‘-M’ ‘/opt/librenms/mibs’ ‘udp:HOSTNAME:161’ ‘dot1qVlanCurrentUntaggedPorts’]

dot1qVlanCurrentUntaggedPorts = No Such Object available on this agent at this OID

But If I do manual snmpwalk -

snmpwalk -Os -v 2c -c XXXX 10.10.10.10 1.3.6.1.4.1.25506.8.35.2.1.1.1.2

enterprises.25506.8.35.2.1.1.1.2.1 = STRING: “defaultvlan”
enterprises.25506.8.35.2.1.1.1.2.100 = STRING: “VLAN100”
enterprises.25506.8.35.2.1.1.1.2.200 = STRING: “VLAN200”
enterprises.25506.8.35.2.1.1.1.2.300 = STRING: “VLAN300”

Let me know if any more info is needed.

**Comment by PipoCanaja** [comment]
Hi @sajiby3k 
Please follow the template for issues and provide ALL informations asked. The issue cannot be processed without it. The information provided will allow the person working on the issue to "duplicate" your device and work on it.
Thanx
@PipoCanaja PipoCanaja
