### ISSUE TITLE
Ignore stack port state for non stacked Huawei VRP devices

### ISSUE THREAD

**Issue by pubyun** [librenms/librenms#9918]
the device is not stacked, and there is alert.

is it caused by commit e17f47a329 "Added VRP stack member and ports discovery (#9891)"?

Severity: critical
Timestamp: 2019-03-06 01:10:29
Unique-ID: 3828
Rule:  State Sensor Critical  Faults:
 1: sysObjectID = .1.3.6.1.4.1.2011.2.23.340; sysDescr = S6720-30C-EI-24S-AC
Huawei Versatile Routing Platform Software
VRP (R) software,Version 5.170 (S6720 V200R011C10SPC600)
Copyright (C) 2007 Huawei Technologies Co., Ltd.; location_id = 2; sensor_id = 17763; sensor_oid = .1.3.6.1.4.1.2011.5.25.183.1.21.1.5.0.0; sensor_descr = Stack Port 0.0 Status; state_descr = Down;
 2: sysObjectID = .1.3.6.1.4.1.2011.2.23.340; sysDescr = S6720-30C-EI-24S-AC
Huawei Versatile Routing Platform Software
VRP (R) software,Version 5.170 (S6720 V200R011C10SPC600)
Copyright (C) 2007 Huawei Technologies Co., Ltd.; location_id = 2; sensor_id = 17764; sensor_oid = .1.3.6.1.4.1.2011.5.25.183.1.21.1.5.0.1; sensor_descr = Stack Port 0.1 Status; state_descr = Down; 
Alert sent to:

**Comment by PipoCanaja** [comment]
Hi @pubyun 
That is perfectly correct. Unfortunately, I did not find any variable available to validate if the device is stacked or not, which means we need to code it another way (instead of YAML as it is done now). Until then, it is better to have the information (and flag it as ignorable for non stacked devices) than having nothing. 
This issue will be corrected in the next few weeks.
PipoCanaja

**Comment by PipoCanaja** [comment]
@pubyun : Patch is here : https://github.com/librenms/librenms/pull/9925 
Feel free to test it. 

The idea is :
- During the discovery, if more than 1 device is seen, then the state will have a "critical" value for stack port "down". Else, the down state will be "unkown" which will ensure no alerting takes place.
- If a stack-port goes down, the polling will trigger the sensor alert if state is "critical" (so a real stack) and not if device is alone. 
- if both port-stack are down during a discovery, then the device will be discovered as standalone. This  cannot be avoided as far as I see it with current vrp MIB.

**Comment by PipoCanaja** [comment]
Hi @pubyun 
The patch fixing this is now committed. You can run "./daily.sh" and redicover all your huawei devices (or wait for the auto discovery to occur) and the issue will be gone. 
@PipoCanaja
