### ISSUE TITLE
The Location column in Alerts

### ISSUE THREAD

**Issue by ArturLesny** [librenms/librenms#9927]
In the list of devices, apart from the device name (most often the IP address and System Name), the assigned location is given, while in Alerts -> Notifications the Hostname is given (usually only the IP address), which does not always indicate for which device it applies.
Maybe it's worth adding the Location column in Alerts.

**Comment by laf** [comment]
This issue has been closed as it isn't classed as anew device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Comment by laf** [comment]
Out of interest, why did you open this issue when all the default templates say not to? I'd like to understand what happened so we can stop users creating issues here that belong on the community forum.
