### ISSUE TITLE
New Device: Cisco WAP371 missing CPU, Memory, and wireless client info

### ISSUE THREAD

**Issue by Chris-GNS** [librenms/librenms#9931]
I have added the Cisco WAP371 device but I'm missing CPU, Memory, and wireless client count.
The device is showing up as a Cisco Small Business device but it would be nice to have the information above.

Please let me know if I need to post more information.

Discovery
https://p.libren.ms/view/e6fb64cd

Poller
https://p.libren.ms/view/c283c421

SNMPBulkWalk
https://p.libren.ms/view/b9dbeda2

Thank you,
Chris Burt

**Comment by spencerbutler** [comment]
The following PR was submitted for this request.
[lnms-9931 - added support for ciscosb_wap371-a-k9](https://github.com/librenms/librenms/pull/9974)
