### ISSUE TITLE
Riello UPS

### ISSUE THREAD

**Issue by JohnnySSH** [librenms/librenms#9949]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20
[poller-rielloups-1.optiplex-networks.com.txt](https://github.com/librenms/librenms/files/2963361/poller-rielloups-1.optiplex-networks.com.txt)
[discovery-rielloups-1.optiplex-networks.com.txt](https://github.com/librenms/librenms/files/2963362/discovery-rielloups-1.optiplex-networks.com.txt)

).
- [X] Please provide as much detail as possible.

MIB files can be downloaded here: https://www.riello-ups.com/uploads/file/136/1136/MIBs.zip

The UPS uses the Netman 204 network card.

- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Links above

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by JohnnySSH** [comment]
[generic-rielloups-1.optiplex-networks.com.snmpwalk.txt](https://github.com/librenms/librenms/files/2963388/generic-rielloups-1.optiplex-networks.com.snmpwalk.txt)

Extension .txt wasn't added in the debug file for snmpwalk so couldn't upload - please find it here!

**Comment by PipoCanaja** [comment]
Hi,
A PR is submitted. You can test it and give us feedback.
PipoCanaja

**Comment by JohnnySSH** [comment]
Thanks PipoCanaja

This is what I get when running the git-apply script:

./scripts/github-apply 9962
Skipped patch 'html/images/os/riello.png'.
<stdin>:58: trailing whitespace.
    
<stdin>:69: trailing whitespace.
-- RPS S.p.A enterprise MIB definition
<stdin>:70: trailing whitespace.

<stdin>:71: trailing whitespace.
-- Copyright (c) RPS S.p.A.
<stdin>:72: trailing whitespace.
-- Version: 1.0 by Michele Marcon
Checking patch includes/definitions/riello.yaml...
Checking patch mibs/riello/RIELLO-MIB...
Checking patch mibs/riello/RIELLOMDU-MIB...
Checking patch mibs/riello/RIELLOMTS-MIB...
Checking patch mibs/riello/RIELLOUPS-MIB...
Checking patch mibs/riello/SENSORTRAP-MIB...
error: mibs/riello/SENSORTRAP-MIB: already exists in working directory
Checking patch tests/data/riello.json...
Checking patch tests/snmpsim/riello.snmprec...

**Comment by JohnnySSH** [comment]
I removed the mibs/riello dir and re-ran the script. Now I am seeing more information under health. 

It needs a little time to produce data so will report back in a few hours.

**Comment by JohnnySSH** [comment]
It seems to be ok. All the data is there but the image is still shown as Generic.

**Comment by PipoCanaja** [comment]
It seems that the patch did not apply correctly to your instance. The image was not loaded. The image will be there when the feature will be merged. 
Please note that you'll need to remove the patch to get your librenms instance updated properly.

**Comment by JohnnySSH** [comment]
Thanks. When I update next time I'll remove the patch before hand :-)
