### ISSUE TITLE
HikVision DS-2CD2185FWD-I

### ISSUE THREAD

**Issue by JohnnySSH** [librenms/librenms#9950]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here (http://docs.librenms.org/Support/FAQ/#faq20).

[discovery-cctv3.optiplex-networks.com.txt](https://github.com/librenms/librenms/files/2963394/discovery-cctv3.optiplex-networks.com.txt)

[poller-cctv3.optiplex-networks.com.txt](https://github.com/librenms/librenms/files/2963402/poller-cctv3.optiplex-networks.com.txt)

[generic-cctv3.optiplex-networks.com.snmpwalk.txt](https://github.com/librenms/librenms/files/2963408/generic-cctv3.optiplex-networks.com.snmpwalk.txt)

- [X] Please provide as much detail as possible.

Camera is 4k variant : https://www.hikvision.com/en/Products/Network-Camera/EasyIP-3.0/8MP/DS-2CD2185FWD-I(S)

- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by kkrumm1** [comment]
Please don’t post anything from observium we need separation from a licensed product. Will reopen once any from observium is removed.

Thank you

**Comment by JohnnySSH** [comment]
The links are from Librenms. The only reason that I mentioned Observium is that I tried the MIB's out which of course didn't work.

The captures are all stock however. Sorry for the misunderstanding!

**Comment by kkrumm1** [comment]
Yes I understand but we can’t have any mentions of it. 

Kevin

> On Mar 13, 2019, at 6:09 PM, JohnnySSH <notifications@github.com> wrote:
> 
> The links are from Librenms. The only reason that I mentioned Observium is that I tried the MIB's out which of course didn't work.
> 
> The captures are all stock however. Sorry for the misunderstanding!
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 










CONFIDENTIALITY NOTICE: This email & attached documents may 
contain confidential information. All information is intended only for the 
use of the named recipient. If you are not the named recipient, you are not 
authorized to read, disclose, copy, distribute or take any action in 
reliance on the information and any action other than immediate delivery to 
the named recipient is strictly prohibited. If you have received this email 
in error, do not read the information and please immediately notify sender 
by telephone to arrange for a return of the original documents. If you are 
the named recipient you are not authorized to reveal any of this 
information to any other unauthorized person. If you did not receive all 
pages listed or if pages are not legible, please immediately notify sender 
by phone.

**Comment by JohnnySSH** [comment]
I removed the mention :-)

**Comment by kkrumm1** [comment]
Thank you

**Comment by JohnnySSH** [comment]
Apologies for that!

**Comment by spencerbutler** [comment]
The accompanying files have been verified.

This has been requested several times over the years, and never implemented. The SNMP implementation by the vendor is beyond poor. I'll see if I can at least get the device recognized and branded.

**Comment by spencerbutler** [comment]
PR https://github.com/librenms/librenms/pull/9980 has been submitted to fix this issue.

**Comment by JohnnySSH** [comment]
Just some feedback here: the device gets recognized and branded. CPU and Memory usage are showing up. There isn't anything else though like network or any other camera specific features... it might just be because the vendor hasn't implemented them so can't really comment.

Thanks for getting the device this far :-)

**Comment by spencerbutler** [comment]
@JohnnySSH Yeah, the device doesn't expose much at all via SNMP.

**Comment by kkrumm1** [comment]
can this be closed?

**Comment by JohnnySSH** [comment]
From my end everything is fine so I will say yes :-)

**Comment by kkrumm1** [comment]
Ok looks like the PR got as much you can get out of the camera. I’m closing this out.
