### ISSUE TITLE
New Device: Eaton 5P 1150

### ISSUE THREAD

**Issue by tocks53** [librenms/librenms#9956]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

https://p.libren.ms/view/87ad8500

https://p.libren.ms/view/924d8342

https://p.libren.ms/view/c1db7151

Thanks a lot

**Comment by PipoCanaja** [comment]
Hi
Please provide the snmpwalk as requested. Without it we cannot proceed.

**Comment by tocks53** [comment]
Sorry an error.

https://p.libren.ms/view/c1db7151

**Comment by PipoCanaja** [comment]
> 
> 
> Sorry an error.
> 
> https://p.libren.ms/view/c1db7151

Still wrong. This one is the Dell, not the Eaton ...

**Comment by PipoCanaja** [comment]
@tocks53 Any chance you could provide this ?

**Comment by PipoCanaja** [comment]
(we'll reopen this when the data is provided)

**Comment by tocks53** [comment]
Sorry for the time.

https://p.libren.ms/view/82b5a622
https://p.libren.ms/view/e267a06f
https://p.libren.ms/view/70104c00

`[root@Serv-Librenms-3 librenms]# snmpbulkwalk -OUneb -v2c -c public 192.168.0.200 .  | ./pbin.sh
Paste endpoint: https://p.libren.ms/api/create
title:
name: root
private: 1
expire: 0
https://p.libren.ms/view/70104c00
[root@Serv-Librenms-3 librenms]#
`

But the snmpbulkwalk is empty.

**Comment by PipoCanaja** [comment]
Lets do it step by step. We remove pbin for now and check that you get a bunch of lines in your terminal. When this happen, redo it with ``` | ./pbin.sh ```. 
First, we remove bulk. 
```snmpwalk -OUneb -v2c -c public 192.168.0.200 .```
If still not, we try in snmp v1
```snmpwalk -OUneb -v1 -c public 192.168.0.200 .```

If it succeeds with v1, check in the config of the device is v2 is enabled. 

Let see what result we get with this.

**Comment by PipoCanaja** [comment]
(Also, check the community in the configuration of course)

**Comment by tocks53** [comment]
[root@Serv-Librenms-3 ~]# snmpwalk -OUneb -v2c -c public 192.168.0.200 .
.1.3.6.1.6.3.18.1.1.1.8.112.117.98.108.105.99.117.115.101.114 = No more variables left in this MIB View (It is past the end of the MIB tree)
[root@Serv-Librenms-3 ~]#

snmpwalk -OUneb -v1 -c public 192.168.0.200 .    it's ok

https://p.libren.ms/view/998f2eb8

Thank's a lot

**Comment by laf** [comment]
These are already supported and your discovery output shows this.

**Comment by PipoCanaja** [comment]
@tocks53 Anything you did expect to improve what you actually have ?

**Comment by tocks53** [comment]
How do you see that it's managed in the discover?

I have an alert on librenms UPS Inverter Status : Inverter Off
But i have no alert in the gui of the UPS

**Comment by laf** [comment]
```
Attempting to initialize OS: eaton-mgeups
```

Do you see UPS inverter status in the webui at all?
