### ISSUE TITLE
New Device: Dell UPS Tower 1000W HV

### ISSUE THREAD

**Issue by tocks53** [librenms/librenms#9957]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ x] Please provide as much detail as possible.
- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

https://p.libren.ms/view/830d8673
https://p.libren.ms/view/52ac5581
https://p.libren.ms/view/e843eb07

Thanks a lot

**Comment by PipoCanaja** [comment]
I opened a PR #9961 that will enable RFC1628 UPS mib support. That will extend a lot of sensors. Looking at the mib, it seems that there is nothing else in the SNMP replies from the devices that we could graph.
