### ISSUE TITLE
New Device: BTI 7000

### ISSUE THREAD

**Issue by czilian** [librenms/librenms#9964]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by czilian** [comment]
[bti7000support.zip](https://github.com/librenms/librenms/files/2969436/bti7000support.zip)

ZIP contains discovery/poll/bulkwalk/mibs/device logo
suggesting to call new OS bti7xxx

**Comment by czilian** [comment]
Your help is highly appreciated. Failed to do it myself because of the devices modular structure. Thank you.

**Comment by PipoCanaja** [comment]
I would suggest juniper-bti as OS name, easier to identify.

**Comment by spencerbutler** [comment]
Currently evaluating. All provided data has been validated.

**Comment by spencerbutler** [comment]
The data files have been verified and PR https://github.com/librenms/librenms/pull/9979 is in progress.

**Comment by spencerbutler** [comment]
I'm still working on this, bit by bit.

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-device-bti-7000/11627/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11627
