### ISSUE TITLE
New device: Dell Networking S4128F-ON

### ISSUE THREAD

**Issue by MrXermon** [librenms/librenms#9966]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

```
Dell EMC Networking OS10 Enterprise
Copyright (c) 1999-2018 by Dell Inc. All Rights Reserved.
OS Version: 10.4.0E(R3)
Build Version: 10.4.0E(R3.233)
Build Time: 2018-03-30T18:05:41-0700
System Type: S4128F-ON
Architecture: x86_64
Up Time: 1 week 00:28:27
```

./discovery.php -h HOSTNAME -d | ./pbin.sh
> https://p.libren.ms/view/1332780f

./poller.php -h HOSTNAME -r -f -d | ./pbin.sh
> https://p.libren.ms/view/448889f6

snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh
> https://p.libren.ms/view/e76c4fcc

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by spencerbutler** [comment]
@MrXermon Thanks for the submission. Upon reviewing your files, your snmpwalk is not complete. Please resubmit one that includes SNMPv2-MIB::sysObjectID.0 and SNMPv2-MIB::sysObjectID.0. The command listed in your report *should* have provided that.

**Comment by MrXermon** [comment]
@spencerbutler That's interesting. I asume that the SNMP implementation in the specific firmware version is a bit buggy because a few minutes after i issued the command, the whole snmp daemon crashed. I'm currently updating the firmware on the devices to the latest version and will update the files once again afterwards.

**Comment by MrXermon** [comment]
Now once again all the data with the latest firmware version (10.4.3E).

```
Dell EMC Networking OS10 Enterprise
Copyright (c) 1999-2019 by Dell Inc. All Rights Reserved.
OS Version: 10.4.3E
Build Version: 10.4.3E.132
Build Time: 2019-02-24T10:36:16-0800
System Type: S4128F-ON
Architecture: x86_64
Up Time: 00:03:21
```

./discovery.php -h HOSTNAME -d | ./pbin.sh
https://p.libren.ms/view/144ef27f

./poller.php -h HOSTNAME -r -f -d | ./pbin.sh
https://p.libren.ms/view/7b3235b6

snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME . | ./pbin.sh
This output only created a MySQL Error at the pastebin instance (Error Number: 2006: MySQL server has gone away), therefore i uploaded it to my instance.
https://paste.level66.network/?659635f9e0f920f8#EQhy4MNFFdCMM64pdauWJ7MfcpfFeaaHwHlXu/Jj79Q=

The Dell OS10 MIBs can be downloaded using the following link: https://www.force10networks.com/CSPortal20/Software/software/OS10_Enterprise_MIB_10.4.3.0.zip

**Comment by spencerbutler** [comment]
Silly bugs. Thanks for resubmitting. From a quick glance, that snmpwalk looks good, and discovery actually found stuff this time.

**Comment by spencerbutler** [comment]
@MrXermon It looks like this device is already fully supported in Librenms. Can you confirm that, after upgrading the firmware, it is working as expected? Is there anything else that needs to be addressed before I close this issue?

**Comment by MrXermon** [comment]
@spencerbutler I'm wondering because the hardware does not show as networking hardware and the logo of dell is missing.

**Comment by spencerbutler** [comment]
@MrXermon I'll look into the branding issue, and update you once a fix is in place.

**Comment by miguelhernandez-work** [comment]
i'm jealous this issue is getting attention but not #9603 .
Any chance you can look at that one after?

I'm finding Dell OS10 is terrible.

**Comment by t0i** [comment]
i'm jealous this issue is getting attention but not #9603 .
Any chance you can look at that one after?

I'm finding Dell OS10 is terrible.

**Comment by spencerbutler** [comment]
@MrXermon PR #10011 has been submitted to address this. If you can, test that out and see what you think (instructions in the PR for early testing).

**Comment by MrXermon** [comment]
@t0i Yes, OS10 is definitly terrible...

I've deleted the switches in LibreNMS and readded them and everything looks good from my point of view.

**Comment by spencerbutler** [comment]
#10011 is slated for the 1.51 release. Can this issue be closed?

**Comment by MrXermon** [comment]
Staged for 1.51
