### ISSUE TITLE
Dantel Webmon LP Sensors

### ISSUE THREAD

**Issue by smiles1969** [librenms/librenms#9972]
Webmon support currently bind slots statically to sensors which is not correct if you don't have the same card/slots usage. 

**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

/opt/librenms/includes/definitions/discovery/webmon.yaml:
https://pastebin.com/p1tBkaXn

Discovery
https://p.libren.ms/view/35062b11

Poller
https://p.libren.ms/view/35753ba1

Bulkwalk:
https://p.libren.ms/view/5ffae66b

**Comment by smiles1969** [comment]
Sensors discover correctly, and pull correct values on discover.

After first poll, the values go to 0.

**Comment by PipoCanaja** [comment]
Need to change existing incomplete Webmon support.

**Comment by PipoCanaja** [comment]
PR is there. #9977
