### ISSUE TITLE
Vlan numbers not available in API for tagged ports

### ISSUE THREAD

**Issue by marvink87** [librenms/librenms#9988]
In the web interface the VLAN numbers are available for a tagged port but they are not available in the API. This does work for a untagged port.

Ports below belong to Arista EOS devices.

### Example of untagged port which returns the VLAN in the ifVlan field:
> {
>     "status": "ok",
>     "port": [
>         {
>             "port_id": 1513,
>             "device_id": 23,
>             "port_descr_type": "cust",
>             "port_descr_descr": "#SECRET#",
>             "port_descr_circuit": null,
>             "port_descr_speed": null,
>             "port_descr_notes": "#SECRET#",
>             "ifDescr": "Ethernet19",
>             "ifName": "Ethernet19",
>             "portName": null,
>             "ifIndex": 19,
>             "ifSpeed": 1000000000,
>             "ifConnectorPresent": "true",
>             "ifPromiscuousMode": "false",
>             "ifHighSpeed": 1000,
>             "ifOperStatus": "up",
>             "ifOperStatus_prev": "down",
>             "ifAdminStatus": "up",
>             "ifAdminStatus_prev": "up",
>             "ifDuplex": "fullDuplex",
>             "ifMtu": 9214,
>             "ifType": "ethernetCsmacd",
>             "ifAlias": "Cust: #SECRET#",
>             "ifPhysAddress": "#SECRET#",
>             "ifHardType": null,
>             "ifLastChange": 3559760482,
>             **"ifVlan": "312",**
>             "ifTrunk": null,
>             "ifVrf": 0,
>             "counter_in": null,
>             "counter_out": null,
>             "ignore": 0,
>             "disabled": 0,
>             "detailed": 0,
>             "deleted": 0,
>             "pagpOperationMode": null,
>             "pagpPortState": null,
>             "pagpPartnerDeviceId": null,
>             "pagpPartnerLearnMethod": null,
>             "pagpPartnerIfIndex": null,
>             "pagpPartnerGroupIfIndex": null,
>             "pagpPartnerDeviceName": null,
>             "pagpEthcOperationMode": null,
>             "pagpDeviceId": null,
>             "pagpGroupIfIndex": null,
>             "ifInUcastPkts": 2476919803,
>             "ifInUcastPkts_prev": 2476919803,
>             "ifInUcastPkts_delta": 0,
>             "ifInUcastPkts_rate": 0,
>             "ifOutUcastPkts": 2406254911,
>             "ifOutUcastPkts_prev": 2406254911,
>             "ifOutUcastPkts_delta": 0,
>             "ifOutUcastPkts_rate": 0,
>             "ifInErrors": 0,
>             "ifInErrors_prev": 0,
>             "ifInErrors_delta": 0,
>             "ifInErrors_rate": 0,
>             "ifOutErrors": 0,
>             "ifOutErrors_prev": 0,
>             "ifOutErrors_delta": 0,
>             "ifOutErrors_rate": 0,
>             "ifInOctets": 2043130915598,
>             "ifInOctets_prev": 2043130915598,
>             "ifInOctets_delta": 0,
>             "ifInOctets_rate": 0,
>             "ifOutOctets": 999904761634,
>             "ifOutOctets_prev": 999904749782,
>             "ifOutOctets_delta": 11852,
>             "ifOutOctets_rate": 40,
>             "poll_time": 1552897987,
>             "poll_prev": 1552897690,
>             "poll_period": 297
>         }
>     ],
>     "count": 1
> }

### Example of tagged port:
config:
> interface Ethernet3
>    description Cust: #SECRET#
>    switchport trunk allowed vlan 10,20-25,100,114,351
>    switchport mode trunk

API results:
> {
>     "status": "ok",
>     "port": [
>         {
>             "port_id": 1497,
>             "device_id": 23,
>             "port_descr_type": "cust",
>             "port_descr_descr": "#SECRET#",
>             "port_descr_circuit": null,
>             "port_descr_speed": null,
>             "port_descr_notes": "#SECRET#",
>             "ifDescr": "Ethernet3",
>             "ifName": "Ethernet3",
>             "portName": null,
>             "ifIndex": 3,
>             "ifSpeed": 10000000000,
>             "ifConnectorPresent": "true",
>             "ifPromiscuousMode": "false",
>             "ifHighSpeed": 10000,
>             "ifOperStatus": "up",
>             "ifOperStatus_prev": "down",
>             "ifAdminStatus": "up",
>             "ifAdminStatus_prev": "up",
>             "ifDuplex": "fullDuplex",
>             "ifMtu": 9214,
>             "ifType": "ethernetCsmacd",
>             "ifAlias": "Cust: #SECRET#",
>             "ifPhysAddress": "#SECRET#",
>             "ifHardType": null,
>             "ifLastChange": 3600702889,
>             "ifVlan": "1",
>             "ifTrunk": null,
>             "ifVrf": 0,
>             "counter_in": null,
>             "counter_out": null,
>             "ignore": 0,
>             "disabled": 0,
>             "detailed": 0,
>             "deleted": 0,
>             "pagpOperationMode": null,
>             "pagpPortState": null,
>             "pagpPartnerDeviceId": null,
>             "pagpPartnerLearnMethod": null,
>             "pagpPartnerIfIndex": null,
>             "pagpPartnerGroupIfIndex": null,
>             "pagpPartnerDeviceName": null,
>             "pagpEthcOperationMode": null,
>             "pagpDeviceId": null,
>             "pagpGroupIfIndex": null,
>             "ifInUcastPkts": 88484064841,
>             "ifInUcastPkts_prev": 88484014730,
>             "ifInUcastPkts_delta": 50111,
>             "ifInUcastPkts_rate": 171,
>             "ifOutUcastPkts": 90479397321,
>             "ifOutUcastPkts_prev": 90479345880,
>             "ifOutUcastPkts_delta": 51441,
>             "ifOutUcastPkts_rate": 176,
>             "ifInErrors": 1,
>             "ifInErrors_prev": 1,
>             "ifInErrors_delta": 0,
>             "ifInErrors_rate": 0,
>             "ifOutErrors": 0,
>             "ifOutErrors_prev": 0,
>             "ifOutErrors_delta": 0,
>             "ifOutErrors_rate": 0,
>             "ifInOctets": 64754875208438,
>             "ifInOctets_prev": 64754837194013,
>             "ifInOctets_delta": 38014425,
>             "ifInOctets_rate": 129742,
>             "ifOutOctets": 73735350489920,
>             "ifOutOctets_prev": 73735332296392,
>             "ifOutOctets_delta": 18193528,
>             "ifOutOctets_rate": 62094,
>             "poll_time": 1552898280,
>             "poll_prev": 1552897987,
>             "poll_period": 293
>         }
>     ],
>     "count": 1
> }

**Comment by kkrumm1** [comment]
Sorry but This issue has been closed as it isn't classed as anew device request. Please read the new issue template.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
