### ISSUE TITLE
Make vlans of tagged port available through API

### ISSUE THREAD

**Issue by marvink87** [librenms/librenms#9992]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

In the web interface the VLAN numbers are available for a tagged port but they are not available in the API. This does work for a untagged port. I'm currently testing with Arista EOS devices. I didn't attach an snmpwalk as I don't think the problem is in the data collection.

### Example of untagged port which returns the VLAN in the ifVlan field:
https://pastebin.com/Aq8T2w5n

### Example of tagged port:
config:
> interface Ethernet3
>    description Cust: #SECRET#
>    switchport trunk allowed vlan 10,20-25,100,114,351
>    switchport mode trunk

API results:
https://pastebin.com/XCnPu0KW

The data is available in the database:
```
MariaDB [librenms]> SELECT port_id,ifVlan FROM ports WHERE port_id=1497;                        
+---------+--------+
| port_id | ifVlan |
+---------+--------+
|    1497 | 1      |
+---------+--------+
1 row in set (0.00 sec)

MariaDB [librenms]> SELECT port_vlan_id,port_id,vlan FROM ports_vlans WHERE port_id=1497;
+--------------+---------+------+
| port_vlan_id | port_id | vlan |
+--------------+---------+------+
|          661 |    1497 |   10 |
|          668 |    1497 |   20 |
|          675 |    1497 |   21 |
|          694 |    1497 |   22 |
|          713 |    1497 |   23 |
|          719 |    1497 |   24 |
|          725 |    1497 |   25 |
|          757 |    1497 |  100 |
|          763 |    1497 |  114 |
|          784 |    1497 |  351 |
+--------------+---------+------+
10 rows in set (0.00 sec)
```

**Comment by kkrumm1** [comment]
Is this a new device request?

**Comment by marvink87** [comment]
From #9988 I understood I needed to open the issue as a new device request. Did I misunderstand?

**Comment by kkrumm1** [comment]
Yes, This is ONLY for new device request. From the looks of this, you want to do a feature request.
Do that here ->https://community.librenms.org/c/feature-requests

**Comment by marvink87** [comment]
Alright, I'll post there.

**Comment by kkrumm1** [comment]
Thank you for your understanding and corporation.
